### ISSUE TITLE
Error: QWeb2: Template 'accountReports.buttons' not found 

### ISSUE THREAD

**Issue by AsmaAl-Haddar** [odoo/odoo#72390] opened 2021-06-21 02:50 UTC
Hello all,
We are try to solve this error  {I replaced my website name by webpage.com}
Error:

Traceback:
Error: QWeb2: Template 'accountReports.buttons' not found
    at Object.exception (https://webpage.com/web/content/318-668acd9/web.assets_common.js:3692:7)
    at Engine._render (https://webpage.com/web/content/318-668acd9/web.assets_common.js:3737:103)
    at Engine.render (https://webpage.com/web/content/318-668acd9/web.assets_common.js:3733:151)
    at Class.renderButtons (https://webpage.com/web/content/326-7a9b853/web.assets_backend.js:3713:413)
    at Class.update_cp (https://webpage.com/web/content/326-7a9b853/web.assets_backend.js:3696:1115)
    at Class.render (https://webpage.com/web/content/326-7a9b853/web.assets_backend.js:3697:585)
    at https://webpage.com/web/content/326-7a9b853/web.assets_backend.js:3696:392

Thanks in advance,

**Comment by pedrobaeza** [comment] 2021-06-21 06:20
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Closed** 2023-04-07 14:06 UTC
Labels: Need information
