### ISSUE TITLE
[9.0] There is no demo data available when user installs the "Asset" app in the system

### ISSUE THREAD

**Issue by jni-odoo** [odoo/odoo#9365] opened 2015-11-02 12:07 UTC
Follow the below step to check the issue -

(1) Create a Database with demo data

(2) Install the module "Asset"

(3) Go to menu "Adviser -> Assets" there is nothing available , or go to Configutation -> Asset Types here  also nothing is available..

Thanks..

Nikunj Jani (Odoo India)

**Comment by mge-odoo** [comment] 2015-11-25 15:48
Hi Nikunj. We are aware of this and working on a solution. Thanks for your feedback.

**Comment by Yenthe666** [comment] 2016-05-24 06:45
Hi @mge-odoo,

Any update on this one?

**Comment by mge-odoo** [comment] 2016-05-24 08:40
Hi @Yenthe666 
We actually looked at it some times ago but it is way more complex that it seems to be because of CoA. The resolution of it is still in discussion but no easy solution has been found yet.

**Comment by mge-odoo** [comment] 2018-01-15 10:55
@qdp-odoo maybe more linked to your team?

**Comment by qdp-odoo** [comment] 2018-01-15 13:09
@lap-odoo this is a feedback to consider... but not a bug report, so I'm closing this issue

**Closed by qdp-odoo** 2018-01-15 13:09 UTC
Labels: 9.0, Accounting

**Comment by lap-odoo** [comment] 2018-01-15 16:25
@qdp-odoo Yep, added in task 33755
