### ISSUE TITLE
[16.0] account_edi: bug with _decode_attachment and mime type check

### ISSUE THREAD

**Issue by salvorapi** [odoo/odoo#150382] opened 2024-01-22 11:06 UTC
**Impacted versions**: 16.0

https://github.com/odoo/odoo/blob/a5a36f2e3f179187484bbadb581d18db0d127178/addons/account_edi/models/account_edi_format.py#L314

### Steps to reproduce:

You have to try to import a vendor bill from XML with user demo (not with admin) and :

- or a file XML name with VENDOR_BILL.XML (all upper case)
- or a file XML with utf8 content

### Current behavior:

The invoice is not imported with user demo and with user admin yes.

### Expected behavior:

The invoice is not imported.

@lordkrandel

**Comment by lordkrandel** [comment] 2024-03-22 07:17
@salvorapi It works like this by design. 
We don't consider it a bug so I'm explaining the reasons why here and close this issue.
If you have further feedback or errors about this, in order to handle it better, please go through the Odoo feedback and ticket system, or contact your Partner Manager of reference.

---

The vendor bills you import MUST have the correct filename, like reported in the official [Tax Agency specifications](https://www.agenziaentrate.gov.it/portale/documents/20143/5747438/Allegato+A+-+Specifiche+tecniche+vers+1.8_18012024.pdf/1ea6143f-0502-1031-5837-6d4589076fae) 

![image](https://github.com/odoo/odoo/assets/1665365/23a0a267-076e-4119-9dc2-c571d5ad65a8)

The filenames are checked against a Regular Expression to determine whether we are able to decode the file or not.
We suppose that if you're uploading a FatturaPA file, you either downloaded it from the Tax Agency or saved from another ERP that has sent it to the Agenzia. We don't encourage people to make up XML files and try to import them.

Here is the regex (notice the case-insensitive extension):
Odoo 15: https://github.com/odoo/odoo/blob/15.0/addons/l10n_it_edi/models/account_edi_format.py#L325
Odoo 16: https://github.com/odoo/odoo/blob/16.0/addons/l10n_it_edi/models/account_edi_format.py#L385
Odoo 17: https://github.com/odoo/odoo/blob/17.0/addons/l10n_it_edi/models/ir_attachment.py#L12

Furthermore, the code you specify is not relevant, since the `attachment.name` is not the only thing that's checked, but there's also the MIME type of the attachment check just a couple lines below, which the browser identifies case-insensitively as XML either for `.xml` or `.XML`.

Anyway, thanks for your time!

**Closed by lordkrandel** 2024-03-22 07:17 UTC

**Comment by salvorapi** [comment] 2024-03-22 08:14
@lordkrandel I think that user experience is more important than technical specifications. And Odoo has made a manifesto of this. Our task must be to reconcile both aspects.

I hope that on this front we are in agreement.

Salvo.

**Comment by lordkrandel** [comment] 2024-03-22 10:31
@salvorapi 
Sorry, I didn't mean to invalidate the requirement.
Your feedback is always welcome and valuable. We're still addressing bugs you pointed out, like the import of customer invoices and the company-to-company import issue.

I really mean you should talk about this with functional people, who actually do not read Github issues.

We've been busy working on several fronts for the Italian localizations and there are priorities. i.e. Internal Reverse Charge, keeping up the documentation, Lettere d'Intento, other TDxx implementations for import.

By looking at the filename, we avoid parsing the files to determine what they are. It's something we do on all localizations, so there's also a general product idea behind that.

I heard you have a new Partner Manager (Stefano Biglieri) that should handle the `l10n_it_edi` side. I'll link him this discussion. My hope is that the company won't let me and you alone in handling issues that are out of my scope at the moment.
