### ISSUE TITLE
Odoo V14 Database Restore Issues

### ISSUE THREAD

**Issue by Henrijo** [odoo/odoo#95717] opened 2022-07-10 20:24 UTC
Hi Everyone 

I got an issue by working with odoo v14. When I'm about to restore db it displayed that the db already exists . I'm struggling to fix this issue .I'm unable to restore my customer db after new flesh odoo installation .help me fix that issue for good 
regards,

**Comment by afmipy** [comment] 2022-07-10 21:42
Hello @Henrijo 

In what manner you tried to restore the database? If you tried using the interface, did you make sure that you change the name of  the database? Maybe a database is already created with the same name.

If you are using the command lines to restore the database, you can show the databases already existing using these commands

1) Use postgres user
sudo su postgres
2) Enter shell 
psql
3) Show databases list
\l+

Then maybe you should delete the database with the same name that you are using , or restore by an other database name.

**Comment by Henrijo** [comment] 2022-07-11 14:29
Hi afmipy
I've checked I don't have a db which get this name

**Comment by niyasraphy** [comment] 2023-05-22 07:03
hi @Henrijo ,
may be you checked from the db manager page ? in case if there is some db filter applied in your instance, you wont see all the db list in the db manager page.

as the message says, there is a db exists in the given name, try with different name and see how it goes.
feel free to close the issue as this is not a bug.
thanks

**Closed** 2023-05-23 13:09 UTC
