### ISSUE TITLE
Payment Server Error

### ISSUE THREAD

**Issue by guinhares** [odoo/odoo#52544] opened 2020-06-05 20:56 UTC
Impacted versions: Odoo12

Steps to reproduce:
Odoo 12 is showing this error on the portal, when the payment will be made, can someone help me?

Video/Screenshot link (optional):
![Error](https://user-images.githubusercontent.com/66495194/83921889-bccf9180-a755-11ea-9e02-03b26fffa92c.png)

**Comment by pedrobaeza** [comment] 2020-06-05 22:11
Which is the payment carrier? Do you have latest source code?

**Comment by guinhares** [comment] 2020-06-13 20:33
Hi, sorry about delay response! i'm still testing

**Comment by Yenthe666** [comment] 2020-07-27 14:18
Hi there,

Since there has been no feedback since our last question I'm closing this issue.
Don't hesitate to comment back with extra information / reproducable steps and we'll be happy to reopen this issue.

Regards,
Yenthe

**Closed by Yenthe666** 2020-07-27 14:18 UTC
Labels: 12.0, Need information, Sales
