### ISSUE TITLE
[13.0]CRM: AttributeError: 'crm.lead' object has no attribute '_compute_probabilities'

### ISSUE THREAD

**Issue by KapilPatel-KP** [odoo/odoo#42634] opened 2020-01-02 17:04 UTC
Impacted versions:

1. Odoo 13.0

**Current behavior:**

![Screenshot](https://user-images.githubusercontent.com/24518821/71680148-5a8df180-2daf-11ea-96a3-09f22523bc0e.png)

**Expected behavior:**

1. No Traceback

**Video/Screenshot link (optional):**

![Peek 2020-01-02 22-25](https://user-images.githubusercontent.com/24518821/71680378-f1f34480-2daf-11ea-8a85-4655896dc39b.gif)

**Comment by pedrobaeza** [comment] 2020-01-02 17:05
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by sswapnesh** [comment] 2020-01-02 17:24
Reproduced on http://817282-13-0-4d62a9.runbot21.odoo.com/web#id=32&action=627&model=crm.lead&view_type=form&cids=&menu_id=446
![Screenshot (44)](https://user-images.githubusercontent.com/16624719/71681484-d8073100-2db2-11ea-90c9-ae104ce0bd16.png)

**Comment by sswapnesh** [comment] 2020-01-02 17:27
This has been fixed in PR https://github.com/odoo/odoo/pull/42573 at https://github.com/odoo/odoo/commit/2e41f129ee39786c8259af792635e3b0f3dbfa3d

**Comment by pedrobaeza** [comment] 2020-01-02 17:28
Then how is still reproducible in runbot?

**Comment by sswapnesh** [comment] 2020-01-02 17:30
I am able to Reproduce this on this Build 
![Screenshot (45)](https://user-images.githubusercontent.com/16624719/71681770-975be780-2db3-11ea-9b01-49a905ad3b11.png)

Maybe this Patch is not applied there.

**Comment by pedrobaeza** [comment] 2020-01-02 17:31
You can check it doing a git checkout over that commit and see if it contains the other commit.

**Comment by sswapnesh** [comment] 2020-01-02 17:35
Thanks.

This patch is not applied on the Runbot I tested https://github.com/odoo/odoo/blob/4d62a94a31c3967bfd34396a3448a3e925422634/addons/crm/models/crm_lead.py#L485

**Comment by pedrobaeza** [comment] 2020-01-02 17:36
OK, then we just need to wait. Closing this issue as solved.

**Closed by pedrobaeza** 2020-01-02 17:36 UTC
Labels: 13.0, Marketing
