### ISSUE TITLE
Pixelated fonts Wkhtmltopdf

### ISSUE THREAD

**Issue by TaiKamilla** [odoo/odoo#24229] opened 2018-04-13 16:46 UTC
Impacted versions: 11.0

Steps to reproduce: 
  1 - Install odoo certified by bitnami on the google cloud plataform.
  2 - Install Wkhtmltopdf for Debian Jessie from [here](https://github.com/odoo/odoo/wiki/Wkhtmltopdf).
  3 - Print a ticket.

Current behavior:
   Pixelated fonts on the pdf.

Expected behavior:
  Normal fonts.

Video/Screenshot link (optional):
  Sample img!
![image](https://user-images.githubusercontent.com/15035750/38747330-d1b2a832-3f4a-11e8-808a-7082c02b6a74.png)

**Comment by pedrobaeza** [comment] 2018-04-13 17:17
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot).

I'm not able to reproduce this problem in latest runbot version.

I'm closing this issue now, but if you feel this can be something reproducible in runbot with other steps, please reply adding all the additional information for reproducing the problem.

**Comment by Yenthe666** [comment] 2018-04-13 18:55
@pedrobaeza it is obvious you cannot reproduce. The user is reporting for Bitnami and Debian Jessie. Odoo is on Linux. You cannot reproduce it there so I'm reopening. Hope you agree.

**Comment by pedrobaeza** [comment] 2018-04-13 19:14
But Bitnami is not something official of Odoo. It's not the first time their images are bad configured and give these problems. They should report them, not here IMO.

**Comment by nhomar** [comment] 2018-04-13 22:38
Hello @Yenthe666 

this should be closed.

bitnami image **is not** officially supported, they should have (and have) their own support channel.

without the specific configuration supported it is almost impossible to give a proper feedback.

I will close it again (2 vs 1 @Yenthe666 ? if you think and have a stronger PoV please kindly let us know).

**Closed by nhomar** 2018-04-13 22:38 UTC

**Comment by Yenthe666** [comment] 2018-04-14 07:34
After reading the comments from you two I agree. You're both right. Thanks for the feedback.
