### ISSUE TITLE
REGRESSION: write method with wrong key now rise error in v12 just log

### ISSUE THREAD

**Issue by OmniaGit** [odoo/odoo#38182] opened 2019-10-08 11:00 UTC
Impacted versions:
V13

Steps to reproduce:
use the .write method passing a wrong key

Current behavior:
in v13 an error is raised 
  File "/home/mboscolo/workspace/v13/addons/product/models/product.py", line 323, in write
    res = super(ProductProduct, self).write(values)
  File "/home/mboscolo/workspace/v13/addons/mail/models/mail_thread.py", line 323, in write
    result = super(MailThread, self).write(values)
  File "/home/mboscolo/workspace/v13/addons/mail/models/mail_activity.py", line 679, in write
    return super(MailActivityMixin, self).write(vals)
  File "/home/mboscolo/workspace/v13/odoo/models.py", line 3397, in write
    field = self._fields[fname]
KeyError: 'KEY'

Expected behavior:
it will nice to have the v12 behaviour having only the log warning

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2019-10-08 11:13
I prefer to have the explicit error.

**Comment by Julien00859** [comment] 2019-10-08 11:33
This is not a regression, writing on unknown fields is invalid. The error is explicit and the traceback lets you know the related module.

**Comment by pedrobaeza** [comment] 2019-10-08 11:38
Thanks for the confirmation. Closing then.

**Closed by pedrobaeza** 2019-10-08 11:38 UTC
Labels: 13.0

**Comment by OmniaGit** [comment] 2019-10-08 13:31
This break all my code in the odooPLM client !!! We use to upload dictionary of values that we use widely, for different purpose.
I also prefer an explicit error, but in this case this change the behaviour that in the older version where different !!
for me it's a regression !!!
Regards,
Matteo

**Comment by pedrobaeza** [comment] 2019-10-08 13:46
But that's because that OdooPLM is not correctly build: you have to curate the information before processing it, so you must include specific Odoo version code. You will have the same problem if a field is renamed or added through versions.

**Comment by OmniaGit** [comment] 2019-10-08 13:52
The fact is that till version 12 the api **write** method accept a dictionary and the value of the dictionary that are not in the model are skipped.
in v13 the api method **write** rise and exception.

For me it's a regression

**Comment by pedrobaeza** [comment] 2019-10-08 13:54
No, it's a change of API. If the change would be done on a stable version, then you can complain about that. Now, you have to adapt to this change.

**Comment by OmniaGit** [comment] 2019-10-08 13:58
For my point of view the  api must be stable during the time, if you change the behaviour you create a new method write1 and than you put deprecate on last version ..
We strongly use com api from the most common cads, and this is the way to work.
NEVER BREAK THE OLD CODE !!

**Comment by pedrobaeza** [comment] 2019-10-08 14:06
Sorry, but this is not the case.

**Comment by OmniaGit** [comment] 2019-10-08 14:06
Thanks for your time !!

**Comment by sswapnesh** [comment] 2019-10-27 08:59
@OmniaGit  I think this commit will be reverted by https://github.com/odoo/odoo/pull/39367


Cc @Julien00859  Maybe you have more info on this as You are an Internal Employee

**Comment by pedrobaeza** [comment] 2019-10-27 10:05
I still think it's a good idea to not allow that.

**Comment by sswapnesh** [comment] 2019-10-27 10:11
But wondering why it was allowed till now (IMO Error log should be enough to correct this rather than blocking message)

**Comment by Julien00859** [comment] 2019-10-27 12:25
@sswapnesh the soon-reverted commit was only reintroducing a nice error message instead a bare `KeyError: model doesn't not have 'unkown field' key`. The warning is not going to be reintroduced.
