### ISSUE TITLE
Odoo 9 Log in internal note in crm lead

### ISSUE THREAD

**Issue by aspcsharp9** [odoo/odoo#14006] opened 2016-10-26 19:43 UTC
I have a question about option in CRM > LEAD "Log an internal note", when switch on Log an internal note and send message my followers also receive this message on email. I won't that.

In module stay: "Log an internal note which will not be sent to followers, but which can be read by users accessing this document.

Note: I won't remove this user from folower list!

Any solution?

**Comment by JKE-be** [comment] 2016-10-26 20:32
"Log an internal note" should not send email to your followers...
I cannot reproduce it ...

![image](https://cloud.githubusercontent.com/assets/4848797/19744060/1f6f8b2c-9bcc-11e6-97b9-1812acbd40bb.png)

**Comment by aspcsharp9** [comment] 2016-10-27 10:46
Hi, tnx for answer.

Several ascertainment and question...

1. When create new TASK and select Assigned to (USER 1) automatically USER 1 receive email this is OK.

2. When send message as Log an internal note USER 1 receive email.  IS IT OK? (Maybe because is Assigned to = USER 1)

3. When change Assigned to = USER 2 and send message as Log an internal note USER 1 receive email! IS IT OK?

**Comment by Yenthe666** [comment] 2017-05-30 08:49
Hi @aspcsharp9,

Thank you for your report.
Just like @JKE-be I can't reproduce this issue (on any instance) and it works fine out of the box.
Please try updating your Odoo to the latest source code or try to reproduce this on a runbot.
Closing this issue as it is no longer reproducable at our end.

Regards,
Yenthe

**Closed by Yenthe666** 2017-05-30 08:49 UTC
Labels: need informations
