### ISSUE TITLE
[16.0 CRITICAL] [Technical] Context issue in name_get, name_search

### ISSUE THREAD

**Issue by dipak-shah** [odoo/odoo#106800] opened 2022-11-29 19:26 UTC
Impacted versions: 16.0

Steps to reproduce:
**- I will go with an actual example here.**
- in the Sales order (we do have **invoice address, delivery address** columns), inherit it and pass the same additional context on both columns in any custom module.
- override the **name_get or _name_search** method in your code and try to get that context  (E.g self._context or self.env.context etc.)

Current behavior:
- We do get context only in during we get a list of dropdowns with values in the column 'Delivery Address?', but not for the INVOICE address column. even though both belong to the same object (res.partner)

Expected behavior:
- it should show the context in our methods (name_get, name_search, etc.) for both columns, not only for single columns
- I added a new dummy column of 'Invoice address' but it's working perfectly. tried for Duplicate 'Fiscal position' columns too. that also works well. not sure what's wrong with the existing INVOICE Address/Delivery address columns'

PS: it's updating a context properly on the Column level. I can see that when we hover the cursor on those columns. so it's updating but not getting into methods.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by dipak-shah** [comment] 2022-12-01 18:35
Hey Guys, Any update on this one ?

**Comment by netfxtech** [comment] 2022-12-03 11:25
You might want to post this on the help forums. 

Just to help you manage your expectations - I’d be surprised if you get any actual direction on this in less than 30 days. I only mention this because you’re asking for an update 2 days after originally creating this issue. 

I have the same issue on some models but not others. I‘ll take a look at the code when I have some time and post back if I find a solution.

**Comment by dipak-shah** [comment] 2022-12-05 16:32
@Yenthe666 @sswapnesh Could guys please have a look into this one ?

Pardon me if I'm missing or tagging you guys wrongly here.

Thank you!

**Comment by Yenthe666** [comment] 2022-12-06 13:33
Sorry but I no longer voluntarely support Odoo issues here. The reason speaks for itself: because nobody at odoo cares or even looks at this.

**Comment by dipak-shah** [comment] 2022-12-24 02:50
> 

Thank you let me know if its resolved by any workaround.

**Comment by badbole** [comment] 2023-01-05 17:12
> Sorry but I no longer voluntarely support Odoo issues here. The reason speaks for itself: because nobody at odoo cares or even looks at this.

Very sad.. but true... 
recently had simmilar experience with odoo crew...

**Comment by dipak-shah** [comment] 2023-03-12 03:15
its been 3+ months. still there is not update or resolution on this ?

**Comment by netfxtech** [comment] 2023-03-12 03:21
I’ve kind of come to realize that if you want it to be fixed then you’ll probably need to submit a PR yourself. I don’t know if I’ve seen anyone have anything fixed by just opening an issue here, at least not in the past few years. 

I don’t have this issue affecting any of my current customers so with that consideration and the lack of assistance I’ve received on past issues, I’m not motivated to submit a PR. 

Sorry, I should probably unfollow this issue since I don’t have anything productive to add. Hope you get it fixed if you haven’t found the root issue yourself yet.

**Comment by dipak-shah** [comment] 2023-03-17 21:20
Thank you @niyasraphy but it's not working yet. what you checked, might be you assumed something wrong from the ticket desc. ?

**Comment by niyasraphy** [comment] 2023-03-24 07:29
@dipak-shah confirmed the issue,
https://github.com/odoo/odoo/pull/116461

**Comment by niyasraphy** [comment] 2023-04-08 11:58
feel free to close as this is fixed in: https://github.com/odoo/odoo/commit/10f0eced62fe6ce085ae1a694aa5debbdc06dc1d

**Closed** 2023-04-09 16:00 UTC
