### ISSUE TITLE
[bug] Odoo 8.0 Stable , Print Customer Invoice

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#9106] opened 2015-10-16 11:37 UTC
Steps:

Create Customer Invoice

Then print Customer Invoice & get bug with odoo 8.0 stable latest revision.

Odoo Server Error
Traceback (most recent call last):
  File "/home/fabfku/8.0/addons/report/controllers/main.py", line 121, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "/home/fabfku/8.0/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/home/fabfku/8.0/addons/report/controllers/main.py", line 65, in report_routes
    pdf = report_obj.get_pdf(cr, uid, docids, reportname, data=options_data, context=context)
  File "/home/fabfku/8.0/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/fabfku/8.0/addons/report/models/report.py", line 274, in get_pdf
    paperformat, specific_paperformat_args, save_in_attachment
  File "/home/fabfku/8.0/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/fabfku/8.0/addons/report/models/report.py", line 485, in _run_wkhtmltopdf
    entire_report_path = self._merge_pdf(pdfdocuments)
  File "/home/fabfku/8.0/addons/report/models/report.py", line 565, in _merge_pdf
    reader = PdfFileReader(pdfreport)
  File "/usr/local/lib/python2.7/dist-packages/pyPdf/pdf.py", line 374, in __init__
    self.read(stream)
  File "/usr/local/lib/python2.7/dist-packages/pyPdf/pdf.py", line 702, in read
    stream.seek(-1, 2)
IOError: [Errno 22] Invalid argument

**Comment by sle-odoo** [comment] 2016-06-08 11:49
Closing as i cannot reproduce.
If you are still facing the issue, please detail a lot more. I tried this scenario on runbot and everything is working fine.

Regards

**Closed by sle-odoo** 2016-06-08 11:49 UTC
