### ISSUE TITLE
[10.0] access error when portal user open project link from invitation email

### ISSUE THREAD

**Issue by m3dbedb** [odoo/odoo#17881] opened 2017-06-28 10:41 UTC
Impacted versions: 10.0-20170228 community

Steps to reproduce: create project with privacy visible by following customer, choose customer, add customer to follovers, login to portal as customer, open project link from invitation email

Current behavior: Odoo warning: access error uppears with following massage: 
![odoo_warning](https://user-images.githubusercontent.com/25632818/27633229-0a751d12-5c07-11e7-9002-c28176c85633.PNG)
> Sorry, you are not allowed to access this document. Only users with the following access level are currently allowed to do that:
> - Project/Manager
> - Project/User
> - Employees/Employee
> 
> (Document model: project.issue.stage)

If customer close error massage by pressing cross twice he see all projects settings
![project](https://user-images.githubusercontent.com/25632818/27633223-062582a6-5c07-11e7-80d1-70d7c5ec03fc.PNG)

Expected behavior: portal user shouldn'r recieve link to project module `http://odoo.su/mail/view?model=project.project&res_id=88` link should look like this `http://odoo.su/my/project/88`

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2018-06-01 00:26
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-06-01 00:26 UTC
Labels: 10.0, Services
