### ISSUE TITLE
checkbox is deactivated automatically

### ISSUE THREAD

**Issue by inetplus** [odoo/odoo#1626] opened 2014-08-06 13:17 UTC
the checkbox in the product detail "Can be Purchased " is deactivated automatically after saving it.

Steps:
1) create a new sellable product "ProductA".
2) set the checkbox as active "can be purchased"
3) select another product
4) select the Product "ProductA"
5) check the status of checkbox "can be Purchased"

accepted result:
- checkbox is activated

current result:
- checkbox is deactivated

**Comment by Yenthe666** [comment] 2017-08-28 14:19
Hi @inetplus,

Thanks a lot for your report. At this point the issue can no longer be reproduced and everything works fine now.
Closing this because it is no longer reproducable.

Regards,
Yenthe

**Closed by Yenthe666** 2017-08-28 14:19 UTC
