### ISSUE TITLE
No sitemap.xml generated

### ISSUE THREAD

**Issue by Alexandre-Bernardes** [odoo/odoo#28038] opened 2018-10-22 17:24 UTC
Impacted versions:
v11
Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

My odoo website dont generate sitemap.xml.
I not have idea whats happen!

**Comment by pedrobaeza** [comment] 2018-10-22 17:32
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue. Check for example http://387880-11-0-e74424.runbot17.odoo.com/sitemap.xml

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-10-22 17:32 UTC
