### ISSUE TITLE
Dialog title does not display localized text

### ISSUE THREAD

**Issue by yuzifu** [odoo/odoo#36189] opened 2019-08-28 13:25 UTC
Impacted versions:
12.0

Steps to reproduce:
1. Install 12.0 CE include sales app, and add other language than english.
2. login to backend, change language to not english.
3. Navigate sales app.
4. Click "Let's start!"/"Customize"/"Set payments"/"Send sample"(in english) button.

Current behavior:
In opened dialog, the title is english, not localized text.
The title text has been confirmed in the i18n file.
Account app has same issue.

Expected behavior:
Display localized text in dialog title.

**Comment by pedrobaeza** [comment] 2019-08-28 14:34
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)? Please make sure also that the translated term is present.

If not reproducible, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by yuzifu** [comment] 2019-08-28 15:19
@pedrobaeza 
In runbot, the issue can be reproduced.

**Comment by pedrobaeza** [comment] 2019-08-28 15:23
Screenshots? Link?

**Comment by yuzifu** [comment] 2019-08-28 15:31
![Screenshot 2019-08-28 23 27 53](https://user-images.githubusercontent.com/853731/63870082-d932e680-c9eb-11e9-9884-d89d1b21a314.png)

**Comment by pedrobaeza** [comment] 2019-08-28 15:33
What is the language you have installed? Spanish (Spain) or other?

**Comment by yuzifu** [comment] 2019-08-28 15:38
I install Spanish.

**Comment by pedrobaeza** [comment] 2019-08-28 15:52
Indeed the term seems translated:

https://github.com/odoo/odoo/blob/412117c2a789a24191cda040614d01fe290e77cc/addons/gamification/i18n/es.po#L1810

![Selección_024](https://user-images.githubusercontent.com/7165771/63871645-8ee64100-c9bc-11e9-9aad-2dd9ccb3e746.png)

But it's not being handled.

Reproduced on http://603176-12-0-5bb431.runbot24.odoo.com

@mart-e can you please check?

**Comment by mart-e** [comment] 2019-08-30 08:35
Looks like the context is not give in the call to `action_open_base_onboarding_company` (and probably the other ones from the dashboard).
But I don't really know how these actions are managed.
@tivisse maybe?

**Comment by tivisse** [comment] 2019-08-30 08:44
Mmmh. Seems like an issue indeed. I've opened a task to fix it internally, as the developer as left the company.

Fix incoming ;)

Thank you for the feedback.

TicketID: 2062419

**Comment by tivisse** [comment] 2019-08-30 14:19
@pedrobaeza 

I've tested it on your runbot, and the term is correctly translated/displayed.

I've tested locally with on 12.0 instance, the term is correctly translated too.

Could you please elaborate so that I can reproduce the issue ? 

Thanks.

**Comment by yuzifu** [comment] 2019-08-30 17:27
@tivisse 
I have tested this issue again on @pedrobaeza 's runbot, the issue can be reproduced.

1. open http://603176-12-0-5bb431.runbot24.odoo.com
2. select database 603176-12-0-5bb431-all
3. login with admin/admin
4. open "Ventas" app in apps menu
5. click link "¡Empecemos!" in header wizard
6. dialog is opened, the title is show text in english.

![2019-08-31 01 18 43](https://user-images.githubusercontent.com/853731/64039933-6ca41d00-cb8e-11e9-8cc9-df61cb79295f.png)

**Comment by pedrobaeza** [comment] 2019-08-31 00:06
Tried myself also in fresh runbot (http://605780-12-0-df85dd.runbot23.odoo.com) with the same result:

![Selección_027](https://user-images.githubusercontent.com/7165771/64056496-e2f74e00-cb93-11e9-954a-480a78ab1eb6.png)

**Closed** 2019-09-16 14:51 UTC
Labels: 12.0, Internationalization
