### ISSUE TITLE
Facing problem to set odoo10 database in postgresql 9.4 BDR at Debian linux

### ISSUE THREAD

**Issue by odoosns** [odoo/odoo#21872] opened 2017-12-27 07:54 UTC
Impacted versions: Odoo 10 and PostgreSQL 9.4 BDR

Steps to reproduce: Hi All,
We are trying to set Odoo10 (One customized MLM Module) with PostgreSQL 9.4 BDR at Debian Linux
 
When we have done setup Odoo10 database with PostgreSQL 9.4 BDR and trying to start Odoo server. Its provide the error for Primary key is not set for many tables or Drop the particular table, which don't have Primary key.  
**error**
  File "/opt/odoo/odoo/addons/project/report/project_report.py", line 88, in init
    tools.drop_view_if_exists(self._cr, self._table)
  File "/opt/odoo/odoo/odoo/tools/sql.py", line 5, in drop_view_if_exists
    cr.execute("DROP view IF EXISTS %s CASCADE" % (viewname,))
  File "/opt/odoo/odoo/odoo/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
ProgrammingError: "report_project_task_user" is not a view
HINT:  Use DROP TABLE to remove a table.

**When I am going to create node 1 ==> SELECT bdr.bdr_group_create( local_node_name := 'node1', node_external_dsn := user= dbname= password=);
at my first BDR machine, its provide **warning** like below.**

**warning**
HINT:  Drop the secondary unique constraint(s), change the table(s) to UNLOGGED if they don't need to be replicated, or exclude the table(s) from the active replication set(s).
WARNING:  Secondary unique constraint(s) exist on replicated table(s)
DETAIL:  Table public.mail_wizard_invite_res_partner_rel has secondary unique constraint mail_wizard_invite_res_partne_mail_wizard_invite_id_res_par_key. This may cause unhandled replication conflicts.
HINT:  Tables without a PRIMARY KEY cannot be UPDATEd or DELETEd from, only INSERTed into. Add a PRIMARY KEY.
WARNING:  Table public.mail_wizard_invite_res_partner_rel has no PRIMARY KEY
HINT:  Tables without a PRIMARY KEY cannot be UPDATEd or DELETEd from, only INSERTed into. Add a PRIMARY KEY.
WARNING:  Table public.mail_message_mail_channel_rel has no PRIMARY KEY
HINT:  Tables without a PRIMARY KEY cannot be UPDATEd or DELETEd from, only INSERTed into. Add a PRIMARY KEY.
WARNING:  Table public.project_tags_project_task_rel has no PRIMARY KEY

Please let me know if any one faced this kind of problem. Please provide the solution on this.

Thank in Advance

**Comment by Yenthe666** [comment] 2017-12-27 08:08
Hi @odoosns,

Thank you for your report but it is a bit confusing.
Have you created the Odoo database from the Odoo web interface and then added a custom module to it or? What exactly do you mean with node 1 at server 1?

**Comment by gdgellatly** [comment] 2017-12-27 08:31
The issue is that m2m rel tables don't have primary keys but rather unique constraints.  It would be a nice feature to have as really both columns form a composite key and already have a unique constraint so really just needs changing UNIQUE to PRIMARY KEY and BDR might work.

@odony what do you think, worth it for supporting (or at least starting to support) BDR?

**Comment by odoosns** [comment] 2017-12-27 08:36
Hi Yenthe,
Thanks for your quick response.

We have database for odoo10 default and MLM module. we restored this database and trying to set PostgreSQL BDR. Node 1 means SELECT bdr.bdr_group_create( local_node_name := 'node1', node_external_dsn :=  user= dbname= password=); when I am going to run this, its providing warning for Primary key tables and unique constraints.
and Server 1 means we are creating this node 1 setup on it.

**Comment by gdgellatly** [comment] 2017-12-27 08:42
@odony One thing I noticed looking at the m2m code just now is that both columns get indexed, but the first one is already indexed by the Unique constraint.  Can't imagine its a massive overhead, but an unnecessary index nonetheless.

**Comment by odoosns** [comment] 2017-12-27 08:52
Hi gdgellatly,
Thanks for your Contribution.

I tried multiple scenarios but did not get success. I added primary key for those tables don't have. I tried to exclude the tables from BDR those don't have primary key but it is not working.

I want the any particular steps or things to resolve this problem.

Thank you in advance

**Comment by odoosns** [comment] 2017-12-29 13:08
Hi All,
If anyone is having any solution for my problem, please suggest me. It will be great help for me.

Thank you

**Comment by sbglive** [comment] 2017-12-31 09:03
Hello everyone,

I am trying to attempt a similar setup on V11, odoo with muti master replication over BDR, with similar issues. 
Does anybody have a workaround ?

Thank you

**Comment by Yenthe666** [comment] 2019-10-07 09:48
Dear @odoosns,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe

**Closed by Yenthe666** 2019-10-07 09:48 UTC
Labels: 10.0, Framework
