### ISSUE TITLE
8.0 stock return does not reconcile negative quants

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#9906] opened 2015-12-03 19:39 UTC
Steps to reproduce:
1. install stock, configure Track Lots or Serial Numbers in Stteings / Warehouse
2. Create an outgoing picking for 1 A2323 manually
3. Force availability on picking
4. Transfer the picking, creating a Serial Number 0001 on the way. 
5. Create a return for the picking, and transfer it specifying the same Serial Number 0001
6. Go to Warehouse / Serial Numbers, open 0001

Expected : the negative quant created in step 3 was reconciled when the return picking was transfered. 

Actual: in the Stock location, I have 1 quant qty -1 and another quant with qty +1 for serial 0001

**Comment by gurneyalex** [comment] 2015-12-03 19:47
Comments: 

the use of serial numbers is probably not required to reproduce but it makes it easier to see the bug. 

I traced the code in step 5 and found that if this line is removed the bug is fixed: 
https://github.com/odoo/odoo/blob/8.0/addons/stock/stock.py#L572

What we have in this use case is typically the same quant which was forced being returned in an attempt to fix the issue, and this line prevents the reconciliation. I don't understand that changeset and the commit message does not help very much (https://github.com/odoo/odoo/commit/244c8ee6259fdb699b992996d8ef9ff82b3294b1) 

@jco-odoo your help is very welcome.

**Comment by gurneyalex** [comment] 2015-12-03 20:43
added a PR to fix this, with a test.

**Comment by gurneyalex** [comment] 2015-12-04 08:14
OPW opened.

**Comment by spadae22** [comment] 2016-01-21 05:20
@gurneyalex We see the same issue, will this be merged?

**Comment by gurneyalex** [comment] 2016-01-21 08:20
@spadae22 I think not :-/ but I'm not the one with the power to do it.

**Comment by nhomar** [comment] 2016-01-21 08:24
@antonylesuisse  @odony @qdp-odoo 

Do we need pass this issue as enterprise?

Because we think it is important but not sure if th technical solution is corect a feedback is welcome.

Regards.

**Comment by gurneyalex** [comment] 2016-01-21 08:27
@nhomar I opened an OPW for this already, and the answer was "not a bug, this is the intended behavior".

**Comment by nhomar** [comment] 2016-01-21 08:29
have negative quants is an intended behavior?

did not they extend the answer?

Seriously, how they manage maths on university? 

A negative quant forever in inventories make impossible to audit a lot of things....

**Comment by gurneyalex** [comment] 2016-01-21 08:34
@nhomar 

Initial answer from Odoo support:

"""This is normal behaviour of Odoo when you transfer product with the serial number and return that same serial number into the stock.
As of now there is no any configuration or functionality available to reconcile the stock quantity (like accounting function and as you say in your description) in to the Stock module.
Thank you.
"""

My answer to this:
"""
The issue that I have then is described by the following scenario (taken from github #9907, simplified from what is happening on my customer instance. )


@jco-odoo consider the following scenario, which can be run on runbot with sale_stock installed

create and validate a SO for Luc Maurer with 1 Blank CD (no stock for this)
force availability of the outgoing picking, and ship
return the erroneous picking

The stock level of Blank CD is 0, with a quant of +1 and a quant of -1

If I create a new SO for Luc Maurer with 1 Blank CD, I get a warning that there is no stock during edition. Yet if I confirm the SO, and Check availability of the picking, it gets Ready to Transfer.
"""

Support's response:

"""This is wanted behaviour: we don't want a quant to eat itself. That way, history is kept: if something is returned from a client, it is logical you can reserve it to send it back to someone else. (we assume it is physically there) If you add new stock, it will 'eat' the negative quant."""

See also @jco-odoo comment on #9907: https://github.com/odoo/odoo/pull/9907#issuecomment-162663086

**Comment by jco-odoo** [comment] 2016-01-21 08:37
This has nothing to do with serial numbers: when a quant has no serial number, it can reconcile with any negative quant, when it has, the negative quant should have that serial number too. As @gurneyalex referred to, it is to avoid quants to eat themselves as it will erase their history: when you return something that came from a negative stock, it is physically there  (and I know the message in sale_stock is not ideal, but normally you should correct your stock as you forgot to input a purchase order e.g.).  If you are really having a lot of problems with negative quants still @nhomar , we might better have a look if there is a way to get rid of them through making inventories.

**Comment by nhomar** [comment] 2016-01-21 08:46
@jco-odoo 

I think it is not a "Black and White" problem, there is a lot of greys areas where such rule is valid.

We have 2 kinds of negative quants.

1. The reconcilable ones.
2. The unreconcilable ones.

Let's say this specific case is one "reconcilable" case because you have all to do it:

1. Lot.
2. Move which made the negtive.
3. Return related.

Then in this case the negative should not be "adjusted" because with several locations you will need to adjust location per location which is too complicated functionally speaking and it is not "procedural" speaking "auditable".

It means, I can share cases where the negative quant do not have any sense and you can not trace "where the problem comes from" we should avoid as much as possible negative quants just for technical conveniences.

About the "eat the quant itself" statement, can you share with us on this example how can we audit once the historical you preserving the relation between quants?

I understand at the end when all fails making inventories is the ultimate measure, but it should not be the first, if it is the first it is too insecure in terms of "Inventory control".

I mean: The inventory process can not be asked to a customer because of "Software issues" it should be asked because "Process and Real adjustments issues".

And in this cas I think it is a design of conceptual problem in the ways you solve this specific behavior.

I hope it clarify my point.

Regard.s

**Comment by liebana** [comment] 2016-06-13 10:25
Any news regarding this?

**Comment by yostashiro** [comment] 2016-08-10 07:57
@jco-odoo 

> it is to avoid quants to eat themselves as it will erase their history: when you return something that came from a negative stock, it is physically there

What "history" do you mean?  Shouldn't quants just represent the current state of the inventory (not the history)?  History can be traced with stock moves.

I cannot at all understand the benefit of blocking negative quants from being reconciled.

**Comment by Yenthe666** [comment] 2017-11-05 19:15
Hi @gurneyalex ,

Thank you for your bug report and thank you to all the others for giving feedback / insights.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Closed by Yenthe666** 2017-11-05 19:15 UTC
