### ISSUE TITLE
Odoo 13 not working with PostgreSQL rds (ERROR: relation "ir_module_module" does not exist)

### ISSUE THREAD

**Issue by AleksandarTokarev** [odoo/odoo#51400] opened 2020-05-18 09:19 UTC
Hello,
I have installed Odoo13 on EC2 and i am connecting to PostgreSQL RDS 10.5.  
Here are the DB options in .conf file
```

[options]
; This is the password that allows database operations:
db_host = xxxxxxxx
db_port = 5432
db_user = odoo13
dbfilter = odoo13
db_password = yyyy
addons_path = /opt/odoo13/odoo/addons,/opt/odoo13/odoo-custom-addons
```
My database name is odoo13, master username is odoo13. 
When i try to connect to the URL on the browser, i am getting the error stated below.
I looked at https://github.com/odoo/odoo/issues/27447, but obviously this does not solve my error.
A workaround as someone stated would be https://superuser.com/questions/1405011/odoo12-err-on-setting-remote-database-to-be-at-amazon-rds/1407488, but is it possible without doing that?
Thanks a lot in advance.

Impacted versions:
Odoo 13
Steps to reproduce:
Go to http://<url>:8069
Current behavior:
```
ERROR odoo13 odoo.sql_db: bad query: SELECT
ERROR: relation "ir_module_module" does not exist
LINE 1: SELECT latest_version FROM ir_module_module WHERE name='base...
```
Expected behavior:
Odoo 13 URL should start correctly

**Comment by pedrobaeza** [comment] 2020-05-18 11:53
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/13.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).

**Closed by pedrobaeza** 2020-05-18 11:53 UTC

**Comment by bernardo-martinez** [comment] 2020-11-10 12:09
hey @AleksandarTokarev have you solved your issue? I'm also facing this so it would be nice to know if you managed to solve it and how. Thanks!

**Comment by AleksandarTokarev** [comment] 2020-11-19 15:28
@bernardo-martinez  i managed to get it working with some configuration changes but i don't remember exactly how.
Another approach that was working for a friend of mine was with Docker

**Comment by MisaghMi** [comment] 2020-12-22 11:48
I have same problem.
Odoo makes DB but there is no table stored in that DB.

**Comment by xiaoniu001** [comment] 2021-04-24 12:53
> @bernardo-martinez i managed to get it working with some configuration changes but i don't remember exactly how.
> Another approach that was working for a friend of mine was with Docker

hi，Have you solved this problem？

**Comment by hertell** [comment] 2021-07-05 08:31
same "ERROR: relation "ir_module_module" does not exist" error in Odoo 14 installed via docker..

**Comment by zzwxrchi** [comment] 2021-08-14 21:36
# My solution
	# stop/delete container
	docker container stop odoo_db_1 odoo_web_1
	docker container rm odoo_db_1 odoo_web_1

	# delete volumens (Warning: you will lose all custom data in the database)
	docker volume rm odoo_db-data odoo_web-data

	# reload container with new created data volumen
	docker-compose up -d

# Reason of error
	Usually it is because you have init database badly created

**Comment by D-Nations** [comment] 2021-08-20 23:38
I have the same problem.  I think it's related to how the PostgreSQL database is initialized or something.  Any ideas?

**Comment by D-Nations** [comment] 2021-08-21 00:43
I think I just figured it out.  The conda version of lxml is causing a conflict.  I uninstalled from conda, but that also uninstalled zeep.  So "pip install lxml zeep" did the trick.

**Comment by zkilburn86** [comment] 2021-10-09 01:27
@ishahriar94  Same with me, Odoo15 in Windows - I added `-i base` to my odoo-bin command which runs init db and loads all the models. Worked for me after that.

**Comment by ishahriar94** [comment] 2021-10-09 07:00
> 
> 
> @ishahriar94 Same with me, Odoo15 in Windows - I added `-i base` to my odoo-bin command which runs init db and loads all the models. Worked for me after that.

Can you give a Screenshot of your work ?? It will be a great help.

**Comment by zkilburn86** [comment] 2021-10-09 14:12
> > @ishahriar94 Same with me, Odoo15 in Windows - I added `-i base` to my odoo-bin command which runs init db and loads all the models. Worked for me after that.
> 
> Can you give a Screenshot of your work ?? It will be a great help.

Sure thing! Hadn't cleared the console yet, here is the full command:
`python odoo-bin -r <pg_user> -w <pg_pw> --addons-path=addons -i base -d <db_name> --db_port 5433`

![Screenshot 2021-10-09 090743](https://user-images.githubusercontent.com/40241811/136661389-3c0ec5a2-1e0e-4b1d-84e8-ebb584548a22.png)

**Comment by HabibaAtique** [comment] 2022-04-17 13:03
> > > @ishahriar94 Same with me, Odoo15 in Windows - I added `-i base` to my odoo-bin command which runs init db and loads all the models. Worked for me after that.
> > 
> > 
> > Can you give a Screenshot of your work ?? It will be a great help.
> 
> Sure thing! Hadn't cleared the console yet, here is the full command: `python odoo-bin -r <pg_user> -w <pg_pw> --addons-path=addons -i base -d <db_name> --db_port 5433`
> 
> ![Screenshot 2021-10-09 090743](https://user-images.githubusercontent.com/40241811/136661389-3c0ec5a2-1e0e-4b1d-84e8-ebb584548a22.png)


Is there a way to run odoo-bin forcefully using -i base in eclipse?  I am using eclipse IDE and this solution helps me when i run using Command Prompt but i want help running odoo project on eclipse

**Comment by anubiaodoosh** [comment] 2023-01-12 09:43
Same problem here running an Odoo 15 using the _Odoo.sh_ platform. Odoo worked ok, but when I add any submodule like an OCA repository, for example _OCA/l10n-spain_, I get this same error in the Odoo log.

Any ideas?

**Comment by me0x2gg** [comment] 2023-04-20 06:40
> > > > @ishahriar94 Same with me, Odoo15 in Windows - I added `-i base` to my odoo-bin command which runs init db and loads all the models. Worked for me after that.
> > > 
> > > 
> > > Can you give a Screenshot of your work ?? It will be a great help.
> > 
> > 
> > Sure thing! Hadn't cleared the console yet, here is the full command: `python odoo-bin -r <pg_user> -w <pg_pw> --addons-path=addons -i base -d <db_name> --db_port 5433`
> > ![Screenshot 2021-10-09 090743](https://user-images.githubusercontent.com/40241811/136661389-3c0ec5a2-1e0e-4b1d-84e8-ebb584548a22.png)
> 
> Is there a way to run odoo-bin forcefully using -i base in eclipse? I am using eclipse IDE and this solution helps me when i run using Command Prompt but i want help running odoo project on eclipse

thank you so much, it works with me, just added -i base

**Comment by WassimMeddeb** [comment] 2023-05-29 21:54
> I think I just figured it out. The conda version of lxml is causing a conflict. I uninstalled from conda, but that also uninstalled zeep. So "pip install lxml zeep" did the trick.

worked for me... thanks.

**Comment by t-sq1** [comment] 2023-07-03 07:22
@anubiaodoosh Could you resolve the issue in sh?

**Comment by SRCthird** [comment] 2023-12-15 20:26
In case others are still having this issue, and the other solutions didn't work: don't create the database manually. -d <database> should be a database you haven't created yet

**Comment by Guyus01** [comment] 2024-11-14 19:36
I had the same problem, after testing the robustness of my database, in particular: deletion of test databases, including the "odoo" reference database, addition of specific schemas, and other oddities that came out of my imagination!
My investigations show that the absence of relationships despite the creation of an odoo database results from one or more lack of rights for the odoo user in postgresql. This can come from the postgresql configuration or from the filters applied to the activation of the odoo server.

**So, here are some tips that can help you, I hope:**

1. If we apply a parameter "db_template=odoo", we must check that the active user of the database has the rights on the odoo schema. ==> In posgresql, if necessary, assign the rights on the "odoo" schema:
```
CREATE SCHEMA odoo;
GRANT ALL PRIVILEGES ON SCHEMA odoo TO odoo;
ALTER USER odoo SET search_path TO odoo, public;
```
2.  Do the same to correctly assign user rights on any other schema you want to use.

3.  If you do not want to specify a parameter for the database schema, comment out or delete the db_template line in the configuration file on the odoo server. Indeed, the "db_template = " option prevents the creation of relations in the database, because of the space after the = sign

4. similarly, using a poorly configured db_filter would probably cause the inability to create the database relations (I haven't tested it)

5. remember to initiate the odoo schema when the server is first launched. Try the options
```
--init odoo ,
--init base,web
```

These checks and fixes allowed me to solve the problem
`**ERROR: relation "ir_module_module" does not exist**`

I made my tests on an odoo 16.0 server

Any other ideas? Let us know
