### ISSUE TITLE
Missing orders + payment in POS

### ISSUE THREAD

**Issue by jzahid** [odoo/odoo#22766] opened 2018-02-02 16:48 UTC
Impacted versions: 10

Steps to reproduce: 
random behaviour, when more than one session is open 

Current behavior:
some times order is missing when session is closed as well as related payment
Expected behavior:

Video/Screenshot link (optional):

Hi
Two times in 8 days interval we had missing order + corresponding payment in POS.  
At the end of the day our customer have extra money compared to registred pos orders and payment (one time in cash journal , another in check journal). The missing orders appear no where and there is no error or warning in logs. In both times, paper receipts are correctly printed with correct data ( product, price...) 
This behavior has been reported earlier in V8 but never solved since then. This is a serious issue that we can't explain to our customer. ( missing ticket/order is considered as fraud by authorities)
Is there à solution to that ?
Regards

**Comment by Yenthe666** [comment] 2018-02-05 08:35
Hi @jzahid,

Is there any way for you to find a reproducable way or atleast a case in which it tends to happen?

Regards,
Yenthe

**Comment by andrewyova** [comment] 2018-02-15 02:52
Bug Odoo10 POS order that missing 
step to reproduce 

1. open at the same time pos session using 2 same browser(1 incognito ) with same user
2. order anything
3. other browser order is saved while the other 1 is not safe

it can reproduce in here
http://302900-10-0-384cc6.runbot11.odoo.com

**Comment by tajwali** [comment] 2018-05-16 05:59
Is there a solution for this bug?

**Comment by anothingguy** [comment] 2018-05-22 11:33
i think it would be nice if we have a video about this issue.
I tried to reproduce as the steps above but not succeed.

**Comment by andrewyova** [comment] 2018-05-30 04:26
[bug_odoo10_pos.mp4.zip](https://github.com/odoo/odoo/files/2052395/bug_odoo10_pos.mp4.zip)

**Comment by anothingguy** [comment] 2018-05-30 17:13
Thanks for your video. Finally i can reproduce this issue at runbot [http://332361-10-0-b708c3.runbot13.odoo.com/web](http://332361-10-0-b708c3.runbot13.odoo.com/web)
This issue is hard to reproduce because it's depends on the loading steps of the POS and the load of server. I can reproduce it on http://332361-10-0-b708c3.runbot13.odoo.com/web because loading POS is slow enough on this server to reproduce it (before i tried with http://332617-10-0-b708c3.runbot17.odoo.com/web but not succeed too).
### My theory:
I think this issue can be explained by some points of code, (not tested in my local yet, just testing runbot).
1. https://github.com/odoo/odoo/blob/10.0/addons/point_of_sale/controllers/main.py#L23
=> call login method when access POS via /web/pos url (click "new session" or "resume")
2. https://github.com/odoo/odoo/blob/10.0/addons/point_of_sale/models/pos_session.py#L222
=> incrementing login_number of session each time access POS
3. https://github.com/odoo/odoo/blame/10.0/addons/point_of_sale/static/src/js/models.js#L224
=> loading pos.session information (including login_number)
4. https://github.com/odoo/odoo/blob/10.0/addons/point_of_sale/models/pos_order.py#L601
=> avoid duplicate order which pushed from client to server by filtering receipt ref

So, from (1),(2),(3),(4). I guess:
- time t1 - 7:00: user_1 open new session: login_number = 1
- time t2 - 7:01: user_2 open this session again in different browser: login_number = login_number + 1 = 2
- time t3 - 7:05 : user_1 loading to step (3), so it gets latest login_number=2 as user_2. So they have the same receipt_ref (see http://prntscr.com/jong95)
- time t4 - 7:06: because 2 orders have the same receipt ref, so avoid duplication (4) only allow the first one which pushed to server.


I think this issue may impact version 9 and 11 also because it seems the code are the same for these version.
Workaround: one computer should open one POS only.
i think we can put (3) to the top of loading models steps (after loading [version](https://github.com/odoo/odoo/blame/10.0/addons/point_of_sale/static/src/js/models.js#L148) is OK)

**Comment by switch87** [comment] 2018-11-15 23:47
Pos sessions are not supposed to be used in multiple windows at the same time. This is not considered a bug but bad practice. Each POS station or pos windows has to have it's own user + session separate from each other. Once a POS session is started it is possible to switch to the same user that is active on another session if this is wanted. I am closing this issue for now, if you have any questions regarding the workflow, please feel free to comment and tag me.

**Closed by switch87** 2018-11-15 23:47 UTC
Labels: 10.0, Point of Sale

**Comment by nick2474** [comment] 2019-03-04 18:14
I got this similar issues but with the order saved in the back office without the line of payment method. Its a weird behavior from POS.

**Comment by switch87** [comment] 2019-03-04 23:40
@nick2474 rhis issue is closed. Please open a new issue with more details on how to reproduce your problem.

**Comment by heshamfm** [comment] 2019-08-22 05:23
Hi @switch87 we have the same issue with client on 8, 11 & 12. We will advise them not to start multiple sessions on the same machine. But, please explain what you mentioned: "Once a POS session is started it is possible to switch to the same user that is active on another session if this is wanted"
