### ISSUE TITLE
[14.0][BUG] Secure Sequence of journal gives error when set prefix 

### ISSUE THREAD

**Issue by ADVALAKI** [odoo/odoo#58877] opened 2020-09-30 03:47 UTC
Impacted versions: 14.0
Steps to reproduce: 
1. Enable "Lock Posted Entries WIth Hash" on customer journal.
![image](https://user-images.githubusercontent.com/14277140/94640807-3a1ea380-02fd-11eb-8008-b7a086d11f8d.png)

2. Go to sequence which is linked with secure_sequence_id of journal. and set prefix 
![image](https://user-images.githubusercontent.com/14277140/94640879-69cdab80-02fd-11eb-914e-9cc198032058.png)

3. Go to invoice and create one invoice and try to confirm it.

Current behavior:

It will show following error.
![image](https://user-images.githubusercontent.com/14277140/94640974-a26d8500-02fd-11eb-875c-193c7dc6edab.png)

Expected behavior: It should allow to validate invoice with given sequence and prefix without any error.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment] 2020-09-30 10:15
@qdp-odoo the 14.0 story has begun!

**Comment by sswapnesh** [comment] 2020-10-02 16:01
> The 14.0 story has begun!

This is for 13.0 as well.

**Comment by dhulisz** [comment] 2020-12-30 10:25
Hello. Is there any news about this bug. It is already few months since it creation.

**Comment by Yenthe666** [comment] 2020-12-30 11:29
I also made an enterprise ticket for this, `2424903`

**Comment by dnz-biebuyck** [comment] 2020-12-30 15:42
Hello Yenthe666,
do you know another way to solve that problem?

**Comment by Yenthe666** [comment] 2020-12-30 16:07
In V14 by using the resequence wizard from the invoices or custom logic, none are really great to be honest.

**Comment by dnz-biebuyck** [comment] 2020-12-30 17:26
Thanks for reply. I'll test resequence... But our problem is that we need to have different sequences for different invoice journal.
I'll try if it works.
In V13, there was no problem to do that. I don't understand why this behaviour has been canceled.

**Comment by ADVALAKI** [comment] 2020-12-31 02:41
for journal sequence in odoo 14 there is already app available while allow journal sequence same like odoo 13.
search for "journal sequence". in app store.(is paid app by the way)

**Comment by ADVALAKI** [comment] 2020-12-31 02:41
> Thanks for reply. I'll test resequence... But our problem is that we need to have different sequences for different invoice journal.
> I'll try if it works.
> In V13, there was no problem to do that. I don't understand why this behaviour has been canceled.

for journal sequence in odoo 14 there is already app available while allow journal sequence same like odoo 13.
search for "journal sequence". in app store.(is paid app by the way)

**Comment by dnz-biebuyck** [comment] 2021-01-05 17:57
> I also made an enterprise ticket for this, `2424903`

Hello Yenthe666,

any news about that ticket?

Denis

**Comment by Yenthe666** [comment] 2021-01-05 18:57
No update yet. I'll post back when I get an update :)

**Comment by william-andre** [comment] 2021-01-20 12:37
> In V14 by using the resequence wizard from the invoices or custom logic, none are really great to be honest.

@Yenthe666 @dnz-biebuyck It has nothing to do with the Resequence wizard. This wizard is for the field `name`, using `sequence.mixin`, while the error reported is linked to `secure_sequence_number`, which is using a `ir.sequence` but we never care about the prefix.

https://github.com/odoo/odoo/blob/036fc78103e3d8875a5a54c797e1ba0670d02272/addons/account/models/account_move.py#L1860-L1865

The issue is that only a number is expected as `secure_sequence_number` is a `fields.Integer`, therefore no prefix is allowed.

**Comment by william-andre** [comment] 2021-02-04 17:05
I cancelled the ticket `2424903` and I am closing this issue.

If you have an idea of improvement, you are welcome to propose it, but this is not a bug.

**Closed by william-andre** 2021-02-04 17:05 UTC
Labels: 13.0, 14.0, Accounting, OE

**Comment by romaric-oci** [comment] 2021-06-21 13:07
Hello, This app seems to be a good compromise.
https://apps.odoo.com/apps/modules/14.0/od_journal_sequence/
or 
https://apps.odoo.com/apps/modules/14.0/journal_sequence/

**Comment by william-andre** [comment] 2021-06-21 13:49
> Hello, This app seems to be a good compromise.
> https://apps.odoo.com/apps/modules/14.0/od_journal_sequence/
> or
> https://apps.odoo.com/apps/modules/14.0/journal_sequence/

@romaric-oci No. There was no bug here, and those apps are not related to the issue at all.
By the way, you will have a lot of issues later if you use this kind of apps, please don't.

**Comment by Yenthe666** [comment] 2021-06-21 14:16
@william-andre the fact that so many of these apps are popping up shows that the logic that was built is not working for a lot of Odoo companies/users. I hope this serves as an eye opener that perhaps there should be some changes made 😉

**Comment by william-andre** [comment] 2021-06-21 14:31
> @william-andre the fact that so many of these apps are popping up shows that the logic that was built is not working for a lot of Odoo companies/users. I hope this serves as an eye opener that perhaps there should be some changes made wink

The fact that this issue exists and your comments on it shows that you don't understand it at all and that you are trying to find solutions for problems that don't exist.

**Comment by romaric-oci** [comment] 2021-06-21 16:07
@william-andre here are some points that I note

- ODOO imposes a sequence by journals, which is not the case of other accounting software package (for example CEGID) it is already a first change for the user. 
- Conversely, ODOO easily allowed via the v13 interface sequences to include the year (which CEGID lacks). 
- The V14 **has lost the simplicity** of disassociating the prefix from the sequence of the log code (the code is used in an export for an external ERP, the prefix is visible on the sales invoice and have). 
- The V14 **has lost the simplicity** of continuing the sequence where the user was before the migration to ODOO
- V14 **imposes** the month on the user in the sequence

As an integrator, we are constantly confronted with the accompaniment to change or the taking into account of the constraints imposed by an external accounting firm. Whether the old software or that of the firm is CEGID, Quadra, Sage, Ciel ...
This is one more thorn for migration to Odoo

For the accounting revision/evolution, is PwC attached to the discussion? (author of all the Mémentos of the accounting range published by Éditions Francis Lefebvre)

**Comment by william-andre** [comment] 2021-06-21 16:09
This has nothing to do with this issue.
