### ISSUE TITLE
odoo.tools.convert.ParseError: "local variable 'res' referenced before assignment"

### ISSUE THREAD

**Issue by khaeusler** [odoo/odoo#47204] opened 2020-03-09 13:43 UTC
https://github.com/odoo/odoo/blob/ca695425a2b06ffba15d7063fb0b8ea994f751d6/addons/stock_account/models/stock.py#L23-L31

it would be great if res were initialized

Traceback (most recent call last):
  File "/opt/odoo/lib/odoo/odoo/service/server.py", line 1183, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/opt/odoo/lib/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/lib/odoo/odoo/modules/loading.py", line 467, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/opt/odoo/lib/odoo/odoo/modules/loading.py", line 352, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/lib/odoo/odoo/modules/loading.py", line 260, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/opt/odoo/lib/odoo/odoo/modules/loading.py", line 103, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/lib/odoo/odoo/tools/convert.py", line 802, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/lib/odoo/odoo/tools/convert.py", line 865, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/lib/odoo/odoo/tools/convert.py", line 755, in parse
    self.parse(rec, mode)
  File "/opt/odoo/lib/odoo/odoo/tools/convert.py", line 764, in parse
    exc_info[2]
  File "/opt/odoo/lib/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/odoo/lib/odoo/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/lib/odoo/odoo/tools/convert.py", line 343, in _tag_function
    _eval_xml(self, rec, env)
  File "/opt/odoo/lib/odoo/odoo/tools/convert.py", line 194, in _eval_xml
    return odoo.api.call_kw(model, method, args, {})
  File "/opt/odoo/lib/odoo/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/lib/odoo/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/lib/odoo/addons/stock/models/stock_inventory.py", line 181, in action_validate
    self._action_done()
  File "/opt/odoo/lib/odoo/addons/stock/models/stock_inventory.py", line 189, in _action_done
    self.post_inventory()
  File "/opt/odoo/lib/odoo/addons/stock_account/models/stock.py", line 31, in post_inventory
    return res

**Comment by pedrobaeza** [comment] 2020-03-09 15:14
Steps to reproduce the problem?

**Comment by khaeusler** [comment] 2020-03-09 16:29
e.g.
```
<function model="stock.inventory" name="demo_action_validate">
    <value model="stock.inventory" search="[('state','in',['confirm', 'draft']),('id', '=', ref('inventory'))]" />
</function>
```

if the search does not match, the error occurs

This patch avoid this exception:
```
diff --git a/addons/stock_account/models/stock.py b/addons/stock_account/models/stock.py
index 6b28ed1de98..d5ca50bba24 100644
--- a/addons/stock_account/models/stock.py
+++ b/addons/stock_account/models/stock.py
@@ -22,6 +22,7 @@ class StockInventory(models.Model):

     @api.multi
     def post_inventory(self):
+        res = None
         acc_inventories = self.filtered(lambda inventory: inventory.accounting_date)
         for inventory in acc_inventories:
             res = super(StockInventory, inventory.with_context(force_period_date=inventory.accounting_date)).post_inventory()
```

**Comment by pedrobaeza** [comment] 2020-03-09 16:32
Yes, but that's something incorrect in your code, so it's not something that is going to happen if everything is correctly coded. And I would say that these are very bad practices IMO to do that kind of things on XML data.

Any way, closing this as no issue, but bad code. You can propose any way a pull request with your patch, but being an improvement, I doubt this is going to be accepted on stable, but only on master branch.

**Closed by pedrobaeza** 2020-03-09 16:32 UTC
Labels: Need information

**Comment by olaf-wagner** [comment] 2020-03-15 10:13
This is a simple fix heeding basic programming conventions. It prevents the user from non-understandable error messages in situations that cannot be foreseen. This was at least the case in our use case. I don't understand why such fixes are not simply merged.
The bad code is the missing variable initialization in method post_inventory.

**Comment by sswapnesh** [comment] 2020-03-16 17:50
Duplicate of https://github.com/odoo/odoo/issues/29694 https://github.com/odoo/odoo/issues/37554

**Comment by sswapnesh** [comment] 2020-03-16 18:12
Added fix at https://github.com/odoo/odoo/pull/47727

@khaeusler  Instead of `None`, I set it to `self.env['stock.move']`

**Comment by sswapnesh** [comment] 2020-05-14 16:42
FYI, This has been fixed in https://github.com/odoo/odoo/pull/48733/commits/b6e77f7220a359e2bca97a66971873041d6429dc

**Comment by olaf-wagner** [comment] 2020-05-14 18:42
On Thu, 14 May 2020 09:42:20 -0700
Swapnesh Shah <notifications@github.com> wrote:

> FYI, This has been fixed in https://github.com/odoo/odoo/pull/48733/commits/b6e77f7220a359e2bca97a66971873041d6429dc

Thank you!

-- 
Olaf Wagner -- elego Software Solutions GmbH -- http://www.elegosoft.com 
               Gustav-Meyer-Allee 25 / Gebäude 12, 13355 Berlin, Germany
Geschäftsführer: Olaf Wagner | Sitz: Berlin
Handelregister: Amtsgericht Charlottenburg HRB 77719 | USt-IdNr: DE163214194
