### ISSUE TITLE
Problem with Odoo Studio. Unable to Undo the Changes

### ISSUE THREAD

**Issue by DonFeraRRi** [odoo/odoo#39047] opened 2019-10-18 14:30 UTC
Impacted versions: 12

Steps to reproduce: I Removed the Order Ref. Field in PO screen and then Again added it to the view. (Using Odoo Studio)

Current behavior: Its not taking the original Place where it is by default present.

Expected behavior: From the place where I removed it, I should be able to add it on the same place

**Comment by pedrobaeza** [comment] 2019-10-18 14:44
Although this is an enterprise problem and you should report it through odoo.com/enterprise, I'll ask you to say that this is not a bug, but not the way it should be handled.

If you remove it by error, just don't save, or if you have saved it, then remove the custom view with Odoo studio for returning to original state.

If you are not happy with my answer, please submit the corresponding enterprise ticket.

Closing as no issue.

**Closed by pedrobaeza** 2019-10-18 14:44 UTC
