### ISSUE TITLE
BUG: Customer invoice created in a purchase journal

### ISSUE THREAD

**Issue by zaoral** [odoo/odoo#54580] opened 2020-07-16 13:13 UTC
### Impacted versions:

13.0

### Steps to reproduce:

1. Activate developer mode
2. Go to Accounting / Vendors / Bills menu
3. Create a new bill and save it
4. Open the developer tools menu and click on "Set Defaults" options
5. select the option "Default: Journal = Vendor Bills" and save default
6. Go to Accounting / Customers / Invoices menu
7. Create and validate an invoice

### Current behavior:

A customer invoice (sales) has been created in a vendor bill journal (purchase).

### Expected behavior:

Obliviously this an user error when creating the default, but this should not be posible. at least should be a constraint that do not let to create a customer invoice in a purchase journal. 

**More important** This also need to be applied for the inverted case: we should not be able to create a purchase invoice in a customer invoice journal, this affect directly when we have electronic invoicing going on because we are creating a invoice and reporting to the government that is wrong is not issue by us is a vendor bill trying to be reported as customer invoice.

**Comment by zaoral** [comment] 2020-07-16 13:15
FYI OPW-2300349

**Comment by pedrobaeza** [comment] 2020-07-16 14:02
I don't see this as an error. Filling Odoo with constraints for every possible bad use of the system (and not through regular UI, but setting defaults, which is a developer operation - you need developer mode for that -), is not a good habit. You must know what are you doing.

You have filled OPW, but I suppose/hope the answer from support team will be similar.

**Comment by Yenthe666** [comment] 2020-07-16 16:15
If you use and set defaults you should know what you're doing. I agree with Pedro. If we start 'fixing' and blocking this kind of stuff we need to add in checks all over the place. I assume Odoo will say the same.

**Comment by zaoral** [comment] 2020-07-17 15:22
Hi @pedrobaeza @Yenthe666 
Thank you for your feedback is valuable.

I agreed with you about that we should not need to add checks all over Odoo to ensure the cases of a misconfiguration of the user, but I also still think that in the case of the customer electronic invoices is really a delicate issue that need to be restrict some way because the legal implications.

We have a couple of customers that have this problem and we think will be great to avoid it somehow. This is just a thought lets that we think it contributes in general to other locations with electronic invoicing , lets going to wait Odoo response. 

Best Regards

**Comment by jjscarafia** [comment] 2020-07-18 01:05
Hi! I agree that is not really a bug but IMHO it could be very harmful and also very easy to fix.
In countries where you use electronic invoice, using a sales journals may implied that the invoice is validated as a customer one, of course each localization could take care of it, but a constraint checking journal type and invoice type seems a good idea to me.

Not only because of the user default value, you can also get into this error by a wrong import, mass editing, etc.

I agree is not super critical, but IMHO there are lot of constraints in odoo that has less importance that the one that could be added to improve this.

Are only github issues for bugs or also enhancements? I agree I would rename the issue title

I believe that setting user defaults is common, can be done for any user and in this case can be very dangerous (for electronic invoice, wrong vat declaration, etc)
![image](https://user-images.githubusercontent.com/3016656/87841133-9125e800-c879-11ea-913b-0fd6e7cff173.png)

**Comment by pedrobaeza** [comment] 2020-08-14 17:14
Was there any feedback from OPW team?

**Comment by jjscarafia** [comment] 2020-08-18 02:05
@pedrobaeza they told us "This is standard behavior as vendor bills and customer invoices share the same model (account.move). The system is behaving how it was configured. "
We have added a constrain on our side to take care of this for now. Should we leave the issue open? IMHO, yes, there is place for a in improvement there..

**Comment by Yenthe666** [comment] 2020-08-18 06:06
Well it doesn't have much use to keep it open to me. If the Odoo support said it is expected behaviour then there is nobody going to change this probably.

**Comment by pedrobaeza** [comment] 2020-08-18 07:28
Yes, let's close it, as this is not going to be changed.

**Closed by pedrobaeza** 2020-08-18 07:28 UTC
Labels: 13.0, Accounting, OE

**Comment by nhomar** [comment] 2020-08-18 09:21
>> A customer invoice (sales) has been created in a vendor bill journal (purchase).

I agree this is not a bug. you can use a journal for any kind of document, thats why I hate base electronic invoice base on journal configuration.

but we know the current design on the l10n_** your localization can have a raise but i agree in general it is not a bug.

Journals   should only give default values they technically should not be the handlers of the behavior of the documents (as less as possible).
