### ISSUE TITLE
V14 website issues

### ISSUE THREAD

**Issue by kig-odoo** [odoo/odoo#57604] opened 2020-09-14 07:51 UTC
Hello, 

@qsm-odoo , @JKE-be , @rdeodoo  I hope you’re doing well

You guys and your team did a great job for website V14. I've seen the website/web_editor module especially the editor part it's awesome. I'm still exploring the website and its new cool features. 

Somehow I found some bugs/imp on the website while I'm exploring the website. can you please check it out if you have time. I fixed some of them by myself. I have not fixed a few of them because I think you guys will have a better solution.

I'm not sure we should consider this all points as a bug or not. I've just noticed these things.

1. Few snippet options are refreshing all public widgets inside it's `$target` on hover. Especially when we are changing color with color picker see: https://drive.google.com/file/d/1bFPjuQpTHNk8H5KHhMfRwxqDYKPwKFAb/view?usp=sharing

2. Save snippet as a Block option may need to destroy all publicWidgets inside it before saving. see: https://drive.google.com/file/d/14If1TOctucy9Gb8mDP9cF2H3Q_zj2Fw4/view. I didn't investigate much into this but I'm a bit curious to see how dynamic snippet, Product snippet will behave with the same case. Because I think right now we are saving the whole HTML of the snippet when we saving block as a snippet. it works well right now because we are removing content before appending new content.

3. Media dialog creating attachment whenever we change the image. Even if I use previously optimized images for the same block. see: https://drive.google.com/file/d/1xMEGSjiiMiwjdBB1AHAkGZtaVezFoazy/view?usp=sharing

4. Image optimization / Filter option performing network requests each time on mouse hover. https://drive.google.com/file/d/1vp_16mIfdCL0GnL3bQE56sPOkzadR0Nk/view?usp=sharing  I tested it locally and it will block the editor for a few minutes. if the same thing happened in the production server it will block the editor for a long time. Maybe we should set `data-no-preview="true"` on such options.

5. `portal_security.xml` file is loading everywhere on the website. see: https://drive.google.com/file/d/1N5JwoBKildvAUYcaWXw4LCoGwNa0BJUs/view?usp=sharing it's loading from here: https://github.com/odoo/odoo/blob/master/addons/portal/static/src/js/portal.js#L166

6. `ColorpickerWidget` unnecessary continuously firing`trigger_up` event on drag over. (FIXED IN: https://github.com/odoo/odoo/pull/57600)

7. Not able to remove the image from the media dialog. see https://drive.google.com/file/d/10yKkx6pJ83Ulkq_-k9kpCaxKXDvFnGvO/view?usp=sharing (FIXED IN: https://github.com/odoo/odoo/pull/57601)

8. `ImageCropWidget` not showing an active aspect ratio.  (FIXED IN: https://github.com/odoo/odoo/pull/57599)

Wating for your response.

Stay safe and healthy :mask:

**Comment by JKE-be** [comment] 2020-09-14 08:46
@sdegueldre 

Here, maybe a good start for the performance task created last week.
Thx

**Comment by sdegueldre** [comment] 2020-09-17 08:44
1: @qsm-odoo I guess we probably need to do a pass on all snippet options and disable public widget refresh for those that don't need them? I don't quite remember why we need a refresh by default.

2: Thanks for the report, I'll look into it.

3: Kind of an edge case since this will only happen if you reselect the already selected image in the media-dialog, which shouldn't happen often in practice, but since it's an easy fix: #57910

4: As you can see in your network logs: there is actually 0 bytes transferred. There are objectURLs that are stored by the browser in-memory or on disk, they are similar to base64 data-urls, and if you check the "hided data URLs" checkbox in chrome they will not show up. There is actually no network activity for those requests. The stalling behaviour you are observing is caused by 2 things:
- You have cache disabled in chrome, this will cause chrome to reload the image data from the server every time the filter or quality is changed, because it's first loaded into an out-of-document <img>. This will cause a real network request, but it doesn't show up in your network tab because you only show XHRs. When caching behaviour is available it will improve performance by a lot already, and some other browsers will not reload images that have already been loaded in the current page even with cache disabled (eg firefox)
- Image and filters, despite being almost all done on the GPU using shaders, still takes some time, and the larger the image the more time it takes. Currently, when you hover an item in the selection menu, we apply all previews in order. This is not ideal and we're working on a solution but it's not entirely obvious how to do this while preserving consistency, but we have something in the works.

5: Fixed at https://github.com/odoo/odoo/commit/5d25d0e9270145866fed2e75ee77eec49589925b

6: @qsm-odoo can't say I know the colorpickers enough to evaluate the fix, can you take a look?

7: We have a fixed lined up already which is waiting to be merged.

8: Good catch, I've made a patch that preserves the color-scheme of the editor instead of using btn-secondary, and I've also made them change in real time when you click on them instead of only on first load: #57915

**Comment by qsm-odoo** [comment] 2020-09-17 16:31
@sdegueldre 

1. debatable: a public widget may rely on anything in the DOM, who knows: someone in the community may implement a widget which relies on the background color of the snippet... so seems a good idea to refresh widgets linked to a snippet when the snippet is edited, whatever the options. But this maybe creates more problems than it solves, so not sure.

**Comment by kig-odoo** [comment] 2020-09-18 10:26
1: @qsm-odoo  On color pallet hover, it refreshes public widgets maybe it kind of acceptable. but on color picker drag over it also refreshing all public widgets it kind of strange. What if snippet inside the $target is making RPC. For example, in product Dynamic, Dynamic product snippet, etc.  I've tested it's making RPC after a few microseconds each time on mouse drag over and ultimately it blocks the editor for few seconds.

Also, I've found something in the existing code that doesn't refresh the publicWidgets based on option see: https://github.com/odoo/odoo/blob/master/addons/website/static/src/js/editor/snippets.options.js#L603 but I'm not sure it is useful or not. Because such an option will avoid refreshing all public widgets in the snippet (even if the snippet needs refresh). I think this needs to be decided by the public widget itself as a public widget is an actual entity that renders and destroy the content. I think some parameters like `refreshDOM` in the start and destroy will be enough. Then the public widget will decide whether it wants to remove and rerender or not. I think this will work well because of a public widget usees `attachTo`. This option will be true by default and needs to be passed via trigger of start public widget. Any thoughts on this @qsm-odoo 

7: @sdegueldre Can you give me PR that is waiting? Also, my PR has 2 commits and a second commit which removes some dead code. BTW this PR is super simple, you can merge it directly. Also, let me know if my PR is not needed, I'm happy to close my PR :smile: 

8: @sdegueldre I think you didn't test my branch. It's working in real-time too.

I've seen your PR. you've written Javascript code to toggle 'active' Class.
As we have `data-toggle="buttons"` attribute on `btn-group` bootstrap will toggle active class automatically so we don't need to write custom javascript code to toggle active class. 
https://getbootstrap.com/docs/4.4/components/buttons/#checkbox-and-radio-buttons

As far as color-scheme is concern. I can adapt to the editor's color-scheme in my PR. Also if you have any doubts on my PR you can always ask :smile:

**Comment by kig-odoo** [comment] 2020-10-07 07:15
Hello @qsm-odoo @JKE-be,

Closed one PR https://github.com/odoo/odoo/pull/57601 a few days ago.
now closing second PR https://github.com/odoo/odoo/pull/57599 PR now, it will be fixed in https://github.com/odoo/odoo/pull/57915 PR.

@sdegueldre it just a few lines of code, and it does not matter to me much. But authorship would have been nice :wink: 

I think it would be good if I just create an issue instead of fixing it :smile: 
Here is an issue that I found for the website https://github.com/odoo/odoo/issues/59337.

**Comment by sdegueldre** [comment] 2020-10-07 10:13
@kig-odoo Ah sorry, added you as a co-author.

**Comment by kig-odoo** [comment] 2020-10-07 11:37
@sdegueldre no worries :wink: 
BTW you did a great work with background shapes I really appreciate it :blush:

**Comment by sdegueldre** [comment] 2020-10-09 13:33
@kig-odoo Alright, I think we handled all the problems you raised in this issue (except for the snippet-saving feature, but the issue appears to be bigger than just stopping the public widgets before saving, as we're actually not doing any cleanup before saving, I have created a task internally so we can deal with this issue).

Thank you for the report and for your work! If you run into any more problems feel free to open new issues, although I would appreciate if you could create one issue per bug, as it makes it easier to track and keep all the relevant information in a single place rather than having to read through a thread with 7 separate issues :+1:

**Closed by sdegueldre** 2020-10-09 13:33 UTC
Labels: 14.0, Website
