### ISSUE TITLE
[11.0] Google spreadsheet does not connect with odoo.

### ISSUE THREAD

**Issue by rubwedoo12** [odoo/odoo#25361] opened 2018-06-20 16:06 UTC
Impacted versions: 
11.0
Steps to reproduce:
Previously i downloaded the Google Drive  and Google Spreadsheet module.
1.- Enable de google drive´s option in General Settings (Developer mode on)
2.- Enable Google Spreadsheet´s integration
3.- Generate Authorization code from google
4.- Copy it and paste it in the blank space
5.- Save configuration.
6.- Go to CMR,  above of the search and filter bar click Favorites - > Add to a Google´spreadsheet. (it opens a emergent window)
7.- Configure the server options in menu Odoo in Spreadsheet.
8.- Once configured, get in Google´s spreadsheet go to Odoo -> Insert Selection Field (i inserted the next filter: "res.partner","name",[]. it just to check if it is working)
and i get the next message.
![screenshot3](https://user-images.githubusercontent.com/40434432/41669630-d6f10f20-7477-11e8-80bf-def58d47ed88.png)

Current behavior:
The filter in the spreadsheet does not work, it send error message when i inserted the filter manually also when it get me redirected from odoo´s CMR to the google´s spreadsheet.
![screenshot3](https://user-images.githubusercontent.com/40434432/41670221-55ee0ce6-7479-11e8-8027-6fe627931d38.png)

Expected behavior:
I hope that it can works for connect the CMR´s module and allow me make a live integration with the task/opportunities in a google´s spreadsheet.
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2018-06-22 18:06
This seems something of your deployment. Can you please try to reproduce the problem on runbot?

**Comment by rubwedoo12** [comment] 2018-06-25 14:36
@pedrobaeza I have tried it on runbot (all versions of odoo) but i still getting the same message, i configured too the spreadsheet´s authorization and i generated the credentials from the developer console of google again, but it still not working.

**Comment by pedrobaeza** [comment] 2018-06-25 14:38
I'm not having that kind of troubles. @mart-e what do you recommend in this case?

**Comment by mart-e** [comment] 2018-06-25 14:45
Could you set a [dbfilter](https://www.odoo.com/documentation/11.0/setup/deploy.html#dbfilter) on your database? It seems the issue is that it tries to access `/web/database/selector/web/session/authenticate` while it should only be `/web/session/authenticate`

Also, try to see on your server logs if you do not have the full traceback.

**Comment by rubwedoo12** [comment] 2018-06-26 15:26
Thanks for the help, i checked again the server access option´s from the odoo´s menu on the spreadsheet, then I modify the URL shortened to .com without the /. The url is now like that: https://odootest.######.com
It works for me. But in some cases i still getting an error from the verification code from google drive.

**Comment by pedrobaeza** [comment] 2018-06-26 15:31
Then it seems clear that the problem is with your deployment and the problem is for not filtering DBs. Closing this.

**Closed by pedrobaeza** 2018-06-26 15:31 UTC
Labels: 11.0, Need information, Services
