### ISSUE TITLE
[10.0] Expected singleton when deactivating language

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#21418] opened 2017-12-04 10:03 UTC
Impacted versions: 10.0

Steps to reproduce:
- Install a new language
- Open the language and click on "Deactivate"
![image](https://user-images.githubusercontent.com/6352350/33546866-7b2a9412-d8e2-11e7-818e-6a5be3801dc0.png)

You'll now get a traceback:
![image](https://user-images.githubusercontent.com/6352350/33546831-5ec2581e-d8e2-11e7-8887-08c0443bb1d8.png)

The issue is coming from https://github.com/odoo/odoo/blob/ab52c636c34b6f8b472a3b45ee162824de08fca4/odoo/addons/base/res/res_lang.py#L227

Current behavior:
Expected singleton error.

Expected behavior: Language is deactivated.

**Comment by nim-odoo** [comment] 2017-12-06 08:02
I can't reproduce this on latest runbot. Anyway, this traceback means that there would be more than one default value for a partner's lang... which should not be the case.

**Comment by Yenthe666** [comment] 2017-12-06 08:16
Hi @nim-odoo,

Nope - it seems to be fixed in the meanwhile. Tested it on two runbots two days ago and both failed. Today I've tested on two new runbots and now it is working. Thanks.

**Comment by Yenthe666** [comment] 2017-12-06 08:30
Actually, no the bug is still there. We just figured out there is another step. You first need to set the just installed language to a customer and then try to deactive the language.
Latest runbot 10:
![image](https://user-images.githubusercontent.com/6352350/33651958-dd14b8f2-da67-11e7-8497-a268b1785000.png)

Customer:
![image](https://user-images.githubusercontent.com/6352350/33652026-1b8c9de8-da68-11e7-95b5-1750d5fb5d7e.png)

**Comment by nim-odoo** [comment] 2017-12-06 08:34
Should be fixed with #21460

**Comment by Yenthe666** [comment] 2017-12-06 08:38
@nim-odoo great, thanks! On a sidenote: If you do the same behaviour in V11 it does it a bit different:
- Install new language
- Add this new language to a user
- Deactivate language
It will work but the language is still set on the customer. What will happen from a functional point of view with this though? Is this absolutely intended?

**Comment by nim-odoo** [comment] 2017-12-06 09:18
That'll still be the case in v10 after the fix. This part of code simply removes the deactivated language as the default value. From a functional PoV, it will switch to English since the language set on the user cannot be found.

**Comment by Yenthe666** [comment] 2017-12-06 09:25
Thanks for the feedback. I believe that from a functional PoV this is probably not great.

Imagine that I have a database with five languages and 3.000 customers. From those 3.000 customers 500 of them are using Dutch, the language that I wish to deactivate.
After I've deactivated the language I have 500 customers with a language set to Dutch which I, as an enduser, still believe is correct. However, all communication to the customer will be in English while the enduser wouldn't even know it. 

Some better solutions would be:
- The language is removed on all the customers that match
- You have the ability to choose what to do with your customers (remove language, keep language).

Just my five cents. Thanks a lot for the fix too.

**Comment by nim-odoo** [comment] 2017-12-06 10:44
Nope, it will appear as "Unknown" in the partner form view.

**Closed** 2017-12-06 11:03 UTC
Labels: 10.0, Internationalization
