### ISSUE TITLE
Stock Picking with 500 moves too slow to edit Done Quantity

### ISSUE THREAD

**Issue by pdyharshad** [odoo/odoo#30880] opened 2019-02-06 12:16 UTC
Impacted versions: 11.0

Steps to reproduce: 
1. Create Purchase order with 500 lines with products having no tracking. 
2. Confirm Order
3. Go to picking, change the Done Quantity and press enter.

Current behavior: Onchange on Picking is called which takes approx. 20 seconds

Expected behavior: Tested same with V12 and it takes 3 seconds

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/10510733/52339883-56891080-2a34-11e9-9dfb-d88f2db47a28.png)
![image](https://user-images.githubusercontent.com/10510733/52339907-6ef92b00-2a34-11e9-90f2-3f0e501ade9a.png)

[profile.txt](https://github.com/odoo/odoo/files/2836271/profile.txt)

**Comment by pedrobaeza** [comment] 2019-02-06 12:23
Is this a pure Odoo without extra modules?

**Comment by pdyharshad** [comment] 2019-02-06 13:49
> Is this a pure Odoo without extra modules?

I checked it again with new pull and new db. Its still the same.

**Comment by pedrobaeza** [comment] 2019-02-06 13:54
Well, this might happen and of course the ideal thing is to improve it, but not having anything more but the complaint that it's slow doesn't help. @rco-odoo is aware of the performance problems on certain parts, they are partly solved in v12, and his team continue working on this area version per version. Migrate as soon as possible to v12 to get that enhancements, or propose specific improvements that don't violate stability policy for the current one.

Closing this by the stated above.

**Closed by pedrobaeza** 2019-02-06 13:54 UTC

**Comment by jfreres** [comment] 2019-02-14 05:52
This performance bug is reproduced by 3. Mark qty done of 1 although the order was 2. Then generated back orders timeout due to cpu timeout.
