### ISSUE TITLE
[9.0] @api.v7 Read method in models.py is bugged 

### ISSUE THREAD

**Issue by gaudaost** [odoo/odoo#10664] opened 2016-01-28 14:54 UTC
When using the @api.v7 version on the model project.task, I get the following stack trace:

> Traceback (most recent call last):
>   File "/home/gaudaost/Documenti/Workspaces/Traipler/Traipler Sviluppo/openerp/http.py", line 643, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/home/gaudaost/Documenti/Workspaces/Traipler/Traipler Sviluppo/openerp/http.py", line 680, in dispatch
>     result = self._call_function(*_self.params)
>   File "/home/gaudaost/Documenti/Workspaces/Traipler/Traipler Sviluppo/openerp/http.py", line 316, in _call_function
>     return checked_call(self.db, *args, *_kwargs)
>   File "/home/gaudaost/Documenti/Workspaces/Traipler/Traipler Sviluppo/openerp/service/model.py", line 118, in wrapper
>     return f(dbname, _args, *_kwargs)
>   File "/home/gaudaost/Documenti/Workspaces/Traipler/Traipler Sviluppo/openerp/http.py", line 309, in checked_call
>     result = self.endpoint(_a, *_kw)
>   File "/home/gaudaost/Documenti/Workspaces/Traipler/Traipler Sviluppo/openerp/http.py", line 959, in __call__
>     return self.method(_args, *_kw)
>   File "/home/gaudaost/Documenti/Workspaces/Traipler/Traipler Sviluppo/openerp/http.py", line 509, in response_wrap
>     response = f(_args, *_kw)
>   File "/home/gaudaost/Documenti/Workspaces/Traipler/Traipler Sviluppo/enterprise/addons/web/controllers/main.py", line 907, in call_kw
>     return self._call_kw(model, method, args, kwargs)
>   File "/home/gaudaost/Documenti/Workspaces/Traipler/Traipler Sviluppo/enterprise/addons/web/controllers/main.py", line 899, in _call_kw
>     return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
>   File "/home/gaudaost/Documenti/Workspaces/Traipler/Traipler Sviluppo/openerp/api.py", line 250, in wrapper
>     return old_api(self, _args, *_kwargs)
>   File "/home/gaudaost/Documenti/Workspaces/Traipler/Traipler Sviluppo/addons/sale_service/models/sale_service.py", line 132, in write
>     res = super(project_task, self).write(cr, uid, ids, values, context=context)
>   File "/home/gaudaost/Documenti/Workspaces/Traipler/Traipler Sviluppo/openerp/api.py", line 250, in wrapper
>     return old_api(self, _args, *_kwargs)
>   File "/home/gaudaost/Documenti/Workspaces/Traipler/Traipler Sviluppo/traipler_addons/traipler_sandbox/models/models.py", line 146, in write
>     test=self.read(cr, uid, [1],[])
>   File "/home/gaudaost/Documenti/Workspaces/Traipler/Traipler Sviluppo/openerp/api.py", line 250, in wrapper
>     return old_api(self, _args, *_kwargs)
>   File "/home/gaudaost/Documenti/Workspaces/Traipler/Traipler Sviluppo/openerp/models.py", line 3175, in read
>     result = BaseModel.read(records, fields, load=load)
>   File "/home/gaudaost/Documenti/Workspaces/Traipler/Traipler Sviluppo/openerp/api.py", line 248, in wrapper
>     return new_api(self, _args, *_kwargs)
>   File "/home/gaudaost/Documenti/Workspaces/Traipler/Traipler Sviluppo/openerp/models.py", line 3210, in read
>     self._read_from_database(stored, inherited)
>   File "/home/gaudaost/Documenti/Workspaces/Traipler/Traipler Sviluppo/openerp/api.py", line 248, in wrapper
>     return new_api(self, _args, *_kwargs)
>   File "/home/gaudaost/Documenti/Workspaces/Traipler/Traipler Sviluppo/openerp/models.py", line 3401, in _read_from_database
>     res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
>   File "/home/gaudaost/Documenti/Workspaces/Traipler/Traipler Sviluppo/openerp/osv/fields.py", line 1497, in get
>     result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
>   File "/home/gaudaost/Documenti/Workspaces/Traipler/Traipler Sviluppo/openerp/osv/fields.py", line 1569, in _related_read
>     res[record.id] = value[self.arg[-1]]
>   File "/home/gaudaost/Documenti/Workspaces/Traipler/Traipler Sviluppo/openerp/models.py", line 5721, in __getitem__
>     return self._fields[key].__get__(self, type(self))
> KeyError: 'user_id'

user_id is a field in the project.task model.

**Steps to reproduce:**
Add the following method to the model project.task and execute:

```
@api.v7
def read_test(self,cr, uid, id, vals,context=None):
     test=self.read(cr, uid, [id],[])
```

It seems to generate the error when executing `result = BaseModel.read(records, fields, load=load)` on line 3175 in openerp/models.py

**Comment by rco-odoo** [comment] 2016-02-04 13:12
@gaudaost the stack trace does not suggest that at all to me.
The method `_read_from_database` evaluates a related field, which accesses the field `user_id` of a record that does not have such a field. The definition of the related field (`'something.user_id'`) is probably wrong.

**Comment by rco-odoo** [comment] 2016-02-04 13:16
@gaudaost your bug is probably a duplicate of #10499.

**Comment by pedrobaeza** [comment] 2018-04-11 22:37
Closing as duplicate of #10499

**Closed by pedrobaeza** 2018-04-11 22:37 UTC
Labels: Duplicate
