### ISSUE TITLE
[v8] Unable to add delivery address

### ISSUE THREAD

**Issue by bringsvor** [odoo/odoo#2316] opened 2014-09-10 10:42 UTC
Hi

I have a company without default accounts receiveable and payable configured.

1. Create a customer, specify accounts receiveable and payable. Save.
2. Create a sales order, click on "Create or edit" on the delivery address to make a new address.
3. Specify the customer created above as the parent, define an address. The Accounting tab says that: "Accounting-related settings are managed on the parent company"
4. Try to save. You cannot because you are missing accounts receiveable and payable.

This must be a bug? Using todays version straight from github.

**Comment by Yenthe666** [comment] 2016-06-03 10:27
Hi @bringsvor,

Just like @jco-odoo I could no longer reproduce this issue on the latest code from V8.
I'm closing this issue since I cannot reproduce this.
Please update your Odoo environment and it should be fixed. If you still face this issue please post on this thread and give us some more information on how to reproduce this.

Regards,
Yenthe

**Closed by Yenthe666** 2016-06-03 10:27 UTC
