### ISSUE TITLE
[13.0 / 14.0] : After warning in change password popup, wizard is useless, can't perform anything.

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#63607] opened 2020-12-19 13:01 UTC
Impacted versions:  13.0 / 14.0

Steps to reproduce:
 - Go to Users
 - select any no. of users, 
 - Go to action > Change Password,
 - Do not enter password and click on button 'Change Password'
 - Warning will appear. and click on OK button.

Current behavior:
- its wiping user's data (User's name) from popup so not able to change password, Need to close the wizard and have to go again to open the same popup. 
- Here even if we selecting multiple users,and not entering password in some user by mistake, it wiping User's name from all records of popup, but not wiping password. See below screenshots for ref.

Expected behavior:
- It should allow to change password in same popup, or should give capability to enter the password again.

Video/Screenshot link (optional):
[Video Link](https://drive.google.com/file/d/1zl2AiXJB18seu_xNDXmipECBlMkE5HM6/view?usp=drivesdk)

![image](https://user-images.githubusercontent.com/35560490/102689843-6d4f3f80-4227-11eb-9724-0124c7a6bdf5.png)
![image](https://user-images.githubusercontent.com/35560490/102689855-7fc97900-4227-11eb-8689-85fdb539e26b.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by sswapnesh** [comment] 2020-12-21 03:30
Duplicate of https://github.com/odoo/odoo/issues/48379

**Closed** 2020-12-21 07:13 UTC
