### ISSUE TITLE
Odoo pos not opening for users other than admin

### ISSUE THREAD

**Issue by tinasanthosh** [odoo/odoo#31867] opened 2019-03-15 10:04 UTC
Impacted versions: version 10 community edition

Steps to reproduce:

Current behavior: The DB is a multi company scenario. I have created two different pos users for the branches of the company. The pos is easily accessible using the admin id but i am getting a TRaceback error when i try to open the pos using the pos users. 

Expected behavior:

Should be able to use pos using the pos users
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2019-03-15 10:12
Which traceback?

**Comment by tinasanthosh** [comment] 2019-03-15 10:53
web.assets_common.js:3028 Server application error {"message":"Odoo Server Error","code":200,"data":{"debug":"Traceback (most recent call last):\n  File \"/usr/lib/python2.7/dist-packages/odoo/http.py\", line 641, in handle_exception\n    return super(JsonRequest, self)._handle_exception(exception)\n  File \"/usr/lib/python2.7/dist-packages/odoo/http.py\", line 683, in dispatch\n    result = self._call_function(**self.params)\n  File \"/usr/lib/python2.7/dist-packages/odoo/http.py\", line 333, in call_function\n    return checked_call(self.db, args, *kwargs)\n  File \"/usr/lib/python2.7/dist-packages/odoo/service/model.py\", line 101, in wrapper\n    return f(dbname, args, *kwargs)\n  File \"/usr/lib/python2.7/dist-packages/odoo/http.py\", line 326, in checked_call\n    result = self.endpoint(*a, *kw)\n  File \"/usr/lib/python2.7/dist-packages/odoo/http.py\", line 941, in __call__\n    return self.method(*args, *kw)\n  File \"/usr/lib/python2.7/dist-packages/odoo/http.py\", line 506, in response_wrap\n    response = f(*args, **kw)\n  File \"/usr/lib/python2.7/dist-packages/odoo/addons/bus/controllers/main.py\", line 35, in poll\n    raise Exception(\"bus.Bus unavailable\")\nException: bus.Bus unavailable\n","exception_type":"internal_error","message":"bus.Bus unavailable","name":"exceptions.Exception","arguments":["bus.Bus unavailable"]}}
(anonymous) @ web.assets_common.js:3028
web.assets_common.js:3028 Server application error {"message":"Odoo Server Error","code":200,"data":{"debug":"Traceback (most recent call last):\n  File \"/usr/lib/python2.7/dist-packages/odoo/http.py\", line 641, in handle_exception\n    return super(JsonRequest, self)._handle_exception(exception)\n  File \"/usr/lib/python2.7/dist-packages/odoo/http.py\", line 683, in dispatch\n    result = self._call_function(**self.params)\n  File \"/usr/lib/python2.7/dist-packages/odoo/http.py\", line 333, in call_function\n    return checked_call(self.db, args, *kwargs)\n  File \"/usr/lib/python2.7/dist-packages/odoo/service/model.py\", line 101, in wrapper\n    return f(dbname, args, *kwargs)\n  File \"/usr/lib/python2.7/dist-packages/odoo/http.py\", line 326, in checked_call\n    result = self.endpoint(*a, *kw)\n  File \"/usr/lib/python2.7/dist-packages/odoo/http.py\", line 941, in __call__\n    return self.method(*args, *kw)\n  File \"/usr/lib/python2.7/dist-packages/odoo/http.py\", line 506, in response_wrap\n    response = f(*args, **kw)\n  File \"/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py\", line 832, in search_read\n    return self.do_search_read(model, fields, offset, limit, domain, sort)\n  File \"/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py\", line 854, in do_search_read\n    offset=offset or 0, limit=limit or False, order=sort or False)\n  File \"/usr/lib/python2.7/dist-packages/odoo/models.py\", line 4709, in search_read\n    result = records.read(fields)\n  File \"/usr/lib/python2.7/dist-packages/odoo/models.py\", line 3020, in read\n    values[name] = field.convert_to_read(record[name], record, use_name_get)\n  File \"/usr/lib/python2.7/dist-packages/odoo/models.py\", line 5224, in _getitem__\n    return self._fields[key].__get__(self, type(self))\n  File \"/usr/lib/python2.7/dist-packages/odoo/fields.py\", line 917, in _get__\n    value = record._cache[self]\n  File \"/usr/lib/python2.7/dist-packages/odoo/models.py\", line 5576, in __getitem__\n    return value.get() if isinstance(value, SpecialValue) else value\n  File \"/usr/lib/python2.7/dist-packages/odoo/fields.py\", line 48, in get\n    raise self.exception\nAccessError: (u'The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\\n\\n(Document type: pos.order, Operation: read)', None)\n","exception_type":"access_error","message":"The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\n\n(Document type: pos.order, Operation: read)\nNone","name":"odoo.exceptions.AccessError","arguments":["The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\n\n(Document type: pos.order, Operation: read)",null]}}
(anonymous) @ web.assets_common.js:3028
web.assets_common.js:3028 Server application error {"message":"Odoo Server Error","code":200,"data":{"debug":"Traceback (most recent call last):\n  File \"/usr/lib/python2.7/dist-packages/odoo/http.py\", line 641, in handle_exception\n    return super(JsonRequest, self)._handle_exception(exception)\n  File \"/usr/lib/python2.7/dist-packages/odoo/http.py\", line 683, in dispatch\n    result = self._call_function(**self.params)\n  File \"/usr/lib/python2.7/dist-packages/odoo/http.py\", line 333, in call_function\n    return checked_call(self.db, args, *kwargs)\n  File \"/usr/lib/python2.7/dist-packages/odoo/service/model.py\", line 101, in wrapper\n    return f(dbname, args, *kwargs)\n  File \"/usr/lib/python2.7/dist-packages/odoo/http.py\", line 326, in checked_call\n    result = self.endpoint(*a, *kw)\n  File \"/usr/lib/python2.7/dist-packages/odoo/http.py\", line 941, in __call__\n    return self.method(*args, *kw)\n  File \"/usr/lib/python2.7/dist-packages/odoo/http.py\", line 506, in response_wrap\n    response = f(*args, **kw)\n  File \"/usr/lib/python2.7/dist-packages/odoo/addons/bus/controllers/main.py\", line 35, in poll\n    raise Exception(\"bus.Bus unavailable\")\nException: bus.Bus unavailable\n","exception_type":"internal_error","message":"bus.Bus unavailable","name":"exceptions.Exception","arguments":["bus.Bus unavailable"]}}
(anonymous) @ web.assets_common.js:3028
(anonymous) @ web.assets_common.js:547
fire @ web.assets_common.js:541
fireWith @ web.assets_common.js:546
done @ web.assets_common.js:937
callback @ web.assets_common.js:957
XMLHttpRequest.send (async)
send @ web.assets_common.js:954
ajax @ web.assets_common.js:930
(anonymous) @ web.assets_common.js:3030
genericJsonRpc @ web.assets_common.js:3028
jsonRpc @ web.assets_common.js:3030
(anonymous) @ web.assets_common.js:3164
(anonymous) @ web.assets_common.js:547
fire @ web.assets_common.js:541
add @ web.assets_common.js:542
(anonymous) @ web.assets_common.js:547
each @ web.assets_common.js:370
(anonymous) @ web.assets_common.js:547
Deferred @ web.assets_common.js:548
then @ web.assets_common.js:547
rpc @ web.assets_common.js:3161
poll @ web.assets_backend.js:2917
web.assets_common.js:3028 Server application error {"message":"Odoo Server Error","code":200,"data":{"debug":"Traceback (most recent call last):\n  File \"/usr/lib/python2.7/dist-packages/odoo/http.py\", line 641, in handle_exception\n    return super(JsonRequest, self)._handle_exception(exception)\n  File \"/usr/lib/python2.7/dist-packages/odoo/http.py\", line 683, in dispatch\n    result = self._call_function(**self.params)\n  File \"/usr/lib/python2.7/dist-packages/odoo/http.py\", line 333, in call_function\n    return checked_call(self.db, args, *kwargs)\n  File \"/usr/lib/python2.7/dist-packages/odoo/service/model.py\", line 101, in wrapper\n    return f(dbname, args, *kwargs)\n  File \"/usr/lib/python2.7/dist-packages/odoo/http.py\", line 326, in checked_call\n    result = self.endpoint(*a, *kw)\n  File \"/usr/lib/python2.7/dist-packages/odoo/http.py\", line 941, in __call__\n    return self.method(*args, *kw)\n  File \"/usr/lib/python2.7/dist-packages/odoo/http.py\", line 506, in response_wrap\n    response = f(*args, **kw)\n  File \"/usr/lib/python2.7/dist-packages/odoo/addons/bus/controllers/main.py\", line 35, in poll\n    raise Exception(\"bus.Bus unavailable\")\nException: bus.Bus unavailable\n","exception_type":"internal_error","message":"bus.Bus unavailable","name":"exceptions.Exception","arguments":["bus.Bus unavailable"]}}
(anonymous) @ web.assets_common.js:3028
(anonymous) @ web.assets_common.js:547
fire @ web.assets_common.js:541
fireWith @ web.assets_common.js:546
done @ web.assets_common.js:937
callback @ web.assets_common.js:957
XMLHttpRequest.send (async)
send @ web.assets_common.js:954
ajax @ web.assets_common.js:930
(anonymous) @ web.assets_common.js:3030
genericJsonRpc @ web.assets_common.js:3028
jsonRpc @ web.assets_common.js:3030
(anonymous) @ web.assets_common.js:3164
(anonymous) @ web.assets_common.js:547
fire @ web.assets_common.js:541
add @ web.assets_common.js:542
(anonymous) @ web.assets_common.js:547
each @ web.assets_common.js:370
(anonymous) @ web.assets_common.js:547
Deferred @ web.assets_common.js:548
then @ web.assets_common.js:547
rpc @ web.assets_common.js:3161
poll @ web.assets_backend.js:2917
setTimeout (async)
(anonymous) @ web.assets_backend.js:2917
(anonymous) @ web.assets_common.js:547
fire @ web.assets_common.js:541
fireWith @ web.assets_common.js:546
deferred.(anonymous function) @ web.assets_common.js:548
fire @ web.assets_common.js:541
fireWith @ web.assets_common.js:546
deferred.(anonymous function) @ web.assets_common.js:548
fire @ web.assets_common.js:541
add @ web.assets_common.js:542
(anonymous) @ web.assets_common.js:547
fire @ web.assets_common.js:541
fireWith @ web.assets_common.js:546
deferred.(anonymous function) @ web.assets_common.js:548
fire @ web.assets_common.js:541
add @ web.assets_common.js:542
(anonymous) @ web.assets_common.js:547
fire @ web.assets_common.js:541
fireWith @ web.assets_common.js:546
done @ web.assets_common.js:937
callback @ web.assets_common.js:957
XMLHttpRequest.send (async)
send @ web.assets_common.js:954
ajax @ web.assets_common.js:930
(anonymous) @ web.assets_common.js:3030
genericJsonRpc @ web.assets_common.js:3028
jsonRpc @ web.assets_common.js:3030
(anonymous) @ web.assets_common.js:3164
(anonymous) @ web.assets_common.js:547
fire @ web.assets_common.js:541
add @ web.assets_common.js:542
(anonymous) @ web.assets_common.js:547
each @ web.assets_common.js:370
(anonymous) @ web.assets_common.js:547
Deferred @ web.assets_common.js:548
then @ web.assets_common.js:547
rpc @ web.assets_common.js:3161
poll @ web.assets_backend.js:2917

This is the error that i am getting

**Comment by pedrobaeza** [comment] 2019-03-15 11:06
Please get the information on the server side and on the client with debug mode activated.

**Comment by Yenthe666** [comment] 2019-04-09 06:11
Hi there,

We haven't recieved any feedback in almost a month. As we cannot reproduce the steps and miss information we're closing off this issue.
Don't hesitate to comment back with more information and we'll look into it again.

Regards,
Yenthe

**Closed by Yenthe666** 2019-04-09 06:11 UTC
Labels: 10.0, Need information, Point of Sale
