### ISSUE TITLE
POS rounding issue

### ISSUE THREAD

**Issue by uktc87504** [odoo/odoo#36732] opened 2019-09-11 17:30 UTC
Impacted versions: 
11.0

Steps to reproduce: 
1. create a new pos order with a product sale price 2.30 and discount 5%

Current behavior:
On PoS screen we can see In front end, on row it shows 2.19 and it total 2.18.

Expected behavior:
Rows (customer display, too) and total should match.

Video/Screenshot link (optional):
http://clearlypro.eu/pub/media/wysiwyg/odoo11_rounding_issue.png

**Comment by pedrobaeza** [comment] 2019-09-11 17:58
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by ammarofficewla** [comment] 2019-09-17 13:39
I am also faced rounding issue
Steps to reproduce:
   1. create a new pos order with a product sale price 58.95 and discount 10% 
Current behavior:
  On PoS receipt display product discounted price 53.06 and discount 5.90 total is 58.06.
  product original price not equal to product discounted price + discount
Expected behavior:
   Product original price == product discounted price + discount

**Comment by switch87** [comment] 2019-09-18 05:38
hi @uktc87504 , I tried to reproduce this on runbot but I was not able to. 
![Screenshot at 2019-09-18 07-38-04](https://user-images.githubusercontent.com/8284204/65114582-48966780-d9e7-11e9-80f1-b827da326347.png)

**Comment by sswapnesh** [comment] 2019-09-25 17:46
Seems working well with same Tax (5% Included in Price) amount  as well.

![Screenshot from 2019-09-25 23-12-36](https://user-images.githubusercontent.com/16624719/65625700-fc03eb00-dfe9-11e9-822b-f441d43f44ae.png)

**Comment by Yenthe666** [comment] 2019-09-25 17:51
@uktc87504 could you please test again and give us feedback?

**Comment by Yenthe666** [comment] 2019-12-03 07:53
Hi there,

Since there has been no extra information in quite a while I'm closing this issue.
Don't hesitate to respond back with detailed information and then we'll reopen this issue.

Regards,
Yenthe

**Closed by Yenthe666** 2019-12-03 07:53 UTC
Labels: 11.0, Need information, Point of Sale
