### ISSUE TITLE
Double kitchen order print click when just one click at pos using jposbox

### ISSUE THREAD

**Issue by loveismyside** [odoo/odoo#32398] opened 2019-04-03 15:14 UTC
Impacted versions: odoo 11CE

Hello everyone,

I want to ask one question. Please! Can you help me?

I using JPosbox when i printing kitchen order receipt paper with network.
But it made double paper retrieve just one click.
I want one click one kitchen order paper retrieve by network printer used JPosbox.

It there a solution to that? Please !

Regards.

**Comment by pedrobaeza** [comment] 2019-04-03 15:15
What is JPosbox?

**Comment by loveismyside** [comment] 2019-04-03 15:45
Hi @pedrobaeza, pos directly connected to Thermal printer without using posbox.

**Comment by pedrobaeza** [comment] 2019-04-03 15:49
But then there's no direct print, but a dialog with the PDF AFAIK.

**Comment by switch87** [comment] 2019-04-03 15:56
@loveismyside If the problem is not reproducible on the posbox the issue is for the jposbox project, it is not part of Odoo. I close this issue for now, if it is reproducible, please let us know to open the issue again.
https://github.com/andreubisquerra/jPosBox

**Closed by switch87** 2019-04-03 15:56 UTC

**Comment by switch87** [comment] 2019-04-03 16:02
> But then there's no direct print, but a dialog with the PDF AFAIK.

@pedrobaeza jposbox is an replacement for the posbox that doesn’t seem to use the original code but instead is written in java, so it does not profit of our bugfixes and visa versa :disappointed:

**Comment by pedrobaeza** [comment] 2019-04-03 16:04
Thanks for extra info, @switch87. I don't understand that double effort...

**Comment by switch87** [comment] 2019-04-03 16:12
@loveismyside You can also run your posbox locally without having to use 3th party software. This way you have support by Odoo for bugs. We do not give official support for the installation process though (except if the installation is failing due a bug) 
https://www.odoo.com/documentation/user/9.0/point_of_sale/overview/setup.html#posboxless-guide-advanced

**Comment by logicprime** [comment] 2020-06-03 13:05
> 
> 
> Impacted versions: odoo 11CE
> 
> Hello everyone,
> 
> I want to ask one question. Please! Can you help me?
> 
> I using JPosbox when i printing kitchen order receipt paper with network.
> But it made double paper retrieve just one click.
> I want one click one kitchen order paper retrieve by network printer used JPosbox.
> 
> It there a solution to that? Please !
> 
> Regards.

Double print problem.
Uncomment     self.receipt_queue.unshift(r); at line 35. 
addons/pos_restaurant/static/src/js/multiprint.js

**** If you use third party addon, also need to uncomment that line.

However jposbox is not compatible with Odoo13.0
