### ISSUE TITLE
Comparing apples and oranges log error.

### ISSUE THREAD

**Issue by JustRibokas** [odoo/odoo#56023] opened 2020-08-18 06:56 UTC
Impacted versions: Odoo12

Steps to reproduce: Testing custom functions

Current behavior: I get an error log odoo.models: Comparing apples and oranges: @ mrp.routing.workcenter(500,) == 4 (/home/myenvironment/Odoo12/odoo/odoo/fields.py:2553) 

Expected behavior: No error log 

Video/Screenshot link (optional): If im right this is an error in the source code.
    def write(self, records, value):
        comodel = records.env[self.comodel_name].with_context(**self.context)
        inverse = self.inverse_name
        vals_list = []                  # vals for lines to create in batch

        def flush():
            if vals_list:
                comodel.create(vals_list)
                vals_list.clear()

        def drop(lines):
            if getattr(comodel._fields[inverse], 'ondelete', False) == 'cascade':
                lines.unlink()
            else:
                lines.write({inverse: False})

        with records.env.norecompute():
            for act in (value or []):
                if act[0] == 0:
                    for record in records:
                        vals_list.append(dict(act[2], **{inverse: record.id}))
                elif act[0] == 1:
                    comodel.browse(act[1]).write(act[2])
                elif act[0] == 2:
                    comodel.browse(act[1]).unlink()
                elif act[0] == 3:
                    drop(comodel.browse(act[1]))
                elif act[0] == 4:
                    record = records[-1]
                    line = comodel.browse(act[1])
                    line_sudo = line.sudo().with_context(prefetch_fields=False)
                    if int(line_sudo[inverse]) != record.id:
                        line.write({inverse: record.id})
                elif act[0] == 5:
                    flush()
                    domain = self.domain(records) if callable(self.domain) else self.domain
                    domain = domain + [(inverse, 'in', records.ids)]
                    drop(comodel.search(domain))
                elif act[0] == 6:
                    flush()
                    record = records[-1]
                    comodel.browse(act[2]).write({inverse: record.id})
                    domain = self.domain(records) if callable(self.domain) else self.domain
                    domain = domain + [(inverse, 'in', records.ids), ('id', 'not in', act[2] or [0])]
                    drop(comodel.search(domain))

            flush()

**Comment by pedrobaeza** [comment] 2020-08-18 07:14
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Closed** 2020-08-18 07:50 UTC
Labels: Need information
