### ISSUE TITLE
Bad visulitation in Ipad

### ISSUE THREAD

**Issue by castoreando** [odoo/odoo#35304] opened 2019-07-30 14:08 UTC
Impacted versions:
v10
Steps to reproduce:
when you are alredy loged, and open the web page dont show more menus
Current behavior:
open the web page dont show more menus
Expected behavior:
Show the menus in the left side 
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2019-07-30 14:11
Sorry, but you have to be more specific.

**Comment by Yenthe666** [comment] 2019-08-11 14:49
@castoreando can you please add more information? Maybe with a video?
If not we'll close this issue off soon as we cannot reproduce this.

**Comment by Yenthe666** [comment] 2019-12-03 07:51
Hi there,

Since there has been no extra information in quite a while I'm closing this issue.
Don't hesitate to respond back with detailed information and then we'll reopen this issue.

Regards,
Yenthe

**Closed by Yenthe666** 2019-12-03 07:51 UTC
Labels: Need information
