### ISSUE TITLE
[13.0] couldn't install resource module

### ISSUE THREAD

**Issue by Yaman-als** [odoo/odoo#45443] opened 2020-02-16 08:07 UTC
Impacted versions:
13.0e
Steps to reproduce:
create a new database and try to install resource module
Current behavior:
can't install 'resource' module, 
odoo.exceptions.ValidationError: ("Attendances can't overlap.", None)
Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2020-02-16 19:16
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Yenthe666** [comment] 2020-03-08 19:30
I'm closing this bug report as there has been no response/feedback to the questions asked by @pedrobaeza

**Closed by Yenthe666** 2020-03-08 19:30 UTC
Labels: 13.0, Need information

**Comment by jj3666csuf** [comment] 2020-05-06 17:33
A little late, but I was having this same issue while building a custom module. It would happen after dropping the database at the command line and running a script to restart the module. I ruled, out my module by commenting it out and just running a __manifest__ with only 'depends': ['base', 'mail','sale_management','purchase','l10n_us'] and still received the error. At first I believed it to be a PostgreSQL caching error, but have almost ruled it out. I then found the following on a web search, https://gitlab.dynapps.be/odoo/odoo/commit/44623864342d771d7698a12cefdee04ecb28ac0f,
and after applying the patch to my Odoo13 local repo, I have not had the issue for 3 Days (usually this error would pop up at least twice a day).

**Comment by pdldeepak** [comment] 2020-07-27 04:43
I am also having the same issues on installing the mrp module in the odoo 13 enterprise.

Steps to reproduce;
Go to Apps > try to install mrp module.

The issue I get is :
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 713, in parse
    self._tag_root(de)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 675, in _tag_root
    f(rec)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 675, in _tag_root
    f(rec)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 578, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4018, in _load_records
    data['record']._load_records_write(data['values'])
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3956, in _load_records_write
    self.write(values)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3529, in write
    real_recs._validate_fields(set(vals) - set(inverse_fields))
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1158, in _validate_fields
    check(self)
  File "/usr/lib/python3/dist-packages/odoo/addons/resource/models/resource.py", line 314, in _check_attendance
    calendar._check_overlap(attendance_ids)
  File "/usr/lib/python3/dist-packages/odoo/addons/resource/models/resource.py", line 303, in _check_overlap
    raise ValidationError(_("Attendances can't overlap."))
odoo.exceptions.ValidationError: ("Attendances can't overlap.", None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1323, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1311, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 395, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 382, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-58>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 463, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 573, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 420, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 312, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 737, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 804, in convert_xml_import
    obj.parse(doc.getroot())
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 722, in parse
    exc_info[2]
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 13, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 713, in parse
    self._tag_root(de)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 675, in _tag_root
    f(rec)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 675, in _tag_root
    f(rec)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 578, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4018, in _load_records
    data['record']._load_records_write(data['values'])
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3956, in _load_records_write
    self.write(values)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3529, in write
    real_recs._validate_fields(set(vals) - set(inverse_fields))
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1158, in _validate_fields
    check(self)
  File "/usr/lib/python3/dist-packages/odoo/addons/resource/models/resource.py", line 314, in _check_attendance
    calendar._check_overlap(attendance_ids)
  File "/usr/lib/python3/dist-packages/odoo/addons/resource/models/resource.py", line 303, in _check_overlap
    raise ValidationError(_("Attendances can't overlap."))
odoo.tools.convert.ParseError: "Attendances can't overlap.
None" while parsing /usr/lib/python3/dist-packages/odoo/addons/resource/data/resource_data.xml:2, near
<odoo>

<data>

    <record id="resource_calendar_std" model="resource.calendar">
        <field name="name">Standard 40 hours/week</field>
        <field name="company_id" ref="base.main_company"/>
    </record>

    <record id="base.main_company" model="res.company">
        <field name="resource_calendar_id" ref="resource_calendar_std"/>
    </record>

    <function model="res.company" name="_init_data_resource_calendar" eval="[]"/>

</data>

<data noupdate="1">

    <record id="resource_calendar_std_35h" model="resource.calendar">
        <field name="name">Standard 35 hours/week</field>
        <field name="company_id" ref="base.main_company"/>
        <field name="hours_per_day">7.0</field>
        <field name="attendance_ids" eval="[                 (0, 0, {'name': 'Monday Morning', 'dayofweek': '0', 'hour_from': 8, 'hour_to': 12, 'day_period': 'morning'}),                 (0, 0, {'name': 'Monday Afternoon', 'dayofweek': '0', 'hour_from': 13, 'hour_to': 16, 'day_period': 'afternoon'}),                 (0, 0, {'name': 'Tuesday Morning', 'dayofweek': '1', 'hour_from': 8, 'hour_to': 12, 'day_period': 'morning'}),                 (0, 0, {'name': 'Tuesday Afternoon', 'dayofweek': '1', 'hour_from': 13, 'hour_to': 16, 'day_period': 'afternoon'}),                 (0, 0, {'name': 'Wednesday Morning', 'dayofweek': '2', 'hour_from': 8, 'hour_to': 12, 'day_period': 'morning'}),                 (0, 0, {'name': 'Wednesday Afternoon', 'dayofweek': '2', 'hour_from': 13, 'hour_to': 16, 'day_period': 'afternoon'}),                 (0, 0, {'name': 'Thursday Morning', 'dayofweek': '3', 'hour_from': 8, 'hour_to': 12, 'day_period': 'morning'}),                 (0, 0, {'name': 'Thursday Afternoon', 'dayofweek': '3', 'hour_from': 13, 'hour_to': 16, 'day_period': 'afternoon'}),                 (0, 0, {'name': 'Friday Morning', 'dayofweek': '4', 'hour_from': 8, 'hour_to': 12, 'day_period': 'morning'}),                 (0, 0, {'name': 'Friday Afternoon', 'dayofweek': '4', 'hour_from': 13, 'hour_to': 16, 'day_period': 'afternoon'})             ]"/>
    </record>

    <record id="resource_calendar_std_38h" model="resource.calendar">
        <field name="name">Standard 38 hours/week</field>
        <field name="company_id" ref="base.main_company"/>
        <field name="hours_per_day">7.6</field>
        <field name="attendance_ids" eval="[                 (0, 0, {'name': 'Monday Morning', 'dayofweek': '0', 'hour_from': 8, 'hour_to': 12, 'day_period': 'morning'}),                 (0, 0, {'name': 'Monday Afternoon', 'dayofweek': '0', 'hour_from': 13, 'hour_to': 16.6, 'day_period': 'afternoon'}),                 (0, 0, {'name': 'Tuesday Morning', 'dayofweek': '1', 'hour_from': 8, 'hour_to': 12, 'day_period': 'morning'}),                 (0, 0, {'name': 'Tuesday Afternoon', 'dayofweek': '1', 'hour_from': 13, 'hour_to': 16.6, 'day_period': 'afternoon'}),                 (0, 0, {'name': 'Wednesday Morning', 'dayofweek': '2', 'hour_from': 8, 'hour_to': 12, 'day_period': 'morning'}),                 (0, 0, {'name': 'Wednesday Afternoon', 'dayofweek': '2', 'hour_from': 13, 'hour_to': 16.6, 'day_period': 'afternoon'}),                 (0, 0, {'name': 'Thursday Morning', 'dayofweek': '3', 'hour_from': 8, 'hour_to': 12, 'day_period': 'morning'}),                 (0, 0, {'name': 'Thursday Afternoon', 'dayofweek': '3', 'hour_from': 13, 'hour_to': 16.6, 'day_period': 'afternoon'}),                 (0, 0, {'name': 'Friday Morning', 'dayofweek': '4', 'hour_from': 8, 'hour_to': 12, 'day_period': 'morning'}),                 (0, 0, {'name': 'Friday Afternoon', 'dayofweek': '4', 'hour_from': 13, 'hour_to': 16.6, 'day_period': 'afternoon'})             ]"/>
    </record>

</data>

</odoo>

**Comment by youring** [comment] 2020-08-26 07:12
Fixed in master but not backported to 13.0 
https://github.com/odoo/odoo/commit/44623864342d771d7698a12cefdee04ecb28ac0f
