### ISSUE TITLE
[11.0] Procurement: run scheduler does not work correctly in multi-company environment

### ISSUE THREAD

**Issue by salmemik** [odoo/odoo#23764] opened 2018-03-20 09:47 UTC
Impacted versions: 11

Steps to reproduce: 
- Create Company A and its child company B
- Create vendor, product and product.supplierinfo all assigned to company B
- Create reordering rule for product (company B's WH & location)
- Settings => Technical => Automation => Scheduled Actions => Procurement: run scheduler => Run Manually (or schedule to run automatically)

Current behavior: 
- Request for Quotation for company B's vendor has not been created
- Odoo creates planned activity for product: "There is no vendor associated to the product <product name>. Please define a vendor for this product."
- NOTE: Request for Quatation is created if company B is selected for admin user (=Cron User on Procurement: run scheduler)

Expected behavior:
- Request for Quatation is made for company B (no matter what company is selected for admin user)
- Note by person on created Request for Quatation should be Product Responsible (not admin / Cron User)

**Comment by pedrobaeza** [comment] 2018-03-21 10:03
Hi @salmemik,

That's not something Odoo performs by default without a specific enterprise module that is called `inter_company_rules`. You have to pay enterprise, install it, and configure for that creation (that it would be not exactly the flow you mention, but similar).

Another options is to look for a community module that performs the same or develop/pay for development on your own.

**Comment by sle-odoo** [comment] 2018-03-21 10:24
@pedrobaeza not sure i agree with your comment, here the problem is that if you have multiple reordering rules in multiple companies, the scheduler is presumably failing to solve them. the `inter_company_rules` method should not matter here, actually we always create the chain of move when confirming a move, the scheduler do not do that anymore

**Comment by pedrobaeza** [comment] 2018-03-21 10:57
OK, thanks for reconfirming. I understood that he wants to create an inter-company operation, but re-reading it indeed it's not exactly the case. I reopen the issue then and let you check.

**Comment by sle-odoo** [comment] 2018-03-21 14:53
fixed by 3c468b0185077626ef2d2f220294f24923dd504f
thanks for the report

**Closed by sle-odoo** 2018-03-21 14:53 UTC
Labels: 11.0, Logistics

**Comment by pedrobaeza** [comment] 2018-03-21 14:55
Great, thanks for the quick reaction and for amending my mistake qualifying the issue.

**Comment by Yenthe666** [comment] 2018-03-21 14:56
Good job guys!

**Comment by salmemik** [comment] 2018-03-21 19:49
Thank you very much! I tested this and now RfQ was created for the right company.
