### ISSUE TITLE
[hr] leave tags in not correctly shown on employee kanban view

### ISSUE THREAD

**Issue by njeudy** [odoo/odoo#10405] opened 2016-01-11 16:23 UTC
Odoo version: 80, 9.0e, 9.0c
Tested on latest runbot.

If you approve leave request for an employee, you can see leave tag on kanban view. But if the current day is the last day of employee leave, this tag is not shown !

To reproduce: 
- create and approve leave for an employee .. end live date should be your current date.
- go to kanban employe view .. no tag.

See this video: https://www.youtube.com/watch?v=7_EqmGgi1Cs

**Comment by jonerikceberio** [comment] 2017-05-23 11:03
Confirmed here for 8.0 and 9.0. The problem is that the employee is only considered absent if he has a leave that starts before now and ends after the 23:59:59 of today. That is, he is absent now if he is not coming today anymore, which is a strange rule.
Even worse, it is not coherent in v10: employee is absent if he has a leave that starts before now and ends after now. IMHO that is what the user expects.

8.0:
https://github.com/odoo/odoo/blob/8.0/addons/hr_holidays/hr_holidays.py#L556
9.0:
https://github.com/odoo/odoo/blob/9.0/addons/hr_holidays/hr_holidays.py#L637
10.0:
https://github.com/odoo/odoo/blob/10.0/addons/hr_holidays/models/hr.py#L148

**Comment by pedrobaeza** [comment] 2018-04-17 23:36
Closing as there hasn't been an answer.

Feel free to open a new issue if this is still happening, but please include all the detailed steps to reproduce the problem, and better if it can be reproducible in a demo environment like runbot (http://runbot.odoo.com).

**Closed by pedrobaeza** 2018-04-17 23:36 UTC
Labels: 9.0, Need information
