### ISSUE TITLE
[9.0] QWebException: 'mock_attach' object has no attribute 'id'

### ISSUE THREAD

**Issue by eandersons** [odoo/odoo#8762] opened 2015-09-29 08:01 UTC
I get this error on clean Odoo 9.0 installation when trying to install Project Management module.

```
INFO odoo_9 werkzeug: 127.0.0.1 - - [29/Sep/2015 10:51:06] "GET /web/? HTTP/1.1" 500 -
ERROR odoo_9 werkzeug: Error on request:
Traceback (most recent call last):
  File "c:\Odoo\venv\lib\site-packages\werkzeug\serving.py", line 180, in run_wsgi
    execute(self.server.app)
  File "c:\Odoo\venv\lib\site-packages\werkzeug\serving.py", line 168, in execute
    application_iter = app(environ, start_response)
  File "c:\Odoo\odoo\openerp\service\server.py", line 245, in app
    return self.app(e, s)
  File "c:\Odoo\odoo\openerp\service\wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "c:\Odoo\odoo\openerp\service\wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "c:\Odoo\odoo\openerp\http.py", line 1356, in __call__
    return self.dispatch(environ, start_response)
  File "c:\Odoo\odoo\openerp\http.py", line 1330, in __call__
    return self.app(environ, start_wrapped)
  File "c:\Odoo\venv\lib\site-packages\werkzeug\wsgi.py", line 591, in __call__
    return self.app(environ, start_response)
  File "c:\Odoo\odoo\openerp\http.py", line 1520, in dispatch
    result = ir_http._dispatch()
  File "C:\Odoo\odoo\addons\web_editor\models\ir_http.py", line 16, in _dispatch
    return super(ir_http, self)._dispatch()
  File "c:\Odoo\odoo\openerp\addons\base\ir\ir_http.py", line 176, in _dispatch
    return self._handle_exception(e)
  File "c:\Odoo\odoo\openerp\addons\base\ir\ir_http.py", line 147, in _handle_exception
    return request._handle_exception(exception)
  File "c:\Odoo\odoo\openerp\http.py", line 684, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "c:\Odoo\odoo\openerp\addons\base\ir\ir_http.py", line 172, in _dispatch
    result = request.dispatch()
  File "c:\Odoo\odoo\openerp\http.py", line 709, in dispatch
    r = self._call_function(**self.params)
  File "c:\Odoo\odoo\openerp\http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "c:\Odoo\odoo\openerp\service\model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "c:\Odoo\odoo\openerp\http.py", line 312, in checked_call
    result.flatten()
  File "c:\Odoo\odoo\openerp\http.py", line 1307, in flatten
    self.response.append(self.render())
  File "c:\Odoo\odoo\openerp\http.py", line 1300, in render
    context=request.context)
  File "c:\Odoo\odoo\openerp\api.py", line 223, in wrapper
    return old_api(self, *args, **kwargs)
  File "C:\Odoo\odoo\addons\web_editor\models\ir_ui_view.py", line 29, in render
    return super(view, self).render(cr, uid, id_or_xml_id, values=values, engine=engine, context=context)
  File "c:\Odoo\odoo\openerp\api.py", line 223, in wrapper
    return old_api(self, *args, **kwargs)
  File "c:\Odoo\odoo\openerp\addons\base\ir\ir_ui_view.py", line 1072, in render
    return self.pool[engine].render(cr, uid, id_or_xml_id, qcontext, loader=loader, context=context)
  File "c:\Odoo\odoo\openerp\api.py", line 223, in wrapper
    return old_api(self, *args, **kwargs)
  File "c:\Odoo\odoo\openerp\addons\base\ir\ir_qweb.py", line 255, in render
    return self.render_node(element, qwebcontext, generated_attributes=qwebcontext.pop('generated_attributes', ''))
  File "c:\Odoo\odoo\openerp\addons\base\ir\ir_qweb.py", line 298, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "c:\Odoo\odoo\openerp\addons\base\ir\ir_qweb.py", line 321, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "c:\Odoo\odoo\openerp\addons\base\ir\ir_qweb.py", line 296, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "c:\Odoo\odoo\openerp\addons\base\ir\ir_qweb.py", line 449, in render_tag_call
    d[0] = self.render_element(element, template_attributes, generated_attributes, d)
  File "c:\Odoo\odoo\openerp\addons\base\ir\ir_qweb.py", line 321, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "c:\Odoo\odoo\openerp\addons\base\ir\ir_qweb.py", line 296, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "c:\Odoo\odoo\openerp\addons\base\ir\ir_qweb.py", line 490, in render_tag_set
    qwebcontext[template_attributes["set"]] = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "c:\Odoo\odoo\openerp\addons\base\ir\ir_qweb.py", line 326, in render_element
    raise_qweb_exception(message="Could not render element %r" % element.tag, node=element, template=template)
  File "c:\Odoo\odoo\openerp\addons\base\ir\ir_qweb.py", line 321, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "c:\Odoo\odoo\openerp\addons\base\ir\ir_qweb.py", line 296, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "c:\Odoo\odoo\openerp\addons\base\ir\ir_qweb.py", line 482, in render_tag_call_assets
    return bundle.to_html(css=css, js=js, debug=bool(qwebcontext.get('debug')), async=async)
  File "c:\Odoo\odoo\openerp\addons\base\ir\ir_qweb.py", line 1188, in to_html
    response.append('<script %s type="text/javascript" src="%s"></script>' % (async and 'async="async"' or '', url_for(self.js().url)))
  File "c:\Odoo\odoo\openerp\addons\base\ir\ir_qweb.py", line 1268, in js
    return self.save_attachment('js', content)
  File "c:\Odoo\odoo\openerp\addons\base\ir\ir_qweb.py", line 1258, in save_attachment
    attachment_id = attachments[0].id
QWebException: 'mock_attach' object has no attribute 'id'
```

I think this error is related to changes made in the commit 6327cda.

**Comment by mart-e** [comment] 2015-09-29 10:05
Hello,

Do you still have the issue with latest 9.0? Can you give more info on which steps you follow? I can not reproduce.

**Comment by eandersons** [comment] 2015-09-29 13:17
Situation got a little bit strange here. This problem still exists when I try to install Project Management module using existing "installation" and newly created database, but there was no problems when I used newly checked out source code in different directory. Though the problem occured also in the new "installation" when I deleted database, created new and tried to install Project Management module.

**Comment by mart-e** [comment] 2015-09-29 13:19
I think it is related to the asset generations. So it could happen when you get the assets of another database in cache maybe.

**Comment by apr-odoo** [comment] 2015-09-29 15:00
The issue come from a bad reload of module.  e.g. install crm then sale, you have to manually reload the page.

**Comment by apr-odoo** [comment] 2015-09-29 15:01
@antonylesuisse says install button should walays return a reload action

**Comment by eandersons** [comment] 2015-09-30 10:26
It seems that this problem has nothing to do with modules installation, because it occurs right after I have created new database, logged in and manually reloaded apps page. After that Odoo is unusable - same error as mentioned in the [first post](#issue-108814424).
Basically, after the commit 6327cda my Odoo "installation" is unusable.

**Comment by antonylesuisse** [comment] 2015-09-30 11:34
@sle-odoo your shit...

**Comment by sle-odoo** [comment] 2015-09-30 11:56
@eandersons 
I can't reproduce the issue at my end. What's the command you use to start Odoo? When you say you create a new database, are you creating it from the command line or from the database manager? Are you using a dbfilter?

Please be sure to pull the latest code, then maybe you can try to clean the assets of your old database (after a backup of this database if you care) then run the command ```DELETE FROM ir_attachment WHERE name ilike '%asset%';``` and refresh the webclient.

Thanks in advance

**Comment by rco-odoo** [comment] 2015-09-30 12:53
@eandersons I cannot reproduce the issue either.

**Comment by wtaferner** [comment] 2015-09-30 13:05
@sle-odoo @rco-odoo 
I do also have this issue...I tried everything to have a clean start (remove db, filestore, clear cache, etc.), but it pops up again. Used the very last github sources for both (enterprise and community).

**Comment by sle-odoo** [comment] 2015-09-30 13:13
@wtaferner Can you be more specific? I just created new databases, installed modules, dropped the assets, refresh, everything looks ok at my end... What's your installation steps?

**Comment by wtaferner** [comment] 2015-09-30 13:18
Hmm, maybe it is OS specific as I am running it on Windows 7 and I guess you guys did try to reproduce on Linux...I was not able to find a clear reproduction path yet, otherwise I would have already posted...I will investigate a little more and come back if I know why it fails exactly...maybe you can test for the OS specific reproduction with your colleagues.

**Comment by eandersons** [comment] 2015-09-30 13:19
I am running Odoo on Windows 7 too.

**Comment by eandersons** [comment] 2015-09-30 13:21
First time I got this error was after I pulled latest code and tried to upgrade Project Management module.

**Comment by wtaferner** [comment] 2015-09-30 13:46
Ok, it seems to be a clearly reload related issue...

- I installed just base and after that I was able to use the UI to install accounting too
- as soon as I try to reload the whole application the very first request of web does end up with HTTP 500
- It is then possible to resolve the issue by deleting the assets in database as suggested and then it works again, but as soon as I reload the whole application it fails again

Hope this helps to reproduce or get an idea where you might have missed something for the implementation.

**Comment by sle-odoo** [comment] 2015-09-30 13:50
so i tested with the latest windows nightly build: created databases, upgraded modules, dropped assets to regenerate them, refreshed and all went well.

**Comment by eandersons** [comment] 2015-09-30 14:19
I have the same problem as @wtaferner mentioned [here](#issuecomment-144403817).
After every HTTP 500 error I have to clear assets in the database to get Odoo working, but it only helps till next full page reload.

**Comment by wtaferner** [comment] 2015-09-30 14:30
@sle-odoo 
Damn, but did you test without debug mode? I know it is a stupid question, but I don't get it why the else condition should work at all as the return value for attachments is something like 
```python
[mock_attach(url=u'/web/content/585-8ff43f8/web.assets_backend.js', last_update='2015-09-30 14:17:37')]
```

**Comment by wtaferner** [comment] 2015-09-30 14:40
@sle-odoo 
Ok, I will do a PR for this as I think I got the solution...

```python
    def save_attachment(self, type, content, inc=None):
        ira = self.registry['ir.attachment']
        self.clean_attachments(type)
        attachments = self.get_attachments(type, inc)
        values = {}

        with self.registry.cursor() as cr2:
            if not attachments:
                values["name"] = "/web/content/%s" % type
                values["datas_fname"] = '%s%s.%s' % (self.xmlid, ('' if inc is None else '.%s' % inc), type)
                values["res_model"] = 'ir.ui.view'
                values["public"] = True
                values["type"] = 'binary'
                attachment_id = ira.create(cr2, openerp.SUPERUSER_ID, values, context=self.context)
                url = '/web/content/%s-%s/%s' % (attachment_id, self.version, values["datas_fname"])
                values["name"] = url
                values["url"] = url

                values["datas"] = content.encode('utf8').encode('base64')
                ira.write(cr2, openerp.SUPERUSER_ID, attachment_id, values, context=self.context)
                return self._mock_attachments(ira.browse(cr2, openerp.SUPERUSER_ID, attachment_id, context=self.context))[0]

        return attachments[0]
```

**Comment by sle-odoo** [comment] 2015-09-30 15:08
@wtaferner finally got it.. as you said, source install on windows. I don't know why it doesn't happen with the nightly package... And clearly, the else condition cannot work as it tries to access the id attribute on a mocked attachment and we only mock the url and last_update parts.

A patch is coming by adding the id attribute to the mocked ir attachment. I don't think your patch is correct as it bypass the case where we update an existing attachment.

**Comment by wtaferner** [comment] 2015-09-30 15:16
Great, LGTM and jep, bypassing was only a desperate move to show you what needs to be fixed...probably the namedtuple was kinda new for me and was afraid to touch it otherwise I would have come up with the same PR ;-)

**Comment by sle-odoo** [comment] 2015-09-30 15:56
@eandersons could you pull and confirm it is fixed for you?
@wtaferner coul you try ton install the [nightly package from yesterday](http://nightly.odoo.com/9.0/nightly/exe/odoo_9.0rc1.20150929.exe) and confirm me that is working on your side, with the same code that's breaking on a source install?

Thanks

**Comment by wtaferner** [comment] 2015-09-30 15:58
I can confirm that your fix is working on my source install. I guess you mixed up who was testing what ;-)

**Comment by sle-odoo** [comment] 2015-09-30 16:05
it's working on my source install too, else i won't have committed in 9.0 :) but again, i cannot reproduce the initial issue with the package i linked, and if you inspect the code of this package you'll see that it does not include my patch.

**Comment by sle-odoo** [comment] 2015-09-30 16:08
plus the fact that three of us cannot reproduce the issue on linux indicates that there's maybe something fishy with get_attachments on windows, and the the fact that i don't have the issue with the package maybe indicates that it is related to some libraries version...

**Comment by wtaferner** [comment] 2015-09-30 16:35
Ok, I did test it now from the nightly package and it was the exact same issue and well, Simon I don't think it is a Windows issue anymore...I moreover want to believe that you've tested it with an NGINX running (with workers whereas cache did not request it again as nothing is changed) or with debug mode (you did not answer this question)...based on your fix and my own research for me it is crystal clear that it does not make any difference...I actually now don't see anything which is OS specific except the client-side or the server environment...so relax and push it :-)

**Comment by sle-odoo** [comment] 2015-09-30 16:44
Hey, it is pushed, see rev c3c2281a4d6a148cebf4eed2d6ab894eedbf472c

I tested it without nginx running and tried with and without debug. And two others colleagues did try to reproduce this issue before me, without success. And yes, there is os specific code in the asset generation. Read it you'll see that ir_qweb plays a little with the files to get their modified date and so on. And i'm pretty sure someone here would have shouted on me if i broke the module installation 6 days ago :)

Anyway, i have a windows computer with the two behaviors now so i can't check it myself :)

**Comment by eandersons** [comment] 2015-09-30 17:01
I just checked this specific commit (6327cda) on OS X and Ubuntu, there is no problems when launching Odoo in similar manner as on Windows 7.
Tomorrow I will check fix on Windows 7.

**Comment by wtaferner** [comment] 2015-09-30 17:04
Hehe, yay, don't give too much about shouters b/c these will mostly deny that they did something wrong or break the build if it happens the other way round for whatever reason or argue even harder why it was inevitable ;-) so, nobody is perfect although everybody wants to be and some pretend to be and as you said now you can still blame this external developer from Vienna you have trusted ^^

**Comment by eandersons** [comment] 2015-10-01 07:01
@sle-odoo I can confirm that the problem is fixed.
Also I can confirm that this problem does not exist when using nightly build you mentioned in this [post](#issuecomment-144457604).

**Comment by antonylesuisse** [comment] 2015-10-01 23:13
Thanks.

**Closed by antonylesuisse** 2015-10-01 23:13 UTC
Labels: confirmed
