### ISSUE TITLE
Odoo Client Error

### ISSUE THREAD

**Issue by NasanbatG** [odoo/odoo#66968] opened 2021-02-27 03:41 UTC
Hi guys,
how can i fix this error

Error:

Traceback:
TypeError: field_utils.format[(formatType || this.formatType)] is not a function
    at Class._formatValue (http://192.168.23.165:8069/web/content/202-3a8efd0/web.assets_backend.js:900:1237)
    at Class._render (http://192.168.23.165:8069/web/content/202-3a8efd0/web.assets_backend.js:894:167)
    at Class._render (http://192.168.23.165:8069/web/content/202-3a8efd0/web.assets_backend.js:1160:1163)
    at Class.prototype.<computed> [as _render] (http://192.168.23.165:8069/web/content/200-5dd599e/web.assets_common.js:4619:488)
    at http://192.168.23.165:8069/web/content/202-3a8efd0/web.assets_backend.js:898:1417

**Comment by pedrobaeza** [comment] 2021-02-27 11:29
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Closed** 2023-04-07 14:23 UTC
Labels: Need information
