### ISSUE TITLE
Uncaught TypeError: Cannot read property 'type' of null

### ISSUE THREAD

**Issue by arkankhan-ak** [odoo/odoo#57020] opened 2020-09-03 10:56 UTC
![image](https://user-images.githubusercontent.com/57611955/92106369-ebffa880-ee01-11ea-8f24-1d103755b7ef.png)

active_view is getting set as null, it doesn't affect anything but prompt everytime when I come back to leave details menu from browsers back button

**Comment by pedrobaeza** [comment] 2020-09-03 11:00
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by arkankhan-ak** [comment] 2020-09-03 11:11
not able to reproduce on runbot. Thank you.

**Comment by pedrobaeza** [comment] 2020-09-03 11:12
Then please check the cause stated before for you local deployment to have that problem. Closing.

**Closed by pedrobaeza** 2020-09-03 11:12 UTC
Labels: Need information
