### ISSUE TITLE
[11.0e/11.0c] CSV/XLS Import Issue - Changing company_type in CSV Import Has No Effect

### ISSUE THREAD

**Issue by lukebranch** [odoo/odoo#20623] opened 2017-11-01 08:31 UTC
<h1>Impacted Versions:</h1>
  - 11.0 Enterprise/Community
<h1>Steps to Reproduce:</h1>

1. Export a Contact with only the company_type field
2. Change the value of company_type field in your CSV from above
3. Import into Odoo

<h1>Current Behaviour:</h1>
There is no change, regardless of whether you use either of the following values:
Company
Individual

There appears to be a bug with this particular field, however
<h1>Expected Behaviour:</h1>
Should have the ability to update this value via CSV or XLS import.

**Comment by lukebranch** [comment] 2017-11-01 08:32
@Yenthe666 ,

Would you mind checking this out when you get the chance.

**Comment by Yenthe666** [comment] 2017-11-01 11:17
Will test it tommorow when I have internet access! Thanks for the report.

**Comment by lukebranch** [comment] 2017-11-01 12:50
Thanks

**Comment by Yenthe666** [comment] 2017-11-02 08:57
Hah, with me just trying out of the box I already have loads of problems.

1. Export one record to a CSV
2. Change the column for "company_type" from "Company" to "Partner"
3. Click on import and upload your CSV:
![image](https://user-images.githubusercontent.com/6352350/32317050-d06c1a66-bfb2-11e7-88a9-edb3aecd9d90.png)

When I then close the dialog and check off "The first row contains the label of the column":
![image](https://user-images.githubusercontent.com/6352350/32317086-f2e49b04-bfb2-11e7-8849-2aa4852f9c36.png)

When I click on "Options" and then change encoding:
![image](https://user-images.githubusercontent.com/6352350/32317167-28cbc9c2-bfb3-11e7-868f-f0967ffc8db6.png)

I then don't even have the ability to click on "Reload file" - which all worked fine out of the box.
So it looks like quite a lot is broken there. 😉 
@xmo-odoo can you look at the encoding issues?
@ged-odoo can you handle the JS error?
@mart-e can you answer the initial bug report? If I am not mistaking this is because the field `company_type` is computed and not a stored field - thus it won't be changed with the import.
I know that if you do custom development for this that you need to make the field `store=True` but shouldn't it work for imports though?

Regards,
Yenthe

**Comment by xmo-odoo** [comment] 2017-11-02 09:04
@lukebranch company_type is a computed field based on the `is_company` flag. It could be made updatable but that's a feature request rather than an issue, at this point everything works as it's supposed to.

@Yenthe666

> can you look at the encoding issues?

I don't see any encoding issue.

> can you handle the JS error?

Can you open a new issue? Because I'm closing this one.

> I know that if you do custom development for this that you need to make the field store=True but shouldn't it work for imports though?

No, computed fields are readonly by default. They can be made writable by adding an inverse function which goes and updates the source, though that's not necessarily possible for all compute fields (not all functions are invertible). It is possible for this one though.

**Comment by Yenthe666** [comment] 2017-11-02 09:08
@xmo-odoo thanks for the feedback. The import was as I expected.
With encoding I was talking about the `itertools` about too many values to unpack - which is a bug.
I guess I'll create a new bug report for point 2 & 3 too.

**Comment by xmo-odoo** [comment] 2017-11-02 09:23
@Yenthe666 thinking about it more, the following issues are probably because the python code blows up first and leaves the widget in a nonsensical state, I'll look into it.

**Comment by Yenthe666** [comment] 2017-11-02 09:25
Thanks - let me reopen this for now.

**Comment by lukebranch** [comment] 2017-11-02 10:07
@xmo-odoo @Yenthe666 ,

Thanks for looking into this. Indeed, it looks like the latest runbot builds are broken.

Regarding this:

> company_type is a computed field based on the is_company flag. It could be made updatable but that's a feature request rather than an issue, at this point everything works as it's supposed to.

Just my two cents, but I believe it might be a little confusing for the user due to this:

<img src="https://user-images.githubusercontent.com/2337666/32320325-55c407e2-bff8-11e7-83a8-a952b96ea6b7.png"/>

I think if it's not import-compatible, perhaps it should only appear in the 'Export All Data' rather than the 'Import-Compatible-Export' option, as it may be a little confusing otherwise (ie. in this case this field's value can be exported, but the value can not be adjusted and used to import again).

**Comment by xmo-odoo** [comment] 2017-11-02 10:58
@Yenthe666 fixed, it was actually an ill-defined `state` attribute on a field in a module with no relation with the import, which would blow up when the import process tries to infer available fields.

@lukebranch that is true and now that I think about it it should be filtered out, it's odd that it is not.

**Comment by xmo-odoo** [comment] 2017-11-02 11:29
@lukebranch and it turns out to be a misconfiguration of the "Company Type" field dating back to the old -> new API conversion of base/res.partner: it was formerly a stored field kept in sync with the flag through overriding create & write, it was then converted to a computed field (good) but for some reason somebody realised it had become readonly and  just marked it as `readonly=False` rather than give it a proper inverse function…

**Closed** 2017-11-07 10:46 UTC
Labels: 11.0

**Comment by Yenthe666** [comment] 2017-11-07 10:55
Yep - I can confirm it is all working fine now. Thanks.

**Comment by lukebranch** [comment] 2017-11-07 11:44
thanks guys!

**Comment by elicoidal** [comment] 2017-11-29 00:19
@Yenthe666 has it been backported to v10.0?
