### ISSUE TITLE
[12] Account overview links don't filter journals

### ISSUE THREAD

**Issue by iblys** [odoo/odoo#30973] opened 2019-02-09 05:42 UTC
Impacted versions: 

12.0+e-20190207

Steps to reproduce:

Goto accounts overview and click on links, ie: # of invoices to validate. On 11 it filters those invoices to respective journal, but on 12 it just list everything from all journals.

As in attached screen grab, if i click on Customer Invoices link it shows invoices of the other maintenance journal as well.

The smaller links, ie # of invoices to validate does filter the state, but not journal. So if you have more than 1 it lists them all.

Video/Screenshot link (optional):

![acc_ovrvw](https://user-images.githubusercontent.com/15857306/52516999-b6aacd00-2c55-11e9-9639-26a99bd37b6e.jpg)

**Comment by pedrobaeza** [comment] 2019-02-09 13:38
@iblys looking at your screenshot, I see journal "Vendor Bills - Foreign" with "0 Bills to Validate", so that's a sign that the overview is not sharing invoices between journals.

**Comment by iblys** [comment] 2019-02-09 14:45
@pedrobaeza , it displays correct. But when I click on 1 bills to pay on vendor foreign the list view contains 6 bills. Including ones in local journal.

**Comment by pedrobaeza** [comment] 2019-02-10 23:57
OK, I get you, then the problem might be on the action window that is called when clicking. @qdp-odoo can you please check this?

**Comment by csnauwaert** [comment] 2019-08-05 14:18
Hello, 
I could not reproduce the issue. I believe this should have been fixed by this commit https://github.com/odoo/odoo/commit/910e5de42d8dc880e5d9261f516cf8ddb429ff24

Feel free to reopen if you still have the problem.

**Closed by csnauwaert** 2019-08-05 14:18 UTC
Labels: 12.0, Accounting
