### ISSUE TITLE
[12.0/13.0] Daylight savings messing up appointment hours

### ISSUE THREAD

**Issue by reinaldoramosarxi** [odoo/odoo#45661] opened 2020-02-18 16:46 UTC
Hello,

We've noticed that in the calendar app, whenever selecting the full 24h to input an appointment, the day will "start" at midnight, which is a normal behavior.

However, if you do the same thing on a day that's after DST (which is March 29th), the day will start at 1 am. This is affecting some other areas where we use calendar appointments, namely days off. It happens on both 12.0 and 13.0.

I'm sending a gif demonstration:
![ezgif com-resize](https://user-images.githubusercontent.com/42942314/74757590-1e82f300-526e-11ea-9068-1c6ded4e6288.gif)

Also, there's a bug when checking and unchecking the "All Day" checkbox:
![ezgif com-resize (1)](https://user-images.githubusercontent.com/42942314/74757672-3f4b4880-526e-11ea-99b3-d72d75e34bd1.gif)

Thank you.

**Comment by MahmoudRizk** [comment] 2020-02-26 13:31
I have been testing the bug related to the day start time, and for me the day started at 2 am. I checked the record in the database and it was normally saved at midnight, have tried changing my PC timezone from (GMT +2) to (GMT +3) and tried to create new record, it started at 3 am. I think this behavior happens because you are now at (GMT +1) and records saved in database are at GMT time.

**Comment by MahmoudRizk** [comment] 2020-02-26 15:05
Another bug is found:
_steps to reproduce:_
1.  Switch to list view.
2. Create new event.
3. Check the all day check box first before choosing starting date.
4. Choose starting date.

_result_
Ending date field is populated automatically with previous date, which is not correct.

_expected_
It is expected Ending date field to be the same as Starting date field.

**Comment by pedrobaeza** [comment] 2020-03-12 18:39
@mart-e I remember some work about DST. Is this issue something related?

**Comment by mart-e** [comment] 2020-03-30 10:52
@pedrobaeza I am afraid this is an old bug, it was already reported at #9268.
@kebeclibre made a fix at #27985 but not sure it's fixing this one.

**Comment by pedrobaeza** [comment] 2020-03-30 10:54
OK, then let's close it as duplicated.

**Closed by pedrobaeza** 2020-03-30 10:54 UTC
Labels: 12.0, 13.0, HR
