### ISSUE TITLE
[12.0] Wrong invoice type on invoices created from repairs

### ISSUE THREAD

**Issue by reinaldoramosarxi** [odoo/odoo#32978] opened 2019-04-26 10:37 UTC
Impacted versions: 
- 12.0 (that we've seen)

Steps to reproduce: 
- Create an invoiceable repair;
- View it by pressing the invoice button;
- After the invoice is confirmed, refresh the page.

Current behavior:
- The customer invoice will show supplier info (will look like a supplier invoice)

Expected behavior:
- It should keep all the fields that it originally had (customer id instead of supplier id)

Looks like the "outgoing" type should be passed in context, but apparently it defaults to "incoming".
Tested on runbot, same thing happens.

**Comment by sswapnesh** [comment] 2019-04-28 17:52
Hello @reinaldoramosarxi 

> Looks like the "outgoing" type should be passed in context, but apparently it defaults to "incoming".
> 

It is passed in context and Correct Invoice (Customer Invoice) is created from Repair.

but this is because of loss of context in action.

Duplicate of https://github.com/odoo/odoo/issues/28271
Cc: @pedrobaeza

**Comment by pedrobaeza** [comment] 2019-04-28 23:45
Yes, closing this.

**Closed by pedrobaeza** 2019-04-28 23:45 UTC
Labels: 12.0, Accounting
