### ISSUE TITLE
Yaml file appears to depend on missing data

### ISSUE THREAD

**Issue by aspcsharp9** [odoo/odoo#18355] opened 2017-07-20 12:00 UTC
Impacted versions: 9

Steps to reproduce: in console get error:   

File "/home/pc/git/odoo/openerp/tools/yaml_import.py", line 173, in get_id
    tests that belong to a module's test suite and depend on each other.""" % (xml_id, self.filename))
ValueError: 'demo_invoice_invest_sale' not found when processing /home/pc/git/odoo/addons/account/demo/account_invoice_demo.yml.
    This Yaml file appears to depend on missing data. This often happens for
    tests that belong to a module's test suite and depend on each other.

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment] 2017-07-20 12:08
@oco-odoo and @qdp-odoo the last commit on this file was by you two. Perhaps one of you could give some input?

**Comment by pedrobaeza** [comment] 2018-06-02 14:49
Hi, I'm not able to reproduce this problem in latest code, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-06-02 14:49 UTC
Labels: 9.0, Framework
