### ISSUE TITLE
[13.0] Error in stock.warehouse

### ISSUE THREAD

**Issue by rhe-mastercore** [odoo/odoo#61742] opened 2020-11-14 23:38 UTC
**Impacted versions:**
13.0
**Steps to reproduce:**
i'm migrate OCA module `maintenance_sotck`  but have one error

```
warehouse._create_missing_locations(vals={}) is this the error:
File "/mnt/maintenance_stock/hooks.py", line 16, in post_init_hook
warehouse._create_missing_locations(vals={})
File "/home/odoo/odoo/addons/stock/models/stock_warehouse.py", line 568, in _create_missing_locations
sub_locations = warehouse._get_locations_values(dict(vals, company_id=company_id), warehouse.code)
TypeError: _get_locations_values() takes 2 positional arguments but 3 were given
```
already update my odoo addons.
What I did was heed the function **_create_missing_locations** of the `stock.warehouse` model and change this line

```
sub_locations = warehouse._get_locations_values (
                dict (vals, company_id = company_id), warehouse.code)
```
for this
`sub_locations = warehouse._get_locations_values (vals)`

but this no migration task to module
![Captura de pantalla de 2020-11-14 19-24-12](https://user-images.githubusercontent.com/35534162/99159151-712ff500-26b0-11eb-8cd5-9b5c680459c9.png)

**Comment by pedrobaeza** [comment] 2020-11-16 08:36
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Comment by rhe-mastercore** [comment] 2020-11-16 11:40
hi @pedrobaeza  i'm sorry if i can't explain myself weel, but the error is found in the stock module function of odoo addons, you can see it here [](https://github.com/odoo/odoo/blob/958f5cd325d7295c462b4f30c7bb1eb1f2c166b6/addons/stock/models/stock_warehouse.py#L568)

but i have no other way to reproduce the error if not the one i comment initially, I managed to solve it by changing the code for this 
`sub_locations = warehouse._get_locations_values (vals)`

**Comment by pedrobaeza** [comment] 2020-11-16 12:01
OK, I see the problem now and indeed it's an Odoo core problem.

@amoyaux there are incorrect args in the call to `_get_locations_values`. Can you please check?

**Comment by ryv-odoo** [comment] 2020-11-16 13:14
Hi @rhe-mastercore , the issue isn't ours.
I look quickly in the repo of [Maintenance Stock](https://odoo-community.org/shop/product/maintenance-stock-5570), it seems you fail the override of `_get_locations_values` in [L71](https://github.com/OCA/maintenance/blob/0392b621247d6600a3917a484f1ce11376fa4354/maintenance_stock/models/stock_warehouse.py#L71) : 
`_get_locations_values(vals)`, it should be `_get_locations_values(vals, code=False)`

**Closed by ryv-odoo** 2020-11-16 13:14 UTC
Labels: 13.0, Logistics

**Comment by rhe-mastercore** [comment] 2020-11-16 14:30
hi @ryv-odoo the error is 
`File "/home/odoo/odoo/addons/stock/models/stock_warehouse.py", line 568, in _create_missing_locations
sub_locations = warehouse._get_locations_values(dict(vals, company_id=company_id), warehouse.code)
TypeError: _get_locations_values() takes 2 positional arguments but 3 were given`

you can see it here [L568](https://github.com/odoo/odoo/blob/958f5cd325d7295c462b4f30c7bb1eb1f2c166b6/addons/stock/models/stock_warehouse.py#L568)

not a problem of the oca module.

**Comment by pedrobaeza** [comment] 2020-11-16 14:33
@rhe-mastercore yes, it's your fault. You are overriding the method incorrectly:

https://github.com/OCA/maintenance/blob/0392b621247d6600a3917a484f1ce11376fa4354/maintenance_stock/models/stock_warehouse.py#L71

without having `code` keyword argument.

@ryv-odoo sorry for not checking that.

**Comment by rhe-mastercore** [comment] 2020-11-16 15:29
I can already see it, excuse my mistake.
@pedrobaeza @ryv-odoo **Thanks!**
