### ISSUE TITLE
keyError: 'total' can any one help with that error

### ISSUE THREAD

**Issue by Salem4dev** [odoo/odoo#28780] opened 2018-11-19 09:56 UTC
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/odoo10/odoo10-server/odoo/service/server.py", line 244, in app
    return self.app(e, s)
  File "/odoo10/odoo10-server/odoo/service/wsgi_server.py", line 186, in application
    return application_unproxied(environ, start_response)
  File "/odoo10/v-server/odoo/service/wsgi_server.py", line 172, in application_unproxied
    result = handler(environ, start_response)
  File "/odoo10/odoo10-server/odoo/http.py", line 1326, in __call__
    return self.dispatch(environ, start_response)
  File "/odoo10/odoo10-server/odoo/http.py", line 1300, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 766, in __call__
    return self.app(environ, start_response)
  File "/odoo10/odoo10-server/odoo/http.py", line 1482, in dispatch
    odoo.registry(db).check_signaling()
  File "/odoo10/odoo10-server/odoo/__init__.py", line 52, in registry
    return modules.registry.Registry(database_name)
  File "/odoo10/odoo10-server/odoo/modules/registry.py", line 59, in __new__
    return cls.new(db_name)
  File "/odoo10/odoo10-server/odoo/modules/registry.py", line 83, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo10/odoo10-server/odoo/modules/loading.py", line 379, in load_modules
    registry.setup_models(cr)
  File "/odoo10/odoo10-server/odoo/modules/registry.py", line 297, in setup_models
    model._setup_complete()
  File "/odoo10/odoo10-server/odoo/models.py", line 2890, in _setup_complete
    field.setup_triggers(self)
  File "/odoo10/odoo10-server/odoo/fields.py", line 747, in setup_triggers
    for model, field, path in self.resolve_deps(model):
  File "/odoo10/odoo10-server/odoo/fields.py", line 725, in resolve_deps
    field = model._fields[fname]
KeyError: 'total'

**Comment by pedrobaeza** [comment] 2018-11-19 14:29
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile or it's a misconfiguration problem, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-11-19 14:29 UTC
