### ISSUE TITLE
[l10_in] field used in template (l10n_in_report_invoice_document_inherit) does not exist in the module l10_in

### ISSUE THREAD

**Issue by aman-webkul** [odoo/odoo#36274] opened 2019-08-30 10:30 UTC
Impacted versions: master

Steps to reproduce: 
1.) Go to website
2.) Go to My Account
3.) Go to Invoices & bills
4.) Open any invoice

Current behavior: Error showing at the place of report showing

Expected behavior: Invoice report should be shown.

Video/Screenshot link (optional): https://prnt.sc/ozkakb

**Comment by pedrobaeza** [comment] 2019-08-31 00:12
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Yenthe666** [comment] 2019-08-31 07:57
Plus I really think we should close this bug report as it is against the master version and Odoo doesn't accept those.

**Comment by pedrobaeza** [comment] 2019-08-31 08:00
Yes, let's close it

**Closed by pedrobaeza** 2019-08-31 08:00 UTC
Labels: Need information

**Comment by aman-webkul** [comment] 2019-09-02 06:50
There is only module installed called invoicing.
Here are steps with proper screenshots to reproduce that:
1.) https://prnt.sc/p0kw2s
2.) https://prnt.sc/p0kwfs
3.) https://prnt.sc/p0kwrd
4.) https://prnt.sc/p0kx2e
