### ISSUE TITLE
Computed field does randomly update/no update

### ISSUE THREAD

**Issue by zaoral** [odoo/odoo#33265] opened 2019-05-08 21:13 UTC
### Impacted versions:

11.0 and 12.0

### Steps to reproduce:

> **Important** This error can be reproduced in: https://demo.odoo.com, customer database and local environments.  For some reason we were not able to reproduce it in runbot environment. 

1. Go to Customer Invoices
2. Duplicate an invoice and save
3. Edit the invoices lines 

### Current behavior:

Some times the Total of the invoice is updated (before save) and sometimes don't.

### Expected behavior:

When we update the invoice lines both line subtotal and Invoice Total should be be update without needed to save and this behavior should be consistent

Here is a [video](https://youtu.be/vX7bnxfEm6w) showing the behavior in both demo.odoo.com and runbot instance 

### HINT: 

* We tried to test it locally and found that this is really random, We try to restart the Odoo sever and the result was that sometimes the error was automatically fixed and sometimes not.
* We also try to test it in a the most clean database possible (without enterprise modules) and the random error persist.
* We also review both Odoo server log and Web Browser Console (with Inspect) and there is no error or warning that give us a HINT about what this is happening.
* We debug the code and found out that the Total computed field is updated every time we update the lines, but for some reason this new value is not showed in the view

**Comment by zaoral** [comment] 2019-05-09 20:05
opw-1986570

**Comment by sswapnesh** [comment] 2019-05-09 20:32
Reported Similar situation at (Duplicate of) https://github.com/odoo/odoo/issues/30989 and https://github.com/odoo/odoo/issues/29620 (and it says it was working well till https://github.com/odoo/odoo/issues/29620#issuecomment-448661788)

**Comment by TimLai125** [comment] 2019-05-17 07:00
@sswapnesh I also agree this should be related to ORM/Framework, and I think it is quite hard to find a way to reproduce as it happens randomly.

As in #30989 I am still facing a similar issue which happens in Sales Order.

**Comment by sswapnesh** [comment] 2019-07-01 17:56
Hi @zaoral 
Is there any update on ticket ?

**Comment by pedrobaeza** [comment] 2019-07-01 18:02
We are experimenting the same problem, and indeed we are not able to reproduce it consistently, but on random occasions.

@rco-odoo I think this is due to snapshots improvement, that are certain edge cases that provokes it. Unfortunately, I can't provide you with a test or STR that showcases the problem.

cc @Tardo

**Comment by sotolucas** [comment] 2019-10-11 15:09
Hi everyone. Updates on 1986570 are that the issue is marked as Done (but not resolved for 11.0 or 12.0 due Odoo technical support can't reproduce the error).
Tested on several Python versions (including latest) with or without proxy-pass and clean Odoo 11.0 (CE, CE+EE) and Odoo 12.0 (CE, CE+EE) versions.
We could reproduce the issue on demo.odoo.com until it was 12.0, but now that is 13.0 it seems resolved (tested on Odoo runbot and demo).

**Comment by TimLai125** [comment] 2019-11-13 06:42
@sotolucas, thank you for your updates. I wonder if Odoo can identify the issue and back-port the fix to 11.0 and 12.0
@rco-odoo, May I have your comments on the updates?

**Comment by Yenthe666** [comment] 2020-03-19 12:13
Hi all,

What is the latest status of this issue? @zaoral what was the final response on the OPW?

**Comment by sotolucas** [comment] 2020-03-19 14:52
@Yenthe666 task has been marked as done as Odoo can't reproduce it consistently.
AFAIK this issue is resolved in 13.0.

**Comment by Yenthe666** [comment] 2020-03-19 14:54
Okay thanks! Let's close it then.

**Closed** 2020-03-19 14:54 UTC
Labels: 11.0, 12.0, OE, ORM
