### ISSUE TITLE
Error on checking Invoice for customers in POS Settings

### ISSUE THREAD

**Issue by chriswachira** [odoo/odoo#31370] opened 2019-02-22 14:41 UTC
Current behavior: 

I'm getting the following error when I check **"Invoicing - Print invoices on customer request"** checkbox at POS Configuration page. Kindly assist.

Can someone confirm for me if that checkbox when checked will result in an invoice creation at a POS session? I haven't used that feature yet.

![screenshot_20190221_110021](https://user-images.githubusercontent.com/19710961/53249201-9d2f6980-36c8-11e9-86d1-5d3a835a1ebb.png)
![screenshot_20190221_110255](https://user-images.githubusercontent.com/19710961/53249202-9d2f6980-36c8-11e9-8ac5-7195a240fd6d.png)

**Comment by pedrobaeza** [comment] 2019-02-22 15:25
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by chriswachira** [comment] 2019-02-26 12:25
Hello,

I was able to launch the runbot instance and when checking the Invoicing checkbox at the POS configuration page, there was no error report. I tried to create a POS Journal entry at my personal Odoo installation to match the one at the runbot instance but still I get the same error as in original post.

**Comment by pedrobaeza** [comment] 2019-02-26 12:33
Then the problem is in your local installation. It seems you have removed the journal created by the module. Update the module and it will be recreated again.

Closing as no real issue.

**Closed by pedrobaeza** 2019-02-26 12:33 UTC
Labels: Need information

**Comment by chriswachira** [comment] 2019-02-26 12:42
Could you kindly explain how to do as you recommend? Because I'm sure I haven't uninstalled any module related to Journals

**Comment by pedrobaeza** [comment] 2019-02-26 12:46
Update `point_of_sale` module.

**Comment by chriswachira** [comment] 2019-02-26 14:13
Thanks a lot, Sir. That pretty much solved my issue!
