### ISSUE TITLE
[10.0] Byproduct Producted Qty is not Updated when MO has Routing

### ISSUE THREAD

**Issue by tenxor105** [odoo/odoo#14089] opened 2016-11-01 04:01 UTC
Impacted versions: 10

Steps to reproduce: Create a BOM with byproduct and Routing with at least one operation. Create MO with such, plan MO, process workorders.

Current behavior: Only the finished good produced qty gets updated. The byproduct quantities are 0.

Expected behavior: Byproduct produced qty should be equal to qty to produce

Video/Screenshot link (optional):

**Comment by amoyaux** [comment] 2018-02-21 16:37
Duplicate of issue https://github.com/odoo/odoo/issues/14126

**Closed by amoyaux** 2018-02-21 16:37 UTC
Labels: 10.0, Logistics
