### ISSUE TITLE
[11.0] POS problem with invoice PDF

### ISSUE THREAD

**Issue by thomas15v** [odoo/odoo#28754] opened 2018-11-16 11:32 UTC
Impacted versions:
11.0

Steps to reproduce:
1. Open pos with posbox on android with Google Chrome 70.xxx
2. Create an invoice on the POS system
3. Click confirm

Current behavior:

There are 2 things that can happen after this point:
1. An error occurs. You can however click away the error and try again and everything will be fine
2. The pos system times out and keeps waiting.

I think the error itself is caused because the POS system sends undefined instead of the invoice id. But I am having a very hard time trying to replicate this issue.

Expected behavior:

No error and possible an option to not download a PDF in the first place. 

Video/Screenshot link (optional):
![img_20181114_142135 002](https://user-images.githubusercontent.com/2163941/48619001-59c3b180-e99b-11e8-8cbc-417a59a64dfa.jpg)

**Comment by pedrobaeza** [comment] 2018-11-16 11:40
Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by thomas15v** [comment] 2018-11-16 16:34
I can not simulate it with my android phone on the runbot. I guess it might be an infrastructure problem or a specific problem with samsung tablets (I suspect the download manager from doing something). If I find more information or a way to resolve it I will post it here.

**Comment by pedrobaeza** [comment] 2018-11-16 16:35
@switch87 you decide if we keep this opened meanwhile.

**Comment by switch87** [comment] 2018-11-19 08:49
@thomas15v, it would surprise me if this has anything to do with the download manager of your tablet. What you could try is to empty the cache of your tablets browser, it could be a problem there. Because you cannot reproduce this problem on runbot I also advice you to make sure your server is up to date with the latest version of Odoo 11.0.

I have taken a look at the code mentioned in the traceback, but based on the little information we have and the impossibility to reproduce I will close this issue. If you manage to get us more information, do not hesitate to add it to the issue to reopen it.

cc @pedrobaeza

**Closed** 2018-11-19 08:51 UTC
Labels: 11.0, Need information, Point of Sale
