### ISSUE TITLE
Suggestion: make city field a drop-down everywhere, when the list of cities is loaded

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#28952] opened 2018-11-22 11:37 UTC
**Tested versions:**
v12.0 / v 11.0

**Steps to reproduce:**
- On a full database (demo.odoo.com) Install `base_address_city`
- Change portugal to enforce cities
- Create City "Lisboa" for portugal
- Create an opportunity
- Set Portugal as the country on that opportunity (follow up tab)

**Current behavior:**
- City field is not a dropdown

**Suggested behavior:**
- City field should be a drop down, also on CRM (and all other instances where a address is entered)
- Could we look into improving this in the next versions?

**Comment by pedrobaeza** [comment] 2018-11-22 11:40
Sorry, but I understand perfectly, and you want to achieve something that is not possible in stable and out of scope in other versions. But I will let @odony to close it this time if he considers the same as me.

For reference, this is a duplicate of #28930

**Comment by blaggacao** [comment] 2018-11-22 11:46
I don't reclaim with any word it should be tackled on _stable_. I wonder where you take this assumption from...

**Comment by pedrobaeza** [comment] 2018-11-22 12:09
Read second part about "out of scope in other versions" (I mean v13). This is a clear candidate for a community module `crm_base_address_city`. And also as said, that module might absorbed by core one day.

**Comment by blaggacao** [comment] 2018-11-22 13:05
What the hell are you basing your judgements on? I mean, there is a possibility that you have a point, but it's so god damn intransparent. I don't think you have a compelling argument here. Which leads me to think your judgment is based on ignorance or arrogance. This is the most annoying bit about when you comment on issues.

**Comment by Yenthe666** [comment] 2018-11-22 13:38
@pedrobaeza 
Something can still be valuable if it cannot be done in stable and is not mandatory to have though (or atleast not mandatory for you). From personal experience I've noticed that as long as it is just here in a closed issue nobody really seems to look at it. Only when there is an internal task in the Odoo system it seems to be followed up and monitored so I can understand the frustration from @blaggacao honestly.

On a sidenote: we should really find a good way where people can put their suggestions and ideas and where there is listened to them. Clearly Github does not seem to have that effect on Odoo.

**Comment by pedrobaeza** [comment] 2018-11-22 13:52
That's the point, Yenthe, this doesn't serve currently, and that's why I close them, or do you want an issue tracker with 1000 wishlist issues in 2 years? And I close them also in a feasibility spirit, which is subjective, but based also on my experience. In this case, as this can be easily solved in a community module, and the facts exposed previously, I predict this will be one of the lower priorities.

But I agree we can look for another way to put suggestions:

![imagen](https://user-images.githubusercontent.com/7165771/48906888-33ec5000-ee66-11e8-8284-8926dfc11247.png)

(JOKE)

**Comment by blaggacao** [comment] 2018-11-22 14:06
@pedrobaeza If Odoo has given you decision power, you have their trust. Why don't you point to the right product owner and flag this as a valuable suggestion where they either create an internal task or close this issue based on the product owner's judgment.

That's fully in line with your GTD methodology, it's even more efficient. And it's truly empowering.

Refine yourself! :wink:

**Comment by blaggacao** [comment] 2018-11-22 16:07
> so I prefer to not doing

In this case you didn't understand the whole context of this issue, which is less dev oriented, but rather UX oriented. Remember, that there are a growing number of product owners at Odoo.

It's silly to assume you can't find exactly the right angle to place this issue there.
And it's even sillier to assume they would not be grateful for it.

However, don't rise such topics to the developer in the first place, that's indeed not efficient. But it's not the whole truth, either.

**Comment by blaggacao** [comment] 2018-11-22 16:19
> This can't be implemented in base_address_city module per dependencies and granularity

This phrase exhibits a lack of imagination. We already have seen an AddressFormatMixin in the back end, so why do you reason based on such limited assumptions? Is it precisely because of your huge experience??

I think you can a little bit it why you drive very knowledgeable people mad, at times. It's all covered up and explodes at the same time in your non-involving engagement on some issues.

**Comment by odony** [comment] 2018-11-22 18:57
(I think) I understand both sides of the discussion, and you both have valid points. We don't have a very effective feedback channel on Github indeed, but we do have one internally, and I have opened an entry with this suggestion - asking our POs to give you feedback here. We can keep the issue open until we get feedback from them.

PS: Sorry for locking the issue temporarily, but I know how difficult it is to resist answering a heated discussion ;-)

**Comment by Yenthe666** [comment] 2018-11-22 19:08
Thanks a lot for your valuable feedback Olivier. I'm happy you made an internal task to discuss it internally. Please reach out to me regarding community feedback and streamlining. I think we need to put some extra effort into this but it is off topic here.

**Closed** 2023-03-30 13:46 UTC
Labels: Wishlist
