### ISSUE TITLE
Incorrect padding on v12 (ir_http.py guess_mimetype)

### ISSUE THREAD

**Issue by litnimax** [odoo/odoo#33082] opened 2019-05-01 15:54 UTC
Many times per day I can see in my error log:

```
Error: Incorrect padding
  File "raven/middleware.py", line 20, in common_exception_handling
    yield
  File "raven/middleware.py", line 100, in __call__
    iterable = self.application(environ, start_response)
  File "odoo/service/wsgi_server.py", line 126, in application
    return werkzeug.contrib.fixers.ProxyFix(application_unproxied)(environ, start_response)
  File "werkzeug/middleware/proxy_fix.py", line 228, in __call__
    return self.app(environ, start_response)
  File "odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "odoo/http.py", line 1318, in __call__
    return self.dispatch(environ, start_response)
  File "odoo/http.py", line 1291, in __call__
    return self.app(environ, start_wrapped)
  File "werkzeug/middleware/shared_data.py", line 227, in __call__
    return self.app(environ, start_response)
  File "odoo/http.py", line 1486, in dispatch
    result = ir_http._dispatch()
  File "odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "odoo/addons/web_editor/models/ir_http.py", line 22, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "odoo/addons/http_routing/models/ir_http.py", line 394, in _dispatch
    result = super(IrHttp, cls)._dispatch()
  File "odoo/addons/base/models/ir_http.py", line 207, in _dispatch
    return cls._handle_exception(e)
  File "odoo/addons/website/models/ir_http.py", line 177, in _handle_exception
    return super(Http, cls)._handle_exception(exception)
  File "odoo/addons/base/models/ir_http.py", line 177, in _handle_exception
    return request._handle_exception(exception)
  File "odoo/http.py", line 774, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "odoo/addons/base/models/ir_http.py", line 203, in _dispatch
    result = request.dispatch()
  File "odoo/http.py", line 833, in dispatch
    r = self._call_function(**self.params)
  File "odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "odoo/addons/web/controllers/main.py", line 1076, in content_image
    default_mimetype='image/png', related_id=related_id, access_mode=access_mode, access_token=access_token)
  File "odoo/addons/web/controllers/main.py", line 435, in binary_content
    env=env)
  File "odoo/addons/website/models/ir_http.py", line 260, in binary_content
    access_mode=access_mode, env=env)
  File "odoo/addons/base/models/ir_http.py", line 365, in binary_content
    mimetype = guess_mimetype(base64.b64decode(content), default=default_mimetype)
  File "python3.5/base64.py", line 88, in b64decode
    return binascii.a2b_base64(s)
```

I have no idea what can cause this. May be somebody knows.

**Comment by Yenthe666** [comment] 2019-05-02 06:14
@pedrobaeza do you know the real reason? I've seen some of those lately too

**Comment by gdgellatly** [comment] 2019-05-03 12:01
@Yenthe666 upload a png file as favicon is how I fix it. I think there is an issue with default one.

**Comment by pedrobaeza** [comment] 2019-05-03 12:02
No idea by my part, sorry.

**Comment by misnedtech** [comment] 2019-05-29 10:45
Me too got same error on server. This happens after updating odoo with latest code from github (76131748f9e492a0ebe751481f952dda30bca1f7). Now I am not able to use ERP, displaying nothing on browser but white screen.

...
...
...
  File "/home/erp/workspace/odoo_12e/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/home/erp/workspace/odoo_12e/addons/web/controllers/main.py", line 1076, in content_image
    default_mimetype='image/png', related_id=related_id, access_mode=access_mode, access_token=access_token)
  File "/home/erp/workspace/odoo_12e/addons/web/controllers/main.py", line 435, in binary_content
    env=env)
  File "/home/erp/workspace/odoo_12e/addons/website/models/ir_http.py", line 317, in binary_content
    access_mode=access_mode, env=env)
  File "/home/erp/workspace/odoo_12e/odoo/addons/base/models/ir_http.py", line 365, in binary_content
    mimetype = guess_mimetype(base64.b64decode(content), default=default_mimetype)
  File "/usr/lib/python3.6/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding - - -

**Comment by Yenthe666** [comment] 2019-06-12 08:35
I've found one in the logs again so I can provide a traceback now:
```
2019-06-12 08:28:15,865 1055 ERROR Test01 odoo.addons.website.models.ir_http: 500 Internal Server Error:

Traceback (most recent call last):
  File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 203, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo/http.py", line 833, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/website/controllers/main.py", line 476, in favicon
    return self.content_image(model='website', id=str(request.website.id), field='favicon', **kw)
  File "/opt/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/website/controllers/main.py", line 471, in content_image
    return Binary().content_image(**kw)
  File "/opt/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 1076, in content_image
    default_mimetype='image/png', related_id=related_id, access_mode=access_mode, access_token=access_token)
  File "/opt/odoo/addons/web/controllers/main.py", line 435, in binary_content
    env=env)
  File "/opt/odoo/addons/website/models/ir_http.py", line 317, in binary_content
    access_mode=access_mode, env=env)
  File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 365, in binary_content
    mimetype = guess_mimetype(base64.b64decode(content), default=default_mimetype)
  File "/usr/lib/python3.6/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
```

I also tested with a `.png` favicon as @gdgellatly suggested but without success.
It seems to come back from 
https://github.com/odoo/odoo/blob/63e19c118bb26a7419a9892e1122330181f6012d/addons/web/controllers/main.py#L427-L435

The only way I was able to resolve it was basically an update of the `website` module.

**Comment by JKE-be** [comment] 2019-06-12 14:05
I take several hours to try to reproduce but not found.

The error is because at a moment, you got the size of your picture instead of the picture (but how??? I have no idea).

But I suppose that if you do "select favicon from website", you will have `\x31353336206279746573`, that is a binary form of `1536 bytes`

If anybody can find a way to reproduce it, I will be happy to take a look !!! 

But I have no more idea.
My first idea was a bin_size=True somewhere in res.config.settings but not found... or a bug of onchange (idea from rco) but tested a lot of situation without see the error...

**Comment by block-cat** [comment] 2019-07-18 02:52
I met the same issue and print the content by track infos

![image](https://user-images.githubusercontent.com/6907475/61425532-d0111d00-a949-11e9-90e2-382ebb01f3e5.png)

I found the favicon field of website was written something strange.

![image](https://user-images.githubusercontent.com/6907475/61425592-fdf66180-a949-11e9-92e4-bdbdf4abae69.png)

I don't know the reason but I solved the problem by:

`update website set favicon=null;`

**Comment by Yenthe666** [comment] 2019-07-28 20:51
Hmm interestingly enough I've hit this one again on another database. When I checking the favicon from the website (like block-cat suggested) I also get a very odd value for the field.
```
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 \x414141424141454145424141414145414941426f4241414146674141414367414141415141414141494141414141454149414141414141414141514141424d4c4141415443774141414141414141414141414141414141414141414141495a466f41434b527149416955616845496c476f6b364a52714b4d6955616971346c476f71754a52714b4c6955616953346c476f67364a527149416945576841414141414141414141414141414141414968466f514349526145436955616952596c476f72714a52714c7a695561692f346c476f762b4a52714c2f695561692f346c476f764b4a52714b3069556169506f68466f51474a527145414141414141496c476f6743495261454369556169596f6c476f75714a52714c2f695561692f346c476f762b4a52714c2f695561692f346c476f762b4a52714c2f695561692f346c476f75614a52714a5968554f64414968466f51434a5271494169556169526f6c476f75714a52714c2f695561692f346c476f75794a52714b6a69556169626f6c476f6d364a52714b6a6955616937496c476f762b4a52714c2f6955616935496c476f6a324a527149416955616845596c476f72714a52714c2f695561692f346c476f74694a52714a476945616842496c476f67434a527149416945616842496c476f6b614a52714c59695561692f346c476f762b4a52714b786955616944596c476f6c434a52714c7a695561692f346c476f764b4a52714a5169556169414968466f6741414141414141414141414968466f51434a527149416955616955496c476f764b4a52714c2f6955616938596c476f6b714a52714b4e695561692f346c476f762b4a52714b3369556168436f6c476f514141414141414141414141414141414141414141414169456168414968476f51714a52714b33695561692f346c476f762b4a52714b4b6955616971346c476f762b4a52714c2f69556169695970476f774348526141414141414141414141414141414141414141414141414964466f41434b52714d416955616969596c476f762b4a52714c2f6955616971346c476f71714a52714c2f695561692f346c476f6f714b52714d416830576741414141414141414141414141414141414141414141434952614541696b656a41496c476f6f2b4a52714c2f695561692f346c476f716d4a52714b49695561692f346c476f762b4a52714b366955616843346c476f51414141414141414141414141414141414141414141416955616841496c476f512b4a52714c44695561692f346c476f762b4a52714b476955616953496c476f76434a52714c2f6955616939496c476f6c694b52714d4169456168414141414141414141414141694557684149354b7077434a52714a6b695561692b496c476f762b4a52714c756955616952496c476f67794a52714b76695561692f346c476f762b4a52714c676955616956346c476f51714a527149416930696a41496c476f51324a52714a6969556169356f6c476f762b4a52714c2f69556169715968466f51714a52714941695561694f596c476f75434a52714c2f695561692f346c476f764f4a52714b3669556169696f6c476f6f364a52714c4269556169396f6c476f762b4a52714c2f6955616933596c476f6a534a5271494169455768414a464d7251434a52714a4f6955616933596c476f762b4a52714c2f695561692f346c476f762b4a52714c2f695561692f346c476f762b4a52714c2f69556169336f6c476f6b794b534b5541694557684141414141414349527145416845476241496c476f6a474a52714b6a6955616936346c476f76364a52714c2f695561692f346c476f762b4a52714c776955616971346c476f6a5238513567416945616841414141414141414141414141414141414952456e51434a527149416955576943496c476f6a794a52714a396955616970596c476f71754a52714b4969556169526f6c476f67754a527149416945576841414141414141414141414138413841414d4144414143414151414167414541414147414141414834414141422b414141412f774141415038414141422b414141416667414141426741414167414541414d414441414441417741413841384141413d3d
```
The backend shows no image as if there is no favicon set.

**Comment by dansanti** [comment] 2020-02-02 02:09
hello!
maybe the problem is because a cache problem. So when i make a One2many tree, and set a computed field tha reads a file,this makes a incorrect padding, because odoo sendo base64 the object field, not the string to decode
example:
`
class NewTable(model.Models):
    _name = "new_table"

    def read_method(self):
        for r in self:
            data = base64.b64decode(r.binary_content)
            data_result = r._process_data(data)
            r.compute_field = data_result["target_integer"]

    compute_field = fields.Integer(
       compute="read_method"
    )
    
    binary_content = fields.Binary(
        string="target_content"
    )
    ref_id = fields.Many2one(
        'new_table_2'
    )
    


class NewTable2(model.Models):
    _name = "new_table_2"


    def read_method(self):
        for r in self:
            sum = 0
            for t in r.targets:
                sum += t.compute_field
            r.compute_field_2 = sum

    compute_field_2 = fields.Integer(
       compute="read_method"
    )

    targets = field.One2many(
        'new_table',
        'ref_id'
    )
`


so in this case if you add a new file to targets, gets a binary object buts i want a string to decode, but example I add a button on NewTable view, like <button type="object" string="manual load" name="read_method"/>    its works fine, method retrieve a string to decode( using the same method and decoring with @api.multi". 

This happends to if you want to add a new file to a tree and you read it when its tree change, gets an object binary no the string binary

**Comment by rb3606** [comment] 2020-05-30 10:16
Hi while i tried to import data using csv file i am getting same error .
`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo12/odoo/service/server.py", line 434, in app
    return self.app(e, s)
  File "/opt/odoo12/odoo/service/wsgi_server.py", line 142, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo12/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/opt/odoo12/odoo/http.py", line 1320, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo12/odoo/http.py", line 1293, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo12/odoo/http.py", line 1488, in dispatch
    result = ir_http._dispatch()
  File "/opt/odoo12/addons/website_sale/models/ir_http.py", line 15, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/opt/odoo12/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "/opt/odoo12/addons/web_editor/models/ir_http.py", line 22, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/opt/odoo12/addons/http_routing/models/ir_http.py", line 403, in _dispatch
    result = super(IrHttp, cls)._dispatch()
  File "/opt/odoo12/addons/utm/models/ir_http.py", line 26, in _dispatch
    response = super(IrHttp, cls)._dispatch()
  File "/opt/odoo12/odoo/addons/base/models/ir_http.py", line 207, in _dispatch
    return cls._handle_exception(e)
  File "/opt/odoo12/addons/website/models/ir_http.py", line 195, in _handle_exception
    return super(Http, cls)._handle_exception(exception)
  File "/opt/odoo12/addons/utm/models/ir_http.py", line 31, in _handle_exception
    response = super(IrHttp, cls)._handle_exception(exc)
  File "/opt/odoo12/odoo/addons/base/models/ir_http.py", line 177, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/odoo12/odoo/http.py", line 776, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo12/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo12/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo12/odoo/addons/base/models/ir_http.py", line 203, in _dispatch
    result = request.dispatch()
  File "/opt/odoo12/odoo/http.py", line 835, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo12/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo12/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo12/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo12/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo12/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo12/addons/base_import/controllers/main.py", line 20, in set_file
    'file_type': file.content_type,
  File "/opt/odoo12/odoo/models.py", line 3344, in write
    self._write(store_vals)
  File "/opt/odoo12/odoo/models.py", line 3412, in _write
    val = field.convert_to_column(val, self, vals)
  File "/opt/odoo12/odoo/fields.py", line 1816, in convert_to_column
    decoded_value = base64.b64decode(value)
  File "/usr/lib/python3.6/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding - - -
`

**Comment by JKE-be** [comment] 2020-05-30 14:37
Can you share the file please ?

Jeremy Kersten

**Comment by JKE-be** [comment] 2020-10-23 09:30
while we cannot reproduce it, I close it !

**Closed by JKE-be** 2020-10-23 09:30 UTC
Labels: Website

**Comment by EwetoyeIbrahim** [comment] 2021-04-07 09:25
How I got this same error was in two steps, sometimes only the second occurs.

1. Settings > General > Acess Rights > Click on default access right. It throws:
`
Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 88, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7f963e627400>, 'base.default_user')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base_setup/models/res_config_settings.py", line 74, in open_default_user
    action['res_id'] = self.env.ref('base.default_user').id
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 864, in ref
    return self['ir.model.data'].xmlid_to_object(xml_id, raise_if_not_found=raise_if_not_found)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_model.py", line 1443, in xmlid_to_object
    t = self.xmlid_to_res_model_res_id(xmlid, raise_if_not_found)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_model.py", line 1427, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-25>", line 2, in xmlid_lookup
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 93, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_model.py", line 1416, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: base.default_user
`


2. Close the pop-up window from step 1, and try clicking on access rights again. It throws:
`
Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 757, in call_kw
    return _call_kw_model_create(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 737, in _call_kw_model_create
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-268>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 440, in _model_create_single
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/account/models/res_config_settings.py", line 161, in create
    return super(ResConfigSettings, self).create(values)
  File "<decorator-gen-3>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 461, in _model_create_multi
    return create(self, [arg])
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3621, in create
    fields[0].determine_inverse(batch_recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1143, in determine_inverse
    self.inverse(records)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 642, in _inverse_related
    other[field.name] = record_value[record]
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5154, in __setitem__
    return self._fields[key].__set__(self, value)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1048, in __set__
    record.write({self.name: write_value})
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/website.py", line 151, in write
    result = super(Website, self - public_user_to_change_websites).write(values)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3346, in write
    self._write(store_vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3476, in _write
    field.write(other, vals[field.name])
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1886, in write
    atts.write({'datas': value})
  File "/usr/lib/python3/dist-packages/odoo/addons/calendar/models/ir_attachment.py", line 30, in write
    return super(Attachment, self).write(vals)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_attachment.py", line 481, in write
    vals = self._check_contents(vals)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_attachment.py", line 255, in _check_contents
    mimetype = values['mimetype'] = self._compute_mimetype(values)
  File "/usr/lib/python3/dist-packages/odoo/addons/muk_utils/models/ir_attachment.py", line 132, in _compute_mimetype
    return super(IrAttachment, self)._compute_mimetype(values)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_attachment.py", line 251, in _compute_mimetype
    mimetype = guess_mimetype(base64.b64decode(values['datas']))
  File "/usr/lib/python3.6/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
`

**Comment by JKE-be** [comment] 2021-04-07 09:30
Hello

It is not related to this bug.
Meanwhile it has been fixed.

In your case, you have this similar bug, because you delete the default_user, so you have a Falsy value.
you should make an update of base module and all should works again...

Best regards

**Comment by mvikral** [comment] 2021-04-12 04:52
im migrating odoo 12 from one server into another server, and got this error
default_mimetype='image/png', related_id=related_id, access_mode=access_mode               , access_token=access_token)
  File "/opt/odoo/odoo-server/odoo/addons/web/controllers/main.py", line 435, in                binary_content
    env=env)
  File "/opt/odoo/odoo-server/odoo/addons/website/models/ir_http.py", line 260,                in binary_content
    access_mode=access_mode, env=env)
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_http.py", line 365, in                binary_content
    mimetype = guess_mimetype(base64.b64decode(content), default=default_mimetyp               e)
  File "/usr/lib/python3.6/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding - - -
2021-04-12 04:46:52,426 14987 INFO bill odoo.addons.base.models.ir_cron: Startin               g job `Post process payment transactions`.

was the problem same as the post?

**Comment by JKE-be** [comment] 2021-04-22 08:11
The error that you post is probably because you try to decode from base64 something that is not a base64...
So the output is the same... but not linked to the favicon error that has been fixed meanwhile.

Maybe a rsync between your filtestore will solve it.
Else you need to print more info to see the file and de content that is used when it crash.
