### ISSUE TITLE
Bug: You can only adjust storable products.

### ISSUE THREAD

**Issue by HafedhRahmani** [odoo/odoo#43717] opened 2020-01-22 08:53 UTC
https://github.com/odoo/odoo/blob/d02baddc8940469dbb719ce367ec1e42c368fdca/addons/stock/models/stock_inventory.py#L236

I can't make a start of my inventory, by what it detects lines there is product of service type (constraint _check_product_id () in the class inventory lines)!
Can you add a condition to filter only the "stock quants" as of product type ('type', '=', 'product')? because I had a bug at this level.

Historical:
I have a database migrated from version 9 to version 12 (in the last this db was under v 6).
this database already contains stock records for a service type product (probably this product was stockable product in time).
Thank you!
![stock quant](https://user-images.githubusercontent.com/36736035/72879341-f949a600-3cfc-11ea-9c0b-79e3a1b401ee.jpg)

**Comment by pedrobaeza** [comment] 2020-01-22 08:55
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case. You are mentioning a migrated database. How did you migrate it?

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by HafedhRahmani** [comment] 2020-01-22 09:05
I can't reproduce the problem on runbut, because it can only be reproduced on a migrated db from version 6 to 12 and and you must have a product that changed from sockable type to service type.

Can you look at the code, and see if you can add a condition that filter non stockable products?

**Comment by pedrobaeza** [comment] 2020-01-22 09:07
How did you migrate the database?

**Comment by HafedhRahmani** [comment] 2020-01-22 09:08
By odoo Upgrade 9 To 12 (Entreprise licence):
https://upgrade.odoo.com

**Comment by pedrobaeza** [comment] 2020-01-22 09:11
And from 6.1 to 9? If this is something on the Odoo upgrade part, you should put an issue on odoo.com/help for them to check the migration done, but nothing that can be tracked here, as it's not reproducible in standard, so closing.

**Closed by pedrobaeza** 2020-01-22 09:11 UTC
Labels: Need information

**Comment by HafedhRahmani** [comment] 2020-01-22 09:15
From v6.1 to 9 it was migrating for 4 years I think.
I don't know the history

**Comment by pedrobaeza** [comment] 2020-06-04 16:56
Well, it's a bad manipulation at the end. OK about adding improvements on that, but it's not a bug.

@sle-odoo @amoyaux what do you think about these 2 suggestions?

**Comment by andrewdhastings** [comment] 2020-06-04 17:15
Yes, technically the customer shouldn't do that....but they CAN. Which in my book is a bug. 

Odoo should not let you do anything that breaks another feature. That is the very definition of a bug. Either the inventory adjustment form needs to exclude all "consumable" products by default, or it should be prevented as suggested above.  Just my two cents. 

Not sure if there is a use case where you would want to allow archiving or changing product type with stock on hand?

**Comment by Yenthe666** [comment] 2020-06-04 18:08
I'd like to be in favor of @andrewdhastings and label this as a bug though. We should prevent this or make sure it doesn't impact the results.

**Comment by pedrobaeza** [comment] 2020-06-04 18:10
OK, I still don't consider it a bug, but if you think that way, please label it, Yenthe.

**Comment by Yenthe666** [comment] 2020-06-04 18:15
Well, I'd like to be on one page :) Why don't you consider it a bug? The system allows changing the product type & it keeps the old data in place to. That's bound to give wrong behavior which is a bug, no?

**Comment by pedrobaeza** [comment] 2020-06-04 18:21
My point is that preventing everything a user can do wrong is impossible. What about changing the product to service? What about that stock is reserved in some moves before changing? What about the quants that have been moved to other locations? Some of these questions can be avoided forbidding the change, but the number of prohibitions to put should be limited, or you will have an unusable system in several cases (as the system forbids operations due to human errors), or most of the code will be business constraints instead of business logic.

**Comment by andrewdhastings** [comment] 2020-06-04 19:24
I do see your point, we can't prevent all user issues. However, I feel this is a considerable issue that I have seen time and time again (esp archiving products with qty on hand). 

The system already checks for open moves and throws an error, so that check is already being done. We would just need to add a stock check. If there are qty in other locations, I still consider that "qty on hand". (production, scrap, customer/vendor, etc locations aside)

**Comment by ray-odoo** [comment] 2020-06-24 23:24
Just ran into this today.   I found products that are now services or consumables that were once storable.

**Comment by mohdshoaib04** [comment] 2020-07-01 09:26
Same issue here.

**Comment by nivels** [comment] 2020-07-01 11:26
@pedrobaeza
 
> I was able to reproduce the error. (had a client with the same issue)
> This is an issue and should probably be reopened.
> Steps to reproduce:
> 
> 1. Create a Stockable Product
> 2. Add qty on hand
> 3. Change to consumable product type (without removing qty on hand)
> 4. Try to create an inventory adjustment (without specifying a product, just click on start inventory)
> 
> My Solution:
> If you go to the product, change it back to a stackable product. Then reduce the "qty on hand" to 0. Change it back to a consumable product. Now it should work.
> 
> However, this is just a patch. I think Odoo should fix the underlining issue. I think there are two issues that should be addressed:
> 
> 1. When changing a product from stockable to consumable it should check to see if there is Qty on Hand. If so, then prevent the change and/or auto zero the qty on hand first (with user prompt/permission).
> 2. Same issue when Archiving a product. You shouldn't be able to archive a product that has Qty on Hand as it will sit on the books forever with no way to remove it.

same issue on our clients

**Comment by pedrobaeza** [comment] 2020-07-01 11:30
I can ping @sle-odoo and @amoyaux for considering to extend the check not only changing UoM, but also product type, but no guarantee this is going to be accepted and more in current stable versions.
