### ISSUE TITLE
[11.0] Redirect error after deleting child_ids and self.

### ISSUE THREAD

**Issue by Linekio** [odoo/odoo#24244] opened 2018-04-16 08:51 UTC
Impacted versions:
11.0
Steps to reproduce:
Install contacts module.
Open a partner who have child_ids.
Delete one or more childs.
Delete the partner.

Current behavior:
The page isn't redirect to another partner.

Expected behavior:
Redirect to another partner.

Video/Screenshot link (optional):
<a href="http://www.k-upload.fr/afficher-video-2018-04-16-124bae0e2output.mp4.html" title="K-Upload - Hébergeur de video gratuit">Video link</a>

**Comment by sswapnesh** [comment] 2018-05-10 18:35
I can not Reproduce the same on [Runbot](http://runbot.odoo.com/runbot).

**Comment by pedrobaeza** [comment] 2018-05-10 19:12
Hi, I'm not able either to reproduce this problem in latest runbot version, so I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-05-10 19:12 UTC
Labels: 11.0, Framework

**Comment by Linekio** [comment] 2018-05-11 06:56
New issue, reproduced on Runbot: [#24676](https://github.com/odoo/odoo/issues/24676)
