### ISSUE TITLE
Error when adding followers in Time Off document

### ISSUE THREAD

**Issue by vmelnych** [odoo/odoo#48727] opened 2020-04-01 14:29 UTC
**Impacted versions:** 13.0 (night build 31.03.2020)
tried on several March builds - same thing.

**Steps to reproduce:** hard to narrow down as a full set of activities was done:
1. Take a full backup and restore to another db
2. delete all employees and remove all leaves
3. create few dummy users and employees, one is a manager of another one
4. register a paid leave - add followers - works!
5. register a sick leave - add followers (pops up a message about security restrictions)
6. try to add followers to already approved ticket - error message (the second attempt on the same action does not even show an error - no reaction)

**Current behavior:** 
adding a follower - the first time shows an error message:
Traceback:
TypeError: Cannot read property 'bind' of undefined
    at http://10.0.0.75/web_editor/static/src/js/wysiwyg/root.js:46:57
    at Function._.each._.forEach (http://10.0.0.75/web/static/lib/underscore/underscore.js:145:9)
    at http://10.0.0.75/web_editor/static/src/js/wysiwyg/root.js:45:15

**Expected behavior:** shows the dialog to specify followers

**Video/Screenshot link:**
![Heitor Gonzales on Sick Leave - add followers](https://user-images.githubusercontent.com/49236938/78148865-a0516900-7435-11ea-8bac-cf170f23cee4.png)

**Comment by vmelnych** [comment] 2020-04-01 15:03
Became a "Superuser", activated Tests Assets Debugging and repeated the same. Here is the console output:
![Heitor Gonzales on Sick Leave - add followers debug](https://user-images.githubusercontent.com/49236938/78152859-af86e580-743a-11ea-8c21-6fcaa6355e2c.png)

**Comment by pedrobaeza** [comment] 2020-04-01 15:51
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by pedrobaeza** [comment] 2020-05-08 19:58
Closing as no more answer.

**Closed by pedrobaeza** 2020-05-08 19:58 UTC
Labels: Need information
