### ISSUE TITLE
Calendar  filter when i checked everybody's calenders Issue based on odoo11

### ISSUE THREAD

**Issue by JackSunI** [odoo/odoo#39839] opened 2019-11-06 10:06 UTC
### Impacted versions:
       odoo 11.0
### Steps to reproduce:
&nbsp; &nbsp; &nbsp; &nbsp; when i created a new User and then checked the select Everybody's calendars . the first one ,all  normal, Second  nothing render.But not all Users are not  normal.   <br>
&nbsp; &nbsp; &nbsp; &nbsp;  And then i found the Python codes for the module . I found the code : <br>
 ```events = super(Meeting, self).search(new_args, offset=0, limit=0, order=None, count=False)```<br>
&nbsp; &nbsp; &nbsp; &nbsp; the new_args  is a domain. But the list has the partner_id , the partner_id is a related field:  <br>
```partner_id = fields.Many2one('res.partner', string='Responsible', related='user_id.partner_id', readonly=True)``` <br>
&nbsp; &nbsp; &nbsp; &nbsp; Is   the related field  not normal when searched ? 

#### The first checked:
![image](https://user-images.githubusercontent.com/56639586/68288760-f6f18b80-00bf-11ea-8eaf-3be6fa27222b.png)

#### Second checked:
![image](https://user-images.githubusercontent.com/56639586/68286975-eee41c80-00bc-11ea-9fec-969f99db140e.png)

`Thanks for watching.`

**Comment by pedrobaeza** [comment] 2019-11-06 10:07
I don't get the problem...

**Comment by JackSunI** [comment] 2019-11-06 10:18
Sorry, My English is not Ok. The porblem is when i create a new User named Jack Sun . And install calendar model. When i first use the module and selected the Everybody's calendars
![image](https://user-images.githubusercontent.com/56639586/68289678-85b2d800-00c1-11ea-82a9-72dbb336431e.png)
all is Ok . But selected again , is not normal . Nothing.

**Comment by pedrobaeza** [comment] 2019-11-06 10:20
Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by JackSunI** [comment] 2019-11-06 10:20
Is the  field   problem who has the param 'related' ?

**Comment by pedrobaeza** [comment] 2019-11-06 10:23
I don't think so, but still not clear steps to reproduce the problem.

**Comment by JackSunI** [comment] 2019-11-08 02:52
Hi Pedro,
Still the problem , it still exists.
We added a new company (Studio Vadi) and there are two users (Adam and Carmela).
When they view the calendar, clicking on "Everybody's Calendar" shows nothing. But it works OK if they select individual users.

But here has another one ,

One user (Kat Lam) has created several calendar events, and another user (Kit Chau) has accepted the invitations. However, when Kit is signed in to Warric he cannot see any of these events in the calendar view. They are displayed in the List View, and they are also displayed in both Calendar View and List View when he is signed in to Thicas.

Even stranger, today (Monday) these events are visible in the Calendar view when signed in to either Warric or Thicas.

**Comment by JackSunI** [comment] 2019-11-08 03:20
![pic1](https://user-images.githubusercontent.com/56639586/68447015-65962c80-0219-11ea-95ec-150895da12ba.jpg)

**Comment by JackSunI** [comment] 2019-11-08 03:20
![pic2](https://user-images.githubusercontent.com/56639586/68447118-c6be0000-0219-11ea-8486-945e5f24548b.jpg)

**Comment by JackSunI** [comment] 2019-11-08 03:22
![pic3](https://user-images.githubusercontent.com/56639586/68447161-ece3a000-0219-11ea-8f1c-337144df1677.png)
I changed the code , As shown , all is OK.
Thanks .

**Comment by pedrobaeza** [comment] 2019-11-08 08:36
@mart-e are you understanding the problem?

**Comment by JackSunI** [comment] 2019-11-12 01:40
Hi, brother
I want to  know the  Progress of the problem. 
Is the compute fields in search problem  while the user has a lot of data? For some reason， I can not change the code to fixing the problem.
Thanks .
@mart-e

**Comment by pedrobaeza** [comment] 2019-11-12 08:27
As this is a voluntary effort, there's no guarantee even of answer. If you have an enterprise contract, you can submit a ticket to odoo.com/help for assuring an answer.

**Comment by JackSunI** [comment] 2019-11-13 03:34
Thanks bro,
The first problem has been solved. Thanks again. @mart-e

**Closed** 2019-11-13 07:46 UTC
Labels: Need information
