### ISSUE TITLE
cant install timesheets

### ISSUE THREAD

**Issue by dpelaez** [odoo/odoo#5831] opened 2015-03-18 17:14 UTC
In relation to this issue [8.0] Unable to install Timesheet modules #1839, I am having the same problem. I deleted the service product when I created the database. I created a new database without deleting the service and I was able to install the module.

I tried creating a service product and installing the module, but it gave me the same error. Is there a way to install the module without having to start with a new database?

**Comment by isometriq** [comment] 2015-03-22 16:51
Same problem here, using Version 8.0-20150128
I would think that if the "Service" product is specifically needed, it trying to match a unique field like an ID. I think we need to check the exact value in the database to compare, otherwise the source code...

**Comment by isometriq** [comment] 2015-03-22 17:01
Found this commit
cd12832f9e3b75c524855a9ea808dd3dab5e6472

Seems to reference a "sale_ok" field being "true" in
https://github.com/odoo/odoo/blob/cd12832f9e3b75c524855a9ea808dd3dab5e6472/addons/hr_timesheet/hr_timesheet_data.xml

And "sale_ok" field being "false" in
https://github.com/odoo/odoo/blob/cd12832f9e3b75c524855a9ea808dd3dab5e6472/addons/product/product_data.xml

..I do not fully understand what it means, but maybe the problem has something to do with the "sale_ok" field ?

**Comment by loslolos** [comment] 2015-03-24 22:42
I had the same issue. I was able to install timesheet module after upgrade of Employee Directory module.

**Comment by isometriq** [comment] 2015-03-24 23:08
Good to know, I'll test on my end to confirm when I have some time.

**Comment by dpelaez** [comment] 2015-03-24 23:14
Didn't work for me. did you use the latest build?

**Comment by isometriq** [comment] 2015-03-30 05:24
Didn't work for me too.. the system yeld the exact same error

**Comment by isometriq** [comment] 2015-03-30 06:08
Testing with a new database, I can observe that by installing the Timesheets module, the record id#1 in the table "product_template" (the default "Service" product that comes with a new database) ..its field "sale_ok" will be set from "f" to "t"

**Comment by isometriq** [comment] 2015-03-30 07:38
It works now! ..and I think I understand what's happening.

It appears that the Timesheet module require a product that will represent the services (his time) that an employee can offer to a customer. That's what the default product ID#1 "Service" is all about. The Timesheet module tries to turn "sale_ok" to "t" (true) when it installs/activates.

So deleting this default product causes the problem. Now... What I've did is create a product ..I called it "Consultation" (prefer that term ..name doesn't matter).

Then need to adjust the value in the table "ir_model_data" where the "product_product_consultant" and refers to that specific product with "res_id" equal to "1"..

Actually not sure what's the difference between "product_product" and "product_template"... only template has the "sale_ok" field though and "product_product" links to "product_template" with the "product_tmpl_id" field.

The "res_id" must be set to the "Consultation" "product_product" ID#. There was also originally an entry for "product_product_consultant_product_template", but it disappears wen deleting the "Service" product.

**Comment by isometriq** [comment] 2015-03-30 07:43
Just found out that I could have changed the "res_id" value using the Odoo Settings section:
Settings > Technical > Sequences & Identifiers > External Identifiers
Search for "product_product_consultant"

I had only one entry, so I've created one for "product_product_consultant_product_template", but maybe it was not necessary... (valuesbelow)

Module: product
External Identifier: product_product_consultant_product_template 
Model Name: product.template
Record ID: 4 

Hoping that helps

**Comment by isometriq** [comment] 2015-03-30 07:49
Now I can see why the "Service" product could be used, but not sure why it is mandatory and even worse, causing an installation failure.

Either validate before install (possible?), apply "gracefully" or do not require at all (no product update).

**Comment by isometriq** [comment] 2015-03-30 08:54
Ok, I've replicated on a live system by following these steps:
1. Creating a product with product type set to "service"
2. I've set that product as "inactive" (cause I didn't need it)
3. The product "id" represents the product_template.id... so i need to check in the database what is the product_product.id linking to it (would like to know how without peeking in the db)
4. Went to "Settings > Technical > Sequences & Identifiers > External Identifiers"
5. Modified the entry "product_product_consultant" related id for product_product.id
6. Went to "Settings > Local Modules"
7. Pressed the Timesheets module title ..on the next page pressed the "Cancel Install" button.
8. Went back in the list of modules and pressed the "Install" button.

Eh voila.. but such a pain.

**Comment by isometriq** [comment] 2015-03-30 09:02
For step #3 (above), just found out that I can get the product ID i need by checking the product variant instead. Now i understand what are product templates.

**Comment by dpelaez** [comment] 2015-03-30 15:24
What version of odoo are you using because I can't find "Settings > Technical"?

**Comment by dpelaez** [comment] 2015-03-30 16:19
Modifying the "res_id" field from "product_product_consultant" directly in the database to the id of the service product that I created worked for me. Thank you. But just out of curiosity how do you access "Settings > Technical"? I am using the build from 2 weeks ago from odoo 8.0

**Comment by isometriq** [comment] 2015-03-30 16:43
Technical is on the left sidebar, in the "Settings" section.
Your user must have the "Technical" permission checked in its profile. Edit your user as necessary.

However, I wouldn't close this issue, because even if we've found a workaround, the fact that you must keep demo data for the Timesheet module is not good. It's volatile and prone to problems.

**Comment by isometriq** [comment] 2015-03-30 16:46
In my opinion, the default user "Admin" should have the "Technical" by default... I would post an issue just because of that, but maybe it was designed on purpose?

**Comment by scperkins** [comment] 2015-04-28 12:49
Had this same issue. Thank you @isometriq for the workaround, I have no way of knowing for sure when this record was deleted in our database (we don't even use hr timesheets) and we have accumulated a lot of data, so restoring a backup or starting from scratch was not an option for me!

**Comment by jandrade42** [comment] 2015-06-16 16:46
Hello all,

I have the same issue but I can't solve it. I have the technical menu and I find the product_product_consultant external identifier, but then I don´t understand how to get the res_id field to point to the id of the service product that I just created.

I can't even find the ID of the product that I just created, can you give me a bit more info on this please?

Many thanks.

**Comment by isometriq** [comment] 2015-06-16 17:15
Hi @jandrade42,
There are 2 identifiers, "product_product_consultant" and "product_product_consultant_product_template".

First one is for product "variant" and the other is the product "template". It looks like in Odoo, all products are template and have 1 variant by default. The "res_id" in the form interface is represented by the the "Record ID" field. Changing it will affect the value to the "res_id" field in the database.

I was able to get the correct product variant id and product template id by browsing directly the the database. But I think when you get to a single product form view, the ID of the product variant id is in the URL. I don't know the exact procedure, but you can also use the developer mode to get more info about the product's IDs. To activate it, click your avatar top-right and select "About Odoo".

**Comment by jandrade42** [comment] 2015-06-16 19:27
Many thanks Daniel, so the url for the service product that I just created
is:

web#id=80&view_type=form&model=product.template&menu_id=197&action=221

Do you mean to say that I have to locate the external identifier for
"product_product_consultant", edit it, and change the record id field from
"1" to "80" as outlined in the url? or is it "197"?

Many thanks.

**Comment by isometriq** [comment] 2015-06-16 20:35
OK, I've found a procedure to get the IDs from the URL:
1. Go to the "Service" product form (this is the template)
2 .Click the "Variants" tab
3. Click the icon "List of Variants (1)" on the right
4. Click on the first item in the list (another "Service" product, the variant)
5. Then while you're in the edit form, check the URL, for example mine is:
   * /web#id=43&view_type=form&model=product.product&action=113&active_id=49
   * "product_product_consultant" is "id=" (43)
   * "product_product_consultant_product_template" is "active_id=" (49)

**Comment by isometriq** [comment] 2015-06-16 20:38
And if the identifiers don't exist, I think you have to create them (instead of edit)

**Comment by jandrade42** [comment] 2015-06-17 10:50
Many thanks, and sorry for getting confused.

I thought that I was going to change the ID on the new Service Product that
I just created, but from your instructions I got the following:

/web#id=10&view_type=form&model=product.product&action=220&active_id=80
"product_product_consultant" is "id=" (10)
"product_product_consultant_product_template" is "active_id=" (80)

What do I do with this now?

Many thanks for your support.

**Comment by jandrade42** [comment] 2015-06-17 14:20
Hi Daniel,

My cables got connected somehow. The ID of the new product service is what
I had to type in within the record of the product_product_consultant, right?

I did so and the Time Tracking module got installed. Many thanks for the
great help.

After having done this it is quite stressful to know that I can break Odoo
in such an easy manner, the system should have told me not to delete the
Product called Service, it should have an alert of something to say
something like "This Record is a System Record and can't be deleted".

Is there some sort of App to improve the system admin capabilities of Odoo?

Many thanks.

**Comment by isometriq** [comment] 2015-06-17 14:36
Great, glad you've been able to fix it too.
I'm not aware of such module. I agree that Odoo seems to be fragile. I hope they consider this issue and fix that by eliminating such dependencies.

**Comment by keskifo** [comment] 2015-12-09 14:44
Hello,

Just ran through the same problem and I'm not able to fix the issue even with the procedure above...

Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/web/controllers/main.py", line 940, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/modules/registry.py", line 368, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/modules/loading.py", line 176, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/tools/convert.py", line 901, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/tools/convert.py", line 987, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/tools/convert.py", line 853, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/tools/convert.py", line 763, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/base/ir/ir_model.py", line 1077, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/hr_holidays/hr_holidays.py", line 493, in create
    return super(hr_employee, self).create(cr, uid, vals, context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/hr/hr.py", line 284, in create
    employee_id = super(hr_employee, self).create(cr, uid, data, context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/mail/mail_thread.py", line 384, in create
    thread_id = super(mail_thread, self).create(cr, uid, values, context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 336, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/models.py", line 4059, in create
    record = self.browse(self._create(old_vals))
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/models.py", line 4115, in _create
    record_id = self.pool[table].create(cr, user, tocreate[table], context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 336, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/models.py", line 4059, in create
    record = self.browse(self._create(old_vals))
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/models.py", line 4197, in _create
    tuple([u[2] for u in updates if len(u) > 2])
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ParseError: "null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (22, 1, 1, null, null, null, 1, 1, 2015-12-09 14:41:42.95542, null, t, 2015-12-09 14:41:42.95542, user).
" while parsing /opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/hr_timesheet/hr_timesheet_data.xml:11, near
<record id="hr.employee" model="hr.employee">
            <field name="journal_id" ref="analytic_journal"/>
        </record>

**Comment by isometriq** [comment] 2015-12-10 07:08
Can you provide more detail?
Where and how that trace stack was generated?

**Comment by keskifo** [comment] 2015-12-10 07:44
This happens every time I'd like to change an option from the "Settings -> Sales". As an example, I wanted to enable "Contracts management" or another option from the "Sales"

**Comment by keskifo** [comment] 2015-12-10 16:38
in fact, this happens every time, I'd like to install a module also. Quite annoying!

**Comment by isometriq** [comment] 2015-12-10 17:39
I'm not sure why, but maybe you can try going in the HumanResources section and set a product (of Service type) for all the personel you have. This fixed a problem similar to yours a while ago.

**Comment by elsguns** [comment] 2016-05-13 12:22
Thank you so much for your explanation. Encountered the issue too and had it fixed right away! :-)

**Comment by sathwiksunderreddy** [comment] 2016-09-30 15:39
Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-11/openerp/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/saas-11/openerp/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/saas-11/openerp/http.py", line 321, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-11/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-11/openerp/http.py", line 314, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/saas-11/openerp/http.py", line 966, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/saas-11/openerp/http.py", line 516, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/saas-11/addons/web/controllers/main.py", line 876, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/saas-11/addons/web/controllers/main.py", line 868, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-11/openerp/api.py", line 254, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-11/openerp/addons/base/module/module.py", line 458, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/home/odoo/src/odoo/saas-11/openerp/api.py", line 254, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/src/custom/trial/saas_trial/module.py", line 86, in _button_immediate_function
    res = super(ir_module_module, self)._button_immediate_function(cr, uid, ids, function, context=context)
  File "/home/odoo/src/odoo/saas-11/openerp/api.py", line 254, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-11/openerp/addons/base/module/module.py", line 532, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/home/odoo/src/odoo/saas-11/openerp/modules/registry.py", line 402, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/saas-11/openerp/modules/loading.py", line 340, in load_modules
    loaded_modules, update_module)
  File "/home/odoo/src/odoo/saas-11/openerp/modules/loading.py", line 239, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/odoo/src/odoo/saas-11/openerp/modules/loading.py", line 158, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/odoo/src/odoo/saas-11/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/odoo/src/odoo/saas-11/openerp/tools/convert.py", line 867, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/odoo/src/odoo/saas-11/openerp/tools/convert.py", line 950, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/odoo/src/odoo/saas-11/openerp/tools/convert.py", line 820, in parse
    self._tags[rec.tag](self.cr, rec, de, mode=mode)
  File "/home/odoo/src/odoo/saas-11/openerp/tools/convert.py", line 723, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/home/odoo/src/odoo/saas-11/openerp/api.py", line 254, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-11/openerp/api.py", line 358, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-11/openerp/addons/base/ir/ir_model.py", line 1074, in _update
    record = record.create(values)
  File "/home/odoo/src/odoo/saas-11/openerp/api.py", line 252, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-11/openerp/api.py", line 552, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/home/odoo/src/custom/trial/saas_trial/res_users.py", line 89, in create
    res = super(res_users, self).create(cr, uid, values, context=context)
  File "/home/odoo/src/odoo/saas-11/openerp/api.py", line 254, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-11/openerp/api.py", line 358, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-11/addons/auth_signup/models/res_users.py", line 141, in create
    user = super(ResUsers, self).create(values)
  File "/home/odoo/src/odoo/saas-11/openerp/api.py", line 252, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-11/addons/mail/models/res_users.py", line 50, in create
    raise openerp.exceptions.RedirectWarning(msg, action.id, _('Go to the configuration panel'))
ParseError: "You cannot create a new user from here.
 To create new user please go to configuration panel.
71
Go to the configuration panel" while parsing /home/odoo/src/odoo/saas-11/addons/hr/security/hr_security.xml:23, near
<record id="base.default_user" model="res.users">
        <field name="groups_id" eval="[(4,ref('base.group_hr_manager'))]"/>
    </record>




When iam trying to install TIme sheets it shows this error 

I am new to Odoo I need a payroll module it is poping up same issue tried to check product_product_consultant in Technical options but i didnt found that any where please guide me 

Thanks in Advance

**Comment by sathwiksunderreddy** [comment] 2016-09-30 15:46
Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-11/openerp/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/saas-11/openerp/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/saas-11/openerp/http.py", line 321, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-11/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-11/openerp/http.py", line 314, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/saas-11/openerp/http.py", line 966, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/saas-11/openerp/http.py", line 516, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/saas-11/addons/web/controllers/main.py", line 876, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/saas-11/addons/web/controllers/main.py", line 868, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-11/openerp/api.py", line 254, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-11/openerp/addons/base/module/module.py", line 458, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/home/odoo/src/odoo/saas-11/openerp/api.py", line 254, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/src/custom/trial/saas_trial/module.py", line 86, in _button_immediate_function
    res = super(ir_module_module, self)._button_immediate_function(cr, uid, ids, function, context=context)
  File "/home/odoo/src/odoo/saas-11/openerp/api.py", line 254, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-11/openerp/addons/base/module/module.py", line 532, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/home/odoo/src/odoo/saas-11/openerp/modules/registry.py", line 402, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/saas-11/openerp/modules/loading.py", line 340, in load_modules
    loaded_modules, update_module)
  File "/home/odoo/src/odoo/saas-11/openerp/modules/loading.py", line 239, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/odoo/src/odoo/saas-11/openerp/modules/loading.py", line 158, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/odoo/src/odoo/saas-11/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/odoo/src/odoo/saas-11/openerp/tools/convert.py", line 867, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/odoo/src/odoo/saas-11/openerp/tools/convert.py", line 950, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/odoo/src/odoo/saas-11/openerp/tools/convert.py", line 820, in parse
    self._tags[rec.tag](self.cr, rec, de, mode=mode)
  File "/home/odoo/src/odoo/saas-11/openerp/tools/convert.py", line 723, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/home/odoo/src/odoo/saas-11/openerp/api.py", line 254, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-11/openerp/api.py", line 358, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-11/openerp/addons/base/ir/ir_model.py", line 1074, in _update
    record = record.create(values)
  File "/home/odoo/src/odoo/saas-11/openerp/api.py", line 252, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-11/openerp/api.py", line 552, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/home/odoo/src/custom/trial/saas_trial/res_users.py", line 89, in create
    res = super(res_users, self).create(cr, uid, values, context=context)
  File "/home/odoo/src/odoo/saas-11/openerp/api.py", line 254, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-11/openerp/api.py", line 358, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-11/addons/auth_signup/models/res_users.py", line 141, in create
    user = super(ResUsers, self).create(values)
  File "/home/odoo/src/odoo/saas-11/openerp/api.py", line 252, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-11/addons/mail/models/res_users.py", line 50, in create
    raise openerp.exceptions.RedirectWarning(msg, action.id, _('Go to the configuration panel'))
ParseError: "You cannot create a new user from here.
 To create new user please go to configuration panel.
71
Go to the configuration panel" while parsing /home/odoo/src/odoo/saas-11/addons/hr/security/hr_security.xml:23, near
<record id="base.default_user" model="res.users">
        <field name="groups_id" eval="[(4,ref('base.group_hr_manager'))]"/>
    </record>

Please help me I have checked product_product_consultant in Technical option didnt found it I am new to ODOO please help 

Thanks in advance #@isometriq

**Comment by isometriq** [comment] 2016-10-11 02:54
It's been a while now, but if I recall, you can create the key if it does not exists. Check my previous posts and I think you will be able to succeed. Maybe you're not using the same version that was used when I've resolved it.

**Comment by Yenthe666** [comment] 2017-12-12 15:45
Hi @dpelaez,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Closed by Yenthe666** 2017-12-12 15:45 UTC
