### ISSUE TITLE
Odoo 9 Accountant Access right not providing Accounting Module Access

### ISSUE THREAD

**Issue by iksweliwita** [odoo/odoo#13484] opened 2016-09-15 05:59 UTC
Impacted versions: Odoo 9

Steps to reproduce: Create a new user with the access right Accountant for the Accounting & Finance application. I don't want the user to have admin rights so I left the Administration blank. Login as the newly created user and click on the Accounting App. 

Current behavior: Error message is shown 
_Odoo Warning - Access Error_
_Sorry, you are not allowed to access this document. Only users with the following access level are currently allowed to do that:_
_Administration/Settings_
_(Document model: ir.cron)_

Expected behavior: Full access to the accounting app ONLY should be given WITHOUT ADMIN access

Video/Screenshot link (optional):

**Comment by JKE-be** [comment] 2016-09-15 09:40
Hello
We need more info to help you.

Can you reproduce it on Runbot ? 
Could you provide the traceback  ? Because the error seems to be unrelated to the accounting.

**Comment by iksweliwita** [comment] 2016-09-27 13:31
I am sorry but I am new to Odoo and I am not aware on how to get the runbot running. However, I agree to what you said. It seems that the issue is occurring with some configure issue.

**Comment by JKE-be** [comment] 2016-09-27 14:09
Maybe a un-standard module that you have installed that try to launch one ? 

Are you sure that it happend everytime that you click on the accounting menu ? 
Or it is another thing that oculd trigger it...

**Comment by Yenthe666** [comment] 2018-02-12 10:30
Closing as it is working fine in the default Odoo (as confirmed by the creator too) and since there has been no feedback in ages.

**Closed** 2018-02-12 10:30 UTC

**Comment by mehmoodhussain94** [comment] 2018-02-13 08:16
I have facing similar issue in purchase module .While user who didn't have access right are unable to create vendor bill 
Version = 10.0
![image](https://user-images.githubusercontent.com/36437843/36139584-edefd5ec-10bf-11e8-8d43-f73d80024d35.png)
