### ISSUE TITLE
CORS issue while using live chat as external widget

### ISSUE THREAD

**Issue by gokhandilek** [odoo/odoo#62931] opened 2020-12-06 04:05 UTC
Impacted versions:Live chat 13.0.1.0

Steps to reproduce: copy the the tag to an external site.

Current behavior: chat widget is not visible.
When opening console, it has Access to XMLHTTPREQUEST at 'myodoosite1234.com' from origin 'external site' has been blocked by CORS policy. Request header field content type is not allowed by Access control allow headers in preflight response.

If I visit the direct link, myodoosite1234.com/im_livechat/support/5 
It works without any issue.
Expected behavior: chat should be visible on an external side.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2020-12-06 09:49
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by gokhandilek** [comment] 2020-12-06 11:00
I copied and pasted he widget code to the external site..
This is what I am getting.

![16072520793245964143669995271950](https://user-images.githubusercontent.com/10161605/101278157-88b45680-37f4-11eb-91ff-a4df603ebfac.jpg)


The live chat page works without any issue which is exactly what I am experiencing.

I also saved the live chat page as HTML file and this is what I am getting:

![16072522924859206100581910079858](https://user-images.githubusercontent.com/10161605/101278235-11cb8d80-37f5-11eb-881b-2d3b3bd7c03d.jpg)

**Comment by pedrobaeza** [comment] 2020-12-06 11:03
OK, tagging

**Comment by gokhandilek** [comment] 2020-12-08 10:55
I created a trial account using the https://www.odoo.com/trial site.
It worked perfectly fine.
So not sure what the problem is still.
I checked the controller/main.py to make sure the was cors='*'.

**Comment by pumppi** [comment] 2021-01-18 11:12
I added comment to this commit message: https://github.com/odoo/odoo/commit/9e27956aa960dc9eea442418c83f5b3941b0c447

I had little bit issues implementing rest. Might be issue with headers check in preflight check. If you have some external headers what are not allowed.

**Comment by seb-odoo** [comment] 2021-04-02 16:43
I don't think this URL on runbot is correct because the user would need to visit the page first to select the DB.

Correct URL for sharing runbot links should have the db name on it (in this example `-all`), such as https://7007153-13-0-all.runbot59.odoo.com/

I think the change was made somewhat recently that the `-all` db is the one by default in the URL, instead of the non-db URL.

If you have a reverse proxy in the way make sure to configure it properly.
And if you are on the saas feel free to open a ticket if the issue keeps happening.

I just put this on a random html page on my computer and it is working fine:
```
            <link rel="stylesheet" href="https://7007153-13-0-all.runbot59.odoo.com/im_livechat/external_lib.css"/>
            <script type="text/javascript" src="https://7007153-13-0-all.runbot59.odoo.com/im_livechat/external_lib.js"></script>
            <script type="text/javascript" src="https://7007153-13-0-all.runbot59.odoo.com/im_livechat/loader/1"></script>
```

**Comment by seb-odoo** [comment] 2021-06-04 09:45
Considering this resolved as no response since my last message.

**Closed by seb-odoo** 2021-06-04 09:45 UTC
Labels: 13.0, Discuss
