### ISSUE TITLE
created_production_id value missing on procurement_group

### ISSUE THREAD

**Issue by silverdaletech-zubair** [odoo/odoo#74370] opened 2021-07-28 14:27 UTC
**Impacted versions:**
14C and 14E

**Steps to reproduce:**
Enable Multi-Step Routing on Warehouse
Enable MTO + Manufacture on Product
Create SO
The MOs get created but do not get linked to Stock Moves within the SO Procurement Group so the Smart Button on SO doesn't show them connected

**Current behavior:**
The created_production_id is not attached to SO Procurement Group Stock Moves and SO doesn't show the MO Count

**Expected behavior:**
The created_production_id is attached to SO Procurement Group Stock Moves and SO does show the MO Count

**Video/Screenshot link (optional):**

**Support ticket number submitted via odoo.com/help (optional):**
2613518

**Comment by silverdaletech-zubair** [comment] 2021-07-31 08:11
Hello @Yenthe666 @pedrobaeza any insights?

**Comment by pedrobaeza** [comment] 2021-07-31 08:29
As you have filled an OPW ticket, Odoo support will contact you.

**Comment by silverdaletech-zubair** [comment] 2021-07-31 08:31
Yeah but the turn around time is probably the worst. Keeping my fingers crossed for getting a quick response.

**Comment by pedrobaeza** [comment] 2021-07-31 08:33
We both don't "solve" issues, just classify them for Odoo team. Sometimes, we can give the hint or directly know that is not a bug, closing them, but it's not the case.

**Comment by vava-odoo** [comment] 2023-04-06 21:22
Fixed with https://github.com/odoo/odoo/pull/79015

**Closed by vava-odoo** 2023-04-06 21:22 UTC
Labels: OE, Logistics, 14.0
