### ISSUE TITLE
[9.0CE]Forum Text Editor: default preset for paragraph layout: centered instead of left

### ISSUE THREAD

**Issue by treviser** [odoo/odoo#12646] opened 2016-06-30 14:56 UTC
Impacted versions: 9.0 CE, nightly build 2016-06-29

Steps to reproduce:

Enter a new question or an answer in the editor.

Current behavior:

The default paragraph layout is centered. This makes no sense and is annoying.

Expected behavior:

The default paragraph layout should be left adjusted.

Video/Screenshot link (optional):

**Comment by JKE-be** [comment] 2016-07-22 15:24
Hi @treviser,
Still existing problem ? 
I cannot reproduce it...

**Comment by treviser** [comment] 2016-07-23 07:52
I did check it, it is obviously theme-related, I can reproduce it for the theme KEA for example, but not for the default bootstrap theme.

**Comment by JKE-be** [comment] 2016-07-25 09:44
Ok, it is a problem of css in theme.
@qsm-odoo  will take a look to fix it.

Meanwhile, you can always override the style with smthg like: 
`note-editor.panel {     text-align: initial; }`

**Comment by treviser** [comment] 2016-07-25 12:32
Thanks!

**Comment by qsm-odoo** [comment] 2016-07-26 09:08
Hello, the problem has been fixed with commit https://github.com/odoo/design-themes/commit/81391002508ce8ce2df66da942db098ac670988d, following @JKE-be suggestion.

**Closed by qsm-odoo** 2016-07-26 09:08 UTC
