### ISSUE TITLE
Failed to render email template in odoo 11 community

### ISSUE THREAD

**Issue by 12cedrych** [odoo/odoo#34081] opened 2019-06-12 15:28 UTC
Impacted versions:
Odoo 11 Community Version/Hotel Management app
Steps to reproduce:
I want to send email reservation but it is failing  due to an error described as failed to render template. I am new to odoo plz help me
Current behavior:
Whenever i send a reservation email the below error occurs
Expected behavior:
I want thatthe email gets sent and that when i check the receiver inbox I get to see the sent email
![Scrnshot](https://user-images.githubusercontent.com/48095501/59364444-241b5700-8d37-11e9-82e9-2134d3250ba6.JPG)
 
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2019-06-12 15:33
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

Hint: You probably have wrong translations or the mail template modified.

**Comment by sswapnesh** [comment] 2019-06-12 16:49
or Maybe better to report it to https://github.com/OCA/vertical-hotel/issues/new with Proper steps

**Comment by pedrobaeza** [comment] 2019-06-12 16:50
Oh, I didn't see that... closing as unrelated to this repository

**Closed by pedrobaeza** 2019-06-12 16:50 UTC
Labels: Need information

**Comment by 12cedrych** [comment] 2019-06-13 08:18
@pedrobaeza hello I am not used to runbot so I started the whole process in a new DB and that error didn't come again. Hhhhh....the problem was solved but in a way I can't explain
