### ISSUE TITLE
First successful login from LDAP authenticated account causes internal server error

### ISSUE THREAD

**Issue by uncle-zipper** [odoo/odoo#9114] opened 2015-10-16 22:06 UTC
Successful authentication of a user not in Odoo's database through LDAP causes 500 error. Incorrect password does not result in this error. Refreshing the page reveals the user is logged in and no further errors occur. Screenshots and relevant portion of the log file are attached below.

Username and password fields filled in.
![2015-10-16 17_46_45-login _ localhost](https://cloud.githubusercontent.com/assets/15164487/10554241/c14a4d58-742f-11e5-8fc9-2252ba563720.png)

Upon logging in, an error occurs.
![2015-10-16 17_47_11-internal server error](https://cloud.githubusercontent.com/assets/15164487/10554242/c14b4f00-742f-11e5-8091-f2a82a37e341.png)

Refreshing the page from the previous screenshot yields the expected landing page.
![2015-10-16 17_47_33-inbox - odoo](https://cloud.githubusercontent.com/assets/15164487/10554243/c14bab76-742f-11e5-9efd-39282537be9d.png)

```
2015-10-16 21:44:26,251 2187 ERROR tekno openerp.addons.website.models.ir_http: 500 Internal Server Error:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/addons/website/models/ir_http.py", line 199, in _handle_exception
    response = super(ir_http, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_http.py", line 147, in _handle_exception
    return request._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 666, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_http.py", line 173, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 684, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/auth_oauth/controllers/main.py", line 94, in web_login
    response = super(OAuthLogin, self).web_login(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/auth_signup/controllers/main.py", line 38, in web_login
    response = super(AuthSignupHome, self).web_login(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/website/controllers/main.py", line 52, in web_login
    return super(Website, self).web_login(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 509, in web_login
    uid = request.session.authenticate(request.session.db, request.params['login'], request.params['password'])
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 966, in authenticate
    if uid: self.get_context()
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1001, in get_context
    self.context = request.registry.get('res.users').context_get(request.cr, request.uid) or {}
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/res/res_users.py", line 402, in context_get
    return self._context_get(cr, uid)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in _context_get
  File "/usr/lib/python2.7/dist-packages/openerp/tools/cache.py", line 74, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/res/res_users.py", line 395, in _context_get
    res = getattr(user, k) or False
  File "/usr/lib/python2.7/dist-packages/openerp/fields.py", line 823, in __get__
    return record._cache[self]
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 5931, in __getitem__
    return value.get() if isinstance(value, SpecialValue) else value
  File "/usr/lib/python2.7/dist-packages/openerp/fields.py", line 55, in get
    raise self.exception
MissingError: ('MissingError', u'One of the documents you are trying to access has been deleted, please try again after refreshing.')

2015-10-16 21:44:26,267 2187 INFO tekno werkzeug: 10.8.0.6 - - [16/Oct/2015 21:44:26] "POST /web/login HTTP/1.1" 500 -
2015-10-16 21:44:48,461 2187 INFO tekno werkzeug: 10.8.0.6 - - [16/Oct/2015 21:44:48] "POST /web/login HTTP/1.1" 200 -
2015-10-16 21:44:49,313 2187 INFO tekno werkzeug: 10.8.0.6 - - [16/Oct/2015 21:44:49] "GET /web? HTTP/1.1" 200 -
2015-10-16 21:44:49,778 2187 INFO tekno openerp.service.common: successful login from 'test' using database 'tekno'
```

**Comment by williamgutierres** [comment] 2015-10-24 02:41
Hi there,

I'm facing the same issue. Please update this thread if you find something. Thanks.

**Comment by naglis** [comment] 2016-04-13 09:00
Might be a duplicate of #7785.

**Comment by grv333** [comment] 2016-12-26 12:43
try edit _context_get function in /openerp/addons/base/res/res_users.py
In my case error was in string.  
`res = getattr(user, k) or False`

I add try - except and it's work fine for my. My function after edit:
`    @tools.ormcache(skiparg=2)
    def _context_get(self, cr, uid):
        user = self.browse(cr, SUPERUSER_ID, uid)
        result = {}
        for k in self._fields:
            if k.startswith('context_'):
                context_key = k[8:]
            elif k in ['lang', 'tz']:
                context_key = k
            else:
                context_key = False
            if context_key:
                try:
                        res = getattr(user, k) or False
                except Exception as e:
                        res = False
                if isinstance(res, models.BaseModel):
                    res = res.id
                result[context_key] = res or False
        if res == False:
                result = {'lang': u'ru_RU', 'tz': False}
        return result`

**Comment by pedrobaeza** [comment] 2018-04-06 00:48
It seems so that it's something similar to the other mentioned issue. If this is still reproducible in latest version, please feel free to open a new issue or a PR with the proposed code that fixes the problem.

**Closed by pedrobaeza** 2018-04-06 00:48 UTC
