### ISSUE TITLE
function is not a constructor (evaluating 'super()') in Safari 13.1.2

### ISSUE THREAD

**Issue by estekadigital** [odoo/odoo#71518] opened 2021-05-31 20:19 UTC
Impacted versions:
14.0 community
Steps to reproduce:
With Safari 13.1.2 Just get into Settings > Users > User
Current behavior:
Following message pops up: 
```
Error: function is not a constructor (evaluating 'super()')
OdooEditor@https://example.com/web/assets/143-f40727c/web_editor.assets_wysiwyg.min.js:701:76
https://example.com/web/assets/143-f40727c/web_editor.assets_wysiwyg.min.js:1487:2299
asyncFunctionResume@[native code]
[native code]
promiseReactionJobWithoutPromise@[native code]
promiseReactionJob@[native code]
```

Expected behavior:
No error should appear

Video/Screenshot link (optional):
It also happens in odoo.com forum:

![Captura de pantalla 2021-05-31 a las 22 17 58](https://user-images.githubusercontent.com/52083572/120239240-19c53100-c25e-11eb-90c1-c4e40a9e72c8.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by estekadigital** [comment] 2021-05-31 20:22
May it have something to do with virtual-scroller? https://github.com/WICG/virtual-scroller/issues/124

**Comment by pedrobaeza** [comment] 2021-05-31 21:07
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by estekadigital** [comment] 2021-05-31 21:29
Yes it does happen in master (not in 14.0)

![Captura de pantalla 2021-05-31 a las 23 24 35](https://user-images.githubusercontent.com/52083572/120243472-f7381580-c267-11eb-9dca-e384d146d3ff.png)

**Comment by pedrobaeza** [comment] 2021-05-31 21:30
master is a development brach, so that one is not expected to fully work. Closing meanwhile you are not able to reproduce it in runbot in 14.0 branch.

**Closed by pedrobaeza** 2021-05-31 21:30 UTC
Labels: Need information
