### ISSUE TITLE
[11.0] Original subject line always persisted in mass email

### ISSUE THREAD

**Issue by jorunn** [odoo/odoo#23280] opened 2018-02-23 09:09 UTC
Impacted versions:
Tested with 11.0 Enterprise

Steps to reproduce:
1. Create a mass email message with a given set of recipient criteria.
2. Copy this message to retain the same criteria. Change subject line and contents.
3. Send test message and see that everything looks right.
4. Send to all recipients.

Current behavior:
5. Email is sent with updated contents, but the subject line of the original message (which is no longer visible anywhere else in the Odoo interface).

Expected behavior:
5. Email is sent with updated contents and updated subject line.

Video/Screenshot link (optional):

**Comment by jorunn** [comment] 2018-03-12 12:43
Update: It looks like Odoo is always using whichever subject line was first saved for a mass email campaign. Changing it updates it in the Odoo interface and the test message, but when sending to everyone, the original/draft subject line is used.

This bug is really ugly and makes the mass email feature hard to use in a predictable and meaningful way ...

**Comment by baba75** [comment] 2018-05-23 13:56
Hope you will fix for version 10.0 also.

**Comment by jorunn** [comment] 2018-05-25 09:11
Yes, I found the same solution and had forgotten to update the report. Am I able to invalidate it myself? Doesn't look that way. (I won't claim the way these translations are handled is elegant at all; it's incredibly confusing, but that's a usability issue, not a data persistance bug, so this one is clearly invalid.)

**Comment by pedrobaeza** [comment] 2018-05-26 14:36
Indeed, this is not a bug itself, but a misunderstanding on how translations work. This can be improved indeed, as there's not too much sense to have a translatable subject if there's no multi-language on mass mailing sending.

Closing this as no issue, but noted for giving feedback on this.

**Closed by pedrobaeza** 2018-05-26 14:36 UTC
Labels: 11.0, Services
