### ISSUE TITLE
[12] Issue with One2Many

### ISSUE THREAD

**Issue by dungxboss** [odoo/odoo#27601] opened 2018-10-10 01:20 UTC
Impacted versions: 12

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/40818338/46707702-4ec38600-cc65-11e8-8763-2eab9a48aafc.png)

**Comment by Yenthe666** [comment] 2018-10-10 06:08
Hi @dhamedic,

I see you've made some custom development.
Can you reproduce the same on some official code/view? I don't seem to get/see it elsewhere. Please also add more information: which browser, which version of the browser, how to reproduce, ..

**Comment by dhamedic** [comment] 2018-10-10 06:47
The "delete" button has white space around it.
When I checked in the box, the button "Many2one" is behind, this is mainly about the interface.

**Comment by pedrobaeza** [comment] 2018-10-10 08:40
@Yenthe666 I can confirm this is happening also on v11. It's not something about custom development, but how many2one fields inside a one2many tree behaves.

**Comment by Yenthe666** [comment] 2018-10-10 09:03
Not sure what to label it with or who is responsible though. Do you? I guess it is a small community quirk.

**Comment by pedrobaeza** [comment] 2018-10-10 09:05
This is something about CSS/HTML layout, so I guess it can be @qsm-odoo

**Comment by qsm-odoo** [comment] 2018-10-10 09:31
Framework team should always have a look first at that kind of backend issue :) @ged-odoo ? :)

**Comment by C3POdoo** [comment] 2023-03-30 11:56
Dear @dungxboss,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._

**Closed by C3POdoo** 2023-03-30 11:56 UTC
Labels: 12.0
