### ISSUE TITLE
Fiscal position not applying when customer is created from website

### ISSUE THREAD

**Issue by mohdshoaib04** [odoo/odoo#32899] opened 2019-04-24 08:35 UTC
Impacted versions:
Odoo V11 community
Steps to reproduce:
1.) Add products to cart, do not signup the customer and proceed for order checkout.
2.) When we see the sale order > customer > There is no fiscal position set. This should be set automatically.
Current behavior:
Fiscal position not getting set when customer is created from website.
Expected behavior:
Fiscal position must be auto selected.
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2019-04-24 22:47
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos. Specifically, which country rules have you applied.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Closed** 2019-06-05 09:11 UTC
Labels: 11.0, Website
