### ISSUE TITLE
Serialize error, regeneration of assets css

### ISSUE THREAD

**Issue by matmicro** [odoo/odoo#41685] opened 2019-12-11 07:56 UTC
Impacted versions: 10, 11

Steps to reproduce:

Current behavior:
I can see a lot of issues likes the below error message. This occurs very often per second. My odoo then looks slow, i presume this comes from this.

Logs:
2019-12-11 07:04:56 UTC [5939-18] odoo@prod STATEMENT:  DELETE FROM ir_attachment WHERE id IN (346787, 346786)
2019-12-11 07:05:30 UTC [5811-17] odoo@prod ERROR:  could not serialize access due to concurrent update
2019-12-11 07:05:30 UTC [5811-18] odoo@prod STATEMENT:  DELETE FROM ir_attachment WHERE id IN (346797, 346796)
2019-12-11 07:06:08 UTC [5893-11] odoo@prod ERROR:  could not serialize access due to concurrent update

I am using filestore db-storage, i presume this is because of this. 
All the times, the concerned files are the regeneration of assets css. Any way to avoid this occur so often ?

Regards

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2019-12-11 08:20
I don't think it's due to the db-storage, but multiple simultaneous concurrent writes (assets are not written several times). Any way, there's not too much sense to write that to the DB, and the problem is in your deployment configuration, as this is not reproducible in other end, so closing meanwhile you don't give hints that suggest that this is an Odoo problem.

**Closed by pedrobaeza** 2019-12-11 08:20 UTC

**Comment by matmicro** [comment] 2019-12-11 09:31
Hi Pedro,

Then why thoses 3 files are always behing updated ?
 349127 | /web/content/349127-0e78996/web.assets_frontend.0.css
 349128 | /web/content/349128-0e78996/web.assets_frontend.1.css
 349129 | /web/content/349129-0e78996/web.assets_frontend.js

Then how to you advise to manage filestore on a cluster of Odoo server instances, to get common filestore, if not storing into DB.  NFS shared folder ?

Which kind of deployment configuration could generate that issue ?

Thanks and regards

**Comment by pedrobaeza** [comment] 2019-12-11 09:39
Yes, a shared filestore is better solution. That files are being regenerated constantly due to your cluster configuration. That doesn't happen normally. But it's out of this issue tracker more explanations about cluster configuration and so on.

**Comment by matmicro** [comment] 2019-12-12 06:44
Could you please let me know in which file of odoo, or function, that invalidate/regenerate the assets frontend ?
Then i can investigate by myself.

Thanks and regards

**Comment by pedrobaeza** [comment] 2019-12-12 08:37
I can't say, but you can look for the invalidation message for finding it in the source code.
