### ISSUE TITLE
default_ values aren't taken into account in one2many relation fields.

### ISSUE THREAD

**Issue by llacroix** [odoo/odoo#71782] opened 2021-06-05 00:05 UTC
Impacted versions:
14.0

Steps to reproduce:
For example in a sale.order add the order_id to the tree view of the sale.order.line 
on the order_line field set the default_order_id to id
add a new line on the sale.order

Current behavior:
order_id remains empty.
Odoo calls onchange with the proper order_id defined but will return in the values of the onchange

order_id: false.

If order_id is defined in the tree view, it will also return from the onchange as false value despite being sent to odoo.
In an onchange call, the id of the order_id is properly set to NewId(origin=id) but the onchange sets it back to false.

If we do update the field manually to 

    self.order_id = self.order_id.origin

The onchange will properly define the value. 

When using the value of order_id in a domain, it will be incorrectly set to false so if you would use the value of the inverse of the one2many field in a domain in one of the one2many records, it will always be false unless you first save the records and then edit it.

Expected behavior:

The inverse field should be properly set even if it's not passed as default_ value and onchange shouldn't return order_id: false.
All of this should be working even before saving the records that would eventually populate the ids to disk.

Other:

I imagine this issue is caused because Odoo doesn't trigger the onchange because it consider the NewId to be equal to the value being created... so it doesn't even try to return it. I'm guessing that since it's the inverse reference, it also doesn't attempt to set the value in the record because it expect it to be saved by the parent record using (0, values) which would automatically set the back reference.

The problem is mainly that until the record is saved, it's not possible to use the field in domains or to populate other sub records. It will be set to false.

**Comment by pedrobaeza** [comment] 2021-06-05 07:19
The problem is that you are trying to do your stuff with the `inverse_name` field of the one2many, and that field is treated in a special way on the one2many widget. You mustn't include that field in the one2many view, or things won't work correctly.

If you want to do domains in the JS side, use `parent.parent_field` in the view.

Closing as no bug, but limitation on that specific field.

**Closed by pedrobaeza** 2021-06-05 07:19 UTC

**Comment by llacroix** [comment] 2021-06-07 14:44
@pedrobaeza parent.parent_field won't work when parent.parent_field is itself the inverse_name.

**Comment by llacroix** [comment] 2021-06-07 22:32
> Closing as no bug, but limitation on that specific field.

With that kind of definition anything that doesn't work isn't a bug it's a limitation. 

But in my book if the top view's id is the report_id of the sub view.. Then the subview of the subview that use the report_id of its parent view should have the same value as the top view's id. But due to the bug, it gets set to false by the onchange and then due to something else, the frontend ends up with 2 states where the value is either False or the Record. 

But if we actually send the id back, we can ensure ourselves to not end up with two different states!

I mean, I know it's possible because I fixed it... or removed the limitation. 

https://github.com/odoo/odoo/pull/71835

**Comment by pedrobaeza** [comment] 2021-06-07 22:57
OK, let's hope Odoo considers that, but you should know that this is only taken into consideration for master branch, not for current stable branches, where the risk of introducing a problem is high.

**Comment by llacroix** [comment] 2021-06-08 00:27
ok then I'll make the PR against master
