### ISSUE TITLE
Wrong grouped totals

### ISSUE THREAD

**Issue by Tardo** [odoo/odoo#47950] opened 2020-03-18 17:55 UTC
Impacted versions:
Only tested on 12.0 and 13.0

Steps to reproduce:
![wrong_total](https://user-images.githubusercontent.com/731270/76991352-bea16a00-6949-11ea-8cb3-f25a7d74f725.gif)

  - Domain used: `[["order_line.product_uom","ilike","dozen"]]`
  - Model: sale.order

Current behavior:
Grouped totals doesn't shows correct values. This appears to be a problem with "_read_group_raw" function and how constructs the query.

Expected behavior:
Show the correct values in grouped totals

**Comment by Tardo** [comment] 2020-03-18 17:55
cc @tecnativa

**Comment by pedrobaeza** [comment] 2020-03-18 18:00
Please put in plain text the used domain.

@xmo-odoo not sure if this is for your or for @rco-odoo

**Comment by xmo-odoo** [comment] 2020-03-24 10:21
@Tardo sadly this is a known issue with auto_join fields and while there have been efforts to fix / deprecate / ... them (e.g. odoo/odoo#25182) these efforts have... not borne fruit so far.

I'll close this issue but it's not because the issue is fixed, unknown or considered fine, but rather because it's a known issue and assuming we eventually manage to fix it, it's unlikely we'll remember to come back and mark it as fixed (it's also unlikely the fix will be backported, though I guess that's still a possibility).

**Closed** 2020-03-24 10:33 UTC

**Comment by MarinkaPapeleuDoria** [comment] 2020-05-28 14:19
I downloaded the advanced search module for V13 and released it on my Odoo.sh database. When I install it , it works fine, however I get the following error with the regular 'Add Custom Filter':

Error:


Traceback:
TypeError: Cannot read property 'model' of undefined
    at Class.init (https://marinkapapeleudoria-simlab-staging-26-05-1133685.dev.odoo.com/web/content/4564-c9398dc/web.assets_backend.js:4506:2619)
    at Class.prototype.<computed> [as init] (https://marinkapapeleudoria-simlab-staging-26-05-1133685.dev.odoo.com/web/content/3647-447a04f/web.assets_common.js:3861:488)
    at new Class (https://marinkapapeleudoria-simlab-staging-26-05-1133685.dev.odoo.com/web/content/3647-447a04f/web.assets_common.js:3862:65)
    at Class.select_field (https://marinkapapeleudoria-simlab-staging-26-05-1133685.dev.odoo.com/web/content/4564-c9398dc/web.assets_backend.js:1596:88)
    at Class.changed (https://marinkapapeleudoria-simlab-staging-26-05-1133685.dev.odoo.com/web/content/4564-c9398dc/web.assets_backend.js:1594:1377)
    at https://marinkapapeleudoria-simlab-staging-26-05-1133685.dev.odoo.com/web/content/3647-447a04f/web.assets_common.js:3945:11

Can this be fixed?
