### ISSUE TITLE
message_track

### ISSUE THREAD

**Issue by YuraPotapov** [odoo/odoo#41528] opened 2019-12-09 09:59 UTC
Impacted versions: 13.0

Steps to reproduce: call message_track, for example call  message_subscribe() for send email.

line was removed where gets model object , after that calls method "exists" from str object(should be model obj)

calling str obj "if not subtype.exists():"  instead of the model obj

**Comment by pedrobaeza** [comment] 2019-12-09 10:03
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2019-12-09 10:03 UTC

**Comment by YuraPotapov** [comment] 2019-12-09 11:54
Sorry, more details for reproduce, module odoo/addons/mail/models/mail_thread.py:648
Method _track_subtype must return browse object to consider e61286ecd4ab0ff969f91aff1dc63859f7245852 commit, but returns str object
