### ISSUE TITLE
[13.0] Issue with kanban view when group by

### ISSUE THREAD

**Issue by JordiMForgeFlow** [odoo/odoo#92731] opened 2022-06-02 07:28 UTC
Impacted versions: 13.0, fixed in superior versions

Steps to reproduce: Open kanban view for product variants without any filter applied. Try to group by a field that is stored in product.product (for example 'active'). The error is raised.

Current behavior:

The error is caused in the method _read_progress_bar in mail_activity.py (https://github.com/odoo/odoo/blob/7c2cd8ff5ea8f4c137f574aedc6fc7a190b81c15/addons/mail/models/mail_activity.py#L737). This method performs a specific query for the field 'activity_state' (https://github.com/odoo/odoo/blob/7c2cd8ff5ea8f4c137f574aedc6fc7a190b81c15/addons/mail/models/mail_activity.py#L767) which performs a JOIN after the {from_clause}. The from_clause is based on the tables of the object _query_. Initially the only table that you have in the query tables is product_product, but in the method _apply_ir_rules (https://github.com/odoo/odoo/blob/7c2cd8ff5ea8f4c137f574aedc6fc7a190b81c15/addons/mail/models/mail_activity.py#L750) the table product_template is appended to the tables in the query, specifically it is done here (https://github.com/odoo/odoo/blob/7c2cd8ff5ea8f4c137f574aedc6fc7a190b81c15/odoo/models.py#L4259).

In summary, the problem is basically that in the from_clause, the order of the tables when doing it this way is product_product and product_template, and it is an implicit join (FROM product_product, product_template...). However, as the specific JOIN for the activity_state is explicit join with product_product, SQL raises the error.

It is also worth mentioning that, if we apply the group by with the default filter on the field sale_ok, as the field is from the table product_template the order of the tables is already correct when doing the evaluation in (https://github.com/odoo/odoo/blob/7c2cd8ff5ea8f4c137f574aedc6fc7a190b81c15/addons/mail/models/mail_activity.py#L749). SQL does not complain when the from is like: FROM product_template, product_product JOIN...

I can see that in higher versions the method to _apply_ir_rules has been changed and the error is not happening anymore, so it would be nice if it is easy for you to apply a fix for it based on what you implemented there :)

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/71635103/171574026-d8e5621d-5837-4a9f-8e6a-d9e35bb40275.png)

![image](https://user-images.githubusercontent.com/71635103/171574074-c90fe17e-dd65-41d6-9eee-0482a3cc0136.png)

**Comment by yelizariev** [comment] 2022-06-02 13:44
Hello @JordiMForgeFlow 
Thanks for the analysis.
I do confirm the problem in v13.

The changes in `_apply_ir_rules` (probably  https://github.com/odoo/odoo/commit/dda73afe13f726858876ae4c1b58f1550453d802 ) can't be backported to v13 because of stable version policy. A possible solution could be some patch in `_read_progress_bar` method.

Could you submit a ticket with the link to this issue? We could work on it in a regular way then
https://www.odoo.com/help

**Comment by JordiMForgeFlow** [comment] 2022-06-02 14:03
Hi @yelizariev 

Thank you for looking into it! I have opened ticket #2870937

**Comment by yelizariev** [comment] 2022-07-08 09:13
Indeed, the final query is not valid in v13 because of implicit joins in FROM clause.
The only appropriate solution I see for v13 is disabling the method in such cases: #95634

I also noticed that grouping by such fields doesn't work in v14+ too: it gives empty results. I'll try to fix in v14+ or in master.

v13 query

<details>

```

SELECT 1 AS id, count(*) AS "__count", coalesce("product_product"."active",false) as "active", "_last_activity_state"."activity_state" as "activity_state"
FROM "product_product","product_template" as "product_product__product_tmpl_id"
JOIN (
    SELECT res_id,
    CASE
        WHEN min(date_deadline - (now() AT TIME ZONE COALESCE(res_partner.tz, 'Europe/Brussels'))::date) > 0 THEN 'planned'
        WHEN min(date_deadline - (now() AT TIME ZONE COALESCE(res_partner.tz, 'Europe/Brussels'))::date) < 0 THEN 'overdue'
        WHEN min(date_deadline - (now() AT TIME ZONE COALESCE(res_partner.tz, 'Europe/Brussels'))::date) = 0 THEN 'today'
        ELSE null
    END AS activity_state
    FROM mail_activity
    JOIN res_users ON (res_users.id = mail_activity.user_id)
    JOIN res_partner ON (res_partner.id = res_users.partner_id)
    WHERE res_model = 'product.product'
    GROUP BY res_id
) AS "_last_activity_state" ON ("product_product".id = "_last_activity_state".res_id)
WHERE ("product_product"."active" = true) AND ("product_product"."product_tmpl_id" = "product_product__product_tmpl_id"."id") AND (("product_product__product_tmpl_id"."company_id" in (1))  OR  "product_product__product_tmpl_id"."company_id" IS NULL )
GROUP BY coalesce("product_product"."active",false), "_last_activity_state"."activity_state"
```
</details>

v14 query

<details>

```

SELECT 1 AS id, count(*) AS "__count", coalesce("product_product"."active",false) as "active", "_last_activity_state"."activity_state" as "activity_state"
FROM "product_product" LEFT JOIN "product_template" AS "product_product__product_tmpl_id" ON ("product_product"."product_tmpl_id" = "product_product__product_tmpl_id"."id")
JOIN (
    SELECT res_id,
    CASE
        WHEN min(date_deadline - (now() AT TIME ZONE COALESCE(res_partner.tz, %s))::date) > 0 THEN \'planned\'
        WHEN min(date_deadline - (now() AT TIME ZONE COALESCE(res_partner.tz, %s))::date) < 0 THEN \'overdue\'
        WHEN min(date_deadline - (now() AT TIME ZONE COALESCE(res_partner.tz, %s))::date) = 0 THEN \'today\'
        ELSE null
    END AS activity_state
    FROM mail_activity
    JOIN res_users ON (res_users.id = mail_activity.user_id)
    JOIN res_partner ON (res_partner.id = res_users.partner_id)
    WHERE res_model = \'product.product\'
    GROUP BY res_id
) AS "_last_activity_state" ON ("product_product".id = "_last_activity_state".res_id)
WHERE (("product_product"."active" = %s) AND ("product_product__product_tmpl_id"."available_in_pos" = %s)) AND (("product_product__product_tmpl_id"."company_id" in (%s)) OR "product_product__product_tmpl_id"."company_id" IS NULL )
GROUP BY coalesce("product_product"."active",false), "_last_activity_state"."activity_state"

```
</details>

**Comment by JordiMForgeFlow** [comment] 2022-07-08 09:27
Hi @yelizariev 

Thank you for looking into it! I would also say to disable the method in such cases if the solution is not valid

**Comment by yelizariev** [comment] 2023-01-16 09:30
v13 is not supported anymore.
I'm afraid we have to close this issue, because the problem is not reproduced in v14+.
However, related issue was fixed in v13+ https://github.com/odoo/odoo/pull/95654

For on premise server you may apply this patch: https://github.com/odoo/odoo/pull/95634
For odoo.com/odoo.sh hosting, one should upgrade to Odoo v14+

**Closed by yelizariev** 2023-01-16 09:30 UTC
