### ISSUE TITLE
13 pricelists bug

### ISSUE THREAD

**Issue by szegc** [odoo/odoo#49332] opened 2020-04-09 13:47 UTC
Impacted versions:
13
Steps to reproduce:
Use single company, and active pricelists(multiple prices per product) in sale setting.
Current behavior:
Select menu pricelists in sale,then edit and add a line  ,select apply on "product",no product can listed in product.
Expected behavior:
Display product list,maybe caused by domain.please corrected it.
Video/Screenshot link (optional):

**Comment by szegc** [comment] 2020-04-09 13:48
![image](https://user-images.githubusercontent.com/39893502/78902023-c74e1180-7aab-11ea-9b1b-73e6ba65b3b6.png)

**Comment by sswapnesh** [comment] 2020-04-09 16:51
> Display product list,maybe caused by domain.please corrected it.

I have checked and It is displayed correctly, Can you please check Company Assigned on pricelists and Products?
(If you have selected company Pricelist then you won't be able to See product from other company)

**Comment by pedrobaeza** [comment] 2020-04-09 17:37
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by szegc** [comment] 2020-04-09 18:32
Multi-company mode used in runbot, so it's different.Company_id only visiable in multi-company mode for pricelist and product.
No changes have been made to it，update to the latest version,issue still exists.
Please do not active multi-company, and active pricelists(multiple prices per product) in sale setting,
then edit in sale menu pricelists,add price item for a product,then you can see symptom like mentioned.
[screenshot.docx](https://github.com/odoo/odoo/files/4457977/screenshot.docx)

**Comment by pedrobaeza** [comment] 2020-04-09 18:37
What I see is that if you don't have products in your company, how do you expect to have them on the list?

**Comment by szegc** [comment] 2020-04-09 18:44
I want to see the product in product list in price item and then assign a price for it.

**Comment by pedrobaeza** [comment] 2020-04-09 18:50
But for that you have to put the products to be multi-company.

**Comment by szegc** [comment] 2020-04-09 19:08
![image](https://user-images.githubusercontent.com/39893502/78931384-786aa100-7ad8-11ea-9f47-b6c658c75798.png)

When pricelist is created no company_id assigned by default(company_id invisiable in single company mode, so can't assign it by manual).
So you mean pricelist only used in multi-company ? Otherwise can only use standard price?

**Comment by pedrobaeza** [comment] 2020-04-09 19:15
No, I'm guessing that products you are trying to add belongs to other company where you are logged in, but no real facts as you are not specifying detailed steps from the beginning for reproducing the problem.

**Comment by szegc** [comment] 2020-04-09 19:21
No, only one company exists.And after product created,default company_id assigned:
![image](https://user-images.githubusercontent.com/39893502/78932422-07c48400-7ada-11ea-950e-1b4163946130.png)
Just use single-company mode,and  active pricelists(multiple prices per product) in sale setting，
Create a product and pricelist,and then create pricelist item for the product, then you can reproduce it.

**Comment by pedrobaeza** [comment] 2020-04-09 19:34
I'm not able to reproduce it:
![Selección_027](https://user-images.githubusercontent.com/7165771/78933672-f2cffc80-7aa9-11ea-89d0-ad41acd7669f.png)

**Comment by szegc** [comment] 2020-04-09 19:39
Are you used in multi-company mode?

**Comment by pedrobaeza** [comment] 2020-04-09 19:41
What means for you "multi-company mode"?

**Comment by szegc** [comment] 2020-04-09 19:43
Only one company  defined in company . Like this :
![image](https://user-images.githubusercontent.com/39893502/78934394-6c351280-7add-11ea-8ef8-84d8bc8f94d2.png)

**Comment by pedrobaeza** [comment] 2020-04-09 19:57
I still don't understand.

@sswapnesh or @Yenthe666 do you?

**Comment by Yenthe666** [comment] 2020-04-10 06:22
Sorry but I tested the flow in multi-company and it seems to work just fine?
Please provide us with detailed steps from the creation of the product to the pricelists (or a video)

**Comment by szegc** [comment] 2020-04-10 06:27
Please do not test in multi-company mode,just in single-company mode.

**Comment by Yenthe666** [comment] 2020-04-10 06:50
That works just fine too:
![image](https://user-images.githubusercontent.com/6352350/78969856-4d984100-7b08-11ea-9a4c-64497e619ddf.png)

**Comment by szegc** [comment] 2020-04-10 06:53
Don't know why. I'll try to update and test the code again . Thank you.

**Comment by Yenthe666** [comment] 2020-04-10 07:01
Okay, I'll close it for now but don't hesitate to respond back if you found reproducable steps :)

**Closed by Yenthe666** 2020-04-10 07:01 UTC
Labels: 13.0, Need information

**Comment by sswapnesh** [comment] 2020-04-11 06:07
@szegc 
> No, only one company exists.And after product created,default company_id assigned:

So, You are assigning (or its already there)  `company_id` on a Product but on pricelist `company_id` is null.

To correct this, You have to remove the `company_id` from All Product manually. (I wonder How Products have company assigned If you are not using multi-company) or Select the company on Pricelist.




------------------------

The only way I can think of to Re-produce on Single company is (Which is not valid)

- Enable Multi-company, (and We have just once Company  - in` res.company`)
- Select the company on Product
- Disable Multi-company 
- Create Pricelist
- No Products will be visible as they are assigned to the company, (While company is False on Pricelist)
