### ISSUE TITLE
Some button titles for select a view type are untranslatable.

### ISSUE THREAD

**Issue by edy1192** [odoo/odoo#31009] opened 2019-02-11 23:09 UTC
Impacted versions:
12.0

Steps to reproduce:
1. Activate Spanish language.
1. Change the user language to Spanish.
1. Go to a view (eg: Invoices).
1. Mouse over any button to select view type (e.g. kanban)

Current behavior:
- The button titles are not in Spanish.
- When exporting the `.pot`  or `es.po` file these terms are not exported.

Expected behavior:
- The button titles should be in Spanish.
- When exporting the `.pot`  or `es.po` file these terms should be exported.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/11479473/52599340-fd4b2380-2e1d-11e9-8048-ea221978b072.png)

![image](https://user-images.githubusercontent.com/11479473/52599334-f8866f80-2e1d-11e9-9ccd-c69cc0b4be3e.png)

**Comment by edy1192** [comment] 2019-02-11 23:25
OPW-1939678

**Comment by luisg123v** [comment] 2019-02-13 17:59
@mart-e wasn't this already fixed on https://github.com/odoo/odoo/pull/29432?

**Comment by mart-e** [comment] 2019-02-14 06:35
@luisg123v no, this is a different issue, this is a web view, not one processed server side.
Looks like bootstrap is composing the data-original-title which is not translated.

Something like odoo-dev/odoo@b3465088cec (not merged, just testing) is probably a first step but anyway, the label is composed here

https://github.com/odoo/odoo/blob/ef03db9edd9472201cb2c08a32d20ff0f33a5fdf/addons/web/static/src/xml/base.xml#L209

and the `t-` values are not translatable (as containing logic).

@ged-odoo can we consider building the label js side with explicit calls to `_t` instead?

**Comment by luisg123v** [comment] 2019-02-14 15:07
@mart-e   
You're right!

I don't know if it's possible, but another alternative could be to have the translated view name on a different attribute.

**Comment by C3POdoo** [comment] 2019-04-11 14:11
Dear @edy1192,

_This is an automated message._
This issue is linked to the Odoo support ticket opw-1939678 that has been closed.
We hope you got an answer to your issue.

If you believe the problem is not solved yet and would like to keep this issue open, please let us know to reopen it.

**Comment by luisg123v** [comment] 2019-04-13 00:06
Hi @mart-e 
Could you reopen this issue, please? It was automatically closed.

CC @nhomar

**Comment by C3POdoo** [comment] 2023-03-30 11:53
Dear @edy1192,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._

**Closed by C3POdoo** 2023-03-30 11:53 UTC
Labels: OE, Internationalization, 12.0
