### ISSUE TITLE
Odoo 10 Bugs Failed to restore with multi worker, Most common issue.

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#15658] opened 2017-02-27 14:50 UTC
Impacted versions: 10.0

Steps to reproduce:  With multi worker 6
Restore database with mutli-database with db-filter on subdomain

Current behavior:
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 167, in load_module_graph
    module.with_context(overwrite=overwrite).update_translations()
  File "/odoo/odoo-server/odoo/addons/base/module/module.py", line 767, in update_translations
    self.env['ir.translation'].load_module_terms(mod_names, filter_lang)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_translation.py", line 704, in load_module_terms
    res_lang.load_lang(lang)
  File "/odoo/odoo-server/odoo/addons/base/res/res_lang.py", line 90, in load_lang
    language.write({'active': True})
  File "/odoo/odoo-server/odoo/addons/base/res/res_lang.py", line 222, in write
    return super(Lang, self).write(vals)
  File "/odoo/odoo-server/odoo/models.py", line 3550, in write
    self._write(old_vals)
  File "/odoo/odoo-server/odoo/models.py", line 3631, in _write
    cr.execute(query, params + (sub_ids,))
  File "/odoo/odoo-server/odoo/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

Expected behavior:  Normal 

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment] 2018-01-10 15:56
Closing as duplicate of https://github.com/odoo/odoo/issues/15659

**Closed by Yenthe666** 2018-01-10 15:56 UTC
