### ISSUE TITLE
Normal user can not import data from excel file

### ISSUE THREAD

**Issue by ADVALAKI** [odoo/odoo#46342] opened 2020-02-26 12:46 UTC
Impacted versions: 13.0

Steps to reproduce:

1. Create user.
2. Login with that user.
3. Try to import product(or any other data) using excel file.
It will give trackback.

here is code from where its trigger.
https://github.com/odoo/odoo/blob/13.0/odoo/fields.py#L1857

Current behavior: Its not allow to import data using excel file.

Expected behavior: It should allow user to import data

Video/Screenshot link (optional):
https://imgur.com/W3HBsM6

VIdeo: https://streamable.com/gleqf

Sample FIle: https://filebin.net/3wp7i0aiobo6nn7l

**Comment by ADVALAKI** [comment] 2020-02-26 12:47
created issue again as old issue is closed  #46286

**Comment by pedrobaeza** [comment] 2020-02-26 12:49
And I'm going to close this one again unless you provide useful steps to reproduce the problem...

Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by ADVALAKI** [comment] 2020-02-26 12:52
@pedrobaeza please follow step.:

login with user: demo/demo on (http://runbot.odoo.com/runbot)

and try to import excel file using import button on any object.

thats it. you will get trackback.

i request you to test(reproduce) it once, on runbot before closing this.

**Comment by pedrobaeza** [comment] 2020-02-26 12:54
I have already done it without problem, and that's why I say that if you don't specify what are you trying to import, it's not possible to reproduce it.

**Comment by ADVALAKI** [comment] 2020-02-26 12:56
let me share video.

**Comment by pedrobaeza** [comment] 2020-02-26 12:56
Better to put here the excel (properly obfuscated) that you are trying to import.

**Comment by ADVALAKI** [comment] 2020-02-26 12:57
> Better to put here the excel (properly obfuscated) that you are trying to import.

sure let me do that. thanks

**Comment by ADVALAKI** [comment] 2020-02-26 13:10
@pedrobaeza  Here is video.

VIdeo: https://streamable.com/gleqf

Sample FIle: https://filebin.net/3wp7i0aiobo6nn7l

**Comment by ADVALAKI** [comment] 2020-03-02 06:52
> @pedrobaeza Here is video.
> 
> VIdeo: https://streamable.com/gleqf
> 
> Sample FIle: https://filebin.net/3wp7i0aiobo6nn7l

@pedrobaeza i hope this is enough information to regenerate issue.
let me know if you need any further info.

**Comment by pedrobaeza** [comment] 2020-03-02 07:37
Yes, I have reproduced it. It happens only with XLSX. Meanwhile, you can convert file to XLS for importing.

Tagging the issue.

**Comment by sswapnesh** [comment] 2020-03-11 17:47
#47382 will fix this

**Comment by pedrobaeza** [comment] 2020-05-05 17:37
Closing as PR has been merged.

**Closed by pedrobaeza** 2020-05-05 17:37 UTC
Labels: 13.0, Framework
