### ISSUE TITLE
[8.0][9.0] Week number bug

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#9375] opened 2015-11-03 08:28 UTC
Hi Odoo,

I find there’s no consistency of week number between calendar view and pivot view.
To test it, you can test on runbot both on version 8 and 9:
1.  Create a manufacture order
2.  Look on the calendar view and remember the week number
3.  Look on the pivot view, and select based on schedule month based on weeks.
4.  You will find the issue which is week number is not same.

Here is the video to explain things:
https://www.dropbox.com/s/tdq0dyapmx4tyvc/weeknumberbug.avi?dl=0

**Comment by pedrobaeza** [comment] 2018-04-10 00:51
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-04-10 00:51 UTC
Labels: 9.0
