### ISSUE TITLE
[11.0]  point of sale generating wrong stock moves and messing up inventory

### ISSUE THREAD

**Issue by hydrosIII** [odoo/odoo#36976] opened 2019-09-16 18:53 UTC
I have wondered if to post this here as it is a suspicion. But I do not know where else to post it. So let me explain.

I have detected in my system a great amount of errors in the inventory. I found this when comparing the tables in odoo 11 enterprise stock_move_line, where the actual moves of stock are recorded and the stock_quant table, the table that odoo uses to display the stock in the GUI. For this detection I have compared manually the tables stock_move_line where the actual stock move are recorded and stock_quant. 

I update the system every month with a new version of odoo. 

**II suspect point of sale or something with lot selection is messing up the tables, I have only one extra module installed in my system and it is pos_lot_selection by oca**

The error arises when I compare the sum of the stock of products recorded in each table. This sum should be equal, but it is not. I put here the sql script I have created to check this difference:

```
/*Gets the current entries in the location connected with pos*/
WITH incoming as (
SELECT product_id, Sum(qty_done)
FROM stock_move_line
WHERE location_dest_id=15
GROUP BY product_id
), outgoing AS
/* gets the current outgoing stock from one determined location*/
(SELECT product_id, Sum(qty_done)
FROM stock_move_line
WHERE location_id=15
GROUP BY product_id
/*puts the quantity of stock incoming aside from its outgoing quantity*/
), incomingvsoutgoing AS (
SELECT incoming.product_id AS id, incoming.sum AS incoming, outgoing.sum AS outgoing
FROM incoming
LEFT OUTER JOIN outgoing
ON incoming.product_id = outgoing.product_id 
/*Gets the difference of the incoming stock vs the outgoing stock to get the difference and supposed stock in that location*/
), comparison AS
(select id, Sum(incoming) AS quant_incoming, Sum(outgoing) AS quant_outgoing, Sum(incoming-outgoing) AS supposed_stock
from  incomingvsoutgoing
group by id
/*Get the quantity in that location from the stock_quant table, this table is used by odoo to display the current stock*/
), stock_qty AS 
( SELECT product_id, Sum(quantity) AS quant_stock_ontable
FROM stock_quant
WHERE location_id=15 
GROUP BY product_id
/*Gets side by side the calculated supposed quantity and the quantity from the stock_quant*/
), supposed_stock_vs_stock_on_table AS
(SELECT id,quant_incoming,quant_outgoing, supposed_stock, quant_stock_ontable
from comparison, stock_qty
WHERE comparison.id=stock_qty.product_id
/*substracts the difference of supposed stock - quant_stock_on_table to get the difference*/
), results AS 
(select supposed_stock_vs_stock_on_table.id, Sum(supposed_stock_vs_stock_on_table.quant_incoming) AS  quant_incoming, Sum(supposed_stock) AS supposed_stock, Sum(supposed_stock_vs_stock_on_table.quant_outgoing) AS quant_outgoing, Sum(supposed_stock_vs_stock_on_table.supposed_stock-supposed_stock_vs_stock_on_table.quant_stock_ontable) AS difference, Sum(quant_stock_ontable) AS quant_stock_ontable
from supposed_stock_vs_stock_on_table
group by id
/*adds the product barcode*/
), results_w_code AS (
select results.id, results.quant_incoming, results.quant_outgoing, results.difference, supposed_stock, default_code, product_tmpl_id,  quant_stock_ontable
from results, product_product
where results.id = product_product.id)
/*prints the results, adding the product name, and selecting just the products where the supposed stock is not equal to the stock in stock_quant table*/
SELECT results_w_code.id as product_database_id, results_w_code.quant_incoming, results_w_code.quant_outgoing, supposed_stock, results_w_code.quant_stock_ontable, difference, name as corrupted_product_name, product_template.default_code AS corrupted_product_code
from results_w_code, product_template
WHERE results_w_code.product_tmpl_id = product_template.id 
AND difference IS NOT NULL
AND difference <> 0
ORDER BY difference DESC;

```
.
Also I have noticed the following trends:

a) The error rate grows every month, adding new products and new errors every month.
b) These errors only occur in the location (15) that is my default location in my odoo config where the products are taken from to  sale them later in the point of sale. No other location is affected by inventory errors despite transactions.

So far I think there are three possibilities.
1) An error in the odoo core modules.
2) An error the pos_lot_selection module in oca. 
3) Something else.

Unfortunately I do not have the steps to reproduce this bug. I have tried in unbot several times but i haven't replicated it. The problems seems to arise only when a lot of transactions are done. Not just a few. The issue has been around 6 months in my system, also I have detected odoo 10 systems that have it also.

**Comment by switch87** [comment] 2019-09-17 09:15
@hydrosIII since you use a oca module to do these lot transactions, it's recommended to report the bug first on their github branch. With the information you provide and since we don't use oca code at Odoo we are not able to reproduce the problem. I will close the issue for now, once you are sure it is a Odoo problem feel free to open it again with the new information.

**Closed by switch87** 2019-09-17 09:15 UTC
Labels: 11.0, Point of Sale

**Comment by hydrosIII** [comment] 2019-09-26 18:20
I have corrected manually the table stock quant after a lot of effort, One week later i have corrupted lots in tables and almost 400 products corrupted in the stock_quant. For every lot that must be unique I have different products in stock_quant. These are related to inactive products, and are always the same inactive products. So, in one week in my stock_quant table I have: corrupted lots, corrupted quantity.
I send some screenshots.
![Captura de pantalla de 2019-09-26 13-02-57](https://user-images.githubusercontent.com/7807363/65714238-5344a280-e060-11e9-8389-71b2e2dea1c8.png)
![Captura de pantalla de 2019-09-26 13-05-06](https://user-images.githubusercontent.com/7807363/65714243-5475cf80-e060-11e9-9832-6084c0348f3b.png)

**Comment by pedrobaeza** [comment] 2019-09-26 18:27
@hydrosIII but still without steps to reproduce the problem? What are you talking about inactive products? Are they sold in PoS being inactive?

And the weird thing is that several of us are using these features and nobody has experimented this problem for now.
