### ISSUE TITLE
Issue integrating Asterisk with Odoo

### ISSUE THREAD

**Issue by AdrianJoel** [odoo/odoo#16815] opened 2017-05-04 20:21 UTC
Hello.

I installed new modules in Odoo because I want to integrate with my Asterisk Server. When I want to call, the following message appears:

OpenERP Server Error
Traceback (most recent call last):
  File "/opt/openerp/server/openerp/http.py", line 470, in dispatch
    result = self._call_function(**self.params)
  File "/opt/openerp/server/openerp/http.py", line 294, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/openerp/server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/openerp/server/openerp/http.py", line 291, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/openerp/server/openerp/http.py", line 638, in __call__
    return self.method(*args, **kw)
  File "/opt/openerp/server/openerp/http.py", line 337, in response_wrap
    response = f(*args, **kw)
TypeError: get_record_from_my_channel() takes exactly 2 arguments (1 given)

Please help me, I am new in this topic.

**Comment by Yenthe666** [comment] 2017-05-05 06:49
Hi @AdrianJoel,

If I am not mistaking you're install a non official module from Akretion named Asterisk?
In this case this looks like a bug in the custom module from Akretion and it has nothing to do with Odoo.
Also, is this issue https://github.com/odoo/odoo/issues/16816 the same problem? The traceback looks identical.

Regards,
Yenthe

**Comment by AdrianJoel** [comment] 2017-05-05 13:57
Hi @Yenthe666
Yes, It is the same issue. Before installing Asterisk modules, I didn't have problems. I erased the installed files in the "addons" folder but the problem persists.

**Comment by Yenthe666** [comment] 2017-05-30 09:04
Hi @AdrianJoel,

Alright thank you for the extra information.
As your report is about a non-official module you'll have better luck asking feedback (or reporting the issue) at https://github.com/OCA/connector-telephony
You might want to ask this question on the official help forums too (http://odoo.com/help)
Closing as this is not a bug in the official Odoo but in a module from somebody else.

Regards,
Yenthe

**Closed by Yenthe666** 2017-05-30 09:04 UTC
Labels: need informations
