### ISSUE TITLE
Pasting from excel loses formatting

### ISSUE THREAD

**Issue by shazzwazz20** [odoo/odoo#61538] opened 2020-11-09 13:15 UTC
Impacted versions:
odoo 12 enterprise
Steps to reproduce:
1. Go to any html editor on Odoo .
2. Copy content from excel and paste it on editor.

Current behavior:
Table from excel not showing or breaks the css
Expected behavior:
Table should appear on editor.

Video/Screenshot link (optional):
https://user-images.githubusercontent.com/5850263/33992194-17aa5f92-e0eb-11e7-8dc0-1f48350b455f.PNG

**Comment by Yenthe666** [comment] 2020-11-09 14:20
Duplicate of https://github.com/odoo/odoo/issues/61536

**Closed by Yenthe666** 2020-11-09 14:20 UTC
