### ISSUE TITLE
Exception: bus.Bus unavailable

### ISSUE THREAD

**Issue by periatrubikx** [odoo/odoo#68792] opened 2021-04-06 05:10 UTC
Impacted versions: 14.0

Steps to reproduce: 
1. run docker image of Odoo 14.
2. Log into the container using the following command (docker exec -it $container_name bash) - replace container name with whatever your container name is
3. update any module using the following command (odoo --xmlrpc-port 8070 -u $custom_add_on_module -d $database_name) - here I have a custom module which I was trying to update. 

Current behavior: The update is successful, however get the following exceptions post update:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
Exception: bus.Bus unavailable

In my odoo.conf file, I have the long_polloing_port configured to 8072 etc.. 

Expected behavior: The update should be clean without any errors/exceptions.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment] 2021-04-06 06:11
This is not a bug, but the problem is in the way you do the update, having used the longpolling port 2 times. Ask in the forums for more information.

Closing thus.

**Closed by pedrobaeza** 2021-04-06 06:11 UTC

**Comment by periatrubikx** [comment] 2021-04-06 12:30
Strangely enough, I didn't encounter it in Odoo 13.0 and so was wondering, what might have changed. I will try to figure out where and why the double calling might be happening. 

I did put the question on the forum some time ago; but haven't received any responses. Thanks for the quick feedback though. I appreciate it.
