### ISSUE TITLE
please help this error

### ISSUE THREAD

**Issue by m7med7amdy** [odoo/odoo#63745] opened 2020-12-23 14:00 UTC
Odoo Server Error
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\models.py", line 5096, in ensure_one
    _id, = self._ids
ValueError: too many values to unpack (expected 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\pycompat.py", line 14, in reraise
    raise value
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\service\model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 915, in _call_
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\web\controllers\main.py", line 1331, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\web\controllers\main.py", line 1319, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\stock\models\stock_picking.py", line 910, in button_validate
    self.action_done()
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\stock\models\stock_picking.py", line 727, in action_done
    todo_moves._action_done(cancel_backorder=self.env.context.get('cancel_backorder'))
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\stock_account\models\stock_move.py", line 250, in _action_done
    res = super(StockMove, self)._action_done(cancel_backorder=cancel_backorder)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\stock\models\stock_move.py", line 1422, in _action_done
    moves_todo.write({'state': 'done', 'date': fields.Datetime.now()})
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\stock\models\stock_move.py", line 499, in write
    res = super(StockMove, self).write(vals)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\models.py", line 3627, in write
    real_recs._validate_fields(set(vals) - set(inverse_fields))
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\models.py", line 1201, in _validate_fields
    check(self)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\warehouse_stock_restrictions\stock.py", line 27, in check_user_location_rights
    self.ensure_one()
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\models.py", line 5099, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: stock.move(113, 114, 115, 116)

**Comment by pedrobaeza** [comment] 2020-12-23 14:53
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2020-12-23 14:53 UTC
