### ISSUE TITLE
Search results in tree view different depending of result sorting

### ISSUE THREAD

**Issue by gediminasvenc** [odoo/odoo#37151] opened 2019-09-19 13:30 UTC
Impacted versions: 

12ce, 12 ee

Steps to reproduce: 

Go into the sale order tree view, and search sale orders by product called 'a'. Note, that the number of results should be over 40, so in runbot you need to duplicate a few sale orders for it to work.

![image](https://user-images.githubusercontent.com/19407260/65245315-0c512d00-daf5-11e9-9122-fe9020a05381.png)

Current behavior:

Now try to sort results by "Quotation Number"
The number of results will be different regarding how you will sort, ascending or descending:

![image](https://user-images.githubusercontent.com/19407260/65246958-322c0100-daf8-11e9-94cd-052e844b83ab.png)

![image](https://user-images.githubusercontent.com/19407260/65246999-43750d80-daf8-11e9-9795-bb61924b22d7.png)

Expected behavior:

Number of results should be the same no matter how results are sorted

Video/Screenshot link (optional):

[Screencast 2019-09-19 16:20:11.zip](https://github.com/odoo/odoo/files/3631419/Screencast.2019-09-19.16.20.11.zip)

**Comment by pedrobaeza** [comment] 2019-09-19 13:31
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by gediminasvenc** [comment] 2019-09-19 13:35
Please go into http://625575-12-0-e02ff9.runbot26.odoo.com/web?debug=1#action=826&model=sale.order&view_type=list&menu_id=555
Search by product called 'a', and try to sort lines by Quotation Number

**Comment by Yenthe666** [comment] 2019-09-19 13:37
Well, there is indeed a difference. 
Initial search = 37 records
First time sorting on lines by Quotation number = 40
Second time sorting on lines by Quotation number = 39 records

**Comment by gediminasvenc** [comment] 2019-09-19 13:39
I did a quick look and if you hard code limit=0 in this method it will show all results:
def _search(self, args, offset=0, limit=None, order=None, count=False, access_rights_uid=None):
@Yenthe666 thanks for confirming :)

**Comment by Feyensv** [comment] 2019-10-02 08:24
Seems it has been solved, can't reproduce it anymore on last v12 runbots.
Can you confirm it has been solved for you ? :)

**Comment by gediminasvenc** [comment] 2019-10-10 10:35
Hi, sorry for late reply, no it's still not fixed. Here you can see it, go to http://645713-12-0-d26395.runbot11.odoo.com/web#action=1028&model=sale.order&view_type=list&menu_id=688
Go to sales orders, search products by the name "**a**", and group by the **salesperson**.
![image](https://user-images.githubusercontent.com/19407260/66561647-8ad44400-eb62-11e9-8080-ffceeff0a882.png)
It says 122 records. Open this group:
![image](https://user-images.githubusercontent.com/19407260/66561707-9fb0d780-eb62-11e9-950b-796e7d561401.png)
You see 32 records. Sort it another way around by Quotation Number:
![image](https://user-images.githubusercontent.com/19407260/66561748-bc4d0f80-eb62-11e9-852c-46d174cf3840.png)
And you have 29 records.

**Comment by Yenthe666** [comment] 2019-12-03 07:54
@Feyensv hi is there any update about this one?

**Comment by Feyensv** [comment] 2019-12-03 12:14
No change is currently planned for this.
It could be "easily" solved, but would lead to a huge performance loss which isn't worth this minor case.

A more advanced solution would need to be tested with regards to performance and code complexity to verify its worth.  But this is not planned in the short term...

**Comment by C3POdoo** [comment] 2023-03-30 11:47
Dear @gediminasvenc,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._

**Closed by C3POdoo** 2023-03-30 11:47 UTC
Labels: Confirmed, 12.0, Sales
