### ISSUE TITLE
Issue in Setting Dashboard Button Navigation

### ISSUE THREAD

**Issue by ashish-webkul** [odoo/odoo#27558] opened 2018-10-09 07:02 UTC
Impacted versions: 12.0

Steps to reproduce: Go to dashboard then click on buttons present inside the dashboard

Current behavior: After clicking on these buttons it sends back to the home page

Expected behavior: Buttons should go to correct pages.

Video/Screenshot link (optional):
[Dashboard](http://nimb.ws/Tsf0Lw)
[dashboard.webm.zip](https://github.com/odoo/odoo/files/2459209/dashboard.webm.zip)

**Comment by sswapnesh** [comment] 2018-10-09 08:31
Duplicate of https://github.com/odoo/odoo/issues/27434

**Closed** 2018-10-09 08:52 UTC
