### ISSUE TITLE
I can't open website app from odoo 13 dashboard!

### ISSUE THREAD

**Issue by Ahmedposhi** [odoo/odoo#44202] opened 2020-01-29 13:24 UTC
Impacted versions: odoo 13

Steps to reproduce: 1- `Access website builder`. 2-Tried from "chrome, firefox and Microsoft edge.
Current behavior: Odoo Server Error.

Expected behavior: open the website to create or edit.
![website_error_-_odoo_13](https://user-images.githubusercontent.com/40128980/73360338-5e783b00-42ab-11ea-97fe-f3ae8360275f.png)

`Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/src/odoo/13.0/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/13.0/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/13.0/addons/website_sale/controllers/backend.py", line 55, in fetch_dashboard_data
    groupby='product_tmpl_id', orderby='product_uom_qty desc', limit=5)
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 2132, in read_group
    result = self._read_group_raw(domain, fields, groupby, offset=offset, limit=limit, orderby=orderby, lazy=lazy)
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 2257, in _read_group_raw
    self._cr.execute(query, where_clause_params)
  File "/home/odoo/src/odoo/13.0/odoo/sql_db.py", line 163, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/src/odoo/13.0/odoo/sql_db.py", line 240, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: column sale_report.website_id does not exist
LINE 4:             WHERE (((("sale_report"."website_id" = 1)  AND  ...
                              ^`
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment] 2020-01-29 13:30
Hi @Ahmedposhi,

You seem to be reporting quite some issues lately and they all lack details and steps on how to reproduce the problem. Given the limited info and the fact that you're getting so many errors I assume you're doing something wrong on your deployment. Have you checked out the developer docs? (https://www.odoo.com/documentation/13.0/)

Please add more steps on how to reproduce this or this issue will be closed soon. CC @pedrobaeza 

Regards,
Yenthe

**Comment by Ahmedposhi** [comment] 2020-01-29 14:11
> 
> 
> Hi @Ahmedposhi,
> 
> You seem to be reporting quite some issues lately and they all lack details and steps on how to reproduce the problem. Given the limited info and the fact that you're getting so many errors I assume you're doing something wrong on your deployment. Have you checked out the developer docs? (https://www.odoo.com/documentation/13.0/)
> 
> Please add more steps on how to reproduce this or this issue will be closed soon. CC @pedrobaeza
> 
> Regards,
> Yenthe

the deployment process was made correctly, and the administrator can open the app, but i'm can't.

**Comment by Yenthe666** [comment] 2020-01-29 14:13
Again, we really need reproducable steps. Since this all works fine on the latest runbot instances and you're not providing reproducable steps we can't help

**Comment by Ahmedposhi** [comment] 2020-01-29 14:18
> 
> 
> Again, we really need reproducable steps. Since this all works fine on the latest runbot instances and you're not providing reproducable steps we can't help

i'm sorry, but i'm new on github and don't know how to provide reproduce steps. could you explain please.

**Comment by Yenthe666** [comment] 2020-01-29 14:24
@Ahmedposhi well, we need a flow on how to reproduce it on a new Odoo 13 instance. Basically write down all the steps that you've did to get this error. Perhaps https://github.com/odoo/odoo/wiki/Contributing#reporting-issues can give you some more insights :)

**Comment by Ahmedposhi** [comment] 2020-01-29 14:27
> 
> 
> @Ahmedposhi well, we need a flow on how to reproduce it on a new Odoo 13 instance. Basically write down all the steps that you've did to get this error. Perhaps https://github.com/odoo/odoo/wiki/Contributing#reporting-issues can give you some more insights :)

thank you, i will work on it and submit more steps.

**Comment by Ahmedposhi** [comment] 2020-01-29 16:16
> 
> 
> > @Ahmedposhi well, we need a flow on how to reproduce it on a new Odoo 13 instance. Basically write down all the steps that you've did to get this error. Perhaps https://github.com/odoo/odoo/wiki/Contributing#reporting-issues can give you some more insights :)
> 
> thank you, i will work on it and submit more steps.

please check my issue again.

**Comment by Ahmedposhi** [comment] 2020-01-29 17:09
> 
> 
> @Ahmedposhi well, we need a flow on how to reproduce it on a new Odoo 13 instance. Basically write down all the steps that you've did to get this error. Perhaps https://github.com/odoo/odoo/wiki/Contributing#reporting-issues can give you some more insights :)

please check again.

**Comment by pedrobaeza** [comment] 2020-01-29 17:47
Sorry but this is not reproducible in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin), so the problem should be on your side. Closing this until you are able to give these steps.

**Closed by pedrobaeza** 2020-01-29 17:47 UTC
Labels: 13.0, Need information
