### ISSUE TITLE
setup.py install ends with error : setup script specifies an absolute path

### ISSUE THREAD

**Issue by mr-akin** [odoo/odoo#25311] opened 2018-06-18 20:05 UTC
**impacted version:** 11.0

**How to reproduce?**
`python setup.py install`

**Result:**

```
error: Error: setup script specifies an absolute path:

    C:\Users\abcd\AppData\Local\Programs\Python\Python36\lib\site-packages\babel\global.dat

setup() arguments must *always* be /-separated paths relative to the
setup.py directory, *never* absolute paths.
```

**Comment by pedrobaeza** [comment] 2018-06-18 20:21
Can you specify the detailed steps to reproduce the problem?

**Comment by pedrobaeza** [comment] 2018-07-02 01:19
@d-fence do you have a clue on this, or should we close it as not enough information?

**Comment by d-fence** [comment] 2018-07-02 06:19
Hello, it seems linked to the py2exe stuffs:
https://github.com/odoo/odoo/blob/2ab3fa86fe83d507e9e1152ad2a44811af7f55cd/setup.py#L26

py2exe is not used anymore since v11, I have to clean the setup file.

**Comment by mr-akin** [comment] 2018-07-03 09:01
Hello, I'm sorry for following up after too long. @d-fence Yes its related to py2exe stuff, I want to make an executable file but ends up with that mentioned error.

**Comment by d-fence** [comment] 2018-07-03 11:24
@mr-akin py2exe doesn't not work anymore with Odoo since version 11.
I'm sorry.
I close this issue as it was the purpose.

**Closed by d-fence** 2018-07-03 11:24 UTC
Labels: 11.0, Need information

**Comment by mr-akin** [comment] 2018-07-03 19:09
@d-fence  so this means there is no way I can make an executable file?

**Comment by d-fence** [comment] 2018-07-04 05:52
I tried hard, also with cx_Freeze and Pyinstaller.
The py2exe section in the setup.py is rather old and is about the previous Odoo version.
