### ISSUE TITLE
sometimes tax cash based move lines are marked with tax_exigible = True after invoice validation

### ISSUE THREAD

**Issue by eburghar** [odoo/odoo#22358] opened 2018-01-18 20:56 UTC
Impacted versions: 11.0

Steps to reproduce: Define a purchase tax based on payment, create a supplier bill with one line and validate.

Current behavior: On tax report, we can see the tax without Net (net line has tax_exigible = False but not the tax line)

Expected behavior: No tax before payment received 

The following code on `addons/account/models/account_move.py` is wrong

```python
         taxes = False
         if vals.get('tax_line_id'):
             taxes = [{'tax_exigibility': self.env['account.tax'].browse(vals['tax_line_id']).tax_exigibility}]
         if vals.get('tax_ids'):
             taxes = self.env['account.move.line'].resolve_2many_commands('tax_ids', vals['tax_ids'])
```

`tax_ids` can be `(6, 0, [])` and in that case `taxes` is overwritten leading to the bug.

This fixed the bug

```python
        taxes = []
        if vals.get('tax_line_id'):
            taxes = [{'tax_exigibility': self.env['account.tax'].browse(vals['tax_line_id']).tax_exigibility}]
        if vals.get('tax_ids'):
            taxes.extend(self.env['account.move.line'].resolve_2many_commands('tax_ids', vals['tax_ids']))
```

**Comment by Yenthe666** [comment] 2018-01-19 09:09
@qdp-odoo could you check? If you approve the concept I'll make a PR to help you.

**Comment by qdp-odoo** [comment] 2018-02-09 15:06
can't reproduce, and I don't see how the code could fail/how yours would improve anything...

can you give more details? I'm closing this issue in the meanwhile

**Closed by qdp-odoo** 2018-02-09 15:06 UTC
Labels: 11.0, Accounting
