### ISSUE TITLE
[Odoo 11.0] Direction RTL doesn't applied

### ISSUE THREAD

**Issue by arriouach** [odoo/odoo#20682] opened 2017-11-03 19:39 UTC
Hi,
When I changing Direction value to Right-To-Left for language, doesn't work correctly.
Someone have any idea.

ARRIOUACH,

**Comment by Yenthe666** [comment] 2017-11-05 18:25
Hi @arriouach,

Thank you for your report. @mart-e could you please check?

**Comment by mart-e** [comment] 2017-11-06 11:52
Hello,

The Right-to-Left support is not complete at the moment. We plan to improve it but it is a long refactoring.
However, if you specify what does not work, maybe we can help.

**Comment by arriouach** [comment] 2017-11-06 13:12
Hello @mart-e,
Thanks for your replies, I want just know if I can use odoo as a Arabic UI (Right-To-Left).

**Comment by mart-e** [comment] 2017-11-06 13:41
It should be working but is not optimal.
We have already worked on it, for instance at #19892 (giving you an idea of the size of the change) but it is not ready yet.

**Comment by haggag** [comment] 2017-12-17 12:36
I can confirm the following issues for exported PDF reports when the UI language is set to Arabic (an RTL language):

- The header has scrambled HTML printed in every page 
- The footer has scrambled HTML printed in every page
- The report words in general is translated but still LTR not RTL, but this is minor compared the first 2 issues.

Attached are screenshots for an exported PDF report for both the header and footer.
![footer](https://user-images.githubusercontent.com/114218/34079508-05752f1c-e340-11e7-93ef-da621f4ac2b1.png)
![header](https://user-images.githubusercontent.com/114218/34079509-0593aca8-e340-11e7-95cb-47ff049a6207.png)

**Comment by mart-e** [comment] 2017-12-19 08:33
@haggag thanks, we know all these issues.
As said above we tried to fix it (#19892) but it is not correct either. The problem is that bootstrap does not support RTL so we will need to figure out a way to fix that.
So far, we can unfortunately not offer any solution for the current versions but hope v12 will support RTL.

**Comment by j209** [comment] 2017-12-24 14:03
[Bootstrap-rtl](https://github.com/morteza/bootstrap-rtl)
This may help you.

**Comment by hanyelbanna** [comment] 2017-12-30 12:52
@mart-e Could I go throw (#19892) and try to fix another bugs like all the contents go very right with big scrollbar and the page displayed as empty and the user have to scroll the bar to right to see the screen (I sent the details on Enterprise PR).

Or it will be a lot of headache and you advice we to wait for v12?
Will your solution be with Bootstrap 3 or you will upgrade to Bootstrap 4 or we should wait for new interface framework?

**Comment by Yenthe666** [comment] 2018-01-02 07:43
@hanyelbanna as for the Bootstrap question: Odoo V12 will use bootstrap 4, V11 should keep Bootstrap V3.

**Comment by mart-e** [comment] 2018-01-02 17:18
Bootstrap v4 does not support RTL either. bootstrap-rtl can be a solution but adding such libraries will definitely be for master.
I am not confident #19892 will lead anywhere so I advise you to wait for v12 instead (where we will migrate to bootstrap v4)

**Comment by Yenthe666** [comment] 2018-05-03 05:56
I guess we can close this report. This will not be changed in a stable Odoo version as it can break a lot of things and is against the policy.
As there is a PR to add support for it in an upcoming version (maybe 12) it might land there, so there is nothing to do here and Odoo is working on it.

**Closed by Yenthe666** 2018-05-03 05:56 UTC
Labels: 11.0, Localization, Need information
