### ISSUE TITLE
Lot Date Incorrect

### ISSUE THREAD

**Issue by gigidn** [odoo/odoo#14941] opened 2017-01-05 09:33 UTC
Impacted versions:

v10 CE - v10 ENT

Steps to reproduce:

Enable LOT/Serial Number
Create a New Lot
Set expire Date to a random date (or other traceability date)
Save the Lot

Current behavior:

The system don't keep the user date expressed on the form

Expected behavior:

The system save the date user insert in the form

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2018-05-05 15:54
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Disclaimer**: I'm not an Odoo employee, but a community member that voluntary contributes to triage / classify / solve issues. Take also into account that there's no obligation to answer nor solving things put in Odoo Community issue tracker. And thus, please consider this as a best effort initiative.

**Closed by pedrobaeza** 2018-05-05 15:54 UTC
Labels: 10.0, Logistics
