### ISSUE TITLE
[13.0] Facing warning twice instead of once (Document layout > Wrong Company logo selection)

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#38002] opened 2019-10-05 09:27 UTC
Impacted versions:

Steps to reproduce:
- Settings > general settings 
- Section Document Layout ,
- Click on Configure Document layout,
- Select Company logo > Select Any other file. e.g .pdf etc.

Current behavior:
- Its showing two warning messages for same thing. (Could not display the selected image)

Expected behavior:
- It should throw only once. Like its working fine in V12 .

Video/Screenshot link (optional):

For ref i checked on following instance :

[V13](http://640993-13-0-a0605e.runbot19.odoo.com/web?debug=1#id=&action=99&model=res.config.settings&view_type=form&cids=1&menu_id=4)

v12 : working fine.instance i checked is :
[V12](http://640946-12-0-e6d269.runbot21.odoo.com/web?debug#id=&action=116&model=res.config.settings&view_type=form&menu_id=4)

**Comment by KapilPatel-KP** [comment] 2019-10-05 14:59
Adding screenshot for reference

![Screenshot from 2019-10-05 20-11-23](https://user-images.githubusercontent.com/24518821/66256754-bea01a00-e7ae-11e9-969d-cc10f421f208.png)

**Comment by sswapnesh** [comment] 2019-10-05 21:20
This seems expected behaviour to me as the same Image (Company Logo) is also used in preview_logo also, Which triggers the same warning twice.


![Screenshot (10)](https://user-images.githubusercontent.com/16624719/66260970-57508d00-e7e3-11e9-8292-bfc1acdcc0d9.png)

**Comment by Yenthe666** [comment] 2020-05-13 12:04
I'm going to close this one since it is just a small pop-up error and what @sswapnesh says is true. A very small improvement could be to only accept specific file types I guess but it is nothing big.

**Closed by Yenthe666** 2020-05-13 12:04 UTC
Labels: 13.0, Framework
