### ISSUE TITLE
[13.0] Selection field values are case-insensitive

### ISSUE THREAD

**Issue by kenneth-vkd** [odoo/odoo#43323] opened 2020-01-15 09:34 UTC
Impacted versions:
13.0
Steps to reproduce:
Create a module where fields.Selection is used and the selection values are made and use case sensitive values.
Fx create this:
```
class PosCardTerminalTransaction(models.Model):
    _name = 'pos.card_terminal.transaction'
    pos_order_id = fields.Many2one('pos.order')
    transaction_mode = fields.Selection(selection=[('a','Offline PIN'),('A','Online PIN'),('@','Signature verified')])
```
Current behavior:
Duplicate records are created for both `a` and `A` options, so that these would be created as `a` and therefore be the same.
This previously worked on Odoo 12.0 and below and seems to be caused by changing `selection` to `selection_ids` on the `ir.models.fields` model

Expected behavior:
It would be expected that selection options are read, created and handled as case sensitive, just like previous versions of Odoo

**Comment by Elkasitu** [comment] 2020-01-15 12:23
Hi,

I can confirm the bug and I'm currently working on a fix, however this fix is only possible for master as changing the schema of XMLIDs is dangerous in a stable version (potential data corruption / loss).

So we will consider this a limitation of the ORM up to the next feature freeze (saas-13.2)

**Comment by kenneth-vkd** [comment] 2020-01-15 12:26
Hi
Thank you for the quick response.
So a fix will be provided for Odoo 13, but at a later state. Do you have any idea on when 13.2 will be released, as the bug is currently preventing usage of Odoo 13 with some larger national systems where we have to integrate

**Comment by Yenthe666** [comment] 2020-01-15 13:19
@kenneth-vkd 13.2 is not equal to V13. A fix made in 13.2 (for the SaaS version) will not come back into 13.0 as it breaks the stable policies so this will not be fixed in V13 but in the upcoming V14.
@Elkasitu correct me if I'm wrong ;)

**Comment by Elkasitu** [comment] 2020-01-15 14:51
saas-13.2 should be released around the first week of February, but like @Yenthe666 said it's basically a standalone version, it is not v13, it is a transition from v13 to v14.

The only way (to my knowledge) in which you could benefit from this fix is if you self-host Odoo, otherwise you'll have to wait until v14 if you're on the SaaS / Odoo.sh

**Comment by Yenthe666** [comment] 2020-01-15 14:53
Plus if you self-host you'd need to create a backport of this yourself, it will not be in the source code for V13 by itself.

**Comment by Elkasitu** [comment] 2020-01-15 15:00
@Yenthe666 Yes but I meant he could self-host saas-13.2, I wouldn't recommend manually backporting the fix even in self-hosted instances, the risk is the same... The reason why the fix should only be done in master is because it works with new DBs but not existing ones, unless a proper migration script is applied (which we'll have to do when migrating DBs from 13 to 13.2)

**Comment by Yenthe666** [comment] 2020-01-15 15:03
You'd be insane to follow the saas-x flow on a local instance too as you're basically following the SaaS flow without having the migration scripts for it ;)

**Comment by kenneth-vkd** [comment] 2020-01-15 15:17
Seems like we then wait until a fix is provided for saas-13.2 (future version 14.0) and then backport the changes to stable Odoo 13.0 and apply the backport manually to any installations where the fix is required.
We currently only support one customer running on Odoo.sh. All other customers are on our hosting or self-hosted
As @Yenthe666 said, it would no unwise to follow saas-x.x branches without having the same upgrade scripts as Odoo uses for SaaS customers

**Comment by Elkasitu** [comment] 2020-01-16 09:24
@kenneth-vkd We're currently discussing whether this should be a valid use-case or not before applying my patch at #43354

Can you explain why do you need the key to be case-sensitive? Is it just because of migration ease from 12.0 to 13.0? The key for selection fields are for internal reference only, the only thing that should be important is the label.

It was not an intended change from 12.0 to 13.0 but it was the product of a heavy refactoring of Selection fields since they had many other, more impactful problems but I fail to see why it would be a problem other than conveniency.

The problem is not whether we can "fix" the behaviour to be like 12.0 or not, but whether it is worth the effort is complexifying migrations from 13.0 to 14.0, so we're debating whether this should be a legit use-case or throw a warning if it happens

**Comment by kenneth-vkd** [comment] 2020-01-16 10:10
@Elkasitu 
the issue is related to certain larger national systems here in Denmark, where we are sending a recieving either API calls or files, where one or more fields only contain a single character, like shown in the example.
Many of these systems are over 20 years old and implemented an a lot of smaller and larger systems. This makes it hard to change the behavior.
When initially developing custom modules for Odoo in order to integrate with these systems, we set the key of the selection field options to match the raw value used by these systems. This worked fine in Odoo 10, Odoo 11 and Odoo 12.
In order to migrate these modules to Odoo 13, a layer in between would essentially have to be made for translating the raw case-sensitive values used with these external systems into a different case-insensitive values.
Surely there must be others who have similar issues

**Comment by C3POdoo** [comment] 2023-03-30 11:43
Dear @kenneth-vkd,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._

**Closed by C3POdoo** 2023-03-30 11:43 UTC
Labels: ORM, 13.0
