### ISSUE TITLE
8.0 stability test passed, looks great, required small res_partner patch in my env, will retest 

### ISSUE THREAD

**Issue by royaladmin** [odoo/odoo#2844] opened 2014-10-01 20:09 UTC
Odoo 8.0 is very impressive.  So was 7.0.  So was 6.1.  That's where I started.
With the announcement that 8.0 is stable, I refreshed with a new git clone and checkout 8.0.

I had to make a patch to get databases to create and to get into the panel, both of which are now working and our team will continue with stability testing.  Making such a patch is like chopping with a machete.  I think I may just not have received the correct res_partner.py or something with my checkout.

I did feel I should share what I did.

During database creation I noticed res_partner.py both in def write and def create using your new api to call BaseModel.write via super(res_partner, self).write() and BaseModel.create via super(res_partner, self).create().

I also noticed the old api being selected by your decoration mechanism, with fatal errors in the log about wrong argument counts.

So in the interest of creating a database and seeing the new panel, since I have a whole team of people waiting with baited breath, I Googled about python decorators and took out my machete:
  - changed openerp/models.py from having this:
@api.multi
def write(self, vals):
  ...

instead to this:
def new_write(self, vals):
  ...
write = api.multi( new_write )

similarly changed this:
@api.model
@api.returns('self', lambda value: value.id)
def create(self, vals):
  ...

to this:
def new_create(self, vals):
  ...
create = api.model( api.returns('self', lambda value: value.id)( new_create ) )

And then in res_partner.py, changed the super(res_partner, self).write and .create
to use .new_write and .new_create instead, for def write and def create respectively.

In went the database.  Up came the panel.

Looks like someone even adjusted the icons.  Everything seems to pop.  Very nice.

On behalf of the administration and members of the Inter Dimensional Space Port, let me send our gratitude for the apparently 12,500 (!) person days that have gone into this 8.0 release.

I am certainly in favor of replacing my hack job with a more appropriate setup,
and I'm looking forward to some guidance as to what that setup should be.

Jim
...
# thanks to Google...
# thanks to http://simeonfranklin.com/blog/2012/jul/1/python-decorators-in-12-steps/
# thanks to http://thadeusb.com/weblog/2010/8/23/python_multiple_decorators
# thanks to http://www.artima.com/weblogs/viewpost.jsp?thread=240845
# thanks to http://stackoverflow.com/questions/5929107/python-decorators-with-parameters

**Comment by mart-e** [comment] 2015-01-27 11:13
Thank you for your message.

If I understand correctly your issue, you got error when you surcharge write and create in your module with the new api syntax ? You are indeed probably missing a decorator. In your module, it should be enough with:
```
@api.multi
def write(self, vals):
```

Check the [backend tutorial](https://www.odoo.com/documentation/8.0/howtos/backend.html) for some examples to develop with the new syntax and also the [Compatibility between new API and old API](https://www.odoo.com/documentation/8.0/reference/orm.html#compatibility-between-new-api-and-old-api)  or [Method decorators](https://www.odoo.com/documentation/8.0/reference/orm.html#module-openerp.api) pages.

I am closing this as it's not a bug report. For more help on your development try the forum, mailing lists or contact the support team.

Regards

**Closed by mart-e** 2015-01-27 11:13 UTC
