### ISSUE TITLE
[9.0]Email Calendar meeting links going to blank Pages

### ISSUE THREAD

**Issue by slevenhagen** [odoo/odoo#9494] opened 2015-11-09 14:12 UTC
Version ODOO 9.0 enterprise and community versions

The links Accept, Decline and View links found in Odoo calendar meeting confirmation emails  go to a blank page but  Meeting status is updated is working.

I've made sure to be logged out of system  when attempting to use these emailed links meeting update links to avoid errors for attempting to access to meeting logged in as incorrect user.

**Comment by ravishekharco** [comment] 2016-01-12 19:23
I have having the exact same issue with Odoo 9 Community Builds

**Comment by pedrobaeza** [comment] 2018-04-10 00:41
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue. This in concrete was something that I suffered in the past until it got solved.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-04-10 00:41 UTC
Labels: 9.0, Services
