### ISSUE TITLE
Portal documents list

### ISSUE THREAD

**Issue by NICO-SOLUTIONS** [odoo/odoo#62858] opened 2020-12-04 08:07 UTC
Impacted versions: Odoo V14 CE

Steps to reproduce:
- grant portal acess to a user

Current behavior:
- When the user enters the documents page in the portal, the complete list of categories is listed. 

Expected behavior:
- In fewer versions, only the categories with an entry-value>0 were listed, which gives a better overview. I dont know if it was the goal to show the complete list. On my opinion it is more user friendly by showing only the categories that are relevant.

**Comment by pedrobaeza** [comment] 2020-12-04 08:15
Which documents page are you talking about?

**Comment by pedrobaeza** [comment] 2020-12-04 08:17
OK, re-reading, you mean orders, invoices, and so on, so yes, this is intended and it's very subjective, but Odoo has changed this and know all the possible sections are shown, even if they contain 0 records.

Closing then as expected behavior.

**Closed by pedrobaeza** 2020-12-04 08:17 UTC

**Comment by NICO-SOLUTIONS** [comment] 2020-12-04 08:25
Thanks for clarifying...

**Comment by pedrobaeza** [comment] 2020-12-04 08:27
Take into account that the contrary behavior (not showing then), can lead to doubts about the feature being missing, so that can be one of the reasons why Odoo has changed this.

**Comment by NICO-SOLUTIONS** [comment] 2020-12-04 08:31
Yes it makes sense on one hand. On the other hand the portal users will see the features not used. This can be confusing as well. But ok. It was just something I noticed. This is just a small optical issue. I am ok with that.

All the best
