### ISSUE TITLE
[12.0][BUG] Required fields are not checked before create() method server side

### ISSUE THREAD

**Issue by ddzopenforce** [odoo/odoo#58892] opened 2020-09-30 13:50 UTC
Impacted versions: 12.0

Steps to reproduce: Create a module that uses website_form and desn't set the class `o_website_form_input` for some required input field.
If you doesn't set this class the JS check is skipped and server side this check doesn't recognize missing required
https://github.com/odoo/odoo/blob/12.0/addons/website_form/controllers/main.py#L183

Current behavior: Missing fields show an error when create() start, but if the `not null` attribute is not set at DB level (because some olds records don't this field properly set) no error is shown and records gets created

Expected behavior: Show error to client side if required field is not set by checking it server side too (not only client side)

Video/Screenshot link (optional):

This line:
https://github.com/odoo/odoo/blob/12.0/addons/website_form/controllers/main.py#L183
check only if error_fields have some record, if yes include inside ValidationError `error_fields` and `missing_required_fields`

If only `missing_required_fields` exists no error is raised so there isn't a real check for missing fields before `create()` method

If I can suggest a simple solution this advice user before `create()` method, just change this:
https://github.com/odoo/odoo/blob/12.0/addons/website_form/controllers/main.py#L182

```
....

missing_required_fields = [label for label, field in authorized_fields.items() if field['required'] and not label in data['record']]
        if any(error_fields):
            raise ValidationError(error_fields + missing_required_fields)

....
```

with this:

```
missing_required_fields = [label for label, field in authorized_fields.items() if field['required'] and not label in data['record']]
all_errors = error_fields + missing_required_fields
        if any(all_errors):
            raise ValidationError(all_errors)
```
So ValidationError get raised if only `missing_required_fields` exists too

A good improvement can be to add a specific MissingRequiredError error that will be raised only for missing_required_fields and when caught show to the client-side the Label of related fields that are missings

```
missing_required_fields = [label for label, field in authorized_fields.items() if field['required'] and not label in data['record']]
if any(missing_required_fields):
    raise MissingRequiredError(missing_required_fields)
if any(error_fields):
    raise ValidationError(error_fields)
```

**Comment by pedrobaeza** [comment] 2020-09-30 14:13
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on. You can also provide a PR for improving current situation, but always on master branch.

**Closed by pedrobaeza** 2020-09-30 14:13 UTC
