### ISSUE TITLE
odoo12 Error: Uncaught TypeError: Cannot read property 'actionID' of undefined

### ISSUE THREAD

**Issue by talway** [odoo/odoo#29201] opened 2018-12-02 06:11 UTC
Impacted versions:
odoo12 (20181202) Community version

Steps to reproduce:
1.use  https://github.com/Yenthe666/InstallScript  ;install;
2.Create databases and users

Current behavior:
1、use user and pass,http://117.50.42.212:8069/web
2、Prompt error

Expected behavior:

Video/Screenshot link (optional):

Error:
Uncaught TypeError: Cannot read property 'actionID' of undefined

http://117.50.42.212:8069/web/content/354-cfecdf3/web.assets_backend.js:860
Traceback:
TypeError: Cannot read property 'actionID' of undefined
    at Class._setActiveApp (http://117.50.42.212:8069/web/content/354-cfecdf3/web.assets_backend.js:860:874)
    at Class._openApp (http://117.50.42.212:8069/web/content/354-cfecdf3/web.assets_backend.js:860:616)
    at Class.openFirstApp (http://117.50.42.212:8069/web/content/354-cfecdf3/web.assets_backend.js:860:567)
    at Class.openFirstApp (http://117.50.42.212:8069/web/content/354-cfecdf3/web.assets_backend.js:856:127)
    at Object.<anonymous> (http://117.50.42.212:8069/web/content/354-cfecdf3/web.assets_backend.js:564:531)
    at Object.<anonymous> (http://117.50.42.212:8069/web/content/353-a3169d1/web.assets_common.js:802:681)
    at fire (http://117.50.42.212:8069/web/content/353-a3169d1/web.assets_common.js:796:299)
    at Object.fireWith [as resolveWith] (http://117.50.42.212:8069/web/content/353-a3169d1/web.assets_common.js:801:198)
    at Object.deferred.(anonymous function) [as resolve] (http://117.50.42.212:8069/web/content/353-a3169d1/web.assets_common.js:803:56)
    at Object.<anonymous> (http://117.50.42.212:8069/web/content/353-a3169d1/web.assets_common.js:3587:448)

http://117.50.42.212:8069/web
demo:demo

**Comment by talway** [comment] 2018-12-02 06:13
Odoo Client Error
An error occurred

Please use the copy button to report the error to your support service.


Error:
Uncaught TypeError: Cannot read property 'actionID' of undefined

http://117.50.42.212:8069/web/content/354-cfecdf3/web.assets_backend.js:860
Traceback:
TypeError: Cannot read property 'actionID' of undefined
    at Class._setActiveApp (http://117.50.42.212:8069/web/content/354-cfecdf3/web.assets_backend.js:860:874)
    at Class._openApp (http://117.50.42.212:8069/web/content/354-cfecdf3/web.assets_backend.js:860:616)
    at Class.openFirstApp (http://117.50.42.212:8069/web/content/354-cfecdf3/web.assets_backend.js:860:567)
    at Class.openFirstApp (http://117.50.42.212:8069/web/content/354-cfecdf3/web.assets_backend.js:856:127)
    at Object.<anonymous> (http://117.50.42.212:8069/web/content/354-cfecdf3/web.assets_backend.js:564:531)
    at Object.<anonymous> (http://117.50.42.212:8069/web/content/353-a3169d1/web.assets_common.js:802:681)
    at fire (http://117.50.42.212:8069/web/content/353-a3169d1/web.assets_common.js:796:299)
    at Object.fireWith [as resolveWith] (http://117.50.42.212:8069/web/content/353-a3169d1/web.assets_common.js:801:198)
    at Object.deferred.(anonymous function) [as resolve] (http://117.50.42.212:8069/web/content/353-a3169d1/web.assets_common.js:803:56)
    at Object.<anonymous> (http://117.50.42.212:8069/web/content/353-a3169d1/web.assets_common.js:3587:448)

**Comment by talway** [comment] 2018-12-02 06:36
An error occurred after logging in, unable to enter the system
![2222](https://user-images.githubusercontent.com/10338638/49336565-8f28fa00-f63f-11e8-86e2-1855635680bd.gif)

**Comment by pedrobaeza** [comment] 2018-12-02 11:40
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Yenthe666** [comment] 2019-01-28 12:52
Hi,

I'm closing this bug report as there has been no feedback or reproducable steps.
We assume your issue has been solved in the meanwhile.

Regards,
Yenthe

**Closed by Yenthe666** 2019-01-28 12:52 UTC
Labels: Need information
