### ISSUE TITLE
[11.0C, 12.0C] CRM: Adding salesperson to second sales channel removes salesperson from first

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#30932] opened 2019-02-07 17:16 UTC
Impacted versions: 11.0, 12.0 (community only)

Steps to reproduce:
1. Login to the latest runbot 11.0 or 12.0
2. Go to CRM > Configuration > Sales channels and open up the record "Europe". You will see the "Administrator" is in there
3. Open up another sales channel and add the "Administrator" to it
4. Go back to the "Europe" sales channel, the administrator is now automatically removed.

Current behavior:
The sales person is automatically removed from the previous sales channel if you add him/her to another channel.

Expected behavior:
The sales person is not automatically removed from the previous channel (without you noticing). You should get a warning or be able to add a sales person to multiple sales channels, just like you can in the enterprise version.
I know being able to add a salesperson to one channel is made by design, in the code, but it is real magic that your salesperson is removed from another sales channel without you ever noticing.

**Comment by sswapnesh** [comment] 2019-02-07 17:32
However it is same since v8.
Related to https://github.com/odoo/odoo/issues/15557 and 
https://www.odoo.com/forum/help-1/question/odoo-10-how-to-assign-a-user-in-two-sales-teams-simultaneously-114971

+1 if we can get similar in community or at-least some notification.

**Comment by Yenthe666** [comment] 2019-02-07 17:39
Thanks for the links @sswapnesh! I honestly think that just a notification is enough, just so you know it happens.

**Comment by Yenthe666** [comment] 2019-02-08 09:53
This is by the way flawed in multiple ways.
You can only add a salesperson to one sales team as it is automatically deleted in the second team. What if I have a salesperson that works in multiple sales teams? In this case I can't do it. So let us say I don't add the salesperson to any teams and just set the sales team on the lead manually.
Well, you can't by default. This code prevents it and will even change and save the salesteam that you've manually set:
https://github.com/odoo/odoo/blob/a02e2778172f7de54cca58babb26151030b5b9dc/addons/crm/models/crm_lead.py#L236-L252

**Comment by Yenthe666** [comment] 2019-02-08 09:56
@tde-banana-odoo could you please look into this and come with a solution? It has been around ever since V8.

**Comment by rafaelbn** [comment] 2019-03-29 19:12
@Yenthe666 this also apply to EE

**Comment by treviser** [comment] 2019-05-18 07:39
<rant on>
This is one of several restrictions by design I will never understand. They are not necessary from a conceptional data modeling perspective nor from a business perspective. They are a true PITA especially for small enterprises. Same is the constraint on bank accounts per partner, which does not allow married couples in family businesses to pay their salary to the same bank account.
And no, I do not buy any of these contorted justifications I heard so far. To me it is meaningless, noxious and unnecessary.
</rant off>

**Comment by Yenthe666** [comment] 2019-05-18 07:42
I just think it should be changed in master so it will atleast be more dynamic from V13 and on :)

**Comment by treviser** [comment] 2019-05-18 07:46
And no, I do not need notifications about it, my cardiologist has forbidden it :-)

**Comment by treviser** [comment] 2019-05-18 09:27
Just for the sake of completeness: here is the one with the bank accounts: https://github.com/odoo/odoo/issues/15636
@Yenthe666 Maybe we should try to reopen that one also in the same context?

**Comment by Yenthe666** [comment] 2019-12-08 16:47
@mart-e so what do you guys think about this? It would be great if we got an official statement.

**Comment by tde-banana-odoo** [comment] 2019-12-09 09:04
Hello,

Good news, we are working on this in master. We finally get rid of the hard "mono-sales team" constraint (unless you install website_crm_score which is not the easiest module to handle). This is still an ongoing task with no ETA. Here are the main ideas: basically in crm you can choose between single-sales team or multi sales team for sales people, with warnings when you try to change someone's sales team in mono sales team mode. It will be integrated with automatic lead assignation based on PLS.

Cheers,

Thibault.

**Comment by Yenthe666** [comment] 2019-12-09 10:13
🎉 wooh, awesome! Would you like to close this off as it'll be handled in the upcoming V14 and you guys probably have an internal task?

**Closed** 2019-12-09 10:14 UTC
Labels: 11.0, 12.0, Services
