### ISSUE TITLE
Product variant value price extra is ignored with an extra price

### ISSUE THREAD

**Issue by paulius-sladkevicius** [odoo/odoo#55834] opened 2020-08-13 06:51 UTC
Impacted versions: 

- 13.0
- 12.0
- Could be and older ones

Steps to reproduce:

Tested on the latest runbot.

1. Add to the "Customizable Desk (CONFIG)" product "Extra Price" (Price Rule) for the 
"Customizable Desk (CONFIG) (Aluminium, White)" variant and set it to 1000.00 USD.
2. Open e-commerce and choose Aliuminium and White attributes

Current behavior:

- The final price is set to 1000.00 USD for e-commerce and sales orders

Expected behavior:

- The final price is set to 1050.40 USD for e-commerce and sales orders

Video/Screenshot link (optional):

![2020-08-13 09-46](https://user-images.githubusercontent.com/213811/90102758-f7533d00-dd49-11ea-997e-bf82c8a2f741.gif)

**Comment by rdeodoo** [comment] 2020-11-05 17:38
Hello, thank you for reporting.

That's the way it is intended to work, if you set a price in your pricelist (price rules), that price will be used and prevail on product attribute value's extra price.
Put in another way:
- my product cost 500€
- when black is selected, I want to add 50€ on top of the price (product attribute value extra price)
- but when 32Go black is selected, I want the price of that product variant to be 300€

The price for the 32Go black iphone will (and should) be 300€, ignoring the extra price of the black attribute.

About the badge '+XX€' next to the attribute value, it shows the extra price set for that attribute value, that might be ignored in favor of the fixed price for that variant in the pricelist, as explained.

> Expected behavior:
The final price is set to 1050.40 USD for e-commerce and sales orders

So, the answer is no.

Does that answer your question?

**Comment by paulius-sladkevicius** [comment] 2020-11-05 18:32
Thank you for your answer. I understand that it was intended, but this should be considered UX bug that a label +XX€ is showing when there is specific price. This leads user to misunderstanding how extra is added (while it is ignored).

**Comment by rdeodoo** [comment] 2020-11-06 11:19
The issue would be the opposite if we were to hide the label, there would still be a misunderstanding for the user as the badge would not be shown but the product would cost 150 more with the fixed price.
And in that case, it is simply impossible to know how much the badge should show. It is +150, but where do we display those +150 ? On attribute 1, on attribute 2? We split ? There is no functional solution for that case, as the +150 comes from a variant fixed price, so a combination of attributes.

Real case:
- my product cost 500€
- when black is selected, I want to add 50€ on top of the price (product attribute value extra price)
- but when 32Go black is selected, I want the price of that product variant to be 800€
- the user has selected 32Go white, when he will click on black, the price will be 800, which is +300 from product price
- where do we display those +300, on "black" badge, on "32Go" badge ? we split ? the answer is we can't show the fixed price difference in badge in attribute grid.

For such cases, when there is a mixed of attribute extra price and variant fixed price, I would probably consider using the variant list instead of attribute gird in ecommerce.

cc @sbuhl

**Comment by pedrobaeza** [comment] 2020-11-06 11:26
What about simply putting a label "With extra cost" or similar in that cases?

**Comment by rdeodoo** [comment] 2020-11-06 11:46
![image](https://user-images.githubusercontent.com/30048408/98362247-2ddce300-202d-11eb-9ad8-985200820719.png)

When I will click on black, the price will be a fixed price of 1.000 for the Aluminium-Black variant.

At the step of the screenshot, what woud you expect, to show "With extra cost" on both Aluminium AND Black attribute values? Because when black will be clicked, both Aluminium and Black badges will be irrelevant.
It wouldn't make sense to show With extra cost (instead of extra cost amount) if the user just click "Steel" at that point, we don't know if he is going to select something that is a fixed price or something else.

If you want to add that label once the fixed price variant has been selected, it doesn't fix anything since you still saw wrong badge value before clicking on it.

**Comment by pedrobaeza** [comment] 2020-11-06 11:49
Yeah, right, it's not easy choice to get a balanced display against features. In this convoluted case, I would fix all the variant prices by pricelist, and don't add extra prices per attribute value, and thus you don't have any tag, and only different prices are displayed when the combination is selected.

Thanks for this constructive debate :smiley:

**Comment by rdeodoo** [comment] 2020-11-06 11:55
@pedrobaeza Always a pleasure.
This one has been discussed so many times at the office, at first the 'unsolvable' part (nothing is but you got the point) of the issue is hard to get but it really is a headache to fit all possible configuration/flow/cases, and solving an inconsistency would just create a new one.

What you suggest is indeed a possible workaround if the 'issue' is really annoying you. If the configuration allows you, you could also switch from attribute grid selection to variant list selection.

At the end it is not something we will think about as it only happens when you mix attribute extra price + pricelist fixed price and display attribute grid mode in ecommerce.

So, I will close this one.

**Closed by rdeodoo** 2020-11-06 11:55 UTC
Labels: 12.0, 13.0, Website

**Comment by paulius-sladkevicius** [comment] 2020-11-06 14:21
@rdeodoo I would go with @pedrobaeza solution and restrict such combinations and then you will save many headache by trying solve this combinations (fix in it master?) However, for our scenario that requires mix them we did solution/workaround, but it covers only this case and can't be contributed.

Pity that it's closed, however happy that you looked to it while official support did much worse and almost ignored it by saying it works :-)

**Comment by rdeodoo** [comment] 2020-11-06 15:21
@paulius-sladkevicius I think @pedrobaeza was thinking about how he would make a workaround for this specific case if it was his database, not about a fix in Odoo codebase

> Pity that it's closed, however happy that you looked to it while official support did much worse and almost ignored it by saying it works :-)

We try to care about github issues and reply to all of them (sometimes very late I admit), especially in website.
And for this one, indeed I think there is an user experience issue for this specific case (extra price + fixed price + attribute grid view), but since it is a specific case with no functional solution for now, I closed it.

**Comment by pedrobaeza** [comment] 2020-11-06 15:26
Yes, I commented for a possible workaround if it would be my case. I don't see either an issue that can be fixed "in master" for this case, and adding constraints Odoo for avoiding this combination doesn't add too much value as well. I agree on closing it.
