### ISSUE TITLE
Warning: It is not possible to unreserve more products than you have in stock.

### ISSUE THREAD

**Issue by vishwanathchannagiri** [odoo/odoo#49274] opened 2020-04-09 07:44 UTC
Impacted versions: 
odoo 12.0

Steps to reproduce:
This warning message is popping up in some places of Internal transfers, We are doing internal transfers from the different features example Material Transfers, Manufacturing material replenishment, etc.,

Current behavior:
System displaying this warning message even the stock available at the source location without reserving the stock to other pickings basically free stock is available even though this warning message is popping up

Expected behavior:
If someone helps me to understand this warning message and provide me the solution because stock available then also this warning coming up

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2020-04-09 07:50
This is a "desynchronization" between reserved quantities and the quantity to release. It can be motivated due to chained moves that are altered some way, but in theory nothing wrong about the code. If you don't provide detailed steps to reproduce it, it can't be considered as a bug, so closing meanwhile.

**Closed by pedrobaeza** 2020-04-09 07:50 UTC

**Comment by vishwanathchannagiri** [comment] 2020-04-09 08:15
Hi Mr. Pedrobaeza,
For your reference am attaching a video to reproduce the step Please refer to the attached video and help me out in this
In the given instance  onhand qty is 19 and reserver qty is 2 remaining 17 qty is free then also this warning message is popping 
"It is not possible to unreserve more products of [1001205001] Barcode Scanner MJ4209 than you have in stock."

[simplescreenrecorder-2020-04-09_13.38.12.mkv.tar.gz](https://github.com/odoo/odoo/files/4454861/simplescreenrecorder-2020-04-09_13.38.12.mkv.tar.gz)

**Comment by pedrobaeza** [comment] 2020-04-09 08:17
Please reproduce the problem on runbot: http://runbot.odoo.com/runbot (admin/admin in the corresponding slot).
