### ISSUE TITLE
Fails to install on Debian 9 due to missing python-pypdf

### ISSUE THREAD

**Issue by grubshka** [odoo/odoo#17944] opened 2017-06-30 14:28 UTC
Impacted versions:
10

Steps to reproduce:
aptitude install odoo

Current behavior:
 odoo : Dépend: python-pypdf which is a virtual package and is not provided by any available package

Expected behavior:
Installs odoo

**Comment by Yenthe666** [comment] 2017-06-30 14:29
@sle-odoo looks like one for you?

**Comment by odony** [comment] 2017-06-30 15:34
Duplicate of #17002, so closing it ;-)

**Closed by odony** 2017-06-30 15:34 UTC

**Comment by Yenthe666** [comment] 2017-06-30 15:47
Woops I've missed that, although I've responded on both.. Sorry! ;-)

**Comment by zeroheure** [comment] 2018-01-29 19:25
It is very easy to fix the problem by using a fake python-pypdf package. Then install pypdf from pip.
See the complete tutorial on my blog :
http://zeroheure.info/how-to-install-odoo-on-latest-debian-ubuntu-without-python-pypdf-dependency/

**Comment by kholioeg** [comment] 2018-12-09 18:12
Another workaround is to do the following:

`apt-get install python-pypdf2`

`dpkg --ignore-depends=python-pypdf -i odoo_*`
