### ISSUE TITLE
half(SOLVED)If we click on discussion icon, we have restrictions error

### ISSUE THREAD

**Issue by SkiBY** [odoo/odoo#22764] opened 2018-02-02 16:26 UTC
Impacted versions:
11e

Out of nowhere we have error on our production odoo:
If we click on discussion icon, 

![2018-02-02 19 06 56](https://user-images.githubusercontent.com/6535546/35742770-9278526e-084c-11e8-84a4-791ebfcc6c0f.png)

we have error for all(!) users

> The requested operation cannot be completed due to security restrictions. Please contact your system administrator.
> 
> (Document type: mail.message, Operation: read)

We've found this issue on forum:
https://www.odoo.com/forum/help-1/question/messages-not-visible-in-inbox-and-app-wide-mail-message-permission-issues-92618

But base drop is not an option and reactivate user doesn't work.
All access right are the same - we've checked it in models and users.

Logs:

> INFO odoo odoo.models: The requested operation cannot be completed due to record rules: Document type: mail.message, Operation: read, Records: 296,1,451,280,297, User: 9

We haven't message with id 1 in our base. And there are no user, who can delete it directly.

(half)**SOLVED**
Problem was solved with adding new message to 'general' channel(because message with id 1 is made there while new installation). So the issue was not the permissions, but "no record"

**Comment by Yenthe666** [comment] 2018-02-05 08:36
Hi @SkiBY,

Thanks a lot for your bug report.
Can you reproduce this on an official Odoo test instance at runbot.odoo.com? Did you find a way to reproduce it? Have you updated your Odoo source code to the latest source?

Regards,
Yenthe

**Comment by Yenthe666** [comment] 2018-03-19 09:41
Closing as there has been no feedback on this issue.

**Closed by Yenthe666** 2018-03-19 09:41 UTC
Labels: 11.0, Need information

**Comment by grivalta** [comment] 2019-03-19 11:06
@SkiBY  your suggestion ((half)SOLVED
Problem was solved with adding new message to 'general' channel(because message with id 1 is made there while new installation). So the issue was not the permissions, but "no record") is ok.
Thanks...
