### ISSUE TITLE
[12.0] UPS : Not able to validate the outgoing shipment when use UPS US as delivery method.

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#52416] opened 2020-06-04 10:04 UTC
Impacted versions: [12.0 / 12.0 E]

Steps to reproduce:
- Create any Sale order having Customer with proper address.
- Select Delivery method 'UPS US' , Select Product in SO line, and confirm the SO.
- Try to Validate the Shipment (Outgoing shipment).

Current behavior:
- its raising warning as per the snap shot. even though we use Odoo's default credentials for same purpose.

Expected behavior:
- It should allow to validate the shipment.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/35560490/83743646-a3a4e300-a678-11ea-9cf6-a23fea9be233.png)

I tried on runbot :-

[https://2937783-12-0-5982f4.runbot32.odoo.com/](https://2937783-12-0-5982f4.runbot32.odoo.com/)

Please advise !

**Comment by pedrobaeza** [comment] 2020-06-04 10:17
As that's an enterprise module, please report it to odoo.com/help. Any way, I would say that you can't reproduce it in runbot because the UPS endpoint is not accessible, but not sure about this. Any way, as said, it should be checked by OPW team, so closing.

**Closed by pedrobaeza** 2020-06-04 10:17 UTC
