### ISSUE TITLE
[BUG][10.0][Enterprise and Community] Wrong TAX calculation after changing unit price or discount (#1858633) 

### ISSUE THREAD

**Issue by rafaelbn** [odoo/odoo#25226] opened 2018-06-13 10:49 UTC
Impacted versions: 10.0 Enterprise 10.0 Communiy

Steps to reproduce:

- https://youtu.be/eG3SSFPVVWg 

Current behavior:

- Taxes are wrong calculated

Expected behavior:

- Taxes are right calculated

Video/Screenshot link (optional):

- Check this video: https://youtu.be/eG3SSFPVVWg
- Or this one: https://youtu.be/k00hiRaowVw

OPW 1858633

Commented in the OCA Code Sprint with  @tivisse and  @tde-banana-odoo 

cc @Tecnativa

**Comment by tivisse** [comment] 2018-06-13 12:35
Hi @rafaelbn 

Just a question: Did you manage to reproduce the issue on the runbot ? Because @JKE-be tested it and it seems to work from his side.

Thanks.

**Comment by intero-chz** [comment] 2018-06-14 12:03
I saw enough Odoo 10.0 EE without such wrong tax calculations. Was this "introduced" in newer versions?

**Comment by len-odoo** [comment] 2018-06-22 12:45
Unfortunately this won't be fixed. 
We know that some subtle errors exist in the old JS framework, but there shouldn't remain errors that are a problem in practice.
In that case, there is a simple workaround: re-edit the lines, and click somewhere else before saving.
So this is not ideal, but the old JS suite is not tested, and the risk to introduce new bugs is very high, so it's not worth the risk.

**Closed** 2018-06-26 06:18 UTC
Labels: 10.0, Won't Fix

**Comment by rafaelbn** [comment] 2019-01-11 09:34
@len-odoo @tivisse @tde-banana-odoo ,

opw-1917605 has been attended 

https://github.com/odoo/odoo/commit/b131658966a347ec0058b713610e123347799cd7

https://github.com/odoo/odoo/pull/30021

opw-1917605

My OPW 1858633 is not attended :cry:

**Comment by kebeclibre** [comment] 2019-01-11 10:12
@rafaelbn 
The two issues are not related. This one is a linked to a limitation in the JS framework in 10.0.
As I answered on the opw, the issue doesn't occur in 11.0
The fix you refer to deals with an actual computing issue on the python side
