### ISSUE TITLE
[13.0] sale_coupon: why allow sales order to generate a number of coupons more than maximum number of sales order

### ISSUE THREAD

**Issue by khaihoan123** [odoo/odoo#63618] opened 2020-12-21 08:05 UTC
Impacted versions: 13.0

Current behavior:
- Allow sales order to generate a number of coupons more than maximum number of sales order with  programs applied for next order. we can use them for the  corresponding number of sales order 

Expected behavior:
- Only allow sales order  to create a number of coupons in the 'Valid' state less than or equal to maximum number of sales order for programs applied for next order

Video/Screenshot link (optional):

https://user-images.githubusercontent.com/65581749/102753150-4581e800-439d-11eb-9649-bc8e3bdfe527.mp4

**Comment by royleviindoo** [comment] 2020-12-22 01:55
This is by design, isn't it, @pedrobaeza ?

**Comment by pedrobaeza** [comment] 2020-12-22 07:16
You are misunderstanding the meaning of the sales order limit: the limit is for applying the coupon, not for generating them.

Closing as expected behavior.

**Closed by pedrobaeza** 2020-12-22 07:16 UTC

**Comment by khaihoan123** [comment] 2020-12-22 07:22
> You are misunderstanding the meaning of the sales order limit: the limit is for applying the coupon, not for generating them.
> 
> Closing as expected behavior.

but i still apply a number of coupon more than the limit, that's the problem.

**Comment by pedrobaeza** [comment] 2020-12-22 07:24
I don't see such thing in the video, but applying 2 coupons.

**Comment by khaihoan123** [comment] 2020-12-22 07:30
> I don't see such thing in the video, but applying 2 coupons.

in the end of video, you can see 2 sales orders applied and 'Apply on first' field just has 1 order

**Comment by pedrobaeza** [comment] 2020-12-22 07:31
But with different coupons...

**Comment by khaihoan123** [comment] 2020-12-22 07:33
> But with different coupons...

yes

**Comment by pedrobaeza** [comment] 2020-12-22 07:35
Limit is per coupon, not global.

**Comment by hantt05** [comment] 2020-12-22 08:45
@pedrobaeza 
On promotion, we are setting maximum order is 1. However, as this video, we can apply on 2 order. 
If following your idea "Limit is per coupon, not global", the meaning of field "Apply on First" is not right.
![Selection_164](https://user-images.githubusercontent.com/45425212/102867600-96601200-446b-11eb-8e43-fff6bd4c43fb.png)

**Comment by royleviindoo** [comment] 2020-12-22 08:48
@pedrobaeza Maybe you are misunderstanding
I create a `10% Discount` coupon, with `Apply on First` as `1` and `Applicability` as `Apply On Next Order`.
I create a sale order, apply the above `10% Discount` coupon. Then, 1 coupon code will be generated.
I create another sale order, apply the above `10% Discount` coupon. Then, 1 coupon code will be generated.

This does not match the meaning of `Apply on First` as 1. Because I have applied more than 2 sale orders.
