### ISSUE TITLE
odoo 10 pos error :traceback (most recent call last) / addons/report , in report_download

### ISSUE THREAD

**Issue by mustafaadel125** [odoo/odoo#27999] opened 2018-10-20 19:23 UTC
![img-20181020-wa0000](https://user-images.githubusercontent.com/44326104/47259743-0c007a00-d4bf-11e8-92eb-bc0fa42795cb.jpg)
Impacted versions: v.10

Steps to reproduce:

Current behavior: cant make pos orders

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2018-10-20 19:56
We need more information for understanding the problem. Please try to reproduce the problem on runbot (https://runbot.odoo.com - admin/admin), and put here all the detailed steps to reproduce the problem and even screenshots/video.

**Comment by pedrobaeza** [comment] 2018-10-21 12:05
Please be even more specific, putting all the detailed steps for configuration, master data, etc.

**Comment by switch87** [comment] 2018-10-25 15:52
hi @mustafaadel125 ,

Do you have any customizations? I do not see the User name where it should be? 
Can you reproduce the error on the runbot of odoo 10 as @pedrobaeza sugested?

**Comment by switch87** [comment] 2018-11-15 23:32
@mustafaadel125,

I am closing this issue due to lack of information. It can be reopened if you respond to our comments.

**Closed by switch87** 2018-11-15 23:32 UTC
Labels: 10.0, Need information
