### ISSUE TITLE
Change timezone − User image too big

### ISSUE THREAD

**Issue by qtheuret** [odoo/odoo#1627] opened 2014-08-06 13:27 UTC
After an install of odoo (commit d71a21bfdb25b6db942d82830788cc165db7c844), there is a warning icon that say you your timezone is not correct.
If you click on this icon, the user preferences page is displayed and allow you to choose a timezone, but if you click on the down arrow on the right of the field to open the list of options, it opens the file selection dialog box and if you choose an image, the user avatar is updated with this image.

I think it's a little problem with CSS.

**Comment by Yenthe666** [comment] 2017-08-28 14:16
Hi @qtheuret,

Thanks a lot for your report. At this point the issue can no longer be reproduced and everything works fine now.
Closing this because it is no longer reproducable.

Regards,
Yenthe

**Closed by Yenthe666** 2017-08-28 14:16 UTC
