### ISSUE TITLE
onchange error

### ISSUE THREAD

**Issue by SnailZSJ** [odoo/odoo#52943] opened 2020-06-13 11:17 UTC
After an error is thrown in the onchange function, the display value of the field on the interface is inconsistent with the cache value.

Impacted versions: 
odoo13

Steps to reproduce:
There are start_time and end_time fields on the page. When these two fields are changed, the program enters the onChange function to check whether the start time is earlier than the end time.If the check does not pass, the program will actively raise error.

1. before change:
start_time = 09:00
end_time = 20:00

2. change end_time to 08:00，then get raise error msg.

3. At this point, the interface is shown as:
start_time = 09:00
end_time = 08:00

4. change start_time to 10:00，The value passed to the onchange function is:
start_time = 10:00
end_time = 20:00

5. However, the value displayed on the interface at this time is:
start_time = 10:00
end_time = 08:00

Current behavior:

Expected behavior:
I expect the values displayed on the interface to be the same as the cached values.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2020-06-14 17:22
That's because you shouldn't raise an exception in onchanges, but returning a warning in the dictionary. Raising an exception leads to inconsistent data like yours.

Closing as expected behavior.

**Closed by pedrobaeza** 2020-06-14 17:22 UTC
