### ISSUE TITLE
[10.0] [Accounting] No taxes showing up after installing SKR3

### ISSUE THREAD

**Issue by doomguy** [odoo/odoo#15932] opened 2017-03-19 21:31 UTC
Impacted versions: Odoo 10.0-20170207 (Community Edition) docker image

Steps to reproduce: Install "Deutscher Kontenplan SKR03", try to activate the template and check for installed taxes.

Current behavior: Taxes not showing up. I also can't activate the SKR03 template. After saving it will just drop to discussion without any changes.

Expected behavior: There should be taxes and an activated SKR03 template.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2018-05-22 08:10
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-05-22 08:10 UTC
Labels: 10.0, Accounting
