### ISSUE TITLE
how to add the debit and credits accounts in the salary structure section in odoo10 ?

### ISSUE THREAD

**Issue by ameen760760** [odoo/odoo#17932] opened 2017-06-30 07:17 UTC
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment] 2017-06-30 14:09
Hi @ameen760760,

The Github issue tracker is only for bugs in the official code.
This is not used to ask questions, we have the official Odoo Help forums for this (http://odoo.com/help).
I'm closing this as it is not a bug (plus there is very little information too)

Regards,
Yenthe

**Closed by Yenthe666** 2017-06-30 14:09 UTC
