### ISSUE TITLE
Error when a stock.production.lot is created in stock.move.line

### ISSUE THREAD

**Issue by dorcyv** [odoo/odoo#29462] opened 2018-12-12 10:55 UTC
Impacted versions:
12.0

Steps to reproduce:
Go to receipt and split a reception into two line with the same lot and a different package and click to validate.
![capture d ecran du 2018-12-12 11-45-09](https://user-images.githubusercontent.com/13641281/49864964-f4c97300-fe03-11e8-95b1-959de6b989e9.png)
 
This sql contrait is raise:
```
_sql_constraints = [
        ('name_ref_uniq', 'unique (name, product_id)', 'The combination of serial number and product must be unique !'),
    ]
``` 
(stock_production_lot.py in line 26 of the module stock)

The bug is introduce (I think) in the stock_move_line, line 393 of the stock module in case of lot managment (and not serial). 
```python
if ml.lot_name and not ml.lot_id:
    lot = self.env['stock.production.lot'].create(
        {'name': ml.lot_name, 'product_id': ml.product_id.id}
    )
    ml.write({'lot_id': lot.id})
```

We need to search any stock.production.lot before create it in the case of the lot is already created by a previous line in this case

**Comment by pedrobaeza** [comment] 2018-12-12 13:23
Hi @dorcyv, you can't use "Create New Lots/Serial Numbers" option if you are going to split the reception into several lines with the same lot. You have to use "Use Existing Lots/Serial Numbers", and create on the fly the lot.

This is this way by design, although I agree it can't be inconvenient. I have already reported something similar, and might be considered for future versions, but for this one, it should be this way.

Closing then by the stated reasons.

**Closed by pedrobaeza** 2018-12-12 13:23 UTC
Labels: 12.0, Logistics
