### ISSUE TITLE
Added Bcc on mail Object, but seems like Bcc shown to all recipients.

### ISSUE THREAD

**Issue by hilarak** [odoo/odoo#23579] opened 2018-03-11 08:25 UTC
Impacted versions:
10
Steps to reproduce:
Added new field bcc on mail objects and do all processing and included in mail functions.
Current behavior:
Bcc hidden recipients were shown to all on Gmail interface
Expected behavior:
Bcc should be hidden
Video/Screenshot link (optional):
https://www.odoo.com/forum/help-1/question/email-bcc-shown-to-all-other-recipients-while-sending-from-odoo-126848

**Comment by sswapnesh** [comment] 2018-03-11 16:51
I can Confirm this behavior too Since v8.

**Comment by sswapnesh** [comment] 2018-03-11 17:59
To test we can add `bcc: 'email'` in https://github.com/odoo/odoo/blob/11.0/addons/mail/models/mail_mail.py#L315
Actually,  `bcc` header should be deleted while sending mail as mentioned here 
https://github.com/python/cpython/blob/3.6/Lib/smtplib.py#L945

**Comment by hilarak** [comment] 2018-03-12 06:57
No, That's wrong bcc will not delete, and we can see the bcc recipients on mail while opening it on Gmail.
We have to process the headder in some other mail functions also, not only on header.

**Comment by sswapnesh** [comment] 2018-03-27 16:18
This has been fixed in commit 2445f9e3c22db810d61996afde883e4ca608f15b.

**Comment by pedrobaeza** [comment] 2018-03-27 16:20
Handled in 2445f9e, so I close.

**Closed by pedrobaeza** 2018-03-27 16:20 UTC
Labels: 10.0, Services
