### ISSUE TITLE
[account] Error in print vendor bill in account.move model.

### ISSUE THREAD

**Issue by aman-webkul** [odoo/odoo#36858] opened 2019-09-13 11:56 UTC
Impacted versions: master Detected Version: V13

Steps to reproduce: https://prnt.sc/p5n8jz

Current behavior: https://prnt.sc/p5n9as

Expected behavior: Its pdf should be download

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2019-09-13 12:00
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by aman-webkul** [comment] 2019-09-13 12:16
Given screenshot were taken from runbot.
There is an error occurred when user open any invoice and try to print **Original vendor bills**.
If there is still any need of screenshots to reproduce that again then i can provide these.

**Comment by Yenthe666** [comment] 2019-09-14 15:42
It is against the master version so we should close it off anyways. Odoo doesn't allow bug reports for the master version.

**Closed by Yenthe666** 2019-09-14 15:42 UTC
Labels: Need information
