### ISSUE TITLE
POS Invoice skips a correlative number everytime a pos session is closed and a new 1 is open

### ISSUE THREAD

**Issue by sibuxiang** [odoo/odoo#14786] opened 2016-12-20 14:26 UTC
Impacted versions: v 9.0c20161219  

Steps to reproduce: Create a pos session and create a sale with invoice close the session and open a new session and create a new sale with invoice. The invoice number will skip a number Ex 11->13
(sequence is configured with no-gap)
Current behavior:

Expected behavior: The correlative number must not skip.

Video/Screenshot link (optional):

![pos correlative gap](https://cloud.githubusercontent.com/assets/13316399/21354115/266c32f6-c69f-11e6-8056-ab79c10ed8cb.png)

**Comment by pedrobaeza** [comment] 2018-05-05 15:48
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Disclaimer**: I'm not an Odoo employee, but a community member that voluntary contributes to triage / classify / solve issues. Take also into account that there's no obligation to answer nor solving things put in Odoo Community issue tracker. And thus, please consider this as a best effort initiative.

**Closed by pedrobaeza** 2018-05-05 15:48 UTC
Labels: 9.0, Point of Sale
