### ISSUE TITLE
Error when use the timesheet analysis dashboard in odoo_8

### ISSUE THREAD

**Issue by milan-thakkar** [odoo/odoo#16344] opened 2017-04-10 12:14 UTC
![timesheet analysis odoo second](https://cloud.githubusercontent.com/assets/13216534/24862278/a6ff0430-1e19-11e7-8fdb-c65f5e261a39.png)
![timesheet analysis odoo-error](https://cloud.githubusercontent.com/assets/13216534/24862286/aa6d9104-1e19-11e7-8890-9f60734f892a.png)

**Comment by Yenthe666** [comment] 2017-04-10 13:26
Hi @milan-acespritech,

Thanks a lot for your report.
I've just tested this and I can confirm that this is an issue:
![image](https://cloud.githubusercontent.com/assets/6352350/24863663/11d06c1c-1e02-11e7-9224-5311e6b8cb28.png)
@mart-e who can look at this?

Regards,
Yenthe

**Comment by milan-acespritech** [comment] 2017-04-19 06:16
@mart-e how much days will it take to solve this?

**Comment by Yenthe666** [comment] 2017-06-14 11:54
@ged-odoo any update on this one?

**Comment by ged-odoo** [comment] 2017-06-14 12:36
@Yenthe666 @milan-acespritech well, I may have been assigned this, but I actually am not in the bug fix team. Maybe @nim-odoo will want to have a look on this. I am overloaded, and give higher priority to PR.

Note that this seems to be a problem with the filter itself, it looks like it tries to add the field time to the measure list, but there is not time field in the model.  I suspect that this should be replaced by 'quantity'.

**Comment by Yenthe666** [comment] 2017-08-28 09:16
@ged-odoo sorry to ping you again - any update on this?

**Comment by mart-e** [comment] 2017-11-09 10:56
Hello,

Thank you for your contribution but the version 8.0 is no longer supported. We only support the last 3 stable versions so no longer accepts patches into this branch.
We apology if we could not find a proper fix in time.

Regards

**Closed by mart-e** 2017-11-09 10:56 UTC
Labels: confirmed
