### ISSUE TITLE
[14.0] Error on trying a sample vendor bill when clicking on the 'First bill' in Accounting dashboard.

### ISSUE THREAD

**Issue by saurabh-cybro** [odoo/odoo#68187] opened 2021-03-22 09:13 UTC
Impacted versions:14.0 - Community and Enterprise

Steps to reproduce:
1. Activate "Show Full Accounting Features" in user settings in debug mode.
2. Go to invoicing>Dashboard and click on the "First Bill" on the on-boarding panel.
3. Select "Try a sample vendor bill" option in the wizard and click continue.

Current behavior:
On Clicking continue button the following error appears,

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/data/build/odoo/odoo/addons/base/models/ir_http.py", line 238, in _dispatch
    result = request.dispatch()
  File "/data/build/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/data/build/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/build/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/build/odoo/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/build/odoo/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/data/build/odoo/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 456, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 443, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/data/build/odoo/addons/account/wizard/account_tour_upload_bill.py", line 70, in apply
    bill.write({
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'dict' object has no attribute 'write'

Expected behavior:
Don't know as it never worked. You can produce this error on runbot. The screenshots attached below are from runbot.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/60174650/111965765-1b66d000-8b1c-11eb-8a01-b4480d482880.png)
![image](https://user-images.githubusercontent.com/60174650/111965824-31749080-8b1c-11eb-832a-d48310568f8e.png)
![image](https://user-images.githubusercontent.com/60174650/111966424-e9a23900-8b1c-11eb-82f7-43bd5880ffcb.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by sswapnesh** [comment] 2021-03-22 16:32
Duplicate of https://github.com/odoo/odoo/issues/66558

**Comment by pedrobaeza** [comment] 2021-03-22 16:37
Closing then.

**Closed by pedrobaeza** 2021-03-22 16:37 UTC
Labels: 14.0, Accounting
