### ISSUE TITLE
[13] website_sale: Traceback due to miss configuration on shop page

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#50707] opened 2020-05-05 19:30 UTC
Impacted versions: 13.0

Reproduced on https://2507894-13-0-8da327.runbot46.odoo.com/shop

Steps to reproduce: On Public Pricelist (or Maybe other) set company which doesn't belong to Website's company
 Open  `/shop`

Current behavior:
![screenshot-localhost_8069-2020 05 06-00_56_59](https://user-images.githubusercontent.com/16624719/81107263-83c4b700-8f34-11ea-90d8-515535129265.png)
```
Traceback (most recent call last):
  File "/data/build/odoo/odoo/models.py", line 5000, in ensure_one
    _id, = self._ids
ValueError: not enough values to unpack (expected 1, got 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/build/odoo/odoo/addons/base/models/qweb.py", line 332, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_website_sale_products_item_931
  File "/data/build/odoo/addons/website_sale_stock/models/product_template.py", line 22, in _get_combination_info
    parent_combination=parent_combination, only_template=only_template)
  File "/data/build/odoo/addons/website_sale/models/product.py", line 298, in _get_combination_info
    has_discounted_price = pricelist.currency_id.compare_amounts(list_price, price) == 1
  File "/data/build/odoo/odoo/addons/base/models/res_currency.py", line 155, in compare_amounts
    self.ensure_one()
  File "/data/build/odoo/odoo/models.py", line 5003, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: res.currency()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/build/odoo/odoo/addons/base/models/ir_http.py", line 229, in _dispatch
    result = request.dispatch()
  File "/data/build/odoo/odoo/http.py", line 809, in dispatch
    r = self._call_function(**self.params)
  File "/data/build/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/build/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/build/odoo/odoo/http.py", line 342, in checked_call
    result.flatten()
  File "/data/build/odoo/odoo/http.py", line 1236, in flatten
    self.response.append(self.render())
  File "/data/build/odoo/odoo/http.py", line 1229, in render
    return env["ir.ui.view"].render_template(self.template, self.qcontext)
  File "/data/build/odoo/odoo/addons/base/models/ir_ui_view.py", line 1177, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/data/build/odoo/addons/website/models/ir_ui_view.py", line 345, in render
    return super(View, self).render(values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/data/build/odoo/addons/web_editor/models/ir_ui_view.py", line 25, in render
    return super(IrUiView, self).render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/data/build/odoo/odoo/addons/base/models/ir_ui_view.py", line 1185, in render
    return self.env[engine].render(self.id, qcontext)
  File "/data/build/odoo/odoo/addons/base/models/ir_qweb.py", line 58, in render
    result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/data/build/odoo/odoo/addons/base/models/qweb.py", line 260, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/data/build/odoo/odoo/addons/base/models/qweb.py", line 334, in _compiled_fn
    raise e
  File "/data/build/odoo/odoo/addons/base/models/qweb.py", line 332, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_website_sale_products_906
  File "<template>", line 2, in body_call_content_904
  File "<template>", line 68, in foreach_900
  File "<template>", line 69, in foreach_899
  File "/data/build/odoo/odoo/addons/base/models/qweb.py", line 339, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.models.qweb.QWebException: Expected singleton: res.currency()
Traceback (most recent call last):
  File "/data/build/odoo/odoo/models.py", line 5000, in ensure_one
    _id, = self._ids
ValueError: not enough values to unpack (expected 1, got 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/build/odoo/odoo/addons/base/models/qweb.py", line 332, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_website_sale_products_item_931
  File "/data/build/odoo/addons/website_sale_stock/models/product_template.py", line 22, in _get_combination_info
    parent_combination=parent_combination, only_template=only_template)
  File "/data/build/odoo/addons/website_sale/models/product.py", line 298, in _get_combination_info
    has_discounted_price = pricelist.currency_id.compare_amounts(list_price, price) == 1
  File "/data/build/odoo/odoo/addons/base/models/res_currency.py", line 155, in compare_amounts
    self.ensure_one()
  File "/data/build/odoo/odoo/models.py", line 5003, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: res.currency()

Error to render compiling AST
ValueError: Expected singleton: res.currency()
Template: website_sale.products_item
Path: /t/t[2]
Node: <t t-set="combination_info" t-value="product._get_combination_info(only_template=True, add_qty=add_qty or 1, pricelist=pricelist)"/>
```

Expected behavior:  miss-configuration should be blocked.

We are already checking similar checks at some places
![screenshot-2507894-13-0-8da327 runbot46 odoo com-2020 05 06-00_57_53](https://user-images.githubusercontent.com/16624719/81107370-b1a9fb80-8f34-11ea-8bce-1fd0456dc677.png)

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2020-05-05 19:35
This is a forced misconfiguration and I think it's not a bug per se. What I'm not sure if this can be prevented through `check_company` attribute. @Feyensv is that possible?

**Comment by sswapnesh** [comment] 2020-05-05 19:41
Maybe this can be prevented by `_check_website_pricelist` which makes sure each website has active  Pricelist within the same company,

I was playing through Multicompany (and this PR https://github.com/odoo/odoo/pull/50704#issuecomment-624240145) and Got this one.

I think `check_company` is to Prevent user to select a record from another company, Not sure If it can help us here.

@JKE-be  What do you think on this one?

**Comment by Feyensv** [comment] 2020-05-06 09:03
Indeed, a change of the `company_id` didn't trigger the check to ensure there is a pricelist available for all websites (https://github.com/odoo/odoo/pull/50721)

**Comment by pedrobaeza** [comment] 2020-05-06 11:31
Thanks! Let's close the issue then as there's the PR.

**Comment by Feyensv** [comment] 2020-05-06 11:42
Next time, let github automatically close the issue when the fix PR is merged ;).

**Comment by pedrobaeza** [comment] 2020-05-06 11:45
Yeah, I practice extreme GTD :stuck_out_tongue: and as not always it's automatically closed (depending on the target branch), I tend to close it and don't let that to the future, but it's true this one would be closed.

**Comment by Yenthe666** [comment] 2020-05-06 12:29
@pedrobaeza you're basically faster than a bot. 😉 I'm going to call you PedroBot.

**Comment by pedrobaeza** [comment] 2020-05-06 12:35
:rofl: others told about "Pedro and its minions" :laughing:

**Comment by sswapnesh** [comment] 2020-05-06 16:58
@Feyensv I just tried the same Steps on Latest Build  (Which contains this fix)  and Still, Issues exists.

Pricelists: https://2522241-13-0-911ada.runbot35.odoo.com/web?#action=251&model=product.pricelist&view_type=list&cids=1%2C2&menu_id=370

Shop: https://2522241-13-0-911ada.runbot35.odoo.com/shop

**Comment by pedrobaeza** [comment] 2020-05-06 17:01
Reopening then...

**Comment by Feyensv** [comment] 2020-05-06 17:27
Ok then, maybe this fix wasn't enough :thinking:.
From a fresh runbot instance, what did you exactly do ? (I suppose the bug I had in local was maybe not exactly the same as yours).

**Comment by sswapnesh** [comment] 2020-05-06 17:37
@Feyensv  I have added a new Patch #50785 Could you please Review ?

> what did you exactly do?
 
> Archive all other Pricelists and Selected **My Company (Chicago)** company on  Public Pricelist
> Go shop

**Comment by rdeodoo** [comment] 2020-11-26 13:24
Fixed with https://github.com/odoo/odoo/pull/50785

**Closed by rdeodoo** 2020-11-26 13:24 UTC
Labels: 13.0
