### ISSUE TITLE
[8.0][Issue] Odoo store function: JSON not serializable

### ISSUE THREAD

**Issue by alca259** [odoo/odoo#4628] opened 2015-01-10 23:20 UTC
Hello, i have problems with update stored data. It's works but later i cannot see it... It say this when i try to view.

Odoo Server Error
Traceback (most recent call last):
  File "D:\Desarrollo\Odoo\Server\server\.\openerp\http.py", line 517, in _handle_exception
  File "D:\Desarrollo\Odoo\Server\server\.\openerp\http.py", line 539, in dispatch
  File "D:\Desarrollo\Odoo\Server\server\.\openerp\http.py", line 506, in _json_response
  File "simplejson\__init__.pyc", line 354, in dumps
  File "simplejson\encoder.pyc", line 264, in encode
  File "simplejson\encoder.pyc", line 612, in _iterencode
  File "simplejson\encoder.pyc", line 568, in _iterencode_dict
  File "simplejson\encoder.pyc", line 568, in _iterencode_dict
  File "simplejson\encoder.pyc", line 568, in _iterencode_dict
  File "simplejson\encoder.pyc", line 568, in _iterencode_dict
  File "simplejson\encoder.pyc", line 455, in _iterencode_list
  File "simplejson\encoder.pyc", line 622, in _iterencode
  File "simplejson\encoder.pyc", line 239, in default
TypeError: <function _get_lines at 0x0603C7F0> is not JSON serializable

This is my code

    from openerp import models, fields, api, _, exceptions
    class account_analytic_account(models.Model):

        _inherit = 'account.analytic.account'

        @api.one
        @api.multi
        @api.depends('planned_resources_ids')
        def _get_horas_planificadas(self):
            """
            Calcula horas planificadas
            """
            data = 0.0

            # Recorremos los datos obtenidos
            for plan_line in self.planned_resources_ids:
                if plan_line:
                    data += plan_line.plan_coste_esf_tot
                
            self.planned_hours = data

        @api.multi
        def _get_lines(self):
            result = {}
            for line in self.planned_resources_ids:
                result[line.id] = True
            return result.keys()

        #Properties
        planned_resources_ids = fields.One2many('planned.resources.contract', 'contract_id', _(u'Líneas de contrato'))
        planned_hours = fields.Float(compute = "_get_horas_planificadas", string = _(u'Total horas planificadas'), digits = (12, 2), store = { 
            'account.analytic.account': (_get_lines, ['planned_resources_ids'], 10)
        })

**Comment by npiganeau** [comment] 2015-01-11 14:24
1. This sort of questions should be asked on the Q&A of Odoo website and not here. Indeed, it is not a bug report.
2. store parameter in new api is a boolean, not a dict anymore (see https://www.odoo.com/documentation/8.0/reference/orm.html#fields)
3. api.one and api.multi are mutually exclusive: self is either a record or a recordset, not both.

**Comment by xmo-odoo** [comment] 2015-01-12 09:12
@npiganeau seems to have covered all the bases, closing

**Closed by xmo-odoo** 2015-01-12 09:12 UTC

**Comment by LeartS** [comment] 2015-01-12 15:40
@xmo-odoo you think it would be possible to add labels for closed issues like "invalid" and "fixed"? That way we could take a look at the closed issues to see problems recently resolved without having to go through the invalid issues.
