### ISSUE TITLE
odoo.conf: password is not encrypted

### ISSUE THREAD

**Issue by luntik2012** [odoo/odoo#31836] opened 2019-03-14 08:29 UTC
Somebody says here that you can just set permissions to your file and it'll be in safe, but my vps hoster can easy read this, not so easy as from RAM, so I think password has to be encrypted.
https://www.odoo.com/forum/help-1/question/how-to-encrypt-passwords-in-config-file-58980

**Comment by Yenthe666** [comment] 2019-03-14 08:39
@luntik2012 are you talking about the master password?
If you fill it in from the frontend of Odoo (from `/web/database/manager`) then Odoo will automatically encrypt it in the `odoo.conf` file.

**Comment by luntik2012** [comment] 2019-03-14 08:41
I use [this manual](https://wiki.archlinux.org/index.php/Odoo#Configuring_Odoo_to_run_with_PostgreSQL) to configure odoo connection to postgres and I cannot just write plain password and save that file, it's not secure

**Comment by Yenthe666** [comment] 2019-03-14 08:43
@luntik2012 yeah if you manually set it in the configuration file it will be stored in plain-text (and human readable). You have to set the master password from the frontend through `http://yoururl.com/web/database/manager`. It then passes through the Odoo functions which will cause the master password to be encrypted to a non-readable value which cannot be decoded.
Closing as this is not a bug but made this way by design.

**Comment by luntik2012** [comment] 2019-03-14 08:44
Thank you

**Closed by Yenthe666** 2019-03-14 08:43 UTC
Labels: Need information

**Comment by Yenthe666** [comment] 2019-03-14 08:46
You're welcome. I've also given the same answer on the official help forums so other people can find it too. Best of luck.

**Comment by babarlhr** [comment] 2021-10-10 07:09
thanks, @yenthe66. may I know which function Odoo uses for this in source code?  which encryption is used by Odoo.

**Comment by ismailprojet** [comment] 2023-10-01 23:45
Hi @Yenthe666 

It is safer to encrypt the "db_password" parameter symmetrically and save it. How to do it.

**Comment by houssine78** [comment] 2023-11-16 11:07
@ismailprojet you can't AFAIK, you need to change the pg_hba.conf to tell postgresql to use peer or ident authentication and not MD5.
if your postgresql database is on the same server that will be even more easy
