### ISSUE TITLE
Inventory products warehouse filter not working

### ISSUE THREAD

**Issue by dan18fan** [odoo/odoo#19693] opened 2017-09-25 17:38 UTC
Impacted versions: 10.0e

Steps to reproduce:

1.  Go to Inventory
2. Open the menu Inventory Control then "Products"
3. Open advanced filters
4. Select group by: Warehouse or Location

Current behavior: Filter is not working as intended, only gives a column "Undefined" with all the products registered

Expected behavior: Show me the warehouses or locations and what products are located in there

Video/Screenshot link (optional):
https://imgur.com/a/d1LvY

**Comment by MouTio** [comment] 2017-09-26 11:00
In 9.0c the behaviour is similar.

Filter is not working, and it shows all products, no matter what location/warehouse they are in.

**Comment by sle-odoo** [comment] 2018-02-21 13:01
Hi,
We confirmed the issue, we'll work on a patch.
MB 816798

Thank you

**Comment by edsersolis** [comment] 2018-04-12 23:50
Noticed this issue on v11. Is there a time estimate for this to be fixed? I see that last response on this thread was on Feb 21... @lap-odoo 

Same thing happens with the Inventory Valuation < which worries me a lot because we already have a bunch of customers in v11.

**Comment by Yenthe666** [comment] 2018-04-13 07:38
@edsersolis don't forget that the Github issue tracker is on a best effort basis. If you have an enterprise license you can escalate the issue and get it fixed faster though.
@sle-odoo can you give an update please?

**Comment by sle-odoo** [comment] 2018-04-13 07:46
There's a branch at #23262 that fixes the issue but i still have to review and adapt it. As there's no opened ticket at the moment, i'll do it when i get some time. This is not linked to the valuation report, in v11 you cannot group the valuation by location/warehouse as the cost is not on the quants. But when the pr will be merged, the option in the groupby will disappear so hopefully it'll be less confusing.

**Comment by edsersolis** [comment] 2018-05-02 22:17
@sle-odoo that's something that must be fixed. In v10 we had the valuation per location, and in v11 it should also be, that it's not a matter of if it's in the quants or not is that it has to be fixed. Most of our customers are already running in v11 and are/will be needing this valuation per location as many of them have many warehouses.

There's no opened ticket because we stopped creating tickets to support and started to use Github instead because Odoo support only gives lame excuses to everything and have never fixed anything, our team has had to fix all the issues we've reported and then create a PR for Odoo. Unfortunately there are some of these that require such an expertise level that our company can't count on and that level of support is to high for us, that's why our customers pay for a license.

**Comment by Yenthe666** [comment] 2018-05-03 05:46
@edsersolis I've noticed huge issues with the official Odoo tickets too. Bad response times and simpling saying 'not on the roadmap' or 'we don't consider this a bug' seems to be getting the default on most tickets now. Nevertheless, some are handled well and are fixed. What I usually do is create a Github issue and an official Odoo ticket. I link both to eachother so both parties know about it and most of the times one of both gives a solution / acceptable answer.

Sorry to hear though!

**Comment by edsersolis** [comment] 2018-05-03 11:42
@Yenthe666 have also done that they don't even see the issue.

@jco-odoo there's no effort in closing tickets without a solution nor will to provide one like you just did now. 

The same attitude that Fabien takes when someone reports or requests something is generalized all over Odoo. That's a big issue because you reduce the improvement possibilities at all, you have great professionals in Odoo SA but that doesn't mean you're any better than your customers or partners, where I'm completely sure there's also great professionals and you have an awful attitude towards these.

I'm not trying to offend anyone, even though you guys always take it that, but stop acting like spoiled childs and work hand to hand with the community that YOU created and worse yet that PAYS for your services.

**Comment by Yenthe666** [comment] 2018-05-03 11:46
@jco-odoo wouldn't it be better that we close of a bug report after it is fixed? The PR (https://github.com/odoo/odoo/pull/23262) is still open and not added in so a close feels to me like we're just trying to close off as many reports as possible?

**Comment by pimodoo** [comment] 2018-05-03 11:55
@edsersolis The pull request https://github.com/odoo/odoo/pull/23262 will be reviewed by our bugfix team, and we'll warn you as soon as it is merged.

Because of the change on the field, we will only fix it from V 11.0 as explained in the PR.

Best regards

**Comment by pimodoo** [comment] 2018-05-07 15:15
@dan18fan @edsersolis the corresponding pull request has just been merged in commit: https://github.com/odoo/odoo/commit/7c7b0992734ded9e72a04e4a412582763cff9a79

Best regards.

**Closed by pimodoo** 2018-05-07 15:15 UTC
Labels: 10.0, 11.0, Confirmed, Logistics
