### ISSUE TITLE
[14.0] Customer or internal users can't accept/decline meeting invitation sent by mail

### ISSUE THREAD

**Issue by Loerres** [odoo/odoo#65582] opened 2021-02-05 07:44 UTC
Impacted versions: 14.0

Steps to reproduce: Go to calender, create new meeting, add staff memeber or customer to meeting

Current behavior: In the calender view in Odoo, if you create a new meeting, an invitation via E-Mail is sent to all participants that are added in the form. In the mail, if you want to accept a meeting, a new window in a browser opens and says "**Internal Server Error. The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.**"
This happens for customers and internal users (staff). In Odoo 13 the invitations worked without any problem.
The log when someone tries to open the link for a invitation:

2021-02-04 17:02:36,596 285779 INFO odoo odoo.addons.base.models.ir_model: Access Denied by ACLs for operation: read, uid: 4, model: calendar.attendee
2021-02-04 17:02:36,617 285779 INFO odoo werkzeug: 192.168.178.47 - - [04/Feb/2021 17:02:36] "GET /calendar/meeting/accept?db=&token=&action=129&id=263 HTTP/1.1" 500 - 6 0.026 0.074
2021-02-04 17:02:36,644 285779 ERROR odoo werkzeug: Error on request:
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/odoo/odoo-server/odoo/http.py", line 805, in dispatch
    r = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 358, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 346, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 911, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 530, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/calendar/controllers/main.py", line 17, in accept_meeting
    attendee = request.env['calendar.attendee'].search([
  File "/odoo/odoo-server/odoo/models.py", line 1697, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/odoo/odoo-server/odoo/models.py", line 4444, in _search
    model.check_access_rights('read')
  File "/odoo/odoo-server/odoo/models.py", line 3312, in check_access_rights
    return self.env['ir.model.access'].check(self._name, operation, raise_exception)
  File "<decorator-gen-33>", line 2, in check

  File "/odoo/odoo-server/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_model.py", line 1758, in check
    raise AccessError(msg)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/serving.py", line 306, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/serving.py", line 294, in execute
    application_iter = app(environ, start_response)
  File "/odoo/odoo-server/odoo/service/server.py", line 440, in app
    return self.app(e, s)
  File "/odoo/odoo-server/odoo/service/wsgi_server.py", line 124, in application
    return application_unproxied(environ, start_response)
  File "/odoo/odoo-server/odoo/service/wsgi_server.py", line 99, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/odoo/odoo-server/odoo/http.py", line 1294, in __call__
    return self.dispatch(environ, start_response)
  File "/odoo/odoo-server/odoo/http.py", line 1262, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/middleware/shared_data.py", line 220, in __call__
    return self.app(environ, start_response)
  File "/odoo/odoo-server/odoo/http.py", line 1464, in dispatch
    result = ir_http._dispatch()
  File "/odoo/odoo-server/addons/website/models/ir_http.py", line 181, in _dispatch
    response = super(Http, cls)._dispatch()
  File "/odoo/odoo-server/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "/odoo/odoo-server/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/odoo/odoo-server/addons/utm/models/ir_http.py", line 29, in _dispatch
    response = super(IrHttp, cls)._dispatch()
  File "/odoo/odoo-server/addons/http_routing/models/ir_http.py", line 512, in _dispatch
    result = super(IrHttp, cls)._dispatch()
  File "/odoo/odoo-server/odoo/addons/base/models/ir_http.py", line 241, in _dispatch
    return cls._handle_exception(e)
  File "/odoo/odoo-server/addons/utm/models/ir_http.py", line 34, in _handle_exception
    response = super(IrHttp, cls)._handle_exception(exc)
  File "/odoo/odoo-server/addons/http_routing/models/ir_http.py", line 602, in _handle_exception
    return super(IrHttp, cls)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_http.py", line 209, in _handle_exception
    return request._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 743, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 314, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.exceptions.AccessError: You are not allowed to access 'Informationen für Kalender-Teilnehmer' (calendar.attendee) records.

This operation is allowed for the following groups:
        - Time Off/All Approver
        - User types/Internal User

Contact your administrator to request access if necessary. - - -

Expected behavior: You should accept/decline a meeting via E-Mails.

Thank you very much.

**Comment by pedrobaeza** [comment] 2021-02-05 07:46
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Loerres** [comment] 2021-02-05 11:27
No, I can't reproduce it in runbot since there wasn't any mail sent.

Steps to reproduce:
1. Set a customer in module "Conctacts" with e-mail address
2. Go to module "Calendar" and create a meeting with clicking on the point in time.
3. Add the customer created in step 1
4. Save. The Mail to myself and the customer are sent.
5. Neither the link on my invitation-mail nor the link in the mail for the customer are working, only showing "Internal Server Error. The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application." in the browser tab when trying to accept the invitation. Same for decline.

The calendar module was updated right before reporting the issue. No self-programmed modules are integrated. The mail-template for calendar invitations also hasn't been changed.

Thank you very much.

**Comment by pedrobaeza** [comment] 2021-02-05 11:32
You can check the sent mail in settings part. I suspect that the problem comes from your deployment, not in Odoo itself.

**Comment by Loerres** [comment] 2021-02-05 11:59
Ich checked it again and I can't reproduce it on runbot, the invitation works and is displayed.

**Comment by pedrobaeza** [comment] 2021-02-05 12:02
Yeah, that was my suspect. Try to update your system and delete mail templates to let Odoo to regenerate them on update to see.

Closing meanwhile. If you find more traces about what's going on and the culprit is Odoo code, we can reopen.

**Closed by pedrobaeza** 2021-02-05 12:02 UTC
Labels: Need information
