### ISSUE TITLE
Bug Odoo 9: Purchase order line "Received quantity"

### ISSUE THREAD

**Issue by bodedra** [odoo/odoo#13299] opened 2016-08-25 15:06 UTC
Impacted versions: Odoo 9.0

Steps to reproduce:
- Create Purchase order
- Add Product, quantity = 25 (as you add any positive quantity)
- Confirm Purchase order
- Click on "Received Products" button
- Validate it.
- Go back to Purchase order. And check product line received quantity = 25 which is correct.
- Click again on "Received Products" button
- Click on "Reverse" button. It will open wizard. Update product line quantity = 5.
- Click on "Return"
- Go back to Purchase order. And check product line "Received quantity". It's show 25.

Current behavior:
- Purchase 25 quantity 
- Received 25 quantity = Incoming shipment DONE
- Return quantity 5
- In purchase order line, it's show "Received quantity" = 25

Expected behavior:
- Purchase order line should show "Received quantity" = 20

**Comment by bistaray** [comment] 2016-08-26 03:15
This is how Odoo is designed to work.  25 was received, and this number cannot be lower because the Vendor will Invoice you for 25.  If it went to 20, the Invoice would be created for 20, which would be wrong.  If you do return 5, you will still almost certainly get an Invoice for 25, and a credit for 5. I have heard your feedback before, so I understand it, but Invoicing is tied now to the received quantity and would be affected by your expected behavior.

**Comment by bodedra** [comment] 2016-08-26 05:56
Hi Ray,

Thanks for your valuable feedback.

Please let me correct.

I have two case here.

1st case:

What if I don't create invoice before return product ?   => In these case, User create invoice, quantity should be 20  ( 25 received - 5 return ).

2nd case:

What if invoice is created ? => In these case, Vendor refund will be create automatically with 5 quantity if created invoice is "Open/Paid" state. Otherwise draft invoice should be updated with quantity 20 (25-5).

What you think about it ?

**Comment by bistaray** [comment] 2016-08-29 16:38
1st case:

If a company send 25 items, they almost certainly process an Invoice for 25 items.  Since those items have left their inventory, they are entitled to collect revenue (and book that revenue).   So the company send 25 items and invoices for 25 items.

Odoo won't reduce the quantity on the PO.  You did receive 25.  The fact that you returned 5 is another transaction with another invoice (as Odoo and I see it).

2nd case:

There is no automatic creation of a Vendor Invoice when products are returned.  This is just the way it works.  In most cases, the Vendor will credit with ANOTHER invoice.  So you will need two Invoices - one for 25, one for the credit of 5.

I understand what you want Odoo to do.

I am just trying to explain that isn't how it was designed to work.

I believe it was designed not to work that way because that's not how most Vendors operate.  I have not experienced from any client that a Vendor will send products, then wait for the Customer to decide what they will accept and subtract the returned quantity from what the Vendor will Invoice.

I have always seen a full invoice accompany the shipment (or at least be created to match the quantity on the full shipment) and a second invoice or credit note get created if anything is returned.

Perhaps it is different in your case?  I don't believe it is common.  What happens if the truck delivering the goods is lost on the way?  The Vendor needs full accounting of the 25 items it sent.  Even if you don't receive any, someone has to be liable for them.

**Comment by bodedra** [comment] 2016-08-30 14:31
Hi Ray,

I am agree with you that most of Vendors operate as you mentioned.

Yes in my case, it's different with Generic Vendor operates. 

You are correct. Sometime quantity lots while travailing or User mistake (mark as received all quantity).

I believe I am thinking over the beyond generic functionality.

**Comment by bistaray** [comment] 2016-08-30 14:34
You may have to customize how it works, or see if the users can change their workflow and expectations (may be cheaper than customization).

**Comment by sle-odoo** [comment] 2018-02-06 20:31
@bistaray explained everything :) thus i'm closing this one too. Thank you

**Closed by sle-odoo** 2018-02-06 20:31 UTC
Labels: 9.0, Logistics
