### ISSUE TITLE
Odoo Discuss's Chat Status is Always Offline

### ISSUE THREAD

**Issue by raspberryflakes** [odoo/odoo#66419] opened 2021-02-18 03:46 UTC
Impacted versions:
Odoo Version 12

Steps to reproduce:
When user are logging into Odoo, the chat status is always appear offline even some other user are logged in.

Current behavior:
- Chat status is always offline after user logged in.
- Chat status goes online (green) and sometimes produce yellow lights after quite sometime, but when user refreshed the page, it all goes offline.
- Chats are sent properly among other users in real time and having no problem, longpolling port are set properly as usual to 8072.
- Sound notification doesn't sound when user opening another tab (other web), only when user are opening odoo.

Expected behavior:
- Chat status should show whose online with green lights as usual
- Chat sound notification should also ring when user are opening other tab

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/68892527/108302356-ca8f4f00-71de-11eb-84c1-c4fd6640eeb5.png)

Support ticket number submitted via odoo.com/help (optional): -

**Comment by pedrobaeza** [comment] 2021-02-18 07:14
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/14.0/setup/install.html. The specific problem seems to be on longpolling configuration or the reverse proxy.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).

**Closed by pedrobaeza** 2021-02-18 07:14 UTC
