### ISSUE TITLE
Module Time Off: ValueError: time data does not match format '%Y-%m-%d'

### ISSUE THREAD

**Issue by akram1** [odoo/odoo#64236] opened 2021-01-07 23:59 UTC
I am using Linux Debian 10 and Odoo is installed with deb package. Odoo is updated with today deb package. Once I choose Time Off module the following message shows up:

Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 682, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 358, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 911, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 530, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1377, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1369, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 392, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 365, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/hr_holidays/models/hr_leave.py", line 1250, in get_unusual_days
    dfrom = datetime.combine(fields.Date.from_string(date_from), time.min).replace(tzinfo=UTC)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1744, in to_date
    return datetime.strptime(value, DATE_FORMAT).date()
  File "/usr/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.7/_strptime.py", line 359, in _strptime
    (data_string, format))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: time data '٢٠٢٠-١٢-٢٥' does not match format '%Y-%m-%d'

Impacted versions: 14 (latest)

Steps to reproduce: Choose Time Off from main menu

Current behavior: Error message ValueError: time data '٢٠٢٠-١٢-٢٥' does not match format '%Y-%m-%d', Which prevents calendar to view data.

Expected behavior: Calendar should display as normal

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment] 2021-01-08 08:11
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by akram1** [comment] 2021-01-08 19:23
I fixed it by reconfigure locales and remove all locale and assign it to  C UTF8.
for debian based Linux use: dpkg-reconfigure locales

**Comment by RachidAlassir** [comment] 2021-01-09 20:51
@pedrobaeza 
This probably was fixed in #63833

**Closed** 2021-01-11 13:16 UTC
Labels: Need information
