### ISSUE TITLE
[8.0] [Event] Unable to save record in event.

### ISSUE THREAD

**Issue by cod-odoo** [odoo/odoo#2823] opened 2014-10-01 09:17 UTC
Impacted versions: 
  -> 8.0 and master.
Steps to reproduce:
-> Goto Marketing > Events > Events
-> Create new event,set maximum = 3 and create registration from o2m,
-> click on save button yo got constrain error.
     -> you can also see video: http://youtu.be/DVRqTWI_R2A
Current behavior:
    -> constrain error occur,i can't able to save record
Expected behavior:
  -> i should able to save record.

**Comment by pna-odoo** [comment] 2015-01-05 12:21
I Could not reproduce the bug, it probably has been fixed meanwhile. so I'm closing this issue. Thanks.

**Closed by pna-odoo** 2015-01-05 12:21 UTC
