### ISSUE TITLE
[13.0] Html field - Odoo Client Error when using table

### ISSUE THREAD

**Issue by grzekru** [odoo/odoo#40829] opened 2019-11-25 21:08 UTC
**Impacted versions:**

13.0 (CE current commit)

**Steps to reproduce:**

1. Create note (or project task - something with html field)
2. Add 1x2 table
3. Add text to cell 2
4. Go to cell 1 and press backspace
5. Error 1

1. Create table
2. Remove table
3. Try to add new table (may require several attempts)
4. Error 2

**Video/Screenshot link (optional):**

Error 1
![image](https://user-images.githubusercontent.com/5862658/69577519-cb7f0400-0fce-11ea-9db0-f45ec7d923c8.png)

Error 2
![image](https://user-images.githubusercontent.com/5862658/69578070-fae24080-0fcf-11ea-89d7-3efcc963b5c8.png)

**Comment by pedrobaeza** [comment] 2019-11-26 09:23
@qsm-odoo you are still referred in the wiki for this kind of things, but I remember you told me that you are not in this. Can you point me to the right person?

**Comment by qsm-odoo** [comment] 2019-11-26 09:55
I still work on the website editor (snippets and options) so I may still have a look once in a while but the right person for an editor bug when editing the **text** (+ top bar options, like the table here) would be:
- for <= 12.0: our bug fix team with @nim-odoo 
- for >= 13.0 only: our editor team with @dmo-odoo 

Correct me if I am wrong guys... :)

**Comment by pedrobaeza** [comment] 2019-11-26 10:05
Thanks for the references, so it seems @dmo-odoo can be the right person for this one, although not sure if this is happening as well on v12.

**Comment by dmo-odoo** [comment] 2019-11-27 07:48
Hello @pedrobaeza,

I was able to reproduce the bug you encountered on v12. This means your guy is @nim-odoo and, basically, the standard Odoo support.

Best regards,
David

**Comment by pedrobaeza** [comment] 2019-11-27 08:12
Thanks for checking, David.

@nim-odoo do you need an OPW ticket for this or are you going to check it?

**Comment by sswapnesh** [comment] 2019-12-01 17:30
Seems duplicate of https://github.com/odoo/odoo/issues/33472

**Comment by pedrobaeza** [comment] 2019-12-01 17:39
Yes, quite similar, although I prefer to leave both for now to see if someone of the pinged persons answer.

**Comment by Yenthe666** [comment] 2020-05-13 12:27
1) is fixed in the meanwhile
2) Very similar to https://github.com/odoo/odoo/issues/50966 and I've reported this kind of behaviour in my OPW today at `2256835`

**Comment by Yenthe666** [comment] 2020-05-28 07:26
https://github.com/odoo/odoo/pull/51956

**Closed** 2020-05-28 10:56 UTC
Labels: 12.0, 13.0, Confirmed, Web editor
