### ISSUE TITLE
Odoo 10 ERROR odoo.http: Exception during JSON request handling

### ISSUE THREAD

**Issue by ausl** [odoo/odoo#19814] opened 2017-09-30 10:54 UTC
Impacted versions: Odoo 10 Community with latest update

Steps to reproduce: Start Odoo Server/Login

Current behavior: Show error as following:

Traceback (most recent call last):
  File "/home/odoo/parts/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/parts/odoo/odoo/addons/base/ir/ir_http.py", line 177, in _dispatch
    rule, arguments = cls._find_handler(return_rule=True)
  File "/home/odoo/parts/odoo/odoo/addons/base/ir/ir_http.py", line 79, in _find_handler
    return cls.routing_map().bind_to_environ(request.httprequest.environ).match(return_rule=return_rule)
  File "/home/odoo/eggs/Werkzeug-0.9.3-py2.7.egg/werkzeug/routing.py", line 1433, in match
    raise NotFound()
NotFound: 404: Not Found

Expected behavior: No error - i almost removed all custom module from OCA and still can't find the issue

I dont know where i can find more error message, this happen when Odoo try to odoo.addons.base.ir.ir_http: Generating routing map.

**Comment by itautomationo** [comment] 2017-12-14 05:23
I have the same error..

**Comment by develetham** [comment] 2017-12-29 07:34
Same here but with something different
2017-12-29 07:32:04,816 1766 ERROR Omnibus odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 885, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 678, in call_kw_multi
    recs = self.with_context(context or {}).browse(ids)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 4887, in with_context
    context = dict(args[0] if args else self._context, **kwargs)
**ValueError: dictionary update sequence element #0 has length 12; 2 is required**

**Comment by danger89** [comment] 2018-01-26 16:52
yep same.. Constantly...

```
Traceback (most recent call last):                                                                                                                                                                                 
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 646, in _handle_exception                                                                                                                               
    return super(JsonRequest, self)._handle_exception(exception)                                                                                                                                                   
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 307, in _handle_exception                                                                                                                               
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])                                                                                                                                          
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise                                                                                                                                
    raise value                                                                                                                                                                                                    
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_http.py", line 190, in _dispatch                                                                                                                     
    rule, arguments = cls._find_handler(return_rule=True)                                                                                                                                                          
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_http.py", line 84, in _find_handler                                                                                                                  
    return cls.routing_map().bind_to_environ(request.httprequest.environ).match(return_rule=return_rule)                                                                                                           
  File "/usr/lib/python3/dist-packages/werkzeug/routing.py", line 1563, in match                                                                                                                                   
    raise NotFound()                                                                                                                                                                                               
werkzeug.exceptions.NotFound: 404: Not Found                                                                                                                                                                       

``

```
2018-01-26 16:51:24,681 13961 ERROR ? odoo.http: Exception during JSON request handling.                                                                                                                           
Traceback (most recent call last):                                                                                                                                                                                 
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 646, in _handle_exception                                                                                                                               
    return super(JsonRequest, self)._handle_exception(exception)                                                                                                                                                   
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 307, in _handle_exception                                                                                                                               
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])                                                                                                                                          
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise                                                                                                                                
    raise value                                                                                                                                                                                                    
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1442, in _dispatch_nodb                                                                                                                                 
    func, arguments = self.nodb_routing_map.bind_to_environ(request.httprequest.environ).match()                                                                                                                   
  File "/usr/lib/python3/dist-packages/werkzeug/routing.py", line 1563, in match                                                                                                                                   
    raise NotFound()                                                                                                                                                                                               
werkzeug.exceptions.NotFound: 404: Not Found                                                                                                                                                                       
```

**Comment by Yenthe666** [comment] 2018-01-28 10:40
@danger89 did you find any way to reproduce the behaviour perhaps?

**Comment by vuwnevska** [comment] 2018-02-15 15:42
On days received this one problem. Get on some machines all on Ubuntu, some instances on docker, can't reproduce it locally.

Get this issue when linking M2M, O2M fields in different modules, but all are custom.

```
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 890, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 882, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 676, in call_kw_multi
    ids, args = args[0], args[1:]
IndexError: list index out of range
```

**Comment by hieuht817** [comment] 2018-02-27 07:50
I have the same error.. on odoo 11 (docker).
The context leads to the error:
- ec2 server run odoo 11 (docker)
- I terminate the ec2
- I start the ec2
- I restart docker: `docker restart db odoo

Then I get the error. Odoo server response 500.

**Comment by develetham** [comment] 2018-02-27 08:24
I've solved this issue desinstalling one module from the OCA repositoy.
I've seen there are some modules that generates this kind of error. Mine has been located in OCA/server-tools but I can't remember what module was.
I've lost more than one day installing one by one those modules and looking for the error.
Let me try to find out in my notes what module was.

**Comment by JayVora-SerpentCS** [comment] 2018-06-07 18:46
@pedrobaeza close this too.

**Comment by pedrobaeza** [comment] 2018-06-07 18:54
Closing as no answer.

**Closed by pedrobaeza** 2018-06-07 18:54 UTC
Labels: 10.0, Framework
