### ISSUE TITLE
#id=home web_enterprise module community backend theme issue

### ISSUE THREAD

**Issue by 1AbdulKareem** [odoo/odoo#69808] opened 2021-04-26 02:01 UTC
Impacted versions:14

Steps to reproduce: I'm installing the akl_backend_theme from the 3rd party apps store on odoo enterprise, the backend addon shows apps without icons, which exactly what I want, works well on community, but in enterprise it doesn't work because of the web#id=home, as I can assume it's related to web_enterprise module which, but when I uninstall it, the accounting modules will uninstall too and will break the database!, any ideas how to make the odoo enterprise backend theme looks like community so I don't have to redo writing styles based on web_enterprise module ?

Video/Screenshot link:
the theme looks like this on community (the way I want)
![DeepinScreenshot_select-area_20210426050854](https://user-images.githubusercontent.com/47043905/116020053-344c2f00-a64e-11eb-85bf-ef3864802762.png)

I appreciate any solutions. Thanks

**Comment by pedrobaeza** [comment] 2021-04-26 06:09
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in such code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2021-04-26 06:09 UTC
