### ISSUE TITLE
Incoming mail server configuration

### ISSUE THREAD

**Issue by remz1337** [odoo/odoo#15603] opened 2017-02-22 15:47 UTC
Impacted versions:
10

Steps to reproduce:
Brand new Ubuntu Server 16.04.1 x64
Install Odoo Community using Deb package
Go to General Settings-->Incoming Mail Servers
Create
Fill in IMAP connection parameters (Working on my iPhone)
Click Test&Confirm

Current behavior:
warning pop-up:
Odoo Warning - Warning
Connection test failed: 8
EOF occurred in violation of protocol (_ssl.c:590)

Expected behavior:
Successfully retrieve emails

Other information:
We are running a Microsoft Server 2003 R2 with Microsoft Exchange 2003. IMAP and SMTP are working fine (tested with imap account on my iphone).
I do get a warning about untrusted certificate on my iphone, but everything still works.

**Comment by remz1337** [comment] 2017-02-24 15:49
Update I was able to get the mails working with unsecured POP and SMTP,
problem with IMAP still persists

**Comment by Yenthe666** [comment] 2017-05-31 08:42
Hi @remz1337,

Thank you for your configuration.
This however looks like a misconfiguration for the mailserver. There can be small differences in Odoo configuration and another mobile app its configuration.
Closing this one as it is not reproducable and because you've got it working.

Regards,
Yenthe

**Closed by Yenthe666** 2017-05-31 08:42 UTC

**Comment by cococococococo** [comment] 2018-07-05 10:02
I have same problem
