### ISSUE TITLE
[13.0] Mobile - datepicker iphone browser

### ISSUE THREAD

**Issue by shenxuchu** [odoo/odoo#47653] opened 2020-03-16 06:16 UTC
Impacted versions: 13

Steps to reproduce: edit form

Current behavior: When entering a form in the iphone browser, the date field fails to evoke the input method，The android browser is fine

Expected behavior:

Video/Screenshot link (optional):

![gav1](https://user-images.githubusercontent.com/44028892/76728063-97ec0380-6790-11ea-8bc7-54d403ac3718.gif)

**Comment by Yenthe666** [comment] 2020-03-16 07:15
@JKE-be

**Comment by JKE-be** [comment] 2020-03-16 07:47
@Yenthe666 

Probably a framwork / backend problem.
Cannot reproduce in Frontend (Website) with iPhone  IOS 13.3.1 on the last master
![image](https://user-images.githubusercontent.com/4848797/76734212-baffbe80-6762-11ea-8a26-ef34beb01408.png)

**Comment by JKE-be** [comment] 2020-03-16 07:48
//Cc @adr-odoo

**Comment by shenxuchu** [comment] 2020-03-19 08:14
Is there a solution?

**Comment by pparidans** [comment] 2020-03-19 09:21
Hi,

Actually this issue is related to https://github.com/odoo/odoo/issues/23056 .
This is kind of tricky to find the right balance between the basic usability of the date picker and not blocking the form view.
An internal task (id 2069687) has been created but should be discussed to find the right implementation.

**Comment by pparidans** [comment] 2020-03-19 09:21
//Cc @aab-odoo

**Comment by celebraciones** [comment] 2020-04-28 03:55
Tested in iPhoneX iOS 13.3.1 using Opera, Chrome and Safari with the same behavior. Desktop Safari in responsive mode shows the datepicker but not in the handheld device. If someone finds a workaround please advise since it may be not Odoo code related.

**Comment by pparidans** [comment] 2020-05-11 09:50
@shenxuchu @celebraciones I tested it on and iPhone with iOS 13.4.1 but... I can't reproduce this issue anymore.

Do you still encounter it on the latest commits (for 13.0)?

**Comment by celebraciones** [comment] 2020-05-12 03:37
@pparidans I just tested it using runbot Saas-13.3 with iPhone XR 13.4.1 and seems to be working fine so far. I would need to install a new Test instance using latest commit of CE but won’t be able to do it this week. Is there some kind of runbot in CE to test it on the fly instead of cloning latest commit? That will help me to test it this same week. Thanks.

**Comment by pparidans** [comment] 2020-05-18 12:23
Happy to read that it fixed the issue. :+1: 
Sadly I can't attribute this fix to a specific commit and/or a change between iOS 13.3 and 13.4...

Closing it for now.

**Closed by pparidans** 2020-05-18 12:23 UTC
Labels: 13.0

**Comment by celebraciones** [comment] 2020-06-14 21:12
The issue comes from addons/web/static/src/js/widgets/date_picker.js. Just updating it to the latest commit works in either iOS 13.3 or 13.4. Seems that this two components are the reason behind:
if (currentDate && currentDate.format('YYYY-MM-DD') > moment().format('YYYY-MM-DD'))

window.removeEventListener('wheel', this._onScroll, true);

did the trick!

Issue is closed as you mentioned, just wanted to comment on it.
