### ISSUE TITLE
Odoo is not compatible with wkhtmltopdf version 0.12.2 (error around table headers)

### ISSUE THREAD

**Issue by harobed** [odoo/odoo#5177] opened 2015-02-09 20:11 UTC
Odoo is not compatible with wkhtmltopdf version 0.12.2
With 0.12.2, there are some error around table header when table is splited on several pages.

0.12.1 work perfectly.

Suggest : append wkhtmltopdf version check here : https://github.com/odoo/odoo/blob/8.0/addons/report/models/report.py#L72

**Comment by smack815** [comment] 2015-02-09 20:31
This is a known issue #4806 and is being investigated by @aab-odoo

**Comment by aab-odoo** [comment] 2015-02-11 07:35
Hello,

There are indeed some issues with version 0.12.2 and 0.12.2.1 of wkhtmltopdf. We have several open issues on the wkhtmltopdf repository and we hope that they will be fixed soon.

I agree with your suggestion, we'll display a warning when the version of wkhtmltopdf is 0.12.2 or 0.12.2.1.

Thanks.

**Comment by falinwa** [comment] 2015-02-11 08:36
I confirm this issue too.

**Comment by sle-odoo** [comment] 2015-03-05 14:36
At the moment please keep using the 0.12.1 version as [written in the documentation](https://www.odoo.com/documentation/8.0/setup/install.html#deb)

``The recommended version is 0.12.1 and is available on the wkhtmltopdf download page, in the archive section. As there is no official release for Debian Jessie, you can find ours on http://nightly.odoo.com/extra/.
``

**Closed by sle-odoo** 2015-03-05 14:36 UTC

**Comment by ashkulz** [comment] 2015-05-29 12:18
@sle-odoo: can you list out which issues are blocking you from upgrading (or create a tracking bug and link to all of them)? I'm planning to release `0.12.3` in the near future, and would like to see if it is possible to solve them before it happens.

**Comment by sle-odoo** [comment] 2015-06-01 21:07
Hello @ashkulz and thank you for the consideration.
We still have two blocking issues: 
* https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2183 : external javascripts in header/footer result in blank header/footer.
* https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2156 : --dpi argument is ignored. The behavior can be achieved with --zoom but, as the values are platform dependent, it's not very elegant to handle it on our side.

I'll be very happy to test the new release and give you some feedbacks. I'll try to build it right away.

Simon

**Comment by ashkulz** [comment] 2016-11-23 08:28
wkhtmltopdf [`0.12.4`](http://wkhtmltopdf.org/downloads.html#stable) has been released, which should contain the fix for this issue. Please report back if it is not solved with the above version.

**Comment by steenzout** [comment] 2016-12-09 15:42
@aab-odoo can you confirm `0.12.4` fixes the issues?

this really important to know since it seems it's the only way to get `wkhtmktopdf` to work on Ubuntu 16.04.

**Comment by ashkulz** [comment] 2016-12-10 00:53
There may be a regression on macOS with retina display, still being investigated in wkhtmltopdf/wkhtmltopdf#3241

**Comment by aab-odoo** [comment] 2016-12-14 08:07
@sle-odoo Can you check that 0.12.4 fixes the issues?

**Comment by DarkoNikolovski** [comment] 2017-02-27 23:25
I have installed 0.12.4 with Odoo 10. When I try to print a report the server loading till I don't reset it. Any idea why this happens?

**Comment by steenzout** [comment] 2017-02-27 23:41
@DarkoNikolovski did you setup `web.base.url`?

if you check that setting and it's pointing to `domain.yourcompany.com` you may want to try `http://127.0.0.1:8069` (or whatever port you have Odoo running).

this solved a similar situation I had on Odoo 9.

**Comment by DarkoNikolovski** [comment] 2017-02-28 07:44
Thanks @steenzout it solved the issue.

**Comment by bunhin** [comment] 2017-09-15 04:03
Hello,
I install 0.1.2.4 for odoo 10 community,  i have small render problem,  the negatif sign of negatif numbers becoma a small square instead of ( - ), please anybody help what should i do to solve it, is odoo 10 still need to use only 0.12.1 version of wkhtmltopdf even now ?

**Comment by chris001** [comment] 2018-01-11 19:27
@DarkoNikolovski @steenzout 
Can you confirm `wkhtmltopdf` version `0.12.4` is working fine on Odoo 11, as long as `web.base.url` value is set to `http://127.0.0.1:8069` ??

**Comment by chris001** [comment] 2018-01-11 21:02
WKHTMLtoPDF Version 0.12.1 (supported by Odoo 11 !?) is obsolete and not supported by the `wkhtmltopdf` project!
```
Please note that bug reports will not be accepted against the following, which are considered obsolete. It is recommended to use the latest stable release instead, and report an issue if there is a regression from a previous release.
```
