### ISSUE TITLE
[14.0] website: header is disappear when quickly scrolling to the top.

### ISSUE THREAD

**Issue by kig-odoo** [odoo/odoo#72972] opened 2021-06-30 08:45 UTC
On the website, the header disappears when quickly scrolling to the top.
https://www.awesomescreenshot.com/video/4313731?key=945fc97e6bcb570e5fef640fa434c729

Tested on runbot.

**Comment by pedrobaeza** [comment] 2021-06-30 10:47
It seems that happens when clicking directly on the scroll bar free part for provoking a "hard" scroll.

@JKE-be can you please check this?

**Comment by rdeodoo** [comment] 2021-07-02 10:18
Duplicate of https://github.com/odoo/odoo/issues/71449

> It seems that happens when clicking directly on the scroll bar free part for provoking a "hard" scroll.

Not especially, you can reproduce it by any scrolling method, eg just 2 finger scroll on touchpad

**Closed by rdeodoo** 2021-07-02 10:18 UTC
Labels: 14.0, Confirmed, Website
