### ISSUE TITLE
Menu Bar not loading when using Multi language

### ISSUE THREAD

**Issue by BlissNomad** [odoo/odoo#52284] opened 2020-06-02 16:35 UTC
Impacted versions:v13

Steps to reproduce:add second language , reload page

Current behavior: page menu dosent load

Expected behavior: page menu loads

Video/Screenshot link (optional):

![Screen Shot 2020-06-02 at 12 35 02 PM](https://user-images.githubusercontent.com/53065476/83545710-926ba300-a4cd-11ea-8dcc-766e1a7448cd.png)

**Comment by Yenthe666** [comment] 2020-07-27 14:17
Hi there,

Since there has been no feedback since our last question I'm closing this issue.
Don't hesitate to comment back with extra information / reproducable steps and we'll be happy to reopen this issue.

Regards,
Yenthe

**Closed by Yenthe666** 2020-07-27 14:17 UTC
Labels: Need information
