### ISSUE TITLE
Display total amount 

### ISSUE THREAD

**Issue by hindbenessy** [odoo/odoo#12279] opened 2016-06-03 10:04 UTC
version : odoo8
hello , i want to display total amount in check with French language 
thanks 
![capture du 2016-06-03 11 04 37](https://cloud.githubusercontent.com/assets/17640313/15775657/fd365248-297a-11e6-946e-e462c116d833.png)

**Comment by Yenthe666** [comment] 2016-06-03 10:06
Hi @hindbenessy,

Are you actually asking how to add the total of all lines in this report or?

**Comment by hindbenessy** [comment] 2016-06-03 10:08
i want to translate the text amount to french

**Comment by Yenthe666** [comment] 2016-06-03 10:14
Hi @hindbenessy,

All translations regarding Odoo should be done on Transifex (transifex.com/odoo/).
After you've translated the terms it will be in the Odoo code within two weeks. Please do all your translations there and then update your Odoo environment in two weeks.
Another option that you have is to translate it yourself under settings > translations > translated terms.
Closing this since this is not a bug, it is just a missing translation.

Regards,
Yenthe

**Closed by Yenthe666** 2016-06-03 10:14 UTC
