### ISSUE TITLE
How to set Sum distinct in reporting 

### ISSUE THREAD

**Issue by m3asmi** [odoo/odoo#15695] opened 2017-03-02 11:20 UTC
hello,

is there a way to set group_operator as SUM(DISTINCT column) in reporting :

I have the following view :

```
SELECT
    sale_id,
    COUNT( product_id),
    SUM(DISTINCT sale_qty) sale_qty ,
    SUM(delivered_qty) deliveryed_qty
FROM sale_delivery
WHERE sale_id=3063
GROUP BY sale_id 
```

**Comment by Yenthe666** [comment] 2017-03-02 15:22
Hi @m3asmi,

The github tracker is only for bugs in the official code, this is not the place to ask questions.
Please ask this at odoo.com/help there are plenty of people who can help you there. 😄 
Closing this as it is not a bug report, please see the official rules at https://github.com/odoo/odoo/wiki/BugManagement

Regards,
Yenthe

**Closed by Yenthe666** 2017-03-02 15:22 UTC
