### ISSUE TITLE
9.0 CE Bug, Installing some CRM related modules.

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#10814] opened 2016-02-08 08:48 UTC
Official Odoo Addons,

Install crm then other modules related to CRM.

We get below things in terminal...

2016-02-08 08:45:07,324 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (374)
2016-02-08 08:45:07,326 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (376) 
2016-02-08 08:45:07,348 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (370)
 2016-02-08 08:45:07,364 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (375)
2016-02-08 08:45:07,389 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (373)
 2016-02-08 08:45:07,411 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (686)
  2016-02-08 08:45:07,470 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (686)
 2016-02-08 08:45:07,490 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (375)
2016-02-08 08:45:07,490 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (376)
2016-02-08 08:45:07,501 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (374)
 2016-02-08 08:45:07,518 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (687)
 2016-02-08 08:45:07,559 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (687)
  2016-02-08 08:45:07,607 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (376)
 2016-02-08 08:45:07,640 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (375)
2016-02-08 08:45:07,640 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (688)
2016-02-08 08:45:07,640 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (688)
   2016-02-08 08:45:07,737 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (689)
2016-02-08 08:45:07,738 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (689)
2016-02-08 08:45:07,747 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (376)
    2016-02-08 08:45:07,851 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (690)
 2016-02-08 08:45:07,876 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (690)
   2016-02-08 08:45:07,975 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (691)
2016-02-08 08:45:07,976 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (691)
2016-02-08 08:45:08,074 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (692)
2016-02-08 08:45:08,080 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (692)
2016-02-08 08:45:08,173 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (693)
2016-02-08 08:45:08,187 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (693)
2016-02-08 08:45:08,285 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (694)
2016-02-08 08:45:08,294 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (694)
2016-02-08 08:45:08,400 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (972)
2016-02-08 08:45:08,403 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (972)
2016-02-08 08:45:08,501 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (695)
2016-02-08 08:45:08,515 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (695)
2016-02-08 08:45:08,625 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (371)
2016-02-08 08:45:08,630 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (371)
2016-02-08 08:45:08,762 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (372)
2016-02-08 08:45:08,764 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (372)
2016-02-08 08:45:08,855 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (373)
2016-02-08 08:45:08,871 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (373)
2016-02-08 08:45:08,971 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (374)
2016-02-08 08:45:08,993 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (374)
2016-02-08 08:45:09,139 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (375)
2016-02-08 08:45:09,140 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (375)
2016-02-08 08:45:09,248 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (376)
2016-02-08 08:45:09,254 10958 INFO cloud_wheelsuk openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (376)

**Comment by Yenthe666** [comment] 2016-06-14 07:19
Hi @tejastank,

I just tested this on the latest code and can install all CRM related apps without any problem.
If you still face this issue please update your Odoo to the latest codebase and install the apps again.
Closing this issue since I cannot reproduce this.

Regards,
Yenthe

**Closed by Yenthe666** 2016-06-14 07:19 UTC
