### ISSUE TITLE
Promotion plan filtering products are not effective for sales orders

### ISSUE THREAD

**Issue by yaodongshi** [odoo/odoo#57441] opened 2020-09-10 14:37 UTC
Impacted versions:
13.0
Steps to reproduce:
1.Open the promotion plan and set the designated product as a discount product
2.Create a quotation, add a discount product, add a product that is not within the discount range.
3.Insert promotion plan
Current behavior:
All products in the entire quotation are discounted
Expected behavior:
Only calculate discounts for discounted products
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2020-09-10 15:04
The applicability is "Apply On Current Order", so that's the expected behavior. Closing due to this.

**Comment by yaodongshi** [comment] 2020-09-10 15:42
For discounts on all products, the product filter discount function is equivalent to no effect, because only one order is a discounted product, and the entire sales order is discounted, not a single product for discount calculation.

**Comment by pedrobaeza** [comment] 2020-09-10 15:43
AFAIK, this is how it works. @Yenthe666 do you know about this?

**Comment by yaodongshi** [comment] 2020-09-10 15:50
However, on 12.0, the discount is calculated for products within the discount range, and only the discount percentage of the discounted product is calculated. As long as there is a discount product in an order on 13.0, the total amount of the entire sales order will be discounted. I think this Not the right way.

**Comment by Yenthe666** [comment] 2020-09-10 15:58
Hmm I think it was built this way indeed and it feels logical to me. However, if it was different in V12 we should check with the product responsible maybe?

**Comment by pedrobaeza** [comment] 2020-09-10 16:04
OK, reopening and pinging @JKE-be to see.

**Comment by yaodongshi** [comment] 2020-09-10 16:26
@pedrobaeza @Yenthe666 Thanks for the reply, I found that the reward discount product refers to the total amount discount amount product. I think this is how the official designs the product.

**Comment by maitaoriana** [comment] 2020-10-14 19:01
I have a error look like this and it can be replicated on Odoo 12 and 13. 
**Steps to reproduce:**

1. Create a promotion and exclude one product. 
2. Create a sale order add the excluded product and other product.
3. Insert promotion plan

**Current behavior:**
Both products have discount. 
Expected behavior:
The product was excluded must not have discount. 
![SO040-Odoo](https://user-images.githubusercontent.com/17258001/96033014-e3a18100-0e35-11eb-8adf-f04af156deab.png)

I understand that I selected "Discount Apply" --> "On order", but it should have one way that to exclude products of the discounts  or indicate which products must have discount. Maybe "Discount Apply" --> Products List (same logic of Based on products) 

Video https://drive.google.com/file/d/1wswp33hWQfQtRzo8R9DHuOqHYpmzTs72/view

**Comment by rdeodoo** [comment] 2020-10-23 15:36
I confirm there is nothing wrong here, the "Based on product" field is the trigger field, it means whenever this condition is met, the reward is given.
Then if "Discount apply on" is set to "On order", the discount will be on the full order indeed.

@maitaoriana About your flow, I get it is not very convenient since the exclude rule in "Based on product" is a domain while "Discount apply on" is a list picker, but ultimately you can do it.

There is definitely room for improvement regarding some coupons flows, it is already in our pipe but nothing priority for now.

**Closed by rdeodoo** 2020-10-23 15:36 UTC
Labels: Website

**Comment by rb3606** [comment] 2021-07-12 07:22
@yaodongshi Can you give me answer how you solve issue for apply discount for "Based on Domain" product. Currently its applying for full order(all products) even i selected domain in rule.
