### ISSUE TITLE
[10.0] Sticky notes, soft return

### ISSUE THREAD

**Issue by grzekru** [odoo/odoo#18109] opened 2017-07-09 14:13 UTC
Impacted versions: 10.0

Steps to reproduce: Create new sticky note, write few characters, press shift+enter two times

Current behavior: Odoo Client Error

Expected behavior: Create soft return

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment] 2017-07-10 08:12
Hi @grzekru,

Thank you for your report.
I've just tested this and I can confirm it does indeed throw a client error:
![image](https://user-images.githubusercontent.com/6352350/28008513-257d0e94-6558-11e7-80c1-e98975f72b23.png)
@nim-odoo I believe you're the summernote expert?

Regards,
Yenthe

**Comment by Yenthe666** [comment] 2018-02-11 14:36
Hi @grzekru,

I've just tested this again and it seems to be fixed in the meanwhile.
Please update your source code in order to fix the issue at your end. If you can still reproduce it then please do respond back.

Regards,
Yenthe

**Closed by Yenthe666** 2018-02-11 14:36 UTC
Labels: Confirmed
