### ISSUE TITLE
psycopg2.ProgrammingError: ON CONFLICT DO UPDATE command cannot affect row a second time

### ISSUE THREAD

**Issue by m3asmi** [odoo/odoo#35483] opened 2019-08-06 09:34 UTC
Impacted versions:
12.0
Steps to reproduce:
run update all modules 
Current behavior:
```
2019-08-06 09:36:06,363 8574 INFO database12 odoo.tools.translate: loading /opt/odoo/odoo12.e/odoo/addons/calendar/i18n/nl_BE.po 
2019-08-06 09:30:47,125 7490 INFO database12 odoo.tools.translate: loading /opt/odoo/odoo12.e/odoo/addons/calendar/i18n/nl_BE.po 
2019-08-06 09:30:47,135 7490 DEBUG database12 odoo.addons.base.models.ir_translation: ir.translation.cursor: We have 43 entries to process 
2019-08-06 09:30:47,139 7490 ERROR database12 odoo.sql_db: bad query: b" INSERT INTO ir_translation(name, lang, res_id, src, type, value, module, state, comments)\n                           SELECT name, lang, res_id, src, type, value, module, state, comments\n                           FROM tmp_ir_translation_import\n                           WHERE type = 'model'\n                           AND noupdate IS NOT TRUE\n                           ON CONFLICT (type, lang, name, res_id) WHERE type = 'model'\n                            DO UPDATE SET (name, lang, res_id, src, type, value, module, state, comments) = (EXCLUDED.name, EXCLUDED.lang, EXCLUDED.res_id, EXCLUDED.src, EXCLUDED.type, EXCLUDED.value, EXCLUDED.module, EXCLUDED.state, EXCLUDED.comments)\n                            WHERE EXCLUDED.value IS NOT NULL AND EXCLUDED.value != '';\n                       "
ERROR: ON CONFLICT DO UPDATE command cannot affect row a second time
HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
 
2019-08-06 09:30:47,143 7490 WARNING database12 odoo.modules.loading: Transient module states were reset 
2019-08-06 09:30:47,148 7490 ERROR database12 odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/opt/odoo/odoo12/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo12/odoo/modules/loading.py", line 417, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/opt/odoo/odoo12/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/odoo12/odoo/modules/loading.py", line 231, in load_module_graph
    module.with_context(overwrite=overwrite)._update_translations()
  File "/opt/odoo/odoo12.e/odoo/addons/base/models/ir_module.py", line 885, in _update_translations
    self.env['ir.translation'].load_module_terms(mod_names, filter_lang)
  File "/opt/odoo/odoo12.e/odoo/addons/base/models/ir_translation.py", line 825, in load_module_terms
    tools.trans_load(self._cr, trans_file, lang, verbose=False, module_name=module_name, context=context)
  File "/opt/odoo/odoo12/odoo/tools/translate.py", line 1016, in trans_load
    result = trans_load_data(cr, fileobj, fileformat, lang, verbose=verbose, module_name=module_name, context=context)
  File "/opt/odoo/odoo12/odoo/tools/translate.py", line 1160, in trans_load_data
    irt_cursor.finish()
  File "/opt/odoo/odoo12.e/odoo/addons/base/models/ir_translation.py", line 156, in finish
    """ % (self._model_table, self._table))
  File "/opt/odoo/odoo12/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/odoo12/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: ON CONFLICT DO UPDATE command cannot affect row a second time
HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.

2019-08-06 09:30:47,152 7490 CRITICAL database12 odoo.service.server: Failed to initialize database 'database12'. 
Traceback (most recent call last):
  File "/opt/odoo/odoo12/odoo/service/server.py", line 1116, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/opt/odoo/odoo12/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo12/odoo/modules/loading.py", line 417, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/opt/odoo/odoo12/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/odoo12/odoo/modules/loading.py", line 231, in load_module_graph
    module.with_context(overwrite=overwrite)._update_translations()
  File "/opt/odoo/odoo12.e/odoo/addons/base/models/ir_module.py", line 885, in _update_translations
    self.env['ir.translation'].load_module_terms(mod_names, filter_lang)
  File "/opt/odoo/odoo12.e/odoo/addons/base/models/ir_translation.py", line 825, in load_module_terms
    tools.trans_load(self._cr, trans_file, lang, verbose=False, module_name=module_name, context=context)
  File "/opt/odoo/odoo12/odoo/tools/translate.py", line 1016, in trans_load
    result = trans_load_data(cr, fileobj, fileformat, lang, verbose=verbose, module_name=module_name, context=context)
  File "/opt/odoo/odoo12/odoo/tools/translate.py", line 1160, in trans_load_data
    irt_cursor.finish()
  File "/opt/odoo/odoo12.e/odoo/addons/base/models/ir_translation.py", line 156, in finish
    """ % (self._model_table, self._table))
  File "/opt/odoo/odoo12/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/odoo12/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: ON CONFLICT DO UPDATE command cannot affect row a second time
HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.

2019-08-06 09:30:47,152 7490 INFO database12 odoo.service.server: Initiating shutdown 
2019-08-06 09:30:47,153 7490 INFO database12 odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2019-08-06 09:30:47,153 7490 DEBUG database12 odoo.service.server: current thread: <_MainThread(MainThread, started 140402194773824)> 
2019-08-06 09:30:47,153 7490 DEBUG database12 odoo.service.server: process <_MainThread(MainThread, started 140402194773824)> (False) 
2019-08-06 09:30:47,153 7490 DEBUG database12 odoo.service.server: -- ```

**Comment by pedrobaeza** [comment] 2019-08-06 09:40
This is because you have started from a database with duplicated translations. Can it be, @mart-e ?

**Comment by mart-e** [comment] 2019-08-06 09:44
Could be.
@m3asmi could you please give a bit more context.
Which language is installed?
Which file was it processing _before_ the error?
Can you reproduce it on a [runbot](http://runbot.odoo.com/runbot) or only on your database?

**Comment by m3asmi** [comment] 2019-08-06 09:46
@mart-e I update the issue: this is the file ` /opt/odoo/odoo12.e/odoo/addons/calendar/i18n/nl_BE.po `

**Comment by mart-e** [comment] 2019-08-06 09:50
Thanks. Is you code up to date? Can you upload the content of this file?

**Comment by m3asmi** [comment] 2019-08-06 10:05
I updated the code and rerun the update now it's fine, thank you @mart-e

**Comment by mart-e** [comment] 2019-08-06 10:06
Thanks for the update, glad it is fixed in recent version

**Closed by mart-e** 2019-08-06 10:06 UTC

**Comment by m3asmi** [comment] 2019-08-06 10:27
> This is because you have started from a database with duplicated translations. Can it be, @mart-e ?

how can I know which line is duplicated in the file ?

**Comment by mart-e** [comment] 2019-08-06 10:31
You were probably missing this fix

https://github.com/odoo/odoo/commit/57884ccdc8621f7c489a24e0bb89ac6b47763e12#diff-b1089d8c84e8807ac92f10373c0332c5

**Comment by m3asmi** [comment] 2019-08-06 10:45
thank you @mart-e that what I noticed from comparing some files replacing `model` by `model_terms` in ir.ui.view
