### ISSUE TITLE
Can't start odoo because module urllib2 can't be imported 

### ISSUE THREAD

**Issue by filipvuksan** [odoo/odoo#26806] opened 2018-09-05 15:16 UTC
Impacted versions: 11.0

Current behavior:

I cloned the git repo, imported the project into pycharm. i installed a virtual python env with pipenv for python 3.5. i installed the requirements.txt with pip3. when i start odoo this error occurs: 

![error_11](https://user-images.githubusercontent.com/43007075/45102253-9b2f1980-b12d-11e8-8800-e2ac3dbb9ab2.png)

I tried to install the urllib2 but i does not find the package. i searched on stackoverflow and what i found was this: https://stackoverflow.com/questions/2792650/import-error-no-module-name-urllib2

Also here is my start config for pycharm:

![config](https://user-images.githubusercontent.com/43007075/45102459-17c1f800-b12e-11e8-9c42-6ae180cf9a7e.png)

**Comment by pedrobaeza** [comment] 2018-09-05 15:18
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/11.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

**Closed by pedrobaeza** 2018-09-05 15:18 UTC

**Comment by gdgellatly** [comment] 2018-09-06 09:45
The problem is pipenv I think. I've found it doesn't understand complex
requirements files very well.

**Comment by and2carvalho** [comment] 2019-10-04 18:08
I'm facing the same issue with odoo 13 in debian buster. I've already searched in the web for solution but couldn't find nothing. @gdgellatly 's answer finally gave me some insight of couse of my problem... yes, i'm using pipenv for my virtual enviroment =/ Is there a solution for this or should I return to virtualenv ?

**Comment by AntonioMariaVigliotti** [comment] 2020-02-25 07:44
I met the same issue using pycharm and odoo 12. I do not use pipenv, I use virtualenv.
How did you solve this trouble?

**Comment by and2carvalho** [comment] 2020-02-26 16:16
running odoo without a virtual environment worked for me!
