### ISSUE TITLE
[9.0] web_editor’s 'font_to_img' route doesn’t work without authentication

### ISSUE THREAD

**Issue by gordonzola** [odoo/odoo#13106] opened 2016-08-10 13:55 UTC
Impacted versions:
- 9.0

Steps to reproduce:
1. In 'mass_mailing', create a mailing containing an icon image (specifically in the **Pictogram** section)
2. Send a test mail from this mailing
3. Log out from Odoo
4. check the test mail contents

Alternatively, without logging out, you can simply read your test mail on another computer

Current behavior:
- The image is not displayed, its URL returns a 404 status code, **except if** you’re logged in

Expected behavior:
- The image should be displayed.
- The 'font_to_img' route used to generate the pictogram is defined as public/unauthenticated, but this doesn’t seem to work.

Video/Screenshot link (optional):
![odoo_font_to_img](https://cloud.githubusercontent.com/assets/5214490/17556156/b2e23342-5f12-11e6-95b8-5bcc9ddee358.png)

**Comment by pedrobaeza** [comment] 2018-04-25 23:48
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-04-25 23:48 UTC
Labels: 9.0, Web editor
