### ISSUE TITLE
Odoo client error when editing task description with table

### ISSUE THREAD

**Issue by sy-github** [odoo/odoo#67806] opened 2021-03-14 15:41 UTC
Impacted versions:
13 & 14

Steps to reproduce:
create a task, add table to description and enter new lines above.

Current behavior:
There is a table in the description. When enter new lines above the table, exception occurs.

Expected behavior:
No exception. And new lines should appear like normal blank space, not like a 1x1 table above.

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/12111755/111074649-e505d100-84db-11eb-88df-d6edb3741283.png)

**Comment by sy-github** [comment] 2021-03-14 15:42
![image](https://user-images.githubusercontent.com/12111755/111074642-d6b7b500-84db-11eb-8028-3f93793af5ea.png)

**Comment by pedrobaeza** [comment] 2021-03-14 21:50
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Closed** 2023-04-07 14:22 UTC
Labels: Need information
