### ISSUE TITLE
enabling Discuss module raises Exception

### ISSUE THREAD

**Issue by timdlm** [odoo/odoo#13545] opened 2016-09-21 01:43 UTC
**Impacted versions:** 9.0c.20160921 and earlier

**Steps to reproduce:**
1. `apt-get install odoo` 9.0 nightly build on ubuntu 16.04.
2. `apt-get install apache2, mailutils, wkhtmltopdf, python-gevent, python-psycogreen` on same host.
3. configure apache with:
   
   ```
   ServerName ...
   
   <VirtualHost *:80>
   ProxyRequests Off
   
   <Proxy *>
       Order deny,allow
       Allow from all
   </Proxy>
   
   ProxyVia On
   
   ProxyPass / http://127.0.0.1:8069/
   <Location / >
       ProxyPassReverse /
   </Location>
   
   ProxyPass /longpolling/ http://127.0.0.1:8072/
   <Location /longpolling/ >
       ProxyPassReverse /longpolling/
   </Location>
   
   RequestHeader set "X-Forwarded-Proto" "https"
   
   # Fix IE problem (httpapache proxy dav error 408/409)
   SetEnv proxy-nokeepalive 1
   </VirtualHost>
   ```
4. configure db server.
5. configure odoo with:
   
   ```
   xmlrpc_interface = 127.0.0.1
   xmlrpc_port = 8069
   proxy_mode = True
   workers = 2
   db_host = ...
   db_port = ...
   db_user = ...
   db_password = ...
   ```
6. start odoo server
7. browse to localhost/ and fill out form to create odoo db
8. when presented with odoo apps page, install Discuss module

**Current behavior:**

Exception is observed in log:

```
2016-09-21 01:14:39,928 16193 ERROR xxxxx openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 321, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 314, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 964, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/bus/controllers/main.py", line 34, in poll
    raise Exception("bus.Bus unavailable")
Exception: bus.Bus unavailable
2016-09-21 01:14:39,930 16193 INFO xxxxx werkzeug: 127.0.0.1 - - [21/Sep/2016 01:14:39] "POST /longpolling/poll HTTP/1.1" 200 -
```

**Expected behavior:**

No exception should be raised.

**Additional information:**

I have done a bit of research and debugging on this, read through similar issues such as #3793 and have an otherwise perfectly working install, AFAIK.  The crux of the problem seems to be that longpolling is incompatible with multi-process mode (workers != 0), in contradiction to [documentation](https://www.odoo.com/documentation/9.0/setup/deploy.html) which states that longpolling _requires_ multi-process mode.

Turning multi-process mode off (setting workers = 0) makes the exception go away, but also makes the longpolling listener on port 8072 go away.  I assume this causes the Discuss module not to function properly.  I am brand new to odoo and setting up an instance for the first time so I cannot confirm or refute that.

There is a simple explanation for this behavior in the code (openerp/addons/bus/models/bus.py):

```
    def start(self):
        if openerp.evented:
            # gevent mode
            import gevent
            self.Event = gevent.event.Event
            gevent.spawn(self.run)
        elif openerp.multi_process:
            # disabled in prefork mode               <---------------------------
            return
        else:
            # threaded mode
            self.Event = threading.Event
            t = threading.Thread(name="%s.Bus" % __name__, target=self.run)
            t.daemon = True
            t.start()
```

I would like to know how to have the Discuss module working without exceptions getting raised.  Thanks in advance for your help.

**Video/Screenshot link (optional):**

**Comment by joolsr** [comment] 2016-09-23 20:42
I use Nginx with a multi-process on ie workers is greater than 0 (i have this set to 2 or 3 AFAIR).

Getting exactly the right config with a proxy is a pain especially with things like this and/or getting the https:// working for everything like slides where odoo sometimes goes back to providing http data.

All I can suggest is try looking at the odoo docs as they are best and look at a few other guides on how to setup with apache/nginx proxying. But all i can say is that Discuss **can** work but is fiddly to get just right ...

Good luck

Julian

**Comment by Ark74** [comment] 2018-01-02 11:07
@timdlm did you fid the apache configuration?

Seems like odoo prefer very much nginx over apache u_u since seems there is no documentation to configure apache with longpolling correctly.

 Cheers!

**Comment by pedrobaeza** [comment] 2018-04-29 00:26
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/11.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

**Closed by pedrobaeza** 2018-04-29 00:26 UTC
Labels: 9.0
