### ISSUE TITLE
[12.0] Sales | Quotations | Template error - Uncaught TypeError: o.replace is not a function

### ISSUE THREAD

**Issue by zozolpl** [odoo/odoo#60211] opened 2020-10-17 10:44 UTC
Impacted versions: 12

Steps to reproduce: Chose template when creating quotation

Current behavior: Error

Expected behavior: Apply template 

Hello, For some time now, odoo returns an error when selecting a Quotation template while creating quotes in the sales module.

The error only appears with new quotes. If I edit the quote that was created before the error appeared, you can change the template without error.

I did not install new modules, nor did I make configuration changes that could affect it.

The full text of the error below.

```
Uncaught TypeError: o.replace is not a function
https://xx.com/web/content/25026-062bb19/web.assets_backend.js:3545
Traceback:
TypeError: o.replace is not a function
    at
https://xx.com/web/content/25026-062bb19/web.assets_backend.js:3545:5623
    at
Aw.<anonymous>
(https://xx.com/web/content/25026-062bb19/web.assets_backend.js:3545:6717)
    at kg.c.fire
(https://xx.com/web/content/25026-062bb19/web.assets_backend.js:3509:183092)
    at Aw.fire
(https://xx.com/web/content/25026-062bb19/web.assets_backend.js:3509:183604)
    at bw
(https://xx.com/web/content/25026-062bb19/web.assets_backend.js:3509:327179)
    at Aw.setContent
(https://xx.com/web/content/25026-062bb19/web.assets_backend.js:3509:334681)
    at Class.reset
(https://xx.com/web/content/25026-062bb19/web.assets_backend.js:3616:59)
    at
https://xx.com/web/content/25026-062bb19/web.assets_backend.js:1559:237
    at
Function._.each._.forEach
(https://xx.com/web/content/19216-2fd958a/web.assets_common.js:12:558)
    at
Class.confirmChange
(https://xx.com/web/content/25026-062bb19/web.assets_backend.js:1559:78)
```

I also tried updating odoo to the latest github version

**Comment by pedrobaeza** [comment] 2020-10-17 20:43
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by zozolpl** [comment] 2020-10-19 08:57
Hello

[bandicam 2020-10-19 10-40-22-428.zip](https://github.com/odoo/odoo/files/5400441/bandicam.2020-10-19.10-40-22-428.zip)

Video showing the error - short description.
SO176 - this is a valuation from 6 months ago - I choose other valuation templates and an error comes out, but only after one in a row selection.

Then I open a new quote and the error always appears when choosing a template for the first time.

After receiving the error, I cannot do anything until the page is refreshed (F5)

I am convinced that the error was not caused by module installation or any changes to the source code.

They may be due to the removal of some default product from inventory (we were cleaning up), but I cannot locate it. All items were archived, restoring them did not fix the problem.
I also tried to create a new template that only uses one product, but that didn't help.

The problem may also be with linux and software update.

I have python v 3.6.9 and 3.8.6 installed, but I don't know which odoo is used by.

**Closed** 2023-04-06 09:43 UTC
Labels: 12.0, Sales
