### ISSUE TITLE
<field name="attribute_line_ids">' cannot be located in parent view

### ISSUE THREAD

**Issue by mcassuto** [odoo/odoo#2379] opened 2014-09-12 20:19 UTC
I installed a DB few weeks ago and update the code yesterday.
After an update=all, I am unable to log in again.

Server log gives:
2014-09-12 19:35:16,381 25947 INFO talsom openerp.modules.loading: loading product/views/report_pricelist.xml
2014-09-12 19:35:16,665 25947 ERROR talsom openerp.addons.base.ir.ir_ui_view: Element '<field name="attribute_line_ids">' cannot be located in parent view

Error context:
View `product.template.form`
[view_id: 290, xml_id: product.product_template_form_view_variant_button, model: product.template, parent_id: 283]

**Comment by sle-odoo** [comment] 2016-06-13 15:12
Hi,
I can't reproduce this issue with the latest code. It was probably fixed in the meantime.

Regards

**Closed by sle-odoo** 2016-06-13 15:12 UTC
