### ISSUE TITLE
[13.0][BUG]Error returns because slides of category type are not listed

### ISSUE THREAD

**Issue by ieski** [odoo/odoo#58549] opened 2020-09-28 00:03 UTC
Impacted versions:
13.0
 Steps to reproduce:
Records added as e-learning section

Error:
File "/usr/lib/python3/dist-packages/odoo/addons/website_slides/controllers/main.py", line 92, in _get_slide_detail    slide_index = channel_slides_ids.index(slide.id)ValueError: 121 is not in list

Exception Line: 
https://github.com/odoo/odoo/blob/422f7f4a9c4d5ad60c63c6d20c9bf8ddda9a3966/addons/website_slides/controllers/main.py#L92

Code to fix:
https://github.com/odoo/odoo/blob/422f7f4a9c4d5ad60c63c6d20c9bf8ddda9a3966/addons/website_slides/models/slide_channel.py#L212

fix:
```python
    @api.depends('slide_ids.is_category')
    def _compute_category_and_slide_ids(self):
        for channel in self:
            channel.slide_category_ids = channel.slide_ids.filtered(lambda slide: slide.is_category)
            channel.slide_content_ids = channel.slide_ids
```

**Comment by pedrobaeza** [comment] 2020-09-28 06:44
Can you add the steps to reproduce a problem, crash or similar?

**Comment by ieski** [comment] 2020-09-28 06:56
Hi,

When you create sections in the e-learning "slide.slide" content, it throws this error into the logs.

https://prnt.sc/up304g

**Comment by pedrobaeza** [comment] 2020-09-28 07:02
Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by sswapnesh** [comment] 2020-10-02 16:46
Hello @ieski 
I have tried Reproducing the Same but It is working well.

Created Course with Multiple Section 
![Screenshot from 2020-10-02 22-09-27](https://user-images.githubusercontent.com/16624719/94947848-f6de5380-04fb-11eb-9004-517fce44a7bb.png)
I am able to see it on website Without any error.


The error you are facing is due to Previewing wrong Slide (Which is actually section) so Please check the URL on which facing this Issue.


-----------------------------
The fix you provided is not related to this as You are trying to make slide_content_ids same as slide_ids
slide_content_ids is used for Actual slides which contain content. (Real Slides to be Previewed)
slide_ids is used for all slides including Section.

**Comment by pedrobaeza** [comment] 2020-10-04 15:54
Good explanation, @sswapnesh. Indeed, direct visualization of section slides is not possible through UI, and forcing it through the URL leads to this.

**Closed by pedrobaeza** 2020-10-04 15:54 UTC
Labels: 13.0, Need information

**Comment by delacruzleonardo2019** [comment] 2021-05-04 18:38
Error
 
slide_index = channel_slides_ids.index(slide.id) 

Solución

slide_chanel.py Line 212

channel.slide_content_ids = channel.slide_ids - channel.slide_category_ids
