### ISSUE TITLE
Web_Login_Error

### ISSUE THREAD

**Issue by urbmend26** [odoo/odoo#30381] opened 2019-01-20 17:51 UTC
Impacted versions: 11 Enterprise

Steps to reproduce: Enter at odoo url and see blank Background.

Current behavior:
```
login:20 GET https://192.168.2.17/web/content/12530-e8b4fe4/web.assets_common.0.css net::ERR_ABORTED 403 (FORBIDDEN)
login:21 GET https://192.168.2.17/web/content/14631-b77330e/web.assets_frontend.0.css net::ERR_ABORTED 403 (FORBIDDEN)
2login:23 GET https://192.168.2.17/web/content/14632-b77330e/web.assets_frontend.js net::ERR_ABORTED 403 (FORBIDDEN)
web.assets_common.js:3776 warning: Some modules could not be started
web.assets_common.js:3776 Missing dependencies:     ["web.session"]
web.assets_common.js:3780 Non loaded modules:       (9) ["web.AjaxService", "web_editor.base", "web_editor.ready", "web_editor.ace", "web.planner.common", "web_tour.TourManager", "web_tour.tour", "project_timesheet_synchro.test_screen_navigation", "account_reports.tour"]
```

Expected behavior:

Web login Background

Video/Screenshot link (optional):

![odoo_login_error](https://user-images.githubusercontent.com/39883453/51442751-949cdb00-1ca5-11e9-97f2-1b59f30f7cf1.png)

![odoo_login_error_sources](https://user-images.githubusercontent.com/39883453/51443037-2eb25280-1ca9-11e9-8bda-4abdc37249a5.PNG)

**Comment by pedrobaeza** [comment] 2019-01-20 17:55
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Boudmir-Ibrahim** [comment] 2019-01-21 09:16
@urbmend26 , 
have you made any changes on the login web page ? 
It seems to me that the problem comes from a custom module that you have added. 
I do not encounter any problem with logging into V11 Entreprise using the runbot.

**Comment by urbmend26** [comment] 2019-01-21 14:03
@Boudmir-Ibrahim 

Thanks for answering. I have two odoo servers with the same modules in one works well but this one suddenly I present this problem. I use an Odoo_web_Login module in both the uninstall and the same problem.

What I see in the debug is that it can not find a few ccs and js, but I can not find the folder / web / content to be able to check if the problem with permissions.

GET http://192.168.2.17:8069/web/content/14768-e8b4fe4/web.assets_common.0.css net :: ERR_ABORTED 403 (FORBIDDEN)
login? debug = asset: 22 GET http://192.168.2.17:8069/web/content/14772-e8b4fe4/web.assets_common.js net :: ERR_ABORTED 403 (FORBIDDEN)
login? debug = asset: 21 GET http://192.168.2.17:8069/web/content/14775-c9de6b5/web.assets_frontend.0.css net :: ERR_ABORTED 403 (FORBIDDEN)
2login? Debug = asset: 23 GET http://192.168.2.17:8069/web/content/14776-c9de6b5/web.assets_frontend.js net :: ERR_ABORTED 403 (FORBIDDEN)

**Comment by mart-e** [comment] 2020-03-05 08:28
Hi,

Please publish your errors with `debug=assets` mode, otherwise we can not do anything with the error.
Closing as most likely due to the custom Odoo_web_Login module.
If you have more information and give us a way to reproduce on a standard Odoo (try on runbot as Pedro suggested), we can reopen

Best,

**Closed by mart-e** 2020-03-05 08:28 UTC
Labels: Need information

**Comment by marvar81** [comment] 2021-03-01 17:03
> Impacted versions: 11 Enterprise
> 
> Steps to reproduce: Enter at odoo url and see blank Background.
> 
> Current behavior:
> 
> ```
> login:20 GET https://192.168.2.17/web/content/12530-e8b4fe4/web.assets_common.0.css net::ERR_ABORTED 403 (FORBIDDEN)
> login:21 GET https://192.168.2.17/web/content/14631-b77330e/web.assets_frontend.0.css net::ERR_ABORTED 403 (FORBIDDEN)
> 2login:23 GET https://192.168.2.17/web/content/14632-b77330e/web.assets_frontend.js net::ERR_ABORTED 403 (FORBIDDEN)
> web.assets_common.js:3776 warning: Some modules could not be started
> web.assets_common.js:3776 Missing dependencies:     ["web.session"]
> web.assets_common.js:3780 Non loaded modules:       (9) ["web.AjaxService", "web_editor.base", "web_editor.ready", "web_editor.ace", "web.planner.common", "web_tour.TourManager", "web_tour.tour", "project_timesheet_synchro.test_screen_navigation", "account_reports.tour"]
> ```
> 
> Expected behavior:
> 
> Web login Background
> 
> Video/Screenshot link (optional):
> 
> ![odoo_login_error](https://user-images.githubusercontent.com/39883453/51442751-949cdb00-1ca5-11e9-97f2-1b59f30f7cf1.png)
> 
> ![odoo_login_error_sources](https://user-images.githubusercontent.com/39883453/51443037-2eb25280-1ca9-11e9-8bda-4abdc37249a5.PNG)

Did you find the solution???

**Comment by marvar81** [comment] 2021-03-01 17:03
Did you find the solution??

**Comment by GuM0x1a** [comment] 2021-03-04 16:58
> Did you find the solution??

Yes, update the Odoo [Base] Module.
