### ISSUE TITLE
[9.0] VAT 0% on Tax summary on Invoice view

### ISSUE THREAD

**Issue by Bartii** [odoo/odoo#10671] opened 2016-01-28 22:48 UTC
According to Polish law, there should be listed tax lines with all VAT values including:
- VAT 0%, 
- non VAT (not the same as 0%) 
- tax exempt. 

Impacted versions:
Version: 9.0

Current behavior:
Tax lines related with invoice contain only non 0 vat values.

Expected behavior:
all tax line must be presented with appropriate vat values.
I understand it is not required everywhere so this option could be configure

Regards

**Comment by zbik2607** [comment] 2017-04-12 12:30
+1 

To generate zero tax_line, in method tax_line_move_line_get (in account_invoice.py)
you replace line:

if tax_line.amount:

by
 
if tax_line.amount or isinstance(tax_line.amount, float):

**Comment by pedrobaeza** [comment] 2018-04-11 22:49
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-04-11 22:49 UTC
Labels: 9.0, Accounting
