### ISSUE TITLE
[12.0] @api.constrains consumes id while raising validation error

### ISSUE THREAD

**Issue by crtmneric** [odoo/odoo#43340] opened 2020-01-15 12:46 UTC
Impacted versions:
12.0
Steps to reproduce:
Write a function with @api.constraints method with an easy condition that raises an validation error. Than create a new record passes the condition u have wrote that in decorator method than create another record that inapplicable for the condition u have wrote. The new record's id is now incremented +2 even though that latest record wasnt created beacuse of the validation error ?
Current behavior:
Isnt that an id consume situation ?
Expected behavior:
new records id should be +1 incremented.
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2020-01-15 12:49
That's something on the ORM/PostgreSQL combination, but where is the problem?

**Comment by Yenthe666** [comment] 2020-01-15 13:53
That's framework behaviour, something similar will happen if you try to import a CSV that fails. It also consumes ID's in the table without them being used as a rollback deletes them again but the increment continues on the table ID's. @Elkasitu can probably confirm this

**Comment by crtmneric** [comment] 2020-01-16 04:12
> That's something on the ORM/PostgreSQL combination, but where is the problem?

When we try to use sequence to generate report id's yearly and people want to see total report numbers yearly when they look at the report. When we use sequence to generate report numbers then validation errors consumes id's so the report numbers isnt correctly generated with ir.sequence



> That's framework behaviour, something similar will happen if you try to import a CSV that fails. It also consumes ID's in the table without them being used as a rollback deletes them again but the increment continues on the table ID's. @Elkasitu can probably confirm this

So actually ORM is creating a record then when it rollsback and deletes, it looks like it shouldnt just create the record instead of rolling back.

**Comment by pedrobaeza** [comment] 2020-01-16 08:49
The problem is the way Postgres uses `nextval` AFAIK. Have you tried with `nogap` sequences?

**Comment by gdgellatly** [comment] 2020-01-16 08:50
Its kind of unavoidable. Sequences are consumed even during rollbacks, because a subsequent transaction may already have acquired `nextval`.

**Comment by crtmneric** [comment] 2020-01-17 04:54
After googling a bit about psql nextval logic i get what u meant 

> The problem is the way Postgres uses `nextval` AFAIK. Have you tried with `nogap` sequences?

by this;

> To avoid blocking concurrent transactions that obtain numbers from the same sequence, a nextval operation is never rolled back; that is, once a value has been fetched it is considered used, even if the transaction that did the nextval later aborts. This means that aborted transactions might leave unused "holes" in the sequence of assigned values.

So ir.sequence is actually psql nextval and it never rolls back so it consumes id's,
by the way i just heart about nogap from you and i m going to ctrl+shift+f that in source code ! :D Thank you for awesome works & quick, informative replys.

@Yenthe666 i learnt alot from your guides, tutorials and forum responses it's nice to have a chance to say thank you !

**Comment by Yenthe666** [comment] 2020-01-17 15:01
I'm happy to hear that @crtmneric and it's my pleasure!
I guess we can conclude that it is done with a reason, it's built-in and nothing that's going to change. If you don't mind I think we can close this report? :)

**Closed** 2020-01-18 06:44 UTC
