### ISSUE TITLE
[11.0] Web Client OnChange JS error in case of pagination in the embedded list view

### ISSUE THREAD

**Issue by wtaferner** [odoo/odoo#21008] opened 2017-11-16 14:41 UTC
**Impacted versions:**
saas-16 and above

**Steps to reproduce:**
Create an invoice with more than 40 lines. Keep the pagination and try to delete a line. It will crash for undefined list variable. Remove the pagination by setting it 1-your_number_of_lines and try again...it will work without any issue.

If you are fast enough, here is already an instance and an object you can use and test.
[Runbot](http://278705-11-0-d71b75.runbot9.odoo.com/web?debug=assets#id=124&view_type=form&model=account.invoice&action=363&active_id=11&menu_id=228
)

**Current behavior:**
Javascript crash due to undefined object in case x2many embedded tree view is triggering an on change.

```javascript

basic_model.js:1346 Uncaught TypeError: Cannot read property 'id' of undefined
    at basic_model.js:1346
    at Function._.each._.forEach (underscore.js:150)
    at Class._applyOnChange (basic_model.js:1256)
    at basic_model.js:1394
    at Function._.each._.forEach (underscore.js:145)
    at basic_model.js:1352
    at Function._.each._.forEach (underscore.js:150)
    at Class._applyOnChange (basic_model.js:1256)
    at Object.<anonymous> (basic_model.js:3420)
    at Object.<anonymous> (jquery.js:3276)

```

**Expected behavior:**
No flaws ;-)

@ged-odoo @nim-odoo 
Gerry, I think you will be more than happy to fix this, right? ;-) It took me some time to figure out how to reproduce it on runbot, but I guess the hardest part is done I hope :-)

**Comment by Yenthe666** [comment] 2017-11-16 14:44
Hi @wtaferner,

Thanks a lot for the bug report!
Tested and confirmed on your runbot instance. I like screenshots so:
![image](https://user-images.githubusercontent.com/6352350/32897071-f31db99c-cae4-11e7-8b94-7b776d595015.png)

Looks like a real issue yep.

**Comment by wtaferner** [comment] 2017-11-16 14:44
OPW-782974

**Comment by ged-odoo** [comment] 2017-11-20 10:07
fixed by commit https://github.com/odoo/odoo/commit/6cd17d575c7d970286ec3dfedcfacf01be5f7592 in saas-16

**Closed** 2017-11-20 10:08 UTC
Labels: 11.0, confirmed, Framework
