### ISSUE TITLE
Unable to open the module list via Website

### ISSUE THREAD

**Issue by EdwinvWees** [odoo/odoo#29390] opened 2018-12-10 13:43 UTC
Unable to open the module list via website on IOS (Safari Browser)

Impacted versions:
V11C

Steps to reproduce:

1. Navigate to your Odoo website
2. Login as an internal user
3. Click in the top left corner on the module selector

Current behavior:
Nothing happens

Expected behavior:
You will be navigated to the module list so that you can select a module.

Video/Screenshot link (optional):
https://drive.google.com/file/d/1v_6lD7BHsff7jolo9CU81PBgOUq06k-D/view

**Comment by Yenthe666** [comment] 2018-12-10 14:10
@JKE-be I've seen it on a co-worker his iphone, does seem to be an issue. Can one of you guys check it please? 🍺

**Comment by JKE-be** [comment] 2018-12-12 16:57
confirmed on my iphone

**Comment by Yenthe666** [comment] 2018-12-28 15:37
@JKE-be any update? 🙏 We have a complaining customer now hehe.

**Comment by ploegvde** [comment] 2019-01-06 10:54
@JKE-be Can you have a look to fix this?

**Comment by lukebranch** [comment] 2019-01-07 09:38
This same issue existed in 10.0:
https://github.com/odoo/odoo/issues/15551

and was fixed here:

https://github.com/odoo/odoo/commit/3dcc54ccf46c38df308a6af2ecaf2826a95f1fa0

**Comment by JKE-be** [comment] 2019-01-07 11:16
@lukebranch 

Thanks for reminder.
We are investigate about this issue.

Strangely, it is reproducible on my iPhone but not in the Chrome emulator.
In the past (from memory), when we fixed it in v10, it was reproductible in chrome emulator :/

Edit: It is a problem that a appear only with safari due to a overflow:hidden

**Comment by qsm-odoo** [comment] 2019-01-24 13:05
Hello, the bug should be solved in 10.0 with https://github.com/odoo/odoo/commit/caacd95a8787b2874a129753b7e5439d0c0c02e8 that just got merged. A little bit more of patience to wait for forward-port in 11.0 and it should be ok ! Closing the issue, don't hesitate if it is not solved later on.

**Closed by qsm-odoo** 2019-01-24 13:05 UTC
Labels: 11.0, Confirmed, Website

**Comment by Yenthe666** [comment] 2019-01-24 13:18
@ploegvde can you please update one of our 10.0 instances and then check on your iPhone?

**Comment by Yenthe666** [comment] 2019-01-24 14:04
Tested & confirmed on 10.0, it works.
