### ISSUE TITLE
Odoo Server Error when trying to install Invoicing

### ISSUE THREAD

**Issue by akapa100** [odoo/odoo#38698] opened 2019-10-14 09:57 UTC
Impacted versions:
13
Steps to reproduce:
Try to install Invoicing module by Odoo S.A.
Current behavior:
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 713, in parse
    self._tag_root(de)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 675, in _tag_root
    f(rec)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 675, in _tag_root
    f(rec)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 578, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3963, in _load_records
    data['record']._load_records_write(data['values'])
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3901, in _load_records_write
    self.write(values)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3451, in write
    field.write(self, vals[fname])
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1493, in write
    tname, 'model', lang, real_recs._ids, value, source_value,
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_translation.py", line 275, in _set_ids
    for res_id in set(ids) - set(existing_ids)
  File "<decorator-gen-47>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 359, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_translation.py", line 540, in create
    records = super(IrTranslation, self.sudo()).create(vals_list).with_env(self.env)
  File "<decorator-gen-3>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 359, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3652, in create
    records = self._create(data_list)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3769, in _create
    cache_value = field.convert_to_cache(value, record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 2162, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for ir.translation.lang: 'en_US'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1242, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1230, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 410, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 397, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-58>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 463, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 573, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 420, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 312, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 737, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 804, in convert_xml_import
    obj.parse(doc.getroot())
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 722, in parse
    exc_info[2]
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 13, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 713, in parse
    self._tag_root(de)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 675, in _tag_root
    f(rec)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 675, in _tag_root
    f(rec)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 578, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3963, in _load_records
    data['record']._load_records_write(data['values'])
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3901, in _load_records_write
    self.write(values)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3451, in write
    field.write(self, vals[fname])
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1493, in write
    tname, 'model', lang, real_recs._ids, value, source_value,
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_translation.py", line 275, in _set_ids
    for res_id in set(ids) - set(existing_ids)
  File "<decorator-gen-47>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 359, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_translation.py", line 540, in create
    records = super(IrTranslation, self.sudo()).create(vals_list).with_env(self.env)
  File "<decorator-gen-3>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 359, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3652, in create
    records = self._create(data_list)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3769, in _create
    cache_value = field.convert_to_cache(value, record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 2162, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
odoo.tools.convert.ParseError: "Wrong value for ir.translation.lang: 'en_US'" while parsing /usr/lib/python3/dist-packages/odoo/addons/product/data/product_data.xml:2, near
<odoo>
    <data noupdate="1">
        <record id="product_category_all" model="product.category">
            <field name="name">All</field>
        </record>
        <record id="product_category_1" model="product.category">
            <field name="parent_id" ref="product_category_all"/>
            <field name="name">Saleable</field>
        </record>
        <record id="cat_expense" model="product.category">
            <field name="parent_id" ref="product_category_all"/>
            <field name="name">Expenses</field>
        </record>

        
        <record forcecreate="True" id="decimal_price" model="decimal.precision">
            <field name="name">Product Price</field>
            <field name="digits">2</field>
        </record>
        <record forcecreate="True" id="decimal_discount" model="decimal.precision">
            <field name="name">Discount</field>
            <field name="digits">2</field>
        </record>
        <record forcecreate="True" id="decimal_stock_weight" model="decimal.precision">
            <field name="name">Stock Weight</field>
            <field name="digits">2</field>
        </record>
        <record forcecreate="True" id="decimal_volume" model="decimal.precision">
            <field name="name">Volume</field>
            <field name="digits">2</field>
        </record>
        <record forcecreate="True" id="decimal_product_uom" model="decimal.precision">
            <field name="name">Product Unit of Measure</field>
            <field name="digits" eval="3"/>
        </record>

        

        
        <record id="list0" model="product.pricelist">
            <field name="name">Public Pricelist</field>
            <field name="sequence">1</field>
        </record>

        

    </data>
</odoo>
Expected behavior:

**Comment by pedrobaeza** [comment] 2019-10-14 09:59
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin - base database)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by akapa100** [comment] 2019-10-14 10:54
@pedrobaeza I can't reproduce in the runbot infrastructure. This is a fresh install of Odoo there's no costume module.
When I click to install the Invoicing module, I get this message
![Screenshot_1](https://user-images.githubusercontent.com/22882537/66746186-13abf200-ee79-11e9-9ad0-f9c81b52fb95.png)
But imediatly afterwards it say "Back online"
When I click again a second time I get this:
![Screenshot_2](https://user-images.githubusercontent.com/22882537/66746254-3c33ec00-ee79-11e9-8e6c-07c8ed323842.png)

Also when going to the Settings in the menu I get another error:
![Screenshot_3](https://user-images.githubusercontent.com/22882537/66746322-62f22280-ee79-11e9-9cbd-ea179bb1a42a.png)

**Comment by pedrobaeza** [comment] 2019-10-14 10:56
Then should be a deployment problem or an outdated code. Please try again with latest code, and make sure you have at least PostgreSQL 9.6.

Closing meanwhile no other proof of possible Odoo problem.

**Closed by pedrobaeza** 2019-10-14 10:56 UTC
Labels: Need information

**Comment by akapa100** [comment] 2019-10-14 11:04
@pedrobaeza 
![image](https://user-images.githubusercontent.com/22882537/66746579-165b1700-ee7a-11e9-9a84-0eba22d472ba.png)

**Comment by pedrobaeza** [comment] 2019-10-14 11:06
That's not latest code, only latest package. See any way also about Postgres version. More doubts, please do them on forums.

**Comment by akapa100** [comment] 2019-10-14 11:12
@pedrobaeza My Postgres version is 11.5. How can I update my code?
