### ISSUE TITLE
Wishlist: comments field to be stored with UI presentation of Backups in Odoo.sh

### ISSUE THREAD

**Issue by geoff-bbc** [odoo/odoo#54286] opened 2020-07-09 18:57 UTC
In the Backups module of Odoo.sh it would be helpful to have a Comments field associated with each backup and some way to save comments. It would be helpful to be able to label or otherwise describe my reason for taking that backup and perhaps notes on the contents/configuration.

**Comment by Yenthe666** [comment] 2020-07-10 06:23
@dbo-odoo & @mart-e  can you pass this feedback along to the right people from the SH team?
Closing as its not a bug and not related to Odoo itself. 
P.S: next time you can log the feedback through official tickets at odoo.com/help 😉

**Closed by Yenthe666** 2020-07-10 06:23 UTC
