### ISSUE TITLE
Error when opening webpage frontend from linkedin

### ISSUE THREAD

**Issue by adrianplugandplay** [odoo/odoo#53358] opened 2020-06-19 20:57 UTC
Impacted versions:

Steps to reproduce:

Current behavior:
When opening any link of our company's website through linkedin, an error dialog opens (just in Android phones) Traceback:
TypeError: Cannot read property 'getItem' of null
    at Class.start (https://plugandplay.energy/web/content/3528-4f2dc34/1/web.assets_frontend_lazy.js:164:298)
    at Class.prototype.<computed> [as start] (https://plugandplay.energy/web/content/2077-ddf19a8/1/web.assets_common_lazy.js:3762:488)
    at https://plugandplay.energy/web/content/2077-ddf19a8/1/web.assets_common_lazy.js:3992:416
    at async Promise.all (index 0)
    at async Promise.all (index 19)
    at async Promise.all (index 1)

Remark that if I go into webpage with chrome for android or any other web browser, it works perfectly
Expected behavior:
Webpage showing perfectly in any case
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2020-06-20 10:40
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Closed** 2023-04-07 14:28 UTC
Labels: Need information
