### ISSUE TITLE
[9.0] Traceback when we try to add a follower on the blog from backend

### ISSUE THREAD

**Issue by jni-odoo** [odoo/odoo#9446] opened 2015-11-06 09:53 UTC
See the below steps to generate 

(1) Click on the app Website Admin

(2) Open any existing blog in the backend

(3) Click on Add follower (provide an email of the follower if not provided

 You will get 

https://drive.google.com/file/d/0B5j41T1Hqv1sR1dqbXJ3bHoyT3M/view?usp=drivesdk

Thanks & Regards
Nikunj Jani (Odoo India)

**Comment by Yenthe666** [comment] 2016-05-24 06:41
Hi @jni-odoo,

I can no longer reproduce this bug on the latest Odoo 9:
![image](https://cloud.githubusercontent.com/assets/6352350/15494526/32e9e348-218b-11e6-857c-2e8b3ba58298.png)

If you can still trigger this bug please let me know, I'll re-open this issue then. Closing this since it seems fixed.

Regards,
Yenthe

**Closed by Yenthe666** 2016-05-24 06:41 UTC
