### ISSUE TITLE
[16][stock] Inconsistency between locations of stock.move and stock.move.line

### ISSUE THREAD

**Issue by florian-dacosta** [odoo/odoo#113486] opened 2023-02-23 10:30 UTC
Impacted versions: 16.0

Steps to reproduce: 
- Install Purchase module with demo data
- Give your user the rights to manage multiple locations (group Manage Multiple Stock Locations)
- Go on the P00008 from supplier Ready mat, which is already confirmed (xml id : purchase_stock.purchase_order_8)
- Go on the reception and change the destination location of the picking from WH/Stock to WH/Input/Order Processing
- Click on validate button and then apply

Current behavior:
The stock is transfered to WH/Stock instead of WH/Input/Order Processing

Expected behavior:
The stock should be added in WH/Input/Order Processing

**Comment by AbdelAzizMohamedMousa** [comment] 2023-02-23 13:05
This issue seems to be a bug in the Purchase module of Odoo version 16.0. The issue occurs when the user changes the destination location of the picking from WH/Stock to WH/Input/Order Processing on the reception of an already confirmed purchase order. When the user clicks on the validate button, the stock is transferred to the wrong location (WH/Stock) instead of the intended location (WH/Input/Order Processing).

The expected behavior is that the stock should be added in the intended location (WH/Input/Order Processing).

To resolve this issue, you can try updating your Odoo instance to the latest version or contacting the Odoo support team for assistance.

**Comment by hparfr** [comment] 2023-02-24 13:58
True;  It's a bit disturbing.

![image](https://user-images.githubusercontent.com/8331206/221196466-c18c39dd-e9c1-4907-83ae-2009811915dc.png)

@Whenrow

**Comment by Whenrow** [comment] 2023-03-01 08:34
@hparfr I raised a simple error for the 16.0 in this [PR](https://github.com/odoo/odoo/pull/113962) version and maybe try to change the locations on the stock move line for the master version. It's not an easy part as the move lines can be created by reservation, putaway strategies or manually. This can also involve lot numbers, owners and packages.

**Closed** 2023-03-09 19:33 UTC
