### ISSUE TITLE
Odoo 13 Creates Duplicate Employee Record when using Create and Edit

### ISSUE THREAD

**Issue by sissieadmin** [odoo/odoo#49749] opened 2020-04-19 02:35 UTC
Impacted versions:

Ubuntu 18.04 LTS
Odoo 13.0.20200227

Steps to reproduce:

Create an employee through either the Recruitment form or directly in the Employees module.

When Create Employee is selected, it creates an Employee with no associated user account.

Go into HR Settings >  Related User > Create and Edit

Current behavior:

Create and Edit ...  the user produces an error:

` hr.employee(<NewId origin=149>,).exit_progress`

A new user is created but is not associated with the Employee  record. It creates a new Employee record separate from the record used to create it.

Expected behavior:

A new user account should be created and be associated with the Employee record. You should also be able to associate an existing User to an existing Employee record.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2020-04-19 11:02
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by sswapnesh** [comment] 2020-04-19 12:56
Seems duplicate of https://github.com/odoo/odoo/issues/44442 and fixed in https://github.com/odoo/odoo/pull/45411

@sissieadmin Can you please update the source code and try again?

(It works well on latest Runbot https://2257074-13-0-80dce3.runbot25.odoo.com/web#action=280&model=hr.employee&view_type=kanban&cids=&menu_id=204)

**Comment by pedrobaeza** [comment] 2020-04-19 14:03
OK, thanks for the followup, Swapnesh, then closing as already fixed.

**Closed by pedrobaeza** 2020-04-19 14:03 UTC
Labels: Need information

**Comment by sissieadmin** [comment] 2020-04-21 03:24
Upgrading resolved the issue.

**Comment by sissieadmin** [comment] 2020-04-23 01:38
I spoke too soon. We just had this issue reoccur. We created an employee from the Recruitment page, it created an employee record. We tried to create a user Account for that Employee through HR Settings, go the same error and it created an account associated with a different employee record and did not associate with the original.
