### ISSUE TITLE
[9.0] Stock picking forgets lot when it is processed partially

### ISSUE THREAD

**Issue by aisopuro** [odoo/odoo#11437] opened 2016-03-22 10:26 UTC
##### Impacted versions:
- 9.0

This issue is very similar to #7044, though not as critical. The fix by @nim-odoo seemed fairly straightforward, so maybe it will be equally easy for this?
##### Steps to reproduce:
1. Install `sale_stock`
2. Enable lot tracking and packages from Stock settings
3. Add a stockable product that has traceability set to "By lot" and add 10 stock for it. 
4. Make a sale using that product. Sell 5 units of the product.
5. On the resulting picking, click the "split lots" button on the line for the product
6. Gather 3 units of the product
7. Click "Put in Package"
8. Click the "split lots" button on the remaining line
##### Current behavior:

The wizard for selecting the amount to process from a selected lot or lots is shown, but the original lot has been forgotten, even if there was still enough stock in that lot to fulfill the picking.
##### Expected behavior:

The wizard should default to the original lot if there is still stock left for it, the same way that is done the first time the "split lots" button is pressed.

**Comment by Yenthe666** [comment] 2018-02-14 08:19
@nim-odoo any update on this one as you self assigned it?

**Comment by pedrobaeza** [comment] 2018-04-17 23:57
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-04-17 23:57 UTC
Labels: 9.0, Logistics
