### ISSUE TITLE
Latest pull in odoo v11, gives error on user creation

### ISSUE THREAD

**Issue by AnilKesariya** [odoo/odoo#23305] opened 2018-02-24 16:26 UTC
Impacted versions:
version v11, latest source code : 

commit 517b1d1faf97a8c4866a8bebcb13afa90f08771f
Author: Adrian Torres <adt@odoo.com>
Date:   Fri Feb 23 16:06:03 2018 +0100

Steps to reproduce:
Take latest pull in odoo v11, and try to create new user.

Current behavior:
Gives the following error on creation of new user.

Expected behavior:
The user should be able to created without any error.
Video/Screenshot link (optional):

![screenshot from 2018-02-24 21-55-27](https://user-images.githubusercontent.com/5101994/36632516-86b666f6-19ad-11e8-9d11-f1fba6c18aed.png)

**Comment by sswapnesh** [comment] 2018-02-24 17:41
@AnilKesariya 
Related/Duplicate of #23303

**Comment by AnilKesariya** [comment] 2018-02-26 05:23
@sswapnesh,
Yes, it was duplicated. thanks for report.

**Comment by rupareliyahemangi145** [comment] 2018-02-26 08:01
Quick solution to resolve the current issue.

1. Make sure the branch is taken with following command

 _git clone https://www.github.com/odoo/odoo --branch 11.0_

If the branch will be taken with following command then you will be able to checkout to the specific revision to avoid the issue. if you have used the yenthe script than you might not able to checkout because it does uses the following link : _git clone https://www.github.com/odoo/odoo branch 11.0 --single-branch --depth 1_
This won't allow you to checkout to **SHA**

This will solve the issue, once the issue resolve we can switch to latest pull back.

Hope this will help everyone,

Regards,
Hemangi.

**Closed** 2018-02-26 11:46 UTC
Labels: 11.0, Framework
