### ISSUE TITLE
Can't install modules from apps.odoo.com

### ISSUE THREAD

**Issue by mahmoudaljan** [odoo/odoo#25368] opened 2018-06-20 22:10 UTC
Impacted versions: 9, 10 & 11

Current behavior: We are unable to install modules from odoo that come from apps.odoo.com. It is not also possible to download the modules zip files with urllib2 when we tried to debug. it shows HTTP Error 404: NOT FOUND

**Comment by pedrobaeza** [comment] 2018-06-20 22:13
Duplicate of #24549

**Comment by mahmoudaljan** [comment] 2018-06-20 22:18
Come on ! it is absolutely not a duplicate of the issue. It has to do with the apps.odoo.com server not with odoo code per say. Please reconsider.

**Comment by pedrobaeza** [comment] 2018-06-20 22:19
You haven't read the other issue. It's due to a browser extension

**Comment by pedrobaeza** [comment] 2018-06-20 22:29
OK, reopening it, but can you point the code where the download is performed?

**Comment by mahmoudaljan** [comment] 2018-06-20 22:49
Thx for the help.
https://github.com/odoo/odoo/blob/8235f03f565ecbb097aca94638703f5dd6ca4eea/odoo/addons/base/module/module.py#L642

**Comment by pedrobaeza** [comment] 2018-06-20 22:54
I see that it's not the same code, but I suppose you get a similar problem. I let this in the hands of @KangOl, that I think it's the person for these things. Can you please check it, Christophe?

**Comment by mahmoudaljan** [comment] 2018-06-20 22:55
Indeed, not the same code but on line 672 the same logic was applied. I fired an ipython console to quickly reproduce the error.

**Comment by Yenthe666** [comment] 2018-06-27 13:12
CC @mart-e - I think you can have a look too?

**Comment by mart-e** [comment] 2018-06-27 13:15
Hello,

If you have an issue specific to the marketplace (and not the standard Odoo), please contact the responsible of the app platform.
See the last question of https://www.odoo.com/apps/faq

**Closed** 2018-06-27 14:23 UTC
