### ISSUE TITLE
[Stable Odoo 8.0 ] Bugs for name_get in form view.

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#7351] opened 2015-06-29 19:44 UTC
Hello,

I had apply address with name as name_get/name_search method in customer form.
then check to edit record.

Even I changes address and its data.

name_get  or name_search not change. Even I reload page.

Show same old values. Bugs here.

Thanks,

**Comment by Yenthe666** [comment] 2016-06-08 13:52
I have no way of reproducing this since your information is way too short. I do not know on which view you are, what you are doing, if this is custom development, ...
I'm closing this since this is probably fixed by now too. You're free to submit more information if you still face this issue and I'll be glad to look further look in to this.

**Closed by Yenthe666** 2016-06-08 13:52 UTC
