### ISSUE TITLE
odoo 15 fresh installation "NotImplementedError: Templates should use the ir.qweb compile method"

### ISSUE THREAD

**Issue by ark-sparkprompt** [odoo/odoo#82837] opened 2022-01-15 09:41 UTC
2022-01-15 09:39:47,748 35600 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 180, in _compile
    self._compile_node(element, _options, 1) +
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 346, in _compile_node
    return self._compile_static_node(el, options, indent)
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 689, in _compile_static_node
    body = self._compile_directive_content(el, options, indent)
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 943, in _compile_directive_content
    body.extend(self._compile_node(item, options, indent))
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 346, in _compile_node
    return self._compile_static_node(el, options, indent)
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 689, in _compile_static_node
    body = self._compile_directive_content(el, options, indent)
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 943, in _compile_directive_content
    body.extend(self._compile_node(item, options, indent))
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 346, in _compile_node
    return self._compile_static_node(el, options, indent)
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 689, in _compile_static_node
    body = self._compile_directive_content(el, options, indent)
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 943, in _compile_directive_content
    body.extend(self._compile_node(item, options, indent))
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 346, in _compile_node
    return self._compile_static_node(el, options, indent)
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 689, in _compile_static_node
    body = self._compile_directive_content(el, options, indent)
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 943, in _compile_directive_content
    body.extend(self._compile_node(item, options, indent))
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 346, in _compile_node
    return self._compile_static_node(el, options, indent)
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 689, in _compile_static_node
    body = self._compile_directive_content(el, options, indent)
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 943, in _compile_directive_content
    body.extend(self._compile_node(item, options, indent))
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 365, in _compile_node
    return body + self._compile_directives(el, options, indent)
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 383, in _compile_directives
    return self._compile_directive(el, options, directive, indent)
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 827, in _compile_directive
    return compile_handler(el, options, indent)
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 1008, in _compile_directive_if
    orelse = self._compile_node(next_el, dict(options, t_if=True), indent + 1) + self._flushText(options, indent + 1)
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 365, in _compile_node
    return body + self._compile_directives(el, options, indent)
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 383, in _compile_directives
    return self._compile_directive(el, options, directive, indent)
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 827, in _compile_directive
    return compile_handler(el, options, indent)
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 977, in _compile_directive_elif
    compiled = self._compile_directive_if(el, options, indent)
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 1010, in _compile_directive_if
    code.append(self._indent(f"if {self._compile_expr(expr)}:", indent))
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 578, in _compile_expr
    raise NotImplementedError("Templates should use the ir.qweb compile method")
NotImplementedError: Templates should use the ir.qweb compile method

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo15/odoo/odoo/http.py", line 1477, in _dispatch_nodb
    result = request.dispatch()
  File "/opt/odoo15/odoo/odoo/http.py", line 811, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo15/odoo/odoo/http.py", line 361, in _call_function
    return self.endpoint(*args, **kwargs)
  File "/opt/odoo15/odoo/odoo/http.py", line 917, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo15/odoo/odoo/http.py", line 536, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo15/odoo/addons/web/controllers/main.py", line 1079, in selector
    return self._render_template(manage=False)
  File "/opt/odoo15/odoo/addons/web/controllers/main.py", line 1074, in _render_template
    return QWeb()._render(html.document_fromstring(template), d, load=load)
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 132, in _render
    render_template = self._compile(template, options)
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 187, in _compile
    raise QWebException("Error when compiling xml template", self, options,
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo15/odoo-venv/lib/python3.8/site-packages/werkzeug/serving.py", line 306, in run_wsgi
    execute(self.server.app)
  File "/opt/odoo15/odoo-venv/lib/python3.8/site-packages/werkzeug/serving.py", line 294, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo15/odoo/odoo/service/server.py", line 476, in app
    return self.app(e, s)
  File "/opt/odoo15/odoo/odoo/service/wsgi_server.py", line 112, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo15/odoo/odoo/service/wsgi_server.py", line 87, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/opt/odoo15/odoo/odoo/http.py", line 1314, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo15/odoo/odoo/http.py", line 1280, in __call__
    return self.app(environ, start_wrapped)
  File "/opt/odoo15/odoo-venv/lib/python3.8/site-packages/werkzeug/middleware/shared_data.py", line 220, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo15/odoo/odoo/http.py", line 1510, in dispatch
    result = _dispatch_nodb()
  File "/opt/odoo15/odoo/odoo/http.py", line 1479, in _dispatch_nodb
    return request._handle_exception(e)
  File "/opt/odoo15/odoo/odoo/http.py", line 749, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo15/odoo/odoo/http.py", line 302, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.addons.base.models.qweb.QWebException: Templates should use the ir.qweb compile method
Traceback (most recent call last):
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 180, in _compile
    self._compile_node(element, _options, 1) +
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 346, in _compile_node
    return self._compile_static_node(el, options, indent)
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 689, in _compile_static_node
    body = self._compile_directive_content(el, options, indent)
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 943, in _compile_directive_content
    body.extend(self._compile_node(item, options, indent))
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 346, in _compile_node
    return self._compile_static_node(el, options, indent)
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 689, in _compile_static_node
    body = self._compile_directive_content(el, options, indent)
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 943, in _compile_directive_content
    body.extend(self._compile_node(item, options, indent))
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 346, in _compile_node
    return self._compile_static_node(el, options, indent)
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 689, in _compile_static_node
    body = self._compile_directive_content(el, options, indent)
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 943, in _compile_directive_content
    body.extend(self._compile_node(item, options, indent))
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 346, in _compile_node
    return self._compile_static_node(el, options, indent)
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 689, in _compile_static_node
    body = self._compile_directive_content(el, options, indent)
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 943, in _compile_directive_content
    body.extend(self._compile_node(item, options, indent))
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 346, in _compile_node
    return self._compile_static_node(el, options, indent)
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 689, in _compile_static_node
    body = self._compile_directive_content(el, options, indent)
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 943, in _compile_directive_content
    body.extend(self._compile_node(item, options, indent))
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 365, in _compile_node
    return body + self._compile_directives(el, options, indent)
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 383, in _compile_directives
    return self._compile_directive(el, options, directive, indent)
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 827, in _compile_directive
    return compile_handler(el, options, indent)
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 1008, in _compile_directive_if
    orelse = self._compile_node(next_el, dict(options, t_if=True), indent + 1) + self._flushText(options, indent + 1)
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 365, in _compile_node
    return body + self._compile_directives(el, options, indent)
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 383, in _compile_directives
    return self._compile_directive(el, options, directive, indent)
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 827, in _compile_directive
    return compile_handler(el, options, indent)
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 977, in _compile_directive_elif
    compiled = self._compile_directive_if(el, options, indent)
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 1010, in _compile_directive_if
    code.append(self._indent(f"if {self._compile_expr(expr)}:", indent))
  File "/opt/odoo15/odoo/odoo/addons/base/models/qweb.py", line 578, in _compile_expr
    raise NotImplementedError("Templates should use the ir.qweb compile method")
NotImplementedError: Templates should use the ir.qweb compile method

Error when compiling xml template
NotImplementedError: Templates should use the ir.qweb compile method
Template: <Element html at 0x7f1c89ebfdb0>
Path: /html/body/div/div[1]/div/t[1]
Node: <t t-content="True"/> - - -

**Comment by tate11** [comment] 2022-01-15 11:02
https://github.com/odoo/odoo/issues/82835

**Comment by mart-e** [comment] 2022-01-15 12:27
Duplicate of #82835

**Closed by mart-e** 2022-01-15 12:27 UTC
