### ISSUE TITLE
SyntaxError: invalid syntax under /odoo/tools/config.py", line 571

### ISSUE THREAD

**Issue by shazzwazz20** [odoo/odoo#44111] opened 2020-01-28 13:46 UTC
Impacted versions: 13.0

Steps to reproduce: run odoo service

Current behavior:
    glob.glob(os.path.join(res, f"*/*/{prefix}-*.py"))
                                                   ^
SyntaxError: invalid syntax

Expected behavior:
service should run properly
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment] 2020-01-28 14:12
Hi,

Can you add more steps on how to reproduce this? All runbot instances build fine and I've got multiple V13's running  just fine too.

Regards,
Yenthe

**Comment by mra-odoo** [comment] 2020-01-29 13:52
We have faced same issue as well in our local system.

glob.glob(os.path.join(res, f"//{prefix}-*.py"))
^
SyntaxError: invalid syntax

Thank you,
Mustufa Rangwala

**Comment by rccardero** [comment] 2020-01-29 20:07
Regards,
we are having the same error installing odoo_13.0+e.latest_all.deb on Debian Stretch.

**Comment by Yenthe666** [comment] 2020-01-29 21:23
@d-fence maybe for you to check

**Comment by rccardero** [comment] 2020-01-29 21:46
The line(571) that fails was added to the commit:
https://github.com/odoo/odoo/commit/90ced8024a53c4662b198dcbd841ffce824a75ab

**Comment by Yenthe666** [comment] 2020-01-30 08:04
@Julien00859 and @KangOl it looks like you guys might have introduced this actually ;-)

**Comment by Julien00859** [comment] 2020-01-30 08:14
Hello, can you all give the python version you are using ? We are trying to reproduce the problem in-house.

**Comment by Julien00859** [comment] 2020-01-30 08:44
We are about sure you are using an outdated python version, the minimal python version supported for Odoo v13 is python3.6. Debian stretch comes with Python3.5, please upgrade to Debian buster.

**Comment by d-fence** [comment] 2020-01-30 08:47
I confirm that the Odoo Debian package 13.0 is built against Buster (https://github.com/odoo/odoo/blob/f66042c96795701c1a313f40fdd320d28e9803ee/setup/package.dfdebian#L3)

**Comment by shazzwazz20** [comment] 2020-01-30 10:26
Hi, Yes this version issue.
It works fine if python version is 3.6 or >.

To avoid this issue run odoo 13 on python version is 3.6 or >.


Best way is to create virtual enviornement on ubuntu bcoz of multile python verskion in use.
make sure to use pip3.6 for installing packages otherwise your package would installed in 3.5 of pip.

**Comment by pedrobaeza** [comment] 2020-01-30 14:08
Then the problem is clear. @shazzwazz20 please check next time minimum requirements before raising anything, and give thanks that 2 Odoo employees have kindly attended you.

Closing this.

**Closed by pedrobaeza** 2020-01-30 14:08 UTC
Labels: 13.0, Need information

**Comment by shazzwazz20** [comment] 2020-01-30 14:15
thanks all
