### ISSUE TITLE
[10.0] reply_to field in mail.template is not used when sending email

### ISSUE THREAD

**Issue by Auneor** [odoo/odoo#18098] opened 2017-07-07 09:08 UTC
Impacted versions:
10.0 community at least

Steps to reproduce:
Go to edit a mail.template in the technical configuration menu, for exemple the "invoice - send by Email" template
Set a reply_to email address, for example reply@example.org
Send an email from an invoice, with this template

Current behavior:
The reply_to in the outgoing email is set mail.catchall.alias is this config is set, otherwise it's set to the from address

Expected behavior:
the reply_to in the outgoing email should be reply@example.org

**Comment by taifu** [comment] 2018-04-06 08:14
See https://github.com/odoo/odoo/issues/16635#issuecomment-379181538 for a solution

**Comment by pedrobaeza** [comment] 2018-06-02 14:19
Duplicate of #16635

**Closed by pedrobaeza** 2018-06-02 14:19 UTC
Labels: 10.0, Services
