### ISSUE TITLE
[11.0] Bank staments lines- Can not add more lines after 40 items- list widget

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#22856] opened 2018-02-06 16:49 UTC
Impacted versions:
11.0

Steps to reproduce:
1.- Create a bank stament
2.- Add payments until 40 itemes
3- Try to add more items

Current behavior:
After 40 items in the list, next items are not added to the list
Expected behavior:
Improve the usability by allowing add and edit new lines after list view items limit be exceeded

Video/Screenshot link (optional):

https://youtu.be/wapcjojlMfc

**Comment by sswapnesh** [comment] 2018-02-06 18:54
Hello @hugho-ad 
Next Items are added to the Second page.
By default, it will show 40 line in a page.

![](https://image.prntscr.com/image/ZnrnfO3CRSOd1gOJ5sW7ag.png)

Cc: @Yenthe666

**Comment by hugho-ad** [comment] 2018-02-06 19:19
Hi @Yenthe666 
Sure, but that is an usability issue, since user has to increment the items number in the list each time that it is added new row in order to edit the row

https://youtu.be/5lzBYmaYDKE

**Comment by alan196** [comment] 2018-02-06 22:11
I have this same issue in purchase orders.

**Comment by Yenthe666** [comment] 2018-02-07 06:36
Hi @hugho-ad,

Thanks for the report.
@ged-odoo could you have a look? I believe this is made by design and not something that is easy to change or that Odoo wants to change it.
@sswapnesh indeed, considering the default behaviour it works fine.

**Comment by ged-odoo** [comment] 2018-02-07 13:13
this is indeed kind of stupid. I suppose we should have a look

**Comment by JulioSerna** [comment] 2018-03-05 16:50
any news about this issue?

**Comment by ged-odoo** [comment] 2018-03-07 13:32
@JulioSerna working on it right now. but looking at this, I found many small other related bugs with the interactions between onchanges/required fields and x2many fields.  This is not as simple as I hoped :/

**Comment by ged-odoo** [comment] 2018-03-12 12:55
fix just landed in v11.0: https://github.com/odoo/odoo/commit/e7fab234201e357da52c3576ad2e8fc9ceee9359

**Closed by ged-odoo** 2018-03-12 12:55 UTC
Labels: 11.0, Framework, Functional review
