### ISSUE TITLE
Getting error after specifying tax in invoice line v9.

### ISSUE THREAD

**Issue by omalbastin** [odoo/odoo#10069] opened 2015-12-14 21:15 UTC
Create a new invoice with invoice line having a tax. Saving the record will show error.

  File "/home/omalbastin/WORK/odoo/openerp/http.py", line 605, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/omalbastin/WORK/odoo/openerp/http.py", line 642, in dispatch
    result = self._call_function(**self.params)
  File "/home/omalbastin/WORK/odoo/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/omalbastin/WORK/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/omalbastin/WORK/odoo/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/omalbastin/WORK/odoo/openerp/http.py", line 893, in __call__
    return self.method(*args, **kw)
  File "/home/omalbastin/WORK/odoo/openerp/http.py", line 471, in response_wrap
    response = f(*args, **kw)
  File "/home/omalbastin/WORK/odoo/addons/web/controllers/main.py", line 892, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/omalbastin/WORK/odoo/addons/web/controllers/main.py", line 884, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/omalbastin/WORK/odoo/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/omalbastin/WORK/odoo/openerp/api.py", line 369, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/omalbastin/WORK/odoo/openerp/models.py", line 5987, in onchange
    record = self.new(values)
  File "/home/omalbastin/WORK/odoo/openerp/api.py", line 236, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/omalbastin/WORK/odoo/openerp/models.py", line 5557, in new
    record._cache.update(record._convert_to_cache(values, update=True))
  File "/home/omalbastin/WORK/odoo/openerp/models.py", line 5452, in _convert_to_cache
    for name, value in values.iteritems()
  File "/home/omalbastin/WORK/odoo/openerp/models.py", line 5453, in <dictcomp>
    if name in fields
  File "/home/omalbastin/WORK/odoo/openerp/fields.py", line 1744, in convert_to_cache
    ids = OrderedSet(command[2])
  File "/home/omalbastin/WORK/odoo/openerp/tools/misc.py", line 1106, in __init__
    super(OrderedSet, self).__init__([(x, None) for x in seq])
  File "/usr/lib/python2.7/collections.py", line 57, in __init__
    self.__update(*args, **kwds)
  File "/usr/lib/python2.7/_abcoll.py", line 569, in update
    self[key] = value
  File "/usr/lib/python2.7/collections.py", line 63, in __setitem__
    if key not in self:
TypeError: unhashable type: 'list'

**Comment by odony** [comment] 2015-12-15 16:37
Hi, I suggest we close this issue as a duplicate of #10055, which contains more information, and confirm the latter, if you don't mind.

**Closed by odony** 2015-12-15 16:37 UTC
