### ISSUE TITLE
Cannot access any to the interface after login

### ISSUE THREAD

**Issue by m3asmi** [odoo/odoo#27090] opened 2018-09-19 10:37 UTC
Impacted versions: 
**10 enterprise edition**

Current behaviour:
**cannot access any to the interface after login**
 
interface Error:

`TypeError: this.view_order[0] is undefined`

```

http://localhost:8069/web/static/src/js/view_manager.js:163
Retraçage :
get_default_view@http://localhost:8069/web/static/src/js/view_manager.js:163:9
get_default_view@http://localhost:8069/web_enterprise/static/src/js/view_manager.js:14:32
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8069/web/static/src/js/framework/class.js:122:35
init@http://localhost:8069/web/static/src/js/view_manager.js:82:29
OdooClass.extend/</prototype[name]</<@http://localhost:8069/web/static/src/js/framework/class.js:89:35
Class@http://localhost:8069/web/static/src/js/framework/class.js:106:23
widget@http://localhost:8069/web/static/src/js/action_manager.js:779:24
ir_actions_common/<@http://localhost:8069/web/static/src/js/action_manager.js:756:37
then/</</<@http://localhost:8069/web/static/lib/jquery/jquery.js:3276:86
fire@http://localhost:8069/web/static/lib/jquery/jquery.js:3119:38
add@http://localhost:8069/web/static/lib/jquery/jquery.js:3165:49
then/</<@http://localhost:8069/web/static/lib/jquery/jquery.js:3275:57
each@http://localhost:8069/web/static/lib/jquery/jquery.js:383:49
then/<@http://localhost:8069/web/static/lib/jquery/jquery.js:3272:49
Deferred@http://localhost:8069/web/static/lib/jquery/jquery.js:3332:25
then@http://localhost:8069/web/static/lib/jquery/jquery.js:3271:48
ir_actions_common@http://localhost:8069/web/static/src/js/action_manager.js:754:16
ir_actions_act_window@http://localhost:8069/web/static/src/js/action_manager.js:777:16
do_action@http://localhost:8069/web/static/src/js/action_manager.js:672:23
do_action@http://localhost:8069/web/static/src/js/abstract_web_client.js:196:16
do_action@http://localhost:8069/web_enterprise/static/src/js/web_client.js:160:16
OdooClass.extend/</prototype[name]</<@http://localhost:8069/web/static/src/js/framework/class.js:89:35
do_action@http://localhost:8069/web_studio/static/src/js/web_client.js:203:16
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8069/web/static/src/js/framework/class.js:122:35
on_menu_clicked/</<@http://localhost:8069/web_enterprise/static/src/js/web_client.js:255:28
Mutex.prototype.exec/<@http://localhost:8069/web/static/src/js/framework/utils.js:205:23
then/</</<@http://localhost:8069/web/static/lib/jquery/jquery.js:3276:86
fire@http://localhost:8069/web/static/lib/jquery/jquery.js:3119:38
add@http://localhost:8069/web/static/lib/jquery/jquery.js:3165:49
then/</<@http://localhost:8069/web/static/lib/jquery/jquery.js:3275:57
each@http://localhost:8069/web/static/lib/jquery/jquery.js:383:49
then/<@http://localhost:8069/web/static/lib/jquery/jquery.js:3272:49
Deferred@http://localhost:8069/web/static/lib/jquery/jquery.js:3332:25
then@http://localhost:8069/web/static/lib/jquery/jquery.js:3271:48
Mutex.prototype.exec@http://localhost:8069/web/static/src/js/framework/utils.js:204:12
on_menu_clicked/<@http://localhost:8069/web_enterprise/static/src/js/web_client.js:253:24
then/</</<@http://localhost:8069/web/static/lib/jquery/jquery.js:3276:86
fire@http://localhost:8069/web/static/lib/jquery/jquery.js:3119:38
fireWith@http://localhost:8069/web/static/lib/jquery/jquery.js:3231:49
Deferred/</deferred[tuple[0]]@http://localhost:8069/web/static/lib/jquery/jquery.js:3321:33
add/<@http://localhost:8069/web/static/src/js/framework/utils.js:416:17
fire@http://localhost:8069/web/static/lib/jquery/jquery.js:3119:38
fireWith@http://localhost:8069/web/static/lib/jquery/jquery.js:3231:49
then/</</<@http://localhost:8069/web/static/lib/jquery/jquery.js:3283:73
fire@http://localhost:8069/web/static/lib/jquery/jquery.js:3119:38
fireWith@http://localhost:8069/web/static/lib/jquery/jquery.js:3231:49
then/</</<@http://localhost:8069/web/static/lib/jquery/jquery.js:3283:73
fire@http://localhost:8069/web/static/lib/jquery/jquery.js:3119:38
fireWith@http://localhost:8069/web/static/lib/jquery/jquery.js:3231:49
Deferred/</deferred[tuple[0]]@http://localhost:8069/web/static/lib/jquery/jquery.js:3321:33
fire@http://localhost:8069/web/static/lib/jquery/jquery.js:3119:38
fireWith@http://localhost:8069/web/static/lib/jquery/jquery.js:3231:49
then/</</<@http://localhost:8069/web/static/lib/jquery/jquery.js:3283:73
fire@http://localhost:8069/web/static/lib/jquery/jquery.js:3119:38
fireWith@http://localhost:8069/web/static/lib/jquery/jquery.js:3231:49
then/</</<@http://localhost:8069/web/static/lib/jquery/jquery.js:3283:73
fire@http://localhost:8069/web/static/lib/jquery/jquery.js:3119:38
fireWith@http://localhost:8069/web/static/lib/jquery/jquery.js:3231:49
done@http://localhost:8069/web/static/lib/jquery/jquery.js:9275:33
callback@http://localhost:8069/web/static/lib/jquery/jquery.js:9685:57



```

**Comment by pedrobaeza** [comment] 2018-09-19 10:40
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-09-19 10:40 UTC
