### ISSUE TITLE
[15.0] Install fails on Ubuntu 20.04 LTS, Python 3.8

### ISSUE THREAD

**Issue by bosskopp** [odoo/odoo#82842] opened 2022-01-15 15:36 UTC
**Impacted versions:**

15.0 - commit 3014e922b48696fb9aba4b477ebe1878dd01bb69
using Python 3.8.10 (venv) on Ubuntu 20.04.3 LTS

**Steps to reproduce:**

1. clone repo
2. create and activate venv, pip install Odoo's requirements.txt
3. odoo-bin -c odoo.conf (db user therein exists and has create database rights)
4. call in browser: <hostname>/web/database/manager - shows form to create new Odoo environment
5. insert required fields
6. submit form

**Current behavior:**

Database manager GUI shows message:

> Database creation error: relation "ir_model" does not exist LINE 1: SELECT * FROM ir_model WHERE state='manual' ^

![o15c-err](https://user-images.githubusercontent.com/1733427/149627460-b39f87f1-ce11-448b-b89b-a530f1593ff8.png)

**Expected behavior:**

Should run trough without issues.

Checked e.g. commit ad434b00163a4c033c2df403adb5f119ada347cb - there it works after installing requirements.txt from that version (html2text was [removed later on](https://github.com/odoo/odoo/commit/b3b9627b655cd7cb928925affed6cc8d92661e8d)).

**Comment by odony** [comment] 2022-01-16 22:40
Hi, thanks for reporting. This is a duplicate of issue #82843, and it's fixed by #82844, you can just update to the latest revision :)

**Closed by odony** 2022-01-16 22:40 UTC
