### ISSUE TITLE
Product BOM type KIT not allow to confirm sale order, wrong rule for components routes. 

### ISSUE THREAD

**Issue by tanceee** [odoo/odoo#65311] opened 2021-01-31 20:33 UTC
Impacted versions:12

Steps to reproduce: 
1. Create a product with bom type = kit with 1 or more components,
2. Set routes to this Kit product as **MTO** and **Manufacturing**
3. Set routes to component products to **buy** and update stock availability by updating the qty on hand.
4. Make a Sale Order with Kit prorduct created on step 1 and CONFIRM. 
5. Odoo gives error There is no vendor associated to the product *Component product(product name)*. Please define a vendor for this product. 

Current behavior: Odoo forward MTO rule to **components** of the Kit product, but the components have rule as **Buy** but odoo tries to create a purchase order instead of getting from stock.

https://user-images.githubusercontent.com/29401455/106397026-b50edc80-640b-11eb-9d8f-a443be68d1e6.mp4

Expected behavior: Odoo should confirm the order and reserve the components from stock as the stock qty is available

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment] 2021-01-31 21:09
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by tanceee** [comment] 2021-01-31 21:52
Steps to reproduce 
1 Create a product **Product KIT**
* Product type = stockable 
* Routes = manufacture + make to order
![image](https://user-images.githubusercontent.com/29401455/106398546-aaf0dc00-6413-11eb-94df-e498c3cbdb28.png)

2. Create a **purchased product** 
* Product type = stockable 
* Routes = Buy
* update qty on hand 
![image](https://user-images.githubusercontent.com/29401455/106398764-0ff90180-6415-11eb-8e5a-5cdc434f0dec.png)
3. Set a BOM for **product KIT** 
* BOM type = kit
* component =  **purchased product** 
![image](https://user-images.githubusercontent.com/29401455/106398847-7da52d80-6415-11eb-9c5c-fe4aeb4a75ad.png)

4. Create a sale order for **Product KIT** and try to confirm
![image](https://user-images.githubusercontent.com/29401455/106398907-dbd21080-6415-11eb-99cf-c4f2bf6cb25f.png)

5. odoo error for purchased product **here is no vendor associated to the product Product purchased. Please define a vendor for this product.**
![image](https://user-images.githubusercontent.com/29401455/106398927-0d4adc00-6416-11eb-833b-b10a482e23d1.png)
odoo tries to create a puchase order for **purchased product** this is not a normal behaviour because the component has stock available ose has set routes to **buy** instead odoo tries to apply product kit routes rule (make to order). 
I hope everything is clear.

**Comment by pedrobaeza** [comment] 2021-01-31 22:43
Ok, got it, but that's the expected behavior, as marking MTO always procures more stock, no matter if you have in stock already. On later versions, there's a MTS+MTO route for such approach (but only having whole quantity).

Closing thus.

**Closed by pedrobaeza** 2021-01-31 22:43 UTC

**Comment by tanceee** [comment] 2021-01-31 23:09
This is not a normal behavior I am making MTO the **product KIT** not the component, the component has **Buy** rule, this bug is not i odoo version 10 and version 13(tested).  
Normal behavior is that when I create a KIT product and my customer is ordering to the system will generate stock moves routes depending product component Routes Rule, not KIT product rule. 
As you can see in videos and screenshot my product has routes as **Buy** but odoo trying to generate(MTO) purchase order for that component. 
I have test this behavior on odoo 10 and 13 and odoo is not giving this error but depending on rule of components odoo takes from stock or create MTO as set in product template.
I think you are wrong. i can send video on odoo 10 version as i tested.
