### ISSUE TITLE
[10] Amount Due does not print on invoice with overpaid invoice

### ISSUE THREAD

**Issue by clxadmin** [odoo/odoo#26291] opened 2018-08-09 15:10 UTC
Impacted versions: 
10 CE

Steps to reproduce:
create invoice for 10 bugs, create payment with overpay total 15 bugs
mark overpayment as invoice fully done
create new invoice for same partner with example 20 bugs
confirm invoice -- youll notics payment from last invoice 5 bugs, confirm this 5 bugs used for this invoice
you see Amount Due line 15 bugs
print invoice
missing line Amound Due on invoice print

Current behavior:

Expected behavior:
show Amount Due line like in version [11]

Video/Screenshot link (optional):
https://drive.google.com/file/d/1mvBZNAAPMUCVd-KwDdk7-ST83u91o6ND/view?usp=sharing

**Comment by clxadmin** [comment] 2018-08-10 07:46
The video is the example how it works on odoo 11 -- in odoo 10 the line 'Amount Due' is missing on invoice printout

**Comment by pedrobaeza** [comment] 2018-08-10 07:51
OK, got it, but that's not a bug. It's simply that the amount due display in the invoice report is a new feature in v11.

Then you have to upgrade your DB to v11 for enjoying that feature, or customize your v10 invoice report for including that information.

Closing by the reasons above.

**Closed by pedrobaeza** 2018-08-10 07:51 UTC
Labels: 10.0, Accounting, Need information
