### ISSUE TITLE
Not possible to write a message in a task from the portal

### ISSUE THREAD

**Issue by falmagnef** [odoo/odoo#36674] opened 2019-09-11 09:23 UTC
Impacted versions: 
-12.0

Steps to reproduce: 
-Log into a portal account (I used the account portal from runbot, joel willis)
-Go to a task where u're follower (I picked this one : SERV_89665] Junior Architect (Invoice on Timesheets) (#125))

-Tape a message in the discussion and send it
![image](https://user-images.githubusercontent.com/55185319/64684611-b857a000-d485-11e9-9892-8d7b4ddbca7f.png)

Current behavior:
-Return Error 403

![image](https://user-images.githubusercontent.com/55185319/64684641-c73e5280-d485-11e9-866e-710632dffc02.png)

Expected behavior:
-The message is send

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2019-09-11 09:38
I have been able to do it in runbot:

![Peek 11-09-2019 11-37](https://user-images.githubusercontent.com/7165771/64686235-a1667d00-d488-11e9-9648-14db66b6df2b.gif)

so it should be something in your end, or something misconfigured in that specific instance.

I close this meanwhile you don't give more possible steps to reproduce the problem.

**Comment by falmagnef** [comment] 2019-09-11 09:44
Hi @pedrobaeza,

You have to pick the same task than my example :) 
If I remember, joel willis isn't in the task "SERV_89665] Junior Architect (Invoice on Timesheets)" as follower by default

Regards,

**Comment by pedrobaeza** [comment] 2019-09-11 09:46
What that task has different from the showed one?

**Comment by falmagnef** [comment] 2019-09-11 13:08
I don't know, I changed nothing

I have the problem right now here: http://615493-12-0-77e836.runbot23.odoo.com/my/task/125
(logged as the user portal)


Sometimes I have the problem, and sometimes not

**Comment by pedrobaeza** [comment] 2019-09-11 15:05
Well, I'm afraid that if you don't have clear steps to reproduce the problem, there's nothing Odoo can do.

**Comment by falmagnef** [comment] 2019-09-12 06:36
https://youtu.be/GvAJ_txg0wE

**Comment by pedrobaeza** [comment] 2019-09-12 07:22
The problem is that the project "DPC - SO065" has as "Privacy" = "Visible by following customers", but Joel Willis is not a follower of the project, and thus, the error. Please add it as well to the project.

**Comment by falmagnef** [comment] 2019-09-12 07:32
I did it

![image](https://user-images.githubusercontent.com/55185319/64763314-05984800-d540-11e9-8304-e4c97c5cbeb2.png)

![image](https://user-images.githubusercontent.com/55185319/64763346-15b02780-d540-11e9-9c11-66005ab86a46.png)

Still not working


![image](https://user-images.githubusercontent.com/55185319/64763387-2d87ab80-d540-11e9-8ac9-b47d14eb5471.png)

![image](https://user-images.githubusercontent.com/55185319/64763403-34aeb980-d540-11e9-86ca-832cde1d0346.png)

**Comment by pedrobaeza** [comment] 2019-09-12 07:41
OK, reproduced now, so we finally got the steps. Reopening.

@jem-odoo not sure if this falls in your part, as one suspicion I have is that it's due to the timesheets linked to the task.

**Closed** 2019-09-18 15:26 UTC
Labels: 12.0, Services
