### ISSUE TITLE
Unable to change font or color of the theme on the website!

### ISSUE THREAD

**Issue by Ahmedposhi** [odoo/odoo#44240] opened 2020-01-30 02:55 UTC
Impacted versions: odoo 13 

Steps to reproduce: 
1- installed website
2-installed Website Theme Install 
3- open the website app 
4- select theme 
5- clicked customize theme
6- tried to change color, font size or type.  

Current behavior: when i trying to customize the theme i selected it nothing is happened. 

Expected behavior: when i click on the customize theme and going to select or edit any thing like navabar for example and change the size of the font it should be changing.

Video/Screenshot link (optional): https://www.screencast.com/t/v3nfteGo6H

I trust you can help me this time. 

Thanks.

**Comment by pedrobaeza** [comment] 2020-01-30 07:18
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by bahram-css** [comment] 2020-01-30 10:10
Did you uninstall website module and install it again?
If you do that this problem apears beacause of duplication in file address at database.

**Comment by Ahmedposhi** [comment] 2020-01-30 10:36
Yes, it appears after that. How could i solve this?

**Comment by Ahmedposhi** [comment] 2020-01-30 10:36
How can i report it on the runboot.

**Comment by Ahmedposhi** [comment] 2020-01-30 12:17
> 
> 
> Did you uninstall website module and install it again?
> If you do that this problem apears beacause of duplication in file address at database.

Yes, it appears after that. How could i solve this?

**Comment by Ahmedposhi** [comment] 2020-01-30 12:19
> 
> 
> Did you uninstall website module and install it again?
> If you do that this problem apears beacause of duplication in file address at database.



> 
> 
> Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?
> 
> If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.
> 
> If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.
> 
> For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

How can i report it on the runboot.

**Comment by bahram-css** [comment] 2020-01-30 17:37
You must remove that duplicated record from ir_attachment table in database if you can.
I'm sorry, I don't remember what the record id was but you can search all that table for "asset" or "css" or something like these.

**Comment by Ahmedposhi** [comment] 2020-01-30 17:53
>  ir_attachment

you mean from the view or what?

**Comment by bahram-css** [comment] 2020-01-30 18:09
Do you have access to database?
ir_attachment is a table (a model).

**Comment by Ahmedposhi** [comment] 2020-01-30 18:21
> 
> 
> Do you have access to database?
> ir_attachment is a table (a model).

My odoo version is Enterprise SaaS.

**Comment by bahram-css** [comment] 2020-01-30 18:51
So I'm sorry. But keep in mind that this is due to the uninstall and installation of the website module, and you can do it in the runbot and complete the report.

**Comment by Ahmedposhi** [comment] 2020-01-30 18:54
> 
> 
> So I'm sorry. But keep in mind that this is due to the uninstall and installation of the website module, and you can do it in the runbot and complete the report.

i'm so sorry for that, but how can i do it in the run boot to make report.

**Comment by bahram-css** [comment] 2020-01-30 19:06
Choose your version from list. These are for test.
http://runbot.odoo.com/runbot

**Comment by Ahmedposhi** [comment] 2020-01-30 19:11
After i connect the version, what is the steps to make test to report my
issue.

I'm sorry for disturbing you.

**Comment by bahram-css** [comment] 2020-01-30 19:27
@pedrobaeza

**Comment by bahram-css** [comment] 2020-01-30 19:52
https://youtu.be/0hc7rDrEtCk

**Comment by Ahmedposhi** [comment] 2020-01-30 20:01
Thank you so much for your support and help.

I saw your tutorial and i did what you suggested.
So after that what i suppose to do.

**Comment by Ahmedposhi** [comment] 2020-01-31 03:24
> 
> 
> https://youtu.be/0hc7rDrEtCk

Thank you so much for your support and help.
I saw your tutorial and i did what you suggested.
So after that what i suppose to do.

**Comment by Yenthe666** [comment] 2020-01-31 07:27
@Ahmedposhi I'd really suggest you to start reading guides and docs about Odoo before continuing honestly. Since you're on the SaaS you also have an enterprise license, which means you can report problems through odoo.com/help. This channel is made for enterprise users and gets higher priority in help.

**Closed by Yenthe666** 2020-01-31 07:27 UTC
Labels: Need information

**Comment by CarlosRG-PC** [comment] 2022-04-20 17:46
I would like to re-open this issue. Still happening in v14 I reproduce it on runbot: https://14686465-14-0-all.runbot61.odoo.com/contactus#scrollTop=0
Basicly if you remove the website app, when you re-install it is impossible to modify some of the options on the website editor.
Steps:
1- you website is working correctly - open website and edit.
2- modify page layout to boxed and full, modify size of logo to 80
3-unistall the website app
4-reinstall website app
5-try to repeat step 2
https://www.youtube.com/watch?v=6cfVIWoMvc8
let me know if I need to open a new issue for this.

**Comment by qsm-odoo** [comment] 2022-08-10 13:37
Hello,

This problem of re-installation of the website app has now been re-solved (it was actually already solved before but broken again later) at https://github.com/odoo/odoo/commit/4658afd9a290e2e4a43a2e3c2808c62475518e0f, it will take some time to reach the 15.0 version and be available for databases (normally by the end of next week maximum, it should be OK).

However, the solution we found will just prevent the problem to reappear but it will not solve the problem in databases where the bug already occurred. You would need to delete the problematic attachments that were not removed during the uninstallation. They are named user_XXX.scss (you should delete those which are without a set website):
![image](https://user-images.githubusercontent.com/10338094/183914911-0af04147-785b-42de-bcf7-3669d0020c26.png)
