### ISSUE TITLE
Logical relation between fields of product.product vs. product.product.template

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#1198] opened 2014-07-15 22:37 UTC
The fields which are steered by the template on variants is not as expected for various fields. 

**Version:**
V8alpha - SaaS Offer (15.07.2014)

**Reproduce:**
 Activate Product Variants

**Observed Behaviour:**
- Some Fields cannot be individualized (only examples):
  - Costing Method
  - Cost
- Some fields have strange display behaviour:
  - Costing Method / Standard Price on Product Variant View
  - Iventory Valuation (only visible on product variant) - it seems there is alternating default on how to display template/variant fields..

**Expected behaviour:**
- A sensible set of fields can be individualized per variant. (Costing method/standard-price for example is important to reproduce the 16GB 32GB example of many product showcases)
- A consistent display method is chosen for fields steered by template vs fields steeed by variant.

**Comment by erwin-bas-solutions** [comment] 2015-01-04 08:30
Did someone Make a PR or module to make a cost price per variant?

**Comment by jeremyirawan** [comment] 2015-01-06 14:23
I am trying to follow ana's solution which are the following:

I proposed this solution in #3985:
Our patch design would be something like this (needs more detailed focus):
1. To create a new field product_cost on product.product
2. To include product_id relation on cost history table
3. To update this field same way is made now to update standard_price on product.template but updating product_cost on product.product.

I know how to do step 1, but not sure where should i apply number 2 & 3. Which model should i use?
is it product.template or product.price.history?

Can anyone or perhaps @anajuaristi can help me further ? I am trying to apply this temporary solution. Thx.

**Comment by anajuaristi** [comment] 2015-01-06 16:08
Hi Ramadhi

Modules with the proposed patch is now landing on odoomrp project
New module name would be purchase_product_price_history, expected to be
merged during this or next week.
You can take a look here. We are still testing and reviewing
https://github.com/odoomrp/odoomrp-wip/pull/331



2015-01-06 15:23 GMT+01:00 Ramadhi Irawan <notifications@github.com>:

> I am trying to follow ana's solution which are the following:
>
> I proposed this solution in #3985
> <https://github.com/odoo/odoo/issues/3985>:
> Our patch design would be something like this (needs more detailed focus):
> 1. To create a new field product_cost on product.product
> 2. To include product_id relation on cost history table
> 3. To update this field same way is made now to update standard_price on
> product.template but updating product_cost on product.product.
>
> I know how to do step 1, but not sure where should i apply number 2 & 3.
> Which model should i use?
> is it product.template or product.price.history?
>
> Can anyone or perhaps @anajuaristi <https://github.com/anajuaristi> can
> help me further ? I am trying to apply this temporary solution. Thx.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/odoo/odoo/issues/1198#issuecomment-68870671>.
>



-- 
CEO Avanzosc, S.L <http://www.avanzosc.es> : Office phone / Tfono oficina:
(+34) 943 02 69 02
Ana Juaristi Olalde <http://www.anajuaristi.com/>: Personal phone: 677 93
42 59. User/usuario skype: Avanzosc
www.openerpsite.com


*El contenido de esta comunicación y de toda su documentación anexa es
confidencial y se dirige exclusivamente a su destinatario. El uso no
autorizado de esta información está prohibido por la legislación vigente.
Si usted no es el destinatario le rogamos nos lo indique, no comunique su
contenido a terceros y proceda a su destrucción. Disculpe las molestias que
le haya ocasionado la recepción indebida de este e-mail. Sus datos figuran
en un fichero cuyo titular es Avanzosc, S.L., a quien usted puede dirigirse
para ejercer sus derechos de acceso, rectificación, cancelación y oposición
en Julio Urkijo, 32, 20720, Azkoitia (Gipuzkoa), Tef. 943 02 69 02 -
administracion@avanzosc.com <soporte@avanzosc.com> *

*Komunikazio honen edukia eta dokumentazio erantsia konfidentziala da eta
hartzaileak bakarrik jaso beharko luke. Indarrean dagoen legeriak debekatu
egiten du bertan eskainitako informazioa baimenik gabe erabiltzea.
Komunikazioa zuri iritsi bazaizu, baina zu ez bazara hartzailea, mesedez,
guri jakinarazi, eta jasotako informazioa ez inori jakinarazi eta suntsitu.
Barkatu okerreko email hau jasotzeak eragindako eragozpenak. Zure datuak
Avanzosc, S.L. enpresaren fitxategietan sartuta daude. Zure datuak atzitzea
eska dezakezu, bai eta, datuak zuzentzea, ezereztea eta tratamenduari aurka
egitea ere. Horretarako, enpresara jo dezakezu, helbide honetan: Julio
Urkijo, 32, 20720, Azkoitia (Gipuzkoa), telefonoa: 943 02 69 02 -
**administracion@avanzosc.com
<soporte@avanzosc.com> *
*This message and all documents attached to it are confidential and
intended only for the person or entity to which it is addressed. Any use of
this information by unauthorised persons is prohibited under current
legislation. If you received this message by error, please advise us,
destroy it and refrain from communicating its contents to third parties. We
apologise for any inconvenience receiving this email improperly may cause
to you. Your personal data are included in a file owned by Avanzosc, S.L.
If you want to exercise your rights of access, correction, erasure and
objection you can contact the Controller at Julio Urkijo, 32, 20720,
Azkoitia (Gipuzkoa), T: 943 02 69 02 – administracion@avanzosc.com
<soporte@avanzosc.com>*

**Comment by jeremyirawan** [comment] 2015-01-06 16:28
Hi @anajuaristi 

Thanks for the reply. Unfortunately most of the conversation is in spanish (is it?). But, anyway i think i can wait until the next update is here.

Btw, will it be possible to apply the update from the Odoo directly ?

**Comment by anajuaristi** [comment] 2015-01-06 16:39
I don't think so the update will be merged in Odoo V8 directly, since this
is an enhancement and merging it would break the stable policy.

Maybe they would consider to include it on core next Odoo V9.0, but this is
up to Odoo, S.A itself. We only can help building community modules to try
to cover this kind of things but decisions about roadmap for new versions,
of course, is defined by them.

2015-01-06 17:28 GMT+01:00 Ramadhi Irawan <notifications@github.com>:

> Hi @anajuaristi <https://github.com/anajuaristi>
>
> Thanks for the reply. Unfortunately most of the conversation is in spanish
> (is it?). But, anyway i think i can wait until the next update is here.
>
> Btw, will it be possible to apply the update from the Odoo directly ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/odoo/odoo/issues/1198#issuecomment-68889041>.
>



-- 
CEO Avanzosc, S.L <http://www.avanzosc.es> : Office phone / Tfono oficina:
(+34) 943 02 69 02
Ana Juaristi Olalde <http://www.anajuaristi.com/>: Personal phone: 677 93
42 59. User/usuario skype: Avanzosc
www.openerpsite.com


*El contenido de esta comunicación y de toda su documentación anexa es
confidencial y se dirige exclusivamente a su destinatario. El uso no
autorizado de esta información está prohibido por la legislación vigente.
Si usted no es el destinatario le rogamos nos lo indique, no comunique su
contenido a terceros y proceda a su destrucción. Disculpe las molestias que
le haya ocasionado la recepción indebida de este e-mail. Sus datos figuran
en un fichero cuyo titular es Avanzosc, S.L., a quien usted puede dirigirse
para ejercer sus derechos de acceso, rectificación, cancelación y oposición
en Julio Urkijo, 32, 20720, Azkoitia (Gipuzkoa), Tef. 943 02 69 02 -
administracion@avanzosc.com <soporte@avanzosc.com> *

*Komunikazio honen edukia eta dokumentazio erantsia konfidentziala da eta
hartzaileak bakarrik jaso beharko luke. Indarrean dagoen legeriak debekatu
egiten du bertan eskainitako informazioa baimenik gabe erabiltzea.
Komunikazioa zuri iritsi bazaizu, baina zu ez bazara hartzailea, mesedez,
guri jakinarazi, eta jasotako informazioa ez inori jakinarazi eta suntsitu.
Barkatu okerreko email hau jasotzeak eragindako eragozpenak. Zure datuak
Avanzosc, S.L. enpresaren fitxategietan sartuta daude. Zure datuak atzitzea
eska dezakezu, bai eta, datuak zuzentzea, ezereztea eta tratamenduari aurka
egitea ere. Horretarako, enpresara jo dezakezu, helbide honetan: Julio
Urkijo, 32, 20720, Azkoitia (Gipuzkoa), telefonoa: 943 02 69 02 -
**administracion@avanzosc.com
<soporte@avanzosc.com> *
*This message and all documents attached to it are confidential and
intended only for the person or entity to which it is addressed. Any use of
this information by unauthorised persons is prohibited under current
legislation. If you received this message by error, please advise us,
destroy it and refrain from communicating its contents to third parties. We
apologise for any inconvenience receiving this email improperly may cause
to you. Your personal data are included in a file owned by Avanzosc, S.L.
If you want to exercise your rights of access, correction, erasure and
objection you can contact the Controller at Julio Urkijo, 32, 20720,
Azkoitia (Gipuzkoa), T: 943 02 69 02 – administracion@avanzosc.com
<soporte@avanzosc.com>*

**Comment by jeremyirawan** [comment] 2015-01-06 16:50
@anajuaristi Thanks for the info. I'll just fork it from github then.

**Comment by erwin-bas-solutions** [comment] 2015-01-07 19:55
Hi,

Thanks for the work done. To start i have to tell you i'm not a developer.

I tested the new module purchase_product_price_history, but when making a purchase order, it  always takes the cost price of the main product instead of the variant.

On the variant the cost per variant is saved. Only there are 2 cost price fields on a variant and it is not clear to me why (it is confusing).

Also the dependency module "product_price_history" does not create the menu "ales/Products/Price history by product" as far as i can see.

If i can test again, i would love to do that.

**Comment by Giuliano69** [comment] 2015-08-03 07:20
Hi all,
I would like to ask if this discussion has lead to important design CHANGE in product.template and product.product object for NEXT version 9.0

Are there some draft design to READ and to comment ?

Thanks

**Comment by mylbco** [comment] 2015-11-10 11:50
how is the status ?

**Comment by bealdav** [comment] 2016-07-06 14:48
how is the status for v10 ?

**Comment by pabloveintimilla** [comment] 2016-11-28 17:08
Same question. how is the status for v10 ?

**Comment by nhomar** [comment] 2016-12-03 13:32
Almost all this topic was solved in v10 and v9.0 the best way is test and if something is not solved yet comment it here.

@qdp-odoo you should close this issue if is ready I think

**Comment by pabloveintimilla** [comment] 2016-12-07 18:27
Hi,

The problem continue in cost field, for example:

1. Crate a product with $10 of cost
2. Create a product variant, define a cost $11
3. Create a purchase order and select product variant, the cost is $10, not $11.

I use Odoo 10.0-20161129 (Community edition)

**Comment by Yenthe666** [comment] 2017-10-05 11:40
Hi @user,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
I can see in the thread that there are multiple statements and/or issues so please do create new reports if multiple are still open, please do split them up if they're not related.

Regards,
Yenthe

**Closed by Yenthe666** 2017-10-05 11:40 UTC
Labels: wishlist
