### ISSUE TITLE
[10.0]Pos Session could be opened twice

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#20761] opened 2017-11-07 13:48 UTC
Impacted versions:
10.0 Community
* 10.0 fdb2f17 [I18N] add VAT es_MX translations

Steps to reproduce:
didn't succeed to identify a proper scenario

Current behavior:
some session could be opened while another is currently opened.
![bad_sessions](https://user-images.githubusercontent.com/1043935/32496720-7bfa27ae-c3ca-11e7-83ad-469510a60c1c.png)
Maybe some constraints / controls are missing

**Comment by flotho** [comment] 2017-11-13 14:34
@Yenthe666 
Any idea if it could be considered as a BUG ?

**Comment by Yenthe666** [comment] 2017-11-13 14:36
@flotho can I ask you to reproduce this on the latest 10.0 runbot? If you can reproduce it there I can confirm it and I'll do my very best to have somebody have a look at it. 😉

**Comment by Yenthe666** [comment] 2017-11-13 15:04
Thanks - Please do try to update your local Odoo to the latest source code too. It is just to make sure the problem is still there and that we have a good case to test it. Thank you!

**Comment by flotho** [comment] 2018-01-17 16:28
Hi,
I recently updated my repo and have other issues that seems to be related. IMO, the rescue mode was not working correctly in my latest tests. 
So please find attached an example of session for the same POS that are really weird 👍 
![screenshot_20180117_171937_barb](https://user-images.githubusercontent.com/1043935/35053665-0df0946e-fbab-11e7-92cb-f9ff585a8f54.png)

For sure the vendor close the session in an appropriate manner, for sure Odoo started correctly a rescue session and save all the orders in the rescue session.
Yet, Odoo allowed somebody to open another session whereas another one was already opened.

@Yenthe666 , what's your point of view for this one.

**Comment by Yenthe666** [comment] 2018-01-18 07:22
Hi @flotho,

In short: this shouldn't happen. Can you please find a way to reproduce this? Otherwise it'll be hard to figure out where it comes from and what should be fixed.

Regards,
Yenthe

**Comment by flotho** [comment] 2018-01-31 11:39
Hi @Yenthe666 , I think I can't reproduce it.
Yet the #22638 could be related because accessing directly to the POS url could be the source of the problem.
regards

**Comment by pimodoo** [comment] 2018-02-21 12:43
Hello, as the POS can work offline, nothing we cannot do anything to prevent opening twice the same session on two different computer, and that's why there are rescue sessions.

Best regards

**Closed by pimodoo** 2018-02-21 12:43 UTC
Labels: 10.0, Logistics

**Comment by flotho** [comment] 2018-04-06 20:44
Hi @pimodoo , I'm not sure to understand.
Opening a session is only possible online as far as I know. Better is to say starting a session, with all the control stuff before running the POS. Only the open button on the POS dasboard allow to start the session. 
On the other hand I totally understand that POS could work offline (even if it became a problem regarding to the french law) and you added rescue session to be able to handle pos.order saved in an already *closed* session.
So the point is not on opening the POS but on starting a new session. This part must be controlled in an harder way IMHO.
