### ISSUE TITLE
Odoo Creates Multiple stock_quant of Product After Validating And Changes qty to Zero

### ISSUE THREAD

**Issue by raspberryflakes** [odoo/odoo#61454] opened 2020-11-06 05:39 UTC
Impacted versions:
Odoo Enterprise 12

Steps to reproduce:
Validating Picking Operation, Internal Transfer or Delivery Order

Current behaviour:
1. After validating one of three operations above, screen goes to loading moment for a long time
2. Once it finished, operation status changed from "Ready" to "Done"
3. Operation status already in "done" state but quantity becomes zero 
3. Every product included in one of operation above generating new stock_quant
4. When validating another operation the process back to behaviour number 1

Expected behaviour:
- Stock_quant should be merged into one instead of minus other stock_quant.
- Product qty inside operations should be persist and not changed into zero.
- User should be able to begin validating other operations without experiencing long time amount of loading.

Video/Screenshot link (optional):
Multiple quant of the product : 
![image](https://user-images.githubusercontent.com/68892527/98330132-b0b56c00-2034-11eb-9bac-109a02a91fec.png)

Qty in operation becomes zero : 
![Screen Shot 2020-11-06 at 13 35 28](https://user-images.githubusercontent.com/68892527/98330332-1efa2e80-2035-11eb-891c-bfbdb9d2e8aa.png)

![Screen Shot 2020-11-06 at 13 36 09](https://user-images.githubusercontent.com/68892527/98330342-26b9d300-2035-11eb-8c85-3d6d90a843a1.png)

**Comment by pedrobaeza** [comment] 2020-11-06 08:34
That happens because behind the scenes, it seems to be a concurrent error, and thus Odoo acts this way. On next stock regularization, quants will be merged.

Closing as expected behavior. You should check though why you got that concurrent error. Maybe you have an incorrect opened connection.

**Closed by pedrobaeza** 2020-11-06 08:34 UTC
Labels: 12.0, Logistics

**Comment by raspberryflakes** [comment] 2021-02-18 03:58
> That happens because behind the scenes, it seems to be a concurrent error, and thus Odoo acts this way. On next stock regularization, quants will be merged.
> 
> Closing as expected behavior. You should check though why you got that concurrent error. Maybe you have an incorrect opened connection.

For future reference,
I've solved the problem by changing value in /etc/odoo.conf :
- limit_cpu_time = 240. 
- limit_time_real = 480.
