### ISSUE TITLE
[11.0] : ValueError: <class 'NameError'>: "name 'context' is not defined" when installing app

### ISSUE THREAD

**Issue by peterhoth** [odoo/odoo#19947] opened 2017-10-08 09:09 UTC
Impacted versions:
version11 (odoo-11.0-20171007)

Steps to reproduce:
NOTE: using CentOS 7.3, Python 3.5.4, Postgresql 9.2.18
1. Fresh install : unzip source
2. ./odoo-bin -c demo.conf
3. Create database "odoo11_demo" and check "Load Demonstration Data"
3. Install "CRM" App
4. vi /var/log/odoo/demo.log
: 

> 2017-10-08 08:47:59,364 19558 DEBUG odoo11_demo odoo.schema: Table 'mail_test_simple': added foreign key 'write_uid' references 'res_users'('id') ON DELETE set null
> 2017-10-08 08:47:59,431 19558 DEBUG odoo11_demo odoo.schema: Table 'mail_test': added foreign key 'alias_id' references 'mail_alias'('id') ON DELETE restrict
> 2017-10-08 08:47:59,434 19558 DEBUG odoo11_demo odoo.schema: Table 'mail_test': added foreign key 'create_uid' references 'res_users'('id') ON DELETE set null
> 2017-10-08 08:47:59,436 19558 DEBUG odoo11_demo odoo.schema: Table 'mail_test': added foreign key 'write_uid' references 'res_users'('id') ON DELETE set null
> 2017-10-08 08:47:59,573 19558 INFO odoo11_demo odoo.modules.loading: loading mail/wizard/invite_view.xml
> 2017-10-08 08:47:59,613 19558 INFO odoo11_demo odoo.modules.loading: loading mail/wizard/mail_compose_message_view.xml
> 2017-10-08 08:47:59,670 19558 DEBUG odoo11_demo odoo.tools.convert: Context value ({                             'default_composition_mode': 'mass_mail',                             'default_partner_to': '${object.id or \'\'}',                             'default_active_domain': [['id', 'in', context.get('active_ids', [])]],                         }) for element with id "action_partner_mass_mail" or its data node does not parse at server-side, keeping original string, in case it's meant for client side only
> Traceback (most recent call last):
>   File "/opt/odoo11/demo/odoo-11.0-20171007/odoo/tools/safe_eval.py", line 347, in safe_eval
>     return unsafe_eval(c, globals_dict, locals_dict)
>   File "", line 1, in <module>
> NameError: name 'context' is not defined
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/odoo11/demo/odoo-11.0-20171007/odoo/tools/convert.py", line 224, in get_context
>     ctx_res = safe_eval(ctx, eval_dict)
>   File "/opt/odoo11/demo/odoo-11.0-20171007/odoo/tools/convert.py", line 28, in <lambda>
>     safe_eval = lambda expr, ctx={}: s_eval(expr, ctx, nocopy=True)
>   File "/opt/odoo11/demo/odoo-11.0-20171007/odoo/tools/safe_eval.py", line 370, in safe_eval
>     pycompat.reraise(ValueError, ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr)), exc_info[2])
>   File "/opt/odoo11/demo/odoo-11.0-20171007/odoo/tools/pycompat.py", line 85, in reraise
>     raise value.with_traceback(tb)
>   File "/opt/odoo11/demo/odoo-11.0-20171007/odoo/tools/safe_eval.py", line 347, in safe_eval
>     return unsafe_eval(c, globals_dict, locals_dict)
>   File "", line 1, in <module>
> ValueError: <class 'NameError'>: "name 'context' is not defined" while evaluating
> "{                             'default_composition_mode': 'mass_mail',                             'default_partner_to': '${object.id or \\'\\'}',                             'default_active_domain': [['id', 'in', context.get('active_ids', [])]],                         }"
> 2017-10-08 08:47:59,680 19558 INFO odoo11_demo odoo.modules.loading: loading mail/views/mail_message_subtype_views.xml
> 2017-10-08 08:47:59,756 19558 INFO odoo11_demo odoo.modules.loading: loading mail/views/mail_tracking_views.xml
> 2017-10-08 08:47:59,832 19558 INFO odoo11_demo odoo.modules.loading: loading mail/views/mail_message_views.xml
> 2017-10-08 08:47:59,991 19558 INFO odoo11_demo odoo.modules.loading: loading mail/views/mail_mail_views.xml
> 

:

**Comment by Yenthe666** [comment] 2017-10-09 11:56
Hi @peterhoth,

Could you try this again? I believe this has been fixed in the meanwhile too.
I can't reproduce it on a runbot anymore (which has demo data checked on)

**Comment by Yenthe666** [comment] 2018-01-10 08:51
Closing as there has been no feedback in months.

**Closed by Yenthe666** 2018-01-10 08:51 UTC
