### ISSUE TITLE
Record Count is not refreshing ver 13

### ISSUE THREAD

**Issue by sxrgit** [odoo/odoo#52236] opened 2020-06-02 08:50 UTC
![Error Count](https://user-images.githubusercontent.com/32684065/83500276-2d6b7980-a4dc-11ea-91bc-0c10d8beb495.png)
Impacted versions: 13

Steps to reproduce: Select any record in List view , add some filter even if the number of record changes the count does not change

Current behavior: Count not changing

Expected behavior: Count should change

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2020-06-02 09:02
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by sxrgit** [comment] 2020-06-02 09:14
Hi, issue exists in runbot too. The screenshot attached is of runbot only.  I have explained the steps to reproduce in the issue itself. Kindly check.

**Comment by pedrobaeza** [comment] 2020-06-02 09:19
Sames as the other issue you have put.

Closing meanwhile no further evidence.

**Closed by pedrobaeza** 2020-06-02 09:19 UTC
Labels: Need information

**Comment by sxrgit** [comment] 2020-06-02 09:22
You are right working in other browser fine. I was using edge and it was showing problems.
