### ISSUE TITLE
Odoo 13 language translation issue

### ISSUE THREAD

**Issue by abhishekms123** [odoo/odoo#53190] opened 2020-06-18 03:48 UTC
When language is translated from English to any other languages in odoo13 after changing in preferences, white blank screen appears..  Any solutions? Only when language is translated white screen appears.. is there any solution to solve the problem?

**Comment by pedrobaeza** [comment] 2020-06-18 06:48
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by ericzen** [comment] 2020-06-22 15:19
Hello
I've the same issue on premise version odoo 13. Fresh install on a demo base install and only website installed.
Regards

**Comment by abhishekms123** [comment] 2020-06-22 15:53
Check the log file of odoo 13 , I have solved the problem by checking the
log. The problem is  file is missing in add-ons locale location, so create
the file using touch cmd (missing file will be mentioned in log file)

**Closed** 2020-06-23 08:19 UTC
Labels: Need information
