### ISSUE TITLE
Odoo 11 - Error generating and printing invoice from order 

### ISSUE THREAD

**Issue by newodoo** [odoo/odoo#23859] opened 2018-03-23 17:05 UTC
Impacted versions:
Odoo11

Steps to reproduce:

Create a new Order with one stockable product in quantity = 1
Click on **Create Invoice**  and select the invoicing type you prefear (error on every type selected)

Current behavior:
An error is shown:
```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 934, in call_button
    action = self._call_kw(model, method, args, {})
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\sale\wizard\sale_make_invoice_advance.py", line 134, in create_invoices
    sale_orders.action_invoice_create(final=True)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\sale\models\sale.py", line 448, in action_invoice_create
    subtype_id=self.env.ref('mail.mt_note').id)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\mail\models\mail_thread.py", line 1940, in message_post_with_view
    record.message_post_with_template(False, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\mail\models\mail_thread.py", line 1965, in message_post_with_template
    ).create(kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\mail\models\mail_message.py", line 768, in create
    message = super(Message, self).create(values)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 3307, in create
    record = self.browse(self._create(old_vals))
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 3400, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.InternalError: ERRORE:  lettura del blocco 5 nel file "base/16393/19510" fallita: letti soli 0 byte di 8192
```
Expected behavior:
The Invoice should be created
Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/37513316/37843050-1b0dd278-2ec4-11e8-8ec2-1249e91af560.png)

In the log file the following message is logged:
```
2018-03-23 16:18:14,000 1140 ERROR matranga odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 934, in call_button
    action = self._call_kw(model, method, args, {})
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\sale\wizard\sale_make_invoice_advance.py", line 134, in create_invoices
    sale_orders.action_invoice_create(final=True)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\sale\models\sale.py", line 448, in action_invoice_create
    subtype_id=self.env.ref('mail.mt_note').id)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\mail\models\mail_thread.py", line 1940, in message_post_with_view
    record.message_post_with_template(False, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\mail\models\mail_thread.py", line 1965, in message_post_with_template
    ).create(kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\mail\models\mail_message.py", line 768, in create
    message = super(Message, self).create(values)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 3307, in create
    record = self.browse(self._create(old_vals))
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 3400, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.InternalError: ERRORE:  lettura del blocco 4 nel file "base/16393/19510" fallita: letti soli 0 byte di 8192

2018-03-23 16:18:14,000 1140 INFO matranga werkzeug: 127.0.0.1 - - [23/Mar/2018 16:18:14] "POST /web/dataset/call_button HTTP/1.1" 200 -
2018-03-23 16:18:14,345 1140 INFO matranga werkzeug: 127.0.0.1 - - [23/Mar/2018 16:18:14] "POST /web/dataset/call_kw/sale.advance.payment.inv/read HTTP/1.1" 200 -
2018-03-23 16:18:24,907 1140 INFO matranga werkzeug: 127.0.0.1 - - [23/Mar/2018 16:18:24] "POST /longpolling/poll HTTP/1.1" 200 -
2018-03-23 16:19:15,249 1140 INFO matranga werkzeug: 127.0.0.1 - - [23/Mar/2018 16:19:15] "POST /longpolling/poll HTTP/1.1" 200 -
```

**Comment by pedrobaeza** [comment] 2018-03-23 17:09
Can you please try to reproduce the problem in runbot? http://runbot.odoo.com/

**Comment by sswapnesh** [comment] 2018-03-23 17:50
Should be due to Some data corruption in postgres.

**Comment by newodoo** [comment] 2018-03-23 18:17
Hi sswapnesh, you are right, can you suggest how to investigate on this? I have two istance of the same application on windows server 2012 r2, cloned coping the following directory:
C:\Program Files (x86)\Odoo 11.0
C:\Users\Administrator\AppData\Local\OpenERP S.A
(is this all I need to clone an environment?)
in one of the istance (the original) the create invoice is working fine, in the other istance I have the error.

**Comment by pedrobaeza** [comment] 2018-03-23 18:21
Probably you are not copying filestore, but this is not Odoo related, but your deployment, so I close the issue.

**Closed by pedrobaeza** 2018-03-23 18:21 UTC
Labels: 11.0
