### ISSUE TITLE
[7.0] Flag on the group 'Check Total on supplier invoices' depends on the group 'Allow multi currencies'

### ISSUE THREAD

**Issue by tafaRU** [odoo/odoo#2995] opened 2014-10-09 14:32 UTC
Hello,

shown below the steps to reproduce it on runbot::
1. in **Techinical Settings** set as True the flag **Check Total on supplier invoices** (which corresponds to the group _account.group_supplier_inv_check_total_);
2. in Settings --> Accounting set as True the flag **Allow multi currencies** (which corresponds to the group _base.group_multi_currency_);
3. the flag **Check Total on supplier invoices** has become **False**.

In addition:
1. in **Techinical Settings** set again as True the flag **Check Total on supplier invoices**;
2. in Settings --> Accounting set as False the flag **Allow multi currencies**;
3. the flag **Check Total on supplier invoices** has become again **False**.

You can see the video at: http://youtu.be/i0JaZ3wIsnM

Thank you in advance.

**Comment by Yenthe666** [comment] 2017-12-06 15:28
Indeed - not a bug but a setting. Closing as this was already answered.

**Closed by Yenthe666** 2017-12-06 15:28 UTC
Labels: Accounting
