### ISSUE TITLE
Bug in the pos_restaurant module: tables are duplicated ++

### ISSUE THREAD

**Issue by lastalfriday** [odoo/odoo#27921] opened 2018-10-18 07:14 UTC
Impacted versions: > 11

Steps to reproduce: create a table, then deselect it => you now have 2 tables

This is what happens when you first create a table
```
rpc.query({
                model: 'restaurant.table',
                method: 'create_from_ui',
                args: [serializable_table],
            })
            .then(function (table_id){
                rpc.query({
                        model: 'restaurant.table',
                        method: 'search_read',
                        args: [[['id', '=', table_id]], fields],
                        limit: 1,
                    })
                    .then(function (table){
                        for (var field in table) {
                            self.table[field] = table[field];
                        }
                        self.renderElement();
                    });
            }, function(type,err) {
                self.gui.show_popup('error',{
                    'title':_t('Changes could not be saved'),
                    'body': _t('You must be connected to the internet to save your changes.'),
                });
});
```

This is the part of the code that is buggy
```
                   .then(function (table){
                        for (var field in table) {
                            self.table[field] = table[field];
                        }
                        self.renderElement();
                    });
```
because the returned `table`from search_read is not an object, but an array containing the object on index 0. This means `self.table` wont get its id set and will create a new one when deselecting instead of updating the one being selected.

![selection_110](https://user-images.githubusercontent.com/40355961/47137133-0be15e00-d2b6-11e8-8040-3af894fbaf64.png)

^ first is `table`, second is `self.table`

**Comment by pedrobaeza** [comment] 2018-10-18 07:16
Duplicate of #24831, so closing.

**Closed by pedrobaeza** 2018-10-18 07:16 UTC
