### ISSUE TITLE
Unable to update form

### ISSUE THREAD

**Issue by lcmsrl** [odoo/odoo#13427] opened 2016-09-08 08:47 UTC
Impacted versions:
Version 9.0c-20160808 (Community Edition, server Windows 10)
Version 9.0c-20160906 (Community Edition, server Ubuntu 16)

Steps to reproduce:
- activate the developer mode
- go to Manufacturing -> Products and click on a product
- with product form opened, edit the form (debug menu -> manage views -> edit)
- add a field or modify the property of an existing one 
- click on update button

Current behavior:
the last operation (clik on update button) generate the following error:

> Uncaught TypeError: Failed to execute 'serializeToString' on 'XMLSerializer': parameter 1 is not of type 'Node'.
> http://127.0.0.1:8069/web/static/src/js/framework/utils.js:176
> Traceback:
> TypeError: Failed to execute 'serializeToString' on 'XMLSerializer': parameter 1 is not of type 'Node'.
>     at TypeError (native)
>     at Object.xml_to_str (http://127.0.0.1:8069/web/static/src/js/framework/utils.js:176:37)
>     at OdooClass.do_save_update_arch (http://127.0.0.1:8069/web_view_editor/static/src/js/view_editor.js:671:44)
>     at OdooClass.click (http://127.0.0.1:8069/web_view_editor/static/src/js/view_editor.js:873:30)
>     at HTMLButtonElement.<anonymous> (http://127.0.0.1:8069/web/static/src/js/framework/dialog.js:87:41)
>     at HTMLButtonElement.dispatch (http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:4641:58)
>     at HTMLButtonElement.elemData.handle (http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:4309:63)

Expected behavior:
update without error

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2018-04-29 00:05
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-04-29 00:05 UTC
Labels: 9.0, Framework
