### ISSUE TITLE
_register_hook is unsafe to extend BaseModels

### ISSUE THREAD

**Issue by llacroix** [odoo/odoo#16540] opened 2017-04-20 12:32 UTC
Impacted versions:
Probably all (tested on V8)

Steps to reproduce:
Define a _register_hook on any model which will be called when it should. Since it's not possible to extend base methods like search, the only way to extend the behaviour for all model is to replace the method in BaseModel._search by something else and keep a reference of BaseModel._search to be called as we could do with super(). 

Current behavior:
It's happening in the WorkerCron but my guess it could affect any worker, _register_hook will be called multiple times and instead of overriding a fresh BaseModel we override the BaseModel we overrode. As a result, after a repetition of WorkerCron calling register_hook, when calling a method such as _search, it will call _new_search as _ns for simplicity then _base_search as _bs:

_register_hook called once:

    _ns -> _bs

_register_hook called twice:

    _ns2 -> _ns1-> _bs

_register_hook called n times:

    _ns(n) -> .... -> _ns(1) -> _bs

Expected behavior:

_register_hook should be called only once on a fresh model class instead of extending indefinitely the same Model. Which in return can result in a function call time growing geometrically.

Also, since the register_hook might get called multiple times, we can check that the latest method is not the one the actual register hook is going to override.. But this won't work in special case where a different module tries to extend the same method in a similar fashion.

For example, module A check if it already overridden the method. Skip the override because it's already overridden... Module B check if the latest method is its own, no, it override it. Then the next time module A will check that the method is overridden and it will see method from module B and not its own. So it could lead to a chain of method alternating to the original one. 

My guess is that it would be safer/easier to simply add a layer above the real BaseModel and create some kind of abstract model named "base.model", Having all models inherit from this model. This way, we can use the standard odoo inheritance rendering the _register_hook mostly useless. All changes made directly to a BaseModel class should be prohibited as it can cause some serious issues. But the API should be changed to make it unnecessary to extend the BaseModel class.

**Comment by xmo-odoo** [comment] 2017-04-24 08:34
Dupe of #9084

That was fixed in version 10 with the introduction of the `Base` (`_name = 'base'`) abstract model (53572ba4c6b678656aa34bc7a2db26481b38dff3), as well as improvements to inheritance visibility (#10288). They are breaking changes and news features and will not be backported (cf #9084).

**Closed by xmo-odoo** 2017-04-24 08:34 UTC

**Comment by llacroix** [comment] 2017-04-24 20:00
@xmo-odoo  that's a good news, but for v8,v9 is there a particular way to fix this correctly?

**Comment by yucer** [comment] 2017-11-22 11:20
@llacroix: I forgot to thank you about this in the past. Thanks for caring about **v8** and **v9**.

**Comment by llacroix** [comment] 2017-11-23 20:15
@yucer  in case you're facing the same issue, I fixed one of our module by completely ditching the _register_hook method. I instead monkey patched the classes directly. It's not pretty but it works. I discovered this bug after overriding the search method to search in multiple languages.

Needless to say how bad it was to have odoo search n^x times if n is the number of languages and x the number of time register_hook appended a hook. 

The monkey patch can be an issue if you're not going to install the module that does the monkey patch. We do the monkey patch at import time, and odoo import all python modules even if they are not installed.

**Comment by lmignon** [comment] 2017-11-24 07:15
@llacroix @yucer In V8 and v9 you should use model._patch_method to patch existing method 
https://github.com/odoo/odoo/blob/9.0/openerp/models.py#L5324
https://github.com/odoo/odoo/blob/8.0/openerp/models.py#L5212

If you need to add new method, the best to do is to use the 'register_hook' and check if the method is already patched before applying your patch.

**Comment by llacroix** [comment] 2017-11-24 07:33
@lmignon oh it was using patch_method, the problem being that the bug created a new method each time which mean there is no real way to check if you alread patched it or not. Since register hook gets called multiple times.

**Comment by yucer** [comment] 2017-11-26 01:14
@llacroix  Just to visualize it a little more. I guess your code was like this right ?

```python
class MyModelPatch(models.AbstractModel):
    ''' My model patch'''

    _name = 'my.model.patch'

    def _register_hook(self, cr):

        @api.multi
        def my_method(self):
            res = my_method.origin(self)
            # my code to extend the result
            return res

        myModel = self.registry('my.model')
        origin = getattr(myModel.my_method, 'origin', None)
        if origin != my_method:
            myModel._patch_method('my_method', my_method)
            _logger.warning('MyModel.my_method hook registered !')
        
        return super(MyModelPatch, self)._register_hook(cr)
```

what I don't understand is why your **_register_hook** method was called twice. I have not used **_register_hook** in complicated inheritance constructions, just in Basemodel, but It was called only once for me.

Maybe you have defined it in a mixing ?

I guess that your workaround was similar to this right?

```python
class MyModelPatch(models.AbstractModel):
    ''' My model patch'''

    _name = 'my.model.patch'

    def _register_hook(self, cr):

        @api.multi
        def my_method(self):
            res = my_method.origin(self)
            # my code to extend the result
            return res

        myModel = self.registry('my.model')
        if hasattr(MyModelPatch, 'registered', False):
            myModel._patch_method('my_method', my_method)
            MyModelPatch.registered = True
            _logger.warning('MyModel.my_method hook registered !')
        
        return super(MyModelPatch, self)._register_hook(cr)

```
