### ISSUE TITLE
[14.0] website: steps block breaks when changing icon

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#63806] opened 2020-12-28 07:10 UTC
Impacted versions: 14.0

Steps to reproduce:
1. Login to the latest runbot 14.0 with the admin user
2. Open the website and click on edit
3. Add the "Steps" building block
4. Change the icon in one of the steps
Steps in video: 

https://user-images.githubusercontent.com/6352350/103196217-0d6e2e00-48e4-11eb-925e-7ae7ab1c941f.mp4

Current behavior: The block breaks and the icon is pushed to the left with dirty alignment.

Expected behavior: The icon is nicely changed.

Support ticket number submitted via odoo.com/help (optional): 2423705

**Comment by Yenthe666** [comment] 2020-12-28 07:15
Very similar issues with the "Features" block actually. When you change the icon you see that the icon block becomes much smaller:
![image](https://user-images.githubusercontent.com/6352350/103196559-b452ca00-48e4-11eb-9bb8-2f4bfff1290d.png)

And yet similar issues with the "Features" grid block too:
![image](https://user-images.githubusercontent.com/6352350/103196661-dba99700-48e4-11eb-90d4-c570c0d41b65.png)

**Comment by Yenthe666** [comment] 2020-12-28 07:24
@rdeodoo @sbuhl puhh these building blocks are all pretty broken :) Can this get checked out ASAP please? This was painful to all break in a new customer demo call.

**Comment by sbuhl** [comment] 2020-12-28 09:18
@Yenthe666 Thank you for the report, we'll tackle this as soon as possible.

Cheers

**Comment by sdegueldre** [comment] 2021-01-08 10:52
@Yenthe666 there are two different behaviours you're reporting, one which is a bug and is a duplicate of #60224 (icons change size or lose some of their classes when you change the icon itself)

The other one is regarding icons being small when replacing images, but that is the expected behaviour. We may want to improve this in master but as far as I can tell this is not a bug (can you confirm @sbuhl  ?)

I'll close this as duplicate of #60224 for now, we can reopen it if the second behaviour is unexpected in stable but I don't think that's the case.

**Closed by sdegueldre** 2021-01-08 10:52 UTC
Labels: 14.0, Duplicate, OE, Website
