### ISSUE TITLE
[BUG: 11.0 ... 14.0] website_sale checkout: partner_shipping_id by last_order (checkout_values)

### ISSUE THREAD

**Issue by bobslee** [odoo/odoo#71852] opened 2021-06-08 08:48 UTC
Impacted versions: 14, 13, 12, 11

Please review, seems I spotted a severe bug in the Website (sale) Checkout process.

**Module:** `website_sale`
**controller method:** `checkout_values`

If no shipping (partner) has been determined, the method tries to find and set the partner from the last (sale) order.

**BUG:**
See: https://github.com/odoo/odoo/blob/14.0/addons/website_sale/controllers/main.py#L537
If found a `last_order`, the ID of the `last_order` is now stored **INSTEAD** of the `last_order.partner_id.id`

**Comment by pedrobaeza** [comment] 2021-06-08 15:45
Please indicate steps to reproduce a problem via UI.

**Comment by bobslee** [comment] 2021-06-08 15:52
Sorry, this came along while extending this method.
Currently no time to dictate UI steps. Code seems obvious to me.

**Comment by pedrobaeza** [comment] 2021-06-08 16:02
OK, I get you. Maybe it's only dead code. I think it should be:
```python
                elif not order.partner_shipping_id:
                    last_order = request.env['sale.order'].sudo().search([("partner_id", "=", order.partner_id.id)], order='id desc', limit=1)
                    if last_order:
                        order.partner_shipping_id = last_order.partner_shipping_id.id
```

@JKE-be can you check?

**Comment by rdeodoo** [comment] 2021-06-10 09:10
Duplicate of #65629
Indeed, this is a dead code, you can't reach it since [`partner_shipping_id` is required](https://github.com/odoo/odoo/blob/56fe0abca3aa2d262a43740ea7b2fdac16eb1b08/addons/sale/models/sale.py#L201), the condition can't be True and the code can't be reached.

**Closed by rdeodoo** 2021-06-10 09:10 UTC
Labels: 14.0, Website

**Comment by bobslee** [comment] 2021-06-10 17:23
Thanks for analyzing and and answer.
Why not remove such death code?
For clarity, to prevent regression or when somebody overrides the required field.

**Comment by bobslee** [comment] 2021-06-11 05:09
Sorry I missed that. Thanks!
