### ISSUE TITLE
ODOO add a prouct

### ISSUE THREAD

**Issue by Douwe10** [odoo/odoo#9514] opened 2015-11-10 13:57 UTC
Hello,

I cant create my on topic on this site. I try to do it on this way. My problem:
I start for 2 days with odoo 8.
My steps:
Install warehouse
Go to product
Make a product
Fill the name of the product in and try to make it. I cant make it because there is coming a warning:
ValidateError
Field(s) `uom_id` failed against a constraint: Error: The default Unit of Measure and the purchase Unit of Measure must be in the same category.
Error details:
AccessError
The requested operation cannot be completed due to security restrictions. Please contact your system administrator.
(Document type: product.template, Operation: read)

How do i need to make it work???

Thanks 
Douwe

**Comment by Yenthe666** [comment] 2016-05-24 06:31
Hi @Douwe10,

You're facing this issue because you've created a product with another Unit of Measure than the purchase Unit of this product is. For example: Your unit of measure is in kg but your purchase unit is in pieces.
The access error might be a bug but since this report is rather old I think this should be fixed by now. I can't reproduce this in any way.

Can you let me know if this is still an active problem or not?

Thanks,
Yenthe

**Comment by Yenthe666** [comment] 2016-06-22 07:28
There has been no response in a month so I'm closing this issue.

**Closed by Yenthe666** 2016-06-22 07:28 UTC
