### ISSUE TITLE
get_current_website RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by xiexiaopeng2016** [odoo/odoo#68568] opened 2021-03-31 06:06 UTC
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

  File "/home/odoo/odoo-14/addons/website/models/website.py", line 568, in get_current_website
    website_id = self._get_current_website_id(domain_name, country_id, fallback=fallback)
  File "<decorator-gen-301>", line 2, in _get_current_website_id
  File "/home/odoo/odoo-14/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/odoo-14/addons/website/models/website.py", line 625, in _get_current_website_id
    found_websites = self.search([('domain', 'ilike', _remove_port(domain_name))]).sorted('country_group_ids')
  File "/home/odoo/odoo-14/odoo/models.py", line 1704, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/home/odoo/odoo-14/odoo/models.py", line 4495, in _search
    self._flush_search(args, order=order)
  File "/home/odoo/odoo-14/odoo/models.py", line 4413, in _flush_search
    domain = list(domain) + (self.env['ir.rule']._compute_domain(self._name, 'read') or [])
  File "<decorator-gen-176>", line 2, in _compute_domain
  File "/home/odoo/odoo-14/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/odoo-14/odoo/addons/base/models/ir_rule.py", line 142, in _compute_domain
    eval_context = self._eval_context()
  File "/home/odoo/odoo-14/addons/website/models/ir_rule.py", line 19, in _eval_context
    res['website'] = is_frontend and Website.get_current_website() or Website
  File "/home/odoo/odoo-14/addons/website/models/website.py", line 568, in get_current_website
    website_id = self._get_current_website_id(domain_name, country_id, fallback=fallback)
  File "<decorator-gen-301>", line 2, in _get_current_website_id
  File "/home/odoo/odoo-14/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/odoo-14/addons/website/models/website.py", line 625, in _get_current_website_id
    found_websites = self.search([('domain', 'ilike', _remove_port(domain_name))]).sorted('country_group_ids')
  File "/home/odoo/odoo-14/odoo/models.py", line 1704, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/home/odoo/odoo-14/odoo/models.py", line 4495, in _search
    self._flush_search(args, order=order)
  File "/home/odoo/odoo-14/odoo/models.py", line 4413, in _flush_search
    domain = list(domain) + (self.env['ir.rule']._compute_domain(self._name, 'read') or [])
  File "<decorator-gen-176>", line 2, in _compute_domain
  File "/home/odoo/odoo-14/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/odoo-14/odoo/addons/base/models/ir_rule.py", line 142, in _compute_domain
    eval_context = self._eval_context()
  File "/home/odoo/odoo-14/addons/website/models/ir_rule.py", line 19, in _eval_context
    res['website'] = is_frontend and Website.get_current_website() or Website
  File "/home/odoo/odoo-14/addons/website/models/website.py", line 568, in get_current_website
    website_id = self._get_current_website_id(domain_name, country_id, fallback=fallback)
  File "<decorator-gen-301>", line 2, in _get_current_website_id
  File "/home/odoo/odoo-14/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/odoo-14/addons/website/models/website.py", line 625, in _get_current_website_id
    found_websites = self.search([('domain', 'ilike', _remove_port(domain_name))]).sorted('country_group_ids')
  File "/home/odoo/odoo-14/odoo/models.py", line 1704, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/home/odoo/odoo-14/odoo/models.py", line 4495, in _search
    self._flush_search(args, order=order)
  File "/home/odoo/odoo-14/odoo/models.py", line 4413, in _flush_search
    domain = list(domain) + (self.env['ir.rule']._compute_domain(self._name, 'read') or [])
  File "<decorator-gen-176>", line 2, in _compute_domain
  File "/home/odoo/odoo-14/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/odoo-14/odoo/addons/base/models/ir_rule.py", line 142, in _compute_domain
    eval_context = self._eval_context()
  File "/home/odoo/odoo-14/addons/website/models/ir_rule.py", line 19, in _eval_context
    res['website'] = is_frontend and Website.get_current_website() or Website
  File "/home/odoo/odoo-14/addons/website/models/website.py", line 568, in get_current_website
    website_id = self._get_current_website_id(domain_name, country_id, fallback=fallback)
  File "<decorator-gen-301>", line 2, in _get_current_website_id
  File "/home/odoo/odoo-14/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/odoo-14/addons/website/models/website.py", line 625, in _get_current_website_id
    found_websites = self.search([('domain', 'ilike', _remove_port(domain_name))]).sorted('country_group_ids')
  File "/home/odoo/odoo-14/odoo/models.py", line 1704, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/home/odoo/odoo-14/odoo/models.py", line 4495, in _search
    self._flush_search(args, order=order)
  File "/home/odoo/odoo-14/odoo/models.py", line 4413, in _flush_search
    domain = list(domain) + (self.env['ir.rule']._compute_domain(self._name, 'read') or [])
  File "<decorator-gen-176>", line 2, in _compute_domain
  File "/home/odoo/odoo-14/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/odoo-14/odoo/addons/base/models/ir_rule.py", line 142, in _compute_domain
    eval_context = self._eval_context()
  File "/home/odoo/odoo-14/addons/website/models/ir_rule.py", line 19, in _eval_context
    res['website'] = is_frontend and Website.get_current_website() or Website
  File "/home/odoo/odoo-14/addons/website/models/website.py", line 568, in get_current_website
    website_id = self._get_current_website_id(domain_name, country_id, fallback=fallback)
  File "<decorator-gen-301>", line 2, in _get_current_website_id
  File "/home/odoo/odoo-14/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/odoo-14/addons/website/models/website.py", line 625, in _get_current_website_id
    found_websites = self.search([('domain', 'ilike', _remove_port(domain_name))]).sorted('country_group_ids')
  File "/home/odoo/odoo-14/odoo/models.py", line 1704, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/home/odoo/odoo-14/odoo/models.py", line 4495, in _search
    self._flush_search(args, order=order)
  File "/home/odoo/odoo-14/odoo/models.py", line 4413, in _flush_search
    domain = list(domain) + (self.env['ir.rule']._compute_domain(self._name, 'read') or [])
  File "<decorator-gen-176>", line 2, in _compute_domain
  File "/home/odoo/odoo-14/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/odoo-14/odoo/addons/base/models/ir_rule.py", line 142, in _compute_domain
    eval_context = self._eval_context()
  File "/home/odoo/odoo-14/addons/website/models/ir_rule.py", line 19, in _eval_context
    res['website'] = is_frontend and Website.get_current_website() or Website
  File "/home/odoo/odoo-14/addons/website/models/website.py", line 568, in get_current_website
    website_id = self._get_current_website_id(domain_name, country_id, fallback=fallback)
  File "<decorator-gen-301>", line 2, in _get_current_website_id
  File "/home/odoo/odoo-14/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/odoo-14/addons/website/models/website.py", line 625, in _get_current_website_id
    found_websites = self.search([('domain', 'ilike', _remove_port(domain_name))]).sorted('country_group_ids')
  File "/home/odoo/odoo-14/odoo/models.py", line 1704, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/home/odoo/odoo-14/odoo/models.py", line 4495, in _search
    self._flush_search(args, order=order)
  File "/home/odoo/odoo-14/odoo/models.py", line 4413, in _flush_search
    domain = list(domain) + (self.env['ir.rule']._compute_domain(self._name, 'read') or [])
  File "<decorator-gen-176>", line 2, in _compute_domain
  File "/home/odoo/odoo-14/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/odoo-14/odoo/addons/base/models/ir_rule.py", line 142, in _compute_domain
    eval_context = self._eval_context()
  File "/home/odoo/odoo-14/addons/website/models/ir_rule.py", line 11, in _eval_context
    res = super(IrRule, self)._eval_context()
  File "/home/odoo/odoo-14/odoo/addons/base/models/ir_rule.py", line 54, in _eval_context
    'user': self.env.user.with_context({}),
  File "/home/odoo/odoo-14/odoo/models.py", line 5124, in with_context
    return self.with_env(self.env(context=context))
  File "/home/odoo/odoo-14/odoo/api.py", line 507, in __call__
    return Environment(cr, uid, context, su)
  File "/home/odoo/odoo-14/odoo/api.py", line 446, in __new__
    env, envs = None, cls.envs
  File "/home/odoo/odoo-14/odoo/tools/func.py", line 114, in __get__
    return self.fget.__get__(None, owner)()
  File "/home/odoo/odoo-14/odoo/api.py", line 417, in envs
    return getattr(cls._local, 'environments', ())
  File "/home/odoo/.local/lib/python3.6/site-packages/werkzeug/local.py", line 70, in __getattr__
    def __getattr__(self, name):
RecursionError: maximum recursion depth exceeded

**Comment by pedrobaeza** [comment] 2021-03-31 06:08
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Closed** 2023-04-07 14:22 UTC
Labels: Need information
