### ISSUE TITLE
There is problem if we create down payment with extra amount

### ISSUE THREAD

**Issue by Omkar2295** [odoo/odoo#26401] opened 2018-08-16 11:31 UTC
Impacted versions:
11.0

Steps to reproduce:
1. Add order line with 100 Rs.
2. Create invoice using Down payment (fixed amount ) option.
3. Enter 300.
4. click create and view.
5. validate and register payment using bank.
6. create invoice using Invoiceable lines (deduct down payments).
7. click validate.

Current behavior:
- In customer invoice Amount due is -200.
  and after open that invoice it shows 200 is Amount due....i.e we have to pay again.

Expected behavior:
-Amount due should be zero and extra amount should go to Outstanding credits

Video/Screenshot link (optional):
![screenshot 75](https://user-images.githubusercontent.com/38411833/44205969-d022fe80-a175-11e8-805d-14d672019cbc.png)

![screenshot 74](https://user-images.githubusercontent.com/38411833/44205999-ecbf3680-a175-11e8-9bb7-dcccef4ab366.png)

**Comment by pedrobaeza** [comment] 2018-08-16 13:58
AFAIK, this is an uncovered case. The easiest solution is to prevent to create that kind of down payment instead of changing logic for creating a refund.

What do you think, @qdp-odoo?

**Comment by mga-odoo** [comment] 2018-08-21 18:30
I don't think its a problem

Customer balance with the negative amount shows customer balance, even if you create a down payment more then the order amount.

Look at closely, the final invoice creates the credit note not an invoice, so even if you register payment it is already a refund.

I don't think we should prevent anything as it gives flexibility to mange more business case rather preventing anything. 

Look at https://drive.google.com/file/d/1Cqys3EkW_DJtURW3xYlMNIwkdIK3eMD5/view advance payment can be refund or adjusted against the next invoice.

**Comment by pedrobaeza** [comment] 2018-08-22 06:08
Thanks for the video, @mga-odoo. Then it's clear this is not a bug, so closing.

**Closed by pedrobaeza** 2018-08-22 06:08 UTC
Labels: 11.0, Accounting
