### ISSUE TITLE
BUG in Arabic interface with "Time Off" dashboard

### ISSUE THREAD

**Issue by eranetsa** [odoo/odoo#63762] opened 2020-12-24 04:45 UTC
Impacted versions:
14

Steps to reproduce:
1. Install the "Time Off" module
2. Enable the Arabic language and make it active for the current user
3. Open "Time Off Dashboard" from the menu
4. Bug raise an error here

Current behavior:
Error:
خطأ:
Odoo Server Error
Traceback (most recent call last):
File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
result = request.dispatch()
File "/home/odoo/src/odoo/odoo/http.py", line 683, in dispatch
result = self._call_function(**self.params)
File "/home/odoo/src/odoo/odoo/http.py", line 359, in _call_function
return checked_call(self.db, *args, **kwargs)
File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
return f(dbname, *args, **kwargs)
File "/home/odoo/src/odoo/odoo/http.py", line 347, in checked_call
result = self.endpoint(*a, **kw)
File "/home/odoo/src/odoo/odoo/http.py", line 912, in __call__
return self.method(*args, **kw)
File "/home/odoo/src/odoo/odoo/http.py", line 531, in response_wrap
response = f(*args, **kw)
File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1377, in call_kw
return self._call_kw(model, method, args, kwargs)
File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1369, in _call_kw
return call_kw(request.env[model], method, args, kwargs)
File "/home/odoo/src/odoo/odoo/api.py", line 392, in call_kw
result = _call_kw_model(method, model, args, kwargs)
File "/home/odoo/src/odoo/odoo/api.py", line 365, in _call_kw_model
result = method(recs, *args, **kwargs)
File "/home/odoo/src/odoo/addons/hr_holidays/models/hr_leave.py", line 1248, in get_unusual_days
dfrom = datetime.combine(fields.Date.from_string(date_from), time.min).replace(tzinfo=UTC)
File "/home/odoo/src/odoo/odoo/fields.py", line 1771, in to_date
return datetime.strptime(value, DATE_FORMAT).date()
File "/usr/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
tt, fraction, gmtoff_fraction = _strptime(data_string, format)
File "/usr/lib/python3.8/_strptime.py", line 349, in _strptime
raise ValueError("time data %r does not match format %r" %
Exception
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/home/odoo/src/odoo/odoo/http.py", line 639, in _handle_exception
return super(JsonRequest, self)._handle_exception(exception)
File "/home/odoo/src/odoo/odoo/http.py", line 315, in _handle_exception
raise exception.with_traceback(None) from new_cause
ValueError: time data '٢٠٢٠-١١-٢٧' does not match format '%Y-%m-%d'
Expected behavior:

Video/Screenshot link (optional):
https://ibb.co/KDCNswM

Support ticket number submitted via odoo.com/help (optional):
2422915

**Comment by maherkhalil07** [comment] 2020-12-25 11:16
Hi
do you have any customized add ons?

**Comment by eranetsa** [comment] 2020-12-25 11:50
> Hi
> do you have any customized add ons?

No, I tried with a new DB, and the same bug shows. 
Also, I saw the same bug in [Subscribtions -> reporting -> Revenue KPIs]. ARABIC interface only

**Comment by maherkhalil07** [comment] 2020-12-28 22:17
i think is is a bug in odoo css file

**Comment by RachidAlassir** [comment] 2021-01-02 22:24
@eranetsa  I can't reproduce the bug on Runbot.
 Update your local code to the latest version and retest it.
Also I think it's something related to JS, I came across a similar issue before, it was related to moment.js which Odoo uses.
where it failed automatically (without specific configs) to change the arabic numbers (e.g  '٢٠٢٠-١١-٢٧') to Latin numbers that the backend accepts (_directly convert from string to date_).

**Comment by yelizariev** [comment] 2021-01-06 16:10
Fixed in https://github.com/odoo/odoo/pull/63833

**Closed** 2021-01-07 07:10 UTC
Labels: 14.0, Localization, OE
