### ISSUE TITLE
Bug in external_layout template to define the conditions of the company's report.

### ISSUE THREAD

**Issue by fv-clearcorp** [odoo/odoo#7589] opened 2015-07-13 16:15 UTC
In the reports that have more than one object with the compani_id field, the company's report is not set correctly. for example in reports to view pending payments from customers.

Steps to reproduce:
Just go to Partners 
Select a Partners
Go to the Print button > "pending payments"
Review the report and see that the "header" and "footer" of the report does not print correctly.

**Comment by Yenthe666** [comment] 2018-03-21 16:25
@sle-odoo you self assigned this quite some time ago but nothing moved here. Is this still relevant? Can you give feedback?

**Comment by sle-odoo** [comment] 2018-03-21 16:29
Not sure if the issue is still relevant, i think we would have received some tickets about it since 2015. Haven't tested it though.

**Comment by pedrobaeza** [comment] 2018-04-04 23:15
I think this has been solved lately with latest templates, so we can close it. If not, @fv-clearcorp please open a new issue without problem.

**Closed by pedrobaeza** 2018-04-04 23:15 UTC
Labels: Framework
