### ISSUE TITLE
[12.0] Sale Order notes aren't passed over to invoice

### ISSUE THREAD

**Issue by reinaldoramosarxi** [odoo/odoo#34042] opened 2019-06-11 16:40 UTC
Impacted versions: 12.0

Steps to reproduce: 
- Create invoiceable Sale Order that has at least one note line (not section, note)
- Create invoice from said Sale Order

Current behavior: The new invoice will have all of the sale order lines, including sections, but not the notes.

Expected behavior: Notes are important in order to input additional information that can't be fully inserted into product lines, so it makes sense that the method should include them in invoices.

We're not sure if this was on purpose or if it's a bug, but the action_invoice_create method in the sale package (https://github.com/odoo/odoo/blob/12.0/addons/sale/models/sale.py#L531) iterates over the lines, isolates the ones that are of type line section and runs a float_is_zero() method on all lines. 

However, the method doesn't isolate note lines.

**Comment by Yenthe666** [comment] 2019-06-11 17:27
Hmm, this is an interesting one. @dbo-odoo what do you think?

**Comment by pedrobaeza** [comment] 2019-06-11 17:44
Isn't this a duplicate of #33024?

**Comment by Yenthe666** [comment] 2019-06-11 17:51
Similar, same subject, but this is for SO to invoice and other one is invoice to credit note.

**Comment by dbo-odoo** [comment] 2019-08-22 15:34
Notes are indeed not transferred, this is by design in v12: there is no easy way to know which notes to transfer (and transferring all of them on every invoice would add a lot of noise).

We have a task to improve this, but I will close this report since this is not a bug - the feature work as intended, notes are _consciously_ ignored.

**Closed by dbo-odoo** 2019-08-22 15:34 UTC
Labels: 12.0, Sales
