### ISSUE TITLE
Put Away Strategy on Location Not Working Odoo 12 EE

### ISSUE THREAD

**Issue by usmanfarzandali** [odoo/odoo#34461] opened 2019-06-29 19:40 UTC
Impacted versions:12EE

Steps to reproduce:

Current behavior:
When i Create: Put Away Strategy on Location there is location column show only same location name which is open not all location show on location many2one fields 

Expected behavior:
When i Create: Put Away Strategy on Location should be show all location in location column 

Video/Screenshot link (optional):

![imageedit_108_9092570178](https://user-images.githubusercontent.com/22232100/60388772-7f876c00-9acf-11e9-8ba8-176aebac5527.gif)

**Comment by pedrobaeza** [comment] 2019-06-29 23:35
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by usmanfarzandali** [comment] 2019-06-30 08:43
yes it's same issue on runbot ....
Away Strategy is working fine on runbot odoo 10 EE, odoo 11 EE not working on odoo 12 EE
problem is 
when i select location its show only same location where i'm stand not show other location.

Odoo 10 EE code 

<field name="fixed_location_id"/>

Odoo 11 EE code 
 
<field name="fixed_location_id"/>

odoo 12 EE code 

<field name="fixed_location_id" domain="[('id', 'child_of', context.get('location_id'))]"/>

why domain is apply ? 
its show only current selection location in many2one fields 
hope you understand if not pls let me know i give you more detail

**Comment by pedrobaeza** [comment] 2019-06-30 12:04
The problem I see is that you are setting the putaway strategy in a location with no children, and that's why you only see that location. Putaway strategies must be put on the top parent location, that is the one where goods are received/sent. Example: WH/Stock.

Closing due to this.

**Closed by pedrobaeza** 2019-06-30 12:04 UTC
Labels: Need information
