### ISSUE TITLE
9.0 Wrong planned dates in procurements for manufacturing

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#9877] opened 2015-12-02 17:02 UTC
Here is a scenario to reproduce the problem :
This scenario is executed on December 2nd 2015

1) Connect to Runbot v9 in the "all" database as admin.

2) Add yourself to the multi-company group, so as to see the Company menu entry (!) On the company form, set "Manufacturing Lead Time" to 0, "Purchase Lead Time" to 0 and "Sale Safety days" to 0 (it make it easier to understand delays that way)

3) Create 3 products :
a) name : P3
Can be sold : yes
Can be purchased : no
Type : stockable product
Routes : Manufacture
Manufacturing Lead time : 15
Customer Lead Time : 28

=> for this product, create a new re-ordering rule with default values (OP/00009)

b) name : P2
Can be sold : no (keep it at "yes" at first, otherwise the field "Manufacturing Lead Time is hidden)
Can be purchased : no
Type : stockable product
Routes : Manufacture
Manufacturing Lead time : 5

=> for this product, create a new orderpoint with default values (OP/000010)

c) name : P1
Can be sold : no
Can be purchased : yes
Type : consumable
default values for the rest of the product configuration.

4) P2 is built from P1 ; P3 is built from P2.
So you have to create 2 BOMs :
a) First BOM :
Product = P2
qty 1
Component : P1 with qty 1
b) Second BOM :
Product = P3
qty 1
Component : P2 with qty 1

5) Create a new quotation (SO047) with 1 sale order line :
product : P3
qty : 1
On the sale order line, we have delay = 28 days (as configured on the product P3)
Confirm the quotation (we suppose we are December 2 2015)

6) The out picking corresponding to SO047 has a schedule time of December 30 2015 =>OK, it corresponds to the customer lead time of 28 days for P3. The underlying procurement has the same scheduled date.

7) Run the scheduler twice.
It will create 2 manufacturing orders :
a) one manufacturing order for P3 (MO/00014) with scheduled date = 17 November 2015... why ??? (it seems to be "today - Manufacturing Lead time of P3", which is wrong)
b) one manufacturing order for P2 (MO/00015) with scheduled date = 27 November 2015... why ??? (it seems to be "Today - Manufacturing Lead time of P2", which is wrong)
So, according to the manufacturing orders, we have to produce P3 first, and then produce P2... but we require P2 to be able to produce P3 !!! => it's all WRONG.

When we look at the procurements, we see 3 procurements :
a) a procurement for P3 with origin SO0047, linked to the rule "WH: Stock -> Customers", with schedule date = 30 December 2015 => OK
b) another procurement for P3 with origin OP/00009, linked to the rule "Your Company: Manufacture", with schedule date = 2 December 2015 => why this date ?
c) a procurement for P2 with origin OP/000010, linked to the rule "Your Company: Manufacture", with schedule date = 2 December 2015 => why this date ?

**Comment by alexis-via** [comment] 2015-12-02 17:03
This bug report is an update of this old bug report on LP for v7: https://bugs.launchpad.net/openobject-addons/+bug/1269528

**Comment by anajuaristi** [comment] 2015-12-02 19:35
Hi @alexis-via 

Yes... it has been like that in every Odoo, OpenERP version I know. 
The issue here is that you can not plan lowest levels MO's if you don't launch high level MO's. 

This is... all dates are calculated from the date you push a button, be confirm SO, confirm MO and so on. Procurement will be created with that date, so... manufacture delay or customer delay will be calculated using that date. 
On the other side, you need to confirm orders from high level to lowest levels so... there is no way to plan without launching every MO's. If you need cancelling one MO, it's a nightmare because you don't know the lower affected level MO's

It's because of that reason we made procurement_plan and procurement_plan_mrp modules.
With them you can split all manufacturing levels from one procurement. It will calculate the lowest level procurements date taking in mind manufacturing delays + supplier delays(product to buy) and confirming procurements will create the manufacturing or purchase orders on the order you want. 

We added the "level" field on procurements so... all of them created automatically, will be numbered with level higher that 0 and the ones created by system will be level=0 

To test this modules you should also include procurement_orderpoint_no_confirm and procurement_mrp_no_confirm. It's quite complex to explain a customer why system is not only creating manufacturing orders but also confirming them. 

Please let me know

Ana

**Comment by scosist** [comment] 2016-03-26 12:04
@alexis-via 

The combination of #11389 and #11413 should fix the wrong dates you're seeing.

> 7) Run the scheduler twice.

Using a low level code eliminates the need to run schedulers more than once. #4315 would fix this in master. If you need it in 9.0, there's a [module.](https://github.com/asphaltzipper/azi-odoo-modules/tree/master/mrp_llc)

**Comment by jco-odoo** [comment] 2016-06-13 14:57
@sle-odoo I know, would be good for master.

**Comment by mauroanelli2017** [comment] 2017-11-24 08:36
@anajuaristi 
i install yours modules but get errors in purchase delivery date.
es.
PRODUCT X is manufacture with bom , 30 days production time, made by A+B
both A and B are product buy and has supplier delivery date 30 days
if i start procurement plan from X's manufacturing order , date 15/11/2017
i get A delivery date on 15/10/2017
and B delivery date on 15/09/2017 and so on
instead it should be both on 15/10/2017 right?
where i'm doing wrong?

**Comment by anajuaristi** [comment] 2017-11-24 09:19
Our modules were developed for V8, I don't know how are they working on V9. 
But, It seems that one of the products you menction could have production time <> 30 and the other = 30, so the calculated data differs 30 days.

**Comment by mauroanelli2017** [comment] 2017-11-24 09:38
i install them in v8, 
the problem is that if i have 30 days supplier delivery for all materials, i aspect to have the same purchase order date, insted every materials go back from 30 days
so es A 30/10/2017
B 30/09/2017
C 30/08/2017
the right purchase delivery date must be all to 30/10/2017

**Comment by mauroanelli2017** [comment] 2017-11-27 10:14
I think the problem can be resolved by changing the date_planned field. at this time it takes the date when you press the scheduler's botton and then counts it. if instead considering the date of the father procurement everything would be ok.
@anajuaristi 
your modules work fine but i experience a bug in purchase order.
to recreate:
i make products A,B,C - buy - 30 days supplier delibery
D and E are manufacture 30 days production made like that
D=A+B , E=D+C. i lunch procurement plan on E manufacturing order and this is what i got:

![cattura](https://user-images.githubusercontent.com/29704450/33261724-13a75f2e-d364-11e7-9f22-c67b241bbb65.JPG)

as you can se A and B don't have the same purchase date, ami doing something wrong?

**Comment by jco-odoo** [comment] 2018-02-21 13:25
I will close this issue because the initial problem is not one: if you break the chain in logistics, it is logical not to propagate the dates.  That is why we have MTO.  Of course the idea of the right order in executing the orderpoints is still a good one, but not planned any time soon and nothing to do with the initial problem.

**Closed by jco-odoo** 2018-02-21 13:25 UTC
Labels: 9.0, Logistics
