### ISSUE TITLE
blockUI requires jQuery v1.2.3 or later!  You are using v1.11.1

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#17271] opened 2017-05-29 13:11 UTC
Impacted versions:
8.0 so far tested

Steps to reproduce:
- Fresh install Odoo from source in Debian 8 or Ubuntu 16.04
- Go to /web/database/manager

Current behavior:
Popup appears each time an action button is clicked or page reloaded, with the text: 
`blockUI requires jQuery v1.2.3 or later!  You are using v1.11.1`

Also an error in the console with: 
```
Uncaught TypeError: Cannot read property 'msie' of undefined
    at jquery.ba-bbq.js:9
    at jquery.ba-bbq.js:13
```
Expected behavior:
No error and the possibility to upload a database

**Comment by gustavovalverde** [comment] 2017-05-29 15:15
@odony @Yenthe666, this is halting Odoo installation. Any idea why this might be happening?

**Comment by Yenthe666** [comment] 2017-05-29 17:01
Hmm not sure. @mart-e do you have any idea? I believe upgrading the jQuery is a bit overkill and to dangerous for existing Odoo's?
Cc @JKE-be

**Comment by JKE-be** [comment] 2017-05-29 22:15
@yenthe666

No update required... just patch the check in bbq ... 11 is already > 2 :)

**Comment by JKE-be** [comment] 2017-05-30 16:29
hello

I cannot reproduce the error ! 
I suspect a problem of cache from your side.

We use jquery 1.8 in v8 and 1.11 in v9...

Because in anycase this check is wrong, we can remove it from jquery.blockUI file

Landed in 8.0

**Closed by JKE-be** 2017-05-30 16:29 UTC

**Comment by mart-e** [comment] 2017-05-31 07:09
Hello,

Yes, I have also found the issue when I am switching from 10 to 8 locally and so on. Refreshing the page usually removes the error so I assume it is indeed a cache problem (without investigating it further).

**Comment by gustavovalverde** [comment] 2017-05-31 22:56
Just so you know, in the end it was a Cloudflare thing, so no matter how much I cleaned cache, cookies or whatever on my side, it was still giving the error. Anyways, the Pull will help for this cases. Thank you @JKE-be
