### ISSUE TITLE
[9.0] 'current transaction is aborted, commands ignored until end of transaction block' error in PoS Session

### ISSUE THREAD

**Issue by SiviBu** [odoo/odoo#11071] opened 2016-02-23 14:10 UTC
Steps to reproduce this error:
1. Open PoS Session (Automatic Receipt Printing and Skip Receipt Screen should be disabled in PoS Config).
2. Create more than one (not empty) order on the same table.
3. Prepare to validate those orders (register payments and stay in Payment Screen).
4. Validate first order, second, third, ... and it must be done quickly (cashiers are working fast :) ).

Result:
1. Error popup shows with this: 'current transaction is aborted, commands ignored until end of transaction block'.
2. Orders are validated in the PoS session but only the first order is sent to the backend.

**Comment by pedrobaeza** [comment] 2018-04-17 23:40
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-04-17 23:40 UTC
Labels: 9.0, Point of Sale
