### ISSUE TITLE
Unknown error during import: <class 'openerp.exceptions.ValidationError'>: (u'Error ! You cannot use this attribute with the following value.', None) at row 2 Resolve other errors first

### ISSUE THREAD

**Issue by msmits2016** [odoo/odoo#13904] opened 2016-10-20 09:15 UTC
I have this error when i try to import more attributes on the products.
Every single product has one attribute and i want to import a second.

**Comment by JKE-be** [comment] 2016-10-20 10:26
Hello

Please use template when you post an issue.

You are probably using attributes values that are not corresponding to the attribute.

Probably an error in your import file and not an issue in Odoo.
If you can reproduce the problem with just a sample of data, post the files here...

**Comment by msmits2016** [comment] 2016-10-20 11:31
hello
the attributes wich i want to import are in my list with 'attribute values'.
if i input a attribute and attribute value on a product manual then i get the attribute values wich i want to import, so the attributes values are corresponding to the attribute (i think)

![image](https://cloud.githubusercontent.com/assets/22955259/19558195/82e82a54-96c9-11e6-9e14-6444d43e1ace.png)

**Comment by pedrobaeza** [comment] 2018-05-01 14:52
The problem seems to be on the import itself and not Odoo, so I close this.

**Closed by pedrobaeza** 2018-05-01 14:52 UTC
Labels: Need information
