### ISSUE TITLE
Bank Reconciliation based on wrong accuracy

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#4949] opened 2015-01-27 22:03 UTC
##### Version:
c22ed1390bcebc3ed5797de874a6c6eadc0cb760

##### Problem:
Bank Statement Reconcile is based on the currency's price rounding. In a country where bank statments are more exact than prices, statements cannot be reconciled, as the entry is templated in the price rounding style, so a 15.15 doesn't obviously reconcile with a rounded 15.

##### Rationale:
Bank statments should have their own accuracy. When adhering to account accuracy we would get in trouble when talking about foreign exchange bank accounts, which might follow a different pattern.

Generally it is an old topic, that accuracies must be more fine grained for many countries. Ceterum censero: The fear it might ge to complex is not warranted, as a paralleled structure is more transparent to the user (more configuration entries does NOT mean more complex, as long as it parallels business logic)

**Comment by Whisno** [comment] 2015-01-28 13:30
Hi,
Each reconciliation widget uses either the transaction's currency or the statement's currency (read `currency = statement_line.currency_id or st_line.journal_id.currency_id or st_line.journal_id.company_id.currency_id`).
This is the right behaviour as long as accounting entries need to be rounded to the currency's precision.
It's the first time I hear about banks issuing account statements with a greater precision than the currency's precision. So I need to understand : why would they do that and is there a legal basis ?

**Comment by blaggacao** [comment] 2015-01-29 00:39
I would guess of two reasons:
A) Historically, the countries currency had a .01 precision before it got skrewed up by inflation.
B) Interests are paid on a daily basis, so this might be a reason why for smaller ammount's a 0.01 precision matters (in terms of interests not beeing rounded to zero).

I think the question if it is because of a legal basis is not adequate here. I will instead answer the question if this is general business habit in our Country (Colombia): yes it is.

I think the "natural" home of such a configuration would be the bank account itself (as it might be different in other countries/currencies, but as we see not the same as price rounding).

The real pain starts when you have .01 on POS module which is just un-managable if a standard coffe costs about 7000 units.

Thanks for your kind consideration. Let me know if you need more context! I'll be happy to provide...

**Comment by Whisno** [comment] 2015-01-29 14:31
Ok, so the colombian peso's precision is two significants digits but people usually don't bother using them. So the currency has to be configured in Odoo with a rounding factor of 0.01 and the accuracy used in the reconciliation is correct. Therefore, I'll close the issue.

The solution could possibly be to create some kind of monetary widget that allows the user to choose the unit (eg. you can choose to input hundreds, units or cents). However we don't plan to develop this, so I can't help with that, sorry.

**Closed by Whisno** 2015-01-29 14:31 UTC

**Comment by blaggacao** [comment] 2015-01-30 05:26
Hi Arthur, please consider the following:
The currency accuracy is actually caled "price accuracy". Following your line of thought, you would have to change it to "(official) currency precision". This then would reveal a silent misunderstanding that would make double line of thought impossible. We could then all follow and **stick** to your line of thought, which makes indeed sense to me.

Remains the problem of "unofficial" currency rounding, I've come up with an untested idea, which is to present prices in a different currency ( "COP-UNOFICIAL" ) which has an exchange rate of 1 and is used for all publicly facing prices. 

If this sounds like a valid solution (and stricktly thinking in your model, we are able to be effectifely sepaking about tow different currencies - with two different behaviours and exchange rate of 1), this might go even as a hint below the currencies accuracy field, as i think this case is not that uncommon.

If you like some or all of my suggestions, consider reopening in order to be able to continue tracking about it. Thanks. :+1:

**Comment by Whisno** [comment] 2015-01-30 07:39
It sounds like a hack but it could definitively do the job (and be an excellent way to debug multi-currency behaviour)
I think that since the problem is all about the input method, the best solution would be to modify the client. In V9, all amounts of money will be displayed using the widget monetary. You could override this widget in l10n_co to allow selecting units.
We could possibly someday develop this usability feature but it's not currently in project.

**Comment by blaggacao** [comment] 2015-01-30 20:50
Sound's promising, havend dug into V9 so far, thanks for the pointer!!
