### ISSUE TITLE
Product Extra Image not updating without refreshing the page after save

### ISSUE THREAD

**Issue by zainulabideentt2020** [odoo/odoo#53074] opened 2020-06-16 13:56 UTC
Impacted versions: Odoo 13

Steps to reproduce:
1.Login
2.Go Products
3.Click on 
5.Go to E commerce tab
6.Add an image in Extra Product Media and save it.
7.Edit the image and click on save button

Expected result
Once after edited the image should be updated

Actual result
Once after edited the image is not updated https://prnt.sc/t0sy3z

**Comment by pedrobaeza** [comment] 2020-06-16 14:36
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos (video is the preferred one in this case).

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by zainulabideentt2020** [comment] 2020-06-16 15:12
> Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?
> 
> If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos (video is the preferred one in this case).
> 
> If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.
> 
> For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

vedio url : https://www.loom.com/share/41569dc8d565408b819eb9e79fbf35c1

**Comment by pedrobaeza** [comment] 2020-06-16 15:24
Is this reproduced in runbot or in your local?

**Comment by zainulabideentt2020** [comment] 2020-06-16 15:25
> Is this reproduced in runbot or in your local?

In my local

**Comment by pedrobaeza** [comment] 2020-06-16 15:36
Then you need to reproduce it on runbot, as several variables can affect:

- Outdated code
- Extra third-party modules
- Deployment

**Closed** 2023-04-07 14:29 UTC
Labels: Need information
