### ISSUE TITLE
error : click [more contacts] app and error

### ISSUE THREAD

**Issue by alexhmyang** [odoo/odoo#56387] opened 2020-08-24 11:33 UTC
Impacted versions: 13 community

Steps to reproduce:
 
Current behavior:

错误:

`Odoo Server Error

Traceback (most recent call last):
  File "/app/erp/odoo13/odoo/odoo/addons/base/models/ir_ui_view.py", line 664, in apply_inheritance_specs
    pre_locate=pre_locate)
  File "/app/erp/odoo13/odoo/odoo/tools/template_inheritance.py", line 230, in apply_inheritance_specs
    _("Element '%s' cannot be located in parent view") % tag
ValueError: 父视图中没有找到元素 '<tree string="更多联系人">' 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/erp/odoo13/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/app/erp/odoo13/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/app/erp/odoo13/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/app/erp/odoo13/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/app/erp/odoo13/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/app/erp/odoo13/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/app/erp/odoo13/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/app/erp/odoo13/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/app/erp/odoo13/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/app/erp/odoo13/odoo/addons/web/controllers/main.py", line 1322, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/app/erp/odoo13/odoo/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/app/erp/odoo13/odoo/odoo/api.py", line 383, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/app/erp/odoo13/odoo/odoo/api.py", line 356, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/app/erp/odoo13/odoo/odoo/models.py", line 1441, in load_views
    for [v_id, v_type] in views
  File "/app/erp/odoo13/odoo/odoo/models.py", line 1441, in <dictcomp>
    for [v_id, v_type] in views
  File "/app/erp/odoo13/odoo/addons/mail/models/mail_thread.py", line 410, in fields_view_get
    res = super(MailThread, self).fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/app/erp/odoo13/odoo/addons/web/models/models.py", line 206, in fields_view_get
    r = super().fields_view_get(view_id, view_type, toolbar, submenu)
  File "/app/erp/odoo13/odoo/odoo/models.py", line 1521, in fields_view_get
    result = self._fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/app/erp/odoo13/odoo/odoo/addons/base/models/res_partner.py", line 301, in _fields_view_get
    res = super(Partner, self)._fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/app/erp/odoo13/odoo/odoo/models.py", line 1483, in _fields_view_get
    root_view = View.browse(view_id).read_combined(['id', 'name', 'field_parent', 'type', 'model', 'arch'])
  File "/app/erp/odoo13/odoo/odoo/addons/base/models/ir_ui_view.py", line 738, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "/app/erp/odoo13/odoo/odoo/addons/base/models/ir_ui_view.py", line 687, in apply_view_inheritance
    source = self.apply_inheritance_specs(source, specs_tree, view_id)
  File "/app/erp/odoo13/odoo/odoo/addons/base/models/ir_ui_view.py", line 666, in apply_inheritance_specs
    self.raise_view_error(str(e), inherit_id)
  File "/app/erp/odoo13/odoo/odoo/addons/base/models/ir_ui_view.py", line 614, in raise_view_error
    raise ValueError(message)
ValueError: 父视图中没有找到元素 '<tree string="更多联系人">' 

错误的上下文:
视图 `res.partner.tree.form.inherit`
[view_id: 2608, xml_id: membership.view_partner_tree, model: res.partner, parent_id: 117]
`

Expected behavior:

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/10215059/91040338-a17f6e80-e640-11ea-9ef3-87fffd332920.png)

**Comment by pedrobaeza** [comment] 2020-08-24 11:34
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Closed** 2020-09-01 06:29 UTC
Labels: Need information

**Comment by Etren** [comment] 2021-09-08 12:29
> Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?
> 
> If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.
> 
> If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.
> 
> For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

I also encountered this problem when I installed the community edition for the first time!
After trying to install in English, this problem did not occur, but the problem occurred again after switching to Chinese. The problem still exists after the interface is restored to English.

**Comment by Yenthe666** [comment] 2021-09-08 14:58
Looks like yet another broken translation in the terms then :) You can fix those on https://www.transifex.com/odoo
