### ISSUE TITLE
[10.0] IMP: Wrong payment/exchange rate entry creation

### ISSUE THREAD

**Issue by sajadkk** [odoo/odoo#15987] opened 2017-03-22 07:28 UTC
Impacted versions: 10.0

**Steps to reproduce:**

Company Currency: EUR
Invoice Currency: USD

1) Create a Vendor Bill on 1/1/2017 for 100USD,  USD@5 
2) Make a partial payment of 50USD on 22/03/2017, USD@10

**Current behavior:**

Odoo create an exchange rate entry for remaining 50USD, and the invoice becomes payed

**Expected behavior:**

1) Odoo should create only the 50USD partial payment
2) should create the exchange gain/loss when the remaining 50USD is made

**Video/Screenshot link (optional):**
![screen](https://cloud.githubusercontent.com/assets/1268273/24186630/a4d9bea6-0ef2-11e7-9e37-9bf179be057d.png)

**Comment by pedrobaeza** [comment] 2018-05-22 08:04
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-05-22 08:04 UTC
Labels: 10.0, Accounting
