### ISSUE TITLE
9.0: crash when adding a line with a tax  to a sale.order (unhashable type: list)

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#10083] opened 2015-12-15 14:26 UTC
steps to reproduce

* connect on runbot 9.0, install only sales
* create a new product  called foobar, save
* create  a new sale order for Camptocamp. Add foobar to the 1st line. Check that the onchange added a 15%tax to the line
* Click on Save to save the sale order

You will get the following traceback:

```
Traceback (most recent call last):
  File "/home/odoo/runbot/extra/runbot/static/build/119703-9-0-b787c0/openerp/http.py", line 605, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/runbot/extra/runbot/static/build/119703-9-0-b787c0/openerp/http.py", line 642, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/runbot/extra/runbot/static/build/119703-9-0-b787c0/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/119703-9-0-b787c0/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/119703-9-0-b787c0/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/119703-9-0-b787c0/openerp/http.py", line 893, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/119703-9-0-b787c0/openerp/http.py", line 471, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/119703-9-0-b787c0/openerp/addons/web/controllers/main.py", line 907, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/119703-9-0-b787c0/openerp/addons/web/controllers/main.py", line 899, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/119703-9-0-b787c0/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/119703-9-0-b787c0/openerp/api.py", line 369, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/119703-9-0-b787c0/openerp/models.py", line 5985, in onchange
    record = self.new(values)
  File "/home/odoo/runbot/extra/runbot/static/build/119703-9-0-b787c0/openerp/api.py", line 236, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/119703-9-0-b787c0/openerp/models.py", line 5555, in new
    record._cache.update(record._convert_to_cache(values, update=True))
  File "/home/odoo/runbot/extra/runbot/static/build/119703-9-0-b787c0/openerp/models.py", line 5450, in _convert_to_cache
    for name, value in values.iteritems()
  File "/home/odoo/runbot/extra/runbot/static/build/119703-9-0-b787c0/openerp/models.py", line 5451, in <dictcomp>
    if name in fields
  File "/home/odoo/runbot/extra/runbot/static/build/119703-9-0-b787c0/openerp/fields.py", line 1743, in convert_to_cache
    ids = OrderedSet(command[2])
  File "/home/odoo/runbot/extra/runbot/static/build/119703-9-0-b787c0/openerp/tools/misc.py", line 1106, in __init__
    super(OrderedSet, self).__init__([(x, None) for x in seq])
  File "/usr/lib/python2.7/collections.py", line 52, in __init__
    self.__update(*args, **kwds)
  File "/usr/lib/python2.7/_abcoll.py", line 548, in update
    self[key] = value
  File "/usr/lib/python2.7/collections.py", line 58, in __setitem__
    if key not in self:
TypeError: unhashable type: 'list'
```

You can get this by adding any product from the demo data, and manually adding a tax to the sale order line.

**Comment by gurneyalex** [comment] 2015-12-15 14:28
OPW opened.

**Comment by gurneyalex** [comment] 2015-12-15 15:27
I reproduce on both enterprise and community.

**Comment by gurneyalex** [comment] 2015-12-15 15:29
after the crash the product is created and the SO too. 

But adding the same product in any SO will generate the same crash --> it looks like the product is not correctly configured.

**Comment by gurneyalex** [comment] 2015-12-15 15:33
Nope I can reproduce with a product created from the product creation form:

1. create product foobar with default values from Sales -> Product
2. create sale order for camptocamp, add foobar
3. save -> crash.

**Comment by lepistone** [comment] 2015-12-15 15:47
:suspect:

**Comment by lukebranch** [comment] 2015-12-15 15:48
@gurneyalex ,

I can confirm i've had this as well as a host of other TypeError, ProgrammingError and KeyError tracebacks with the latest commit of 9.0 on a clean Ubuntu 14.04 VPS.
```
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 70, in wrap
    return f(*args, **kwargs)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 1483, in index
    file_name = reports.read(res_id[0], ['name'], context)['name']
  File "/opt/odoo/odoo-server/openerp/http.py", line 998, in proxy
    result = meth(cr, request.uid, *args, **kw)
  File "/opt/odoo/odoo-server/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/custom/Aeroo/report_aeroo/report_xml.py", line 458, in read
    res = super(report_xml, self).read(cr, user, ids, fields, context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 3175, in read
    result = BaseModel.read(records, fields, load=load)
  File "/opt/odoo/odoo-server/openerp/api.py", line 236, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 3210, in read
    self._read_from_database(stored, inherited)
  File "/opt/odoo/odoo-server/openerp/api.py", line 236, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 3348, in _read_from_database
    cr.execute(query_str, params)
  File "/opt/odoo/odoo-server/openerp/sql_db.py", line 139, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/sql_db.py", line 215, in execute
    res = self._obj.execute(query, params)
  File "/usr/lib/python2.7/dist-packages/psycopg2/extensions.py", line 129, in getquoted
    pobjs = [adapt(o) for o in self._seq]
ProgrammingError: can't adapt type 'ir.actions.report.xml'
```

**Comment by gurneyalex** [comment] 2015-12-15 15:52
@lukebranch you should report a separate issue for this with the proper steps to reproduce.

**Comment by lukebranch** [comment] 2015-12-15 15:53
@gurneyalex ,

I'll create a separate issue with proper steps to reproduce now, thanks.

**Comment by gurneyalex** [comment] 2015-12-15 15:56
Same issue as #10069 #10055

**Comment by odony** [comment] 2015-12-15 16:37
I suggest we close this issue as a duplicate of #10055, which contains more information, and confirm the latter, if you don't mind. The OPW ticket will be handled accordingly.

**Closed by odony** 2015-12-15 16:37 UTC

**Comment by joolsr** [comment] 2015-12-16 10:46
Thanks for the quick fix.
