### ISSUE TITLE
TypeError: edit_custom() missing 1 required positional argument: 'custom_id'

### ISSUE THREAD

**Issue by lwdsw** [odoo/odoo#46495] opened 2020-02-28 07:20 UTC
Impacted versions:  
13.0

Steps to reproduce:
create new module depends on board and install it, when i click 'Change Layout' and choose a layout

Current behavior:
TypeError: edit_custom() missing 1 required positional argument: 'custom_id'

Expected behavior:
im not sure  if this is a BUG

Video/Screenshot link (optional):
![图片](https://user-images.githubusercontent.com/45808789/75519192-a53d8a00-5a3d-11ea-9fe1-1296a787fa65.png)

**Comment by pedrobaeza** [comment] 2020-02-28 07:21
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2020-02-28 07:21 UTC

**Comment by lwdsw** [comment] 2020-02-28 07:46
got it ,thanks

**Comment by PierreAlainKouakou** [comment] 2023-01-05 16:14
Follow the steps below to fix this bug:
1    Create a js file in the static folder of your custom module
2    Override the _saveDashboard method

The code looks like this:

/** @odoo-module **/

import BoardView from 'board.BoardView';
import core from 'web.core';
import dataManager from 'web.data_manager';

var QWeb = core.qweb;

BoardView.prototype.config.Controller.include({
custom_events: _.extend({}, BoardView.prototype.config.Controller.prototype.custom_events, {
save_dashboard: '_saveDashboard',
}),

/**
* Actually save a dashboard
* @override
*
* @returns {Promise}
*/
_saveDashboard: function () {
var board = this.renderer.getBoard();
var arch = QWeb.render('DashBoard.xml', _.extend({}, board));
return this._rpc({
route: '/web/view/edit_custom',
params: {
custom_id: this.customViewID ? this.customViewID : "",
arch: arch,
}
}).then(dataManager.invalidate.bind(dataManager));
},
});

Odoo 15.0
It helps you I hope !

**Comment by SheltonMuianga** [comment] 2023-08-14 05:52
Hi guys, i am having the same error but in odoo 16.0, can someone's helps me?

**Comment by burkeallen** [comment] 2023-09-01 15:59
yes, experiencing the same issue in Odoo 16, i disagree this is a custom code issue, as you can reproduce the issue with a hello world dashboard definition like below. 

`        <record id="dashboard_hello_world" model="ir.ui.view">
            <field name="name">My Dashbaord</field>
            <field name="model">board.board</field>
            <field name="type">form</field>
            <field name="arch" type="xml">
                <board style="1-1">
                    <column>
                        <h1> my test board </h1>
                    <column>  
`
the team over at odoo mates has a workaround for this issue, that involves modifying the base code. (https://www.youtube.com/watch?v=kfffu4Uzo10&t=1094s)

hopefully this will make it into an upcoming update.
