### ISSUE TITLE
[9.0] [ Payroll ] Traceback when we create employee payslip

### ISSUE THREAD

**Issue by jar-odoo** [odoo/odoo#9444] opened 2015-11-06 09:05 UTC
Steps to generate a traceback.

Step 1 : Create a new contract for employee payslip or use existing employee contract in payslip.
Step 2 : Create a new Employee payslip.
Step 3 : Select that Employee which have a contract.

see the image to getting better idea

https://drive.google.com/file/d/0B_QdPkKVSAqOaElFYmVSamJDcFU/view?usp=sharing

**Comment by ajaychauhan727** [comment] 2015-11-06 09:45
This issue is duplicate of #8238.

**Comment by jni-odoo** [comment] 2015-11-06 09:48
if its already there then please close it...

**Closed** 2015-11-06 10:22 UTC
