### ISSUE TITLE
[9.0] "500 Internal Server Error" after eCommerce modul installation

### ISSUE THREAD

**Issue by satriani-vai** [odoo/odoo#9711] opened 2015-11-24 11:07 UTC
```
2015-11-24 11:03:46,577 92618 ERROR odoo_9 openerp.addons.website.models.ir_http: 500 Internal Server Error:

Traceback (most recent call last):
  File "/usr/local/odoo_9/addons/website/models/ir_http.py", line 242, in _handle_exception
    response = super(ir_http, self)._handle_exception(exception)
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_http.py", line 147, in _handle_exception
    return request._handle_exception(exception)
  File "/usr/local/odoo_9/openerp/http.py", line 737, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_http.py", line 172, in _dispatch
    result = request.dispatch()
  File "/usr/local/odoo_9/openerp/http.py", line 768, in dispatch
    r = self._call_function(**self.params)
  File "/usr/local/odoo_9/openerp/http.py", line 315, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/local/odoo_9/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/local/odoo_9/openerp/http.py", line 311, in checked_call
    result.flatten()
  File "/usr/local/odoo_9/openerp/http.py", line 1367, in flatten
    self.response.append(self.render())
  File "/usr/local/odoo_9/openerp/http.py", line 1360, in render
    context=request.context)
  File "/usr/local/odoo_9/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/odoo_9/addons/website/models/ir_ui_view.py", line 141, in render
    return super(view, self).render(cr, uid, id_or_xml_id, values=values, engine=engine, context=context)
  File "/usr/local/odoo_9/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/odoo_9/addons/web_editor/models/ir_ui_view.py", line 29, in render
    return super(view, self).render(cr, uid, id_or_xml_id, values=values, engine=engine, context=context)
  File "/usr/local/odoo_9/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_ui_view.py", line 1065, in render
    return self.pool[engine].render(cr, uid, id_or_xml_id, qcontext, loader=loader, context=context)
  File "/usr/local/odoo_9/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 253, in render
    return self.render_node(element, qwebcontext, generated_attributes=qwebcontext.pop('generated_attributes', ''))
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 296, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 458, in render_tag_call
    res = self.render(cr, uid, template, d)
  File "/usr/local/odoo_9/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 253, in render
    return self.render_node(element, qwebcontext, generated_attributes=qwebcontext.pop('generated_attributes', ''))
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 296, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 296, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 296, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 476, in render_tag_call_assets
    bundle = AssetsBundle(xmlid, cr=cr, uid=uid, context=context, registry=self.pool)
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 1123, in __init__
    self.html = self.registry['ir.ui.view'].render(self.cr, self.uid, xmlid, context=context)
  File "/usr/local/odoo_9/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/odoo_9/addons/website/models/ir_ui_view.py", line 141, in render
    return super(view, self).render(cr, uid, id_or_xml_id, values=values, engine=engine, context=context)
  File "/usr/local/odoo_9/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/odoo_9/addons/web_editor/models/ir_ui_view.py", line 29, in render
    return super(view, self).render(cr, uid, id_or_xml_id, values=values, engine=engine, context=context)
  File "/usr/local/odoo_9/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_ui_view.py", line 1065, in render
    return self.pool[engine].render(cr, uid, id_or_xml_id, qcontext, loader=loader, context=context)
  File "/usr/local/odoo_9/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 253, in render
    return self.render_node(element, qwebcontext, generated_attributes=qwebcontext.pop('generated_attributes', ''))
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 296, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 458, in render_tag_call
    res = self.render(cr, uid, template, d)
  File "/usr/local/odoo_9/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 251, in render
    element = self.get_template(id_or_xml_id, qwebcontext)
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 173, in get_template
    raise_qweb_exception(QWebTemplateNotFound, message="Loader could not find template %r" % name, template=origin_template)
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 171, in get_template
    document = qwebcontext.loader(name)
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_ui_view.py", line 1063, in loader
    return self.read_template(cr, uid, name, context=context)
  File "/usr/local/odoo_9/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_ui_view.py", line 937, in read_template
    view_id = self.get_view_id(cr, uid, xml_id, context=context)
  File "/usr/local/odoo_9/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in get_view_id
  File "/usr/local/odoo_9/openerp/tools/cache.py", line 85, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/usr/local/odoo_9/addons/website/models/ir_ui_view.py", line 109, in get_view_id
    raise ValueError('View %r in website %r not found' % (xml_id, context['website_id']))
QWebTemplateNotFound: View 'web.jqueryui_conflict' in website 1 not found

2015-11-24 11:03:47,094 92618 INFO odoo_9 werkzeug: 85.182.59.9 - - [24/Nov/2015 11:03:47] "GET /shop HTTP/1.1" 500 -
2015-11-24 11:03:47,116 92618 ERROR odoo_9 werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/odoo_9/openerp/service/server.py", line 245, in app
    return self.app(e, s)
  File "/usr/local/odoo_9/openerp/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/usr/local/odoo_9/openerp/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/usr/local/odoo_9/openerp/http.py", line 1416, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/local/odoo_9/openerp/http.py", line 1390, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python2.7/site-packages/werkzeug/wsgi.py", line 588, in __call__
    return self.app(environ, start_response)
  File "/usr/local/odoo_9/openerp/http.py", line 1580, in dispatch
    result = ir_http._dispatch()
  File "/usr/local/odoo_9/addons/website_sale/models/ir_http.py", line 12, in _dispatch
    return super(IrHttp, self)._dispatch()
  File "/usr/local/odoo_9/addons/utm/models/ir_http.py", line 13, in _dispatch
    response = super(ir_http, self)._dispatch()
  File "/usr/local/odoo_9/addons/website/models/ir_http.py", line 190, in _dispatch
    resp = super(ir_http, self)._dispatch()
  File "/usr/local/odoo_9/addons/web_editor/models/ir_http.py", line 16, in _dispatch
    return super(ir_http, self)._dispatch()
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_http.py", line 176, in _dispatch
    return self._handle_exception(e)
  File "/usr/local/odoo_9/addons/website/models/ir_http.py", line 295, in _handle_exception
    html = request.website._render('website.http_error', values)
  File "/usr/local/odoo_9/openerp/api.py", line 230, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/local/odoo_9/openerp/api.py", line 547, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/usr/local/odoo_9/addons/website/models/website.py", line 409, in _render
    return self.pool['ir.ui.view'].render(cr, uid, template, values=values, context=context)
  File "/usr/local/odoo_9/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/odoo_9/addons/website/models/ir_ui_view.py", line 141, in render
    return super(view, self).render(cr, uid, id_or_xml_id, values=values, engine=engine, context=context)
  File "/usr/local/odoo_9/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/odoo_9/addons/web_editor/models/ir_ui_view.py", line 29, in render
    return super(view, self).render(cr, uid, id_or_xml_id, values=values, engine=engine, context=context)
  File "/usr/local/odoo_9/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_ui_view.py", line 1065, in render
    return self.pool[engine].render(cr, uid, id_or_xml_id, qcontext, loader=loader, context=context)
  File "/usr/local/odoo_9/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 253, in render
    return self.render_node(element, qwebcontext, generated_attributes=qwebcontext.pop('generated_attributes', ''))
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 296, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 458, in render_tag_call
    res = self.render(cr, uid, template, d)
  File "/usr/local/odoo_9/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 253, in render
    return self.render_node(element, qwebcontext, generated_attributes=qwebcontext.pop('generated_attributes', ''))
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 296, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 296, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 296, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 476, in render_tag_call_assets
    bundle = AssetsBundle(xmlid, cr=cr, uid=uid, context=context, registry=self.pool)
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 1123, in __init__
    self.html = self.registry['ir.ui.view'].render(self.cr, self.uid, xmlid, context=context)
  File "/usr/local/odoo_9/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/odoo_9/addons/website/models/ir_ui_view.py", line 141, in render
    return super(view, self).render(cr, uid, id_or_xml_id, values=values, engine=engine, context=context)
  File "/usr/local/odoo_9/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/odoo_9/addons/web_editor/models/ir_ui_view.py", line 29, in render
    return super(view, self).render(cr, uid, id_or_xml_id, values=values, engine=engine, context=context)
  File "/usr/local/odoo_9/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_ui_view.py", line 1065, in render
    return self.pool[engine].render(cr, uid, id_or_xml_id, qcontext, loader=loader, context=context)
  File "/usr/local/odoo_9/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 253, in render
    return self.render_node(element, qwebcontext, generated_attributes=qwebcontext.pop('generated_attributes', ''))
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 296, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 458, in render_tag_call
    res = self.render(cr, uid, template, d)
  File "/usr/local/odoo_9/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 251, in render
    element = self.get_template(id_or_xml_id, qwebcontext)
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 173, in get_template
    raise_qweb_exception(QWebTemplateNotFound, message="Loader could not find template %r" % name, template=origin_template)
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 171, in get_template
    document = qwebcontext.loader(name)
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_ui_view.py", line 1063, in loader
    return self.read_template(cr, uid, name, context=context)
  File "/usr/local/odoo_9/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/odoo_9/openerp/addons/base/ir/ir_ui_view.py", line 937, in read_template
    view_id = self.get_view_id(cr, uid, xml_id, context=context)
  File "/usr/local/odoo_9/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in get_view_id
    
  File "/usr/local/odoo_9/openerp/tools/cache.py", line 85, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/usr/local/odoo_9/addons/website/models/ir_ui_view.py", line 109, in get_view_id
    raise ValueError('View %r in website %r not found' % (xml_id, context['website_id']))
QWebTemplateNotFound: View 'web.jqueryui_conflict' in website 1 not found
```

**Comment by antonylesuisse** [comment] 2015-11-25 12:25
jqueryui_conflict does not exists in odoo, the problem is probably due to an addon.

**Comment by satriani-vai** [comment] 2015-11-26 11:18
Apparently crm module causes this isuue.

**Comment by sle-odoo** [comment] 2016-06-07 14:51
Closing as i cannot reproduce this issue anymore, it has probably been fixed in the meantime.
Regards

**Comment by treviser** [comment] 2016-06-16 14:44
@sle-odoo  It can be reproduced when you install the module CRM before you have installed the website builder/e-commerce. Workaround after you have installed the website builder: uninstall CRM and install it again.

**Comment by treviser** [comment] 2016-06-27 10:02
@antonylesuisse @sle-odoo It happened again after I have installed an additional module. I can't access my website again, this is urgent.

**Comment by treviser** [comment] 2016-06-27 12:35
website_booking_calendar is the culprit in my case. Sorry for the hassle.

**Closed** 2016-06-27 16:21 UTC

**Comment by bolsystem** [comment] 2016-08-10 02:20
Hola, Gracias por su valiosa aporte. Tenia ese problema .Luego desintale el modulo de comercio electrónico y todo marcho perfecto..
Gracias a todos...!!

**Comment by treviser** [comment] 2016-08-10 03:37
Du muesch öis de traceback vom Odoo log schicke, süsch cha Dier niemert hälfe. Schliesslich hend mier kei Zauberchugle um i Dis Syschtem chönne ine z'luege.

twanda AG
Ermin Trevisan
Artherstrasse 19
6318 Walchwil

Tel. 041 758 1515
Mobil 079 208 7373
Email trevi@twanda.com
www.twanda.ch
