### ISSUE TITLE
invoice sender mail sender wrong

### ISSUE THREAD

**Issue by pab691** [odoo/odoo#32839] opened 2019-04-19 13:03 UTC
Impacted versions:
12
Steps to reproduce: 

Change invoice sender in the mail template and send invoice.
It is still send with the user email

Current behavior: invoice Email sender doesnt use the template setting

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2019-04-19 13:07
This is not something of Odoo, but on your email server that doesn't allow mail relay (to put other sender on the mail header) in the email configuration you have put.

Closing as no Odoo issue.

**Closed by pedrobaeza** 2019-04-19 13:07 UTC

**Comment by pab691** [comment] 2019-04-19 13:13
No...
On the same server it is working on odoo 11.. (sender template adress in used instead of user adress)
And it is also working in V12 for order sent...

**Comment by pedrobaeza** [comment] 2019-04-19 13:16
Well, this hasn't changed and it's working in my side, so unless you'll be more specific, this is still consider invalid.

**Comment by pab691** [comment] 2019-04-19 13:25
It cannot be an email server issue because with the same email server and Odoo V11 we have no problem and the template sender email is used .
We have installed a new fresh version of odoo12 and the issue persist.
So it is strange that this could work with you in a standard odoo 12 installation

**Comment by pab691** [comment] 2019-04-19 13:57
check and reopen this issue please

**Comment by pedrobaeza** [comment] 2019-04-19 14:59
As said, you must provide more information about the problem, because as is, it's not an issue.

**Comment by pab691** [comment] 2019-04-19 15:04
I dont see what i can say more ! The problem and the issue are described.
Ok forget it, we will try to resolve the problem by ourself but if you treat each issue like that, oddo will never be a mature product...

**Comment by pedrobaeza** [comment] 2019-04-19 15:23
It's not a question of software maturity, but searching deep enough in the problem and not throwing things without that. I have already told you that I'm not experimenting that problem in 12.0, so something is different in your side than in mine. Maybe it's a problem of Odoo, but under certain circumstances, which you are not talking about.

**Comment by Yenthe666** [comment] 2019-04-19 16:18
@pab691 please give us a reproducable case so that we can test and simulate it. This means that you're able to reproduce it on a default Odoo at runbot.odoo.com. We're happy to reopen it if you can give us the steps needed to reproduce the issue. 
As my colleague said, without this we cannot help you. We really need more details.
