### ISSUE TITLE
Make2Order and Make2Stock not compatible

### ISSUE THREAD

**Issue by ybofr** [odoo/odoo#6769] opened 2015-05-19 13:53 UTC
This was tested on runbot 19th May 2015
How to get the mistake
1. Create a product with route buy and call for bid set
2. Create a reordering rule for the product
3. Create a sales order for the product with route make2order
4. Run the scheduler
What happened?
The system created 2 procurements: one procurement for the customer and one procurement for the make2order. The procurement for the customer already has created a call for bid.
When run, the scheduler proposes another purchase based on mini/maxi rules only and not considering that one of the requirement was basically already considered in a call for bid.

What should happen?
The system should not consider any requirement that already has a call for bid on it. 

Thanks for a correction

**Comment by falinwa** [comment] 2015-05-20 03:59
I confirm this is a bug,
when in sale order the user choose the make to order, the system must not create another procurement for make to stock.

**Comment by anajuaristi** [comment] 2015-08-11 21:20
Tested the mentioned case I'm not sure it is a bug. Let me explain a little bit 

Following the mentioned steps 
1. Create a product with route buy and call for bid set
2. Create a reordering rule for the product
3. Create a sales order for the product with route make2order
At this point, the system will create a BID for the product including the mentioned quantities on SO. So it's right

4. Run the scheduler
Conceptually the people who is running the scheduler or the stock minimun rule calculation should be sure that there is no open bids nor draft purchase orders. Otherwise it's imposible the system by default takes in account products included in other draft documents.
if you see the way it's programmed the needed quantity for a product depends on product virtual stock when running scheduler. On the other side 
.- To confirm sale order will decrease virtual stock
.- To confirm purchase order will increase virtual stock
Meantime, even if you create as many bids, draft purchase orders or draft sale orders, product virtual stock will not change so...if you run schedulers at this point, system will calculate same quantity if you mantain or you erase all draft orders containing your product. 

Anyway I found this small improvements:
1. If a procurement is related to a bid, It's not set done until you manually close the bid, but... the bid status is not depending on received products but it's totally manual. Very easy to forget to change.
2. When a purchase order is confirmed from a bid, it's not assigned to procurement. I'm not sure if it should be or not since the procurement workflow is depending on bid status but maybe it would be also an usability improvement to assing confirmed purchase order from bid to procurement and making it done when purchse order goods are received, even if bid is not manually set to done.

Sorry if I don't agree with both (@ybofr, @falinwa) but I think standar proccess is working properly. Anyway, I would really want to know other people opinion since procurement area is really critical concept. 
@pedrobaeza @jbeficent 

Thank you!!
Ana

**Comment by pedrobaeza** [comment] 2015-08-11 22:23
I also think that the process is correct with the set rules. Adding a new layer to check the in-progress bids will make more difficult to debug problems and the possible side effects will increase. It's up to the person responsible of running this to check some things.

**Comment by ybofr** [comment] 2015-08-12 10:33
Hi Ana,

The process is perfectly working if you set the route in the product. BUT, the problem is coming when you decide that you can either supply to order OR supply to stock.

In that case, you will NOT set the route on the product, you will set the route on the sales order. 
	1. route = buy: a procurement is created stock to customer.
	2. route = make2order: a procurement created for the stock to customer and a procurement is created supplier to stock
		In the second case, the procurement supplier to stock will have a call for bid linked to it, automatically.
	3. When you run the scheduler, the system is checking all the procurements from stock and is creating a call for bid for all of them. This way, I procure the quantity twice.

This is the issue.

Regards
Eva P.

**Comment by anajuaristi** [comment] 2015-08-12 10:44
@ybofr 
This is not like this: When you run the scheduler, the system is checking all the procurements from stock and is creating a call for bid for all of them. This way, I procure the quantity twice.

The system is ONLY checking the virtual stock of the product, it's not checking any existing procurement.
Try the same but just not having any draft bid or purchase and it is working properly. This is... just create the MTO purchase and confirm and only after that execute run schedulers and you will see that it's right.

The problem is not it's calculating 2 times but, if you have got draft documents they are not taking in account because they dont increase or decrease product virtual quantities. 

Maybe it looks very extrange behavior but it's the same on other ERPs when you have to erase or cancel all draft documents before launching calculation or even proccess itself is cancelling before starting to calculate. 
For me there is no error on it.

**Comment by ybofr** [comment] 2015-08-12 10:53
@Ana,

This is not the same on other ERP. The system is not calculating properly. He is only considering the actual stock and not all the purchases that are coming. The system should always make a calculation considering what is already purchased, even in draft, otherwise it is impossible to manage. You may have different people working on purchasing and some are at the level of draft and the system does not care about what they are doing. This is from a conceptional point of you incorrect.

Regards
Eva p.

**Comment by pedrobaeza** [comment] 2015-08-12 10:57
> He is only considering the actual stock and not all the purchases that are coming

@ybofr, that's not true. Scheduler consider virtual stock, not actual stock. The problem is that a bid is not yet considered as virtual stock until one of its purchase order is confirmed. Maybe that's what we have to add: consider the quantities of a bid as virtual incoming, and neutralize it when a purchase order coming from this bid is confirmed.

**Comment by anajuaristi** [comment] 2015-08-12 11:02
@pedrobaeza you are right

@ybofr it's because of that (and also because it's not considering any date) we built the module stock_planning. On our module it's considering draft purchase orders, procurements and so on + the dates where material should come.

But for standard, simple way I think it's correct like it is and even trying to include an improvement as @pedrobaeza proposed, There will be still a lack of functionality and would be too complex to control all possibilities. So... I vote to let it like it is now but if you decide to program the proposed improvement  (consider the quantities of a bid as virtual incoming, and neutralize it when a purchase order coming from this bid is confirmed.) it will also be right. We could try it.

**Comment by ybofr** [comment] 2015-08-12 11:18
Thanks.

I will propose the change to our CTO. It should pretty much correct all the issues we have with procurement.

You are the best

Eva P.

**Comment by ana** [comment] 2015-08-12 11:22
@ybofr  please use @anajuaristi  and not @ana. If not, you'll be highlighting the wrong person (me).

**Closed** 2017-12-14 12:15 UTC
Labels: Logistics
