### ISSUE TITLE
[12.0][BUG][auth_ldap] LDAP First login problem

### ISSUE THREAD

**Issue by sinandurgut07** [odoo/odoo#44154] opened 2020-01-29 06:44 UTC
I install 'auth_ldap' and 'auth_oauth' modules. After i **first** login with ldap getting error like bottom. Then i delete ldap user from 'res.users' and uninstall 'auth_oauth' module. The problem gone. But it's not about 'auth_oauth' module. Before that whenever i overload 'web_login' method and some search or something with orm this is happening. 
```
2020-01-29 06:08:06,347 29609 INFO odootest odoo.addons.base.models.res_users: Login failed for db:odootest login:sinan.durgut@nymailtest121.com from 127.0.0.1 
2020-01-29 06:08:06,595 29609 INFO odootest werkzeug: 127.0.0.1 - - [29/Jan/2020 06:08:06] "POST /web/login HTTP/1.1" 500 - 171 0.081 0.190
2020-01-29 06:08:06,599 29609 ERROR odootest werkzeug: Error on request:
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/home/user/.local/lib/python3.6/site-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/home/user/Projects/custom_addons/odoo_lib/odoo/service/server.py", line 409, in app
    return self.app(e, s)
  File "/home/user/Projects/custom_addons/odoo_lib/odoo/service/wsgi_server.py", line 128, in application
    return application_unproxied(environ, start_response)
  File "/home/user/Projects/custom_addons/odoo_lib/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/home/user/Projects/custom_addons/odoo_lib/odoo/http.py", line 1320, in __call__
    return self.dispatch(environ, start_response)
  File "/home/user/Projects/custom_addons/odoo_lib/odoo/http.py", line 1293, in __call__
    return self.app(environ, start_wrapped)
  File "/home/user/.local/lib/python3.6/site-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/home/user/Projects/custom_addons/odoo_lib/odoo/http.py", line 1488, in dispatch
    result = ir_http._dispatch()
  File "/home/user/Projects/custom_addons/odoo_lib/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "/home/user/Projects/custom_addons/odoo_lib/addons/web_editor/models/ir_http.py", line 22, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/home/user/Projects/custom_addons/odoo_lib/odoo/addons/base/models/ir_http.py", line 207, in _dispatch
    return cls._handle_exception(e)
  File "/home/user/Projects/custom_addons/odoo_lib/odoo/addons/base/models/ir_http.py", line 177, in _handle_exception
    return request._handle_exception(exception)
  File "/home/user/Projects/custom_addons/odoo_lib/odoo/http.py", line 776, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/home/user/Projects/custom_addons/odoo_lib/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/user/Projects/custom_addons/odoo_lib/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/user/Projects/custom_addons/odoo_lib/odoo/addons/base/models/ir_http.py", line 203, in _dispatch
    result = request.dispatch()
  File "/home/user/Projects/custom_addons/odoo_lib/odoo/http.py", line 835, in dispatch
    r = self._call_function(**self.params)
  File "/home/user/Projects/custom_addons/odoo_lib/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/user/Projects/custom_addons/odoo_lib/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/user/Projects/custom_addons/odoo_lib/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/user/Projects/custom_addons/odoo_lib/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/home/user/Projects/custom_addons/odoo_lib/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/home/user/Projects/custom_addons/odoo_lib/addons/auth_oauth/controllers/main.py", line 94, in web_login
    response = super(OAuthLogin, self).web_login(*args, **kw)
  File "/home/user/Projects/custom_addons/odoo_lib/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/home/user/Projects/custom_addons/odoo_lib/addons/auth_signup/controllers/main.py", line 21, in web_login
    response = super(AuthSignupHome, self).web_login(*args, **kw)
  File "/home/user/Projects/custom_addons/odoo_lib/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/home/user/Projects/custom_addons/odoo_lib/addons/web/controllers/main.py", line 491, in web_login
    uid = request.session.authenticate(request.session.db, request.params['login'], request.params['password'])
  File "/home/user/Projects/custom_addons/odoo_lib/odoo/http.py", line 1052, in authenticate
    if uid: self.get_context()
  File "/home/user/Projects/custom_addons/odoo_lib/odoo/http.py", line 1092, in get_context
    self.context = request.env['res.users'].context_get() or {}
  File "<decorator-gen-88>", line 2, in context_get
    
  File "/home/user/Projects/custom_addons/odoo_lib/odoo/tools/cache.py", line 93, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/user/Projects/custom_addons/odoo_lib/odoo/addons/base/models/res_users.py", line 569, in context_get
    values = user.read(list(name_to_key), load=False)[0]
IndexError: list index out of range - - -
```

I checked the 'auth_ldap' module code. I found something with db cursor. The ldap user create process working with different cursor. I thing whenever overload or add something to progress. Code not working first login. 'res.user' created but on main db curser cannot find it.  
```
    @classmethod
    def _login(cls, db, login, password):
        try:
            return super(Users, cls)._login(db, login, password)
        except AccessDenied as e:
            with registry(db).cursor() as cr:
                cr.execute("SELECT id FROM res_users WHERE lower(login)=%s", (login,))
                res = cr.fetchone()
                if res:
                    raise e

                env = api.Environment(cr, SUPERUSER_ID, {})
                Ldap = env['res.company.ldap']
                for conf in Ldap._get_ldap_dicts():
                    entry = Ldap._authenticate(conf, login, password)
                    if entry:
                        return Ldap._get_or_create_user(conf, login, entry)
                raise e
```
```
Ldap = env['res.company.ldap']
****************************************
Ldap = request.env['res.company.ldap']
```
I change the code like above  add 'request.' then problem fixed but i think this is not  the right way. What do you suggest me to ?
@odony 
@Yenthe666

**Comment by mayjo79** [comment] 2020-02-07 16:22
I encounter a similar error when in a certain context, after creating a new database, Odoo authenticates with the default user :
https://translate.google.com/translate?u=https://agipme.fr/2020/02/odoo-12-ce-erreur-database-creation-error-list-index-out-of-range.html&&hl=fr&ie=UTF-8&sl=fr&tl=en

**Comment by Yenthe666** [comment] 2020-02-07 16:28
I believe this is a duplicate of https://github.com/odoo/odoo/issues/41060

**Comment by sinandurgut07** [comment] 2020-02-07 16:39
> I believe this is a duplicate of #41060

Yeap, That's same problem.

**Comment by pedrobaeza** [comment] 2020-04-01 17:58
Closing this as duplicated.

**Closed by pedrobaeza** 2020-04-01 17:58 UTC
