### ISSUE TITLE
Label Issue in product

### ISSUE THREAD

**Issue by KCITSindia** [odoo/odoo#10263] opened 2016-01-01 12:37 UTC
When i print product label at that time it will not print product label

http://www.awesomescreenshot.com/image/874792/12c1f17e9f738a3b4abceca7257157e7

http://www.awesomescreenshot.com/image/874791/1fa19752f7b0e0682679ca357e1fe084

http://www.awesomescreenshot.com/image/874795/13f96d9b1abe0e73f1e2abedba8ad127

[output.pdf](https://github.com/odoo/odoo/files/75896/output.pdf)
![products ipad retina display product variants a2323 ipad retina display 16 gb white 2 4 ghz odoo](https://cloud.githubusercontent.com/assets/15699740/12070836/3c925e6a-b0b2-11e5-94dd-94eff8a97a41.png)
![products ipad retina display product variants odoo](https://cloud.githubusercontent.com/assets/15699740/12070837/3f6e626e-b0b2-11e5-914f-79b0461cf8e0.png)
![desctop screenshot](https://cloud.githubusercontent.com/assets/15699740/12070840/6d69d9aa-b0b2-11e5-88f3-e5efeeaab8ba.png)

**Comment by jeffery9** [comment] 2016-01-02 04:42
you should install barcode fonts for report_lab

**Comment by Yenthe666** [comment] 2016-06-15 10:02
Hi @KCITSindia,

As @jeffery9 stated you're missing the barcode fonts on your system.
When you install the Python package report_lab it'll be fixed.
Closing this since it is not a bug / issue but because the implementation is not correctly done.

**Closed by Yenthe666** 2016-06-15 10:02 UTC
