### ISSUE TITLE
[Odoo 10] Expense move wrong reconciled 

### ISSUE THREAD

**Issue by elperrofarelo** [odoo/odoo#14571] opened 2016-12-02 13:47 UTC
Impacted versions:
10
Steps to reproduce:
Employee claim for more than one expense.
submit for approval
manager prove it
accountant register the payment

Current behavior:
Problem 1: The expense report only shows one move (account_move_id) for one expense, not for all of them.
Problem 2: The Journal entry is only reconciled with one move.  

Expected behavior:

Video/Screenshot link (optional):

**Comment by elperrofarelo** [comment] 2016-12-05 08:58
I see that the problem is being solved in the new versions.

**Comment by elperrofarelo** [comment] 2016-12-05 09:43
The Problem 2 is still there: The Journal entry is only reconciled with one move ((account_move_id)) not with all of them

**Comment by pedrobaeza** [comment] 2018-05-03 23:54
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-05-03 23:54 UTC
Labels: 10.0, Accounting
