### ISSUE TITLE
[9.0] Installation of MRP App results in a 'bad_query' error

### ISSUE THREAD

**Issue by pjmcdermott** [odoo/odoo#11037] opened 2016-02-21 11:49 UTC
Impacted versions: Odoo Server 9.0c-20160220

Steps to reproduce:
1. Clean install of Odoo Server 9.0c
2. Set log_level = warn
3. Install CRM app
4. Install Inventory Management app
5. Install MP app

Current behavior:
Error message in log during installation:

> Odoo Server 9.0c-20160220:larkfield:INFO:openerp.sql_db:bad query: UPDATE "ir_actions_todo" SET "state"='done',"write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (1)

**NB** This is marked as an 'INFO' message despite the log level being set to 'warn'. Yet it appears to be a warning or an error

Expected behavior:
No error messages in the log

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2018-04-12 19:41
Hi, I'm not able to reproduce this problem in latest version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there.

**Closed by pedrobaeza** 2018-04-12 19:41 UTC
Labels: 9.0
