### ISSUE TITLE
Move Operation Type before Source Location on Inventory Transfer form

### ISSUE THREAD

**Issue by pawa2007** [odoo/odoo#35000] opened 2019-07-19 04:09 UTC
Impacted versions:
12.0

Steps to reproduce:
1. Go to `Inventory > Configuration > Settings` and enable `Multi-Warehouses`
2. Go to `Inventory > Operations > Transfers` and click `Create`

You will get a form that looks like this.
![image](https://user-images.githubusercontent.com/21964536/61508248-ad910980-aa06-11e9-9926-793cafe06d4c.png)

Current behavior:
The `Source Location` and `Destinaton Location` fields are dependent on the `Operation Type` field i.e. when you select the `Operation Type` the values for `Source Location` and `Destination Location` are populated based on the default values set up for the selected Operation Type.

Expected behavior:
From a usability perspective, it will be better if the `Operation Type` is displayed before `Source Location` so that the user can select the Operation Type and then change the Source and Destination Locations, if required.

Video/Screenshot link (optional):
Screenshot posted above.

**Comment by pedrobaeza** [comment] 2019-07-19 07:23
Thanks for the suggestion, and for sure @lap-odoo will take note of this, but this change is not possible in stable, as it's not a bugfix.

@lap-odoo can you tell us if in master this can be/is switched?

**Comment by lap-odoo** [comment] 2019-07-19 08:34
@pawa2007 @pedrobaeza It will be fixed in V13, thanks for the feedback.

**Comment by Yenthe666** [comment] 2019-07-20 10:48
Hmm as it'll be fixed in V13 I guess we can close this one off?

**Closed** 2019-07-20 13:06 UTC
Labels: 12.0, Logistics
