### ISSUE TITLE
JS Error: Date field from wizard used for search default

### ISSUE THREAD

**Issue by psyonara** [odoo/odoo#30293] opened 2019-01-17 08:05 UTC
Impacted versions:
12 (only checked this version)

Steps to reproduce:
* Create a wizard (model and form) with a date field
* Add a button to the wizard that returns an action to load a list view
* Add field "blah" to search view that is used in the list view
* Provide "context" for action, setting "search_default_blah" to date field value

Current behavior:
JS error when clicking on wizard button:
```
Error:
TypeError: facetValue.get(...) is undefined

http://localhost/web/content/508-220ac79/web.assets_backend.js:953
Traceback:
value_from@http://localhost/web/content/508-220ac79/web.assets_backend.js:953:356
value_to_domain@http://localhost/web/content/508-220ac79/web.assets_backend.js:944:170
_.collect@http://localhost/web/content/501-a11114a/web.assets_common.js:13:270
Collection.prototype[method]@http://localhost/web/content/508-220ac79/web.assets_backend.js:68:535
get_domain@http://localhost/web/content/508-220ac79/web.assets_backend.js:945:13
build_search_data/<@http://localhost/web/content/508-220ac79/web.assets_backend.js:893:275
_.forEach@http://localhost/web/content/501-a11114a/web.assets_common.js:12:558
Collection.prototype[method]@http://localhost/web/content/508-220ac79/web.assets_backend.js:68:535
build_search_data@http://localhost/web/content/508-220ac79/web.assets_backend.js:893:203
_executeWindowAction/</def<@http://localhost/web/content/508-220ac79/web.assets_backend.js:502:116
then/</</<@http://localhost/web/content/501-a11114a/web.assets_common.js:802:678
fire@http://localhost/web/content/501-a11114a/web.assets_common.js:796:281
add@http://localhost/web/content/501-a11114a/web.assets_common.js:797:467
then/</<@http://localhost/web/content/501-a11114a/web.assets_common.js:802:649
each@http://localhost/web/content/501-a11114a/web.assets_common.js:625:758
then/<@http://localhost/web/content/501-a11114a/web.assets_common.js:802:553
Deferred@http://localhost/web/content/501-a11114a/web.assets_common.js:803:189
then@http://localhost/web/content/501-a11114a/web.assets_common.js:802:518
_executeWindowAction/<@http://localhost/web/content/508-220ac79/web.assets_backend.js:502:75
then/</</<@http://localhost/web/content/501-a11114a/web.assets_common.js:802:678
fire@http://localhost/web/content/501-a11114a/web.assets_common.js:796:281
fireWith@http://localhost/web/content/501-a11114a/web.assets_common.js:801:198
Deferred/</deferred[tuple[0]]@http://localhost/web/content/501-a11114a/web.assets_common.js:803:56
then/</</<@http://localhost/web/content/501-a11114a/web.assets_common.js:802:678
fire@http://localhost/web/content/501-a11114a/web.assets_common.js:796:281
fireWith@http://localhost/web/content/501-a11114a/web.assets_common.js:801:198
Deferred/</deferred[tuple[0]]@http://localhost/web/content/501-a11114a/web.assets_common.js:803:56
then/</</<@http://localhost/web/content/501-a11114a/web.assets_common.js:802:678
fire@http://localhost/web/content/501-a11114a/web.assets_common.js:796:281
fireWith@http://localhost/web/content/501-a11114a/web.assets_common.js:801:198
then/</</<@http://localhost/web/content/501-a11114a/web.assets_common.js:802:874
fire@http://localhost/web/content/501-a11114a/web.assets_common.js:796:281
fireWith@http://localhost/web/content/501-a11114a/web.assets_common.js:801:198
Deferred/</deferred[tuple[0]]@http://localhost/web/content/501-a11114a/web.assets_common.js:803:56
genericJsonRpc/<@http://localhost/web/content/501-a11114a/web.assets_common.js:3556:1
then/</</<@http://localhost/web/content/501-a11114a/web.assets_common.js:802:678
fire@http://localhost/web/content/501-a11114a/web.assets_common.js:796:281
fireWith@http://localhost/web/content/501-a11114a/web.assets_common.js:801:198
then/</</<@http://localhost/web/content/501-a11114a/web.assets_common.js:802:874
fire@http://localhost/web/content/501-a11114a/web.assets_common.js:796:281
fireWith@http://localhost/web/content/501-a11114a/web.assets_common.js:801:198
done@http://localhost/web/content/501-a11114a/web.assets_common.js:1192:86
callback@http://localhost/web/content/501-a11114a/web.assets_common.js:1212:15
```
From what I can tell, it has something to do with the interaction with the Moment library. The "facet" dict usually contains the keys "label" and "value", but for a date field it is expecting "valueAsMoment" (search_input.js:350). This key does not exist, leading me to believe that somewhere it is not successfully managing to parse the selected date (which is in ISO format: YYYY-MM-DD) into a Moment object (or it is not trying at all). The "complete" function below "value_from" for the DateField in search_input.js seems to be the place where this Moment object is being created, but as far as I could tell, this code doesn't get run. This might be the problem, I don't know.

Expected behavior:
Specified date is used as a default for the date field when rendering the view.

Video/Screenshot link (optional):
![wizard_form](https://user-images.githubusercontent.com/771840/51303792-1fc86780-1a3f-11e9-99b8-6462e4c41e77.png)

![wizard_error](https://user-images.githubusercontent.com/771840/51303805-248d1b80-1a3f-11e9-8ae8-581fa5a38766.png)

**Comment by pedrobaeza** [comment] 2019-01-17 08:20
Can you provide the minimum module for reproducing the error? Have you tried with latest Odoo version?

**Comment by psyonara** [comment] 2019-01-17 09:23
I am not aware of any module that uses this specific setup, I came across it while developing a custom module.
This was on the latest version available on Github (branch 12.0).

**Comment by pedrobaeza** [comment] 2019-01-17 14:49
The problem is in the custom date format you have configured/entered, which is incorrect. Please fix that in your custom code.

Closing as no valid.

**Closed by pedrobaeza** 2019-01-17 14:49 UTC

**Comment by sswapnesh** [comment] 2019-01-17 17:03
Maybe related to https://github.com/odoo/odoo/issues/29551
