### ISSUE TITLE
Warehouse selectable routes - use is not possible

### ISSUE THREAD

**Issue by zbik2607** [odoo/odoo#4758] opened 2015-01-17 11:04 UTC
In Route definitions view it is possible to check field warehouse_selectable, but in Warehouse form 
it is not possible to add the route. In the form view of stock.warehouse field route_ids not exists.

**Comment by jco-odoo** [comment] 2015-01-19 13:29
It is not difficult to add it to the view and there is also a Routes button.  We thought not to add it because it would mostly be done through the wizard.

**Comment by zbik2607** [comment] 2015-01-19 13:46
Hmm, I understand. Can therefore add the configuration parameter for advanced users and separate page with separate access rights? Without it, create your own routes always requires customizations.

**Comment by guewen** [comment] 2015-01-30 10:19
@jco-odoo The Routes button opens routes but if we create a new one, it is not linked to the warehouse, that's sounds like a bug.

**Comment by jco-odoo** [comment] 2015-01-30 10:28
Honestly the Routes button on the warehouse is a little bit ambiguous
because it also shows other routes than those that are assigned to the
warehouse, so linking it by default to the warehouse somehow might just
lead to more confusion.  If you want this functionality, the best thing is
still to add the field route_ids to the warehouse view, which we might do,
but it should be for the advanced user somehow.

On Fri, Jan 30, 2015 at 11:20 AM, Guewen Baconnier <notifications@github.com

**Comment by guewen** [comment] 2015-01-30 11:52
> Honestly the Routes button on the warehouse is a little bit ambiguous because it also shows other routes than those that are assigned to the warehouse, so linking it by default to the warehouse somehow might just lead to more confusion. If you want this functionality, the best thing is still to add the field route_ids to the warehouse view, which we might do, but it should be for the advanced user somehow.

I agree

**Comment by Yenthe666** [comment] 2017-12-13 12:14
Hi @zbik2607,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Closed by Yenthe666** 2017-12-13 12:14 UTC
Labels: Logistics
