### ISSUE TITLE
Proxy Server Error after clicking on "Pay Now" button

### ISSUE THREAD

**Issue by kmlew** [odoo/odoo#11318] opened 2016-03-14 08:32 UTC
Impacted versions: 
9

Steps to reproduce:
- Select "Wire Transfer" as a Payment Method for a purchase in the Shop
- Click the "Pay Now" button

Current behavior:
502 Proxy Error generated.

Expected behavior:
Bank transfer information provided

Video/Screenshot link (optional):

<img width="579" alt="screen shot 2016-03-14 at 15 30 24" src="https://cloud.githubusercontent.com/assets/17688618/13738768/c33a9254-e9f9-11e5-9a0d-d75d255839a6.png">

**Comment by pedrobaeza** [comment] 2018-04-17 23:49
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-04-17 23:49 UTC
Labels: 9.0
