### ISSUE TITLE
xml parse error

### ISSUE THREAD

**Issue by Hojalab** [odoo/odoo#12152] opened 2016-05-24 12:40 UTC
I2016-05-24 12:30:51,314 13000 ERROR data openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home//odoo/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/openerp/http.py", line 680, in dispatch
    result = self._call_function(**self.params)
  File "/home//odoo/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/openerp/http.py", line 959, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/openerp/http.py", line 509, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/addons/web/controllers/main.py", line 616, in load
    return Client(request.httprequest.app, BaseResponse).get(path, base_url=base_url).data
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/test.py", line 762, in get
    return self.open(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/test.py", line 736, in open
    response = self.run_wsgi_app(environ, buffered=buffered)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/test.py", line 659, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/test.py", line 855, in run_wsgi_app
    app_iter = app(environ, start_response)
  File "/home/odoo/openerp/http.py", line 1488, in __call__
    return self.dispatch(environ, start_response)
  File "/home/odoo/openerp/http.py", line 1462, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 588, in __call__
    return self.app(environ, start_response)
  File "/home/odoo/openerp/http.py", line 1655, in dispatch
    result = _dispatch_nodb()
  File "/home/odoo/openerp/http.py", line 1628, in _dispatch_nodb
    result = request.dispatch()
  File "/home/odoo/openerp/http.py", line 840, in dispatch
    r = self._call_function(**self.params)
  File "/home/odoo/openerp/http.py", line 317, in _call_function
    return self.endpoint(*args, **kwargs)
  File "/home/odoo/openerp/http.py", line 959, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/openerp/http.py", line 509, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/addons/web/controllers/main.py", line 530, in qweb
    content, checksum = concat_xml(files)
  File "/home/odoo/addons/web/controllers/main.py", line 205, in concat_xml
    xml = ElementTree.parse(fp).getroot()
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1183, in parse
    tree.parse(source, parser)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1643, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1507, in _raiseerror
    raise err

**Comment by Yenthe666** [comment] 2016-05-25 06:27
Hi @Hojalab,

In order to find / fix a bug like this we need more details. How does it happen, how can we trigger it? Next time also post the full stack trace please, this is just a part of the log.
I'm closing this since we have no way of reproducing this or finding out what you did, sorry.

Regards,
Yenthe

**Closed by Yenthe666** 2016-05-25 06:27 UTC

**Comment by Hojalab** [comment] 2016-05-25 13:05
Thanks I Solved It

**Comment by hhxjzyr** [comment] 2017-05-18 02:41
please tell me how you solved it, I met the same question
