### ISSUE TITLE
Date issue in calendar

### ISSUE THREAD

**Issue by lakshman12345** [odoo/odoo#10239] opened 2015-12-30 10:41 UTC
In calendar of sales after dec 31 2015 it is showing jan 2015.

**Comment by Yenthe666** [comment] 2018-07-25 10:09
Hi there,

This no longer seems to be the case/reproducable so I'm closing it off.
Don't hesitate to respond if you can still reproduce it!

Regards,
Yenthe

**Closed by Yenthe666** 2018-07-25 10:09 UTC
