### ISSUE TITLE
[12] Odoo Studio Icon missing

### ISSUE THREAD

**Issue by technicomp** [odoo/odoo#27421] opened 2018-10-04 09:15 UTC
Impacted versions: 12

Steps to reproduce: install Odoo Studio (Enterprise / Windows / German)

Current behavior: Odoo Studio Icon missing

Video/Screenshot link (optional):

![studiojpg](https://user-images.githubusercontent.com/24723923/46464470-b9d50e80-c7c6-11e8-9ef1-9d88a8d2dd5c.JPG)

**Comment by sswapnesh** [comment] 2018-10-04 17:47
Are you sure this screenshot belong to Enterprise version ? (It will show enterprise even if you are on Odoo community as mentioned in #27403 )
Enterprise Screenshot Looks like: 
![666](https://user-images.githubusercontent.com/16624719/46492523-6d6fea00-c82b-11e8-8065-35c91b87a5c1.png)

**Comment by alexkuhn** [comment] 2018-10-04 19:33
Hello,

I could not reproduce this issue on Odoo Enterprise 12.0 with German language.
Note that when there is an issue in showing the Studio icon, it displays the text "Odoo Studio-Symbol" in German. This may occur with very slow internet connection.

Please let us know if you still have this issue, and when it occurs (everytime? sometimes? etc.)

**Comment by Yenthe666** [comment] 2018-10-05 10:14
Hi there,

I was not able to reproduce it either.
Can you please try it again on the latest V12 runbot? If you can reproduce it can you please add steps on how to reproduce it exactly?
I'm closing this one as three people couldn't simulate it.

Regards,
Yenthe

**Closed by Yenthe666** 2018-10-05 10:14 UTC
