### ISSUE TITLE
Bug When opening 2 cursor for two different database

### ISSUE THREAD

**Issue by MohamedAmineOuali** [odoo/odoo#66891] opened 2021-02-26 06:16 UTC
Impacted versions:
odoo 14 
Steps to reproduce:

```
    with registry("database1").cursor() as cr1:
        env1 = api.Environment(cr1, SUPERUSER_ID, self._context)
        env1["model1"].write(.......)
        with registry("database2").cursor() as cr2:  # model1 doesn't exist in the second databse
            env2 = api.Environment(cr2, SUPERUSER_ID, self._context)
            env2["model2"].write(.......)
```
Current behavior:

When we finish with database2 and the system tries to commit it does a flush(). This is where the error is produced in fact. When we change the user record in the first commit the changes are stored in memory exactly in an object called `towrite`. When the system does a commit for cr2 it tries to flush all results from `towrite` including the changes of model1 which does not exist in the second database. this produce an error because the system tries to look for the record in env2

api.py file
```
class Environments(object):
    """ A common object for all environments in a request. """
    def __init__(self):
        self.envs = WeakSet()                   # weak set of environments
        self.cache = Cache()                    # cache for all records
        self.protected = StackMap()             # fields to protect {field: ids, ...}
        self.tocompute = defaultdict(set)       # recomputations {field: ids}
        # updates {model: {id: {field: value}}}
        self.towrite = defaultdict(lambda: defaultdict(dict))
```

model.py file
```
        if fnames is None:
            # flush everything
            self.recompute()
            while self.env.all.towrite:
                model_name, id_vals = self.env.all.towrite.popitem()
                process(self.env[model_name], id_vals)
```

The `towrite` object is shared between all envs. However when we try to flush everything we use one env to do flush `self.env` which leads to an exception if the model doesn't exist in that envirment.

 
Expected behavior:

`towrite` object should not be shared by all env or we should have `towrite` per database

Btw why did you chose to use  `env.all.towrite`  instead of `env.towrite` 

For anyone facing the same problem, I think you can fixe it temporarily by doing flush each time you change something in a different database

Example:

- change in database1
- flush
- change in database2
- change in database2
- change in database2
- flush
-  change in database1 
- flush
- commit database2 
- commit database1 

I  think this is not a recommended approach because each time you do a flush odoo send the request to the database server

**Comment by pedrobaeza** [comment] 2021-02-26 09:30
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2021-02-26 09:30 UTC

**Comment by MohamedAmineOuali** [comment] 2021-02-26 18:58
Hi,

With all my respect. This is the second time I report a bug in **standard odoo code** and it gets closed. With all modesty, I already fixed my problem using monkey patching so I don't really need a solution.  

I have put all the details that help identify the bug. I don't really understand what do you mean by not using extra addons.  The bug is in the odoo core code. You have an object `towrite` which is shared by all environments this should not be the case.

**I am not looking for a solution I am reporting a bug.**

If you want to produce the error without extra addons. Create a **server action** using the **odoo user interface** and put the code that I provided. You can for example put it in **automated action**

**Comment by pedrobaeza** [comment] 2021-02-26 19:00
The problem is that you are doing operations that you shouldn't. Opening cursors and committing by yourself is the recipe to the failure, and that's not something that should be covered in Odoo. The Odoo ORM framework doesn't include any commit for you to do it. And it's not an "advanced use". It's an irregular use that very rarely times it should be done and under very certain conditions.

**Comment by MohamedAmineOuali** [comment] 2021-02-27 04:38
You have several addons which aren't considered basic addons and yet you are doing a manual commit. There are multiple cases where a manual commit is needed.

> Here is the very simple rule:
> You should NEVER call cr.commit() yourself, UNLESS you have created your own database cursor explicitly! And the situations where you need to do that are exceptional!
> 
> And by the way if you did create your own cursor, then you need to handle error cases and proper rollback, as well as properly close the cursor when you’re done with it.

This is a quote from the [odoo documentation](https://www.odoo.com/documentation/14.0/reference/guidelines.html) it says that we can do a manual commit if we create our own database cursor. What is the purpose of putting this in the documentation if it doesn't work as it is supposed to be?

**Even if the situations when doing a manual commit are exceptional this doesn't mean that we should ignore the bugs produced by them.**
