### ISSUE TITLE
POS Invoice Validate Error

### ISSUE THREAD

**Issue by asiamatrix** [odoo/odoo#31687] opened 2019-03-08 03:52 UTC
Impacted versions: Odoo 12 Enterprise Version

I facing error when i click validate button in POS screen.

Odoo Server Error
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\api.py", line 1039, in get
    value = self._data[key][field][record.id]
KeyError: 615

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\fields.py", line 963, in __get__
    value = record.env.cache.get(record, self)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\api.py", line 1041, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('res.partner(615,).property_account_receivable_id', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "c:\program files (x86)\odoo 12.0e\server\odoo\addons\web\controllers\main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "c:\program files (x86)\odoo 12.0e\server\odoo\addons\web\controllers\main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\api.py", line 745, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\api.py", line 718, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "c:\odoo-12.0+e.20181210\addons\wk_pos_partial_payment\models\pos_order.py", line 25, in create_from_ui
    order_ids = return_data = super(PosOrder, self).create_from_ui(orders)
  File "c:\program files (x86)\odoo 12.0e\server\odoo\addons\point_of_sale\models\pos_order.py", line 750, in create_from_ui
    pos_order.action_pos_order_invoice()
  File "c:\program files (x86)\odoo 12.0e\server\odoo\addons\point_of_sale\models\pos_order.py", line 681, in action_pos_order_invoice
    invoice = Invoice.new(order._prepare_invoice())
  File "c:\odoo-12.0+e.20181210\addons\xdbx_template\models\sale_order.py", line 40, in _prepare_invoice
    res = super(PosOder, self)._prepare_invoice()
  File "c:\program files (x86)\odoo 12.0e\server\odoo\addons\point_of_sale\models\pos_order.py", line 174, in _prepare_invoice
    'account_id': self.partner_id.property_account_receivable_id.id,
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\fields.py", line 967, in __get__
    self.determine_value(record)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\fields.py", line 1078, in determine_value
    self.compute_value(recs)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\fields.py", line 1034, in compute_value
    self._compute_value(records)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\fields.py", line 1027, in _compute_value
    self.compute(records)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\fields.py", line 647, in _compute_company_dependent
    values = Property.get_multi(self.name, self.model_name, records.ids)
  File "c:\program files (x86)\odoo 12.0e\server\odoo\addons\base\models\ir_property.py", line 268, in get_multi
    cr.execute(query, params + [sub_refs])
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.InternalError: current transaction is aborted, commands ignored until end of transaction block

<img width="894" alt="screenhunter 858" src="https://user-images.githubusercontent.com/44358604/54006543-14b2cd80-418c-11e9-8196-d65e7845f01c.png">

**Comment by pedrobaeza** [comment] 2019-03-08 08:29
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Yenthe666** [comment] 2019-04-09 06:10
Hi there,

As we haven't recieved any feedback in over a month we're closing off this issue.
Don't hesitate to comment back with more information and details if you can still reproduce it on an official test instance.

Regards,
Yenthe

**Closed by Yenthe666** 2019-04-09 06:10 UTC
Labels: Need information

**Comment by asiamatrix** [comment] 2019-04-09 06:11
Hello,

Good Day To You!

Thank you for your email. 
We will contact you back as soon as possible.

MAY SUCCESS BE WITH YOUR BUSINESS...
Best Regards,

Ko Kyaw Zin Oo
Founder & Managing Director
ASIA MATRIX COMPANY LIMITED
+959783355903, +959768064691
http://www.asiamatrixsoftware.com
