### ISSUE TITLE
Cannot print PDF reports with the correct wkhtmltopdf version

### ISSUE THREAD

**Issue by mokerosan** [odoo/odoo#27600] opened 2018-10-10 00:00 UTC
Impacted versions: odoo12

Steps to reproduce: print anything in odoo 12

Current behavior: The error pops up: Wkhtmltopdf failed (error code: -8). Message: b''. The truth is that I do not know why send this error because I have installed version 11 and it works without problems.

Expected behavior: I should get the pdf file to download..

Video/Screenshot link (optional): 
![captura de pantalla de 2018-10-09 20-57-25](https://user-images.githubusercontent.com/31668345/46710171-2b74e880-cc1d-11e8-89c7-3338d7d4662b.png)

**Comment by sswapnesh** [comment] 2018-10-10 03:41
Duplicate of https://github.com/odoo/odoo/issues/27487

**Comment by Yenthe666** [comment] 2018-10-10 06:05
Yeah, closing off as it is a duplicate. You can follow the responses and feedback on https://github.com/odoo/odoo/issues/27487

**Closed by Yenthe666** 2018-10-10 06:05 UTC
