### ISSUE TITLE
[12.0] [Master]Procurement Group can not propagation after mrp production order

### ISSUE THREAD

**Issue by Bonainifo** [odoo/odoo#36297] opened 2019-08-30 23:26 UTC
Impacted versions:
In 11.0 Sale order can propagation group_id to purchase order to tracking order. But in 12.0, MO will creat a new MO procurement_group_id instead of origin group_id of sale order. What is the purpose of this design? 
Steps to reproduce:
1、Computer bom include mainboard. Mainboard include material01
2、Using replnish to order route for all products
3、Creat sale order for computer and confirm so00001
4、In WH/MO/00001 for computer, orign is so00001,but Procurement Group is creat a new value usiing mo name WH/MO/00001. 
5、So all procurement group of any opeartion oders is WH/MO/00001.
6、In 11.0 and 10.0, all procurement group is so00001 until is was broken by procurement rules.
Current behavior:
12.0 & Master
![图片](https://user-images.githubusercontent.com/46485742/64057446-7732d680-cbcf-11e9-852b-e034802fce08.png)
![图片](https://user-images.githubusercontent.com/46485742/64057469-b95c1800-cbcf-11e9-88a6-4fab910720e2.png)

Expected behavior:
11.0
![图片](https://user-images.githubusercontent.com/46485742/64058081-54f18680-cbd8-11e9-963d-44f1b5adda03.png)
![图片](https://user-images.githubusercontent.com/46485742/64058087-6f2b6480-cbd8-11e9-890f-4c698df62a21.png)

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2019-08-30 23:29
Why are you mixing in your description purchases in v11 with manufacturing orders in v12?

**Comment by Bonainifo** [comment] 2019-08-30 23:37
Thank you for your reply. I just description the function is work normal but different in 12.0. Now we can tracking sale order to purchase order. The reason is MO break the propagation of prcurement group

**Comment by pedrobaeza** [comment] 2019-08-30 23:40
Yes, but it's not the same flow on MTO from sales to purchase than from sales to MO. The procurement group was the same on that flow in v11?

**Comment by Bonainifo** [comment] 2019-08-31 00:34
Yes，it was. So we can tracking sale order to purchase order by setup propagation of procurement group to propagation for buy route




------------------ 原始邮件 ------------------
发件人: "Pedro M. Baeza"<notifications@github.com>;
发送时间: 2019年8月31日(星期六) 上午7:41
收件人: "odoo/odoo"<odoo@noreply.github.com>;
抄送: "每人都有一个回不去的家乡"<124358678@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [odoo/odoo] [12.0] Procurement Group can not propagation aftermrp production order (#36297)




Yes, but it's not the same flow on MTO from sales to purchase than from sales to MO. The procurement group was the same on that flow in v11?

**Comment by pedrobaeza** [comment] 2019-08-31 00:37
Again, you are mixing sales to purchase with sales to mrp.

**Comment by Bonainifo** [comment] 2019-08-31 00:44
In manufacture company, tracking sales order not only from sale to mo. We need using one sale order number to trackiing sale order for all operation in whole company include all mo、picking order、purchase order.  Just like the last flow in Version 11.0 & 10.0

**Comment by Bonainifo** [comment] 2019-08-31 00:48
And，sale to purchase often include sale to mo & mo to purchase

**Comment by pedrobaeza** [comment] 2019-08-31 00:48
Sorry, but I'm still not understanding you, probably by the language. Any way, you must provide all the steps to reproduce the problem, or this issue won't qualify for being fixed.

**Comment by Bonainifo** [comment] 2019-08-31 01:37
I have update the description now

**Comment by pedrobaeza** [comment] 2019-08-31 07:40
OK, read the steps to reproduce, but this doesn't mean any problem. OK, procurement group is different, but what is the problem on that? Is any standard business flow broken? Are MTO SO not serve when the MO is finished?

**Comment by Bonainifo** [comment] 2019-08-31 09:27
OK，Soory！I didn't say that this is a problem, I just want to know what the business purpose of this design change is. Behind every design, there must be goals he wants to achieve, and I have not found any relevant instructions.

**Comment by pedrobaeza** [comment] 2019-08-31 09:39
But that kind of questions must be done on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Closed by pedrobaeza** 2019-08-31 09:39 UTC
Labels: Need information
