### ISSUE TITLE
Uncaught Error: Widget type 'html' is not implemented

### ISSUE THREAD

**Issue by ndemoreau** [odoo/odoo#19216] opened 2017-09-02 15:32 UTC
Impacted versions: 10.0e. This is a re-open of issue #11627 which is closed while a number of people like me are still impacted. This is a main issue, thanks for solving it!

Steps to reproduce:
Impossible to open an app, or to create a new SO

Current behavior:

Error message window.

http://localhost:8070/web/content/865-2c72e2f/web.assets_backend.js:2200
Traceback:
Error: Widget type 'html' is not implemented
    at http://localhost:8070/web/content/865-2c72e2f/web.assets_backend.js:2200:104
    at Function._.each._.forEach (http://localhost:8070/web/content/766-f880028/web.assets_common.js:12:558)
    at Class.render_to (http://localhost:8070/web/content/865-2c72e2f/web.assets_backend.js:2199:1798)
    at Class.start (http://localhost:8070/web/content/865-2c72e2f/web.assets_backend.js:2135:283)
    at Class.prototype.(anonymous function) [as start] (http://localhost:8070/web/content/766-f880028/web.assets_common.js:3010:559)
    at http://localhost:8070/web/content/766-f880028/web.assets_common.js:3113:963
    at http://localhost:8070/web/content/766-f880028/web.assets_common.js:547:681
    at fire (http://localhost:8070/web/content/766-f880028/web.assets_common.js:541:299)
    at Object.add [as done] (http://localhost:8070/web/content/766-f880028/web.assets_common.js:542:467)
    at Array.<anonymous> (http://localhost:8070/web/content/766-f880028/web.assets_common.js:547:649)

The origin of the problem is the fact that some modules don't load in the browser. This is what i see in Chrome's browser console:

warning: Some modules could not be started
Missing dependencies: ["web_editor.summernote"]
Non loaded modules: (15) ["web_editor.editor", "web_editor.rte", "web_editor.rte.summernote", "web_editor.widget", "web_editor.snippet.editor", "web_editor.snippets.options", "web_editor.tour", "web_editor.transcoder", "web_editor.translate", "website.editor", "website.translator", "website.contentMenu", "website.snippets.editor", "website.rte.summernote", "website.snippets.editor.gallery"]
Debug: {web_editor.editor: {…}, web_editor.rte: {…}, web_editor.rte.summernote: {…}, web_editor.widget: {…}, web_editor.snippet.editor: {…}, …}

When I go to developer mode with assets, the modules load correctly and I get rid of this issue.

This problem starts without any specific reason. It happened to me with two different instances, quite suddenly.

Thanks for your help!

**Comment by Yenthe666** [comment] 2017-09-02 15:49
Hi @ndemoreau,

Thanks for the report.
As it is a duplicate of https://github.com/odoo/odoo/issues/11627 I decided to reopen the other issue and close this one. This'll keep the whole history on the same report.

Regards,
Yenthe

**Closed by Yenthe666** 2017-09-02 15:49 UTC

**Comment by ndemoreau** [comment] 2017-09-02 16:54
ok, thanks
