### ISSUE TITLE
Password cannot contain only digits when using Json RPC

### ISSUE THREAD

**Issue by litnimax** [odoo/odoo#49435] opened 2020-04-11 03:31 UTC
Impacted versions: 12.0 / 13.0

Steps to reproduce: Just try to authenticate with password 123

Current behavior: Gives an error.

Expected behavior: Allow or deny.

```
2020-04-11 03:18:47,844 891 ERROR asterisk_12.0 odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 811, in authenticate
    request.session.authenticate(db, login, password)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1041, in authenticate
    uid = odoo.registry(db)['res.users'].authenticate(db, login, password, env)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/res_users.py", line 627, in authenticate
    uid = cls._login(db, login, password)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/res_users.py", line 606, in _login
    user._check_credentials(password)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/res_users.py", line 318, in _check_credentials
    .verify_and_update(password, hashed)
  File "/usr/lib/python3/dist-packages/passlib/context.py", line 2568, in verify_and_update
    if not record.verify(secret, hash, **clean_kwds):
  File "/usr/lib/python3/dist-packages/passlib/utils/handlers.py", line 748, in verify
    validate_secret(secret)
  File "/usr/lib/python3/dist-packages/passlib/utils/handlers.py", line 122, in validate_secret
    raise exc.ExpectedStringError(secret, "secret")
TypeError: secret must be unicode or bytes, not int
```

**Comment by pedrobaeza** [comment] 2020-04-11 10:13
I'm not able to reproduce it on runbot. It seems you have something different in your local.

**Comment by pedrobaeza** [comment] 2020-05-08 19:45
No answer, so closing.

**Closed by pedrobaeza** 2020-05-08 19:45 UTC
Labels: Need information
