### ISSUE TITLE
Many2many domain is failing in Odoo 10.0.20180219

### ISSUE THREAD

**Issue by rockcesar** [odoo/odoo#23156] opened 2018-02-19 14:53 UTC
Impacted versions: 10.0.20180219

Steps to reproduce:

    * Create two fields with a domain in partner_id:

    partner_ids = fields.Many2many('res.partner', 'custom_model_res_partner_rel', 'custom_model_id', 'res_partner_id', string="Partner IDS")
    partner_id = fields.Many2one('res.partner', string='Partner', domain="[('id', 'in', partner_ids and partner_ids[0] and partner_ids[0][2] or False)]", required=True)

    * And display in the view:

    <field name="partner_ids"/>
    <field name="partner_id" widget="selection"/>

Current behavior:

    * partner_ids is retrieving a dictionary in view side (an object):
    [('id', 'in', partner_ids and partner_ids[0] and partner_ids[0][2] or False)]

    {'name': 'Me', 'vat': '098123'}

    * and if it is many records, it returns:

    [{'name': 'Me', 'vat': '098123'}, {'name': 'Me_1', 'vat': '098123_1'}]

Expected behavior:

    * partner_ids should return a list of tuples:

    [(6, 0, IDs_in_res_partner)]

Video/Screenshot link (optional):

**Comment by rockcesar** [comment] 2018-02-19 14:58
I downloaded this version of Odoo from the Debian nightly repository:

deb http://nightly.odoo.com/10.0/nightly/deb/ ./

**Comment by rockcesar** [comment] 2018-02-19 15:38
The version from GitHub, branch 10.0, is working fine. But the problem is still happening in the nightly version.

**Comment by AbdulrhmanGad** [comment] 2018-04-12 09:29
dsfgbfgf

**Comment by Yenthe666** [comment] 2018-04-12 09:54
@d-fence I believe you're responsible for the nightly?

**Comment by d-fence** [comment] 2018-04-12 12:46
@rockcesar can you confirm that the problem is still there with the latest package ?
The nightly package is based on the git repository but is built really early in the morning.
So it may be out of sync with the git tree a few hours later.
But IMHO this kind of difference in the behavior cannot be caused by the build.
Did you make the test exactly in the same conditions ?

**Comment by rockcesar** [comment] 2018-05-25 21:02
Sorry for the late. Yes, I did the test in the same condition. Let me try if it's still happening. Thanks.

**Comment by Yenthe666** [comment] 2019-10-07 09:22
Dear @rockcesar,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe

**Closed by Yenthe666** 2019-10-07 09:22 UTC
Labels: 10.0, Framework
