### ISSUE TITLE
Odoo 14 ParseError during installation of payment acquierer module

### ISSUE THREAD

**Issue by t-900-a** [odoo/odoo#61335] opened 2020-11-04 14:02 UTC
Impacted versions: Odoo 14.0.20201101

Steps to reproduce: Install this plug-in: https://github.com/t-900-a/odoo-solana-payments

Current behavior: ParseError when parsing payment acquirer, full log here: https://siasky.net/CAAOumg4APg9bRC12s0IxfL1epH6s3dsc8573HFH3o1Y3A

File that is having issues being parsed: https://github.com/t-900-a/odoo-solana-payments/blob/main/data/solana_sol_payment_acquirer.xml

Expected behavior: Successful installation and a new payment acquirer should show up in the payment acquirer menu

My Notes on the issue:
I don't see any obvious spelling errors, and I've gone through each line to figure out which one is causing the error. I've eliminated a few fields.

These fields install without any errors: name, company_id, payment_flow, pre_msg, pending_msg, done_msg

The fields that cause the installation of the payment acquirer to fail are as follows: provider, view_template_id, registration_view_template_id, environment, and all my custom fields.

I'm following the way other payment acquirers have done it, but they are compatible with odoo 13. It is possible that the installation fails due to a bug or compatibility issue with odoo 14.

**Comment by pedrobaeza** [comment] 2020-11-04 14:48
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2020-11-04 14:48 UTC
