### ISSUE TITLE
float_round don't work with some values

### ISSUE THREAD

**Issue by carlosdauden** [odoo/odoo#30354] opened 2019-01-18 12:36 UTC
If you want round 6.1 with 0.001 precision the result is 6.1000000000000005
This operation 
https://github.com/odoo/odoo/blob/c45a4e8f835fd8d22af8941fd85e2b951f1e046b/odoo/tools/float_utils.py#L100
with rounded_value=6100 and rounding_factor=0.001
returns 6.1000000000000005

@Tecnativa

**Comment by carlosdauden** [comment] 2019-01-18 12:37
May be related with this closed issue: https://github.com/odoo/odoo/issues/20856

**Comment by pedrobaeza** [comment] 2019-01-18 12:39
Yeah, but this answer is the right one also for this one: https://github.com/odoo/odoo/issues/20856#issuecomment-344585431

The problem is in the nature of floats. The solution is to use the proper tools for comparing results, like done in #30352.

As this is not possible to be fixed in a general way, closing.

**Closed by pedrobaeza** 2019-01-18 12:39 UTC

**Comment by carlosdauden** [comment] 2019-01-18 12:41
Ok. Thanks
