### ISSUE TITLE
[12] Font size which passed in q-web-template not reflecting accurately in pdf report. (size in pt measurement)

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#52377] opened 2020-06-03 15:29 UTC
Impacted versions: 12 and 12E

Steps to reproduce:

- Download any report for which q-web template (xml) having used Style font-size in pts. (e.g. style="font-size:10pt;").
- Now open any tool offline / online for measurement of pdf font size. and use this downloaded report.

Current behavior:
- Its showing weird size. when applying 15pt in (code) report , it actually applied and showing 12.8 pt only. as you can see in below snapshot from runbot.

You can check example of Employee badge report. 
  - As this report having font size **style="font-size:15pt;** for Employee name.
  - Open any employee and from action print "Print Badge'.

Expected behavior:
- it should apply 15pt in this example or whatever which applied from code.

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/35560490/83655907-8b7f8600-a5dc-11ea-9075-846ee5f02fc8.png)

Thanks!

**Comment by pedrobaeza** [comment] 2020-06-03 15:33
That's because there are flex classes/components for adapting contents. It can be weird, but it's the expected behavior for not overflowing borders on several cases.

Closing as no issue, but expected behavior.

**Closed by pedrobaeza** 2020-06-03 15:33 UTC

**Comment by dipsshah42** [comment] 2020-06-03 15:34
@pedrobaeza  then how can we set specifc size in pt to any report if we want. can you please assist here ?

**Comment by pedrobaeza** [comment] 2020-06-03 15:36
You have to use classes that don't have that flex components, but I can't say more out of memory. Please use forums for asking that kind of questions.
