### ISSUE TITLE
13.0: Error in attribute "confirm" of tag "button" from wizard. 

### ISSUE THREAD

**Issue by gabrielhernandez3333** [odoo/odoo#68374] opened 2021-03-25 23:27 UTC
Impacted versions: 13

Steps to reproduce: 

XML:
```
 <record model="ir.ui.view" id="wizard_form_view">
            <field name="name">wizard.form.view</field>
            <field name="model">example.wizard</field>
            <field name="arch" type="xml">
                <form>
                    <sheet>
                        <group>
                            <group>
                                ........
                        </group>
                    </sheet>
                    <footer>
                        <button string="Process" confirm="Confirmation mnessage example" type="object" class="btn-primary" name="action_process"/>
                        <button string="Cancel" class="btn-secondary" special="cancel"/>
                    </footer>
                </form>
            </field>
        </record>

        <act_window id="action_wizard_example"
            name="Example"
            binding_model="example.model"
            res_model="example.wizard"
            binding_views="list"
            view_mode="form"
            target="new"
        />
```

Current behavior: When pressing the button with the "confirm" attribute, a dialog appears to accept or cancel, when pressing accept, the button method is executed correctly and the wizard is closed, but the dialog that opens the "confirm" attribute of the button remains open and only closes when pressing cancel or with the X above. 

Expected behavior: it should close the dialog. 

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment] 2021-03-26 07:25
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by gdgellatly** [comment] 2021-03-29 06:57
I can confirm this can happen with 3rd party modules installed. But not in default Odoo in 13.0. Confirmation dialogs in wizards work fine. I know because I went to report and I couldn't reproduce in runbot months ago and tested again just now using the Debit Note wizard dialog.

**Comment by pedrobaeza** [comment] 2021-03-29 06:58
OK, then closing and you should inspect which third party module is causing it.

**Closed by pedrobaeza** 2021-03-29 06:58 UTC
Labels: Need information
