### ISSUE TITLE
[11.0] Debian install - community 11

### ISSUE THREAD

**Issue by leonard-decaillet** [odoo/odoo#20285] opened 2017-10-18 12:33 UTC
Impacted versions: 11

Steps to reproduce:
Launch "apt update", following the install procedure described into the doc

Current behavior:
Get an error:
W: GPG error: http://nightly.odoo.com/11.0/nightly/deb ./ InRelease: The following signatures were i│drwxr-xr-x  2 root root 4096 Oct 12 15:48 __pycache__                                    
nvalid: 5D134C924CB06330DCEFE2A1DEF2A2198183CBB5                                                    │root@<masqued>:/usr/lib/python3/dist-packages/odoo/conf# cd ..
W: The repository 'http://nightly.odoo.com/11.0/nightly/deb ./ InRelease' is not signed.            │root@<masqued>:/usr/lib/python3/dist-packages/odoo# $cd /etc                                
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.│bash: /etc: Is a directory                  
N: See apt-secure(8) manpage for repository creation and user configuration details.

Expected behavior:
Can you correct the key, please ?

Video/Screenshot link (optional):

**Comment by amoyaux** [comment] 2017-10-18 12:40
@d-fence

**Comment by zbik2607** [comment] 2017-10-18 12:48
A similar error occurs with 
>aptitude update 
for the Odoo repositories 10

**Comment by d-fence** [comment] 2017-10-18 12:51
Hello, it's linked or duplicate of #19900 and #19960 .

I'm working on it.

**Comment by d-fence** [comment] 2017-10-19 13:16
The problem was that the 'Release' file needed for the Debian repository was signed with what is now considered a weak digest algorithm: sha1. Ubuntu 16.04 was giving a warning and Debian 9 refuse to use a repository with such a signature.
Although the fact that the preferred algorithms were in the right order, gpg signatures were always using sha1.
Finally, and as a reminder, adding the following config option in the gpg.conf file solved the problem:
```
personal-digest-preferences SHA256
```

**Closed by d-fence** 2017-10-19 13:16 UTC
Labels: 11.0
