### ISSUE TITLE
multiple attachments with own report with multiple pages

### ISSUE THREAD

**Issue by fwilly** [odoo/odoo#8393] opened 2015-09-04 20:02 UTC
After printing an invoice not only 1 invoice document is attached but a number of documents, 1 for each page of the invoice. If the invoice has 3 pages then 3 documents with respectively 1 page are attached.

Background info:
I have created a own report for invoices and sale orders. All can have multiple pages. Because I have different formats for the first and the next page my report define 2 div's with class "page".

But the download, which is automatically start after printing, contains a right pdf (1 document with 3 pages).

A additionally problem is, that the downloaded file has name "my_addon.my_invoice_report.pdf" and not the name defined at "attachment" property of my report definition. But the attached files have the right name.

**Comment by jlaloux** [comment] 2016-06-02 14:14
Up. Same issue

**Comment by JKE-be** [comment] 2016-06-02 19:20
Duplicate of #12272

**Closed by JKE-be** 2016-06-02 19:20 UTC
