### ISSUE TITLE
Odoo running on a google.cloud's VPS lost SQL connection when try to acess a product record

### ISSUE THREAD

**Issue by gnfranco** [odoo/odoo#49688] opened 2020-04-16 19:22 UTC
Impacted versions: 13

Steps to reproduce: Even I try to load /web#action=213&model=product.template&view_type=kanban&cids=&menu_id=93

Jsut return to connect to sql if I restart server vps or sql instance. If you restart the instance machine that run oddo or intance machine running sql it's work well another time. But since you try to acess product windows on stock it chashs another time.

Current behavior: Crash sql connection

Expected behavior: Don't crash any thing

Video/Screenshot link (optional):

**Comment by gnfranco** [comment] 2020-04-16 19:57
[818]: [1-1] db=postgres,user=odoo FATAL: remaining connection slots are reserved for non-replication superuser connections
{
  "textPayload": "[818]: [1-1] db=postgres,user=odoo FATAL:  remaining connection slots are reserved for non-replication superuser connections",
  "insertId": "s=0ee04e184fe44036b75770e76860c66c;i=c08cb;b=31be495c7e6240bb88efd8d27651b7ad;m=167fab8ac50;t=5a36db90d19f6;x=ebb468d6b8f94a8d-0@a1",
  "resource": {
    "type": "cloudsql_database",
    "labels": {
      "project_id": "sturdy-now-271200",
      "region": "us-west1",
      "database_id": "sturdy-now-271200:ghost33"
    }
  },
  "timestamp": "2020-04-16T19:48:54.959606Z",
  "severity": "ALERT",
  "logName": "projects/sturdy-now-271200/logs/cloudsql.googleapis.com%2Fpostgres.log",
  "receiveTimestamp": "2020-04-16T19:48:55.829922349Z"
}

**Comment by gnfranco** [comment] 2020-04-16 20:00
textPayload: "[376]: [1-1] db=odoo13,user=odoo FATAL:  terminating connection due to administrator command"

**Comment by gnfranco** [comment] 2020-04-16 20:03
[116]: [1-1] db=odoo13,user=odoo ERROR: could not obtain lock on row in relation "ir_cron"
{
textPayload: "[116]: [1-1] db=odoo13,user=odoo ERROR:  could not obtain lock on row in relation "ir_cron""
insertId: "s=0ee04e184fe44036b75770e76860c66c;i=c0fb4;b=31be495c7e6240bb88efd8d27651b7ad;m=16808f4f03f;t=5a36dc7495de4;x=47738e8f38e6654e-0@a1"
resource: {2}
timestamp: "2020-04-16T19:52:53.790180Z"
severity: "ERROR"
logName: "projects/sturdy-now-271200/logs/cloudsql.googleapis.com%2Fpostgres.log"
receiveTimestamp: "2020-04-16T19:52:54.798902096Z"
}

**Comment by gnfranco** [comment] 2020-04-16 20:05
{
  "textPayload": "[116]: [2-1] db=odoo13,user=odoo STATEMENT:  SELECT id FROM \"ir_cron\" WHERE id IN (7) FOR UPDATE NOWAIT",
  "insertId": "s=0ee04e184fe44036b75770e76860c66c;i=c0fb5;b=31be495c7e6240bb88efd8d27651b7ad;m=16808f4f277;t=5a36dc749601e;x=21e8ed2f8ed6172f-0@a1",
  "resource": {
    "type": "cloudsql_database",
    "labels": {
      "project_id": "sturdy-now-271200",
      "database_id": "sturdy-now-271200:ghost33",
      "region": "us-west1"
    }
  },
  "timestamp": "2020-04-16T19:52:53.790750Z",
  "severity": "INFO",
  "logName": "projects/sturdy-now-271200/logs/cloudsql.googleapis.com%2Fpostgres.log",
  "receiveTimestamp": "2020-04-16T19:52:54.798902096Z"
}

**Comment by gnfranco** [comment] 2020-04-16 20:19
https://www.dropbox.com/s/ztlu7et9h4yd4aa/2020-04-16.png?dl=0

**Comment by gdgellatly** [comment] 2020-04-16 21:48
Hi,

Its a configuration issue, you really could have just googled these errors. Basically you have oversized your odoo and undersized your database so you are running out of connections is the main problem.

The rest are usual errors but normally you would configure correctly so they don't occur. This is an administrator issue not an Odoo one.

**Comment by gnfranco** [comment] 2020-04-16 23:18
I will contact Google.    Thanks.
But I don't changed any thing on my configuration...

**Comment by gnfranco** [comment] 2020-04-17 00:34
I've increased a bit memory and seens to solve my problem.
Sorry for post it here. And thank you any way.

Best regards,
Glauber

**Comment by Yenthe666** [comment] 2020-04-17 07:03
Closing as it is a deployment issue, not a bug in Odoo.

**Closed by Yenthe666** 2020-04-17 07:03 UTC
