### ISSUE TITLE
[11.0] Calendar: Could not create all day event.

### ISSUE THREAD

**Issue by Dangar-Serpentcs** [odoo/odoo#25680] opened 2018-07-09 13:06 UTC
Impacted versions: 11.0

Steps to reproduce: 

- Go to Calendar tree / form view
- Create new record
- Tick `All Day` and select `Starting / Ending at`.
- Save the record.

Current behavior:
Could not save the record.
![screenshot from 2018-07-09 18-34-37](https://user-images.githubusercontent.com/38550879/42452139-daafeeae-83a6-11e8-83e4-61441a4255d7.png)

Expected behavior:
Save the record.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2018-07-09 14:39
@RomainLibert is this related with the work you are doing in some PRs?

**Comment by mart-e** [comment] 2018-07-09 15:32
I was able to reproduce this in 10.0 as well. If you go to the calendar view you do not have this issue as the start/end fields are already field.

However, if you go to the form view for a new record, you do not have any value on these required fields.

https://github.com/odoo/odoo/blob/dc0914b8a5966b70bcaf647fca6f8c92d3c8c26d/addons/calendar/models/calendar.py#L690-L691

They are filled by the inverse fields `start_date` and `end_date` but this is done _after_ the create....

https://github.com/odoo/odoo/blob/dc0914b8a5966b70bcaf647fca6f8c92d3c8c26d/addons/calendar/models/calendar.py#L811-L817

**Comment by pedrobaeza** [comment] 2018-07-09 15:36
I think a solution is to put them as not required on the view, and let the inverse to act on saving.

**Comment by RomainLibert** [comment] 2018-07-09 15:38
The solution is probably to add an onchange on start_date and stop_date in order to fill start and stop fields

**Comment by mart-e** [comment] 2018-07-10 07:54
> I think a solution is to put them as not required on the view, and let the inverse to act on saving.

@pedrobaeza This does not work (I tried) as the computed are set _after_ the `create`.
The solution from @RomainLibert seems better.

**Comment by pedrobaeza** [comment] 2018-07-10 07:56
OK, thanks, I didn't know that.

**Comment by pedrobaeza** [comment] 2018-07-10 10:22
Fixed in  e08f999

**Comment by pedrobaeza** [comment] 2018-07-10 10:23
Well, it will come to 11.0 when forward-porting is done, so technically is not yet solved in 11.0, but in 10.0.

**Closed by pedrobaeza** 2018-07-10 10:22 UTC
Labels: Confirmed, Services

**Comment by sswapnesh** [comment] 2018-07-10 17:12
@pedrobaeza  @RomainLibert  Instead of onchnage we can add `default=fields.Datetime.now()` for `start/stop` fields, because on save it will calculate those fields again, So onchnage is useless here.

**Comment by pedrobaeza** [comment] 2018-07-10 17:15
Well, the computation cost is more or less the same, so let's keep it as is right now, being this an edge case and not the general one.
