### ISSUE TITLE
[Odoo 11] Error change stage maintenance request with lang vietnamese

### ISSUE THREAD

**Issue by oanhle** [odoo/odoo#30048] opened 2019-01-09 04:17 UTC
I am having problems on runbot when change state Maintenance requirements with Vietnamese language

**Comment by Yenthe666** [comment] 2019-01-09 07:00
Hi @oanhle,

Thanks for your report, I've confirmed the behaviour. Example video:
https://drive.google.com/file/d/15nqieyKNCigwiq5V-kyrgREhexA1SkvR/view
It looks like there are some issues with the translation values for the e-mail template, there is probably a mistake in the translation term. Have you tried to fix the e-mail template?
@mart-e any chance you can give a helping hand?

Regards,
Yenthe

**Comment by mart-e** [comment] 2019-01-09 10:21
Hi,

Indeed, there was an issue in the translation.
It has been fixed in Transifex, it will be in the next synchronisation, thanks for the report.

See on Transifex for details
https://www.transifex.com/odoo/odoo-11/translate/#vi/mail/119295387?q=occurrence%3Amail_template_data_notification_email_default

**Closed by mart-e** 2019-01-09 10:21 UTC
Labels: 11.0, Confirmed, Internationalization
