### ISSUE TITLE
[9.0] Duplicate database is not worked

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#9294] opened 2015-10-29 03:32 UTC
Hi Odoo,

I want to duplicated database in version 9, and when I make a duplicate it will be an error,
and when I enter the duplicate database I have a blank screen.

Here is the log:

2015-10-29 02:39:47,920 948 INFO Z_HPG_151029 openerp.addons.base.ir.ir_attachment: _read_file$
Traceback (most recent call last):
  File "/home/odoo90/odoo/openerp/addons/base/ir/ir_attachment.py", line 151, in _file_read
    r = open(full_path,'rb').read().encode('base64')
IOError: [Errno 2] No such file or directory: u'/home/odoo90/.local/share/Odoo/filestore/Z_HPG$
2015-10-29 02:39:47,956 948 INFO Z_HPG_151029 openerp.addons.base.ir.ir_attachment: _read_file$
Traceback (most recent call last):
  File "/home/odoo90/odoo/openerp/addons/base/ir/ir_attachment.py", line 151, in _file_read
    r = open(full_path,'rb').read().encode('base64')
IOError: [Errno 2] No such file or directory: u'/home/odoo90/.local/share/Odoo/filestore/Z_HPG$
2015-10-29 02:39:47,977 948 INFO Z_HPG_151029 openerp.addons.base.ir.ir_attachment: _read_file$
Traceback (most recent call last):
  File "/home/odoo90/odoo/openerp/addons/base/ir/ir_attachment.py", line 151, in _file_read
    r = open(full_path,'rb').read().encode('base64')
IOError: [Errno 2] No such file or directory: u'/home/odoo90/.local/share/Odoo/filestore/Z_HPG$
2015-10-29 02:39:47,977 948 INFO Z_HPG_151029 openerp.addons.base.ir.ir_attachment: _read_file$
Traceback (most recent call last):
  File "/home/odoo90/odoo/openerp/addons/base/ir/ir_attachment.py", line 151, in _file_read
    r = open(full_path,'rb').read().encode('base64')
IOError: [Errno 2] No such file or directory: u'/home/odoo90/.local/share/Odoo/filestore/Z_HPG$
2015-10-29 02:39:47,979 948 INFO Z_HPG_151029 openerp.addons.base.ir.ir_attachment: _read_file$
Traceback (most recent call last):
  File "/home/odoo90/odoo/openerp/addons/base/ir/ir_attachment.py", line 151, in _file_read
    r = open(full_path,'rb').read().encode('base64')
IOError: [Errno 2] No such file or directory: u'/home/odoo90/.local/share/Odoo/filestore/Z_HPG$
2015-10-29 02:39:47,979 948 INFO Z_HPG_151029 openerp.addons.base.ir.ir_attachment: _read_file$
Traceback (most recent call last):
  File "/home/odoo90/odoo/openerp/addons/base/ir/ir_attachment.py", line 151, in _file_read
    r = open(full_path,'rb').read().encode('base64')
IOError: [Errno 2] No such file or directory: u'/home/odoo90/.local/share/Odoo/filestore/Z_HPG$

**Comment by pedrobaeza** [comment] 2018-04-06 00:33
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-04-06 00:33 UTC
Labels: 9.0, Framework

**Comment by Yenthe666** [comment] 2018-04-06 15:12
@pedrobaeza duplicate on a runbot? 😉 Hmm 😉

**Comment by pedrobaeza** [comment] 2018-04-06 15:17
Agh, I modify the template, but not all. Not on runbot, but directly on my local instance. In fact, it's something I do everyday. That's why I have it very clear.
