### ISSUE TITLE
Error after loading images from external website - 9.0

### ISSUE THREAD

**Issue by kkoci** [odoo/odoo#9504] opened 2015-11-10 10:05 UTC
Hi, I need to revert something I've added to a website file, from the HTML editor.

This is the error on my browser's console:
```
error: Some modules could not be started 
Failed modules:          Array[1]0: "web.session"length: 1__proto__: Array[0]concat: concat()constructor: Array()copyWithin: copyWithin()entries: entries()every: every()fill: fill()filter: filter()find: find()findIndex: findIndex()forEach: forEach()indexOf: indexOf()join: join()keys: keys()lastIndexOf: lastIndexOf()length: 0map: map()pop: pop()push: push()reduce: reduce()reduceRight: reduceRight()reverse: reverse()shift: shift()slice: slice()some: some()sort: sort()splice: splice()toLocaleString: toLocaleString()toString: toString()unshift: unshift()Symbol(Symbol.iterator): values()Symbol(Symbol.unscopables): Object__proto__: Object 
Rejected modules:        Array[1]0: "website_sale.website_sale"length: 1__proto__: Array[0] 
Non loaded modules:      Array[22]0: "web.Widget"1: "web.Model"2: "web.Dialog"3: "web.planner.common"4: "rating.rating"5: "website_crm.tour"6: "web_editor.editor"7: "web_editor.rte"8: "web_editor.rte.summernote"9: "web_editor.widget"10: "web_editor.snippet.editor"11: "web_editor.snippets.options"12: "web_editor.tour"13: "web_editor.transcoder"14: "web_editor.translate"15: "website.website"16: "website.share"17: "website_portal"18: "website_mail.thread"19: "website_payment.website_payment"20: "website_sale.rating"21: "website.editor"length: 22__proto__: Array[0]window.odoo.log @ web.assets_common.js:2523
(index):1 Font from origin 'https://www.sukottoscissors.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://45.79.131.75:8069' is therefore not allowed access.
```

Which comes after this:

```
Server application error {"message":"Odoo Server Error","code":200,"data":{"debug":"Traceback (most recent call last):\n  File \"/opt/python/apps/odoo/instances/sukotto/odoo/openerp/http.py\", line 599, in _handle_exception\n    return super(JsonRequest, self)._handle_exception(exception)\n  File \"/opt/python/apps/odoo/instances/sukotto/odoo/openerp/addons/base/ir/ir_http.py\", line 154, in _dispatch\n    rule, arguments = self._find_handler(return_rule=True)\n  File \"/opt/python/apps/odoo/instances/sukotto/odoo/openerp/addons/base/ir/ir_http.py\", line 65, in _find_handler\n    return self.routing_map().bind_to_environ(request.httprequest.environ).match(return_rule=return_rule)\n  File \"/opt/python/apps/odoo/instances/sukotto/virtual_sukotto/local/lib/python2.7/site-packages/werkzeug/routing.py\", line 1430, in match\n    raise NotFound()\nNotFound: 404: Not Found\n","exception_type":"internal_error","message":"","name":"werkzeug.exceptions.NotFound","arguments":[]}}(anonymous function) @ web.assets_common.js:2543
web.assets_common.js:2523 error: Some modules could not be started 
Failed modules:          Array[1]0: "web.session"length: 1__proto__: Array[0]concat: concat()constructor: Array()copyWithin: copyWithin()entries: entries()every: every()fill: fill()filter: filter()find: find()findIndex: findIndex()forEach: forEach()indexOf: indexOf()join: join()keys: keys()lastIndexOf: lastIndexOf()length: 0map: map()pop: pop()push: push()reduce: reduce()reduceRight: reduceRight()reverse: reverse()shift: shift()slice: slice()some: some()sort: sort()splice: splice()toLocaleString: toLocaleString()toString: toString()unshift: unshift()Symbol(Symbol.iterator): values()Symbol(Symbol.unscopables): Object__proto__: Object 
Rejected modules:        Array[1]0: "website_sale.website_sale"length: 1__proto__: Array[0] 
Non loaded modules:      Array[22]0: "web.Widget"1: "web.Model"2: "web.Dialog"3: "web.planner.common"4: "rating.rating"5: "website_crm.tour"6: "web_editor.editor"7: "web_editor.rte"8: "web_editor.rte.summernote"9: "web_editor.widget"10: "web_editor.snippet.editor"11: "web_editor.snippets.options"12: "web_editor.tour"13: "web_editor.transcoder"14: "web_editor.translate"15: "website.website"16: "website.share"17: "website_portal"18: "website_mail.thread"19: "website_payment.website_payment"20: "website_sale.rating"21: "website.editor"length: 22__proto__: Array[0]window.odoo.log @ web.assets_common.js:2523
```

Anyways, if this is confusing, I need to know, where I can find any custom lines I've added, in database, or whatever, so I can revert this situation manually.

I think this error, comes from website.common.assets, after I've added some remote files (remote URL's)

These errors appeared.

Please, someone could lead me to these files or tables? I just need the paths.

Or maybe another solution, is also very welcome.

Thanks in advance!

**Comment by aleksandar-irvas** [comment] 2016-08-25 08:59
I have same errors too. Did you solve this?

**Comment by pedrobaeza** [comment] 2018-04-17 23:33
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-04-17 23:33 UTC
