### ISSUE TITLE
[10.0] AutoReload watcher does not reload Odoo correctly on Windows

### ISSUE THREAD

**Issue by maksym-synkevych** [odoo/odoo#18418] opened 2017-07-24 16:00 UTC
Impacted versions: 10.0

Steps to reproduce:
1. Start Odoo on Windows with following command:
`python odoo-bin -w %login% -r %password% --addons-path=addons,%my_addon_path%  --log-level=debug --dev=reload`
2. Open UI on http://localhost:8069 - everything is fine.
3. Add comment to %file%.py file in %my_addon_path% directory.
4. Wait for restarting.

Current behavior:
Open UI on http://localhost:8069 - Odoo does not respond.

Expected behavior:
Open UI on http://localhost:8069 - Odoo respond.

Video/Screenshot link (optional):
Starting Odoo logs:
```
2017-07-24 15:50:29,125 3252 DEBUG ? odoo.netsvc: logger level set: "odoo.workflow.workitem:WARNING"
2017-07-24 15:50:29,128 3252 DEBUG ? odoo.netsvc: logger level set: "odoo.http.rpc.request:INFO"
2017-07-24 15:50:29,128 3252 DEBUG ? odoo.netsvc: logger level set: "odoo.http.rpc.response:INFO"
2017-07-24 15:50:29,128 3252 DEBUG ? odoo.netsvc: logger level set: "odoo.addons.web.http:INFO"
2017-07-24 15:50:29,130 3252 DEBUG ? odoo.netsvc: logger level set: "odoo.sql_db:INFO"
2017-07-24 15:50:29,130 3252 DEBUG ? odoo.netsvc: logger level set: ":INFO"
2017-07-24 15:50:29,131 3252 DEBUG ? odoo.netsvc: logger level set: "odoo:DEBUG"
2017-07-24 15:50:29,131 3252 DEBUG ? odoo.netsvc: logger level set: ":INFO"
2017-07-24 15:50:29,132 3252 INFO ? odoo: Odoo version 10.0
2017-07-24 15:50:29,132 3252 INFO ? odoo: addons paths: [u'%user_home_directory_path%\\AppData\\Local\\OpenERP S.A.\\Odoo\\addons\\10.0', u'%Odoo_path%\\addons', u'%my_addon_path%', '%Odoo_path%\\odoo\\addons']
2017-07-24 15:50:29,134 3252 INFO ? odoo: database: odoo@default:default
2017-07-24 15:50:29,153 3252 INFO ? odoo.service.server: Watching addons folder %user_home_directory_path%\AppData\Local\OpenERP S.A.\Odoo\addons\10.0
2017-07-24 15:50:29,155 3252 INFO ? odoo.service.server: Watching addons folder %Odoo_path%\addons
2017-07-24 15:50:29,157 3252 INFO ? odoo.service.server: Watching addons folder %my_addon_path%
2017-07-24 15:50:29,157 3252 INFO ? odoo.service.server: Watching addons folder %Odoo_path%\odoo\addons
2017-07-24 15:50:29,160 3252 INFO ? odoo.service.server: AutoReload watcher running
2017-07-24 15:50:29,161 3252 DEBUG ? odoo.service.server: Setting signal handlers
2017-07-24 15:50:29,161 3252 INFO ? odoo.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
2017-07-24 15:50:29,167 3252 DEBUG ? odoo.service.server: cron0 started!
2017-07-24 15:50:29,170 3252 DEBUG ? odoo.service.server: cron1 started!
```
Restarting Odoo logs:
```
2017-07-24 15:50:41,273 3252 INFO ? odoo.service.server: autoreload: python code updated, autoreload activated

> 2017-07-24 15:50:42,980 8452 DEBUG ? odoo.netsvc: logger level set: "odoo.workflow.workitem:WARNING"
2017-07-24 15:50:42,982 8452 DEBUG ? odoo.netsvc: logger level set: "odoo.http.rpc.request:INFO"
2017-07-24 15:50:42,983 8452 DEBUG ? odoo.netsvc: logger level set: "odoo.http.rpc.response:INFO"
2017-07-24 15:50:42,983 8452 DEBUG ? odoo.netsvc: logger level set: "odoo.addons.web.http:INFO"
2017-07-24 15:50:42,983 8452 DEBUG ? odoo.netsvc: logger level set: "odoo.sql_db:INFO"
2017-07-24 15:50:42,984 8452 DEBUG ? odoo.netsvc: logger level set: ":INFO"
2017-07-24 15:50:42,986 8452 DEBUG ? odoo.netsvc: logger level set: "odoo:DEBUG"
2017-07-24 15:50:42,986 8452 DEBUG ? odoo.netsvc: logger level set: ":INFO"
2017-07-24 15:50:42,986 8452 INFO ? odoo: Odoo version 10.0
2017-07-24 15:50:42,987 8452 INFO ? odoo: addons paths: [u'%user_home_directory_path%\\AppData\\Local\\OpenERP S.A.\\Odoo\\addons\\10.0', u'%Odoo_path%\\addons', u'%my_addon_path%', '%Odoo_path%\\odoo\\addons']
2017-07-24 15:50:42,990 8452 INFO ? odoo: database: odoo@default:default
2017-07-24 15:50:43,007 8452 INFO ? odoo.service.server: Watching addons folder %user_home_directory_path%\AppData\Local\OpenERP S.A.\Odoo\addons\10.0
2017-07-24 15:50:43,013 8452 INFO ? odoo.service.server: Watching addons folder %Odoo_path%\addons
2017-07-24 15:50:43,015 8452 INFO ? odoo.service.server: Watching addons folder %my_addon_path%
2017-07-24 15:50:43,016 8452 INFO ? odoo.service.server: Watching addons folder %Odoo_path%\odoo\addons
2017-07-24 15:50:43,019 8452 INFO ? odoo.service.server: AutoReload watcher running
2017-07-24 15:50:43,022 8452 DEBUG ? odoo.service.server: Setting signal handlers
2017-07-24 15:50:43,023 8452 INFO ? odoo.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
2017-07-24 15:50:43,026 8452 DEBUG ? odoo.service.server: cron0 started!
2017-07-24 15:50:43,029 8452 DEBUG ? odoo.service.server: cron1 started!
```
After that Odoo сontinues to send logs "polling for jobs", but does not respond to calls.
When you change the files again, the Odoo also restarts, but does not respond to calls.

**Comment by Yenthe666** [comment] 2017-12-28 10:14
@d-fence maybe for you?

**Comment by d-fence** [comment] 2017-12-28 14:49
@Yenthe666 Not the packaged version (10.0 is an .exe) and was not able to reproduce.

**Comment by Yenthe666** [comment] 2017-12-28 14:51
@maksym-synkevych can you still reproduce this issue on the latest Odoo 10?

**Comment by maksym-synkevych** [comment] 2018-03-05 09:59
Yes, I still reproduce this issue on the latest Odoo 10 from that repository (https://github.com/odoo/odoo/tree/10.0)
Launched from src (not an .exe version)

Console log:
```
Maksym_Synkevych@XXX D:\XXX\odoo-src
> python odoo-bin -w odoo -r odoo --addons-path=addons,xxx  --log-level=debug --dev=reload
2018-03-05 09:47:09,265 10288 DEBUG ? odoo.netsvc: logger level set: "odoo.workflow.workitem:WARNING"
2018-03-05 09:47:09,266 10288 DEBUG ? odoo.netsvc: logger level set: "odoo.http.rpc.request:INFO"
2018-03-05 09:47:09,266 10288 DEBUG ? odoo.netsvc: logger level set: "odoo.http.rpc.response:INFO"
2018-03-05 09:47:09,266 10288 DEBUG ? odoo.netsvc: logger level set: "odoo.addons.web.http:INFO"
2018-03-05 09:47:09,267 10288 DEBUG ? odoo.netsvc: logger level set: "odoo.sql_db:INFO"
2018-03-05 09:47:09,267 10288 DEBUG ? odoo.netsvc: logger level set: ":INFO"
2018-03-05 09:47:09,267 10288 DEBUG ? odoo.netsvc: logger level set: "odoo:DEBUG"
2018-03-05 09:47:09,269 10288 DEBUG ? odoo.netsvc: logger level set: ":INFO"
2018-03-05 09:47:09,269 10288 INFO ? odoo: Odoo version 10.0
2018-03-05 09:47:09,269 10288 INFO ? odoo: addons paths: [u'C:\\Users\\Maksym_Synkevych\\AppData\\Local\\OpenERP S.A.\\Odoo\\addons\\10.0', u'xxx\\odoo-src\\addons', u'xxx', 'xxx\\odoo-src\\odoo\\addons']
2018-03-05 09:47:09,269 10288 INFO ? odoo: database: odoo@default:default
2018-03-05 09:47:09,414 10288 INFO ? odoo.service.server: Watching addons folder C:\Users\Maksym_Synkevych\AppData\Local\OpenERP S.A.\Odoo\addons\10.0
2018-03-05 09:47:09,434 10288 INFO ? odoo.service.server: Watching addons folder xxx\odoo-src\addons
2018-03-05 09:47:09,434 10288 INFO ? odoo.service.server: Watching addons folder xxx
2018-03-05 09:47:09,436 10288 INFO ? odoo.service.server: Watching addons folder xxx\odoo-src\odoo\addons
2018-03-05 09:47:09,437 10288 INFO ? odoo.service.server: AutoReload watcher running
2018-03-05 09:47:09,437 10288 DEBUG ? odoo.service.server: Setting signal handlers
2018-03-05 09:47:09,438 10288 INFO ? odoo.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
2018-03-05 09:47:09,443 10288 DEBUG ? odoo.service.server: cron0 started!
2018-03-05 09:47:09,444 10288 DEBUG ? odoo.service.server: cron1 started!
2018-03-05 09:47:43,607 10288 INFO ? odoo.service.server: autoreload: python code updated, autoreload activated

Maksym_Synkevych@xxx xxx\odoo-src
> 2018-03-05 09:47:45,607 11152 DEBUG ? odoo.netsvc: logger level set: "odoo.workflow.workitem:WARNING"
2018-03-05 09:47:45,608 11152 DEBUG ? odoo.netsvc: logger level set: "odoo.http.rpc.request:INFO"
2018-03-05 09:47:45,608 11152 DEBUG ? odoo.netsvc: logger level set: "odoo.http.rpc.response:INFO"
2018-03-05 09:47:45,608 11152 DEBUG ? odoo.netsvc: logger level set: "odoo.addons.web.http:INFO"
2018-03-05 09:47:45,609 11152 DEBUG ? odoo.netsvc: logger level set: "odoo.sql_db:INFO"
2018-03-05 09:47:45,611 11152 DEBUG ? odoo.netsvc: logger level set: ":INFO"
2018-03-05 09:47:45,611 11152 DEBUG ? odoo.netsvc: logger level set: "odoo:DEBUG"
2018-03-05 09:47:45,611 11152 DEBUG ? odoo.netsvc: logger level set: ":INFO"
2018-03-05 09:47:45,611 11152 INFO ? odoo: Odoo version 10.0
2018-03-05 09:47:45,612 11152 INFO ? odoo: addons paths: [u'C:\\Users\\Maksym_Synkevych\\AppData\\Local\\OpenERP S.A.\\Odoo\\addons\\10.0', u'xxx\\odoo-src\\addons', u'xxx', 'xxx\\odoo-src\\odoo\\addons']
2018-03-05 09:47:45,614 11152 INFO ? odoo: database: odoo@default:default
2018-03-05 09:47:45,630 11152 INFO ? odoo.service.server: Watching addons folder C:\Users\Maksym_Synkevych\AppData\Local\OpenERP S.A.\Odoo\addons\10.0
2018-03-05 09:47:45,631 11152 INFO ? odoo.service.server: Watching addons folder xxx\odoo-src\addons
2018-03-05 09:47:45,632 11152 INFO ? odoo.service.server: Watching addons folder xxx
2018-03-05 09:47:45,632 11152 INFO ? odoo.service.server: Watching addons folder xxx\odoo-src\odoo\addons
2018-03-05 09:47:45,634 11152 INFO ? odoo.service.server: AutoReload watcher running
2018-03-05 09:47:45,635 11152 DEBUG ? odoo.service.server: Setting signal handlers
2018-03-05 09:47:45,637 11152 INFO ? odoo.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
2018-03-05 09:47:45,641 11152 DEBUG ? odoo.service.server: cron0 started!
2018-03-05 09:47:45,642 11152 DEBUG ? odoo.service.server: cron1 started!
2018-03-05 09:48:45,644 11152 DEBUG ? odoo.service.server: cron0 polling for jobs
2018-03-05 09:48:46,642 11152 DEBUG ? odoo.service.server: cron1 polling for jobs
```
And after that restart Odoo does not response at localhost:8069

**Comment by Yenthe666** [comment] 2018-03-05 11:13
@d-fence could you check from source too please?

**Comment by pedrobaeza** [comment] 2018-06-02 14:54
Hi, this seems something related to your deployment, so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/10.0/setup/install.html. It's also strongly recommended to use Linux, where there are less possibilities of errors.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

**Closed by pedrobaeza** 2018-06-02 14:54 UTC
Labels: 10.0, Framework
