### ISSUE TITLE
Email Template breaks after opening to edit template and discarding changes

### ISSUE THREAD

**Issue by decamindit** [odoo/odoo#46599] opened 2020-02-28 15:55 UTC
Impacted versions:
13
Steps to reproduce:
Settings -> Technical -> Templates -> Sales Order: Confirmation Email
Once open click Edit, click inside Body window, click Discard. Click Preview and select any SO placed through the website

Current behavior:
Template breaks for website orders (SO generated from website orders) only

Expected behavior:
Template does not break

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2020-02-28 19:17
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by decamindit** [comment] 2020-02-28 19:23
Hello,

Yes I am able to reproduce it in runbot.

Steps to reproduce:
Settings -> Technical -> Templates -> Sales Order: Confirmation Email
Once open click Edit, click inside Body window, click Discard. Click Preview and select any SO placed through the website

The SO that was created through the Sale app works absolutely fine.

I’ve tracked down the issue to this block:

% for line in object.order_line:
                    % if not line.is_delivery:
                        <tr style="${loop.cycle('background-color: #f2f2f2', 'background-color: #ffffff')}">
                            % if line.display_type == 'line_section':
                                <td colspan="4"><strong>${line.name}</strong></td>
                            % elif line.display_type == 'line_note':
                                <td colspan="4"><i>${line.name}</i></td>
                            % else:
                                <td style="width: 150px;">
                                    <img src="/web/image/product.product/${line.product_id.id}/image_128" style="width: 64px; height: 64px; object-fit: contain;" alt="Product image"/>
                                </td>
                                <td align="left">${line.product_id.name}</td>
                                <td>${line.product_uom_qty}</td>
                                % if object.user_id.has_group('account.group_show_line_subtotals_tax_excluded'):
                                    <td align="right">${format_amount(line.price_reduce_taxexcl, object.currency_id)}</td>
                                % endif
                                % if object.user_id.has_group('account.group_show_line_subtotals_tax_included'):
                                    <td align="right">${format_amount(line.price_reduce_taxinc, object.currency_id)}</td>
                                % endif
                            % endif
                        </tr>
                    % endif
                % endfor


The issue seems to be a problem parsing the <td> and <tr> tags, if they are replaced with <div> tags then the template parses.
Interesting enough on of the runbot servers the issue is only with the EN template, it had CH installed which produced no issue.

Regards,
Rosti

**Comment by decamindit** [comment] 2020-02-28 19:33
I've found where the issue lies. When using the code editor instead of the HTML editor to edit the template, everytime I would paste the code it seemed ok but if saving or hitting preview the code would get rearranged. The only way I got the template to work is by pasting the code directly in to the body_html cell in the database. Every time that the template is opened for editing and even if the changes are discarded the template code is rearranged.

**Comment by pedrobaeza** [comment] 2020-02-28 19:36
But how are you using that code editor? Are you clicking the view code button? Then this is a missing step to reproduce the problem. Any way, I'm trying with both and I'm not able to reproduce it, so there are more missing steps.

**Comment by decamindit** [comment] 2020-02-28 19:39
Initially I ran into the problem when just opening the template, clicking discard and then preview. Thats when the template broke for the website SO orders.
When i started to investigate where the problem lies i found out that when pasting the code into the code window and then clicking Save, would automatically format the code to this:

<div style<div="" style="margin:0px;padding: 0px;">
    <p style="padding:0px;font-size: 12px;">
        Hello,
        <br><br>
        % set transaction = object.get_portal_last_transaction()
        Your order <strong>${object.name}</strong> amounting in <strong>${format_amount(object.amount_total, object.currency_id)}</strong>
        % if object.state == 'sale' or (transaction and transaction.state in ('done', 'authorized')) :
            has been confirmed.<br>
            Thank you for your trust!
        % elif transaction and transaction.state == 'pending' :
            is pending. It will be confirmed when the payment is received.
            % if object.reference:
                Your payment reference is <strong>${object.reference}</strong>.
            % endif
        % endif
        <br><br>
        Do not hesitate to contact us if you have any questions.
        <br><br></p>
        % if object.website_id:
        
                % for line in object.order_line:
                    % if not line.is_delivery:
                        
                            % if line.display_type == 'line_section':
                                
                            % elif line.display_type == 'line_note':
                               
                            % else:
                                
                                % if object.user_id.has_group('account.group_show_line_subtotals_tax_excluded'):
                                    
                                % endif
                                % if object.user_id.has_group('account.group_show_line_subtotals_tax_included'):
                                   
                                % endif
                            % endif
                        
                    % endif
                % endfor
            <table width="100%" style="color:#454748;font-size: 12px; border-collapse: collapse;">
                <tbody><tr style="border-bottom:2px solid #dee2e6;">
                    <td width="18%"><strong>Products</strong></td>
                    <td></td>
                    <td><strong>Quantity</strong></td>
                    <td width="10%" align="center"><strong>Price</strong></td>
                </tr><tr style="${loop.cycle('background-color:#f2f2f2', 'background-color: #ffffff')}"><td colspan="4"><strong>${line.name}</strong></td><td colspan="4"><i>${line.name}</i></td><td style="width:150px;">
                                    <img src="/web/image/product.product/${line.product_id.id}/image_128" style="width:64px;height: 64px; object-fit: contain;" alt="Product image">
                                </td>
                                <td align="left">${line.product_id.name}</td>
                                <td>${line.product_uom_qty}</td><td align="right">${format_amount(line.price_reduce_taxexcl, object.currency_id)}</td><td align="right">${format_amount(line.price_reduce_taxinc, object.currency_id)}</td></tr></tbody></table>
    % endif
    <div></div>
            
                % if object.carrier_id:
                   
                % else:
                    
                % endif
                <table width="40%" style="color:#454748;font-size: 12px; border-spacing: 0px 4px;" align="right"><tbody><tr>
                        <td style="border-top:1px solid #dee2e6;" align="right"><strong>Delivery:</strong></td>
                        <td style="border-top:1px solid #dee2e6;" align="right">${format_amount(object.amount_delivery, object.currency_id)}</td>
                    </tr>
                    <tr>
                        <td width="30%" align="right"><strong>SubTotal:</strong></td>
                        <td align="right">${format_amount(object.amount_untaxed, object.currency_id)}</td>
                    </tr><tr>
                        <td style="border-top:1px solid #dee2e6;" width="30%" align="right"><strong>SubTotal:</strong></td>
                        <td style="border-top:1px solid #dee2e6;" align="right">${format_amount(object.amount_untaxed, object.currency_id)}</td>
                    </tr><tr>
                    <td align="right"><strong>Taxes:</strong></td>
                    <td align="right">${format_amount(object.amount_tax, object.currency_id)}</td>
                </tr>
                <tr>
                    <td style="border-top:1px solid #dee2e6;" align="right"><strong>Total:</strong></td>
                    <td style="border-top:1px solid #dee2e6;" align="right">${format_amount(object.amount_total, object.currency_id)}</td>
                </tr>
            </tbody></table>
            <br>
            
                % if object.partner_invoice_id:
                    
                % endif
                % if object.partner_shipping_id and not object.only_services:
                    
                    % if object.carrier_id:
                       
                    % endif
                % endif
            <table width="100%" style="color:#454748;font-size: 12px;"><tbody><tr>
                        <td style="padding-top:10px;">
                            <strong>Bill to:</strong>
                            ${object.partner_invoice_id.street or ''}
                            ${object.partner_invoice_id.city or ''}
                            ${object.partner_invoice_id.state_id.name or ''}
                            ${object.partner_invoice_id.zip or ''}
                            ${object.partner_invoice_id.country_id.name or ''}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <strong>Payment Method:</strong>
                            % if transaction.payment_token_id:
                                ${transaction.payment_token_id.name}
                            % else:
                                ${transaction.acquirer_id.name}
                            % endif
                             (${format_amount(transaction.amount, object.currency_id)})
                        </td>
                    </tr><tr>
                        <td>
                            <br>
                            <strong>Ship to:</strong>
                            ${object.partner_shipping_id.street or ''}
                            ${object.partner_shipping_id.city or ''}
                            ${object.partner_shipping_id.state_id.name or ''}
                            ${object.partner_shipping_id.zip or ''}
                            ${object.partner_shipping_id.country_id.name or ''}
                        </td>
                    </tr><tr>
                            <td>
                                <strong>Shipping Method:</strong>
                                ${object.carrier_id.name}
                                % if object.carrier_id.fixed_price == 0.0:
                                    (Free)
                                % else:
                                    (${format_amount(object.carrier_id.fixed_price, object.currency_id)})
                                % endif
                            </td>
                        </tr></tbody></table>
        ### endif
    <p></p>
</div>

**Comment by decamindit** [comment] 2020-02-28 19:40
the only way for me to save the code in the correct format would be to paste it directly in to the db

**Comment by pedrobaeza** [comment] 2020-02-28 19:42
Sorry, but still not able to reproduce it. Is that standard template code or custom one?

**Comment by decamindit** [comment] 2020-02-28 19:43
its a standard template. I've tested it on the runbot 1540907-13-0-bf7d2d-all

**Comment by decamindit** [comment] 2020-02-28 19:47
<img width="1244" alt="Screen Shot 2020-02-28 at 12 46 30 PM" src="https://user-images.githubusercontent.com/61265922/75582270-6f41db00-5a28-11ea-84d4-691f347e00b8.png">

**Comment by pedrobaeza** [comment] 2020-02-29 12:00
You are not pasting the exact code, as I have tried with yours, and indeed it gives error, but cutting the existing code, saving, and pasting again it, it continues to work, so the problem should be in your pasted code:

![Peek 29-02-2020 13-00](https://user-images.githubusercontent.com/7165771/75607053-7681eb00-5af3-11ea-9b46-46f680a62133.gif)

Closing this as no apparent issue. If it's proved to be failing later, I can reopen.

**Comment by decamindit** [comment] 2020-02-29 19:30
The template SO40 was does not seem as a website created order, please try SO39

Please excuse the typos and spelling mistakes
Sent from Samsung Note 10
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by pedrobaeza** [comment] 2020-03-01 11:42
OK, reproduced the problem and investigated a bit, and the problem is that the code viewer is not presenting whole code!! See the diff of the original code (left - pasted from source code), and the code that the template editor shows (right):

![Selección_066](https://user-images.githubusercontent.com/7165771/75624983-eeb2e400-5bb9-11ea-9528-85721953a4e6.png)

@mart-e this one is serious, as this is not a problem only with HTML editor, but a general problem. #45633 may fix it?

**Comment by Wiserby** [comment] 2020-03-11 12:05
Had the same issue on the live project when noticed a bigger than usual amount of abandoned carts, thankfully website doesn't have a lot of visitors (broken mail template cancels the transaction and order ends up "not paid").
`Wysiwyg` messes the code when Preview button is clicked since action also saves the code before showing the look and you end up with a bad template.
`loop.cycle` and `line` end up outside the loop, hence the reason for this bug.

**Comment by pedrobaeza** [comment] 2020-03-11 16:02
@tde-banana-odoo maybe you can check this or ping the proper person for checking it

**Comment by tde-banana-odoo** [comment] 2020-03-11 16:34
Indeed having jinja commands between tr and td is generally an issue if you try to edit template as they will be moved outside of tr / td.

**Comment by tde-banana-odoo** [comment] 2020-03-18 14:59
Jinja is very easy to fix ... WIP fix at https://github.com/odoo/odoo/pull/47934 ^^

**Closed** 2020-03-20 12:42 UTC
Labels: 13.0, Confirmed

**Comment by TTPBruce** [comment] 2024-03-12 12:34
This problem still exists in Odoo 15 to this day!
