### ISSUE TITLE
[13.0] Constrains misbehave in delegation inheritance

### ISSUE THREAD

**Issue by ngoctrinh-viindoo** [odoo/odoo#54260] opened 2020-07-09 09:55 UTC
**Impacted versions:**
13.0

**Steps to reproduce:**

Create the following two models:

```python
class SampleA(models.Model):
    _name = 'sample.a'

    x = fields.Integer()
    y = fields.Integer()

    @api.constrains('x', 'y')
    def _check_xy(self):
        for r in self:
            if r.x > r.y:
                raise Exception()

class SampleB(models.Model):
    _name = 'sample.b'
    _inherits = {'sample.a': 'a_id'}

    a_id = fields.Many2one('sample.a', required=True)
```

and execute the following code:

```python
b = self.env['sample.b'].create({
            'x': 1,
            'y': 2
})
b.write({
            'x': 3,
            'y': 4
})
```

**Current behavior:**
The exception in the constrains method `_check_xy()` is raised because `x` and `y` are written separatetly that trigger the constrains method two times with values:

1. x = 3, y = 2 (raise error)
2. x = 3, y = 4

**Expected behavior:**
No exception is raise. The constrains method is called one time.

**Comment by pedrobaeza** [comment] 2020-07-09 10:00
That's not the reason, but there are 2 models involved, and the method is executed once per model.

Closing as no valid.

**Closed by pedrobaeza** 2020-07-09 10:00 UTC

**Comment by ngoctrinh-viindoo** [comment] 2020-07-09 14:53
@pedrobaeza Could you please explain in more detail? I don't understand what you mean in the sentence  `the method is executed once per model`.  I tested with Odoo 12 and it works as expected, the issue occurs with Odoo 13.

**Comment by pedrobaeza** [comment] 2020-07-09 14:56
The constraint is check for model `sample.a` and another for `sample.b`.

**Comment by HoangVanNhat-odoo** [comment] 2020-07-09 15:05
@ngoctrinh-viindoo Can I know the result of example 2.x = 3, y = 4 did it raise error again?

**Comment by HoangVanNhat-odoo** [comment] 2020-07-09 15:12
@ngoctrinh-viindoo Might you discribe the issure wrong? the example 1.x = 3, y = 2 (raise error) that is expectable.
But the problem is in example 2.x = 3, y = 4  the exception still raise, isn't it?

**Comment by ngoctrinh-viindoo** [comment] 2020-07-09 15:44
@HoangVanNhat-odoo It didn't even run to the second time because the exception was raised in the first time call to the constrains method. The problem is when executing the `write`:
```
b.write({
            'x': 3,
            'y': 4
})
```
The record of the parent model `same.a` should be updated in one call to `write` that triggers only one call to the constrains method. However, in Odoo 13, two `write` are called to update `x`, then `y` separately:

1. The first `write`: `x` is updated first with the new value (3) while `y` is still in old value (2) => the contrains method is called with x = 3, y = 2 instead of x = 3, y = 4.
2. The second `write`: `y` will be updated with the new value (4) but this will not be excuted because the exception was raised in the first call.

@pedrobaeza. Look at the code to update fields of the parent in delegation inheritance
https://github.com/odoo/odoo/blob/4f7981f80fb55ab4bf8b30d137e45b4fda4013cd/odoo/models.py#L3570

```python
for fields in determine_inverses.values():
                # inverse records that are not being computed
                try:
                    fields[0].determine_inverse(real_recs)
                except AccessError as e:
                    if fields[0].inherited:
                        description = self.env['ir.model']._get(self._name).name
                        raise AccessError(
                            _("%(previous_message)s\n\nImplicitly accessed through '%(document_kind)s' (%(document_model)s).") % {
                                'previous_message': e.args[0],
                                'document_kind': description,
                                'document_model': self._name,
                            }
                        )
                    raise
```
I think the issue is caused by fields in the `determine_inverses` are updated one by one instead of a bulk update.

**Comment by HoangVanNhat-odoo** [comment] 2020-07-13 09:41
@ngoctrinh-viindoo I think we should reopen a issure, maybe they misunderstand your issure description. There is real issure here!

**Comment by matof** [comment] 2020-09-09 09:00
I also think this really is problem. Try to create inherited model for calendar.event. Create event with valid start and stop datetimes where start is before stop. Then try to write new start and stop on inherited model while start is before stop but new start is after old (actual) stop. Exception is raised with message:

The ending date and time cannot be earlier than the starting date and time.

It seems problem is in code for updating inherited fields as written above by @ngoctrinh-viindoo 

@pedrobaeza Could you check it again please? Thanks. Or at least say us how we should save new values for inherited model.

**Comment by pedrobaeza** [comment] 2020-09-09 09:50
Please pass a module + test showcasing the problem

**Comment by matof** [comment] 2020-09-09 10:42
Attached whole module for test the bug.
[inherit_bug.zip](https://github.com/odoo/odoo/files/5194543/inherit_bug.zip)

You can also see the problem in this video:
http://couz.sk/calendar_bug.mp4

Inherited model looks like this:
```
from odoo import models, fields


class CalendarExt(models.Model):
    _name = 'calendar.ext'
    _description = 'Calendar extension'
    _inherits = {'calendar.event': 'event_id'}

    extra = fields.Char(string='Extra')
    event_id = fields.Many2one('calendar.event', ondelete='restrict', required=True)
```

**Comment by pedrobaeza** [comment] 2020-09-09 13:58
I don't see the unit test in the module exercising the bug you are mentioning.

**Comment by matof** [comment] 2020-09-10 06:10
Added unit test
[inherit_bug.zip](https://github.com/odoo/odoo/files/5199474/inherit_bug.zip)
