### ISSUE TITLE
Odoo 9 Public and Portal 500: Internal Server Error on Product Pages.

### ISSUE THREAD

**Issue by stephenunclejunks** [odoo/odoo#14110] opened 2016-11-02 18:31 UTC
Hey Guys,

While I was working yesterday, my whole e-commerce broke, I think it is due to Public and Portal User Rights are not set correctly, If a public or portal user try to access an individual product page on our website it gives a white screen with 500: Internal Server Error, but if I give users standard settings that do not have the rights of Portal or Public User, the product pages on the website load perfectly. Hopefully one of you guys can guide me in the right direction to fix this, since our e-commerce has been down for 24 hours now and we are losing money!

From research I've done a lot of people with a similar error were saying it was due to werkzeug not being installed, I have verified this, and have version 0.9.1 currently on the server.

I'm running Bitnami Odoo 9.0.20160620-2 via Google Cloud Platform.

Here is the Error that populates from the console:

2016-11-02 17:48:40,675 29971 ERROR bitnami_openerp openerp.addons.website.models.ir_http: 500 Internal Server Error:

Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/addons/website/models/ir_http.py", line 243, in _handle_exception
    response = super(ir_http, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/addons/base/ir/ir_http.py", line 157, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/http.py", line 784, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/addons/base/ir/ir_http.py", line 182, in _dispatch
    result = request.dispatch()
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/http.py", line 843, in dispatch
    r = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/http.py", line 319, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/http.py", line 312, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/http.py", line 962, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/addons/website_sale/controllers/main.py", line 301, in product
    rating_ids = Rating.search(cr, uid, [('message_id', 'in', product.website_message_ids.ids)], context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/fields.py", line 829, in __get__
    self.determine_value(record)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/fields.py", line 927, in determine_value
    record._prefetch_field(self)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/models.py", line 3298, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/models.py", line 3228, in read
    self._read_from_database(stored, inherited)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/models.py", line 3419, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/osv/fields.py", line 802, in get
    records = comodel.search(domain, limit=self._limit)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/addons/calendar/calendar.py", line 1770, in search
    return super(mail_message, self).search(cr, uid, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/models.py", line 1658, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/addons/website_mail/models/mail_message.py", line 56, in _search
    context=context, count=count, access_rights_uid=access_rights_uid)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/addons/mail/models/mail_message.py", line 632, in _search
    count=False, access_rights_uid=access_rights_uid)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/models.py", line 4764, in _search
    query = self._where_calc(cr, user, args, context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/models.py", line 4535, in _where_calc
    e = expression.expression(cr, user, domain, self, context)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/osv/expression.py", line 644, in __init__
    self.parse(cr, uid, context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/osv/expression.py", line 875, in parse
    right_ids = comodel.search(cr, uid, [(path[1], operator, right)], context=dict(context, active_test=False))
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/models.py", line 1658, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/models.py", line 4765, in _search
    self._apply_ir_rules(cr, user, query, 'read', context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/models.py", line 4590, in _apply_ir_rules
    rule_where_clause, rule_where_clause_params, rule_tables = rule_obj.domain_get(cr, uid, self._name, mode, context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/addons/base/ir/ir_rule.py", line 133, in domain_get
    dom = self._compute_domain(cr, uid, model_name, mode)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in _compute_domain
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/tools/cache.py", line 85, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/addons/base/ir/ir_rule.py", line 112, in _compute_domain
    rule_domain = self.read(cr, uid, [rule.id], ['domain'])[0]['domain']
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/models.py", line 3193, in read
    result = BaseModel.read(records, fields, load=load)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/models.py", line 3228, in read
    self._read_from_database(stored, inherited)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/models.py", line 3419, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/osv/fields.py", line 1495, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/addons/base/ir/ir_rule.py", line 35, in _domain_force_get
    res[rule.id] = expression.normalize_domain(eval(rule.domain_force, eval_context))
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/tools/safe_eval.py", line 296, in safe_eval
    c = test_expr(expr, _SAFE_OPCODES, mode=mode)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/tools/safe_eval.py", line 153, in test_expr
    code_obj = compile(expr, "", mode)
  File "<string>", line 1
    [('internal', '=', False]
                            ^
SyntaxError: unexpected EOF while parsing

**Comment by JKE-be** [comment] 2016-11-03 09:09
Hello,

I don't know from where this rule comes, but it is wrong ! `[('internal', '=', False]` ==> `[('internal', '=', False)]`

If it is not a bug reproducible on runbot, please use forum for this kind of question. This thread is the bug tracker of Odoo.

I close it, but I keep an eye on this thread, so let me know if updating the rule solves your problem ...

**Closed by JKE-be** 2016-11-03 09:09 UTC

**Comment by stephenunclejunks** [comment] 2016-11-05 15:28
@JKE-be Wow, I can't believe I overlooked that syntax error, but Yes that was what resolved my issue. Thank you for pointing that out.
