### ISSUE TITLE
Bug in Aged payables report OE

### ISSUE THREAD

**Issue by elevationO** [odoo/odoo#10761] opened 2016-02-03 19:47 UTC
When adding an aged payable that is 60 or 90 days the report shows the amount for 90/60/30 and totals that repeated amount resulting in an incorrect amount.

$622.46 is the correct total for A/P but $1947.96 is displayed.

![screen shot 2016-02-03 at 11 22 52 am](https://cloud.githubusercontent.com/assets/8355352/12794833/e8e20e2c-ca6b-11e5-9622-9595bd87d67a.png)

**Comment by elevationO** [comment] 2016-02-06 17:29
This same problem exists in A/R as well.

**Comment by elicoidal** [comment] 2016-06-30 08:14
also impacted

**Comment by csnauwaert** [comment] 2018-02-28 12:36
Hello,

Seems to me that this issue has been fixed as I can't reproduce it on the latest v9.0, therefore I'm closing this issue, if this is not the case, feels free to comment so that I can reopen it.

Best regards.

**Closed by csnauwaert** 2018-02-28 12:36 UTC
Labels: 9.0, Accounting
