### ISSUE TITLE
Checkout's Company name write on wrong field

### ISSUE THREAD

**Issue by hurrinico** [odoo/odoo#12541] opened 2016-06-22 15:09 UTC
Impacted versions: 8.0, 9.0

Steps to reproduce: Create a user,
                                In user's related partner associate a parent_id and set street and street2,
                                 Make an order on website with created user,
                                 On Checkout as Company's name i see parent_id name,
                                 Validate Checkout
                                 Go check partner's value

Current behavior: What you set in Checkout's Company Name is in partner's street field

Expected behavior: What you set in Checkout's Company Name will not be in partner's street field
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment] 2016-06-23 06:14
@JKE-be can you give @hurrinico a little bit more information about why it won't be fixed?
Also, if it is not fixed we can probably close the issue too?

**Comment by JKE-be** [comment] 2016-06-23 08:57
Because it is a duplicate of https://github.com/odoo/odoo/issues/2541

**Closed by JKE-be** 2016-06-23 08:57 UTC
Labels: wontfix
