### ISSUE TITLE
[9.0] Strange access error on `res.company` under multi-company setting

### ISSUE THREAD

**Issue by yostashiro** [odoo/odoo#11018] opened 2016-02-19 11:00 UTC
Impacted versions: 9.0

Steps to reproduce:
- Enable multi-company.
- Create a new company (other than the default one)
- Create a user who belongs to the new company
- Login with the user and go to `Sales > Sales > Products`

Current behavior:
- Access error shows:

```
The requested operation cannot be completed due to security restrictions. Please contact your system administrator.

(Document type: res.company, Operation: read)
```

![image](https://cloud.githubusercontent.com/assets/7766939/13173789/7ec2b358-d73a-11e5-901d-30976df2dc82.png)

Expected behavior:
- There should be no such error.

**Comment by DidierLACOMBE** [comment] 2016-02-20 07:47
[Unable to read res.company after creating new admin user in company B.pdf](https://github.com/odoo/odoo/files/139041/Unable.to.read.res.company.after.creating.new.admin.user.in.company.B.pdf)

**Comment by jasadmoozhiyan** [comment] 2016-03-27 07:43
Same for me also...

**Comment by n37r06u3** [comment] 2016-06-28 04:49
Same for me also...

**Comment by Yenthe666** [comment] 2018-01-16 10:16
Hi @yostashiro,

Thanks a lot for your bug report.
I've just tried to reproduce this. The new company:
![image](https://user-images.githubusercontent.com/6352350/34983636-821fccc2-faae-11e7-8bae-73c5bae12dde.png)

The new user (assigned to the new company):
![image](https://user-images.githubusercontent.com/6352350/34983627-7a9dae88-faae-11e7-927c-e9a62e0c0068.png)

Going to Sales > Sales > Products with the new user:
![image](https://user-images.githubusercontent.com/6352350/34983681-9c438a08-faae-11e7-829a-acab3aa910a6.png)

It looks like this has been fixed in the meanwhile.
Please update your Odoo to the latest source code in order to fix this.

Regards,
Yenthe

**Closed by Yenthe666** 2018-01-16 10:16 UTC
Labels: 9.0
