### ISSUE TITLE
[12.0][BUG] hr_holidays: create_date is a datetime already

### ISSUE THREAD

**Issue by alexey-pelykh** [odoo/odoo#28186] opened 2018-10-26 09:38 UTC
https://github.com/odoo/odoo/blob/25e82a5c6837c6b55478222942038bbcb3a06a66/addons/hr_holidays/models/hr_leave_allocation.py#L169

**Comment by pedrobaeza** [comment] 2018-10-26 09:44
This is better to put the PR fixing it directly, as you have the skills for that :wink:

**Comment by Elkasitu** [comment] 2018-10-26 11:33
`Datetime.from_string` is an alias for `Datetime.to_datetime` which accepts almost anything that can represent a date/datetime as input and returns a `datetime.datetime` object.

While the statement is useless, it is not blocking (i.e. not a bug), unless you were able to get a traceback or experienced data loss from this?

**Comment by Yenthe666** [comment] 2018-10-26 15:04
Could be an improvement for master though? ;)

**Comment by Elkasitu** [comment] 2018-10-26 15:20
Sure, but for cleanups I'd rather have them done either in batch like at #27599 or as a part of a refactoring of the surrounding code.

Otherwise you end up with a lot of noise in the commit history

**Comment by mart-e** [comment] 2018-10-31 09:42
Closing as not a bug, it is just code cleanup.
If this code does introduce a regression, please let us know and we can reopen.

**Closed by mart-e** 2018-10-31 09:42 UTC
Labels: 12.0, Services
