### ISSUE TITLE
[11.0] Error on sending invoice by email

### ISSUE THREAD

**Issue by livingdeadfr** [odoo/odoo#35088] opened 2019-07-23 07:47 UTC
Impacted versions:11

Steps to reproduce:send invoice by email, module invoicing

Current behavior:
Sending invoice by email return the following error : 
Erreur:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/wizard/mail_compose_message.py", line 194, in send_mail_action
    return self.send_mail()
  File "/usr/lib/python3/dist-packages/odoo/addons/website_sale/models/mail_compose_message.py", line 21, in send_mail
    return super(MailComposeMessage, self).send_mail(auto_commit=auto_commit)
  File "/usr/lib/python3/dist-packages/odoo/addons/sale/wizard/mail_compose_message.py", line 17, in send_mail
    return super(MailComposeMessage, self).send_mail(auto_commit=auto_commit)
  File "/usr/lib/python3/dist-packages/odoo/addons/account/models/account_invoice.py", line 1858, in send_mail
    return super(MailComposeMessage, self).send_mail(auto_commit=auto_commit)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/wizard/mail_compose_message.py", line 258, in send_mail
    **mail_values)
  File "/usr/lib/python3/dist-packages/odoo/addons/rating/models/mail_thread.py", line 14, in message_post
    message = super(MailThread, self).message_post(body=body, subject=subject, message_type=message_type, subtype=subtype, parent_id=parent_id, attachments=attachments, content_subtype=content_subtype, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 1916, in message_post
    new_message = MailMessage.create(values)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_message.py", line 795, in create
    user_signature=self.env.context.get('mail_notify_user_signature', True))
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_message.py", line 883, in _notify
    ])._notify(self, force_send=force_send, send_after_commit=send_after_commit, user_signature=user_signature)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/res_partner.py", line 190, in _notify
    new_emails, new_recipients_nbr = self._notify_send(fol_values['body'], fol_values['subject'], recipient_template_values['followers'], **base_mail_values)
KeyError: 'body'

Expected behavior:

Should send the invoice by email

It seems that the current fol_values['body'] is not defined, but the fol_values['body_html'] is available and work fine. 

Thanks for your help.

Regards

David

**Comment by pedrobaeza** [comment] 2019-07-23 07:49
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Yenthe666** [comment] 2019-08-17 12:10
Hi there,

Since we haven't had any feedback on our questions and are not able to reproduce this issue we're closing it.
If you still face this issue then please add more information and we'll reopen your issue.

Regards,
Yenthe

**Closed by Yenthe666** 2019-08-17 12:10 UTC
Labels: Need information
