### ISSUE TITLE
Can I use odoo 10 with mongodb using docker?

### ISSUE THREAD

**Issue by NaziburR** [odoo/odoo#17988] opened 2017-07-04 04:07 UTC
Impacted versions: 

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by lukebranch** [comment] 2017-07-04 05:39
@NaziburR 

What do you want to use MongoDB for with Odoo? Is it session storage?

Odoo requires PostgreSQL, as it's fully ACID compliant. MongoDB is not ACID compliant.

**Comment by Yenthe666** [comment] 2017-07-04 06:00
Hi @NaziburR,

To further expand on this: by default you won't be able to use Odoo with MongoDB. You would have to write an own wrapper that connects to the MongoDB database and handles all queries / API calls etc so this is not something trivial to do.
You can however use Odoo on Docker (you can find the docker templates here https://github.com/odoo/docker).
I'm closing this report as it is not a bug but a question. The Github issue tracker is only for bugs in the official code. These questions belong on the Help forum (http://odoo.com/help).

Regards,
Yenthe

**Closed by Yenthe666** 2017-07-04 06:00 UTC
