### ISSUE TITLE
[9.0] hr_payroll_account - Journal Items wrong allocated -> [Solution inside]

### ISSUE THREAD

**Issue by elperrofarelo** [odoo/odoo#9096] opened 2015-10-16 04:38 UTC
All salary lines are allocated after confirm the pay slip in journal as a Debit, although the salary rule has only a Credit Account defined and no Debit Account.

The Bank Adjustment Entry is therefore wrong calculated.

![1](https://cloud.githubusercontent.com/assets/9564408/10533962/82144c9c-73d0-11e5-9035-fa7a1a525df8.jpg)
![2](https://cloud.githubusercontent.com/assets/9564408/10533963/86009c5c-73d0-11e5-94f1-208800652a0d.jpg)

**Comment by elperrofarelo** [comment] 2015-10-29 04:21
Credit and debit are wrong calculated in hr_payslip_account
Ist:
                if credit_account_id:
                    credit_line = (0, 0, {
                         'name': line.name,
                        'partner_id': hr_payslip_line_pool._get_partner_id(cr, uid, line, credit_account=True, context=context),
                        'account_id': credit_account_id,
                        'journal_id': slip.journal_id.id,
                        'date': date,
                        'debit': amt < 0.0 and -amt or 0.0,
                        'credit': amt > 0.0 and amt or 0.0,
                        'analytic_account_id': line.salary_rule_id.analytic_account_id and line.salary_rule_id.analytic_account_id.id or False,
                        'tax_line_id': line.salary_rule_id.account_tax_id and line.salary_rule_id.account_tax_id.id or False,
                    })

Solution:
                        'credit': amt < 0.0 and -amt or 0.0,
                        'debit': amt > 0.0 and amt or 0.0,
Debit and Credit must be changed

**Comment by jaredkipe** [comment] 2016-03-20 20:34
I think you will want to make the value negative (meaning the total is negative, so either rate or amount need to be negative) on the payslip line / rule.  Then only assign a debit account.

You probably want to give your NET rule a credit account, so that you won't have a label 'Adjustment Entry' and it will take only what NET actually evaluates to.

When in doubt, try reading through the localizations (i.e. l10n_be_hr_payroll and l10n_be_hr_payroll_account).

**Comment by elperrofarelo** [comment] 2016-03-23 04:54
We are talking about a financial matter. If I define in a salary rule a credit account I wanted to see in journal items as a a credit (and the same for debit).
But in any case I can always modify my salary rules

**Comment by elperrofarelo** [comment] 2016-03-23 06:20
Hi. I've tried to change in salary rules credit and debit and it's not working for the accounting.
The only solution is the first proposed. If you want check please in hr_payslip_account some lines before and you see that credit and debit are defined in the same way that I propose:
                if debit_account_id:
                    debit_line = (0, 0, {
                        'name': line.name,
                        'partner_id': hr_payslip_line_pool._get_partner_id(cr, uid, line, credit_account=False, context=context),
                        'account_id': debit_account_id,
                        'journal_id': slip.journal_id.id,
                        'date': date,
                        'debit': amt > 0.0 and amt or 0.0,
                        'credit': amt < 0.0 and -amt or 0.0,
                        'analytic_account_id': line.salary_rule_id.analytic_account_id and line.salary_rule_id.analytic_account_id.id or False,
                        'tax_line_id': line.salary_rule_id.account_tax_id and line.salary_rule_id.account_tax_id.id or False,
                    })

**Comment by jaredkipe** [comment] 2016-03-23 15:16
I am trying to help you, but you are making unfounded assumptions and then trying to change the code to meet what you are trying to achieve.

Lets say that you want the following.

account, debit, credit
Salary Expense, 1000, 0
Some Tax/withholding, 0, 100
Salary Payable, 0, 900

Then your rules better calculate like this.
GROSS 1000 with debit account "Salary Expense"
SOMETAX -100 with debit account "Some Tax/withholding"
NET 900 with credit account "Salary Payable"

Now, if you're saying that you want something more like this...
Salary Expense, 1000, 0
Some Tax, 0, 100
Some Tax Expense, 100, 0
Salary Payable, 0, 900

Then you'll want rules that calculate like this.
GROSS 1000 with debit account "Salary Expense"
SOMETAX -100 with debit account "Some Tax", credit account "Some Tax Expense"
NET 900 with credit account "Salary Payable"

For this one, you could of course reverse the accounts and make the calculation positive.  But if you ware trying to 'reduce' the total payable, you should do it like the first example.

**Comment by elperrofarelo** [comment] 2016-03-24 08:16
Thanks for your answers. But it's only a accounting matter, about debit and credit. 
I think it's more easy to understand to everybody if you define a salary rule with a credit account, this rule is going to appeat in the journal entry as a credit (and not as debit)

**Comment by pedrobaeza** [comment] 2018-04-06 00:53
Is this still reproducible in latest v11 version?

**Comment by Yenthe666** [comment] 2018-04-06 15:11
Or in the latest 9.0 😉

**Comment by jaredkipe** [comment] 2018-04-07 19:14
It is reproducible in every version of Odoo I have ever used including 9-11.  **But I don't think it should be 'fixed'...**

The issue here is about expectation more than a defect in implementation.
If you have a salary rule and you give it a debit account AND a credit account then:

1. If your rule evaluates to a positive result, then the debit account is debited and the credit account is credited.

2. If your rule evaluates to a negative result, then the credit account is debited and the debit account is credited.

In general, only 'company paid' amounts will have both a debit and credit account. Why? Because most rules only include one account side because the intention is to 'take from' or 'give to' a category.... most of those categories are already effectively defining both sides of the accounting, and you're merely stepping into the middle to increase or decrease these amounts and provide GL counterparts for your changes.

What happens when you only want one account? The same exact thing without whichever account you didn't want. Make no mistake, don't discard the account based on preconceived notions of if you want a `debit` or you want a `credit`, discard the actual GL account that you are not trying to directly influence.


Example:
======

Let us imagine a tax on the employee's wages as it is the most common salary rule.  We can imagine this as a debit to `Employee Net Payable` and a credit to `Tax Agency Payable`.  If this calculation was done in isolation (e.g. in the `Company Part` category), then we could compute it as a positive result and we would be done and everything would behave fine.  

However, if calculating our rule would result in a negative (i.e. typical DED rule), then the implementor would switch the accounts so that the rule's 'debit account' would be `Tax Agency Payable` and the 'credit account' would be `Employee Net Payable` (per `2.` above).  

Keep in mind, if we're putting this negative amount into the DED category, then by the time the Net rule runs (typical Net rules have a 'credit account' of some `Payable` type) you will have already reduced the amount that is going to be credited to `Employee Net Payable`, thus to make your 'accounting' correct you would drop the `Employee Net Payable` account, leaving you with only ... **a 'debit account' of `Tax Agency Payable`**.

------

Why is this confusing?

It may be counter intuitive, but it is a direct result of the flexible nature of the calculations the Payroll system provides.

The original screenshot deceptively didn't show how the rule is calculated, nor did it show the post evaluation results of the entire salary slip. This context is extremely important. Nobody can glance at only the `Accounting` tab of a rule and accurately predict what will happen when the entire payroll journal entry is generated. However, someone armed with both the accounting tab and the rule's evaluated result (and sign), can predict that rule's accounting outcome on the payroll journal entry.

Changing this behavior would effectively break every salary rule that is intended to evaluate to a negative number. That includes stock ones like those in `l10n_be_hr_payroll_account`

**Comment by pedrobaeza** [comment] 2018-04-09 09:54
Thanks for the huge explanation, @jaredkipe. Based on this, I think we can close the issue.

**Closed by pedrobaeza** 2018-04-09 09:54 UTC
Labels: 9.0, Services
