### ISSUE TITLE
[BUG] Kit bom with the service component caused the sale order Delivered quantity can't be updated

### ISSUE THREAD

**Issue by AndyChen1124** [odoo/odoo#60335] opened 2020-10-20 08:45 UTC
Impacted versions: 
N/A

Steps to reproduce:
1) create a Storable Product "product kit with service"
2) add one kit BOM for the product "product kit with service", and the bom contains one service component
3) create the sale order with the product "product kit with service"
4) for the delivery order it just generated the Storable Product list for operations, there is no service component
5) validate/done the delivery order
6) the sale order line delivered quantity is 0

Current behavior:
the sale order line delivered quantity is 0

Expected behavior:
the sale order line delivered quantity should be updated as the delivered kit quantity

Video/Screenshot link (optional):
N/A

**Comment by pedrobaeza** [comment] 2020-10-20 09:34
This combination is not supported, so this is not a bug, but something not implemented. Closing due to this. It's also difficult to measure how a service is delivered, so this can't be put also as a wishlist without a finer proposition.

**Closed by pedrobaeza** 2020-10-20 09:34 UTC
