### ISSUE TITLE
when we installed website module, it  gives the error 

### ISSUE THREAD

**Issue by meghshyamodoo** [odoo/odoo#27485] opened 2018-10-07 14:21 UTC
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2018-10-07 15:35
Which error?

**Comment by meghshyamodoo** [comment] 2018-10-07 15:53
The style compilation failed, see the error below. Your recent actions may be the cause, please try reverting the changes you made.

Error: unterminated interpolant inside string constant "https://fonts.googleapis.com/css?family=#{unquote
        on line 2698 of stdin
>> @each $-number in $-font-numbers {
   ------------------------^
This error occured while compiling the bundle 'web.assets_frontend' containing:
    - /web/static/lib/bootstrap/scss/_functions.scss
    - /web/static/lib/bootstrap/scss/_mixins.scss
    - /web/static/src/scss/utils.scss
    - /web/static/src/scss/bs_mixins_overrides.scss
    - /web/static/src/scss/primary_variables.scss
    - /web_editor/static/src/scss/web_editor.variables.scss
    - /mail/static/src/scss/variables.scss
    - /portal/static/src/scss/primary_variables.scss
    - /website/static/src/scss/primary_variables.scss
    - /website/static/src/scss/options/colors/user_color_palette.scss
    - /website/static/src/scss/options/colors/user_theme_color_palette.scss
    - /website_blog/static/src/scss/primary_variables.scss
    - /web/static/src/scss/secondary_variables.scss
    - /website/static/src/scss/secondary_variables.scss
    - /web/static/src/scss/bootstrap_overridden_frontend.scss
    - /web_editor/static/src/scss/bootstrap_overridden.scss
    - /portal/static/src/scss/bootstrap_overridden.scss
    - /website/static/src/scss/bootstrap_overridden.scss
    - /web/static/src/scss/import_bootstrap_part1.scss
    - /web/static/src/scss/bs_mixins_overrides.scss
    - /web/static/src/scss/import_bootstrap_part2.scss
    - /web/static/lib/tempusdominus/tempusdominus.scss
    - /web/static/src/scss/navbar_mobile.scss
    - /web_editor/static/src/scss/web_editor.common.scss
    - /portal/static/src/scss/bootstrap.extend.scss
    - /portal/static/src/scss/portal.scss
    - /payment/static/src/scss/portal_payment.scss
    - /payment/static/src/scss/payment_form.scss
    - /sale/static/src/scss/sale_portal.scss
    - /project/static/src/scss/portal_rating.scss
    - /website/static/src/scss/website.scss
    - /website/static/src/scss/website.ui.scss
    - /website/static/src/scss/website.zoomodoo.scss
    - /website_mail/static/src/css/website_mail.scss
    - /website_rating/static/src/scss/website_rating.scss
    - /website_form/static/src/scss/website_form.scss
    - /website_sale/static/src/scss/website_sale.scss
    - /website_sale/static/src/scss/website_mail.scss
    - /website_sale/static/src/scss/website_sale_frontend.scss
    - /sale/static/src/scss/sale_portal.scss
    - /sale/static/src/scss/product_configurator.scss
    - /website_sale/static/src/scss/website_sale_options.scss
    - /mail/static/src/scss/abstract_thread_window.scss
    - /mail/static/src/scss/thread.scss
    - /im_livechat/static/src/scss/im_livechat.scss
    - /website_blog/static/src/scss/website_blog.scss
    - /website_slides/static/src/scss/website_slides.scss

**Comment by sswapnesh** [comment] 2018-10-07 16:57
Looks Duplicate of #27483
Please install `libsass` library (sudo apt install python3-libsass)

**Comment by pedrobaeza** [comment] 2018-10-07 17:18
Indeed, closing.

**Closed by pedrobaeza** 2018-10-07 17:18 UTC

**Comment by Akashshere19** [comment] 2023-01-16 13:09
given above error in ubuntu 22.04 and odoo14. I have installed libsass ==0.22.0 and all requirements.txt
