### ISSUE TITLE
purchase: TypeError: not enough arguments for format string (when canceling)

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#27307] opened 2018-09-28 16:39 UTC
### Impacted versions:
11.0

### Steps to reproduce:
- Try to cancel a purchase.order with pickings on state == 'done':

### Current behavior:
- Instead of giving the error to the user it crashes with the subject error in: https://github.com/odoo/odoo/blob/11.0/addons/purchase/models/purchase.py#L363 

**Note:** It seems obvious; but the only way I could manage to make this work was using `.format()`, with this old string formatting I can't make it work somehow. 

### Expected behavior:
Raised UserError

**Comment by gustavovalverde** [comment] 2018-09-28 16:40
cc: @pedrobaeza maybe there's something trivial here, but I'm not seeing it.

**Comment by pedrobaeza** [comment] 2018-09-28 18:29
I don't see any problem in the code. The problem should be in the translation, that includes more `%s`.

**Comment by sswapnesh** [comment] 2018-09-29 09:44
Hello @gustavovalverde 
I am not able to reproduce same on Runbot.
![3](https://user-images.githubusercontent.com/16624719/46244292-50d24d00-c3fa-11e8-8780-226a2a9b840b.png)

Tried with Other language too.
![3](https://user-images.githubusercontent.com/16624719/46244279-1ff21800-c3fa-11e8-8bbd-c7581bf2ddcb.png)

**Comment by pedrobaeza** [comment] 2018-09-29 09:46
Yeah, now it's more clear that it's a problem in the translation (I think he is using es_CR). Closing.

**Closed by pedrobaeza** 2018-09-29 09:46 UTC

**Comment by sswapnesh** [comment] 2018-09-29 09:55
Tried that and works well on Runbot.
![3 25](https://user-images.githubusercontent.com/16624719/46244379-e28e8a00-c3fb-11e8-82c1-2ce5a6f2f8a5.png)
