### ISSUE TITLE
Odoo wired, bug Infinite loop !!!

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#10577] opened 2016-01-21 12:16 UTC
In custom  module just added onchange method to some existing field. via xpath with attributes.

Then try to upgrade module with command lines.

2016-01-21 12:11:21,566 27666 INFO 9xxxxxx openerp.modules.loading: Modules loaded.
2016-01-21 12:11:21,573 27666 INFO 9xxxxxx openerp.addons.base.ir.ir_http: Generating routing map
2016-01-21 12:11:21,574 27666 INFO 9xxxxxx openerp.addons.base.ir.ir_http: Generating routing map
2016-01-21 12:11:21,574 27666 INFO 9xxxxxx openerp.addons.base.ir.ir_http: Generating routing map
2016-01-21 12:11:21,574 27666 INFO 9xxxxxx openerp.addons.base.ir.ir_http: Generating routing map
2016-01-21 12:11:21,574 27666 INFO 9xxxxxx openerp.addons.base.ir.ir_http: Generating routing map
2016-01-21 12:11:21,574 27666 INFO 9xxxxxx openerp.addons.base.ir.ir_http: Generating routing map
2016-01-21 12:11:21,575 27666 INFO 9xxxxxx openerp.addons.base.ir.ir_http: Generating routing map
2016-01-21 12:11:21,575 27666 INFO 9xxxxxx openerp.addons.base.ir.ir_http: Generating routing map
2016-01-21 12:11:21,575 27666 INFO 9xxxxxx openerp.addons.base.ir.ir_http: Generating routing map
2016-01-21 12:11:21,575 27666 INFO 9xxxxxx openerp.addons.base.ir.ir_http: Generating routing map
2016-01-21 12:11:21,575 27666 INFO 9xxxxxx openerp.addons.base.ir.ir_http: Generating routing map
2016-01-21 12:11:21,576 27666 INFO 9xxxxxx openerp.addons.base.ir.ir_http: Generating routing map
2016-01-21 12:11:21,576 27666 INFO 9xxxxxx openerp.addons.base.ir.ir_http: Generating routing map
2016-01-21 12:11:21,576 27666 INFO 9xxxxxx openerp.addons.base.ir.ir_http: Generating routing map
2016-01-21 12:11:21,576 27666 INFO 9xxxxxx openerp.addons.base.ir.ir_http: Generating routing map
2016-01-21 12:11:21,576 27666 INFO 9xxxxxx openerp.addons.base.ir.ir_http: Generating routing map
2016-01-21 12:11:21,576 27666 INFO 9xxxxxx openerp.addons.base.ir.ir_http: Generating routing map
2016-01-21 12:11:21,577 27666 INFO 9xxxxxx openerp.addons.base.ir.ir_http: Generating routing map
2016-01-21 12:11:21,577 27666 INFO 9xxxxxx openerp.addons.base.ir.ir_http: Generating routing map
2016-01-21 12:11:21,577 27666 INFO 9xxxxxx openerp.addons.base.ir.ir_http: Generating routing map
2016-01-21 12:11:21,577 27666 INFO 9xxxxxx openerp.addons.base.ir.ir_http: Generating routing map
2016-01-21 12:11:38,983 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (359)
2016-01-21 12:11:38,983 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (359)
2016-01-21 12:11:38,982 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (359)
2016-01-21 12:11:38,983 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (359)
2016-01-21 12:11:38,983 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (359)
2016-01-21 12:11:38,983 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (359)
2016-01-21 12:11:38,983 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (359)
2016-01-21 12:11:38,983 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (359)
2016-01-21 12:11:38,983 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (359)
2016-01-21 12:11:38,983 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (359)
2016-01-21 12:11:38,983 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (359)
2016-01-21 12:11:38,983 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (359)
2016-01-21 12:11:38,982 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (359)
2016-01-21 12:11:38,983 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (359)
2016-01-21 12:11:38,983 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (359)
2016-01-21 12:11:38,983 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (359)
2016-01-21 12:11:38,984 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (359)
2016-01-21 12:11:38,983 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (359)
2016-01-21 12:11:38,983 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (359)
2016-01-21 12:11:38,983 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (359)
2016-01-21 12:11:38,992 27666 INFO 9xxxxxx werkzeug: 127.0.0.1 - - [21/Jan/2016 12:11:38] "GET /web?debug= HTTP/1.1" 200 -
2016-01-21 12:11:39,035 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (360)
2016-01-21 12:11:39,064 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (360)
2016-01-21 12:11:39,074 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (360)
2016-01-21 12:11:39,077 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (360)
2016-01-21 12:11:39,081 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (360)
2016-01-21 12:11:39,086 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (360)
2016-01-21 12:11:39,088 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (360)
2016-01-21 12:11:39,086 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (360)
2016-01-21 12:11:39,090 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (360)
2016-01-21 12:11:39,103 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (360)
2016-01-21 12:11:39,102 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (360)
2016-01-21 12:11:39,101 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (360)
2016-01-21 12:11:39,106 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (360)
2016-01-21 12:11:39,102 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (360)
2016-01-21 12:11:39,110 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (360)
2016-01-21 12:11:39,111 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (360)
2016-01-21 12:11:39,110 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (360)
2016-01-21 12:11:39,117 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (360)
2016-01-21 12:11:39,121 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (361)
2016-01-21 12:11:39,123 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (360)
2016-01-21 12:11:39,132 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (360)
2016-01-21 12:11:39,191 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (361)
2016-01-21 12:11:39,198 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (361)
2016-01-21 12:11:39,211 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (361)
2016-01-21 12:11:39,213 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (361)
2016-01-21 12:11:39,214 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (361)
2016-01-21 12:11:39,211 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (361)
2016-01-21 12:11:39,215 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (361)
2016-01-21 12:11:39,213 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (361)
2016-01-21 12:11:39,219 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (362)
2016-01-21 12:11:39,226 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (361)
2016-01-21 12:11:39,220 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (361)
2016-01-21 12:11:39,229 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (361)
2016-01-21 12:11:39,225 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (361)
2016-01-21 12:11:39,229 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (361)
2016-01-21 12:11:39,243 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (361)
2016-01-21 12:11:39,245 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (361)
2016-01-21 12:11:39,252 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (361)
2016-01-21 12:11:39,251 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (361)
2016-01-21 12:11:39,254 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (361)
2016-01-21 12:11:39,257 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (361)
2016-01-21 12:11:39,298 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (362)
2016-01-21 12:11:39,304 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (362)
2016-01-21 12:11:39,304 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (362)
2016-01-21 12:11:39,308 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (362)
2016-01-21 12:11:39,309 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (362)
2016-01-21 12:11:39,311 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (362)
2016-01-21 12:11:39,315 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (362)
2016-01-21 12:11:39,317 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (362)
2016-01-21 12:11:39,328 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (362)
2016-01-21 12:11:39,330 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (362)
2016-01-21 12:11:39,327 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (362)
2016-01-21 12:11:39,329 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (362)
2016-01-21 12:11:39,336 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (362)
2016-01-21 12:11:39,343 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (362)
2016-01-21 12:11:39,347 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (362)
2016-01-21 12:11:39,349 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (362)
2016-01-21 12:11:39,357 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (362)
2016-01-21 12:11:39,362 27666 INFO 9xxxxxx openerp.sql_db: bad query: UPDATE "ir_attachment" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') W

Odoo really wired, Its seems I had face same issue in 7 and 8 too. but in 9 too.

What might be issue ?

**Comment by Yenthe666** [comment] 2016-05-23 12:28
Hi @tejastank,

I can (no longer) reproduce this issue.
I'm closing this since I cannot reproduce this, the report is a few months old and because I have no sample.
If you'd have an example module (or still face this problem) please let em know, I'll re-open this issue then.

Regards,
Yenthe

**Closed by Yenthe666** 2016-05-23 12:28 UTC

**Comment by debaetsr** [comment] 2016-08-08 10:29
I'm experiencing this too, especially when adding new modules. I notice a deadlock in postgresql.
