### ISSUE TITLE
Programming Error installing any module

### ISSUE THREAD

**Issue by yyuri** [odoo/odoo#6161] opened 2015-04-06 19:11 UTC
I get this error if I try to install any module:

`Traceback (most recent call last):
  File "/usr/lib64/python2.7/lib/python2.7/site-packages/odoo-8.0.post20150406-py2.7.egg/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib64/python2.7/lib/python2.7/site-packages/odoo-8.0.post20150406-py2.7.egg/openerp/http.py", line 567, in dispatch
    result = self._call_function(*_self.params)
  File "/usr/lib64/python2.7/lib/python2.7/site-packages/odoo-8.0.post20150406-py2.7.egg/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/usr/lib64/python2.7/lib/python2.7/site-packages/odoo-8.0.post20150406-py2.7.egg/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/usr/lib64/python2.7/lib/python2.7/site-packages/odoo-8.0.post20150406-py2.7.egg/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/usr/lib64/python2.7/lib/python2.7/site-packages/odoo-8.0.post20150406-py2.7.egg/openerp/http.py", line 796, in __call__
    return self.method(_args, *_kw)
  File "/usr/lib64/python2.7/lib/python2.7/site-packages/odoo-8.0.post20150406-py2.7.egg/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/usr/lib64/python2.7/lib/python2.7/site-packages/odoo-8.0.post20150406-py2.7.egg/openerp/addons/web/controllers/main.py", line 939, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib64/python2.7/lib/python2.7/site-packages/odoo-8.0.post20150406-py2.7.egg/openerp/addons/web/controllers/main.py", line 927, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/usr/lib64/python2.7/lib/python2.7/site-packages/odoo-8.0.post20150406-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib64/python2.7/lib/python2.7/site-packages/odoo-8.0.post20150406-py2.7.egg/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/usr/lib64/python2.7/lib/python2.7/site-packages/odoo-8.0.post20150406-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib64/python2.7/lib/python2.7/site-packages/odoo-8.0.post20150406-py2.7.egg/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/usr/lib64/python2.7/lib/python2.7/site-packages/odoo-8.0.post20150406-py2.7.egg/openerp/modules/registry.py", line 368, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib64/python2.7/lib/python2.7/site-packages/odoo-8.0.post20150406-py2.7.egg/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/usr/lib64/python2.7/lib/python2.7/site-packages/odoo-8.0.post20150406-py2.7.egg/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib64/python2.7/lib/python2.7/site-packages/odoo-8.0.post20150406-py2.7.egg/openerp/modules/loading.py", line 157, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/usr/lib64/python2.7/lib/python2.7/site-packages/odoo-8.0.post20150406-py2.7.egg/openerp/modules/module.py", line 290, in init_module_models
    obj.init(cr)
  File "/usr/lib64/python2.7/lib/python2.7/site-packages/odoo-8.0.post20150406-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib64/python2.7/lib/python2.7/site-packages/odoo-8.0.post20150406-py2.7.egg/openerp/addons/project/project.py", line 1354, in init
    """)
  File "/usr/lib64/python2.7/lib/python2.7/site-packages/odoo-8.0.post20150406-py2.7.egg/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/usr/lib64/python2.7/lib/python2.7/site-packages/odoo-8.0.post20150406-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column "h.date" must appear in the GROUP BY clause or be used in an aggregate function
LINE 9:                     h.date+generate_series(0, CAST((coalesce...
                            ^'

when I try to install any module in a clear instalation. I guess it's a postgresql problem, the point is, how I solve that?

**Comment by Tchevass** [comment] 2015-06-01 19:13
I get the same thing.
Odoo 8.0, Python 2.7.10, Postgres 8.4.20

**Comment by codingisacopingstrategy** [comment] 2015-12-02 18:04
Hello,

I get a similar error when I try to install applications.

I found what seems like a [related issue](https://github.com/odoo/odoo/issues/2954) that was fixed by upgrading to Postgres 9.1, but I’m running Postgres 9.4.5

~~~
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 256, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/module/module.py", line 447, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 256, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/module/module.py", line 495, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 157, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/module.py", line 290, in init_module_models
    obj.init(cr)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 256, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/project/project.py", line 1365, in init
    """)
  File "/usr/lib/python2.7/dist-packages/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column "h.date" must appear in the GROUP BY clause or be used in an aggregate function
LINE 9:                     h.date+generate_series(0, CAST((coalesce...
                            ^
~~~

**Comment by codingisacopingstrategy** [comment] 2015-12-02 18:04
FWIW, I’m running OpenERP version 8.0-20151202 from the Oodo Debian repo

**Comment by odony** [comment] 2017-06-30 16:06
This really seems to be a duplicate of #2954 indeed.
If you look at the [release notes of PG 9.1](https://www.postgresql.org/docs/9.1/static/release-9-1.html) you will see this new feature is described as follows:

> Allow non-GROUP BY columns in the query target list when the primary key is specified in the GROUP BY clause (Peter Eisentraut)
> 
> The SQL standard allows this behavior, and because of the primary key, the result is unambiguous.

This is further explained in [the documentation for GROUP BY](https://www.postgresql.org/docs/9.1/static/sql-select.html#SQL-GROUPBY) as of 9.1:

>  (...) When GROUP BY is present, it is not valid for the SELECT list expressions to refer to ungrouped columns **except within aggregate functions or if the ungrouped column is functionally dependent on the grouped columns**, since there would otherwise be more than one possible value to return for an ungrouped column. A functional dependency exists if **the grouped columns (or a subset thereof) are the primary key** of the table containing the ungrouped column.

If you look at [the query](https://github.com/odoo/odoo/blob/20dc8480006e92187f1be3b5c7c456fed79c5ace/addons/project/project.py#L1343-L1364), you will see that it uses `GROUP BY h.id`, so `h.date` is a functionnaly dependent column.
The only explanation is that you're not using PG 9.1 or later, which was required for OpenERP 8.

**Closed by odony** 2017-06-30 16:06 UTC
