### ISSUE TITLE
[14.4] Cannot add menu to the website

### ISSUE THREAD

**Issue by mshahbazi** [odoo/odoo#70915] opened 2021-05-17 18:08 UTC
Impacted versions: 14.4

Steps to reproduce: 
1. Install the website module
2. try to add a menu or mega menu

Current behavior:
Raises this error: Error: QWeb2: Template 'wysiwyg.widgets.link' not found

Expected behavior:
Should add the menu without error

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/6513072/118536051-7d306880-b760-11eb-8041-fecda3085583.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment] 2021-05-17 18:14
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Yenthe666** [comment] 2021-05-17 18:36
Honestly, it is 14.4 so there is no use in keeping it open. Either it is hosted on premise when you shouldn't be on a 14.x and it is your own issue or you are on odoo.com and then you have to open an OPW with Odoo :)

**Closed by Yenthe666** 2021-05-17 18:36 UTC
Labels: Need information

**Comment by mshahbazi** [comment] 2021-05-17 18:44
@pedrobaeza the screenshot has taken from runbot master.
@Yenthe666 please let me know how can I report the issues of the master branch?

Thanks

**Comment by Yenthe666** [comment] 2021-05-17 18:53
@mshahbazi tickets against the master version or in general not accepted. The branch changes all the time and fixes (plus breakages) are happening all the time too. It is only when it is close to a major release (e.g when we get 14.5) that it is considered in the last weeks or so.

**Comment by mshahbazi** [comment] 2021-05-17 18:59
Ok, thank you so much
