### ISSUE TITLE
POS card payment method

### ISSUE THREAD

**Issue by carlositurri** [odoo/odoo#33884] opened 2019-06-04 20:06 UTC
Impacted versions:
odoo v 11
Steps to reproduce:
Payment at the point of sale by bank card
Current behavior:
The field to enter the card code and cancel and apply buttons are displayed in disorder
Expected behavior:
The fields are in correct order
Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/11946302/58910098-b5108380-86e2-11e9-85b3-dd6114052315.png)

**Comment by pedrobaeza** [comment] 2019-06-06 07:29
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Ark74** [comment] 2019-07-05 18:56
@carlositurri  Is that a custom module?
Haven't seen that window before.

**Comment by Yenthe666** [comment] 2019-07-31 14:42
Hi there,

I'm closing this bug report as there has been no more feedback on the last question. We assume that the problem has been solved in the meanwhile. If this is not the case then don't hesitate to respond back (with feedback) and we'll reopen it.

Regards,
Yenthe

**Closed by Yenthe666** 2019-07-31 14:42 UTC
Labels: 11.0, Need information, Point of Sale
