### ISSUE TITLE
uninstalling module from res.config.settings is dangerous

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#6835] opened 2015-05-25 09:46 UTC
Originally reported by @guewen on launchpad (issue https://bugs.launchpad.net/openobject-server/+bug/1262172). I'm resubmitting here to help keeping track. 

---

In "Settings > Configuration" we have various section "Sales", "Purchases" and so on. In each section, we can find configuration options, usually checkboxes. Some of them change groups, some install modules.

Example:
"Settings > Configuration > General Settings" : The option "Activate the customer portal" installs the portal module.

And the reverse, when the checkbox is ticked and we untick it, the portal module is uninstalled.

This is very dangerous when people do not really realize what is happening underhand, especially since the columns of the uninstalled modules are dropped. But this is even more dangerous: the uninstallation also uninstalls all the dependencies and there is no warning (when we uninstall a module from the "Installed Modules" menu, there is a warning).

It can lead to serious damage on a database, when a user thinks is just activating / deactivating options.

**Comment by bealdav** [comment] 2015-05-25 10:11
Yes, unfortunately it happened on my customer instance. All delivery method managed by the module have been erased from sales and pickings.

**Comment by sbidoul** [comment] 2015-05-25 10:37
:+1:

**Comment by shahid139** [comment] 2015-05-25 10:42
[?]

**Comment by bealdav** [comment] 2015-05-25 15:26
Feel free to comment this proposal
https://github.com/OCA/server-tools/pull/171/files

**Comment by mart-e** [comment] 2015-05-26 11:17
Hello,

Isn't that fixed with the warning popup at 86c24265551920dd837703a7f058970676e62c24 ?
![screenshot from 2015-05-26 13-15-10](https://cloud.githubusercontent.com/assets/564822/7811268/4e0c981a-03a9-11e5-997a-0cb4e808c06a.png)

**Comment by bealdav** [comment] 2015-05-26 13:10
No because when you're responsible of the instance of your customer, you don't want that anybody jumping into any available PC with sufficient rights and erase production data. In production instance only administrator should be able to uninstall, Thanks

**Comment by rvalyi** [comment] 2015-05-26 13:23
@bealdav may be you should also see with @sebastienbeau, he had a patch so that when un-installing a module it doesn't drop the tables data (like before version 7). May be a good feature that can be bundled as a monkey patch in this module? If that's not monkey-patchable, may be a hook could be introduced in OCB so that this modules takes advantage of it? Just thinking...

**Comment by mart-e** [comment] 2015-05-26 13:39
Bug at lp:1262172 seems fixed with the warning (it was Antony suggestion at that time).
(Un)installing a module requires the "Administration/Settings" level that only few users should have (maybe only the admin).

We could add a second password (quite bothersome) or a message with bigger warning ("this will remove the data"). The issue is that, you can put as many red blinking warning as you want, people don't read warning messages !

Not dropping the tables could be a good feature but I don't think it should be the case by default (so if I reinstall, I get all the data back ?) and how would it work for modules adding only one column ?

**Comment by bealdav** [comment] 2015-05-26 13:47
@rvalyi yes, I've done this module after talked to Seb. Drop data is good to ensure to be clean between data and code. It's reliable for the job, and no problem for test database (exception to this rule could happen bugs). It doesn't hurt me. But for production we are not here to laugh. We can have huge damage. My module don't reinvent another password and it do the job.
Could make a review of it even if it feature is not accepted in the core ? Thanks

**Comment by hugues-michel** [comment] 2015-05-27 14:42
I confirm that. After creating a database for production, I lost six months of work because of it.
Thank you for resubmitting !

Another thing to know: Do not delete the objects that are created with a new database. For example item service (hide the product without removing it)

**Comment by pedrobaeza** [comment] 2018-04-03 22:57
This has been addressed in latest version (v12) with the uninstalling wizard that informs of the documents being removed, so I close it.

**Closed by pedrobaeza** 2018-04-03 22:57 UTC
Labels: Wishlist
