### ISSUE TITLE
[12.0][BUG] Datepicker start-of-week is not affected by locale editing

### ISSUE THREAD

**Issue by alexey-pelykh** [odoo/odoo#36450] opened 2019-09-05 08:28 UTC
1. Edit English locale in Odoo to change week_start to Monday (let's leave out reasoning for it)
2. Odoo calendar now starts on Monday, but datepicker still starts on Sunday, since it uses the unmodified locale settings.

Possible reason:
https://github.com/odoo/odoo/blob/4b8e0d82bb2463e9d5e3492f7014c89cdc41b5e7/addons/web/static/src/js/views/calendar/calendar_renderer.js#L370

Shouldn't here be a call to `datepickerLocale` https://github.com/odoo/odoo/blob/905e01921f3c3ef43ace6fc537d1d8c0d280002c/addons/web/static/lib/fullcalendar/js/fullcalendar.js#L10360 as well to configure the locale of datepicker with custom settings of Odoo?

**Comment by alexey-pelykh** [comment] 2019-09-05 08:30
Possibly related to https://github.com/odoo/odoo/commit/e7bbdf884fa113bda1c7dd9d16ac17ac6429a013 (ping @kebeclibre )

**Comment by alexey-pelykh** [comment] 2019-09-05 08:39
@aab-odoo if possible, give a hint on this, please

**Comment by kebeclibre** [comment] 2019-09-05 08:40
@alexey-pelykh 
I don't understand. Do you have a practical issue i.e. a use case ?
Besides, we don't modify our libraries

**Comment by alexey-pelykh** [comment] 2019-09-05 08:46
Thanks for such a swift reply! My usecase is:

1. Edit English locale in Odoo to change week_start to Monday (let's leave out reasoning for it)
2. For me, Odoo calendar now starts on Monday, but datepicker still starts on Sunday, since it uses the unmodified locale settings.

I've started looking around the sources where parameters are passed to the datepicker, and it's here:
https://github.com/odoo/odoo/blob/905e01921f3c3ef43ace6fc537d1d8c0d280002c/addons/web/static/lib/fullcalendar/js/fullcalendar.js#L10360

but this method is not called anywhere at all, so `dpOptions` are being set from the locale, I presume.

**Comment by alexey-pelykh** [comment] 2019-09-05 08:49
> Besides, we don't modify our libraries

I assume that `calendar_renderer.js` needs adjustment to pass locale configuration to datepciker, not the libraries?

**Comment by naglis** [comment] 2019-09-07 15:48
@alexey-pelykh, please check if this is not a duplicate of #30709. See also PR: #28586.

**Comment by alexey-pelykh** [comment] 2019-09-07 16:34
@naglis it actually is, so I'm closing this one as duplicate of #30709

**Comment by alexey-pelykh** [comment] 2019-09-07 18:17
This is different from #30709, so reopening

**Comment by andriisem** [comment] 2019-09-07 18:30
@alexey-pelykh 
https://github.com/andriisem/addons/tree/12.0/first_weekday

**Comment by alexey-pelykh** [comment] 2019-09-07 18:33
@andriisem thanks, but that's only setting locale, not the week start, that can be custom in Odoo

**Closed** 2019-10-11 09:13 UTC
