### ISSUE TITLE
ODOOBOT

### ISSUE THREAD

**Issue by fa-odoo** [odoo/odoo#33532] opened 2019-05-21 13:10 UTC
Impacted versions:
12.0
Steps to reproduce:

Current behavior:
Some purchase /sale orders are canceled by odoobot.
Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2019-05-21 13:12
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by fa-odoo** [comment] 2019-05-21 13:15
I can't reproduce the issue cause i don't understand how does it happen... i was surprised by several purchase and sale orders canceled by odoobot.

![image](https://user-images.githubusercontent.com/42148719/58099119-ed886b80-7bd2-11e9-81d2-d470d8bdf776.png)

**Comment by Yenthe666** [comment] 2019-07-31 14:41
Hi there,

I'm closing this bug report as there has been no more feedback on the last question. We assume that the problem has been solved in the meanwhile. If this is not the case then don't hesitate to respond back (with feedback) and we'll reopen it.

Regards,
Yenthe

**Closed by Yenthe666** 2019-07-31 14:41 UTC
Labels: Need information
