### ISSUE TITLE
[14.0] Does not stay in Apps after module upgrade

### ISSUE THREAD

**Issue by miro-igov** [odoo/odoo#76737] opened 2021-09-17 10:48 UTC
Impacted versions: 14.0

Steps to reproduce: Click on Apps, click on three vertical dots in top right corner of an app and select Upgrade.

Current behavior: After upgrade of the app loads Discuss page

Expected behavior: Should stay in Apps or if Module info is selected from the three vertical dots, should stay in module info after upgrade.

Video/Screenshot link (optional):  https://streamable.com/bvkfjx

Support ticket number submitted via odoo.com/help (optional):

**Comment by sswapnesh** [comment] 2021-09-18 09:32
Duplicate of https://github.com/odoo/odoo/issues/15295

**Closed** 2021-09-22 17:56 UTC
