### ISSUE TITLE
Wrong account used when expenses are emailed (but correct account when expenses entered manually) Why?

### ISSUE THREAD

**Issue by sylwek845** [odoo/odoo#17912] opened 2017-06-29 09:33 UTC
I'm using expense module and it's working fine when I use it manually, but when I email the expense with price to odoo the record is there but the account for the product is not correct, it is set to default account not the one that is configured in the expense product.

Any suggestions?

**Impacted versions:** 10 com

**Steps to reproduce:** Create Expense [F]Fuel  product with specific account (eg car fuel) ->email expense with [F] 10.0 in the topic and picture 

**Current behavior:** Account in expense module created by system (email) is incorrect (company default exist in the record)

**Expected behavior:** Account in the record created by email should be the same as it is in the exprense product (car fuel)

**Comment by Vartkat** [comment] 2017-07-28 00:01
Exactly what I'm saying since June 19th ([#17684](https://github.com/odoo/odoo/issues?utf8=✓&q=is%3Aissue%20is%3Aopen%20%20expense)). Let me add that not only account is wrong but also taxes.

**Comment by Vartkat** [comment] 2017-08-08 18:09
Same situation here. When emailed expense don't get account nor tax from the expandable product. I thought these products were meant to act as template for emailed expenses.

Thanks for your help
Regards 

V.

**Comment by Yenthe666** [comment] 2017-08-09 06:28
@nim-odoo could you perhaps have a look at this (or ping somebody else)?

**Comment by sylwek845** [comment] 2017-08-13 15:21
I fixed the issue (I hope) you can get it from my github profile. I never submitted the fix to official odoo project yet. You need to update the module hr_expense (or just hr_expense.py) and it should work.

[https://github.com/sylwek845/hr_expense](url)

Let mi know (on my project if possible) if you have any issues. Hope it's gonna work for yous.

**Comment by ndemoreau** [comment] 2017-09-18 07:43
Hi, has this fix been merged? I'm a bit afraid to mix two code bases in my projects. Thank you.

**Comment by Yenthe666** [comment] 2017-09-18 15:02
Nothing has been merged at this point. This report it still open.

**Comment by Vartkat** [comment] 2017-09-30 12:26
@sylwek845 issue #17912

Hi,

I’ve replaced the hr_expense.py on a test config and sent some mails. Seems to work for me. If someone able to merge listens…

:-)

Thanks a lot

Regards

V.

**Comment by Vartkat** [comment] 2018-01-09 15:51
Hi,

Why nobody is merging this ? I’m using it since September and seems to work for me.

**Comment by sylwek845** [comment] 2018-01-09 20:19
@Vartkat I'll try to merge it ASAP

**Comment by Vartkat** [comment] 2018-03-22 12:23
Hi, this issue is waiting till 9 month...

Impacted versions: 10ce

Steps to reproduce: 
-Create an expense  product, say [F]Fuel, with specific account from the accounting chart and tax.  
- Send an email for this kind of expense, i.e. with email subject = " [F] bla bla 10.0".

Current behavior: 
Expense is created with a default account, not the account specified in the Fuel product nor the tax.

Expected behavior: 
The created expense should get its account and taxes from the expense product. 
The expense product should act as a template for expenses of its kind.


The mods by @sylwek845 are doing the job, just one thing is still missing :  title of the create expense is the product name, should be the "bla bla" from the email subject.

And of course...This has not been merged since 9 month.

If someone could be kind enough to take a look...

Thanks for your help

regards
V.

**Comment by pedrobaeza** [comment] 2018-06-01 00:30
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-06-01 00:30 UTC
Labels: Accounting

**Comment by gdgellatly** [comment] 2018-06-01 06:03
@pedrobaeza out of interest what's the method you use for emailing runbot
to do the test?

**Comment by pedrobaeza** [comment] 2018-06-01 09:09
It's a saved reply, but my tests were not on runbot indeed. We have this working in one customer without problems.

**Comment by Yenthe666** [comment] 2018-06-01 10:03
@pedrobaeza on a customer environment with the latest updates? I don't know I find this weird. You're replying saying that you can't reproduce it on a runbot while you didn't reproduce it on a runbot and while you say people have to reproduce it on a runbot in order to be a valid report.
Do you see the irony of that?

**Comment by pedrobaeza** [comment] 2018-06-01 10:05
OK, easily fixed editing that saved reply. Done. I think you are being wrongly picky.

**Comment by Yenthe666** [comment] 2018-06-01 10:55
Nah, I'm not being picky, I just like things to be correct. Don't take it offensive, I can be quite straight forward in responses just like you 😉

**Comment by pedrobaeza** [comment] 2018-06-01 10:58
OK, 2 replies for the same thing is not the usual thing, but solved.

**Comment by Yenthe666** [comment] 2018-06-01 12:03
Thanks a lot!
