### ISSUE TITLE
SyntaxWarning: "is not" with a literal. Did you mean "!="?

### ISSUE THREAD

**Issue by zwgshr** [odoo/odoo#39231] opened 2019-10-23 08:50 UTC
Impacted versions:
13.0

``` python
py.warnings: /odoo/addons/base/models/res_config.py:600: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if method.startswith('set_') and method is not 'set_values':
```

**Comment by pedrobaeza** [comment] 2019-10-23 09:14
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by zwgshr** [comment] 2019-10-23 09:23
This is a SyntaxWarning:

``` python
for method in dir(self):
    # if method.startswith('set_') and method is not 'set_values':
    # should replace 'is not' by '!='.
    if method.startswith('set_') and method != 'set_values':
```


![image](https://user-images.githubusercontent.com/10608334/67378015-24ffa780-f5b9-11e9-9865-7bd4f0da9677.png)

**Comment by pedrobaeza** [comment] 2019-10-23 09:25
Sorry, that's not enough. Please specify steps to reproduce the problem in runbot.

**Comment by zwgshr** [comment] 2019-10-23 09:42
I can't find this warning in runbot logs.
My local python version is 3.8.0。maybe it only warning in python 3.8.


find a same issues: https://github.com/Microsoft/ptvsd/issues/1374
![image](https://user-images.githubusercontent.com/10608334/67380137-79f0ed00-f5bc-11e9-9f3c-07054ca10d9a.png)

**Comment by pedrobaeza** [comment] 2019-10-23 09:47
You mustn't use Python 3.8, but 3.6 or 3.7.

Closing as no issue at all.

**Closed by pedrobaeza** 2019-10-23 09:47 UTC
Labels: 13.0, Need information

**Comment by yusraalroom** [comment] 2020-09-23 14:48
try :
sudo apt-get -y upgrade
