### ISSUE TITLE
[9.0, 10.0] Odoo POS layout scrambled in Chrome 58.0.3029.110 

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#17336] opened 2017-05-31 13:18 UTC
Impacted versions: 9.0, 10.0

Steps to reproduce: Use Chrome 58.0.3029.110 and open the POS

Current behavior: The left widgets are scrambled:
![image](https://cloud.githubusercontent.com/assets/6352350/26633601/390c4a8c-4614-11e7-84cb-d77ff1f19a62.png)

Expected behavior: It is rendered correctly (as in Firefox):
![image](https://cloud.githubusercontent.com/assets/6352350/26633613/4697c0d2-4614-11e7-83ea-8900cd89e128.png)

**Comment by Yenthe666** [comment] 2017-05-31 13:19
@jorenvo another one for you.
This can literally fixed by changing the width from the `actionpad` from 188px to 187px. Not sure if this is your wanted fix though.

**Comment by jorenvo** [comment] 2017-05-31 18:37
Weird, I'm running the exact same Chrome (Version 58.0.3029.110 (64-bit)) and I do not have the issue. Were the above screenshots from runbot?

**Comment by Yenthe666** [comment] 2017-05-31 18:50
@jorenvo yes, from the latest Odoo 9.0 runbot (from today)

**Comment by wtaferner** [comment] 2017-05-31 19:52
@Yenthe666 
Any zoom activated? I can reproduce it by zooming into with 110% in Chrome. So, if the single pixel resolves this which it actually does, then I vote for changing it ;-)

**Comment by jorenvo** [comment] 2017-05-31 19:56
@wtaferner ah ok, I can reproduce when zooming. Thanks for the tip. I'll see if changing that width is the right way of fixing the problem.

**Comment by gustavovalverde** [comment] 2017-06-02 13:58
Same here when zooming.

**Comment by jorenvo** [comment] 2017-06-02 16:47
@Yenthe666 could you confirm you were zoomed in as well? I have an idea of what's going on, but if my understanding of the problem is correct it should only happen when browser zoom is not 100%.

**Comment by Yenthe666** [comment] 2017-06-02 17:03
@jorenvo it starts at 90% zoom for me. It is present in 90%, 100%, 110%...
![image](https://cloud.githubusercontent.com/assets/6352350/26736343/efdce03e-47c5-11e7-92c0-ed41aa4a7534.png)

At 80% it is fine:
![image](https://cloud.githubusercontent.com/assets/6352350/26736394/22bb89ba-47c6-11e7-8627-38ec2fc0b78b.png)

**Comment by jorenvo** [comment] 2017-06-02 22:24
Fixed in 9.0 at https://github.com/odoo/odoo/commit/3a826bb7728cdd8fb7d7dfc036542e056e0bffd2.

**Closed by jorenvo** 2017-06-02 22:24 UTC
