### ISSUE TITLE
[12] fleet vehicle not showing if driver not selected

### ISSUE THREAD

**Issue by elperrofarelo** [odoo/odoo#31454] opened 2019-02-27 09:30 UTC
Impacted versions:
[12] 
Steps to reproduce:
Create a vehicle and try to add a odometer, fuel, cost,.... log
No vehicle under the vehicle_id field to select 
Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2019-02-27 10:15
Can you please put some screenshots to show the problem?

**Comment by elperrofarelo** [comment] 2019-02-28 09:22
![fleet1](https://user-images.githubusercontent.com/9564408/53555628-faa13b80-3b4a-11e9-8bbc-eaee63b3dc3d.jpeg)
![fleet2](https://user-images.githubusercontent.com/9564408/53555655-04c33a00-3b4b-11e9-8355-de0fe39ede0b.jpeg)

**Comment by elperrofarelo** [comment] 2019-02-28 09:23
It´s showing only vehicles with predefined driver

**Comment by pedrobaeza** [comment] 2019-02-28 09:26
Yes, but that's on purpose, as a vehicle without driver "can't do kilometers".

Closing as intended behavior.

**Closed by pedrobaeza** 2019-02-28 09:26 UTC
Labels: Need information
