### ISSUE TITLE
Traceback when sharing project edit to contact

### ISSUE THREAD

**Issue by QaidjoharBarbhaya** [odoo/odoo#75765] opened 2021-08-31 05:09 UTC
Impacted versions:
master

Steps to reproduce:

Current behavior:
Traceback:
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/data/build/odoo/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/data/build/odoo/odoo/tools/func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
  File "/data/build/odoo/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: ('ir.model.data', <function IrModelData._xmlid_lookup at 0x7f6c44cd8af0>, 'industry_fsm_report.access_project_worksheet_template_portal')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/build/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/data/build/odoo/odoo/http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "/data/build/odoo/odoo/http.py", line 361, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/build/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/build/odoo/odoo/http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/build/odoo/odoo/http.py", line 918, in __call__
    return self.method(*args, **kw)
  File "/data/build/odoo/odoo/http.py", line 537, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1334, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1322, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/data/build/odoo/addons/project/wizard/project_share_wizard.py", line 42, in action_send_mail
    self.resource_ref._add_collaborators(self.partner_ids)
  File "/data/build/odoo/addons/project/models/project.py", line 796, in _add_collaborators
    self.write({'collaborator_ids': [
  File "/data/build/odoo/addons/sale_timesheet/models/project.py", line 175, in write
    res = super(Project, self).write(values)
  File "/data/build/enterprise/timesheet_grid/models/project.py", line 11, in write
    result = super(Project, self).write(values)
  File "/data/build/odoo/addons/hr_timesheet/models/project.py", line 153, in write
    return super(Project, self).write(values)
  File "/data/build/odoo/addons/project/models/project.py", line 467, in write
    res = super(Project, self).write(vals) if vals else True
  File "/data/build/odoo/addons/mail/models/mail_alias_mixin.py", line 69, in write
    super(AliasMixin, self).write(record_vals)
  File "/data/build/odoo/addons/mail/models/mail_thread.py", line 321, in write
    result = super(MailThread, self).write(values)
  File "/data/build/odoo/addons/mail/models/mail_activity_mixin.py", line 243, in write
    return super(MailActivityMixin, self).write(vals)
  File "/data/build/odoo/odoo/models.py", line 3839, in write
    field.write(self, value)
  File "/data/build/odoo/odoo/fields.py", line 3267, in write
    return self.write_batch([(records, value)])
  File "/data/build/odoo/odoo/fields.py", line 3288, in write_batch
    return self.write_real(records_commands_list, create)
  File "/data/build/odoo/odoo/fields.py", line 3460, in write_real
    flush()
  File "/data/build/odoo/odoo/fields.py", line 3424, in flush
    comodel.create(to_create)
  File "<decorator-gen-293>", line 2, in create
  File "/data/build/odoo/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/data/build/odoo/addons/project/models/project_collaborator.py", line 29, in create
    self._toggle_project_sharing_portal_rules(True)
  File "/data/build/enterprise/industry_fsm_report/models/project_collaborator.py", line 13, in _toggle_project_sharing_portal_rules
    access_worksheet_template_portal = self.env.ref('industry_fsm_report.access_project_worksheet_template_portal').sudo()
  File "/data/build/odoo/odoo/api.py", line 576, in ref
    res_model, res_id = self['ir.model.data']._xmlid_to_res_model_res_id(
  File "/data/build/odoo/odoo/addons/base/models/ir_model.py", line 1931, in _xmlid_to_res_model_res_id
    return self._xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-35>", line 2, in _xmlid_lookup
  File "/data/build/odoo/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/data/build/odoo/odoo/addons/base/models/ir_model.py", line 1924, in _xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 645, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/odoo/http.py", line 302, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: External ID not found in the system: industry_fsm_report.access_project_worksheet_template_portal

Expected behavior:

Video/Screenshot link (optional):

https://user-images.githubusercontent.com/23092156/131445477-5c319f0f-79bf-483b-b065-363c9b4653de.mp4

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment] 2021-08-31 05:11
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by QaidjoharBarbhaya** [comment] 2021-08-31 05:14
Yes, it is reproducible on runbot.

**Comment by pedrobaeza** [comment] 2021-08-31 05:15
But I see this is something enterprise, so please report it to odoo.com/help instead.

**Comment by pedrobaeza** [comment] 2021-08-31 05:15
You are not even saying the Odoo version.

**Comment by vava-odoo** [comment] 2023-04-07 12:55
Closing as this option doesn't seem to exist in stable versions anymore

**Closed by vava-odoo** 2023-04-07 12:55 UTC
Labels: Need information
