### ISSUE TITLE
[9.0]Sequence for Payment is not based on Company

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#11098] opened 2016-02-25 09:46 UTC
Impacted versions:
[9.0]
Steps to reproduce:
Create multi company configuration environment
configure the sequence_payment_customer_invoice to have based on company
Current behavior:
when we create the payment it will just follow the sequence that created from the system, not based on company that we belong to.
Expected behavior:
The sequence must take in account of what company that we belong to.

**Comment by pedrobaeza** [comment] 2018-04-17 23:41
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-04-17 23:41 UTC
Labels: 9.0
