### ISSUE TITLE
Invalid model name 'ir.action.report.xml' in action definition.

### ISSUE THREAD

**Issue by etiennebonnafoux** [odoo/odoo#25676] opened 2018-07-09 10:46 UTC
Impacted versions: OdooV11

Steps to reproduce: Put this module in your addons ( https://we.tl/m7bQj3xscQ )files and try to install it.

Current behavior: When Installing I got this error:
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/odoo/odoo/tools/convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/odoo/odoo/odoo/addons/base/ir/ir_model.py", line 1476, in _update
    record = record.create(values)
  File "/opt/odoo/odoo/odoo/addons/base/ir/ir_actions.py", line 221, in create
    return super(IrActionsActWindow, self).create(vals)
  File "/opt/odoo/odoo/odoo/addons/base/ir/ir_actions.py", line 48, in create
    res = super(IrActions, self).create(vals)
  File "/opt/odoo/odoo/odoo/models.py", line 3373, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/odoo/odoo/models.py", line 3526, in _create
    self._validate_fields(vals)
  File "/opt/odoo/odoo/odoo/models.py", line 1036, in _validate_fields
    check(self)
  File "/opt/odoo/odoo/odoo/addons/base/ir/ir_actions.py", line 129, in _check_model
    raise ValidationError(_('Invalid model name %r in action definition.') % action.res_model)
odoo.exceptions.ValidationError: ("Invalid model name 'report' in action definition.", None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 935, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-41>", line 2, in button_immediate_install
  File "/opt/odoo/odoo/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo/odoo/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/odoo/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 380, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 181, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/odoo/odoo/tools/convert.py", line 791, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/odoo/odoo/tools/convert.py", line 852, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/odoo/odoo/tools/convert.py", line 741, in parse
    self.parse(rec, mode)
  File "/opt/odoo/odoo/odoo/tools/convert.py", line 751, in parse
    exc_info[2]
  File "/opt/odoo/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/odoo/odoo/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/odoo/odoo/tools/convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/odoo/odoo/odoo/addons/base/ir/ir_model.py", line 1476, in _update
    record = record.create(values)
  File "/opt/odoo/odoo/odoo/addons/base/ir/ir_actions.py", line 221, in create
    return super(IrActionsActWindow, self).create(vals)
  File "/opt/odoo/odoo/odoo/addons/base/ir/ir_actions.py", line 48, in create
    res = super(IrActions, self).create(vals)
  File "/opt/odoo/odoo/odoo/models.py", line 3373, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/odoo/odoo/models.py", line 3526, in _create
    self._validate_fields(vals)
  File "/opt/odoo/odoo/odoo/models.py", line 1036, in _validate_fields
    check(self)
  File "/opt/odoo/odoo/odoo/addons/base/ir/ir_actions.py", line 129, in _check_model
    raise ValidationError(_('Invalid model name %r in action definition.') % action.res_model)
odoo.tools.convert.ParseError: "Invalid model name 'report' in action definition.
None" while parsing /opt/odoo/odoo/addons/report/views/views.xml:45, near
<record id="reports_action" model="ir.actions.act_window">
            <field name="src_model"/>
            <field name="name">Report</field>
            <field name="res_model">ir.action.report.xml</field>
            <field name="view_type">form</field>
            <field name="view_mode">tree,form</field>
        </record> 

Expected behavior: The module works.

The view.xml file is located in a file with two other xml: layouts.xml and report.xml which I think should be load by the deficient action definition.

Thank you very much.

**Comment by pedrobaeza** [comment] 2018-07-09 10:51
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2018-07-09 10:51 UTC
