### ISSUE TITLE
inventory on hand quantity 1 in valuation is 0

### ISSUE THREAD

**Issue by icf20** [odoo/odoo#31723] opened 2019-03-09 11:28 UTC
Impacted versions: 12

Steps to reproduce:

no idea how to reproduce this

Current behavior:
on hand quantity =1 but on valuation say =0

Expected behavior:
hand quantity x price

Video/Screenshot link (optional):
product detail
![image](https://user-images.githubusercontent.com/17784575/54070875-18b31e00-4266-11e9-86a8-b1756ed606eb.png)

inventory report 

![image](https://user-images.githubusercontent.com/17784575/54070897-4bf5ad00-4266-11e9-9b91-d7696bd5f21a.png)

inventory value report

![image](https://user-images.githubusercontent.com/17784575/54070941-bdcdf680-4266-11e9-994c-382288510ccf.png)

**Comment by pedrobaeza** [comment] 2019-03-10 15:45
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by nhomar** [comment] 2019-03-10 18:18
This fequently happen if you do not have valuation perpetual.
Since v12.0 the valuation is hardly linked to accounting, just let me know the valuation method and if it is FIFO please.

Regards.

**Comment by icf20** [comment] 2019-03-11 22:55
@nhomar is set standard 
![image](https://user-images.githubusercontent.com/17784575/54163005-e2d58b80-4457-11e9-928a-a2ff7053c830.png)

**Comment by sle-odoo** [comment] 2019-03-12 08:02
hi,
> no idea how to reproduce this

then, i'm afraid we can't really help you
there are cases where having one on hand and zero valued makes sense too, imagine you have in stock at the moment one unit of a product you do not own.

regards

**Closed by sle-odoo** 2019-03-12 08:02 UTC
Labels: 12.0, Logistics, Need information
