### ISSUE TITLE
Customer user created without partner_id, can access to all invoices/sales from portal

### ISSUE THREAD

**Issue by dansanti** [odoo/odoo#47646] opened 2020-03-15 16:39 UTC
Impacted versions:
11.0
Steps to reproduce:
if you have this problem:
https://github.com/odoo/odoo/commit/64a3d8f1d6162cc2556633e8acf73bb281a23677#diff-08b0dbc88b9cca7f1424794857fd0ba6
1.- create contact 
2.- create subcontact
3.- add portal access to subcontact
4.- before this commit https://github.com/odoo/odoo/commit/64a3d8f1d6162cc2556633e8acf73bb281a23677#diff-08b0dbc88b9cca7f1424794857fd0ba6 odoo create user without partner ( i fix it in my installation)
5.- create password for user
6. open website portal sales view
7.- user can access to all data

Current behavior:

here the real problem, is that kind of user can access to all data, independent if this issues is generated with my steps, the real problem is that issue ( user without partner ) can do it

**Comment by Yenthe666** [comment] 2020-03-15 18:48
@dbo-odoo @qdp-odoo for you guys

**Comment by dbo-odoo** [comment] 2020-03-19 10:54
Hello,

The description is a bit vague and I'm unable to reproduce it.

Here's what I did:
1. create a partner (type 'company') and a child partner for that company (with an email address)
2. use the wizard 'portal access management' on that company and grant access to the child
3. go to Settings > Users and set a password for the new portal user
4. connect as this new user in an incognito window
5. everything is fine

I'm a bit fuzzy on how you can create a user without a partner. This should not be possible. Ideally, use our testing platform ( http://runbot.odoo.com/runbot/repo/git-github-com-odoo-enterprise-7?search=11.0 ), connect to the latest 11.0 build using the demo credentials (admin/admin) and make a recording of what you speak of, please.
![screenshot-runbot odoo com-2020 03 19-11_51_21](https://user-images.githubusercontent.com/9530767/77060086-5057b880-69d8-11ea-9023-324866614a14.png)

Also, you might want to check your default portal user configuration, since it gets duplicated upon signup of new users: Settings > General Settings > Default Access Right (in the 'Customer Account' section). Nothing should be set on that template user.
![screenshot-1808588-11-0-4f3dc6 runbot46 odoo com-2020 03 19-11_53_22](https://user-images.githubusercontent.com/9530767/77060100-551c6c80-69d8-11ea-8ffa-5f48dd65ae5e.png)

Thx

**Comment by dansanti** [comment] 2020-03-19 18:06
currently is fixed create a user without partner from portal wizard, i noticed this problem, because my installation is before 64a3d8f commit, before that but the underlying problem is that in case in other cases some user without partner allow to acces all data
before 64a3d8f commit:
1.- create a partner A
2.- create a partner child to A as B
3.- create a partner child to B as C
4.- select partner C and allow use portal,
5.- a user without is created

that user  can see all data

**Comment by Yenthe666** [comment] 2020-03-19 20:13
Euhh but if it's fixed then I see no point in this issue? Just update and it's solved?

**Comment by dbo-odoo** [comment] 2020-03-20 10:04
@dansanti 
Puede explicar todo eso en español, por favor - con mas detalles (capturas de plantillas, screencast, todo eso...)? Disculpa pero no entiendo su Inglès...

Como lo dice @Yenthe666 , si su problema es que sin el commit hay un problema, la solucion es de implementar el commit.

**Comment by dansanti** [comment] 2020-03-20 17:16
hola!
el commit lo que soluciona es el problema de crear usuarios sin partners, sin embargo si por alguna rzón todavía se puede crear usuario sin partner, ese usuario puede hacer login y ver todo desde el portal de cliente

antes del commit mencionado, se podía crear por error un usuario sin partner sin embargo, aún no se soluciona el problema de que un usuario sin partner pueda visualizar la información

**Comment by luisg123v** [comment] 2020-03-22 20:54
I just double-checked that actually it's not possible to create an user without partner:

```
>>> user.partner_id = False
ERROR dbname odoo.sql_db: bad query: UPDATE "res_users" SET "partner_id"=NULL,"write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (24)
ERROR: null value in column "partner_id" violates not-null constraint
```

**Comment by dbo-odoo** [comment] 2020-03-23 06:44
Hello,

As explained by me and demonstrated by @luisg123v, it is not possible to create a user without a partner. I've asked for screenshots/screencasts several times. I am not able to reproduce your issue, postgres constraints of a standard installation prevent the behaviour you speak of. The fix you mention does not changes the fact that a user without a partner is not possible; it just allows creating users for partners that are companies through a wizard - a very small change compared to what you speak of.

I will close this, if you can show me how to reproduce it reliably on a standard installation (video), then I will consider reopening it. Still, I suspect that something is wrong in your installation; not in the code.

KR,

**Closed by dbo-odoo** 2020-03-23 06:44 UTC
