### ISSUE TITLE
[18.0] odoo: RTL odoo has an issue with Next and Previous buttons

### ISSUE THREAD

**Issue by shlayel** [odoo/odoo#186889] opened 2024-11-12 08:40 UTC
### Odoo Version

- [ ] 16.0
- [ ] 17.0
- [X] 18.0
- [ ] Other (specify)

### Steps to Reproduce

Install the Arabic language.
Switch to Arabic.
Look at the Next and Previous buttons in the list view, for instance. You will find that the edges of the buttons and their radius are reversed.

**Comment by chgo-odoo** [comment] 2024-11-19 13:05
Hello @shlayel, thanks for opening this issue 👋 

It seems like the issue is there in `17.0` as well. These buttons now have a background since `17.0`, which makes the issue clearly visible. I'm not exactly sure why these two buttons have a different structure but I'll investigate.

**Comment by chgo-odoo** [comment] 2024-11-20 11:46
Hello @shlayel, thanks again for the feedback 👋 

The fix successfully landed in `18.0` via https://github.com/odoo/odoo/commit/387a3bf7db3bcc96f9995d1a62f4fdbf010c3755 and is now being forward-ported all the way up to Master.

I'm closing this issue as it is now resolved,

Wishing you a nice day 🙂

**Closed by chgo-odoo** 2024-11-20 11:46 UTC
