### ISSUE TITLE
database backup error

### ISSUE THREAD

**Issue by xwjh** [odoo/odoo#28138] opened 2018-10-25 08:47 UTC
Impacted versions:
Odoo 12.0-20181008(docker)
Steps to reproduce:
web/database/backup,backup the database
Current behavior:
Database backup error: Postgres subprocess ('/usr/bin/pg_dump', '--no-owner', '--file=/tmp/tmpva5pui5s/dump.sql', 'odoo12') error 1
Expected behavior:
backup database
Video/Screenshot link (optional):

**Comment by fractalf** [comment] 2019-01-28 11:52
I had the same problem.

The problem:
https://github.com/odoo/odoo/issues/30599

The fix until they update the .deb file is to manually install *pg_dump* (see issue)

**Comment by d-fence** [comment] 2019-01-28 12:58
It seems to be a Docker image issue.
The problem is explained in #30599 
Docker image will be fixed soon.

**Closed by d-fence** 2019-01-28 12:58 UTC
