### ISSUE TITLE
Advance invoice wizard with method percentage ignores taxes

### ISSUE THREAD

**Issue by tafaRU** [odoo/odoo#4653] opened 2015-01-12 16:43 UTC
**Advance invoice wizard with method percentage ignores taxes**

Impacted versions:
- 8.0 and above

Steps to reproduce:
1.  make a SO with one line with one product with unit price = 1000.00 and add a 20.0% tax on this line, so the total amount of the SO is 1200.00;
2.  click on create invoice and choose **Percentage** and put 50% as percentage;

Current behaviour:
- the invoce is created with one line of 600.00 without tax, so the total amount of this invoice is 600.00

Expected behaviour:
- the invoice is created with one line of 500 with 100 as value tax, so the total amount of this invoice is 600.00.

Thank you in advance

**Comment by markusr** [comment] 2015-02-17 15:43
This is a duplicate of #530 but unfortunately there is no fix yet.

**Comment by elacunza** [comment] 2015-04-28 14:01
Maybe this PR fixes your problem #6073

**Comment by Yenthe666** [comment] 2017-12-05 10:56
Hi @tafaRU,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Closed by Yenthe666** 2017-12-05 10:56 UTC
Labels: Accounting
