### ISSUE TITLE
[11.0 - 12.0 ?] Permission read error when validating an invoice with analytic account

### ISSUE THREAD

**Issue by jbguerraz** [odoo/odoo#29797] opened 2018-12-28 15:25 UTC
We faced the exact same issue as described in https://github.com/odoo/odoo/issues/24504 : no way to validate an invoice until we either use admin account or change the record rule `account.analytic.line.billing.user` in order to give read permission.

Since Odoo 12 still have this read permission set to false; how is it going to work ?

"Change manually the rule and no more problem" as said @pedrobaeza doesn't sounds like a fix. Is it supposed to "work" that way ? if so, then what's wrong with our use case ? how is it supposed to work ?

_Originally posted by @jbguerraz in https://github.com/odoo/odoo/issues/24504#issuecomment-450376258_

**Comment by pedrobaeza** [comment] 2018-12-31 10:09
The question is that you don't include the exact steps to reproduce the problem, and I haven't faced the problem in any of my installations, so it should be something custom. That's why I told about modifying the record rule to adapt to your custom things.

Any way, this won't be solved nor analyzed if you don't provide that steps on a runbot instance to make sure the environment is not "dirty": https://runbot.odoo.com.

**Comment by dalonsod** [comment] 2018-12-31 18:38
@jbguerraz as long as I could check, the issue #24504  was already fixed in Odoo 12.

As you say "_Since Odoo 12 still have this read permission set to false; how is it going to work ?_" I think you don't understand how record rules work in this case. Since there are no active rules for _read_ permissions for an account analytic line without project_id, the user gets access. So, perm_read=0 is not "read is not allowed" but "read permissions are not affected by this rule".

You can read more in [this link](url).

Actually, before the issue fix the problem consisted on another rule (`account.analytic.line.timesheet.manager`) setting perm_read="1", that incorrectly restricted access for records not matching the rule. Thus, modifying `account.analytic.line.billing.user`in the same way was only a patch for this.

**Comment by pedrobaeza** [comment] 2019-01-04 17:03
Then it is clear: change manually the record rule in your DB or start a fresh new one.

Closing this.

**Closed by pedrobaeza** 2019-01-04 17:03 UTC
Labels: 11.0, Need information
