### ISSUE TITLE
odoo13: Aliase email can't route to personal inbox

### ISSUE THREAD

**Issue by czssf** [odoo/odoo#46614] opened 2020-02-29 02:38 UTC
Impacted versions: odoo13

Steps to reproduce: create a new Aliase email "demo", set as below:

Aliased Model:User

Record Thread ID:x(as user id)

Default Values:{}
Alias Contact Security:everyone
Owner:demo

when a incoming email to demo@yourdomail, raise error:

ValueError: Mailbox unavailable - model res.users does not accept document creation

**Comment by pedrobaeza** [comment] 2020-02-29 10:13
This is something expected, as that model can't accept incoming mails. You shouldn't try to imitate personal inboxes in Odoo. That's not the aim of the social network features of Odoo.

Closing as intended behavior.

**Closed by pedrobaeza** 2020-02-29 10:13 UTC
