### ISSUE TITLE
 [8.0] Not translated titles views odoo

### ISSUE THREAD

**Issue by CarlesAntoli** [odoo/odoo#5277] opened 2015-02-14 12:21 UTC
In the latest updates all titles views are not translated.  My language is Spanish and all labels shown are in English.

span class="oe_view_title_text oe_breadcrumb_title"><span class="oe_breadcrumb_item">Automated Actions

**Comment by Sameer1990** [comment] 2015-02-17 09:51
There is more than a word missing translation , I think Odoo not consider missing translation an issue because they translate many words .
You have to translate it .

**Comment by danimaribeiro** [comment] 2015-02-20 01:15
@Sameer1990 It's happening with all views in all languages.
Doesn't seem a missing translation.

![capturar](https://cloud.githubusercontent.com/assets/854781/6279899/3729033e-b88d-11e4-8d56-a406754d635b.PNG)

**Comment by Yajo** [comment] 2015-02-20 08:26
@danimaribeiro It's definitely a bug. It's happening to me too after the last update.

**Comment by Cedric-Pigeon** [comment] 2015-02-20 12:10
Hello I encounter the same problem. If you test on runbot it is also wrong. Whatever the language you load, titles are always in English.
I have a database dated on 30 january and it was OK. So the regression occured in the last 3 weeks.

**Comment by Cedric-Pigeon** [comment] 2015-02-20 12:11
@CarlesAntoli  Could you prefix the issue title with [8.0] ?

**Comment by Cedric-Pigeon** [comment] 2015-02-20 13:06
@beledouxdenis It seems that your commit on main.py  https://github.com/odoo/odoo/commit/1d76586a1b0fff766581871cd277332bbfec030a is responsible of the regression.

**Comment by beledouxdenis** [comment] 2015-02-20 13:16
Thank for the bisect and to inform me. I am on it right now.

**Comment by beledouxdenis** [comment] 2015-02-20 14:39
This issue is solved in Odoo 7.0 from rev. 27a48f8026f824f62955d5bf2a83b2799ad98db1.

I will forward port the fix to Odoo 8.0 asap.

**Comment by Cedric-Pigeon** [comment] 2015-02-20 16:00
@beledouxdenis Thanks for the quick fix :+1:

**Comment by beledouxdenis** [comment] 2015-02-20 16:34
The fix has been ported to Odoo 8.0, from rev. b0be8dfdfd78c7953c1f60bf86b862bc46abd65c.

This issue is therefore regarded as closed. Thank you for your report.

**Closed by beledouxdenis** 2015-02-20 16:34 UTC
