### ISSUE TITLE
[12] Can not open Accounting App

### ISSUE THREAD

**Issue by technicomp** [odoo/odoo#27500] opened 2018-10-08 06:43 UTC
Impacted versions: 12

Steps to reproduce: Try to open Accounting

Current behavior:

Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1032, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7fce70fd4f60>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 970, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1034, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('account.journal(1,).kanban_dashboard_graph', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 938, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 904, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 926, in do_search_read
    offset=offset or 0, limit=limit or False, order=sort or False)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4516, in search_read
    result = records.read(fields)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2768, in read
    values[name] = field.convert_to_read(record[name], record, use_name_get)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5042, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 974, in __get__
    self.determine_value(record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1085, in determine_value
    self.compute_value(recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1041, in compute_value
    self._compute_value(records)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1032, in _compute_value
    getattr(records, self.compute)()
  File "<decorator-gen-252>", line 2, in _kanban_dashboard_graph
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 372, in loop
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 372, in <listcomp>
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/usr/lib/python3/dist-packages/odoo/addons/account/models/account_journal_dashboard.py", line 21, in _kanban_dashboard_graph
    self.kanban_dashboard_graph = json.dumps(self.get_bar_graph_datas())
  File "/usr/lib/python3/dist-packages/odoo/addons/account/models/account_journal_dashboard.py", line 96, in get_bar_graph_datas
    day_of_week = int(format_datetime(today, 'e', locale=self._context.get('lang') or 'en_US'))
  File "/usr/lib/python3/dist-packages/babel/dates.py", line 603, in format_datetime
    if datetime.tzinfo is None:
AttributeError: 'datetime.date' object has no attribute 'tzinfo'

**Comment by Elkasitu** [comment] 2018-10-08 07:10
Can you reproduce this on the [runbot](http://runbot.odoo.com/runbot) ?

I checked the code, tested locally and on the runbot and it all seems fine, what version of python are you running?

**Comment by sswapnesh** [comment] 2018-10-08 07:50
Duplicate of https://github.com/odoo/odoo/issues/27445 and handled in https://github.com/odoo/odoo/commit/35151b62b32195ecabaf0481fee228e05bb513f9

**Closed** 2018-10-08 07:58 UTC
Labels: 12.0, Need information
