### ISSUE TITLE
Tax report incorrect calculation

### ISSUE THREAD

**Issue by jayo2005** [odoo/odoo#69632] opened 2021-04-21 18:59 UTC
Impacted versions: 11

Steps to reproduce: I updated to latest branch but issues still remains

Current behaviour: Calculating Tax Wrong

Expected behaviour: Calculate tax correct

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

If you look at the TAX report. The Calculation is all wrong. 

9% of €29376.55 = €2643.89
23% of €2083.63 = €479.23
13.5% of €11702.77 = €1579.87

Below is what Odoo is reporting. 
![2021-04-21_19-53-24](https://user-images.githubusercontent.com/7015925/115606203-51de6900-a2db-11eb-8217-37c49f121fc9.jpg)

**Comment by pedrobaeza** [comment] 2021-04-22 06:18
Sorry, but 11.0 is a deprecated version that is already not being supported, so any bug report about this old version won't be attended, and thus I close this issue. Please check if the problem is still there in new versions, and if so, you can open a new issue regarding that version.

Anyway, the problem is probably due to rounding by line, that makes this to accumulate rounding errors. Select round globally.

Thanks for your comprehension.

**Closed by pedrobaeza** 2021-04-22 06:18 UTC
