### ISSUE TITLE
Odoo Help Forum - problems

### ISSUE THREAD

**Issue by zbik2607** [odoo/odoo#33709] opened 2019-05-28 08:44 UTC
Impacted versions: master

My Browsers: Firefox 67.0, Google Chrome 74.0

1) Impossible to add image
2) Impossible copy and paste code - tags are removed 
3) 'User rank' is not set - see image rank_0.svg on page https://www.odoo.com/profile/users
4) Ranks are confused - see 1,2,3 on page https://www.odoo.com/profile/ranks_badges

Wishlist:
5) Preview

**Comment by Yenthe666** [comment] 2019-05-28 09:16
@JKE-be for you. Also related issues:
- Converting a comment to an answer fails
- Adding code in a code block that is QWeb fails (for example: `<t t-foreach="invoice_lines" t-as="invoice_line">`)

**Comment by Yenthe666** [comment] 2019-05-30 15:36
@JKE-be another one: you cannot remove the 'mark as answered' option from an answer, this was possible in the past.

**Comment by Yenthe666** [comment] 2019-06-08 13:22
The editor has become even worse than the one from two weeks ago so it seems. It now glitches even more and editing code blocks has become even more cumbersome.

**Comment by mpagani-nexapp** [comment] 2019-06-25 14:55
Good morning,
i'm also having some problems with the Courses: i'm not receiving the badges for the 2k XP and the completed course.
I've opened a thread on the forum (https://www.odoo.com/it_IT/forum/help-1/question/odoo-courses-bug-151481) but i've received instruction from Niyas Raphy to post it here too.

Thanks

**Comment by treviser** [comment] 2019-07-09 05:01
It is also not possible to mark a question as favorite anymore.

**Comment by Yenthe666** [comment] 2019-07-09 05:54
And it is also not possible to delete an accepted answer or to change it afterwards. This has always been the case.
The dialogs that show the XP/ranks also show "False" at the top a lot

**Comment by sudhir-erpharbor** [comment] 2019-07-09 06:59
There are many countries which are not enabled. I don't see India to fill the postal address.

![free_mug](https://user-images.githubusercontent.com/7952467/60866033-f72e6700-a244-11e9-8bc8-d9e51845125c.png)

**Comment by DikuBhadane** [comment] 2019-07-09 07:30
![Screenshot from 2019-07-09 12-57-05](https://user-images.githubusercontent.com/48708589/60867701-1d560600-a249-11e9-82a6-ac88d4c35d34.png)
I can't change my profile picture.

**Comment by JKE-be** [comment] 2019-07-10 10:25
@sudhir-erpharbor 

should be available now

**Comment by JKE-be** [comment] 2019-07-10 10:26
@DikuBhadane 

should be fixed now

**Comment by sudhir-erpharbor** [comment] 2019-07-10 10:56
> @DikuBhadane
> 
> should be fixed now

Yes, its available. Thanks for fixing that quickly.

**Comment by sudhir-erpharbor** [comment] 2019-07-10 10:56
> @sudhir-erpharbor
> 
> should be available now

Yes, its available. Thanks for fixing that quickly.

**Comment by Yenthe666** [comment] 2019-07-10 18:27
The image button in the editor on the forums is also no longer working. It is a dead button now:
![image](https://user-images.githubusercontent.com/6352350/60994610-25996880-a351-11e9-8173-209954fe8360.png)

**Comment by Yenthe666** [comment] 2019-07-10 18:33
The code editor is also broken as hell. Now I can't even nicely paste a block of code anymore..

**Comment by pawa2007** [comment] 2019-07-16 12:24
Karma points are not getting added when a person accepts an answer and marks the issue as "Resolved".

**Comment by Yenthe666** [comment] 2019-07-16 12:29
@pawa2007 are you sure? I've got an accept earlier today and I think the karma was added (for this one https://www.odoo.com/nl_NL/forum/help-1/question/using-position-after-or-position-inside-which-one-is-pest-practice-152795#answer-152798).

**Comment by pawa2007** [comment] 2019-07-16 12:33
@Yenthe666 absolutely sure. I've been noticing this behavior since yesterday. I've posted 4 responses that have been accepted by the OP but my karma points have not budged by a single point.

**Comment by Yenthe666** [comment] 2019-07-16 12:36
Hmm interesting. Did you make the topic at https://www.odoo.com/nl_NL/forum/help-1/question/how-do-i-report-a-technical-issue-regarding-posting-on-this-forum-152811 ? If so can you accept my answer, we'll see what happens with karma. I have 22.623 karma right now.

There is also another issue actually.
1. Create a new answer
2. Add a comment under the answer
3. Convert the answer to a comment
4. All comments under the answer are lost

I think they should be kept and stacked under eachother.

**Comment by pawa2007** [comment] 2019-07-16 12:40
@Yenthe666 I just accepted your answer. Noticed something interesting....it added 2 points to my karma for accepting the answer :-)

**Comment by Yenthe666** [comment] 2019-07-16 12:41
@pawa2007 yeah accepting an answer has always given a +2 karma (well atleast the last two years). I've also gained the karma as I now have 22.638 so it all seems to work fine?
Are you sure you've not accepted your own answers? This results in zero karma to prevent upvoting yourself.

**Comment by pawa2007** [comment] 2019-07-16 12:46
Ah..ah...@Yenthe666 I think it's a case of self-inflicted injury. I clicked on the check mark because it said "Send answers" thinking that it sent it to the original poster. My bad. Hiding the button on your own posts would be a better way to implement this. Thanks for pointing this out to me.

**Comment by pawa2007** [comment] 2019-07-16 12:48
@Yenthe666 ...also the wording should at least be changed from "Send answer" to "Accept answer" so that it is less misleading.

**Comment by Yenthe666** [comment] 2019-07-16 12:49
Good point, looks like an invalid change in the latest version. @JKE-be can you change the term for the forums?

**Comment by pawa2007** [comment] 2019-07-16 13:02
@JKE-be I had received an email to claim an Odoo mug. I had clicked on the link but was not able to enter my address because it did not have "India" as a value in the country field. I noticed that one of your earlier posts suggests that you have added it. But, now I am getting a "403 - Forbidden" error when I click on the link and navigate to the page to enter the address.

**Comment by pawa2007** [comment] 2019-07-16 13:15
@Yenthe666 Is there a way to "unmark" the answer as resolved so that the OP can mark it once it is confirmed ?

**Comment by Yenthe666** [comment] 2019-07-16 13:22
@pawa2007 actually no, while it has been around in Odoo though. I've already asked the guys (@JKE-be) to bring the functionality back to remove an accepted answer or modify it though.

**Comment by JKE-be** [comment] 2019-07-16 13:57
#34097 wip

Jeremy Kersten

**Comment by pawa2007** [comment] 2019-07-20 13:24
The editor on the Help forum does not seem to work with mobile browsers (Chrome in my case). I get a lot of gibberish when I try to type something in especially when I type a backspace or try to change some text.

**Comment by usmanfarzandali** [comment] 2019-07-22 09:31
Pakistan is also missing pls fix this issue .....

**Comment by usmanfarzandali** [comment] 2019-07-22 09:31
Pakistan is also missing pls fix this issue .....
![imageedit_152_4887645456](https://user-images.githubusercontent.com/22232100/61622021-6f594b80-ac8d-11e9-9f35-e8ae24eb4049.png)

**Comment by pedrobaeza** [comment] 2019-07-22 09:34
@usmanfarzandali please stop spamming other unrelated issues. You have the steps to do in the other thread.

**Comment by pawa2007** [comment] 2019-07-26 02:27
Over the last few days I have noticed that the odoo.com website language automatically switches to a random language around midnight UTC even if I am in the middle of a session (browsing from India). So far, the website has been displayed using the Brazilian, Spanish, German and Arabic localization while I was browsing the help forum. I problem persists till I manually change the language.

**Comment by JKE-be** [comment] 2019-07-26 07:39
@pawa2007, lang is in your cookies, so I have really some doubts about this new feature.
And we don't add a script to random lang recently ;)

**Comment by Yenthe666** [comment] 2019-07-26 11:19
I'm going to bet you've opened a shared link somewhere which contained another Lang. The lang cookie is then updated and you're viewing in another lang all of a sudden.

**Comment by pawa2007** [comment] 2019-07-26 11:42
It has happened while opening a post from the forum (which I was browsing in English) or while refreshing the list of posts on the first page of the help forum to check for the latest post. It could be a coincidence but whenever this happened I've noticed it around 5:30 pm IST which is midnight UTC hence the question. I'll monitor it again today since it's about 20 mins away and will post immediately if it happens again.

**Comment by pawa2007** [comment] 2019-07-26 12:40
Monitored this for over 30 mins now. All seems to be well. Will post a screenshot if I encounter this again. Thanks everyone for the feedback.

**Comment by pawa2007** [comment] 2019-07-28 11:24
Happened again just now (Sunday, Jul 28th 4:49pm IST) while on the front page of odoo.com. Here's a screenshot. It's showing me the Brazilian translation of the site without me explicitly setting it to that language.

![image](https://user-images.githubusercontent.com/21964536/62005968-2fe0a280-b158-11e9-83af-5e393d830111.png)

**Comment by Yenthe666** [comment] 2019-11-12 09:48
Looks like it is all pretty much solved in the meanwhile / in V13.

**Closed by Yenthe666** 2019-11-12 09:48 UTC
Labels: Website
