### ISSUE TITLE
[10.0] Not correctly formed UTM - Source of Applicants

### ISSUE THREAD

**Issue by collex100** [odoo/odoo#15927] opened 2017-03-18 16:37 UTC
Impacted versions: 10.0c

Steps to reproduce:
1. Recruitment - > Sources of Applicants
2. Create -> Source -> Automatically generated - url Parameters and Email

Current behavior:
**url Parameters:**  https://my_site.com/False?utm_campaign=Position+Company&utm_medium=Website&utm_source=Mailing+Partner
**Email:** false+mailing-partner@my_site.com
Why is it added: **False**?

Expected behavior:
There must be a valid link

Video/Screenshot link (optional):
https://youtu.be/a128VaYMiQk

**Comment by pedrobaeza** [comment] 2018-05-22 08:18
This has been changed recently in a commit, but I don't have right now the exact reference. Please try again to see if the problem is still there, and if so, please comment back. Meanwhile, I close this.

**Closed by pedrobaeza** 2018-05-22 08:18 UTC
Labels: 10.0, Services
