### ISSUE TITLE
 Difference Amount in "Register Payment" is not displayed properly

### ISSUE THREAD

**Issue by inetplus** [odoo/odoo#1892] opened 2014-08-20 19:52 UTC
Version 8

Steps:
1) Create invoice
2) click on button "Register Payment"
3) enter in the field "Paid Amount" an amount which is less than total amount
   in my example from test data:
   Customer: Think Big Systems
   Paid Amount: 750,00 Euro -> entered 250 Euro
   Payment Method: Bank(EUR) selected

4) Difference Amount: 
   As soon as any kind of Payment Method is selected than difference amount is always zero.
   which is wrong when entered an amount which is less/more than paid amount

Expected Result:
1) invoice created
2) modal window is opened
3) paid amoun is changable
4) difference is displayed

Actual Result
1) OK
2) OK
3) OK
4) 0 Euro is displayed instead 500 Euro

**Comment by richard-willowit** [comment] 2015-02-25 06:39
Any movement on this?  Was very embarrassed when demonstrating to client that wanted to accept a short payment and write the difference off and not given an option to do so.

**Comment by sfaraujo** [comment] 2015-03-03 10:20
SOLVED
With the default Chart of accounts there is no problem. But with my custom charts account for Portugal I had the same problem. 
So, I solved it just comparing the charts involved in this process, and I realized that the Receivable Account wasn't able to reconcile.

Accounts -> Templates -> Accounts -> Charts of Accounts Templates 
Click on the  Receivable Account and turn on the Allow Reconciliation

**Comment by AlmustafaNET** [comment] 2015-03-12 21:58
I solved it!

The problem exist when I used the custom  Charts of Accounts.

1. Change Clients Accounts.  In my case:  '1.01.02.05.01.01  - Clientes' set both Types to: 'Por cobrar '
   And '2.02.02.01.01.  - Proveedores' set to:  'A pagar' AND checked 'Allow Reconciliation'

2. Set a correct account in "Account Journal" in 'Journals', for default this account is incorrect.

And BINGO!

**Comment by richard-willowit** [comment] 2015-04-14 07:28
@thomich - I just tried your module.  It seems that with that installed, it only allows a write off if there is an overpayment, not if there is an underpayment?  It reverses the original problem.

**Comment by thomich** [comment] 2015-04-14 07:49
@richard-willowit do you have setup your receivable accounts correctly? as above comments the receivable account (account on customer invoice) has to be set to allow reconciliation... same for supplier invoices...

if i try that on any odoo 8 runbot (http://runbot.odoo.com/runbot) i can't get it running as above comments described... if i do a underpayment for a invoice, difference amount for me is not calculated... even if runbot's are using default CoA.

As you described about reverse the problem, for me on runbot's if you register a overpayment it calculates the difference amount, which is wrong...

As i know from accounting, a overpayment can't be done in this way, for this you have to create a own journal entry.. register full amoutn of invoice/payment and for overpayment create a own journal entry...

**Comment by richard-willowit** [comment] 2015-04-16 03:15
@thomich Yes, Receivable and Payables set correctly.

We want to allow under and overpayments this way.  The variances are there for every payment this particular client invoice payment, because there is a currency variation every time.  I have just bitten the bullet, written my own module that is a complete copy of their code, with two dummy hooks in it, and then I change the apply amount in those hooks to stop it from reaching the ceiling of applies, and it then always shows the full variance on the pop-up, and allows under and overpayments to be written off then.

**Comment by thomich** [comment] 2015-04-20 15:31
@richard-willowit normaly, over payment can be registered with customer payments wizard (NOT register payment from invoice)... there you can also make bulk payments for partners...

**Comment by richard-willowit** [comment] 2015-04-20 23:27
@thomich Yes, I realise that, but why make people do it in two steps when they can do it in one.  Register payment from invoice is just as logical.  "Here is your invoice for 199.99".  "Here is 200 dollars".  Hmmm, better go to a different screen to process this...

**Comment by wpichler** [comment] 2015-07-09 15:33
i do have the same problem here
i can see a fix for version 7 which was never merged
https://code.launchpad.net/~openerp-dev/openobject-addons/trunk-bug-1202127-ssh

I will try this fix on my 8.0 branch

**Comment by Troublicious** [comment] 2015-12-03 14:04
This bug is still present in the Version 8.0-20151109 , nobody use this feature in Odoo ? Nobody uses seriously Odoo in fact ??

**Comment by thomich** [comment] 2015-12-03 16:05
our customers use it.. we have done a fix for it, see above comments...
if underpayment it works fine... for overpayment, you have to go to customer payments and make the payment from there...

**Comment by Troublicious** [comment] 2015-12-03 16:15
Thank you thomich for your answer and your fix that i tried: indeed it's not a real solution as it inverse the problem . I can't understand how sfaraujo and AlmustafaNET solved the problem, as nothing as to deal with reconciliation in my testing DB. I really don't understand how such a bug can stay in Odoo during more than 15 months ...

**Comment by thomich** [comment] 2015-12-03 16:29
i also don't know, why this still exists.. and i think it also exists in v9...

you say it inverts problem.. now, we here in switzerland normally not having customers that pay more then the invoiced amount ;)
for us, if invoice amount is eg. 105 and customer pays 100, we can make the write off and difference will be calculated correctly...
if invoice amount is eg. 95 and customer pays 100, then we have to go trough customer payment OR normally register 95 trough register payment wizard an make a manual journal entry with the extra 5 to the needed account...

**Comment by Troublicious** [comment] 2015-12-04 14:33
LOL =) it seems that the end user for whom i try to find a solution has some customers who pay more! (cause they use paper order forms, maybe they just don't know about abacus, or calculator ;).
In any case, thank you for your suggestions thomich, i'll post again if i find something convincing !

**Comment by thomich** [comment] 2015-12-04 14:42
thanks ;)

if i find time and maybe a contributor, we will enhance the fix that it also can handle over payments in payment registration wizard...

**Comment by ysoler** [comment] 2016-02-02 15:39
Hi thomich, your fix is good enought for me with Customer Payments, but with Supplier Payments when i try to register partial payments, payments are registering fully. Do you have the same issue?

**Comment by lapagept** [comment] 2016-02-12 23:28
The fix from thomic has many lines. We already have a custom module who overrides account_voucher class. It seems dangerous to install his fix. 
More, in his fix, we don't really see the differences with original files.

**Comment by rossasa** [comment] 2016-02-26 19:39
I'm having the same issue, It's still not solved?

**Comment by thomich** [comment] 2016-03-01 06:22
please check our latest version of account_voucher_payment_fix, for us on odoo 8 we can solve the issue, under and over payment...

important is, correct configuration of accounts, as usual...

**Comment by rossasa** [comment] 2016-03-01 21:18
thomich, You mean that it's a configuration problem?
Becouse I check my receivable accounts it's with the option Allow Reconciliation checked and still having this error, I check even with the default Belgium chart of accounts I have this same error. Could be other configuration?

**Comment by rossasa** [comment] 2016-03-01 21:28
I installed you module and works great with the company currency, in multi-currency is where I have problems the fix doesn't works correctly. For example:
If I have an invoice of 200USD and try paid 5000PYG(1USD) the Difference Amount gives me -4800PYG instread of 995000PYG witch will be the correct

**Comment by rossasa** [comment] 2016-03-01 21:32
This only happends if the value of the Paid Amount is bigger than the Invoice residual value

**Comment by afrikanovic** [comment] 2016-11-02 21:11
Does anyone fixed this ? it seems i have the same problem on V8

**Comment by ehanuise** [comment] 2016-11-21 13:04
I have this issue on odoo.com, how can I apply your fix on the saas odoo ? Don't find it in the modules list.

**Comment by thomich** [comment] 2016-11-21 13:56
you can't use tht module/repository on saas odoo.. you have to use standalone odoo..

contact me, if you need support for standalone odoo.

**Comment by ehanuise** [comment] 2016-11-21 14:48
oh, ok... Any chances this get fixed on saas someday ? It's quite a problem :)

**Comment by thomich** [comment] 2016-11-21 14:54
hey @ehanuise 

see, this bug is open since aug 2014 and we just have made a fix, but seams odoo is not interested to implement or fix it in base..

go with your own odoo is best way to get fast fixes ;)..

**Comment by Yenthe666** [comment] 2017-10-07 15:42
Hi @inetplus ,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: Sorry it wasn't ever handled fully.

Regards,
Yenthe

**Closed by Yenthe666** 2017-10-07 15:42 UTC
