### ISSUE TITLE
Company logo not changing after adding ensure_db()

### ISSUE THREAD

**Issue by ozarga** [odoo/odoo#13169] opened 2016-08-17 05:30 UTC
Impacted versions:
Odoo 9.0
Steps to reproduce:
Installed Odoo in Google Cloud Server using Bitnami 1-click installation/launch.
Created databases.

Current behavior:
When I tried to change the company logo (Settings>Edit company data>Edit logo (pencil icon)>select image>Save) even after clearing cache and refreshing browser the Odoo logo keeps appearing, not my logo. When I try to edit the logo again in company settings it looks like it is already uploaded but only there.
Looking for solutions I arrived to #3753 and added ensure_db() after def company_logo(self, dbname=None, **kw): in main.py but still have the same problem.

Every time I have tried Odoo (even when it was OpenERP) I had this problem.

Even though I can access server console and I'm able to modify code if guided clearly I'm not very technical so I would really appreciate clear (step-by-step) explanations or fixes.
Help me please

@AlanBell @ke-real please SOS

**Comment by JKE-be** [comment] 2016-08-17 10:21
Seems like a cache issue... already discuss in several PR / Issue...
you can always try:
right click on the image, 
open image in new tab, 
add ?a=b at the end of the url to force a refresh without cache, 
do ctrl + shift + R to force a hard reload ... 
you should see your new logo... 
And restart all your chrome...

Else you can also try, F12, disable cache 

https://bugs.chromium.org/p/chromium/issues/detail?id=44122
http://superuser.com/questions/220179/how-can-i-do-a-cache-refresh-in-google-chrome/512833#512833
It is probably a problem of cache in chrome... 

But because you don't change logo every hours, we don't want to force the invalidation at each load...

**Comment by ke-real** [comment] 2016-08-17 11:50
@JKE-be 
yes it is a cache issue, but you don't expect every user to clear their cache or hit force refresh.
It is also true that you don't change logo every hour, however it might be important to force it to change at a certain moment for all users (company rebranding for example). Current solution only takes DB name and company ID into account. Even daily based reload could be fine compared to general Odoo traffic.
It is easy job to add an additional modifier to all logo links.

**Comment by ozarga** [comment] 2016-08-17 15:58
I was using Firefox and not Chrome, but anyway I tried what you said (in chrome):
1. Open logo image in a new tab 
RESULTS: Odoo logo in new tab
2. In image tab added ?a=b at the end of the url to force a refresh without cache 
RESULTS: My logo appeared
3. Did trl + shift + R to force a hard reload
RESULTS: Refreshed image tab, still with my logo.
4. Restarted Chrome:
RESULTS: Odoo logo still in backend odoo but my logo in image tab.

If you want you can access the server, I don't mind: http://104.197.233.1/ 
fake@fake.com
Fake123

Open to test anything.

**Comment by bartstelder** [comment] 2016-08-19 05:34
@JKE-be I fully agree the modifier should be added. This reaction is unacceptable; think customer!

**Comment by JKE-be** [comment] 2016-08-19 09:08
@bartstelder  which reaction ? 

I just said that ?t=time() is not the good fix like discuss in other threads, to avoid to refresh each times !
That doesn't mean that we will not take a look to this issue... 

Related opw-686305

**Comment by nim-odoo** [comment] 2016-08-29 12:08
Hello,

Have you tried something else than a Bitnami server? We are using Odoo instances with many databases on our side, and we don't face the problem. For example, on the runbot: http://runbot.odoo.com/runbot After changing the image, a simple refresh of the page will display the new image.

**Comment by bartstelder** [comment] 2016-08-30 13:51
jke-BE
Thx, i hope this issue will be solved soon

**Comment by JKE-be** [comment] 2016-08-30 14:03
@bartstelder -> Have you take a look to the nmi answer... ?

The problem from ozarga seems to be a cache issue on the server (bitnami server, google cloud)...
So not linked to yours issue at first view... Please see with @nim-odoo if you can reproduce your issue cache with a standard install (eg: runbot)

**Comment by ozarga** [comment] 2016-09-02 21:23
Hello everyone and thanks for the help.
I was very bussy at my work this last two weeks but today I returned to my Odoo instance in the google cloud server (installed through bitnami).
Sudenly it's working without problems. I can change the company logo  by Settings>Edit company data>Edit logo (pencil icon)>select image>Save
I wonder if it is because Google made something in my server account or what...
weird

**Comment by mart-e** [comment] 2017-10-12 10:18
Closing as it seems solved (tested again on 9 and 10 without issue)

**Closed by mart-e** 2017-10-12 10:18 UTC

**Comment by killvis** [comment] 2017-12-20 10:53
if the image is not updating after uploading the image for the company then check the partner_id for that company, if not then set the respective id and the issue will be resolved
