### ISSUE TITLE
odoo unfold group in tree view is not responding  in ios

### ISSUE THREAD

**Issue by StarV5s** [odoo/odoo#66659] opened 2021-02-23 09:23 UTC
Impacted versions:
Odoo11.0e
Steps to reproduce:
Using odoo in ios, whether in odoo app or browser like safari or chrome, enter a tree view, unfold a group (if no group there, add one), and the UI is not responding anymore.
Current behavior:
Using odoo in ios, whether in odoo app or browser like safari or chrome, enter a tree view, unfold a group (if no group there, add one), and the UI is not responding anymore. Not all module have this problem,  "hr_payroll" is one which is odoo official module(problem model's name is "hr.payslip.run" ).
Expected behavior:
It should unfold this group, and show all the record in this group.
Video/Screenshot link (optional):
Support ticket number submitted via odoo.com/help (optional):
None.

**Comment by pedrobaeza** [comment] 2021-02-23 09:24
Sorry, but the Odoo version mentioned in the issue is no longer supported. Odoo only supports the last 3 stable versions.

If the report still makes sense for the upper version, please let us know and specify possible recreated steps for the newer version in a new issue report.

Meanwhile, closing this.

**Closed by pedrobaeza** 2021-02-23 09:24 UTC
