### ISSUE TITLE
Error on creating a warehouse

### ISSUE THREAD

**Issue by quiero** [odoo/odoo#12377] opened 2016-06-10 13:58 UTC
Impacted versions: V9 (Debian Jessie, Python 2.7.9 (default, Mar  1 2015, 12:57:24)  [GCC 4.9.2] on linux2

The last commit I can see in my log:
vnc@jessie:/opt/odoo$ git log
commit 4ffd2fdd81aad675194f9c21c097abdc99a0d3c0
Author: Damien Bouvy <dbo@odoo.com>
Date:   Thu May 26 10:27:44 2016 +0200

Steps to reproduce:
Go to Inventory \  Warehouse Management  \  Warehouses \ Create
Fill up the fields. Hit Save

Then I got this.
Current behavior:

2016-06-10 13:46:29,087 5039 ERROR v9 openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 680, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/openerp/http.py", line 959, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 509, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 896, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 888, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/addons/stock/stock.py", line 3796, in create
    wh_loc_id = location_obj.create(cr, uid, loc_vals, context=context)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/addons/stock/stock.py", line 147, in create
    return super(stock_location, self).create(cr, uid, default, context=context)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 4151, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/opt/odoo/openerp/models.py", line 4317, in _create
    cr.execute('update '+self._table+' set parent_left=%s,parent_right=%s where id=%s', (pleft+1, pleft+2, id_new))
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

**Comment by JKE-be** [comment] 2016-06-10 14:40
Cannot reproduce in last 9.0
Pull the last code and retry ...

**Comment by Yenthe666** [comment] 2016-06-13 06:02
Hi @quiero,

I've just tested this on another runbot and can't reproduce this either. A newly created warehouse example:
![image](https://cloud.githubusercontent.com/assets/6352350/15998233/e0216b74-313c-11e6-8ca6-87059afaf85d.png)

Please update your Odoo to the latest codebase and this issue should be resolved.
Closing this issue since it can't be reproduced anymore (neither on the community and the enterprise version).

Regards,
Yenthe

**Closed by Yenthe666** 2016-06-13 06:02 UTC
