### ISSUE TITLE
No module named 'stdnum' (from stdnum.iso7064 import mod_97_10)

### ISSUE THREAD

**Issue by mprice4-1Up** [odoo/odoo#50876] opened 2020-05-07 15:17 UTC
Impacted versions:
Odoo 13 CE (cloned odoo/odoo git yesterday)

Steps to reproduce:
1) Open App
2) Click Install Sales

Current behavior:
Receive an error message:
```
File "/opt/odoo/addons/account/models/account_move.py", line 10, in <module>
    from stdnum.iso7064 import mod_97_10
ModuleNotFoundError: No module named 'stdnum'
```

Expected behavior:
Sales Module is installed

Video/Screenshot link (optional):
I've confirmed that the appropriate Python Module is in fact installed.
<img width="668" alt="image" src="https://user-images.githubusercontent.com/38380835/81312041-bf9e7000-904b-11ea-9a79-7ca4875eb2be.png">

**Comment by pedrobaeza** [comment] 2020-05-08 13:58
The problem is that you don't have the library in your Odoo running environment. It's probably because you need `python3-stdnum`, not `python-stdnum`.

Any way, it's a deployment problem that you should solved on your own or asking help on the forums, but out of the scope of this issue tracker, so closing.

**Closed by pedrobaeza** 2020-05-08 13:58 UTC

**Comment by mprice4-1Up** [comment] 2020-05-09 04:55
Thanks Pedro. Much appreciate the feedback!
