### ISSUE TITLE
website_theme_install issue from 19 may 2020 update

### ISSUE THREAD

**Issue by Mayank-navabrindit** [odoo/odoo#65581] opened 2021-02-05 06:54 UTC
HELLO everyone,

I am getting this issue while update my template change. Please Anyone can help me out. 

2021-02-05 06:46:54,453 15186 ERROR ti_4feb_13e odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/home/ashika/Workspace/odoo-13.0/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/ashika/Workspace/odoo-13.0/odoo/modules/loading.py", line 417, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/ashika/Workspace/odoo-13.0/odoo/modules/loading.py", line 313, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/ashika/Workspace/odoo-13.0/odoo/modules/loading.py", line 266, in load_module_graph
    module.write({'state': 'installed', 'latest_version': ver})
  File "/home/ashika/Workspace/odoo-13.0/addons/website_theme_install/models/ir_module_module.py", line 90, in write
    module._theme_load(website)
  File "/home/ashika/Workspace/odoo-13.0/addons/website_theme_install/models/ir_module_module.py", line 205, in _theme_load
    module._update_records(model_name, website)
  File "/home/ashika/Workspace/odoo-13.0/addons/website_theme_install/models/ir_module_module.py", line 167, in _update_records
    find.update(rec_data)
  File "/home/ashika/Workspace/odoo-13.0/odoo/models.py", line 5430, in update
    record[name] = value
  File "/home/ashika/Workspace/odoo-13.0/odoo/models.py", line 5698, in __setitem__
    return self._fields[key].__set__(self, value)
  File "/home/ashika/Workspace/odoo-13.0/odoo/fields.py", line 1085, in __set__
    records.write({self.name: write_value})
  File "/home/ashika/Workspace/odoo-13.0/addons/website_theme_install/models/theme_models.py", line 230, in write
    res &= super(IrUiView, no_arch_updated_views).write(vals)
TypeError: unsupported operand type(s) for &=: 'NoneType' and 'NoneType'
2021-02-05 06:46:54,456 15186 CRITICAL ti_4feb_13e odoo.service.server: Failed to initialize database `ti_4feb_13e`. 
Traceback (most recent call last):
  File "/home/ashika/Workspace/odoo-13.0/odoo/service/server.py", line 1190, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/ashika/Workspace/odoo-13.0/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/ashika/Workspace/odoo-13.0/odoo/modules/loading.py", line 417, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/ashika/Workspace/odoo-13.0/odoo/modules/loading.py", line 313, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/ashika/Workspace/odoo-13.0/odoo/modules/loading.py", line 266, in load_module_graph
    module.write({'state': 'installed', 'latest_version': ver})
  File "/home/ashika/Workspace/odoo-13.0/addons/website_theme_install/models/ir_module_module.py", line 90, in write
    module._theme_load(website)
  File "/home/ashika/Workspace/odoo-13.0/addons/website_theme_install/models/ir_module_module.py", line 205, in _theme_load
    module._update_records(model_name, website)
  File "/home/ashika/Workspace/odoo-13.0/addons/website_theme_install/models/ir_module_module.py", line 167, in _update_records
    find.update(rec_data)
  File "/home/ashika/Workspace/odoo-13.0/odoo/models.py", line 5430, in update
    record[name] = value
  File "/home/ashika/Workspace/odoo-13.0/odoo/models.py", line 5698, in __setitem__
    return self._fields[key].__set__(self, value)
  File "/home/ashika/Workspace/odoo-13.0/odoo/fields.py", line 1085, in __set__
    records.write({self.name: write_value})
  File "/home/ashika/Workspace/odoo-13.0/addons/website_theme_install/models/theme_models.py", line 230, in write
    res &= super(IrUiView, no_arch_updated_views).write(vals)
TypeError: unsupported operand type(s) for &=: 'NoneType' and 'NoneType'

**Comment by pedrobaeza** [comment] 2021-02-05 07:07
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Mayank-navabrindit** [comment] 2021-02-05 07:16
I have upgrade a theme module which my custom changes at that time it shows error. PFA screenshot. 
![Screenshot from 2021-02-05 12-44-20](https://user-images.githubusercontent.com/72067007/107001762-353c9580-67b0-11eb-919a-920df775e122.png)

**Comment by pedrobaeza** [comment] 2021-02-05 07:18
Then I'm afraid it's something from your custom module that you have to solve, unless you give more clues about what's going on on your local DB. Closing meanwhile.

**Closed by pedrobaeza** 2021-02-05 07:18 UTC
Labels: Need information
