### ISSUE TITLE
Button on Email Marketing

### ISSUE THREAD

**Issue by marcchausse** [odoo/odoo#72287] opened 2021-06-17 12:39 UTC
Impacted versions: V14

Steps to reproduce:
1 - Create a new Mailing from the Email  Marketing
2 - Select a theme with a button
3 - Change the Back ground color (anything else than 100% transparency)
4 - Modify the Button shape for the Default + Rouding.

Current behavior:
The button has a mixed shape (rounded and squared)
Expected behavior:
The button should have the rounded shape only
Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/57365364/122397976-722b4c80-cf47-11eb-9531-d7c95346b219.png)

![image](https://user-images.githubusercontent.com/57365364/122398066-83745900-cf47-11eb-9108-b5c5dd13f829.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment] 2021-06-17 12:46
What happen with another theme? Which theme are you using?

**Comment by marcchausse** [comment] 2021-06-17 15:01
Hello Pedro, well in fact I used the third template:
![image](https://user-images.githubusercontent.com/57365364/122422281-04891b80-cf5b-11eb-91d2-52cbe369870d.png)
But I have the Same issue with most of them.

**Comment by pedrobaeza** [comment] 2021-06-17 15:56
That are enterprise themes, and the problem is in their design, not in Odoo "engine" itself. You should put a ticket in odoo.com/help for receiving support.

Closing here as something on the enterprise mass mailing themes.

**Closed by pedrobaeza** 2021-06-17 15:56 UTC

**Comment by marcchausse** [comment] 2021-06-17 19:04
Hello Pedro, 
I have the same issue with all Themes, the Community As well
Not sure we should close this ticket at the moment.

**Comment by marcchausse** [comment] 2021-06-17 19:04
![image](https://user-images.githubusercontent.com/57365364/122458035-55aa0700-cf7d-11eb-8c49-1c0503bb67a5.png)

**Comment by pedrobaeza** [comment] 2021-06-17 19:15
OK, let's reopen it then.
