### ISSUE TITLE
[14.0] website_sale payment.acquirer after uninstalling / reinstalling paypal

### ISSUE THREAD

**Issue by stefwbe** [odoo/odoo#60424] opened 2020-10-21 10:01 UTC
Impacted versions: 14.0

Steps to reproduce: Install paypal payment acquirer - uninstall it - reinstall it

Current behavior: Error while trying to (re-)install

Expected behavior: /

Traceback: 
Fout:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo14/odoo14-server/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/odoo14/odoo14-server/odoo/http.py", line 682, in dispatch
    result = self._call_function(**self.params)
  File "/odoo14/odoo14-server/odoo/http.py", line 358, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo14/odoo14-server/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo14/odoo14-server/odoo/http.py", line 346, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo14/odoo14-server/odoo/http.py", line 911, in __call__
    return self.method(*args, **kw)
  File "/odoo14/odoo14-server/odoo/http.py", line 530, in response_wrap
    response = f(*args, **kw)
  File "/odoo14/odoo14-server/addons/web/controllers/main.py", line 1363, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/odoo14/odoo14-server/addons/web/controllers/main.py", line 1351, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo14/odoo14-server/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/odoo14/odoo14-server/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-71>", line 2, in button_immediate_install
  File "/odoo14/odoo14-server/odoo/addons/base/models/ir_module.py", line 73, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoo14/odoo14-server/odoo/addons/base/models/ir_module.py", line 474, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/odoo14/odoo14-server/odoo/addons/base/models/ir_module.py", line 592, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/odoo14/odoo14-server/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo14/odoo14-server/odoo/modules/loading.py", line 453, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/odoo14/odoo14-server/odoo/modules/loading.py", line 346, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/odoo14/odoo14-server/odoo/modules/loading.py", line 221, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/odoo14/odoo14-server/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/odoo14/odoo14-server/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/odoo14/odoo14-server/odoo/tools/convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "/odoo14/odoo14-server/odoo/tools/convert.py", line 719, in parse
    self._tag_root(de)
  File "/odoo14/odoo14-server/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/odoo14/odoo14-server/odoo/tools/convert.py", line 681, in _tag_root
    raise ParseError('while parsing %s:%s, near\n%s' % (
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/odoo14/odoo14-server/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo14/odoo14-server/odoo/http.py", line 314, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.tools.convert.ParseError: while parsing /odoo14/odoo14-server/addons/payment_paypal/data/payment_acquirer_data.xml:5, near
<record id="payment.payment_acquirer_paypal" model="payment.acquirer">
            <field name="name">Paypal</field>
            <field name="image_128" type="base64" file="payment_paypal/static/src/img/paypal_icon.png"/>
            <field name="provider">paypal</field>
            <field name="company_id" ref="base.main_company"/>
            <field name="view_template_id" ref="paypal_form"/>
        </record>

**Comment by pedrobaeza** [comment] 2020-10-21 16:17
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by sswapnesh** [comment] 2020-10-21 17:01
Got this error on Uninstalling Paypal module on Runbot

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/data/build/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/data/build/odoo/odoo/http.py", line 682, in dispatch
    result = self._call_function(**self.params)
  File "/data/build/odoo/odoo/http.py", line 358, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/build/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/build/odoo/odoo/http.py", line 346, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/build/odoo/odoo/http.py", line 911, in __call__
    return self.method(*args, **kw)
  File "/data/build/odoo/odoo/http.py", line 530, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1363, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1351, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/data/build/odoo/odoo/addons/base/wizard/base_module_uninstall.py", line 59, in action_uninstall
    return modules.button_immediate_uninstall()
  File "<decorator-gen-74>", line 2, in button_immediate_uninstall
  File "/data/build/odoo/odoo/addons/base/models/ir_module.py", line 73, in check_and_log
    return method(self, *args, **kwargs)
  File "/data/build/odoo/odoo/addons/base/models/ir_module.py", line 616, in button_immediate_uninstall
    return self._button_immediate_function(type(self).button_uninstall)
  File "/data/build/odoo/odoo/addons/base/models/ir_module.py", line 592, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/data/build/odoo/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/data/build/odoo/odoo/modules/loading.py", line 522, in load_modules
    cr.commit()
  File "<decorator-gen-7>", line 2, in commit
  File "/data/build/odoo/odoo/sql_db.py", line 101, in check
    return f(self, *args, **kwargs)
  File "/data/build/odoo/odoo/sql_db.py", line 444, in commit
    flush_env(self)
  File "/data/build/odoo/odoo/sql_db.py", line 78, in flush_env
    env_to_flush['base'].flush()
  File "/data/build/odoo/odoo/models.py", line 5391, in flush
    self.recompute()
  File "/data/build/odoo/odoo/models.py", line 5826, in recompute
    process(field)
  File "/data/build/odoo/odoo/models.py", line 5810, in process
    recs.mapped(field.name)
  File "/data/build/odoo/odoo/models.py", line 5197, in mapped
    recs = recs._fields[name].mapped(recs)
  File "/data/build/odoo/odoo/fields.py", line 1035, in mapped
    self.__get__(record, type(records))
  File "/data/build/odoo/odoo/fields.py", line 937, in __get__
    self.compute_value(recs)
  File "/data/build/odoo/odoo/fields.py", line 1111, in compute_value
    records._compute_field_value(self)
  File "/data/build/odoo/odoo/models.py", line 4020, in _compute_field_value
    getattr(self, field.compute)()
  File "/data/build/odoo/addons/payment/models/payment_acquirer.py", line 203, in _compute_color
    if acquirer.module_id and not acquirer.module_state == 'installed':
  File "/data/build/odoo/odoo/fields.py", line 2418, in __get__
    return super().__get__(records, owner)
  File "/data/build/odoo/odoo/fields.py", line 949, in __get__
    recs._fetch_field(self)
  File "/data/build/odoo/odoo/models.py", line 3050, in _fetch_field
    self._read(fnames)
  File "/data/build/odoo/odoo/models.py", line 3117, in _read
    cr.execute(query_str, params + [sub_ids])
  File "<decorator-gen-3>", line 2, in execute
  File "/data/build/odoo/odoo/sql_db.py", line 101, in check
    return f(self, *args, **kwargs)
  File "/data/build/odoo/odoo/sql_db.py", line 298, in execute
    res = self._obj.execute(query, params)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/odoo/http.py", line 314, in _handle_exception
    raise exception.with_traceback(None) from new_cause
psycopg2.ProgrammingError: column payment_acquirer.paypal_email_account does not exist
LINE 1: ..."odoo_adyen_payout_id" as "odoo_adyen_payout_id", "payment_a...
                                                             ^
```

**Comment by pedrobaeza** [comment] 2020-10-21 17:15
OK, then I think the uninstall-man is @Elkasitu, hehe.

**Comment by Elkasitu** [comment] 2020-10-22 11:40
I'm aware of it but haven't had the time to do a deep dive on it yet, I will try to take a look at it next week.

**Comment by Yenthe666** [comment] 2020-10-28 16:38
Yep, hit by the same. Made an OPW for it, `2372598`

**Comment by JayVora-SerpentCS** [comment] 2020-10-29 10:25
:) Have we got another uninstall king after solid @sswapnesh ? :)

**Closed** 2020-11-24 15:58 UTC
Labels: 14.0, Confirmed, OE, Payment
