### ISSUE TITLE
Discount Bug

### ISSUE THREAD

**Issue by amindehghani** [odoo/odoo#56357] opened 2020-08-23 04:26 UTC
Impacted versions: 13.0

Steps to reproduce: 
1. Enable Discount in Settings > Sales
2. Choose your desired Pricelist and set the Discount policy to > Show public price & discount to the customer
3. Give a price rule to a product example is if min quantity 2 price is 10
4. Add product to shopping cart 

Current behavior:
the shopping cart adds a little bit of extra money to the price

Expected behavior:
it is not supposed to add extra cash to the current price

Video/Screenshot link (optional):
![Screenshot from 2020-08-23 08-54-10](https://user-images.githubusercontent.com/16416527/90970794-7270dc00-e51e-11ea-8142-c3bf382449c4.png)
![Screenshot from 2020-08-23 08-54-22](https://user-images.githubusercontent.com/16416527/90970795-756bcc80-e51e-11ea-9a88-f80e1b78631d.png)

**Comment by auyeung112002** [comment] 2020-09-02 02:11
Related: https://github.com/odoo/odoo/issues/46417

**Comment by rdeodoo** [comment] 2020-10-28 12:23
Duplicate of https://github.com/odoo/odoo/issues/46417

**Closed by rdeodoo** 2020-10-28 12:23 UTC
Labels: 13.0, Website
