### ISSUE TITLE
[13.0] Wrong discount % calculation in sales report

### ISSUE THREAD

**Issue by lgarcia11** [odoo/odoo#50846] opened 2020-05-07 11:48 UTC
Impacted versions:
13.0

The column discount % is being summed, which is a wrong calculation.

Example from runbot,
![image](https://user-images.githubusercontent.com/12752396/81290537-40eb0800-9036-11ea-9085-7546348536f4.png)

**Comment by pedrobaeza** [comment] 2020-05-07 11:51
Although the average aggregation is selected on the SQL view, the result is not going to be correct, due to the nature of that data. Any way, I let @dbo-odoo to give his opinion.

This can be got with our OCA module https://github.com/OCA/web/tree/12.0/web_pivot_computed_measure, but it's not migrated to v13 yet.

**Comment by dbo-odoo** [comment] 2020-05-12 14:58
Hello @lgarcia11 ,

I agree that the current aggregation is useless, but you're missing the most interesting part of this issue: what is the *expected behaviour*, exactly 😬? Because I honestly don't know.

To me, there is simply no way to accurately represent this data based on grouping: summing the discounts is meaningless, averaging is meaningless (because it would need to be weighted), counting is meaningless, min/max is meaningless... I simply do not see a way to represent discounts accurately in such an array through SQL. Perhaps the OCA module could indeed allow to compute the average discount properly, but that's outside the scope of Odoo.

So, how do you suggest we aggregate discounts in a way that is SQL compatible and user-friendly (i.e. *understandable*)?

I have hoewever sent this to our internal feedback type: perhaps we should allow developers to prevent aggregation on specific fields? This would avoid displaying fields in groupBy/pivot/graph views when it simply doesn't make any sense.

Unless you provide me a meaningful expected result, I simply see no way of fixing this ¯\\\_(ツ)\_\/¯. I'll close it for now, if you find a meaningful metric I might reopen it.

Have a nice day,

**Closed by dbo-odoo** 2020-05-12 14:58 UTC
Labels: 13.0, Sales
