### ISSUE TITLE
[15.0] Can not delete a canceled stock picking.

### ISSUE THREAD

**Issue by tanghulu0608** [odoo/odoo#94007] opened 2022-06-20 02:02 UTC
**Impacted versions:**
15.0 , maybe all.

**Steps to reproduce:**
Cancel a stock picking, then try to delete it. 
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/5561864/174512286-ea7be8af-2e8b-4143-b5dd-5be02ac0a7f8.png">

https://github.com/odoo/odoo/blob/6c8008b2e9ba0e58b940d8f0e6ad7b13d6b8c9bd/addons/stock/models/stock_move_line.py#L459

**Current behavior:**
Can not delete a canceled stock picking.

**Expected behavior:**
User can delete canceled stock pickings, because those picking has no effect to the system.

**Comment by bodedra** [comment] 2022-06-21 17:53
I am unable to reproduce it.

**Comment by tanghulu0608** [comment] 2022-06-27 02:33
@bodedra 
steps to reproduce,
1.  go to runbot, select V15, login.
2. go to menu Inventory, create a Delivery Orders with done qty 333
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/5561864/175849111-be426f53-72ed-48e5-a6a7-c47dad0e183a.png">
3. cancel the delivery order ,and try to deleted it.

**Comment by bodedra** [comment] 2022-06-27 17:13
@tanghulu0608 Thanks for providing steps. Now I reproduce it on runbot. https://16923508-15-0-all.runbot56.odoo.com/web#cids=1&menu_id=438&action=666&active_id=2&model=stock.picking&view_type=form&id=46
![do-picking-validation](https://user-images.githubusercontent.com/14229503/175997240-2093cd81-cbd7-447a-bc0a-5d856f89b0c5.PNG)

**Comment by BayarkhuuBataa** [comment] 2022-06-28 09:41
It is also affected in v14

**Comment by ticodoo** [comment] 2022-07-26 15:06
This error is occurring because quantities are being marked as 'Done' before cancelling, therefore the picking isn't possible to be deleted because these quantities are still recorded. If the picking must be deleted rather than having cancelled pickings in your database, then you can set all Done quantities to '0' and then delete directly (with or without cancelling first).

Either way, this is not really a blocking issue so there will be no change done for this.

**Closed by ticodoo** 2022-07-26 15:06 UTC
Labels: Logistics
