### ISSUE TITLE
[9.0][Accounting] Error while editing journal's default account

### ISSUE THREAD

**Issue by lem8r** [odoo/odoo#8617] opened 2015-09-19 11:07 UTC
_Tested on demo.odoo.com_

Accounting -> Configuration -> Journals -> Edit any journal
Try to set default debit or credit account -> Error

```
TypeError: val is undefined

https://demo1.odoo.com/web/content/71-f1aa49f/web.assets_backend.js:3053
Traceback:
wrap_context@https://demo1.odoo.com/web/content/71-f1aa49f/web.assets_backend.js:3053:1
eval_domains/<@https://demo1.odoo.com/web/content/71-f1aa49f/web.assets_backend.js:3060:143
_.forEach@https://demo1.odoo.com/web/content/79-6fd8666/web.assets_common.js:12:558
_.mixin/</_.prototype[name]@https://demo1.odoo.com/web/content/79-6fd8666/web.assets_common.js:69:521
eval_domains@https://demo1.odoo.com/web/content/71-f1aa49f/web.assets_backend.js:3059:136
eval_domains/<@https://demo1.odoo.com/web/content/71-f1aa49f/web.assets_backend.js:3060:301
_.forEach@https://demo1.odoo.com/web/content/79-6fd8666/web.assets_common.js:12:558
_.mixin/</_.prototype[name]@https://demo1.odoo.com/web/content/79-6fd8666/web.assets_common.js:69:521
eval_domains@https://demo1.odoo.com/web/content/71-f1aa49f/web.assets_backend.js:3059:136
eval_domains/<@https://demo1.odoo.com/web/content/71-f1aa49f/web.assets_backend.js:3060:301
_.forEach@https://demo1.odoo.com/web/content/79-6fd8666/web.assets_common.js:12:558
_.mixin/</_.prototype[name]@https://demo1.odoo.com/web/content/79-6fd8666/web.assets_common.js:69:521
eval_domains@https://demo1.odoo.com/web/content/71-f1aa49f/web.assets_backend.js:3059:136
pyeval@https://demo1.odoo.com/web/content/71-f1aa49f/web.assets_backend.js:3070:24
eval_arg@https://demo1.odoo.com/web/content/71-f1aa49f/web.assets_backend.js:3073:61
ensure_evaluated@https://demo1.odoo.com/web/content/71-f1aa49f/web.assets_backend.js:3076:11
.call@https://demo1.odoo.com/web/content/71-f1aa49f/web.assets_backend.js:2943:1
DataSet<.name_search@https://demo1.odoo.com/web/content/71-f1aa49f/web.assets_backend.js:3203:1038
CompletionFieldMixin.get_search_result@https://demo1.odoo.com/web/content/71-f1aa49f/web.assets_backend.js:3621:25
FieldMany2One<.render_editable/<.source@https://demo1.odoo.com/web/content/71-f1aa49f/web.assets_backend.js:3726:103
._search@https://demo1.odoo.com/web/content/79-6fd8666/web.assets_common.js:1588:142
$.widget/</proxiedPrototype[prop]</<@https://demo1.odoo.com/web/content/79-6fd8666/web.assets_common.js:1124:328
.search@https://demo1.odoo.com/web/content/79-6fd8666/web.assets_common.js:1588:8
$.widget/</proxiedPrototype[prop]</<@https://demo1.odoo.com/web/content/79-6fd8666/web.assets_common.js:1124:328
$.widget.bridge/$.fn[name]/<@https://demo1.odoo.com/web/content/79-6fd8666/web.assets_common.js:1129:13
.each@https://demo1.odoo.com/web/content/79-6fd8666/web.assets_common.js:473:758
jQuery.prototype.each@https://demo1.odoo.com/web/content/79-6fd8666/web.assets_common.js:461:636
$.widget.bridge/$.fn[name]@https://demo1.odoo.com/web/content/79-6fd8666/web.assets_common.js:1126:342
FieldMany2One<.render_editable/<@https://demo1.odoo.com/web/content/71-f1aa49f/web.assets_backend.js:3721:995
jQuery.event.dispatch@https://demo1.odoo.com/web/content/79-6fd8666/web.assets_common.js:740:378
jQuery.event.add/elemData.handle@https://demo1.odoo.com/web/content/79-6fd8666/web.assets_common.js:713:151
```

**Comment by mart-e** [comment] 2015-09-22 13:48
Hello,

I see you are using demo1.odoo.com. This looks like an error with the assets (bundle of javascript and css).
We have had a few issues with those lately, it should be fixed now (can not reproduce anymore).

**Closed by mart-e** 2015-09-22 13:48 UTC

**Comment by lem8r** [comment] 2015-09-22 14:34
Just checked latest github revision of Odoo 9 to test this locally and I got error when creating new database with demo data:
```
2015-09-22 14:23:30,914 16816 WARNING odoo9-test2 openerp.addons.base.ir.ir_qweb:  Error: Error opening fileThis error occured while compiling the bundle 'web.assets_common' containing:
    - /web/static/src/less/mimetypes.less
    - /web_planner/static/src/less/web_planner_common.less
    - /web_editor/static/src/less/web_editor.less
2015-09-22 14:23:31,801 16816 WARNING odoo9-test2 openerp.addons.base.ir.ir_qweb:  Error: Error opening fileThis error occured while compiling the bundle 'web.assets_backend' containing:
    - /website/static/src/less/import_bootstrap.less
    - /web/static/src/less/enterprise_compatibility.less
    - /web/static/src/less/utils.less
    - /web/static/src/less/modal.less
    - /web/static/src/less/notification.less
    - /base_import/static/src/less/import.less
    - /web_tip/static/src/less/tip.less
    - /web_calendar/static/src/less/web_calendar.less
    - /web_diagram/static/src/less/diagram_view.less
    - /web_kanban/static/src/less/kanban_dashboard.less
    - /web_kanban/static/src/less/kanban_view.less
    - /web_settings_dashboard/static/src/less/dashboard.less
```

**Comment by buldi** [comment] 2016-02-24 10:01
Hi

Please data from the command 'whereis lessc'
