### ISSUE TITLE
Issues with oauth Facebook module OAuth2 Authentication.

### ISSUE THREAD

**Issue by LeCaoPhuc** [odoo/odoo#29256] opened 2018-12-05 04:33 UTC
Impacted versions:
Odoo 12
Steps to reproduce:
Install a module OAuth2 Authentication try setup and oauth Facebook. 

Current behavior:
Will get "You can't get an access token or log in to this app from an insecure page. Try re-loading the page as https://"

Expected behavior:
Can oauth success.
Video/Screenshot link (optional):

Note: I research Policy of Facebook have a change details [here](https://developers.facebook.com/docs/facebook-login/security#https).  

> On October 6, 2018, all apps will be required to use HTTPS.

My solution is override method `list_providers` in class `OAuthLogin` of module `auth_oauth` change `return_url = request.httprequest.url_root + 'auth_oauth/signin'` from 'http' to `https`.

Hope this issues to be review. 
Thanks.

**Comment by Yenthe666** [comment] 2018-12-05 07:12
@tde-banana-odoo or @tivisse could one of you check this please?

**Comment by pedrobaeza** [comment] 2018-12-05 08:14
The problem is in your deployment, being HTTP. You should deploy a reverse proxy with SSL security. As there has been already some ping by my colleague, I wait for their confirmation.

**Comment by pedrobaeza** [comment] 2018-12-05 08:33
Then I think you should have something incorrect in your Proxy configuration, as this is working on my side. Please check install instructions: https://www.odoo.com/documentation/11.0/setup/install.html.

**Comment by Yenthe666** [comment] 2018-12-05 08:40
@pedrobaeza do you have it running & working fine on a V12?

**Comment by pedrobaeza** [comment] 2018-12-05 08:41
No, on v11, but AFAIK, this hasn't changed from v11 to v12.

**Comment by LeCaoPhuc** [comment] 2018-12-05 08:46
Hi all !
Thanks for reply. 
I will check again when has an time because I resolve it with my solution on above and i don't find other anyway to resolve it.
My code override [here](https://github.com/LeCaoPhuc/moretarget/blob/master/test_module/controllers/controllers.py).
Hope this issues to be look like.

**Comment by KevinSawyer** [comment] 2018-12-05 14:55
I have the same issue.  I am using Apache as a reverse proxy with SSL cert from LE, Odoo v11CE.  All http is redirected to https after which reverse proxy sends it to Odoo on port 8069.  web.base.url is set with https and web.base.url.freeze is True.  However, the URL generated relative to the "Log in with Facebook" link does not have https, only http, in the redirect URI, etc:

`https://www.facebook.com/dialog/oauth?redirect_uri=http%3A%2F%2Fmydomain.com%2Fauth_oauth%2Fsignin&scope=public_profile%2Cemail&response_type=token&client_id=705266863150553&state={%22r%22%3A+%22http%253A%252F%252Fmydomain.com%252Fweb%22%2C+%22p%22%3A+2%2C+%22d%22%3A+%22db_demo%22}`

**Comment by KevinSawyer** [comment] 2018-12-09 17:59
I've checked and double-checked my configuration, and I followed the Apache2 reverse proxy setup from https://antiun.github.io/odoo-reverse-proxy-howto.   The the URL generated by Odoo for the "Log in with Facebook" link still does not contain https and is therefore still rejected by Facebook.  If this is not a bug, then what else can it be, @pedrobaeza?

**Comment by pedrobaeza** [comment] 2018-12-09 18:38
Well, that guide is not official and it's very old, so I can't assure that following it is guarantee of success. I'm letting this opened any way if somebody can add extra explanations.

**Comment by KevinSawyer** [comment] 2018-12-09 18:41
Is there another reverse proxy guide that you recommend?  I've found several, and they all seem to show the same configuration for reverse proxy.

**Comment by pedrobaeza** [comment] 2018-12-09 18:42
I have forgotten all of this thanks to our Docker project: https://github.com/Tecnativa/doodba. You can try to deploy with it to see.

**Comment by KevinSawyer** [comment] 2018-12-09 18:42
OK, I'll take a look.  Thank you.  I suppose I could also look through the code and see how the Facebook log on URL is generated, but I think it still stands to reason that it should be using the value of web.base.url.

**Comment by zeroboss2006** [comment] 2019-08-15 13:42
I have Successful execution Nginx as a Reverse Proxy
referenced 
https://linuxize.com/post/configure-odoo-with-nginx-as-a-reverse-proxy/
https://alanhou.org/server-deployment/


Need root to run install
```
apt-get update
apt-get install software-properties-common -y
add-apt-repository universe
add-apt-repository ppa:certbot/certbot
apt-get update
apt-get install certbot python-certbot-nginx -y
```

Create credentials
```
certbot certonly --standalone -n --agree-tos -m youremail@example.com -d odoo.example.com
service nginx stop
```

modify  odoo-server.conf
`vim /etc/odoo-server.conf`
`proxy_mode = True`

modify  default
`vim /etc/nginx/sites-enabled/default`

```
upstream odoo.example.com {
	server 127.0.0.1:8069;
}

upstream odoo-chat.example.com {
	server 127.0.0.1:8072;
}

server {
	listen 80;
	server_name nester-toys.byi-e.com;
	return 301 https://odoo.example.com$request_uri;
}

server {
	listen 443;
	server_name nester-toys.byi-e.com;
	proxy_read_timeout 720s;
	proxy_connect_timeout 720s;
	proxy_send_timeout 720s;

	ssl on;
	ssl_certificate /etc/letsencrypt/live/nester-toys.byi-e.com/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/nester-toys.byi-e.com/privkey.pem;
	ssl_session_timeout 30m;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	ssl_ciphers "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384";
	ssl_prefer_server_ciphers on;

	access_log /var/log/nginx/odoo.access.log;
	error_log /var/log/nginx/odoo.error.log;

	gzip on;
	gzip_types text/css text/scss text/plain text/xml application/xml application/json application/javascript;

	proxy_set_header X-Forwarded-Host $host;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Proto $scheme;
	proxy_set_header X-Real-IP $remote_addr;
	
	location /longpolling {
		proxy_pass http://odoo-chat.example.com;
	}
	
	location / {
	proxy_redirect off;
	proxy_pass http://odoo.example.com;
	}
	
	location ~* /web/static/ {
	proxy_cache_valid 200 60m;
	proxy_buffering on;
	expires 864000;
	proxy_pass http://odoo.example.com;
	}

	#ssl_session_cache shared:SSL:50m;
	#ssl_session_tickets off;
	#ssl_dhparam /path/to/dhparam.pem;

	#add_header Strict-Transport-Security max-age=15768000;

	#ssl_stapling on;
	#ssl_stapling_verify on;
	#ssl_trusted_certificate /path/to/root_CA_cert_plus_intermediates;
	#resolver 8.8.8.8 8.8.4.4;
}
```
Then restart the service
```
service odoo-server restart
service nginx restart
```

**Comment by zeroboss2006** [comment] 2019-08-15 13:44
But I encountered a difficulty later
I can't use "Facebook Graph" properly

**Comment by mart-e** [comment] 2019-11-06 07:18
Closing as very likely to be a deployment issue
See the documentation page about HTTPS deployment https://www.odoo.com/documentation/12.0/setup/deploy.html#https
Also check #23812 which is about the same problem

**Closed by mart-e** 2019-11-06 07:18 UTC
Labels: 12.0, Services

**Comment by f0f0-cr** [comment] 2020-10-18 14:20
If the URL Odoo is passing to Facebook is not "https" there might be something wrong with Proxy config.

On the other hand, there is one extra configuration in Facebook to make this to work and this is not documented in "deploy" Odoo docs.

Make sure the "Valid OAuth Redirect URIs" is set to "**https://YOURDOMAIN/auth_oauth/signin**" under "https://developers.facebook.com -> YOURAPP -> Products -> Facebook Login -> Settgins -> Client OAuth Settings"

![image](https://user-images.githubusercontent.com/23691117/96370257-72561c80-111a-11eb-8fe9-1f8b7c4b6144.png)
