### ISSUE TITLE
Raise error when reconcile invoices in USD with payments in MXN

### ISSUE THREAD

**Issue by alan196** [odoo/odoo#14158] opened 2016-11-04 23:43 UTC
Configuration:
- Company Currency: MXN
- Tax 16%.
- Multicurrency, MXN and USD.
- Decimal precision: 4
- Currency Data:
MXN: rate 1.0
USD rates

| Database time | rate | Local time (Mexico) | 
| --- | --- | --- |
| 2016-09-09 00:00:01 | 0.054440 | 2016-09-08 17:00:01 |
| 2016-10-11 00:00:01 | 0.051815 | 2016-10-10 17:00:01 |

Steps to reproduce:

1. Create an invoice for 600 USD  + tax (16%) with date 09/09/16 (September 9, 2016) and when you validate in the journal entry is $12,784.7172 MXN.
3. Create a bank statement in MXN and add a line with date 11/10/16 (October 11, 2016) and amount $13,372.80 MXN.
4. When reconcile select the invoice and there is a difference ($588.0828 MXN) add a line with the difference and select an account for the difference. 
<img width="607" alt="captura de pantalla 2016-11-04 a la s 17 23 26" src="https://cloud.githubusercontent.com/assets/6758279/20025385/749605a2-a2b3-11e6-8b1a-4e9fbf1521ed.png">

**Note that the amount of difference is $588.08 in when you select the account**

5. Click on reconcile.

Expected behavior:
- Reconcile the invoice and create account move.

Current behavior:
- Raise an error  `Wrong credit or debit value in accounting entry !`

![captura de pantalla 2016-11-01 a la s 19 18 52](https://cloud.githubusercontent.com/assets/6758279/19913537/1c272866-a069-11e6-9b06-5851681c7fa5.png)

**Comment by nim-odoo** [comment] 2016-11-22 15:04
For the record, I corrected the rates of your example to match the numbers. There was probably a confusion in the rate used since the invoice uses a date field, while a currency rate uses a datetime field (due to timezone). Anyway, I could reproduce on my end and the fix will land shortly.

**Comment by nim-odoo** [comment] 2016-11-22 15:50
Fixed with https://github.com/odoo/odoo/commit/27b6d245e79cc0ae5cbd1cdc9ee1fe388075d333

**Closed by nim-odoo** 2016-11-22 15:50 UTC
