### ISSUE TITLE
i get message odoo session expired + dynamic products do not appear for website visitor while appear for signed users

### ISSUE THREAD

**Issue by maherkhalil07** [odoo/odoo#64294] opened 2021-01-09 13:59 UTC
Impacted versions: 14

Steps to reproduce:install odoo then website and e commerce + template no 6 in website templates

Current behavior: i get message odoo session expired + dynamic products do not appear for website visitor while appear for signed users

Expected behavior: no session expired message should not appear while dynamic products should appear for visitor

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):
![odoo_session](https://user-images.githubusercontent.com/38738435/104093506-9ba6c480-5293-11eb-9209-c2c2a20e8c1d.png)

**Comment by pedrobaeza** [comment] 2021-01-09 19:04
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by maherkhalil07** [comment] 2021-01-09 20:58
I will try to reproduce it and report back to you

**Comment by maherkhalil07** [comment] 2021-01-09 21:08
Hello
I reproduced it in runbot 
I share video for problem in runbot and my system
I am very open and you can ask anything I will reply 
I compressed the video then I can upload it

[session problem.zip](https://github.com/odoo/odoo/files/5791825/session.problem.zip)

**Comment by maherkhalil07** [comment] 2021-01-09 21:11
My system was working in very good condition then the problem happen after I updated it 2 or 3 days ago.
I can go back to previous snapshoot for whole system but I would like to participate to improve the system since I started to use the community version

**Comment by pedrobaeza** [comment] 2021-01-11 08:19
But I see that you are doing logout. Sorry, but you need to give exact reproducible steps for the problem. I don't see them.

**Comment by maherkhalil07** [comment] 2021-01-11 20:35
the message of session expires appear only when I log out. It should not appear

**Comment by pedrobaeza** [comment] 2021-01-11 20:38
What is the problem with that? You have logged out, so the session is no more valid...

**Comment by maherkhalil07** [comment] 2021-01-11 20:40
when I open the website from another browser as normal visitor, the message appear and when and when I click the ok button under the message, the home page refresh. that should not happen to normal visitor, also the dynamic product disappear from the page (only the block of products)

**Comment by maherkhalil07** [comment] 2021-01-11 23:20
The problem comes from dynamic snippets, dynamic carousel and dynamic products

**Comment by pedrobaeza** [comment] 2021-01-12 07:34
On other device or the same?

**Comment by maherkhalil07** [comment] 2021-01-12 12:33
If checked in other devices, the problem still happen, dynamic snippets, dynamic carousel and dynamic products do not appear and the message come.
I also have demo server working in good condition without any of dynamic snippets, dynamic carousel and dynamic products.
I added them (them=dynamic snippets, dynamic carousel and dynamic products) to website then the problem happen then I removed them back then the problem disappear

**Comment by maherkhalil07** [comment] 2021-01-12 12:44
I checked also Firefox debugger using "F12", I found the disappeared section has class "d-none" which I think should not come here
![Screenshot 2021-01-12 14:43:17](https://user-images.githubusercontent.com/38738435/104316103-a73cfa00-54e4-11eb-9045-ab5b68e3b10a.png)

**Comment by maherkhalil07** [comment] 2021-01-14 17:36
Hello, Anything I can do?

**Comment by maherkhalil07** [comment] 2021-01-26 13:36
Hello 
It is solved in today odoo update

**Comment by maherkhalil07** [comment] 2021-01-26 13:37
Hello
It is solved in today Odoo update on January 26, 2021
Thanks

**Closed** 2021-01-26 13:37 UTC
Labels: 14.0, Website

**Comment by sezginzerdelci** [comment] 2021-01-28 11:06
hello maherkhalil07,

Can I learn how I need to update, please? i am having the same problem. I am using version 14.

**Comment by pbanswer** [comment] 2022-04-27 12:43
Perhaps i have the similar problem . When i create dynamic snippet, it works correctly only if you log in like an administrator account, snippet uses data from the odoo model. So if you log in as a public user, odoo displays a message, something like

"Odoo session is expired. The current page is about to be refreshed."

, and snippet uses default content from template(not data from database).

I didn't find an answer to my question in the documentation or on the forums. Please, if anyone has encountered such a problem, write how you solved it. Thank you in advance. p.s.: clearing the cache does not help
