### ISSUE TITLE
SQL Error When Ordering Product

### ISSUE THREAD

**Issue by physiii** [odoo/odoo#38884] opened 2019-10-16 13:29 UTC
I'm Odoo 13.0 and when I add a product to checkout then try to validate payment, I get the following server error:

```
2019-10-16 13:16:47,078 24898 ERROR pyfi odoo.sql_db: bad query: INSERT INTO "pos_order" ("id", "create_uid", "create_date", "write_uid", "write_date", "amount_paid", "amount_return", "amount_tax", "amount_total", "company_id", "crm_team_id", "customer_count", "date_order", "employee_id", "fiscal_position_id", "name", "nb_print", "partner_id", "pos_reference", "pricelist_id", "sequence_number", "session_id", "state", "table_id", "to_invoice", "user_id") VALUES (nextval('pos_order_id_seq'), 2, (now() at time zone 'UTC'), 2, (now() at time zone 'UTC'), 103.19, 6.8100000000000005, 8.19, 103.19, 1, 3, 1, '2019-10-16 13:16:47', 2, NULL, '/', 0, 1, 'Order 00008-006-0001', 1, 1, 8, 'draft', NULL, false, 2) RETURNING id                                      
ERROR: insert or update on table "pos_order" violates foreign key constraint "pos_order_employee_id_fkey"                                                                                    
DETAIL:  Key (employee_id)=(2) is not present in table "hr_employee".
```

Front end images:

![odoo-checkout](https://user-images.githubusercontent.com/6277642/66923646-d4071680-efee-11e9-814e-92cf8bd4ccb5.png)
![odoo-error](https://user-images.githubusercontent.com/6277642/66923647-d4071680-efee-11e9-9b68-e0e9fc2c3174.png)

Idea's on how to fix this?

**Comment by physiii** [comment] 2019-10-18 13:48
BUMP.

Should I revert to an older version and test?

**Comment by switch87** [comment] 2019-10-21 07:56
@physiii I cannot reproduce this problem with the provided information. I tried closing an order with user login and employee login, both still work in the newest build.

**Comment by pimodoo** [comment] 2019-10-21 08:09
@physiii Hello, thanks for your feedback, it should have been fixed three days in pr: https://github.com/odoo/odoo/pull/39028 could you update your sources and confirm us that you don't have trouble anymore?

**Closed by pimodoo** 2019-10-21 08:09 UTC
Labels: 13.0, Point of Sale
