### ISSUE TITLE
[10.0]price_unit doesn't update while create purchase order lines with more than two same product_id in one purchase order.

### ISSUE THREAD

**Issue by yueqin** [odoo/odoo#18054] opened 2017-07-06 02:05 UTC
Impacted versions:
[10.0]
Steps to reproduce:
1. create a purchase order;
2. add one purchase order line with product_id: a;
3. add another purchase order line with product_id:a with different plan_date,
Current behavior:
The product_id a's Unit Price doesn't updated.
Expected behavior:
Every Lines with product_id a need update there Unit Price depends on the product_qty of all.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment] 2017-07-06 07:39
@nim-odoo could you look at this, please?

**Comment by yueqin** [comment] 2017-07-08 02:18
@Yenthe666  @nim-odoo  Could you look at this,please.

**Comment by pedrobaeza** [comment] 2018-06-02 12:18
I have just tried on runbot and it's working correctly:

![seleccion_013](https://user-images.githubusercontent.com/7165771/40874455-b6d0dbbe-666f-11e8-8c75-12acf7bde421.png)

so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-06-02 12:18 UTC
Labels: 10.0
