### ISSUE TITLE
When a user refreshes the Odoo page, the system reloads the page with someone else account

### ISSUE THREAD

**Issue by Tariqlab** [odoo/odoo#59981] opened 2020-10-14 10:57 UTC
Impacted versions:
Odoo-13
Steps to reproduce:
When a user refreshes the Odoo page, the system reloads the page with someone else account.
This incident has happened 3 times during two months
Current behavior:
If the user refresh page Odoo reloads the page with someone else account.
Expected behavior:
When user refresh page system reloads the page with user account

**Comment by pedrobaeza** [comment] 2020-10-14 11:01
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Closed** 2023-04-07 14:17 UTC
Labels: Need information
