### ISSUE TITLE
Access rights error on using the partner merge wizard

### ISSUE THREAD

**Issue by niyasraphy** [odoo/odoo#71829] opened 2021-06-07 16:34 UTC
Impacted versions: Odoo 14

Steps to reproduce: 
1. Open contacts tree view
2. Select two records from tree view, click Action -> Merge
3. Click Skip These Contacts, Click Deduplicate The Other Contacts
4. Select Name from wizard
5. Click Merge With Manual Check, and click Skip these contacts

Current behavior: Access rights error

Expected behavior: Next set of contacts has to be shown

![Screenshot from 2021-06-07 19-28-46](https://user-images.githubusercontent.com/27989791/121056843-4e3d6d80-c7c7-11eb-8718-124781547fc8.png)

**Comment by pedrobaeza** [comment] 2021-06-07 20:50
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by niyasraphy** [comment] 2021-06-08 01:48
Hi,
The image i have added is from the runbot, i will share a video of the same


https://user-images.githubusercontent.com/27989791/121109648-a6e72780-c814-11eb-96d5-8e3c2c6332d1.mp4

**Closed** 2023-01-14 17:37 UTC
Labels: 14.0
