### ISSUE TITLE
short dump in closing MO

### ISSUE THREAD

**Issue by ccandito** [odoo/odoo#14306] opened 2016-11-14 13:47 UTC
Impacted versions:
10
Steps to reproduce:
entering analytic account in WC master data

Current behavior:
a short dump's occurred when marking as done the related MO
system log is reported below

by removing the analytic account no dump occurs anymore

Expected behavior:
no dump at all
actual value posted in analytic account for labor costs

Video/Screenshot link (optional):

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 866, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/var/lib/odoo/.local/share/Odoo/addons/10.0/quality_mrp/models/mrp_production.py", line 92, in button_mark_done
    return super(MrpProduction, self).button_mark_done()
  File "/var/lib/odoo/.local/share/Odoo/addons/10.0/mrp_account/models/mrp_production.py", line 63, in button_mark_done
    self._costs_generate()
  File "/var/lib/odoo/.local/share/Odoo/addons/10.0/mrp_account/models/mrp_production.py", line 43, in _costs_generate
    value = wc_line.hour * wc.costs_hour
AttributeError: 'mrp.workorder' object has no attribute 'hour'

**Comment by Yenthe666** [comment] 2018-02-16 11:09
Hi @ccandito,

Thanks a lot for the bug report.
I've just tried to reproduce this but the issue seems to be fixed in the meanwhile.
Please update your local Odoo instance in order to fix this issue.

Regards,
Yenthe

**Closed by Yenthe666** 2018-02-16 11:09 UTC
Labels: 10.0, Logistics
