### ISSUE TITLE
[10.0] ValueError: Wrong value for base.language.install.lang: u'en_GB'

### ISSUE THREAD

**Issue by CybroOdoo** [odoo/odoo#24975] opened 2018-05-30 05:20 UTC
Impacted versions:
Odoo v10.0

Steps to reproduce:
While creating the Database.

Current behavior:

Traceback (most recent call last):
  File "/home/cybrosys/Odoos/odoo-10.0/odoo/http.py", line 118, in dispatch_rpc
    result = dispatch(method, params)
  File "/home/cybrosys/Odoos/odoo-10.0/odoo/service/common.py", line 57, in dispatch
    return g[exp_method_name](*params)
  File "/home/cybrosys/Odoos/odoo-10.0/odoo/service/common.py", line 29, in exp_authenticate
    res_users = odoo.registry(db)['res.users']
  File "/home/cybrosys/Odoos/odoo-10.0/odoo/__init__.py", line 52, in registry
    return modules.registry.Registry(database_name)
  File "/home/cybrosys/Odoos/odoo-10.0/odoo/modules/registry.py", line 59, in __new__
    return cls.new(db_name)
  File "/home/cybrosys/Odoos/odoo-10.0/odoo/modules/registry.py", line 83, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/cybrosys/Odoos/odoo-10.0/odoo/modules/loading.py", line 289, in load_modules
    tools.load_language(cr, lang)
  File "/home/cybrosys/Odoos/odoo-10.0/odoo/tools/translate.py", line 1201, in load_language
    installer = env['base.language.install'].create({'lang': lang})
  File "/home/cybrosys/Odoos/odoo-10.0/odoo/models.py", line 3847, in create
    record = self.browse(self._create(old_vals))
  File "/home/cybrosys/Odoos/odoo-10.0/odoo/models.py", line 3927, in _create
    self._check_selection_field_value(name, val)
  File "/home/cybrosys/Odoos/odoo-10.0/odoo/models.py", line 2131, in _check_selection_field_value
    field.convert_to_cache(value, self)
  File "/home/cybrosys/Odoos/odoo-10.0/odoo/fields.py", line 1791, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for base.language.install.lang: u'en_GB'

Expected behavior:

Video/Screenshot link (optional):
![111](https://user-images.githubusercontent.com/15099781/40700483-5036125e-63f7-11e8-8631-589b06aabb31.png)

**Comment by pedrobaeza** [comment] 2018-05-30 07:03
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/10.0/setup/install.html. Specifically, this seems to be the OS language forced to `en_GB`, which is not a valid.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

**Closed by pedrobaeza** 2018-05-30 07:03 UTC

**Comment by Yenthe666** [comment] 2018-05-31 11:07
@pedrobaeza to be fair, the builds are only in English so the runbot doesn't catch that. But I can't reproduce it locally. 😉

**Comment by pedrobaeza** [comment] 2018-05-31 11:09
Yeah, that's my saved reply. That's why I have added later "Specifically, this seems to be the OS language forced to en_GB, which is not a valid."

**Comment by optimum-web** [comment] 2018-08-22 11:09
Same here,  
**Database creation error: Wrong value for base.language.install.lang: u'en_US'**
Please reopen this issue, it's not fixed, Odoo 10.0,  postgres:9.6,

**Comment by pedrobaeza** [comment] 2018-08-22 11:11
@optimum-web, this seems more related to your deployment, so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/10.0/setup/install.html.

**Comment by optimum-web** [comment] 2018-08-22 13:01
Already checked that.  Does not work with postgres 9.4.  I use docker deployment.

**Comment by optimum-web** [comment] 2018-08-22 13:01
and 9.6  gives same error

**Comment by pedrobaeza** [comment] 2018-08-22 14:28
I can assure you it's working, as you can see on runbot or the multiple installations out there. You have to check all your environment, and maybe try on a fresh system. If still not working, you should ask on the Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).

**Comment by optimum-web** [comment] 2018-08-28 10:19
Ok, the issue was in docker-compose.yml  
` volumes:
      - odoo-web-data:/var/lib/odoo`

from https://hub.docker.com/_/odoo/,  
it was mounted with root permissions and "odoo" user could not write to it. 
`odoo     |   File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 208, in _inverse_datas
odoo     |     vals['store_fname'] = self._file_write(value, vals['checksum'])
odoo     |   File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 108, in _file_write
odoo     |     fname, full_path = self._get_path(bin_value, checksum)
odoo     |   File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 89, in _get_path
odoo     |     os.makedirs(dirname)
odoo     |   File "/usr/lib/python2.7/os.py", line 150, in makedirs
odoo     |     makedirs(head, mode)
odoo     |   File "/usr/lib/python2.7/os.py", line 157, in makedirs
odoo     |     mkdir(name, mode)
odoo     | ParseError: "13
odoo     | Permission denied" while parsing /usr/lib/python2.7/dist-packages/odoo/addons/base/base_data.xml:17, near
odoo     | <record id="main_partner" model="res.partner" context="{'default_is_company': True}">
odoo     |             <field name="name">My Company</field>
odoo     |             <field name="company_id" eval="None"/>
odoo     |             <field name="image" type="base64" file="base/static/img/main_partner-image.png"/>
odoo     |             <field name="customer" eval="False"/>
odoo     |             <field name="is_company" eval="True"/>
odoo     |             <field name="street"/>
odoo     |             <field name="city"/>
odoo     |             <field name="zip"/>
odoo     |             <field name="phone"/>
odoo     |             <field name="email">info@yourcompany.com</field>
odoo     |             <field name="website">www.yourcompany.com</field>
odoo     |         </record>
odoo     | 2018-08-28 10:03:51,559 14 INFO test2 odoo.modules.loading: loading 1 modules...
odoo     | 2018-08-28 10:03:51,576 14 INFO test2 odoo.modules.loading: 1 modules loaded in 0.02s, 0 queries
odoo     | 2018-08-28 10:03:51,599 14 WARNING test2 odoo.modules.loading: Transient module states were reset
odoo     | 2018-08-28 10:03:51,600 14 ERROR test2 odoo.modules.registry: Failed to load registry
odoo     | Traceback (most recent call last):
odoo     |   File "/usr/lib/python2.7/dist-packages/odoo/modules/registry.py", line 83, in new
odoo     |     odoo.modules.load_modules(registry._db, force_demo, status, update_module)
odoo     |   File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 327, in load_modules
odoo     |     tools.load_language(cr, lang)
odoo     |   File "/usr/lib/python2.7/dist-packages/odoo/tools/translate.py", line 1201, in load_language
odoo     |     installer = env['base.language.install'].create({'lang': lang})
odoo     |   File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3847, in create
odoo     |     record = self.browse(self._create(old_vals))
odoo     |   File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3927, in _create
odoo     |     self._check_selection_field_value(name, val)
odoo     |   File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 2131, in _check_selection_field_value
odoo     |     field.convert_to_cache(value, self)
odoo     |   File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 1791, in convert_to_cache
odoo     |     raise ValueError("Wrong value for %s: %r" % (self, value))
odoo     | ValueError: Wrong value for base.language.install.lang: u'en_US'
odoo     | 2018-08-28 10:03:51,601 14 ERROR test2 odoo.http: Wrong value for base.language.install.lang: u'en_US'
odoo     | Traceback (most recent call last):
odoo     |   File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 118, in dispatch_rpc
odoo     |     result = dispatch(method, params)
odoo     |   File "/usr/lib/python2.7/dist-packages/odoo/service/common.py", line 57, in dispatch
odoo     |     return g[exp_method_name](*params)
odoo     |   File "/usr/lib/python2.7/dist-packages/odoo/service/common.py", line 29, in exp_authenticate
odoo     |     res_users = odoo.registry(db)['res.users']
odoo     |   File "/usr/lib/python2.7/dist-packages/odoo/__init__.py", line 52, in registry
odoo     |     return modules.registry.Registry(database_name)
odoo     |   File "/usr/lib/python2.7/dist-packages/odoo/modules/registry.py", line 59, in __new__
odoo     |     return cls.new(db_name)
odoo     |   File "/usr/lib/python2.7/dist-packages/odoo/modules/registry.py", line 83, in new
odoo     |     odoo.modules.load_modules(registry._db, force_demo, status, update_module)
odoo     |   File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 327, in load_modules
odoo     |     tools.load_language(cr, lang)
odoo     |   File "/usr/lib/python2.7/dist-packages/odoo/tools/translate.py", line 1201, in load_language
odoo     |     installer = env['base.language.install'].create({'lang': lang})
odoo     |   File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3847, in create
odoo     |     record = self.browse(self._create(old_vals))
odoo     |   File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3927, in _create
odoo     |     self._check_selection_field_value(name, val)
odoo     |   File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 2131, in _check_selection_field_value
odoo     |     field.convert_to_cache(value, self)
odoo     |   File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 1791, in convert_to_cache
odoo     |     raise ValueError("Wrong value for %s: %r" % (self, value))
odoo     | ValueError: Wrong value for base.language.install.lang: u'en_US'`

So the error message is not correct.  People must see "Permission denied"  error too for addons or any other mounted directory. 

The solution for me was commenting out
` volumes:
      #- odoo-web-data:/var/lib/odoo`

another solution is to use  same GID and UID on host machine and container.

**Comment by optimum-web** [comment] 2018-08-28 10:34
I think Issue is related to this one  https://github.com/odoo/docker/issues/97

**Comment by zakali** [comment] 2019-06-18 19:04
make sure you have correct version of YML package.

**Comment by captivea-jpa** [comment] 2019-07-17 10:00
Indeed,

I have the same problem with a fresh install of Odoo 11 CE, with any problem of the postgresql client encoding (UTF8 everywhere), but one with "yaml.load() without Loader...", and as mentioned here:

https://www.odoo.com/fr_FR/forum/aide-1/question/having-yaml-constructor-constructorerror-while-installing-apps-sales-management-inventory-management-etc-147961

The version of PyYAML should be below 4 => problem solved!
