### ISSUE TITLE
Bank statelment reconcile auto fill tax id from account properties

### ISSUE THREAD

**Issue by rosenvladimirov** [odoo/odoo#28906] opened 2018-11-21 12:03 UTC
Impacted versions: 11.0

Steps to reproduce: when start payment reconcile in manual mode, and when selecting the account does not automatically fill in the fiscal position

Current behavior: The Fiscal position is configured in Account setting.

Expected behavior: Auto fill Fiscal position when worked with account without product only on invoices is worked correct, but in bank statement on manual mod is not worked.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2018-11-21 12:06
I'm not sure what you are talking about. Can you please add some screenshots of what do you refer?

**Comment by rosenvladimirov** [comment] 2018-11-21 12:20
[
![2018-11-21 14-14-52](https://user-images.githubusercontent.com/6825051/48840927-a3940980-ed98-11e8-88c6-74481d98f824.png)
](url)

**Comment by pedrobaeza** [comment] 2018-11-21 12:23
And in what fiscal position is involved with the screenshot?

**Comment by pedrobaeza** [comment] 2018-11-21 12:38
I think you are mixing terminology, saying FP instead of Taxes. Any way, this is something expected, as default taxes are only applied on manual journal entries, not in account reconciliation. If you want to have predefined taxes, use a reconciliation model and put taxes there.

Closing as no real issue, but intended behavior (or lack of behavior).

**Closed by pedrobaeza** 2018-11-21 12:38 UTC
Labels: Need information
