### ISSUE TITLE
auto_join incorrect results for ['|', (field.name, '=', 'something'), ('field, '=', False)]

### ISSUE THREAD

**Issue by StefanRijnhart** [odoo/odoo#25175] opened 2018-06-10 15:01 UTC
Impacted versions:
8.0 up to Master

Steps to reproduce:
Set auto_join = true for some Many2one field. Combine a subsearch with a search on False.

Current behavior:
Records without the relational field set are not returned

Expected behavior:
Both records without the relational field and records matching the subsearch are returned

Below is an example in which res.partner's `state_id` is set to auto_join. We can search for partners without state_id and we can search partners in Florida but the combined query only returns the partners in Florida.

```
>>> session.env['res.partner'].search([('state_id', '=', False)])
2018-06-10 14:54:17,182 17553 DEBUG 11master odoo.sql_db: query: SELECT "res_partner".id FROM "res_partner" WHERE (("res_partner"."active" = true)  AND  "res_partner"."state_id" IS NULL ) ORDER BY "res_partner"."display_name"  
res.partner(10, 36, 31, 19, 18, 9, 40, 24, 17, 41, 42, 16, 14, 28, 34, 27, 11, 20, 22, 33, 23, 15, 35, 8, 7)

>>> session.env['res.partner'].search([('state_id.name', '=', 'Florida')])
2018-06-10 14:54:50,990 17553 DEBUG 11master odoo.sql_db: query: SELECT "res_partner".id FROM "res_country_state" as "res_partner__state_id","res_partner" WHERE ("res_partner"."state_id"="res_partner__state_id"."id") AND (("res_partner"."active" = true)  AND  ("res_partner__state_id"."name" = 'Florida')) ORDER BY "res_partner"."display_name"  
res.partner(13, 29, 30)

>>> session.env['res.partner'].search(['|', ('state_id', '=', False), ('state_id.name', '=', 'Florida')])
2018-06-10 14:54:06,991 17553 DEBUG 11master odoo.sql_db: query: SELECT "res_partner".id FROM "res_country_state" as "res_partner__state_id","res_partner" WHERE ("res_partner"."state_id"="res_partner__state_id"."id") AND (("res_partner"."active" = true)  AND  ("res_partner"."state_id" IS NULL   OR  ("res_partner__state_id"."name" = 'Florida'))) ORDER BY "res_partner"."display_name"  
res.partner(13, 29, 30)
```

**Comment by Elkasitu** [comment] 2018-06-11 06:16
We're aware of this issue (https://github.com/odoo/odoo/issues/22661, https://github.com/odoo/odoo/issues/23808).

The problem itself is with `OR` operations and `auto_join`, it works with `AND` (by chance, mind you) and we're working on a fix for v12, hopefully.

I don't think we'll be able to implement a fix for stable versions because it requires a refactoring of `expression.py`.

A simple workaround would be to do the two operands of the `OR` as two separate queries and then use set operations between the two recordsets.

**Comment by StefanRijnhart** [comment] 2018-06-11 12:10
I committed a fix for master and a backport to Odoo 8.0

**Comment by ThomasBinsfeld** [comment] 2019-10-17 14:21
@Elkasitu Any news on this?

**Comment by pedrobaeza** [comment] 2020-12-03 19:57
@Elkasitu we have been hit by this again. Is there any news on a possible fix at framework level?

**Comment by Elkasitu** [comment] 2020-12-04 09:39
@pedrobaeza this specific issue should've been fixed by https://github.com/odoo/odoo/pull/49999

**Comment by pedrobaeza** [comment] 2020-12-04 09:41
Good to know, so it should land since 14.0, isn't it?

**Comment by Elkasitu** [comment] 2020-12-04 10:16
> Good to know, so it should land since 14.0, isn't it?

Yes, I'm gonna close the issue for now, feel free to reopen if it's still not working as intended

**Closed by Elkasitu** 2020-12-04 10:16 UTC
Labels: 10.0, 11.0, 9.0, Framework, ORM
