### ISSUE TITLE
[14.0] [mass_mailing] No drag and drop when browser scale > 100%

### ISSUE THREAD

**Issue by feelwhy** [odoo/odoo#63306] opened 2020-12-14 10:38 UTC
Impacted versions:
14.0

Steps to reproduce:
 1. Change browser scale for more than 100% (for example, to 125% - which is default for many notebooks)
 2. Refresh browser page with Odoo
 3. Create New mailing
 4. Choose theme
 5. Try to drag and drop any building block

Current behavior:
 * Building block can't be selected 
 * The error occurs:
"""
Uncaught TypeError: Cannot read property 'contains' of undefined
    at Class._onSmoothDragStart (web.assets_common.js:5048)
    at HTMLDivElement.start (web.assets_common.js:5028)
    at $.<computed>.<computed>._trigger (web.assets_common.js:2090)
    at $.<computed>.<computed>._trigger (web.assets_common.js:2229)
    at $.<computed>.<computed>._trigger (web.assets_common.js:2060)
    at $.<computed>.<computed>._mouseStart (web.assets_common.js:2153)
    at $.<computed>.<computed>._mouseStart (web.assets_common.js:2060)
    at $.<computed>.<computed>._mouseMove (web.assets_common.js:2137)
    at $.<computed>.<computed>._mouseMove (web.assets_common.js:2060)
    at HTMLDocument._mouseMoveDelegate (web.assets_common.js:2134)
"""

Expected behavior:
 * No errors and it is possible to build a new email under any browser scale

**Comment by pedrobaeza** [comment] 2020-12-14 13:06
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by feelwhy** [comment] 2020-12-14 13:30
Hi!
Yes the same error is re-produced on the runbot as well (look at the attached screen shot)

![scrolltop](https://user-images.githubusercontent.com/42974129/102086177-b454c380-3e28-11eb-8ae9-6f84af3a4a26.png)

The error depends on:
1. The screen height (I mean your physical screen, since it influences window / document heigth)
2. The scale. It should be more than 100% scale. On the attached screen shot it is 150%
3. The field html height should be not very long (less than screen - e.g. empty)
Make sure after you scale the screen - you have refreshed the page (otherwise JavaScript variables would be taken as for the previous case).

We have investigated the issue quite a lot (regretfully, I can't reference at the moment the found JavaScript methods). Roughly: the point is that under the circumstances above the 'top scroll' param of a note body is calculated as less than real document height (something like 1113.86 px >= 1114 px results in false; in real ). Hence, one of the JavaScript checks is not passed, and drag&drop finds no position to be inserted.

**Comment by pedrobaeza** [comment] 2020-12-14 14:35
OK, thanks for the extra information

**Comment by feelwhy** [comment] 2021-01-11 16:36
Further investigations lead us to the following results:
    • The reason of such behavior is deep inside the lib jquery (web/static/src/js/libs/jquery.js) in the method 'getScrollingElement'
    • Under normal scale the document body height ($(document.body).height()) and the height of field wrap (div id='wrapwrap') is exactly the same. For example, 598 and 598. This is correct when field content is less than window height – so when you create a new object and the field is empty
    • When the window is zoomed (e.g. 125% in my experiments, or under full 4k resolution reported by our clients), the height of document is slightly changed. For example, under 125% scale it become 598.4 instead of normal 598
    • That is why the check el.scrollHeight < bodyHeight becomes incorrect, and the method does not return wrapwrap as a scrolling document. 

A solution (at least temporary?) would be to round the height for integers to the lesser numbers. So, to consider 598.4 as not less than 598. Or to replace the check to:

            if (bodyHeight - el.scrollHeight >= 1) {
                continue;
            }

Please take into account:
    • The issue does not relate only to mass_mailing, but it actually influences a lot of Odoo interfaces, although often not visible for the end users.
    • The issue is already reported by a few of our clients. It becomes really urgent. The recommendation to zoom the browser is very inconvenient, while really a lot notebooks and monitors have default 125% zoom or 4k resolutions
    * The issue relates to both Odoo Enterprise and Odoo community

Thanks!

**Comment by feelwhy** [comment] 2021-01-11 17:00
Another thing to mention: scrollHeight returns always a rounded integer: https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollHeight. 

So, comparing of height() to scrollHeight is incorrect. So, instead of scrollHeight it is recommended to use getBoundingClientRect(), what would be a technically correct solution (as far as the documentation states that).

**Comment by feelwhy** [comment] 2021-03-02 15:33
Hello! Is it possible to somehow consider the related PR https://github.com/odoo/odoo/pull/65543
It is a single-line change commit, which is reasoned by a direct reference from MDN web documentation. A lot of our clients have to work in Odoo with zoomed screen.
Thanks!

**Closed** 2021-03-16 15:53 UTC
Labels: 14.0, Web editor
