### ISSUE TITLE
[9.0] On invoices, open payment button is not doing anything.

### ISSUE THREAD

**Issue by nhomar** [odoo/odoo#8640] opened 2015-09-21 10:22 UTC
Hello.

Just open a paid invoice and the try to click on info button on the total section, then click on "open payment" anything is happening.

![INV](https://www.evernote.com/l/AJ7CWcJ1Q6JPtLalwMBJVYJT53z85mtApFsB/image.png)

**Comment by fpodoo** [comment] 2015-09-21 16:33
Hello,

We can't reproduce. When we click on "Open Payment", it opens the payment form as expected. I close the issue. Please reopen if you can give more information about how to reproduce.

Fabien

**Closed by fpodoo** 2015-09-21 16:33 UTC
