### ISSUE TITLE
Multi Website user account issue

### ISSUE THREAD

**Issue by frankmiao2015** [odoo/odoo#34308] opened 2019-06-22 03:21 UTC
Impacted versions: 12

For multi website, there is a tick choice under website setting: Specific User Account. For what I am understanding, if we do not tick the choice, all websites would share the same user account. When I sign up in one of the website as portal user, I do can login from other sites. But after I place one order on one of these websites, I can not login from other websites any more. I notice the Registration filed under the user contacts was blank for the first sign up. But it will be filled with the website once an order was placed on one of the website. And then all other website cannot log in anymore. I want to share all my customers across all my multi websites. And I saw this Specific User Account function. Is there something I understand wrong or is this a bug.

Thank you.

**Comment by pedrobaeza** [comment] 2019-06-23 22:06
@JKE-be maybe you can clarify this? I would say portal users can't be shared among several websites.

**Comment by frankmiao2015** [comment] 2019-06-24 03:07
@pedrobaeza But the websites do share the user for initial sign up before you place any order. And what is the website boolean Specific User Account function for? Thank you!

**Comment by JKE-be** [comment] 2019-06-24 08:43
> . But after I place one order on one of these websites, I can not login from other websites any more

If it is true, it sound like a bug.

**Comment by rdeodoo** [comment] 2019-06-24 11:55
I was not able to reproduce your issue, could please provide us a small 'step to reproduce' so we can investigate further?

So far, I tried different scenario and all worked fine:

- Creating the user from site 1 then creating an order from checkout on site 2, I am able to login on both sites and can see the order, the account is correctly shared.
- Creating the user from checkout on site 2, I am then able to login on site 1 with same account.

By worked fine, I mean:

- I was able to create the user, either from site 1 or site 2, and either during checkout or on signup page.
- I was able to login with that created user on the other site
- I was not able to signup on the other site with the same email (correct warning shows 'already existing account').

**Comment by frankmiao2015** [comment] 2019-06-24 14:38
@rdeodoo Thank you for looking into it. I just pulled the latest code and it still performs what I said. I have the following doubts for you.

1. Could you check if the customer's Registration Website field is filled with any website after your order is placed? If not, how the Sale Order Send Email template deal with the webiste_id? If yes, the customer is supposed only to login with the registration website. This is happens to internal users too. I once created an internal user and cannot login with another website. At last I found I have to remove the registration website for the user and then I can login with the other website. 

2. Could you have a try to log out and login in again for website B if you place the order on website A? I do can log in all website after sign up before I place any order.

Thank you!

**Comment by rdeodoo** [comment] 2019-06-26 14:09
I can confirm the behavior, going through checkout on a website with a shared user will add a website_id on that user (by adding it on its partner which is a related).
Then the user will lose the posibility to login to other websites.

A fix is coming ASAP, I will let you know once it is merged.

Thank you for reporting the issue.

**Closed** 2019-07-01 13:27 UTC
Labels: 12.0, Confirmed, Website
