### ISSUE TITLE
Readonly button not getting disabled

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#13264] opened 2016-08-23 13:25 UTC
Impacted versions: 9

Steps to reproduce: Add `readonly="True"` or `attrs="{'readonly':[('some_check','=',True)]}"` to a `oe_stat_button`.

Current behavior: Button does not get disabled.

Expected behavior: [Docs say:](https://www.odoo.com/documentation/9.0/reference/views.html#lists)

> Possible attributes are invisible (hides the button) and readonly (disables the button but still shows it)

That's what should happen.

Video/Screenshot link (optional):

![captura de pantalla de 2016-08-23 15-21-59](https://cloud.githubusercontent.com/assets/973709/17893363/b8973d04-6945-11e6-9d4d-cf839a4c7255.png)

@Tecnativa

**Comment by JKE-be** [comment] 2016-08-23 21:42
Hello, 
You are referring to the documentation of button from list view !

IMHO, It is actually not support in oe_stat_button.

@ged-odoo ... can you confirm it ?

**Comment by Yajo** [comment] 2016-08-24 07:50
Yes, but docs of form view say it behaves mostly the same... At least that's what I was expecting by reading the docs...

**Comment by simahawk** [comment] 2016-09-26 14:34
looks like setting `readonly="1"` onto any buttons in forms does not have any effect on them, you can still click on them.

**Comment by leorochael** [comment] 2017-08-22 19:56
This also happens on at least v8.0 and up to v10.0, and the documentation links for [both](https://www.odoo.com/documentation/8.0/reference/views.html) of [them](https://www.odoo.com/documentation/10.0/reference/views.html) still report `readonly` as a valid attribute that should disable the button.

**Comment by Yenthe666** [comment] 2017-08-24 08:44
@ged-odoo could you confirm this one?

**Comment by ged-odoo** [comment] 2017-08-24 09:22
@Yenthe666 I confirm the issue and the lack of documentation.  It comes from the fact that readonly modifiers are currently only defined for fields.  There is some confusion, most likely because the 'invisible' modifier can be applied to any node, not only fields.

Clearly, the 'required' modifiers only makes sense for fields.  But for 'readonly', this is an example of non-field where we have a default behaviour that make sense. I think that it seems very useful, so I support doing this change.

**Comment by ged-odoo** [comment] 2017-08-24 10:01
our CTO, which is apparently a complete usability expert, and whose opinion is worth more than everyone else, says that it is useless and it does not make sense and noone sane should use this...

so, I guess I'll close this...

**Closed by ged-odoo** 2017-08-24 10:01 UTC
Labels: confirmed

**Comment by Yenthe666** [comment] 2017-08-24 10:06
Hmm I was happy for a minute it got confirmed there. No matter what the usability expert says, it would be a great addition to be able to set `readonly` on buttons in specific cases.
I see you don't fully agree either. Ohwell, that is what you have superiors for. Thank you for the feedback @ged-odoo!

**Comment by pedrobaeza** [comment] 2017-08-24 10:13
Ouch, it's a pity not to have this. Although Antony says it's useless and not sane to use it, now I don't see any other way of presenting some information in the cool smart-button form without requiring to attach an action to that button, or better, disable that action on certain conditions. We have a legitimate case with our product_bundle module: https://github.com/OCA/product-attribute/pull/180.

Does any of you think in a possible workaround?

**Comment by sle-odoo** [comment] 2017-08-24 11:13
The problem is that @antonylesuisse does not see any usecase where you want to have a non clickable stat button. Maybe yours is legitimate though: using a stat button to present an information which does not lead to any actual action.

**Comment by msteinfeld** [comment] 2017-08-24 11:15
@pedrobaeza i have unproved idea to use t-att-* with standard html button tag disabled maybe that would be a way?

**Comment by Yajo** [comment] 2017-08-24 11:19
AFAIK no `t-*` is available in backend views, which are not handled by Qweb.

**Comment by pedrobaeza** [comment] 2017-08-24 11:23
For clarifying this, the use case is the following:

- We define some products as "bundles". It has a list of contained products.
- Available stock is then computed as the number of bundles we can have with the available stocks of the contained products, and this information is shown on the same stat button as for normal products.
- But we don't want to be clickable, as the resulting action will be invalid, leading you to an empty screen (as there's no quants available for the product).

Alternatives to this:

- Hide the button for bundle products. We lose some valuable information.
- Show the available stock of bundles in a regular field. This will be inconsistent as you have to check different places according the type of the product. It also doesn't follow Odoo's paradigm.
- Change the action for showing the quants of the contained products. It will be also confuse the user about what he/she is seeing.

That's why we took the decision of disabling the action... if it works.

**Comment by Yajo** [comment] 2017-08-24 11:25
> Show the available stock of bundles in a regular field

I guess this would be the only "sane" option now then... 😕

**Comment by nhomar** [comment] 2017-08-24 11:42
It is insane just think you can not give a readonly thing (which exists since the beginning of times in the more basic frameworks) to a button.

The more common use case is:

You have a button and no result to show, instead annoyingly send the user to a blank list (current behavior) or hide the button (then user will not know it exists) put the f#%$&&/g button readonly read only that' it.

Honestly sometimes "Usability things" are "PoV things that I do not want to support because.... YES!". :-)

**Comment by leorochael** [comment] 2017-08-24 13:16
The rationale for not allowing buttons to be disabled is well argued here:

http://www.uxbooth.com/articles/who-killed-the-inactive-button-state/

But we should also consider that, as far as Odoo is concerned, buttons made invisible change the layout drastically, and as argued by others, in the case of buttons that display actual information, removes an important information placeholder.

As a concrete anecdote: I needed to disable a button that could activate an ongoing operation: the button should be disable while the operation was ongoing so the user would not try to enable the operation twice (and yes, I already had a backend check that the operation could not be activated a second time while the first operation was ongoing).

Since I couldn't disable the button, I had to make it invisible, and the operator was distressed when the button disappeared from the interface after being activated.

**Comment by pedrobaeza** [comment] 2017-08-24 16:05
I can agree with the rationale of part of the article, but it also let some cases that are not covered and the use case I expose can be a good example, and it also don't take into account a factor that happens on a transactional system (multi-record) like Odoo: it's very annoying to navigate through records and have notebook pages, smart-buttons, fields that appear and disappear according each record conditions. Sometimes is better to disable them than to hide them. This is of course very opinionated and the navigation should be restricted in favor of search + locate, but I raise these points to highlight that there's no best option here.

That's is then why is important to  have the option of disabling buttons, and let the developer decide in some of these cases to apply that design paradigm, although Odoo in all its core doesn't use it.

**Comment by antonylesuisse** [comment] 2017-08-24 23:23
I dont think we have many use cases for those disabled buttons, but I wont block the feature if it's implemented cleanly. My point was:
- there is a workaround  you can generate the same html as a stat button with a simple char field. 
- there are more important improvements in the pipe in terms of usability i.e. attrs for invisible in o2m list view based on a domain instead of context  (badly needed for Quote->SO and pickings).
So i asked not to waste time on that feature until the v11 release.

**Comment by Yajo** [comment] 2017-08-25 07:36
> there is a workaround you can generate the same html as a stat button with a simple char field.

How?

**Comment by ged-odoo** [comment] 2017-08-25 07:52
@Yajo he means writing a div or something with a char (or other) field inside, and style it to look like a real stat button (by using as much as possible the same html structure)

However, this is not really a workaround.  It allows you to display readonly information, but it does not allow you to have a button which is active or not, depending on the current record (like a modifier would)

**Comment by Yajo** [comment] 2017-08-25 07:56
Indeed

**Comment by Yenthe666** [comment] 2017-08-25 07:58
That is rather a 'hackish' way than a solution though. @sle-odoo perhaps we can atleast reopen the issue and label it wishlist? By the amount of responses it is clear that multiple people could use it or want it.
