### ISSUE TITLE
Package Level and  orphaned packages

### ISSUE THREAD

**Issue by stesifrancesco** [odoo/odoo#44338] opened 2020-01-30 15:58 UTC
Impacted versions: >= 12 (for what I've tested)

Steps to reproduce:
Install Inventory and enable "delivery packages"
Create a new Receipts with some stock_move
Mark as to do
Confirm some quantity_done via stock_move_line
Then click "PUT IN PACK"
DO NOT VALIDATE
Open again stock_move_line and change the new created package with a new one
SAVE ALL
Now go in inventory --> Master Data --> Packages and try to delete the first and now orphaned packages
Current behavior:
I got this error:
The operation cannot be completed:

> - Create/update: a mandatory field is not set.
> - Delete: another model requires the record being deleted. If possible, archive it instead.
> 
> Model: Stock Package Level (stock.package_level), Field: Package (package_id)

Expected behavior:

The package was never used in the system.... so I have to be hable to delete it.
As a matter of the fact I canno undestand  "package_level model" utility
Aniway.... if I create a package via stock_move_line..... and then change this package I'm able to delete it.... I expect the same bheavior for packages created via put in pack

Thanks in advance 

Francesco

**Comment by ibrahim08** [comment] 2020-02-15 15:31
Hi
I couldn't reproduce the problem, If not resolved yet kindly update your Source code.
kindly check my Video if there is somethings I'm not doing right.
https://drive.google.com/open?id=1G1AqD16AaHRTk7Y8_qh_NfXZznD5IqOq

**Comment by ticodoo** [comment] 2021-02-18 07:41
Fixed in all versions with https://github.com/odoo/odoo/pull/63544

**Closed by ticodoo** 2021-02-18 07:41 UTC
Labels: 12.0, 13.0, Logistics
