### ISSUE TITLE
Image code base64 does not shown in wizard and email server

### ISSUE THREAD

**Issue by ysantiago** [odoo/odoo#12303] opened 2016-06-06 16:05 UTC
Impacted versions: 8.0 b9a006c1c02a06cf3cd34828860125e6d6aa3fb4

Steps to reproduce: 
- Press button 'Send by mail'
- Edit the template and add code line with an image 
`<img src="data:image/png;base64,/*Base64CodeImage*/">`
- Save the template
- Send mail

Note: In preview of the template if it works but in the wizard not.

Current behavior:
- When press button Send the image in wizard disappears and the message is sent without the image.

Expected behavior:
- The image must to stay in the wizard and must appear in the message body

Video/Screenshot link (optional): https://youtu.be/32vqfsrSQ5w

https://www.odoo.com/web/#id=680023&view_type=form&model=project.issue&action=963&active_id=49&menu_id=4720

**Comment by Yenthe666** [comment] 2016-06-07 06:19
@Gorash could you have a look at this one please?

**Comment by dreispt** [comment] 2016-06-08 09:50
Is this a duplicate of #12050 ?

**Comment by moylop260** [comment] 2016-06-08 15:10
@dreispt 
Yes this one is duplicated
Thank you!

**Closed** 2016-06-13 11:33 UTC
Labels: OE
