### ISSUE TITLE
Odoo 10.0 Error 500 on website_portal_sale

### ISSUE THREAD

**Issue by gorozcoh** [odoo/odoo#19822] opened 2017-10-01 10:17 UTC
It seems like a fancy use case but it just happened to one of my clients.
**Impacted versions**: 10.0
**Steps to reproduce:**
1. Create customer invoice for partner A, comercial partner CPA
2. Process invoice. 
3. Cancel invoice, return to draft
4. Change invoice partner to partner B, comercial partner CPB
5. Process invoice.
6. Enable portal access for partner A
7. Partner A logged in portal clic in your invoices and payments
8. Error 500; internal server error

**Current behavior:** Error 500
**Expected behavior:** Show invoices and payments for comercial partner CPA
**Suggested solution:** in website_portal_sale/controllers/main/portal_my_invoices:
```
domain = [
            ('type', 'in', ['out_invoice', 'out_refund']),
            ('message_partner_ids', 'child_of', [partner.commercial_partner_id.id]),
            ('partner_id', 'child_of', [partner.commercial_partner_id.id]),
            ('state', 'in', ['open', 'paid', 'cancel'])
        ]
```
**Error traceback:**
```
2017-10-01 03:33:03,773 4844 ERROR mecanica-alpo odoo.addons.website.models.ir_http: 500 Internal Server Error:

Traceback (most recent call last):
  File "/home/odoo/odoo-dev/odoo/addons/website/models/ir_http.py", line 273, in _handle_exception
    response = super(Http, cls)._handle_exception(exception)
  File "/home/odoo/odoo-dev/odoo/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)
  File "/home/odoo/odoo-dev/odoo/odoo/http.py", line 768, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo-dev/odoo/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()
  File "/home/odoo/odoo-dev/odoo/odoo/http.py", line 827, in dispatch
    r = self._call_function(**self.params)
  File "/home/odoo/odoo-dev/odoo/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/odoo-dev/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/odoo-dev/odoo/odoo/http.py", line 329, in checked_call
    result.flatten()
  File "/home/odoo/odoo-dev/odoo/odoo/http.py", line 1259, in flatten
    self.response.append(self.render())
  File "/home/odoo/odoo-dev/odoo/odoo/http.py", line 1252, in render
    return env["ir.ui.view"].render_template(self.template, self.qcontext)
  File "/home/odoo/odoo-dev/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1039, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/home/odoo/odoo-dev/odoo/addons/website/models/ir_ui_view.py", line 110, in render
    return super(View, self).render(values, engine=engine)
  File "/home/odoo/odoo-dev/odoo/addons/web_editor/models/ir_ui_view.py", line 26, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/home/odoo/odoo-dev/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1059, in render
    return self.env[engine].render(self.id, qcontext)
  File "/home/odoo/odoo-dev/odoo/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 53, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/home/odoo/odoo-dev/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 248, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/home/odoo/odoo-dev/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 322, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0]), name)
QWebException: (u'No se ha podido completar la operaci\xf3n por restricciones de seguridad. Contacte por favor con su administrador de sistema.\n\n(Tipo de documento: res.partner, Operaci\xf3n: read)', None)
Traceback (most recent call last):
  File "/home/odoo/odoo-dev/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 315, in _compiled_fn
    return compiled(self, append, values, options, log)
  File "<template>", line 1, in template_1272_716
  File "<template>", line 3, in body_call_content_715
  File "<template>", line 20, in foreach_712
  File "/home/odoo/odoo-dev/odoo/odoo/fields.py", line 870, in __get__
    self.determine_value(record)
  File "/home/odoo/odoo-dev/odoo/odoo/fields.py", line 972, in determine_value
    record._prefetch_field(self)
  File "/home/odoo/odoo-dev/odoo/odoo/models.py", line 3069, in _prefetch_field
    result = self.read([f.name for f in fs], load='_classic_write')
  File "/home/odoo/odoo-dev/odoo/odoo/models.py", line 3021, in read
    values[name] = field.convert_to_read(record[name], record, use_name_get)
  File "/home/odoo/odoo-dev/odoo/odoo/models.py", line 5210, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/odoo/odoo-dev/odoo/odoo/fields.py", line 866, in __get__
    value = record._cache[self]
  File "/home/odoo/odoo-dev/odoo/odoo/models.py", line 5562, in __getitem__
    return value.get() if isinstance(value, SpecialValue) else value
  File "/home/odoo/odoo-dev/odoo/odoo/fields.py", line 48, in get
    raise self.exception
AccessError: (u'No se ha podido completar la operaci\xf3n por restricciones de seguridad. Contacte por favor con su administrador de sistema.\n\n(Tipo de documento: res.partner, Operaci\xf3n: read)', None)

Error to render compiling AST
AccessError: (u'No se ha podido completar la operaci\xf3n por restricciones de seguridad. Contacte por favor con su administrador de sistema.\n\n(Tipo de documento: res.partner, Operaci\xf3n: read)', None)
Template: 1272
Path: /templates/t/t/t[2]/table/t/tr/td[5]/a
Node: <a t-if="invoice.state == 'open'" t-attf-href="/website_payment/pay?reference=#{invoice.number}&amp;amount=#{invoice.residual}&amp;currency_id=#{invoice.currency_id.id}&amp;country_id=#{invoice.partner_id.country_id.id}" alt="Pagar ahora" class="btn btn-xs btn-primary"><i class="fa fa-arrow-circle-right"/> Pagar Ahora</a>


```

**Comment by csnauwaert** [comment] 2018-02-28 14:21
Hello,

I've managed to reproduce the problem in v10 and in v11. While it does not crash in v11, the invoice is still visible for both user A and B which should not be the case.

**Comment by csnauwaert** [comment] 2018-02-28 14:43
It would seems that I spoke a little too fast, after further investigation and internal discussion. The problem happens because both user (A and B) are followers of the invoice. If you remove A from the followers, the problem does not occurs.
We won't change the fact that invoices are visible on the portal based on the fact that an user must be follower of an invoice. And this use case you are describing is a bit peculiar in the sense that cancelling a validated invoice is not legal and in your case if you've made an error on the customer (which is not an error we do everyday), we assume that it is on the user that cancel the invoice and change the partner on that invoice to also remove the partner from the followers.

Since we won't fix it, I'm closing this issue.
Best regards

**Closed by csnauwaert** 2018-02-28 14:43 UTC
Labels: 10.0, Accounting, Confirmed
