### ISSUE TITLE
Work Order with lots does not reference reserve 

### ISSUE THREAD

**Issue by Moto017** [odoo/odoo#22575] opened 2018-01-28 11:09 UTC
Impacted versions: 
11.0CE

Steps to reproduce:
Enable work order and lots
Inventory with multiple lots under same product.
Create MO and WO
Lot # will be blank
Manually select Lot #s 
Only allows 1 selection of the Lot.  If Lot # inventory is less than BOM amount, will create negative inventory of lot

**Comment by Moto017** [comment] 2018-01-28 21:36
Rephrased in #22578 as applies to overall problem with consumed product lots in MRP

**Comment by Yenthe666** [comment] 2018-01-29 10:48
Closing as it is a duplicate of https://github.com/odoo/odoo/issues/22578

**Closed by Yenthe666** 2018-01-29 10:48 UTC
Labels: 11.0, Logistics
