### ISSUE TITLE
Can't save General Settings

### ISSUE THREAD

**Issue by shiftctrl-io** [odoo/odoo#29630] opened 2018-12-18 22:39 UTC
Impacted versions: 12 Community

Steps to reproduce: Click general settings tab - make changes and try to save. 

Current behavior: When trying to save settings in General Settings and error pops up and prevents me from saving anything

Expected behavior: Should be able to save

This problem started happening after I install a few different addons. Unfortunately I'm not sure now which ones because I was testing something and thought I had a snapshot of my VM to fall back on though I forgot to create the snapshot and didn't note the addons at the time either - however, I believe it might have something to do with the account_payment module... if I remember correctly, I say that in another error which I'm not able to reproduce now. 

I also notice that all my previously saved settings have disappeared (EX: Website name, Pads server, etc..)

Error:
Odoo Server Error
```
Traceback (most recent call last):
  File "/opt/snapper/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/snapper/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/snapper/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/snapper/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/opt/snapper/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/snapper/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/snapper/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/snapper/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/opt/snapper/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/opt/snapper/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/snapper/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/snapper/odoo/api.py", line 747, in call_kw
    return _call_kw_model_create(method, model, args, kwargs)
  File "/opt/snapper/odoo/api.py", line 727, in _call_kw_model_create
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-282>", line 2, in create
  File "/opt/snapper/odoo/api.py", line 430, in _model_create_single
    return create(self, arg)
  File "/opt/snapper/addons/account/models/res_config_settings.py", line 161, in create
    return super(ResConfigSettings, self).create(values)
  File "<decorator-gen-3>", line 2, in create
  File "/opt/snapper/odoo/api.py", line 451, in _model_create_multi
    return create(self, [arg])
  File "/opt/snapper/odoo/models.py", line 3542, in create
    fields[0].determine_inverse(batch_recs)
  File "/opt/snapper/odoo/fields.py", line 1106, in determine_inverse
    self.inverse(records)
  File "/opt/snapper/odoo/fields.py", line 617, in _inverse_related
    other[field.name] = record_value[record]
  File "/opt/snapper/odoo/models.py", line 5058, in __setitem__
    return self._fields[key].__set__(self, value)
  File "/opt/snapper/odoo/fields.py", line 1013, in __set__
    record.write({self.name: write_value})
  File "/opt/snapper/addons/website/models/website.py", line 146, in write
    values['user_id'] = company._get_public_user().id
  File "/opt/snapper/addons/website/models/res_company.py", line 22, in _get_public_user
    self.ensure_one()
  File "/opt/snapper/odoo/models.py", line 4653, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: res.company()
```

**Comment by pedrobaeza** [comment] 2018-12-19 10:23
Hi, thanks for reporting. This seems because the website doesn't have a related company. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by pedrobaeza** [comment] 2018-12-29 12:56
Closing until further notice.

**Closed by pedrobaeza** 2018-12-29 12:56 UTC
Labels: 12.0, Need information
