### ISSUE TITLE
[9.0] Purchase error while creating PO from procurement

### ISSUE THREAD

**Issue by paulius-sladkevicius** [odoo/odoo#10707] opened 2016-02-01 08:30 UTC
Got error when PO is made from procurement

Impacted versions:
- 9.0

Traceback

```
AttributeError: 'list' object has no attribute 'filtered'
  File "openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "addons/purchase/purchase.py", line 709, in _run
    return procurement.make_po()
  File "openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "addons/purchase/purchase.py", line 898, in make_po
    vals = procurement._prepare_purchase_order_line(po, supplier)
  File "openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "addons/purchase/purchase.py", line 775, in _prepare_purchase_order_line
    taxes_id = taxes_id.filtered(lambda x: x.company_id.id in companies).ids
```

Issue introduced with this commit https://github.com/odoo/odoo/commit/2ce9311cfe48f1664dd36a33d3d64b5e47b3ab1a#diff-fe8587929089e5fdb6c75687011b1c7eR759

**Comment by ppa-odoo** [comment] 2016-02-01 08:39
Duplicate of  https://github.com/odoo/odoo/issues/10686

**Comment by Yenthe666** [comment] 2018-01-16 13:35
Hi @paulius-sladkevicius,

Thanks a lot for the bug report.
I've just tried this on the latest Odoo V9 and this issue has been fixed in the meanwhile. As you can see the code also changed:
https://github.com/odoo/odoo/blob/11c73cd0aa2ff9cbfde8e5eebf3f22dfa1c805f1/addons/purchase/purchase.py#L858-L860
Please update your Odoo source code in order to fix this issue.

Regards,
Yenthe

**Closed by Yenthe666** 2018-01-16 13:35 UTC

**Comment by paulius-sladkevicius** [comment] 2018-01-16 14:07
Hi @Yenthe666, thanks to pointing out this!

**Comment by Yenthe666** [comment] 2018-01-16 14:10
You're welcome!
