### ISSUE TITLE
Description for Quotations is not editable from Shop frontend

### ISSUE THREAD

**Issue by nafex** [odoo/odoo#17445] opened 2017-06-06 14:19 UTC
Impacted versions:
Tested on latest 10. and master on runbot

Steps to reproduce:
- login as admin
- go to website -> shop
- go into an item e.g. iPod
- click on edit, top right
- edit the description for Quotations: On iPod the description is:
Height: 76.5 mm
Width: 39.6 mm
Depth: 5.4 mm **[[add some text here and press enter]]**
Weight: 31 grams

Current behavior:
the field is cleared, the text is deleted

Expected behavior:
text should be changeable

https://drive.google.com/file/d/0B2CIGeDDt1gKbVA4M0V3ay1BUXc/view

**Comment by mart-e** [comment] 2017-06-07 13:10
Hello,

Thank you but did you made some pre-configurations (like change of language) ? 
I just tired on latest 10.0 and did not get the issue. What am I missing?

https://drive.google.com/file/d/0B0RwS91KXoeCR1ljMDdRVUNnbE0/view?usp=sharing

**Comment by nafex** [comment] 2017-06-07 14:03
https://drive.google.com/file/d/0B2CIGeDDt1gKbVA4M0V3ay1BUXc/view

**Comment by mart-e** [comment] 2017-06-07 14:48
Thanks for the info. I confirm the bug ! As sson as you press the Enter key, you get empty content.

_issue content updated to remove noise from previous mail exchange, easier to understand with a video ;-) _

**Comment by nle-odoo** [comment] 2017-07-20 13:07
Hi @nafex,

I have been working on a fix for this in https://github.com/odoo/odoo/pull/18319 since this is a rather delicate things to modify, would it be possible for you to test the change?

Most use case I tried with return seem to be working fine for me.

**Comment by nafex** [comment] 2017-07-20 15:06
Hi @nle-odoo 

hitting enter works now but the input still buggy. When you select all with ctrl-a and paste something or select all and write something it deletes everything and you cannot edit the input anymore...

**Comment by nle-odoo** [comment] 2017-08-04 09:01
Hi @nafex 

I have changed the PR, after a lot of errors and other test, it seem better that way.

There is a lot of use case and making a change could add issue to other use case and:

- enter can still be entered by pressing shift + enter
- this part is also editable in the backend

**Comment by nafex** [comment] 2017-08-04 09:36
Hi @nle-odoo 

I'm still having the copy paste issue. When you select all with ctrl-a and paste something or select all and write something it deletes everything and you cannot edit the input anymore...

Copy and paste is a very important feature. I think no one writes all descriptions by hand... The most descriptions are copied and pasted from other documents e.g. from a manufacturer documentation.

**Comment by nle-odoo** [comment] 2017-08-04 13:05
I modified the fix again for this use case.

I was trying to reproduce it but in my tests it did not happen since I had:

```html
<p>
  description line 1<br/>
  description line 2<br/>
</p>
```

and in this instance (having a <br/> at the end) the issue did not happen.

**Comment by nafex** [comment] 2017-08-04 13:34
Tried again on your latest runbot build:
http://251544-9-0-web-editor-opw-751360-nle-e87a56.runbot5.odoo.com

The issue still there:
CTRL + A  ->  ENTER or CTRL + V don't work. 

Here a video:
https://drive.google.com/file/d/0B2CIGeDDt1gKdmQyNmEtTDRiemM/view

I am on holiday for a week now. Will not be able to test in this time.

**Comment by nle-odoo** [comment] 2017-08-07 06:53
ok, [http://251544-9-0-web-editor-opw-751360-nle-e87a56.runbot5.odoo.com](build 251544) was the previous change: https://github.com/odoo-dev/odoo/commit/e87a56267e2, so it's normal the ctrl + V still not work in some instances.

In the last build (with https://github.com/odoo-dev/odoo/commit/773829005) I have tried what's done in the video and for me it works.

**Comment by nafex** [comment] 2017-08-15 14:42
Hi @nle-odoo

I'm back. Could you please rebuild the branch on runbot for me to test? Thank you.

**Comment by nle-odoo** [comment] 2017-08-16 06:48
Hi,


I have updated the branch so it will be available [here](http://runbot.odoo.com/runbot/repo/git-github-com-odoo-dev-odoo-2?search=9.0-web-editor-opw-751360-nle).

**Comment by nafex** [comment] 2017-08-16 07:56
Thank you. The edition works fine now, but when you paste some content with CTRL + V you cannot save the field. Clicking on save will color the field red and show a hint saying "None"

**Comment by nle-odoo** [comment] 2017-08-16 14:51
I should check it further, but as of 10.0 in fact I have neither issue with CTRL + A then CTRL + V with or without the fix.

I think at one point, the "CTRL + V" functionality was rewritten (I guess between 9.0 and 10.0) and so I guess either the new way it is done doesn't have this issue, or I was not able to reproduce it.

**Comment by nafex** [comment] 2017-08-17 08:46
Yes on v10 CTRL + A -> CTRL + V is working fine now :-)
But CTRL + A -> BACKSPACE or DELETE removes the entire field. So you cannot edit it anymore...

https://drive.google.com/file/d/0B2CIGeDDt1gKM2NJNGpERDJlcnM/view

**Closed** 2017-09-07 13:18 UTC
Labels: confirmed, Framework
