### ISSUE TITLE
[12.0] Different exchange rates on different dates create inconsistencies in payment and invoice values

### ISSUE THREAD

**Issue by reinaldoramosarxi** [odoo/odoo#48502] opened 2020-03-27 12:44 UTC
Hello,

A client has noticed the following regarding multi currencies and exchange rates:

- On a Portuguese company, they create an invoice in USD and at that date the exchange rate is X;
- Then at a different date, they create a receipt but the exchange rate is now Y;
- If the new rate converts the receipt value into a value that is higher than the invoice value, this means they will be inconsistent (and Portuguese tributary rules state that a receipt value cannot be higher than the invoice value).

What they are doing right now in order to not go against the Portuguese certification rules is changing the current exchange rate to the one from the day of the invoice, issuing the receipt, creating the account moves and then changing the rate back.

We would like to know if the receipt amount adapting to the rate on the date of the invoice is something that should work by default or if it's too specific to the Portuguese rules, but we believe more countries follow that same rule.

Thank you.

**Comment by Yenthe666** [comment] 2020-03-27 13:00
If that is really the case it should be fixed probably. It should apply the currency rate of the day it was issued.
Could you add reproducable steps for testing on a runbot?

**Comment by reinaldoramosarxi** [comment] 2020-03-27 15:10
Hello,

- Have multicurrency on, activate USD and EUR and set your main company's currency be in EUR;
- Set a currency exchange rate between the two currencies;
- Create and validate an invoice in USD;
- Change the currency exchange rate to a different value;
- Set the invoice as paid;
- Check the exchange difference gain or loss accounting journal.

Thank you.

**Comment by gdgellatly** [comment] 2020-03-28 07:00
In the IFRS world, the current behaviour is correct. see p29 IAS 21.

**Comment by gdgellatly** [comment] 2020-03-28 07:10
I was interested so found the equivelant portugese standard NCRF 23 - it seems it is basically identical to IAS 21, so maybe you should check with a public accountant that you are interpreting the rule correctly. Receiving 800 USD for an 800 USD invoice seems to be valid.

**Comment by gdgellatly** [comment] 2020-03-28 08:13
Actually, I think I know your issue, and it is a global one with foreign currency invoices in jurisdictions with VAT. Although generally it never crops up unless it occurs within 1 tax jurisdiction, because such exports are normally zero rated for VAT purposes. Also VAT is outside the scope of IFRS for most practical purposes as finances are typically ex-tax. 

The one I am most familiar with is Euro denominated invoices for GBP functional currency. Basically the foreign currency value of VAT is purely representative, the amount of VAT is the amount in the functional currency. In fact UK HMRC requires the GBP amount of VAT, and amount of supply to be on the invoice (or at least it did 10 years ago). 

So the reality is that when receiving a payment you are meant to allocate that exact amount of tax. But in practice it makes no difference how you do the entries, because the receipt of money itself has no tax effect. 
In the UK there is even a special exception for cash basis accounting, that for Forex denominated invoices the time of supply is deemed as time of invoice, and not time of receipt.

If there is a difference in the exchange rate for the tax component you either gain it or lose it effectively ex tax, as the tax amount never changes. I imagine all over the EU uses similar rules given they have largely the same frameworks.

But yes Odoo does not handle well. To be honest I think it could be handled by instead of creating 2 journal entries, they are combined in a single entry.

So instead of
DR Bank 1000
CR Debtors 1000

Then 
DR Debtors 200
CR Forex Diff 200

Just one entry of 
DR Bank 1000
CR Debtors 800
CR Forex Diff 200

Would get by, and your receipt is only for the amount.

I decided to check my 10 year old knowledge - it is still the same now.
https://www.gov.uk/guidance/foreign-currency-transactions-vat-and-tour-operators for accrual

**Comment by C3POdoo** [comment] 2023-03-30 11:41
Dear @reinaldoramosarxi,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._

**Closed by C3POdoo** 2023-03-30 11:41 UTC
Labels: 12.0, Sales
