### ISSUE TITLE
CSV Import with default option 'Track history during import' fails

### ISSUE THREAD

**Issue by PCatinean** [odoo/odoo#289] opened 2014-06-02 12:56 UTC
For most large imports (Products / Product Templates) trying to import with this option fails

lastest git revision: 872842ff9e4e0861c365a3edf4d3b9d776553f85

Headers for a csv file: 
id	name	purchase_ok	rental	sale_ok	categ_id/id	standard_price	description	dimension_type_ids/id	value_ids/id	do_not_generate_new_variant	do_not_update_variant	flagpole	weight	is_multi_variants	weight_net	prefix	procure_method	type	description_purchase	uom_po_id/id	description_sale	list_price	supply_method	template_category_id/id	category_id/id	uom_id/id

Traceback:
2014-06-02 12:49:58,683 13922 ERROR DB openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/server/openerp/http.py", line 464, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/server/openerp/http.py", line 483, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/server/openerp/http.py", line 299, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/server/openerp/http.py", line 296, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/server/openerp/http.py", line 664, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/server/openerp/http.py", line 348, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/server/addons/web/controllers/main.py", line 1046, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/server/addons/web/controllers/main.py", line 1038, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/server/addons/base_import/models.py", line 323, in do
    cr, uid, import_fields, data, context=context)
  File "/opt/odoo/server/openerp/osv/orm.py", line 1392, in load
    noupdate=noupdate, res_id=id, context=context))
  File "/opt/odoo/server/openerp/addons/base/ir/ir_model.py", line 1014, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/opt/odoo/server/addons/product/product.py", line 673, in create
    self.create_variant_ids(cr, uid, [product_template_id], context=context)
  File "/opt/odoo/server/addons/product/product.py", line 656, in create_variant_ids
    id = product_obj.create(cr, uid, values, context=ctx)
  File "/opt/odoo/server/addons/product/product.py", line 1060, in create
    return super(product_product, self).create(cr, uid, vals, context=ctx)
  File "/opt/odoo/server/addons/mail/mail_thread.py", line 377, in create
    self.message_post(cr, uid, thread_id, body=_('%s created') % (self._description), context=context)
  File "/opt/odoo/server/addons/mail/mail_thread.py", line 1586, in message_post
    msg_id = mail_message.create(cr, uid, values, context=context)
  File "/opt/odoo/server/addons/mail/mail_message.py", line 822, in create
    values['reply_to'] = self._get_reply_to(cr, uid, values, context=context)
  File "/opt/odoo/server/addons/mail/mail_message.py", line 797, in _get_reply_to
    sanitized_doc_name = re.sub(r'[^\w+.]+', '-', document_name[1])
  File "/usr/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer

**Comment by Yenthe666** [comment] 2016-06-13 06:35
Hi @PCatinean,

I recently imported over 1.000 records in one go for a customer without any problems.
I'm closing this since I cannot reproduce this issue anymore. If you still face this issue please post a message here and I'll reopen it. Be sure to add an example CSV file then.

Regards,
Yenthe

**Closed by Yenthe666** 2016-06-13 06:35 UTC
