### ISSUE TITLE
pop up error message when install/uninstall modules

### ISSUE THREAD

**Issue by wingsoul** [odoo/odoo#19486] opened 2017-09-15 10:24 UTC
Impacted versions:
v 10.0ee

Steps to reproduce:
install/uninstall any modules

Current behavior:
pop up error message as following:

`Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/odoo/addons/base/module/wizard/base_module_upgrade.py", line 76, in upgrade_module
    odoo.modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/odoo/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/home/odoo/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/odoo/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/odoo/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/odoo/odoo/tools/convert.py", line 845, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/odoo/odoo/tools/convert.py", line 915, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/odoo/odoo/tools/convert.py", line 796, in parse
    self.parse(rec, mode)
  File "/home/odoo/odoo/tools/convert.py", line 799, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/odoo/odoo/tools/convert.py", line 707, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/home/odoo/odoo/addons/base/ir/ir_model.py", line 1228, in _update
    record = record.create(values)
  File "/home/odoo/addons/crm/models/crm_team.py", line 40, in create
    return super(Team, self).create(vals)
  File "/home/odoo/addons/mail/models/mail_alias.py", line 223, in create
    )).create(vals)
  File "/home/odoo/addons/sales_team/models/crm_team.py", line 45, in create
    return super(CrmTeam, self.with_context(mail_create_nosubscribe=True)).create(values)
  File "/home/odoo/addons/mail/models/mail_thread.py", line 228, in create
    thread = super(MailThread, self).create(values)
  File "/home/odoo/odoo/models.py", line 3830, in create
    record = self.browse(self._create(old_vals))
  File "/home/odoo/odoo/models.py", line 3925, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/home/odoo/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ParseError: "null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (30, 2017-09-15 09:10:28.625887, null, 1, 1, null, null, 4, 2017-09-15 09:10:28.625887, t, null, null, 37, t, f, null, t, null, f).
" while parsing /home/odoo/addons/website_crm/data/website_crm_data.xml:33, near
<record model="crm.team" id="sales_team.salesteam_website_sales">
            <field name="use_leads">True</field>
            <field name="use_opportunities" eval="False"/>
        </record>`

Expected behavior:
Module should be install/uninstall without any pop up error message

seems related with #19158 

hope someone can help
Thank you~

**Comment by Yenthe666** [comment] 2017-09-15 13:14
Hi @wingsoul,

Thank you for your report.
Can you reproduce this on an official Odoo instance (at runbot.odoo.com)? I've just tried this on the latest 10.0 enterprise without any problems. Can you provide more information?
If you still face this but can't reproduce it on a runbot then please update your local Odoo instance.

Regards,
Yenthe

**Comment by Yenthe666** [comment] 2018-02-12 11:08
Hi there,

I'm closing this bug report as there has been no feedback in a few months.

Regards,
Yenthe

**Closed by Yenthe666** 2018-02-12 11:08 UTC
Labels: Need information
