### ISSUE TITLE
I don't arrive to uninstall a modul from odoo 14

### ISSUE THREAD

**Issue by tinmar565** [odoo/odoo#61234] opened 2020-11-03 09:43 UTC
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo/odoo/http.py", line 682, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/odoo/http.py", line 358, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/http.py", line 346, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 911, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 530, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 1359, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 1351, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/models.py", line 6178, in onchange
    snapshot1 = Snapshot(record, nametree)
  File "/opt/odoo/odoo/odoo/models.py", line 5984, in __init__
    self.fetch(name)
  File "/opt/odoo/odoo/odoo/models.py", line 5992, in fetch
    self[name] = [Snapshot(line, tree[name]) for line in record[name]]
  File "/opt/odoo/odoo/odoo/models.py", line 5992, in <listcomp>
    self[name] = [Snapshot(line, tree[name]) for line in record[name]]
  File "/opt/odoo/odoo/odoo/models.py", line 5984, in __init__
    self.fetch(name)
  File "/opt/odoo/odoo/odoo/models.py", line 5994, in fetch
    self[name] = record[name]
  File "/opt/odoo/odoo/odoo/models.py", line 5625, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo/odoo/odoo/fields.py", line 972, in __get__
    self.compute_value(recs)
  File "/opt/odoo/odoo/odoo/fields.py", line 1111, in compute_value
    records._compute_field_value(self)
  File "/opt/odoo/odoo/odoo/models.py", line 4020, in _compute_field_value
    getattr(self, field.compute)()
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_model.py", line 202, in _compute_count
    records = self.env[model.model]
  File "/opt/odoo/odoo/odoo/api.py", line 473, in __getitem__
    return self.registry[model_name]._browse(self, (), ())
  File "/opt/odoo/odoo/odoo/modules/registry.py", line 177, in __getitem__
    return self.models[model_name]
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 314, in _handle_exception
    raise exception.with_traceback(None) from new_cause
KeyError: 'crm.claim'

**Comment by pedrobaeza** [comment] 2020-11-03 09:52
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code, as `crm.claim` is not something of Odoo itself since a lot of versions. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2020-11-03 09:52 UTC

**Comment by ivantodorovich** [comment] 2020-11-05 15:06
Hi,

I've been encountering this error from time to time as well. 

AFAIK, It happens when you try to uninstall a custom module that has defined custom models record data, and that is no longer available in your addons path.

I can reproduce this at least in `>= 12.0`. 
Although, due to the nature of this issue, it's not reproduceable in runbot, because there aren't any custom modules there.

As a workaround, you can go to **Settings > Technical > External identifiers** and delete that module's `ir.model.data` records that are defined for that custom model. Once removed, you can uninstall the module.

It is very annoying, and IMO this *is* a framework bug, as odoo should be able to uninstall a module, even if it's no longer available in the addons path.

I can't say for sure, but I'm pretty sure this didn't happen in previous versions.

**Comment by tinmar565** [comment] 2020-11-05 15:22
Thank you very much
I have resolv this problem.

Le jeu. 5 nov. 2020 à 16:07, Iván Todorovich <notifications@github.com> a
écrit :

**Comment by pedrobaeza** [comment] 2020-11-05 15:23
Please provide then a module that allow to reproduce such problem to see if it can be handled at framework level.

**Comment by ivantodorovich** [comment] 2020-11-07 19:49
**Steps to reproduce:**

1. Install a custom module that defines a new model, and data records of that custom model ([sample module here](https://github.com/ivantodorovich/odoo-uninstall-unavailable-module/tree/14.0/odoo_test_module))
2. Remove that custom module from your addons_path & restart odoo
3. Try to uninistall your custom module

**Result:**

```
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/odoo/http.py", line 682, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 358, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 346, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 911, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 530, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1359, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1351, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/models.py", line 6154, in onchange
    snapshot1 = Snapshot(record, nametree)
  File "/home/odoo/src/odoo/odoo/models.py", line 5974, in __init__
    self.fetch(name)
  File "/home/odoo/src/odoo/odoo/models.py", line 5982, in fetch
    self[name] = [Snapshot(line, tree[name]) for line in record[name]]
  File "/home/odoo/src/odoo/odoo/models.py", line 5982, in <listcomp>
    self[name] = [Snapshot(line, tree[name]) for line in record[name]]
  File "/home/odoo/src/odoo/odoo/models.py", line 5974, in __init__
    self.fetch(name)
  File "/home/odoo/src/odoo/odoo/models.py", line 5984, in fetch
    self[name] = record[name]
  File "/home/odoo/src/odoo/odoo/models.py", line 5615, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/odoo/src/odoo/odoo/fields.py", line 973, in __get__
    self.compute_value(recs)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1112, in compute_value
    records._compute_field_value(self)
  File "/home/odoo/src/odoo/odoo/models.py", line 4020, in _compute_field_value
    getattr(self, field.compute)()
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_model.py", line 203, in _compute_count
    records = self.env[model.model]
  File "/home/odoo/src/odoo/odoo/api.py", line 473, in __getitem__
    return self.registry[model_name]._browse(self, (), ())
  File "/home/odoo/src/odoo/odoo/modules/registry.py", line 177, in __getitem__
    return self.models[model_name]
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 314, in _handle_exception
    raise exception.with_traceback(None) from new_cause
KeyError: 'custom.model'
```

**Expected Result:**
Module should be uninstalled

**Impacted versions:**
I've been able to reproduce it in `12.0` and `14.0`.
I haven't tested the others.

**Workaround**
Delete the `ir.model.data` defined for your custom model manually, then you can uninstall.

**Comment by pedrobaeza** [comment] 2020-11-07 22:10
Iván, that's normal, as you are removing the module from the addons path while not yet uninstalled.

**Comment by ivantodorovich** [comment] 2020-11-07 22:30
Hi @pedrobaeza 

Yes, that is exactly what I said

> It is very annoying, and IMO this is a framework bug, as odoo should be able to uninstall a module, even if it's no longer available in the addons path.

**Comment by pedrobaeza** [comment] 2020-11-07 22:37
Sorry, I didn't read that part, but no, it's not a framework but, as the framework can't handle such misconfiguration.

**Comment by Yenthe666** [comment] 2020-11-09 11:12
That's just misuse :)
