### ISSUE TITLE
POS numpad issue when pressing decimal point multiple times

### ISSUE THREAD

**Issue by elementgreen** [odoo/odoo#32034] opened 2019-03-22 06:53 UTC
Impacted versions:
12.0.20181213

Steps to reproduce:
1. Open up POS interface
2. Add an item
3. Press the decimal point button multiple times (2 or more)
4. Note that pressing additional number keys do not display
5. Backspace must be pressed for the number of digits entered, plus the multiple decimal points, to clear all the hidden characters in the value buffer
6. Same behavior occurs with the Discount and Price values

Current behavior:
Multiple decimal point characters can be "entered" and are inserted into value buffer (Qty, Disc, or Price), but do not display on screen.
Additional digits entered after multiple decimal point presses are inserted into buffer, but do not display on screen.
Additional digits entered after the last valid digit on the screen are also inserted into the buffer.
Backspace must be used to remove the invisible characters from the value buffer.

Expected behavior:
The value buffer for Qty, Disc, or Price should more closely match what is displayed on the screen.
Characters which are invalid and aren't displayed on the screen, should not be inserted into the value buffer, including the decimal point button.
Ideally, pressing the decimal point button could position the buffer "insertion point" at the current decimal point index. Thus pressing the decimal point, if digits have already been keyed in afterwards, would allow for overwriting the values after the decimal digit, regardless of where the current position is. Also, pressing the decimal point and then the backspace button could position the insertion point before the decimal point and allow for keying in the integer portion of the value without affecting the digits afterwards.
There is no visual indicator when a backspace "removes" a decimal point, allowing for key-in of values before the decimal point. Ideally there would be some way to know on which side of the decimal point the current insertion point is at. For example, highlighting the current digit which will be overwritten.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment] 2019-03-23 10:16
@elementgreen I see that the Odoo you're testing this on hasn't been updated in quite a while (12.0.20181213). Have you also tried it on the latest version?

**Comment by pedrobaeza** [comment] 2019-03-23 11:28
Complementing Yenthe's answer, are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If not reproducible, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by elementgreen** [comment] 2019-03-23 17:45
Behavior is identical to what was described in the ticket with master branch on runbot. Is there a new branch than that? Its pretty easy to test, just log into runbot, open up a POS session, add an item, optionally press a digit or 2 for the quantity, then press the decimal point multiple times, then a bunch more digits (which wont display), but backspace will be required to delete all the invisible characters in the buffer. Can get very confusing if accidentally pressing decimal point multiple times.

**Comment by pedrobaeza** [comment] 2019-03-23 17:57
Master branch is a development branch. You must use a stable one (12.0, 11.0, 10.0...)

**Comment by elementgreen** [comment] 2019-03-23 18:15
OK. Tried it on 12.0, 11.0, and 10.0, all have the same confusing behavior.

**Comment by Yenthe666** [comment] 2019-03-23 20:16
Then @pim-odoo can probably take a look at this.

**Comment by pedrobaeza** [comment] 2019-03-24 14:00
@switch87 are you aware of this problem?

**Comment by switch87** [comment] 2019-03-25 10:16
@pedrobaeza I was not, thanks for tagging me!

**Comment by Yenthe666** [comment] 2019-04-09 06:11
@switch87 I see there's a PR open. Is there anything else needed to get it merged in?

**Comment by switch87** [comment] 2019-04-09 12:37
fixed in  #32089

**Closed** 2019-04-09 12:37 UTC
Labels: 12.0, Need information, Point of Sale
