### ISSUE TITLE
9.0 CE, Bugs with web framework, Calendar issues.

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#10811] opened 2016-02-08 06:44 UTC
Uncaught TypeError: Cannot read property 'arch' of undefined
http://localhost:8069/web/static/src/js/framework/view.js:255
Traceback:
TypeError: Cannot read property 'arch' of undefined
    at OdooClass.Widget.extend.is_action_enabled (http://localhost:8069/web/static/src/js/framework/view.js:255:37)
    at Engine.eval (eval at <anonymous> (http://localhost:8069/web/static/lib/qweb/qweb2.js:404:33), <anonymous>:9:133)
    at Engine.QWeb2.Engine.QWeb2.tools.extend._render (http://localhost:8069/web/static/lib/qweb/qweb2.js:393:58)
    at Engine.QWeb2.Engine.QWeb2.tools.extend.render (http://localhost:8069/web/static/lib/qweb/qweb2.js:385:26)
    at OdooClass.View.extend.render_buttons [as _super] (http://localhost:8069/web/static/src/js/views/list_view.js:281:36)
    at OdooClass.ListView.include.render_buttons (http://localhost:8069/web/static/src/js/views/list_view_editable.js:286:34)
    at OdooClass.<anonymous> (http://localhost:8069/web/static/src/js/framework/class.js:122:38)
    at OdooClass.ListView.include.render_buttons (http://localhost:8069/base_import/static/src/js/import.js:62:21)
    at OdooClass.render_buttons (http://localhost:8069/web/static/src/js/framework/class.js:122:38)
    at OdooClass.Widget.extend.render_view_control_elements (http://localhost:8069/web/static/src/js/view_manager.js:291:29)

**Comment by JKE-be** [comment] 2016-02-08 13:24
need more details... 
Take a look here: https://github.com/odoo/odoo/wiki/Contributing

**Comment by Yenthe666** [comment] 2016-05-23 12:12
Hi @tejastank,

As JKE already said, you should add some more information or we have no way to test if this issue still exists.
I'm closing this one since there is not enough information and the issue is already quite old too.
If you do still face this issue please create a new issue and add more information.

Regards,
Yenthe

**Closed by Yenthe666** 2016-05-23 12:12 UTC
