### ISSUE TITLE
POS price and tax calculation for Quebec province

### ISSUE THREAD

**Issue by Skrypt** [odoo/odoo#1515] opened 2014-08-01 15:12 UTC
The price calculation is not working really well with composite tax.

![image](https://cloud.githubusercontent.com/assets/3228637/3780519/34274f28-198d-11e4-8da2-4ccf6cb9d87e.png)

Here is a page that explains taxes in Quebec and that returns an accurate result.

http://www.calculconversion.com/sales-tax-calculator-gst-qst.html

There is another fact too that is concerning rounding that is explained there : 

http://www.fin.gc.ca/1cent/index-eng.asp

**Comment by lapagept** [comment] 2015-02-15 20:22
I have the problem too!

**Comment by qdp-odoo** [comment] 2015-02-23 14:21
sorry for the delay, i'll try to have a look at that during this week

**Comment by lapagept** [comment] 2015-02-23 14:24
Super!

**Comment by gaultp** [comment] 2015-02-23 14:25
:+1:

**Comment by gbard** [comment] 2015-03-05 03:22
Any update on this issue? I'm in the same situation.

**Comment by eleop** [comment] 2015-03-10 20:20
Any update? same situation since a long time !!!

**Comment by gbard** [comment] 2015-03-10 21:11
Yes, please provide us with a fix for this bug! That's the only thing missing before we can go forward with this ERP! Thanks!

**Comment by martinauger03** [comment] 2015-03-10 21:59
I fixed it for the v7...  I added all the taxes details on the POS screen and on the receipt.  On the screen we don't have the subtotal, just like the original version.  

But it's work only for Quebec Canada because the tax name on the POS screen are hardcoded.  I think a java programmer can fix this issue in some minutes. (I have some difficulties with java).

On the receipt the taxes name are not harcoded. But in QC the taxe number must appear on the receipt, so we harcoded it on the receipt because no specific field exist in OpenERP for that and we didn't create it. A logo was added to the header of the receipt, but this logo must be put directly in the module directory.  Some other message was hardcoded too (see image below).

So, I didn't share it because it still have some hardcoded issues to fix.  I hate doing hardcode, but I hate waiting for a fix years after years too... This is not perfect but it works for us.  If you want this, to see what I changed, or make a diff, I can maybe send it or put it somewhere on the net. I commented my modifications directly in the code.  But if you fix it at all please send me it!!!

![pos screen 2](https://cloud.githubusercontent.com/assets/1906270/6586195/192ec3d0-c74e-11e4-8ea5-126999e94895.png)

Martin

**Comment by gbard** [comment] 2015-03-10 22:59
I want this!

bardbq@gmail.com

G

**Comment by gbard** [comment] 2015-03-17 15:31
Still no updates?

**Comment by gurneyalex** [comment] 2015-03-18 07:52
See also https://github.com/odoo/odoo/pull/1835 which needs rebasing

**Comment by jnbrunet** [comment] 2015-03-21 02:56
See my patch in the comments of the [8.0-pos-child-taxes-fva](https://github.com/odoo/odoo/pull/1835) branch to fix the invoice bug in odoo 8.0

**Comment by jnbrunet** [comment] 2015-03-21 22:24
I've create a pull request based on the odoo-dev pull request. Mine should work correctly with the odoo/8.0 branch and should fix the point of sale with child taxes.

https://github.com/odoo/odoo/pull/5873

**Comment by bwrsandman** [comment] 2015-03-23 14:18
Hi @jnbrunet would you mind also making a pull request with https://github.com/oca/ocb, you might get a quicker review.

**Comment by jnbrunet** [comment] 2015-03-25 22:35
The pull request has been added to [OCA/OCB 183](https://github.com/OCA/OCB/pull/183)

**Comment by bwrsandman** [comment] 2015-03-30 19:48
Thank you!

**Closed** 2015-04-16 07:37 UTC
Labels: confirmed

**Comment by mart-e** [comment] 2015-04-16 07:41
Hello,

We have fixed the computation of subtaxes at 58a481329eb1ec4074a08e12b89fdbd2aaa35343.
Thank you for the report.

**Comment by lapagept** [comment] 2016-01-07 02:10
Hello guys,

I think I have found a new error in the point of sale today.

We are in Quebec, Canada. We have 2 taxes here : TPS (5 %) and TVQ (9,975 %)

We use Odoo 8.0

Let's take an example
###For an invoice with a subtotal of 4,30 $.
TPS (5 %) should be 4,3 * 0,05 = 0,215 = 0,22 $ (rounded)
TVQ (9,975 %) should be 4,3 * 0,09975 = 0,4289... = 0,43 $ (rounded)
Total of taxes = 0,22 + 0,43 = 0,65 $
Final total should be 4,3 + 0,65 = 4,95 $

###But in the Odoo point of sale...
The same invoice with a subtotal of 4,30 $
Taxes are rather 0,64 $ (*&&#?$*&@#$*&?@#*&?$*?)
Final total are 4,3 + 0,64 = 4,94 $

I think the point of sale uses the one shot way to calculate the taxe in Quebec :

4,3 * 0,14975 = 0,6439... = 0,64 $ (rounded)

**Comment by mcassuto** [comment] 2016-01-07 02:15
hello @lapagept ,

les 2 méthodes sont correctes : http://www.revenuquebec.ca/fr/entreprises/taxes/tpstvhtvq/perception/calcultaxes.aspx

**Comment by lapagept** [comment] 2016-01-07 12:00
Thanks for your comment @mcassuto!
You are right. Both methods are corrects in Quebec. 
But because all transactions we do in the point of sale is automatically invoiced, because all taxes in invoices are rounded 2 times (one for the TPS and one for the TVQ), we would want to use the same method in the Odoo point of sale. 
How could we achieve this and use the same taxes rounding method in the pos and the account system?
Thanks

**Comment by mcassuto** [comment] 2016-01-07 12:45
@lapagept : use the Tax calculation rounding method in Settings > Configuration > Accounting

**Comment by lapagept** [comment] 2016-01-07 13:56
@mcassuto : my tax calculation method is well set to "round globally".
This is not the problem. The problem is that the taxes are rounded only one time in pos. Taxes are rounded (correctly) two times in account (tps is rounded and tvq is rounded). For a invoive of 4,30 $, this causes a 0,01 $ difference on the final amount.

**Comment by lapagept** [comment] 2016-01-07 22:57
I have study the code of the file /openerp/addons/point_of_sale/static/src/js/models.js
I note that the point of sale calculates the taxes by line, even if we choose "round_globally" for the tax calculation rounding method in the setting. In this case, the code only change the precision (currency_rounding * 0.00001) for each line.
