### ISSUE TITLE
Error on trying to print invoice with local charset

### ISSUE THREAD

**Issue by boumboum** [odoo/odoo#21029] opened 2017-11-17 10:04 UTC
Impacted versions: Odoo V11 exe (20171117)

Steps to reproduce: create an invoice with (probably) some non English chars in the description/tax, etc. fields

Current behavior: The attached error message

Expected behavior:create the PDF

Video/Screenshot link (optional):
Hiba:
Odoo Server Error

Traceback (most recent call last):
  File "C:\Odoo\python\lib\site-packages\PyPDF2\generic.py", line 484, in readFromStream
    return NameObject(name.decode('utf-8'))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 7: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Odoo\server\odoo\addons\web\controllers\main.py", line 1647, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "C:\Odoo\server\odoo\http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "C:\Odoo\server\odoo\addons\web\controllers\main.py", line 1596, in report_routes
    pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
  File "C:\Odoo\server\odoo\addons\base\ir\ir_actions_report.py", line 641, in render_qweb_pdf
    return self._post_pdf(save_in_attachment, pdf_content=pdf_content, res_ids=html_ids), 'pdf'
  File "C:\Odoo\server\odoo\addons\base\ir\ir_actions_report.py", line 551, in _post_pdf
    writer.write(result_stream)
  File "C:\Odoo\python\lib\site-packages\PyPDF2\pdf.py", line 482, in write
    self._sweepIndirectReferences(externalReferenceMap, self._root)
  File "C:\Odoo\python\lib\site-packages\PyPDF2\pdf.py", line 571, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "C:\Odoo\python\lib\site-packages\PyPDF2\pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "C:\Odoo\python\lib\site-packages\PyPDF2\pdf.py", line 571, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "C:\Odoo\python\lib\site-packages\PyPDF2\pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "C:\Odoo\python\lib\site-packages\PyPDF2\pdf.py", line 556, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, data[i])
  File "C:\Odoo\python\lib\site-packages\PyPDF2\pdf.py", line 571, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "C:\Odoo\python\lib\site-packages\PyPDF2\pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "C:\Odoo\python\lib\site-packages\PyPDF2\pdf.py", line 586, in _sweepIndirectReferences
    newobj = self._sweepIndirectReferences(externMap, newobj)
  File "C:\Odoo\python\lib\site-packages\PyPDF2\pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "C:\Odoo\python\lib\site-packages\PyPDF2\pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "C:\Odoo\python\lib\site-packages\PyPDF2\pdf.py", line 577, in _sweepIndirectReferences
    newobj = data.pdf.getObject(data)
  File "C:\Odoo\python\lib\site-packages\PyPDF2\pdf.py", line 1611, in getObject
    retval = readObject(self.stream, self)
  File "C:\Odoo\python\lib\site-packages\PyPDF2\generic.py", line 66, in readObject
    return DictionaryObject.readFromStream(stream, pdf)
  File "C:\Odoo\python\lib\site-packages\PyPDF2\generic.py", line 579, in readFromStream
    value = readObject(stream, pdf)
  File "C:\Odoo\python\lib\site-packages\PyPDF2\generic.py", line 60, in readObject
    return NameObject.readFromStream(stream, pdf)
  File "C:\Odoo\python\lib\site-packages\PyPDF2\generic.py", line 492, in readFromStream
    raise utils.PdfReadError("Illegal character in Name Object")
PyPDF2.utils.PdfReadError: Illegal character in Name Object

**Comment by rruebner** [comment] 2017-11-30 10:23
@boumboum Tested in runbot and it works fine. Maybe a Windows problem?

**Comment by Yenthe666** [comment] 2017-12-04 09:32
Hi @boumboum,

Thanks for the report.
Just like @rruebner I tried to reproduce it but it works fine at my side. Can you reproduce it on an official runbot (at runbot.odoo.com) or can you show a detailed report on how to reproduce it on a windows please?

Regards,
Yenthe

**Comment by Yenthe666** [comment] 2018-03-19 09:40
Hi there,

Closing as there has been no feedback on this issue.

**Comment by boumboum** [comment] 2018-03-19 12:29
Well you can close it but there is no solution provided. I have used the official (?) all-in-one windows installer from http://nightly.odoo.com/, I do not have such kind of issue with none of the other application (including other python bottle, flask), just with odoo.
The characters to test are: óüöúőűáéíÓÜÖÚŐŰÁÉÍ

**Comment by Yenthe666** [comment] 2018-03-19 12:42
@boumboum then please provide us with a step by step test case (or a video) that shows us the problem.

**Comment by boumboum** [comment] 2018-03-22 16:03
Well I don't know how to give you more info beside I've already given, but I'll try:
1. Select Invoicing/Documents/Customer Invoices
2. Click on Create
3. Select any customer (Agrolait), enter any date (03/05/2018)
4. Add an invoice item (product = óüöúőűáéí, description=óüöúőűáéí, Quantity=1, Unit price = 1.00, Tax=27%)
5. Click on Validate
6. Click on Print Invoice

And I have the already mentioned error: PyPDF2.utils.PdfReadError: Illegal character in Name Object

I have 2 languages installed Hungarian and English. The error is the same with both languages

**Comment by Yenthe666** [comment] 2018-03-22 16:11
Hi @boumboum,

I've just did this and it works fine. Have a look at my example record and see the downloaded file at the bottom of my browser:
![image](https://user-images.githubusercontent.com/6352350/37782761-0440195a-2df4-11e8-84a5-c2548f2dafe9.png)
When I open the PDF:
![image](https://user-images.githubusercontent.com/6352350/37782777-0dd31bc0-2df4-11e8-9402-cd928a604306.png)

So everything seems to be working fine here. But that is on a Linux, so I'd have to double check on a Windows. Will reopen for now.

**Comment by Yenthe666** [comment] 2018-03-22 16:23
Just tested on Windows with the latest 11.0 and it is working perfectly fine there too.
Can you please download the latest version and try again?

**Comment by Yenthe666** [comment] 2018-05-03 05:58
Closing again as there has been no feedback and it really seems to work fine.

**Closed by Yenthe666** 2018-05-03 05:58 UTC
Labels: 11.0, Need information

**Comment by petrcar** [comment] 2019-08-15 05:53
> Well I don't know how to give you more info beside I've already given, but I'll try:
> 
> 1. Select Invoicing/Documents/Customer Invoices
> 2. Click on Create
> 3. Select any customer (Agrolait), enter any date (03/05/2018)
> 4. Add an invoice item (product = óüöúőűáéí, description=óüöúőűáéí, Quantity=1, Unit price = 1.00, Tax=27%)
> 5. Click on Validate
> 6. Click on Print Invoice
> 
> And I have the already mentioned error: PyPDF2.utils.PdfReadError: Illegal character in Name Object
> 
> I have 2 languages installed Hungarian and English. The error is the same with both languages

Hi, did you solve this issue at the end? I have the same, apart of my Widnows is Czech language...

**Comment by marlonbidu** [comment] 2020-06-01 13:26
Hi! I have this issue too, but the problem is only with paid invoices when you print a payment receipt in Odoo version12.
