### ISSUE TITLE
Payments: Wrong Payment Journal field domain

### ISSUE THREAD

**Issue by grzekru** [odoo/odoo#23762] opened 2018-03-20 09:04 UTC
**Impacted versions:**

11.0

**Steps to reproduce:**

1. Install account_invoicing module
2. Invoicing -> Sales -> Documents -> Payments
3. Click Create
4. See positions under Payment Journal select field
![image](https://user-images.githubusercontent.com/5862658/37644881-6bd7f1e4-2c25-11e8-81f0-e71aa8a4e0b4.png)
5. Change payment type to "Send Money" and back to "Receive Money"
6. See positions under Payment Journal
![image](https://user-images.githubusercontent.com/5862658/37644938-9bd2e14c-2c25-11e8-805d-6064b1a1f383.png)

**Current behavior:**

Strange Payment Journal domain behavior

**Expected behavior:**

Domain in Payment Journal working correctly

**Comment by Yenthe666** [comment] 2018-03-20 09:07
@qdp-odoo for you 😉

**Comment by gustavovalverde** [comment] 2018-03-26 12:10
This is a duplicate of #22296. Just so you know @grzekru, this will be fixed in master not in stable, as it was an intended behavior. 

cc: @qdp-odoo saved you the answer ;)

**Comment by Yenthe666** [comment] 2018-03-26 12:15
Oooh indeed @gustavovalverde - thanks a lot!

**Closed by Yenthe666** 2018-03-26 12:15 UTC
Labels: 11.0, Accounting
