### ISSUE TITLE
qweb t-inherit template not being loaded

### ISSUE THREAD

**Issue by t-900-a** [odoo/odoo#61725] opened 2020-11-13 15:18 UTC
Impacted versions: 14

Steps to reproduce:
Add to inherited template: 
<t t-set="helloworld" t-value="helloworld"/>
<t t-log="helloworld"/>

Example code / project: https://github.com/t-900-a/odoo-solana-payments/blob/master/views/solana_payment_confirmation.xml

Current behavior: helloworld is not being logged

Expected behavior: helloworld should be logged

Video/Screenshot link (optional):
https://www.odoo.com/nl_NL/forum/help-1/question/adding-custom-message-to-payment-confirmation-status-view-179083

**Comment by pedrobaeza** [comment] 2020-11-13 15:22
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2020-11-13 15:22 UTC
