### ISSUE TITLE
Duplicating a manufacturing order does carry over the by-product lines from the original order

### ISSUE THREAD

**Issue by brian-inksmith** [odoo/odoo#76338] opened 2021-09-10 12:53 UTC
Impacted versions: 14

Steps to reproduce:  

1.  Create a product with a BoM that includes components and byproducts
2.  Create a manufacturing order for this product
3.  Duplicate the manufacturing order from the action menu.

Current behavior:

The duplicated manufacturing order carries over the component lines, but not the by-product lines.

Expected behavior:

The by-product lines should be carried over, 

Video/Screenshot link (optional):

(MO578 is a duplicate of MO577)

![image](https://user-images.githubusercontent.com/75486961/132856161-217b4f31-b709-4045-a6df-4f68e2dd5388.png)
![image](https://user-images.githubusercontent.com/75486961/132856179-5f052bb7-bf77-436b-8feb-cacb0e45608f.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by sswapnesh** [comment] 2021-09-11 18:01
Duplicate of https://github.com/odoo/odoo/issues/70369

**Comment by pedrobaeza** [comment] 2021-09-11 22:07
Closing then

**Closed by pedrobaeza** 2021-09-11 22:07 UTC
Labels: Logistics, 14.0
