### ISSUE TITLE
[11.0] Inventory Valuation not possible by location nor WH

### ISSUE THREAD

**Issue by edsersolis** [odoo/odoo#25055] opened 2018-06-04 19:35 UTC
Impacted versions:
11.0

Steps to reproduce:
- Create a Valuation Report
- Group by WH or Location

Current behavior:
- Grouping shows as undefined.

Expected behavior:
- Group by WH or Location.

Use case, maybe the most important one: everytime you have to send a report for insurance you must know what value of stock you have in that location. 

The solution Odoo gave to this issue was to delete the options because the information wasn't been registered in the Quants. This is a huge mistake because of this and other use cases.

@lap-odoo @gustavovalverde

**Comment by gustavovalverde** [comment] 2018-06-05 10:58
This is even a problem if a client gets a fiscal audit, where the regulatory institution needs to match the inventory amount in books with the amount of each Warehouse.

This is a very needed functionality. I can't understand why this was removed in v11.

**Comment by jco-odoo** [comment] 2018-06-12 16:10
Because the financial fifo is calculated for the entire company based on the moves.  (as it is financial and not taking into account the logistics part, it does not take into account locations)

**Comment by edsersolis** [comment] 2018-06-12 23:07
Ok, yes that's the reason. But still doesn't satisfies the need so this ticket shouldn't be closed.

A solution is needed for this.

**Comment by edsersolis** [comment] 2018-06-12 23:09
What about the Inventory?! not only Valuation is affected, you can't have an inventory by location nor warehouse either. 

A fix is needed for this asap.

**Comment by jco-odoo** [comment] 2018-06-13 07:45
There should be no problem in having qties by location/warehouse...

**Comment by gustavovalverde** [comment] 2018-07-01 15:19
I feel this is being taken too lightly.

Companies with great amount of inventory distributed though their stores commonly audit their locations and the money ($) each store has under their responsibility.

For some of our clients it would be _unhealthy_ to migrate their multi-branches to v11, as they won't be able to take administrative decisions based on their inventory fluctuation ($) between locations. This also affects inventory adjustment decisions: is not the same losing 100 pieces in an inventory location that represent US$2,000 than losing 5 pieces that represented US$50,000.

This is a critical regression for clients with high value inventories.

cc: @lap-odoo

**Comment by Yenthe666** [comment] 2018-07-03 06:34
@lap-odoo and @jco-odoo could you please look into the argument from @gustavovalverde? I haven't experienced it myself so I can't decide here.

**Comment by ke-real** [comment] 2018-07-18 07:41
Totally agree with @gustavovalverde. There should be an option to choose between simplified valuation and detailed valuation as simplification might not be an option for all cases. For now I had to bring back stock.history view and adapt it to odoo 11. I know there are certain differences and landed costs might also be an issue, but it still gives a better overview.

**Comment by gustavovalverde** [comment] 2018-07-19 20:01
Just to keep the track here. Today I have the 4th client with this issue; with no possible workaround.

**Comment by wtaferner** [comment] 2018-07-20 04:56
@gustavovalverde and others
Feel free to reuse my commit to have a convenient workaround by applying a little fork commit.

**Comment by ke-real** [comment] 2018-07-20 10:51
@gustavovalverde this is rather too "trivial", it's not FIFO :)

**Comment by edsersolis** [comment] 2018-07-20 15:40
@wtaferner great! Very similar to what Odoo stated suggested to be done when asked through support. Except that `product.cost` should be used instead of `product.standard_price`

Thanks!

**Comment by wtaferner** [comment] 2018-07-20 17:15
@edsersolis 
You are right, I forgot that this is easily possible too as we have a date in hand.
So the computation must have been like that.

```python
    def _compute_trivial_valuation(self):
        for product in self:
            product.trivial_valuation = product.get_history_price(
                product.company_id.id, date=product._context.get('to_date')
            ) * product.qty_available
```

**Comment by lap-odoo** [comment] 2018-07-23 08:52
Hello, 

We're working on a solution for the 11.0. However, I'm not sure yet what we'll be able to achieve in stable. For AVCO and Standard, multiplying Qty by standard_price will work fine but for FIFO it's more complex as what we currently have is a financial FIFO (meaning we don't take into account the locations for the valuation, first value in = first value out, no matter from which location the product is taken). It's probable that we will only have approximation of the valuation per location in case of FIFO valuation.

Thanks !

**Comment by ke-real** [comment] 2018-07-23 09:41
@lap-odoo the pre-11 stock.valuation.history worked well for this use case and it can do it's job for version 11 if modified a bit. Of course it would be inventory FIFO, not financial FIFO as you mentioned (in my case we actually need first). 
Another major change (read "problem") for multi-warehouse setup is that valuation only happens when leaving or enterin the company. Previously leaving or entering from/to transit locations also triggered valuation.

**Comment by lap-odoo** [comment] 2018-07-23 11:06
@ke-real For the transit locations, if you let the company_id field empty on the transit location, the products will be valued. This change allows to manage both use cases. Indeed, some users don't want the products to be considered as "out of stock" when they are only transiting between warehouses.

**Comment by sle-odoo** [comment] 2018-07-24 14:14
Hello,
Would a patch like [this one](https://github.com/odoo-dev/odoo/commit/abce926f7117bcddd30aa7622d860d00f82cc1d0) help you?
The branch is testable in the runbot under the name "11.0-stock-account-by-location-sle".

Regards

**Comment by gustavovalverde** [comment] 2018-07-25 23:09
@sle-odoo could you make it available to log-in? http://runbot.odoo.com/runbot/repo/git-github-com-odoo-dev-odoo-2?search=11.0-stock-account-by-location

**Comment by lap-odoo** [comment] 2018-07-26 07:38
@gustavovalverde I've just launched a rebuild, should be available in +/- 1hr (admin, admin to connect)

**Comment by gustavovalverde** [comment] 2018-08-09 11:00
Hi, will this patch be merged?

**Comment by sle-odoo** [comment] 2018-08-09 11:05
We are waiting for some feedback, did you test it? does the feature looks ok to you?

**Comment by xamissa** [comment] 2018-09-25 10:31
@sle-odoo I have applied the patch and when running the inventory valuation report and grouping by location, the location is still undefined. Is there something further that needs to be done in order for this patch to work?

**Comment by gustavovalverde** [comment] 2018-11-28 14:05
As we have more Enterprise clients, this becomes more and more of an issue. Insurance companies rely on this information to insure each location (branch) of our clients. They insure an amount for that location; but not knowing the amount of the inventory in that location, makes it impossible for the insurance company to issue a warranty to our clients.

**Comment by florca1979** [comment] 2019-01-12 03:48
definitely this empty in odoo either free as enterprice is a disaster there is no client that pays an enterprice version of an erp without having an option of valuation of inventories for each location this does not happen in any erp even with many less functionalities than odoo
that it hurts that odoo does not cover these basic things that any erp has a very deciluted base and many lost clients

**Comment by gustavovalverde** [comment] 2019-01-17 15:03
@xamissa this was not applied to the valuation report but to the inventory report (a bit confusing).

@sle-odoo this is working, just 2 issues: (a) It's too slow on big product databases; a bunch of resources (+8GB) and time (+10min) are needed to compute the report; and (b) the 'value' measure is needed in the pivot view.

**Comment by jjdelarosa** [comment] 2019-01-27 01:16
It's not possibile to get report by location, I hope you can able to resolve this issue, because for insurece policy is neccesary get like that.

Thanks

**Comment by gustavovalverde** [comment] 2019-04-17 13:27
@sle-odoo just pinging here as this is still an issue in **v12**, **master**.

**Comment by bunhin** [comment] 2019-05-09 12:28
very bad and very sad, all cost information and history fields are gone in quant, just don't understand why such a bad move just happen,  the higher version become more shiny in the skin but lesser in essential capability?

**Comment by mcassuto** [comment] 2019-05-28 17:56
We have the same issue at our customer.... Multi-stores and unable to provide the values...

**Comment by jeffryjdelarosa** [comment] 2019-05-28 20:11
We are looking forward to solve this issue,  it so important to us to get the this solved.

**Comment by yostashiro** [comment] 2019-06-03 14:18
It looks like this issue is going to put me into trouble. It puzzles me why the valuation has been removed from quants.

**Comment by sle-odoo** [comment] 2019-06-03 14:28
@yostashiro https://github.com/odoo/odoo/issues/25055#issuecomment-396646533

**Comment by yostashiro** [comment] 2019-06-04 06:58
@sle-odoo #25055 doesn't sound to me like a valid reason for the change - it's just one of the passive reasons if anything. Yes, many small companies probably find no issue with the current design, but I doubt it accommodates the requirements of companies with larger logistical settings. To me the previous design was conceptually easier to understand, and provided much better visibility and flexibility on stock valuation, so I wonder what the motivation was of this change. To be frank, I'm failing to see the benefit of the current design...

**Comment by sle-odoo** [comment] 2019-06-04 07:11
There's a really valid reason, you can only justify using the old real price cost method to your financial institution if all your products are tracked by serial number (ie you can always be sure this unit should be valued to this price, and prove it). As it could only be of use to a low, low number of companies and dropping this feature would allow merging quants and get rid of a lot of performance issues, we did it.

> it's just one of the passive reasons if anything

It's not.

I only let this ticket open because it would be nice to get back this report when the standard or avco cost method is used. I even posted a module a while back to get some feedback but didn't receive any.

**Comment by yostashiro** [comment] 2019-06-04 07:28
@sle-odoo Thank you for the explanation. I understand that merging quants is a good point.

> if all your products are tracked by serial number

I think this is not so uncommon for manufacturing companies, though.  I wish the previous design could have kept even for this particular use case, although I understand the cost of maintaining it.

**Comment by titouanbrauchli** [comment] 2019-06-25 07:43
What is the status of this issue? I do not see anything moving from sides of odoo... I can understand that from a technical point of view this can be pretty difficult, but honestly, as a user I just need this feature as it is hard a major setback to work without.

**Comment by lap-odoo** [comment] 2019-06-25 09:30
You can test on this branch https://github.com/odoo-dev/odoo/tree/master-improve-inventory-report-svs A new value field is added on the inventory report.

**Comment by sle-odoo** [comment] 2019-07-15 08:24
fixed by c861edefaa0009ba214d79a53376c85ab9f45991

**Closed by sle-odoo** 2019-07-15 08:24 UTC
Labels: 11.0, Logistics

**Comment by gustavovalverde** [comment] 2019-07-15 17:10
![giphy](https://user-images.githubusercontent.com/16890942/61234747-ddd46180-a701-11e9-8758-9edf164bc74d.gif)

**Comment by davidtranhp** [comment] 2019-08-02 07:27
@sle-odoo Is there any backport for Odoo 12?

**Comment by pedrobaeza** [comment] 2019-08-02 08:05
You can create a module with that code for being plugged in v11/v12

**Comment by luisg123v** [comment] 2020-03-19 18:51
Hi @pedrobaeza, Do you know if this has been addresssed on any of the OCA's module?

**Comment by pedrobaeza** [comment] 2020-03-19 18:53
No, it doesn't till now.

**Comment by pedrobaeza** [comment] 2020-03-19 18:53
The alternative is https://odoo-community.org/shop/product/stock-inventory-valuation-report-4932

**Comment by luisg123v** [comment] 2020-03-19 19:03
Thanks @pedrobaeza, I'll have a look on that.
