### ISSUE TITLE
[ Bug in Stable latest] odoo purchase confirm button.

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#7833] opened 2015-07-31 14:24 UTC
Hello,

When trying to confirm purchase order, getting bug

Traceback (most recent call last):
  File "/home/latesttest/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/latesttest/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/home/latesttest/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/latesttest/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/latesttest/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/latesttest/odoo/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/home/latesttest/odoo/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/home/latesttest/odoo/addons/web/controllers/main.py", line 955, in exec_workflow
    return request.session.exec_workflow(model, id, signal)
  File "/home/latesttest/odoo/openerp/http.py", line 1111, in exec_workflow
    r = self.proxy('object').exec_workflow(self.db, self.uid, self.password, model, signal, id)
  File "/home/latesttest/odoo/openerp/http.py", line 879, in proxy_method
    result = dispatch_rpc(self.service_name, method, args)
  File "/home/latesttest/odoo/openerp/http.py", line 115, in dispatch_rpc
    result = dispatch(method, params)
  File "/home/latesttest/odoo/openerp/service/model.py", line 37, in dispatch
    res = fn(db, uid, *params)
  File "/home/latesttest/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/latesttest/odoo/openerp/service/model.py", line 183, in exec_workflow
    return exec_workflow_cr(cr, uid, obj, signal, *args)
  File "/home/latesttest/odoo/openerp/service/model.py", line 177, in exec_workflow_cr
    return execute_cr(cr, uid, obj, 'signal_workflow', [res_id], signal)[res_id]
  File "/home/latesttest/odoo/openerp/service/model.py", line 159, in execute_cr
    return getattr(object, method)(cr, uid, *args, **kw)
  File "/home/latesttest/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/latesttest/odoo/openerp/models.py", line 3559, in signal_workflow
    for res_id in ids:
  File "/home/latesttest/odoo/openerp/workflow/__init__.py", line 85, in trg_validate
    return WorkflowService.new(cr, uid, res_type, res_id).validate(signal)
  File "/home/latesttest/odoo/openerp/workflow/service.py", line 91, in validate
    res2 = wi.validate(signal)
  File "/home/latesttest/odoo/openerp/workflow/instance.py", line 75, in validate
    wi.process(signal=signal, force_running=force_running, stack=stack)
  File "/home/latesttest/odoo/openerp/workflow/workitem.py", line 120, in process
    ok = self._split_test(activity['split_mode'], signal, stack)
  File "/home/latesttest/odoo/openerp/workflow/workitem.py", line 248, in _split_test
    self._join_test(t[0], t[1], stack)
  File "/home/latesttest/odoo/openerp/workflow/workitem.py", line 257, in _join_test
    WorkflowItem.create(self.session, self.record, activity, inst_id, stack=stack)
  File "/home/latesttest/odoo/openerp/workflow/workitem.py", line 95, in create
    workflow_item.process(stack=stack)
  File "/home/latesttest/odoo/openerp/workflow/workitem.py", line 120, in process
    ok = self._split_test(activity['split_mode'], signal, stack)
  File "/home/latesttest/odoo/openerp/workflow/workitem.py", line 248, in _split_test
    self._join_test(t[0], t[1], stack)
  File "/home/latesttest/odoo/openerp/workflow/workitem.py", line 272, in _join_test
    WorkflowItem.create(self.session, self.record, activity, inst_id, stack=stack)
  File "/home/latesttest/odoo/openerp/workflow/workitem.py", line 95, in create
    workflow_item.process(stack=stack)
  File "/home/latesttest/odoo/openerp/workflow/workitem.py", line 120, in process
    ok = self._split_test(activity['split_mode'], signal, stack)
  File "/home/latesttest/odoo/openerp/workflow/workitem.py", line 248, in _split_test
    self._join_test(t[0], t[1], stack)
  File "/home/latesttest/odoo/openerp/workflow/workitem.py", line 257, in _join_test
    WorkflowItem.create(self.session, self.record, activity, inst_id, stack=stack)
  File "/home/latesttest/odoo/openerp/workflow/workitem.py", line 95, in create
    workflow_item.process(stack=stack)
  File "/home/latesttest/odoo/openerp/workflow/workitem.py", line 116, in process
    if not self._execute(activity, stack):
  File "/home/latesttest/odoo/openerp/workflow/workitem.py", line 162, in _execute
    returned_action = self.wkf_expr_execute(activity)
  File "/home/latesttest/odoo/openerp/workflow/workitem.py", line 313, in wkf_expr_execute
    return self.wkf_expr_eval_expr(activity['action'])
  File "/home/latesttest/odoo/openerp/workflow/workitem.py", line 291, in wkf_expr_eval_expr
    result = eval(line, env, nocopy=True)
  File "/home/latesttest/odoo/openerp/tools/safe_eval.py", line 314, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/latesttest/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/latesttest/odoo/openerp/api.py", line 547, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/home/latesttest/odoo/addons/purchase/purchase.py", line 872, in action_picking_create
    self._create_stock_moves(cr, uid, order, order.order_line, picking_id, context=context)
  File "/home/latesttest/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/latesttest/odoo/addons/purchase/purchase.py", line 827, in _create_stock_moves
    for vals in self._prepare_order_line_move(cr, uid, order, order_line, picking_id, new_group, context=context):
  File "/home/latesttest/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
ValueError: "_prepare_order_line_move() got multiple values for keyword argument 'context'" while evaluating
u'action_picking_create()'

**Comment by cubells** [comment] 2016-01-07 09:33
@tejastank: 
Did you solve this problem? I've got this problem now.

**Comment by tejastank** [comment] 2016-01-07 11:23
Yes, we fixed, but I not remember for which client I had fixed.

In case you till getting, first pull code again then reload server.

**Comment by Yenthe666** [comment] 2016-05-25 13:41
Hi @tejastank,

I can no longer reproduce this issue on the newest Odoo versions.
If you should still face this issue please update your codebase and it will be fixed!
Closing this since it can no longer be reproduced.

Regards,
Yenthe

**Closed by Yenthe666** 2016-05-25 13:41 UTC

**Comment by tejastank** [comment] 2016-05-26 14:27
@Yenthe666 Thanks for quick update on issues.
