### ISSUE TITLE
[v14] zip required issue

### ISSUE THREAD

**Issue by HieuMinh67** [odoo/odoo#58950] opened 2020-10-02 07:28 UTC
Impacted versions: 14.0

Steps to reproduce:
Using module web

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/43398131/94898243-6c75ff80-04bb-11eb-989b-657040e1d75e.png)

**Comment by pedrobaeza** [comment] 2020-10-02 07:38
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by HieuMinh67** [comment] 2020-10-02 07:50
I had reproduced the problem in runbot infrastructure. And it seem happening  when I add a new address when I check out from my order

**Comment by pedrobaeza** [comment] 2020-10-02 07:51
Please indicate detailed and complete steps to reproduce it.

**Comment by HieuMinh67** [comment] 2020-10-02 08:26
Although I recorded in local env but I did the same in runbot infrastructure
[Link to the video](https://drive.google.com/file/d/1ymL7afVBYJjLcDapXFDpqIwY_Py3dUVZ/view?usp=sharing)

**Comment by pedrobaeza** [comment] 2020-10-05 08:07
Are you sure with latest version is happening the same?

**Comment by HieuMinh67** [comment] 2020-10-06 09:20
Yes, it's happening the same. This time, I have recorded when i reproduce on runbot. [Link to the video](https://drive.google.com/file/d/1TiSID9P6QmtYy9pk522g3ldEjtTfnUqS/view?usp=sharing)

**Comment by HieuMinh67** [comment] 2020-10-06 09:46
I have found the problem. That error occurs when I skip the 'zip code' and select the 'Country' and 'zip code' disappear

**Comment by JKE-be** [comment] 2020-10-23 13:51
Hey,

Thanks. 
Not really sure about the right way to fix it.

Format address let's suppose that zip is not needed in address so field are hidden in ecommerce.
While ecommerce think that the field zip is required (set on country)

![image](https://user-images.githubusercontent.com/4848797/97011832-7681a000-1547-11eb-85c5-4101b35b2953.png)


What is the real solution ? 
Zip (postal code) needed in format address, or not required on country ? 

If you can confirm @HieuMinh67  since it seems you are from Vietnam ;) thank you

**Closed** 2020-10-26 09:21 UTC
Labels: 14.0, Website
