### ISSUE TITLE
Error when you add a product in a stock.picking

### ISSUE THREAD

**Issue by rdeheele** [odoo/odoo#1325] opened 2014-07-23 10:02 UTC
**_Impacted versions:**_
runbot.odoo.com (last 7.0)
07329-7-0-9a2001

**_Steps to reproduce:**_
1. Create a stock.picking
2. Add a line with "Add an item"
3. select a product
4. Click "Save"

**_Current behavior:**_
- A traceback occurs : 
  Server Traceback (most recent call last):
  File "/home/bak/runbot/extra/runbot/static/build/07329-7-0-9a2001/openerp/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/home/bak/runbot/extra/runbot/static/build/07329-7-0-9a2001/openerp/netsvc.py", line 296, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/home/bak/runbot/extra/runbot/static/build/07329-7-0-9a2001/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, _params)
  File "/home/bak/runbot/extra/runbot/static/build/07329-7-0-9a2001/openerp/osv/osv.py", line 190, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/home/bak/runbot/extra/runbot/static/build/07329-7-0-9a2001/openerp/osv/osv.py", line 132, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/07329-7-0-9a2001/openerp/osv/osv.py", line 199, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/home/bak/runbot/extra/runbot/static/build/07329-7-0-9a2001/openerp/addons/audittrail/audittrail.py", line 532, in execute_cr
    return fct_src(cr, uid, model, method, _args, *_kw)
  File "/home/bak/runbot/extra/runbot/static/build/07329-7-0-9a2001/openerp/osv/osv.py", line 187, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/home/bak/runbot/extra/runbot/static/build/07329-7-0-9a2001/openerp/osv/orm.py", line 2372, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/home/bak/runbot/extra/runbot/static/build/07329-7-0-9a2001/openerp/osv/orm.py", line 4954, in _search
    cr.execute('SELECT "%s".id FROM ' % self._table + from_clause + where_str + order_by + limit_str + offset_str, where_clause_params)
  File "/home/bak/runbot/extra/runbot/static/build/07329-7-0-9a2001/openerp/sql_db.py", line 161, in wrapper
    return f(self, _args, *_kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/07329-7-0-9a2001/openerp/sql_db.py", line 226, in execute
    res = self._obj.execute(query, params)
  DataError: invalid input syntax for integer: "one2many_v_id_232"
  LINE 1: ...ove".id FROM "stock_move" WHERE "stock_move".id = 'one2many_

**_Expected behavior:**_
- no traceback

Regards,

**Comment by Yenthe666** [comment] 2017-08-24 15:32
Hi @rdeheele,

Thank you for your report.
This report is against an Odoo version that is no longer supported (Odoo supports back untill three versions).
As this bug is for an old Odoo and I can't reproduce it anymore I'm closing this.
Please do feel free to create a new issue if you face this for V8, V9 or V10.

Regards,
Yenthe

**Closed by Yenthe666** 2017-08-24 15:32 UTC
