### ISSUE TITLE
 500 Internal Server Error

### ISSUE THREAD

**Issue by rajeshbk042** [odoo/odoo#14695] opened 2016-12-12 18:54 UTC
Impacted versions:Odoo 10

Steps to reproduce:Run the odoo 10 source package on windows , Please run odoo in cmd and enter http://localhost:8069 on browser. cmd doesn't accessing while I browse http://localhost:8069, its in same stage not updating with no lines of execution.

Current behavior:No connection between browser and cmd while running

Expected behavior: Should show the odoo page on browser and update cmd running states.

Video/Screenshot link (optional):

**Comment by edsersolis** [comment] 2016-12-12 19:14
Have you made sure the service is running?

**Comment by WhitleyStriber** [comment] 2016-12-12 21:13
Have you ensured your Windows Firewall isn't blocking anything through localhost?

**Comment by daramousk** [comment] 2016-12-17 23:54
Check your server logs. The issue is probably reported over there. This error is reported as `CRITICAL` in odoo logs.

**Comment by Yenthe666** [comment] 2018-01-12 14:35
Closing as there was never any feedback.

**Closed by Yenthe666** 2018-01-12 14:35 UTC
