### ISSUE TITLE
[12] Send Quotation by E-Mail Error

### ISSUE THREAD

**Issue by technicomp** [odoo/odoo#27427] opened 2018-10-04 11:20 UTC
Impacted versions: 12

Steps to reproduce: Create a Quotation, Send by E-Mail

Current behavior: 

Fehler beim Erstellen der Vorlage <Template memory:6afd190> mit den Werten {'format_date': <function MailTemplate._render_template.<locals>.<lambda> at 0x06DF66A8>, 'format_tz': <function MailTemplate._render_template.<locals>.<lambda> at 0x055CF6F0>, 'format_amount': <function MailTemplate._render_template.<locals>.<lambda> at 0x055CF270>, 'user': res.users(2,), 'ctx': {'lang': 'de_CH', 'tz': False, 'uid': 2, 'params': {'return_label': 'Website', 'model': 'sale.order', 'id': 1, 'action': 525, 'view_type': 'form'}, 'active_model': 'sale.order', 'active_id': 1, 'active_ids': [1], 'default_model': 'sale.order', 'default_res_id': 1, 'default_use_template': True, 'default_template_id': 18, 'default_composition_mode': 'comment', 'mark_so_as_sent': True, 'custom_layout': 'mail.mail_notification_paynow', 'proforma': False, 'force_email': True, 'search_disable_custom_filters': True, 'tpl_partners_only': True}, 'object': sale.order(1,)} 

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2018-10-04 11:35
Are you doing this in English? If not, try on English and if no problem, then the issue is with an incorrect translation that you will need to fix on Transifex.

**Comment by sswapnesh** [comment] 2018-10-04 17:01
Seems working fine on Latest Build, Please make sure someone has not modified Email template. (You can upgrade module and try again)

**Comment by technicomp** [comment] 2018-10-08 07:08
Hello, 
The E-Mail Template is not modified - it is a plain installation. I switched the language to english and get an error again.

Failed to render template <Template memory:7fce70c33e10> using values {'ctx': {'lang': 'en_US', 'default_res_id': 1, 'force_email': True, 'mark_so_as_sent': True, 'default_template_id': 16, 'search_disable_custom_filters': True, 'default_use_template': True, 'tpl_partners_only': True, 'default_model': 'sale.order', 'default_composition_mode': 'comment', 'active_ids': [1], 'active_model': 'sale.order', 'custom_layout': 'mail.mail_notification_paynow', 'tz': False, 'uid': 2, 'proforma': False, 'active_id': 1}, 'object': sale.order(1,), 'user': res.users(2,), 'format_amount': <function MailTemplate._render_template.<locals>.<lambda> at 0x7fce73e58d90>, 'format_date': <function MailTemplate._render_template.<locals>.<lambda> at 0x7fce73e58950>, 'format_tz': <function MailTemplate._render_template.<locals>.<lambda> at 0x7fce73e58ea0>}

**Comment by pedrobaeza** [comment] 2018-10-11 16:48
I have tried again on runbot and it's working, so please check everything on your side. Closing.

**Closed by pedrobaeza** 2018-10-11 16:48 UTC
Labels: 12.0, Need information
