### ISSUE TITLE
[11.0]  multi-worker mode is slower than single worker mode when hitting memory limits

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#21391] opened 2017-12-02 04:16 UTC
Impacted versions:
11-ce, 11-ee

Steps to reproduce:

run odoo with workers= 10 [any number bigger than 1]
you should notice odoo is very slow

Current behavior:

 multi-worker mode is the same fast like single worker mode

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment] 2017-12-04 08:26
@odony as this is worker and performance related I think you're probably the best guy to answer this.

**Comment by odony** [comment] 2017-12-04 08:34
@jeffery9 with so little information, we can't really help you ;-)

You'll have to provide much more information:
- your deployment architecture
- your hardware
- your configuration files for Odoo and PostgreSQL and your web server
- if multi-server, how are you sharing the sessions, source and filestore
- logfiles showing the system running
- and as much other info you can provide..

**Comment by gdgellatly** [comment] 2017-12-04 09:26
@odony I have noticed this behaviour over the past week, possibly fortnight as well in dev.  Like really noticeably slow, 10-100x slower than usual to start and load a worker.  Like maybe 40 seconds from launch to load compared to couldn't even switch to browser screen and it was ready before.

I'll update this tomorrow with exact details, left laptop at work, but the setup has not changed in 3 months, except for pulling latest code every few days.  I can tell you watching the logs, that it is the loading that is taking time, not actual activity.

PG10 w/ fairly standard pg tune settings on Ubuntu 16.04 desktop / 16gb RAM, internal SSDs, Intel i7 with 8 cores.
4 workers, usual type limits, probably around 2gb per worker maybe a bit more. 
1 testing enterprise database with maybe 50 sales, 8 products, 10 customers so small.
No more than 1 or 2 users ever.
Filestore, just whatever is default config - not that it matters - there's maybe 10 files.
Python 3.5.2 venv

I got sick of it at one point so ran with gevent instead and it was noticably better.  I'll retry that experiment tomorrow as well and get some real numbers.

**Comment by jeffery9** [comment] 2017-12-04 14:52
your deployment architecture
as a cluster, with 6 server. 2 node db cluster, 2 node odoo cluster, 1 nfs and 1 nginx

your hardware
2 postgresql with pgpool, each one is 72 core and 512 G RAM, with 10G bond network card.
2 odoo server with 24 core and 128G ram
1 nginx server with 8 core and 128G ram
1 nfs server with 8 core and 256G ram, this one act as redis server for session store too.

your configuration files for Odoo and PostgreSQL and your web server
odoo have been test run in thread mode and prefork mode,  thread mode is almost 10~100 times  more faster  than prefork mode...  odoo read api call consumed  50ms in thread mode, but  1.5~3 s in prefork mode.
in prefork mode, i have set the workers to 48

and found one funny thing.  with default memory_limits setting, it always said it exceed  soft_limit  2G, this should let  HttpWorker exit and start new one. so it seemed that  it is out of service.

if multi-server, how are you sharing the sessions, source and filestore
logfiles showing the system running
and as much other info you can provide..

store filestore on NFS, and save session in redis server, worker set to 48, and memory is enough .

key configuration item calculated use this 
![image](https://user-images.githubusercontent.com/1404460/33558715-97882ae4-d945-11e7-933b-33b6983cf6ef.png)

**Comment by jeffery9** [comment] 2017-12-13 05:12
for thread mode.  it laod page less than 1 seconds.
![image](https://user-images.githubusercontent.com/1404460/33922636-0ecea6f6-e007-11e7-838a-193174d7a5f8.png)


for multi-process mode. there is a long time to load the page
![image](https://user-images.githubusercontent.com/1404460/33922638-198ee042-e007-11e7-9924-170e0b7e93ed.png)

and there occurred worker  reboot.
![image](https://user-images.githubusercontent.com/1404460/33922661-308451f6-e007-11e7-89c7-b71d33d834a2.png)

**Comment by odony** [comment] 2017-12-13 08:42
@jeffery9 thanks for the extra info!
You did not mention, is the problem solved after setting higher memory limits (i.e. the slowness is only caused by workers restarting), or is it still very slow even if you set the memory limit very high?

How is the memory usage of the server workers? If you use `htop` to monitor the workers when you use them, does the memory climb quickly, does it stop at some value, etc? (Maybe a small video of your htop output while you run some tests could help)

Thanks!

**Comment by jeffery9** [comment] 2017-12-13 15:06
@odony  have set the limit_memory_soft  to 2.5 G, worker is alive, this is ok...  there have another trouble, that is `check_signaling()` always trigger `cache_invalidated` and reload all modules. if there have any document for those ? thanks.

**Comment by odony** [comment] 2017-12-13 16:26
> @odony have set the limit_memory_soft to 2.5 G, worker is alive, this is ok...

Is the performance OK after you change the memory limit?

>  there have another trouble, that is check_signaling() always trigger cache_invalidated and reload all modules. if there have any document for those ?
> (...)
> cache already set to 407, this one [Cache - 407 -> 411], why still is 399 [Cache - 399 -> 411]

The cache is per worker process. Each worker has a different cache state, and when one worker signals that the cache changed, all workers will invalidate their cache, one by one, when they handle the next request.
Specifically, in your example:

1. at 2017-12-13 14:31:52,092, **worker 8044** loads registry at cache 110, then generates the routing map and answers to `/web/action/load`. This causes a cache invalidation for some reason, so it is signaled to all other workers as a new cache version (411)
2. at 2017-12-13 14:31:54,993, **worker 8054** was at cache version 407, so it updates to 411 before answering request for `/web/action/load`
3. at 2017-12-13 14:31:55,432,  **worker 8058**  was at cache 399, so it updates to 411 too, before answering request for `/web/action/run`

This is normal and should not cause any performance penalty. Just turn off DEBUG if you want to avoid the extra noise.

**Comment by jeffery9** [comment] 2017-12-14 00:39
for odoo11 on py3,  each worker consume memory more than 2GB [default memory limit ], so change memory limit to 2.5GB, workers will not reboot.

i want to reduce `cache invalidation` and `registry invalidation`, can you give some tips and helps ? thanks.

**Comment by odony** [comment] 2017-12-14 01:49
@jeffery9 you will have to look into the cause for these invalidations, it's very hard to guess without having access to your installation.
Registry invalidation should only happen if you install modules or modify fields/models or automated actions. Definitely not common.
Cache invalidation occurs when users modify cached data - this can be more frequent and should not be a problem.

**Comment by jeffery9** [comment] 2017-12-14 08:16
have search the code, found that each web request session exit should send `signal_changes` to registry.  does this effect the performance?

**Comment by Yenthe666** [comment] 2018-05-03 05:59
@odony and @jeffery9 where are we with this issue? Is this issue still present?

**Comment by lukebranch** [comment] 2018-05-10 04:58
@jeffery9 ,

This is a long shot, but worth double-checking just to rule it out. Do you have the following defined in your odoo-server.conf file?:
```
; XML RPC
xmlrpc = True
xmlrpc_port = 8069
longpolling_port = 8072
xmlrpc_interface = 127.0.0.1
```

**Comment by moylop260** [comment] 2018-06-01 06:10
@jeffery9 
Could you add to `signal_changes` method:
 - https://github.com/odoo/odoo/blob/074ec1aeae281405d998406819808795e4e6c406/odoo/modules/registry.py#L411

the following lines:
```python
import traceback
_logger.warning("It is not a real error %s", traceback.extract_stack())
```

In order to see what methods is calling to `signal_changes`
Maybe a cron that is starting when you run odoo.py:
 - https://github.com/odoo/odoo/blob/074ec1aeae281405d998406819808795e4e6c406/odoo/addons/base/ir/ir_cron.py#L87-L106

**Comment by jeffery9** [comment] 2018-06-01 10:33
OK I'll try

发自我的华为手机

-------- 原始邮件 --------
主题：Re: [odoo/odoo] [11.0] multi-worker mode is slower than single worker mode (#21391)
发件人：moylop260
收件人：odoo/odoo
抄送：Jeffery CHEN Fan ,Mention


@jeffery9<https://github.com/jeffery9>
Could you add to signal_changes method:

  *   https://github.com/odoo/odoo/blob/074ec1aeae281405d998406819808795e4e6c406/odoo/modules/registry.py#L411

the following lines:

import traceback
_logger.warning("It is not a real error %s", traceback.extract_stack())

In order to see what methods is calling to signal_changes
Maybe a cron that is starting when you run odoo.py:

  *   https://github.com/odoo/odoo/blob/074ec1aeae281405d998406819808795e4e6c406/odoo/addons/base/ir/ir_cron.py#L87-L106

―

**Comment by moylop260** [comment] 2018-06-01 17:04
FYI I have created an issue that could be related to this one:
 - https://github.com/NETLINKSAF/apps_mod/issues/3729

**Comment by pedrobaeza** [comment] 2018-07-02 01:12
Any news on this?

**Comment by moylop260** [comment] 2018-07-02 02:55
Please, Could you apply the following patch and tested it again?
https://github.com/odoo/odoo/pull/25234

**Comment by odony** [comment] 2018-07-02 08:08
Looks like the original problem was solved by setting higher memory limits, so we can close this issue. By the way, as of Odoo 12 the limits are going to be applied to multi-threaded mode too, so we'll have a more uniform behavior in that area.

Same thing for cache/registry invalidation: it's already done identically in multi-process and multi-thread mode, as of 10.0, since c60b22335be6358307facbe665bbdb3d7f8a435e.

**Closed by odony** 2018-07-02 08:08 UTC
Labels: 11.0, Framework, Need information
