### ISSUE TITLE
[All]Duplicate pricelist : same name

### ISSUE THREAD

**Issue by fredericpannetier** [odoo/odoo#135441] opened 2023-09-14 09:20 UTC
Impacted versions: 15, 16, 17

Steps to reproduce: In pricelist view form, Action / Duplicate

Current behavior: Same is the same, Old : EUR, New : EUR

Expected behavior: New : EUR (Copy)

**Comment by vava-odoo** [comment] 2023-09-22 10:15
Hi @fredericpannetier 
Thanks for your feedback. 
However, I don't really see the usefulness of this change. In any case, you would have to change the name, as "(copy)" will not really help you differentiating your pricelists.
As this is not a bug, I'm closing the ticket, but I'll share the feedback internally to be sure.
Cheers

**Closed by vava-odoo** 2023-09-22 10:15 UTC
