### ISSUE TITLE
Inherits with more than one parent

### ISSUE THREAD

**Issue by funkring** [odoo/odoo#503] opened 2014-06-12 11:55 UTC
Problem
----------

I use a model which <code> _inherits = [ "product.product" : product_id "]  </code> and than i search with <code> some_model_obj.search(cr, uid, [], order="name") </code> an error occurs, because the sql query was build like this:

<pre>
SELECT "some_model_product".id FROM "product_product" as "some_model_product__product_id",
"some_model_product",
"product_template" as "product_product__product_tmpl_id" 
WHERE ("some_model_product"."product_id"="some_model_product__product_id"."id")
 AND ("some_model_product__product_id"."active" = %s) 
 AND ("product_product"."product_tmpl_id" = "product_product__product_tmpl_id"."id")
 ORDER BY product_product__product_tmpl_id."name"  
</pre>

see **<code>... AND ("product_product"."product_tmpl_id"... </code>** thats wrong.

Bugfix
--------

I made following Bugfix...

<pre>
diff --git a/openerp/osv/orm.py b/openerp/osv/orm.py
index e8730e0..d388501 100644
--- a/openerp/osv/orm.py
+++ b/openerp/osv/orm.py
@@ -2488,7 +2488,7 @@
                                                        context=context)
         return result
 
-    def _inherits_join_add(self, current_model, parent_model_name, query):
+    def _inherits_join_add(self, current_model, parent_model_name, query, current_alias=None):
         """
         Add missing table SELECT and JOIN clause to ``query`` for reaching the parent table (no duplicates)
         :param current_model: current model object
@@ -2497,7 +2497,7 @@
         """
         inherits_field = current_model._inherits[parent_model_name]
         parent_model = self.pool[parent_model_name]
-        parent_alias, parent_alias_statement = query.add_join((current_model._table, parent_model._table, inherits_field, 'id', inherits_field), implicit=True)
+        parent_alias, parent_alias_statement = query.add_join((current_alias or current_model._table, parent_model._table, inherits_field, 'id', inherits_field), implicit=True)
         return parent_alias
 
     def _inherits_join_calc(self, field, query):
@@ -2510,12 +2510,14 @@
         :return: qualified name of field, to be used in SELECT clause
         """
         current_table = self
+        current_alias = None
         parent_alias = '"%s"' % current_table._table
         while field in current_table._inherit_fields and not field in current_table._columns:
             parent_model_name = current_table._inherit_fields[field][0]
             parent_table = self.pool[parent_model_name]
-            parent_alias = self._inherits_join_add(current_table, parent_model_name, query)
+            parent_alias = self._inherits_join_add(current_table, parent_model_name, query, current_alias=current_alias)
             current_table = parent_table
+            current_alias = parent_alias
         return '%s."%s"' % (parent_alias, field)
 
     def _parent_store_compute(self, cr):
</pre>

**Comment by rco-odoo** [comment] 2015-06-09 07:44
@funkring if I am not mistaken, this is a duplicate of issue #5761, which has been fixed by #6666.

**Closed by rco-odoo** 2015-06-09 07:44 UTC
Labels: duplicate
