### ISSUE TITLE
Issue with website theme

### ISSUE THREAD

**Issue by vr0929** [odoo/odoo#75207] opened 2021-08-17 15:23 UTC
Impacted versions: 13

Steps to reproduce: 

Current behavior: Encountering an error when loading the shop and categories page on the website module when using a new theme. (See below for error)

Expected behavior: Pages load properly using other themes

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Error Message:**

QWeb

Error message:

Error to render compiling AST
AttributeError: 'product.template' object has no attribute '_get_image_holder'
Template: website_sale.products_item
Path: /t/form/div[1]/a/t[1]
Node: <t t-set="image_holder" t-value="product._get_image_holder()"/>
                

The error occured while rendering the template website_sale.products_item and evaluating the following expression: <t t-set="image_holder" t-value="product._get_image_holder()"/>
Traceback

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 332, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_website_sale_products_item_137546
AttributeError: 'product.template' object has no attribute '_get_image_holder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 229, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 809, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 342, in checked_call
    result.flatten()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1236, in flatten
    self.response.append(self.render())
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1229, in render
    return env["ir.ui.view"].render_template(self.template, self.qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1177, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_ui_view.py", line 336, in render
    return super(View, self).render(values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/web_editor/models/ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1185, in render
    return self.env[engine].render(self.id, qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 58, in render
    result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 260, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 334, in _compiled_fn
    raise e
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 332, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_website_sale_products_137516
  File "<template>", line 2, in body_call_content_137514
  File "<template>", line 266, in foreach_137507
  File "<template>", line 267, in foreach_137506
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 339, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.models.qweb.QWebException: 'product.template' object has no attribute '_get_image_holder'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 332, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_website_sale_products_item_137546
AttributeError: 'product.template' object has no attribute '_get_image_holder'

Error to render compiling AST
AttributeError: 'product.template' object has no attribute '_get_image_holder'
Template: website_sale.products_item
Path: /t/form/div[1]/a/t[1]
Node: <t t-set="image_holder" t-value="product._get_image_holder()"/>

**Comment by pedrobaeza** [comment] 2021-08-17 15:36
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2021-08-17 15:36 UTC
