### ISSUE TITLE
One2many html attribute data-id does not match with the database id

### ISSUE THREAD

**Issue by nomadic-coding** [odoo/odoo#51932] opened 2020-05-27 00:53 UTC
Impacted versions:
13.0

Steps to reproduce:
1) Edit Form view to show ID field on any one2many widget. e.g. sales order
2) open web debugger
Current behavior:
The data-id in the html does **not match** the id in the database. 

Expected behavior:
The data-id **matches** the id in the database.

Video/Screenshot link (optional):
![Selection_049](https://user-images.githubusercontent.com/38637556/82964168-63fc3e00-9f8a-11ea-989b-3ce350e2e7b3.png)

**Comment by pedrobaeza** [comment] 2020-05-27 06:53
This is because it uses internal data and it's not expected to be the database ID. You need to find other way for what you are looking for and know JS internals.

Closing as no issue, but expected behavior.

**Closed by pedrobaeza** 2020-05-27 06:53 UTC

**Comment by nomadic-coding** [comment] 2020-05-30 22:18
if someone else is looking for this have a look at the javascript function traverse_records in web.utils

`get_selected_ids_one2many: function () {
            var self=this;
            var ids =[];
            this.$el.find('td.o_list_record_selector input:checked')
                    .closest('tr').each(function () {
                        ids.push(parseInt(self._getResId($(this).data('id'))));
            });
            return ids;
        },

         //* Traverse recordData to find and return the recordId with given dataPoint id
        _getResId: function (recordId) {
            var record;
            utils.traverse_records(this.recordData[this.name], function (r) {
                if (r.id === recordId) {
                    record = r;
                }
            });
            return record.res_id;
        },`
