### ISSUE TITLE
pos_sale session can't be closed

### ISSUE THREAD

**Issue by eddybc** [odoo/odoo#33511] opened 2019-05-20 16:29 UTC
Impacted versions:
11.0
Steps to reproduce:
1. Set the company Rounding Method as "Round Globally"
2. Create the next taxes for sales:
- 0%
- 8% - Price included
- 16% - Price included
3. Configure 14 products with the next prices and taxes:
https://drive.google.com/file/d/1Bp_BgR-HR6lbVSev07KtV_yHfeyOBIgO/view?usp=sharing
4. Make a PoS order with those products 
5. Try to close the session

Current behavior:
When I try to close the session, I get the next error: Cannot create unbalanced journal entry.

Expected behavior:
The session is closed

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment] 2019-05-20 17:26
Duplicate of https://github.com/odoo/odoo/issues/32667 (Same behaviour but different place)

**Comment by Yenthe666** [comment] 2019-05-21 06:25
Not really a duplicate if it is in another place 😉 @switch87 for you.

**Comment by switch87** [comment] 2019-05-21 12:12
@eddybc I can't reproduce this problem. I tried on 11.0 and 12.0

**Comment by sswapnesh** [comment] 2019-05-21 18:03
> Not really a duplicate if it is in another place  @switch87 for you.

You are right (and also Both are for different Versions, My bad)

I have tried to Reproduce same with all steps (Taxes including Prices/ Rounding as well) and It seems working well

**Comment by luistorresm** [comment] 2019-05-22 17:53
Hello @switch87 @sswapnesh 

With the same products?

OPW #1998831

**Comment by sswapnesh** [comment] 2019-05-22 18:08
Hello @luistorresm 

> With the same products?

No, I have tried with other Product but setting up Correct Tax/Config.

**Comment by luistorresm** [comment] 2019-05-22 18:17
I understand.

This not fail in all the cases, only with some values.

Like the case in the initial video.

Regards

**Comment by sswapnesh** [comment] 2019-05-22 18:20
I didn't found any Video shared here. (Maybe you have added this on OPW)

**Comment by umontiel** [comment] 2019-05-22 18:31
Hello @sswapnesh  @luistorresm 

You can try with these orders:

![image](https://user-images.githubusercontent.com/50925754/58199105-62bc7500-7c95-11e9-9788-836b0182491a.png)

I copy a video

https://youtu.be/H0ppYrZd2Wo

**Comment by switch87** [comment] 2019-05-24 09:36
@umontiel I see they are already testing it at Odoo support. Since they can test on duplicate databases of the enterprise db in the video I think it's best to try to solve it with them.

cc: @sswapnesh @luistorresm

**Comment by sswapnesh** [comment] 2019-06-12 18:15
Maybe we can close if it has been handled though Odoo support team

**Comment by Yenthe666** [comment] 2019-06-12 19:30
@mart-e actually has a script that runs once in a while to match issues here labeled with OE (and the OPW) with the enterprises issues to auto close. Could you guys add the OPW?

**Comment by luistorresm** [comment] 2019-06-12 21:03
Here is the OPW @Yenthe666 

OPW #1998831

**Comment by Yenthe666** [comment] 2019-07-31 14:41
@mart-e or @switch87 could one of you check the related status of this OPW? I assume this has been solved in the meanwhile right?

**Closed** 2019-07-31 16:27 UTC
Labels: 12.0, Need information, OE, Point of Sale

**Comment by houssine78** [comment] 2019-09-19 12:15
@mart-e @switch87 @Yenthe666 do this was a misconfiguration or a bug as this happens in Odoo Community with tax_calculation_rounding_method to True.
