### ISSUE TITLE
record tree <widget  update error

### ISSUE THREAD

**Issue by snowtianyou** [odoo/odoo#72102] opened 2021-06-14 03:27 UTC
Impacted versions:13

Steps to reproduce:
'record tree add  widget name="res_config_edition" '
Current behavior:
update model error 
--dev = xml,qweb    Successful entry into force
Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):
![image](https://user-images.githubusercontent.com/26185123/121835551-28065900-cd04-11eb-811f-ab0c2bc029fc.png)
![image](https://user-images.githubusercontent.com/26185123/121837796-1d01f780-cd09-11eb-9ea8-91de9b51ea61.png)

**Comment by pedrobaeza** [comment] 2021-06-14 06:41
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2021-06-14 06:41 UTC
