### ISSUE TITLE
remaining time in task will be count as zero if no timesheet input.

### ISSUE THREAD

**Issue by fausthuang** [odoo/odoo#10541] opened 2016-01-20 07:10 UTC
in Odoo V9. 
eg:We create a task and set the initial time as 10 hours. but didn't add timesheet time yet.
in task list view or report. the task remaining time will be show as zero, but not 10 hours.
the screenshot as following:
![image](https://cloud.githubusercontent.com/assets/16218652/12442071/c490b38c-bf87-11e5-87d6-31288d8c6155.png)

**Comment by pedrobaeza** [comment] 2018-04-11 22:44
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-04-11 22:44 UTC
Labels: 9.0, Services
