### ISSUE TITLE
Bug in query builder when many2one field is empty in other table

### ISSUE THREAD

**Issue by kirtangajjar** [odoo/odoo#64247] opened 2021-01-08 10:11 UTC
Apologies for a poor title, that's the best I could give. 

Impacted versions: 13.0

Steps to reproduce:
1. Add many2many field `department_ids` on user.
2. Add many2one field `department_id` on warehouse and location.
3. Create couple of transfers and inventory adjustments in departments you have access to.
4. Add following domain in `ir.rule` on `stock.move.line`:
```
[
'|',
    ('picking_id.picking_type_id.warehouse_id.department_id','in', [x.id for x in user.department_ids]),
    '&',
        ('location_id.usage','=', 'inventory'),
        ('location_dest_id.department_id','in', [x.id for x in user.department_ids])
]
```

It's a pretty simple rule that is used to ensure that users only see stock move lines from their own department.
1st node in domain is used to allow users access to all stock move lines that have a picking (i.e. are transfers).
2nd and 3rd node in domain is used to give access to inventory adjustment to users.

5. Go to "Product Moves" tab.

Current behavior:

You will see only those stock move lines which have a picking id(i.e. Transfers), but you won't be able to see any entry of  "Inventory Adjustments". On further debugging, the issue seems to be in query generated, which looks like following:

```
SELECT  "stock_move_line".id
FROM "stock_move_line","stock_picking" AS "stock_move_line__picking_id"
WHERE ("stock_move_line"."state" = %s) 
AND ("stock_move_line"."picking_id"="stock_move_line__picking_id"."id") 
AND (("stock_move_line__picking_id"."picking_type_id" IN (%s...)) OR (("stock_move_line"."location_id" IN (%s...)) AND ("stock_move_line"."location_dest_id" IN (%s...))))
ORDER BY "stock_move_line"."date" ASC 
LIMIT 80
```

More precisely, the issue seems to be in these lines:
```
AND ("stock_move_line"."picking_id"="stock_move_line__picking_id"."id") 
AND (("stock_move_line__picking_id"."picking_type_id" IN (%s...)) OR (("stock_move_line"."location_id" IN (%s...)) AND ("stock_move_line"."location_dest_id" IN (%s...))))
```
Here, because of first line which matches `picking_id` from `stock_move_line` and `stock_picking` tables, all the records which do not have a `picking_id` in `stock_move_line`(i.e. Inventory Adjustments) are getting omitted.

Expected behavior:
Both the Transfers and Inventory Adjustments should be visible when this domain is set.

(optional) Alternate way to verify bug:

You can also verify this bug by checking number of records in both the domains separately, and then by combining the domains:
1st domain: 
```
('picking_id.picking_type_id.warehouse_id.department_id','in', [x.id for x in user.department_ids])

len(self.env['stock.move.line'].search([('picking_id.picking_type_id.warehouse_id.department_id','in', [x.id for x in user.department_ids])]))

Result: 5911
```
2nd domain: 
```
len(self.env['stock.move.line'].search([('location_id.usage','=', 'inventory'),('location_dest_id.department_id','in', [x.id for x in user.department_ids])]))

Result: 1567
```

Both domains combined:
```
len(self.env['stock.move.line'].search(['|',('picking_id.picking_type_id.warehouse_id.department_id','in', [x.id for x in user.department_ids]),'&',('location_id.usage','=', 'inventory'),('location_dest_id.department_id','in', [x.id for x in user.department_ids])]))

Result: 5911
```

Since first query will only look for picking, and second query only looks for inventory transfers, combining them with "or" should increase the output of count to approx their sum(7478). However, it remains the same, proving my point.

Interestingly, the following domains works when we change picking_id to `move_id`
```
len(self.env['stock.move.line'].search(['|',('move_id.picking_type_id.warehouse_id.department_id','in', [x.id for x in user.department_ids]),'&',('location_id.usage','=', 'inventory'),('location_dest_id.department_id','in', [x.id for x in user.department_ids])]))

Result: 7482
```

**Comment by pedrobaeza** [comment] 2021-01-08 12:24
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this. Specifically, bad balanced domain.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2021-01-08 12:24 UTC
