### ISSUE TITLE
[9.0] Journal configuration doesn't have allow canceling entries checkbox

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#8532] opened 2015-09-15 08:07 UTC
Hi Odoo,

On version 9, even we already installed account_cancel module,
on the journal configuration form, there's no checkbox about allow canceling entries as like previous version.

The expected behavior, should be we have checkbox to configure the journal if the entries on this journal can be cancel or not.

**Comment by patricksindelka** [comment] 2015-10-17 22:53
Exactly the same problem here. Hope they'll fix it.

**Comment by bleuubuntu** [comment] 2016-01-26 14:33
I think so too, but I finally find it, you have to activate debug mode, and go to journal - advanced settings (from your invoice page - other info - journal)

**Comment by jinzo** [comment] 2016-02-03 09:12
I'm quite sure I followed this procedure on the latest 9.0 and it looks like that it doesen't work for some of us. I would presume that it has something to do with outdated localization packages that we have installed? I'm planing to investigate further.

**Comment by csnauwaert** [comment] 2018-02-28 10:59
Hello,

Sorry for the time it took to reply to this issue, as @bleuubuntu said, you have to be in debug mode in order to see the advanced settings in the journal and if you've installed the account_cancel module you'll see the option to "allow cancel entries" on the journal.
Tested on the latest 9.0 runbot and working fine.

I'm closing this issue, feels free to comment if you can reproduce your problem.

Best regards

**Closed by csnauwaert** 2018-02-28 10:59 UTC
Labels: 9.0, Accounting
