### ISSUE TITLE
 TypeError: Cannot read property 'removeClass' of undefined

### ISSUE THREAD

**Issue by oetapia** [odoo/odoo#32478] opened 2019-04-07 15:44 UTC
Hi guys! This is my first issue, I'm sorry if it's not well explained. Let me know if there are any questions or information you need. 

Impacted versions: odoo12 
commit: 4ccdddcf6bd67151cfe929df2bd00f96693a58ed

Steps to reproduce: Create new database

Current behavior: Website and UI, especially in backend looks misaligned (padding, margin, font-styles) just as if some CSS were missing. When using debug option a TypeError shows up

Error:
Uncaught TypeError: Cannot read property 'removeClass' of undefined

http://67.209.127.206:8069/web/content/335-4b5d23d/web.assets_common.js:3951
Traceback:
TypeError: Cannot read property 'removeClass' of undefined
    at Class._reposition (http://67.209.127.206:8069/web/content/335-4b5d23d/web.assets_common.js:3951:313)
    at Class.update (http://67.209.127.206:8069/web/content/335-4b5d23d/web.assets_common.js:3950:6)
    at Class._check_for_tooltip (http://67.209.127.206:8069/web/content/335-4b5d23d/web.assets_common.js:3994:152)
    at Class.update (http://67.209.127.206:8069/web/content/335-4b5d23d/web.assets_common.js:3991:213)
    at MutationObserver.<anonymous> (http://67.209.127.206:8069/web/content/335-4b5d23d/web.assets_common.js:4011:669)
    at later (http://67.209.127.206:8069/web/content/335-4b5d23d/web.assets_common.js:46:255)

Expected behavior: to compile correctly

Video/Screenshot link (optional):
https://snag.gy/E2yo5h.jpg

**Comment by pedrobaeza** [comment] 2019-04-08 07:54
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by oetapia** [comment] 2019-04-08 17:00
Hi Pedro, thank you for the prompt reply.
I cannot see the error in the latest odoo in runbot, so I guess it could be something local as you mentioned.

In our case it appears as soon a new database is created. The backend looks a bit wonky as some CSS is missing. Only when running debug mode de we get the error I mentioned before: 
https://snag.gy/HiI2oJ.jpg  

When the issue appears no modules have been installed yet. 

I'm running CentOS7 in a cloudserver that was installed yesterday with updated installers from yum. I will try updating elements again (I've read pip and node.js could cause these type of errors). Or it might be a specific mix of them. If you could give me an idea of where to look it would be helpful.

Thanks once again.

**Comment by pedrobaeza** [comment] 2019-04-08 19:04
Well, I'm afraid there should be a problem in your deployment method, but nothing directly involved with Odoo itself. Please check installation guide and try other method: https://www.odoo.com/documentation/12.0/setup/install.html, or try in forums to get help in this topic.

I'm closing this issue now, but if you feel this can be something reproducible in runbot with other steps, please reply adding all the additional information for reproducing the problem.

**Closed by pedrobaeza** 2019-04-08 19:04 UTC
Labels: Need information

**Comment by volodymyrrudyi** [comment] 2019-05-01 10:12
We've just got the same error on Odoo.sh-hosted Odoo after editing a quote.

**Comment by volodymyrrudyi** [comment] 2019-05-01 10:14
@pedrobaeza  Can it be somehow connected with JS load order? How can I help with further investigating this issue?

**Comment by pedrobaeza** [comment] 2019-05-01 10:44
Well, sometimes JS files are not totally loaded and any interaction can cause this, but I haven't seen it with all fully loaded.

**Comment by evansadji** [comment] 2019-06-11 12:20
I have the same problem,.. 
then i try to install "npm install node-odoo"
it seems worked to me
