### ISSUE TITLE
Error when installing forum module

### ISSUE THREAD

**Issue by pitah81** [odoo/odoo#26703] opened 2018-08-30 21:24 UTC
Impacted versions: 11.0

Steps to reproduce: When trying to install forum application

Current behavior: Failes to install the application

Expected behavior:

Video/Screenshot link (optional):
```
Traceback (most recent call last):
  File "/opt/odoo/sources/odoo/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/sources/odoo/odoo/tools/convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/odoo/sources/odoo/odoo/addons/base/ir/ir_model.py", line 1487, in _update
    record = record.create(values)
  File "/opt/odoo/sources/odoo/addons/gamification/models/goal.py", line 114, in create
    definition = super(GoalDefinition, self).create(vals)
  File "/opt/odoo/sources/odoo/odoo/models.py", line 3372, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/sources/odoo/odoo/models.py", line 3465, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/opt/odoo/sources/odoo/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/sources/odoo/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: insert or update on table "gamification_goal_definition" violates foreign key constraint "gamification_goal_definition_batch_distinctive_field_fkey"
DETAIL:  Key (batch_distinctive_field)=(8357) is not present in table "ir_model_fields".
> During
 handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/odoo/sources/odoo/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/sources/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/sources/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/sources/odoo/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/sources/odoo/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/sources/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/sources/odoo/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/sources/odoo/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/sources/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/sources/odoo/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/sources/odoo/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/sources/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/sources/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-47>", line 2, in button_immediate_install
  File "/opt/odoo/sources/odoo/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/sources/odoo/odoo/addons/base/module/module.py", line 449, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo/sources/odoo/odoo/addons/base/module/module.py", line 542, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/sources/odoo/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/sources/odoo/odoo/modules/loading.py", line 380, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/odoo/sources/odoo/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/sources/odoo/odoo/modules/loading.py", line 181, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/sources/odoo/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/sources/odoo/odoo/tools/convert.py", line 791, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/sources/odoo/odoo/tools/convert.py", line 852, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/sources/odoo/odoo/tools/convert.py", line 741, in parse
    self.parse(rec, mode)
  File "/opt/odoo/sources/odoo/odoo/tools/convert.py", line 751, in parse
    exc_info[2]
  File "/opt/odoo/sources/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/odoo/sources/odoo/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/sources/odoo/odoo/tools/convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/odoo/sources/odoo/odoo/addons/base/ir/ir_model.py", line 1487, in _update
    record = record.create(values)
  File "/opt/odoo/sources/odoo/addons/gamification/models/goal.py", line 114, in create
    definition = super(GoalDefinition, self).create(vals)
  File "/opt/odoo/sources/odoo/odoo/models.py", line 3372, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/sources/odoo/odoo/models.py", line 3465, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/opt/odoo/sources/odoo/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/sources/odoo/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
odoo.tools.convert.ParseError: "insert or update on table "gamification_goal_definition" violates foreign key constraint "gamification_goal_definition_batch_distinctive_field_fkey"
DETAIL:  Key (batch_distinctive_field)=(8357) is not present in table "ir_model_fields".
" while parsing /opt/odoo/sources/odoo/addons/website_forum/data/badges_moderation.xml:20, near
<record model="gamification.goal.definition" id="definition_critic">
            <field name="name">Critic</field>
            <field name="description">First downvote</field>
            <field name="computation_mode">count</field>
            <field name="display_mode">boolean</field>
            <field name="model_id" eval="ref('website_forum.model_forum_post_vote')"/>
            <field name="condition">higher</field>
            <field name="domain">[('vote', '=', '-1')]</field>
            <field name="batch_mode">True</field>
            <field name="batch_distinctive_field" eval="ref('website_forum.field_forum_post_vote_user_id')"/>
            <field name="batch_user_expression">user.id</field>
        </record>
```

**Comment by pedrobaeza** [comment] 2018-08-31 06:04
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-08-31 06:04 UTC
