### ISSUE TITLE
Deletion of  a record referenced by a transient record raise an error

### ISSUE THREAD

**Issue by frln** [odoo/odoo#30298] opened 2019-01-17 09:34 UTC
Impacted versions:11

Steps to reproduce: Use a transient model (wizard) that has a many2one relation field with a normal model. In my case I used a custom wizard ,which i put the implementation below, linked to a project.task model.

Current behavior: If I try to delete the related model, I see a validation error because the model id is referenced by the transient model. Until the automatic vacuum purge the transient models from the database the deletion doesn't work.

Expected behavior: The many2one should be set to null in the transient model? That would allow the deletion of the model without problem. I suppose the system already does that for regular models because it's possible to delete a record referenced by another model.

```
  class wizard_employee_intervention(models.TransientModel):
    """ Transient model being used in the addition of an employee to an intervention"""
    _name = 'allmaids_extension.wizard_employee_intervention' 

    def _default_intervention(self):
        active_id = self._context.get('active_id', False)
        if not active_id:
            active_id=0
        return self.env['project.task'].browse(active_id)    

    def _default_start_day(self):
        active_id = self._context.get('active_id', False)
        if not active_id:
            active_id=0
        intervention = self.env['project.task'].browse(active_id)
        if intervention.date_start:
            return fields.Datetime.to_string(datetime.combine(fields.Datetime.from_string(intervention.date_start).date(),time(0)))

    def _default_stop_day(self):
        active_id = self._context.get('active_id', False)
        if not active_id:
            active_id=0
        intervention = self.env['project.task'].browse(active_id)
        if intervention.date_end:
            return fields.Datetime.to_string(datetime.combine(fields.Datetime.from_string(intervention.date_start).date(),time(20)))
        
    employee_id = fields.Many2one('hr.employee', string="Employé à ajouter à l'intervention", required=True)
    task_id = fields.Many2one('project.task', required=True, default=_default_intervention)
    start_day = fields.Datetime(string="Jour de début des interventions", default=_default_start_day)
    stop_day = fields.Datetime(string="Jour de fin des interventions", default=_default_stop_day) 

```

**Comment by pedrobaeza** [comment] 2019-01-17 09:38
Hi @frln this is because the transient model needs the ondelete="cascade" option in the declared many2one fields.

If you detect any Odoo transient model without this, then the issue is to put that argument to the field and you can report/propose a fix for these individual cases. If it's in your code, then you should add it.

Closing then according comments.

**Closed by pedrobaeza** 2019-01-17 09:38 UTC
