### ISSUE TITLE
Uncaught TypeError: Cannot read property 'action' of undefined

### ISSUE THREAD

**Issue by vivekbics** [odoo/odoo#2831] opened 2014-10-01 11:58 UTC
I received this issue in Odoo 7. What could have caused this issue?

**Comment by Yenthe666** [comment] 2016-06-03 09:54
Hi @vivekbics,

This issue can have a lot of reasons. The reason is because of a missing action in a part of the code.
Odoo issues should have a clear step-by-step proces to follow.
Since I have no way to reproduce this issue I'm closing it.

Regards,
Yenthe

**Closed by Yenthe666** 2016-06-03 09:54 UTC
