### ISSUE TITLE
[12.0/Master] RFC/Feature Request: Improved Organisation/Navigation For Snippets Editor & Customize Theme Features

### ISSUE THREAD

**Issue by lukebranch** [odoo/odoo#25395] opened 2018-06-21 12:50 UTC
<h1>Impacted versions:</h1>
Master
<h1>Explanation</h1>
I want to propose this as an RFC. I believe the current features in the core are great, but have room for improvement in terms of UX.
<h1>Steps to reproduce:</h1>
Open website in editor mode.
<h1>Current Behaviour:</h1>
<ul>
<li>Large numbers of custom snippets and snippet sections/categories are cumbersome to scroll through, and difficult to navigate. If we have a theme with hundreds of snippets and a large number of different sections, the current default snippet sidebar is not ideal.</li>
<li>Customise Theme widget is not particularly intuitive in terms of it's location.</li>
<li>Form Editor is not particularly intuitive. I believe an Odoo Studio style layout would be better.</li>
</ul>
<h1>Expected Behaviour:</h1>
<ul>
<li>Create an all-in-one sidebar for snippets, form editor, customise theme, code editor (for those with access) and other website editor features. This could work like a tabbed megamenu layout. The first level of tabs for Snippets, Form Editor, Customize Theme, etc. could then expand into sub-sections under these main tabs. Sub-sections could contain their own tabbed layout to allow for easier navigation through a large number of options.</li>
<li>Snippets should be their own sidebar tab. Snippets Categories should be grouped under sub-section tabs to allow for more efficient navigation with a large number of categories and snippets.</li>
<li>Form Editor Snippet should be merged into it's own sidebar tab, to allow for more of an Odoo Studio style layout.</li>
<li>Customize Theme widget should be merged into the sidebar containing sub-sections for different theme options </li>
</ul>
<h1>Video/Screenshot link (optional):</h1>
This is a good example of what i'm referring to in terms of tabbed sections for snippets and other website editor features that could be merged into a single menu.
<br/>
<a href="http://www.youtube.com/watch?feature=player_embedded&v=XYGDDM_mYE0" target="_blank"><img src="http://img.youtube.com/vi/XYGDDM_mYE0/0.jpg" 
alt="Example Nav For Website Editor" width="640" height="480" border="10" /></a>

**Comment by pedrobaeza** [comment] 2018-06-21 16:28
@JKE-be what do you think about this?

**Comment by lukebranch** [comment] 2018-10-17 16:02
In addition to what i've mentioned above it would also be great to have page/context-aware snippets functionality.

What I mean by this is the ability to restrict specific snippets to be useable on specific pages. Certain snippets could be globally available on all pages (eg. layout blocks/snippets), however some functional snippets might have a specific use-case only usable on a specific page.

For example, on a product page, on the e-commerce there might be a use-case for a snippet that includes some logic/functionality that might be applicable only to a product. Therefore you (as the theme developer) could restrict its use to a handful of hardcoded pages (eg. product view page) where that makes sense, but for example, you would not see that snippet when editing the home page or contact page.

**Comment by rdeodoo** [comment] 2022-07-29 21:12
Thanks a lot for the proposal and sorry we didn't reply before.

@pierre-pde Reading
> Large numbers of custom snippets and snippet sections/categories are cumbersome to scroll through, and difficult to navigate.

I thought it was about our custom snippet but in 2018 that feature didn't exists. But this is actually making a point when you consider the custom snippets (that one can save).
I saw someone using Odoo.com and they had like 50 saved custom snippet, it is quite an UX killer as one always has to scroll down a lot to actually see the real snippets.
I am not sure if something has to be done as this is mainly coming from the fact that those custom snippets are shared by everyone, thus of course on odoo.com the problem is amplified.
cc @pierre-pde I'll you judge functionally if that's something that need to be worked on.

Anyway, since v12/2018 lot of stuff changed and the UI got really improved, I don't think there is anything here that are still up to date and we want at the moment, I'll close this one.

Feel free to open a new one for the current version and I promise we will read and reply this time :wink:  :grimacing: 
(Or let me know if you want to update it with the current version and want me to reopen it)

**Closed by rdeodoo** 2022-07-29 21:12 UTC
Labels: Wishlist, Website

**Comment by pierre-pde** [comment] 2022-08-01 08:20
Thanks for the feedback.
Users with tons of custom snippet can use the search functionality.
