### ISSUE TITLE
[12] active_id is not correct after preforming more than 1 action

### ISSUE THREAD

**Issue by auyeung112002** [odoo/odoo#28826] opened 2018-11-20 10:10 UTC
Impacted versions:
12

Steps to reproduce:
1. Setup an odoo server
2. Install CRM, Sales, Contact, install a chart of account template
3. Add context {'test_id':active_id} to the cancel button of sale order form
4. See the video for detail, https://youtu.be/5aNzLLFrWsk
5. Administrator id is 3, while the newly created sale order id is 2
6. When clicking the cancel(with active_id set in context), the active_id is 3(which is wrong)

Current behavior:
active_id is the active_id of the first view
This issue will affect button with type=action and type=object, resulting in pointing to wrong record or cause referential integrity error

Expected behavior:
active_id is the active id of the current view

**Comment by pedrobaeza** [comment] 2018-12-07 17:16
@auyeung112002 It's strange what you are referring, as I haven't experimented this using active_id in smart-buttons. Can you please do 2 things:

* Try again in latest code.
* If still reproducible, please attach a mini-module showcasing the problem.

**Comment by auyeung112002** [comment] 2018-12-14 02:20
Test with the latest code, dated on 2018-12-14, the problem still exist. The active_id is wrong and the active_model is also wrong.

I think there is no need to make a module for this issue, since you can simply add a breakpoint to sales.order.action_cancel(sale.py line 587) or add the below code to action_cancel if you can't use breakpoint:

```python
def action_cancel:
    if self.id != self.env.context['active_id']:
        raise UserError('Document ID is %s but the active_id is %s' %(self.id, self.env.context['active_id']))
```

**Comment by auyeung112002** [comment] 2018-12-17 06:36
I have made another video(https://youtu.be/msdpNyXPvmk) for showcasing the issue. As you can see in the video, the active_id always refers to the id of the first opened document. However, developer is unable to ensure the active_id refers to the "active" document, especially the act_window shown in the below picture.
![image](https://user-images.githubusercontent.com/8391358/50070434-e1a21300-0208-11e9-9212-6db3d2513ea5.png)

**Comment by pedrobaeza** [comment] 2018-12-20 16:58
Hi, @auyeung112002 thanks for the video, but when I try to replicate the problem is not present in smart-buttons, which is where you can have problems. For buttons, you have `self` variable for accessing affected records:

![peek 20-12-2018 17-52](https://user-images.githubusercontent.com/7165771/50298712-123fb200-0480-11e9-95df-4039a054d2ec.gif)

I'm closing this now due to the stated above. If you find a real problem with this, please comment.

**Closed by pedrobaeza** 2018-12-20 16:58 UTC
Labels: 12.0, Framework, Need information

**Comment by auyeung112002** [comment] 2019-01-04 09:01
Developers have to use self.id in model or "id" in button context in view definition. A尸, For buttons, you have self variable for accessing affected records.

The safer way is to change to use id instead of active_id in view context. But this bug actually make the active_id usage unreliable. This behavior should be documented if it is not fixed. active_id is only reliable at the first level.

The smart button you tested doesn't use active_id. So it is not affected.
You can see the active_id is still wrong if I follow your first few steps.
![active_id](https://user-images.githubusercontent.com/8391358/50680222-dc82f780-1041-11e9-86ee-26ecff35ea47.gif)

Later active_id is corrected by return value of method "open_reconcile_view"
Please consider reopen it.

**Comment by pedrobaeza** [comment] 2019-01-04 09:05
Sorry but no, you have to use the system properly. On buttons, simply don't use `active_id`, but `self`.

**Comment by auyeung112002** [comment] 2019-01-04 10:41
I guess you are saying always use self. id instead of self.env.context['active_id']
Totally agree.

How about <button name="xxx" type="action" context="{'yyy' :active_id}" />
Is it proper usage of active_id? Odoo often uses active_id like this in official module? 

If yes, then the active_id is only reliable at the first level

**Comment by pedrobaeza** [comment] 2019-01-04 10:43
When used in smart-button, the value is correct. If you find an official usage of active_id that is incorrect, then please report it and it will be fixed.
