### ISSUE TITLE
[12.0] "Group By" dropdown no longer allows mouse selection in Chrome

### ISSUE THREAD

**Issue by TTPBruce** [odoo/odoo#66848] opened 2021-02-25 13:33 UTC
Impacted versions: Odoo 12 latest runbot using Chrome

Steps to reproduce: In Google Chrome, open a list/tree view (eg. sales), click on "Group By", then "Add Custom Group" then click an item from the list.

Current behavior: The list disappears and the dropdown selection is reset.

Expected behavior: The selected item from the list is displayed along with further options for grouping.

This has been reported by multiple users on different computers running Chrome. No issues with other browsers yet.

This started happening this week on our instance which is not running an updated version of Odoo, but also occurs on latest runbot, so the issue is likely related to a Chrome patch that breaks the Odoo dropdown functionality.

**Comment by pedrobaeza** [comment] 2021-02-25 20:59
@chienandalu is this the same that we were reported?

**Comment by chienandalu** [comment] 2021-02-26 08:29
Looks like it, although I couldn't reproduce it locally (Chrome + Linux)

**Comment by pedrobaeza** [comment] 2021-02-26 08:42
@TTPBruce can you tell us which Chrome version and OS?

**Comment by TTPBruce** [comment] 2021-02-26 13:24
Chrome Version 88.0.4324.182 (Official Build) (64-bit)

Windows 10, version 2004

**Comment by sebastienpongi** [comment] 2021-03-11 15:59
@TTPBruce 

I found your issue yesterday after one of my customers reported me a similar problem.

Behaviour is the same when Grouping data and using customer searches too with Chrome (Windows) and Odoo 12. (3 users out of 240 reported the issue). It occured on both their Odoo instance and the V12 Odoo runbot. 

I was unable to reproduce on my side (Windows + same version of Chrome), neither using the laptops of two other users (same windows et chrome version). 

We solved the problem this morning by :
- Uninstalling Chrome
- Deleting the user profile folder
- Install Chrome again

Everything is back to normal now. 
Unfortunatly we don't know what caused the problem but if it could help

**Comment by jtempletmg** [comment] 2021-03-16 14:37
Just confirming that I too am having this issue.  Odoo Version 12 and Chrome version 89.0.4389.90.  To add to the issue, this also happens to me when adding a custom filter.  As soon as I select the field to filter the drop down disappears.

**Comment by l-schmitt** [comment] 2021-03-30 10:58
Hello, same problem here, with same Google Chrome versions on different computers.., we have checked the diffs beetween v12 and v13 in the js filters_menu and we found a working solution : 

The js functions triggered on the events are called like this scheme :

```
    events: _.extend({}, DropdownMenu.prototype.events, {
        'click .o_add_custom_filter': '_onAddCustomFilterClick',
[..]
    }),
```
```
    _onAddCustomFilterClick: function (event) {
        event.preventDefault();
        event.stopPropagation();
        this._toggleCustomFilterMenu();
    },
```

But on the function '_appendProposition' there is no "container function" to call stopPropagation() (which was rewrite like this later in v13)

So the fix for filter_menu and groupby_menu in v12 : 

```diff
--- a/addons/web/static/src/js/views/search/filters_menu.js
+++ b/addons/web/static/src/js/views/search/filters_menu.js
@@ -100,7 +100,11 @@ var FiltersMenu = DropdownMenu.extend({
         var prop = new search_filters.ExtendedSearchProposition(this, this.fields);
         this.propositions.push(prop);
         this.$('.o_apply_filter').prop('disabled', false);
-        return prop.insertBefore(this.$addFilterMenu);
+        prop.insertBefore(this.$addFilterMenu);
+
+        return $(".dropdown-menu .dropdown-item-text select").click(function(e){
+            e.stopPropagation();
+        });
     },
     /**
      * Confirm a filter selection, creates it and add it to the menu
@@ -207,6 +211,10 @@ var FiltersMenu = DropdownMenu.extend({
             // https://getbootstrap.com/docs/4.0/components/dropdowns/#methods
             self.$dropdownReference.dropdown('update');
         });
+
+        $(".dropdown-menu .dropdown-item-text select").click(function(e){
+            e.stopPropagation();
+        });
     },

     //--------------------------------------------------------------------------
```

```diff 
--- a/addons/web/static/src/js/views/search/groupby_menu.js
+++ b/addons/web/static/src/js/views/search/groupby_menu.js
@@ -170,6 +170,10 @@ var GroupByMenu = DropdownMenu.extend({
         this.$menu.append($generatorMenu);
         this.$addCustomGroup = this.$menu.find('.o_add_custom_group');
         this.$groupSelector = this.$menu.find('.o_group_selector');
+        $(".dropdown-menu .dropdown-item-text select").click(function(e){
+            e.stopPropagation();
+        });
     },
     /**
      * @private
````

**Comment by inspiredbusiness** [comment] 2021-04-12 05:15
This affects us and our customers. It is spreading to more computers and clients

**Comment by inspiredbusiness** [comment] 2021-04-12 10:42
OPW #2504399

**Comment by celm1990** [comment] 2021-04-12 18:28
I tested on rumbot
SO: windows and linux
Chorme: 88 y 89

Windows, Chorme 89
https://user-images.githubusercontent.com/7775116/114442739-7ecfa500-9b92-11eb-8f54-d70083c1b23d.mp4

Ubuntu, Chorme 88

https://user-images.githubusercontent.com/7775116/114443129-eede2b00-9b92-11eb-98ba-a4a7af6f50c7.mp4

**Comment by inspiredbusiness** [comment] 2021-04-13 02:25
We have heard from our Odoo Account managers that this is been worked on and there are several tickets lodged under enterprise contracts including ours. Hopefully a fix is merged into the Odoo soon.

Thanks ursais for the merge above we can look at using for now.

**Comment by TTPBruce** [comment] 2021-04-13 13:10
@l-schmitt Fix worked great for us, thanks!

**Comment by celm1990** [comment] 2021-04-14 19:36
FIxed on https://github.com/odoo/odoo/pull/69274

**Closed** 2021-04-15 15:19 UTC

**Comment by jeroen7s** [comment] 2021-04-20 08:36
I'm having the same issue on Odoo11, is there any fix for that (we're migrating to Odoo14 but a fix in the meantime would be nice)

**Comment by matteoopenf** [comment] 2021-08-03 16:27
> I'm having the same issue on Odoo11, is there any fix for that (we're migrating to Odoo14 but a fix in the meantime would be nice)
> 
> EDIT: just saw the last commit in Odoo11 has a fix for this, great!

I don't understand is merged for 11.0 https://github.com/odoo/odoo/pull/69304?

**Comment by matteoopenf** [comment] 2021-08-03 16:35
> > I'm having the same issue on Odoo11, is there any fix for that (we're migrating to Odoo14 but a fix in the meantime would be nice)
> > EDIT: just saw the last commit in Odoo11 has a fix for this, great!
> 
> I don't understand is merged for 11.0 #69304?

is merged 
![image](https://user-images.githubusercontent.com/43987335/128052901-0e803259-aa9f-4c8b-87fe-7780298d6404.png)

**Comment by matteoopenf** [comment] 2021-09-01 08:17
The fix is not available there http://nightly.odoo.com/11.0/nightly/src/ any one can do something?

**Comment by matteoopenf** [comment] 2021-09-01 08:25
I open an Issue https://github.com/odoo/odoo/issues/75818
