### ISSUE TITLE
[10.0] Currency Rate- bad convertion

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#15071] opened 2017-01-13 22:32 UTC
Impacted versions:
10.0
Steps to reproduce:

1.  Allow multi currencies from Account configuration
2. Active MXN Currency
3. Configure MXN Currency to main company
4. Update the currencies from account configuration
5. Select `European Central Bank` and click update now button
6. Create an invoice with usd currency, add one invoice line with unit price of $1
7. Save and Validate the invoice

Current behavior:
USD
![image](https://cloud.githubusercontent.com/assets/10233975/21948935/ea1be7f6-d9b3-11e6-90ac-5ef3449a4c21.png)

MXN (current used by company)
![image](https://cloud.githubusercontent.com/assets/10233975/21948981/3c392788-d9b4-11e6-9b8c-7ab95a79344a.png)

The Journal Entry shows a bad convertion
IF  $1mxn is $0.046180 usd
![image](https://cloud.githubusercontent.com/assets/10233975/21947930/7b4f0f20-d9ad-11e6-83a4-ae4b355178c3.png)

Then the convertion is wrong
![image](https://cloud.githubusercontent.com/assets/10233975/21947902/48a6e3c2-d9ad-11e6-8721-15fab2eda16a.png)
Expected behavior:
Journal Entry show the correct convertion
The correct value must be $21.654395842 mxn

Video/Screenshot link (optional):
(sorry for my bad inglish)
https://drive.google.com/file/d/0B_jQX2tloXM7MWQ2eTNkd21kTUE/view

**Comment by hugho-ad** [comment] 2017-01-13 22:33
@qdp-odoo can you give us your point of view please
Regards

**Comment by TheCloneMaster** [comment] 2017-01-13 23:00
What are the exchange rates registered for previous date in each currency?
In previous versions, as exchange rates had timestamps, the time zone made
odoo to select previous day's rate...
Regards,
Mario

**Comment by hugho-ad** [comment] 2017-01-13 23:21
@TheCloneMaster 

USD
![image](https://cloud.githubusercontent.com/assets/10233975/21948935/ea1be7f6-d9b3-11e6-90ac-5ef3449a4c21.png)

MXN (current used by company)
![image](https://cloud.githubusercontent.com/assets/10233975/21948981/3c392788-d9b4-11e6-9b8c-7ab95a79344a.png)

**Comment by suniagajose** [comment] 2017-01-13 23:51
@TheCloneMaster @hugho-ad 

The problem is that `date_invoice` is just a `date` field, and currency.rate date is `datetime`.

Suppose the following example,
- early morning was update the rates at 05:00:00 (hh:mm:ss)
- after that at 07:00:00 (hh:mm:ss) i created a customer invoice with `today()` as date.
- when validate the invoice, is execute the [following query](https://github.com/odoo/odoo/blob/10.0/odoo/addons/base/res/res_currency.py#L42) to get the rate.
- That query will return me the last exchange rates less than equal to (<=) `today()`, leaving out the rate that updates early in the morning.

Current query:
```sql
SELECT c.id, (SELECT r.rate FROM res_currency_rate r
WHERE r.currency_id = c.id AND r.name <= '2017-01-13'
AND (r.company_id IS NULL OR r.company_id = 1) 
ORDER BY r.company_id, r.name DESC          
LIMIT 1) AS rate 
FROM res_currency c  
WHERE c.id IN (3); 
```

Expected query:
```sql
SELECT c.id, (SELECT r.rate FROM res_currency_rate r
WHERE r.currency_id = c.id AND r.name <= '2017-01-13 07:00:00'
AND (r.company_id IS NULL OR r.company_id = 1) 
ORDER BY r.company_id, r.name DESC          
LIMIT 1) AS rate 
FROM res_currency c  
WHERE c.id IN (3); 
```

**Comment by TheCloneMaster** [comment] 2017-01-14 01:31
Exactly!  Set the exchange rates for previos dates to the same you are
using for the invoice date, cancel the invoice and validate again and you
will see the right result...  but for the wrong reason....

As a quick fix, we use a small module that makes the exchange rates ' date
only,  no time portion...

Regards,
Mario

El 13 ene. 2017 5:51 PM, "Jose Suniaga [Vauxoo]" <notifications@github.com>
escribió:

@TheCloneMaster <https://github.com/TheCloneMaster> @hugho-ad
<https://github.com/hugho-ad>

The problem is that date_invoice is just a date field, and currency.rate
date is datetime.

Suppose the following example,

   - early morning was update the rates at 05:00:00 (hh:mm:ss)
   - after that at 07:00:00 (hh:mm:ss) i created a customer invoice with
   today() as date.
   - when validate the invoice, is execute the following query
   <https://github.com/odoo/odoo/blob/10.0/odoo/addons/base/res/res_currency.py#L42>
   to get the rate.
   - That query will return me the last exchange rates less than equal to
   (<=) today(), leaving out the rate that updates early in the morning.

Current query:

SELECT c.id, (SELECT r.rate FROM res_currency_rate rWHERE
r.currency_id = c.id AND r.name <= '2017-01-13 <2017%200113>'AND
(r.company_id IS NULL OR r.company_id = 1) ORDER BY r.company_id,
r.name DESC          LIMIT 1) AS rate FROM res_currency c  WHERE c.id
IN (3);

Expected query:

SELECT c.id, (SELECT r.rate FROM res_currency_rate rWHERE
r.currency_id = c.id AND r.name <= '2017-01-13 07:00:00'AND
(r.company_id IS NULL OR r.company_id = 1) ORDER BY r.company_id,
r.name DESC          LIMIT 1) AS rate FROM res_currency c  WHERE c.id
IN (3);

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/odoo/odoo/issues/15071#issuecomment-272578976>, or mute
the thread

**Comment by nhomar** [comment] 2017-01-15 03:51
The correct solution should be that the invoice should be also datetime instead date, if comparision is datetime all is ok...

But yes, both need to be the same to properlly manage the case.

**Comment by qdp-odoo** [comment] 2017-01-16 16:11
Ok, as @suniagajose described, the problem comes from the fact we use a date field on invoices and a datetime field on res.currency.rate. (Actually, men may find some other approximations made in the same fashion, like on invoices analysis report for example, which tend to say that currently it's not supported to have several rates for a single day)

We don't want to use a datetime on invoices, as this field has to stay timezone independent. So the right thing to do are
* change to use a date field on currency rate.
* add a constraint to avoid several rates on the same day.
That's something we will do on master (will be in saas-15) as it implies a migration and a database scheme change.

In the meanwhile, in current stable versions, the system is using the rate at 00:00 (so most likely the yesterday rate -except if the rate was created at midnight which is the default for manual input-). This is the intended behavior, even if the design is a little dubious, so you'll understand I cannot confirm the issue as a bug.

**Closed by qdp-odoo** 2017-01-16 16:11 UTC

**Comment by nhomar** [comment] 2017-01-16 18:44
On Mon, Jan 16, 2017 at 10:11 AM, qdp-odoo <notifications@github.com> wrote:

> Ok, as @suniagajose <https://github.com/suniagajose> described, the
> problem comes from the fact we use a date field on invoices and a datetime
> field on res.currency.rate. (Actually, men may find some other
> approximations made in the same fashion, like on invoices analysis report
> for example, which tend to say that currently it's not supported to have
> several rates for a single day)
>
> We don't want to use a datetime on invoices, as this field has to stay
> timezone independent.
>
Can you enlight us why you do not want do this?.

- We used datetime sine 5 years on invoices (mandatory in MX) and that will
be one proposal for saas-15, we can add an extra field datetime as we did
some time ago here:
https://github.com/Vauxoo/addons-vauxoo/tree/8.0/invoice_datetime

- The point is that the rate is 1 of the problems that requires this field
being datetime (electronic invoices is controlled with datetime precision),
POS transactions need that also for closing process (another topic but
related).

- IMHO Invoices are datetime in the timezone of the company which taxes
will be declared in that way you will solve at least 10 localization
problems, VE,MX, CR, PE, AR, etc, etc, and it fit legally I think in 90% of
cases for invoice.

Rethink this topic is better... (may be 2 dates on invoices?)

Coming back to rate issue, In Costa Rica rate is per transaction even, we
need to save the rate used in an specific invoice/document, in Accounting
it is indirectly coputed (which is worng also due to the mathematical
precision you know also.

Please do not return rate to date, I prefer follow "for now" the convetion
you just mentioned instead fight in the future for the datetime to comeback
until we find a middle point here, I know you are working hard on this
topic.

> So the right thing to do are
>
>    - change to use a date field on currency rate.
>    - add a constraint to avoid several rates on the same day.
>    That's something we will do on master (will be in saas-15) as it
>    implies a migration and a database scheme change.
>
> In the meanwhile, in current stable versions, the system is using the rate
> at 00:00 (so most likely the yesterday rate -except if the rate was
> created at midnight which is the default for manual input-). This is the
> intended behavior, even if the design is a little dubious, so you'll
> understand I cannot confirm the issue as a bug.
>



Nhomar Hernandez
CEO Vauxoo.
Site: http://vauxoo.com
Twitter: @nhomar
Blog: http://nhomar.com
Github User: https://github.com/nhomar
Odoo Gold Partner
Skype: nhomar00 (Envia mail previo no lo superviso siempre).
HangOut: nhomar@vauxoo.com
Móvil Venezuela:
+58 4144110269
Móvil México:
+52 1 4773933942

**Comment by qdp-odoo** [comment] 2017-02-14 10:46
Oops, forgot to answer here:
>     We don't want to use a datetime on invoices, as this field has to stay
>     timezone independent.
> Can you enlight us why you do not want do this?.
Because datetime means nothing without a timezone. If I'm in a multi-timezone environment I might face strange use cases where an invoice is made in company A timezone at D day and is shown in company B at day D-1.
And that's definitively not what we want.

FYI: we have branches currently being tested at 
https://github.com/odoo/odoo/pull/15122
https://github.com/odoo/enterprise/pull/706

**Comment by gustavovalverde** [comment] 2017-06-24 15:05
I've been experiencing this, as every validated invoice is using yesterday's rate instead of today's rate.

The fix for current stable seems easy, just as @suniagajose exposed, changing the query to:

```
SELECT c.id, (SELECT r.rate FROM res_currency_rate r
WHERE r.currency_id = c.id AND r.name <= '2017-01-13 07:00:00'
AND (r.company_id IS NULL OR r.company_id = 1) 
ORDER BY r.company_id, r.name DESC          
LIMIT 1) AS rate 
FROM res_currency c  
WHERE c.id IN (3);
``` 
@qdp-odoo, you stated:
> In the meanwhile, in current stable versions, the system is using the rate at 00:00 (so most likely the yesterday rate -except if the rate was created at midnight which is the default for manual input-)

But this is not happening, when creating a new rate 00:00:00 is not the default:
![image](https://user-images.githubusercontent.com/16890942/27509494-392358d8-58cc-11e7-830d-1c2d130cece7.png)
This is using runbot just now.

Currently, users have to input **today's rate with yesterday's date**. Apart from being a wrong approach, it also raises and Audit problem for companies; and we could save ourselves the explanation to the Auditor of why every single rate has the wrong rate.

**Comment by gustavovalverde** [comment] 2017-07-05 14:16
@Yenthe666, should I create a new issue with my last statement?

**Comment by XeJames** [comment] 2017-10-10 18:04
I am not certain that this is the "same" problem, but it certainly indicates a possible solution...

Problem:
1. AWS and other online companies charges their OWN magical (about 1% too high) exchange rate if they do the exchange for you.  
2. Every bank charges you a DIFFERENT "exchange rate" on multi-currency banking transactions - it is actually a hidden fee that is never itemized.  
3. Banks publish multiple rates throughout the day (at least twice daily) so that single rate will likely be wrong anyhow.

Would it not be simpler - when paying a bill or receiving a customer payment - to just enter both the currency amount as well as the actual value received and then infer the exchange rate from that?  Maybe raise a flag if it differs from the "official" rate by 1% or 2%?

Today's example, Amazon charged me CAD11.75 for a USD9.00 bill.  Today's exchange rate says it should be CAD11.68 so I end up with CAD0.11 remaining when I reconcile the CAD VISA statement.  Accounting for that phantom 1% is going to raise audit flags no matter how you handle it.
