### ISSUE TITLE
[9.0] Traceback If trying to create BOM in MRP with special character

### ISSUE THREAD

**Issue by dipesh-suthar-flectra** [odoo/odoo#9761] opened 2015-11-26 12:01 UTC
- In 9.0
- Go to the Manufacture, Create one MO and try to create BOM with special character and it will give you warning and then it throws traceback.
- See here: https://goo.gl/fea8aC

**Comment by andreparames** [comment] 2015-11-28 16:45
It doesn't seem to be a problem with the special characters, I can reproduce the problem even with ASCII characters.

It seems it's trying to evaluate the domain of the `bom_id` field, but in doing so it gets the value of that field, which is `undefined`, and which blows up `wrap_context()`, since that function only checks for `null`.

**Comment by Yenthe666** [comment] 2016-05-23 13:24
Hi @dsu-odoo and @andreparames,

I've just tested this and this issue is still present in the latest Odoo 9.0. 
@mart-e can you assign this issue to somebody please? You can even reproduce this by just filling in 'test' as a bill of material:
![image](https://cloud.githubusercontent.com/assets/6352350/15472231/4d42dcd6-20fa-11e6-99d6-8370696185cf.png)

On a sidenote: there might be another issue too.
Create a new MO, fill in some details and then click on discard. When you now do this again you will see the numbering of the MO is incremented, even when the previous MO is not created / saved.
Perhaps this is something we should fix too?

Regards,
Yenthe

**Comment by pedrobaeza** [comment] 2018-04-10 23:03
@adr-odoo is this still happening?

**Comment by Yenthe666** [comment] 2018-04-12 07:55
Hey,

I just tried this again and in the meanwhile it seems to be fixed and working.
Don't hesitate to respond back if I missed something or if you can still reproduce it on the latest 9.0.

Regards,
Yenthe

**Closed by Yenthe666** 2018-04-12 07:55 UTC
Labels: Confirmed

**Comment by adr-odoo** [comment] 2018-04-12 09:32
It's fixed now.
See: https://github.com/odoo/odoo/commit/8c0b23c23925ecadeb753ed93919dbe2cbea4370
