### ISSUE TITLE
[11.0] ir_mail_server: UnicodeEncodeError for user.name with special chars

### ISSUE THREAD

**Issue by moylop260** [odoo/odoo#23502] opened 2018-03-06 19:10 UTC
Impacted versions:
11.0 (I don't know if older ones too)

Steps to reproduce:
1. Create a user with `name` using special char like as `Moisés López [Vauxoo]`
2. Create an invoice and use `send email` button

Current behavior:

 - The email is not sent
<img width="364" alt="screen shot 2018-03-06 at 13 07 29" src="https://user-images.githubusercontent.com/6644187/37052590-58edebba-213f-11e8-845c-e5a87edd8024.png">

The traceback is:
```bash
2018-03-06 19:03:03,608 1355 ERROR vauxoo110 odoo.addons.mail.models.mail_mail: failed sending mail (id: 21273) due to ascii Moisés ordinal not in range(128)
Traceback (most recent call last):
  File "addons/mail/models/mail_mail.py", line 323, in _send
    headers=headers)
  File "odoo/addons/base/ir/ir_mail_server.py", line 308, in build_email
    msg['From'] = encode_rfc2822_address_header(email_from)
  File "odoo/addons/base/ir/ir_mail_server.py", line 123, in encode_rfc2822_address_header
    return COMMASPACE.join(encode_addr(a) for a in addresses)
  File "odoo/addons/base/ir/ir_mail_server.py", line 123, in <genexpr>
    return COMMASPACE.join(encode_addr(a) for a in addresses)
  File "odoo/addons/base/ir/ir_mail_server.py", line 120, in encode_addr
    return formataddr((name, email))
  File "/usr/lib/python3.5/email/utils.py", line 91, in formataddr
    address.encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 4: ordinal not in range(128)
```

Expected behavior:
 - Email sent

<s>
You can reproduce this error using the following line of code:
`PYTHONPATH=~/odoo python3.5 -c "from odoo.addons.base.ir.ir_mail_server import encode_rfc2822_address_header as ench;ench('Moisés')"`

traceback
```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/odoo/addons/base/ir/ir_mail_server.py", line 123, in encode_rfc2822_address_header
    return COMMASPACE.join(encode_addr(a) for a in addresses)
  File "/odoo/addons/base/ir/ir_mail_server.py", line 123, in <genexpr>
    return COMMASPACE.join(encode_addr(a) for a in addresses)
  File "/odoo/addons/base/ir/ir_mail_server.py", line 120, in encode_addr
    return formataddr((name, email))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/email/utils.py", line 91, in formataddr
    address.encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 4: ordinal not in range(128)
```
</s>  odoo guys are confused because this comment, better deleting...

**Comment by Elkasitu** [comment] 2018-03-07 07:46
Hi, you'll need to be more specific with your reproduction steps and the bug has to be reproducible from the UI.

`encode_rfc2822_address_header('Mosiés')` won't work, please read the docstring of the method to find out why.

**Comment by Elkasitu** [comment] 2018-03-08 10:26
Closed in favor of #23527 as it contains more detail

**Comment by moylop260** [comment] 2018-03-08 13:18
@elkasitu Did you see the “Steps to reproduce“?

Create a new user with special char, create a invoice and send email...

You just review the last complement part of the issue

**Comment by Elkasitu** [comment] 2018-03-09 07:31
@moylop260 If you create a new user with special chars in the name everything works perfectly, since `encode_rfc2822_address_header` *does not* convert the name to ASCII.

The error comes from having an email address with non-ASCII characters, so if your email address is `moiséslopéz@whatévèr.com`, then the system will try to convert it to ASCII and fail, therefore your message won't be sent.

This means that your steps to reproduce don't actually trigger any error, and are in fact wrong, the issue is not with the name but with the e-mail address, which is being discussed in issue #23527

**Comment by moylop260** [comment] 2018-03-09 15:09
@Elkasitu Actually I don't have an email address with special chars, really I have a user name (just name) with special chars, see image above:

 - <img width="566" alt="screen shot 2018-03-09 at 09 06 51" src="https://user-images.githubusercontent.com/6644187/37214000-43bb7d02-2379-11e8-945b-2333ff224c2a.png">

Like as I told you from my main description

**Comment by moylop260** [comment] 2018-03-09 15:42
Let me update the source code in order to verify if It was fixed before...

**Comment by hugho-ad** [comment] 2018-03-09 23:11
@Elkasitu 
Please reopen this issue
Already replicated in 
http://runbot13.odoo.com/runbot/static/build/309876-11-0-9d3ae9/logs/job_30_run.txt
OPW 1824243
![image](https://user-images.githubusercontent.com/10233975/37234178-ebf08ebc-23bb-11e8-82fd-dbdf54989f76.png)

![image](https://user-images.githubusercontent.com/10233975/37234186-f798c8ba-23bb-11e8-8ae0-6513ab6d56a5.png)

Create a new user named ```Moisés López [Vauxoo]```

Login with it, then follow the steps in main issue description

![image](https://user-images.githubusercontent.com/10233975/37234217-200d5cac-23bc-11e8-9bd4-79e5ea43905f.png)

![image](https://user-images.githubusercontent.com/10233975/37234330-ba0fc6fa-23bc-11e8-983c-3c352fcc7156.png)

**Comment by Elkasitu** [comment] 2018-03-12 08:10
@hugho-ad Thanks, the key missing information from the original post is that one must be logged in as the user with the special unicode characters in order to trigger the error.

**Comment by nim-odoo** [comment] 2018-03-22 13:58
For the record: https://github.com/odoo/odoo/pull/23118

**Comment by hugho-ad** [comment] 2018-04-24 15:04
Any news about this ??

**Closed** 2018-06-01 11:09 UTC
Labels: 11.0, Framework

**Comment by wtaferner** [comment] 2019-04-24 03:54
@len-odoo @tde-banana-odoo @nim-odoo 
The solution with the quotes seems to work for actively created mails from Odoo but does not work in case an email is rendered in Odoo (incoming) and forwarded to its followers.

Is or was there any solution in the meantime? Quite some PRs are in state pending as it seems.

**Comment by len-odoo** [comment] 2019-04-24 06:44
@wtaferner 
Well, it's kind of a different problem in the case of incoming email.
AFAICT, this would be solved by #30079; it doesn't really crash because of the special characters, but just because we feed whatever garbage we received in the email header to 'parse email', and unsurprisingly it crashes.
As noted on the PR, I didn't merge it because it's really crappy, and it would be much better to really fix the flow on incoming mail. However it takes some time to do right, and it was forgotten away because of lack of interest.
Do you have an example (anonymised) mail that reproduces the crash?

**Comment by wtaferner** [comment] 2019-04-25 19:20
@len-odoo 
Hmm, it is actually easy to reproduce...

* Quotation sent to customer
* Answer by the customer with having this kind of email_from
`César Somesurname, SomeAdditionalString <cesar@somedomain.com>`
* It is parsed correctly and added to the thread
* As soon it is tried to send this message to the other followers it will fail
* Solution was to edit the outgoing mail `email_from` by replacing é with e or as done in the other solution by quoting the name in this context

So, IMHO not a rocket science, but of course it can become tricky...

I hope you can at least fix such normal characters in Odoo Core to not fail with an ASCII error ;-)

As a sidenote kind of unrelated as you like smooth solutions ;-)
It is bad practice to try to send a mail with an email domain which you are not in charge of (`César Somesurname, SomeAdditionalString <cesar@somedomain.com>`). 
For example some mail providers will deny completely and others like Google will replace the mail address by your allowed sending domain on the fly and I think Odoo should at least have such a mechanism too as this happens a lot and having an own mail server sending these mails is not the best for reputation.

**Comment by len-odoo** [comment] 2019-04-26 06:59
>not a rocket science
You're right it isn't, but it takes some time, and there are plenty of bugs to fill up our days. But I'll try to get around that next week. Thanks for the steps.

For the sidenote, you could create an issue if there isn't already one, because this is way outside of what I'm allowed to do within Odoo. 
I think anybody reasonably competent in the company knows this, so you can set up any instance to "impersonate" any address. It happened before, but that doesn't seem to have created any kind of reaction. Consequences have not been bad enough I guess.
IMO that's crazy that Odoo would allow to use an address that hasn't been verified before.
I'd say the opinion that would matter on the subject would be Oliver Dony's, if you hope for any progress on it.
