### ISSUE TITLE
[16.0] Price Range: Uncaught Promise > Cannot read properties of null (reading 'classList')

### ISSUE THREAD

**Issue by kristian-vkd** [odoo/odoo#105636] opened 2022-11-14 07:11 UTC
Impacted versions: 16 Enterprise & Community Edition 

Steps to reproduce: Go to webshop -> Filter on price, where no produts is in the price range, then create a wider price range.

Current behavior: Error occurs when making a wider price range, if products did not match the last price range.

Video/Screenshot link (optional): https://i.imgur.com/qATE1jw.png & https://i.imgur.com/kqwhiSl.png

Traceback:
TypeError: Cannot read properties of null (reading 'classList')
    at Class._onPriceRangeSelected (https://20997988-16-0-all.runbot115.odoo.com/web/assets/debug/1/web.assets_frontend_lazy.js:120904:70) (/website_sale/static/src/js/website_sale.js:1197)
    at HTMLInputElement.<anonymous> (https://20997988-16-0-all.runbot115.odoo.com/web/assets/debug/1/web.assets_frontend_lazy.js:72819:23) (/web/static/src/legacy/js/core/mixins.js:277)
    at HTMLDivElement.dispatch (https://20997988-16-0-all.runbot115.odoo.com/web/assets/debug/1/web.assets_frontend_lazy.js:26912:27) (/web/static/lib/jquery/jquery.js:5183)
    at elemData.handle (https://20997988-16-0-all.runbot115.odoo.com/web/assets/debug/1/web.assets_frontend_lazy.js:26720:28) (/web/static/lib/jquery/jquery.js:4991)
    at Multirange.dispatchNewValueEvent (https://20997988-16-0-all.runbot115.odoo.com/web/assets/debug/1/web.assets_frontend_lazy.js:121710:24) (/website/static/lib/multirange/multirange_custom.js:258)

**Comment by vava-odoo** [comment] 2023-04-06 07:53
Closing as not able to reproduce

**Closed by vava-odoo** 2023-04-06 07:53 UTC
Labels: eCommerce, 16.0
