### ISSUE TITLE
[7.0,8.0,master] Purchasing Products with Invoice Control "manual" won't be cancelled correctly

### ISSUE THREAD

**Issue by intero-chz** [odoo/odoo#6947] opened 2015-06-03 15:26 UTC
**Cancelling purchase orders is not working properly for invoice control option manual (Based on Purchase Order lines)**

Impacted versions:
- 7.0
- 8.0
- master

Steps to reproduce:

Part 1 (Services, on all branches)
1. create a purchase order (Invoicing Control: Based on Purchase Order lines)
2. setup a supplier and a line with a service product
3. confirm the order
4. cancel the order

Part 2 (Normal Products, on 7.0 only)
1. create a purchase order (Invoicing Control: Based on Purchase Order lines)
2. setup a supplier and a line with a stockable product
3. confirm the order
4. cancel the picking
5. set picking to OK by Button (I Know it is a unnormal behaviour, but it's possible)
6. cancel the order

Current behavior:
- lines are set to cancelled
- order is not set to cancelled

Expected behavior:
- lines are set to cancelled
- order is set to cancelled

**Comment by StefanRijnhart** [comment] 2015-09-04 07:55
Duplicate of #6925

**Comment by Yenthe666** [comment] 2017-12-08 15:34
Hi @intero-chz,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some. I believe Stefan is correct.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Closed by Yenthe666** 2017-12-08 15:34 UTC
