### ISSUE TITLE
Odoo pos duplicates tables

### ISSUE THREAD

**Issue by DennisAries** [odoo/odoo#25278] opened 2018-06-15 17:15 UTC
Impacted versions: 10, 11

Steps to reproduce: create a floor plan with tables. Close the window. Enter the floor plan again and add an table. Close the browser and connect again. 

Current behavior: tables on the floor are duplicated or tripled after alteration. 

Expected behavior: floorplan to stay intact after alteration

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment] 2018-06-16 06:16
Duplicate of #24831

**Comment by Yenthe666** [comment] 2018-06-27 08:45
Indeed, closing this one off as it is a duplicate.

**Closed by Yenthe666** 2018-06-27 08:45 UTC
Labels: 11.0, Point of Sale

**Comment by ZeroCoolHacker** [comment] 2018-08-29 10:04
You marked this issue duplicate of the <a href="https://github.com/odoo/odoo/issues/24831">#24831</a> and marked that issue duplicate of this one and didn't answer the question in any of them -_-.

**Comment by sswapnesh** [comment] 2018-10-25 19:56
@ZeroCoolHacker Resolved in #27924
