### ISSUE TITLE
When in a crm.lead search domain is used information from the mail.activity model it does not show the leads without activities

### ISSUE THREAD

**Issue by DarkoNikolovski** [odoo/odoo#32195] opened 2019-03-28 09:23 UTC
**Impacted versions:**
12

**Steps to reproduce:**
Try to search by this domain in crm.lead model:
`['&', ('stage_id', '=', 2), '|', ('activity_ids', '=', False), ('activity_ids.date_deadline', '<', '2019-03-28')]`

**Current behavior:**
It shows only past leads.

**Expected behavior:**
To be shown leads from the past and leads without activities.

**Comment by pedrobaeza** [comment] 2019-03-28 09:29
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2019-03-28 09:29 UTC

**Comment by DarkoNikolovski** [comment] 2019-03-28 09:50
@pedrobaeza Sorry but the problem is related directly to Odoo and the way how it does the search for such domains. I just sent the domain as an easy way to reproduce it, you can reproduce the same from the GUI if that is the way that you prefer.
After the debugging that I have done, the issue is happening because when information is required from the `mail.activity` model, such in this case `('activity_ids.date_deadline', '<', '2019-03-28')`, the query is done through this model instead of `crm.lead` model so therefore leads without activities are not included in the final result.

**Comment by pedrobaeza** [comment] 2019-03-28 12:32
If so, then propose the PR solving it, or expose more clearly the cause.
