### ISSUE TITLE
Normal user can not import data from excel file

### ISSUE THREAD

**Issue by ADVALAKI** [odoo/odoo#46286] opened 2020-02-26 06:27 UTC
Impacted versions: 13.0

Steps to reproduce: 
1. Create user with sales user or purchase user rights.
2. Login with that user.
3. Try to import product(or any other data) using excel file.

It will give trackback.
here is code from where its trigger.
https://github.com/odoo/odoo/blob/13.0/odoo/fields.py#L1857 

Current behavior: Its not allow to import data using excel file.

Expected behavior: It should allow user to import data if user have create access.

Video/Screenshot link (optional):
https://ibb.co/c23K9nd

**Comment by pedrobaeza** [comment] 2020-02-26 07:10
This has nothing to do with permissions, but you have the module partner_autocomplete installed and it needs IAP credits for consuming in that task. Uninstall the module or give credits.

Closing as no issue at all.

**Closed by pedrobaeza** 2020-02-26 07:10 UTC

**Comment by ADVALAKI** [comment] 2020-02-26 07:27
uninstall the partner_autocomplete,  but till getting same error.

**Comment by pedrobaeza** [comment] 2020-02-26 07:30
Unless you get more information, the screenshot was about that. Any way, try on a new fresh DB, because you may have other modules that interferes, and give clear steps to reproduce the problem.

**Comment by ADVALAKI** [comment] 2020-02-26 07:31
> Unless you get more information, the screenshot was about that. Any way, try on a new fresh DB, because you may have other modules that interferes, and give clear steps to reproduce the problem.

sorry i have uploaded wrong screenshot.
https://imgur.com/a/QAQctyI

**Comment by pedrobaeza** [comment] 2020-02-26 07:33
That error indicates a bad file to import.

**Comment by ADVALAKI** [comment] 2020-02-26 08:49
> That error indicates a bad file to import.

i have tested it with multiple file and in all file its giving same issue, if imported from user.

if same file imported from admin its get imported without any issue.

**Comment by sswapnesh** [comment] 2020-03-11 17:44
I think https://github.com/odoo/odoo/pull/47382 will fix this
Cc @pedrobaeza

**Comment by pedrobaeza** [comment] 2020-03-11 17:47
Uhm, interesting... It can be indeed.
