### ISSUE TITLE
[Odoo 11] Due payment report not impacted when an invoice is partially paid

### ISSUE THREAD

**Issue by minos84** [odoo/odoo#22244] opened 2018-01-15 21:20 UTC
Impacted versions:
Odoo 11
Steps to reproduce:
1- Create a customer
2- Sell a product to this customer
3- Deliver the product, create an invoice
4- Pay partially the amount of the invoice
5- Print the invoice then open it ==> The payment and the balance are displayed in the PDF File
6- Click on the customer ==>The customer form is displayed
7- Under "Print", click on "Due Payments" ==> The PDF is downloaded
8- Open the PDF
Current behavior:
The  report does not take into account the payment made previously
Expected behavior:
The  report should consider the payment made previously
Video/Screenshot link (optional):

**Comment by StefanRijnhart** [comment] 2018-03-08 14:22
Duplicate of https://github.com/odoo/odoo/issues/21353

**Comment by Yenthe666** [comment] 2018-03-08 14:50
Thanks a lot for pointing this out @StefanRijnhart 
@minos84 as the original bug report (https://github.com/odoo/odoo/issues/21353) is older and has more content I'm closing this one in favour of the other.

Regards,
Yenthe

**Closed by Yenthe666** 2018-03-08 14:50 UTC
Labels: 11.0
