### ISSUE TITLE
Wkhtmltopdf failed (error code: -11). Memory limit too low or maximum file number of subprocess reached.

### ISSUE THREAD

**Issue by novawish** [odoo/odoo#19160] opened 2017-08-30 09:55 UTC
Impacted versions:
Odoo 10, wkhtmltopdf 0.12.4

Steps to reproduce:
Print a PDF report with a field Text placed at the bottom of the page. The size of field Text must be long enough to overflow the current page so it must creates a new page

Current behavior: Show errors:
`Wkhtmltopdf failed (error code: -11). Memory limit too low or maximum file number of subprocess reached.`

Expected behavior:
The content of field Text must split to a new page or move completely to a new page

**Comment by Yenthe666** [comment] 2017-09-01 15:19
Hi @novawish,

Thank you for your report.
It is however not advised to use wkhtmltopdf version `0.12.2.x`, `0.12.3.x` or `0.12.4.x` as stated in the wiki at: https://github.com/odoo/odoo/wiki/Wkhtmltopdf
Please downgrade your wkhtmltopdf to `0.12.1.x` and you'll most likely won't face this issue anymore.
Can you please downgrade and let us know if everything is working fine?

Regards,
Yenthe

**Comment by novawish** [comment] 2017-09-01 16:52
Hi @Yenthe666,

Thanks for your reply.
I have downgraded the wkhtmltopdf to `0.12.1.x` and it's fine to print. However, the headers are overlapped with the contents of the body.
I found the workaround way for this issue (with wkhtmltopdf `0.12.4.x`), though it sounds irrelevant but worked: In my case, I set the `style="min-height: 300px"` for the Text field at the bottom of page so that it can be split to the new page.

If anyone had the same issue, you may try that solution and give me feedback

Regards,

**Comment by mkschreder** [comment] 2017-11-02 10:53
I have downgraded to v0.12.1 and I'm still having the same problem. Wouldn't it be better if odoo bundled the right version with the release? Seems ridiculous to me that we have to manually compile a custom version of qt in order to use odoo.

**Comment by jl2035** [comment] 2017-11-06 21:38
@mkschreder It's ridiculous, I agree.

I'm also haviing this issue. Downgrading to 0.12.1 does not solve the problem.

**Comment by aliencrash** [comment] 2017-11-08 01:12
Having the same issue here, cannot print any document.

**Comment by novawish** [comment] 2017-11-08 10:17
@mkschreder @jl2035 @aliencrash Did you try the solution I mentioned above?

**Comment by jl2035** [comment] 2017-11-08 10:42
@novawish yes,  but I can't print invoices.

me@vps134323:~$ wkhtmltopdf --version
wkhtmltopdf 0.12.1 (with patched qt)

**Comment by mkschreder** [comment] 2017-11-08 11:25
For me just downgrading did not work. I had to have a special version built with modified qt.

**Comment by jl2035** [comment] 2017-12-11 10:35
I ended up here again. This is one of the biggest nightmares in Odoo!

**Comment by rim-odoo** [comment] 2018-01-08 16:23
The CSS of the report causes wkhtmltopdf to eat too much RAM. Either you can upsize your memory limit (if your server can handle it), either you must change the text at the bottom of the page in order to change a bit the number of pages. This issue is very nasty since wkhtmltopdf crashes without indicating the real source of the problem that seems to be the evaluation of some CSS rule

**Comment by aliencrash** [comment] 2018-01-08 17:42
The actual problem is with openssl library, verify with version you are using and install openssl 1.0. This is an issue with QT

**Comment by chris001** [comment] 2018-01-11 20:08
@aliencrash 
1. Can you provide a link to the problem issue with `openssl` library in the fork of `QT` inside `wkhtmltopdf`.
2. Have you tested 0.12.4 and does it work for you with the `web.base.url` setting `http://127.0.0.1:8069`

**Comment by aliencrash** [comment] 2018-01-15 09:02
@chris001 

1. This is the error https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3001. 
2. I'm not using any settings. If you type wkhtmltopdf www.google.com google.pdf on your console you will get the error even with version 0.12.4. So it's not actually related to Odoo.

**Comment by chris001** [comment] 2018-01-15 16:27
@aliencrash 
I just tested this exact command on ubuntu 16.04 while logged in as `root` (not that it should matter which user you're running it as) and it worked.
Which OS you using?
Which version `wkhtmltopdf`?
Downloaded `wkhtmltopdf` from which link?
```
root@server7:~# wkhtmltopdf www.google.com google.pdf
Loading pages (1/6)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
root@server7:~# ls -la *.pdf
-rw-r--r-- 1 root root 100100 Jan 15 11:21 google.pdf
root@server7:~# wkhtmltopdf --version
wkhtmltopdf 0.12.4 (with patched qt)
```

**Comment by aliencrash** [comment] 2018-01-15 16:43
I upgraded again the openssl-devel library to version 1.1  
I'm using fedora 27. 

wkhtmltopdf 0.12.4 (with patched qt)

wkhtmltopdf www.google.com google.pt
Loading pages (1/6)
QSslSocket: cannot resolve CRYPTO_num_locks                  ] 10%
QSslSocket: cannot resolve CRYPTO_set_id_callback
QSslSocket: cannot resolve CRYPTO_set_locking_callback
QSslSocket: cannot resolve sk_free
QSslSocket: cannot resolve sk_num
QSslSocket: cannot resolve sk_pop_free
QSslSocket: cannot resolve sk_value
QSslSocket: cannot resolve SSL_library_init
QSslSocket: cannot resolve SSL_load_error_strings
QSslSocket: cannot resolve SSLv23_client_method
QSslSocket: cannot resolve SSLv23_server_method
QSslSocket: cannot resolve X509_STORE_CTX_get_chain
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
QSslSocket: cannot resolve SSLeay
QSslSocket: cannot call unresolved function CRYPTO_num_locks
QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
QSslSocket: cannot call unresolved function SSL_library_init
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function sk_num
Segmentation fault (core dumped)

**Comment by chris001** [comment] 2018-01-15 17:01
@aliencrash 
Gathered from https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3001
It appears this is the fix for fedora, because `QT` inside `wkhtmltopdf` requires ssl 1.0 :
> Fedora 26 breaks it, you need the 1.1.0 ssl devel libs. This solves it:
`dnf install compat-openssl10-devel.x86_64 --allowerasing`
The new version of `QT`, 5.10, which will be added to the new version of `wkhtmltopdf` soon, should run without crashing on popular versions of `openssl`.

**Comment by chris001** [comment] 2018-04-30 16:49
@FlyingPigSolutions 
This should solve your issue: 
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2592

**Comment by FlyingPigSolutions** [comment] 2018-05-02 06:51
I tried to increase memory from what was:

> limit_memory_hard = 2684354560
> limit_memory_soft = 2147483648
> 

TO

> limit_memory_hard = 4684354560
> limit_memory_soft = 4147483648
> 

then restarted the odoo server : `sudo service odoo-server restart`

Problem remain the same : 
> Wkhtmltopdf failed (error code: -11). Memory limit too low or maximum file number of subprocess reached. Message : b''


We have in our ubuntu server this configuration :  

> 2 GB Memory / 30 GB Disk

Could it be really just a RAM issue on the server? I think 2GB is more than enough. There is nothing else share on that server. What you think?

**Comment by FlyingPigSolutions** [comment] 2018-05-02 07:03
Checking the link your mentioned @chris001, I also check on terminal with command `ulimit -a` 

> core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 7928
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 7928
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

then increased the open files with `ulimit -n 10000`

now I have raised the open files limit : 

> core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 7928
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 10000
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 7928
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

Still got the message error:

> Wkhtmltopdf failed (error code: -11). Memory limit too low or maximum file number of subprocess reached. Message : b''

> That's tricky… Would raising the RAM of the server do the trick? I wonder...

**Comment by FlyingPigSolutions** [comment] 2018-05-02 08:14
> Ok raising the server RAM from 2GB to 4GB did not solved it.

**Comment by FlyingPigSolutions** [comment] 2018-05-02 08:40
Ok, making further test, it seems I can print sales proforma, order quotation, order.
What I can't print is after sales confirmation, is the delivery slip.
I can print preparation order document though (the one with barcode).
And I can print Invoices.

My test was done with the same order.
So the only document I can't print from the whole order process is the delivery slip.

> Total mystery...

**Comment by FlyingPigSolutions** [comment] 2018-05-02 12:45
Thanks @aliencrash I'll try that.
It's surprising coz it just happened to not work when it was working fine till now:

To check version:
`apt-cache policy openssl`

> openssl:
>   Installed: 1.0.2g-1ubuntu4.12
>   Candidate: 1.0.2g-1ubuntu4.12
>   Version table:
>  *** 1.0.2g-1ubuntu4.12 500

**Comment by FlyingPigSolutions** [comment] 2018-05-02 13:34
I have run `sudo apt-get install openssl`

> Reading package lists... Done
Building dependency tree       
Reading state information... Done
openssl is already the newest version (1.0.2g-1ubuntu4.12).
The following packages were automatically installed and are no longer required:
  linux-headers-4.4.0-104 linux-headers-4.4.0-104-generic linux-headers-4.4.0-109
  linux-headers-4.4.0-109-generic linux-headers-4.4.0-112 linux-headers-4.4.0-112-generic
  linux-image-4.4.0-104-generic linux-image-4.4.0-109-generic linux-image-4.4.0-112-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 53 not upgraded.

Now it is working. o_0 Problem seems to be solved. For now... [TO BE CONTINUED]

Thank you @aliencrash @chris001

**Comment by Yenthe666** [comment] 2018-05-03 05:55
@novawish are you still facing this issue? Can you try the provided solution for the `openssl` package too please?

**Comment by Yenthe666** [comment] 2018-05-22 14:11
Hi there,

I'm closing this bug report as there has been no feedback in a few weeks from the author and as some fixes have been provided.

Regards,
Yenthe

**Comment by Auneor** [comment] 2018-05-28 14:56
Hi @Yenthe666 ,
I'm experiencing the same issue. I've tried all fixes suggested here
and nothing make it works
It's odoo10 enterprise
For a certain report and a certain object, it's working fine, until
adding 4 cells in a table of the template (with nothing in it) the
error appears
I've set a very high ulimit, I have 16Gb of ram, and I've set the odoo
memory limits very hight
Ubuntu 16.04
simon@ ~ () $ wkhtmltopdf --version
wkhtmltopdf 0.12.1 (with patched qt)
ii  openssl                                       1.0.2g-1ubuntu4.12                           amd64        Secure Sockets Layer toolkit - cryptographic utility

Regards

**Comment by idealisconsultingbe** [comment] 2018-05-30 12:40
Hi,
Same problem for me.
I find a way to print the document by adding  `--disable-smart-shrinking` to the command with a batch script, but the PDF isn't the same anymore.

Here is what I did:
```
mv /usr/local/bin/wkhtmltopdf /usr/local/bin/wkhtmltopdf_original
touch /usr/local/bin/wkhtmltopdf
chmod +x /usr/local/bin/wkhtmltopdf
nano /usr/local/bin/wkhtmltopdf
```
and add the following lines:
```
#!/bin/bash
wkhtmltopdf_original --disable-smart-shrinking $@
```
But this is not a real solution as the design isn't the same anymore...

Regards

**Comment by pedrobaeza** [comment] 2018-05-30 13:26
This is not an Odoo problem, but wkhtmltopdf one, and we provided a reproducible case 2 weeks ago to the developer for fixing it (https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2711#issuecomment-389429960), and he has said that is going to be fixed on next release, but nothing to do on Odoo side.

@mart-e the upgrade to the new version is going to be mandatory if we want a good behavior.

Closing this issue by the reasons above.

**Closed by pedrobaeza** 2018-05-30 13:26 UTC
Labels: Need information

**Comment by eLBati** [comment] 2018-09-19 17:44
@pedrobaeza @mart-e odoo could allow user to increase the maximum number of open file descriptors and avoid this error, with an additional option ```--limit-open-files```
See https://github.com/odoo/odoo/pull/27115/

**Comment by pedrobaeza** [comment] 2018-09-19 17:47
@eLBati it's not the same problem. For solving this one, upgrade to 0.12.5. Description is above.

**Comment by bunhin** [comment] 2018-09-27 13:35
I have similar error message when try to print General Ledger Report with data range more than 2 month with all journals,  is it the same problem with wkhtmltopdf?,  i am using v 0.12.4 on centos 7.

here is the error message :  
"Wkhtmltopdf failed (error code: -11). Memory limit too low or maximum file number of subprocess reached. Message : tepages=1273&webpage=/tmp/report.body.tmp.KWFeYl.html&time=12:37 PM&date=9/27/18 (sometimes it will work just to ignore this error with --load-error-handling ignore)
Error: Failed loading page file:///tmp/report.header.tmp.qULVx5.html?page=1272&section=PT...........: General ledger&sitepage=1272&title=&subsection=&frompage=1&subsubsection=&isodate=2018-09-27&topage=1273&doctitle=&sitepages=1273&webpage=/tmp/report.body.tmp.KWFeYl.html&time=12:37 PM&date=9/27/18 (sometimes it will work just to ignore this error with --load-error-handling ignore)
Error: Failed loading page file:///tmp/report.header.tmp.qULVx5.html?page=1273&section=PT...........: General ledger&sitepage=1273&title=&subsection=&frompage=1&subsubsection=&isodate=2018-09-27&topage=1273&doctitle=&sitepages=1273&webpage=/tmp/report.body.tmp.KWFeYl.html&time=12:37 PM&date=9/27/18 (sometimes it will work just to ignore this error with --load-error-handling ignore)
QPaintDevice: Cannot destroy paint device that is being painted"

**Comment by sagarvsakaria** [comment] 2021-07-21 12:24
> Hi @novawish,
> 
> Thank you for your report.
> It is however not advised to use wkhtmltopdf version `0.12.2.x`, `0.12.3.x` or `0.12.4.x` as stated in the wiki at: https://github.com/odoo/odoo/wiki/Wkhtmltopdf
> Please downgrade your wkhtmltopdf to `0.12.1.x` and you'll most likely won't face this issue anymore.
> Can you please downgrade and let us know if everything is working fine?
> 
> Regards,
> Yenthe

I have already 

> Hi @novawish,
> 
> Thank you for your report.
> It is however not advised to use wkhtmltopdf version `0.12.2.x`, `0.12.3.x` or `0.12.4.x` as stated in the wiki at: https://github.com/odoo/odoo/wiki/Wkhtmltopdf
> Please downgrade your wkhtmltopdf to `0.12.1.x` and you'll most likely won't face this issue anymore.
> Can you please downgrade and let us know if everything is working fine?
> 
> Regards,
> Yenthe

I have already use 0.12.1 version but still getting issue

**Comment by trinanda** [comment] 2024-01-20 15:44
I am still experiencing the same issue in Odoo 16:

> Wkhtmltopdf failed (error code: -11). Memory limit too low or maximum file number of subprocess reached. Message: 


It happened when I tried to print a pdf with hundreds of pages.
Is there already a solution for this?

**Comment by KjourdainBHC** [comment] 2024-07-17 11:54
same problem on macos (sonoma) , i can print a few report (single page) then it refuses to work, error -11 , memory too low.

**Comment by keiverobles** [comment] 2024-09-27 09:47
> I tried to increase memory from what it was:
> 
> > limit_memory_hard = 2684354560
> > limit_memory_soft = 2147483648
> 
> TO
> 
> > limit_memory_hard = 4684354560
> > limit_memory_soft = 4147483648
> 
> then restarted the odoo server : `sudo service odoo-server restart`
> 
> Problem remain the same :
> 
> > Wkhtmltopdf failed (error code: -11). Memory limit too low or maximum file number of subprocess reached. Message : b''
> 
> We have in our ubuntu server this configuration :
> 
> > 2 GB Memory / 30 GB Disk / 1vCPU
> 
> Could it be really just a RAM issue on the server? I think 2GB is more than enough. There is nothing else shared on that server. What you think?

Hi, I solved my problem with this solution. Although I had to increase my server memory to 16GB.
But basically, I think that the limit_memory_hard option should be always less to server memory physical
