### ISSUE TITLE
[11.0 enterprise] Message Form View

### ISSUE THREAD

**Issue by bhumiht** [odoo/odoo#31898] opened 2019-03-18 04:41 UTC
Impacted versions: 11.0 Enterprise

Steps to reproduce: 

1. Enable Active Developer Mode
2. Settings -> Messages 
3. Open Message Form View
4. In Form view -> Body Tab -> Click on link 
5. Give Traceback.

**Comment by pedrobaeza** [comment] 2019-03-18 08:37
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by bhumiht** [comment] 2019-03-18 21:25
Hi,

Yes this issue is produce in http://runbot.odoo.com/runbot/repo/git-github-com-odoo-enterprise-7.

You can check in this video: https://www.youtube.com/watch?v=L-QtVpCrAts

**Comment by sswapnesh** [comment] 2019-03-20 16:45
Hello @bhumiht 
Duplicate of https://github.com/odoo/odoo/issues/24112

Cc: @pedrobaeza

**Comment by pedrobaeza** [comment] 2019-03-20 17:41
Closing then as duplicate of #24112

**Closed by pedrobaeza** 2019-03-20 17:41 UTC
Labels: Need information
