### ISSUE TITLE
Odoo 9C BUG , TypeError: _run_wkhtmltopdf() takes at most 10 arguments (11 given)

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#10802] opened 2016-02-06 11:57 UTC
Traceback (most recent call last):
 
    return old_api(self, *args, **kwargs)
TypeError: _run_wkhtmltopdf() takes at most 10 arguments (11 given)

Created odoo 9C applicant print pdf vi qweb-pdf

What's 10 arguments ? Strange odoo Message !!! Traceback

**Comment by sle-odoo** [comment] 2016-06-08 11:47
Closing as i cannot reproduce. This is probably linked to a custom addon. Also, your bug report is really not clear.

**Closed by sle-odoo** 2016-06-08 11:47 UTC

**Comment by tejastank** [comment] 2016-06-09 05:53
No customize addons used, only office addons, 

Thanks for quick close it.
