### ISSUE TITLE
Prevent save a model when clicking a button that rises a wizard

### ISSUE THREAD

**Issue by osmanialv** [odoo/odoo#26527] opened 2018-08-22 15:05 UTC
I need to save my model (lets call this Model_A) after filling a form raising for a wizard. The explanation is: I have a module that has a button which raises a wizard , so, when i press that button it saves the Model_A before and then raises the wizard. The problem is that i need to fill some fields in the wizard form, save it, close the wizard, and after that save Model_A by clicking on the save button.  I already tried by rewriting the create function and returning False, None, an empty dictionary... Iam working with Odoo V8.
Its that possible?

**Comment by pedrobaeza** [comment] 2018-08-22 15:48
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

Any way, this is how Odoo works by design, so it shouldn't be done and you should work with that paradigm in mind.

**Closed by pedrobaeza** 2018-08-22 15:48 UTC

**Comment by sswapnesh** [comment] 2018-08-22 19:00
@osmanialv 
Replacing vals with blank dictionary(not always but based on some condition) should work but wont suggest to do so as @pedrobaeza  said.
