### ISSUE TITLE
[v14.0] Can't add product to invoice by barcode in POS Interface v14,Please Help

### ISSUE THREAD

**Issue by EslamDawoud** [odoo/odoo#59056] opened 2020-10-04 08:13 UTC

**Comment by pedrobaeza** [comment] 2020-10-05 07:22
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Closed** 2020-10-05 07:44 UTC
Labels: Need information
