### ISSUE TITLE
Duplicate with  different ticket number in POS

### ISSUE THREAD

**Issue by mrsmartkhalil** [odoo/odoo#42367] opened 2019-12-25 19:53 UTC
Impacted versions: odoo 13

Steps to reproduce:

Current behavior: after getting payments and clicking Validate in POS, it saves the amount received twice with different ticket number

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2019-12-26 11:16
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by pedrobaeza** [comment] 2020-01-07 15:49
This should be fixed in #40600, so closing.

**Closed by pedrobaeza** 2020-01-07 15:49 UTC
Labels: Need information
