### ISSUE TITLE
[10.0] [BUG] Expense from email

### ISSUE THREAD

**Issue by Vartkat** [odoo/odoo#17684] opened 2017-06-19 00:10 UTC
Impacted versions:
10.0

Steps to reproduce:

Create an Expense product with taxe, account and internal ref.
Send an email to your special expense mail address using this internal ref.

Current behavior:

An expense is created but the Expense product is not completely recognized, account is not the account that has been setup in the Expense product nor the taxe.

Expected behavior:
A new expense is created using the Expense product as a template i.e. account is the account setup is the Expense product, taxe is the taxe setup in the Expense product. I was expecting the expense made from email to act as the one created from the backend.

**Comment by Vartkat** [comment] 2017-07-26 21:38
Nobody cares about this ? Perhaps I didn't explain the problem clearly.

In Expense module, 
- Create an Expense product (product that could be expensed), setting its account, tax and Internal ref 
- Create an expense using this product as expense template, Odoo gives your expense the account and taxe from the Expense product.
Now send a email to expense@YourDomain.com. The mail object begins with the product internal ref within brackets, then a description then the amount.

Current behavior 
Mail is received and parsed to expense module, product name, description and amount are recognized but not tax neither the account.

Expected behavior
Mail is received and completely parsed to the expense module, i.e. all parameters from the expendable product are given to the expense created, i.e. name, description, amount, tax and account, so that (most of time) there's nothing more to do than submitting, approving and posting the expense.

Hope someone can take care of this cause without this behavior the expense mail function is useless.

Regards

V.

**Comment by pedrobaeza** [comment] 2018-06-01 00:17
Hi, I'm not able to reproduce this problem in latest version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-06-01 00:17 UTC
Labels: 10.0, Services
