### ISSUE TITLE
Generate a Payment Link does not work with same payment acquirers 

### ISSUE THREAD

**Issue by m-abdalrahman** [odoo/odoo#85284] opened 2022-02-24 10:43 UTC
Impacted versions:
14.0
Steps to reproduce:
create Generate a Payment Link from sale order to pay with same payment acquirers
Current behavior:
I get error `There is an issue with your delivery method. Please refresh the page and try again.` , this error happen if user not logged in to website or sale order not created from website.
_Note :_
_delivery method added_ 

**Is there away to solve this problem, because some partner doesn't want logged in website?**

**Comment by m-abdalrahman** [comment] 2022-02-25 14:28
this commit here https://github.com/odoo/odoo/commit/a170fb29e7eddfd533efa10980e91bf84ca2e64a, is the reason for this problem because `request.website.sale_get_order()`  looking for user how create the order from website

**Comment by vava-odoo** [comment] 2023-04-27 13:39
Hello @m-abdalrahman 
Sorry for the late answer. Is the error still there.
If yes, can you provide more information/context? I was not able to reproduce your error on the [runbot](http://runbot.odoo.com/runbot)? (blue door icon of the version row (15) with login/pwd as admin/admin)
Could you try and send the exact steps to reproduce ?
If not, could you close the issue?
Thanks,

**Closed** 2023-05-01 08:54 UTC
Labels: Need information, Payment
