### ISSUE TITLE
Mobile browser goback error

### ISSUE THREAD

**Issue by KennyLeung** [odoo/odoo#30001] opened 2019-01-07 16:02 UTC
Impacted versions:10.0

Steps to reproduce:

In mobile browser or desktop broswer mobile mode,  login odoo, and open some sale order or purchase order , or any pages, then goback previous page twice , and error occured.

Current behavior:

Uncaught TypeError: Cannot read property 'type' of null

http://423389-10-0-d4024a.runbot18.odoo.com/web/static/src/js/view_manager.js:467
Traceback:
TypeError: Cannot read property 'type' of null
    at Class.do_load_state (http://423389-10-0-d4024a.runbot18.odoo.com/web/static/src/js/view_manager.js:467:69)
    at http://423389-10-0-d4024a.runbot18.odoo.com/web/static/src/js/action_manager.js:570:42
    at fire (http://423389-10-0-d4024a.runbot18.odoo.com/web/static/lib/jquery/jquery.js:3119:58)
    at Object.add [as done] (http://423389-10-0-d4024a.runbot18.odoo.com/web/static/lib/jquery/jquery.js:3165:49)
    at Class.do_load_state (http://423389-10-0-d4024a.runbot18.odoo.com/web/static/src/js/action_manager.js:568:46)
    at Object.<anonymous> (http://423389-10-0-d4024a.runbot18.odoo.com/web/static/src/js/web_client.js:132:41)
    at Object.<anonymous> (http://423389-10-0-d4024a.runbot18.odoo.com/web/static/lib/jquery/jquery.js:3276:89)
    at fire (http://423389-10-0-d4024a.runbot18.odoo.com/web/static/lib/jquery/jquery.js:3119:58)
    at Object.add [as done] (http://423389-10-0-d4024a.runbot18.odoo.com/web/static/lib/jquery/jquery.js:3165:49)
    at Array.<anonymous> (http://423389-10-0-d4024a.runbot18.odoo.com/web/static/lib/jquery/jquery.js:3275:77)

Video/Screenshot link (optional):
http://zhflash.com/downloads/client_error.flv

**Comment by KennyLeung** [comment] 2019-01-07 16:08
in elder odoo 10 version (2018-11-14 issued), follow steps above,  it reproduced below errors:

Uncaught TypeError: Cannot read property 'arch' of undefined

https://test.zhsunlight.cn/web/static/src/js/view_manager.js:282 追溯： TypeError: Cannot read property 'arch' of undefined at Class.create_view (https://test.zhsunlight.cn/web/static/src/js/view_manager.js:282:41) at Class.start (https://test.zhsunlight.cn/web/static/src/js/view_manager.js:115:49) at Class.prototype.(anonymous function) [as start] (https://test.zhsunlight.cn/web/static/src/js/framework/class.js:89:38) at Array.<anonymous> (https://test.zhsunlight.cn/web/static/src/js/framework/widget.js:193:25) at Array.<anonymous> (https://test.zhsunlight.cn/web/static/lib/jquery/jquery.js:3276:89) at fire (https://test.zhsunlight.cn/web/static/lib/jquery/jquery.js:3119:58) at Object.fireWith [as resolveWith] (https://test.zhsunlight.cn/web/static/lib/jquery/jquery.js:3231:49) at Object.<anonymous> (https://test.zhsunlight.cn/web/static/lib/jquery/jquery.js:3360:58) at fire (https://test.zhsunlight.cn/web/static/lib/jquery/jquery.js:3119:58) at Object.fireWith [as resolveWith] (https://test.zhsunlight.cn/web/static/lib/jquery/jquery.js:3231:49)

**Comment by pedrobaeza** [comment] 2019-01-07 17:33
Navigation through back button of the browser is not guaranteed. You should click instead the arrow in the interface. Or is that what you are using? If so, please explain a reproducible steps in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin) with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Yenthe666** [comment] 2019-01-28 12:48
Hi there,

I'm closing this issue as there has been no feedback in three weeks.

Regards,
Yenthe

**Closed by Yenthe666** 2019-01-28 12:48 UTC
Labels: Need information
