### ISSUE TITLE
[Master, 12.0 C] Repair module : Invoice feature from repair.

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#36301] opened 2019-09-01 13:31 UTC
Impacted versions: [12.0 C]

Steps to reproduce:
- Create repair. select :: Invoice Method = After repair,
- Confirm Repair and Start the repair.

Current behavior:
- Its started showing Invoice count = 1 in smart button. when I click on it there is not any invoice created yet.
- Then also when I created and save that invoice (move-in v13), it is saved.but not linking with that repair record anymore.

- Now after I click on the button 'End repair' in repair form,
- It is showing me a button to create the invoice. when I create an invoice using it. its showing me count 1 in invoice smart button again and when opening smart button it is showing currently created invoice.which is right.because my invoicing method is after the repair so. 

Expected behavior:

-  It should not show any count or smart button if my invoicing method is after the repair I believe after Starting the repair. OR if you want to show it then count should be 0. and after clicking on smart button if i saved it, then it should show count to 1 and link my created invoice too. 

- OR just show the invoice and smart button of it only when I end repair record and create invoice using Create Invoice button.

Video/Screenshot link (optional):

[https://drive.google.com/open?id=1Cy6aZV-QVxKdTu1CWtuBzrHwqszHn6CD](url)

**Comment by pedrobaeza** [comment] 2019-09-02 10:47
Please don't open issues on master branch, as it's a branch on continuous development, so errors are expected. You will be able to do it when the version is released.

Closing by the reason above.

**Closed by pedrobaeza** 2019-09-02 10:47 UTC

**Comment by dipsshah42** [comment] 2019-10-03 13:59
@pedrobaeza  and @sswapnesh  i can able to re-produce the same issue again now. Kindly have a look.

**Comment by pedrobaeza** [comment] 2019-10-03 15:21
In runbot

**Comment by sswapnesh** [comment] 2019-10-03 20:01
@dipsshah42  I can confirm this issue.
-------------------------------
In v13

https://github.com/odoo/odoo/blob/c47b1f7dd235d67e123793cba732338445abcb79/addons/repair/views/repair_views.xml#L54

What?


----------------

For v12 (I didn't find any Invoice Count there) I have added Fix at https://github.com/odoo/odoo/pull/37944 to fix Smart button's visibility
