### ISSUE TITLE
[13] Do not try to load Image on Kanban view if no Image is set

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#44803] opened 2020-02-06 18:47 UTC
Impacted versions: 13.0

Steps to reproduce:  Create Employee without Image --> Go to Kanban View

Current behavior: 404 on Console

(_Couldn't Upload Image here as Github has some Issues_)
![Screenshot from 2020-02-07 00-11-02](https://user-images.githubusercontent.com/16624719/73968665-0b078c00-4940-11ea-9b15-3abcac4813b5.png)

`web.assets_common.js:1030 GET http://localhost:8069/web/image?model=hr.employee&id=22&field=image_128&unique=02072020000902 404 (NOT FOUND)`

Expected behavior: No error on Console, Do not try to load Image

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment] 2020-02-06 20:07
Psht, that's not a bug in HR. That's a system-wide thing happening and only on kanban views. For example on products from the purchase app:
![image](https://user-images.githubusercontent.com/6352350/73974365-82c7bd80-4924-11ea-933d-dcc22ce0e2cb.png)

It only seems to happen in 13.0 and I've seen it being triggered thousands of times at my biggest customer. Maybe I should log it as an OPW..

**Comment by Yenthe666** [comment] 2020-02-06 20:11
OPW `2192340`

**Comment by sswapnesh** [comment] 2020-02-07 17:34
> That's a system-wide thing happening and only on kanban views. 

Not really, I have tested the same on Contacts and didn't found these errors there
http://1158815-13-0-43a580.runbot32.odoo.com/web#action=171&model=res.partner&view_type=kanban&cids=1&menu_id=121
![Screenshot from 2020-02-07 23-02-21](https://user-images.githubusercontent.com/16624719/74051415-eb369d80-49fd-11ea-9fa2-86ec6e44cfe3.png)

**Comment by Yenthe666** [comment] 2020-02-07 19:40
Hmm interesting, not framework wide but in multiple places then :) Anyways its reported so fixes will follow

**Comment by Yenthe666** [comment] 2020-02-12 08:06
Fixed in https://github.com/odoo/odoo/commit/0347a2e7cd8be0c4e8ee6fdcefec0a3e26dab419

**Closed by Yenthe666** 2020-02-12 08:06 UTC
Labels: 13.0, Framework, OE
