### ISSUE TITLE
[16.0] account: UnboundLocalError: local variable 'balance' referenced before assignment

### ISSUE THREAD

**Issue by ljsalvatierra-factorlibre** [odoo/odoo#116064] opened 2023-03-21 14:50 UTC
Impacted versions:
16.0

Steps to reproduce:
Click on `RECONCILE x ITEMS` on the Accouting Dashboard with demo data.

Current behavior:
```
addons/account/models/account_reconcile_model.py", line 523, in _get_write_off_move_lines_dict
    if currency.is_zero(balance):
UnboundLocalError: local variable 'balance' referenced before assignment
```

Demo data / `'amount_type': 'regex'`:

```python
    @api.model
    def _get_demo_data_reconcile_model(self):
        cid = self.env.company.id
        return ('account.reconcile.model', {
            f'{cid}_reconcile_from_label': {
                'name': 'Line with Bank Fees',
                'rule_type': 'writeoff_suggestion',
                'match_label': 'contains',
                'match_label_param': 'BRT',
                'line_ids': [
                    Command.create({
                        'label': 'Due amount',
                        'account_id': self._get_demo_account(
                            'income',
                            'income',
                            self.env.company,
                        ).id,
                        'amount_type': 'regex',
                        'amount_string': r'BRT: ([\d,.]+)',
                    }),
```
Expected behavior:
Enter the reconcilitation view.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by WeronikaBorsukowska** [comment] 2023-03-21 17:17
They won't fix it lol

**Comment by smetl** [comment] 2023-06-13 06:29
@ljsalvatierra-factorlibre Hello. I mentioned on https://github.com/odoo/odoo/pull/123626, I'm not able to reproduce the issue and the code doesn't seem incorrect to me. I followed your steps to reproduce as well without success on any of the 8 demo statement lines. Can you give me more details how to reproduce it or a video, by chance?
Thank you in advance.

**Comment by smetl** [comment] 2023-06-23 10:13
Let me know if this issue comes back.

**Closed by smetl** 2023-06-23 10:13 UTC
Labels: Accounting, 16.0

**Comment by ACheung-FactorLibre** [comment] 2024-02-16 09:17
Hello @smetl,

The error still persists. It only appears in new databases with demo data. Could you please check this?

Thank you in advance.

**Comment by smetl** [comment] 2024-02-19 09:02
@ACheung-FactorLibre I would like to fix it but `_get_write_off_move_lines_dict` is only called from the manual reconciliation widget in which, you only have access to models having strictly lines being percentage or fixed (`get_reconcile_modelds_for_manual_reconciliation`).
This method is not called from the bank reco widget pointed by `RECONCILE x ITEMS` on the accounting dashboard.
I clearly don't have the same setup as yours to reproduce this issue :sweat_smile: 
I'll do a quick fix to remove the traceback but I don't know how you reach this error at the first place.

**Comment by ACheung-FactorLibre** [comment] 2024-02-19 09:34
Hi @smetl,
Thank you for your response. The error that appears is explained here: https://github.com/OCA/account-reconcile/issues/592
