### ISSUE TITLE
Image widget on list view with other than image file types brakes attachments

### ISSUE THREAD

**Issue by sciallo** [odoo/odoo#43162] opened 2020-01-12 21:54 UTC
Impacted versions: 12.0 (AFAIK)

Steps to reproduce: 
- in developer mode settings -> Technical -> attachments
- Modify view_attachment_tree by adding <field name="datas" widget="image"/> (devel menu edit view: list)
- Refresh

Current behavior: 
Image is displayed in tree for image files, but not for other files (as one would expect) but all non image files now show as mimetype application/octet-stream and the content field is empty. files can't be downloaded.
Going to the original document where the document was created (eg message, chatter etc) downloading said document downloads a 0bite file. If we try to view web assets in that list we'll have to regenerate assets...

Expected behavior: image widget should just ignore non image files and move on without any other consequence.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/17577898/72225837-01b11c80-3558-11ea-83d7-056c07aca11b.png)

The more I try to view, the more "break"

![image](https://user-images.githubusercontent.com/17577898/72225892-9ae03300-3558-11ea-9c07-37ff5bdf973b.png)

![image](https://user-images.githubusercontent.com/17577898/72225944-5dc87080-3559-11ea-9a82-de73b9a5f50e.png)

![image](https://user-images.githubusercontent.com/17577898/72225963-818bb680-3559-11ea-964c-72fc4fc6f9e1.png)

Assets are gone!
![image](https://user-images.githubusercontent.com/17577898/72226173-23140780-355c-11ea-9868-444594ac826c.png)

**Comment by pedrobaeza** [comment] 2020-01-12 22:57
This is something expected, as the image widget is not for an heterogeneous binary field, and you won't find any usage of it in that case, so closing.

**Comment by sciallo** [comment] 2020-01-12 23:21
Respectfully, This is dangerous!

Whether or not I would find a usage for it (I could argue a case there, I want to list all attachments of a task in a tree view, some might be pdfs) the Idea that anyone with developer mode access can royally corrupt my database and delete files just by doing this leaves me very uneasy.... I can come up with a different view for my needs, but the problem remains, the image widget should not be able to delete files.

**Comment by pedrobaeza** [comment] 2020-01-12 23:44
Are you sure the attachments have been deleted? I doubt this behavior on wrong image is developed. Please try to reproduce on runbot. If so, indeed there's a chance of this to be corrected - at least the deletion part -.

**Comment by sciallo** [comment] 2020-01-12 23:50
Screenshots were from runbot .... Sorry I broke it :-p
http://3403223-12-0-8a529f.runbot3.odoo-community.org/web
I'm doing more experimenting on my own server, it looks like the actual files are gone from the filestore too!

**Comment by pedrobaeza** [comment] 2020-01-12 23:56
OK, reopening. @ged-odoo maybe something to see on your side.

**Comment by C3POdoo** [comment] 2023-03-30 11:44
Dear @sciallo,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._

**Closed by C3POdoo** 2023-03-30 11:44 UTC
Labels: Framework, 12.0
