### ISSUE TITLE
[8.0] Sale order line is not added to tree view until the sale order saved

### ISSUE THREAD

**Issue by levkar** [odoo/odoo#10241] opened 2015-12-30 17:49 UTC
when sale order line is added with form view, when line is saved it is not added as a new line. it is shown when sale order is saved. can be easily regenerated in runbot.

Impacted versions:

 - 8.0

Steps to reproduce:

 1. create a new sale order
 2. add a line with form view (not tree view)
 3. save sale order line form

Current behavior:

 - Saved line is not shown

Expected behavior:

 - Saved line is added to tree view

**Comment by raycarnes** [comment] 2015-12-31 02:03
There are two ways to save the SALE ORDER LINE form, and you didn't specify which one you used, so I tried both in a few combinations.

1. New order, add item, SAVE AND CLOSE - product added to treeview

2. New order, add item, SAVE AND NEW, add item, SAVE AND CLOSE - both products added to treeview.

3. New order, add item, SAVE AND NEW, add item, SAVE AND NEW, close (includes clicking DISCARD) without adding a product - no products added to treeview

So - this only happens for me if you click SAVE AND NEW, then close the form view (without adding a new product).

**Comment by stijnh92** [comment] 2015-12-31 08:18
Got the same issue with the latest version of Odoo 8.0.
Happens on all One2Many fields when adding new item via form view.

**Comment by levkar** [comment] 2015-12-31 08:25
go to runbot.odoo.com and click quick connect on 8.0 branch. click sales, sales orders, create, select a customer, click add an item, select product and click save & close button. your item is not on the list!

**Comment by qsm-odoo** [comment] 2015-12-31 09:21
Ok I understand the problem, this only appears when the o2m is empty at the beginning because when saving it goes trough page -1 because of the referenced commit. I will fix this.

**Comment by qsm-odoo** [comment] 2015-12-31 12:30
The issue is fixed with commit https://github.com/odoo/odoo/commit/94a1536ae146a7b3fa2129672665978a4842c5ef.
Thank you

**Closed by qsm-odoo** 2015-12-31 12:30 UTC
