### ISSUE TITLE
[9.0ce] Wrong Calendar Week Number

### ISSUE THREAD

**Issue by oliverzgy** [odoo/odoo#12068] opened 2016-05-17 07:55 UTC
Impacted versions: 9.0 CE
![_010](https://cloud.githubusercontent.com/assets/3712729/15315018/c5b8014e-1c47-11e6-9dfd-a1ee213687ac.png)
Wrong in English UI

![_009](https://cloud.githubusercontent.com/assets/3712729/15315022/cd22289c-1c47-11e6-9575-c59b21dc56d9.png)
Correct in Chinese UI

**Comment by Yenthe666** [comment] 2016-05-18 10:02
@mart-e this bug is indeed true. It is actually week 20 right now on most systems / calendars, not week 19 or 21.

**Comment by mart-e** [comment] 2016-05-18 10:06
Duplicate of #9629 (and it depends of the standard you are using, go for ISO week date
 !)

**Comment by Yenthe666** [comment] 2016-05-18 10:11
@mart-e the fact that at the top it shows `19` and lower on it shows `W21` is a bug that is not described in the other one though.

**Comment by mart-e** [comment] 2016-05-18 10:12
my bad, read too quickly

**Comment by Yenthe666** [comment] 2016-05-18 10:15
@mart-e thanks for re-opening this. Would love to see a confirmed label? :smile:

**Comment by Yenthe666** [comment] 2016-06-07 07:42
@JKE-be any update on this one?

**Comment by JKE-be** [comment] 2016-06-07 10:45
I'm ok that we need to use the same week computation for title and calendar view.

Now, for the IsoWeek or not, it is according to people / format lang / preference / ... anyway it can be easily customized with an override of get_fc_defaultOptions.

https://github.com/odoo/odoo/pull/11522 introduce this bug, because that change only the computation week and not the title. So I suggest to keep this fix #11522, and adjust the title to be coherent.

**Comment by Yenthe666** [comment] 2016-06-07 11:05
Sounds good to me, looks like a neat way to make it coherent.
Let me know when it is added in 9.0, then we can close this issue.

**Closed** 2016-06-07 12:10 UTC
Labels: confirmed
