### ISSUE TITLE
[11] Exporting Measure as Float Time to Excel

### ISSUE THREAD

**Issue by guidev224** [odoo/odoo#34214] opened 2019-06-18 13:01 UTC
Impacted versions: 11

Steps to reproduce:
1. Create some timesheets with quantity greater than 0
2. Go to timesheets reporting, choose by  project  for example
3. Download the table as xlsx

Current behavior:
Measures with float_time widget are exported as simple floats

Expected behavior:
Export measures with float_time widget as time to xlsx. Eg: **20:52** becomes **20.86** in excel file

Video/Screenshot link (optional):
**Odoo Pivot View**
![image](https://user-images.githubusercontent.com/31063466/59683952-9624ed80-91c8-11e9-84f0-7fddaf3d7a97.png)

**Pivot View Downloaded as Excel file**
![image](https://user-images.githubusercontent.com/31063466/59684089-e1d79700-91c8-11e9-8c8a-614ae0915e50.png)

**Comment by sswapnesh** [comment] 2019-06-18 16:56
Related to https://github.com/odoo/odoo/issues/22727

**Comment by pedrobaeza** [comment] 2019-06-18 17:16
I would say more duplicate of ##22727, so closing.

**Closed by pedrobaeza** 2019-06-18 17:16 UTC
