### ISSUE TITLE
Website, attachment selector give a `MemoryError` when a specific photo are in attachments

### ISSUE THREAD

**Issue by sebastienhasa** [odoo/odoo#34937] opened 2019-07-17 09:43 UTC
Impacted versions:

Odoo 11.0-20190128 (Community Edition) 

Steps to reproduce:

Create a web page, add the photo gallery snippet and import the photo
attached to this issue.

Attachment:
![IMG_0317](https://user-images.githubusercontent.com/48090545/61365429-04240980-a888-11e9-8e05-3644873f87ba.jpg)

Current behavior:

The photo is not add to the gallery but must important the gallery can
no longer show attachments already on the db of Odoo. Even If I close
the attachment selector and open it again. The only solution is to
remove the problematic photo from attachments.

When I invoke the attachment selector from the website page I got this
error in the log:
```
2019-07-17 09:13:01,725 63 INFO prod-fso werkzeug: 192.168.56.52 - - [17/Jul/2019 09:13:01] "POST /web/dataset/call_kw/ir.attachment/search_read HTTP/1.1" 200 -
2019-07-17 09:13:03,070 82 ERROR prod-fso odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 707, in dispatch
    return self._json_response(result)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 639, in _json_response
    body = json.dumps(response, default=ustr)
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
MemoryError
```

Expected behavior:

Attachment selector (from the website) showing attachments already on
the db of Odoo.

**Comment by pedrobaeza** [comment] 2019-07-17 12:08
But this seems because your system goes out of memory. Can it be? Can you do the photo a bit smaller?

**Comment by sebastienhasa** [comment] 2019-07-18 07:51
We are at 3.1 G on 16 G of ram and less than 25% of disk usage.

**Comment by rdeodoo** [comment] 2019-07-18 13:44
I tried to reproduce it on runbot 11.0, runbot 12.0, runbot master and 11.0 local instance and everything went fine with the image you provided, were you able to reproduce the error on runbot?

As @pedrobaeza suggested, it is probably something going wrong with your system.

Note that in Odoo 13.0 you will have the possibility to greatly optimize the picture you upload in the media dialog. I just give it a shot and uploading your image to a 1920px in 80% quality will reduce it from 3.5MB to 414kB.
On 11.0 and 12.0 the image is a bit optimized after upload (3.5 to 1.9MB). So you definitely should reduce the image before upload it for the sake of your visitors.

**Comment by sebastienhasa** [comment] 2019-07-19 09:58
@rdeodoo I got the same error with another photo and now I can import again the
two photos without error. And I cannot reproduce it. It seems to be an
intermittent error. 

I didn't have enough time to spend hours on this to try to reproduce
it. If it reproduce, what do you suggest to test to found the origin
of it and found if it's an Odoo or a system problem?

**Comment by rdeodoo** [comment] 2019-07-19 11:08
> If it reproduce, what do you suggest to test to found the origin of it and found if it's an Odoo or a system problem?

Well, I really don't think that is an Odoo problem as we always had people uploading big images (way bigger than yours) without any issue of that kind. That's actually why we improved the next version to allow the user to optimize their image sizes/weight.
It could be related to Odoo, but I am confident it is more related to your system.

If you find a way to reproduce it, you might want to investigate using `htop` and see what process is using the memory.

**Comment by rdeodoo** [comment] 2019-07-23 11:16
I don't think we can help much more here, I will close this one for now.

**Closed by rdeodoo** 2019-07-23 11:16 UTC
Labels: 11.0, Need information, Website
