### ISSUE TITLE
[12] document , not showing "attachment" menu

### ISSUE THREAD

**Issue by alrik88** [odoo/odoo#27760] opened 2018-10-14 07:18 UTC
A few days ago it worked on Odoo 12

Steps to reproduce:
- On Odoo Cloud and own installation (module name: "document") 
- Installing "document" APP
- https://hibou.io/casts/series/odoo-10-basics-1/lesson/attaching-documents-to-records-10

Current behavior:
Not showing Menu "attachment" next to print and action

Video/Screenshot link (screen from older odoo):
![dokumente 4](https://user-images.githubusercontent.com/44069871/46913660-f1e00c80-cf91-11e8-8136-db662eb91a93.jpg)

**Comment by pedrobaeza** [comment] 2018-10-15 08:36
@sswapnesh I don't see that button nor the possibility to freely add an attachment. Do you?

**Comment by sswapnesh** [comment] 2018-10-15 14:04
@pedrobaeza I didn't find one but we can add through Log option in chatter or Manage attachments from debug actions.

**Comment by pedrobaeza** [comment] 2018-10-15 14:45
Yeah, but it's not very clean...

@ThanhDodeurOdoo do you know if this is now the official way of adding attachments to a record?

**Comment by pedrobaeza** [comment] 2018-10-15 16:33
Thanks for the confirmation @ThanhDodeurOdoo. It seems a bit uglier now being forced to log a message for attaching something (and going to debug technical menu is not a solution for the user), but if it's the only way to go...

Closing this then as not an issue, but intended behavior.

**Closed by pedrobaeza** 2018-10-15 16:33 UTC

**Comment by Yenthe666** [comment] 2018-10-15 17:09
Hmm I remember discussing this one with Fabien. Fabien his rationale was that it shouldn't have been added/created like this in the first place. He was not a fan of the menu at the top. I genuinely liked it. Clear & easy to check but I guess we'll have to get used to it 😉

**Comment by Yenthe666** [comment] 2018-10-15 17:37
Yeah you don't have to convince me to that. @fpodoo & @antonylesuisse can't we come with a more elegant way to show and handle attachments though? 🙏

**Comment by Axel-G** [comment] 2018-10-15 18:11
i see no possibility to delete a attachment in the chatter.

**Comment by sswapnesh** [comment] 2018-10-15 18:14
You have to do it from "Manage Attachments" from Debug mode action.

**Comment by Axel-G** [comment] 2018-10-15 18:17
debug mode menu is  not a solution ...  users should not debug odoo, they should use it ;)

**Comment by nhomar** [comment] 2018-10-15 18:32
Attachments are becoming part of the flow of the record, then I think remove them is a technical feature and not a functional one +1 for this.

In l10_mx we did some tricks to avoid the deletion of attachments even, this way is better on my opinion, but the list of attachments should be available BTW.

I thinks that's the intention then.

**Comment by sswapnesh** [comment] 2018-10-15 18:38
Agree With @nhomar , +1
There should be easy way to View Attachments and Add Attachment.

**Comment by CasVissers** [comment] 2018-10-17 10:57
Agree with @Yenthe666 this solution is not user friendly. I would suggest to maybe an "add attachment" button or something like this.

**Comment by Axel-G** [comment] 2018-10-17 12:34
i test the last day the new workflow and without possibiltiy to delete attachments its a hard break in the workflow to the lesser releases. We attach a lot of documents and its dangerous to use the wrong document (for example pricelists, technical sheets)

**Comment by Axel-G** [comment] 2018-10-22 20:12
A other issue is: for example we attach the bank statements to the bank record. this have no chatter and so you cant in v12 attach a file. in v11 you can attach to every record a file with the top menü :-(

**Comment by Saphar** [comment] 2018-12-13 17:13
If I try to create a new attachment with the Manage attachment menu the Resource Name is empty and it doesn't create the attachment. How can I fix this?

**Comment by ThanhDodeurOdoo** [comment] 2018-12-14 08:10
@Saphar Hello, It is because the action doesn't have a context key with default_res_model and default_res_id, I made a fix for 12.0;

On the same topic, the attachment menu of the "sidebar" is completely removed in 12.1 and the chatter's attachment button is being improved allow deleting and direct upload of attachments.

**Comment by ray-odoo** [comment] 2019-02-05 17:18
I don't see this information shared here, so am adding it:

Screenshots taken today from v12 CE:

View Attachments:

![](https://i.imgur.com/t1RS6QA.png)


Add Attachment without using Chatter:

![](https://i.imgur.com/l3J8OJH.png)


Add Attachment using Chatter:

![](https://i.imgur.com/V19codr.png)

Delete Attachment:

![](https://i.imgur.com/EddfNyI.png)

**Comment by sswapnesh** [comment] 2019-02-05 17:21
This has been added from PR https://github.com/odoo/odoo/pull/30636

**Comment by pedrobaeza** [comment] 2019-02-05 17:24
That's great! Thanks for sharing

**Comment by bealdav** [comment] 2019-02-06 07:32
> Add Attachment without using Chatter:

Yes, but chatter is required even in this case #paradox

**Comment by pedrobaeza** [comment] 2019-02-06 08:11
> Yes, but chatter is required even in this case

Although true, it's a minor problem, don't you think?

**Comment by Axel-G** [comment] 2019-02-06 09:00
> > Yes, but chatter is required even in this case
> 
> Although true, it's a minor problem, don't you think?

In my case its a big problem: We use attachments in many cases e. g. accounting to attach bank statements. That are records without chatter. No chatter -  no attachment. With the old system no problem. Thats why i use https://apps.odoo.com/apps/modules/12.0/document_sidebar/

**Comment by pedrobaeza** [comment] 2019-02-06 09:03
OK, you can always recreate the "feature" with community modules. Take into account that this specific module generates extra queries for getting that information. On the case you mention, I would prefer a community module that adds the chatter to these objects, and promote that Odoo includes the chatter in this objects for future versions (it the are not yet).

**Comment by ray-odoo** [comment] 2019-02-06 17:09
@Axel-G - In case you didn't know, the bank.statement model has support for Chatter, it just doesn't have the DIV in the Form View.

Just add:

```
<div class="oe_chatter">
    <field name="message_follower_ids" widget="mail_followers" groups="base.group_user"/>
    <field name="message_ids" widget="mail_thread"/>
 </div>
```

**Comment by sswapnesh** [comment] 2019-02-06 17:12
If it has already this information than I think we should consider this adding in form view in master.
