### ISSUE TITLE
(master) account: Cancelling Journal Entries could lead to weird results

### ISSUE THREAD

**Issue by hbto** [odoo/odoo#35841] opened 2019-08-20 10:54 UTC
(master) account: Cancelling Journal Entries could lead to weird results
=

Impacted versions:
-
master

Steps to reproduce:
-
- Set Multi-currency environment
<img width="687" alt="Screen Shot 2019-08-20 at 5 14 28 AM" src="https://user-images.githubusercontent.com/7598010/63338928-6948a000-c309-11e9-8b2e-8df57f990590.png">

- Set three currency rates for EUR.
<img width="837" alt="Screen Shot 2019-08-20 at 5 15 44 AM" src="https://user-images.githubusercontent.com/7598010/63339027-97c67b00-c309-11e9-9346-307022ea991a.png">

- Create a Vendor Bill in EUR
<img width="1173" alt="Screen Shot 2019-08-20 at 5 18 02 AM" src="https://user-images.githubusercontent.com/7598010/63339300-34891880-c30a-11e9-987a-08bfd7a167f6.png">

- Make a Partial Payment in EUR.
<img width="1077" alt="Screen Shot 2019-08-20 at 5 19 34 AM" src="https://user-images.githubusercontent.com/7598010/63339310-394dcc80-c30a-11e9-84b7-791ddb95c75b.png">

- Make a Partial Payment to fully pay the invoice in EUR
<img width="1077" alt="Screen Shot 2019-08-20 at 5 20 06 AM" src="https://user-images.githubusercontent.com/7598010/63339321-3eab1700-c30a-11e9-8b8a-f4af4c447283.png">

- Review the Journal Entries Created
<img width="1060" alt="Screen Shot 2019-08-20 at 5 22 07 AM" src="https://user-images.githubusercontent.com/7598010/63339458-8d58b100-c30a-11e9-869e-b654ea98eede.png">

- Review the Journal Items.

<img width="1265" alt="Screen Shot 2019-08-20 at 5 27 39 AM" src="https://user-images.githubusercontent.com/7598010/63339842-62229180-c30b-11e9-874f-afdd46003ca6.png">

- Review the P&L Report.
<img width="1060" alt="Screen Shot 2019-08-20 at 5 22 35 AM" src="https://user-images.githubusercontent.com/7598010/63339465-90ec3800-c30a-11e9-8e39-2b62e5a97108.png">

- Install `account_cancel` 
<img width="720" alt="Screen Shot 2019-08-20 at 5 24 08 AM" src="https://user-images.githubusercontent.com/7598010/63339557-c2fd9a00-c30a-11e9-8ff7-bf5a7f21d78a.png">

- Set FX Journal to Allow Cancellation of Journal Entries.
<img width="546" alt="Screen Shot 2019-08-20 at 5 25 15 AM" src="https://user-images.githubusercontent.com/7598010/63339653-fa6c4680-c30a-11e9-82fa-b96f0c98a85d.png">

- Cancel the FX Journal Entry.

<img width="1265" alt="Screen Shot 2019-08-20 at 5 30 19 AM" src="https://user-images.githubusercontent.com/7598010/63339982-ad3ca480-c30b-11e9-834d-878300b2a406.png">

<img width="1265" alt="Screen Shot 2019-08-20 at 5 31 24 AM" src="https://user-images.githubusercontent.com/7598010/63340065-cfcebd80-c30b-11e9-873e-1adad0738fab.png">

- Review the P&L Report.
<img width="1265" alt="Screen Shot 2019-08-20 at 5 32 18 AM" src="https://user-images.githubusercontent.com/7598010/63340112-eb39c880-c30b-11e9-8a08-59c3a15f41ff.png">

Instead of US$402.50 now we have  US$-402.50 in Gains/Losses

- Let us review Journal Entries. A new Journal Entries reversal - of the just cancelled Journal Entry - was created.

<img width="1265" alt="Screen Shot 2019-08-20 at 5 35 44 AM" src="https://user-images.githubusercontent.com/7598010/63340349-6f8c4b80-c30c-11e9-8b5f-f9ed1065e6e2.png">

- Let us review Journal Items. We can see that previous Matching Reconciliation is no more. And a new reconciliation was create between the cancelled journal item and the newly created reversal 
<img width="1265" alt="Screen Shot 2019-08-20 at 5 38 20 AM" src="https://user-images.githubusercontent.com/7598010/63340485-c72ab700-c30c-11e9-8e09-006d9f7a4caf.png">

Current behavior:
=

- Cancelation of Journal Entries, with reversal are skewing the reports. 
- P&L and other reports do not include cancelled Journal Entries.
- Reversed Journal Entries is to cancel out the Journal Entry being reversed but when both are kept outsanding.

Expected behavior:

A debate on how to fix this issue.

Regards

**Comment by nhomar** [comment] 2019-08-20 18:02
@smetl

**Comment by smetl** [comment] 2019-08-28 07:32
In my opinion, it's not a bug. You are free to cancel what you want like exchange difference entries. Cancelled journal entries are not show up in any reports, it's the expected behaviour.

**Comment by smetl** [comment] 2019-09-03 13:19
Fixed on saas-12.4

**Closed by smetl** 2019-09-03 13:19 UTC
Labels: Accounting
