### ISSUE TITLE
paypal never works always give "A system error has occurred. Try later. "

### ISSUE THREAD

**Issue by ser-tec** [odoo/odoo#113283] opened 2023-02-21 15:35 UTC
Impacted versions: 
16

Steps to reproduce: 
try to make a payment with paypal

Current behavior:
it opens paypal page with "A system error has occurred. Try later. "

Expected behavior:
let me pay with paypal

LOG : 
2023-02-21 15:27:18,938 1451 INFO database1 odoo.addons.payment.models.payment_transaction: generic and provider-specific processing values for transaction with reference S00015-2:
{'amount': 18.3,
 'currency_id': 1,
 'partner_id': 2116,
 'provider_code': 'paypal',
 'provider_id': 10,
 'reference': 'S00015-2'}
2023-02-21 15:27:18,939 1451 INFO database1 odoo.addons.payment.models.payment_transaction: provider-specific rendering values for transaction with reference S00015-2:
{'address1': 'via roma',
 'amount': 18.3,
 'api_url': 'https://www.paypal.com/cgi-bin/webscr',
 'business': 'store@mywebsite.com',
 'city': 'roncade',
 'country': 'IT',
 'currency_code': 'EUR',
 'email': 'customer@gmail.com',
 'first_name': 'customer',
 'handling': 1.01,
 'item_name': 'company s.p.a.: S00015-2',
 'item_number': 'S00015-2',
 'last_name': 'customer',
 'lc': 'it_IT',
 'notify_url': 'https://odoo.mywebsite.com/payment/paypal/webhook/',
 'return_url': 'https://odoo.mywebsite.com/payment/paypal/return/',
 'state': 'Treviso',
 'zip_code': '31056'}
2023-02-21 15:27:18,949 1451 INFO database1 werkzeug: 172.71.114.122 - - [21/Feb/2023 15:27:18] "POST /my/orders/15/transaction?access_token=REPLACETOKENFORSENSITIVEINFORMATION HTTP/1.0" 200 - 47 0.010 0.054
2023-02-21 15:27:52,593 1466 INFO database1 odoo.addons.base.models.ir_cron: Starting job `payment: post-process transactions`.
2023-02-21 15:27:52,595 1466 INFO database1 odoo.addons.base.models.ir_cron: Job `payment: post-process transactions` done.
2023-02-21 15:27:52,602 1466 INFO database1 odoo.addons.base.models.ir_cron: Starting job `Mail: Fetchmail Service`.

* i replace transaction?access_token i don't know if is a sensitive information 
* also i replace my website url and paypal and customer email 

Thanks

**Comment by AbdelAzizMohamedMousa** [comment] 2023-02-23 16:09
Based on the log you provided, it seems like the error is coming from PayPal's side. It is possible that there is a temporary issue with PayPal's service or API, causing the system error.

You can try the following steps to resolve the issue:

Wait for a while and try again later to see if the issue persists.
Contact PayPal customer support to check if there are any issues with your account or payment settings.
Check if there are any updates or patches available for the PayPal payment module in your Odoo installation and apply them if necessary.
If none of these steps work, you may want to consider using an alternative payment method until the issue with PayPal is resolved.

**Comment by Tradeforlife** [comment] 2023-04-04 23:19
I've getting the same error, was there a fix to this? @ser-tec

**Comment by ser-tec** [comment] 2023-04-06 11:24
I solved using stripe, not a real solution. 
Maybe with paypal sandbox you can understand where is the problem but i haven't had time to try yet. I believe there is a required parameter that is not being passed

**Comment by vava-odoo** [comment] 2023-04-07 17:01
Hi @ser-tec & @Tradeforlife 

Is the problem still there? We were not able to reproduce on runbot 16.

Anyway, there was no change in Odoo that seems to be responsible for such an issue. So it may be on Paypal side.

Regards,

**Comment by vava-odoo** [comment] 2023-04-24 14:47
I close the issue. If the problem is still there and you have more information to provide, please re-open

**Closed by vava-odoo** 2023-04-24 14:47 UTC
Labels: Payment, 16.0
