### ISSUE TITLE
Download problem by IDM

### ISSUE THREAD

**Issue by saeed-raeisi** [odoo/odoo#73931] opened 2021-07-17 07:35 UTC
Impacted versions:
**14**
=======================
Steps to reproduce:
**sales -> quotation -> print**
=======================
Current behavior:
**Error:
undefined**
=======================
Expected behavior:
**print !**
=======================
Video/Screenshot link (optional):
[video](https://streamable.com/tdtbou)

When **IDM**(Internet Download manager) is enable -> print(https://wkhtmltopdf.org/) have error
Disabling _idm_ **solves** the problem.
[idm](https://www.internetdownloadmanager.com/)
[wkhtmltopdf](https://wkhtmltopdf.org/)

Support ticket number submitted via odoo.com/help (optional):

**Comment by miladsadeghi1376** [comment] 2021-07-17 07:44
![image](https://user-images.githubusercontent.com/45930406/126030034-ca6527ff-bd14-4caf-9fd4-c34f680c87d9.png)

**Comment by miladsadeghi1376** [comment] 2021-07-17 07:45
![image](https://user-images.githubusercontent.com/45930406/126030074-12dc229d-a481-4876-82e7-990c1b6137bf.png)

**Comment by pedrobaeza** [comment] 2021-07-18 08:17
Sorry, but the problem is caused by external agents, and you should remove such things, or report it to that part, not to Odoo.

Closing this as no Odoo code issue.

**Closed by pedrobaeza** 2021-07-18 08:17 UTC

**Comment by saeed-raeisi** [comment] 2021-07-18 10:24
The error is related to odoo
Cannot check that the download has been transferred to another application

Is there a way to prevent the transfer?
Delete the popular IDM program from the system or change the settings ?!

**Comment by miladsadeghi1376** [comment] 2021-07-18 10:28
Thanks for your relentless pursuit, at least provide a solution to this problem
 Thank you

**Comment by saeed-raeisi** [comment] 2021-07-19 04:59
The way ->->

odoo/addons/base/models/ir_actions_report.py =>

>  def _render_qweb_pdf -> def _post_pdf

addons/web/controller/main.py ->def **report_routes** =>

>  converter ='pdf' -> **report_download** -> @http.route(['/report/download'], type='http', auth="user")

addons/web/static/src/js/chrome/action/manager_report.js =>

>  _downloadReport -> error =>

```
self.call('crash_manager', 'rpc_error', error);
reject();
```
