### ISSUE TITLE
IE 11 Odoo client error on latest update

### ISSUE THREAD

**Issue by ausl** [odoo/odoo#10257] opened 2015-12-31 20:16 UTC
Much appreciated if anyone can help.

Unable to get property 'permission' of undefined or null reference
http://192.168.0.11:8069/web/content/336-7790abc/web.assets_backend.js:4343
Traceback:
TypeError: Unable to get property 'permission' of undefined or null reference
   at init (http://192.168.0.11:8069/web/content/336-7790abc/web.assets_backend.js:4343:3736)
   at Anonymous function (http://192.168.0.11:8069/web/content/333-6df9be4/web.assets_common.js:2532:548)
   at Class (http://192.168.0.11:8069/web/content/333-6df9be4/web.assets_common.js:2533:47)
   at widget (http://192.168.0.11:8069/web/content/336-7790abc/web.assets_backend.js:3128:50)
   at Anonymous function (http://192.168.0.11:8069/web/content/336-7790abc/web.assets_backend.js:3125:158)
   at Anonymous function (http://192.168.0.11:8069/web/content/333-6df9be4/web.assets_common.js:650:661)
   at fire (http://192.168.0.11:8069/web/content/333-6df9be4/web.assets_common.js:644:278)
   at self.add (http://192.168.0.11:8069/web/content/333-6df9be4/web.assets_common.js:645:467)
   at Anonymous function (http://192.168.0.11:8069/web/content/333-6df9be4/web.assets_common.js:650:631)
   at each (http://192.168.0.11:8069/web/content/333-6df9be4/web.assets_common.js:473:752)

**Comment by paulinxe** [comment] 2016-01-08 11:04
same here

**Comment by alqfahad** [comment] 2016-03-01 12:51
I got the same error

**Comment by Yenthe666** [comment] 2016-06-15 10:03
Hi @ausl,

I can no longer reproduce this on IE 11 with the latest Odoo code.
On a sidenote: please add more information on your next reports, we have no idea where this bug is or how it is reproduced.
Closing this since I'm missing more information and since I cannot reproduce it anymore.

Regards,
Yenthe

**Closed by Yenthe666** 2016-06-15 10:03 UTC
