### ISSUE TITLE
Kanban Priority Widget does not respect readonly attribute

### ISSUE THREAD

**Issue by Josh95LeanEasy** [odoo/odoo#67580] opened 2021-03-10 10:55 UTC
Impacted versions:
14.0
Steps to reproduce:
Make a Kanban view with the priority widget and set it to readonly
Current behavior:
Hovering over the stars changes them and clicking them changes the value of the field
Expected behavior:
Hovering and clicking on the stars should not do anything, field should be read only
Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by Yenthe666** [comment] 2021-03-10 14:24
Duplicate of https://github.com/odoo/odoo/issues/65240 and https://github.com/odoo/odoo/issues/40641

**Closed by Yenthe666** 2021-03-10 14:24 UTC
