### ISSUE TITLE
[9.0][BUG] Stock operation couldn't be generated

### ISSUE THREAD

**Issue by Zhouhao12345** [odoo/odoo#18503] opened 2017-07-28 03:10 UTC
Impacted versions:
-Working with Odoo 9

Steps to reproduce:
1. Inventory--->Configuration-->Units of Measure-->Click record 'Unit(s)'-->set 'Rounding Precision' to 0.00000
2. Inventory--->Dashboard-->Receipts-->Create incoming order with any products-->Mark as Todo

Current behavior:
1. No stock operation will be generated from specific stock move.
2. Incoming order, which was already generate stock operation but hasn't be validated, will fall in endless while loop waiting of https://github.com/odoo/odoo/blob/9.0/addons/stock/stock.py 1408 line, when click 'Validate' Button after above setting. It may cause overload of server CPU. 

Expected behavior:

1. Avoid user to set 'Rounding Precision' to 0.00000
2. Set the steps counting for this while loop

**Comment by sle-odoo** [comment] 2018-02-06 21:07
Hi,
Sorry but it is not a bug, just another way to shoot yourself in the foot with a wrong configuraiton. I'm noting the feedback to improve the robustness and it may lead to a commit sometimes but i'm closing the issue.

Hope you understand,
Regards

**Closed by sle-odoo** 2018-02-06 21:07 UTC
Labels: 9.0, Logistics
