### ISSUE TITLE
Odoo package list 

### ISSUE THREAD

**Issue by iman-alhaddar** [odoo/odoo#68957] opened 2021-04-08 12:17 UTC
Impacted versions: 13.0

Steps to reproduce: Go to Inventory> then master data> then packages.

Current behavior: We will find that there is no data except for the (Company , Owner, Location, and the content which is Product, L/S number , quantity, unit of measure).

Expected behavior: We want to define more info like to add the gross and net weight and we need to print all the report in QR code instead of barcode.

If there is any module can help please inform me.
Thanks,

**Comment by Yenthe666** [comment] 2021-04-08 13:09
Hi,

Sorry but this is out of scope for the issue track. This is about custom module and not a bug :)
Please ask it on the official help forums at https://www.odoo.com/forum/help-1 or have a look on the appstore at apps.odoo.com.

Regards,
Yenthe

**Closed by Yenthe666** 2021-04-08 13:09 UTC

**Comment by AsmaAl-Haddar** [comment] 2021-04-08 13:29
I said if there is a module but maybe there is something I should activate I need to know this and thanks
