### ISSUE TITLE
 Kanban view remove default grouping condition invalid

### ISSUE THREAD

**Issue by liweijie0812** [odoo/odoo#45405] opened 2020-02-14 14:15 UTC
Impacted versions:
13.0
Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):
https://youtu.be/_RQTmSMscGc

**Comment by sswapnesh** [comment] 2020-02-14 17:18
Duplicate of https://github.com/odoo/odoo/issues/44906

**Comment by pedrobaeza** [comment] 2020-02-14 17:24
Closing then

**Closed by pedrobaeza** 2020-02-14 17:24 UTC
