### ISSUE TITLE
[12] cannot add lines to PO after confirming

### ISSUE THREAD

**Issue by gr22** [odoo/odoo#31724] opened 2019-03-10 11:23 UTC
If I create and confirm a PO later on I cannot unlock and add more lines. 
It fails with:
`odoo.sql_db: bad query: b'INSERT INTO "purchase_order_line" ("id", "create_uid", "create_date", "write_uid", "write_date", "account_analytic_id", "date_planned", "name", "order_id", "price_unit", "product_id", "product_qty", "sequence", "state") VALUES (nextval(\'purchase_order_line_id_seq\'), 2, (now() at time zone \'UTC\'), 2, (now() at time zone \'UTC\'), NULL, \'2019-03-11 11:09:28\', \'Cane Sugar, organic\', 41, \'3.92\', 291, \'25.000\', 11, \'purchase\') RETURNING id'
ERROR: null value in column "product_uom" violates not-null constraint`

As you can see it tries to create a new line not supplying product_uom which is mandatory
The same happens when trying to add more lines to Manufactoring Order

**Comment by pedrobaeza** [comment] 2019-03-10 15:35
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by gr22** [comment] 2019-03-10 15:41
Quick test does not show the issue on runbot.
I noticed the problem after updating the other day to v. 12.0.20190307
Which is the version runbot runs with?

**Comment by pedrobaeza** [comment] 2019-03-10 15:44
If you pick the latest one, then the latest code ;)

**Comment by pedrobaeza** [comment] 2019-03-10 15:45
Try to update your own code to the latest one to see.

**Comment by gr22** [comment] 2019-03-10 16:06
Updated but same results.

What I do is this:
1. Create a PO and confirm it.
2. Edit again add a product and save

> The operation cannot be completed, probably due to the following:
> - deletion: you may be trying to delete a record while other records still reference it
> - creation/update: a mandatory field is not correctly set
> 
> [object with reference: product_uom - product.uom]

the traceback shows:

```
Server application error {"code":200,"data":{"arguments":["The operation cannot be completed, probably due to the following:
- deletion: you may be trying to delete a record while other records still reference it
- creation/update: a mandatory field is not correctly set

[object with reference: product_uom - product.uom]",null],"name":"odoo.exceptions.ValidationError","debug":"Traceback (most recent call last):
  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 939, in __call__
    return self.method(*args, **kw)
  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 517, in response_wrap
    response = f(*args, **kw)
  File \"/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py\", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File \"/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py\", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File \"/usr/lib/python3/dist-packages/odoo/addons/purchase_stock/models/purchase.py\", line 69, in write
    res = super(PurchaseOrder, self).write(vals)
  File \"/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py\", line 322, in write
    result = super(MailThread, self).write(values)
  File \"/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_activity.py\", line 575, in write
    return super(MailActivityMixin, self).write(vals)
  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 3284, in write
    self._write(store_vals)
  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 3424, in _write
    field.write(other, vals[field.name])
  File \"/usr/lib/python3/dist-packages/odoo/fields.py\", line 2522, in write
    flush()
  File \"/usr/lib/python3/dist-packages/odoo/fields.py\", line 2483, in flush
    comodel.create(vals_list)
  File \"<decorator-gen-271>\", line 2, in create
  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 433, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 433, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File \"/usr/lib/python3/dist-packages/odoo/addons/purchase_stock/models/purchase.py\", line 230, in create
    line = super(PurchaseOrderLine, self).create(values)
  File \"<decorator-gen-264>\", line 2, in create
  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 430, in _model_create_single
    return create(self, arg)
  File \"/usr/lib/python3/dist-packages/odoo/addons/purchase/models/purchase.py\", line 516, in create
    line = super(PurchaseOrderLine, self).create(values)
  File \"<decorator-gen-3>\", line 2, in create
  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 451, in _model_create_multi
    return create(self, [arg])
  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 3533, in create
    records = self._create(data_list)
  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 3633, in _create
    cr.execute(query, params)
  File \"/usr/lib/python3/dist-packages/odoo/sql_db.py\", line 148, in wrapper
    return f(self, *args, **kwargs)
  File \"/usr/lib/python3/dist-packages/odoo/sql_db.py\", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: null value in column \"product_uom\" violates not-null constraint
DETAIL:  Failing row contains (164, Baking soda (kg), 10, 1.000, null, 2019-03-11 15:52:59, null, 42, 4.69, null, null, null, 45, null, null, purchase, null, null, null, null, 2, 2019-03-10 15:59:08.20911, 2, 2019-03-10 15:59:08.20911, null, null).


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File \"/usr/lib/python3/dist-packages/odoo/tools/pycompat.py\", line 87, in reraise
    raise value
  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 696, in dispatch
    result = self._call_function(**self.params)
  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 139, in wrapper
    raise ValidationError(msg)
odoo.exceptions.ValidationError: ('The operation cannot be completed, probably due to the following:\
- deletion: you may be trying to delete a record while other records still reference it\
- creation/update: a mandatory field is not correctly set\
\
[object with reference: product_uom - product.uom]', None)
","exception_type":"validation_error","message":"The operation cannot be completed, probably due to the following:
- deletion: you may be trying to delete a record while other records still reference it
- creation/update: a mandatory field is not correctly set

[object with reference: product_uom - product.uom]
None"},"message":"Odoo Server Error"}
```
I have custom addons but the traceback does not reference them. Could it be that the upgrade I did (from december 2018 to March 2019) has changes which would require module upgrade (changed database fields or smth)?

**Comment by pedrobaeza** [comment] 2019-03-10 16:09
You can try to upgrade your whole database (or the base module) to see, but it seems your custom code is handling badly the thing, so this is not something about Odoo itself, and thus I'm closing this. I hope you find the root of the problem, but it's out of the scope of this issue tracker.

**Closed by pedrobaeza** 2019-03-10 16:09 UTC
Labels: 12.0, Logistics, Need information

**Comment by gr22** [comment] 2019-03-10 21:07
Just for the record: the problem was a custom view. At some point `force_save="1"` was added to the `product_uom` in _purchase_order_line_ and other views and it was missing in my custom view causing it to not be passed in the SQL query values during save.
