### ISSUE TITLE
TypeError: CleanCSS is not a function\A at Object.toCSS 

### ISSUE THREAD

**Issue by lsqtzj** [odoo/odoo#12209] opened 2016-05-29 19:07 UTC
TypeError: CleanCSS is not a function\A at Object.toCSS (/usr/lib/nodejs/less/lib/less/parser.js:620:32)\A at /usr/lib/nodejs/less/bin/lessc:357:32\A at Object.finish [as _finish] (/usr/lib/nodejs/less/lib/less/parser.js:669:28)\A at Object.subFinish [as _finish] (/usr/lib/nodejs/less/lib/less/import-visitor.js:63:47)\A at Object.subFinish [as _finish] (/usr/lib/nodejs/less/lib/less/import-visitor.js:63:47)\A at Object.subFinish [as _finish] (/usr/lib/nodejs/less/lib/less/import-visitor.js:63:47)\A at Object.tree.importVisitor.run (/usr/lib/nodejs/less/lib/less/import-visitor.js:25:22)\A at /usr/lib/nodejs/less/lib/less/import-visitor.js:72:38\A at fileParsedFunc (/usr/lib/nodejs/less/lib/less/parser.js:83:17)\A at /usr/lib/nodejs/less/lib/less/parser.js:106:29\A This error occured while compiling the bundle 'web.assets_backend' containing:\A - /website/static/src/less/import_bootstrap.less\A - /web/static/src/less/variables.less\A - /web/static/src/less/enterprise_compatibility.less\A - /web/static/src/less/utils.less\A - /web/static/src/less/modal.less\A - /web/static/src/less/notification.less\A - /base_import/static/src/less/import.less\A - /web_tip/static/src/less/tip.less\A - /web_calendar/static/src/less/web_calendar.less\A - /web_diagram/static/src/less/diagram_view.less\A - /web_kanban/static/src/less/kanban_dashboard.less\A - /web_kanban/static/src/less/kanban_view.less\A - /web_settings_dashboard/static/src/less/dashboard.l

**Comment by Yenthe666** [comment] 2016-05-30 05:49
Hi @lsqtzj,

We really need a bit more information to handle this report. Can you please provide us with steps about how to trigger this error, the full stacktrace and which Odoo version you've used? This is just a part of it.
Can you reproduce this issue on the latest runbot?

Regards,
Yenthe

**Comment by Yenthe666** [comment] 2016-06-06 13:51
@sle-odoo I just got this issue on a live server too, with the latest installation (which is from the Odoo source code of today).
The issue seems to happen when you install a new module. Every once in a while the lessc seems to invalidate throwing up lots of issues.

**Comment by sle-odoo** [comment] 2016-06-06 14:11
When you install a module, the bundle may be invalidated. You have this error because your installation is not correct, which is the case by default with the latest ubuntu and debian stable. Uninstall the system packages and install lessc and clean-css with npm at the moment.

**Comment by sle-odoo** [comment] 2016-06-06 14:12
duplicate of #9113

**Closed by sle-odoo** 2016-06-06 14:12 UTC

**Comment by Yenthe666** [comment] 2016-06-06 14:21
@sle-odoo what exactly do you mean with:

> You have this error because your installation is not correct, which is the case by default with the latest ubuntu and debian stable. Uninstall the system packages and install lessc and clean-css with npm at the moment.

Are you literally saying that all default Ubuntu and debian installations are incorrect regarding `lessc` and `clean-css` installations? I've seen numerous of reports and issues about this.

**Comment by sle-odoo** [comment] 2016-06-06 14:24
yes, debian jessie broke the clean-css package when upgrading the lessc one.

**Comment by ToonMeynen** [comment] 2017-11-07 10:38
workarround 
```
unlink /usr/bin/lessc
ln -s /usr/bin/lessc /usr/lib/node_modules/less/bin/lessc
```
