### ISSUE TITLE
M1 chip of macbook can't run odoo

### ISSUE THREAD

**Issue by srekal** [odoo/odoo#79221] opened 2021-10-30 18:11 UTC
i am trying use pycharm CE in M1 chip of macbook to running odoo,but  i failed!
problem1.  File "/odoo/service/server.py", line 83, in set_limit_memory_hard
    resource.setrlimit(rlimit, (config['limit_memory_hard'], hard))
ValueError: current limit exceeds maximum limit

<img width="613" alt="WX20211031-020425@2x" src="https://user-images.githubusercontent.com/20722306/139552031-a8f8238e-11f6-4ccc-8dd9-988f37c11053.png">
**i resolve this error by  ‘pass’** 
but when i create database i got an other problem.
 problem2.  File "/odoo/addons/web/controllers/main.py", line 457, in web_client
    context = request.env['ir.http'].webclient_rendering_context()
AttributeError: 'ir.http' object has no attribute 'webclient_rendering_context' - - -
**i got the same errors odoo12 version and odoo14 version,**

**Comment by KangOl** [comment] 2021-10-30 22:19
Duplicate of #79112

**Closed** 2021-10-30 22:19 UTC
