### ISSUE TITLE
cannot delete content of fields description for quotations, description for vendors, description for pickings

### ISSUE THREAD

**Issue by rgeromegnace** [odoo/odoo#12223] opened 2016-05-30 13:37 UTC
**Impacted versions:**
9

**Steps to reproduce:**
Create a new article

Set content in Note sheet in "description for quotations, description for vendors, description for pickings"

**Current behavior:**
When we update the new article in order to remove the description, if we save the article the description is always displayed

**Expected behavior:**
When we update the new article in order to remove the description, if we save the article we should have no more description.

**Video/Screenshot link (optional):**

**Comment by Yenthe666** [comment] 2016-06-07 07:10
Hi @rgeromegnace,

Do you mean that if you create a product with a warning and then change the type from Warning to none that the value is still in the field?
Product with warning:
![image](https://cloud.githubusercontent.com/assets/6352350/15848834/74893a9c-2c8f-11e6-88b2-4f5ee6691fdf.png)

Setting the warning off in the product view:
![image](https://cloud.githubusercontent.com/assets/6352350/15848860/9e493c06-2c8f-11e6-884e-f570ac3f566e.png)

Are you talking about the fact that the warning is still shown, despite picking the choice 'No Message'?

**Comment by rgeromegnace** [comment] 2016-06-07 09:51
Hello,

My product screen is not like yours. My problem appear in « Note » sheet. I have no « Warnings » sheet in my Odoo version.
I use Odoo 9.

Regards,
Le 7 juin 2016 à 03:11, Yenthe <notifications@github.com<mailto:notifications@github.com>> a écrit :


Hi @rgeromegnace<https://github.com/rgeromegnace>,

Do you mean that if you create a product with a warning and then change the type from Warning to none that the value is still in the field?
Product with warning:
[image]<https://cloud.githubusercontent.com/assets/6352350/15848834/74893a9c-2c8f-11e6-88b2-4f5ee6691fdf.png>

Setting the warning off in the product view:
[image]<https://cloud.githubusercontent.com/assets/6352350/15848860/9e493c06-2c8f-11e6-884e-f570ac3f566e.png>

Are you talking about the fact that the warning is still shown, despite picking the choice 'No Message'?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/odoo/odoo/issues/12223#issuecomment-224198493>, or mute the thread<https://github.com/notifications/unsubscribe/ANl8YDCnKH2CjKTnSgD-Qbol3SSAJlteks5qJRmWgaJpZM4Ipzfj>.




Régis GEROMEGNACE
Ingénieur Développement [cid:image35f284.PNG@e302b4e5.4fa9ac8a]
www.digitom.fr <http://www.digitom.fr>
<mailto:e.phelip@digitom.fr>r.geromegnace@digitom.fr<mailto:r.geromegnace@digitom.fr>
 -

**Comment by Yenthe666** [comment] 2016-06-07 10:03
@rgeromegnace can you post a screenshot of your screen here please? It is hard to find an issue if you have little details.

**Comment by rgeromegnace** [comment] 2016-06-07 10:15
[cid:FB0F78F6-1463-460B-8C23-95498F0B9022@home]
Le 7 juin 2016 à 06:04, Yenthe <notifications@github.com<mailto:notifications@github.com>> a écrit :


@rgeromegnace<https://github.com/rgeromegnace> can you post a screenshot of your screen here please? It is hard to find an issue if you have little details.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/odoo/odoo/issues/12223#issuecomment-224235947>, or mute the thread<https://github.com/notifications/unsubscribe/ANl8YEomFnM5omPfYs4fnXj44JyTCWWSks5qJUIygaJpZM4Ipzfj>.




Régis GEROMEGNACE
Ingénieur Développement [cid:image8bc2fb.PNG@a568cea7.459058b3]
www.digitom.fr <http://www.digitom.fr>
<mailto:e.phelip@digitom.fr>r.geromegnace@digitom.fr<mailto:r.geromegnace@digitom.fr>
 -

**Comment by pedrobaeza** [comment] 2018-04-24 07:39
This is a know issue due to the way translations work, as there's no way of differentiating a missing translation (and then it should be used the original term) and an empty translation. You have to put an space and the content will be erased.

Closing as there's no other solution by design.

**Closed by pedrobaeza** 2018-04-24 07:39 UTC
Labels: 9.0
