### ISSUE TITLE
error in odoo v11 timesheet costume module "message_follower_ids" does not exist

### ISSUE THREAD

**Issue by tusharwaghsailotech** [odoo/odoo#28318] opened 2018-10-31 12:47 UTC
Impacted versions:Odoo v11

Steps to reproduce:

Current behavior:error in odoo v11 timesheet costume module "message_follower_ids" does not exist.
Hi I have Inherited the account.analytic.line in my custom module and also inherited the
class AccountAnalyticLine(models.Model):
    _name='account.analytic.line'

    _inherit= ['account.analytic.line','mail.thread']

also added the dependencies in the manifest file
    "category": "Generic",
    "depends": ['mail','project','base'],
    "license": "AGPL-3", 

and XML code is is below 
</group>
          </xpath>
          </group>
          
          <xpath expr="//sheet"  position="after">
              <div class="oe_chatter">
                    <field name="message_follower_ids" widget="mail_followers"/>
                    <field name="message_ids" widget="mail_thread"/>
              </div>
          </xpath>
          
        </field>

but still getting an error message in windows server.
Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2018-10-31 16:37
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2018-10-31 16:37 UTC
