### ISSUE TITLE
Contacts (res.partner) access forbidden when when access portal document using Access token and without login

### ISSUE THREAD

**Issue by hareshkansara** [odoo/odoo#52198] opened 2020-05-29 22:01 UTC
Impacted versions:
Version-13 Community

Steps to reproduce:
First of all send any documents to any email address like create RFQ by going to Purchase > Create RFQ, click on "Send by email". 

So when user open email and click on provided link and open to browser (make sure you are not logged in with odoo), then you will get errors in terminal log for contact access forbidden

NOTE: I have checked in different databases like fresh DB with demo data and fresh DB without demo and without custom modules. So i think it's base bug.

Current behavior:
No any access rights provided when any documents access using access token and without login.

Expected behavior:
Need to add access rights such a way that user can access documents without contact forbidden error.

Video/Screenshot link (optional):
odoo.exceptions.AccessError: ('The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\n\n(Document type: "Contact" (res.partner), Operation: read)', None) - - -

**Comment by pedrobaeza** [comment] 2020-06-01 07:23
I'm not able to reproduce the problem in latest version. I send a mail with token and see the provided document (on sales). Can you please try with latest source code?

**Comment by hareshkansara** [comment] 2020-06-01 07:45
I have taken latest pull.
I have checked. We can access documents but in the terminal i got errors.






Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 304, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 292, in execute
    application_iter = app(environ, start_response)
  File "/home/hk/workspace/odoo/community/13.0/odoo/service/server.py", line 439, in app
    return self.app(e, s)
  File "/home/hk/workspace/odoo/community/13.0/odoo/service/wsgi_server.py", line 142, in application
    return application_unproxied(environ, start_response)
  File "/home/hk/workspace/odoo/community/13.0/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/home/hk/workspace/odoo/community/13.0/odoo/http.py", line 1287, in __call__
    return self.dispatch(environ, start_response)
  File "/home/hk/workspace/odoo/community/13.0/odoo/http.py", line 1257, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/middleware/shared_data.py", line 220, in __call__
    return self.app(environ, start_response)
  File "/home/hk/workspace/odoo/community/13.0/odoo/http.py", line 1457, in dispatch
    result = ir_http._dispatch()
  File "/home/hk/workspace/odoo/community/13.0/addons/website/models/ir_http.py", line 172, in _dispatch
    response = super(Http, cls)._dispatch()
  File "/home/hk/workspace/odoo/community/13.0/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "/home/hk/workspace/odoo/community/13.0/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/home/hk/workspace/odoo/community/13.0/addons/utm/models/ir_http.py", line 29, in _dispatch
    response = super(IrHttp, cls)._dispatch()
  File "/home/hk/workspace/odoo/community/13.0/addons/http_routing/models/ir_http.py", line 519, in _dispatch
    result = super(IrHttp, cls)._dispatch()
  File "/home/hk/workspace/odoo/community/13.0/odoo/addons/base/models/ir_http.py", line 233, in _dispatch
    return cls._handle_exception(e)
  File "/home/hk/workspace/odoo/community/13.0/addons/utm/models/ir_http.py", line 34, in _handle_exception
    response = super(IrHttp, cls)._handle_exception(exc)
  File "/home/hk/workspace/odoo/community/13.0/addons/http_routing/models/ir_http.py", line 610, in _handle_exception
    return super(IrHttp, cls)._handle_exception(exception)
  File "/home/hk/workspace/odoo/community/13.0/odoo/addons/base/models/ir_http.py", line 201, in _handle_exception
    return request._handle_exception(exception)
  File "/home/hk/workspace/odoo/community/13.0/odoo/http.py", line 750, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/home/hk/workspace/odoo/community/13.0/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/hk/workspace/odoo/community/13.0/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/home/hk/workspace/odoo/community/13.0/odoo/addons/base/models/ir_http.py", line 229, in _dispatch
    result = request.dispatch()
  File "/home/hk/workspace/odoo/community/13.0/odoo/http.py", line 809, in dispatch
    r = self._call_function(**self.params)
  File "/home/hk/workspace/odoo/community/13.0/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/hk/workspace/odoo/community/13.0/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/hk/workspace/odoo/community/13.0/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/hk/workspace/odoo/community/13.0/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/home/hk/workspace/odoo/community/13.0/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/hk/workspace/odoo/community/13.0/addons/web/controllers/main.py", line 1437, in content_image
    quality=int(kwargs.get('quality', 0)), access_token=access_token)
  File "/home/hk/workspace/odoo/community/13.0/addons/web/controllers/main.py", line 1446, in _content_image
    default_mimetype='image/png', access_token=access_token)
  File "/home/hk/workspace/odoo/community/13.0/addons/website/models/ir_http.py", line 336, in binary_content
    default_mimetype=default_mimetype, access_token=access_token)
  File "/home/hk/workspace/odoo/community/13.0/odoo/addons/base/models/ir_http.py", line 457, in binary_content
    default_mimetype='application/octet-stream')
  File "/home/hk/workspace/odoo/community/13.0/odoo/addons/base/models/ir_http.py", line 374, in _binary_record_content
    content = record[field] or ''
  File "/home/hk/workspace/odoo/community/13.0/odoo/models.py", line 5610, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/hk/workspace/odoo/community/13.0/odoo/fields.py", line 1005, in __get__
    record._fetch_field(self)
  File "/home/hk/workspace/odoo/community/13.0/odoo/models.py", line 2944, in _fetch_field
    self._read(fnames)
  File "/home/hk/workspace/odoo/community/13.0/odoo/models.py", line 3019, in _read
    self.check_access_rule('read')
  File "/home/hk/workspace/odoo/community/13.0/odoo/models.py", line 3238, in check_access_rule
    raise self.env['ir.rule']._make_access_error(operation, forbidden)
odoo.exceptions.AccessError: ('The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\n\n(Document type: "Contact" (res.partner), Operation: read)', None) - - -

**Comment by pedrobaeza** [comment] 2020-06-01 08:35
It seems you have some misconfiguration in the contacts permissions. Maybe bad multi-company assignations in the customer/salesman contact.

Any way, I have tried on my own and don't get this problem, so closing for now until further evidence is given.

**Closed by pedrobaeza** 2020-06-01 08:35 UTC
Labels: Need information
