### ISSUE TITLE
Reverse Transfer Issue [V8]

### ISSUE THREAD

**Issue by 7Eleven1995** [odoo/odoo#24021] opened 2018-04-04 02:20 UTC
Steps to reproduce:
1. I have a picking record (e.g. WH/IN/1127) and I'm going to return a specific product (e.g. T-Shirt) with 6 quantities.
2. I clicked on the [Reverse Transfer] button, and the pop up wizard appears. The quantity indicated for product T-shirt was 0 quantity, so I manually indicate 6 quantities. 
3. I clicked on the [Return] button and the system automatically created an outgoing picking record (e.g. WH/OUT/9047), in 'Waiting Availability' state. Once I clicked on the 'Check Availability', nothing happens.

Kindly explain why quantity indicated by the system was 0 when I did the reverse transfer.
To correct this, am I going to cancel the outgoing picking record and manually create a new one?

Note: There are 20 qty on-hand for the product T-shirt

**Comment by pedrobaeza** [comment] 2018-04-04 14:01
v8 is not supported anymore, and this is not a bug, but the reservation can't be done because the quants moved on that picking has been moved or reserved in another one.

I close this due to the reasons above.

**Closed by pedrobaeza** 2018-04-04 14:01 UTC
