### ISSUE TITLE
Odoo Client Error when Saving Notes

### ISSUE THREAD

**Issue by povi2946** [odoo/odoo#51733] opened 2020-05-23 16:30 UTC
Impacted versions:Odoo 13.0-20200523 (Community Edition) 

Steps to reproduce: Create A note and to to edit more to add more additional information then try to save it and error occures

Current behavior: After the error interface kinda freezes.. other buttons becomes inactive and if you press it doesn't load.. you have to fully reload the page (hit f5) to let this become active again.

Expected behavior: It should just save the notes.

Video/Screenshot link (optional):
Error:

Traceback:
commitChanges@https://apt204showroom.com/web/content/1349-e677060/web.assets_backend.js:2590:55
OdooClass.extend/</prototype[name]</<@https://apt204showroom.com/web/content/506-3513272/web.assets_common.js:3860:488
commitChanges@https://apt204showroom.com/web/content/1349-e677060/web.assets_backend.js:2644:13
OdooClass.extend/Class.include/</prototype[name]</<@https://apt204showroom.com/web/content/506-3513272/web.assets_common.js:3863:371
commitChanges/defs<@https://apt204showroom.com/web/content/1349-e677060/web.assets_backend.js:1388:235
_.collect@https://apt204showroom.com/web/content/506-3513272/web.assets_common.js:109:270
commitChanges@https://apt204showroom.com/web/content/1349-e677060/web.assets_backend.js:1388:169
saveRecord/unlockedMutex<@https://apt204showroom.com/web/content/1349-e677060/web.assets_backend.js:1371:355

**Comment by pedrobaeza** [comment] 2020-05-24 09:47
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by povi2946** [comment] 2020-05-24 17:31
I can't remember exactly when this started to happen. I think first time I noticed when I was trying to setup additional languages. But I search more about this and it I tried to "Regenerate Assets Bundles" and it seemed that it fixed the problem.

**Closed** 2020-05-24 17:52 UTC
Labels: Need information

**Comment by povi2946** [comment] 2020-05-24 23:03
I can't remember exactly when this started to happen. I think first time I noticed when I was trying to setup additional languages. But I search more about this and it I tried to "Regenerate Assets Bundles" and it seemed that it fixed the problem.
