### ISSUE TITLE
[8.0] Tree view inline edit error when expanding search bar

### ISSUE THREAD

**Issue by russell07** [odoo/odoo#2866] opened 2014-10-02 14:14 UTC
Whilst inline editing a tree view row, if you expand or contract the search bar, the inline edit fields remain in the same location which can overlap the search bar parameters.

![screen shot 2014-10-02 at 15 10 54](https://cloud.githubusercontent.com/assets/6756532/4492070/3efb13c6-4a3e-11e4-85b6-587298959aa7.png)

Browser: Chrome 37.0.2062.124 on Linux and Mac OS X

**Comment by omalbastin** [comment] 2015-06-22 11:21
but this issue is there in form view also if the form view have more than one o2m editable tree views.

**Comment by Moret84** [comment] 2016-04-18 07:57
+1 I can confirm the issue

**Comment by Yenthe666** [comment] 2017-10-09 18:09
Hi guys,

This problem is no longer presented in newer versions of Odoo (V9, V10 and V11). As Odoo 8 is no longer officially supported I'm closing this report.

Regards,
Yenthe

**Closed by Yenthe666** 2017-10-09 18:09 UTC

**Comment by omalbastin** [comment] 2017-10-10 04:16
Great. This issue was reported 3 years back and now because of the new release of odoo v11, it is no longer supported... Hopefully v11 will also have many issues and some one will report them also.. So officials can hold the issue till ODOO v14 so that they can close it because its no logner officially supported

**Comment by ged-odoo** [comment] 2017-10-10 07:08
@omalbastin I understand you frustration, but you should know that we have a finite amount of resources.  Some issues takes a long time to fix, and the fix may be risky. The editable list view is one of the trickiest part of the web client, and until recently, our javascript team was extremely small. So, of course, we had to focus on higher priority issues/features.

I want to say that we actually care about the web client.  We may not be able to solve every problems, but we really do our best.  I hope that v11 will not have many issues, and I will dedicate as many resources as I can to solve them quickly.
