### ISSUE TITLE
[10.0] It's not possible to choose a custom template in Mass Mailings

### ISSUE THREAD

**Issue by CGenie** [odoo/odoo#14148] opened 2016-11-04 11:15 UTC
Impacted versions: 10.0

Steps to reproduce: none

Current behavior:
Go to mass mailings templates, create some custom template, then go and create a mass mailing. In v 9.0 there were 2 options for mail body: Select a Theme or Choose a Template. Seems this was removed in commit

https://github.com/odoo/odoo/commit/1501b30c5373cbdd85a9fc9e1867c374c1a2c108#diff-ff1ac4b89d226a281c58f8f1e1a832d3L40

Now there is only 'Select a template' but my custom template is not present there. 

Expected behavior: Have my custom template be present in Mass Mailings.

Video/Screenshot link (optional):

**Comment by CGenie** [comment] 2016-11-04 11:33
@qsm-odoo I see you made some changes here, please describe a bit to help out with this issue :)

**Comment by qsm-odoo** [comment] 2016-11-04 13:20
@CGenie Hello, in 10.0, the mass mailing templates menu allows to edit default mass mailing templates which are used in other apps. If you want to use a specific mail content when starting a new mass mailing, I suggest you go to a mass mailing you already created and use Action -> Duplicate to create a new draft mass mailing with the same mail body. Hope this is helping.

**Comment by bartstelder** [comment] 2016-11-08 10:36
First of all this not how it was intended, In V9 it was possible to create a new template for a certain group of users...

@qsm-odoo Concerning your advice

I can create a copy. When i want to edit the template, for example to add a banner, the banner is not shown, basicaly none of the newly added pictures is shown
![2016-11-08_11h30_08](https://cloud.githubusercontent.com/assets/21118163/20095795/3dfda8d2-a5a7-11e6-9458-60fd5ec171bf.png)

**Comment by qsm-odoo** [comment] 2016-11-21 14:09
Hello.
The issue mentioned in the last comment was fixed with commit https://github.com/odoo/odoo/commit/a2d05a7087cdeacf242873c75f7e1f11779e2024.
The "Mail Templates" menu will be moved in a future update to avoid confusion as they are not meant to be used for Mass Mailing creations anymore.

**Closed by qsm-odoo** 2016-11-21 14:09 UTC

**Comment by qsm-odoo** [comment] 2016-11-22 09:56
Commit https://github.com/odoo/odoo/commit/dff12736dbeae07af5ecd6e916ce72e03ec06c24 removed the menu to avoid confusion. Edition of mail templates from other modules can still be done thanks to the "Templates" menu in the Settings app.
