### ISSUE TITLE
POS order state is still draft after I do a payment via ui

### ISSUE THREAD

**Issue by natthanank** [odoo/odoo#48291] opened 2020-03-25 03:38 UTC
[https://youtu.be/Bt9RA2tAtWM](https://youtu.be/Bt9RA2tAtWM)
Please see the video I uploaded. I make 4 order with different customer and payment method.
But after I close the pos ui and back to backend page. I see the third order state is still draft. Anyone can tell me why it is still draft? 

Thank you

**Comment by pedrobaeza** [comment] 2020-03-25 08:42
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by natthanank** [comment] 2020-03-25 09:15
Sorry, I can’t login with admin/admin.

 

จาก: Pedro M. Baeza <notifications@github.com> 
ส่ง: Wednesday, March 25, 2020 3:43 PM
ถึง: odoo/odoo <odoo@noreply.github.com>
สำเนาถึง: Natks <natthanank14@gmail.com>; Author <author@noreply.github.com>
เรื่อง: Re: [odoo/odoo] POS order state is still draft after I do a payment via ui (#48291)

 

Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by pedrobaeza** [comment] 2020-03-25 09:17
Maybe someone has changed the password in one of the instances. Try another one (there are usually 4 for the same version).

**Comment by natthanank** [comment] 2020-03-26 02:34
Do you mean another username and password? I don't know it. :(

**Comment by Yenthe666** [comment] 2020-03-26 07:23
@natthanank try another test instance with the same logins ("admin" for both username and password). Sometimes people change it on a test instance to lock others out sadly.

**Comment by natthanank** [comment] 2020-03-26 10:01
![image](https://user-images.githubusercontent.com/16128880/77634317-55da7300-6f83-11ea-9886-685bb3035e2e.png)
I tried all of these instance

**Comment by pedrobaeza** [comment] 2020-03-26 10:04
That's not instances... These are:

![Selección_046](https://user-images.githubusercontent.com/7165771/77634654-991bee00-6f51-11ea-9fc5-5dcd150a8e5e.png)

**Comment by pedrobaeza** [comment] 2020-05-08 19:56
Closing as no more answer.

**Closed by pedrobaeza** 2020-05-08 19:56 UTC
Labels: Need information
