### ISSUE TITLE
odoo - Mail server

### ISSUE THREAD

**Issue by Hari-Guhan-s** [odoo/odoo#22346] opened 2018-01-18 12:56 UTC
Impacted versions:10.0

Current behavior:

Able to retrieve mail through incoming mail config from my private mail server (name@mydomain.com)

Expected behavior:

Need additional behavior to retrieve contacts and calendar events

**Comment by Yenthe666** [comment] 2018-01-18 13:06
Hi @Hari-Guhan-s,

This bug report is way too small. Please provide information, how to reproduce, what is wrong, ...
Without this we cannot help you.

Regards,
Yenthe

**Comment by Hari-Guhan-s** [comment] 2018-02-14 07:11
Hi,
I need a outlook odoo connector to sync my contacts and calendar events or suggest me a better solution to do this.

**Comment by Yenthe666** [comment] 2018-02-14 07:13
Hi @Hari-Guhan-s,

Okay, thanks for the extra info.
As this is not a bug in the default Odoo but a question I'm closing this. The Github bug tracker is only for bugs in the official code.
You can find quite some Outlook related apps on the official app store at https://www.odoo.com/apps/modules/browse?search=Outlook

Regards,
Yenthe

**Closed by Yenthe666** 2018-02-14 07:13 UTC
Labels: 10.0, Need information
