### ISSUE TITLE
Incomplete debian nightly package

### ISSUE THREAD

**Issue by zbik2607** [odoo/odoo#20903] opened 2017-11-13 14:44 UTC
Impacted versions:
10.0 (probably 9.0 and 11.0)
Steps to reproduce:
Install on Debian Odoo based on nightly repository and compare addons folders with 
downloaded zip from github 
Current behavior:
For example, file /mail/static/scripts/openerp_mailgate.py not exist in Debian package
Total difference in files count (folder addons) = 680 files
Expected behavior:
APT repository = Github

**Comment by Yenthe666** [comment] 2017-11-13 14:50
@d-fence can you check?

**Comment by zbik2607** [comment] 2017-11-13 14:54
Compared with the nightly version 10.0.20171110

**Comment by Yenthe666** [comment] 2017-12-18 09:03
@d-fence any update on this?

**Comment by aisopuro** [comment] 2018-01-11 12:33
I can confirm that this also extends to the file `addons/base_import/tests/test.xlsx`, which in the debian package should reside in `/usr/lib/python2.7/dist-packages/odoo/addons/base_import/tests/test.xlsx`. It is missing from at least the 10.0 version and 11.0 version of the Debian package. These packages were downloaded from the nightly repository at https://nightly.odoo.com/. We would also be very interested in updates to this @d-fence :sweat_smile: . So far we have noticed that the unit tests for `base_import` break because they do not find the expected file.

**Comment by d-fence** [comment] 2018-01-11 14:28
I'll have a look at that ASAP

**Comment by aisopuro** [comment] 2018-02-05 07:06
This seems to have caused another issue #22778. This is now blocking unit tests run on the debian package.

**Comment by pedrobaeza** [comment] 2020-02-17 18:14
As 10.0 is already deprecated, I close this. Please answer if it's still happening in >=11.0

**Closed by pedrobaeza** 2020-02-17 18:14 UTC
Labels: 10.0, Framework

**Comment by zeroheure** [comment] 2021-03-17 17:58
Same issue with RPM package.
