### ISSUE TITLE
Create New User (Select profile pics) profile pics can't view after save the record.

### ISSUE THREAD

**Issue by imjaypatel** [odoo/odoo#2399] opened 2014-09-15 10:06 UTC
<b>Produce in:</b> Master, 8.0 
<b>Description:</b> Create New User (Select profile pics) and save. but can't display. Again same thing when edit user select profile pics and save profile. Profile pics display.

<b>View on:</b> https://www.youtube.com/embed/fX_ieldSWbg

**Comment by Yenthe666** [comment] 2016-06-03 10:25
Hi @imjaypatel,

This issue is no longer present in the latest codebase.
Please update your Odoo codebase if you still face this issue, it will be solved then.
Closing this issue since it can no longer be reproduced!

Regards,
Yenthe

**Closed by Yenthe666** 2016-06-03 10:25 UTC
