### ISSUE TITLE
[13.0] [Payment] Multi-currency

### ISSUE THREAD

**Issue by ivanporras** [odoo/odoo#54795] opened 2020-07-22 18:47 UTC
Impacted versions:
13.0

Steps to reproduce:
1.- Set USD as main currency for the company. 
2.- Create an invoice and set USD currency.
3.- Create a payment and set MXN currency.
4.- Try to reconcilie the payment

Current behavior:
Odoo show an error, singleton res.currency, you can see in the screenshot. 

Expected behavior:
Payment must to reconcile with invoice. 

Video/Screenshot link (optional):
![Screenshot(14)](https://user-images.githubusercontent.com/13451948/88215807-d2bfe580-cc21-11ea-9374-1f77ca62853f.png)

**Comment by pedrobaeza** [comment] 2020-07-22 19:04
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the green door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by ivanporras** [comment] 2020-07-23 17:49
@pedrobaeza It's weird, I tried to reproduce the error but I did not make it.

**Comment by pedrobaeza** [comment] 2020-07-23 17:52
Yeah, that's probably because you have something bad in your end:

- Outdated source code.
- Third party modules that breaks the behavior.
- Inconsistent DB state.

Try to check these things, but I have to close this issue, as it's not something on Odoo code itself. If you find this reproducible in runbot later, please tell and we can reopen it with the proper steps to reproduce.

**Closed by pedrobaeza** 2020-07-23 17:52 UTC
Labels: 13.0, Accounting, Need information

**Comment by ivanporras** [comment] 2020-07-23 18:03
Thank you!

**Comment by ivanporras** [comment] 2020-07-23 19:26
@pedrobaeza I fixed the error. When currency_id is null. 
account_move.py 

 #IvanPorras
                            if line.currency_id:
                                amnt_currency_debit = self.amount_currency and line.currency_id.round(line.amount_currency * amount / line.balance) or 0.0,
                                amnt_currency_credit = self.amount_currency and line.currency_id.round(-line.amount_currency * amount / line.balance) or 0.0
                            else:
                                amnt_currency_debit = 0.0
                                amnt_currency_credit = 0.0

**Comment by pedrobaeza** [comment] 2020-07-24 06:58
The question is how do you get to that situation where there's a problem. `currency_id` field is empty most of the time when the account is in the same currency of the company. Maybe you start with an account with a currency set, and the unset it?
