### ISSUE TITLE
[9.0] Incorrect PoS Order sequence when splitting order

### ISSUE THREAD

**Issue by SiviBu** [odoo/odoo#11542] opened 2016-03-30 12:11 UTC
Steps to reproduce:
1. Open PoS session (Bill Splitting must be checked).
2. Create an order and add some products.
3. Press Split button.
4. Add new order by pressing plus ('+') sign on the right.
5. Open previous order (from 2nd step) by clicking on it's tab.
6. Open latest order (from 4th step) by clicking on it's tab.
7. Repeat 5th and 6th steps (e.g. 5 times).
8. Add new order by pressing plus ('+') sign on the right.

Result:

Order created by the 8th step has incorrect sequence.

**Comment by pedrobaeza** [comment] 2018-04-18 00:02
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-04-18 00:02 UTC
Labels: 9.0, Point of Sale
