### ISSUE TITLE
[11.0]Cannot read property 'split' of undefined in filters in app view

### ISSUE THREAD

**Issue by SalahAdDin** [odoo/odoo#25387] opened 2018-06-21 10:32 UTC
Impacted versions:
`Odoo 11.0-20180621 (Community Edition)`

Steps to reproduce:
I just filtered apps first by extra and after by author.
Then, I delete the extra's filter first and after the author 's filter.

Current behaviour:
```bash
Error:
Uncaught TypeError: Cannot read property 'split' of undefined

http://localhost/web/content/1091-a8972a1/web.assets_backend.js:1499
Traceback:
TypeError: Cannot read property 'split' of undefined
    at Class._readTooltipFields (http://localhost/web/content/1091-a8972a1/web.assets_backend.js:1499:749)
    at Array.<anonymous> (http://localhost/web/content/1091-a8972a1/web.assets_backend.js:1499:76)
    at Array.<anonymous> (http://localhost/web/content/1075-be42584/web.assets_common.js:802:681)
    at fire (http://localhost/web/content/1075-be42584/web.assets_common.js:796:299)
    at Object.fireWith [as resolveWith] (http://localhost/web/content/1075-be42584/web.assets_common.js:801:198)
    at Array.deferred.(anonymous function) (http://localhost/web/content/1075-be42584/web.assets_common.js:803:56)
    at fire (http://localhost/web/content/1075-be42584/web.assets_common.js:796:299)
    at Object.fireWith [as resolveWith] (http://localhost/web/content/1075-be42584/web.assets_common.js:801:198)
    at Array.<anonymous> (http://localhost/web/content/1075-be42584/web.assets_common.js:802:874)
    at fire (http://localhost/web/content/1075-be42584/web.assets_common.js:796:299)
```

Expected behaviour:
No error message.

**Comment by sswapnesh** [comment] 2018-06-22 17:53
Not Related to Apps Filter/Group By only, (This happens only If you remove Filter (Don't Wait to load page) and Group by Just after that)

**Comment by SalahAdDin** [comment] 2018-06-22 17:57
It could be happened because i use a filter first and after i grouped, yes; first, i removed the filter and the group still was active, so it takes that as if i would group by without waiting to re-load page.

**Comment by pedrobaeza** [comment] 2018-06-22 17:59
I also think is because JS code hasn't been totally loaded. Please try to reproduce the problem on runbot.l

**Comment by sswapnesh** [comment] 2018-06-22 18:00
I can reproduce the Same on Runbot Latest Build

**Comment by pedrobaeza** [comment] 2018-06-22 18:03
Steps to reproduce?

**Comment by sswapnesh** [comment] 2018-06-22 18:11
Tested Here: [http://341390-11-0-6edf49.runbot16.odoo.com/web?debug=assets#view_type=kanban&model=res.partner&menu_id=72&action=93](http://341390-11-0-6edf49.runbot16.odoo.com/web?debug=assets#view_type=kanban&model=res.partner&menu_id=72&action=93)

![301](https://user-images.githubusercontent.com/16624719/41792140-7afa5c3a-7675-11e8-8caa-49080861aabc.png)

Keep Cursor in Search Bar at End --> Remove  Customer Filter By Clicking Close Button and Press Backspace Just after that

**Comment by SalahAdDin** [comment] 2018-06-22 18:12
I had that problem filtering apps, i had many add-ons from `OCA`.

**Comment by pedrobaeza** [comment] 2018-06-22 18:14
@sswapnesh I have just tried what you say but I don't reproduce it. Which OS and browser?

**Comment by pedrobaeza** [comment] 2018-06-22 18:16
OK, I think I get it: it's removing second filter with backspace before the record loading after the other filter removal has ended. Can it be?

**Comment by sswapnesh** [comment] 2018-06-22 18:17
Tested on Ubuntu 18.04 and Windows with Google Chrome.

**Comment by sswapnesh** [comment] 2018-06-22 18:21
There is no Second Filter Here,
"Filter" --> "Group By" 
Remove Filter (Don't wait to Load Records in view) --> Remove Group By (You can keep you Keyboard Cursor there to press Backspace just after removing Filter)

**Comment by sswapnesh** [comment] 2018-06-22 18:25
Added Video [https://drive.google.com/file/d/1GI2xN6XQfY9bm80-RZU0XeLJp0yB5SkM/view](https://drive.google.com/file/d/1GI2xN6XQfY9bm80-RZU0XeLJp0yB5SkM/view)

**Comment by pedrobaeza** [comment] 2018-06-22 18:25
Yeah, I meant group by instead of filter. I think it's the same in terms of view reloading.

@ged-odoo this is an interesting thing to check and fix in the new views.

**Comment by SalahAdDin** [comment] 2018-06-22 18:29
Oh, great, i can't test it now because i had to delete it due to the other problems that i reported here, i'm working with a customized `docker` image from `odoo` official image.

**Comment by pedrobaeza** [comment] 2018-06-22 18:31
@SalahAdDin you always have to test any possible issue with runbot, not with your image.

**Comment by SalahAdDin** [comment] 2018-06-22 18:52
I don't know about it.

**Comment by pedrobaeza** [comment] 2018-06-22 19:03
Go to https://runbot.odoo.com and click on the blue button of one of the instances you want for the desired branch (11.0) and login with admin/admin

**Comment by husm91** [comment] 2018-06-23 08:02
hi everyone I can not cancel invoice cash
![screen shot 2018-06-23 at 10 56 01 am](https://user-images.githubusercontent.com/40514868/41807260-ec5a75fe-76d4-11e8-8c9c-28ad65de9982.png)

**Comment by sswapnesh** [comment] 2018-06-23 08:20
@husm91 Please Do not Post this type of Questions here.
Invoice cannot be cancelled once it it paid, Create Credit note Instead.

**Comment by mart-e** [comment] 2021-01-21 06:25
Closing as the 11.0 is no longer supported and a quick test indicates this is no longer reproducible in 11 or 12.0

**Closed by mart-e** 2021-01-21 06:25 UTC
Labels: 11.0, Confirmed, Framework
