### ISSUE TITLE
[9.0] Archive button + Web tip

### ISSUE THREAD

**Issue by adekock11** [odoo/odoo#10982] opened 2016-02-18 08:47 UTC
When you install the web_tip module, an Archive button will initially display as in the screen shot below:
![archive](https://cloud.githubusercontent.com/assets/1809451/13137932/c747721c-d62c-11e5-8a1e-252dd9c378a1.JPG)

However, you can't click on the hovering web tip. I you try to click it, the record is archived. The expected behaviour is that the web tip popup is displayed.

**Comment by Yenthe666** [comment] 2016-02-19 07:29
@adekock11 this is a duplicate of https://github.com/odoo/odoo/issues/10155
@odony and @xmo-odoo double issue. Could this however be passed on to somebody to fix? :smile:

**Comment by odony** [comment] 2016-02-19 10:00
Closing as a duplicate of #10155, thanks @Yenthe666 for noticing it.
@adekock11 Thanks for reporting. Please fo not hesitate to search in the (many) posted issues before adding one more, it seems the keywords for finding the duplicate would have matched easily.

**Closed by odony** 2016-02-19 10:00 UTC

**Comment by adekock11** [comment] 2016-02-19 10:09
Alright. Please just note that this issue is both on 9.0C and 9.0E (unlike #10155) + it is on all archive buttons and not just on project form (unlike #10155) :)

**Comment by odony** [comment] 2016-02-19 10:15
@adekock11 thanks for the updated info indeed!

**Comment by odony** [comment] 2016-02-25 15:16
@adekock11 FYI issue #10155 was just closed, and the fix works for all archive buttons :-) See https://github.com/odoo/odoo/issues/10155#issuecomment-188806836
