### ISSUE TITLE
[9.0] Field values lost during the upgrade to property (company_dependent=True) 

### ISSUE THREAD

**Issue by yucer** [odoo/odoo#11648] opened 2016-04-09 10:13 UTC
Impacted versions: 8.0, 9.0

Steps to reproduce:

Specify company_dependent=True on a field of simple type 

Current behavior:

The next database upgrade shows a warning: 

`column mycolumn (my column description) converted to a function, removed from table (table)`

and the values are lost. Currently we need to use then upgrade scripts for the conversion. 

Expected behavior:

Avoid default upgrade behaviors that cause data loss. Either one of this:
1. The values are automatically copied to the new property values during the upgrade phase.
2. Provide a hook where the programmers need to define a **mandatory** upgrade behavior:
   - If the hook returns no value for this field then raise an exception "Property data would be lost. Define an upgrade behavior for the field: {field} at version {version}"
   - The upgrade hook could also return False for this field meaning that the orm is authorized to drop the values
3. Provide a upgrade registry where the upgrade scripts can provide context for the whole update process. There the pre-upgrade script can state that a field was properly treated. Other upgrade phases can check that info when taking actions that could cause the loss of data (e.g dropping a column)

**Comment by yucer** [comment] 2016-11-30 15:11
I have published a sample [module](https://github.com/yucer/odoo-examples/tree/8.0_company_dependent_mig) with migration scripts, to show one possible way to deal with this, until an official or community solution is found to this topic.

Please read the [README.md](https://github.com/yucer/odoo-examples/blob/8.0_company_dependent_mig/README.md) from the repo, and the [description of the module](https://github.com/yucer/odoo-examples/blob/8.0_company_dependent_mig/migration_test/README.md)

**Comment by Yenthe666** [comment] 2017-11-26 15:10
Duplicate of https://github.com/odoo/odoo/issues/11647 pretty much.

**Closed by Yenthe666** 2017-11-26 15:10 UTC
Labels: 9.0

**Comment by yucer** [comment] 2017-11-28 00:12
Do you see a relation with that issue ?

I did note that odoo already implemented the 1. option.

Cheers, Y
