### ISSUE TITLE
Qweb report sale.report_saleorder missing footer at PDF

### ISSUE THREAD

**Issue by guggenbergerl** [odoo/odoo#4806] opened 2015-01-20 22:27 UTC
If I print a saleorder with the qweb report sale.report_saleorder in HTML format, by default a footer is printed. See following screenshot:
![screenshot html](https://cloud.githubusercontent.com/assets/8057352/5827505/21cc576a-a0fb-11e4-8894-6d9a118e85c0.png)

If I print the same saleorder in PDF format, the default footer isn't printed. See following screenshot:
![screenshot pdf](https://cloud.githubusercontent.com/assets/8057352/5827527/57e670f6-a0fb-11e4-9767-6b46cdf0f522.png)

Why is the default footer not printed at the PDF printout of this report? What should I do to solve this problem? I need the footer printed also on the PDF printout.

**Comment by aab-odoo** [comment] 2015-01-21 07:32
What is your version of wkhtmltopdf? If it is 0.12.2 or 0.12.2.1, we are working on the issue. Missing footer is due to their update from 0.12.1 to 0.12.2. Meanwhile, you can still go back to 0.12.1 and it should work properly.

Thanks for reporting it anyway.

**Comment by guggenbergerl** [comment] 2015-01-21 07:53
Thanks for the information! I use wkhtmltopdf 0.12.2. Do I get an info at this issue #4806 if it is solved or should I check this somewhere by myself?

**Comment by aab-odoo** [comment] 2015-01-21 09:26
You will be informed once it is solved.

Regards,

**Comment by trannhuvan** [comment] 2015-03-03 10:32
@aab-odoo 
I have that problem. I am using wkhtmltopdf 0.12.1 with ubuntu 12.01
I try ti set system parameters, as report.url or base.url.freeze..., but it's not work.

Other problem is header (maybe both footer) only display in first page of report (.pdf).

Can you give me your idea about that?

**Comment by sle-odoo** [comment] 2015-03-05 14:39
@trannhuvan Did you customize the default header or/and footer?
The ``report.url`` key is only useful when your setup has multiple databases and no db-filter.

**Comment by trannhuvan** [comment] 2015-03-05 19:53
yeah @sle-odoo I modified both them, inherit "report.external_layout_header" and "report.external_layout_footer".

I have two problems
1. In Ubuntu 12.01, using wkhtmltopdf 0.12.1 trusty, the report has two headers and two footers. So, some pages has header or/and footer, others are not.

2. In Centos 6 using wkhtmltopdf 0.12.1 (for Centos 6) is same error (but has three headers and footers).

My report has many page (4 or more), can you help me?

**Comment by trannhuvan** [comment] 2015-03-09 03:38
@sle-odoo can you help me solve my issue?

**Comment by slim1616** [comment] 2015-03-11 17:54
Hello
my config is :
win 7 64 bits
odoo v8 Running with eclipse
wkhtmltopdf 0.12.2.1 64 bits

for this problem "Qweb report sale.report_saleorder missing footer at PDF", i make some tests and i think that i found a solution but not good!
the problem is in --margin-top (a parameter of wkhtmltopdf command), when he is defined and i print a sale order i have no footer.
I commented a lines 524 to 528 in addons/report/models/report.py (i disabled  --margin-top parameter).
I dont now whats the problem with --margin-top but it work (i have my footer), 
the margin bottom is 10 or 20 change it in configuration-->technical-->reports-->paper format

I hope that's work for you or finding a better solution, I expected yours feedback
Regards

**Comment by MarcoWeiss** [comment] 2015-06-10 11:11
Hi all,
we have this issue, too.
Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-32-generic x86_64)
wkhtmltopdf 0.12.2.1 (with patched qt)
Odoo Version 8.0-20150606

The workaround from slim1616 fixed it.
Just for information...

Regards Marco

**Comment by enriquemartin** [comment] 2015-08-03 09:22
Hi people,

Same problem here with at least sales and invoice reports. Things that I tried and didn't work so far:
* setting webkit_path
* setting web.base.url, web.base.url.freeze
* setting report.url
* downgrade wkhtmltox from 0.12.2 to 0.12.1 and 0.12.0...
* comment lines 524 to 528 in addons/report/models/report.py

It works in HTML mode, not in PDF. Footer always appears, the problem in my case is the header.
Running on Centos7x64

**Comment by guggenbergerl** [comment] 2015-08-13 12:27
When will this issue be solved in Odoo v8? This issue is open now more than a half year.

**Comment by MarcoWeiss** [comment] 2015-08-13 13:47
Hi guggenbergerl,

first i did the workaround like written above. Now i reverted to install the exact package which is working with that Odoo version.

wget http://cznic.dl.sourceforge.net/project/wkhtmltopdf/archive/0.12.1/wkhtmltox-0.12.1_linux-trusty-amd64.deb
dpkg -i wkhtmltox-0.12.1_linux-trusty-amd64.deb 
wkhtmltopdf --version
wkhtmltopdf 0.12.1 (with patched qt)

Regards Marco

**Comment by tejastank** [comment] 2015-10-01 12:41
Its really a odoo hell issue, no such right solution even from odoo people. 

Looking for right solution which work with qweb and wkhtmltopdf any better least version.

Its just footer, #odoo can't had comment to fix it.

**Comment by sle-odoo** [comment] 2015-10-01 12:53
@tejastank What's your issue? It's clearly documented that the only supported version of wkhtmltopdf is the 0.12.1. With this version, there's no footer problem. I'm willing to help you but please explain your issue and if you modified some templates, link here.

If you have no footer: use wkhtmltopdf 0.12.1
If you have no styles: set a db-filter. Then, if it's not working that's because wkhtmltopdf cannot contact your webserver: try to set report.url to an ~internal url (like 127.0.0.1:8069)
If you modified the header and it is crop, try to adjust the marigin-top and header-spacing value.

**Comment by lbonjean** [comment] 2015-10-01 12:58
Hi,

In the margin of this, I cannot print barcodes if I set a db-filter.
My odoo session quits.
If I remove the db-filter, it works.

Any clues on this one.

Thx.


Met vriendelijke groeten / Best regards,
Luc Bonjean

Van: Simon Lejeune [mailto:notifications@github.com]
Verzonden: donderdag 1 oktober 2015 14:54
Aan: odoo/odoo
CC: Luc Bonjean (Lubon bvba)
Onderwerp: Re: [odoo] Qweb report sale.report_saleorder missing footer at PDF (#4806)


@tejastank<https://github.com/tejastank> What's your issue? It's clearly documented that the only supported version of wkhtmltopdf is the 0.12.1. With this version, there's no footer problem. I'm willing to help you but please explain your issue and if you modified some templates, link here.

If you have no footer: use wkhtmltopdf 0.12.1
If you have no styles: set a db-filter. Then, if it's not working that's because wkhtmltopdf cannot contact your webserver: try to set report.url to an ~internal url (like 127.0.0.1:8069)
If you modified the header and it is crop, try to adjust the marigin-top and header-spacing value.

**Comment by tejastank** [comment] 2015-10-03 04:17
odoo@serverhub:~$ wkhtmltopdf --version
wkhtmltopdf 0.12.1  

Already configured url or freeze and all other variable parameter for system config.

Official odoo code, no any customize one, even all had issue.
Footer coming with html report type, but not with qweb pdf report.

If you try to say "If you have no styles: set a db-filter.", people can understand odoo lost quality of code & integration for report, Does people had really force to db-filter to enable this footer problem where entire report print ? 

Seems odoo more wired for minor report feature.

**Comment by web32** [comment] 2015-10-06 15:15
On a clean odoo v8 install on Ubuntu 14.04.3 and wkhtmltopdf 0.12.1 I could manage to get the footer working by choosing the correct paper format (in my case A4).

Hope I could help you guys.

**Comment by antoniomatos78** [comment] 2016-01-02 20:50
i found that it only happens if you have a specific paper format defined.
Just clear it and footer goes on!

**Comment by ozel1978** [comment] 2016-02-16 01:56
i have same issue, with only half page printed for payroll.

hope anyone have similar issue can suggest me what is solution.

- i have format the servers several time and it work for first time but after patch, the problem happen again.
- I change to older or latest version wkhtmltopdf also not working.
- My server using ubuntu.


![image](https://cloud.githubusercontent.com/assets/17262653/13065027/2faa1c74-d493-11e5-98c7-7d2f48ab4540.png)

**Comment by sle-odoo** [comment] 2016-02-16 09:54
@ozel1978 wkhtmltopd cannot contact your server to get the css styles. There are information to troubleshoot this issue in the documentation.

**Comment by lukebranch** [comment] 2016-02-19 01:13
1) Enable debug mode (in backend click your user - eg. Administrator > About > Activate the Developer Mode
2) Settings > Parameters >> System Parameters
3) Create:
<strong>Key:</strong> report.url
<strong>Value:</strong> http://127.0.0.1:8069/

make sure there are no extra spaces before or after http://127.0.0.1:8069/.

**Comment by ozel1978** [comment] 2016-02-20 04:31
thank you sle-odoo and luke.

is there any way i can edit using command line. seem my odoo page not respond when i try to acivate the developer mode.

**Comment by ozel1978** [comment] 2016-02-20 15:40
is working now guys. thank you.

**Comment by diannejose** [comment] 2016-02-23 07:03
Hi
I am also facing same layout issue as said by ozel. 
I am working on odoo9  & my base report have this layout issue. i tried to set the system parameters. but nothing happened

I have two odoo 9 dbs on the same server, but only one has this layout problem
any solution pls,

**Comment by lukebranch** [comment] 2016-02-24 02:32
@diannejose ,

It's best to hit the help forum or mailing lists with these kinds of questions:

http://help.odoo.com

https://www.odoo.com/page/odoo-community

I would suggest checking to make sure you're not running out of memory, and make sure you've got some workers assigned:

https://www.odoo.com/documentation/9.0/setup/deploy.html

If you've tried the system parameters fix, my next guess would be that you've exhausted system resources.

**Comment by ozel1978** [comment] 2016-02-26 14:28
diannejose,
If you can share with us specification of server, OS, using ssl or not.
Probably we can suggest best way to solve you issue.

**Comment by navinks04** [comment] 2016-05-12 19:15
Solved

Removed all the new parameters as suggested by others.

In the web.base.url inserted localhost or the host IP address and the reports are in proper format.

I didn't undo the update done on wkhtmltopdf.

Reports are OK.

**Comment by tejastank** [comment] 2016-05-19 06:05
Till date issue, no proper fix,

**Comment by sle-odoo** [comment] 2016-06-08 11:45
@tejastank it's a well known deployment issue and the answers are everywhere on this bug tracker and even in the documentation.

- use wkhtmltopdf 0.12.1
- use a db-filter
- if wkhtmltopdf cannot contact your odoo server it is because it cannot join web.base.url system parameter, tweak this value or set report.url to a joinable one

**Closed by sle-odoo** 2016-06-08 11:45 UTC

**Comment by tejastank** [comment] 2016-06-09 05:59
Note: right wkhtmltopdf lib, already done well configuration.

I  appreciate you close it, but with each latest code issue their.

Issue till exists

**Comment by nbrahmi** [comment] 2017-03-18 20:47
In my reports in Odoo V10, header and footer are missing.
I have install wkhtmltopdf (0.12.1) but no changes! I've define the system parameter report.url whith http://0.0.0.0:[port], and after I delete this parameter and define (web.base.url = http://127.1.0.0:[port]). I've already the pb! Have you any idea?

Thank you.

**Comment by rubiagatra** [comment] 2017-04-08 02:08
Hellp I facing the same problem with centos 7

**Comment by ozel1978** [comment] 2017-04-08 10:12
You can try view previous comments at git hub.

**Comment by nbrahmi** [comment] 2017-04-08 11:17
I have tested all the above suggestions without success

**Comment by fashkl** [comment] 2017-06-20 00:44
if use wkhtmltopdf version 0.12.1 or earlier try to change it to any updated version such 0.12.4. that will work well.
this to how to install it in Linux wkhtmltopdf-0.12.4 https://www.tecmint.com/wkhtmltopdf-convert-website-html-page-to-pdf-linux/
enjoy :)
