### ISSUE TITLE
HR Employee view can not be inherited for use by non hr group users

### ISSUE THREAD

**Issue by bhtabor** [odoo/odoo#75008] opened 2021-08-12 11:28 UTC
Barcode related buttons prevent the hr employee view from being used by non hr group users.

Impacted versions: 14.0

Steps to reproduce: Inherit the HR Employees view https://github.com/odoo/odoo/blob/14.0/addons/hr/views/hr_employee_views.xml and try to use it with non hr group users.

Current behavior: View page errors out. Error: While parsing modifiers for button: for modifier "invisible": Unknown field barcode in domain.

Expected behavior: View page inheriting from hr employees view renders without error.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment] 2021-08-12 12:18
You need to use `hr.employee.public`.

Closing as expected by design.

**Closed by pedrobaeza** 2021-08-12 12:18 UTC

**Comment by bhtabor** [comment] 2021-08-13 07:04
Thank you @pedrobaeza, `hr.employee.public` is indeed a better fit for such a use case. Notwithstanding that, the fix https://github.com/odoo/odoo/pull/75009 may still be necessary though. The buttons seem to need group restriction since their invisible attributes, `attrs="{'invisible': [('barcode', '!=', False)]}"`,  rely on a group restricted barcode field. https://github.com/odoo/odoo/blob/14.0/addons/hr/models/hr_employee.py#L109

**Comment by pedrobaeza** [comment] 2021-08-13 07:06
The page already has such group, so it's not adding anything useful.

**Comment by bhtabor** [comment] 2021-08-13 07:24
Yeah, that was exactly my original assumption. I'm relatively new to Odoo template engine but it seems to me that, although the page group restriction is hiding the inner content, the content must still be valid for the engine regardless.

I notice a similar repetitive field group restriction on other page sections too. https://github.com/odoo/odoo/blob/14.0/addons/hr/views/hr_employee_views.xml#L135

I'm not sure if fields should be treated differently from buttons though.

**Comment by pedrobaeza** [comment] 2021-08-13 07:26
But if the problem is not exposed in upstream code, then you should do the needed changes on your module, not on Odoo itself.

**Comment by bhtabor** [comment] 2021-08-13 07:34
Yeah, that makes sense. I was just wondering if the buttons were somehow missed since all the other fields under a restricted page were restricted for the engine to work smoothly. Only the two buttons generate an error. I'll try to find a work around on the module then. Thanks a lot for the quick response!
