### ISSUE TITLE
[8.0] Bad Gateway once duplicate Bill Of Material

### ISSUE THREAD

**Issue by sapdenny** [odoo/odoo#16461] opened 2017-04-17 06:13 UTC
Impacted versions:
8.0 did not test on another version
Postgresql 9.6

Steps to reproduce:
Duplicate any saved BOM on product.

Current behavior:
System give me bad gateway pop message.

Expected behavior:
BOM duplicate success, and should have several BOM on that product.

Video/Screenshot link (optional):
![badgateway odoo](https://cloud.githubusercontent.com/assets/22925355/25080585/7db70072-236f-11e7-9e30-955469942611.JPG)

**Comment by Yenthe666** [comment] 2017-05-03 12:46
Hi @sapdenny,

Thank you for your report.
I've just tested this on the latest Odoo 8.0 and could duplicate the BOM without any issues.
Can you try it again on the latest Odoo codebase (runbot.odoo.com) and add some more screenshots or a video on how you did this?

Regards,
Yenthe

**Comment by Yenthe666** [comment] 2017-05-30 09:10
Hi @sapdenny,

There has been no feedback in almost a month.
I'm closing this issue as I can not reproduce it and everything seems to be fine.
If you do have more information or can still reproduce it on an official runbot let me know and I'll reopen this issue.

Regards,
Yenthe

**Closed by Yenthe666** 2017-05-30 09:10 UTC
Labels: need informations

**Comment by sapdenny** [comment] 2017-06-02 06:38
Hi @Yenthe666 
Thanks for your corespondence.
Actually we still working with this issue but as we just end user for ODOO, we cant explain more. 
I guess the problem come from the data. We have so huge data on tables related bymanufacturing.
For this problem i will try to open another issue.
About the runbot would you explain how it work?

Best Regards,
Denny S

**Comment by Yenthe666** [comment] 2017-06-02 16:09
Hi @sapdenny,

The runbot are automatically generated Odoo's based on the latest Odoo source code and with everything installed by default.
You can find them at runbot.odoo.com and sinply choose the Odoo version you'd like to test (9.0, 10.0, ...)
The username and password is always admin

Regards,
Yenthe
