### ISSUE TITLE
DateTimePicker no check for illegal date

### ISSUE THREAD

**Issue by maxch0503** [odoo/odoo#32087] opened 2019-03-25 10:03 UTC
Impacted versions:
12.0
Steps to reproduce:
DateTimePicker input illegal date such as 2019-13-50
Current behavior:
Error:
Uncaught TypeError: Cannot read property 'format' of undefined

http://localhost:18069/web/static/lib/tempusdominus/tempusdominus.js:472
Traceback:
TypeError: Cannot read property 'format' of undefined
    at TempusDominusBootstrap4._setValue (http://localhost:18069/web/static/lib/tempusdominus/tempusdominus.js:472:83)
    at TempusDominusBootstrap4._change (http://localhost:18069/web/static/lib/tempusdominus/tempusdominus.js:493:18)
    at Function._jQueryHandleThis (http://localhost:18069/web/static/lib/tempusdominus/tempusdominus.js:2715:40)
    at jQuery.fn.init._jQueryInterface [as datetimepicker] (http://localhost:18069/web/static/lib/tempusdominus/tempusdominus.js:2722:48)
    at HTMLInputElement.<anonymous> (http://localhost:18069/web/static/lib/tempusdominus/tempusdominus.js:2750:50)
    at HTMLDocument.dispatch (http://localhost:18069/web/static/lib/jquery/jquery.js:4641:58)
    at HTMLDocument.elemData.handle (http://localhost:18069/web/static/lib/jquery/jquery.js:4309:63)
Expected behavior:
raise a validation or user error
Video/Screenshot link (optional):

**Comment by sswapnesh** [comment] 2019-03-25 16:59
Duplicate of https://github.com/odoo/odoo/issues/29551

**Closed** 2019-03-25 19:25 UTC
