### ISSUE TITLE
Multi company accounting settings default tax

### ISSUE THREAD

**Issue by dduarte-odoogap** [odoo/odoo#21213] opened 2017-11-24 17:15 UTC
Impacted versions: 11.0

Steps to reproduce: Create 2 companies A and B, then create an admin for company B, just allowed for company B and try to access company B: Accounting >> Configuration >> Settings or any other (Configuration >> Settings)

Current behavior: You will get the following error:
Odoo Server Error - Access Error
The requested operation cannot be completed due to security restrictions. Please contact your system administrator.
(Document type: account.tax, Operation: read)

Checked the company properties and the default_sale_tax and default_purchase_tax is correct for each company, just the method that get's this value for the res_config must consider the user default company

Expected behavior: We should get no error and the default_sale_tax and default_purchase_tax shown must be for the current user default_company

**Comment by ThijsvOers** [comment] 2017-12-19 08:00
Hi,

I have tested this on the latest runbot 11.0 version and I also get the error just by clicking on the settings menu. I have created a user in 'Your Company' and gave the user all access rights for Your company and 'My company'. Editing the settings menu in 'your company' was allowed, changing the settings in 'My Company' gives the following error:

Odoo Server Error - Access Error
The requested operation cannot be completed due to security restrictions. Please contact your system administrator.
(Document type: res.users, Operation: read) 
I hope it will help finding the cause of the error.

**Comment by PauliusP17** [comment] 2018-01-11 17:17
I have a multi-company setup with 3 companies. I get this error whenever I try to access the Settings with a normal user. Logging in as Admin obviously bypasses this so I went to check the default_sale_tax_id field in Invoicing settings. 

1. I spot the reason why I was getting the error as a normal user before, the tax in default_sale_tax_id field belongs to company C. 
2. I switch it to a tax that belongs to company A and save the settings.
3. The error is now gone if you are logged in as a normal user and are switched to company A, however if you switch to company B or C, the error will come up again. Even though the fields is company dependent for some reason it saves the same value for each company.

**Comment by smetl** [comment] 2018-02-28 14:23
Hello,

This happens only with duplicated companies.
Fixed on 11.0 at revision: https://github.com/odoo/odoo/commit/bff30f58c52dbe96bb5a6205739b2ef17ffec767

Thank you

**Closed by smetl** 2018-02-28 14:23 UTC
Labels: 11.0, Accounting, Confirmed

**Comment by Yenthe666** [comment] 2018-02-28 15:16
@smetl I gave some feedback on the commit as I think the string can be clearer / better. Could you check please? (thanks for the fix!)
