### ISSUE TITLE
Odoo package list

### ISSUE THREAD

**Issue by AsmaAl-Haddar** [odoo/odoo#68968] opened 2021-04-08 13:27 UTC
Impacted versions: 13.0

Steps to reproduce: Go to Inventory> then master data> then packages.

Current behaviour: We will find that there is no data except for the (Company , Owner, Location, and the content which is Product, L/S number , quantity, unit of measure).

Expected behaviour: We want to define more info like to add the gross and net weight and we need to print all the report in QR code instead of barcode.

Thanks,

**Comment by Yenthe666** [comment] 2021-04-08 13:53
Duplicate of https://github.com/odoo/odoo/issues/68957

**Closed by Yenthe666** 2021-04-08 13:53 UTC
