### ISSUE TITLE
Website theme customisation > unable to save new color

### ISSUE THREAD

**Issue by gregory-moka** [odoo/odoo#35168] opened 2019-07-25 07:50 UTC
**Impacted versions:**
12.0 CE

**Steps to reproduce:**
When I'm trying to change the default website theme colors, the color picker does'n want to save the new value.
=> Unable to reproduce on runbot.
=> Which track could I explore ?

**Video/Screenshot link (optional):**
https://recordit.co/NL8XQCqSYU

**Comment by pedrobaeza** [comment] 2019-07-25 07:53
Sorry, but if it's not reproduceable in runbot, then it's because of outdated or custom code in your side, so nothing to do with Odoo core itself.

Closing then.

**Closed by pedrobaeza** 2019-07-25 07:53 UTC
