### ISSUE TITLE
[11.0,12.0] Update modules ir.attachment permission error

### ISSUE THREAD

**Issue by vinclar** [odoo/odoo#47927] opened 2020-03-18 14:01 UTC
Impacted versions:
11.0,12.0 didn't try any other.

Steps to reproduce:
Update to last commit odoo instance, with technical features enabled go to menu Apps/Updates
https://address/web?#menu_id=47&action=34

It will display a message like this:

> Something went wrong !
> Sorry, you are not allowed to access documents of type 'Attachment' (ir.attachment). This operation is allowed for the groups: - User types/Internal User - (Operation: read, User: 4)

Checking the update header of the operation, it tries to compare the files in other location and for version 13.0 even when I'm using version 11.0 or 12.0
Tries to find in "/home/odoo/src/odoo/13.0/" and mines are inside "/opt/odoo/"

version_info response:
`{"jsonrpc": "2.0", "id": 600972711, "result": {"server_version": "12.0", "server_version_info": [12, 0, 0, "final", 0, ""], "server_serie": "12.0", "protocol_version": 1}}`

update response:
`{"jsonrpc": "2.0", "id": 138903292, "error": {"code": 200, "message": "Odoo Server Error", "data": {"name": "odoo.exceptions.AccessError", "debug": "Traceback (most recent call last):\n  File \"/home/odoo/src/odoo/13.0/odoo/api.py\", line 745, in get\n    value = self._data[field][record._ids[0]]\nKeyError: 49752\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/odoo/src/odoo/13.0/odoo/fields.py\", line 996, in __get__\n    value = env.cache.get(record, self)\n  File \"/home/odoo/src/odoo/13.0/odoo/api.py\", line 751, in get\n    raise CacheMiss(record, field)\nodoo.exceptions.CacheMiss: ('loempia.module(49752,).image_ids', None)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/odoo/src/odoo/13.0/odoo/tools/cache.py\", line 85, in lookup\n    r = d[key]\n  File \"/home/odoo/src/odoo/13.0/odoo/tools/func.py\", line 69, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/home/odoo/src/odoo/13.0/odoo/tools/lru.py\", line 44, in __getitem__\n    a = self.d[obj].me\nKeyError: ('ir.model.access', <function IrModelAccess.check at 0x7f7d37194e18>, 4, False, 'ir.attachment', 'read', True, ('es_ES',))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/odoo/src/odoo/13.0/odoo/fields.py\", line 1003, in __get__\n    recs._fetch_field(self)\n  File \"/home/odoo/src/odoo/13.0/odoo/models.py\", line 2935, in _fetch_field\n    self._read(fnames)\n  File \"/home/odoo/src/odoo/13.0/odoo/models.py\", line 3035, in _read\n    field.read(fetched)\n  File \"/home/odoo/src/odoo/13.0/odoo/fields.py\", line 2869, in read\n    lines = comodel.search(domain, limit=self.limit)\n  File \"/home/odoo/src/odoo/13.0/odoo/models.py\", line 1609, in search\n    res = self._search(args, offset=offset, limit=limit, order=order, count=count)\n  File \"/home/odoo/src/odoo/13.0/addons/calendar/models/ir_attachment.py\", line 21, in _search\n    return super(Attachment, self)._search(args, offset=offset, limit=limit, order=order, count=count, access_rights_uid=access_rights_uid)\n  File \"/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_attachment.py\", line 410, in _search\n    count=False, access_rights_uid=access_rights_uid)\n  File \"/home/odoo/src/odoo/13.0/odoo/models.py\", line 4364, in _search\n    model.check_access_rights('read')\n  File \"/home/odoo/src/odoo/13.0/odoo/models.py\", line 3204, in check_access_rights\n    return self.env['ir.model.access'].check(self._name, operation, raise_exception)\n  File \"<decorator-gen-22>\", line 2, in check\n  File \"/home/odoo/src/odoo/13.0/odoo/tools/cache.py\", line 90, in lookup\n    value = d[key] = self.method(*args, **kwargs)\n  File \"/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_model.py\", line 1548, in check\n    raise AccessError(msg % msg_params)\nodoo.exceptions.AccessError: (\"Sorry, you are not allowed to access documents of type 'Attachment' (ir.attachment). This operation is allowed for the groups:\\n\\t- User types/Internal User - (Operation: read, User: 4)\", None)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/odoo/src/odoo/13.0/odoo/tools/cache.py\", line 85, in lookup\n    r = d[key]\n  File \"/home/odoo/src/odoo/13.0/odoo/tools/func.py\", line 69, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/home/odoo/src/odoo/13.0/odoo/tools/lru.py\", line 44, in __getitem__\n    a = self.d[obj].me\nKeyError: ('ir.model.access', <function IrModelAccess.check at 0x7f7d37194e18>, 4, False, 'ir.attachment', 'read', True, ('es_ES',))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/odoo/src/odoo/13.0/odoo/http.py\", line 619, in _handle_exception\n    return super(JsonRequest, self)._handle_exception(exception)\n  File \"/home/odoo/src/odoo/13.0/odoo/http.py\", line 309, in _handle_exception\n    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])\n  File \"/home/odoo/src/odoo/13.0/odoo/tools/pycompat.py\", line 14, in reraise\n    raise value\n  File \"/home/odoo/src/odoo/13.0/odoo/http.py\", line 664, in dispatch\n    result = self._call_function(**self.params)\n  File \"/home/odoo/src/odoo/13.0/odoo/http.py\", line 345, in _call_function\n    return checked_call(self.db, *args, **kwargs)\n  File \"/home/odoo/src/odoo/13.0/odoo/service/model.py\", line 93, in wrapper\n    return f(dbname, *args, **kwargs)\n  File \"/home/odoo/src/odoo/13.0/odoo/http.py\", line 338, in checked_call\n    result = self.endpoint(*a, **kw)\n  File \"/home/odoo/src/odoo/13.0/odoo/http.py\", line 910, in __call__\n    return self.method(*args, **kw)\n  File \"/home/odoo/src/odoo/13.0/odoo/http.py\", line 510, in response_wrap\n    response = f(*args, **kw)\n  File \"/home/odoo/src/custom/private/loempia/controllers/embed.py\", line 96, in update\n    'ico': module.image_ids and '/apps/module_image?image_id=%s' % module.image_ids[0].id or '',\n  File \"/home/odoo/src/odoo/13.0/odoo/fields.py\", line 2246, in __get__\n    return super().__get__(records, owner)\n  File \"/home/odoo/src/odoo/13.0/odoo/fields.py\", line 1005, in __get__\n    record._fetch_field(self)\n  File \"/home/odoo/src/odoo/13.0/odoo/models.py\", line 2935, in _fetch_field\n    self._read(fnames)\n  File \"/home/odoo/src/odoo/13.0/odoo/models.py\", line 3035, in _read\n    field.read(fetched)\n  File \"/home/odoo/src/odoo/13.0/odoo/fields.py\", line 2869, in read\n    lines = comodel.search(domain, limit=self.limit)\n  File \"/home/odoo/src/odoo/13.0/odoo/models.py\", line 1609, in search\n    res = self._search(args, offset=offset, limit=limit, order=order, count=count)\n  File \"/home/odoo/src/odoo/13.0/addons/calendar/models/ir_attachment.py\", line 21, in _search\n    return super(Attachment, self)._search(args, offset=offset, limit=limit, order=order, count=count, access_rights_uid=access_rights_uid)\n  File \"/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_attachment.py\", line 410, in _search\n    count=False, access_rights_uid=access_rights_uid)\n  File \"/home/odoo/src/odoo/13.0/odoo/models.py\", line 4364, in _search\n    model.check_access_rights('read')\n  File \"/home/odoo/src/odoo/13.0/odoo/models.py\", line 3204, in check_access_rights\n    return self.env['ir.model.access'].check(self._name, operation, raise_exception)\n  File \"<decorator-gen-22>\", line 2, in check\n  File \"/home/odoo/src/odoo/13.0/odoo/tools/cache.py\", line 90, in lookup\n    value = d[key] = self.method(*args, **kwargs)\n  File \"/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_model.py\", line 1548, in check\n    raise AccessError(msg % msg_params)\nodoo.exceptions.AccessError: (\"Sorry, you are not allowed to access documents of type 'Attachment' (ir.attachment). This operation is allowed for the groups:\\n\\t- User types/Internal User - (Operation: read, User: 4)\", None)\n", "message": "Sorry, you are not allowed to access documents of type 'Attachment' (ir.attachment). This operation is allowed for the groups:\n\t- User types/Internal User - (Operation: read, User: 4)\nNone", "arguments": ["Sorry, you are not allowed to access documents of type 'Attachment' (ir.attachment). This operation is allowed for the groups:\n\t- User types/Internal User - (Operation: read, User: 4)", null], "exception_type": "access_error", "context": {}}}}`
Current behavior:

Imposible to check available updates

Expected behavior:
Check available updates on apps

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/15079415/76967662-01524a80-6928-11ea-8241-1a7366814583.png)

Server version header:

![image](https://user-images.githubusercontent.com/15079415/76968040-905f6280-6928-11ea-9977-6575d2094ba9.png)

Update header:

![image](https://user-images.githubusercontent.com/15079415/76967982-76258480-6928-11ea-81ed-41eb0d8770e1.png)

**Comment by pedrobaeza** [comment] 2020-03-18 15:14
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/12.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).

**Closed by pedrobaeza** 2020-03-18 15:14 UTC

**Comment by vinclar** [comment] 2020-03-18 18:46
Manually updating web module solved the problem.
Updating base module seems  not to be sufficient.

**Comment by pedrobaeza** [comment] 2020-03-18 18:49
OK, glad to see that it's solved.

**Comment by vinclar** [comment] 2020-03-18 23:32
I said it too soon, don't know why but after a certain time after reinstalling the web module.
The issue comes back.

**Comment by microsound1** [comment] 2020-03-19 20:53
I have the exact the same issue as @vinclar

**Comment by vinclar** [comment] 2020-03-23 18:45
@microsound1 Do you use l10n_es_aeat modules?

**Comment by vinclar** [comment] 2020-03-25 20:13
Dear @pedrobaeza this is happening under this conditions:
Clean database with only installed the following module: l10n_es_aeat_sii  and it's dependencies.
I can't run an ocabot with [l10n-spain ](https://github.com/OCA/l10n-spain)OCA modules to proof you this. 
I thinks it's something related to [odoo apps store](https://apps.odoo.com/apps), it happens with some modules, not all of them for example it doesn't happen when only auditlog it's installed from [OCA/server-tools](https://github.com/OCA/server-tools)
Checked on version 12.0 and 11.0
--

[Update_Error.zip](https://github.com/odoo/odoo/files/4383304/Update_Error.zip)

**Comment by pedrobaeza** [comment] 2020-03-25 20:15
I'm afraid that something not reproduceable with standard core modules can't be logged here as bug. You need to dig the interactions between the modules the led to this problem.

**Comment by stupidgoats** [comment] 2020-03-26 18:35
Well @pedrobaeza that's cool because a bunch of people are having similar issues. 

Another below. Quick mark it duplicate and close it.

https://github.com/odoo/odoo/issues/48388

**Comment by stupidgoats** [comment] 2020-03-26 18:37
@pedrobaeza can you point me to any documentation on how I can test a community edition on the runbot? Trying to reproduce the error for ya but I am new to using the runbot and all the ones I found seemed to be for enterprise.

**Comment by pedrobaeza** [comment] 2020-03-26 18:44
Starting with, this is for 11.0 and 12.0, not for 13. There's no documentation as the idea is to reproduce the problem doing usual stuff on the system. I'm using these 3 versions on a lot of customers without problem and updating every day, so this seems a misuse, and nothing can confirm the contrary, here or in the other issue. I'm not managing the other issue as my colleague in the community started it, but a common problem doesn't mean necessary a bug in the code, but a common misuse.

**Comment by stupidgoats** [comment] 2020-03-26 19:44
@pedrobaeza Same error message. Similar Traceback. Probably same misuse across versions. Odd that it spontaneously started up with both updated and non-updated code bases in the past few weeks. 

Also our v11/12 issue isn't with actually updating. Although that is what the issue I linked to stated. It is trying to access the Updates which basically shows which third party modules on the Odoo app store have newer versions available.

Also it appears the traceback in our 12 versions is pointing to something with 13.0 in the path. From vinclar above. "/home/odoo/src/odoo/13.0/odoo/fields.py"

Care to point me to a place where I can ask more about my misuse?

Well @vinclar @microsound1 did either of you happen to find a solution or any more information?

**Comment by vinclar** [comment] 2020-03-26 20:10
Didn't find any solution, only ways to reproduce it with some modules from OCA, which are the only I use.
I have a vm environment with snapshots where the machines where the updates were working perfectly.
Restored them 1 month back, then I checked them, and the problem still is on, when at that time the problem didn't exist. 
Which makes me believe there's some change on the apps server from odoo or in the API who introduced the bug.

**Comment by stupidgoats** [comment] 2020-03-26 21:14
@vinclar I was able to solve the issue. 

Not by any of my expertise. There were issues with several OCA modules I had installed which were causing the error. The only way I was able to figure out which ones was by creating a clean db on my codebase and then installing the third party OCA modules one by one and checking for the error.

Once I identified them, I went out to the Odoo apps website and got the most recent version. Once I installed the latest version of the OCA apps the updates menu no longer gave me the error and loaded showing no updates.

List of Modules technical names which caused the issue for me follows.

1. mail_tracking
2. base_location
3. mail_activity_done
4. mail_activity_team

Hopefully it gets you in the right direction.

mail_tracking

**Comment by microsound1** [comment] 2020-03-26 21:25
@vinclar I have l10n_generic_coa and l10n_eu_service modules installed.
Thanks for the hint, I will check for updated OCA modules and list it here when I find which caused the issue.

**Comment by microsound1** [comment] 2020-03-28 22:33
Thank you again for the solution @stupidgoats .
In my case I had to upgrade the following modules:

- agreement
- web_widget_x2many_2d_matrix
- base_geoengine
- asset_management
- report_xlsx_helper
- stock_inventory_valuation_report

I can confirm that the issue is caused by outdated modules and because the error didn't help which module was the problem, I had to check one by one for updated version, However I am waiting for a module update to make sure it will appear on the Apps / Update page.

**Comment by Deimoks** [comment] 2020-03-31 15:03
This is the URL causing the error: https://apps.odoo.com/apps/embed/update

```
Server application error

 Error code: 200 
 Error message: Odoo Server Error 
 Error data message:
 Sorry, you are not allowed to access documents of type 'Attachment' (ir.attachment). This operation is allowed for the groups:
	- User types/Internal User - (Operation: read, User: 4)
None 
 Error data debug:
 Traceback (most recent call last):
  File "/home/odoo/src/odoo/13.0/odoo/api.py", line 745, in get
    value = self._data[field][record._ids[0]]
KeyError: 46738

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/13.0/odoo/fields.py", line 996, in __get__
    value = env.cache.get(record, self)
  File "/home/odoo/src/odoo/13.0/odoo/api.py", line 751, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('loempia.module(46738,).image_ids', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/13.0/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/home/odoo/src/odoo/13.0/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/home/odoo/src/odoo/13.0/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.access', <function IrModelAccess.check at 0x7f1892f62950>, 4, False, 'ir.attachment', 'read', True, ('es_ES',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/13.0/odoo/fields.py", line 1003, in __get__
    recs._fetch_field(self)
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 2935, in _fetch_field
    self._read(fnames)
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 3035, in _read
    field.read(fetched)
  File "/home/odoo/src/odoo/13.0/odoo/fields.py", line 2869, in read
    lines = comodel.search(domain, limit=self.limit)
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 1609, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/home/odoo/src/odoo/13.0/addons/calendar/models/ir_attachment.py", line 21, in _search
    return super(Attachment, self)._search(args, offset=offset, limit=limit, order=order, count=count, access_rights_uid=access_rights_uid)
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_attachment.py", line 410, in _search
    count=False, access_rights_uid=access_rights_uid)
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 4364, in _search
    model.check_access_rights('read')
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 3204, in check_access_rights
    return self.env['ir.model.access'].check(self._name, operation, raise_exception)
  File "<decorator-gen-22>", line 2, in check
  File "/home/odoo/src/odoo/13.0/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_model.py", line 1548, in check
    raise AccessError(msg % msg_params)
odoo.exceptions.AccessError: ("Sorry, you are not allowed to access documents of type 'Attachment' (ir.attachment). This operation is allowed for the groups:\n\t- User types/Internal User - (Operation: read, User: 4)", None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/13.0/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/home/odoo/src/odoo/13.0/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/home/odoo/src/odoo/13.0/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.access', <function IrModelAccess.check at 0x7f1892f62950>, 4, False, 'ir.attachment', 'read', True, ('es_ES',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/src/odoo/13.0/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/13.0/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 910, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/custom/private/loempia/controllers/embed.py", line 96, in update
    'ico': module.image_ids and '/apps/module_image?image_id=%s' % module.image_ids[0].id or '',
  File "/home/odoo/src/odoo/13.0/odoo/fields.py", line 2246, in __get__
    return super().__get__(records, owner)
  File "/home/odoo/src/odoo/13.0/odoo/fields.py", line 1005, in __get__
    record._fetch_field(self)
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 2935, in _fetch_field
    self._read(fnames)
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 3035, in _read
    field.read(fetched)
  File "/home/odoo/src/odoo/13.0/odoo/fields.py", line 2869, in read
    lines = comodel.search(domain, limit=self.limit)
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 1609, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/home/odoo/src/odoo/13.0/addons/calendar/models/ir_attachment.py", line 21, in _search
    return super(Attachment, self)._search(args, offset=offset, limit=limit, order=order, count=count, access_rights_uid=access_rights_uid)
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_attachment.py", line 410, in _search
    count=False, access_rights_uid=access_rights_uid)
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 4364, in _search
    model.check_access_rights('read')
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 3204, in check_access_rights
    return self.env['ir.model.access'].check(self._name, operation, raise_exception)
  File "<decorator-gen-22>", line 2, in check
  File "/home/odoo/src/odoo/13.0/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_model.py", line 1548, in check
    raise AccessError(msg % msg_params)
odoo.exceptions.AccessError: ("Sorry, you are not allowed to access documents of type 'Attachment' (ir.attachment). This operation is allowed for the groups:\n\t- User types/Internal User - (Operation: read, User: 4)", None)
```

Notice that this is an error returned by that URL somewhere at /home/odoo/src/odoo/13.0/odoo/ (that's not my path). It started happening several days ago, worked alright before that and no code has changed.

This issue is happening on versions 11 and 12 regardless of OS (tested on Windows and Linux) and it is also reported on version 13 here #48388

**Comment by stupidgoats** [comment] 2020-03-31 15:16
@Deimoks yeah we had a feeling something changed outside of our systems. The most recently updated modules from OCA do not seem to be having an issue with returning this error though.

I suppose you could do a code comparison on the different commits for those OCA modules to find out how they are handling the issue.

**Comment by instechMX** [comment] 2020-04-03 15:55
So how did you fix it? I had the same problem,.

**Comment by stupidgoats** [comment] 2020-04-03 19:42
@instechMX I don't think we specifically changed the code that fixed it. We found updated OCA modules which did not generate the error. If you need to find out the change in code then I would checkout the commits for some of the OCA modules we identified above. Additionally see the URL mentioned in @Deimoks comment. Best I can offer for assistance.

**Comment by vinclar** [comment] 2020-04-06 17:42
Hello guys, 
been investing a lot of time with the error, and didn't find any solution.
I created a new database and installed one by one all the modules that were installed on the other, checking the update function, and it was apparently working properly.
So I decided to update all the modules one by one, and for a day it was fixed, not just temporary like when I updated the web module, and check without refresh.
But it came back since the last git pull again. 
Did it come back to you? Or I'm the only one?

**Comment by stupidgoats** [comment] 2020-04-06 19:21
@vinclar yeah it is back for me but not from any code update as I havn't pulled any updates since. So...if I had to guess, Odoo changed something on https://apps.odoo.com/apps/embed/update or similar location. 

Begin /S

But don't worry, as @pedrobaeza has stated, because this is not a part of the actual Odoo application code and simply exists for letting people know if their Third Party modules have updates available (so wouldn't show up in a stock install ever, because it is specifically designed to support Third Party modules). So we can just move along as this is not happening on his machines. 

I guess we idiot peons who don't use stock Odoo alone will have to continue troubleshooting this ourselves because obviously Odoo has not changed anything.

End /S

On a side note, this error is hilarious, and truly annoying. I am going to compare the old code I had for some of my modules with the updated code to see if I can identify what fixed it and what is causing it now, but that will be several days before I can take the time to dig in. @vinclar thanks for bringing this back to my attention, and please share if you are able to figure something out before I am able to.

Thanks!

**Comment by stupidgoats** [comment] 2020-04-06 19:49
@vinclar had a sudden thought. What if the modules we updated were simply all of the modules which needed updates, and if no modules need updates then the error does not appear. So the code changes were not directly related, but rather prevented the system from ever triggering the error because nothing needed updating. At least when I ran the "Updates" action after "fixing" it - i did no have any modules to update.

@pedrobaeza we might have a situation where it could be Odoo's code. It will require the use of an out of date third party module to confirm specifically because this function of Odoo is only designed to function if Third Party modules are used on the installation.

Test scenario
1. Stock Odoo install and confirm no error.
2. Install any up to date 3rd party module published on Odoo.com app marketplace - confirm no error
3. Change the version number in the manifest file to be prior to the current published version - restart and update - see if error occurs

This would all be Odoo code related, but would not be possible to confirm via the runbot with no third party module installed.

@vinclar it will still be a couple of days before I can test this. But figured I would share the brainstorm.

@Yenthe666 We have never had any interactions, but I have always found you to be a reasonable person in your articles and replies I have read. We have had little help from the other "Collaborator" on this issue. Does this seem reasonable and what do we need to do to "prove" this error since the other "Collaborator" said we could not prove it?

**Comment by stupidgoats** [comment] 2020-04-06 20:55
I have one third party Odoo app which is using like 7 digits for his version control although I think it is by accident on his part. lol

![image](https://user-images.githubusercontent.com/31421058/78604096-3961f480-7827-11ea-8fa4-a56d12e3a05b.png)

**Comment by vinclar** [comment] 2020-04-06 21:23
I upgraded all the modules again, and only one is now breaking the function.
It's l10n_es_aeat_sii, in https://github.com/OCA/l10n-spain/tree/12.0/l10n_es_aeat_sii  the manifest it's a bit different from the odoo appstore, https://apps.odoo.com/apps/modules/12.0/l10n_es_aeat_sii/
manifest github version = "version": "12.0.1.3.0",
manifest apps.odoo.com = "version": "12.0.1.3.2",

Also the dependencies of the module are different.
Manifest on Github.com
```
    "external_dependencies": {
        "python": [
            "zeep",
            "requests",
            "OpenSSL",
        ],
    },
    "depends": [
        "account_invoice_refund_link",
        "l10n_es",
        "l10n_es_aeat",
        "queue_job",
    ],
```

Manifest apps.odoo.com:
```

   "external_dependencies": {
        "python": ["zeep",
                   "requests"],
    },
    "depends": [
        "account_invoice_refund_link",
        "l10n_es_aeat",
        "account_chart_update",
        "queue_job",
        "account_payment_partner",
    ],
```
Maybe duplicated names of the same module?

**Comment by gdgellatly** [comment] 2020-04-07 00:25
The problem is audit log module. It constantly causes errors like this sending you down a dependency black hole. As best as I can tell it happens when a module writes a record which usual user does not have access to

**Comment by stupidgoats** [comment] 2020-04-07 04:46
Unfortunately I am not using the audit log module but also have the issue :(

![image](https://user-images.githubusercontent.com/31421058/78630998-16f0cb00-7869-11ea-834e-08d694b31917.png)

**Comment by vinclar** [comment] 2020-04-07 20:57
I'm checking the [base module code ](https://github.com/odoo/odoo/blob/12.0/odoo/addons/base/models/ir_module.py)and they weren't inspired when they declared some fields.


`    # attention: Incorrect field names !!
    #   installed_version refers the latest version (the one on disk)
    #   latest_version refers the installed version (the one in database)
    #   published_version refers the version available on the repository
    installed_version = fields.Char('Latest Version', compute='_get_latest_version')
    latest_version = fields.Char('Installed Version', readonly=True)
    published_version = fields.Char('Published Version', readonly=True)
`

**Comment by vinclar** [comment] 2020-04-07 21:38
@stupidgoats  @Deimoks @pedrobaeza 

Well magically now it's working perfectly without touching or updating the code on production servers
So it was something related to odoo website or APIT

**Comment by pedrobaeza** [comment] 2020-04-08 08:02
I recommend you to use other deployment system different from this update system, as you can see is not the best, and it's not related to Odoo base code itself. You can use pip, or directly manage addons_path with git cloned repositories.

**Comment by Deimoks** [comment] 2020-04-08 08:24
@vinclar 
> Well magically now it's working perfectly without touching or updating the code on production servers
> So it was something related to odoo website or API

Can confirm. Thank you!

**Comment by vinclar** [comment] 2020-04-08 09:16
> I recommend you to use other deployment system different from this update system, as you can see is not the best, and it's not related to Odoo base code itself. You can use pip, or directly manage addons_path with git cloned repositories.

Thanks,
I use git to update the code on my scripts,
unfortunately the line that should update de modules seems not to be working.
The line is:
sudo service odoo12 restart -u all -d named

**Comment by pedrobaeza** [comment] 2020-04-08 09:20
That's not the way. The service management should be independent from update command line. It depends on the deployment, but it should be something like:
```
path_to_odoo/odoo -u all -d database --workers=0 --stop-after-init
sudo service odoo restart
```
Check also click-odoo-update for avoiding to need to update everything each time.

**Comment by vinclar** [comment] 2020-04-08 09:43
Thank you Pedro, as always an eminence.
I changed my script to this command:
sudo -u odoo12 -H sh -c "./odoo-bin -u all -d dbname -c /etc/odoo12.conf --workers=0 --stop-after-init"

I hope this does the job.

**Comment by pedrobaeza** [comment] 2020-04-08 09:47
Remember to restart also the Odoo service after for reloading registry with newest definitions. Ideally, you should stop service, perform the update, and start it again, for avoiding errors while not restarted (or concurrency issues while updating).

**Comment by stupidgoats** [comment] 2020-04-08 17:32
@vinclar mine is magically fixed now too! And while not a problem with the base odoo software code, it is a problem with the base odoo system or ecosystem. 

@pedrobaeza @vinclar do you have any recommended deployment system guides or reading?

Also I wasn't all that concerned about the feature itself, more that an error just popped up unexpectedly and I couldn't explain where it was coming from or why and didn't know what else might have been broken by it. 

Thank you so much @vinclar

**Comment by pedrobaeza** [comment] 2020-04-08 17:54
We use https://github.com/Tecnativa/doodba for deploying staging, devel and production environments. We have dumped all our knowledge and experience there.

**Comment by stupidgoats** [comment] 2020-04-08 19:18
Awesome! Thanks @pedrobaeza ! Greatly appreciated!
