### ISSUE TITLE
"run manual" cronjob isn't working as expected, passed self is kinda 'Null'

### ISSUE THREAD

**Issue by SnoozeFreddo** [odoo/odoo#52131] opened 2020-05-28 17:06 UTC
Impacted versions: 13

Steps to reproduce:
create cronjob:
```
<record id="my id" model="ir.cron">
            <field name="name">Synchronisieren der Messenger-Organisationen nach Odoo</field>
            <field name="model_id" ref="my_app.model_my_model"/>
            <field name="active" eval="False"/>
            <field name="user_id" ref="base.user_root"/>
            <field name="interval_number">1</field>
            <field name="interval_type">days</field>
            <field name="numbercall">-1</field>
            <field name="state">code</field>
            <field name="code">model.cron_blabla()</field>
            <field name="nextcall">2010-01-01 02:00:00</field>
        </record>

```
and my_model.py has : 

```
@api.model
    def cron_blabla(self):
        running_jobs = self.env['some.model'].sudo().search([])
```

Current behavior:
No error in the log, but it doesn't do anything. The debugger can't retrieve the self value thus i can't perform the typical self.env['my.model'] and if i let it run i get an eternal odoo loading screen.

"running_jobs = self.env['some.model'].sudo().search()"  accessing here self is a for some reason a problem.

Expected behavior:
The function should run, self.env['xyz'] should work

**Comment by pedrobaeza** [comment] 2020-05-28 17:12
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2020-05-28 17:12 UTC
