### ISSUE TITLE
[website_less] conditions (t-if) in assets_frontend breaks java script and css loading

### ISSUE THREAD

**Issue by michaelkarrer81** [odoo/odoo#9289] opened 2015-10-28 15:22 UTC
### How to reproduce
- Install website_less
- Load any addon which inherits from website.assets_frontend AND has some conditional loading of java script or css
#### Example:

```
ader and Footer if the Website was called throug http://baseurl/aswidget/realpath -->
<template id="assets_frontend" inherit_id="website.assets_frontend" name="assets_frontend website_as_widget">
    <xpath expr="." position="inside">
        <t t-if="request.session.get('aswidget', False) is True">
            <link rel='stylesheet' href='/website_as_widget/static/src/css/website_as_widget.css'/>
            <script type="text/javascript" src="/website_tools/static/lib/iframe-resizer/js/iframeResizer.contentWindow.min.js"></script>
        </t>
    </xpath>
</template>
```
#### Result

Loading/Minify of Java Script and or CSS is broken 
### How i found the bug?:
- Installed latest odoo v8.0 on ubuntu 14.04 with lessc compiler and clean css plugin
- install addon theme_graphen
- add some animated snippets and/or a video to the start page (works as expected when logged in)
- log out
- open the page in safari
#### Result:
- The video and animation (and everything related to java script) will FAIL in Apples Safari if we are not logged in as an odoo user
#### Notes:
- The video and the animation are working fine in google chrome and mozilla firefox
- The video and the animations are working fine in Safari **only if we are logged in as an odoo user** ?!?!

URL: http://eurasiaheart.demo.datadialog.net

We are one of the main sponsor of the themes campaign (Datadialog) and really would need some help with this in an ongoing project!

**Comment by odony** [comment] 2015-10-29 12:14
@qsm-odoo Maybe you could have a look while you're working on the themes? Thanks!

**Comment by odony** [comment] 2015-10-29 12:21
@michaelkarrer81 Could you specify under which version of OSX and Safari/iOS you reproduce this? Also, is there a page currently on your website where the problem is visible? (or maybe you can provide a video showcasing the bug?). I browsed the URL under Safari 8.0.8 and OS X 10.10 and could not spot the bug.

**Comment by qsm-odoo** [comment] 2015-10-30 13:29
@michaelkarrer81 Hello, I took a look on this problem too and did not spot the bug either (after tests on odoo v8, theme graphene, video and animation snippets, on safari v6 and v8). A demonstration video or any other information would be great, thank you.

**Comment by michaelkarrer81** [comment] 2015-11-04 08:26
@odony @qsm-odoo Thank you for your replies - i found the cause of the broken css and java script - please see my comments in the topmost issue description.

Any idea how to fix this?

**Comment by qsm-odoo** [comment] 2015-11-04 13:13
@michaelkarrer81 Hello, have you an example of a v8.0 addon which uses a condition in such a template? I have tried with custom code (adding a condition in such a template in a working module) and it did not generate any error. Is any error message occurs on the server / browser console when the bug is happening?

**Comment by michaelkarrer81** [comment] 2015-11-05 11:16
@qsm-odoo There is an error message about missing less variables and also java script will not load correctly in safari: java script is there but it just fails without an error message.

This addon would be an example:
https://github.com/OpenAT/odoo_v8.0/tree/master/addons-own/website_as_widget
https://github.com/OpenAT/odoo_v8.0/blob/master/addons-own/website_as_widget/views/templates.xml

**Comment by odony** [comment] 2015-11-05 11:51
Just a thought: maybe your custom code doesn't work because it does not take into account the automatic cache of public page. The framework will automatically cache page views for public user sessions (visitors that are not logged in), and will not trigger the full rendering nor recompute assets. As a result you can't expect the assets to be recomputed on every page view on public sessions, or you need to disable the cache entirely.
For full user sessions the cache is disabled because the results are possibly different for every user.

**Comment by michaelkarrer81** [comment] 2015-11-05 12:06
@odony thank you very much for your thought - but my thinking is that  even if the assest are not recalculated they still should work: Even if those css and java script files inside the if condition could sometimes be loaded and sometimes not it still should not break the java script nor the css - right? 

But thats exactly what happens: Install the addon or any other addon with an t-if in the frontend assest and the theme graphene is completely broken. (Media box will not load, no affix menu..., wrong missing css styles)

**Comment by michaelkarrer81** [comment] 2015-11-05 12:08
INFO: If i uninstall the related addon again theme graphen works as expected again.

**Comment by michaelkarrer81** [comment] 2015-11-05 12:19
INFO2: The addon mentioned above works perfectly without a installed custom theme. 

@odony But anyway is there a correct/better way to load a custom css (e.g.: to permanently hide the footer) for a user session depending on the Initial url called (e.g.: http://www.home.com/aswidget)

I did sore a parameter aswidget to the session since i want to be 100% sure the css is loaded for every page of the website (webpage, forumpage, shop etc.) even if the request params are not passed to any of the webcontrollers (which can not be guaranteed).

**Comment by odony** [comment] 2015-11-05 12:51
I'm not sure of the exact requirements so I'm a bit shooting in the dark here.
Gor starters I would avoid generating different assets for different users/sessions. The assets bundles are meant to be statically determined and global based on the installed/enabled features. They're cached and managed that way, so you're bound to have *some* problems (if only, perf issues due to recomputing them too often) if you break that rule.
You should have the "custom css" always loaded and turn its effects on/off based on the presence of a special DOM attribute. Usually this is done simply by adding a CSS class to one of the top-level elements of the website.
You could even add this class  based on a cookie stored on the user's session (to avoid public caching issues), although that might cause some flickering when the CSS class is added/removed, depending on when you do it during page load. Other methods to enable/disable CSS effects are possible and common in responsive websites, such as rules based on the available size of the screen, etc.

**Comment by michaelkarrer81** [comment] 2015-11-05 13:08
@odony thank you very much for your hints - will try this way too - but due to my fault this is drifting off topic - so back to the bug :)

**Comment by michaelkarrer81** [comment] 2015-11-12 15:11
@qsm-odoo could you please verify that this is a bug?

**Comment by michaelkarrer81** [comment] 2015-11-16 13:07
@odony My use Case would be tor make the assests bound to the URL so:

URL A (e.g.: www.template_a.com) will always render frontend assets A
URL A (e.g.: www.template_b.com) will always render frontend assets B

Or in other words the theme of the website should be bound (selected by) the url of the website.

Is there a "correct" way to do this in odoo v8.0

**Comment by rafaelbn** [comment] 2015-11-16 19:27
cc @antespi

**Comment by qsm-odoo** [comment] 2017-12-06 16:11
Hello,
Sorry I was not able to help you at the time. There is actually no plan to support conditional assets' parts but I think that is not really what you wanted: you still have the possibility to create new assets and link them conditionally on your page (basically, the `t-if` would be in the page template but not in the assets' one). We will also probably improve our multi-website features in the future to maybe allow such cases to be handled more intuitively.
Again, sorry if I did not help you correctly at the time. I am closing the issue, do not hesitate if you have any new question for version 9.0 or higher.

**Closed by qsm-odoo** 2017-12-06 16:11 UTC
