### ISSUE TITLE
Product Comparison is not properly working for eCommerce[website_sale, website_sale_comparison] module

### ISSUE THREAD

**Issue by hareshjupical** [odoo/odoo#47684] opened 2020-03-16 11:02 UTC
Impacted versions: V11 Community

Steps to reproduce: Go to odoo runbot and select database with demo data. Now go to shop page and select two products (Bose Mini Bluetooth Speaker, iPad Mini). for comparison. Now click on compare button from bottom. Now it will redirect to compare page. Here you will see one error (500: Internal Server Error). 

Current behavior: When we compare any two products then product comparison feature works perfect but for some products, it will giving straight forward error.

This is working correctly but only not working for some products.

Expected behavior: Product comparison will work correctly without any error.

As we have checked for controller (/shop/compare/), then we have found that it's due to following line:
res[cat_name][att_name][num] = val[0].name

Video/Screenshot link (optional):

https://drive.google.com/open?id=1O2KRyXacaka1AT8WQEWZ5dFq03H-Y2yR

**Comment by pedrobaeza** [comment] 2020-03-16 11:31
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by sswapnesh** [comment] 2020-03-16 18:36
I can confirm this Bug
Added Fix at https://github.com/odoo/odoo/pull/47728

**Comment by sswapnesh** [comment] 2020-04-22 17:51
This has been fixed in https://github.com/odoo/odoo/commit/51cfd1cfa7d1c88f0e77823032c5dd06614f9b08

**Closed** 2020-04-22 18:17 UTC
Labels: Need information
