### ISSUE TITLE
Odoo 12 Enterprise Issue in Manufacturing.  It is not possible to unreserve more products of "Product Name" than you have in stock. 

### ISSUE THREAD

**Issue by DonFeraRRi** [odoo/odoo#39137] opened 2019-10-21 15:15 UTC
Impacted versions: odoo12

Steps to reproduce: Created a Manufacturing Order. Completed the Work order. Clicking Mark as Done. The error is coming.

Current behavior: Struggling with the error. I duplicated the Manufacturing order and processed it. It closed smoothly without any issue/error.

Expected behavior: Manufacturing order should move to done state as soon as Mark As done is clicked.

Video/Screenshot link (optional): https://ibb.co/Lp5PntS

**Comment by pedrobaeza** [comment] 2019-10-21 16:24
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Yenthe666** [comment] 2019-12-03 08:04
Hi there,

Since we haven't gotten any feedback in a while I'm closing off this issue.
Don't hesitate to respond back with more information. We'll reopen the issue if there is enough information to explain this issue.

Regards,
Yenthe

**Closed by Yenthe666** 2019-12-03 08:04 UTC
Labels: 12.0, Logistics, Need information
