### ISSUE TITLE
PDF report menu items not showing under Reporting menu in Accounting module.

### ISSUE THREAD

**Issue by kbirkbr** [odoo/odoo#28858] opened 2018-11-21 06:51 UTC
Impacted versions: Odoo 11 EE

Steps to reproduce:

1. Create a new database.
2. Install `account_accountant` module.

Current behavior:

Not appearing PDF reports under Reporting Menu in Accounting module.
Not even list out in Menu items under  Settings -> Technical -> User Interface.
Have to refresh the `account` module to make PDF report menu visible.

Expected behavior:

Show PDF reports under Reporting Menu in Accounting module

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2018-11-21 08:34
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile or it's a misconfiguration problem, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-11-21 08:34 UTC
