### ISSUE TITLE
first bill -> AttributeError: 'dict' object has no attribute 'write'

### ISSUE THREAD

**Issue by werkwolk** [odoo/odoo#66558] opened 2021-02-19 16:47 UTC
Impacted versions: Odoo 14 community latest runbot build

Steps to reproduce: enable full accounting features for user admin -> go to invoices -> create first bill -> press next

Current behavior: throws exception AttributeError: 'dict' object has no attribute 'write'
 

Video/Screenshot link (optional): 
![image](https://user-images.githubusercontent.com/69362083/108534203-2be81880-72da-11eb-93a8-ab511dc68d80.png)

**Comment by pedrobaeza** [comment] 2021-02-19 19:23
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by pedrobaeza** [comment] 2021-02-19 19:24
I'm missing what the `Next` mean in your steps.

**Comment by werkwolk** [comment] 2021-02-19 21:51
yes i've taken the pic from the version: Odoo 14 community latest runbot build (https://6302689-14-0.runbot32.odoo.com/)

You enable the full accounting for admin/admin

you go to the invoice module which now shows the full accounting features

in the onboarding panel you click the most left "lets start"

with "next" i meant the "continue" button. My apologies. 

then the exception is thrown

**Comment by werkwolk** [comment] 2021-02-19 21:54
> If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.
> 
> If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.
> 
> For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

yes i fully understand. i'm new to odoo and had to adapt to bug reporting. will make sure to have runbot examples. Not sure where i can go with config matters, but since i've switched to windows i haven't had any config problems.

**Comment by Yenthe666** [comment] 2021-02-22 08:15
Confirmed on the latest 14.0 runbot:
![image](https://user-images.githubusercontent.com/6352350/108680628-64f8d680-74ee-11eb-8fde-140a52090164.png)


@qdp-odoo :)

**Comment by folkn** [comment] 2021-03-06 16:28
I can confirm that I have the same problem on 14.0
![image](https://user-images.githubusercontent.com/1535393/110213676-de30eb80-7e55-11eb-95b1-dc4cb1828c56.png)

**Comment by sswapnesh** [comment] 2021-03-30 17:44
Added Fix at #68561

**Comment by sswapnesh** [comment] 2021-03-31 18:02
Fixed in https://github.com/odoo/odoo/pull/67573

**Comment by Yenthe666** [comment] 2021-03-31 18:23
https://github.com/odoo/odoo/commit/2252cae941efcca36f981d50c546cacf70ff760d

**Closed by Yenthe666** 2021-03-31 18:23 UTC
Labels: 14.0, Accounting, Confirmed
