### ISSUE TITLE
Odoo crashes when editing website in an other language than english

### ISSUE THREAD

**Issue by implefy** [odoo/odoo#44672] opened 2020-02-05 17:05 UTC
Impacted versions: 13.0

Steps to reproduce:
Go to website module, press go to website. Then change language to Swedish

Current behavior: Crashes with the log:
2020-02-05 17:01:19,462 21647 ERROR fredrik_webshop odoo.sql_db: bad query: UPDATE "website_visitor" SET "write_uid"=2,"lang_id"=78,"write_date"=(now() at time zone 'UTC') WHERE id IN (1)
ERROR: could not serialize access due to concurrent update

2020-02-05 17:01:19,464 21647 INFO fredrik_webshop werkzeug: 127.0.0.1 - - [05/Feb/2020 17:01:19] "GET /sv/ HTTP/1.0" 500
- 415 0.151 0.399
2020-02-05 17:01:19,468 21647 ERROR fredrik_webshop werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/srv/src/odoo/odoo/service/server.py", line 414, in app
    return self.app(e, s)
  File "/srv/src/odoo/odoo/service/wsgi_server.py", line 140, in application
    return ProxyFix(application_unproxied)(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/contrib/fixers.py", line 152, in __call__
    return self.app(environ, start_response)
  File "/srv/src/odoo/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/srv/src/odoo/odoo/http.py", line 1281, in __call__
    return self.dispatch(environ, start_response)
  File "/srv/src/odoo/odoo/http.py", line 1251, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/wsgi.py", line 766, in __call__
    return self.app(environ, start_response)
  File "/srv/src/odoo/odoo/http.py", line 1454, in dispatch
    response = self.get_response(httprequest, result, explicit_session)
  File "/srv/src/odoo/odoo/http.py", line 280, in __exit__
    self._cr.commit()
  File "/srv/src/odoo/odoo/sql_db.py", line 163, in wrapper
    return f(self, *args, **kwargs)
  File "/srv/src/odoo/odoo/sql_db.py", line 388, in commit
    flush_env(self)
  File "/srv/src/odoo/odoo/sql_db.py", line 67, in flush_env
    env['base'].flush()
  File "/srv/src/odoo/odoo/models.py", line 5230, in flush
    process(self.env[model_name], id_vals)
  File "/srv/src/odoo/odoo/models.py", line 5221, in process
    recs._write(vals)
  File "/srv/src/odoo/odoo/models.py", line 3537, in _write
    cr.execute(query, params + [sub_ids])
  File "/srv/src/odoo/odoo/sql_db.py", line 163, in wrapper
    return f(self, *args, **kwargs)
  File "/srv/src/odoo/odoo/sql_db.py", line 240, in execute
    res = self._obj.execute(query, params)
psycopg2.extensions.TransactionRollbackError: could not serialize access due to concurrent update - - -

Expected behavior:
No crash

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2020-02-05 17:11
This seems to be because other thing, which is concurrent access to same resource, due to deployment or chance of being doing the same in 2 places.

Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

**Comment by implefy** [comment] 2020-02-05 17:18
@pedrobaeza I cannot reproduce it on runbot, however I'm more concerned with the first error 
2020-02-05 17:01:19,462 21647 ERROR fredrik_webshop odoo.sql_db: bad query: UPDATE "website_visitor" SET "write_uid"=2,"lang_id"=78,"write_date"=(now() at time zone 'UTC') WHERE id IN (1)

**Comment by pedrobaeza** [comment] 2020-02-05 17:19
That one is derived from the other. Please check your concurrences and you will prevent this. Obviously, if the site is public and there are visitors to the exact page, there is likely to happen them.

Closing then as circumstantial thing.

**Closed by pedrobaeza** 2020-02-05 17:19 UTC
Labels: Need information

**Comment by implefy** [comment] 2020-02-05 18:03
@pedrobaeza  what do you mean with check your concurrences? I've one odoo instances running on one computer, with one database with nginx in front of it. If odoo has a race condition with itself it must be an issue, right?

**Comment by pedrobaeza** [comment] 2020-02-05 18:05
If you are not able to reproduce it on runbot, then it's not a race condition. It's something on your side.

**Comment by implefy** [comment] 2020-02-07 08:33
much likely it's something on my side, but it's a very reproduceable error. Everytime I change the language to non-english I get this crash. So I've run
find . -name "*.py" -exec grep -H "website_visitor" {} \;

to find where this query is coming from and it doesn't seem to be a part of the code at all. Can you confirm this? How can I see where this query comes from?

**Comment by pedrobaeza** [comment] 2020-02-07 14:50
I can't say, sorry
