### ISSUE TITLE
[12.0/ 3.0] Framwork level issue : After sorting on column not able to Order/DragDrop the records in listview. (Using Handle widget in listview)

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#38569] opened 2019-10-13 09:41 UTC
Impacted versions: 12.0 / 13.0

Steps to reproduce:

- Open any listview having sequence (widget Handle)
- Drag and Drop row, it will allow you.

Current behavior:
- It is not allowing  Ordering / Drag and Drop to rows of listview after Sorting any column of that listview.

Expected behavior:
- it should allow dragging/ordering of records in listview.

Video/Screenshot link (optional):
[Video ref ](https://youtu.be/fLJzBwhLGdI)

Thanks!

**Comment by pedrobaeza** [comment] 2019-10-13 12:55
This is something expected and forbidden by design, as reordering in that sorted list will reorder all the rows according that sorting and will provoke a massive change that can't be controlled by the user (specially on very long sets with a lot of records).

Closing thus as not issue, but designed that way.

**Closed by pedrobaeza** 2019-10-13 12:55 UTC
Labels: 12.0, 13.0, Framework
