### ISSUE TITLE
[9.0] Bug when restore with the backup database not include filestore

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#9296] opened 2015-10-29 04:45 UTC
Hi Odoo,

When I restored the database that I backup with option not include filestore,
I cannot enter the system, as it have a blank screen, and the log say I dont have some file on my filestore.

The expected behavior should be I still can enter the system, and its not a blank screen.
and I will understand if I open the attachment and its not there yet because I don't copy it yet.

Thank You.

**Comment by aisopuro** [comment] 2016-05-16 08:04
We encountered the same problem in our system. The problem seems to be that Odoo generates the backed web assets beforehand (i.e. compiles `.less`, minifies `.js` etc). These files are saved in the filestore, and references to these files are saved in the `ir_attachment`-table. However, when copying the database without the filestore, these entries in `ir_attachment` remain, and Odoo can't seem to relize that they are no longer valid. Instead of generating new files, it returns an error to the JavaScript engine in the browser, and the browser fails to render the view.

You can verify whether this is the case if it works in debug mode: add `?debug=` to the end of your URL
```
yourodoo.com/web?debug=
```
If the site starts working, it means you have this problem, because debug mode forces Odoo to not use the pre-generated assets.

This is speculation based on the fact that we faced the same problem as described by @falinwa (grey screen, unable to do anything) and saw these messages in the logs:
```
2016-05-06 09:07:25,787 1 INFO database-name openerp.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/<database name>/82/825be0a9492aa429844218238d35347d6a3c9220
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_attachment.py", line 105, in _file_read
    r = open(full_path,'rb').read().encode('base64')
IOError: [Errno 2] No such file or directory: u'/var/lib/odoo/filestore/<database name>/82/825be0a9492aa429844218238d35347d6a3c9220'
```
We run our Odoo inside Docker, so it is possible that part of the problem stems from that. However, we were able to fix this problem with a workaround: manually going into the database and removing the entries pointing to the missing files:
```
DELETE FROM ir_attachment WHERE store_fname LIKE '%<the ending hash>%'
```
So the above error would be fixed by doing
```
DELETE FROM ir_attachment WHERE store_fname LIKE '%8ef9c5770a09153250c8d58d91d98d02f737b19a%';
```
After doing this for every problematic file, Odoo re-compiled all the assets and the backend started working again.

I would specify this as the expected behaviour:

If Odoo cannot find the file specified in the `ir_attachment`-table, i.e trying to access it raises an `IOError`, Odoo should remove that entry from the table and signal the caller that no attachment was found.

**Comment by Yenthe666** [comment] 2016-05-24 07:00
Hi @falinwa and @aisopuro,

Could one of you test this again with the latest codebase please?
I couldn't reproduce this. I will leave this issue open for now, please let me know if this has been fixed or not.
In case it is not fixed: could you please give detailed information about how to reproduce this?

**Comment by aisopuro** [comment] 2016-05-25 10:50
We run our build of Odoo inside Docker, and I unfortunately do not have the time right now to build a fresh image. The one we use is based on the nightly build for 18th of March 2016 (20160318). It is entirely possible this is based on some Docker weirdness.

I did however just copy over a database to my local environment and have been given the same errors again. Here are the steps I took:

1. Have a database up and running on a separate system. Make sure it functions correctly. Open any views you can think of, do not use `debug` mode.
2. Take a backup of said database from the database maangement view (`/web/database/manager`). Select to take a `pg_dump`, without filestore.
3. Start up the same Odoo code in a different filesystem (it is not enough to just copy the database in place)
4. Restore the backup taken in part 2.

#### Expected behaviour
By selecting the restored database, you should be shown the main Odoo dashboard.
#### Actual behaviour
You will see a number of errors in you server log:
```
odoo_1 | 2016-05-25 10:15:53,259 1 INFO database openerp.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/database/4d/4d248d296d600e6775110839df4329790f7c124b
odoo_1 | Traceback (most recent call last):
odoo_1 |   File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_attachment.py", line 105, in _file_read
odoo_1 |     r = open(full_path,'rb').read().encode('base64')
odoo_1 | IOError: [Errno 2] No such file or directory: u'/var/lib/odoo/filestore/database/4d/4d248d296d600e6775110839df4329790f7c124b'
odoo_1 | 2016-05-25 10:15:53,264 1 INFO database werkzeug: 172.18.0.1 - - [25/May/2016 10:15:53] "GET /mail/static/src/less/web.assets_backend/announcement.less.css HTTP/1.1" 304 -
```
 Additionally, the browser will display a white background with a number of errors on it:
```
"Could not get content for /web/static/src/less/bootstrap_overridden.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/touch_device.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/webclient.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/webclient_layout.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/navbar.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/datepicker.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/progress_bar.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/dropdown.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/tooltip.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/debug_manager.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/app_switcher.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/app_switcher_layout.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/control_panel.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/control_panel_layout.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/views.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/pivot_view.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/graph_view.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/tree_view.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/form_view_layout.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/form_view.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/list_view.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/search_view.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/data_export.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/compatibility.less defined in bundle 'web.assets_backend'.
 NameError: variable @odoo-sheet-vpadding is undefined in - on line 1477, column 36:
 1476 margin: @odoo-horizontal-padding auto;
 1477 .o-webclient-padding(@top: @odoo-sheet-vpadding, @bottom: @odoo-sheet-vpadding);
 1478 .o_account_reports_level0 {
 
 This error occured while compiling the bundle 'web.assets_backend' containing:
 - /website/static/src/less/import_bootstrap.less
 - /web/static/lib/bootstrap-datetimepicker/src/less/bootstrap-datetimepicker.less
 - /web/static/src/less/variables.less
 - /web/static/src/less/bootstrap_overridden.less
 - /web/static/src/less/utils.less
 - /web/static/src/less/touch_device.less
 - /web/static/src/less/webclient.less
 - /web/static/src/less/webclient_layout.less
 - /web/static/src/less/navbar.less
 - /web/static/src/less/datepicker.less
 - /web/static/src/less/progress_bar.less
 - /web/static/src/less/dropdown.less
 - /web/static/src/less/tooltip.less
 - /web/static/src/less/debug_manager.less
 - /web/static/src/less/app_switcher.less
 - /web/static/src/less/app_switcher_layout.less
 - /web/static/src/less/control_panel.less
 - /web/static/src/less/control_panel_layout.less
 - /web/static/src/less/views.less
 - /web/static/src/less/pivot_view.less
 - /web/static/src/less/graph_view.less
 - /web/static/src/less/tree_view.less
 - /web/static/src/less/form_view_layout.less
 - /web/static/src/less/form_view.less
 - /web/static/src/less/list_view.less
 - /web/static/src/less/search_view.less
 - /web/static/src/less/modal.less
 - /web/static/src/less/data_export.less
 - /web/static/src/less/compatibility.less
 - /account/static/src/less/account_reconciliation.less
 - /account/static/src/less/account_journal_dashboard.less
 - /account_reports/static/src/less/account_financial_report.less
 - /base_import/static/src/less/import.less
 - /mail/static/src/less/announcement.less
 - /mail/static/src/less/client_action.less
 - /mail/static/src/less/chat_window.less
 - /mail/static/src/less/composer.less
 - /mail/static/src/less/chatter.less
 - /mail/static/src/less/thread.less
 - /sales_team/static/src/less/sales_team_dashboard.less
 - /web_tip/static/src/less/tip.less
 - /web_calendar/static/src/less/web_calendar.less
 - /web_diagram/static/src/less/diagram_view.less
 - /web_gantt/static/src/css/gantt.less
 - /web_kanban/static/src/less/kanban_dashboard.less
 - /web_kanban/static/src/less/kanban_view.less
 - /web_settings_dashboard/static/src/less/dashboard.less
 Could not get content for /web/static/src/less/bootstrap_overridden.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/touch_device.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/webclient.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/webclient_layout.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/navbar.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/datepicker.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/progress_bar.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/dropdown.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/tooltip.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/debug_manager.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/app_switcher.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/app_switcher_layout.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/control_panel.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/control_panel_layout.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/views.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/pivot_view.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/graph_view.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/tree_view.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/form_view_layout.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/form_view.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/list_view.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/search_view.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/data_export.less defined in bundle 'web.assets_backend'.
 Could not get content for /web/static/src/less/compatibility.less defined in bundle 'web.assets_backend'."
```
The error message originally contained `\A` instead of newlines, as it was inserted as a CSS `content` value on `body:before`.

While I admit that this may not be reproducible without our specific docker setup, I would still argue that this is a bug. My understanding of this behaviour is that Odoo stores pre-compiled website content (HTML, CSS and JavaScript) in files on the filesystem so that they do not need to be recompiled on every request. This is a great feature and is absolutely the way to do it.

However, what causes this error seems to me to be that the system expects to find a precompiled file somewhere, and then doesn't. In this situation it does not seem to me to be an error, but more like a cache miss: we hoped to find a file so that we could serve the web page, but it wasn't there. Instead of failing to render the web page entirely, I think that Odoo should do what it does if it does not find any mention of this precompiled file in the first place. It should compile all the necessary assets as if this were the first time someone was opening the web page.

The basic problem seems to be a missing special case in the design:
1. Can't find any reference to this in `ir_attachments` -> **OK**, generate the file and return its contents
2. Can find a reference in `ir_attachment`, and the referenced file can be opened -> **OK**, return the file contents
3. Can find a reference to the file in `ir_attachment`, but it isn't in the filestore -> **ERROR**

I think item 3. should work like item 1.

**Comment by Yenthe666** [comment] 2016-05-25 11:06
@mart-e who could I assign to look in to this? I don't know who the Docker expert is at Odoo. :+1:

**Comment by Yenthe666** [comment] 2016-06-22 07:29
@aab-odoo could you have a look at this?

**Comment by moylop260** [comment] 2016-06-23 14:30
I use dialy the database wizard in our runbot based on docker without problem.

Your main issue is

> Select to take a pg_dump, without filestore.

Try `with` filestore.

Or copy the filestore path from source.

We had this issue in our CI 
https://github.com/OCA/maintainer-quality-tools/issues/299

And was fixed copying filestore
https://github.com/OCA/maintainer-quality-tools/pull/304

Could you try?

**Comment by mart-e** [comment] 2016-06-24 08:08
As said Moises, if you dump the database without the filestore, don't be surprised to get errors regarding the filestore.
You will want to use this option if you move the filestore manually (e.g. too big to be used via web interface so will be copied manually).

If you want to fix this, you will need to delete the attachments linked to the assets (or go in debug mode).

**Closed by mart-e** 2016-06-24 08:08 UTC

**Comment by sylnsr** [comment] 2017-03-09 15:43
Why doesn't anyone explain how to simply rebuild the filestore ?

**Comment by aisopuro** [comment] 2017-03-09 16:12
@sylnsr, we have found the following (technical) way of fixing the above issue: you will need to gain direct access to your database, or possibly you could do this from the shell. So if you are running into this problem on Odoo Online, this will not work.

The problem stems from the fact that Odoo thinks there are pre-compiled JavaScript and CSS-files somewhere, when there actually aren't. So you need to delete Odoo's references to those files so that it rebuilds them. I do not know of a way to trigger this rebuilding from the UI.

Gaining access to your database depends on you setup: maybe you use `psql` directly from the command line, or PgAdmin, or some other solution. You should not need to have the Odoo instance running, just the database, so googling for "postgresql browse database" ought to get you started.

Once you have connected to the database you need to fix, you need to delete those `ir.attachment` records that refer to the missing assets. These are always either JavaScript or CSS files, so deleting anything where the referenced filename ends with `.js` or `.css` should do the trick. We use the following:

```sql
DELETE FROM ir_attachment WHERE datas_fname SIMILAR TO '%.(js|css)';
```

**Comment by sylnsr** [comment] 2017-03-09 18:38
I still need to rebuild the file store in Docker.

**Comment by aisopuro** [comment] 2017-03-10 14:36
Unfortunately we have found no way of rebuilding the filestore: if you did not transfer it by taking a `zip` format backup, I don't know how you'd restore it separately.

**Comment by sylnsr** [comment] 2017-03-16 18:11
@aisopuro I am only referring to the files in the filestore that were created when the DB is created for the first time. I am not referring to attachments uploaded by users.  My thinking follows that if Odoo's python code initially created the filestore for a newly created database, say for example, a new DB named "dev" into `filestore/dev/` then it follows that the same python code should be able to be re-run to do that same thing it did when the "dev" DB was first created ... that is to say, build the filestore assets for the "dev" DB back into `filestore/dev`. If it did it once then certainly there should be an idiomatic way to have Odoo do it again.

**Comment by sylnsr** [comment] 2017-03-16 19:05
Solution for Docker: Just delete the assets as indicated above by aisopuro the `docker exec -it <container-name-for-server> bash` to get a term in the server container. Stop odoo: `service odoo stop`. Update all modules (which also starts odoo running again)`. This causes odoo to rebuild the filestore for base assets.

**Comment by quesad** [comment] 2017-03-21 17:23
This work for me.
1. First you need to map the volume /var/lib/odoo in your odoo container ex: -v  /data/odoo/filestore:/var/lib/odoo/filestore. (from official Odoo docker  documentation).
2. delete all in ir_attachment.
3. update base.
Keeping the filestore in a volume mapped to the docker host allows you to destroy and create the odoo container without having the issue with the filestore.

**Comment by ardeearam** [comment] 2019-12-17 06:03
In Odoo 13, there is no more `datas_fname` field. 

Deleting all entries in `ir_attachment` solved the problem for me.

**Comment by traviswaelbro** [comment] 2020-02-27 16:01
I had an issue in Odoo 13 with report styles rendering on one database but not rendering on another.

I was able to identify the missing styles by switching a report from **Report Type** of "PDF" to "HTML". Then, I printed that report and it partially renders the report before throwing an error:

> Style error
>
> The style compilation failed, see the error below. Your recent actions may be the cause, please try reverting the changes you made.
>
> Could not get content for /web/static/src/scss/report_styles.scss defined in bundle 'web.report_assets_common'.

Once I had the URL which was being accessed and failing, I could do some checking in the `ir.attachments` table (this could be done similarly through the frontend's **Settings > Technical > Database Structure > Attachements** menu).

#### Working Database

```sql
db_name=# SELECT
    id, name, company_id, type, url, store_fname, mimetype, LEFT(index_content, 100) AS index_content
FROM ir_attachment
WHERE url = '/web/static/src/scss/report_styles.scss';

 id |       name       | company_id |  type  |                   url                   |                 store_fname                 | mimetype  |                                            index_content
----+------------------+------------+--------+-----------------------------------------+---------------------------------------------+-----------+------------------------------------------------------------------------------------------------------
  4 | res.company.scss |          1 | binary | /web/static/src/scss/report_styles.scss | 60/60f944bb91adcadffd2d1edadb68ab37ddf593e8 | text/scss | $o-company-font: 'Lato';$o-company-primary-color: rgb(0, 0, 0);$o-company-secondary-color: rgb(0, 0,
(1 row)
```

#### Broken Database

```sql
db_name=# SELECT
    id, name, company_id, type, url, store_fname, mimetype, LEFT(index_content, 100) AS index_content
FROM ir_attachment
WHERE url = '/web/static/src/scss/report_styles.scss';

 id |       name       | company_id |  type  |                   url                   |                 store_fname                 | mimetype  |                                            index_content
----+------------------+------------+--------+-----------------------------------------+---------------------------------------------+-----------+------------------------------------------------------------------------------------------------------
(0 rows)
```

So it's obvious that this file is not available, but not clear why. I used the Developer Mode **Regenerate Asset Bundles** button and even tried deleting all CSS/JS files (using `name` as a filter instead of `datas_fname`) from the attachments table, but neither resolved anything.

For what it's worth, I was able to edit the `report_assets_common` view and comment out the line which loads `report_styles.scss` and it did allow me to print PDFs properly. However, I don't like that as a solution, so I kept looking.

I found that the `report_styles.scss` is generated as a part of the `base` module's data files (as seen in `core/odoo/addons/base/data/res_company_data.xml`). Presumably, you can update the `base` module and it will recreate the missing `report_styles.scss` file. However, if you can't or don't want to update `base` (which will also update all other modules you have installed), then you could manually take the file from a working database's filestore, then move it into your database's filestore and perform a SQL `INSERT` to make Odoo aware of the new attachment. If you don't have a working database, then you can manually create a file in your filestore with these contents (which is all that's in a working database as of 2020-02-27) and create an `ir.attachements` entry to it.

```
$o-company-font: 'Lato';$o-company-primary-color: rgb(0, 0, 0);$o-company-secondary-color: rgb(0, 0, 0);
```

After that file and attachment were recreated, I had no issues printing PDFs.

**Comment by anderwm** [comment] 2020-05-15 17:55
I had to do
DELETE FROM ir_attachment WHERE url LIKE '/web/content/%';
to get it working again

**Comment by agaldemas** [comment] 2020-08-24 15:16
I face the same issue, with odoo 13 under docker, where the filestore is not properly restored, what is strange is that it occurs on our staging environnement Odoo 13 with docker on ubuntu 18.04, but not on macosX, and not on debian....
I thaught about an issue wiith docker version, but after upgrading the docker on ubuntu, the issue remains, the filestore got from the zip archive to restore is not properly copied, and then the restore fails, II have to recover the filestore by hand with a tar, or update the base module to recover evrything.
To note this issue appeared after the installation of the website module on the odoo where the backup comes from

I saw a specific directory "**checklist**" in the filestore which seems to **rule the copy of the filestore** content at restore step, can someone explain how it works ?
