### ISSUE TITLE
international domain name are not supported correctly 

### ISSUE THREAD

**Issue by icf20** [odoo/odoo#23527] opened 2018-03-07 18:13 UTC
this issue is a better version of issue 23011

i got time to test this correctly

1 test boot 
http://309067-11-0-d594fe.runbot9.odoo.com/web
2 email 
![image](https://user-images.githubusercontent.com/17784575/37109748-24bdfacc-223b-11e8-835c-717a2b706fff.png)
3 creating a new company 
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/addons/web/controllers/main.py", line 930, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/addons/project_timesheet_holidays/models/res_company.py", line 22, in create
    company = super(Company, self).create(values)
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/addons/stock/models/res_company.py", line 33, in create
    company = super(Company, self).create(vals)
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/addons/product/models/res_company.py", line 12, in create
    new_company = super(ResCompany, self).create(vals)
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/addons/resource/models/res_company.py", line 24, in create
    company = super(ResCompany, self).create(values)
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/addons/base/res/res_company.py", line 216, in create
    'vat': vals.get('vat'),
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/addons/base/res/res_partner.py", line 532, in create
    partner = super(Partner, self).create(vals)
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/addons/mail/models/mail_thread.py", line 236, in create
    thread.message_post(body=_('%s created') % doc_name)
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/addons/rating/models/mail_thread.py", line 14, in message_post
    message = super(MailThread, self).message_post(body=body, subject=subject, message_type=message_type, subtype=subtype, parent_id=parent_id, attachments=attachments, content_subtype=content_subtype, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/addons/mail/models/mail_thread.py", line 1896, in message_post
    new_message = MailMessage.create(values)
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/addons/mail/models/mail_message.py", line 735, in create
    values['email_from'] = self._get_default_from()
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/addons/mail/models/mail_message.py", line 30, in _get_default_from
    return formataddr((self.env.user.name, self.env.user.email))
  File "/usr/lib/python3.5/email/utils.py", line 91, in formataddr
    address.encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 6-9: ordinal not in range(128)
```

4 creating a new user

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/addons/web/controllers/main.py", line 930, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/addons/sales_team/models/res_users.py", line 17, in create
    user = super(ResUsers, self).create(vals)
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/addons/note/models/res_users.py", line 14, in create
    user = super(Users, self).create(values)
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/addons/auth_signup/models/res_users.py", line 144, in create
    user = super(ResUsers, self).create(values)
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/addons/mail/models/res_users.py", line 57, in create
    user = super(Users, self).create(values)
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/addons/base/res/res_users.py", line 803, in create
    user = super(UsersView, self).create(values)
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/addons/base/res/res_users.py", line 649, in create
    return super(UsersImplied, self).create(values)
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/addons/base/res/res_users.py", line 332, in create
    user = super(Users, self).create(vals)
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/models.py", line 3294, in create
    record = self.browse(self._create(old_vals))
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/models.py", line 3351, in _create
    parent_id = self.env[parent_model].create(parent_vals).id
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/addons/base/res/res_partner.py", line 532, in create
    partner = super(Partner, self).create(vals)
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/addons/mail/models/mail_thread.py", line 236, in create
    thread.message_post(body=_('%s created') % doc_name)
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/addons/rating/models/mail_thread.py", line 14, in message_post
    message = super(MailThread, self).message_post(body=body, subject=subject, message_type=message_type, subtype=subtype, parent_id=parent_id, attachments=attachments, content_subtype=content_subtype, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/addons/mail/models/mail_thread.py", line 1896, in message_post
    new_message = MailMessage.create(values)
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/addons/mail/models/mail_message.py", line 735, in create
    values['email_from'] = self._get_default_from()
  File "/home/odoo/runbot/extra/runbot/static/build/309067-11-0-d594fe/odoo/addons/mail/models/mail_message.py", line 30, in _get_default_from
    return formataddr((self.env.user.name, self.env.user.email))
  File "/usr/lib/python3.5/email/utils.py", line 91, in formataddr
    address.encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 6-9: ordinal not in range(128)
```

**Comment by sswapnesh** [comment] 2018-03-07 19:35
I can confirm this Issue too.
![](https://image.prntscr.com/image/LSf0JwprRX6C1OERH-O6KQ.png)
Related to #23502

**Comment by Elkasitu** [comment] 2018-03-08 10:42
@xmo-odoo it seems like python's `email.utils.formataddr` does not account for [internationalized email addresses](https://tools.ietf.org/html/rfc6531), any ideas ?

**Comment by xmo-odoo** [comment] 2018-03-08 10:58
Reading https://bugs.python.org/issue20083 and https://bugs.python.org/issue11783 (especially [the final few comments of the second issue](https://bugs.python.org/issue11783#msg294937)) it looks like this is decidedly non-trivial to say the least, possibly even problematic to handle ourselves.

It seems the best solution would be a clean validation that the address is pure ASCII (rather than traceback) & asking users to input punycode-encoded domains.

**Comment by icf20** [comment] 2018-03-08 16:09
> punycode-encoded domains

please note that this can add confusion, government certificate to sign documents ( in case of spain can have à á è é ñ) and documents signed will show a "normal" email while the user will see an punycode-encoded domain

**Comment by Elkasitu** [comment] 2018-03-09 07:47
@icf20 unfortunately the solution to this would be to decode the puny-encoded email address for display, which as the links that @xmo-odoo provided show, is a bad idea in python.

Basically, our hands are tied, the best we can do is what @xmo-odoo suggested.

**Comment by icf20** [comment] 2018-06-02 12:28
@len-odoo pépé@gmail.com is not a international domain name pépé@gmail.com is just an gmail domain an international domain name is  Яндекс.рф ( yandex.ru) you go to mail.yandex.com make a account and then send a email to that account@Яндекс.рф

**Comment by sswapnesh** [comment] 2019-05-11 14:04
Fixed in https://github.com/odoo/odoo/pull/25023
Cc @len-odoo

**Comment by Yenthe666** [comment] 2019-05-11 14:24
I think you're right @sswapnesh (https://github.com/odoo/odoo/commit/5242380b4ee0deb8e35cef6783ba2af891e14835). If you can still find issues then please don't hesitate to respond again.

**Closed by Yenthe666** 2019-05-11 14:24 UTC
Labels: 11.0, Framework

**Comment by icf20** [comment] 2019-05-11 15:41
i tested this on version 12 changing the email work and so on but login does not

**Comment by sswapnesh** [comment] 2019-05-11 16:00
Any tracback or It is saying about Invalid Id/Password?

**Comment by icf20** [comment] 2019-05-11 16:06
> It is saying about Invalid Id/Password?

is just the default "error" you get when wrong password is inserted

**Comment by icf20** [comment] 2019-05-11 16:22
runbot **http://517403-11-0-0bf5ad.runbot13.odoo.com/web/login**

![image](https://user-images.githubusercontent.com/17784575/57572370-70623700-7419-11e9-8e7b-a6ca84a9aa49.png)


![image](https://user-images.githubusercontent.com/17784575/57572376-8d970580-7419-11e9-8ab3-9d7a7759894d.png)

**Comment by sswapnesh** [comment] 2019-05-11 16:24
I would suggest you to create new Issue in this case.

**Comment by len-odoo** [comment] 2019-05-13 09:20
The support for international domain names was never merged.
Anthony himself disliked the idea; approximate quote is "we shouldn't support this, anyone with such an address is looking for trouble".
The argument is, it creates the possibility to have 'unicode similar looking characters confusion' and the problem with the confusion IDNA2003/8.
However I've tested the given example, and had no problem to log in v11, 12, local and runbot.
But it's not a very good idea to use since Odoo is unable to send mail to these addresses anyway.

**Comment by icf20** [comment] 2019-05-16 11:52
> "we shouldn't support this, anyone with such an address is looking for trouble".

quite the opposite, no spam, no newsletters and ads-crap via email, the only people who email you are those that you contact first  

if that is the final decision there is no other option that to obey the overlords or start a fork over this :(
