### ISSUE TITLE
When Production description empty then Quote Confirm giving Error

### ISSUE THREAD

**Issue by rb3606** [odoo/odoo#64970] opened 2021-01-23 14:35 UTC
Impacted versions: 14.0

Steps to reproduce: SEtup fresh database without demo data and create new product without description field(keep it blank) and create quotation and mark confirm

Current behavior: It giving error due to description coming as None

Expected behavior: Need to check if description is none then no need to concate

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/6355966/105583829-43ed7a80-5db6-11eb-8474-7a94a8801675.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment] 2021-01-23 14:41
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by rb3606** [comment] 2021-01-25 06:59
Hi @pedrobaeza  i tried on runbot but unable to reproduce.

**Comment by pedrobaeza** [comment] 2021-01-25 07:16
Sorry, but if not reproducible, then something in your end is outdated or there are third-party code that breaks this.

Closing as no reproducible.

**Closed by pedrobaeza** 2021-01-25 07:16 UTC
Labels: Need information
