### ISSUE TITLE
[15] AttributeError: 'NoneType' object has no attribute 'envs' when create new database

### ISSUE THREAD

**Issue by MR-ILYAS08** [odoo/odoo#78001] opened 2021-10-07 11:54 UTC
Trying to install odoo 15 in ubuntu server 20.04 , i setup everything like usual , master password & db user details are correct but 
getting this issue in log file (in the gui is just saying "Database creation error: Access Denied" but the db is created) :

Traceback (most recent call last):
  File "/opt/odoo/odoo/service/db.py", line 66, in _initialize_db
    env = odoo.api.Environment(cr, SUPERUSER_ID, {})
  File "/opt/odoo/odoo/api.py", line 506, in __new__
    for env in transaction.envs:
AttributeError: 'NoneType' object has no attribute 'envs'

Thanks for help

**Comment by johnny-longneck** [comment] 2021-10-08 07:42
Same issue. Ubuntu 20.04 fresh install with a certain install script, we all know.
@Pedro-JPG this did not solve my issue.

**Comment by Yenthe666** [comment] 2021-10-08 11:13
@d-fence @mart-e looks like a pretty common one 🤔

**Comment by peseotni** [comment] 2021-10-09 17:20
I also tried it now with Ubuntu 18.04 and the same error, and again I can get into it with admin/admin.
This is not ubuntu or dependency error, but something in odoo 15
I checked also the differences between 14 & 15 but I am not an expert, so I don't know where to start

**Comment by ahmedsmaali5** [comment] 2021-10-09 17:33
> I also tried it now with Ubuntu 18.04 and the same error, and again I can get into it with admin/admin. This is not ubuntu or dependency error, but something in odoo 15 I checked also the differences between 14 & 15 but I am not an expert, so I don't know where to start

If you create a new admin user with anything other than admin/admin & disable the old admin account , does that solve it?

**Comment by danielosser** [comment] 2021-10-09 20:10
> If you create a new admin user with anything other than admin/admin & disable the old admin account , does that solve it?
Yes, or rename admin user and change the password.

**Comment by ACBRI** [comment] 2021-10-10 04:43
todos con el mismo problema.

**Comment by johnny-longneck** [comment] 2021-10-10 09:05
Yesterday @Albin-John submitted a fix for this issue and this worked for me. The fix seems to be in the latest code so you should update your odoo version.

Since the problematic code was on several parts of the file, I expect there might be still problems when duplicating or dropping a database.

**Comment by danielosser** [comment] 2021-10-10 13:10
> Yesterday @Albin-John submitted a fix for this issue and this worked for me. The fix seems to be in the latest code so you should update your odoo version.
> 
> Since the problematic code was on several parts of the file, I expect there might be still problems when duplicating or dropping a database.

@johnny-longneck  - I did a checkout of 15.0 (latest commit) and issue is still present...do you know if it's been accepted?

**Comment by huynhsonny** [comment] 2021-10-10 22:17
> > Yesterday @Albin-John submitted a fix for this issue and this worked for me. The fix seems to be in the latest code so you should update your odoo version.
> > Since the problematic code was on several parts of the file, I expect there might be still problems when duplicating or dropping a database.
> 
> @johnny-longneck - I did a checkout of 15.0 (latest commit) and issue is still present...do you know if it's been accepted?

The first, You should create a new database with account admin and password is admin. It should be ok. and then you can login with account admin and password is admin. And then you can go to setting to change admin password is what ever you want.

**Comment by mart-e** [comment] 2021-10-11 05:24
Hi,

Thanks for the report, we are looking into it. Closing as duplicate of #77516.

**Closed by mart-e** 2021-10-11 05:24 UTC
Labels: 15.0

**Comment by yberezkin** [comment] 2021-11-14 07:11
If you use odoo.conf approach, with `db_name = False` line, it seems so resolve the issue

**Comment by Henrijo** [comment] 2022-07-10 12:00
Hi every one   
I've the same issue on odoo v14 i've created the new database with admin:admin and that solve my issues but the secont issue is that I can't restore anymore database it display that database exits issue . Help me deal with that issue for good
