### ISSUE TITLE
[11.0, 12.0] Not possible to delete a pricelist promo code after submiting it

### ISSUE THREAD

**Issue by Parsia** [odoo/odoo#34633] opened 2019-07-07 11:20 UTC
Impacted versions: 12.0

Steps to reproduce: 

Current behavior: there isnt any button to delete a coupon. I dont want to use it. when the coupon box is blank, I use the apply button but it has this error: "This promo code is not available"

Expected behavior: delete my coupon. I dont want to use it. there is another discount without coupon with which the product is cheaper.

Video/Screenshot link (optional): 
![Screenshot from 2019-07-07 15-46-38](https://user-images.githubusercontent.com/52624519/60767523-9b41d200-a0ce-11e9-9bf7-131fb2b5567b.png)

**Comment by sswapnesh** [comment] 2019-07-07 17:52
> there isnt any button to delete a coupon. I dont want to use it. when the coupon box is blank, I use the apply button but it has this error: "This promo code is not available"

IMO its not Informative about applied Code but still you can Apply your another coupon  (or Just type Invalid code there to remove it) 

(Cc: @JKE-be  Any chances to Consider this as wishlist ?)

**Comment by Parsia** [comment] 2019-07-08 06:03
> > there isnt any button to delete a coupon. I dont want to use it. when the coupon box is blank, I use the apply button but it has this error: "This promo code is not available"
> 
> IMO its not Informative about applied Code but still you can Apply your another coupon (or Just type Invalid code there to remove it)
> 
> (Cc: @JKE-be Any chances to Consider this as wishlist ?)

The main issue is that when I enter an invalid code it doesnt remove!!

**Comment by JKE-be** [comment] 2019-07-09 09:26
in the past, submit a blank coupon remove the applied coupon.
We will check it.

**Comment by rdeodoo** [comment] 2019-07-09 15:23
That's not related to coupon, coupon (`website_sale_coupon`) is not available in community in 12.0.
This screenshot/behavior is related to pricelist promo code.
I know that for the end user pricelist promo code and coupon are the same but let's differenciate those 2 in this thread.

Indeed, there was a regression related to the behavior you mention.
When a pricelist promo code has been applied, adding an empty promo code is supposed to clear that pricelist and use the fallback pricelist (either the one from the user, the company, whatever pricelist should be used by default). You can see it [here](https://github.com/odoo/odoo/blame/3e63d8efcec28758f78c0efa6a02cec818d53aa5/addons/website_sale/models/website.py#L224): `If empty, it's a special case to reset the pricelist with the first available else the default.`.

Of course, if the fallback pricelist is the promo code pricelist applied (that could happen), it will looks like it is not working but actually it removed the promo code pricelist as expected and applied it afterwards, ending with the same result.


We will have a fix coming for this ASAP, once done we will ask you to try it out and confirm it fixes your behavior.

**Comment by rdeodoo** [comment] 2019-07-09 16:19
Please can you test/confirm https://github.com/odoo/odoo/pull/34711

**Comment by sswapnesh** [comment] 2019-07-09 17:50
> Please can you test/confirm #34711

Tested on http://559461-saas-14-fix-pricelist-empty-rese-12c147.runbot25.odoo.com

![screenshot-559461-saas-14-fix-pricelist-empty-rese-12c147 runbot25 odoo com-2019 07 09-23-07-41](https://user-images.githubusercontent.com/16624719/60910563-c5e28500-a29e-11e9-921c-7a2ba3d15657.jpg)

- Original Price is 180 $ (Pricelist is configured with 10% discount, So 162 $ is correct)


![screenshot-559461-saas-14-fix-pricelist-empty-rese-12c147 runbot25 odoo com-2019 07 09-23-10-36](https://user-images.githubusercontent.com/16624719/60910565-c67b1b80-a29e-11e9-87c0-9bb6bd1636ca.jpg)

Things I noticed

- Applying Same Code again removes selected Pricelist, It should stay applied. (When User click Apply again as there is no Information if Code is applied or not - (else you remember price))

![screenshot-559461-saas-14-fix-pricelist-empty-rese-12c147 runbot25 odoo com-2019 07 09-23-11-56](https://user-images.githubusercontent.com/16624719/60910644-fde9c800-a29e-11e9-8213-7c1668c2a8b3.jpg)

- Wrong Promo Code doesn't set old Pricelist brings back applied Promocode on the Box.
(Ps:  Adding an empty promo code applied pricelist and use the fallback pricelist)

![screenshot-559461-saas-14-fix-pricelist-empty-rese-12c147 runbot25 odoo com-2019 07 09-23-15-42](https://user-images.githubusercontent.com/16624719/60910860-823c4b00-a29f-11e9-927d-8fd8f3083fe2.jpg)

**Comment by JKE-be** [comment] 2019-07-10 08:21
@rdeodoo 

3 to check
4 lgtm -> if you don't use a new coupon, we keep previous, not an issue

**Comment by rdeodoo** [comment] 2019-07-10 09:39
The 3 point is indeed a bug. The code is going through the `elif` condition that is handling empty promo code to reset pricelist, but it shouldn't.

While this current PR is a regression in saas-14, this bug has always been there, so I fixed it in 10.0 at https://github.com/odoo/odoo/pull/34734/files

**Comment by rdeodoo** [comment] 2019-07-10 12:57
> Applying Same Code again removes selected Pricelist, It should stay applied. (When User click Apply again as there is no Information if Code is applied or not - (else you remember price))

Fixed with https://github.com/odoo/odoo/pull/34734

**Comment by sswapnesh** [comment] 2019-07-10 19:32
> > Applying Same Code again removes selected Pricelist, It should stay applied. (When User click Apply again as there is no Information if Code is applied or not - (else you remember price))
> 
> Fixed with #34734

Tested and Works well.

**Comment by rdeodoo** [comment] 2019-07-24 09:36
https://github.com/odoo/odoo/commit/36fdb2ff499136b8f5a6c1c1d842251c5e6e2c5b

**Closed by rdeodoo** 2019-07-24 09:36 UTC
Labels: 11.0, 12.0, Confirmed, Website
