### ISSUE TITLE
Odoo 10 in Ubuntu 16.04: blank page on localhost:8069

### ISSUE THREAD

**Issue by inspireaman** [odoo/odoo#21262] opened 2017-11-27 13:56 UTC
Impacted versions:odoo 10 on ubuntu 16

We installed odoo 10 on ubuntu 16.04.

when we login  to demo db as admin from local server,after login it's showing only odoo logo..nothing else.
then, we are try to login from remote system, after login, odoo page was loading ...........but, nothing comes to view.

we checked this post also,
https://github.com/odoo/odoo/issues/14581#issuecomment-329473903
it explained  to apply tweaks in windows platform.but, what can we do in Ubuntu 16.04,which does not contain C:\Program files (x86)\Odoo 10.0\server.so, we can't replace  folder werkzeug.

kindly help us to resolve this..

Thanks in Advance.

**Comment by Yenthe666** [comment] 2017-12-04 08:09
Duplicate of https://github.com/odoo/odoo/issues/19627
Please update your whole Odoo and regenerate all your assets.

Regards,
Yenthe

**Closed by Yenthe666** 2017-12-04 08:09 UTC
