### ISSUE TITLE
Bug that prevent to save record of a field in a o2m field tree not present in the record form

### ISSUE THREAD

**Issue by aek** [odoo/odoo#24220] opened 2018-04-13 11:32 UTC
Impacted versions:
Odoo 11.0

Steps to reproduce:
Create a One2many field that contains a field in the TreeView that it's not present as a field in the FormView, could be a calculated field or a field that will take a value after the record is saved. You could see the field create_date as an example also because this issue was discovered and tested using that field

Current behavior:
The target field will get no value, specifically undefined, not even false
Here is where the value is obtained:
https://github.com/odoo/odoo/blob/11.0/addons/web/static/src/js/views/list/list_renderer.js#L288
and you could see here that only false values are tested:
https://github.com/odoo/odoo/blob/11.0/addons/web/static/src/js/fields/field_utils.js#L135
Due to that the value of the record is undefined you will get an error at this line:
https://github.com/odoo/odoo/blob/11.0/addons/web/static/src/js/fields/field_utils.js#L139
with the value.clone() call

```
Uncaught TypeError: Cannot read property 'clone' of undefined
    at Object.formatDateTime [as datetime] (VM2516 field_utils.js:139)
    at Class._renderBodyCell (VM2549 list_renderer.js:284)
    at VM2549 list_renderer.js:570
    at Function._.map._.collect (VM2405 underscore.js:164)
    at Class._renderRow [as _super] (VM2549 list_renderer.js:569)
    at Class._renderRow (VM2548 list_editable_renderer.js:499)
    at Class._renderRow (VM2439 class.js:123)
    at Function._.map._.collect (VM2405 underscore.js:164)
    at Class._renderRows (VM2549 list_renderer.js:591)
    at Class._renderRows (VM2548 list_editable_renderer.js:516)
```
Expected behavior:
the value should be checked against undefined too, like:
`if (value === false || value === undefined) {`
In every place where it's used. I saw that the first check against false was added/changed in this two commits
https://github.com/odoo/odoo/commit/da4e653695cceb1d3cbd9342b3cd830734c21fee
https://github.com/odoo/odoo/commit/c8d77f93e5a857acd22025f4a8d4d42d674479d1

**Comment by gustavovalverde** [comment] 2018-04-13 18:34
Oh, so it wasn't my code but a bug. Good to know 👍

**Comment by alexkuhn** [comment] 2018-04-16 08:11
Hi @aek 

I would like to reproduce it, so that I understand why we get the value `undefined` in the first place.
Unfortunately, I was not able to reproduce it with the above information. I have followed these steps:

- Let **R** be a record containing a many2one field **M**.
- The list view of **M** contains the field `create_date`, while the form view of **M** does not contain `create_date`.

1. Create a record **R**
2. Add an item in **M**, **M1**, with `create_date` unset
3. Open **M1**'s form view

Could you please provide me more information on the issue? (e.g. steps on runbot, a short clip, ...)

Kind regards,

**Comment by aek** [comment] 2018-04-16 09:54
Hi @alexkuhn 
Do you mean one2many?. The proper steps are:

- Let **R** be a record containing a **one2many** field **M**.
- The list view of **M** contains the field `create_date`, while the form view of **M** does not contain `create_date`.

1. Create a record **R**
2. Add an item in **M**, **M1** by opening **M** model form view, (`create_date` doesn't belong to the form and will set after **R** is saved triggering the save of **M1**) 
3. Try to save **M1** Form Record to the one2many in **R**

You should get the error after save while trying to format the `create_date` field value

**Comment by aek** [comment] 2018-04-16 11:00
Also reviewing some commits seems that this was solved already
https://github.com/odoo/odoo/commit/8e5156938a9c87b80512bff9ecd025891406e624
https://github.com/odoo/odoo/commit/9c1c2c55c23655c56dcd04c3d80da59b5bcab177

I have tried this in runbot at:
http://320503-11-0-ff07f0.runbot13.odoo.com/web?debug=assets#id=&view_type=form&model=sale.order&action=717
and it's working, weird but working
weird because I have tried first by using the field create_date and the onchange of the field order_line it's returning the default value of false for the field create_date added to the o2m list and not the false value for the field write_date(not added to the o2m list), after been changed the field create_date with the field write_date in the o2m list the order_line onchange then return the default false value for the field write_date.
Maybe @aab-odoo and @kebeclibre could explain better the new behavior for a better understanding. But seems to be solved

**Comment by alexkuhn** [comment] 2018-04-16 11:11
Sorry, I meant one2many instead of many2one.

Indeed, https://github.com/odoo/odoo/commit/8e5156938a9c87b80512bff9ecd025891406e624 should have fixed this issue.

The fix above has been merged 3 days ago, which is almost at the same time this issue has been opened.

**Closed** 2018-04-16 12:34 UTC
Labels: 11.0, Framework
