### ISSUE TITLE
Bank statements reconcile: Account journal entry's period different from journal items' period

### ISSUE THREAD

**Issue by jalzaga** [odoo/odoo#5692] opened 2015-03-11 00:49 UTC
Bank statements reconcile: Account journal entry's period different from journal items' period

Impacted versions:
- 8.0

Steps to reproduce:
1. Create or import a bank statement
2. Go to the estatement and press reconcile button 
3. select one of the items. Try to get one with a date corresponding to a period previous to the actual period,  and fill in the counterpart, press OK.
4. the journal entry created takes the date and the period form the bank statement item date. This is correct. But the journal items take a different period. 

Current behavior:
- Journal entry´s period different from journal items' period. 

Expected behavior:

 The period should be the same for journal entry and journal items

**Comment by jalzaga** [comment] 2015-03-19 11:30
This issue has become Urgent. There are already complains from customers because they cannot reconcile their accounts

**Comment by fclementic2c** [comment] 2015-03-19 12:47
@jalzaga Hi. This is not a bug. I reported the same in openerp v7.
Odoo has always said that a period must be force on the statement to prevent from posting on the wrong period.
If you want to post on previous period then split you statement.

It is probably a good advic eto split statement by month if you work with period closing as well.

**Comment by Yenthe666** [comment] 2017-12-12 15:53
Indeed - the answer is correct as far as I know.

**Closed by Yenthe666** 2017-12-12 15:53 UTC
Labels: Accounting

**Comment by jalzaga** [comment] 2017-12-12 16:29
The point was not what you explained, the problem is that you get a journal (account_move) with a period and a journal item (account_move_line) with a different period.  Normally they are the same to be coherent. @fclementic2c @Yenthe666 . However I know that odoo v8 is no longer supported.

**Comment by Yenthe666** [comment] 2017-12-12 17:01
Ahh sorry I thought it was directly related. The V8 reached end of life indeed, so the close is still relevant. Sorry it wasn't fully handled!
