### ISSUE TITLE
Decreasing stock 'Update Qty On Hand' generate stock  increasing

### ISSUE THREAD

**Issue by zbik2607** [odoo/odoo#27972] opened 2018-10-19 10:14 UTC
Impacted versions: 11 (probably others)

Steps to reproduce:
1) Product X  - stock = 10 pcs. in PACK0000006
2) Info on product view - "On Hand" = 10
3) Click on "Update Qty On Hand" and set "New Quantity on Hand" = 9
4) Info on product view - "On Hand" = 19
 
Current behavior:
"On Hand" = 19

Expected behavior:
"On Hand" = 9

**Comment by pedrobaeza** [comment] 2018-10-19 10:18
That's because the new quantity is attached to a location, so for sure you have the other 9 pieces in other location, so 10 in this one + 9 in the other(s) makes 19.

Closing as no real issue.

**Closed by pedrobaeza** 2018-10-19 10:18 UTC

**Comment by zbik2607** [comment] 2018-10-19 10:41
www.fishing.pl/html/odoo/20181019_123716.mp4

**Comment by sswapnesh** [comment] 2018-10-20 10:13
Hello @zbik2607 
This because of Miss configuration,According to your Video.

10 Qty is already reserved for Location` WH/Stock/Shelf 2` for Package `PACK0000006` but next time when you Update Quantity for that Product you should select Package `PACK0000006` if you want to make an update in that(You need to activate `Lots & Serial Numbers` from Inventory settings)

![screenshot 33](https://user-images.githubusercontent.com/16624719/47254291-34b44f80-d47e-11e8-9859-ecadd6b12e04.png)

Right now when you add New Quantity (9) it is reserved without Package.
![screenshot 34](https://user-images.githubusercontent.com/16624719/47254312-7f35cc00-d47e-11e8-9556-cbc29ec0be37.png)

> 
> Expected behavior:
> "On Hand" = 9
For this You should Enable lot and Select Same Package/Location with Zero quantity.

Hope this helps.

Cc: @pedrobaeza

**Comment by pedrobaeza** [comment] 2018-10-24 09:38
Yeah, indeed the problem is that the stock is on a package, so you can't change via this option the quantity. You should unpack first the stock.

@sswapnesh "Manage lots & serial numbers" option is not exactly for this.

**Comment by sswapnesh** [comment] 2018-10-24 14:42
@pedrobaeza than Which option enables this feature?

**Comment by pedrobaeza** [comment] 2018-10-24 14:45
There's no handling of packages from inventory quick update.
