### ISSUE TITLE
Can't change user password

### ISSUE THREAD

**Issue by psugne** [odoo/odoo#57926] opened 2020-09-17 09:18 UTC
Impacted versions: 14.0
Checked on latest runbot (saas-13-5)

Steps to reproduce:

_Settings -> Users -> Select User -> Action -> Change Password_
Write a _New Password_ and click on _Change Password_ button

Current behavior:
Can't change password for a user, validation error is thrown.

Expected behavior:
Password could be changed

Video/Screenshot link (optional):
![change_password](https://user-images.githubusercontent.com/17007193/93451267-a0f49380-f8df-11ea-9916-fb5c0d670a67.png)

**Comment by Yenthe666** [comment] 2020-09-17 09:46
@mart-e who can check this one?

**Comment by Feyensv** [comment] 2020-09-17 09:50
Will be fixed by https://github.com/odoo/odoo/pull/57922

**Comment by mart-e** [comment] 2020-09-17 09:51
@psugne thanks for the report but keep in mind version 14.0 does **not** exist yet, saas-13.5 is in stabilisation phase but not stable yet, expect bugs.

Closing as duplicate of #57149

**Closed by mart-e** 2020-09-17 09:51 UTC
