### ISSUE TITLE
[13.0] : Footer of QWEB reports can't printed

### ISSUE THREAD

**Issue by Hamza-Talibi** [odoo/odoo#38394] opened 2019-10-10 12:47 UTC
Impacted versions:
13.0
Steps to reproduce:
Print report (Sale, Invoice, Purchase, RMA,....)
Current behavior:
Footer not printed
Expected behavior:
Footer printed
Video/Screenshot link (optional):
![Screenshot from 2019-10-10 13-46-16](https://user-images.githubusercontent.com/25642031/66569910-69745780-eb64-11e9-93e1-1b63b7cbf970.png)

opw-2086708

**Comment by pedrobaeza** [comment] 2019-10-10 16:26
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Hamza-Talibi** [comment] 2019-10-10 17:41
Hi,

Yes, I'm able to reproduce the issue in runbot:

I choose any layout then I print any report (Sale, RMA, Purchase,...)  -> The footer is blank even the company data are set.

Attached you will find my test in runbot.

Best regards.

![ezgif-1-7c4399d2614f](https://user-images.githubusercontent.com/25642031/66592736-8c673180-eb8d-11e9-8eb0-9b62712eb1b0.gif)

**Comment by nafex** [comment] 2019-10-10 17:46
I have the same problem

**Comment by Feyensv** [comment] 2019-10-10 19:57
![image](https://user-images.githubusercontent.com/19364378/66601675-c2fe7580-eba8-11e9-98a2-de7139bba293.png)
Just tried, after filling the first step of the sales onboarding (setting up your company data) and no problem on my side.  I'll investigate more in depth tomorrow.

**Comment by Hamza-Talibi** [comment] 2019-10-11 09:53
Hi everyone,

The problem seems only with google chrome, because I could print the report with footer in firefox.

My chrome version is  77.0.3865.120 (Official Build) (64-bit)

**Comment by Feyensv** [comment] 2019-10-11 09:54
Well, I'm not able to reproduce it in a 13.0 db (latest version of the 13.0 branch) without demo datas.
Please verify it works for you, and if not, please give a detailed explanation of your configuration to confirm we can reproduce it.

**Comment by Hamza-Talibi** [comment] 2019-10-11 11:38
Hi,

The problem appears when we activate developer mode:
![ezgif-1-51e987b9d5fe](https://user-images.githubusercontent.com/25642031/66648670-0a761780-ec24-11e9-94eb-bf3c1e60b0ec.gif)

**Comment by Hamza-Talibi** [comment] 2019-10-14 09:44
Hello,

Any news on this?

**Comment by pedrobaeza** [comment] 2019-10-14 10:04
@Hamza-Talibi you were asked by @Feyensv with the impossibility of reproducing the problem, if you don't have more proofs about reproducing the problem outside your environment, this will be closed.

**Comment by nafex** [comment] 2019-10-14 10:10
> Hi,
> 
> The problem appears when we activate developer mode:
> 
> ![ezgif-1-0a2a838d6ec1](https://user-images.githubusercontent.com/25642031/66650425-7fe3e700-ec28-11e9-94ed-35d3e871d615.gif)

This is the proof using odoo runbot. I have checked that also with the latest v13.0 on runbot just now and with active developer mode there is no footer in the pdf reports...

**Comment by Hamza-Talibi** [comment] 2019-10-14 10:14
Hi @pedrobaeza 

The problem is reproduced on odoo runbot when activating developer mode.

**Comment by pedrobaeza** [comment] 2019-10-14 10:17
OK, let's see if this is enough for reproducing it. Any way, you have to take into account that this is a voluntary effort, so no guarantee of this being answered or solved. If you have an enterprise contract, then put the corresponding OPW ticket in odoo.com/help and this will be attended in time and form.

**Comment by nafex** [comment] 2019-10-14 10:24
> OK, let's see if this is enough for reproducing it. Any way, you have to take into account that this is a voluntary effort, so no guarantee of this being answered or solved. If you have an enterprise contract, then put the corresponding OPW ticket in odoo.com/help and this will be attended in time and form.

Thank you very much for your help. I have submited the issue with odoo.com/help.

**Comment by hibouambigu** [comment] 2019-10-21 13:09
I also have this problem.
Only affects PDF reports. HTML version of report is fine.

13.0 Community running on Ubuntu 18.04 VM (KVM).

Have tried Wkhtmltopdf versions

- 0.12.5
- 0.12.3
- 0.12.1

All have the same issue. Footer always appears blank or as black square, and header sometimes disappears as well, eg (footer):

![image](https://user-images.githubusercontent.com/51302834/67207847-5a05d180-f3e2-11e9-845f-836b4d04588b.png)

**Comment by Hamza-Talibi** [comment] 2019-10-21 13:37
Hi @nafex,

Did you get som feedback from odoo?

Thanks

**Comment by nafex** [comment] 2019-10-21 18:28
No, nothing. Have open an ticket on 14.10.2019, until now no reaction...

**Comment by PieterPaulussen** [comment] 2019-10-21 21:33
Confirmed the issue on macOS as well (if anyone cares). Deactivating developer mode solves the issue.

**Comment by nafex** [comment] 2019-10-23 08:57
News from Odoo:
> we are actively working on the issue and will be back to you as soon as possible

**Closed** 2019-10-31 11:05 UTC
Labels: 13.0, Need information, OE

**Comment by razvanioan** [comment] 2021-04-15 10:09
This seems to happen again on v14.
If debug mode enabled, footer is completely missing from PDF reports (HTML preview is working)

**Comment by carloselioz** [comment] 2021-04-28 23:08
> This seems to happen again on v14.
> If debug mode enabled, footer is completely missing from PDF reports (HTML preview is working)

You can install new version 0.12.6. in v14 from sources: https://wkhtmltopdf.org/downloads.html


![image](https://user-images.githubusercontent.com/63575400/116483224-4bf10680-a84c-11eb-81a5-7f7fa54a014f.png)

**Comment by razvanioan** [comment] 2021-04-29 09:51
@carloselioz I'm already using that version

```bash
wkhtmltopdf --version
wkhtmltopdf 0.12.6 (with patched qt)
```

**Comment by TheoCaparros** [comment] 2023-11-27 14:13
Is their any news, because it's still here for Odoo 16.
