### ISSUE TITLE
"Remaining requests" while doing PhantomJS tests

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#12927] opened 2016-07-27 12:00 UTC
Impacted versions: 8, 9

Steps to reproduce: Run a test in PhantomJS. It only triggers sometimes, not sure under what circumstances.

Current behavior:

The test ends (failure or not) and logs this in loop endlessly:

```
2016-07-27 11:56:03,065 22 INFO db openerp.tests.common: remaining requests
2016-07-27 11:56:03,069 22 INFO db openerp.tools.misc: 
# Thread: openerp.addons.bus.models.bus.Bus (id:140432738608896) (uid:n/a)
File: "/usr/lib64/python2.7/threading.py", line 784, in __bootstrap
  self.__bootstrap_inner()
File: "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
  self.run()
File: "/usr/lib64/python2.7/threading.py", line 764, in run
  self.__target(*self.__args, **self.__kwargs)
File: "/opt/odoo/extra-addons/OCB/bus/models/bus.py", line 168, in run
  self.loop()
File: "/opt/odoo/extra-addons/OCB/bus/models/bus.py", line 151, in loop
  if select.select([conn], [], [], TIMEOUT) == ([], [], []):

# Thread: openerp.service.http.request.140432747001600 (id:140432747001600) (uid:n/a)
File: "/usr/lib64/python2.7/threading.py", line 784, in __bootstrap
  self.__bootstrap_inner()
File: "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
  self.run()
File: "/usr/lib64/python2.7/threading.py", line 764, in run
  self.__target(*self.__args, **self.__kwargs)
File: "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
  self.finish_request(request, client_address)
File: "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
  self.RequestHandlerClass(request, client_address, self)
File: "/usr/lib64/python2.7/SocketServer.py", line 649, in __init__
  self.handle()
File: "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 200, in handle
  rv = BaseHTTPRequestHandler.handle(self)
File: "/usr/lib64/python2.7/BaseHTTPServer.py", line 340, in handle
  self.handle_one_request()
File: "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 235, in handle_one_request
  return self.run_wsgi()
File: "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 177, in run_wsgi
  execute(self.server.app)
File: "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 167, in execute
  for data in application_iter:
File: "/usr/lib/python2.7/site-packages/werkzeug/debug/__init__.py", line 88, in debug_application
  app_iter = self.app(environ, start_response)
File: "/usr/lib/python2.7/site-packages/openerp/service/wsgi_server.py", line 184, in application
  return application_unproxied(environ, start_response)
File: "/usr/lib/python2.7/site-packages/openerp/service/wsgi_server.py", line 170, in application_unproxied
  result = handler(environ, start_response)
File: "/usr/lib/python2.7/site-packages/openerp/http.py", line 1494, in __call__
  return self.dispatch(environ, start_response)
File: "/usr/lib/python2.7/site-packages/openerp/http.py", line 1468, in __call__
  return self.app(environ, start_wrapped)
File: "/usr/lib/python2.7/site-packages/werkzeug/wsgi.py", line 579, in __call__
  return self.app(environ, start_response)
File: "/usr/lib/python2.7/site-packages/openerp/http.py", line 1643, in dispatch
  ir_http = request.registry['ir.http']
File: "/usr/lib/python2.7/site-packages/openerp/http.py", line 364, in registry
  return openerp.modules.registry.RegistryManager.get(self.db) if self.db else None
File: "/usr/lib/python2.7/site-packages/openerp/modules/registry.py", line 350, in get
  with cls.lock():
File: "/usr/lib64/python2.7/threading.py", line 173, in acquire
  rc = self.__block.acquire(blocking)

# Thread: MainThread (id:140433304557376) (uid:n/a)
File: "/usr/bin/odoo.py", line 160, in <module>
  main()
File: "/usr/bin/odoo.py", line 157, in main
  openerp.cli.main()
File: "/usr/lib/python2.7/site-packages/openerp/cli/command.py", line 64, in main
  o.run(args)
File: "/usr/lib/python2.7/site-packages/openerp/cli/server.py", line 166, in run
  main(args)
File: "/usr/lib/python2.7/site-packages/openerp/cli/server.py", line 160, in main
  rc = openerp.service.server.start(preload=preload, stop=stop)
File: "/usr/lib/python2.7/site-packages/openerp/service/server.py", line 930, in start
  rc = server.run(preload, stop)
File: "/usr/lib/python2.7/site-packages/openerp/service/server.py", line 315, in run
  rc = preload_registries(preload)
File: "/usr/lib/python2.7/site-packages/openerp/service/server.py", line 892, in preload_registries
  registry = RegistryManager.new(dbname, update_module=update_module)
File: "/usr/lib/python2.7/site-packages/openerp/modules/registry.py", line 386, in new
  openerp.modules.load_modules(registry._db, force_demo, status, update_module)
File: "/usr/lib/python2.7/site-packages/openerp/modules/loading.py", line 337, in load_modules
  loaded_modules, update_module)
File: "/usr/lib/python2.7/site-packages/openerp/modules/loading.py", line 237, in load_marked_modules
  loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
File: "/usr/lib/python2.7/site-packages/openerp/modules/loading.py", line 188, in load_module_graph
  report.record_result(openerp.modules.module.run_unit_tests(module_name, cr.dbname))
File: "/usr/lib/python2.7/site-packages/openerp/modules/module.py", line 465, in run_unit_tests
  result = unittest.TextTestRunner(verbosity=2, stream=TestStream(m.__name__)).run(suite)
File: "/usr/lib64/python2.7/unittest/runner.py", line 151, in run
  test(result)
File: "/usr/lib64/python2.7/unittest/suite.py", line 70, in __call__
  return self.run(*args, **kwds)
File: "/usr/lib64/python2.7/unittest/suite.py", line 108, in run
  test(result)
File: "/usr/lib64/python2.7/unittest/case.py", line 433, in __call__
  return self.run(*args, **kwds)
File: "/usr/lib64/python2.7/unittest/case.py", line 369, in run
  testMethod()
File: "/opt/odoo/extra-addons/OCB/website/tests/test_ui.py", line 6, in test_01_public_homepage
  self.phantom_js("/", "console.log('ok')", "'website.snippets.animation' in odoo.__DEBUG__.services")
File: "/usr/lib/python2.7/site-packages/openerp/tests/common.py", line 434, in phantom_js
  self.phantom_run(cmd, timeout)
File: "/usr/lib/python2.7/site-packages/openerp/tests/common.py", line 385, in phantom_run
  self._wait_remaining_requests()
File: "/usr/lib/python2.7/site-packages/openerp/tests/common.py", line 401, in _wait_remaining_requests
  openerp.tools.misc.dumpstacks()
File: "/usr/lib/python2.7/site-packages/openerp/tools/misc.py", line 1051, in dumpstacks
  for line in extract_stack(stack):

# Thread: openerp.service.httpd (id:140432978192128) (uid:n/a)
File: "/usr/lib64/python2.7/threading.py", line 784, in __bootstrap
  self.__bootstrap_inner()
File: "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
  self.run()
File: "/usr/lib64/python2.7/threading.py", line 764, in run
  self.__target(*self.__args, **self.__kwargs)
File: "/usr/lib/python2.7/site-packages/openerp/service/server.py", line 248, in http_thread
  self.httpd.serve_forever()
File: "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 436, in serve_forever
  HTTPServer.serve_forever(self)
File: "/usr/lib64/python2.7/SocketServer.py", line 236, in serve_forever
  poll_interval)
File: "/usr/lib64/python2.7/SocketServer.py", line 155, in _eintr_retry
  return func(*args)

# Thread: openerp.service.cron.cron1 (id:140432961406720) (uid:n/a)
File: "/usr/lib64/python2.7/threading.py", line 784, in __bootstrap
  self.__bootstrap_inner()
File: "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
  self.run()
File: "/usr/lib64/python2.7/threading.py", line 764, in run
  self.__target(*self.__args, **self.__kwargs)
File: "/usr/lib/python2.7/site-packages/openerp/service/server.py", line 238, in target
  self.cron_thread(i)
File: "/usr/lib/python2.7/site-packages/openerp/service/server.py", line 215, in cron_thread
  time.sleep(SLEEP_INTERVAL + number)     # Steve Reich timing style

# Thread: openerp.service.cron.cron0 (id:140432969799424) (uid:n/a)
File: "/usr/lib64/python2.7/threading.py", line 784, in __bootstrap
  self.__bootstrap_inner()
File: "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
  self.run()
File: "/usr/lib64/python2.7/threading.py", line 764, in run
  self.__target(*self.__args, **self.__kwargs)
File: "/usr/lib/python2.7/site-packages/openerp/service/server.py", line 238, in target
  self.cron_thread(i)
File: "/usr/lib/python2.7/site-packages/openerp/service/server.py", line 215, in cron_thread
  time.sleep(SLEEP_INTERVAL + number)     # Steve Reich timing style
```

Expected behavior:

Tests should work.
@Tecnativa

**Comment by Yajo** [comment] 2016-07-27 14:01
OK, found the problem: running phantomjs tests with multiple local databases. Preparing fix...

**Comment by sle-odoo** [comment] 2016-08-03 16:06
How did you come to the conclusion that the issue is linked with having multiple databases?

**Comment by Yajo** [comment] 2016-08-04 09:20
Debugging. I used patch at #12933 and problem stopped.

**Comment by Yenthe666** [comment] 2018-01-26 10:42
@Yajo is it still relevant?

**Comment by Yajo** [comment] 2018-01-26 11:10
I always develop with single databases now, so I don't hit this nowadays, although it's not been fixed, so I guess it is.

**Comment by pedrobaeza** [comment] 2018-04-25 23:27
Closing as there's no plans of fixing this now that PhantomJS is deprecated.

**Closed by pedrobaeza** 2018-04-25 23:27 UTC
Labels: 9.0, Framework
