### ISSUE TITLE
new record is shown in calendar view when switching different views 

### ISSUE THREAD

**Issue by tanghulu0608** [odoo/odoo#46826] opened 2020-03-04 09:09 UTC
Impacted versions:
13.0

Steps to reproduce:
1. make an action with View Mode: calendar,tree,form.
<img width="1501" alt="image" src="https://user-images.githubusercontent.com/5561864/75862397-db15b080-5e39-11ea-85bd-4931070c9b44.png">
2. switch to list view, and add some record.
<img width="1504" alt="image" src="https://user-images.githubusercontent.com/5561864/75862502-04ced780-5e3a-11ea-99bf-c777118efcc7.png">
3. switch back to calendar view, the new add record is now shown in the calendar view.
<img width="1502" alt="image" src="https://user-images.githubusercontent.com/5561864/75862644-3647a300-5e3a-11ea-8bb9-9551124e5a14.png">
4. reload the web page, then the record is shown.
<img width="1503" alt="image" src="https://user-images.githubusercontent.com/5561864/75862744-5bd4ac80-5e3a-11ea-8f60-c93e87ecadb1.png">

this issue exist in sale apps, maybe all app too.
 
Expected behavior:
new record shown in calendar when switching different views

**Comment by sswapnesh** [comment] 2020-03-04 09:22
Duplicate of https://github.com/odoo/odoo/issues/45665

**Comment by pedrobaeza** [comment] 2020-03-04 09:26
Closing then.

**Closed by pedrobaeza** 2020-03-04 09:26 UTC

**Comment by tanghulu0608** [comment] 2020-03-04 09:32
OK, thanks
