### ISSUE TITLE
[stable odoo] Bug for sales total in lines

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#7634] opened 2015-07-16 07:57 UTC
![screenshot from 2015-07-16 13 25 20](https://cloud.githubusercontent.com/assets/311413/8718038/512795c6-2bbe-11e5-895f-59f5872d3d28.png)

Sales order, total for tax and subitem lines total wrong.

Its stable odoo version code & till buggy

**Comment by jbradsha** [comment] 2015-07-16 14:12
What are you trying to do?  It could be a configuration issue.
Do you want your base price to be without tax (i.e. add tax to that amount).

4.55 plus 21% tax = 4.55 + 0.9555 = 4.55 + 0.95 = 5.50
So apart from some rounding (which is 2 decimal places per screenshot) it's fine.
Or 5.50 / 121% x 100% = 4.55 if you work backwards.

**Comment by tejastank** [comment] 2015-07-20 11:26
I want tax included in price.

1. in this, unite price correct, but expected qty*unite=subtotal.

2. Here tax 21% & Price 5.50, 21% mean 0.21000. So TAX = 5.50×0.2100 = 1.155

Let me your view and guide this issue.

**Comment by jbradsha** [comment] 2015-07-20 11:33
The price including tax is 121% of the ex-tax amount.
For example if $1 without tax then total (including tax) = $1 + 21% = $1.21
But you can't take 21% of $1.21 and expect $.21 as tax (21% of $1.21 is 0.2541).

I think Odoo is OK here, you just need to remember that the price inlcluding tax is 121% of the base price.

To work back:
Tax = 21 x total / 121
Untaxed = 100 x total / 121

Working forward:
Tax = .21 x untaxed
Total = 1.21 x untaxed

Hope that helps explain it.

**Comment by tejastank** [comment] 2015-07-20 11:53
[ Marked True ] We had Tax Included in Price for IVA 21%(0.21000)

Quotation had below details,
Item = PA0000COR25, Quantity= 1.0, Unite Price = 6.10, SubTotal = 5.04 (Here Subtotal wrong)

Total TAX: 1.06 , Is that right !

Which step make this correct so subtotal of line become 1.0 * 6.10 =  6.10, Total tax = 1.281, Total=6.10

I hope you had strong right answer.

**Comment by jbradsha** [comment] 2015-07-20 11:55
Yes, 21% of 5.04 is 1.06 (actually 1.0584 but rounding to 2 decimal places is configured).
Total is 121% of 5.04 = 6.0984 (rounds to 6.10).

Looks OK to me, Odoo is adding 21% to the base price (or calculating base tax as 100/121 of the total).

Don't think this is a bug ;-)

**Comment by jbradsha** [comment] 2015-07-20 12:11
If you want the taxed total on each line you can change the view to show total instead of untaxed there... the calculations look OK to me.

For the tax query see this - it shows the same type of calculations as above but for profit instead of tax:
http://www.accountingcoach.com/blog/gross-margin-markup

**Comment by tejastank** [comment] 2015-07-20 12:29
Its complete wrong and odoo bug.

I respect your responses but your understanding is wrong for this.

*  Tax Included in Price, mean sales lines with subtotal must be correct, here odoo wrong.
*  Including tax calculation Odoo wrong.

In case 6.10 unite price and qty=1, 21% tax, mean tax amount 1.281. sub total of line must be 6.10.

This is correct situation if I put in #SAP, #Oracle APP or #ERPNext or #QuickBook & Other Accounting Software.

Sample 
![screenshot from 2015-07-20 17 45 17](https://cloud.githubusercontent.com/assets/311413/8775750/bea01518-2f08-11e5-8386-b818a526c4d5.png)

So its 100% #ODOO bug.

**Comment by tejastank** [comment] 2015-07-20 12:32
@jbradsha this message not for you.

We can't 100% trust odoo, its 200% sure buggy,
For #odoo I can say its apps of bugs or bugs of apps, Both equal.

**Comment by jbradsha** [comment] 2015-07-20 12:57
So you need a view change to show price including taxes, it's a customisation in Odoo terms not a bug as such.  They normally recommend you get a partner to do that in a module (so you can perform software upgrades and then your module will restore your configuration).

By the way I don't work for Odoo ;-)
We do however use it for a medium sized manufacturing company and it works well - of course there are bugs but they are generally fixed quickly (we pay for our support).  You do need some customisation but the same goes for SAP and other ERP too... the good thing about Odoo is that you have full access to the code and the data.

**Comment by tejastank** [comment] 2015-07-20 13:17
Not talking for odoo customization, but default/official feature buggy.

Its 100% bug of ODOO, It might be work for you, but not correct in term of standardisation, if its Odoo own policy mean, they stuck with one particular group, not global solution. In term of this, integration & migration stuffs odoo will fail in global market.

Here your view or ODOO mean people who use SAP are wrong in term of standardisation & others accounting softwares.

Its 1000% bug in term of calculation, configuration & usability of tax where Odoo "including tax price" making hell this odoo apps.

**Comment by ApisNatura** [comment] 2015-09-07 15:29
This bug is still open?! We have exactly the same issue, the subtotal shows the price NOT including the Tax, but the product's price includes it. Since this, odoo is not usable for end-customers..

Please give a comment why there is no fix yet.

**Comment by wtaferner** [comment] 2015-09-07 15:55
Same issue like https://github.com/odoo/odoo/issues/2594#issuecomment-138325183

**Comment by Yenthe666** [comment] 2016-06-09 11:05
Closing this one since it is a duplicate of https://github.com/odoo/odoo/issues/2594.

**Closed by Yenthe666** 2016-06-09 11:05 UTC

**Comment by tejastank** [comment] 2016-06-10 06:41
@Yenthe666 Please look at https://github.com/odoo/odoo/issues/2594 and try to fix and close it too.
