### ISSUE TITLE
Can not access draft invoices

### ISSUE THREAD

**Issue by haconsult** [odoo/odoo#28729] opened 2018-11-15 14:11 UTC
Impacted versions:
v12

Steps to reproduce:
- create a new draft invoice for any one customer
- save, navigate to the customer

Current behavior:
- no way to access the draft invoice from the customer page
- could be accessed from "all invoices" link in previous odoo versions

Expected behavior:
- find a link on the customer page to retrieve draft invoices

**Comment by pedrobaeza** [comment] 2018-11-15 14:39
This has been a design decision I think. @qdp-odoo can you confirm?

**Comment by sswapnesh** [comment] 2018-11-15 14:57
IMO, This is by design to see correct Invoiced Value in customer.

**Comment by haconsult** [comment] 2018-11-15 15:02
The old design perfectly shows the correct Invoiced Value in customer - draft invoices are not taken into account.

**Comment by sswapnesh** [comment] 2018-11-15 15:06
I think that was confusing as On customer it has different amount than total number of invoices of that customer. (As it includes draft Invoices as well)

**Comment by haconsult** [comment] 2018-11-15 15:14
@sswapnesh I don't get that. The button "Invoiced" displays the total amount without draft invoices. It links to a list of validated invoices only, no drafts. 
To access all invoices (draft and valid) you need to go to "Action" → "All invoices".

**Comment by sswapnesh** [comment] 2018-11-15 15:54
Ah Okay, Got It.
This has been removed in https://github.com/odoo/odoo/commit/f56ad6daf80a15101017dce1145a7ee821d272a3#diff-1b77ac79a00e073bb5fa83b31eb48da4L170

**Comment by haconsult** [comment] 2018-11-16 12:02
So now the only way to find draft invoices is to drill down from the Accounting Dashboard to "Invoices to validate". I still think it wold be good to have a link to drafts per customer from the customers page.

Regards

**Comment by qdp-odoo** [comment] 2018-11-16 13:23
it's has been a design decision, but we got your feedback and see if we can do something for it in a next version. In the meanwhile, I'm closing this issue.

Thanks for the understanding

**Comment by sswapnesh** [comment] 2019-06-12 17:28
Hello @qdp-odoo 
Can we please Re-introduce this in 13?

**Comment by qdp-odoo** [comment] 2019-06-14 07:31
okay 
https://github.com/odoo/odoo/pull/34114

**Comment by qdp-odoo** [comment] 2019-06-14 11:46
landed in master, for saas-12.5, at revision https://github.com/odoo/odoo/commit/3309ecbd7a4c61fac476b18642dd7e49c544f7e6

**Closed by qdp-odoo** 2019-06-14 11:46 UTC
Labels: 12.0, Accounting

**Comment by sswapnesh** [comment] 2019-06-14 16:40
Thanks a lot for this.

IMO still we have to align Domain applied in `_invoice_total` (Which does not consider `draft` invoices in total), So Total/Invoices will be aligned.

https://github.com/odoo/odoo/blob/b1ce2dd6c163522633572b31f3aba29a21c5c913/addons/account/models/partner.py#L282
Ps: Adding default Unpaid filter ( `'search_default_unpaid': 1`) will generate more confusion here.
![qdp](https://user-images.githubusercontent.com/16624719/59524214-e9f5b500-8ef0-11e9-89bd-0b8b667d27fc.gif)


Ps2: literal_eval (and itemgetter) is not used so we can remove that too.
