### ISSUE TITLE
[Odoo9.0] reuirements.txt install problem , python setup.py egg_info failed

### ISSUE THREAD

**Issue by akira32chen** [odoo/odoo#70145] opened 2021-04-30 08:14 UTC
Impacted versions: Odoo 9.0

Steps to reproduce:
$ pip install -r requirements.txt

Current behavior:

Expected behavior:

    Complete output from command python setup.py egg_info:
    The required version of setuptools (>=1.4) is not available,
    and can't be installed while this script is running. Please
    install a more recent version first, using
    'easy_install -U setuptools'.
    
    (Currently using setuptools 0.9.8 (/usr/lib/python2.7/site-packages))

Command "python setup.py egg_info" failed with error code 2 in /tmp/pip-build-ynkv0p/suds-jurko/
You are using pip version 8.1.2, however version 21.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

I try to use  the line to install setuptools 1.4.1 in centos7, but it appears those error message:

$ pip install setuptools==1.4.1

The error message:

Collecting setuptools==1.4.1
  Using cached https://files.pythonhosted.org/packages/b2/0f/d08477648a2d4458fe9a149d351665a1742020bc45b6b20eed808fee2f2f/setuptools-1.4.1-py2.py3-none-any.whl
Installing collected packages: setuptools
  Found existing installation: setuptools 0.9.8
    Uninstalling setuptools-0.9.8:
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 326, in run
    strip_file_prefix=options.strip_file_prefix,
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 736, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 742, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/lib/python2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/usr/lib/python2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/usr/lib64/python2.7/shutil.py", line 302, in move
    os.unlink(src)
OSError: [Errno 13] Permission denied: '/usr/bin/easy_install'
You are using pip version 8.1.2, however version 21.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by pedrobaeza** [comment] 2021-04-30 08:57
Sorry, but 9.0 is a deprecated version that is already not being supported, so any bug report about this old version won't be attended, and thus I close this issue. Please check if the problem is still there in new versions, and if so, you can open a new issue regarding that version.

Thanks for your comprehension.

**Closed by pedrobaeza** 2021-04-30 08:57 UTC

**Comment by akira32chen** [comment] 2021-04-30 09:00
Ok, thanks. pedrobaeza.
