### ISSUE TITLE
[11.0] Sales: See own documents group is messy

### ISSUE THREAD

**Issue by edsersolis** [odoo/odoo#24658] opened 2018-05-09 19:01 UTC
Impacted versions:
11.0

Steps to reproduce:
- Create a user
- Set permission to only Sales and group: See Own Documents

Current behavior:
- A permission error raises not allowing the user to save the SO. It states that the user doesn't have privilige for Sales Order Lines but when you go see the settings for this group it does have the privilege. 
- It doesn't happen with other sales groups.

Expected behavior:
- Be able to save the SO without this error.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2018-05-09 19:03
This is because the sales order salesman is not you or empty, so it's working as expected.

**Comment by edsersolis** [comment] 2018-05-09 19:14
@pedrobaeza NOT working as expected. That was one of the first things that were checked.

**Comment by pedrobaeza** [comment] 2018-05-09 19:17
Sorry, but I have said what is the reason of your problem. Why don't you check that or pass screenshots / video about the issue?

**Comment by edsersolis** [comment] 2018-05-09 22:07
Sure, here you go:

![image](https://user-images.githubusercontent.com/6585110/39842179-83acbfce-53b3-11e8-9f95-39fa4e8d51b9.png)

![image](https://user-images.githubusercontent.com/6585110/39842253-c8a555be-53b3-11e8-9630-2ad6918d0408.png)


![image](https://user-images.githubusercontent.com/6585110/39842204-99cca7ba-53b3-11e8-9380-b6eba98baf80.png)

**Comment by pedrobaeza** [comment] 2018-05-09 22:15
You are still missing the main thing: you are not showing me the field "Salesman" (Comercial), which is the one that limits this. You are also forgetting record rules, which is the other security element in Odoo, so please read this documentation about this: https://www.odoo.com/documentation/11.0/reference/security.html#record-rules.

Closing this finally as no real issue, but misunderstanding on how Odoo works and the paper of record rules.

**Closed by pedrobaeza** 2018-05-09 22:15 UTC

**Comment by pedrobaeza** [comment] 2018-05-09 22:27
Yes, there are. See this screenshot taken from runbot:

![seleccion_002](https://user-images.githubusercontent.com/7165771/39842907-dbaed290-53e8-11e8-832b-7e728e1590c3.png)

**Comment by edsersolis** [comment] 2018-05-09 22:30
Those come by default. There are no other than those that may limit the usage of the system.

This is happning to more than 1 customer in v11 and many users. As soon as they're set to be able to see all documents it stops happening.

This didn't happen in v10 or earlier.

**Comment by gustavovalverde** [comment] 2018-05-10 16:54
I take this from another PoV:

This shouldn't be a **record rule**, but just a validation on Python; as for technical users this is easy to find, but for final (and some functional users) it's just too tricky.

In the end, this should be a `raise` with a message like: **You can't sell to a client of another Salesperson** which is more than enough to avoid a bunch of tickets like this one.

**Comment by pedrobaeza** [comment] 2018-05-10 16:57
Yeah, but this is a lot of more Python code to maintain while you already have a mechanism. Teach your users one time and it will be enough.

**Comment by gustavovalverde** [comment] 2018-05-10 17:03
Actually, with my comment, I'm just thinking on **Odoo Online** users, which have no partners on their side who explain this. It can reduce a lot of Tickets for Odoo with a simple _friendly_ message.

Maybe the root issue is that the record rule messages are not friendly at all, and don't have a inner mechanism to customize messages for specific rules (which should be better)

**Comment by pedrobaeza** [comment] 2018-05-10 17:07
Yeah, the problem is that you can't deduce what is the inner cause for something with record rules, but it's the only way to be sure you cut the access to whatever you want, as other mechanisms can't be partial.

**Comment by Yenthe666** [comment] 2018-05-10 19:08
Hi all,

I believe all the ones that have responded now look at this from another point of view. Pedro is the technical thinker, Gustavo takes the middle way and @edsersolis thinks from a functional point of view. In my opinion nobody is wrong here, all choices have a plus and downside. Maybe this would be nice to report as a feedback for future versions. This way functionals can have a look again and who knows it can see an improvement. What do you all think?

**Comment by gustavovalverde** [comment] 2018-05-10 19:10
Agree

**Comment by edsersolis** [comment] 2018-05-12 15:16
https://youtu.be/C-fIGoWiUno
