### ISSUE TITLE
Search more unpredictable

### ISSUE THREAD

**Issue by hparfr** [odoo/odoo#17490] opened 2017-06-08 09:18 UTC
### Impacted versions:

7, 8, 9, 10, master

### Steps to reproduce:
In a form with a many2one, click on "search_more". A dialog opens with results.

### Current behavior:
A maximum of 160 results are displayed.
The result count is wrong (limited to 160).
There is no terms in the search field.

#### Ideal

It should perform a normal search: count all the results and display it in a paginated form. Search terms should be pre-filled in the search field.

#### Acceptable: work the UI to make it predictable 

it should be obvious for the user that the result is incomplete and he should be clear for him how to get all the expected results.

### Related

#17408 #11232 #12001 #2235  #1415  #1386

**Comment by Yenthe666** [comment] 2017-06-08 11:12
Hi @hparfr,

Thanks for your report.
However, did this really need a new issue? You've basically made a duplicate of all those open topics (17408, 11232, 12001, 2235, 1415, 1386).
@mart-e perhaps we should make a final decision in this (at https://github.com/odoo/odoo/issues/17408) so we can handle all these open issues.

Regards,
Yenthe

**Comment by hparfr** [comment] 2017-06-08 13:44
Odoo support told me :  They won't fix how it works nor they won't fix the UI for versions <= 11.

**Comment by Yenthe666** [comment] 2017-06-08 13:48
@hparfr,

So, if you already get a no from Odoo support and you know that it will not be changed / accepted... Why do you open an issue here then?
Closing as you both gave your own answer and because there are literally 6 other reports about the exact same thing.

Regards,
Yenthe

**Closed by Yenthe666** 2017-06-08 13:48 UTC

**Comment by hparfr** [comment] 2017-06-08 14:02
> Why do you open an issue here then?

Last time I requested the support about something I had to first create an issue on github. I wasn't aware the support has updated his process. That's why I created this issue.

>So, if you already get a no from Odoo support [...]

Indeed, I updated the issue __after__ having a response from the support. 

@Yenthe666  You may also close all the issues referenced and label them as "Won't fix."

Regards,

**Comment by Yenthe666** [comment] 2017-06-08 14:10
Ahh I see. You should be fine with logging an issue at the Odoo support itself.
As to all the other issues: I'd like confirmation from @mart-e to be sure if he is fine with it too. 😄

**Comment by mart-e** [comment] 2017-06-08 14:24
> Last time I requested the support about something I had to first create an issue on github. I wasn't aware the support has updated his process. That's why I created this issue.

No we haven't. We don't ask people to create a github issue. I guess a misunderstanding here.

>  As to all the other issues: I'd like confirmation from @mart-e to be sure if he is fine with it too. 😄

Indeed, we won't change it in stable (a bit inconvenient but nothing blocking).
However, we _want_ to change that in master but it is not that easy (we have a problem to keep the current search).
In discussion with the framework team to find a solution but no promise on what and when.
