### ISSUE TITLE
Reports on Firefox

### ISSUE THREAD

**Issue by AquaMCU** [odoo/odoo#42289] opened 2019-12-23 11:10 UTC
Impacted versions: 13, Firefox 71.0 on Ubuntu 18.04

Steps to reproduce:
Open Report in FF. Chrome does not show the bug
![bug](https://user-images.githubusercontent.com/48280831/71354719-1c0d6100-257d-11ea-8120-855aac16648b.gif)

**Comment by pedrobaeza** [comment] 2019-12-23 11:13
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by AquaMCU** [comment] 2019-12-23 11:17
Yes. just reproduced it on 786367-master-cc20e8 ( it is the 2nd green one on runbot master)

Just Login --> Invoicing --> Reporting --> Invoices

**Comment by pedrobaeza** [comment] 2019-12-23 11:19
Master? But that one is not 13.0...

**Comment by AquaMCU** [comment] 2019-12-23 11:21
Its the same on 13 ... I just checked.

**Comment by pedrobaeza** [comment] 2019-12-23 11:24
Well, I'm trying right now and I don't have that problem, so check:

- Version of Firefox not being the latest.
- Firefox complements that alter this.

I'm closing this now while not proved that is really a problem as I have checked myself without that results.

**Closed by pedrobaeza** 2019-12-23 11:24 UTC
Labels: Need information

**Comment by AquaMCU** [comment] 2019-12-23 11:39
I can see, that it depends on the resolution. See new Video. 

![bug3](https://user-images.githubusercontent.com/48280831/71355962-04d07280-2581-11ea-854c-cc91a709efec.gif)

**Comment by pedrobaeza** [comment] 2019-12-23 11:42
I'm still not having that problem:
![Peek 23-12-2019 12-42](https://user-images.githubusercontent.com/7165771/71356175-ace63b80-2581-11ea-9e68-228d2f5fec58.gif)

**Comment by AquaMCU** [comment] 2019-12-23 11:43
Hmm. To bad . I will try to update browser and come back if it is still an issue. Have a nice day and all the best for 2020 ...

**Comment by pedrobaeza** [comment] 2019-12-23 11:45
The same to you. Hope you hunt down the problem or come with more information to know what is happening.
