### ISSUE TITLE
[9.0]Rule from other pricelist is affecting price even compute price is Percentage (discount)

### ISSUE THREAD

**Issue by dev6intellial** [odoo/odoo#11715] opened 2016-04-15 09:47 UTC
**Impacted versions:** 9.0

**Steps to reproduce:**
- In price-list create a price list item for a product and set compute price is formula as shown image below.
- Apply formula with 5% discount and select an other price-list.
  ![4-15-2016 3-26-24 pm](https://cloud.githubusercontent.com/assets/10939916/14557844/e0bf128c-031c-11e6-90fd-687be36f08fc.png)
- In other price-list add global rule with 5% discount.
  ![4-15-2016 3-26-38     @@@@pm](https://cloud.githubusercontent.com/assets/10939916/14557851/f1b3c088-031c-11e6-953e-b873f3571afa.png)
- Now price of product is on 5% discount  with additional 5% discount.
- Now set compute price as discount and set it 5%.
- But still  additional 5% discount is applied.

**Current behavior:**

Additional 5% discount is applied from other price-list even though  compute price is discount.

**Expected behavior:**

Additional 5% discount should not applied from other price-list when compute price is discount.

@beledouxdenis Kindly take a look.

**Comment by pedrobaeza** [comment] 2018-04-24 08:14
This is not the intended behavior, as you can't only apply to other pricelist if the computation method is a formula, not a direct discount. Closing thus.

**Closed by pedrobaeza** 2018-04-24 08:14 UTC
Labels: 9.0, Services
