### ISSUE TITLE
hours_per_day division by zero error.

### ISSUE THREAD

**Issue by eimantasnejus** [odoo/odoo#29908] opened 2019-01-03 19:40 UTC
Impacted versions:
V12 community and enterprise
Steps to reproduce:
This is reproducible on any V12 Odoo runbot (http://runbot.odoo.com/runbot)
1. Employees -> Configuration -> Settings -> Edit Working Hours (something like 'Standard 40 Hours/Week')
2. Try to set up a new working schedule(`resource.calendar.attendancies`), or edit existing one so that all days have Starting Date (`date_from`). While trying to set a start date for last entry, you'll get a division by zero server error.
Current behavior:
You get a division by zero error:

Odoo Server Error
`Traceback (most recent call last):
  File "/data/build/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/data/build/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/data/build/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/data/build/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/build/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/build/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/build/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/data/build/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/data/build/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/data/build/odoo/models.py", line 5430, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/data/build/odoo/models.py", line 5283, in _onchange_eval
    method_res = method(self)
  File "/data/build/odoo/addons/resource/models/resource.py", line 195, in _onchange_hours_per_day
    self.hours_per_day = float_round(hour_count / float(len(set(attendances.mapped('dayofweek')))), precision_digits=2)
ZeroDivisionError: float division by zero`

Expected behavior:
You can easily set Start Dates for all lines in Working Hours with no errors.
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2019-01-03 19:42
Duplicate of #29627

**Closed by pedrobaeza** 2019-01-03 19:43 UTC
