### ISSUE TITLE
InternalError: current transaction is aborted, commands ignored until end of transaction block

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#8514] opened 2015-09-12 07:54 UTC
Code caused by odoo,

Even we put try... except block odoo did not respect except statement... even odoo crash the execution....

  File "/home/expnext/source/v8/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/expnext/source/v8/odoo/openerp/api.py", line 332, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/expnext/source/v8/odoo/openerp/models.py", line 3964, in create
    record = self.browse(self._create(old_vals))
  File "/home/expnext/source/v8/odoo/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/expnext/source/v8/odoo/openerp/api.py", line 464, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/home/expnext/source/v8/odoo/openerp/models.py", line 4102, in _create
    tuple([u[2] for u in updates if len(u) > 2])
  File "/home/devid/source/v8/odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/home/expnext/source/v8/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
InternalError: current transaction is aborted, commands ignored until end of transaction block

**Comment by lynndotconfig** [comment] 2015-12-11 03:13
I have met this problem, too... How do you solve it ?

**Comment by tejastank** [comment] 2015-12-11 12:07
These lot time happen on server with multi-database. Also to work with multi processing enabled module just lot issues, Don't worries 9.0 Enterprise also had same issues till date.

**Comment by travs-w** [comment] 2015-12-17 13:05
I get this issue regularly too, mostly when generating an inventory report. Just because Odoo 9 has the same issue doesn't make the issue any less frustrating.

**Comment by Sanat90** [comment] 2016-02-19 14:06
Really No solution to this yet...

**Comment by jl2035** [comment] 2016-03-10 10:13
Whoah! Isn't this like a huge problem? And I get no hints from the stack trace, about what is going on.

**Comment by tejastank** [comment] 2016-03-10 12:43
Seems they only gives important to bugs which improve enterprise version, else they never response.
Now they had already enterprise version, why one serve you. Aim is full-fulled, is what license affect.

Might someone community response you, but don't wait for theme.


For this issue I suggest you to take latest code for your version of code.
Then update -u all.

Might this resolve your issue.

**Comment by lukebranch** [comment] 2016-03-10 13:19
@tejastank ,

I think this is related to PostgreSQL concurrent transactions, or timeout. These issues might be of interest to you:

https://github.com/odoo/odoo/issues/8585
https://github.com/odoo/odoo/issues/10357

Depending on what version you're using you may want to consider extending the default time limits here:

limit_time_cpu = 60
limit_time_real = 120

to something like this:

limit_time_cpu = 6000
limit_time_real = 12000

in /etc/odoo-server.conf

I may be completely wrong, however i've managed to avoid the error by extending CPU lime limits before on 9.0.

**Comment by tejastank** [comment] 2016-03-10 13:41
@lukebranch Thank for this information we will little increase time and will check different kind of values with CPU and REAL.

But even in local desk with high configuration this happens. 

Thanks for this, will sure try this & resolve it.

**Comment by jl2035** [comment] 2016-03-10 13:55
I installed just like they say in the readme file. Using this command: wget -O- https://raw.githubusercontent.com/odoo/odoo/9.0/odoo.py | python

Can somebody tell me where can I find odoo-server.conf file. It is not under /etc ... :(

**Comment by bluestingray** [comment] 2016-05-18 19:51
Any update on this issue?

**Comment by tejastank** [comment] 2016-05-19 06:03
Issue even come when one single user accessing server, no update till date.

its bug since version 6 to till 9.0. odoo is unstable app

**Comment by jl2035** [comment] 2016-05-19 06:29
I think if you install correctly from a repo with all deps there's no problem. The problem was gone for me after a few installs. Maybe I just got more familiar with odoo.

**Comment by tejastank** [comment] 2016-05-19 06:43
Its problem of architecture not issue of repo, lot many had same issue facing. Even no repo issue at all, avoid it.

They can't fix it till date, some bugs always stay version to version in odoo.

**Comment by Yenthe666** [comment] 2016-06-08 13:48
As luke pointed out this looks like an implementation / configuration issue. None of the latest Odoo codebases reproduce this issue and I personally have 40+ Odoo's running without any of these issues.
Closing this since Luke gave quite some nice pointers and I can't reproduce this in any way.

**Closed by Yenthe666** 2016-06-08 13:48 UTC

**Comment by ydaniels** [comment] 2016-08-04 08:33
The issue is from postgres not odoo but to solve it Odoo still has to implement a way to rollback failed transaction before executing a new one

**Comment by prassannajohnpaul** [comment] 2017-08-25 20:04
Any update on the same?

**Comment by aslamup** [comment] 2017-08-29 07:37
This is what postgres does when a query produces an error and you try to run another query without first rolling back the transaction. To fix it, you'll want to figure out where in the code that bad query is being executed. It might be helpful to use the log_statement and log_min_error_statement options in your postgresql server

**Comment by ray-odoo** [comment] 2019-04-28 18:53
I am getting this error when importing data, so I am assuming the data is generating a bad SQL insert/update.

**Comment by m3asmi** [comment] 2019-06-13 09:38
verify your postgres log

**Comment by ahronshor** [comment] 2019-06-17 23:33
please see [this from odoo docs](https://www.odoo.com/documentation/12.0/reference/guidelines.html#never-commit-the-transaction),
i got the error in a place what i used `self.env.cr.commit()`
but anyway we can fix it by calling `self.env.cr.rollback()` in the try... except block.

**Comment by guopeng1998** [comment] 2020-12-23 13:29
I also encountered this problem, I would like to ask you how to solve it?

**Comment by ahronshor** [comment] 2020-12-23 13:50
add  try... except block and call `self.env.cr.rollback()` in the except before any call to the database.
