### ISSUE TITLE
Picking report is missing barcode when WH name contains non ASCII symbols

### ISSUE THREAD

**Issue by lem8r** [odoo/odoo#8017] opened 2015-08-11 19:28 UTC
I know this is limitation of Code128 algorithm but it have to be stated somewhere not to name WH with non ascii symbols or it has to be transliterated to ascii range before barcode generation.
test link with Cyrillic symbols: https://demo.odoo.com/report/barcode/?type=Code128&value=СКЛД/ВИХ/00001&width=600&height=100

**Comment by Vassy** [comment] 2016-05-07 10:25
Same issue - /report/barcode/?type=Code128&value=СКЛ4\ИЗХ\00001&width=600&height=100

**Comment by Yenthe666** [comment] 2018-02-07 16:38
@sle-odoo I see you self assigned this ages ago. Can you give feedback?

**Comment by sle-odoo** [comment] 2018-02-07 16:52
@Yenthe666 This is not a bug, code 128 works with ascii characters. I should have closed it.

**Closed by sle-odoo** 2018-02-07 16:52 UTC
Labels: Logistics

**Comment by Yenthe666** [comment] 2018-02-08 06:34
Thanks!
