### ISSUE TITLE
error occured while compiling the bundle 'web.assets_backend' containing in Odoo 14.0 enterprise | python 3.7 |  postgres 13.0 | ubuntu 20

### ISSUE THREAD

**Issue by shazzwazz20** [odoo/odoo#60698] opened 2020-10-26 09:06 UTC
Impacted versions:
14.0 enterprise
Steps to reproduce:
Create a new database without demo data and login to odoo
Current behavior:
After login css styling breaks and give below error-
This error occured while compiling the bundle 'web.assets_backend' containing:
    - /web/static/lib/bootstrap/scss/_functions.scss
    - /web/static/lib/bootstrap/scss/_mixins.scss
    - /web/static/src/scss/bs_mixins_overrides.scss
    - /web/static/src/scss/utils.scss
    - /web/static/src/scss/primary_variables.scss
    - /web_enterprise/static/src/scss/primary_variables.scss
    - /web_editor/static/src/scss/web_editor.variables.scss
    - /web_editor/static/src/scss/secondary_variables.scss
    - /web_enterprise/static/src/scss/secondary_variables.scss
    - /web/static/src/scss/secondary_variables.scss
    - /web_editor/static/src/scss/bootstrap_overridden_backend.scss
    - /web_editor/static/src/scss/bootstrap_overridden.scss
    - /web_enterprise/static/src/scss/bootstrap_overridden.scss
    - /web/static/lib/bootstrap/scss/_variables.scss
    - /web/static/src/scss/import_bootstrap.scss
    - /web/static/src/scss/bootstrap_review.scss
    - /web_enterprise/static/src/scss/webclient.scss
    - /web_enterprise/static/src/scss/webclient_layout.scss
    - /web/static/src/scss/webclient.scss
    - /web/static/src/scss/domain_selector.scss
    - /web/static/src/scss/model_field_selector.scss
    - /web/static/src/scss/progress_bar.scss
    - /web/static/src/scss/dropdown.scss
    - /web_enterprise/static/src/scss/dropdown.scss
    - /web/static/src/scss/tooltip.scss
    - /web/static/src/scss/switch_company_menu.scss
    - /web/static/src/scss/debug_manager.scss
    - /web/static/src/scss/control_panel.scss
    - /web/static/src/scss/fields.scss
    - /web_enterprise/static/src/scss/fields.scss
    - /web/static/src/scss/file_upload.scss
    - /web/static/src/scss/views.scss
    - /web/static/src/scss/pivot_view.scss
    - /web/static/src/scss/graph_view.scss
    - /web/static/src/scss/form_view.scss
    - /web_enterprise/static/src/scss/form_view.scss
    - /web/static/src/scss/list_view.scss
    - /web_enterprise/static/src/scss/list_view.scss
    - /web/static/src/scss/kanban_dashboard.scss
    - /web/static/src/scss/kanban_examples_dialog.scss
    - /web/static/src/scss/kanban_column_progressbar.scss
    - /web/static/src/scss/kanban_view.scss
    - /web/static/src/scss/web_calendar.scss
    - /web/static/src/scss/search_view.scss
    - /web/static/src/scss/search_panel.scss
    - /web/static/src/scss/dropdown_menu.scss
    - /web_enterprise/static/src/scss/search_view.scss
    - /web/static/src/scss/data_export.scss
    - /base/static/src/scss/onboarding.scss
    - /web/static/src/scss/attachment_preview.scss
    - /web/static/src/scss/notification.scss
    - /web/static/src/scss/base_document_layout.scss
    - /web/static/src/scss/special_fields.scss
    - /web/static/src/scss/ribbon.scss
    - /web/static/src/scss/base_settings.scss
    - /web/static/src/scss/report_backend.scss
    - /web_mobile/static/src/scss/mobile.scss
    - /web_mobile/static/src/scss/pivot_view_mobile.scss
    - /base_import/static/src/scss/base_import.scss
    - /web_cohort/static/src/scss/web_cohort.scss
    - /web_editor/static/src/scss/web_editor.common.scss
    - /web_editor/static/src/scss/web_editor.backend.scss
    - /web_enterprise/static/src/scss/base_settings_mobile.scss
    - /web_enterprise/static/src/scss/home_menu.scss
    - /web_enterprise/static/src/scss/home_menu_layout.scss
    - /web_enterprise/static/src/scss/search_panel_mobile.scss
    - /web_enterprise/static/src/scss/menu_mobile.scss
    - /web_enterprise/static/src/scss/menu_search.scss
    - /web_enterprise/static/src/scss/control_panel_layout.scss
    - /web_enterprise/static/src/scss/control_panel_mobile.scss
    - /web_enterprise/static/src/scss/datepicker.scss
    - /web_enterprise/static/src/scss/kanban_view.scss
    - /web_enterprise/static/src/scss/touch_device.scss
    - /web_enterprise/static/src/scss/snackbar.scss
    - /web_enterprise/static/src/scss/swipe_item_mixin.scss
    - /web_enterprise/static/src/scss/form_view_mobile.scss
    - /web_enterprise/static/src/scss/kanban_view_mobile.scss
    - /web_enterprise/static/src/scss/modal_mobile.scss
    - /web_enterprise/static/src/scss/web_calendar_mobile.scss
    - /web/static/src/scss/navbar_mobile.scss
    - /web_gantt/static/src/scss/web_gantt.scss
    - /web_grid/static/src/scss/grid_view.scss 
Expected behavior:
After login odoo web should load properly
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2020-10-26 09:10
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by shazzwazz20** [comment] 2020-10-28 14:41
Issue solved by taking pull of latest enterprise code.

**Closed** 2020-10-28 14:41 UTC
Labels: Need information

**Comment by AhmedEltaybShi** [comment] 2021-09-19 13:05
try to run this command 
sudo npm install -g less@3.0.4 less-plugin-clean-css

**Comment by Akashshere19** [comment] 2022-11-04 12:47
This error occured while compiling the bundle 'web.assets_frontend' containing:
    - /web/static/lib/bootstrap/scss/_functions.scss
    - /web/static/lib/bootstrap/scss/_mixins.scss
    - /web/static/src/scss/bs_mixins_overrides.scss
    - /web/static/src/scss/utils.scss
    - /web/static/src/scss/primary_variables.scss
    - /web_editor/static/src/scss/web_editor.variables.scss
    - /mail/static/src/scss/variables.scss
    - /portal/static/src/scss/primary_variables.scss
    - /website/static/src/scss/primary_variables.scss
    - /website/static/src/scss/options/user_values.custom.web.assets_common.scss
    - /website/static/src/scss/options/colors/user_color_palette.scss
    - /website/static/src/scss/options/colors/user_theme_color_palette.custom.web.assets_common.scss
    - /website/static/src/snippets/s_badge/000_variables.scss
    - /website/static/src/snippets/s_product_list/000_variables.scss
    - /account/static/src/scss/variables.scss
    - /hr_org_chart/static/src/scss/variables.scss
    - /sh_back_theme_config/static/src/scss/back_theme_config_main_scss.scss
    - /website/static/src/scss/secondary_variables.scss
    - /web_editor/static/src/scss/secondary_variables.scss
    - /web/static/src/scss/secondary_variables.scss
    - /website/static/src/scss/user_custom_bootstrap_overridden.scss
    - /website/static/src/scss/bootstrap_overridden.scss
    - /portal/static/src/scss/bootstrap_overridden.scss
    - /web_editor/static/src/scss/bootstrap_overridden.scss
    - /web/static/src/scss/bootstrap_overridden_frontend.scss
    - /web/static/lib/bootstrap/scss/_variables.scss
    - /web/static/src/scss/import_bootstrap.scss
    - /web/static/src/scss/bootstrap_review.scss
    - /web/static/src/scss/base_frontend.scss
    - /web/static/src/scss/lazyloader.scss
    - /web/static/src/scss/navbar_mobile.scss
    - /web/static/src/scss/notification.scss
    - /web_editor/static/src/scss/web_editor.common.scss
    - /web_editor/static/src/scss/web_editor.frontend.scss
    - /portal/static/src/scss/bootstrap.extend.scss
    - /portal/static/src/scss/portal.scss
    - /website/static/src/scss/website.scss
    - /website/static/src/scss/website.ui.scss
    - /website/static/src/snippets/s_alert/000.scss
    - /website/static/src/snippets/s_card/000.scss
    - /website/static/src/snippets/s_share/000.scss
    - /website/static/src/snippets/s_rating/001.scss
    - /website/static/src/snippets/s_hr/000.scss
    - /website/static/src/snippets/s_image_gallery/001.scss
    - /website/static/src/snippets/s_product_catalog/001.scss
    - /website/static/src/snippets/s_comparisons/000.scss
    - /website/static/src/snippets/s_company_team/000.scss
    - /website/static/src/snippets/s_references/000.scss
    - /website/static/src/snippets/s_popup/001.scss
    - /website/static/src/snippets/s_faq_collapse/000.scss
    - /website/static/src/snippets/s_features_grid/000.scss
    - /website/static/src/snippets/s_tabs/001.scss
    - /website/static/src/snippets/s_table_of_content/000.scss
    - /website/static/src/snippets/s_quotes_carousel/001.scss
    - /website/static/src/snippets/s_masonry_block/001.scss
    - /website/static/src/snippets/s_media_list/001.scss
    - /website/static/src/snippets/s_timeline/000.scss
    - /website/static/src/snippets/s_process_steps/000.scss
    - /website/static/src/snippets/s_text_highlight/000.scss
    - /website/static/src/snippets/s_blockquote/000.scss
    - /website/static/src/snippets/s_badge/000.scss
    - /website/static/src/snippets/s_color_blocks_2/000.scss
    - /website/static/src/snippets/s_product_list/000.scss
    - /website/static/src/snippets/s_google_map/000.scss
    - /website/static/src/snippets/s_dynamic_snippet/000.scss
    - /website/static/src/snippets/s_dynamic_snippet_carousel/000.scss
    - /website/static/src/snippets/s_btn/000.scss
    - /website_mail/static/src/css/website_mail.scss
    - /portal_rating/static/src/scss/portal_rating.scss
    - /payment/static/src/scss/portal_payment.scss
    - /payment/static/src/scss/payment_form.scss
    - /sale/static/src/scss/sale_portal.scss
    - /rating/static/src/scss/rating.scss
    - /project/static/src/scss/portal_rating.scss
    - /sale_timesheet/static/src/scss/sale_timesheet_portal.scss
    - /sh_all_in_one_helpdesk/static/src/css/feedback.scss
    - /sh_back_theme_config/static/src/scss/fonts.scss
    - /sh_backmate_theme/static/src/scss/login_style_1.scss
    - /website/static/src/scss/user_custom_rules.scss

**Comment by Akashshere19** [comment] 2022-11-04 12:48
I am facing above problem on windows....
