### ISSUE TITLE
Stripe  Payment Redirect to  /shop/undefined

### ISSUE THREAD

**Issue by prakashkumar163** [odoo/odoo#20232] opened 2017-10-17 07:52 UTC
Impacted versions:V11

Steps to reproduce:
On shop/payment page while selecting the stripe, no popup open.
Instead, it redirects to /shop/undefined

Current behavior:
Undefined  redirect
Expected behavior:
Stripe popup open should open.

**Comment by Yenthe666** [comment] 2017-10-17 12:11
Duplicate of https://github.com/odoo/odoo/issues/20054

**Closed by Yenthe666** 2017-10-17 12:11 UTC
