### ISSUE TITLE
POS Invoicement and payment

### ISSUE THREAD

**Issue by alejandroperezcosio** [odoo/odoo#6534] opened 2015-04-30 20:16 UTC
On branch 8.0
Modules: 
- point_of_sale
- account
- account_voucher

Problem:
Selling something from the POS and then "close session" -> "validate closing and post entries", the invoice related to the pos_order will not have any payment nor change its state to "paid", it remains without payments and "open".
Some manual steps need to be performed to complete the process:
- Create a new Customer Payment from invoicing
- Select the invoiced user 
- Put the amount to charge
- Validate the payment

Expected behavior:
On "validate closing and post entries", also, set the payment for that customer with the correct amount, and validate automatically the payment.

**Comment by wtaferner** [comment] 2015-05-01 05:44
:+1: by now you could reconcile the payments with the invoices afterwards and separately to achieve this but it should be done automatically.

**Comment by beledouxdenis** [comment] 2015-06-10 10:27
Hello Luis, Wolfgang,

We understand the need to automatically reconcile the payments journal items with the invoices journal items.

However, we cannot change this in a stable release such as 8.0: This will lead to a huge change of behavior: Companies currently in production may rely on the current behavior, and require the intervention of an accountant to validate each POS invoice.

What we could do is, in the master development branch, add a boolean "Auto-reconciliation" somewhere (in the POS Terminal configuration ?) that once checked auto reconcile payments and invoices.

Currently, this is expected to not reconcile automatically the payments with the invoices of the point of sale module. Changing that in the stable releases 8.0 will lead to a huge change of behavior, which is prohibited by our stable policy, for the reasons I mention above. To know more about our stable policy, please read:
https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean

Does the change I propose in the master development branch fit your requirements ?

Regards,

**Comment by wtaferner** [comment] 2015-06-10 12:22
Hi Denis,
Thank you for taking a look. I think your change suggested would make it more flexible and sufficient to resolve the issue given. Although I guess the default should be to have it auto-reconciled and to uncheck in case it is unwanted. Would be nice if you could link the pull request to the master later that I might backport it easily to v8 in case my customer needs it desperately and it is already there ;-)

Regards,

**Comment by beledouxdenis** [comment] 2015-06-10 12:27
Wolfgang, 

I do not develop in the master branch. This feature will therefore not be my responsibility, but the responsibility of another team. I will simply forward the development request to the team in charge.

Regarding v8: I am allmost sure that this can be "corrected" through a simple automated action, triggered on update of the pos.order to the validated state, and performing the reconciliation operations needed.

Regards,

**Comment by wtaferner** [comment] 2015-06-10 12:37
I know, but it would be even nice when the responsible would somehow do :-) Linking on Github is such a beautiful feature so I encourage whenever it is possible...and it would help a lot to make communication super-efficient even without Odoo ;-)

Jep, you are right, it can be done...one way or the other...thank you for your quick suggestion how to "correct" it :-)

**Comment by alejandroperezcosio** [comment] 2015-06-10 13:36
+1
I'm eager to see this feature working..

Best regards
--
Alejandro

**Comment by Amit-Parik** [comment] 2015-06-15 06:45
We also faced the same problem here with this.

Evan we can't manually reconcile the journal item because what I see that in invoice the journal entry created with the tax amount, so receivable account contains the tax amount and bank statement/cash register journal entry doesn't contains the tax amount.
So here is the case we can see the partner journal item with different amount and we can't able to close it .

Any clue about this?

**Comment by Amit-Parik** [comment] 2015-06-18 10:55
hello,

I have found the some temporary solution for this. 
When we are doing to close the POS session we can reconcile the both journal item, one if created from invoice and another created from bank statement/cash register .

So once this will be reconciled all related invoice for that perticuler session has been paid.

Here is the method what we override and did this changes to make it work.

class pos_session(osv.osv):
    _inherit = 'pos.session'
    
    def _confirm_orders(self, cr, uid, ids, context=None):
        
        account_move_obj = self.pool.get('account.move')
        account_move_line_obj = self.pool.get('account.move.line')
        pos_order_obj = self.pool.get('pos.order')
        for session in self.browse(cr, uid, ids, context=context):
            local_context = dict(context or {}, force_company=session.config_id.journal_id.company_id.id)
            order_ids = [order.id for order in session.order_ids if order.state == 'paid']

            move_id = account_move_obj.create(cr, uid, {'ref' : session.name, 'journal_id' : session.config_id.journal_id.id, }, context=local_context)
            
            pos_order_obj._create_account_move_line(cr, uid, order_ids, session, move_id, context=local_context)

            for order in session.order_ids:
                if order.state == 'done':
                    continue
                if order.state not in ('paid', 'invoiced'):
                    raise osv.except_osv(
                        _('Error!'),
                        _("You cannot confirm all orders of this session, because they have not the 'paid' status"))
                else:
                    pos_order_obj.signal_workflow(cr, uid, [order.id], 'done')
            order_ids = self.pool.get('pos.order').search(cr, uid, [('session_id','=', session.id)])
            for obj_order_id in self.pool.get('pos.order').browse(cr, uid, order_ids, context=context):
                move_line = []
                
                for move_line_id in obj_order_id.invoice_id.move_id.line_id:
                    if move_line_id.name == obj_order_id.name:
                		
                        move_line.append(move_line_id.id)
                
   
                for statement_id in obj_order_id.statement_ids:
                    move_line_ids = account_move_line_obj.search(cr, uid, [('statement_id','=', statement_id.statement_id and statement_id.statement_id.id)]) 
                    
                    for line in account_move_line_obj.browse(cr, uid, move_line_ids):
                    	
                        if line.credit and line.name.strip().strip(':') == obj_order_id.name:
                          move_line.append(line.id) 
           
                ctx = context.copy()
                ctx.update({'active_ids': move_line})
                self.pool.get('account.move.line.reconcile').trans_rec_reconcile_full(cr, uid, [], ctx)
                #move_line_ids = self.pool.get('account.move.line').search(cr, uid, [('name','=',obj_order_id.name)])
                #print "@######move_line_id@@@@", move_line_ids  
        
        return True

**Comment by lapagept** [comment] 2015-11-21 03:04
Thanks for this good method. 
But sometimes I get this error when I try to close and validate the pos.session : 
    except_orm: (u'Warning!', u'You have to provide an account for the write off/exchange difference entry.')
Idea?

**Comment by lapagept** [comment] 2015-11-22 20:45
With the above method "_confirm_orders" you can close an validate a pos session if ALL the pos.order have been invoiced.

If just one order of the pos session have not been invoiced (just validated, with the pos receipt), I get this error :   except_orm: (u'Warning!', u'You have to provide an account for the write off/exchange difference entry.')

**Comment by lapagept** [comment] 2015-12-01 15:50
Hello all! After two days of work, here is our new method. This new method can also reconciliate the return amount  (the money that we give back to the customer).
`sdfasd`

**Comment by Amit-Parik** [comment] 2015-12-01 16:15
Hello,

I will test this soon and let you know.
After all this is a good work! 

Appreciated
Thanks

**Comment by mohamedhagag** [comment] 2016-04-08 07:57
Just in case that there are people still looking for a fix, here is a simple module that will auto reconcile the invoice with its payment so the invoice will be paid.

https://github.com/mohamedhagag/dvit-odoo8/tree/master/pos_invoice_payment_auto_reconcile

**Comment by mohamedhagag** [comment] 2017-02-05 23:45
for v 8.0 you the module have been renamed to pos_fixes available in the same repo.
It may work with v 9.0 after some little modifications but I didn't port it till now.
https://github.com/mohamedhagag/dvit-odoo8/tree/master/pos_fixes

**Comment by damendieta** [comment] 2017-02-06 14:08
@mohamedhagag thanks a lot.

**Comment by Yenthe666** [comment] 2017-12-13 07:28
Hi @alejandroperezcosio ,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Closed by Yenthe666** 2017-12-13 07:28 UTC
