### ISSUE TITLE
res.group full names with '/' in group name are not searchable

### ISSUE THREAD

**Issue by dek-odoo** [odoo/odoo#17025] opened 2017-05-17 05:23 UTC
Impacted versions:
>V10 and probably others

Steps to reproduce:

>search like ('full_name',=,'Technical Settings / Manage Lots / Serial Numbers'):

Current behavior:

>If you try to search a full_name of a group that has a '/' in its group name, (for e.g. 'Manage Lots / Serial Numbers'), it returns nothing.
So for a search like ('full_name',=,'Technical Settings / Manage Lots / Serial Numbers'):
Internally category_id.name becomes 'Technical Settings / Manage Lots' and group name becomes 'Serial Numbers'

Possible Root Cause:
>It looks like the problem is in _search_full_name: https://github.com/odoo/odoo/blob/10.0/odoo/addons/base/res/res_users.py#L100

<b>Or Else the group names should not have a '/' in it.</b>

Expected behavior:

Video/Screenshot link (optional):

**Comment by dek-odoo** [comment] 2017-05-17 05:24
@Yenthe666

**Comment by Yenthe666** [comment] 2017-05-17 05:42
Hi @dek-odoo,

Thank you for your report!
This indeed looks like an issue. The `split()` method on the '/' is probably to blame here.
Nevertheless, why search by the name though? It is much better to such by ID for example. Nevertheless it is a bug.
@mart-e can we change this behaviour so it accepts the '/' too?

Regards,
Yenthe

**Comment by dek-odoo** [comment] 2017-05-18 07:52
Thanks @Yenthe666 for the suggestion.
That's what we did to overcome the problem, but as a work around.

**Comment by mart-e** [comment] 2017-05-23 11:12
Hello,

The issue is that the displayed name is "Category / Group", so if you search on "Category / Group", you must find it (to have the `name_search` to be the reversed of the `name_get`).
Having groups containing `/` in their name is probably a bad idea because of this behaviour.
Searching for just "Manage Lots / Serial Numbers" should work though.

We are not going to remove the split to keep the reverse.
Maybe we could try to improve it if there is more than one `/` in the search but not sure how yet.

**Comment by pedrobaeza** [comment] 2018-05-29 23:01
I also don't know how to handle this in code for this very little examples, but this is the same as using `%` in a search, because it acts like a wildcard. You can search omitting taking a part of the group name. The only real case can be if you copy/paste full group name, but that's not going to happen frequently on groups (not as in categories, locations, etc) and the number of groups with `\` is very low.

@mart-e, a good option would be to not use `\` character anymore in that groups and replace it by `-` for example.

Any way, closing this as nothing critical and not a bug, but an improvement.

**Disclaimer**: I'm not an Odoo employee, but a community member that voluntary contributes to triage / classify / solve issues. Take also into account that there's no obligation to answer nor solving things put in Odoo Community issue tracker. And thus, please consider this as a best effort initiative.

**Closed by pedrobaeza** 2018-05-29 23:01 UTC
Labels: Wishlist
