### ISSUE TITLE
Error when i switched into kanban view(different error in different feature)

### ISSUE THREAD

**Issue by seemugia1** [odoo/odoo#24839] opened 2018-05-22 02:19 UTC
Impacted versions: 11.0

Steps to reproduce:
1. activate developer mode
2. Go to Sales->quotation //or any other features which started with list view
3. open developer tools->edit list view->view type change into kanban view
4. Save and refresh

Current behavior:
-If i do this error in quotation feature, it shows: Uncaught TypeError: Cannot read property 'tag' of undefined
-but if i do this error in orders feature, it shows: Uncaught Error: Unknown field state in domain

Expected behavior:
switch into kanban view
Video/Screenshot link (optional):
Quotation feature
![screenshot from 2018-05-22 09-07-34](https://user-images.githubusercontent.com/25352142/40338722-f9515d6a-5da0-11e8-8c99-3e6067ebb67f.png)

Orders feature
![screenshot from 2018-05-22 09-18-11](https://user-images.githubusercontent.com/25352142/40338742-155fef62-5da1-11e8-8875-b2b791b66af8.png)

**Comment by pedrobaeza** [comment] 2018-05-22 07:20
You sho
Hi, I'm not able to reproduce this problem in latest runbot version, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-05-22 07:20 UTC
Labels: 11.0, Framework
