### ISSUE TITLE
[All versions][Fleet] Odometer creation from fuel log

### ISSUE THREAD

**Issue by elperrofarelo** [odoo/odoo#53474] opened 2020-06-23 06:08 UTC
Impacted versions:
All versions

Steps to reproduce:
A new odometer record is always created after giving a new odometer value in fuel log.
The problem comes when there is a typing mistake in the odometer value and we want to correct it, then a new odometer record is created and the old wrong odometer record maintains.

Current behavior:
    def _set_odometer(self):
        for record in self:
            if not record.odometer:
                raise UserError(_('Emptying the odometer value of a vehicle is not allowed.'))
            odometer = self.env['fleet.vehicle.odometer'].create({
                    'value': record.odometer,
                    'date': record.date or fields.Date.context_today(record),
                    'vehicle_id': record.vehicle_id.id
                })
           self.odometer_id = odometer

Expected behavior:
Proposed code change:
    def _set_odometer(self):
        for record in self:
            if not record.odometer:
                raise UserError(_('Emptying the odometer value of a vehicle is not allowed.'))
            # Added
            if record.odometer_id:
                record.odometer_id.vehicle_id = record.vehicle_id
                record.odometer_id.value = record.odometer
                record.odometer_id.date = record.date
            else:
                odometer = self.env['fleet.vehicle.odometer'].create({
                    'value': record.odometer,
                    'date': record.date or fields.Date.context_today(record),
                    'vehicle_id': record.vehicle_id.id
                })
                self.odometer_id = odometer

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2020-06-23 07:27
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by elperrofarelo** [comment] 2020-06-23 10:33
Hi. 
It's not a code error itself. It only appears when someone types a wrong odometer value in fuel log / service log and saves it, then ALLWAYS a new odometer record is created. My code proposal works checking before if there's an odometer_id and modifying it instead creating a new one.
And yes the "problem" can be reproduced in runbot

**Comment by pedrobaeza** [comment] 2020-06-23 10:35
But please specify the steps to reproduce it. How do you get to modify that odometer that way?

**Closed** 2023-04-07 14:28 UTC
Labels: Need information
