### ISSUE TITLE
[11.0] Search more not displayed while inherit name_get not method

### ISSUE THREAD

**Issue by Gokulakannanaj** [odoo/odoo#28847] opened 2018-11-20 14:38 UTC
Impacted versions:
[11.0]

Steps to reproduce:
Inherit name_get method like below code

```
@api.multi
def name_get(self):
       if self.env.uid != 1:
              return [(record.id, record.name) for record in self if record.id != 1]
       else:
              return [(record.id, record.name) for record in self]
```
Current behavior:
Search more not displayed in m2o field. 
[Note: number of records is 32]

Expected behavior:
Search more want to be displayed in m2o field.

If logged in as a Admin user it works perfectly. Otherwise search more not displayed.

**Comment by pedrobaeza** [comment] 2018-11-20 15:05
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2018-11-20 15:05 UTC
