### ISSUE TITLE
[13] The problem of  when the model with _inherits fields and image field

### ISSUE THREAD

**Issue by joshuajan** [odoo/odoo#48438] opened 2020-03-26 13:27 UTC
Impacted versions:
13.0

Steps to reproduce:
1. modify the product variants's `name` and  remove `image` and save.
2. Get error mssage "Model: Product Template (product.template), Field: Name (name)".

Current behavior:
error message: "Model: Product Template (product.template), Field: Name (name)"

I have debug the code I found this problem is the image fields is a `attachment=Ture`. When you remove the image. The attachment object will be `unlink`. And the `unlink` method will clean the cache. So the product.product.name is null and can not be save for product.template.

Expected behavior:
save success

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/1176173/77651394-aebc0280-6fa7-11ea-8760-0b9de9f3dd4c.png)
![image](https://user-images.githubusercontent.com/1176173/77651351-a2d04080-6fa7-11ea-8887-ec69626a3635.png)

**Comment by pedrobaeza** [comment] 2020-03-26 15:49
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by sswapnesh** [comment] 2020-03-26 16:45
I can reproduce this on Latest Runbot at https://1912799-13-0-38e90e.runbot45.odoo.com/web#id=15&action=246&model=product.product&view_type=form&cids=&menu_id=585

**Comment by pedrobaeza** [comment] 2020-03-26 16:47
@rco-odoo this seems something for you

**Comment by C3POdoo** [comment] 2023-03-30 11:41
Dear @joshuajan,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._

**Closed by C3POdoo** 2023-03-30 11:41 UTC
Labels: ORM, 13.0
