### ISSUE TITLE
URGENT!! Web Site and Payment: Issue with 'Pay Now' button

### ISSUE THREAD

**Issue by valermari** [odoo/odoo#76306] opened 2021-09-10 09:06 UTC
Impacted versions: v. 14.0

Steps to reproduce: 
1. Add some products to the cart and proceed to checkout.
2. Select the payment method.
3. Press the "Pay Now"

Current behavior:
1. The button will keep loading and there seems to be no response on the page.
2. Odoo server seems to be entered a deadlock state.

Expected behavior:
The page will loading and I should enter the page of  /shop/confirmation

Video/Screenshot link (optional):
![Problem](https://user-images.githubusercontent.com/90445565/132829681-90325449-5c7c-4e54-971c-622660726fea.jpg)

**Comment by pedrobaeza** [comment] 2021-09-10 09:08
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by valermari** [comment] 2021-09-10 10:18
I can't reproduce the problem in runbut infrastructure because I'm using odoo for a university project and the professor created a virtual machine for us. 
Anyway, the 'Pay Now' problem arose when I added lines of code to the 'payment' view module by VisualStudioCode. These lines  are useful to create the 'Cardholder Name', 'Card Number' fields and so on. when choosing the payment method. But even trying to eliminate those lines of code the problem persists.

I attach the video file.

https://user-images.githubusercontent.com/90445565/132838965-e89f78ca-c271-4a8e-b8eb-45d4c6a3bc5c.mp4

**Comment by pedrobaeza** [comment] 2021-09-10 10:20
I'm afraid that if you don't reproduce it on standard runbot, then it's due to your installation, and so, you need to get help by other means (your professor, forums, etc), but not here.

Closing as no reproducible.

**Closed by pedrobaeza** 2021-09-10 10:20 UTC
Labels: Need information
