### ISSUE TITLE
Bank Reconcilation Line Item - 'has_no_partner' undefined

### ISSUE THREAD

**Issue by holdenrehg** [odoo/odoo#12306] opened 2016-06-06 16:48 UTC
**Impacted versions:**

9.0 Enterprise

**Steps to reproduce:**

I cannot consistently reproduce the error, but on some bank statement imports when reconciling the line items.

**Current behavior:**

Throws a js error:

`Uncaught TypeError: Cannot read property 'has_no_partner' of undefined`

This is happening in the render function of `bankStatementReconciliationLine` in `account/static/src/js/account_reconcilation_widgets.js` around line 1673 at the line:

`self.st_line.has_no_partner`

This is not affecting any actions, the line still reconciles correctly, and everything processes correctly on the backend. It appears to happen when `self.st_line` is undefined which can happen in the init function if inital_data_provided is falsy. This should be able to be resolved by updating the follwing lines and adding a check for st_line:

`if (self.st_line && self.st_line.no_match) self.$el.addClass("no_match");`

```
if (self.st_line && self.st_line.has_no_partner) {
    self.updateBalance();
    self.$(".change_partner_container").show(0);
    self.$el.addClass("no_partner");
}
```

**Expected behavior:**

No error appears.

**Video/Screenshot link (optional):**

**Comment by Yenthe666** [comment] 2016-06-07 06:17
Hi @holdenrehg,

Thanks for your report! Are you facing this issue on the latest code from Odoo? Can you reproduce this on the runbot too?
@qdp-odoo pinging you, this might ring a bell for you.

**Comment by holdenrehg** [comment] 2016-06-07 14:52
@Yenthe666, I am on the latest code but cannot reproduce on runbot. It does seem pretty inconsistent so this may not be something that can be easily fixed by the community, but wanted to report it and see if anyone has seen similar issues.

**Comment by qdp-odoo** [comment] 2016-06-09 08:57
I've no idea, but this doesn't seem urgent at all.

Cédric can you check if the proposed patch fix the error or simply hides the symptoms?

**Comment by Xpiva** [comment] 2016-06-09 19:00
I am having the same issue, and have the latest updates.

**Comment by holdenrehg** [comment] 2016-06-14 14:08
@Xpiva are you able to consistently reproduce?

**Comment by manney** [comment] 2016-09-07 18:37
Hi @qdp-odoo / @csnauwaert 

Has this been moved on any further?  Our customer is now experiencing this issue every time they reconcile.

Thanks.

**Comment by qdp-odoo** [comment] 2016-09-26 07:55
We're not able to reproduce that at our side, please open a ticket and provide us a database where this error occurs if you want us to fix it..

**Comment by Yenthe666** [comment] 2018-01-16 08:26
Hey @holdenrehg,

If you still face this problem then please do use your enterprise license and report it at odoo.com/help.
I'll close this one as there is no way to reproduce at the moment (and it has been quite for over a year).
P.S: Hope you're doing well!

Regards,
Yenthe

**Closed by Yenthe666** 2018-01-16 08:26 UTC
