### ISSUE TITLE
[14.0] Unmet dependencies: board

### ISSUE THREAD

**Issue by Manopphysics** [odoo/odoo#71899] opened 2021-06-09 09:08 UTC
Impacted versions:

Odoo Server 14.0 (Community)

Steps to reproduce:
https://www.odoo.com/documentation/14.0/developer/howtos/backend.html#dashboards

Current behavior:
There seems to be an unmet dependency issue with 'board' as I'm following the steps from the tutorial to create a dashboard.

2021-06-09 09:02:25,071 21357 INFO db2 odoo.modules.graph: module openacademy: Unmet dependencies: board 

Expected behavior:

There should be no dependency problem for 'board' as it is present in the addons folder, and the odoo.conf already specified the correct path, I checked that countless times already.

Video/Screenshot link (optional):

![Screenshot from 2021-06-09 16-02-41](https://user-images.githubusercontent.com/30766552/121325929-3dfacf00-c93c-11eb-9852-289e03a9fd06.png)

**Comment by pedrobaeza** [comment] 2021-06-09 19:11
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2021-06-09 19:11 UTC
