### ISSUE TITLE
[8.0][website_event_track] Duplicated timezone field

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#7173] opened 2015-06-19 11:41 UTC
The `event` module already defines the [`date_tz` field](https://github.com/odoo/odoo/blob/a9e3d74713b6882c64617345696ad326d75a4745/addons/event/event.py#L119), but `website_event_track` defines the [redundant `timezone_of_event` field](https://github.com/odoo/odoo/blob/a9e3d74713b6882c64617345696ad326d75a4745/addons/website_event_track/models/event.py#L153).

It's useless and confusing.

**Comment by Yajo** [comment] 2015-06-23 10:59
Seems fixed in master.

**Comment by sle-odoo** [comment] 2016-06-10 12:56
Closing as we won't change the database structure and the issue is fixed in the next version.
Regards

**Closed by sle-odoo** 2016-06-10 12:56 UTC
