### ISSUE TITLE
[11.0] The whole forecasted digital doesn't show in Chinese or Japanese.

### ISSUE THREAD

**Issue by jlzhou** [odoo/odoo#23930] opened 2018-03-29 00:56 UTC
Impacted versions:
11.0
Steps to reproduce:
Convert to Chinese or Japanese Lang, go  product page.
Current behavior:
See below picture.
Expected behavior:
Show whole digital when the display space is sufficient.
Video/Screenshot link (optional):
English is OK
<img width="722" alt="forecast4" src="https://user-images.githubusercontent.com/1243299/38064174-37ea01ae-332f-11e8-9569-27beede2bffd.png">
<img width="740" alt="forecast3" src="https://user-images.githubusercontent.com/1243299/38064119-009adce6-332f-11e8-862d-73ba59bb699c.png">
<img width="673" alt="forecast2" src="https://user-images.githubusercontent.com/1243299/38064126-05ac157e-332f-11e8-9064-e6be2dd2aac0.png">

**Comment by jlzhou** [comment] 2018-03-29 23:32
I think it is not about translation, but about style sheet setting.

**Comment by Yenthe666** [comment] 2018-03-30 07:54
@jlzhou its the best matching label I have for this, basically. The source is because of the text (terms), so I guess it is related to translations (although it is coming from stylesheet)

**Comment by mart-e** [comment] 2020-05-15 13:47
![Screenshot_2020-05-15 ASUSTeK - Odoo](https://user-images.githubusercontent.com/564822/82057199-480fb700-96c3-11ea-8cc5-d0cce43b7ec6.png)

Closing as looks solved but let me know if you can reproduce.
Anyway it's definitly a styling issue, not the translation engine

**Closed by mart-e** 2020-05-15 13:47 UTC
Labels: 11.0, Internationalization
