### ISSUE TITLE
Uncaught TypeError: Cannot read property 'digits' of undefined

### ISSUE THREAD

**Issue by JpGarciiia964** [odoo/odoo#46582] opened 2020-02-28 14:30 UTC
Impacted versions:
V 11
Steps to reproduce:
1- Go to the billing or accounting module.
2- Click on the "CONCILIAR 'N' ELEMENTOS" button.
3- Assign an account to the line you want to reconcile
4- Click on the VALIDATE button.
Current behavior:

When validating, it generates the following error:

Uncaught TypeError: Cannot read property 'digits' of undefined

http://odooprod.fledgit.com/web/content/1638-eff7471/web.assets_backend.js:2491
Traceback:
TypeError: Cannot read property 'digits' of undefined
    at http://odooprod.fledgit.com/web/content/1638-eff7471/web.assets_backend.js:2491:616
    at Function._.each._.forEach (http://odooprod.fledgit.com/web/content/1472-84b29e0/web.assets_common.js:12:558)
    at Class.validate (http://odooprod.fledgit.com/web/content/1638-eff7471/web.assets_backend.js:2490:28)
    at Class._onValidate (http://odooprod.fledgit.com/web/content/1638-eff7471/web.assets_backend.js:2461:1702)
    at Class.<anonymous> (http://odooprod.fledgit.com/web/content/1472-84b29e0/web.assets_common.js:3923:11)
    at Class.trigger (http://odooprod.fledgit.com/web/content/1472-84b29e0/web.assets_common.js:3921:180)
    at Class._trigger_up (http://odooprod.fledgit.com/web/content/1472-84b29e0/web.assets_common.js:3927:365)
    at Class._trigger_up (http://odooprod.fledgit.com/web/content/1472-84b29e0/web.assets_common.js:3927:449)
    at Class.trigger_up (http://odooprod.fledgit.com/web/content/1472-84b29e0/web.assets_common.js:3927:280)
    at Class._onValidate (http://odooprod.fledgit.com/web/content/1638-eff7471/web.assets_backend.js:2540:69)

Expected behavior:

You should validate the reconciliation without errors

Video/Screenshot link (optional):

![1](https://user-images.githubusercontent.com/26505235/75556770-33e9e100-5a15-11ea-84b0-a98b8a593363.png)
![2](https://user-images.githubusercontent.com/26505235/75556774-35b3a480-5a15-11ea-8162-ff894ffc3113.PNG)
![3](https://user-images.githubusercontent.com/26505235/75556775-364c3b00-5a15-11ea-999e-8e42b026fc3c.PNG)

**Comment by pedrobaeza** [comment] 2020-02-28 14:44
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by JpGarciiia964** [comment] 2020-02-28 23:46
Hi,

I could not reproduce the error at (http://runbot.odoo.com/runbot - admin / admin), I will try to update all my odoo since I have, Odoo 11.0-20191011 (Community Version).


Thank you very much for your reply.

**Comment by pedrobaeza** [comment] 2020-02-29 10:14
OK, thanks for the followup. I'm closing this then now, but if you reproduce it later on standard, we can reopen.

**Closed by pedrobaeza** 2020-02-29 10:14 UTC
Labels: Need information
