### ISSUE TITLE
short dump in pick components stock movement

### ISSUE THREAD

**Issue by ccandito** [odoo/odoo#28378] opened 2018-11-04 09:18 UTC
Impacted versions:
12 CE

Steps to reproduce:
perform a pick conponents stock movement with qty less than planned
select no backorder option

Current behavior:
short dump has occurred 
system log is reported below

Expected behavior:
no dump

Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo12/odoo/odoo/api.py", line 1032, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7fefc285a5f8>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo12/odoo/odoo/fields.py", line 970, in __get__
    value = record.env.cache.get(record, self)
  File "/home/odoo12/odoo/odoo/api.py", line 1034, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('mail.activity(20,).res_name', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo12/odoo/odoo/http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo12/odoo/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo12/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo12/odoo/odoo/http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo12/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo12/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo12/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo12/odoo/odoo/http.py", line 938, in __call__
    return self.method(*args, **kw)
  File "/home/odoo12/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo12/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo12/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo12/odoo/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo12/odoo/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo12/odoo/addons/stock/wizard/stock_backorder_confirmation.py", line 34, in process_cancel_backorder
    self._process(cancel_backorder=True)
  File "<decorator-gen-191>", line 2, in _process
  File "/home/odoo12/odoo/odoo/api.py", line 372, in loop
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/home/odoo12/odoo/odoo/api.py", line 372, in <listcomp>
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/home/odoo12/odoo/addons/stock/wizard/stock_backorder_confirmation.py", line 22, in _process
    pick_id._log_less_quantities_than_expected(moves_to_log)
  File "/home/odoo12/odoo/addons/sale_stock/models/stock.py", line 109, in _log_less_quantities_than_expected
    return super(StockPicking, self)._log_less_quantities_than_expected(moves)
  File "/home/odoo12/odoo/addons/stock/models/stock_picking.py", line 966, in _log_less_quantities_than_expected
    self._log_activity(_render_note_exception_quantity, documents)
  File "/home/odoo12/odoo/addons/stock/models/stock_picking.py", line 928, in _log_activity
    'res_model_id': self.env['ir.model'].search([('model', '=', parent._name)], limit=1).id,
  File "<decorator-gen-114>", line 2, in create
  File "/home/odoo12/odoo/odoo/api.py", line 430, in _model_create_single
    return create(self, arg)
  File "/home/odoo12/odoo/addons/mail/models/mail_activity.py", line 275, in create
    activity = super(MailActivity, self.sudo()).create(values_w_defaults)
  File "<decorator-gen-3>", line 2, in create
  File "/home/odoo12/odoo/odoo/api.py", line 451, in _model_create_multi
    return create(self, [arg])
  File "/home/odoo12/odoo/odoo/models.py", line 3551, in create
    self.recompute()
  File "/home/odoo12/odoo/odoo/models.py", line 5200, in recompute
    vals = {n: rec[n] for n in ns}
  File "/home/odoo12/odoo/odoo/models.py", line 5200, in <dictcomp>
    vals = {n: rec[n] for n in ns}
  File "/home/odoo12/odoo/odoo/models.py", line 5047, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/odoo12/odoo/odoo/fields.py", line 974, in __get__
    self.determine_value(record)
  File "/home/odoo12/odoo/odoo/fields.py", line 1061, in determine_value
    self.compute_value(recs)
  File "/home/odoo12/odoo/odoo/fields.py", line 1041, in compute_value
    self._compute_value(records)
  File "/home/odoo12/odoo/odoo/fields.py", line 1032, in _compute_value
    getattr(records, self.compute)()
  File "/home/odoo12/odoo/addons/mail/models/mail_activity.py", line 174, in _compute_res_name
    activity.res_name = self.env[activity.res_model].browse(activity.res_id).name_get()[0][1]
IndexError: list index out of range

**Comment by sswapnesh** [comment] 2018-11-04 10:42
I am not able to Reproduce on latest v12 Runbot. (http://393573-12-0-6c8103.runbot13.odoo.com/web), I am able to Process Picking  "No Backorder" option

**Comment by ccandito** [comment] 2018-11-04 11:29
Dear swapnesh,
Please activate the new version 12 feature related to perform components picking in a manufacturin order.
You can activate it in warehouse settings
Regards
Claudio

**Comment by sle-odoo** [comment] 2019-06-18 13:21
This issue was probably fixed in the meantime since i'm not able to reproduce it.

**Closed by sle-odoo** 2019-06-18 13:21 UTC
Labels: 12.0, Logistics
