### ISSUE TITLE
[11.0] Domain not working for related field

### ISSUE THREAD

**Issue by Gokulakannanaj** [odoo/odoo#34836] opened 2019-07-12 13:16 UTC
Impacted versions:
11.0

Steps to reproduce:
1. Create a One2many(prod.prod) field and set domain to display only active records
2. Create New Model and One2many(related field)

Current behavior:
In Main Model displaying only active records. But In related field, All active and inactive records are displayed.

Expected behavior:
In related One2many table, should display only active records(like Main Model) and here domain is not working

Thank You.

**Comment by pedrobaeza** [comment] 2019-07-12 13:49
This case seems to be happening due to the special field you are handling: `active`. That one is force depending on the context `active_test=False`, so I'm pretty sure the problem is that you are passing that context somehow on the chain. By default, active=False records are not shown in Odoo.

Closing this guessing my hypothesis is true. If not, please comment back.

**Comment by Gokulakannanaj** [comment] 2019-07-12 13:53
Hi @pedrobaeza Thanks, But I'm using isactive not active(special field)

**Comment by pedrobaeza** [comment] 2019-07-12 13:55
But are you putting the same domain on the related field?

**Comment by Gokulakannanaj** [comment] 2019-07-12 13:58
Model 1:(model.model1)

field1 = fields.One2many('model.model', domain=[('isactive', '=', True)])

Model 2: (model.model2)

name = fields.Many2one('model.model1')
field2 = fields.One2many(related='name.field1')

Way 1:
field2 = fields.One2many(related='name.field1')

Way 2:
field2 = fields.One2many(related='name.field1', domain=[('isactive', '=', True)])

In Model 1 --> Active records only displayed but in Model2 Both are displayed

**Comment by pedrobaeza** [comment] 2019-07-12 14:04
And it's not working with way 2?

**Comment by Gokulakannanaj** [comment] 2019-07-12 14:16
Yeah, Way 2 not working.

**Comment by pedrobaeza** [comment] 2019-07-12 14:19
@rco-odoo can you check this?

**Comment by Elkasitu** [comment] 2019-07-15 12:55
It looks very closely related to #23808, I will investigate if it is the case

**Comment by Elkasitu** [comment] 2019-07-16 12:58
Seems like it's not related to the previously referenced issue, it's still a bug however: setting `active` doesn't invalidate the cache's entry for the one2many field (`field2`).

Basically, if you add an inactive record to the one2many, it will display the correct results, however if you add an active record and then make that record inactive, you will have to manually trigger a cache invalidation for it to recalculate the records of the one2many (this is a workaround)

e.g.

```python3
# assume user = res.users(6,)
# assume p1 = res.partner(9,); p2 = res.partner(19,)
# taken from a default odoo install with demo data
p1.field1 = user
p2.field2 = user


assert user.field1 == p1 | p2
# this is true
assert p2.field2 == p1 | p2

p1.active = False
assert user.field1 == p2
# this is false but should be true!
assert p2.field2 == p2

# workaround
p2.invalidate_cache(['field2'])
assert p2.field2 == p2
```

I will try to fix this if it's possible in stable, in the meantime, you can use the workaround

**Comment by pedrobaeza** [comment] 2019-07-16 13:02
@Elkasitu take into account one thing that also confused me: the field is not `active`, but `isactive`. The example given by the reporter is indeed not the best one...

**Comment by Gokulakannanaj** [comment] 2019-07-17 04:42
Thanks for your kind information

**Comment by C3POdoo** [comment] 2023-03-30 11:49
Dear @Gokulakannanaj,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._

**Closed by C3POdoo** 2023-03-30 11:49 UTC
Labels: Framework, 11.0
