### ISSUE TITLE
Email image attachments have wrong content-type

### ISSUE THREAD

**Issue by adaptivdesign** [odoo/odoo#13380] opened 2016-09-02 12:41 UTC
It seems emails send by Odoo have an incorrect content-type for image attachments. This causes problems in outlook.com (and mayby other clients).

Impacted versions:

9.0, Odoo online

Steps to reproduce:
1. Send email with image attachment to a crm lead. 
2. Go to email client.
3. View email source

Current behavior:

Email source shows this:

--===============0400072690820366799==
MIME-Version: 1.0
Content-Type: **application/octet-stream**; name="google-rankbrain.jpg"
Content-Disposition: attachment; filename="google-rankbrain.jpg"
Content-Transfer-Encoding: base64

Expected behavior:

--===============0400072690820366799==
MIME-Version: 1.0
Content-Type: **image/jpeg**; name="google-rankbrain.jpg"
Content-Disposition: attachment; filename="google-rankbrain.jpg"
Content-Transfer-Encoding: base64

**Comment by Yenthe666** [comment] 2016-10-03 08:08
@JKE-be can you have a look at this?

**Comment by JKE-be** [comment] 2016-10-06 08:00
Could you provide your picture: "google-rankbrain.jpg"

Thanks

**Comment by adaptivdesign** [comment] 2016-10-09 23:44
![google-rankbrain](https://cloud.githubusercontent.com/assets/1424733/19224655/99225d2c-8e8a-11e6-97f8-3273798a3c1a.jpg)

Hope this helps. I downloaded the image through Chrome on Ubuntu 16, these are the file properties:

![screenshot from 2016-10-10 01-43-07](https://cloud.githubusercontent.com/assets/1424733/19224673/fe0edd00-8e8a-11e6-82f4-59ec8dc301f9.png)

**Comment by JKE-be** [comment] 2016-11-22 15:57
Sorry, missing your answer...
Do you have always the bug ?

**Comment by JKE-be** [comment] 2016-11-22 16:50
I cannot reproduce...
![image](https://cloud.githubusercontent.com/assets/4848797/20532962/2456edf4-b0dc-11e6-9f1f-b6ec66f6bd29.png)

**Comment by adaptivdesign** [comment] 2016-11-24 12:33
Ok I will try to dig deeper into this, see if I can still produce this.

**Comment by Yenthe666** [comment] 2018-02-14 10:35
Hi there,

I'm closing this bug report as we where unable to reproduce it and as there has been no feedback in over a year now.

Regards,
Yenthe

**Closed by Yenthe666** 2018-02-14 10:35 UTC
