### ISSUE TITLE
[9.0] Cannot include in instance.web.KanbanView

### ISSUE THREAD

**Issue by idncom** [odoo/odoo#15014] opened 2017-01-10 20:12 UTC
Impacted versions: 9.0 Community

Steps to reproduce:
For any module add js to assets like so:
`openerp.some_module = function(instance, local) {
    instance.web.KanbanView.include({});
}`

Current behavior:
The entire kanban view will not load saying some modules cannot be loaded.  The exact same code except changing KanbanView to ListView works as expected.
Expected behavior:
Should allow you to add custom javascript to the kanban view.

Video/Screenshot link (optional):

**Comment by qsm-odoo** [comment] 2017-01-13 16:29
Hello,
It seems like you are using our old javascript system. In 9.0, there is a module system you can find information about here: https://www.odoo.com/documentation/9.0/reference/javascript.html#javascript-module-system-overview

If you want to add some extension to the KanbanView, you should : 
- Create a new JS module
```javascript
odoo.define("myModule.myExtension", function (require) {
    // ... define your extension here ...
});
```
- Inside, you must require the tools you will work with, so for the kanban view:
```javascript
var KanbanView = require("web_kanban.KanbanView");
```
- Then, you can include the kanban view using the require result

Hope this helps.

**Comment by Yenthe666** [comment] 2017-01-16 11:47
Hi @idncom,

Thank you for your report.
As this report is about custom development and it is not a bug in the official code I'm closing this issue.
The answer by @qsm-odoo should fix your issue, you're just using the old JS system.

Regards,
Yenthe

**Closed by Yenthe666** 2017-01-16 11:47 UTC
