### ISSUE TITLE
Odoo Client Error when upgrading the module in odoo13

### ISSUE THREAD

**Issue by GUNALAN952** [odoo/odoo#47552] opened 2020-03-13 05:10 UTC
hi all , when iam trying to update my custom module in odoo 13 , it throwing this error below 

transfers.xml:
<?xml version="1.0" encoding="utf-8"?>
<odoo>

    <record id="transfer_tree" model="ir.ui.view">
        <field name="name">Money.Transfer.tree</field>
        <field name="model">transfers.name</field>
        <field name="type">tree</field>
        <field name="arch" type="xml">
             <tree string ="money_transfers">
                  <field name ="transfers_Name"/>
                  <field name ="transfers_ISO"/>
                  <field name ="transfers_amount"/>
                  <field name ="notes"/>
             </tree>
	</field>
    </record>

    <record id="money_transfer" model="ir.ui.view">
        <field name="name">Money.Transfer.form</field>
        <field name="model">transfers.name</field>
        <field name="type">form</field>
        <field name="arch" type="xml">
            <form string ="money_transfers">
                <sheet>
                    <group>
                        <group>
                            <field name ="transfers_Name"/>
                        </group>
                    	<group>
                            <field name ="transfers_ISO"/>
			</group>
		    </group>
                    <group>
                        <field name ="transfers_amount"/>
                        <field name ="notes"/>
                        <field name ="image"/>
                    </group>
                </sheet>
            </form>
        </field>
    </record>

    <record id="action_transfers" model="ir.actions.act_window">
        <field name="name">Transfers</field>
        <field name="type">ir.actions.act_window</field>
        <field name="res_model">transfers.name</field>
        <field name="view_mode">tree,form</field>
        <field name="help" type="html">
            <p class="o_view_nocontent_smiling_face">
                create your first transfer
            </p>            
        </field>
    </record>
    <menuitem id ="transfers_root" name ="Transfers" sequence ="0" web_icon="transfers,static/description/icon.png" />  
    <menuitem id ="transfers_name" name ="Transfers_Name" parent="transfers_root" action="action_transfers"/> 
</odoo>

transfers.py:

# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

from odoo import models, fields, _

class Transfers(models.Model):
     _name ="transfers.name"
     _description ="Transfer Record"

     transfers_Name = fields.Char(string="Name", required = True)
     transfers_ISO = fields.Char(string="ISO") 
     transfers_amount = fields.Integer("Amount")
     notes = fields.Text(string ="Notes")
     image = fields.Binary(string ="Image")

**Comment by pedrobaeza** [comment] 2020-03-13 07:59
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2020-03-13 07:59 UTC
