### ISSUE TITLE
Odoo Buggy : KeyError:  input_filter = self._input_filters[authorized_fields[field_name]['type']]

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#10931] opened 2016-02-15 13:00 UTC
Getting issue when job online form submitted with date type of field.

Traceback (most recent call last):
  File "/home/7799/source/odoo9c/addons/website/models/ir_http.py", line 242, in _handle_exception
    response = super(ir_http, self)._handle_exception(exception)
  File "/home/7799/source/odoo9c/openerp/addons/base/ir/ir_http.py", line 157, in _handle_exception
    return request._handle_exception(exception)
  File "/home/7799/source/odoo9c/openerp/http.py", line 781, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/home/7799/source/odoo9c/openerp/addons/base/ir/ir_http.py", line 182, in _dispatch
    result = request.dispatch()
  File "/home/7799/source/odoo9c/openerp/http.py", line 840, in dispatch
    r = self._call_function(**self.params)
  File "/home/7799/source/odoo9c/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/7799/source/odoo9c/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/7799/source/odoo9c/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/7799/source/odoo9c/openerp/http.py", line 959, in __call__
    return self.method(*args, **kw)
  File "/home/7799/source/odoo9c/openerp/http.py", line 509, in response_wrap
    response = f(*args, **kw)
  File "/home/7799/source/odoo9c/addons/website_form/controllers/main.py", line 22, in website_form
    data = self.extract_data(model_record, ** kwargs)
  File "/home/7799/source/odoo9c/addons/website_form/controllers/main.py", line 119, in extract_data
    input_filter = self._input_filters[authorized_fields[field_name]['type']]
KeyError: 'date'

**Comment by tejastank** [comment] 2016-02-15 13:01
ON debug only shows...


{'selection': <function identity at 0x7f2132e366e0>, 'text': <function identity at 0x7f2132e366e0>, 'float': <function floating at 0x7f2132e368c0>, 'one2many': <function one2many at 0x7f2132e36a28>, 'char': <function identity at 0x7f2132e366e0>, 'many2many': <function many2many at 0x7f2132e36aa0>, 'boolean': <function boolean at 0x7f2132e36938>, 'many2one': <function integer at 0x7f2132e36848>, 'integer': <function integer at 0x7f2132e36848>, 'datetime': <function identity at 0x7f2132e366e0>, 'binary': <function binary at 0x7f2132e369b0>, 'html': <function identity at 0x7f2132e366e0>} 


Might their framework issue where date missing !

**Comment by tejastank** [comment] 2016-02-15 13:05
File/home/7799/source/odoo9c/addons/website_form/controllers/main.py

Below code fix our issue, might community help this.

                    ftype = authorized_fields[field_name]['type'] if ftype != 'date' else 'datetime'
                    input_filter = self._input_filters[ftype]
                    data['record'][field_name] = input_filter(self, field_name, field_value)

**Comment by dmo-odoo** [comment] 2016-02-19 15:26
Hello,

Could you please provide a step by step instruction so I can reproduce the issue on my side ?

Best regards,
David

**Comment by tejastank** [comment] 2016-02-20 14:05
Example like https://t.co/MJ5NR4cVed, take date then issue raise. we fix this, you might check..

My fix works for my clients and me, you had to fix authorized_fields properly, somewhere form this framework had coded for datetime but not for date.

**Comment by dmo-odoo** [comment] 2016-02-22 09:57
Hello,

The link you gave me doesn't explain how to trigger the issue.
Starting fom the standard HR jobs form, how can I reproduce this bug ?

Best regards,
David

**Comment by tejastank** [comment] 2016-03-08 10:15
+1 Odoo 9.0 Enterprise Edition Bug

**Comment by dmo-odoo** [comment] 2016-03-08 10:35
Hello,

The link you gave me doesn't explain how to trigger the issue.
Starting fom the standard HR jobs form, how can I reproduce this bug ?

Best regards,
Davi

**Comment by Yenthe666** [comment] 2016-06-09 06:44
Since there has been no valid way to explain the bug in several months, while @dmo-odoo asked this multiple times, I'm closing this issue.
If you ever feel like writing down a step by step procedure I'll check it but I bet it has been fixed by now.

**Closed by Yenthe666** 2016-06-09 06:44 UTC
