### ISSUE TITLE
Possible problem/bug with Forecast in Odoo Online ?

### ISSUE THREAD

**Issue by nicolaselbo** [odoo/odoo#14998] opened 2017-01-09 23:42 UTC
Dear,

Impacted versions: 
Odoo online (try for free "edu-")

Steps to reproduce: 
I followed these steps in your documentation: https://www.odoo.com/documentation/user/10.0/project/planning/forecast.html

Expected behavior:
I should be able to edit the "% of time" a user works on a task... (see picture: https://www.odoo.com/documentation/user/10.0/_images/forecast041.png)

Current behavior:
However, I am not able to edit the "% Time"

Video/Screenshot link (optional):
<img width="1440" alt="screen shot 2017-01-10 at 00 40 26" src="https://cloud.githubusercontent.com/assets/6498942/21788189/7e2a7dfc-d6cd-11e6-9324-36c6b4417863.png">

Can someone please tell me what I might have missed?
Thank you for your help.

Kind regards,
Nicolas.

**Comment by Yenthe666** [comment] 2017-01-12 08:26
@mart-e it looks like the documentation is not in sync with the code. Can you verify this?

**Comment by mart-e** [comment] 2017-01-12 09:29
@fgi-odoo is it planned to work on the forecast page? It is a bit outdated.

In v9, you could specify a percentage of working time to compute the planned hours.
In v10, you specify a planned hours to get a percentage of working time.
It was changed at odoo/enterprise@943ea5c0f93c8232dfa4cef9bc739db251888885

@nicolaselbo if you wish to improve the documentation, you can always subit changes at https://github.com/odoo/documentation-user
Thanks

Closing as a problem of documentation but not in the software Odoo (intended behaviour) and even less in the community repository (enterprise app).

**Closed by mart-e** 2017-01-12 09:29 UTC

**Comment by nicolaselbo** [comment] 2017-01-12 18:16
Hello mart-e,

Unfortunately even with "planned hours" filled, the Gantt chart still display "0%" for the time of the employee.

![picture2](https://cloud.githubusercontent.com/assets/6498942/21902210/4ffdc832-d8fb-11e6-8423-e18b02ef97da.png)

![picture1](https://cloud.githubusercontent.com/assets/6498942/21902214/53b7507e-d8fb-11e6-8b15-23efebdbf4c7.png)

It seems to me that the Forecast process is bugged.

Can you please re-open my issue?
Or provide me with the steps I must follow to make it work properly?

Thank you,
Nicolas.

**Comment by mart-e** [comment] 2017-01-13 07:56
Hello,

The computation is done if you have a resource calendar specified on the user.
![screenshot from 2017-01-13 08-54-12](https://cloud.githubusercontent.com/assets/564822/21922249/e451145e-d96d-11e6-97af-1ea4d58a1e31.png)

**Comment by tde-banana-odoo** [comment] 2017-01-13 08:25
I confirm work calendars will be improved in future versions.
