### ISSUE TITLE
odoo12e(runbot)build351550:when install module purchase and stock,it will make some error

### ISSUE THREAD

**Issue by floraXiao** [odoo/odoo#25942] opened 2018-07-24 09:43 UTC
Impacted versions:

Steps to reproduce:
install purchase module.
then install stock module, it will give me an error:
![image](https://user-images.githubusercontent.com/13793204/43130217-c7805a62-8f68-11e8-9a80-90ad555a93c7.png)
last, I install stock module again, it success.But, when I click on the product menu, it pop up an error:
![image](https://user-images.githubusercontent.com/13793204/43130332-0f9aa942-8f69-11e8-9bcb-3e07988a5801.png)
 
Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment] 2018-07-25 08:29
Hi @floraXiao,

Thanks a lot for the report. I assume it is for Odoo 11?
@mart-e this seems to be language related judging by the `ValueError` in the traceback.

**Comment by mart-e** [comment] 2018-07-25 08:33
Seeing the traceback I would say is master.
@floraXiao Please give exact steps to reproduce your problem it on a stable version. If you have changed some settings (like changed the language) please explain.

**Comment by floraXiao** [comment] 2018-07-25 09:53
Hi @mart-e ,
yes, the version is odoo 12(master), I reproduce the problem just now.  the build number is 351851. Firstly, I load Chinese translation and change the language to Chinese because I am Chinese. Then I install purchase module and stock module, I meet an error like I said. I guess something went wrong with the module purchase_stock.
![image](https://user-images.githubusercontent.com/13793204/43193829-94a2cc9e-9033-11e8-873b-104cc27668fd.png)

**Comment by mart-e** [comment] 2018-07-26 14:37
Thank you for the report. I confirm the bug, it was fixed in saas-11.4 at 424e50121b5, it will soon be ported to master.
Please keep in mind that the master is not a stable branch, things _will_ be broken. No need to report issues for this branch.
Thank you to report issues on the stable branches instead.

**Closed by mart-e** 2018-07-26 14:37 UTC
Labels: Internationalization

**Comment by floraXiao** [comment] 2018-07-27 03:00
Thanks a lot, the problem is fixed.
