### ISSUE TITLE
Bug in arabic days in datepicker

### ISSUE THREAD

**Issue by Mraimou** [odoo/odoo#19320] opened 2017-09-07 10:49 UTC
Impacted versions:10

Steps to reproduce:
change the langage to arabic and pick a date

Current behavior:
Translated dates in arabic are not coherent with the numbers in the calendar 
for example we find 
ر/شتنبر -->septembre - 4 
![bug_date](https://user-images.githubusercontent.com/16048627/30159797-d63020cc-93c1-11e7-97d2-2677e07192a5.PNG)
Expected behavior:

ن/شتنبر -->septembre - 4

**Comment by Mraimou** [comment] 2017-09-07 11:39
I changed this code in lib\moment\locale\ar-ma.js
```
  week : {
            dow : 6, // Saturday is the first day of the week.
            doy : 12  // The week that contains Jan 1st is the first week of the year.
        }
```
to this 
```
week : {
            dow : 1, // Monday is the first day of the week.
            doy : 12  // The week that contains Jan 1st is the first week of the year.
        }
```
here is the result:
![bug_fixed_date](https://user-images.githubusercontent.com/16048627/30161653-6a7e7d8a-93c9-11e7-86fd-b779f2f319b4.PNG)

Is this the right solution ?

**Comment by Yenthe666** [comment] 2017-09-07 18:29
@mart-e this one is for you as it is lang / calendar related.

**Comment by mart-e** [comment] 2017-11-06 12:33
Hello,

Sorry but I am not sure to understand the issue.
Do you disagree on the first day of the week specified for Arabic language?
Because we did not implemented that part, we use moment.js library and it is specified there
https://github.com/moment/moment/blob/develop/locale/ar-ma.js

You can report there the problem so they correct it.

**Comment by Mraimou** [comment] 2017-11-07 10:19
Hi, 
The first day of the week is Monday in Morocco, so the problem is in moment.js library.

**Comment by mart-e** [comment] 2017-11-07 10:52
Thanks for the answer.
Closing as the issue is to report upstream.
Don't hesitate to let us know when you have an answer from moment.js if we need to update our locales.

**Closed by mart-e** 2017-11-07 10:52 UTC
Labels: need information
