### ISSUE TITLE
[Odoo 10.0] User with [Inventory/Manager] access rights cannot validate internal transfer 

### ISSUE THREAD

**Issue by femioz** [odoo/odoo#18669] opened 2017-08-03 22:50 UTC
Impacted versions:
10.0
Steps to reproduce:

1. Installed Inventory module.. 

2. Configured 4 warhouses and locations 

3. Configured Routes so that there is one step in between internal transfers using a transit location. 

4. Installed Warehouse restrict module from Odoo app market place.. (Everything looks fine) https://apps.odoo.com/apps/modules/10.0/warehouse_stock_restrictions/ 

5. Configure regular user for initial inventory and validation (All works well with policies in place) 

6. Configure other user with manager rights. (Error here)

Current behavior:

When I click on the Validate button I get the following Error 

Odoo Warning - 

Access Error The requested operation cannot be completed due to security restrictions. Please contact your system administrator. (Document type: stock.picking.type, Operation: read) 

Expected behavior:

When I click on validate I expect no error

Video/Screenshot link (optional):
<img width="1670" alt="2017-08-03 10 39 00 pm" src="https://user-images.githubusercontent.com/28513058/28947189-7e4857c0-78a6-11e7-9a7b-7171e7a37a5c.png">

**Comment by yostashiro** [comment] 2017-08-06 01:16
@femioz I suggest you report the issue to the module author and not here if the behavior is caused by the 3rd party module.

**Comment by Yenthe666** [comment] 2017-08-07 06:32
Hi @femioz,

Thank you for your report. Can you reproduce this on a runbot (runbot.odoo.com)? I tried this on a V10 (without the third party app) but didn't seem to find an issue. Please try this on a runbot and if you can reproduce it then do let me know. It looks like an issue from the third party app to me.

**Comment by femioz** [comment] 2017-08-08 01:20
Thank you both for your response. Will try and reproduce on runbot and see how that goes.

**Comment by Yenthe666** [comment] 2017-12-28 09:38
@femioz any update?

**Comment by sle-odoo** [comment] 2018-02-06 20:58
Hi,
This was fixed in the meantime, it was a related not set as readonly in the view. I cannot find back the commit though :/

If you're still facing the issue, feel free to comment and i'll reopen.

Regards

**Closed by sle-odoo** 2018-02-06 20:58 UTC
Labels: 10.0, Logistics

**Comment by noellalaina** [comment] 2018-07-27 05:43
Hi,
What is your solution because I have same issue ?

Thanks
