### ISSUE TITLE
menuitem issues

### ISSUE THREAD

**Issue by montaab1** [odoo/odoo#48553] opened 2020-03-29 22:58 UTC
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7fddf55cc9d8>, 'base.menu_opentt_maintenance_root ')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/tools/convert.py", line 713, in parse
    self._tag_root(de)
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/tools/convert.py", line 675, in _tag_root
    f(rec)
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/tools/convert.py", line 675, in _tag_root
    f(rec)
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/tools/convert.py", line 443, in _tag_menuitem
    values['parent_id'] = self.id_get(rec.attrib['parent'])
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/tools/convert.py", line 658, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/tools/convert.py", line 664, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/addons/base/models/ir_model.py", line 1657, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-24>", line 2, in xmlid_lookup
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/addons/base/models/ir_model.py", line 1646, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: base.menu_opentt_maintenance_root 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/http.py", line 910, in __call__
    return self.method(*args, **kw)
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/addons/web/controllers/main.py", line 1324, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/addons/web/controllers/main.py", line 1312, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/api.py", line 395, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/api.py", line 382, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-58>", line 2, in button_immediate_install
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/addons/base/models/ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/addons/base/models/ir_module.py", line 463, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/addons/base/models/ir_module.py", line 573, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/modules/loading.py", line 420, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/modules/loading.py", line 312, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/tools/convert.py", line 737, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/tools/convert.py", line 804, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/tools/convert.py", line 722, in parse
    exc_info[2]
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/tools/pycompat.py", line 13, in reraise
    raise value.with_traceback(tb)
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/tools/convert.py", line 713, in parse
    self._tag_root(de)
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/tools/convert.py", line 675, in _tag_root
    f(rec)
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/tools/convert.py", line 675, in _tag_root
    f(rec)
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/tools/convert.py", line 443, in _tag_menuitem
    values['parent_id'] = self.id_get(rec.attrib['parent'])
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/tools/convert.py", line 658, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/tools/convert.py", line 664, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/addons/base/models/ir_model.py", line 1657, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-24>", line 2, in xmlid_lookup
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/odoo/addons/base/models/ir_model.py", line 1646, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
odoo.tools.convert.ParseError: "External ID not found in the system: base.menu_opentt_maintenance_root " while parsing /home/montassar/PyCharmProjects/odoo-13-opentt-cmms-test/custom_addons/maintenance_opentt/views/mro_view.xml:2, near
<odoo>
	<data>

        
        <menuitem name="Maintenance OpenTT" id="base.menu_opentt_maintenance_root" sequence="80"/>

        
        <menuitem name="Maintenance" id="menu_mro_maintenance" parent="base.menu_opentt_maintenance_root" sequence="1"/>

        
        <record id="mro_request_tree_view" model="ir.ui.view">
            <field name="name">mro.request.tree</field>
            <field name="model">mro.request</field>
            <field name="arch" type="xml">
                <tree string="Maintenance Requests">
                    <field name="message_unread" invisible="1"/>
                    <field name="name"/>
                    <field name="execution_date" string="Date"/>
                    <field name="asset_id"/>
                    <field name="cause"/>
                    <field name="state"/>
                </tree>
            </field>
        </record>

        <record id="mro_request_form_view" model="ir.ui.view">
            <field name="name">mro.request.form</field>
            <field name="model">mro.request</field>
            <field name="arch" type="xml">
                <form string="Maintenance Request" version="7.0">
                    <header>
                        <button name="action_send" states="draft" string="Send Request" type="object" class="oe_highlight"/>
                        <button name="action_confirm" states="claim" string="Confirm Request" type="object" class="oe_highlight" groups="assets_opentt.group_opentt_maintenance_user"/>
                        <button name="%(action_request_reject)d" states="claim" string="Reject Request" type="action" groups="assets_opentt.group_opentt_maintenance_user"/>
                        <button name="action_cancel" states="draft" string="Cancel" type="object"/>
                        <field name="state" widget="statusbar" statusbar_visible="draft,claim,run,done"/>
                    </header>
                    <sheet>
                        <div class="oe_title">
                            <h1>Maintenance Request <field name="name" class="oe_inline" readonly="1"/></h1>
                        </div>
                        <group>
                            <group>
                                <field name="asset_id"/>
                                <field name="cause"/>
                                <field name="breakdown"/>
                            </group>
                            <group>
                                <field name="requested_date" attrs="{'invisible':[('breakdown','=',True),('state','=','draft')],'readonly':[('state','!=','draft')]}"/>
                                <field name="execution_date"/>
                            </group>
                        </group>
                        <group string="Reject Reason" states="reject">
                            <field name="reject_reason" colspan="4" nolabel="1"/>
                        </group>
                        <group string="Description">
                            <field name="description" colspan="4" nolabel="1"/>
                        </group>
                    </sheet>
                    <div class="oe_chatter">
                        <field name="message_follower_ids" widget="mail_followers"/>
                        <field name="message_ids" widget="mail_thread"/>
                    </div>
                </form>
            </field>
        </record>

        <record id="mro_request_search" model="ir.ui.view">
            <field name="name">mro.request.search</field>
            <field name="model">mro.request</field>
            <field name="arch" type="xml">
                <search string="Search Maintenance Request">
                    <field name="state"/>
                    <field name="name"/>
                    <field name="asset_id"/>
                    <filter icon="terp-mail-message-new" string="Unread Messages" name="message_unread" domain="[('message_unread','=',True)]"/>
                    <separator/>
                    <filter icon="terp-document-new" name="open" string="Open" domain="['|',('state','in',('draft','claim')),('message_unread','=',True)]" help="Undecided maintenance request"/>
                    <group expand="0" string="Group By">
                      <filter name="group_state" string="State" context="{'group_by': 'state'}"/>
                    </group>
                </search>
            </field>
        </record>

        <record id="action_requests" model="ir.actions.act_window">
            <field name="name">Maintenance Requests</field>

            <field name="res_model">mro.request</field>

            <field name="view_mode">tree,form</field>
            <field name="context">{'search_default_open': 1}</field>
        </record>

        <menuitem name="Maintenance Requests" action="action_requests" id="menu_mro_request" parent="menu_mro_maintenance" sequence="1"/>

        
        <record id="mro_order_tree_view" model="ir.ui.view">
            <field name="name">mro.order.tree</field>
            <field name="model">mro.order</field>
            <field name="arch" type="xml">
                <tree string="Maintenance Orders">
                    <field name="message_unread" invisible="1"/>
                    <field name="name"/>
                    <field name="date_execution" string="Order Date" widget="date"/>
                    <field name="asset_id"/>
                    <field name="maintenance_type"/>
                    <field name="description"/>
                    <field name="origin"/>
                    <field name="state"/>
                </tree>
            </field>
        </record>

        <record id="mro_order_calendar_view" model="ir.ui.view">
            <field name="name">mro.order.calendar</field>
            <field name="model">mro.order</field>
            <field name="arch" type="xml">
                <calendar color="asset_id" date_start="date_execution" string="Maintenance Orders">
                    <field name="name"/>
                    <field name="description"/>
                </calendar>
            </field>
        </record>

        <record id="mro_order_form_view" model="ir.ui.view">
            <field name="name">mro.order.form</field>
            <field name="model">mro.order</field>
            <field name="arch" type="xml">
                <form string="Maintenance Orders" version="7.0">
                    <header>
                        <button name="action_confirm" states="draft" string="Confirm Maintenance" type="object" class="oe_highlight"/>
                        <button name="action_done" states="ready" string="Done" type="object" class="oe_highlight"/>
                        <button name="force_done" states="released" string="Done" type="object" class="oe_highlight"/>
                        <button name="force_parts_reservation" states="released" string="Force Reservation" type="object"/>
                        <button name="button_recreate_picking_parts" states="parts_except" string="Recreate Picking" type="object" class="oe_highlight"/>
                        <button name="action_cancel" type="object" states="draft,ready,parts_except" string="Cancel"/>
                        <button name="action_cancel" type="object" states="released" string="Cancel"/>
                        <field name="state" widget="statusbar" statusbar_visible="draft,ready,done" statusbar_colors="{&quot;parts_except&quot;:&quot;red&quot;,&quot;released&quot;:&quot;blue&quot;}"/>
                    </header>
                    <sheet>
                        <div class="oe_title">
                            <h1>Maintenance Order <field name="name" class="oe_inline" readonly="1"/></h1>
                        </div>
                        <group>
                            <group>
                                <field name="asset_id"/>
                                <field name="category_ids" invisible="1"/>
                                <field name="maintenance_type"/>
                                <label for="task_id" attrs="{'invisible':[('maintenance_type','=','bm')]}"/>
                                <div attrs="{'invisible':[('maintenance_type','=','bm')]}">
                                    <field name="task_id" attrs="{'required':[('maintenance_type','!=','bm')]}"/>
                                </div>
                                <field name="description"/>
                            </group>
                            <group>
                                <field name="date_planned"/>
                                <field name="date_scheduled"/>
                                <field name="date_execution"/>
                                <field name="user_id"/>
                                <field name="origin"/>
                            </group>
                            <group groups="stock.group_locations">

                            </group>
                            <group>
                                <field name="company_id" groups="base.group_multi_company" widget="selection"/>
                            </group>
                        </group>
                        <notebook>
                            <page string="Parts">
                                    <group string="Planned Parts" states="draft,released,done,parts_except,cancel">
                                        <field name="parts_lines" nolabel="1" context="{'default_categ_id': context.get('default_categ_id')}">
                                            <tree string="Planned Parts" editable="bottom">
                                                <field name="parts_id" domain="[('isParts','=',True)]" context="{'default_categ_id': context.get('default_categ_id')}"/>
                                                <field name="parts_qty"/>
                                                <field name="parts_uom" groups="uom.group_uom"/>
                                                <field name="name"/>
                                            </tree>
                                        </field>
                                    </group>

                            </page>
                            <page string="Tools">
                                <separator string="Description for Tools"/>
                                <field name="tools_description" placeholder="Specify the tools and mechanisms needed for execute this order..."/>
                            </page>
                            <page string="Labor">
                                <separator string="Description for Labor"/>
                                <field name="labor_description" placeholder="Specify the specialists needed for execute this order..."/>
                            </page>
                            <page string="Operations">
                                <separator string="Description for Operations"/>
                                <field name="operations_description" placeholder="Specify the jobs that need execute..."/>
                            </page>
                            <page string="Documentation">
                                <separator string="Description for Documentation"/>
                                <field name="documentation_description" placeholder="Specify the documentation useful when execute this order..."/>
                            </page>
                        </notebook>
                        <group string="Problem Description">
                            <field name="problem_description" colspan="4" nolabel="1"/>
                        </group>
                    </sheet>
                    <div class="oe_chatter">
                        <field name="message_follower_ids" widget="mail_followers"/>
                        <field name="message_ids" widget="mail_thread"/>
                    </div>
                </form>
            </field>
        </record>

        <record id="mro_order_search" model="ir.ui.view">
            <field name="name">mro.order.search</field>
            <field name="model">mro.order</field>
            <field name="arch" type="xml">
                <search string="Search Maintenance Order">
                    <field name="name"/>
                    <field name="maintenance_type"/>
                    <field name="asset_id"/>
                    <field name="category_ids"/>
                    <filter icon="terp-mail-message-new" string="Unread Messages" name="message_unread" domain="[('message_unread','=',True)]"/>
                    <separator/>
                    <group expand="0" string="Group By">
                      <filter name="group_state" string="State" context="{'group_by': 'state'}"/>
                      <filter name="group_type" string="Maintenance Type" context="{'group_by': 'maintenance_type'}"/>
                      <filter name="group_asset" string="Asset" context="{'group_by': 'asset_id'}"/>
                      <filter name="group_date_scheduled" string="Scheduled Date" context="{'group_by': 'date_scheduled'}"/>
                      <filter name="group_date_execution" string="Execution Date" context="{'group_by': 'date_execution'}"/>
                    </group>
                </search>
            </field>
        </record>

        <record id="action_orders" model="ir.actions.act_window">
            <field name="name">Maintenance Orders</field>

            <field name="res_model">mro.order</field>

            <field name="view_mode">tree,form,calendar</field>
            <field name="context" eval="{'default_categ_id': ref('maintenance_opentt.product_category_mro')}"/>
        </record>

        <menuitem name="Maintenance Orders" action="action_orders" id="menu_mro_order" parent="menu_mro_maintenance" sequence="10"/>

        
        <menuitem name="Parts" id="menu_maintenance_parts" parent="base.menu_opentt_maintenance_root " groups="assets_opentt.group_opentt_maintenance_user" sequence="9"/>

        <record id="part_search_form_view" model="ir.ui.view">
            <field name="name">product.template.search.mro</field>
            <field name="model">product.template</field>
            <field name="mode">primary</field>
            <field name="inherit_id" ref="product.product_template_search_view"/>
            <field name="arch" type="xml">
                <filter name="services" position="before">
                    <filter string="Parts" name="parts" domain="[('isParts','=',True)]" help="Parts your store in the inventory"/>
                </filter>
            </field>
        </record>

        <record id="part_action" model="ir.actions.act_window">
            <field name="name">Part</field>
            <field name="res_model">product.template</field>
            <field name="view_mode">tree,form,kanban</field>

            <field name="search_view_id" ref="part_search_form_view"/>
            <field name="context" eval="{'default_categ_id': ref('maintenance_opentt.product_category_mro'), 'default_isParts': True, 'search_default_parts':1}"/>
            <field name="help" type="html">
              <p class="oe_view_nocontent_create">
                Click to define a new spare part.
              </p>
            </field>
        </record>

        <menuitem name="Parts" action="part_action" id="menu_maintenance_parts_parts" parent="menu_maintenance_parts" sequence="100"/>

        
        <record id="mro_task_tree_view" model="ir.ui.view">
            <field name="name">mro.task.tree</field>
            <field name="model">mro.task</field>
            <field name="arch" type="xml">
                <tree string="Maintenance Tasks">
                    <field name="category_id"/>
                    <field name="name"/>
                    <field name="maintenance_type"/>
                </tree>
            </field>
        </record>

        <record id="mro_task_form_view" model="ir.ui.view">
            <field name="name">mro.task.form</field>
            <field name="model">mro.task</field>
            <field name="arch" type="xml">
                <form string="Tasks" version="7.0">
                <header>
                </header>
                <sheet>
                    <div class="oe_title">
                        <h1>Task Name <field name="name" class="oe_inline"/></h1>
                    </div>
                    <group>
                        <field name="category_id"/>
                        <field name="maintenance_type"/>
                        <field name="active"/>
                    </group>
                    <notebook>
                        <page string="Parts">
                            <field name="parts_lines" nolabel="1" context="{'default_categ_id': context.get('default_categ_id')}">
                                <tree string="Parts" editable="bottom">
                                    <field name="parts_id" domain="[('isParts','=','True')]" context="{'default_categ_id': context.get('default_categ_id')}"/>
                                    <field name="parts_qty"/>
                                    <field name="parts_uom" groups="uom.group_uom"/>
                                    <field name="name"/>
                                </tree>
                            </field>
                        </page>
                        <page string="Tools">
                            <separator string="Description for Tools"/>
                            <field name="tools_description" placeholder="Specify the tools and mechanisms needed for execute this order..."/>
                        </page>
                        <page string="Labor">
                            <separator string="Description for Labor"/>
                            <field name="labor_description" placeholder="Specify the specialists needed for execute this order..."/>
                        </page>
                        <page string="Operations">
                            <separator string="Description for Operations"/>
                            <field name="operations_description" placeholder="Specify the jobs that need execute..."/>
                        </page>
                        <page string="Documentation">
                            <separator string="Description for Documentation"/>
                            <field name="documentation_description" placeholder="Specify the documentation useful when execute this order..."/>
                        </page>
                    </notebook>
                </sheet>
                </form>
            </field>
        </record>

        <record id="action_tasks" model="ir.actions.act_window">
            <field name="name">Maintenance Tasks</field>

            <field name="res_model">mro.task</field>

            <field name="view_mode">tree,form</field>
            <field name="context" eval="{'default_categ_id': ref('maintenance_opentt.product_category_mro')}"/>
        </record>

        <menuitem name="Tasks" id="menu_maintenance_tasks" parent="base.menu_opentt_maintenance_root" sequence="9"/>

        <menuitem name="Tasks" action="action_tasks" id="menu_maintenance_tasks_tasks" parent="menu_maintenance_tasks" sequence="100"/>

 	</data>
</odoo>

**Comment by pedrobaeza** [comment] 2020-03-29 23:40
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2020-03-29 23:40 UTC
