### ISSUE TITLE
[13.0] Error 500 bank transfer payment method e-commerce & PayPal render error

### ISSUE THREAD

**Issue by tsteenbergen96** [odoo/odoo#40912] opened 2019-11-26 20:39 UTC
Impacted versions:
13.0
Steps to reproduce
**Bank transfer error:**
- add something to basket
- go to the last page of the checkout
- select option 'bank transfer'
- complete order and error 500 occurs
YouTube link:
https://youtu.be/pWLx69CeAX4

**PayPal error**
- add something to basket
- go to the last page of the checkout
- select option 'PayPal'
- do payment successful through paypal
- when PayPal send you back to Odoo an render error appears 
YouTube link:
https://youtu.be/dtC75TDXnmo

**Comment by pedrobaeza** [comment] 2019-11-27 00:54
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Feyensv** [comment] 2019-11-27 12:27
Is maybe related and fixed by https://github.com/odoo/odoo/pull/39408

**Comment by tsteenbergen96** [comment] 2019-12-02 16:58
> Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?
> 
> If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.
> 
> If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.
> 
> For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

Hi, sorry for my late reply. But on, I am not able to reproduce the problem there because I don't know how the Runbot works. If you can explain it to me then I give it a try, otherwise I can make some more videos and upload it to YouTube. By the way, I updated the code from #39408 but doesn't make any sense... :(

**Comment by Yenthe666** [comment] 2020-03-08 19:25
@tsteenbergen96 go to runbot.odoo.com, take the latest 13.0 build and login with the username "admin" and the password "admin"

**Comment by pedrobaeza** [comment] 2020-05-08 19:54
Closing as no more answer.

**Closed by pedrobaeza** 2020-05-08 19:54 UTC
Labels: Need information, Sales
