### ISSUE TITLE
[Odoo] Issue of negative search on many2many fields

### ISSUE THREAD

**Issue by gan-odoo** [odoo/odoo#4613] opened 2015-01-09 12:36 UTC
Reproduce in 8.0 and Master

Step to reproduce
1) Open sales -> customers
2) Go to advance search
3) Negative search : many2many field - doesn't contain - value
          like : tags - doesn't contain - IT Services

Demo : https://www.youtube.com/watch?v=jkjEkmC44kM

**Comment by xmo-odoo** [comment] 2015-01-12 13:02
Duplicate of #4489 I think, reopen if it isn't.

**Closed by xmo-odoo** 2015-01-12 13:02 UTC
