### ISSUE TITLE
Widget handle increment

### ISSUE THREAD

**Issue by ltduc** [odoo/odoo#32271] opened 2019-03-30 05:05 UTC
Impacted versions:
Odoo - 12

Steps to reproduce:
Sequence field, widget="handel" and _order = "sequence" added

Current behavior:
When drag and drop default behavior, Sequence field will increment 1
Ex: Sequences is 1,2,3,4...

Expected behavior:
When drag and drop default behavior, Sequence field will increment 10.
Ex: Sequences is 10, 20, 30, 40

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment] 2019-03-30 08:56
> Sequence field will increment 10.
> Ex: Sequences is 10, 20, 30, 40

What is the reason for making this as `Expected behavior` ?

**Comment by ltduc** [comment] 2019-03-30 09:06
Hi, Sswapnesh!

Because, my grid page size than 100, i want type sequence field  to orderd when i need, to quick than drag & drop

Please, help for me!

Thanks!

**Comment by pedrobaeza** [comment] 2019-03-30 21:53
Sorry, but the default behavior increasing one is valid. If you need another size, you should customize the JS part.

Closing as no real issue.

**Closed by pedrobaeza** 2019-03-30 21:53 UTC
