### ISSUE TITLE
 Create new custom field type Odoo

### ISSUE THREAD

**Issue by girishghoda** [odoo/odoo#30796] opened 2019-02-04 09:46 UTC
Impacted versions:
Odoo 11
Steps to reproduce:

Current behavior:

Expected behavior:
I want to create custom field type with use of existing field type.Just like Odoo have field types: Char,Integer etc.I want create new Integer type with use of existing Integer field type. So new custom field type has existing and new functionality.

Odoo allow create custom field type? If yes then how to create custom field type?

I guess that inherit existing field type we can create custom field type just like we create custom module with use of inherit existing model.

Thank you
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment] 2019-02-04 09:48
Hi there,

I'm closing this as it is not a bug or issue. The Github tracker is only for issues or bugs.
I see you've already asked it on the official help forums (https://www.odoo.com/forum/help-1/question/create-new-custom-field-type-odoo-145249) so I'm sure you'll get feedback soon. It is in fact possible.

Regards,
Yenthe

**Closed by Yenthe666** 2019-02-04 09:48 UTC

**Comment by girishghoda** [comment] 2019-02-04 09:52
Sorry for posted here but we want it fast so if you do some help here very thank full. Any hint or resource link.

**Comment by Yenthe666** [comment] 2019-02-04 12:31
Done on the forum.
