### ISSUE TITLE
[9.0E] Flanker not found, missing Python library in requirements

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#11870] opened 2016-04-30 12:09 UTC
Impacted versions: 9.0 Enterprise

Steps to reproduce: Install a new Odoo V9 Enterprise and install the module `website_crm_score`.
Check the logfile afterwards:
`2016-04-30 11:06:53,802 2605 WARNING ? openerp.addons.website_crm_score.models.sales_team: flanker not found, email validation disabled.`

Current behavior:
Warnings in the Odoo logfile when Flanker is not installed

Expected behavior:
Flanker should be either added as a requirement on `requirements.txt` or it should be automatically installed on the system when you install the module `website_crm_score`?
Either way, there is no way for the system administrator to know that this Python package should be installed and it is not mentioned anywhere.

**Comment by Yenthe666** [comment] 2016-05-02 08:29
@mart-e I think you might know this. Is it by purpose not in the `requirements.txt` since it is only used in enterprise or?

**Comment by mart-e** [comment] 2016-05-02 08:42
This is not an mandatory dependency, the module will still work without this, just the verification of email addresses that will not be present.
We have a few of those, as it is very specific (webiste_crm_score is quite advanced, requires complex configuration), we don't want to impose it to everyone.

So no, I don't think it should go in requirement.
We could add information about this in the description of the module though.

**Comment by Yenthe666** [comment] 2016-05-02 08:50
Alright so it does make sense that it is not a requirement but, honestly, without opening the logfiles you would never know you'd need it.
I think it would be a good idea to add it in the description of the module and also on the documentation later on.
Perhaps a little warning could be thrown up in Odoo too? On the moment you install the module or something. Just a simple dialog.

**Comment by mart-e** [comment] 2016-05-02 08:54
PR welcome :wink: 
I am not fan of popup warning (because people seeing the popup are probably not necessary the people that can do something about the problem) but sure, we can put it in the description of the module.

**Comment by JKE-be** [comment] 2016-05-10 18:52
duplicate of https://github.com/odoo/odoo/issues/11840

**Closed by JKE-be** 2016-05-10 18:52 UTC

**Comment by JKE-be** [comment] 2016-07-07 22:32
Fixed in https://github.com/odoo/enterprise/commit/a7a61dcc9d07a65bd0bc41d5c555977e051b3cd3
