### ISSUE TITLE
Odoo 9.0 Enterprise Edition Bug.

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#9263] opened 2015-10-27 08:37 UTC
Error Detected with Enterprise Edition issues, 

Start once worked, bug again it raise issue when start with debug mode.

fabia@forked-desktop:~/source/odoo9e$ python odoo.py -c odoo9.conf -s --addons-path openerp/addons/
2015-10-27 08:32:50,865 13952 INFO ? openerp: OpenERP version 9.0-20151025
2015-10-27 08:32:50,865 13952 INFO ? openerp: addons paths: ['/home/fabia/.local/share/Odoo/addons/9.0', u'/home/fabia/source/odoo9e/openerp/addons']
2015-10-27 08:32:50,865 13952 INFO ? openerp: database: fabia@default:default
2015-10-27 08:32:50,976 13952 INFO ? openerp.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
2015-10-27 08:32:59,039 13952 INFO ? openerp.addons.bus.models.bus: Bus.loop listen imbus on db postgres
2015-10-27 08:32:59,325 13952 INFO ? openerp.addons.report.models.report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
2015-10-27 08:32:59,432 13952 WARNING ? openerp.addons.website_crm_score.models.sales_team: flanker not found, email validation disabled.
2015-10-27 08:32:59,455 13952 INFO ? werkzeug: 127.0.0.1 - - [27/Oct/2015 08:32:59] "GET / HTTP/1.1" 500 -
2015-10-27 08:32:59,457 13952 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/share/pyshared/werkzeug/serving.py", line 159, in run_wsgi
    execute(app)
  File "/usr/share/pyshared/werkzeug/serving.py", line 146, in execute
    application_iter = app(environ, start_response)
  File "/home/fabia/source/odoo9e/openerp/service/server.py", line 245, in app
    return self.app(e, s)
  File "/home/fabia/source/odoo9e/openerp/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/home/fabia/source/odoo9e/openerp/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/home/fabia/source/odoo9e/openerp/http.py", line 1415, in __call__
    self.load_addons()
  File "/home/fabia/source/odoo9e/openerp/http.py", line 1436, in load_addons
    m = __import__('openerp.addons.' + module)
  File "/home/fabia/source/odoo9e/openerp/modules/module.py", line 61, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/home/fabia/source/odoo9e/openerp/addons/website_less/__init__.py", line 1, in <module>
    import ir_qweb
  File "/home/fabia/source/odoo9e/openerp/addons/website_less/ir_qweb.py", line 276, in <module>
    class SassAsset(StylesheetAsset, openerp.addons.base.ir.ir_qweb.SassAsset):
AttributeError: 'module' object has no attribute 'SassAsset'

**Comment by tejastank** [comment] 2015-10-27 08:39
Fixed.

**Comment by tejastank** [comment] 2015-10-27 08:56
Again getting same issue with other resetup of database...

**Comment by tejastank** [comment] 2015-10-27 09:09
class SassAsset(StylesheetAsset, openerp.addons.base.ir.ir_qweb.SassAsset):
AttributeError: 'module' object has no attribute 'SassAsset'

Even with community edition of 9.0 same issue

**Comment by sle-odoo** [comment] 2016-06-08 11:48
Closing as i cannot reproduce.
Feel free to comment with a clear way to reproduce this issue if you are still facing it.
Regards.

**Closed by sle-odoo** 2016-06-08 11:48 UTC
