### ISSUE TITLE
Can't create website in multi-company

### ISSUE THREAD

**Issue by edy1192** [odoo/odoo#69499] opened 2021-04-19 16:05 UTC
Impacted versions:
13.
Steps to reproduce:

- Multi company (Company A, Company B).
- Company A: Create website and set sale team Website (sales_team.salesteam_website_sales)
- Company B: Create Website

Current behavior:

Got a security error.
The requested operation ("read" on "Sales Team" (crm.team)) was rejected because of the following rules:
- Sales Team multi-company
Note: this might be a multi-company issue.
(Records: Website (id=2), User: Mitchell Admin (id=2))

Expected behavior:
Create Website for Company B.

Video/Screenshot link (optional):

https://youtu.be/-AQeMpOizxw

runbot v13: https://7254953-13-0-all.runbot56.odoo.com/

Support ticket number submitted via odoo.com/help (optional):

#2511130

**Comment by edy1192** [comment] 2021-04-19 18:53
Hi @pedrobaeza 

No, I am using the Website sales team for the company A website.

When creating the website of company B, it fails because it tries to assign the sales team of company A.

https://github.com/odoo/odoo/blob/13.0/addons/website_sale/models/website.py#L25

cc @moylop260

**Comment by moylop260** [comment] 2021-04-20 00:49
@mart-e @nim-odoo 

I think it is an issue related with default values for multi-company rules:
 - https://github.com/odoo/odoo/blob/a7bce66f3e6124ec572f86bc22c7d11c73df378d/addons/website_sale/models/website.py#L25

I mean, the original record with xml_id was assigned for another company but new ones will try to use it by default even if it doesn't have access because multi-compnay ir.rules

What is the best fix for you in these kind of cases?

**Comment by pedrobaeza** [comment] 2021-04-20 06:23
But by default the sales team doesn't have company:

https://github.com/odoo/odoo/blob/a7bce66f3e6124ec572f86bc22c7d11c73df378d/addons/sales_team/data/sales_team_data.xml#L13

so in which moment the sales team have become of only one company and thus raise the error?

**Comment by mart-e** [comment] 2021-04-20 08:07
Are you sure this runbot "fresh start" ? As said Pedro, there is no comparny on the saleteam for that reason. I just tested locally and had no issue.
Could you check again, maybe on a local install to be sure you are the only one modifying this db?

**Comment by mart-e** [comment] 2021-04-20 08:14
I just realised the runbot is still alive so I checked and yep, the sale team is set to a specifc company so obviously only people in this company can use it.

![Screenshot_2021-04-20 New - Odoo](https://user-images.githubusercontent.com/564822/115361341-c7094b80-a1c0-11eb-8421-75dc6fc81704.png)

I let @JKE-be stop me if I am wrong but you should create another team if you want to have one that is company specific

**Comment by JKE-be** [comment] 2021-04-20 08:21
On Last v13 Runbot, you don't have any copany_id set by default.
So as "reported" by pedro, the problem is more a question of configuration.
![image](https://user-images.githubusercontent.com/4848797/115362452-d50b9c00-a1c1-11eb-9ff3-3ffb9f78dbd7.png)

But yes, we could at least add a check in `_get_default_website_team` that company match or use False as default... since this field is not required. But it will not avoid the same crash if after create your second website, you change the company_id on the saleteam.

**Comment by mart-e** [comment] 2021-04-20 08:56
Closing as to be solved with a change of configuration.
We could improve this and be a bit more tolerant on these configuration. If you wish to submit a PR, we could catch `AccessError` alongside of `ValueError` here.

https://github.com/odoo/odoo/blob/a7bce66f3e6124ec572f86bc22c7d11c73df378d/addons/website_sale/models/website.py#L23-L28

But as said Jeremy, will only solve this specific problem, you may have other errors in existing websites that use this team.

**Closed by mart-e** 2021-04-20 08:56 UTC
Labels: Need information
