### ISSUE TITLE
[10.0] Postgres 10 sequences bug

### ISSUE THREAD

**Issue by farzeni** [odoo/odoo#21163] opened 2017-11-23 08:50 UTC
Impacted versions:
10.0

Steps to reproduce:
Install odoo 10 with postgres 10 and, with debug enabled, go to technical settings -> sequences

Current behavior:
In posgres 10 sequences specific table (eg ir_sequence_XXX) doesn't have anymore increment_by column, so the following select placed in:

odoo/addons/base/ir_sequency.py
78.                 query = "SELECT last_value, increment_by, is_called FROM ir_sequence_%03d" % seq.id

gives the following error:

Traceback (most recent call last):
  File "/srv/webapp/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/srv/webapp/odoo/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/srv/webapp/odoo/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/srv/webapp/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/srv/webapp/odoo/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/srv/webapp/odoo/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/srv/webapp/odoo/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/srv/webapp/odoo/addons/web/controllers/main.py", line 827, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/srv/webapp/odoo/addons/web/controllers/main.py", line 849, in do_search_read
    offset=offset or 0, limit=limit or False, order=sort or False)
  File "/srv/webapp/odoo/odoo/models.py", line 4699, in search_read
    result = records.read(fields)
  File "/srv/webapp/odoo/odoo/models.py", line 3021, in read
    values[name] = field.convert_to_read(record[name], record, use_name_get)
  File "/srv/webapp/odoo/odoo/models.py", line 5214, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/srv/webapp/odoo/odoo/fields.py", line 870, in __get__
    self.determine_value(record)
  File "/srv/webapp/odoo/odoo/fields.py", line 981, in determine_value
    self.compute_value(recs)
  File "/srv/webapp/odoo/odoo/fields.py", line 936, in compute_value
    self._compute_value(records)
  File "/srv/webapp/odoo/odoo/fields.py", line 927, in _compute_value
    getattr(records, self.compute)()
  File "/srv/webapp/odoo/odoo/addons/base/ir/ir_sequence.py", line 79, in _get_number_next_actual
    self._cr.execute(query)
  File "/srv/webapp/odoo/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/srv/webapp/odoo/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column "increment_by" does not exist
LINE 1: SELECT last_value, increment_by, is_called FROM ir_sequence_...

in postgres 10 increment_by info is stored in pg_sequences table, which is common to all sequences

**Comment by Yenthe666** [comment] 2017-11-23 08:57
Hi @farzeni,

Thank you for your bug report.
This is pretty much a duplicate of https://github.com/odoo/odoo/issues/20269 - which was fixed in the commits https://github.com/odoo/odoo/commit/fa5ee6ed2634b1a5b4388efb2c6ab6ae80356f28 and https://github.com/odoo/odoo/commit/56588e8d447a188f730ecfc62b451dba046e81ef in V11).
Fixes for V10 are at https://github.com/odoo/odoo/commit/fa5ee6ed2634b1a5b4388efb2c6ab6ae80356f28 and https://github.com/odoo/odoo/commit/7a4c6eb35d0dd662d2bd992f4725413efbe31a97
Please update your Odoo source code and this will be fixed.

**Closed by Yenthe666** 2017-11-23 08:57 UTC

**Comment by farzeni** [comment] 2017-11-23 13:17
oh, you are right

thank you for the quick response

**Comment by Yenthe666** [comment] 2017-11-23 13:28
You're welcome - best of luck.
