### ISSUE TITLE
Singleton error in authenticate API

### ISSUE THREAD

**Issue by bhanukrn888** [odoo/odoo#25650] opened 2018-07-07 11:41 UTC
### Impacted versions:
10.0 and 11.0
### Steps to reproduce:
Affected API: /web/session/authenticate
Providing wrong credentials results in singleton error. I am able to reproduce in the odoo runbot.
A proper response has to shown.
**Sample Request:**
```
{
    "params":{
             "login":"admin",
             "password":"admin1",
             "db":"346136-11-0-cf1ec5-all"
   }
}
```
### Current behavior:
**Response:**
```
{
    "jsonrpc": "2.0",
    "id": null,
    "error": {
        "code": 200,
        "message": "Odoo Server Error",
        "data": {
            "name": "builtins.ValueError",
            "debug": "Traceback (most recent call last):\n  File \"/home/odoo/runbot/runbot/runbot/static/build/346136-11-0-cf1ec5/odoo/http.py\", line 650, in _handle_exception\n    return super(JsonRequest, self)._handle_exception(exception)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/346136-11-0-cf1ec5/odoo/http.py\", line 310, in _handle_exception\n    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])\n  File \"/home/odoo/runbot/runbot/runbot/static/build/346136-11-0-cf1ec5/odoo/tools/pycompat.py\", line 87, in reraise\n    raise value\n  File \"/home/odoo/runbot/runbot/runbot/static/build/346136-11-0-cf1ec5/odoo/http.py\", line 692, in dispatch\n    result = self._call_function(**self.params)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/346136-11-0-cf1ec5/odoo/http.py\", line 342, in _call_function\n    return checked_call(self.db, *args, **kwargs)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/346136-11-0-cf1ec5/odoo/service/model.py\", line 97, in wrapper\n    return f(dbname, *args, **kwargs)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/346136-11-0-cf1ec5/odoo/http.py\", line 335, in checked_call\n    result = self.endpoint(*a, **kw)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/346136-11-0-cf1ec5/odoo/http.py\", line 936, in __call__\n    return self.method(*args, **kw)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/346136-11-0-cf1ec5/odoo/http.py\", line 515, in response_wrap\n    response = f(*args, **kw)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/346136-11-0-cf1ec5/odoo/addons/web/controllers/main.py\", line 787, in authenticate\n    return request.env['ir.http'].session_info()\n  File \"/home/odoo/runbot/runbot/runbot/static/build/346136-11-0-cf1ec5/odoo/addons/web_tour/models/ir_http.py\", line 12, in session_info\n    result = super(Http, self).session_info()\n  File \"/home/odoo/runbot/runbot/runbot/static/build/346136-11-0-cf1ec5/odoo/addons/barcodes/models/ir_http.py\", line 11, in session_info\n    res = super(IrHttp, self).session_info()\n  File \"/home/odoo/runbot/runbot/runbot/static/build/346136-11-0-cf1ec5/odoo/addons/web/models/ir_http.py\", line 28, in session_info\n    \"is_system\": request.env.user._is_system(),\n  File \"/home/odoo/runbot/runbot/runbot/static/build/346136-11-0-cf1ec5/odoo/addons/base/res/res_users.py\", line 618, in _is_system\n    self.ensure_one()\n  File \"/home/odoo/runbot/runbot/runbot/static/build/346136-11-0-cf1ec5/odoo/models.py\", line 4362, in ensure_one\n    raise ValueError(\"Expected singleton: %s\" % self)\nValueError: Expected singleton: res.users()\n",
            "message": "Expected singleton: res.users()",
            "arguments": [
                "Expected singleton: res.users()"
            ],
            "exception_type": "internal_error"
        }
    }
}
```
### Expected behavior:
**Response:**
```
{
    "jsonrpc": "2.0",
    "id": null,
    "result": {
        "username": "admin",
        "user_context": {            
            "lang": "en_US",
            "tz": "Europe/Brussels",
            "uid": 1
        },
        "uid": 1,
        "db": "346136-11-0-cf1ec5-all",
        "company_id": 1,
        "session_id": "11a5a8de3f3fe82f2dabeec9f9cd4c2182d0fd1b",
        "partner_id": 3
    }
}
```
Video/Screenshot link (optional):

**Comment by sswapnesh** [comment] 2018-07-07 13:05
Duplicate of #24071

**Comment by bhanukrn888** [comment] 2018-07-08 07:44
@sswapnesh,
This issue occurs in odoo 10 also

**Comment by pedrobaeza** [comment] 2018-07-09 08:16
Closing as duplicated.

**Closed by pedrobaeza** 2018-07-09 08:16 UTC
