### ISSUE TITLE
i made one mistake... i run the command of git for hard reset with origin/11.0 and when it's done lots of error are came like couldn't import this module

### ISSUE THREAD

**Issue by GauswamiSaumil** [odoo/odoo#32917] opened 2019-04-24 12:40 UTC
Impacted versions:

Steps to reproduce:

Current behavior:
Traceback (most recent call last):
File "/opt/odoo/odoo/odoo/modules/registry.py", line 85, in new
odoo.modules.load_modules(registry._db, force_demo, status, update_module)
File "/opt/odoo/odoo/odoo/modules/loading.py", line 376, in load_modules
force, status, report, loaded_modules, update_module, models_to_check)
File "/opt/odoo/odoo/odoo/modules/loading.py", line 274, in load_marked_modules
perform_checks=perform_checks, models_to_check=models_to_check
File "/opt/odoo/odoo/odoo/modules/loading.py", line 137, in load_module_graph
load_openerp_module(package.name)
File "/opt/odoo/odoo/odoo/modules/module.py", line 368, in load_openerp_module
import('odoo.addons.' + module_name)
File "/opt/odoo/odoo/odoo/modules/module.py", line 82, in load_module
exec(open(modfile, 'rb').read(), new_mod.dict)
File "", line 5, in 
File "/opt/odoo/odoo/addons/http_routing/models/init.py", line 5, in 
from . import ir_ui_view
File "/opt/odoo/odoo/addons/http_routing/models/ir_ui_view.py", line 5, in 
from odoo.addons.http_routing.models.ir_http import slug, unslug_url
ImportError: cannot import name 'slug'
2019-04-24 12:20:37,990 18107 CRITICAL learn_db odoo.service.server: Failed to initialize database learn_db.
Traceback (most recent call last):
File "/opt/odoo/odoo/odoo/service/server.py", line 945, in preload_registries
registry = Registry.new(dbname, update_module=update_module)
File "/opt/odoo/odoo/odoo/modules/registry.py", line 85, in new
odoo.modules.load_modules(registry._db, force_demo, status, update_module)
File "/opt/odoo/odoo/odoo/modules/loading.py", line 376, in load_modules
force, status, report, loaded_modules, update_module, models_to_check)
File "/opt/odoo/odoo/odoo/modules/loading.py", line 274, in load_marked_modules
perform_checks=perform_checks, models_to_check=models_to_check
File "/opt/odoo/odoo/odoo/modules/loading.py", line 137, in load_module_graph
load_openerp_module(package.name)
File "/opt/odoo/odoo/odoo/modules/module.py", line 368, in load_openerp_module
import('odoo.addons.' + module_name)
File "/opt/odoo/odoo/odoo/modules/module.py", line 82, in load_module
exec(open(modfile, 'rb').read(), new_mod.dict)
File "", line 5, in 
File "/opt/odoo/odoo/addons/http_routing/models/init.py", line 5, in 
from . import ir_ui_view
File "/opt/odoo/odoo/addons/http_routing/models/ir_ui_view.py", line 5, in 
from odoo.addons.http_routing.models.ir_http import slug, unslug_url
ImportError: cannot import name 'slug'

Expected behavior:

Video/Screenshot link (optional):
![error](https://user-images.githubusercontent.com/47734272/56660028-2f012600-66bc-11e9-8e16-14b96c3ace9e.png)

**Comment by gdgellatly** [comment] 2019-04-24 13:06
Thats a pretty big mistake.

You have 2 options.
1. Fix it using some git skills. (seeing its called learn_db, good way to learn).
2. Trash it and start over with fresh repo.

I nearly always choose option 2 as the fastest.

But it isn't an Odoo bug. And no way anyone here knows what existed before or even what version it was before or how you've managed it.

**Comment by Yenthe666** [comment] 2019-04-24 13:08
Closing as duplicate of https://github.com/odoo/odoo/issues/32916 where I also gave you an answer already.

**Closed by Yenthe666** 2019-04-24 13:08 UTC

**Comment by GauswamiSaumil** [comment] 2019-04-25 05:19
i solved that error with below commands of git:-
1) git reflog -> that will give you a current head than whichever id of that head just copy it and execute second command 
2) sudo git reset --hard  [copied head's id(paste it)]

solved.....
