### ISSUE TITLE
Odoo Helpdesk can't handle automated email replies(vacation notice)

### ISSUE THREAD

**Issue by aaly-dp** [odoo/odoo#66329] opened 2021-02-17 09:50 UTC
Impacted versions:
13

Steps to reproduce:
1. Configure an automated reply in your email.
2. Install the Helpdesk Module and configure the first step to reply with an automated reply, that Odoo received the email/ticket.
3. Send with the same email address, that has an automated email reply, an email to the Helpdesk Module in Odoo.
4. Be ware: The CronJobs for fetching and sending emails are running every 5 Minutes or so.

Current behavior:
Odoo and the Email Server will play ping pong with emails. Odoo replies with an email, that a ticket was created. And the email Server replies with an automated reply of Odoo. This leads Odoo to create another helpdesk ticket and sends a reply again.

This is a loop and can just be stopped, if you stop the odoo reply email or removing the automated reply from the helpdesk stage.
Odoo Helpdesk can't handle automated replies.

Expected behavior:
Odoo Helpdesk should be able to detect automated replies and ignore them.

Video/Screenshot link (optional):
![fis bounce](https://user-images.githubusercontent.com/32839388/108186708-fc84b080-710d-11eb-9f16-20ad8825d5f1.jpg)

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment] 2021-02-17 10:12
I don't think the problem is in Odoo, but on configuration. Anyway, being something enterprise, please report it to odoo.com/help instead. Closing as something very specific of deployment and for enterprise.

**Closed by pedrobaeza** 2021-02-17 10:12 UTC

**Comment by tnagels** [comment] 2022-01-07 12:14
Don't understand why this should be limited to enterprise. Many of our customers have out-of-office messages which could trigger this. Also a number of our suppliers communicate with us using CRM's which also generate automatic replies, triggering this same chain.

**Comment by Bramasselman** [comment] 2026-02-17 20:56
Still an issue on v18? Looked through the source and couldn't find any auto-Submitted header checks, only bounce handling via mailer-daemon. Automated replies and OOTO messages get routed as regular emails.

Ended up writing a module that filters these out: https://apps.odoo.com/apps/modules/18.0/reply_intelligence
