### ISSUE TITLE
unsubscribe_from_list in sitemap.xml

### ISSUE THREAD

**Issue by gregory-moka** [odoo/odoo#35464] opened 2019-08-05 15:53 UTC
**Impacted versions:**
12.0 CE

**Steps to reproduce:**
Activate website + email marketing

**Current behavior:**
the unsubscribe_from_list page is added on the sitemap => Google Search Console find a 404 page.

**Expected behavior:**
unsubscribe_from_list page shouldn't be mentionned in the sitemap.xml

**Comment by pedrobaeza** [comment] 2019-08-05 15:58
@JKE-be can you check this?

**Comment by gregory-moka** [comment] 2019-08-05 16:12
And the view mention other item in sitemap, but, there are no way to edit those values : 
- lastmod (automatic, I guess)
- prority
- Changefreq

![image](https://user-images.githubusercontent.com/45974412/62478852-6a77ba00-b7ac-11e9-9e42-7e5e99167a39.png)

**Comment by Yenthe666** [comment] 2019-08-08 12:04
or alternatively @rdeodoo as @JKE-be is on holiday :)

**Comment by rdeodoo** [comment] 2019-08-08 12:37
That should not be the case since https://github.com/odoo/odoo/commit/ad4a618a82649a040c1a6d318e5ad62a90c0eb17
Could you confirm you had this issue on latest codebase?

For the `lastmod` and `changefreq`, I could not find an answer for you, I will investigate further and come back to you.

**Comment by rdeodoo** [comment] 2019-08-26 09:49
Closing this as I could not reproduce the bug and the mentioned commit should've fixed it.

About `lastmod` and `changefreq`, as far as I know, that code was never used (introduced with https://github.com/odoo/odoo/commit/54d30d5194117e2e2484a199bc66464224bd1152 but never used it seems).

**Closed by rdeodoo** 2019-08-26 09:49 UTC
Labels: 12.0, Website

**Comment by rdeodoo** [comment] 2019-08-26 16:26
This is now fixed in 11.0.
