### ISSUE TITLE
Not allowed to modify documents of type 'Public Employee'

### ISSUE THREAD

**Issue by hileut2016** [odoo/odoo#39219] opened 2019-10-23 05:00 UTC
Impacted versions:
13.0

Steps to reproduce:
Click employee which is manager

Current behavior:
Sorry, you are not allowed to modify documents of type 'Public Employee' (hr.employee.public). No group currently allows this operation. - (Operation: write, User: 2)

Expected behavior:

Video/Screenshot link (optional):
<img width="882" alt="warning1" src="https://user-images.githubusercontent.com/23517268/67359101-970dc780-f58c-11e9-8317-7616d2740a0f.png">

**Comment by pedrobaeza** [comment] 2019-10-23 07:59
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by hileut2016** [comment] 2019-10-23 08:34
Yes, I am able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot  - admin/admin)
Steps to reproduce:
Click module employe. Click employees that at the top of organization chart. eg. Mitchell Admin and Ronnie Hart. Produce a warning as i mentioned above. "Sorry, you are not allowed to modify documents of type 'Public Employee' (hr.employee.public). No group currently allows this operation. - (Operation: write, User: 2)"

**Comment by Talal-Albahra** [comment] 2019-10-25 12:54
Hello,
I'm facing the same issue in V13 EE
Did anyone solve this?

**Comment by Yenthe666** [comment] 2019-10-25 13:02
Confirmed on latest 13.0: 
![image](https://user-images.githubusercontent.com/6352350/67573247-2b685d80-f738-11e9-81d2-b6365d63f1d0.png)
OPW `2093677`

**Comment by sswapnesh** [comment] 2019-10-27 09:35
Regression of https://github.com/odoo/odoo/pull/38805
I am pretty sure it was working earlier.
Cc @rco-odoo

**Comment by sswapnesh** [comment] 2019-10-27 09:52
Added fix at https://github.com/odoo/odoo/pull/39405
@Yenthe666  Could you please send this PR reference in the OPW for fast-tracking ?

**Comment by Yenthe666** [comment] 2019-10-28 07:12
@sswapnesh done!

**Comment by sswapnesh** [comment] 2019-10-28 11:14
This has been fixed in #39405

**Comment by pedrobaeza** [comment] 2019-10-28 11:16
Closing then, thanks!

**Closed by pedrobaeza** 2019-10-28 11:16 UTC
Labels: 13.0, Confirmed, HR, OE

**Comment by lovermann** [comment] 2019-10-29 11:15
Have the same problem.
![odoo-error](https://user-images.githubusercontent.com/19916572/67762429-7810a900-fa56-11e9-837f-6f55d9bd72f7.png)

**Comment by pedrobaeza** [comment] 2019-10-29 11:16
You should update your code for having the fix applied.

**Comment by Talal-Albahra** [comment] 2019-10-29 11:21
Pardon me please, but how could we update the code in an on-premises installation?

**Comment by pedrobaeza** [comment] 2019-10-29 11:32
Sorry, but that's out of the scope of this issue tracker. You should know how to deploy things if you are doing that on premise. If not, use SaaS services, where it's done automatically. And it totally depends on how did you deploy it originally. Ask in the forum indicating the used deployment method.

**Comment by lovermann** [comment] 2019-10-29 11:34
I think there's some misunderstanding. We thought we can send bug reports regarding the problems we've met using odoo.com embedded  online applications.

**Comment by pedrobaeza** [comment] 2019-10-29 11:40
@lovermann and what is your role here? And what "odoo.com embedded online applications" mean?

The bug is solved, but you need to know how to deploy it, and this issue tracker is not the place to know how to do that.

**Comment by Yenthe666** [comment] 2019-10-29 12:43
For a tutorial with Git see https://www.odoo.yenthevg.com/update-odoo-environment-github/
