### ISSUE TITLE
[13.0] Users e-mail signature code view disappeared

### ISSUE THREAD

**Issue by marcinkuk** [odoo/odoo#41147] opened 2019-11-30 10:57 UTC
Impacted versions:
13.0

Steps to reproduce:
Go to user preferences and try to edit signature

Current behavior:
Switch to code view is not visible like in v12.0

Expected behavior:
Switch to code view should be visible

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2019-11-30 12:43
I have been able to do it from the user form with debug mode:

![Selección_018](https://user-images.githubusercontent.com/7165771/69900725-52d5ca00-1377-11ea-8394-ad1ae653a63f.png)

Closing as no real issue.

**Closed by pedrobaeza** 2019-11-30 12:43 UTC

**Comment by marcinkuk** [comment] 2019-11-30 15:57
Is debug mode the same as developer mode? I switched to developer mode and don't see this button.

**Comment by pedrobaeza** [comment] 2019-11-30 17:11
Yes, developer mode. You should have something different in your end: outdated code, custom code, etc

**Comment by marcinkuk** [comment] 2019-11-30 18:09
Any modifications applied. Clear installation - only CRM module installed.

Odoo version: Odoo 13.0-20191106
Environment: docker composed from https://hub.docker.com/_/odoo/

Developer mode: ON.
No code preview button.

![Przechwycenie obrazu ekranu_2019-11-30_19-02-45](https://user-images.githubusercontent.com/5391645/69904260-dbb72a80-13a4-11ea-86da-6468a46adea3.png)

**Comment by Yenthe666** [comment] 2019-11-30 18:22
Possible also related to https://github.com/odoo/odoo/pull/40421 which was fixed 12 days ago

**Comment by pedrobaeza** [comment] 2019-11-30 18:50
I'm doing it from user form view, not the popup.

**Comment by marcinkuk** [comment] 2019-11-30 20:00
> I'm doing it from user form view, not the popup.

Checked from user form view - problem still exist.

**Comment by pedrobaeza** [comment] 2019-11-30 20:20
As said, the problem is in your side. Try on runbot and you'll see it works.
