### ISSUE TITLE
[11.0] ondelete attribute is not correctly shown on field form

### ISSUE THREAD

**Issue by sqxccdy** [odoo/odoo#24464] opened 2018-04-27 03:47 UTC
Impacted versions: 11

Steps to reproduce:  any many2one field define fields.Many2one("item.sales", string="2 hours sales", ondelete='cascade')

Expected behavior:
hope ondelete of many2one field is active.

Video/Screenshot link (optional):
please check and repair it

![图片](http://wx4.sinaimg.cn/mw690/0060lm7Tly1fqr2lnttgrj30o90jr3zq.jpg
)

**Comment by pedrobaeza** [comment] 2018-04-27 11:26
Hi, I'm not able to reproduce this problem. ondelete='cascade' works the way it has to work: when deleting the main record, children records are removed as well, so no real issue.

**Comment by sswapnesh** [comment] 2018-04-27 14:04
@pedrobaeza  I also consider this as Bug.

**Comment by pedrobaeza** [comment] 2018-04-27 14:35
I don't get why. Maybe the problem is the screenshot in a language I don't understand.

**Comment by sswapnesh** [comment] 2018-04-27 14:40
On Delete is Blank in the above Screenshot.
It should be set Cascade.

Actually it is not related to order_id but it is related to Core. Even if On delete Cascade is set in Fields definition, It is always blank in If you see In Database Structure.

**Comment by pedrobaeza** [comment] 2018-04-27 14:41
Then the problem is on the display only?

**Comment by sswapnesh** [comment] 2018-04-27 14:47
Yes, In works well in the Backend.

**Comment by pedrobaeza** [comment] 2018-04-27 17:43
I have changed the description then to reflect the real problem.

**Comment by sswapnesh** [comment] 2018-04-27 19:50
Sane Behaviour in v10 too.
The domain is also Blank on the field even if it is there in field Definition.

Adding Screenshot in English for Reference.
![](https://image.prntscr.com/image/BEBuU4hzSyy9Yy4ABuvn-w.png)

**Comment by sqxccdy** [comment] 2018-04-28 08:50
@sswapnesh thanks...

**Comment by alexkuhn** [comment] 2018-05-14 08:05
The data fetched from an rpc `read` on this record seems wrong:
https://drive.google.com/file/d/1ospu9EKeAExLxJI3OpMqNlVMLMrUW8gh/view?usp=sharing

cc: @rco-odoo

**Comment by sqxccdy** [comment] 2018-05-18 06:09
ir.model.fields define real field name is "on_delete"..function _instanciate_attrs rename "on_delete" to "ondelete". ....It is not all case is active and work

**Comment by sswapnesh** [comment] 2018-10-06 16:49
Hello @alexkuhn 
This is meant for Custom modules not the Base ones, So if you Install any custom module than It will display data correctly.

**Comment by sswapnesh** [comment] 2018-10-18 19:17
Still` Access Rights` are missing.
![screenshot 30](https://user-images.githubusercontent.com/16624719/47178322-88b51c00-d338-11e8-99f6-41998d38a3cb.png)
![screenshot 31](https://user-images.githubusercontent.com/16624719/47178342-95d20b00-d338-11e8-84cb-4e330af0a566.png)

**Comment by rco-odoo** [comment] 2018-10-19 11:54
Fixed by #27906

**Closed by rco-odoo** 2018-10-19 11:54 UTC
Labels: 11.0, Framework
