### ISSUE TITLE
[9.0] l10n_nl accounting module is missing XML record

### ISSUE THREAD

**Issue by RoelAdriaans-B-informed** [odoo/odoo#11482] opened 2016-03-25 12:46 UTC
Impacted versions:
9.0 community & enterprise 

Steps to reproduce:
Install l10n_nl module on runbot or clean install

Current behavior:
Error:
```
Traceback (most recent call last):
  File "/home/odoo/runbot/extra/runbot/static/build/138863-9-0-3ab843/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)

<...>
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/138863-9-0-3ab843/openerp/addons/base/ir/ir_model.py", line 972, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % (xmlid))
ParseError: "External ID not found in the system: l10n_nl.tax_tag_5" while parsing /home/odoo/runbot/extra/runbot/static/build/138863-9-0-3ab843/openerp/addons/l10n_nl/account_chart_netherlands.xml:3360, near
<record id="btw_6_buy_incl" model="account.tax.template">
            <field name="sequence">10</field>
            <field name="chart_template_id" ref="l10nnl_chart_template"/>
            <field name="name">BTW te vorderen laag (inkopen incl. BTW)</field>
            <field name="description">6% BTW Incl.</field>
            <field eval="6" name="amount"/>
            <field name="amount_type">percent</field>
            <field name="price_include">True</field>
            <field name="refund_account_id" ref="vat_refund_low"/>
            <field name="account_id" ref="vat_refund_low"/>
            <field name="type_tax_use">purchase</field>
            <field name="tag_ids" eval="[(6,0,[ref('tax_tag_5')])]"/>
        </record>
```
Expected behavior:
Clean installation of module.

Related to commit https://github.com/odoo/odoo/commit/1c92a88003491966c7577839c4cea58ef71f244c

Pinging @sha-odoo  @pvy-odoo

**Comment by Yenthe666** [comment] 2016-06-14 07:15
Hi @RoelAdriaans-B-informed,

I've just tested this on the latest runbot and it all works fine.
This issue has probably been fixed in the meanwhile. Closing this since I can't reproduce it anymore.

Regards,
Yenthe

**Closed by Yenthe666** 2016-06-14 07:15 UTC
