### ISSUE TITLE
TypeError: Found non-callable @@iterator

### ISSUE THREAD

**Issue by lsqtzj** [odoo/odoo#61675] opened 2020-11-12 13:54 UTC
Impacted versions:Odoo 14.0-20201112 (Community Edition)

Steps to reproduce: Activate the developer mode (with tests assets)

Current behavior:

Expected behavior:

Video/Screenshot link (optional):
Error:

Traceback:
TypeError: Found non-callable @@iterator
    at PatchableClass._attachAdditionalContent (http://192.168.1.220:8069/web/static/src/js/control_panel/control_panel.js:164:32)
    at PatchableClass.patched (http://192.168.1.220:8069/web/static/src/js/control_panel/control_panel.js:134:18)
    at Fiber.complete (http://192.168.1.220:8069/web/static/lib/owl/owl.js:3595:31)
    at http://192.168.1.220:8069/web/static/lib/owl/owl.js:3335:40
    at Array.filter (<anonymous>)
    at Scheduler.flush (http://192.168.1.220:8069/web/static/lib/owl/owl.js:3327:27)
    at Store.__notifyComponents (http://192.168.1.220:8069/web/static/lib/owl/owl.js:4512:27)

**Comment by pedrobaeza** [comment] 2020-11-12 14:03
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by aduijs** [comment] 2020-12-22 04:31
@isqtzj did you by any change change the jquery version, or added/linked another jquery version?
I just rant into the same problem so i reversed the whole odoo instalation then i traced back my steps , and i had changed the jquery version to make it compatible with some scripts i was still using.

**Comment by pedrobaeza** [comment] 2020-12-22 07:10
Closing as no answer and seems something outside Odoo.

**Closed by pedrobaeza** 2020-12-22 07:10 UTC
Labels: Need information
