### ISSUE TITLE
Not possible to load data from CSV files using noupdate=1

### ISSUE THREAD

**Issue by lonelyleaves** [odoo/odoo#25536] opened 2018-06-29 08:10 UTC
Impacted versions:10 &11

I wrote a basic permission group through csv. There will be different usage scenarios. Then I will modify some corresponding permissions in the permission group. Now if I update the module where the csv is located, many permissions will be covered by the csv file. Hopefully, Can be resolved when the upgrade can be set to update

**Comment by Yenthe666** [comment] 2018-06-29 09:05
Hi @lonelyleaves,

It is not really clear what you're trying to explain or what the issue is.
Can you add code, samples en detailed steps about what you believe is wrong or a bug?

Regards,
Yenthe

**Comment by pedrobaeza** [comment] 2018-06-29 09:12
I think I get it, Yenthe. He wants to be able to put on `data` key on the manifest a CSV file, but mark some of the records (or all) as noupdate.

Unfortunately, that's not possible. If you want noupdate records, then you have to use XML files, with the tag `<data noupdate="1">` (or directly `<odoo noupdate="1">` if all file is noupdate).

Closing this issue then. If this is not what you ask for, feel free to reply.

**Closed by pedrobaeza** 2018-06-29 09:12 UTC
Labels: Need information

**Comment by Yenthe666** [comment] 2018-06-29 09:13
Ahh. Indeed, if that is what he means it is not possible and it'll need to be XML noupdate records.
Thanks for the help & feedback @pedrobaeza
