### ISSUE TITLE
Odoo Client Error v11 enterprise

### ISSUE THREAD

**Issue by fasilwdr** [odoo/odoo#49683] opened 2020-04-16 16:46 UTC
Error:
Uncaught TypeError: Cannot read property 'clone' of undefined

http://localhost:8069/web/content/252-8cfb54c/web.assets_backend.js:976
Traceback:
TypeError: Cannot read property 'clone' of undefined
    at Object.formatDateTime [as datetime] (http://localhost:8069/web/content/252-8cfb54c/web.assets_backend.js:976:69)
    at Class._renderBodyCell (http://localhost:8069/web/content/252-8cfb54c/web.assets_backend.js:1625:137)
    at http://localhost:8069/web/content/252-8cfb54c/web.assets_backend.js:1643:132
    at Function._.map._.collect (http://localhost:8069/web/content/244-fc361f2/web.assets_common.js:13:270)
    at Class._renderRow [as _super] (http://localhost:8069/web/content/252-8cfb54c/web.assets_backend.js:1643:82)
    at Class._renderRow (http://localhost:8069/web/content/252-8cfb54c/web.assets_backend.js:1585:71)
    at Class._renderRow (http://localhost:8069/web/content/244-fc361f2/web.assets_common.js:3819:371)
    at Function._.map._.collect (http://localhost:8069/web/content/244-fc361f2/web.assets_common.js:13:270)
    at Class._renderRows (http://localhost:8069/web/content/252-8cfb54c/web.assets_backend.js:1644:85)
    at Class._renderRows (http://localhost:8069/web/content/252-8cfb54c/web.assets_backend.js:1586:53)

**Comment by pedrobaeza** [comment] 2020-04-16 16:52
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

Also, being enterprise, you can report your problem in odoo.com/help instead of here.

**Comment by pedrobaeza** [comment] 2020-05-08 19:45
No more information, so closing.

**Closed by pedrobaeza** 2020-05-08 19:45 UTC
Labels: Need information
