### ISSUE TITLE
[v10] odoo accounting dashboard - wrong value

### ISSUE THREAD

**Issue by orchidinfosys** [odoo/odoo#13945] opened 2016-10-23 18:36 UTC
Impacted versions: v10

Steps to reproduce: Accounting Dashboard - Invoiced and Pending showing wrongly
Invoice value 10,000, Partially Paid 3000, Waiting Payment 7000
Current behavior: Invoice showing 7000 in graph, Waiting Payment showing 10,000

Expected behavior: Invoice 10,000 Waiting Payment 7000, One more Filed Paid 3000

Video/Screenshot link (optional):

Dash Board View
![screen shot 2016-10-23 at 10 27 53 pm](https://cloud.githubusercontent.com/assets/2189864/19628528/c2d9caf6-9970-11e6-8891-fc0f7a6175d2.png)

Current Status

![screen shot 2016-10-23 at 10 28 08 pm](https://cloud.githubusercontent.com/assets/2189864/19628529/c4d3467a-9970-11e6-8479-21a8d893f6ee.png)

**Comment by pedrobaeza** [comment] 2018-05-01 14:54
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-05-01 14:54 UTC
Labels: 10.0

**Comment by raycarnes** [comment] 2018-07-18 23:58
See also https://github.com/odoo/odoo/pull/25859
