### ISSUE TITLE
Compute function not working when normal user loggedIn and works fine when admin user loggedIn

### ISSUE THREAD

**Issue by kajal789** [odoo/odoo#41148] opened 2019-11-30 12:25 UTC
Impacted versions: 13

Steps to reproduce:
1) Add new any compute field in hr.employee model and add to form view of employee (hr.view_employee_form)
2) Create two users one with admin access (Access Rights/Settings)  and second with normal internal user (Not a access Access Rights/Settings).
3) Now login with admin and go to Employee > any employee > compute function works well (compute function called)
4) Now login with normal and go to Employee > any employee > compute function will not called.

We have added one field on hr.employee and display this field in smart button (for the purpose for count documents) (Added field in smart button in header)

Current behavior:

So actually what happend, when we login as admin user and our smart button display in header section. but when we login as normal user header section is not display so our computed field is not display and our compute function is not called.

So we have checked that is there any conditions or groups or attrs added in header section through any view but it's not the issue of that. So why header section not display for normat user?

Expected behavior:

When we login as normal user, then header section will display and our smart button should display in header so compute function can call.

Note: It's working fine with admin user

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2019-11-30 12:44
Unless you put full code, this is to assume the problem is in your code.

**Comment by Yenthe666** [comment] 2020-01-05 17:29
Hi,

As there has been no feedback in quite a while I'm closing this report. When you provide more info we'll reopen it and look at it.

Regards,
Yenthe

**Closed by Yenthe666** 2020-01-05 17:29 UTC
Labels: 13.0, Need information
