### ISSUE TITLE
When the number of product variants is very large, the performance of the product.product is very low.

### ISSUE THREAD

**Issue by sum1201** [odoo/odoo#25649] opened 2018-07-07 09:14 UTC
Impacted versions:
11.0
Steps to reproduce:
- product A have 1000 product variant.
- when i open product.product screen , takes a long time to see the data
![qq20180707-170209](https://user-images.githubusercontent.com/5398273/42409116-1e934440-8208-11e8-85ec-865492f7b549.png)
Current behavior:

Expected behavior:

- I track sql ,found some bug ,found some problem 
- **Why just calculate the sales data for product.product, why would you calculate all the variants of product.template?**
https://github.com/odoo/odoo/blob/cf1ec5d3167b304923c91291cf13d1c8be73c290/addons/sale/models/product_product.py#L10-L25
![qq20180707-170539](https://user-images.githubusercontent.com/5398273/42409149-9181407e-8208-11e8-8566-42db8118e5b2.png)

![qq20180707-170619](https://user-images.githubusercontent.com/5398273/42409152-aa44eb2e-8208-11e8-8cb9-53f1795cb7c9.png)

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment] 2018-07-07 13:02
Already reported in #22783

**Comment by sum1201** [comment] 2018-07-07 14:29
@sswapnesh 
Thank you very much for your answer.
But I feel that you have not found the cause of the problem.
I think the reason for the low performance is not due to the compute.
Instead, when I only look at one of the product.product? information, why do I have to calculate all variants of its product.templte.

@xmo-odoo and @nseinlet

**Comment by sswapnesh** [comment] 2018-07-07 15:08
Hello @sum1201,
I have not gone through the detailed technical description but added that for reference.

**Comment by gdgellatly** [comment] 2018-07-08 01:49
@sum1201 - @sswapnesh is right.  It is essentially a duplicate, actually there are lots of duplicates for this and a few open PR's to resolve.  You have to read all the variants to get a sales count, as you can't sell product templates because they aren't stored on the order lines.

**Comment by sum1201** [comment] 2018-07-08 03:54
I just look at the data of a certain product, why does it calculate the variant of the product template? Not double counting

**Comment by moylop260** [comment] 2018-07-08 04:48
FYI I have created a fix in the following PR:
 - https://github.com/odoo/odoo/pull/25280

Notice that I have 2 commits, the first one is using the same behavior for current 11.0 version the second one is for using a way like other models. (Recommended: Use the first one)

**Comment by sum1201** [comment] 2018-07-08 05:39
@moylop260 
Thank you very much for your answer.
I don't know if I didn't express it clearly, or if I have a problem with my understanding.
Please see my picture above.
I opened the Form interface, just looking at one piece of data. 
Even if you want to calculate the sales volume of this product, you should only count the data related to this product. Why do you want to process other data?
I think there is a problem with inherits.


- I open a next product.product Form view ,and track my code
![qq20180707-170539](https://user-images.githubusercontent.com/5398273/42417122-6a74d166-82b3-11e8-94ef-17b012e58ff2.png)

- when  I tracking code ,I found self.ids 's count ==1000, **Why is this happening?**
I think self.ids  only one . I'm not in tree view
![qq20180707-170619](https://user-images.githubusercontent.com/5398273/42417125-894a8572-82b3-11e8-818a-84605511f634.png)

**Comment by sum1201** [comment] 2018-07-08 05:53
@gdgellatly @gdgellatly @sswapnesh @xmo-odoo and @nseinlet
I upload a mp4 to youtube.

https://youtu.be/h95loQXS_8w

**Comment by sswapnesh** [comment] 2018-07-08 06:33
Would have been better If it is in English.

**Comment by sum1201** [comment] 2018-07-09 08:45
@Yenthe666  @mart-e

**Comment by Yenthe666** [comment] 2018-07-09 09:09
Hey all,

This would have been better in English indeed. @sum1201 why didn't you continue on the previous issue you made though? It is pretty much the same but just more/other info.

**Comment by sum1201** [comment] 2018-07-09 09:33
I just have the text on the picture in Chinese. Next time I try to make the picture in English too.
The problems I described are different from what they discuss.
I think there is a problem with the inheritance design in product.template, product.product.

**Comment by switch87** [comment] 2018-07-09 11:15
Duplicate of #22783

**Comment by pedrobaeza** [comment] 2018-07-09 11:23
Closing as there's the other report, and this info is already linked by GitHub in the other issue.

**Closed by pedrobaeza** 2018-07-09 11:23 UTC
Labels: 11.0, Framework, Performance
