### ISSUE TITLE
Error: time.getLangDateFormatWoZero is not a function

### ISSUE THREAD

**Issue by setiawand** [odoo/odoo#74522] opened 2021-07-31 02:06 UTC
Impacted versions: 
14.0, ubuntu 20.0

Steps to reproduce: 

"apt-get upgrade odoo" will getting current nightly build, yesterday was build 20210730.

1. login
2. open Preferences menu on the right corner
3. error popup showing up
4. the error showing in some pages too, but random

Current behavior:

Expected behavior:
no popup error, last time on odoo build 20210429, never see the error

Video/Screenshot link (optional):

https://drive.google.com/file/d/1axAqhhlVosmogrrZ5-YvnQjnIBs5VQc7/view?usp=sharing

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment] 2021-07-31 08:35
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/14.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).

**Closed by pedrobaeza** 2021-07-31 08:36 UTC

**Comment by treviser** [comment] 2021-08-09 06:19
@pedrobaeza I have the same issue on a CE 14.0 deployment after I have installed a bunch of OCA modules. I have a suspicion it could be an OCA/edi module, but is there any way to find out without uninstalling and reinstalling dozens of modules?

**Comment by pedrobaeza** [comment] 2021-08-09 06:21
Well, you can try to debug with assets to see if it points to a specific code, but if not, you should uninstall some of them in a demo DB until spotting the conflicting one.

**Comment by treviser** [comment] 2021-08-09 06:22
@pedrobaeza Thanks for your prompt feedback. I was thinking the same, but I can't access the settings anymore because of this error.

**Comment by pedrobaeza** [comment] 2021-08-09 06:26
Use tools like `click-odoo-uninstall` for uninstalling from command line.

**Comment by treviser** [comment] 2021-08-09 06:27
Thanks for the hint, now I have to take the hard way :-)

**Comment by setiawand** [comment] 2021-08-09 06:59
Hi ermin,

What I did is update odoo to latest build and click the regenerate assets bundle.

First time try that it was not working, funny that after trying some times then it working

Sent from my iPhone

On 9 Aug 2021, at 13.27, Ermin Trevisan ***@***.***> wrote:

﻿

Thanks for the hint, now I have to take the hard way :-)
