### ISSUE TITLE
chart of account doesnt install on odoo 14.0

### ISSUE THREAD

**Issue by Khanstore** [odoo/odoo#59047] opened 2020-10-03 14:20 UTC
Impacted versions: 14.0

Steps to reproduce: install any chart Of account

Current behavior: Traceback (most recent call last):
  File "F:\original\odoo\odoo\http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "F:\original\odoo\odoo\http.py", line 314, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Many2one account.tax.report.line.report_id from Model to TransientModel is forbidden

Expected behavior: no error

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment] 2020-10-03 16:33
I am not able to Reproduce this issue. 
(and also the error you are mentioning could not be reproduced on 14 as report_id is not m2o in relation with TransientModel model)

**Comment by pedrobaeza** [comment] 2020-10-03 16:36
Closing meanwhile further evidence.

**Closed by pedrobaeza** 2020-10-03 16:36 UTC
