### ISSUE TITLE
[11.5] Wrong behavior on "Date" question type on Surveys

### ISSUE THREAD

**Issue by rsilvam21** [odoo/odoo#27012] opened 2018-09-15 16:58 UTC
Impacted versions:
11.5
Steps to reproduce:
Test a survey with a type of question "Date" and try to select a date on the calendar widget
Current behavior:
The Date field doesn't work as is, it works as a normal text field
Expected behavior:
Must appear the calendar widget in order to select a specific date
Video/Screenshot link (optional):
https://youtu.be/znYf1CnhY3M

**Comment by Yenthe666** [comment] 2018-09-16 09:26
@JKE-be I thing this has to do with your website refactoring. Just an FYI.

**Comment by rdeodoo** [comment] 2018-10-27 23:01
Hello, a fix was deployed recently for this: https://github.com/odoo/odoo/commit/46f48c35a03ef03a5a45596ad66dd278e023a7b4.
I checked on runbot on Odoo 12 and the datepicker is back with it.
Could you confirm the issue is also resolved on your end so I can close this one?
Thanks for your report

**Closed** 2018-10-29 10:42 UTC
Labels: Website
