### ISSUE TITLE
IndexError: list index out of range  in Odoo 13 - POS Restaurant

### ISSUE THREAD

**Issue by ivaqmo123** [odoo/odoo#40036] opened 2019-11-08 13:34 UTC
Impacted versions: 20191105 and 20191106

Current behavior: when switching from Table Mgmt view to Order view, there is a popup error that appears showing at the end "in get_table_draft_orders
    order['uid'] = order['pos_reference'].split(' ')[1]
IndexError: list index out of range"

Expected behavior: the popup error should not appear

Video/Screenshot link (optional):
[Issue.docx](https://github.com/odoo/odoo/files/3824771/Issue.docx)

**Comment by pedrobaeza** [comment] 2019-11-08 13:40
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by ivaqmo123** [comment] 2019-11-08 16:07
Hi @pedrobaeza , please see below detailed steps to reproduce the issue in runbot:

1.- Load Spanish-PE translation.
2.- Change localization preference for a user (either admin or demo) to Spanish.
3.- Login to Odoo POS using the user with spanish localization.
4. Go to POS, select BAR POS, select a table and place a draft order with at least 1 order line (do not proceed to payment)
5.- Go back to table mgmt view and click again to the previous selected table and the error appears.

Possible explanation:
This issue happens in any translation where pos_reference for a draft order is not separated with white space as it happens in English. I mean in english the pos_reference is something like "Order 00003-001-0002" but in spanish it is "Pedido00003-001-0002" (no whitespace), so the line 143 in code https://github.com/odoo/odoo/blob/13.0/addons/pos_restaurant/models/pos_order.py assumes that there will always be a whitespace which is not true for some odoo translations like spanish one.

**Comment by pedrobaeza** [comment] 2019-11-08 19:32
Thanks for the details. Now it's totally clear.

@switch87 what do you think of removing that faulty condition or apply it only if possible? I know that the translation can be amended, but failing due to a translation is not a very good thing. Other possibility is to leave out of the translation the space, so it's always found (and it's also weird to have an space and the end of the translation - normal that translators forget to add it -).

**Comment by ivaqmo123** [comment] 2019-11-13 16:51
hi @pedrobaeza , @switch87  - is there any workaround for this issue till a final solution is in place? please advise. I already tried to change .po file in i18n folder for pos_restaurant add on but it doesn't work. Also I installed es_CO translation in which "Order" is translated to "Orden" (same 5 characters) but the issue is also there.

Please advise. Thanks

**Comment by Yenthe666** [comment] 2019-11-19 07:45
This was actually fixed in https://github.com/odoo/odoo/commit/c32126da5ac55a03637d82cf520b8655be8546e6

**Closed by Yenthe666** 2019-11-19 07:45 UTC
Labels: 13.0, Point of Sale
