### ISSUE TITLE
Python 3 not orderable list with None values

### ISSUE THREAD

**Issue by cormaza** [odoo/odoo#25071] opened 2018-06-05 14:16 UTC
Impacted versions:
11.0
Steps to reproduce:
On production enviroment with python 3
Current behavior:
```
Traceback (most recent call last):
  File "/opt/odoo/server/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/server/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/server/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/server/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/server/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/server/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/server/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/server/addons/web/controllers/main.py", line 935, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/server/addons/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/ecua_contabilidad/ecua_hr/models/batch_slip.py", line 36, in recalc_payslip_run
    slip.onchange_employee()
  File "/opt/odoo/ecua_contabilidad/ecua_hr/models/slip.py", line 527, in onchange_employee
    return super(hr_payslip, self).onchange_employee()
  File "/opt/odoo/server/addons/hr_payroll/models/hr_payslip.py", line 458, in onchange_employee
    self.contract_id = self.env['hr.contract'].browse(contract_ids[0])
  File "/opt/odoo/server/odoo/fields.py", line 980, in __set__
    record.write({self.name: write_value})
  File "/opt/odoo/server/odoo/models.py", line 3086, in write
    self._write(old_vals)
  File "/opt/odoo/server/odoo/models.py", line 3314, in _write
    self.recompute()
  File "/opt/odoo/server/odoo/models.py", line 4884, in recompute
    field, recs = self.env.get_todo()
  File "/opt/odoo/server/odoo/api.py", line 911, in get_todo
    field = min(self.all.todo, key=self.registry.field_sequence)
TypeError: unorderable types: int() < NoneType()
```
Expected behavior:

On some occasions, when in a recurrent environment, the recalculation processes throw this exception to the user, it seems that some recalculation remains hanging and within the list is a None value, for which we have to restart the system so that it starts to work again, in python 2 the order does not throw error if you have a None in the list

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment] 2018-06-05 16:49
I cannot Reproduce on Runbot.
May be from custom module `ecua_hr` ?

**Comment by pedrobaeza** [comment] 2018-06-05 17:22
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. In concrete in module `ecua_hr`. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2018-06-05 17:22 UTC

**Comment by cormaza** [comment] 2018-06-05 19:08
It's not easy to reproduce, users show me error, I debug code en my machine and cannot reproduce,  because I think it's a matter of concurrency, for example, the process batch can last several minutes in case the client does not have access to it, however another user can send the same process, however when trying to recalculate any field the record has been deleted, so it can not process, and the system hangs, because that variable self.all.todo, can not be emptied again, and only restart fix behavior
