### ISSUE TITLE
[11.0] Bug in existing_accounting at file chart_template.py

### ISSUE THREAD

**Issue by jay009id** [odoo/odoo#42372] opened 2019-12-26 07:36 UTC
Impacted versions: 11.0

Steps to reproduce: Visit Accounting | Configuration | Settings, edit and save

Current behavior: It happen when account.move.line contains more than 7 mio

Expected behavior: No error message

Video/Screenshot link (optional):

![setting](https://user-images.githubusercontent.com/9130678/71464738-11590300-27ed-11ea-8cf7-b3c124f645fe.png)

**Comment by pedrobaeza** [comment] 2019-12-26 11:05
This is not a bug, but you have to increase the resources of your Odoo server (or configuration of limits).

Closing as deployment configuration error.

**Closed by pedrobaeza** 2019-12-26 11:05 UTC
