### ISSUE TITLE
[v10] Dynamic Domains - Web Client Many2many change???

### ISSUE THREAD

**Issue by dhannyz** [odoo/odoo#16072] opened 2017-03-27 06:01 UTC
Impacted versions: Latest v10

**Steps to reproduce:**
Use any domain in a view  like `domain="[('id', 'in', m2m_field and m2m_field[0][2])]"`

**Issue:**
Now returns the contents of the first element and not the list of id's making dynamic domains useless!

I know someone will come back and say 'use an onchange and return the domain', but I'm sorry, this doesn't cut it.
An onchange isn't triggered if the depending field is not changed, making the domain useless for already saved records (if will just allow everything!)
Not only that, but even worse, in a tree view, an onchange sets this domain for ALL rows of the tree, which makes no sense at all.
If you trigger the onchange in row 5 of your tree view, that same domain is applied to the field in **ALL the tree rows.** It's terrible...

The m2m_field[0][2]  actually woked quite well.

If there is a new way of accessing this feature can someone please advise. Otherwise some serious fixing is needed with the current onchange returned domain behaviour... Especially in the editable tree views.

**This recent change seems like a complete backwards step**

**Comment by chrisdilbert** [comment] 2017-03-27 20:35
This issue was caused by commit [https://github.com/odoo/odoo/commit/f65475d68cef09f5818841cf12fc5b22d295fe28](url)

**Comment by dhannyz** [comment] 2017-03-27 23:13
@chrisdilbert  Thanks, I had my 
suspicions about that particular commit when i had a quick browse through yesterday. 
@nle-odoo Can you confirm this is new desired behaviour or an unintended consequence? And could you suggest a work-around?

**Comment by nle-odoo** [comment] 2017-03-28 06:52
hi @dhannyz 


the commit f65475d68cef09f5818841cf12fc5b22d295fe28 has been only intended to have the same onchange behavior in x2many with default view as the behavior already present for x2many with an embedded view (embedded in the form view).

so if onchange are not part of the issue, f65475d68cef09f5818841cf12fc5b22d295fe28 should not change anything at all.

i have found an instance of `[('id', 'in', m2m_field and m2m_field[0][2])]` in our code and unless I am missing something it is still working if the many2many view is embedded or not.

if many2many is embedded (as it is in our code without modification) the list we see in the field with the domain is correct (and follow the many2many) and as you can see the list of ids in `m2m_field[0][2]` is present and updated (at the beginning there was only 2 ids):
http://i.imgur.com/FjxdrR9.png

and it is the same with a many2many with default view: http://i.imgur.com/E0GmmVl.png 

to be sure (but it should be the same) I also tested in 10.0 community and the result is the same: http://i.imgur.com/UvjNte7.png

so am I missing something or is there another particularity to reproduce the issue I missed?

and is the issue solved for you when you revert f65475d68cef09f5818841cf12fc5b22d295fe28?

**Comment by fva-idealis** [comment] 2017-03-28 09:09
hi @nle-odoo 

I confirm, I tried to revert this commit and it's works ! 

Could you please revert this commit definitively in your repository ? 

You can't do change like that with Odoo version already released. 

We have a lot of projects with Odoo 10 and you can imagine the disaster if we pull your last modifications.

Best regards

**Comment by nle-odoo** [comment] 2017-03-28 09:19
@fva-idealis ok

in any case I would prefer to reproduce the issue to know what the issue is. since you can also reproduce the issue do have have any hint about something specific that make it possible to reproduce the issue?

> You can't do change like that with Odoo version already released.

the change should only restrain what was done in https://github.com/odoo/odoo/commit/bbdf9605e4c

**Comment by fva-idealis** [comment] 2017-03-28 09:34
@nle-odoo For sure, it's easy to reproduce, here a sample:

To reproduce the issue you need two fields. The first one is many2many fields computed and one field many2one. Both fields are linked to same object:

```
external_company_domain_ids = fields.Many2many('res.company', 'company_rel', 'wizard_id', 'company_id', compute=_get_external_companies)

external_company_id = fields.Many2one('res.company', 'External Company', required=True)
```

My compute method is something like that:

```
@api.multi
@api.depends('OTHERFIELD')
def _get_external_companies(self):
	for wizard in self:

		...


    	wizard.external_company_domain_ids = ids
```

My view:

```
<field name="external_company_domain_ids" invisible="1"/>
<field name="external_company_id" domain="[('id', 'in', external_company_domain_ids and external_company_domain_ids[0] and external_company_domain_ids[0][2] or False)]"/>
```

Before the commit `external_company_domain_ids[0][2]` returned a list of ids and now it return the name fields and it crash when you load the view.

Thanks for your help

**Comment by dhannyz** [comment] 2017-03-28 09:50
Hi @fva-idealis This is a perfect example of the issue. thanks for your reproduction

@nle-odoo 
You say you have instance in your codebase in which it does still work, is it perhaps a stored M2M?, try using a computed, non-stored m2m field in the domain...
Being stored=False, this would behave like an onchange?

m2m_field = fields.Many2many(
    'comodel',
    string='Computed M2M'
    compute='_compute_m2m_field'
)

Using these types of computed m2m's is extremely handy when you need 'dynamic' domains. Especially handy in tree views...

Also what do you think about the other issue, with onchange return {'domain':{'field':[(domain)]}} on editable tree views?
It sets the domain on ALL the rows to that of the last onchange result. this is pretty useless when you wanted your domain to depends on a property in each row independently...

**Comment by nle-odoo** [comment] 2017-03-28 16:51
Hello @dhannyz  and @fva-idealis

Thanks, I have been able to reproduce.

When we combine non-stored x2many computed with default x2many view, now the onchange correctly returns a dictionary of value instead of just a list of ids (without this the onchange would be broken).

But the hack of `[('id', 'in', m2m_field and m2m_field[0][2])]` only works if the x2many has been populated by a list of ids.

So before the bc0313791 fix with your use case with a computed x2many field and an onchange:

```xml
<field name="x2many"/>
=> [V / X] returns a list of ids (field[0][2] works) but onchange may be broken

<field name="x2many">
  <tree><field name="name" /></tree>
</field>
=> [X / V] returns a list of dictionaries (field[0][2] doesn't work) and the onchange always work

<field name="x2many_changed_in_onchange"><tree /></field>
=> [V / V] returns a list of ids and the onchange worked
```

And after the fix:

```xml
<field name="x2many"/>
=> [X / V] returns a list of dictionaries (field[0][2] doesn't works) and the onchange always work

<field name="x2many">
  <tree><field name="name" /></tree>
</field>
=> [X / V] returns a list of dictionaries (field[0][2] doesn't work) and the onchange always works

<field name="x2many_changed_in_onchange"><tree /></field>
=> [V / V] returns a list of ids and the onchange worked
```

I am not sure what we can do there since if we reverted bc0313791 we would have:

- a hack based on internal implementation would work a little more times (when the x2many is computed or changed in an onchange) but still not everytime
- we would get back the real bug of onchange

At least now in the case of @fva-idealis (if the x2many is not displayed) it is possible to specify `<tree />` as the field view (which is logical to do since if you don't do it the tree view is fully loaded even if it is not used).

Another way (which would work also for a non empty tree (or other) view) is adding the onchange bug back on a case by case basis with something like:

```py
    @api.multi
    def onchange(self, values, field_name, field_onchange):
        for field in field_onchange.keys():
            if field.startswith('external_company_domain_ids.'):
                del field_onchange[field]
        return super(ResPartner, self).onchange(values, field_name, field_onchange)
```

As for fixing modifying it in stable:
- either I find a fix which solves the two issues: I currently have none,
- either I revert bc0313791: we add back the bug it solved

---

> Also what do you think about the other issue, with onchange return {'domain':{'field':[(domain)]}} on editable tree views?

Depending on how that is implemented it would not be out of expectation. If I remember correctly, the editable list row is a form view and if the same form view is used for all the row the domain of the field would be the same.

**Comment by chrisdilbert** [comment] 2017-03-28 17:20
@nle-odoo it's possible to add python expression when we need domains like field[0][2]?
Example: 
   `<attribute name="domain" eval="[('id', 'in', external_company_domain_ids and external_company_domain_ids[0] and external_company_domain_ids[0][2] or False)]" />`

**Comment by nle-odoo** [comment] 2017-03-28 18:16
@chrisdilbert 

no. there is the [`add` and `remove` variants](https://github.com/odoo/odoo/blob/10.0/odoo/addons/base/tests/test_views.py#L734-L737) (which allow to add / remove a word) but no eval.

do you have the problem and are you displaying the x2many computed?

**Comment by dhannyz** [comment] 2017-03-29 21:19
@nle-odoo Thanks for the workaround, this restores old behaviour. I imagine that will be annoying for many developers that have made use of the [0][2] method. 
Going forward however, shouldn't there be a better method for actually using a list of computed id's in a domain? To make a list available somewhere.
Perhaps a field of type list that can be sent to the form view?
```
m2o_field_1 = fields.Many2one('model1')
m2o_field_2 = fields.Many2one('model2')
domain_list = fields.List(compute='_compute_domain_list')

@api.depends('m2o_field_1')
def _compute_domain_list(self):
    for record in self:
        if record.m2o_field_1:
            domain_recordset = ...
            record.domain_list = domain_recordset.ids
```
```
<tree editable="bottom">
    <field name="m2o_field_1"
    <field name="domain_list" invisible="1"/>
    <field name="m2o_field_2" domain="[('id', 'in', domain_list)]"/>
</tree>
```

Also, is there a way of hacking a computed fields.Char to build a domain string?

**Comment by lmignon** [comment] 2017-03-30 06:35
@dhannyz @nle-odoo For the record I've written a module to be able to use the value of a field as domain of an other field in the xml definition of your view.
```xml
<field name="product_id_domain" invisible="1"/>
<field name="product_id" domain="product_id_domain"/>
```
https://github.com/acsone/web/blob/64db0709231a8203436926f535b085fd4246bcd5/web_domain_field/README.rst (https://github.com/OCA/web/pull/567 ). The JS code is too intrusive since we have to redefine some methods from pyeval.js. It would be nice to have this kind of functionality natively supported by odoo.

**Comment by nle-odoo** [comment] 2017-03-30 12:03
> Going forward however, shouldn't there be a better method for actually using a list of computed id's in a domain? To make a list available somewhere.

it is the crust of the issue here, we don't have a expected way to do this (so only hacks using internal implementation which don't work every time). it would be nice to have something like:

```xml
[('id', 'in', many2many_field.ids)]`
```

which always contain the ids (or compute the ids on the fly from the current list of values)

> Also, is there a way of hacking a computed fields.Char to build a domain string?

it seems to be what is done by lmignon and I don't see any way to have it simpler.

@lmignon : so in the example given by @fva-idealis we would have:

```xml
<field name="external_company_domain" invisible="1"/>
<field name="external_company_id" domain="external_company_domain"/>
```

with external_company_domain value being computed to the string `[['ids', 'in', [1, 5, 19, 20]]`?

**Comment by lmignon** [comment] 2017-03-30 12:48
@nle-odoo 
> @lmignon : so in the example given by @fva-idealis we would have:
> ```python
> <field name="external_company_domain" invisible="1"/>
> <field name="external_company_id" domain="external_company_domain"/>
> ``` 
> with external_company_domain value being computed to a string for example such as [['ids', 'in', [1, 5, 19, 20]]?

Yes it's a possibility but you are free to build any kind of domain using values from the current model instance. IMO this approach has the following advantages:
* To override / extend an existing domain you just need to override the compute method (you no more need to replace the domain into the xml)
* You are not limited in the way you can build your domain. 
* The domain can be reused into an 'api.constrains' to enforce this constraint if the record is not created from the UI,
* ....

```python
external_company_domain = fields.Char(
    compute="_compute_external_company_domain",
    readonly=True,
    store=False,
)

@api.multi
@api.depends('name')
def _compute_external_company_domain(self):
    for rec in self:
        rec.product_id_domain = json.dumps(
            [('name', 'like', rec.name),
             ('id', 'in', rec.external_company_domain_ids),
             ....
            ]
        )
```

**Comment by dhannyz** [comment] 2017-03-30 18:34
@lmignon Thanks for that link to your module, it looks like it achieves this in quite a nice way, as you also don't need to embed dependant x2m fields to compute domains. This is much lighter on the client as only a string need be re-sent onchange.
@nle-odoo It's unfortunate that odoo doesnt include this kind of domain operation in its core, and that there are no plans to introduce anything in the future. It seems to be a very common use case, particularly to restrict a domain further down entry flow (Column 1 selection in a row constrains column 4's domain).

Do either of you see any significant risk of altering pyeval in the way the 'web_domain_field' module does?

**Comment by mbcosta** [comment] 2017-04-11 19:56
This change also affect version 9.0 community. Thanks @lmignon , your module "save the day"

**Comment by dhannyz** [comment] 2017-04-12 04:35
@lmignon  I am having some js errors after installing your module, relating to the wrap function not being defined... In particular clicking through to some Many2one fields in tree views.
For example in a invoice/vendor bill, try to change the account_id in the invoice_line_ids

This is occuring both in my local, and also a near production-ready environment.
```
Uncaught ReferenceError: wrap is not defined

http://localhost:8069/web/content/410-bc4ac4a/web.assets_backend.js:4224
Traceback:
ReferenceError: wrap is not defined
    at F.__getitem__ (http://localhost:8069/web/content/410-bc4ac4a/web.assets_backend.js:4224:8)
    at F.__getattr__ (http://localhost:8069/web/content/410-bc4ac4a/web.assets_backend.js:4224:69)
    at F.__getattribute__ (http://localhost:8069/web/content/410-bc4ac4a/web.assets_backend.js:1385:38)
    at Object.py.PY_getAttr (http://localhost:8069/web/content/410-bc4ac4a/web.assets_backend.js:1349:176)
    at Object.py.evaluate (http://localhost:8069/web/content/410-bc4ac4a/web.assets_backend.js:1452:11)
    at Object.py.evaluate (http://localhost:8069/web/content/410-bc4ac4a/web.assets_backend.js:1450:194)
    at Object.py.eval (http://localhost:8069/web/content/410-bc4ac4a/web.assets_backend.js:1454:284)
    at http://localhost:8069/web/content/410-bc4ac4a/web.assets_backend.js:4234:110
    at iterator (http://localhost:8069/web/content/352-4429b4d/web.assets_common.js:14:183)
    at Function.<anonymous> (http://localhost:8069/web/content/352-4429b4d/web.assets_common.js:17:8)
```

**Comment by dhannyz** [comment] 2017-04-12 04:45
@lmignon @mbcosta 
Copying the wrap function from addons/web/static/src/js/framework/pyeval.js  into @lmignon 's version of pyeval.js resolves this issue.
As is said in the code
```javascript
/** copied from pyeval and not modified but required since not publicly
exposed by web.pyeval**/
```
Copy the following function just after that comment
```javascript
function wrap(value) {
    if (value === null) { return py.None; }

    switch (typeof value) {
    case 'undefined': throw new Error("No conversion for undefined");
    case 'boolean': return py.bool.fromJSON(value);
    case 'number': return py.float.fromJSON(value);
    case 'string': return py.str.fromJSON(value);
    }

    switch(value.constructor) {
    case Object: return wrapping_dict.fromJSON(value);
    case Array: return wrapping_list.fromJSON(value);
    }

    throw new Error("ValueError: unable to wrap " + value);
}```

**Comment by lmignon** [comment] 2017-04-12 07:10
@dhannyz This error is already fixed https://github.com/OCA/web/pull/567/files#diff-f760f293b9587c1f50a65e794fd45953R17. :smirk:

**Comment by krueger80** [comment] 2017-04-13 22:05
@nle-odoo Should we already start to migrate our code to @lmignon workaround or the company is going to give some other alternatives? This should be native to odoo imho!

**Comment by dhannyz** [comment] 2017-07-14 00:36
@nle-odoo Looking forward to odoo v11, with the frontend rewrite, will this workaround still be required to achieve this type of functionality? Or are there other possibilities with the new framework?
@lmignon Do you know yet if your module will be usable in v11? I would guess it may need some reworking.
I imagine there has been significant time invested in improving the behaviour of x2many fields in the new frontend, and would love to see this issue addressed.

**Comment by flyingL123** [comment] 2017-07-14 00:40
@dhannyz Agreed. I am relying pretty heavily on the web_domain_field module for my implementation. I'm hoping it still works in v11 if the standard Odoo functionality doesn't suffice.

**Comment by nle-odoo** [comment] 2017-07-14 14:09
@dhannyz 

doing a small test on master (new framework is available since saas-16), the following gives me an error in any case:

`domain="[('id', 'in', m2m_field and m2m_field[0][2])]"`

and this works:

`domain="[('id', 'in', x2m_field)]"`

**Comment by pedrobaeza** [comment] 2017-07-14 14:12
Cool! I was having a lot of issues with this and finally discarding this technique due to these issues.

**Comment by dhannyz** [comment] 2017-07-14 15:28
@nle-odoo ok that's interesting, I will have to have a play around. Particularly with the behaviour inside a one2many tree like sale order lines. 
It would be great if this indeed behaves nicely in all scenarios

**Comment by Yenthe666** [comment] 2018-01-10 15:09
@nle-odoo if I'm not mistaking this has all been handled & fixed in V11, no? I believe this can be closed.

**Comment by dhannyz** [comment] 2018-01-10 22:35
@Yenthe666 I believe it has been fixed in 11, so this can be closed, I will check in the coming days and if not I'll report any issues.
But what about support for v10 users who have not made the move to v11?

**Comment by Yenthe666** [comment] 2018-01-11 07:40
@dhannyz thanks for the feedback. In short: I don't think they'll fix this in V10 as it can break quite some things & they have to think about the stable policy. If you really want to figure it out I guess you can make a ticket at odoo.com/help to get an official response.

**Closed by Yenthe666** 2018-01-11 07:40 UTC
Labels: 10.0, Framework

**Comment by auyeung112002** [comment] 2018-03-14 09:43
`domain="[('id', 'in', m2m_field and m2m_field._store[0][2])]"` may work in v10 without web_domain_field module.
