### ISSUE TITLE
Ambiguous file to run Odoo

### ISSUE THREAD

**Issue by alejandrosantana** [odoo/odoo#6872] opened 2015-05-27 18:56 UTC
**Ambiguous file to run Odoo**

Official documentation says `odoo.py` should be used for launching Odoo:
https://www.odoo.com/documentation/8.0/setup/install.html#running-odoo

But actually there are three files to run Odoo: `odoo.py`, `openerp-server`, `openerp-gevent`, each one with requirements and disadvantages: *openerp-gevent* seems to disable cron and needs workers>0, *openerp-server* seems to not support *im_chat* or *im_livechat*, *odoo.py* not even sure.

Is there a need to run 2 simultaneous Odoo instances to have im_chat/im_livechat and cron available at the same time?

References:

- https://www.odoo.com/nl_NL/forum/help-1/question/live-chat-running-with-gevent-and-cron-stops-working-34171
- https://www.odoo.com/nl_NL/forum/help-1/question/how-to-activate-chat-im-in-v8-trunk-22521
- Is there a need to run 2 instances

Impacted versions:

 - 8.0 (and beyond, I supose)

Steps to reproduce:

 1. try to choose a file to run your Odoo

Current behavior:

 - Three ways of running Odoo: `odoo.py`, `openerp-server`, `openerp-gevent`

Expected behavior:

 - Clear specification of which file to use to run Odoo, and their needs and consequences

**Comment by spadae22** [comment] 2015-05-27 19:51
+1

**Comment by mart-e** [comment] 2015-05-27 19:54
Hello,

`odoo.py` is the classical way to run an odoo server. However it's true it's not the only way to run it.
The good news is that the documentation is [in the code](https://github.com/odoo/odoo/blob/8.0/doc/setup/install.rst#running-odoo) so don't hesitate to submit a better documentation.
Thanks

**Comment by spadae22** [comment] 2015-05-27 19:57
Hi,
OK, so what is the correct way to run odoo with workers >0 and be able to use the chat function. I do not see documentation for this. If workers=0, it works fine. Please let us know as this question is posted in a few places. Tx

**Comment by spadae22** [comment] 2015-05-27 19:59
This is what is running when use the the script:
padae22@spadae22-ProLiant-DL380-Gen9:~$ ps aux|grep openerp
spadae22 14097  0.0  0.0  15944  2268 pts/17   S+   15:58   0:00 grep --color=auto openerp
odoo     27619  1.6  0.1 324372 117784 ?       SN   12:45   3:12 python /opt/odoo/openerp-server -c /etc/odoo-server.conf
odoo     32022  0.0  0.1 298620 100684 ?       S    03:01   0:33 python /opt/odoo/openerp-server -c /etc/odoo-server.conf
odoo     32031  0.0  0.2 351700 136488 ?       S    03:01   0:34 python /opt/odoo/openerp-server -c /etc/odoo-server.conf
odoo     32032  0.0  0.2 366076 150764 ?       S    03:01   0:38 python /opt/odoo/openerp-server -c /etc/odoo-server.conf
odoo     32033  0.0  0.2 359324 144124 ?       S    03:01   0:36 python /opt/odoo/openerp-server -c /etc/odoo-server.conf
odoo     32034  0.0  0.2 359392 144192 ?       S    03:01   0:34 python /opt/odoo/openerp-server -c /etc/odoo-server.conf
odoo     32035  0.0  0.2 379780 164600 ?       S    03:01   0:37 python /opt/odoo/openerp-server -c /etc/odoo-server.conf
odoo     32036  0.0  0.2 364804 149512 ?       S    03:01   0:39 python /opt/odoo/openerp-server -c /etc/odoo-server.conf
odoo     32037  0.1  0.4 577800 319140 ?       S    03:01   0:51 python /opt/odoo/openerp-server -c /etc/odoo-server.conf
odoo     32038  0.2  0.2 363924 148368 ?       S    03:01   1:57 python /opt/odoo/openerp-server -c /etc/odoo-server.conf
odoo     32039  0.0  0.2 358540 143440 ?       S    03:01   0:35 python /opt/odoo/openerp-server -c /etc/odoo-server.conf
odoo     32040  0.0  0.2 363836 148172 ?       S    03:01   0:39 python /opt/odoo/openerp-server -c /etc/odoo-server.conf
odoo     32041  0.0  0.2 360948 144388 ?       S    03:01   0:38 python /opt/odoo/openerp-server -c /etc/odoo-server.conf
odoo     32042  0.0  0.2 358896 143660 ?       S    03:01   0:37 python /opt/odoo/openerp-server -c /etc/odoo-server.conf
odoo     32043  0.0  0.5 581568 330936 ?       S    03:01   0:41 python /opt/odoo/openerp-server -c /etc/odoo-server.conf
odoo     32044  0.1  0.2 440840 158052 ?       S    03:01   0:52 python /opt/odoo/openerp-server -c /etc/odoo-server.conf
odoo     32045  0.0  0.2 360932 145624 ?       S    03:01   0:42 python /opt/odoo/openerp-server -c /etc/odoo-server.conf
odoo     32046  0.2  0.2 356808 141608 ?       S    03:01   1:44 python /opt/odoo/openerp-server -c /etc/odoo-server.conf
odoo     32047  0.0  0.2 353392 138236 ?       S    03:01   0:35 python /opt/odoo/openerp-server -c /etc/odoo-server.conf
odoo     32048  0.0  0.0 315900 61032 ?        Sl   03:01   0:02 /usr/bin/python /opt/odoo/openerp-gevent -c /etc/odoo-server.conf
odoo     32049  2.0  0.2 359168 154420 ?       SN   03:01  16:01 python /opt/odoo/openerp-server -c /etc/odoo-server.conf

**Comment by mart-e** [comment] 2015-06-03 15:48
You will need to configure a proxy on `/longpolling` URL with a dedicated `--longpolling-port` option when running in multiworker, see [basic doc](https://github.com/odoo/odoo/blob/8.0/doc/setup/deploy.rst#livechat) (a bit minimal, suggestions of improvement welcomed).
You will also need additional configuration if you use WSGI (we don't use it ourself so can not really help you here).
Closing as not a bug but deployment questions.

**Closed by mart-e** 2015-06-03 15:48 UTC
