### ISSUE TITLE
Import error: odoo.service.report

### ISSUE THREAD

**Issue by MeetKD** [odoo/odoo#23832] opened 2018-03-22 14:18 UTC
Impacted versions:
11.0
Steps to reproduce:

Take latest pull of 11.0 branch.

Current behavior:

Unable to start the odoo server.

Expected behavior:

Server should run without import error.

ImportError: No module named 'odoo.service.report'

**Comment by pedrobaeza** [comment] 2018-03-22 14:28
Sorry, but this seems to be something associated with your deployment method. Can you provide at least the full stack trace?

**Comment by sswapnesh** [comment] 2018-03-22 14:38
@pedrobaeza 
I cam reproduce this too.
`CRITICAL ? odoo.modules.module: bad magic number in 'odoo.service.report': b'\x03\xf3\r\n'
ERROR ? odoo.service.server: Failed to load server-wide module `web`.
The `web` module is provided by the addons found in the `openerp-web` project.
Maybe you forgot to add those addons in your addons_path configuration.
Traceback (most recent call last):
  File "/home/WorkSpace/11.0/odoo/service/server.py", line 867, in load_server_wide_modules
    odoo.modules.module.load_openerp_module(m)
  File "/home/WorkSpace/11.0/odoo/modules/module.py", line 368, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/home/WorkSpace/11.0/odoo/modules/module.py", line 82, in load_module
    exec(open(modfile, 'rb').read(), new_mod.__dict__)
  File "<string>", line 4, in <module>
  File "/home/WorkSpace/11.0/addons/web/controllers/__init__.py", line 4, in <module>
    from . import main, pivot
  File "/home/WorkSpace/11.0/addons/web/controllers/main.py", line 47, in <module>
    from odoo.service.report import exp_report, exp_report_get
ImportError: bad magic number in 'odoo.service.report': b'\x03\xf3\r\n'
`

**Comment by sswapnesh** [comment] 2018-03-22 14:39
Just resolved in 4787bc7553f31377822648d5f67de0a3bba0e0a2

**Comment by pedrobaeza** [comment] 2018-03-22 14:42
@MeetKD can you check again pulling latest branch?

**Comment by MeetKD** [comment] 2018-03-23 06:20
@pedrobaeza took latest pull and as @sswapnesh said its resolved in above mentioned commit. :+1:

**Closed** 2018-03-23 07:03 UTC
Labels: 11.0, Need information
