### ISSUE TITLE
[13.0] Survey: Error 403: Forbidden when Print Survey or Answers

### ISSUE THREAD

**Issue by jonatasartur** [odoo/odoo#54159] opened 2020-07-07 03:33 UTC
**Impacted versions:**
Odoo CE 13.0 Updated until 29/05/2020

**Steps to reproduce:**
1. Install Odoo 13 with [InstallScript](https://github.com/Yenthe666/InstallScript)
2. Create a Database
3. Install Survey Module
4. Create a Survey with Questions
5. Click on Print Button (Action_Print_Survey) or print the answers (Action_Print_Answers)

**Current behavior:**
Redirect to page:
```
403: Forbidden
A page you were looking for cannot be authorized.
```
**Expected behavior:**
Open the website page with the survey printable view

Has anyone had this problem or know what it could be?

**Comment by pedrobaeza** [comment] 2020-07-07 07:25
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by jonatasartur** [comment] 2020-07-07 20:35
Hi pedrobaeza, thanks for the answer. I found the same problem on Runbot.

Steps to reproduce:
1. On [Odoo 13 RunBot;](https://runbot.odoo.com/runbot)
2. Go to **Survey**;
3. Select any survey already created or create a new one;
4. In options select "**Scoring without answers at the end**";
5. Try to use the **print button** [_Print Button (Action_Print_Survey) or print the answers (Action_Print_Answers)_];
6. The print doesnt work and redirect to **403 page**.

Current behavior:
```
403: Forbidden
A page you were looking for cannot be authorized.
```

**Comment by pedrobaeza** [comment] 2020-07-08 06:50
OK, tagged

**Comment by Yenthe666** [comment] 2020-07-27 14:52
OPW `2307495`

**Comment by Yenthe666** [comment] 2020-08-06 06:42
Fixed in https://github.com/odoo/odoo/commit/3fcadce3de4a1cfd067b155dd746854065f4b452

**Closed by Yenthe666** 2020-08-06 06:42 UTC
Labels: 13.0, Confirmed, Marketing, OE
