### ISSUE TITLE
[v11/v12/master][base_automation] On Update Triggering Condition does not work with Property Fields

### ISSUE THREAD

**Issue by hbto** [odoo/odoo#26680] opened 2018-08-30 05:25 UTC
Impacted versions:
V11/master

Steps to reproduce:
https://drive.google.com/file/d/1Mjp3sUCTNtoFihLmAIwP3rtRSLpUerQT/view

Current behavior:
The one demonstrated in the Video

Expected behavior:
Updating a Property field do trigger an automated action with OnUpdate Trigger

**Comment by luisg123v** [comment] 2019-05-09 15:39
@hbto  
Could you edit the PR description to perform the following?:
- Specify this issue also affects 12.0
- Provide steps to reproduce

CC @tomeyro

**Comment by hbto** [comment] 2019-05-09 15:42
@luisg123v Steps are in the video.

**Comment by luisg123v** [comment] 2019-10-13 02:49
@hbto 
I tested this and it seems to work properly. In the steps you provided it doesn't, but it's because your automated action is set up to be triggered on the product category model, while it should be set to the property model (`ir.property`). That's because, when a property field is set/modified/unset, what actually happens back stage is an `ir.property` is created/updated/unlinked, respectively.

The only situation where the condition is not triggered, is when the field is unset, because properties are removed via SQL to avoid cache issues, but maybe that is unavoidable:
https://github.com/odoo/odoo/blob/50d302631a18d10e7e5a5c8394aa76d5a3811acb/odoo/addons/base/models/ir_property.py#L317-L321

CC @moylop260

**Comment by pedrobaeza** [comment] 2019-12-18 18:18
No further answer, so closing.

**Closed by pedrobaeza** 2019-12-18 18:18 UTC
Labels: 11.0, Framework, ORM
