### ISSUE TITLE
Odoo.sh report PDF version not showing/loading image/logo

### ISSUE THREAD

**Issue by odoo-mastercore** [odoo/odoo#21998] opened 2018-01-03 22:20 UTC
**Impacted versions**: Odoo 11.0+e on odoo.sh production environment

**Steps to reproduce**: 

Set Company logo and, 

Go to _Settings_ -> _Users & Companies_ -> _Companies_

then select Company and in the _Print_ menu: 

_Print_ -> _Preview External Report_

All Styles appears in the PDF report but logo don't.

**Current behavior**:

All Styles appears in the PDF report but logo don't.

**Expected behavior**:

PDF report with logo image.

Video/Screenshot link (optional): --

**Comment by Yenthe666** [comment] 2018-01-04 08:10
Hi @odoo-mastercore,

Thanks for the report.
When looking at the code it does exactly what it should though 
 (see https://github.com/odoo/odoo/blob/1df6f4c74151d012f9ff784cef6eea58a5ac3b9e/addons/web/views/report_templates.xml#L374-L391)
@mart-e or @sle-odoo could one of you confirm that this is absolutely not a bug and that this is default behaviour?

Regards,
Yenthe

**Comment by sle-odoo** [comment] 2018-01-04 09:58
maybe you're missing rev https://github.com/odoo/odoo/commit/1df6f4c74151d012f9ff784cef6eea58a5ac3b9e#diff-a48de36bdafe346387b4eb7347aa2144 ? try to upgrade base

**Comment by pedrobaeza** [comment] 2020-03-30 00:19
As no comment since long, closing this.

**Closed by pedrobaeza** 2020-03-30 00:19 UTC
Labels: 11.0

**Comment by Jeffabri** [comment] 2025-06-05 12:57
I've been stuck with the same issue for days, but the cause was something else.Default odoo uses non-patched wkhtmltopdf.This causes issues on newer systems.

The patched version on it's turn requires libssl1.1 (not libssl3), which is also not by default available in recent ubuntu server versions.

Steps to solve:

Remove current installation:
sudo apt remove --purge wkhtmltopdf

Download and install libssl1.1
wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.0g-2ubuntu4_amd64.deb
sudo dpkg -i libssl1.1_1.1.0g-2ubuntu4_amd64.deb

Download and install qkhtmltopdf (with patched Qt)wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.jammy_amd64.deb
sudo apt install ./wkhtmltox_0.12.6.1-2.jammy_amd64.deb

This solved it on my side!
