### ISSUE TITLE
[13.0] Error when Email and SMS marketing apps are installed from odoo github repository

### ISSUE THREAD

**Issue by Netsoro** [odoo/odoo#49947] opened 2020-04-22 09:49 UTC
Impacted versions:13.0

Steps to reproduce: 

1. git clone https://www.github.com/odoo/odoo --depth 1 --branch 13.0
2. install Sms marketing app (which install Email marketing app)
3. Click Email marketing in order to create Email campagne

Current behavior: After click on email/sms  marketing app the app crash with error, the full erreur log in joined file : erreur_log.txt

Erreur:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/zemafret/odoo/odoo/addons/base/models/ir_ui_view.py", line 662, in apply_inheritance_specs
    pre_locate=pre_locate)
  File "/opt/zemafret/odoo/odoo/tools/template_inheritance.py", line 230, in apply_inheritance_specs
    _("Element '%s' cannot be located in parent view") % tag
ValueError: L'élément '<xpath expr="//span[@name='failed_text']">' ne peut être localisé dans la vue parente

  File "/opt/zemafret/odoo/odoo/addons/base/models/ir_ui_view.py", line 612, in raise_view_error
    raise ValueError(message)
ValueError: L'élément '<xpath expr="//span[@name='failed_text']">' ne peut être localisé dans la vue parente

Contexte de l'erreur :
Vue `mailing.mailing.view.form.inherit.sms`
[view_id: 1365, xml_id: mass_mailing_sms.mailing_mailing_view_form_sms, model: mailing.mailing, parent_id: 1283]

But when you desinstall email marketing app or sms marketing app and let one of them the remained one will works correctly !

Expected behavior: to not crash and show Email/Sms marketing page.

But when i install these apps from https://www.odoo.com/fr_FR/page/download. 
They  behave correctly without any crash.

Video/Screenshot link (optional):

[erreur_log.txt](https://github.com/odoo/odoo/files/4515210/erreur_log.txt)

**Comment by pedrobaeza** [comment] 2020-04-22 13:39
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by sswapnesh** [comment] 2020-04-22 17:40
I could not reproduce this error on New database with only this Module installed.

I am able to open and create a new list.
![Screenshot from 2020-04-22 23-09-29](https://user-images.githubusercontent.com/16624719/80014730-56b4e500-84ee-11ea-87aa-66d4b74d1f38.png)

**Comment by sswapnesh** [comment] 2020-04-22 17:46
This is due to bad translation.

![screenshot-localhost_8069-2020 04 22-23_15_08](https://user-images.githubusercontent.com/16624719/80015313-2588e480-84ef-11ea-8f1c-62e78fc62150.png)
 
I think @Yenthe666 can fix it quickly

**Comment by Yenthe666** [comment] 2020-04-23 06:59
Hmm I don't have access to French but @mart-e can fix this quickly though!

**Comment by mart-e** [comment] 2020-04-23 07:11
Hi!,

I have fixed the problem on Transifex (will be in the next synchronisation), thanks for the report and analyzis !

@sswapnesh @Yenthe666 actually anyone can fix it, the Transifex teams are open and on runbot you even have the transifex button leading you to the right place.

![Screenshot_2020-04-23 Translated Terms - Odoo](https://user-images.githubusercontent.com/564822/80069704-18491580-8542-11ea-8649-8dd344268cae.png)

**Closed by mart-e** 2020-04-23 07:11 UTC
Labels: Need information

**Comment by Yenthe666** [comment] 2020-04-23 07:25
@mart-e no, you don't. They're only open if you are within a language its team. Eg French:
![image](https://user-images.githubusercontent.com/6352350/80071017-3879d400-8544-11ea-8c2e-42c4acd798ee.png)
to translate the message: "To be able to translate you should be logged in and should be a part of the French team".

You can see and do everything because you're an admin, we cannot do anything in another lang.

**Comment by mart-e** [comment] 2020-04-23 07:42
What I wanted to say is that you can join any team. Screenshots made with a new account with no priviledge :

![Screenshot_2020-04-23 The Odoo 13 0 translation project on Transifex](https://user-images.githubusercontent.com/564822/80071803-8ba05680-8545-11ea-97ce-67eb3db387fc.png)

![Screenshot_2020-04-23 The Odoo 13 0 translation project on Transifex2](https://user-images.githubusercontent.com/564822/80072361-6bbd6280-8546-11ea-8815-3d52c132fe82.png)

**Comment by Yenthe666** [comment] 2020-04-23 07:52
Cool, I didn't knew you could do that. Didn't it need approval in the past? Anyways good to know :)

**Comment by Netsoro** [comment] 2020-04-23 08:00
Hi,

Thank for your analysis it was happened when French language is activated.
