### ISSUE TITLE
www.odoo.com/forum: Unable to post new questions (403: Forbidden)

### ISSUE THREAD

**Issue by treviser** [odoo/odoo#15022] opened 2017-01-11 11:52 UTC
"403:Forbidden" is a daily companion when using Odoo's forum (editing, deleting, converting or adding posts or comments), but since some hours it hits when trying to post a new question. @Yenthe666 you may know whom to ping :-)

**Comment by JKE-be** [comment] 2017-01-11 15:30
Should be fixed now...
Thanks..

Error of 'Access read' on the new filter to avoid spam :-1:

**Closed by JKE-be** 2017-01-11 15:30 UTC

**Comment by treviser** [comment] 2017-01-11 17:02
@JKE-be The best antispam measure I've seen so far ;-)

**Comment by JKE-be** [comment] 2017-01-11 17:03
:postal_horn:

**Comment by aek** [comment] 2017-02-27 16:18
Hi @JKE-be @treviser 
This is happening again when you try to post an answer to a question

**Comment by JKE-be** [comment] 2017-02-28 10:29
Should be fixed (temporary removed automated action).
Seems a bug with automated action if not employee rights in saas-14... @mart-e is looking for a fix.

Thanks to you for the reporting, and to @mart-e  for the future fix ;)

**Comment by mart-e** [comment] 2017-02-28 10:40
@aek yes this was an issue with one of our own customization, not a bug on Odoo.
When reporting issues on github, you can check [on a runbot](http://runbot.odoo.com/runbot) if they are reproducible on a standard version.

**Comment by aek** [comment] 2017-02-28 14:24
@JKE-be and @mart-e 
Thanks to both of you guys, the thing is that this issue was old and solved but appear again yesterday on the Odoo Forum online, I won't create a new one, just add a comment here to let you know that something was affecting the Odoo Forum online.
I will check on runbot in the future, thanks again

**Comment by adrien3d** [comment] 2017-10-13 06:50
I think this is happening again when you try to post a new question on the forum.

**Comment by JKE-be** [comment] 2017-10-13 08:14
Hi

I have just tested now with a new user, and my own account, and both works as expected.

Are you sure that you don't try to post an external link or other things that text without enough karma?

**Comment by adriencombourieu** [comment] 2018-03-12 08:40
Hi, I have same problem now when posting a new question.
Been trying for a week !
Here
https://www.odoo.com/fr_FR/forum/aide-1/ask?post_type=question

EDIT :
I tried again, and by changing the formatting of my body text, it worked now !

**Comment by Yenthe666** [comment] 2018-03-12 08:50
@adriencombourieu Odoo recently upgraded the database to V11 and it still has some issues. This is a known issue at the moment. 😉

**Comment by rbuisson** [comment] 2019-04-10 06:48
Hi,
Having this annoying issue too for 2 days.
Tried with 2 different accounts, same result: 403 Forbidden

**Comment by JKE-be** [comment] 2019-04-10 06:59
@rbuisson 

It can arrive when you try to post img/url if you don't have enough karma.

Have you try to just post a question in pain text?

**Comment by rbuisson** [comment] 2019-04-10 07:08
Simple as that. Indeed I wanted to insert an image.
Thanks for the quick response @JKE-be

**Comment by celm1990** [comment] 2019-05-06 19:25
Hi, Today I wanted posted new question and get 403 Forbidden, any solution?

![image](https://user-images.githubusercontent.com/7775116/57249494-b6c72880-700a-11e9-94e1-b594ae285fb7.png)


![image](https://user-images.githubusercontent.com/7775116/57249504-be86cd00-700a-11e9-8845-0215b590ae05.png)
