### ISSUE TITLE
Filters Customer/Vendor wrong results

### ISSUE THREAD

**Issue by Ark74** [odoo/odoo#27822] opened 2018-10-16 05:32 UTC
**Impacted versions:**
* Odoo 10 CE
* Odoo 11 Runbot
* Odoo 12 Runbot

**Steps to reproduce:**

1. Setup Sales and/or Puchases along with Contacts module.
2. Setup customers and/or vendors contacts.
3. Filter by quick filter "Customer" or "Vendor"
4. Also test the advance filter: Is Customer -> true || Is Vendor -> true

**Current behavior:**

Filtered results are not the same.

![customers](https://user-images.githubusercontent.com/7444518/46994559-8fdeee80-d0da-11e8-83f5-0899baec1777.png)
![customers_true](https://user-images.githubusercontent.com/7444518/46994560-8fdeee80-d0da-11e8-97f7-c81496fcb835.png)
![vendors](https://user-images.githubusercontent.com/7444518/46994561-90778500-d0da-11e8-8f3d-0c57aae7b214.png)
![vendors_true](https://user-images.githubusercontent.com/7444518/46994562-90778500-d0da-11e8-8655-d3aa4b6941e6.png)

**Expected behavior:**
Both filter show all the results.

Am I missing something here? I mean, they must be the same, right?

**Video/Screenshot link (optional):**
Above

**Comment by pedrobaeza** [comment] 2018-10-16 07:32
That's the expected behavior, as the standard filters don't check only the value of that field, but intends to filter out children contacts. Look their definition:

https://github.com/odoo/odoo/blob/661483c026777fff4c6dd6ec245c991f7c4248ac/odoo/addons/base/views/res_partner_views.xml#L459-L460

Closing as no real issue, but intended behavior.

**Closed by pedrobaeza** 2018-10-16 07:32 UTC

**Comment by Ark74** [comment] 2018-10-16 07:49
Ohh! 
So that's the reason, sorry wasn't aware of it.

Thanks for the clarification.

**Comment by sswapnesh** [comment] 2018-10-17 19:41
@pedrobaeza I believe I  this Case filters (Records) should be same at both place.

**Comment by sswapnesh** [comment] 2018-10-17 19:44
Duplicate of https://github.com/odoo/odoo/issues/23533

**Comment by pedrobaeza** [comment] 2018-10-17 20:09
It's not a duplicate, as they are different things.
