### ISSUE TITLE
[10, 11, 12] Wrong Tax Calculation in case with inclusive in Price

### ISSUE THREAD

**Issue by bhaveshselarka** [odoo/odoo#28545] opened 2018-11-10 09:18 UTC
Impacted versions: v10, v11, v12

Steps to reproduce:
Need to define a group of tax (14.975) with child taxes like 5 % and 9.975 with inclusive in Price.

Current behavior:
Price unit: 100
subtotal: 86.60
5 % tax amount : 4.76
9.975 % tax amount: 8.64

Expected behavior:
Price unit: 100
subtotal: 86.98
5 % tax amount : 4.35
9.975 % tax amount: 8.68

Reference link for calculations: http://www.calculconversion.com/reverse-sales-tax-calculator-gst-qst.html

similar issue found but closed without solution: #5784

**Comment by sswapnesh** [comment] 2018-11-13 14:33
This can be solved only using python code in tax definition.
Ps. this was supposed to be solved in v12.

**Comment by sswapnesh** [comment] 2018-11-13 14:47
Duplicate of #25743 and #25770, 
However, You can use workaround given by @mga-odoo  in https://github.com/odoo/odoo/issues/25743#issuecomment-404850476

**Comment by bhaveshselarka** [comment] 2018-11-13 15:44
Hi @sswapnesh, 

Thanks for sharing this information, Yes I have solved this issue via this way only. But It should support natively not with a workaround solution.

This issue still persists in v12 as well. I think the mention version is major odoo versions so it will great to have fixed solution by native code functionality.

**Comment by Yenthe666** [comment] 2018-12-21 07:09
@bhaveshselarka if it is done against master it will not land in stable versions, so it most likely won't ever land in V10/V11/V12.

**Comment by sswapnesh** [comment] 2018-12-21 16:14
> Duplicate of #25743 and #25770,
> However, You can use workaround given by @mga-odoo in [#25743 (comment)](https://github.com/odoo/odoo/issues/25743#issuecomment-404850476)

@bhaveshselarka  Use python code for this (tax calculation) and it work will fine (But still it will be wrong base amount in report)

**Comment by oco-odoo** [comment] 2019-09-30 11:43
As already mentioned in the thread, it cannot be done in v10, 11, 12. It has however been done in saas-12.3, and works fine. v13 won't face this issue anymore :) I'm closing this thread.

**Closed by oco-odoo** 2019-09-30 11:43 UTC
Labels: 10.0, 11.0, 12.0, Accounting

**Comment by bhaveshselarka** [comment] 2019-12-26 16:15
@oco-odoo in v13 having the same issue again? 

as I found an odoo app on the app store for v13

https://www.odoo.com/apps/modules/13.0/price_inclusive_tax/

**Comment by oco-odoo** [comment] 2020-01-06 08:53
@bhaveshselarka Nope, v13 should work fine. I don't know what this module does, but it's probably wrong :/

**Comment by bhaveshselarka** [comment] 2020-01-06 09:08
Thanks for sharing information @oco-odoo.
