### ISSUE TITLE
[8.0/7.0/6.1...] name_get for taxes brings the incorrect field

### ISSUE THREAD

**Issue by pedrobaeza** [odoo/odoo#1805] opened 2014-08-16 14:16 UTC
In _account.tax_, we have two char fields: _name_ and _description_, with the labels _'Tax name'_ and _'Tax Code'_ respectively. Both are printed in the PDF in the tax section of the invoice, but only the _description_ field is shown in the interface when selecting taxes (for example, in the many2many field of the invoice line).

Due to these premises, in Spain we have put taxes data as shown:

| Tax Name  | Tax Code
----------- | --------
| SIVA21 | IVA 21%
| SIVA10 | IVA 10%
| PIVA10 | 10% IVA soportado (operaciones corrientes)
| PIVA21 | 21% IVA soportado (operaciones corrientes)
| ... | ...

In this way, we can have a short tax name that doesn't change a lot and allows some match operations like the ones done in [account_chart_update module](https://github.com/OCA/account-financial-tools/tree/7.0/account_chart_update), and when it appears on the printed invoice, the double value doesn't hurt anyone, but we keep the full name on the _Tax Code_ field, because when you search in the many2many fields, what you see is the tax code, not the tax name, and the other field is not descriptive enough for the average user.

The problem comes when you want to translate the tax name (hosted on the tax code field) when making international operations (for example, put '21% VAT'). The only translatable field is Tax Name, but with this approach, this doesn't serve. There are several solutions:

* Put _Tax Code_ field as translatable also.
* Change `name_get` method of account.tax to take the other field:

  ```
    def name_get(self, cr, uid, ids, context=None):
        res = []
        for record in self.read(cr, uid, ids, ['description', 'name'], context=context):
            name = record['name'] or record['description']
            res.append((record['id'], name))
        return res
  ```
  and we will adapt _l10n_es_ to this new condition.
* Put both fields in the name_get:

  ```
    def name_get(self, cr, uid, ids, context=None):
        res = []
        for record in self.read(cr, uid, ids, ['description', 'name'], context=context):
            name = record['name']
            if record['description']:
                name += " - " + record['description']
            res.append((record['id'], name))
        return res
  ```
  and we will also adapt _l10n_es_ to this new condition.

The first one implies less work and less side effects, but a combination of 1 and 3 is my favourite option.

**Comment by vjnunez** [comment] 2016-08-21 08:12
@pedrobaeza is this already solved? I just installed Odoo 8 for a client using the **spanish locale pack** and when selecting the tax type using the dropdown i can only see the codes (S_IVA21B), instead of the name (IVA 21% (Bienes).

Any solutions or workarounds?

**Comment by pedrobaeza** [comment] 2016-08-21 11:17
`name_get` was patched in the _l10n_es_ of the repo OCA/l10n-spain

**Comment by vjnunez** [comment] 2016-08-22 20:12
Hola Pedro, efectivamente vi el commit y el patch hace tiempo, pero por alguna razón, en el dropdown me salen los códigos. Los módulos se deben instalar en un orden específico? (estoy usando los últimos archivos de OCA/l10n-spain)

Muchas gracias por la respuesta.

**Comment by pedrobaeza** [comment] 2016-08-22 20:43
Víctor, don't answer here in Spanish. It should work if you put the correct priority on modules path. Please don't continue here your issue, as it's not related.

**Comment by qdp-odoo** [comment] 2016-08-25 13:16
ok so I suppose i can close this issue by now

**Closed by qdp-odoo** 2016-08-25 13:16 UTC

**Comment by DevNIX** [comment] 2017-01-23 20:24
I may be affected by this bug? I am customizing a Odoo 10 fresh installation...

![image](https://cloud.githubusercontent.com/assets/1777519/22221207/35b7c300-e1b2-11e6-9f5f-e15cc71ebd5b.png)

**Comment by rmatcar** [comment] 2017-01-28 21:33
Hi @DevNIX 
Do you fix the issue? I have the sae problem :-(

On pos.xml, I know that I must change the following line, but I don't know which is the correct field instead .name

<td><t t-esc="taxdetail.name" /></td>

**Comment by DevNIX** [comment] 2017-01-30 10:26
No, I'm just introducing myself to Odoo, and I'm still not into customization/development.

I feel that the problem is the name of the tax just in Spanish language, and not a template issue...

**Comment by albertedevigo** [comment] 2018-01-25 17:33
Same error here on an Odoo 11 installation. Should this issue be reopened? @qdp-odoo 
![image](https://user-images.githubusercontent.com/7793176/35402900-3938e8de-01fe-11e8-9c6d-05649c2f316c.png)
