### ISSUE TITLE
Account>sales>customer statement.

### ISSUE THREAD

**Issue by Gitnav4790** [odoo/odoo#26492] opened 2018-08-21 12:01 UTC
Impacted versions:11.00 EE

Steps to reproduce: Accounting > sales> customer statement give trace back for followup

Current behavior:trace {Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_qweb/qweb.py", line 341, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_account_reports_template_followup_report_3048
  File "/odoo/enterprise/addons/account_reports_followup/models/account_followup.py", line 147, in get_partners_in_need_of_action_and_update
    elif result[partner_id][1] < delay:
TypeError: unorderable types: NoneType() < NoneType()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 930, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/lin-haw/report_partner_filter/models/account_followup_report.py", line 32, in get_report_informations
    informations = super(AccountReportFollowupAll, self).get_report_informations(options)
  File "/odoo/enterprise/addons/account_reports/models/account_followup_report.py", line 285, in get_report_informations
    informations = super(account_report_followup_all, self).get_report_informations(options)
  File "/odoo/lin-haw/report_partner_filter/models/account_partner_ledger.py", line 101, in get_report_informations
    'main_html': self.get_html(options),
  File "/odoo/enterprise/addons/account_reports/models/account_followup_report.py", line 156, in get_html
    return super(report_account_followup_report, self).get_html(options, line_id=line_id, additional_context=additional_context)
  File "/odoo/enterprise/addons/account_reports/models/account_report.py", line 424, in get_html
    values=dict(rcontext),
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_ui_view.py", line 1158, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/odoo/odoo-server/addons/website/models/ir_ui_view.py", line 113, in render
    return super(View, self).render(values, engine=engine)
  File "/odoo/odoo-server/addons/web_editor/models/ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_ui_view.py", line 1167, in render
    return self.env[engine].render(self.id, qcontext)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 57, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_qweb/qweb.py", line 271, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_qweb/qweb.py", line 343, in _compiled_fn
    raise e
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_qweb/qweb.py", line 341, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_2300_3026
  File "<template>", line 2, in foreach_3024
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_qweb/qweb.py", line 348, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.ir.ir_qweb.qweb.QWebException: unorderable types: NoneType() < NoneType()
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_qweb/qweb.py", line 341, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_account_reports_template_followup_report_3048
  File "/odoo/enterprise/addons/account_reports_followup/models/account_followup.py", line 147, in get_partners_in_need_of_action_and_update
    elif result[partner_id][1] < delay:
TypeError: unorderable types: NoneType() < NoneType()

Error to render compiling AST
TypeError: unorderable types: NoneType() < NoneType()
Template: account_reports.template_followup_report
Path: /templates/t/div[1]
Node: <div class="alert alert-warning o_account_reports_followup-no-action" id="no-action" role="alert" t-if="partner != False and partner.id not in partner.get_partners_in_need_of_action_and_update().keys() and context.get('print_mode') != True">
            <p><strong>Warning!</strong> No action needs to be taken for this partner. <a t-if="(partner.payment_next_action_date or '') &gt; today" class="o_account_reports_followup-auto">Put back in the list</a></p>
        </div>
}

Expected behavior:should show statement of customers

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/34165842/44400144-c7f90380-a567-11e8-84b9-391bb18d5f3c.png)

**Comment by sswapnesh** [comment] 2018-08-21 16:53
Looks like it is from custom module `report_partner_filter`.

**Comment by pedrobaeza** [comment] 2018-08-21 17:19
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-08-21 17:19 UTC
Labels: 11.0, Accounting

**Comment by mga-odoo** [comment] 2018-08-21 17:36
I believe you have installed the custom application `report_partner_filter` as you would like to print the ledger for the specific partner.

you can still do the same without any custom application go through video available at https://odoobooks.com/en/latest/accounting/print_customer_ledger.html
