### ISSUE TITLE
Can't save custom model's field in account.move.line

### ISSUE THREAD

**Issue by Hamza-Talibi** [odoo/odoo#40751] opened 2019-11-23 22:35 UTC
Impacted versions:
13.0
Steps to reproduce:
At Odoo runbot:
Create new model
Add a Many2one field with custom model in account.move.line
Fill the field
Save The invoice
Current behavior:
The field hasn't saved
Expected behavior:
The many2one field saved

Video/Screenshot link (optional):

![move_line_custom_field](https://user-images.githubusercontent.com/25642031/69486227-e2e0b480-0e49-11ea-8530-d4e0f2cd1b02.gif)

**Comment by pedrobaeza** [comment] 2019-11-24 01:49
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2019-11-24 01:49 UTC

**Comment by Hamza-Talibi** [comment] 2019-11-24 18:31
Hello @pedrobaeza ,

I reproduced this bug on odoo runbot:
In odoo runbot, I've created a new model, with their access right.
I 've created a new many2one field in account.move.line related to this new model.
I've created a new invoice and I've added a invoice line, I've filled this field, saving the invoice, the data of this new field can't be saved.
Attached you fill find my test in odoo runbot.
![move_line_custom_field](https://user-images.githubusercontent.com/25642031/69499315-fa26ad00-0ef0-11ea-9a7a-656a37e01d10.gif)


Best regards

**Comment by pedrobaeza** [comment] 2019-11-24 22:19
The question is that you are doing a modification in the standard, and thus that may require extra code like this special case for the invoice/move duality, so you should add that code for making it work, but it's not an Odoo issue itself.

**Comment by implementosk** [comment] 2020-09-01 14:56
Hello,

Have the same issue.
And i think it is an Odoo issue, because it happens also when you create a new field on account.move.line model with **Odoo Studio**.

Thanks.

**Comment by pedrobaeza** [comment] 2020-09-01 15:35
Check how it's done in core. I remember it needs to be added to several views for working.

**Comment by anandkansagra** [comment] 2020-11-12 09:48
We can do that using the following things.

```
<xpath expr="//field[@name='invoice_line_ids']/tree/field[@name='company_id']" position="after">
        <field name="customfield"/>
</xpath>
<xpath expr="//field[@name='line_ids']/tree/field[@name='company_id']" position="after">
        <field name="customfield"/>
</xpath>
```
