### ISSUE TITLE
[12.0] [13.0] [14.0] Odoo wrongfully mimics sender’s e-mail address in notifications

### ISSUE THREAD

**Issue by ossimantylahti** [odoo/odoo#66575] opened 2021-02-20 00:22 UTC
When an external user generates an event that causes a notification in Odoo business object the system sends a notification for followers using recipient’s e-mail domain mimicking recipients e-mail address. This is incorrect functionality. Odoo should not send message with MAIL FROM the e-mail address who caused the notification if the one who caused the notification is an external e-mail address.

Typical case for external users to cause notification events is when a client comments on a quote. 

**Impacted versions:**
12.0, 13.0, 14.0 CE and EE equally

**Steps to reproduce:**
1.	Create a user account for Odoo: admin@myserver.com
2.	Create a partner in odoo: client-test@gmail.com
3.	Send quote from Odoo to client-test@gmail.com
4.	Add follower to the order: follower-test@gmail.com 
5.	Without being logged in to Odoo, open client-test’s e-mail box and click on quote’s “review and sign order”
6.	This will open the quote on Odoo server’s website
7.	Write a comment on Feedback field
8.	Odoo now sends a notification to admin@myserver.com and follower-test@gmail.com
9.	The MAIL FROM of this notification message is client-test@gmail.com. Odoo tries to send mail in behalf of whoever caused the notification without considering if this e-mail user is an Odoo user.
10.	Gmail intercepts the message being from a fraudulent source. This is natural. The myodooserver.com is not authorized to send messages on behalf of my clients e-mail addresses.

This is also a business critical issue. This functionality as currently implemented has a negative impact on the myodooserver.com’s reputation.

**Current behavior:**
Odoo sends emails coming from whoever generated the notification. If it is a client john.doe@veryimportantclient who wrote a comment on a quote, an e-mail notification will be gererated as MAIL FROM john.doe@veryimportantclient.com

Expected behavior:
Odoo should not sent the MAIL FROM field as whoever caused the notification. 

Instead Odoo should first verify if the generated address belongs to one of Odoo’s users. If not, Odoo should send the message from a common myodooserver.com address. (Perhaps catchall@odooserver.com so possible replies can be intercepted).

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/37711285/108575055-ac107d00-72de-11eb-99e5-966376667407.png)

![image](https://user-images.githubusercontent.com/37711285/108575058-afa40400-72de-11eb-9c3c-baaac3800269.png)

![image](https://user-images.githubusercontent.com/37711285/108575066-b3378b00-72de-11eb-90ec-753065ab7c17.png)

This functionality has been verified on Runbot on 19th Feb 2021.

**Comment by jusle** [comment] 2021-02-20 00:36
Hello

I have confirmed the issue on all supported Odoo versions, and have to build a special SMTP relay to support the mail implementation in Odoo which IMHO is not compatible with any industry or law requirement or standard. Odoo should send the mail from a SMTP server which domain properly supports DKIM and SPF.

**Comment by jusle** [comment] 2021-02-20 01:20
Or instead of catchall with a fixed address, maybe an alias could be created with the following logic: If outgoing mail address is else than mail.catchall.domain, parse sender mail address and create user alias useraddress@mail.catchall.domain.

**Comment by mvaled** [comment] 2021-02-20 15:11
This has been known for quite a while. See https://github.com/odoo/odoo/issues/5864 and https://github.com/odoo/odoo/issues/3347.

**Comment by ossimantylahti** [comment] 2021-02-20 23:28
Simplest fix really would be if Odoo were to send notifications always as MAIL FROM catchall@mail.catchall.domain (for example catchall@myodooserver.com).

**Comment by jcBalmes92** [comment] 2021-02-21 03:28
> Simplest fix really would be if Odoo were to send notifications always as MAIL FROM [catchall@mail.catchall.domain](mailto:catchall@mail.catchall.domain) (for example [catchall@myodooserver.com](mailto:catchall@myodooserver.com)).

I agree with @ossimantylahti 

Although sending notifications from catchall@mail.catchall.domain should only happen if from_mail.split('@')[1] != alias_domain

**Comment by vantran-novobi** [comment] 2021-02-21 10:03
Hi guys

I agree with using an internal email which is accepted in the SMTP whitelist to go throw, to send the notification emails to followers of the record in Odoo, but still keep the customer email name. The Email From should be "Client Name <erp@myodoo.com>".

But, remember that we also have the multi companies feature so that the company may have multiple domain for each company branch. So that, we can not use the catchall email (the combination in System Parameters) as the Email From.
I suggest that we should create a new fields as a configuration in company level and get the Email From for the notification emails from company level.

Btw, regarding the limited use of System Parameters, the web.base.url as well as Alias email can not supports multi companies feature. But that's another issue and we can discuss in another thread.

Best,
Van

**Comment by andrewdhastings** [comment] 2021-02-21 22:28
I have a basic fix developed for this because AWS will not send emails from domains that you don't have configured. The module lets you pick an email address to use for notifications and then you can have a list of allowed domains. Any notification that Odoo tries to send that is not in the allowed domain list is updated to use the provided email address. 

The final formatting for updated emails looks like:

<[Customer Name] via Admin> admin@alloweddomain.com 

If you are needing a solution right away, let me know. I can probably add the module to Odoo.com/apps too.

**Comment by gdgellatly** [comment] 2021-02-22 06:50
In general most experienced partners won't use the default Odoo SMTP anyway in last 5 or 6 years because of all its issues, not just compliance. A localhost postfix relay with SRS rewriting, multi domain support etc etc which takes all of 10 minutes to setup always resolved all the issues and has added benefit of being pluggable so you can use for example mailhog in test. Odoo has a few of these basically implemented features more for ease of initial use/demo use than production.  

Expecting a standards compliant SMTP implementation from your ERP is maybe asking a bit too much, especially with how surprisingly fast the bolt on standards evolve. Honestly, I'd almost prefer time wasn't wasted fixing it, but rather spent in documentation for production ready mail.

**Comment by ossimantylahti** [comment] 2021-02-22 07:34
> Expecting a standards compliant SMTP implementation from your ERP is maybe asking a bit too much,

I do not think that anyone is asking Odoo to implement its own SMTP server. And as far as I know, Odoo does not have SMTP server. Odoo **connects** to an SMTP server and when sending message uses incorrect MAIL FROM field.

**Comment by pedrobaeza** [comment] 2021-02-22 07:49
The question is clear as explained by Graeme, and, believe or not, it's a deployment issue: you need to provide in your stack a mail relay with SRS if you want to avoid such things, but not relaying in Odoo for that, the same you attach an inverse proxy for SSL connection and don't expect Odoo to do it. Closing thus.

**Closed by pedrobaeza** 2021-02-22 07:49 UTC

**Comment by ossimantylahti** [comment] 2021-02-22 08:13
@pedrobaeza A mail relay won't help at all. Any mail relay worth of its salt (Amazon, Azure etc.) would simply reject the messages because they do not accept the incorrect MAIL FROM header. 

Current Odoo implementation is simply wrong. Odoo should have no business in sending messages in behalf of client@clientdomain.com ("mail from client@clientdomain.com"). 

Please do not close the issue. This is a real bug.

**Comment by pedrobaeza** [comment] 2021-02-22 08:15
As said, local mail relay with SRS.

**Comment by ap-wtioit** [comment] 2021-02-22 09:23
For those researching the topic (e.g. me in the future ;-) ), there was a talk for this on Odoo Experience 2019:
How to Handle Your Email Environment with Odoo
https://www.youtube.com/watch?v=emLnLw2XliI&list=PL1-aSABtP6AD0n2NWnXRX6h1f7n7NyiMF&index=34

**Comment by pedrobaeza** [comment] 2021-02-22 09:36
Note that Doodba (https://github.com/Tecnativa/doodba) as deployment method is already bundling the mail relay with SRS.

**Comment by gdgellatly** [comment] 2021-02-22 09:40
> > Expecting a standards compliant SMTP implementation from your ERP is maybe asking a bit too much,
> 
> I do not think that anyone is asking Odoo to implement its own SMTP server. And as far as I know, Odoo does not have SMTP server. Odoo **connects** to an SMTP server and when sending message uses incorrect MAIL FROM field.

@ossimantylahti Its semantics really. I get what you are saying, but really it's not worth arguing, not 5 years ago and not today. For you this is a new issue, if you hunt back you will find at least 2 PR's to address some of it that just go nowhere. It is just easier to accept Odoo doesn't send modern public SMTP server compliant emails and probably never will and just stick a relay in the middle to deal with the crap. It performs better too.

**Comment by ossimantylahti** [comment] 2021-02-22 09:47
I am trying to form understanding of the proposed solution… So essentially you are saying that Odoo setup should always be done with a local server postfix SMTP server installation and the system administrator should implement SRS (Sender Rewriting Scheme). SRS in turn would then change outgoing emails’ MAIL FROM and Return-path envelope fields.

If I understood correctly the postfix SRS configuration, you would need to configure manually all addresses that would be excluded from rewriting. Ok, another point for the to-do list when setting up a server. (Just wondering what happens with DKIM signing and would the return-path be the catchall address?).

Granted. Technically this would work. But then what is the point of having outgoing mail servers in Odoo Settings – Technical – Outgoing mail servers configuration, if the correct way of setup is to have always a local mail server with SRS rewriting? I am pretty certain that 90+% of world’s Odoo installations do not implement outgoing mail in this manner. Including Odoo.sh – it is not implementing SRS. In fact, the example messages in the original Issue are from Odoo.sh

If this is really the correct and recommended way of setting up an Odoo server, it should at least be documented very well. And probably included in the most common installation scripts (like @Yenthe666  's great scripts ).

**Comment by pedrobaeza** [comment] 2021-02-22 09:56
The SRS is set by accepted (canonical) domains. The rest of the domains will be "masked" by the SRS. That's the typical configuration of an SRS system.

The aim of having several outgoing servers is for mass mailing, where you can use a specific outgoing server for that purpose (and can be selected in the mass mailing record itself).

About the documentation, you can propose a pull request adding such pieces of information in the documentation.

**Comment by gdgellatly** [comment] 2021-02-22 09:57
@ossimantylahti I'm not saying anyone has to do anything. I'm just saying what works for me and I was guided by people who know what they are doing. 

You don't need to do manual configuration of all addresses in postfix. You just need to configure canonical domains, allowed domains etc. The return path is always the catchall anyway, that doesn't change AFAIK relying on the X header for routing (another issue, another day).

As for the Odoo outgoing mail servers config, I very rarely use it, just rely on localhost:25 in conf file. Even before DMARC, DKIM was an issue, local relays were first suggested to me in 2012 and in very common use just simply for the connection speed to Odoo offloading the mail. 

As for anybodys scripts, I wouldn't know about that.

**Comment by ossimantylahti** [comment] 2021-02-22 11:19
It seems that someone in the OCA disagrees with the proposed solution of SRS in Postfix. There is already a module which fixes this functionality:
https://github.com/OCA/social/blob/13.0/mail_outbound_static/README.rst

"This module brings Odoo outbound emails in to strict compliance with RFC-2822 by allowing for a dynamically configured From header, with the sender's e-mail being appended into the proper Sender header instead."

Maybe this module could be merged to main Odoo branch?

**Comment by pedrobaeza** [comment] 2021-02-22 11:22
Of course people can take different approaches to this, but that module has another drawbacks that I'm not going to explain here, so choose your favorite solution. This won't be integrated in core (although I'm not from Odoo stuff, but I'm pretty sure) due to that drawbacks and to force to use such approach.

**Comment by jusle** [comment] 2021-02-22 11:45
> The question is clear as explained by Graeme, and, believe or not, it's a deployment issue: you need to provide in your stack a mail relay with SRS if you want to avoid such things, but not relaying in Odoo for that, the same you attach an inverse proxy for SSL connection and don't expect Odoo to do it. Closing thus.

Hello

I understand Odoo's point of view. But, there is no documentation available for configuring Postfix SRS for Odoo deployment in the official docs (https://www.odoo.com/documentation/14.0/setup/deploy.html), and the default behaviour in Odoo makes the system a email spamming/spoofing machine, without user knowing it. Thus, I think this should be considered as a issue or bug.

Ultimately the best solution would be to look at what OCA has done and implement the same concept for Odoo core standard: https://github.com/OCA/social/tree/13.0/mail_outbound_static

Odoo should at least document the behaviour of Odoo in the deployment guide, including, how to deploy Odoo so that it is compatible with the rest of the world, for example with a a new section "Postfix".

Because the same fault occurs on Odoo's own hosting systems (confirmed on Odoo.sh, Odoo Online), the spamming/spoofing implementation seems to be the official way that Odoo supports which means Odoo's online services, and Odoo on-premise without a custom module or Postfix SRS, cannot be used for any business who want's to send emails for example to customers or suppliers on external domains (a very common use case ;)).

**Comment by pedrobaeza** [comment] 2021-02-22 11:50
If you want that to be documented, make a pull request with that part. You demand a lot from others, but don't contribute your part.

**Comment by ossimantylahti** [comment] 2021-02-22 11:53
> Because the same fault occurs on Odoo's own hosting systems (confirmed on Odoo.sh, Odoo Online), the spamming/spoofing implementation seems to be the official way that Odoo supports which means Odoo's online services, and Odoo on-premise without a custom module or Postfix SRS, cannot be used for any business who want's to send emails for example to customers or suppliers on external domains (a very common use case ;)).

Agree with @jusle . 

We should also keep in mind that Odoo is available in multiple platforms. There _are_ people running Odoo for example on Windows servers and it is not possible to implement Postfix on Windows. This is also quite an issue if you are trying to use Odoo with Azure or Amazon mail transfer agents.

By the way, is this issue only coming up when there are notifications triggering from outside users? If so, implementing the proposed postfix SRS relay would be quite a burden. It is essentially a workaround for the fact that Odoo is breaking compatibility with RFC-2822.

I would certainly be happy to contribute. Just don't close the bug as this is a real issue.

**Comment by pedrobaeza** [comment] 2021-02-22 11:58
Keeping the issue opened won't mean anything different.

**Comment by jusle** [comment] 2021-02-22 11:58
> If you want that to be documented, make a pull request with that part. You demand a lot from others, but don't contribute your part.

Thanks for the tip! I will.

I am just trying to say there is a design fault. And what I have now done is testing, validation, reporting and trying to find a workaround.

**Comment by jusle** [comment] 2021-02-22 12:15
> By the way, is this issue only coming up when there are notifications triggering from outside users? If so, implementing the proposed postfix SRS relay would be quite a burden. It is essentially a workaround for the fact that Odoo is breaking compatibility with RFC-2822.

All messages from external domains delivered to Odoo business object, are, by default, spoofed and routed to other followers in the business object, from the external domain address.

**Comment by ossimantylahti** [comment] 2021-02-22 12:22
> Of course people can take different approaches to this, but that module has another drawbacks that I'm not going to explain here, so choose your favorite solution. This won't be integrated in core (although I'm not from Odoo stuff, but I'm pretty sure) due to that drawbacks and to force to use such approach.

Pedro, where would be more appropriate forum to discuss the drawbacks of this OCA module and its design? So far what I studied the module does exactly what it is supposed to do. I would like to understand what are its problems.

**Comment by pedrobaeza** [comment] 2021-02-22 12:28
If it's OK for you, then install it. If not, discuss it in OCA.

**Comment by ossimantylahti** [comment] 2021-02-22 13:11
@pedrobaeza I'm not looking for just one-time fix for one client. I am suggesting merging this OCA module for the main version. If there is a problem with this approach, I'd like to understand what seems to be the issue.

**Comment by llacroix** [comment] 2021-02-22 17:04
> As said, local mail relay with SRS.

Nice workaround you have there... But please don't call it a solution when it's nothing more than a hack. If Odoo was compliant with SMTP or implemented the correct behaviour, there wouldn't be need for an external mail relay.

**Comment by Yenthe666** [comment] 2021-02-22 17:06
I honestly agree it is not the greatest thing in Odoo. Perhaps @tde-banana-odoo can shed a light on this one (and on the roadmap for V15 about email)

**Comment by pedrobaeza** [comment] 2021-02-22 17:08
I don't think it's a workaround. SRS is something standard as well.

**Comment by jcBalmes92** [comment] 2021-02-22 17:17
> But, remember that we also have the multi companies feature so that the company may have multiple domain for each company branch. So that, we can not use the catchall email (the combination in System Parameters) as the Email From.

@vantran-novobi, as far as I know, Odoo only accepts one domain even when using multi-company. That been said, creating new fields might complicate things.

**Comment by andrewdhastings** [comment] 2021-02-22 17:54
I also agree that this is a Odoo bug/issue. I get that the deployment for emails will greatly very based on needs. However, I don't believe any software should be designed so that it violates basic email standards out of the box. 

I'm no email expert, but this one issue has caused significant problems for many of my clients. It is such a simple fix that could be deployed by Odoo in less then 100 lines of code and then none of us have to waste resources making hacks to fix such basic issues. Odoo is already time consuming to deploy, why are we adding more things to worry about?

**Comment by ossimantylahti** [comment] 2021-02-23 03:19
> this one issue has caused significant problems for many of my clients. It is such a simple fix that could be deployed by Odoo in less then 100 lines of code and then none of us have to waste resources making hacks to fix such basic issues. Odoo is already time consuming to deploy, why are we adding more things to worry about?

Fully agree with @andrewdhastings . **There is a a clear standard (RFC 2822). Odoo violates this standard.** So this **is** a bug and / or design fault. Postfix solution is a workaround, rather complex to implement, not compatible with other platforms (i.e. systems where postfix is not available) and real world deployment shows that almost no-one (including Odoo Online and Odoo.sh) do not implent it.

A solution wound not be that difficult. Technically a solution would be less than 100 lines of code. And even better: the OCA module has a decent solution. In my opinion it should be merged to the main code base.

**Comment by ap-wtioit** [comment] 2021-02-23 07:52
@ossimantylahti the [RFC 2822](https://tools.ietf.org/html/rfc2822#section-3.6.2) compliance depends how you interpret the "author" of the message. Odoo is still compliant to RFC2822 (the author is the user client-test@gmail.com, the sender is odoo (see 3.6.2 the example with the secretary sending the message for another person)) if it declares the sender as well as the from.

**Comment by gdgellatly** [comment] 2021-02-23 08:50
@ap-wtioit actually @ossimantylahti is correct, Odoo does violate the standard as it is quite specific IRT to mailing lists. However they have already stated repeatedly it won't be fixed as it is a feature not a bug.

However @ossimantylahti I think you misunderstand OCA and Odoo. OCA doesn't have the legal rights to gift code to Odoo, and nor would Odoo want it even if it was the solution. 

I know this may seem like a brick wall, we've just all gone down this road before. Perhaps some history will enlighten you somewhat https://github.com/odoo/odoo/issues/3347 - there are plenty of others if you look in the intervening 7 years since then.

**Comment by ossimantylahti** [comment] 2021-02-23 22:19
It seems that a permanent fix is in the development. When 61853 gets implemented, there is no longer need for Postfix hack.

https://github.com/odoo/odoo/pull/61853

**Comment by ap-wtioit** [comment] 2021-02-24 06:58
"4. If no notifications email is configured or if no mail server are
found for the notifications email, fallback to the old system and
spoof the FROM header. In that case we do not have the choice if we
want to send the email, he will probably be marked as spam."

It seems they still plan the old behaviour for partners that don't have an account.

**Comment by Yenthe666** [comment] 2021-02-24 07:52
"So we will be able to configure SMTP relay (on Office 365 e.g.) based on an SSL certificate instead of an hard-coded IP address."
Thank god, finally.

**Comment by jjscarafia** [comment] 2021-02-24 12:45
If I'm not wrong, some of what is being done on https://github.com/odoo/odoo/pull/61853 is what we've done [here](https://github.com/OCA/social/pull/598). Just in case it helps someone till odoo improvement is merged

**Comment by tde-banana-odoo** [comment] 2021-03-01 09:01
As pointed out, indeed we are working on this issue with @std-odoo :) . It is still under validation but we plan to merge it quite soon in order to finally stop spoofing emails.

**Comment by ossimantylahti** [comment] 2021-05-19 15:27
It seems that the merge is taking place.

https://github.com/odoo/odoo/pull/70854

**Comment by tde-banana-odoo** [comment] 2021-09-02 08:30
And for (v15) see https://github.com/odoo/odoo/pull/61853 .

**Comment by source-promo** [comment] 2022-10-31 10:40
@tde-banana-odoo was this not fixed / implemented in Odoo 15? 
We just experienced this issue on V15 running on Oodo.sh again

**Comment by ossimantylahti** [comment] 2023-01-27 21:56
> Please also see #69218 and the use of the system parameters: mail.force.smtp.from and mail.dynamic.smtp.from in cooperation with mail.catchall.domain

Just to note for documentation purposes: the parameters are not `mail.force.smtp.from` and `mail.dynamic.smtp.from`. The parameters in question are `mail.default.from_filter` and `mail.default.from`. The parameters .force.smtp.from and dynamic.smtp.from are not documented to do anything.

Odoo's own admin documentation:
[https://www.odoo.com/documentation/16.0/applications/general/email_communication/email_domain.html](https://www.odoo.com/documentation/16.0/applications/general/email_communication/email_domain.html)

**Comment by ray-odoo** [comment] 2023-01-27 22:53
Correct - we changed the names of the parameters!

**Comment by lesiakj** [comment] 2024-01-04 09:13
Guys I need your help. I already installed OCA module "Mail Outbound Static" to my Odoo instance and unfortunately, when I want to open existing or create new Outgoing Mail Server I got a error:
UncaughtPromiseError > OwlError
Uncaught Promise > The following error occurred in onWillStart: ""ir.mail_server"."domain_whitelist" field is undefined."
OwlError: The following error occurred in onWillStart: ""ir.mail_server"."domain_whitelist" field is undefined."
...
Could someone give me a hint how to solve it? I try to uninstall the module but it was not helped :(

**Comment by ossimantylahti** [comment] 2024-01-04 10:08
@lesiakj Sounds like the problem is with that OCA module. OCA modules unfortunately are often not very mature. In this case domain_whitelist is defined in https://github.com/OCA/social/blob/16.0/mail_outbound_static/models/ir_mail_server.py

You would need to restore a database backup to get rid of it.

In any case this module is no longer needed as with the latest changes Odoo core is already compliant with RFC-2822.

**Comment by pedrobaeza** [comment] 2024-01-04 14:57
@ossimantylahti I don't agree with your statement: "OCA modules unfortunately are often not very mature". Most of the OCA modules have more quality than the rest of the modules you find in Odoo Apps store. Anyway, there's a declared status (Alpha, Beta, Production/Stable, Mature) for knowing also this level (although most of the beta modules are actually stable).

In this case, the problem seems to be the installation of the module, not a problem in the module itself. It seems that @lesiakj has tried to import the module via the menu option (which is only for data modules, and I hate that Odoo includes this that confuse every new user), or maybe added the module without restarting the server, or other similar issue, but I insist, it's not a problem of the OCA module.

**Comment by lesiakj** [comment] 2024-01-04 16:23
> ...It seems that @lesiakj has tried to import the module via the menu option (which is only for data modules, and I hate that Odoo includes this that confuse every new user), or maybe added the module without restarting the server...

Indeed - Im new in Odoo and didn't know I can't use "import module" for custom scripts :( In addition I have online version of Odoo so also I can't restart the server.  
If someone from OCA read it - would be great to mentions such things in module description or add disclaimer for newbie users ;)
If there is no possibility to fix it (e.g. add missing fields) the only way will be to restore database from backup. I hope Odoo can help here because for online instance - If Im not mistake - I do not have option to restore DB.

**Comment by lesiakj** [comment] 2024-01-04 16:28
Guys, I contacted directly with Odoo support and they help me to fix the issue. Here is the solution:
•	Activate the Developer Mode
•	Go to Settings
•	Select Views from the Technical menu
•	Search  IR Mail Server - From Address 
•	Click on the three check boxes beside the name of each view
•	Click on the gear button   Action
•	Select Archive
After these steps, your Mail Servers will be accessible again.

**Comment by pedrobaeza** [comment] 2024-01-04 16:54
All of these things are not related to modules, but Odoo ecosystem/background.

Sorry, you can't put in any of the 3000 OCA modules 10 pages of things "you should know before using this module". Don't make me wrong, I don't want to be rude, but it's not something that you can blame to any of the OCA contributors, nor the suggestion is feasible, because you have this problem, but others can have another deployment problem due to their own decisions, so it's impossible to cover all these things.

Anyway, the main initial guilty here is Odoo for adding that option that confuses all users. It's true that they warn very well about its usage:

![imagen](https://github.com/odoo/odoo/assets/7165771/032b1098-eb42-4af8-83e2-a1aeeba7a074)

but as proved, people don't read. Forbidding to import the module if it contains code would be the desirable behavior.

Using Odoo online, you can't put any extra module (except data ones, which are only website themes mostly).
