### ISSUE TITLE
Not able to update Quantity of a Lot

### ISSUE THREAD

**Issue by shubham805** [odoo/odoo#55964] opened 2020-08-15 13:24 UTC
Impacted versions:

Steps to reproduce:

Current behavior:
Unit is getting edited
Expected behavior:
I should be able to edit Quantity
Video/Screenshot link (optional):

![Screenshot 2020-08-15 at 6 49 56 PM](https://user-images.githubusercontent.com/16641688/90313248-9d5c9e00-df28-11ea-8772-51c69678d68e.png)

**Comment by sswapnesh** [comment] 2020-08-15 15:46
Because Package is selected.

**Comment by pedrobaeza** [comment] 2020-08-15 16:40
That's it, so closing for now as this is not a bug.

**Closed by pedrobaeza** 2020-08-15 16:40 UTC
