### ISSUE TITLE
[14]: Web Editor: error when using "Dynamic Products" block

### ISSUE THREAD

**Issue by smonv** [odoo/odoo#69161] opened 2021-04-13 10:10 UTC
Impacted versions: 14

Steps to reproduce:
- On Website, click edit
- Drag "Dynamic Products" block to web page

Current behavior:
- Show XML parsing error

Expected behavior:
- Display products

Video/Screenshot link (optional):
<img width="975" alt="Screen Shot 2021-04-13 at 17 09 31" src="https://user-images.githubusercontent.com/8962973/114536210-0c86bf80-9c7b-11eb-84c5-b668e4b57e00.png">

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment] 2021-04-13 10:16
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by sswapnesh** [comment] 2021-04-13 16:13
Seems working well on Runbot

**Closed** 2023-06-14 16:11 UTC
Labels: Need information
