### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by aitalinassim** [odoo/odoo#28075] opened 2018-10-23 14:30 UTC
Impacted versions: Odoo 12

Steps to reproduce: logout and login again

Current behavior: Error shows

Uncaught TypeError: Cannot read property 'display' of undefined
http://ubuntuserver:8069/calendar/static/src/js/base_calendar.js:76
Retraçage :
TypeError: Cannot read property 'display' of undefined
    at http://ubuntuserver
![capture du 2018-10-23 15-30-26](https://user-images.githubusercontent.com/28365138/47367940-996ae680-d6d8-11e8-965b-f883ff8127ed.png)
:8069/calendar/static/src/js/base_calendar.js:76:43

Expected behavior: no errors

**Comment by pedrobaeza** [comment] 2018-10-23 14:38
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-10-23 14:38 UTC

**Comment by aitalinassim** [comment] 2018-10-23 14:50
Sir,

Thanks for your answer

Issue solved by replacing already existing file on the server "base_calndar.js" by the one download from odoo source from github.

Is this procedure correct ?

**Comment by aitalinassim** [comment] 2018-10-23 15:02
Left is old file and on right is file fro github

![capture du 2018-10-23 16-01-07](https://user-images.githubusercontent.com/28365138/47370100-eb157000-d6dc-11e8-97e2-1c64291181c3.png)
