### ISSUE TITLE
[9.0] No update not available for csv data files - _load_data is not called for init.

### ISSUE THREAD

**Issue by yvaucher** [odoo/odoo#10696] opened 2016-01-29 20:03 UTC
Having a look at https://github.com/odoo/odoo/blob/9.0/openerp/modules/loading.py#L96 it seems that part of the code is still ready to load csv with noupdate. However, as init and init_xml were deprecated the only way to do it right now is to create a post init hook.

As CSV are faster than XML to be loaded, they are quite well designed for big load of data to insert. Like for country states or bank list. However having a lot of data you don't want them to be loaded each time you update the module. Thus, you want to activate 'noupdate'.

Could we have an `init_csv` key in `__openerp__.py` or restore `init` or `init_xml` ?

The issue is that _load_data is never called with kind='init' thus when checking is file is csv and kind is 'init' or 'init_xml' won't work.

(BTW it seems that XML loading time is strangely slower in 9.0, I can only compare with a csv import which takes less than 1 min while the same data in XML takes 7 minutes)

**Comment by danimaribeiro** [comment] 2016-09-07 02:36
Any chance this could be addressed in v10?

**Comment by yvaucher** [comment] 2016-09-07 11:02
By the way the work around I used was to make a post_init hook:

https://github.com/OCA/l10n-switzerland/pull/175/commits/3ddbcffc580857123ff29ebcd980e08c05eb9a8f

**Comment by danimaribeiro** [comment] 2016-09-08 10:42
Nice :+1:

**Comment by thomassomko** [comment] 2017-01-26 15:13
I had to dirty work around it, with a patch. To many CSV files and modules. I hope this gets adresses fast. 

https://gist.github.com/thomassomko/29c7c1bcb6db228bda1a7c99173f7750

**Comment by pedrobaeza** [comment] 2018-04-11 22:50
@yvaucher is this still happening?

**Comment by yvaucher** [comment] 2018-04-16 13:36
@pedrobaeza I didn't see any change or option to tag a csv file as noupdate, have you?

**Comment by pedrobaeza** [comment] 2018-04-16 13:44
No, indeed. I'm not sure if this is by design. Any way, if you know how to change this, maybe you can propose something to master. If not, I think this should be closed as "Won't fix" or "Wishlist".

**Comment by yvaucher** [comment] 2018-04-16 14:03
@pedrobaeza it didn't changed in master:
https://github.com/odoo/odoo/blob/master/odoo/modules/loading.py#L89

I have some doubts that a change on `__manifest__` would be accepted, I'll try though to do a proposition in a not too far future.

**Comment by pedrobaeza** [comment] 2018-04-16 14:11
OK, thanks.

**Comment by pedrobaeza** [comment] 2018-04-17 23:37
Closing this as no real bug and a PR is expected.

**Closed by pedrobaeza** 2018-04-17 23:37 UTC

**Comment by yvaucher** [comment] 2018-04-18 09:47
@pedrobaeza I disagree this is at least some dead code in code base. I consider this as a bug.

**Comment by pedrobaeza** [comment] 2018-04-18 10:42
As you pointed, the option dissapears when deprecating the keys in the manifest, so it's a missing feature. The only way is to re-add an option in manifest for having this feature back.
