### ISSUE TITLE
[11]error installing payroll 

### ISSUE THREAD

**Issue by icf20** [odoo/odoo#24212] opened 2018-04-13 07:54 UTC
http://319943-11-0-6fb59b.runbot13.odoo.com

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/addons/base/ir/ir_model.py", line 1469, in _update
    record = record.create(values)
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/addons/hr/models/hr.py", line 220, in create
    return super(Employee, self).create(vals)
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/addons/mail/models/mail_thread.py", line 231, in create
    thread = super(MailThread, self).create(values)
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/addons/resource/models/resource_mixin.py", line 29, in create
    'name': values.get(self._rec_name)
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/addons/resource/models/resource.py", line 697, in create
    return super(ResourceResource, self).create(values)
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/models.py", line 3348, in create
    record = self.browse(self._create(old_vals))
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/models.py", line 3441, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: null value in column "calendar_id" violates not-null constraint
DETAIL:  Failing row contains (120, Roger Scott, t, 1, user, null, 100, null, 1, 2018-04-13 07:51:32.543247, 1, 2018-04-13 07:51:32.543247).


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/addons/web/controllers/main.py", line 934, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-40>", line 2, in button_immediate_install
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/modules/loading.py", line 159, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='demo')
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/tools/convert.py", line 788, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/tools/convert.py", line 849, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/tools/convert.py", line 748, in parse
    exc_info[2]
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/addons/base/ir/ir_model.py", line 1469, in _update
    record = record.create(values)
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/addons/hr/models/hr.py", line 220, in create
    return super(Employee, self).create(vals)
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/addons/mail/models/mail_thread.py", line 231, in create
    thread = super(MailThread, self).create(values)
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/addons/resource/models/resource_mixin.py", line 29, in create
    'name': values.get(self._rec_name)
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/addons/resource/models/resource.py", line 697, in create
    return super(ResourceResource, self).create(values)
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/models.py", line 3348, in create
    record = self.browse(self._create(old_vals))
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/models.py", line 3441, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
odoo.tools.convert.ParseError: "null value in column "calendar_id" violates not-null constraint
DETAIL:  Failing row contains (120, Roger Scott, t, 1, user, null, 100, null, 1, 2018-04-13 07:51:32.543247, 1, 2018-04-13 07:51:32.543247).
" while parsing /home/odoo/runbot/runbot/runbot/static/build/319943-11-0-6fb59b/odoo/addons/hr_payroll/data/hr_payroll_demo.xml:128, near
<record id="hr_employee_payroll" model="hr.employee">
            <field eval="0" name="manager"/>
            <field name="company_id" ref="base.main_company"/>
            <field eval="1" name="active"/>
            <field name="name">Roger Scott</field>
            <field name="work_location">Building 1, Second Floor</field>
            <field name="work_phone">+3282823500</field>
            <field name="image" type="base64" file="hr_payroll/static/img/hr_employee_payroll-image.jpg"/>
        </record>

```

**Comment by pedrobaeza** [comment] 2018-04-13 07:56
What are the steps followed for reproducing the problem?

**Comment by icf20** [comment] 2018-04-13 07:58
@pedrobaeza just click the install payroll

**Comment by pedrobaeza** [comment] 2018-04-13 08:01
That runbot instance has been very manipulated (I was tonight for example touching it), so I think it's the problem, due to a record removed, and another hint to guess that is that the module is installed by default. Please try on a fresh one to reproduce the problem.

**Comment by Yenthe666** [comment] 2018-04-13 08:06
@pedrobaeza when I deinstall and reinstall `payroll` I'm also getting an internal server error on the runbot but a completely different one. Something looks off honestly:
```
Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 180, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 168, in execute
    application_iter = app(environ, start_response)
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/service/wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/http.py", line 1316, in __call__
    return self.dispatch(environ, start_response)
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/http.py", line 1290, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 591, in __call__
    return self.app(environ, start_response)
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/http.py", line 1480, in dispatch
    result = ir_http._dispatch()
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/addons/website_sale/models/ir_http.py", line 15, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/addons/website_crm_score/models/ir.py", line 32, in _dispatch
    response = super(ir_http, cls)._dispatch()
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/addons/website_version/models/ir_http.py", line 13, in _dispatch
    x = super(ir_http, cls)._dispatch()
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/addons/web_editor/models/ir_http.py", line 22, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/addons/http_routing/models/ir_http.py", line 398, in _dispatch
    result = super(IrHttp, cls)._dispatch()
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/addons/utm/models/ir_http.py", line 26, in _dispatch
    response = super(IrHttp, cls)._dispatch()
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/addons/base/ir/ir_http.py", line 212, in _dispatch
    return cls._handle_exception(e)
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/addons/website/models/ir_http.py", line 164, in _handle_exception
    return super(Http, cls)._handle_exception(exception)
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/addons/utm/models/ir_http.py", line 31, in _handle_exception
    response = super(IrHttp, cls)._handle_exception(exc)
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/addons/base/ir/ir_http.py", line 182, in _handle_exception
    return request._handle_exception(exception)
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/http.py", line 770, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/addons/base/ir/ir_http.py", line 208, in _dispatch
    result = request.dispatch()
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/http.py", line 829, in dispatch
    r = self._call_function(**self.params)
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/http.py", line 338, in checked_call
    result.flatten()
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/http.py", line 1267, in flatten
    self.response.append(self.render())
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/http.py", line 1260, in render
    return env["ir.ui.view"].render_template(self.template, self.qcontext)
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/addons/base/ir/ir_ui_view.py", line 1189, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/addons/website/models/ir_ui_view.py", line 113, in render
    return super(View, self).render(values, engine=engine)
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/addons/web_editor/models/ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/addons/base/ir/ir_ui_view.py", line 1198, in render
    return self.env[engine].render(self.id, qcontext)
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/addons/website_version/models/ir_qweb.py", line 46, in render
    return super(QWeb, self).render(id_or_xml_id, values, **options)
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 57, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/addons/base/ir/ir_qweb/qweb.py", line 271, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/addons/base/ir/ir_qweb/qweb.py", line 346, in _compiled_fn
    element, document = self.get_template(template, options)
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/addons/base/ir/ir_qweb/qweb.py", line 371, in get_template
    raise QWebException("load could not load template", name=template)
odoo.addons.base.ir.ir_qweb.qweb.QWebException: None
Traceback (most recent call last):
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.qweb', <function IrQWeb._get_asset at 0x7fa0ae48e2f0>, 'web.assets_backend', 'en_US', True, False, False, False, (None,))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/addons/base/ir/ir_qweb/qweb.py", line 341, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_435_5264
  File "<template>", line 2, in body_call_content_5263
  File "<template>", line 3, in set_5261
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/addons/website/models/ir_qweb.py", line 30, in _get_asset
    return super(QWeb, self)._get_asset(xmlid, options, css, js, debug, async, values)
  File "<decorator-gen-37>", line 2, in _get_asset
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 197, in _get_asset
    return asset.to_html(css=css, js=js, debug=debug, async=async, url_for=(values or {}).get('url_for', lambda url: url))
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/addons/base/ir/ir_qweb/assetsbundle.py", line 125, in to_html
    css_attachments = self.css() or []
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/addons/base/ir/ir_qweb/assetsbundle.py", line 272, in css
    self.save_attachment("css", ' '.join(page), inc=idx)
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/addons/base/ir/ir_qweb/assetsbundle.py", line 231, in save_attachment
    self.clean_attachments(type)
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/addons/base/ir/ir_qweb/assetsbundle.py", line 181, in clean_attachments
    return ira.sudo().search(domain).unlink()
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/addons/base/ir/ir_attachment.py", line 427, in unlink
    res = super(IrAttachment, self).unlink()
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/models.py", line 2911, in unlink
    cr.execute(query, (sub_ids,))
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.extensions.TransactionRollbackError: could not serialize access due to concurrent update


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.view', <function View._read_template at 0x7fa0af3636a8>, frozenset({1, 3, 4, 7, 8, 9, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 34, 36, 39, 40, 41, 42, 43, 44, 45, 49, 50, 51, 52, 53, 54, 56, 57, 58, 59, 60, 61, 63, 64, 65, 69, 70, 71, 76, 77, 78, 79, 82, 83, 84, 85, 86, 87, 88, 90, 91, 93, 96, 97, 98, 99, 101, 102, 103, 104, 105, 106, 107, 108, 114, 115, 117, 118}), 435, ('en_US', None, None, None, None, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/addons/base/ir/ir_qweb/qweb.py", line 367, in get_template
    document = options.get('load', self.load)(template, options)
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 85, in load
    template = env['ir.ui.view'].read_template(name)
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/addons/base/ir/ir_ui_view.py", line 1084, in read_template
    return self._read_template(self.get_view_id(xml_id))
  File "<decorator-gen-25>", line 2, in _read_template
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/addons/base/ir/ir_ui_view.py", line 1075, in _read_template
    arch = self.browse(view_id).read_combined(['arch'])['arch']
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/addons/base/ir/ir_ui_view.py", line 697, in read_combined
    [view_data] = root.read(fields=fields)
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/models.py", line 2565, in read
    self._read_from_database(stored, inherited)
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/models.py", line 2684, in _read_from_database
    cr.execute(query_str, params)
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/runbot/runbot/runbot/static/build/320007-11-0-c59817/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.InternalError: current transaction is aborted, commands ignored until end of transaction block


load could not load template
Template: 435
```

**Comment by pedrobaeza** [comment] 2018-04-13 08:11
That's because the tests are on a dirty environment as stated. The only way to assure that the tests are correct is to perform it on a clean environment. The problem is that demo data depends on other demo data installed by other modules, and thus if they have been previously manipulated, system will break. Uninstalling is not a guarantee, as you still have the unstable environment.

**Comment by Yenthe666** [comment] 2018-04-13 08:18
I guess somebody deleted this record:
https://github.com/odoo/odoo/blob/cd48a806ac636806130efcf5c055f73758cb0902/addons/hr_payroll/data/hr_payroll_demo.xml#L128-L136

Which triggers the failing row.

**Comment by pedrobaeza** [comment] 2018-04-13 10:41
Exactly, so closing this.

**Closed by pedrobaeza** 2018-04-13 10:41 UTC
Labels: 11.0, Services
