### ISSUE TITLE
[V14.0] cannot install invoicing for Vietnam

### ISSUE THREAD

**Issue by tuanace** [odoo/odoo#59054] opened 2020-10-04 03:45 UTC
Impacted versions:
14.0 community
Steps to reproduce:
Clone Odoo community version 14.0, create new database and choose language Vietnamese, Country Vietnamese and with Demo data then instal the Invoicing app
Current behavior:
Showing error 
Demo Installation Failures
while parsing /Users/eicaptain/1sourcecode/14/odoo/addons/l10n_vn/demo/demo_company.xml:30, near <function model="account.chart.template" name="try_loading"> <value eval="[ref('l10n_vn.vn_template')]"/> <value model="res.company" eval="obj().env.ref('l10n_vn.demo_company_vn')"/> </function>

![image](https://user-images.githubusercontent.com/13285061/95006419-884de280-062e-11eb-8842-356009b893a7.png)

Expected behavior:
It should install successfully without any error

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2020-10-05 07:27
This sounds as a bad translation. Please try installing l10_vn with English. Also full error should be shown.

**Comment by thongthele** [comment] 2020-10-08 08:19
@pedrobaeza The error occurred when installing `account` with Vietnamese.
**Steps to reproduce:**
1. Create a brand new Vietnamese database (using `-l vi_VN` and `--load-language=vi_VN`)
2. Install Invoicing (`account`), an email alias constraint is raised.

> Cannot use 'VN Company-Hoá đơn' as email alias, fallback to 'purchase' 
> Module l10n_vn demo data failed to install, installed without demo data
> The e-mail alias is already used. Please enter another one.

**Traceback:**

2020-10-08 08:10:22,514 39303 INFO odoo14 odoo.modules.loading: Loading module l10n_vn (41/42) 
2020-10-08 08:10:22,843 39303 INFO odoo14 odoo.modules.loading: loading l10n_vn/data/l10n_vn_chart_data.xml 
2020-10-08 08:10:23,282 39303 INFO odoo14 odoo.modules.loading: loading l10n_vn/data/account.account.template.csv 
2020-10-08 08:10:23,759 39303 INFO odoo14 odoo.modules.loading: loading l10n_vn/data/l10n_vn_chart_post_data.xml 
2020-10-08 08:10:23,764 39303 INFO odoo14 odoo.modules.loading: loading l10n_vn/data/account_data.xml 
2020-10-08 08:10:23,777 39303 INFO odoo14 odoo.modules.loading: loading l10n_vn/data/account_tax_report_data.xml 
2020-10-08 08:10:23,894 39303 INFO odoo14 odoo.modules.loading: loading l10n_vn/data/account_tax_data.xml 
2020-10-08 08:10:23,968 39303 INFO odoo14 odoo.modules.loading: loading l10n_vn/data/account_chart_template_data.xml 
2020-10-08 08:10:41,813 39303 WARNING odoo14 odoo.addons.account.models.account_journal: Cannot use 'YourCompany-Hoá đơn' as email alias, fallback to 'purchase' 
2020-10-08 08:10:46,690 39303 INFO odoo14 odoo.modules.loading: Module l10n_vn: loading demo 
2020-10-08 08:10:46,690 39303 INFO odoo14 odoo.modules.loading: loading l10n_vn/demo/demo_company.xml 
2020-10-08 08:10:57,550 39303 WARNING odoo14 odoo.addons.account.models.account_journal: Cannot use 'VN Company-Hoá đơn' as email alias, fallback to 'purchase' 
2020-10-08 08:11:51,419 39303 WARNING odoo14 odoo.modules.loading: Module l10n_vn demo data failed to install, installed without demo data 
Traceback (most recent call last):
  File "/home/thongle/Viindoo/odoo-12/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/home/thongle/Viindoo/odoo-12/odoo/tools/convert.py", line 330, in _tag_function
    _eval_xml(self, rec, env)
  File "/home/thongle/Viindoo/odoo-12/odoo/tools/convert.py", line 201, in _eval_xml
    return odoo.api.call_kw(model, method_name, args, kwargs)
  File "/home/thongle/Viindoo/odoo-12/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/thongle/Viindoo/odoo-12/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/thongle/Viindoo/odoo-12/addons/account/models/chart_template.py", line 186, in try_loading
    template.with_context(default_company_id=company.id)._load(15.0, 15.0, company)
  File "/home/thongle/Viindoo/odoo-12/addons/l10n_multilang/models/l10n_multilang.py", line 16, in _load
    res = super(AccountChartTemplate, self)._load(sale_tax_rate, purchase_tax_rate, company)
  File "/home/thongle/Viindoo/odoo-12/addons/account/models/chart_template.py", line 251, in _load
    acc_template_ref, taxes_ref = self._install_template(company, code_digits=self.code_digits)
  File "/home/thongle/Viindoo/odoo-12/addons/account/models/chart_template.py", line 522, in _install_template
    tmp1, tmp2 = self.with_context(lang=company.partner_id.lang)._load_template(company, code_digits=code_digits, account_ref=acc_ref, taxes_ref=taxes_ref)
  File "/home/thongle/Viindoo/odoo-12/addons/account/models/chart_template.py", line 579, in _load_template
    self.generate_journals(account_ref, company)
  File "/home/thongle/Viindoo/odoo-12/addons/account/models/chart_template.py", line 417, in generate_journals
    journal = JournalObj.create(vals_journal)
  File "<decorator-gen-158>", line 2, in create
  File "/home/thongle/Viindoo/odoo-12/odoo/api.py", line 323, in _model_create_single
    return create(self, arg)
  File "/home/thongle/Viindoo/odoo-12/addons/account/models/account_journal.py", line 558, in create
    journal._update_mail_alias(vals)
  File "/home/thongle/Viindoo/odoo-12/addons/account/models/account_journal.py", line 409, in _update_mail_alias
    self.alias_id = self.env['mail.alias'].sudo().create(alias_values)
  File "<decorator-gen-123>", line 2, in create
  File "/home/thongle/Viindoo/odoo-12/odoo/api.py", line 323, in _model_create_single
    return create(self, arg)
  File "/home/thongle/Viindoo/odoo-12/addons/mail/models/mail_alias.py", line 115, in create
    vals['alias_name'] = self._clean_and_check_unique(vals.get('alias_name'))
  File "/home/thongle/Viindoo/odoo-12/addons/mail/models/mail_alias.py", line 153, in _clean_and_check_unique
    raise UserError(_('The e-mail alias is already used. Please enter another one.'))
odoo.exceptions.UserError: The e-mail alias is already used. Please enter another one.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thongle/Viindoo/odoo-12/odoo/modules/loading.py", line 86, in load_demo
    load_data(cr, idref, mode, kind='demo', package=package)
  File "/home/thongle/Viindoo/odoo-12/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/home/thongle/Viindoo/odoo-12/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/home/thongle/Viindoo/odoo-12/odoo/tools/convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/thongle/Viindoo/odoo-12/odoo/tools/convert.py", line 719, in parse
    self._tag_root(de)
  File "/home/thongle/Viindoo/odoo-12/odoo/tools/convert.py", line 681, in _tag_root
    raise ParseError('while parsing %s:%s, near\n%s' % (
odoo.tools.convert.ParseError: while parsing /home/thongle/Viindoo/odoo-12/addons/l10n_vn/demo/demo_company.xml:30, near
<function model="account.chart.template" name="try_loading">
        <value eval="[ref('l10n_vn.vn_template')]"/>
        <value model="res.company" eval="obj().env.ref('l10n_vn.demo_company_vn')"/>
    </function>

**Comment by thongthele** [comment] 2020-10-08 08:54
@pedrobaeza The error occurred when installing `account` with Vietnamese.
**Steps to reproduce:**
1. Create a brand new Vietnamese database (using `-l vi_VN` and `--load-language=vi_VN`)
2. Install Invoicing (`account`), an email alias constraint is raised.

> Cannot use 'VN Company-Hoá đơn' as email alias, fallback to 'purchase' 
> Module l10n_vn demo data failed to install, installed without demo data
> The e-mail alias is already used. Please enter another one.

**Traceback:**

2020-10-08 08:10:22,514 39303 INFO odoo14 odoo.modules.loading: Loading module l10n_vn (41/42) 
2020-10-08 08:10:22,843 39303 INFO odoo14 odoo.modules.loading: loading l10n_vn/data/l10n_vn_chart_data.xml 
2020-10-08 08:10:23,282 39303 INFO odoo14 odoo.modules.loading: loading l10n_vn/data/account.account.template.csv 
2020-10-08 08:10:23,759 39303 INFO odoo14 odoo.modules.loading: loading l10n_vn/data/l10n_vn_chart_post_data.xml 
2020-10-08 08:10:23,764 39303 INFO odoo14 odoo.modules.loading: loading l10n_vn/data/account_data.xml 
2020-10-08 08:10:23,777 39303 INFO odoo14 odoo.modules.loading: loading l10n_vn/data/account_tax_report_data.xml 
2020-10-08 08:10:23,894 39303 INFO odoo14 odoo.modules.loading: loading l10n_vn/data/account_tax_data.xml 
2020-10-08 08:10:23,968 39303 INFO odoo14 odoo.modules.loading: loading l10n_vn/data/account_chart_template_data.xml 
2020-10-08 08:10:41,813 39303 WARNING odoo14 odoo.addons.account.models.account_journal: Cannot use 'YourCompany-Hoá đơn' as email alias, fallback to 'purchase' 
2020-10-08 08:10:46,690 39303 INFO odoo14 odoo.modules.loading: Module l10n_vn: loading demo 
2020-10-08 08:10:46,690 39303 INFO odoo14 odoo.modules.loading: loading l10n_vn/demo/demo_company.xml 
2020-10-08 08:10:57,550 39303 WARNING odoo14 odoo.addons.account.models.account_journal: Cannot use 'VN Company-Hoá đơn' as email alias, fallback to 'purchase' 
2020-10-08 08:11:51,419 39303 WARNING odoo14 odoo.modules.loading: Module l10n_vn demo data failed to install, installed without demo data 
Traceback (most recent call last):
  File "/home/user/odoo-12/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/home/user/odoo-12/odoo/tools/convert.py", line 330, in _tag_function
    _eval_xml(self, rec, env)
  File "/home/user/odoo-12/odoo/tools/convert.py", line 201, in _eval_xml
    return odoo.api.call_kw(model, method_name, args, kwargs)
  File "/home/user/odoo-12/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/user/odoo-12/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/user/odoo-12/addons/account/models/chart_template.py", line 186, in try_loading
    template.with_context(default_company_id=company.id)._load(15.0, 15.0, company)
  File "/home/user/odoo-12/addons/l10n_multilang/models/l10n_multilang.py", line 16, in _load
    res = super(AccountChartTemplate, self)._load(sale_tax_rate, purchase_tax_rate, company)
  File "/home/user/odoo-12/addons/account/models/chart_template.py", line 251, in _load
    acc_template_ref, taxes_ref = self._install_template(company, code_digits=self.code_digits)
  File "/home/user/odoo-12/addons/account/models/chart_template.py", line 522, in _install_template
    tmp1, tmp2 = self.with_context(lang=company.partner_id.lang)._load_template(company, code_digits=code_digits, account_ref=acc_ref, taxes_ref=taxes_ref)
  File "/home/user/odoo-12/addons/account/models/chart_template.py", line 579, in _load_template
    self.generate_journals(account_ref, company)
  File "/home/user/odoo-12/addons/account/models/chart_template.py", line 417, in generate_journals
    journal = JournalObj.create(vals_journal)
  File "<decorator-gen-158>", line 2, in create
  File "/home/user/odoo-12/odoo/api.py", line 323, in _model_create_single
    return create(self, arg)
  File "/home/user/odoo-12/addons/account/models/account_journal.py", line 558, in create
    journal._update_mail_alias(vals)
  File "/home/user/odoo-12/addons/account/models/account_journal.py", line 409, in _update_mail_alias
    self.alias_id = self.env['mail.alias'].sudo().create(alias_values)
  File "<decorator-gen-123>", line 2, in create
  File "/home/user/odoo-12/odoo/api.py", line 323, in _model_create_single
    return create(self, arg)
  File "/home/user/odoo-12/addons/mail/models/mail_alias.py", line 115, in create
    vals['alias_name'] = self._clean_and_check_unique(vals.get('alias_name'))
  File "/home/user/odoo-12/addons/mail/models/mail_alias.py", line 153, in _clean_and_check_unique
    raise UserError(_('The e-mail alias is already used. Please enter another one.'))
odoo.exceptions.UserError: The e-mail alias is already used. Please enter another one.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/odoo-12/odoo/modules/loading.py", line 86, in load_demo
    load_data(cr, idref, mode, kind='demo', package=package)
  File "/home/user/odoo-12/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/home/user/odoo-12/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/home/user/odoo-12/odoo/tools/convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/user/odoo-12/odoo/tools/convert.py", line 719, in parse
    self._tag_root(de)
  File "/home/user/odoo-12/odoo/tools/convert.py", line 681, in _tag_root
    raise ParseError('while parsing %s:%s, near\n%s' % (
odoo.tools.convert.ParseError: while parsing /home/user/odoo-12/addons/l10n_vn/demo/demo_company.xml:30, near
<function model="account.chart.template" name="try_loading">
        <value eval="[ref('l10n_vn.vn_template')]"/>
        <value model="res.company" eval="obj().env.ref('l10n_vn.demo_company_vn')"/>
    </function>

**Comment by thongthele** [comment] 2020-10-08 08:57
I think this issue is similar with [8dc85be](https://github.com/odoo/odoo/commit/ad2cc2fe43cb80a7ab3b0bcd08ea29aa5b403761)

**Comment by wllbll** [comment] 2021-03-26 00:32
The same issue occurs in installing l10n_cn. 
Steps to reproduce:
1. Initialize the database with Country set the China (Odoo will install l10n_cn , which has localization setting for Chinese Accounting) and the language to Chinese
2. Add another company in Setting
3. Setting the account for new company with Chinese localization Accounting setting.
Odoo will fail to install Chinese Accounting Data as Odoo will try to set the alias name 'purchase' and this name is duplicated .
The reason fail i guess:
Odoo will set the safe alias when the name code has non-ascii character( for example , "账单" in Chinese), which is `purchase`
```
        except UnicodeEncodeError:
            try:
                remove_accents(self.code).encode('ascii')
                safe_alias_name = self.code
            except UnicodeEncodeError:
                safe_alias_name = self.type
``` 
The second company setup has same procedure, then safe name will be duplicated in mail.alias 

Fix it:
1. Manually setting the alias in Accounting-> Journal for sale and purchase journal 
2. Then add another company in odoo.

**Comment by william-andre** [comment] 2021-03-26 08:14
Please update your code if you still have this issue. It should be fixed with https://github.com/odoo/odoo/commit/ad2cc2fe43cb80a7ab3b0bcd08ea29aa5b403761

**Closed by william-andre** 2021-03-26 08:14 UTC
Labels: 14.0, Accounting
