### ISSUE TITLE
[11.0-sale_margin] Wrong Computation with FIFO automated cost method and Landed Costs

### ISSUE THREAD

**Issue by cvinh** [odoo/odoo#25604] opened 2018-07-04 14:53 UTC
Impacted versions:
11.0 (at least)

Steps to reproduce:
- Setup a product with costing method to automated FIFO and tax included in price
- Setup a foreign currency
- Buy a Product in foreign currency (purchase order --> stock receipt --> supplier invoice)
- Add Landed costs in company's currency
- Sale the product in company's currency

Current behavior:
- Cost price in sale_order is zero

Expected behavior:
- Cost price should be taken from real time cost move

**Comment by vcloud9ray** [comment] 2018-07-04 21:36
Since you have not shipped (delivered), the price will stay at $0 until you do so.

The "Cost" on a product in this situation becomes "the cost of the last product shipped" since the product cost is not trivial to calculate.

Example:

- Receive three products on three shipments - $11, $12 and $13 - maybe adjusted with a landed cost and maybe not.
- Enter more than one Sales Order.

The "cost" depends on:

1. how many items are on the Sales Order - for one it might be $11 and for 3 it might be $12; 
2. when each order is confirmed - what if the second is confirmed before the first?;
3. if the reservation is changed - what if Odoo reserves the $11 unit for the first order, but a user unreserves and reserves this unit for the second order?
4. what if the landed cost is adjusted after the Sales Order is confirmed and before delivery?
5. what if the landed cost is adjusted after the Sales Order is confirmed and after delivery?

The stock.quant is where the cost is stored, and can be updated, until needed when an item is delivered.  Until a quant is reserved for a delivery order, cost is unknown.

Since the cost of the product isn't known until the order is processed and delivered, it doesn't have the same meaning as a product cost.   

Hiding this field from users might be useful - as you remind them that cost doesn't mean what they might think it means.

**Comment by gustavovalverde** [comment] 2018-08-02 10:13
@vcloud9ray  I might agree with:

> Hiding this field from users might be useful - as you remind them that cost doesn't mean what they might think it means.

But this is mainly because Odoo doesn't distinguish between two similar _concepts_:
- Cost of Revenue (or COGS)
- Product Cost (or Product Value) --> mainly coming from valuation

In the Product template we have **COGS** but not the _actual_ **Product Cost/Value**. 

This causes issues like this one and also:

When buying a product for the first time or manufacturing a product for the first time Odoo is expecting to have a `standard_price` in the `product.template` or `product.product` (which won't be there with FIFO until the product is sold); but this completely halts **sales** and the **production** process because:
- A Sale with a pricelist based on cost will set the first buy product to $0 on sales (not real). #25977 
- A production with a newly created product won't allow to finalize the MO because the product has no cost (not real). #25290

This is all because in FIFO we're waiting to sell the product to set a cost/value on it. When we should be waiting to sell just to set a COGS in the accounting.

So **yes**, the cost in the product is very confusing but it's also being wrongly used in a bunch of computations. Based on all the experiences I've been trough with clients I'd say that those behaviors are wrongly _defined_.

**Comment by invitu** [comment] 2018-08-02 15:49
@gustavovalverde I saw that the landed costs are considered in real time cost indeed as the confirmation of the landed costs sheet generates accounting entries for stock move equal to the landed cost values. By the way, the cost in quants are updated correctly (thanksfully).
Could you double check that ?

**Comment by invitu** [comment] 2018-08-02 15:52
@vcloud9ray @mga-odoo do you have any advice on how to manage that ? Do you have real cases ? For a salesman, it's very useful to have at least estimated margins for a sale_order at the quotation state...

**Comment by gustavovalverde** [comment] 2018-08-02 16:41
My bad @invitu I actually wanted to refer to COGS or Product Cost on the `product.template`, in the test I did the landed_cost were not consider for the `standard_price`.

**Comment by mga-odoo** [comment] 2018-08-02 19:51
@invitu I just explain the computation of profit for both method at https://github.com/odoo/odoo/issues/25977 for the same example look at the video https://youtu.be/PSRWuz8ClCw

If there is a possibility to replace the FIFO with AVCO you can have the correct cost price that can be used to compute for Pricelist or Margin, it has a correct result.

**Landed cost**, yes its removed with the AVCO, but you can achieve the same out-of-the-box. Refer the same thread to know how you can calculate and apply the landed cost with AVCO.

**Comment by bhavik1989863** [comment] 2019-12-16 11:58
I think this is related hence posting here.

In sales report given in reporting section in sales app, Margin is calculated based on order lines for particular variant ,means unit price - (cost in sales order line)..
Now cost in sales order line is taken based on product onchange (from product variant form).
But in Real time valuation with FIFO.Cost price in product variant is updated once there is an outgoing.so cost price is not updated yet while you are doing sales ,and leading to wrong margin in the Sales report.
​
For example :
let say product variant  x have 58.5 as cost price in form view.Now i purchased a new unit with 78.
but still cost in product variant is 58.5(because it will update once i do the sales/delivery.)

Now when i create sales order ,odoo will take 58.5 as cost in order line based on product variant  onchange. While it should be 78.
​
Is this a real issue with Real time -FIFO or i am doing something wrong ?
If it's the issue is there any solution .

**Comment by sle-odoo** [comment] 2020-01-08 16:17
the cost price on the so is now updated after the delivery to reflect the real value

see rev f21b696c6e837c3807168ced990a28f1d51b87e9

**Closed by sle-odoo** 2020-01-08 16:17 UTC
Labels: 11.0, Logistics
