### ISSUE TITLE
Use preload instead of preconnect for google fonts

### ISSUE THREAD

**Issue by yelizariev** [odoo/odoo#50793] opened 2020-05-07 07:21 UTC
Impacted versions:

13. See https://github.com/odoo/odoo/commit/67dabea1dd12ed88998fd97cbbc84574cb982a92

Steps to reproduce:

block access to fonts.gstatic.com 

Current behavior:

waste extra 10 seconds

Expected behavior:

allow run odoo locally with slow internet or without internet connection

Video/Screenshot link (optional): -

Possible solution is using ``<link rel="preload">`` instead. Here is the quote from https://web.dev/uses-rel-preconnect/:

> 
> Bear in mind that while ``<link rel="preconnect">`` is pretty cheap, it can still take up valuable CPU time, particularly on secure connections. This is especially bad if the connection isn't used within 10 seconds, as the browser closes it, wasting all of that early connection work.
> 
> In general, try to use ``<link rel="preload">``, as it's a more comprehensive performance tweak, but ...
> 
>

**Comment by pedrobaeza** [comment] 2020-05-07 07:28
@qsm-odoo what do you think about the suggestion?

**Comment by qsm-odoo** [comment] 2020-05-07 11:40
@pedrobaeza We have a task in the pipe related to this. Not started yet but it will be considered. I added a reference to this issue in there, I'll give news when we will have thought this through :+1:

**Comment by pedrobaeza** [comment] 2020-05-07 11:42
Thanks, that's great!

**Comment by qsm-odoo** [comment] 2020-10-19 15:41
Is this still a problem? I actually cannot reproduce it anymore. Even if I block the fonts URL (by disabling my wi-fi or even explicitely blocking that URL only) the page is simply not blocked at all and the font fallbacks to another one immediately... maybe browsers just improved meanwhile?

As for the suggestion of using preload instead of preconnect, this is not a solution. Preload is for preloading a resource, which is not what we are trying to do here as we don't know the resource to load. We just know its base origin, hence the use of preconnect. We can consider improving the system to load fonts via an HTML `<link` and then preload would make sense but that would be for master. For 13.0, it is about removing or not the use of preconnect... as I cannot reproduce the issue, I'll leave the feature untouched and close this PR. If anybody manages to reproduce it, of course, please reopen the issue :+1:

**Closed by qsm-odoo** 2020-10-19 15:41 UTC
Labels: 13.0
