### ISSUE TITLE
Date Field: Widget ISO Warning

### ISSUE THREAD

**Issue by psyonara** [odoo/odoo#30291] opened 2019-01-17 07:51 UTC
Impacted versions: 
12 (only checked this version)

Steps to reproduce:
* Add a date field to a model
* Add the field for a form
* Proceed to create/edit a record
* Select a date in that field, e.g. "2019-01-01".

Current behavior:
Console in browser spits out a warning from the Moment library:
```
Deprecation warning: value provided is not in a recognized ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
```

Expected behavior:
No warnings in console.

Video/Screenshot link (optional):
![moment_iso_warning_on_date_field](https://user-images.githubusercontent.com/771840/51303222-65843080-1a3d-11e9-9e60-01cbbc71e476.png)

**Comment by psyonara** [comment] 2019-01-17 09:20
The difference was down to date format in the language settings. See screenshot below with default settings (matching what you have), and the warning still coming up.
![Uploading date_iso_warning.png…]()

**Comment by pedrobaeza** [comment] 2019-01-17 14:50
The problem is then in the custom date format you have configured/entered, which is incorrect. Please fix that and the warning will be gone.

Closing as no valid.

**Closed by pedrobaeza** 2019-01-17 14:50 UTC

**Comment by psyonara** [comment] 2019-01-18 07:07
I was able to reproduce this on a clean runbot build with all default settings. Steps:
* Start an instance of the latest v12 build
* Go to the Employees app
* Create a new employee
* Clicked on the "Date of Birth" field, and selected a date
* Immediately the ISO warning pops up in Firefox's console

Please see the screenshot below. Note the URL, showing that this is not my own custom build.
![employee_date_field_warning](https://user-images.githubusercontent.com/771840/51370535-210d9900-1b00-11e9-809a-d6c8606064e5.png)

It seems the warning does not come up on any date field, but on the date of birth field for employees it does come up.

**Comment by psyonara** [comment] 2019-01-18 07:17
Version 11 has the same behaviour, but version 10 does not.

**Comment by pedrobaeza** [comment] 2019-01-18 08:46
This is not critical, as it's only a warning and the rest is working properly, but OK if you decide to keep it opened.

**Comment by Yenthe666** [comment] 2019-01-18 09:53
@pedrobaeza I agree it is not critical but we should still try to remove/fix it at some point right? It is better to not have warnings honestly. I know that if we close this one there is absolutely nobody going to look at it anymore.

**Comment by pedrobaeza** [comment] 2019-01-18 09:54
OK, let's see is someone can handle it.

**Comment by psyonara** [comment] 2019-01-18 10:35
I believe the problem is contained in ```_isSameValue``` of ```basic_fields.js```. This runs whenever the date in the widget is changed. If it was previously empty, it tries to check if the new value (some date) is the same as the current value (which is false). Then the moment library is asked to evaluate "false" as a date, and that is where the warning comes in. I will try to submit a patch for the function asap.

**Comment by C3POdoo** [comment] 2023-03-30 11:53
Dear @psyonara,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._
