### ISSUE TITLE
Quant value does not change when invoice is different than SO.

### ISSUE THREAD

**Issue by elevationO** [odoo/odoo#12504] opened 2016-06-20 18:52 UTC
Impacted versions:
9.0e
Steps to reproduce:
Create PO, receive invoice for PO at higher price than PO.  Receive products, check inventory valuation.
Current behavior:
Quant value is generated from PO.
Expected behavior:
Quant value should be what the invoice states.
Video/Screenshot link (optional):

**Comment by sle-odoo** [comment] 2018-02-06 20:01
Hi,
This is a duplicate of #16441, please see my answer on this issue.

Regards

**Closed by sle-odoo** 2018-02-06 20:01 UTC
Labels: 9.0, Logistics
