### ISSUE TITLE
Inventory module problem

### ISSUE THREAD

**Issue by davidabsenta** [odoo/odoo#65808] opened 2021-02-09 12:45 UTC
Impacted versions: 14

Steps to reproduce:
I have the community version installed in windows 10. I did not make any changes at the time the error occurred, the problem is that when I go to the inventory and I want to see the products, it does not leave me. before that just enter a purchase invoice.

Current behavior: also does not let me install or update applications. the error that appears is the following:

Error:
Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files\Odoo 14.0.20201126\server\odoo\addons\base\models\ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "C:\Program Files\Odoo 14.0.20201126\server\odoo\http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files\Odoo 14.0.20201126\server\odoo\http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files\Odoo 14.0.20201126\server\odoo\service\model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files\Odoo 14.0.20201126\server\odoo\http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files\Odoo 14.0.20201126\server\odoo\http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files\Odoo 14.0.20201126\server\odoo\http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files\Odoo 14.0.20201126\server\odoo\addons\web\controllers\main.py", line 1363, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "C:\Program Files\Odoo 14.0.20201126\server\odoo\addons\web\controllers\main.py", line 1355, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files\Odoo 14.0.20201126\server\odoo\api.py", line 392, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "C:\Program Files\Odoo 14.0.20201126\server\odoo\api.py", line 365, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "C:\Program Files\Odoo 14.0.20201126\server\odoo\models.py", line 1519, in load_views
    for [v_id, v_type] in views
  File "C:\Program Files\Odoo 14.0.20201126\server\odoo\models.py", line 1519, in <dictcomp>
    for [v_id, v_type] in views
  File "C:\Program Files\Odoo 14.0.20201126\server\odoo\addons\web\models\models.py", line 220, in fields_view_get
    r = super().fields_view_get(view_id, view_type, toolbar, submenu)
  File "C:\Program Files\Odoo 14.0.20201126\server\odoo\models.py", line 1600, in fields_view_get
    result = self._fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "C:\Program Files\Odoo 14.0.20201126\server\odoo\models.py", line 1561, in _fields_view_get
    root_view = View.browse(view_id).read_combined(['id', 'name', 'field_parent', 'type', 'model', 'arch'])
  File "C:\Program Files\Odoo 14.0.20201126\server\odoo\addons\base\models\ir_ui_view.py", line 809, in read_combined
    arch = root.apply_view_inheritance(arch_tree, self.model)
  File "C:\Program Files\Odoo 14.0.20201126\server\odoo\addons\base\models\ir_ui_view.py", line 750, in apply_view_inheritance
    return self._apply_view_inheritance(source, inherit_tree)
  File "C:\Program Files\Odoo 14.0.20201126\server\odoo\addons\base\models\ir_ui_view.py", line 758, in _apply_view_inheritance
    source = view.apply_inheritance_specs(source, arch_tree)
  File "C:\Program Files\Odoo 14.0.20201126\server\odoo\addons\base\models\ir_ui_view.py", line 735, in apply_inheritance_specs
    self.handle_view_error(str(e))
  File "C:\Program Files\Odoo 14.0.20201126\server\odoo\addons\base\models\ir_ui_view.py", line 673, in handle_view_error
    raise ValueError(formatted_message).with_traceback(from_traceback) from from_exception
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\Odoo 14.0.20201126\server\odoo\http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files\Odoo 14.0.20201126\server\odoo\http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: El elemento '<xpath expr="//group[@name='invoicing']">' no puede ser localizado en la vista padre

View name: product.template.sales
Error context:
 view: ir.ui.view(1217,)
 xmlid: sale.product_template_sale_form_view
 view.model: product.template
 view.parent: ir.ui.view(423,)

**Comment by pedrobaeza** [comment] 2021-02-09 12:48
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Closed** 2023-04-07 14:24 UTC
Labels: Need information, 14.0
