### ISSUE TITLE
Problem with default focus in HTML fields at form views (no matter if default_focus is set to another field)

### ISSUE THREAD

**Issue by zaoral** [odoo/odoo#26366] opened 2018-08-13 21:12 UTC
**Impacted versions:**

11.0

**Steps to reproduce:**

Go to any task form view.

**Current behavior:**

It focus the cursor in the description field (html widget).

**Expected behavior:**

It focus the cursor in the name field. 
I have added a default_focus in the view for the name field so this way it focus name field.. but it does not work. Always focus html field no matter what. 

NOTE: Only if i change the description field to widget="text" then the default_focus is applied

**Video/Screenshot link (optional):**

https://youtu.be/XzTgd8u2FHY

**Comment by zaoral** [comment] 2018-08-13 21:15
FYI opw-1874880

**Comment by Yenthe666** [comment] 2018-08-14 07:07
Duplicate of https://github.com/odoo/odoo/issues/24756 pretty much but I'll leave it open for now as it has an OPW. Please let us know the final answer from the OPW.

**Comment by intero-chz** [comment] 2018-08-14 07:29
By the way is `default_focus` really working? I had so much trouble with it in the beginning of my Odoo "era" that i've never touched it again.

**Closed** 2018-09-03 14:57 UTC
Labels: 11.0, Framework
