### ISSUE TITLE
Accept and Sign link wrong in email template

### ISSUE THREAD

**Issue by jwaes** [odoo/odoo#69017] opened 2021-04-09 07:53 UTC
Impacted versions:
Latest

Steps to reproduce:
On odoo.sh i made a staging version of the latest version and i am sending out a quotation mail

Current behavior:
The link generated is` xxxx.dev..odoo.com` with the double dot.

Expected behavior:
To create a valid link

Video/Screenshot link (optional):
![Screenshot 2021-04-09 095156](https://user-images.githubusercontent.com/50528773/114147847-66088a80-9919-11eb-9203-f686f31bf335.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment] 2021-04-09 12:06
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Yenthe666** [comment] 2021-04-09 13:30
@pedrobaeza I don't think you can simulate this in a runbot. I presume it is the logic from SH that duplicates the build and modifies some params. Either way it is an SH issue and SH issues should be logged through odoo.com with the enterprise license to be honest.

**Comment by pedrobaeza** [comment] 2021-04-09 13:41
Well, I was thinking in runbot and seeing Mailhog output mail. Anyway, according you say, I don't think this is something of this issue tracker, but Odoo.sh thing.

**Closed** 2021-04-09 13:45 UTC
Labels: Need information

**Comment by jev-odoo** [comment] 2021-04-13 19:57
Hello,

So far:
Not SH related, we have at least one Saas database with the same issue.
Seems related only to V14.
It does not reproduce when duplicating the database nor locally.
It may be related to RFC1521, section-5.1, rule #5
https://tools.ietf.org/html/rfc1521.html#section-5.1

Still investigating
