### ISSUE TITLE
Download pdf report from odoo but showing this error

### ISSUE THREAD

**Issue by batzaya** [odoo/odoo#26784] opened 2018-09-05 07:40 UTC
```
Uncaught SyntaxError: Unexpected token T in JSON at position 0
SyntaxError: Unexpected token T in JSON at position 0
    at JSON.parse (<anonymous>)
    at HTMLIFrameElement.<anonymous> (https://test.mn/web/content/2016-06decb5/web.assets_common.js:3038:379)
    at HTMLIFrameElement.dispatch (https://test.mn/web/content/2016-06decb5/web.assets_common.js:637:451)
    at HTMLIFrameElement.elemData.handle (https://test.mn/web/content/2016-06decb5/web.assets_common.js:610:173)
```

**Comment by matfeb** [comment] 2018-09-05 08:45
Same error with extension "Current stock in Excel", I can't export anything.

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

http://[IP_ADDRESS]/web/content/312-aadf65c/web.assets_common.js:3848

get_file/$target<@http://[IP_ADDRESS]/web/content/312-aadf65c/web.assets_common.js:3848:374
dispatch@http://[IP_ADDRESS]/web/content/312-aadf65c/web.assets_common.js:892:378
add/elemData.handle@http://[IP_ADDRESS]/web/content/312-aadf65c/web.assets_common.js:865:151

Maybe you have to change, when you are in developer mode, the export type of report (switch from PDF to HTML).
Go to "Configuration" -> "Technical" -> "Report"

**Comment by mart-e** [comment] 2018-09-06 07:26
Hello,

Could you detail how to reproduce your bug?
- which version?
- which report?
- how was installed odoo?
- can you reproduce on an up to date version (e.g. [runbot](http://runbot.odoo.com/) )

**Comment by gdgellatly** [comment] 2018-09-06 07:55
I've had this error plenty of times.  I wish I could remember the cause, but it is basic report setup stuff.   Probably a missing or incorrect dependency. I know once when I got it with excel its because I forgot xlwt.

**Comment by mart-e** [comment] 2018-09-06 07:58
If it is a missing dependency, it should be logged. Could you also check your server logs? Do you see an error when executing this method?
Also, when giving an error, always execute the method in [debug=assets](https://odoo-development.readthedocs.io/en/latest/odoo/usage/debug-assets-mode.html) mode to have more details.

**Comment by matfeb** [comment] 2018-09-06 15:30
**From my logs when I choose to export in HMTL from the extension :**

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 252, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1298, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1272, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1462, in dispatch
    result = ir_http._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/http_routing/models/ir_http.py", line 391, in _dispatch
    result = super(IrHttp, cls)._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_http.py", line 212, in _dispatch
    return cls._handle_exception(e)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_http.py", line 182, in _handle_exception
    return request._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 761, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_http.py", line 208, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 820, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/mnt/extra-addons/report_xlsx/controllers/main.py", line 43, in report_routes
    reportname, docids, converter, **data
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1609, in report_routes
    html = report.with_context(context).render_qweb_html(docids, data=data)[0]
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_actions_report.py", line 654, in render_qweb_html
    data = report_model.get_report_values(docids, data=data)
AttributeError: 'report.export_stockinfo_xls.stock_report_xls.xlsx' object has no attribute 'get_report_values'

**This is when I want to export in xlsx from the extension :**

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 252, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1298, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1272, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1462, in dispatch
    result = ir_http._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/http_routing/models/ir_http.py", line 391, in _dispatch
    result = super(IrHttp, cls)._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_http.py", line 212, in _dispatch
    return cls._handle_exception(e)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_http.py", line 182, in _handle_exception
    return request._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 761, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_http.py", line 208, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 820, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/mnt/extra-addons/report_xlsx/controllers/main.py", line 30, in report_routes
    docids, data=data
  File "/mnt/extra-addons/report_xlsx/models/ir_report.py", line 21, in render_xlsx
    }).create_xlsx_report(docids, data)
  File "/mnt/extra-addons/report_xlsx/report/report_xlsx.py", line 24, in create_xlsx_report
    self.generate_xlsx_report(workbook, data, objs)
  File "/mnt/extra-addons/export_stockinfo_xls/report/current_stock_xls.py", line 102, in generate_xlsx_report
    tz = pytz.timezone(user.tz)
  File "/usr/lib/python3/dist-packages/pytz/__init__.py", line 152, in timezone
    if zone.upper() == 'UTC':
AttributeError: 'bool' object has no attribute 'upper'

I run Odoo 11.0-20180122 (Community Edition) on Docker 17.05.0-ce
Anyway I've never got a working PDF export.
This error is from the extension "Current stock in Excel"

**Comment by mart-e** [comment] 2018-09-07 06:49
I am sorry but it looks like the problem comes from the custom module `export_stockinfo_xls`, not standard Odoo.
However, thank you not to hijack @batzaya report. Let's keep one bug per issue.

@batzaya can you please give more details about your problem?
Try in debug=assets as stated above.
Please specify which version and report you are trying to print.

**Comment by Yenthe666** [comment] 2019-01-28 12:43
Hi,

I'm closing this bug report as there has been no feedback on the questions from @mart-e 

Regards,
Yenthe

**Closed by Yenthe666** 2019-01-28 12:43 UTC
Labels: Need information

**Comment by lukebranch** [comment] 2019-01-28 12:52
@batzaya @matfeb ,

I've encountered this error before and if I remember correctly in my case this may have been due to a timeout on our proxy (Nginx in our case). I'd suggest taking a quick look at extending your timeout.

I will try and sift through some notes to find the case and the solution. I'll update this thread if I can find it.

**Comment by mom988** [comment] 2022-01-30 01:49
http://blog.sina.com.cn/s/blog_53d318170102wvnm.html
