### ISSUE TITLE
Windows: v8: Unicode decode error after installation

### ISSUE THREAD

**Issue by snapshot109** [odoo/odoo#4368] opened 2014-12-22 08:30 UTC
I am chewing quite some time now on this prob and couldn't find a solution (despite having found many threads containing unicode decode errors):

On my machine I had an OpenErp V7 installation, but deinstalled this now (I am at the beginning of the implementation of the ERP System) in favor to V8.

Unfortunately the installation of the latest build will not run. Trying to start up the server I get this error:

C:\Program Files (x86)\Odoo 8.0-20141218\server>openerp-server.exe
Traceback (most recent call last):
  File "openerp-server", line 2, in <module>
  File "C:\Program Files (x86)\Odoo 8.0-20141218\server\.\openerp\__init__.py",
line 78, in <module>
    import service
  File "C:\Program Files (x86)\Odoo 8.0-20141218\server\.\openerp\service\__init
__.py", line 27, in <module>
    import wsgi_server
  File "C:\Program Files (x86)\Odoo 8.0-20141218\server\.\openerp\service\wsgi_s
erver.py", line 46, in <module>
    import websrv_lib
  File "C:\Program Files (x86)\Odoo 8.0-20141218\server\.\openerp\service\websrv
_lib.py", line 37, in <module>
    from SimpleHTTPServer import SimpleHTTPRequestHandler
  File "SimpleHTTPServer.pyc", line 27, in <module>

  File "SimpleHTTPServer.pyc", line 208, in SimpleHTTPRequestHandler

  File "mimetypes.pyc", line 358, in init

  File "mimetypes.pyc", line 258, in read_windows_registry
    --extension / -e  -- guess extension instead of type
  File "mimetypes.pyc", line 249, in enum_types

UnicodeDecodeError: 'ascii' codec can't decode byte 0xae in position 7: ordinal
not in range(128)
 

Trying to run odoo on win server 2008 (x64) with the latest build from 18.12. with postgresql 9.3

I already tried reinstalling odoo, postgresql and adding unidecode 0.04.17 from python.org to the server directory. still, I can not get this solved (though I had this problem before during my tests and adding a new, empty postgre-db solved it, but this does not work this time).

Any ideas on this? I am quite lost at the moment.

**Comment by sle-odoo** [comment] 2015-01-06 17:05
Closing this as cannot reproduce, sorry.
I'll be glad to find/apply a patch if you can give me a consistent way to reproduce it.

**Closed by sle-odoo** 2015-01-06 17:05 UTC
Labels: blocked
