### ISSUE TITLE
Negative "To Pay" amount in Vendor Bills

### ISSUE THREAD

**Issue by rchavik** [odoo/odoo#28706] opened 2018-11-15 03:16 UTC
Impacted versions: 11.0 - enterprise (ee0ff262f084ca921c5414f528372e3d971806e3)

Steps to reproduce:
- Create a new vendor bill

Current behavior:
- Vendor bill created with Negative "To Pay"

Expected behavior:
- Vendor bill created with Positive "To Pay"

Possible cause: #28148 

Attached below is an example of bills created with the different commits

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/39490/48527608-5f979500-e8be-11e8-8823-833c8ce218de.png)

**Comment by rchavik** [comment] 2018-11-16 14:18
Note: We were unable to reproduce in runbot.  So this might not be core related.

**Comment by pedrobaeza** [comment] 2018-11-16 14:42
Then I'm afraid we have to close this.

Try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module.

**Closed by pedrobaeza** 2018-11-16 14:42 UTC
Labels: 11.0, Accounting
