### ISSUE TITLE
[7.0] hr_timesheet_sheet Error when selecting an analytic account

### ISSUE THREAD

**Issue by jbeficent** [odoo/odoo#4660] opened 2015-01-13 08:36 UTC
Using the odoo latest commit version from monday jan 13, when a user now searches for an analytox account, and selects it to add it to the timesheet the following error appears:

'TypeError: cannot read property 'render_value_defs' of undefined.

This did not occur in previous commit versions.

I believe that this error was introduced by this commit:
https://github.com/odoo/odoo/commit/38aa984f31f525539d27f2bf47806352705830ba

**Comment by gdgellatly** [comment] 2015-01-13 09:51
While I have different errors, certainly web has become unusable since the above mentioned commit and reverting has been the only option, althugh I also had to revert past the commit that that commit reverts as well

**Comment by beledouxdenis** [comment] 2015-01-13 11:28
Jordi, Graeme, 

I would be more than happy to solve your issues today.

I just had a look to Jordi issue, but couldn't reproduce the issue. Can you please describe the steps to perform in order to reproduce your problems: Where should I go ? What should I do ?

Graeme, regarding your different errors, could you explain them to me ? What are they ? When do they occur ? How can I reproduce them ?

Regards,

**Comment by beledouxdenis** [comment] 2015-01-13 11:47
Jorgi, Graeme, 

I was able to reproduce your issue by looking around a little more. I solved it with rev.
https://github.com/odoo/odoo/commit/275367581bbf26496607224cff3b5c16340098b9.

Graeme, I am still waiting for your feedback concerning your erros. In the meanwhile, I close this issue.

Regards,

**Closed by beledouxdenis** 2015-01-13 11:47 UTC

**Comment by jbeficent** [comment] 2015-01-13 13:36
I can see that the problem now does not reproduce.
Thanks!
