### ISSUE TITLE
User login value disappears when click on change password button without entering new password value in user change password wizard

### ISSUE THREAD

**Issue by GautamBothra** [odoo/odoo#71459] opened 2021-05-30 15:59 UTC
Impacted versions: 14.0

Steps to reproduce: General Settings --> Users --> Open a user record --> click on action menu --> click on action menu and click change password --> click on change password button without entering new password in wizard --> a warning message will appear, click OK --> After clicking OK button, User login gets disappear from the wizard

Current behavior: When we change password without entering any value in new password field, User login gets disappear from the wizard.

Expected behavior: User login value should be present in the wizard even if user enters blank password. So that it should whose password user/admin is changing.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment] 2021-05-31 06:38
Duplicate of #48379

**Closed by pedrobaeza** 2021-05-31 06:38 UTC
