### ISSUE TITLE
Accounting - Cannot publish account move in odoo v14 ce

### ISSUE THREAD

**Issue by OAlarconCast** [odoo/odoo#76373] opened 2021-09-12 14:36 UTC
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by OAlarconCast** [comment] 2021-09-12 14:41
![Captura de Pantalla 2021-09-12 a la(s) 8 55 00 a  m](https://user-images.githubusercontent.com/43056080/132992014-b1dd1a35-c52c-4728-91cf-d3e281274ace.png)

**Comment by pedrobaeza** [comment] 2021-09-12 14:48
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by OAlarconCast** [comment] 2021-09-12 18:09
Thank you @pedrobaeza for your comments. I'm trying to create the initial balance for one instance. 1) Odoo V14 Community Edition 2) In development mode 3 ) User with appropriate profile (Full access to accounting module) 4) Route: Billing (Accounting) / Accounting / Accounting Register / Create / Name-Date - Debit amount / Credit amount (Equal Values) / Save
5) After that I need tu publish that movement in the accounting and the button of PUBLISH that not appear (like in previous versions) 
![Captura de Pantalla 2021-09-12 a la(s) 12 57 54 p  m](https://user-images.githubusercontent.com/43056080/132998134-796b4199-a9c8-48df-8278-f219e7c463ed.png)
![Captura de Pantalla 2021-09-12 a la(s) 12 59 35 p  m](https://user-images.githubusercontent.com/43056080/132998137-a00cf3d5-366d-464e-972e-26ed8b43ef29.png)

**Comment by pedrobaeza** [comment] 2021-09-12 18:11
You need to reproduce the same problem on the runbot instance, or the problem will be something on your side.

**Comment by OAlarconCast** [comment] 2021-09-12 18:13
Ok, On it. Thanks.

**Comment by OAlarconCast** [comment] 2021-09-12 18:28
Yes, probably the error is in my site, because in the runbot works very well https://9915901-14-0-all.runbot59.odoo.com/web#id=21&action=390&model=account.move&view_type=form&cids=&menu_id=277 
![Captura de Pantalla 2021-09-12 a la(s) 1 26 49 p  m](https://user-images.githubusercontent.com/43056080/132998712-953a108e-4f6c-472e-a0dd-27baacf38a34.png)

**Comment by pedrobaeza** [comment] 2021-09-12 18:35
Check you have latest code, do an upgrade of all modules, and no third-party module is interfering.

Closing this as not possible to find an issue in standard code. We can reopen if you find any trace that leads to standard code.

**Closed by pedrobaeza** 2021-09-12 18:35 UTC
Labels: Need information
