### ISSUE TITLE
Error while uninstalling Odoo

### ISSUE THREAD

**Issue by FedwaSlimani** [odoo/odoo#27141] opened 2018-09-20 16:06 UTC
I installed Extensia theme to try it but i found many fonctionnalities don't work and when I want to uninstall it I got this error "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application" how to fix this problem ? I want to go back to the standard theme of odoo.

**Comment by pedrobaeza** [comment] 2018-09-20 16:11
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in that code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2018-09-20 16:11 UTC
