### ISSUE TITLE
Studio Error

### ISSUE THREAD

**Issue by shamasahmed** [odoo/odoo#145179] opened 2023-12-06 11:01 UTC
Impacted versions:17.0

Steps to reproduce: When Clicking on top right Studio icon, error occured.

Current behavior: When Clicking on top right Studio icon, error occured.

Expected behavior: It should run smoothly

Video/Screenshot link (optional):
![Screenshot from 2023-12-06 15-58-35](https://github.com/odoo/odoo/assets/49227061/575b4d43-842f-4af4-bb30-761ce2fb0402)

Support ticket number submitted via odoo.com/help (optional):

**Comment by vava-odoo** [comment] 2024-01-03 13:01
Hi @shamasahmed 
It seems to be working fine, so closing the issue. Don't hesitate to re-open with steps to reproduce if it still fails.
Cheers

**Closed by vava-odoo** 2024-01-03 13:01 UTC
