### ISSUE TITLE
[12.0] Could not select Membership

### ISSUE THREAD

**Issue by murtuzasaleh** [odoo/odoo#29169] opened 2018-11-30 07:24 UTC
Impacted versions: 12.0

Steps to reproduce:  Install membership module --> Open Customers --> Invoice Membership

Current behavior:

![invoice membership](https://user-images.githubusercontent.com/20418904/49273946-a2e82b00-f49c-11e8-83ce-d050989eeb36.png)

![membership](https://user-images.githubusercontent.com/20418904/49273957-abd8fc80-f49c-11e8-931b-c2be51d893ab.png)
Expected behavior: Should be able to see Membership
![in_m](https://user-images.githubusercontent.com/20418904/49274211-a29c5f80-f49d-11e8-803d-a33c12a235f1.png)

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2018-11-30 08:47
Hi, this is because now there's no demo data for this module, so you don't have any membership product:

https://github.com/odoo/odoo/commit/bed29a4aeab0ec6ef0c02975ee86655d6a030299#diff-b2fd3d6a0cc504b3ef9d03f10c235c51L32

It's not ideal, but it's not a bug, and thus I'm closing this. @tde-banana-odoo or @tivisse it would be good to restore some demo data for next iteration.

**Closed by pedrobaeza** 2018-11-30 08:47 UTC

**Comment by murtuzasaleh** [comment] 2018-11-30 09:11
@pedrobaeza 
Okay agree, But we don't have that field (memberhsip) in Product's form view and that is used in domain of Membership wizard.

**Comment by pedrobaeza** [comment] 2018-11-30 09:15
Access Members > Configuration and create the product from there.

**Comment by murtuzasaleh** [comment] 2018-11-30 09:19
Thanks, (y)
