### ISSUE TITLE
website : top menu empty if in different language

### ISSUE THREAD

**Issue by ericzen** [odoo/odoo#53673] opened 2020-06-25 13:15 UTC
Impacted versions:
Odoo 13.0+e-20200625 (Enterprise Edition) 

Steps to reproduce:
Reproduce on a fresh install and only website builder install.
You make your first install with an other language than english. In my case French.
You create a new website and use French as default language.
You install a second language : English.

Current behavior:
You go to the website to see the home page. In French, you can see the top menu.
You change the langage in English. No top menu displayed.
If you choose English language as default for the website. You go to the website homepage, you have the top menu displayed.
You change to French language. The top menu is present in French too.

Expected behavior:
Having the English top menu and the possibility to translate pages when the default language is French.
Video/Screenshot link (optional):

**Comment by bso-odoo** [comment] 2020-10-23 14:14
I cannot reproduce this problem in 13.0 (Enterprise) on 2020-10-23.

Could you confirm whether you still have the problem, and if it is the case give more detail about your specific scenario:
- first language: French, or French of a given country (I tested with general French)
- second language: which English (I tested with English US and other languages)
- does "fresh install" mean with or without demo data (I tested without demo data)
- any specific added inside the website before switching languages ? (I tested without any content and with a banner content)

**Comment by qsm-odoo** [comment] 2020-11-02 13:43
I tried to reproduce the issue as well and did not manage either. If this ever appears again, please tell us. I am closing the issue for now.

**Closed by qsm-odoo** 2020-11-02 13:43 UTC
Labels: 13.0, Website

**Comment by AtarianComputing** [comment] 2021-07-22 15:36
I have encountered this exact problem in Odoo 14. Main language has been solely English US. Now when adding Finnish as another language, the menu is blank. Also, the edit button does nothing in Finnish mode. Otherwise the translation and its functions seem to work.

I restarted Odoo service (Ubuntu). I tried a different language (French) but couldn't get it to work. I'm stumpped.

Josh.

**Comment by AtarianComputing** [comment] 2021-07-22 15:37
![msedge_d0ZHGWvLJT](https://user-images.githubusercontent.com/29645247/126667230-03152276-a3df-49d2-a46e-950fb8abc8f0.png)
![msedge_898YlI8IsQ](https://user-images.githubusercontent.com/29645247/126667241-42c5e4bb-1462-4514-8dad-6a2c19cce641.png)

**Comment by AtarianComputing** [comment] 2021-07-22 15:38
The menu items exist, you can hover over them and click them and they function correctly. They are just white.

**Comment by Selectsolution** [comment] 2022-05-15 22:19
i've the same problem, i think it's nginx server problem, because when i call the system with http with port, it works properly, but. but when i call it with https and domain, the problem happened, till now i don't know the missing server configuration leads to this problem, any idea?

**Comment by Selectsolution** [comment] 2022-05-15 22:23
This request has been blocked; the content must be served over HTTPS.

**Comment by Selectsolution** [comment] 2022-05-15 22:43
the problem was proxy_mode = True slipping out of my odoo.con
