### ISSUE TITLE
[13.0]An error occurred when I clicked on the mail module avatar

### ISSUE THREAD

**Issue by c1ayton** [odoo/odoo#49913] opened 2020-04-22 07:18 UTC
Impacted versions:
Docker container 13
Steps to reproduce:
![111111111111111](https://user-images.githubusercontent.com/30924624/79952029-55fb5f00-84ac-11ea-8d69-4e0a888ce387.png)
![22222222222222](https://user-images.githubusercontent.com/30924624/79952044-5bf14000-84ac-11ea-9f93-25a568c0e123.png)

Current behavior:

Expected behavior:
It can be adjusted as normal as clicking on the name
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2020-04-22 07:23
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by c1ayton** [comment] 2020-04-22 07:39
> 您好，感谢您的举报。您是否能够在runbot基础结构中重现该问题（[http://runbot.odoo.com/runbot-](http://runbot.odoo.com/runbot)单击版本行的蓝色门图标-admin / admin）？
> 
> 如果是这样，请说明所有可能的详细步骤以解决该错误。没有它们，很难找到问题所在。请不要怕添加细节，如果提供一些屏幕截图或视频，那就更好了。
> 
> 否则，可能是由于配置更改，您已在数据库中部署的自定义/社区模块或过时的代码所致。如果是这种情况，请报告。
> 
> 为了在此问题跟踪器中保持干净的房子，如果您在几天之内不回答，则假定这是其中所述的内容之一，它将被关闭。

[recurring.zip](https://github.com/odoo/odoo/files/4514497/recurring.zip)
I packaged the video that I recreated and it was a 20-second video.

**Comment by pedrobaeza** [comment] 2020-04-22 07:42
Can you please write down the detailed steps to reproduce the problem?

**Comment by c1ayton** [comment] 2020-04-22 07:46
> Can you please write down the detailed steps to reproduce the problem?

Using the zip I uploaded. It has video.
1.Open any module.You can edit followers.
2.Then click on the following avatar and name.Make a comparison and you'll see the problem

**Comment by pedrobaeza** [comment] 2020-04-22 07:47
What do yo mean with "Make and comparison"?

**Comment by c1ayton** [comment] 2020-04-22 07:48
> What do yo mean with "Make a comparison"?

Contrast meaning.Clicking on the avatar is not the same as clicking on the name

**Comment by pedrobaeza** [comment] 2020-04-22 07:49
OK, understood. Tagging then.

**Comment by sswapnesh** [comment] 2020-04-22 15:41
Confirmed on Runbot too
![screenshot-2330034-13-0-acd1ee runbot44 odoo com-2020 04 22-21_10_23](https://user-images.githubusercontent.com/16624719/80002788-b9ea4b80-84dd-11ea-8379-f0b88335d74e.png)
```

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/data/build/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/data/build/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/data/build/odoo/odoo/http.py", line 318, in _call_function
    raise werkzeug.exceptions.BadRequest(msg % params)
werkzeug.exceptions.BadRequest: 400 Bad Request: <function Home.web_client at 0x7f8af01328c8>, /web: Function declared as capable of handling request of type 'http' but called with a request of type 'json'
```

**Comment by Yenthe666** [comment] 2020-05-13 11:07
OPW `2256795`

**Comment by Yenthe666** [comment] 2020-05-25 11:30
Fixed in https://github.com/odoo/odoo/commit/11c4a2907e635662216ebc0e745f0ce9d16771cb

**Closed by Yenthe666** 2020-05-25 11:30 UTC
Labels: 13.0, Discuss, OE
