### ISSUE TITLE
United state Cart of account for multi company

### ISSUE THREAD

**Issue by odoouser2** [odoo/odoo#18700] opened 2017-08-06 09:42 UTC
Impacted versions: 10 Community

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):
Hello,
Greetings,

I use odoo V10 Community edition.I use multi company features. I have installed "United States - Accounting" but it does not appear in the Account >>setting>> Chart of Account template

Please suggest the process to assign it to other company too...
Attached is the details.

Lets say I have A parent company and B C and D are their child company. How to assign United state COA to all companies?

![coa](https://user-images.githubusercontent.com/21218238/29002129-7183708a-7abb-11e7-8c4d-a7cf768ea29a.jpg)
![coa1](https://user-images.githubusercontent.com/21218238/29002131-7344795a-7abb-11e7-90c7-5b9ad9f22de9.jpg)

**Comment by Yenthe666** [comment] 2017-08-07 06:25
Duplicate of https://github.com/odoo/odoo/issues/18428 and https://github.com/odoo/odoo/issues/18373 please stop doing that and give people the time to give feedback. We can't be on every issue all the time and duplicating issues only makes it worse.

**Closed by Yenthe666** 2017-08-07 06:25 UTC

**Comment by odoouser2** [comment] 2017-08-08 04:12
This issue is not closed. So please just comment and don't close it.
