### ISSUE TITLE
[8.0]Advance filter menu Overlapping the filter zone in popup menu

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#3224] opened 2014-10-21 14:57 UTC
Hy,

In sale.order.line, when you make a search more and display advanced search, there is an inconvenient overlapping :
![sujet standardisation1](https://cloud.githubusercontent.com/assets/1043935/4720642/85defa84-5932-11e4-81b9-98f5c7619c72.png)

**Comment by flotho** [comment] 2015-04-22 20:24
Hy @ged-odoo , any chance to be reviewed on this?

**Comment by ged-odoo** [comment] 2015-04-23 08:21
Hey flotho, not sure what you mean, but this is a bug report, not a PR that can be reviewed.  It is indeed a bug, and it should be fixed.  Anyone can submit a PR, and if it is good, it will be merged.  However, I don't have the time to solve this particular bug myself.

**Comment by flotho** [comment] 2015-04-27 15:50
@ged-odoo, great thanks for your answer

**Comment by Yenthe666** [comment] 2016-10-03 10:28
Hi @flotho,

Thanks a lot for your report!
The issue has been fixed in the meanwhile and I can no longer reproduce this.
I'm closing this issue since it has been solved (the duplicate is fixed too).

Regards,
Yenthe

**Closed by Yenthe666** 2016-10-03 10:28 UTC
