### ISSUE TITLE
[17.0] Can not set home action by TypeError: e.target.getSelection is not a function

### ISSUE THREAD

**Issue by Bonainifo** [odoo/odoo#140276] opened 2023-10-30 10:38 UTC
Impacted versions:
Odoo 17.0
Steps to reproduce:
1、Creat an database and install an app such as Invoicing
2、Enable debug mode with assets
3、Open Setting，and open any user and change to Preference page
4、In Home Action type apps to select
Current behavior:
TypeError: e.target.getSelection is not a function
    _selectQwebNode/<@http://dmmsys:8090/web/assets/debug/web.assets_web.js:152302:40 (/web_editor/static/src/js/backend/QWebPlugin.js:138)
![Image](https://github.com/odoo/odoo/assets/46485742/7638a8ea-7d14-4944-af16-9f7f7c521d64)

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by manishkumarbohra** [comment] 2023-11-07 21:03
Hello @Bonainifo , 
unable to reproduce the same issue.
Kindly, pull updated code and check.

**Comment by vava-odoo** [comment] 2023-11-13 11:08
Hi @Bonainifo
Thanks for reporting.
This was fixed with https://github.com/odoo/odoo/pull/140143.
Cheers!

**Closed by vava-odoo** 2023-11-13 11:08 UTC
Labels: 17.0
