### ISSUE TITLE
Import Chart of Account Odoo 12 EE

### ISSUE THREAD

**Issue by usmanfarzandali** [odoo/odoo#36034] opened 2019-08-23 15:18 UTC
Impacted versions:
Odoo 12 EE
Steps to reproduce:
Creating issue on Payable and Receivable account 
i Install Accounting then i install United State COA when i import i face this issue

Current behavior:
![Screenshot from 2019-08-23 20-14-05](https://user-images.githubusercontent.com/22232100/63603248-a9966f80-c5e2-11e9-9748-ecb4430f0106.png)

Expected behavior:

Video/Screenshot link (optional):

![Screenshot from 2019-08-23 20-12-11](https://user-images.githubusercontent.com/22232100/63603286-c632a780-c5e2-11e9-88bc-a3e543f03374.png)
![Screenshot from 2019-08-23 20-11-55](https://user-images.githubusercontent.com/22232100/63603293-cd59b580-c5e2-11e9-93ca-47c314af18e3.png)

**Comment by pedrobaeza** [comment] 2019-08-23 15:31
@usmanfarzandali the problem is the indicated: you must set as reconciliable those account that are receivable. Add the column for that field and set it.

Closing as no real Odoo issue, but misuse.

**Closed by pedrobaeza** 2019-08-23 15:31 UTC
Labels: 12.0, Accounting
