### ISSUE TITLE
Error while loading xls file when importing

### ISSUE THREAD

**Issue by implementosk** [odoo/odoo#41828] opened 2019-12-13 09:43 UTC
Impacted versions:
13.

Steps to reproduce:
Load .xls file when importing data

Current behavior:
Error

Expected behavior:
Should work without error

Video/Screenshot link (optional):
<img width="979" alt="Screenshot 2019-12-13 at 09 52 02" src="https://user-images.githubusercontent.com/35446152/70790410-4d27ad80-1d95-11ea-8e30-a09d32a5fbf5.png">

**Comment by pedrobaeza** [comment] 2019-12-13 09:49
Unless you specify more what are you importing, which data, etc, we have to assume the XLS is incorrect.

**Comment by mart-e** [comment] 2020-01-31 07:48
Closing as not enough information to reproduce. As said Pedro, assuming the issue is in the file content.

**Closed by mart-e** 2020-01-31 07:48 UTC
Labels: Need information
