### ISSUE TITLE
[9.0] Inheritance view doesnt provide string selector anymore

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#9000] opened 2015-10-10 02:25 UTC
Hi Odoo,

In version 9, you make the inheritance view doesnt support string selector anymore,
why you are doing this?
it makes the modification of view is harder than before,

For the example when we want to make another page in notebook,
we can't have flexibility to add it after which page.

Yes I see on your sale_crm_view that you add the name on the page,
but there's a lot of it that you dont provide the name, (for example on mrp form)

I think you must add all the name on each page or it must be required on the framework,
so we can have a flexibility to inherit it.

This is the only case that I think, but it should be a lot of issue that you cause of this change.

**Comment by yaho9** [comment] 2015-10-11 09:15
I'm completely agree with this, the problem is that the name is not everywhere.
Here is my tip for this problem :
\<xpath expr="//notebook[last()]" position="inside">
                    \<page string="my page">

**Comment by nhomar** [comment] 2015-10-11 09:53
You can look the commit message with this change.

And yes it can be a little problematic, but the technical reason is good, the String is used for the new translation system and it mst be blocked.

What I recommend is that if you find places where tthe name is not present either pivot in other place or monkey patch your server or try to make a PR asking to add the name on such element.

Frequently with some of this 3 options you will solve the problem.

Regards.

**Comment by nhomar** [comment] 2015-10-11 10:00
This is a related explained [issue](https://github.com/odoo/odoo/issues/8662#issuecomment-145097156)

**Comment by falinwa** [comment] 2015-10-12 01:41
ok, I have seen that we can have an index like this:
You can use indexes in XPath, like //page[2] (note: it starts from 1, not 0).

I never tried it, but if it works, it will solve the problem.
Thank You.

**Comment by xmo-odoo** [comment] 2015-10-12 08:12
@falinwa you need brackets for indexed access e.g. `//page[2]`. Which really is just a shortcut for `//page[position()=2]`.

Anyway closing since you got your answer.

**Closed by xmo-odoo** 2015-10-12 08:12 UTC
