### ISSUE TITLE
[11.0] Debian package mrp_workorder_kanban.scss file not found.

### ISSUE THREAD

**Issue by ieski** [odoo/odoo#48227] opened 2020-03-24 08:04 UTC
Impacted versions: 11.0

Steps to reproduce: -

Current behavior: debian package in "/mrp/static/src/scss/mrp_workorder_kanban.scss" file not found.

Expected behavior: -

Video/Screenshot link (optional): http://prntscr.com/rkywel

**Comment by pedrobaeza** [comment] 2020-03-24 08:07
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/11.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).

**Comment by kosz85** [comment] 2020-04-08 22:34
Please reopen this issue, and check your own packages:
http://nightly.odoo.com/11.0/nightly/src/odoo_11.0.20200407.tar.gz
http://nightly.odoo.com/11.0/nightly/src/odoo_11.0.20200407.zip
http://nightly.odoo.com/11.0/nightly/deb/odoo_11.0.20200407_all.deb

In all this, there is no folder in `mrp` module `static/src/scss/mrp_workorder_kanban.scss`

But here: http://nightly.odoo.com/11.0/nightly/deb/odoo_11.0.20200408.tar.xz
There is this file :) seems like your building is filtering this file, making debs and sources not correct. Its visible only when you install mrp module.

**Comment by pedrobaeza** [comment] 2020-04-09 07:02
OK, thanks for the extra details. Indeed, in that package is missing.

@d-fence can you please check that?

**Comment by mlaitinen** [comment] 2020-04-13 17:32
The manifest file https://github.com/odoo/odoo/blob/11.0/MANIFEST.in doesn't include `scss` files like it does in the `13.0` branch. That's why they're not included in the debian package.

**Comment by d-fence** [comment] 2020-04-14 12:14
The problem is not packaging, 11.0 is not using scss but less. This file has nothing to do there.
I'm closing this issue. The fix is in progress.

**Closed** 2020-04-14 12:15 UTC
Labels: 11.0, Packaging

**Comment by kosz85** [comment] 2020-04-14 12:58
Can you link to the correct issue fixing this scss problem?

**Comment by d-fence** [comment] 2020-04-14 13:03
Fix proposal here: #49535
