### ISSUE TITLE
[9.0] When developer mode is activated, the UI is all messed up

### ISSUE THREAD

**Issue by jbeficent** [odoo/odoo#8681] opened 2015-09-23 13:57 UTC
The classical UI cannot be used at all when I log as admin and activate the developer mode. Menus not accessible, screen does not show anything.

![image](https://cloud.githubusercontent.com/assets/7683926/10046907/b3e3d688-620b-11e5-9d47-7bee44596e0d.png)

**Comment by jni-odoo** [comment] 2015-09-23 14:09
Hello jbeficent ,

They are visible see: https://drive.google.com/file/d/0B5j41T1Hqv1sR0Fzc0c2R1cxb1U/view?usp=drivesdk

May be there is some problem of reloading or refreshing , or you can take the latest pull..

Thanks,
Nikunj Jani (Odoo India)

**Comment by jbeficent** [comment] 2015-09-23 14:14
@jni-odoo you are right. When I refresh the problem disappears. But the before refreshing it is all wrong. I took the latest pull from 2 hours ago.

**Comment by mart-e** [comment] 2015-09-23 14:22
Is it possible you get some files in cache from a previous version (e.g. you are also testing the 8.0 locally) ?

**Comment by jbeficent** [comment] 2015-09-23 14:28
Well, not executing the 8.0 at the moment, but yes, I was on both sometimes.

**Comment by mart-e** [comment] 2015-09-23 14:36
So try with an empty cache if you can reproduce this issue as well but that's probably just an old css file cached in the browser.

**Comment by tilaprimera** [comment] 2016-03-05 14:13
In 9.0c this problem is persisting. I opened #11212 . Please see.

**Comment by lukebranch** [comment] 2016-03-06 09:04
i've encountered this issue many times as well on 9.0C, usually right after upgrading modules.

If I can find a specific set of steps to reproduce i'll write back with steps and an animated screen grab (GIF) of the whole process.

**Comment by tilaprimera** [comment] 2016-03-06 09:36
Despite restarting server, the error persisted for a long time. But in incognito, it worked. Hence, I removed cache and it is working now. I will close this.

**Comment by SakaRicky** [comment] 2016-03-09 00:09
I have the same issue on version 9. The sidebar become invisible and cannot update list

**Comment by Yenthe666** [comment] 2016-05-25 07:06
Hi @jbeficent,

This issue isn't present in the latest version anymore and as said above this was probably a cache problem.
I'm closing this issue since there has been no more comment in months and everything works fine on the latest runbot.
Should you be able to reproduce this issue again or if you think this is not fixed don't hesitate to comment on this.

Regards,
Yenthe

**Closed by Yenthe666** 2016-05-25 07:06 UTC
