### ISSUE TITLE
this place has a bug

### ISSUE THREAD

**Issue by mxz19901102** [odoo/odoo#37189] opened 2019-09-20 09:26 UTC
model:  account.abstract.payment     method:  _compute_journal_domain_and_types

line:188    has_invoices is not a field of this model

**Comment by pedrobaeza** [comment] 2019-09-20 09:28
Which version? And please don't make reference to line numbers, as this moved in time. Provide the permalink at least.

**Comment by sswapnesh** [comment] 2019-09-20 14:51
Seems duplicate of https://github.com/odoo/odoo/issues/31411
Related PR https://github.com/odoo/odoo/pull/32847

**Comment by pedrobaeza** [comment] 2019-09-20 16:22
Yes, closing.

**Closed by pedrobaeza** 2019-09-20 16:22 UTC
