### ISSUE TITLE
The line is comment and also running 

### ISSUE THREAD

**Issue by mohamednooralamin** [odoo/odoo#41703] opened 2019-12-11 11:20 UTC
Impacted versions:V12 community

Steps to reproduce:
```
<record model="ir.ui.view" id="school_management_form">
      <field name="name">School Management Form</field>
      <field name="model">school_management.school_management</field>
      <field name="arch" type="xml">
        <form>
            <header>
                <button string="Confirm Day" name="confirm_day" type="object" class="oe_highlight"/>
<!--                <button string="Change Rank" name="%(school_management.action_change_rank)d" type="action" class="oe_highlight"/> -->
            </header>

```

Current behavior: External id not found 

Expected behavior:No exception 
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2019-12-11 11:22
That's because all the content is parsed and if a reference is found, it's solved before interpreting the XML itself, so it's something expected. Remove the line instead.

Closing as no issue, but expected behavior.

**Closed by pedrobaeza** 2019-12-11 11:22 UTC

**Comment by obayit** [comment] 2019-12-12 10:00
This is ABSOLUTELY not expected :(
However, a more explanatory exception message would be good enough.
