### ISSUE TITLE
"Unsubscribe" in Massmail doesn't work

### ISSUE THREAD

**Issue by auditum-sbl** [odoo/odoo#22087] opened 2018-01-08 13:45 UTC
Impacted versions:
Odoo 10 

Steps to reproduce:
Click in a Massmail on "Unsubscribe"

Current behavior:
Redirect to a 404 error page called "/ unsubscribe_from_list"

Expected behavior:
User should be removed from the Massmail Recipient list and redirected to a page that confirms the logout

Video/Screenshot link (optional):
![bildschirmfoto 2018-01-08 um 14 40 30](https://user-images.githubusercontent.com/22189188/34673375-58c249ae-f482-11e7-8d51-e4740a67415a.png)

**Comment by qsm-odoo** [comment] 2018-01-17 11:28
Hello,

It appears to be working on my side. When you create a template, the unsubscribe links do indeed have the `/unsubscribe_from_list` url but, when the mail is sent, this link should be automatically converted to a personalized link (for the user it is sent to).

I am closing the issue. If you are still facing the issue on sent emails, please ask me to reopen the issue and give me details about how you sent the mass mailing and how you created the template. Thanks! :)

**Closed by qsm-odoo** 2018-01-17 11:28 UTC
Labels: 10.0, Services

**Comment by SamTzu** [comment] 2018-09-18 16:33
I can confirm this problem on Ubuntu/odoo11 installed from odoo repo with apt-get.
/unsubscribe_from_list does not work (our server is behind a firewall that NAT's translate address's from http => https.

**Comment by SamTzu** [comment] 2018-09-18 18:11
My bad. Unsubscribe does not work with Test emails but works with the actual mailing lists.

**Comment by benjbt** [comment] 2018-10-11 05:43
I am having this problem on Ubuntu-18.04LTS/Odoo 11.0-20180518 (Community Edition) 

Steps to recreate...
1. Create Mass Mailing Campaign using HTML template (change nothing)
2. Filter recipients to email="my-email"
3. Send campaign
4. Click on unsubscribe link in email footer

Result is I am sent to http://mydomain.com.au/en_AU/unsubscribe_from_list

404: Page not found!

The page you were looking for could not be found; it is possible you have typed the address incorrectly, but it has most probably been removed due to the recent website reorganisation.

Maybe you were looking for one of these popular pages ?

Notes: base.url DOES NOT have a trailing /

**Comment by ggive** [comment] 2018-12-10 12:50
Hello,

I'm having the same issue on Ubuntu/Odoo 11 thus user can't unsubscribe from list.
Does anyone have an idea of how to solve this issue or point a workaround on how to overcome this issue ?

**Comment by benjbt** [comment] 2018-12-10 22:51
@qsm-odoo can you please reopen this issue

**Comment by pedrobaeza** [comment] 2018-12-10 23:00
The problem usually comes from an incorrect deployment. For example, deploying Odoo behind a proxy, but not adding `proxy_mode = True` in the Odoo config file, or having an incorrect `web.base.url` system parameter. It's working also on my side, so no need for reopening this IMO.

**Comment by ggive** [comment] 2018-12-12 18:24
Thanks for the quick reply.
I'm not using any proxy thus I guess that the issue may come from `web.base.url` system parameter. 
How this should looks ?

The site is in 3 languages, after testing by removing language parameter from [http://mydomain.com.au/en_AU/unsubscribe_from_list](http://mydomain.com.au/en_AU/unsubscribe_from_list) to [http://mydomain.com.au/unsubscribe_from_list](http://mydomain.com.au/unsubscribe_from_list) in mailing template, it's work well... the issue maybe related to multilingual platform ? Is there any settings to ajust in order to solve the problem ?
