### ISSUE TITLE
[11.0] Date(time) fields not editable in Firefox

### ISSUE THREAD

**Issue by adaptivdesign** [odoo/odoo#23438] opened 2018-03-02 15:29 UTC
Impacted versions:

11.0
FireFox 58.0.2 (tested on OSX and Windows 10)

Steps to reproduce:

- Go to any date(time) field, for example go to task -> deadline.
- If the field is empty, pick a date.
- Now try to edit the date directly, with keyboard / mouse

Current behavior:

- Date(time) text is not selectable. Type cursor is positioned at beginning of the text, and does not allow backspace. 

Expected behavior:

- Being able to edit datetime with keyboard controls / mouse. And not have to resort to the picker overlay. See Chrome for normal use.

Video/Screenshot link (optional):

**Comment by mge-odoo** [comment] 2018-03-19 12:35
Hi @adaptivdesign 

Thanks for reporting the bug.

I have tested on Firefox 59 on Ubuntu and the issue still appears.
Actually you can edit the input directly ; the issue is with the visual representation of the carret position (and selection) so it's not really blocking, just really disturbing.

I'm trying to figure out what's going on here but they problem probably comes from the datepicker lib update from 3 to 4 (see https://github.com/odoo/odoo/commit/ad6fd5f838e174cc6e354bb9998e1e5bc4e8d4f1)

Regards,

Martin

**Comment by adaptivdesign** [comment] 2018-03-19 12:46
Thank you @mge-odoo  for looking into  this! Yes it is a annoying one, couldn't find the problem. Good luck!

**Comment by mge-odoo** [comment] 2018-10-11 12:20
Hi @adaptivdesign 

Sorry for the long delay, we were quite busy with the new release.
The issue has been fixed in 11.0 with the rev. odoo/odoo@f249c5e

Regards,

Martin

**Closed by mge-odoo** 2018-10-11 12:20 UTC
Labels: 11.0, Framework
