### ISSUE TITLE
[>=8.0] Filters are shown in inventory with wrong group

### ISSUE THREAD

**Issue by pablocm-aserti** [odoo/odoo#7818] opened 2015-07-31 07:36 UTC
Impacted versions:
8.0 and onwards

Steps to reproduce:
1. Check issue #7817 and make sure it is solved or at least make sure there is still an stock.config.settings record on the database.
2. Enable "Use packages: pallets, boxes, ... " (group_stock_tracking_lot) and disable "Track lots or serial numbers" (group_stock_production_lot)
3. Create a new stock.inventory.

Current behavior:
The filter to select a lot is shown
The filter to select a package is not shown

Expected behavior:
The filter to select a lot should be hidden
The filter to select a package should be shown

Analysis and solution:
Wrong groups are being tested [here](https://github.com/odoo/odoo/blob/2d407de5d4eddada0d46b1ed2b0d43fdc749deda/addons/stock/stock.py#L2651-L2654).
Please, change group_stock_tracking_lot for group_stock_production_lot and group_stock_packaging for group_stock_tracking_lot.

**Comment by Yenthe666** [comment] 2017-11-26 16:21
Hi @pablocm-aserti ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
Also duplicate of https://github.com/odoo/odoo/issues/7817

Regards,
Yenthe

**Closed by Yenthe666** 2017-11-26 16:21 UTC
Labels: Logistics
