### ISSUE TITLE
Restaurant Module Error installed

### ISSUE THREAD

**Issue by Cu4rach4** [odoo/odoo#14705] opened 2016-12-13 21:14 UTC
Impacted versions: 8.0

Steps to reproduce: After installed chilean localization from BMYA (odoo-chile)

Current behavior:
`Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 539, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 576, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 312, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 309, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 805, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 405, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/module/module.py", line 447, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/module/module.py", line 495, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 176, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 900, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 986, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 852, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 756, in _tag_record
    f_val = _eval_xml(self,field, self.pool, cr, self.uid, self.idref)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 176, in _eval_xml
    for n in node]), idref)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 165, in _process
    idref[id] = self.id_get(cr, id)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 831, in id_get
    res = self.model_id_get(cr, id_str, raise_if_not_found)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 842, in model_id_get
    raise_if_not_found=raise_if_not_found)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_model.py", line 905, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(cr, uid, xmlid)[1:3]
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in xmlid_lookup
  File "/usr/lib/python2.7/dist-packages/openerp/tools/cache.py", line 74, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_model.py", line 895, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % (xmlid))
ParseError: "External ID not found in the system: l10n_cl_invoice.action_account_journal_document_config_form" while parsing /opt/odoo/stable-addons/bmya/odoo-bmya-cl/l10n_cl_invoice/views/journal_view.xml:16, near
<record id="view_account_journal_cl_form" model="ir.ui.view">
            <field name="model">account.journal</field>
            <field name="name">account.journal.ar.form</field>
            <field name="inherit_id" ref="account.view_account_journal_form"/>
            <field name="arch" type="xml">
                <data><field name="type" position="after">
                    <field name="use_documents" attrs="{'invisible': [('type','not in',['purchase','sale','purchase_refund','sale_refund'])]}"/>
                </field>
                    
                <notebook position="inside">
                    <page string="Documents" attrs="{'invisible': ['|',('use_documents','=',False),('type','not in',['purchase','sale','purchase_refund','sale_refund'])]}">
                        <button name="%(action_account_journal_document_config_form)d" string="Create Journal Documents" type="action" context="{'type':type, 'excempt_documents': excempt_documents}"/>
                        <group>
                            <field name="point_of_sale_id" attrs="{'invisible': ['|',('type','not in',['sale','sale_refund'])],'required': [('use_documents','=',True),('type','in',['sale','sale_refund'])]}" context="{'default_company_id':company_id}"/>
                            <field name="point_of_sale" attrs="{'invisible': ['|',('type','not in',['sale','sale_refund'])]}"/>
                            <field name="journal_activities_ids" attrs="{'invisible': ['|',('type','not in',['purchase','sale','purchase_refund','sale_refund'])],'required': [('use_documents','=',True),('type','in',['sale','sale_refund'])]}" context="{'default_company_id':company_id}" placeholder="Giros del Diario" widget="many2many_tags" options="{'no_create': True}" domain="[('partner_ids', '=', company_id)]"/>
                            <field name="excempt_documents" readonly="True"/>
                            
                        </group>
                        <field name="journal_document_class_ids" context="{'journal_type':type}"/>
                    </page>
                </notebook>
            </data></field>
        </record>`

Expected behavior:

How i can solved this, to install a restaurant module!

Thanks!

**Comment by Yenthe666** [comment] 2016-12-14 07:21
Hi @Cu4rach4,

Thanks a lot for your report. I've just tested this and I can install the account and the restaurant module without any problems.
Could you please try to reproduce it on a runbot (runbot.odoo.com) or update your Odoo to the latest source code and try again?

Regards,
Yenthe

**Comment by Cu4rach4** [comment] 2016-12-14 19:24
>  Hi @Cu4rach4,
> 
> Thanks a lot for your report. I've just tested this and I can install the account and the restaurant module without any problems.
> Could you please try to reproduce it on a runbot (runbot.odoo.com) or update your Odoo to the latest source code and try again?
> 
> Regards,
> Yenthe

Thanks for the fast reply, unfortunately, i can't, i used odoo 8.0 and runbot version crash when i try to login with my odoo account.

I install odoo from where: https://hub.docker.com/r/bmya/odoo-bmya/

because they have al chilean localization done in that container, when i tried to install from 0 i have many problems to install lacalization.

Thanks.

**Comment by dvdhinesh** [comment] 2016-12-16 08:57
@Cu4rach4 I can reproduce this issue and its not related to Odoo, but with this module [l10n_cl_invoice](https://github.com/odoo-chile/l10n_cl_invoice)

You can refer the PR for more info and i guess Odoo can close this issue.

**Comment by Yenthe666** [comment] 2016-12-16 09:03
Hi @Cu4rach4,

As stated by @dvdhinesh the issue looks to be coming from l10n_cl_invoice. This module however is not an official Odoo module. The bug management from Odoo is only for bugs in the official code, not for third party modules.
I'm closing this issue because of that.

Regards,
Yenthe

**Closed by Yenthe666** 2016-12-16 09:03 UTC
