### ISSUE TITLE
Landed costs in COGS with anglo-saxon accounting

### ISSUE THREAD

**Issue by max3903** [odoo/odoo#13139] opened 2016-08-12 20:23 UTC
# Impacted versions

9.0
# Steps to reproduce
## Configuration
- Activate anglo-saxon accounting
- Configure your product category with real price and perpetual inventory and the expense account as a COGS account
- Configure your product with a price of 0.5 $ and an initial cost of 0.1 $
- Configure brokerage, custom duties and transportation as landed cost products with their expense accounts as an expense account in the CoA
- Configure your Landed Costs journal to use the inventory account
## Purchase/Receiving Process
- Create a purchase order for 10,000 items of your product and confirm it
- Do the receiving of the 10,000 items
- Receive the vendor bill (1,000$), validate it and pay it
- Receive the broker (100$), customs (200$) and transportation (1,000$) bills:
  - Create the vendor bills, validate them and pay them
  - Create the landed cost for the incoming shipment, compute it and validate it
- Generate the General Ledger
## Sale/Delivery Process
- Create a quotation to sell 10,000 items of your product and confirm it
- Create the customer invoice (5,000$), validate it and register the payment
- Deliver the 10,000 items to the customer
- Generate the General Ledger
# Current behavior
## After the Sale/Delivery Process
- I have 1,300$ remaining in my output stock account
- I have 1,000$ in my COGS account
- My expenses accounts (Brokerage fee, Custom fee and Transportation) have a zero balance
# Expected behavior
## After the Sale/Delivery Process
- I have 0$ remaining in my output stock account
- I have 2,300$ in my COGS account
- My expenses accounts (Brokerage fee, Custom fee and Transportation) have a zero balance

**Comment by max3903** [comment] 2016-08-12 20:33
Reported to Odoo support as ticket # 686054.

**Comment by max3903** [comment] 2016-08-12 20:40
...and to add some fun, I could be expecting my COGS balance (2,300$) to be split into different accounts:
* Purchased product (COGS): 1,000$
* Brokerage fee (COGS): 100$
* Custom duties (COGS): 200$
* Transportation (COGS): 1,000$

**Comment by vcloud9ray** [comment] 2017-11-27 20:32
@max3903 - Hola/Bonjour - was this resolved?

**Comment by max3903** [comment] 2017-11-27 20:45
@vcloud9ray I don't remember. I can check on friday at the earliest.

**Comment by max3903** [comment] 2017-12-01 21:38
@vcloud9ray Nope.

**Comment by vcloud9ray** [comment] 2017-12-01 22:39
@max3903 - UGH - thanks for checking!!

**Comment by Yenthe666** [comment] 2017-12-04 09:19
Hey guys,

I've labelled it so it atleast pops up to the right guys.
If one of you can still reproduce it and has an enterprise license I suggest to report it there.

Regards,
Yenthe

**Comment by vcloud9ray** [comment] 2018-02-13 23:01
Still happens at v10.  

Stock Interim delivered gets a credit of $1000 (counterpart COGS debit of $1000) during the Invoice and a debit of $2300 (counterpart RAW MATERIALS of $2300) during the Delivery.

Note: Need to configure Invoicing Policy of Product to "Ordered Quantities".

standard_price on the product isn't updated until the delivery, so that's why the Invoice uses to pre-landed cost.

**Comment by max3903** [comment] 2018-02-13 23:47
@vcloud9ray If I remember well, landed costs can only be used if the costing method is real. It doesn't work with standard or average.

**Comment by vcloud9ray** [comment] 2018-02-14 00:42
@max3903 - agreed - this is true - the cost field on the product is still called standard_price though, even when real time costing is enabled.

**Comment by pedrobaeza** [comment] 2018-04-25 23:49
Is this still happening?

**Comment by vcloud9ray** [comment] 2018-04-27 19:48
I haven't tested since Feb - it was still happening at that point.

**Comment by gustavovalverde** [comment] 2018-06-07 11:13
Confirming this issue

**Comment by gustavovalverde** [comment] 2018-06-07 11:33
@max3903 How are you dealing with https://github.com/odoo/odoo/issues/13139#issuecomment-239554280? This is still true in v11.

@pedrobaeza  maybe the labeling should be updated to include 10.0 and 11.0?

**Comment by max3903** [comment] 2018-06-07 13:19
@gustavovalverde Here is their final answer:

```
We have discussed for the problem you have recorded.

As I said you are required to deliver the product first and invoice it after the delivery, when you have category costing method real time as well anglo-saxon is enabled.

But in your case Invoicing first is mandatory then you should disable the anglo-saxon accounting and keep the Expenses account and Stock output account as COGS.

After that you can check to make the invoice first and deliver the products later.
```

**Comment by pedrobaeza** [comment] 2018-06-08 19:53
Then we can close this according to the answer.

**Closed by pedrobaeza** 2018-06-08 19:53 UTC
Labels: 10.0, 11.0, 9.0, Accounting

**Comment by vcloud9ray** [comment] 2018-06-08 23:07
Annoying, but I was just reminded that GAAP /SOX compliant Accounting you can't invoice until you've shipped product (because you can't book Sales Revenue - if you do you have UNEARNED REVENUE), so perhaps you are really just taking a DEPOSIT.  Hmm...

I am more concerned about how to resolve the true COGS when the LANDED COST isn't adjusted until AFTER the Customer Delivery has been made.
