### ISSUE TITLE
Wrong translations url in multilang environment

### ISSUE THREAD

**Issue by unwasted** [odoo/odoo#41731] opened 2019-12-11 15:57 UTC
https://github.com/odoo/odoo/blob/b62b2828552abb38c8adc74c69cb427c3fd98605/addons/http_routing/models/ir_http.py#L312

There should be lang suffix for multilang website and for non default language.
No need to do request /website/translations(hash?)
if it gets redirected to /en/website/translations

**Comment by pedrobaeza** [comment] 2019-12-11 16:01
Please share with us steps to reproduce a problem. If not, your guess can't qualify as a bug.

**Comment by unwasted** [comment] 2019-12-11 16:40
1) Make a website at least 2 languages
2) choose lang (a) as default and lang (b) as selectable
3) From frontent, select lang (b) .. so that url will became /<lang b key>/
4) Observe the communication between server:
- 1. request will be /website/translations with a response status 302
- 2. request will be /<lang b key>/website/translations

**Comment by pedrobaeza** [comment] 2019-12-11 16:43
But I think that's not an error, but an observation of something that you think it's not correct, but it should have its logic associated.

**Comment by unwasted** [comment] 2019-12-11 16:46
Don't know if it's an error or not but why make 1 unnecessary request for nothing - before showing user the translations?

**Comment by pedrobaeza** [comment] 2019-12-11 16:50
As said, you don't know if it's useless or not (me neither), but this is definitively not an error, so closing this.

**Closed by pedrobaeza** 2019-12-11 16:50 UTC
Labels: Need information

**Comment by unwasted** [comment] 2019-12-11 16:55
I know that it's useless request! - Only to reroute to correct language url!

**Comment by pedrobaeza** [comment] 2019-12-11 16:58
Then propose a pull request with the code not needing that reroute

**Comment by rdeodoo** [comment] 2019-12-11 17:13
Hi @unwasted thanks for the report (and reaching me by email about this PR).

I do agree with @pedrobaeza, maybe it could be improved to not go through that redirection (I didn't check and I don't know without investigating if it could be done) but that's not a bug.
This issue is therefore not ingluded in the ones we can make a 'fix' for.

Note that any improvement pull request are always welcome.
