### ISSUE TITLE
Can't set value as negative in qweb report

### ISSUE THREAD

**Issue by ShamsulArifin** [odoo/odoo#65916] opened 2021-02-11 06:40 UTC
Impacted versions:10.0

Steps to reproduce:
i added a condition like: 
if payment_type == outbound
    set amount = -1 * amount
but the doesn't seem to have any effects
![Capture](https://user-images.githubusercontent.com/52891680/107608384-0ae25080-6c66-11eb-8885-89bed3cbbf7b.PNG)

**Comment by pedrobaeza** [comment] 2021-02-11 07:10
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2021-02-11 07:10 UTC

**Comment by ShamsulArifin** [comment] 2021-02-11 07:16
> 
> 
> Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.
> 
> Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.
> 
> If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

sure...
