### ISSUE TITLE
Odoo Client Error when Adding new Product Category

### ISSUE THREAD

**Issue by c0fe** [odoo/odoo#124931] opened 2023-06-13 19:31 UTC
Impacted versions: 16.0-20230611

Steps to reproduce:

Go to add new product. Click on Product Category and start typing in.

Current behavior:

Throws an error:

```
UncaughtPromiseError > TypeError
Uncaught Promise > can't access property "reject", this.loadingPromise is null
TypeError: can't access property "reject", this.loadingPromise is null
    setup/this.debouncedProcessInput<@https://odoo.mydomain.com/web/assets/237-bb5271e/web.assets_backend.min.js:31:976
```

Expected behavior:

Let's you add a product category without errors

**Comment by ChristianAutmix** [comment] 2023-06-13 23:23
We have the same error on the latest version of Odoo SH, when typing to find a product in a Purchase Order.

Impacted versions: 16.0-20230612

Steps to reproduce:

Go to add Purchase Order and start typing to add a product.

Current behavior:

Throws an error:
`UncaughtPromiseError > TypeError
Promesa desconocida > Cannot read properties of null (reading 'reject')
TypeError: Cannot read properties of null (reading 'reject')
    at AutoComplete.<anonymous> (https://domain.odoo.com/web/assets/6991-9b32bed/web.assets_backend.min.js:38:996)`

Expected behavior:

Add a product to Purchase Order without errors

**Comment by niyasraphy** [comment] 2023-06-14 03:50
hi @c0fe @ChristianAutmix ,
this is a bug get introduced in this commit: https://github.com/odoo/odoo/commit/0fa4a83a43c355f19d95f13a8412f1561588e28f and later it has been fixed in this commit: https://github.com/odoo/odoo/commit/a750e61544138a9d533f3391fbd2a179697fd7b4

if you are using odoo online/odoo sh, you will get the updates by the next week, as the source code is updated on weekly basis, and if you are using the odoo sh, you can set the odoo version to previous week source code from the settings to resolve the issue and next week you can set back the source code to latest. and if you are using own premise instance, pulling the latest source code will resolve the case.

thanks

**Comment by tmkhalid** [comment] 2023-06-14 07:44
@niyasraphy We are getting the same error while searching and adding products in sales order line. As you advised, we will set the Odoo version to previous week source code and will check. 

Just would like to know, Is there any specific day of a week for source code update ?

Thanks,

**Comment by niyasraphy** [comment] 2023-06-14 07:45
@tmkhalid ,
source codes are updated on sunday i believe(weekly basis) for odoo sh and odoo online.
thanks

**Comment by tmkhalid** [comment] 2023-06-14 08:05
@niyasraphy Setting back to 16.0.20230605 solved this issue. Thank you..

**Comment by FrancoisKr** [comment] 2023-06-14 16:27
> @tmkhalid , source codes are updated on sunday i believe(weekly basis) for odoo sh and odoo online. as of now setting the revision back to **16.0.20230605** will resolve the issue.
> 
> thanks

Monday a the build versions indicate

**Comment by ChristianAutmix** [comment] 2023-06-15 01:14
Thank you, @niyasraphy !

We have reverted the version back to 16.0.20230605. As a result, the system is now functioning as intended, without any further complications.

Once again, we appreciate your assistance and expertise in guiding us towards a resolution.

Best regards.

**Comment by niyasraphy** [comment] 2023-06-15 13:06
i hope, what you mean is on premise installation and if yes, just pull the latest source code.

**Closed** 2023-06-26 09:44 UTC
