### ISSUE TITLE
Printing product Attributes (Variant) 

### ISSUE THREAD

**Issue by jayo2005** [odoo/odoo#33157] opened 2019-05-04 07:28 UTC
Impacted versions:10

Steps to reproduce:Great product Variants

Current behavior:When printing it does not print the product variant attribute. Only Product name. This happens for Purchase order and sales orders. Supplier does not know what I want to order as Its not printed.

Expected behavior: Print Attribute

Video/Screenshot link (optional):
![12](https://user-images.githubusercontent.com/7015925/57175670-7d45c000-6e46-11e9-9b70-363670b84d7d.jpg)
![14](https://user-images.githubusercontent.com/7015925/57175672-7fa81a00-6e46-11e9-9dfe-b035ea10acf2.jpg)

**Comment by pedrobaeza** [comment] 2019-05-05 09:26
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by jayo2005** [comment] 2019-05-06 07:35
It works as expected on runbot

**Comment by pedrobaeza** [comment] 2019-05-06 13:51
Then it should be an outdated source code in your end or a conflict with another third party module. Check these things.

Closing meanwhile if you don't find that is due to something in Odoo core.

**Closed by pedrobaeza** 2019-05-06 13:51 UTC
Labels: Need information
