### ISSUE TITLE
[13.0][BUG] mrp workorder error because of bad logic.

### ISSUE THREAD

**Issue by stanevicius** [odoo/odoo#57227] opened 2020-09-08 08:41 UTC
hi @Whenrow,
bad logic:
https://github.com/odoo/odoo/blob/82c727a766f5b7a9554d9766e4eb5c448eae8e31/addons/mrp/models/mrp_abstract_workorder.py#L247-L274

on if condition checking for existing any production_move
https://github.com/odoo/odoo/blob/82c727a766f5b7a9554d9766e4eb5c448eae8e31/addons/mrp/models/mrp_abstract_workorder.py#L247
 if no then goes to else where trying to make changes for no records: `production_move._set_quantity_done`
https://github.com/odoo/odoo/blob/82c727a766f5b7a9554d9766e4eb5c448eae8e31/addons/mrp/models/mrp_abstract_workorder.py#L270-L274

It will cause error:

`Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1326, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/mnt/enterprise/mrp_workorder/models/mrp_workorder.py", line 583, in do_finish
    self.record_production()
  File "/mnt/enterprise/mrp_workorder/models/mrp_workorder.py", line 525, in record_production
    res = super(MrpProductionWorkcenterLine, self).record_production()
  File "/usr/lib/python3/dist-packages/odoo/addons/mrp/models/mrp_workorder.py", line 412, in record_production
    self._update_finished_move()
  File "/usr/lib/python3/dist-packages/odoo/addons/mrp/models/mrp_abstract_workorder.py", line 273, in _update_finished_move
    float_round(self.qty_producing, precision_rounding=rounding)
  File "/usr/lib/python3/dist-packages/odoo/tools/float_utils.py", line 55, in float_round
    precision_rounding=precision_rounding)
  File "/usr/lib/python3/dist-packages/odoo/tools/float_utils.py", line 30, in _float_check_precision
    "precision_rounding must be positive, got %s" % precision_rounding
AssertionError: precision_rounding must be positive, got 0.0`

**Comment by pedrobaeza** [comment] 2020-09-08 09:26
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Whenrow** [comment] 2020-09-08 09:38
@stanevicius Seems very unfortunate to not have a finished move at this stage but I will fix it to be more robust for the future. Thanks for reporting a well documented issue :)

**Comment by stanevicius** [comment] 2020-09-08 10:53
> Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?
> 
> If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.
> 
> If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.
> 
> For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

Dockerfile
ENV ODOO_VERSION 13.0
ARG ODOO_RELEASE=20200629
ARG ODOO_SHA=1d86e2728a65ed2c9f6ea9b6b893df878f75599e

Warehouse settings:
![image](https://user-images.githubusercontent.com/42935609/92463512-95fd7d00-f1d4-11ea-93b8-aca99cb2c3a4.png)

All products No Tracking

Using work orders.
Only last work order raise this error
![image](https://user-images.githubusercontent.com/42935609/92463834-03a9a900-f1d5-11ea-84cd-6c77ff3e4314.png)

mrp.production:
![image](https://user-images.githubusercontent.com/42935609/92464052-4bc8cb80-f1d5-11ea-8a93-57c5385baab3.png)

Product moves from mpr.production button:
![image](https://user-images.githubusercontent.com/42935609/92464160-7155d500-f1d5-11ea-8328-eb71942c8d95.png)

Components on mrp.production (all components only from purchases - buy):
![image](https://user-images.githubusercontent.com/42935609/92464483-d9a4b680-f1d5-11ea-9173-b6697e111af8.png)

Any ideas on which point I need to search a problem?
When production done moves must be generated?
this error cause when trying to make as done last work order.

@Whenrow last work order
`
self.production_id.move_finished_ids
stock.move()
self.production_id.move_dest_ids
stock.move(572,)
self.move_raw_ids
stock.move(573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620)`

Don't know on which point must be finished moves generated, maybe priorities of method calls are wrong...
from comments i'm not sure is it ok (we don't use lots and as we mentioned there is no finished moves yet.):
https://github.com/odoo/odoo/blob/40bc27774d4eed0a8a23f6762a09c6a10d2af8e8/addons/mrp/models/mrp_workorder.py#L436-L445

**Comment by Whenrow** [comment] 2020-09-08 12:04
@stanevicius  I though at first glance you had a finished move but already done. Having no workorders at all seems very strange. Also, having the error at the end is not surprising since: 
```python
 # If last work order, then post lots used 
 if not self.next_work_order_id: 
```
The finished move is created at the production order confirmation ('Mark As Todo'). You should inspect the stock moves list at this time to see if the move is created correctly (or create a support request via odoo.com/help. One of our support agents will investigate if your contract allows it ) 

Hope this will help you. 

Btw, I made a PR (https://github.com/odoo/odoo/pull/57237) to get rid of the traceback but will not solve your particular issue. From what you said, I think the problem appear sooner in the process.

**Comment by stanevicius** [comment] 2020-09-08 15:30
It becomes more strange, because there is move..
https://github.com/odoo/odoo/blob/82c727a766f5b7a9554d9766e4eb5c448eae8e31/addons/mrp/models/mrp_production.py#L582-L594
On `_generate_finished_moves` i can see one move..
`moves_values`:
`[{'product_id': 18320, 'product_uom_qty': 1.0, 'product_uom': 1, 'operation_id': False, 'byproduct_id': False, 'unit_factor': 1.0, 'name': 'WH/MO/00010', 'date': datetime.datetime(2020, 9, 8, 15, 10, 52), 'date_expected': datetime.datetime(2020, 9, 8, 16, 10, 52, 820904), 'picking_type_id': 8, 'location_id': 15, 'location_dest_id': 8, 'company_id': 1, 'production_id': 10, 'warehouse_id': 1, 'origin': 'WH/MO/00010', 'group_id': 165, 'propagate_cancel': False, 'propagate_date': True, 'propagate_date_minimum_delta': 1, 'move_dest_ids': []}]`

then I tried from that metod to check relations...

```
moves
stock.move(811,)
moves.production_id
mrp.production(10,)
moves.production_id.move_finished_ids
stock.move()
```

It seems that already can't see any relations after creation.

on `action_confirm` after _generate_finished_moves:
https://github.com/odoo/odoo/blob/82c727a766f5b7a9554d9766e4eb5c448eae8e31/addons/mrp/models/mrp_production.py#L693

```
self
mrp.production(10,)
self.move_finished_ids
stock.move()
production.move_finished_ids
stock.move()
self.env['stock.move'].search([('production_id', '=', production.id)])
stock.move(811,)
self.env['stock.move'].search([('production_id', '=', production.id)]).scrapped
True
```
And here it is: scrapped.
https://github.com/odoo/odoo/blob/82c727a766f5b7a9554d9766e4eb5c448eae8e31/addons/mrp/models/mrp_production.py#L172-L175

Then taking an eye to field `scrapped`:
`scrapped = fields.Boolean('Scrapped', related='location_dest_id.scrap_location', readonly=True, store=True)`

Maybe needs some extra raise or validation..

one on 'Mark As Todo' and another one on _update_finished_move

**Comment by stanevicius** [comment] 2020-09-09 07:12
I checked on odoo demo, there isn't marked as true scrap_location... So I think this is wrong configuration.
But I suggesting to add constraints or other checks on 'Mark As Todo' and another one on  _update_finished_move
@Whenrow

**Comment by Whenrow** [comment] 2020-09-09 07:54
@stanevicius Ok everything seems clear now. Except why did you set your stock location (or maybe the 'Post-production' if you set the 3 steps manufacturing) as scrap ? The scrapped product are meant to be thrown away not the result of a manufacturing order.

**Comment by stanevicius1** [comment] 2020-09-09 08:16
Cllient set main location as scrap location. Don't know why he did it.

**Comment by stanevicius** [comment] 2020-09-09 08:17
Cllient set main location as scrap location. Don't know why he did it.

**Comment by Whenrow** [comment] 2020-09-09 10:41
I suggest you to change it :)

**Closed** 2020-10-07 16:33 UTC
Labels: 13.0, Logistics
