### ISSUE TITLE
website editor not working and assets mode not load all this after install ssl - https

### ISSUE THREAD

**Issue by AbdulghaniFawzi** [odoo/odoo#29063] opened 2018-11-27 12:10 UTC
Impacted versions: 
V 11 CE

Steps to reproduce:

Current behavior:
some icons and images not loading  , assets mode not loading , website editor not loading , uninstall some modules not working ,images for apps in store not loading , when i click on website module in menu  opens for moment then reopen the previous module which i was in.
Expected behavior:

Video/Screenshot link (optional):

[
![untitled](https://user-images.githubusercontent.com/28447109/49080711-98882000-f255-11e8-9bba-b91207d30ccd.png)
](url)

**Comment by pedrobaeza** [comment] 2018-11-27 12:12
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by pedrobaeza** [comment] 2018-11-27 13:35
Then this is something related to your deployment and you should ask for extra questions on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above..

**Closed by pedrobaeza** 2018-11-27 13:35 UTC
Labels: 11.0, Need information
