### ISSUE TITLE
Sale Order - After deleting some products in Quotation, I get error message whenever creating new quotation, confirming sale or doing other actions

### ISSUE THREAD

**Issue by hoanguyenpt** [odoo/odoo#13570] opened 2016-09-23 04:18 UTC
Impacted versions: Odoo 9

Steps to reproduce:
0. The internet connection is poor.
1. Access Sales > Create new Quotation
2. Add some products
3. Try to remove two products continuously 

Current behavior: 
- Right after step 3, there is an error message (see attached file)
- Can't do other actions --> get this error
  [OdooServerError.txt](https://github.com/odoo/odoo/files/488858/OdooServerError.txt)

Expected behavior:
- If the products in step 3 was removed unsuccessfully, other main actions should not be affected.

Video/Screenshot link (optional):

**Comment by JKE-be** [comment] 2016-09-23 08:08
I cannot reproduce it.

I have tester with gprs connection and no error.

Can you reproduce it on runbot ?

**Comment by Yenthe666** [comment] 2018-02-13 15:51
Hi there,

I'm closing this bug report as it has been open for a very long time without any feedback from your side.
If you can still reproduce it on the latest Odoo 9.0 then please post back here and we'll reopen it.

Regards,
Yenthe

**Closed by Yenthe666** 2018-02-13 15:51 UTC
Labels: 9.0
