### ISSUE TITLE
[10.0] ParseError: "new row for relation "res_partner" violates check constraint "res_partner_check_name

### ISSUE THREAD

**Issue by clxadmin** [odoo/odoo#15095] opened 2017-01-17 09:19 UTC
Impacted versions: 10

Steps to reproduce: make multiple DBs (copy DBs)

Current behavior: Switching between databases gives an internal server error 500 in browser.
This is the log if such a DB is called from Browser: 

2017-01-17 09:18:39,206 14538 INFO basis odoo.modules.loading: loading 1 modules...
2017-01-17 09:18:39,252 14538 INFO basis odoo.modules.registry: module base: creating or updating database tables
2017-01-17 09:18:40,505 14538 INFO basis odoo.modules.loading: loading base/res/res.lang.csv
2017-01-17 09:18:41,074 14538 INFO basis odoo.modules.loading: loading base/base_data.xml
2017-01-17 09:18:41,134 14538 INFO basis odoo.modules.loading: loading base/res/res_currency_data.xml
2017-01-17 09:18:41,348 14538 INFO basis odoo.modules.loading: loading base/res/res_country_data.xml
2017-01-17 09:18:41,885 14538 INFO basis odoo.modules.loading: loading base/security/base_security.xml
2017-01-17 09:18:42,917 14538 INFO basis odoo.modules.loading: loading base/base_menu.xml
2017-01-17 09:18:43,060 14538 INFO basis odoo.modules.loading: loading base/res/res_config.xml
2017-01-17 09:18:43,093 14538 INFO basis odoo.modules.loading: loading base/res/res.country.state.csv
2017-01-17 09:18:45,009 14538 INFO basis odoo.modules.loading: loading base/ir/ir_actions.xml
2017-01-17 09:18:45,188 14538 INFO basis odoo.models.unlink: User #1 deleted ir.translation records with IDs: [17389]
2017-01-17 09:18:45,406 14538 INFO basis odoo.models.unlink: User #1 deleted ir.translation records with IDs: [17386, 17704, 17706, 17707, 17725, 17726, 77466, 77467, 77478, 77588, 77727, 77837, 77948, 77951]
2017-01-17 09:18:45,514 14538 INFO basis odoo.modules.loading: loading base/ir/ir_config_parameter_view.xml
2017-01-17 09:18:45,600 14538 INFO basis odoo.modules.loading: loading base/ir/ir_cron_view.xml
2017-01-17 09:18:45,619 14538 INFO basis odoo.models.unlink: User #1 deleted ir.translation records with IDs: [17079]
2017-01-17 09:18:45,673 14538 INFO basis odoo.modules.loading: loading base/ir/ir_filters.xml
2017-01-17 09:18:45,731 14538 INFO basis odoo.modules.loading: loading base/ir/ir_mail_server_view.xml
2017-01-17 09:18:45,784 14538 INFO basis odoo.modules.loading: loading base/ir/ir_model_view.xml
2017-01-17 09:18:45,827 14538 INFO basis odoo.models.unlink: User #1 deleted ir.translation records with IDs: [17565, 17569, 17571, 17720, 77345, 77377, 77440, 77654, 77993]
2017-01-17 09:18:45,886 14538 INFO basis odoo.models.unlink: User #1 deleted ir.translation records with IDs: [17566, 17570, 17572, 17719, 77378, 77439, 77783, 77984, 77994]
2017-01-17 09:18:46,139 14538 INFO basis odoo.models.unlink: User #1 deleted ir.translation records with IDs: [17123]
2017-01-17 09:18:46,153 14538 INFO basis odoo.modules.loading: loading base/ir/ir_attachment_view.xml
2017-01-17 09:18:46,202 14538 INFO basis odoo.models.unlink: User #1 deleted ir.translation records with IDs: [17635, 77536]
2017-01-17 09:18:46,222 14538 INFO basis odoo.modules.loading: loading base/ir/ir_rule_view.xml
2017-01-17 09:18:46,272 14538 INFO basis odoo.models.unlink: User #1 deleted ir.translation records with IDs: [17122]
2017-01-17 09:18:46,294 14538 INFO basis odoo.modules.loading: loading base/ir/ir_sequence_view.xml
2017-01-17 09:18:46,316 14538 INFO basis odoo.models.unlink: User #1 deleted ir.translation records with IDs: [17209]
2017-01-17 09:18:46,436 14538 INFO basis odoo.modules.loading: loading base/ir/ir_translation_view.xml
2017-01-17 09:18:46,504 14538 INFO basis odoo.modules.loading: loading base/ir/ir_ui_menu_view.xml
2017-01-17 09:18:46,560 14538 INFO basis odoo.modules.loading: loading base/ir/ir_ui_view_view.xml
2017-01-17 09:18:46,615 14538 INFO basis odoo.models.unlink: User #1 deleted ir.translation records with IDs: [17063, 17387]
2017-01-17 09:18:46,853 14538 INFO basis odoo.modules.loading: loading base/ir/ir_values_view.xml
2017-01-17 09:18:47,004 14538 INFO basis odoo.modules.loading: loading base/ir/ir_autovacuum.xml
2017-01-17 09:18:47,010 14538 INFO basis odoo.modules.loading: loading base/ir/ir_model_report.xml
2017-01-17 09:18:47,022 14538 INFO basis odoo.models.unlink: User #1 deleted ir.values records with IDs: [2]
2017-01-17 09:18:47,027 14538 INFO basis odoo.modules.loading: loading base/ir/report_ir_model.xml
2017-01-17 09:18:47,055 14538 INFO basis odoo.models.unlink: User #1 deleted ir.translation records with IDs: [17283, 17451, 17551, 17562, 17563, 17589, 17594, 17603, 77584, 77585, 77586, 77596, 77848]
2017-01-17 09:18:47,058 14538 INFO basis odoo.modules.loading: loading base/ir/ir_logging_view.xml
2017-01-17 09:18:47,112 14538 INFO basis odoo.modules.loading: loading base/ir/ir_qweb.xml
2017-01-17 09:18:47,131 14538 INFO basis odoo.modules.loading: loading base/workflow/workflow_view.xml
2017-01-17 09:18:47,404 14538 INFO basis odoo.models.unlink: User #1 deleted ir.translation records with IDs: [17503]
2017-01-17 09:18:47,419 14538 INFO basis odoo.modules.loading: loading base/module/module_view.xml
2017-01-17 09:18:47,465 14538 INFO basis odoo.models.unlink: User #1 deleted ir.translation records with IDs: [17599]
2017-01-17 09:18:47,498 14538 INFO basis odoo.models.unlink: User #1 deleted ir.translation records with IDs: [17078]
2017-01-17 09:18:47,517 14538 INFO basis odoo.models.unlink: User #1 deleted ir.translation records with IDs: [17612]
2017-01-17 09:18:47,541 14538 INFO basis odoo.models.unlink: User #1 deleted ir.translation records with IDs: [76688]
2017-01-17 09:18:47,571 14538 INFO basis odoo.modules.loading: loading base/module/module_data.xml
2017-01-17 09:18:48,473 14538 INFO basis odoo.modules.loading: loading base/module/module_report.xml
2017-01-17 09:18:48,523 14538 INFO basis odoo.models.unlink: User #1 deleted ir.values records with IDs: [4]
2017-01-17 09:18:48,527 14538 INFO basis odoo.modules.loading: loading base/module/report/report_ir_module_reference.xml
2017-01-17 09:18:48,593 14538 INFO basis odoo.models.unlink: User #1 deleted ir.translation records with IDs: [17279, 17657, 17671]
2017-01-17 09:18:48,599 14538 INFO basis odoo.modules.loading: loading base/module/wizard/base_module_update_view.xml
2017-01-17 09:18:48,631 14538 INFO basis odoo.modules.loading: loading base/module/wizard/base_language_install_view.xml
2017-01-17 09:18:48,658 14538 INFO basis odoo.modules.loading: loading base/module/wizard/base_import_language_view.xml
2017-01-17 09:18:48,680 14538 INFO basis odoo.models.unlink: User #1 deleted ir.translation records with IDs: [17324, 17702]
2017-01-17 09:18:48,694 14538 INFO basis odoo.modules.loading: loading base/module/wizard/base_module_upgrade_view.xml
2017-01-17 09:18:48,742 14538 INFO basis odoo.modules.loading: loading base/module/wizard/base_module_configuration_view.xml
2017-01-17 09:18:48,756 14538 INFO basis odoo.modules.loading: loading base/module/wizard/base_export_language_view.xml
2017-01-17 09:18:48,777 14538 INFO basis odoo.models.unlink: User #1 deleted ir.translation records with IDs: [17163, 17178, 17343]
2017-01-17 09:18:48,790 14538 INFO basis odoo.modules.loading: loading base/module/wizard/base_update_translations_view.xml
2017-01-17 09:18:48,815 14538 INFO basis odoo.modules.loading: loading base/module/wizard/base_module_immediate_install.xml
2017-01-17 09:18:48,827 14538 INFO basis odoo.modules.loading: loading base/res/res_company_view.xml
2017-01-17 09:18:48,886 14538 INFO basis odoo.modules.loading: loading base/res/res_request_view.xml
2017-01-17 09:18:49,086 14538 INFO basis odoo.modules.loading: loading base/res/res_lang_view.xml
2017-01-17 09:18:49,147 14538 INFO basis odoo.models.unlink: User #1 deleted ir.translation records with IDs: [77730]
2017-01-17 09:18:49,176 14538 INFO basis odoo.models.unlink: User #1 deleted ir.translation records with IDs: [77460, 77461, 77472, 77590, 77593, 77601, 77602, 77605, 77611, 77620, 77650, 77655, 77674, 77692, 77775, 77779, 77861, 77864, 77873, 77887, 77904]
2017-01-17 09:18:49,204 14538 INFO basis odoo.modules.loading: loading base/res/res_partner_view.xml
2017-01-17 09:18:49,265 14538 INFO basis odoo.models.unlink: User #1 deleted ir.translation records with IDs: [17282]
2017-01-17 09:18:49,285 14538 INFO basis odoo.models.unlink: User #1 deleted ir.translation records with IDs: [17281]
2017-01-17 09:18:49,306 14538 INFO basis odoo.models.unlink: User #1 deleted ir.translation records with IDs: [17354]
2017-01-17 09:18:49,334 14538 INFO basis odoo.models.unlink: User #1 deleted ir.translation records with IDs: [17152, 17280, 17547]
2017-01-17 09:18:49,355 14538 INFO basis odoo.models.unlink: User #1 deleted ir.translation records with IDs: [17544]
2017-01-17 09:18:49,441 14538 INFO basis odoo.models.unlink: User #1 deleted ir.translation records with IDs: [76715]
2017-01-17 09:18:49,445 14538 INFO basis odoo.modules.loading: loading base/res/res_bank_view.xml
2017-01-17 09:18:49,465 14538 INFO basis odoo.models.unlink: User #1 deleted ir.translation records with IDs: [17593]
2017-01-17 09:18:49,650 14538 INFO basis odoo.modules.loading: loading base/res/res_country_view.xml
2017-01-17 09:18:49,802 14538 INFO basis odoo.modules.loading: loading base/res/res_currency_view.xml
2017-01-17 09:18:49,994 14538 INFO basis odoo.models.unlink: User #1 deleted ir.translation records with IDs: [77954]
2017-01-17 09:18:49,998 14538 INFO basis odoo.modules.loading: loading base/res/res_users_view.xml
2017-01-17 09:18:50,039 14538 INFO basis odoo.models.unlink: User #1 deleted ir.values records with IDs: [7]
2017-01-17 09:18:50,144 14538 INFO basis odoo.models.unlink: User #1 deleted ir.translation records with IDs: [17718]
2017-01-17 09:18:50,280 14538 INFO basis odoo.models.unlink: User #1 deleted ir.translation records with IDs: [17153, 17329, 17458, 17561]
2017-01-17 09:18:50,423 14538 INFO basis odoo.modules.loading: loading base/res/res_partner_data.xml
2017-01-17 09:18:50,434 14538 INFO basis odoo.modules.loading: loading base/res/ir_property_view.xml
2017-01-17 09:18:50,451 14538 INFO basis odoo.models.unlink: User #1 deleted ir.translation records with IDs: [17278]
2017-01-17 09:18:50,492 14538 INFO basis odoo.modules.loading: loading base/res/res_security.xml
2017-01-17 09:18:50,499 14538 INFO basis odoo.modules.loading: loading base/security/ir.model.access.csv
2017-01-17 09:18:51,782 14538 INFO basis odoo.modules.loading: loading base/base_demo.xml
2017-01-17 09:18:51,792 14538 INFO basis odoo.modules.loading: loading base/res/res_currency_demo.xml
2017-01-17 09:18:52,104 14538 INFO basis odoo.modules.loading: loading base/res/res_bank_demo.xml
2017-01-17 09:18:52,109 14538 INFO basis odoo.modules.loading: loading base/res/res_partner_demo.xml
2017-01-17 09:18:53,144 14538 INFO basis odoo.modules.loading: loading base/res/res_partner_demo.yml
2017-01-17 09:18:53,189 14538 INFO basis odoo.modules.loading: loading base/res/res_partner_image_demo.xml
2017-01-17 09:18:53,213 14538 INFO basis odoo.sql_db: bad query: INSERT INTO "res_partner" ("id", "customer", "lang", "tz", "color", "company_id", "partner_share", "supplier", "employee", "active", "type", "is_company", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval('res_partner_id_seq'), true, 'en_US', NULL, 0, 1, false, false, false, true, 'contact', false, 1, 1, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id
2017-01-17 09:18:53,214 14538 ERROR basis odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 278, in load_modules
    loaded_modules, processed_modules = load_module_graph(cr, graph, status, perform_checks=update_module, report=report)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 159, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='demo')
  File "/odoo/odoo-server/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 848, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 918, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 799, in parse
    self.parse(rec, mode)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 802, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 710, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_model.py", line 1180, in _update
    record = record.create(values)
  File "/odoo/odoo-server/odoo/addons/base/res/res_partner.py", line 511, in create
    partner = super(Partner, self).create(vals)
  File "/odoo/odoo-server/odoo/models.py", line 3804, in create
    record = self.browse(self._create(old_vals))
  File "/odoo/odoo-server/odoo/models.py", line 3892, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/odoo/odoo-server/odoo/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
ParseError: "new row for relation "res_partner" violates check constraint "res_partner_check_name"
DETAIL:  Failing row contains (1555, null, 1, null, null, 2017-01-17 09:18:40.488012, 0, t, null, f, null, null, null, null, null, null, null, null, f, null, null, f, null, en_US, null, null, null, null, 2017-01-17 09:18:40.488012, null, null, 1, t, 1, null, null, null, contact, f, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null).
" while parsing /odoo/odoo-server/odoo/addons/base/res/res_partner_image_demo.xml:13, near
<record id="base.res_partner_address_4" model="res.partner">
            <field name="image" type="base64" file="base/static/img/res_partner_address_4-image.png"/>
        </record>
2017-01-17 09:18:53,216 14538 INFO basis werkzeug: 109.164.242.121 - - [17/Jan/2017 09:18:53] "GET /web?db=basis HTTP/1.1" 500 -
2017-01-17 09:18:53,230 14538 ERROR basis werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/odoo/odoo-server/odoo/service/server.py", line 246, in app
    return self.app(e, s)
  File "/odoo/odoo-server/odoo/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/odoo/odoo-server/odoo/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/odoo/odoo-server/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/odoo/odoo-server/odoo/http.py", line 1280, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 579, in __call__
    return self.app(environ, start_response)
  File "/odoo/odoo-server/odoo/http.py", line 1454, in dispatch
    odoo.registry(db).check_signaling()
  File "/odoo/odoo-server/odoo/__init__.py", line 55, in registry
    return modules.registry.Registry(database_name)
  File "/odoo/odoo-server/odoo/modules/registry.py", line 55, in __new__
    return cls.new(db_name)
  File "/odoo/odoo-server/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 278, in load_modules
    loaded_modules, processed_modules = load_module_graph(cr, graph, status, perform_checks=update_module, report=report)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 159, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='demo')
  File "/odoo/odoo-server/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 848, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 918, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 799, in parse
    self.parse(rec, mode)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 802, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 710, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_model.py", line 1180, in _update
    record = record.create(values)
  File "/odoo/odoo-server/odoo/addons/base/res/res_partner.py", line 511, in create
    partner = super(Partner, self).create(vals)
  File "/odoo/odoo-server/odoo/models.py", line 3804, in create
    record = self.browse(self._create(old_vals))
  File "/odoo/odoo-server/odoo/models.py", line 3892, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/odoo/odoo-server/odoo/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
ParseError: "new row for relation "res_partner" violates check constraint "res_partner_check_name"
DETAIL:  Failing row contains (1555, null, 1, null, null, 2017-01-17 09:18:40.488012, 0, t, null, f, null, null, null, null, null, null, null, null, f, null, null, f, null, en_US, null, null, null, null, 2017-01-17 09:18:40.488012, null, null, 1, t, 1, null, null, null, contact, f, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null).
" while parsing /odoo/odoo-server/odoo/addons/base/res/res_partner_image_demo.xml:13, near
<record id="base.res_partner_address_4" model="res.partner">
            <field name="image" type="base64" file="base/static/img/res_partner_address_4-image.png"/>
        </record>

Expected behavior: show correct GUI for DB

Video/Screenshot link (optional):

**Comment by Fenkiou** [comment] 2017-01-22 14:47
I'm using the duplicate database feature (from the web database manager) all the time and never encounter this error.

Can you reproduce this error with a fresh odoo installation, without any additional modules installed ?

**Comment by Danisan** [comment] 2017-08-13 04:32
I'm having this problem while installing website_partner module. If I cancel itss installation I get rid of the error.

**Comment by Danisan** [comment] 2017-08-13 05:02
The workaround I could do, was to comment the records in following file:

website_partner/data/website_partner_demo.xml

commenting from  all the records, I could install.

**Comment by pedrobaeza** [comment] 2018-05-06 13:03
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-05-06 13:03 UTC
Labels: 10.0

**Comment by zodman** [comment] 2019-04-02 22:42
i edit:

`vim odoo/addons/base/__manifest__.py`

the line 

```
    'demo': [
        'base_demo.xml',
        'res/res_currency_demo.xml',
        'res/res_bank_demo.xml',
        'res/res_partner_demo.xml',
        'res/res_partner_demo.yml',
        #'res/res_partner_image_demo.xml',
    ],
```
