### ISSUE TITLE
[10.0] Due Payment report wrong with partial payment

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#21353] opened 2017-11-30 17:16 UTC
Here is the scenario to reproduce the bug on runbot v10:
1) login as admin on runbot v10
2) create a new customer TOTO
3) create a new invoice for TOTO for the total amount of 1000$
4) On this invoice, register a partial payment of 200$ -> the residual of the invoice should now be 800$
5) On the form view of partner TOTO, click on "Print > Due Payments"
-> In the letter, the balance is 1000$ (instead of 800$) and the "Paid" columns only has zeros.

Code analysis:
On the account.move.line of the partial payment of 200$ that has the receivable account, the field "reconciled" is true. On the account.move.line of the invoice of 1000$ that has the receivable account, field "reconciled" is false.
As reconciled = true on the partial payment move line, it is excluded from the SQL request of the method _get_account_move_lines() that prepare the data. This bug is a side-effect of the merge of this PR by @pedrobaeza https://github.com/odoo/odoo/pull/16440/files

**Comment by alexis-via** [comment] 2017-11-30 17:23
The bug is also present on v9 and v11.

**Comment by oco-odoo** [comment] 2018-03-01 08:08
@alexis-via I can't reproduce the error, so either it has been fixed since you submitted your feedback, or I'm forgetting something (though your description is pretty clear). Can you check on your side ?

**Comment by StefanRijnhart** [comment] 2018-03-08 14:19
Hi @oco-odoo, on today's runbot 11.0CE: create an invoice of $22.90. Add a payment of $11.00. Print Due Payments report. The Due Payment reports lists the invoice but not the payment, resulting in a balance of $22.90. See the attached prints.

[Invoice - INV_2018_0005.pdf](https://github.com/odoo/odoo/files/1793448/Invoice.-.INV_2018_0005.pdf)
[Due Payments - Test.pdf](https://github.com/odoo/odoo/files/1793450/Due.Payments.-.Test.pdf)

**Comment by oco-odoo** [comment] 2018-03-09 13:19
@StefanRijnhart Thank you for your feedback! I actually was checking on enterprise only, were the report is not the same. On community, there was indeed a bug. It is now fixed: https://github.com/odoo/odoo/commit/7c6da3e076348a386db54a312192b58fffc51984

**Closed by oco-odoo** 2018-03-09 13:19 UTC
Labels: 10.0, Accounting
