### ISSUE TITLE
[14.0] Can not select UoM

### ISSUE THREAD

**Issue by haconsult** [odoo/odoo#71488] opened 2021-05-31 11:51 UTC
Impacted versions: 14.0

Steps to reproduce: 
* Create a new invoice
* Enter a description, quantity and try to select an UOM accordingly

Current behavior:
* No drop-down-list of available UOMs
* You have to create a new UOM on the fly
*  No way to select from existing UOMs

Expected behavior:
* Present existing UOMs to the user
* Let the user choose from existing UOMs

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment] 2021-05-31 15:38
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by haconsult** [comment] 2021-05-31 17:59
Hi, thanks for messaging back.

In runbot v14.0 (community edition) I found the following:

- Invoicing → Create a new invoice
- "Add a new line" to the invoice but do not select a predefined Product, just fill some text in the "Label" field
- Fill in some "Quantity"
- Try to assign a "UoM" → not possible. You would need to Crate and Edit a new UoM although it already exists in the database

- If you select a predefined product then you can assign one of the UoMs that are defined in the product but without selecting a product you can not select any existing UoM

Thanks for taking care of this issue.

**Comment by pedrobaeza** [comment] 2021-05-31 21:06
Thanks for the extra explanations. That's something expected, as the unit of measure is only selectable if a product is indicated. In any other case, there's no UoM reference.

Closing as expected behavior.

**Closed by pedrobaeza** 2021-05-31 21:06 UTC
Labels: Need information
