### ISSUE TITLE
[12.0] Field 'sinid' is in module 'hr', but not in view

### ISSUE THREAD

**Issue by Borruso** [odoo/odoo#56162] opened 2020-08-19 15:44 UTC
Impacted versions:
12.0

Steps to reproduce:
Open view 'hr.view_employee_form'

Current behavior:
Field 'sinid', in module 'hr', there isn't in anywhere view

Expected behavior:
I suggest to add this field in view 'hr.view_employee_form' after field 'birthday'

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2020-08-19 15:47
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by pedrobaeza** [comment] 2020-08-19 15:50
I re-read your issue and you are requesting to add that field in views, but this kind of improvement is not allowed on stable versions. You can add it by yourself in a module or using Odoo Studio if you need it. You can also propose in a pull request its inclusion in master version.

Closing as no issue, but improvement.

**Closed by pedrobaeza** 2020-08-19 15:50 UTC
