### ISSUE TITLE
Product Attribute Change Problem

### ISSUE THREAD

**Issue by krutarthbuch** [odoo/odoo#31665] opened 2019-03-07 13:28 UTC
Impacted versions: V11 Enterprise

Steps to reproduce: I have created a product and have added variants as attached image 1. Then I have purchased and sold a variant. After that I went to same product and changed attribute to other attribute which contains value as attached in image 2.

Current behavior: We can choose any attribute which contains value which shows mismatch with variant attributes.

Expected behavior: Attribute should not be changed once it has values configured in it.

Video/Screenshot link (optional):

![odoo bug 1](https://user-images.githubusercontent.com/9315479/53959941-007abc00-410b-11e9-8575-8bea00369863.png)
![odoo bug 2](https://user-images.githubusercontent.com/9315479/53959942-007abc00-410b-11e9-925d-40fc33d87db2.png)

**Comment by pedrobaeza** [comment] 2019-03-07 19:06
Preventing these changes will require to extend for each of the possible places where the product can be put to extend the checks, which is overkill.

Thus, Odoo acts smarter, simply deactivating the variants that aren't present now with current combination of attributes/values. If you want to have again the product, then just activate the product or introduce again the combination of attributes/values that match that product.

Closing this then as no real issue, but intended behavior.

**Closed by pedrobaeza** 2019-03-07 19:06 UTC
Labels: 11.0, Services

**Comment by gdgellatly** [comment] 2019-03-08 19:10
@pedrobaeza Not really, it is just a missing constraint IMO and requires writing nothing for checking products, just on product.attribute.line. Attribute lines shouldn't be able to be written with an attribute != attribute_values.attribute

**Comment by pedrobaeza** [comment] 2019-03-10 15:53
@gdgellatly I think this one is not the same case you are mentioning. You are talking about changing attribute values by code, which is not the case here. I still see the current logic (disabling inexisting variants) as a good one for covering all the mangling in the attribute/values table.
