### ISSUE TITLE
Timezone widget error 12.0

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#27701] opened 2018-10-11 22:25 UTC
Impacted versions:

Steps to reproduce:
Open either user preferences or user form with a timezone mismatch
Reproduced in enterprise and community latest 12.0 runbots

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/5093264/46837361-8ec76c00-ce11-11e8-9633-24046eabd28f.png)

EDIT: With correct screenshot and correct spelling

**Comment by pedrobaeza** [comment] 2018-10-11 22:28
Duplicate of #27410

**Closed by pedrobaeza** 2018-10-11 22:28 UTC
