### ISSUE TITLE
[9.0] enterprise: Unexpected behavior in purchase pricelist, amount incorrect with demo data.

### ISSUE THREAD

**Issue by nhomar** [odoo/odoo#8874] opened 2015-10-03 08:50 UTC
Hello all.

What did I try?:
---

1. Use Ipad Mini demo product.

![Ipad Mini](https://www.evernote.com/l/AJ5lGAtt3-5FEJ7uz74CmTfHa90R3uu2fUsB/image.png)

2. Try to make a purchase with partner Asustek.

![Ipad Mini](https://www.evernote.com/l/AJ7sQFEI3GRM0Yf1iC2ezVOeLY-zldqNW94B/image.png)

What do I get?:

First, it allows pick the parent product template (which I think is incorrect because the data has actually some variants), the extrange is that the cost taken is not the one in the purchase price list for asustek and the cost on form either (for 1 product) it is a total different cost.

What do I expect?

Cost is taken from the partner on product.

Second Part:
 ---

1. Try to pick a contact on the partner field, which is an Asustek Contact:

![Pick Another.](https://www.evernote.com/l/AJ6gDflKWw5JHaTZObe63DeReCr7ASfiVu4B/image.png)

Then may be do I miss something but the price list behavior for partners is a something not clearly working as before or even in a logical way.

**Comment by antonylesuisse** [comment] 2015-10-03 11:21
Yes you are right. The onchange should also look on the parent partner. Be aware than we only look up for supplier info (we  dont fallback on cost price anymore).

@nim-odoo can you fix it?

**Comment by nim-odoo** [comment] 2015-10-05 08:58
Hello,

As Antony said, we only take into account the supplier info in order to find out the price to apply. It doesn't fall back on the cost price of the product. Since the supplier info are linked to a product template, the first behavior you describe is the intended behavior: although the product has some variants, the price of the template is taken into account. The price goes from 750 to 1,146.68 in your example because of currency conversion: 750 EUR in the supplier info is converted into 1,146.68 USD in the PO.

If you want to specify a price for a given product variant, there is a 'hidden feature'. On the supplier info, you can also specify a product variant by making the field `product_id` visible: https://github.com/odoo/odoo/blob/9.0/addons/product/product_view.xml#L772. When this field is filled in, the supplier info will apply only to the specified product variant. However, be aware that the logic for selecting a supplier among the possible suppliers is pretty basic: the suppliers are ordered by sequence, and the first match is selected.

Let's illustrate with an example. We have a product which has 3 variants A, B, C.
- Supplier info 1: `sequence = 5`, `price = 1299`, `product_id = False`
- Supplier info 2: `sequence = 10`, `price = 1499`, `product_id = A`

When you purchase A, B or C, the price selected will be 1299 since the supplier info 1 match with the 3 products and is the first one to be browsed.

If you change the sequence:
- Supplier info 1: `sequence = 10`, `price = 1299`, `product_id = False`
- Supplier info 2: `sequence = 5`, `price = 1499`, `product_id = A`

When you purchase A, the price selected will be 1499. When you purchase B or C, the price will be 1299. In this case, the supplier info 2 is the first browsed, and match the product A.

Note that the minimum quantity as well as the validity period is taken into account to determine the price. If one of these criteria is not met, the supplier is skipped. When no matching supplier is found, the price is reset to zero.

I hope this explanation makes things more clear.

Regarding the second point, it should be fixed with https://github.com/odoo-dev/odoo/commit/f12e1c26e9998d2f2c7093135f57b6e31467725a

**Closed** 2015-10-05 09:03 UTC
Labels: confirmed

**Comment by nhomar** [comment] 2015-10-05 09:17
@nim-odoo 

About the hypotesis in the conversion rate:

Everything was configured with USD/Dollars then we have a deeper bug here, Should I opne a new issue-report, or we can work on this one instead this folow up??

**Comment by nhomar** [comment] 2015-10-05 09:28
@nim-odoo 

About the explanation of the functionality, yes it brings it really more clear, some point outs:

1. Should not this explanation goes in the Help on the field? then it can be more clear I think it is not obvious at all (but clear enought to be solved ith this explanation).

2. About the openess of the field: IMHO this should be a setteable feature to avoid need to develop this bringing unnecesary development, but cool, We can make our own simple module which open the product_id field. (but I understand it is pretty uncommon somebody buying different variants to different supplers) which is really more common is that the price on Variant almost always is different between them (i.e a 16Gb product differ on cost of a 32 gb product).

Thanks for the explanation it clariy a lot the situation.

**Comment by nim-odoo** [comment] 2015-10-05 10:01
@nhomar 

I double checked, the issue comes from the currency. When the supplier info is created, the currency taken is the one of the company of the user, which is EUR at the moment of the creation of the demo data: https://github.com/odoo/odoo/blob/9.0/addons/product/product.py#L1251
![screenshot-area-2015-10-05-113722](https://cloud.githubusercontent.com/assets/11041725/10277403/f755e444-6b55-11e5-8aaa-794a54267d23.png)

I guess that somehow, during the installation process of the runbot, this currency is changed at some point. We'll have a look into it, but it is not a really a bug in itself.

Regarding the explanation, we'll improve the help of the field and/or the related documentation, thanks for the suggestion.

**Comment by nhomar** [comment] 2015-10-05 10:06
@nim-odoo The demo should be consistent always in order to avoid mixed-test error I consider this a bug, but yes a low priority one.
