### ISSUE TITLE
Error when open ticket from Kanban view

### ISSUE THREAD

**Issue by FaTaToo** [odoo/odoo#76155] opened 2021-09-08 11:38 UTC
Impacted versions: 12.0

Steps to reproduce:
- Open any ticket from kanban view.

Current behavior:
- This bug is happen randomly.
- Form view of ticket was openned but still have search view area and name of the ticket is not the same with the name on control panel.
- URL still reference to kanban view: /web?debug=assets#action=465&active_id=1&model=helpdesk.ticket&view_type=kanban&menu_id=289. 

Expected behavior:
- When form view of ticket was opening, search view should be hidden and name of ticket should be the same with the one on control panel. 
- URL should reference to form view: /web?debug=assets#id=81470&action=465&active_id=1&model=helpdesk.ticket&view_type=form&menu_id=289

Video/Screenshot link (optional):
https://prntscr.com/1rkhhat

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment] 2021-09-08 11:40
As this is something enterprise (or is it OCA helpdesk?), you should report it to the proper place (odoo.com/help in the case of enterprise), but without exact steps to reproduce the problem, nothing can't be done.

Closing this due to the above.

**Closed by pedrobaeza** 2021-09-08 11:40 UTC
