### ISSUE TITLE
Can`t preview * .pdf

### ISSUE THREAD

**Issue by digitalliuzg** [odoo/odoo#59814] opened 2020-10-13 01:43 UTC
Impacted versions: odoo 12,13 community and enterprises on odoo/odoo/addons/web on Google Chrome and FireFox

Steps to reproduce:
worker_loader.js:71 Refused to execute script from 'http://localhost:8269/web/static/lib/pdfjs/src/shared/util.js' because its MIME type ('text/plain') is not executable.
(anonymous) @ worker_loader.js:71
worker_loader.js:71 Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://localhost:8269/web/static/lib/pdfjs/src/shared/util.js' failed to load.
at http://localhost:8269/web/static/lib/pdfjs/src/worker_loader.js:71:5

Current behavior:Can`t preview * .pdf

Expected behavior: preview * .pdf

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/11321237/95805549-43b1fd80-0d38-11eb-97b5-b767123a684c.png)
![image](https://user-images.githubusercontent.com/11321237/95805564-490f4800-0d38-11eb-90cd-60d122c3eaaf.png)
![image](https://user-images.githubusercontent.com/11321237/95805572-4dd3fc00-0d38-11eb-9878-70c3a97071db.png)
![image](https://user-images.githubusercontent.com/11321237/95805678-8ffd3d80-0d38-11eb-8ac5-0ce1be7dc0e4.png)
![image](https://user-images.githubusercontent.com/11321237/95805919-1b76ce80-0d39-11eb-9793-d706d86f827e.png)
![image](https://user-images.githubusercontent.com/11321237/95805929-203b8280-0d39-11eb-810f-3e28e28d1495.png)

**Comment by pedrobaeza** [comment] 2020-10-13 08:01
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by digitalliuzg** [comment] 2020-10-13 11:13
I don't understand, why, the same code service, my analytical type to text/plain, and http://runbot.odoo.com/runbot, parsing is application/javascript.
![image](https://user-images.githubusercontent.com/11321237/95853458-0d03d380-0d88-11eb-82de-70c6dee638cc.png)
![image](https://user-images.githubusercontent.com/11321237/95853519-260c8480-0d88-11eb-84e3-1258ce605900.png)

**Comment by pedrobaeza** [comment] 2020-10-13 11:22
Probably your reverse proxy or Odoo configuration. Anyway, this is something outside of the scope of this issue tracker. For further doubts, please go to the forums.

**Closed by pedrobaeza** 2020-10-13 11:22 UTC
Labels: Need information
