### ISSUE TITLE
Enterprise addons no longer exist (docs)

### ISSUE THREAD

**Issue by cbcoutinho** [odoo/odoo#40546] opened 2019-11-20 09:20 UTC
Impacted versions:

- Current documentation on [odoo.com](https://www.odoo.com/documentation/master/setup/install.html#git) states that the enterprise addons are available at [https://github.com/odoo/enterprise](https://github.com/odoo/enterprise)

Steps to reproduce:

- Go to the documentation

Current behavior:

- Documentaion is incorrect, or enterprise addons are somewhere else

Expected behavior:

- Documentation is correct and git repository is update, or section on enterprise addons is removed 

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2019-11-20 09:23
The problem is that you don't have access to that repo as is only available to partners or enterprise customers.

Closing as no issue.

**Closed by pedrobaeza** 2019-11-20 09:23 UTC

**Comment by cbcoutinho** [comment] 2019-11-20 09:38
Ah gotcha, thanks for the explanation.
