### ISSUE TITLE
Error: Permission denied to access property "apply"

### ISSUE THREAD

**Issue by xuehao** [odoo/odoo#29643] opened 2018-12-19 12:22 UTC
Impacted versions:
V12.0 on macOS

Steps to reproduce:

Current behavior:
Error:
Error: Permission denied to access property "apply"

http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:887
Traceback:
trigger@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:887:28
trigger/<@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:937:134
each@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:625:758
each@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:613:636
trigger@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:937:113
jQuery.fn[name]@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:1134:355
.focus</<@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:1267:264
_focusInput@http://localhost:8069/web/content/356-a3dfb74/web.assets_backend.js:893:136
on_attach_callback@http://localhost:8069/web/content/356-a3dfb74/web.assets_backend.js:887:195
on_attach_callback@http://localhost:8069/web/content/356-a3dfb74/web.assets_backend.js:1278:94
_notify/<@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:3719:400
_.forEach@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:12:558
_notify@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:3719:329
append@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:3720:116
_appendController@http://localhost:8069/web/content/356-a3dfb74/web.assets_backend.js:460:113
_pushController@http://localhost:8069/web/content/356-a3dfb74/web.assets_backend.js:482:79
_executeAction/<@http://localhost:8069/web/content/356-a3dfb74/web.assets_backend.js:465:1
then/</</<@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:802:678
fire@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:796:281
add@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:797:467
then/</<@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:802:649
each@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:625:758
then/<@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:802:553
Deferred@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:803:189
then@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:802:518
_executeAction@http://localhost:8069/web/content/356-a3dfb74/web.assets_backend.js:463:58
_executeWindowAction/</<@http://localhost:8069/web/content/356-a3dfb74/web.assets_backend.js:504:135
then/</</<@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:802:678
fire@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:796:281
fireWith@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:801:198
Deferred/</deferred[tuple[0]]@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:803:56
fire@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:796:281
fireWith@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:801:198
Deferred/</deferred[tuple[0]]@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:803:56
then/</</<@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:802:678
fire@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:796:281
fireWith@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:801:198
Deferred/</deferred[tuple[0]]@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:803:56
_createViewController/<@http://localhost:8069/web/content/356-a3dfb74/web.assets_backend.js:496:786
then/</</<@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:802:678
fire@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:796:281
fireWith@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:801:198
then/</</<@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:802:874
fire@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:796:281
fireWith@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:801:198
updateFunc/<@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:804:482
fire@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:796:281
fireWith@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:801:198
then/</</<@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:802:874
fire@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:796:281
fireWith@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:801:198
then/</</<@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:802:874
fire@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:796:281
fireWith@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:801:198
Deferred/</deferred[tuple[0]]@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:803:56
fire@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:796:281
add@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:797:467
then/</</<@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:802:772
fire@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:796:281
fireWith@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:801:198
then/</</<@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:802:874
fire@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:796:281
fireWith@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:801:198
Deferred/</deferred[tuple[0]]@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:803:56
rpc/<@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:3587:436
then/</</<@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:802:678
fire@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:796:281
fireWith@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:801:198
Deferred/</deferred[tuple[0]]@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:803:56
fire@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:796:281
fireWith@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:801:198
Deferred/</deferred[tuple[0]]@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:803:56
genericJsonRpc/<@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:3556:1
then/</</<@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:802:678
fire@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:796:281
fireWith@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:801:198
then/</</<@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:802:874
fire@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:796:281
fireWith@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:801:198
done@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:1192:86
callback@http://localhost:8069/web/content/350-9a98bea/web.assets_common.js:1212:15

Expected behavior:

Video/Screenshot link (optional):

**Comment by xuehao** [comment] 2018-12-19 12:31
Thanks for your reply.

I tested Odoo 12 on macOS following this [instruction](https://bloopark.de/en_US/blog/the-bloopark-times-english-2/post/setup-odoo-development-on-os-x-with-pycharm-109#blog_content) .

Maybe it's a problem of Firefox and Chrome. When I use Safari, No Error occurs.

Firefox:
<img width="1013" alt="2018-12-19 8 29 24" src="https://user-images.githubusercontent.com/2335731/50220318-034bf780-03cd-11e9-8418-a9c4d300a9e6.png">

And Chrome:
<img width="1015" alt="2018-12-19 8 29 39" src="https://user-images.githubusercontent.com/2335731/50220335-0cd55f80-03cd-11e9-91bb-5f158e2d034a.png">

**Comment by pedrobaeza** [comment] 2018-12-19 12:38
But the steps to reproduce the problem?

**Comment by xuehao** [comment] 2018-12-19 12:45
I just did these things on macOS 10.14.2.

1. Python3

$ brew update
$ brew install python
$ python --version
Python 3.7.1

2. Postgres.app

Postgres.app https://postgresapp.com/

3. dependency

$ brew install freetype jpeg libpng libtiff webp xz

4. python dependency

$ pip install -r requirements.txt
$ pip freeze
Babel==2.3.4
beautifulsoup4==4.6.3
certifi==2018.11.29
chardet==3.0.4
decorator==4.0.10
docutils==0.12
ebaysdk==2.1.5
feedparser==5.2.1
gevent==1.3.4
greenlet==0.4.13
html2text==2016.9.19
idna==2.7
Jinja2==2.8.1
libsass==0.12.3
lxml==4.2.3
Mako==1.0.4
MarkupSafe==0.23
mock==2.0.0
num2words==0.5.6
ofxparse==0.16
olefile==0.46
passlib==1.6.5
pbr==5.1.1
Pillow==4.0.0
psutil==4.3.1
psycopg2==2.7.3.1
pydot==1.2.3
pyldap==2.4.28
pyparsing==2.1.10
PyPDF2==1.26.0
pyserial==3.1.1
python-dateutil==2.5.3
python-stdnum==1.10
pytz==2016.7
pyusb==1.0.0
qrcode==5.3
reportlab==3.3.0
requests==2.20.0
six==1.12.0
suds-jurko==0.6
urllib3==1.24.1
vatnumber==1.2
vobject==0.9.3
Werkzeug==0.11.15
xlrd==1.0.0
XlsxWriter==0.9.3
xlwt==1.3.0

5. db

$ ./odoo-bin -d testdb

6. open http://localhost:8069

Just these things.

Or do you have other instructions about Odoo development on macOS?

**Comment by pedrobaeza** [comment] 2018-12-19 13:02
Do you mean this happens only opening the URL? This is for sure a problem with your deployment, not on Odoo itself, but you should find support in other part on how to install a development environment in MacOS, as the best for this goal is Linux or using Docker.

I would say that at least using requirements.txt file for installing that requirements.

You can also ask on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).

Closing this by the reason above.

**Closed by pedrobaeza** 2018-12-19 13:02 UTC
Labels: Need information

**Comment by 3piece** [comment] 2023-05-15 19:26
For anyone experiencing this error in the future. Check your browser extensions. 

Try opening Odoo in a private browser or a different browser.
Try turning all extensions off, or loading the browser in safe mode.
