### ISSUE TITLE
 value.format is not a function Why this error

### ISSUE THREAD

**Issue by sandeepksrana** [odoo/odoo#23672] opened 2018-03-15 07:53 UTC
Impacted versions: Odoo 11

Steps to reproduce:

Current behavior:  

> value.format is not a function
When copy a date string in date field or any date field value into another date field

 

Expected behavior: it was working fine in odoo 8 9 10

Video/Screenshot link (optional):  Error:
Uncaught TypeError: value.format is not a function

http://192.168.1.39:8069/web/static/src/js/fields/field_utils.js:118
Traceback:
TypeError: value.format is not a function
    at Object.formatDate [as date] (http://192.168.1.39:8069/web/static/src/js/fields/field_utils.js:118:18)
    at Class._renderBodyCell (http://192.168.1.39:8069/web/static/src/js/views/list/list_renderer.js:289:60)
    at http://192.168.1.39:8069/web/static/src/js/views/list/list_renderer.js:576:25
    at Function._.map._.collect (http://192.168.1.39:8069/web/static/lib/underscore/underscore.js:164:24)
    at Class._renderRow [as _super] (http://192.168.1.39:8069/web/static/src/js/views/list/list_renderer.js:575:24)
    at Class._renderRow (http://192.168.1.39:8069/web/static/src/js/views/list/list_editable_renderer.js:499:32)
    at Class._renderRow (http://192.168.1.39:8069/web/static/src/js/core/class.js:123:38)
    at Function._.map._.collect (http://192.168.1.39:8069/web/static/lib/underscore/underscore.js:164:24)
    at Class._renderRows (http://192.168.1.39:8069/web/static/src/js/views/list/list_renderer.js:597:18)
    at Class._renderRows (http://192.168.1.39:8069/web/static/src/js/views/list/list_editable_renderer.js:515:26)

**Comment by sandeepksrana** [comment] 2018-03-16 04:56
can you please ask someone to answer this one or we should change odoo backend for resolving this

**Comment by Yenthe666** [comment] 2018-03-16 06:57
@ged-odoo could you or one of the guys have a look?

**Comment by aab-odoo** [comment] 2018-03-16 07:30
Hello @sandeepksrana 

I can't reproduce your issue. I tried on the crm.lead form view, and copy-pasting dates into the 'Expected closing' date field seems to work fine. Could you provide us more details (or even better, a video)?

Regards.

**Comment by sandeepksrana** [comment] 2018-03-16 08:05
@aab-odoo Hi First Thanks for reply i have seen this is in  /web/static/src/js/fields/field_utils.js. in formatDate function there it return  value.format(date_format); and says TypeError: value.format is not a function. see its working fine whenever we just select the date but when copy a date from a model to another it give this error.  example i have a wizard to show employee list and their joining date i search all the employee and copy their names and joining date from employee model to that wizard and when opening this error is produced. if you could same you can see.
is there any function define of the value in that method in fields_util.js if yes please tell me where it is i don't thing it there i find it in moment.js but its not inherited in the field_utils.js. this same thing working in odoo 8 , 9 but not in 11 

Please let me know thanks

**Comment by aab-odoo** [comment] 2018-03-19 07:34
Hello @sandeepksrana 

I'm not sure to understand your scenario. Can you reproduce on a runbot (e.g. http://312101-11-0-ed3276.runbot11.odoo.com/?db=312101-11-0-ed3276-all, login: admin, pw: admin)? A video would really help...

Regards

**Comment by sandeepksrana** [comment] 2018-03-19 09:35
@aab-odoo  Hi its was very difficult me to share video can please do one think.  just build a new module with wizard having two field employee many2one and a date field and add employee and date of joining from hr.employee into that wizard through default get method or a button, you will get that error.

Thanks
Sandeep

**Comment by sandeepksrana** [comment] 2018-03-19 11:27
@aab-odoo  Hi when i check any model form its giving me as object typeof() in java script and while in wizard it says String is typeof() while check ing formate date method. 

t/web/static/src/js/fields/field_utils.js

function formatDate(value, field, options) {
if (value === false) {
return "";
}
if (field && field.type === 'datetime') {
if (!options || !('timezone' in options) || options.timezone) {
value = value.clone().add(session.getTZOffset(value), 'minutes');
}
}
var date_format = time.getLangDateFormat();
return value.format(date_format);
}

**Comment by sandeepksrana** [comment] 2018-03-20 06:49
@aab-odoo  Hello can you please answer  why the moment object is not sending from wizard to formatDate() function while in model form its sending moment object the value parameter in the formatDate() function actually a moment object which has format method but in wizard case its String in this function why this is happening . can you please reply or just ignoring me

**Comment by kalway-tony** [comment] 2018-04-05 04:44
Yes, I got this situation, I found value need a Moment object, but i got a string , so "Uncaught TypeError: value.format is not a function"

**Comment by aab-odoo** [comment] 2018-04-11 10:00
Hello @kalway-tony

Could you precisely explain the scenario and/or provide a video to reproduce the issue (ideally on a runbot if the problem occurs in standard versions: http://runbot.odoo.com/runbot/repo/git-github-com-odoo-enterprise-7). If it doesn't, could you provide a minimal addon which allows to reproduce it?

Regards

**Comment by lreficent** [comment] 2018-04-12 13:38
Hi everyone,

I had the same issue as @sandeepksrana. 

@aab-odoo I can give you a scenario to reproduce it. Go to the runbot of this PR: https://github.com/OCA/stock-logistics-warehouse/pull/411 and go to "Inventory > Master Data > Reordering Rules", the click on this little gear I point you on the picture below.

![image](https://user-images.githubusercontent.com/23449160/38680718-41934f74-3e67-11e8-8c2a-fd4823724bb9.png)

You will get the error:
![image](https://user-images.githubusercontent.com/23449160/38680784-6e58507c-3e67-11e8-9778-fa4eb83deddd.png)

Thanks!

**Comment by aab-odoo** [comment] 2018-04-12 13:47
Thanks @lreficent, now that i can reproduce i'll be able to fix it.

It seems that the issue occurs because the datetime value comes from a one2many command returned by a default_get. I'll provide a fix asap.

Regards.

**Closed** 2018-04-13 13:01 UTC
Labels: 11.0, Confirmed, Framework

**Comment by lreficent** [comment] 2018-04-13 13:47
Thanks a lot for the fast fix @aab-odoo
