### ISSUE TITLE
Microsoft azure odoo sso - Couldn't find the Secret Key

### ISSUE THREAD

**Issue by cuongdnv2307** [odoo/odoo#46137] opened 2020-02-24 15:42 UTC
I refer to the document below, to perform SSO for Odoo through Azure Microsoft.

https://www.slideshare.net/SerpentcsConsulting/microsoft-azure-odoo-sso-integration

Impacted versions: Odoo 12.0 (Community Edition)

Steps to reproduce: I couldn't find the Secret Key field on the OAuth Providers screen.
https://imgur.com/iZXNftB

Current behavior:

Expected behavior:  The Secret Key field on the OAuth Providers screen in Odoo 10
https://imgur.com/a/lfalM31

How can i set Secret Key ?
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2020-02-24 15:55
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2020-02-24 15:55 UTC
