### ISSUE TITLE
Less issue in ubuntu 18.04

### ISSUE THREAD

**Issue by mevivek4u** [odoo/odoo#25015] opened 2018-06-01 10:39 UTC
Impacted versions: V9

Steps to reproduce: 
Ubuntu 18.04
Odoo Version : 9

Video/Screenshot link (optional): 
![screenshot from 2018-06-01 16-11-34](https://user-images.githubusercontent.com/1643205/40837002-7bfa7edc-65b6-11e8-9e05-62774223d354.png)

**Comment by pedrobaeza** [comment] 2018-06-01 10:41
What is the issue?

**Comment by mevivek4u** [comment] 2018-06-01 10:43
@pedrobaeza The issue is with less and lessc. I have applied all solutions but still getting the same

**Comment by pedrobaeza** [comment] 2018-06-01 10:44
OK, now you have changed the screenshot, but any way, the issue is with your deployment, that you are not installing correctly dependencies. Be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/11.0/setup/install.html. You can also use other package solutions like the DEB package or Docker image.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

**Closed by pedrobaeza** 2018-06-01 10:44 UTC

**Comment by Yenthe666** [comment] 2018-06-01 10:56
and this might also help you https://www.odoo.com/nl_NL/forum/help-1/question/ubuntu-18-04-lts-how-to-install-less-and-sass-compass-and-bootstrap-sass-134194
