### ISSUE TITLE
[8.0][website][Windows] lessc.cmd not found

### ISSUE THREAD

**Issue by 73lines** [odoo/odoo#10769] opened 2016-02-04 10:29 UTC
Steps to reproduce.

1. Install Odoo v8 windows package from nightly.
2. Install website module.
3. Install theme_clean
4. Restart the server and try to configure the page.

Output in Log.

```
2016-02-04 10:19:28,892 36344 ERROR test werkzeug: Error on request:
Traceback (most recent call last):
  File "werkzeug\serving.py", line 177, in run_wsgi
    
  File "werkzeug\serving.py", line 165, in execute
    
  File "C:\Program Files (x86)\Odoo 8.0-20160202\server\openerp\service\server.py", line 290, in app
    return self.app(e, s)
  File "C:\Program Files (x86)\Odoo 8.0-20160202\server\openerp\service\wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "C:\Program Files (x86)\Odoo 8.0-20160202\server\openerp\service\wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "C:\Program Files (x86)\Odoo 8.0-20160202\server\openerp\http.py", line 1290, in __call__
    return self.dispatch(environ, start_response)
  File "C:\Program Files (x86)\Odoo 8.0-20160202\server\openerp\http.py", line 1264, in __call__
    return self.app(environ, start_wrapped)
  File "werkzeug\wsgi.py", line 579, in __call__
    
  File "C:\Program Files (x86)\Odoo 8.0-20160202\server\openerp\http.py", line 1437, in dispatch
    result = ir_http._dispatch()
  File "C:\Program Files (x86)\Odoo 8.0-20160202\server\openerp\addons\website\models\ir_http.py", line 148, in _dispatch
    resp = super(ir_http, self)._dispatch()
  File "C:\Program Files (x86)\Odoo 8.0-20160202\server\openerp\addons\base\ir\ir_http.py", line 175, in _dispatch
    return self._handle_exception(e)
  File "C:\Program Files (x86)\Odoo 8.0-20160202\server\openerp\addons\website\models\ir_http.py", line 196, in _handle_exception
    return super(ir_http, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 8.0-20160202\server\openerp\addons\base\ir\ir_http.py", line 145, in _handle_exception
    return request._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 8.0-20160202\server\openerp\http.py", line 666, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 8.0-20160202\server\openerp\addons\base\ir\ir_http.py", line 171, in _dispatch
    result = request.dispatch()
  File "C:\Program Files (x86)\Odoo 8.0-20160202\server\openerp\http.py", line 684, in dispatch
    r = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 8.0-20160202\server\openerp\http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 8.0-20160202\server\openerp\service\model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 8.0-20160202\server\openerp\http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 8.0-20160202\server\openerp\http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 8.0-20160202\server\openerp\http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files (x86)\Odoo 8.0-20160202\server\openerp\addons\website_less\controllers\main.py", line 35, in css_bundle
    response = request.make_response(bundle.css(), [('Content-Type', 'text/css')])
  File "C:\Program Files (x86)\Odoo 8.0-20160202\server\openerp\addons\website_less\ir_qweb.py", line 121, in css
    content = self.preprocess_css()
  File "C:\Program Files (x86)\Odoo 8.0-20160202\server\openerp\addons\website_less\ir_qweb.py", line 177, in preprocess_css
    cmd = assets[0].get_command()
  File "C:\Program Files (x86)\Odoo 8.0-20160202\server\openerp\addons\website_less\ir_qweb.py", line 339, in get_command
    lessc = which('lessc.cmd', path=os.pathsep.join(defpath))
  File "C:\Program Files (x86)\Odoo 8.0-20160202\server\openerp\tools\which.py", line 148, in which
    raise IOError(ENOENT, '%s not found' % (mode & X_OK and 'command' or 'file'), file)
IOError: [Errno 2] command not found: 'lessc.cmd'
```

**Comment by tvibliani** [comment] 2016-02-18 10:25
Possibly related:
```
2016-02-18 14:22:07,000 13850 ERROR temur_2016_01_12 werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 290, in app
    return self.app(e, s)
  File "/usr/lib/python2.7/dist-packages/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1290, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1264, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 588, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1264, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 588, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1264, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 588, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1264, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 588, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1264, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 588, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1437, in dispatch
    result = ir_http._dispatch()
  File "/usr/lib/python2.7/dist-packages/openerp/addons/website/models/ir_http.py", line 148, in _dispatch
    resp = super(ir_http, self)._dispatch()
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_http.py", line 175, in _dispatch
    return self._handle_exception(e)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/website/models/ir_http.py", line 196, in _handle_exception
    return super(ir_http, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_http.py", line 145, in _handle_exception
    return request._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 666, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_http.py", line 171, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 684, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/var/lib/odoo/.local/share/Odoo/addons/8.0/website_less/controllers/main.py", line 35, in css_bundle
    response = request.make_response(bundle.css(), [('Content-Type', 'text/css')])
  File "/var/lib/odoo/.local/share/Odoo/addons/8.0/website_less/ir_qweb.py", line 121, in css
    content = self.preprocess_css()
  File "/var/lib/odoo/.local/share/Odoo/addons/8.0/website_less/ir_qweb.py", line 177, in preprocess_css
    cmd = assets[0].get_command()
  File "/var/lib/odoo/.local/share/Odoo/addons/8.0/website_less/ir_qweb.py", line 341, in get_command
    lessc = which('lessc', path=os.pathsep.join(defpath))
  File "/usr/lib/python2.7/dist-packages/openerp/tools/which.py", line 148, in which
    raise IOError(ENOENT, '%s not found' % (mode & X_OK and 'command' or 'file'), file)
IOError: [Errno 2] command not found: 'lessc'
```

**Comment by tvibliani** [comment] 2016-02-18 11:19
On a Debian host, the issue is fixed by installing `python-lesscpy` package. it seems error were originated from a missed dependency in the system.

**Comment by 73lines** [comment] 2016-02-21 05:18
@tvibliani : the issue I mentioned is specifically with Windows package of Odoo v8, on ubuntu everything is working perfect.

**Comment by tvibliani** [comment] 2016-02-22 08:02
@73lines I have not mentioned windows at all, I had related issue and as I found issue already reported, I commented here, instead of starting new thread. As I commented above, I fixed it by installing node-less and python-lesscpy packages. What it concerns the Windows case, issue is the same. So you can fix it by installing node-less for Windows and by making sure that commands of node-less are available in cmd (command line), that is the directory, containing lessc* executable of node-less is on the path (if not, then add this directory to the PATH environment variable, it may be added by itself as you install node-less, if not then add it manually). You can check if your installation is correct, by executing lessc command in cmd, if terminal says that it's unknown command, then your setup is not correct (missing PATH entry, or node-less is not installed).

**Comment by sle-odoo** [comment] 2016-06-08 12:38
Closing, as it's a deployment issue. Please note that this issue only concern 8.0 and in this version lessc is not mandatory. Starting from 9, we embed lessc in the windows executable for ease of deployment. To use it in 8.0, you have to install lessc and make the lessc.cmd executable available in the PATH.

Regards

**Closed by sle-odoo** 2016-06-08 12:38 UTC
