### ISSUE TITLE
[12] One2many 'sale.order' / View not working -  Cannot read property 'options' of undefined 

### ISSUE THREAD

**Issue by alrik88** [odoo/odoo#27703] opened 2018-10-12 06:45 UTC
Impacted versions: [12]

Steps to reproduce:

```
class tasty(models.Model):
    _name = 'tasty.process'
    order_ids = fields.One2many('sale.order','process_id ', string='Orders')

class tasty_order(models.Model):
    _inherit = 'sale.order'
    process_id = fields.Many2one('tasty.process')
```

Current behavior:

> Uncaught TypeError: Cannot read property 'options' of undefined
> http://x.x.x.x:8069/web/content/317-ed0663d/web.assets_backend.js:2748
> Zurückverfolgung
> TypeError: Cannot read property 'options' of undefined
>     at Class.init (http://x.x.x.x:8069/web/content/317-ed0663d/web.assets_backend.js:2748:213)
>     at Class.prototype.(anonymous function) [as init] (http://x.x.x.x:8069/web/content/316-deedd5d/web.assets_common.js:3537:488)
>     at new Class (http://x.x.x.x:8069/web/content/316-deedd5d/web.assets_common.js:3538:65)
>     at Class._renderNode (http://x.x.x.x:8069/web/content/317-ed0663d/web.assets_backend.js:2789:156)
>     at Class._renderNode (http://x.x.x.x:8069/web/content/316-deedd5d/web.assets_common.js:3540:371)
>     at Function._.map._.collect (http://x.x.x.x:8069/web/content/316-deedd5d/web.assets_common.js:13:270)
>     at Class._renderTagForm (http://x.x.x.x:8069/web/content/317-ed0663d/web.assets_backend.js:1616:18)
>     at Class._renderNode [as _super] (http://x.x.x.x:8069/web/content/317-ed0663d/web.assets_backend.js:1608:246)
>     at Class._renderNode (http://x.x.x.x:8069/web/content/317-ed0663d/web.assets_backend.js:2790:50)
>     at Class._renderNode (http://x.x.x.x:8069/web/content/316-deedd5d/web.assets_common.js:3540:371)
> 

Video/Screenshot link (optional):
![saleorder](https://user-images.githubusercontent.com/44069871/46852131-3a64c200-cdfa-11e8-950d-b5a7058a7bff.jpg)

**Comment by pedrobaeza** [comment] 2018-10-12 12:17
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2018-10-12 12:17 UTC
Labels: 12.0, Framework

**Comment by edison12347** [comment] 2018-11-22 15:55
@alrik88 did you manage to solve the problem? I have the same issue, opening sale order and product variant from the one2many field since a couple of weeks from now.

**Comment by edison12347** [comment] 2018-11-22 17:11
I found the solution, even though the problem is most probably fixed by now.
My deployment relied on odoo:12.0 image. This problem arose about the same time when new image release was made and this issue was reported.
The issue might existed in the code that was used to build the image odoo:12.0. After I rebuilt image locally from the source code, using default odoo Dockerfile, it disappeared.
@pedrobaeza if you may know who is in charge of building images, I suggest making new release sooner because release 20181109 contains this particular issue.

**Comment by pedrobaeza** [comment] 2018-11-22 17:30
Thanks for the followup. The image is built periodically, so with this process is enough for assuring up to date code soon.

**Comment by edison12347** [comment] 2018-11-22 17:41
P.S. I reported it in docker repo
https://github.com/odoo/docker/issues/230
