### ISSUE TITLE
Warehouse could not creat correct procuement rules

### ISSUE THREAD

**Issue by Guobower** [odoo/odoo#15832] opened 2017-03-11 11:51 UTC
Impacted versions:
10.0 from relased until now
Steps to reproduce:
1、Creat  another warehouse named Material
2、Edit default warehouse, setup resupply warehouse is Material warehouse
3、Disanble the resupply warehouse checked box before Material warehouse
4、Enable the resupply warehouse checked box before Material warehouse

Current behavior:
Every time disable/enable the check box，it will insert duplicate procuement rules recode, the MTO route then include duplicate procuement rules about MTO
Expected behavior:

Video/Screenshot link (optional):
![default](https://cloud.githubusercontent.com/assets/22065407/23823018/cd9ada12-0693-11e7-92a0-0659afd1aad8.png)
![default](https://cloud.githubusercontent.com/assets/22065407/23823024/e2fc3d6a-0693-11e7-9275-8412ea9aa503.png)
![default](https://cloud.githubusercontent.com/assets/22065407/23823027/0e87fc12-0694-11e7-860a-9fc6b80d7ee3.png)

**Comment by pedrobaeza** [comment] 2018-05-10 09:39
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-05-10 09:39 UTC
Labels: 10.0, Logistics
