### ISSUE TITLE
In kanban view, with no content to show the help message mixes with columns.

### ISSUE THREAD

**Issue by shingonoide** [odoo/odoo#2884] opened 2014-10-03 10:17 UTC
![screenshot-area-2014-10-03-065347](https://cloud.githubusercontent.com/assets/27135/4504952/75f1e7a6-4aed-11e4-8b49-cb5325fdf7ba.png)
When there's no content to show in kanban view, the message "there's no content" mixes with kanban_groups(columns).

Impacted versions:

* 7.0 and above

Steps to reproduce: (Surveys is just for example)
* go to Marketing -> Surveys
* remove all surveys if avaiable if any
* click in survey menu again to reload view

Current behavior:
* The message which inform there's no content show with kanban_groups, create a confusion visual. 

Expected behavior:
* I'm expect he see a clealy message here, maybe the table kaban_group can be hide.

**Comment by rim-odoo** [comment] 2015-10-15 14:17
Hi,

I cannot reproduce this bug in v7, it is confirmed in v8 and not existent in v9.
We won't fix it as it is a known glitch of Odoo 8, but not so easy to fix. 
I agree it gives a not very clear view but it does not prevent you to work.

Regards

**Closed by rim-odoo** 2015-10-15 14:17 UTC
