### ISSUE TITLE
[14.0] website: Traceback on edit page

### ISSUE THREAD

**Issue by jat-odoo** [odoo/odoo#71197] opened 2021-05-25 07:56 UTC
Impacted versions:
v14

Steps to reproduce:
I made video what happen when edit page containing too much categories or attributes on page. (Categories are rendered using `t-field`)

Current behavior:
When you have too much `t-field` on page it through traceback when edit page. 

Expected behavior:

Video/Screenshot link (optional):
https://user-images.githubusercontent.com/7599689/119460642-86bb6100-bd5c-11eb-8640-939d93675ad5.mp4

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment] 2021-05-25 16:16
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by jat-odoo** [comment] 2021-05-25 16:33
Hi @pedrobaeza ,

The recorded video is of runbot. :smile: 

On website, If you have too much `t-field` on page it through traceback while edit page. So, you have to create fake records using scripts (As I did, I created 2000 categories using script which are rendered using `t-field` by Odoo).

Let me know if you still need more information for clarification.

**Comment by pedrobaeza** [comment] 2021-05-25 17:06
OK, tagged

**Comment by Yenthe666** [comment] 2021-05-27 06:48
@JKE-be

**Comment by rdeodoo** [comment] 2021-06-02 15:26
Is this a real use case?
Regarding your video, even if the editor supported it, your website would look terrible. You have an almost infinite scrollbar that scroll through blank content..
I don't think any eshop are displaying thousands of categories like that, in a non hierarchic way.

Real use case would be to have hierarchy between categories, and enabling foldable categories -> in which case folded categories won't be loaded, so the issue won't occur. 

IMHO, this is not worth investigating, I don't think a page with thousands of t-field is a real use case.

**Comment by jat-odoo** [comment] 2021-06-06 05:48
Hi @rdeodoo,

Collapsible categories are not lazy-loaded so that will not work.

Yes, I have a real use case with **more than 4k categories**. (See screenshot)

![screenshot-worldcam odoo com-2021 06 03-10_08_45 (1)](https://user-images.githubusercontent.com/7599689/120913940-52c73080-c6b8-11eb-98a5-41db9ae95598.png)

**Comment by Yenthe666** [comment] 2021-06-07 06:03
We don't get to 4K yet but we also have hundreds and hundreds so it can be a real case :)

**Comment by jat-odoo** [comment] 2021-06-07 06:22
Sorry, It is 4k products but there 300+ categories and there are 1400+ of attributes. Means there are lot's of `t-field` on the page.

**Comment by Yenthe666** [comment] 2021-06-07 08:33
Yeah same. Hundreds of categories & thousands of attributes. We have 4.5K attributes.

**Comment by rdeodoo** [comment] 2021-06-07 09:56
> Collapsible categories are not lazy-loaded so that will not work.

Indeed, I read the code too fast. We will improve that in a next version.

For the bug, it seems caused by this line https://github.com/odoo/odoo/blame/4b609c59efd81a650d0cca22e3276817198f5afa/addons/web_tour/static/src/js/tour_service.js#L136
Maybe @qsm-odoo might have a quick understanding of what to do here and if there is a simple possible fix

**Comment by rdeodoo** [comment] 2021-06-14 13:53
> For the bug, it seems caused by this line https://github.com/odoo/odoo/blame/4b609c59efd81a650d0cca22e3276817198f5afa/addons/web_tour/static/src/js/tour_service.js#L136
> Maybe @qsm-odoo might have a quick understanding of what to do here and if there is a simple possible fix

A PR was opened for that exact same bug and same line of code, maybe this is good to merge @qsm-odoo https://github.com/odoo/odoo/pull/72132

**Comment by rdeodoo** [comment] 2021-06-15 08:30
Fixed with https://github.com/odoo/odoo/pull/72132

**Closed by rdeodoo** 2021-06-15 08:30 UTC
Labels: 14.0, Website
