### ISSUE TITLE
[8.0] Reporting - Chart, Filter, Dashboard - selected Measures, Chart Type not saved

### ISSUE THREAD

**Issue by svenpetersen** [odoo/odoo#2835] opened 2014-10-01 14:01 UTC
Hello,

(I know it's possible to set the chart type and the measures in a graph view and an action)

Although you can save a Filter, share it with others and add it to a dashboard, the selected Measures, and Chart Type, (stacked, etc.) are not saved.
Especially for financial analysis, (e.g. entries analysis) it can become quite misleading if the measures are not saved (credit, debit, balance).
So the feature is sadly quite limited for pure endusers without access rights and knowledge of views and actions. 
Would you consider to not only save filters but also graph view options through the gui?

with kind regards,
Sven

**Comment by Cedric-Pigeon** [comment] 2015-01-12 12:48
I have the same problem and this is really annoying.

Is there any solutions ?

**Comment by Cedric-Pigeon** [comment] 2015-01-12 12:54
I have the same problem and this is really annoying.

Is there any solutions ?

**Comment by mathi123** [comment] 2015-01-30 16:04
+1
Nobody has a temporty solution?

**Comment by binarybabel** [comment] 2015-01-31 00:41
There is a temporary solution, but it's painfully complicated. It depends heavily on the data source of the graph as well. In this example I will be working with an accounting entries graph.

### Fork the existing graph view
**Settings » User Interface » Views**

* Find the existing view "account.entries.report.graph" and duplicate it with a new name, such as "account.entries.report.graph.pie"
* Change the graph xml type from "pivot" to "pie".
* Adjust the field entries to match what you would have selected from the measure's dropdown.

Here's an example of what it could look like:
![image](https://cloud.githubusercontent.com/assets/3771540/5985820/f4293e58-a8df-11e4-94fc-02a44396d6c8.png)

### Create a new window action
**Settings » Actions » Window Actions**

* Choose any action name you want. I like to add the section symbol § to the end so that I can easily find all views that I created manually.
* The object should match the datasource for your graph, in this case "account.entries.report"
* View type = Form
* View mode = graph
* View ref = *Search for the view you created earlier*
* The domain doesn't technically matter, because it's overridden in your dashboard entry.
* Save new action
* Look in the URL bar for "id=" and note down the id of your new action

Here's a screenshot of the result:
![image](https://cloud.githubusercontent.com/assets/3771540/5985890/5fdae740-a8e1-11e4-8b19-97e760dfca44.png)

### Update your dashboard
**Settings » User Interface » Customized Views**

* Edit the topmost version of "My Dashboard"
* Find the "action" tag for the graph you're customizing.
* Change the "name=" value to the id of your new action
* Save changes

### Follow up notes

In theory it should be possible to specify "view_id" in the dashboard action xml, just like "view_mode" is specified, thus skipping the need for a custom action. However, I've never been able to get that to work, either with the view's numerical id or name.

**Comment by mathi123** [comment] 2015-02-01 09:51
Thanks!

**Comment by yveshoyos** [comment] 2015-03-18 10:22
Thanks for the workarround, but will this issue be fixed directly in the Odoo standard, without having to do this complex procedure?
Thanks

**Comment by binarybabel** [comment] 2015-03-18 23:02
@yveshoyos The workaround was discovered as part of our general usage, we're not part of the odoo team, so only the admins can answer that for you.

**Comment by mistotebe** [comment] 2015-06-10 10:10
The commit does not actually fix this issue. It fixed the issue where a saved filter on task analysis would not record the measures.

This issue is instead about measures not being applied when a report is saved on the dashboard. The data is actually saved in the action (as mentioned in comment 3) but the dashboard does not take that into account and uses the default measures instead.

**Comment by click2prasanth** [comment] 2015-08-31 06:44
Did anybody got the solution ?? to create the custom dash board

**Comment by pedrobaeza** [comment] 2016-02-09 11:51
For references, a fix has been proposed in OCB in https://github.com/OCA/OCB/pull/437

**Comment by Yenthe666** [comment] 2017-10-09 18:05
Hi @svenpetersen,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Closed by Yenthe666** 2017-10-09 18:05 UTC
