### ISSUE TITLE
[14.0] Cannot create bank account without administration permissions.

### ISSUE THREAD

**Issue by GSLabIt** [odoo/odoo#94680] opened 2022-06-27 12:55 UTC
Impacted versions: [14.0]

**edit**: seems 15.0 is also impacted (tested locally)

Steps to reproduce:
1. Set an user as Billing Administrator rule
2. Leave empty Administrator rules
3. Go to Invoicing -> Configuration -> Add Bank Account 

Access error is raised. 

Expected behavior: Billing Administrator User should be able to create a bank account without Administration permission

Video/Screenshot link (optional):

https://recordit.co/DsCnX00oy1

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment] 2022-06-28 10:13
@qdp-odoo @oco-odoo maybe you can check this.

**Comment by elvise** [comment] 2022-08-05 14:28
> @qdp-odoo @oco-odoo maybe you can check this.

@pedrobaeza any good news for this ?

**Comment by pedrobaeza** [comment] 2022-08-05 16:23
Sorry, nothing that I can do on my side.

**Comment by elvise** [comment] 2022-08-05 17:04
@pedrobaeza can we reopen this one:
https://github.com/OCA/bank-payment/pull/931

**Comment by pedrobaeza** [comment] 2022-08-05 17:08
The problem is not there in such repo, so there's no sense in having it opened.

**Comment by francesco-ooops** [comment] 2023-03-07 09:20
@pedrobaeza FYI this was solved [here](https://github.com/odoo/odoo/commit/b086df9bb4bffcc5cfd907b08aab535f466c88b8) 👍

@GSLabIt you can close the issue!

**Comment by pedrobaeza** [comment] 2023-03-07 11:29
Great, closing myself. Thanks for the followup.

**Closed by pedrobaeza** 2023-03-07 11:29 UTC
