### ISSUE TITLE
[12.0][14.0] Product Form View Attribute Values keep showing after Archiving its product variant

### ISSUE THREAD

**Issue by mardisiaw** [odoo/odoo#66973] opened 2021-02-28 04:16 UTC
Impacted versions:12.0, 14.0

Steps to reproduce:
 Enable Product Variant in setting. 
 Create product from Products Form View, in tab Variants -> Create new attribute value (ie. Blue, Red)
 Then open product Variants Tree View -> Archive one of created attribute value (ie. Blue) product.
 Re-Open Products Form View, in tab Variants -> The archived attribute value is still showing.

Current behavior:
 After archived the attribute value, then creating new other attribute value, the archived attribute value before is unarchived   automatically.

Expected behavior:
 Every archived attribute value is deleted from products form view, attribute values.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by gdgellatly** [comment] 2021-02-28 07:46
@mardisiaw It is an interesting question.

Lets extend it a bit and see what you think.

I create new attribute value line 1, (Blue, Red).
I create new sttribute value line 2, Memory, (16GB, 32GB)

I open Blue 16GB variant and archive it.

What now should I expect?

**Comment by mardisiaw** [comment] 2021-02-28 10:19
When 2 attribute set (color: Blue,red & memory: 16,32), than we have 4 product variants. After we archive the  blue 16gb, than we still have blue 32, red 16, red 32. So all attribute still there.
But when we archive another blue 32gb, or red 16gb than one of the product attribute will be deleted, either blue or 16gb deleted from its attribute.

**Comment by mardisiaw** [comment] 2021-02-28 10:28
Lets see the matrix below:
2 Attribute : color & memory
2 value for each attribute: blue,red & 16gb,32gb
So in odoo product form view, variant tab:
Color: blue, red
Memory: 16gb, 32gb

After archive blue 16gb, still same view,
But let say there have 2 scenario:
1. after archive another blue 32gb, the view will be:
Color: red
Size: 16gb, 32gb
Because there are no more blue color in variants

2. Or after archive another red 16gb, the view will be:
Color: blue, red
Size: 32gb
Because there are no more 16gb in variants

**Comment by gdgellatly** [comment] 2021-02-28 10:38
@mardisiaw My point is that actually, allowing archive on the product is the wrong behaviour in a variant situation. Only exclusions or editing the template to archive some variants by manipulating attribute values should be allowed. 

Archiving the attribute value only if all other variants are archived is an undesirable behaviour change that leads to unpredictability. Sometimes products will just be unarchived, sometimes they wouldn't.

**Comment by pedrobaeza** [comment] 2021-02-28 18:34
Yes, archiving a product variant with an attribute value doesn't mean that you can't use that attribute value in another combination.

Closing as no issue, but intended behavior.

**Closed by pedrobaeza** 2021-02-28 18:34 UTC
