### ISSUE TITLE
Connection lost when trying to view customers,

### ISSUE THREAD

**Issue by olubiyi80** [odoo/odoo#31476] opened 2019-02-27 16:47 UTC
Impacted versions:
12.0
Steps to reproduce:
Install Odoo version 12 with PostgreSQL version 11.0
Current behavior:
Every other app opens, but connection lost when trying to view customers or contacts

Expected behavior:
to be able to view customer details

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2019-02-27 16:52
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by olubiyi80** [comment] 2019-02-27 17:00
I could access them until I upgraded Postgresql from version 9.5, what could be the problem, is odoo not compatible with PostgreSQL 11.0?

**Comment by pedrobaeza** [comment] 2019-02-27 17:03
Well, maybe the upgrade is not correct or there's an incompatibility. The official supported version is not v11 indeed.

**Comment by olubiyi80** [comment] 2019-02-27 17:09
Sorry to ask, is 9.5 the official version?

**Comment by pedrobaeza** [comment] 2019-02-27 17:20
I'm not sure right now if 9.5 or 9.6. It's the one aligned with last Debian stable version. I can assure you that PG 10 works without problem.

**Closed** 2019-02-27 18:17 UTC
Labels: Need information

**Comment by AnilKesariya** [comment] 2020-09-26 07:24
psql (PostgreSQL) 10.14 (Ubuntu 10.14-0ubuntu0.18.04.1)
Odoo 12 version

proxy_mode and workers also configured well.

I face the same connection lost error when I try to change sales person on quotation and creating invoice from quotation. it is changes the sales person correctly and creates an invoice too. but this warning popup which taking attention for users that system has some error.

If somebody has solved it already would appreciated

Thanks.
