### ISSUE TITLE
Odoo 13 403: Forbidden The page you were looking for could not be authorized

### ISSUE THREAD

**Issue by anoureldin** [odoo/odoo#48387] opened 2020-03-25 22:47 UTC
Hello
Guests can't access shop they can open home and contact us when they try to open shop they get 
403: Forbidden The page you were looking for could not be authorized.
 also if i send product link they can open but if i send Categories link they get same error .

also get this when try to signup 

403: Forbidden
The page you were looking for could not be authorized.

Error message:

Sorry, you are not allowed to access documents of type 'Journal Entries' (account.move). This operation is allowed for the groups:
	- Expenses/Team Approver
	- Expenses/Team Approver
	- Invoicing/Billing
	- Invoicing/Billing Administrator
	- Purchase/Administrator
	- Purchase/User
	- Purchase/User
	- Sales/Administrator
	- Sales/User: Own Documents Only
	- User types/Portal - (Operation: read, User: 10)

**Comment by pedrobaeza** [comment] 2020-03-26 13:13
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by anoureldin** [comment] 2020-03-26 17:02
> Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?
> 
> If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.
> 
> If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.
> 
> For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

thanks for your help 
it was because module conflict when i deleted it every thing works good

**Comment by pedrobaeza** [comment] 2020-03-26 17:07
OK, then let's close this.

**Closed by pedrobaeza** 2020-03-26 17:07 UTC
Labels: Need information
