### ISSUE TITLE
sum attribute on a field of a tree view is only computing the sum for the current page

### ISSUE THREAD

**Issue by khalyomede** [odoo/odoo#35557] opened 2019-08-08 10:23 UTC
**Impacted versions:**

- 11

**Steps to reproduce:**

1. Make a tree view:

```xml
<record id="my_tree" model="ir.model.view">
  <field name="name">My tree</field>
  <field name="model">res.partner</field>
  <field name="arch" type="xml">
    <tree>
      <field name="name" />
      <field name="credit" string="Amount due" sum="Total amount due" />
    </tree>
  </field>
</record>
```

2. Navigate between pages: the sum is only computing for the current viewed page.

**Current behavior:**

The sum is computed for the current viewed page only.

**Expected behavior:**

I do not know if it is expected, but could we have an option to compute it for the whole pages instead of the current page? maybe something like:

```xml
<field name="credit" string="Amount due" total="Total amount due" />
```

**Video/Screenshot link (optional):**

Don't have one.

**Comment by Yenthe666** [comment] 2019-08-08 10:47
@khalyomede this has been the case across all Odoo versions and was built so by design. If you want the sum of all records you will need to modify the amount of records shown in your tree view.
Right @pedrobaeza / @mart-e?

**Comment by khalyomede** [comment] 2019-08-08 10:56
@Yenthe666 I am afraid this solution can cause latency in the UI since a tree can hold a lot of information (in my example this tree only has 2 fields, but in reality in my case my tree contains 7 fields, including a `many2many_tags` widget on one field). This is the reason I asked to know if there is a way to compute the "total" (let us call it like this for the moment) sum across the pages while keeping the pagination.

Your thoughts on this?

**Comment by pedrobaeza** [comment] 2019-08-08 10:59
Indeed this is designed that way because sum is computed client side. In fact, it varies depending on the selected elements in the tree.

If you want totals, list all the elements in the tree. Other option that is computed server side is to group by any element. Totals there are computed server side, and not sure right now if the general sum is shown client side summing all the groups subtotals.

Closing as no issue, but intended behavior.

**Comment by Yenthe666** [comment] 2019-08-08 11:00
No need for an example; I get your point and what you're trying but it is outside of the ORM. Just get your totals from the report views or compute it in another field for example.

**Closed by pedrobaeza** 2019-08-08 10:59 UTC
Labels: 11.0, Framework
