### ISSUE TITLE
[10.0] create new company report create_warehouse error

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#17860] opened 2017-06-28 00:37 UTC
Impacted versions:
10.0 CE

Steps to reproduce:
1, run odoo 10 on windows 10
2, create new database for  odoo10 with demo data
3, enable multi-company
4, install inventory application
5, create new company, report 

Current behavior:

it can not create warehouse, report `type error`
```
Traceback (most recent call last):
  File "C:\_odoo\odoo\odoo\http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\_odoo\odoo\odoo\http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "C:\_odoo\odoo\odoo\http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\_odoo\odoo\odoo\service\model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\_odoo\odoo\odoo\http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\_odoo\odoo\odoo\http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "C:\_odoo\odoo\odoo\http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "C:\_odoo\odoo\addons\web\controllers\main.py", line 885, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "C:\_odoo\odoo\addons\web\controllers\main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\_odoo\odoo\odoo\api.py", line 679, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "C:\_odoo\odoo\odoo\api.py", line 664, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "C:\_odoo\odoo\addons\stock\models\res_company.py", line 37, in create
    self.env['stock.warehouse'].sudo().create({'name': company.name, 'code': company.name[:5], 'company_id': company.id})
  File "C:\_odoo\odoo\addons\stock\models\stock_warehouse.py", line 90, in create
    vals['view_location_id'] = self.env['stock.location'].create(loc_vals).id
  File "C:\_odoo\odoo\odoo\models.py", line 3830, in create
    record = self.browse(self._create(old_vals))
  File "C:\_odoo\odoo\odoo\models.py", line 3958, in _create
    pleft = cr.fetchone()[0] + 1
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

```

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment] 2017-06-28 06:20
Hi @jeffery9,

Thank you for your report.
Can you try to reproduce this on the latest runbot (runbot.odoo.com)? I've just tested this and I can create another company and warehouse without any issues.

Regards,
Yenthe

**Comment by jeffery9** [comment] 2017-06-28 11:12
Can't reproduce this on runbot but on my own deployment on windows.  

I have upload  python Memory Snapshot, If this is useful for you're trouble shooting, You can get it via http://pan.baidu.com/s/1dFiWTS9

**Comment by Yenthe666** [comment] 2017-06-28 11:29
Hi @jeffery9,

Can you please update your Odoo source code and try again then?
It looks like it has been fixed in the meanwhile and that you're Odoo doesn't have the fix yet.

**Comment by jeffery9** [comment] 2017-06-28 11:32
I running my development lab with the latest source code always.

**Comment by jeffery9** [comment] 2017-06-28 11:45
it seemed that  `stock.location` lost the parent related id.  like bellow.

product.category is ok
stock.location is bad

```
odoo=# select   id,parent_left,parent_right from stock_location    order by id limit 10;
 id | parent_left | parent_right
----+-------------+--------------
  1 |             |
  2 |             |
  3 |             |
  4 |             |
  5 |             |
  6 |             |
  7 |             |
  8 |             |
  9 |             |
 10 |             |
(10 行记录)


odoo=# select id,parent_left,parent_right from product_category;
 id | parent_left | parent_right
----+-------------+--------------
  3 |           1 |            2
  6 |           4 |            5
  4 |           6 |            7
  5 |           8 |            9
  2 |           3 |           10
  1 |           0 |           11
(6 行记录)



```

**Comment by bosd** [comment] 2017-09-14 05:10
Is there any sollution to this issue??
I encountered the same problem, on a new database in v10 (CE latest). With official odoo addons only.
However I've faild to replicate some steps to create this error.

An google search showed multiple threatds from version 8 - v10 about this same error. All without an sollution or exact steps to reproduce.

**Comment by mamcode** [comment] 2017-10-02 14:47
@jeffery9 Did you find a way to solve this error?

**Comment by FLovison** [comment] 2017-11-21 17:20
Same error with stock.location lost the parent related id :

>  id |             name             | parent_left | parent_right 
----+------------------------------+-------------+--------------
  1 | Physical Locations           |             |             
  2 | Partner Locations            |             |             
  3 | Virtual Locations            |             |             
  4 | Scrapped                     |             |             
  5 | Inventory adjustment         |             |             
  6 | Procurements                 |             |             
  7 | Production                   |             |             
  8 | Vendors                      |             |             
  9 | Customers                    |             |             
 10 | Inter Company Transit        |             |             
 11 | WH                           |             |             
 12 | Packing Zone                 |             |             
 13 | Input                        |             |             
 14 | Quality Control              |             |             
 15 | Stock                        |             |             
 16 | Output                       |             |             
 17 | My Company: Transit Location |             |             
(17 rows)


While waiting for a serious patch, I replicate values from another clean db ...

**Comment by gdgellatly** [comment] 2017-12-13 00:11
@Yenthe666 still present in v11, just got it on a fresh database.  The only thing I did differently to normal was created the database with -d flag, but all modules installed by hand.  Add a company and boom, that error.

Executed `ALTER TABLE stock_location drop COLUMN parent_right, drop COLUMN parent_left;` then updated modules and things worked fine again.

**Comment by Yenthe666** [comment] 2017-12-13 07:06
@jco-odoo and @sle-odoo this is something we should really look at.

**Comment by sle-odoo** [comment] 2017-12-13 08:08
We get this ticket really often, it's because the computation of parent left and right failed. You can try to upgrade the stock module or call `self.env['stock.location']._parent_store_compute()` in a server action or the shell. I already tried to look at this issue but i'm not able to reproduce it reliably, it's difficult to know where the problem is. Besides, it's more of an ORM issue.

**Comment by gdgellatly** [comment] 2017-12-13 08:29
how about

```python
try:
    vals['view_location_id'] = self.env['stock.location'].create(loc_vals).id
except TypeError:
    # Because we get lots of tickets for last 4 versions when parent store isn't 
    # computed and don't know why. Framework team please look at
    self.env['stock.location']._parent_store_compute()
    vals['view_location_id'] = self.env['stock.location'].create(loc_vals).id
```

**Comment by pedrobaeza** [comment] 2018-06-01 00:26
@gdgellatly if this still happening, please put a PR with your proposal.

I haven't personally faced this in all the years I'm working with Odoo, so maybe it's a question of deployment.

Any way, I'm closing this as an alternative workaround has been proposed, and now in v12 there's no more parent_left / parent_right architecture, which radically removes this bug.

**Closed by pedrobaeza** 2018-06-01 00:26 UTC
Labels: 10.0

**Comment by TarikIbrahim** [comment] 2020-12-20 03:16
> @Yenthe666 still present in v11, just got it on a fresh database. The only thing I did differently to normal was created the database with -d flag, but all modules installed by hand. Add a company and boom, that error.
> 
> Executed `ALTER TABLE stock_location drop COLUMN parent_right, drop COLUMN parent_left;` then updated modules and things worked fine again.

worked fine on v10

**Comment by TheHardest18** [comment] 2022-10-05 20:55
> @gdgellatly if this still happening, please put a PR with your proposal.
> 
> I haven't personally faced this in all the years I'm working with Odoo, so maybe it's a question of deployment.
> 
> Any way, I'm closing this as an alternative workaround has been proposed, and now in v12 there's no more parent_left / parent_right architecture, which radically removes this bug.

Thanks this is the answer.
