### ISSUE TITLE
[10] Field One2many and attribute inverse return repeat values

### ISSUE THREAD

**Issue by igallart** [odoo/odoo#29516] opened 2018-12-13 12:36 UTC
Impacted versions: 
10

Steps to reproduce:
In product template, I create a field with this structure:

```
_inherit = 'product.template'

packing_tmpl_ids = fields.One2many(
        comodel_name="product.template.packing",
        inverse_name="product_tmpl_id",
        inverse="_inverse_packing_tmpl_ids"
    )
```

```
 def _inverse_packing_tmpl_ids(self):
        for template in self:
            ....
            packing = [(0, 0, {
                "any_value": 999,               
            }) for x in packing_tmpl_ids]
```

```
class ProductTemplatePacking(models.Model):
    _name = "product.template.packing"

    product_tmpl_id = fields.Many2one(
        string="Product Template",
        comodel_name="product.template",
        required=True,
        ondelete="cascade",
    )
```

This for is looped the number of records that are save more the lines from tree product.template.packing:

packing = [1,2, NewId, NewId]
NewId is the record 1 and record 2

The problem is that the newId from the table product.template.packing that I write are read, and the for is looped the double of times.

Expected behavior:
Only loop two times when there are two lines.

**Comment by pedrobaeza** [comment] 2018-12-13 12:48
The problem is you are using an attribute for something that is not intended for. `inverse` is only for computed non stored fields. The rest of the combinations is an abuse of the ORM framework, and thus, unexpected things will happen.

Closing this as misuse of the framework.

**Closed by pedrobaeza** 2018-12-13 12:48 UTC

**Comment by igallart** [comment] 2018-12-13 12:56
@pedrobaeza, correct!

One can define a field whose value is computed instead of simply being
        read from the database. The attributes that are specific to computed
        fields are given below. To define such a field, simply provide a value
        for the attribute ``compute``.

        :param compute: name of a method that computes the field

        :param inverse: name of a method that inverses the field (optional)

I don't read the doc, sorry.
