### ISSUE TITLE
Make Payment using Preview option in Sales Order

### ISSUE THREAD

**Issue by JADCO5692** [odoo/odoo#21711] opened 2017-12-18 18:30 UTC
Hi Team,

I am getting the followig error when i make an authorize payment from sales order using preview button in odoo 10.

2017-12-18 17:26:21,238 888 ERROR test2 werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/odoo/service/wsgi_server.py", line 186, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/odoo/service/wsgi_server.py", line 172, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/odoo/http.py", line 1308, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/odoo/http.py", line 1282, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 588, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/odoo/http.py", line 1481, in dispatch
    result = ir_http._dispatch()
  File "/opt/odoo/addons/website_sale/models/ir_http.py", line 15, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/opt/odoo/addons/website/models/ir_http.py", line 218, in _dispatch
    resp = super(Http, cls)._dispatch()
  File "/opt/odoo/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/opt/odoo/addons/utm/models/ir_http.py", line 20, in _dispatch
    response = super(IrHttp, cls)._dispatch()
  File "/opt/odoo/odoo/addons/base/ir/ir_http.py", line 199, in _dispatch
    return cls._handle_exception(e)
  File "/opt/odoo/addons/website/models/ir_http.py", line 270, in _handle_exception
    return super(Http, cls)._handle_exception(exception)
  File "/opt/odoo/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 768, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo/http.py", line 827, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/payment_authorize/controllers/main.py", line 25, in authorize_form_feedback
    request.env['payment.transaction'].sudo().form_feedback(post, 'authorize')
  File "/opt/odoo/addons/website_portal_sale/models/payment.py", line 47, in form_feedback
    res = super(PaymentTransaction, self).form_feedback(data, acquirer_name)
  File "/opt/odoo/addons/payment/models/payment_acquirer.py", line 582, in form_feedback
    return getattr(tx, feedback_method_name)(data)
  File "/opt/odoo/addons/payment_authorize/models/payment.py", line 213, in _authorize_form_validate
    res = transaction.create_customer_profile_from_tx(self.partner_id, self.acquirer_reference)
  File "/opt/odoo/addons/payment_authorize/models/authorize_request.py", line 186, in create_customer_profile_from_tx
    res['profile_id'] = response.find('customerProfileId').text
AttributeError: 'NoneType' object has no attribute 'text'

Thanks & Regards

**Comment by JADCO5692** [comment] 2017-12-18 18:57
Also, this should be marked to re-produce the error

![image](https://user-images.githubusercontent.com/5710396/34122704-55bd21dc-e453-11e7-80a9-2a790f4ecf37.png)

**Comment by JADCO5692** [comment] 2017-12-18 18:58
![image](https://user-images.githubusercontent.com/5710396/34122778-8c80fcca-e453-11e7-969b-9ba3fb16595c.png)


Also this should be marked in order to reproduce

**Comment by Yenthe666** [comment] 2017-12-19 08:27
Hi @JADCO5692,

Thanks a lot for your bug report.
@tbe-odoo another payment provider related issue. Could you or @tde-banana-odoo have a look?

Regards,
Yenthe

**Comment by tbe-odoo** [comment] 2017-12-19 10:08
Hello @JADCO5692 

I tried in a local 10.0 instance and I couldn't reproduce the bug.
Are you still able to reproduce the bug ? Are you able to put a debugger to provide me more information ?

Thanks :)

**Comment by tbe-odoo** [comment] 2017-12-20 00:04
Hello @JADCO5692 

After investigating, I found out that it might be because the "Customer Information Manager" option isn't activated on your Authorize.net account.

This is indeed an issue we have to fix by warning with an error message what should be done to fix it.

Could you please confirm me that activating the "Customer Information Manager" option solves your issue ? So we can move forward and write a fix for this bug.

**Comment by Yenthe666** [comment] 2017-12-29 10:18
Hi @JADCO5692,

Can you confirm that activating the "Customer Information Manager" option solves your issue ? If you can provide us with feedback we can make a fix.

**Comment by Elkasitu** [comment] 2018-01-03 10:01
@JADCO5692 the traceback is fixed in commit 864ca50 for 11.0, we can backport to 10.0 if necessary

@tbe-odoo You might want to use this error-checking to notify the user that he needs to enable Customer Information Manager with something like ```python3if err_code == 'EXXXXXX':`

**Comment by JADCO5692** [comment] 2018-01-03 11:57
I have asked client to enable it.
Kindly add a message instead of showing such errors to customer

**Comment by Yenthe666** [comment] 2018-01-03 12:18
@Elkasite the new error message is not wrapped with the translation tag _(). Can you still add it in please? Otherwise it'll always be in English.

**Comment by Elkasitu** [comment] 2018-01-03 12:50
@Yenthe666 It's not needed as the error message is only displayed in debug mode and the authorize.net error message is returned in english anyway.

Or did you mean the snippet of code I posted above? if so, it's just a PoC

**Comment by Yenthe666** [comment] 2018-01-03 15:28
Okay, all good then! Thanks.

**Comment by Yenthe666** [comment] 2019-10-07 09:49
As it has been fixed in V11 and up and as Odoo 10 is no longer officially supported I'm closing off this issue.

**Closed by Yenthe666** 2019-10-07 09:49 UTC
Labels: 10.0, Confirmed, Services
