### ISSUE TITLE
Can't open setting app in my dashboard of odoo 13, odoo client error popup.

### ISSUE THREAD

**Issue by Ahmedposhi** [odoo/odoo#44042] opened 2020-01-27 17:27 UTC
![odoo_client_error](https://user-images.githubusercontent.com/40128980/73197976-f4408880-413a-11ea-98fc-bfb72da2dc7a.png)
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by Ahmedposhi** [comment] 2020-01-27 17:40
here is the error from Chrome browser: 
--------------------------------------------
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/src/odoo/13.0/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/13.0/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/13.0/addons/web/controllers/main.py", line 1319, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/13.0/addons/web/controllers/main.py", line 1311, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/13.0/odoo/api.py", line 391, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/home/odoo/src/odoo/13.0/odoo/api.py", line 364, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 1432, in load_views
    for [v_id, v_type] in views
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 1432, in <dictcomp>
    for [v_id, v_type] in views
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/res_config.py", line 386, in fields_view_get
    toolbar=toolbar, submenu=submenu)
  File "/home/odoo/src/odoo/13.0/addons/web/models/models.py", line 203, in fields_view_get
    r = super().fields_view_get(view_id, view_type, toolbar, submenu)
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 1519, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(self._name, etree.fromstring(result['arch']), view_id)
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_ui_view.py", line 964, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_ui_view.py", line 592, in raise_view_error
    raise ValueError(message)
ValueError: Field `google_font_api_key` does not exist

Error context:
View `n/a`
[view_id: n/a, xml_id: n/a, model: n/a, parent_id: n/a]

**Comment by pedrobaeza** [comment] 2020-01-27 20:46
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Ahmedposhi** [comment] 2020-01-27 21:07
i didn't use the runbot before, but i already accessed it with my odoo account. so what can i do then? 

and yes i tried to install this module " website_theme_flexible-11.0.1.0.1 "

**Comment by Yenthe666** [comment] 2020-01-27 21:21
website_theme_flexible-11.0.1.0.1 on a V13 ? Are you sure that's not a V11 theme you're deploying on a V13 instance ?

**Comment by Ahmedposhi** [comment] 2020-01-27 22:10
> 
> 
> website_theme_flexible-11.0.1.0.1 on a V13 ? Are you sure that's not a V11 theme you're deploying on a V13 instance ?

i make mistake by deploying that version

**Comment by pedrobaeza** [comment] 2020-01-27 22:25
Any way, this is a third party module, so nothing to do with this issue tracker, which is for standard Odoo code, so closing.

**Closed by pedrobaeza** 2020-01-27 22:25 UTC
Labels: Need information

**Comment by Ahmedposhi** [comment] 2020-01-27 22:29
> 
> 
> Any way, this is a third party module, so nothing to do with this issue tracker, which is for standard Odoo code, so closing.

But how can i solve this issue?

**Comment by Ahmedposhi** [comment] 2020-01-27 22:30
> 
> 
> Any way, this is a third party module, so nothing to do with this issue tracker, which is for standard Odoo code, so closing.

but this third party not installed on my db because it's not compatible with my version.

**Comment by pedrobaeza** [comment] 2020-01-27 22:35
Please ask on forums for support. You have tried to install that module and then it seems you have broken the DB.

**Comment by Yenthe666** [comment] 2020-01-28 07:00
You really shouldn't install apps from other versions on a database, it will almost always give problems. Deinstall the app and then install the right version.

**Comment by Ahmedposhi** [comment] 2020-01-28 10:28
I can't see this app on my dashboard, is there any other way to uninstall
it?

**Comment by Yenthe666** [comment] 2020-01-28 10:31
I think its time for you to move to the official help forums as @pedrobaeza suggested and you might want to read up on how the framework/system works and how it handles apps. It's an important part.
