### ISSUE TITLE
First internal note becomes email

### ISSUE THREAD

**Issue by werkwolk** [odoo/odoo#66235] opened 2021-02-15 23:28 UTC
Impacted versions: 14 community (latest nightly build)

Steps to reproduce: create opportunity -> create internal note -> will add partner as follower and mark as "sent message". after that all is ok and internal messages are ok again. UNTIL you remove the follower and create an internal note again and the same happens. I did NOT mark it as non internal or whatsoever. 

Current behavior: in runbot this works fine, i have no idea how i managed to do this, but i cant unmanage it. Please do not close this just because runbot does it properly. its a terrible problem and others have it too (see #59681) I added a video link beneath

Expected behavior: internal note should remain internal on first note

Video/Screenshot link (optional):  

https://user-images.githubusercontent.com/69362083/108001767-b1737c00-6fed-11eb-8177-b7041d96c925.mp4

**Comment by Yenthe666** [comment] 2021-02-17 09:20
Did you check this? 
> Probably, the subtype "Note" has unchecked the mark "Internal". Closing as no Odoo issue at all.

Sorry but if you cannot reproduce it on runbot we really cannot do anything about it. CC @pedrobaeza

**Comment by pedrobaeza** [comment] 2021-02-17 09:22
Yes, I agree. We need reproducible steps in standard code without possible interference, so closing.

**Closed by pedrobaeza** 2021-02-17 09:22 UTC

**Comment by werkwolk** [comment] 2021-02-17 15:15
> Did you check this?
> 
> > Probably, the subtype "Note" has unchecked the mark "Internal". Closing as no Odoo issue at all.
> 
> Sorry but if you cannot reproduce it on runbot we really cannot do anything about it. CC @pedrobaeza

Dear Yenthe,

I was afraid for that reply so i put it in my opening that i didn't do that.  
 
> Yes, I agree. We need reproducible steps in standard code without possible interference, so closing.

I just performed it on a new database/install and it happens again. 

Let's hope someone in the community takes it serious enough, because a lot of people will send internal notes to external people by accident

**Comment by Yenthe666** [comment] 2021-02-17 15:21
@werkwolk well there has to be some flow to reproduce it or there's nothing we can do. 
We could keep it open but the conclusion is easy: nobody from Odoo will even consider it without exact steps to reproduce.

**Comment by werkwolk** [comment] 2021-02-17 15:32
> @werkwolk well there has to be some flow to reproduce it or there's nothing we can do.
> We could keep it open but the conclusion is easy: nobody from Odoo will even consider it without exact steps to reproduce.

Hey Yenthe 

indeed, I fully understand.  No need to keep it open. 

thx for your feedback!

**Comment by werkwolk** [comment] 2021-02-17 16:59
is there a  way to see the odoo.conf file of a (running online) runbot? i would like to compare it to my own install.

**Comment by Yenthe666** [comment] 2021-02-17 17:10
No, they're completely shielded off.. It doesn't make sense to compare them probably as they have completely different purposes and run in clusters ;)

**Comment by werkwolk** [comment] 2021-02-17 17:13
i've been trying to get this setup running too -> firewall with haproxy -> multiple odoo instances with nginx for the longpolling. Its been quite the struggle since indeed everything is shielded off. If you have any references for me, it would help me a lot.

**Comment by Yenthe666** [comment] 2021-02-17 17:30
There's very little public content about this I'm afraid, sorry!

**Comment by werkwolk** [comment] 2021-02-17 18:17
believe it or not...but it all works right out of the box (workers > 0 without reverse proxying longpolling etc) and the crm/logs with ....a windows version of odoo! it took me almost a week to get 1 linux version running...this windows version was ready within 15mins.

**Comment by Yenthe666** [comment] 2021-02-17 18:50
You'll get your fair share of joy with Windows at some time haha. There's a reason why plenty of people run it on Linux and not Windows 😆

**Comment by werkwolk** [comment] 2021-02-17 19:06
Yenthe,

Thx for the heads up :) 

but the amount of time i've lost with simple things like pdf creation and small things like adding http://0.0.0.0:8069 as report url, automatic updates of the underlying linux, the longpolling behind a firewall and local reverse proxying, static files not showing properly (needing url rewrites), website (and email marketing) building blocks not rendering properly in certain browsers, the note problem (that sends an email), ...the list goes on....i just "ran" through all these problems i faced on linux within the windows install and i cant believe it, it all works out of the box and i havent touched a single conf file! I'm even wondering if the worker threads are even active, but the speed is amazing, so i may not even need them. 

I"m clustering one install now with a differencing mother disk, allowing to vector this out with nearly no storage cost. If all goes well i'll be able to get something done in a single day which didnt even work after months of trial/error



is there a different dev team on the windows build?

**Comment by werkwolk** [comment] 2021-02-17 21:46
![image](https://user-images.githubusercontent.com/69362083/108271951-db55ab80-7171-11eb-8d07-4ff24585b4b0.png)

I mean..COME ON!!! doesnt that say everything?!?! :))))))))

**Comment by Yenthe666** [comment] 2021-02-18 11:16
> is there a different dev team on the windows build?
Nope and it is the exact same code/stack, just compiled and packaged. So basically that means you misconfigured stuff. We deployed Linux Odoo instances within an hour, including all related configs to be honest. Happy to hear Windows works for you though.

**Comment by werkwolk** [comment] 2021-02-18 11:48
I never doubted i misconfigured something. Hence the advantage of not needing a tutorial -> doubleclick ".exe". 
the most tilting for me was that the longpolling simply worked out of the box. to be very honest, i think odoo should advertise windows as its platform for "most users". you guys will have much less support requests ;)

**Comment by Yenthe666** [comment] 2021-02-18 15:30
We barely ever have tickets about deployments honestly :D
