### ISSUE TITLE
Sales App can not be installed :cry:

### ISSUE THREAD

**Issue by NebojsaKrtolica** [odoo/odoo#39998] opened 2019-11-07 22:04 UTC
Impacted versions:
**13.0 via docker & with demo data**
Steps to reproduce:
**Try to install sales app**

Current behavior:
**Can not install the sales app 😢** 

Expected behavior:
**The sales app is installed 🚀** 
Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/6503280/68431748-351ba780-01b3-11ea-9ffb-e4ab1b440e63.png)

**Stacktrace:**

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 753, in get
    value = self._data[field][record._ids[0]]
KeyError: 31

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 955, in __get__
    value = env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 759, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('product.product(31,).type', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1323, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1311, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 395, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 382, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-58>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 463, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 573, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 420, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 312, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 195, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 322, in init_models
    env['base'].flush()
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5343, in flush
    self.recompute()
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5744, in recompute
    process(next(iter(fields_to_compute)))
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5728, in process
    recs.mapped(field.name)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5160, in mapped
    recs = recs._mapped_func(operator.itemgetter(name))
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5119, in _mapped_func
    vals = [func(rec) for rec in self]
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5119, in <listcomp>
    vals = [func(rec) for rec in self]
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5564, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 950, in __get__
    self.compute_value(recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1060, in compute_value
    records._compute_field_value(self)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3880, in _compute_field_value
    getattr(self, field.compute)()
  File "/usr/lib/python3/dist-packages/odoo/addons/sale_timesheet/models/sale_order.py", line 188, in _compute_is_service
    so_line.is_service = so_line.product_id.type == 'service'
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 979, in __get__
    self.compute_value(recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1060, in compute_value
    records._compute_field_value(self)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3882, in _compute_field_value
    field.compute(self)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 551, in _compute_related
    record[self.name] = self._process_related(value[self.related_field.name])
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5573, in __setitem__
    return self._fields[key].__set__(self, value)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1025, in __set__
    self.write(protected_records, value)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 908, in write
    cache_value = self.convert_to_cache(value, records)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 2122, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for product.product.type: 'product'
```

**Comment by pedrobaeza** [comment] 2019-11-07 22:59
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin - `base` db)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by NebojsaKrtolica** [comment] 2019-11-08 09:24
I will see about the runbot process, but what i can say now is the following:

1. Started db and odoo via docker-compose
```
version: '2'
services:
  web:
    image: odoo:13.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data:
```

2. Then created the first admin user with **test data checkbox turned on**

3. After that i started installing some apps, and one of them was Sales, which then threw the stacktrace from the first comment.

**Comment by pedrobaeza** [comment] 2019-11-08 09:31
If not reproducible in runbot, then it's a problem of your deployment method or steps. Please check https://www.odoo.com/documentation/13.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).

**Closed by pedrobaeza** 2019-11-08 09:31 UTC
Labels: Need information

**Comment by NebojsaKrtolica** [comment] 2019-11-08 09:37
I did not say its not reproducible in runbot, I wanted to give the feedback that i do have right now **before** i even start with runbot. Big negative point for this move 😠

**Comment by pedrobaeza** [comment] 2019-11-08 09:49
Yeah, I'm used to negative points, but it allows to have this clearer while determining real issues. If you prove that, I will be happy to reopen.
