### ISSUE TITLE
Tax calculation incorrect for tax included in price

### ISSUE THREAD

**Issue by colml** [odoo/odoo#2594] opened 2014-09-22 06:11 UTC
Affected versions: 8.0 and presumably previous versions

Steps to reproduce:
1) Set tax calculation to round globally
![rounding](https://cloud.githubusercontent.com/assets/2428769/4352098/74cd9164-421d-11e4-9f2c-46aaa3873df8.png)

2) Add tax of 5% and included in price
![tax](https://cloud.githubusercontent.com/assets/2428769/4352082/e9277260-421c-11e4-8cab-236a3095eb89.png)

3) Create invoice of three lines, each 1.10 USD with tax. The total should be 3.30 USD. 
![invoice](https://cloud.githubusercontent.com/assets/2428769/4352123/f1ed4a4a-421d-11e4-9569-f9d92746285e.png)

The tax amount is correct, 0.16 USD in this case. The total listed of course is not correct. The base amount is calculated incorrectly as shown below:
![invoiceother](https://cloud.githubusercontent.com/assets/2428769/4352139/4524fa5a-421e-11e4-87ca-a0d152cb3fb8.png)

Adding more lines makes the calculation off even more. Other price combinations are also affected. Setting the tax rounding per line also has issues but that's for a separate bug report.

**Comment by pjmcdermott** [comment] 2015-04-03 22:16
I'm struggling with the same thing. I think the issue is the attempt to present the net of tax amount, add it up to a subtotal, and then add on the calculated tax. When rounding to 2 decimal places it is never going to be possible to do this accurately for all cases.

When you think about a receipt from a supermarket or some other place where they sell to consumers at gross (tax inclusive prices), they add up the gross amounts to present a gross total (which is the amount paid), and then add as a note that this includes tax of $x.xx.

i.e. in this case
Total = $3.30
Includes tax of $0.16

I think the behaviour of an invoice when the "tax included in price" setting is selected should be:
- Column title "Amount" should be changed to "Gross Amount"
- The number in this column is the gross extended amount i.e. quantity x unit price
- The subtotal is removed
- The total is the sum of the gross amounts
- A note is added below the total of the included tax amount

A sales order should have similar functionality.

Given that many (all?) EU jurisdictions require that prices are shown to consumer customers as tax inclusive prices, I am wondering how the new e-commerce functionality in Odoo is handling this, without getting a mismatch between the prices displayed to customers in the webstore and the totals on the invoices.

**Comment by ApisNatura** [comment] 2015-09-07 15:26
It's still not fixed. We have exactly the same issue, since this, we are not able to use the Odoo's webshop. If a customer is buying 3 items each 1,1Euro including Tax, a amount of 3,31 is calculated. If the customer pays with paypal, he has to pay this wrong price. There is absolutely no discussion, that is a bug. 

Why is it not fixed yet? If you do a google search, everybody with tax included prices has the same problem.

To Odoo: Please give a statement!

**Comment by wtaferner** [comment] 2015-09-07 15:54
**Tax included should NOT be used together with round globally**...round globally was introduced by Odoo due to having the same issue for net prices with round per line...accounting is refactored in version 9 and I have not checked yet if the global setting would allow mixed usage (tax included and excluded approach in one instance) in the future.

**Solution**: Use round per line by now and hope for better solutions in the future.

By the way, did my help lately worked for you? Anyway, please be polite even if you can not believe something is still not fixed (who says that it is a bug per definition in the first place). Odoo is more or less not able to handle all the issues and Pull Requests alone, so they give higher priority to Pull Requests as it does actually contribute to the code and improves the product.

**Comment by ApisNatura** [comment] 2015-09-07 16:35
I have selected round per line, but the issue is still there. There is no difference between round per line or round globally. I have a decimal precision of 4 digits for all amount, however, the tax is always calculated only by 2 digits. I think if it was calculated by 4 digits, it would work..

**Comment by pjmcdermott** [comment] 2015-09-07 16:35
@wtaferner 

"Tax included should NOT be used together with round globally"--if this is truly correct it should not even be possible to select this combination of options--so yet another bug.

"who says that it is a bug per definition in the first place"--I'm afraid there is such a thing as an objective bug. Tax and accounting operates to rules. Any software purporting do do these things **must** follow the rules. Otherwise it's broken.

While I agree that pull requests are better, not everyone submitting a bug report is a programmer, so pull requests can't be expected. Odoo manages to find lots of time for new feature development...I think they need to provide more priority to bug fixing. Having these reported bugs provides Odoo with an enormous advantage in working out where things are going wrong...given this information, I expect them to make some use of it within a reasonable time frame....otherwise, why should people report.

Continued serious bugs in core functionality is one of the reasons I still have not been able to make the leap to Odoo for my business. As far as I know version 9 is still not released, so "accounting is re-factored in version 9" does not help

**Comment by wtaferner** [comment] 2015-09-07 18:05
@ApisNatura 
I am pretty sure that you have missed some decimal precision setting...round per line should work with tax included afaik...anyway, this is an issue which needs to be addressed some day (consistently working for all use cases), but can be solved more or less by configuration at least for most use cases already...

@pjmcdermott 
Well, you can not tell them how they are supposed to invest their time...having said that I am sorry that you were not able to make the leap to Odoo for your business. Try to take my hints for the good...as already said I doubt ranting here will improve anything on the situation.

You are welcome! At least I tried to help...

**Comment by ApisNatura** [comment] 2015-09-07 18:39
All precision settings available at the technical settings in backend, also the global journal precision, are set to 4 digits. But nowhere was a "tax precision" nor similar setting. If there is a(hidden)  setting, please tell me.
Still there is no difference between round per line or global rounding (found only one setting for this)

**Comment by wtaferner** [comment] 2015-09-08 01:53
You have probably missed the kind of hidden rounding setting on the currency itself (Rounding Factor should be 0.000100 for 4 digits accuracy).

**Comment by andycheng123** [comment] 2015-09-08 08:29
Hi All,

It bothers me so much. I’ve asked the support team and they simply refused to fix this and stated it’s not a bug…..

> On Sep 7, 2015, at 11:27 PM, ApisNatura <notifications@github.com> wrote:
> 
> It's still not fixed. We have exactly the same issue, since this, we are not able to use the Odoo's webshop. If a customer is buying 3 items each 1,1Euro including Tax, a amount of 3,31 is calculated. If the customer pays with paypal, he has to pay this wrong price. There is absolutely no discussion, that is a bug.
> 
> Why is it not fixed yet? If you do a google search, everybody with tax included prices has the same problem.
> 
> To Odoo: Please give a statement!
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/odoo/odoo/issues/2594#issuecomment-138325183>.
> 

-- 
☺
祝萬事順心
Best Regards,

鄭安迪, 多伯特系統整合有限公司
Andy Cheng, Dobtor SI Ltd.

10646 臺北市大安區羅斯福路二段79號7樓之4
7F.-4, No.79, Sec. 2, Roosevelt Rd., Da’an Dist., Taipei City 10646, Taiwan

統編 VAT# 54187967

(E): andy.cheng@dobtor.com

(O): +886-2-2362-9405, 112

(F): +886-2-2362-9410

(M): +886-933-717-714

(W): http://www.dobtor.com/

**Comment by ApisNatura** [comment] 2015-09-08 10:38
No, I've niticed the both settings available al the currency settings

When I set the price rounding factor to 0,0001, all prices visible at the invoice have a 4 digit length. But that's not useful for the customers, they need a 2 digits price (3,30 instead of 1,3000). So I set this to 0,01. The internal calculation precision is set to 4 digits, also in Database --> Decimal) All prices which are used internal by odoo, are calculated with 4 digits, except the tax. That's what the bug is about...
Normally, all internal calculations, including tax, should be based on the internal decimal precision (4 digits). When I create the Invoice, then the prices should be printed with 2 digits. This is also what I expected the price setting is about (this is why I can set the price precision with 0,01 and the calculated precision with 4 digits).

**Comment by tejastank** [comment] 2015-09-08 10:41
Look like confirmed bugs or hidden configuration issues.
https://github.com/odoo/odoo/issues/7634#issuecomment-122855362

@andycheng123 seems odoo failed for support.

We had manage by it different way which working best for us.

**Comment by andycheng123** [comment] 2015-09-08 11:04
Hi Tejas,

Would you kindly tell me what ur solution is? It would be a great help even if our environments are different.

> On Sep 8, 2015, at 6:42 PM, Mr. Tejas Tank <notifications@github.com> wrote:
> 
> Look like confirmed bugs or hidden configuration issues.
> #7634 (comment) <https://github.com/odoo/odoo/issues/7634#issuecomment-122855362>
> @andycheng123 <https://github.com/andycheng123> seems odoo failed for support.
> 
> We had manage by it different way which working best for us.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/odoo/odoo/issues/2594#issuecomment-138511357>.
> 

-- 
☺
祝萬事順心
Best Regards,

鄭安迪, 多伯特系統整合有限公司
Andy Cheng, Dobtor SI Ltd.

10646 臺北市大安區羅斯福路二段79號7樓之4
7F.-4, No.79, Sec. 2, Roosevelt Rd., Da’an Dist., Taipei City 10646, Taiwan

統編 VAT# 54187967

(E): andy.cheng@dobtor.com

(O): +886-2-2362-9405, 112

(F): +886-2-2362-9410

(M): +886-933-717-714

(W): http://www.dobtor.com/

**Comment by wtaferner** [comment] 2015-09-08 11:16
@ApisNatura 
I tested it and it totally works in terms of rounding (even if I want a 2 digits accuracy for the price and a 4 digits accuracy for the accounting and currency rounding)...but I quit this conversation as you guys don't need help...good luck ;-)

**Comment by wtaferner** [comment] 2015-09-08 11:56
Ok, guys, if you need it or not, I found a corner case myself and created a pull request (https://github.com/odoo/odoo/pull/8427) to improve the current situation...I don't know if Odoo will accept it, but maybe it might help you...

**Comment by ApisNatura** [comment] 2015-09-08 12:10
Hi.

Thanks for the pull request.
However, I made some screenshots right now for a better explenation of what I did, maybe this helps to find a possible misconfiguration I have made...

Example (all prices including tax, rounding per line):

Product 1: 6,00 Euro
Product 2: 5,25 Euro
Summary: 11,25 Euro

First example, wrong calculation:
In Backend:
![odoo_2precision_backend](https://cloud.githubusercontent.com/assets/14164797/9734369/c31aeb08-5632-11e5-9860-7b15320268b2.jpg)

In printed invoice (pdf):
![odoo_2precision](https://cloud.githubusercontent.com/assets/14164797/9734384/e88a527a-5632-11e5-9f1e-1836bb645aec.jpg)


Second example, correct calculation, but summary-price with 4 digits instead of 2..
Backend:
![odoo_4precision_backend](https://cloud.githubusercontent.com/assets/14164797/9734396/02d306e0-5633-11e5-898e-e205759584dc.jpg)

In printed invoice (pdf):
![odoo_4precision](https://cloud.githubusercontent.com/assets/14164797/9734399/09609a90-5633-11e5-80dc-2bec20b9a90c.jpg)

**Comment by wtaferner** [comment] 2015-09-08 12:24
@ApisNatura 
Well, thank you for being finally showing what you mean instead of fuzzy describing...the report is something which should be customized as the representation is wrong anyway (the sub total must be including tax)...actually I doubt that the 4 digits are needed for accounting anyway...standard use case are 2 digits and it is perfectly ok if you use two digits for the calculations...then you don't need to customize the report. But your use case does in my opinion work also work without my changes made as long you use round per line and always use unit prices including taxes and only taxes included...

**Comment by tejastank** [comment] 2015-09-08 14:22
@wtaferner I wish odoo consider your code, let's see.

**Comment by andycheng123** [comment] 2015-09-17 07:07
Sorry it’s been a while
I’ve checked your code modification. It does fix this problem in some situations, but not all. It’s a logical problem of the way Odoo calculation total and taxes related thing. Unless the base logic is fixed, the problem remains.
 
> On Sep 8, 2015, at 7:56 PM, Wolfgang Taferner <notifications@github.com> wrote:
> 
> Ok, guys, if you need it or not, I found a corner case myself and created a pull request (#8427 <https://github.com/odoo/odoo/pull/8427>) to improve the current situation...I don't know if Odoo will accept it, but maybe it might help you...
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/odoo/odoo/issues/2594#issuecomment-138531353>.
> 

-- 
☺
祝萬事順心
Best Regards,

鄭安迪, 多伯特系統整合有限公司
Andy Cheng, Dobtor SI Ltd.

10646 臺北市大安區羅斯福路二段79號7樓之4
7F.-4, No.79, Sec. 2, Roosevelt Rd., Da’an Dist., Taipei City 10646, Taiwan

統編 VAT# 54187967

(E): andy.cheng@dobtor.com

(O): +886-2-2362-9405, 112

(F): +886-2-2362-9410

(M): +886-933-717-714

(W): http://www.dobtor.com/

**Comment by wtaferner** [comment] 2015-09-17 07:26
@andycheng123 
Good that some issues are resolved by the fix which was not yet reviewed nor merged by Odoo staff. Well, if you state it is a logical issue then describe precisely what does not work for you otherwise it is just some point of view without facts even though I agree it might be difficult to configure and does not work for all use cases possible at once...I am eager to learn every angle which could lead to issues with the current code as rounding precision is important but always depends on correct application and usage.

**Comment by andycheng123** [comment] 2015-09-17 08:05
Hi Wolfgang,

I’m sorry that I didn’t describe it clearly. I appreciate a lot your modification which give me more idea about this issue. More precisely, there’s no perfect logic for this issue. Different solution works better under different situation. The problem about Odoo’s original code is that they chose a bad approach which causes problems in a lot of situations. I’ll spend some time to organise my thought and share with you. Again, Thank a lot for your sharing.

> On Sep 17, 2015, at 3:27 PM, Wolfgang Taferner <notifications@github.com> wrote:
> 
> @andycheng123 <https://github.com/andycheng123> 
> Good that some issues are resolved by the fix which was not yet reviewed nor merged by Odoo staff. Well, if you state it is a logical issue then describe precisely what does not work for you otherwise it is just some point of view without facts even though I agree it might be difficult to configure and does not work for all use cases possible at once...I am eager to learn every angle which could lead to issues with the current code as rounding precision is important but always depends on correct application and usage.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/odoo/odoo/issues/2594#issuecomment-140991259>.
> 

-- 
☺
祝萬事順心
Best Regards,

鄭安迪, 多伯特系統整合有限公司
Andy Cheng, Dobtor SI Ltd.

10646 臺北市大安區羅斯福路二段79號7樓之4
7F.-4, No.79, Sec. 2, Roosevelt Rd., Da’an Dist., Taipei City 10646, Taiwan

統編 VAT# 54187967

(E): andy.cheng@dobtor.com

(O): +886-2-2362-9405, 112

(F): +886-2-2362-9410

(M): +886-933-717-714

(W): http://www.dobtor.com/

**Comment by Yenthe666** [comment] 2016-06-10 07:54
@qdp-odoo could you look at this and give a response?

**Comment by qdp-odoo** [comment] 2016-06-10 09:09
hi there,

not sure when it has been fixed, but it has: I cannot reproduce the bug on runbot v8

![screenshot from 2016-06-10 10 15 40](https://cloud.githubusercontent.com/assets/7628598/15958236/8ff2cfac-2ef4-11e6-86a9-900047649d76.png)

Thanks for the contribution

**Closed by qdp-odoo** 2016-06-10 09:09 UTC

**Comment by wtaferner** [comment] 2016-06-10 09:12
@qdp-odoo 
Not sure if this issue was ever a bug, but I think I have found one during my efforts to support.

Maybe you could also take a look to the dedicated PR https://github.com/odoo/odoo/pull/8427?

**Comment by farhanrashad** [comment] 2016-08-16 18:57
I resolve this problem by calculating with python code

![tax-calculation](https://cloud.githubusercontent.com/assets/294660/17711931/c690e506-63c1-11e6-9e1e-69fb60acb333.jpg)
