### ISSUE TITLE
[8.0] Error when updating modules for existing DB - don't understand the error

### ISSUE THREAD

**Issue by mojowebs** [odoo/odoo#2798] opened 2014-09-30 09:58 UTC
I installed a fresh copy of 8.0 stable and loaded an RC1 database. Keep getting this error and I don't understand it:

2014-09-30 09:57:37,589 15334 ERROR app openerp.addons.base.ir.ir_ui_view: Eleme                                                                                                                                nt '<xpath expr="//t[@t-call-assets="website.assets_frontend"][@t-js]">' cannot                                                                                                                                 be located in parent view

Error context:
View `Editor`
[view_id: 263, xml_id: website.editor_head, model: n/a, parent_id: 260]
2014-09-30 09:57:37,590 15334 CRITICAL app openerp.service.server: Failed to ini                                                                                                                                tialize database `app`.
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/service/server.py", line 901, in preload_r                                                                                                                                egistries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/opt/odoo/odoo-server/openerp/modules/registry.py", line 324, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module                                                                                                                                )
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 354, in load_mod                                                                                                                                ules
    force, status, report, loaded_modules, update_module)
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 263, in load_mar                                                                                                                                ked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report                                                                                                                                , skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 182, in load_mod                                                                                                                                ule_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 118, in _load_da                                                                                                                                ta
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, r                                                                                                                                eport)
  File "/opt/odoo/odoo-server/openerp/tools/convert.py", line 899, in convert_fi                                                                                                                                le
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/odoo-server/openerp/tools/convert.py", line 985, in convert_xm                                                                                                                                l_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/odoo-server/openerp/tools/convert.py", line 851, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/opt/odoo/odoo-server/openerp/tools/convert.py", line 827, in _tag_templ                                                                                                                                ate
    return self._tag_record(cr, record, data_node)
  File "/opt/odoo/odoo-server/openerp/tools/convert.py", line 765, in _tag_recor                                                                                                                                d
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module                                                                                                                                , res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate                                                                                                                                (data_node), mode=self.mode, context=rec_context )
  File "/opt/odoo/odoo-server/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_model.py", line 1024, in                                                                                                                                 _update
    model_obj.write(cr, uid, [res_id], values, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_ui_view.py", line 282, i                                                                                                                                n write
    context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 360, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 3693, in write
    self._write(old_vals)
  File "/opt/odoo/odoo-server/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 552, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 3855, in _write
    recs._validate_fields(vals)
  File "/opt/odoo/odoo-server/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 1306, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "ValidateError
Field(s) `arch` failed against a constraint: Invalid view definition

Error details:
Element '<xpath expr="//t[@t-call-assets="website.assets_frontend"][@t-js]">' ca                                                                                                                                nnot be located in parent view

Error context:
View `Editor`
[view_id: 263, xml_id: website.editor_head, model: n/a, parent_id: 260]" while p                                                                                                                                arsing None:182, near
<data inherit_id="website.layout" name="Editor">
    <xpath expr="//t[@t-call-assets=&quot;website.assets_frontend&quot;][@t-js]"                                                                                                                                 position="after">
        <t t-call-assets="website.assets_editor" t-js="false"/>
    </xpath>
    <xpath expr="//t[@t-call-assets=&quot;website.assets_frontend&quot;][@t-css]                                                                                                                                " position="after">
        <t t-call-assets="website.assets_editor" t-css="false"/>
    </xpath>
</data>

**Comment by Yenthe666** [comment] 2016-06-03 09:55
Hi @mojowebs,
I'm closing this issue since I can no longer reproduce this.
Looks like a duplicate of https://github.com/odoo/odoo/issues/2813 too.

Regards,
Yenthe

**Closed by Yenthe666** 2016-06-03 09:55 UTC
