### ISSUE TITLE
9.0 - Pick + Ship  : don't keep information (Serial number / availabilities)

### ISSUE THREAD

**Issue by stephaniemillet** [odoo/odoo#9207] opened 2015-10-23 09:08 UTC
Pick + Ship  : don't keep Serial Numbers

When you configure
 on your warehouse
Outgoing shippings  = Pick + ship
on your picking type
pick and ship : Use existing lots

And create a sales order for stockable product with unique serial number 

It create two 'deliveries' (stock operation) document 'pick' (Stock -> Output location)  and then 'Ship' (Output-> customer location)
On first operation 'pick' (Stock -> Output location), you select the serial numbers
On second operation 'Ship' (Output-> customer location) you have to re-select the serial numbers

1 - Theses should be the SAME serial numbers.  - automatically selected .
You shouldn't be able to create and change the serial numbers between the pick and ship 
2 - if you have selected for picking type
pick and ship : Use existing lots 
Why can you create some ?

**Comment by jco-odoo** [comment] 2015-10-23 18:15
Because a many2one basically allows to create some all the time.(there is an option you can apply in the view, but it is all the time then)  With the scanner it is different.  And you can put them in a pack to avoid scanning them at each step.

**Comment by stephaniemillet** [comment] 2015-11-26 17:59
Other case – not working for Pick & Ship

If we have to force availability on a picking,

(for instance if a product is configured ‘MTO’ and finally you delete PR because you have enough stock),

and everything is validate and available in location ‘output’

in second transfer / delivery order :  Output -> ‘Customer -> we have to force availability AGAIN !

**Comment by jco-odoo** [comment] 2015-11-26 18:08
If it is really like that, it is a bug because it should automatically be
reserved in that case.

**Comment by pedrobaeza** [comment] 2018-04-06 00:35
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-04-06 00:35 UTC
Labels: 9.0, Logistics
