### ISSUE TITLE
Matching sale order line uom with product uom not possible

### ISSUE THREAD

**Issue by enclustra-odoo** [odoo/odoo#47337] opened 2020-03-11 06:26 UTC
Impacted versions:
12

Steps to reproduce:

1. Create sale order with an order line where the product unit of measure is in _Unit(s)_

1. Change unit of measure on product from _Unit(s)_ to _Hour(s)_

1. Try to correct the unit of measure in the sale order line from _Unit(s)_ to _Hour(s)_

Current behavior:

- User error is raised when any sale order line is changed. Even if the unit of measure mismatch is corrected (https://github.com/odoo/odoo/blob/054d4bc6bc219bcc6b0a64265e8d7e9c7423dbc8/addons/uom/models/uom_uom.py#L148)
- There is no other workaround than deleting the sale order or deleting the sale order line with SQL in the database
- Probably this compute function leads to errors: https://github.com/odoo/odoo/blob/054d4bc6bc219bcc6b0a64265e8d7e9c7423dbc8/addons/uom/models/uom_uom.py#L135

Expected behavior:
- User error should only be raised when saving (write to DB) the sale order and not onchange

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2020-03-11 09:49
How can you change the product UoM? That's forbidden by default.

Any way, the problem is that you can't change a UoM once you have used the product. You must create another one instead, so closing because of that. You can post another issue about the fact that you get to change the UoM of the product.

**Closed by pedrobaeza** 2020-03-11 09:49 UTC

**Comment by enclustra-odoo** [comment] 2020-03-11 11:27
The product has not been used yet. The following happened:

1. The user created a sale order,

1. inserted a sale order line with a product,

1. changed the product unit of measure,

1. went back to the sale order and now nothing could be changed in the sale order lines. Not even the uom mismatch could be corrected.

Only workaround is to delete the whole sale order or delete the lines in the database. These workarounds are not acceptable.

**Comment by pedrobaeza** [comment] 2020-03-11 11:29
Yes, you have to remove the sales order line before changing the UoM. That's not the workaround. It's what you have to do.

**Comment by Yenthe666** [comment] 2020-03-11 12:04
Yep, this is by design and it is not a bug.

**Comment by seancallahan88** [comment] 2022-01-04 23:12
I can't get into the transfer list because of this error. How are we supposed to fix this after an upgrade? Seemingly no way to know which product or transfer (or the reason for the UOM change) - its not listed in the log.

`odoo.http: The unit of measure Unit(s) defined on the order line doesn't belong to the same category as the unit of measure m defined on the product. Please correct the unit of measure defined on the order line or on the product, they should belong to the same category.`

**Comment by euroblaze** [comment] 2023-07-30 13:27
> Yep, this is by design and it is not a bug.

To the end-user, this is anything but intuitive!
