### ISSUE TITLE
[11] Inventory Valuation report fails with shared locations

### ISSUE THREAD

**Issue by arveitch** [odoo/odoo#28385] opened 2018-11-05 08:35 UTC
Impacted versions: 11

Steps to reproduce: Create a Stock Location with the Company not set. Put Stock into that Location. run Inventory Valuation Report.

Current behavior: Stock in a Location that is not owned by a company is not shown on the Inventory Valuation Report. In our case the report is completely blank as we have a warehouse shared between three companies with none of the stock locations owned.

Expected behavior: The Inventory Valuation Report should show Stock based on ownership of the Stock Quant. It should not decide ownership based on the ownership of the Stock Location.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2018-11-05 08:40
You should create different locations per company, as you can't share your stock that way. Conceptually and logically in the ERP there should be a transfer from one company to other when the non owning company requires that stock.

Closing as misuse of the location system.

**Comment by arveitch** [comment] 2018-11-05 08:41
I think the problem is here:
https://github.com/odoo/odoo/blob/11.0/addons/stock_account/views/product_views.xml#L98

**Closed by pedrobaeza** 2018-11-05 08:40 UTC

**Comment by arveitch** [comment] 2018-11-05 08:44
We have a shared physical warehouse with three independent companies. Company A might put stock in location A1 and then move it later in the week. Company B might then use that same location.

There is now transfer of stock between the companies. They are just sharing the same physical location.

If sharing a stock location is not supported then it should be compulsory to set the company on a stock location instead of having it as an optional field.

**Comment by pedrobaeza** [comment] 2018-11-05 08:46
Virtual locations can be shared, but not physical locations. If you want to make a PR for adding that constraint, you are invited to do it for improving that part.

**Comment by arveitch** [comment] 2018-11-05 10:04
We have been using Odoo for a long time with shared locations. So I guess the choices are:

1. Change the warehouse process so they have specific physical location for each company. This would be very wasteful of time and space.
2. Create each warehouse physical location three times in Odoo, once for each company. This would result in many thousands of extra locations which isn't very easy to manage.
3. Continue with locations shared between companies and create a custom version of the Inventory Valuation report with a different context.

I think for us we'll just go with option 3. Every other part of Odoo seems to work fine with shared physical locations.

**Comment by pedrobaeza** [comment] 2018-11-05 10:07
OK, the problem is that you drag the wrong initial design decision. Doing 1 or 2 would be the proper way to fix it. If not, you would resolve now in custom this specific problem, but as everything is designed for the other concept, you might find other problems in the future.
