### ISSUE TITLE
[11.0] Could not Add/Copy and Remove POS table

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#25281] opened 2018-06-16 08:33 UTC
Impacted versions: 11.0
Performed on Runbot @ [http://338925-11-0-c53b0a.runbot17.odoo.com/pos/web/](http://338925-11-0-c53b0a.runbot17.odoo.com/pos/web/)

Steps to reproduce: Login to Pos --> Edit Floor Plan --> Add new Table/Select and Copy Table --> Remove New Created Table
![pos1](https://user-images.githubusercontent.com/16624719/41497169-a6b6b4de-716d-11e8-909b-f95a937626b5.png)
![pos2](https://user-images.githubusercontent.com/16624719/41497170-a9324764-716d-11e8-8aed-0d0f6602b608.png)
![pos3](https://user-images.githubusercontent.com/16624719/41497171-aa6dde40-716d-11e8-8556-d1f4c8a36e12.png)

Current behavior:

> Server application error {"code":200,"message":"Odoo Server Error","data":{"name":"odoo.exceptions.ValidationError","debug":"Traceback (most recent call last):\n  File \"/home/odoo/runbot/runbot/runbot/static/build/338925-11-0-c53b0a/odoo/service/model.py\", line 97, in wrapper\n    return f(dbname, *args, **kwargs)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/338925-11-0-c53b0a/odoo/http.py\", line 335, in checked_call\n    result = self.endpoint(*a, **kw)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/338925-11-0-c53b0a/odoo/http.py\", line 936, in __call__\n    return self.method(*args, **kw)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/338925-11-0-c53b0a/odoo/http.py\", line 515, in response_wrap\n    response = f(*args, **kw)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/338925-11-0-c53b0a/odoo/addons/web/controllers/main.py\", line 931, in call_kw\n    return self._call_kw(model, method, args, kwargs)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/338925-11-0-c53b0a/odoo/addons/web/controllers/main.py\", line 923, in _call_kw\n    return call_kw(request.env[model], method, args, kwargs)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/338925-11-0-c53b0a/odoo/api.py\", line 687, in call_kw\n    return call_kw_model(method, model, args, kwargs)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/338925-11-0-c53b0a/odoo/api.py\", line 672, in call_kw_model\n    result = method(recs, *args, **kwargs)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/338925-11-0-c53b0a/odoo/addons/pos_restaurant/models/pos_restaurant.py\", line 50, in create_from_ui\n    table_id = self.create(table).id\n  File \"/home/odoo/runbot/runbot/runbot/static/build/338925-11-0-c53b0a/odoo/models.py\", line 3373, in create\n    record = self.browse(self._create(old_vals))\n  File \"/home/odoo/runbot/runbot/runbot/static/build/338925-11-0-c53b0a/odoo/models.py\", line 3466, in _create\n    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))\n  File \"/home/odoo/runbot/runbot/runbot/static/build/338925-11-0-c53b0a/odoo/sql_db.py\", line 155, in wrapper\n    return f(self, *args, **kwargs)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/338925-11-0-c53b0a/odoo/sql_db.py\", line 232, in execute\n    res = self._obj.execute(query, params)\npsycopg2.IntegrityError: null value in column \"name\" violates not-null constraint\nDETAIL:  Failing row contains (44, null, null, square, 10, 10, 50, 50, 1, null, f, 1, 2018-06-16 08:22:09.397209, 1, 2018-06-16 08:22:09.397209).\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/odoo/runbot/runbot/runbot/static/build/338925-11-0-c53b0a/odoo/http.py\", line 650, in _handle_exception\n    return super(JsonRequest, self)._handle_exception(exception)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/338925-11-0-c53b0a/odoo/http.py\", line 310, in _handle_exception\n    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])\n  File \"/home/odoo/runbot/runbot/runbot/static/build/338925-11-0-c53b0a/odoo/tools/pycompat.py\", line 87, in reraise\n    raise value\n  File \"/home/odoo/runbot/runbot/runbot/static/build/338925-11-0-c53b0a/odoo/http.py\", line 692, in dispatch\n    result = self._call_function(**self.params)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/338925-11-0-c53b0a/odoo/http.py\", line 342, in _call_function\n    return checked_call(self.db, *args, **kwargs)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/338925-11-0-c53b0a/odoo/service/model.py\", line 139, in wrapper\n    raise ValidationError(msg)\nodoo.exceptions.ValidationError: ('The operation cannot be completed, probably due to the following:\\n- deletion: you may be trying to delete a record while other records still reference it\\n- creation/update: a mandatory field is not correctly set\\n\\n[object with reference: name - name]', None)\n","message":"The operation cannot be completed, probably due to the following:\n- deletion: you may be trying to delete a record while other records still reference it\n- creation/update: a mandatory field is not correctly set\n\n[object with reference: name - name]\nNone","arguments":["The operation cannot be completed, probably due to the following:\n- deletion: you may be trying to delete a record while other records still reference it\n- creation/update: a mandatory field is not correctly set\n\n[object with reference: name - name]",null],"exception_type":"validation_error"}}

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment] 2018-06-27 08:21
@pimodoo can you check please?

**Comment by switch87** [comment] 2018-10-25 19:51
Closed by  #27924

**Closed by switch87** 2018-10-25 19:51 UTC
Labels: 11.0, Confirmed, Point of Sale

**Comment by sswapnesh** [comment] 2018-10-26 19:58
@switch87 
I am able to Reproduce this on latest v12 (http://390664-12-0-40c6bc.runbot13.odoo.com/pos/web/#action=pos.ui)

![screenshot 60](https://user-images.githubusercontent.com/16624719/47589699-8d588080-d987-11e8-80f1-9c7f6210c06c.png)

**Comment by sswapnesh** [comment] 2018-12-18 19:38
Hello @switch87 
 Still same issue in v12 (http://416077-27766-4aa538.runbot14.odoo.com)
![screenshot from 2018-12-19 01-06-37](https://user-images.githubusercontent.com/16624719/50178429-7ea89d00-032a-11e9-9d1f-bf3408d71f3f.png)

**Comment by switch87** [comment] 2018-12-18 20:52
@sswapnesh did you do some configuration changes on this runbot? I can confirm the error on the runbot you send but not on runbot I open myself

**Comment by sswapnesh** [comment] 2018-12-19 01:21
No, I didn't any

**Comment by switch87** [comment] 2018-12-19 09:54
I see your test is done one runbot 27766 and not on 12.0. 27766 is yours so probably you do not have the fix in it? On runbot 12.0 the issue is solved.
