### ISSUE TITLE
[10.0] Babel Locale Failure in Resource Tests

### ISSUE THREAD

**Issue by anassahmed** [odoo/odoo#21747] opened 2017-12-20 05:17 UTC
**Impacted versions:**

- 10.0

**Steps to reproduce:**

- Unset all locale system environment variables (if you're not using `docker` image):
  ```bash
  unset LANG LC_ALL LC_TIME LANGUAGE LC_CTYPE LC_MESSAGES
  ```
- Run `odoo-bin` (or in my case `docker run odoo`) with the options: `-d <db_name> -i resource --test-enable`

**Current behavior:**

Tests fail at `_make_attendance` method because babel `Locale.parse()` doesn't get a locale passed to it and looks like it doesn't have a default one.

- proposed solution: I passed the `lang` key of the current user `self.env.user.lang` and it successfully passed. so you may add something like:
  ```python
  locale = self.env.user.lang or 'en_US'
  day_name = babel.dates.get_day_names(locale=locale)[weekday]
  ```

- Note: using `LANG = C.UTF-8` doesn't help either, it should be a true locale like `en_US.UTF-8`.

**Expected behavior:**

Tests pass.

**Error logs:**

```
2017-12-20 04:55:54,186 1 ERROR babel odoo.addons.resource.tests.test_resource: ERROR                                                                
2017-12-20 04:55:54,188 1 INFO babel odoo.addons.resource.tests.test_resource: ======================================================================                                                 
2017-12-20 04:55:54,188 1 ERROR babel odoo.addons.resource.tests.test_resource: ERROR: test_global_leaves (odoo.addons.resource.tests.test_resource.TestWorkDays)
2017-12-20 04:55:54,188 1 ERROR babel odoo.addons.resource.tests.test_resource: Traceback (most recent call last):     
2017-12-20 04:55:54,188 1 ERROR babel odoo.addons.resource.tests.test_resource: `   File "/usr/lib/python2.7/dist-packages/odoo/addons/resource/tests/test_resource.py", line 535, in setUp
2017-12-20 04:55:54,188 1 ERROR babel odoo.addons.resource.tests.test_resource: `     for i in range(5)                                                            
2017-12-20 04:55:54,188 1 ERROR babel odoo.addons.resource.tests.test_resource: `   File "/usr/lib/python2.7/dist-packages/odoo/addons/resource/tests/test_resource.py", line 520, in _make_attendance
2017-12-20 04:55:54,189 1 ERROR babel odoo.addons.resource.tests.test_resource: `     data = {                                                                
2017-12-20 04:55:54,189 1 ERROR babel odoo.addons.resource.tests.test_resource: `   File "/usr/lib/python2.7/dist-packages/babel/dates.py", line 178, in get_day_names                     
2017-12-20 04:55:54,189 1 ERROR babel odoo.addons.resource.tests.test_resource: `     return Locale.parse(locale).days[context][width]                                   
2017-12-20 04:55:54,189 1 ERROR babel odoo.addons.resource.tests.test_resource: ` AttributeError: 'NoneType' object has no attribute 'days'                                                           
2017-12-20 04:55:54,189 1 INFO babel odoo.addons.resource.tests.test_resource: ======================================================================                                        
2017-12-20 04:55:54,189 1 ERROR babel odoo.addons.resource.tests.test_resource: ERROR: test_mixed_leaves (odoo.addons.resource.tests.test_resource.TestWorkDays)                                                                              
2017-12-20 04:55:54,189 1 ERROR babel odoo.addons.resource.tests.test_resource: Traceback (most recent call last):                                                                                                                             
2017-12-20 04:55:54,190 1 ERROR babel odoo.addons.resource.tests.test_resource: `   File "/usr/lib/python2.7/dist-packages/odoo/addons/resource/tests/test_resource.py", line 535, in setUp
2017-12-20 04:55:54,190 1 ERROR babel odoo.addons.resource.tests.test_resource: `     for i in range(5)                                                                                               
2017-12-20 04:55:54,190 1 ERROR babel odoo.addons.resource.tests.test_resource: `   File "/usr/lib/python2.7/dist-packages/odoo/addons/resource/tests/test_resource.py", line 520, in _make_attendance                                        
2017-12-20 04:55:54,190 1 ERROR babel odoo.addons.resource.tests.test_resource: `     data = {                                                                                                                                                 
2017-12-20 04:55:54,190 1 ERROR babel odoo.addons.resource.tests.test_resource: `   File "/usr/lib/python2.7/dist-packages/babel/dates.py", line 178, in get_day_names                                                                         
2017-12-20 04:55:54,190 1 ERROR babel odoo.addons.resource.tests.test_resource: `     return Locale.parse(locale).days[context][width]                                                                                                         
2017-12-20 04:55:54,190 1 ERROR babel odoo.addons.resource.tests.test_resource: ` AttributeError: 'NoneType' object has no attribute 'days'
2017-12-20 04:55:54,190 1 INFO babel odoo.addons.resource.tests.test_resource: ======================================================================                                                                                          
2017-12-20 04:55:54,191 1 ERROR babel odoo.addons.resource.tests.test_resource: ERROR: test_no_calendar (odoo.addons.resource.tests.test_resource.TestWorkDays)                            
2017-12-20 04:55:54,191 1 ERROR babel odoo.addons.resource.tests.test_resource: ` If a resource has no resource calendar, they don't work                          
2017-12-20 04:55:54,191 1 ERROR babel odoo.addons.resource.tests.test_resource: Traceback (most recent call last):
2017-12-20 04:55:54,191 1 ERROR babel odoo.addons.resource.tests.test_resource: `   File "/usr/lib/python2.7/dist-packages/odoo/addons/resource/tests/test_resource.py", line 535, in setUp
2017-12-20 04:55:54,191 1 ERROR babel odoo.addons.resource.tests.test_resource: `     for i in range(5)
2017-12-20 04:55:54,191 1 ERROR babel odoo.addons.resource.tests.test_resource: `   File "/usr/lib/python2.7/dist-packages/odoo/addons/resource/tests/test_resource.py", line 520, in _make_attendance
2017-12-20 04:55:54,191 1 ERROR babel odoo.addons.resource.tests.test_resource: `     data = {
2017-12-20 04:55:54,191 1 ERROR babel odoo.addons.resource.tests.test_resource: `   File "/usr/lib/python2.7/dist-packages/babel/dates.py", line 178, in get_day_names
2017-12-20 04:55:54,191 1 ERROR babel odoo.addons.resource.tests.test_resource: `     return Locale.parse(locale).days[context][width]
2017-12-20 04:55:54,192 1 ERROR babel odoo.addons.resource.tests.test_resource: ` AttributeError: 'NoneType' object has no attribute 'days'
2017-12-20 04:55:54,192 1 INFO babel odoo.addons.resource.tests.test_resource: ======================================================================
2017-12-20 04:55:54,192 1 ERROR babel odoo.addons.resource.tests.test_resource: ERROR: test_personal_leaves (odoo.addons.resource.tests.test_resource.TestWorkDays)
2017-12-20 04:55:54,192 1 ERROR babel odoo.addons.resource.tests.test_resource: ` Leaves with a resource_id apply only to that resource
2017-12-20 04:55:54,192 1 ERROR babel odoo.addons.resource.tests.test_resource: Traceback (most recent call last):
2017-12-20 04:55:54,192 1 ERROR babel odoo.addons.resource.tests.test_resource: `   File "/usr/lib/python2.7/dist-packages/odoo/addons/resource/tests/test_resource.py", line 535, in setUp
2017-12-20 04:55:54,192 1 ERROR babel odoo.addons.resource.tests.test_resource: `     for i in range(5)
2017-12-20 04:55:54,193 1 ERROR babel odoo.addons.resource.tests.test_resource: `   File "/usr/lib/python2.7/dist-packages/odoo/addons/resource/tests/test_resource.py", line 520, in _make_attendance
2017-12-20 04:55:54,193 1 ERROR babel odoo.addons.resource.tests.test_resource: `     data = {
2017-12-20 04:55:54,193 1 ERROR babel odoo.addons.resource.tests.test_resource: `   File "/usr/lib/python2.7/dist-packages/babel/dates.py", line 178, in get_day_names
2017-12-20 04:55:54,193 1 ERROR babel odoo.addons.resource.tests.test_resource: `     return Locale.parse(locale).days[context][width]
2017-12-20 04:55:54,193 1 ERROR babel odoo.addons.resource.tests.test_resource: ` AttributeError: 'NoneType' object has no attribute 'days'
2017-12-20 04:55:54,193 1 INFO babel odoo.addons.resource.tests.test_resource: ======================================================================
2017-12-20 04:55:54,194 1 ERROR babel odoo.addons.resource.tests.test_resource: ERROR: test_trivial_calendar_no_leaves (odoo.addons.resource.tests.test_resource.TestWorkDays)
2017-12-20 04:55:54,194 1 ERROR babel odoo.addons.resource.tests.test_resource: ` If leaves are not involved, only calendar attendances (basic company configuration) are taken in account
2017-12-20 04:55:54,194 1 ERROR babel odoo.addons.resource.tests.test_resource: Traceback (most recent call last):
2017-12-20 04:55:54,194 1 ERROR babel odoo.addons.resource.tests.test_resource: `   File "/usr/lib/python2.7/dist-packages/odoo/addons/resource/tests/test_resource.py", line 535, in setUp
2017-12-20 04:55:54,194 1 ERROR babel odoo.addons.resource.tests.test_resource: `     for i in range(5)
2017-12-20 04:55:54,194 1 ERROR babel odoo.addons.resource.tests.test_resource: `   File "/usr/lib/python2.7/dist-packages/odoo/addons/resource/tests/test_resource.py", line 520, in _make_attendance
2017-12-20 04:55:54,194 1 ERROR babel odoo.addons.resource.tests.test_resource: `     data = {
2017-12-20 04:55:54,194 1 ERROR babel odoo.addons.resource.tests.test_resource: `   File "/usr/lib/python2.7/dist-packages/babel/dates.py", line 178, in get_day_names
2017-12-20 04:55:54,195 1 ERROR babel odoo.addons.resource.tests.test_resource: `     return Locale.parse(locale).days[context][width]
2017-12-20 04:55:54,195 1 ERROR babel odoo.addons.resource.tests.test_resource: ` AttributeError: 'NoneType' object has no attribute 'days'
2017-12-20 04:55:54,195 1 INFO babel odoo.addons.resource.tests.test_resource: Ran 16 tests in 601.215s
2017-12-20 04:55:54,195 1 ERROR babel odoo.addons.resource.tests.test_resource: FAILED
2017-12-20 04:55:54,195 1 INFO babel odoo.addons.resource.tests.test_resource:  (errors=5)
2017-12-20 04:55:54,195 1 INFO babel odoo.modules.module: odoo.addons.resource.tests.test_resource tested in 601.22s, 753 queries
2017-12-20 04:55:54,195 1 ERROR babel odoo.modules.module: Module resource: 0 failures, 5 errors
```

**Comment by Yenthe666** [comment] 2017-12-20 07:16
@anassahmed I'm not sure why you would ever want to unset all locales manually though.. That really sounds counterproductive and onlogical to do. You know that removing locales breaks things, that is for more systems than Odoo only. @mart-e final call is for you.

**Comment by mart-e** [comment] 2017-12-20 09:41
Hello,

I do not consider the failing tests in a specific environment as a bug, the point is not to have tests that work on all systems/configurations but to cover the most scenarios.
This error does not show a weakness in the addons but a test not properly formatted.

I can accept a PR improving the test as you suggest but close this report as not a bug.

If you find the same code in the code of the addons, it can be considered as a bug though.

**Closed by mart-e** 2017-12-20 09:41 UTC
Labels: 10.0

**Comment by anassahmed** [comment] 2017-12-20 14:34
@mart-e I opened it here because the first thought for me was it's a bug in the tests, but I'm confused if it should be a bug in the docker image then?!

@Yenthe666 Well, I'm trying to mimic the docker image environment which doesn't have any locale except the `C.UTF-8` one, which obviously fails the test because there's no `LC_TIME` for `C.UTF-8`.

Going forward, Should I fix it by installing a proper locale in the docker image and sending a pull request to the [odoo/docker](https://github.com/odoo/docker) repository, or fixing the test here with that proposed solution and sending it as a PR?

**Comment by mart-e** [comment] 2017-12-20 14:37
@anassahmed probably both :) Could you check if you have the issue in 11.0 with docker? I think the locale was set there.

**Comment by anassahmed** [comment] 2017-12-20 14:50
@mart-e The locale was set there but to `C.UTF-8` as of [this commit](https://github.com/odoo/docker/commit/16d5988408434e4678f3bf6318aabad542dec4ee). I tried that on `10.0` and it didn't work.

I'll see what I can do.
