### ISSUE TITLE
Browser get stucked

### ISSUE THREAD

**Issue by chalupka95** [odoo/odoo#34495] opened 2019-07-01 14:26 UTC
Impacted versions: Odoo12. before i dont know

Steps to reproduce: 
Menü > Leaves > take leave from x to y (eg. 3.Jan2019 to 8.Jan2019) > save it. > 
Menü > Leaves > take leave from 1 before x to one after y  (eg. 1.Jan2019 to 10.Jan2019) > save it. 

Current behavior: Browser get stucked till refreshing the page

Expected behavior: functionality? ;)

Video/Screenshot link (optional): Screenshots (2 pcs)
![screenshot1](https://user-images.githubusercontent.com/50046445/60444111-d3539b80-9c1c-11e9-87dc-949275a2f43c.PNG)
![screenshot2](https://user-images.githubusercontent.com/50046445/60444113-d3ec3200-9c1c-11e9-9165-5bd9c61a8332.PNG)

**Comment by pedrobaeza** [comment] 2019-07-01 14:27
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by chalupka95** [comment] 2019-07-01 14:43
i dont know runbot infrastructure.
i have a centos server and a new created database.
this bug is out of the box. 
i also havent modified the configuration-file yet.

**Comment by pedrobaeza** [comment] 2019-07-01 14:50
I have already given you how to access to runbot, so please try there.

**Comment by chalupka95** [comment] 2019-07-01 15:25
No. sry im not able to do that because i dont understand the website following your link.

What is this? 
And where can i login with admin admin?
Your description is not very good for me 😅

You can try to reproduce it by yourself. Its very easy follow my steps

**Comment by pedrobaeza** [comment] 2019-07-01 15:34
You have to open the link, click on the blue button for the version you have to try.

> You can try to reproduce it by yourself. Its very easy follow my steps

Sorry, but this is not how it goes. If you prove there's a problem (which I'm not sure right now), then this might be fixed for you, but with no effort, there's no prize.

**Comment by nigchicker** [comment] 2019-07-11 14:29
@pedrobaeza he just draw you attention for a bug and you want that he solve it by himself? 
I don't think thats very professional. The company should check the bug, not the customer.

**Comment by pedrobaeza** [comment] 2019-07-11 14:36
Well, I'm not asking to solve the problem by himself, just that he proves that there's a problem, with reproducible steps to be able to see it and fix it. That's the minimum to ask, and more being all of this for free (including my time as community volunteer). If you are paying Odoo S.A. an enterprise contract, then put an OPW ticket at odoo.com/help and be sure a paid employee will check this with more diligence than me, but even in that case, if not possible to reproduce the problem, it's not possible to fix anything by them.

**Comment by Yenthe666** [comment] 2019-07-31 14:45
I agree with Pedro plus I tested it but it is not reproducable. You'll even get a warning that two overlaps are not allowed.
I'm closing this bug report as there has been no more feedback on the last question and as we assume that the problem has been solved in the meanwhile. If this is not the case then don't hesitate to respond back (with feedback) and we'll reopen it.

Regards,
Yenthe

**Closed by Yenthe666** 2019-07-31 14:45 UTC
Labels: Need information
