### ISSUE TITLE
No fields shown in developer tools Show fields when product_dimension module installed

### ISSUE THREAD

**Issue by kowal119** [odoo/odoo#15655] opened 2017-02-27 11:03 UTC
Impacted versions:
9.0
Steps to reproduce:
In developer mode. Click Inventory. In top menu Inventory Control -> Products. Then in developer tools Action -> View fields. It happens when 'product_dimension module' installed (it adds to product additional fields like length,width, height etc). I investigated this issue and it's because in 'fields' object  there is key 'length', which leads to error in qweb2.js line 141. This dict is recognized as array because of having property length, which leads to bad handling it in 'foreach' method. I suggest checking in this line if Array.isArray(enu), which will fix this issue.
Current behavior:
No fields shown
Expected behavior:
Showing fields

**Comment by Yenthe666** [comment] 2017-02-28 07:35
Hi @kowal119,

Thank you for your report.
The module `product_dimension` you're talking about is however a custom build module I assume? (I believe it is this one https://www.odoo.com/apps/modules/10.0/wk_product_dimensions/).
Since this is not an official module and it is in a custom developed module this would normally mean closing the issue. However, perhaps we can improve this for later on if we would ever run into this.
@mart-e and @sle-odoo what do you think?

Regards,
Yenthe

**Comment by CGenie** [comment] 2017-02-28 07:45
Hi @Yenthe666,

Issue here is not in using `product_dimension` or any other module. This is obviously a type error -- you're checking length of an object which doesn't make sense and prevents possibility of adding a field named `length`. One way to fix this is to check whether an object is an array first, as suggested by @kowal119 . Another is to investigate this even deeper and see why an array is expected there, when an object comes in.
I don't think that closing this issue solves the problem though 😛 

Cheers,
Przemek

**Comment by CGenie** [comment] 2017-02-28 07:47
BTW, even not taking this error into account -- if there is always an object, that `if x.length` code is simply dead and does nothing :)

**Comment by kowal119** [comment] 2017-02-28 07:52
I'm using this module https://www.odoo.com/apps/modules/9.0/product_dimension/ , which is maintained by OCA.

**Comment by mart-e** [comment] 2017-02-28 08:00
> which leads to error in qweb2.js line 141. 

Please do no assume line numbers as a good indication, it change and today there is nothing [at the given line](https://github.com/odoo/odoo/blob/e0392500dc0ba5bd3558575ba0c0eb6977179dad/addons/web/static/lib/qweb/qweb2.js#L141).
So my first answer will be : try updating your code.

Also, yes product_dimension is not an official module so we do not support it.

However, what you may want to say is that product_dimension is jsut an easy way to reveal a bug in the ORM.
For the sake of testing, I tried installing the module and reproduced the given step, I got no error.

- check you are up to date
- ideally give a way to  reproduce on a standard odoo
- give the full traceback if you have an erro

**Comment by kowal119** [comment] 2017-02-28 08:13
https://github.com/odoo/odoo/blob/e0392500dc0ba5bd3558575ba0c0eb6977179dad/addons/web/static/lib/qweb/qweb2.js#L154 Sorry, that's where it is. There's no traceback, it fails silently returning empty template  (it doesn't do proper iteration through fields).

**Comment by mart-e** [comment] 2017-02-28 08:16
Thanks, I can not reproduce the bug (probably dependant of other factors) but it is obviously a wrong condition. Will fix it soon.

**Closed** 2017-02-28 12:08 UTC

**Comment by amigrave** [comment] 2017-02-28 12:12
@kowal119: Thanks for reporting. The object detection conditional was indeed awkward. I could reproduce the problem by adding a "length" field in any model and use the View Fields debugging option to see that the rendering was empty. The issue is now fixed in 10.0 and forward ported to master.

**Comment by CGenie** [comment] 2017-03-06 07:52
@mart-e Proposing a patch requires signing a contribution agreement with odoo, I did send it long time ago by email and it was never accepted :)

**Comment by mart-e** [comment] 2017-03-06 08:06
@CGenie you can sign the CLA by a simple pull request. To which contact did you sent the signature? It is not usual to use emails for the CLA signatures but have accepted a few in the past so I guess it got lost.

**Comment by CGenie** [comment] 2017-03-07 07:22
I sent it to cla@odoo-community.org on 27th Jul 2016.

**Comment by mart-e** [comment] 2017-03-07 12:25
@CGenie ok it makes sense we did not get it as it is not us :)
You are probably talking about the OCA CLA, not Odoo SA.
Please read https://odoo.com/sign-cla to see how you can sign our CLA

**Comment by CGenie** [comment] 2017-10-20 09:14
@amigrave The patch you proposed is merged to 10.0 but not to 9.0. Could you backport it? The 9.0 version is still officially supported and the bug was described first in 9.0.
We have a module that patches it but I'd prefer to have upstream code that works :)

**Comment by amigrave** [comment] 2017-10-20 12:13
Thanks @KangOl  !
