### ISSUE TITLE
TypeError: <builder: '/project/rating'>() argument after * * must be a mapping, not list

### ISSUE THREAD

**Issue by deepdad** [odoo/odoo#47356] opened 2020-03-11 09:58 UTC
Impacted versions:
13.0

Steps to reproduce:
Multi-website. Try to change the URL for the homepage (or probably other URL's as well).

Current behavior:
TypeError: <builder: '/project/rating'>() argument after * * must be a mapping, not list

Expected behavior:
No error

Video/Screenshot link (optional):
<img width="763" alt="Screenshot 2020-03-11 at 10 58 00" src="https://user-images.githubusercontent.com/22483621/76404726-3c340b80-6387-11ea-8a71-8a14b79c3e78.png">

**Comment by pedrobaeza** [comment] 2020-03-11 10:14
How do you change URL?

**Comment by deepdad** [comment] 2020-03-11 12:26
Sign In > Log In ? Website > Goto Website > Edit > click on menu link > Edit the Menu > click on the pencil to the right of Home > start typing: error pops up

**Comment by deepdad** [comment] 2020-03-11 12:28
This is the docker Odoo 13 20200121 (CE)

**Comment by pedrobaeza** [comment] 2020-03-11 12:31
Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by deepdad** [comment] 2020-03-11 12:53
on runbot there is no error... http://1713639-13-0-6ebcc4.runbot39.odoo.com/?fw=1# it seems (it is slow so I can't do a lot of different similar things)
<img width="1168" alt="Screenshot 2020-03-11 at 13 51 07" src="https://user-images.githubusercontent.com/22483621/76418830-9e990600-639f-11ea-9b7a-a5de6d5a539f.png">


I have installed few modules, and turned on Multiple Websites. It may be related to configuration of course.

Here is something from the docker log: at least it seems to start a request for /s too early ?

**Comment by pedrobaeza** [comment] 2020-03-11 12:56
I don't think so, but unless you are able to reproduce it on runbot, here we can't assist you more. Try on forums.

**Comment by deepdad** [comment] 2020-03-11 12:57
This is a bug. You should not close it.

**Closed by pedrobaeza** 2020-03-11 12:56 UTC
Labels: Need information

**Comment by Yenthe666** [comment] 2020-03-11 13:10
@deepdad We need reproducible steps on a runbot instance to verify that the bug is still present.  I just tested this on the latest 13.0 and it works fine there out of the box.

**Comment by kurenai-ryu** [comment] 2020-03-29 17:54
https://github.com/odoo/docker/issues/299#issue-565226011
