### ISSUE TITLE
Error when opening Accounting

### ISSUE THREAD

**Issue by CometSL9** [odoo/odoo#59347] opened 2020-10-07 08:32 UTC
Impacted versions:
Odoo 14.0-20201006 (Community Edition)

Steps to reproduce:
Click on Main Menu->Accounting

Current behavior:
Error Message (see below).

Expected behavior:
Correct Window should appear.

Video/Screenshot link (optional):

Error Message:
Fehler:
Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files\Odoo 14.0.20201006\server\odoo\addons\base\models\ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "C:\Program Files\Odoo 14.0.20201006\server\odoo\http.py", line 682, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files\Odoo 14.0.20201006\server\odoo\http.py", line 358, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files\Odoo 14.0.20201006\server\odoo\service\model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files\Odoo 14.0.20201006\server\odoo\http.py", line 346, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files\Odoo 14.0.20201006\server\odoo\http.py", line 911, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files\Odoo 14.0.20201006\server\odoo\http.py", line 530, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files\Odoo 14.0.20201006\server\odoo\addons\web\controllers\main.py", line 1359, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "C:\Program Files\Odoo 14.0.20201006\server\odoo\addons\web\controllers\main.py", line 1351, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files\Odoo 14.0.20201006\server\odoo\api.py", line 392, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "C:\Program Files\Odoo 14.0.20201006\server\odoo\api.py", line 365, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "C:\Program Files\Odoo 14.0.20201006\server\odoo\models.py", line 1519, in load_views
    for [v_id, v_type] in views
  File "C:\Program Files\Odoo 14.0.20201006\server\odoo\models.py", line 1519, in <dictcomp>
    for [v_id, v_type] in views
  File "C:\Program Files\Odoo 14.0.20201006\server\odoo\addons\web\models\models.py", line 220, in fields_view_get
    r = super().fields_view_get(view_id, view_type, toolbar, submenu)
  File "C:\Program Files\Odoo 14.0.20201006\server\odoo\models.py", line 1607, in fields_view_get
    xarch, xfields = view.postprocess_and_fields(etree.fromstring(result['arch']), model=self._name)
  File "C:\Program Files\Odoo 14.0.20201006\server\odoo\addons\base\models\ir_ui_view.py", line 844, in postprocess_and_fields
    arch, name_manager = self._postprocess_view(node, model, validate=validate)
  File "C:\Program Files\Odoo 14.0.20201006\server\odoo\addons\base\models\ir_ui_view.py", line 856, in _postprocess_view
    self.postprocess(node, [], editable, name_manager)
  File "C:\Program Files\Odoo 14.0.20201006\server\odoo\addons\base\models\ir_ui_view.py", line 956, in postprocess
    self.postprocess(child, current_node_path, node_info['editable'], name_manager)
  File "C:\Program Files\Odoo 14.0.20201006\server\odoo\addons\base\models\ir_ui_view.py", line 956, in postprocess
    self.postprocess(child, current_node_path, node_info['editable'], name_manager)
  File "C:\Program Files\Odoo 14.0.20201006\server\odoo\addons\base\models\ir_ui_view.py", line 956, in postprocess
    self.postprocess(child, current_node_path, node_info['editable'], name_manager)
  [Previous line repeated 1 more time]
  File "C:\Program Files\Odoo 14.0.20201006\server\odoo\addons\base\models\ir_ui_view.py", line 951, in postprocess
    transfer_node_to_modifiers(node, node_info['modifiers'], self._context, current_node_path)
  File "C:\Program Files\Odoo 14.0.20201006\server\odoo\addons\base\models\ir_ui_view.py", line 66, in transfer_node_to_modifiers
    modifiers.update(ast.literal_eval(attrs))
  File "C:\Program Files\Odoo 14.0.20201006\python\lib\ast.py", line 46, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "C:\Program Files\Odoo 14.0.20201006\python\lib\ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\Odoo 14.0.20201006\server\odoo\http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files\Odoo 14.0.20201006\server\odoo\http.py", line 314, in _handle_exception
    raise exception.with_traceback(None) from new_cause
  File "<unknown>", line 1
    {'invisible'\: ['|', ('state', '!=', 'draft'), ('name', '!=', '/')]}
                                                                       ^
SyntaxError: unexpected character after line continuation character

**Comment by pedrobaeza** [comment] 2020-10-07 08:52
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Yenthe666** [comment] 2020-10-07 08:54
Plus what do you mean with "Click on Main Menu->Accounting"? As there is no "Accounting" app in community, only invoicing.

**Comment by tuanvuvd** [comment] 2020-10-07 09:14
> Plus what do you mean with "Click on Main Menu->Accounting"? As there is no "Accounting" app in community, only invoicing.

Why is your name like a Vietnamese name?

**Comment by Yenthe666** [comment] 2020-10-07 09:21
> > Plus what do you mean with "Click on Main Menu->Accounting"? As there is no "Accounting" app in community, only invoicing.
> 
> Why is your name like a Vietnamese name?
> @Yenthe666

Ehm, what? 😄

**Comment by CometSL9** [comment] 2020-10-07 09:37
Sorry, it should be "Invoicing". I use a german version, which is completely different...

**Comment by CometSL9** [comment] 2020-10-07 09:44
Un runbot, reproduction was not successful. The error appears only on my local DB.

**Comment by CometSL9** [comment] 2020-10-07 09:52
I tried to deinstall the "Invoicing" app on my local db and re-installed it.

The error persists, therefore, my best guess is that my odoo database is corrupt. Which is absoultely great, because I do not have a backup without this error.

That is a full day of labour lost (putting in products, configuring them, etc...).

Any guess how I can isolate and eliminate the errorneous DB entry?

**Comment by Yenthe666** [comment] 2020-10-07 09:59
Well, that's the risk of starting so early with a new major release. It's nothing severe though. Just find the XML view through the frontend and fix the XML format.

**Closed by Yenthe666** 2020-10-07 09:59 UTC
Labels: Need information

**Comment by CometSL9** [comment] 2020-10-07 10:00
????

**Comment by pedrobaeza** [comment] 2020-10-07 10:03
@CometSL9 further help on this, which it's a private problem, is out of the scope of this issue tracker I'm afraid. You can ask for help on the topic on forums.

**Comment by CometSL9** [comment] 2020-10-07 10:04
So, a not working software is a private problem? You are kidding.

**Comment by Yenthe666** [comment] 2020-10-07 10:06
@CometSL9 you've installed a new major release days after it was released. It's possible to have bugs. This bug is nowhere near a database break or heavy issue and it is already fixed in the latest builds.
You can find the view through the frontend and fix it or search through the Github commits to see what was wrong or you can do an update of your database. All of these will fix the issue and all of these options need no further help.

**Comment by CometSL9** [comment] 2020-10-07 10:08
... and how to update the database?

**Comment by pedrobaeza** [comment] 2020-10-07 10:14
Or maybe it's not a problem of the beta version, but incorrect manipulation. In any case, you have these options:

- Hire Odoo enterprise service, and their support service can handle this.
- Hire any Odoo third-party expert/company for fixing it.
- Fix it by yourself, maybe with some voluntary help from forums/community.

**Comment by asnetbeat** [comment] 2020-10-12 14:40
Same problem here. It seems to be a problem in the translation. When I switch the language to english, the problem disapears.

**Comment by asnetbeat** [comment] 2020-10-12 14:41
> Sorry, it should be "Invoicing". I use a german version, which is completely different...

Same problem here. It seems to be a problem in the translation. When I switch the language to english, the problem disapears.
