### ISSUE TITLE
[9.0] Semi-critical /web formatting issue after latest commit (Reproducible on Runbots)

### ISSUE THREAD

**Issue by lukebranch** [odoo/odoo#12312] opened 2016-06-07 04:32 UTC
<h1>Impacted versions:</h1>
9.0

<h1>Environment:</h1>
All Major Browsers (latest versions of Chrome, Safari, Firefox)
Runbot - latest 9.0 commit
<h1>Steps to reproduce:</h1>
<ol>
<li>Login to backend</li>
<li>View Sale Order List View (fonts and some formatting have been lost)</li>
<li>View inside a Sale Order - massive formatting problems, sale order document/page view is corrupted</li>
</ol>

<h1>Current behavior:</h1>
<ol>
<li>Huge formatting problems in the backend when related to fonts, icons, etc..</li>
<li>View inside a Sale Order - massive formatting problems, sale order document/page view is corrupted</li>
</ol>

<h1>Expected behavior:</h1>
Backend /web views are as they have always been, without formatting problems.

<h1>Video/Screenshot link (optional):</h1>
<img src="https://cloud.githubusercontent.com/assets/2337666/15846044/ceff033c-2cab-11e6-8455-af2ca5ac765c.gif"/>

**Comment by lukebranch** [comment] 2016-06-07 04:35
@Yenthe666 ,

I've just noticed an issue after running an update this morning (my last update was two days ago). It looks like something was committed that has broken some parts of the /web module. Fonts and formatting are affected.

I can't seem to pinpoint the commit it was merged in, however I think this one needs to be looked at as soon as possible.

**Comment by Yenthe666** [comment] 2016-06-07 05:07
Hi @lukebranch,

This indeed looks like quite a bug, thanks for reporting.
Its a duplicate of https://github.com/odoo/odoo/issues/12308 but yours shows way more details so I'll keep it open for that reason.
@mart-e and @jke-be can you guys look at this please?

**Comment by lukebranch** [comment] 2016-06-07 06:04
@Yenthe666 ,

Thanks for looking into this so quickly.

**Comment by JKE-be** [comment] 2016-06-07 08:07
@Gorash is working on this issue.
Meanwhile, you can temporarily ignore commit a4c1e10ae6705216a06275cf0f7defed1e06bbe3

**Closed** 2016-06-07 12:17 UTC
Labels: confirmed, RD

**Comment by lukebranch** [comment] 2016-06-07 13:59
@Gorash @JKE-be ,

Thanks for the fix!
