### ISSUE TITLE
[11.0] Upload an image in a task description.

### ISSUE THREAD

**Issue by pfichefet** [odoo/odoo#24196] opened 2018-04-12 08:54 UTC
Impacted versions:
v11

Steps to reproduce:
Log with a user who can write on task (who is not a SUPERUSER), open the form view of a task. Try to upload an image in to the description of the task.

Current behavior:
After having selecting an image from my computer I receive an error during the upload : "('The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\n\n(Document type: Task, Operation: write)', None)" although my user has this rights.

Expected behavior:
The image should be uploaded.
I think that the error comes from odoo/models.py line 2767
2767 => ids, result_ids = set(self.ids), set(result_ids) 
In my case self.ids is a tuple of string ('2049') and result_ids a tuple on integer (2049).
The next line, 
2768 => missing_ids = ids - result_ids 
missing_ids will always be equal to ids since result_ids and ids are not of the same type. 
2769 => if missing_ids:
This condition will then be true. Once we go in this if only the superuser has the right to upload the image. I replaced the line 2767 by  # ids_list = [int(id) for id in self.ids]
                                                        # ids, result_ids = set(ids_list), set(result_ids)
And it works, but I think the error comes from higher, set(self.ids) should always be a tuple of integer not string...

Video/Screenshot link (optional):
![screenshot from 2018-04-12 10-53-21](https://user-images.githubusercontent.com/9250028/38666695-d8013048-3e3f-11e8-846a-fbf2fd80dbe8.png)
![screenshot from 2018-04-12 10-53-39](https://user-images.githubusercontent.com/9250028/38666704-db4cfa66-3e3f-11e8-8b85-c86d95dc1251.png)

**Comment by pedrobaeza** [comment] 2018-04-12 19:37
Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by nhomar** [comment] 2018-04-13 06:56
Hello @pfichefet .

Please update your code, this is an old solved issue (it happens to me few month ago).

BTW, you are having an ACL problem I tested with pure demo data and just project installed and it is working as expected, please reopen the issue if you think it is not.

Check it you have a problematic custom ACL.

![image](https://user-images.githubusercontent.com/338634/38720908-9f41bad8-3ebd-11e8-97f6-b91048a7359a.png)

if you reopen it, please I kindly ask you to put the full log here and.

Regards.

**Closed by nhomar** 2018-04-13 06:56 UTC
Labels: 11.0, Services
