### ISSUE TITLE
[V11.0] I need datetime only shows to hour, not seconds

### ISSUE THREAD

**Issue by huoxy** [odoo/odoo#24546] opened 2018-05-03 10:58 UTC
Impacted versions:
11.0

Steps to reproduce:

Current behavior:
datetime fields shows to seconds

Expected behavior:
I need datetime only shows to hour, not seconds

Or there is any solution to pass "options" to bootstrap-datetimepicker to overwrite its 'format' parameter.

Video/Screenshot link (optional):

**Comment by hmrodrigues** [comment] 2018-05-03 11:11
Hello @huoxy 

You can set the datetime format for the languages under **Settings** -> **Translations** -> **Languages**

You can set the **Time Format** to %H to only show the hour. Note that this changes the format for all time formats for that language

![runbot](https://user-images.githubusercontent.com/8062666/39573388-ee71d472-4eca-11e8-8675-5c078682633c.png)


I don't know if this does the job for you

**Comment by Yenthe666** [comment] 2018-05-03 11:41
Yep indeed, and this is a question, not a bug in Odoo.
I'm closing this one as the Github tracker is only for bugs and not for questions. You can ask questions on the help forum at help.odoo.com

**Closed by Yenthe666** 2018-05-03 11:41 UTC

**Comment by huoxy** [comment] 2018-05-04 03:06
@hmrodrigues @Yenthe666 

Ok, Thanks a lot for giving a global solution, I will ask `how to set time format of a specific <field>` in help.odoo.com
