### ISSUE TITLE
Many2many required fields seen as empty by js validation

### ISSUE THREAD

**Issue by PCatinean** [odoo/odoo#7838] opened 2015-08-01 16:31 UTC
Impacted versions:

 - 8.0 (maybe others)

Steps to reproduce:

 1. Go to runbot and enter developer mode
 2. Navigate to product "iPad Retina Display" of demo data and edit form view
 3. Add required="1" to value_ids field
 4. Refresh view and click on the first line once then try to save

Current behavior:

 - Returns "The following fields are invalid: Product Attributes"

Expected behavior:

- Should save product without warning since there are already values in the many2many field

**Comment by Yenthe666** [comment] 2016-10-03 12:00
Hi @PCatinean,

Thanks a lot for your report. I've just tested this but I can no longer reproduce this issue.
I'm closing this issue since it has probably been fixed in the meanwhile.
If this issue still persists don't hesitate to answer here.

Regards,
Yenthe

**Closed by Yenthe666** 2016-10-03 12:00 UTC

**Comment by PCatinean** [comment] 2016-10-03 21:31
@Yenthe666 it seem to be fixed indeed. Thank you!

**Comment by Yenthe666** [comment] 2016-10-04 07:08
You're welcome, best of luck with Odoo and thank you for your feedback.
