### ISSUE TITLE
[9.0] some css not loading

### ISSUE THREAD

**Issue by monami7000** [odoo/odoo#9963] opened 2015-12-08 08:44 UTC
I installed odoo v9 and got http://web.syspro.info/web/content/248-2c1fc9f/web.assets_common.0.css net::ERR_CONNECTION_RESET
and the it lacks some css (see picture)

![screenshot from 2015-12-08 09 38 19](https://cloud.githubusercontent.com/assets/4570429/11651307/2251d40c-9d90-11e5-9d9e-a2ebb12dda37.png)

**Comment by busel7** [comment] 2015-12-13 13:59
May be browser problem. Try using newest Chrome browser. Or you can clear your browser cache.

**Comment by lukebranch** [comment] 2015-12-13 16:50
@monami7000 ,

I've had this issue when i've installed a module that hasn't completely installed due to missing dependencies or other things.

My suggestion would be to first edit your /etc/odoo-server.conf file and remove any community modules from your addons path. Restart the server and try to access it again and see if you have the same issue.

This has most often been caused in my personal experience from the use of auto-checking for external (eg. python) dependencies in modules. Keep in mind these modules do not need to be installed and only need to be in your addons path in order to cause this kind of behaviour.

**Comment by Yenthe666** [comment] 2016-06-15 10:55
Hi @monami7000,

This issue is no longer present with the latest Odoo code.
If you still face this issue please add some more information on how to reproduce this.
I'll close this issue, in case you have more information just post it here and I'll look at it again.

Regards,
Yenthe

**Closed by Yenthe666** 2016-06-15 10:55 UTC
