### ISSUE TITLE
Error while updating image inside Odoo product

### ISSUE THREAD

**Issue by ashish-webkul** [odoo/odoo#19945] opened 2017-10-08 07:26 UTC
Impacted versions: 11.0

Steps to reproduce: Update image of any product which already has an image from "**Product Variants**" Section.

Current behavior:
Error which i am getting `"Traceback (most recent call last):
  File "/usr/lib/python3.4/base64.py", line 519, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: str object does not have the buffer interface

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.4/encodings/base64_codec.py", line 19, in base64_decode
    return (base64.decodebytes(input), len(input))
  File "/usr/lib/python3.4/base64.py", line 553, in decodebytes
    _input_type_check(s)
  File "/usr/lib/python3.4/base64.py", line 522, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value
  File "/opt/odoo/odoo/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 341, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 334, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 929, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 916, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 908, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/addons/product/models/product.py", line 303, in write
    res = super(ProductProduct, self).write(values)
  File "/opt/odoo/addons/mail/models/mail_thread.py", line 277, in write
    result = super(MailThread, self).write(values)
  File "/opt/odoo/odoo/models.py", line 3019, in write
    self._fields[key].determine_inverse(self)
  File "/opt/odoo/odoo/fields.py", line 1045, in determine_inverse
    getattr(records, self.inverse)()
  File "<decorator-gen-191>", line 2, in _set_image_medium
  File "/opt/odoo/odoo/api.py", line 369, in loop
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/opt/odoo/odoo/api.py", line 369, in <listcomp>
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/opt/odoo/addons/product/models/product.py", line 256, in _set_image_medium
    self._set_image_value(self.image_medium)
  File "<decorator-gen-193>", line 2, in _set_image_value
  File "/opt/odoo/odoo/api.py", line 369, in loop
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/opt/odoo/odoo/api.py", line 369, in <listcomp>
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/opt/odoo/addons/product/models/product.py", line 264, in _set_image_value
    image = tools.image_resize_image_big(value)
  File "/opt/odoo/odoo/tools/image.py", line 143, in image_resize_image_big
    return image_resize_image(base64_source, size, encoding, filetype, avoid_if_small)
  File "/opt/odoo/odoo/tools/image.py", line 56, in image_resize_image
    image_stream = io.BytesIO(codecs.decode(base64_source, encoding))
TypeError: decoding with 'base64' codec failed (TypeError: expected bytes-like object, not str)"`

Expected behavior: It should update product images 

Video/Screenshot link (optional):
Video Link : http://nimb.ws/my5Pk6
Screenshot : https://prnt.sc/guolsa

**Comment by Yenthe666** [comment] 2017-10-08 13:47
Hi @ashish-webkul,

Thank you for your bug report.
I've just tested this on the latest Odoo 11 and I can still reproduce it:
![image](https://user-images.githubusercontent.com/6352350/31317365-e6ab6fe2-ac3f-11e7-9b46-b68a4a999f17.png)
This looks like a problem with encoding and the conversion from P2 to P3. @xmo-odoo could you have a look?

**Comment by xmo-odoo** [comment] 2017-10-11 09:59
The issue should now be fixed in the 11.0 branch.

Although while that was not a factor here please note that you seem to be using Python 3.4 and we officially only support 3.5 and up.

**Closed by xmo-odoo** 2017-10-11 09:59 UTC
Labels: 11.0, confirmed, P3

**Comment by saadalee** [comment] 2018-01-17 21:27
Same issue with python 3.6
