### ISSUE TITLE
 When changing  user's password, an error appear!

### ISSUE THREAD

**Issue by baoding-fenshuajiang** [odoo/odoo#56764] opened 2020-08-29 10:06 UTC
Impacted versions:
master

Steps to reproduce:
"Settings-->Users &  Companies-->Users"， Click one user, Click "Action-->Change Password"，input new password，click “Change  Password”.
![image](https://user-images.githubusercontent.com/9589725/91634309-07456f00-ea22-11ea-8bd7-1ea222036e61.png)

Current behavior:
![image](https://user-images.githubusercontent.com/9589725/91634280-de24de80-ea21-11ea-83b2-cc72ee2c5cbd.png)
Expected behavior:
No error

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2020-08-29 10:44
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by sswapnesh** [comment] 2020-08-29 11:13
@pedrobaeza  Yes I can reproduce it on saas-13-5 and master, so Maybe this can be closed as It still in dev.

**Comment by pedrobaeza** [comment] 2020-08-29 11:20
Oh, yes, I didn't see that it was over master, so let's close it as that's not a stable branch, but good to warn @odony about this for him to know it.

**Closed by pedrobaeza** 2020-08-29 11:20 UTC
Labels: Need information

**Comment by sswapnesh** [comment] 2020-09-19 07:15
Update: This has been fixed in https://github.com/odoo/odoo/commit/641ae07dbce1d0515fb0710a3363db47b27548e7
