### ISSUE TITLE
[12.0] Extra menu entries after install website_event_track

### ISSUE THREAD

**Issue by CLTanuki** [odoo/odoo#28972] opened 2018-11-22 18:15 UTC
Impacted versions: 12.0

Steps to reproduce: Install website_event_track module. No matter with or without demo data.

Current behavior: Extra fields are added to main menu once `Website Menu​` checkbox is activated for event. After removing checkbox entries are still there.

Expected behavior: Entries are added in sub menu, but not in main, and removed after option is unchecked.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/5824716/48918107-9ad82c00-ee9b-11e8-99da-42dcb7d324fa.png)

**Comment by pedrobaeza** [comment] 2018-11-22 18:29
Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by CLTanuki** [comment] 2018-11-23 18:04
Here are screenshots of last v12 runbot from chrome and firefox under stable debian.

![screenshot at 2018-11-23 21-00-30](https://user-images.githubusercontent.com/5824716/48956271-384a6300-ef63-11e8-8dd1-3ff76d912912.png)
![screenshot at 2018-11-23 21-02-54](https://user-images.githubusercontent.com/5824716/48956272-384a6300-ef63-11e8-8504-4f29b69a3c66.png)

**Comment by CLTanuki** [comment] 2018-11-23 18:10
Even under incognito mode.

![screenshot at 2018-11-23 21-10-01](https://user-images.githubusercontent.com/5824716/48956461-33d27a00-ef64-11e8-9718-fd058823c599.png)

**Comment by pedrobaeza** [comment] 2018-11-24 13:49
OK, I see, thanks for the extra info, and indeed, the problem arises in all runbot instances.

@JKE-be is this under your side?

**Comment by JKE-be** [comment] 2018-11-28 13:16
Thanks for the reporting.

It has been introduced by 
https://github.com/odoo/odoo/commit/7077f18e3a3e5ccb8f877fae99f49d87574bac7e

and fixed by commit https://github.com/odoo/odoo/commit/a67553c9d2a7a5fcb28e44a5fbd5c245d851b91d

JKE

**Closed by JKE-be** 2018-11-28 13:16 UTC
Labels: 12.0, Confirmed, Services, Website
