### ISSUE TITLE
Problems with Odoo fetchmail Routing and corresponding server actions

### ISSUE THREAD

**Issue by Rumpen** [odoo/odoo#22559] opened 2018-01-26 15:53 UTC
Impacted versions: 10 (other version not checked, so possible impact here to)

We use fetchmail.server for the email adress support@mycompany.org.
Besides the email settings in the fetchmail.server we defined:
- "Action to Perform on Incoming Mails": Create a new Record: Project Issue 
- Perform a Server Action that tags each created project Project Issue with a specified Tag "EXTERNAL SUPPORT" and set the stage to "TODO".

99% the system works as expected: new mails will create a new Project Issue in the stage "TODO" with the Tag "EXTERNAL Support", but we noticed three problems:

**A. Some Emails sent to support@mycompany.org didnt create or update a Project Issue but created a Lead in CRM.
B. Some Emails sent to support@mycompany.org didnt create or update a Project Issue but created a new message for a User.
C. Some Issues (esp. older ones with low IDs) which had been in a stage other then "TODO", have been automatically moved to the stage "TODO" and sometimes tagged "EXTERNAL SUPPORT".**

Our Customer sents a new mail address an issue to us email_to: support@mycompany.com and wants to inform his own departments that he did so: cc: sales@othercompany.com, admin@othercompany.com

- A cron in ODOO peridodically checks for new mails in using the method fetch_mail in fetchmail.server
- The method fetch_mail checks the IMAP for unread emails and each unread email is processed in the following order:
- Use Odoo mail.thead function message_process to process the email
- Use the return value of the message_process to call the server action  

the message is processed by the message_process method of mail.thread which will:
1. Parse the message
2. Determine the route this message has to take in odoo (message_route of mail.thread)

message_route only returns a route for the first matching of the following conditions:

1. The email is a reply to an email sent from our odoo (Not the case)
2. An alias can be found for any recpient of the email (Maybe)
3. A fallback model is defined in the fetch.mail server (Yes)

The aliascheck at the moment works with the list rcpt_tos_localparts  wich is created by:
rcpt_tos = ','.join([
    tools.decode_message_header(message, 'Delivered-To'),
    tools.decode_message_header(message, 'To'),
    tools.decode_message_header(message, 'Cc'),
    tools.decode_message_header(message, 'Resent-To'),
    tools.decode_message_header(message, 'Resent-Cc')])
rcpt_tos_localparts = [e.split('@')[0].lower() for e in tools.email_split(rcpt_tos)]

In our example the list is now ['support', 'support', 'sales', 'admin'], support is added two times ('Delivered-To' + 'To'), Domain is split off.

for this list the aliases are searched: dest_aliases = Alias.search([('alias_name', 'in', rcpt_tos_localparts)] 

This is a big problem as the routes ignore the domain of the email as the domain has been split off and we have an alias defined for:
sales -> create crm.lead
admin -> message to user admin

So finally the message_route returns a route of list in our case a route for sales and admin. (fallback model (project.issue) is ignored as condition 2 matches)

The route list is then sent to the message_route_process function wich does the following:

iterate all routes and return a thread_id (this is very important for Problem 3):
-> A new crm.lead will be created with the message. (thread_id: 100 (id of the new created lead) -> Explains **Problem A**
-> The Admin User gets a new message from our customer. (thread_id: 1 (id of the existing User Admin)  -> Explains **Problem B**
Method returns thread_id 1 (thread_id is not a list so always the last route in the list of routes will set the thread_id).

This thread_id is now used in the server action we defined in the fetchmail.server for the model project.issue: The project.issue with the id 1 will be moved to stage "TODO" and taggged "EXTERNAL Support") **Problem C.**

**Comment by scaldewi** [comment] 2018-02-09 13:48
We experience similar faulty behaviour with one customer.
"incoming mailserver" is configured "Actions to Perform on Incoming Mails":
Create a New Record: None (empty)
Server Action: None (empty)

1)
fetchmail receives mail from mailserver and correctly assigns them to a previous sent mail at odoo object (f.e. a reply to a sales order mail to customer).

2) If there is mail without previous Odoo mail (no reply mail)
Expected behaviour: When a mail cannot be assigned to an odoo sent mail, expected behaviour would be that this mail is simply ignored.
Observed behaviour: Odoo creates a crm.lead (althoug not configured with incoming mail)

I would consider this to be a buggy behaviour.

**Comment by dbo-odoo** [comment] 2018-02-13 16:19
@Rumpen 
At every step, the system behaves as intended (thank you for the detailed explications btw).

Note that the server action is launched for every e-mail that comes in, regardless of where it's routed. I agree that it's a bit weird that it gets applied on the wrong model if another route than the fallback is applied; I'll see if we can do something about that but there's no guarantee at this point since this bug is low level (and thus dangerous) and that the workaround is really easy.

Instead of assigning your server action to the fetchmail, simply create an automated action on your project issues at creation. Or better yet, create an alias for your project directly (+ automated action for the tag if needed).

To be frank, I would not recommend creating anything from the fetchmail if aliases are defined as well; the main fetchmail should be a catchall (with all your aliases done there) and the support@ email should be a separate mail box that you use just for that and that creates your record (btw we have possible plans to drop this "creation" at fetchmail at some point since aliases should be the way to go).

@scaldewi your description seems to be unrelated to the problem happening here; probably an alias somewhere or something of the kind.

**Comment by Rumpen** [comment] 2018-02-14 11:08
@dbo-odoo 
Thanks for the info but you did not adress the domain issue i explained esp. for Problem A wich in my view is still buggy even if i assign a dedicated alias for the support project and an automated action for the tag.

Here is a Usecase that explains the problem if i use aliases:

Alias 1: support@ -> Create Issue
Alias 2: sales@ -> Create CRM Lead

A Customer sents an email with email_to: support@**mycompany.com** and wants to inform his coworkers and uses email_cc: sales@**ourcustomer.com**.

As the domain is stripped of in the message_route function (e.split('@')[0].lower()) both aliases will be accepted as routes and thus an Issue and a Lead will be created. 

The expected behaviour would be that the mail sales@ourcustomer.com would be ignored in the message_route function as its not the domain our odoo instance is routing for.

**Comment by Rumpen** [comment] 2018-03-23 07:50
@dbo-odoo any update concerning my comment from last month?

**Comment by cvinh** [comment] 2019-09-02 17:15
@rumpen do you know if your issue is fixed in v12 ?

**Comment by C3POdoo** [comment] 2023-03-30 12:02
Dear @Rumpen,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._

**Closed by C3POdoo** 2023-03-30 12:02 UTC
Labels: Services, 10.0
