### ISSUE TITLE
[13.0] Manufacturing - Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by imanie383** [odoo/odoo#65763] opened 2021-02-08 20:31 UTC
Impacted versions: 13.0

Steps to reproduce:
1.- Manufacturing
2.-Master Data
3.- Bills of Materials
4.- Select a product
5.- Components
https://user-images.githubusercontent.com/35231827/107282675-eba6b180-6a20-11eb-9dea-da35216c8706.mp4

Current behavior:
```
Traceback:
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at http://localhost:8069/web/content/1139-e913ba1/web.assets_backend.js:1351:344
    at Function._.each._.forEach (http://localhost:8069/web/content/1138-d56694f/web.assets_common.js:108:558)
    at Class._loadData (http://localhost:8069/web/content/1139-e913ba1/web.assets_backend.js:1350:499)
    at async Promise.all (index 0)
```

Expected behavior:

Video/Screenshot link (optional):
https://youtu.be/IIxSlv-oSAc

A validation error was added by odoo in:
https://github.com/odoo/odoo/blame/2bfd0fb06b41a5743565cf9aa7080bf411109d98/addons/web/static/src/js/views/basic/basic_view.js#L146

They are not validating the existence of the fieldsInfo attribute

Video:
https://user-images.githubusercontent.com/35231827/107282675-eba6b180-6a20-11eb-9dea-da35216c8706.mp4

**Comment by pedrobaeza** [comment] 2021-02-08 20:53
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by imanie383** [comment] 2021-02-08 21:19
these are the steps to replicate in runbot:
@pedrobaeza 

https://user-images.githubusercontent.com/35231827/107282675-eba6b180-6a20-11eb-9dea-da35216c8706.mp4

**Comment by pedrobaeza** [comment] 2021-02-09 07:17
OK, closing as there's a PR.

**Closed by pedrobaeza** 2021-02-09 07:17 UTC
Labels: 13.0, Need information
