### ISSUE TITLE
11.0 MRP Wrong Inventory behaviour when using Workorders

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#20964] opened 2017-11-15 10:40 UTC
Impacted versions:
11.0 Enterprise, but community code

Now I might be missing something here but I'm pretty sure this is correct.

Steps to reproduce:
You need to have some kind of location hierarchy and put a tracked product into a location
Lets say Product A - qty 1000 into Stock/Rack1/Shelf1 (Lot 0001)
Product Category is realtime, FIFO

Have a Bom to create product B from Product A and a routing with a single step.
Create a manufacturing order.
Process it through the workorder and you will see the final Stock Move is from Stock -> Production (unless stock is a view location, then you just get error messages and can't post).

Create / duplicate / edit above BoM to have no routing.
Create a manufacturing order using this BoM.
Click Produce - 0001 should already be in there coming from the correct location so your moves end up
Shelf1 -> Production
auto proposed as expected for FIFO.

Current behavior:
No way to select a location, or use inventory rules with workorders.  Check availability on the production seems to do what we want (hard to tell as the relevant fields are hidden when using workorders), but then the work order overwrites it?

Expected behavior:
Behaves same as working without workorders.

Video/Screenshot link (optional):

**Comment by sle-odoo** [comment] 2017-11-15 10:51
@gdgellatly Hello, thanks for the report. Did you click on "check availability" on the MO before processing the WO and is the error message related to quants in a view location?

Regards

**Comment by gdgellatly** [comment] 2017-11-15 11:30
Hi @sle-odoo 
1- I did it both with and without using check availabillty, behaviour is the same.
2- I think the error message was just about posting to a view location - I don't think it was to do with quants.  That was a couple days ago now, and I changed to internal just to put in a different bug report related to rounding errors.  I can't change it back now because of the stock moves.

However in trying to zero it out I found something to help.

There is a currently 2 reservations of stock for manufacturing orders, both for shelf 1.
- I go to one of the reservation workorders, which happened to be in progress at that time and click Mark Done.
- The reservation is still for Shelf 1
- I click Post inventory on the manufacturing and the move is now posted from Stock.

**Comment by gdgellatly** [comment] 2017-11-15 11:31
Oh btw, don't worry about the error message, it should be there if this works as expected, just obviously in order to report this bug and another I had to get around it.

**Comment by gdgellatly** [comment] 2017-11-15 11:49
Hmmm I just saw something weird, let me triple check whats going on here, it might be to do with final_lot_id.  I'll provide details and a vid tomorrow.

**Comment by gdgellatly** [comment] 2017-11-15 16:39
@sle-odoo OK I found the issue - thankfully it was your code not mine and was 2 seperate bugs combining.  What it is to do with is the function _generate_lot_ids (at least IRT to tracked lots)
1. Takes no account of existing reservations and creates a new moveline 
2. Then takes no account of inventory rules and just uses the production order location

**Comment by sle-odoo** [comment] 2017-11-16 14:50
@gdgellatly are you using the `quality_mrp` module or did you ran your tests only on community?

**Comment by sle-odoo** [comment] 2017-11-16 15:48
nope, i'm wrong, it's due to the fact that we tried to unify the models and method used in stock/mrp in v11. in v10, there was a [second "action_done"](https://github.com/odoo/odoo/blob/10.0/addons/mrp/models/stock_move.py#L278) on move that used the quants reserved by `action_assign`. As we got rid of the move lots and the second action_done and the links between the reserved quants and the moves, the only solution would be to correctly share the reservation key (location_id, lot_id, owner_id, package_id) on the temp move lines... will try make a fix..

**Comment by gdgellatly** [comment] 2017-11-16 19:08
@sle-odoo Note there was a related bug reported yesterday with quality_mrp and stock routes.  Totally different effect but seems same root cause.  Sorry with all the bot closures I can't find it again.

**Comment by gdgellatly** [comment] 2017-11-16 19:08
Oh yes, you are right I was using quality_mrp

**Comment by sle-odoo** [comment] 2017-11-16 19:57
@gdgellatly The issue is fixed in the branch linked in this issue (not the final patch), so it comes directly from mrp. It was not easy because the same mechanism (linking the temporary move line to the reservation move line through lot_produced_id) is broken too in v10, but the move_quants method has a fallback that moves the reserved quants and it worked as expected.

**Closed** 2017-11-17 12:32 UTC
Labels: 11.0, Logistics
