### ISSUE TITLE
Error to install new module

### ISSUE THREAD

**Issue by alexlarraga1** [odoo/odoo#32223] opened 2019-03-28 18:07 UTC
Impacted versions: 11.0

Steps to reproduce:
-Go to apps
-Select purchase management
-Install

Current behavior:

`
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo11/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/odoo11/odoo/tools/convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_model.py", line 1488, in _update
    record = record.create(values)
  File "/opt/odoo/odoo11/addons/sales_team/models/res_users.py", line 17, in create
    user = super(ResUsers, self).create(vals)
  File "/opt/odoo/odoo11/addons/auth_signup/models/res_users.py", line 154, in create
    user = super(ResUsers, self).create(values)
  File "/opt/odoo/odoo11/addons/mail/models/res_users.py", line 55, in create
    raise exceptions.RedirectWarning(msg, action.id, _('Go to the configuration panel'))
odoo.exceptions.RedirectWarning: ('No puede crear un nuevo usuario desde aquí.\nPara crear un nuevo usuario, vaya al panel de configuración.', 65, 'Ir al panel de configuración')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo11/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo11/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo11/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo11/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo11/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo11/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo11/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo11/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo11/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo11/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo11/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-42>", line 2, in button_immediate_install
  File "/opt/odoo/odoo11/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/addons/base/module/module.py", line 449, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo/odoo11/odoo/addons/base/module/module.py", line 542, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/odoo11/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo11/odoo/modules/loading.py", line 380, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/odoo/odoo11/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/odoo11/odoo/modules/loading.py", line 181, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/odoo11/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/odoo11/odoo/tools/convert.py", line 791, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/odoo11/odoo/tools/convert.py", line 852, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/odoo11/odoo/tools/convert.py", line 741, in parse
    self.parse(rec, mode)
  File "/opt/odoo/odoo11/odoo/tools/convert.py", line 751, in parse
    exc_info[2]
  File "/opt/odoo/odoo11/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/odoo/odoo11/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/odoo11/odoo/tools/convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_model.py", line 1488, in _update
    record = record.create(values)
  File "/opt/odoo/odoo11/addons/sales_team/models/res_users.py", line 17, in create
    user = super(ResUsers, self).create(vals)
  File "/opt/odoo/odoo11/addons/auth_signup/models/res_users.py", line 154, in create
    user = super(ResUsers, self).create(values)
  File "/opt/odoo/odoo11/addons/mail/models/res_users.py", line 55, in create
    raise exceptions.RedirectWarning(msg, action.id, _('Go to the configuration panel'))
odoo.tools.convert.ParseError: "No puede crear un nuevo usuario desde aquí.
Para crear un nuevo usuario, vaya al panel de configuración.
65
Ir al panel de configuración" while parsing /opt/odoo/odoo11/addons/purchase/security/purchase_security.xml:36, near
<record id="base.default_user" model="res.users">
        <field name="groups_id" eval="[(4,ref('purchase.group_purchase_manager'))]"/>
    </record>
`

**Comment by pedrobaeza** [comment] 2019-03-28 18:09
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by alexlarraga1** [comment] 2019-03-28 19:25
> Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?
> 
> If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.
> 
> If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.
> 
> For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.



In runbot this problem does not occur,  but here I leave some screenshots of the only steps I take and the modules that I have installed.

![odoo-1](https://user-images.githubusercontent.com/25646528/55186761-eefe6000-515c-11e9-861b-b719d5fb701b.PNG)
![odoo-2](https://user-images.githubusercontent.com/25646528/55186762-eefe6000-515c-11e9-9355-ce04cfb1f460.PNG)
![odoo-3](https://user-images.githubusercontent.com/25646528/55186764-eefe6000-515c-11e9-8b96-d0ef63fb2708.PNG)

**Comment by pedrobaeza** [comment] 2019-03-28 19:28
Then you should probably an altered or outdated DB. Try on a fresh DB, or update you DB modules.

Closing this as no Odoo issue, but deployment one.

**Closed by pedrobaeza** 2019-03-28 19:28 UTC
Labels: Need information

**Comment by sswapnesh** [comment] 2019-03-30 09:33
@alexlarraga1  
It seems someone has deleted **Default User Template** user in that Db which is causing this error.
