### ISSUE TITLE
[IMP] account_move_line edition in an invoice move is very slow when processing large invoices

### ISSUE THREAD

**Issue by a-willem** [odoo/odoo#83828] opened 2022-02-02 11:57 UTC
Impacted versions:
15.0

Steps to reproduce:
import a *very* large invoice (> 900 lines)

Current behavior:
Any modification requires a long processing time while the frontend is seeing onchanges to the backend and processing the final account_move onchange response

Expected behavior:
Either add a "batch edition" mode, adding checkboxes in front of lines and global actions (like account.move.line.tree)
Or change the account_move_line one2many to allow for easier one-by-one edition and a final recompute of automated fields and lines.

Video/Screenshot link (optional):

<img width="1364" alt="Screenshot 2022-02-02 at 12 50 15" src="https://user-images.githubusercontent.com/31848075/152148446-04514881-3005-43d3-a827-6d9aefb7a493.png">

Support ticket number submitted via odoo.com/help (optional): 2752277

**Comment by william-andre** [comment] 2022-02-28 16:39
We are actively working on this issue, and trying multiple PoCs.

I am closing this issue but it is one of our priorities already, even if the issue is very complex.

**Closed by william-andre** 2022-02-28 16:39 UTC
Labels: Accounting, Performance

**Comment by a-willem** [comment] 2022-03-02 17:03
Hi @william-andre and thanks for your reply.

Would it be possible to participate / give some feedback on those POCs ? One customer I'm currently integrating is generating 1000+ lines in their invoices and this performance issue is a huge hit. (Not even mentioning the hell of interacting with account.move / account.move.line OdooRPC creation for such a huge entry.)

Best regards,
AW
