### ISSUE TITLE
[11.0] < 55K rows record raise MemoryError

### ISSUE THREAD

**Issue by smurf-U** [odoo/odoo#50696] opened 2020-05-05 16:18 UTC
Impacted versions:
11.0

Steps to reproduce:
When trying to **filter out Sales Order Customer doesn't contain with "XYZ"**.

Memory Allocated to server:-

- 4 webserver with 5 worker with below memory
- limit_memory_soft = 6526623069
- limit_memory_hard = 572662306

Video/Screenshot link (optional):

Error:
Odoo Server Error

> Traceback (most recent call last):
>   File "/data/odoo-production/odoo/fields.py", line 948, in __get__
>     value = record.env.cache.get(record, self)
>   File "/data/odoo-production/odoo/api.py", line 967, in get
>     value = self._data[key][field][record._ids[0]]
> KeyError: 296610
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/data/odoo-production/odoo/http.py", line 653, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "<string>", line 68, in _handle_exception
>   File "/data/odoo-production/odoo/http.py", line 312, in _handle_exception
>     raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
>   File "/data/odoo-production/odoo/tools/pycompat.py", line 87, in reraise
>     raise value
>   File "/data/odoo-production/odoo/http.py", line 695, in dispatch
>     result = self._call_function(**self.params)
>   File "/data/odoo-production/odoo/http.py", line 344, in _call_function
>     return checked_call(self.db, *args, **kwargs)
>   File "/data/odoo-production/odoo/service/model.py", line 97, in wrapper
>     return f(dbname, *args, **kwargs)
>   File "/data/odoo-production/odoo/http.py", line 337, in checked_call
>     result = self.endpoint(*a, **kw)
>   File "/data/odoo-production/odoo/http.py", line 939, in __call__
>     return self.method(*args, **kw)
>   File "/data/odoo-production/odoo/http.py", line 517, in response_wrap
>     response = f(*args, **kw)
>   File "/data/odoo-production/addons/web/controllers/main.py", line 876, in search_read
>     return self.do_search_read(model, fields, offset, limit, domain, sort)
>   File "/data/odoo-production/addons/web/controllers/main.py", line 898, in do_search_read
>     offset=offset or 0, limit=limit or False, order=sort or False)
>   File "/data/odoo-production/odoo/models.py", line 4268, in search_read
>     records = self.search(domain or [], offset=offset, limit=limit, order=order)
>   File "/data/odoo-production/odoo/models.py", line 1481, in search
>     res = self._search(args, offset=offset, limit=limit, order=order, count=count)
>   File "/data/odoo-production/odoo/models.py", line 3816, in _search
>     query = self._where_calc(args)
>   File "/data/odoo-production/odoo/models.py", line 3606, in _where_calc
>     e = expression.expression(domain, self)
>   File "/data/odoo-production/odoo/osv/expression.py", line 668, in __init__
>     self.parse()
>   File "/data/odoo-production/odoo/osv/expression.py", line 1064, in parse
>     push(create_substitution_leaf(leaf, _get_expression(comodel, left, right, operator), model))
>   File "/data/odoo-production/odoo/osv/expression.py", line 1057, in _get_expression
>     res_ids = [x[0] for x in comodel.with_context(active_test=False).name_search(right, [], operator, limit=None)]
>   File "/data/odoo-production/odoo/addons/base/res/res_partner.py", line 697, in name_search
>     return super(Partner, self).name_search(name, args, operator=operator, limit=limit)
>   File "/data/odoo-production/odoo/models.py", line 1563, in name_search
>     return self._name_search(name, args, operator, limit=limit)
>   File "/data/odoo-production/odoo/models.py", line 1578, in _name_search
>     return recs.sudo(access_rights_uid).name_get()
>   File "/data/odoo-production/odoo/addons/base/res/res_partner.py", line 588, in name_get
>     name = partner.name or ''
>   File "/data/odoo-production/odoo/fields.py", line 952, in __get__
>     self.determine_value(record)
>   File "/data/odoo-production/odoo/fields.py", line 1055, in determine_value
>     record._prefetch_field(self)
>   File "/data/odoo-production/odoo/models.py", line 2663, in _prefetch_field
>     result = records.read([f.name for f in fs], load='_classic_write')
>   File "/data/odoo-production/odoo/models.py", line 2601, in read
>     self._read_from_database(stored, inherited)
>   File "/data/odoo-production/odoo/models.py", line 2755, in _read_from_database
>     self.env.cache.update(fetched, field, values)
>   File "/data/odoo-production/odoo/api.py", line 978, in update
>     self._data[key][field].update(pycompat.izip(records._ids, values))
> MemoryError

**Comment by pedrobaeza** [comment] 2020-05-05 16:22
The problem is not the limits you have configured, but the resources of your server, and in this case, you don't have memory. That's not something that has to be with Odoo itself, and you should manage and size your server accordingly.

Closing as no Odoo issue.

**Closed by pedrobaeza** 2020-05-05 16:22 UTC

**Comment by smurf-U** [comment] 2020-05-05 16:37
Hi @pedrobaeza 

Appreciate your response. But this is hepping every time even it same on downtime too.
So, what is the issue? Can you help me out?

**Comment by pedrobaeza** [comment] 2020-05-05 17:07
I can't say, but that's a low level error and you should monitor your server memory consumption to see.

**Comment by smurf-U** [comment] 2020-05-05 17:11
> I can't say, but that's a low level error and you should monitor your server memory consumption to see.

Okay thanks
