### ISSUE TITLE
[15.0] Display issue in timesheet app

### ISSUE THREAD

**Issue by jaitjulien** [odoo/odoo#104247] opened 2022-10-27 07:21 UTC
Impacted versions: 15

Steps to reproduce:
- Create enough (more than 80) projects.
- Code time on all these projects.
- Go to a list view in the Timesheets app and group by project

Current behavior:
You will see some projects appearing with (0) ts (whereas the shouldn't) and if you click on the arrow to see another page, the number of projects will change, and some of the projects with (0) will still be there, but with timesheets. Looks like it displays also projects that should be on other pages.

Expected behavior:

We shouldn't see projects with 0 timesheets

Video/Screenshot link (optional):

I did it on this branch (https://20546679-15-0-all.runbot60.odoo.com/web#cids=1%2C2%2C3%2C4%2C5&menu_id=659&action=946&model=account.analytic.line&view_type=list) under My Company (Chicago) to show you.

Thanks for your help!

**Comment by jaitjulien** [comment] 2022-10-27 07:39
I forgot to mention that it happens only when grouping by project

**Comment by bouvyd** [comment] 2022-11-03 08:07
Hello hello,

The issue is caused by the "group_expand" functionality.

In short: when specifying model fields definition, it is possible to tell Odoo that a "group by" on a specific field should always include values for which there are no records (the list of groups is expanded, hence the name). For example, when grouping tasks by Stages in a project, it makes sense to "include" stages for which there are currently no record in the result; otherwise there would never be any empty column in the kanban view, and the list and pivot view would not "reflect" the structure of the project stages properly (stages without any task in them would never be shown).

However, when you start hitting the limit of the list view, Odoo will start mixing stuff up in an incoherent way: assuming you set a limit of 5 groups in the list views, the system will fetch 5 groups for which there are record, then try to include groups for which there are no data (even if you reached the expected number). Let's imagine that you have a project with the following stages and number of records in them:
- New (0)
- Spec (2)
- Dev (0)
- Testing (5)
- Review (1)
- Done (5)
- Canceled (0)

You have 7 groups, 3 of which are "empty". In a normal list view where the limit if set to 80, you will see everything at once and all is well. If you limit the list to 5 groups, the following will happen:
- the groups with tasks in them are fetched from the db, ordered by sequence (Spec, Testing, Review, Done)
- the limit is reached, but the "expanding" feature is not aware of the limit and doesn't care: the empty groups are read from the db, ordered by sequence (New, Dev, Canceled)
- the empty groups are merged with the non-empty ones, and you end up with more groups than initially asked 

This behaviour will become even more messy if you start using the pager and try to go to page 2, for example, because this means that you have to include offsets, limits, make sure to expand properly and insert empty records at the right place (meaning that you need to respect the ordering clause, which is not trivial).

There are no solutions in stable, and to be honest I do not consider this an emergency (AFAICT, this has been the case since the dawn of Odoo, a.k.a Odoo 8 at least, and I confirmed on runbot that it's present in 13.0, which is still the middle-age Odoo-wise). But indeed, we will check what we can do in future versions, since it leads to a very weird experience in the UI (even though the feature is still worth it, so I prefer leaving it be a bit buggy when used on a corner case rather than removing it entirely).


Cheers,

**Closed by bouvyd** 2022-11-03 08:07 UTC
