### ISSUE TITLE
[12.0] analytic account domain 

### ISSUE THREAD

**Issue by dlemireanybox** [odoo/odoo#49642] opened 2020-04-16 10:18 UTC
Impacted versions: 12.0

Steps to reproduce: 
1) go to Facturation or accounting > supplier > invoice list> invoice 
2) click on studio button and clic on invoice line list
3) click on edit list view
4) click on analytic account field 
5) click on domain property

Current behavior:
by default ,  an error message occur the domain is not supported
Expected behavior:
by default , no error message

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment] 2020-04-16 14:07
Duplicate of https://github.com/odoo/odoo/issues/42609
Odoo has said they will not fix this in stable versions and will try to improve this in the future V14.

**Closed by Yenthe666** 2020-04-16 14:07 UTC
