### ISSUE TITLE
Odoo Help/Forum Issue

### ISSUE THREAD

**Issue by hilarak** [odoo/odoo#45446] opened 2020-02-16 10:28 UTC
**Impacted versions:** **ODOO Latest**

**Steps to reproduce:**
It's happening while window resize() JS event. I did Browser Search Using ctrl + f

**Current behavior:**
Error:
TypeError: self.stop is not a function

https://www.odoo.com/web/content/24379050-9cdbb93/1/web.assets_frontend_lazy.js:867
Traceback:
start/this.checkIfSearch@https://www.odoo.com/web/content/24379050-9cdbb93/1/web.assets_frontend_lazy.js:867:343
dispatch@https://www.odoo.com/web/content/24379047-a36ee8b/1/web.assets_common_lazy.js:925:447
add/elemData.handle@https://www.odoo.com/web/content/24379047-a36ee8b/1/web.assets_common_lazy.js:911:166

Debug Details:
{…}
​
"openerp_apps.portal": Object { dependencies: (1) […], name: "openerp_apps.portal", rejected: "DOM doesn't contain '.o_redeem_info'", … }
​
"openerp_enterprise.databases": Object { dependencies: (6) […], name: "openerp_enterprise.databases", rejected: "DOM doesn't contain `.odoo-oe-databases`", … }
​
"openerp_enterprise.github_access": Object { dependencies: (3) […], name: "openerp_enterprise.github_access", rejected: "DOM doesn't contain '.oe-github-access'", … }
​
"openerp_enterprise.start_trial": Object { dependencies: (5) […], name: "openerp_enterprise.start_trial", rejected: "Not on start page?", … }
​
"openerp_enterprise.upgrade": Object { dependencies: (3) […], name: "openerp_enterprise.upgrade", rejected: "DOM doesn't contain 'div.oe_self_page'", … }
​
"openerp_french_certification.french_certification": Object { dependencies: (3) […], name: "openerp_french_certification.french_certification", rejected: "\".french-certification-widget,.loading-screen\" not present in DOM", … }
​
"openerp_website.enterprise_download": Object { dependencies: (2) […], name: "openerp_website.enterprise_download", rejected: "DOM doesn't contain `#oe_download_modal`", … }
​
"openerp_website.issues": Object { dependencies: (3) […], name: "openerp_website.issues", rejected: "DOM doesn't contain 'form[action='/help/submit']'", … }
​
"openerp_website.o_exp_2017": Object { dependencies: (1) […], name: "openerp_website.o_exp_2017", rejected: "DOM contains '#o_xp_bg_video'", … }
​
"website.set_view_track": Object { dependencies: (2) […], dependents: [], name: "website.set_view_track", … }
​
"website_slides_forum.editor": Object { dependencies: (2) […], dependents: [], name: "website_slides_forum.editor", … }

**Expected behavior:** 

It should not block the user from searching or doing client activities.

**Video/Screenshot link (optional):**
![image](https://user-images.githubusercontent.com/24998694/74603007-2e60d280-50c8-11ea-8a60-6fce4224a785.png)

**Comment by pedrobaeza** [comment] 2020-02-16 19:13
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by pedrobaeza** [comment] 2020-02-16 19:14
Take into account that master branch is a development branch. Latest one should be 13.0.

**Comment by hilarak** [comment] 2020-02-17 06:26
@pedrobaeza This has actually happened while I am using Odoo Forum. https://www.odoo.com/forum/help-1
Maybe this is not the place to submit the Forum issues. I am not sure. You can close the issue if I am in wrong place.

**Comment by Yenthe666** [comment] 2020-02-17 07:12
Yeah its confirmed:
![image](https://user-images.githubusercontent.com/6352350/74631416-361e8680-515d-11ea-8d53-973461390b2c.png)


@JKE-be can you let somebody check it?

**Comment by Yenthe666** [comment] 2020-02-17 07:13
We also *still* can't remove the accepted answer or move it to another answer. This has been reported like a dozen times through several channels.

**Comment by JKE-be** [comment] 2020-02-17 09:41
> Steps to reproduce:
> It's happening while window resize() JS event. I did Browser Search Using ctrl + f

heu, perso, I cannot reproduce. Connected as user or as portal...
So if I that to call "window resize() JS " I just need to resize my browser.

It seems that it is fixed meanwhile, or that the bug was a problem of cache.

For the "still can't remove the accepted answer ", seems like already broken in 12 on runbot, fature removed by error in first website refactoring of forum. And feature not add by second refactoring of designer. So yes, feature is still missing.

**Closed** 2020-02-17 09:46 UTC
Labels: 13.0, Website
