### ISSUE TITLE
Hyperlink errror

### ISSUE THREAD

**Issue by daydinodakent** [odoo/odoo#39745] opened 2019-11-04 13:34 UTC
Impacted versions: 13

Steps to reproduce:

Current behavior: I can't add a hyperlink to any picture object.

Expected behavior: I should add any hyperlink to a picture object.

Video/Screenshot link (optional):
![resim](https://user-images.githubusercontent.com/29478810/68124616-da6b1d00-ff20-11e9-9c1f-cd3cbedc20fd.png)

**Comment by pedrobaeza** [comment] 2019-11-04 14:14
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Yenthe666** [comment] 2019-12-03 08:05
Hi there,

Since we haven't gotten any feedback in a while I'm closing off this issue.
Don't hesitate to respond back with more information. We'll reopen the issue if there is enough information to explain this issue.

Regards,
Yenthe

**Closed by Yenthe666** 2019-12-03 08:05 UTC
Labels: Need information
