### ISSUE TITLE
[Bug] Account Voucher: Reconciling Logic fails when matching Invoice amount is found

### ISSUE THREAD

**Issue by deepa4lok** [odoo/odoo#4083] opened 2014-12-07 08:19 UTC
I came across another issue in voucher logic, w.r.t. variable called "move_lines_found"

Consider Customer X, has the following transactions with us.
Invoice (Inv - 01) of amount INR 1000
Invoice (Inv - 02) of amount INR 2000
Refund (CN - 01) of amount INR 2000 (refunded Inv - 02)

Now am going to create a customer payment of INR 1000
We all know, Credit side amount allocations are automatically adjusted with debit enties if exists...

So in this case, amount received is 1000, and there exists a refund (debit) of 2000, so which should make Customer X's account fully reconciled/payment adjusted..

![voucher_issue](https://cloud.githubusercontent.com/assets/8802906/5330408/9918b62c-7e16-11e4-94c8-891c68847ad2.png)

However If you see the above pic, when paid amount is entered as 1000, it found the Invoice which matches the amount and allocated the same, whereas it didn't proceed with allocating the debit amount of (2000) to another record (Inv-02)

Note: If I enter if lesser or greater than 1000, (i.e if it didn't find any matching record for the entered amount) then allocation happens correctly, 

As you can see it in this pic
![voucher_issue2](https://cloud.githubusercontent.com/assets/8802906/5330411/39167fa6-7e17-11e4-9839-0c10650a6c53.png)

**Comment by Yenthe666** [comment] 2017-12-08 10:37
Hi @deepa4lok ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: Pretty much a duplicate of your other report at https://github.com/odoo/odoo/issues/4082 too.

Regards,
Yenthe

**Closed by Yenthe666** 2017-12-08 10:37 UTC
Labels: Accounting
