### ISSUE TITLE
Viewing Quotation Template through mail always requires Odoo Login

### ISSUE THREAD

**Issue by AlfiiKazii** [odoo/odoo#40668] opened 2019-11-22 06:38 UTC
Impacted versions:
Odoo 12 Community
Steps to reproduce:

Current behavior:
When a Sales Ordrer Quotation Template is sent to the customer through an email,the customer is unable to view the template the very first time ,if the user is not logged into Odoo.
However,if before opening the link sent through an email,if user has logged into Odoo even once through the browser,it does allow.
Once cookies are deleted,404 error is raised.
Error being raised on terminal:
GET /my/orders/24?access_token=8398810a-b886-401d-9824-3e817f9bbfe5& HTTP/1.1" 404 - 1 0.002 0.035

Expected behavior:
User should be able to view the Quotation Template even if user is not logged in into Odoo.

Video/Screenshot link (optional):
![template_preview](https://user-images.githubusercontent.com/48550902/69403327-4a024a00-0d20-11ea-8e4a-0368259810b7.png)
![url](https://user-images.githubusercontent.com/48550902/69403344-525a8500-0d20-11ea-9154-51e425488117.png)

**Comment by pedrobaeza** [comment] 2019-11-22 08:38
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by AlfiiKazii** [comment] 2019-11-22 10:08
Hello Pedro M. Baeza,
Thanks for your reply.I emulated the issue at runbot as well,the issue is
replicated.I am hereby attaching the video to better understand the
issue.Sales Order Quotation is sent through email,Before opening the link
the user has not logged in into Odoo.Now when I click on Sign & Pay
online,it shows URL not found,as user has not logged in into Odoo.

Thanks,

*Kazi Alfiya*
Jr. Software Engineer
Certified Python Developer
Python for Data Science
<https://courses.cognitiveclass.ai/certificates/1db4cf138d954098a53f6c62cbf5cc0b>
Data Analysis with Python
<https://courses.cognitiveclass.ai/certificates/cfffd03fac024310852b68584a39c7c0>
*Pragmatic Techsoft Pvt. Ltd*

**Comment by AlfiiKazii** [comment] 2019-11-22 10:14
Hello,
Please have a look over the video attached,Quotation Template  Link does not open up as user is not logged in with Odoo.Issue persists on runbot as well.
![url_unaccessible](https://user-images.githubusercontent.com/48550902/69417492-c60b8a80-0d3e-11ea-9221-b90fdb10de7f.gif)

Thanks

**Comment by Yenthe666** [comment] 2019-11-22 10:22
Well, the runbot has two db's and the unique link does not keep track of the db's. Odoo cannot differantiate those so the request gives a 404.
You just need a db-filter / one db ;)

**Comment by AlfiiKazii** [comment] 2019-11-22 10:46
I wanted to convey that we have Production server with muti database
environment,and there it is not possible to add db filter.
Can you suggest any other solution in order to resolve this?

Thanks,

*Kazi Alfiya*
Jr. Software Engineer
Certified Python Developer
Python for Data Science
<https://courses.cognitiveclass.ai/certificates/1db4cf138d954098a53f6c62cbf5cc0b>
Data Analysis with Python
<https://courses.cognitiveclass.ai/certificates/cfffd03fac024310852b68584a39c7c0>
*Pragmatic Techsoft Pvt. Ltd*

**Comment by Yenthe666** [comment] 2019-11-22 12:55
There simply isn't. You'll need a db-filter or separated databases or it will keep giving 404's as far as I'm aware. @pedrobaeza anything you can add?

**Comment by pedrobaeza** [comment] 2019-11-22 13:36
Yeah, clearly the problem is a not proper deployment, as an URL should be unique to only one DB, doing through DB filter or having only one DB in that Odoo instance. That's a requirement and you should change your deployment method to comply with it.

Closing by the stated above.

**Closed by pedrobaeza** 2019-11-22 13:36 UTC
Labels: Need information
