### ISSUE TITLE
How can i print a message when a home page is loaded using widget in odoo10?? 

### ISSUE THREAD

**Issue by nidhinmmohan** [odoo/odoo#18124] opened 2017-07-10 11:37 UTC
Impacted versions: Odoo 10.0

Steps to reproduce:
I'm a beginner and i was writing java script code on odoo10.0. I referred codes that written previous versions. So, I want to print 'Nidhin, your pet store home page loaded' when my home page is loaded. 

Current behavior:
In mypetstore/static/src/js/my_pet_store.js:
mypetstore is my module name . 

odoo.define('mypetstore.my_pet_store', function (require) {
	"use strict";
	var Class = require('web.Class');
	var Widget = require('web.Widget');
	var core = require('web.core');
	var utils = require('web.utils');
	
	var _t = core._t;
        var _lt = core._lt;
        var QWeb = core.qweb;
     console.log("Nidhin");
    HomePage = Widget.extend({
	    start: function() {
	        console.log("Nidhin, your pet store home page loaded");
	    },
	});
	core.view_registry.add('my_pet_store', HomePage);
});

In mypetstore/views/my_pet_store.xml  

<odoo>
    <data>
      
        <template id="assets_backend" name="petstore" inherit_id="web.assets_backend">
            <xpath expr="." position="inside">
                <script type="text/javascript" src="/mypetstore/static/src/js/my_pet_store.js"></script>
            </xpath>
		</template>	

         <record id="action_home_page_my_petstore" model="ir.actions.client">
            <field name="name">Pet Store Home</field>
            <field name="tag">my_pet_store</field>
        </record> 
            .......
           ........
            ........
</data>
</odoo>
In menu:
<odoo>
	<data>
		<menuitem id="main_my_petstore_menu"
				 name="My Pet Store 10" />
				 
        <menuitem id="my_petstore_menu" 
        		name="Pet Store"
            	parent="main_my_petstore_menu" />
            
        <menuitem id="home_page_my_petstore_menu" 
        		name="Home Page"
        		parent="my_petstore_menu"
            	action="action_home_page_my_petstore"/>
            
	</data>	 
</odoo>

In custom_addons/mypetstore/__manifest__.py:

'depends': [
        'web',
    ],
    'data': [ 
        'views/my_pet_store.xml',
        'views/menu.xml',
    ],
    'demo': [
    ],

Expected behavior:

I have seen same code in openerp(previous version):

openerp.oepetstore = function(instance, local) {
    var _t = instance.web._t,
        _lt = instance.web._lt;
    var QWeb = instance.web.qweb;

    local.HomePage = instance.Widget.extend({
        start: function() {
            console.log("pet store home page loaded");
        },
    });

    instance.web.client_actions.add('petstore.homepage', 'instance.oepetstore.HomePage');
}

So, I want to print 'Nidhin, your pet store home page loaded' when my home page is loaded.

Video/Screenshot link (optional):

![screenshot from 2017-07-10 17-01-07](https://user-images.githubusercontent.com/12710988/28016336-8fdc7ed0-6591-11e7-807e-091cf26002e7.png)

**Comment by Yenthe666** [comment] 2017-07-10 12:36
Hi @nidhinmmohan,

Thank you for your bug report.
The Github issue tracker however is only for bugs, it is not the place to ask questions. We have the Odoo help forums for that (http://odoo.com/help), please ask your question there as there are plenty of people that can help you there.
Closing as this is not a bug but a question.

Regards,
Yenthe

**Closed by Yenthe666** 2017-07-10 12:36 UTC
