### ISSUE TITLE
Opening Email Marketing Mailing Lists Throws Syntax Error

### ISSUE THREAD

**Issue by emaxet** [odoo/odoo#28813] opened 2018-11-19 19:31 UTC
**Impacted versions:**
12

**Steps to reproduce:**

Open Email Marketing > Mailing Lists > Mailing Lists

**Current behavior:**

Throws a syntax error (Stack Trace Posted Below)

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/api.py", line 1032, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7f3a4f18c6d8>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/fields.py", line 970, in __get__
    value = record.env.cache.get(record, self)
  File "/home/odoo/src/odoo/odoo/api.py", line 1034, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('mail.mass_mailing.list(1,).contact_nbr', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/src/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/src/odoo/odoo/http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 938, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 904, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 926, in do_search_read
    offset=offset or 0, limit=limit or False, order=sort or False)
  File "/home/odoo/src/odoo/odoo/models.py", line 4524, in search_read
    result = records.read(fields)
  File "/home/odoo/src/odoo/odoo/models.py", line 2768, in read
    values[name] = field.convert_to_read(record[name], record, use_name_get)
  File "/home/odoo/src/odoo/odoo/models.py", line 5047, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/odoo/src/odoo/odoo/fields.py", line 974, in __get__
    self.determine_value(record)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1085, in determine_value
    self.compute_value(recs)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1041, in compute_value
    self._compute_value(records)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1032, in _compute_value
    getattr(records, self.compute)()
  File "/home/odoo/src/odoo/addons/mass_mailing/models/mass_mailing.py", line 125, in _compute_contact_nbr
    ''')
  File "/home/odoo/src/odoo/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: syntax error at or near "%"
LINE 7: ...in mail_blacklist bl on (LOWER(substring(c.email, %s)) = bl....
                                                             ^
**Expected behavior:**

Open up a list view of mailing lists.

**Comment by pedrobaeza** [comment] 2018-11-20 08:34
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile or it's a misconfiguration problem, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-11-20 08:34 UTC
