### ISSUE TITLE
OnChange Handler not returning complete data

### ISSUE THREAD

**Issue by agenterp** [odoo/odoo#46284] opened 2020-02-25 23:36 UTC
Impacted versions: 

11.0 
12.0 
13.0

Steps to reproduce:

We have three models, lets call them:

1)Sale.Order

2)Sale.Order.Tour 
relevant field distance

3)Sale.Order.Line 
relevant fields:
sale_order_tour_id m2o
price (@api.depends(sale_order_tour_id.distance))) computed float

When we change the distance in webclient of the Sale.Order.Tour, the price will be propperly computed.

Current behavior:

The onchange method will not! return the computed result of the sale_order_line.

Expected behavior:

The diff between the snapshots in the onchange handler should contain the computed changes for the sale.order.line.

in v8 this was working! 

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2020-02-26 07:13
Unless you put the full example, the problem is not understandable.

**Comment by agenterp** [comment] 2020-02-26 09:56
@pedrobaeza thank's for your reply!

What shall i do best, create a demo module?

**Comment by pedrobaeza** [comment] 2020-02-26 10:19
You can share a code snippet exercising the problem, or a whole module

**Comment by agenterp** [comment] 2020-02-26 13:28
https://github.com/agenterp/onchangebug/tree/11.0

I created a demo module to show the problem

**Comment by agenterp** [comment] 2020-02-26 14:28
[onchange_video.zip](https://github.com/odoo/odoo/files/4256231/onchange_video.zip)

**Comment by agenterp** [comment] 2020-02-26 15:36
this works:
https://github.com/odoo/odoo/blob/8.0/openerp/models.py#L5905

this not:
https://github.com/odoo/odoo/blob/11.0/odoo/models.py#L5091

nor v12 v13

**Comment by gdgellatly** [comment] 2020-02-26 19:44
There is no method with an onchange decorator in your module. What do you expect to happen?

**Comment by agenterp** [comment] 2020-02-26 21:25
> There is no method with an onchange decorator in your module. What do you expect to happen?

Depends includes onchange...

**Comment by pedrobaeza** [comment] 2020-02-26 21:58
As said by @gdgellatly, this has nothing to do with onchanges. These are computed fields, in whatever version you want.

What I see incorrect is that you have put `force_save` in `price` field in the view. Another weird thing is to depend in `base_order_id.base_order_tour_ids`, while there's no code associated with that dependency.

**Comment by agenterp** [comment] 2020-02-26 22:10
> As said by @gdgellatly, this has nothing to do with onchanges. These are computed fields, in whatever version you want.
> 
> What I see incorrect is that you have put `force_save` in `price` field in the view. Another weird thing is to depend in `base_order_id.base_order_tour_ids`, while there's no code associated with that dependency.

Sorry, but depends always implies onchange😆

**Comment by pedrobaeza** [comment] 2020-02-26 22:15
Well, that depends on the internal implementation, which you shouldn't rely on. They are different concepts. Any way, why don't you try what I'm proposing?

**Comment by agenterp** [comment] 2020-02-26 22:20
> Well, that depends on the internal implementation, which you shouldn't rely on. They are different concepts. Any way, why don't you try what I'm proposing?

Force save is that it will be written in readonly. That’s needed in some cases. The problem is the new omchange handler wont return the diff😆

**Comment by pedrobaeza** [comment] 2020-02-26 22:22
`force_save` is a nonsense for computed fields without inverse.

**Comment by agenterp** [comment] 2020-02-26 22:50
Thats incorrect. If the value is computed in readonly it will not be written without this.

**Comment by agenterp** [comment] 2020-02-26 23:05
Nevertheless we Are not Talking about the issue but about a lot nonsense...

**Comment by pedrobaeza** [comment] 2020-02-27 01:22
About the `force_save`, I'm afraid you're wrong, but if you want to think that, be free to do it.

About the problem you depicted, the field is properly computed on save, and everything is working fine on backend. Why it doesn't update on screen? I suppose the question is on performance about crossed updates between several one2many and possible infinite recursions, but I let @rco-odoo to decide if this should be fixed or you have to find an alternative implementation.

**Comment by agenterp** [comment] 2020-02-27 06:08
> About the `force_save`, I'm afraid you're wrong, but if you want to think that, be free to do it.
> 
> About the problem you depicted, the field is properly computed on save, and everything is working fine on backend. Why it doesn't update on screen? I suppose the question is on performance about crossed updates between several one2many and possible infinite recursions, but I let @rco-odoo to decide if this should be fixed or you have to find an alternative implementation.

Pedro i Would say believe me it's correct.
But You dont have to believe, just make the cost line readonly and the Computed value will never we part of the write from the webclient. I played with it long enough.  Its a stange behaviour of the webclient, and some Kind of randomeness. From my point of view its a bug and it Was working in v8.

**Comment by pedrobaeza** [comment] 2020-02-27 07:17
My tests in local were with `force_save` removed and was working, so I was saying that with knowledge, but as said, you are free to put what you want in your code, as well as to fork the core with your own modifications (that's why it's open source).

**Comment by agenterp** [comment] 2020-02-27 07:45
> My tests in local were with `force_save` removed and was working, so I was saying that with knowledge, but as said, you are free to put what you want in your code, as well as to fork the core with your own modifications (that's why it's open source).

As said it will work unless the line is readonly. If You want recompute the price on distance change on readonly of the cost line You need it.

I know that i Can fork an fix it. But isnt the idea of oss community to push together the possibility of the shared framework?

So why dont We use our energy to discuss the Problem itselve?

**Comment by Yenthe666** [comment] 2021-03-06 14:19
Hi,

Sorry but Odoo V11 is no longer supported officially so we have to close this one.
Don't hesitate to update the ticket or create a new one if you can reproduce this in V12 and up though.

Regards,
Yenthe

**Closed by Yenthe666** 2021-03-06 14:19 UTC
Labels: 11.0, Framework
