### ISSUE TITLE
Wishlist: Ability to specify alternate foreign key within Many2many field, allowing for delegated/inherited M2M fields

### ISSUE THREAD

**Issue by tesserB** [odoo/odoo#13435] opened 2016-09-09 05:02 UTC
Impacted versions: All

Steps to reproduce:
Not technically the "[Diamond Problem](https://en.wikipedia.org/wiki/Multiple_inheritance#The_diamond_problem)", but close enough... [See example models, data, and demo.](https://github.com/tesserB/odoo/tree/master-diamond_problem-demo/diamond_problem)

[Abstracted Models](https://github.com/tesserB/odoo/blob/master-diamond_problem-demo/diamond_problem/models/actors.py)
[Demo](https://github.com/tesserB/odoo/blob/master-diamond_problem-demo/diamond_problem/demo/actor_demo.xml)
[Data](https://github.com/tesserB/odoo/blob/master-diamond_problem-demo/diamond_problem/data/race_selection.xml)

Current behavior:
A [ParseError](https://github.com/tesserB/odoo/blob/master-diamond_problem-demo/diamond_problem/log/stacktrace.txt#L34-L47) is thrown after the demo violates the constraint. This stems from the root of the issue, which is the way in which fields.Many2many.check_schema() [sets up constraints on the junction table](https://github.com/tesserB/odoo/blob/master-diamond_problem-demo/odoo/fields.py#L2252-L2277). If an additional slot were added to Many2many's  "slots"―or if something like "related_field" could be used as a means of allowing developers to specify an alternate model field/"inverse field"/fkey value to be stored within "[column1](https://github.com/tesserB/odoo/blob/master-diamond_problem-demo/odoo/fields.py#L2201)" of the junction table; and if this field could then be used as the constraint instead...

Expected Behavior:
N/A

Video/Screenshot link (optional):
[Detailed example](https://github.com/tesserB/odoo/tree/master-diamond_problem-demo/diamond_problem)

[Full Log](https://github.com/tesserB/odoo/blob/master-diamond_problem-demo/diamond_problem/log/full.log)

[Stacktrace](https://github.com/tesserB/odoo/blob/master-diamond_problem-demo/diamond_problem/log/stacktrace.txt)

Respectfully,
Cody K.

@rco-odoo

**Comment by dreispt** [comment] 2016-09-09 09:36
The explanation looks short and too technical.
Can you write a higher level conceptual explanation of the underlying issue?

**Comment by gdgellatly** [comment] 2016-09-09 09:51
@dreispt many2many fields don't work with abstract models (perhaps only if
all the m2m arguments are specified, doesn't appear he tested without, and
I suspect it probably works then) - short and high level enough.

**Comment by tesserB** [comment] 2016-09-09 11:37
@dreispt I expanded the doc string for you within the example [models](https://github.com/tesserB/odoo/blob/master-diamond_problem-demo/diamond_problem/models/actors.py).
![goofyreason](https://cloud.githubusercontent.com/assets/14143175/18385203/26e6e4fc-765d-11e6-9433-42d9318687cb.png)

DETAIL:  Key (partner_id)=(2) is not present in table **"dp_student".**
![goofyreason1](https://cloud.githubusercontent.com/assets/14143175/18385504/0ea645b6-765f-11e6-86ff-4aa6b8c03306.png)
Because there's only 1 student in the demo, but the demo record is for an "alumni" belonging on dp_alumni...
![goofyreason2](https://cloud.githubusercontent.com/assets/14143175/18385694/29035b50-7660-11e6-99bb-7979ed955a8d.png)

Indeed, @gdgellatly, "many2many fields don't work with abstract models" ―but take a look the example, because the reason is _silly_...

**Comment by dreispt** [comment] 2016-09-09 13:25
@gdgellatly Thanks, I wasn't aware of that.
@tesserB Try removing `race_ids` monay2many from the Actors model, to confirm it is the one causing the issue.

**Comment by tesserB** [comment] 2016-09-09 19:05
I know exactly what's causing it and so I don't have an "issue", in that
sense, sir. :-) I've opened it because it's an issue that needs solving,
not because I'm looking for ways around it, which is why I went through the
trouble of creating the demo module.

Respectfully,
Cody K.

**Comment by moylop260** [comment] 2016-09-13 17:20
FYI we had a similar case see: https://github.com/odoo/odoo/pull/13458

The case is:
 - Create module_b depends `model_x` adding a test creating a record of `model_x`
 - Create module_a depends `model_x` adding new field required with a `_defaults` (old api) for `model_x` in order to avoid a `not-null` from other modules.
 - Run `-i module_b --test-enable` all fine!
 - Run `-i module_a,module_b --test-enable` error `Not-Null`

**Comment by tesserB** [comment] 2016-09-23 09:49
I've got it, ladies and gentlemen ―and it's glorious lmao I've still got some refactoring/documentation to do, but I'll have the PR in ASAP...

![m2m_related_field](https://cloud.githubusercontent.com/assets/14143175/18781838/7dbb70f0-8151-11e6-8caf-c8aee70e9bb0.png)

**Comment by Yenthe666** [comment] 2016-10-03 09:48
Hi @tesserB,

I really like the effort that you're putting in this and your effort to try and improve Odoo. 👍  for that!
@odony and @xmo-odoo what do you guys think about this concept? Is it okay if I label this with wishlist?

**Comment by tesserB** [comment] 2016-10-13 17:12
@Yenthe666 Another example, maybe?
[DB Normalization, DRY'er Code, immediately. Simplified Interfaces, down the road.](https://gist.github.com/tesserB/a9cd38f71366d1dfbca4a71277669e84)

**Comment by odony** [comment] 2016-10-14 17:54
@tesserB Thanks for the comprehensive explanation and reproduction data.
I have to admit I haven't analyzed your use case in details yet. However it seems you're trying to define a many2many relationship in an abstract `Actor` model that is later inherited by other models.

IIRC this has been supported by the Odoo framework since version 6.1, but it requires an important precaution: you must not force the name of the m2m relationship table, nor any of the FK fields (`relation`, `column1` and `column2`). Instead, you must let the framework choose the names dynamically as needed (depending on the source model). Then it should work as expected.
In fact this is the [recommended way of defining m2m fields](https://www.odoo.com/documentation/9.0/reference/orm.html#openerp.fields.Many2many), all the time.

In your [sample code](https://github.com/tesserB/odoo/blob/master-diamond_problem-demo/diamond_problem/models/actors.py) you can simplify the declaration of the `race_ids` field as follows:

`race_ids = fields.Many2many(string='Race', comodel_name='dp.race')`

BTW, in general it is not recommended to over-specify your model fields (`required=False` is the default, `auto_join` is not supported on m2m fields, etc.)

Could you test the above change, and let us know whether this solves your issue or not?

Thanks!

**Comment by pedrobaeza** [comment] 2018-04-29 00:06
Closing as answered and no further response.

**Closed by pedrobaeza** 2018-04-29 00:06 UTC
Labels: Wishlist
