### ISSUE TITLE
Uncaught TypeError: Cannot read property 'translate' of undefined

### ISSUE THREAD

**Issue by YDandrew** [odoo/odoo#24535] opened 2018-05-03 01:40 UTC
Versions:11
/web.assets_backend.js:1412
I can not save quotation when i try to save it the window pop up with
Uncaught TypeError: Cannot read property 'translate' of undefined

**Comment by Yenthe666** [comment] 2018-05-03 05:54
Hi @YDandrew,

Thanks a lot for your bug report.
I've just tested quotations on the latest Odoo 11 and was unable to reproduce it.
Can you reproduce it after updating your whole Odoo environment or can you reproduce it on an official Odoo test instance at runbot.odoo.com?

Regards,
Yenthe

**Comment by Yenthe666** [comment] 2018-05-22 14:31
Hi there,

I'm closing this bug report as there has been no feedback in over two weeks.
If you can still reproduce it then please add extra information/screenshots and we'll look at it again.

Regards,
Yenthe

**Closed by Yenthe666** 2018-05-22 14:31 UTC
Labels: 11.0, Need information

**Comment by bitssg** [comment] 2018-07-06 12:51
Same error on Odoo (CE) v11 release 20180503

Issue appears related to using different languages in the system. In our case we switched the language for the superuser to en_us as a workaroudn for this issue - https://github.com/odoo/odoo/issues/19661

The error we get on sale orders is similar to OP's:

Error:
Uncaught TypeError: Cannot read property 'translate' of undefined

https://staging-00008.domain.com/web/content/696-d953d79/web.assets_backend.js:1403
Traceback:
TypeError: Cannot read property 'translate' of undefined
    at Object.<anonymous> (https://staging-00008.domain.com/web/content/696-d953d79/web.assets_backend.js:1403:730)
    at Object.<anonymous> (https://staging-00008.domain.com/web/content/420-fef7aee/web.assets_common.js:802:681)
    at fire (https://staging-00008.domain.com/web/content/420-fef7aee/web.assets_common.js:796:299)
    at Object.add [as done] (https://staging-00008.domain.com/web/content/420-fef7aee/web.assets_common.js:797:467)
    at Array.<anonymous> (https://staging-00008.domain.com/web/content/420-fef7aee/web.assets_common.js:802:649)
    at Function.each (https://staging-00008.domain.com/web/content/420-fef7aee/web.assets_common.js:625:767)
    at Object.<anonymous> (https://staging-00008.domain.com/web/content/420-fef7aee/web.assets_common.js:802:560)
    at Function.Deferred (https://staging-00008.domain.com/web/content/420-fef7aee/web.assets_common.js:803:194)
    at Object.then (https://staging-00008.domain.com/web/content/420-fef7aee/web.assets_common.js:802:525)
    at Class.saveRecord (https://staging-00008.domain.com/web/content/696-d953d79/web.assets_backend.js:1403:388)

**Comment by Yenthe666** [comment] 2018-07-06 13:00
@bitssg can you also reproduce it after updating your Odoo to the very last source code?

**Comment by bitssg** [comment] 2018-07-06 17:55
Thank you for the quick response @Yenthe666 

Yes, the issue is not resolved even with 20180706 release

**Comment by Yenthe666** [comment] 2018-07-06 19:58
You're welcome, happy to hear it is solved!
