### ISSUE TITLE
Install Python Library for Conekta Payment Acquirer

### ISSUE THREAD

**Issue by Uhub202** [odoo/odoo#71230] opened 2021-05-25 15:16 UTC
Impacted versions: Odoo v 13.0 hosted on Odoo SH.

Steps to reproduce: I bought the Conekta Payment acquirer app in apps.odoo.com. I have not been able to installed it in Odoo since it requires a python library of Conekta. I am not familiarized with installing external libraries and I am not sure how should I proceed. Is it directly from the Github repository? And how should I do it?

Current behavior: When trying to install the Conekta app in Odoo, an error message appears saying "Python library not installed: conekta"

Expected behavior: Be able to install the Payment Conekta app.

Video/Screenshot link (optional): <img width="1079" alt="Screen Shot 2021-05-25 at 10 16 42" src="https://user-images.githubusercontent.com/71733271/119523353-4ea72480-bd42-11eb-8ad7-dd1cfddeeb23.png">

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment] 2021-05-25 16:10
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2021-05-25 16:10 UTC
