### ISSUE TITLE
Ignored controller inheritance

### ISSUE THREAD

**Issue by RemiFr82** [odoo/odoo#39202] opened 2019-10-22 15:41 UTC
Impacted versions:
12.0 (maybe previous ones too)

Steps to reproduce:
Add a print() or a _logger.info() between the lines 12 and 13 of website_crm/controllers/main.py e.g. at the beginning of the website_form() method.

Current behavior:
The print() / _logger.info() is not displayed in the logs => which means the class / method inheritance is not working.

Expected behavior:
The print() / _logger.info() should be displayed in the logs => working inheritance

**Comment by pedrobaeza** [comment] 2019-10-22 15:48
Please expose a problem in Odoo core, not your suspicions. There can be multiple reasons why the logger are not "printed".

**Comment by Yenthe666** [comment] 2019-12-03 08:04
Hi there,

Since we haven't gotten any feedback in a while I'm closing off this issue.
Don't hesitate to respond back with more information. We'll reopen the issue if there is enough information to explain this issue.

Regards,
Yenthe

**Closed by Yenthe666** 2019-12-03 08:04 UTC
Labels: Need information

**Comment by Dogma11** [comment] 2020-01-03 14:20
Hi there,

I experienced the same problem, when i try to overload the website_form controller, but nothing happens, then i also tried to put explicit eval error (i.e. `"toto" + False`) on existing one and no traceback, nothing happened.

Step to reproduce : put toto at the beginning of the website_form method in website_crm/controller/main.

If this does not convince you, can you please show me the step to do a proper test of that case.

**Comment by Asmaa-Aly** [comment] 2020-08-03 20:34
I have the same issue and i want to know the solution.

**Comment by Dogma11** [comment] 2020-08-08 13:07
Hi since this thread was closed i've managed to found the reason of that bug, that was somehow due a class mixin with WebsiteForm and Home classe, properly inheriting from the http.Controller abstract class resolved the bugHope this can help.

Regards
