### ISSUE TITLE
[9.0]Unable to restore database: "Database name already exists"

### ISSUE THREAD

**Issue by treviser** [odoo/odoo#13450] opened 2016-09-11 11:38 UTC
Impacted versions:
Version 9.0c-20160805

Steps to reproduce:
Go to .../web/database/manager
Try to restore a database backup file created by the database manager

Current behavior:
Database cannot be restored, Error message "Database name already exists". This is fatal in a multi-database setup using dbfilter, because one has to deactivate the dbfilter, restart Odoo, delete the database, restore it and then to reactivate the dbfilter again and restart Odoo.

Expected behavior:
Database gets correctly restored.

Video/Screenshot link (optional):

**Comment by treviser** [comment] 2016-09-25 08:56
@Yenthe666 Could you have a look at this?

**Comment by Yenthe666** [comment] 2016-09-26 07:54
@mart-e this is something for you. :smile:

**Comment by treviser** [comment] 2016-12-02 07:58
@mart-e @Yenthe666 Any news on this?

**Comment by Yenthe666** [comment] 2016-12-02 08:20
Hmm @treviser this is one I can't personally answer but @mart-e and @JKE-be I think you guys can.

**Comment by mart-e** [comment] 2016-12-02 09:16
Hello,

I am not sure to get the issue. The problems lies in the fact that you have a conflict with the db filter and the name of the restored database?
I tested and got no issue as long as I put a name for a non-existant db.

Or do you get a "Database name already exists" error specifying a name that do not exists at the sql level?

Please gives more info like your filter and the names you are using.

**Comment by treviser** [comment] 2016-12-02 09:55
@mart-e 
Using the /web/database/manager it is not possible to restore a database which already exists. One has to delete the database first, before it is possible to restore it. This is not a real issue without dbfilter or as long as you have only one database. You just delete the corresponding database using the database manager and you are ok. But when you have dbfilter active in a productive environment, it is possible to delete a database using the database manager, but after that you do not have access to the database manager anymore because the dbfilter points into the nirvana. Therefore you can not restore a database anymore.
The restore function of the database manager should drop the existing database first before trying to restore it.

**Comment by mart-e** [comment] 2016-12-02 10:16
Right, I see. I think there is a misunderstanding in the terminology.
We mean "restore" in the way "recreate from backup" but you understand "restore" as "replace".

This feature could make sense but it is not what the restore button is intended.
Maybe we can find a different term that clarify this.

**Comment by treviser** [comment] 2016-12-02 10:31
@mart-e The discussion about the terminology might be of academic interest, but as soon as you have an Odoo deployment using dbfilter properly set up, you loose the ability to restore a database without taking a whole Odoo instance completely offline.

**Comment by mart-e** [comment] 2016-12-02 10:44
To sum up:

- changing the behaviour of the "restore" button to drop the db if it exists
=> not going to happen

- clarifying the name of the button
=> why not

- adding a new button to do so
=> new feature, could be useful for the maintenance indeed but need to be clear on what it will do, need a new wizard to explain

Also, on production environment, we usually not use this wizard to restore a backup. The wizard will quickly not work for big database or just take too much upload time.

**Comment by treviser** [comment] 2016-12-02 10:54
Thanks for the summary.
The first bullet was my intention. The second is nice, but does not help :-)

**Comment by odony** [comment] 2016-12-07 10:00
For the record, our "Backup" and "Restore" features are semantically similar to the `pg_dump` and `pg_restore` PostgreSQL commands which _create_ a backup and _restore_ a backup, respectively _from_ and _to_ whichever database name you like. `pg_restore` will never replace a database if it already existed, for the same reason we don't do it: this would carry a very high risk of mistake/data loss. If you really want to drop a database, you have to show your meaning explicitly by using the `Drop` menu.

In addition, even though the use of the database manager is heavily discouraged in production environments (at the very least, [it should be protected from external access](https://www.odoo.com/documentation/9.0/setup/deploy.html#security)) it should usually be possible to setup a `db-filter` that would work for your purpose.
Let's say I have deployed my database **"mydb"** on **mydb.mycompany.com** with **`--db-filter='^%d'`**. I can then restore a backup under the name **"mydb_recover"**, temporarily seeing 2 databases because they share the same prefix, and then drop the old **"mydb"** without having to change the `db-filter`. Next time I need to replace the database again I can swap the names around.
Of course YMMV depending on the naming scheme of your hosts and databases.

**Comment by pedrobaeza** [comment] 2018-04-29 00:11
Closing as answered.

**Closed by pedrobaeza** 2018-04-29 00:11 UTC
Labels: Functional review

**Comment by angerangel** [comment] 2019-06-22 15:03
Frankly it has no sense. Restore should:

- or delete and restore automatically
- or overwrite automatically

**Comment by Yenthe666** [comment] 2019-06-22 19:10
It's not a bug and what you suggest is extremely dangerous. Just one time of not paying attention or making a mistake could drop your production db.

**Comment by angerangel** [comment] 2019-07-06 05:49
So you think that is better that user has to connect to the server using terminal, delete manually the database halt and restart odoo (so he must know how to work with postgre and terminal), and then he can restore?
In every software when you restore, you delete/overwrite. **It's the standard practice.**
However at the present the interface in unusable. A solution must be found. If you are scared that to restore the wrong backup and loose all, an advice to backup prior to restore can be added.
The sense of the of a backup is that is a **backup**, so you don't loose anything.

**Comment by pedrobaeza** [comment] 2019-07-06 22:18
Odoo database manager allows to drop databases, so it's not any restriction. The restriction is to avoid the accidental overwritting. If you want to do that, just drop previous one and then restore.

**Comment by treviser** [comment] 2019-07-26 16:26
As this popped up in my notifications, I just wanted to thank for solving my original problem. Since at least Odoo 11, if not earlier, the database manager dialog has changed and it is now easily possible to drop a database and to recreate the same from a backup without having to remove the dbfilter from the conf file. That's great!
