### ISSUE TITLE
[9.0] Notification Email template is ignored from new message chatting for other languages.

### ISSUE THREAD

**Issue by JoshuaQ** [odoo/odoo#13426] opened 2016-09-08 07:59 UTC
Impacted versions:
9.0

Steps to reproduce:

Change the Settings\Email\Template with Spanish Language. Don´t ask the language but i check that change the template on Setting\Translate Terms. There are a row with translate field "mail.template,body_html" that change with the value that i put in the Settings\Email\Template .

In whatever form, click on "New Message" type email, put a message and "Send". 

Check in the inbox the mail i you can see that is not the template that i change in Settings\Email\Template 

But if you go to whatever form, click on "New Message" type email, put a message and click on "Edit" not in "Send" and send the email from the new window, then the spanish template is used.

Workaround:
Its to change the original template on db on mail_template table row 1 name = "Notification Email" and change the body_html. this change the quickly "Send" message.

**Comment by pedrobaeza** [comment] 2018-04-29 00:04
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-04-29 00:04 UTC
Labels: 9.0, Services
