### ISSUE TITLE
User avatar not saved at user creation

### ISSUE THREAD

**Issue by qtheuret** [odoo/odoo#1628] opened 2014-08-06 13:32 UTC
On the latest trunk (commit d71a21bfdb25b6db942d82830788cc165db7c844), when you create a new user, if you set an avatar on the user, then click on 'Save', the avatar is not saved.
If you set again the avatar on the already saved user, the avatar is saved.

Screencast of this issue : https://cloud.theuret.net/public.php?service=files&t=1c1a3518436f819ed107dfcf6748cefd

**Comment by Yenthe666** [comment] 2017-08-28 14:21
Hi @qtheuret,

Thanks a lot for your report. At this point the issue can no longer be reproduced and everything works fine now.
Closing this because it is no longer reproducable.

Regards,
Yenthe

**Closed by Yenthe666** 2017-08-28 14:21 UTC
