### ISSUE TITLE
edit webpage template in odoo website

### ISSUE THREAD

**Issue by mostafaala2** [odoo/odoo#75778] opened 2021-08-31 09:38 UTC
Impacted versions: 14

Steps to reproduce:
I  want to edit that template in odoo web
Current behavior:
facing this error
Traceback:
Error: Couldn't load css dependency: http://web/content/210-db0568a/1/website.assets_wysiwyg.css
    at HTMLLinkElement.<anonymous> (http://web/content/203-d71ab95/1/web.assets_common_lazy.js:4480:359)
    at HTMLLinkElement.dispatch (http://web/content/203-d71ab95/1/web.assets_common_lazy.js:1617:447)
    at HTMLLinkElement.elemData.handle (http://web/content/203-d71ab95/1/web.assets_common_lazy.js:1603:166)

Expected behavior:
open navigation bar to edit

**Comment by pedrobaeza** [comment] 2021-08-31 09:40
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by inst-sol4u** [comment] 2021-10-30 13:10
I faced the same issue with Odoo 15, but it was resolved once I connect my odoo instance to the Internet. The issue was that I was working offline!

**Closed** 2021-10-30 13:12 UTC
Labels: Need information
