### ISSUE TITLE
Display name for new payments is "False"

### ISSUE THREAD

**Issue by luisg123v** [odoo/odoo#30784] opened 2019-02-04 04:24 UTC
Impacted versions:
- 12.0

Steps to reproduce:
- Go to payments (Accounting -> customers -> Payments)a
- Create a new payment filling only the partner

Current behavior:
The record name is `False`, so the window title is also `False`.

Expected behavior:
The record name should be something more descriptive. For instance, in v11.0 it's "Draft Payment".

Video/Screenshot link (optional):
![Payment False](https://user-images.githubusercontent.com/19801181/52227618-a372b880-2875-11e9-9fbb-a6455b6f7330.png)

**Comment by Yenthe666** [comment] 2019-02-04 16:54
@qsm-odoo for you 🙏

**Comment by luisg123v** [comment] 2019-02-04 18:13
FYI @yaniaular @umiphos

**Comment by luisg123v** [comment] 2019-02-15 20:53
opw-1941698.

**Comment by william-andre** [comment] 2019-03-06 13:39
I can't reproduce
![image](https://user-images.githubusercontent.com/44770049/53885231-7e609980-401d-11e9-9fb5-4ff9a0b0f8ce.png)

Guess it has been fixed by the framework

**Comment by C3POdoo** [comment] 2019-04-11 14:11
Dear @luisg123v,

_This is an automated message._
This issue is linked to the Odoo support ticket opw-1941698 that has been closed.
We hope you got an answer to your issue.

If you believe the problem is not solved yet and would like to keep this issue open, please let us know to reopen it.

**Closed by C3POdoo** 2019-04-11 14:11 UTC
Labels: 12.0, Accounting, OE
