### ISSUE TITLE
[9.0] Purchase Order: Invoice status is still "Waiting invoices" when the verdor bill is received.

### ISSUE THREAD

**Issue by youzengjian** [odoo/odoo#9321] opened 2015-10-30 08:11 UTC
Impacted versions:  9.0

Steps to reproduce:
    1. Go to Purchase/Purchase/Requests for Quotation – Create a PO-->Confirm PO-->Create Vendor Bill.
    2. Go back to PO, the "Deliveries & Invoices" Tab shows that the "Invoice Status" is "Invoice Received".
    3. Click on "Set to Done" button.
    4. Then you will see the "Invoice Status" changes from "Invoice Received" to "Not purchased".

Current behavior:
    The "Invoice Status" is not correct when the verdor bill is received.

Expected behavior:
    The "Invoice Status" should keep "Invoice Received" when the verdor bill is received.

**Comment by guewen** [comment] 2016-11-01 11:00
I confirm I can reproduce this issue on Odoo 9.0.

**Comment by pedrobaeza** [comment] 2018-04-06 00:30
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-04-06 00:30 UTC
Labels: 9.0, Logistics
