### ISSUE TITLE
Clean Install returning error: Template 'website.new_content_loader' not found

### ISSUE THREAD

**Issue by lilywhiteweb** [odoo/odoo#70574] opened 2021-05-09 17:05 UTC
https://github.com/odoo/odoo/blob/3b8e1e0e30e4d7ec0eb4b1a4b3c4c54132028748/addons/website/static/src/xml/website.editor.xml#L147

Not sure if that line specifically is causing it, but on an older (2 moths old) version that I have locally I did not have this problem and it does not include this fix. I done a clean install and a git clone and as soon as I add the website module and try save the template it gives the error:

Error:

Traceback:
Error: QWeb2: Template 'website.new_content_loader' not found
    at Object.exception (http://x.x.x.x:8069/web/content/418-ac5f83a/1/web.assets_common_lazy.js:4295:7)
    at Engine._render (http://x.x.x.x:8069/web/content/418-ac5f83a/1/web.assets_common_lazy.js:4340:103)
    at Engine.render (http://x.x.x.x:8069/web/content/418-ac5f83a/1/web.assets_common_lazy.js:4336:151)
    at Class.start (http://x.x.x.x:8069/web/content/420-65607e0/1/website.assets_editor.js:64:21)
    at Class.prototype.<computed> [as start] (http://x.x.x.x:8069/web/content/418-ac5f83a/1/web.assets_common_lazy.js:4533:488)
    at http://x.x.x.x:8069/web/content/418-ac5f83a/1/web.assets_common_lazy.js:4859:13
    at async Promise.all (index 0)

**Comment by pedrobaeza** [comment] 2021-05-09 17:17
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by lilywhiteweb** [comment] 2021-05-09 19:01
I'll definitely get to test that through runbot and will report back my
findings.
I got this error on a clean install of odoo on a fresh Ubuntu droplet on
digital ocean. I did not install any modules other than sales and website
and followed the package installation instructions on the odoo website.

**Comment by lilywhiteweb** [comment] 2021-05-09 21:11
Haven't tried runbot yet, but to reproduce this simply do the following (I've tried it again on a clean droplet):
- Clean install of Ubuntu 20.04
- Install Odoo as per the Ubuntu packaged installer instructions
https://www.odoo.com/documentation/14.0/setup/install.html#debian-ubuntu
- Create DB and username in database manager page
- Install Sales Module (no issues)
- Install Website Module
- Select Loftspace as the template
- Error message will appear

**Comment by pedrobaeza** [comment] 2021-05-10 06:23
Loftspace is not something of Odoo core itself, but an isolated theme, so the problem should be there. Please report it at the shop.

**Comment by lilywhiteweb** [comment] 2021-05-10 06:33
A few things on this:
- Loftspace theme comes pre-installed on the Odoo Packaged Installation
- This happens with the default theme (and any other theme)
Have you tried to do a fresh installation of the packaged installer and the website module? It is not working.

**Comment by lilywhiteweb** [comment] 2021-05-10 06:47
Commenting out the following lines fixes this for me....Can you please follow the steps I outlined to repo this issue. I have taken the time to troubleshoot and report the issue...I hope you can take the time to try and fix this.

https://github.com/odoo/odoo/blob/3b8e1e0e30e4d7ec0eb4b1a4b3c4c54132028748/addons/website/static/src/js/menu/new_content.js#L70

https://github.com/odoo/odoo/blob/3b8e1e0e30e4d7ec0eb4b1a4b3c4c54132028748/addons/website/static/src/js/menu/new_content.js#L199

**Comment by pedrobaeza** [comment] 2021-05-10 06:57
@JKE-be do you consider this a problem of Odoo, the theme or deployment thing?

**Comment by JKE-be** [comment] 2021-05-10 07:00
Hello @pedrobaeza 

While we have no other way, yes, let's try here.

Thank you

**Comment by JKE-be** [comment] 2021-05-10 09:06
@lilywhiteweb 

Hello,

Seems like a problem of cache in you case.
If you clear your cache or use another url, it should work.
Or just try to edit the file `odoo/addons/website/static/src/xml/website.editor.xml`.

Their are no "bug" into the code.

**Closed by JKE-be** 2021-05-10 09:06 UTC
Labels: Need information

**Comment by lilywhiteweb** [comment] 2021-05-10 09:24
There is a bug in the code...I'm disappointed that the instructions/details have not been read. I have installed 2 clean droplets on digital ocean (meaning there can be no cache issues) and followed the instructions on the Odoo Installation website. I have also done the same on a local installation on my laptop and got the same results. If I edit out the culprit lines of code in the JS file it works fine for me.

**Comment by JKE-be** [comment] 2021-05-10 09:32
I'm disappointed that you think that I don't read your instructions/details.
I have read it, and reproduce it. I disable cache (using another domain) and it works.

Open your debugger console, and in Network panel check the checkbox "Disable cache" ...

While you open the debugger, you can also check the file website/static/src/xml/website.editor.xml
It should contains this website.new_content_loader template.

Cache is in browser not in server...
If you are using the same url/domain it will share the same cache...

KR

**Comment by vanderperre** [comment] 2022-07-15 17:36
perhaps this helps:
-- select * from ir_attachment where url like '/web/content/%-%/%.%';
delete from ir_attachment where url like '/web/content/%-%/%.%';

if not, try to run or update all with an addons path without your website_theme folder 

I am sure another error would appear ... , then you can make investigation ....
i.e. for me: the web designer has overwriten a basic odoo website template without taken into account the body tag
