### ISSUE TITLE
Deferred constraint violation exceptions not handled properly

### ISSUE THREAD

**Issue by elgow** [odoo/odoo#27697] opened 2018-10-11 18:50 UTC
Impacted versions: 11.0

Steps to reproduce:
This issue was reported by another user for 8.0 [here](https://github.com/odoo/odoo/issues/15395)   but was closed because 8.0 is no longer supported. I have reproduced the exact same error in 11.0. Since it is well described in the original 8.0 issue it is best to look there.

It should be noted that deferred constraints are the only kind that will work with sequence fields manipulated with the handle widget.

Current behavior:
Deferred constraint violation causes server disconnect

Expected behavior:
Expect the same ValidationError that would result from a non-deferred constraint violation. 

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2018-10-11 18:57
Although it's indeed reproducible on newer versions, this can't be solved due to a limitation on how ORM works, and commiting in the middle of the method is not the solution.

I let @rco-odoo to close the issue if "won't fix", but maybe he has something in mind to be changed on the framework.

**Comment by elgow** [comment] 2018-10-11 19:09
I agree that a commit in the middle of saving is not helpful. I hope, however, that the Odoo ORM won't make deferred constraints impossible because they are absolutely essential for a constraint on a sequence field used with the handle widget. Actually, they are essential for any transaction that includes modification of a constrained field on more than one related object in a transaction.  If this gets marked as "won't fix" then it would cement in place a fairly damaging restriction on the functionality of the underlying postgresql database that should at least be clearly spelled out in the documentation.

**Comment by pedrobaeza** [comment] 2018-10-11 19:12
Well, personally I don't consider this so constraining, and I have never faced this problem without being able to fix it saving in 2 steps, but it's indeed a problem.

**Comment by pedrobaeza** [comment] 2018-10-11 22:14
Well, I'm not putting a constraint over sequence field. I always rely on several order fields. In general, I would say that put that constraint is not a good idea. What is your use case for that?

**Comment by elgow** [comment] 2018-10-11 22:51
In my application that field value determines the identity of a medical sample in a run of a DNA sequencer. It is essential that it be unique to avoid possibly mixing up patients. The normal, and most reliable, way to do that is with a unique constraint in the DB. The case of swapping values under unique constraint is usually handled with deferred constraints in postgresql and other DBs. That's what the feature is there for. 

In actual fact, the deferred constraint works fine in Odoo apart from the fact that the code at odoo/sql_db.py:375 
```
    def commit(self):
        """ Perform an SQL `COMMIT`
        """
        result = self._cnx.commit()
        for func in self._pop_event_handlers()['commit']:
            func()
        return result
```
fails to put a try-except block around the `self._cnx.commit()` to trap the psycopg2.IntegrityException and convert it to something that can generate the ValidationException further upstream.

**Comment by elgow** [comment] 2018-10-11 23:08
Actually, I think it's worth noting that this problem will apply to _any_ postgresql exception that occurs during commit. The user-visible manifestation is server disconnect/reconnect and failure to save the record w/o any explanation. Since commit() is a significant thing it would seem worthwhile for Odoo code to catch errors throw by it  and display them in some meaningful way.

**Comment by pedrobaeza** [comment] 2018-10-12 00:01
For that case, I don't see the problem using the ir.sequence object for that an adding the unique constraint. But this has nothing to do with widget="handler".

**Comment by elgow** [comment] 2018-10-12 17:09
I'm not using ir.sequence, I'm using the reserved field "sequence" as documented [here](https://www.odoo.com/documentation/11.0/reference/orm.html#model-reference) under the heading **Reserved field names** with the handler widget just as the documentation says I should.

**Comment by elgow** [comment] 2018-10-12 17:39
The short explanation is that a DNA sample in the modern NGS sequencing process is only identified by its location in a processing plate. Each location has reagents that ligate one or two DNA tags to the sample which are then visible in the sequence data. The same tags are re-used in every run, so the ir.sequence field makes zero sense for this purpose. The layout of the processing plate for each run is designed via a UI in which the handle widget is extremely useful. 

Since I had to explain that I'll assume that you don't work in DNA sequencing. I'd ask that you leave the design of my application to me and focus on the problem at hand, which is that the Odoo DB code simply does not handle ANY exception thrown by the postgresql DB during commit.

**Comment by pedrobaeza** [comment] 2018-10-12 17:45
Indeed, I don't work with DNA, and indeed I'm not going to try to help you more, and as said, the problem is there very deep on how ORM works, so I doubt this can be fixed easily. If you don't want to use my suggestion of using ir.sequence (you can create one per each sample/tag/whatever), then I don't have any other useful thing to you.

**Comment by elgow** [comment] 2018-10-12 17:48
Having traced and examined the code I don't see that it's so hard to fix this in the ORM. A `try-except` block around the commit() call that would put the error into the returned `result` would be a good start.

**Comment by pedrobaeza** [comment] 2018-10-12 17:50
OK, if you think it's easy to fix it, propose a PR (this kind of change should be proposed against master branch, not stable ones), and contribute to make ORM stronger.

**Comment by elgow** [comment] 2018-10-12 17:51
I had rather hoped that the Odoo team would care enough to look at handling exceptions during `commit()`.

**Comment by pedrobaeza** [comment] 2018-10-12 17:58
OK, as you prefer.

**Comment by elgow** [comment] 2018-10-12 18:04
Perhaps we can get someone from Odoo, (@rco-odoo ?) to weigh in on whether they feel that the `commit()` call is important enough to warrant a `try-except` block. I'll stress again that w/o it Odoo can't support a deferred constraint on a field in a related record to handle multiple updates which are valid at the end of the transaction. The postgresql developers seem to think that's important enough to justify the deferred constraint  feature.

**Comment by C3POdoo** [comment] 2023-03-30 11:56
Dear @elgow,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._

**Closed by C3POdoo** 2023-03-30 11:56 UTC
Labels: Framework, 11.0, ORM

**Comment by elgow** [comment] 2023-03-30 16:27
Sadly I'm not working with Odoo at this time. I've proposed using Odoo to two different employers, but it was rejected both times. The fact that serious bug reports are just left to languish and then dismissed without serious consideration is very likely a factor in that.
