### ISSUE TITLE
[10.0] Crashed JS when `Close` modal window from one2many corresponding form

### ISSUE THREAD

**Issue by shepilov-vladislav** [odoo/odoo#15849] opened 2017-03-14 06:31 UTC
Impacted versions:
    - [x] 8.0
    - [x] 9.0
    - [x] 10.0
Steps to reproduce:
1) Create form with one2many tree(for ex. line1_ids)
2) Create form for model(from 1 step) contains another one2many field like <field name="line2_ids"/>
3) Open line from line1_ids
4) Click `Close` button
Current behavior:
Crashed JS with error
```
Uncaught Error: QWeb2 - template['ViewManager']: Runtime Error: TypeError: Cannot read property 'view' of undefined
```
Expected behavior:
Nothing, only close window

**Comment by Yenthe666** [comment] 2017-03-14 07:43
@ged-odoo this one is for you? 😉

**Comment by ged-odoo** [comment] 2017-03-16 12:51
This one is interesting, but I couldn't reproduce it in 10.0.  Could you give me more info? it looks like the step 2 is incomplete.

**Comment by Yenthe666** [comment] 2017-11-26 11:07
@shepilov-vladislav could you give more information please? Then @ged-odoo can look into it.

**Comment by Yenthe666** [comment] 2018-04-18 08:06
Closing as there has been no feedback in a few months.

**Closed by Yenthe666** 2018-04-18 08:06 UTC
Labels: 10.0, 9.0
