### ISSUE TITLE
[14.0] Mass e-mail editor does not allow dragging components to e-mail body

### ISSUE THREAD

**Issue by ossimantylahti** [odoo/odoo#65439] opened 2021-02-03 06:45 UTC
**Impacted versions**:
14.0 CE

**Steps to reproduce:** 
Using Windows 10 and and Chrome browser or MS Edge browser log in to Odoo server and create a new mass e-mail.
Try to drag components from right hand side component box to e-mail body

**Current behavior:**
Component is not picked up and cannot be dragged to e-mail body.

Strange enough: maximizing the browser (by pressing F11) before creating the mass e-mail fixes this. If you maximize the browser before creating the e-mail template, it works.

**Expected behavior:**
Expected that the components can be dragged from component box to the body and edited there.

**Video/Screenshot link (optional):**
https://www.youtube.com/watch?v=Xjcel_35Y3I

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment] 2021-02-03 06:48
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by ossimantylahti** [comment] 2021-02-03 06:57
Hi @pedrobaeza I can repeat the problem in Runbot. The steps to reproduce are following:
1. Go to e-mail marketing
2. Create new e-mail marketing message
3. Observe how the e-mail body and layout are messed up and you cannot drag components to the body
4. Discard e-mail
5. Press F11 to maximize the Chrome browser
6. Create new mass e-mail. Observe how it works as intended.

Here is a video capture of reproducing the error in Runbot:
https://youtu.be/zGNs0DCaeNw

There is actually error log in Google Chrome (Press F12, start recording, try to drag components to the e-mail body. The look for errors.

Chrome reports following:
```
web.assets_common.js:5040 Uncaught TypeError: Cannot read property 'contains' of undefined
    at Class._onSmoothDragStart (web.assets_common.js:5040)
    at HTMLDivElement.start (web.assets_common.js:5020)
    at $.<computed>.<computed>._trigger (web.assets_common.js:2083)
    at $.<computed>.<computed>._trigger (web.assets_common.js:2222)
    at $.<computed>.<computed>._trigger (web.assets_common.js:2053)
    at $.<computed>.<computed>._mouseStart (web.assets_common.js:2146)
    at $.<computed>.<computed>._mouseStart (web.assets_common.js:2053)
    at $.<computed>.<computed>._mouseDown (web.assets_common.js:2125)
    at $.<computed>.<computed>._mouseDown (web.assets_common.js:2053)
    at HTMLDivElement.<anonymous> (web.assets_common.js:2122)
_onSmoothDragStart @ web.assets_common.js:5040
start @ web.assets_common.js:5020
_trigger @ web.assets_common.js:2083
_trigger @ web.assets_common.js:2222
(anonymous) @ web.assets_common.js:2053
_mouseStart @ web.assets_common.js:2146
(anonymous) @ web.assets_common.js:2053
_mouseDown @ web.assets_common.js:2125
(anonymous) @ web.assets_common.js:2053
(anonymous) @ web.assets_common.js:2122
dispatch @ web.assets_common.js:1705
elemData.handle @ web.assets_common.js:1691
```

**Comment by pedrobaeza** [comment] 2021-02-03 06:59
OK, thanks, tagged.

**Comment by ossimantylahti** [comment] 2021-02-03 07:00
Google Chrome error log when trying to drag objects:
![image](https://user-images.githubusercontent.com/37711285/106710106-07dac680-65bb-11eb-9e0b-7e1e9ea3e279.png)

**Comment by ossimantylahti** [comment] 2021-02-03 07:01
Runbot layout is broken:
![image](https://user-images.githubusercontent.com/37711285/106710218-35277480-65bb-11eb-9a51-a58762960bd9.png)

Pressing F11 before creating the new mass e-mail, the layout works as intended:
![image](https://user-images.githubusercontent.com/37711285/106710281-4cfef880-65bb-11eb-8b10-1eeb2d0cc031.png)

**Comment by ossimantylahti** [comment] 2021-02-15 00:18
It seems that fix done on 12th Feb fixed this issue. Checked on Runbot at 14th Feb 2021


Subject | [FIX] mass_mailing,web_editor: content no under sidebar
-- | --
Date | 2021-02-12 16:32:37
Author | Nicolas Lempereur <nle@odoo.com>

**Comment by pedrobaeza** [comment] 2021-02-15 00:59
Great, closing then.

**Closed by pedrobaeza** 2021-02-15 00:59 UTC
Labels: 14.0, Marketing
