### ISSUE TITLE
Delete attribute in tree view cannot handle computed field

### ISSUE THREAD

**Issue by pfeliprada** [odoo/odoo#64761] opened 2021-01-19 16:51 UTC
Impacted versions: 13

Steps to reproduce:

**Cause of the Problem:**
1.) Created can_delete field under sale.order model
![Screenshot_1](https://user-images.githubusercontent.com/37857886/105064859-35524b00-5ab8-11eb-90db-13a5abb73fa5.png)

2.) Used the created field ('can_delete') in attribute delete in tree view to supposedly handle desired conditions
![Screenshot_6](https://user-images.githubusercontent.com/37857886/105066530-dc83b200-5ab9-11eb-99c3-daea5ee1f2ad.png)

3.) Update the custom module (No issues in logs)

4.) Tried opening the sale order tree view. Error occured!

**Other actions taken:**
1.) Did not used the created field instead I used the word "false" and 0. Worked just fine, delete button under action was removed. **However I need the created field to handle desired conditions in hiding the delete button in the tree view**.
2.) Tried using the word False(capital letter "F") same error occured with **The Problem**.

Current behavior:
1.) Tried opening the sale order tree view. Error occured!
![Screenshot_2](https://user-images.githubusercontent.com/37857886/105065230-9712b500-5ab8-11eb-950e-951a9a6de541.png)

Expected behavior:
1.) Delete button under action must be removed

Supporting screenshots and links that I find useful in using delete attribute:
Links:
https://www.odoo.com/documentation/13.0/reference/views.html
https://www.odoo.com/forum/help-1/how-to-remove-hide-the-delete-function-inside-the-more-button-by-role-group-131052

Screenshots:
![Screenshot_4](https://user-images.githubusercontent.com/37857886/105065999-74cd6700-5ab9-11eb-8236-410093e0d66d.png)
![Screenshot_5](https://user-images.githubusercontent.com/37857886/105066036-8151bf80-5ab9-11eb-8e9a-4a0a89ece6d9.png)

Any help and explanation is highly appreciated.

**Comment by pfeliprada** [comment] 2021-01-19 17:59
Work around:
1.) I used groups

Helpful links:
https://www.cybrosys.com/blog/how-to-create-security-group-odoo-13
https://stackoverflow.com/questions/59588723/hide-create-and-export-all-button-but-show-import-button-in-odoo13-tree-view

**Comment by pedrobaeza** [comment] 2021-01-19 18:11
This is not a bug, but a non existing feature. `delete` attribute must be 0 or 1, and this won't never be implemented, as the attribute for whole list not for a specific record that can be computed. If you want to limit per record, override `unlink` method and raise an exception if not applicable.

Closing thus.

**Closed by pedrobaeza** 2021-01-19 18:11 UTC
