### ISSUE TITLE
Can't add follwoers

### ISSUE THREAD

**Issue by Analogic2004** [odoo/odoo#46165] opened 2020-02-25 04:10 UTC
Impacted versions:
13.0
Steps to reproduce:
add Follower to Quotation
Current behavior:
Error:
Traceback:
Error: Failed to execute 'matches' on 'Element': 'event)"]' is not a valid selector.
    at getMatchedCSSRules (https://starfish.catalist-me.com/web/content/1190-1bb8460/web.assets_backend.js:2695:168)
    at https://starfish.catalist-me.com/web/content/1190-1bb8460/web.assets_backend.js:2719:266
    at applyOverDescendants (https://starfish.catalist-me.com/web/content/1190-1bb8460/web.assets_backend.js:2710:97)
    at styleToClass (https://starfish.catalist-me.com/web/content/1190-1bb8460/web.assets_backend.js:2719:189)
    at Class._fromInline (https://starfish.catalist-me.com/web/content/1190-1bb8460/web.assets_backend.js:2723:407)
    at Class._onLoadWysiwyg (https://starfish.catalist-me.com/web/content/1190-1bb8460/web.assets_backend.js:2723:644)
    at Class._onLoadWysiwyg (https://starfish.catalist-me.com/web/content/1185-b91308d/web.assets_common.js:3866:371)
    at https://starfish.catalist-me.com/web/content/1190-1bb8460/web.assets_backend.js:2672:259
Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2020-02-25 08:21
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by sswapnesh** [comment] 2020-02-25 14:41
Seems working fine on latest Runbot v13

**Comment by pedrobaeza** [comment] 2020-02-25 15:00
Yeah, seems so. Closing until further notice is given.

**Closed by pedrobaeza** 2020-02-25 15:00 UTC
Labels: Need information
