### ISSUE TITLE
"Add to Cart" button causes bad query and create multi quotations

### ISSUE THREAD

**Issue by TimLai125** [odoo/odoo#24853] opened 2018-05-23 03:49 UTC
**Impacted versions:**
11.0c

**Steps to reproduce:**
1. Make sure the cart is empty and no existing quotation
2. Add some products to the wishlist
3. Go to the wishlist page
4. Add the products to the cart with the "Add to Cart" button quickly
ref: https://drive.google.com/file/d/1F92-bXEcI1XS8-BNa4rwwPZecXJGNyY0/view

**Current behavior:**
SQL errors occur (bad query) and multiple quotations are being created.

_Log from Odoo_
```
2018-05-23 03:32:59,190 23098 ERROR ttest odoo.sql_db: bad query: b'UPDATE "res_partner" SET "last_website_so_id"=119,"write_uid"=1,"write_date"=(now() at time zone \'UTC\') WHERE id IN (3)'
ERROR: could not serialize access due to concurrent update
2018-05-23 03:32:59,191 23098 INFO ttest odoo.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.0874 sec...
2018-05-23 03:32:59,785 23097 INFO ttest werkzeug: 127.0.0.1 - - [23/May/2018 03:32:59] "POST /shop/cart/update_json HTTP/1.1" 200 -
2018-05-23 03:32:59,978 23098 INFO ttest werkzeug: 127.0.0.1 - - [23/May/2018 03:32:59] "POST /shop/cart/update_json HTTP/1.1" 200 -
2018-05-23 03:33:00,259 23097 INFO ttest werkzeug: 127.0.0.1 - - [23/May/2018 03:33:00] "POST /shop/cart/update_json HTTP/1.1" 200 -
2018-05-23 03:33:00,868 23097 INFO ttest werkzeug: 127.0.0.1 - - [23/May/2018 03:33:00] "POST /shop/cart/update_json HTTP/1.1" 200 -
2018-05-23 03:33:01,382 23097 INFO ttest werkzeug: 127.0.0.1 - - [23/May/2018 03:33:01] "POST /shop/cart/update_json HTTP/1.1" 200 -
2018-05-23 03:33:05,984 23098 INFO ttest werkzeug: 127.0.0.1 - - [23/May/2018 03:33:05] "GET /shop/cart?type=popover HTTP/1.1" 200 -
```

_Log from PostgreSQL_
```
2018-05-23 03:32:59.188 UTC [23433] tslai@ttest ERROR:  could not serialize access due to concurrent update
2018-05-23 03:32:59.188 UTC [23433] tslai@ttest STATEMENT:  UPDATE "res_partner" SET "last_website_so_id"=119,"write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (3)
```

![image](https://user-images.githubusercontent.com/27185427/40402350-a604cba0-5e7d-11e8-838d-e6b65075b682.png)

**Expected behavior:**
There should be only one quotation be created.

**Further Background**
- The actions are performed with latest version of Chrome (66.0.3359.181)
- The commit version of Odoo: 77aa313b141b9b4c79fa8e24ed0984a9d5c955fe
- PostgreSQL Version: 9.6.5

**Comment by TimLai125** [comment] 2018-05-23 03:56
I cannot reproduce the issue with Odoo runbot therefore I believe the issue is something related to my setup but I cannot figure it out.

Things that I have tried to adjust:
- Test with worker settings and without workers settings
- Increase the limit_memory_hard and limit_memory_soft of Odoo
- Adjust the postgresql.conf and try to increase the performance with https://pgtune.leopard.in.ua/#/
- Adjust the `synchronous_commit` in the PostgreSQL

If anyone has ever encountered similar issue, please let me know if you know what I should adjust in order to fix the issue.

**Comment by TimLai125** [comment] 2018-06-04 11:08
@Yenthe666 Hi, I have some tests on this issue. I found the issue appears less when I increase the `limit_memory_hard` and `limit_memory_soft`. However, I do not think it is reasonable to increase the spec of our server to overcome the issue. (The spec of the server: 2CPU and 4GB of memory)

May I know the mem spec of Odoo Runbot and the configuration of PostgreSQL?

**Comment by TimLai125** [comment] 2018-06-04 11:36
I have found a way to reproduce the issue with Odoo Runbot.

1. Register and login as a new portal user
2. Add a product to the wishlist
3. Check the "Add product to my cart but keep it in my wishlist" option on the wishlist page  (/shop/wishlist)
4. Press "Add to Cart" quickly
5. Check the backend and there should be like 2 sales orders are created.
![image](https://user-images.githubusercontent.com/27185427/40915413-89a7e040-682e-11e8-9a96-b4ed5e2e438d.png)

**Comment by Yenthe666** [comment] 2018-06-04 13:17
@TimLai125 the runbot has atleast 32GB RAM, I actually think 64GB.
As for the reproducable case: @JKE-be I summon you. 😉

**Comment by JKE-be** [comment] 2018-06-04 13:26
don't worry about the server resource.

Fix need to be done into the code. and only catch one click!

**Comment by TimLai125** [comment] 2018-06-06 11:39
@Yenthe666, Thank you for the information. 

@JKE-be, Thank you for the update, probably it is easier to reproduce on a low-spec environment. Please let me know once there are any further updates.

**Comment by TimLai125** [comment] 2018-06-12 08:55
OPW-1858080

**Comment by JKE-be** [comment] 2018-06-13 10:57
since, you open a ticket, I close it, to avoid 2 dev to work at the same time
Thanks for reporting

**Closed by JKE-be** 2018-06-13 10:57 UTC
Labels: 11.0, Website

**Comment by yostashiro** [comment] 2018-06-13 11:12
@JKE-be I don't like the practice of closing the ticket here just because it was reported in a OPW ticket. It deprives people of the visibility of what is happening/has happened with this issue unless you closely watch the commit history. Is this Odoo's official practice now to close GitHub issues when they are reported under OPW?

**Comment by JKE-be** [comment] 2018-06-13 12:52
Hello @yostashiro 

I don't like the practice of *opening* the *opw* for a minor bug, that cannot be reproduced easily, and that I already take the time to look, and say that I will try to fix it.

It is not like if the bug was blocking or that nobody answer to the PR.

With the support team, it is not the same flow. On GitHub, each team try to take a look on their issues, while the support team takes all type of issues, spent times to reproduce it, fix it if necessary, in some case come to the team to ask if it is valid, ... In this case, open an opw will not change anything except to ask to support team to do the same job than me, and that has been already done what is not really productive.

> Is this Odoo's official practice now to close GitHub issues when they are reported under OPW?

Not really, it is my choice in this case and I continue to think that it avoid losing more time on this small issue that has no critical impact except to create draft quotation. 
Now, just need to wait that Support team catch the ticket, reproduce it again, and fix it... There is nothing else to do with this issue so we can close this.

**Comment by yostashiro** [comment] 2018-06-13 13:34
@JKE-be Thanks for your comment. I don't know how you people work internally there, so I made comments based on what I can see.  We obviously reference GitHub issue in the OPW ticket, so didn't imagine there'd be such confusion/inconveniences within Odoo...

I understand how you see this a minor issue but it is rather critical for our customer who has implemented logic to archive the product when quotation is created.

**Comment by Yenthe666** [comment] 2018-06-14 08:51
@yostashiro from what I've noticed most of the Odoo support people (through odoo.com/help) do not look at Github or close the bug reports there. There doesn't seem to be a lot of communication between the two from what I see.

**Comment by TimLai125** [comment] 2018-06-19 09:35
@JKE-be Thank you for the commit. I have checked and believe the update will disable the user from pressing the "Add to Cart" button before the transaction complete.
However if the user clicks fast enough on "Add to Cart" of two products, there will be still a chance of encountering the concurrent update issue. I suggest we should disable all the "Add to Cart" buttons instead of the "clicked" one.
