### ISSUE TITLE
Application latency

### ISSUE THREAD

**Issue by ptlooping** [odoo/odoo#38283] opened 2019-10-09 12:59 UTC
Impacted versions: 10.0 Community

Steps to reproduce: validate a sale

Current behavior: response time 3 minutes (sometimes crash)

Expected behavior: response time 45 seconds

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2019-10-10 07:40
Sorry, but 10.0 is out of official support since the arrival of 13.0. Any way, this is out of scope of this issue tracker, as you have to check on your side the root causes of this. Probably bad third party code.

**Closed by pedrobaeza** 2019-10-10 07:40 UTC
