### ISSUE TITLE
Database creation error: 'res.users'

### ISSUE THREAD

**Issue by SalahAdDin** [odoo/odoo#30097] opened 2019-01-10 12:33 UTC
Impacted versions: 12.0

Steps to reproduce:
1. Lauch a new Odoo 12.0/Postgres 10.0 stack.
2. Go to the web.
3. Try to create a new database.

Current behavior:
![deepinscreenshot_seleccionar area_20190110153106](https://user-images.githubusercontent.com/5034215/50968735-08dcbf00-14ed-11e9-9163-85b6ed1f1842.png)

Expected behavior:
New database successfully created.

**Comment by pedrobaeza** [comment] 2019-01-10 12:35
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - and create new DB)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by SalahAdDin** [comment] 2019-01-10 12:44
odoo.conf:
```
[options]
dev_mode = all
addons_path = /mnt/extra-addons/ant
data_dir = /var/lib/odoo
admin_passwd = J5VcCfBuq/RomXsaHwNZ7lF9/7qxcmnj
load_language=tr_TR,es_CO
log_db = True
log_handler = [':WARNING','werkzeug:CRITICAL','odoo.service.server:INFO']
log_level = debug
logfile = /var/log/odoo/openerp-server.log
longpolling_port = 8072
max_cron_threads = 2
smtp_port = 1025
smtp_server = mailhog
timezone = Europe/Istanbul
without_demo = True
```

**Comment by SalahAdDin** [comment] 2019-01-10 12:45
compose file:
```
version: '3'
services:
    web:
        restart: always
        image: odoo:12.0
        networks:
            - odoo-network
        container_name: odoo.web
        ports:
        - "8069:8069"
        - "8072:8072"
        environment:
            - USER=odoo
            - PASSWORD=odoo12
            - WDB_NO_BROWSER_AUTO_OPEN=False
            - WDB_SOCKET_SERVER=debug
            - WDB_WEB_PORT=1984
            - WDB_WEB_SERVER=localhost
            - WERKZEUG_DEBUG_PIN=817580
        depends_on:
            - db
            - debug
            - mailhog
        volumes:
            - 'odoo-web-data:/var/lib/odoo'
            - './addons:/var/lib/odoo/addons/11.0'
            - './odoo/odoo.conf:/etc/odoo/odoo.conf'
    db:
        restart: always
        image: postgres:9.6
        networks:
            - odoo-network
        container_name: odoo.db
        environment:
        - POSTGRES_USER=odoo
        - POSTGRES_PASSWORD=odoo12
        - POSTGRES_DB=postgres
        - POSTGRES_EXTRA_OPTS= '--schema=public --blobs'
        - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
        - odoo-db-data:/var/lib/postgresql/data/pgdata
    db-admin:
        restart: always
        # restart: unless-stopped
        image: dpage/pgadmin4
        container_name: odoo.db_admin
        ports:
          - "5050:80"
        environment:
            - PGADMIN_DEFAULT_EMAIL
            - PGADMIN_DEFAULT_PASSWORD
        depends_on:
            - db
        networks:
            - odoo-network
    debug:
        image: kozea/wdb
        networks:
            - odoo-network
        container_name: odoo.debug
        ports:
            - "1984:1984"
    mailhog:
        image: mailhog/mailhog
        networks:
            - odoo-network
        container_name: odoo.mail
        ports:
            # Web service port.
            - "8025:8025"
            # SMTP port.
            # - "1025:1025"
volumes:
    odoo-web-data:
    odoo-db-data:
networks:
    odoo-network:
```

**Comment by SalahAdDin** [comment] 2019-01-10 12:59
It happens also either using demo or not.

**Comment by pedrobaeza** [comment] 2019-01-10 13:02
And on runbot?

**Comment by SalahAdDin** [comment] 2019-01-10 13:36
We need a master password for creating a new database.

**Comment by pedrobaeza** [comment] 2019-01-10 13:37
Well, OK, but I'm pretty sure this is not an Odoo problem. It's a deployment one.

**Comment by mutamizh** [comment] 2019-03-19 17:46
> Impacted versions: 12.0
> 
> Steps to reproduce:
> 
> 1. Lauch a new Odoo 12.0/Postgres 10.0 stack.
> 2. Go to the web.
> 3. Try to create a new database.
> 
> Current behavior:
> ![deepinscreenshot_seleccionar area_20190110153106](https://user-images.githubusercontent.com/5034215/50968735-08dcbf00-14ed-11e9-9163-85b6ed1f1842.png)
> 
> Expected behavior:
> New database successfully created.

I had the same problem. it's got fixed after setting correct addons path. Please check your addons path. If you wrongly mentioned it then the database will not be created. So the error will come.

**Comment by Yenthe666** [comment] 2019-04-09 06:20
Hi,

I've heard a few cases of people mentioning it happening when they had an invalid addons path setup. 
This really looks like a deployment platform. All our new installs and database creations are working fine (including runbot).
I'm closing this as we have no way to reproduce it. Don't hesitate to respond back if you have more information or found a good reproducable way.

Regards,
Yenthe

**Closed by Yenthe666** 2019-04-09 06:20 UTC
Labels: Need information

**Comment by Rafaellinos** [comment] 2019-10-23 14:14
It happened to me when I was running odoo12 locally, and it was because wrong addons path configuration. I solved by just reorganizing the folders and the paths.

**Comment by wnadobnik** [comment] 2020-01-04 12:10
@Rafaellinos  I'm facing the same problem. Could You maybe give some details on what kind of reorganization was necessary? Thank You in advance.

**Comment by microsound1** [comment] 2020-03-27 11:19
In my case one specific addon module caused the issue. Try to view the log and it will gives you hint about the module. As soon as I deleted that bad or outdated module from the addon folder, it created a new database without any problem.

**Comment by shurshilov** [comment] 2021-01-11 16:22
addons_path = C:\Program Files (x86)\Odoo 13.0\server\odoo\addons,C:\Users\chlen\Desktop\odoo,C:\Users\chlen\Desktop\bitbucket13,C:\Users\chlen\Desktop\brown_bear13
I had the following paths and had this error. I removed all paths except the base one and the base was created. Then, I added each of these paths and checked the modules, one modules from each folder and they connected. Perhaps the error is related to the path length? or with some kind of modules that break exactly during installation.

**Comment by mos1em** [comment] 2021-01-21 14:22
@shurshilov when you have a space in your path you have to put all the path between double quotes "path"
On windows just put every single path between double quotes
ex: addons_path = "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons","C:\Users\chlen\Desktop\odoo","C:\Users\chlen\Desktop\bitbucket13","C:\Users\chlen\Desktop\brown_bear13"

**Comment by macagua** [comment] 2022-07-07 18:45
In my case I had the same error, but I had correctly defined the correct addon paths, but I had a Syntax error in Python code, when I corrected that error, I was able to correctly create the Odoo database.
