### ISSUE TITLE
Less fields on the create form of the RMA pieces when you use a small device

### ISSUE THREAD

**Issue by estagumor** [odoo/odoo#46303] opened 2020-02-26 09:36 UTC
Impacted versions: 12.0

Steps to reproduce: Open your Odoo on a small device or use the development tools of the navigator to make your resolution 480x320. Go to the RMAs menu and click on the 'create' button. Go to pieces and click on the 'add' button. 

Current behavior: The field lot_id and others are not at the view. 

Expected behavior: The same fields must be showed. 

Video/Screenshot link (optional):
![screenshot-localhost_8079-2020 02 26-10_31_00](https://user-images.githubusercontent.com/19464609/75331670-68c62e80-5883-11ea-95f7-113067769465.png)
![Captura el 2020-02-26 a las 10 31 21](https://user-images.githubusercontent.com/19464609/75331690-72e82d00-5883-11ea-80f8-2006a34548d8.png)
![screenshot-localhost_8079-2020 02 26-10_31_45](https://user-images.githubusercontent.com/19464609/75331702-77144a80-5883-11ea-97bc-d66db11c39d6.png)

**Comment by pedrobaeza** [comment] 2020-02-26 13:04
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this. Little tip: check `web_responsive` module.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2020-02-26 13:04 UTC
