### ISSUE TITLE
[8.0] Printing Purchase RFQ does nothing

### ISSUE THREAD

**Issue by jbvidex** [odoo/odoo#4023] opened 2014-12-03 17:18 UTC
I updated to the 12/02 nightly build (odoo-8.0_5d58b55), and am unable to print Purchase RFQs.  Nothing happens in the browser - it just says, "Waiting for localhost..." forever.  If set to a PDF report, you get the spinning "Loading" icon forever.  This message appears in the Terminal window:

``> /usr/lib/python2.7/site-packages/odoo-8.0_5d58b55-py2.7.egg/openerp/addons/base/ir/ir_qweb.py(473)render_tag_field()
-> field = record._fields[field_name]``

Other forms, such as Sales Quotations, still print/load correctly.

**Comment by sle-odoo** [comment] 2015-12-09 14:55
Cannot reproduce, this bug should have been fixed in the meantime

**Closed by sle-odoo** 2015-12-09 14:55 UTC
