### ISSUE TITLE
[11.0 e] Cannot open Dahsboard

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#19995] opened 2017-10-10 07:16 UTC
Impacted versions: 11.0 e

Steps to reproduce: [http://269855-11-0-0dd370.runbot8.odoo.com](http://269855-11-0-0dd370.runbot8.odoo.com) --> Go to Main Dahsborad 

Current behavior: Throws traceback. 

Expected behavior: Should open Dahsboard.

Video/Screenshot link (optional): https://prnt.sc/gvhxl3

**Comment by Yenthe666** [comment] 2017-10-10 07:19
Hi @sswapnesh,

Thank you for your report. I can confirm that this is a bug:
![image](https://user-images.githubusercontent.com/6352350/31373883-03f760e4-ad9c-11e7-80e7-f2c7a47e5704.png)
@ged-odoo could you assign somebody on it?

Regards,
Yenthe

**Comment by ged-odoo** [comment] 2017-10-12 13:20
sorry, @sswapnesh I cannot reproduce this issue in version 11.0, community or enterprise.  The runbot link that you show is dead, so I had to try on a new database, and it works.

Do you have more detailed steps that could lead to this crash?  Something like adding a specific view to the dashboard?

**Comment by Yenthe666** [comment] 2017-10-12 13:22
I've just tested on the latest runbot too and it seems to be fixed in the meanwhile. @sswapnesh can you try again for us buddy?

**Comment by sswapnesh** [comment] 2017-10-12 14:02
I got new error. 

Steps to reproduce:[http://270780-11-0-04a110.runbot14.odoo.com](http://270780-11-0-04a110.runbot14.odoo.com) --> Go to Main Dashboard.  (First create dashboard for any object and than uninstall that module)

It will give `"server application error"` in console.

Same way it works in v10.

**Comment by ged-odoo** [comment] 2017-10-12 14:18
ah, I see. The dashboard code does not handle well the fact that the action does not exist anymore.  This is indeed a problem.

**Comment by sswapnesh** [comment] 2017-10-12 14:34
@Yenthe666  @ged-odoo  
Finally I generated the error Which I got previously

Steps to reproduce: [http://270871-11-0-055c03.runbot8.odoo.com](http://270871-11-0-055c03.runbot8.odoo.com)--> Add two Items to Dashboard. --> Delete one of  it and refresh.

Error:
Uncaught SyntaxError: Unexpected token o in JSON at position 1

```
http://270871-11-0-055c03.runbot8.odoo.com/web#id=&view_type=form&model=board.board&menu_id=104&action=111:1
Traceback:
SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at http://270871-11-0-055c03.runbot8.odoo.com/web/content/1898-e9ab4f4/web.assets_backend.js:599:86
    at Object.traverse (http://270871-11-0-055c03.runbot8.odoo.com/web/content/1892-8abbaad/web.assets_common.js:4018:320)
    at http://270871-11-0-055c03.runbot8.odoo.com/web/content/1892-8abbaad/web.assets_common.js:4018:368
    at Function._.each._.forEach (http://270871-11-0-055c03.runbot8.odoo.com/web/content/1892-8abbaad/web.assets_common.js:12:558)
    at Object.traverse (http://270871-11-0-055c03.runbot8.odoo.com/web/content/1892-8abbaad/web.assets_common.js:4018:331)
    at http://270871-11-0-055c03.runbot8.odoo.com/web/content/1892-8abbaad/web.assets_common.js:4018:368
    at Function._.each._.forEach (http://270871-11-0-055c03.runbot8.odoo.com/web/content/1892-8abbaad/web.assets_common.js:12:558)
    at Object.traverse (http://270871-11-0-055c03.runbot8.odoo.com/web/content/1892-8abbaad/web.assets_common.js:4018:331)
    at http://270871-11-0-055c03.runbot8.odoo.com/web/content/1892-8abbaad/web.assets_common.js:4018:368
```

**Comment by mge-odoo** [comment] 2017-11-17 10:34
Hi @sswapnesh 

Thanks for reporting the bug. I'm on this issue right now and I have tried to reproduce it but I'm not able to do so. Has it been fixed in the meanwhile? I have tried to add two actions in the Dashboard (i.e. Notes kanban view and My pipeline), on the last 11.0e but I don't get any traceback.

May I ask you to double check please?

Regards,

Martin

**Comment by mge-odoo** [comment] 2017-11-17 10:37
This issue may have been fixed by the following revision: https://github.com/odoo/odoo/commit/54d5678696e8ab8db3b67216a46802623ebef925

**Comment by Yenthe666** [comment] 2017-11-17 12:35
Yep - did another attempt and it looks like it is fixed.

**Closed by Yenthe666** 2017-11-17 12:35 UTC
Labels: 11.0, confirmed, Framework

**Comment by sswapnesh** [comment] 2017-11-17 17:18
@mge-odoo @Yenthe666 Actually There were two different issues here, One of them is resolved.

Still, there is one issue left here.

Steps to reproduce:[http://279257-11-0-ca3390.runbot11.odoo.com](http://270780-11-0-04a110.runbot14.odoo.com) --> Go to Main Dashboard. (First, create dashboard for any object and then uninstall that module)

In this Example I uninstalled Payroll.


![](https://image.prntscr.com/image/Tl9KTzX8S9i4__zn3seaJQ.png)

![](https://image.prntscr.com/image/XMtAwQB4Qh2k76rnWtkXDw.png)


There will be traceback in the console.

`Server application error {"code":200,"data":{"exception_type":"internal_error","arguments":[],"name":"werkzeug.exceptions.BadRequest","debug":"Traceback (most recent call last):\n  File \"/home/odoo/runbot/extra/runbot/static/build/279257-11-0-ca3390/odoo/http.py\", line 646, in _handle_exception\n    return super(JsonRequest, self)._handle_exception(exception)\n  File \"/home/odoo/runbot/extra/runbot/static/build/279257-11-0-ca3390/odoo/http.py\", line 307, in _handle_exception\n    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])\n  File \"/home/odoo/runbot/extra/runbot/static/build/279257-11-0-ca3390/odoo/tools/pycompat.py\", line 87, in reraise\n    raise value\n  File \"/home/odoo/runbot/extra/runbot/static/build/279257-11-0-ca3390/odoo/http.py\", line 683, in dispatch\n    result = self._call_function(**self.params)\n  File \"/home/odoo/runbot/extra/runbot/static/build/279257-11-0-ca3390/odoo/http.py\", line 315, in _call_function\n    raise werkzeug.exceptions.BadRequest(msg % params)\nwerkzeug.exceptions.BadRequest: 400: Bad Request\n","message":"400: Bad Request"},"message":"Odoo Server Error"}`

**Comment by Yenthe666** [comment] 2017-11-17 17:29
Hmm the second one looks like a bad cleanup. @mge-odoo could you have a look at that one please?

**Comment by mge-odoo** [comment] 2017-11-20 14:46
@Elkasitu In addition to this fix, I don't know if this is feasible but it should be a good idea to clean up the actions in board view when uninstalling a module, what do you think?

**Comment by Elkasitu** [comment] 2017-11-20 15:06
@mge-odoo I'm not sure but we can talk about it tomorrow if you'd like

**Comment by mge-odoo** [comment] 2017-11-20 16:53
A fix has been done in saas-16 and will soon be forward-ported in 11.0

Thanks for reporting the bug.

Regards,

Martin

**Comment by sswapnesh** [comment] 2017-12-14 17:18
Hello @ged-odoo, @mge-odoo,

I came across the same Situation in v10. (Not sure If it was working earlier or not.)
Just tested on [Runbot.](http://286312-10-0-e89fbb.runbot8.odoo.com/web?#view_type=form&model=board.board&action=117)

![](https://image.prntscr.com/image/z23zRwBoTTKET6jJ7QWZ9g.png)


First, create dashboard for any object and then uninstall that module
[Here](http://286312-10-0-e89fbb.runbot8.odoo.com/web?#view_type=form&model=board.board&action=117) I uninstalled Payroll module.

When you try to remove Item
![](https://image.prntscr.com/image/PvYIHipoSPmIAHaud8aSbA.png)

When you drag from bottom to top or vice versa.

![](https://image.prntscr.com/image/sVTj5Ms4RgCIOsIhmfpF2w.png)

**Comment by kharbat** [comment] 2018-02-05 21:10
I have the same problem, after adding a couple of blocks to the dashboard and trying to change the layout, I became unable to access the dashboard page again.

I tried the new Odoo 11 update,  and #54d5678   but I still get the error.

Attaching my JS console:

![screen shot 2018-02-06 at 12 07 48 am](https://user-images.githubusercontent.com/34914/35828851-1a2f36e6-0ad2-11e8-9627-f9bea02bde9e.png)
![screen shot 2018-02-06 at 12 07 37 am](https://user-images.githubusercontent.com/34914/35828885-2eb94a02-0ad2-11e8-99b4-a12e8965ef9b.png)

**Comment by Yenthe666** [comment] 2018-02-06 07:21
@kharbat can you reproduce it on an official Odoo test instance (at runbot.odoo.com)?
Could you please add `?debug=assets` in the URL and then paste the JavaScript output again? This should give more insight.
