### ISSUE TITLE
[11.0] Event search view uses datetime object, which is not imported

### ISSUE THREAD

**Issue by DR4RCON** [odoo/odoo#24663] opened 2018-05-10 08:32 UTC
Impacted versions: 11

Steps to reproduce: install current event version

Current behavior: javascript error, there is no datetime object

Expected behavior: no javascript errors

View with datetime object
https://github.com/odoo/odoo/blob/11.0/addons/event/views/event_views.xml#L376
Model
https://github.com/odoo/odoo/blob/11.0/addons/event/models/event.py#L10

**Comment by pedrobaeza** [comment] 2018-05-10 08:53
Hi, I'm not able to reproduce this problem in latest runbot version, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-05-10 08:53 UTC

**Comment by DR4RCON** [comment] 2018-05-10 08:58
Pedro please have a look into events.py the datetime object isnt imported, how can I use it in search view? both links point to same version.

**Comment by pedrobaeza** [comment] 2018-05-10 08:59
But I don't get what do you mean by "It's not imported". Please put the steps to reproduce the problem.

**Comment by pedrobaeza** [comment] 2018-05-10 09:12
You don't need that, as web client doesn't depend on that file for making the operations on filters.

**Comment by DR4RCON** [comment] 2018-05-10 09:12
```
<filter string="Upcoming" name="upcoming"
                        domain="['&amp;', ('state', '!=', 'cancel'), ('date_begin','&gt;=', datetime.datetime.combine(context_today(), datetime.time(0,0,0)))]" help="Upcoming events from today" />
```

This string from event.search view results in a javascript error:
```
Fehler:
Error: AttributeError: object has no attribute 'datetime'

http://pbc-obersteiger.tom-dev.de/web/static/lib/py.js/lib/py.js:757
Zurückverfolgung
__getattribute__@http://pbc-obersteiger.tom-dev.de/web/static/lib/py.js/lib/py.js:757:19
py.PY_getAttr@http://pbc-obersteiger.tom-dev.de/web/static/lib/py.js/lib/py.js:526:28
py.evaluate@http://pbc-obersteiger.tom-dev.de/web/static/lib/py.js/lib/py.js:1425:20
py.evaluate@http://pbc-obersteiger.tom-dev.de/web/static/lib/py.js/lib/py.js:1425:34
py.evaluate@http://pbc-obersteiger.tom-dev.de/web/static/lib/py.js/lib/py.js:1379:32
py.evaluate@http://pbc-obersteiger.tom-dev.de/web/static/lib/py.js/lib/py.js:1397:35
py.evaluate@http://pbc-obersteiger.tom-dev.de/web/static/lib/py.js/lib/py.js:1409:34
py.eval@http://pbc-obersteiger.tom-dev.de/web/static/lib/py.js/lib/py.js:1453:16
eval_domains/<@http://pbc-obersteiger.tom-dev.de/web/static/src/js/core/pyeval.js:884:39
_.forEach@http://pbc-obersteiger.tom-dev.de/web/static/lib/underscore/underscore.js:145:9
_.mixin/</_.prototype[name]@http://pbc-obersteiger.tom-dev.de/web/static/lib/underscore/underscore.js:1484:29
eval_domains@http://pbc-obersteiger.tom-dev.de/web/static/src/js/core/pyeval.js:875:5
pyeval@http://pbc-obersteiger.tom-dev.de/web/static/src/js/core/pyeval.js:986:16
stringToArray@http://pbc-obersteiger.tom-dev.de/web/static/src/js/core/domain.js:243:16
get_domain/domains<@http://pbc-obersteiger.tom-dev.de/web/static/src/js/chrome/search_inputs.js:632:24
_.collect@http://pbc-obersteiger.tom-dev.de/web/static/lib/underscore/underscore.js:164:24
_.mixin/</_.prototype[name]@http://pbc-obersteiger.tom-dev.de/web/static/lib/underscore/underscore.js:1484:29
get_domain@http://pbc-obersteiger.tom-dev.de/web/static/src/js/chrome/search_inputs.js:627:23
build_search_data/<@http://pbc-obersteiger.tom-dev.de/web/static/src/js/chrome/search_view.js:394:26
_.forEach@http://pbc-obersteiger.tom-dev.de/web/static/lib/underscore/underscore.js:145:9
Collection.prototype[method]@http://pbc-obersteiger.tom-dev.de/web/static/lib/backbone/backbone.js:956:14
build_search_data@http://pbc-obersteiger.tom-dev.de/web/static/src/js/chrome/search_view.js:392:9
start/def<@http://pbc-obersteiger.tom-dev.de/web/static/src/js/chrome/view_manager.js:152:25
then/</</<@http://pbc-obersteiger.tom-dev.de/web/static/lib/jquery/jquery.js:3276:86
fire@http://pbc-obersteiger.tom-dev.de/web/static/lib/jquery/jquery.js:3119:38
add@http://pbc-obersteiger.tom-dev.de/web/static/lib/jquery/jquery.js:3165:49
then/</<@http://pbc-obersteiger.tom-dev.de/web/static/lib/jquery/jquery.js:3275:57
each@http://pbc-obersteiger.tom-dev.de/web/static/lib/jquery/jquery.js:383:49
then/<@http://pbc-obersteiger.tom-dev.de/web/static/lib/jquery/jquery.js:3272:49
Deferred@http://pbc-obersteiger.tom-dev.de/web/static/lib/jquery/jquery.js:3332:25
then@http://pbc-obersteiger.tom-dev.de/web/static/lib/jquery/jquery.js:3271:48
start@http://pbc-obersteiger.tom-dev.de/web/static/src/js/chrome/view_manager.js:150:19
OdooClass.extend/</prototype[name]</<@http://pbc-obersteiger.tom-dev.de/web/static/src/js/core/class.js:90:35
__widgetRenderAndInsert/<@http://pbc-obersteiger.tom-dev.de/web/static/src/js/core/widget.js:206:20
then/</</<@http://pbc-obersteiger.tom-dev.de/web/static/lib/jquery/jquery.js:3276:86
fire@http://pbc-obersteiger.tom-dev.de/web/static/lib/jquery/jquery.js:3119:38
fireWith@http://pbc-obersteiger.tom-dev.de/web/static/lib/jquery/jquery.js:3231:49
updateFunc/<@http://pbc-obersteiger.tom-dev.de/web/static/lib/jquery/jquery.js:3360:49
fire@http://pbc-obersteiger.tom-dev.de/web/static/lib/jquery/jquery.js:3119:38
fireWith@http://pbc-obersteiger.tom-dev.de/web/static/lib/jquery/jquery.js:3231:49
then/</</<@http://pbc-obersteiger.tom-dev.de/web/static/lib/jquery/jquery.js:3283:73
fire@http://pbc-obersteiger.tom-dev.de/web/static/lib/jquery/jquery.js:3119:38
fireWith@http://pbc-obersteiger.tom-dev.de/web/static/lib/jquery/jquery.js:3231:49
then/</</<@http://pbc-obersteiger.tom-dev.de/web/static/lib/jquery/jquery.js:3283:73
fire@http://pbc-obersteiger.tom-dev.de/web/static/lib/jquery/jquery.js:3119:38
fireWith@http://pbc-obersteiger.tom-dev.de/web/static/lib/jquery/jquery.js:3231:49
then/</</<@http://pbc-obersteiger.tom-dev.de/web/static/lib/jquery/jquery.js:3283:73
fire@http://pbc-obersteiger.tom-dev.de/web/static/lib/jquery/jquery.js:3119:38
fireWith@http://pbc-obersteiger.tom-dev.de/web/static/lib/jquery/jquery.js:3231:49
done@http://pbc-obersteiger.tom-dev.de/web/static/lib/jquery/jquery.js:9275:33
callback@http://pbc-obersteiger.tom-dev.de/web/static/lib/jquery/jquery.js:9685:57
```

**Comment by DR4RCON** [comment] 2018-05-10 09:25
Can you please link the one you have used?

**Comment by pedrobaeza** [comment] 2018-05-10 09:29
I'm opening events and using that filter without problems. That's why I ask you for detailed steps to reproduce the problem.

**Comment by DR4RCON** [comment] 2018-05-10 09:42
Have nothing done, but installed events in a customer database. But that database has no records for events as it has a demo. The problem also appears, when uninstall the module and make a fresh install.

Installed modules:
```
Project | project | Odoo S.A. | 11.0.1.1 | Installiert
-- | -- | -- | -- | --
  | Sales Management | sale_management | Odoo S.A. | 11.0.1.0 | Installiert
  | Sale & Purchase Vouchers | account_voucher | Odoo S.A. | 11.0.1.0 | Installiert
  | Discuss | mail | Odoo S.A. | 11.0.1.0 | Installiert
  | Invoicing | account | Odoo S.A. | 11.0.1.1 | Installiert
  | Rechnungsstellungs-Management | account_invoicing | Odoo S.A. | 11.0.1.0 | Installiert
  | Productivity | note | Odoo S.A. | 11.0.1.0 | Installiert
  | Website Builder | website | Odoo S.A. | 11.0.1.0 | Installiert
  | Employee Directory | hr | Odoo S.A. | 11.0.1.1 | Installiert
  | Account Bank Statement Import | account_bank_statement_import | Odoo S.A. | 11.0.1.0 | Installiert
  | Analytic Accounting | analytic | Odoo S.A. | 11.0.1.1 | Installiert
  | Password Encryption | auth_crypt | ['Odoo SA', 'FS3'] | 11.0.2.0 | Installiert
  | Signup | auth_signup | Odoo S.A. | 11.0.1.0 | Installiert
  | Material/United Backend Theme | backend_theme_v11 | Openworx | 11.0.1.0.3 | Installiert
  | Base | base | Odoo S.A. | 11.0.1.3 | Installiert
  | IBAN Bank Accounts | base_iban | Odoo S.A. | 11.0.1.0 | Installiert
  | Base import | base_import | Odoo S.A. | 11.0.1.0 | Installiert
  | Initial Setup Tools | base_setup | Odoo S.A. | 11.0.1.0 | Installiert
  | Dünnbesetzte Felder | base_sparse_field | Odoo S.A. | 11.0.1.0 | Installiert
  | VAT Number Validation | base_vat | Odoo S.A. | 11.0.1.0 | Installiert
  | USt-IdNr.-Autovervollständigung | base_vat_autocomplete | Odoo S.A. | 11.0.1.0 | Installiert
  | Dashboards | board | Odoo S.A. | 11.0.1.0 | Installiert
  | IM Bus | bus | Odoo S.A. | 11.0.1.0 | Installiert
  | Kalender-SMS | calendar_sms | Odoo S.A. | 11.0.1.0 | Installiert
  | Contacts Directory | contacts | Odoo S.A. | 11.0.1.0 | Installiert
  | Decimal Precision Configuration | decimal_precision | Odoo S.A. | 11.0.0.1 | Installiert
  | Attachments List and Document Indexation | document | Odoo S.A. | 11.0.2.1 | Installiert
  | Document Page | document_page | OpenERP SA, Odoo Community Association (OCA) | 11.0.9.0.1.0.1 | Installiert
  | Events Organization | event | Odoo S.A. | 11.0.1.0 | Installiert
  | Events Sales | event_sale | Odoo S.A. | 11.0.1.1 | Installiert
  | Email Gateway | fetchmail | Odoo S.A. | 11.0.1.0 | Installiert
  | Google Users | google_account | Odoo S.A. | 11.0.1.0 | Installiert
  | Google Calendar | google_calendar | Odoo S.A. | 11.0.1.0 | Installiert
  | Google Drive™ integration | google_drive | Odoo S.A. | 11.0.0.2 | Installiert
  | Google Spreadsheet | google_spreadsheet | Odoo S.A. | 11.0.1.0 | Installiert
  | In-App Purchases | iap | Odoo S.A. | 11.0.1.0 | Installiert
  | Knowledge Management System | knowledge | OpenERP SA, Odoo Community Association (OCA) | 11.0.9.0.1.1.0 | Installiert
  | Deutschland - Accounting | l10n_de | openbig.org | 11.0.1.0 | Installiert
  | Deutschland SKR03 - Accounting | l10n_de_skr03 | openbig.org | 11.0.2.0 | Installiert
  | Deutschland SKR04 - Accounting | l10n_de_skr04 | openbig.org | 11.0.2.0 | Installiert
  | Link Tracker | link_tracker | Odoo S.A. | 11.0.1.0 | Installiert
  | Massenmailings an Teilnehmer | mass_mailing_event | Odoo S.A. | 11.0.1.0 | Installiert
  | Partner first name and last name | partner_firstname | Camptocamp, Grupo ESOC Ingeniería de Servicios, Tecnativa, LasLabs, ACSONE SA/NV, Odoo Community Association (OCA) | 11.0.1.0.0 | Installiert
  | Payment Acquirer | payment | Odoo S.A. | 11.0.1.0 | Installiert
  | Transfer Payment Acquirer | payment_transfer | Odoo S.A. | 11.0.1.0 | Installiert
  | Products & Pricelists | product | Odoo S.A. | 11.0.1.2 | Installiert
  | Project Task Default Stage | project_task_default_stage | Tecnativa, Odoo Community Association (OCA) | 11.0.1.0.0 | Installiert
  | Job Queue | queue_job | Camptocamp,ACSONE SA/NV,Odoo Community Association (OCA) | 11.0.1.0.1 | Installiert
  | Resource | resource | Odoo S.A. | 11.0.1.1 | Installiert
  | Sales | sale | Odoo S.A. | 11.0.1.1 | Installiert
  | Sales Channels | sales_team | Odoo S.A. | 11.0.1.0 | Installiert
  | SMS-Gateway | sms | Odoo S.A. | 11.0.1.0 | Installiert
  | TOM] Billard Manager | tom_billardmanager | Karsten Kinateder | 11.0.0.1 | Installiert
  | UTM Trackers | utm | Odoo S.A. | 11.0.1.0 | Installiert
  | Web | web | Odoo S.A. | 11.0.1.0 | Installiert
  | Odoo Web Diagram | web_diagram | Odoo S.A. | 11.0.2.0 | Installiert
  | Web Editor | web_editor | Odoo S.A. | 11.0.1.0 | Installiert
  | Gauge Widget for Kanban | web_kanban_gauge | Odoo S.A. | 11.0.1.0 | Installiert
  | Planner | web_planner | Odoo S.A. | 11.0.1.0 | Installiert
  | Web Responsive | web_responsive | LasLabs, Tecnativa, Odoo Community Association (OCA) | 11.0.1.0.2 | Installiert
  | Odoo Settings Dashboard | web_settings_dashboard | Odoo S.A. | 11.0.1.0 | Installiert
  | Tours | web_tour | Odoo S.A. | 11.0.0.1 | Installiert
  | Website Mail | website_mail | Odoo S.A. | 11.0.0.1 | Installiert
  | Website Mass Mailing Campaigns | website_mass_mailing | Odoo S.A. | 11.0.1.0 | Installiert
  | Website Partner | website_partner | Odoo S.A. | 11.0.0.1 | Installiert
  | Website Theme Install | website_theme_install | Odoo S.A. | 11.0.1.0 | Installiert
  | Email Marketing | mass_mailing | Odoo S.A. | 11.0.2.0 | Installiert
  | Calendar | calendar | Odoo S.A. | 11.0.1.0 | Installiert
  | Blogs | website_blog | Odoo S.A. | 11.0.1.0 | Installiert
  | Bootswatch Theme | theme_bootswatch | Odoo S.A. | 11.0.1.0 | Installiert
  | Kundenportal | portal | Odoo S.A. | 11.0.1.0 | Installiert
  | Web-Routen | http_routing | Odoo S.A. | 11.0.1.0 | Installiert

```

**Comment by DR4RCON** [comment] 2018-05-10 09:47
There is only one customized modul TOM] Billard Manager but that doent effects event or any view of it.

**Comment by pedrobaeza** [comment] 2018-05-10 09:48
Sorry, but this is not happening in runbot as said. It's something on your side. Please don't put issues without checking this basic steps I'm commenting you (try on runbot and again **provide detailed steps to reproduce**).

**Comment by DR4RCON** [comment] 2018-05-10 09:54
Please how should I handle this problems with databases older then the current branch? Should I not update? Sure that could be a specific problem that this error appears in my database. But when that error also appears after updating an existing database it is also an Odoo issue? Checking with runbot is not representative in that case, cause all components are from same head.

**Comment by DR4RCON** [comment] 2018-05-10 09:59
My demo database on my development server has same installation date as the customer one. And I have the same problem. You can check that: Login http://demo.tom-dev.de  admin/alcoholfree  and go to events.
So this Problem seems to appear with a database older then the current branch.

**Comment by pedrobaeza** [comment] 2018-05-10 09:59
You have to update your DB modules with -u all.

**Comment by DR4RCON** [comment] 2018-05-10 10:01
I have backuped data and tried that, -u all runs fine and complete, but the errors continues.

**Comment by DR4RCON** [comment] 2018-05-10 10:01
I checked different browsers, deleted all cache. But that error will not go until I delete the filter in search view.

**Comment by pedrobaeza** [comment] 2018-05-10 10:03
Then remove the filter and update again

**Comment by Yenthe666** [comment] 2018-05-11 07:31
@DR4RCON alternatively you can ask for help on the official help forums at help.odoo.com but I'm afraid you provide too little valuable info for anybody to help.
Try to reproduce it on runbot.odoo.com with detailed steps and then we can help.
