### ISSUE TITLE
[v12][CE][EE][WEB] m2m field gives error on TransientModel o2m fied

### ISSUE THREAD

**Issue by tpa-odoo** [odoo/odoo#32486] opened 2019-04-08 09:53 UTC
Impacted versions: v12

Steps to reproduce: Add m2m field on o2m field of any TransientModel and try to select value on that filed in popup it will give an error

Just add one m2m field on Picking return wiz lines and check.

Current behavior: Traceback

Expected behavior: No error, It should allow to select m2m records

Video/Screenshot link (optional):
![Odoo (5)](https://user-images.githubusercontent.com/7599790/55715265-04ec0a80-5a12-11e9-9f32-20d8faa653c9.png)
![Odoo (6)](https://user-images.githubusercontent.com/7599790/55715267-061d3780-5a12-11e9-8cd7-b77de465b46d.png)

**Comment by pedrobaeza** [comment] 2019-04-08 10:47
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

AFAIK, I have done this before and it's working.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2019-04-08 10:47 UTC

**Comment by tpa-odoo** [comment] 2019-04-08 14:26
Hello @pedrobaeza ,

It's not about my custom code or so. I gave just way to reproduce it.

the real issue is with web framework.

Please open it again so odoo Framework team can have a look on it.

If you want to check you can check it on thsi runbot DB: http://495103-12-0-3017ae.runbot13.odoo.com/web#id=7&action=392&model=stock.picking&view_type=form&menu_id=281

I don't know in default odoo there is such use case or not. So given simple flow so the developer can reproduce it easily.

Let me know if you need further infomration.
