### ISSUE TITLE
Error on search PO inside accounting: "Uncaught Promise > Name 'str' is not defined"

### ISSUE THREAD

**Issue by sefirosweb** [odoo/odoo#130131] opened 2023-07-29 07:38 UTC
Impacted versions: 
16 and 17(preview online)

Steps to reproduce + Video/Screenshot link (optional):
Install fresh of odoo 16 or go to preview of 17: https://demo4.odoo.com/web#cids=1&action=menu
Go Accounting:
![image](https://github.com/odoo/odoo/assets/20754836/e3e64903-3387-4176-9ea8-f4bb45412461)
Create manually:
![image](https://github.com/odoo/odoo/assets/20754836/c6de4400-5933-4b8e-84bb-1f98ab6466e4)
Click on search more
![image](https://github.com/odoo/odoo/assets/20754836/0622a612-7396-4f08-a605-ecf37d51c90c)
And search using reference:
![image](https://github.com/odoo/odoo/assets/20754836/d0fb8207-1333-4722-b66f-e71daad6d48f)
![image](https://github.com/odoo/odoo/assets/20754836/8f3fd00f-0608-49c2-9723-ddc61612187b)

This happens in fresh installation of odoo 16

Is the same error:
UncaughtPromiseError > EvaluationError
Uncaught Promise > Name 'str' is not defined
EvaluationError: Name 'str' is not defined
    at _evaluate (https://demo4.odoo.com/web/assets/1371-36e8e4e/web.assets_backend.min.js:1376:232)
    at _evaluate (https://demo4.odoo.com/web/assets/1371-36e8e4e/web.assets_backend.min.js:1380:23)
    at evaluate (https://demo4.odoo.com/web/assets/1371-36e8e4e/web.assets_backend.min.js:1389:8)
    at applyBinaryOp (https://demo4.odoo.com/web/assets/1371-36e8e4e/web.assets_backend.min.js:1360:48)
    at _evaluate (https://demo4.odoo.com/web/assets/1371-36e8e4e/web.assets_backend.min.js:1377:102)
    at Array.map (<anonymous>)
    at _evaluate (https://demo4.odoo.com/web/assets/1371-36e8e4e/web.assets_backend.min.js:1378:33)
    at Array.map (<anonymous>)
    at _evaluate (https://demo4.odoo.com/web/assets/1371-36e8e4e/web.assets_backend.min.js:1378:33)
    at evaluate (https://demo4.odoo.com/web/assets/1371-36e8e4e/web.assets_backend.min.js:1389:8)

**Comment by vava-odoo** [comment] 2023-09-07 11:40
Hi @sefirosweb 
Thanks for reporting. Looks like it has been fixed in between, as not reproducible on [runbot](http://runbot.odoo.com/runbot)
Cheers

**Closed by vava-odoo** 2023-09-07 11:40 UTC
