### ISSUE TITLE
[www.odoo.com]Forum moderation: Unable to delete/close post waiting for validation

### ISSUE THREAD

**Issue by treviser** [odoo/odoo#14462] opened 2016-11-24 15:04 UTC
Impacted versions:

Actual instance www.odoo.com after the update this afternoon

Steps to reproduce:
Try to delete posts waiting in the validation queue 

Current behavior:

When deleting a post waiting in the validation queue, the post seems to be deleted directly, but the windows for closing posts and specifying a closing reason does not appear. After a refresh, the post reappears in the validation queue.

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment] 2016-11-24 15:36
Hi @treviser,

Thanks a lot for your report! I've just tested this and this is indeed a bug.
@JKE-be could you fix it please?

Regards,
Yenthe

**Comment by JKE-be** [comment] 2016-11-24 15:48
Meaculpa,

Broken by my commit #5c11310

I fix it asap...

**Comment by JKE-be** [comment] 2016-11-25 08:22
Fixed by commit odoo/odoo@4fa39c0e1994ffeffb8937f935634aa29e523da8

Thanks for reporting

Will be deployed today

**Comment by treviser** [comment] 2016-11-29 06:57
@JKE-be  It happens again.

**Comment by Yenthe666** [comment] 2016-11-29 07:14
Yup, same behaviour as before.

**Comment by JKE-be** [comment] 2016-11-30 09:44
Cannot reproduce... are you sure ?

**Comment by JKE-be** [comment] 2016-11-30 11:39
?

**Comment by Yenthe666** [comment] 2016-11-30 12:10
The validation process doesn't work anymore. You cannot delete/close a topic anymore on the forums.

**Comment by JKE-be** [comment] 2016-11-30 15:46
I have just try now, and without problem :/

can you chec network to see if you got a 500 or smthing else?

**Comment by Yenthe666** [comment] 2016-11-30 16:54
Hi @JKE-be,

I've just double checked this and it is still not fixed. The page returns 200 (OK) and no issues bubble up.
![image](https://cloud.githubusercontent.com/assets/6352350/20762242/06ce9ef8-b726-11e6-8383-9ecfbc301fb2.png)

**Comment by JKE-be** [comment] 2016-11-30 17:57
Code always not updated on the prod :) That can explain why ;)

**Closed by JKE-be** 2016-11-30 17:57 UTC
Labels: confirmed

**Comment by treviser** [comment] 2016-12-02 08:02
Bump...
