### ISSUE TITLE
Impossible to process incoming shipment's backorder

### ISSUE THREAD

**Issue by florian-dacosta** [odoo/odoo#8528] opened 2015-09-14 15:27 UTC
Hello,

I have found a bug when trying to process an incoming shipment's backorder.
It happens if we change the key "_order" of the stock_move class.

How to reproduce : 
Create a module (or change directly in module stock to test quickly) which modify the _order key of the stock.move class this way : `_order = "id desc"`

`class StockMove(models.Model):`
`_inherit = 'stock.move'`
`_order = "id desc"`

Then, create an incoming shipment with one line of 10 products. (any product).
Do the transfer of 2 of these products.
A back order is created, it is all good until now.
Then, try to transfer the backorder (with the 8 remaining products).
It won't be possible, the system will create an empty picking in draft and will do nothing more.

The explanation : 
During the transfer process, the picking will contain 2 moves.
the original move with 2 products and a new created move with 8 products.
Then the `recompute_remaining_qty` method will create a `stock.move.operation.link` with a quantity of 2. It will create the link for the first move of the dict `prod2move_ids`.

So if we have the classic `order_by`, which is `id asc`, it is ok, the link will be done with the move having the smallest id (the first one).
But if the `order_by` is `id desc`, the link will be created for the wrong move, the one with the biggest id.
Of course, the bug can be present with others`order_by`, it will depend...

The result is that the stock.move.link.operation is linked to the move which is in the backorder. So the remaining qty of this move is false. When we try to process the backorder, the remaining_qty will be negative and nothing will happen.

If it is not clear enought, I can give more details.

Thanks for your feedback.

**Comment by sle-odoo** [comment] 2018-02-21 10:35
Hi,
I'm closing this ticket since it is not reproducible in standard code.

Regards

**Closed by sle-odoo** 2018-02-21 10:35 UTC
Labels: Logistics
