### ISSUE TITLE
[12, 13, 14] Rounding error with advanced pricelist

### ISSUE THREAD

**Issue by auyeung112002** [odoo/odoo#46417] opened 2020-02-27 10:35 UTC
Impacted versions:
13

Steps to reproduce in frontend, this can also be reproduced in backend:
1. login to runbot.odoo.com. Choose a version 13 instance
2. Go to setting->sales -> pricelists -> Enable Advanced price rules
3. Create a dummy product, with list price $168 and no tax
4. Click Extra Price to create a pricelist item. Min Quantity is 1. Price is $158
5. Go to pricelist->Public Pricelist-> Configuration Tab -> Set Discount Policy to Discount included in the price
6. Go to website, publish the dummy product
7. Add 2 dummy product to cart
8. Total Price is 316.00. Correct

Now reproduce the bug
9. Go to pricelist->Public Pricelist-> Configuration Tab -> Set Discount Policy to Show public price & discount to the customer
10. Clear the cart
11. Add 2 dummy products to cart
12. Unit price is $158.01. Total Price is $316.01
13. Adding more products will increase the rounding error

Current behavior:
Unit price and total price are wrong

Expected behavior:
Unit price and total price correctly computed.

Video/Screenshot link (optional):
![rounding_bug](https://user-images.githubusercontent.com/8391358/75436639-e24b4300-598f-11ea-8a45-83bfc1937bc7.gif)

**Comment by Yenthe666** [comment] 2020-02-27 11:02
@auyeung112002 have you also tested with rounding per order instead of rounding per line?

**Comment by auyeung112002** [comment] 2020-02-27 13:34
Round per line and round globally makes no difference. The rounding error still exists.

**Comment by cvinh** [comment] 2020-03-20 02:26
cc @tglukhov @LuceEasyPme

**Comment by cvinh** [comment] 2020-04-22 07:01
It seems that this issue was introduced here https://github.com/odoo/odoo/commit/180866fe1e3b8998cc47ee584abaaff76d4135bb
It's due to the fact the discount in sale_order is in percentage and the price list is in fixed price.
The discount is calculated with a rounding and then the final price cannot be exactly the wanted fixed price.
@nim-odoo could you please advice us
cc @LuceEasyPme

**Comment by auyeung112002** [comment] 2020-04-22 07:17
@cvinh Exactly. The SO Item discount is derived from fixed amount in price list. And it causes the rounding problem.

**Comment by cvinh** [comment] 2020-04-22 07:19
a workaround is to increase the Decimal Precision on Discount
@auyeung112002 try to increase to 3 or 4

**Comment by auyeung112002** [comment] 2020-04-22 07:34
@cvinh Thanks. Already done. But the problem still occurs when buying more quantity even if precision is 5 or 6. But it is a workaround for the time being.

**Comment by amindehghani** [comment] 2020-09-24 09:41
any updates on this issue?

**Comment by rdeodoo** [comment] 2020-10-29 12:10
This is not related to the ecommerce or a website module.
The exact same issue is also in regular SO in the backend.
As `sale.order.discount` field is storing only 2 digits, the subtotal of a line will always be incorrect if the exact discount has over 2 digits.

Indeed, as:
1. Discount = (product price - fixed pricelist price) / product price * 100 = might be 98,666666667% which is rounded to 98.67
2. Prix subtotal : Qty * product price * discount, then you lose the difference between 98,666666667 and 98.67

We are discussing this issue and will keep you inform

**Comment by rdeodoo** [comment] 2020-10-30 13:34
After discussion, it has been decided that this won't be fixed in stable, as:

1. We consider this a corner case in the sense that it only appears under certain circumstances, when **discount** is shown on pricelist + fixed price, in which case you most of the time set a discount, not a fixed price. You probably don't want to show 15.67% discount to the enduser.
The fact this rounding issue has never been fixed despite being reproductible in every version enforce this idea.
2. There is a possible, not elegant, workaround by increasing the rounding precision on _Discount_
3. Here is a [local patch](https://github.com/odoo/odoo/pull/60963) that you might consider that seems to do the trick (it is a draft wip, to triple check, especially perf wise).

We will consider this in master, we added it in wishlist.

**Closed by rdeodoo** 2020-10-30 13:34 UTC
Labels: 12.0, 13.0, 14.0, Sales, Wishlist
