### ISSUE TITLE
Fetch Mail does fetch the Mail but does not create a Record

### ISSUE THREAD

**Issue by maltehelmhold** [odoo/odoo#6757] opened 2015-05-18 19:42 UTC
Hey there, 

IMAP Incoming gateway is created and works. After
fetching manually the mail is immediately marked as read in the
inbox of the provider. So it's fetched. 

Under Actions to Perform on Incoming Mails I set 
"create a new record" to mail.message. 

But there will be no mail.message record. And no other record if I try something else. And when I navigate to Incoming Mail Server the Value for "# of emails" will still remain (0 records). 

I have this problem on two different servers. A year ago I hassled 1 week with Odoo Mail-Fetching. I thought I'm a genius now relating this stuff. But it seems there is either an error or something fundamentally changed and I do not know about it yet:(

Malte

**Comment by victorlclopes** [comment] 2017-11-21 20:32
Hi there,
 
I know this is a really old post, and either you've found your answer or you gave up on waiting :)
But for those looking for this and experiencing the same behavior described here, I’d like to write a few words:
 
When we (people new to Odoo) see the incoming email server configuration and we notice the “**Create a New Record**” option under the “**Action to perform...**” we easily end up with the false impression that any kind of record can be created from here. However, that’s not entirely true. Unfortunately, some models have an implementation for this and some not, some of them would even work fine with the fallback method that can generically create such records, but some will not.
 
Odoo is prepared to create a number of records this way, that are traditionally generated from e-mail messages, like **Lead/Opportunity** in Sales, **Project Tasks**, **HR Applications**, etc. But that does not apply to other record types such as **Purchase Orders**, for example.
 
That's the case I'm bringing today: I've been trying to create purchase orders from incoming e-mails.
 
**1.** The first advice is, of course, to take a look at your logs. On a Ubuntu installation (and Debian too, I believe) they can be found on the following path:
 
**/var/log/odoo**
file: odoo-server
 
In my case, I was seeing things like these:
 
```
17-11-21 02:00:01,390 1293  odoo.addons.fetchmail.models.fetchmail: start checking for new emails on imap server YOURSERVER
2017-11-21 02:00:04,191 1293 odoo.addons.mail.models.mail_thread: Routing mail from John Doe <john@somedomain.com> to PO <po_odoo@somedomain.com> with Message-Id <033BEAFA3A88314AAD1AF741D8A56C0E95DD2533@YOURSERVER>: fallback to model:purchase.order, thread_id:None, custom_values:None, uid:5
2017-11-21 02:00:04,288 1293 ERROR odoo.sql_db: bad query: b'INSERT INTO "purchase_order" ("id", "currency_id", [... LONG COLUNM LIST...]
ERROR: null value in column "partner_id" violates not-null constraint
```
 
That's one of the reasons why you see the e-mail messages being retrieved (marked as read), but no record is created.
 
**2.** The method used for this (in Odoo's python files) is the "**message_new**", as mentioned on these posts: 
[https://stackoverflow.com/questions/35573960](https://stackoverflow.com/questions/35573960/adding-followers-to-mail-followers-widget-automatically-from-hr-employee-in-odoo)
[https://www.odoo.com/forum/...39343](https://www.odoo.com/forum/help-1/question/add-followers-automatically-39343)
 
**3.** The Purchase Order module (**purchase.py**) doesn't have an implementation (override) for said method and the generic call to its "Create" method (made by the mail.thread model) won't suffice because the "partner_id" column (which can't be null) is not parsed by default.
 
That being said, I've gathered information from some posts (like those above) and from some other models that do have a message_new method implementation, and put together a message_new function for my Purchase Order module (purchase.py).
 
• If you don't have experience with python (just like me), don't worry.
These modules and files can be found on the following path:
 
**/odoo/odoo-server/addons**
 
• Each module has a folder on this path and it usually has a subfolder called "models", where you will find these files, e.g.: /odoo/odoo-server/addons/purchase/models/purchase.py
 
• **Edit** the file _purchase.py_ (path above) and insert the following lines:
 
```
@api.model
    def message_new(self, msg, custom_values=None):
        """ Overrides mail_thread message_new that is called by the mailgateway
            through message_process.
            This override updates the document according to the email.
        """
        # remove default author when going through the mail gateway. Indeed we
        # do not want to explicitly set user_id to False; however we do not
        # want the gateway user to be responsible if no other responsible is
        # found.
        create_context = dict(self.env.context or {})
        create_context['default_user_id'] = False
        if custom_values is None:
            custom_values = {}
        defaults = {
            'name': msg.get('subject') or _("No Subject"),
            'partner_id': msg.get('author_id')
        }
        defaults.update(custom_values)
        p_order = super(PurchaseOrder, self.with_context(create_context)).message_new(msg, custom_values=defaults)
 
        followers_obj = p_order.env['mail.followers']
        follower_id = False
        reg = {
                'res_id': p_order.id,
                'res_model': 'purchase.order',
                'partner_id': msg.get('author_id'), }
        try:
                follower_id = followers_obj.create(reg)
        except:
                 _logger.info(u'AddFollower: follower already exists')
 
        return p_order
```
 
 
I don't believe there is a particular order, but make it between two other existing functions (defs).
 
And be aware of python's indentation requirements (don't mess up with the tabs and spaces at the beginning of each line, and check if pasting it here have not done it already :). Here is if you encounter any error regarding this: [https://stackoverflow.com/questions/1016814](https://stackoverflow.com/questions/1016814/what-to-do-with-unexpected-indent-in-python)
 
After saving this file, restart Odoo's service (_sudo service odoo-server restart_) and try sending and fetching e-mails again.
 
**Final considerations:**
 
• This is applicable to purchase orders, but I think it can be modified to suite your needs on other record types.
 
• This is such a simple function and it will just get you started. It will mark the sender as "Vendor" (which doesn't make much sense at first, but can be altered once the purchase order is viewed by the applicable employee). And it will also add the sender as a "follower", so when the order is replied to, the sender will receive an answer.
 
• Inside the "**defaults = {** " block there are specific parameters that belong to the type of record being created, so they may vary and more can be added here.

• In this case, the sender will have to be a pre-existing user in the database (an internal employee, for example, with its account in Odoo). Otherwise you will have to elaborate more on this message_new function in order to create a new user on the fly (case it doesn't exist yet).

For the record, this was tested on an Odoo 10 and Odoo 11 installation, both on Ubuntu Server 16.04 (Xenial) and my e-mail server is an Exchange Server 2010. Here are some complementary files:

[purchase (sample).py.txt](https://github.com/odoo/odoo/files/1492773/purchase.sample.py.txt)

[Purchase order error complete sample.txt](https://github.com/odoo/odoo/files/1492774/Purchase.order.error.complete.sample.txt)


**Incoming server (IMAP) server** (developer mode - "Technical" menu > Incoming Mail Servers):

![printscreen - incoming server settings](https://user-images.githubusercontent.com/27737616/33094686-25d6dd8a-cee8-11e7-8c2b-e520e9306251.png)

New **Purchase Order sample**, created from e-mail:

![printscreen - purchase order created sample](https://user-images.githubusercontent.com/27737616/33094688-25fcd332-cee8-11e7-9768-6533b78cfac2.png)


Cheers,

Victor Lopes

**Comment by Yenthe666** [comment] 2017-12-14 12:14
Hi @maltehelmhold,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Closed by Yenthe666** 2017-12-14 12:14 UTC

**Comment by alielgarhi** [comment] 2018-09-18 11:40
@victorlclopes  great and good work do you think can do the same thing in sales and insert time lines from emails may be from body or attachment
