### ISSUE TITLE
HOW DEFINE TRANSFER ACCOUNT  IN INVOICING

### ISSUE THREAD

**Issue by shaneebkhan** [odoo/odoo#24016] opened 2018-04-03 16:09 UTC
where i can define transfer account 
am asking how define the transfer account 

Impacted versions:11

Steps to reproduce:invoicing -->sales-->documents-->payments-->internal transafer

Current behavior:Transfer account not defined on the company.

Expected behavior: tranasfer one head to anther

odoo error on internal transfer (payments invoicing )

where i can define transfer account

Odoo Server Error - Warning
Transfer account not defined on the company.

Video/Screenshot link (optional):

![error on transfer](https://user-images.githubusercontent.com/10399842/38261280-64f76a90-3787-11e8-9546-d6aed5d78134.png)

**Comment by sswapnesh** [comment] 2018-04-03 16:29
Duplicate of #23981

**Comment by pedrobaeza** [comment] 2018-04-03 16:31
And this is not for asking for help, only for reporting issues, sorry. Use forums for that.

**Closed** 2018-04-03 16:30 UTC

**Comment by shaneebkhan** [comment] 2018-04-03 16:42
am asking how can i set transfer account?
please answer me not close the issue
i known  this is not bug but i want to known how set or define transfer account

**Comment by sswapnesh** [comment] 2018-04-03 17:13
This is because of field `transfer_account_id` is not set in Company, Maybe because COA is not Installed for that Company.
@pedrobaeza  However, I agree that field should be in views as mentioned [here](https://github.com/odoo/odoo/blob/11.0/addons/account/models/company.py#L15).

> #TODO check all the options/fields are in the views (settings + company form view)

@shaneebkhan, For now, you can add  `transfer_account_id` in company's form view and set account there.
