### ISSUE TITLE
Placeholder Web Master

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#19239] opened 2017-09-04 09:53 UTC
Impacted versions: master

Steps to reproduce:
Just a placeholder for now, until I can dig deeper, latest pull of master has lots and lots of issues, not sure where to start.  Cursor behaviour is all over the place with onchanges in editable x2manys in form modals, if an onchange is triggered then it takes you back to the first field of an onchange (e.g. field d, depends on fields a, b, c for onchange.  Change field A, press tab, back to field A, Change field B press tab, back to field A, Change field C back to A.  Press shift tab to go backwards and onchanges in parents not triggered. x2many fields in modals, are not getting written at create time.  When they are edited they are saving as empty records e.g [[1,{}], [2,{}].  If the x2many fields aren't also in the tree view they won't write at all.

I've been pulling the code every few days, and all of a sudden working code just stopped with all sorts of issues.

@ged-odoo FYI for now, I'll try and get reproducibility and seperate issues for all of these as I work them out, but I've spent a few hours at this now.

**Comment by simahawk** [comment] 2017-09-06 07:15
Sounds like this is not happening on master only. It happens on 10.0 too :sob: 

Here's my use case:
1. add a m2m field to SO line
2. open a SO and add an SO line w/ the std popup
3. populate the m2m field w/ an onchange using recorset assignation
3a. you can see the m2m populated properly
4. save line
5. save order

What you get in the order write is something like:
```python
u'my_m2m_ids': [
            #  _, SUB ID, _
            [1, 1, {u'product_uom_id': 20}],
            [1, 4, {u'product_uom_id': 20}],
            [1, 7, {u'product_uom_id': 20}],
        ]
```
where `1,4,7` are the IDs of the items to link.
As a result your m2m is totally wiped out.

/cc @ged-odoo

**Comment by ged-odoo** [comment] 2017-09-13 13:29
@mge-odoo

**Comment by gdgellatly** [comment] 2017-10-12 01:30
@simahawk I'm pretty sure my issue is resolved and was going to close, but maybe you want to check yours first

**Comment by simahawk** [comment] 2017-10-12 06:33
@gdgellatly resolved where? :thinking:

**Comment by gdgellatly** [comment] 2017-10-12 06:40
@simahawk tbh I'm not entirely sure.  It all got a bit confusing as there were unrelated commits as release approached which fixed some things, reverts of things that were broken and then actual commits related to this issue.  But for me latest v11 is working as expected.  Check for a commit in v11 by (@)aab-odoo whereby they increased the write depth of onchange fields.

**Comment by simahawk** [comment] 2017-10-12 07:30
@gdgellatly the issue is not that the onchange does not work but that values are wrongly set.
@ged-odoo @aab-odoo is there a fix for this? If yes, any chance we can have the fix for v10 too?

**Comment by mge-odoo** [comment] 2017-11-28 12:28
Hi guys,

It appears that the revision https://github.com/odoo/odoo/commit/36b4d78a2678806b25aaa5650b64496f9da9d205 fixes this issue.

@gdgellatly thanks for reporting the bug.

@simahawk no chance to do it in v10 unfortunately, it requires way too much refactoring for a stable version. Refactoring that has been done in saas-16 (just before v11).

Regards,

Martin

**Closed by mge-odoo** 2017-11-28 12:28 UTC
Labels: Framework
