### ISSUE TITLE
[11.0] Problem with sorting sale order lines 

### ISSUE THREAD

**Issue by thomas15v** [odoo/odoo#32883] opened 2019-04-23 13:59 UTC
**Impacted versions:**

11.0 & 10.0 (is fixed in odoo 12 by #27639)

**Steps to reproduce:**

1. Create a sale order with 10 products (name them product1, product2, ... for convenience) 
2. Save this order
3. Add a second line and sort it between the products. This causes Odoo to sort the lines with sequences 10, 20, 30.
4. Create a new line and watch how this lines jumps to second place. You now get the following result because the starting sequence is 10:
![image](https://user-images.githubusercontent.com/2163941/56583867-d7d75480-65da-11e9-9de2-6ef36af404a9.png)

We also got reports that lines would be mixed after saving, but I haven't found a way to reproduce that, but I have seen it happening.

I tested following on runbot version 11.0 and can reproduce this issue.

**Current behavior:**

Sorting goes wild as soon you go over 10-100 items. Changing the default value of sequence to a higher nummer also does not create a correct behavior (we initially tried this as a fix).

**Expected behavior:**

Sorting does not change upon saving and new lines always have to start from below.

**Video/Screenshot link (optional):**

https://youtu.be/gfeBFpUIo7A?t=64

Go to 1min to skip preparation. I Just wanted to include every step.

**Comment by pedrobaeza** [comment] 2019-04-26 19:16
@seb-odoo @ged-odoo this is something that is happening to me also, so I wonder if there's any chance to mitigate it in v11.

**Comment by seb-odoo** [comment] 2019-04-29 15:48
The problem is that the fix of #27639 is done inside `_computeOverrideDefaultFields` which was introduced in #25483 with a target on master (12.0 back then) because the change was too complicated/risky to implement in stable versions.

The question would be can be implement the fix without the other PR, and I don't really know, maybe the framework JS team would have a better idea.

**Comment by pedrobaeza** [comment] 2019-04-29 16:51
Thanks for your insights, @seb-odoo. @ged-odoo can you comment something about this?

**Comment by thomas15v** [comment] 2019-05-16 13:53
Is there any more news about this issue? Or can there be given some clues to where exactly the problem lies?

**Comment by seb-odoo** [comment] 2019-06-12 15:11
I think the lack of news speaks for itself, we will probably never change this in v11 due to the above mentioned reasons. It should be possible to back port the PR I linked but this is not something we can do ourselves in a stable version.

As this is already fixed in v12 I'm not adding to wishlist but directly closing.

**Closed by seb-odoo** 2019-06-12 15:11 UTC
Labels: 10.0, 11.0, Sales
