### ISSUE TITLE
Odoo 13:. On hand Issue showing zero when sale order creation.

### ISSUE THREAD

**Issue by iman-alhaddar** [odoo/odoo#70824] opened 2021-05-16 15:15 UTC
Hello, 
I have an issue about products on hand as I can see in that I have products in hand but when I select the product for sale order it shows the little icon red color telling the I have zero quantity and when I log the product from the little arrow beside it it shows that I have 385 on hand and also the forecasted is 385 is the problem related to the forecasted quantity. 
May someone please help me solve this please.
Thanks in advance,
Have a nice day, 
Iman,

**Comment by pedrobaeza** [comment] 2021-05-17 06:15
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by QaidjoharBarbhaya** [comment] 2021-05-17 10:00
@iman-alhaddar Can you please review the warehouse on sales order under 'Other Info' tab, and also the location that belongs to which warehouse where the onhand quantity is there? Thanks.

**Closed** 2023-04-07 14:08 UTC
Labels: Need information
