### ISSUE TITLE
Is odoo support PostgreSQL 11 | Database creation error: relation "ir_model" does not exist

### ISSUE THREAD

**Issue by Elbagoury** [odoo/odoo#32771] opened 2019-04-17 10:58 UTC
Impacted versions:
V: 12 EE,CE April 2019 

Steps to reproduce:
odoo 12 is   working  good with PostgreSQL 10 but when Install PostgreSQL 11 and try to create DB using odoo 12 EE or CE this Error will Appear : 
Database creation error: relation "ir_model" does not exist LINE 1: SELECT * FROM ir_model WHERE state='manual'

<img width="293" alt="bug" src="https://user-images.githubusercontent.com/9639673/56282712-731e8480-6118-11e9-827f-1a2dde87a86b.png">

**Comment by pedrobaeza** [comment] 2019-04-17 11:00
I don't think the problem is with PG version. I remember to try PG 11 without problems.

**Comment by Yenthe666** [comment] 2019-04-17 11:04
Rather looks like a deployment issue.

**Comment by intero-chz** [comment] 2019-04-17 11:26
Yep, we have Odoo running with PostgreSQL 11.2 like a charm.

**Comment by pedrobaeza** [comment] 2019-04-17 11:32
Closing then without more details of the problem. Feel free to answer if there are more.

**Closed by pedrobaeza** 2019-04-17 11:32 UTC

**Comment by Elbagoury** [comment] 2019-04-17 12:10
Ok , I will test it again maybe it is deployment issue.

**Comment by rizkanf** [comment] 2019-08-09 04:07
Ahsyaaapppppp

**Comment by saeed-raeisi** [comment] 2021-07-27 10:20
check postgres user and permission 
i check res_partner_view -> <field name="state_id" class="o_address_state" placeholder="State" options="{'no_open': True, 'no_quick_create': True}"
