### ISSUE TITLE
[17.0] account_accountant: reconciliation error #3949954

### ISSUE THREAD

**Issue by MichaelHadar** [odoo/odoo#166790] opened 2024-05-26 13:51 UTC
### Odoo Version

- [ ] 15.0
- [ ] 16.0
- [X] 17.0
- [ ] Other (specify)

After the recent upgrade of our customer we are facing reconciliation errors.
### Steps to Reproduce

1. Go to the journal items screen
2. Make sure to filter according to the attached filter screenshots
![Filter](https://github.com/odoo/odoo/assets/74454561/a736fe74-6478-44d5-a8b1-0ef223a242dc)

3. Select all records and click the reconcile button
4. In the wizard select "ביטול יתרות" and click the reconcile button
5. You get the error

What is the current behavior that you observe?
An error reconciling journal items. It appears the system is trying to reconcile already reconciled lines (that were not even selected) for no reason

What would be your expected behavior in this case?
Reconcile the tax lines with no problems.

@guva-odoo 
@clbr-odoo 

### Support Ticket
Video explanation is in the ticket:
Ticket number in odoo support is #3949954

**Comment by hedshefer** [comment] 2024-05-28 15:44
@guva-odoo 
@clbr-odoo 
This issue exist after migration from V 15. When you try to reconclie items with or without writeoff.

**Comment by hedshefer** [comment] 2024-05-28 20:00
@smetl

**Comment by hedshefer** [comment] 2024-05-29 06:14
@william-andre

**Comment by william-andre** [comment] 2024-05-29 10:25
@hedshefer Please don't don't ping an entire team.

**Comment by william-andre** [comment] 2024-05-29 10:26
The issue doesn't say what the error is, neither what the button is in English despite the screenshot being in English.

**Comment by hedshefer** [comment] 2024-05-29 10:41
@william-andre 
Hi William,
Thank you for the assistance! We cannot do year closing because of this.
The full video and DB details are in the following ticket:
#3949954
To reproduce you have to filter the items according to the screenshot and do full reconciliation or reconcile partially with any account.
The error is:
"You can just change some non legal fields or you must unreconcile first.."

**Comment by william-andre** [comment] 2024-05-29 11:32
Then I will let the support handle the part linked to opw-3949954
This is not a fast lane support.

**Closed by william-andre** 2024-05-29 11:32 UTC
