### ISSUE TITLE
Activities: ExtendedLeaf: ('company_id', '=', False) 

### ISSUE THREAD

**Issue by m3asmi** [odoo/odoo#64548] opened 2021-01-14 13:47 UTC
Impacted versions:
12.0

Steps to reproduce:
click on the top activities -> Notes/Leaves (late,today)

Current behavior: 

Erro:
Odoo Server Error

Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/data/build/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/data/build/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/data/build/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/build/odoo/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/build/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/build/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/data/build/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/web/controllers/main.py", line 963, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/main.py", line 955, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 755, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 728, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/data/build/odoo/addons/note/models/note.py", line 93, in read_group
    } for stage in stages]
  File "/data/build/odoo/addons/note/models/note.py", line 93, in <listcomp>
    } for stage in stages]
  File "/data/build/odoo/odoo/models.py", line 1558, in search_count
    res = self.search(args, count=True)
  File "/data/build/odoo/odoo/models.py", line 1581, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/data/build/odoo/odoo/models.py", line 4147, in _search
    query = self._where_calc(args)
  File "/data/build/odoo/odoo/models.py", line 3939, in _where_calc
    e = expression.expression(domain, self)
  File "/data/build/odoo/odoo/osv/expression.py", line 673, in __init__
    self.parse()
  File "/data/build/odoo/odoo/osv/expression.py", line 854, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'company_id' in leaf "<osv.ExtendedLeaf: ('company_id', '=', False) on note_note (ctx: )>"

**Comment by pedrobaeza** [comment] 2021-01-14 14:16
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by m3asmi** [comment] 2021-01-14 16:38
@pedrobaeza yes you can try it yourself in the runbot

**Comment by pedrobaeza** [comment] 2021-01-14 16:40
Yes, I have done it without problem:

https://user-images.githubusercontent.com/7165771/104620686-91b80380-568f-11eb-8ab5-7903394435f5.mp4

**Comment by m3asmi** [comment] 2021-01-15 09:19
in deed the bug is when you click on the late, today, future of the object that does not have a company_id field example Note/Leaves
https://5746175-12-0.runbot51.odoo.com/web#action=116&active_id=mailbox_inbox&menu_id=95

 
![image](https://user-images.githubusercontent.com/7910752/104706198-169c2f00-571b-11eb-8fe1-9c7c8b0b59b5.png)

![image](https://user-images.githubusercontent.com/7910752/104706220-1c921000-571b-11eb-8d4d-41c3e4b1db00.png)

**Comment by pedrobaeza** [comment] 2021-01-15 09:21
In my video I clicked on "Notes".

**Comment by m3asmi** [comment] 2021-01-15 09:25
@pedrobaeza yes you did click on notes not in the filters ( late/ today/ future)

**Comment by pedrobaeza** [comment] 2021-01-15 09:27
OK, I see. Tagging this as confirmed.

**Comment by pedrobaeza** [comment] 2021-01-15 09:27
@tde-banana-odoo can you check this?

**Comment by tde-banana-odoo** [comment] 2021-01-15 10:06
Hello,

Thanks for pointing it out. This comes from a wrong fix: https://github.com/odoo/odoo/pull/64201 . I will do the followup on the original PR. This kind of regression should not happen ...

**Comment by m3asmi** [comment] 2021-01-15 13:27
@robodoo @pedrobaeza it's fixed, Thank you

**Comment by tde-banana-odoo** [comment] 2021-01-15 13:47
@robodoo is such a great colleague.

**Closed** 2021-01-15 13:47 UTC
Labels: 12.0, Confirmed, Discuss
