### ISSUE TITLE
Mass Mailing no include Return Path header

### ISSUE THREAD

**Issue by pablodgonzalez** [odoo/odoo#73897] opened 2021-07-16 15:03 UTC
Impacted versions: 13 & 14

Steps to reproduce: Create a campaign with no existents email addresses

Current behavior: No get bounce responses  

Expected behavior: Get the bounces in the return path address

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment] 2021-07-16 15:10
I'm afraid there are a lot of reasons why this is not working, and more of them not related with Odoo code, but deployments, so unless you prove the problem is in the code specifying details that point to this, this is not a valid issue.

**Comment by pablodgonzalez** [comment] 2021-07-16 15:18
In my Use Case I want to receive the bounces from AWS SES. The SES email feedback notification through email is to the Return-Path, it does not work with sender neither Reply-To. All Bounces and complaint are send to Return-Path.
We send email with AWS SES through SMTP endpoints and in that case is the odoo which create and send the email without the Return-Path header.

**Comment by pedrobaeza** [comment] 2021-07-18 08:25
That's the less important problem with Amazon SES. It alters the `Message-Id`, avoiding any kind of threading in Odoo. But that's something not solvable at Odoo side. The question is simple: you can't use Amazon SES with Odoo, unless they don't corrupt the original mail. Put an issue there to see if they attend it.

Closing as no Odoo problem, but Amazon SES.

**Closed by pedrobaeza** 2021-07-18 08:25 UTC
Labels: Need information
