### ISSUE TITLE
Error: Invalid generated code while compiling template 'web.ViewSwitcherButton': missing ) after argument list

### ISSUE THREAD

**Issue by sephrat** [odoo/odoo#68040] opened 2021-03-17 17:42 UTC
Impacted versions: Odoo 14.0-20210308 (Community Edition) 

Steps to reproduce: browse to any module, like Apps

Current behavior: Page is totally broken.
```
Error:


Traceback:
Error: Invalid generated code while compiling template 'web.ViewSwitcherButton': missing ) after argument list
_compile@http://192.168.2.200:8069/web/content/706-bacd4aa/web.assets_common.js:971:133
atNodeEncounter@http://192.168.2.200:8069/web/content/706-bacd4aa/web.assets_common.js:1056:140
_compileNode@http://192.168.2.200:8069/web/content/706-bacd4aa/web.assets_common.js:990:54
_compileChildren@http://192.168.2.200:8069/web/content/706-bacd4aa/web.assets_common.js:1027:108
_compileNode@http://192.168.2.200:8069/web/content/706-bacd4aa/web.assets_common.js:997:6
atNodeEncounter@http://192.168.2.200:8069/web/content/706-bacd4aa/web.assets_common.js:1066:44
_compileNode@http://192.168.2.200:8069/web/content/706-bacd4aa/web.assets_common.js:990:54
_compileChildren@http://192.168.2.200:8069/web/content/706-bacd4aa/web.assets_common.js:1027:108
_compileNode@http://192.168.2.200:8069/web/content/706-bacd4aa/web.assets_common.js:997:6
_compileChildren@http://192.168.2.200:8069/web/content/706-bacd4aa/web.assets_common.js:1027:108
_compileNode@http://192.168.2.200:8069/web/content/706-bacd4aa/web.assets_common.js:997:6
_compileChildren@http://192.168.2.200:8069/web/content/706-bacd4aa/web.assets_common.js:1027:108
_compileNode@http://192.168.2.200:8069/web/content/706-bacd4aa/web.assets_common.js:997:6
_compileChildren@http://192.168.2.200:8069/web/content/706-bacd4aa/web.assets_common.js:1027:108
_compileNode@http://192.168.2.200:8069/web/content/706-bacd4aa/web.assets_common.js:997:6
_compileChildren@http://192.168.2.200:8069/web/content/706-bacd4aa/web.assets_common.js:1027:108
_compileNode@http://192.168.2.200:8069/web/content/706-bacd4aa/web.assets_common.js:997:6
_compile@http://192.168.2.200:8069/web/content/706-bacd4aa/web.assets_common.js:967:6
fn@http://192.168.2.200:8069/web/content/706-bacd4aa/web.assets_common.js:952:105
render@http://192.168.2.200:8069/web/content/706-bacd4aa/web.assets_common.js:959:20
useModel/__owl__.renderFn@http://192.168.2.200:8069/web/content/707-ce956c9/web.assets_backend.js:1325:147
__render@http://192.168.2.200:8069/web/content/706-bacd4aa/web.assets_common.js:1278:33
__prepareAndRender@http://192.168.2.200:8069/web/content/706-bacd4aa/web.assets_common.js:1276:29
```

Expected behavior: No error

Additional info: I'm running Odoo via Docker (odoo:14.0). A fairly recent upgrade triggered this issue.
Activating developer mode with assets fixes it temporarily.
`grep -r -i "web.ViewSwitcherButton" /usr/lib/python3/dist-packages/odoo/` returns:
```
/usr/lib/python3/dist-packages/odoo/addons/web/static/src/xml/base.xml:                        <t t-call="web.ViewSwitcherButton"/>
/usr/lib/python3/dist-packages/odoo/addons/web/static/src/xml/base.xml:<t t-name="web.ViewSwitcherButton" owl="1">
```
There was a recent change in d54b707efd63cb3dd4b5080d60672932bfb5fe94, not sure if this is related.
It seems I'm not the only one experiencing this: 
https://stackoverflow.com/questions/66422993/invalid-generated-code-while-compiling-template-web-viewswitcherbutton-odoo 
https://www.odoo.com/fr_FR/forum/aide-1/cannot-open-any-module-after-upgrade-to-latest-odoo-14-build-183896

**Comment by pedrobaeza** [comment] 2021-03-17 19:05
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by sephrat** [comment] 2021-03-20 07:20
I'm afraid I cannot reproduce it in runbot infrastructure, nor on fresh Docker setup with the same settings/modules.
I have not installed any custom or community modules (full list here: https://pastebin.com/9P5Ssn3B), nor did I make any change in the code (I rm'd and restarted the container just to be sure).
My docker-compose setting is nothing exotic, it's just the one from the official doc. 
I don't mind deep diving into logs or code but I'm pretty lost as to where to look at now.

**Comment by pedrobaeza** [comment] 2021-03-20 11:35
You can try with more advanced deployment system like Doodba for seeing if it helps you, but I'm afraid this is out of scope of this issue tracker. Try to ask on Odoo forums.

**Closed by pedrobaeza** 2021-03-20 11:35 UTC
Labels: Need information

**Comment by reyesruiz** [comment] 2021-03-22 22:05
@sephrat I am getting the same error, on an unbuntu 20.04 installation.

One thing I found out is that there was a change to base.xml file around February 26, if I revert those changes manually in my installation, it works.

I am guessing it has something to do with sprintf

https://github.com/odoo/odoo/commit/d54b707efd63cb3dd4b5080d60672932bfb5fe94#diff-72f3229e49fc364ae1c1dcedc5e544c87a94121b92b538090af85103b705e768

**Comment by jakobkrabbe** [comment] 2021-03-30 09:44
Ubuntu 20.04 and a blank install of Odoo 14. Numbers at the end differ, the rest is the same as the original post.

`Traceback:
Error: Invalid generated code while compiling template 'web.ViewSwitcherButton': missing ) after argument list
_compile@http://anna:8069/web/content/168-cc304f5/web.assets_common.js:971:133
atNodeEncounter@http://anna:8069/web/content/168-cc304f5/web.assets_common.js:1056:140
_compileNode@http://anna:8069/web/content/168-cc304f5/web.assets_common.js:990:54
_compileChildren@http://anna:8069/web/content/168-cc304f5/web.assets_common.js:1027:108
_compileNode@http://anna:8069/web/content/168-cc304f5/web.assets_common.js:997:6
atNodeEncounter@http://anna:8069/web/content/168-cc304f5/web.assets_common.js:1066:44
_compileNode@http://anna:8069/web/content/168-cc304f5/web.assets_common.js:990:54
_compileChildren@http://anna:8069/web/content/168-cc304f5/web.assets_common.js:1027:108
_compileNode@http://anna:8069/web/content/168-cc304f5/web.assets_common.js:997:6
_compileChildren@http://anna:8069/web/content/168-cc304f5/web.assets_common.js:1027:108
_compileNode@http://anna:8069/web/content/168-cc304f5/web.assets_common.js:997:6
_compileChildren@http://anna:8069/web/content/168-cc304f5/web.assets_common.js:1027:108
_compileNode@http://anna:8069/web/content/168-cc304f5/web.assets_common.js:997:6
_compileChildren@http://anna:8069/web/content/168-cc304f5/web.assets_common.js:1027:108
_compileNode@http://anna:8069/web/content/168-cc304f5/web.assets_common.js:997:6
_compileChildren@http://anna:8069/web/content/168-cc304f5/web.assets_common.js:1027:108
_compileNode@http://anna:8069/web/content/168-cc304f5/web.assets_common.js:997:6
_compile@http://anna:8069/web/content/168-cc304f5/web.assets_common.js:967:6
fn@http://anna:8069/web/content/168-cc304f5/web.assets_common.js:952:105
render@http://anna:8069/web/content/168-cc304f5/web.assets_common.js:959:20
useModel/__owl__.renderFn@http://anna:8069/web/content/230-7252356/web.assets_backend.js:1326:147
__render@http://anna:8069/web/content/168-cc304f5/web.assets_common.js:1279:33
__prepareAndRender@http://anna:8069/web/content/168-cc304f5/web.assets_common.js:1277:29`

**Comment by sephrat** [comment] 2021-03-30 09:47
I solved the issue with solution provided here: https://github.com/odoo/odoo/issues/67801#issuecomment-805389867
However it's only temporary as it's a rollback to a recent change made to one file. Still hoping https://github.com/odoo/odoo/issues/67801 gets addressed by the team at some point.

**Comment by ediazrod** [comment] 2021-03-30 21:45
I on the same situation I roll back everthing and stop the updates util is solved.

**Comment by BennyVeeOmy** [comment] 2021-03-31 14:29
Same here, revert to a febrary release fix the issue, wishing a permanent fix soon

**Comment by jakobkrabbe** [comment] 2021-04-01 08:07
When can we expect a permanent fix? Any idea?

**Comment by awgrass** [comment] 2021-04-13 18:03
We are running on ubuntu 20.04 and Odoo 14.0-20210407 and we experience the same issue. 

Here the error log:

Error:


Traceback:
TypeError: scope.sprintf is not a function
    at QWeb.eval (eval at _compile (https://erp.epicore.co/web/content/378-31f4530/web.assets_common.js:971:178), <anonymous>:16:32)
    at QWeb.eval (eval at _compile (https://erp.epicore.co/web/content/378-31f4530/web.assets_common.js:971:178), <anonymous>:396:48)
    at QWeb.render (https://erp.epicore.co/web/content/378-31f4530/web.assets_common.js:960:20)
    at Object.__owl__.renderFn (https://erp.epicore.co/web/content/168-eedee27/web.assets_backend.js:1325:147)
    at PatchableClass.__render (https://erp.epicore.co/web/content/378-31f4530/web.assets_common.js:1277:33)
    at PatchableClass.__prepareAndRender (https://erp.epicore.co/web/content/378-31f4530/web.assets_common.js:1275:29)

Seems to be related to the latest patch, since we did not experience that problem before.

**Comment by leimantas** [comment] 2021-04-15 07:50
> We are running on ubuntu 20.04 and Odoo 14.0-20210407 and we experience the same issue.
> 
> Here the error log:
> 
> Error:
> 
> Traceback:
> TypeError: scope.sprintf is not a function
> at QWeb.eval (eval at _compile (https://erp.epicore.co/web/content/378-31f4530/web.assets_common.js:971:178), :16:32)
> at QWeb.eval (eval at _compile (https://erp.epicore.co/web/content/378-31f4530/web.assets_common.js:971:178), :396:48)
> at QWeb.render (https://erp.epicore.co/web/content/378-31f4530/web.assets_common.js:960:20)
> at Object.**owl**.renderFn (https://erp.epicore.co/web/content/168-eedee27/web.assets_backend.js:1325:147)
> at PatchableClass.__render (https://erp.epicore.co/web/content/378-31f4530/web.assets_common.js:1277:33)
> at PatchableClass.__prepareAndRender (https://erp.epicore.co/web/content/378-31f4530/web.assets_common.js:1275:29)
> 
> Seems to be related to the latest patch, since we did not experience that problem before.

solution: [#67801](https://github.com/odoo/odoo/issues/67801#issuecomment-809696901)
