### ISSUE TITLE
Error when create employee payslips with worked day 

### ISSUE THREAD

**Issue by wangchunlei** [odoo/odoo#8238] opened 2015-08-26 07:24 UTC
master:

2015-08-26 07:14:16,391 22709 ERROR odoo openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/sswy/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/sswy/odoo/openerp/http.py", line 588, in dispatch
    return self._json_response(result)
  File "/home/sswy/odoo/openerp/http.py", line 526, in _json_response
    body = simplejson.dumps(response)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/__init__.py", line 366, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/encoder.py", line 269, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/encoder.py", line 348, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/encoder.py", line 246, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <openerp.models.NewId object at 0x7f006306fd90> is not JSON serializable

**Comment by qtheuret** [comment] 2015-08-27 14:55
Can you give us more in details the use case you use to reproduce this issue ? Thanks.

**Comment by andreparames** [comment] 2015-10-07 16:40
We're having the same problem, and have confirmed it in the Runbot (commit 3e3ba3e). Steps to reproduce:

  - Create a Contract for some Employee, and set the wage, the salary structure (e.g. Base for new structures) and Working Schedule (e.g. 45 Hours/Week).
  - Create a new Payslip, selecting that Employee and that Contract (if not automatically loaded).

--

Having investigated the problem, it seems that when the `onchange_contract_id()` returns new worked days lines, the `onchange()` function in models.py auto-fills the field `payslip_id` in those lines with a `openerp.models.NewId` object, which then gets returned to the client - specifically, here:

                # force re-evaluation of function fields on secondary records
                for field_seq in secondary:
                    record.mapped(field_seq)

https://github.com/odoo/odoo/blob/3e3ba3e2b7fe13ad5bab339b580b307375566174/openerp/models.py#L5981

**Comment by andreparames** [comment] 2015-10-08 14:55
I've tracked the issue, so here's some extra info.

  - As I wrote earlier, the `onchange_contract_id()` method generates a new `Payslip Worked Days` line, which then gets processed by the code copied above.
  - That code processes a computed field called `worked_days_line_ids.payslip_id`, which updates the new Worked Days line, setting `payslip_id` to the ID of the current payslip, but since the payslip hasn't been saved yet, it gets set to `NewId`.
  - Then in [line 6002](https://github.com/odoo/odoo/blob/3e3ba3e2b7fe13ad5bab339b580b307375566174/openerp/models.py#L6002) the `onchange()` method generates a dict to send to the client, which converts the `NewId` into a tuple `(NewId, name)`. The dict now looks like this:

        {'worked_days_line_ids': [
            {'name': 'Normal Working Days paid at 100%',
             'payslip_id': (NewId, 'Payslip Name'),
             ...}],
         ...}
  - Finally, the dict is returned and converted into JSON, which blows up since it doesn't know how to convert `NewId` objects.

**Comment by rahulshinde77** [comment] 2015-12-01 15:44
Hi andreparames
I am not a techie. But even i am facing the same problem. i read the thread but dont know where to do the changes you mentioned 'I've made a temporary fix to the hr.payslip method name_get(), returning False when the id == NewId'
can you please guide me on where to find the hr.payslip?
egerly waiting for ur responce and thanks in advance

**Comment by andreparames** [comment] 2015-12-01 16:48
Hi @rahulshinde77. On [this comment](https://github.com/odoo/odoo/issues/9193#issuecomment-152109016), sbevnc showed this is a problem with third-party modules that extend the hr.payslip. Do you have any installed?

**Comment by rahulshinde77** [comment] 2015-12-09 16:22
thanks for the reply. i had installed openeducat ERP module.
Pls help.

**Comment by Yenthe666** [comment] 2018-03-21 16:12
Hi guys,

As this bug report was reported against the master version at that time and as bug reports against master are usually not handled I'm closing this.
If anybody can still reproduce this on Odoo 9, 10 or 11 then please do create a new bug report.

Regards,
Yenthe

**Closed by Yenthe666** 2018-03-21 16:12 UTC
