### ISSUE TITLE
Tax Codes cannot be duplicated, edited and saved as new

### ISSUE THREAD

**Issue by KangOdoo** [odoo/odoo#23449] opened 2018-03-04 07:29 UTC
Impacted versions: 10

Steps to reproduce:
Select Tax Code, Action, Duplicate

Current behavior:
Cannot duplicate existing Tax Code, rename, edit and save as new Tax Code as Validation Error window prevents ability to edit. This results in having to create new Tax Codes entirely rather than duplicate existing one, edit differences only and save as new Tax Code.

Expected behavior:
Duplicate, rename and save in same manner as Product, Customer, etc.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/36682465/36943221-3c34ba60-1fd9-11e8-8581-d2a2d9a23f17.png)

**Comment by sswapnesh** [comment] 2018-03-04 12:56
@KangOdoo Doing this will allow you to save Records with duplicate Tax name.
(Duplicate and Discard the Changes , There will be two records with Same Tax name)

**Comment by KangOdoo** [comment] 2018-03-04 19:45
Thanks for your suggestion but that doesn’t work as there is no option to duplicate or edit. The start and end state is viewing the Tax Code chosen to be copied, no duplicate is created.

**Comment by sswapnesh** [comment] 2018-08-23 17:55
Alternatively you can Remove Tax code --> Duplicate and Add different tax code in Both.
or Override copy method to Remove code from Vals

**Comment by sswapnesh** [comment] 2019-04-16 19:03
I believe this is Intended behaviour (At Least in current Framework )
@pedrobaeza  What do you think ?

**Comment by pedrobaeza** [comment] 2019-04-17 00:07
The name unique constraint avoids to use the duplicate function, but this is not a fault of the framework, but something to deal with in the model `copy` method (or `copy_data` one), changing the name before duplicating. It has been done with certain models like product. It would be good to do something similar on tax one, but it's not a specially complex model for not being able to copy it by hand.

Any way, this is something that is not going to be in stable for sure. Maybe for master.

**Comment by oco-odoo** [comment] 2019-09-30 10:22
This seems to work fine now (we duplicate with a different name), so it has probably been fixed since then. I'm closing the issue.

**Closed by oco-odoo** 2019-09-30 10:22 UTC
Labels: 10.0, Accounting
