### ISSUE TITLE
Bug when print an invoice with the group sale.group_sale_layout

### ISSUE THREAD

**Issue by aek** [odoo/odoo#14200] opened 2016-11-08 06:17 UTC
Impacted versions: 
Odoo 10

Steps to reproduce: 
Add to the user the group sale.group_sale_layout and try to print an invoice 

Current behavior: 
KeyError: 'price_total'
Error to render compiling AST
KeyError: 'price_total'
Template: account.report_invoice_document
Path: /templates/t/t/div/t[2]/table/tbody/t/t[2]/tr/td[7]/span
Node: <span t-field="l.price_total" t-options="{&quot;widget&quot;: &quot;monetary&quot;, &quot;display_currency&quot;: o.currency_id}"/>

Expected behavior:
Print the Group Layouted Invoice

Video/Screenshot link (optional):
**More details at:**
https://www.odoo.com/es_ES/forum/ayuda-1/question/help-problem-with-print-invoice-odoo-10-community-110504

**Comment by DipaliKhatri** [comment] 2016-11-11 10:01
@aek,
In odoo 10 price_total field is not allow.

**Comment by aek** [comment] 2016-11-11 19:33
The use of price_total field is not mine, it's on the Odoo code report template on the sale module

**Comment by CarlosPascual** [comment] 2016-11-30 12:51
@aek 
I am not an expert but this worked for me, I changed price_total for price_subtotal in the qWeb report under:
Reports/Invoices/Viewsreport_invoice_layouted
Feel free to contact me if you need some help.

Original
```
<td class="text-right" groups="sale.group_show_price_total">
<span t-field="l.price_total" t-options="{&quot;widget&quot;: &quot;monetary&quot;, &quot;display_currency&quot;: o.currency_id}"/>
</td>
```

Change

```
<td class="text-right" groups="sale.group_show_price_total">
<span t-field="l.price_subtotal" t-options="{&quot;widget&quot;: &quot;monetary&quot;, &quot;display_currency&quot;: o.currency_id}"/>
</td>
```

**Comment by aek** [comment] 2016-12-11 01:59
@CarlosPascual I'm not having the issue, I'm just reporting it so Odoo could fix it, I get it from a question in the Odoo forum and there I provide a solution, but the issue exists so I'm reporting it here

**Comment by pedrobaeza** [comment] 2018-05-01 15:08
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-05-01 15:08 UTC
Labels: 10.0, Accounting

**Comment by aek** [comment] 2018-05-04 19:42
@pedrobaeza Sure, this one is too old and easy one. It was fixed
