### ISSUE TITLE
[13] web: Report Layout. No footer in external report 

### ISSUE THREAD

**Issue by elperrofarelo** [odoo/odoo#45624] opened 2020-02-18 12:14 UTC
Impacted versions:
13
Steps to reproduce:
From company form try to print external report.
[Preview External Report-5.pdf](https://github.com/odoo/odoo/files/4219091/Preview.External.Report-5.pdf)

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by elperrofarelo** [comment] 2020-02-18 13:15
Footer appears in the invoice preview, but disappears in the pdf generated using the print button

**Comment by pedrobaeza** [comment] 2020-02-18 13:57
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by elperrofarelo** [comment] 2020-02-19 08:54
Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)? No
I'm testing Odoo V13 in Mac Osx using homebrew, no difference with Safari or Firefox browser.
It looks like a Html/scss compatibility problem

**Comment by pedrobaeza** [comment] 2020-02-19 08:55
I don't think so. I know people working with Mac OS server and this is working, so the problem is in your deployment, which is out of scope of this issue tracker, so closing.

**Closed by pedrobaeza** 2020-02-19 08:55 UTC
Labels: Need information
