### ISSUE TITLE
Sale Subscription Module --Generate Invoice Error --V10

### ISSUE THREAD

**Issue by jaronemo** [odoo/odoo#13809] opened 2016-10-14 08:47 UTC
Impacted versions: ODOO 10 Version

Steps to reproduce:
1.create sub order 0001
2. create sales order and mapping sub order 0001
3. confirm sales order and sub order 
4. sub order 0001  touch generate invoice 

Error message : 
 File "/Users/jason/odoo-dev/odoo10/enterprise/sale_contract/models/sale_subscription.py", line 227, in recurring_invoice
    self._recurring_create_invoice()
  File "/Users/jason/odoo-dev/odoo10/enterprise/sale_contract/models/sale_subscription.py", line 246, in _recurring_create_invoice
    subtype_id=self.env.ref('mail.mt_note'))
  File "/Users/jason/odoo-dev/odoo10/addons/mail/models/mail_thread.py", line 1930, in message_post_with_view
    record.message_post_with_template(False, **kwargs)
  File "/Users/jason/odoo-dev/odoo10/addons/mail/models/mail_thread.py", line 1953, in message_post_with_template
    ).create(kwargs)
  File "/Users/jason/odoo-dev/odoo10/addons/mail/models/mail_message.py", line 719, in create
    message = super(Message, self).create(values)
  File "/Users/jason/odoo-dev/odoo10/odoo/models.py", line 3802, in create
    record = self.browse(self._create(old_vals))
  File "/Users/jason/odoo-dev/odoo10/odoo/models.py", line 3890, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/Users/jason/odoo-dev/odoo10/odoo/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/Users/jason/odoo-dev/odoo10/odoo/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
ProgrammingError: can't adapt type 'mail.message.subtype'

**Comment by JKE-be** [comment] 2016-10-14 11:14
Hello, 
An opw has been already open for this issue, so it will be fixed by our internal support team as soon as possible.
Thanks for the reporting.

**Comment by JKE-be** [comment] 2016-10-14 11:14
Hello, 
An opw has been already open for this issue, so it will be fixed by our internal support team as soons as possible.
Thanks for the reporting.

**Closed by JKE-be** 2016-10-14 11:14 UTC

**Comment by jeffery9** [comment] 2016-10-14 13:45
what are the real mean for " ProgrammingError: can't adapt type " ？

**Comment by JKE-be** [comment] 2016-10-14 14:33
Usually, that arrive when a method send a browseRecord instead of an id.
We are waiting a id, but we receive a BrowseRecord that cannot be adapted to type int.

**Comment by JKE-be** [comment] 2016-10-14 14:36
@jeffery9 
In this case / this issue

```python
invoices[-1].message_post_with_view('mail.message_origin_link',
                     values={'self': invoices[-1], **'origin': sub**},
                     subtype_id=self.env.ref('mail.mt_note'))
```

`Sub` is a browseRecord, and cannot be adapted to string.

**Comment by JKE-be** [comment] 2016-10-14 14:41
In this issue, the problem is:

```python
                    invoices[-1].message_post_with_view('mail.message_origin_link',
                     values={'self': invoices[-1], 'origin': sub},
                     subtype_id=self.env.ref('mail.mt_note'))
```

subtype_id should be an integer, but are currently a browse record...

So the fix will be to replace
` subtype_id=self.env.ref('mail.mt_note')`
to
` subtype_id=self.env.ref('mail.mt_note').id
`

**Comment by jaronemo** [comment] 2016-10-17 14:18
Yes..

add  id it's ok..can generate invoice for month...
