### ISSUE TITLE
Account localization cannot install account.tax.template with more than 2 repartion lines 

### ISSUE THREAD

**Issue by aliencrash** [odoo/odoo#42998] opened 2020-01-09 05:48 UTC
Impacted versions:
13.0 
Steps to reproduce:
Create a xml data for account.tax.template. In invoice_repartition_line_ids and  refund_repartition_line_ids add 3 lines as the xml in the example:
```xml  
<record id="account_tax_taxissue" model="account.tax.template">
            <field name="chart_template_id" ref="ao_chart_template"/>
            <field name="name">TAX  Issue 1%</field>
            <field name="description">IS 1%</field>
            <field name="amount">-1</field>
            <field name="amount_type">percent</field>
            <field name="type_tax_use">sale</field>
            <field name="invoice_repartition_line_ids" eval="[(5, 0, 0),
                (0,0, {
                    'factor_percent': 100,
                    'repartition_type': 'base',
                }),

                (0,0, {
                    'factor_percent': -100,
                    'repartition_type': 'tax',
                    'account_id': ref('account_chart_xxxx'),
                }),
                (0,0, {
                    'factor_percent': 100,
                    'repartition_type': 'tax',
                    'account_id': ref('account_chart_yyyy'),
                }),
            ]"/>
            <field name="refund_repartition_line_ids" eval="[(5, 0, 0),
                (0,0, {
                    'factor_percent': 100,
                    'repartition_type': 'base',
                }),

                (0,0, {
                    'factor_percent': -100,
                    'repartition_type': 'tax',
                    'account_id': ref('account_chart_xxxx'),
                }),
                (0,0, {
                    'factor_percent': 100,
                    'repartition_type': 'tax',
                    'account_id': ref('account_chart_yyyy'),
                }),
            ]"/>
            <field name="cash_basis_transition_account_id" ref="account_chart_xyp"/>
        </record>
```

Current behavior:
While installing the localization this xml will throw a error

```pytb
  File "/home/alien/odoo/13/odoo/odoo/addons/account/models/chart_template.py", line 160, in try_loading
    template.with_context(default_company_id=company.id)._load(15.0, 15.0, company)
  File "/home/alien/odoo/13/odoo/odoo/addons/account/models/chart_template.py", line 226, in _load
    acc_template_ref, taxes_ref = self._install_template(company, code_digits=self.code_digits)
  File "/home/alien/odoo/13/odoo/odoo/addons/account/models/chart_template.py", line 512, in _install_template
    tmp1, tmp2 = self.with_context(lang=company.partner_id.lang)._load_template(company, code_digits=code_digits, account_ref=acc_ref, taxes_ref=taxes_ref)
  File "/home/alien/odoo/13/odoo/odoo/addons/account/models/chart_template.py", line 540, in _load_template
    generated_tax_res = self.with_context(active_test=False).tax_template_ids._generate_tax(company)
  File "/home/alien/odoo/13/odoo/odoo/addons/account/models/chart_template.py", line 941, in _generate_tax
    'account_id': template_account.id,
  File "/home/alien/odoo/13/odoo/odoo/models.py", line 5583, in __getitem__
    return self.browse((self._ids[key],))
```

Expected behavior:
It should be able to create the tax with all 3 lines. The the issue it thrown when in line 934 from account.chart_template  we get the variable all_tax_rep_lines with sorted invoice_repartition_line_ids and refund it regurns 4 items while in  all_template_rep_lines has 6. Se screenshot to show the code parte and the debugger variables.

Video/Screenshot link (optional):
![imagem](https://user-images.githubusercontent.com/10322162/72041367-a6f39880-32ab-11ea-9ac9-36b33f57a011.png)

![imagem](https://user-images.githubusercontent.com/10322162/72041182-1fa62500-32ab-11ea-9d1e-b1b0ae0156a8.png)

**Comment by pedrobaeza** [comment] 2020-01-09 08:52
@oco-odoo do you see something incorrect?

**Comment by oco-odoo** [comment] 2020-01-14 11:31
@pedrobaeza @aliencrash 
This seems unrelated to the fact the tax has more than two repartition lines. Such taxes exist indeed in l10n modules, and they work fine : https://github.com/odoo/odoo/blob/13.0/addons/l10n_be/data/account_tax_template_data.xml#L1196

So it's strange, indeed... @aliencrash , are you using any custom stuff next to that ? Are you sure you don't get another in the logs ? Also, the traceback you give seems incomplete; it would be good to have the entirety of it.

**Comment by nhomar** [comment] 2020-01-14 12:29
AFAICS this is a data error.

Can you try to add manually (no by data) such 3 lines and share the output here?

Then once you can do it functionally share the xml that you are using to load such example manual tax, with that we will be able to see what's the error.


Regards.

**Comment by william-andre** [comment] 2020-01-17 13:35
@aliencrash  I just tried with the same xml data you provided (only with other account.account.template ids) and it worked like a charm.

**Comment by aliencrash** [comment] 2020-01-24 09:50
Ok. But the issue is with account.tax.template no account.account.template

**Comment by william-andre** [comment] 2020-01-24 09:52
I'm talking about `account_chart_xxxx` and ´account_chart_yyyy`. I copy pasted your code in a l10n module, but I changed those to match existing accounts in the l10n I used.

**Comment by aliencrash** [comment] 2020-01-24 09:57
ok. Thank you. That means that there is something wrong from my side and not from the expression.

**Comment by oco-odoo** [comment] 2020-01-24 10:01
@aliencrash Probably, indeed. There are plenty of examples in l10n modules that you can take inspiration of to find out what the problem is, maybe it can help. I'm closing the issue. We'll reopen it if necessary :)

**Closed by oco-odoo** 2020-01-24 10:01 UTC
Labels: 13.0, Accounting, Need information

**Comment by aliencrash** [comment] 2021-01-11 19:03
I would like to reopen this issue. I tried to install l10n_be and gives me the same error. I'm in fedora 31 python 3.7.9.
So I would to try to find out is why I'm not able to install any localization with the repartition line are greater than 2.
If someone could help, I would appreciate.

**Comment by aliencrash** [comment] 2021-01-11 19:03
Traceback (most recent call last):
  File "/home/alien/odoo/14/odoo/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/home/alien/odoo/14/odoo/odoo/tools/convert.py", line 330, in _tag_function
    _eval_xml(self, rec, env)
  File "/home/alien/odoo/14/odoo/odoo/tools/convert.py", line 201, in _eval_xml
    return odoo.api.call_kw(model, method_name, args, kwargs)
  File "/home/alien/odoo/14/odoo/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/alien/odoo/14/odoo/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/alien/odoo/14/odoo/odoo/addons/account/models/chart_template.py", line 186, in try_loading
    template.with_context(default_company_id=company.id)._load(15.0, 15.0, company)
  File "/home/alien/odoo/14/odoo/odoo/addons/l10n_multilang/models/l10n_multilang.py", line 16, in _load
    res = super(AccountChartTemplate, self)._load(sale_tax_rate, purchase_tax_rate, company)
  File "/home/alien/odoo/14/odoo/odoo/addons/account/models/chart_template.py", line 251, in _load
    acc_template_ref, taxes_ref = self._install_template(company, code_digits=self.code_digits)
  File "/home/alien/odoo/14/odoo/odoo/addons/account/models/chart_template.py", line 522, in _install_template
    tmp1, tmp2 = self.with_context(lang=company.partner_id.lang)._load_template(company, code_digits=code_digits, account_ref=acc_ref, taxes_ref=taxes_ref)
  File "/home/alien/odoo/14/odoo/odoo/addons/account/models/chart_template.py", line 550, in _load_template
    generated_tax_res = self.with_context(active_test=False).tax_template_ids._generate_tax(company)
  File "/home/alien/odoo/14/odoo/odoo/addons/account/models/chart_template.py", line 987, in _generate_tax
    'account_id': template_account.id,
  File "/home/alien/odoo/14/odoo/odoo/models.py", line 5662, in __getitem__
    return self.browse((self._ids[key],))
IndexError: tuple index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alien/odoo/14/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/alien/odoo/14/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/alien/odoo/14/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/alien/odoo/14/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/alien/odoo/14/odoo/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/alien/odoo/14/odoo/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/home/alien/odoo/14/odoo/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/home/alien/odoo/14/odoo/odoo/addons/web/controllers/main.py", line 1381, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/alien/odoo/14/odoo/odoo/addons/web/controllers/main.py", line 1369, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/alien/odoo/14/odoo/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/alien/odoo/14/odoo/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-71>", line 2, in button_immediate_install
  File "/home/alien/odoo/14/odoo/odoo/addons/base/models/ir_module.py", line 73, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/alien/odoo/14/odoo/odoo/addons/base/models/ir_module.py", line 474, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/alien/odoo/14/odoo/odoo/addons/base/models/ir_module.py", line 592, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/alien/odoo/14/odoo/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/alien/odoo/14/odoo/odoo/modules/loading.py", line 455, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/home/alien/odoo/14/odoo/odoo/modules/loading.py", line 348, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/alien/odoo/14/odoo/odoo/modules/loading.py", line 221, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/home/alien/odoo/14/odoo/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/home/alien/odoo/14/odoo/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/home/alien/odoo/14/odoo/odoo/tools/convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/alien/odoo/14/odoo/odoo/tools/convert.py", line 719, in parse
    self._tag_root(de)
  File "/home/alien/odoo/14/odoo/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/home/alien/odoo/14/odoo/odoo/tools/convert.py", line 685, in _tag_root
    )) from e
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alien/odoo/14/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/alien/odoo/14/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.tools.convert.ParseError: while parsing /home/alien/odoo/14/odoo/odoo/addons/l10n_be/data/account_chart_template_configure_data.xml:4, near
<function model="account.chart.template" name="try_loading">
            <value eval="[ref('l10n_be.l10nbe_chart_template')]"/>
        </function>

**Comment by william-andre** [comment] 2021-01-11 19:17
@aliencrash So to be clear, you can't do a `odoo-bin -i l10n_be` on a checkout of `odoo/14.0` with a clean/non existent database and without any local changes on the branch?
