### ISSUE TITLE
logout issue

### ISSUE THREAD

**Issue by vuvivian** [odoo/odoo#42276] opened 2019-12-23 03:32 UTC
Impacted versions:13.0

Steps to reproduce: click  logout

Current behavior:
function logout() {
    debugger
    redirect('/web/session/logout');
    return new Promise();
}
core.action_registry.add("logout", logout);

Error ： promise dont have params
Expected behavior:

Video/Screenshot link (optional):
why return empty promise？

**Comment by pedrobaeza** [comment] 2019-12-23 11:27
Is this provoking any error or side effect?

**Comment by vuvivian** [comment] 2020-01-16 06:15
> Is this provoking any error or side effect?

Even if it does not affect subsequent business processing, but it will cause unnecessary problems when we catch all system exceptions and show them to users.

**Comment by pedrobaeza** [comment] 2020-01-16 08:42
Well, you can propose the fix as a pull request to see if it's accepted. Meanwhile, I'm going to close it as this is not a bug per se.

**Closed by pedrobaeza** 2020-01-16 08:42 UTC
Labels: Need information

**Comment by vuvivian** [comment] 2020-01-17 02:29
> Well, you can propose the fix as a pull request to see if it's accepted. Meanwhile, I'm going to close it as this is not a bug per se.

okey
