### ISSUE TITLE
Update available quantity issue

### ISSUE THREAD

**Issue by duonglong** [odoo/odoo#47969] opened 2020-03-19 05:34 UTC
Impacted versions: 13

https://github.com/odoo/odoo/blob/13.0/addons/stock/models/stock_quant.py#L400-L412
```
for quant in quants:
            try:
                with self._cr.savepoint():
                    self._cr.execute("SELECT 1 FROM stock_quant WHERE id = %s FOR UPDATE NOWAIT", [quant.id], log_exceptions=False)
                    quant.write({
                        'quantity': quant.quantity + quantity,
                        'in_date': in_date,
                    })
                    break
            except OperationalError as e:
                if e.pgcode == '55P03':  # could not obtain the lock
                    continue
                else:
                    raise
```
As i understand "self._cr.savepoint()" will make the transaction rollback to the created savepoint if lock can't be aquired on quant's row, but the quantity can never be updated since the exception handling will ignore the error and continue to process another quant, am i missing something here ? Is there any special reason for using savepoint ?

**Comment by pedrobaeza** [comment] 2020-03-19 09:19
Do you have any step to reproduce a problem? This is intended for avoiding inter-locks between several simultaneous writes. If that's the case, a new quant is created. Other code try to merge them later. This is working since several versions.

So I'm closing this unless you have a real problem with this, and not only guessing reading code.

**Closed by pedrobaeza** 2020-03-19 09:19 UTC
