### ISSUE TITLE
[mail] Not work forwarding email

### ISSUE THREAD

**Issue by JulioSerna** [odoo/odoo#1566] opened 2014-08-04 18:49 UTC
Impacted versions:
* 7.0 and above

Steps to reproduce:
* To set an outgoing mail server causing some error in "Test connection", in this case configured wrong pasword
![outgoing mail servers openerp](https://cloud.githubusercontent.com/assets/7595505/3801423/08183dba-1c04-11e4-824b-cdbd0b79b040.png)

* To create new partner "test"
![customers openerp](https://cloud.githubusercontent.com/assets/7595505/3801343/2b6e0f16-1c03-11e4-87e4-eda84a1ec09e.png)
* To create new sale order with customer "test" and send by email
![sales orders openerp](https://cloud.githubusercontent.com/assets/7595505/3801389/be6c3874-1c03-11e4-806e-9af9fa4c09de.png)
*  Go to emails and we can observed that email status is delivery failed
![emails openerp](https://cloud.githubusercontent.com/assets/7595505/3801572/c553d032-1c05-11e4-86c3-2f2e7ea12943.png)
* Set correctly the outgoing email server
![outgoing mail servers openerp](https://cloud.githubusercontent.com/assets/7595505/3801630/4b7064f0-1c06-11e4-9d75-df377dc373b4.png)
* Go to emails and try to forward email again
![emails openerp](https://cloud.githubusercontent.com/assets/7595505/3801704/239e3f00-1c07-11e4-91bc-2470e5c0a190.png)

Current behavior:
* The email is not sent

Expected behavior:
* The email should be sent

**Comment by mart-e** [comment] 2015-03-26 09:40
Hello,

Indeed this is problematic however the issue is that the list of recipients (`recipient_ids`) exists only in 8.0.
In 7.0 we have to recompute the list (e.g. using `get_partners_to_notify`) when retrying. But this means that in the scenario when only parts of the recipients got the email (e.g. some invalid email or other reason) retrying will send the email to *all* recipients, even the one that already got the email.
So unfortunately, we can not fix properly this bug (and avoid sending email to too many people) without backporting a field.
So I will put it as won't fix as I don't think we have proper solution respecting stable guidelines.

**Closed by mart-e** 2015-03-26 09:40 UTC

**Comment by nhomar** [comment] 2015-03-26 09:58
2015-03-26 3:40 GMT-06:00 Martin Trigaux <notifications@github.com>:

> So unfortunately, we can not fix properly this bug (and avoid sending
> email to too many people) without backporting a field.
> So I will put it as won't fix as I don't think we have proper solution
> respecting stable guidelines.
>

Hello Martin.

Some facts:

1. We have a bug.

2. You will not solve it.

3. The bug is due an incorrect technical decision on your side.

Then.

You do not want brake rules.

So.

What do I answer to my customer?

Opt 1.

Pay me more money to solve you a bug which you paid a solution with the
Enterprise, which was injected by an incorrect decision done by Odoo in the
change process of the behavior between v7 and v8.

Opt 2.

We (my team) absorve the cost of a solution with our time even if I do not
have the revenue generated by the Enterprise but I need to Odoo decide
brake a feature between versions.

Opt 3.

¿Proposal?

IMHO- You must be able to offer an extra module with the solution (even if
not official one) in order to solve this kind of issues, it is so tired for
us expend the time srguing things and thing waiting month for this kind of
answers men.

I am sorry for my hard words!

-- 
--------------------
Saludos Cordiales

  [image: --]
Nhomar Hernandez
[image: http://]about.me/nhomar
     <http://about.me/nhomar?promo=email_sig>
