### ISSUE TITLE
Is it possible to have the same manager approve Expenses in two different companies?

### ISSUE THREAD

**Issue by lkwangli** [odoo/odoo#17049] opened 2017-05-17 19:12 UTC
Impacted versions:9.0

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by lkwangli** [comment] 2017-05-17 19:15
Hi, 
Manager A is in both Company X and Y. (She spends 50% of her time in each company).
She is able to approve all Expenses from her subordinates in Company X. 
Short of creating a new UserID, I am unable to configure the system such that she can also approve all Expenses from her subordinates in Company Y.

Manager A is not an accountant. She's a line manager, and so she doesn't have high privilege rights in the system.

Thanks for your advice.

**Comment by Yenthe666** [comment] 2017-05-18 05:55
Hi @lkwangli,

Thank you for your report.
The Github issue tracker however is only for bugs in the official code and is not the place for ask questions. This is where we have the official Odoo forums for (odoo.com/help).
That being said: I believe it is possible if you give the manager more rights and set her up in the main company. I'm sure somebody on the forums can explain you the whole details.
Closing as this is not a bug.

Regards,
Yenthe

**Closed by Yenthe666** 2017-05-18 05:55 UTC
