### ISSUE TITLE
[10.0][purchase] Refunded returns ignored in vendor bills

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#13974] opened 2016-10-25 12:17 UTC
Impacted versions: 10

Steps to reproduce:
1. Install purchase and sale_stock.
2. Create purchase order of 20 iPad mini for ASUSTek.
3. Confirm order.
4. Recieve products.
5. Validate the stock.picking.
6. Return 5 ipads.
7. Check "To Refund" checkbox.
8. Validate the new stock.picking.
9. Go create a vendor bill from ASUSTek.
10. Choose the PO you created from the list.

Current behavior: You invoice 20 ipads.

Expected behavior: Invoice 15 ipads.

Video/Screenshot link (optional): [recording.zip](https://github.com/odoo/odoo/files/550538/out.ogv.zip)

@Tecnativa
@pedrobaeza

**Comment by pedrobaeza** [comment] 2016-10-25 15:23
Hi, @fpodoo, you told me at Odoo experience that this was solved in version 10, but we have tried without success. Sales part is OK, but not for the purchase part. Even worst, all the "To be refund" stuff is on sale_stock module, which makes this more difficult to solve without depending on it.

Please tell me how do you want me to proceed.

**Comment by bistaray** [comment] 2016-10-27 02:13
Please make this a configuration option so users can choose to NOT have Odoo work this way.

Why?

I have not heard from a single Customer in four years that they want Odoo to work this way because not a single one receives a modified Invoice after the Vendor has already issued it.  I think it may be illegal in some places for a Vendor who sends an Invoice for 20 iPads to later 'change a legal document' and Issue an Invoice for 15 iPads.

The Vendor has an accounting system also, and as soon as the Vendor has shipped 20 iPads -they have created an Invoice for 20 iPads.  This 'already issued' Vendor Invoice should be entered as it comes from the Vendor.  

One of three things then happens:
1. The Invoice is short paid - the Customer pays for 15 iPads and waits for a credit from the Vendor before the Invoice is closed. **An Invoice for 15 iPads screws this workflow up.**
2. The Invoice is fully paid - the Customer requests a credit from the Vendor and uses it on their next order, or requests a cash/wire refund. **An Invoice for 15 iPads screws this workflow up.**
3. The Customer requests a credit from the Vendor and waits until they receive it before paying only for the 15 iPads, closing the Invoice with the credit they receive. **An Invoice for 15 iPads screws this workflow up.**

This is in line with how Accounting works (for the Customers I have spoken with) in the USA.  

When 5 iPads are returned, that is a separate business transaction, with a separate Invoice.

**Comment by Yajo** [comment] 2016-10-27 07:23
Actually if you follow https://github.com/odoo/odoo/issues/13974#issue-185100018, but invoicing before the return, after you finish, the PO does not have an option to issue a return invoice.

**Comment by pedrobaeza** [comment] 2016-10-27 08:29
@bistaray, the option you are commenting is maybe anglo-saxon accounting. Anyway, this is how sales work right now, so if that's a problem, you should check also that part. 

The use case that is missing is that if you have already invoiced the full purchase order, and you return the same 5 units, then you should be able to make a supplier refund for that 5 pieces.

I have seen a new PR that I think adds this functionality: https://github.com/odoo/odoo/pull/14013

**Comment by jbeficent** [comment] 2017-03-02 18:18
@bistaray I agree that in general the returns process should be a separate process. In fact we are now designing an RMA process to cover that.

I think, however, that in cases where there were quantiy discrepancies (e.g. received more than expected for some reason) it's still good to be able to return quantity and to expect less quantity to appear in the invoice, or even to expect a refund if the vendor has already issued an invoice.

See this PR:
https://github.com/OCA/account-invoicing/pull/230

**Comment by raycarnes** [comment] 2017-03-02 18:22
@jbeficent I agree with the concept - just have never been asked by my customers/prospects.  With EDI, the Invoice often arrives before the shipment.

**Comment by jbeficent** [comment] 2017-03-02 18:34
@raycarnes have you seen the PR? Other systems use the concept of return PO.

**Comment by raycarnes** [comment] 2017-03-02 21:02
I have seen the PR, and it would be useful for returns.  

I don't think any of your ideas are bad.

I just responded based on my experience in my part of the world - that nobody I have spoken to wants Odoo to work this way. It could be a USA thing, (as Pedro intimates) or it could be just the prospects and customers I have encountered.  

I think the major reason is that the Invoice is created within minutes of the Vendor shipping the shipment to the Customer (way before any quantity differences are noticed).  Maybe that's not how it works where you are?

If the Customer receives less they see that on the Invoice and pay for what they received.  A second Invoice is created if/when the remaining quantity is sent.  I don't think you are suggesting anything different here - Odoo supports this quite nicely without modifications.

If they have to return some at the point of unloading (or even days after) they advise the Vendor, create an Invoice matching the PO, and either (1) short pay it or (2) request a credit/refund.  They don't want an Invoice showing what was received minus what was sent back.   

If they receive more, they advise the Vendor and (if they accept the additional) either ask for a new Invoice or a second Invoice, or (it they don't accept the additional) just create an Invoice matching the PO

Perhaps tomorrow I will meet someone who does business the way you describe (or someone who has purchased on of these 'other systems').  If I do, I'll be sure to let you know...

**Comment by jbeficent** [comment] 2017-03-02 21:58
Hi Ray,

See the following:

https://help.sap.com/saphelp_sbo91/helpdata/en/44/
fc227a1d3c6c30e10000000a114a6b/content.htm

https://help.sap.com/saphelp_sbo91/helpdata/en/44/fc225c1d3c6c30e10000000a114a6b/content.htm

Mostly the implemement what the PR does.

You cannot return items not connected to a PO under perpetual inventory,
because you want to return the same cost that you received.

You should not create an A/P credit not connected to the return, if you
really returned items, because that would make it hard to perform a 3 way
match (compare ordered vs. received/returned vs. Billed/refunded).

You should create an A/P refund not connected to a return PO when you are
just disputing over quantities or cost not linked to any logistic movement.

cc @pedrobaeza @eficent

**Comment by jbeficent** [comment] 2017-03-02 22:26
Here https://github.com/OCA/purchase-workflow/pull/336 I also played with
the idea to create a type of PO called return PO, as Navision or SAP ECC
does.

**Comment by bistaray** [comment] 2017-03-03 23:00
Thanks for the additional information!!

**Comment by alexis-via** [comment] 2018-01-10 21:54
For me, the real-life scenario is the following:

1. Install purchase and sale_stock.
2. Create purchase order of 20 iPad mini for ASUSTek.
3. Confirm order.
4. Recieve products.
5. Validate the stock.picking.
6. Create supplier invoice from PO. It creates an invoice for 20 ipads. Validate it.
7. On the confirmed incoming picking, click on the button "Return" and set the wizard to 5 ipads and make sure that the option "To Refund" is enabled.
8. Validate the return picking.
9. On the PO, click on the button "Invoice" and "Create". It creates a supplier invoice with 0 ipads. That's the bug, it should create a supplier refund for 5 ipads.

And I think that it corresponds to the real-life scenarios, as underlined in some comments.

**Comment by tarbib** [comment] 2018-02-01 03:03
Hello I am having the same issue.

Are there any actions triggered when enabled "To refund" ?

**Comment by aheficent** [comment] 2018-02-20 12:20
ping @qdp-odoo

**Comment by pedrobaeza** [comment] 2018-02-23 11:47
I don't think this is going to be fixed, and more recently that they have hidden the field on vendor refunds. @Yajo close the issue and we have the module purchase_stock_picking_return_invoicing in the PR https://github.com/OCA/account-invoicing/pull/283 for covering that flow. Please review that one.

**Closed** 2018-02-26 11:33 UTC
Labels: 10.0, Accounting
