### ISSUE TITLE
Odoo11 Mail Compose Message onchange_template_id_wrapper error 

### ISSUE THREAD

**Issue by isserver1** [odoo/odoo#33699] opened 2019-05-27 19:49 UTC
Impacted versions: 
Odoo 11.0-20190527 (Community Edition) from odoo nightly
Highly likely after this commit (because version 20190515 still working fine): [](https://github.com/odoo/odoo/commit/95f8eb410e81e11f1bd40800714fc0f585724916) 

Steps to reproduce:
1. Open CRM Lead, Task or any record with Chatter
2. Open message in full-composer mode.

Current behavior:
Error occurs but wizard still opens and message is sent.

Expected behavior:
No error should occur

Video/Screenshot link (optional):
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5195, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5021, in _onchange_eval
    method_res = method(self)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/wizard/mail_compose_message.py", line 345, in onchange_template_id_wrapper
    setattr(self, fname, value)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 966, in __set__
    value = self.convert_to_cache(value, record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 2103, in convert_to_cache
    ids = OrderedSet(command[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/misc.py", line 990, in __init__
    self._map = OrderedDict((elem, None) for elem in elems)
TypeError: unhashable type: 'list'


```

**Comment by pedrobaeza** [comment] 2019-05-27 23:10
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by isserver1** [comment] 2019-05-28 08:49
Hi, this is how to reproduce it on runbot (http://528620-11-0-c868da.runbot15.odoo.com):
1. Go to Sales
2. Open SO046
3. Go to chatter.
4. Open Mail Composer in full screen
![image](https://user-images.githubusercontent.com/2234999/58464538-89b7f280-813e-11e9-874a-a7aa0691f2e2.png)

**Comment by Yenthe666** [comment] 2019-05-28 09:23
Same report as https://github.com/odoo/odoo/issues/33712.
I'm closing this one in favour of the other one as it is more transparant.

**Closed by Yenthe666** 2019-05-28 09:23 UTC
Labels: Need information
