### ISSUE TITLE
Import Inventory Adjustment pick wrong product to update qty.

### ISSUE THREAD

**Issue by gtopba** [odoo/odoo#27016] opened 2018-09-16 23:30 UTC
**Impacted versions:**
11.0
**Steps to reproduce:**
Import Inventory Adjustment by specifying desired line_ids/product_qty for a product line_ids/product_id/id. 

**Current behavior:**
Go to the web and check the product name in the imported Inventory Adjustment. You will find out that it is not the product you want to update qty.

**Expected behavior:**
Correctly update the product qty. 

I have also tested with the odoo 12.0 in runbot, it has the same behavior. 

Thanks

**Comment by pedrobaeza** [comment] 2018-09-17 08:51
Sorry, this is not an Odoo issue, but a question on how to use import feature, as this is working as expected. The problem is that you are not using proper ID (maybe you are mixing product.template ID instead of product.product ID), or using external ID instead of internal ID.

You should make additional questions on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Closed by pedrobaeza** 2018-09-17 08:51 UTC
Labels: 11.0, Logistics
