### ISSUE TITLE
Mass mailer: UI does not show editor

### ISSUE THREAD

**Issue by fredericmora** [odoo/odoo#16617] opened 2017-04-25 00:07 UTC
Impacted versions:odoo-10.0_20170424-1

Steps to reproduce:
1. In mass mailing, click New
2. Try to edit the body of the message under "Mail body". Nothing shows up. No JS editor, no text box.

Current behavior:
Nothing shows up. No JS editor, no text box. Verified on Firefox 52.0 for Linux and Chrome 58.0 for Linux.

Expected behavior:
Should be able to edit the mail body

Video/Screenshot link (optional):

**Comment by elevationO** [comment] 2017-05-01 16:47
I too have this issue.

**Comment by Yenthe666** [comment] 2017-05-03 07:49
Hi @fredericmora,

Thanks for your report.
I've just tested this on the latest Odoo 10.0 with chrome 52.0 and could not reproduce this. Could you try this again on the newest Odoo (runbot.odoo.com) or alternatively update your Odoo codebase? 

Regards,
Yenthe

**Comment by Yenthe666** [comment] 2017-05-30 08:53
Hi @fredericmora,

There is been no feedback in almost a month and we cannot reproduce this issue.
I'm closing this report for this reason. If you still face this and can provide more information about how to reproduce it please let me know. I'll re-open this issue if you can give us more information on how to reproduce it.

Regards,
Yenthe

**Closed by Yenthe666** 2017-05-30 08:53 UTC
Labels: need informations
