### ISSUE TITLE
Text overlap of table header on qweb report

### ISSUE THREAD

**Issue by RamlaFtouh** [odoo/odoo#35549] opened 2019-08-08 08:03 UTC
Impacted versions: 12.0

Steps to reproduce:
When adding a big text in any cell  on tables (sale lines, invoice lines, purchase lines... ) 

Current behavior:
The text overlap the table header on qweb documents .

Expected behavior:
The rest of the text should be shown on the next page, without overlapping the table header

Video/Screenshot link (optional):

![bug_overlap_header](https://user-images.githubusercontent.com/30926992/62685858-62419980-b9bb-11e9-8557-d19d0cfd2026.PNG)

**Comment by pedrobaeza** [comment] 2019-08-08 08:07
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by RamlaFtouh** [comment] 2019-08-08 08:38
Hello Pedro Baeza, 

I reproduced the pug on http://583269-12-0-3f634f.runbot17.odoo.com. 
You can check the SO153.

![bug_overlap_header_2](https://user-images.githubusercontent.com/30926992/62688011-d5e5a580-b9bf-11e9-8f8c-ea0300bf8f54.PNG)

![quotation_test_bug_overlap_header](https://user-images.githubusercontent.com/30926992/62688121-29f08a00-b9c0-11e9-8315-86102d5242cd.PNG)

[Quotation - SO153.pdf](https://github.com/odoo/odoo/files/3480643/Quotation.-.SO153.pdf)

Greetings, 
Ramla Ftouh

**Comment by pedrobaeza** [comment] 2019-08-08 09:03
It's not overlapping at all in runbot test, although not very "beauty", but I'm afraid there's no better solution dealing with wkhtmltopdf.

@mart-e I think this has been discussed other times, isn't it?

**Comment by mart-e** [comment] 2019-08-08 09:08
It is that same as  #34806 right?

**Comment by pedrobaeza** [comment] 2019-08-08 09:13
Yes, indeed, and that's why it sounds me you were involved. Closing this one then as duplicated.

**Closed by pedrobaeza** 2019-08-08 09:13 UTC
Labels: Need information

**Comment by RamlaFtouh** [comment] 2019-08-08 09:16
@pedrobaeza 
@mart-e 

Okay, so  please is there any solution for these problem, I checked the  problem from  #34806 , but no solution is given yet.

**Comment by pedrobaeza** [comment] 2019-08-08 09:18
No, no solution. As I guessed, it's not an easy one and very specific use case (most texts are not so long). Customize your layout if it's a critical problem for you.

**Comment by RamlaFtouh** [comment] 2019-08-08 09:41
Okay, thank you for your feedback.
