### ISSUE TITLE
[saas-14] Field city_id not is visible when country_id.enforce_citie =True

### ISSUE THREAD

**Issue by maitaoriana** [odoo/odoo#19701] opened 2017-09-26 02:39 UTC
Impacted versions: 
saas-14, master
Steps to reproduce:
- Install module City Addresses (base_address_city)
- 'Enforce cities' field of Mexico country set to True
- Country of company set to Mexico
- Create a partner with Mexico country

Current behavior:
-  Field city_id invisible
![test odoo](https://user-images.githubusercontent.com/17258001/30839064-694e9d78-a23d-11e7-9c7b-85f7d939e535.png)

Expected behavior:
- Field city_id [visible](https://github.com/odoo/odoo/blob/saas-14/addons/base_address_city/models/res_partner.py#L32)
![new odoo](https://user-images.githubusercontent.com/17258001/30839063-69379452-a23d-11e7-8d30-7f96251f6503.png)

Video/Screenshot link (optional):
[Video](https://www.youtube.com/watch?v=LdompKDvLXg&feature=youtu.be)

opw-774206

**Comment by luistorresm** [comment] 2017-09-26 14:03
CC @qdp-odoo

**Comment by nim-odoo** [comment] 2017-10-06 11:28
This is caused by https://github.com/odoo/odoo/commit/7dd344129e2ae30a857f72fdf61dca6e40768983
The context is changed here: 
https://github.com/odoo/odoo/blob/saas-14/odoo/addons/base/res/res_partner.py#L52

However, `Partner` is not returned, so the context key `no_address_format` is never set in the context at this point:
https://github.com/odoo/odoo/blob/saas-14/addons/base_address_city/models/res_partner.py#L23
Therefore, we never reach this part of code:
https://github.com/odoo/odoo/blob/saas-14/addons/base_address_city/models/res_partner.py#L25-L39

**Comment by qdp-odoo** [comment] 2017-10-09 12:26
@smetl can you link your PR/bugfix here please?

**Comment by smetl** [comment] 2017-10-09 12:49
Fixed on saas-14 at revision:
https://github.com/odoo/odoo/commit/13b25fedbfb817726ac92674c7386c76c23c8c3c
https://github.com/odoo/odoo/commit/165d13bdb5439e4ad78f31dc97ab99a314352d65

**Closed by smetl** 2017-10-09 12:49 UTC
Labels: OE
