### ISSUE TITLE
[BUG] Odoo doesn't update images on res.partner when multicompany is activated

### ISSUE THREAD

**Issue by Rodasac** [odoo/odoo#36249] opened 2019-08-29 17:56 UTC
Impacted versions: 12

Steps to reproduce: Try to update the image of a contact / partner when multicompany has been activated and there are several companies created.

Current behavior: Odoo does not update the image and returns to the previous one when saving if before there was an image.

Expected behavior: Odoo must update the image

Video/Screenshot link (optional):

Before save:
![Before](https://i.ibb.co/xX0GfYj/Deepin-Screenshot-Seleccionar-rea-20190829134150.png)

After save:
![After](https://i.ibb.co/mGbNKP0/Deepin-Screenshot-Seleccionar-rea-20190829134208.png)

**Comment by pedrobaeza** [comment] 2019-08-29 22:33
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Yenthe666** [comment] 2019-12-03 07:49
Hi there,

Since there has been no extra information in quite a while I'm closing this issue.
Don't hesitate to respond back with detailed information and then we'll reopen this issue.

Regards,
Yenthe

**Closed by Yenthe666** 2019-12-03 07:49 UTC
Labels: Need information
