### ISSUE TITLE
Multiple database display company logo abnormal deviant

### ISSUE THREAD

**Issue by lonelyleaves** [odoo/odoo#24875] opened 2018-05-23 14:27 UTC
Impacted versions:8&10

Steps to reproduce:company logo about login page

Current behavior: open localhost:8069/web/login

Expected behavior:page‘s  logo is the company logo of the current database

Video/Screenshot link (optional):
https://github.com/OCA/web/files/2022378/about.company_log.zip

**Comment by pedrobaeza** [comment] 2018-05-23 14:30
This is nothing about Odoo itself, but browser's cache system. Refreshing the page with Shift+F5 renovates the logo (but putting the company of the admin user, as no user is still loggued in). That's the reason why the browser keeps initially last used logo, to preserve that thing if possible.

Closing as no real issue, and please close the same the issue at OCA/web if it's for the same reasoning.

**Closed by pedrobaeza** 2018-05-23 14:30 UTC

**Comment by pedrobaeza** [comment] 2018-05-23 14:42
The problem is with your deployment system. Using different URLs per BD with dbfilter, this doesn't happen.
