### ISSUE TITLE
[13.0] [utm] Asset loadin error

### ISSUE THREAD

**Issue by tpa-odoo** [odoo/odoo#47106] opened 2020-03-06 15:19 UTC
Impacted versions: 13.0

Steps to reproduce: Install of utm module

Current behavior: Error
GET /utm/static/src/scss/web.assets_backend/utm_views.scss.css net::ERR_ABORTED 404 (NOT FOUND)

Expected behavior: No error

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2020-03-06 15:23
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/13.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).

**Comment by tpa-odoo** [comment] 2020-03-06 15:29
> Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/13.0/setup/install.html.
> 
> I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.
> 
> You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).

Please inspect element and you will see error easily:
please open issue as welas pull request: https://github.com/odoo/odoo/pull/47105

**Comment by pedrobaeza** [comment] 2020-03-06 15:43
I'm not reopening the issue because you already have a pull request, and I let others to judge if this pull request is needed.

**Comment by pedrobaeza** [comment] 2020-03-06 15:50
Closing, what I want to keep opened is the PR. Please don't duplicate things: or an issue, or a pull request, not both.

**Closed by pedrobaeza** 2020-03-06 15:50 UTC
