### ISSUE TITLE
[13.0] Odoo Navbar appears very late.

### ISSUE THREAD

**Issue by MojtabaAp** [odoo/odoo#47151] opened 2020-03-09 07:40 UTC
Hi
Odoo Navbar appears very late, sometimes taking about 10 to 15 seconds depending on the size of the page. please check it.
![Odoo Menu](https://user-images.githubusercontent.com/36371067/76192175-6a361600-61f6-11ea-9041-f9d352cea13b.gif)

**Comment by pedrobaeza** [comment] 2020-03-09 07:58
I'm not able to reproduce this problem, so unless you specify the steps to get the navbar appearing very late, this can't be solved.

**Comment by MojtabaAp** [comment] 2020-03-09 08:12
@pedrobaeza 
I checked and found that Odoo added the o_menu_loading class to the navbar and this would hide the menu and make changes to the menu elements. when page load done remove this class from navbar.  if page loads take 15 seconds it remove after 15seconds. This is an interesting method you used, but it makes load late and annoys the customer.

**Comment by pedrobaeza** [comment] 2020-03-09 08:14
Then the problem is that your page is taking 15 seconds to load, and that's the problem. That has been done on purpose for avoiding to click when not everything has been loaded, leading to possible problems.

Closing then as expected behavior. Try to speed up your page.

**Closed by pedrobaeza** 2020-03-09 08:14 UTC
Labels: Need information
