### ISSUE TITLE
[9.0] @api.constains with fields from product.product and fields from product.template

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#17312] opened 2017-05-30 15:14 UTC
This bug is related to a problem we have in the OCA module sale_rental for odoo v9:
https://github.com/OCA/sale-workflow/pull/419

In this module, in the class ProductProduct, we add a constraint:

```
@api.constrains('rented_product_id', 'must_have_dates', 'type', 'uom_id')
```
The field 'rented_product_id' is on product.product and the fields 'must_have_dates', 'type' and 'uom_id' are on product.template.
When we create a new product, we get this warning in the logs:
```
2017-05-30 15:03:43,544 17408 WARNING o9_test1 openerp.models: method product.product._check_rental: @constrains parameter 'must_have_dates' is not writeable
2017-05-30 15:03:43,544 17408 WARNING o9_test1 openerp.models: method product.product._check_rental: @constrains parameter 'type' is not writeable
2017-05-30 15:03:43,544 17408 WARNING o9_test1 openerp.models: method product.product._check_rental: @constrains parameter 'uom_id' is not writeable
```

It seems to be linked to this commit of @rco-odoo in december 2016:
https://github.com/odoo/odoo/commit/64249936e82926353350a0db8490eb6b17fe5941
and, in the comments of the commit, @JonathanStein had already spotted the problem.

@rco-odoo Do you think there is a solution to avoid this warning ?

**Comment by rco-odoo** [comment] 2017-06-01 08:18
The issue is fixed in version 8.0.
The fix will be forward-ported soon to 9.0 and 10.0.

**Closed by rco-odoo** 2017-06-01 08:18 UTC
