### ISSUE TITLE
[11.0][Enterprise] Entering WorkOrder tablet view through tree view adds save/discard header

### ISSUE THREAD

**Issue by MartinAavastik** [odoo/odoo#33263] opened 2019-05-08 15:46 UTC
Impacted versions:
Enterprise 11.0
Steps to reproduce:
This in enterprise WO tablet view. I used runbot to check.

1.On Manufacturing dashboard,
click with workcenter with WOs(workorders)
2. Next change from kanban view to tree view.
click on the work order.

**Current behavior**:
![Selection_101](https://user-images.githubusercontent.com/8569032/57388406-c7210400-71c0-11e9-90d6-2c2d000ffefc.png)
View opens with save/discard header

**Expected behavior**:
Not show save/discard as it happens with when clicking on WO in kanban view
![Selection_102](https://user-images.githubusercontent.com/8569032/57388495-fc2d5680-71c0-11e9-8bbd-210f7893e136.png)

Video/Screenshot link (optional):

**Comment by sle-odoo** [comment] 2020-01-08 16:04
Cannot reproduce, probably fixed in the meantime.

**Closed by sle-odoo** 2020-01-08 16:04 UTC
Labels: 11.0, Logistics
