### ISSUE TITLE
(<type 'exceptions.Exception'>, Exception('tostring() has been removed. Please call tobytes() instead.\nidentity=[ImageReader@0x7f9772051190]\n handle_pageBegin args=()',), <traceback object at 0x7f9773431878>)

### ISSUE THREAD

**Issue by cycleuzb** [odoo/odoo#12524] opened 2016-06-21 20:39 UTC
Hi all,

have a big real problem when want to print on pdf not work and no emails to send here is the problem 👍 

tostring() has been removed. Please call tobytes() instead.
identity=[ImageReader@0x7f9772051190]
handle_pageBegin args=()

(<type 'exceptions.Exception'>, Exception('tostring() has been removed. Please call tobytes() instead.\nidentity=[ImageReader@0x7f9772051190]\n handle_pageBegin args=()',), <traceback object at 0x7f9773431878>)

I think that the problem come from Python module after update maybe im a looser...

**Comment by bplancher** [comment] 2016-06-24 12:38
Hello,

I may be wrong but the tobytes() instead of tostring() make me think about python 2 and 3 conflict (but not sure). Have you updated PIL / pillow to newer version (>3) ?

Hope it helps in some way,
Regards

**Comment by cycleuzb** [comment] 2016-06-24 13:20
Hello,

How i may update it maybe some helps to me ??

Thank you 

Envoyé de mon iPhone

**Comment by bplancher** [comment] 2016-06-24 13:24
No sorry,

do not update this module !
I asked this to see what you did to reach this bug, but don't do this ^^

Did you do something special before having this bug ?
Have you ever try to print a PDF before ? (did it work before ?)
Have you changed anything in your Odoo installation just before this bug ?

Regards

**Comment by cycleuzb** [comment] 2016-06-24 20:04
Hello,

No i alredy print with pdf with now problem. But after maybe its update who have a problem....

I try to create a new base and pdf work with it fine.... 

Thnks

Envoyé de mon iPhone

**Comment by Yenthe666** [comment] 2018-04-19 12:50
Hi there,

Do you still face this issue? Can you reproduce it on the latest Odoo instance at runbot.odoo.com?

Regards,
Yenthe

**Comment by pedrobaeza** [comment] 2018-04-25 23:08
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above and any way, there's no answer.

**Closed by pedrobaeza** 2018-04-25 23:08 UTC
Labels: Need information
