### ISSUE TITLE
[13.0] website_blog javescript error

### ISSUE THREAD

**Issue by nanxiaomo** [odoo/odoo#44621] opened 2020-02-05 04:07 UTC
Impacted versions:
odoo version 13.0

Steps to reproduce:
on the website blog ,when i add photo to the blog.  i click this picture in the webpage.
there is  Javescript error   
![image](https://user-images.githubusercontent.com/13805164/73810014-6b9ba980-4818-11ea-9ec7-858595e162b9.png)

Current behavior:
I have tested it in chrome and FireFox. Both of them are error
![image](https://user-images.githubusercontent.com/13805164/73809614-2165f880-4817-11ea-8a5b-4006941b6b0c.png)
Error:
IndexSizeError: Index or size is negative or greater than the allowed amount
![image](https://user-images.githubusercontent.com/13805164/73809867-eca67100-4817-11ea-8153-cc74ebb4e4be.png)

```
http://www.odoo-hilines.top/web/content/32778-1ce5d5b/2/web.assets_frontend_lazy.js:446
Traceback:
getSelection@http://www.odoo-hilines.top/web/content/32778-1ce5d5b/2/web.assets_frontend_lazy.js:446:449
popOver@http://www.odoo-hilines.top/web/content/32778-1ce5d5b/2/web.assets_frontend_lazy.js:447:210
init/<@http://www.odoo-hilines.top/web/content/32778-1ce5d5b/2/web.assets_frontend_lazy.js:444:324
dispatch@http://www.odoo-hilines.top/web/content/25049-be5fb60/2/web.assets_common_lazy.js:925:447
add/elemData.handle@http://www.odoo-hilines.top/web/content/25049-be5fb60/2/web.assets_common_lazy.js:911:166
```
Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2020-02-05 07:16
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos. In this case, put on debug mode with assets for having the proper JS stacktrace.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Yenthe666** [comment] 2020-03-08 19:29
I'm closing this bug report as there has been no response/feedback to the questions asked by @pedrobaeza

**Closed by Yenthe666** 2020-03-08 19:29 UTC
Labels: Need information
