### ISSUE TITLE
[10.0]negative values are not interpreted in wkhtml reports

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#21468] opened 2017-12-06 12:17 UTC
Impacted versions:
latest v10 release up to date from git 

Steps to reproduce:
add a negative unit price in a quotation
print the pdf

Current behavior:
negative values don't appear in the report

Expected behavior:
negative symbol must appear

**Comment by gaelTorrecillas** [comment] 2017-12-06 12:23
hello,

we have two screens:
- view in Odoo, we have the negative values : 
![view](https://user-images.githubusercontent.com/16572874/33661489-6d38c944-da88-11e7-83f2-42ece22ab92f.png)

- PDF, we don't have our negative values
![quote](https://user-images.githubusercontent.com/16572874/33661488-6d1982d2-da88-11e7-805a-1b2d7c98a490.png)

**Comment by Yenthe666** [comment] 2017-12-06 12:26
Duplicate of https://github.com/odoo/odoo/issues/17093

**Closed by Yenthe666** 2017-12-06 12:26 UTC
