### ISSUE TITLE
[8.0]How to set default sales journal

### ISSUE THREAD

**Issue by pk299** [odoo/odoo#26864] opened 2018-09-09 18:57 UTC
**Impacted versions: 8.0**

**Steps to reproduce:**
My default currency is GBP and I have setup 5 sales journal
Sales Journal AUD
Sales Journal CNY
Sales Journal GBP
Sales Journal HKD
Sales Journal EUR
when create invoice I want to set Sales Journal GBP as default journal
**Current behavior:**
I try to override _default_journal method. It set Sales Journal GBP but after a second it automatic change with Sales Journal AUD
**Expected behavior:**
I want to set Sales Journal GBP as default journal
Video/Screenshot link (optional):

![screen shot 2018-09-10 at 12 21 13 am](https://user-images.githubusercontent.com/43117858/45267722-bc766980-b48f-11e8-973d-85f6f2d288bc.png)

**Comment by sswapnesh** [comment] 2018-09-17 16:59
8.0 is no Longer Supported. You can use [forum]( https://www.odoo.com/forum/help-1) Instead.

**Comment by pedrobaeza** [comment] 2018-09-17 17:02
Indeed. Only last 3 versions are officially supported. If you still reproduces this problem in upper versions, please put another issue indicating the steps in new version (note that v9 is hardly supported as we are only 1 month to the new version).

Closing by the reason above.

**Closed by pedrobaeza** 2018-09-17 17:02 UTC
