### ISSUE TITLE
UI error 

### ISSUE THREAD

**Issue by andrestone** [odoo/odoo#30438] opened 2019-01-22 13:31 UTC
Impacted versions:
12.0

Steps to reproduce:
Install Expenses module in a new database with demo data
Click on a product inside the registered expense

Current behavior:
exception

Expected behavior:
open the product view

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/7958086/51538739-5d1f6180-1e52-11e9-9074-485c0f03b255.png)

**Comment by pedrobaeza** [comment] 2019-01-22 13:52
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by andrestone** [comment] 2019-01-22 15:23
It isn't reproduceable in the runbot environment.

My environment is quite easily replicable, though:
```$ docker run -d -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo -e POSTGRES_DB=postgres --name db postgres:10```
```$ docker run -p 8069:8069 --name odoo --link db:db -t odoo```

**Comment by pedrobaeza** [comment] 2019-01-22 17:36
I have just tried in runbot with the DB `base`, and installing expenses module, there's no problem, so I'm afraid this is something in your deployment.

Closing until further proofs.

**Closed by pedrobaeza** 2019-01-22 17:36 UTC
Labels: Need information

**Comment by andrestone** [comment] 2019-01-22 18:01
> I have just tried in runbot with the DB `base`, and installing expenses module, there's no problem, so I'm afraid this is something in your deployment.
> 
> Closing until further proofs.

Alright. Going to post it at the docker github.
