### ISSUE TITLE
Odoo 10 App installation error: ParseError: "You cannot create a new user from here.

### ISSUE THREAD

**Issue by gigamare** [odoo/odoo#14750] opened 2016-12-17 03:48 UTC
Impacted versions:
10 e
Partner
Windows installation

Steps to reproduce:
Odoo 10 just installed, basic information there with 3 users and basic company general settings in place.

Trying to install 'Lunch' or 'Mass Mailing'
-as Admin
-As User with Settings rights

Current behavior:
Testing version 10 and it was working fine. Was able to install modules.
Suddenly started to get error messages when installing new Apps. See error below:

Odoo Server Error

Traceback (most recent call last):
  File "C:\odoo\server\odoo\http.py", line 638, in _handle_exception
 --cut off to save space--
  File "C:\odoo\server\odoo\addons\base\ir\ir_model.py", line 1180, in _update
  File "C:\odoo\server\odoo\addons\auth_signup\models\res_users.py", line 141, in create
  File "C:\odoo\server\odoo\addons\mail\models\res_users.py", line 46, in create
ParseError: "You cannot create a new user from here.
 To create new user please go to configuration panel.
71
Go to the configuration panel" while parsing file:///C:/odoo/server/odoo/addons/lunch/security/lunch_security.xml:44, near
<record id="base.default_user" model="res.users">
            <field name="groups_id" eval="[(4,ref('lunch.group_lunch_manager'))]"/>
        </record>

-Having trying to find solution, like adding Group user rights for Admin for different Lunch Objects using Name 'lunch.group_lunch_manager'
But no luck, same error always.

Expected behavior:
-Apps installed OK.

Video/Screenshot link (optional):
-NA

**Comment by sudipta-dapl** [comment] 2017-01-02 11:20
I am also getting the same error.
![screenshot from 2017-01-02 16 49 42](https://cloud.githubusercontent.com/assets/24808973/21588317/89c0ae6a-d10b-11e6-9ac0-2baa30874de5.png)

**Comment by asp** [comment] 2017-12-12 20:59
We have this happening now. We have 10 apps installed and tried to add "Manufacturing".

We are on Odoo 10.0-20171212 (Community Edition) running in an LXC container on Ubuntu 16.04.

**Comment by asp** [comment] 2017-12-12 21:08
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 411, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 485, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/registry.py", line 83, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 845, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 915, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 796, in parse
    self.parse(rec, mode)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 799, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 707, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_model.py", line 1229, in _update
    record = record.create(values)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/auth_signup/models/res_users.py", line 144, in create
    user = super(ResUsers, self).create(values)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/mail/models/res_users.py", line 47, in create
    raise exceptions.RedirectWarning(msg, action.id, _('Go to the configuration panel'))
ParseError: "You cannot create a new user from here.
 To create new user please go to configuration panel.
71
Go to the configuration panel" while parsing /usr/lib/python2.7/dist-packages/odoo/addons/mrp/security/mrp_security.xml:25, near
<record id="base.default_user" model="res.users">
        <field name="groups_id" eval="[(4,ref('mrp.group_mrp_manager'))]"/>
    </record>

**Comment by ivanporras** [comment] 2018-01-09 22:46
I have the same error, Any solution??

Thank you!!

**Comment by Yenthe666** [comment] 2018-01-10 08:17
Hey all,

Has anybody found  a clear way to reproduce this? Can you reproduce this on an official runbot (runbot.odoo.com)?

Regards,
Yenthe

**Comment by nehemiascr** [comment] 2018-02-17 13:57
I just reproduced this error in runbot odoo 11:
I created 3 contacts, exported them and with the .csv tried to create user accounts with the referenced parter.

<img width="882" alt="error_in_runbot" src="https://user-images.githubusercontent.com/1874087/36341720-1ce6a9a2-13b8-11e8-9b0c-c200732a3c8b.png">

csv:
"id","email","name"
"__export__.res_partner_1797","ana@hello.com","ana"
"__export__.res_partner_1796","juan@hello.com","juan"
"__export__.res_partner_1798","maria@hello.com","maria"

**Comment by nehemiascr** [comment] 2018-02-17 16:34
[I realized](https://www.odoo.com/forum/help-1/question/create-user-from-importing-user-csv-89531) I was getting this error because I wasn't providing values for the login field, I believe my issue is unrelated to @gigamare 's

**Comment by Yenthe666** [comment] 2018-03-19 09:43
Closing as there has been no feedback by the creator on this issue and as nehemiascr pointed out it was probably unrelated.

**Closed by Yenthe666** 2018-03-19 09:43 UTC
Labels: 10.0, Need information

**Comment by roller24** [comment] 2019-01-24 00:13
I think this error is due to deleting the demo data on the community version. I deleted the demo user, and some demo data and was faced with the same error after doing so. I had success installing 5 apps prior to doing so. After using those apps and deleting some records and the demo user, the error popped at every attempt to install another app.

**Comment by nelsonhoover** [comment] 2019-02-20 19:55
Did a fresh install of a preconfigured Odoo system from TurnKey Linux and deleted the demo user, then tried to install the Project app. I got this same error.

Did another fresh install from the same source, left the demo user in place, then tried to install the Project app. It worked perfectly.
