### ISSUE TITLE
[Odoo 12] psycopg2: missing From-clause entry for table

### ISSUE THREAD

**Issue by viechsross** [odoo/odoo#35313] opened 2019-07-31 03:35 UTC
Hello everyone ! 
I got problem with missing From-clause in odoo 12 when I tried into tree of data and it show this error. what I did wrong?
Please help to share your solution.

Thanks in advance.

Screenshot here :
![image](https://user-images.githubusercontent.com/51958339/62181571-e5d90600-b37d-11e9-9bf4-a7ea42f70122.png)

**Comment by pedrobaeza** [comment] 2019-07-31 07:41
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2019-07-31 07:41 UTC
