### ISSUE TITLE
Failed to load server-wide module `None`

### ISSUE THREAD

**Issue by zbik2607** [odoo/odoo#14048] opened 2016-10-28 11:22 UTC
Impacted versions:  8.0.20161028

Steps to reproduce: Update debian odoo system with todays nightly repository

Current behavior: System error:

2016-10-28 11:19:10,337 28762 ERROR ? openerp.service.server: Failed to load server-wide module `None`.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 878, in load_server_wide_modules
    openerp.modules.module.load_openerp_module(m)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/module.py", line 315, in load_openerp_module
    __import__('openerp.addons.' + module_name)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/module.py", line 79, in load_module
    f, path, descr = imp.find_module(module_part, ad_paths)
ImportError: No module named None

Probably duplicate: #14045
Expected behavior: No start errors

**Comment by Armitxes** [comment] 2016-10-28 12:17
Just took the newest sources, got the same issue. When trying to access odoo over the browser, odoo just returns a 404.

**Comment by odony** [comment] 2016-10-28 13:02
We apologize for the trouble, this problem is caused by a [bugfix](https://github.com/odoo/odoo/commit/5ee4344efd0074fac4006984c1eb1ccc4f335518) that enables the use of the `server_wide_modules` configuration option, which was previously ignored.

You can fix your issue immediately by removing the line `server_wide_modules = None` that is in your Odoo configuration file. The configuration file is either located in `$HOME/.openerp_serverrc`,  `$HOME/.odoorc`, next to your odoo/openerp executable, or the location is explicitly passed as `-c <config_file>` to the Odoo server.

Alternatively, please update your source code as soon as the bug is closed, we will update the system to handle this case gracefully.

**Comment by odony** [comment] 2016-10-28 13:41
The bug has been fixed by #14051, so if you update your source code you should not get the error anymore.

**Closed by odony** 2016-10-28 13:41 UTC
