### ISSUE TITLE
Duplicate database error

### ISSUE THREAD

**Issue by joyinfo** [odoo/odoo#13633] opened 2016-09-29 09:28 UTC
Impacted versions:
saas-13

Steps to reproduce:
Duplicate database in link of "web/database/manager"

Current behavior:
in the browser:
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application

in the log:

2016-09-29 09:26:39,604 11273 ERROR crm werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/git/odoo-saas-13/odoo/service/server.py", line 246, in app
    return self.app(e, s)
  File "/git/odoo-saas-13/odoo/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/git/odoo-saas-13/odoo/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/git/odoo-saas-13/odoo/http.py", line 1306, in **call**
    return self.dispatch(environ, start_response)
  File "/git/odoo-saas-13/odoo/http.py", line 1280, in **call**
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 588, in **call**
    return self.app(environ, start_response)
  File "/git/odoo-saas-13/odoo/http.py", line 1476, in dispatch
    response = self.get_response(httprequest, result, explicit_session)
  File "/git/odoo-saas-13/odoo/http.py", line 276, in **exit**
    self._cr.commit()
  File "/git/odoo-saas-13/odoo/sql_db.py", line 141, in wrapper
    return f(self, _args, *_kwargs)
  File "/git/odoo-saas-13/odoo/sql_db.py", line 363, in commit
    result = self._cnx.commit()
InterfaceError: connection already closed

Expected behavior:
No error

Video/Screenshot link (optional):

**Comment by MMstp** [comment] 2017-04-10 09:00
For me, this error occured when trying to duplicate the currently in-use database.
I was able to duplicate my database when I changed my 'my-instance.cfg'
db_name = False
dbfilter = (?!^_).*
and restarted the server (no current database was selected).
I tried this on my development server - so I'm not sure if this also works on a life server when other users are logged in simultaneously.

Another possibility to create a duplicate of your current database would be to create a backup & then restore it with a differnt name.

**Comment by jado95** [comment] 2017-05-09 13:47
Hello, i have the same error of @joyinfo . There isn't other solution??

**Comment by MMstp** [comment] 2017-05-11 05:30
Did you try one of the two suggested solutions? did none of them help?

**Comment by retailscm** [comment] 2017-09-30 04:11
I have the same error. But the duplicate job still finished.

**Comment by ilmir-k** [comment] 2018-03-06 13:48
I had the same error only when used incorrect master password for duplication or removing DB. Otherwise I haven't such problem

**Comment by pedrobaeza** [comment] 2018-04-29 00:37
Hi, this seems something related to your deployment, so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/11.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

**Closed by pedrobaeza** 2018-04-29 00:37 UTC
Labels: Framework
