### ISSUE TITLE
[11.0] 404: Page not found! when trying to pay with Stripe

### ISSUE THREAD

**Issue by yostashiro** [odoo/odoo#20054] opened 2017-10-11 11:18 UTC
### Impacted versions:

11.0

### Steps to reproduce:

- Install eCommerce app.
- Install Stripe and publish it on website.
- Try to purchase something on website with Stripe.

### Current behavior:

You get redirected to an "undefined" page when you press "Pay Now" button.

### Expected behavior:

You stay on the same page and Stripe payment modal should pop up.

### Video/Screenshot link (optional):

![2017-10-11_19-08-11](https://user-images.githubusercontent.com/7766939/31437731-db6fc224-aeb8-11e7-81c3-0222c5b5bd52.gif)

**Comment by Yenthe666** [comment] 2017-10-11 11:22
@tbe-odoo and @dbo-odoo could you guys look at this? (perhaps @csnauwaert)

**Comment by dbo-odoo** [comment] 2017-10-11 13:32
Confirmed. Caused by an aggressive review process which improved the code globally but lost the stripe use case. I've reported the bug internally, opw-776200.

@yostashiro PM me on twitter with your email address and i'll add you as follower of the issue if you wish.

**Comment by jleaders** [comment] 2017-10-14 22:42
Related: I haven't been able to get Authorize.NET accepting payments in Odoo 10 or 11 since March via the test sandbox environment. I figure it's worth mentioning.

**Comment by dbo-odoo** [comment] 2017-10-16 07:02
@jleaders 
Besides having something to do with payments, this is unrelated :)

This issue is odoo 11/stripe specific (due to the way stripe does not redirect but opens a popup). Please report your problem as another issue, or better yet on odoo.com/help, thx :)

**Comment by Yenthe666** [comment] 2018-03-20 09:03
@yostashiro,

This should have been fixed in https://github.com/odoo/odoo/commit/7c639be4aadce20bf6662ab347470fadf9afd99f I believe.

**Closed by Yenthe666** 2018-03-20 09:03 UTC
Labels: 11.0, Confirmed
