### ISSUE TITLE
[12] No records when using Time range filter

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#28118] opened 2018-10-24 17:00 UTC
Impacted versions: 12

Steps to reproduce: Filter Invoices based on Time Range
![screenshot 50](https://user-images.githubusercontent.com/16624719/47446802-a15e7f80-d7d9-11e8-9150-679ad8a30497.png)

Current behavior:
Tested With Created/Last Day
No Records when Range is last 7/30/365 Days
![screenshot 54](https://user-images.githubusercontent.com/16624719/47447949-60b43580-d7dc-11e8-9de6-2be837a09840.png)

![screenshot 52](https://user-images.githubusercontent.com/16624719/47447194-9bb56980-d7da-11e8-95cb-53a79407bb83.png)
![screenshot 53](https://user-images.githubusercontent.com/16624719/47447262-b687de00-d7da-11e8-915d-0d45dee3ab43.png)

Expected behavior:
Records should be there based on Selected Date field
Video/Screenshot link (optional):

**Comment by william-andre** [comment] 2018-12-12 08:04
I tried to see what was wrong. And I could reproduce the problem, but not only in Accounting; on every pivot view I tried.
At some point, my browser crashed because it took more than 10Gb of RAM and i had to close it. Then poof ! Magic ! It worked fine.

I think this is more for the Framework team than the Accounting...

**Comment by sswapnesh** [comment] 2018-12-12 14:10
Hahaha, No User want to crash browser to make this working.  (Just kidding)

**Comment by sswapnesh** [comment] 2019-04-15 18:08
Hello @william-andre 
I am not sure but it seems like Last X days is not considering Today's day in domain.
Could you please confirm if this is desired behaviour ?

**Comment by Yenthe666** [comment] 2019-04-16 06:34
@sswapnesh I can confirm this one. I've actually made a bug report abotu this in the past but Odoo feels that the "last 365" days means the "LAST" and not the last 365 including today. They did not want to change this behaviour. I still find it odd.

**Comment by sswapnesh** [comment] 2019-05-09 17:16
` "last 365" days means the "LAST" and not the last 365 days including today. `

and at other Place it includes today's records as well.
![Screenshot from 2019-05-09 22-45-59](https://user-images.githubusercontent.com/16624719/57472934-4f300800-72ac-11e9-9a88-ad6a44c0f773.png)

Here It counts today's order as well.

PS: Similar situation in https://github.com/odoo/odoo/pull/29803 as well where AM/PM works differently at both place

**Comment by remi-filament** [comment] 2019-09-05 06:38
I also acknowledge this issue, the problem is in web JS core/domain.js where the filters use the following :
```js
rightBoundaryParams = t ? {days: -1}
```

From my point of view, last week should indeed the week before, but last x days should include today...

**Comment by C3POdoo** [comment] 2023-03-30 13:47
Dear @sswapnesh,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._

**Closed by C3POdoo** 2023-03-30 13:47 UTC
Labels: Framework, 12.0
