### ISSUE TITLE
.Deb nightly build not building every day

### ISSUE THREAD

**Issue by totalard** [odoo/odoo#20043] opened 2017-10-11 03:52 UTC
Impacted versions:11

Steps to reproduce:
Check https://nightly.odoo.com/11.0/nightly/

Current behavior:
.Deb is not building... All others are ok

Expected behavior:
.Deb should build every day

Video/Screenshot link (optional):
https://nightly.odoo.com/11.0/nightly/

**Comment by Yenthe666** [comment] 2017-10-11 06:13
Hi @totalard,

Thank you for your report. This is a duplicate of https://github.com/odoo/odoo/issues/19960 and somebody from Odoo is already looking at it.

Regards,
Yenthe

**Closed by Yenthe666** 2017-10-11 06:13 UTC
Labels: 11.0, duplicate
