### ISSUE TITLE
[8.0][9.0]Wrong value displayed for the company's name

### ISSUE THREAD

**Issue by Fenkiou** [odoo/odoo#13198] opened 2016-08-18 10:19 UTC
Impacted versions:
8 and 9

Steps to reproduce:
Install Odoo with website_sale and website_portal.

Current behavior:
In the field `Company Name`, the company's street is displayed.

Expected behavior:
It should be the name of the company.

These are the lines impacted:
https://github.com/odoo/odoo/blob/7682760dcad232829fbb5d4221f66a1ebb9d6c91/addons/website_portal/views/templates.xml#L90

https://github.com/odoo/odoo/blob/ff1845bf86f40c847b68ca84b94cab24e22d2457/addons/website_sale/views/templates.xml#L980

For odoo v8, the issue is related to the OCA modules.

**Comment by JKE-be** [comment] 2016-08-18 23:22
Because it is a duplicate of #2541

In v10, we add a specific new field.

**Closed by JKE-be** 2016-08-18 23:22 UTC
