### ISSUE TITLE
Validation Error On Contract Module

### ISSUE THREAD

**Issue by hcortez-bit** [odoo/odoo#64968] opened 2021-01-22 23:05 UTC
Impacted versions: 13.0

Steps to reproduce: Create a customer contract, fill in the necessary fields, add products and recurring invoice

Current behavior: It doesn't create the invoices and show an validation error 
__Validation Error__ : __Missing required account on accountable invoice line.__

Expected behavior: create the recurring invoices

Video/Screenshot link (optional): 

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment] 2021-01-22 23:11
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2021-01-22 23:11 UTC
