### ISSUE TITLE
Customers and Users Listed as Vendors

### ISSUE THREAD

**Issue by haconsult** [odoo/odoo#38165] opened 2019-10-08 08:57 UTC
Impacted versions: 13

Steps to reproduce:

- create a new vendor, customer and user

Current behavior:

- go to "Invoicing → Customers → Customers"
    → customers are listed as expected
- go to "Invoicing → Vendors → Vendors"
    → vendors, customers and users are listed 

Expected behavior:

- List Vendors only in vendors view

**Comment by pedrobaeza** [comment] 2019-10-08 09:01
There's no more customer or vendors, only partners, with a ranking for being selected first on sales order or purchase orders, depending on their activity in previous times. Obviously, if no purchase nor orders, everyone will be applicable since the beginning. And the same if there are activity, but you search directly for them.

The logic behind this change is when separating that way, duplicated entries for the same customer that acts as vendor (or vice versa) happened.

Closing this as expected behavior.

**Closed by pedrobaeza** 2019-10-08 09:01 UTC

**Comment by haconsult** [comment] 2019-10-08 09:27
Ok, but then I do not understand why "Invoicing → Customers → Customers" and "Invoicing → Vendors → Vendors" give different results (no previous sales or purchases apply).

**Comment by pedrobaeza** [comment] 2019-10-08 09:34
Well, not sure right now. Can you please try on runbot to see?

**Comment by haconsult** [comment] 2019-10-08 09:38
... never did that before, sorry!

**Comment by pedrobaeza** [comment] 2019-10-08 09:39
http://runbot.odoo.com/ with admin/admin

**Comment by haconsult** [comment] 2019-10-08 10:09
I am not sure if this is how you are supposed to to this, however i proceeded as follows:
- selected v13, database ....-base on runbot
- installed "Invoicing"
- "Invoicing → Customers → Customers", created new partner "Test Customer"
- "Invoicing → Vendors → Vendors", created new partner "Test Vendor"

- "Invoicing → Customers → Customers" lists only "Test Customer"
- "Invoicing → Vendors → Vendors" lists both, "Test Customer" and "Test Vendor"

hope this helps

**Comment by pedrobaeza** [comment] 2019-10-08 10:14
Yes, but as said, this is the expected behavior...

**Comment by haconsult** [comment] 2019-10-08 10:36
Ok, I find it a bit confusing, but if it is a design decision, so be it. Thanks anyway!
