### ISSUE TITLE
[9.0] Bogus fields invalid message

### ISSUE THREAD

**Issue by bringsvor** [odoo/odoo#9816] opened 2015-11-30 14:26 UTC
Hi

When I try to edit a sales order to add a new line, then click Save I get this error message:

![image](https://cloud.githubusercontent.com/assets/7498104/11474123/6282a148-9776-11e5-9ea6-8fd4c6bc1e10.png)

But it doesn't say which fields are invalid so I am not able to fix them. And even if it did, it seems sometimes the line will be set as read only even when the sales order appears to be in edit mode. This is not very promising for my (potential) customer, they would like to keep a SO open for a while then add to it as they go.

-Torvald

**Comment by Yenthe666** [comment] 2016-05-23 13:19
Hi @bringsvor,

I can no longer reproduce this issue on the latest Odoo 9.0.
If this issue still persist please add a workflow in order for me to test / find the bug.
Closing this, since there is no way to reproduce this at the moment.

Regards,
Yenthe

**Closed by Yenthe666** 2016-05-23 13:19 UTC
