### ISSUE TITLE
@api.onchange cannot modify one2many lines

### ISSUE THREAD

**Issue by agenterp** [odoo/odoo#2693] opened 2014-09-25 06:52 UTC
for example in sale.order model :

```
@api.onchange('location_ids')
def _onchange_sale_order_lines(self):
    print "welcome"
    for self_id in self.order_line:
        print self_id.name #this works
        self_id.name = "updated names" #this is not updating in weblcient
    self.partner_id = 1 # this is updating in weblient
```

**Comment by cysnake4713** [comment] 2015-01-10 17:59
Can't change many2mnay fields in onchange is really big issue! I wonder when this one will be fixed or if I want to fix it, where should I look at?

**Comment by LeartS** [comment] 2015-05-15 09:51
I agree; this is kind of a big issue. No plans for allowing this?

**Comment by chesucr** [comment] 2015-05-27 15:34
+1 to solve this issue soon

**Comment by rruebner** [comment] 2015-08-03 12:40
@rco-odoo If possible can you explain why this limitation was introduced in odoo v8 in openerp/models.py lines 5898 - 5902. What does it mean "... The web client does not behave well ..."?

If I remove these lines my many2many fields are updated well and I know that this worked in OpenERP v7.

**Comment by jholze** [comment] 2015-08-10 09:31
:+1:

**Comment by agb80** [comment] 2015-08-12 02:02
:+1:

**Comment by michaelkarrer81** [comment] 2015-08-12 09:45
+1

**Comment by rruebner** [comment] 2015-08-28 06:46
@rco-odoo Hi, it would be really nice if you can answer my question above. Thanks and regards Robert.

**Comment by novikod** [comment] 2015-08-28 13:42
Any info about this?

**Comment by cooshy** [comment] 2015-09-01 08:26
Have they fixed this yet?

**Comment by jholze** [comment] 2015-09-09 08:04
Lost in space :)

**Comment by christophlsa** [comment] 2015-09-14 14:57
Is there an answer for the question of comment of @rruebner (@rco-odoo)? Or does someone knows a workarround to update xtomany fields in onchange methods?

**Comment by cooshy** [comment] 2015-09-15 03:19
@christophlsa I posted a question to stackoverflow a while ago and someone posted a dirty patch for this, please check this out: http://stackoverflow.com/questions/32326212/one2many-field-on-change-function-cant-change-its-own-value

**Comment by Benniphx** [comment] 2015-09-23 11:18
I created a pull request with the changes @rruebner mentioned.

**Comment by NL66278** [comment] 2016-03-05 21:40
Even the dirty fix does not work for me. I do not get One2many field updated at all, even though it is NOT the field triggering the onchange.

**Comment by NL66278** [comment] 2016-03-07 14:49
Haha write() does not work while in onchange, because it will try to update the db, we have to update the dummy self passed to onchange method to update() method.

So in method called from both write/create methods (after actual write or create) and from onchange methods I have:
        if self.ids:                                                           
            # Write works when record backed by real db row:                   
            super(Design, self).write(vals)                                    
        else:                                                                  
            # Update is needed when called from onchange:                      
            self.update(vals)
(Design is the name of my class)

In onchange self has a dummy id (NewId object), but ids is empty: []

**Comment by nafex** [comment] 2016-06-09 09:00
Still not possible? Even on v9 and master? Any new on this? Anyone knows a workaround?

**Comment by Yenthe666** [comment] 2016-06-09 09:14
Alright since this has been confirmed quite a while ago I'll ping around some people again.
@rco-odoo, @mart-e and @odony could you guys give some input on this please? It has been confirmed and open for 9 months. Will this be added for V10 or what is the plan?
Thanks guys!

**Comment by mart-e** [comment] 2016-06-09 09:55
It's currently not supported by the web client. To give you an idea, we gave it a try at #10557 (should not be merged in 9.0 by the way, too risky).
So it's not trivial and there is no easy workaround now, sorry

**Comment by nafex** [comment] 2016-06-09 11:58
Are there any chance that this will be resolved in v10?

**Comment by mart-e** [comment] 2016-06-09 11:59
There is chances yes but it is not a priority

**Comment by ernesto-medina** [comment] 2016-11-02 06:57
hello @agenterp, I was in the same situation, when you use @api.onchange on a model that is in api V7, odoo make a downgrade and in some point of code, clear a values that you send for many2many fields, i think that is same case with one2many fields.

how resolve this?
- I change the code of my "onchange" to api V7, and work fine in many2many fields

I hope the information is usefull.

Regards

**Comment by Yajo** [comment] 2016-11-03 10:27
Recently I made a workaround: the onchange changes a boolean field that displays a button; the user clicks the button and the one2many changes; if he doesn't, it gets auto-triggered on `write()`.

**Comment by nafex** [comment] 2016-11-03 18:19
@rco-odoo, @mart-e any news on this? Is this resolved in odoo v10?

**Comment by thomas15v** [comment] 2017-06-20 08:13
Can confirm that this is not resolved in V10, been struggling with this for while.

**Comment by Yenthe666** [comment] 2017-06-27 12:56
Any update guys? (@odony and @xmo-odoo )

**Comment by mart-e** [comment] 2017-06-28 08:09
As said before, will work on it when we can but it is not something we plan to do in a short term and most likely not in stable version.
I can not give you a release target (no need to ask if it will be in v11)

**Comment by JosDeGraeve** [comment] 2017-06-28 08:19
I see that this will not get fixed while you're prepping for v11, but in the meantime, is it an option to clearly document the limits of the current situation ?  I think as odoo developers we all have been struggling with this for hours while dealing with the subtleties that surround this issue.  Having some documentation, that clearly states what works and what not, will help us all.

**Comment by yelizariev** [comment] 2017-06-28 08:26
Anyone can suggest updates in  odoo documentation via PR. You don't need to wait when odoo representative will do it themselves (I don't believe that they will update documentation regarding to this issue)

**Comment by pedrobaeza** [comment] 2018-05-22 07:46
@rco-odoo are there any plan for supporting this on v12 ORM?

**Comment by yelizariev** [comment] 2018-05-22 16:13
Reference to v8 may be removed from the issue title

**Comment by pedrobaeza** [comment] 2018-05-22 16:18
Changed

**Comment by blaggacao** [comment] 2018-06-28 20:20
Not exactly the same, but maybe somebody can enlighten me:
In V10 ...

```python
class IrModel(models.Model):
    _inherit = ['ir.model']
    mapped_model_id = fields.Many2one('ir.model', string="Mapped Model")
    @api.onchange('mapped_model_id')
    def _onchange_mapped_model(self):
        # self.field_id, despite the name is a one2many
        for fld in self.field_id.filtered(lambda f: f.state == 'manual'):
            fld.update({
                'mapped_field_id': False,
                'mapped_value_ids': False
                })
```

This onchange returns to the web client:

```

field_id : Array(46)
0: [5]
1: (3) [1, 4740, {…}]
2 : (3) [1, 4739, {…}]
3 : (3) [1, 4738, {…}]
...
45 : (3) [1, 4805, {…}]
```
Which is a 

1. combination of the commands `5` and 
2. subsequently many `1`,
3. which in turn also include `base` fields,
4. which then, naturally, on save hits this `UserError` line: https://github.com/odoo/odoo/blob/2774e3b4a82f3c0ea94faff8facb7c4ee5ce7b48/odoo/addons/base/ir/ir_model.py#L587

**Q: Is there a way so that have the onchange to truely respect the `filtered()` (and only update [ `1` command] the updated values)?**

**Comment by nhomar** [comment] 2018-08-15 08:45
@all

Closing this because of the official non-support of this feature from here:

https://github.com/odoo/odoo/pull/22531

May be in a future this behavior will not happen.

**Closed by nhomar** 2018-08-15 08:45 UTC
Labels: Confirmed, Wishlist

**Comment by sanjaycoder123** [comment] 2018-12-22 09:19
@api.onchange('sale_order_id')
    def get_product_details(self):
        
        list = []
        value = {}
        if self.sale_order_id.material_line:
            for line in self.sale_order_id.material_line:
                move_line = {
                    'product_id': line.product_id.id,
                    'product_uom_qty': float(line.qty),
                    'picking_type_id':self.picking_type_id.id,
                    'state':'draft',
                    'name':self.sale_order_id.name,
                    'location_id': self.picking_type_id.default_location_src_id.id,
                    'location_dest_id': self.picking_type_id.default_location_dest_id.id,
                    'date_expected':datetime.datetime.now(),
                    'product_uom':line.uom_id.id
                }
                list.append([0, 0, move_line])
        print list
        self.update({'move_lines': list })

this code is working for, i was having senior , that in sale order i am having another one line items for raw materials, that product line i need to fetch in inventory , through saleorder_id .

**Comment by obayit** [comment] 2019-02-07 08:04
They fixed this.
I don't know at what commit/PR exactly. But now onchange can by used with x2many fields.

**Comment by TadeuszKarpinski** [comment] 2020-10-02 15:58
Hey this works for version 10

`    new_operation = self.pack_operation_product_ids.new({
        'product_id': barcode_parent_product.id,
        'product_qty': 0,
        'fresh_record': True,
        'package_id': False,
        'location_dest_id': self.location_dest_id.id,
        'ordered_qty': 0,
        'qty_done': 1,
        'owner_id': False,
        'location_id': self.location_id.id,
    })
    pack_operation_product_ids = [operation.id for operation in self.pack_operation_product_ids]
    pack_operation_product_ids.append(new_operation.id)
    return {'value': {'pack_operation_product_ids': pack_operation_product_ids}}`
