### ISSUE TITLE
[8.0 Final]  CRM - Error when clic on Sales Teams opportiunty Graph

### ISSUE THREAD

**Issue by haylahi** [odoo/odoo#2637] opened 2014-09-23 11:14 UTC
Traceback (most recent call last):
  File "/home/haylahi/workspace/odoo8_final/odoo/openerp/http.py", line 499, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/haylahi/workspace/odoo8_final/odoo/openerp/http.py", line 516, in dispatch
    result = self._call_function(*_self.params)
  File "/home/haylahi/workspace/odoo8_final/odoo/openerp/http.py", line 282, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/haylahi/workspace/odoo8_final/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/haylahi/workspace/odoo8_final/odoo/openerp/http.py", line 279, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/haylahi/workspace/odoo8_final/odoo/openerp/http.py", line 732, in __call__
    return self.method(_args, *_kw)
  File "/home/haylahi/workspace/odoo8_final/odoo/openerp/http.py", line 375, in response_wrap
    response = f(_args, *_kw)
  File "/home/haylahi/workspace/odoo8_final/odoo/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/haylahi/workspace/odoo8_final/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/home/haylahi/workspace/odoo8_final/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/haylahi/workspace/odoo8_final/odoo/openerp/models.py", line 1579, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(cr, uid, self._name, etree.fromstring(result['arch']), view_id, context=ctx)
  File "/home/haylahi/workspace/odoo8_final/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/haylahi/workspace/odoo8_final/odoo/openerp/addons/base/ir/ir_ui_view.py", line 836, in postprocess_and_fields
    self.raise_view_error(cr, user, message, view_id, context)
  File "/home/haylahi/workspace/odoo8_final/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/haylahi/workspace/odoo8_final/odoo/openerp/addons/base/ir/ir_ui_view.py", line 367, in raise_view_error
    raise AttributeError(message)
AttributeError: Field `total_revenue` does not exist

Error context:
View `crm.opportunity.report.graph`
[view_id: 328, xml_id: crm.view_report_crm_opportunity_graph, model: crm.opportunity.report, parent_id: n/a]

**Comment by Yenthe666** [comment] 2017-06-27 11:56
Hi @haylahi,

Thank you for your report.
The problem is fixed in the meanwhile and I believe it was done with https://github.com/odoo/odoo/pull/2306/commits/29a8e352bfaed11c102704cd41c7e316e8bd7de6

Regards,
Yenthe

**Closed by Yenthe666** 2017-06-27 11:56 UTC
Labels: duplicate
