### ISSUE TITLE
[12] Wrong Date not show message to user

### ISSUE THREAD

**Issue by celm1990** [odoo/odoo#32995] opened 2019-04-27 19:56 UTC
**Impacted versions:**
12, tested runbot
**Steps to reproduce:**
Go to any field Date, enter wrong date and get error

**Current behavior:**

**Expected behavior:**
Show message to user according [this code ](https://github.com/odoo/odoo/blob/12.0/addons/web/static/src/js/fields/field_utils.js#L431)

PD:
[Here](https://github.com/odoo/odoo/blob/12.0/addons/web/static/src/js/widgets/date_picker.js#L126-L135) catch error and return false

Video/Screenshot link (optional):

![Untitled Project](https://user-images.githubusercontent.com/7775116/56854444-39a9fe00-68fc-11e9-82ff-863d95ef6691.gif)

**Comment by pedrobaeza** [comment] 2019-04-27 20:18
@ged-odoo can you please check this?

**Comment by Yenthe666** [comment] 2019-04-27 21:14
@sswapnesh didn't you report this recently?

**Comment by sswapnesh** [comment] 2019-04-27 21:29
Yes,Duplicate of https://github.com/odoo/odoo/issues/29551

**Comment by pedrobaeza** [comment] 2019-04-27 21:31
This one gives some insight about where to see, so maybe a patch can be extracted

**Comment by pedrobaeza** [comment] 2019-04-27 21:32
Any way, closing as duplicate and the link is preserved thanks to GitHub.

**Closed by pedrobaeza** 2019-04-27 21:32 UTC
Labels: 12.0, Framework

**Comment by sswapnesh** [comment] 2019-04-27 21:35
I just added this part (links with reference) on Related odoo ticket.

**Comment by celm1990** [comment] 2019-04-27 21:44
Sorry for create new issue duplicate.

But issue reported by @sswapnesh  has more 4 months and nothing solution?

**Comment by sswapnesh** [comment] 2019-04-28 02:03
I hope We will get some solution soon As I have added Enterprise Ticket for this.
