### ISSUE TITLE
[11.0] Web Client: OnChange Handling Issues

### ISSUE THREAD

**Issue by wtaferner** [odoo/odoo#20169] opened 2017-10-15 05:39 UTC
**Impacted versions:**
11.0

**Steps to reproduce:**

Initial: ValidationError not respected for resetting the hidden frontend values in x2many form view
Other related issues beneath the initial screenshots

- Create a stored computed field which is triggered for computation of a form view embedded One2many field and raise a Validation Error in case a certain condition is met.
- Go into edit mode and change a value which is triggering the computation (430 instead of 420 in our sample after doing a successful change from 450 to 430) and therefore the Validation Error. All working as excepted...the visible value is reset back to 430.
- Try to immediately save after and find yourself having sent the same value as you tried before even if the field shows another value for this field.

So, the request sends the old/wrong value back although it was denied by the server before.

**Current behavior:**
Validation Error does not reset the values completely as expected

**Expected behavior:**
Validation Error should reset all the values tested before in an onchange or at least should match the visible field values.

@ged-odoo 
I guess this one is a use case which needs to be fixed in the JS client handling.

**Video/Screenshot link (optional):**

User did change the value to 420 and an onchange was triggered resulting in this.

![1 onchange validationerror in the backend](https://user-images.githubusercontent.com/362478/31582073-399904dc-b17a-11e7-8b02-2df140183a61.JPG)

User tries to click save immediately after the error was shown and moving back to the form view.

![2 save after validationerror in the backend](https://user-images.githubusercontent.com/362478/31582075-3f3c7a22-b17a-11e7-8338-5fdbba246825.JPG)

Onchange related other use case (sorry to mix it here, but I guess it is the same construction yard)
Here the user changed the saftey stock to 23 and in the onchange it was changed and corrected to 15 (automatic helper to return the max value)

![4 no updated value in case it was corrected during onchange](https://user-images.githubusercontent.com/362478/31582412-ed92a77a-b181-11e7-963f-5c08ac7ca347.JPG)

**Additional Minor Issue (as you are touching this anyway)**
The sum fields are not updated during onchange...not sure if this is possible, but as we have the brand new webclient I have a good feeling about the stars to reach ;-)

![3 additional minor issue](https://user-images.githubusercontent.com/362478/31582175-26d15220-b17d-11e7-9811-f0b28fe23f51.JPG)

https://www.odoo.com/web?debug#id=776653&view_type=form&model=project.issue&action=963&active_id=49&menu_id=4720

**Comment by wtaferner** [comment] 2017-10-15 06:31
@nim-odoo 
OPW-776653

**Comment by wtaferner** [comment] 2017-10-19 14:27
@ged-odoo
Are you or your team already on it? Is everything clear? It is kind of cumbersome developing or testing in the frontend the UI in onchange. Would be nice to get some feedback.

**Comment by ged-odoo** [comment] 2017-10-19 14:46
@wtaferner yep, there is a ticket, and I am working on it.  However, I had to fix other onchanges/x2m issues first... (we could not do any expenses)

But this one will not be forgotten...

**Comment by wtaferner** [comment] 2017-10-19 14:52
@ged-odoo 
Thanks for the short notice...I saw that you are assigned...if you are already working on it I feel confident that you will fix them soon...having a possible launch (need to decide next week if we postpone or keep the planned date) of a quite big project (of course 11.0) in two weeks was keen but shows the trust I have in you guys ;-)

**Comment by ged-odoo** [comment] 2017-10-20 14:20
@wtaferner Well, I hope that your project will be a success, delayed or not.  We'll do our best from our side :)

I have a fix for initial issue (https://github.com/odoo-dev/odoo/commit/e6b73cc252eb7709bcd1a5118da5c83f83ba878a).  In that fix, we keep the value given by the user.  We just make sure that the displayed value is the same as the internal value from the basic model.

Now, I'll work on the next one...

**Comment by ged-odoo** [comment] 2017-10-23 08:50
@wtaferner 

- I am not sure I can reproduce your second issue: there is an onchange on a field, and it is not applied. I do not know how it could happen.  Is it because the field that changed was still in focus? (in that case, why did the onchange triggered?).  If this is the case, does this commit solve your issue: https://github.com/odoo-dev/odoo/commit/2f1688ab50e470560422f77b9ebb0ad7bf4e190e ?

- Could you elaborate on your 3rd issue? As far as I can tell, sum fields can be updated.  For example, in a sale order, when you create a new order line.

**Comment by wtaferner** [comment] 2017-10-23 11:30
Well, I am changing the value to 23 which does trigger an onchange...the server does evaluate the number and decides that it is too much and sends back only 15...so the frontend should respect the number getting back from the server...I will test your commit later today.

About the other stuff you have fixed it now does show the "real" old value but IMHO a validation error should set back the original value otherwise the save must always be secured by the ORM and for god sake it is almost never secured in Odoo core...why should we if we can stop the user during onchange having a certain value set.

**Comment by wtaferner** [comment] 2017-10-24 07:19
@ged-odoo 
Ok, the provided patch is resolving the issue from screenshot number 3. I guess you can merge it.

About the 3rd issue it is true that the sum is updating as soon as you create a new x2m line but is not updating if you modify existing lines.

May I ask you to reelaborate issue number 1 and do the resetting of values in case of a validation or user error? The only time when the values should stay as the user has put them is if you return a warning.

**Comment by ged-odoo** [comment] 2017-10-24 14:16
@wtaferner 
- Ok, issue #2 is fixed (saas-16, commit https://github.com/odoo/odoo/commit/616eedb7e47cc557afbe8bda20cbb490665e4b50).

- issue #1 I kind of agree with the issue 1, but not with your reason (Onchanges should not be used for business logic enforcement, it should always be secured by the ORM).  Note that we try in odoo to move our onchanges to computed fields (not all of them can be converted to computed fields, but a pretty good amount).  

Also, in your case, what you could do to work around this is to reset the value in the onchange to its previous value, and returns a warning at the same time (instead of raising a validation error).  This should have the effect you are looking for.

- I am confused about issue #3, it is definitely possible and it works (as far as I can tell) for quotations/sale orders, when I add/edit/remove lines.  Could you give me a more specific scenario? (sorry to bother you, there is something that I must be missing)

**Comment by wtaferner** [comment] 2017-10-24 14:33
@ged-odoo 
Thank you.

Issue # 1 
I do agree with you that it is not to enforce business logic but is helping a lot before approaching the write method which is a pain to manage compared to the onchange mechanism which is precise and can IMHO also used to guide the user and check things before even clicking save. Anyway, the validation is the easiest way to just reject the last change done (at least this was the case in all previous versions)

Do you reject that the validation should reset the lately changed field values or are you fixing this at some point?

Issue # 3
Just tested on runbot and can confirm that it works if you have a modal in place, it does also work for adding new entries inline, but it does not work for modifying inline an existing line field.
http://273087-11-0-2e5f27.runbot9.odoo.com/web?debug#id=126&view_type=form&model=sale.order&action=823&menu_id=569

I modified the standard view for you as it was not reproduce able on runbot (all modules) in the sale order. 

![runbot_x2m_list_sum_inline](https://user-images.githubusercontent.com/362478/31949153-e4b9a8ca-b8d8-11e7-836a-2112ef914ce5.JPG)

**Comment by ged-odoo** [comment] 2017-10-25 08:03
@wtaferner ok, I understood the issue #3, you were talk about the sums in a list view, not the total which is displayed before.  took me way too long... This should be quite simple to fix.

For issue #1, i am on the fence.  Not totally sure that you are right.  But you said that this was the previous behaviour, so I guess that push me in your direction, so we do not break existing code. I'll  see what I can do.

**Comment by wtaferner** [comment] 2017-10-25 10:59
@ged-odoo 
Great, I thought it won't be too difficult but as always communication is always first and needed :-)

About issue #1: well, I do not directly want to push you, but there is of course a reason behind why I think it is the right way. One argument is to not break existing code, but another one is also that you can use these triggers to really do changes in the backend by breaking out the onchange mechanism (for whatever reason you want to do that) and on Python side the rollback mechanism is a good thing and I think the client should be consistent with what is happening on Python side, so I guess this is the main reason why a rollback for an onchange does make sense. Even if the onchange mechanism normally do not need the rollback (no write or create if you do not break out of the onchange mode) it is an easy way to just reject a change without handling and controlling everything (developer convenience and serving the user in the end).

I know that it is probably more difficult for you and the web client and maybe also not what you normally maybe expect a client to do, but in this symbiosis I think it should be respected and I hope you can see the need from this perspective a little bit better.

Anyway, you already committed that you will give it a try...thank you for your help and efforts. I love the new web client and that everything is now tested, therefore easier to reproduce and less in danger to be broken.

**Comment by ged-odoo** [comment] 2017-10-25 13:03
@wtaferner issue #3 is now fixed (commit https://github.com/odoo/odoo/commit/c739bcf0d1a740b6757d51276a9dc08a66158c80 in saas-16)

Ok for #1, i'll see how easy/hard the change is :)

**Comment by Yenthe666** [comment] 2017-10-25 14:34
@ged-odoo you're doing a great job! Keep up the good work. 👏

**Comment by ged-odoo** [comment] 2017-10-27 09:53
Last issue (#1) is now fixed: https://github.com/odoo/odoo/commit/c163351e8a6776e046f04e6c264bf4372499dbba

It was not so hard after all... I think that I can now close this issue. Thanks @wtaferner for clear and useful bug reports.

**Closed by ged-odoo** 2017-10-27 09:53 UTC
Labels: 11.0, Framework, OE
