### ISSUE TITLE
Time Buffer for Appointment

### ISSUE THREAD

**Issue by BobboBuckley** [odoo/odoo#158337] opened 2024-03-20 11:09 UTC
Impacted versions: 17

Steps to reproduce: In Appointment Configuration/Settings, there is no way to set a time buffer between appointments

Current behavior: Clients can book back-to-back Appointments, with no time for preparation, bathroom break, transportation, etc.

Expected behavior: All the Appointment apps I have used in the past have a Buffer feature to allow time between Appointments that can't be booked.
 

Video/Screenshot link (optional): <img width="604" alt="Odoo_Feature_Appointment_Buffer" src="https://github.com/odoo/odoo/assets/22560911/d9ed070b-84e4-4b80-8b2a-1c53fa715201">

Support ticket number submitted via odoo.com/help (optional):

**Comment by vava-odoo** [comment] 2024-04-17 09:06
Hi @BobboBuckley 
Thanks for the feedback. I sent it to the R&D team, it will be considered for future developments but won't be merged in stable versions. 
As this is not a bug, I'm closing the issue.
Cheers

**Closed by vava-odoo** 2024-04-17 09:06 UTC
Labels: Wishlist, Marketing
