### ISSUE TITLE
[10.0] Dynamically disabling a field shows the previous value when saving in the enabled state

### ISSUE THREAD

**Issue by osluys** [odoo/odoo#19167] opened 2017-08-30 14:02 UTC
There is a client-side bug that arises when the enabled/disabled state (i.e. the *readonly* attribute) of an input field is dynamically determined. When the form is saved at the time that the field is in the enabled state (the value and state needs to change a few times first), the field will show the previous value instead of the current value. However, this does not happen if the field is in the disabled state when saving, and instead will correctly display the current value.

To illustrate, I have defined the following parent/child models, where an *onchange* method sets the text value whenever the checkbox is clicked:

```python
class ScratchOne(models.Model):
    _name = 'scratch.one'
    many = fields.One2many('scratch.many', inverse_name='one')
    value = fields.Char("Value is disabled", readonly=True)
    check = fields.Boolean("Check to disable Value", default=True)

    @api.onchange('check')
    def _onchange_check(self):
        self.value = "yes" if self.check else "no"


class ScratchMany(models.Model):
    _name = 'scratch.many'
    one = fields.Many2one('scratch.one')
    value = fields.Char("Value is disabled", readonly=True)
    check = fields.Boolean("Check to disable Value", default=True)

    @api.onchange('check')
    def _onchange_check(self):
        self.value = "yes" if self.check else "no"
```

and the corresponding view, declaring a dynamic *readonly* attribute on the text fields:

```xml
    <record id="scratch_view_form" model="ir.ui.view">
        <field name="name">scratch_view_form</field>
        <field name="model">scratch.one</field>
        <field name="arch" type="xml">
            <form>
                <group col="4">
                    <field name="check"/>
                    <field name="value" attrs="{'readonly':[('check','=',True)]}"/>
                </group>
                <group string="Many">
                    <field name="many">
                        <tree editable="bottom">
                            <field name="check"/>
                            <field name="value" attrs="{'readonly':[('check','=',True)]}"/>
                        </tree>
                    </field>
                </group>
            </form>
        </field>
    </record>
```

In the below screencast, you can see that as the checkbox in the tree list is clicked, the textbox is either enabled or disabled and the text is updated to reflect the correct state of the field. However, as soon as the focus is removed from the line item with the textbox in the enabled state, then the field no longer shows the correct state (which should be *yes*) and is instead showing the previous value *no*. Likewise, the same behavior is exhibited when checkbox on the main form is clicked repeatedly and then the textbox left in the enabled state and the form saved. (The end of the screencast doesn't clearly show me clicking the *Save* button on the form, so it may not be obvious that that's what happened.)

![screencast](https://user-images.githubusercontent.com/17426923/29876438-0ec8259a-8d9d-11e7-9589-451fc6698ddf.gif)

This is a sample module to illustrate the bug.

[Source.zip](https://github.com/odoo/odoo/files/1263840/Source.zip)

## UPDATE:

After more testing, my statements about the textbox needing to be in the enabled state when saving may not be true in all circumstances. What is important is that the checkbox be clicked several times and the form saved for both enabled/disabled states of the textbox. Then you'll see the inconsistency show up in the textbox value.

**Comment by pedrobaeza** [comment] 2018-06-06 10:52
This is not a bug, but the desired behavior, as any readonly value is not passed back to the server. You can workaround this using a compute + inverse field, but it's a bit convoluted, as you need an extra field for storing the custom value.

Fortunately, in later version, there's a mechanism for saving this readonly fields, which is to add force_save="1" in your XML field definition.

Closing this then.

**Closed by pedrobaeza** 2018-06-06 10:52 UTC
Labels: 10.0, Framework
