### ISSUE TITLE
[8.0] Journal Entry Number Duplication On entry through Cash Register

### ISSUE THREAD

**Issue by lithint** [odoo/odoo#10496] opened 2016-01-16 19:35 UTC
Steps to reproduce: 
1. Open CashRegister
2. Add a cash transaction line.
3.Reconcile it.(1st journal entry will generate) and back to any menu.
4.Back to cash register again, put another entry line and reconcile. 
5. Check the second journal entry generated. Both the Journal entry is having same number.
![01cash registers - odoo 2016-01-16 23-12-22](https://cloud.githubusercontent.com/assets/7326014/12374011/dc2ee244-bca7-11e5-8fef-af7a269588d2.png)

Entry
![01journal entries - odoo 2016-01-16 23-13-04](https://cloud.githubusercontent.com/assets/7326014/12374013/f1e25076-bca7-11e5-9380-246f6adff185.png)

Any fix ?

**Comment by lithint** [comment] 2016-02-16 08:32
Hi all,
any fix for the above

**Comment by lithint** [comment] 2016-02-16 09:25
did a small workaround and is working fine

/addons/account/account_bank_statement.py
replaced the following line
 `move_name = (st_line.statement_id.name or st_line.name) + "/" + str(st_line.sequence)`  
with 

 `        new_sequnce = st_line.statement_id.number_of_lines_reconciled() + 1
`
`move_name = (st_line.statement_id.name or st_line.name) + "/" + str(new_sequnce)`

**Comment by treviser** [comment] 2017-04-18 14:53
I can confirm multiple duplicates of sequence numbers also for version 9.0.
@Yenthe666 Any comment on this?

**Comment by Yenthe666** [comment] 2017-04-18 15:48
Hmm @qdp-odoo I see no apparant business flow why this is the case. Is this a bug or does it have a reason to work like this?

**Comment by qdp-odoo** [comment] 2017-04-24 08:27
nah it's definitively a bug

**Comment by treviser** [comment] 2017-06-10 09:08
@Yenthe666 @qdp-odoo Any news on this? Might @lithint workaround be a solution?

**Comment by qdp-odoo** [comment] 2017-07-05 16:10
nope, it has been fixed in a further stable version (where the numbering of bank/cash journal entries have been totally reviewed) but nothing at my knowledge has been done for v8.

**Comment by treviser** [comment] 2017-07-14 09:04
@qdp-odoo Could please let me know for which stable version it has been fixed (9.0, 10.0...)?

**Comment by qdp-odoo** [comment] 2017-07-17 07:27
sure. it was released on https://github.com/odoo/odoo/commit/b17e4a0f6, so for version 10.

As you can see, the "fix" is a complete revamp of the journal entries numbering for bank statements so it can't simply be backported to v8. 
My opinion would be to close this bug report unless you really need the fix for v8 and have an enterprise contract and want to use it

**Comment by treviser** [comment] 2017-07-17 08:05
@qdp-odoo Thanks for your feedback. I would need a fix for 9.0 only.

**Comment by Yenthe666** [comment] 2017-11-05 19:09
Hi all,

Since the bug is fixed in V10 (at https://github.com/odoo/odoo/commit/b17e4a0f6) and Odoo 8 is no longer supported I'm closing this bug report.
P.S: @qdp-odoo is there a fix on the way for 9.0 (for @treviser?)

Regards,
Yenthe

**Closed by Yenthe666** 2017-11-05 19:09 UTC
Labels: confirmed

**Comment by qdp-odoo** [comment] 2017-11-06 09:06
Not at my end. 

@treviser , if you need a bugfix from our part, please follow the usual ticket process by contacting our support (might be a good idea to relate this github issue on the ticket).
