### ISSUE TITLE
[12.0] QWeb error when generating invoice

### ISSUE THREAD

**Issue by liogate** [odoo/odoo#34093] opened 2019-06-13 10:41 UTC
## Impacted versions:

12.0

## Steps to reproduce:
![image](https://user-images.githubusercontent.com/17850842/59426341-3dc0ab00-8dd8-11e9-809b-b9b6b1803dc2.png)

## Current behavior:

Internal server error:

```
Erreur:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 346, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_683_1739
TypeError: decoding str is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1671, in report_download
    response = self.report_routes(reportname, docids=docids, converter=converter)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1612, in report_routes
    pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_actions_report.py", line 703, in render_qweb_pdf
    return self._post_pdf(save_in_attachment, pdf_content=pdf_content, res_ids=html_ids), 'pdf'
  File "/usr/lib/python3/dist-packages/odoo/addons/account_facturx/models/ir_actions_report.py", line 19, in _post_pdf
    xml_content = invoice._export_as_facturx_xml()
  File "/usr/lib/python3/dist-packages/odoo/addons/account_facturx/models/account_invoice.py", line 45, in _export_as_facturx_xml
    content = self.env.ref('account_facturx.account_invoice_facturx_export').render(template_values)
  File "/usr/lib/python3/dist-packages/odoo/addons/web_editor/models/ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1293, in render
    return self.env[engine].render(self.id, qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 59, in render
    result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 274, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 353, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.models.qweb.QWebException: decoding str is not supported
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 346, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_683_1739
TypeError: decoding str is not supported

Error to render compiling AST
TypeError: decoding str is not supported
Template: 683
Path: /templates/t/rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeAgreement/ram:BuyerOrderReferencedDocument/ram:IssuerAssignedID
```

## Expected behavior:

Download my invoice.

## Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/17850842/59426391-5e890080-8dd8-11e9-890e-b6f9e3492c0c.png)

**Comment by pedrobaeza** [comment] 2019-06-13 11:03
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by pedrobaeza** [comment] 2019-06-13 11:03
(wrong button)

**Comment by liogate** [comment] 2019-06-13 12:15
You're welcome, I'm using an instance of odoo on a docker engine with the latest image `12:latest`.
**Latest upgrade:** 2019-06-13 12:24:23

I'm using A4 format, the french version and a one of your modern template:
![image](https://user-images.githubusercontent.com/17850842/59431075-4c14c400-8de4-11e9-9c63-74b3ab2af40d.png)

## Steps to reproduce:

![image](https://user-images.githubusercontent.com/17850842/59429680-91cf8d80-8de0-11e9-9484-529da963f070.png)

![image](https://user-images.githubusercontent.com/17850842/59429714-a14ed680-8de0-11e9-98a3-46f0760c6997.png)

And when I print, Internal Server Error.

On your instance it works... 😢 I don't understand why, maybe encoding error ?

For information: Generating pdf works for orders

**Comment by pedrobaeza** [comment] 2019-06-13 12:17
Please reproduce it on runbot. And try also to do it in English. If so, it can be due to the translations.

**Comment by liogate** [comment] 2019-06-13 12:44
I did it here: http://539111-12-0-9993f9.runbot21.odoo.com

**Comment by pedrobaeza** [comment] 2019-06-13 15:16
Tried on runbot and no problem, so it should be something specific of the deployment or the translation, so closing.

**Closed by pedrobaeza** 2019-06-13 15:16 UTC
Labels: Need information

**Comment by jumshudsultan** [comment] 2021-01-30 07:14
@liogate you should uninstall `Import Bills/Invoices From XML` module
