### ISSUE TITLE
Traceback when having multile languages active and disable the en_us then

### ISSUE THREAD

**Issue by jni-odoo** [odoo/odoo#5103] opened 2015-02-06 06:35 UTC
Produced on : 8.0 runbot

Steps to reproduce :
(1) In your database make sure you have 2-3 languages installed
     see here :https://docs.google.com/file/d/0B5j41T1Hqv1sVGhNTXdEZThzT28/edit?usp=drivesdk
(2)Now inactive one languages , for example en_us

(3) Go to menu Settings -> User 

(4) You will get a traceback here , the expected behavior is it should give some proper message 

Traceback :
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/runbot/extra/runbot/static/build/44934-8-0-859979/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/runbot/extra/runbot/static/build/44934-8-0-859979/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/runbot/extra/runbot/static/build/44934-8-0-859979/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/44934-8-0-859979/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/44934-8-0-859979/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/44934-8-0-859979/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/44934-8-0-859979/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/44934-8-0-859979/openerp/addons/web/controllers/main.py", line 875, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/home/odoo/runbot/extra/runbot/static/build/44934-8-0-859979/openerp/addons/web/controllers/main.py", line 896, in do_search_read
    request.context)
  File "/home/odoo/runbot/extra/runbot/static/build/44934-8-0-859979/openerp/http.py", line 900, in proxy
    result = meth(cr, request.uid, *args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/44934-8-0-859979/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/44934-8-0-859979/openerp/models.py", line 5093, in search_read
    result = self.read(cr, uid, record_ids, fields, context=read_ctx)
  File "/home/odoo/runbot/extra/runbot/static/build/44934-8-0-859979/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/44934-8-0-859979/openerp/addons/base/res/res_users.py", line 873, in read
    res = super(users_view, self).read(cr, uid, ids, other_fields, context=context, load=load)
  File "/home/odoo/runbot/extra/runbot/static/build/44934-8-0-859979/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/44934-8-0-859979/openerp/addons/base/res/res_users.py", line 295, in read
    result = super(res_users, self).read(cr, uid, ids, fields=fields, context=context, load=load)
  File "/home/odoo/runbot/extra/runbot/static/build/44934-8-0-859979/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/44934-8-0-859979/openerp/models.py", line 3109, in read
    result = BaseModel.read(records, fields, load=load)
  File "/home/odoo/runbot/extra/runbot/static/build/44934-8-0-859979/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/44934-8-0-859979/openerp/models.py", line 3152, in read
    values[name] = field.convert_to_read(record[name], use_name_get)
  File "/home/odoo/runbot/extra/runbot/static/build/44934-8-0-859979/openerp/models.py", line 5518, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/odoo/runbot/extra/runbot/static/build/44934-8-0-859979/openerp/fields.py", line 760, in __get__
    self.determine_value(record)
  File "/home/odoo/runbot/extra/runbot/static/build/44934-8-0-859979/openerp/fields.py", line 862, in determine_value
    self.compute_value(recs)
  File "/home/odoo/runbot/extra/runbot/static/build/44934-8-0-859979/openerp/fields.py", line 818, in compute_value
    self._compute_value(records)
  File "/home/odoo/runbot/extra/runbot/static/build/44934-8-0-859979/openerp/fields.py", line 810, in _compute_value
    self.compute(records)
  File "/home/odoo/runbot/extra/runbot/static/build/44934-8-0-859979/openerp/fields.py", line 503, in _compute_related
    record[self.name] = other[self.related[-1]]
  File "/home/odoo/runbot/extra/runbot/static/build/44934-8-0-859979/openerp/models.py", line 5527, in __setitem__
    return self._fields[key].__set__(self, value)
  File "/home/odoo/runbot/extra/runbot/static/build/44934-8-0-859979/openerp/fields.py", line 776, in __set__
    value = self.convert_to_cache(value, record)
  File "/home/odoo/runbot/extra/runbot/static/build/44934-8-0-859979/openerp/fields.py", line 1310, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for res.users.lang: u'en_US'

**Comment by xmo-odoo** [comment] 2015-02-11 07:40
I'm pretty sure it's a duplicate of #4453

**Closed by xmo-odoo** 2015-02-11 07:40 UTC
