### ISSUE TITLE
Odoo 13 js error

### ISSUE THREAD

**Issue by purevsurento** [odoo/odoo#48643] opened 2020-03-31 02:52 UTC
Impacted versions: 13.0
![Screenshot from 2020-03-31 18-50-04](https://user-images.githubusercontent.com/6300456/77981804-6a30be00-733d-11ea-860d-8c43004b49c9.png)

Steps to reproduce:

Current behavior: Traceback:
TypeError: Cannot read property 'apply' of undefined
    at Class.getScrollPosition (http://localhost:8069/web/content/255-d239c2d/web.assets_backend.js:506:20)
    at Class.prototype.(anonymous function) [as getScrollPosition] (http://localhost:8069/web/content/254-21395cb/web.assets_common.js:3866:488)
    at http://localhost:8069/web/content/255-d239c2d/web.assets_backend.js:504:101

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment] 2020-03-31 05:57
Hi @purevsurento,

Thanks for your report. Can you reproduce this on an official Odoo test instance at runbot.odoo.com?
We're missing steps to reproduce this problem so please add them and make sure it is reproducable on the latest code from Odoo.

Regards,
Yenthe

**Comment by purevsurento** [comment] 2020-03-31 06:18
web enterprise module installation error

**Comment by purevsurento** [comment] 2020-03-31 06:24
> Hi @purevsurento,
> 
> Thanks for your report. Can you reproduce this on an official Odoo test instance at runbot.odoo.com?
> We're missing steps to reproduce this problem so please add them and make sure it is reproducable on the latest code from Odoo.
> 
> Regards,
> Yenthe
web enterprise module installation error

**Comment by Yenthe666** [comment] 2020-03-31 06:47
Please give us reproducible steps on runbot.odoo.com or this issue will be closed as we cannot reproduce this. Are you sure you're on the latest version of the code?

**Comment by purevsurento** [comment] 2020-03-31 07:00
> Please give us reproducible steps on runbot.odoo.com or this issue will be closed as we cannot reproduce this. Are you sure you're on the latest version of the code?

Yes. lastest version code

**Comment by Yenthe666** [comment] 2020-03-31 07:15
Well, please test on a runbot and add the steps or a video here.

**Comment by Yenthe666** [comment] 2020-06-06 15:32
Closing as no extra info/videos have been added.

**Closed by Yenthe666** 2020-06-06 15:32 UTC
Labels: Need information
