### ISSUE TITLE
The translation of the quotation and order report does not load

### ISSUE THREAD

**Issue by Mbunto** [odoo/odoo#3866] opened 2014-11-25 13:32 UTC
Order report does not translate. When i look in the po file terms of the report are translate but but does not apply when printing.

**Comment by mayjo79** [comment] 2015-01-08 13:12
For me, this issue seems to be solved

**Comment by mart-e** [comment] 2015-01-08 13:56
Thanks for the update, closing this.
Now sure what you mean by saying my commit changed the language of the report, it shouldn't impact.
If you still have this, please open a new issue with steps to reproduce.

**Closed by mart-e** 2015-01-08 13:56 UTC
