### ISSUE TITLE
Odoo Ecommerce transaction

### ISSUE THREAD

**Issue by knb2121** [odoo/odoo#71185] opened 2021-05-24 08:51 UTC
Odoo Version 14

When Clicking products on e-commerce modules it is not proceeding to customer information

Traceback (most recent call last):
  File "/opt/odoo14test/odoo14test-server/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo14test/odoo14test-server/odoo/http.py", line 806, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo14test/odoo14test-server/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo14test/odoo14test-server/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo14test/odoo14test-server/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo14test/odoo14test-server/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo14test/odoo14test-server/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo14test/odoo14test-server/addons/website_sale/controllers/main.py", line 428, in cart_update
    sale_order = request.website.sale_get_order(force_create=True)
  File "/opt/odoo14test/odoo14test-server/addons/website_sale/models/website.py", line 293, in sale_get_order
    so_data = self._prepare_sale_order_values(partner, pricelist)
  File "/opt/odoo14test/odoo14test-server/addons/website_sale_stock/models/website.py", line 12, in _prepare_sale_order_values
    values = super(Website, self)._prepare_sale_order_values(partner, pricelist)
  File "/opt/odoo14test/odoo14test-server/addons/website_sale/models/website.py", line 225, in _prepare_sale_order_values
    'payment_term_id': self.sale_get_payment_term(partner),
  File "/opt/odoo14test/odoo14test-server/addons/website_sale/models/website.py", line 203, in sale_get_payment_term
    pt = self.env.ref('account.account_payment_term_immediate', False).sudo()
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo14test/odoo14test-server/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo14test/odoo14test-server/odoo/http.py", line 806, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo14test/odoo14test-server/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo14test/odoo14test-server/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo14test/odoo14test-server/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo14test/odoo14test-server/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo14test/odoo14test-server/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo14test/odoo14test-server/addons/website_sale/controllers/main.py", line 428, in cart_update
    sale_order = request.website.sale_get_order(force_create=True)
  File "/opt/odoo14test/odoo14test-server/addons/website_sale/models/website.py", line 293, in sale_get_order
    so_data = self._prepare_sale_order_values(partner, pricelist)
  File "/opt/odoo14test/odoo14test-server/addons/website_sale_stock/models/website.py", line 12, in _prepare_sale_order_values
    values = super(Website, self)._prepare_sale_order_values(partner, pricelist)
  File "/opt/odoo14test/odoo14test-server/addons/website_sale/models/website.py", line 225, in _prepare_sale_order_values
    'payment_term_id': self.sale_get_payment_term(partner),
  File "/opt/odoo14test/odoo14test-server/addons/website_sale/models/website.py", line 203, in sale_get_payment_term
    pt = self.env.ref('account.account_payment_term_immediate', False).sudo()
AttributeError: 'NoneType' object has no attribute 'sudo'

**Comment by pedrobaeza** [comment] 2021-05-24 08:54
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by knb2121** [comment] 2021-05-24 09:24
Hi pedrobaeza 

this error is based on our configuration, that we seem cant track back where it came from 


https://user-images.githubusercontent.com/69497718/119326707-c6c70900-bcb4-11eb-94d3-f7ea37469049.mp4

**Comment by pedrobaeza** [comment] 2021-05-24 09:26
Sorry, but if no possible to be reproduced in a runbot instance, then it can be due to several factors outside this repository and issue tracker: deployment, third-party modules, etc, so nothing can be done here.

I'm closing now the issue, but if you find a way to report specific steps that reproduce the problem in a runbot, then please report back and I'll reopen.

**Closed by pedrobaeza** 2021-05-24 09:26 UTC
Labels: Need information
