### ISSUE TITLE
Error without exception. Probably due do sending an email without computed recipients. in odoo11

### ISSUE THREAD

**Issue by thuypt35** [odoo/odoo#50886] opened 2020-05-08 03:16 UTC
1. Pre-condition:
the Email only has CC, hasn't To, 
2. Actual:
The email was delivery failed with reason:
Error without exception. Probably due do sending an email without computed recipients.

**Comment by pedrobaeza** [comment] 2020-05-08 06:54
And how do you get to that with standard Odoo?

**Comment by thuypt35** [comment] 2020-05-08 09:11
I edit a delivery fail email and resent it
(please see my image on link: http://prntscr.com/sd2fw8)

**Comment by pedrobaeza** [comment] 2020-05-08 09:55
But then that's a bad manipulation of the record, and thus it's not a bug itself. Please add reproducible steps for getting a problem on regular Odoo flows. Meanwhile, I close this.

**Closed by pedrobaeza** 2020-05-08 09:55 UTC
Labels: Need information

**Comment by thuypt35** [comment] 2020-05-08 10:05
We have a function to sent email, allow end user preview and edit To, CC.
The To field is not required field
The user didn't input anything in To field, They only input data in CC field

**Comment by pedrobaeza** [comment] 2020-05-08 10:12
As said, that's a bad manipulation. Forbid that option in your "function".

**Comment by thuypt35** [comment] 2020-05-08 10:19
I see I can sent an email without To, only Cc on gmail, so I can't do it on odoo?

**Comment by pedrobaeza** [comment] 2020-05-08 10:22
Starting with, this is not an email client, but not only that, you are manipulating incorrectly a model assuming it should be like an email, and it's not. For example, there are links to res.partner instead of plain email texts. Any way, you should know what to do if you are manipulating this, and it's very low level.
