### ISSUE TITLE
[14.0] Server error while marking as draft in the Time Off

### ISSUE THREAD

**Issue by Gokulakannanaj** [odoo/odoo#69989] opened 2021-04-28 11:17 UTC
Impacted versions:
14.0
Steps to reproduce:
1. Log in as Admin.
2. Navigate to Time Off -> Managers -> Time Off -> Create the record.
3. Create the record and the mode is By Employee Tag.
4. Approve the record and Refuse it now.
5. Click the "Mark as Draft".

Current behavior:
It throwing the Server Error.
Expected behavior:
The status should be changed from the Refuse to Draft without any Erros.
Video/Screenshot link (optional):
**Error Info**
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/data/build/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/data/build/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/data/build/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/build/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/build/odoo/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/build/odoo/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/data/build/odoo/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/data/build/odoo/addons/hr_holidays/models/hr_leave.py", line 947, in action_draft
    linked_requests.unlink()
  File "/data/build/odoo/addons/hr_holidays/models/hr_leave.py", line 830, in unlink
    return super(HolidaysRequest, self.with_context(leave_skip_date_check=True, unlink=True)).unlink()
  File "/data/build/odoo/addons/mail/models/mail_thread.py", line 337, in unlink
    res = super(MailThread, self).unlink()
  File "/data/build/odoo/addons/mail/models/mail_activity.py", line 771, in unlink
    result = super(MailActivityMixin, self).unlink()
  File "/data/build/odoo/odoo/models.py", line 3425, in unlink
    self.check_access_rule('unlink')
  File "/data/build/odoo/odoo/models.py", line 3346, in check_access_rule
    invalid = self - self._filter_access_rules_python(operation)
  File "/data/build/odoo/odoo/models.py", line 3401, in _filter_access_rules_python
    return self.sudo().filtered_domain(dom or [])
  File "/data/build/odoo/odoo/models.py", line 5314, in filtered_domain
    data = rec.mapped(key)
  File "/data/build/odoo/odoo/models.py", line 5242, in mapped
    recs = recs._fields[name].mapped(recs)
  File "/data/build/odoo/odoo/fields.py", line 1075, in mapped
    self.recompute(records)
  File "/data/build/odoo/odoo/fields.py", line 1153, in recompute
    self.compute_value(recs)
  File "/data/build/odoo/odoo/fields.py", line 1175, in compute_value
    records._compute_field_value(self)
  File "/data/build/odoo/addons/mail/models/mail_thread.py", line 410, in _compute_field_value
    return super()._compute_field_value(field)
  File "/data/build/odoo/odoo/models.py", line 4068, in _compute_field_value
    self.filtered('id')._validate_fields(fnames)
  File "/data/build/odoo/odoo/models.py", line 1260, in _validate_fields
    check(self)
  File "/data/build/odoo/addons/hr_holidays/models/hr_leave.py", line 580, in _check_holidays
    leave_days = mapped_days[holiday.employee_id.id][holiday.holiday_status_id.id]
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
KeyError: False

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment] 2021-04-28 11:45
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Gokulakannanaj** [comment] 2021-04-28 12:36
@pedrobaeza - Thanks for your update. Yeah, it's reproducible in the run bot too.

**Screenshot 1:** The record details 
![info-1](https://user-images.githubusercontent.com/41570711/116404383-32e85580-a84c-11eb-8ddb-da93fa239948.png)

**Screenshot 2:** Error Info, While clicking the Mark as Draft
![Info-2](https://user-images.githubusercontent.com/41570711/116404528-59a68c00-a84c-11eb-8422-269b9bb543d6.png)

**Comment by sswapnesh** [comment] 2021-04-28 18:24
![Screenshot(6)](https://user-images.githubusercontent.com/16624719/116453734-da7d7c00-a87c-11eb-97cf-b276deb4b8b3.png)

I am getting different Error with same steps

**Comment by Gokulakannanaj** [comment] 2021-04-29 02:26
@sswapnesh - Yeah, you are right. In the run but, It throws the server error and In my local(Community Edition) machine, It's throwing the error exactly what you get in the enterprise.

**Comment by pedrobaeza** [comment] 2021-04-29 06:27
But that's because a required data is missing, so I see it correct, and tests should always be done on runbot, as it contains latest code and no contamination from third party modules.

Closing thus.

**Closed by pedrobaeza** 2021-04-29 06:27 UTC
Labels: Need information

**Comment by Gokulakannanaj** [comment] 2021-04-29 08:47
@pedrobaeza - Then why am I getting the server error in the run bot? I think it's a bug.
