### ISSUE TITLE
Recuring costs generated on Fleet Module have roday's date

### ISSUE THREAD

**Issue by akselon** [odoo/odoo#40348] opened 2019-11-15 14:05 UTC
Impacted versions:
Odoo 13
Steps to reproduce:
1. Go to Fleet App,
2. Open a vehicle and a Contract (model: fleet.vehicle.log.contract) that begins on 01.01.2019 and ends on 31.12.2019 with some monthly recurring costs,
3. Wait until the Scheduler "Fleet: Generate contracts costs based on costs frequency" will run or run it manually.

Current behavior:
All generated costs have today's date.

Expected behavior:
I thought, that date would be set to first day of the month. Would it not be more natural?
This would be more natural for the reports.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/14870018/68948838-10c65900-07b9-11ea-996a-172b3285981c.png)

**Comment by pedrobaeza** [comment] 2019-11-15 16:42
This is an expected behavior, because this is not intended for doing things in the past: all the pending costs are posted with the date where it's examined. If not, there's the risk of doing operations in closed periods.

Closing this as expected behavior.

**Closed by pedrobaeza** 2019-11-15 16:42 UTC
