### ISSUE TITLE
When a POS session is closed out, any open orders are lost

### ISSUE THREAD

**Issue by multiwebinc** [odoo/odoo#15952] opened 2017-03-20 20:11 UTC
Impacted versions: 10.0

Steps to reproduce: 

- Start a POS session
- Select a table and click on a few items to add to the bill
- Go back to the Odoo main page and close out that session, do money validation, etc.
- Start a new session

Current behavior:

- A table had an open unpaid order that was completely lost.

Expected behavior:

- Either an error should prevent a server from closing their session (forcing all current customers to pay before it can be closed and validated), or the order should be passed on to the next session.

**Comment by Yenthe666** [comment] 2017-06-14 12:06
Hi @multiwebinc,

Thank you for your report.
I'm closing this one however as it is pretty much  a duplicate of your other topic (https://github.com/odoo/odoo/issues/16151) which has responses and the wishlist label.

Regards,
Yenthe

**Closed by Yenthe666** 2017-06-14 12:06 UTC

**Comment by multiwebinc** [comment] 2017-06-14 22:17
@Yenthe666 You're right. I must have the memory of a goldfish if I can't even remember reporting this a week earlier.

**Comment by Yenthe666** [comment] 2017-06-15 11:39
Haha no worries, it happens easily. ;)
