### ISSUE TITLE
Unable to change Purchase>Receive Orders page

### ISSUE THREAD

**Issue by kirtangajjar** [odoo/odoo#38923] opened 2019-10-17 08:45 UTC
Impacted versions: all

Steps to reproduce:

Go to Purchase > New Order > Confirm Order > Receive Orders. If you try to inherit the view and modify it(hide an attribute etc...), it will not show up on this page. However, if you refresh the page, the modifications will show up! I checked it on runbot master.

This page uses `stock/stock_picking_views.xml/view_picking_form`

Video/Screenshot link (optional):
![PurchaseOrders-Odoo-GoogleChrome](https://user-images.githubusercontent.com/8456197/66993005-78b94f00-f0e8-11e9-9d29-c53f049c36ea.gif)

**Comment by pedrobaeza** [comment] 2019-10-17 08:48
This is a totally expected behavior, as views are cached and not reloaded until you refresh the browser page.

Closing as no issue at all.

**Closed by pedrobaeza** 2019-10-17 08:48 UTC

**Comment by kirtangajjar** [comment] 2019-10-17 08:53
Hey @pedrobaeza, So what can I do here to see that my modifications show up when I click on "receive orders" and not when I refresh the page?

**Comment by pedrobaeza** [comment] 2019-10-17 09:01
I understood you were doing the changes on the fly. Have you programmed that in a module?

**Comment by kirtangajjar** [comment] 2019-10-17 09:05
Yes. I have created a custom module, and extended `stock.view_picking_form`. I can see my changes when I try to create a new transfer, but not in this form.

**Comment by pedrobaeza** [comment] 2019-10-17 09:10
This is because you are not inheriting the proper one. Please check which one is being used, or ask in the forum.
