### ISSUE TITLE
12.0 Cannot "Mark as Done" in Manufacturing Orders

### ISSUE THREAD

**Issue by tnquyinfo** [odoo/odoo#50531] opened 2020-05-04 03:47 UTC
Impacted versions: 12

Steps to reproduce: Manufacturing Orders

Current behavior: Cannot "Mark as Done"

Expected behavior: Check inventory, products have 10.000 gram, but reserved 9.999,99 (error), i can't fix.

Video/Screenshot link (optional):
![loi1](https://user-images.githubusercontent.com/50733014/80934876-5d97fd80-8df4-11ea-9192-bd5206ab27c1.png)
![loi2](https://user-images.githubusercontent.com/50733014/80934877-5f61c100-8df4-11ea-8060-94e2bd985c52.png)

**Comment by pedrobaeza** [comment] 2020-05-04 06:46
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by tnquyinfo** [comment] 2020-05-05 09:34
Please sent me "file tutorial" how to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot), i try to building but not running (i upload my database ~170 MB, get 413 Request Entity Too Large on runbot32.odoo.com
![413 Request Entity Too Large on runbot32 odoo com](https://user-images.githubusercontent.com/50733014/81051765-87cce680-8eec-11ea-9069-083704dda8ab.png)
).

I provide more infomation about problem:
- I have Bills of Material (include 1 material S ~ 500 gram + 1 nylon-bag) manufacture 1 product A.
- Infomation Inventory:
+ Material S have 15.000 gram.
+ Nylon-bag have 30 unit.
My situation:
- Manufacture 20 product A.
+ Theory, system uses 10.000 gram & 20 nylon-bags.
+ Reality, system reserved 9.999 gram (but display 10.000 gram) & 20 nylon-bags.
I can't complete the Manufacturing Orders.

Please help!

**Comment by pedrobaeza** [comment] 2020-05-05 09:47
You can't upload your DB. You have to recreate the problem with the minimal data set in runbot for being reproducible, and specify all this data.

**Comment by tnquyinfo** [comment] 2020-05-05 09:58
But the problem self occurs during system running, my server runs 18 months, this is first error.
I can't recreate that, i think if i create error, i can fix it.
Are you wanted me to do a mission impossible?

Thanks your answer.

**Comment by pedrobaeza** [comment] 2020-05-05 10:00
Then do you expect here that we do that impossible mission? If you have an enterprise contract, you can ask for direct support in your DB through odoo.com/help. If not, here we can only track issues that are reproducible, which means all the needed requirements I have specified.

**Comment by tnquyinfo** [comment] 2020-05-05 10:09
I know i use version Community Edition, i don't have better help as Enterprise contract.
System has "ManyToMany Relations", so i can't delete the Manufacturing Orders, make the system always display 2 unfinished jobs.

Thank you!

**Closed** 2020-05-05 10:09 UTC
Labels: Need information
