### ISSUE TITLE
Singleton Odoo 9

### ISSUE THREAD

**Issue by sidick43** [odoo/odoo#14487] opened 2016-11-26 17:27 UTC
Traceback (most recent call last):
  File "D:\openworkspaceodoo9\odoo9\odoo\openerp\http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "D:\openworkspaceodoo9\odoo9\odoo\openerp\http.py", line 680, in dispatch
    result = self._call_function(**self.params)
  File "D:\openworkspaceodoo9\odoo9\odoo\openerp\http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "D:\openworkspaceodoo9\odoo9\odoo\openerp\service\model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "D:\openworkspaceodoo9\odoo9\odoo\openerp\http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "D:\openworkspaceodoo9\odoo9\odoo\openerp\http.py", line 959, in __call__
    return self.method(*args, **kw)
  File "D:\openworkspaceodoo9\odoo9\odoo\openerp\http.py", line 509, in response_wrap
    response = f(*args, **kw)
  File "D:\openworkspaceodoo9\odoo9\odoo\addons\master_ent\web\controllers\main.py", line 905, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "D:\openworkspaceodoo9\odoo9\odoo\addons\master_ent\web\controllers\main.py", line 926, in do_search_read
    request.context)
  File "D:\openworkspaceodoo9\odoo9\odoo\openerp\http.py", line 1064, in proxy
    result = meth(cr, request.uid, *args, **kw)
  File "D:\openworkspaceodoo9\odoo9\odoo\openerp\api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "D:\openworkspaceodoo9\odoo9\odoo\openerp\models.py", line 5257, in search_read
    result = self.read(cr, uid, record_ids, fields, context=read_ctx)
  File "D:\openworkspaceodoo9\odoo9\odoo\openerp\api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "D:\openworkspaceodoo9\odoo9\odoo\openerp\models.py", line 3175, in read
    result = BaseModel.read(records, fields, load=load)
  File "D:\openworkspaceodoo9\odoo9\odoo\openerp\api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "D:\openworkspaceodoo9\odoo9\odoo\openerp\models.py", line 3221, in read
    values[name] = field.convert_to_read(record[name], use_name_get)
  File "D:\openworkspaceodoo9\odoo9\odoo\openerp\models.py", line 5721, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "D:\openworkspaceodoo9\odoo9\odoo\openerp\fields.py", line 807, in __get__
    self.determine_value(record)
  File "D:\openworkspaceodoo9\odoo9\odoo\openerp\fields.py", line 914, in determine_value
    self.compute_value(recs)
  File "D:\openworkspaceodoo9\odoo9\odoo\openerp\fields.py", line 869, in compute_value
    self._compute_value(records)
  File "D:\openworkspaceodoo9\odoo9\odoo\openerp\fields.py", line 859, in _compute_value
    getattr(records, self.compute)()
  File "D:\openworkspaceodoo9\odoo9\odoo\sankofa_addons\gestion_pv\gestion_pv.py", line 184, in _create_name
    if self.type_epreuve_id and  self.dossierinscription_id and self.annee_id :
  File "D:\openworkspaceodoo9\odoo9\odoo\openerp\fields.py", line 797, in __get__
    record.ensure_one()
  File "D:\openworkspaceodoo9\odoo9\odoo\openerp\models.py", line 5384, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: gestion_pv.composition(22, 23)

**Comment by Yenthe666** [comment] 2016-11-28 08:48
Hi @sidick43,

Thanks for your report. It however looks like the issue that you're facing is regarding custom development (gestion_pv) module.
This error is telling you that you're looping over a recordset why your code requires a record. If you still face this issue please create an help question on the official forums (help.odoo.com) and add the code there, then people can help you further.
I'm closing this since it is not a bug and neither is it in the official Odoo code.

Regards,
Yenthe

**Closed by Yenthe666** 2016-11-28 08:48 UTC
