### ISSUE TITLE
TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by aaronsaquing** [odoo/odoo#40392] opened 2019-11-18 07:29 UTC
Impacted versions: 13
Resume Module

Steps to reproduce:
1. Create Menu Item > Resume under Employees
2. Create Window Action to show Resume on Employee Menu

Current behavior:
Return a Traceback:
TypeError: Cannot read property 'type' of undefined

Expected behavior:
Go to Resume Tree View

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/42097911/69032719-45dce080-0a31-11ea-8fcd-98585968d405.png)

**Comment by pedrobaeza** [comment] 2019-11-18 08:48
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2019-11-18 08:48 UTC
Labels: 13.0, HR

**Comment by aaronsaquing** [comment] 2019-11-18 22:43
Hi Pedro, this issue is reproduce not doing any code that just through the developer mode GUI Menu Items and Windows Actions. On the Skills there have no problem. So it can be assumed that the Resume can also be placed on Employee Menu without any errors.  I am referring to the new hr_skills module which contains Resume and Skills models. 

I am just saying that this happen on the standard Odoo module. Hence posting it here.

Thank you.
