### ISSUE TITLE
"Failed to render template <Template memory:7f525c556a90>"  when adding user to a meeting

### ISSUE THREAD

**Issue by marciorpbradoo** [odoo/odoo#15031] opened 2017-01-11 17:05 UTC
Impacted versions: Odoo 10.0 Enterprise

Steps to reproduce: Fresh Odoo > Install Calendar > Create new meeting > **Add system user other than the owner of the meeting**.

Current behavior: When the steps described are reproduced the systems doesn't allow to save the changes in the meeting.

Expected behavior: It should be possible to save the Meeting after adding other user to it.

Odoo log
2017-01-11 16:51:40,118 1568 INFO database werkzeug: 104.236.197.28 - - [11/Jan/2017 16:51:40] "POST /web/dataset/call_kw/res.partner/get_attend$
2017-01-11 16:51:41,548 1568 INFO database odoo.addons.mail.models.mail_template: Failed to render template <Template memory:7f525c556a90> using$
Traceback (most recent call last):
  File "/odoo/odoo-server/addons/mail/models/mail_template.py", line 360, in render_template
    render_result = template.render(variables)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 40, in top-level template code
  File "/usr/local/lib/python2.7/dist-packages/jinja2/sandbox.py", line 356, in call
    return __context.call(__obj, *args, **kwargs)
TypeError: get_interval() got multiple values for keyword argument 'tz'

Video/Screenshot link (optional):
![captura de tela de 2017-01-11 11 03 23](https://cloud.githubusercontent.com/assets/22821998/21858197/5d0495fc-d80f-11e6-806f-37d4836bd772.png)

**Comment by lukebranch** [comment] 2017-01-12 01:25
@marciorpbradoo,

I believe there is a problem with an email template that is being triggered by this action. Do you have any custom modules installed?

I would also suggest attempting to reproduce this issue on the runbots:

runbot.odoo.com

username: admin
password: admin

Just choose the 10.0 branch there and provide steps to reproduce this issue on the runbots.

If possible also provide an animated GIF demonstrating the issue using something like:

http://www.cockos.com/licecap/

Once you've done this and confirmed the issue on the runbots your issue will be easier for the Odoo dev team to review and reproduce tge issue themselves.

**Comment by Yenthe666** [comment] 2017-01-12 07:09
Yep, those are great tips @lukebranch. Thank you for explaining this in detail.
If you can give me some more details that would be great. I just tried this on the latest Odoo 10 without problems.

**Comment by marciorpbradoo** [comment] 2017-01-13 12:44
@Yenthe666 @lukebranch 
Thanks for the responses! Sorry for the delay to answer.

Yes, I have tried running it in runbot and the result is the same as the one reported by @Yenthe666, the problem doesn't happen.
Both odoo and enterprise folders were updated from GitHub today and the problem persists.
There is no custom module installed other than a custom webtheme, but I don't believe that such a thing could interfere in the mail template.

I really would like to provide more details to help solve the issue, but this is as much as I can get. The only log message is the one posted above and the steps to reproduce are as simple as described.

**Comment by Yenthe666** [comment] 2017-01-13 12:57
@marciorpbradoo let me double check to be absolutely sure. So, you cannot reproduce this on official Runbot instances and only have this issue on your local Odoo?
If this is the case then please update your codebase, update your whole Odoo and try again.

**Comment by marciorpbradoo** [comment] 2017-01-13 13:47
@Yenthe666 That's it, this is NOT happening in a runbot instance.
As mentioned, I just updated my server from the official GitHub repositories odoo and enterprise. Are there other ways to update Odoo ?

Additionally, while trying different scenarios I just discovered that the problem is not limited to system users. Actually I can't add any Attendees other than my current user to a meeting. The problem is not related to a particular user, given that other people reported the same issue to me.

**Comment by lukebranch** [comment] 2017-01-17 00:34
@marciorpbradoo ,

My personal suggestion would be to create a backup of your current DB and keep it as a local backup, then duplicate your existing DB and call it something like DB_Test. Once you've done this restart the odoo-server from the command line (eg. service odoo-server restart) which will update the python code being used in the DB's, and then login to your duplicated test DB (DB_Test) and take a look at your installed modules and upgrade modules related to the calendar app.

You may want to try reproduce the issue again at this point as perhaps the issue you've run into is related to the python code.

If this doesn't work i'd suggest upgrading the app, this will update the views in the module (which is where I suspect the problem is).

Before you do the upgrade on that app, i'd suggest making sure your /etc/odoo-server.conf file has something like the following in there:

limit_time_cpu = 12000
limit_time_real = 24000

When you upgrade the calendar module you will be triggering an upgrade for mail (discuss) and a few other modules which could take some time. After you've done a successful upgrade in your DB_Test db see if you can reproduce the issue locally.

If you find that once this is done you're still able to reproduce the issue, i'd suggest uninstalling any community modules you have installed in the DB_Test db, and remove them from the addons_path in /etc/odoo-server.conf.

FWIW I have not been able to reproduce this issue on a local instance of Odoo 10.0c, however I have not yet had the chance to test it on 10.0e.

**Comment by Yenthe666** [comment] 2017-01-17 06:11
@lukebranch good and detailed answer. I've tested it on V10E so we can exclude that too. A -u all after a fit fetch should absolutely do the job.

**Comment by marciorpbradoo** [comment] 2017-01-23 12:01
Took me sometime to figure this one. It turns out that there was a problem with the translated email templates. I took the original ones in english and had them translated myself after that I pasted where the old translated templates were.

@Yenthe666 @lukebranch 
Thanks for all the help provided!

**Comment by Yenthe666** [comment] 2017-01-23 12:03
Hi @marciorpbradoo,

Alright good to hear you've got it solved! Closing this issue then.
Best of luck.

Regards,
Yenthe

**Closed by Yenthe666** 2017-01-23 12:03 UTC

**Comment by eldy** [comment] 2017-03-21 09:51
I got the same trouble. It's true that making a new translation may fix this but it is not the problem. Real problem is a bug into the default sale order template. Into template, you have
		% set access_url = is_online and access_action['url'] or object.get_signup_url()
where you should have
		% set access_url = is_online and access_action['url']

Because var access_url is used late only if is_online is set the the or is useless and above all the or is using a method that is not vailable returning this stack trace:

Traceback (most recent call last):
  File "/home/ldestailleur/git/teclib_odoo_lugos/odoo/addons/mail/models/mail_template.py", line 376, in render_template
    render_result = template.render(variables)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 7, in top-level template code
  File "/usr/local/lib/python2.7/dist-packages/jinja2/sandbox.py", line 432, in call
    if not __self.is_safe_callable(__obj):
  File "/usr/local/lib/python2.7/dist-packages/jinja2/sandbox.py", line 345, in is_safe_callable
    return not (getattr(obj, 'unsafe_callable', False) or
UndefinedError: 'odoo.api.sale.order object' has no attribute 'get_signup_url'

**Comment by marciorpbradoo** [comment] 2017-03-21 13:29
Well noted, thanks for sharing the real solution. 
Hopefully this is going to be useful in the future

**Comment by alexanderahlsen** [comment] 2017-03-25 10:08
I'm having the same error on 10c when I translated to Norwegian. But I can't seem to fix it by re-translating... Can someone help me solve this?
Here is the error:
`Failed to render template <Template memory:7f5a66504ed0> using values {'format_tz': <function <lambda> at 0x7f5a663e0230>, 'ctx': {u'lang': u'nb_NO', u'tz': u'Europe/Oslo', u'uid': 1, u'active_model': u'mail.template', 'safe': False, u'params': {u'menu_id': 89, u'view_type': u'list', u'min': 1, u'limit': 80, u'action': 99, u'_push_me': False, u'model': u'mail.template'}, u'search_disable_custom_filters': True, u'active_ids': [6], u'template_id': 6, u'active_id': 6}, 'user': res.users(1,), 'object': calendar.attendee(1,)}`

**Comment by lukebranch** [comment] 2017-03-25 11:47
Do you have any community modules installed, or is this just core Odoo?

If there are no community modules I think a full traceback and a GIF demonstrating steps to reproduce would be very useful for Odoo SA to debug.

**Comment by kurkop** [comment] 2017-04-05 17:57
@Yenthe666 I think that this is a error of Odoo. We upgrade Odoo 9 to 10 and this translations fails tool. 

If I want create a new metting show this:

```
Failed to render template <Template memory:7f5a66504ed0> using values {'format_tz': <function <lambda> at 0x7f5a663e0230>, 'ctx': {u'lang': u'nb_NO', u'tz': u'Europe/Oslo', u'uid': 1, u'active_model': u'mail.template', 'safe': False, u'params': {u'menu_id': 89, u'view_type': u'list', u'min': 1, u'limit': 80, u'action': 99, u'_push_me': False, u'model': u'mail.template'}, u'search_disable_custom_filters': True, u'active_ids': [6], u'template_id': 6, u'active_id': 6}, 'user': res.users(1,), 'object': calendar.attendee(1,)}
```
I fix this when delete "Meeting Invitation Template" translations. (With es_CO).
Settings->Technical->Templates->Meeting Invitation (edit) - Click in translations, select all translations and remove.

Could Odoo show the template that fails?

**Comment by rafaelbn** [comment] 2017-05-25 23:25
Hi @Yenthe666 @lukebranch , we have same error and the solution is in @eldy comment: https://github.com/odoo/odoo/issues/15031#issuecomment-288027574

For sure the error is generated by `or object.get_signup_url()` in "Sales Order - Send by Email" template

😲 

The problem has been solved by Odoo in any moment (I don't know when), but everyone who has this issue has to fix the template... This one is correct:

```

<p>Dear ${object.partner_id.name}
% set access_action = object.with_context(force_website=True).get_access_action()
% set doc_name = 'quotation' if object.state in ('draft', 'sent') else 'order confirmation'
% set is_online = access_action and access_action['type'] == 'ir.actions.act_url'
% set access_name = is_online and object.template_id and doc_name == 'quotation' and 'Accept and pay %s online' % doc_name or 'View %s' % doc_name
% set access_url = is_online and access_action['url'] or None

% if object.partner_id.parent_id:
    (<i>${object.partner_id.parent_id.name}</i>)
% endif
,</p>
<p>
Here is your ${doc_name} <strong>${object.name}</strong>
% if object.origin:
(with reference: ${object.origin} )
% endif
amounting in <strong>${object.amount_total} ${object.pricelist_id.currency_id.name}</strong>
from ${object.company_id.name}.
</p>

    <br><br>
% if is_online:
    <center>
        <a href="${access_url}" style="background-color: #1abc9c; padding: 20px; text-decoration: none; color: #fff; border-radius: 5px; font-size: 16px;" class="o_default_snippet_text">${access_name}</a>
        <br><br>
        <span style="color:#888888">(or view attached PDF)</span>
    </center>
    <br>
% endif

<p>You can reply to this email if you have any questions.</p>
<p>Thank you,</p>

<p style="color:#eeeeee;">
% if object.user_id and object.user_id.signature:
    ${object.user_id.signature | safe}
% endif
</p>
```

**Comment by Danisan** [comment] 2017-06-02 21:15
In my case solved it changing the language to english. To be more specific, the problem is that when using this in a language different from english, Jinja2 received the word "objetivo" instead of the reserved word "object", so he could not render.

**Comment by herohat** [comment] 2017-08-14 03:37
Hi,

I have the same problem in "Sales Order - Send by Email" template.   But my problem can't be fixed removing the translation or sending the email in english.   I tested removing everything from the template and doesn't work. 

I am On branch 10.0.    Any advice? 


Thank you

**Comment by herohat** [comment] 2017-08-17 02:12
Hi,

After of hours and hours debugging, I found the error for my issue.

In Settings => Email -> Templales => Sale Order Notification Email.   Then in tab "Advanced Settings"   I set the value for language field:  ${object.partner_id.lang},  that in order to get this template multi-language, just as the help tooltip for this field said, but this throw the error. 

Tooltip Screenshot:  `https://onedrive.live.com/?authkey=AvphfTf2THpwh5E&cid=1B8E966532F20D97&id=1B8E966532F20D97%21277&parId=1B8E966532F20D97%21105&o=OneUp` 

I didn't realize what that was the problem because I did a lot of changes before I detect the problem.

I hope my experience help others and if this is a error in ODOO (at least in the tooltip), can be fixed.

**Comment by Heifara** [comment] 2017-10-24 01:46
Hi,
I had the same problem. I solve it by updating my odoo and reinstalling the calendar module.

1. Update Odoo
`$ sudo apt-get update && sudo apt-get upgrade`

2. Re-install calendar
`$sudo odoo -d demo -i calendar`

**Comment by 12cedrych** [comment] 2019-06-12 15:17
Hello I am meeting this odoo error whenever I want to send an email template that confirms hotel reservation. Can someone help me plz. I am pasting the error below|:

Failed to render template <Template memory:7f08b0f3c940> using values {'format_date': <function MailTemplate.render_template.<locals>.<lambda> at 0x7f08c4c68620>, 'format_tz': <function MailTemplate.render_template.<locals>.<lambda> at 0x7f08c4c68840>, 'format_amount': <function MailTemplate.render_template.<locals>.<lambda> at 0x7f08c4c68598>, 'user': res.users(7,), 'ctx': {'lang': 'en_US', 'tz': False, 'uid': 7, 'params': {'action': 359}, 'active_model': 'hotel.reservation', 'active_id': 540, 'active_ids': [540], 'default_model': 'hotel.reservation', 'default_res_id': 540, 'default_use_template': True, 'default_template_id': 12, 'default_composition_mode': 'comment', 'force_send': True, 'mark_so_as_sent': True, 'search_disable_custom_filters': True, 'tpl_partners_only': True, 'safe': False}, 'object': hotel.reservation(540,)}
