### ISSUE TITLE
Website console error when loading language over https

### ISSUE THREAD

**Issue by implementosk** [odoo/odoo#42137] opened 2019-12-18 18:43 UTC
Impacted versions:
13
Odoo by Bitnami on Google Cloud

Steps to reproduce:
Install Website, Ecommerce modul
Install and activate second language
Add language to languages avialable on your website
Go to website
Change Language

Current behavior:
Mixed Content: The page at 'https://www.waki-vaky.com/sk/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://www.waki-vaky.com/sk/website/translations/a424fef376dd523e3a7fee66995534b2b82091c9?mods=&lang='. This request has been blocked; the content must be served over HTTPS.

Because of this issue website navigation is not displayed.

I tried changing system parameters website url to https.
Also tried to reinstall language logged over https.

Expected behavior:
Navigation should be displayed.
Translation should be loaded over https.

Video/Screenshot link (optional):
<img width="1680" alt="Screenshot 2019-12-18 at 19 42 03" src="https://user-images.githubusercontent.com/35446152/71113730-84032680-21ce-11ea-8df8-54a99be07dbd.png">

**Comment by pedrobaeza** [comment] 2019-12-18 18:52
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/13.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).

**Closed by pedrobaeza** 2019-12-18 18:52 UTC

**Comment by marclijour** [comment] 2020-01-27 01:59
I have exactly the same issue here with Odoo 13 (latest deb binary package). The problem comes from the web proxy (in my case Nginx deals with HTTPS and passes requests to Odoo on port 8069). I have configured the proxy to pass the https scheme. Everything I need works fine except for the translation which is requested through http every time. As a result, the browser blocks the request (because of the mixed content) and the menu doesn't show up in the second language.

notes
- I found no solution on forums or list
- following a forum recommendation: I have already tried to update the web.base.url to https:// instead of http:// and I've also created the parameter web.base.url.freeze and assigned to True.

**Comment by marclijour** [comment] 2020-01-28 18:19
My mistake
This was missing in nginx conf:
`proxy_set_header X-Forwarded-Host $host;`

**Comment by treviser** [comment] 2020-01-29 12:12
FYI: This proxy setting should be obsolete when using Werkzeug 0.15, see https://github.com/odoo/odoo/issues/35085

**Comment by medellino** [comment] 2020-03-05 04:50
> 
> 
> FYI: This proxy setting should be obsolete when using Werkzeug 0.15, see #35085

That had been the solucion for me! Thanks a lot!

**Comment by hydrandt** [comment] 2020-05-22 08:24
If you run into this problem, double-check the `proxy_set_header X-Forwarded-Host $host;` in nginx config **and** `proxy_mode = True` in odoo config.

**Comment by lyprono** [comment] 2021-05-28 01:57
Hello i have got this problem too and i have config proxy_mode = True with odoo.conf  in docker .i really need you help .thank

**Comment by jellyhappy** [comment] 2021-07-30 08:31
After digging the codes with an afternoon, I found the solution finally , just change the config in your nginx config file:

`proxy_redirect http://yourdomainhere/ https://yourdomainhere/;`

@pedrobaeza is correct , this is not relevant with odoo, it's a deployment error.

**Comment by johnbritto1** [comment] 2021-12-22 10:24
Try adding a header in the Nginx domain server block.
add_header Content-Security-Policy "upgrade-insecure-requests";

**Comment by sh4dowb** [comment] 2022-05-18 00:16
nginx ssl:
`proxy_set_header X-Forwarded-Proto $scheme;`

nginx http + cloudflare https (flexible ssl)
`proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;`

**Comment by looeee** [comment] 2022-11-11 23:57
I'm using Nginx Proxy Manager, Let's Encrypt, Cloudflare CDN. `proxy_mode = True` in odoo.conf. NPM is already set to force HTTPS. 

However I was stilling getting the error so I went through all the suggestions here. Here's my results:

```
// Doesn't solve the issue: 
proxy_set_header X-Forwarded-Host $host;

// Doesn't solve the issue: 
add_header Content-Security-Policy "upgrade-insecure-requests";

// Doesn't solve the issue: 
proxy_set_header X-Forwarded-Proto $scheme;

// Doesn't solve the issue: 
proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;

// ...solves the issue (finally!) 
proxy_redirect http://mysite.com/ https://mysite.com/;
```

**Comment by devangi1810** [comment] 2024-01-24 13:01
// ...solves the issue (finally!) 
proxy_redirect http://mysite.com/ https://mysite.com/;

**Comment by alejandrosofter** [comment] 2024-06-21 10:48
@looeee only love! 2 days search and find solution! thanks
