### ISSUE TITLE
Odoo Client Error When Editing Users

### ISSUE THREAD

**Issue by ChiaraFrr** [odoo/odoo#51734] opened 2020-05-23 16:43 UTC
Impacted versions: Odoo 13.0-20200523 (Community Edition)

Steps to reproduce: Select a User and click on edit, then click on Employee(s) or Go to website and error occurs

Current behavior: After the error is displayed the links and buttons on the page don't work anymore until you refresh the page

Expected behavior: Go to Employee(s) or open the website

Video/Screenshot link (optional):

Error: (I have removed the real domain and added a dummy one - domain.com)

Traceback:
TypeError: this.wysiwyg.saveCroppedImages is not a function
    at Class.commitChanges (https://domain.com/web/content/1349-e677060/web.assets_backend.js:2590:55)
    at Class.prototype.<computed> (https://domain.com/web/content/506-3513272/web.assets_common.js:3860:488)
    at Class.commitChanges (https://domain.com/web/content/1349-e677060/web.assets_backend.js:2644:13)
    at Class.commitChanges (https://domain.com/web/content/506-3513272/web.assets_common.js:3863:371)
    at https://domain.com/web/content/1349-e677060/web.assets_backend.js:1388:235
    at Function._.map._.collect (https://domain.com/web/content/506-3513272/web.assets_common.js:109:270)
    at Class.commitChanges (https://domain.com/web/content/1349-e677060/web.assets_backend.js:1388:169)
    at https://domain.com/web/content/1349-e677060/web.assets_backend.js:1371:355

**Comment by pedrobaeza** [comment] 2020-05-24 09:50
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Yenthe666** [comment] 2020-07-27 13:42
Hi there,

Since there has been no feedback since our last question I'm closing this issue.
Don't hesitate to comment back with extra information / reproducable steps and we'll be happy to reopen this issue.

Regards,
Yenthe

**Closed by Yenthe666** 2020-07-27 13:42 UTC
Labels: Need information
