### ISSUE TITLE
Static files not shown in browser

### ISSUE THREAD

**Issue by werkwolk** [odoo/odoo#55646] opened 2020-08-07 17:35 UTC
Impacted versions: odoo 13
OS: windows server 2016

Steps to reproduce: load any theme 

Expected behavior: show the image 

I was asked by an odoo helpdesk employee to post the issue here.

all descripton subfolder images give following error

web.assets_common.js:1030 GET  http://myserveraddress/web/image/theme_default/static/description/theme_default_screenshot.jpg 404 (NOT FOUND)

i tried different themes, reinstalled the os multiple times, reinstalled odoo/postgress, keep getting the same error

the file actually exists on the file system, but the browser doesnt seem to load it

PS, localhost works the same way on the sever itself, so its not a routing/proxy problem

**Comment by pedrobaeza** [comment] 2020-08-07 17:49
The path is not correct, as that one is not a static path. It mustn't contain /image/ in the middle.

Closing as invalid.

**Closed by pedrobaeza** 2020-08-07 17:49 UTC

**Comment by werkwolk** [comment] 2020-08-07 18:09
well..i can guarantee you that 100% of all windows users will have no clue why that "image" is in the middle of it.

in this case it seems to be a bug in the rendering of the webpages?

**Comment by pedrobaeza** [comment] 2020-08-07 18:11
Unless you reproduce the problem in a runbot (https://runbot.odoo.com), and tell us the steps to reproduce, that's something that doesn't happen on standard.

**Comment by werkwolk** [comment] 2020-08-08 01:10
i tried looking into that but have no idea what/how...i'm just a simple user. 

in any case, i used an older installer and it works with that one. 

for me its all the same to be honest. just pointing out there's a bug in the latest installer. if someone has the time/will to try a simple vanilla install + look into the url, he/she will notice this bug immediately.

**Comment by pedrobaeza** [comment] 2020-08-08 10:12
Which theme and how do you load it?

**Comment by Yenthe666** [comment] 2020-08-08 10:22
Also, this one is super weird:

> I was asked by an odoo helpdesk employee to post the issue here.

Did they ask so because you do not have an enterprise license?

**Comment by werkwolk** [comment] 2020-08-08 17:06
@pedrobaeza 
Any theme, even the default loaded one doesnt show any background images. I watched some youtubers installing odoo on window s and they had it happen during their stream. Its definetely a version issue, because some work and others have the prob.

@Yenthe666 
We were asked to become a partner and we have a meeting the 19th. when i pointed out the issue to live chat they asked me to "ask for a pull".

 If we are going to promote this product we will have to "defend" the community version too towards customers that know we are an odoo partner. We will not get away with "its community sorry, get enterprise". 
So i'm trying out the community version myself and...man...coming from MS suit env, in which i thought there were too many bugs, have i been surprised with the massive amount of bugs i've already encountered in Odoo. the most frustrating part about it is, that most of it is considered "user mistakes". I'm not an expert in any field, but i've been in ICT since my 12th and been developing software since then. I'm now 38. I know the difference most of the time between config issues and errors that shouldnt "come out of the box". 

I know for a fact that if we ever encounter this with our current dynamics/Crm/sharepoint customers...they'll be spooked forever.

**Comment by Yenthe666** [comment] 2020-08-09 05:59
I've never really gotten this though.

I run multinationals in Odoo that revenue 7-figure numbers every month. I also run customers with just 10 users. Odoo works perfect for all of them. Sure once in a while you have some bug or need to create a ticket but that's with any software. Go look at Microsoft SharePoint, it has some serious flaws at some point.

On a side note, you should run Odoo  on a Linux and with a Github repo. Works better.
If you can show us reproducible steps on a runbot instance (runbot.odoo.com) we can recheck though!

**Comment by werkwolk** [comment] 2020-08-09 22:49
yenthe: i believe odoo works properly for most parts.  

an update on the issue: its the same on linux. i installed it on ubuntu. although i have to admit its ALOT faster, the problem persists. 

for now i'm not going to put more effort in in (runbot). others will start encountering the problem + reporting it too. so it'll get fixed one day i hope.
