### ISSUE TITLE
Only first two pages are visible when clicking "Search More" on an m2o field

### ISSUE THREAD

**Issue by luisg123v** [odoo/odoo#32066] opened 2019-03-22 23:18 UTC
Impacted versions:
- 12.0
- 11.0

Steps to reproduce:
- Go to contacts
- Click on any contact and edit it
- Click the country field and click "Search More"

Current behavior:
Only two first pages are shown and navigable, which means only 160 records are visible (2*80=160)

Expected behavior:
All pages should be visible. and navigable.

Video/Screenshot link (optional):
![List of countries](https://user-images.githubusercontent.com/19801181/54857708-68fa9900-4cc6-11e9-8a91-1a1876d8fb0f.png)

**Comment by luisg123v** [comment] 2019-03-22 23:29
opw-1958886

CC @yaniaular

**Comment by sswapnesh** [comment] 2019-03-23 05:01
Duplicate of https://github.com/odoo/odoo/issues/28975,https://github.com/odoo/odoo/issues/29708,
https://github.com/odoo/odoo/issues/12001 and https://github.com/odoo/odoo/issues/1386

**Comment by fmdl** [comment] 2019-03-23 07:00
Hack Idea : create a filter like this for all model :
`<filter name="limit_160" string="160 first result" domain="[]"/>`
this filter is called on the `search_more` view, and when you remove it, you show all.
and in the js : `context.update(search_default_limit_160=1)`

**Hack Test :**
on partner search view add : `<filter name="limit_160" string="160 first result" domain="[]"/>`
on a purchase form on field `partner_id` add context="{'search_default_limit_160':1}"
reload
click on search more, you see the filter `160 first result`, delete it, and now the limit in infinit :-)

@nim-odoo @Yenthe666 @odony

**Comment by Yenthe666** [comment] 2019-03-23 08:18
Hi all,

You know this is made and done by design in the ORM right? This has been done for performance. Once you do any search query the 160 limit will be removed and you'll get all the desired results.

**Closed** 2019-03-23 08:18 UTC

**Comment by luisg123v** [comment] 2019-03-23 11:05
@Yenthe666 I understand this is intentional. However, I believe it's still an issue, because people get confused about it, as may be appreciated on the related issues. Moreover, I think this will continue to happen in the future, until this is solved or clarified.

**Comment by sswapnesh** [comment] 2019-03-23 11:09
As mentioned in https://github.com/odoo/odoo/issues/12001#issuecomment-383838210
> for info, an (internal) task (task id: 34105) was created to solve this issue. It is in the framework project, and may or may not be done in the future. But it is still possible :)

Maybe @ged-odoo  can add some update on this if any.

**Comment by pedrobaeza** [comment] 2019-03-23 11:27
@luisg123v there's a reason for this to be that way, and it's performance, as `name_search` + `name_get` is performed under the hook. While this technical "debt" exists, this can't change. This is not an issue, but a know behavior that you have to get used to. As said, when you search again inside the popup, the limitation disappears.
