### ISSUE TITLE
email Marketing V12 CE  

### ISSUE THREAD

**Issue by PDMeira** [odoo/odoo#55430] opened 2020-08-04 23:04 UTC
Impacted versions:
Odoo 12 CE

Steps to reproduce:

create a new email marking template 

Current behavior:

don't show any email template, email component on the left.
It says on email body <p>on_change_model_and_list</p>

Expected behavior:

email body templatges, componets on the left of the screen

Video/Screenshot link (optional):

<img width="1685" alt="image" src="https://user-images.githubusercontent.com/12361370/89353842-3e3c9500-d6af-11ea-8e52-ba3344c30e6f.png">

**Comment by pedrobaeza** [comment] 2020-08-05 06:49
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Closed** 2023-04-07 14:27 UTC
Labels: Need information
