### ISSUE TITLE
[8.0] empty string seems on calendar rules !

### ISSUE THREAD

**Issue by malatestay** [odoo/odoo#6502] opened 2015-04-28 16:22 UTC
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/calendar/controllers/main.py", line 61, in notify
    res = registry.get("calendar.alarm_manager").get_next_notif(cr, uid, context=context)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/addons/calendar/calendar.py", line 496, in get_next_notif
    for one_date in self.pool.get("calendar.event").get_recurrent_date_by_event(cr, uid, curEvent, context=context):
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/addons/calendar/calendar.py", line 712, in get_recurrent_date_by_event
    rset1 = rrule.rrulestr(str(event.rrule), dtstart=startdate, forceset=True)
  File "/usr/lib/python2.7/dist-packages/dateutil/rrule.py", line 1093, in __call__
    return self._parse_rfc(s, **kwargs)
  File "/usr/lib/python2.7/dist-packages/dateutil/rrule.py", line 994, in _parse_rfc
    raise ValueError, "empty string"
ValueError: empty string

**Comment by xmo-odoo** [comment] 2015-04-29 08:32
Dupe of #5313

**Closed by xmo-odoo** 2015-04-29 08:32 UTC
