### ISSUE TITLE
ValueError: Field `employee_id` does not exist -> View `res.users.form`

### ISSUE THREAD

**Issue by meysam81** [odoo/odoo#32480] opened 2019-04-08 06:31 UTC
Impacted versions:
12

Steps to reproduce:
when trying to add a new user

Current behavior:
an exception is raised saying: ```ValueError: Field `employee_id` does not exist```

Expected behavior:
everything should be good I guess

The full error is as follows:
```
 

Error:

Odoo Server Error

 

Traceback (most recent call last):

  File "/opt/odoo12/odoo/odoo/http.py", line 653, in _handle_exception

    return super(JsonRequest, self)._handle_exception(exception)

  File "/opt/odoo12/odoo/odoo/http.py", line 312, in _handle_exception

    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])

  File "/opt/odoo12/odoo/odoo/tools/pycompat.py", line 87, in reraise

    raise value

  File "/opt/odoo12/odoo/odoo/http.py", line 695, in dispatch

    result = self._call_function(**self.params)

  File "/opt/odoo12/odoo/odoo/http.py", line 344, in _call_function

    return checked_call(self.db, *args, **kwargs)

  File "/opt/odoo12/odoo/odoo/service/model.py", line 97, in wrapper

    return f(dbname, *args, **kwargs)

  File "/opt/odoo12/odoo/odoo/http.py", line 337, in checked_call

    result = self.endpoint(*a, **kw)

  File "/opt/odoo12/odoo/odoo/http.py", line 938, in __call__

    return self.method(*args, **kw)

  File "/opt/odoo12/odoo/odoo/http.py", line 517, in response_wrap

    response = f(*args, **kw)

  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 962, in call_kw

    return self._call_kw(model, method, args, kwargs)

  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 954, in _call_kw

    return call_kw(request.env[model], method, args, kwargs)

  File "/opt/odoo12/odoo/odoo/api.py", line 745, in call_kw

    return _call_kw_model(method, model, args, kwargs)

  File "/opt/odoo12/odoo/odoo/api.py", line 718, in _call_kw_model

    result = method(recs, *args, **kwargs)

  File "/opt/odoo12/odoo/odoo/models.py", line 1368, in load_views

    for [v_id, v_type] in views

  File "/opt/odoo12/odoo/odoo/models.py", line 1368, in <dictcomp>

    for [v_id, v_type] in views

  File "/opt/odoo12/odoo/odoo/models.py", line 1454, in fields_view_get

    xarch, xfields = View.postprocess_and_fields(self._name, etree.fromstring(result['arch']), view_id)

  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 1092, in postprocess_and_fields

    self.raise_view_error(message, view_id)

  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 545, in raise_view_error

    raise ValueError(message)

ValueError: Field `employee_id` does not exist

 

Error context:

View `res.users.form`

[view_id: 144, xml_id: base.view_users_form, model: res.users, parent_id: n/a]

-----------------------------------------------------------------------------------------------------------------------------

SOME_CORPORATION                                                                                 

SOME_NAME

VP Marketing & CRM

Address:  SOME_ADDRESS

TEL: SOME_TEL

Website: SOME_WEBSITE                                                                                    

E-mail: SOME_EMAIL                                                                            

 

cid:image001.jpg@01D23A8D.843BB170

 

Privileged/Confidential Information may be contained in this message. If you are not the addressee indicated in this message (or responsible for delivery of the message to such person), you may not copy or deliver this message to anyone. In such case, you should destroy this message and kindly notify the sender by reply email. Please advise immediately if you or your employer do not consent to Internet email for messages of this kind. Opinions, conclusions and other information in this message that do not relate to the official business of my firm shall be understood as neither given nor endorsed by it.

 ```

**Comment by pedrobaeza** [comment] 2019-04-08 07:30
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by meysam81** [comment] 2019-04-08 08:26
@pedrobaeza 
I tried `runbot` but I don't think I can find the same path there.
The problem was when trying to access users management in CRM.

**Comment by pedrobaeza** [comment] 2019-04-08 08:28
I don't get your problem. Is that custom code?

**Comment by meysam81** [comment] 2019-04-08 08:33
I don't think so, I just met your product this morning (amazing, right?), and the admin guy that was using it had a headache trying to find what the problem was. I'm the only person with python knowledge in the company so I tried to dig in to the code before I found that there are thousands of commits.
So I realized that it's a big product. He told me that there are no custom code, only using what was available on Github.

**Comment by pedrobaeza** [comment] 2019-04-08 08:34
Well, it seems a bad deployment or outdated code, as if you try on runbot, the problem is not there.

**Comment by meysam81** [comment] 2019-04-08 08:36
is there a CRM available on runbot? I couldn't find one.

**Comment by Yenthe666** [comment] 2019-04-08 08:37
Indeed. @meysam81 if you cannot reproduce it on a runbot it has to be something locally. Check with the admin guy if he is absolutely sure there is no custom development and if there where no changes done.
The CRM module is available by default, out of the box, on any runbot instance.
P.S: I hope you like Odoo.

**Comment by meysam81** [comment] 2019-04-08 11:54
Ok guys, I'm gonna post some photo regarding the issue

**Comment by meysam81** [comment] 2019-04-08 11:54
And there's another issue as well, right when I open the site, there's this nasty error about some CSS not loading:
![Screenshot from 2019-04-08 16-21-42](https://user-images.githubusercontent.com/30233243/55722172-bbec8400-5a1a-11e9-8cca-fbc6a42b419c.png)

**Comment by pedrobaeza** [comment] 2019-04-08 11:58
@alexey-pelykh is this the same error you are receiving?

**Comment by meysam81** [comment] 2019-04-08 11:58
from the main screen, using the top left corner, I click `Settings` and then here's the screen I confront
![Screenshot from 2019-04-08 16-26-52](https://user-images.githubusercontent.com/30233243/55722366-50ef7d00-5a1b-11e9-8b29-94bfec29b5d8.png)

**Comment by meysam81** [comment] 2019-04-08 11:58
And this is the issue I have opened here
![Screenshot from 2019-04-08 16-28-33](https://user-images.githubusercontent.com/30233243/55722390-64024d00-5a1b-11e9-86fd-f4e39987b59a.png)

**Comment by alexey-pelykh** [comment] 2019-04-08 12:02
@pedrobaeza nope, I get 
![image](https://user-images.githubusercontent.com/345102/55722541-43cc9100-5a0f-11e9-9049-f094629b0549.png)

**Comment by pedrobaeza** [comment] 2019-04-08 12:03
Thanks, @alexey-pelykh 

@meysam81 can you please try in runbot to reproduce the problem?

**Comment by meysam81** [comment] 2019-04-08 12:07
Why can't I see a `Settings` in here:

![Screenshot from 2019-04-08 16-36-53](https://user-images.githubusercontent.com/30233243/55722815-906a9900-5a1c-11e9-8ddd-c6eae7a32337.png)

**Comment by pedrobaeza** [comment] 2019-04-08 12:11
Login with admin/admin

**Comment by meysam81** [comment] 2019-04-08 14:36
well I tested the runbot and it doesn't seem to have our problem, so it may as well be one of your guesses in the beginning of the conversation

**Comment by meysam81** [comment] 2019-04-08 14:37
I have a guess of my own though, maybe it is fixed in the latest commits (as the runbot main page only shows the last 4)

**Comment by Yenthe666** [comment] 2019-05-23 13:33
Hi,

As you've said yourself it is not reproducable on runbot I'm closing this report. Try to update your local instance to solve it there too.

**Closed by Yenthe666** 2019-05-23 13:33 UTC
Labels: Need information

**Comment by abhishek-wenlighning** [comment] 2020-07-21 20:43
.This usually happens if you write function name same as field name in same file. atleast in my case this was the issue.
