### ISSUE TITLE
Problem nested transaction isolation 

### ISSUE THREAD

**Issue by MohamedAmineOuali** [odoo/odoo#65036] opened 2021-01-26 07:35 UTC
Impacted versions:
I  tested the problem on odoo 14 but I believe it is also a problem with odoo 13 (not sure). Things are working fine with odoo 12
Steps to reproduce:
The problem is with nested transactions. When doing a commit in a nested transaction the changes in the first one are also committed

```
with api.Environment.manage():
    with registry(self.env.cr.dbname).cursor() as new_cr1:
        first = self.with_env(self.env(cr=new_cr1))
        # doing some changes without commit   first.write({})  **(1)**
        with api.Environment.manage():
            with registry(self.env.cr.dbname).cursor() as new_cr2:
                new_env = api.Environment(new_cr2, self.env.uid, self.env.context)
                second = self.with_env(new_env)
                # do some changes using second  second.write({})   **(2)**
                new_env.cr.commit()  # this commit will will apply both  (1) and (2)
        self._cr.commit()
```

Current behavior:
To my understanding the caches used to keep track of the changes is the same for both environment. I notice that env.all.towrite  contains both changes.  Several problem can occur because of this. Sometimes when doing a select and then update on the same record  in **(1)**  the second commit will hang indefinitely because the select didn't release the lock on the database and the second transaction is trying to commit the update query which doesn't belong to the second transaction.
the first transaction status is idle transaction and the second one is active waiting for the lock.  (PostgreSQL   `select * from pg_stat_activity`.

This may lead to the exhaustion of database connections 

Expected behavior:
2 separate isolated transaction. 

The solution that I have found is to always commit changes before opening a nested transaction.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment] 2021-01-26 07:40
You are not opening new transactions, but new environments, which is not the same.

Anyway, this is a development question, and not a bug, so closing. For further ones, go to forums.

**Closed by pedrobaeza** 2021-01-26 07:40 UTC

**Comment by MohamedAmineOuali** [comment] 2021-01-26 16:37
But I am also creating a new cursor.  I checked some odoo packages and I found that this code is used to open new transaction when creating a thread. 
```
    def _procure_calculation_orderpoint(self):
        with api.Environment.manage():
            # As this function is in a new thread, I need to open a new cursor, because the old one may be closed
            new_cr = self.pool.cursor()
            self = self.with_env(self.env(cr=new_cr))
            scheduler_cron = self.sudo().env.ref('stock.ir_cron_scheduler_action')
            # Avoid to run the scheduler multiple times in the same time
            try:
                with tools.mute_logger('odoo.sql_db'):
                    self._cr.execute("SELECT id FROM ir_cron WHERE id = %s FOR UPDATE NOWAIT", (scheduler_cron.id,))
            except Exception:
                _logger.info('Attempt to run procurement scheduler aborted, as already running')
                self._cr.rollback()
                self._cr.close()
                return {}

            for company in self.env.user.company_ids:
                cids = (self.env.user.company_id | self.env.user.company_ids).ids
                self.env['procurement.group'].with_context(allowed_company_ids=cids).run_scheduler(
                    use_new_cursor=self._cr.dbname,
                    company_id=company.id)
            new_cr.close()
            return {}

    def procure_calculation(self):
        threaded_calculation = threading.Thread(target=self._procure_calculation_orderpoint, args=())
        threaded_calculation.start()
        return {'type': 'ir.actions.act_window_close'}
```

You can find this code in the stock addons

**Comment by pedrobaeza** [comment] 2021-01-26 17:26
If you have UI steps to reproduce the problem in standard Odoo, please expose them, and then it can be considered for its bugfixing.

**Comment by MohamedAmineOuali** [comment] 2021-01-26 21:21
This a code that you can test easy by putting it in a function of a model that have a name field (there are multiple model that have name field in odoo). As for the model bus.bus you can use any model that you want.

```
        with api.Environment.manage():
            with registry(self.env.cr.dbname).cursor() as new_cr1:
                new_env1 = api.Environment(new_cr1, self.env.uid, self.env.context)
                new_env1[self._name].search([('id', '=', self.id)]).write({"name": "new name"})
                with api.Environment.manage():
                    with registry(self.env.cr.dbname).cursor() as new_cr2:
                        new_env2 = api.Environment(new_cr2, self.env.uid, self.env.context)
                        new_env2['bus.bus'].sendone('web_progress', "test")
                        new_env2.cr.commit()
                new_env1.cr.rollback()
```

1) I am creating a new cursor(transaction) I am using this transaction to change the name of the current object.
2) I a creating a second transaction to create a record in the "bus.bus" model
3) I am committing the second transaction 
4) I have canceled the first transaction where I changed the name of the current object

The name is changed in the first transaction which was **canceled** (rollback) => However, the name changed.

I believe that the problem is related to `env.all.towrite`

**Comment by ws-mps** [comment] 2024-08-06 13:18
This was a bug indeed.
In Odoo version 13 `towrite` was introduced, which is shared between all the envs (`all`), and when committing to DB using a new cursor it just commits everything stored in `towrite`.
The issue is the cursor is completely ignored when dealing with `towrite`, which should have been defined like: `towrite[cursor][model][record]` instead of just  `towrite[model][record]`.
This was later fixed in version 15 when `Transaction` object was introduced.
