### ISSUE TITLE
[11.0] Sale order totals not updating

### ISSUE THREAD

**Issue by joezsweet** [odoo/odoo#29620] opened 2018-12-18 16:46 UTC
Impacted versions: 11.0

Steps to reproduce:
1. Sale Order
2. Add an order line for a product and save the order
3. Edit the order either qty or price

Current behavior:
Totals are not updated

Expected behavior:

Totals should be updated

Video/Screenshot link (optional):

http://recordit.co/P8VXVwkeTh

could it be after merge: https://github.com/odoo/odoo/commit/8fe7229e1984811f3456dbf502cb03fba879e180 ?

**Comment by sswapnesh** [comment] 2018-12-19 16:18
Maybe duplicate of https://github.com/odoo/odoo/issues/27707

**Comment by sswapnesh** [comment] 2018-12-19 16:30
Sorry for Bad reference. (Bad reference of Issue, will search again and add correct one)

**Comment by pedrobaeza** [comment] 2018-12-19 16:30
Well, that's the last checkout you have done, but there should be more commits between that and the previous checkout, isn't it? This was working previously?

**Comment by sswapnesh** [comment] 2018-12-19 16:31
This commits seems related to #27707

**Comment by pedrobaeza** [comment] 2018-12-19 16:32
@sswapnesh please check my previous comment

**Comment by joezsweet** [comment] 2018-12-19 16:40
Could be, 

> Well, that's the last checkout you have done, but there should be more commits between that and the previous checkout, isn't it? This was working previously?

Yes, was working, at least up to this https://github.com/odoo/odoo/commit/9d2d539a1631bc15516c75a100d8e0f305df2cd6

**Comment by sswapnesh** [comment] 2018-12-19 18:08
@joezsweet I have tried to reproduce same on Runbot v11 (Community + Enterprise) but seems working fine.
Total is updated even after the warning regarding `Not enough inventory!`

**Comment by joezsweet** [comment] 2018-12-20 08:56
@sswapnesh that's weird. I cannot find out what's the issue as no custom modules are installed. Did u test also on v. 11.0 CE only?

**Comment by sswapnesh** [comment] 2018-12-20 14:45
@joezsweet 

>  Did u test also on v. 11.0 CE only?

11 CE + EE

**Comment by Yenthe666** [comment] 2019-01-28 12:49
Hi,

I've just tested this again on the latest 11.0 (community) and was also not able to reproduce this.
Please update your local instance and try again. I'm closing this issue as we have not been able to reproduce it with multiple people.

Regards,
Yenthe666

**Closed by Yenthe666** 2019-01-28 12:49 UTC
Labels: 11.0, Need information, Services
