### ISSUE TITLE
BUG in sales pricelist

### ISSUE THREAD

**Issue by mschou** [odoo/odoo#11901] opened 2016-05-03 07:41 UTC
**Impacted versions:** 9.0, 9.0 enterprise

Module "Prices Visible Discounts", installed

**Steps to reproduce:** Create product with sales price = 300, Create sales pricelist "Price" and set product price to 250
Create new sales pricelist "Price10" compute price, with 10% discount based on other pricelist, set Discount Policy = Show discount in the sale order. 
Create partner and set salespricelist to "Price10"

**Current behavior:** When creating salesline the price before discount are not from sales pricelist but from Product sales price

**Expected behavioror:** Correct behavioror must be, salesprice from partner sales pricelist

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment] 2016-06-06 06:40
@nim-odoo could you have a look at this one please?

**Comment by pedrobaeza** [comment] 2018-04-24 07:57
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-04-24 07:57 UTC
Labels: 9.0, Services
