### ISSUE TITLE
active=False的产品点击销售和追溯提示错误

### ISSUE THREAD

**Issue by itrojan** [odoo/odoo#15480] opened 2017-02-14 01:14 UTC
File "/Users/lanyun/python/odoo10/addons/stock/models/product.py", line 531, in action_view_stock_moves
    action['context'] = {'default_product_id': products.ids[0]}

**Comment by Icallhimtest** [comment] 2017-02-14 16:39
How on earth are we supposed to know what the problem is from such a message ?

`active = False` means something is archived, maybe you've archived something that you shouldn't have ?

**Comment by Yenthe666** [comment] 2017-02-15 10:32
Hi @itrojan,

I'm closing this report as it has no context, information or anything to reproduce this.
Please create a new issue in which you give more information and a testing scenario.
We really have no clue what you're talking about as there is not even a version in your topic.

Regards,
Yenthe

**Closed by Yenthe666** 2017-02-15 10:32 UTC
