### ISSUE TITLE
QWeb Report is very slow when the report has 1000+ rows table

### ISSUE THREAD

**Issue by natthanank** [odoo/odoo#30286] opened 2019-01-17 03:20 UTC
Impacted versions: Odoo 10

Steps to reproduce: I generate report with 1000+ rows data

Current behavior: It's very slow (3-5 minutes)

Video/Screenshot link (optional): I also tried to add system parameters report.url like this
![report_url](https://user-images.githubusercontent.com/16128880/51293411-6dde6a80-1a41-11e9-8294-4b86a804c07c.PNG)

**Comment by nhomar** [comment] 2019-01-17 07:03
Which report? it is not a generic feature to solve each report has its own performance behavior.

IOH, Internet bandwidth? did you remove the internet from your test? (downloading the report is a problem also).

Once you have this information we can check who can be in charge...

BTW depending on the report this can be considered a bug or not.

**Comment by natthanank** [comment] 2019-01-17 09:39
I generate report from data that I query from my stored procedure

**Comment by pedrobaeza** [comment] 2019-01-17 14:51
Then the problem is in your report/procedure. Closing by this reason.

If you prove to happen this on a standard report, then we'll reopen to analyze.

**Closed by pedrobaeza** 2019-01-17 14:51 UTC
Labels: Need information

**Comment by natthanank** [comment] 2019-01-18 01:57
this is my render_html function, I logged start and end time
`
        @api.model
        def render_html(self, docids, data=None):
        _logger.info('start')
        _logger.info(datetime.now().time())
        self.model = self.env.context.get('active_model')
        docs = self.env[self.model].browse(self.env.context.get('active_id'))
        stock_moves = []
        
        if (parse(docs['date_from']) > parse(docs['date_to'])):
            raise UserError('Please select valid date!!')

        date_from = ''.join('{0}'.format(d) for d in docs['date_from'].split(' ')[0].split('-'))
        date_to = ''.join('{0}'.format(d) for d in docs['date_to'].split(' ')[0].split('-'))
        part_no = None
        if (type(docs['part_no']) != bool):
            part_no = docs['part_no'].strip()
            if (len(part_no) == 0):
                part_no = None

        self.env.cr.callproc("public.odoo_stock_move_report_acc", [part_no, date_from, date_to,])
        result = self.env.cr.fetchall()
        for res in result:
            stock_moves.append({
                "docDate": res[4],
                "doDate": res[19],
                "pn": res[6],
                "description": res[7]
            })

        docargs = {
                    'doc_ids': self.ids,
                    'doc_model': self.model,
                    'docs': docs,
                    'stock_moves': stock_moves
                }
        _logger.info('end')
        _logger.info(datetime.now().time())
        return self.env['report'].render('stock_move_acc_report.report_bydate', docargs)`

and this is log
![git_result](https://user-images.githubusercontent.com/16128880/51360639-0981e080-1aff-11e9-8759-21221ebe247a.png)

just 5 seconds
