### ISSUE TITLE
Pictures in Inventory are broken, when you use translation

### ISSUE THREAD

**Issue by sergeiruzkiicode** [odoo/odoo#22802] opened 2018-02-05 11:45 UTC
Impacted versions:
11.0CE and E
Steps to reproduce:
Add russian(as example) translation. Go to inventory with test data
English:
![image](https://user-images.githubusercontent.com/34267807/35802890-e3b9af3c-0a82-11e8-8035-d8383dad6a13.png)
Go to My Prefrences, change to Russian - all icons are broken
![image](https://user-images.githubusercontent.com/34267807/35802920-013c549c-0a83-11e8-89de-858a1f334f86.png)
Go to some product - all is correct
![image](https://user-images.githubusercontent.com/34267807/35802943-18b7d7cc-0a83-11e8-8574-700539d2b484.png)

You can check it on http://299885-11-0-3d1821.runbot14.odoo.com/web?#view_type=kanban&model=product.template&action=567

**Comment by sswapnesh** [comment] 2018-02-05 14:04
Duplicate of #22519
Cc: @Yenthe666

**Comment by Yenthe666** [comment] 2018-02-05 14:32
Yeah agreed, another view but the same isuse. @sergeiruzkiicode please keep a look out for https://github.com/odoo/odoo/issues/22519

**Closed by Yenthe666** 2018-02-05 14:32 UTC
Labels: 11.0, Internationalization
