### ISSUE TITLE
Image not changing  in Form view  untill page reload 

### ISSUE THREAD

**Issue by prakashkumar163** [odoo/odoo#20226] opened 2017-10-17 06:13 UTC
Impacted versions:11

Steps to reproduce: 
Create a res.partner records and assign the image and save.
Now again try to change it will not change.
Now refresh the page, change will reflect.

Current behavior:
 Update image not reflects till page, not reload.

Expected behavior:

Image change should be reflected.

**Comment by Yenthe666** [comment] 2017-10-17 09:58
Pretty much a duplicate of https://github.com/odoo/odoo/issues/20198 and https://github.com/odoo/odoo/issues/20046 - so closing this one in favour of the other two.

**Closed by Yenthe666** 2017-10-17 09:58 UTC
