### ISSUE TITLE
Sale pricelist for each individual partner with property_product_pricelist field

### ISSUE THREAD

**Issue by daramousk** [odoo/odoo#12880] opened 2016-07-22 12:55 UTC
I have a question for this functionality. 

Example:

I set a different price-list for customerA using the field property_product_pricelist. When I log in as that partner I can see that the prices of the products have been correctly overridden by the pricelist. But my issue is that the currency set on the pricelist of a specific user does not get applied.

Shouldn't in the case I have defined a pricelist for that user, that user see the prices on the website with their correct currency?

**Comment by mart-e** [comment] 2016-07-25 11:40
Hello,

Which version of Odoo are you using?
Could you give the exact steps when you say "the currency set on the pricelist of a specific user does not get applied"? Not applied on what?

**Comment by Gorkygd** [comment] 2016-07-28 22:16
Version of Odoo: 9.0c
Commit: e349692ede0d08f82e1a1847cb25bec0dc9e4b13 (Sun Jul 3 00:32:09 2016 +0200)
How to replicate:

On a new database install website_sale.
Activate multi-currencies for the admin user and the customer user.
Create a product with a price 10 euros and publish it to the website.
Go to Sale -> Configuration -> Settings and activate Advanced pricing based on formula
Go to Settings -> Users and create a user giving him only portal access.
Go to Customers, find the partner that is linked to our specific user and on Sales and Purchases tab create and edit a new Sale Pricelist. Give your new pricelist a name, USD currency and add the product on the bottom with a fixed price of say 50 usd.
Create a website pricelist that links to the above pricelist.

Now open the website shop with the administrator. You should see the test product with the price of 10 euros which is correct.

On an incognito window log in as your test customer. Go to your shop. You will see that the price of the product has changed according to the pricelist assigned to the user but the currency does not change to the one set on the pricelist. Rather it stays the default.

Shouldn't the currency change as well?

**Comment by mart-e** [comment] 2016-07-29 09:38
@JKE-be opinion? It seems indeed there is something a bit strange with the currency on the ecommerce for fixed price pricelist (not for percentage)
![screenshot from 2016-07-29 11-35-05](https://cloud.githubusercontent.com/assets/564822/17244213/00dec736-5581-11e6-8da3-a20f52218667.png)
![screenshot from 2016-07-29 11-37-57](https://cloud.githubusercontent.com/assets/564822/17244216/01ef0820-5581-11e6-8a95-8236247b5562.png)

**Comment by Gorkygd** [comment] 2016-08-04 12:48
Hello there,

Is this issue confirmed or dismissed?

Thanks

**Comment by Yenthe666** [comment] 2018-02-12 10:33
@JKE-be any update here as you self assigned?

**Comment by JKE-be** [comment] 2018-02-12 10:54
was a long time ago ;) 
Thanks, I retag website

**Comment by JKE-be** [comment] 2018-02-14 10:43
@mart-e @daramousk 

I cannot reproduce the issue, probably fixed meanwhile.
Can you check and reopen this issue if it is not the case.

Thanks

**Closed by JKE-be** 2018-02-14 10:43 UTC
Labels: Website
