### ISSUE TITLE
[14] Outlook CRM extension, after click 'Allow' redirect to https://mydomain/plugins/outlook/taskpane.html which does not exist in server

### ISSUE THREAD

**Issue by WatchingOn9** [odoo/odoo#75813] opened 2021-09-01 04:44 UTC
Impacted versions: Odoo community 14.0 latest 20210831

Steps to reproduce: 

1. Fresh install Odoo Community 14 on server (my case windows) 
2. Install CRM App
3. Enable Outlook CRM extension in setting
4. Login into outlook mailbox, install add-in and click on the icon
5. Type in my odoo domain on right pane, click login button
![image](https://user-images.githubusercontent.com/9769260/131612014-79775139-05ea-47b5-a8eb-70dec1918391.png)

--------------

Current behavior:  

After login, click 'Allow' will redirect to https://odoo.mydomain.com/plugins/outlook/taskpane.html which does not exist in my server, end up it return a 404 page.
Below is the request header:
![image](https://user-images.githubusercontent.com/9769260/131613441-9544572f-82ae-4917-add5-d2db1821c11b.png)

--------------------

Expected behavior:  

Had tried in runbot, it can works.
After click allow will redirect to http://download.odoo.com/plugins/outlook/taskpane.html
Below is the request header i've tried with runbot.
![image](https://user-images.githubusercontent.com/9769260/131613229-0b83b254-3c82-40ce-bbd8-d6a27ed597c1.png)

--------------------

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment] 2021-09-01 06:12
As not reproducible in runbot, then it should be something of your deployment or outdated code. Please check both, but we have to close this while not able to reproduce it on an official installation.

**Closed by pedrobaeza** 2021-09-01 06:12 UTC
