### ISSUE TITLE
[13.0] base: many2one_reference field is not visible on form view

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#38009] opened 2019-10-06 05:59 UTC
Impacted versions: 13.0

Steps to reproduce:  Open Attachment form view

Current behavior:  Resource ID is not Visible on Form view (While correct value is there on tree view)
![Screenshot (11)](https://user-images.githubusercontent.com/16624719/66264959-fe591700-e82b-11e9-8fea-6089186c0bd6.png)
![Screenshot (12)](https://user-images.githubusercontent.com/16624719/66264961-12047d80-e82c-11e9-9f24-2cbd95385ea9.png)

Expected behavior: It should be there

Video/Screenshot link (optional):
![Peek 2019-10-06 11-26](https://user-images.githubusercontent.com/16624719/66264981-63ad0800-e82c-11e9-970e-f0d79bb3edc5.gif)

Cc: @rco-odoo

**Comment by seb-odoo** [comment] 2019-10-07 09:31
It should be displayed as `int` for now, to keep the same behavior as before (`res_id` was an `int`). A proper widget might be implemented for future versions.

This https://github.com/odoo/odoo/commit/d0c852f50e71bc4c9c2a08230f515fec6909b725 fixed in some cases, but, apparently, not all.

We should probably have tests for that type of field too, to notice that kind of issues.

cc @ged-odoo

**Comment by katyukha** [comment] 2019-10-30 12:06
Hi, we have `generic_m2o` ([link](https://github.com/crnd-inc/generic-addons/tree/13.0/generic_m2o)) widget implementation, that allows to display and edit `many2one_reference` fields. I can start Pull Request to create implementation of `many2one_reference` widget. But, could it be merged in 13? Or it could be merged only in master?

**Comment by seb-odoo** [comment] 2019-10-31 09:51
Only master as it would be a new feature.

**Comment by Yenthe666** [comment] 2019-11-13 13:02
@seb-odoo  any update?

**Comment by seb-odoo** [comment] 2019-11-14 09:49
No idea, a ticket should probably be open if the issue is still present.

**Comment by sswapnesh** [comment] 2019-11-19 18:04
Issue still exists.

OPW 2127010

**Comment by sswapnesh** [comment] 2019-12-03 16:05
2 weeks and still no update on OPW

**Comment by Yenthe666** [comment] 2019-12-03 16:17
Hmm that's pretty long :/ I saw the issue counter going up very fast so I assume they're behind on tickets a bit right now.

**Comment by seb-odoo** [comment] 2019-12-03 20:25
There seem to be quite a few tickets open at the moment indeed... If it doesn't move in the next days I guess I'll see what I can do for this.

**Comment by Yenthe666** [comment] 2019-12-03 21:44
@seb-odoo wins the awesome Odoo employee badge of this week! And sorry for my part in those tickets, I made you a good 10 the last few days. 😅

**Closed** 2019-12-10 16:11 UTC
Labels: 13.0, Confirmed, Framework, OE
