### ISSUE TITLE
User-defined defaults not set if a company is specified

### ISSUE THREAD

**Issue by ctringham** [odoo/odoo#41679] opened 2019-12-11 02:46 UTC
Impacted versions: **13EE**

Steps to reproduce: **Create a user-defined default and specify a company**

Current behavior: **Default is not applied**

Expected behavior: **Default should be applied**

Workaround: **Set company to blank and default is applied**

Note: **if a user-default is setup through debug mode, the company is set, but it can be removed through the Settings menu**

**Comment by pedrobaeza** [comment] 2019-12-11 08:27
That's because the company is not set as well as default, but derived from other business logic, so it can't be deduced in the context of the default.

Closing as no issue, but working way.

**Comment by ctringham** [comment] 2019-12-11 08:58
Don't agree!  Here are some screenshots to explain the problem:

1. In debug mode, set default for Product Type

![Set Default 1](https://user-images.githubusercontent.com/38899643/70606246-04f27900-1c37-11ea-95ba-0ce128f6b157.jpg)

2. Does NOT set the Product type when selecting the Product Category

![Set Default 2](https://user-images.githubusercontent.com/38899643/70606333-33705400-1c37-11ea-97e7-db054d4feab2.jpg)

3. Confirmed that system has setup default with company specified

![Set Default 3](https://user-images.githubusercontent.com/38899643/70606367-45ea8d80-1c37-11ea-98e8-d5e6af255d60.jpg)

Can the company be set as blank?

**Comment by pedrobaeza** [comment] 2019-12-11 09:07
As a test, try to set the company default as well and see if it works.

**Comment by ctringham** [comment] 2019-12-11 09:19
I tried to default the company to "My Company (Chicago)" but the same issue.  It only works if the company is set to blank on ir.default (and as far as I can see, that can only be done manually, which is not ideal).

**Comment by pedrobaeza** [comment] 2019-12-11 09:21
OK, let's reopen this as it can be a side effect of the multi-company refactoring.

@Feyensv maybe you can help here.

**Comment by Feyensv** [comment] 2019-12-11 11:11
I just tried the feature (without changing the company_id field), and everything worked fine.
When I changed the product category, the type was updated.

Could you give us either a video of the problematic behavior (and/or a link to a runbot where the problem is happening and how to reproduce it ?).

**Comment by ctringham** [comment] 2019-12-12 01:48
I agree that it does work sometimes, but I have been able to recreate in [this runbot](http://738973-saas-13-1-a1797b.runbot20.odoo.com/web): 

![User defined defaults](https://user-images.githubusercontent.com/38899643/70675317-d1116500-1cc3-11ea-9751-722b68f8b1cc.JPG)

[Video](https://drive.google.com/file/d/151wfDFZ0RbgeQ64ppMg0GrZSciU0mJ60/view?usp=sharing)

**Comment by pedrobaeza** [comment] 2019-12-12 08:50
Video doesn't help too much. Please describe the steps to reproduce the problem in runbot.

**Comment by Feyensv** [comment] 2019-12-12 10:16
Bug found and understood. I'm on it ;).

**Closed** 2019-12-19 08:58 UTC
Labels: 13.0, Confirmed, Framework
