### ISSUE TITLE
Record does not exist or has been deleted.

### ISSUE THREAD

**Issue by aakashct** [odoo/odoo#48963] opened 2020-04-03 11:25 UTC
Impacted versions:
Odoo version 13

Steps to reproduce:
Contacts - Click on opportunity - Click on meeting.

Current behavior:
Record does not exist or has been deleted.(Tested in runbot odoo version 13)
Expected behavior:
It should open the calendar view.
Video/Screenshot link (optional):

![meetiong-crm](https://user-images.githubusercontent.com/44608752/78355741-d7598300-75cb-11ea-85ef-d62e5b8ec2e9.png)

**Comment by pedrobaeza** [comment] 2020-04-03 11:28
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by aakashct** [comment] 2020-04-03 11:55
Hi, thanks for the reply, the above problem was reproduced in runbot. i have attached the video to reproduce the same in runbot.

**Comment by pedrobaeza** [comment] 2020-04-03 12:16
I see. It's a problem with active_id and smart-buttons reusing them.

@Yenthe666 do you remember the issue where this was debated?

**Comment by Yenthe666** [comment] 2020-04-03 14:42
@pedrobaeza are you talking about this https://github.com/odoo/odoo/issues/47680 one? I think we had one where @sswapnesh was involved too actually.

**Comment by pedrobaeza** [comment] 2020-04-03 14:45
No, not that one, sorry. It was one talking about `active_id` not being updated when drilling through forms.

**Comment by sswapnesh** [comment] 2020-04-03 14:47
@Yenthe666  Yes Here it is https://github.com/odoo/odoo/issues/42450
I think @pedrobaeza  is talking about https://github.com/odoo/odoo/issues/39070

**Comment by pedrobaeza** [comment] 2020-04-03 14:51
Indeed, #39070 is

**Comment by sswapnesh** [comment] 2020-04-03 14:54
@pedrobaeza  Its because its taking `active_id` of res.partner instaed of crm.lead

**Comment by pedrobaeza** [comment] 2020-04-03 14:55
Exactly.

**Comment by sswapnesh** [comment] 2020-04-03 15:07
@pedrobaeza  Correct fix would be replacing `active_id` by `active_ids[0]` in the calendar module itself 

https://github.com/odoo/odoo/blob/c53f1c6a58b4c8c9e9b3c87f27281c9bfd65a0e1/addons/calendar/models/calendar.py#L575-L576

But I doubt if PR will be accepted of not. Can I give a try?

**Comment by pedrobaeza** [comment] 2020-04-03 16:07
I think the problem is the same. Both `active_id` or `active_ids` are not refreshed on each click-through.

**Comment by sswapnesh** [comment] 2020-04-03 17:09
Yes, It was not related to that

Added Fix at #48992

**Comment by sswapnesh** [comment] 2020-07-15 15:14
Fixed in https://github.com/odoo/odoo/commit/b9abc757da3034209b083c4ba862edd3865f7637

**Comment by Yenthe666** [comment] 2020-07-15 15:40
Indeed it is! Thanks for keeping an eye out @sswapnesh 👍

**Closed by Yenthe666** 2020-07-15 15:40 UTC
Labels: 13.0, Marketing
