### ISSUE TITLE
Odoo Help Forum - TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by zbik2607** [odoo/odoo#6432] opened 2015-04-22 16:15 UTC
Today I get  this error when I call in browser, site https://www.odoo.com/forum/help-1  

ERR_TOO_MANY_REDIRECTS

https://www.odoo.com/pl_PL/pl_PL/pl_PL/pl_PL/pl_PL/pl_PL/pl_PL/pl_PL/pl_PL/pl_PL/pl_PL/pl_PL/pl_PL/pl_PL/pl_PL/pl_PL/pl_PL/pl_PL/pl_PL/pl_PL/forum/help-1

If I call for example: https://www.odoo.com/fr_FR/forum/help-1 ....       all is OK?!

PS. I logout to testing... but now ...login impossible!

**Comment by odony** [comment] 2015-04-22 18:24
As a temporary fix, could you try to manually go to https://www.odoo.com/en_US/forum/help-1 while we fix the underlying issue, and see if it solves your problem? Thanks!

**Comment by zbik2607** [comment] 2015-04-22 18:33
When en_US browse impossibe (probably becaouse en_US my other browser language)
When fr_FR  browse OK, but Login No.

**Comment by odony** [comment] 2015-04-22 23:08
It should be fixed now.. is it ok for you?

**Comment by zbik2607** [comment] 2015-04-23 05:50
Yes. Thanks

**Closed** 2015-04-23 07:39 UTC

**Comment by JayVora-SerpentCS** [comment] 2015-04-23 08:32
How was this fixed? Curious!

**Comment by odony** [comment] 2015-04-23 09:30
@JayVora-SerpentCS We're currently test-driving patch f7cf68da1d44a2efe14ff2efe33a45ec9712c9d0 on the forum, and the problem was caused by the previous version of the patch: 1d68d95fa4f3830005c94a7d87d286cfd5ac3c38

**Comment by JayVora-SerpentCS** [comment] 2015-04-23 11:50
Thanks!
