### ISSUE TITLE
[14.0] website: Error when update the theme after apply filter or crop image 

### ISSUE THREAD

**Issue by kig-odoo** [odoo/odoo#62933] opened 2020-12-06 12:19 UTC
Hello,

Error when updating the theme after an apply filter or crop the image element

Tested on runbot see: https://drive.google.com/file/d/1nLZKjjcchrZveucJf_mJ14qJ_BGUC1ea/view?usp=sharing

Thanks

**Comment by kig-odoo** [comment] 2020-12-06 12:27
ping @JKE-be

**Comment by kig-odoo** [comment] 2020-12-21 19:35
@rdeodoo can you please check this issue or forward it to the responsible guy for this one?
I've read your comment somewhere you guys not checking issues with the Web editor tag.
But I think this should be fixed asap right now we are not able to update the theme if previously we cropped any image or apply a filter on the image. 

Please see the video for more info: https://drive.google.com/file/d/1nLZKjjcchrZveucJf_mJ14qJ_BGUC1ea/view?usp=sharing

**Comment by rdeodoo** [comment] 2020-12-21 22:03
Hi, yes of course, I won't be able to pick this one up myself as I am on holiday since 2021 but maybe @qsm-odoo can have a look at this one and dispatch it to bugfix or our team if needed

**Comment by kig-odoo** [comment] 2020-12-22 00:18
Thanks for the quick response.

**Comment by qsm-odoo** [comment] 2020-12-22 10:04
@sdegueldre Could you have a look at this once you get the time?

**Comment by sdegueldre** [comment] 2020-12-28 07:23
I've been able to reproduce this and am working on a solution

**Comment by sdegueldre** [comment] 2021-01-04 07:14
fixed in #63940

**Closed by sdegueldre** 2021-01-04 07:14 UTC
Labels: 14.0, Confirmed, Web editor, Website
