### ISSUE TITLE
[9.0] Invoice lines won't update on currency change

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#14091] opened 2016-11-01 14:59 UTC
**Impacted versions:**
9.0, maybe others

**Steps to reproduce:**
- Create an invoice
- Add some invoice lines with producs and prices
- Change the currency 

**Current behavior:**
The prices of the products already added to the invoice wont update with the currency change. But if more products are added, they will be added with the new currency price, causing to have prices with one currency and prices with the other; which is an unwanted behaviour.  

**Expected behavior:**
Even if product were added to an invoice before changing the currency, **on change** of the currency all prices must be updated to the selected currency.

So if a user creates an invoice and then the client says "Oh, we wanted it in X currency"...when the user changes the currency, all will the prices will be updated with the X currency rate.

**Comment by csnauwaert** [comment] 2018-02-28 15:54
Hello,

Sorry for the delay, I could not reproduce your issue on the latest 9.0 version, it seems that this has been fixed, therefore I'm closing this issue.

Best regards

**Closed by csnauwaert** 2018-02-28 15:54 UTC
Labels: 9.0, Accounting
