### ISSUE TITLE
Impossible to change product description in SO

### ISSUE THREAD

**Issue by haconsult** [odoo/odoo#23066] opened 2018-02-14 16:08 UTC
Impacted versions:
v11

Steps to reproduce:

- create a new sales order
- in a sales order line, select a product
- description automatically fills according to the product
- extend the description, save

Current behavior:

- changes made to the description are not saved.

Interesting, though: 

- edit again
- don not extend the description, but shorten it, save
- changes are saved
- any following changes (deletions or extensions) are saved.

Also:
- beginning from the second row it is not possible to 'tab' the cursor all the way through the row to the "price per unit" field
- however, after you managed to save some changes (see above) it will be possible

**Comment by sswapnesh** [comment] 2018-02-14 16:22
Hello @haconsult  
Could you please update your source code and try again?
Duplicate of #22927 and #22797

**Comment by haconsult** [comment] 2018-02-14 17:26
Hi, 
I am running on 11.0-20180211 (Community Edition), I guess this is after the referenced issues? However, I am unable to upgrade before next week and will report back then.

**Comment by haconsult** [comment] 2018-02-20 21:46
Ok, is much improved now. However, if you got different UOMs set you can still not 'tab' your way to the UOM column and apply changes. 

Also (related or not) in any sales order: you get a very similar behavior but only if you try to sell more quantities of a product than you have in stock. This may easily happen if you want to sell a quantity smaller than 1 since 1 is the preset default. If necessary I will create a new issue for this.

regards.

**Comment by Yenthe666** [comment] 2019-05-11 14:56
Hi there,

I'm closing this issue as it should have been solved in the meanwhile and as we recieved no feedback.
Please update your local instance and try again. Don't hesitate to respond back if you can still reproduce it on the latest 11.0

Regards,
Yenthe

**Closed by Yenthe666** 2019-05-11 14:56 UTC
Labels: 11.0
