### ISSUE TITLE
Error when adding value to a foreign field

### ISSUE THREAD

**Issue by nmhung89** [odoo/odoo#8653] opened 2015-09-22 09:46 UTC
Hi,

I have two models here:
```
class Watch(osv.Model):
    _name = 'my_theme.watch'
    _columns = {
        'crystal': fields.char('Crystal'),
        'brand': fields.many2one('my_theme.brand', 'Brand', required=True)
}

class Brand(osv.Model):
    _name = 'my_theme.brand'
    _columns = {
        'name': fields.char('Name')
}
```
I have added a form view for Watch and added several records successfully. However, this issue happens sometimes but I don't know why. I think it's a odoo's bug but I am not sure. Could you guys please give me some tips, or help to fix it if it's a bug?

```
Traceback (most recent call last):
  File "/home/deploy/odoo/build/8.0/openerp/http.py", line 476, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/deploy/odoo/build/8.0/openerp/http.py", line 495, in dispatch
    result = self._call_function(**self.params)
  File "/home/deploy/odoo/build/8.0/openerp/http.py", line 311, in _call_function
    return checked_call(self.db, args, *kwargs)
  File "/home/deploy/odoo/build/8.0/openerp/service/model.py", line 113, in wrapper
    return f(dbname, args, *kwargs)
  File "/home/deploy/odoo/build/8.0/openerp/http.py", line 308, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/deploy/odoo/build/8.0/openerp/http.py", line 685, in call
    return self.method(*args, **kw)
  File "/home/deploy/odoo/build/8.0/openerp/http.py", line 360, in response_wrap
    response = f(*args, **kw)
  File "/home/deploy/odoo/build/8.0/addons/web/controllers/main.py", line 941, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/deploy/odoo/build/8.0/addons/web/controllers/main.py", line 933, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, args, *kwargs)
  File "/home/deploy/odoo/build/8.0/openerp/api.py", line 234, in wrapper
    return old_api(self, args, *kwargs)
  File "/home/deploy/odoo/build/8.0/openerp/api.py", line 329, in old_api
    result = method(recs, args, *kwargs)
  File "/home/deploy/staging/my_theme/models/models.py", line 142, in create
    brand_queryset = model.search([('id', '=', brand)], limit=1)[0]
  File "/home/deploy/odoo/build/8.0/openerp/api.py", line 232, in wrapper
    return new_api(self, args, *kwargs)
  File "/home/deploy/odoo/build/8.0/openerp/api.py", line 461, in new_api
    result = method(self._model, cr, uid, args, *kwargs)
  File "/home/deploy/odoo/build/8.0/openerp/models.py", line 1656, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/home/deploy/odoo/build/8.0/openerp/api.py", line 234, in wrapper
    return old_api(self, args, *kwargs)
  File "/home/deploy/odoo/build/8.0/openerp/models.py", line 4492, in _search
    cr.execute(query_str, where_clause_params)
  File "/home/deploy/odoo/build/8.0/openerp/sql_db.py", line 155, in wrapper
    return f(self, args, *kwargs)
  File "/home/deploy/odoo/build/8.0/openerp/sql_db.py", line 230, in execute
    res = self._obj.execute(query, params)
DataError: invalid input syntax for integer: "concord"
LINE 1: ...ld_theme_brand" WHERE "my_theme_brand".id = 'concord' ...
```

**Comment by mart-e** [comment] 2015-09-23 13:25
Hello,

Looks like the issue is in your custom code. 
```
 File "/home/deploy/staging/my_theme/models/models.py", line 142, in create
    brand_queryset = model.search([('id', '=', brand)], limit=1)[0]
```
I guess `brand` is a string and not an ID. You may check the [technical documentation](https://www.odoo.com/documentation/8.0/) for help on your development. (by the way, if you start a new module, you probably want to fully switch to the new API).

Closing as not an Odoo bug.

**Closed by mart-e** 2015-09-23 13:25 UTC

**Comment by nmhung89** [comment] 2015-09-23 13:43
Ah, I see. Thank you so much, you make my day :)
