### ISSUE TITLE
Exception: bus.Bus unavailable

### ISSUE THREAD

**Issue by robinhli** [odoo/odoo#26983] opened 2018-09-14 02:15 UTC
Impacted versions: 11.0

Steps to reproduce: start the odoo-bin with multi process mode with worker = 4

Current behavior: browser can't show page

Expected behavior: browser can show the page

Video/Screenshot link (optional):
2018-09-13 13:28:26,065 24383 INFO ? odoo: Odoo version 11.0
2018-09-13 13:28:26,066 24383 INFO ? odoo: Using configuration file at /home/wwwroot/odoo/odoo.conf
2018-09-13 13:28:26,066 24383 INFO ? odoo: addons paths: ['/home/odoo/.local/share/Odoo/addons/11.0', '/home/wwwroot/odoo/odoo/addons', '/home/wwwroot/odoo/addons']
2018-09-13 13:28:26,066 24383 INFO ? odoo: database: odoo@localhost:5432
2018-09-13 13:28:26,083 24383 INFO ? odoo.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
2018-09-13 13:28:26,087 24388 INFO ? odoo.service.server: Worker WorkerHTTP (24388) alive
2018-09-13 13:28:26,091 24390 INFO ? odoo.service.server: Worker WorkerHTTP (24390) alive
2018-09-13 13:28:26,092 24389 INFO ? odoo.service.server: Worker WorkerHTTP (24389) alive
2018-09-13 13:28:26,095 24391 INFO ? odoo.service.server: Worker WorkerHTTP (24391) alive
2018-09-13 13:28:26,098 24393 INFO ? odoo.service.server: Worker WorkerCron (24393) alive
2018-09-13 13:28:26,839 24392 INFO ? odoo: Odoo version 11.0
2018-09-13 13:28:26,840 24392 INFO ? odoo: Using configuration file at /home/wwwroot/odoo/odoo.conf
2018-09-13 13:28:26,840 24392 INFO ? odoo: addons paths: ['/home/odoo/.local/share/Odoo/addons/11.0', '/home/wwwroot/odoo/odoo/addons', '/home/wwwroot/odoo/addons']
2018-09-13 13:28:26,840 24392 INFO ? odoo: database: odoo@localhost:5432
2018-09-13 13:28:26,856 24392 INFO ? odoo.service.server: Evented Service (longpolling) running on 0.0.0.0:8072
2018-09-13 13:28:28,995 24389 INFO ? odoo.tools.misc: The path is ['/home/p3/p3/bin', '/usr/local/sbin', '/usr/local/bin', '/sbin', '/bin', '/usr/sbin', '/usr/bin', '/root/bin'].
2018-09-13 13:28:28,998 24389 INFO ? odoo.tools.misc: The path is ['/home/p3/p3/bin', '/usr/local/sbin', '/usr/local/bin', '/sbin', '/bin', '/usr/sbin', '/usr/bin', '/root/bin'].
2018-09-13 13:28:28,998 24389 INFO ? odoo.addons.base.ir.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
2018-09-13 13:28:29,830 24389 INFO ? odoo.addons.sms.wizard.send_sms: The `phonenumbers` Python module is not available. Phone number validation will be skipped. Try `pip3 install phonenumbers` to install it.
2018-09-13 13:28:30,063 24389 INFO ? odoo.http: HTTP Configuring static files
2018-09-13 13:28:30,080 24389 INFO CirqueAS odoo.modules.loading: loading 1 modules...
2018-09-13 13:28:30,107 24389 INFO CirqueAS odoo.modules.loading: 1 modules loaded in 0.03s, 0 queries
2018-09-13 13:28:30,236 24389 INFO CirqueAS odoo.modules.loading: loading 192 modules...
2018-09-13 13:28:30,350 24389 INFO ? odoo.addons.hw_escpos.controllers.main: disconnected : Printer Not Found
2018-09-13 13:28:30,350 24389 WARNING ? odoo.addons.hw_escpos.controllers.main: ESC/POS Device Disconnected: Printer Not Found
2018-09-13 13:28:30,387 24389 WARNING CirqueAS odoo.addons.base_gengo.wizard.base_gengo_translations: Gengo library not found, Gengo features disabled. If you plan to use it, please install the gengo library from http://pypi.python.org/pypi/gengo
2018-09-13 13:28:31,002 24390 INFO ? odoo.tools.misc: The path is ['/home/p3/p3/bin', '/usr/local/sbin', '/usr/local/bin', '/sbin', '/bin', '/usr/sbin', '/usr/bin', '/root/bin'].
2018-09-13 13:28:31,008 24390 INFO ? odoo.tools.misc: The path is ['/home/p3/p3/bin', '/usr/local/sbin', '/usr/local/bin', '/sbin', '/bin', '/usr/sbin', '/usr/bin', '/root/bin'].
2018-09-13 13:28:31,009 24390 INFO ? odoo.addons.base.ir.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
2018-09-13 13:28:31,142 24389 INFO CirqueAS odoo.modules.loading: 192 modules loaded in 0.91s, 0 queries
2018-09-13 13:28:31,820 24390 INFO ? odoo.addons.sms.wizard.send_sms: The `phonenumbers` Python module is not available. Phone number validation will be skipped. Try `pip3 install phonenumbers` to install it.
2018-09-13 13:28:32,047 24390 INFO ? odoo.http: HTTP Configuring static files
2018-09-13 13:28:32,063 24390 INFO CirqueAS odoo.modules.loading: loading 1 modules...
2018-09-13 13:28:32,090 24390 INFO CirqueAS odoo.modules.loading: 1 modules loaded in 0.03s, 0 queries
2018-09-13 13:28:32,218 24390 INFO CirqueAS odoo.modules.loading: loading 192 modules...
2018-09-13 13:28:32,299 24390 INFO ? odoo.addons.hw_escpos.controllers.main: disconnected : Printer Not Found
2018-09-13 13:28:32,300 24390 WARNING ? odoo.addons.hw_escpos.controllers.main: ESC/POS Device Disconnected: Printer Not Found
2018-09-13 13:28:32,364 24390 WARNING CirqueAS odoo.addons.base_gengo.wizard.base_gengo_translations: Gengo library not found, Gengo features disabled. If you plan to use it, please install the gengo library from http://pypi.python.org/pypi/gengo
2018-09-13 13:28:32,500 24389 WARNING CirqueAS odoo.fields: Field mrp.workorder.material.product_id with unknown comodel_name 'product.prodcut'
2018-09-13 13:28:33,079 24389 INFO CirqueAS odoo.modules.loading: Modules loaded.
2018-09-13 13:28:33,088 24389 INFO CirqueAS odoo.addons.base.ir.ir_http: Generating routing map
2018-09-13 13:28:33,111 24390 INFO CirqueAS odoo.modules.loading: 192 modules loaded in 0.89s, 0 queries
2018-09-13 13:28:33,353 24389 ERROR CirqueAS odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/wwwroot/odoo/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/wwwroot/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/wwwroot/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/wwwroot/odoo/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/home/wwwroot/odoo/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/wwwroot/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/wwwroot/odoo/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/wwwroot/odoo/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/home/wwwroot/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/wwwroot/odoo/addons/bus/controllers/main.py", line 37, in poll
    raise Exception("bus.Bus unavailable")
Exception: bus.Bus unavailable
====================
the odoo.conf file:
[options]
......
limit_memory_hard = 1677721600
limit_memory_soft = 629145600
limit_request = 8192
limit_time_cpu = 600
limit_time_real = 1200
max_cron_threads = 1
workers = 4

**Comment by pedrobaeza** [comment] 2018-09-14 07:47
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/11.0/setup/install.html.

Specifically, the problem is with the reversed proxy configuration (you should put `proxy_mode = True` if your conf if so).

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

**Closed by pedrobaeza** 2018-09-14 07:47 UTC
