### ISSUE TITLE
[16.0] website / blog / enable side-bar : internal server error

### ISSUE THREAD

**Issue by jwaes** [odoo/odoo#103888] opened 2022-10-24 08:19 UTC
Impacted versions:
16.0 reproducable on runbot.

Steps to reproduce:
Go to website -> Blog
Edit the Blog overview page
In 'Blogs Page' enable 'Sidebar', which is disabled by default

Current behavior:
500: Internal server error

`UncaughtClientError > TypeError
Uncaught Javascript Error > Cannot read properties of null (reading 'replace')
TypeError: Cannot read properties of null (reading 'replace')
    at set pageDocument [as pageDocument] (https://20444389-16-0-all.runbot111.odoo.com/web/assets/1863-1451a95/web.assets_backend.min.js:14421:750)
    at WebsitePreview._onPageLoaded (https://20444389-16-0-all.runbot111.odoo.com/web/assets/1863-1451a95/web.assets_backend.min.js:14334:262)
    at Object.mainEventHandler (https://20444389-16-0-all.runbot111.odoo.com/web/assets/1866-ec1691b/web.assets_common.min.js:2008:77)
    at HTMLIFrameElement.listener (https://20444389-16-0-all.runbot111.odoo.com/web/assets/1866-ec1691b/web.assets_common.min.js:1241:15)`

Expected behavior:

No internal server error.

**Comment by niyasraphy** [comment] 2022-10-24 08:22
Seems to duplicate of this issue: https://github.com/odoo/odoo/issues/103199

**Closed** 2022-10-26 13:38 UTC
Labels: Website, 16.0
