### ISSUE TITLE
Odoo Server Error (Traceback inside).

### ISSUE THREAD

**Issue by paula-em-lafon** [odoo/odoo#7274] opened 2015-06-24 20:10 UTC
We still don't really know what the problem is, but we can't modify any of the web pages inside odoo. Here's the traceback:

```
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/src/odoo/8.0/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/8.0/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/8.0/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/8.0/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/8.0/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/8.0/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/8.0/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/8.0/addons/web/controllers/main.py", line 878, in load_needaction
    return request.session.model('ir.ui.menu').get_needaction_data(menu_ids, request.context)
  File "/home/odoo/src/odoo/8.0/openerp/http.py", line 908, in proxy
    result = meth(cr, request.uid, *args, **kw)
  File "/home/odoo/src/odoo/8.0/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/src/odoo/8.0/openerp/addons/base/ir/ir_ui_menu.py", line 345, in get_needaction_data
    res[menu.id]['needaction_counter'] = obj._needaction_count(cr, uid, dom, context=context)
  File "/home/odoo/src/odoo/8.0/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/src/odoo/8.0/openerp/addons/base/ir/ir_needaction.py", line 64, in _needaction_count
    res = self.search(cr, uid, (domain or []) + dom, limit=100, order='id DESC', context=context)
  File "/home/odoo/src/odoo/8.0/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/src/odoo/8.0/addons/calendar/calendar.py", line 1769, in search
    return super(mail_message, self).search(cr, uid, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/home/odoo/src/odoo/8.0/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/src/odoo/8.0/openerp/models.py", line 1642, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/home/odoo/src/odoo/8.0/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/src/odoo/8.0/addons/website_mail/models/mail_message.py", line 67, in _search
    group_ids = self.pool.get('res.users').browse(cr, uid, uid, context=context).groups_id
  File "/home/odoo/src/odoo/8.0/openerp/fields.py", line 817, in __get__
    self.determine_value(record)
  File "/home/odoo/src/odoo/8.0/openerp/fields.py", line 910, in determine_value
    record._prefetch_field(self)
  File "/home/odoo/src/odoo/8.0/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/src/odoo/8.0/openerp/models.py", line 3229, in _prefetch_field
    result = records.read(list(fnames), load='_classic_write')
  File "/home/odoo/src/odoo/8.0/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/src/odoo/8.0/openerp/api.py", line 546, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/home/odoo/src/odoo/8.0/openerp/addons/base/res/res_users.py", line 883, in read
    res = super(users_view, self).read(cr, uid, ids, other_fields, context=context, load=load)
  File "/home/odoo/src/odoo/8.0/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/src/odoo/8.0/openerp/addons/base/res/res_users.py", line 300, in read
    result = super(res_users, self).read(cr, uid, ids, fields=fields, context=context, load=load)
  File "/home/odoo/src/odoo/8.0/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/src/odoo/8.0/openerp/models.py", line 3139, in read
    result = BaseModel.read(records, fields, load=load)
  File "/home/odoo/src/odoo/8.0/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/src/odoo/8.0/openerp/models.py", line 3174, in read
    self._read_from_database(stored, inherited)
  File "/home/odoo/src/odoo/8.0/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/src/odoo/8.0/openerp/models.py", line 3257, in _read_from_database
    self._apply_ir_rules(query, 'read')
  File "/home/odoo/src/odoo/8.0/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/src/odoo/8.0/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/home/odoo/src/odoo/8.0/openerp/models.py", line 4521, in _apply_ir_rules
    rule_where_clause, rule_where_clause_params, rule_tables = rule_obj.domain_get(cr, uid, inherited_model, mode, context=context)
  File "/home/odoo/src/odoo/8.0/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/src/odoo/8.0/openerp/addons/base/ir/ir_rule.py", line 150, in domain_get
    dom = self._compute_domain(cr, uid, model_name, mode)
  File "/home/odoo/src/odoo/8.0/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in _compute_domain
  File "/home/odoo/src/odoo/8.0/openerp/tools/cache.py", line 74, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/src/odoo/8.0/openerp/addons/base/ir/ir_rule.py", line 130, in _compute_domain
    rule_domain = self.read(cr, uid, [rule.id], ['domain'])[0]['domain']
  File "/home/odoo/src/odoo/8.0/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/src/odoo/8.0/openerp/models.py", line 3139, in read
    result = BaseModel.read(records, fields, load=load)
  File "/home/odoo/src/odoo/8.0/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/src/odoo/8.0/openerp/models.py", line 3174, in read
    self._read_from_database(stored, inherited)
  File "/home/odoo/src/odoo/8.0/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/src/odoo/8.0/openerp/models.py", line 3352, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/home/odoo/src/odoo/8.0/openerp/osv/fields.py", line 1466, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/home/odoo/src/odoo/8.0/openerp/addons/base/ir/ir_rule.py", line 53, in _domain_force_get
    res[rule.id] = expression.normalize_domain(eval(rule.domain_force, eval_context))
  File "/home/odoo/src/odoo/8.0/openerp/tools/safe_eval.py", line 312, in safe_eval
    c = test_expr(expr, _SAFE_OPCODES, mode=mode)
  File "/home/odoo/src/odoo/8.0/openerp/tools/safe_eval.py", line 167, in test_expr
    code_obj = compile(expr, "", mode)
  File "<string>", line 2
    ['|',('company_id','child_of',[user.company_id.id]),('company_id','=',False)]
    ^
SyntaxError: invalid syntax
```

**Comment by Anhlq87** [comment] 2015-06-25 02:12
You should be check again condition in your record rule.

**Comment by Yenthe666** [comment] 2016-08-05 09:57
Hi @paula-em-lafon,

Please update your Odoo codebase to the latest PR with a git fetch, then do an update of your Odoo and all your issues will be gone.
Closing this since we have no way of reproducing and it should really be fixed by now.

Regards,
Yenthe

**Closed by Yenthe666** 2016-08-05 09:57 UTC
