### ISSUE TITLE
Publishing Members to Public

### ISSUE THREAD

**Issue by lslaz1** [odoo/odoo#11310] opened 2016-03-11 20:57 UTC
website_membership module should have a configuration to publish members to the public and not only to users who are logged in.

**Comment by InstitutoARC** [comment] 2017-05-15 12:30
I hope this will be done. But if not, can anyone explain how to publish it manually? Obviasly there is change doing this, as can be seen on the oca website: https://odoo-community.org/members
Thanks

**Comment by lslaz1** [comment] 2017-05-15 12:58
@InstitutoARC I found one issue is whether they're a paid member or not. Under the "Membership" tab of the member, if "Current Membership Status" isn't Paid Member, it will not be public.

**Comment by InstitutoARC** [comment] 2017-05-15 13:34
@lslaz1 thank you for testing, yes I found the same, but I can´t find how to overcome this. 

I looked for some code in the html like this one:              
<t t-if="not memberships_partner_ids">
<p>No result found.</p> 
But it only gives out the text or not.
I as well looked at Technical - Record Rules - Membership lines - but public has already read access there.
I have no idea where to look and all I found in the forums were these two possibilities to restrict acess rights to the site.

**Comment by lslaz1** [comment] 2017-05-15 21:23
@InstitutoARC So, I found this in controllers/main.py
https://github.com/odoo/odoo/blob/9.0/addons/website_membership/controllers/main.py#L117
If you adapt the `membership_state` to be what you need it to be, it will work

**Comment by InstitutoARC** [comment] 2017-05-16 06:10
Thank you, I changed all the free to "paid" in the main.py and updated the app. But still nothing to see. :(

**Comment by lslaz1** [comment] 2017-05-16 13:39
I actually removed the `membership_state = free` part altogether and they are displaying for me. The only problem would be if you don't want every single member to be displayed.

**Comment by InstitutoARC** [comment] 2017-05-24 12:52
Really it functions, but now he does not show seperated membership states, everything as free member, not a gold and silver member, or maybe I have done something wrong? Can you display different membership types? Thanks

**Comment by pedrobaeza** [comment] 2018-04-17 23:48
Hi, I'm not able to reproduce this problem in latest runbot version and a working version of that in for example https://www.aeodoo.org/members, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-04-17 23:48 UTC
Labels: Wishlist
