### ISSUE TITLE
Many2many field widget set editable="bottom" at not edit model,  the fields also can be edit！

### ISSUE THREAD

**Issue by a4435351** [odoo/odoo#25370] opened 2018-06-21 04:18 UTC
Impacted versions:8.0

Steps to reproduce: set many2many widgit and set editable="bottom" at not edit model,the fields alse can be edit and submit

**Comment by a4435351** [comment] 2018-06-21 04:19
and also the blur for edit fields is invalid

**Comment by pedrobaeza** [comment] 2018-06-21 07:11
Sorry, but 8.0 is a deprecated version that is already not being supported, so any bug report about this old version won't be attended, and thus I close this issue. Please check if the problem is still there in new versions, and if so, you can open a new issue regarding that version.

Thanks for your comprehension.

**Closed by pedrobaeza** 2018-06-21 07:11 UTC
