### ISSUE TITLE
email send is ok, but receive appear bug. 

### ISSUE THREAD

**Issue by alexhmyang** [odoo/odoo#56140] opened 2020-08-19 13:18 UTC
![image](https://user-images.githubusercontent.com/10215059/90639336-1c234500-e261-11ea-851f-49fb854d1931.png)

I setup mail pop acount, and click 【receive now】, then it keeps loading and sending and receiving, hundreds of email are bounce back 

for example:
Aug 19 21:15:08 ecs-a583.novalocal odoo13[21676]: 2020-08-19 13:15:08,663 21676 INFO demo odoo.addons.mail.models.mail_thread: Routing mail from "postmaster" <postmaster@free....all, bounce
Aug 19 21:15:08 ecs-a583.novalocal odoo13[21676]: 2020-08-19 13:15:08,680 21676 INFO demo odoo.addons.mail.models.mail_thread: Routing mail from "postmaster" <postmaster@free....all, bounce
Aug 19 21:15:09 ecs-a583.novalocal odoo13[21676]: 2020-08-19 13:15:09,197 21676 INFO demo odoo.addons.mail.models.mail_mail: Mail with ID 1507 and Message-Id '<429152481368829...sfully sent
Aug 19 21:15:09 ecs-a583.novalocal odoo13[21676]: 2020-08-19 13:15:09,211 21676 INFO demo odoo.models.unlink: User #2 deleted mail.mail records with IDs: [1507]
Aug 19 21:15:09 ecs-a583.novalocal odoo13[21676]: 2020-08-19 13:15:09,228 21676 INFO demo odoo.models.unlink: User #2 deleted mail.message records with IDs: [2076]
Aug 19 21:15:09 ecs-a583.novalocal odoo13[21676]: 2020-08-19 13:15:09,228 21676 INFO demo odoo.addons.mail.models.mail_mail: Sent batch 1 emails via mail server ID #False
Aug 19 21:15:09 ecs-a583.novalocal odoo13[21676]: 2020-08-19 13:15:09,252 21676 INFO demo odoo.addons.mail.models.mail_mail: Mail with ID 1506 and Message-Id '<872066398760825...sfully sent
Aug 19 21:15:09 ecs-a583.novalocal odoo13[21676]: 2020-08-19 13:15:09,267 21676 INFO demo odoo.models.unlink: User #1 deleted mail.mail records with IDs: [1506]
Aug 19 21:15:09 ecs-a583.novalocal odoo13[21676]: 2020-08-19 13:15:09,284 21676 INFO demo odoo.models.unlink: User #1 deleted mail.message records with IDs: [2075]
Aug 19 21:15:09 ecs-a583.novalocal odoo13[21676]: 2020-08-19 13:15:09,284 21676 INFO demo odoo.addons.mail.models.mail_mail: Sent batch 1 emails via mail server ID #False

and cannot set up receive mail box.

[root@ecs-a583 ~]# systemctl status odoo13
● odoo13.service - Odoo13
   Loaded: loaded (/etc/systemd/system/odoo13.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2020-08-19 21:15:10 CST; 2min 33s ago
  Process: 21676 ExecStart=/app/erp/odoo13/odoo13-venv/bin/python3 /app/erp/odoo13/odoo/odoo-bin -c /app/erp/odoo13/odoo13.conf (code=exited, status=1/FAILURE)
 Main PID: 21676 (code=exited, status=1/FAILURE)

Aug 19 21:15:10 ecs-a583.novalocal odoo13[21676]: File: "/usr/local/python3/lib/python3.7/socket.py", line 676, in getfqdn
Aug 19 21:15:10 ecs-a583.novalocal odoo13[21676]: hostname, aliases, ipaddrs = gethostbyaddr(name)
Aug 19 21:15:10 ecs-a583.novalocal odoo13[21676]: 2020-08-19 13:15:10,466 21676 INFO ? odoo.service.server: Initiating server reload
Aug 19 21:15:10 ecs-a583.novalocal odoo13[21676]: 2020-08-19 13:15:10,715 21676 INFO demo odoo.addons.mail.models.mail_mail: Mail with ID 1510 and Message-Id '<636436631752576...sfully sent
Aug 19 21:15:10 ecs-a583.novalocal odoo13[21676]: 2020-08-19 13:15:10,730 21676 INFO demo odoo.models.unlink: User #2 deleted mail.mail records with IDs: [1510]
Aug 19 21:15:10 ecs-a583.novalocal odoo13[21676]: 2020-08-19 13:15:10,747 21676 INFO demo odoo.models.unlink: User #2 deleted mail.message records with IDs: [2079]
Aug 19 21:15:10 ecs-a583.novalocal odoo13[21676]: 2020-08-19 13:15:10,747 21676 INFO demo odoo.addons.mail.models.mail_mail: Sent batch 1 emails via mail server ID #False
Aug 19 21:15:10 ecs-a583.novalocal systemd[1]: odoo13.service: main process exited, code=exited, status=1/FAILURE
Aug 19 21:15:10 ecs-a583.novalocal systemd[1]: Unit odoo13.service entered failed state.
Aug 19 21:15:10 ecs-a583.novalocal systemd[1]: odoo13.service failed.

and in the end odoo is shut down by too many errors

**Comment by pedrobaeza** [comment] 2020-08-19 13:32
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Closed** 2023-04-07 14:27 UTC
Labels: Need information
