### ISSUE TITLE
Odoo sends duplicate e-mails when an e-mail client CCs to followers

### ISSUE THREAD

**Issue by johnw-bluemark** [odoo/odoo#53837] opened 2020-06-30 01:05 UTC
Impacted versions:
12.0, probably more

Steps to reproduce:

1. Create an invoice, sale order, or any other document that derives from mail.thread.
2. Add several followers to this document.
3. Send an e-mail on this thread from Odoo (send invoice/sale order or just a regular message).
4. Using an e-mail client, reply to the e-mail sent from Odoo, and add 1 or more of the other followers to the CC field.

Current behavior:
After the e-mail client sends the e-mail, it arrives in the inboxes marked on the e-mail. A few minutes later (when the cron job fires), Odoo will send this e-mail to all followers, even if they have already received it.

Expected behavior:
After the e-mail client sends the e-mail, it arrives in the inboxes marked on the e-mail. A few minutes later (when the cron job fires), Odoo sends this e-mail only to those who did not already receive it.

More Info:
In addons/mail/models/mail_thread.py, there's some code in the message_route_process() function that appears to be for dealing with this exact scenario, but it doesn't actually work. It is built on the premise that not passing the CC'd partner_ids to thread.message_post() will prevent the duplicate e-mails, but this is ineffective, as followers are notified by creating a second mail.mail record with all of the missing recipients. Something that might work better would be to add the partner_ids into the call, then delete the returned mail.mail as it represents all of the partner_ids that have already received the e-mail. The other mail.mail record will take care of sending the e-mail to the partner_ids that didn't receive it.

**Comment by pedrobaeza** [comment] 2020-06-30 06:58
That's something expected, and it's logical that goes this way, as Odoo always resend what is posted in Odoo to its followers. Why? Because the original mail received by them (the CC one) doesn't contain the extra contain that Odoo provides. For example: the button to view the document in Odoo or other action links.

Closing this as expected behavior.

**Closed by pedrobaeza** 2020-06-30 06:58 UTC

**Comment by johnw-bluemark** [comment] 2020-06-30 08:02
The only extra information Odoo provides in the duplicate e-mail is a "partner signature" at the end, which is not exactly a valuable contribution. I'm not convinced you understood the issue, so to be extra clear, I'm talking about external e-mail replies that originate from e-mail clients like Outlook, Thunderbird, and G-mail. It wouldn't make any sense for Odoo to randomly insert a "view document" button into one of these, nor have I ever seen it do so.

**Comment by pedrobaeza** [comment] 2020-06-30 08:07
The extra content depends on the user type to which that email belongs: portal or internal users will receive extra stuff. The mail is also important for tracking purposes.

Anyway, this is intended by design.

**Comment by johnw-bluemark** [comment] 2020-06-30 08:42
Who's design exactly? This comment seems to indicate that sending duplicate e-mails is **not** by design

> \# postponed after message_post, because this is an external message and we don't want to create
> \# duplicate emails due to notifications

The duplicate e-mails are very unpleasant, and since Odoo does not let e-mail recipients know who has been included on the e-mail, the use of CC on existing followers is inevitable.

**Comment by pedrobaeza** [comment] 2020-06-30 08:43
Odoo only send one. The other comes because it's in CC of your original email.

**Comment by johnw-bluemark** [comment] 2020-06-30 09:18
I'm fully aware of where each copy of the e-mail comes from. But a duplicate is a duplicate. Odoo knows who received it. Odoo sends another copy regardless. You say it's for tracking purposes, but the mail.message record would still be there if the e-mail was only sent to those who are following, but didn't receive it. What tracking do you need beyond that?

**Comment by pedrobaeza** [comment] 2020-06-30 09:19
Mail viewed tracking.
