### ISSUE TITLE
Pasting from excel loses formatting odoo 12 Enterprise

### ISSUE THREAD

**Issue by shazzwazz20** [odoo/odoo#61536] opened 2020-11-09 13:15 UTC
Impacted versions:
odoo 12 enterprise
Steps to reproduce:
1. Go to any html editor on Odoo .
2. Copy content from excel and paste it on editor.

Current behavior:
Table from excel not showing or breaks the css
Expected behavior:
Table should appear on editor.

Video/Screenshot link (optional):
https://user-images.githubusercontent.com/5850263/33992194-17aa5f92-e0eb-11e7-8dc0-1f48350b455f.PNG

**Comment by Yenthe666** [comment] 2020-11-09 14:43
To me that is out of scope. What do you think @pedrobaeza ?

**Comment by pedrobaeza** [comment] 2020-11-09 14:52
Yes, I agree, although it would be great that any copy/paste operation give an eye pleasant result, the truth is that each program inserts and pollutes somehow the content of the clipboard for adapting certain things for being later pasted in the same program, but not with others. Trying to read and interpret each possible content to the source program conventions is a huge task that is very possible to be broken across versions and time, so we can count this a feature that is not going to be implemented, but not a bug.

I recommend you though to go to software that is more respectful with standards, like LibreOffice, that copies the content following more standards, and get you to a more similar pasted content:

![Selección_001](https://user-images.githubusercontent.com/7165771/98556676-98975400-22a3-11eb-8c8a-08f3ea3553e7.png)

![Selección_002](https://user-images.githubusercontent.com/7165771/98556690-9b924480-22a3-11eb-9443-74b19edad70d.png)

**Closed by pedrobaeza** 2020-11-09 14:52 UTC

**Comment by shazzwazz20** [comment] 2020-11-09 18:10
Odoo using summernote library for editor.
This is a bug in summernote library. 
Not libraoffice but issue occurs cpoying paste from Microsoft excel also.
Would appreciate if odoo look into the library & come up with solution.
Editor is very important tool for Helpdesk module where agents /support/tech guy use lot of excel copy paste feature. 

Thanks in advance

**Comment by pedrobaeza** [comment] 2020-11-09 18:16
The way is orienting this is to change Summernote by other editor made internally: Jabberwock, so they are improving things, but for sure this can't be handled in current versions.
