### ISSUE TITLE
[12.0] tel: uri broken if not logged in after 8557bcfa302de7aca4b5dadb35841cd52f9ebfff

### ISSUE THREAD

**Issue by sherpya** [odoo/odoo#34306] opened 2019-06-21 17:58 UTC
Impacted versions:
12.0 after  8557bcfa302de7aca4b5dadb35841cd52f9ebfff

Steps to reproduce:
create a button, set tel:800800 as target

Current behavior:
Logged in -> correct
Anonymous -> /tel:800800 -> rootsite/tel:800800

Expected behavior:
Correct url in both cases

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2019-06-22 01:10
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by sherpya** [comment] 2019-06-24 12:09
@pedrobaeza 
http://546458-12-0-d489b5.runbot23.odoo.com/web/login

look at bottom (CALL 800800), I'm using incognito browser window with en_US locale

**Comment by pedrobaeza** [comment] 2019-06-24 13:05
This is something on your end, with the browser extension that converts numbers to links, as Odoo doesn't do that. Closing then.

**Comment by sherpya** [comment] 2019-06-24 13:20
I don't have any extension, you can try with curl, reverting the commit does not exposes the problem

**Comment by sherpya** [comment] 2019-06-24 13:22
curl 'http://546458-12-0-d489b5.runbot23.odoo.com/web/login' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: http://546458-12-0-d489b5.runbot23.odoo.com/web/database/selector' -H 'Connection: keep-alive' -H 'Cookie: utm_source=db; utm_medium=module; session_id=b2dc6d214760b92544b52c6ccf0960e3a94ce874; frontend_lang=en_US; im_livechat_history=["/web/login?db%3D546458-12-0-d489b5-all%26login%3Dadmin%26redirect%3D/web?debug=1","/","/#scrollTop=0","/web/login?db%3D546458-12-0-d489b5-all%26login%3Dadmin%26redirect%3D/","/web/login"]' -H 'Upgrade-Insecure-Requests: 1' -H 'Cache-Control: max-age=0'|grep tel:

**Comment by pedrobaeza** [comment] 2019-06-24 13:23
But where do you get tel thing? This is not something on standard page.

**Comment by sherpya** [comment] 2019-06-24 13:23
```
                <a href="/web/tel:800800" class="btn btn-primary" data-original-title="" title="" aria-describedby="tooltip587192">CALL 800800</a>
```

**Comment by sherpya** [comment] 2019-06-24 13:24
![Screenshot_20190624_152406](https://user-images.githubusercontent.com/120074/60022474-2e711580-9694-11e9-972a-c972facbda70.png)

**Comment by pedrobaeza** [comment] 2019-06-24 13:25
As said, this is not something standard... It's something that you are adding. And it's not a button, but simply a link. It's difficult to deduce the problem not using proper terminology.

OK, got it now. I reopen and tag.

**Comment by sherpya** [comment] 2019-06-24 13:26
I've added it using "button" widget so I supposed it's called button

**Comment by pedrobaeza** [comment] 2019-06-24 13:26
@nle-odoo you were the author of the mentioned commit. Can you please check the resolution of `tel:` links?

**Comment by nle-odoo** [comment] 2019-06-24 15:09
Hello,


From my tests, we use `werkzeug` to parse the URL (this is similar to python parsing URL but works in python2 and python3 the same), and in this particular instance it chooses that `tel:800800` is website `http://tel:800800` and not a telephone number.

So yes, this fail in this instance, but for example most instances in the phone number RFC works: https://tools.ietf.org/html/rfc3966

Testing it in a python prompt:

```
In [1]: import werkzeug                                                                                                                                                                                                                        

In [2]: werkzeug.urls.url_parse('tel:800800')                                                                                                                                                                                                  
Out[2]: URL(scheme='', netloc='', path='tel:800800', query='', fragment='')

In [3]: werkzeug.urls.url_parse('tel://800800')                                                                                                                                                                                                
Out[3]: URL(scheme='tel', netloc='800800', path='', query='', fragment='')

In [4]: werkzeug.urls.url_parse('tel:+800800')                                                                                                                                                                                                 
Out[4]: URL(scheme='tel', netloc='', path='+800800', query='', fragment='')

In [5]: werkzeug.urls.url_parse('tel:800-800')                                                                                                                                                                                                 
Out[5]: URL(scheme='tel', netloc='', path='800-800', query='', fragment='')

In [6]: werkzeug.urls.url_parse('tel:800800;ext=13')                                                                                                                                                                                           
Out[6]: URL(scheme='tel', netloc='', path='800800;ext=13', query='', fragment='')

In [7]: werkzeug.urls.url_parse('tel:7042;phone-context=example.com')
Out[7]: URL(scheme='tel', netloc='', path='7042;phone-context=example.com', query='', fragment='')
```

so for me, it seems rather ok, and if it is not okay maybe the issue should rather be solved in python or the library we use. In python the version of today still has this behavior (tel:800800 is a {website}:{port number} not a phone number):

https://github.com/python/cpython/blob/9bbf4d7083a819cbcee2a6cd3df2802d4c50f734/Lib/urllib/parse.py#L456

**Closed by nle-odoo** 2019-06-24 15:09 UTC
Labels: 12.0, Website

**Comment by pedrobaeza** [comment] 2019-06-24 15:11
Thanks for the insights, @nle-odoo

**Comment by sherpya** [comment] 2019-06-24 15:26
@nle-odoo why if I'm logged in the url is correct (without the / at the beginning)?

**Comment by sherpya** [comment] 2019-06-24 15:45
as a workaround I'm using tel:800-800 for now

**Comment by nle-odoo** [comment] 2019-06-24 15:55
@sherpya 

you must be in the particular case of being logged in and being someone that can edit the website, in this instance there is no URL rewriting.

If for example you are on another language that the principal (eg. http://localhost/fr_FR/) you will have the same issue with:

`http://localhost/fr_FR/tel:800800`

instead of:

tel:800800

And if you are a logged in user but that can't edit website, it will also not work and you will have

`http://localhost/tel:800800`

This is done in this part:

https://github.com/odoo/odoo/blob/4f3497c220c8cb16a69fe394379625b0b5dc59b4/addons/website/models/ir_qweb.py#L46-L48

if you are able to edit the website (`inherit_branding`) or editing translations (`edit_translations`) or in debug mode, the URLs are not rewritten (either for multilang, or for CDN).

Before 8557bcfa3 the URLs were never rewritten for multilang (which was an error and could duplicated the number of requests on frontend), now they are but as you said there seems to be this issue where tel:800800 is not considered a phone number by our library (but this should have already been the case in 10.0 and previous version).

> as a workaround I'm using tel:800-800 for now

yes, - is ignored by browser in any case

do note that it is recommended to have global numbers (with the +) if you are expecting people outside where the regional number work to use it.

**Comment by sherpya** [comment] 2019-06-24 15:57
@nle-odoo I used to prefix with +39, but it does not work with vodafone (since it's a local only number), now I've added a dash
