### ISSUE TITLE
datepicker is not working 

### ISSUE THREAD

**Issue by sangitassh** [odoo/odoo#48225] opened 2020-03-24 03:21 UTC
Impacted versions:
saas 13.2
Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):
https://drive.google.com/file/d/1yEjH3LnMlTu6BWp-FKtU__UUl06qwVI_/view?usp=sharing

**Comment by sangitassh** [comment] 2020-03-24 03:22
@Yenthe666 ping

**Comment by Yenthe666** [comment] 2020-03-24 11:31
Interesting enough I've reported something very similar through an official ticket (`2178976`) but nobody was ever able to reproduce it so we decided to close it.
@jvm-odoo looks like somebody else has a very similar issue.

**Comment by jvm-odoo** [comment] 2020-03-24 11:51
Indeed, I just reproduced it on runbot 13.0. I think the bug appears when you use arrow keys & enter to select the field you want to filter by.

**Comment by jvm-odoo** [comment] 2020-04-30 12:47
Hello,

I pushed a fix (for a very related issue) which should be merged today and it should be live on Monday.
https://github.com/odoo/odoo/commit/226c4d3fd2e6565fce7916be213e71dd17cee25e

The issue was related to the chart library that Odoo uses.

**Closed** 2020-04-30 18:51 UTC
Labels: 13.0, Confirmed
