### ISSUE TITLE
The "hours" label displayed with widget float_time is not the most logical label

### ISSUE THREAD

**Issue by geoff-bbc** [odoo/odoo#114619] opened 2023-03-07 17:44 UTC
Please review the attached screenshot as an example. (content within eLearning course)
I know there are multiple places across Odoo where the widget `float_time` is used. It doesn't seem too logical to have a field that renders as hh:mm (hours and minutes) to be labeled as "hours."

- If this were a decimal representation, like 1.5 hours then I would concur with the label.
- In this example, the spoken explanation of this value would be "0 hours and 37 minutes" or usually just "37 minutes"
- Since hh:mm is a fairly universal standard, one approach is to remove the label altogether and let the field caption and help text do the work.
- Another option would be a label like "hh:mm" or "hours/minutes" so that there isn't confusion that the value could be minutes and seconds (mm:ss).
- I do appreciate the functionality of the field widget itself. It is helpful to have the conversion between a decimal entry and hh:mm. For example the entry of 1.75 will be converted to display 01:45. 

![SNAG_3-7-2023_9 25 23 AM](https://user-images.githubusercontent.com/59264352/223504688-a98ad702-affb-46c9-9b89-35b2f26483bb.png)

**Comment by AbdelAzizMohamedMousa** [comment] 2023-04-01 15:21
Thank you for bringing this to our attention. The label for the float_time widget in Odoo does indeed display as "hours" which may not be the most appropriate label for all use cases. Your suggestion of removing the label or using a label like "hh:mm" or "hours/minutes" is a valid one.

One potential solution would be to allow the label for the float_time widget to be customizable, so that users can choose the label that best fits their use case. This could be done through a configuration setting or through a custom module that extends the float_time widget.

In the meantime, as you suggested, using the field caption and help text to provide context for the float_time value may be the best workaround.

**Comment by vava-odoo** [comment] 2023-06-15 19:09
Hi @geoff-bbc 
I'll made the feedback internally, but since it's not a bug I'll close the issue.
Best

**Closed by vava-odoo** 2023-06-15 19:09 UTC
