### ISSUE TITLE
[13.0][OE] web: optional list hide

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#62681] opened 2020-12-01 12:51 UTC
Impacted versions:
13.0, 14.0

Steps to reproduce:
Go to runbot
Open sale order
Add option field in order line
--> Issue some item are hide

![image](https://user-images.githubusercontent.com/16716992/100743485-9f197700-33dc-11eb-979d-7e5acfbb2cae.png)

**Comment by pedrobaeza** [comment] 2020-12-01 14:54
But I suppose that is because you have restricted a lot the height of the window. It's hidden due to the coupon/promotions thing, but I think is the same as bad as being on top of that buttons. The problem is that you need more height.

**Comment by fmdl** [comment] 2020-12-01 14:56
I use a macbook 13".

**Comment by fmdl** [comment] 2020-12-01 14:57
@pedrobaeza the height of the field list is limited by the height of the One2many field. (if you add some articles it is good).

**Comment by pedrobaeza** [comment] 2020-12-01 14:58
OK, that last comment seems something, as if a height is limited, then the dropdown shouldn't be limited that way.

**Comment by msh-odoo** [comment] 2020-12-02 05:12
@fmdl @pedrobaeza Should be fixed with https://github.com/odoo/odoo/pull/62472

**Closed** 2021-01-05 12:59 UTC
Labels: 13.0, 14.0, Framework
