### ISSUE TITLE
[9.0] Can't post message on Issues when having read-only access

### ISSUE THREAD

**Issue by dreispt** [odoo/odoo#10838] opened 2016-02-09 10:36 UTC
1/ Change "demo" access to "Project User"
2/ Change ACL on Issues to read-only for Project Users
3/ Login as "demo" and open an Issue form. It's should be read-only.
4/ Try to "Log an Internal Note": it works.
5/ Try to post a "New Message": you sill see a write permission error, but shouldn't.

As a side note, on Project Tasks the equivalent test works perfectly.

**Comment by pedrobaeza** [comment] 2018-04-12 20:06
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-04-12 20:06 UTC
Labels: 9.0, Services
