### ISSUE TITLE
[11.0] website contact form, phone validation error on valid country prefix

### ISSUE THREAD

**Issue by yung-wang** [odoo/odoo#22513] opened 2018-01-25 09:54 UTC
Impacted versions: 11

Steps to reproduce:
Make sure Phone Validation is active (+ add international prefix) and that website contact form is installed.
Go to the website and fill in the "contact us" page and try both phonenumbers.
+31765123456 (this works)
0031765123456 (error unable to parse 0031765123456: (0) missing or invalid default region)
Both are valid ways of using the country code prefix.

In the backend this doesn't raise an error. Create a new customer in the country The Netherlands. Try both phone numbers and the system accepts them.

Current behavior:
see above

Expected behavior:
the same logic should be used in the backend and website. On the website form both phonenumbers should work, since these are valid ways of writing an internal country code prefix.

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment] 2018-01-26 16:17
Hello @yung-wang 
I can Reproduce on [Runbot](http://297439-11-0-843115.runbot14.odoo.com/contactus) and Confirm this behavior.

Contact us form:

![](https://image.prntscr.com/image/sLntDh1YR_WVTbishlqK1A.png)

Backend:
Netherlands is Selected

![](https://image.prntscr.com/image/w2TG2C08Samttb43gN16dg.png)

If Country is blank

![](https://image.prntscr.com/image/eIzUV0kwTLKfy__3A7quKQ.png)

I don't Consider this as bug but Warning message should be Improved and also In Contact Us form Country Should be added as It is used for Phone number Validation.

CC: @Yenthe666

**Comment by Yenthe666** [comment] 2018-01-28 08:14
The website team will look at this as soon as possible!

**Comment by JKE-be** [comment] 2018-01-31 09:21
@yung-wang 

Thanks for the reporting, we will try to find a solution to fix it asap.

Meanwhile, the simple way to get it working as expected is to install the GeoIP lib.
Until now it was optional, but if you don't get it, we cannot check your phone number because your country is unknown by the system. So the fix will be probably to add it as dependency

**Comment by JKE-be** [comment] 2018-02-07 08:19
Hi @rrahir 
any news ?

**Comment by rrahir** [comment] 2018-02-07 13:21
Fixed with 65832dc2982b5bbec0ac92dae5ece9fe7d9430e6.

**Closed** 2018-02-07 13:22 UTC
Labels: 11.0, Confirmed, Website

**Comment by JKE-be** [comment] 2018-02-07 14:03
@rrahir 

si tu retires le raise_exception, a quoi sert les try catch du commit initial ? 
https://github.com/odoo/odoo/blob/11.0/addons/website_crm_phone_validation/controllers/website_form.py#L43

 code mort ?

**Comment by yung-wang** [comment] 2018-02-08 08:00
Thanks for the fix. I just tested it in Runbot and it works.
