### ISSUE TITLE
[v11] Disable the page /website/info

### ISSUE THREAD

**Issue by MathAndrews** [odoo/odoo#39678] opened 2019-10-31 17:22 UTC
Impacted versions: 11

Steps to reproduce: 
- Have a Odoo with the module website install,
- Go in the back office, in developer mod, in Settings > Technical > User Interface > Views,
- Search for the view `website_info',
- Edit the view and disable the view,
- The on the website: go to the page /website/info.

Current behavior:
Generate a 500: Internal Server Error: _handle_exception() takes 2 positional arguments but 3 were given

Expected behavior:
Get a 404 page

Video/Screenshot link (optional):
![odoo_website_info](https://user-images.githubusercontent.com/11832944/67970234-f4e48400-fc0a-11e9-914b-95cf398c2982.png)

In file `addons/contrib/addons/website/controllers/main.py` line 195 may be change
```return request.env['ir.http']._handle_exception(e, 404)```
into
```return request.env['ir.http']._handle_exception(werkzeug.exceptions.NotFound())```

Best Regards,
M.

**Comment by pedrobaeza** [comment] 2019-10-31 17:24
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by MathAndrews** [comment] 2019-10-31 17:33
Yes I manage to reproduce the error in runbot infrastructure.

For more detail on how to reproduce the issue, please check my first comment.

Best regards.

**Comment by pedrobaeza** [comment] 2019-10-31 17:43
Thanks for extra checks.

Maybe you can do the PR with the proposed fix?

**Comment by MathAndrews** [comment] 2019-11-27 13:22
It's seem I can't do PR

**Comment by pedrobaeza** [comment] 2019-11-27 13:23
You can always do a PR. What you can't do is to create the branch in odoo/odoo, so you need to first fork the project, but the rest is git stuff.

**Comment by Yenthe666** [comment] 2019-11-27 14:12
I've discussed this with the guys from Odoo but this proposal won't be accepted. The reason is that these pages would create an SEO backlink after this change, which Odoo doesn't want (CC @JKE-be).

**Closed by Yenthe666** 2019-11-27 14:12 UTC
Labels: 11.0, Website

**Comment by MathAndrews** [comment] 2019-11-27 14:49
@Yenthe666 So Odoo want to generate a 500 Server Error due to a error in the python code rather than generate a 404 for people who don't want to display the list of application installed in there Odoo???

**Comment by Yenthe666** [comment] 2019-11-27 15:05
Yes. It's not my call, it was the call from somebody very high up the chain ;)
