### ISSUE TITLE
[9.0] Cannot backup with zip (includes file store)

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#9295] opened 2015-10-29 03:34 UTC
Hi Odoo,

I cannot backup the database with the option of "zip (includes file store)".
it will takes a long time and do nothing.
But when I backup the database with no include file store I can.

The database that I have, just have 20.000 records of contacts. thats all, but still cannot backup it.

Thank You.

**Comment by Yenthe666** [comment] 2016-05-24 06:59
Hi @falinwa,

I can no longer reproduce this issue, the zip (including filestore) works fine now. I've just tested this on a database from 2GB with over 10.000 records.
If you should still face this problem please update your Odoo and test again. If you still have this problem don't hesitate to re-open this issue or create a new one with a bit more details!

Closing this one since there is no way to reproduce this as the moment.

Regards,
Yenthe

**Closed by Yenthe666** 2016-05-24 06:59 UTC
