### ISSUE TITLE
[12.0] Invoice pdf without watermark with several invoices

### ISSUE THREAD

**Issue by AngelCamacho** [odoo/odoo#40088] opened 2019-11-11 14:00 UTC
Impacted versions: 12.0

Steps to reproduce: You have to select more than 10 invoices and select to print all the invoices in a single pdf . 

Current behavior: All the invoices doesn't have a watermark.

Expected behavior: Print the invoices like a simple one, with the watermark.

Video/Screenshot link (optional):
10 invoices grouped in a single pdf, without watermark:
![image](https://user-images.githubusercontent.com/11173802/68592633-d0eb3300-0493-11ea-9ead-0a25388ce233.png)

6 invoices grouped in a single pdf, with watermark:
![image](https://user-images.githubusercontent.com/11173802/68592688-ef512e80-0493-11ea-9dfc-a1ea71609101.png)

**Comment by pedrobaeza** [comment] 2019-11-13 18:16
@xmo-odoo I think you are the one that did the PDF optimization splitting by `<h1>` or similar, aren't you? Can you say anything about this?

**Comment by xmo-odoo** [comment] 2019-11-14 07:17
@pedrobaeza that might be true but I don't remember it. I know that I implemented a page-break thing but that was for the financial reports (and tables spanning multiple pages)

Also trying it out on runbot I don't see the issue, though I might have mis-repro'd:

* [9 invoices, background is present on all pages](https://github.com/odoo/odoo/files/3845086/Invoices-1.pdf)
* [11 invoices, background is also present on all pages](https://github.com/odoo/odoo/files/3845091/Invoices-3.pdf)

**Comment by pedrobaeza** [comment] 2019-11-14 08:14
Then if no reproducible, no bug for now. @AngelCamacho if you are not able to reproduce this in runbot and give us steps to reproduce it, we will have to discard this.

**Comment by Yenthe666** [comment] 2019-12-03 08:36
Hi there,

Since we haven't gotten any feedback in a while I'm closing off this issue.
Don't hesitate to respond back with more information. We'll reopen the issue if there is enough information to explain this issue.

Regards,
Yenthe

**Closed by Yenthe666** 2019-12-03 08:36 UTC
Labels: 12.0, Need information
