### ISSUE TITLE
[14.0]No more public method for downloading report through RPC

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#78533] opened 2021-10-18 10:16 UTC
Impacted versions:

v> 14.0

Steps to reproduce:

try to download a report trhough xmlrpc or jsonrpc 

Current behavior:

@mart-e placed many methods in private there : https://github.com/OCA/OCB/commit/d9287caf9408bb4ff85ad734cbca08e44321e205#diff-7ce69a093ea1fb1cf2989e24d52cb8e717ab4f2b3c2006ba5cc67503a3df1aff 

_render is a private method and cannot be used through public api

Yet in the commit message it is supposed to leave the render_template method public :

![image](https://user-images.githubusercontent.com/1043935/137710177-cda921b3-8bfd-4ef7-bc9d-d982a3af5b5e.png)
 

Expected behavior:

at least one public method or workaround to be able to DL a report

@mart-e  any workaround on this ?

**Comment by mart-e** [comment] 2021-10-18 10:52
Duplicate of #78533

**Closed by mart-e** 2021-10-18 10:52 UTC
