### ISSUE TITLE
CRITICAL Accounting Issue in anglosaxon vendor bills

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#32911] opened 2019-04-24 10:38 UTC
Impacted versions: 12.0

Steps to reproduce:
Using anglosaxon create an invoice for a product with a price variance. Use a discount on the line. Use 100% discount for a very egregious example.

Initial analysis shows that the move lines dict and inv_line passed to 
`def _anglo_saxon_purchase_move_lines(self, i_line, res)` have the correct price, but an incorrect price unit. 

Anglosaxon goes and does everything correctly, creating the correct diff lines, even calculating the correct diff, but then inexplicably decides not to use it.

This is the variable `price_val_dif` - it is correct except for rounding (and arguably spelling).(Roughly line 117)

But then the line is updated not with that amount but rather.
`line['price'] = inv.currency_id.round(line['quantity'] * line['price_unit'])` (roughly line 137)

But the price unit field is the price_unit on the invoice line, rather than than a discount inclusive price unit. Moreover, price_val_dif must be used, even if you fix price unit upstream, because even if price_unit was calculated correctly, it would be rounded and lead to errors, as the rounding occurs at subtotal level in invoices. It must be the difference between the original line price and the diff line price - no other value or calculation makes sense.

So BUGFIX 1: Use price_val_dif in `_anglo_saxon_purchase_move_lines` Line 137 of purchase_stock/models/account_invoice.py - This is the critical one
BUGFIX 2: To come - not so critical - get a correct price unit to start, at least a rounded approximation. OK its line 1123 of account/models/account_invoice.py. Function is `def invoice_line_move_line_get(self):`

OPW to come.
https://github.com/odoo/odoo/blob/77c708c516beb322df37220634e178ba82e894c9/addons/purchase_stock/models/account_invoice.py#L117-L139

Current behavior:
Residual / Sum of relevant journals != Invoice Total

Expected behavior:
Residual / Sum of relevant journals == Invoice Total

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/5093264/56653743-71d5f480-66e2-11e9-9707-4e0973955f72.png)

@qdp-odoo

**Comment by gdgellatly** [comment] 2019-04-24 10:47
opw 1974002

**Comment by william-andre** [comment] 2019-04-24 10:51
@oco-odoo

**Comment by oco-odoo** [comment] 2019-04-24 11:07
@kebeclibre It seems really similar to the ticket we were talking about this morning. I think the issue is just the same. 

@gdgellatly If I'm right (which might no the case), the problem lies actually in the price difference lines that are computed. Some are wrong because of this line https://github.com/odoo/odoo/blob/12.0/addons/purchase_stock/models/account_invoice.py#L87 , and cause the amount on the payable account to be different from the invoice total, hence the bug you're facing. We're suspecting that this line should simply be removed, and are currently running further tests to ensure doing a so "naive" fix is actually enough.

**Comment by gdgellatly** [comment] 2019-04-24 11:15
Hi @oco-odoo No I don't think it can be i this case. In the screenshot above I have the following

Qty 50.0
Price 5.61
Stock Value 2.29
Nett Price ~5.25 after discount

The line coming in is price of 262.77
2.29 * 50 = 114.50 is correct
price_val_dif is correct
price_unit is wrong, but even if it was right it would be wrong.

What it gives (5.61-2.29) * 50 = 166
If price_unit was correct. (5.25-2.29) * 50 = 148
What it should be 262.77 - 114.50 = 147.77 = price_val_dif

**Comment by gdgellatly** [comment] 2019-04-24 11:19
@oco-odoo Also the other reason that line can't be the cause of this issue, is that you can reproduce without an associated purchase order, so that line of code is never called.

**Comment by oco-odoo** [comment] 2019-04-24 11:23
@gdgellatly Alright, I'll let my colleagues from support handle it, then. Since it seemed pretty similar to another issue I knew, I just wanted to make sure it was reported, so that people don't do the job twice ;)

**Comment by gdgellatly** [comment] 2019-04-24 16:23
Oh my it gets even worse, as a quick fix I tried

```python
    @api.model
    def _anglo_saxon_purchase_move_lines(self, i_line, res):
        if i_line.invoice_id.anglo_saxon_financial:
            return res
        # Note this loop isa temporary fix for a bug
        for r in res:
            r['price_unit'] = r['price'] / r['quantity']
        return super()._anglo_saxon_purchase_move_lines(i_line, res)
```

https://github.com/odoo/odoo/blob/77c708c516beb322df37220634e178ba82e894c9/addons/purchase_stock/models/account_invoice.py#L99

If you fix price unit to be actually correct, you get no difference entries. This whole comparison is messed up. I don't even get why the second leg is needed, but if it is, it is wrong. The first one is wrong too really. 
The only thing that matters is
`interim_price` compared to `line['price']`. 
Price units have no place as a comparison for whether difference entries are required.

**Comment by gustavovalverde** [comment] 2019-04-28 13:55
Landed here because I was seeing this awkward  behavior in a client with a total amount due completely different from the amount total of the invoice (explaining that was worst). After tracking further I realized that the categories with the **price difference** account set were causing this odd behavior.

@gdgellatly do you know if this is already in bug-fixing?

**Comment by gdgellatly** [comment] 2019-04-28 14:59
@gustavovalverde I got a message saying under investigation. But support is pretty hit and miss, depends who you get.

**Closed** 2019-05-21 10:13 UTC
Labels: 12.0, Accounting, OE
