### ISSUE TITLE
[9.0] web redirect results in blank backend page - needs ?debug to show content

### ISSUE THREAD

**Issue by explanar** [odoo/odoo#11293] opened 2016-03-10 17:16 UTC
Impacted versions: 9.0alpha1, 9.0alpha2, 9.0, Master

Steps to reproduce: Fresh install via [https://github.com/aschenkels-ictstudio/odoo-install-scripts/blob/9.0/ubuntu-14-04/odoo_install.sh](script), install "Accounting & finance"

Current behavior: After admin login, backend shows only backgrounds+logo+Powered by - no menu, no content

Expected behavior: show whole backend including menus and content

Video/Screenshot link (optional):

After the login URL= `http://host:8069/web`:

```
"GET /web HTTP/1.1" 200 -
"POST /longpolling/poll HTTP/1.1" 200 -
```

Add ?debug: URL= `http://host:8069/web?debug` loading complete backend:

```
GET /web?debug HTTP/1.1" 200 -
GET /web?debug HTTP/1.1" 200 -
GET /web/static/lib/jquery.ui/jquery-ui.css HTTP/1.1" 200 -
GET /web/static/src/fonts/lato/stylesheet.css HTTP/1.1" 200 -
GET /web/static/src/less/mimetypes.less.css HTTP/1.1" 304 -
GET /web/static/src/less/animation.less.css HTTP/1.1" 304 -
GET /web/static/lib/bootstrap-datetimepicker/css/bootstrap-datetimepicker.css HTTP/1.1" 200 -
GET /web/static/lib/select2/select2.css HTTP/1.1" 200 -
GET /web/static/lib/select2-bootstrap-css/select2-bootstrap.css HTTP/1.1" 200 -
GET /web_planner/static/src/less/web_planner_common.less.css HTTP/1.1" 304 -
GET /web_editor/static/src/css/web_editor.css HTTP/1.1" 200 -
GET /web_editor/static/src/less/web_editor.less.css HTTP/1.1" 304 -
GET /web/static/lib/jquery.textext/jquery.textext.css HTTP/1.1" 200 -
GET /web/static/lib/jquery.ui.notify/css/ui.notify.css HTTP/1.1" 200 -
GET /web/static/lib/nvd3/nv.d3.css HTTP/1.1" 200 -
GET /web/static/src/css/base.css HTTP/1.1" 200 -
GET /web/static/src/css/data_export.css HTTP/1.1" 200 -
GET /base/static/src/css/modules.css HTTP/1.1" 200 -
GET /website/static/src/less/import_bootstrap.less.css HTTP/1.1" 200 -
GET /web/static/src/less/variables.less.css HTTP/1.1" 304 -
GET /web/static/src/less/enterprise_compatibility.less.css HTTP/1.1" 304 -
GET /web/static/src/less/modal.less.css HTTP/1.1" 304 -
GET /web/static/src/less/utils.less.css HTTP/1.1" 304 -
GET /web/static/src/less/notification.less.css HTTP/1.1" 304 -
GET /account/static/src/css/account_bank_and_cash.css HTTP/1.1" 200 -
GET /account/static/src/css/account.css HTTP/1.1" 200 -
GET /account/static/src/less/account_reconciliation.less.css HTTP/1.1" 304 -
GET /account/static/src/less/account_journal_dashboard.less.css HTTP/1.1" 304 -
GET /mail/static/src/less/announcement.less.css HTTP/1.1" 304 -
GET /base_import/static/src/less/import.less.css HTTP/1.1" 304 -
GET /mail/static/src/less/client_action.less.css HTTP/1.1" 304 -
GET /mail/static/src/less/chat_window.less.css HTTP/1.1" 304 -
GET /mail/static/src/less/composer.less.css HTTP/1.1" 304 -
GET /sales_team/static/src/css/sales_team.css HTTP/1.1" 200 -
GET /mail/static/src/less/chatter.less.css HTTP/1.1" 304 -
GET /mail/static/src/less/thread.less.css HTTP/1.1" 304 -
GET /sales_team/static/src/less/sales_team_dashboard.less.css HTTP/1.1" 304 -
GET /web_tip/static/src/less/tip.less.css HTTP/1.1" 304 -
GET /web_calendar/static/src/less/web_calendar.less.css HTTP/1.1" 304 -
GET /web_calendar/static/lib/fullcalendar/css/fullcalendar.css HTTP/1.1" 200 -
GET /web_diagram/static/src/less/diagram_view.less.css HTTP/1.1" 304 -
GET /web_editor/static/lib/summernote/summernote.css HTTP/1.1" 200 -
GET /web_editor/static/src/css/snippets.css HTTP/1.1" 200 -
GET /web_editor/static/src/css/editor.css HTTP/1.1" 200 -
GET /web_editor/static/src/css/backend.css HTTP/1.1" 200 -
GET /web_kanban/static/src/less/kanban_dashboard.less.css HTTP/1.1" 304 -
GET /web_kanban/static/src/less/kanban_view.less.css HTTP/1.1" 304 -
GET /web_view_editor/static/src/css/view_editor.css HTTP/1.1" 200 -
GET /web_settings_dashboard/static/src/less/dashboard.less.css HTTP/1.1" 304 -
GET /web/static/lib/es5-shim/es5-shim.min.js HTTP/1.1" 200 -
GET /web/static/lib/underscore/underscore.js HTTP/1.1" 200 -
GET /web/static/lib/underscore.string/lib/underscore.string.js HTTP/1.1" 200 -
GET /web/static/lib/spinjs/spin.js HTTP/1.1" 200 -
GET /web/static/lib/moment/moment.js HTTP/1.1" 200 -
GET /web/static/lib/autosize/autosize.js HTTP/1.1" 200 -
GET /web/static/lib/jquery.ui/jquery-ui.js HTTP/1.1" 200 -
GET /web/static/lib/jquery/jquery.browser.js HTTP/1.1" 200 -
GET /web/static/lib/jquery.blockUI/jquery.blockUI.js HTTP/1.1" 200 -
GET /web/static/lib/jquery.hotkeys/jquery.hotkeys.js HTTP/1.1" 200 -
GET /web/static/lib/jquery.placeholder/jquery.placeholder.js HTTP/1.1" 200 -
GET /web/static/lib/jquery.timeago/jquery.timeago.js HTTP/1.1" 200 -
GET /web/static/lib/jquery.form/jquery.form.js HTTP/1.1" 200 -
GET /web/static/lib/jquery.ba-bbq/jquery.ba-bbq.js HTTP/1.1" 200 -
GET /web/static/lib/qweb/qweb2.js HTTP/1.1" 200 -
GET /web/static/src/js/boot.js HTTP/1.1" 200 -
GET /web/static/src/js/framework/class.js HTTP/1.1" 200 -
GET /web/static/src/js/framework/translation.js HTTP/1.1" 200 -
GET /web/static/src/js/framework/ajax.js HTTP/1.1" 200 -
GET /web/static/src/js/framework/time.js HTTP/1.1" 200 -
GET /web/static/src/js/framework/mixins.js HTTP/1.1" 200 -
GET /web/static/src/js/framework/widget.js HTTP/1.1" 200 -
GET /web/static/src/js/framework/registry.js HTTP/1.1" 200 -
GET /web/static/src/js/framework/session.js HTTP/1.1" 200 -
GET /web/static/src/js/framework/model.js HTTP/1.1" 200 -
GET /web/static/src/js/framework/utils.js HTTP/1.1" 200 -
GET /web/static/src/js/framework/core.js HTTP/1.1" 200 -
GET /web/static/src/js/framework/dialog.js HTTP/1.1" 200 -
GET /web/static/src/js/tour.js HTTP/1.1" 200 -
GET /web/static/test/menu.js HTTP/1.1" 200 -
GET /web/static/test/x2many.js HTTP/1.1" 200 -
GET /web/static/lib/bootstrap-datetimepicker/src/js/bootstrap-datetimepicker.js HTTP/1.1" 200 -
GET /web/static/lib/select2/select2.js HTTP/1.1" 200 -
GET /web_planner/static/src/js/web_planner_common.js HTTP/1.1" 200 -
GET /web_editor/static/src/js/base.js HTTP/1.1" 200 -
GET /web_editor/static/src/js/snippets.animation.js HTTP/1.1" 200 -
GET /web/static/lib/jquery.validate/jquery.validate.js HTTP/1.1" 200 -
GET /web/static/lib/jquery.scrollTo/jquery.scrollTo.js HTTP/1.1" 200 -
GET /web/static/lib/jquery.textext/jquery.textext.js HTTP/1.1" 200 -
GET /web/static/lib/bootstrap/js/affix.js HTTP/1.1" 200 -
GET /web/static/lib/bootstrap/js/alert.js HTTP/1.1" 200 -
GET /web/static/lib/bootstrap/js/button.js HTTP/1.1" 200 -
GET /web/static/lib/bootstrap/js/carousel.js HTTP/1.1" 200 -
GET /web/static/lib/bootstrap/js/collapse.js HTTP/1.1" 200 -
GET /web/static/lib/bootstrap/js/popover.js HTTP/1.1" 200 -
GET /web/static/lib/bootstrap/js/scrollspy.js HTTP/1.1" 200 -
GET /web/static/lib/bootstrap/js/tab.js HTTP/1.1" 200 -
GET /web/static/lib/bootstrap/js/transition.js HTTP/1.1" 200 -
GET /web/static/lib/jquery.ui.notify/js/jquery.notify.js HTTP/1.1" 200 -
GET /web/static/lib/nvd3/d3.v3.js HTTP/1.1" 200 -
GET /web/static/lib/nvd3/nv.d3.js HTTP/1.1" 200 -
GET /web/static/lib/backbone/backbone.js HTTP/1.1" 200 -
GET /web/static/lib/py.js/lib/py.js HTTP/1.1" 200 -
GET /web/static/src/js/framework/data_model.js HTTP/1.1" 200 -
GET /web/static/src/js/framework/formats.js HTTP/1.1" 200 -
GET /web/static/src/js/framework/view.js HTTP/1.1" 200 -
GET /web/static/src/js/framework/pyeval.js HTTP/1.1" 200 -
GET /web/static/src/js/action_manager.js HTTP/1.1" 200 -
GET /web/static/src/js/control_panel.js HTTP/1.1" 200 -
GET /web/static/src/js/view_manager.js HTTP/1.1" 200 -
GET /web/static/src/js/web_client.js HTTP/1.1" 200 -
GET /web/static/src/js/framework/data.js HTTP/1.1" 200 -
GET /web/static/src/js/compatibility.js HTTP/1.1" 200 -
GET /web/static/src/js/framework/misc.js HTTP/1.1" 200 -
GET /web/static/src/js/framework/session_instance.js HTTP/1.1" 200 -
GET /web/static/src/js/framework/crash_manager.js HTTP/1.1" 200 -
GET /web/static/src/js/widgets/change_password.js HTTP/1.1" 200 -
GET /web/static/src/js/widgets/debug_manager.js HTTP/1.1" 200 -
GET /web/static/src/js/widgets/data_export.js HTTP/1.1" 200 -
GET /web/static/src/js/widgets/date_picker.js HTTP/1.1" 200 -
GET /web/static/src/js/widgets/loading.js HTTP/1.1" 200 -
GET /web/static/src/js/widgets/notification.js HTTP/1.1" 200 -
GET /web/static/src/js/widgets/sidebar.js HTTP/1.1" 200 -
GET /web/static/src/js/widgets/priority.js HTTP/1.1" 200 -
GET /web/static/src/js/widgets/progress_bar.js HTTP/1.1" 200 -
GET /web/static/src/js/widgets/pager.js HTTP/1.1" 200 -
GET /web/static/src/js/widgets/systray_menu.js HTTP/1.1" 200 -
GET /web/static/src/js/widgets/user_menu.js HTTP/1.1" 200 -
GET /web/static/src/js/menu.js HTTP/1.1" 200 -
GET /web/static/src/js/views/list_common.js HTTP/1.1" 200 -
GET /web/static/src/js/views/list_view.js HTTP/1.1" 200 -
GET /web/static/src/js/views/form_view.js HTTP/1.1" 200 -
GET /web/static/src/js/views/form_common.js HTTP/1.1" 200 -
GET /web/static/src/js/views/form_widgets.js HTTP/1.1" 200 -
GET /web/static/src/js/views/form_relational_widgets.js HTTP/1.1" 200 -
GET /web/static/src/js/views/list_view_editable.js HTTP/1.1" 200 -
GET /web/static/src/js/views/pivot_view.js HTTP/1.1" 200 -
GET /web/static/src/js/views/graph_view.js HTTP/1.1" 200 -
GET /web/static/src/js/views/graph_widget.js HTTP/1.1" 200 -
GET /web/static/src/js/views/search_view.js HTTP/1.1" 200 -
GET /web/static/src/js/views/search_filters.js HTTP/1.1" 200 -
GET /web/static/src/js/views/search_inputs.js HTTP/1.1" 200 -
GET /web/static/src/js/views/search_menus.js HTTP/1.1" 200 -
GET /web/static/src/js/views/tree_view.js HTTP/1.1" 200 -
GET /web/static/src/js/apps.js HTTP/1.1" 200 -
GET /account/static/src/js/account_reconciliation_widgets.js HTTP/1.1" 200 -
GET /account/static/src/js/move_line_quickadd.js HTTP/1.1" 200 -
GET /account/static/src/js/tour_bank_statement_reconciliation.js HTTP/1.1" 200 -
GET /account/static/src/js/account_payment_widget.js HTTP/1.1" 200 -
GET /account/static/src/js/account_journal_dashboard_widget.js HTTP/1.1" 200 -
GET /base_import/static/lib/javascript-state-machine/state-machine.js HTTP/1.1" 200 -
GET /base_import/static/src/js/import.js HTTP/1.1" 200 -
GET /bus/static/src/js/bus.js HTTP/1.1" 200 -
GET /im_odoo_support/static/src/js/im_odoo_support.js HTTP/1.1" 200 -
GET /mail/static/src/js/many2many_tags_email.js HTTP/1.1" 200 -
GET /mail/static/src/js/announcement.js HTTP/1.1" 200 -
GET /mail/static/src/js/client_action.js HTTP/1.1" 200 -
GET /mail/static/src/js/chat_window.js HTTP/1.1" 200 -
GET /mail/static/src/js/composer.js HTTP/1.1" 200 -
GET /mail/static/src/js/chat_manager.js HTTP/1.1" 200 -
GET /mail/static/src/js/chatter.js HTTP/1.1" 200 -
GET /mail/static/src/js/thread.js HTTP/1.1" 200 -
GET /mail/static/src/js/systray.js HTTP/1.1" 200 -
GET /mail/static/src/js/window_manager.js HTTP/1.1" 200 -
GET /mail_tip/static/src/js/mail_tip.js HTTP/1.1" 200 -
GET /web_planner/static/src/js/web_planner_backend.js HTTP/1.1" 200 -
GET /report/static/src/js/qwebactionmanager.js HTTP/1.1" 200 -
GET /sales_team/static/src/js/sales_team.js HTTP/1.1" 200 -
GET /sales_team/static/src/js/sales_team_dashboard.js HTTP/1.1" 200 -
GET /web_tip/static/src/js/tip.js HTTP/1.1" 200 -
GET /web_calendar/static/lib/fullcalendar/js/fullcalendar.js HTTP/1.1" 200 -
GET /web_calendar/static/src/js/widgets.js HTTP/1.1" 200 -
GET /web_calendar/static/src/js/web_calendar.js HTTP/1.1" 200 -
GET /web_diagram/static/lib/js/jquery.mousewheel.js HTTP/1.1" 200 -
GET /web_diagram/static/lib/js/raphael.js HTTP/1.1" 200 -
GET /web_diagram/static/src/js/vec2.js HTTP/1.1" 200 -
GET /web_diagram/static/src/js/graph.js HTTP/1.1" 200 -
GET /web_diagram/static/src/js/diagram.js HTTP/1.1" 200 -
GET /web_editor/static/lib/summernote/src/js/core/async.js HTTP/1.1" 200 -
GET /web_editor/static/lib/summernote/src/js/core/func.js HTTP/1.1" 200 -
GET /web_editor/static/lib/summernote/src/js/core/agent.js HTTP/1.1" 200 -
GET /web_editor/static/lib/summernote/src/js/core/list.js HTTP/1.1" 200 -
GET /web_editor/static/lib/summernote/src/js/core/dom.js HTTP/1.1" 200 -
GET /web_editor/static/lib/summernote/src/js/core/key.js HTTP/1.1" 200 -
GET /web_editor/static/lib/summernote/src/js/core/range.js HTTP/1.1" 200 -
GET /web_editor/static/lib/summernote/src/js/editing/Bullet.js HTTP/1.1" 200 -
GET /web_editor/static/lib/summernote/src/js/editing/History.js HTTP/1.1" 200 -
GET /web_editor/static/lib/summernote/src/js/editing/Style.js HTTP/1.1" 200 -
GET /web_editor/static/lib/summernote/src/js/editing/Table.js HTTP/1.1" 200 -
GET /web_editor/static/lib/summernote/src/js/editing/Typing.js HTTP/1.1" 200 -
GET /web_editor/static/lib/summernote/src/js/module/Editor.js HTTP/1.1" 200 -
GET /web_editor/static/lib/summernote/src/js/module/Button.js HTTP/1.1" 200 -
GET /web_editor/static/lib/summernote/src/js/module/Clipboard.js HTTP/1.1" 200 -
GET /web_editor/static/lib/summernote/src/js/module/Codeview.js HTTP/1.1" 200 -
GET /web_editor/static/lib/summernote/src/js/module/DragAndDrop.js HTTP/1.1" 200 -
GET /web_editor/static/lib/summernote/src/js/module/Fullscreen.js HTTP/1.1" 200 -
GET /web_editor/static/lib/summernote/src/js/module/Handle.js HTTP/1.1" 200 -
GET /web_editor/static/lib/summernote/src/js/module/HelpDialog.js HTTP/1.1" 200 -
GET /web_editor/static/lib/summernote/src/js/module/ImageDialog.js HTTP/1.1" 200 -
GET /web_editor/static/lib/summernote/src/js/module/LinkDialog.js HTTP/1.1" 200 -
GET /web_editor/static/lib/summernote/src/js/module/Popover.js HTTP/1.1" 200 -
GET /web_editor/static/lib/summernote/src/js/module/Statusbar.js HTTP/1.1" 200 -
GET /web_editor/static/lib/summernote/src/js/module/Toolbar.js HTTP/1.1" 200 -
GET /web_editor/static/lib/summernote/src/js/Renderer.js HTTP/1.1" 200 -
GET /web_editor/static/lib/summernote/src/js/EventHandler.js HTTP/1.1" 200 -
GET /web_editor/static/lib/summernote/src/js/defaults.js HTTP/1.1" 200 -
GET /web_editor/static/lib/summernote/src/js/summernote.js HTTP/1.1" 200 -
GET /web_editor/static/src/js/summernote.js HTTP/1.1" 200 -
GET /web_editor/static/lib/nearest/jquery.nearest.js HTTP/1.1" 200 -
GET /web_editor/static/src/js/editor.js HTTP/1.1" 200 -
GET /web_editor/static/src/js/rte.js HTTP/1.1" 200 -
GET /web_editor/static/src/js/rte.summernote.js HTTP/1.1" 200 -
GET /web_editor/static/src/js/widgets.js HTTP/1.1" 200 -
GET /web_editor/static/src/js/snippets.editor.js HTTP/1.1" 200 -
GET /web_editor/static/src/js/snippets.options.js HTTP/1.1" 200 -
GET /web_editor/static/src/js/tour.rte.js HTTP/1.1" 200 -
GET /web_editor/static/src/js/transcoder.js HTTP/1.1" 200 -
GET /web_editor/static/src/js/translator.js HTTP/1.1" 200 -
GET /web_editor/static/src/js/backend.js HTTP/1.1" 200 -
GET /web_kanban/static/src/js/kanban_record.js HTTP/1.1" 200 -
GET /web_kanban/static/src/js/kanban_relational.js HTTP/1.1" 200 -
GET /web_kanban/static/src/js/kanban_quick_create.js HTTP/1.1" 200 -
GET /web_kanban/static/src/js/kanban_column.js HTTP/1.1" 200 -
GET /web_kanban/static/src/js/kanban_view.js HTTP/1.1" 200 -
GET /web_kanban/static/src/js/kanban_widgets.js HTTP/1.1" 200 -
GET /web_kanban/static/src/js/compatibility.js HTTP/1.1" 200 -
GET /web_kanban_gauge/static/lib/justgage/justgage.js HTTP/1.1" 200 -
GET /web_kanban_gauge/static/src/js/kanban_gauge.js HTTP/1.1" 200 -
GET /web_view_editor/static/src/js/view_editor.js HTTP/1.1" 200 -
GET /web_settings_dashboard/static/src/js/dashboard.js HTTP/1.1" 200 -
POST /web/dataset/call HTTP/1.1" 200 -
GET /web_editor/static/src/xml/editor.xml?debug=1457629949762 HTTP/1.1" 200 -
POST /web/dataset/call_kw/ir.model.data/xmlid_to_res_id HTTP/1.1" 200 -
GET /web_editor/static/src/xml/snippets.xml?debug=1457629949928 HTTP/1.1" 200 -
POST /web/dataset/call_kw/ir.model.data/xmlid_to_res_id HTTP/1.1" 200 -
GET /mail/static/src/audio/ting.ogg HTTP/1.1" 200 -
POST /mail/client_action HTTP/1.1" 200 -
GET /web_editor/static/src/xml/translator.xml?debug=1457629950020 HTTP/1.1" 200 -
POST /web/webclient/translations HTTP/1.1" 200 -
POST /mail/chat_init HTTP/1.1" 200 -
2016-03-10 17:12:30,568 2226 INFO proto00 openerp.service.common: successful login from 'admin' using database 'proto00'
POST /web/session/get_session_info HTTP/1.1" 200 -
POST /web/proxy/load HTTP/1.1" 200 -
POST /web/session/modules HTTP/1.1" 200 -
POST /web/dataset/search_read HTTP/1.1" 200 -
POST /web/webclient/translations HTTP/1.1" 200 -
POST /web/dataset/call_kw/res.users/read HTTP/1.1" 200 -
POST /web/dataset/search_read HTTP/1.1" 200 -
POST /web/dataset/search_read HTTP/1.1" 200 -
GET /web/image?model=res.users&field=image_small&id=1 HTTP/1.1" 200 -
POST /web/dataset/call_kw/res.users/read HTTP/1.1" 200 -
POST /web/action/load HTTP/1.1" 200 -
POST /web/menu/load_needaction HTTP/1.1" 200 -
POST /web/dataset/call_kw/mail.message/fields_view_get HTTP/1.1" 200 -
POST /web/dataset/call_kw/mail.message/fields_get HTTP/1.1" 200 -
POST /web/dataset/call_kw/ir.filters/get_filters HTTP/1.1" 200 -
POST /web/dataset/call_kw/mail.message/message_fetch HTTP/1.1" 200 -
POST /longpolling/poll HTTP/1.1" 200 -
```

**Comment by aznnoh** [comment] 2016-03-10 21:36
same issue

**Comment by newnectar** [comment] 2016-05-22 06:18
Same observation here. Any update?

**Comment by sle-odoo** [comment] 2016-06-08 13:35
Hello,
Could you please use official installers on nightly.doo.com? Also, odoo.py --update does not work if you do not specify a database with the -d argument.

**Comment by manisho2b** [comment] 2017-09-18 11:27
kjk

**Comment by pedrobaeza** [comment] 2018-04-17 23:47
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-04-17 23:47 UTC
Labels: Blocked
