### ISSUE TITLE
ImportError: cannot import name 'objectify'

### ISSUE THREAD

**Issue by deyvsonaguiar** [odoo/odoo#21820] opened 2017-12-23 02:20 UTC
An error occure in version 11.0;

```
2017-12-23 02:16:21,390 54561 INFO ? odoo: Odoo version 11.0
2017-12-23 02:16:21,391 54561 INFO ? odoo: addons paths: ['/root/.local/share/Odoo/addons/11.0', '/opt/odoo/odoo/addons', '/opt/odoo/addons']
2017-12-23 02:16:21,392 54561 INFO ? odoo: database: default@default:default
2017-12-23 02:16:21,427 54561 INFO ? odoo.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
2017-12-23 02:16:22,197 54561 INFO ? odoo.addons.base.ir.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
2017-12-23 02:16:36,938 54561 INFO ? werkzeug: 191.217.40.74 - - [23/Dec/2017 02:16:36] "GET /web/database/manager HTTP/1.1" 500 -
2017-12-23 02:16:36,953 54561 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.4/dist-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/odoo/service/server.py", line 252, in app
    return self.app(e, s)
  File "/opt/odoo/odoo/service/wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/odoo/http.py", line 1297, in __call__
    self.load_addons()
  File "/opt/odoo/odoo/http.py", line 1319, in load_addons
    m = __import__('odoo.addons.' + module)
  File "/opt/odoo/odoo/modules/module.py", line 82, in load_module
    exec(open(modfile, 'rb').read(), new_mod.__dict__)
  File "<string>", line 4, in <module>

  File "/opt/odoo/addons/payment_authorize/models/__init__.py", line 2, in <module>
    from . import payment
  File "/opt/odoo/addons/payment_authorize/models/payment.py", line 4, in <module>
    from .authorize_request import AuthorizeAPI
  File "/opt/odoo/addons/payment_authorize/models/authorize_request.py", line 4, in <module>
    from lxml import etree, objectify
ImportError: cannot import name 'objectify'
```

**Comment by Yenthe666** [comment] 2017-12-27 09:53
Hi @deyvsonaguiar,

Thank you for your report.
Are you sure you've installed all dependencies from https://github.com/odoo/odoo/blob/11.0/requirements.txt and that they're up to date?

**Comment by deyvsonaguiar** [comment] 2017-12-27 10:55
yes, but not start.

**Comment by Yenthe666** [comment] 2017-12-27 10:56
Euhm? What do you mean with
> yes, but not start.

That doesn't really answer anything.

**Comment by mart-e** [comment] 2020-01-14 07:43
It is most likely a bad version of lxml that is installed. The requirements (cf link given by Yenthe) asks for `3.7.1` or `4.2.3` (based on the python version).
Closing as installation problem, not a bug in Odoo

**Closed by mart-e** 2020-01-14 07:43 UTC
Labels: 11.0
