### ISSUE TITLE
[11.0] custom template xml KeyError: 'odoo' 

### ISSUE THREAD

**Issue by dantvalan** [odoo/odoo#20772] opened 2017-11-07 15:42 UTC
Impacted versions:11.0

Steps to reproduce: Create a specific page layout
when i set the attribute **page="True"** in tag template the Error appears.
`<odoo>
  <template name="Services page" id="website.services" page="True">
    <t t-call="website.layout">
      <div id="wrap">
        <div class="container">
          <h1>Hola!!!</h1>
        </div>
        
        <div class="oe_structure" />
      </div>
    </t>
  </template>
  <record id="services_page_link" model="website.menu">
    <field name="name">Services</field>
    <field name="url">/page/services</field>
    <field name="parent_id" ref="website.main_menu" />
    <field name="sequence" type="int">99</field>
  </record>
</odoo>`

Current behavior: Element odoo has extra content: template

Expected behavior: load my template

Video/Screenshot link (optional): 
![error odoo](https://user-images.githubusercontent.com/11239566/32502204-b9816702-c39f-11e7-9c23-804359a815ff.png)

**Comment by Yenthe666** [comment] 2017-11-07 15:45
Hi @dantvalan,

You can remove the `page="True"` parameter and it'll work just fine? You can set the page=True parameter in the controller 😉

**Comment by dantvalan** [comment] 2017-11-07 15:58
Hi @Yenthe666 yes i can remove the parameter and the error dissappear, but the template not work fine. Where is the controller?. 
I only have this files __init__.py is empty , __manifest__.py  is a dict, views and statics files

**Comment by Yenthe666** [comment] 2017-11-07 15:59
Hi @dantvalan,

Have you ever made webpages & controllers in Odoo? Please have a look at https://www.odoo.com/documentation/10.0/howtos/website.html 😉

**Comment by dantvalan** [comment] 2017-11-07 20:58
@Yenthe666 you were right, now can you help me, i dont know where add my own styles css?

**Comment by nehemiascr** [comment] 2017-11-07 21:59
I encounter the same issue by following the [theme tutorial for odoo 11](https://www.odoo.com/documentation/11.0/howtos/themes.html#create-a-specific-page-layout), is @Yenthe666 solution a workaround or is it the way to go in odoo 11? thanks.

**Comment by Yenthe666** [comment] 2017-11-08 06:03
I think it was done by design. @JKE-be can you confirm this?
And @dantvalan you can do this by adding the CSS files to the Odoo assets with an xpath. It should be in the documentation too.

**Comment by Yenthe666** [comment] 2017-12-06 13:18
Hi @dantvalan,

I'm closing this bug report in favour of https://github.com/odoo/odoo/issues/21243
It has been confirmed there and it is desired behaviour.
In short: don't use `page=True` and the documentation will be adjusted accordingly.

**Closed by Yenthe666** 2017-12-06 13:18 UTC
