### ISSUE TITLE
can't understand the diffenerence between 'active_id' and 'id' odoo 14

### ISSUE THREAD

**Issue by Amchakkah** [odoo/odoo#77665] opened 2021-10-02 10:58 UTC
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by omalbastin** [comment] 2021-10-02 12:29
id:  id of a record in a table
active_id: active_id and active_ids are mainly in views. In form view, active_id contains the id of the record that is opened and in tree view or kanban view, active_ids contain the list of record ids that are selected and the active_id contain the first/last(not sure) record we have selected

Hope this helps. please try to put doubts in odoo help forum.

**Comment by Amchakkah** [comment] 2021-10-02 12:37
Well, I'm trying to work with active_id. I'm trying to create a reject comment. I'm trying to update the current record with the comment. when using active_id, to get the current id, I get error record deleted, User()...

**Comment by hoangtrann** [comment] 2021-10-03 10:28
This should be a question on https://www.odoo.com/forum/help-1

In short, ID is the `id` of a record in the database table. Active ID/IDs is the one(s) showing on the form/list view. If you are popping up a wizard from a form view, or by selecting a list of records in the list view, the active ID/IDs contains the ID of record in that form view or selected records on list view. Also, there is `active_model` going along with them

**Comment by Yenthe666** [comment] 2021-10-04 06:02
Yep, closing as not a bug but a question :)

**Closed by Yenthe666** 2021-10-04 06:02 UTC
