### ISSUE TITLE
[11.0] New setup install sock app error

### ISSUE THREAD

**Issue by duybq86** [odoo/odoo#31124] opened 2019-02-15 03:31 UTC
Traceback (most recent call last):
  File "C:\Odoo11\odoo\models.py", line 1037, in _validate_fields
    check(self)
  File "C:\Odoo11\odoo\addons\base\ir\ir_ui_view.py", line 342, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "C:\Odoo11\odoo\addons\base\ir\ir_ui_view.py", line 1077, in postprocess_and_fields
    self.raise_view_error("\n".join(msg_lines), view_id)
  File "C:\Odoo11\odoo\addons\base\ir\ir_ui_view.py", line 519, in raise_view_error
    raise ValueError(message)
ValueError: Field 'company_id' used in attributes must be present in view but is missing:
 - 'company_id' in domain="['|', ('company_id', '=', company_id), ('company_id', '=', False)]"
 - 'company_id' in domain="['|', ('company_id', '=', company_id), ('company_id', '=', False)]"

Error context:
View `Operation Types`
[view_id: 377, xml_id: n/a, model: stock.picking.type, parent_id: n/a]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Odoo11\odoo\tools\convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "C:\Odoo11\odoo\tools\convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "C:\Odoo11\odoo\addons\base\ir\ir_model.py", line 1493, in _update
    record = record.create(values)
  File "C:\Odoo11\odoo\addons\base\ir\ir_ui_view.py", line 408, in create
    return super(View, self).create(self._compute_defaults(values))
  File "C:\Odoo11\odoo\models.py", line 3402, in create
    self._fields[key].determine_inverse(record)
  File "C:\Odoo11\odoo\fields.py", line 1073, in determine_inverse
    getattr(records, self.inverse)()
  File "C:\Odoo11\odoo\addons\base\ir\ir_ui_view.py", line 273, in _inverse_arch
    view.write(data)
  File "C:\Odoo11\odoo\addons\base\ir\ir_ui_view.py", line 424, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "C:\Odoo11\odoo\models.py", line 3109, in write
    self._write(old_vals)
  File "C:\Odoo11\odoo\models.py", line 3277, in _write
    self._validate_fields(vals)
  File "C:\Odoo11\odoo\models.py", line 1041, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error while validating constraint\n\nField \'company_id\' used in attributes must be present in view but is missing:\n - \'company_id\' in domain="[\'|\', (\'company_id\', \'=\', company_id), (\'company_id\', \'=\', False)]"\n - \'company_id\' in domain="[\'|\', (\'company_id\', \'=\', company_id), (\'company_id\', \'=\', False)]"\n\nError context:\nView `Operation Types`\n[view_id: 377, xml_id: n/a, model: stock.picking.type, parent_id: n/a]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Odoo11\odoo\http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Odoo11\odoo\http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Odoo11\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "C:\Odoo11\odoo\http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "C:\Odoo11\odoo\http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Odoo11\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Odoo11\odoo\http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Odoo11\odoo\http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "C:\Odoo11\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "C:\Odoo11\addons\web\controllers\main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "C:\Odoo11\addons\web\controllers\main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Odoo11\odoo\api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "C:\Odoo11\odoo\api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-42>", line 2, in button_immediate_install
  File "C:\Odoo11\odoo\addons\base\module\module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "C:\Odoo11\odoo\addons\base\module\module.py", line 449, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "C:\Odoo11\odoo\addons\base\module\module.py", line 543, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "C:\Odoo11\odoo\modules\registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "C:\Odoo11\odoo\modules\loading.py", line 380, in load_modules
    loaded_modules, update_module, models_to_check)
  File "C:\Odoo11\odoo\modules\loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "C:\Odoo11\odoo\modules\loading.py", line 181, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "C:\Odoo11\odoo\modules\loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "C:\Odoo11\odoo\tools\convert.py", line 791, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "C:\Odoo11\odoo\tools\convert.py", line 852, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "C:\Odoo11\odoo\tools\convert.py", line 751, in parse
    exc_info[2]
  File "C:\Odoo11\odoo\tools\pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "C:\Odoo11\odoo\tools\convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "C:\Odoo11\odoo\tools\convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "C:\Odoo11\odoo\addons\base\ir\ir_model.py", line 1493, in _update
    record = record.create(values)
  File "C:\Odoo11\odoo\addons\base\ir\ir_ui_view.py", line 408, in create
    return super(View, self).create(self._compute_defaults(values))
  File "C:\Odoo11\odoo\models.py", line 3402, in create
    self._fields[key].determine_inverse(record)
  File "C:\Odoo11\odoo\fields.py", line 1073, in determine_inverse
    getattr(records, self.inverse)()
  File "C:\Odoo11\odoo\addons\base\ir\ir_ui_view.py", line 273, in _inverse_arch
    view.write(data)
  File "C:\Odoo11\odoo\addons\base\ir\ir_ui_view.py", line 424, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "C:\Odoo11\odoo\models.py", line 3109, in write
    self._write(old_vals)
  File "C:\Odoo11\odoo\models.py", line 3277, in _write
    self._validate_fields(vals)
  File "C:\Odoo11\odoo\models.py", line 1041, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error while validating constraint

Field 'company_id' used in attributes must be present in view but is missing:
 - 'company_id' in domain="['|', ('company_id', '=', company_id), ('company_id', '=', False)]"
 - 'company_id' in domain="['|', ('company_id', '=', company_id), ('company_id', '=', False)]"

Error context:
View `Operation Types`
[view_id: 377, xml_id: n/a, model: stock.picking.type, parent_id: n/a]
None" while parsing file:/C:/Odoo11/addons/stock/views/stock_picking_views.xml:28, near
<record model="ir.ui.view" id="view_picking_type_form">
            <field name="name">Operation Types</field>
            <field name="model">stock.picking.type</field>
            <field name="arch" type="xml">
                <form string="Operation Types">
                    <sheet>
                        <div class="oe_button_box" name="button_box">
                            <button name="toggle_active" type="object" class="oe_stat_button" icon="fa-archive">
                                <field name="active" widget="boolean_button" options="{&quot;terminology&quot;: &quot;archive&quot;}"/>
                            </button>
                        </div>
                        <group>
                            <group>
                                <field name="name"/>
                                <field name="sequence_id"/>
                                <field name="warehouse_id" groups="stock.group_stock_multi_warehouses"/>
                            </group>
                            <group>
                                <field name="code"/>
                                <field attrs="{&quot;invisible&quot;: [(&quot;code&quot;, &quot;not in&quot;, [&quot;incoming&quot;, &quot;outgoing&quot;, &quot;internal&quot;])]}" name="return_picking_type_id"/>
                                <field attrs="{&quot;invisible&quot;: [(&quot;code&quot;, &quot;not in&quot;, [&quot;incoming&quot;, &quot;outgoing&quot;, &quot;internal&quot;])]}" name="barcode_nomenclature_id" groups="base.group_no_one"/>
                                <field name="show_operations"/>
                                <field name="show_reserved" attrs="{'invisible': [('show_operations', '!=', False)]}"/>
                            </group>
                        </group>
                        <group>
                            <group attrs="{&quot;invisible&quot;: [(&quot;code&quot;, &quot;not in&quot;, [&quot;incoming&quot;, &quot;outgoing&quot;, &quot;internal&quot;])]}" string="Packs and Lots" groups="stock.group_tracking_lot,stock.group_production_lot">
                                <field name="show_entire_packs" groups="stock.group_tracking_lot"/>
                                <field name="use_create_lots" groups="stock.group_production_lot"/>
                                <field name="use_existing_lots" groups="stock.group_production_lot"/>
                            </group>
                            <group string="Locations" groups="stock.group_stock_multi_locations">
                                <field name="default_location_src_id" attrs="{'required': [('code', '=', 'internal')]}" domain="['|', ('company_id', '=', company_id), ('company_id', '=', False)]"/>
                                <field name="default_location_dest_id" attrs="{'required': [('code', 'in', ('internal', 'incoming'))]}" domain="['|', ('company_id', '=', company_id), ('company_id', '=', False)]"/>
                            </group>
                        </group>
                    </sheet>
                </form>
            </field>
        </record>

**Comment by Yenthe666** [comment] 2019-02-15 07:16
Hi,

Are you sure your Odoo is up to date and that you have no third party modules? It seems to work fine in the latest 11.0
Can you reproduce it on runbot.odoo.com?

**Comment by duybq86** [comment] 2019-02-15 07:52
i installed from lastet source github. While i delete that source and replace from old source ,it's ok.

**Comment by Yenthe666** [comment] 2019-02-15 08:17
Looks like a view you have is not updated correctly. Did you do a `-u` for the modules? Are you sure your views are not set as `No update` by yourself or that you've manually changed the view?

**Comment by pedrobaeza** [comment] 2019-02-15 08:20
This is a regression that should be fixed with #31121

**Comment by Yenthe666** [comment] 2019-02-15 08:24
Good find Pedro, thanks!

**Comment by pedrobaeza** [comment] 2019-02-17 19:15
This was fixed directly in 287e0507f1f6a6d2e89d373b48bc3e380bd93b96, so we can close this.

**Closed by pedrobaeza** 2019-02-17 19:15 UTC
Labels: 11.0, Confirmed, Logistics
