### ISSUE TITLE
[12.0] Create a new Mailing error

### ISSUE THREAD

**Issue by jmem2019** [odoo/odoo#58363] opened 2020-09-23 14:59 UTC
Impacted versions:
12.0

Steps to reproduce:
1. Go to mass mailing
2. Create a new Mailing
3. Select any template and save

Current behavior:
An Odoo Client Error

Expected behavior:
Normal save without any issue

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/47604144/94030261-ff17ef80-fd93-11ea-8fcf-6060e3366fbb.png)

**Comment by pedrobaeza** [comment] 2020-09-23 15:12
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by jmem2019** [comment] 2020-09-23 15:56
Hi,

The test was made in runbot as the screenshot reveals.

The error is just what it was reported. It seems that there is a problem with the templates available within the mass mailing module.

Best regards.

**Comment by pedrobaeza** [comment] 2020-09-23 17:03
I have just tried with no problem:
![Peek 23-09-2020 19-02](https://user-images.githubusercontent.com/7165771/94045209-6ef79b80-fdcf-11ea-88c0-54f3450085ca.gif)
Closing meanwhile no further steps to reproduce the problem are provided.

**Closed by pedrobaeza** 2020-09-23 17:03 UTC
Labels: Need information
