### ISSUE TITLE
[11.0] Trace back while checking "Show technical modules" On module uninstallation page.

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#20240] opened 2017-10-17 09:02 UTC
Impacted versions: 11.0

Steps to reproduce: [http://271352-11-0-mrpfix-bng-3315c7.runbot13.odoo.com](http://271352-11-0-mrpfix-bng-3315c7.runbot13.odoo.com) Active Developer mode --> Apps --> Module's Form View--> Click Uninstall --> Check Show technical modules
![1](https://user-images.githubusercontent.com/16624719/31655849-cda05b52-b347-11e7-8c98-c152961f02b5.png)
![2](https://user-images.githubusercontent.com/16624719/31655859-d40abf78-b347-11e7-8cd3-47d2e0e98ae7.png)
Same Error while changing module.
![4](https://user-images.githubusercontent.com/16624719/31656287-c4030594-b348-11e7-9433-0fde6e041e7e.png)
 
Current behavior: Throws trace back
![3](https://user-images.githubusercontent.com/16624719/31655871-daab1c4c-b347-11e7-8604-7e890fcd3265.png)
Expected behavior: Should Show technical modules.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment] 2017-10-17 12:13
Hi @sswapnesh,

Thank you for your report. I can confirm that this is a bug.
@xmo-odoo could I ask you to have a look?

**Comment by xmo-odoo** [comment] 2017-10-17 13:03
That's more @Elkasitu 's bailiwick.

**Comment by Elkasitu** [comment] 2017-10-18 14:10
bisect shows bug was introduced in rev 1da064a, will have to check further since it's a forward-port

**Comment by Elkasitu** [comment] 2017-10-19 07:26
@ged-odoo

**Comment by ged-odoo** [comment] 2017-10-19 07:35
i'm on it

**Comment by ged-odoo** [comment] 2017-10-19 09:00
fix is merged: https://github.com/odoo/odoo/commit/d8f03e64fd46f45446c69f6b851813c559d0d5c7

**Comment by ged-odoo** [comment] 2017-10-19 09:00
(in saas-16). will be forwardported shortly in v11/master

**Closed by ged-odoo** 2017-10-19 09:00 UTC
Labels: 11.0, confirmed
