### ISSUE TITLE
Uncaught TypeError: Cannot read property 'attrs' of undefined

### ISSUE THREAD

**Issue by batzaya** [odoo/odoo#21248] opened 2017-11-27 06:06 UTC
@Yenthe666 How to fix this error???? this error open "project.task" gantt view odoo 10 community
![image](https://user-images.githubusercontent.com/4206565/33252854-89138d48-d37b-11e7-818c-f73699df6ee8.png)

**Comment by Yenthe666** [comment] 2017-11-27 07:36
Hi @batzaya,

Sorry saw the other report first.
Have you updated your Odoo to the latest source code? Can you reproduce it on an official runbot instance (at runbot.odoo.com)? How can we reproduce it?

Regards,
Yenthe

**Comment by Yenthe666** [comment] 2017-12-27 14:19
Hi there,

As there has been no feedback on the questions and as I cannot reproduce it I'm closing this bug report.
If you can still reproduce it on an official runbot then please post back and I'll reopen this.

Regards,
Yenthe

**Closed by Yenthe666** 2017-12-27 14:19 UTC
Labels: 10.0, need information

**Comment by khoaphandct** [comment] 2018-04-09 15:08
@Yenthe666 : The step to reproduce is:
1. Install web_gantt (migrating module 9.0 to 10.0)
2. Code Gantt view for Project Task in my custom module as following code:
```xml
<record id="project.action_view_task" model="ir.actions.act_window">
			<field name="name">Tasks</field>
			<field name="view_mode">kanban,tree,form,calendar,gantt,pivot,graph</field>
		</record>
		<record id="project_gantt_view" model="ir.ui.view">
			<field name="name">project.task.gantt</field>
			<field name="type">gantt</field>
			<field name="model">project.task</field>
			<field name="arch" type="xml">
				<gantt date_start="" date_stop="date_deadline" progress="progress"
					string="Tasks" default_group_by="project_id" />
			</field>
		</record>
```
3. Click on Gantt Button in Task View as following picture
![screenshot from 2018-04-09 22-06-58](https://user-images.githubusercontent.com/34157654/38505843-62198f1e-3c42-11e8-946e-f2c16d8e7417.png)
4. Error pop as @batzaya 's picture

Please help me with the problem. Thanks

**Comment by Yenthe666** [comment] 2018-04-09 15:32
@khoaphandct migrating a module is at own risk though, that doesn't fall under default odoo
