### ISSUE TITLE
[11.0] ERROR: null value in column "module_id" violates not-null constraint when deleting module

### ISSUE THREAD

**Issue by NothingCtrl** [odoo/odoo#20720] opened 2017-11-06 09:45 UTC
Impacted versions: 11c, 11e

Steps to reproduce: Install module, uninstall it, then go to action choise delete module (tested with some module: Automated Translations through Gengo API, Vietnam - Accounting...)

Current behavior:
Popup error:
```
The operation cannot be completed, probably due to the following:
- deletion: you may be trying to delete a record while other records still reference it
- creation/update: a mandatory field is not correctly set

[object with reference: Module Uninstallation - base.module.uninstall]
```
--
logs:
```
ERROR: null value in column "module_id" violates not-null constraint
DETAIL:  Failing row contains (1, t, null, 1, 2017-11-06 09:26:04.803957, 1, 2017-11-06 09:26:04.803957).
CONTEXT:  SQL statement "UPDATE ONLY "public"."base_module_uninstall" SET "module_id" = NULL WHERE $1 OPERATOR(pg_catalog.=) "module_id""
```

If module is not installed before, no error occurs

Expected behavior: the module should delete normally

**Comment by Elkasitu** [comment] 2017-11-06 10:37
@NothingCtrl Hi, I confirm that this happens on the runbot for v11, however I'm not sure of the use cases where this would be a problem? Could you provide me with some examples? I don't want to introduce changes into the ORM if the bug isn't blocking or doesn't have any real-world consequences, I am marking this as wontfix for now

**Comment by NothingCtrl** [comment] 2017-11-06 13:21
@Elkasitu Hi, I just test some module (in development) then this error happens, so I report the bug :), it isn't blocking but I think some detail-oriented person (ex: me) may feel inconvenienced when some function not working as it should.

Regards,
T.

**Comment by Elkasitu** [comment] 2017-11-07 06:55
@NothingCtrl I understand, however I don't see an scenario where anyone would need to delete a module, still, I'll look around and see what I can dig up

**Comment by Yenthe666** [comment] 2017-11-07 07:13
@Elkasitu,

Do you really? Deleting modules happens rather often to be honest. For example: when I've developed a whole module I install it, deinstall it and install it again (on a test instance) to be 100% sure there are no issues. In this case I might already run into this problem 😉 
I believe we should treat this like a bug. Although not a lot of people might do this it is a quite big issue when you do it.

**Comment by Elkasitu** [comment] 2017-11-07 09:13
@Yenthe666 Maybe I understood you wrong but delete != uninstall, in this case deleting the module means going to apps > selecting tree view > checking the checkboxes of the apps you want to delete > selecting the "delete" contextual action and then those apps are deleted from ir_modules, which basically means you won't see them in the list of apps that can be installed/uninstalled/upgraded.

In your example, you install, uninstall and reinstall your module on a test DB, that works fine ( in theory ;) ), and I see why someone would want to do that, what I don't understand is why someone would want to delete the app from the registry, effectively making it impossible to install/uninstall/upgrade the deleted app.

For me this delete action is destructive and irreversible for a user, and makes no sense, maybe it should be completely removed from the apps tree view, but again, if you can provide me with a real-world use case I might be able to look into it, but for now it's a non-blocking issue, I might talk to rco about it and ask him what he thinks

**Comment by Yenthe666** [comment] 2017-11-07 09:25
Hi @Elkasitu,

Thanks a lot for the extra information. I was actually under a wrong assumption here. I was thinking about uninstalling them app and was seeing this as deleting. 
Judging by this whole thread and your last feedback I genuinely wonder why we actually have the option to delete an app from the app registry list. What good purpose or use does this have? Perhaps a removal wouldn't be to bad after all..
Anyways, I wouldn't see this as a blocking issue indeed.

**Comment by Karsten-77** [comment] 2017-11-20 18:10
Hi!
For developers there are some reasons for deleting modules. Sometimes you move them to another directory and want to delete the references to old path from db. Other times you prepare a database for customer, but not wanted that obsolete references of only local modules are still in when giving it to production.
Deleting a module from ir_modules doesnt mean, that you not can reinstall when it is in an included path and you Update your modules from apps.
Just my opinion. I use deleting.

Regards.

**Comment by Elkasitu** [comment] 2017-11-21 08:26
@Karsten-77 Hi, thank you for your input, I've gone ahead and fixed it in PR #21111 you can patch your instance locally and try it out if you want to :smile:

**Closed by Elkasitu** 2017-11-21 08:26 UTC
Labels: Framework, wontfix

**Comment by marcos-mendez** [comment] 2020-11-21 21:34
@Elkasitu please re-open this as this is still happening in v12

**Comment by Elkasitu** [comment] 2020-11-23 10:51
@marcos-mendez cannot reproduce on v12 runbot
