### ISSUE TITLE
Reconcile account voucher line : Wrong comparison on float - Account precision should be used

### ISSUE THREAD

**Issue by sarac2013** [odoo/odoo#7884] opened 2015-08-04 21:59 UTC
Hi,
Line 810 of account_voucher/account_voucher.py file.
if rs['amount_unreconciled'] == rs['amount']:
                rs['reconcile'] = True
The comparaison doesn't care about precision. As example If an account move line to reconcile has credit amount =15416.05. So the comparison between 15616.05 and 15416.05000000001.
This problem came from the value set in the cache after reading the value from the database using float_round method. (see convert_to_cache) method of fields.Float class.

PATCH:
Replace 
if rs['amount_unreconciled'] == rs['amount']:
                rs['reconcile'] = True
With 
precision_digits = self.pool.get('decimal.precision').precision_get(cr, uid, 'Account')
if float_compare(rs['amount_unreconciled'], rs['amount'], precision_digits=precision_digits) == 0:
                rs['reconcile'] = True

**Comment by csnauwaert** [comment] 2018-02-28 16:04
Hello,

It would seems that this issue is related to v8, since v8 is not supported anymore, I'm closing this issue. If you can reproduce it in a later version don't hesitate to comment so that I can reopen it.

Best regards

**Closed by csnauwaert** 2018-02-28 16:04 UTC
Labels: 9.0, Accounting
