### ISSUE TITLE
<progressbar in kanban  KeyError: 'fieldname' after nighty 20210702 

### ISSUE THREAD

**Issue by justzxw** [odoo/odoo#76136] opened 2021-09-08 05:28 UTC
Impacted versions: 13.0

Steps to reproduce: <progressbar field='xxxx'

Current behavior:KeyError: 'fieldname'

Expected behavior:

Video/Screenshot link (optional):
错误:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/local/lib/python3.6/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/local/lib/python3.6/dist-packages/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/usr/local/lib/python3.6/dist-packages/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/local/lib/python3.6/dist-packages/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/odoo/addons/web/controllers/main.py", line 1339, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/odoo/addons/web/controllers/main.py", line 1331, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/odoo/api.py", line 383, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/odoo/api.py", line 356, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/odoo/addons/web/models/models.py", line 156, in read_progress_bar
    field_value = group[progress_bar['field']]
KeyError: 'read_state'
Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment] 2021-09-08 06:55
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Closed** 2023-04-07 12:46 UTC
Labels: Need information
