### ISSUE TITLE
[10/11/12] default_focus doesn't work in wizard

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#29589] opened 2018-12-17 17:49 UTC
default_focus="1" doesn't have any effect in the form view of wizards.

Here is a scenario to reproduce the bug:
1) in the wizard account.invoice.create, the button "Confirm" has default_focus="1", cf https://github.com/odoo/odoo/blob/10.0/addons/account/wizard/account_invoice_state_view.xml#L16 (on v11 and v12, the confirm button also has default_focus="1").
2) Connect to runbot v10, v11 or v12 as admin
3) Go to the menu "Accounting > Customer Invoices"
4) Select several invoices and click on "Action > Confirm Draft Invoices"

I also experience this problem when settings default_focus in the char field of a wizard (tested on v10).

It would be really useful to be able to set default_focus in the form view of a wizard !

**Comment by hugho-ad** [comment] 2019-11-05 01:39
What's the status of this?
We begin affected by this issue
OPW 2119143

**Comment by kebeclibre** [comment] 2019-11-12 15:32
I believe this issue is more of a feedback than a bug
the lines https://github.com/odoo/odoo/blame/b3c539b09a0bd462309a10c565cb91375a7011b9/addons/web/static/src/js/views/form/form_renderer.js#L60 are pretty much explicit. Only in readonly can we have focus on a button.
The default_focus in the form view of account.invoice.confirm is admittedly useless, as this attribute only works on fields by design.

In v11.0, focusing in a button in readonly is not supported
v10 is not supported anymore as a whole

the focus being stolen by html field has been fixed in 11.0 at https://github.com/odoo/odoo/pull/26582

**Closed by kebeclibre** 2019-11-12 15:32 UTC
Labels: 10.0, 11.0, 12.0, Framework

**Comment by hugho-ad** [comment] 2019-11-12 15:43
@kebeclibre 

default_focus on wizard's fields also is not working. should you try it, please

you need we open a new issue?

regards!

**Comment by kebeclibre** [comment] 2019-11-12 16:02
Yes it does work in v11.0
As I said, v10.0 is not supported anymore

**Comment by hugho-ad** [comment] 2019-11-12 16:19
You right, it's working on v11.0 on desktop, but not in mobile, see the following video made it on the last runbot instance from v11.0
https://youtu.be/P26dSBCXhys

regards!

**Comment by kebeclibre** [comment] 2019-11-12 16:35
https://github.com/odoo/enterprise/commit/6e94c3179b4890bab17cd419990e0755e033777f
Desired behavior

**Comment by hugho-ad** [comment] 2019-11-12 16:38
Thanks!
