### ISSUE TITLE
[8.0] payment transaction not created while payment from backend

### ISSUE THREAD

**Issue by ajayjaviya** [odoo/odoo#4490] opened 2015-01-01 09:21 UTC
Impacted versions:
8.0 and above

step to reproduce :
1) create and conform the sale order
2) now payment acquire button will appear
3) click payment acquire button eg. paypal and complete payment
4) go to settings > payment > payment transactions

Current behavior:
Payment transactions is not created and if we payment using other payment acquire except paypal then it will gives an Internal Server Error

Reason:
After completing a payment payment gateway redirect customer with payment transaction detail on murchant website(return url), controller will search reference transaction(payment.transaction) in case of paypal if reference transaction is not found(payment transaction is  not created while payment from backend) then it add `_logger.warning('Paypal: answered INVALID on data verification')` while in other case (buckaroo , ongone , adyen) it gives `ValidationError: acquire name: received data for reference SO0XX; no order found`

Note :if we perform payment from front end (website) payment transaction is created

**Comment by nicolas-pantel** [comment] 2015-05-21 08:04
We have the same problem, but from front end with Ogone.

Back to our website from Ogone payment (validated), a 500 error is raised. In the logs, we have the `ValidationError: acquire name: received data for reference SOxxx; no order found.`

**Comment by zbik2607** [comment] 2015-06-17 20:08
+1

**Comment by dlasley** [comment] 2015-06-19 02:41
This is affecting my instance as well. I circumvented it by adding code to create a draft transaction if one does not exist, but that seems like a bad solution.

**Comment by stephen144** [comment] 2015-11-03 19:54
+1

@lasley I can't tell what happened to your commit, but I'm guessing you went with the fix in in the [laslabs module](https://github.com/laslabs/odoo-payment_authorize_auto_reconcile)?

**Comment by lasley** [comment] 2015-11-03 22:04
Yup I ended up using the code in https://github.com/odoo/odoo/commit/844e8ac158d873cdab6cb8380f425087cebe4eb1 for a while. 

I also ended up writing a plugin that incorporates this fix, as well as automatically applying the payment to invoices - https://github.com/laslabs/odoo-payment_authorize_auto_reconcile

-Dave Lasley

**Comment by Softdil** [comment] 2017-06-08 10:31
@lasley I know this issue is a bit old, but i'm having same problem as @ajayjaviya 
Are payments made from acquire button in the sales order supposed to confirm the order? The problem is that no payment transaction is created when you make the payment. I have Redsys configured and it's working perfectly fine except that it won't confirm the order since no payment transaction is created.

As @ajayjaviya pointed, if you create it through website it works fine.

**Comment by lasley** [comment] 2017-06-08 15:27
@Softdil - You nailed the issue on the head. If you take a look at the solution in [our module](https://github.com/LasLabs/odoo-payment/tree/release/8.0/payment_authorize_auto_reconcile) you'll see that we simply [create the payment transaction](https://github.com/LasLabs/odoo-payment/blob/release/8.0/payment_authorize_auto_reconcile/models/payment_transaction.py#L62) after receiving a response from the acquirer, then [create and complete a voucher](https://github.com/LasLabs/odoo-payment/blob/release/8.0/payment_authorize_auto_reconcile/models/payment_transaction.py#L97) upon transaction success.

The real solution IMO Is upgrading to Odoo v10, where this is handled elegantly and completely via core.

**Comment by Softdil** [comment] 2017-06-08 15:49
@lasley so, creating a voucher will only help to get an invoice marked as paid but... what about confirming a 'sent' state sale order? Is it possible? Customers can pay 'sent' orders when logging through the portal but order won't get confirmed automatically.

**Comment by lasley** [comment] 2017-06-08 16:09
Our module does not handle sales, which is actually what broke it in v9. We did some work towards this goal (and PayPal too) in [this branch](https://github.com/laslabs/odoo-payment/tree/feature/9.0/LABS-101-create-payment_paypal_auto_reconcile), but it doesn't work last I remember. 

v10 had come out by the time we were solving this, so it was a matter of using it as a feature point to induce upgrades instead of charging for custom dev. Most of the code we could come up with ended up being pretty shoddy and littered with edge cases (similar to sales) due to a lack of unification of workflows. Odoo SA fixed that for us, so floating recommendation was a backport module instead of bothering with mine.

**Comment by Softdil** [comment] 2017-06-08 16:16
I really appreciate your help. I guess i'll simply deactivate the payment buttons in sales and leave it only for website sales.

**Comment by Yenthe666** [comment] 2017-12-04 10:29
Hi @ajayjaviya,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Closed by Yenthe666** 2017-12-04 10:29 UTC
Labels: Accounting
