### ISSUE TITLE
TypeError: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by jiad** [odoo/odoo#50968] opened 2020-05-09 11:19 UTC
Impacted versions:
version 12 community
Steps to reproduce:
In a multiple language odoo website, when a user uses non-english language to login, make a purchase online then make payment with stripe, it shows error, but the payment with stripe is successful. 
Current behavior:
error occur, no further notice in odoo, and customer doesn't know what happening.
Expected behavior:
customer receive payment success message
Video/Screenshot link (optional):

error message from log file:
processing transaction(s) [57], exception "not all arguments converted during string formatting" 
Traceback (most recent call last):
  File "/odoo/odoo-server/addons/payment/controllers/portal.py", line 98, in payment_status_poll
    tx_to_process._post_process_after_done()
  File "/odoo/odoo-server/addons/payment/models/payment_acquirer.py", line 850, in _post_process_after_done
    self._log_payment_transaction_received()
  File "/odoo/odoo-server/addons/sale/models/payment.py", line 58, in _log_payment_transaction_received
    super(PaymentTransaction, self)._log_payment_transaction_received()
  File "/odoo/odoo-server/addons/payment/models/payment_acquirer.py", line 718, in _log_payment_transaction_received
    post_message = trans._get_payment_transaction_received_message()
  File "/odoo/odoo-server/addons/payment/models/payment_acquirer.py", line 698, in _get_payment_transaction_received_message
    return message % tuple(message_vals)
TypeError: not all arguments converted during string formatting

**Comment by pedrobaeza** [comment] 2020-05-09 11:23
This seems a problem with the translation itself. Please check which language and the translation contains the same placeholders (`%s`) than the original string.

**Comment by jiad** [comment] 2020-05-12 20:27
> This seems a problem with the translation itself. Please check which language and the translation contains the same placeholders (`%s`) than the original string.

Thanks. will check it.

**Comment by jiad** [comment] 2020-05-15 09:02
> > This seems a problem with the translation itself. Please check which language and the translation contains the same placeholders (`%s`) than the original string.
> 
> Thanks. will check it.
Have check the translation, but there is no placeholders (`%s`) found.
Could you point out which one should look? Thanks.

**Comment by jiad** [comment] 2020-05-21 05:27
```
    @api.multi
    def _get_payment_transaction_received_message(self):
        self.ensure_one()
        amount = formatLang(self.env, self.amount, currency_obj=self.currency_id)
        message_vals = [self.reference, self.acquirer_id.name, amount]
        if self.state == 'pending':
            message = _('The transaction %s with %s for %s is pending.')
        elif self.state == 'authorized':
            message = _('The transaction %s with %s for %s has been authorized. Waiting for capture...')
        elif self.state == 'done':
            message = _('The transaction %s with %s for %s has been confirmed. The related payment is posted: %s')
            message_vals.append(self.payment_id._get_payment_chatter_link())
        elif self.state == 'cancel' and self.state_message:
            message = _('The transaction %s with %s for %s has been cancelled with the following message: %s')
            message_vals.append(self.state_message)
        else:
            message = _('The transaction %s with %s for %s has been cancelled.')
        return message % tuple(message_vals)
```
That's the code from file payment_acquirer.py.
Anybody help please.

Customers make stripe payments then receive this error, so customers think may not successful payment and pay again. But all payment are successful in stripe backend.

**Comment by jiad** [comment] 2020-05-21 05:59
After check odoo server log, found many same errors, start the error like this below:
ERROR HY01 odoo.addons.payment.controllers.portal: Error while processing transaction(s) [258], exception "not all arguments converted during string formatting"

**Comment by pedrobaeza** [comment] 2020-05-21 06:46
That are the strings you have to look on translations. You are still not mentioning which language you are handling.

**Comment by jiad** [comment] 2020-05-21 10:13
Thanks. The languages are Chinese and Korean

**Comment by pedrobaeza** [comment] 2020-05-21 10:19
Then you have both data needed for looking for it: that string in that languages.

**Comment by jiad** [comment] 2020-05-21 10:36
|  
-- | --
Thanks Message |  
Pending Message | Pending, Your online payment has been successfully processed. But your order is not validated yet.
Done Message | Done, Your online payment has been successfully processed. Thank you for your order.
Cancel Message | Cancel, Your payment has been cancelled.
Error Message | Error, Please be aware that an error occurred during the transaction. The order has been confirmed but will not be paid. Do not hesitate to contact us if you have any questions on the status of your order.

English messages from stripe configration at backend

**Comment by jiad** [comment] 2020-05-21 10:36
|  
-- | --
感谢留言 |  
待定消息 | 待定, 在线支付已完成. 订单未确认.
完成的信息 | 完成, 您的在线支付已成功完成. 谢谢.
取消消息 | 取消, 您的付款已取消.
错误消息 | 错误，请注意，发生错误。订单已经确认，但不会支付。如果您对订单状态有任何疑问，请随时与我们联系.

Chinese Version

**Comment by jiad** [comment] 2020-05-21 10:37
|  
-- | --
감사 메시지 |  
보류 메시지 | 보류중. 귀하의 온라인 결제가 성공적으로 처리되었습니다. 하지만 주문이 아직 확인되지 않았습니다.
완료 메시지 | 완료. 귀하의 온라인 결제가 성공적으로 처리되었습니다. 주문해 주셔서 감사합니다.
취소 메시지 | 취소. 귀하의 결제가 취소되었습니다.
오류 메시지 | 오류. 거래처리 중에 오류가 발생했습니다. 주문은 확인되었지만 대금은 지불되지 않았습니다. 주문 상태에 대해 궁금한 점이 있으시면 언제든지 저희에게 연락하십시오.

Korean version

**Comment by jiad** [comment] 2020-05-21 10:38
are they right?

**Comment by pedrobaeza** [comment] 2020-05-21 10:58
Placeholders `%s` are missing, and that's the problem.

**Comment by jiad** [comment] 2020-05-21 12:25
> Placeholders `%s` are missing, and that's the problem.

Can you show me the correct code please?

**Comment by jiad** [comment] 2020-05-21 12:27
Actually it is odoo offical code, I haven't edit the code. 
If it's error, should be reported? right?

**Comment by pedrobaeza** [comment] 2020-05-21 12:30
As said, the problem is that translations doesn't respect the same number of that placeholders. You must fix that translations, not Odoo code, and change it for everyone in Transifex (https://github.com/odoo/odoo/wiki/Translations) if you to contribute with the fix.

I'm closing this now as we are in a loop in the clarification.

**Closed by pedrobaeza** 2020-05-21 12:30 UTC
