### ISSUE TITLE
[9.0] Quotation report

### ISSUE THREAD

**Issue by SBollatti** [odoo/odoo#8707] opened 2015-09-24 18:10 UTC
If
- Company name: Enough long
- Company Address: enough long

- Customer name: enough long
- Customer Address: enough long

then quotation report would be without information like:
![aca](https://cloud.githubusercontent.com/assets/11006126/10082017/16f1745c-62ce-11e5-99a7-10d04a9e2ef8.jpg)

- Missing full Customer name, address, shipping address, etc
- Also notice the Quotation date and time ...weird

**Comment by SBollatti** [comment] 2015-10-15 18:18
Still Waiting

**Comment by sle-odoo** [comment] 2016-06-09 14:42
duplicate of #8707

**Closed by sle-odoo** 2016-06-09 14:42 UTC

**Comment by joolsr** [comment] 2016-06-09 16:59
have you closed the wrong one ? 8707 is referenced but is this bug report.
Which is the other one then ?

Julian
