### ISSUE TITLE
invoiced and invoiced_target in sales team cannot be set to over 2 billions 

### ISSUE THREAD

**Issue by pouyamn** [odoo/odoo#42992] opened 2020-01-08 18:30 UTC
Hi, `invoiced` and `invoiced_target` fields should be of Monetary type, but they are defined as Integer. As a result, it is not possible to have a target more than about two billions. If you think 2 billion Euro is too much for a sales team's monthly target, consider countries with lower value currencies, e.g. 2 billion Indonesian Rupiah, is around 130k EUR only.
  
Impacted versions:
7.0-13.0
Steps to reproduce:
try to add any value bigger than 2,147,483,647 in invoiced_target
Current behavior:
Raises error
Expected behavior:
accept the number.

**Comment by dbo-odoo** [comment] 2020-01-09 12:51
Hi @pouyamn 

You are completely right, and this is really quite stupid.

Fixing it in master is gonna be a breeze. Fixing that in stable... Well, that's gonna be a bit more annoying. Our stable policy clearly prohibits us from changing the column type of an existing field - it'd just mess up existing installations.

I see two possibilities for a possible fix in supported versions (11.0+):
- either we introduce a new module to modify the field's type. I certainly don't want to do that, but it's easy to code and idiot-proof (for us, i mean)
- either we introduce a new non-stored, inversable computed field that will store the values somewhere else (e.g. in the ir_property table)
- option C: something else, suggested by another brain (yours if you have an idea, or @nim-odoo's team)

@nim-odoo I would like your opinion here. The problem is not critical in the sense that it's "just" for reporting purposes, but that's seriously annoying for a rather big part of our user-base...

I suggest that we do it in master with @Feyensv; and that you decide what to do in stable version (and ideally that the bugfix team handles it for those versions as well, if possible).

We could also, as part of the same fix, introduce currency conversion for the SQL query - right now, it just sums up everything without regard for the currency of the account move. Multi-currency sales teams are not so frequent, so it doesn't seem to be a huge issue - we could limit that particular change to master for now.

**Comment by Feyensv** [comment] 2020-03-12 11:59
@nim-odoo can we have your opinion about this ? It is fixed in master by #44103 but something should probably also be done in stable :thinking:.

**Comment by nim-odoo** [comment] 2020-03-12 12:13
I don't really know what to do in stable... We could suggest users to convert their columns to `BIGINT`, but it's not really something to be done at the Odoo level.

**Comment by Feyensv** [comment] 2020-03-12 12:16
Well, ok let's leave it to targeted fixes then, thanks.

**Closed by Feyensv** 2020-03-12 12:16 UTC
Labels: 13.0, Confirmed, Sales
