### ISSUE TITLE
Odoo 9 Clean theme - in image + text block sides of pictogram are cut off

### ISSUE THREAD

**Issue by lrazov** [odoo/odoo#10564] opened 2016-01-21 06:48 UTC
in Odoo 9 Clean theme when using a pictogram with any animation is used in an image + text block the left and right sides of the pictogram get cut off by a couple of pixels. This doesn't happen with no animation used.

**Comment by qsm-odoo** [comment] 2017-12-06 16:46
Hello,
Sorry we did not reply to you at the time. I cannot reproduce your error so it has probably been fixed since then. I will close the issue but do not hesitate to ping me if any similar issue is still occurring.

**Closed by qsm-odoo** 2017-12-06 16:46 UTC
