### ISSUE TITLE
[10.0] fa icons are missing on pdf reports

### ISSUE THREAD

**Issue by lem8r** [odoo/odoo#15068] opened 2017-01-13 15:13 UTC
Impacted versions: 10.0

Steps to reproduce: print any pdf report with fa icons

Current behavior: fa icons are visible on html report and missing on pdf

Expected behavior: fa icons should be rendered on pdf report

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment] 2017-01-16 11:43
@Gorash and @sle-odoo could one of you guys look at this?

**Comment by lem8r** [comment] 2017-01-16 12:30
There are no fa icons on default Odoo reports. The problem is with custom reports.

**Comment by lem8r** [comment] 2017-01-16 14:26
Strange, it was fixed here #14433 but still not working

**Comment by pedrobaeza** [comment] 2018-05-06 12:55
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-05-06 12:55 UTC
Labels: 10.0, Framework
