### ISSUE TITLE
Cannot change customer country in Point of Sale on Android

### ISSUE THREAD

**Issue by StefanRijnhart** [odoo/odoo#14886] opened 2016-12-30 14:10 UTC
Impacted versions: 8, 9, 10

Steps to reproduce:
Open a Point of Sale session in Firefox (v.50) or Chrome (v.55) on Android 6. Go to the customer list, select a customer and select the pencil button to edit. Click on the country dropdown to select a (different) country.

Current behavior:
Dropdown does not open. No country can be selected.

Expected behavior:
The dropdown opens so that a country can be selected.

**Comment by Yenthe666** [comment] 2017-01-02 12:50
Hi @StefanRijnhart,

Thanks a lot for your report.
I've just tested this on Android 6.0.1 with Chrome 55 on Odoo 10 and I can reproduce this issue.
It looks like selecting the element is (nearly) impossible and doesn't seem to work.
@ged-odoo and @mart-e can one of you guys look at it?

Regards,
Yenthe

**Comment by StefanRijnhart** [comment] 2017-01-02 14:13
Thanks @Yenthe666 for confirming!

**Comment by jorenvo** [comment] 2017-02-02 17:49
Thanks for the report. A recent change in browser behavior was responsible for this. It has been fixed in Odoo 8 at c0817016d2523d0078bf3e7e94a2aa9d9048d598. This fix will be forward-ported to all later versions of Odoo. As soon as it gets merged into our latest LTS release this issue will automatically close.

**Closed** 2017-02-10 10:50 UTC
Labels: confirmed

**Comment by StefanRijnhart** [comment] 2017-02-10 11:45
@jorenvo thank you for fixing this!
