### ISSUE TITLE
[12.0] Issue on mail_notification_pay_now variable taking user_id instead of current (sender) id

### ISSUE THREAD

**Issue by reinaldoramosarxi** [odoo/odoo#32523] opened 2019-04-08 17:13 UTC
Impacted versions: 12.0, that we've tested

Steps to reproduce:
- Create a document (sale order, invoice, purchase order...) as a user
- Log in with another user and send that document through email

Current behavior: The signature (and by default the email as well, though it can be changed in the front end) inserted into the email is that of the user that created the document, and not of the current user (sender)

Expected behavior: Seems like it should use the sender's signature, at least by default.

We've pinpointed the problem to this line:

https://github.com/odoo/odoo/blob/12.0/addons/mail/data/mail_data.xml#L270

It uses the record.user_id variable instead of the current user id.

**Comment by Yenthe666** [comment] 2019-04-08 18:14
It's related to the salesperson / sales team set if I'm not mistaking. This has been the way it worked for atleast four years and I think it's correct. The person did create the SO originally.

**Comment by pedrobaeza** [comment] 2019-04-08 19:07
Indeed, that's the behavior since a lot, and it's the same as good as bad depending the case, but it's more likely to be preferable to use the salesman one than the administrative person sending the mail. If you don't want this behavior, just change the mail template to your needs.

Closing as no issue, but intended behavior, although as said in my land, it never rains to everyone's taste.

**Closed by pedrobaeza** 2019-04-08 19:07 UTC
