### ISSUE TITLE
ValueError: Field `exp_date` does not exist -> View `res.users.tree`

### ISSUE THREAD

**Issue by raquelribeiro2** [odoo/odoo#62213] opened 2020-11-23 21:14 UTC
Impacted versions: 13.0

Steps to reproduce: Settings/Users & Companies/Users

Current behavior: an exception is raised saying: ValueError: Field `exp_date` does not exist.

Expected behavior: in a localhost I can manage users, creating, changing passwords.

The full error is as follows:

Odoo Server Error
Traceback (most recent call last):
  File "/root/biplan-gestao/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/root/biplan-gestao/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/root/biplan-gestao/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/root/biplan-gestao/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/root/biplan-gestao/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/root/biplan-gestao/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/root/biplan-gestao/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/root/biplan-gestao/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/root/biplan-gestao/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/root/biplan-gestao/addons/web/controllers/main.py", line 1322, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/root/biplan-gestao/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/root/biplan-gestao/odoo/api.py", line 383, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/root/biplan-gestao/odoo/api.py", line 356, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/root/biplan-gestao/odoo/models.py", line 1441, in load_views
    for [v_id, v_type] in views
  File "/root/biplan-gestao/odoo/models.py", line 1441, in <dictcomp>
    for [v_id, v_type] in views
  File "/root/biplan-gestao/addons/hr/models/res_users.py", line 151, in fields_view_get
    return super(User, self).fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/root/biplan-gestao/addons/web/models/models.py", line 206, in fields_view_get
    r = super().fields_view_get(view_id, view_type, toolbar, submenu)
  File "/root/biplan-gestao/odoo/models.py", line 1528, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(self._name, etree.fromstring(result['arch']), view_id)
  File "/root/biplan-gestao/odoo/addons/base/models/ir_ui_view.py", line 987, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/root/biplan-gestao/odoo/addons/base/models/ir_ui_view.py", line 614, in raise_view_error
    raise ValueError(message)
ValueError: Field `exp_date` does not exist

Error context:
View `res.users.tree`
[view_id: 157, xml_id: base.view_users_tree, model: res.users, parent_id: n/a]

**Comment by pedrobaeza** [comment] 2020-11-24 08:05
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by raquelribeiro2** [comment] 2020-11-24 19:49
Hi Pedro! We actually customized some modules and noticed that some updates were missing, but our instance that is in production is not updating through the commands found in Odoo's forums, even generating another error.

Traceback:
TypeError: Cannot read property 'list' of undefined
    at https://potencial.biplan.com.br/web/content/1222-3ac6bad/web.assets_backend.js:447:309
    at Function._.each._.forEach (https://potencial.biplan.com.br/web/content/894-a0411c9/web.assets_common.js:108:558)
    at Class._generateActionViews (https://potencial.biplan.com.br/web/content/1222-3ac6bad/web.assets_backend.js:447:229)
    at https://potencial.biplan.com.br/web/content/1222-3ac6bad/web.assets_backend.js:442:497

The previous error persists. Could you help me, please?

**Comment by pedrobaeza** [comment] 2020-11-24 20:08
Sorry, I'm afraid I can't help right now on that. You need to properly update your database and avoid custom code that breaks it.

Respecting this issue, I'm closing not being related to Odoo code itself.

**Closed by pedrobaeza** 2020-11-24 20:08 UTC
Labels: Need information
