### ISSUE TITLE
[13.0] ir.model: Custom fields that are inherited on a different model are saved as base fields

### ISSUE THREAD

**Issue by RobCols** [odoo/odoo#44705] opened 2020-02-06 12:37 UTC
Impacted versions: 13.0

Steps to reproduce: 

- Add new fields on product.template
- Look at those fields on product.product

Current behavior:
Custom fields on product.product have state "base". 

Expected behavior:
Custom fields on product.product have state "manual"

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/32837815/73937363-27c2a600-48e5-11ea-9d04-9fb63a5cf87f.png)
![image](https://user-images.githubusercontent.com/32837815/73937392-390bb280-48e5-11ea-992b-599dbcc15335.png)

**Comment by RobCols** [comment] 2020-02-06 13:59
I had an exception message in the original post, but I edited out as it was irrelevant to the issue described.

**Comment by Feyensv** [comment] 2020-02-07 10:57
@dbo-odoo Dunno if it's a wanted behavior or not ;).

**Comment by dbo-odoo** [comment] 2020-02-10 08:56
Hi @RobCols 

I'd need @rco-odoo 's take on this, but in my opinion, this is how it should behave.

The fields on `product.product` are inherited through the delegation, which means that you don't really have control over them from the child model. You can't store them, you can't track them, you can't index them, you can't rename them, etc. from the `product.product` model, this has to be done on the `product.template` fields. I agree that the terminology can seem a bit strange, but since the fields are added on the product model through the delegation, this seems correct to me - you should _not_ be able to modify these fields at all through their inherited version (e.g. change name, etc.) and should only be able to modify the "real" ones. And for that, they _should_ be marked as base fields on the child model; otherwise it's gonna be wayyy too easy to mess it up. `base` fields here should be understood as 'unalterable through the UI'. One can even say that `base` is the correct terminology since the fields are set up automatically on the `product.product` model through the inheritance and not through a customization (granted, that's a bit of a stretch of the syntax ^^).

I'm gonna close this, since i'm pretty confident it's the expected behaviour. I'll raise the issue with Raphael to be sure and will re-open if needed.

KR,

**Closed by dbo-odoo** 2020-02-10 08:56 UTC
