### ISSUE TITLE
Cannot create serial number

### ISSUE THREAD

**Issue by jalena** [odoo/odoo#20662] opened 2017-11-03 03:50 UTC
Impacted versions:10.0

> Traceback (most recent call last):
  File "F:\python\YunShangZhuangShi\source\odoo\http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "F:\python\YunShangZhuangShi\source\odoo\http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "F:\python\YunShangZhuangShi\source\odoo\http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "F:\python\YunShangZhuangShi\source\odoo\service\model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "F:\python\YunShangZhuangShi\source\odoo\http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "F:\python\YunShangZhuangShi\source\odoo\http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "F:\python\YunShangZhuangShi\source\odoo\http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "F:\python\YunShangZhuangShi\source\addons\web\controllers\main.py", line 827, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "F:\python\YunShangZhuangShi\source\addons\web\controllers\main.py", line 849, in do_search_read
    offset=offset or 0, limit=limit or False, order=sort or False)
  File "F:\python\YunShangZhuangShi\source\odoo\models.py", line 4690, in search_read
    result = records.read(fields)
  File "F:\python\YunShangZhuangShi\source\odoo\models.py", line 3015, in read
    values[name] = field.convert_to_read(record[name], record, use_name_get)
  File "F:\python\YunShangZhuangShi\source\odoo\models.py", line 5205, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "F:\python\YunShangZhuangShi\source\odoo\fields.py", line 910, in __get__
    self.determine_value(record)
  File "F:\python\YunShangZhuangShi\source\odoo\fields.py", line 1022, in determine_value
    self.compute_value(recs)
  File "F:\python\YunShangZhuangShi\source\odoo\fields.py", line 976, in compute_value
    self._compute_value(records)
  File "F:\python\YunShangZhuangShi\source\odoo\fields.py", line 967, in _compute_value
    getattr(records, self.compute)()
  File "F:\python\YunShangZhuangShi\source\odoo\addons\base\ir\ir_sequence.py", line 79, in _get_number_next_actual
    self._cr.execute(query)
  File "F:\python\YunShangZhuangShi\source\odoo\sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "F:\python\YunShangZhuangShi\source\odoo\sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column "increment_by" does not exist
LINE 1: SELECT last_value, increment_by, is_called FROM ir_sequence_...
                           ^

**Comment by sswapnesh** [comment] 2017-11-03 07:21
@jalena Are you using postgresql 10 ?
@Yenthe666  Seems related to #20269

**Comment by Yenthe666** [comment] 2017-11-03 07:24
Indeed, this looks related.
@jalena are you using postgreSQL 10? If you are can you please try the patches for PSQL 10?
- Odoo 9.0: 7be3bcefb6c7682d37dd8c49b8da9f28f02a81e4
- Odoo 10.0 | 11.0: 69582ab05dee445854b11303f2e48965f1ad4a90 (should apply cleanly in both versions)

**Comment by odony** [comment] 2017-11-04 00:56
Yes, this is a duplicate of #20269, let's track it there.

**Closed by odony** 2017-11-04 00:56 UTC
Labels: 10.0

**Comment by jalena** [comment] 2017-11-04 05:10
@sswapnesh yes,I use  postgresql 10 ..
