### ISSUE TITLE
[v8] account: Advanced search on Invoice fields Subtotal/Tax/Total ends up in exception

### ISSUE THREAD

**Issue by andrius-preimantas** [odoo/odoo#6605] opened 2015-05-07 11:23 UTC
* Open Invoice list
* Do advanced search on any of these 3 fields
* Observe exception raised:
```
  ...
  File "/home/openerp/odoo/openerp/osv/fields.py", line 403, in <lambda>
    self._symbol_f = lambda x: _symbol_set_float(self, x)
  File "/home/openerp/odoo/openerp/osv/fields.py", line 376, in _symbol_set_float
    digits = self.digits
  File "/home/openerp/odoo/openerp/osv/fields.py", line 393, in digits
    cr = next(iter(Environment.envs)).cr
StopIteration
```
Tested on latest runbot.

Cheers

**Comment by Morney** [comment] 2015-05-12 09:31
Hi Andrius,

I am getting this same error on our system and can not see, to resolve it. 

Have you had any luck in fixing this?

Thanks
Peter

**Comment by andrius-preimantas** [comment] 2015-05-13 11:10
@Morney , no I didn't have time in finding the source of this problem. Hopefully somebody from odoo will look at this.

Cheers

**Comment by LeartS** [comment] 2015-05-14 07:23
Seems to have been fixed by https://github.com/odoo/odoo/commit/5efac22043adc735d9502fb9f6f7466b85916573, I can't reproduce it on latest runbot.

**Comment by nafex** [comment] 2015-05-15 10:28
fix is here: https://github.com/odoo-dev/odoo/commit/e9d5d9d278d54650d8f6228348f59e207f835df0 but don't has been merged...

**Closed** 2015-05-19 18:20 UTC
