### ISSUE TITLE
Incorrect leave duration calculation for half-days

### ISSUE THREAD

**Issue by blueman007** [odoo/odoo#67989] opened 2021-03-16 19:24 UTC
Impacted versions: 13.0 with latest git , 14.0 seems impacted too.

Steps to reproduce:
On the demo data, edit the Working Times -> Standard 40 hours -> remove the entire line for Tuesday afternoon.
![image](https://user-images.githubusercontent.com/34320141/111364760-f1338f00-8691-11eb-910c-5ab945b47078.png)

On the TimeOff module, create a leave request for user Mitchel Admin for an entire week (monday to sunday)
![image](https://user-images.githubusercontent.com/34320141/111364961-3061e000-8692-11eb-878f-f09f3e73fa5a.png)

Current behavior above: Duration is calculated at 5 days.
Expected behavior: Duration should be 4.5, as one-half day is never worked.
If you try to create a leave for the entire Tuesday, the duration is calculated as 1 day, what is expected is 0.5 day.

Additional debugging information, related issue in calculation I believe:
Steps to reproduce: change the Time_Off_Type "Paid Time Off", select "Take Time Off in **Half Day**".
On the TimeOff module, create a leave request for user Mitchel Admin for the half-day of Tuesday **morning**.
![image](https://user-images.githubusercontent.com/34320141/111366329-a581e500-8693-11eb-8463-b8e6ca0a8f55.png)
Current behavior above: Duration is calculated at 1 day.
Expected behavior: Duration should be 0.5 day.

Steps to reproduce: 
On the TimeOff module, create a leave request for user Mitchel Admin for the half-day of Tuesday **afternoon**.
![image](https://user-images.githubusercontent.com/34320141/111366522-e24ddc00-8693-11eb-9907-aa27037dca28.png)
Current behavior above: Duration is calculated at 1 day.
Expected behavior: Duration should be 0 day, as Tuesday afternoon is never worked.

What is curious is that if you switch change the Time_Off_Type "Paid Time Off", select "Take Time Off in **Hours**", and you try to create a leave for Tuesday, the number of hours is properly calculated (4.00 hours) but the number of days is not (1 day, where it is expected to have 0.5)
![image](https://user-images.githubusercontent.com/34320141/111366676-1c1ee280-8694-11eb-8587-7b82d415d968.png)

This seems related to hr_leave.py or hr_employee.py in models of hr_holidays.
Note: I have made sure that the timezones are the same everywhere. The issue doesn't seem to be related to that.

**Comment by blueman007** [comment] 2021-03-16 19:28
Additional info: If on the demo data, you edit the Working Times -> Standard 40 hours -> remove the 2 lines for both Tuesday morning **and** afternoon, then the calculations are correct. A leave request for monday to sunday will correctly report a duration of 4 days. The issue is only when half a day (morning or afternoon) is never worked.

**Comment by pedrobaeza** [comment] 2021-03-16 19:33
This is not a bug, but the expected behavior. If you define on Odoo that on Tuesday you only work half of the usual schedule, taking a leave for that hours is like taking whole day for holidays, so it shouldn't compute a regular 8 hours working time.

Closing as no issue.

**Closed by pedrobaeza** 2021-03-16 19:33 UTC

**Comment by blueman007** [comment] 2021-03-16 19:39
If I define on Odoo that on Tuesday mornings I usually work, but not during afternoons, then why if I request a leave for Tuesday afternoon the calculation gives 1 full day of holiday instead of zero ? I will be there during the morning. 
At least the calculation in that scenario should be zero.

**Comment by pedrobaeza** [comment] 2021-03-16 19:42
I'm afraid your logic is not the leave calculation logic.
