### ISSUE TITLE
Can't print Quotations: QWebException: Opening and ending tag mismatch: stong line 40 and strong, line 40, column 49

### ISSUE THREAD

**Issue by cmmata** [odoo/odoo#9536] opened 2015-11-12 11:27 UTC
Two days ago I installed Odoo 9 in a fresh server. I followed the [Official guide](https://www.odoo.com/documentation/9.0/setup/install.html#setup-install-source) and everything seems ok. I can add customers, projects, quotations, etc. But when I try to print a quotation, it shows a pop-up with the following trace. What can I do? I don't know where to see that error in more detail in debug mode.

Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/addons/report/controllers/main.py", line 101, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "/opt/odoo/openerp/http.py", line 465, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/report/controllers/main.py", line 45, in report_routes
    pdf = report_obj.get_pdf(cr, uid, docids, reportname, data=data, context=context)
  File "/opt/odoo/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/addons/report/models/report.py", line 156, in get_pdf
    html = self.get_html(cr, uid, ids, report_name, data=data, context=context)
  File "/opt/odoo/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/addons/report/models/report.py", line 130, in get_html
    return self.render(cr, uid, [], report.report_name, docargs, context=context)
  File "/opt/odoo/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/addons/report/models/report.py", line 106, in render
    return view_obj.render(cr, uid, template, values, context=context)
  File "/opt/odoo/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/addons/web_editor/models/ir_ui_view.py", line 29, in render
    return super(view, self).render(cr, uid, id_or_xml_id, values=values, engine=engine, context=context)
  File "/opt/odoo/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_ui_view.py", line 1065, in render
    return self.pool[engine].render(cr, uid, id_or_xml_id, qcontext, loader=loader, context=context)
  File "/opt/odoo/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 253, in render
    return self.render_node(element, qwebcontext, generated_attributes=qwebcontext.pop('generated_attributes', ''))
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 296, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 447, in render_tag_call
    d[0] = self.render_element(element, template_attributes, generated_attributes, d)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 425, in render_tag_foreach
    ru.append(self.render_element(element, template_attributes, generated_attributes, copy_qwebcontext))
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 324, in render_element
    raise_qweb_exception(message="Could not render element %r" % element.tag, node=element, template=template)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 458, in render_tag_call
    res = self.render(cr, uid, template, d)
  File "/opt/odoo/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 251, in render
    element = self.get_template(id_or_xml_id, qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 171, in get_template
    document = qwebcontext.loader(name)
  File "/opt/odoo/openerp/addons/base/ir/ir_ui_view.py", line 1063, in loader
    return self.read_template(cr, uid, name, context=context)
  File "/opt/odoo/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_ui_view.py", line 938, in read_template
    return self._read_template(cr, uid, view_id, context=context)
  File "/opt/odoo/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in _read_template
  File "/opt/odoo/openerp/tools/cache.py", line 85, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_ui_view.py", line 923, in _read_template
    arch = self.read_combined(cr, uid, view_id, fields=['arch'], context=context)['arch']
  File "/opt/odoo/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_ui_view.py", line 635, in read_combined
    view_arch = etree.fromstring(view['arch'].encode('utf-8'))
  File "lxml.etree.pyx", line 3092, in lxml.etree.fromstring (src/lxml/lxml.etree.c:70473)
  File "parser.pxi", line 1828, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:106307)
  File "parser.pxi", line 1716, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:105098)
  File "parser.pxi", line 1086, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:99780)
  File "parser.pxi", line 580, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:94254)
  File "parser.pxi", line 690, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:95690)
  File "parser.pxi", line 620, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:94757)
QWebException: Opening and ending tag mismatch: stong line 40 and strong, line 40, column 49

**Comment by cmmata** [comment] 2015-11-12 12:42
I found there's a "stong" instead of "strong" [in this file](https://github.com/odoo/odoo/search?utf8=%E2%9C%93&q=stong&type=Code). I changed it in my odoo source code, but still fails.

**Comment by cmmata** [comment] 2015-11-12 13:19
I found the same string in the database, table ir_translation. I fixed it with
UPDATE ir_translation SET value = '<strong>Comercial:</strong>' WHERE id = 23051;

Now I have another bug, and can't find how to fix it the same way as previous one:

Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/addons/report/controllers/main.py", line 101, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "/opt/odoo/openerp/http.py", line 465, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/report/controllers/main.py", line 45, in report_routes
    pdf = report_obj.get_pdf(cr, uid, docids, reportname, data=data, context=context)
  File "/opt/odoo/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/addons/report/models/report.py", line 156, in get_pdf
    html = self.get_html(cr, uid, ids, report_name, data=data, context=context)
  File "/opt/odoo/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/addons/report/models/report.py", line 130, in get_html
    return self.render(cr, uid, [], report.report_name, docargs, context=context)
  File "/opt/odoo/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/addons/report/models/report.py", line 106, in render
    return view_obj.render(cr, uid, template, values, context=context)
  File "/opt/odoo/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/addons/web_editor/models/ir_ui_view.py", line 29, in render
    return super(view, self).render(cr, uid, id_or_xml_id, values=values, engine=engine, context=context)
  File "/opt/odoo/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_ui_view.py", line 1065, in render
    return self.pool[engine].render(cr, uid, id_or_xml_id, qcontext, loader=loader, context=context)
  File "/opt/odoo/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 253, in render
    return self.render_node(element, qwebcontext, generated_attributes=qwebcontext.pop('generated_attributes', ''))
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 296, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 447, in render_tag_call
    d[0] = self.render_element(element, template_attributes, generated_attributes, d)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 425, in render_tag_foreach
    ru.append(self.render_element(element, template_attributes, generated_attributes, copy_qwebcontext))
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 324, in render_element
    raise_qweb_exception(message="Could not render element %r" % element.tag, node=element, template=template)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 458, in render_tag_call
    res = self.render(cr, uid, template, d)
  File "/opt/odoo/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 251, in render
    element = self.get_template(id_or_xml_id, qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 171, in get_template
    document = qwebcontext.loader(name)
  File "/opt/odoo/openerp/addons/base/ir/ir_ui_view.py", line 1063, in loader
    return self.read_template(cr, uid, name, context=context)
  File "/opt/odoo/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_ui_view.py", line 938, in read_template
    return self._read_template(cr, uid, view_id, context=context)
  File "/opt/odoo/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in _read_template
  File "/opt/odoo/openerp/tools/cache.py", line 85, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_ui_view.py", line 923, in _read_template
    arch = self.read_combined(cr, uid, view_id, fields=['arch'], context=context)['arch']
  File "/opt/odoo/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_ui_view.py", line 635, in read_combined
    view_arch = etree.fromstring(view['arch'].encode('utf-8'))
  File "lxml.etree.pyx", line 3092, in lxml.etree.fromstring (src/lxml/lxml.etree.c:70473)
  File "parser.pxi", line 1828, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:106307)
  File "parser.pxi", line 1716, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:105098)
  File "parser.pxi", line 1086, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:99780)
  File "parser.pxi", line 580, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:94254)
  File "parser.pxi", line 690, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:95690)
  File "parser.pxi", line 620, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:94757)
QWebException: Entity 'oacute' not defined, line 123, column 39

**Comment by Charly-HID** [comment] 2015-11-19 01:15
Enable the developer mode
Go to top menu settings
Go to left menu Actions/Reports
Search for "sale" report
Click on quotation/order 
Click on seach associated qweb views
Click on report_saleorder_document
Click on edit translations
Change the word <stong>Comercial:</strong> to <strong>Comercial:</strong>
Change the word <strong>Posici&oacut;n fiscal:</strong> to <strong>Posición fiscal:</strong>
Save and reset the server.
Search to for other acute words.

**Comment by Charly-HID** [comment] 2015-11-19 01:23
Enable the developer mode
Go to top menu settings
Go to left menu Actions/Reports
Search for "sale" report
Click on quotation/order 
Click on seach associated qweb views
Click on report_saleorder_document
Click on edit translations
Change the word "< s t o n g >Comercial:< / s t r o n g >" to "< s t r o n g >Comercial:< / s t r o n g >"
Change the word "< s t r o n g >Posici&oacut;n fiscal:< / s t r o n g >" to "< s t r o n g >Posición fiscal:< / s t r o n g >"
Save and reset the server.
Search to for other acute words.

**Comment by eneldoserrata** [comment] 2015-11-19 01:28
I already fix on https://www.transifex.com/odoo/odoo-9/language/es_DO/ this problem was present in other view too

**Comment by Charly-HID** [comment] 2015-11-19 01:31
Eneldoserrata: i can not  get access to you link address, in what other vies happend this error?

**Comment by eneldoserrata** [comment] 2015-11-19 01:41
@Charly-HID 

The problem is the translation in Spanish by the accents are not well escapees,
To help fix Register in transfix and fix the problem in your location.

go to https://github.com/odoo/odoo/wiki/Translations to learn hot to do it

**Comment by cmmata** [comment] 2015-11-19 16:20
@Charly-HID Great! It was the solution! Now it's working fine. I didn't notice the "edit translations" link and I was unable to find the correct view text. Thank you! Should I close this issue?
@eneldoserrata I'm going to Transifex and check if it's not yet corrected there.

**Comment by eneldoserrata** [comment] 2015-11-19 16:26
@cmmata a pleasure to have been able to help, I think if I can close it

**Comment by mart-e** [comment] 2016-01-26 14:23
fixed at 6872aae8ef9c1a1fc6a8283aa9d12ce3a6859157

**Closed by mart-e** 2016-01-26 14:23 UTC
