### ISSUE TITLE
[11.0]Error when using the oe_read_group function in Google Spreadsheet? 

### ISSUE THREAD

**Issue by bennals** [odoo/odoo#25517] opened 2018-06-27 23:47 UTC
Impacted versions:
11 Community Edition
Steps to reproduce:

1.  Install Google Spreadsheet module
2. Create Google authorisation code and allow requested permissions
3. Click 'Add to Google Spreadsheets' from Favourites drop down when in a kanban view.
4. Allow requested template permissions.
5. Enter a formula with a related field in a cell such as:
=oe_read_group("pos.order.line"; "display_name,qty,create_date"; "product_id";; "create_date desc";20)

Current behavior:
I get an error in the spreadsheet and the error below in the log. 

    File "/home/odoo/odoo-server/odoo/osv/expression.py", line 190, in normalize_domain
    assert isinstance(domain, (list, tuple)), "Domains to normalize must have a 'domain' form: a list or            
    tuple of domain components"
    AssertionError: Domains to normalize must have a 'domain' form: a list or tuple of domain  
    components

The oe_browse function works fine and pulls data into the spreadsheet correctly so I know the connection is fine and everything is configured properly.  For example:

     =oe_browse("pos.order.line"; "display_name,qty,create_date";; "create_date desc";20)

...works perfectly and returns the last 20 pos order lines as expected.

Expected behavior:
The oe_read_group function works without error.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2018-06-28 07:36
You are not using correctly the method: you have to provide a domain (https://www.odoo.com/documentation/online/reference/orm.html#domains). That's the message of the error and it's correct.

Closing as no real issue.

**Comment by wtaferner** [comment] 2018-06-28 07:40
@pedrobaeza 
There is a bug in the domain...it is of type str instead of list, tuples, so it is a valid issue.
It is already reported with OPW-1862033

**Comment by pedrobaeza** [comment] 2018-06-28 07:44
I don't see the domain on the formula.

**Comment by wtaferner** [comment] 2018-06-28 14:12
True, this one is missing the domain, but as said, I did a clear reproduction and there is an issue with Google Spreadsheet ;-) Test it yourself and you will see that it is not working properly :wink: 

Here are my test data with the same or similar result:
So, I tried to use the insert selection field wizard and tried as easy as
```
sale.report, name, [['state','not in',['draft','cancel','sent']]]
```
The error I got was "Unable to fetch data due to session expired exception" which is just wrong...

In the backend this error was trown...
```
File "/deploy/odoo-11.0/odoo/osv/expression.py", line 190, in normalize_domain

assert isinstance(domain, (list, tuple)), "Domains to normalize must have a 'domain' form: a list or tuple of domain components"

AssertionError: Domains to normalize must have a 'domain' form: a list or tuple of domain components
```
So, I checked what is wrong there and this is why...
```
Domain: [["state","notin",["draft","cancel","sent"]]] | Type: <class 'str'>
```

**Comment by wtaferner** [comment] 2018-06-28 14:57
Honestly, you have no idea why this issue is opened and it is most likely that it is the same issue, so please, do your homework, but don't try to tell me that it is another issue and I hijack this one...if you have invested time into this issue, show me the results and prove me wrong...over and out :stuck_out_tongue_winking_eye:

**Comment by pedrobaeza** [comment] 2018-06-28 15:04
We can be in the loop the time you want, so:

GOTO https://github.com/odoo/odoo/issues/25517#issuecomment-400943616

**Comment by wtaferner** [comment] 2018-06-29 03:53
@pedrobaeza 
And it was and is the same issue ;-)

May I ask you now to reopen? :stuck_out_tongue: 

@bennals 
You need to add a ```JSON.parse(domain)``` into the Google script (see screenshot), then it will work properly.

![googlescript](https://user-images.githubusercontent.com/362478/42072227-befb2524-7b5f-11e8-8ece-ae1e545ccc06.JPG)

@nim-odoo 
May I ask you to take care that this is added in the template of the Google Script?
https://github.com/odoo/odoo/blob/ef0907d5b0858efbf7702c78698d21fadf0149e7/addons/google_spreadsheet/data/google_spreadsheet_data.xml#L8

**Comment by wtaferner** [comment] 2018-06-29 09:30
@bennals 
I know and nevermind, Pedro and I have talked it through over other channels ;-) it was more like a religous discussion :smile: 

For the second issue "not in" -> "notin" we still need to find a solution, but I guess it will be solved too when the template is fixed by Odoo SA (I can not edit the Google Template Script which is good)

**Comment by pedrobaeza** [comment] 2018-06-29 10:28
@bennals I'm reopening this one, but please change main comment with the new error.

**Comment by wtaferner** [comment] 2018-06-29 10:34
@bennals 
Well, the issue is of course not about loading the work onto other persons shoulder or getting support but sharing common issues (and maybe remove them via a PR or other means and share again). 

It is pretty sure that the Google Spreadsheet is not perfect...as you seem to be knowledgeable I would suggest to find out the reason and try to improve and share your findings (maybe in another issue if it is different from this one). I am pretty sure they will, if correct, happily improve it based on your improvements.

For me the issue can be closed as soon as the two findings of myself are put into the central template (managed by Odoo SA).

**Comment by wtaferner** [comment] 2018-06-29 10:34
@pedrobaeza 
Thank you for reopening.

**Comment by mevivek4u** [comment] 2018-07-03 06:15
@wtaferner 
Is it possible to know the get a value from one2many field using oe_browse?
For example, product related to a sale order. =oe_browse("sale.order";'name'; 'customer_id'; 'order_line')

**Comment by wtaferner** [comment] 2018-07-11 14:04
For what it is worth...the solution for the operator whitespace removal is to resolve as simply as that.

![googlescript](https://user-images.githubusercontent.com/362478/42577051-0bd31d48-8524-11e8-9506-59f4aceff8ae.JPG)

**Comment by janarthanandev** [comment] 2018-11-26 15:57
@wtaferner @bennals  can you please help me how to resolve this error .
DNS error: http://localhost:8069/web/session/authenticate (line 310).
while setting odoo configuration i gave
server http://localhost:8069
dbname: xyz
username: admin
password: admin

**Comment by C3POdoo** [comment] 2019-04-11 14:11
Dear @bennals,

_This is an automated message._
This issue is linked to the Odoo support ticket opw-1862033 that has been closed.
We hope you got an answer to your issue.

If you believe the problem is not solved yet and would like to keep this issue open, please let us know to reopen it.

**Closed by C3POdoo** 2019-04-11 14:11 UTC
Labels: 11.0, OE, Services

**Comment by bennals** [comment] 2019-04-21 05:12
@janarthanandev 
This may not be of any assistance, but one thing that I frequently encounter with the Google Spreadsheet module is the need to generate a new authorization code for the spreadsheet to be able to connect to my odoo server.  Don't know why the old code stops working, and it's mildly annoying, but generating a new code usually allows me to connect again.

So, if you're sure the url you're using is the one where your odoo server is located (and assuming you're in 11CE) maybe try that by activating developer mode and going to Settings->General Settings->Integrations->Google Drive->Get Authorization code.  Enter the new code and save, then try connecting with your Google Spreadsheet again.
