### ISSUE TITLE
[8.0] survey: Survey print button does not generate any report

### ISSUE THREAD

**Issue by alejandrosantana** [odoo/odoo#6089] opened 2015-04-01 10:31 UTC
**Survey print button does not generate any report**

Impacted versions:

 - 8.0

Steps to reproduce:

 1. create a survey
 2. enter its form view
 3. Press "Print survey" button

Current behavior:

 - When pressing "Print survey" button no report is generated, but you are forwarded to its html.

Expected behavior:

 - When pressing "Print survey" button a PDF is generated, respecting theme and format.

This is very useful when filled in in any scenario without connection or by people without access (say elderly people or whatever).

**Comment by rim-odoo** [comment] 2015-10-15 14:04
Maybe the label of the button "Print survey" is indeed confusing, but it is actually the intended behaviour.  Something like "Printable version" could be more clear.

I will close this ticket but feel free to submit a pull request to improve that.

**Closed by rim-odoo** 2015-10-15 14:04 UTC
Labels: wishlist
