### ISSUE TITLE
Uninstalling modules can cause unintentional drop of SQL views (e.g. uninstalling sale_stock crashes the product form)

### ISSUE THREAD

**Issue by mzuiderbaan** [odoo/odoo#5030] opened 2015-02-02 18:02 UTC
**Uninstalling sale_stock results in error**

Impacted versions:
- 8.0 of 2-2-2015

Steps to reproduce:
1. uninstall stock & sale_stock
2. try to edit a product
3. results in error
4. install stock & sale_stock
5. no more error.
6. uninstall again, error back

Current behavior:

Odoo

Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 567, in dispatch
    result = self._call_function(*_self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 796, in __call__
    return self.method(_args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 949, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 932, in _call_kw
    records = getattr(request.session.model(model), method)(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 900, in proxy
    result = meth(cr, request.uid, _args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 3109, in read
    result = BaseModel.read(records, fields, load=load)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 3141, in read
    self._read_from_database(stored)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 3305, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/usr/lib/python2.7/dist-packages/openerp/osv/fields.py", line 1361, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/sale/sale.py", line 1283, in _sales_count
    res[template.id] = sum([p.sales_count for p in template.product_variant_ids])
  File "/usr/lib/python2.7/dist-packages/openerp/fields.py", line 760, in __get__
    self.determine_value(record)
  File "/usr/lib/python2.7/dist-packages/openerp/fields.py", line 853, in determine_value
    record._prefetch_field(self)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 3196, in _prefetch_field
    result = records.read(list(fnames), load='_classic_write')
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 3141, in read
    self._read_from_database(stored)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 3305, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/usr/lib/python2.7/dist-packages/openerp/osv/fields.py", line 1361, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/sale/sale.py", line 1269, in _sales_count
    for group in self.pool['sale.report'].read_group(cr, uid, domain, ['product_id','product_uom_qty'], ['product_id'], context=context):
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 2135, in read_group
    cr.execute(query, where_clause_params)
  File "/usr/lib/python2.7/dist-packages/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: relation "sale_report" does not exist
LINE 3:             FROM "sale_report" LEFT JOIN "product_product" a...
                         ^

Expected behavior:

Be able to uninstall the stock module and edit the product

**Comment by xclam** [comment] 2015-04-03 08:44
I have the same problem

**Comment by michaelcoyote** [comment] 2015-04-09 06:38
Same problem here.  See gist here: https://gist.github.com/michaelcoyote/8c50a2a2a893cf547609 for more details.

**Comment by sergueikp** [comment] 2015-05-28 14:53
Hi, me too I have the same problem : 
Traceback (most recent call last):
  File "C:\Odoo 8.0-20150528\server\.\openerp\http.py", line 536, in _handle_exception
  File "C:\Odoo 8.0-20150528\server\.\openerp\http.py", line 573, in dispatch
  File "C:\Odoo 8.0-20150528\server\.\openerp\http.py", line 309, in _call_function
  File "C:\Odoo 8.0-20150528\server\.\openerp\service\model.py", line 113, in wrapper
  File "C:\Odoo 8.0-20150528\server\.\openerp\http.py", line 306, in checked_call
  File "C:\Odoo 8.0-20150528\server\.\openerp\http.py", line 802, in __call__
  File "C:\Odoo 8.0-20150528\server\.\openerp\http.py", line 402, in response_wrap
  File "C:\Odoo 8.0-20150528\server\openerp\addons\web\controllers\main.py", line 937, in call_kw
  File "C:\Odoo 8.0-20150528\server\openerp\addons\web\controllers\main.py", line 929, in _call_kw
  File "C:\Odoo 8.0-20150528\server\.\openerp\api.py", line 241, in wrapper
  File "C:\Odoo 8.0-20150528\server\.\openerp\models.py", line 3139, in read
  File "C:\Odoo 8.0-20150528\server\.\openerp\api.py", line 239, in wrapper
  File "C:\Odoo 8.0-20150528\server\.\openerp\models.py", line 3174, in read
  File "C:\Odoo 8.0-20150528\server\.\openerp\api.py", line 239, in wrapper
  File "C:\Odoo 8.0-20150528\server\.\openerp\models.py", line 3352, in _read_from_database
  File "C:\Odoo 8.0-20150528\server\.\openerp\osv\fields.py", line 1466, in get
  File "C:\Odoo 8.0-20150528\server\openerp\addons\sale\sale.py", line 1308, in _sales_count
  File "C:\Odoo 8.0-20150528\server\.\openerp\fields.py", line 817, in __get__
  File "C:\Odoo 8.0-20150528\server\.\openerp\fields.py", line 910, in determine_value
  File "C:\Odoo 8.0-20150528\server\.\openerp\api.py", line 239, in wrapper
  File "C:\Odoo 8.0-20150528\server\.\openerp\models.py", line 3229, in _prefetch_field
  File "C:\Odoo 8.0-20150528\server\.\openerp\api.py", line 239, in wrapper
  File "C:\Odoo 8.0-20150528\server\.\openerp\models.py", line 3174, in read
  File "C:\Odoo 8.0-20150528\server\.\openerp\api.py", line 239, in wrapper
  File "C:\Odoo 8.0-20150528\server\.\openerp\models.py", line 3352, in _read_from_database
  File "C:\Odoo 8.0-20150528\server\.\openerp\osv\fields.py", line 1466, in get
  File "C:\Odoo 8.0-20150528\server\openerp\addons\sale\sale.py", line 1288, in _sales_count
  File "C:\Odoo 8.0-20150528\server\.\openerp\api.py", line 241, in wrapper
  File "C:\Odoo 8.0-20150528\server\.\openerp\models.py", line 2140, in read_group
  File "C:\Odoo 8.0-20150528\server\.\openerp\sql_db.py", line 158, in wrapper
  File "C:\Odoo 8.0-20150528\server\.\openerp\sql_db.py", line 234, in execute
ProgrammingError: ERREUR:  la relation « sale_report » n'existe pas
LINE 3:             FROM "sale_report" LEFT JOIN "product_product" a...
                         ^

**Comment by sergueikp** [comment] 2015-05-28 15:31
Did anybody managed to find a solution ?

**Comment by moerazem** [comment] 2015-06-14 11:08
Same problem here. Any solution?

**Comment by michaelcoyote** [comment] 2015-06-16 22:37
@moerazem Only the workaround of reinstalling the Stock Module

**Comment by sergueikp** [comment] 2015-06-17 07:01
Hi, as for me I found the cause of error, it was my custom module.

**Comment by maljac** [comment] 2015-06-30 14:36
Re-Install `sale_stock` worked for me (Odoo V8 20150628)

**Comment by odony** [comment] 2015-07-16 13:14
This is a consequence of a DROP CASCADE being done on stock-related tables. SQL views that depend on stock-related tables are automatically dropped by the CASCADE mode, and are unfortunately not re-created afterwards.
This is a limitation of the uninstallation system at the moment. The workaround is simple: manually force an update of the `sale` module (the one that defines the `sale_report` view) so that it will re-create the view.

**Comment by houssine78** [comment] 2016-01-07 12:06
Hi! 

Got the same issue and never installed stock or stock_sale. updating the sale module didn't solve issue.

Anyway I managed to solve it recreating the view directly on postgres 

Here is the code. This is for the sale module only if you have module extending this view you shoud adapt the code accordingly!

CREATE or REPLACE VIEW sale_report as (
WITH currency_rate (currency_id, rate, date_start, date_end) AS (
                    SELECT r.currency_id, r.rate, r.name AS date_start,
                        (SELECT name FROM res_currency_rate r2
                        WHERE r2.name > r.name AND
                            r2.currency_id = r.currency_id
                         ORDER BY r2.name ASC
                         LIMIT 1) AS date_end
                    FROM res_currency_rate r
                )
             SELECT min(l.id) as id,
                    l.product_id as product_id,
                    t.uom_id as product_uom,
                    sum(l.product_uom_qty / u.factor * u2.factor) as product_uom_qty,
                    sum(l.product_uom_qty * l.price_unit / cr.rate * (100.0-l.discount) / 100.0) as price_total,
                    count(*) as nbr,
                    s.date_order as date,
                    s.date_confirm as date_confirm,
                    s.partner_id as partner_id,
                    s.user_id as user_id,
                    s.company_id as company_id,
                    extract(epoch from avg(date_trunc('day',s.date_confirm)-date_trunc('day',s.create_date)))/(24*60*60)::decimal(16,2) as delay,
                    l.state,
                    t.categ_id as categ_id,
                    s.pricelist_id as pricelist_id,
                    s.project_id as analytic_account_id,
                    s.section_id as section_id
FROM (sale_order_line l
                      join sale_order s on (l.order_id=s.id)
                        left join product_product p on (l.product_id=p.id)
                            left join product_template t on (p.product_tmpl_id=t.id)
                    left join product_uom u on (u.id=l.product_uom)
                    left join product_uom u2 on (u2.id=t.uom_id)
                    left join product_pricelist pp on (s.pricelist_id = pp.id)
                    join currency_rate cr on (cr.currency_id = pp.currency_id and
                        cr.date_start <= coalesce(s.date_order, now()) and
                        (cr.date_end is null or cr.date_end > coalesce(s.date_order, now()))))
GROUP BY l.product_id,
                    l.order_id,
                    t.uom_id,
                    t.categ_id,
                    s.date_order,
                    s.date_confirm,
                    s.partner_id,
                    s.user_id,
                    s.company_id,
                    l.state,
                    s.pricelist_id,
                    s.project_id,
                    s.section_id  
)

**Comment by lukebranch** [comment] 2016-01-26 09:56
@odony ,

Just for records sake, I just encountered this issue in Odoo 9.0c, specifically when I selected and applied:

Display margins on quotations and sales orders

and the switched back to:

Salespeople do not need to view margins when quoting

and applied again.

Reproduce-able on the latest runbot for 9.0c.

<h1>Environment:</h1>
<ul>
<li>Ubuntu 14.04 LTS Server Edition</li>
<li>PostgreSQL 9.5</li>
<li>Odoo 9c - installed from source using Andre S. script derivative</li>
<li>Nginx 1.9.9</li>
</ul>

<h1>Steps to Reproduce:</h1>
1) Sales >> Settings >> Tick - Display margins on quotations and sales orders
2) Apply
3) Sales >> Settings >> Tick - Salespeople do not need to view margins when quoting
4) Apply
5) Sales >> Products >> Click - Apple Wireless Keyboard

<h1>Result:</h1>
```
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/runbot/extra/runbot/static/build/127301-9-0-2a4e3d/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/runbot/extra/runbot/static/build/127301-9-0-2a4e3d/openerp/http.py", line 680, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/runbot/extra/runbot/static/build/127301-9-0-2a4e3d/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/127301-9-0-2a4e3d/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/127301-9-0-2a4e3d/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/127301-9-0-2a4e3d/openerp/http.py", line 959, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/127301-9-0-2a4e3d/openerp/http.py", line 509, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/127301-9-0-2a4e3d/openerp/addons/web/controllers/main.py", line 892, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/127301-9-0-2a4e3d/openerp/addons/web/controllers/main.py", line 884, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/127301-9-0-2a4e3d/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/127301-9-0-2a4e3d/openerp/models.py", line 3175, in read
    result = BaseModel.read(records, fields, load=load)
  File "/home/odoo/runbot/extra/runbot/static/build/127301-9-0-2a4e3d/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/127301-9-0-2a4e3d/openerp/models.py", line 3221, in read
    values[name] = field.convert_to_read(record[name], use_name_get)
  File "/home/odoo/runbot/extra/runbot/static/build/127301-9-0-2a4e3d/openerp/models.py", line 5721, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/odoo/runbot/extra/runbot/static/build/127301-9-0-2a4e3d/openerp/fields.py", line 807, in __get__
    self.determine_value(record)
  File "/home/odoo/runbot/extra/runbot/static/build/127301-9-0-2a4e3d/openerp/fields.py", line 914, in determine_value
    self.compute_value(recs)
  File "/home/odoo/runbot/extra/runbot/static/build/127301-9-0-2a4e3d/openerp/fields.py", line 869, in compute_value
    self._compute_value(records)
  File "/home/odoo/runbot/extra/runbot/static/build/127301-9-0-2a4e3d/openerp/fields.py", line 859, in _compute_value
    getattr(records, self.compute)()
  File "/home/odoo/runbot/extra/runbot/static/build/127301-9-0-2a4e3d/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/127301-9-0-2a4e3d/openerp/addons/sale/sale.py", line 852, in _sales_count
    product.sales_count = sum([p.sales_count for p in product.product_variant_ids])
  File "/home/odoo/runbot/extra/runbot/static/build/127301-9-0-2a4e3d/openerp/fields.py", line 807, in __get__
    self.determine_value(record)
  File "/home/odoo/runbot/extra/runbot/static/build/127301-9-0-2a4e3d/openerp/fields.py", line 914, in determine_value
    self.compute_value(recs)
  File "/home/odoo/runbot/extra/runbot/static/build/127301-9-0-2a4e3d/openerp/fields.py", line 869, in compute_value
    self._compute_value(records)
  File "/home/odoo/runbot/extra/runbot/static/build/127301-9-0-2a4e3d/openerp/fields.py", line 859, in _compute_value
    getattr(records, self.compute)()
  File "/home/odoo/runbot/extra/runbot/static/build/127301-9-0-2a4e3d/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/127301-9-0-2a4e3d/openerp/addons/sale/sale.py", line 835, in _sales_count
    for group in self.env['sale.report'].read_group(domain, ['product_id', 'product_uom_qty'], ['product_id']):
  File "/home/odoo/runbot/extra/runbot/static/build/127301-9-0-2a4e3d/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/127301-9-0-2a4e3d/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/127301-9-0-2a4e3d/openerp/models.py", line 2123, in read_group
    cr.execute(query, where_clause_params)
  File "/home/odoo/runbot/extra/runbot/static/build/127301-9-0-2a4e3d/openerp/sql_db.py", line 139, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/127301-9-0-2a4e3d/openerp/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
ProgrammingError: relation "sale_report" does not exist
LINE 3:             FROM "sale_report" LEFT JOIN "product_product" a...
                         ^
```

**Comment by houssine78** [comment] 2016-01-28 11:00
I recently got the same error on an update of module on V8

2016-01-26 10:57 GMT+01:00 Luke Branch <notifications@github.com>:

**Comment by EdyKend** [comment] 2016-04-04 19:14
Hi All
I found the cause of the same error in my custom module, below is the part that caused the error.

class sale_order(models.Model):
_inherit ='sale.order'
.......
date_confirm = fields.Datetime('Confirmation Date', readonly=True, help="Date on which sales order is payment confirmed.", copy=False)
...........

I tried to replace the official field type from the date to datetime in field date_confirm.
if I do not replace this field type, then update the sale module, everything will be normal.

I hope this can help a little solution

**Comment by travs-w** [comment] 2016-04-25 16:17
Hello,

I was trying to accomplish [the same](https://www.odoo.com/forum/help-1/question/sales-analysis-error-line-1-report-id-from-sale-report-where-sale-report-id-in-17586) as @EdyKend when I got this error, but I found the solution.

In order to change the date_confirm attribute into a datetime field (instead of just date), we have to change the field definition in two places:

The obvious place is in the **sale** module's _sale.py_ file:

`'date_confirm': fields.datetime('Confirmation Date', readonly=True, select=True, help="Date on which sales order is confirmed.", copy=False),`

However, you must also change in the **sale** module's _sale_report.py_ file:
`'date_confirm': fields.datetime('Date Confirm', readonly=True),`

(This is obviously v7 API version, but same can be achieved easily with v8 API)

**Comment by ddiazpinto** [comment] 2016-05-30 17:52
I have had the same issue in Odoo v9 after uninstall `stock` application. Re-installing the `sale` app fixes the problem.

**Comment by bkgunderson** [comment] 2016-06-28 16:19
Also encountered this in Odoo v9 after uninstalling a custom module. Upgrading the `sale` app fixed the view for me.

**Comment by gezorro** [comment] 2016-11-02 10:38
I have the same problem after select "Display margins on quotations and sales orders" in Sales / Setting.
Unselect this point solved the problem.

**Comment by nhomar** [comment] 2018-08-15 09:38
There is a workaround and closing then, but marked as wishlist can be seen in the future.

**Closed by nhomar** 2018-08-15 09:38 UTC
Labels: Wishlist
