### ISSUE TITLE
9.0 - Possible to confirm Same Serial Number on different deliveries

### ISSUE THREAD

**Issue by stephaniemillet** [odoo/odoo#8989] opened 2015-10-09 14:48 UTC
When you create a sales order for product with unique serial number tracking
And you 'reserve' the delivery order linked to sales order.
And change the serial number it automatically proposed.
several  issues

1 - it does NOT change the reserved serial number in Stock
2 - you can select the SAME serial number on two different sales order. And validate both
(just check that the serial number is not selected twice on the SAME sales order, not different)
(give a negative quantity on serial number inventory) 
3 - if you duplicate the sales order with serial number reserved on its delivery : it even DUPLICATE the serial number reserved)

![image](https://cloud.githubusercontent.com/assets/12233420/10396765/938bcda0-6ea4-11e5-8fb5-64c7a9c74b3f.png)

![image](https://cloud.githubusercontent.com/assets/12233420/10396797/adc09b9c-6ea4-11e5-838b-a7dc82b7b0ac.png)

![image](https://cloud.githubusercontent.com/assets/12233420/10396835/d40b4dce-6ea4-11e5-9e25-e6dad5be77fa.png)

![image](https://cloud.githubusercontent.com/assets/12233420/10396917/46ba36a0-6ea5-11e5-8940-2da310e3ea69.png)

![image](https://cloud.githubusercontent.com/assets/12233420/10396976/90113966-6ea5-11e5-9a7c-fce2b9e23bbb.png)

**Comment by jco-odoo** [comment] 2015-10-14 09:58
1 The stock is indeed not automatically rereserved.  With a small customization in the view it is possible to add a button to do the rereservation where it will take into account the lots provided. 
2 In general, you can create negative stock if the things you specify are not there, so also if you take a serial number that is not there.  
3 If I duplicate a sale order, it will take other serial numbers.  I don't understand what you mean exactly.  (did you copy the picking itself maybe?)

**Comment by stephaniemillet** [comment] 2015-10-20 12:28
The point is  :
You can't select the same 'unique' serial number on different lines of the SAME delivery order
But you CAN select the same 'unique' serial number on different line of DIFFERENT delivery order

**Comment by stephaniemillet** [comment] 2015-12-11 09:51
Odoo's answer
Hello Stéphanie,

Both issues are linked to the same use case: the serial number is changed manually by the user. In this situation, we assume that this is done when the user is about to put the product in the package, and therefore validate the picking.

Let's consider a product A, for which we have two units in stock with serial numbers (SN): X001 and X002. The product with SN X001 was received in stock before X002.
A first picking is created with one unit of this product, then reserved. Odoo will reserve, by default, the product with X001 since it follows FIFO rules.
A second picking is created with one unit of this product, then reserved. Odoo will reserve the product with SN X002.
Both pickings are in state "Available"

At this point, here is the scenario we support. The user takes care of the second picking, and decides to send product with SN X001 instead of X002. He changes the lot number in the picking and validate. At this point, picking 2 will be in state "Done", while picking 1 will be in state "Waiting Availability". Indeed, the validation of picking 2 triggered the removal of the reservation of X001 for picking 1.
The point is that we assume that when the user chooses which serial numbers he picks, he also puts the product in the package. In other words, this is supposed to be set during the packaging phase of the picking.

Changing the lot on the picking should not be used to change the reservation. This is not meant to be used that way. Therefore, the current behavior should not cause any practical issue.

Regards,
Nicolas

--
Nicolas Martinelli (nim)

**Comment by stephaniemillet** [comment] 2015-12-11 09:52
Hi Nicolas, 

Thank you very much for your detailed answer and your long email.

The fact that you need to detail a whole scenario to explain how a functionality works, proves that this functionality does not work in all cases, so it does not work properly and need to be improved
The ERP is supposed to fit customers’ process, and not the opposite.

Specifically , my customer do not use Packs, and don’t want to.
I guess I won’t have this point be fixed for their go live, but please, make sure to improve  this in the future upgrade

Best,

**Comment by sle-odoo** [comment] 2018-02-21 10:44
Hi,
This is the expected behaviour except point 3 which i was not able to reproduce (duplicating a confirmed SO creates a new one draft). Note that in version 11, the reservation is updated when you change the serial number. You're still able to select the same serial in multiple deliveries, we don't want to block a user that maybe doesn't have an accurate inventory at this time. The line will be in red though.

Regards

**Closed by sle-odoo** 2018-02-21 10:44 UTC
Labels: 9.0, Logistics
