### ISSUE TITLE
[Odoo 13] Error 500 with new  language on website

### ISSUE THREAD

**Issue by attikaworld** [odoo/odoo#40078] opened 2019-11-10 17:42 UTC
Impacted versions: 
Odoo 13.0-20191010 (Community Edition)

Steps to reproduce: 
After adding any new language for the website on multiple instances the website stops working on any language except English. It shows error 500 or undefined error.

Current behavior:
On demo data somehow it works with new languages with the same odoo version.

**Comment by pedrobaeza** [comment] 2019-11-10 20:15
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by attikaworld** [comment] 2019-11-11 15:37
Hi! 

Thank you for reply, I've tried on RunBot - everything seems to work fine there.

I use Bitnami and Google Cloud to run instance with
Odoo 13.0-20191010 (Community Edition)

After noticing first error, I've created a clean instance several times without any module except Website.

And after adding new language and selecting it on the website, the server gives Error 404 or Error 500 time to time when selecting any new language.

Other local languages for administrator and users works perfect.

**Comment by wpdigital** [comment] 2019-11-16 19:02
Hi! 

I've launched new version where multiple languages seems to work fine.

But with the new version now the page is not editable, new pages cannot be created and template cannot be customised.

It is another error, but maybe connected to this thread as well.

I use Google Cloud on Bitnami
Odoo 13.0-20191110 (Community Edition)
Have tried to reinstall the instance and the Website app.
Website is a single installed app.

Below are all three errors:

**1. Refuses to edit page**
 
Traceback:
Error: QWeb2: Template 'website.editorbar' not found
    at Object.exception (http://**.**.**.**.**/web/content/365-ebaa920/1/web.assets_common_lazy.js:3593:7)
    at Engine._render (http://**.**.**.**.**/web/content/365-ebaa920/1/web.assets_common_lazy.js:3638:103)
    at Engine.render (http://**.**.**.**.**/web/content/365-ebaa920/1/web.assets_common_lazy.js:3634:151)
    at Class.renderElement (http://**.**.**.**.**/web/content/365-ebaa920/1/web.assets_common_lazy.js:3991:1137)
    at http://**.**.**.**.**/web/content/365-ebaa920/1/web.assets_common_lazy.js:4001:6
    at async Class._startEditMode (http://**.**.**.**.**/web/content/367-ea09f0c/1/website.assets_editor.js:48:26)
    at async Promise.all (index 0)


**2. New page cannot be added**

Traceback:
Error: QWeb2: Template 'website.components.switch' not found
    at Object.exception (http://**.**.**.**.**/web/content/365-ebaa920/1/web.assets_common_lazy.js:3593:7)
    at Engine._render (http://**.**.**.**.**/web/content/365-ebaa920/1/web.assets_common_lazy.js:3638:103)
    at Engine.render (http://**.**.**.**.**/web/content/365-ebaa920/1/web.assets_common_lazy.js:3634:151)
    at Object.init (http://**.**.**.**.**/web/content/367-ea09f0c/1/website.assets_editor.js:55:380)
    at http://**.**.**.**.**/web/content/366-8c5157d/1/web.assets_frontend_lazy.js:78:746

**3. Template cannot be edited**

Traceback:
Error: QWeb2: Template 'website.theme_customize_widget_color' not found
    at Object.exception (http://**.**.**.**.**/web/content/443-7f68b20/1/web.assets_common_lazy.js:3593:7)
    at Engine._render (http://**.**.**.**.**/web/content/443-7f68b20/1/web.assets_common_lazy.js:3638:103)
    at Engine.render (http://**.**.**.**.**/web/content/443-7f68b20/1/web.assets_common_lazy.js:3634:151)
    at http://**.**.**.**.**/web/content/445-396954f/1/website.assets_editor.js:103:527
    at Function._.each._.forEach (http://**.**.**.**.**/web/content/443-7f68b20/1/web.assets_common_lazy.js:9:558)
    at _processItems (http://**.**.**.**.**/web/content/445-396954f/1/website.assets_editor.js:102:1230)
    at http://**.**.**.**.**/web/content/445-396954f/1/website.assets_editor.js:105:89
    at Function._.each._.forEach (http://**.**.**.**.**/web/content/443-7f68b20/1/web.assets_common_lazy.js:9:558)
    at _processItems (http://**.**.**.**.**/web/content/445-396954f/1/website.assets_editor.js:102:1230)
    at http://**.**.**.**.**/web/content/445-396954f/1/website.assets_editor.js:102:655

**Comment by wpdigital** [comment] 2019-11-16 19:17
Everything works fine with direct installation from Bintnami and not from GC Console.

Maybe this information will be useful.

Thank you!

**Comment by wpdigital** [comment] 2019-11-16 19:27
Unfortunately after installing new language it keeps giving the errors (listed above) again.
Will be grateful for fix, thank you!

**Comment by milekium** [comment] 2019-11-19 18:55
I get same error, I use English language for admin but I have not install english on the website. I guess admin languages different from website languages gives this error when editing website configs, just a guess.

**Comment by mart-e** [comment] 2019-11-22 13:15
Hello,

Thanks for the report, we confirm the issue.
I am closing this issue in favour of #40078 where there is a bit more details.
You can follow the progress there

**Closed by mart-e** 2019-11-22 13:15 UTC
Labels: 13.0, Website

**Comment by ossimantylahti** [comment] 2020-04-14 22:10
This issue is still present with Odoo 13 CE on . And I think I found out what the problem is: if the USER's language is different than website language, there is an error 500 in opening the page.
Steps to reproduce:

1. Create Odoo instance in English
2. Install another Odoo language (for example Spanish) in Settings
3. Create an user with high priviledges (adminprofile@example.com)
4. Use the system in English with this user
5. Change this user's preferred language to Spanish in his user profile

To trigger the error seems a bit fuzzy, but it seems that editing translations (like Product name) by clicking on the small EN symbol (that opens translations dialog) seems to trigger problematic behaviour.

Close browsers and open the server main page. Observe error 500 appearing

Workaround: open the /web to to to the main backend page and edit user's preferences of language. Change from Spanish to English and save. Then refresh and open the main page (without /web).

Funny thing is that after the error 500 has disappeared, the user's language can be changed back to Spanish again and website works.
