### ISSUE TITLE
[10.0 e] website lang switcher conflict when browser lang differs from website default lang

### ISSUE THREAD

**Issue by nbessi** [odoo/odoo#19488] opened 2017-09-15 10:43 UTC
Impacted versions: 10.0 enterprise

Steps to reproduce:

Create a website, install graphen odoo theme, load german and french language, set french as preffered language in browser.
(Tested in Chrome)

Current behavior:
You got to the site, the site switch to the default language set in web admin. Try to switch to German -> OK  Now try to goes back to english or (the website default lang) the site will always return to prefered browser languange. There is no way to switch back to default language. 

You can play with default of odoo and browser to have variation of this bug.

Expected behavior:

We can switch the lang many times and each time the website shown the correct lang. Whatever the browser setting and website settings are.

Video/Screenshot link (optional):

**Comment by nbessi** [comment] 2017-09-15 12:14
Issu is not reproducible if graphen theme is not installed

**Comment by Yenthe666** [comment] 2017-09-15 13:11
@JKE-be I've seen similar things. Could you give feedback/have a look?

**Comment by rdeodoo** [comment] 2017-11-29 11:05
Could you please reproduce the issue on [runbot theme](http://runbot.odoo.com/runbot/repo/git-github-com-odoo-design-themes-3?search=)?
As you can see on [this runbot](http://281373-10-0-602fbc.runbot12.odoo.com/), I have installed graphen theme, then installed french and german language (in that order).
I have set my browser language to french, but I can't reproduce your issue.

**Comment by rdeodoo** [comment] 2018-01-03 09:59
I am closing this since some fixes have been made about language issues very recently, specially about browser lang conflict.

**Closed by rdeodoo** 2018-01-03 09:59 UTC
Labels: need information, Website
