### ISSUE TITLE
[9.0]Debug Mode in multi worker break the UI

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#9571] opened 2015-11-16 08:34 UTC
Debug Mode in multi worker break the UI
I'm running in multi worker successfully. Yet when trying to use the debug mode, it failed.
It runs perfectly in worker = 0

# Impacted versions:

 - 9.0

# Steps to reproduce:

 1. run odoo in multi worker mode
 2. go into debug mode

# Current behavior:

it failed:
![odoo_v10](https://cloud.githubusercontent.com/assets/1043935/11177275/b92b172e-8c44-11e5-8358-87b8fa89b057.jpeg)
I precise that without the debug mode it works

# Expected behavior:

Working

**Comment by sle-odoo** [comment] 2016-07-28 15:13
Closing as i cannot reproduce. If you're still facing the issue, please provide a more detailed report.
Regards

**Closed by sle-odoo** 2016-07-28 15:13 UTC
