### ISSUE TITLE
Survey print not showing results on print

### ISSUE THREAD

**Issue by mikifus** [odoo/odoo#21308] opened 2017-11-28 19:37 UTC
Impacted versions: 11.0

Steps to reproduce:
Make a survey, fill it, go to the answer and click print.

Current behavior:
When trying to print a single survey (or only see its results), survey.js can't load the values of each field.

Expected behavior:
Fields display the previously answered data.

**I've actually fixed it** but I was lazy to do the whole thing for pull requests.
Here's the fix: https://github.com/odoo/odoo/compare/11.0...mikifus:print-survey-fix

**Comment by sswapnesh** [comment] 2017-11-29 02:49
Duplicate of #20836

**Comment by mikifus** [comment] 2017-11-29 08:34
Thanks @sswapnesh, I didn't find it before. Shall I move my fix proposal there?

**Comment by sswapnesh** [comment] 2017-11-29 13:59
@mikifus It was handled in #21325.
@JKE-be You can close this issue.

**Closed** 2017-11-29 15:45 UTC
