### ISSUE TITLE
Currency showing wrong in List view Also total is showing wrong.

### ISSUE THREAD

**Issue by rb3606** [odoo/odoo#68677] opened 2021-04-02 04:34 UTC
Impacted versions: Odoo14

Steps to reproduce: Create 2 companies with different currency and Create invoice and when you enabled both company from company selection from top right in list view currency showing wrong in invoice list view.

Current behavior: Single Currency showing  for all records

Expected behavior: Currency should be showing as per record (selected currency)

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/6355966/113380792-c7b97980-939a-11eb-8cbe-bc6115a94511.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment] 2021-04-02 06:17
I confirm such problem. Maybe it can't be avoided, as showing both companies at the same time is not allowed in the dynamic currency conversion that is performed for having homogeneous amounts.

**Comment by ray-odoo** [comment] 2021-04-04 18:55
![Screenshot 2021-04-04 115257](https://user-images.githubusercontent.com/41073831/113518648-7e089480-953c-11eb-8ce9-ab3018f7b191.png)

I cannot reproduce this.

1. Create Company.
2. Configure Chart of Accounts.
3. Set Company current to Euro
4. Configure multi-currency
5. Create and post Invoice in Euros

What are the steps to reproduce?

**Comment by rb3606** [comment] 2021-04-05 11:25
Hello @ray-odoo 
I have Fresh odoo setup no custom module installed.   i have latest commit (2nd March,2021, Hash : 0784e14dd39817720e6fc70c2b41ea3bbad5843a) . I just want to confirm that did you install 2 chart of account company wise ?

**Comment by ray-odoo** [comment] 2021-04-05 14:34
Yes. That was my step 2. The Chart was already installed for the first Company.

**Comment by rb3606** [comment] 2021-04-08 13:49
@ray-odoo But lets say company currency USD and i am creating Invoice in EURO then list view showing amount is from EURO but symbol is from USD.

**Comment by pedrobaeza** [comment] 2021-04-08 14:14
@rb3606 The amounts in the list are converted to the company currency, so it's not a bug, but a feature. When I did my test, I should overview the company currency and seems to me that it was incorrect, but it's not, so closing.

**Closed by pedrobaeza** 2021-04-08 14:14 UTC
Labels: 13.0, 14.0, Accounting, Confirmed

**Comment by rb3606** [comment] 2021-04-08 14:29
No its not feature. Because amount is not converted to Company currency but its showing as it is. Just symbol is changed. If you see in my above picture amount is in INR(indian currency) but list view just putting symbol of $(USD). So ultimately total is also wrong.

**Comment by pedrobaeza** [comment] 2021-04-08 14:30
That will be one of these causes:

- No conversion date.
- No currency rate set.

**Comment by rb3606** [comment] 2021-04-08 14:31
I already checked that as well. its already there.

**Comment by ray-odoo** [comment] 2021-04-08 14:34
@rb3606 I suggest you are missing a step.  For example if you set the Currency of a Company *then* install a Chart for that Company, the currency will match the Chart, not what you set.  Try again and post the *exact* steps (not missing anything) because I have tried this several times and can't get it to happen unless I miss a step or do things out of order.
