### ISSUE TITLE
Issue on E-commerce v14 CE + Pricelists Show Public Price + Discounts (Grant Discounts on sales orders)

### ISSUE THREAD

**Issue by marcosmonauta** [odoo/odoo#64728] opened 2021-01-19 03:27 UTC
Impacted versions: v14 CE

When making a ecommerce with V14 CE, if you create a product with a price, 5,626 USD for example, and then you create a Pricelist with a special price for that product, 116 USD for example 

**AND** you activate the Discount Policy  in the Pricelist/Configuration Show public price & discount to the customer 

**AND** you chek the chekmark in Settings / Sales /Discount (Grant Discounts on sales orders),

**THEN** the price in the product e-commerce page is 116 but when purchasing suddenly the price is 112.52(an extra 3% discount, exactly), that discount was not configured anywhere.

If you change the the Discount Policy from Show Public Price to Discount included in the price
**OR** deselect the checkmark Discount (Grant Discounts on sales orders),
**THEN** the price when purchasing is right 116

Can anybody help me with that issue? **Seems like odoo is including an extra discount of 3% when showing the price discount !**  Thank you

![image](https://user-images.githubusercontent.com/75961027/104984004-8a686100-59d3-11eb-9388-efede1e502df.png)

![image](https://user-images.githubusercontent.com/75961027/104984061-a53ad580-59d3-11eb-93fe-e7073cde4425.png)

**Comment by pedrobaeza** [comment] 2021-01-19 07:47
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by marcosmonauta** [comment] 2021-01-19 21:53
Hi Pedro, I could not do exactly the same problem, but one that I think is the same.
In configuraiton, in decimal I put 0 in product price and discunt
Set in the pricelist a discount of 50.5% (in the example Pedal Bin)
The price of the pedal bin is 47, then in the ecommerce product price is 26.45. When adding to the cart the price is 26.48

There is a problem with the discount decimals, in the product page uses a formula and in the cart uses a different one. I guess the problem is on the decimals that I set to 0 for the discount and product price.

Tested in runbot 14.0 CE 

https://5815313-14-0.runbot55.odoo.com/shop/cart


![image](https://user-images.githubusercontent.com/75961027/105097437-2cd52280-5a6e-11eb-9355-a3e03760aa5e.png)
![image](https://user-images.githubusercontent.com/75961027/105097515-555d1c80-5a6e-11eb-96b5-2ce0409dc643.png)

**Comment by pedrobaeza** [comment] 2021-01-20 07:16
This is something expected, as you can't mangle that way the decimal precision without consequences. For having the same results in all places, you need to make sure that the precision is at least enough for computing back and forward from price with and without discount, or don't use such option in the pricelist, or rounding artifacts will appear.

Closing thus.

**Closed by pedrobaeza** 2021-01-20 07:16 UTC
