### ISSUE TITLE
Not able to set Integer and Float as mandatory

### ISSUE THREAD

**Issue by mohmdlabeeb** [odoo/odoo#75138] opened 2021-08-16 10:57 UTC
Impacted versions:

Steps to reproduce: Set  a integer field as mandatory and save the record

Current behavior: As the default value is 0, the field will be saved as 0

Expected behavior: There should not be any default value and the user should be forced to enter the value

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment] 2021-08-16 10:59
This is by design, as depending the business flow, 0 can be an accepted value. Put a constraint over that field > 0 if your business case requires it.

Closing as no issue, but expected by design.

**Closed by pedrobaeza** 2021-08-16 10:59 UTC
