### ISSUE TITLE
TypeError: must be string or buffer, not None

### ISSUE THREAD

**Issue by killex55** [odoo/odoo#15969] opened 2017-03-21 11:53 UTC
Impacted versions: Odoo 10
S.O. Centos 7

Steps to reproduce: the error message appears when I try to send an invoice email

Odoo Server Error:

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 862, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 5469, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 5367, in _onchange_eval
    method_res = method(self)
  File "/usr/lib/python2.7/site-packages/odoo/addons/mail/wizard/mail_compose_message.py", line 339, in onchange_template_id_wrapper
    values = self.onchange_template_id(self.template_id.id, self.composition_mode, self.model, self.res_id)['value']
  File "/usr/lib/python2.7/site-packages/odoo/addons/mail/wizard/mail_compose_message.py", line 361, in onchange_template_id
    values = self.generate_email_for_composer(template_id, [res_id])[res_id]
  File "/usr/lib/python2.7/site-packages/odoo/addons/mail/wizard/mail_compose_message.py", line 498, in generate_email_for_composer
    template_values = self.env['mail.template'].with_context(tpl_partners_only=True).browse(template_id).generate_email(res_ids, fields=fields)
  File "/usr/lib/python2.7/site-packages/odoo/addons/mail/models/mail_template.py", line 515, in generate_email
    result, format = Template.env['report'].get_pdf([res_id], report_service), 'pdf'
  File "/usr/lib/python2.7/site-packages/odoo/addons/report/models/report.py", line 192, in get_pdf
    save_in_attachment = self._check_attachment_use(docids, report)
  File "/usr/lib/python2.7/site-packages/odoo/addons/report/models/report.py", line 326, in _check_attachment_use
    pdf = base64.decodestring(pdf)
  File "/usr/lib64/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
TypeError: must be string or buffer, not None

**Comment by arafatx** [comment] 2017-04-28 14:27
Same issue here. Anyone ?

**Comment by Yenthe666** [comment] 2017-05-08 07:02
Hi @killex55,

Thank you for your report.
I've just tried to reproduce this on the latest Odoo 10.0 and couldn't reproduce this.
Can you try again on a runbot (runbot.odoo.com) or update your Odoo to the latest code and try again please?

Regards,
Yenthe

**Comment by Yenthe666** [comment] 2017-05-30 09:14
Hi @killex55,

I'm closing this bug report as there has been no feedback in almost a month and the issue is no longer reproducable.
If you can still reproduce this on the latest Odoo code (or a runbot) then please add more information here and I'll reopen the issue.

Regards,
Yenthe

**Closed by Yenthe666** 2017-05-30 09:14 UTC
Labels: need informations

**Comment by shyjuk** [comment] 2017-08-11 10:49
Had the same issue on CentOS 7. Following solution worked.

1. Downloaded the new [wkhtmltopdf](https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz).
2. Extracted . (tar xf wkhtmltox-0.12.4_linux-generic-amd64.tar.xz)
3. Backup old one. ( mv /bin/wkhtmltopdf /bin/wkhtmltopdf_old) Or /usr/bin/
4.  Copy the new file. (cp wkhtmltox/bin/wkhtmltopdf /bin/)
5. Delete the current invoice/quote and create a new one and try.
6.

**Comment by vadermemo** [comment] 2018-01-07 02:09
Same issue on CentOS 7, 
the shyjuk's workaround don't work for last version of centOS and odoo
