### ISSUE TITLE
[10.0] adding one2many field to sale.order.line breaks onchange (partner_id) on sale.order

### ISSUE THREAD

**Issue by eLBati** [odoo/odoo#17618] opened 2017-06-14 13:37 UTC
**Impacted versions**:

10.0

**Steps to reproduce**:

 - With a custom module, add a one2many field to sale.order.line (you can use [sale_commission](https://github.com/hurrinico/commission/tree/5537392b4347b08801d41afc4167d38f2b1e9c98/sale_commission), OCA open PR https://github.com/OCA/commission/pull/117; see  ```agents```  field)
 - Create a new sale order, add a sale order line, add a record to the new o2m. Save
 - Edit the sale order, change the customer. Save

**Current behavior**:

Get ```Record does not exist or has been deleted```

**Expected behavior**:

Sale order is saved

**Comment by eLBati** [comment] 2017-06-15 12:37
Please check how onchange builds o2m values of sub fields: in this case I see a list of tuples where the first one is ```(5)``` ("removes all records from the set") followed by ```(4, recordID)```.
Maybe this is the cause of ```Record does not exist or has been deleted```?
According to ```write``` documentation, both commands (4 and 5) are not allowed for One2many fields
cc @rco-odoo

**Comment by nim-odoo** [comment] 2017-06-19 11:08
@ged-odoo @aab-odoo Can you confirm if this is supported for v10? Or is it a known limitation?

**Comment by gdgellatly** [comment] 2017-06-19 11:31
@eLBati  I've had problems for years with the behaviour of nested one2many's.  Each version, different issues, although I recall this one in previous versions, however we had the command resolve2many in the past which mitigated it..  

The root issue as far as I can recall is that regardless of what the original line was you get a record with new ID for one2many when the record/s is/are loaded (i.e. orderline).  Then because the fk for the nested one2many is the real id (or because its been changed to the new id, and on save that id no longer exists) things go bad.  At least thats my best guess after weeks of trying to make it work in v10.  

In fact I suspect this is related to other bug reports/feature requests relating to onchanges impacting one2many fields.

My current work around is using a many2one to bridge the relationship.  In my case that actually leads to better functionality and less duplication but it also has its own set of issues to deal with.

**Comment by ged-odoo** [comment] 2017-06-19 11:50
@nim-odoo not 100% sure of the problem, but nested one2manys are supposed to work in v10 and this definitely look like a bug. If it worked in v9.0, the likely suspect is the onchange refactoring between v9 and v10.

Howerver, note that nested x2manys are definitely the most complicated part of Odoo.  There are so many slightly different situations that can arise, and with many potential subtle (or not so subtle) bugs.  Also, this may be the reason why some bugs were left, if a simple workaround was found.

@gdgellatly Until saas-15, handling x2manys (particularly when editable list view and onchanges are involved) was extremely tricky in odoo.  Each change that we dared do broke something else, in a totally unexpected way.  However, starting in saas-16, we rewrote the JS views, and added 21k lines of test.  This means that
1) the new views are better designed, and much easier to change
2) the test suite protects us against unexpected bugs
3) the test suite define the semantics of the views.  Before, much of the behaviour was just emergent behaviour, not something that was particularly decided.  And much of the behaviour could change from a version to the next.  Now, in many case, we had to make a choice on the way the web client behave, and this choice is specified in the tests.  Of course, we may decide later to change some behaviour, but at least, it will be each time a conscious decision, not just random chance.

To be honest, I feel that this was something really basic that was missing from the web client for way too long, but at least, it is done now.  Hopefully, it will lead to a better future, for us and for every odoo users.

**Comment by gdgellatly** [comment] 2017-06-19 22:17
@ged-odoo Wow that is great news.  I think I might just focus on other areas until v11 hits.  Because you are right, it just constantly feels like one fix breaks something else, every version has its own cases and you end up pinned to certain revisions feeling like you are doing something that isn't really supported, but absolutely necessary.

**Comment by dhannyz** [comment] 2017-06-21 23:37
I'm also extremely happy to hear about the refactoring of the JS code that's on its way. Just like @gdgellatly I've been struggling with issues related to this kind of x2many nesting for some time.
Hopefully the refactoring might also move to solve other issues, like the behaviour of dynamic domains (Especially in tree views where returning a domain from an onchange is completely broken)?

**Comment by lmignon** [comment] 2017-06-22 06:41
@ged-odoo @eLBati IMO a bug still exists into the python code, more precisely into the `convert_to_onchange` method defined on  `class _RelationalMulti` https://github.com/odoo/odoo/pull/15566/files#diff-c1b8488f841717177876eb16877596af.... I've proposed a PR to solve this kind of error and it's successfully used in production for months..
https://github.com/odoo/odoo/pull/15566/

**Comment by zeroincombenze** [comment] 2019-10-09 10:26
The above workaround seems to have a side effect. 

Steps to reproduce:

* Install sale_commission module
* Configure 2 customs with agent and commission
* Create a new sale order to customer 1, add a sale order line, add a record with commission
* Edit the sale order, change the customer to customer 2. Save


Current behavior:

Commission in order lines are deleted


Expected behavior:

Commission in order lines must have value as from customer

**Comment by eduardo-tirado** [comment] 2019-10-30 18:38
> The above workaround seems to have a side effect.
> 
> Steps to reproduce:
> 
> * Install sale_commission module
> * Configure 2 customs with agent and commission
> * Create a new sale order to customer 1, add a sale order line, add a record with commission
> * Edit the sale order, change the customer to customer 2. Save
> 
> Current behavior:
> 
> Commission in order lines are deleted
> 
> Expected behavior:
> 
> Commission in order lines must have value as from customer

Hi @zeroincombenze I recommend using the latest version of the sale_commission module, I have tried it and the errors presented in this thread are resolved.

https://github.com/OCA/commission/tree/10.0/sale_commission versión 10.0.2.5.0

**Comment by pedrobaeza** [comment] 2020-05-03 12:37
Closing this as fixed in later versions (but adding inline view in nested o2m fields).

**Closed by pedrobaeza** 2020-05-03 12:37 UTC
Labels: 10.0, Framework
