### ISSUE TITLE
Error asterisk_click2dial Odoo 10 installation

### ISSUE THREAD

**Issue by voipsense** [odoo/odoo#24561] opened 2018-05-03 22:02 UTC
Impacted versions:10

Steps to reproduce:

Current behavior: Error: QWeb2: Template 'asterisk_click2dial.OpenCaller' not found

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2018-05-03 22:03
Hi, I'm not able to reproduce this problem in latest runbot version, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there.

**Closed by pedrobaeza** 2018-05-03 22:03 UTC

**Comment by voipsense** [comment] 2018-05-03 22:05
this is my source code https://github.com/OCA/connector-telephony/tree/10.0

**Comment by voipsense** [comment] 2018-05-03 22:09
Error: QWeb2: Template 'asterisk_click2dial.OpenCaller' not found

http://192.168.1.106:8069/web/content/251-60b13b6/web.assets_common.js:2908
Retraçage :
exception@http://192.168.1.106:8069/web/content/251-60b13b6/web.assets_common.js:2908:7
_render@http://192.168.1.106:8069/web/content/251-60b13b6/web.assets_common.js:2953:92
render@http://192.168.1.106:8069/web/content/251-60b13b6/web.assets_common.js:2949:146
renderElement@http://192.168.1.106:8069/web/content/251-60b13b6/web.assets_common.js:3118:1068
__widgetRenderAndInsert/<@http://192.168.1.106:8069/web/content/251-60b13b6/web.assets_common.js:3118:912
then/</</<@http://192.168.1.106:8069/web/content/251-60b13b6/web.assets_common.js:547:678
fire@http://192.168.1.106:8069/web/content/251-60b13b6/web.assets_common.js:541:281
add@http://192.168.1.106:8069/web/content/251-60b13b6/web.assets_common.js:542:467
then/</<@http://192.168.1.106:8069/web/content/251-60b13b6/web.assets_common.js:547:631
each@http://192.168.1.106:8069/web/content/251-60b13b6/web.assets_common.js:370:758
then/<@http://192.168.1.106:8069/web/content/251-60b13b6/web.assets_common.js:547:553
Deferred@http://192.168.1.106:8069/web/content/251-60b13b6/web.assets_common.js:548:189
then@http://192.168.1.106:8069/web/content/251-60b13b6/web.assets_common.js:547:518
__widgetRenderAndInsert@http://192.168.1.106:8069/web/content/251-60b13b6/web.assets_common.js:3118:879
prependTo@http://192.168.1.106:8069/web/content/251-60b13b6/web.assets_common.js:3118:214
load_items/<@http://192.168.1.106:8069/web/content/324-44e8b61/web.assets_backend.js:1966:703
_.forEach@http://192.168.1.106:8069/web/content/251-60b13b6/web.assets_common.js:12:558
load_items@http://192.168.1.106:8069/web/content/324-44e8b61/web.assets_backend.js:1966:565
start@http://192.168.1.106:8069/web/content/324-44e8b61/web.assets_backend.js:1966:288
OdooClass.extend/</prototype[name]</<@http://192.168.1.106:8069/web/content/251-60b13b6/web.assets_common.js:3015:556
show_application@http://192.168.1.106:8069/web/content/324-44e8b61/web.assets_backend.js:1721:1295
show_application@http://192.168.1.106:8069/web/content/324-44e8b61/web.assets_backend.js:2926:4337
OdooClass.extend/Class.include/</prototype[name]</<@http://192.168.1.106:8069/web/content/251-60b13b6/web.assets_common.js:3018:368
start/<@http://192.168.1.106:8069/web/content/324-44e8b61/web.assets_backend.js:1717:1680
then/</</<@http://192.168.1.106:8069/web/content/251-60b13b6/web.assets_common.js:547:678
fire@http://192.168.1.106:8069/web/content/251-60b13b6/web.assets_common.js:541:281
fireWith@http://192.168.1.106:8069/web/content/251-60b13b6/web.assets_common.js:546:198
Deferred/</deferred[tuple[0]]@http://192.168.1.106:8069/web/content/251-60b13b6/web.assets_common.js:548:31
fire@http://192.168.1.106:8069/web/content/251-60b13b6/web.assets_common.js:541:281
add@http://192.168.1.106:8069/web/content/251-60b13b6/web.assets_common.js:542:467
then/</</<@http://192.168.1.106:8069/web/content/251-60b13b6/web.assets_common.js:547:753
fire@http://192.168.1.106:8069/web/content/251-60b13b6/web.assets_common.js:541:281
fireWith@http://192.168.1.106:8069/web/content/251-60b13b6/web.assets_common.js:546:198
Deferred/</deferred[tuple[0]]@http://192.168.1.106:8069/web/content/251-60b13b6/web.assets_common.js:548:31
fire@http://192.168.1.106:8069/web/content/251-60b13b6/web.assets_common.js:541:281
fireWith@http://192.168.1.106:8069/web/content/251-60b13b6/web.assets_common.js:546:198
Deferred/</deferred[tuple[0]]@http://192.168.1.106:8069/web/content/251-60b13b6/web.assets_common.js:548:31
fire@http://192.168.1.106:8069/web/content/251-60b13b6/web.assets_common.js:541:281
fireWith@http://192.168.1.106:8069/web/content/251-60b13b6/web.assets_common.js:546:198
Deferred/</deferred[tuple[0]]@http://192.168.1.106:8069/web/content/251-60b13b6/web.assets_common.js:548:31
fire@http://192.168.1.106:8069/web/content/251-60b13b6/web.assets_common.js:541:281
fireWith@http://192.168.1.106:8069/web/content/251-60b13b6/web.assets_common.js:546:198
Deferred/</deferred[tuple[0]]@http://192.168.1.106:8069/web/content/251-60b13b6/web.assets_common.js:548:31
fire@http://192.168.1.106:8069/web/content/251-60b13b6/web.assets_common.js:541:281
fireWith@http://192.168.1.106:8069/web/content/251-60b13b6/web.assets_common.js:546:198
Deferred/</deferred[tuple[0]]@http://192.168.1.106:8069/web/content/251-60b13b6/web.assets_common.js:548:31
loadJS/script.onreadystatechange@http://192.168.1.106:8069/web/content/251-60b13b6/web.assets_common.js:3038:25

**Comment by pedrobaeza** [comment] 2018-05-03 22:11
This is a bad manipulation in your end or a deployment problem, so please don't spam more this issue.
