### ISSUE TITLE
Upgrade fails on hw_blackbox_be/controllers/main.py

### ISSUE THREAD

**Issue by johanehnberg** [odoo/odoo#33228] opened 2019-05-08 05:51 UTC
Impacted versions:
Nightly 8 May 2019 DEBs from
deb http://nightly.odoo.com/11.0/nightly/deb/ ./

Steps to reproduce:
The addon seems to be included by default so the error is triggered on all default installs with a normal upgrade:
`sudo apt-get update && sudo apt-get upgrade`

Current behavior:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up odoo (11.0.20190508) ...
  File "/usr/lib/python3/dist-packages/odoo/addons/hw_blackbox_be/controllers/main.py", line 178
    return address = f.read().rstrip().replace(b':', b'')[-7:]
                   ^
SyntaxError: invalid syntax

dpkg: error processing package odoo (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 odoo
E: Sub-process /usr/bin/dpkg returned an error code (1)

Expected behavior:
Installs without error.

**Comment by pedrobaeza** [comment] 2019-05-08 07:43
@nle-odoo can this be due to https://github.com/odoo/odoo/commit/b87454ee1b4538834afc20c78c68b37ad39114a8?

Is it because it's being executed in Python 2?

**Comment by Byloth** [comment] 2019-05-08 08:42
Same problem for me. 👍

I don't think so the problem is related to the Python version in which it runs...  
Actually, I'm pretty sure it's a syntax problem.

Unlike other languages, Python doesn't allow you to return the result of an assignment.

---

Here the problem: https://github.com/odoo/odoo/commit/b87454ee1b4538834afc20c78c68b37ad39114a8#diff-fe98190785f16b4bdc799cd481fd657eR178

**Comment by nle-odoo** [comment] 2019-05-08 08:55
yes, sorry, I tested in local and with blackbox with the right code, but a test of syntax change got in the merged commit somehow

should be solved with https://github.com/odoo/odoo/pull/33239 that should be merged in following hours

**Closed** 2019-05-08 10:29 UTC
Labels: 11.0, Point of Sale
