### ISSUE TITLE
[9.0] Blog post translation not working

### ISSUE THREAD

**Issue by Fl0rianFischer** [odoo/odoo#9510] opened 2015-11-10 12:21 UTC
## Affects Versions

* 9.0
* Runbot

## Steps to reproduce

* install a new language (German in my case)
* activate language in website admin panel
* go to blog
* click on translate

## Current behavior

Blog title and subtitle are translatable and marked with yellow background. It is NOT possible to translate the actual content of the blog.

## Expected behavior

The content of the blog should be translatable as any other content.

**Comment by jholze** [comment] 2015-11-10 13:08
@odony did you know if it's already fixed ? i think translations for the blog are a must have / blocker

**Comment by jholze** [comment] 2015-11-10 13:08
@Fl0rianFischer did you checked it also in Enterprise ?

**Comment by odony** [comment] 2015-11-10 15:19
@Gorash could you have a look? In 9.0 the blog content is not editable when in translate mode in the front-end, while it was working in 8.0.

**Comment by jholze** [comment] 2015-11-10 18:45
@odony thanks :)

**Comment by jholze** [comment] 2015-12-08 14:24
some updates here ? Because it's really bad to run a blog without the possibility to translate them.

**Comment by jholze** [comment] 2015-12-09 14:42
@Gorash @odony today we started to fix this issue. So no need on your side. PR is coming soon today or tomorrow

**Comment by Gorash** [comment] 2015-12-09 15:23
I'm back, I'll fix this

**Comment by Gorash** [comment] 2015-12-09 15:25
Issue because the fields html use a specific function to translate. This function is apply automatically if translate=True and sanitize=True but for the blog, the field is sanitize=False
It will be fixed today

**Comment by jholze** [comment] 2015-12-16 08:45
@odony i think you can close it because of the fix from @Gorash.

**Comment by odony** [comment] 2015-12-16 08:58
Closing this issue, fixed by #9993 and confirmed by @jholze, thanks!

**Closed by odony** 2015-12-16 08:58 UTC

**Comment by jholze** [comment] 2016-02-17 16:01
welcome
