### ISSUE TITLE
odoo website 

### ISSUE THREAD

**Issue by abdorhem** [odoo/odoo#46970] opened 2020-03-05 13:00 UTC
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

Error:
Uncaught TypeError: resp.indexOf is not a function

https://www.odoo.com/thanks/trial?
Traceback:

**Comment by Yenthe666** [comment] 2020-03-05 13:34
Please add more info and reproducible steps. Closing untill the issue is more clear.

**Closed by Yenthe666** 2020-03-05 13:34 UTC
