### ISSUE TITLE
[9.0]Impossible to reconcile : Access error

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#10469] opened 2016-01-14 22:44 UTC
Hi,

I create a fresh database and set a user with max accounting access right.
When reaching the reconciliation interface from the dashboard, I have this message :

![odoo_v10](https://cloud.githubusercontent.com/assets/1043935/12339241/406bbac4-bb14-11e5-9abb-846992c01593.jpeg)

I tried to change and add some rules on objects.
I checked on a fresh bank account statement .

**Comment by Yenthe666** [comment] 2016-10-04 13:04
Hi @flotho,

Thank you for your report.
I've just tested this on the latest Odoo 9 and I can no longer reproduce this issue:
![image](https://cloud.githubusercontent.com/assets/6352350/19075099/bc566d2e-8a43-11e6-84ea-e2c2294e0610.png)
I'm closing this issue since I can no longer reproduce it. If you still face an issue please update your Odoo source code. If the issue still persist you can ping me and I'll reopen the issue.

Regards,
Yenthe

**Closed by Yenthe666** 2016-10-04 13:04 UTC
