### ISSUE TITLE
[9.0] SEO Modal on translated page: Uncaught TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by leoniscsem** [odoo/odoo#10629] opened 2016-01-26 13:40 UTC
When working on a translated page (i.e. secondary language set to German) and trying to edit the metatags, the modal does not pop up, but delivers an uncaught type error. Browser console points me to websites.assets_editor.js line 176
`var m=repr.match(/(.+)\((\d+),(.*)\)/)`

Editing the data in the site's main language works as intended.

**Comment by JKE-be** [comment] 2016-02-08 16:07
I cannot reproduce. Can you pull the last version and retry...
See also:  https://github.com/odoo/odoo/wiki/Contributing

**Comment by Yenthe666** [comment] 2018-01-16 12:51
Closing as there has been no feedback in a long, long, time.

**Closed by Yenthe666** 2018-01-16 12:51 UTC
