### ISSUE TITLE
Strange behavior with datetime fields in domain

### ISSUE THREAD

**Issue by flyingL123** [odoo/odoo#24102] opened 2018-04-07 03:06 UTC
I'm using `saas-14`. My database contains a `purchase.order.line` with an `id = 98` and `create_date = 2018-04-07 01:04:32`. The create date for this object is the most recent create date for any `purchase.order.line` in the system. In other words, there are no other `purchase.order.line` objects in the system where `create_date > 2018-04-07 01:04:32`.

I have the following code in an server action for a `purchase.order.line`:

```
raise Warning(env['purchase.order.line'].search([('create_date', '>', record.create_date)]).id)
```

When I trigger this action for the existing `purchase.order.line(98,)`, the result is `98`. In other words, the system seems to think that `2018-04-07 01:04:32 > 2018-04-07 01:04:32`. That obviously doesn't make any sense.

I would expect the action to return `false`. Why is this happening?

**Comment by nhomar** [comment] 2018-04-07 07:31
Hello.

We only give support to stable versions (saas-** are not stable ones), can you try it in v11 and confirm if the wrong behavior is there then please let's know to help you properly.

In the meanwhile, I will left open the issue marking it as need information.

Regards.

**Comment by sswapnesh** [comment] 2018-04-07 19:09
Hello @nhomar 
I can confirm this Issue and can reproduce in v11 too.
I have tested this using dummy button not server action.

```
print(self.id, self.create_date) --> 2 2018-02-24 17:36:14
print(self.search([('create_date', '>', self.create_date)])) --> stock.picking(13, 3, 2, 25, 1, 4, 6, 5)
print(self.search([('id','=',self.id),('create_date', '>', self.create_date)])) --> stock.picking(2,)
```

**Comment by Elkasitu** [comment] 2018-04-09 09:02
Ok so it turns out this is not a bug with domain resolution but it's specific to `create_date` and other datetime fields which use postgres' `NOW()` function.

The search you perform is technically correct, the problem is that the `NOW()` function returns a datetime with floating-point precision, so in the database your datetime will look like `2018-04-07 01:04:32.45642`, which is indeed greater than `2018-04-07 01:04:32`

This is difficult to patch (without resorting to hacks), and more importantly the gain-to-risk ratio is low so I don't think we'll be making a patch for these versions, but as a workaround you can add `.99999` to your datetime string which should work.

We'll try to fix this in master.

**Comment by flyingL123** [comment] 2018-04-09 16:03
Very interesting thanks @Elkasitu. As a workaround for now I am just including an additional condition that the IDs are not equal `[('create_date', '>', record.create_date), ('id', '!=', record.id)]`, but it would of course be great to not have to do that.

**Comment by sswapnesh** [comment] 2018-04-09 16:04
@Elkasitu What about domains already applied in odoo?
I would prefer adding (id,|=, record.id)

**Comment by pedrobaeza** [comment] 2020-01-25 17:58
Coming to this through codetriage.com. @Elkasitu was there a solution to this in master?

**Closed** 2023-03-30 13:08 UTC
Labels: Framework
