### ISSUE TITLE
Switzerland - Accounting: unable to update

### ISSUE THREAD

**Issue by alex71m-zz** [odoo/odoo#54463] opened 2020-07-14 16:38 UTC
Impacted versions: 13.0

Steps to reproduce: App -> Search for l10n_ch and try to upgrade

Current behavior: the update process stops with following message:

Error context:
View `l10n_ch_swissqr_template`
[view_id: 1783, xml_id: l10n_ch.l10n_ch_swissqr_template, model: n/a, parent_id: 1512]" while parsing /usr/lib/python3/dist-packages/odoo/addons/l10n_ch/report/swissqr_report.xml:2, near
<odoo>
    <data>

        <report id="l10n_ch_qr_report" model="account.move" report_type="qweb-pdf" string="QR-bill" name="l10n_ch.qr_report_main" file="l10n_ch.qr_report_main" attachment="'QR-bill-' + object.name + '.pdf'" menu="False" print_report_name="'QR-bill-%s' % object.name" paperformat="l10n_ch.paperformat_euro_no_margin"/>

        <template id="l10n_ch.qr_report_main">
            <t t-call="web.html_container">
                <t t-foreach="docs" t-as="o">
                    <t t-set="lang" t-value="o.partner_id.lang"/>
                    <t t-call="l10n_ch.l10n_ch_swissqr_template" t-lang="lang"/>
                </t>
            </t>
        </template>
    </data>
</odoo>

Expected behavior:

Video/Screenshot link (optional):

**Comment by treviser** [comment] 2020-08-08 10:20
Check this: https://github.com/odoo/odoo/issues/53822

**Comment by pedrobaeza** [comment] 2020-08-08 10:30
Yeah, closing as duplicate of #53822

**Closed by pedrobaeza** 2020-08-08 10:30 UTC
Labels: 13.0, Localization
