### ISSUE TITLE
Extra Move is created and duplicate the stock quants in packet drop

### ISSUE THREAD

**Issue by mrzingo** [odoo/odoo#27456] opened 2018-10-05 17:12 UTC
Impacted versions: 10 EE

Steps to reproduce:
Try to transfer the picking in a bad connection with packet drop.

Current behavior:
Duplicated stock move lines in the picking (Extra move) is created and doubling the quants transfer to the customer location.
Expected behavior:
Stock moves is transferred to the customer location without any extra moves (duplicates).

**Comment by pedrobaeza** [comment] 2018-10-11 15:58
Sorry, but not enough information is provided. You should provide the detailed steps for getting the error.

**Comment by mrzingo** [comment] 2018-12-12 12:06
Try to use this tool to simulate the issue.
https://jagt.github.io/clumsy/

**Comment by mrzingo** [comment] 2018-12-19 15:57
This also can be due to worker issues or exception due to limit time ?

**Comment by pedrobaeza** [comment] 2018-12-19 16:08
You still haven't provided more information

**Comment by yostashiro** [comment] 2019-01-12 07:36
Without packet loss, the issue can be reproduced with the following steps:

1. Create a delivery, reserve stock and make the state 'Available'.
2. Click on 'Validate' to show immediate transfer modal.
3. Open the same delivery in a different browser tab/window, click on 'Validate' to show immediate transfer modal.
4. Click 'Apply' of the immediate transfer modal from Step 2 (this changes the state of delivery to 'Done').
5. Click 'Apply' of the immediate transfer modal from Step 3, and this generates Extra Moves on top of the already processed moves from Step 4.

**Comment by sle-odoo** [comment] 2020-01-08 09:33
Closing since version 10 is not supported anymore.

Regards

**Closed by sle-odoo** 2020-01-08 09:33 UTC
Labels: 10.0, Logistics
