### ISSUE TITLE
[9.0] Description not saved when creating/updating tasks

### ISSUE THREAD

**Issue by micson1** [odoo/odoo#14422] opened 2016-11-22 02:15 UTC
Impacted versions: Version 9.0c-20161121

Steps to reproduce: Go to Project -> Create -> New task with description.

Current behavior: Description seems to be deleted/cleared when pressing save.

Expected behavior: Description should remain.

Video/Screenshot link (optional):

**Comment by 7hunderbug** [comment] 2016-11-22 02:32
I was about to raise the same ticket. Confirmed for nightly build of 10.0-20161121 (Community Edition) also.

**Comment by 7hunderbug** [comment] 2016-11-22 02:35
Apparently this bug has already been reported but not fixed yet? Duplicate of https://github.com/odoo/odoo/issues/14394 and https://github.com/odoo/odoo/issues/14351 apparently. Temporary fix at the bottom of issue thread https://github.com/odoo/odoo/issues/14351.

**Comment by qsm-odoo** [comment] 2016-11-22 10:22
Hello.
Yes, the issues mentioned above are duplicates of this issue. The fix was merged in 9.0c yesterday and should thus be available everywhere for 9.0 today.
10.0 fix will land in the upcoming days.

**Closed by qsm-odoo** 2016-11-22 10:22 UTC
