### ISSUE TITLE
[9.0] wont install properly on webfaction/wsgi due to lessc

### ISSUE THREAD

**Issue by aduijs** [odoo/odoo#8879] opened 2015-10-04 00:21 UTC
First of all, the error i am getting after the install is the same as the other lessc issue that is open, but mine wont go away after a blog install, nor does it render well the admin screen.

So this is a different issue which I am realy struggling with and dont seem to get it work properly in my webfaction environment.
- installed node + less (added paths and verified if both are executable from the cmd line
- josesapelli@web452 ~]$ less -V
- less 436 Copyright (C) 1984-2009 Mark Nudelman
- [josesapelli@web452 ~]$ npm -version
  2.11.3
- created a virtualenv to install odoo
- within the virtualenv:
- verified if LESS was still working
- git clone https://github.com/odoo/odoo.git
- pip install -r requirements.txt  (gevent wouldnt instll due to wheel errors, after removing gevent it installed all the addons)
- python setup.py install
- created the Database
- and browse to odoo:\

But still getting the "Could not execute command 'lessc" and the admin panel is missing quite some styles (does not render propetly)

Event installing the blog addon as some suggested doesnt make a difference.
So somehow odoo still cant get to less, but the cmd line does say otherwise.

Another suggestion was that the odoo search path is /usr/bin and that a symlink to lessc could work.

Unfortunately Webfaction doesnt allow you to SUDO so i was unable to create the symlink there.

Webfaction told me i should use myhomedir/bin since that is my personal bin.

After creating the symlink again the whole installation enchillada, but same result..

Hopefully here someone else got some briliant ideas, because mine are out. (is there a way to compile the less/css manually?)

**Comment by xmo-odoo** [comment] 2015-10-05 07:44
There is no way to compile the less files manually (it's done on the fly by the assets pipeline thing).

* interactive versus non-interactive login may not source the same files, in fact non-interactive users may not have a shell at all so there's no guarantee a PATH you set in `.profile` or `.bashrc` or whatever will be seen by whatever the web server runs under. Only way to know what the server sees is to push an application/page to it
* I don't know how what webfaction uses for WSGI, but it might be possible to set environment variables through it directly
* if it uses a custom wsgi boot script, you can alter `sys.path` via that
* last fallback, modify the Odoo source and append whatever you need to `sys.path`

**Comment by sle-odoo** [comment] 2015-10-05 11:34
@aduijs
Hello,
In your post you said that you installed "less", but it's "lessc" that you have to install. What is the distribution you're using on webfaction? Ubuntu/Debian? Which version?

Can you try to install less and less-plugin-clean-css from the npm installer? [Like explained in the doc](https://www.odoo.com/documentation/8.0/setup/install.html#source-install)

**Comment by aduijs** [comment] 2015-10-05 13:24
@sle-odoo 
Hi Simon,
yes lessc was installed via de npm installer
- [josesapelli@web452 ~]$ lessc -v
- lessc 2.5.3 (Less Compiler) [JavaScript]

As for the webfaction server: 
- CentOS 6 - 64bit

@xmo-odoo 
webfaction uses mod_wsgi 4.4.13/Python 2.7
you mentioned "Only way to know what the server sees is to push an application/page to it"
Isnt there a way to log what the application page is seeing?
Debugging con the current error message in the log "can not exucute lessc" doesnt help much

Y did alter my sys.path as well before, to insert the /homedir/bin but that didnt help either

**Comment by aduijs** [comment] 2015-10-08 13:26
any suggestions? still unable to install v9

**Comment by pedrobaeza** [comment] 2018-04-03 23:27
This is an install issue, but not a bug. I close it then.

I suggest you to see the way Odoo is installed in OCA CI, or go for other deployment solutions like Docker. Install scripts are in https://github.com/OCA/maintainer-quality-tools/blob/master/travis/travis_install_nightly

**Closed by pedrobaeza** 2018-04-03 23:27 UTC
Labels: 9.0, Framework

**Comment by aduijs** [comment] 2018-04-04 00:42
wow this was 2,5 years ago.. we are running 11 now . but yeah please close,
cant even remember how it solved it back then

2018-04-03 18:28 GMT-05:00 Pedro M. Baeza <notifications@github.com>:

**Comment by pedrobaeza** [comment] 2018-04-04 00:59
Yeah, I'm triaging some of the old issues. Cleaning the house we will have only the proper issues opened.
