### ISSUE TITLE
TypeError raised when try to manually write random string in datetime field

### ISSUE THREAD

**Issue by HardGITer** [odoo/odoo#34056] opened 2019-06-12 07:55 UTC
Impacted versions:
Odoo 12 community
Steps to reproduce:
1. Go to Sale -> Quotations
2. Open any quotation
3. Select date in validity_date(Validity on UI)
4. Manually input random string in validity_date field
5. Click on any place on form

Current behavior:
```python
Uncaught TypeError: Cannot read property 'format' of undefined
http://localhost/web/content/712-2ec683b/web.assets_common.js:2822
Traceback:
TypeError: Cannot read property 'format' of undefined
    at TempusDominusBootstrap4._setValue (http://localhost/web/content/712-2ec683b/web.assets_common.js:2822:288)
    at TempusDominusBootstrap4._change (http://localhost/web/content/712-2ec683b/web.assets_common.js:2823:228)
    at Function._jQueryHandleThis (http://localhost/web/content/712-2ec683b/web.assets_common.js:3099:73)
    at jQuery.fn.init._jQueryInterface [as datetimepicker] (http://localhost/web/content/712-2ec683b/web.assets_common.js:3099:223)
    at HTMLInputElement.<anonymous> (http://localhost/web/content/712-2ec683b/web.assets_common.js:3102:42)
    at HTMLDocument.dispatch (http://localhost/web/content/712-2ec683b/web.assets_common.js:892:451)
    at HTMLDocument.elemData.handle (http://localhost/web/content/712-2ec683b/web.assets_common.js:865:173)
```
Expected behavior:
Should not raise an error

**Comment by Yenthe666** [comment] 2019-06-12 08:10
Isn't this a bit of common sense though? Anyways, I guess it can be improved. @nim-odoo perhaps for you? I know you did some datetime changes in the past.

**Comment by sswapnesh** [comment] 2019-06-12 14:20
Duplicate of https://github.com/odoo/odoo/issues/29551

**Comment by Yenthe666** [comment] 2019-06-12 14:23
good catch and fair point.

**Closed by Yenthe666** 2019-06-12 14:23 UTC
Labels: 12.0, Framework
