### ISSUE TITLE
Delivery Order Quantity no Updates

### ISSUE THREAD

**Issue by goyanipankaj** [odoo/odoo#43331] opened 2020-01-15 11:09 UTC
Impacted versions: 11.0

Steps to reproduce:
1. Create new sale order >> Confirm Sale Order
2. After edit sale order line in quantity with reduce quantity
(Ex. Before Qty: 30 (unit's)     After change Qty: 22 (unit's) 

Current behavior:
Delivery order in no update quantity

Expected behavior:
Also under the delivery order quantity should be change as per sale order.

Video/Screenshot link (optional):
Runbot system link: http://874842-11-0-10dc32.runbot36.odoo.com/web?#id=36&view_type=form&model=sale.order&menu_id=521&action=696

**Comment by pedrobaeza** [comment] 2020-01-15 12:25
That's expected and is warned in a message that you discarded without reading it apparently. This is a design decision because there are multiple reasons for decreasing quantities on sales order without affecting on deliveries, and you can have some stock reserved that has to be manually reviewed.

Closing as no bug, but intended behavior.

**Closed by pedrobaeza** 2020-01-15 12:25 UTC

**Comment by goyanipankaj** [comment] 2020-01-15 12:28
Thanks for your reply, but any solution for that?

**Comment by pedrobaeza** [comment] 2020-01-15 12:29
Change the quantity manually in the delivery order.

**Comment by goyanipankaj** [comment] 2020-01-15 12:57
Okay thanks for quick reply.
