### ISSUE TITLE
version 10 enterprise studio bug

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#16056] opened 2017-03-25 08:28 UTC
![screenshot from 2017-03-25 13-58-21](https://user-images.githubusercontent.com/311413/27270604-022be8ce-54dd-11e7-8fb5-31b509320533.png)
Impacted versions: enterprise 10

Steps to reproduce:  install studio and generate bug when click on next after setup model.

```
Current behavior:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 878, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 870, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 5449, in onchange
    value = record[name]
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 5186, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 871, in __get__
    self.determine_draft_value(record)
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 991, in determine_draft_value
    self._compute_value(record)
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 926, in _compute_value
    getattr(records, self.compute)()
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 156, in _get_desc
    path = modules.get_module_resource(module.name, 'static/description/index.html')
  File "/usr/lib/python2.7/dist-packages/odoo/modules/module.py", line 215, in get_resource_path
    mod_path = get_module_path(module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/module.py", line 165, in get_module_path
    files = [opj(adp, module, manifest) for manifest in MANIFEST_NAMES] +\
  File "/usr/lib/python2.7/posixpath.py", line 68, in join
    if b.startswith('/'):
AttributeError: 'bool' object has no attribute 'startswith'
```

![screenshot from 2017-03-25 13-58-21](https://user-images.githubusercontent.com/311413/27270604-022be8ce-54dd-11e7-8fb5-31b509320533.png)

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment] 2017-06-14 12:03
Hi @tejastank,

Thank you for your report.
I can no longer reproduce this on the latest source code (neither on the latest runbots).
Can you please update your Odoo and try again?

Regards,
Yenthe

**Comment by tejastank** [comment] 2017-06-19 05:16
@Yenthe666 Their are major bugs you failed to produce, let official guys to check.

@Yenthe666 big thanks for your bad support and force to close / hide bugs in odoo.

**Comment by Yenthe666** [comment] 2017-06-19 06:17
@tejastank,

I haven't even closed your report.. I'm simply asking you for more feedback on how to reproduce this bug so I can confirm it and ask somebody to look into it.
Please make a video on the latest runbot so I can reproduce this?

Regards,
Yenthe

**Comment by tejastank** [comment] 2017-06-19 07:04
@Yenthe666 after many month in case you can't detect its useless, In case a odoo not response to customer / community in 2/3 weeks and world get suffered.

please quite it without feedback. @erpnnext is also good product compare to odoo.

So stop flattery of odoo and its bugs, leave in case you don't face anything which people reported.

I suggest your(@Yenthe666 ) kind of falletery to immidate check my bugs as I reported, not after months and years.

**Comment by mart-e** [comment] 2017-06-19 09:59
@tejastank being aggressive never helps your case.

Yenthe asked you information to be able to reproduce your issue (what lacks in many of the issues you have reported). Maybe it was already fixed in a recent version. We can only know that if we are fully aware on how to reproduce the bug. You can always check on the runbot ([community](http://runbot.odoo.com/runbot/) or [enterprise](http://runbot.odoo.com/runbot/repo/git-github-com-odoo-enterprise-7)) if you want to easily test on the latest version.

Seeing your error, it looks like there was a missing manifest or something. So I guess you have create a module or something like this. This is the kind of information we need.

You have probably noticed there is many opened issues, so yes, it takes time to check it. We have [always said](https://github.com/odoo/odoo/wiki/Contributing#reporting-issues) that the issues will be threaded in a lower priority. Any feedback made is greatly appreciated, may he work for Odoo or not.

If you reject people trying to solve your issue, I guess it is not that important...

**Closed by mart-e** 2017-06-19 09:59 UTC
Labels: need information

**Comment by tejastank** [comment] 2017-06-22 13:40
@mart-e, It seems you too much aggressive.

Its nothing thier more module or anything else.
Just official code only.

If their any new module, I additional their, I sure feed.

It's issue we face that we reported, in case odoo guys had now nagative vision for community than you can avoid it.

**Comment by mart-e** [comment] 2017-06-22 13:47
@tejastank if you give me exact steps on how to reproduce the problem, then we can reopen and confirm the bug. Use the [runbot](http://runbot.odoo.com/runbot/repo/git-github-com-odoo-enterprise-7), make screenshots, a youtube video or whatever but we need to be able to reproduce ourself the issue.
