### ISSUE TITLE
[11.0] When remove attribute in product affects some details of the variant (barcode,price)

### ISSUE THREAD

**Issue by Boss1669** [odoo/odoo#25033] opened 2018-06-03 09:15 UTC
Impacted versions: 11.0

Steps to reproduce: Create product , Add Attribute and Attribute Value to it
For Example
Product A
Attribute : Kilogram, Attribute Value : 5,6
Attribute : Color, Attribute Value : Pink,Blue
Go to ->Catalog -> Products variant manually input barcode or in price list add these product to pricelist and set a specific price.
Go to -> Catalog -> Products, manually remove one of the attribute let say you remove Color attribute. 
  
Current behavior: The barcode will automatically remove from each variant, also when create the sales with the pricelist it doesn't show the price the default will be 1

Expected behavior: Barcode and Pricelist should stay the same

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment] 2018-06-04 15:01
If I'm not mistaking this is working as intended and this is a known 'limitation' of the current product/variant setup.
@mart-e and @pedrobaeza I'm sure one of you can confirm this. I believe it recomputes all the other variants causing this behaviour.

**Comment by pedrobaeza** [comment] 2018-06-04 15:44
This is not an error, but a misunderstanding on how variant system works:

- About the price, you put the price on the variant, so the price is reflected as an extra price for one of the attributes, not the template list price. When you removed that attribute, you lose the extra price. So put the price on the template. Maybe some visual guidance on variant when readonly mode putting <template_list_price>+<sum of extra prices> would help for avoiding these confusions, but any way, it's not a bug.

- About the barcode, the system takes in different place (the template or the variant) this data depending on the number of variants. If you are playing with only one, it's also a normal behavior, so please depending on the number of variants, set it on template or in the variants.

Closing by the reasons stated above.

**Closed by pedrobaeza** 2018-06-04 15:44 UTC
Labels: 11.0, Services

**Comment by Yenthe666** [comment] 2018-06-05 05:36
Thanks for the extra info @pedrobaeza, better explained than me.
