### ISSUE TITLE
Downloaded pdf from odoo11 cannot be viewed by pdf viewer

### ISSUE THREAD

**Issue by tisadmin96** [odoo/odoo#70571] opened 2021-05-09 06:20 UTC
Downloaded sale/invoice pdf from odoo11 cannot be viewed by pdf viewer. When I try to open the pdf by pdf viewer it showing like  " File type HTML document (text/html) is not supported ". Actually I have installed odoo 12,13,14 etc but there is no issue while downloading pdf from these version and pdf can be viewed properly in the remaining version. Both odoo 11 and wkhtmtopdf are latest version. Only issue when I try to download invoice/sale pdf from odoo 11 latest version. Anyone please help me to find out a solution for this issue..

![Screenshot from 2021-05-09 11-42-32](https://user-images.githubusercontent.com/76433223/117562325-c24aff80-b0bb-11eb-83a6-3c491ad286fe.png)

**Comment by pedrobaeza** [comment] 2021-05-09 10:03
Sorry, but 11.0 is a deprecated version that is already not being supported, so any bug report about this old version won't be attended, and thus I close this issue. Please check if the problem is still there in new versions, and if so, you can open a new issue regarding that version.

Even more, this is a deployment thing. A little tip: check wkhtmltopdf version.

**Closed by pedrobaeza** 2021-05-09 10:03 UTC
