### ISSUE TITLE
[account_anglo_saxon]Incongruence of price_unit in journal items

### ISSUE THREAD

**Issue by JulioSerna** [odoo/odoo#12307] opened 2016-06-06 17:38 UTC
Impacted versions:
- 8.0

Steps to reproduce:
- Create Product in real time with Costing Method **Standard Price** and Cost Price **$ 120**
- Create Sale Order and confirm
- Change Cost Price to **$ 110**
- Transfer Picking of sale order
- Create invoice from picking
- Validate invoice

Current behavior:
- The journal items by transfer picking are make by **$ 110** this is the `price_unit` from the product not is the price_unit from picking
- The journal items invoice by COGS are make by **$ 120** this is the `price_unit` from picking not is the price unit from the product

Expected behavior:
- The **price_unit** into journal items from picking/invoice(COGS) should have the same source from the picking or from product 

Video/Screenshot link (optional):
https://www.youtube.com/watch?v=j0ucElu8Up4

**Comment by orchidinfosys** [comment] 2016-06-07 00:11
Check the cost in stock move lines. This will not be updated at the time of
real transfer. It's calculated at move creation. Also check quant to know
the stock value of the transfer.

**Comment by nim-odoo** [comment] 2016-06-17 12:01
Hi,
As mentioned by @orchidinfosys , the stock move unit price is calculated at the creation, i.e. when you confirm the SO. Therefore, to solved the issue, one should do something like: http://pastebin.com/yVwdkk1K Which doesn't seem very clean...
Is there actually a use case where this is an issue? It just seems to me that it makes more sense to configure your product in 'Real Price' when it comes to appropriate accounting and stock valuation.

**Comment by nim-odoo** [comment] 2016-06-17 12:03
@jco-odoo what do you think?

**Comment by hbto** [comment] 2016-06-22 15:36
@nim-odoo 

The use case was already presented to you

> Create Product in real time with Costing Method Standard Price and Cost Price $ 120
> Create Sale Order and confirm
> Change Cost Price to $ 110
> Transfer Picking of sale order
> Create invoice from picking
> Validate invoice

Solution cannot change Costing Method from STD to REAL at will.

Regards.

**Comment by nim-odoo** [comment] 2016-06-22 15:56
@hbto I read the use case, but I'm still convinced that it makes more sense to configure your product in 'Real Price' when it comes to appropriate accounting and stock valuation.

Moreover, the solution I provided works only if you create a SO for a product which is not available in stock. If the product is available, then the stock move is already linked to quants, and you obviously cannot change the cost of existing quants (that's why I filter on states 'draft' and 'confirmed').

**Comment by nim-odoo** [comment] 2016-06-22 15:57
@beledouxdenis

**Comment by nhomar** [comment] 2016-06-22 16:10
@nim-odoo You are sugesting that I change 100% of the valuation methodology of a company just because you do not want to solve a clear issue?.

Without even considere that when I move to another valuation method, then it will bring MORE problems unknown (remember in odoo real time is new Standard exists since well.... always and it is almost brainless, and BTW for production Odoo's real time does not work properly from a conceptually PoV).

dude bad bad bad answer.

**Comment by beledouxdenis** [comment] 2016-06-22 16:14
@qdp-odoo @jco-odoo Can you have a look at this issue ? I am not expert at all regarding this.

**Comment by nim-odoo** [comment] 2016-06-22 16:40
@nhomar : no. I'm first suggesting a fix (http://pastebin.com/rtXPTHtn), which works for what I have tested. As you point out, "Standard" valuation exists since always, and the use case you describe has never been taken into account since then. Therefore, considering the obviously intrusive nature and limited scope of the fix, and the fact that this behavior has (to my knowledge) not been reported as a major issue, I am wondering whether it is something appropriate to introduce in a stable version.
Although I understand that the actual behavior has a negative impact on your project, I must also consider the impact of such a change for other users.

I also suggest a solution, "Real Time", which seems more appropriate for the use case. Do I suggest to change 100 % of the valuation methodology of a company which is running in production? No...

**Comment by hbto** [comment] 2016-06-22 19:52
@nim-odoo 
> and you obviously cannot change the cost of existing quants (that's why I filter on states 'draft' and 'confirmed').

Yes, you can, as it has already been done on Landed Cost:
https://github.com/odoo/odoo/blob/8.0/addons/stock_landed_costs/stock_landed_costs.py#L264-L270

The thing is that you have only focused the right behaviour on REAL,

Other Costing Methods have been _slightly_ overlooked

With your proposal what you can do is apply it and provide strong testing on the costing method.

Regards.

**Comment by qdp-odoo** [comment] 2016-06-23 11:52
My personal opinion is: changing the standard price of a product is something you should only do with precaution. If you're use to change that twice a week, then you don't use the system as it is intended.

So when you do that, you have to manually make adjustments in your accounting, I'd say, as it is somehow an exceptional case and we don't want to put exceptions in the code for exceptions in real life.

**Comment by hbto** [comment] 2016-06-23 14:30
Hello @qdp-odoo 

> My personal opinion is: changing the standard price of a product is something you should only do with precaution.

You are right, though as you could know Standard Price does change in real life process, and 
that is something that should be taken into account, 

but here we are not discussing the frequency rate at which a customer is changing the standard price 
of a product, we are discussing the _issue_ posted by @JulioSerna, which is a real case scenario
that do happen to everybody no matter if the price is changed twice a week or twice  a year.

The issue is that it actually happens and need to be fixed.

if you are in a manufacturing process with many parts and those many parts at some point the process got price changed, you are intending that the user tries to find out which products have changed in prices and figures it out what should be done in accounting?

The problem even is not that the quant most be changed or that the price cannot be changed twice a week. the problem is that picking should take the actual standard price at transaction date, and not the 
price that was store the stock.move in draft state was created, at the state that we are discussing _not even one quant has been created, so there is no need to change cost/prices at quant_ @nim-odoo 

So I keep pushing the problem is not that the frequency rate in price changes, problem is 
_use the actual standard price @ transaction date, and not the historical price recorded at creation date of document_

Best Regards

**Comment by nhomar** [comment] 2016-08-16 22:29
@qdp-odoo @jco-odoo @nim-odoo @odony @fpodoo 

My customer under this enterprise licence mentioned me this:

```
Dear @JulioSerna ,
 
I appreciate all your help and I would like to close this chapter as soon as possible.
Your performed solution is fulfilling our requirements and could be loaded into the various instances.
 
I have in the meantime asked help in this matter over a group in LinkedIn from accounting professionals. All of my precious colleagues, at least from 15 different countries which answered to me about this subject, came to the same conclusion like me and are mentioning IAS 2 and IAS18 as reference for their opinion. You need to show always the costs to which you shipped the product and not the ones to which it was originally sold.

Odoo needs to review here its opinion.
 
Best regards
```

@JulioSerna Proposed a simple solution with an action server, but dudes seriously "review your sources"

Even with our solution (which will be shared with a proper PR) we stay yet open with the process when incoice and picking are Invoice First Picking after (as v9.0 works by default).

Everything works like a charm with Invoice From Picking (feature missed in v9.0).

Conclusions: This issue has been one of the worst answered ever by Odoo, if you have 20 move per month odoo is ok, make a manual revision is fine but with thousand of moves and thousand of products and variants, this is simple unauditable.

**Comment by Yenthe666** [comment] 2017-11-26 15:00
Hi all,

This should have been fixed way back with https://github.com/odoo/odoo/pull/15612/commits/b866c0c4af9254af0b99ef1d3fdb0b12edb23cf7

Regards,
Yenthe

**Closed by Yenthe666** 2017-11-26 15:00 UTC
Labels: blocked
