### ISSUE TITLE
onchange with 'length' field is broken 

### ISSUE THREAD

**Issue by grindtildeath** [odoo/odoo#41353] opened 2019-12-04 15:26 UTC
Impacted versions:
12.0, but probably any other versions

Steps to reproduce:
 - Install `delivery` and `stock` modules
 - Go to Inventory > Configuration > Settings
 - Mark 'Delivery Packages' and 'Product Packagings'
 - Implement a basic onchange method on model `product.packaging` to change the field `length` (this is only a dummy example, but let's assume we want to update `length` according to `width`):
```
    @api.onchange('width')
    def _onchange_width(self):
        self.length = self.width
```
 - Now go to Inventory > Master Data > Packages
 - Create a new Package and create a new Package Type (`product.packaging`) using 'Create and edit'
 - Set a value (e.g. 1000) on `width` to play the onchange:
![image](https://user-images.githubusercontent.com/778828/70153570-72d6f780-16af-11ea-8401-86f696fa73f9.png)

Current behavior:

 - The onchange doesn't update the field correctly
 - The HTTP request is correct:
![image](https://user-images.githubusercontent.com/778828/70153518-5d61cd80-16af-11ea-802c-58058a051996.png)
 - However, the JS object containing the onchange values is mishandled by `_.each` at https://github.com/odoo/odoo/blob/12.0/addons/web/static/src/js/views/basic/basic_model.js#L1594 , and this is what happens by setting following loggers:
```
        console.log("values: " + values)
        console.log(values)
        _.each(values, function (val, name) {
            console.log("val: " + val)
            console.log("name: " + name)
```
![image](https://user-images.githubusercontent.com/778828/70154217-728b2c00-16b0-11ea-8e7d-51d22cf64eb9.png)

 - There is an overflowing loop until "name: 999" as it uses the `length` value defined in the onchange Object.
 - This happens because of a bug in `underscore.js` on `each` function, that is implemented as follows:
```
  // Collection Functions
  // --------------------

  // The cornerstone, an `each` implementation, aka `forEach`.
  // Handles raw objects in addition to array-likes. Treats all
  // sparse array-likes as if they were dense.
  _.each = _.forEach = function(obj, iteratee, context) {
    iteratee = optimizeCb(iteratee, context);
    var i, length;
    if (isArrayLike(obj)) {
      for (i = 0, length = obj.length; i < length; i++) {
        iteratee(obj[i], i, obj);
      }
    } else {
      var keys = _.keys(obj);
      for (i = 0, length = keys.length; i < length; i++) {
        iteratee(obj[keys[i]], keys[i], obj);
      }
    }
    return obj;
  };
```
 - AFAIU getting length on the object returns 1000 (the value of length field to update) instead of the length of the object, so we're doomed...

Expected behavior:

 - Being able to change the value of a field called `length`

OPW: 2151164

**Comment by pedrobaeza** [comment] 2019-12-04 15:35
This is a problem with JS itself, as `length` is a reserved word there. The module with that field is Odoo core or is in your custom code? We have a linter in OCA for avoiding this field name as someone (I think it was @gdgellatly) was hit by this problem in the past.

**Comment by grindtildeath** [comment] 2019-12-04 15:37
@pedrobaeza The field is defined in `delivery` module: https://github.com/odoo/odoo/blob/12.0/addons/delivery/models/product_packaging.py#L12

**Comment by pedrobaeza** [comment] 2019-12-04 15:38
Ouch, that's a deeper problem.

@ged-odoo are you aware of this problem with the reserved word `length`?

**Comment by Yenthe666** [comment] 2019-12-04 16:32
Interesting that nobody got hit by this one before. That's indeed because the JS interprets it as a built-in. @pedrobaeza maybe we should create an official OPW for this one?

**Comment by pedrobaeza** [comment] 2019-12-04 16:37
Well, it has difficult solution except renaming the field, and that's not going to happen on stable. You can raise an OPW if you think it helps.

**Comment by Yenthe666** [comment] 2019-12-04 17:04
I think we should at least try to avoid it for the future 14 to start with :) I've made an OPW because I know this one will get burried otherwise. OPW `2151196`

**Comment by gdeb** [comment] 2019-12-04 20:05
wow, that's interesting. I was aware that `length` is handled in a weird way by the JS language, but I was not aware that `_.each` was not treating it properly. 

We are moving to ES6 in the future, and new code will not use `_` that much. Still, we need to be careful when manipulating object with arbitrary keys.

**Comment by ged-odoo** [comment] 2019-12-04 20:05
dammit, I always have the wrong user...

**Comment by Yenthe666** [comment] 2019-12-06 07:33
This issue has been confirmed by Odoo. Official feedback from the ticket:

> Hello,
Indeed, we should rename this field for a future version. Thanks for the feedback.

I've now asked if this will become a PR right now or an internal task. This won't be changed/fixed before V14 for sure though.

**Comment by Yenthe666** [comment] 2019-12-06 15:23
Hi guys,

The Odoo team has made an internal task and this will be fixed for the upcoming V14 by the logistics team. As this cannot be changed in a stable we can close this ticket.

Regards,
Yenthe

**Closed by Yenthe666** 2019-12-06 15:23 UTC
Labels: 12.0, Confirmed, Framework, OE

**Comment by pedrobaeza** [comment] 2019-12-06 15:32
@grindtildeath a workaround you can do is:

- Create a related non readonly field to this field with other name (for example `length_alt`).
- Hide the `length` field in the view and show this one.
- Do the onchange stuff in this related field.

**Comment by gdgellatly** [comment] 2019-12-20 18:32
@grindtildeath Yeah this is part of underscore JS. _ expects a length property in its each method, and obviously they clash meaning the field gets consumed early. Drove me nuts for years with Odoo telling me nothing was wrong with web client.

`lngth` works. You get used to it pretty quickly and soon you can't even spell it right anymore.

**Comment by gdgellatly** [comment] 2019-12-20 18:58
see this, maybe it is just a missed forward port https://github.com/OCA/OCB/commit/25616b9f2bbca3f03dbde1dc81a57986241c1aab

**Comment by grindtildeath** [comment] 2020-01-13 16:02
FTR: https://github.com/odoo/odoo/pull/43222
