### ISSUE TITLE
POS 8.0: change always sent to first cash journal

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#6975] opened 2015-06-06 21:18 UTC
Here is the scenario to reproduce the bug:
1) connect as admin to runbot v8 or to a local up-to-date odoo v8 and make sure that the "point_of_sale" module is installed
2) Go to "Point of Sale > Config > Payment methods" and create a new payment method:
Name : Cash2
Code : CASH2
Type : Cash
Default credit/debit account : select any account
3) Go to "Point of Sale > Config > Point of sales" and edit "Main" : add "Cash2" to the "Available payment methods"
4) Go to "Point of sale > Daily Operations > Your session"
If you have a running session, close it first.
Click on "New session"
5) Once the frontend of the POS has started, click on "250g Lays Pickels" (1.48 €) to add it to the ticket. Then click on "Cash2" and enter "10.0" as the amount of cash given by the customer. Odoo will tell you to return a change of 8.52 €. Click on "Validate".
6) Close the POS frontend. Then click on "Close session" ; In the "Summary by Payment Methods", for the "Total transactions", you have
Cash Journal (test) : -8.52 €
Cash2 : 10 €

So the change is always sent to the first cash journal, not the one selected in the POS interface !

**Comment by Yenthe666** [comment] 2017-03-14 14:54
Hi @mart-e,

This issue is back in Odoo V9. We did the same scenario in V9 as written above and used another payment method than the default cash method named cash2 but it still uses cash:
![image](https://cloud.githubusercontent.com/assets/6352350/23906513/7aecbc80-08ce-11e7-9547-3ee435fa0bbf.png)
![image](https://cloud.githubusercontent.com/assets/6352350/23906537/8f8b39f0-08ce-11e7-9731-b6a190fb1329.png)

**Comment by Yenthe666** [comment] 2017-03-20 10:59
@mart-e we're still running into this issue and have a live customer which his accounting is going wrong because of this. Any update? 😉

**Comment by mart-e** [comment] 2017-03-20 13:17
@Yenthe666 I don't get it, on the screenshot you show me it uses Cash 2 for both lines, so the expected behaviour

**Comment by Yenthe666** [comment] 2017-05-30 07:00
Hey @mart-e,

An update on this one as I finally found the time to spit this through.
It turns out that we had two payment methods of the type cash, from which Odoo always takes the first. This is more of a functional configuration mistake than a bug in Odoo.
Closing as this can be bypassed by just configuring one cash payment method (which is the desired behaviour).

Regards,
Yenthe

**Closed by Yenthe666** 2017-05-30 07:00 UTC
