### ISSUE TITLE
Exception during JSON request handling.

### ISSUE THREAD

**Issue by rokealva83** [odoo/odoo#31795] opened 2019-03-12 15:09 UTC
Impacted versions: 12.0

Steps to reproduce: 
1. Install Odoo with demo data
2. Install CRM
3. Change setting in Demo user  Notification Management to Handle in Odoo [Image 1](https://nimb.ws/Xy4WO6)
4. In any Opportunity change Saleperson in Demo user [Image 2](https://nimb.ws/I8kamX)
5. Login with Demo user
6. Open notifications and click to notification [image 3](https://nimb.ws/piqcJn)

Expected behavior:
I think must open opportunity

Current behavior:
`Odoo Server Error
Traceback (most recent call last):
  File "/home/rokealva/Production/immo_spader/odoo-12.0/odoo/http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/rokealva/Production/immo_spader/odoo-12.0/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/rokealva/Production/immo_spader/odoo-12.0/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/rokealva/Production/immo_spader/odoo-12.0/odoo/http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "/home/rokealva/Production/immo_spader/odoo-12.0/odoo/http.py", line 320, in _call_function
    raise werkzeug.exceptions.BadRequest(msg % params)
werkzeug.exceptions.BadRequest: 400: Bad Request`

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2019-03-12 15:37
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by rokealva83** [comment] 2019-03-12 16:12
I cant reproduce the problem in runbot. Everything works there
I added video [linl](https://nimb.ws/eqvDwT)

**Comment by pedrobaeza** [comment] 2019-03-12 16:23
Then the problem is in you side, due to outdated code or custom/third party modules.

Closing this, but if you get to reproduce the problem in standard, reply to this thread or create a new issue.

**Closed by pedrobaeza** 2019-03-12 16:23 UTC
Labels: Need information

**Comment by rokealva83** [comment] 2019-03-12 16:31
Its very interesting, but i dont use any modules. Only your [Odoo](https://github.com/odoo/odoo)  Branch 12.0
