### ISSUE TITLE
[9.0] mail_massmailing fails with error 'mail.mail' object has no attribute '_ids'

### ISSUE THREAD

**Issue by mmattes** [odoo/odoo#8734] opened 2015-09-26 20:43 UTC
Sending Mass Mails doesnt work currently as the error 'mail.mail' object has no attribute '_ids' occurs. 

Here the content from the odoo-server.log:

2015-09-26 15:18:14,449 10625 ERROR odoo-live openerp.addons.mail.models.mail_mail: failed sending mail (id: 4) due to 'mail.mail' object has no attribute '_ids'
Traceback (most recent call last):
  File "/opt/odoo/addons/mail/models/mail_mail.py", line 216, in send
    email_list.append(mail.send_get_email_dict(partner=partner))
  File "/opt/odoo/openerp/api.py", line 221, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 538, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/opt/odoo/addons/mass_mailing/models/mail_mail.py", line 92, in send_get_email_dict
    res = super(MailMail, self).send_get_email_dict(cr, uid, ids, partner, context=context)
  File "/opt/odoo/openerp/api.py", line 223, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 345, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/addons/mail/models/mail_mail.py", line 168, in send_get_email_dict
    body = self.send_get_mail_body(partner=partner)
  File "/opt/odoo/openerp/api.py", line 221, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 538, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/opt/odoo/addons/mass_mailing/models/mail_mail.py", line 69, in send_get_mail_body
    for match in re.findall(URL_REGEX, self.body_html):
  File "/opt/odoo/openerp/fields.py", line 806, in __get__
    record.ensure_one()
  File "/opt/odoo/openerp/models.py", line 5360, in ensure_one
    if len(self) == 1:
  File "/opt/odoo/openerp/models.py", line 5559, in __len__
    return len(self._ids)
AttributeError: 'mail.mail' object has no attribute '_ids'

**Comment by apr-odoo** [comment] 2015-09-29 15:08
seems fixed. If not, can you give me more infomation please ? I can't reproduce

**Comment by mmattes** [comment] 2015-09-30 05:59
I pulled the latest source yesterday but the error still occurs. Here is what I do: 

1.) Go to Mass Mailing and click on Create
2.) Type in a Subject, choose the Recipients from the Customers list
3.) Define a Mail Body by dragging a Header, Body and Footer Template into the Mail Body field, do not do any special modification on it.
4.) Click on Test Mailing > Send Sample Mail will works fine but when I click on Send to all then it get sheduled and later on I can find the error in Settings > General Settings > Email 

Im not a python expert but the mail.mail.py send_get_mail_body hase changed compared to 8.0 and adds now statistic_ids to the mail body if im right and that new part seems to cause the error on my installation.

**Comment by kga-odoo** [comment] 2015-09-30 06:07
Agree with @mmattes 
it gives error for mass mailing having body.
for @apr-odoo , There is an issue created for this already in master. 
Issue: https://www.odoo.com/web#id=649626&view_type=form&model=project.issue&action=963&active_id=681

**Comment by tde-banana-odoo** [comment] 2015-09-30 09:31
Fixed in 9 at commit b28199a6d68defb33d88fa4371d632c62bfe5b28  .

**Closed by tde-banana-odoo** 2015-09-30 09:31 UTC
Labels: confirmed
