### ISSUE TITLE
Purchase Order Workflow breaks on cancel

### ISSUE THREAD

**Issue by miamoebel** [odoo/odoo#2515] opened 2014-09-18 10:13 UTC
v7.0-20140623-231029

Hi,

Reproduce:

Create an purchase order and set invoicing control to be based on lines or shipments. Now confirm and go to incoming shipment. Cancel shipment and purchase order. Go to database and you will see the workflow instance for that purchase is still active (instead of complete).

This is because there is one remaining workitem with activity invoice_end.

Solution:

Create an workflow transition between invoice_end and cancel with signal "purchase_cancel".

I found this bug, when i realized that some procurements where still in state running after the purchase order was canceled.

Regards,
Christian

**Comment by StefanRijnhart** [comment] 2015-09-04 07:55
Duplicate of #6925

**Closed** 2017-03-14 16:21 UTC
