### ISSUE TITLE
CRITICAL issue included on last core update

### ISSUE THREAD

**Issue by anajuaristi** [odoo/odoo#6358] opened 2015-04-17 09:47 UTC
Hi

Regression appaired on core. We detected this morning that stock files has been changed recently 

  File "/opt/odoo/v8/core/addons/stock_account/stock_account.py", line 263, in action_done
    res = super(stock_move, self).action_done(cr, uid, ids, context=context)
  File "/opt/odoo/v8/core/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/v8/core/addons/stock/stock.py", line 2398, in action_done
    self.check_tracking(cr, uid, move, move.restrict_lot_id.id, context=context)
  File "/opt/odoo/v8/core/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/v8/core/addons/mrp/stock.py", line 40, in check_tracking
    super(StockMove, self).check_tracking(cr, uid, move, lot_id, context=context)
  File "/opt/odoo/v8/core/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/v8/core/addons/stock/stock.py", line 2197, in check_tracking
    self.check_tracking_product(cr, uid, move.product_id, lot_id, move.location_id, move.location_dest_id, context=context)
  File "/opt/odoo/v8/core/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/v8/core/addons/stock/stock.py", line 2191, in check_tracking_product
    raise osv.except_osv(_('Warning!'), _('You must assign a serial number for the product %s') % (product.name))

Now it's not possible making DONE stock moves including trazeable products.
Move is correct, quants are correctly asigned but it's imposible making move done.

**Comment by anajuaristi** [comment] 2015-04-17 14:06
Tested on runbot 
http://62818-8-0-forwardport-mat-18a0ba.runbot6.odoo.com/web?db=62818-8-0-forwardport-mat-18a0ba-all

Steps to reproduce:

Create product trazeable 
Make inventory for it including a lot
Create a picking including this product
"check availability" on picking so quant with lot is correctly assigned to move

Try to process the single move --> this warning is shown
Warning!
You must assign a serial number for the product ProductTrazeable

It's impacting in manufacturing where very usually is needed consuming materials individually and not using wizards.
Thank you

**Comment by tejastank** [comment] 2015-04-20 17:48
Same problem faced

**Comment by pedrobaeza** [comment] 2015-04-20 18:29
Please fix it.

**Comment by nhomar** [comment] 2015-04-20 18:47
I am agreed it is an issue (not tested on my side yet).

BUT the last answer I receive around this (in other places it is happening) they answer me they will not improve the stock.move behavior because user should use always a picking, I do not remember the issue where we received such answer but it clearly is an issue.

Regards.

**Comment by anajuaristi** [comment] 2015-04-20 18:58
BUT.. it's not improving anything... IT's just not breaking existing functionality.
One week before we could make done directly stock.moves. Today we can not. If we never did stock.moves directly we would never found the problem so if they gave you such an answer they are mistaken. 
People is using frecuently to make done stock moves. It's only failing on trazeable moves, even if assigned quant includes a lot so warning is wrong.

**Comment by nhomar** [comment] 2015-04-20 19:33
2015-04-20 13:58 GMT-05:00 Ana Juaristi <notifications@github.com>:

> BUT.. it's not improving anything... IT's just not breaking existing
> functionality.
> One week before we could make done directly stock.moves. Today we can not.
> If we never did stock.moves directly we would never found the problem so if
> they gave you such an answer they are mistaken.
> People is using frecuently to make done stock moves. It's only failing on
> trazeable moves, even if assigned quant includes a lot so warning is wrong.
>

I agree


-- 
--------------------
Saludos Cordiales

  [image: --]
Nhomar Hernandez
[image: http://]about.me/nhomar
     <http://about.me/nhomar?promo=email_sig>

**Comment by odony** [comment] 2015-04-21 13:51
@anajuaristi @tejastank  Do you have any idea of where this "regression" occurred, in terms of revision number? When was your last update where you think it worked? (You can use `git reflog` in any repository to see the list of operations updates/pull you have done)?

**Comment by odony** [comment] 2015-04-21 16:34
@jco-odoo FYI ;-)

**Comment by oihane** [comment] 2015-04-23 14:22
Hi @odony @anajuaristi told me to look into the reflog, and this is what I got:
```
2492503 HEAD@{5}: pull: Fast-forward
17c1556 HEAD@{6}: pull: Fast-forward
ddb900c HEAD@{7}: pull: Fast-forward
0c964f0 HEAD@{8}: clone: from https://github.com/odoo/odoo.git
```
Wishing it would help, thank you

**Comment by pedrobaeza** [comment] 2015-04-26 19:12
I'm not able to find the exact commit where the problem is brought, but it's caused by this line: https://github.com/odoo/odoo/blob/8.0/addons/stock/stock.py#L2391, that is called with _restrict_lot_id_ empty (because you have it assigned via reserved quants).

**Comment by tejastank** [comment] 2015-04-27 05:08
@rco-odoo  FYI ;-) Enough information you had now, we expect to soon fix this. So we can utilize it.

**Comment by jco-odoo** [comment] 2015-04-27 07:47
I am sorry but the reflog is useless and I don't know what @rco-odoo has to do with this.  The code @pedrobaeza referred to has been there all the time.

**Comment by odony** [comment] 2015-04-27 08:37
@oihane Well, the reflog you quoted gives us the commits and dates for every time your pulled the official branch, so you could try to use `git bisect` to find the commit that introduces the problem :

- **2015-04-16 19:25:53 +0200** 2492503 HEAD@{5}: pull: Fast-forward
- **2015-03-13 15:59:54 +0100** 17c1556 HEAD@{6}: pull: Fast-forward
- **2015-03-01 03:34:00 +0100** ddb900c HEAD@{7}: pull: Fast-forward
- **2015-02-23 20:15:57 +0100** 0c964f0 HEAD@{8}: clone: from https://github.com/odoo/odoo.git

Where are the more recent entries for the reflog? It should start with the most recent revision as  `HEAD@{0}`, but yours starts at `HEAD@{5}`? Also, do you know at what date/commit you started to notice the problem?

Thanks!

**Comment by oihane** [comment] 2015-04-27 08:45
I do not remember the date, and it was @anajuaristi who reported the problem.

The revisions missing are that I started to change between the different commits so I deleted that info. Here you have the complete one
```
2492503 HEAD@{0}: checkout: moving from 17c1556208d895bd227ce13761794014b34f6e0b to 8.0
17c1556 HEAD@{1}: checkout: moving from 8.0 to 17c1556
2492503 HEAD@{2}: checkout: moving from 34088c6031e1b18fc3403526d7e4a89d3a355712 to 8.0
34088c6 HEAD@{3}: checkout: moving from 58a481329eb1ec4074a08e12b89fdbd2aaa35343 to 34088c6031e1b18fc3403526d7e4a89d3a355712
58a4813 HEAD@{4}: checkout: moving from 8.0 to 58a481329eb1ec4074a08e12b89fdbd2aaa35343
2492503 HEAD@{5}: pull: Fast-forward
17c1556 HEAD@{6}: pull: Fast-forward
ddb900c HEAD@{7}: pull: Fast-forward
0c964f0 HEAD@{8}: clone: from https://github.com/odoo/odoo.git
```

**Comment by pedrobaeza** [comment] 2015-07-02 23:36
I have tried on current version runbot and the issue seems to be fixed, so you should close it.

**Comment by Yenthe666** [comment] 2017-12-12 18:35
as mentioned by Pedro it could have been closed back then. Closing as Odoo 8 is no longer supported either.

**Closed** 2017-12-12 18:35 UTC
