### ISSUE TITLE
[10.0 ]POS session opened without opening date

### ISSUE THREAD

**Issue by zeroheure** [odoo/odoo#35461] opened 2019-08-05 14:26 UTC
Impacted versions: 
10.0, at least

Steps to reproduce:
Didn't succeed to identify a proper scenario. **Might be** related to Wifi conection lost on POS (Android tablet).

Current behavior:
Missing opening date on POS session. Closing date OK. But session can't be closed. Error message below :
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 642, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 334, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 327, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 942, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 507, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 899, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 887, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/addons/point_of_sale/models/pos_session.py", line 246, in action_pos_session_closing_control
    session.action_pos_session_close()
  File "/usr/lib/python2.7/site-packages/odoo/addons/point_of_sale/models/pos_session.py", line 266, in action_pos_session_close
    self.with_context(ctx)._confirm_orders()
  File "/usr/lib/python2.7/site-packages/odoo/addons/point_of_sale/models/pos_session.py", line 26, in _confirm_orders
    move = self.env['pos.order'].with_context(force_company=company_id)._create_account_move(session.start_at, session.name, int(journal_id), company_id)
  File "/usr/lib/python2.7/site-packages/odoo/addons/point_of_sale/models/pos_order.py", line 152, in _create_account_move
    date_tz_user = fields.Datetime.context_timestamp(self, fields.Datetime.from_string(dt))
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 1589, in context_timestamp
    assert isinstance(timestamp, datetime), 'Datetime instance expected'
AssertionError: Datetime instance expected
```
Expected behavior:
Can't run a session without opening date. At least provide a way to close the session.

Video/Screenshot link (optional):
![POS_without_opening_date_20190805](https://user-images.githubusercontent.com/24126/62471721-8a53b180-b79d-11e9-85cb-44c17b6f8703.png)

**Comment by flotho** [comment] 2019-08-07 13:51
Hi @zeroheure 

it looks like I'm not alone there as you can see there https://github.com/odoo/odoo/issues/20761
@pimodoo had a look in the past to my issue.
maybe he could have a look to yours too

**Comment by zeroheure** [comment] 2019-08-07 14:06
@flotho Yes, I've read your bug report before submitting that one. This morning, I accidentaly opened a session twice, on the same computer (Android). Might be related to an old Chrome version on Android 4.x re-using cache.

**Comment by zeroheure** [comment] 2019-08-09 19:02
Any idea to close the session ?

**Comment by Yenthe666** [comment] 2019-10-03 07:59
Dear @zeroheure,

As Odoo 13 has been released today it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe

**Closed by Yenthe666** 2019-10-03 07:59 UTC
Labels: 10.0, Point of Sale
