### ISSUE TITLE
Odoo 13 HR Holidays Allocations Accural  Report Bug 

### ISSUE THREAD

**Issue by ArunagiriK** [odoo/odoo#64649] opened 2021-01-18 06:17 UTC
I have a found issue in odoo 13  HR Holidays Accrual Allocations

Settings---->Technical-------> Scheduled Actions
Accrual Time Off: Updates the number of time off
When i click the run manual button there is an error showed 

if period_end <= start_date:
ValueError: <class 'TypeError'>: "can't compare datetime.datetime to datetime.date" while evaluating
'model._update_accrual()'
![Update_Accrual](https://user-images.githubusercontent.com/8073866/104878986-f66ea900-5982-11eb-906d-f453df3dad0a.png)

**Comment by pedrobaeza** [comment] 2021-01-18 07:24
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by ArunagiriK** [comment] 2021-01-18 09:26
Hi @pedrobaeza  In runbot scenario is working fine, But i clone the odoo 13 in git hub

**Comment by pedrobaeza** [comment] 2021-01-18 12:34
I'm afraid then that the problem is in your database. Try to load a fresh one with latest code, or upgrade current one, and if not working, try to find custom technical support across forums, lists, etc.

Closing thus.

**Closed by pedrobaeza** 2021-01-18 12:34 UTC
Labels: Need information

**Comment by farazc2h** [comment] 2023-03-19 04:52
See if you have the following module installed, as it overrides the function used to get employee start date, which in odoo core is datetime value, but this module replaces it with a date value field.

https://github.com/OCA/hr/blob/a6150784d9d385b856b982d8d0507528c6aa6d27/hr_employee_service/models/hr_employee.py#L102
