### ISSUE TITLE
[8.0] Unable to upgrade from odoo-8.0rc1

### ISSUE THREAD

**Issue by cubells** [odoo/odoo#2813] opened 2014-10-01 03:58 UTC
When I try to upgrade to the last version of odoo, I get an error on website template.

I think it's due to this commit:
https://github.com/odoo/odoo/commit/5c87e7297d9e55b76971c3d42fe39190fcb569bd

More people has the same problem:
https://www.odoo.com/forum/help-1/question/v8-stable-release-module-update-error-dont-understand-the-error-help-needed-64184

The error log:
2014-10-01 02:36:36,974 580 ERROR Adego openerp.addons.base.ir.ir_ui_view: Element '<xpath expr="//t[@t-call-assets="website.assets_frontend"][@t-js]">' cannot be located in parent view

Error context:
View `Editor`
[view_id: 1029, xml_id: website.editor_head, model: n/a, parent_id: 1027]
2014-10-01 02:36:36,974 580 CRITICAL Adego openerp.service.server: Failed to initialize database `Adego`.
Traceback (most recent call last):
  File "/opt/openerp/server/openerp/service/server.py", line 901, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/opt/openerp/server/openerp/modules/registry.py", line 324, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/openerp/server/openerp/modules/loading.py", line 354, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/opt/openerp/server/openerp/modules/loading.py", line 263, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/openerp/server/openerp/modules/loading.py", line 182, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/openerp/server/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/openerp/server/openerp/tools/convert.py", line 899, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/openerp/server/openerp/tools/convert.py", line 985, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/openerp/server/openerp/tools/convert.py", line 851, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/opt/openerp/server/openerp/tools/convert.py", line 827, in _tag_template
    return self._tag_record(cr, record, data_node)
  File "/opt/openerp/server/openerp/tools/convert.py", line 765, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/opt/openerp/server/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/openerp/server/openerp/addons/base/ir/ir_model.py", line 1024, in _update
   context)
  File "/opt/openerp/server/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/openerp/server/openerp/api.py", line 360, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/openerp/server/openerp/models.py", line 3693, in write
    self._write(old_vals)
  File "/opt/openerp/server/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/openerp/server/openerp/api.py", line 552, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/opt/openerp/server/openerp/models.py", line 3855, in _write
    recs._validate_fields(vals)
  File "/opt/openerp/server/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/openerp/server/openerp/models.py", line 1306, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "ValidateError
Field(s) `arch` failed against a constraint: Invalid view definition

Error details:
Element '<xpath expr="//t[@t-call-assets="website.assets_frontend"][@t-js]">' cannot be located in parent view

Error context:
View `Editor`
[view_id: 1029, xml_id: website.editor_head, model: n/a, parent_id: 1027]" while parsing None:182, near
<data inherit_id="website.layout" name="Editor">
    <xpath expr="//t[@t-call-assets=&quot;website.assets_frontend&quot;][@t-js]" position="after">
        <t t-call-assets="website.assets_editor" t-js="false"/>
    </xpath>
    <xpath expr="//t[@t-call-assets=&quot;website.assets_frontend&quot;][@t-css]" position="after">
        <t t-call-assets="website.assets_editor" t-css="false"/>
    </xpath>
</data>

**Comment by Yenthe666** [comment] 2016-06-03 09:55
Hi @mojowebs,

As stated by @tmotyl this issue should be fixed with an update of the latest version.
I'm closing this issue since I can no longer reproduce this.

Regards,
Yenthe

**Closed** 2016-06-09 14:59 UTC

**Comment by waqasidrees07** [comment] 2024-12-03 09:59
assets_frontend not found in  addons/website/views/website_templates.xml 
odoo 16

i am updating my module from odoo13 to odoo16 and face this error
assets_frontend template not exist in odoo16 so what i need to use here
