### ISSUE TITLE
Error creating vendor v11.0

### ISSUE THREAD

**Issue by marcos-mendez** [odoo/odoo#34159] opened 2019-06-14 20:10 UTC
Impacted versions:V11

Steps to reproduce: Just ading a new Vendor in the system

Current behavior: 

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 673, in call_kw_model
    return downgrade(method, result, recs, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 272, in downgrade
    return convert(value)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3347, in <lambda>
    @api.returns('self', lambda value: value.id)
AttributeError: 'NoneType' object has no attribute 'id'

Expected behavior: Vendor to be created

Video/Screenshot link (optional):

**Comment by marcos-mendez** [comment] 2019-06-14 20:12
This also happens when trying to create a contact

**Comment by pedrobaeza** [comment] 2019-06-15 22:17
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by marcos-mendez** [comment] 2019-06-15 23:01
I kind a restarted the production server and it didnt happend again. I have
a snapshot that is not rebooted im working on it to see what happend
Em 15/06/2019 19:19, "Pedro M. Baeza" <notifications@github.com> escreveu:

**Comment by pedrobaeza** [comment] 2019-06-15 23:17
You was probably running old code, so closing this meanwhile you don't have more hints about a problem with core.

**Closed by pedrobaeza** 2019-06-15 23:17 UTC
Labels: Need information
