### ISSUE TITLE
PDF is not translated

### ISSUE THREAD

**Issue by MohammadSalek** [odoo/odoo#75966] opened 2021-09-04 10:56 UTC
_Impacted versions:_
14 ent

_Steps to reproduce:_
Initialize a database with given language X and install Sales (sale_management) module.
From settings add a second language named Y and make it the default one.
Create a sample quotation in Sales module and save it.
Print the quotation in PDF.

_Current behavior:_
The printed PDF is still in language X.

_Expected behavior:_
The printed PDF was expected to be in language Y. (since it was selected to be the default one)

**Comment by pedrobaeza** [comment] 2021-09-04 11:00
It depends on the partner language and if the corresponding language has the translation done, but this is not a bug. Please check the said things.

Closing due to the above.

**Closed by pedrobaeza** 2021-09-04 11:00 UTC

**Comment by MohammadSalek** [comment] 2021-09-04 11:16
Thanks, @pedrobaeza. I installed Contacts module and changed my contact language and was fixed for me.
