### ISSUE TITLE
Unable to install Intercomp in ODOO9C

### ISSUE THREAD

**Issue by DidierLACOMBE** [odoo/odoo#11033] opened 2016-02-20 08:13 UTC
Impacted versions:
ODOO 9C

Steps to reproduce:

Install intercompany set up

Current behavior:

crash dump in installation
reason : Inter_company_rules is missing, 
module not availlable under ODOO apps under V9C (only 8 and master)

Expected behavior:

Inter_company_rules must be available for ODOO 9C

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment] 2016-06-13 07:04
Hi @DidierLACOMBE,

The module `Inter_company_rules` was available for anybody under V8 but since version 9 it has been moved to the Enterprise part. 
You can see the commit that does this here: https://github.com/odoo/odoo/commit/846e206182eacc936ea8762c6341629312e20bf6
And some more information about the versions here: https://www.odoo.com/nl_NL/editions
If you buy the enterprise version you can use the inter company rules. 

I'm closing this since it is not a bug but wanted behaviour.

Regards,
Yenthe

**Closed by Yenthe666** 2016-06-13 07:04 UTC
