### ISSUE TITLE
Odoo 13 Pages>Edit_Menu>Add_Menu_Item error

### ISSUE THREAD

**Issue by han6man** [odoo/odoo#40092] opened 2019-11-12 06:49 UTC
Impacted versions:
v13

Steps to reproduce:
Pages>Edit_Menu>Add_Menu_Item

Current behavior:
Error:
Uncaught TypeError: Cannot read property 'name' of undefined

http://571158-com-01:8069/web/content/538-f116984/1/website.assets_editor.js:15
Traceback:
TypeError: Cannot read property 'name' of undefined
    at Class.init (http://571158-com-01:8069/web/content/538-f116984/1/website.assets_editor.js:15:895)
    at Class.prototype.<computed> [as init] (http://571158-com-01:8069/web/content/515-243c154/1/web.assets_common_lazy.js:3761:488)
    at new Class (http://571158-com-01:8069/web/content/515-243c154/1/web.assets_common_lazy.js:3762:65)
    at Class._onAddMenuButtonClick (http://571158-com-01:8069/web/content/538-f116984/1/website.assets_editor.js:17:3023)
    at HTMLAnchorElement.<anonymous> (http://571158-com-01:8069/web/content/515-243c154/1/web.assets_common_lazy.js:3845:11)
    at HTMLDivElement.dispatch (http://571158-com-01:8069/web/content/515-243c154/1/web.assets_common_lazy.js:925:447)
    at HTMLDivElement.elemData.handle (http://571158-com-01:8069/web/content/515-243c154/1/web.assets_common_lazy.js:911:166)
![Untitled](https://user-images.githubusercontent.com/2955716/68648525-41905f00-0529-11ea-8bff-4dd7333b3a13.png)

In Debug Mode with assets
Uncaught TypeError: Cannot read property 'name' of undefined
http://571158-com-01:8069/website/static/src/js/menu/content.js:376
Traceback:
TypeError: Cannot read property 'name' of undefined
    at Class.init (http://571158-com-01:8069/website/static/src/js/menu/content.js:376:24)
    at Class.prototype.<computed> [as init] (http://571158-com-01:8069/web/static/src/js/core/class.js:90:38)
    at new Class (http://571158-com-01:8069/web/static/src/js/core/class.js:107:33)
    at Class._onAddMenuButtonClick (http://571158-com-01:8069/website/static/src/js/menu/content.js:601:22)
    at HTMLAnchorElement.<anonymous> (http://571158-com-01:8069/web/static/src/js/core/mixins.js:277:23)
    at HTMLDivElement.dispatch (http://571158-com-01:8069/web/static/lib/jquery/jquery.js:5183:27)
    at HTMLDivElement.elemData.handle (http://571158-com-01:8069/web/static/lib/jquery/jquery.js:4991:28)
Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2019-11-12 08:08
Duplicate of #40002

**Closed by pedrobaeza** 2019-11-12 08:08 UTC
