### ISSUE TITLE
[14.0] Invoicing: Server Error while creating the Invoiving

### ISSUE THREAD

**Issue by dinhngcong** [odoo/odoo#75352] opened 2021-08-20 07:21 UTC
Impacted versions:
- Odoo: 14.0 (pull latest code at 2021/08/20 07:00 UTC)

- python 3.6

- postgres 9.5

Steps to reproduce:
1. Log in as Admin

2. Access menu Accounting --> Customers --> Invoices

3. Click to Create button

Current behavior:
It throws the Server Error.

Expected behavior:
It'll not be thrown any errors.

Video/Screenshot:
![image](https://user-images.githubusercontent.com/80304736/130194502-cbe38db0-0a41-48c7-bfaa-cc3c6e3f8b1b.png)
![image](https://user-images.githubusercontent.com/80304736/130194574-0a7dfa4e-d91e-4401-9dc4-43492cc881cc.png)
![image](https://user-images.githubusercontent.com/80304736/130195203-2406ef43-f3e4-453e-b468-901a5aeb24b2.png)

Error Info:

```
 Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/14/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/14/odoo/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/14/odoo/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/14/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/14/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/14/odoo/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/14/odoo/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/14/odoo/addons/web/controllers/main.py", line 1389, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/14/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/14/odoo/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/14/odoo/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/14/odoo/addons/account/models/account_move.py", line 1093, in onchange
    return super(AccountMove, self.with_context(recursive_onchanges=False)).onchange(values, field_name, field_onchange)
  File "/opt/odoo/14/odoo/odoo/models.py", line 6240, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/opt/odoo/14/odoo/odoo/models.py", line 5982, in _onchange_eval
    method_res = method(self)
  File "/opt/odoo/14/odoo/addons/account/models/account_move.py", line 418, in _onchange_journal
    if self.state == 'draft' and self._get_last_sequence() and self.name and self.name != '/':
  File "/opt/odoo/14/odoo/addons/account/models/sequence_mixin.py", line 179, in _get_last_sequence
    self.env.cr.execute(query, param)
  File "<decorator-gen-3>", line 2, in execute
  File "/opt/odoo/14/odoo/odoo/sql_db.py", line 101, in check
    return f(self, *args, **kwargs)
  File "/opt/odoo/14/odoo/odoo/sql_db.py", line 298, in execute
    res = self._obj.execute(query, params)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/14/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/14/odoo/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
psycopg2.errors.InvalidRegularExpression: invalid regular expression: quantifier operand invalid
```

Query debug

```
UPDATE account_move SET write_date = write_date WHERE id = (
    SELECT id FROM account_move
    WHERE journal_id = 1 AND name != '/' AND sequence_prefix !~ '^(?:.*?)(?:((?<=\D)|(?<=^))((20|21)?\d{2}))(?:\D+?)$'  AND move_type NOT IN ('out_refund', 'in_refund') 
    AND sequence_prefix = (SELECT sequence_prefix FROM account_move WHERE journal_id = 1 AND name != '/' AND sequence_prefix !~ '^(?:.*?)(?:((?<=\D)|(?<=^))((20|21)?\d{2}))(?:\D+?)$'  AND move_type NOT IN ('out_refund', 'in_refund')  ORDER BY id DESC LIMIT 1)
    ORDER BY sequence_number DESC
    LIMIT 1
)
RETURNING name;
```

Please help me to solve this problem. Thanks a lot.

**Comment by pedrobaeza** [comment] 2021-08-20 07:50
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by dinhngcong** [comment] 2021-08-20 08:01
Hi @pedrobaeza, thanks for the response.

Above I have taken a step-by-step picture of the process from start to error.

I'm using Odoo's native source code (pull latest code at 2021/08/20 07:00 UTC), no custom modules here.

**Comment by pedrobaeza** [comment] 2021-08-20 08:01
But do you reproduce it on runbot?

**Comment by dinhngcong** [comment] 2021-08-20 08:03
> But do you reproduce it on runbot?

That's right, I tried it on Runbot but it doesn't give an error.
I'm in doubt about the version of Postgresql.

**Comment by pedrobaeza** [comment] 2021-08-20 22:42
Maybe you have used a previous invalid invoice number. Check that.

Closing this thus, as this is not an Odoo issue per se.

**Closed by pedrobaeza** 2021-08-20 22:42 UTC
Labels: Need information

**Comment by GunalanD95** [comment] 2021-08-28 16:39
iam having this same issue

**Comment by naysonrussier** [comment] 2021-12-07 06:11
> That's right, I tried it on Runbot but it doesn't give an error. I'm in doubt about the version of Postgresql.

I had the same problem with Postgresql 9.5.
Using Postgresql 12 solved the issue for me
