### ISSUE TITLE
[15.0] [16.0] Error when create new payment method.

### ISSUE THREAD

**Issue by Nikul-OSI** [odoo/odoo#121239] opened 2023-05-12 07:33 UTC
Impacted versions: **15.0, 16.0**

Steps to reproduce:

- When create new payment method.

Current behavior:

Check for more details: https://github.com/OCA/bank-payment/issues/896

![image](https://github.com/odoo/odoo/assets/98144048/25ba54a0-36c6-449f-b16c-9edfe1fe05b9)

Expected behavior:

At least created new payment method record.

**Comment by Nikul-OSI** [comment] 2023-05-12 07:38
Solution: If didn't code, pass blank dict, because 

https://github.com/odoo/odoo/blob/a7be194f731370db0d8b0a2075e67676708fbd94/addons/account/models/account_payment_method.py#L26

`information = methods_info.get(method.code, {})
`

In the next line, directly check on dictionary: https://github.com/odoo/odoo/blob/a7be194f731370db0d8b0a2075e67676708fbd94/addons/account/models/account_payment_method.py#L28

`if information and information.get('mode') == 'multi':
`

**Comment by Nikul-OSI** [comment] 2023-05-12 07:43
@pedrobaeza Can you please take a look?

**Comment by niyasraphy** [comment] 2023-05-12 07:51
https://github.com/odoo/odoo/issues/79019

**Comment by pedrobaeza** [comment] 2023-05-12 07:54
Closing as duplicate of #79019

**Closed by pedrobaeza** 2023-05-12 07:54 UTC
