### ISSUE TITLE
Odoo 12 Not compilable with Python 3.8.5

### ISSUE THREAD

**Issue by manishkbohra** [odoo/odoo#59703] opened 2020-10-12 05:09 UTC
Impacted versions: Odoo12

Steps to reproduce: Run odoo with Python 3.8.5

Current behavior: 
KeyError: ('ir.qweb', <function IrQWeb.compile at 0x7f391479fd30>, 178, ('en_US', None, None, None, None, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/addons/base/models/qweb.py", line 330, in compile
    unsafe_eval(compile(astmod, '<template>', 'exec'), ns)
ValueError: Name node can't be used with 'None' constant

Error when compiling AST
ValueError: Name node can't be used with 'None' constant
Template: 178
Path: /templates/t/t/div/main
Node: <main class="o_main_content"/> - - -

Expected behavior:
Odoo works with the newest stable python release

Video/Screenshot link (optional):
![Screenshot from 2020-10-12 10-32-11](https://user-images.githubusercontent.com/72200254/95707446-2ec16580-0c77-11eb-997a-b6512069a259.png)

**Comment by Yenthe666** [comment] 2020-10-12 05:57
Duplicate of https://github.com/odoo/odoo/issues/59456 
Potential backport for V12 on the way at https://github.com/odoo/odoo/issues/59456

**Closed by Yenthe666** 2020-10-12 05:57 UTC

**Comment by imjaypatel** [comment] 2020-11-24 06:37
Hi,

Where is Odoo 11 fix commit? #59456 and  #59630 for 13 and 12. but where is odoo 11 fix for this issue?
