### ISSUE TITLE
Odoo v13 : Traceback appear when open Product by Purchase Administrator

### ISSUE THREAD

**Issue by AmitBista** [odoo/odoo#39885] opened 2019-11-06 14:19 UTC
Impacted versions: v13

Steps to reproduce: 
1. Try to open product with Purchase Administrator
traceback appear as:
-----------------------------------------------------------------
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/data/build/odoo/odoo/addons/base/models/ir_ui_view.py", line 642, in apply_inheritance_specs
    pre_locate=pre_locate)
  File "/data/build/odoo/odoo/tools/template_inheritance.py", line 222, in apply_inheritance_specs
    _("Element '%s' cannot be located in parent view") % tag
ValueError: Element '<xpath expr="//button[@name='action_view_related_putaway_rules']">' cannot be located in parent view

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/data/build/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/data/build/odoo/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/data/build/odoo/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/build/odoo/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/build/odoo/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/build/odoo/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/data/build/odoo/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1319, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1311, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 391, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 364, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/data/build/odoo/odoo/models.py", line 1423, in load_views
    for [v_id, v_type] in views
  File "/data/build/odoo/odoo/models.py", line 1423, in <dictcomp>
    for [v_id, v_type] in views
  File "/data/build/odoo/addons/membership/models/product.py", line 27, in fields_view_get
    return super(Product, self).fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/data/build/odoo/addons/mail/models/mail_thread.py", line 411, in fields_view_get
    res = super(MailThread, self).fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/data/build/odoo/addons/web/models/models.py", line 203, in fields_view_get
    r = super().fields_view_get(view_id, view_type, toolbar, submenu)
  File "/data/build/odoo/odoo/models.py", line 1503, in fields_view_get
    result = self._fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/data/build/odoo/odoo/models.py", line 1465, in _fields_view_get
    root_view = View.browse(view_id).read_combined(['id', 'name', 'field_parent', 'type', 'model', 'arch'])
  File "/data/build/odoo/odoo/addons/base/models/ir_ui_view.py", line 716, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "/data/build/odoo/odoo/addons/base/models/ir_ui_view.py", line 665, in apply_view_inheritance
    source = self.apply_inheritance_specs(source, specs_tree, view_id)
  File "/data/build/enterprise/web_studio/models/ir_ui_view.py", line 154, in apply_inheritance_specs
    pre_locate=pre_locate)
  File "/data/build/odoo/odoo/addons/base/models/ir_ui_view.py", line 644, in apply_inheritance_specs
    self.raise_view_error(str(e), inherit_id)
  File "/data/build/odoo/odoo/addons/base/models/ir_ui_view.py", line 592, in raise_view_error
    raise ValueError(message)
ValueError: Element '<xpath expr="//button[@name='action_view_related_putaway_rules']">' cannot be located in parent view

Error context:
View `product.template.quality`
[view_id: 2332, xml_id: quality_control.product_template_form_view_quality_control, model: product.template, parent_id: 726]
=================
Current behavior: Traceback appear

Expected behavior: Product should be open or raise warning

Video/Screenshot link (optional):
![screenshot-odoo13 bistasolutions com-2019 11 06-19-46-48 (1)](https://user-images.githubusercontent.com/13360865/68305871-6cfcef00-00ce-11ea-8d77-12fee6d00218.png)

**Comment by sswapnesh** [comment] 2019-11-07 17:05
Impacted versions: v13 **Enterprise**  (as it is refering to `quality_control` module)

**Comment by pedrobaeza** [comment] 2019-11-07 17:08
Please report it then through odoo.com/help.

**Comment by Feyensv** [comment] 2019-11-12 10:31
I cannot reproduce this on latest runbots with the demo user.  Could you please verify it is still happening and give me the link of the runbot so that I can investigate precisely what could be the reasons for this error ? :).  It may be due to other access groups or views from other modules than `quality_control`.

**Comment by sswapnesh** [comment] 2019-11-20 18:44
This can be closed in that case. I couldn't reproduce either.

**Comment by pedrobaeza** [comment] 2019-11-20 18:45
Closing then. Thanks for the followup.

**Closed by pedrobaeza** 2019-11-20 18:45 UTC
Labels: 13.0, Logistics

**Comment by AmitBista** [comment] 2019-11-21 06:09
Hello Folks,

Still faced the same issue on latest build runbot. please check attached screen for info.
Traceback should not be accept. instead of that we can give warning to user OR give access rights  of "Inventory/User on product.template".

![screenshot-13 57 66 77-8069-2019 11 21-11-02-45](https://user-images.githubusercontent.com/13360865/69311847-5ff60900-0c53-11ea-896a-ad5281ca8436.png)

**Comment by pedrobaeza** [comment] 2019-11-21 08:14
And the steps to reproduce the problem?
