### ISSUE TITLE
[11.0] Click on tree view and open full sheet

### ISSUE THREAD

**Issue by aitorbouzas** [odoo/odoo#25455] opened 2018-06-25 11:55 UTC
Impacted versions:
11.0

Steps to reproduce:
1. Go to a tree view that hasn't got `editable="top"` or `editable="bottom"`
2. Click on a record

Current behavior:
Opens a popup with the form view of the record.

Expected (wanted) behavior:
I would like to know if there's an option with which you can tell the tree to open the form in the full page (with full sheet). I know you can do it by putting a button, but that's just a workaround.

**Comment by sswapnesh** [comment] 2018-06-25 15:32
If I am not wrong, You are talking about Internal Tree view(o2m/m2m). At the moment there is not Such option available.
Cc: @pedrobaeza

**Comment by pedrobaeza** [comment] 2018-06-25 15:39
Exactly, this is not a bug, but something that it's not covered, and even more, something that it's not wanted to be implemented, as this will make that one2many records (usually without name_get and without proper fields outside the one2many widget - the parent many2one for example -) appears weird and non valid.

Closing by the stated above.

**Closed by pedrobaeza** 2018-06-25 15:39 UTC
