### ISSUE TITLE
[8.0] point_of_sale: Dependencies problem

### ISSUE THREAD

**Issue by AngelCamacho** [odoo/odoo#10238] opened 2015-12-30 09:30 UTC
I have a problem when i install a point of sale module in a Demo. 

The install report a error when parse point_of_sale_demo.xml:

  File "/opt/openerp/instancia1/addons/account/account.py", line 815, in create_sequence
    prefix = vals['code'].upper()
ParseError: "code" while parsing /opt/openerp/instancia1/addons/point_of_sale/point_of_sale_demo.xml:30, near
<record id="account.cash_journal" model="account.journal">
            <field eval="True" name="journal_user"/>
        </record>

The error it's because some post upgrades of account module create a cash journal. 

I think the solution it's adds in point_of_sale the dependence with "account" module.

**Comment by jorenvo** [comment] 2016-01-04 08:38
The point_of_sale module already depends on account through it's dependency on sale_stock (which depends on stock_account which depends on account). When installing the point_of_sale module the system checks whether or not the dependencies are satisfied. In your case they are (they're installed) but one of them is compromised.

The issue is that you have removed something from the account module that the point of sale depended on (the cash journal you mentioned). This can be resolved by either re-initing the account module, or installing the point of sale module without demo data.

The last option is only available through the command line I think.

```
./odoo.py --without-demo=point_of_sale -i point_of_sale
```

The first option would be reiniting the account module, which you can do through the web interface by clicking on the upgrade button on the eInvoicing module. It's probably best to try this in a test database first to see it doesn't cause any unwanted side-effects.

**Closed by jorenvo** 2016-01-04 08:38 UTC

**Comment by AngelCamacho** [comment] 2016-01-04 10:31
Ok, thanks.
