### ISSUE TITLE
Problem to attach files in crm.lead with google_drive installed

### ISSUE THREAD

**Issue by ghost** [odoo/odoo#10047] opened 2015-12-11 21:23 UTC
When I want to attach a file in a new crm.lead without other attachments, I can select the file but the system doesn't save the file.

I debug this problem, and I could find.
The module google_drive extend the class instance.web.Sidebar and rewrite the function start() to load more options in the button 'more', but when the function was load after the attachments, rewrites the node and lost the change function of the node to add files.

To change this is necessary add the change function in the redraw, to don't lost the function change when the attachments are loaded before google-drive.

Steps to reproduce:
On a database, install and configure the modules google_drive and document.
Create a new crm.lead and save that.
Try to attach a document in a crm.lead without files.

![seleccion_003](https://cloud.githubusercontent.com/assets/7594736/11755872/0628bec0-a01b-11e5-98b7-eaf39e4b41cc.png)

**Comment by andreparames** [comment] 2016-06-22 14:01
We have the same issues, and actually implemented the same fix before finding this bug report.

@rr-clearcorp can you submit your fix as a proper PR? If not, I'll do so to see if we can get the attention of Odoo devs.

**Comment by rr-clearcorp** [comment] 2016-06-22 22:29
Sure @andreparames, I can submit the PR this weekend

**Comment by andreparames** [comment] 2016-06-22 23:34
Thanks!

**Comment by pedrobaeza** [comment] 2018-04-10 22:32
Is this still happening in latest code version?

**Comment by Yenthe666** [comment] 2018-04-11 09:11
@pedrobaeza sadly the user @ghost has deleted his account, so he won't respond anymore.
I'll close this off. @andreparames can you confirm if it still happens on the latest code or not?

**Closed by Yenthe666** 2018-04-11 09:11 UTC
Labels: Services

**Comment by andreparames** [comment] 2018-04-11 09:31
@Yenthe666 I can't reproduce it anymore, and the code was significantly changed, so I agree with the closing.

**Comment by Yenthe666** [comment] 2018-04-11 09:35
Perfect, thanks a lot!
