### ISSUE TITLE
[11.0] Bug in Inventory validation report

### ISSUE THREAD

**Issue by deivislaya** [odoo/odoo#26161] opened 2018-08-03 16:23 UTC
**Impacted versions:**
11.0 ee
**Steps to reproduce:**

1. Set up a stockable type product, where its category has a FIFO cost method and its inventory valuation is automated

![card graphics card odoo 1](https://user-images.githubusercontent.com/5775695/43652189-7c9460d2-9712-11e8-9d32-79a6ab0b988b.png)
![all saleable physical odoo](https://user-images.githubusercontent.com/5775695/43652201-83db263c-9712-11e8-8209-3facc59edfd7.png)

2. go to inventory -> valuation report -> Select a specific date

![product valuation odoo 2](https://user-images.githubusercontent.com/5775695/43652833-57a92cec-9714-11e8-81f2-01c4be9cb5a6.png)

**Current behavior:**

It does not show the inventory value correctly, compared to the current date option if it shows it

**Expected behavior:**

Show the correct report for both options

**Video/Screenshot link (optional):**

https://youtu.be/L4gEbaT32BU

**Comment by pedrobaeza** [comment] 2018-08-04 18:05
Did you activate the automatic valuation at the beginning and configure properly the stock accounts? Can you please try to reproduce full process in runbot (https://runbot.odoo.com)?

**Comment by deivislaya** [comment] 2018-08-07 14:15
No, I didn't it the automatic valuation at the beginning. However, I would like to know why both options in the inventory valuation report show different results when it should be the same. Attach video of the process in runbot odoo https://youtu.be/dEV5Zvj_99s

**Comment by nhomar** [comment] 2018-08-15 08:15
@deivislaya With the change you did on the category, you must fix manually the accounting layer, that report you are showing depends of it.

Did you do a proper OPW ticket?. Can you share that number and answer from odoo here?.

That report is pretty new, but with the proper manual fixing of accounting you can fix it. 
@everybody once We set the procedure we can share it here.

**PS:** it looks like a time/date probelm also.

Closing to left this to the proper OPW (@deivislaya put the ticket number here for the record).

**Closed by nhomar** 2018-08-15 08:15 UTC
Labels: 11.0, Logistics

**Comment by deivislaya** [comment] 2018-08-15 14:09
@nhomar  The ticket number for OPW is 1871847

Regards!

**Comment by gustavovalverde** [comment] 2020-03-17 00:35
I can confirm that this is an actual issue cc: @sle-odoo when using FIFO and using the report with an specific date, the information is wrong for some products (quantity and valuation)

**Comment by gustavovalverde** [comment] 2020-03-17 01:31
@sle-odoo this 2 values get completely distorted https://github.com/odoo/odoo/blob/12.0/addons/stock_account/models/product.py#L271-L272

**Comment by gustavovalverde** [comment] 2020-03-17 01:51
@sle-odoo `product.stock_value` should be the sum of the amls shown in the information tree of each product. Any other computation might be mistaken. As it happens right now, where the stock_value is not equal to the sum of amls balance, which is utterly confusing

**Comment by gustavovalverde** [comment] 2020-03-17 03:42
PR to fix this: https://github.com/odoo/odoo/pull/47737/files
