### ISSUE TITLE
Error when « Synchronize terms »

### ISSUE THREAD

**Issue by lapagept** [odoo/odoo#4353] opened 2014-12-19 13:34 UTC
Hello there, 
It's impossible for me to use Settings->Translations->Application Terms->Synchronize Terms

I get this error for any language I try:
```
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/openerp/http.py", line 518, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/openerp/http.py", line 539, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/openerp/http.py", line 295, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/openerp/http.py", line 292, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/odoo/openerp/http.py", line 755, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/openerp/http.py", line 388, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/openerp/addons/base/module/wizard/base_update_translations.py", line 47, in act_update
    tools.trans_export(this.lang, ['all'], buf, 'csv', cr)
  File "/home/odoo/openerp/tools/translate.py", line 513, in trans_export
    modules = set(t[0] for t in translations)
  File "/home/odoo/openerp/tools/translate.py", line 466, in _process
    writer.writerow(("module","type","name","res_id","src","trad"))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)
```
Thanks

**Comment by sle-odoo** [comment] 2016-06-13 11:24
Closing as i cannot reproduce this issue. Feel free to comment if you're still facing it with an updated codebase and we'll have a deeper look.

Regards

**Closed by sle-odoo** 2016-06-13 11:24 UTC
