### ISSUE TITLE
locks or hangs with 100% cpu, when rendering a pdf with wkhtml2pdf (threaded or workers mode)

### ISSUE THREAD

**Issue by jbaudoux** [odoo/odoo#2114] opened 2014-09-01 16:18 UTC
With multicorn (workers>0), Odoo can be dead-locked.

The workers are unthreaded processes that can handle only one request at a time. The request is read with readline waiting for an end of line. If that EOL is not send, the worker gets blocked and do not processes any further request.
This does not happen in threaded mode (workers=0).

For instance, wkhtmltopdf, which is used for the reporting engine, opens 3 connections when you print a RFQ but write the request on the third one. It locks three workers until the third worker finishes processing the request then it releases the 3 workers. If you don't have enough workers, odoo gets dead-locked or if you run multiple reports at the same time, you could end-up locking all your workers.

The multicorn implementation is not safe and should be improved.

Here is a trace showing the call to readline():
  /server/openerp/cli/server.py(168)main()
-> rc = openerp.service.server.start(preload=preload, stop=stop)
  /server/openerp/service/server.py(933)start()
-> rc = server.run(preload, stop)
  /server/openerp/service/server.py(627)run()
-> self.process_spawn()
  /server/openerp/service/server.py(540)process_spawn()
-> self.worker_spawn(WorkerHTTP, self.workers_http)
  /server/openerp/service/server.py(465)worker_spawn()
-> worker.run()
  /server/openerp/service/server.py(730)run()
-> self.process_work()
  /server/openerp/service/server.py(760)process_work()
-> self.process_request(client, addr)
  /server/openerp/service/server.py(751)process_request()
-> self.server.process_request(client, addr)
  /usr/lib/python2.7/SocketServer.py(310)process_request()
-> self.finish_request(request, client_address)
  /usr/lib/python2.7/SocketServer.py(323)finish_request()
-> self.RequestHandlerClass(request, client_address, self)
  /usr/lib/python2.7/SocketServer.py(638)**init**()
-> self.handle()
  /eggs/Werkzeug-0.9.6-py2.7.egg/werkzeug/serving.py(200)handle()
-> rv = BaseHTTPRequestHandler.handle(self)
  /usr/lib/python2.7/BaseHTTPServer.py(340)handle()
-> self.handle_one_request()

> /eggs/Werkzeug-0.9.6-py2.7.egg/werkzeug/serving.py(232)handle_one_request()
> -> self.raw_requestline = self.rfile.readline()

kr
J-E

**Comment by spadae22** [comment] 2015-05-15 16:57
issue still exists, any resolve on this?

**Comment by antonylesuisse** [comment] 2015-05-17 00:45
Please provide a precise scenario to reliably reproduce the bug and we will fix it.

**Comment by sle-odoo** [comment] 2015-05-17 22:31
As i'm facing this issue on another branch, i can now formulate it. but @jbaudoux has already told pretty much everything.
report.py renders the `minimal template` layout with the header, body or footer of the report.
The assets are defined in this template.
So in my branch we have:
```
[...]
<link href="/report/static/src/css/reset.min.css" rel="stylesheet"/>
<t t-call-assets="report.assets"/>
<style type='text/css'><t t-raw="css"/></style>
<t t-if="subst is True">
    <script src='/report/static/src/js/subst.js'></script>
</t>
[...]
```

And the generated html is:
```
    <base href=http://127.0.0.1:8069>
    <!DOCTYPE html>
    <html style="height: 0;">
        <head>
            <link href="/report/static/src/css/reset.min.css" rel="stylesheet"/>
            
            <link href="/web/css/report.assets/d4cf028" rel="stylesheet"/>
            <script  type="text/javascript" src="/web/js/report.assets/d4cf028"></script>
[...]
```

meaning wkhtmltopdf has to download three different files from Odoo. As we know, when printing a report, the http worker executing the wkhtmltodpf is waiting for the return code an cannot respond to other requests.

So let's say we start Odoo with 2 workers, one for waiting wkhtmltopdf and the other to answers the assets http requests:
``./odoo.py -d master-test-sle --db-filter master-test-sle --max-cron-threads=0 --limit-time-real=1200 --workers=2``
notes:
    * i increased the worker timeout to avoid noises in the future logs
    * only sale is installed on this db

Browsing the webclient doesn't show any issues, but when i go to
http://127.0.0.1:8069/report/pdf/sale.report_saleorder/8
the report printing is stuck.
```
2015-05-17 21:22:06,476 14470 INFO master-test-sle openerp.service.server: Worker WorkerHTTP (14470) alive
2015-05-17 21:22:06,479 14471 INFO master-test-sle openerp.service.server: Worker WorkerHTTP (14471) alive
2015-05-17 21:22:07,306 14472 INFO ? openerp: OpenERP version 9.0alpha1
2015-05-17 21:22:07,306 14472 INFO ? openerp: addons paths: ['/home/sle/.local/share/Odoo/addons/9.0', u'/home/sle/odoo/openerp/addons', u'/home/sle/odoo/addons']
2015-05-17 21:22:07,307 14472 INFO ? openerp: database: default@default:default
2015-05-17 21:22:07,402 14472 INFO ? openerp.service.server: Evented Service (longpolling) running on 0.0.0.0:8072
2015-05-17 21:26:29,988 14470 INFO master-test-sle openerp.addons.base.ir.ir_http: Generating routing map
2015-05-17 21:26:30,127 14470 INFO master-test-sle openerp.addons.base.ir.ir_qweb: 'doc.partner_id.lang' is not a valid language code, is an empty field or is not installed, falling back to en_US
```

23:18 $ date
Sun May 17 23:27:52 CEST 2015

Sending kill -3 to 14471 tells us that
```
2015-05-17 21:29:16,695 14471 INFO master-test-sle openerp.tools.misc: 
# Thread: MainThread (id:140192090466048) (uid:n/a)
File: "./odoo.py", line 160, in <module>
  main()
File: "./odoo.py", line 157, in main
  openerp.cli.main()
File: "/home/sle/odoo/openerp/cli/command.py", line 64, in main
  o.run(args)
File: "/home/sle/odoo/openerp/cli/server.py", line 185, in run
  main(args)
File: "/home/sle/odoo/openerp/cli/server.py", line 179, in main
  rc = openerp.service.server.start(preload=preload, stop=stop)
File: "/home/sle/odoo/openerp/service/server.py", line 909, in start
  rc = server.run(preload, stop)
File: "/home/sle/odoo/openerp/service/server.py", line 596, in run
  self.process_spawn()
File: "/home/sle/odoo/openerp/service/server.py", line 508, in process_spawn
  self.worker_spawn(WorkerHTTP, self.workers_http)
File: "/home/sle/odoo/openerp/service/server.py", line 427, in worker_spawn
  worker.run()
File: "/home/sle/odoo/openerp/service/server.py", line 697, in run
  self.process_work()
File: "/home/sle/odoo/openerp/service/server.py", line 729, in process_work
  self.process_request(client, addr)
File: "/home/sle/odoo/openerp/service/server.py", line 720, in process_request
  self.server.process_request(client, addr)
File: "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
  self.finish_request(request, client_address)
File: "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
  self.RequestHandlerClass(request, client_address, self)
File: "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
  self.handle()
File: "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 200, in handle
  rv = BaseHTTPRequestHandler.handle(self)
File: "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
  self.handle_one_request()
File: "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 231, in handle_one_request
  self.raw_requestline = self.rfile.readline()
File: "/usr/lib/python2.7/socket.py", line 447, in readline
  data = self._sock.recv(self._rbufsize)
File: "/home/sle/odoo/openerp/tools/misc.py", line 1103, in dumpstacks
  for line in extract_stack(stack):
```

So it looks like the other http worker is trying to respond to a http request that doesn't send anything.
To be sure, i'm doing the same manipulation but with tcpdump started:
```
2015-05-17 21:41:25,337 17109 INFO master-test-sle openerp.service.server: Worker WorkerHTTP (17109) alive
2015-05-17 21:41:25,339 17110 INFO master-test-sle openerp.service.server: Worker WorkerHTTP (17110) alive
```
``tcpdump -n -A -s 0 'tcp port 8068' -i lo``

and again i go to http://127.0.0.1:8069/report/pdf/sale.report_saleorder/8

It's stuck again
```
2015-05-17 21:39:04,162 16485 INFO ? openerp.http: HTTP Configuring static files
2015-05-17 21:39:04,168 16485 INFO master-test-sle openerp.addons.base.ir.ir_http: Generating routing map
2015-05-17 21:39:04,300 16485 INFO master-test-sle openerp.addons.base.ir.ir_qweb: 'doc.partner_id.lang' is not a valid language code, is an empty field or is not installed, falling back to en_US
```

tcpdum log: http://pastebin.com/s0Bjx3DR
Tcpdump informs us that :
- wkhtmltopdf begins by opening four tcp connections (60099 to 60102) to odoo
- then asks /report/static/src/css/reset.min.css with 60101 and, just after receiving the ACK from odoo, asks /web/css/report.assets/fef60a7 with 60102 and, just after receiving the ACK from odoo, asks /web/js/report.assets/fef60a7 with 60100

So we have three parralels requests and one tcp connection opened but unused, and odoo is dead locked.
(entries at the start end end of the logs are from my google chrome instance i suppose)

However, i can't provide a scenario to reproduce the issue. Sometimes it happens, sometimes not... still working on it. Feel free to correct me if i made some bad conclusions when analysing the log.

**Comment by zazabe** [comment] 2015-05-22 11:07
## Our experience

We found that if the local loop (`localhost`) is used as the `<base>` url in report templates, the source port of `webkit2pdf` requests is sometime wrong on odoo side, and the worker will be stuck.

I have no idea why and it seems to be a socket issue, but `ngrep` was reporting a different source port coming from `webkit2pdf` than the [source port on which odoo was trying to communicate][accept].

We solved this issue by using the public ip of our instance, going through our reverse proxy... But there's some limitations, HTTP Auth is more difficult to setup and HTTP requests done by `webkit2pdf` will have to go through all the networking plumping.

## Details

I did some tests with 2 workers + extra log to get the source ip:port when the socket is accepted by a worker:
- [odoo log with source ip:port + werkzeug logs][odoo]
- [ngrep on requests to odoo][ngrep]

The report was stuck with this request:
```
2015-05-22 10:30:33,557 27841 INFO ? openerp.service.server: Worker (27841) receive request from ('127.0.0.1', 49984)
```
There's something strange, I can't found any client request with the port `49984` on my `ngrep` logs, so where this port is coming from ?

I think there's something wrong in the way socket connection are accepted, the source port seems wrong and then, when we read on this socket (`self.rfile.readline()`), the [worker is stuck at this line][lock].


  [accept]: https://github.com/odoo/odoo/blob/8.0/openerp/service/server.py#L777
  [odoo]: http://pastebin.com/jAEGHJzV
  [ngrep]: http://pastebin.com/775iuAM5
  [lock]: https://github.com/mitsuhiko/werkzeug/blob/master/werkzeug/serving.py#L235

**Comment by wtaferner** [comment] 2015-06-16 10:32
@antonylesuisse @sle-odoo 
Any news on this one? How do you solve this issue in your SaaS? Does it never happen?

Having this issue with a customer using the Odoo website and shop.
I might try to use the public approach mentioned (hope it works) or find an automated way to identify worker deadlocks and provide resurrection through the sledge hammer method ;-)

**Comment by sle-odoo** [comment] 2015-06-16 19:58
@wtaferner nothing new as there's still no reliable way to reproduce this issue and work on it. are you able to reproduce your client's bug in your environment?

About our saas, there's a big amount of workers so deadlocks do not happen regularly + there's a timeout on the workers themselves, so when the deadlocks occurs one stuck worker is killed, a new one is created and can unlock another one and so on.

**Comment by wtaferner** [comment] 2015-06-17 05:45
@sle-odoo 
Hmm, so far the method serving through nginx locally works...well, I did not invest too deeply as you guys tried already and my only mission is/was to circumvent such a scenario, but what I can acknowledge is that it happens when the PDF report is requested directly through werkzeug. So nothing new I guess.

Can you explain the two useless HTTP 400 requests per retrieval? Essentially, it is a post-loading of resources from the QWeb/HTML parsing, but these two requests look suspicious and without knowing any details I would research and explicitly try to explain why these are happening and eliminate these.

**About reproduction**
I have no clear pointer but maybe it happens when a worker has consumed almost its hard/soft memory limit and is forced to handle more than it can take without being able to be killed and respawn...this is really just guessing...I was just thinking that this could be an issue as I had troubles before having too little ```limit_memory_hard``` defined and got always stuck trying to do intensive PDF reports (via the same methodology).

**Comment by christophlsa** [comment] 2016-09-20 10:20
We have similar issues with blocking request when creating reports via wkhtmltopdf. But our problem is that this occurs only in unit tests and only in our docker host (debian, Python 2.7.9). Locally (ubuntu, Python 2.7.6) there is no problem. We are using odoo 8.

I run `kill -3` on the odoo process and got this output: http://pastebin.com/xH3XwPxP

Maybe it's a problem with the odoo connector because it also tries to access the environment.

A workaround for me is now that I added a nginx in this docker and added timeouts of 10s for css files and some other custom routes which will be called in this reports. Because we test only that the report is generated and not if it looks good there is no big issue.

After the tests we start odoo with workers. There is no problem with lock issues. But I cannot run the unit tests with workers (there are some problems). But would be nice if we can fix such blocking issues.

**Comment by esperandus** [comment] 2016-11-04 12:21
Not sure how relevant it is, but I experienced the same issue after switching to the multi-worker mode for the first time. 

However, my first step - before I had read this - was to upgrade to the latest wkhtmltopdf. Perhaps surprisingly , this worked (also applied the patch [ADD] server: optional timeout on blocking socket operations #12356 with a timeout of 5s option, in case).

**Comment by tr37ion** [comment] 2017-05-20 15:22
Enabling `workers !=0` results in 100% CPU on all cores. Odoo 10 on ArchLinux host not multithreadable.

**Comment by odony** [comment] 2017-06-27 17:40
Fixed by 8245c1d1d87b443701b161d8d4a42df2b4d13aec about a year ago, in all versions as of 8.0.

**Closed by odony** 2017-06-27 17:40 UTC

**Comment by tr37ion** [comment] 2017-06-30 12:05
Well, I'm running `Odoo Server 10.0-20170512` and enabling `workers` results in 100% CPU usage on all cores.

**Comment by odony** [comment] 2017-06-30 13:42
@tr37ion that is most likely not related to this issue. The bug here occurs only on a server configured with a low number of workers, when you print a PDF report and the last 2 available workers become blocked by dead wkhtmltopdf requests, so everything is frozen until the report printing timeout occurs. When that happens, no process should be at 100% CPU, they should all be doing nothing.

(The title of this bug is confusing, and the comment by @nafex mentioning 100% CPU was certainly linked to a different problem)

**Comment by moderatemisbehaviour** [comment] 2018-06-12 16:03
For what its worth I experienced a similar problem on an Odoo server running in the default single-threaded mode due simply to the `web.base.url` parameter being set to the public IP (using NGINX as a reverse proxy) rather than default of `localhost:8069`. Correcting this value stopped `wkhtmltopdf` hanging because it could now resolve the paths in the HTML files Odoo generates in `/tmp` before it calls the `wkhtmltopdf` binary.

The problem is intermittent across builds and I've not yet found out why the default value is sometimes overridden but I suspect it is due to some randomness in the module load order.
