### ISSUE TITLE
Problem with uploading of delivery receipt for boxes

### ISSUE THREAD

**Issue by gatbeaumont** [odoo/odoo#19059] opened 2017-08-25 08:38 UTC
Hi all, 
I am creating a delivery with different boxes and I would like to have one delivery receipt for each box. 
Anyway, everything is going well until I tried to upload the delivery receipt, I got this error message: 

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/addons/report/controllers/main.py", line 96, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/report/controllers/main.py", line 45, in report_routes
    pdf = report_obj.with_context(context).get_pdf(docids, reportname, data=data)
  File "/mnt/extra-addons/professional_templates/models/report.py", line 46, in get_pdf
    result = super(Report, self).get_pdf(docids, report_name, html=html, data=data)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/report/models/report.py", line 178, in get_pdf
    html = self.with_context(context).get_html(docids, report_name, data=data)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/report/models/report.py", line 144, in get_html
    return self.render(report.report_name, docargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/report/models/report.py", line 120, in render
    return view_obj.render_template(template, values)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 1029, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/website/models/ir_ui_view.py", line 110, in render
    return super(View, self).render(values, engine=engine)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web_editor/models/ir_ui_view.py", line 26, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 1049, in render
    return self.env[engine].render(self.id, qcontext)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 53, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 248, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 317, in _compiled_fn
    raise e
QWebException: tuple index out of range
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 315, in _compiled_fn
    return compiled(self, append, values, options, log)
  File "<template>", line 1, in template_professional_templates_delivery_lines_30285
  File "<template>", line 52, in foreach_30284
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 5190, in __getitem__
    return self._browse((self._ids[key],), self.env)
IndexError: tuple index out of range

Error to render compiling AST
IndexError: tuple index out of range
Template: professional_templates.delivery_lines
Path: /templates/t/table[2]/tbody/t/tr/td[4]/span
Node: <span t-field="pack_operation.picking_id.move_lines[pack_operation_index].state"/>

Let me know please. Maybe it comes from the translation I've made from english to french, I don't know?

**Comment by pedrobaeza** [comment] 2018-06-06 10:49
Sorry, but the error you are mentioning corresponds to a custom code you are changing, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2018-06-06 10:49 UTC
Labels: 10.0, Logistics
