### ISSUE TITLE
Error activating job offers on website

### ISSUE THREAD

**Issue by mglacr** [odoo/odoo#24208] opened 2018-04-12 19:46 UTC
Impacted versions:11

Steps to reproduce:Activate odoo online employe recruitment

Current behavior:
I get this error:
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/models.py", line 1023, in _validate_fields
    check(self)
  File "/opt/odoo/odoo/odoo/addons/base/ir/ir_ui_view.py", line 342, in _check_xml
    if not valid_view(view_arch):
  File "/opt/odoo/odoo/odoo/tools/view_validation.py", line 18, in valid_view
    if not pred(arch):
  File "/opt/odoo/odoo/odoo/tools/view_validation.py", line 50, in schema_valid
    validator = relaxng(arch.tag)
  File "/opt/odoo/odoo/odoo/tools/view_validation.py", line 37, in relaxng
    with tools.file_open(os.path.join('base', 'rng', '%s_view.rng' % view_type)) as frng:
  File "/opt/odoo/odoo/odoo/tools/misc.py", line 193, in file_open
    pathinfo=pathinfo, basename=basename)
  File "/opt/odoo/odoo/odoo/tools/misc.py", line 211, in _fileopen
    raise ValueError("Unknown path: %s" % name)
ValueError: Unknown path: /base/rng/tree_view.rng

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/odoo/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/odoo/odoo/odoo/addons/base/ir/ir_model.py", line 1469, in _update
    record = record.create(values)
  File "/opt/odoo/odoo/odoo/addons/base/ir/ir_ui_view.py", line 398, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/opt/odoo/odoo/odoo/models.py", line 3356, in create
    self._fields[key].determine_inverse(record)
  File "/opt/odoo/odoo/odoo/fields.py", line 1070, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odoo/odoo/odoo/addons/base/ir/ir_ui_view.py", line 266, in _inverse_arch
    view.write(data)
  File "/opt/odoo/odoo/odoo/addons/base/ir/ir_ui_view.py", line 414, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo/odoo/odoo/models.py", line 3065, in write
    self._write(old_vals)
  File "/opt/odoo/odoo/odoo/models.py", line 3231, in _write
    self._validate_fields(vals)
  File "/opt/odoo/odoo/odoo/models.py", line 1027, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error mientras se validaban las restricciones\n\nUnknown path: /base/rng/tree_view.rng', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 934, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/addons/base/res/res_config.py", line 561, in execute
    self._install_modules(to_install)
  File "/opt/odoo/odoo/odoo/addons/base/res/res_config.py", line 35, in _install_modules
    result = to_install_modules.button_immediate_install()
  File "<decorator-gen-43>", line 2, in button_immediate_install
  File "/opt/odoo/odoo/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo/odoo/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/odoo/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/odoo/odoo/tools/convert.py", line 788, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/odoo/odoo/tools/convert.py", line 849, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/odoo/odoo/tools/convert.py", line 748, in parse
    exc_info[2]
  File "/opt/odoo/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/odoo/odoo/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/odoo/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/odoo/odoo/odoo/addons/base/ir/ir_model.py", line 1469, in _update
    record = record.create(values)
  File "/opt/odoo/odoo/odoo/addons/base/ir/ir_ui_view.py", line 398, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/opt/odoo/odoo/odoo/models.py", line 3356, in create
    self._fields[key].determine_inverse(record)
  File "/opt/odoo/odoo/odoo/fields.py", line 1070, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odoo/odoo/odoo/addons/base/ir/ir_ui_view.py", line 266, in _inverse_arch
    view.write(data)
  File "/opt/odoo/odoo/odoo/addons/base/ir/ir_ui_view.py", line 414, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo/odoo/odoo/models.py", line 3065, in write
    self._write(old_vals)
  File "/opt/odoo/odoo/odoo/models.py", line 3231, in _write
    self._validate_fields(vals)
  File "/opt/odoo/odoo/odoo/models.py", line 1027, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error mientras se validaban las restricciones

Unknown path: /base/rng/tree_view.rng
None" while parsing /opt/odoo/odoo/addons/website_hr_recruitment/views/hr_recruitment_views.xml:3, near
<record id="view_hr_recruitment_tree_url" model="ir.ui.view">
        <field name="name">hr.recruitment.tree.inherit.url</field>
        <field name="model">hr.recruitment.source</field>
        <field name="inherit_id" ref="hr_recruitment.hr_recruitment_source_tree"/>
        <field name="arch" type="xml">
            <xpath expr="//button[@name='create_alias']" position="before">
                <field name="url" widget="url"/>
            </xpath>
        </field>
    </record>
Expected behavior:

Be able to post job offers on the website

Video/Screenshot link (optional):
![odoo fail](https://user-images.githubusercontent.com/38330061/38700208-8b705b10-3e57-11e8-8338-27ac0b258cd7.png)

**Comment by pedrobaeza** [comment] 2018-04-12 19:49
Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by mglacr** [comment] 2018-04-12 20:31
I don't be able to do this on runbot...

I have a fresh odoo installation, cloned from git of odoo 11, i have only this modules installed:
![image](https://user-images.githubusercontent.com/38330061/38702345-aa666c34-3e5d-11e8-90e7-4a3136f0a9d9.png)

I dont have any data in this database is a fresh installation
I just go to the Recruitment menu->Settings->Activate the option **Online job offers**-> And i save the changes 
And i get this error:
![image](https://user-images.githubusercontent.com/38330061/38702532-16952c24-3e5e-11e8-887a-d0f34f413646.png)


I did a git pull on my odoo server and this don't solve the problem...

**Comment by nhomar** [comment] 2018-04-13 06:45
Can you run a -i module_name and put here the log please?

**Comment by jpaulin** [comment] 2018-04-13 10:37
@nhomar Btw. Is the line saying a validation file not found, important ? To me seems like that is the very immediate bug, but don't know more of the background of it.

Unknown path: ... (referring to a .rng file) 

The .rng is a Relax NG validation file.

**Comment by nhomar** [comment] 2018-04-13 11:02
@jpaulin The only way it can fail is that you modify either the base code and/or you have a development that changes something in odoo.

As you can see all modules are being installed on [runbot](https://runbot.odoo.com) and I tried myself locally.

It is telling that a path (path in xml not path on files) can't be found, and that only happen if you customize incorrectly a view.

If you do not find a way to reproduce this error in a standard deployment I can't help you.

I will close this issue if you find a way to reproduce it properly you can reopen it.

**Closed by nhomar** 2018-04-13 11:02 UTC
Labels: 11.0, Need information
