### ISSUE TITLE
Reconcile bank statement : Full Reconcile (account.full.reconcile), Field: Number (name) 

### ISSUE THREAD

**Issue by m3asmi** [odoo/odoo#48431] opened 2020-03-26 12:27 UTC
Impacted versions:12.0

Current behavior:

>  The operation cannot be completed:
> - Create/update: a mandatory field is not set.
> - Delete: another model requires the record being deleted. If possible, archive it instead.
> 
> Model: Full Reconcile (account.full.reconcile), Field: Number (name) 
>

**Comment by pedrobaeza** [comment] 2020-03-26 12:31
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Yenthe666** [comment] 2020-03-26 14:17
Plus nicely reproducable steps would be nice too ;)

**Comment by m3asmi** [comment] 2020-03-26 16:06
@pedrobaeza @Yenthe666 couldn't reproduce it in runbot !
I think the problem is with default value of name
when does it compute in this line ? 
[https://github.com/odoo/odoo/blob/12.0/addons/account/models/account_move.py#L876](https://github.com/odoo/odoo/blob/12.0/addons/account/models/account_move.py#L876)

**Comment by pedrobaeza** [comment] 2020-03-26 16:07
This sounds as something incorrect on your side then:

- Outdated code
- External modules interfering.
- etc

But not being to reproduce it, nothing can be done on this side unless clear clues about what's going on, so closing.

**Closed by pedrobaeza** 2020-03-26 16:07 UTC
Labels: Need information

**Comment by sswapnesh** [comment] 2020-03-26 16:21
@m3asmi  It might be due to the Missing sequence for that model.
https://github.com/odoo/odoo/blob/12.0/addons/account/models/account_move.py#L1820

Please create a sequence for `account.reconcile` and give a try.

**Comment by m3asmi** [comment] 2020-03-26 16:32
@sswapnesh exactly I just found out that after migration the default sequence has a company and I was connected to an other company
solution: verify the `account.reconcile` for the `context company`

**Comment by sswapnesh** [comment] 2020-03-26 16:33
:+1:
