### ISSUE TITLE
Web x2many form modal m2m_tag error

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#19241] opened 2017-09-04 10:26 UTC
Impacted versions: #19239 was placeholder, but this is a new issue trying to reproduce another issue, although we have been getting this occasionally in our own dev when a modal field is not defined on the tree view, although not sure if it is same issue.

Steps to reproduce:
Go to runbot, open a quotation
Click Edit
Add Contracts Analytics Tag
Click Save

Current behavior:
Error:
TypeError: field is undefined

http://260391-master-aee43c.runbot10.odoo.com/web/content/1921-d26dffe/web.assets_backend.js:1195
Traceback:
_parseServerData/<@http://260391-master-aee43c.runbot10.odoo.com/web/content/1921-d26dffe/web.assets_backend.js:1195:983
_.forEach@http://260391-master-aee43c.runbot10.odoo.com/web/content/1902-8b050d3/web.assets_common.js:12:558
_parseServerData@http://260391-master-aee43c.runbot10.odoo.com/web/content/1921-d26dffe/web.assets_backend.js:1195:905
_readUngroupedList/</<@http://260391-master-aee43c.runbot10.odoo.com/web/content/1921-d26dffe/web.assets_backend.js:1204:352
_.forEach@http://260391-master-aee43c.runbot10.odoo.com/web/content/1902-8b050d3/web.assets_common.js:12:558
_readUngroupedList/<@http://260391-master-aee43c.runbot10.odoo.com/web/content/1921-d26dffe/web.assets_backend.js:1204:48
then/</</<@http://260391-master-aee43c.runbot10.odoo.com/web/content/1902-8b050d3/web.assets_common.js:802:678
fire@http://260391-master-aee43c.runbot10.odoo.com/web/content/1902-8b050d3/web.assets_common.js:796:281
fireWith@http://260391-master-aee43c.runbot10.odoo.com/web/content/1902-8b050d3/web.assets_common.js:801:198
Deferred/</deferred[tuple[0]]@http://260391-master-aee43c.runbot10.odoo.com/web/content/1902-8b050d3/web.assets_common.js:803:31
rpc/</<@http://260391-master-aee43c.runbot10.odoo.com/web/content/1902-8b050d3/web.assets_common.js:3856:346
then/</</<@http://260391-master-aee43c.runbot10.odoo.com/web/content/1902-8b050d3/web.assets_common.js:802:678
fire@http://260391-master-aee43c.runbot10.odoo.com/web/content/1902-8b050d3/web.assets_common.js:796:281
fireWith@http://260391-master-aee43c.runbot10.odoo.com/web/content/1902-8b050d3/web.assets_common.js:801:198
Deferred/</deferred[tuple[0]]@http://260391-master-aee43c.runbot10.odoo.com/web/content/1902-8b050d3/web.assets_common.js:803:31
fire@http://260391-master-aee43c.runbot10.odoo.com/web/content/1902-8b050d3/web.assets_common.js:796:281
fireWith@http://260391-master-aee43c.runbot10.odoo.com/web/content/1902-8b050d3/web.assets_common.js:801:198
then/</</<@http://260391-master-aee43c.runbot10.odoo.com/web/content/1902-8b050d3/web.assets_common.js:802:849
fire@http://260391-master-aee43c.runbot10.odoo.com/web/content/1902-8b050d3/web.assets_common.js:796:281
fireWith@http://260391-master-aee43c.runbot10.odoo.com/web/content/1902-8b050d3/web.assets_common.js:801:198
then/</</<@http://260391-master-aee43c.runbot10.odoo.com/web/content/1902-8b050d3/web.assets_common.js:802:849
fire@http://260391-master-aee43c.runbot10.odoo.com/web/content/1902-8b050d3/web.assets_common.js:796:281
fireWith@http://260391-master-aee43c.runbot10.odoo.com/web/content/1902-8b050d3/web.assets_common.js:801:198
done@http://260391-master-aee43c.runbot10.odoo.com/web/content/1902-8b050d3/web.assets_common.js:1192:86
callback@http://260391-master-aee43c.runbot10.odoo.com/web/content/1902-8b050d3/web.assets_common.js:1212:15
Expected behavior:

Video/Screenshot link (optional):

**Comment by mge-odoo** [comment] 2017-11-28 12:41
Hi @gdgellatly 

Thanks for reporting the issue.
However it seems to be fixed in master ; I can't reproduce your traceback.
Probably by one of the innumerable commits to fixes the new view refactoring.
Do not hesitate to re-open it if this issue still applies.

Regards,

Martin

**Closed by mge-odoo** 2017-11-28 12:41 UTC
Labels: Framework
