### ISSUE TITLE
Attachment '_inverse_datas' override

### ISSUE THREAD

**Issue by keshrath** [odoo/odoo#33456] opened 2019-05-17 07:40 UTC
Impacted versions:

12.0

Steps to reproduce:

Override the method `_inverse_datas` to add ,for example, a new storage type.

Current behavior:

It is currently not possible to cleanly overwrite the `_inverse_datas` method. This is because in `write` the two fields `file_size` and `checksum` are automatically set to False. This makes it impossible to call write of super from the overwritten `_inverse_datas` method, as these fields will be deleted in any case. Both currently available solutions are not very clean. Either call super from `_inverse_datas` and then delete the unnecessarily data that has been created. Or the more performant method, but for the maintainability of the code problematic, directly call `models.Model.write(attach.sudo(), vals)` instead of `super(IrAttachment, attach.sudo()).write(vals)`.

Expected behavior:

It should be possible to overwrite `_inverse_datas` cleanly.

Video/Screenshot link (optional):

https://github.com/odoo/odoo/blob/12.0/odoo/addons/base/models/ir_attachment.py#L468

**Comment by pedrobaeza** [comment] 2019-05-17 07:51
Sorry, but the method you are mentioning is an internal method (prefixed with `_`), and thus, it's not expected to be overridden. You must find another way to perform what you want, or propose a patch (to master) easing the inheritance.

Closing as no Odoo issue, but internal coding wishlist.

**Closed by pedrobaeza** 2019-05-17 07:51 UTC

**Comment by Yenthe666** [comment] 2019-05-17 07:53
There is already a PR against master Pedro (https://github.com/odoo/odoo/pull/33392). This could be closed anyways as PR's go over issues. :)

**Comment by pedrobaeza** [comment] 2019-05-17 07:55
OK, then we have a possible path, but the issue is a no-go.

**Comment by keshrath** [comment] 2019-05-17 07:58
`write` is the reason for this problem and it is not an internal method

**Comment by pedrobaeza** [comment] 2019-05-17 08:01
Well, any way, the procedure for changing that is the same: via PR.

**Comment by keshrath** [comment] 2019-05-17 08:08
I'll add the change to the PR. Thanks for the feedback.
