### ISSUE TITLE
While trying to restrore more than 300MB memory producing restore error

### ISSUE THREAD

**Issue by georgeppts** [odoo/odoo#22355] opened 2018-01-18 18:04 UTC
Impacted versions: 10.0

Steps to reproduce: Take backup from web/database/manager. DB size should be more than 300MB

Current behavior: Database restore error: 

Expected behavior: DB need to restore

Video/Screenshot link (optional):

**Comment by Elkasitu** [comment] 2018-01-18 21:08
Are you sure you're on the latest revision? Because we recently [merged a PR](https://github.com/odoo/odoo/pull/22131) which _should have_ fixed this.

**Comment by Yenthe666** [comment] 2018-01-19 09:09
Indeed - this should have been handled. Before this commit I've had multiple databases with a bigger size working too though.
@georgeppts how much RAM does your server have by the way?

**Comment by DimaDevOps** [comment] 2019-05-21 11:44
@Yenthe666  Hi,

I'm having the same issue with restoring a database in 8.0, it's 500mb and i'm getting Memory Error.  I have a 4gb server. I tried to increase  the memory in odoo config file but without succes, i'm still geting error. Any advice? Thank you!

**Comment by Yenthe666** [comment] 2019-10-07 09:47
Dear @georgeppts,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe

**Closed by Yenthe666** 2019-10-07 09:47 UTC
Labels: 10.0
