### ISSUE TITLE
[12.0] pay directly in in Payment Receipt creates wrong entries

### ISSUE THREAD

**Issue by mmotahar-ia** [odoo/odoo#31613] opened 2019-03-06 02:52 UTC
Impacted versions:
12.0 E
12.0 C
Steps to reproduce:
=================================================
Go to V11 and create a sales receipts 
and set 'pay directly' 
Add a line and select any test accounts like 101120 Stock Interim Account (Received)
Set unit price to 120 and quantity to 1
Click on validate
and write down journal entry
Review the generated journal entry

Go to V12 and create a sales receipts 
and set 'pay directly' 
Add a line Select any test accounts like 101120 Stock Interim Account (Received)
Set unit price to 120 and quantity to 1
Click on validate
and write down journal entry

**It asks you to select the account field which is new (despite you selecting the direct pay ) and you can only select account receivable.**
No choice you have to select that to save the entry, So select it and save the record
click on validate
Review the generated journal entry and compare it with V11

Current behaviour:
=================================================

in V11 you get this : 

| Account                                                             |  Debit  |     Credit |    Date |
| - | - | - | - |
| 101120 Stock Interim Account (Received)      | $ 0.00 | $ 120.00 | 03/06/2019 |
| 101401 Bank                                                   | $ 120.00 | $ 0.00 | 03/06/2019 |

in V12 you get this:

| Account                                                             |  Debit  |     Credit  |   Date |
| - | - | - | - |
| 101120 Stock Interim Account (Received)       | $ 0.00 | $ 120.00 | 03/06/2019 |
| **101200 Account Receivable**                        | $ 120.00 | $ 0.00 | 03/06/2019 |

Expected behaviour:
====================================================
V11 was correct. But in V12 is clearly incorrect

1. first of all it should NOT make the account field mandatory when we select pay directly. 
2. Domain set against that field has to be updated too 
3.  entry should be exactly similar to V11. The whole purpose of "Pay Directly" is NOT to get the AR/AC involved in the process and yet in V12 it creates an entry and debit / credit the account receivable  or account payable in both sale receipts and purchase receipts. 

Video/Screenshot link (optional):
=====================
https://www.youtube.com/watch?v=RCshJbX6L_w&feature=youtu.be

See how I generated the entry in Both V11 and V12  and the difference between these versions

**Comment by william-andre** [comment] 2019-03-07 10:23
As I understand it, the behaviour in 12 is intended. Two moves are created instead of one like previously. The second move is reconciled between the account receivable and the bank like this

| Account                                                             |  Debit  |     Credit  |   Date |
| - | - | - | - |
| 101401 Bank                                                   | $ 120.00 | $ 0.00 | 03/06/2019 |
| 101200 Account Receivable                            | $ 0.00 | $ 120.00 | 03/06/2019 |

**Comment by seyed-mohammad-motahar** [comment] 2019-03-12 02:36
> As I understand it, the behaviour in 12 is intended. Two moves are created instead of one like previously. The second move is reconciled between the account receivable and the bank like this
> 

I think the behaviour of V12 is exactly the same regardless of what you choose in the "Payment" option, Whether it is to pay now or pay later, Journal entries at the end are exactly the same.

**Comment by william-andre** [comment] 2019-03-12 08:07
This feature allows you to register a payment directly instead of later, not to change the way it is reconciled or written in your journals

**Comment by mart-e** [comment] 2019-11-04 10:00
Closing as having the intended behaviour as explained by William

**Closed by mart-e** 2019-11-04 10:00 UTC
Labels: 12.0, Accounting
