### ISSUE TITLE
Error: Perhaps you need a different "datestyle" setting.

### ISSUE THREAD

**Issue by aaly-dp** [odoo/odoo#78747] opened 2021-10-21 10:03 UTC
Impacted versions:
15.0
Steps to reproduce:
Install Module timesheet_grid
Navigate through: Timesheets > To Validate > Last Week
error occures
Current behavior:
Error message with:
Traceback (most recent call last):
  File "/home/aaly/gitrepos/demo15e/odoo/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/aaly/gitrepos/demo15e/odoo/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
psycopg2.errors.DatetimeFieldOverflow: date/time field value out of range: "1-1-1970"
LINE 1: ...10-14')) AND ((("account_analytic_line"."date" >= '1-1-1970'...
                                                             ^
HINT:  Perhaps you need a different "datestyle" setting.

The Problem is probably the line: 
domain_search.append((name, operator, '1-1-2250' if operator in ['<', '<='] else '1-1-1970'))

Expected behavior:
No Error
Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/32839388/138256300-f2963c31-7cd5-4fa0-ac00-0dd5af96b995.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by XeJames** [comment] 2022-01-21 12:58
Well, I just got hit with this.  Is it still not fixed three months later, or has this just not been updated?  I kind of hate charging to upgrade a client if it doesn't fix the problem...

**Comment by XeJames** [comment] 2022-01-22 19:40
> Well, I just got hit with this. Is it still not fixed three months later, or has this just not been updated? I kind of hate charging to upgrade a client if it doesn't fix the problem...
> 
> Update: Ouch. Reinstalled odoo/enterprise 14.0 branch from git to ensure latest possible patches - error persists.
> 
> Can someone confirm that maybe I just need to change the date format from '1-1-1970' to '1970-01-01'? Has anyone corrected this?

Workaround:
The problem appears to be only in the view itself.  While it is not possible in the HR app, from the Project View or the Timesheet View, simply choose the List View rather than Grid View and it is possible to view and validate timesheet entries.

I have opened a support ticket for information on how best to fix this in code but will advise clients to simply bypass the Grid View of Timesheet Entries until further notice.

**Comment by XeJames** [comment] 2022-04-20 14:02
Well, it is now April 20th and this bug is not yet assigned.  I am hoping that my comment might "bump" something so it gets noticed.

I opened a ticket with Odoo and was told that since my db is "on-premise" they couldn't do anything about it, but they could not reproduce the issue at their end.

This appears, to me, to be a PGSQL date format issue, doesn't it?  @Yenthe666 can one of the db devs at least glance at this and confirm that this is a PGSQL error?  I am starting to suspect that Odoo has migrated on to a newer version of psychopg and perhaps some on-prems need to get onto the same version as Odoo.  But this is a huge amount of guessing when all a dev needs to do is take a quick look at his source.  My first impression is that the date format should have been converted into mmmmddyy for pgsql - but hey, I'm not the coder who made that decision.

Help, please.

**Comment by Yenthe666** [comment] 2022-04-21 08:59
Sorry, I've given up on managing Odoo issues as an outsider. Odoo does not care about publicly reported issues it seems so I was only yelling into a void most of the time. Chances of you getting a feedback from an Odoo dev are near to zero.
If you have an enterprise license you can report it through the official channels though.

**Comment by XeJames** [comment] 2022-04-21 12:31
Thanks @Yenthe666 , I guess you answered my question.  I do have an Enterprise subscription but the only response is "we cannot duplicate it on our system" - and that's the end of it.  Being on-premise is rough in cases like this.

I'll keep trying to get a solution from Odoo and will post when I do.

(tagging @fpodoo for escalation)

**Comment by xavierbol** [comment] 2022-11-18 09:38
Hello @aaly-dp and @XeJames , 

Sorry for the delay, normally the issue should be fixed in 16.0 with the following enterprise PR: odoo/enterprise#25922.
I will backport the fix to be sure we don't have the issue in the previous versions.

Sorry about that. I will link the PR to the fix.

Can you check in 16.0 to be sure it works as expected? Because I cannot reproduce the issue on my computer. Thanks in advance! 🙂

cc @IT-Ideas

**Closed** 2022-11-21 16:11 UTC
Labels: Confirmed, Services, 14.0, 15.0

**Comment by XeJames** [comment] 2023-01-26 16:00
> Hello @aaly-dp and @XeJames , 
> 
> 
> 
> Sorry for the delay, normally the issue should be fixed in 16.0 with the following enterprise PR: odoo/enterprise#25922.
> 
> I will backport the fix to be sure we don't have the issue in the previous versions.
> 
> 
> 
> Sorry about that. I will link the PR to the fix.
> 
> 
> 
> Can you check in 16.0 to be sure it works as expected? Because I cannot reproduce the issue on my computer. Thanks in advance! 🙂
> 
> 
> 
> cc @IT-Ideas 

Confirmed. Thanks.
