### ISSUE TITLE
Modify the name and sub-dir of uploaded files 

### ISSUE THREAD

**Issue by xiasun** [odoo/odoo#11284] opened 2016-03-10 03:43 UTC
Impacted versions: 8.0

Steps to reproduce: Not a bug

Current behavior: File uploaded with knowledge and document module are stored with a random name and directory.

Expected behavior: I want to have the file name and sub-dir modified depends on my need. Is that possible? I think I may modify the code where uploaded file is processed and saved... can you show me where are those code?

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment] 2017-11-26 15:17
Hi @xiasun,

Thanks for your report and my apologies for the very late response.
As this is not a bug but a question you should ask it on the help forums (help.odoo.com) where other people can help you.
As Odoo 8 is no longer supported either I'm closing this report.

Regards,
Yenthe

**Closed by Yenthe666** 2017-11-26 15:17 UTC
Labels: question
