### ISSUE TITLE
Account move can create duplicate lines when you attempt to post directly before saving new lines

### ISSUE THREAD

**Issue by MasterBlaster479** [odoo/odoo#5629] opened 2015-03-06 12:48 UTC
https://www.youtube.com/watch?v=G4MH7wO7dfg&feature=youtu.be

When you add a new line on one2many list and try to create it with a button_validate. It duplicates lines although the method returns exception and warning message. This behaviour is dangerous and is present in OpenERP version 7 and Odoo version 8.

**Comment by timdiam** [comment] 2015-05-26 17:39
Has this been addressed yet?  This functionality is SUPER dangerous.

**Comment by heshamfm** [comment] 2015-05-26 23:40
Does this behavior take place in other similar views? Do you think the issue could be worked-around by dimming the `Post` button if view is not saved yet?

**Comment by timdiam** [comment] 2015-05-26 23:54
I have a fix, but the problem is I'm not too confident in the javascript.  This really should be solved by the core-team.  Heres a link to my two fixes:

http://pastebin.com/m896eGXB

Let me know what you think.  We have tested patch # 1 extensively.  But patch number 2 we added today.

**Comment by Yenthe666** [comment] 2015-05-27 05:53
@MasterBlaster479 thanks for posting it both here and on the Odoo forums. This should REALLY be addressed..
@odony and @beledouxdenis have a look at this please? This should be fixed asap.

**Comment by timdiam** [comment] 2015-06-13 00:39
Hi everyone,

It looks like the fix I had put on the paste bin fixes most scenarios, however now we get the following error, specifically when hitting an object button that deletes entries from a one2many on the object.  When the form is reloaded, the client errors out, with a "Uncaught record not correctly loaded" error.  This error is thrown from this piece of code: (in data.js (version 7.0))

        var return_records = function() {
            var records = _.map(ids, function(id) {
                var c = _.find(self.cache, function(c) {return c.id === id;});
                return _.isUndefined(c) ? c : _.extend({}, c.values, {"id": id});
            });
            if (self.debug_mode) {
                if (_.include(records, undefined)) {
                    throw "Record not correctly loaded";
                }
            }
            var sort_fields = self._sort,
                    compare = function (v1, v2) {
                        return (v1 < v2) ? -1
                             : (v1 > v2) ? 1
                             : 0;
                    };

**Comment by leahim** [comment] 2015-08-26 12:17
In views.js (v7.0) -> do_execute_action
replace :
```javascript
1491:  return dataset.call_button(action_data.name, args).then(handler).then(function () {
```
with:
```javascript
return dataset.call_button(action_data.name, args).then(handler,function () { self.recursive_reload();}).then(function () {
```
This alleviates (didn't test it thoroughly, tested on v7.0 only) or eliminates duplication issues.. Added fail handler which reloads view.. Similar solution as timdiam's ( thx @timdiam ) , but without reloading issues.. Feedback please. 
Regards!

**Comment by gdgellatly** [comment] 2015-08-26 23:18
Thankyou so much, I've been tracing this for ages.

**Comment by spadae22** [comment] 2015-08-27 03:03
Yes major issue. Users have no idea, we have a credit hold function and when line duos they have no idea.

**Comment by spadae22** [comment] 2015-11-24 17:50
Tested on v8! Solved our issue. Will this be pushed?

**Comment by Yenthe666** [comment] 2017-12-14 07:51
Hi @MasterBlaster479,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Closed by Yenthe666** 2017-12-14 07:51 UTC
Labels: confirmed

**Comment by jado95** [comment] 2018-12-10 13:33
@leahim Hi, 
I have the same problem with the orders and with invoice. 
For example in draft invoice if you add new line and validate before save, the line are duplicated.
Have you a solution, please?
