### ISSUE TITLE
how to add a column which just index the reord in the tree view, but not save it into the model.

### ISSUE THREAD

**Issue by hackrole** [odoo/odoo#8401] opened 2015-09-06 06:50 UTC
I may write like this.

``` xml
<t t-foreach='teachers' t-as='teacher'>
   <p><t t-esc='teacher_index + 1'/></p>
    <p><t t-esc='teacher.id' /></p>
    <p><t t-esc='teacher.name' /></p>
</t>
```

but I was telled to must-use tree-view (cause of the old code).

``` xml
        <record id="teacher_view_tree" model="ir.ui.view">
            <field name="name">teachers.tree</field>
            <field name="model">teachers</field>
            <field name="arch" type="xml">
                <tree>
                    <field name='id' />
                    <field name="name" />
                </tree>
            </field>
        </record>
```

so how can I add this column to the tree view. the doc not help.

**Comment by Yenthe666** [comment] 2018-03-21 16:40
Hi @hackrole,

Sorry for the late reply on this.
As this is a question about custom development and not a bug in Odoo I'm afraid I have to close this. The Github tracker is only for bugs in the official code. Please do ask these questions on the official help forums (at help.odoo.com) in the future.
P.S: I don't understand the question so can't answer it either, I assume you've solved it by now.

Regards,
Yenthe

**Closed by Yenthe666** 2018-03-21 16:40 UTC
Labels: Question
