### ISSUE TITLE
Deprecated Warning when starting server

### ISSUE THREAD

**Issue by bjellesma** [odoo/odoo#83878] opened 2022-02-03 05:20 UTC
Impacted versions: 14.0

Steps to reproduce: Start the server from the CLI with `./odoo-bin`. I am running Linux Mint 19.3.

Current behavior:

I am receiving the following traceback in my logs:

```
py.warnings odoo/addons/base/models/ir_actions_report.py:73: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
File "./odoo-bin", line 8, in <module>
    odoo.cli.main()
  File "odoo/cli/command.py", line 61, in main
    o.run(args)
  File "odoo/cli/server.py", line 176, in run
    main(args)
  File "odoo/cli/server.py", line 170, in main
    rc = odoo.service.server.start(preload=preload, stop=stop)
  File "odoo/service/server.py", line 1286, in start
    load_server_wide_modules()
  File "odoo/service/server.py", line 1196, in load_server_wide_modules
    odoo.modules.module.load_openerp_module(m)
  File "odoo/modules/module.py", line 396, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "odoo/addons/base/__init__.py", line 5, in <module>
    from . import models
  File "odoo/addons/base/models/__init__.py", line 13, in <module>
    from . import ir_actions_report
  File "odoo/addons/base/models/ir_actions_report.py", line 73, in <module>
    if LooseVersion(version) >= LooseVersion('0.12.2'):
```

Expected behavior:

Though I can start the server, I can't find any information online about what this error is.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by william-andre** [comment] 2022-02-28 16:51
https://github.com/odoo/odoo/pull/84097 is a duplicate of this issue, but since that one already has some answers, I'm closing this one to avoid discussion in multiple places

**Closed by william-andre** 2022-02-28 16:51 UTC
