### ISSUE TITLE
Error accessing a database restored OpenERP 7.0

### ISSUE THREAD

**Issue by amartinf** [odoo/odoo#2997] opened 2014-10-09 15:23 UTC
2014-10-09 15:04:47,598 21267 ERROR IGCGES2 openerp.netsvc: 'NoneType' object has no attribute 'create'
Traceback (most recent call last):
  File "/opt/openerp/server/openerp/netsvc.py", line 296, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/opt/openerp/server/openerp/service/web_services.py", line 433, in dispatch
    return fn(*params)
  File "/opt/openerp/server/openerp/service/web_services.py", line 444, in exp_authenticate
    res_users = pooler.get_pool(db).get('res.users')
  File "/opt/openerp/server/openerp/pooler.py", line 49, in get_pool
    return get_db_and_pool(db_name, force_demo, status, update_module)[1]
  File "/opt/openerp/server/openerp/pooler.py", line 33, in get_db_and_pool
    registry = RegistryManager.get(db_name, force_demo, status, update_module)
  File "/opt/openerp/server/openerp/modules/registry.py", line 203, in get
    update_module)
  File "/opt/openerp/server/openerp/modules/registry.py", line 233, in new
    openerp.modules.load_modules(registry.db, force_demo, status, update_module)
  File "/opt/openerp/server/openerp/modules/loading.py", line 435, in load_modules
    model._register_hook(cr)
  File "/opt/openerp/server/openerp/addons/base_action_rule/base_action_rule.py", line 202, in _register_hook
    model_obj.create = self._wrap_create(model_obj.create, model)
AttributeError: 'NoneType' object has no attribute 'create'

**Comment by Yenthe666** [comment] 2016-06-03 09:38
Hi @amartinf,

I can no longer reproduce this issue on the latest Odoo code.
If you still face this issue please update your codebase to the latest version.
Closing this issue since I cannot reproduce this anymore.

Regards,
Yenthe

**Closed by Yenthe666** 2016-06-03 09:38 UTC
