### ISSUE TITLE
[9.0] project task remaining hours 0 when no timesheet

### ISSUE THREAD

**Issue by i4knowledge** [odoo/odoo#9426] opened 2015-11-05 07:44 UTC
The Remaining Hours of a project task are set to zero when Initially Planned Hours are filled in but no timesheets are registered:
0. installed project management with time on tasks
1. create a project task
2. fill in Initially Planned Hours p
3. click on tab Timesheets (there are none) and save (you can quickly see that Remaining Hours is calculated, but then also set to zero) and you'll see that Remaining Hours = 0 where it should be Remaining Hours = p
4. edit the project task and create a timesheet with duration d hours
5. save the task and you'll see that it is now calculated correctly as  Remaining Hours = p-d

**Comment by pedrobaeza** [comment] 2018-04-10 00:47
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-04-10 00:47 UTC
Labels: 9.0, Services
