### ISSUE TITLE
Odoo11 - Negative amount shown as vertical bar in invoice line item

### ISSUE THREAD

**Issue by newodoo** [odoo/odoo#25840] opened 2018-07-18 10:55 UTC
Impacted versions: Odoo 11 on windows server 2012

Steps to reproduce: 
Create a new out invoice, select a product and set a negative amount for unit price.
Print the invoice.

Current behavior:
in PDF the char "-" is shown as "|" even if the total amount is correct (amount1 - amount2 = total)

Expected behavior:
the printed invoice should show the char "-"

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/37513316/42877323-8c712b2e-8a89-11e8-9690-27f00e08b6b2.png)

this is the negative item on odoo:
![image](https://user-images.githubusercontent.com/37513316/42877389-bf04eba2-8a89-11e8-91c0-e38059673b42.png)

**Comment by edsersolis** [comment] 2018-07-19 11:35
You seem to have a custom report. This doesn't happen in runbot when tested with OEM reports.

**Comment by pedrobaeza** [comment] 2018-07-19 11:41
Duplicate of #17093

See a possible solution in https://github.com/odoo/odoo/issues/17093#issuecomment-349665890

**Closed by pedrobaeza** 2018-07-19 11:41 UTC

**Comment by newodoo** [comment] 2018-07-19 14:11
@pedrobaeza  it is duplicated, but in the issue #17093 (I've read it before opening the new issue) there is not a solution for windows server 2012 and the issue is still there.

@edsersolis the issue seem to be only on windows server 2012.

**Comment by pedrobaeza** [comment] 2018-07-19 14:36
Then you should consider change platform, maybe through a Linux Virtual Machine, or replicate the solution on that OS.

**Comment by edsersolis** [comment] 2018-07-19 20:37
@newodoo as @pedrobaeza states you should consider changing OS. I haven't seen the first stable instance in a Windows environment and you'll keep having this kind of issues along the time you keep using Odoo as features will be mainly focused with Linux in mind.

**Comment by nle-odoo** [comment] 2018-07-27 15:48
Hi @newodoo 

This should be solved in 9.0 with https://github.com/odoo/odoo/commit/cb2a3afa7e0

To have the solution available in 11.0, you have to wait for forward-port from 9.0 to 11.0 (the last one was 2 days ago) that should be done at the latest in one week, and once it is in 11.0 the installation bundles should be updated the day after.

Regards.

**Comment by newodoo** [comment] 2018-08-23 10:58
@nle-odoo thanks for the reply, can I have the reference to the fix on Odoo11? I would like to put it manually on my server.

**Comment by nle-odoo** [comment] 2018-08-23 11:13
In 11.0, there was several commits from forward-port and additions:

- https://github.com/odoo/odoo/commit/3a14b75518ab5c9a62dfb0238e9c5f04d957a25f
- https://github.com/odoo/odoo/commit/91d647ecf75d82ef26d16a96fc5c2930fbf835f7
- https://github.com/odoo/odoo/commit/248a59553dfbfb84371451bee33621172c451c4b

do note that the last one contains unrelated changes, the only change that solved this issue were about the replacement of `\u2011` with `-\N{ZERO WIDTH NO-BREAK SPACE}`.
