### ISSUE TITLE
what causes this ???!!!

### ISSUE THREAD

**Issue by Include-Dev** [odoo/odoo#43738] opened 2020-01-22 11:44 UTC
Error:
Odoo Server Error

Traceback (most recent call last):
File "/home/hashim/odoo_13/odoo/http.py", line 619, in _handle_exception
return super(JsonRequest, self)._handle_exception(exception)
File "/home/hashim/odoo_13/odoo/http.py", line 309, in _handle_exception
raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
File "/home/hashim/odoo_13/odoo/tools/pycompat.py", line 14, in reraise
raise value
File "/home/hashim/odoo_13/odoo/http.py", line 664, in dispatch
result = self._call_function(**self.params)
File "/home/hashim/odoo_13/odoo/http.py", line 345, in _call_function
return checked_call(self.db, *args, **kwargs)
File "/home/hashim/odoo_13/odoo/service/model.py", line 93, in wrapper
return f(dbname, *args, **kwargs)
File "/home/hashim/odoo_13/odoo/http.py", line 338, in checked_call
result = self.endpoint(*a, **kw)
File "/home/hashim/odoo_13/odoo/http.py", line 909, in __call__
return self.method(*args, **kw)
File "/home/hashim/odoo_13/odoo/http.py", line 510, in response_wrap
response = f(*args, **kw)
File "/home/hashim/odoo_13/addons/web/controllers/main.py", line 1319, in call_kw
return self._call_kw(model, method, args, kwargs)
File "/home/hashim/odoo_13/addons/web/controllers/main.py", line 1311, in _call_kw
return call_kw(request.env[model], method, args, kwargs)
File "/home/hashim/odoo_13/odoo/api.py", line 391, in call_kw
result = _call_kw_model(method, model, args, kwargs)
File "/home/hashim/odoo_13/odoo/api.py", line 364, in _call_kw_model
result = method(recs, *args, **kwargs)
File "/home/hashim/odoo_13/odoo/models.py", line 4818, in search_read
records = self.search(domain or [], offset=offset, limit=limit, order=order)
File "/home/hashim/odoo_13/odoo/models.py", line 1609, in search
res = self._search(args, offset=offset, limit=limit, order=order, count=count)
File "/home/hashim/odoo_13/odoo/addons/base/models/ir_attachment.py", line 412, in _search
if self.env.is_system():
File "/home/hashim/odoo_13/odoo/api.py", line 523, in is_system
return self.su or self.user._is_system()
File "/home/hashim/odoo_13/odoo/tools/func.py", line 24, in __get__
value = self.fget(obj)
File "/home/hashim/odoo_13/odoo/api.py", line 530, in user
return self(su=True)['res.users'].browse(self.uid)
TypeError: __call__() got an unexpected keyword argument 'su'

**Comment by pedrobaeza** [comment] 2020-01-22 21:35
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Yenthe666** [comment] 2020-03-08 19:27
I'm closing this bug report as there has been no response/feedback to the questions asked by @pedrobaeza

**Closed by Yenthe666** 2020-03-08 19:27 UTC
Labels: Need information
