### ISSUE TITLE
Odoo Point of Sale Session Settings Error:   this.editor.snippetsMenu

### ISSUE THREAD

**Issue by ashishbigbos** [odoo/odoo#20266] opened 2017-10-18 06:18 UTC
I am a Odoo community user in Windows Operating System.

While I tried to setting up a Point of sale session I got the following error. I searched through Odoo community and as suggested installed the latest code again but it did not fixed. I tried the runbot and got the same error. Here is my odoo test credential:

**URL: https://xpro-solutions-pvt-ltd.odoo.com/web
Email: ashish@xprosolutions.co.in
Password: diehard4**

The error contest is as below,
-------------------------------------
**TypeError: this.editor.snippetsMenu is undefined**

http://localhost:8069/web/content/446-1baaebf/web.assets_backend.js:1992
Traceback:
commitChanges@http://localhost:8069/web/content/446-1baaebf/web.assets_backend.js:1992:1
OdooClass.extend/</prototype[name]</<@http://localhost:8069/web/content/319-20613d5/web.assets_common.js:3811:485
commitChanges/defs<@http://localhost:8069/web/content/446-1baaebf/web.assets_backend.js:1261:184
_.collect@http://localhost:8069/web/content/319-20613d5/web.assets_common.js:13:270
commitChanges@http://localhost:8069/web/content/446-1baaebf/web.assets_backend.js:1261:123
exec/<@http://localhost:8069/web/content/319-20613d5/web.assets_common.js:3997:295
then/</</<@http://localhost:8069/web/content/319-20613d5/web.assets_common.js:802:678
fire@http://localhost:8069/web/content/319-20613d5/web.assets_common.js:796:281
add@http://localhost:8069/web/content/319-20613d5/web.assets_common.js:797:467
then/</<@http://localhost:8069/web/content/319-20613d5/web.assets_common.js:802:631
each@http://localhost:8069/web/content/319-20613d5/web.assets_common.js:625:758
then/<@http://localhost:8069/web/content/319-20613d5/web.assets_common.js:802:553
Deferred@http://localhost:8069/web/content/319-20613d5/web.assets_common.js:803:189
then@http://localhost:8069/web/content/319-20613d5/web.assets_common.js:802:518
exec@http://localhost:8069/web/content/319-20613d5/web.assets_common.js:3997:257
saveRecord@http://localhost:8069/web/content/446-1baaebf/web.assets_backend.js:1250:787
saveRecord@http://localhost:8069/web/content/446-1baaebf/web.assets_backend.js:1347:354
OdooClass.extend/</prototype[name]</<@http://localhost:8069/web/content/319-20613d5/web.assets_common.js:3811:485
_onSave@http://localhost:8069/web/content/446-1baaebf/web.assets_backend.js:1352:777
dispatch@http://localhost:8069/web/content/319-20613d5/web.assets_common.js:892:378
add/elemData.handle@http://localhost:8069/web/content/319-20613d5/web.assets_common.js:865:151

Please fix this if anybody know. Its really taken lots of effort.

I have already followed following answers but did not worked for me.
**https://github.com/odoo/odoo/issues/19948
https://github.com/odoo/odoo/issues/19908
https://github.com/odoo/odoo/issues/19947**

Thanks in advance..

**Comment by Yenthe666** [comment] 2017-10-24 06:57
@ashishbigbos please add more information. What steps did you follow? On what screen where you? Where did you click on? Without more details we can't help you further.
I believe this bug has been fixed a bit ago too. Can you still reproduce it on an official runbot?

**Comment by Yenthe666** [comment] 2017-12-07 15:41
Friendly reminder for more information.

**Comment by Yenthe666** [comment] 2017-12-27 14:10
I'm closing this bug report as there has been no more feedback and because I simply can't reproduce.

Regards,
Yenthe

**Closed by Yenthe666** 2017-12-27 14:10 UTC
Labels: need information
