### ISSUE TITLE
Difficulty repeating the company name next to the username

### ISSUE THREAD

**Issue by movahhed** [odoo/odoo#49460] opened 2020-04-13 22:43 UTC
Please advise me how to solve this problem

**Comment by movahhed** [comment] 2020-04-13 22:45
In the Odoo 12 program, wherever the user's name is, the company name is repeated twice...
companyName,CompanyName,username

**Comment by movahhed** [comment] 2020-04-13 22:50
![Untitled](https://user-images.githubusercontent.com/27208274/79168330-df50c880-7dfe-11ea-952c-24a32cde9bd0.png)

**Comment by pedrobaeza** [comment] 2020-04-14 06:57
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)? Is it only happening in your language or also on English?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by movahhed** [comment] 2020-04-14 07:43
thank you.
Yes, you are right, this happened after installing a custom module, but I don't know which module did it.
Another point in English is this problem.

**Comment by pedrobaeza** [comment] 2020-04-14 07:47
Then you should check the custom module and the problem should be solved there.

Closing as this doesn't belong to Odoo code.

**Closed by pedrobaeza** 2020-04-14 07:47 UTC
Labels: Need information
