### ISSUE TITLE
Access to self private address

### ISSUE THREAD

**Issue by tsabi** [odoo/odoo#48177] opened 2020-03-23 10:53 UTC
Impacted versions: 13e

Steps to reproduce:
* Install website module
* Create a User U
* Do not add the access to private adress group to User U
* It creates automatically a contact C1
* Modify the C1 to be a private contact
* With User U open the website

Current behavior:
```
Traceback (most recent call last):
File "/home/odoo/src/odoo/odoo/addons/base/models/qweb.py", line 332, in _compiled_fn
return compiled(self, append, new, options, log)
File "<template>", line 1, in template_web_frontend_layout_509
File "/home/odoo/src/odoo/odoo/fields.py", line 1022, in __get__
self.compute_value(record)
File "/home/odoo/src/odoo/odoo/fields.py", line 1105, in compute_value
records._compute_field_value(self)
File "/home/odoo/src/odoo/odoo/models.py", line 3917, in _compute_field_value
field.compute(self)
File "/home/odoo/src/odoo/odoo/fields.py", line 579, in _compute_related
record[self.name] = self._process_related(value[self.related_field.name])
File "/home/odoo/src/odoo/odoo/models.py", line 5610, in __getitem__
return self._fields[key].__get__(self, type(self))
File "/home/odoo/src/odoo/odoo/fields.py", line 1005, in __get__
record._fetch_field(self)
File "/home/odoo/src/odoo/odoo/models.py", line 2944, in _fetch_field
self._read(fnames)
File "/home/odoo/src/odoo/odoo/models.py", line 3060, in _read
raise self.env['ir.rule']._make_access_error('read', forbidden)
odoo.exceptions.AccessError: ('The requested operation ("read" on "Contact" (res.partner)) was rejected because of the following rules:\n- res.partner.rule.private.employee\n\n(Records: Peter (id=13), User: False (id=10))', None)

Error to render compiling AST
AccessError: ('The requested operation ("read" on "Contact" (res.partner)) was rejected because of the following rules:\n- res.partner.rule.private.employee\n\n(Records: Peter (id=13), User: False (id=10))', None)
Template: web.frontend_layout
Path: /t/html/body/div/header/nav[2]/div/div/ul/li[2]/a/b/span
Node: <span t-esc="user_id.name[:23] + '...' if user_id.name and len(user_id.name) &gt; 25 else user_id.name"/>
```

Expected behavior:
It should be accessed.

**Comment by pedrobaeza** [comment] 2020-03-23 10:56
That's the expected behavior as private addresses are intended for managers with that permission. It's also for performance reason to not check own user contact. Is any of the flows affected by this? If not, we can close this as expected behavior.

**Comment by tsabi** [comment] 2020-03-23 20:17
Hi, sorry but what? The expected behavior of Odoo is to throw an error?
I dont understand you. I was able to force an error in the code, so yes, there is something wrong. If we won't change the design, than we should implement a check on contacts that a user's contact should never be changed to private address.
Another errors can happen also: like if that user is a follower in objects, so another users won be able to see that hidden contact, or it runs to error i havent tried it. But a lot of complications can come out from this situation if we don't close it.

Is implementing a check will affect the performance? Ok, so never implement any check. And sorry to say that, but complaining about this was the ultimate card you played, with that habit dont code anything ever, because it will just eat electricity!

Or if not with a check, than we can hide the type selection widget on the UI when the contact is connected with a user. You cannot say this will significantly modify the speed of Odoo.

But i suggest another one: to modify the design, and implement a modification in the security rules: users should be create and manage private addresses under their own contact. That will be their own private addresses, like their home address, SOS contact, etc.
This is a little bit more elem in the filters. Will it do significant modification in the speed of Odoo? I don't think so...

**Comment by pedrobaeza** [comment] 2020-03-24 07:35
That's not an error in code, but an error message derived from permissions. I let other to give their opinions.

**Comment by Yenthe666** [comment] 2020-03-24 10:19
@mart-e can you please make the final call on this one?

**Comment by mart-e** [comment] 2020-03-24 11:00
@tsabi could you elaborate a bit more on how to reproduce your issue? You are publishing a traceback but I haven't been able to reproduce it, following your steps, I simply got an access right errors (which is fine).

**Comment by tsabi** [comment] 2020-03-25 11:41
@mart-e Yes, i am sorry, you right.
This traceback is thrown when the user goes to the website. The code what runs to error is in a template: web.frontend_layout.

**Comment by mart-e** [comment] 2020-03-26 11:12
@tsabi thanks for the information.
I am a bit mixed about this one. Changing the type of your partner to private address doesn't make much sense but on the other hand, you got a traceback. I see three solutions:

- change the code everywhere to be tolerant to a user not having access to its own information (not ideal)
- change the [security rule](https://github.com/odoo/odoo/blob/034c04efa4ccecd40f657eae97ef2b04934d570c/odoo/addons/base/security/base_security.xml#L76) to allow a user to read a private contact if it's its own partner
- prevent changing this kind of modification via a constraint

@odony what do you think?

**Comment by tsabi** [comment] 2020-03-26 15:44
> @tsabi thanks for the information.
> I am a bit mixed about this one. Changing the type of your partner to private address doesn't make much sense but on the other hand, you got a traceback. I see three solutions:
> 
> * change the code everywhere to be tolerant to a user not having access to its own information (not ideal)
> * change the [security rule](https://github.com/odoo/odoo/blob/034c04efa4ccecd40f657eae97ef2b04934d570c/odoo/addons/base/security/base_security.xml#L76) to allow a user to read a private contact if it's its own partner
> * prevent changing this kind of modification via a constraint
> 
> @odony what do you think?

@mart-e thank you!

One more idea: hide the type modification field from the UI if the partner is binded to an user. A constraint for this could be expensive, because it will be activated on every partner on every operation, but if we just hide the field that is cheap and will do it also.

**Comment by odony** [comment] 2020-03-27 19:25
@mart-e the option I prefer is just hiding the address type field when the `user_ids` field is set, as suggested by @tsabi, this way we limit the change to some view `attrs`.

Let's please be very careful with such a change, it's an _extremely minor_ corner case, but on a core model. We must not break anything else, otherwise the traceback/error is clearly preferable.

**Comment by rb3606** [comment] 2020-04-22 09:17
Hi i tried on runbot with 2 different use 
User A : allow private address
User B : not allow private address

Using User A i created one private address and now using User B i try to create common contact under same company then it try to read private contact created by User A. 
and giving below warning 

![image](https://user-images.githubusercontent.com/6355966/79964289-1c285980-84a8-11ea-9116-2a51f12f400c.png)


27 is id of private contact 

![image](https://user-images.githubusercontent.com/6355966/79964348-3104ed00-84a8-11ea-9a86-fcfee533dfe5.png)

**Closed** 2020-04-27 10:34 UTC
Labels: Need information
