### ISSUE TITLE
[8.0][9.0] Text fields drops \n characters on export to csv

### ISSUE THREAD

**Issue by yannprada** [odoo/odoo#10693] opened 2016-01-29 15:43 UTC
**Impacted versions**

8.0 and 9.0

**How to reproduce**
- Go to [Runbot](http://runbot.odoo.com)
- Launch a 8.0 or 9.0 instance
- Go to any tree view of any model with a Text field (Sales/After-Sale Services/Helpdesk and Support for example)
- Create / edit records to make sure they have newlines in their Text fields
- Export as csv
- Import back (without the Id field to create new record)

**Current Behavior**

\n characters are removed

**Expected Behavior**

This is a Text field, it should keep the newlines!

**Comment by pedrobaeza** [comment] 2018-04-11 22:52
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

![seleccion_013](https://user-images.githubusercontent.com/7165771/38647294-ce7bc528-3deb-11e8-992a-d3108b2111fa.png)

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there.

**Closed by pedrobaeza** 2018-04-11 22:52 UTC
Labels: 9.0, Framework
