### ISSUE TITLE
[14] POS, POS user must have access to account.cash.rounding

### ISSUE THREAD

**Issue by mhabboush97** [odoo/odoo#65943] opened 2021-02-11 10:44 UTC
Impacted versions:
14, maybe others
Steps to reproduce:
create new user, give user pos groups (either user or admin)
try to open new session
Current behavior:
Error message opens when loading pos screen that says 'You are not allowed to access 'Account Cash Rounding' (account.cash.rounding) records.'
Expected behavior:
no error message
Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment] 2021-02-11 10:50
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by mhabboush97** [comment] 2021-02-11 11:30
Yes I reproduced it in version 14
steps:
logged in as admin
created new user with only pos permission
logged in as that user
opened the session
while loading I got the same error
![image](https://user-images.githubusercontent.com/71262174/107631274-bfd03980-6c75-11eb-80a2-99223eb8381d.png)

**Comment by mhabboush97** [comment] 2021-02-13 20:35
@pedrobaeza can we have more importance to this issue please? because this makes POS unusable without accounting permission.
it could be fixed with fetching account rounding records with sudo or whatever the dev team thinks better

**Comment by pedrobaeza** [comment] 2021-02-13 21:20
Sorry, but I only tag the issues. Odoo corresponding team should check it, but there's no obligation on that. If you have an enterprise contract, you can demand an answer from odoo.com/help.

**Comment by mhabboush97** [comment] 2021-03-03 09:08
@pimodoo hello, have you had a look at it?
I cannot be the only one opening a pos session from a user without accounting access right?

**Comment by pimodoo** [comment] 2021-03-03 09:26
hello @mhabboush97 I've approved the following PR few minutes ago https://github.com/odoo/odoo/pull/67068, this should solve your issue once merged.

**Closed** 2021-03-03 09:50 UTC
Labels: 14.0, Point of Sale
