### ISSUE TITLE
[12.0] Missing "Extra Info" from Lead

### ISSUE THREAD

**Issue by Banack** [odoo/odoo#29183] opened 2018-11-30 12:10 UTC
Impacted versions: 12.0

Steps to reproduce: create a new lead with the administrator and he/she will be able to insert "Extra Info". If you try to create a new lead with another user (with or without access rights) the "Extra Info" tab will display only the title "Email" and all the other fields will be invisible (and opening the inspection in Chrome/Firefox will show that all those form fields are present but with "o_invisible_modifier" class)

Current behavior: The "Extra info" tab in the Lead view is visible (and clickable) but the information within is invisible (printed in the HTML but with class "o_invisible_modifier")

Expected behavior: The "Extra info" information in the Lead view must be visible to the user who created the lead

Video/Screenshot link (optional):
![1](https://user-images.githubusercontent.com/6949086/49288519-3d4a6d80-f4a1-11e8-8acc-aeb001059f99.png)
![2](https://user-images.githubusercontent.com/6949086/49288523-43d8e500-f4a1-11e8-86cd-713109d59c2f.png)
![3](https://user-images.githubusercontent.com/6949086/49288528-489d9900-f4a1-11e8-887b-7f461fd6cc51.png)

**Comment by pedrobaeza** [comment] 2018-12-07 17:35
Hi @Banack this is a question of having debug mode enabled or not: if you have it, then you see these fields, so it's not any bug, but the intended behavior.

Closing as no issue.

**Closed by pedrobaeza** 2018-12-07 17:35 UTC
Labels: 12.0, Services
