### ISSUE TITLE
[BUG][12]Messages cause bloking problem when we have multi company configuration with unchecked Common Contact Book

### ISSUE THREAD

**Issue by fa-odoo** [odoo/odoo#30587] opened 2019-01-28 09:06 UTC
Impacted versions:
12
Steps to reproduce:
In multi company database with unchecked common contract book, we have company A and company B:
In company A: we create a sale order and confirm it
we switch to company B and try to create a sale order

Current behavior:
The messages and activities icons on the top are not displayed and an error message is displayed.

Expected behavior:

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/42148719/51825235-99d0da00-22e4-11e9-8f82-313046784903.png)

![image](https://user-images.githubusercontent.com/42148719/51825086-51192100-22e4-11e9-8b53-cb37c05c845d.png)

**Comment by fa-odoo** [comment] 2019-01-28 10:53
@pedrobaeza

**Comment by fa-odoo** [comment] 2019-02-04 08:18
@pedrobaeza unfortunately the problem persists:
Erreur:
TypeError: this.fields.thread.$el is undefined

http://localhost:8069/web/content/2172-b8741b5/web.assets_backend.js:3193
Retraçage :
update@http://localhost:8069/web/content/2172-b8741b5/web.assets_backend.js:3193:24
_renderNode@http://localhost:8069/web/content/2172-b8741b5/web.assets_backend.js:3234:341
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8069/web/content/2165-4e9d278/web.assets_common.js:3540:368
_renderNode@http://localhost:8069/web/content/2172-b8741b5/web.assets_backend.js:3348:45
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8069/web/content/2165-4e9d278/web.assets_common.js:3540:368
_.collect@http://localhost:8069/web/content/2165-4e9d278/web.assets_common.js:13:270
_renderTagForm@http://localhost:8069/web/content/2172-b8741b5/web.assets_backend.js:1637:16
_renderNode@http://localhost:8069/web/content/2172-b8741b5/web.assets_backend.js:1629:237
_renderNode@http://localhost:8069/web/content/2172-b8741b5/web.assets_backend.js:3235:38
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8069/web/content/2165-4e9d278/web.assets_common.js:3540:368
_renderNode@http://localhost:8069/web/content/2172-b8741b5/web.assets_backend.js:3348:45
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8069/web/content/2165-4e9d278/web.assets_common.js:3540:368
_renderView@http://localhost:8069/web/content/2172-b8741b5/web.assets_backend.js:1644:1254
_renderView@http://localhost:8069/web/content/2172-b8741b5/web.assets_backend.js:3348:126
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8069/web/content/2165-4e9d278/web.assets_common.js:3540:368
_render@http://localhost:8069/web/content/2172-b8741b5/web.assets_backend.js:1575:173
updateState@http://localhost:8069/web/content/2172-b8741b5/web.assets_backend.js:1277:597
updateState@http://localhost:8069/web/content/2172-b8741b5/web.assets_backend.js:1614:8
OdooClass.extend/</prototype[name]</<@http://localhost:8069/web/content/2165-4e9d278/web.assets_common.js:3537:485
update/<@http://localhost:8069/web/content/2172-b8741b5/web.assets_backend.js:1288:135
then/</</<@http://localhost:8069/web/content/2165-4e9d278/web.assets_common.js:802:678
fire@http://localhost:8069/web/content/2165-4e9d278/web.assets_common.js:796:281
add@http://localhost:8069/web/content/2165-4e9d278/web.assets_common.js:797:467
then/</<@http://localhost:8069/web/content/2165-4e9d278/web.assets_common.js:802:649
each@http://localhost:8069/web/content/2165-4e9d278/web.assets_common.js:625:758
then/<@http://localhost:8069/web/content/2165-4e9d278/web.assets_common.js:802:553
Deferred@http://localhost:8069/web/content/2165-4e9d278/web.assets_common.js:803:189
then@http://localhost:8069/web/content/2165-4e9d278/web.assets_common.js:802:518
update@http://localhost:8069/web/content/2172-b8741b5/web.assets_backend.js:1287:828
update@http://localhost:8069/web/content/2172-b8741b5/web.assets_backend.js:1545:1287
OdooClass.extend/</prototype[name]</<@http://localhost:8069/web/content/2165-4e9d278/web.assets_common.js:3537:485
update@http://localhost:8069/web/content/2172-b8741b5/web.assets_backend.js:1656:123
OdooClass.extend/</prototype[name]</<@http://localhost:8069/web/content/2165-4e9d278/web.assets_common.js:3537:485
_setMode@http://localhost:8069/web/content/2172-b8741b5/web.assets_backend.js:1550:136
_setMode@http://localhost:8069/web/content/2172-b8741b5/web.assets_backend.js:1659:8
OdooClass.extend/</prototype[name]</<@http://localhost:8069/web/content/2165-4e9d278/web.assets_common.js:3537:485
_onEdit@http://localhost:8069/web/content/2172-b8741b5/web.assets_backend.js:1663:250
dispatch@http://localhost:8069/web/content/2165-4e9d278/web.assets_common.js:892:378
add/elemData.handle@http://localhost:8069/web/content/2165-4e9d278/web.assets_common.js:865:151

**Comment by pedrobaeza** [comment] 2019-02-04 08:20
Can you please record a video showing the problem? I'm not able to reproduce it.

**Comment by fa-odoo** [comment] 2019-02-04 09:18
![chatter_bug 1](https://user-images.githubusercontent.com/42148719/52199375-2d1a8a00-2866-11e9-83d3-d1eadb912e11.gif)

**Comment by fa-odoo** [comment] 2019-02-04 09:20
@pedrobaeza

**Comment by pedrobaeza** [comment] 2019-02-04 10:12
The quality of the video is so bad that I can hardly see, but now I have it clear: you are switching company from the form view, and by default, Odoo preserves the same URL when switching it, so it results in you trying to see a sales order from another company, and the error.

This is not really a bug, but you need to know that. It's very easy to avoid, not switching company in a form view of a document that is specific for a company, or if done, simply click then on another menu for continuing.

Closing this as no real bug, but known behavior when switching companies. This was decided as it was preferable for the rest of the cases to not lose the path.

**Comment by fa-odoo** [comment] 2019-02-04 11:02
@pedrobaeza thanks for your collaboration but you have misunderstood the point. please check the link above

**Comment by pedrobaeza** [comment] 2019-02-04 11:20
OK, now the video is clearer. It seems very weird to me any way, as I haven't experimented this problem, but I'm reopening and tagging for wider investigation. Any way, if you have an enterprise contract, you should pass the ticket for this, or it might be not handled.

**Comment by len-odoo** [comment] 2019-02-12 16:03
Closed by https://github.com/odoo/odoo/pull/30364

**Closed by len-odoo** 2019-02-12 16:03 UTC
Labels: 12.0, Services
