### ISSUE TITLE
Bank statement: invoices statutes settled

### ISSUE THREAD

**Issue by hugo49** [odoo/odoo#34252] opened 2019-06-19 16:55 UTC
Impacted versions: 12

I do not understand, when I enter bank statements, bills are not settled. They remain in payment. If I understand correctly, the bank statement classifies bills paid status. I understand the dates, the partner, the memo sent by the bank and the amount. How do I proceed ?

**Comment by pedrobaeza** [comment] 2019-06-19 20:50
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by hugo49** [comment] 2019-06-20 07:48
Thank you for this return. Here are some screenshots. I took as an example a customer with his invoices and his various regulations with the credit card account. Usually it's an automatic account. In this example, it is in manual mode for entering the 2018 fiscal year. Is there a problem in the way of doing things? Or in the setting? Thank you

![01](https://user-images.githubusercontent.com/31773831/59830447-f4281100-933f-11e9-837a-4ee675785d9f.png)
![02](https://user-images.githubusercontent.com/31773831/59830449-f4c0a780-933f-11e9-9dbe-3d84da938113.png)
![03](https://user-images.githubusercontent.com/31773831/59830450-f4c0a780-933f-11e9-98d7-be7ba0d63492.png)
![04](https://user-images.githubusercontent.com/31773831/59830451-f4c0a780-933f-11e9-9850-afe18cfa9b1f.png)

**Comment by pedrobaeza** [comment] 2019-06-20 11:37
As said, please try to reproduce the problem in a runbot instance, which is free for distortions and with latest code.

**Comment by hugo49** [comment] 2019-06-20 11:57
it's not the right password and id. admin / admin

**Comment by pedrobaeza** [comment] 2019-06-20 12:03
It should be if not changed. Try on other older instance.

**Comment by hugo49** [comment] 2019-06-20 12:14
I do not understand.

On the test instance, I created an invoice and settled on it.

On the test instance, the invoice is paid.

On my behalf to me, it goes into payment.

Why this difference? As if my instance needed validation.

**Comment by pedrobaeza** [comment] 2019-06-20 12:19
Something is misconfigured in your instance. Ask for help in the forums, or if you have an enterprise contract, submit a ticket.

**Closed by pedrobaeza** 2019-06-20 12:19 UTC
Labels: Need information
