### ISSUE TITLE
Uncaught TypeError: Cannot read property 'model' of undefined while adding menu item

### ISSUE THREAD

**Issue by simppa69** [odoo/odoo#22591] opened 2018-01-29 07:28 UTC
Impacted versions: 11.0 (latest 29.1)

Steps to reproduce: 

Trying to apply this https://www.odoo.com/forum/help-1/question/allow-employees-to-see-their-own-attendances-128722 but got error: Uncaught TypeError: Cannot read property 'model' of undefined

**This is happening only if modifying the groups trough submenus. If search the submenus as main menu item for edit, error does not appear. **

Please see the attachment also.

Current behavior:

Error:
Uncaught TypeError: Cannot read property 'model' of undefined

http://odootesti.noisehouse.fi:8069/web/content/624-461185e/web.assets_backend.js:1204
Traceback:
TypeError: Cannot read property 'model' of undefined
    at Class._generateChanges (http://odootesti.noisehouse.fi:8069/web/content/624-461185e/web.assets_backend.js:1204:474)
    at Class._generateX2ManyCommands (http://odootesti.noisehouse.fi:8069/web/content/624-461185e/web.assets_backend.js:1210:1449)
    at Class._generateOnChangeData (http://odootesti.noisehouse.fi:8069/web/content/624-461185e/web.assets_backend.js:1205:136)
    at Class._performOnChange (http://odootesti.noisehouse.fi:8069/web/content/624-461185e/web.assets_backend.js:1244:67)
    at http://odootesti.noisehouse.fi:8069/web/content/624-461185e/web.assets_backend.js:1148:61
    at http://odootesti.noisehouse.fi:8069/web/content/623-86bd832/web.assets_common.js:802:681
    at fire (http://odootesti.noisehouse.fi:8069/web/content/623-86bd832/web.assets_common.js:796:299)
    at Object.add [as done] (http://odootesti.noisehouse.fi:8069/web/content/623-86bd832/web.assets_common.js:797:467)
    at Array.<anonymous> (http://odootesti.noisehouse.fi:8069/web/content/623-86bd832/web.assets_common.js:802:649)
    at Function.each (http://odootesti.noisehouse.fi:8069/web/content/623-86bd832/web.assets_common.js:625:767)

Expected behavior:

No error.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/23297584/35498392-af819916-04d6-11e8-863e-bfebe398ba74.png)

**Comment by sswapnesh** [comment] 2018-01-29 08:07
Duplicate of #22468

**Comment by Yenthe666** [comment] 2018-01-29 08:48
Yeah indeed - closing as it is a duplicate.

**Closed by Yenthe666** 2018-01-29 08:48 UTC
