### ISSUE TITLE
[12.0] Better name for __system__ user?

### ISSUE THREAD

**Issue by yelizariev** [odoo/odoo#26719] opened 2018-08-31 13:20 UTC
Impacted versions: 12.0 (master)

Steps to reproduce:

Make an order in Ecommerce as public user 

Current behavior:

Notification is sent with **From**: System <root@....>

![system](https://user-images.githubusercontent.com/186131/44914482-d5717300-ad49-11e8-9416-9988bb972705.png)

Expected behavior:

Can it be something more interesting? 

* Robot?
* Administrator?

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment] 2018-08-31 13:32
Related to https://github.com/odoo/odoo/pull/25939
@rco-odoo can you please check if this was intended behaviour from your side or if we need a change here? Might be confusing.

**Comment by Elkasitu** [comment] 2018-09-01 09:53
It was intended, if you have some good arguments as to why you think this is not a good idea, we can reconsider.

In any case, you can change its name to whatever you want from the settings.

**Comment by yelizariev** [comment] 2018-09-01 12:14
For me, it's not a good idea, because message text doesn't look like technical notification. It sounds like it's from human (*Dear Ivan...*, *Do not hesitate to contact us...*), but it has "System" as an author.

**Comment by mart-e** [comment] 2018-09-06 07:52
The name "system" is ok IMHO as it should be clear for the user that the message did not came from a real user but was automated. As it is a real user (just deactivated), it can be renamed to be better understood (e.g. "My Company System").
I close this as it is intended but feel free to suggest better names if you have something better.
Another possibility is also to change the email message (keeping in mind this message can also be sent by a "real" user from a sale order).

**Closed by mart-e** 2018-09-06 07:52 UTC
