### ISSUE TITLE
user_id redeclared in account_move.py

### ISSUE THREAD

**Issue by makwin** [odoo/odoo#46051] opened 2020-02-24 10:03 UTC
Impacted versions: 13.0

Steps to reproduce: code weirdness in account_move.py

Current behavior: user_id field is declared twice, with nearly same information apart from help declaration property

Expected behavior: use only one declaration, most probably the second one

Video/Screenshot link (optional):
line code 121 and line code 187

**Comment by pedrobaeza** [comment] 2020-02-24 10:08
As said in OCB, this shouldn't be changed in stable version (13.0 is, master is not), and this is not a bug, but an improvement (as this works although duplicated). Is this still happening in master branch?

**Comment by sswapnesh** [comment] 2020-02-24 15:49
Handled in master at https://github.com/odoo/odoo/commit/3cf3c2dbd40a8725284608f7b9cdffd65b0c7cc0#diff-dd671a54296b170ea1393dca1a5f7798

**Comment by pedrobaeza** [comment] 2020-02-24 15:54
Then we can close it.

**Closed by pedrobaeza** 2020-02-24 15:54 UTC
