### ISSUE TITLE
[13.0] New field in account.move.line cannot be saved when create

### ISSUE THREAD

**Issue by CakJuice** [odoo/odoo#40915] opened 2019-11-27 04:11 UTC
Impacted versions: 13

Steps to reproduce:
- Install new odoo 13
- create new module that depends on 'account'
- create new model inherit from 'account.move.line', like code below
```
from odoo import models, fields


class AccountMoveLine(models.Model):
    _inherit = 'account.move.line'

    int_field = fields.Integer(string="Int Field")
    float_field = fields.Float(string="Float Field")
    char_field = fields.Char(string="Char Field")
```
- inherit view account.move and add all new fields

Current behavior: all new fields cannot be saved when creating a new account.move.line. These fields can only be saved when we edit the account.move.line

Expected behavior: all new fields should must be able to saved either in create or edit mode

Video/Screenshot link (optional):
https://drive.google.com/file/d/1lBQ_wZMy9FCJliaNtSg6ZMYh7GskDcMA/view?usp=sharing

**Comment by william-andre** [comment] 2020-01-15 11:47
Did you add the new fields in both `line_ids` and `invoice_line_ids` in the view? This is needed because of the synchronization between both fields. You need to at least add them as invisible.

**Comment by CakJuice** [comment] 2020-01-16 07:04
@william-andre great, it works now.
So is this a feature, not bug?

**Comment by william-andre** [comment] 2020-01-16 08:30
I wouldn't say it is a feature or a bug. It is an implementation constraint due to the current state of the web framework, and it is a cost we are willing to pay in order to have the relational models we have now on Journal Entries and Invoices.

We know it isn't ideal, but there is nothing we can do at the moment to improve this.

I am closing as the issue is resolved

**Closed by william-andre** 2020-01-16 08:30 UTC
Labels: 13.0, Accounting

**Comment by CakJuice** [comment] 2020-01-16 08:42
@william-andre noted, thank you for your explanation.
