### ISSUE TITLE
Accounting Settings Issue

### ISSUE THREAD

**Issue by goyanipankaj** [odoo/odoo#28954] opened 2018-11-22 13:01 UTC
Impacted versions:
Odoo 12.0

Steps to reproduce:
After installed localization module and go under the menu: (Account > Settings)

Current behavior:
Got error of field is not available in View.

Expected Behavior:

Video/Screenshot link (optional):
Link: Please refer this link.
![issue-account](https://user-images.githubusercontent.com/8874012/48904381-2f369480-ee84-11e8-8b7f-58b7b2ab6b05.png)

**Comment by pedrobaeza** [comment] 2018-11-22 13:29
Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by sswapnesh** [comment] 2018-12-11 15:34
Works well on latest Build.

**Comment by pedrobaeza** [comment] 2018-12-11 15:37
Thanks for confirming. Closing this.

**Closed by pedrobaeza** 2018-12-11 15:37 UTC
Labels: 12.0, Need information
