### ISSUE TITLE
[12.0] Double record inserted

### ISSUE THREAD

**Issue by erkie24** [odoo/odoo#33704] opened 2019-05-28 07:04 UTC
Impacted versions: 11, 12

Steps to reproduce: When creating record on some form, sometimes it will create duplicate record.

Video/Screenshot link (optional):
- https://user-images.githubusercontent.com/16965539/58457549-2be0d600-8151-11e9-8a6e-1905da86749d.jpg
- https://user-images.githubusercontent.com/16965539/58457689-7eba8d80-8151-11e9-909c-fb69051fdff9.jpg

**Comment by Yenthe666** [comment] 2019-05-28 07:15
Hi @erkie24,

Can you reproduce this on an official Odoo instance at runbot.odoo.com? Are  you sure it is not custom development or that you have some scheduled actions causing this?

Regards,
Yenthe

**Comment by erkie24** [comment] 2019-05-28 10:40
It's not always happened, intermittent. so I can't reproduce it, but sometimes it happened.
There's a week when bugs doesn't occur, and then the next day, it create double record again.
I'm sure its not custom development, I have 1 instance odoo version 11 at AWS, and 1 instance odoo version 12 at AWS, and I have 1 instance at local PC. All three instance doesn't have any extra module installed, but they all do creating double record. Not always, but it happened.

Maybe someone here experience the same thing? Or any suggestion that I can try? Thanks.

**Comment by Yenthe666** [comment] 2019-05-28 12:49
Hmm odd, haven't heard this one before. Can you try to reproduce it on an official runbot instance?

**Comment by Yenthe666** [comment] 2019-07-31 14:41
Hi there,

I'm closing this bug report as there has been no more feedback on the last question. We assume that the problem has been solved in the meanwhile. If this is not the case then don't hesitate to respond back (with feedback) and we'll reopen it.

Regards,
Yenthe

**Closed by Yenthe666** 2019-07-31 14:41 UTC
Labels: Need information, Services

**Comment by pramadhana92** [comment] 2019-08-05 06:25
it also happened to me. everytime im saving record from form menu, it will create double record!

at first, i thought it happened because i make mistake in field one2many. but after i comment one2many field, all function, so the file only contain normal field (char). it still create duplicate record!

ive been developing odoo v8 custom module for more than 1 year, and lately try to develop odoo v12 custom module.

is it because ir.act_window? is it because there is difference in Models.model? or api?
i try to search any documentation from official web, still got no clue..

**Comment by pedrobaeza** [comment] 2019-08-05 07:16
Are you double-clicking on the button? You must click only once.

**Comment by pramadhana92** [comment] 2019-08-05 08:14
just click save once, tried it everytime, still double record inserted with same value

**Comment by pedrobaeza** [comment] 2019-08-05 08:28
This is not happening in Odoo itself nor any of my custom developments, so it's something in your custom development. You should ask on forums for more help.

**Comment by aitlamsali** [comment] 2022-11-01 21:50
Hello
This also happening to me on V14, when create SO on One2Many field, sale order is created twice, and when tou delete one of them (= new ) before click save the parent record both are deleted, means they are same record but displayed twice !
Any solution for this please ?
