### ISSUE TITLE
[14.0] problem with image crop

### ISSUE THREAD

**Issue by zahra-np** [odoo/odoo#67511] opened 2021-03-09 09:44 UTC
Impacted versions: 14

Steps to reproduce:

Current behavior: there is not crop image in editor of odoo 14.0

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

![About-us-فروشگاه-سارای](https://user-images.githubusercontent.com/80319930/110451279-4b07e800-80d9-11eb-962e-e16d01655123.png)

**Comment by pedrobaeza** [comment] 2021-03-09 09:46
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)? (recently a warning is put for existing image fields that can't be edited if you don't reupload the image).

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by zahra-np** [comment] 2021-03-09 12:30
https://www.awesomescreenshot.com/video/2998059?key=af3e05b69d6f0054c112958856b9e3d3

In this video, I try to show the image editing options in different snippets. By selecting and canceling their selection, the complete problem can be seen

**Comment by pedrobaeza** [comment] 2021-03-10 07:21
Thanks for the video. That options are not available in image gallery, so closing as missing feature for that snippet.

**Closed by pedrobaeza** 2021-03-10 07:21 UTC
Labels: Need information

**Comment by zahra-np** [comment] 2021-03-10 09:15
This feature was in version 13.0 . Why is it not available in version 14.0?!!!!!!

**Comment by zahra-np** [comment] 2021-03-10 09:16
@pedrobaeza

**Comment by pedrobaeza** [comment] 2021-03-10 09:18
Website has been totally redone in v14, so things don't work the same way. I ping @qsm-odoo to see if they plan to restore such feature in one moment.

**Comment by zahra-np** [comment] 2021-03-10 09:20
Thank you. I am waiting

**Comment by qsm-odoo** [comment] 2021-03-10 10:13
Hello, the feature is there for me on the latest 14.0 runbot. We merged some fixes related to images yesterday, so it may have been fixed just after your reported the bug.

**Comment by pedrobaeza** [comment] 2021-03-10 10:14
Oh, great then. I considered that it was not put instead of being a bug.
