### ISSUE TITLE
Two identical products on WAREHOUSE OUT documents are not processed

### ISSUE THREAD

**Issue by lordt** [odoo/odoo#13649] opened 2016-09-30 13:48 UTC
Impacted versions: **Version 9.0c (Community Edition)**

Steps to reproduce:
- Create quotation with 2 identical positions (product type: _consu_).
- Save quotation
- Confirm sale
- Create invoice
- Validate invoice
- Go to _Inventory > Warehouse Outs_
- Find WO related to created invoice
- Validate
- (In popup with message: _You haven't set processed quantities. If you click apply Odoo will process all quantities to do._) Click apply.

Current behavior:
- You would get message: _The roundings of your Unit of Measures szt. on the move vs. szt. on the product don't allow to do these operations or you are not transferring the picking at once_  (_szt._ is _unit_ in polish)

Expected behavior:
- All quantities should be processed.

**Comment by pedrobaeza** [comment] 2018-04-29 00:41
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-04-29 00:41 UTC
Labels: 9.0, Logistics
