### ISSUE TITLE
[12.0] website: duplicate header tag when using Affix top menu

### ISSUE THREAD

**Issue by bahram-css** [odoo/odoo#36101] opened 2019-08-27 07:45 UTC
Impacted versions: 12.0

Steps to reproduce:

Current behavior: When I enable Affix top menu from Customize menu, Header tag is duplicated in code and this leads to a problem for my javascript code.
Is there a specific reason that a better method is not used to create a fixed menu? because It's not an optimized and correct method to create this feature.

Expected behavior: Just add a 'fixed' class to Header not duplicating  Header tag.

Video/Screenshot link (optional):
![Screenshot-from-2019-08-27-11-56-01](https://user-images.githubusercontent.com/51145639/63750796-64fd2380-c8c3-11e9-93ef-53ce0782d012.jpg)

**Comment by pedrobaeza** [comment] 2019-08-27 14:17
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by bahram-css** [comment] 2019-08-28 06:29
https://youtu.be/b7BE6slFv_Y

**Comment by bahram-css** [comment] 2019-08-28 06:33
Header tag is duplicated.
It's not an optimized and correct method to create FIX menu

**Comment by pedrobaeza** [comment] 2019-08-28 07:27
OK, issue understood and renamed with proper title. Please take note for future issues.

@JKE-be something for your team.

**Comment by JKE-be** [comment] 2019-08-28 08:50
probably by design, but let's @qsm-odoo a righ of reply ;)

**Comment by qsm-odoo** [comment] 2019-08-28 09:19
It is a designer choice, having a "fixed" menu would not lead to the same result. Our version of the affix menu first follows the page scroll then reappear when reaching a specific scroll point.

For future version, this mechanism will also allow us to have a complex and tall menu on top while having a simpler version once it is fixed after scrolling.

If you want a simple fixed menu, you can disable the option and use the scss editor to achieve your version (in 13.0, we provide an easy access to an empty custom scss file to customize).

**Comment by pedrobaeza** [comment] 2019-08-28 09:21
@qsm-odoo the problem seems to be that having two `<header>` tags in the same node is not something correct and can lead to unexpected behavior depending on the browser implementation.

**Comment by qsm-odoo** [comment] 2019-08-28 09:37
Mmh, maybe we can have the same result with an implementation using only one header element... but that would really not improve much (the loaded page only contains one header, that is javascript which is duplicating it) ;)

I'll tag as wishlist and do that for a future master update, it is true that this could improve code we have in others apps like the ecommerce ;)

**Comment by bahram-css** [comment] 2019-08-29 07:41
Duplicating header leads to duplicating its inside IDs too. that's why the problem is created.

**Comment by qsm-odoo** [comment] 2020-04-01 14:57
Hello, we merged a solution to this problem in master alongside other header effects and improvements https://github.com/odoo/odoo/commit/3defe35a0e4e2097115633797df6898ac2724c66 :tada:

**Closed by qsm-odoo** 2020-04-01 14:57 UTC
Labels: 12.0, Website, Wishlist
