### ISSUE TITLE
Vendor bills allow to create and pay a bill to incorrect vendor.

### ISSUE THREAD

**Issue by DITIntl** [odoo/odoo#24688] opened 2018-05-12 14:07 UTC
Impacted versions:
11, 12
Steps to reproduce:
1. create a purchase order [po001] for [vendor 1], confirm--> receiving;
2. create a new vendor bill; 
     2.1. select [vendor 1], then select [po001];
     2.2. select [vendor 2],
     2.3. confirm;
      2.4. pay the bill
      2.5. done. the payment made to [vendor 2], but it is supposed need to paid to [vendor 1];
Current behavior:
the money paid to [vendor 2];
Expected behavior:
the money need to pay to [vendor 1];

Video/Screenshot link (optional):

https://youtu.be/dsiBiO5LPv0
https://youtu.be/DEwmVIQjhlc

# #

**Comment by sswapnesh** [comment] 2018-06-08 17:54
Hello @DITIntl 
This is the Intended Behaviour as you have Vendor to `[vendor 2]` manually.
Cc: @pedrobaeza

**Comment by pedrobaeza** [comment] 2018-06-08 19:18
Indeed that's the intended behavior, as the only valid financial document is the invoice, not the purchase order, so if you change the vendor after importing purchase order lines, the invoice will be charged to that new supplier., and should be payed to it. 

Closing as no issue, but intended behavior.

**Closed by pedrobaeza** 2018-06-08 19:18 UTC
Labels: 11.0, Accounting
