### ISSUE TITLE
[11.0] Translation for found) in website_sale not working

### ISSUE THREAD

**Issue by ap-wtioit** [odoo/odoo#34718] opened 2019-07-10 07:10 UTC
Impacted versions:
11.0

Steps to reproduce:
* Enable german translation for website
* Enable "Show # found" on /shop website url
* Switch to german 
* search for "i"

Current behavior:
Number of results is not translated. Search button says (105 found)

Expected behavior:
Number of results should be translated. Search button should say (105 gefunden)

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/38032588/60948003-3ff02980-a2f2-11e9-857f-053cca750328.png)

Runbot link: http://559413-11-0-5038f7.runbot27.odoo.com/de_DE/shop?&search=i
Transifex link: [https://www.transifex.com/odoo/odoo-11/translate/#de/website_sale/119306789?q=text%3Afound)](https://www.transifex.com/odoo/odoo-11/translate/#de/website_sale/119306789?q=text%3Afound\))

**Comment by pedrobaeza** [comment] 2019-07-10 07:13
@mart-e can you please check?

**Comment by mart-e** [comment] 2019-07-10 08:11
Hmm I have an issue for this one. The external id has a space

**Comment by ap-wtioit** [comment] 2019-07-10 09:23
Could we manually add a record into the db/pot/po file?
```
<class 'tuple'>: ('model', 'ir.ui.view,arch_db', 'website_sale.search', 'found)', '', '')
```
like this:
```
#. module: website_sale
#: model:ir.ui.view,arch_db:website_sale.search
msgid "found)"
msgstr ""
```

**Comment by mart-e** [comment] 2019-07-11 14:45
No the issue is that the external id of the view is not correctly extracted (see the `.split(' ')`, introduced at aea1b134121859eb2d04b435d471142583b6f64a).

https://github.com/odoo/odoo/blob/8f9e1e40a32748e576084320b4f9a4c1165b7a10/odoo/tools/translate.py#L540

In master we have changed the parser to polib which will no longer accept these kind of bad xmlid.

**Comment by mart-e** [comment] 2019-12-30 14:53
Closing as the issue is solved in upper version but I am afraid we do not have a solution for stable.

**Closed by mart-e** 2019-12-30 14:53 UTC
Labels: 11.0, Internationalization
