### ISSUE TITLE
[16.0] Manufacturing date_planned_start incorrect using

### ISSUE THREAD

**Issue by NadozirnySvyatoslav** [odoo/odoo#125158] opened 2023-06-15 09:09 UTC
Impacted versions:
16.0

Steps to reproduce:
1. Create MO, set date_planned_start with few days ago (NOW - 3 days)
2. Confirm MO
3. Fill workorders
4. Close MO

Current behavior:
date_planned_start set with NOW

Expected behavior:
date_planned_start not changed

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by manishkumarbohra** [comment] 2023-07-08 10:26
Hello  @NadozirnySvyatoslav , 

Unable to reproduce the same issue. 

Kindly, pull the updated code and after check.

**Comment by vava-odoo** [comment] 2023-08-02 14:50
Closing as unable to reproduce on runbot

**Closed by vava-odoo** 2023-08-02 14:50 UTC
Labels: Logistics, 16.0
