### ISSUE TITLE
[11.0] Missing dependencies in Web editor

### ISSUE THREAD

**Issue by SalahAdDin** [odoo/odoo#25905] opened 2018-07-20 15:00 UTC
Impacted versions:
`Odoo 11.0-20180716 (Community Edition)`

Steps to reproduce:
Just open `Odoo`.

Current behavior:
Two missing dependencies avoid that the web editor module can be loaded.

Expected behavior:
Web editor module loading normally.

Video/Screenshot link (optional):
![problemaconodoo](https://user-images.githubusercontent.com/5034215/43009567-b34cb812-8c46-11e8-82cc-5f367c0d247c.png)

**Comment by pedrobaeza** [comment] 2018-07-21 14:43
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-07-21 14:43 UTC
