### ISSUE TITLE
Google Spreadsheet Auth is broken

### ISSUE THREAD

**Issue by spadae22** [odoo/odoo#6028] opened 2015-03-28 22:17 UTC
Steps to reproduce:
Create view in reporting,
Click Google Spreadsheet
Run script: connection error!

If I manually add the paramenters on the script: 
function authenticate(){
  Logger.log('Authentication requested!');
  var url = "http://openerp.xxxxxx.xxx:8069";
  var dbname = ("Chris_3_4");
  var username = ("er@eugeconsulting.com");
  var password = ("password2222"); 
  if (!url || !dbname || !username || !password){
    throw "At least one connection detail is not set. You can set them Odoo > Settings in the menu bar";
  }

I can connect and data is shown

**Comment by nolanzandi** [comment] 2015-07-22 06:57
The Google Spreadsheet script that Odoo uses to integrate data between Odoo and Google sheets includes deprecated code and is out of date. Replace all the Utilities.jsonStringify with JSON.stringify and all the Utilities.jsonParse with JSON.parse and the script should work more or less. I still get an error in my Odoo log that says AttributeError: 'NoneType' object has no attribute 'read_group'. I am still working on a debug for that part.

**Comment by nolanzandi** [comment] 2015-07-22 09:40
The AttributeError is caused by the oe_read_group function. I haven't fully dubugged it but commenting it out allows the rest of the script to run without throwing errors in Odoo.

**Comment by spadae22** [comment] 2016-06-03 00:53
@nolanzandi THANKS! Here is the response for the current code on git: 
Denis Ledoux (dle) - 2 months ago 
Dear E.R. Spada II, 

I just tried to reproduce your use case using the latest build 8.0 on runbot, but coudln't.

See the below video for illustration:
https://drive.google.com/file/d/0B5GVjjwUC-ygcFVSb1N6LXB4dzg/view?usp=sharing

Please check your server log to make sure this error "Cannot read property "uid" from undefined."isn't due to a customization or a community module by your side.

Regards,
This was enterprise support.

**Comment by NeoPolus** [comment] 2017-02-03 07:21
I tested the google_spreadshet module on the 10.0 version this week, and found that we are still using the same outdated and bugged template :( 

Create a copy and take a look at the script code of https://docs.google.com/spreadsheet/ccc?key=1KUlSSzZMzkEEzyroyZ2NerRt1RVCspkG9VQIh2V6dnM

- Uses outdated methods like @nolanzandi comments (JSON ones).
- Stores the user and password in plain text as ScriptProperties attached to the document, not UserProperties, so if we share the documents generated with this template with anybody we are sharing our password too... :-1: 
- getScriptProperty function is sloooooow: it always makes the script sleep, up to 2.95 seconds per call, even when it would succeed. It should only sleep if the first try fails (if the objective is to wait until the properties and parameters are loaded / given by the user).

Also, it relies on using the G60 cell of the spreadsheet for passing the Odoo connection parameters (oe_settings) including the plain text password of the current Odoo user... this seems dangerous. The google_spreadsheet module should give the option of passing the password (at your risk) or not (just the url, database and user parameters).

**Comment by Yenthe666** [comment] 2017-12-12 15:42
@JKE-be you might want to double check this one as @NeoPolus mentions that this happens in 10.0 too?

**Comment by Yenthe666** [comment] 2017-12-14 08:25
As this bug report is for V8 I'm closing it though, as it is no longer supported and the bug report is very old.
@NeoPolus feel free to create a new bug report with details about V10. I'll make sure it gets looked at then.

**Closed by Yenthe666** 2017-12-14 08:25 UTC
