### ISSUE TITLE
Error loading image in html field

### ISSUE THREAD

**Issue by ysantiago** [odoo/odoo#20862] opened 2017-11-10 23:14 UTC
Impacted versions:

- 11.0

Steps to reproduce:

Try to load an image in html field

Current behavior:

An error is thrown 
```Uncaught TypeError: Cannot read property 'is_document' of undefined```

Expected behavior:

The image must be loaded correctly.

Video/Screenshot link (optional):

<img width="980" alt="skitch 260" src="https://user-images.githubusercontent.com/11341058/32675624-da6e7dd4-c62d-11e7-83fd-66046f1cf0c1.png">

Click [here](https://www.youtube.com/watch?v=yI7ONWhiayQ&feature=youtu.be) to see the video

**Comment by Yenthe666** [comment] 2017-11-11 14:42
Hi @ysantiago,

Thank you for your bug report (and the video!)
I can indeed confirm that this is a bug in the latest Odoo 11:
![image](https://user-images.githubusercontent.com/6352350/32690422-c75afc58-c6f6-11e7-94e0-98d9cb15f766.png)
@ged-odoo this is another JS related one - could you have a look when you have time please?

Regards,
Yenthe

**Comment by PauliusP17** [comment] 2017-11-20 17:33
I can confirm that this bug also appears in 9.0 CE and 10.0 CE versions, tested on runbot. I also occasionally get a "Cannot read property "className" of undefined" when clicking on the already uploaded images in the wizard.

I noticed this error pops up when clicking "Save" at the bottom of the wizard, but not every time. I assume when you upload the image the wizards save method is automatically called. 

A temporary workaround for this is to double click the uploaded image in the wizard after closing the error (the image is actually uploaded despite the error) which will insert it into the HTML field. Sometimes I have to this a couple of times before it actually works.

**Comment by kebeclibre** [comment] 2017-12-04 15:20
I was not able to reproduce on runbot from 10.0 to 11.0. Apparently the behavior has changed in the meantime: the mediaDialog closes when the image is loaded.

I might be missing something though.

**Comment by Yenthe666** [comment] 2018-01-05 08:47
Hey all,

The `mediaDialog` has indeed been changed in the meanwhile. The dialog now closes when the image is uploaded and the JS error no longer goes off.
Please update your Odoo codebase and it'll be fixed.

Regards,
Yenthe

**Closed by Yenthe666** 2018-01-05 08:47 UTC
Labels: 9.0, Framework
