### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tooltip' of undefined

### ISSUE THREAD

**Issue by manabendra** [odoo/odoo#33315] opened 2019-05-12 18:15 UTC
Hi,

I am using odoo 12. When I am trying to edit the view. I am getting this error

Error:
Uncaught TypeError: Cannot read property 'tooltip' of undefined

http://localhost:8069/web/content/635-48ed65a/web.assets_backend.js:1559
Traceback:
TypeError: Cannot read property 'tooltip' of undefined
at Class.addFieldTooltip (http://localhost:8069/web/content/635-48ed65a/web.assets_backend.js:1559:735)
at http://localhost:8069/web/content/635-48ed65a/web.assets_backend.js:1646:343
at Function..each._.forEach (http://localhost:8069/web/content/532-8e853a2/web.assets_common.js:12:558)
at Class._updateView (http://localhost:8069/web/content/635-48ed65a/web.assets_backend.js:1646:3)
at http://localhost:8069/web/content/635-48ed65a/web.assets_backend.js:1644:1373
at http://localhost:8069/web/content/532-8e853a2/web.assets_common.js:802:681
at fire (http://localhost:8069/web/content/532-8e853a2/web.assets_common.js:796:299)
at Object.fireWith [as resolveWith] (http://localhost:8069/web/content/532-8e853a2/web.assets_common.js:801:198)
at deferred. (http://localhost:8069/web/content/532-8e853a2/web.assets_common.js:803:56)
at fire (http://localhost:8069/web/content/532-8e853a2/web.assets_common.js:796:299)

**Comment by pedrobaeza** [comment] 2019-05-12 20:16
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by hello76yu** [comment] 2019-06-12 03:11
I got exactly same problem on odoo 12.
In most case , there is no any response after i clicked the view (try to open it).
I can see the post message from log , but nothing else (warring or error)
"POST /web/dataset/call_kw/ir.ui.view/read HTTP/1.0" 200 - 16 0.005 0.011

Sometimes i got same error as manabendra mentioned above.
The view editing was working before,  i have no idea how to reproduce these.

Restart odoo doesn't fix the problem.

**Comment by pedrobaeza** [comment] 2019-06-12 07:08
Yeah, but not being able to reproduce it in runbot and the steps to do it invalidates any possible investigation nor solution.

**Comment by Yenthe666** [comment] 2019-07-31 14:40
Hi there,

I'm closing this bug report as there has been no more feedback on the last question. We assume that the problem has been solved in the meanwhile. If this is not the case then don't hesitate to respond back (with feedback) and we'll reopen it.

Regards,
Yenthe

**Closed by Yenthe666** 2019-07-31 14:40 UTC
Labels: Need information
