### ISSUE TITLE
cannot set filter in "Add: Pickings" view, module stock_picking_batch

### ISSUE THREAD

**Issue by pkr123dw** [odoo/odoo#37281] opened 2019-09-23 12:48 UTC
Impacted versions:

Steps to reproduce:
Navigate to "Inventory" -> "Operations" -> "Batch Pickings" -> "Add a line" -> "Filters".
When the pickings list is short the window height is too low to reach the "Add Custom Filter" filter

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2019-09-23 12:50
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by pkr123dw** [comment] 2019-09-23 12:56
![cannot_set_filter](https://user-images.githubusercontent.com/49066434/65427331-5d716180-de12-11e9-90db-cbc1902d571c.png)

**Comment by pedrobaeza** [comment] 2019-09-23 12:58
OK, tagged

**Comment by C3POdoo** [comment] 2023-03-30 11:47
Dear @pkr123dw,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._

**Closed by C3POdoo** 2023-03-30 11:47 UTC
Labels: Framework, 12.0
