### ISSUE TITLE
[14.0] You are not allowed to access 'Action Window' (ir.actions.act_window) records.

### ISSUE THREAD

**Issue by dreispt** [odoo/odoo#74110] opened 2021-07-22 11:23 UTC
I'm sorry, I was not able to reproduce this in Runbot.
I still feel worth reporting, since I found on two different customers.

Clicking on a main screen app raises the error:
```
Access Error

You are not allowed to access 'Action Window' (ir.actions.act_window) records.

This operation is allowed for the following groups:
	- Administration/Settings

Contact your administrator to request access if necessary.
```

Checking ACLs we can see:

![image](https://user-images.githubusercontent.com/1246629/126631236-43f429f4-94ac-4947-8bb5-6462c1b5b185.png)

What is going on here?

**Comment by pedrobaeza** [comment] 2021-07-22 11:27
Daniel, I'm afraid this has to be closed, as it seems clearly by something done incorrect on that instance (probably a custom module), or we need the steps to reproduce the problem in runbot for checking. Please try to filter and isolate the culprit.

You can also ask for help on forums or mailing lists.

Closing due to this, but it can be reopened if more evidences are given.

**Closed by pedrobaeza** 2021-07-22 11:27 UTC

**Comment by dreispt** [comment] 2021-09-24 09:33
For future reference, this is the workaround used:
![image](https://user-images.githubusercontent.com/1246629/134652888-8a02b9d7-75b7-44ab-b2c9-e56ecd5a6635.png)
