### ISSUE TITLE
App Fleet Reports / Costs SyntaxError: Unexpected token T in JSON at position 0  Odoo Community v14 Ubuntu Server

### ISSUE THREAD

**Issue by marcosmonauta** [odoo/odoo#64512] opened 2021-01-14 07:30 UTC
Impacted versions: V14 Community

Steps to reproduce: Install Fleet, select Reports and click on costs

Current behavior:   SyntaxError: Unexpected token T in JSON at position 0

Expected behavior:

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/75961027/104557996-bec0d380-5607-11eb-94a4-340a2fdc0117.png)

I installed Community v14 and the app Fleet. When clicking on reports/costs I get his error

Error:

Traceback:
SyntaxError: Unexpected token T in JSON at position 0
    at JSON.parse (<anonymous>)
    at Class.init (https://donau.com.mx/web/content/9039-1316d81/web.assets_backend.js:2400:235)
    at Class.prototype.<computed> [as init] (https://donau.com.mx/web/content/7977-e9c59c3/web.assets_common.js:4614:488)
    at new Class (https://donau.com.mx/web/content/7977-e9c59c3/web.assets_common.js:4615:65)
    at Class._createViewController (https://donau.com.mx/web/content/9039-1316d81/web.assets_backend.js:448:658)
    at https://donau.com.mx/web/content/9039-1316d81/web.assets_backend.js:453:169

I installed python, checking all dependencies and so on , but I cannot do it work. This happens to me in 2 differente servers

Anybody that could please help me?

**Comment by pedrobaeza** [comment] 2021-01-14 07:32
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by marcosmonauta** [comment] 2021-01-14 14:57
It runs fine in the runbot. Any suggestion?

**Comment by pedrobaeza** [comment] 2021-01-14 15:01
The one already specified: update source code and upgrade your modules.

Closing as no Odoo problem, but specific deployment one.

**Closed by pedrobaeza** 2021-01-14 15:01 UTC
Labels: Need information

**Comment by marcosmonauta** [comment] 2021-01-14 15:09
Thank you Pedro.
