### ISSUE TITLE
[14.0] [13.0] Sales Order: Cart Recovery Email: access_token=False

### ISSUE THREAD

**Issue by hajajroshan** [odoo/odoo#73519] opened 2021-07-09 17:59 UTC
Impacted versions:
14.0, 13.0

Steps to reproduce:
Settings -> Technical -> Email -> Templates -> Sales Order: Cart Recovery Email- 
![Peek 2021-07-09 23-25](https://user-images.githubusercontent.com/62367855/125118193-f74fee80-e10c-11eb-87f4-5112c1abfedf.gif)

Current behavior:
![image](https://user-images.githubusercontent.com/62367855/125118397-4564f200-e10d-11eb-8cf8-d52a00c0a6af.png)
access token not generate. can't open the url

**Comment by pedrobaeza** [comment] 2021-07-09 18:00
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by hajajroshan** [comment] 2021-07-09 18:17
Hi @pedrobaeza, Above screenshots are from runbot version 14.0. logged in as admin. Similar problem I have in a production db also. Then I tried it on runbot with 13 and 14.

**Comment by pedrobaeza** [comment] 2021-07-09 18:19
OK, I see, but you can't do that steps to get something reproducible, as the token is populated from the calling method, and the preview is not going to do it.

Closing as no valid issue.

**Closed by pedrobaeza** 2021-07-09 18:19 UTC
Labels: Need information
