### ISSUE TITLE
[8.0] "res.partner" has some fields with no string 

### ISSUE THREAD

**Issue by JonathanNEMRY** [odoo/odoo#3563] opened 2014-11-11 14:56 UTC
Seems that `partner` model has some fields with no `string` and then those appear as "unknown" into the advanced search.

Here their technical name:
- `related_company_partner_id`
- `unreconciled_aml_ids`
- `single_related_company_id`
- `related_related_company_id`

Thanks in advance for the fix!

-jne

**Comment by Yenthe666** [comment] 2017-10-27 05:48
Hi @JonathanNEMRY,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: It seems to be fixed in newer versions.

Regards,
Yenthe

**Closed by Yenthe666** 2017-10-27 05:48 UTC
