### ISSUE TITLE
[14] account - Sequence constraints error with date and invoice number

### ISSUE THREAD

**Issue by martinsalcedoid** [odoo/odoo#61687] opened 2020-11-12 17:19 UTC
Impacted versions:
14.0
Steps to reproduce:
Create an Invoice an set the fields
number : 045-001-0000001
date: 2020-11-12 (november 12)

Current behavior:
Get the following error

**The date (2020-11-12) doesn't match the sequence number (045-001-0000001).
You might want to remove the sequence before proceeding with the change of the date.**

Why should have relation the number with the date?

Expected behavior:
No errors, create the desired number not related with the date. 
Have the configuration to do not control that. 

Video/Screenshot link (optional):

https://drive.google.com/file/d/1z1q_y4WxK7rI-G4CX6Phxw_EU0NbwhcX/view?usp=sharing

**Comment by pedrobaeza** [comment] 2020-11-12 19:14
The freedom for changing the invoice number is constrained to this for only rectifying certain mistakes, so that's the intended behavior and as such, this is not a bug.

If you want more freedom, then you will need to modify Odoo via third-party modules.

Closing due to this.

**Closed by pedrobaeza** 2020-11-12 19:14 UTC
