### ISSUE TITLE
System doesn't increase quantities of components after unbuild process. 

### ISSUE THREAD

**Issue by mroljic-modoolar** [odoo/odoo#26354] opened 2018-08-13 15:08 UTC
Impacted versions: master

Steps to reproduce: 

1. During unbuild process, system decreases number of the manufacturer project but doesn't increase numbers of components.

Current behavior: Quantities of components remain equal.

Expected behavior: Quantities of components have to be increased. 

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2018-08-13 15:09
Have you tried on latest runbot (https://runbot.odoo.com - admin/admin)? I video would help also a lot.

**Comment by mroljic-modoolar** [comment] 2018-08-15 10:59
Hello Pedro,

thank you for your prompt answer.
I've tried it on the latest runbot version, master branch. 
As well, even you have one manufacture with 5 units, you can perform unbuild as much as you want not just ones, even when you choose manufacture order / number.

Here is the video:
[unbuild bug.zip](https://github.com/odoo/odoo/files/2290028/unbuild.bug.zip)


Kind Regards,
Maja

**Comment by sle-odoo** [comment] 2020-01-08 09:29
I'm not able to reproduce this issue, it is most probably now fixed.
Feel free to comment with all the necessary information to reproduce the issue if you still encounter it.

Thanks

**Closed by sle-odoo** 2020-01-08 09:29 UTC
Labels: Logistics
