### ISSUE TITLE
Live Chat: Unhandled Promise rejection: Promise.resolve(...).then(...).guardedCatch is not a function

### ISSUE THREAD

**Issue by tech348712013870132** [odoo/odoo#44058] opened 2020-01-27 23:14 UTC
Impacted versions:
13.0.20200110-debian-10-r2

Steps to reproduce:
Install live chat and add live chat widget within an external website

Current behavior:
The live chat does not appear visually in any way. Only a long console error gets triggered:

```
Unhandled Promise rejection: Promise.resolve(...).then(...).guardedCatch is not a function ; Zone: <root> ; Task: null ; Value: TypeError: "Promise.resolve(...).then(...).guardedCatch is not a function"
    def external_lib.js:2176
    ZoneAwarePromise zone.js:931
    processJob external_lib.js:2175
    processJobs external_lib.js:2182
    define external_lib.js:2163
    <anonymous> 2:5
 processJob/def<@https://odoo.domain.com/im_livechat/external_lib.js:2176:130
ZoneAwarePromise@https://domain.com/polyfills.js:10413:29
processJob@https://odoo.domain.com/im_livechat/external_lib.js:2175:243
odoo.processJobs@https://odoo.domain.com/im_livechat/external_lib.js:2182:11
odoo.define@https://odoo.domain.com/im_livechat/external_lib.js:2163:161
@https://odoo.domain.com/im_livechat/loader/2:5:26
zone.js:703
    onUnhandledError zone.js:703
    handleUnhandledRejection zone.js:730
    _loop_1 zone.js:720
    microtaskDrainDone zone.js:724
    drainMicroTaskQueue zone.js:608
```

Expected behavior:

No errors in the browser console log and visible and fully working live chat.

**Comment by pedrobaeza** [comment] 2020-01-27 23:27
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Yenthe666** [comment] 2020-03-08 19:27
I'm closing this bug report as there has been no response/feedback to the questions asked by @pedrobaeza

**Closed by Yenthe666** 2020-03-08 19:27 UTC
Labels: Need information
