### ISSUE TITLE
Etherpad integration: cannot specify Note title, after saving pad content is not shown in Notes or in Project

### ISSUE THREAD

**Issue by mbartosch** [odoo/odoo#28329] opened 2018-11-01 09:58 UTC
Impacted versions: Odoo Enterprise version 11
Etherpad: tested on 1.7.0 (latest stable release) and current master head 

Steps to reproduce:
- set up Etherpad, verify it works out of Odoo
- configure Etherpad in Odoo settings
Reproduce problem with the "Notes" app:
- create a Note. Etherpad loads and shows the edit window. Editing works fine, it is also possible to collaborate with other users which have been invited (minor nitpicking: Usernames are not shown/unknown in Etherpad)

Current behavior:
In Notes App:
- it is not possible to assign a title to the Note, after saving the Note is displayed as a nameless empty box in the Notes overview, making this feature useless for organizing a number of notes
- outside the Editing mode (i. e. after saving) the Etherpad text content is not shown, making this also unusable for quickly referencing the content without editing it

In Project/Task:
- Etherpad text is not shown in "view" mode, only in Edit mode the text is shown (see Notes App comment)

Expected behavior:
- in Notes App it should be possible to set a name for the note.
- show the text of the Etherpad as static text if the Etherpad is not active

Video/Screenshot link (optional):
n/a

**Comment by pedrobaeza** [comment] 2018-11-01 10:30
Duplicate of #26277

@nhomar @gustavovalverde did you receive any answer from OPW team?

**Comment by Yenthe666** [comment] 2019-02-11 13:21
I believe this one can be closed as the related ticket and OPW have been closed off?

**Comment by C3POdoo** [comment] 2019-04-11 14:11
Dear @mbartosch,

_This is an automated message._
This issue is linked to the Odoo support ticket opw-1873625 that has been closed.
We hope you got an answer to your issue.

If you believe the problem is not solved yet and would like to keep this issue open, please let us know to reopen it.

**Closed by C3POdoo** 2019-04-11 14:11 UTC
Labels: 11.0, OE, Services

**Comment by bbekir** [comment] 2020-06-30 12:56
I have the same issue with odoo 13. Everythings working fine but there is no field something like title or note name.
