### ISSUE TITLE
Question : How can I duplicate the searchbar and make it searching attributes?

### ISSUE THREAD

**Issue by diezcode** [odoo/odoo#12392] opened 2016-06-13 12:02 UTC
How can I duplicate this search view in odoo8 ?
http://i.imgur.com/49iKseW.png

I need it a second time this searchbar, and it should search the attributes of products, with the AND Operator and not or.

How can I do that, I pay for it .

**Comment by Yenthe666** [comment] 2016-06-13 12:07
Hi @diezcode,

Github issues are only for issues regarding the default code of Odoo. This is not the place for custom development or questions.
I'd suggest you to create a question on the official Odoo help forums, where I'm sure somebody can help you! (see help.odoo.com).
Closing this issue since it is not a bug.

Regards,
Yenthe

**Closed by Yenthe666** 2016-06-13 12:07 UTC
Labels: question
