### ISSUE TITLE
500 Internal Server error

### ISSUE THREAD

**Issue by didiereduardo** [odoo/odoo#69800] opened 2021-04-24 01:38 UTC
Impacted versions: 12

'NoneType' object has no attribute '_fields'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 346, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_310_10976
  File "<template>", line 2, in body_call_content_10975
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 359, in _get_field
    field = record._fields[field_name]
AttributeError: 'NoneType' object has no attribute '_fields'

Error to render compiling AST
AttributeError: 'NoneType' object has no attribute '_fields'
Template: 310
Path: /templates/t/t/div/div[2]/div[1]/div[2]/div/div/div[1]/h2[2]
Node: <h2 class="mb4 o_blog_post_title" style="box-sizing: border-box; font-family: inherit; font-weight: 500; line-height: 1.1; color: inherit; margin-top: 20px; margin-bottom: 4px !important; font-size: 24px;" t-field="blog_post.name"/>

**Comment by pedrobaeza** [comment] 2021-04-24 08:10
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Closed** 2023-06-14 16:10 UTC
Labels: Need information
