### ISSUE TITLE
Data is getting loss inside one2many field which is custom in sale line

### ISSUE THREAD

**Issue by bista-arpit** [odoo/odoo#24921] opened 2018-05-25 12:31 UTC
Impacted versions:
Odoo 11 community and enterprise both
Steps to reproduce:

I created a model name x_sales.order.location having two fields there (x_partner_id, x_commence_date,x_sale_line_id)

and after the creation of this model, I make a field name customer_lines which is one2many with sale.order.line reference to x_sale_line_id.

and I put this field in form view of sale order line as you can see in the attached video.

Current behavior:

if u see  video on Odoo 11 while putting the data inside one2many on sale line only partner . Then I hit save but again I edit the sale order form and put the commencement date in each line along with partner which is already filled. 
And see at this moment if I did not hit save button of the parent form if I hit that than all ok no problem but before saving the parent form    User need to edit or want to see what date he has put in all lines. Than you will see only first line has date which is not loss and in rest line date is getting loss.

Expected behavior:
it is very strange behaviour and very critical .
Please find the attach video.

Video/Screenshot link (optional):

video link as follows

https://drive.google.com/file/d/0Bw_ic8lZZMhtS1dvblU4LXBtNDJZenhEMFFLZmp0cHpQSDJZ/view?usp=sharing

**Comment by bista-arpit** [comment] 2018-05-25 15:18
On replicating the same on odoo version 10

it is working fine.

https://drive.google.com/file/d/0Bw_ic8lZZMhtT3JndWgtZVd2M05tWXV4TmNPaHFLZ3FuUktr/view?usp=sharing

but in odoo 11 it is not working.

Please check , it is very critical issue we are facing.

Thanks
Arpit

**Comment by bistaray** [comment] 2018-05-25 15:41
We also face the same issue and its causing lot of problem in version 11. The patch of the fix should be released soon @Yenthe666 @rvalyi @fpodoo.

**Comment by preetipatankar** [comment] 2018-05-25 16:45
We are facing the same issue. Kindly update once this is fixed. This is critical for our project. @Yenthe666 @fpodoo

**Comment by Yenthe666** [comment] 2018-05-25 17:30
@bistaray what exactly do you mean with the patch of the fix should be released soon? Did you log an official ticket or? Not sure what you mean.

**Comment by bistaray** [comment] 2018-05-25 17:58
@Yenthe666, These are the two official tickets to Odoo

https://www.odoo.com/my/task/1836785
https://www.odoo.com/my/task/1846820

**Comment by robin-bahadur** [comment] 2018-05-25 21:28
Is there is any work around to solve this problem. I can see this bug in ORM is still open from long time, first posted in January 2018
https://www.odoo.com/forum/help-1/question/odoo-one2many-field-does-not-save-field-values-sale-order-line-113073

**Comment by bista-arpit** [comment] 2018-06-04 15:06
Hi @Yenthe666 ,

Is any update on this issue.
Please let me know

Thanks!
Arpit

**Comment by Yenthe666** [comment] 2018-06-05 06:06
@bista-arpit not from my side, @bistaray can you give an update on the official tickets?

**Comment by bistaray** [comment] 2018-06-05 07:31
@Yenthe666, Issue is transferred to Belgium team and they are investigating the root cause and comparing Odoo 10 and Odoo 11. Will keep updating this thread with information shared by Belgium team.

**Comment by Yenthe666** [comment] 2018-06-05 10:02
Thanks!

**Comment by bistaray** [comment] 2018-08-15 19:29
@Yenthe666, @rvalyi,  @fpodoo, @nle-odoo: This issue mentioned as solved in https://github.com/odoo/odoo/commit/06d89a84408 but still the behavior is same and data is getting lost from one2many field.

**Comment by bistaray** [comment] 2018-11-09 18:43
@Yenthe666, @rvalyi, @fpodoo, @nle-odoo: As of today, with all latest Enterprise 11 and Odoo 11 code. Still, the one2many value is not getting saved, even it does not get passed to the backend. Data is getting lost in a web framework.

**Comment by nle-odoo** [comment] 2018-11-09 18:58
Hi,

There was two issues I think in Odoo system:
- https://www.odoo.com/my/task/1836785 (closed in june)
- https://www.odoo.com/my/task/1846820 (with a report in august that the solution in june did not work fully)

For the second one I had tested in august a week after the report from mid-august and was not able to reproduce a looss of data (doing the steps indicated in the two reports).

I have opened back issue 1846820 and will test again next week.

**Comment by nle-odoo** [comment] 2018-11-14 17:22
Hi,


I was able to reproduce this time and I am working on a fix in this PR: https://github.com/odoo/odoo/pull/28644

My next steps are to review it successfully then hopefully this should solve the issue.

**Comment by nle-odoo** [comment] 2018-11-19 17:47
Hi

The above mentioned PR has been merged in 11.0 with:
 https://github.com/odoo/odoo/commit/cac91731221b

Regards.

**Closed** 2018-12-04 13:05 UTC
Labels: 11.0, Framework

**Comment by niyaspavil** [comment] 2019-07-04 01:51
We still have this issue
One2many data is losing
