### ISSUE TITLE
Bug For CRM

### ISSUE THREAD

**Issue by anuar101** [odoo/odoo#5471] opened 2015-02-26 01:02 UTC
Hi good day,

I would to inform you i found a bug your crm.
Please see the screen shot below.

Thanks,
Anuar
![screen shot 2015-02-26 at 8 47 21 am](https://cloud.githubusercontent.com/assets/11203478/6384316/dd44cf20-bd95-11e4-9bbd-71be37ff0e7f.png)

**Comment by lukebranch** [comment] 2015-02-26 01:28
@anuar101 ,

I think this may just mean that your connection to the Odoo server was temporarily disconnected for whatever reason.

It looks like you are using Odoo online, so i'd recommend taking a look at your internet connection if this happens again, as it is likely you are losing your connection to Odoo's SaaS server.

**Comment by anuar101** [comment] 2015-02-26 01:36
Hi,

I see, but the error is annoying for the user it is possible to change your
error message.
Instead of XmlHttpRequestError.

Thanks,
Anuar

**Comment by lukebranch** [comment] 2015-02-26 01:54
@anuar101 ,

I'm not actually involved with Odoo, i'm only a user like yourself. I'd recommend closing this github issue, as it is not a bug.

As you are with Odoo online if you are having issues you may want to get in touch with them here:

https://www.odoo.com/page/website.contactus

to see if their support staff can help you.

**Comment by lukebranch** [comment] 2015-04-02 14:26
@anuar101

**Comment by Yenthe666** [comment] 2017-12-14 07:36
Indeed - not a bug. Your internet was simply gone for a little while and then you get this issue. Odoo 9 and up handles this way cleaner too.

**Closed by Yenthe666** 2017-12-14 07:36 UTC

**Comment by anuar101** [comment] 2017-12-14 15:29
For a long time response lol. I'm not mentioned the internet was gone you
need to create error handler for the internet was gone not system error
return into the user so much better to understand.

**Comment by Yenthe666** [comment] 2017-12-14 15:36
In V9 and up you'll get a non-blocking dialog that shows there is no internet actually.

**Comment by anuar101** [comment] 2017-12-14 15:50
Great job! thanks for your time :)

**Comment by Yenthe666** [comment] 2017-12-14 15:53
You're welcome! :)
