### ISSUE TITLE
[8.0] navigation icon CSS is broken with firefox 32

### ISSUE THREAD

**Issue by nbessi** [odoo/odoo#2313] opened 2014-09-10 10:11 UTC
When in list mode or in form mode navigation butons and view selection button CSS is broken with Firefox 32

**Comment by Yenthe666** [comment] 2016-06-03 10:28
Hey @nbessi,

I can't reproduce this issue anymore so I'm closing this one.

Regards,
Yenthe

**Closed by Yenthe666** 2016-06-03 10:28 UTC
