### ISSUE TITLE
[11.0] Domains no longer working with dynamic dates

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#22956] opened 2018-02-09 11:18 UTC
Impacted versions: 11.0

Steps to reproduce:
1. Go to settings > Technical > Automation > Automated actions and create a new automated action.
2. For example to test use the model to `purchase.order`, action to do to email, add an e-mail template and then add a domain. For this domain say that the date has to be smaller than the current date (dynamical):
```
[["create_date","<",time.strftime('%Y-%m-%d')]]
```
Your domain now looks like this:
![image](https://user-images.githubusercontent.com/6352350/36025345-020d3c20-0d93-11e8-8832-024d32ca36ab.png)
Now when you click anywhere else or save this the domain will be saved as [["create_date","<","2018-02-09"]] (today) as the date field of the domain filter goes off again.
In V10 you could set the domain with dynamic values, such as `[["create_date","<",time.strftime('%Y-%m-%d')]]` without any issues:
![image](https://user-images.githubusercontent.com/6352350/36025398-2c2e6a9c-0d93-11e8-8666-c6604b6b21fe.png)

Current behavior: You can't create dynamic domains that use values such as `[["create_date","<","2018-02-09"]]` as the value is always changed/overriden by the datetime field.

Expected behavior: You're able to set dynamic domains and values just like in V10.

**Comment by Yenthe666** [comment] 2018-02-09 11:22
OPW 815393

**Comment by ddfs** [comment] 2018-03-06 15:52
not sure if this is related to problem but seems similar. when default language is not 'en_US' page editor throws the following error due to malformed date-time. screenshot is from runbot.

![screenshot from 2018-03-06 17-46-42](https://user-images.githubusercontent.com/6930079/37042303-d555fd1a-2166-11e8-805c-7a7e3b58cd95.png)

**Comment by Yenthe666** [comment] 2018-03-06 15:54
@ddfs this is actually not really related I believe. Can you make a new bug report for this one with a bit of info please?

**Comment by ddfs** [comment] 2018-03-06 15:56
@Yenthe666 ok, i ll create new ticket.

**Comment by kebeclibre** [comment] 2018-03-08 09:09
@Yenthe666 
From the opw:
I investigated in depth this issue, and there is indeed a limitation on the domain selector widget.
I also discovered that to improve this widget, many choices, functional and technical would have to be made.

There is a workaround to the issue, that is to remove the widget "domain" from the view. No widget will then handle the char field behind it, and you'll be able to write a dynamic domain.

I am forwarding this ticket as a feedback to the relevant team.
cc. @ged-odoo

**Comment by Yenthe666** [comment] 2018-03-08 09:16
Hi @kebeclibre,

Thanks a lot for the feedback.
Does your answer mean this won't be fixed in 11.0 itself? The workaround is far from ideal and since our functional guys tend to make domains like this without further technical knowledge I think this is not an option.
Could you give a timeline for when we can expect a fix? It is a rather big and blocking issue for functional people.

**Comment by pedrobaeza** [comment] 2018-03-08 09:20
As an additional info, a similar thing happens when trying to use `uid` as variable. It's changed to `"uid"`, making it not usable.

**Comment by Yenthe666** [comment] 2018-03-08 09:26
I cannot understand why my Odoo ticket is put in the state "cancelled" by the way @kebeclibre..

**Comment by kebeclibre** [comment] 2018-03-08 10:07
@Yenthe666 
Yes my answer is that this issue is not a bugfix but a new feature request, and as such I won't fix it.
The widget is precisely here to simplify the edition of domain for non-technical guys. Its limitation is that it cannot (yet) have expression in them.
I understand the workaround is not ideal, but having "fancy" domains is kind of technical anyway. I think it would be a great value added for anyone doing customization to know how to modify a view and to build a domain by hand.
I cancelled your ticket because it is not technically a bugfix, however I diligently referenced the ticket on an internal task that already exists to handle the case.

@pedrobaeza 
It is not surprising that you have this issue, which is totally the same as the present one.
What happens in the widget is that  the expression you write is interpreted *as python* (it allows to check whether it is correct and valid too) and the result of the interpretation is used to redraw the different parts of the domain in the widget (and vice versa)

**Comment by pedrobaeza** [comment] 2018-03-08 10:21
Well, it can be considered a bug when you edit an existing filter with one of that expressions and the widget break them. Odoo itself brings a lot of filters with that expressions.

**Comment by Yenthe666** [comment] 2018-03-08 10:21
and not to mention that it was working perfectly in V10. So basically, it is a bug.

**Comment by ploegvde** [comment] 2018-03-08 11:12
This makes no sense at all. We use this feature in Odoo on dozens of places to give proper filters on lists and we use them indeed on automated actions. There is no way a functional consultant is going to change a view as a workaround. 

Trying to make things better is a good thing, but als acknowledge if you made a mistake in improving by removing a functionality that is used heavily.

**Comment by kebeclibre** [comment] 2018-03-08 12:55
@Yenthe666 
@ploegvde 
I tested in v10.0:
the domains are a many2one towards ir.filter
which you can edit in pure text, no widget involved (unless I'm missing something ?)

I did acknowledge that was a limitation of the widget in v11.0, the functionality you ask for is actually there, not handled by the widget though.

As I mentioned, there is an internal task which handles this case, it requires technical and functional decisions that certainly cannot be made as part of a bugfix, and which development can take slightly more time

@ged-odoo 
@Polymorphe57

**Comment by Yenthe666** [comment] 2018-03-13 15:35
@ged-odoo could you please give us an update and/or more insight here? We really need this for customers / functional people.

**Comment by Yenthe666** [comment] 2018-03-19 14:18
@kebeclibre and @ged-odoo,

I've had this talk with the whole team about the dynamic filters and we all agree on the fact that this is a bug and that this should be fixed.
Usually I don't like to 'force' people or keep pushing but in this case I will have too. We, as a gold partner, demand a fix for what is clearly a bug and clearly worked in 10.0. We have multiple big customers facing this issue and complaining. I don't think think you can genuinely ask us to inherit all views and rewrite filters to make dynamic domains for every single customer we have, right?

CC @ploegvde and @jvOrsouw

Regards,
Yenthe

**Comment by ged-odoo** [comment] 2018-03-26 13:09
@Yenthe666 @pedrobaeza 

I talked with @kebeclibre about this issue.  I also read all the comments in this thread, and while I agree that the situation is not perfect (or quite bad in some respect), I have to close this issue. Here is why:

- we replaced an element of the interface which was complex (editing manually an ir.filter) by a simpler, but more limited widget (no dynamic filter, but much simpler for most users).  This was a functional choice, not a technical one.  We totally should work on the domain editor, and I would guess that we will actually do that when we improve the search filters someday, but this will be  in master.
- we consider that a user capable of editing a dynamic filter is definitely able to remove a widget from a view
- it is quite easy to remove them all (only 5 in odoo community, and 8 in enterprise)

I am really sorry that we let you down, but we (as developers) are stuck between the needs of Odoo (which consider that the cost of losing dynamic filters is ok with the fact that more users will be able to use a domain) and the technical difficulty of working with dynamic filter (a first look tell me that we need to basically implement a custom python parser, since the default one will evaluate the filter.  Even if there is another simpler way, it will take some time to make it accessible, nicely editable, test it, ...).

I think that there is some merit to complaining about this, and maybe you should open again a opw ticket mentioning that you do not agree on the functional choice.

**Comment by Yenthe666** [comment] 2018-03-26 13:47
Hi @ged-odoo,

Thank you for the feedback and the time you took to answer this.
As a developer I - ofcourse - understand that you're a bit stuck and that there is not much you can do. From a functional perspective it is harder to understand I guess.

To conclude: It is sad that it won't (can't) be fixed in this version and I hope we can see a fix for V12 as it really is a handy functionality.

Regards,
Yenthe

**Comment by pedrobaeza** [comment] 2018-03-26 14:28
OK, thanks for the feedback, and I understand the load it supposes to be improved. Please ping me when you decide to improve the widget, as I have several suggestions.

**Comment by HaraldPanten** [comment] 2018-10-19 21:05
Hi all,

Do we have any news about this issue? Is it going to be fixed in V12?

Thanks!

**Comment by Yenthe666** [comment] 2018-10-20 07:37
Sadly it is also an issue in V12 and I'm afraid there is no fix coming anywhere soon.

**Comment by HaraldPanten** [comment] 2018-10-20 22:46
Bad news...

Thanks for your reply, @Yenthe666

**Comment by CasVissers** [comment] 2019-01-09 14:07
Amazing that this issue isn't solved yet. It really blocks functional consultants in doing their job.

**Comment by CasVissers** [comment] 2019-01-09 14:12
Just a random thought, can we not let the user decide in the form if the filter has to be edited rawly or with the widget? Then the decision can be made per filter. The "Use Widget" bool can be hidden behind developer mode.

**Comment by swisskidacex** [comment] 2019-01-14 16:07
This REALLY Needs fixing!

**Comment by C3POdoo** [comment] 2019-04-11 14:12
Dear @Yenthe666,

_This is an automated message._
This issue is linked to the Odoo support ticket opw-1815393 that has been closed.
We hope you got an answer to your issue.

If you believe the problem is not solved yet and would like to keep this issue open, please let us know to reopen it.

**Closed by C3POdoo** 2019-04-11 14:12 UTC
Labels: 11.0, 12.0, Framework, OE

**Comment by Mike1581** [comment] 2020-01-09 12:49
Sorry this was never fixed. Thanks to this thread I was able to figure out a workaround that let's me save dynamic dates. I'm sure you will all shudder when you see what I've done but it works for me (no development knowledge and new to Odoo)
[https://www.odoo.com/forum/help-1/question/odoo-11-ce-dynamic-dates-in-actions-162602]((https://www.odoo.com/forum/help-1/question/odoo-11-ce-dynamic-dates-in-actions-162602))

**Comment by kebeclibre** [comment] 2020-01-09 13:36
@Mike1581 
If you read the whole issue, you would have seen that a similar workaround was proposed long ago.
The widget="domain" doesn't not support dynamic filters, but plain text does and your solution too.
I made a whole lot of justification for not fixing. You can disagree with those, but ultimately we *know* it has not been fixed.

**Comment by Mike1581** [comment] 2020-01-09 14:45
@kebeclibre 
My comment wasn't to tell you it's not fixed, but to say "I'm sorry to find out that it was never fixed", and to provide a detailed link to the workaround for anyone like me who is less technically minded, to save them having to work through it in detail step by step like I did. 
I understand your justifications made above and development / project priorities etc. My post wasn't meant to be a criticism of you or anyone else on this thread so I'm sorry if that was how it came across.
