### ISSUE TITLE
file /usr/lib/python2.7/dist-packages/werkzeug/routing.py in match raise not found

### ISSUE THREAD

**Issue by setiaji** [odoo/odoo#18422] opened 2017-07-25 01:54 UTC
Impacted versions: 10

Steps to reproduce:

a. Login to user which have permission into postgresql

example: sudo su – postgres_user

b. Make sure there is at least one role after executed command below

example: psql \du

c. Check for odoo service, if still active, we should stop it before update

example: systemctl status odoo

d. Update odoo module

example: ./odoo-bin -d nama_database -u all

Current behavior:
Update did not finish in time i expected, and i press Ctrl-C to cancel the update

Expected behavior:
Update ended with smooth.

Video/Screenshot link (optional):

![selection_011](https://user-images.githubusercontent.com/1822082/28552148-ad405770-7127-11e7-8e80-85c23a8e15e9.png)

**Comment by aymanshow** [comment] 2018-03-05 03:49
the same on 9.0 is here !!

**Comment by pedrobaeza** [comment] 2018-06-02 14:55
Hi, I'm not able to reproduce this problem in latest version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-06-02 14:55 UTC
Labels: 10.0, Framework
