### ISSUE TITLE
Google calendar InternalError  transaction block

### ISSUE THREAD

**Issue by m3asmi** [odoo/odoo#64235] opened 2021-01-07 19:03 UTC
Impacted versions:
12.0
Steps to reproduce:
run synchornisation 
Current behavior:
Erreur:
Odoo Server Error

Traceback (most recent call last):
Erreur:
Odoo Server Error
```

Traceback (most recent call last):
2021-01-07 18:59:12,466 2412 ERROR db odoo.sql_db: bad query: UPDATE "calendar_attendee" SET "google_internal_event_id"='3qtmb5ejftmue5cckgs89veh9s_20201005T103000Z,',"write_uid"=231,"write_date"=(now() at time zone 'UTC') WHERE id IN (79726)
ERROR: duplicate key value violates unique constraint "calendar_attendee_google_id_uniq"
DETAIL:  Key (google_internal_event_id, partner_id, event_id)=(3qtmb5ejftmue5cckgs89veh9s_20201005T103000Z, 7158, 23144) already exists.
 
2021-01-07 18:59:12,466 2412 WARNING db odoo.addons.google_calendar.models.google_calendar: Exception when updating recurrent event exclusions on google: duplicate key value violates unique constraint "calendar_attendee_google_id_uniq"
DETAIL:  Key (google_internal_event_id, partner_id, event_id)=(3qtmb5ejftmue5cckgs89veh9s_20201005T103000Z, 7158, 23144) already exists.
 
2021-01-07 18:59:12,468 2412 ERROR db odoo.sql_db: bad query: SELECT "calendar_attendee".id FROM "calendar_attendee" WHERE (("calendar_attendee"."partner_id" = 7158)  AND  ("calendar_attendee"."event_id" = 23145)) ORDER BY "calendar_attendee"."id"   limit 1
ERROR: current transaction is aborted, commands ignored until end of transaction block
 
2021-01-07 18:59:12,468 2412 ERROR db odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/google_calendar/controllers/main.py", line 43, in sync_data
    return GoogleCal.with_context(context).synchronize_events()
  File "/odoo/odoo-server/addons/google_calendar/models/google_calendar.py", line 631, in synchronize_events
    new_ids += recs.bind_recurring_events_to_google()
  File "/odoo/odoo-server/addons/google_calendar/models/google_calendar.py", line 696, in bind_recurring_events_to_google
    source_attendee_record = CalendarAttendee.search([('partner_id', '=', my_partner_id), ('event_id', '=', source_event_record.id)], limit=1)
  File "/odoo/odoo-server/odoo/models.py", line 1581, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/odoo/odoo-server/odoo/models.py", line 4165, in _search
    self._cr.execute(query_str, where_clause_params)
  File "/odoo/odoo-server/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.InternalError: current transaction is aborted, commands ignored until end of transaction block

 
```

**Comment by pedrobaeza** [comment] 2021-01-07 19:05
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by m3asmi** [comment] 2021-01-08 08:02
@pedrobaeza indeed this happened after I pushed the last updates from git !

**Comment by pedrobaeza** [comment] 2021-01-08 08:11
Yeah, but we need reproducible steps in a runbot instance for being able to diagnose the problem.

**Comment by m3asmi** [comment] 2021-01-15 16:36
@pedrobaeza it's not easy to produce it in runbot,
but as you see the traceback error is clear no custom models!

**Comment by pedrobaeza** [comment] 2021-01-15 16:40
Unless you provide a way to reproduce it, nothing can't be done. I suspect a corruption on your data leads to this.

**Comment by m3asmi** [comment] 2021-01-15 16:43
@pedrobaeza we did change the Google API key and re-synch, now not working even after uninstall the module and install it!

**Comment by pedrobaeza** [comment] 2021-01-15 16:45
Then that's the problem. You have to clean offending data cleaning fields or deleting records.

Closing as DB mangling.

**Closed by pedrobaeza** 2021-01-15 16:45 UTC
Labels: Need information

**Comment by m3asmi** [comment] 2021-01-19 09:13
here is a fix:
here https://github.com/odoo/odoo/blob/6b3c81bb5eebaf9be82c9a838cdafd9d3da44787/addons/google_calendar/models/google_calendar.py#L711

we must first verify if `google_interna_event_id` already exists before update
it's crashes if the line exists an we update the line with the same value!
```

            if new_google_internal_event_id:
                #TODO WARNING, NEED TO CHECK THAT EVENT and ALL instance NOT DELETE IN GMAIL BEFORE !
                try:
                    status, response, ask_time = self.update_recurrent_event_exclu(new_google_internal_event_id, source_attendee_record.google_internal_event_id, att.event_id)
                    if status_response(status):
                        ######### fix existing google_interna_event_id passe
                        exist_google_id = self.env['calendar.attendee'].search(
                            [('google_internal_event_id', '=', new_google_internal_event_id),
                             ('partner_id', '=', att.partner_id.id), ('event_id', '=', att.event_id.id)])
                        if not exist_google_id:
                            att.write({'google_internal_event_id': new_google_internal_event_id})
                        ######
                        new_ids.append(new_google_internal_event_id)
                        self.env.cr.commit()
                    else:
                        _logger.warning("Impossible to create event %s. [%s]", att.event_id.id, status)
                        _logger.debug("Response : %s", response)
                except Exception as e:
                    _logger.warning("Exception when updating recurrent event exclusions on google: %s", e)
```

**Comment by pedrobaeza** [comment] 2021-01-19 09:48
Please propose as a PR then.
