### ISSUE TITLE
how we install website_less module in odoo v9

### ISSUE THREAD

**Issue by kartikdanidhariya** [odoo/odoo#10267] opened 2016-01-02 08:08 UTC
hi,
i want to create customize theme for odoo v9
after refer doc of odoo it shows that 

This tutorial requires having installed Odoo v9.0 and the Theme Support Engine (website_less) module. https://www.odoo.com/apps/9.0/website_less/

but website_less module link not works it return Not Found

please provide valid links for download website_less module for odoo v9

**Comment by lukebranch** [comment] 2016-01-02 08:34
@kartikdanidhariya ,

I am not working with Odoo, but am just another user like yourself.

website_less does not exist in version 9.0 as it is no longer required. The documentation for 9.0 is not entirely up to date in this specific area.

For these kinds of questions i'd recommend using the forum here:

http://help.odoo.com

as the github issues are for reporting bugs.

**Comment by kartikdanidhariya** [comment] 2016-01-04 11:42
OK,
  i apologies for mistakes next time i take care of that

**Comment by lukebranch** [comment] 2016-01-04 12:56
@kartikdanidhariya ,

Please close this issue as it is not a bug. This will help keep the open issues as actual bugs that Odoo SA needs to look at so they don't have too much 'noise' (ie. issues that are not relevant to a bug report).

**Closed** 2016-01-06 07:08 UTC
