### ISSUE TITLE
Odoo 11 POS can't validate order

### ISSUE THREAD

**Issue by turkimaki** [odoo/odoo#30877] opened 2019-02-06 11:19 UTC
Hello ,

After following the configuration of official documentation of odoo for the part pos when I click to validate order nothing happend and the order wasn't added and no change when I close the session .
So please if any one can help me to resolve this .

Thanks ,cordially Maki .

**Comment by pedrobaeza** [comment] 2019-02-06 11:22
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by turkimaki** [comment] 2019-02-06 11:30
Thanks for reply ,I had try on runbot community entreprise and doesn't work but unfortunately  they are no error on my process to validate the order just I click on the button and nothings happend so screenshot will show nothing

**Comment by pedrobaeza** [comment] 2019-02-06 11:41
But the steps to reproduce will serve.

**Comment by turkimaki** [comment] 2019-02-06 13:23
do you have test the process and confirm order work for you ?

**Comment by Yenthe666** [comment] 2019-04-09 06:00
@turkimaki can you try again on a runbot? It seems to work fine at my end. Perhaps you can upload a movie if you can still reproduce it?

**Comment by Yenthe666** [comment] 2019-05-14 09:29
Hi there,

I'm closing this issue as there has been no feedback in over a month.

**Closed by Yenthe666** 2019-05-14 09:29 UTC
Labels: Need information
