### ISSUE TITLE
[10.0]Base amount wrong on report

### ISSUE THREAD

**Issue by jayo2005** [odoo/odoo#35192] opened 2019-07-25 18:12 UTC
Impacted versions:10

Steps to reproduce: I have two vat rates 23% & 13.5%. When running the Tax balance report or the Sale/Purchase report the Base amount is wrong. On the 23rd I have one invoice with 13.5%. Prices include Tax

Current behavior: 13.5% tax and 23% tax are mixed up

Expected behavior: each tax rate should have its own base amount.

Video/Screenshot link (optional):
![1](https://user-images.githubusercontent.com/7015925/61897236-8d81ae80-af0e-11e9-8c93-9b12df766af4.jpg)
So the VAt on 13.5% is 11.81.

When I run the Sale/Purchase report.

![2](https://user-images.githubusercontent.com/7015925/61897298-abe7aa00-af0e-11e9-8121-ff040cd61005.jpg)

You can see above the Base amount for 13.5% is totally wrong but Tax is correct.

If I run the Tax balance Report.

![3](https://user-images.githubusercontent.com/7015925/61897369-cd489600-af0e-11e9-98ab-ec55ccb11f4b.jpg)

A closer look at the Tax Balance report where is €20.71 coming from.
![4](https://user-images.githubusercontent.com/7015925/61897469-fe28cb00-af0e-11e9-8218-1bf6518ba422.jpg)

AS a result, my reports are all wrong. My accountant has told me to stop using Odoo as it is not handling the Tax rates correctly. Can some please explain what is going on or supply a fix.

<img width="887" alt="vtagit" src="https://user-images.githubusercontent.com/7015925/61897584-47791a80-af0f-11e9-82a0-89eb422809ca.png">

As you can see the tax info on the invoice is correct but when you run the Sale/Purchase report the base amount is wrong because it added the 20.71 instead of the 11.81
11.81 = 13.5%
20.71 = 23%

So why is the base amount for 13.5% 108.15 when it should be 87.44

**Comment by pedrobaeza** [comment] 2019-07-25 18:16
As said before, are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Yenthe666** [comment] 2019-08-11 14:48
Hi @jayo2005,

As there has been no feedback on this issue I'm closing it.
If you're still able to reproduce this issue then please add extra information and we'll reopen it.

Regards,
Yenthe

**Closed by Yenthe666** 2019-08-11 14:48 UTC
Labels: 10.0, Need information
