### ISSUE TITLE
v11 module - Stock - issue - two moves expecting each other as their destinations move

### ISSUE THREAD

**Issue by anny17** [odoo/odoo#66576] opened 2021-02-20 05:03 UTC
Impacted versions: I have found this in v11

Steps to reproduce:
1. Create a Sale order,
2. Mark the delivery
3. Create a Return on delivery and mark it done
4. Create a return on the return
Now the lastly created return will have both move_orig_id and move_dest_id same. (Which should not be the case)

Current behavior:
The last created return has both move_orig_id and move_dest_id same to the move it was created from.

Expected behavior:
It Should not have its origin move in its linked destination.

**Comment by pedrobaeza** [comment] 2021-02-20 09:56
Sorry, but the Odoo version mentioned in the issue is no longer supported. Odoo only supports the last 3 stable versions.

If the report still makes sense for the upper version, please let us know and specify possible recreated steps for the newer version in a new issue report.

Meanwhile, closing this.

**Closed by pedrobaeza** 2021-02-20 09:56 UTC
