### ISSUE TITLE
[11.0] Performance impact when changing the qty on the Inventory Adjustments

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#22002] opened 2018-01-04 02:47 UTC
### Impacted versions:
11.0 

### Steps to reproduce:
Start an inventory adjustment for all the products

### Current behavior:
If you have more than 3,000 products, changing the real quantity calls an onchange that takes between 12 - 23 seconds; making it almost impossible to use the first option on an inventory adjustment. 

### Expected behavior:
Doing the quantity change without triggering that "killing onchange"

**Comment by Yenthe666** [comment] 2018-01-04 08:01
Hi @gustavovalverde,

Thanks a lot for your report.
I've actually reported bugs like this with inventory adjustments too. Performance is quite a lot slower than V9/V10 for adding lines, removing them etc.
We've also got a ticket regarding performance (ticket number 785425) where they also found major impact on performance with translations - coming from https://github.com/odoo-dev/odoo/commit/0cc70dbfca714bc920e0be2f189669d6f423aa87.
Not exactly your issue but quite similar.

Regards,
Yenthe

**Comment by lukebranch** [comment] 2018-01-04 10:16
I've experienced this as well, it's a major point of annoyance for those customers with large inventories. I wonder if this would be better handled when the save function is triggered.

**Comment by sle-odoo** [comment] 2018-01-04 11:58
When i made some tests, v11 is quicker than v9 and v10 on large inventory adjustment when not using the barcode scanner nor the special view (fullscreen editable list where onchanges are bypassed). It is still really too slow though. Is it not your experience?

**Comment by Yenthe666** [comment] 2018-01-04 12:13
@sle-odoo our performance tests are all done with V11 and a barcode scanner. The barcode scanning on inventory adjustments was quite a bit slower in V11 than V11.

**Comment by sle-odoo** [comment] 2018-01-04 13:12
@Yenthe666 yes we still need to bypass the onchanges if they're not needed in v11, so that's expected. but the onchange are quicker.

**Comment by gustavovalverde** [comment] 2018-01-04 13:48
@sle-odoo we compared two databases, one in v10 with ~2,300 products and a v11 database with ~3,100 products, it was a bunch slower in v11 when making changes to an inventory line.

Even doing manual product selection got slower and slower as more products were added in the inventory lines.

**Comment by sle-odoo** [comment] 2018-01-04 13:50
@gustavovalverde thanks, is it possible you made this test a few weeks ago? we made some changes to cache the name_get in the meantime and it improved a lot

**Comment by gustavovalverde** [comment] 2018-01-04 13:54
Yesterday, on commit 8e181c99c233f1a0e068f9218449add174a9a2b6.

**Comment by sle-odoo** [comment] 2018-01-04 13:57
okay :( i will have a look

**Comment by Yenthe666** [comment] 2018-01-04 14:06
Thanks a lot @sle-odoo

**Comment by lem8r** [comment] 2018-01-06 13:20
We have similar issue with PO containing 2749 lines.
Changing quantity in single line takes about 3 minutes.

Frontend profiling:
![onchange-3min](https://user-images.githubusercontent.com/5942291/34639994-3c18cf66-f2f3-11e7-9174-dc54e26e1f70.png)

Backend (release 2018-01-06) python process takes 100% CPU while handling `/call_kw/purchase.order/onchange`
Stack trace with `kill -3`

```bash
# Thread: <_MainThread(MainThread, started 140505679902464)> (db:db-pedi-test) (uid:1) (url:http://pediando.ch/web/dataset/call_kw/purchase.order/onchange)
odoo11-pediando_1  | File: "/usr/bin/odoo", line 8, in <module>
odoo11-pediando_1  |   odoo.cli.main()
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/cli/command.py", line 60, in main
odoo11-pediando_1  |   o.run(args)
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/cli/server.py", line 175, in run
odoo11-pediando_1  |   main(args)
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/cli/server.py", line 169, in main
odoo11-pediando_1  |   rc = odoo.service.server.start(preload=preload, stop=stop)
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/service/server.py", line 991, in start
odoo11-pediando_1  |   rc = server.run(preload, stop)
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/service/server.py", line 635, in run
odoo11-pediando_1  |   self.process_spawn()
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/service/server.py", line 539, in process_spawn
odoo11-pediando_1  |   self.worker_spawn(WorkerHTTP, self.workers_http)
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/service/server.py", line 457, in worker_spawn
odoo11-pediando_1  |   worker.run()
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/service/server.py", line 743, in run
odoo11-pediando_1  |   self.process_work()
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/service/server.py", line 776, in process_work
odoo11-pediando_1  |   self.process_request(client, addr)
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/service/server.py", line 767, in process_request
odoo11-pediando_1  |   self.server.process_request(client, addr)
odoo11-pediando_1  | File: "/usr/lib/python3.5/socketserver.py", line 341, in process_request
odoo11-pediando_1  |   self.finish_request(request, client_address)
odoo11-pediando_1  | File: "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
odoo11-pediando_1  |   self.RequestHandlerClass(request, client_address, self)
odoo11-pediando_1  | File: "/usr/lib/python3.5/socketserver.py", line 681, in __init__
odoo11-pediando_1  |   self.handle()
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 228, in handle
odoo11-pediando_1  |   rv = BaseHTTPRequestHandler.handle(self)
odoo11-pediando_1  | File: "/usr/lib/python3.5/http/server.py", line 422, in handle
odoo11-pediando_1  |   self.handle_one_request()
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 263, in handle_one_request
odoo11-pediando_1  |   return self.run_wsgi()
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
odoo11-pediando_1  |   execute(self.server.app)
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 193, in execute
odoo11-pediando_1  |   application_iter = app(environ, start_response)
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 166, in application
odoo11-pediando_1  |   return application_unproxied(environ, start_response)
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 154, in application_unproxied
odoo11-pediando_1  |   result = handler(environ, start_response)
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/http.py", line 1298, in __call__
odoo11-pediando_1  |   return self.dispatch(environ, start_response)
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/http.py", line 1272, in __call__
odoo11-pediando_1  |   return self.app(environ, start_wrapped)
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 599, in __call__
odoo11-pediando_1  |   return self.app(environ, start_response)
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/http.py", line 1462, in dispatch
odoo11-pediando_1  |   result = ir_http._dispatch()
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
odoo11-pediando_1  |   return super(Http, cls)._dispatch()
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/addons/web_editor/models/ir_http.py", line 21, in _dispatch
odoo11-pediando_1  |   return super(IrHttp, cls)._dispatch()
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/addons/http_routing/models/ir_http.py", line 391, in _dispatch
odoo11-pediando_1  |   result = super(IrHttp, cls)._dispatch()
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/addons/utm/models/ir_http.py", line 20, in _dispatch
odoo11-pediando_1  |   response = super(IrHttp, cls)._dispatch()
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_http.py", line 208, in _dispatch
odoo11-pediando_1  |   result = request.dispatch()
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/http.py", line 683, in dispatch
odoo11-pediando_1  |   result = self._call_function(**self.params)
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in _call_function
odoo11-pediando_1  |   return checked_call(self.db, *args, **kwargs)
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
odoo11-pediando_1  |   return f(dbname, *args, **kwargs)
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/http.py", line 332, in checked_call
odoo11-pediando_1  |   result = self.endpoint(*a, **kw)
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/http.py", line 927, in __call__
odoo11-pediando_1  |   return self.method(*args, **kw)
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/http.py", line 512, in response_wrap
odoo11-pediando_1  |   response = f(*args, **kw)
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 924, in call_kw
odoo11-pediando_1  |   return self._call_kw(model, method, args, kwargs)
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 916, in _call_kw
odoo11-pediando_1  |   return call_kw(request.env[model], method, args, kwargs)
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/api.py", line 689, in call_kw
odoo11-pediando_1  |   return call_kw_multi(method, model, args, kwargs)
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/api.py", line 680, in call_kw_multi
odoo11-pediando_1  |   result = method(recs, *args, **kwargs)
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/models.py", line 4963, in onchange
odoo11-pediando_1  |   record.mapped(dotname)
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/models.py", line 4411, in mapped
odoo11-pediando_1  |   recs = recs._mapped_func(operator.itemgetter(name))
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/models.py", line 4390, in _mapped_func
odoo11-pediando_1  |   vals = [func(rec) for rec in self]
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/models.py", line 4390, in <listcomp>
odoo11-pediando_1  |   vals = [func(rec) for rec in self]
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/models.py", line 4657, in __getitem__
odoo11-pediando_1  |   return self._fields[key].__get__(self, type(self))
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/fields.py", line 948, in __get__
odoo11-pediando_1  |   self.determine_value(record)
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/fields.py", line 1049, in determine_value
odoo11-pediando_1  |   record._prefetch_field(self)
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/models.py", line 2558, in _prefetch_field
odoo11-pediando_1  |   records &= self._in_cache_without(f)
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/models.py", line 4684, in _in_cache_without
odoo11-pediando_1  |   ids1 = set(self.env.cache.get_records(self, field)._ids)
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/api.py", line 1009, in get_records
odoo11-pediando_1  |   for record_id, field_record_cache in self._data[field].items()
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/api.py", line 1010, in <listcomp>
odoo11-pediando_1  |   if field.cache_key(browse(record_id)) in field_record_cache]
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/models.py", line 4237, in browse
odoo11-pediando_1  |   return self._browse(ids, self.env, prefetch)
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/models.py", line 4210, in _browse
odoo11-pediando_1  |   @classmethod
odoo11-pediando_1  | File: "/usr/lib/python3/dist-packages/odoo/tools/misc.py", line 922, in dumpstacks
odoo11-pediando_1  |   for line in extract_stack(stack):
```

**Comment by sle-odoo** [comment] 2018-01-06 15:48
@lem8r sadly there's often (always?) performance issues when running an onchange on a one2many containing thousands of lines

you can run a pyflame during the call and analyze where most of the time is spent, if it's outside the orm fixing the code could help, if it's in the orm then well it's more tricky and you should ping @rco-odoo

if you don't care about the onchanges i think you can also disable it in the view (on_change="0" on the concerned fields, to test)

or directly open an opw with a clear scenario to reproduce (a dump of a database will help, or an odoo shell script showing the issue)

**Comment by lem8r** [comment] 2018-01-08 09:09
Thank you for your reply.

At first I thought that this is related to PO's onchange methods so I started to disable them or place break points to see what happening.

In my case it looks like ORM related issue.

Here is an example of events:
1. I edit PO's line qty and press enter to fire onchange
2. call_kw/purchase.order/onchange takes most time (3 minutes)
3. call_kw/purchase.order.line/onchange takes fair amount of time (couple seconds)
4. dozens calls to call_kw/account.tax/search_read (couple seconds) fired by web client no PO's logic.

PO with 3k lines is exceptional case and it is ok to have couple seconds delay but even PO with 100 lines get annoying to work with because of call_kw/purchase.order/onchange and many calls to call_kw/account.tax/search_read

**Comment by lem8r** [comment] 2018-01-08 13:17
Here is 60 seconds pyflame chart of odoo process(multi workers mode) handling PO's onchange

![po-line-onchange](https://user-images.githubusercontent.com/5942291/34672270-80a8866e-f486-11e7-96db-bcc83847a71b.png)

After that I got CPU time limit exception with stacktrace
```bash
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/lem8r/bin/odoo-11.0/odoo/fields.py", line 944, in __get__
    value = record.env.cache.get(record, self)
  File "/home/lem8r/bin/odoo-11.0/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: (<odoo.sql_db.Cursor object at 0x7f33258d9f28>, 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lem8r/bin/odoo-11.0/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/lem8r/bin/odoo-11.0/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/lem8r/bin/odoo-11.0/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/lem8r/bin/odoo-11.0/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/lem8r/bin/odoo-11.0/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/lem8r/bin/odoo-11.0/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/lem8r/bin/odoo-11.0/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/lem8r/bin/odoo-11.0/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/home/lem8r/bin/odoo-11.0/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/lem8r/bin/odoo-11.0/odoo/addons/web/controllers/main.py", line 924, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/lem8r/bin/odoo-11.0/odoo/addons/web/controllers/main.py", line 916, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/lem8r/bin/odoo-11.0/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/lem8r/bin/odoo-11.0/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/lem8r/bin/odoo-11.0/odoo/models.py", line 4963, in onchange
    record.mapped(dotname)
  File "/home/lem8r/bin/odoo-11.0/odoo/models.py", line 4411, in mapped
    recs = recs._mapped_func(operator.itemgetter(name))
  File "/home/lem8r/bin/odoo-11.0/odoo/models.py", line 4390, in _mapped_func
    vals = [func(rec) for rec in self]
  File "/home/lem8r/bin/odoo-11.0/odoo/models.py", line 4390, in <listcomp>
    vals = [func(rec) for rec in self]
  File "/home/lem8r/bin/odoo-11.0/odoo/models.py", line 4657, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/lem8r/bin/odoo-11.0/odoo/fields.py", line 948, in __get__
    self.determine_value(record)
  File "/home/lem8r/bin/odoo-11.0/odoo/fields.py", line 1049, in determine_value
    record._prefetch_field(self)
  File "/home/lem8r/bin/odoo-11.0/odoo/models.py", line 2533, in _prefetch_field
    records = self._in_cache_without(field)
  File "/home/lem8r/bin/odoo-11.0/odoo/models.py", line 4684, in _in_cache_without
    ids1 = set(self.env.cache.get_records(self, field)._ids)
  File "/home/lem8r/bin/odoo-11.0/odoo/api.py", line 1009, in get_records
    for record_id, field_record_cache in self._data[field].items()
  File "/home/lem8r/bin/odoo-11.0/odoo/api.py", line 1010, in <listcomp>
    if field.cache_key(browse(record_id)) in field_record_cache]
  File "/home/lem8r/bin/odoo-11.0/odoo/service/server.py", line 707, in time_expired
    raise Exception('CPU time limit exceeded.')
Exception: CPU time limit exceeded.
```

**Comment by sle-odoo** [comment] 2018-01-10 16:52
@rco-odoo is now working on improving the performance in the purchase's onchange, i'm confident the performance gains will also improve the inventories.

**Comment by Yenthe666** [comment] 2018-01-10 17:00
Good to hear! Best of luck.

**Comment by sle-odoo** [comment] 2018-01-11 14:22
first improvement at rev 309b6b8e5ab476de6f432bbf64939a72af85be3b

**Comment by sle-odoo** [comment] 2018-01-19 14:26
My latest tests show an onchange of 1.5 sec with 500 inventory lines. Can you confirm that you're all facing the same kind of delays?

**Comment by lem8r** [comment] 2018-01-19 18:31
40 secs after 309b6b8 vs 200 secs for 3k PO lines.
Totally doable delay for PO with 200 lines.
Massive improvement in my case.
Thank you!

**Comment by gustavovalverde** [comment] 2018-01-30 13:15
@sle-odoo sorry for the late response, I've been testing with a 430 inventory lines stock adjustment, and I'm having a 6.5 sec delay.

**Comment by rco-odoo** [comment] 2018-02-13 15:58
@gustavovalverde @lem8r I made two commits that might improve the timings:
- ac553f0c466d83487bc1d81716b74f3ddf764704 (faster prefetching)
- fd8bf83bf135928613d8580898b2c63b46c4cb34 (related fields)

Can you give them a try, and tell me about their impact?
Thanks!

**Comment by gustavovalverde** [comment] 2018-02-13 16:01
Interesting. I'll be testing @rco-odoo and let you know.

**Comment by gustavovalverde** [comment] 2018-02-13 18:27
The onchange was 4.7 sec now
![image](https://user-images.githubusercontent.com/16890942/36166768-e93a4316-10c9-11e8-848e-a271b759d2c4.png)

**Comment by lem8r** [comment] 2018-02-23 15:14
@rco-odoo 
Now it's even better. It takes 24 secs to finish POST request for 3k PO lines. 
(It was 40 secs after 309b6b8 and 200 secs before fixes)

**Comment by gustavovalverde** [comment] 2018-06-22 16:22
Just retaking this as today we're working on a pre-production inventory and as the day goes on; each counting is taking longer and longer (we're on 4.5 secs right now).

Is this still a WIP?

**Comment by sle-odoo** [comment] 2018-06-23 07:32
@gustavovalverde there's a branch that could have a major impact on the onchanges delays [here](https://github.com/odoo-dev/odoo/commits/11.0-onchange-rco)

i should test it thoroughly next week but you can already try it, and maybe even report the improvements you're seeing? that'd be nice

**Comment by blaggacao** [comment] 2018-07-21 21:20
Can anyone confirm the following observation:

- I duplicate PO A as `UID=1`. After validating it returns in about 1.5 sec
- I duplicate PO A as `UID!=1`. After validating it returns in about **70 sec**

**Comment by gustavovalverde** [comment] 2018-08-21 12:30
@sle-odoo As far as I'm concerned all changes pointing this issue were Merged. We have a big inventory today so I'll be testing and let you know.

**Comment by DR4RCON** [comment] 2018-12-07 09:17
We have still performace problems in current 11   takes about 5 seconds to change the quantity in an inventory.

**Comment by gustavovalverde** [comment] 2018-12-07 11:06
Yes, this issue still persists cc: @sle-odoo

**Comment by gdgellatly** [comment] 2018-12-07 12:13
@gustavovalverde remove the state field from inventory line view, just with an inherit view. odoo refuses due to stable policy but it fixes inventory and it isn't used anywhere.

**Comment by gustavovalverde** [comment] 2019-10-15 11:27
Is this fixed in v13? cc: @sle-odoo

**Comment by sle-odoo** [comment] 2019-10-15 11:29
It should be, now the default view is a fullscreen editable list so the onchange is triggered on one line at a time.

**Comment by pedrobaeza** [comment] 2019-10-15 11:31
If I don't remember bad, this is got through the smart-button on the top-right of the inventory, that navigates to that editable list.

**Comment by pedrobaeza** [comment] 2019-10-15 11:32
Closing this then through that "workaround".

**Closed by pedrobaeza** 2019-10-15 11:32 UTC
Labels: 11.0, Logistics

**Comment by sle-odoo** [comment] 2019-10-15 11:33
the stat button is present in 11 and 12, in 13 it's the default behavior
