### ISSUE TITLE
not able to create a product with image in odoo 9

### ISSUE THREAD

**Issue by omalbastin** [odoo/odoo#9350] opened 2015-11-01 14:12 UTC
To recreate the issue, click on the create button, specify the product name, add the product image then save it. It will show missing record error:"Record does not exist or has been deleted. "

**Comment by cricketmerchant** [comment] 2016-01-09 02:22
We are getting the same issue and were able to replicate. Any fix for this?

**Comment by lukebranch** [comment] 2016-01-09 02:53
@omalbastin @cricketmerchant ,

I'm only an odoo user like yourselves, however from my personal experience this usually happens when you've removed a module and the server still has a record (like a menuitem) in cache.

I've usually been able to resolve this by restarting the odoo-server or manually removing the menuitem (if it has been left behind by a community module).

Turn on your debug logs in /etc/odoo-server.conf and do a:

sudo tail -f /var/log/odoo/odoo-server.log

and try and reproduce the error and watch the logs in your terminal screen. The debug logs are a great way to pinpoint the issue.

If you report an issue you need to provide full steps to reproduce so that Odoo can try to replicate the issue on their own instance (usually the latest runbot).

In this case it does not sound like a bug with Odoo 9 core, and rather a a bug with a module you've installed, or similar. If you find it it not a bug with one of the Odoo core modules I would suggest closing this issue and creating an issue with the module developer with the contents of your debug log's error when you reproduce it and steps to reproduce for them.

**Comment by cricketmerchant** [comment] 2016-01-09 06:17
The issue also seems to exist in runbot.odoo.com Will try your suggested steps. 

Here are the steps:

1. Go to Inventory App



2. Click on Inventory Control menu and than click on Products submenu



3. Click on CREATE button




4. Enter a test product name and add image and click SAVE




5. Odoo will throw an error as displayed below.. The error will still appear even after filling in all necessary new product data and upon clicking on SAVE. 



—
Thanking you with regards, 

Sales 
Cricket Merchant LLC | Elevates Your Game!!!
http://www.cricketmerchant.com <http://www.cricketmerchant.com/> 
Email: sales@cricketmerchant.com <mailto:sale@cricketmerchant.com> 

 <https://www.facebook.com/cricket.merchant>Now find us everywhere!!!

**Comment by lukebranch** [comment] 2016-01-09 06:40
@cricketmerchant ,

What I would suggest is create an animated GIF using a free program like licecap:

http://www.cockos.com/licecap/

showing the issue in the runbot.

For what it's worth I have attempted to reproduce the issue using your steps and have not been able to reproduce the issue on the latest 9.0 runbot.

Please see my screenshot from below (using Chrome 47.0.2526.106 (64-bit) in OSX Yosemite).

<img src="https://cloud.githubusercontent.com/assets/2337666/12214837/ef3d2130-b6de-11e5-8ced-5bda022cefb6.png"/>

**Comment by lukebranch** [comment] 2016-01-09 06:46
@cricketmerchant ,

On a seperate note I notice you're using Magento for your website. I'd suggest taking a look at this server setup script:

https://github.com/zach-adams/hgv-deploy-full

it's designed for Wordpress but can be used for Magento as many of the same rules apply.

HHVM compiles the PHP into machine code making more efficient use of your server resources, and allows for faster page load times. Combined with Varnish and this Magento module:

https://www.magentocommerce.com/magento-connect/pagecache-powered-by-varnish.html

I've found it drastically improves magento performance. Obviously do not put this into production until you have thoroughly tested it, however i'm using this setup (slightly modified) to great success with many of my Magento projects.

I'd recommend looking into implementing the provided VCL bundled with the Magento module.

**Comment by cricketmerchant** [comment] 2016-01-10 00:57
Hi Luck,
cricketmerchant.com is on Magento however, that is not in odoo. We are deploying macecricket.com in Enterprise Odoo

Here is the runbot screen shot for enterprise version and it still shows the same error..
Just two thing to add after clicking on create button. Product name and Picture, hit save, you will see the error. 



—
Thanking you with regards, 

Sales 
Cricket Merchant LLC | Elevates Your Game!!!
http://www.cricketmerchant.com <http://www.cricketmerchant.com/> 
Email: sales@cricketmerchant.com <mailto:sale@cricketmerchant.com> 

 <https://www.facebook.com/cricket.merchant>Now find us everywhere!!!

**Comment by omalbastin** [comment] 2016-01-10 03:27
@cricketmerchant , as you have enterprise code, i think you are partner of odoo. If can reach to odoo support team, please do that. Otherwise we can wait for the support.

**Comment by manojbh** [comment] 2016-05-10 12:04
Did you solve the problem? I came across this same problem.

**Comment by Yenthe666** [comment] 2018-02-14 10:57
Hey all,

I was no longer able to reproduce this issue.
Please update your Odoo source code to the latest version if you still face this issue. If you can still reproduce it afterwards then please make a video to demonstrate the behaviour.

Regards,
Yenthe

**Closed by Yenthe666** 2018-02-14 10:57 UTC
