### ISSUE TITLE
TypeError when adding a new customer 

### ISSUE THREAD

**Issue by frantischek** [odoo/odoo#66378] opened 2021-02-17 14:44 UTC
Impacted versions:14
Current behavior: I wanted to add a new customer. This also happens when I try to open a allready existing customer.

Error is: 
TypeError: field_utils.format[(formatType || this.formatType)] is not a function
    at Class._formatValue (http://fraumartha:8069/web/static/src/js/fields/abstract_field.js:392:65)
    at Class._render (http://fraumartha:8069/web/static/src/js/fields/basic_fields.js:2660:25)
    at http://fraumartha:8069/web/static/src/js/fields/abstract_field.js:209:25

**Comment by pedrobaeza** [comment] 2021-02-17 14:45
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by frantischek** [comment] 2021-02-17 14:49
Hi. I can't reproduce it and I think you are right with community module. In my case I think that my contract module makes this problems. I tried to update it, but it's not working. Can you please tell me how to remove it? I also have ssh access to the server. Thanks!

**Comment by Yenthe666** [comment] 2021-02-17 15:07
Please ask these kind of questions on the official help forums (at help.odoo.com). :)

**Closed** 2021-02-17 15:06 UTC
Labels: Need information
