### ISSUE TITLE
Inherit website_sale.products_categories broke categories list toogle

### ISSUE THREAD

**Issue by hustlercoder** [odoo/odoo#35954] opened 2019-08-22 09:27 UTC
Impacted versions: 12

Steps to reproduce: Try to create a module that add custom properties to product categories list(products_grid_before). When you install your module the toogle is there but when you turn it on...nothing happen..obvs if you remove the custom module that inherit from website_sale.products_categories everything is working good.

My implementation:
`<template id="s_shop_categories" inherit_id="website_sale.products_categories">
		<xpath expr="//div[@id='products_grid_before']" position="replace">
            <div class="vertical-menu" id="products_grid_before">
                <ul class="nav nav-pills flex-column mt16" id="o_shop_collapse_category">
                    <li class="nav-item">
                        <a t-att-href="keep('/shop',category=0)" t-attf-class="nav-link#{'' if category else ' active'} o_not_editable">All Products</a>
                    </li>
                    <t t-foreach="categories" t-as="categ">
                        <t t-call="website_sale.option_collapse_categories_recursive" />
                    </t>
                </ul>
            </div>
        </xpath>
    </template>`

Current behavior: website_sale.products_categories inherited broke the odoo function to list categories in the shop page

If you put the website_sale module as dependency in manifest file and you already had install the website_sale module and setup everything(like categories,products....) the custom module doesn't work(the toogle on shop page)...but if you install the custom module on a fresh db with nothing installed...and with website_sale dependency and configure all things after install the module  the toogle works...its very strange...
Expected behavior: A fix to this situation.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2019-08-22 09:51
Sorry, but the error you are mentioning corresponds to custom code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2019-08-22 09:51 UTC
Labels: 12.0, Website
