### ISSUE TITLE
Issue with merging .png files in .pdf through Pillow 6.0.0 in Odoo 12 (CE)

### ISSUE THREAD

**Issue by jarvee1** [odoo/odoo#34847] opened 2019-07-15 07:34 UTC
Impacted versions:

Odoo 12 CE, Pillow 6.0.0

Steps to reproduce:

I've created the project outside of Odoo with the same virtual environment which I use in Odoo and png files were merged successfully in one pdf file. 

Current behavior:

When I run the method from Odoo I'm getting this message:

File ".../models/sale_order_line.py", line 261, in generateLabel
    image_files[0].save(filename, "PDF", resolution=100.0, save_all=True, append_images=image_files[1:])
  File "/...virt/lib/python3.7/site-packages/PIL/Image.py", line 1994, in save
    save_handler = SAVE_ALL[format.upper()]
KeyError: 'PDF'

Expected behavior:

I expect that png files will be merged in one pdf.

Video/Screenshot link (optional):

To reproduce the issue I added this method on github, you could just copy this method ('test') and run from Odoo: https://github.com/jarvee1/test/blob/master/pil

**Comment by pedrobaeza** [comment] 2019-07-15 07:40
Sorry, but the error you are mentioning corresponds to a custom code, so the problem is a misuse of existing tools. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

**Closed by pedrobaeza** 2019-07-15 07:40 UTC
