### ISSUE TITLE
[9.0] enterprise: Real Time Valuation Completely broken/untested

### ISSUE THREAD

**Issue by nhomar** [odoo/odoo#8873] opened 2015-10-03 07:56 UTC
Hello All @antonylesuisse @fpodoo.

We use real time valuation in all our customers and mandatory (no-go feature) to not have it correctly working, I feel like this is a joke my dear fellows.

1. All tests were removed from stock_account then we have a module stock_account completly untested.
2. The most simple case is broken.

What did i try?

Create a new product with minimal information:

1.- Name: Product A.
2.- 'All' category for product marked as Real Time.
(Not set stock input and output accounts).
3.- Make a normal purchase of Product.
4.- Try to receive them.

First Error, a non-readable error is shown:
---

![error validating.](https://www.evernote.com/l/AJ7PwOFw8_ZK0IZT6gVWMoKSUytIvbkDGpUB/image.png)

Then the error with technical knowledge is pretty obvious, I go to the category and fix the accounting configuration.

![Configuration on product categories.](https://www.evernote.com/l/AJ4tyH-kewdAnLG__CSLJ6-xTSnanA1mAjoB/image.png)

Then what i got?:
---

Picking is correctly validated but the account move shows 0 on Debit and Credit (which is already validated in some countries as invalid and solved in previous versions).

![Stock Move](https://www.evernote.com/l/AJ7EvTOyHnxJEaa__WJX7DZwu_xSz0U1mUoB/image.png)

Then I said myself: Wao I must be doing something really wrong, let me read the tests to validate what is wrong on my weay to set things.

What is my surprise?: The test was completelly deleted, and it was a test of simple 40 lines.

Tests on stock account: 
9.0: No tests folder.

https://github.com/odoo/odoo/tree/9.0/addons/stock_account

8.0: Simple tests (they need to be finished not removed dudes).

https://github.com/odoo/odoo/tree/8.0/addons/stock_account

**Comment by danimaribeiro** [comment] 2015-10-03 17:50
I see your concerns about unit tests.
I've created an issue here about this.
https://github.com/odoo/odoo/issues/8878

**Comment by jco-odoo** [comment] 2015-10-04 12:50
@nhomar, is it possible that as you created a new product, the standard price is 0 and as it is standard price, the price  does not change and remains 0?  I don't remember a test that checks whether it is 0.  

@qdp-odoo, could you have a look at this also?

**Comment by nhomar** [comment] 2015-10-04 17:04
@jco-odoo Wehave 2 parts of the problem.

1.- The fact that the accounting allow 0-0
2.- Wrongly taken the cost from??, because this Account move is the result of a purchase - picking, thene the picking should bring the cost on the PO and IF Average, AML have one behavior, and FIFO, LIFO another behavior, and Standard Another behavior.

That's why unittest re so important.. to be sure ;-) 

I hope it helps

**Comment by lem8r** [comment] 2015-10-04 18:12
During my tests on perpetual stock valuation Odoo was doing correct journal entries on stock moves if product price is set correctly on PO and invoice.

Maybe there is no test to avoid zero cost?

And journal entries should not be posted by default. There should be the way to check entries before freezing them which is currently impossible.

The worst thing is this https://github.com/odoo/odoo/issues/8872 which is doing wrong journal entries on vendor bill and there is no way to create bill manually based on PO.

**Comment by qdp-odoo** [comment] 2015-10-07 15:44
I don't get where exactly you see an issue on the stock valuation, Nhomar. For me, if your making a perpetual valuation with cost method = standard price and your standard price is 0 it's "normal" to have 0 debit/credit. Normal in the way that it's the expected behavior, but more than probably a wrong configuration. So we gonna raise an error if that's the case.

So, for what i've tested, 
1) if you're on perpetual valuation, your accounting moves are correctly created for each incoming/outgoing stock move
2) if the cost method of your product/product category is 
 * standard: it takes the valuation cost as the standard price of the product (0 by default but, he, that's the expected behavior)
 * average: it takes the valuation cost as the standard price of the product (but the standard price is updated for each, so it's the expected behavior)
 * real cost: it takes the valuation cost as the PO cost

Can you share a use case where the issue (issues?) you're talking about is (are?) visible? Or was it only about avoiding 0 in stock valuation entries?

Also i don't find any test available on stock_account for v8, following the link you provided. Where were they?

**Comment by kovika** [comment] 2015-10-14 05:45
Dera qdp-odoo

Tried on saas.

Make a product : product 1 in category all, standard price 0
Category all: perpetual valuation, based on real price
Make PO with product 1: 10 pcs, 100 Euro/pcs, VAT lets say 20% PO Sum: Net: 1000 Euro , Gross 1200 Euro
Validated, picked (whole at once). Make invoice from PO (by the way i miss very much the make invoice from picking feature, cause our vendors allways make invoices from deliveries)

Check inventory value: 10.000 Euro (thats 10 pcs * 10 pcs * 100 Euro)
If you dont use VAT, inventory value is 1.000 (correctly)

**Comment by qdp-odoo** [comment] 2015-10-14 16:03
@kovika: well seen. It has been fixed in revision 64a6a84

the patch to disallow valuation_amount at 0 landed on ddbe0e1

thanks for the contribution

**Closed by qdp-odoo** 2015-10-14 16:03 UTC

**Comment by nhomar** [comment] 2015-10-14 17:05
@qdp-odoo 

The issue have 2 parts.

1. The fact that the use case you describe is not in any unittest that I could see, then part of the issue is the leak of tests.
2. About if it is fixed or not I will try and come back to give a more valuable feedback.
3. About Account moves with 0 - 0, I am not sure if it is usable have such o/o moves.
4. Other part is the incorrect management of the error where if you do not have th right accounts configured, the error message is so technical.

Did this commit solved all this points?

Thanks.

**Comment by kovika** [comment] 2015-10-15 05:53
@qdp-odoo

Thank You! That was fast. Now the value calculated correctly.
Would be good if default purchase tax written in po line, like SO line, but it not belongs here.

Thank you again

**Comment by qdp-odoo** [comment] 2015-10-16 07:59
@nhomar : this commit solve your point 4: https://github.com/odoo/odoo/commit/af0f33a4759b8f3adfd7f9a448be5f63994e9f1f
The rest is fine for me because I cannot consider the lack of tests as a bug, so let's move on... although I agree with you that it should be improved asap.

@kovika: I fixed that in revision c192095. But next time try to report new bugs in new issues, because otherwise it's such a mess

Thanks
