### ISSUE TITLE
Error on Creating Invoice

### ISSUE THREAD

**Issue by rjay1018** [odoo/odoo#45890] opened 2020-02-21 07:40 UTC
Impacted versions: V11

Steps to reproduce: During creation of invoice

Current behavior: Error Popup when creating invoice

Expected behavior:

Video/Screenshot link (optional):
![Screenshot(3)](https://user-images.githubusercontent.com/5526244/75014034-68631780-54c0-11ea-84a4-1c95eb58b76d.png)

**Comment by pedrobaeza** [comment] 2020-02-21 07:42
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by william-andre** [comment] 2020-02-21 12:36
You most likely inherited `def _get_current_sequence(self, sequence_date=None)` from `ir.sequence` in a custom module without putting the optional parameter in the signature.
There is no issue in 11.0 code.

**Closed by william-andre** 2020-02-21 12:36 UTC
Labels: Need information

**Comment by rjay1018** [comment] 2020-02-24 10:07
Hi Pedro,

Thank you for your reply, I will check on the custom modules deployed in
the server.  It think that will be a good start on tracking the error.

Thanks
