### ISSUE TITLE
Error saving in res.partner

### ISSUE THREAD

**Issue by smartboxid** [odoo/odoo#21050] opened 2017-11-18 03:39 UTC
Impacted versions:11.0

Steps to reproduce:Add new address type "Other" and save, while saving partner it will give error

Current behavior:

Expected behavior:

Video/Screenshot link (optional):
in res_partner.py
        
286:        if partner_type in ['other'] and parent_id:
287:            parent_image = self.browse(parent_id).image
288:            image = parent_image and parent_image.decode('base64') or None

change to:

286:        if partner_type in ['other'] and parent_id:
287:            parent_image = self.browse(parent_id).image
288:            image = parent_image and base64.b64decode(parent_image) or None

**Comment by Yenthe666** [comment] 2017-11-18 15:50
Hi @smartboxid,

Thanks for the report. I can confirm that this is a bug:
![image](https://user-images.githubusercontent.com/6352350/32982076-fff7ee3a-cc7e-11e7-95fe-3db47a1e5ec0.png)
I've made a PR at https://github.com/odoo/odoo/pull/21055 to handle this.

**Comment by Yenthe666** [comment] 2017-11-19 08:29
Also, duplicate of https://github.com/odoo/odoo/issues/21021#issuecomment-345474454 so not sure why you,ve reported it twice. 
@Elkasitu this is the duplicate of where you commented on. See the link to a PR in my previous comment.

**Comment by smartboxid** [comment] 2017-11-21 02:19
I'm sorry, I've reported for the first time but soon closed by @Elkasitu so I opened new report, but soon after my second report, the first is opened again.

**Closed** 2017-11-21 09:01 UTC
Labels: 11.0, confirmed
