### ISSUE TITLE
[9.0] stock_picking check availability  bug

### ISSUE THREAD

**Issue by leopard7777777** [odoo/odoo#11473] opened 2016-03-25 03:48 UTC
Impacted versions:
- 9.0

Steps to reproduce:
1. make two sale orders with  same product
2. purchase and put goods on different shelfs (WH/STOCK/z1-1, WH/STOCK/z1-2)
3. confirm A and B sale_order ,then make picking order(Pick),and check availability them 
4. stock_pack_oparetion's from_location is WH/STOCK/z1-1
5. finish one of picking order, another picking order will be waiting available,because there is not product on WH/STOCK/z1-1
6. PAGE OF OPERATIONS is invisible when state is 'confirmed',but the stock_pack_oparetion record still exists with from_location is WH/STOCK/z1-1
7. then check availability isn't able to work,because from_location is fix (stock/stock.py :2424 - :2452)

if change stock shelf of product ,it also will cause the bug.

PS: I delete stock_pack_oparetion records of this picking order, then check it . WH/STOCK/z1-2 is available

Current behavior:
- check availability doesn't work

Expected behavior:
- when state is 'confirmed' and stock_pack_oparetion are exists, remove stock_pack_oparetion records

Thanks,

**Comment by pedrobaeza** [comment] 2018-04-17 23:58
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-04-17 23:58 UTC
Labels: 9.0, Logistics
