### ISSUE TITLE
9.0 BUG Odoo Client Error, Kanban buggy

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#10398] opened 2016-01-11 10:35 UTC
In hr recruitment when move applicant getting bug in odoo 9.0

Odoo Client Error
Uncaught TypeError: Cannot read property '$el' of undefined
http://119.162.77.99:8069/web/content/765-d2485be/web.assets_backend.js:6965
Traceback:
TypeError: Cannot read property '$el' of undefined
    at HTMLDivElement.$el.sortable.update (http://119.162.77.99:8069/web/content/765-d2485be/web.assets_backend.js:6965:467)
    at $.Widget._trigger (http://119.162.77.99:8069/web/content/403-a0e6d4e/web.assets_common.js:1146:75)
    at $.widget._trigger (http://119.162.77.99:8069/web/content/403-a0e6d4e/web.assets_common.js:1513:109)
    at null._trigger (http://119.162.77.99:8069/web/content/403-a0e6d4e/web.assets_common.js:1124:334)
    at null.<anonymous> (http://119.162.77.99:8069/web/content/403-a0e6d4e/web.assets_common.js:1500:217)
    at $.widget._clear (http://119.162.77.99:8069/web/content/403-a0e6d4e/web.assets_common.js:1511:77)
    at null._clear (http://119.162.77.99:8069/web/content/403-a0e6d4e/web.assets_common.js:1124:334)
    at $.widget._mouseStop (http://119.162.77.99:8069/web/content/403-a0e6d4e/web.assets_common.js:1428:136)
    at null._mouseStop (http://119.162.77.99:8069/web/content/403-a0e6d4e/web.assets_common.js:1124:334)
    at $.widget._mouseUp (http://119.162.77.99:8069/web/content/403-a0e6d4e/web.assets_common.js:1160:6)

**Comment by dsu-odoo** [comment] 2016-01-11 10:40
Not reproducible, could you please be more specific!!

**Comment by tejastank** [comment] 2016-01-11 10:53
In HR Applications.

Created new stages for first phase, second phase, hr phase...
then I try to move kanban card to other phase. It generate above bug..

Also we getting below messages again and again....


caught TypeError: Cannot read property 'appendChild' of undefined
http://xxxxxxxxxxxxx:8069/web/content/403-a0e6d4e/web.assets_common.js:1462
Traceback:
TypeError: Cannot read property 'appendChild' of undefined

**Comment by dsu-odoo** [comment] 2016-01-11 11:07
I followed your scenario but still it's not reproducible at my end with latest update of 9.0

**Comment by jessica-oa** [comment] 2016-01-22 13:21
This happens to me too when I move the tickets too fast.

**Comment by tejastank** [comment] 2016-01-22 13:44
Yup, we /& clients face same at many kanban views...

**Comment by jessica-oa** [comment] 2016-01-26 07:39
Error messages I get on https://demo3.odoo.com on a Project, when I move the tasks between stages a few times fast.
![image](https://cloud.githubusercontent.com/assets/8638531/12574867/66042bfe-c410-11e5-97dc-f69f48e48251.png)

AND

Uncaught TypeError: Cannot read property 'appendChild' of undefined
https://demo3.odoo.com/web/content/1171-c7b63d7/web.assets_common.js:1462
Traceback:
TypeError: Cannot read property 'appendChild' of undefined
    at $.widget._createHelper (https://demo3.odoo.com/web/content/1171-c7b63d7/web.assets_common.js:1462:835)
    at null._createHelper (https://demo3.odoo.com/web/content/1171-c7b63d7/web.assets_common.js:1124:334)
    at $.widget._mouseStart (https://demo3.odoo.com/web/content/1171-c7b63d7/web.assets_common.js:1400:226)
    at null._mouseStart (https://demo3.odoo.com/web/content/1171-c7b63d7/web.assets_common.js:1124:334)
    at $.widget._mouseMove (https://demo3.odoo.com/web/content/1171-c7b63d7/web.assets_common.js:1158:88)
    at null._mouseMove (https://demo3.odoo.com/web/content/1171-c7b63d7/web.assets_common.js:1124:334)
    at HTMLDocument._mouseMoveDelegate (https://demo3.odoo.com/web/content/1171-c7b63d7/web.assets_common.js:1155:53)
    at HTMLDocument.jQuery.event.dispatch (https://demo3.odoo.com/web/content/1171-c7b63d7/web.assets_common.js:740:451)
    at HTMLDocument.elemData.handle (https://demo3.odoo.com/web/content/1171-c7b63d7/web.assets_common.js:713:173)

**Comment by qsm-odoo** [comment] 2016-05-13 14:05
Hello, this issue has been fixed in 9.0 with commit https://github.com/odoo/odoo/commit/068acf76daef7e7145520b0bb1f7103656fa7885

**Closed by qsm-odoo** 2016-05-13 14:05 UTC

**Comment by tejastank** [comment] 2016-05-19 06:04
Thanks for quick fixes on enterprise bugs.

**Comment by alfieqashwa** [comment] 2017-05-04 14:32
https://apps.openerp.com/web/content/1443101-3f91498/web.assets_backend.js:1719

Same error. 
any help? 
Thanks

**Comment by hunterhn** [comment] 2017-05-05 20:11
https://github.com/odoo/odoo/issues/10398#issuecomment-299202824

i have this same error, with odoo 10

**Comment by qupro** [comment] 2017-05-10 17:08
Similar in Odoo version 9.0c-20170510 (Community Edition):

Uncaught TypeError: Cannot read property '$el' of undefined

https://apps.openerp.com/web/content/1443101-3f91498/web.assets_backend.js:1719
Traceback:
TypeError: Cannot read property '$el' of undefined
    at https://apps.openerp.com/web/content/1443101-3f91498/web.assets_backend.js:1719:1100
    at https://apps.openerp.com/web/content/1442937-ea2658f/web.assets_common.js:547:681
    at fire (https://apps.openerp.com/web/content/1442937-ea2658f/web.assets_common.js:541:299)
    at Object.fireWith [as resolveWith] (https://apps.openerp.com/web/content/1442937-ea2658f/web.assets_common.js:546:198)
    at https://apps.openerp.com/web/content/1442937-ea2658f/web.assets_common.js:547:874
    at fire (https://apps.openerp.com/web/content/1442937-ea2658f/web.assets_common.js:541:299)
    at Object.fireWith [as resolveWith] (https://apps.openerp.com/web/content/1442937-ea2658f/web.assets_common.js:546:198)
    at deferred.(anonymous function) (https://apps.openerp.com/web/content/1442937-ea2658f/web.assets_common.js:548:56)
    at fire (https://apps.openerp.com/web/content/1442937-ea2658f/web.assets_common.js:541:299)
    at Object.add [as done] (https://apps.openerp.com/web/content/1442937-ea2658f/web.assets_common.js:542:467)

Could be releated with these issue?
https://github.com/odoo/odoo/issues/10157 or this https://github.com/odoo/odoo/issues/14639
All try to get web.assets_backend with success

**Comment by tejastank** [comment] 2017-06-19 05:32
@Yenthe666 you had potential chance to detect this, as useless you close all bugs without facing it.
I think in case you not face this, sure you close this too.

Odoo &  @Yenthe666  jointly had bad response to community or users.

**Comment by okbanouri** [comment] 2018-06-29 10:32
Hello, I know it's kinda too late, but i am having the same issue in Odoo 11.0, and i found out that this error happen after updating the stage of applicant that has empty Responsible field. so this error will be fixed by simply assigning a Responsible to the applicant.

**Comment by Yenthe666** [comment] 2018-06-29 10:34
@okbanouri if you can reproduce it on V11 & can reproduce it on the runbot then please do create a new bug report.

**Comment by okbanouri** [comment] 2018-06-29 10:47
Thanks @Yenthe666 , but i couldn't reproduce it on the runbot.
