### ISSUE TITLE
[13.0] Can't create hr.resume.line tree view

### ISSUE THREAD

**Issue by andreasanggaraa** [odoo/odoo#68856] opened 2021-04-07 05:24 UTC
Impacted versions: 13.0

Steps to reproduce:
On runbot.odoo.com v13.0:
 1. Create new view (Settings > Technical > User Interface > View > Create)
![image](https://user-images.githubusercontent.com/59552116/113813990-2025b800-979b-11eb-8979-1e0d5c176979.png)
2. Click 'Open Views' on Developer Tools (bug icon).
3. Search 'resume' and click the views we just created.

Current behavior:
On runbot.odoo.com v13.0 this error occurs:
```Traceback:
TypeError: Cannot read property 'type' of undefined
    at Class._extractAttributes (https://7052107-13-0-all.runbot34.odoo.com/web/content/1609-089c78e/web.assets_backend.js:1496:80)
    at https://7052107-13-0-all.runbot34.odoo.com/web/content/1609-089c78e/web.assets_backend.js:1505:6
    at Function._.each._.forEach (https://7052107-13-0-all.runbot34.odoo.com/web/content/1577-7f3030c/web.assets_common.js:108:558)
    at Class._parseSearchArch (https://7052107-13-0-all.runbot34.odoo.com/web/content/1609-089c78e/web.assets_backend.js:1500:704)
    at Class.init (https://7052107-13-0-all.runbot34.odoo.com/web/content/1609-089c78e/web.assets_backend.js:1492:1159)
    at Class.prototype.<computed> [as init] (https://7052107-13-0-all.runbot34.odoo.com/web/content/1577-7f3030c/web.assets_common.js:3861:488)
    at new Class (https://7052107-13-0-all.runbot34.odoo.com/web/content/1577-7f3030c/web.assets_common.js:3862:65)
    at Class._createControlPanel (https://7052107-13-0-all.runbot34.odoo.com/web/content/1609-089c78e/web.assets_backend.js:1079:157)
    at Class.getController (https://7052107-13-0-all.runbot34.odoo.com/web/content/1609-089c78e/web.assets_backend.js:1075:678)
    at Class.prototype.<computed> [as getController] (https://7052107-13-0-all.runbot34.odoo.com/web/content/1577-7f3030c/web.assets_common.js:3861:488)
```

On local, I tried to use code instead of UI, this error occurs:

```
Traceback:
Error: can't access property "type", this.fields[attrs.fieldName] is undefined
_extractAttributes@http://localhost:8069/web/content/3523-7a2ab80/web.assets_backend.js:1496:34
_parseSearchArch/<@http://localhost:8069/web/content/3523-7a2ab80/web.assets_backend.js:1505:6
_.forEach@http://localhost:8069/web/content/3522-8935baa/web.assets_common.js:108:566
_parseSearchArch@http://localhost:8069/web/content/3523-7a2ab80/web.assets_backend.js:1500:704
init@http://localhost:8069/web/content/3523-7a2ab80/web.assets_backend.js:1492:1159
OdooClass.extend/</prototype[name]</<@http://localhost:8069/web/content/3522-8935baa/web.assets_common.js:3861:488
Class@http://localhost:8069/web/content/3522-8935baa/web.assets_common.js:3862:65
_createControlPanel@http://localhost:8069/web/content/3523-7a2ab80/web.assets_backend.js:1079:157
getController@http://localhost:8069/web/content/3523-7a2ab80/web.assets_backend.js:1075:678
OdooClass.extend/</prototype[name]</<@http://localhost:8069/web/content/3522-8935baa/web.assets_common.js:3861:488
_createViewController/def<@http://localhost:8069/web/content/3523-7a2ab80/web.assets_backend.js:441:780
_createViewController@http://localhost:8069/web/content/3523-7a2ab80/web.assets_backend.js:441:721
_executeWindowAction/</<@http://localhost:8069/web/content/3523-7a2ab80/web.assets_backend.js:446:169
```

Expected behavior:

Show tree view on model 'hr.resume.line' like other model.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment] 2021-04-07 06:41
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2021-04-07 06:41 UTC
