### ISSUE TITLE
Translations broken in country localizations of spanish(es)

### ISSUE THREAD

**Issue by icoro** [odoo/odoo#28217] opened 2018-10-26 22:56 UTC
Impacted versions: V12

Steps to reproduce:

When I create a DB in the generic spanish (es) translations work fine, but when I change to a country localization like es_BO, many translated terms are broken and reverted to english even though the generic spanish(es) translation is fine.

**Comment by celm1990** [comment] 2018-10-26 23:16
@icoro issue duplicate of #27992 please try with latest code and if problem persist reopen original issue for tracking

**Closed** 2018-10-27 00:14 UTC
