### ISSUE TITLE
Login with session.authenticate error user_agent_env

### ISSUE THREAD

**Issue by daolvcntt** [odoo/odoo#62986] opened 2020-12-08 06:55 UTC
I'm using odoo 14, and i did use function but it show error TypeError: _login() got an unexpected keyword argument 'user_agent_env' - - -
Please help me

`request.session.authenticate(request.session.db, request.params['login'], request.params['password'])

result = super(IrHttp, cls)._dispatch()

File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 241, in _dispatch

return cls._handle_exception(e)

File "/usr/lib/python3/dist-packages/odoo/addons/utm/models/ir_http.py", line 34, in _handle_exception

response = super(IrHttp, cls)._handle_exception(exc)

File "/usr/lib/python3/dist-packages/odoo/addons/http_routing/models/ir_http.py", line 602, in _handle_exception

return super(IrHttp, cls)._handle_exception(exception)

File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 209, in _handle_exception

return request._handle_exception(exception)

File "/usr/lib/python3/dist-packages/odoo/http.py", line 744, in _handle_exception

return super(HttpRequest, self)._handle_exception(exception)

File "/usr/lib/python3/dist-packages/odoo/http.py", line 315, in _handle_exception

raise exception.with_traceback(None) from new_cause

TypeError: _login() got an unexpected keyword argument 'user_agent_env' - - -

**Comment by pedrobaeza** [comment] 2020-12-08 10:30
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by daolvcntt** [comment] 2020-12-08 14:08
@pedrobaeza thank u. I do fix done, because v14 did update function _login more a param

**Closed** 2020-12-08 14:24 UTC
Labels: Need information

**Comment by Guttappa1238** [comment] 2022-02-15 05:56
Hi im getting this error while restricting single user for login in odoo14.

i'm trying this app
https://apps.odoo.com/apps/modules/13.0/restrict_logins/

please help me out

```
uid = cls._login(db, login, password, user_agent_env=user_agent_env)
TypeError: _login() got an unexpected keyword argument 'user_agent_env'
```

**Comment by shams-aalogics** [comment] 2024-02-22 07:45
add user_agent_env={'interactive': True} as a parameter, like return super(Users, cls)._login(db, login, password,user_agent_env={'interactive': True})
