### ISSUE TITLE
[14.0] Website text editor is not reachable

### ISSUE THREAD

**Issue by bahram-ashrafi** [odoo/odoo#69097] opened 2021-04-11 10:40 UTC
Impacted versions: 14.0

Steps to reproduce: on edit mode

Current behavior: hidden

Expected behavior: visible

Video/Screenshot link (optional):
https://www.awesomescreenshot.com/video/3339926?key=888ac6c0aef4a54c1624b70fdade35a9

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment] 2021-04-11 11:05
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by bahram-ashrafi** [comment] 2021-04-11 12:22
this test was on runbot. I sent a video. can you see it?

**Comment by bahram-ashrafi** [comment] 2021-04-12 06:15
@pedrobaeza

**Comment by pedrobaeza** [comment] 2021-04-12 06:18
Please don't hammer me doing pings. I'm not able to reproduce the problem:

![Peek 12-04-2021 08-17](https://user-images.githubusercontent.com/7165771/114349037-a78e7500-9b67-11eb-8db1-4b4cedd2fcef.gif)

**Comment by bahram-ashrafi** [comment] 2021-04-12 08:20
![Screenshot from 2021-04-12 12-43-49](https://user-images.githubusercontent.com/39516328/114362939-1fbb6180-9b8d-11eb-8f59-4df2d0edcd91.jpg)
Here is a editor for text. for changing font-size and some options for texts that now is hidden. if scroll mouse on here you will see them.

**Comment by pedrobaeza** [comment] 2021-04-12 09:34
I'm not able to find the problem. @Yenthe666 maybe you do?

**Comment by Yenthe666** [comment] 2021-04-13 05:17
I'm sorry but everything works at my end too

**Comment by kig-odoo** [comment] 2021-04-13 07:41
Not sure this needs to be fix or not. but @pedrobaeza @Yenthe666  you guys can decide whether it should consider as a bug or not.

I think it works well in a device that has 1920 x 1080 or Higher resolution.
The issue might be in the devices that have 1600 x 900 (HD+) or lower resolution.

@bahram-ashrafi What Is Your Screen Resolution?
If it's 1920 x 1080 or Higher resolution then make sure that your browser is having a 100% zoom scale set.
![image](https://user-images.githubusercontent.com/22187704/114514933-73937c80-9c59-11eb-8fef-7390eb899f04.png)

**Comment by bahram-ashrafi** [comment] 2021-04-13 07:42
I hope this video clearly show problem
https://www.awesomescreenshot.com/video/3360514?key=5a5ee427cf91afbf618c137ecef13eed

**Comment by bahram-ashrafi** [comment] 2021-04-13 07:47
@kig-odoo 
Zoom is on 100%.
My screen resolution is 1600*900

**Comment by zahra-np** [comment] 2021-04-13 12:32
I have this problem too!

**Comment by pedrobaeza** [comment] 2021-04-13 14:38
OK, so summarizing, the problem is when the block has a height options dialog box that overpasses the screen height, letting no space to the other dialog box.

Tagging the issue and doing ping to @qsm-odoo as possible interested in this.

**Comment by qsm-odoo** [comment] 2021-04-13 15:55
Whoa. We recently merged fixes on those text tools to be able to reach all options of opened dropdowns... but don't know how we have missed this issue (well actually I know: I rarely test the editor in small height windows :grimacing:). I will fix this asap :+1:

**Closed** 2021-04-13 18:09 UTC
Labels: 14.0, Web editor

**Comment by pedrobaeza** [comment] 2021-04-13 18:13
Thanks for the quick patch, Quentin!
