### ISSUE TITLE
elearning 

### ISSUE THREAD

**Issue by fastcomsa** [odoo/odoo#55288] opened 2020-08-01 16:48 UTC
Impacted versions: Odoo 13 Enterprise

Steps to reproduce: Go to https://fastcom-sa1.odoo.com/slides > select any course posted > click on any lesson listed >by default, lessons open in fullscreen mode

Current behavior: An error window pop up and lesson content is not visible. The error:  

Error:

**Rastreo de error:
TypeError: Cannot read property 'indexOf' of undefined
    at https://fastcom-sa1.odoo.com/web/content/3833-9b303fe/1/web.assets_frontend_lazy.js:264:488
    at Array.forEach (<anonymous>)
    at Class._preprocessSlideData (https://fastcom-sa1.odoo.com/web/content/3833-9b303fe/1/web.assets_frontend_lazy.js:264:288)
    at Class.init (https://fastcom-sa1.odoo.com/web/content/3833-9b303fe/1/web.assets_frontend_lazy.js:261:5178)
    at Class.prototype.<computed> [as init] (https://fastcom-sa1.odoo.com/web/content/3832-5a49c2a/1/web.assets_common_lazy.js:3762:488)
    at new Class (https://fastcom-sa1.odoo.com/web/content/3832-5a49c2a/1/web.assets_common_lazy.js:3763:65)
    at Class.start (https://fastcom-sa1.odoo.com/web/content/3833-9b303fe/1/web.assets_frontend_lazy.js:269:1509)
    at Class.prototype.<computed> [as start] (https://fastcom-sa1.odoo.com/web/content/3832-5a49c2a/1/web.assets_common_lazy.js:3762:488)
    at https://fastcom-sa1.odoo.com/web/content/3832-5a49c2a/1/web.assets_common_lazy.js:3994:416
    at async Promise.all (index 0)**

Expected behavior: Fullscreen mode works without errors

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/66636567/89106341-c50f1a80-d3ee-11ea-87b2-3a05c827340a.png)

**Comment by pedrobaeza** [comment] 2020-08-01 21:11
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by ivanporras** [comment] 2020-08-04 19:33
@fastcomsa I cannot reproduce the error.

**Comment by pedrobaeza** [comment] 2020-08-05 06:52
It seems so, so it's something in their end. Closing meanwhile no more feedback that points to a bug in Odoo code.

**Closed by pedrobaeza** 2020-08-05 06:52 UTC
Labels: Need information
