### ISSUE TITLE
Module.js cannot find less on Ubuntu

### ISSUE THREAD

**Issue by jacob-v-dam** [odoo/odoo#9079] opened 2015-10-15 06:02 UTC
I installed odoo by the DEB package on my Ubuntu 14.04 server.

Odoo runs but when I want to select the modules I get an error:
```
"module.js:340
throw err;
Error: Cannot find module 'less'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous> (/usr/bin/lessc:9:12)
 at Module._compile (module.js:456:26)
 at Object.Module._extensions..js (module.js:474:10)
 at Module.load (module.js:356:32)
 at Function.Module._load (module.js:312:12)
 at Function.Module.runMain (module.js:497:10)
 This error occured while compiling the bundle 'web.assets_common' containing:
 - /web/static/src/less/mimetypes.less
 - /web/static/src/less/animation.less
 - /web_planner/static/src/less/web_planner_common.less
 - /web_editor/static/src/less/web_editor.less"
```

I tried to run `npm install -g less` but that did not work. But i'm able to access lessc from the command line, so it should be installed.

Any suggestions?

**Comment by rim-odoo** [comment] 2015-10-15 09:40
Can you give us the output of 
```bash
lessc --version
```
in a terminal?

**Comment by jacob-v-dam** [comment] 2015-10-15 09:41
The output is:
```
root@server:~# lessc --version
lessc 2.5.3 (Less Compiler) [JavaScript]
```

**Comment by sle-odoo** [comment] 2015-10-15 13:59
looks like you have multiple installations of less and npm: one local and one from the deb's dependencies (node-less, node-clean-css). the one in /usr/local/bin/lessc is the source install: uninstall this one and you'll have only a lessc in /usr/bin/lessc

**Comment by sle-odoo** [comment] 2015-10-15 13:59
(the issue is that the source install of npm doesn't have the less module)

**Comment by jacob-v-dam** [comment] 2015-10-15 16:01
Ok, now i have `/usr/bin/lessc`, still the same problem

**Comment by sle-odoo** [comment] 2015-10-15 17:23
now drop your assets by running "DELETE FROM ir_attachment WHERE name ilike '%asset%'; (or simply install a module or create a new database)

**Comment by naousse** [comment] 2015-10-15 18:05
sudo apt-get install node-clean-css 
sudo apt-get install node-less

Have you tried to  install these packages. I had the same probleme, and after installation of these packages, everithing was OK

**Comment by jacob-v-dam** [comment] 2015-10-15 21:07
Ok tried the following:
- Ran the update scripts
- Removed the postgres database
- Reinstalled odoo
But this did not work.

I thought to use `dpkg-reconfigure odoo`. It takes a long time to receive some output, but when I hit enter I get the following response:
```
insserv: warning: script 'K02jira1' missing LSB tags and overrides
insserv: warning: script 'K02StartVM' missing LSB tags and overrides
insserv: warning: script 'jira1' missing LSB tags and overrides
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
insserv: warning: script 'screen-cleanup' missing LSB tags and overrides
insserv: Default-Start undefined, assuming empty start runlevel(s) for script `screen-cleanup'
insserv: Default-Stop  undefined, assuming empty stop  runlevel(s) for script `screen-cleanup'
insserv: warning: script 'StartVM' missing LSB tags and overrides
```

**Comment by websoftix** [comment] 2015-10-18 18:49
I have the same problem on Ubuntu 15.04 Desktop
- installed odoo from here: http://nightly.odoo.com/9.0/nightly/deb/
- created a demo DB and I have this error

```
# lessc --version
(node) util.puts is deprecated. Use console.log instead.
lessc 1.4.2 (LESS Compiler) [JavaScript]

# which lessc
/usr/bin/lessc
```

**Comment by websoftix** [comment] 2015-10-18 19:42
The cause seems to be incompatibility between installed node (v4.2.1) and the "less" related packages installed (and required) by odoo package. 
I solved it by installing the following using npm:
```
#  npm install -g less
#  npm install -g clean-css
#  npm install -g commander
#  npm install -g less-plugin-clean-css
```

**Comment by xhair** [comment] 2015-10-27 09:17
this is odoo9 or python bug.. this os PATH not as same as os.environ["PATH"] in python. if you join "bin_path" into .conf ,but odoo not add "bin_path" to os.os.environ["PATH"].  
If you very urgent, make sure you are in command of the operating system can be executed correctly “lessc”, if you can modify the following code:
1. at your odoo ".conf" join in "bin_path",set lessc of path
2. open "/Users/pengyb/PycharmProjects/odoo-9.0/openerp/tools/misc.py", insert "os.environ["PATH"] += os.defpath + config.get('bin_path')"  after line 56

**Comment by ikarys** [comment] 2016-01-19 12:28
I had the same problem.
When i made `sudo npm install -g less less-plugin-clean-css`, the installation indicate less was installed into my user folder.

I made this :
`sudo su`
`npm install -g less less-plugin-clean-css`
And it's works ! Like this, the less module was installed into /usr/bin folder !

**Comment by sle-odoo** [comment] 2016-06-08 11:56
Closing as it looks like fixed deployment issues.

**Closed by sle-odoo** 2016-06-08 11:56 UTC

**Comment by fatwin** [comment] 2016-12-14 06:09
I encountered this problem today after I upgrading server nodejs to v7.2.1.
Thanks to @ikarys you save my day!
I believe the reason is that as mentioned by @websoftix :

> incompatibility between installed node (v4.2.1) and the "less" related packages installed (and required) by odoo package.
...
