### ISSUE TITLE
Chatter messages unexpectedly marked as done

### ISSUE THREAD

**Issue by ecino** [odoo/odoo#20484] opened 2017-10-26 06:57 UTC
Impacted versions: 10.0

Steps to reproduce:

- Go into a inbox of user and find a incoming message linked to a partner
- Click on the partner to open the record
- All messages from the user inbox are marked as done !

Current behavior:
- All messages from user inbox are marked as done when clicking on the record linked to a message

Expected behavior:
- It should not change the "done/to do" state of any message, including the one we are clicking on.

Video/Screenshot link (optional):
[https://youtu.be/jXd988ph7B4](https://youtu.be/jXd988ph7B4)

I believe the line that is doing this is the following: [https://github.com/odoo/odoo/blob/10.0/addons/mail/static/src/js/chat_manager.js#L744](https://github.com/odoo/odoo/blob/10.0/addons/mail/static/src/js/chat_manager.js#L744)

When commenting it, I no longer have the problem, but I'm not sure if it's breaking something else?

**Comment by Yenthe666** [comment] 2017-10-30 15:28
Hi @ecino,

Thank you for your bug report. This does indeed  remove all messages from the inbox by simply clicking on the contact.
@mart-e can you have a look please? I don't think this is desired behaviour?

**Comment by mart-e** [comment] 2017-10-30 15:54
I guess it was intended by @ged-odoo cf 919179b4175de6f43c0ce860dee2634cd6b89f85

**Comment by Yenthe666** [comment] 2017-10-30 15:58
Well, to me it has two sides..

1) Yes it is fine to mark them as read because the user opens the customer form and can see all the data
2) It is not fine since the customer opens the customer but doesn't persé read the whole chatter. He might be there to simply check something from the customer without going through the whole thread.

I feel like the checkmark box on the inbox should be respected and that this is your deliberate choice to mark is as read/handled.
Let us see what @ged-odoo says. 😉

**Comment by ged-odoo** [comment] 2017-10-30 16:04
@Yenthe666 @mart-e This was a specific request from our (hopefully) benevolent dictator.  He wanted to speed up the processing of messages. Personally, I hate that.  It really goes against my desired way of working: with this, I am scared of opening an issue/task, because once I do that, then the message disappear from my inbox, and if I do not process it immediately, I will not have a simple way to reopen the same task.

I don't see it changing for now, but maybe we can talk about this if/when we work on discuss. @tde-banana-odoo

**Comment by tde-banana-odoo** [comment] 2017-11-06 12:52
Since chatter is implemented reading a record marks all its message as read for the current user. We consider that if you go on a record you read the communication history and do what you have to do. Having to remark messages as read is unnecessary work. I understand you could have a different way of using the Inbox but it is how Odoo works. I don't think it will change for Odoo v12 as far as I know.

Thanks !

**Comment by Yenthe666** [comment] 2017-11-06 12:54
Then I believe we can close this bug report as it is clearly ment to work this way and no changes are on the roadmap.

**Closed by Yenthe666** 2017-11-06 12:54 UTC
Labels: 10.0
