### ISSUE TITLE
[11.0] ir.actions.act_url button are disabled when clicked.

### ISSUE THREAD

**Issue by Boss1669** [odoo/odoo#25687] opened 2018-07-10 04:56 UTC
Impacted versions: 11.0

Steps to reproduce: I have create a button (open google map) with this return 
> return{ 'type': 'ir.actions.act_url', 'url': URL, 'target': 'self'}

Current behavior: After user click on button it will obviously open google map but the button on view are disabled

Expected behavior: the buttons on view should not be disable

Video/Screenshot link (optional):
![36843228_10156626301053885_6316520248023449600_n](https://user-images.githubusercontent.com/26357404/42489989-490222be-8438-11e8-96f2-6c1a389781ec.jpg)

**Comment by sswapnesh** [comment] 2018-07-10 08:05
Duplicate of #22545

**Comment by pedrobaeza** [comment] 2018-07-10 08:09
@sswapnesh in this case it's not exactly a duplicate, as this time the action is an URL, and yours it's a report.

**Comment by sswapnesh** [comment] 2018-07-10 08:10
It is the same.
It uses the same act_url in definition.

**Comment by pedrobaeza** [comment] 2018-07-10 08:15
Ah, OK, I see, but I prefer this issue report as it's more clear directly without going through links to see the problem if you don't mind.

**Comment by sswapnesh** [comment] 2018-07-10 08:20
No Problem, I have added link of odoo code itself instead of raw code as some one from odoo will ask me to reproduce on Runbot.

You can add label 10.0 here and close my issue If you prefer.

**Comment by zuezuecodecamp** [comment] 2018-08-10 09:32
https://github.com/odoo/odoo/issues/2931
please check this link.I think it will useful for this issue.

**Comment by ke-real** [comment] 2018-09-07 11:07
https://github.com/odoo/odoo/issues/2931#issuecomment-344910635

so let's wait for odoo 10 and 11 become end of life and the problem is solved :))

**Closed** 2023-03-30 11:59 UTC
Labels: Framework, 11.0, 10.0
