### ISSUE TITLE
adding control attribute to a record-defined tree view

### ISSUE THREAD

**Issue by mhabboush97** [odoo/odoo#62316] opened 2020-11-25 11:43 UTC
Impacted versions:
14, possibly others as well
Steps to reproduce:
create new tree view
Add control attribute
Upgrade module
Current behavior:
xml parser will raise an error because of the control attribute
Expected behavior:
control attribute should not raise error by parser, and if tree is not called from a m2o field, it should be ignored

Instead of defining a m2o tree for every m2o field, one should be able to define a tree view and use tree_view_ref to call it, however, adding control attributes inside the tree breaks module upgrade (--dev xml renders the view fine, but upgrade triggers the error)

part of the error code 
```
2020-11-25 11:37:46,432 101881 ERROR test_db odoo.tools.view_validation: <string>:3:0:ERROR:RELAXNGV:RELAXNG_ERR_ATTRVALID: Element create failed to validate attributes 
2020-11-25 11:37:46,433 101881 ERROR test_db odoo.tools.view_validation: <string>:2:0:ERROR:RELAXNGV:RELAXNG_ERR_CONTENTVALID: Element control failed to validate content 
2020-11-25 11:37:46,433 101881 ERROR test_db odoo.tools.view_validation: <string>:2:0:ERROR:RELAXNGV:RELAXNG_ERR_EXTRACONTENT: Element tree has extra content: control 
2020-11-25 11:37:46,433 101881 ERROR test_db odoo.tools.view_validation: Invalid XML:  Get RNG validator and validate RNG file. 
2020-11-25 11:37:46,437 101881 WARNING test_db odoo.modules.loading: Transient module states were reset 
2020-11-25 11:37:46,453 101881 ERROR test_db odoo.modules.registry: Failed to load registry 
2020-11-25 11:37:46,453 101881 ERROR test_db odoo.http: Exception during JSON request handling. 
```

**Comment by pedrobaeza** [comment] 2020-11-25 11:50
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2020-11-25 11:50 UTC

**Comment by mhabboush97** [comment] 2020-11-25 12:30
Hmmm, of course I cannot provide "detailed information for reproducing the problem on an standard Odoo (without extra addons)" because all odoo modules define a m2o tree with control attribute inside the filed itself, not in  the view file 

The error is "having create attribute inside tree will raise error from convert_xml unless the tree is defined inside a m2o field"

If you still think this is not an error, then you can close the ticket

**Comment by pedrobaeza** [comment] 2020-11-25 12:32
Yes, I think it's not a problem, but a limitation. You can't do such thing in current framework.
