### ISSUE TITLE
[13.0] planning: removing all role types results in unusable calendar

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#42703] opened 2020-01-03 15:17 UTC
Impacted versions: 13.0

Steps to reproduce:
1. Go to the latest runbot 13.0 instance and login
2. Go to Planning > My planning > Calendar and set it to "Month" so you can see the whole month
3. Check off all role options in the calendar view
Video: https://drive.google.com/file/d/1TGgAtCF9IwlV4RD0hly4DQFYLizjR9YV/view

Current behavior:
No more planning records are shown but even worse: the whole option to check off/on roles AND employees is gone. There is no way to see your planning again unless you refresh the view.

Expected behavior:
The option to check off/on roles and employees stays.

**Comment by Yenthe666** [comment] 2020-01-03 15:20
OPW `2166932`

**Comment by sswapnesh** [comment] 2020-01-04 14:42
Duplicate of https://github.com/odoo/odoo/issues/42433 ?

**Comment by Yenthe666** [comment] 2020-01-04 18:39
Yes and no. I've reported it for planning and you for sales, apparently it's a framework thing then :) Let's wait for OPW feedback

**Comment by dbo-odoo** [comment] 2020-01-07 17:42
Hello @Yenthe666 
If you opened an opw, there is no need for a github issue:
- it will not be faster
- if the opw is refused, we won't accept the issue
- there is no added value to doing both (unlike opening an opw and a PR, which is constructive)

In a nutshell: 
- opw + PR = yay
- opw + issue = nay

I'm closing the recent issues you opened where you referenced an opw number.

Thx for your understanding :)

**Comment by sswapnesh** [comment] 2020-01-07 17:43
> If you opened an opw, there is no need for a github issue:

Is it a global Rule or just for Him?

**Comment by dbo-odoo** [comment] 2020-01-07 18:00
Global rule; I really don't see the point of opening an issue if there's an OPW in general - not just for Yenthe:
- it's a miscommunication problem waiting to happen (someone says something on the issue, someone from support says something else on the opw ticket... what happens now?)
- it's a waste of resource waiting to happen (2 people making a patch for the same problem without knowing it)
- github issues are a notorious magnet for non-related problems: someone has a problem, someone else has something that they believe is similar but is in fact completely different. The conversation quickly becomes useless
- there are 2 sources of information for a single problem, and our support agents should not have to switch between the opw and github to get the full picture

I'm not gonna inspect every issue for this, but i really don't see the point of doing it to be honest ¯\_(ツ)_/¯

**Comment by pedrobaeza** [comment] 2020-01-07 18:06
I totally support @dbo-odoo in this, and that's why my original rant about putting in this issue trackers issues about enterprise modules, as they need to be handled by force through OPW.

**Comment by Yenthe666** [comment] 2020-01-07 19:00
Hi @dbo-odoo,

I totally do not agree with this approach and it makes me rather unhappy. I seem to have to discuss and 'fight' about nearly everything with you guys. If you'd look closer to my issue history you notice that I handle the whole flow personally. Let me give you an example with https://github.com/odoo/odoo/issues/40756. As you can see I've referenced an OPW there too (`2144374`). In this public thread I keep track of the OPW and I add information from the official ticket back into the Github issue. As you can see at https://github.com/odoo/odoo/issues/40756#issuecomment-563247420
This results in a nice structure which brings a lot of benefit:
- The issue is publicly available and searchable with a backlink to the OPW and the most important information.
- It informs the community about issues along with their fixes and it probably saves you OPW tickets.
- This allows me to write better descriptions for OPW's as I can add images here much better than in your ticket system that honestly s*cks in handling images and attachments.
- Great way for me to talk/link it to third parties that I don't want to attach to my specific OPW's on odoo.com

Let me counter your points:

> it's a miscommunication problem waiting to happen (someone says something on the issue, someone from support says something else on the opw ticket... what happens now?)
> it's a waste of resource waiting to happen (2 people making a patch for the same problem without knowing it)

It's not. I create the Github issue, I create the OPW and I link both to eachother. Every important update is mentioned on the Github issue and I close it once it is fixed with a link to the PR/commit. I cross-reference everything, always.

> github issues are a notorious magnet for non-related problems: someone has a problem, someone else has something that they believe is similar but is in fact completely different. The conversation quickly becomes useless

Maybe for badly written or vague Github issues but not if they're detailed, documented and well formatted. Have a look into my Github issue history you'll find nearly zero issues with a random guy complaining about other stuff.

> there are 2 sources of information for a single problem, and our support agents should not have to switch between the opw and github to get the full picture

They don't have to do a single extra sh*t for this. I'm doing all the heavy lifting here with a very clear intention: having as much info publicly available as possible so others can find it, find the fix and don't waste time. I'd even argue I've probably saved you OPW's in the past due to this.


I think that by now I've earned some stripes here and know both Github and odoo.com tickets quite well. After all I've been active in 1100+ tickets on Github and 300+ official OPW's.
I'd highly appreciate it if you reopen the ones you've just closed. If you look at the OPW's you will find that they're all still open without any feedback. Let me reference them for you again:
https://github.com/odoo/odoo/issues/42275#issuecomment-571693961
https://github.com/odoo/odoo/issues/42328#issuecomment-571693936
https://github.com/odoo/odoo/issues/42687#issuecomment-571693894
https://github.com/odoo/odoo/issues/42732#issuecomment-571693801
https://github.com/odoo/odoo/issues/42740#issuecomment-571693667
https://github.com/odoo/odoo/issues/42742#issuecomment-571693556

Now for the love of god can we continue with improving and fixing stuff instead of trying to fight over these kind of things? This costed me yet another half hour of my life that I could've spent on way more important Odoo stuff.

**Comment by dbo-odoo** [comment] 2020-01-08 07:43
Hello again,

You have obviously strong feelings about this - I do not. I've read your points, I've re-read mine. I haven't changed my mind.

While you can perhaps take the time to do this correctly, I believe it sets up expectations for other people who will not do it as comprehensively and assiduously as you do.

I won't waste my time policing stuff like this, so if it brings you happiness to put your issues publicly, cross-referencing them and all that jazz, there's little I can do to prevent you from doing it. I'll still close them from time to time when I forget about this whole debate that has seemingly been going on for some time before I closed this specific issue. I still believe it's a waste of time, but as long as you only waste yours I honestly don't really care ¯\\\_(ツ)\_/¯. There is no ill-will here, I just think you're setting up false expectations for other people.

To others who might read this: please know that opening issues for something that has been reported as an opw is useless and will neither improve the speed at which your issue is handled, nor will it give you 'more chances' to get your issue addressed. Feel free to lose your own time, but not ours ;)

Cheers everybody!

**Comment by Yenthe666** [comment] 2020-01-08 07:49
@dbo-odoo well then have fun with the other Odoo issues that are linked to an OPW too (https://github.com/odoo/odoo/issues?q=is%3Aopen+is%3Aissue+label%3AOE)
@mart-e since this has been discussed a few times before I suggest that you make a final call once and for all. Will we accept this behavior or not? If not I will not bother creating any anymore and we'll always close down issues linked to an OPW. I'll leave the call to you.

**Comment by mart-e** [comment] 2020-01-08 08:23
Same as Damien, I don't have strong feelings about either one. As long as we have no wasted time by having multiple people are working on the same issue with conflicting opinions, I see no harm. When I see a github issue that has already been reported in an opw, I will just ignore it.
If you prefer to have the report of an issue public, I see no harm, feel free to continue doing so, just don't forget to close them once the opw has been closed.

**Comment by jvm-odoo** [comment] 2020-01-08 13:26
Hi @Yenthe666 , I'm on it. I will give you a feedback soon. Have a great day!

**Comment by Yenthe666** [comment] 2020-01-08 16:33
Awesome, thank you @jvm-odoo! Let me know if you need anything from me :)

**Closed** 2020-01-09 10:30 UTC
Labels: 13.0, OE, Services
