### ISSUE TITLE
[11.0] Authentication broken after update for existing users

### ISSUE THREAD

**Issue by mlaitinen** [odoo/odoo#23947] opened 2018-03-29 15:13 UTC
Impacted versions: 11.0

Steps to reproduce:
1. Create a database in Odoo `v11.0e-20180128`
2. Log in (get session id to your browser as a cookie)
3. Upgrade the database to Odoo `v11.0e-20180329`

Current behavior:
Users that have logged in will see the following page in their browser:

> 403 Forbidden
> You don't have the permission to access the requested resource. It is either read-protected or not readable by the server.

```
odoo_1    | 2018-03-29 15:03:24,524 27 INFO my-db odoo.addons.base.ir.ir_http: Generating routing map
odoo_1    | 2018-03-29 15:03:24,571 27 INFO my-db odoo.addons.base.ir.ir_http: Exception during request Authentication.
odoo_1    | Traceback (most recent call last):
odoo_1    |   File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_http.py", line 108, in _authenticate
odoo_1    |     request.session.check_security()
odoo_1    |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 1062, in check_security
odoo_1    |     if not security.check_session(self):
odoo_1    |   File "/usr/lib/python3/dist-packages/odoo/service/security.py", line 23, in check_session
odoo_1    |     if odoo.tools.misc.consteq(self._compute_session_token(session.sid), session.session_token):
odoo_1    | TypeError: unsupported operand types(s) or combination of types: 'str' and 'NoneType'
```

Expected behavior:
The login works.

Workaround:
Empty browser cookies or use incognito mode.

This problem is caused by the commit da1f153d61d747d9357694382fe04f96c0ca886a by @tbe-odoo.

**Comment by Yenthe666** [comment] 2018-03-29 15:15
Oh hey, I've had this today too! I thought I broke something myself.
Tip: You can bypass this issue by running Odoo in incognito mode, it will work for now.

**Comment by mlaitinen** [comment] 2018-03-29 15:22
I had to monkey patch that function because I didn't want to explain our client why I broke the production environment. Of course I didn't notice this in staging because I didn't have an existing session in that database.

```
from odoo.service import security as Sec
import odoo


def check_session(session):
    with odoo.registry(session.db).cursor() as cr:
        self = odoo.api.Environment(cr, session.uid, {})['res.users'].browse(session.uid)
        if session.sid and session.session_token and odoo.tools.misc.consteq(self._compute_session_token(session.sid), session.session_token):
            return True
        self._invalidate_session_cache()
        return False

Sec.check_session = check_session
```

**Comment by tbe-odoo** [comment] 2018-04-26 11:38
Hello @mlaitinen really sorry for taking so long to answer.

I have tried to reproduce your issue by reverting my commit, connect to my account, reintroduce the commit restart the server and refresh the page were I was.
I did it multiple time and was never able to reproduce the issue.

Are you able to reproduce it in your side so I can investigate ?
From what I see, the exception is triggered because your session doesn't have a value for "session_token" which shoud not happen since we convert the old session to the new type https://github.com/odoo/odoo/commit/da1f153d61d747d9357694382fe04f96c0ca886a#diff-03542f2676ca18278ea62cb40f5a2261R1066

**Comment by akhlaaqbadulla** [comment] 2018-12-13 06:09
i dont know if its a good solution to do this. i have been searching for different solution to his problem the only one that worked is this: 
`sudo chmod -R 0777 /etc/nginx/`

gave the permission and i am having no issue so far but my question is it safe to give nginx all these permission am newbie i have loads of question?

**Comment by Yenthe666** [comment] 2018-12-13 07:09
@akhlaaqbadulla in general it is never a good idea to give `777` rights to any file on Linux. You're basically allowing anyone that can get into that server to do whatever he/she wants with those files. As your Nginx is the layer to the network and for redirecting data this is a very bad idea.

**Comment by akhlaaqbadulla** [comment] 2018-12-13 07:14
@Yenthe666  ohhh i have to trim down the ryts to a more reasonable one then. though i have not found a solution to my "403 forbidden You don't have the permission to access the requested resource. It is either read-protected or not readable by the server". though every time i fiddle with the database acess it works then when i add something it sends me "403 forbidden You don't have the permission to access the requested resource. It is either read-protected or not readable by the server".

**Comment by Yenthe666** [comment] 2018-12-13 07:18
Looks like a misconfiguration, you might want to learn more about Nginx and security rights :)

**Comment by Yenthe666** [comment] 2018-12-13 07:36
Just follow some Nginx, database and Linux basics tutorials, dozens of them on the internet.

**Comment by akhlaaqbadulla** [comment] 2018-12-13 07:42
thank you i was actually doing that i dont know how but nginx did not had read access to config files. no more 777.

**Comment by mart-e** [comment] 2021-02-23 10:27
Closing as the 11.0 is no longer supported

**Closed by mart-e** 2021-02-23 10:27 UTC
Labels: 11.0, Framework
