### ISSUE TITLE
[V8 ODOO BUG] Upgrade to database for all, failed.

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#6479] opened 2015-04-27 08:00 UTC
Try to upgrade database with -d  database -u all raise bug.

2015-04-27 07:54:11,760 1610 INFO db_ford_xdb openerp.modules.loading: loading purchase/purchase_view.xml
2015-04-27 07:54:12,220 1610 ERROR db_ford_xdb openerp.addons.base.ir.ir_ui_view: Field `related_usage` does not exist

Error context:
View `purchase.order.form`
[view_id: 708, xml_id: purchase.purchase_order_form, model: purchase.order, parent_id: n/a]
2015-04-27 07:54:12,222 1610 CRITICAL db_ford_xdb openerp.service.server: Failed to initialize database `db_ford_xdb`.
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/service/server.py", line 919, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/opt/odoo/odoo-server/openerp/modules/registry.py", line 368, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 351, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 176, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/odoo-server/openerp/tools/convert.py", line 901, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/odoo-server/openerp/tools/convert.py", line 987, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/odoo-server/openerp/tools/convert.py", line 853, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/opt/odoo/odoo-server/openerp/tools/convert.py", line 763, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_model.py", line 1050, in _update
    model_obj.write(cr, uid, [res_id], values, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_ui_view.py", line 282, in write
    context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 363, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 3760, in write
    self._write(old_vals)
  File "/opt/odoo/odoo-server/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 546, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 3931, in _write
    recs._validate_fields(vals)
  File "/opt/odoo/odoo-server/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 1267, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "ValidateError
Field(s) `arch` failed against a constraint: Invalid view definition

Error details:
Field `related_usage` does not exist

Error context:
View `purchase.order.form`
[view_id: 708, xml_id: purchase.purchase_order_form, model: purchase.order, parent_id: n/a]" while parsing /opt/odoo/odoo-server/addons/purchase/purchase_view.xml:185, near
<record id="purchase_order_form" model="ir.ui.view">
            <field name="name">purchase.order.form</field>
            <field name="model">purchase.order</field>
            <field name="arch" type="xml">
                <form string="Purchase Order">
                <header>
                    <button name="bid_received" states="sent" string="Bid Received" class="oe_highlight"/>
                    <button name="wkf_send_rfq" states="draft" string="Send RFQ by Email" type="object" context="{'send_rfq':True}" class="oe_highlight"/>
                    <button name="wkf_send_rfq" states="sent" string="Re-Send RFQ by Email" type="object" context="{'send_rfq':True}"/>
                    <button name="print_quotation" string="Print RFQ" type="object" states="draft" class="oe_highlight" groups="base.group_user"/>
                    <button name="print_quotation" string="Re-Print RFQ" type="object" states="sent" groups="base.group_user"/>
                    <button name="purchase_confirm" states="draft" string="Confirm Order" id="draft_confirm"/>
                    <button name="purchase_confirm" states="bid" string="Confirm Order" class="oe_highlight" id="bid_confirm"/>
                    <button name="picking_ok" states="except_picking" string="Manually Corrected"/>
                    <button name="invoice_ok" states="except_invoice" string="Manually Corrected"/>
                    <button name="purchase_approve" states="confirmed" string="Approve Order" class="oe_highlight" groups="purchase.group_purchase_manager"/>
                    <button name="wkf_send_rfq" states="approved" string="Send PO by Email" type="object" context="{'send_rfq':False}"/>
                    <button name="view_picking" string="Receive Products" type="object" attrs="{'invisible': ['|', ('shipped','=',True), ('state','!=', 'approved')]}" class="oe_highlight"/>
                    <button name="view_invoice" string="Receive Invoice" type="object" attrs="{'invisible': ['|', ('invoice_method','in', ['picking', 'manual']), '|', ('state','!=', 'approved'), ('invoiced','=',True) ]}" class="oe_highlight"/>
                    <button name="action_cancel_draft" states="cancel,sent,confirmed" string="Set to Draft" type="object"/>
                    <button name="action_cancel" states="draft,confirmed,sent,bid,approved,except_picking,except_invoice" string="Cancel" type="object"/>
                    <field name="state" widget="statusbar" statusbar_visible="draft,sent,bid,approved,done" statusbar_colors="{&quot;except_picking&quot;:&quot;red&quot;,&quot;except_invoice&quot;:&quot;red&quot;,&quot;confirmed&quot;:&quot;blue&quot;}" readonly="1"/>
                </header>
                <sheet>
                    <div class="oe_title">
                        <h1>
                            <label string="Request for Quotation " attrs="{'invisible': [('state','not in',('draft','sent','bid'))]}"/>
                            <label string="Purchase Order " attrs="{'invisible': [('state','in',('draft','sent','bid'))]}"/>
                            <field name="name" class="oe_inline" readonly="1"/>
                        </h1>
                    </div>
                    <group>
                        <group>
                            <field name="partner_id" on_change="onchange_partner_id(partner_id, context)" context="{'search_default_supplier':1, 'default_supplier':1, 'default_customer':0}" domain="[('supplier','=',True)]"/>
                            <field name="partner_ref"/>
                            <field domain="[('type','=','purchase')]" name="pricelist_id" groups="product.group_purchase_pricelist" on_change="onchange_pricelist(pricelist_id, context)"/>
                            <field name="currency_id" groups="base.group_multi_currency"/>
                            <field name="journal_id" invisible="1"/>
                        </group>
                        <group>
                            <field name="date_order"/>
                            <field name="origin" attrs="{'invisible': [('origin','=',False)]}"/>
                            <field name="company_id" groups="base.group_multi_company" options="{'no_create': True}"/>
                            <field name="picking_type_id" on_change="onchange_picking_type_id(picking_type_id, context)" domain="[('code','=','incoming')]" options="{'no_create': True}" context="{'special_shortened_wh_name': True}" groups="stock.group_locations"/>
                            <field name="related_usage" invisible="1"/>
                            <field name="dest_address_id" string="Customer Address" on_change="onchange_dest_address_id(dest_address_id, context)" attrs="{'invisible':[('related_usage','!=','customer')],                                 'required': [('related_usage','=', 'customer')]}" groups="stock.group_locations"/>
                        </group>
                    </group>
                    <notebook>
                        <page string="Products">
                            <field name="order_line">
                                <tree string="Purchase Order Lines" editable="bottom">
                                    <field name="product_id" on_change="onchange_product_id(parent.pricelist_id,product_id,0,False,parent.partner_id, parent.date_order,parent.fiscal_position,date_planned,False,False,parent.state,context)"/>
                                    <field name="name"/>
                                    <field name="date_planned"/>
                                    <field name="company_id" groups="base.group_multi_company" options="{'no_create': True}"/>
                                    <field name="account_analytic_id" groups="purchase.group_analytic_accounting" domain="[('type','not in',('view','template'))]"/>
                                    <field name="product_qty" on_change="onchange_product_id(parent.pricelist_id,product_id,product_qty,product_uom,parent.partner_id,parent.date_order,parent.fiscal_position,date_planned,name,False,parent.state,context)"/>
                                    <field name="product_uom" groups="product.group_uom" on_change="onchange_product_uom(parent.pricelist_id,product_id,product_qty,product_uom,parent.partner_id, parent.date_order,parent.fiscal_position,date_planned,name,False,parent.state,context)"/>
                                    <field name="price_unit"/>
                                    <field name="taxes_id" widget="many2many_tags" domain="[('parent_id','=',False),('type_tax_use','!=','sale')]"/>
                                    <field name="price_subtotal"/>
                                    <field name="state" invisible="1"/>
                                </tree>
                            </field>
                            <group class="oe_subtotal_footer oe_right">
                                <field name="amount_untaxed" widget="monetary" options="{'currency_field': 'currency_id'}"/>
                                <field name="amount_tax" widget="monetary" options="{'currency_field': 'currency_id'}"/>
                                <div class="oe_subtotal_footer_separator oe_inline">
                                    <label for="amount_total"/>
                                    <button name="button_dummy" states="draft" string="(update)" type="object" class="oe_edit_only oe_link"/>
                                </div>
                                <field name="amount_total" nolabel="1" class="oe_subtotal_footer_separator" widget="monetary" options="{'currency_field': 'currency_id'}"/>
                            </group>
                            <div class="oe_clear"/>
                            <field name="notes" class="oe_inline" placeholder="Terms and conditions..."/>
                        </page>
                        <page string="RFQ &amp; Bid">
                            <group>
                                <field name="incoterm_id"/>
                                <field name="bid_date"/>
                                <field name="bid_validity"/>
                            </group>
                        </page>
                        <page string="Deliveries &amp; Invoices">
                            <group>
                                <group>
                                    <field name="minimum_planned_date"/>
                                    <field name="location_id" groups="stock.group_locations"/>
                                    <field name="shipped" groups="base.group_no_one"/>
                                </group>
                                <group>
                                    <field name="invoice_method"/>
                                    <field name="invoiced"/>
                                    <field name="payment_term_id" options="{'no_open': True, 'no_create': True}"/>
                                    <field name="fiscal_position" attrs="{'readonly': [('invoiced','=', True)]}"/>
                                    
                                    <field name="validator" groups="base.group_no_one"/>
                                    <field name="date_approve" groups="base.group_no_one"/>
                                </group>
                            </group>
                        </page>
                    </notebook>
                </sheet>
                <div class="oe_chatter">
                    <field name="message_follower_ids" widget="mail_followers"/>
                    <field name="message_ids" widget="mail_thread"/>
                </div>
                </form>
            </field>
        </record>

**Comment by houssine78** [comment] 2015-06-15 13:44
seems like they changed the datamodel and removed the field from the model and they probably have forgotten to remove it from the view...

strange cause since they may not change the datamodel once they marked it froozen... and it maybe stranger that they didn't fix it... as more than one customer may encoure this bug!

**Comment by Yenthe666** [comment] 2016-06-09 11:11
I can't reproduce this bug, could it be you've downloaded the V8 before it was stable and tried to upgrade it later on? In this case a model change is possible as error, but that only happens if you downloaded a non-stable version before.
This cannot be reproduced anymore so closing this one.

**Closed by Yenthe666** 2016-06-09 11:11 UTC
