### ISSUE TITLE
[13.0] [website editor] No way to change looped html fields (2 or more) on the same page

### ISSUE THREAD

**Issue by feelwhy** [odoo/odoo#46155] opened 2020-02-24 17:27 UTC
Impacted versions:
13.0

Steps to reproduce:
1. Add 2 html fields for the same template (e.g. show blog content in the website_blog teaser template to add multiple in a loop > look at the attached screenshot)
2. Go to the related website page > Edit 
3. Choose one HTML field > press the 'link' button
4. Repeat the step 3 for another part of the HTML field. 

Basically, the same / similar error appears under different conditions sporadically.
The mechanics above leads 100% to the same result.

Current behavior:
1. Error appears without a chance to change the second field properly

Expected behavior:
1. No errors.
2. Multiple HTML fields might be simply edited.

Video/Screenshot link (optional):
Done on the official Odoo demo:
Step 1
![example](https://user-images.githubusercontent.com/42974129/75175300-209ff280-5743-11ea-9976-4be2dff88abc.png)
Step 2
![link](https://user-images.githubusercontent.com/42974129/75175301-209ff280-5743-11ea-8734-3a563324f896.png)
Step 3
![error](https://user-images.githubusercontent.com/42974129/75175297-20075c00-5743-11ea-85e8-84c9a8af7205.png)

Uncaught TypeError: Cannot read property 'ownerDocument' of undefined
http://localhost:8013/web/content/6387-2c31490/1/web.assets_common_lazy.js:694
Traceback:
TypeError: Cannot read property 'ownerDocument' of undefined
at Function.Sizzle.contains (http://localhost:8013/web/content/6387-2c31490/1/web.assets_common_lazy.js:694:104)
at Editor.saveRange (http://localhost:8013/web/content/6335-910106e/web_editor.summernote.js:215:741)
at EventHandler.invoke (http://localhost:8013/web/content/6335-910106e/web_editor.summernote.js:380:1506)
at LinkDialog.show (http://localhost:8013/web/content/6335-910106e/web_editor.summernote.js:299:981)
at HTMLDivElement.showLinkDialog (http://localhost:8013/web/content/6335-910106e/web_editor.summernote.js:381:918)
at HTMLDivElement.hToolbarAndPopoverClick (http://localhost:8013/web/content/6335-910106e/web_editor.summernote.js:388:346)
at HTMLDivElement.dispatch (http://localhost:8013/web/content/6387-2c31490/1/web.assets_common_lazy.js:925:447)
at HTMLDivElement.elemData.handle (http://localhost:8013/web/content/6387-2c31490/1/web.assets_common_lazy.js:911:166)

**Comment by qsm-odoo** [comment] 2020-10-09 12:40
I cannot reproduce this issue, I am closing the PR. Please reopen with a video of the issue if it still happens on your side, thank you :+1:

**Closed by qsm-odoo** 2020-10-09 12:40 UTC
Labels: 13.0, Website
