### ISSUE TITLE
PO for services

### ISSUE THREAD

**Issue by ccandito** [odoo/odoo#4909] opened 2015-01-26 17:53 UTC
Dear Customer Support,
I've created a PO for services.
I didn't change the invoice control parameter set by default as Based on incoming shipments.
In this stage it is not possible to cancel the PO or invoice it either.
Regards
claudio

**Comment by jco-odoo** [comment] 2015-01-29 22:51
It does not make sense to do based on incoming shipments for services.  The user should be blocked to do this indeed.

**Comment by ccandito** [comment] 2015-01-30 08:50
I do agree on you it does not make sense to set invoice verification based on incoming shipments in service procurement process. Unfortunately, this has been set by default and after confirming PO, this indicator is not changeble anymore and the PO cannot be cancelled.
Therefore the concerned PO is stuck without any change to move forward it.
Regards
claudio

PS: I've open some other issue, could you please take care about them also?

**Comment by jbeficent** [comment] 2015-02-04 08:56
This was also reported in #3492, and happens in versions 7.0 and 8.0.

It is extremely easy for a purchase user to make a mistake and not change the invoicing control from the default value. 

If there's no way to reverse this confirmed order, the order will be stuck there confirmed, but cannot be invoiced.

I'd say that a bug for which there's no possible workaround should be considered a high priority.

**Comment by jbeficent** [comment] 2015-02-04 11:46
This Pull Request introduces a module that prevents this from happening, and allows you to cancel wrong PO's. https://github.com/OCA/purchase-workflow/pull/89

**Comment by odony** [comment] 2015-02-04 12:51
Closing as it is a duplicate of #3492 indeed, thanks @jbeficent.
Incidentally, why make a module to "fix" this, instead of a simple PR to prevent this from happening in the core? Or did I miss it?

**Closed by odony** 2015-02-04 12:51 UTC

**Comment by jco-odoo** [comment] 2015-02-04 12:56
I thought to have seen in the code (just got a quick look) that it will
throw the error when there is one product of type service.  Not all
products should be services, but you can add a service.
