### ISSUE TITLE
does odoo 9 support ubuntu 17.04?

### ISSUE THREAD

**Issue by menagabara** [odoo/odoo#18686] opened 2017-08-04 14:21 UTC
I installed odoo 9 from [link](https://github.com/odoo/odoo/tree/9.0) and each time i try to run it, this error appears:
`raise ValueError('External ID not found in the system: %s' % (xmlid))
QWebTemplateNotFound: External ID not found in the system: web.login
`
All the modules in requirements.txt were installed including passlib,i also tried to clear history and kill servers. I've created the db role by following this steps:
`sudo adduser odoo`
`sudo apt-get install postgresql`
`sudo su postgresql`
`createuser --createdb --username postgres --no-createrole --no-superuser -pwprompt odoo`
here's openerp-server.config file:
`[options]`
`; This is the password that allows database operations:`
`; admin_passwd = admin`
`db_host = False`
`db_port = False`
`db_user = odoo`
`db_password = False`
`addons_path = /usr/lib/python2.7/dist-packages/openerp/addons`
i also tried this command and it's not working:
python odoo.py --addons addons
and 
./odoo.py --addons-path=.../Desktop/odoo/addons
and tried to change the addons path as well but still facing the same problem.

so i thought my ubuntu version is the problem, is it?

**Comment by menagabara** [comment] 2017-08-04 14:24
I managed to install all the requirements including pypdf, but it raises error about web.log each time i try to run it, so i thpught my ubuntu version is the problem, is it?

**Comment by Yenthe666** [comment] 2017-08-04 17:21
Hi @menagabara,

Odoo should be working on Ubuntu 17.04 (if I'm not mistaking @sle-odoo fixed an issue for this a while ago).
How did you install it / which guide did you follow?
Could you post the traceback please?

Regards,
Yenthe

**Comment by menagabara** [comment] 2017-08-05 16:13
@Yenthe666 updated.

**Comment by Yenthe666** [comment] 2017-08-05 17:37
Will look at it next week and give you feedback, don't have computer access at the moment. :)

**Comment by Yenthe666** [comment] 2017-12-27 14:07
Hey @menagabara,

My apologies for the delay from my side. Could you please update your whole Odoo codebase? I'm not able to reproduce it at this point.

**Comment by Yenthe666** [comment] 2018-02-12 11:04
Hi there,

I'm closing this bug report as there has been no feedback in a few months.

Regards,
Yenthe

**Closed by Yenthe666** 2018-02-12 11:04 UTC
Labels: Need information
