### ISSUE TITLE
analytic: There's no option for the final user to change an analityc tag color

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#25699] opened 2018-07-10 13:08 UTC
#### Impacted versions:
9.0, 10.0, 11.0

#### Steps to reproduce:
- Create an Analytic Tag
- Try to change the Color

#### Current behavior:
- The analytic tags have a color property, but this can't be change on the invoices
- There's a menu (just in debug mode) to create analytic tags, but there's no option to select available colors.

#### Expected behavior:
- Have an accessible option to change the colors of the analytic tags (just as **res.partner.category**)

**Comment by Yenthe666** [comment] 2018-07-12 08:49
@qdp-odoo also related to accounting so I guess you're the guy we're looking for! 🎐

**Comment by qdp-odoo** [comment] 2018-07-13 07:40
yes... but the problem is that there's no handy color picker widget for the form view. So displaying the field in form view would just display an integer field that would confuse people more than anything else.

So for this reason, I'm against changing anything in stable in the current state, but we've created an internal task to define such a color picker widget for the form view in master.

In the meanwhile, let me close this issue at it's more related to a wishlist/nice-to-have than a real bug

Thanks

**Closed by qdp-odoo** 2018-07-13 07:40 UTC
Labels: 10.0, 11.0, 9.0, Accounting
