### ISSUE TITLE
Odoo Client Error in odoo13 custom module

### ISSUE THREAD

**Issue by GUNALAN952** [odoo/odoo#47354] opened 2020-03-11 09:56 UTC
Hi all i have created a custom  module in odoo13 , when i try to upgrade iam getting this error

Traceback:
TypeError: Cannot read property 'type' of undefined
    at Class._renderBodyCell (http://localhost:8069/web/static/src/js/views/list/list_renderer.js:444:50)
    at http://localhost:8069/web/static/src/js/views/list/list_renderer.js:838:25
    at Array.map (<anonymous>)
    at Class._renderRow [as _super] (http://localhost:8069/web/static/src/js/views/list/list_renderer.js:837:35)
    at Class._renderRow (http://localhost:8069/web/static/src/js/views/list/list_editable_renderer.js:1166:32)
    at Class._renderRow (http://localhost:8069/web/static/src/js/core/class.js:123:38)
    at Array.map (<anonymous>)
    at Class._renderRows (http://localhost:8069/web/static/src/js/views/list/list_renderer.js:858:32)
    at Class._renderRows (http://localhost:8069/web/static/src/js/views/list/list_editable_renderer.js:1187:26)
    at Class._renderRows (http://localhost:8069/web/static/src/js/core/class.js:123:38)

it was working fine but suddenly idk what happened i cant access the module , these are my conf files for the module
transfers.xml:

<?xml version="1.0" encoding="utf-8"?>
<odoo>

    <record id="action_transfers" model="ir.actions.act_window">
           <field name="name">Transfers</field>
           <field name="type">ir.actions.act_window</field>
           <field name="res_model">transfers.name</field>
	   <field name="view_mode">tree,form</field>
           <field name="help" type="html">
	     <p class="o_view_nocontent_smiling_face">
	       create your first transfer
	     </p>            
           </field>
     </record>

    <menuitem id ="transfers_root" name ="Transfers" sequence ="0" web_icon="transfers,static/description/icon.png" />  
    <menuitem id ="transfers_name" name ="Transfers_Name" parent="transfers_root" action="action_transfers"/> 

</odoo>

transfers.py:

# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

from odoo import models, fields, _

class Transfers(models.Model):
     _name ="transfers.name"
     _description ="Transfer Record"

     transfers_Name = fields.Char(string="Name", required = True)
     transfers_ISO = fields.Char(string="ISO") 
     transfers_amount = fields.Integer("Amount")
     notes = fields.Text(string ="Notes")
     image = fields.Binary(string ="Image")

ps : i have restarted multiple times , also tried to update is in superuser mode . anyone help with this

**Comment by pedrobaeza** [comment] 2020-03-11 10:20
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2020-03-11 10:20 UTC
