### ISSUE TITLE
[9.0] Issues with website_sale_delivery on front-end 

### ISSUE THREAD

**Issue by kkoci** [odoo/odoo#9567] opened 2015-11-14 02:28 UTC
Hi, everytime I try to do a checkout, when module 'website_sale_delivery' is installed, system throws this QWeb error:

'foreach enumerator 'shipping_countries' is not defined while rendering template 907'

First time I've tried with a customized template, then tried with a vanilla system, and the behavior is the same. First thought it could be a customization issue, but it isn't.

Process to reproduce this error:

1.- Install website, eCommerce and website_sale_delivery modules

2.- Create a product on backend

3.- Publish product on website

4.- Access to yourip:8069/shop

5.- Select 'Add to Cart' , then 'Process checkout'

Here's the complete traceback:

Traceback (most recent call last):
  File "/opt/python/apps/odoo/instances/sukotto/odoo/addons/website/models/ir_http.py", line 242, in _handle_exception
    response = super(ir_http, self)._handle_exception(exception)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/addons/base/ir/ir_http.py", line 147, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/http.py", line 737, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/addons/base/ir/ir_http.py", line 172, in _dispatch
    result = request.dispatch()
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/http.py", line 768, in dispatch
    r = self._call_function(**self.params)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/http.py", line 315, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/http.py", line 311, in checked_call
    result.flatten()
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/http.py", line 1367, in flatten
    self.response.append(self.render())
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/http.py", line 1360, in render
    context=request.context)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/addons/website/models/ir_ui_view.py", line 143, in render
    return super(view, self).render(cr, uid, id_or_xml_id, values=values, engine=engine, context=context)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/addons/web_editor/models/ir_ui_view.py", line 29, in render
    return super(view, self).render(cr, uid, id_or_xml_id, values=values, engine=engine, context=context)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/addons/base/ir/ir_ui_view.py", line 1065, in render
    return self.pool[engine].render(cr, uid, id_or_xml_id, qcontext, loader=loader, context=context)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/addons/base/ir/ir_qweb.py", line 253, in render
    return self.render_node(element, qwebcontext, generated_attributes=qwebcontext.pop('generated_attributes', ''))
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/addons/base/ir/ir_qweb.py", line 296, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/addons/base/ir/ir_qweb.py", line 447, in render_tag_call
    d[0] = self.render_element(element, template_attributes, generated_attributes, d)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/addons/base/ir/ir_qweb.py", line 296, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/addons/base/ir/ir_qweb.py", line 296, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/addons/base/ir/ir_qweb.py", line 296, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/addons/base/ir/ir_qweb.py", line 296, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/addons/base/ir/ir_qweb.py", line 296, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/addons/base/ir/ir_qweb.py", line 434, in render_tag_if
    return self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/addons/base/ir/ir_qweb.py", line 296, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/addons/base/ir/ir_qweb.py", line 296, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/addons/base/ir/ir_qweb.py", line 390, in render_tag_foreach
    raise QWebException("foreach enumerator %r is not defined while rendering template %r" % (expr, template), template=template)
QWebException: foreach enumerator 'shipping_countries' is not defined while rendering template 907

Any ideas please?

Thanks in advance!

**Comment by lukebranch** [comment] 2015-11-14 05:04
@kkoci ,

I highly recommend seeing if you can reproduce this issue on the runbots here:

http://runbot.odoo.com

just choose the 9.0 branch and click the blue button to access an instance with the latest code updates. The login is:

admin
admin

If you are able to reproduce the issue on a clean runbot then I would recommend posting detailed step by step points for steps to reproduce, and also creating a screencapture demonstrating the whole process using licecap found here:

http://www.cockos.com/licecap/

**Comment by kkoci** [comment] 2015-11-14 06:11
Good! Thanks for the quick response, going to try it, and write back!

**Comment by kkoci** [comment] 2015-11-14 06:21
Hi, I chose one runbot http://112500-9-0-32ce41.runbot6.odoo.com/

Logged in, but almsot all modules are installed, I don't think I can reproduce exactly the same situation there, I didn't customized that module thought.

Could you please enlighten me on how to use these runbots? I mean, Is this the way I'll see them? All modules already installed?

**Comment by kkoci** [comment] 2015-11-14 06:24
For example, I see delivery module installed, but cannot see it's menu on Sales->Delivery

**Comment by kkoci** [comment] 2015-11-14 06:27
Sorry, yes, them odule is installed on that runbot, and yes there is the menu, can't reproduce it though

I'm going to check what pull I'm using to see if I can reproduce it.

**Comment by kkoci** [comment] 2015-11-14 06:40
Ok, there is a weird behavior if I disable all three delivery methods on backend.

If I go to the website, and try to process a checkout, the system presents a select field, called 'country'

But I don't have any country to add on it, it's really weird.

I mean, the select field should show all contries on the system, but doesn't show any and I just can't finish the checkout

**Comment by lukebranch** [comment] 2015-11-14 06:49
@kkoci ,

no problem. From experience i've found trying to reproduce the issue on the latest pull on the runbots is the best way to check to see if it's a bug in Odoo, or just a wrong configuration or setup on your development server.

I'd recommend first trying to do a git pull (if you installed by cloning the odoo git repo) and then at the command line do:

sudo su odoo

cd /opt/odoo/odoo-server     *(this should just be wherever your Odoo is installed, might also be called openerp-server depending on how you installed it)*

./openerp-server --update=all -c /etc/odoo-server.conf    *(again this file name and location may depend on how you installed odoo)*

Next open another terminal window, login to your server over SSH (unless you're running locally) and then do the following:

sudo tail -f /var/log/odoo/odoo-server.log    *(this log location may again depend on how you installed odoo)*

You should leave this running for quite a while and just watch the log as it goes through each module updating each one by one. Wait till it's gone through all modules in alphabetical order and try and access your odoo instance in the browser while it's still running in update mode.

Once you can access your instance in the browser you can just do a *ctrl + c* to cancel odoo running in update mode, then do the following at the terminal:

exit    *this will exit you out of your odoo user and back to your root or whatever other user you were using*

sudo service odoo-server start     *this will start again your odoo service - this may differ depending on how you installed odoo*

Then login to your odoo instance and try reproduce the error again.

When I first started playing around with 8.0 quite often i've tried making some minor modifications in the website code editor or similar without thinking, that inevitably bricked my odoo website. The easiest way to check is go to runbots and try there, second step is upgrading all modules in the instance to try and wipe out any customisations made.

Please make absolutely sure you backup your filesystem and database before attempting any of these things if you have anything you need to keep in there just to be safe.

**Comment by lukebranch** [comment] 2015-11-14 06:53
@kkoci ,

This is because there is no delivery method for those products.

If you check the select box below that with the options:

Ship to the same address
-- Create New Address --

you'll find the countries re-appear if you choose --Create New Address --. This is functioning as designed and is not a bug, but a feature.

What exactly are you selling? Is it digital products that don't need a delivery address, or do you simply not require a delivery charge?

**Comment by kkoci** [comment] 2015-11-15 03:01
Alright, yes, it is because of a modification I made, I'm sorry

Btw, do you have any advice you can give me aobut modifying templates on odoo website environment?

I think is more sane to duplicate every template and make one view of my own, for any view I want to customize though.

**Comment by lukebranch** [comment] 2015-11-15 10:26
@kkoci ,

I would recommend learning how to make a basic Odoo module to retain your settings in. Building a module with your view modifications is actually not as hard as it might sound and is a great way of packaging up your modifications/customisations into a module you can install on any odoo database.

I have not yet played around with version 9.0 yet, although I do plan to in the future. I think roughly the same rules will apply between version 8.0 and version 9.0.

Here's a post I did awhile back regarding some basics on extending Odoo themes:

https://www.odoo.com/forum/help-1/question/new-bootstrap-theme-on-website-builder-58809

I'd highly recommend getting this book (targeted at 8.0):

https://essentials.odoo.com/page/homepage

and the online documentation targeted at 8.0 and 9.0:

https://www.odoo.com/documentation/8.0/
https://www.odoo.com/documentation/9.0/

the other option is purchasing one of the themes from the app store and picking it apart to see how it works. This is how I learnt the basics for theme development in odoo.

Regarding building a module it's the recommended way to make modifications as if you do upgrades on your odoo instance in the website or website_sale modules, your customisations will be kept intact, rather than wiped out by the upgrades.

With this issue i'd recommend closing it as it is not a bug. Myself and others can help you out on the mailing list or community forum.

**Comment by kkoci** [comment] 2015-11-15 17:27
Thank you very much Luke

Going to follow your guidelines, very kind from you, cheers.

**Closed** 2015-11-15 17:28 UTC

**Comment by lukebranch** [comment] 2015-11-15 18:05
@kkoci ,

no problem, glad I could help.
