### ISSUE TITLE
OdooV8 Uncaught TypeError: Cannot read property 'facet' of undefined

### ISSUE THREAD

**Issue by GunalanD95** [odoo/odoo#68287] opened 2021-03-24 09:47 UTC
Impacted versions: odoo 8

Steps to reproduce:

Current behavior: shows error when trying to search something in search bar

Expected behavior:

error :
Odoo Client Error
Uncaught TypeError: Cannot read property 'facet' of undefined
http://localhost:8069/web/js/web.assets_backend/34a5a0d:3361

**Comment by pedrobaeza** [comment] 2021-03-24 09:52
Sorry, but 8.0 is a deprecated version that is already not being supported, so any bug report about this old version won't be attended, and thus I close this issue. Please check if the problem is still there in new versions, and if so, you can open a new issue regarding that version.

Thanks for your comprehension.

**Closed by pedrobaeza** 2021-03-24 09:52 UTC
