### ISSUE TITLE
Global Discount in POS Orders is adding to the total instead of substract

### ISSUE THREAD

**Issue by wguerram** [odoo/odoo#22314] opened 2018-01-17 21:17 UTC
Impacted versions:
11
Steps to reproduce:

1. Enable Global discount in Odoo POS
2. Create an order, scan some products.
3. Press the discount button.
4. Apply the discount.

Current behavior:

The discount is adding to the Total instead of substract.

Expected behavior:

When adding a discount the discounted value should substract from the Total.

Video/Screenshot link (optional):

**Comment by pimodoo** [comment] 2018-02-21 13:14
Hello,

I've just tried to reproduce your issue, and the global discount is well removed from the total. Could you confirm me that the problem is fixed on your side.

Best regards

**Closed by pimodoo** 2018-02-21 13:14 UTC
Labels: 11.0, Logistics
