### ISSUE TITLE
Odoo V13: Traceback when open product view from purchase user.

### ISSUE THREAD

**Issue by nimeshcontractor** [odoo/odoo#40021] opened 2019-11-08 11:51 UTC
Impacted versions: V13

Steps to reproduce: Create a user with purchase user access.
Go to Prurchase -> product -> Product

you will face traceback
Current behavior: facing traceback when purchase user click on product menu,

Expected behavior: 
It should open product view.

Video/Screenshot link (optional):

![product error](https://user-images.githubusercontent.com/7592468/68474702-22a17c80-024c-11ea-9f9f-921de63c2e91.png)

**Comment by sswapnesh** [comment] 2019-11-08 14:34
Duplicate of https://github.com/odoo/odoo/issues/39885

**Closed** 2019-11-08 16:19 UTC
Labels: 13.0, Logistics
