### ISSUE TITLE
[11.0] Sales: User: Own Documents Only

### ISSUE THREAD

**Issue by bhaveshselarka** [odoo/odoo#40630] opened 2019-11-21 13:19 UTC
Impacted versions: 11.0

Steps to reproduce

    Create a user
    Set permission to only Sales and group: See Own Documents

Current behavior:

Can see all orders and quations.  

Expected behavior:

Only can see his orders.

Video/Screenshot link (optional):

http://696035-11-0-896127.runbot27.odoo.com/web

user : sales@gmail.com
pass : sales@gmail.com

**Comment by bhaveshselarka** [comment] 2019-11-21 13:20
@pedrobaeza @Yenthe666 @edsersolis @gustavovalverde

**Comment by pedrobaeza** [comment] 2019-11-21 13:21
Please specify which other permissions have you set in which user.

**Comment by bhaveshselarka** [comment] 2019-11-21 13:24
<img width="1680" alt="Screenshot 2019-11-21 at 6 53 58 PM" src="https://user-images.githubusercontent.com/7733043/69341835-550d9980-0c90-11ea-90f9-16bfcfda0708.png">
![Uploading Screenshot 2019-11-21 at 6.54.09 PM.png…]()

**Comment by bhaveshselarka** [comment] 2019-11-21 13:24
<img width="1680" alt="Screenshot 2019-11-21 at 6 54 09 PM" src="https://user-images.githubusercontent.com/7733043/69341862-622a8880-0c90-11ea-8230-252b9f603ff4.png">

**Comment by pedrobaeza** [comment] 2019-11-21 13:26
Please see my comment about the other permissions.

**Comment by bhaveshselarka** [comment] 2019-11-21 13:28
Have not updated any of the default access rights or modify any group aceess.

**Comment by bhaveshselarka** [comment] 2019-11-21 13:36
<img width="1673" alt="Screenshot 2019-11-21 at 6 52 10 PM" src="https://user-images.githubusercontent.com/7733043/69342660-06f99580-0c92-11ea-8047-6b1843657dcf.png">

**Comment by bhaveshselarka** [comment] 2019-11-21 13:45
#40565

**Comment by pedrobaeza** [comment] 2019-11-21 13:50
That record rule change is correct, as the field is the same. Have you really tried with real data? Maybe demo data are not computing that field and that's why it fails in runbot.

**Comment by bhaveshselarka** [comment] 2019-11-21 14:02
Yes tried with new records as well. its seems buggy.

**Comment by pedrobaeza** [comment] 2019-11-21 15:19
@bhaveshselarka the mentioned PR has nothing to do with this potential issue, as it modifies the `sale.order.line` record rule, not the `sale.order` one which you are mentioning.

**Comment by pedrobaeza** [comment] 2019-11-21 15:23
The problem comes from rule "Expense Employee can read confirmed SO" and it was tracked for 12.0 in  #34131. The same fix should be applied for 11.0. Can you please do a PR with it?

**Comment by Yenthe666** [comment] 2021-03-06 14:18
Hi,

Sorry but Odoo V11 is no longer supported officially so we have to close this one. The PR wouldn't be accepted anymore either.
Since it is fixed in V12 there is nothing more to do.

Regards,
Yenthe

**Closed by Yenthe666** 2021-03-06 14:18 UTC
Labels: 11.0
