### ISSUE TITLE
statement = statements_by_journal_id[payment_method.cash_journal_id.id] KeyError: 226

### ISSUE THREAD

**Issue by HaydarZaraki** [odoo/odoo#63803] opened 2020-12-27 10:28 UTC
Impacted versions: 13 Enterprise

Steps to reproduce: 
1.Open Pos Session
2.Click (Validate Closing and Post Entries) button

Current behavior:
Gives the following error
statement = statements_by_journal_id[payment_method.cash_journal_id.id] KeyError: 226
Expected behavior:
Close the session
Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment] 2020-12-27 13:09
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Closed** 2021-02-01 22:19 UTC
Labels: Need information
