### ISSUE TITLE
Import csv file from another DB.

### ISSUE THREAD

**Issue by marcelompz** [odoo/odoo#14352] opened 2016-11-16 16:43 UTC
Impacted versions:
9.0
Steps to reproduce:
Import csv file from another DB.
Current behavior:
Can't even showme the page to upload file.
Expected behavior:
Upload file to validate fields of the DB.
Video/Screenshot link (optional):
![image](https://cloud.githubusercontent.com/assets/17249379/20356205/8c927124-ac02-11e6-96be-aa0d58304abe.png)

**Comment by Yenthe666** [comment] 2017-12-13 10:46
Hi @marcelompz,

Could you try this again please? I was not able to reproduce this anymore.

**Comment by Yenthe666** [comment] 2018-03-19 09:42
Closing as there has been no feedback on this issue.

**Closed by Yenthe666** 2018-03-19 09:42 UTC
Labels: 10.0, Need information
