### ISSUE TITLE
TypeError: MailTemplate.send_mail() got an unexpected keyword argument 'email_values'

### ISSUE THREAD

**Issue by shazzwazz20** [odoo/odoo#122883] opened 2023-05-30 11:42 UTC
Impacted versions: 16

Steps to reproduce: Create a login user and click button Invite to use 2FA

Current behavior: Getting error on button click
TypeError: MailTemplate.send_mail() got an unexpected keyword argument 'email_values'

Expected behavior:
Email should be send

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment] 2023-05-30 11:50
hi @shazzwazz20 ,
this is not able to reproduce in the odoo runbot, may be you are not using the latest source code of odoo 16.
please see if you can reproduce in the runbot, and also try updating the source code to its latest.

below attaching screen shot from runbot:

![Screenshot from 2023-05-30 14-50-24](https://github.com/odoo/odoo/assets/27989791/76265536-ca87-482e-bac9-e3ed89c1eef9)

thanks

**Comment by vava-odoo** [comment] 2023-06-12 07:41
Hi @shazzwazz20 
Looks like the problem is solved, so I'm closing this. Don't hesitate to re-open if the problem is not solved.

**Closed by vava-odoo** 2023-06-12 07:41 UTC
