### ISSUE TITLE
TypeError: Cannot read property 'focusableElement' of null

### ISSUE THREAD

**Issue by slakk** [odoo/odoo#69894] opened 2021-04-27 09:46 UTC
Impacted versions: 14

Steps to reproduce: add Optional Products 

Current behavior: error

Expected behavior:

Video/Screenshot link (optional): https://www.loom.com/share/1758de75d9834d82a0d5b30290b8d322

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment] 2021-04-27 09:47
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by slakk** [comment] 2021-04-27 10:15
not found possibility check it's here http://runbot.odoo.com/runbot
make new product (sales-products-create) test1
make some optional products (edit test1-sales-optional products->create color1, color2)
make new quatations order -> add product test1 to order line
on popup configure click on add to cart on color1 or color2
click on confirm popup.see error message from title

**Comment by pedrobaeza** [comment] 2021-04-27 10:16
Are you telling that you are not able to reproduce it on runbot?

**Comment by slakk** [comment] 2021-04-27 10:20
im check my testcase on http://runbot.odoo.com/runbot
and not see problem. i will try update my version and will previous check on runbot
My apologies

**Comment by pedrobaeza** [comment] 2021-04-27 10:25
OK. I'm closing this now. If you get to reproduce the problem in runbot, please come back. Update your installation with latest source code, and update the modules in your DB.

**Closed by pedrobaeza** 2021-04-27 10:25 UTC
Labels: Need information

**Comment by slakk** [comment] 2021-04-27 13:20
problem actual if add column checkbox type to sale.order.line
on http://runbot.odoo.com/runbot cant check

**Comment by Yenthe666** [comment] 2021-04-30 12:49
You have https://github.com/odoo/odoo/issues/69938 for that :)
