### ISSUE TITLE
using combination of arabic and english text creates problem in pdf reports

### ISSUE THREAD

**Issue by chinu1994** [odoo/odoo#55429] opened 2020-08-04 19:58 UTC
Impacted versions: 13.0

Steps to reproduce: create invoice and put combination of english and arabic

Current behavior: the description in invoice line does not match with the invoice line in pdf report

Expected behavior: the description in invoice line should match with the invoice line in pdf report

Video/Screenshot link (optional):
![Screenshot from 2020-08-05 01-19-10](https://user-images.githubusercontent.com/20063717/89338892-e3a93600-d6ba-11ea-9408-ec396610fb78.png)
![Screenshot from 2020-08-05 01-19-26](https://user-images.githubusercontent.com/20063717/89338896-e572f980-d6ba-11ea-9073-c5501ba4c861.png)

**Comment by pedrobaeza** [comment] 2020-08-05 06:44
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Yenthe666** [comment] 2020-08-07 06:34
Plus isn't that due to the RTL / LTR side of Arabic in combination with EN?

**Closed** 2023-04-07 14:27 UTC
Labels: Need information
