### ISSUE TITLE
website_sale buy a product with 0 sale price returns error

### ISSUE THREAD

**Issue by hviniciusg** [odoo/odoo#32138] opened 2019-03-26 23:04 UTC
Impacted versions:
12.0

Steps to reproduce:
1. Create a product with sale price 0
2. Go to website and buy the product

Current behavior:
When you get to the step to confirm the order, you get the following error:
Error:
```
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2765, in read
    self._read_from_database(stored, inherited)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2892, in _read_from_database
    cr.execute(query_str, params)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.DataError: invalid input syntax for integer: "False"
LINE 5: ...er__name"."res_id") WHERE "payment_acquirer".id IN ('False')
                                                               ^
```

Expected behavior:
When you press the confirm order button on the website with a total of 0. the order should be processed and no further action required.

this is  a use case for adding a trial or free products on your website.

Video/Screenshot link (optional):
http://g.recordit.co/6CfBvewXWt.gif

**Comment by pedrobaeza** [comment] 2019-03-27 08:21
This has nothing to do with the product with price 0, but with the absence of a payment carrier defined.

Closing as no apparent issue.

**Closed by pedrobaeza** 2019-03-27 08:21 UTC

**Comment by hviniciusg** [comment] 2019-03-27 13:00
Thanks for the reply, what do you mean that there is no payment carrier defined? when i process a payment for other products, i have no problems. just when i use a 0 price product.

**Comment by pedrobaeza** [comment] 2019-03-27 13:03
My answer was due to the stack trace:
```
LINE 5: ...er__name"."res_id") WHERE "payment_acquirer".id IN ('False')
```

Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

**Comment by hviniciusg** [comment] 2019-03-27 13:14
Yes, i created a product with sale price 0 and cost 0, published on the website, proceed to checkout an a 500 error is generated, here it is the escreen capture:

http://recordit.co/whD1wzPtlp

**Comment by hviniciusg** [comment] 2019-03-27 13:17
On version 11, the order is created, but the payment information is not displayed. the error is related with the selection of the payment provider, it seams that when 0 is used. a False value is inserted instead of the ID of the payment provider, hense the exeption.

**Comment by sswapnesh** [comment] 2019-03-27 19:15
@pedrobaeza  
I am able to reproduce this on latest Runbot build http://487479-12-0-06cd3e.runbot20.odoo.com/shop/product/ssssssssss-1882

**Comment by pedrobaeza** [comment] 2019-03-27 19:16
OK, he has put a new issue, so no need to reopen this one.

**Comment by hviniciusg** [comment] 2019-03-27 19:39
sorry guys. i opened a new one. since i interpreted that something was wrong with this one. my bad
