### ISSUE TITLE
Odoo 10 bug

### ISSUE THREAD

**Issue by CakJuice** [odoo/odoo#14036] opened 2016-10-28 03:21 UTC
Today i was update my odoo 10 in ubuntu 16.04, and have some bug:

File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 357, in **getattr**
    return self._attrs[name]
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 357, in __getattr__
    return self._attrs[name]
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 357, in __getattr__
    return self._attrs[name]
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 357, in __getattr__
    return self._attrs[name]
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 357, in __getattr__
    return self._attrs[name]
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 357, in __getattr__
    return self._attrs[name]
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 357, in __getattr__
    return self._attrs[name]
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 357, in __getattr__
    return self._attrs[name]
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 357, in __getattr__
    return self._attrs[name]
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 357, in __getattr__
    return self._attrs[name]
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 357, in __getattr__
    return self._attrs[name]
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 357, in __getattr__
    return self._attrs[name]
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 357, in __getattr__
    return self._attrs[name]
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 357, in __getattr__
    return self._attrs[name]
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 357, in __getattr__
    return self._attrs[name]
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 357, in __getattr__
    return self._attrs[name]
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 357, in __getattr__
    return self._attrs[name]
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 357, in __getattr__
    return self._attrs[name]
RuntimeError: maximum recursion depth exceeded
Logged from file fields.py, line 462

**Comment by pedrobaeza** [comment] 2016-10-28 08:01
We have this problem too

**Comment by yelizariev** [comment] 2016-10-28 11:32
The problem was add by @rco-odoo in https://github.com/odoo/odoo/commit/cae04ba1d3782f89e78b7ecf68edb89269b2fff7

**Comment by yelizariev** [comment] 2016-10-28 11:42
I state it, because ``msg`` in ``getMessage`` has value

*"Field %s: parameter %r is no longer supported; use %r instead."*

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 852, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 725, in format
    return fmt.format(record)
  File "/home/iii/odoo-10/odoo/netsvc.py", line 108, in format    return DBFormatter.format(self, record)
  File "/home/iii/odoo-10/odoo/netsvc.py", line 102, in format
    return logging.Formatter.format(self, record)
  File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
  File "/home/iii/odoo-10/odoo/fields.py", line 388, in __str__
    return "%s.%s" % (self.model_name, self.name)
  File "/home/iii/odoo-10/odoo/fields.py", line 357, in __getattr__
    return self._attrs[name]
  File "/home/iii/odoo-10/odoo/fields.py", line 357, in __getattr__
    return self._attrs[name]
  File "/home/iii/odoo-10/odoo/fields.py", line 357, in __getattr__
    return self._attrs[name]
  File "/home/iii/odoo-10/odoo/fields.py", line 357, in __getattr__
    return self._attrs[name]
  File "/home/iii/odoo-10/odoo/fields.py", line 357, in __getattr__
```

**Comment by kkinateder** [comment] 2016-10-29 10:01
#14036

**Comment by yelizariev** [comment] 2016-10-29 12:19
According to #14057, the problem is not caused by cae04ba.

**Comment by yelizariev** [comment] 2016-10-29 12:24
Though, possible workaround could be update cae04ba as following:

        self.set_all_attrs(attrs)

        # check for renamed attributes (conversion errors)
        for key1, key2 in RENAMED_ATTRS:
            if key1 in attrs:
                _logger.warning("Field %s: parameter %r is no longer supported; use %r instead.",
                                self, key1, key2)

i.e. put set_all_attrs before printing warning

(I am not able to check the solution now)

**Comment by CakJuice** [comment] 2016-11-01 04:51
the bug is fixed now.

**Comment by CakJuice** [comment] 2016-11-01 05:08
sorry my false, bug not found when i try build a new module (openacademy module) with new database.
but it still appear in my previous database

**Comment by yelizariev** [comment] 2016-11-01 06:00
@CakJuice the error appears if there is a module with ``index`` or ``digits_compute`` attribute in some field

**Comment by CakJuice** [comment] 2016-11-02 04:14
@yelizariev nope. @pedrobaeza @kkinateder in my case, the error caused by fields.Selection() which has `select=True` attribute. Just remove that attribute and the error has gone.

**Comment by yelizariev** [comment] 2016-11-02 04:37
You are right, ``select`` or ``digits_compute``.

But why do you close the issue? Was it fixed? If not, how do people have to know, that reason in obsolete attribute name? They have to get warning (https://github.com/odoo/odoo/commit/cae04ba1d3782f89e78b7ecf68edb89269b2fff7) instead of this recursion error.

**Comment by CakJuice** [comment] 2016-11-02 05:08
oops, sorry. i didn't see [cae04ba](https://github.com/odoo/odoo/commit/cae04ba1d3782f89e78b7ecf68edb89269b2fff7). i was think that error caused by deprecated attribute in my module.
i'm new in odoo and i get job to upgrading several module from old API.

**Comment by kkinateder** [comment] 2016-11-10 06:26
https://github.com/odoo/odoo/pull/14235

**Comment by eLBati** [comment] 2016-11-16 07:47
Same problem here.

@CakJuice could you extend the title, so that the issue can be identified more easily?
Thanks

**Comment by kkinateder** [comment] 2016-11-16 13:47
@elBati https://github.com/odoo/odoo/pull/14235

**Closed** 2016-11-17 12:58 UTC
