### ISSUE TITLE
Calendar with timezone display event wrong

### ISSUE THREAD

**Issue by shurshilov** [odoo/odoo#72767] opened 2021-06-25 09:27 UTC
Impacted versions:
14.0-20210315 
TZ +3 Europe/Moscow

Steps to reproduce:
create calendar event and change datetime to last month day and time in period (24.00-timezone)

Current behavior:
![screenshot-127 0 0 1_52553-2021 06 25-12_18_28](https://user-images.githubusercontent.com/11828278/123402592-91158880-d5b0-11eb-9b95-a51f2febe0d1.png)
![screenshot-nimbus-capture-2021 06 25-12_20_37](https://user-images.githubusercontent.com/11828278/123402608-9541a600-d5b0-11eb-930f-c18b3fccd1f9.png)
![screenshot-127 0 0 1_8069-2021 06 25-12_23_46](https://user-images.githubusercontent.com/11828278/123402615-970b6980-d5b0-11eb-8c00-03aab71c7195.png)

Expected behavior:
31 may in 22 UTC should display as 1 JUNE in TZ +3(for example) but it always steel may
Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment] 2021-06-25 09:33
That calendar is shown in the timezone of the browser, so you should check which is the one used.

Closing as no bug, but expected behavior.

**Closed by pedrobaeza** 2021-06-25 09:33 UTC

**Comment by shurshilov** [comment] 2021-06-25 09:35
> Этот календарь отображается в часовом поясе браузера, поэтому вам следует проверить, какой из них используется.
> 
> Закрытие как отсутствие ошибки, но ожидаемое поведение.

My browser TZ +3 and event as 31 may 22 UTC should be in 1 JUNE 01.00
Is it really not clear that this is a mistake, I gave an example with a grouping, it shows this event for JUNE and the calendar for MAY !

**Comment by shurshilov** [comment] 2021-06-25 09:39
> That calendar is shown in the timezone of the browser, so you should check which is the one used.
> 
> Closing as no bug, but expected behavior.

I described everything to you as a schoolboy. With red arrows and text. Read carefully!

**Comment by Yenthe666** [comment] 2021-06-25 09:41
Don't be so rude and offensive. It gets you nowhere and will only end up in nobody willing to help you.
Pedro, it might be a bug though, I've seen similar reports in the past..

**Comment by shurshilov** [comment] 2021-06-25 09:42
![screenshot-nimbus-capture-2021 06 25-12_41_14](https://user-images.githubusercontent.com/11828278/123405691-bd320900-d5b2-11eb-95d1-0e0405d948a5.png)

**Comment by pedrobaeza** [comment] 2021-06-25 09:44
Look the same report and the answer here: https://github.com/odoo/odoo/issues/66754#issuecomment-786016896

**Comment by shurshilov** [comment] 2021-06-25 09:48
> Look the same report and the answer here: [#66754 (comment)](https://github.com/odoo/odoo/issues/66754#issuecomment-786016896)

 Yes, I am an odoo developer myself) And I can say that the timezone is used in the frontend, you made a mistake again. I also took a screenshot when we make a grouping in the ode, a request is sent from the FRONTEND to the view sheet and the timezone is TAKEN into ACCOUNT there and it works correctly) Next, I sent you my timezone from the js console and it is not UTC. Therefore, the fact that you threw off the link can of course be sent to ordinary users, but not to developers, because the answer given there is not correct.

**Comment by shurshilov** [comment] 2021-06-25 09:55
I can say one thing - ordinary calendar users will not have this error, since they do not have access to change datetime, they can only change date. BUT if you do like me and change the datetime there will be an error. That is why very few people informed you about it since it does not appear out of the odoo box. And  js console TZ != User preference tz)))

**Comment by shurshilov** [comment] 2021-06-25 09:57
> Don't be so rude and offensive. It gets you nowhere and will only end up in nobody willing to help you.
> Pedro, it might be a bug though, I've seen similar reports in the past..

Sorry, This is because pedro did not rate my screenshots.)))

**Comment by shurshilov** [comment] 2021-06-25 10:07
And in the link that you sent me it is about the PREFERENCE timezone, and I'm talking about the js console BROWSER TZ just the same that you answered with it. 
in general, NOT WORK BROWSER TZ and NOT WORK USER PREFERENCE TZ)))))))))
It's sad that you won't understand this)

**Comment by pedrobaeza** [comment] 2021-06-25 10:12
No, I don't understand you and it's not a pleasure to understand you with that attitude. Screenshors in cyrillic doesn't help either. Anyways, it still seems that it's due to any kind of manipulation by your part, but if not, and you are a developer, then propose a pull request with the solution, and I don't intervene in that part. Keeping opened an issue that it's going to die opened because nobody cares, and that's why I am so extreme closing them.

**Comment by Yenthe666** [comment] 2021-06-25 10:19
On a sidenote: can you reproduce it on a runbot @shurshilov?

**Comment by shurshilov** [comment] 2021-06-25 10:23
> Нет, я не понимаю вас, и мне неприятно понимать вас с таким отношением. Скриншоты кириллицей тоже не помогают. В любом случае, все еще кажется, что это произошло из-за каких-либо манипуляций с вашей стороны, но если нет, и вы разработчик, то предложите запрос на перенос с решением, и я не вмешиваюсь в эту часть. Сохраняя открытым вопрос, что он умрет открытым, потому что всем плевать, и поэтому я так решительно закрываю их.



> Нет, я не понимаю вас, и мне неприятно понимать вас с таким отношением. Скриншоты кириллицей тоже не помогают. В любом случае, все еще кажется, что это произошло из-за каких-либо манипуляций с вашей стороны, но если нет, и вы разработчик, то предложите запрос на перенос с решением, и я не вмешиваюсь в эту часть. Сохраняя открытым вопрос, что он умрет открытым, потому что всем плевать, и поэтому я так решительно закрываю их.

The calendar works only in UTC,

**Comment by shurshilov** [comment] 2021-06-25 10:24
> Нет, я не понимаю вас, и мне неприятно понимать вас с таким отношением. Скриншоты кириллицей тоже не помогают. В любом случае, все еще кажется, что это произошло из-за каких-либо манипуляций с вашей стороны, но если нет, и вы разработчик, то предложите запрос на перенос с решением, и я не вмешиваюсь в эту часть. Сохраняя открытым вопрос, что он умрет открытым, потому что всем плевать, и поэтому я так решительно закрываю их.

Sorry, it was just a joke, don't be offended;)

**Comment by shurshilov** [comment] 2021-06-25 10:35
> On a sidenote: can you reproduce it on a runbot @shurshilov?



> Нет, я не понимаю вас, и мне неприятно понимать вас с таким отношением. Скриншоты кириллицей тоже не помогают. В любом случае, все еще кажется, что это произошло из-за каких-либо манипуляций с вашей стороны, но если нет, и вы разработчик, то предложите запрос на перенос с решением, и я не вмешиваюсь в эту часть. Сохраняя открытым вопрос, что он умрет открытым, потому что всем плевать, и поэтому я так решительно закрываю их.

look, grouping and calendar view dont sync.
I found another bug but from the grouping side)
I just tested again and see
![image](https://user-images.githubusercontent.com/11828278/123412161-f3bf5200-d5b9-11eb-884e-48af4fcb1857.png)
![image](https://user-images.githubusercontent.com/11828278/123412189-ff127d80-d5b9-11eb-983e-7c9ea5fee924.png)
![image](https://user-images.githubusercontent.com/11828278/123412206-03d73180-d5ba-11eb-8d28-5394bf629c65.png)
I think in group one more domain is missing

**Comment by shurshilov** [comment] 2021-06-25 10:37
in short, you have two bugs. Sometimes calendar works in UTC mode as the first error, but this is with my manipulation and the duration is 0. The second error is missing the domain in the grouping when events will be late in grouping by the end date. More details will only be sent to you the code with the correction)))

**Comment by shurshilov** [comment] 2021-06-25 11:51
> On a sidenote: can you reproduce it on a runbot @shurshilov?

I found error its amazing!
Datetime when come from odoo server add 1 second)))
server time for example 23:59:59 
js time 00:00:00 and it will **next day**
It looks like the whole ode has an error of 1 second, that's MEGA BUG!

![screenshot-127 0 0 1_52553-2021 06 25-14_49_16](https://user-images.githubusercontent.com/11828278/123420741-9d0b4580-d5c4-11eb-9013-1223990d16f6.png)
![screenshot-nimbus-capture-2021 06 25-14_48_34](https://user-images.githubusercontent.com/11828278/123420746-9e3c7280-d5c4-11eb-82ed-c5f566916327.png)
