### ISSUE TITLE
odoo11 workers=1 creates directories in /tmp until the server has no space left.

### ISSUE THREAD

**Issue by diezcode** [odoo/odoo#29796] opened 2018-12-28 15:11 UTC
Impacted versions:
11.0

Steps to reproduce:
setup odoo11 with worker=1 and max_cron_thread = 1
run any xmlrpc api that updates record on res.partner

Current behavior:
odoo writes filestore files in /tmp and this will let no space left on the ubuntu server.

Expected behavior:
shouldn't write filestore in /tmp

Video/Screenshot link (optional):
/tmp directory full with data like this writen with the user odoo:
tmp32sg02
tmp5s256s1
tmp37sb2df6

Information: filestore is not set in odoo, it uses the default storage directory in /odoo/.local/share/Odoo

**Comment by Yenthe666** [comment] 2018-12-28 15:36
@xmo-odoo probably for you to check?

**Comment by pedrobaeza** [comment] 2018-12-31 10:11
This seems for me a bad deployment...

**Comment by diezcode** [comment] 2019-01-02 07:13
@pedrobaeza what do you mean by that?

**Comment by pedrobaeza** [comment] 2019-01-02 08:41
@diezcode I mean that I don't have that problem following https://www.odoo.com/documentation/11.0/setup/install.html or using Docker.

**Comment by xmo-odoo** [comment] 2019-01-09 12:12
@diezcode can't help any more than @pedrobaeza at this point, I can't reproduce any sort of /tmp filling up on a base installation of Odoo upon e.g. changing the name of a partner. Furthermore this doesn't look like a filestore thing, filestore files are specifically stored as hashed names (e.g. `92/9272fdee77faa2970921cec7bfc2c739908406c6`) and always explicitly stored in a `filestore` subfolder of the `data_dir` base folder. Likewise werkzeug session files.

This looks like uncleaned temporary file, but AFAIK there are relatively few uses of `tempfile` in Odoo and they're for very explicit & expensive operations (e.g. dumping/restoring DBs, importing/updating translations, that sort of stuff) so even if they were to leak their tempfiles they wouldn't lead to unbounded /tmp growth under normal operations.

You'd need to investigate the source of the issue on your system e.g. is it specific actions, which modules are installed, ...

**Comment by pedrobaeza** [comment] 2019-01-09 12:46
@xmo-odoo I think we should close it until further information.

**Closed** 2019-01-09 15:07 UTC
Labels: 11.0, Need information

**Comment by flotho** [comment] 2022-07-27 08:44
I've reproduce this behaviour with many workers and a compile python3.8 version running with odoo 14.
What test can I provide to help here ?

**Comment by flotho** [comment] 2022-07-27 08:46
![image](https://user-images.githubusercontent.com/1043935/181203700-359be578-816e-4d5a-b3ef-775feddbcbb2.png)

and 
![image](https://user-images.githubusercontent.com/1043935/181203846-b365b687-786d-4902-a3d3-e049837d424f.png)

**Comment by xmo-odoo** [comment] 2022-07-27 08:51
> I've reproduce this behaviour with many workers and a compile python3.8 version running with odoo 14. What test can I provide to help here ?

Provide a reliable reproduction case?

**Comment by flotho** [comment] 2022-07-27 10:11
are a list of module and python version a good starting point for you ?

**Comment by xmo-odoo** [comment] 2022-07-28 10:38
> are a list of module and python version a good starting point for you ?

Sure? But above you say that you reproduce the behaviour so maybe detail that?

**Comment by CyrilLijeesh** [comment] 2023-10-03 08:05
Any update on this issue? we are using odoo 16 , configured with 6 workers. each /tmp folder have 6 directory inside. Filestore path we have setup different from default path, and it have the desired files.

**Comment by mfianfa** [comment] 2024-02-13 07:38
I'm facing this issue too, in my case, it's because of backup files. I'm using auto_backup module and somehow, all dump.sql, mainfest.json, and filestore are not removed from tmp folder. I don't know hot to fix it, but now I'm trying to reconfigure the worker (based on the recommendation total worker = (2 x CPU) + 1), and we'll see if it fixes the behavior or not.

**Comment by wsalgadoq** [comment] 2024-05-23 20:52
I had this issue with my db, is there further information about it?

**Comment by andreampiovesana** [comment] 2024-07-01 07:46
I'm facing this issue too, backup files odoo 14 using auto_backup module

**Comment by NachoCodeseda** [comment] 2025-03-24 15:59
This error occurs when the cron job begins creating the backup. It creates temporary files of the filestore that should be deleted upon completion, but the worker running that cron job reaches the 120 second of `limit_time_real` parameter without completing the task. This causes the worker ends without deleting the temporary files and spawns a new worker to perform the backup again. This happens in a loop until the disk is full.
My solution was to increase `limit_time_cpu` and `limit_time_real`.
