### ISSUE TITLE
Readonly attribute doesn't work on 'o_website_form_date' class in website.

### ISSUE THREAD

**Issue by kbirkbr** [odoo/odoo#34588] opened 2019-07-04 12:33 UTC
Impacted versions: 10.0 CE

Steps to reproduce: Create a text input in website with the class of 'form-control o_website_form_input o_website_form_date', and open in the browser. 

Current behavior: The input field looks like readonly, but when i click on the field the date picker shows. 

Expected behavior: The field must be in readonly mode and doesn't shoe the datepicker.

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/11715958/60666998-0fd60000-9e86-11e9-9ea4-5f5dabf2d02b.png)

**Comment by pedrobaeza** [comment] 2019-07-04 12:37
Sorry, this is not an Odoo issue, but a question of custom development. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Closed by pedrobaeza** 2019-07-04 12:37 UTC

**Comment by kbirkbr** [comment] 2019-07-04 12:39
@pedrobaeza , it's not custom development. All the classes i mentioned in the question are provided by Odoo itself. So i think the should provide a solution for this.

**Comment by pedrobaeza** [comment] 2019-07-04 12:42
The problem are not the classes. The problem is what you are trying to achieve with them. If you find a place in Odoo core where they are used this ways and you don't get the intended usage, then it's an issue.

What you are directly asking is: "how to perform with custom development this?" You should do it in forums, and the solution will be another than putting that classes. Maybe you can dig in Odoo for looking for similar behavior and see how it's done there.

**Comment by kbirkbr** [comment] 2019-07-04 12:52
@pedrobaeza , if i remove the class 'o_website_form_date' from the field, the readonly behaviour works fine. So the problem with the same class.

**Comment by pedrobaeza** [comment] 2019-07-04 12:57
As stated, you are trying to achieve something that might not be intended to be done that way. Maybe it's not possible to do what you want, but that's not an Odoo issue, but a missing feature, unless somewhere in Odoo it's implemented that way with that intended behavior. If not, you will need to find another way to do it, or implement yourself custom CSS/JS for that.
