### ISSUE TITLE
[Forum SaaS-6/Master] Flaw in karma calculation for actions of thread owner.

### ISSUE THREAD

**Issue by smack815** [odoo/odoo#6987] opened 2015-06-08 11:40 UTC
There is a small logic error in the way that karma is given and taken away if you are the owner of the thread.

Yes it is correct that an owner of a thread should NOT be rewarded for accepting his/her own answer to their own thread, however they SHOULD be penalized if they decide that their answer was incorrectly accepted.

This runs the risk of deducting too much karma if they accidentally accept their own answer (a zero karma action) and then remove the check mark (a -15 karma action).  However the opposite, which we have today, is much worse.

Currently if another user accepts their answer they are rewarded with 15 karma points, then the owner of the thread can remove the check mark (a zero karma action) and they can then gain 15 additional karma points.

This can be abused easily by any user creating a second account and simply preforming the action over and over.  With as little as 135 clicks of a mouse a user can have an account that has more then 1,000 karma points and do whatever they want in the forums.

This has not been tested on v8 but is current logic of the odoo help forums.

**Comment by Yenthe666** [comment] 2015-06-08 11:42
:+1: the bug is there and I can confirm it. @odony and @antonylesuisse I believe this is something for you guys.
This should be fixed ASAP before it gets abused..

**Comment by Yenthe666** [comment] 2015-06-09 07:49
Actually, @JKE-be I think this might be something for you too. Since you've coded at the website too if I'm not mistaking.

**Comment by JKE-be** [comment] 2015-06-09 12:00
You will have the same problem in many other cases....

User A create a question,
User B marks as solved
User A create a new question
User B marks as solved
User A create a new question
User B marks as solved
...

The only way to avoid it, is to limit the number of karma by day that a user can win...
So the attack will be delayed and maybe the guy will discard the attack.
no ???

**Comment by smack815** [comment] 2015-06-09 12:29
@JKE-be Your example is abuse of clearly defined rules.  And there are many of them.  I see people all the time in the forums that have every answer that they have ever posted with at least one up-voted.  That is abuse of the system.  If you want to detect that you can easily search for that.

The difference with my documented flaw is that if you were to calculate the users karma by viewing all of their posts, up-votes, down-votes and answers accepted... you would get a different karma value.

In your example you would get the same karma value.  So there is no way that your example and mine are the same cases.  If Odoo does not want to close this hole and obvious flaw, they simply need to say that.  Its just that simple.

**Comment by Yenthe666** [comment] 2015-06-09 12:34
@smack815 steady your horses hehe. Both of you have a point.
@JKE-be you have a point that abusing will always be possible and that there are easy ways to gain karma, but the reported issue by smack is different. This is a big loophole in logic (which can be easily avoided). It wouldn't hurt to atleast fix this one.

**Comment by JKE-be** [comment] 2015-06-09 12:42
Hey, I don't say that this bug should be not fixed. It's why this issue is still open.

I just say that the best fix will be to limit the karma that a user can win every day.

(jke with anthony)

**Comment by Yenthe666** [comment] 2015-06-09 12:48
@JKE-be yes a daily limit would be a good overall limit to prevent jumping up too high. But that brings us to the question what is the limit etc.. On a good day you could jump up 100-150 points, as I did last week.
I think a daily quota would be great (max number of upvotes a day, max number of downvotes, max karma a day, ..) but in addition this whole bug should be fixed. When ANYBODY has accepted an answer it should still be unable to be unchecked but afterwards if it is checked again no more karma should be given to the user.

**Comment by smack815** [comment] 2015-06-09 13:01
@JKE-be I am fine with a karma limit but that would address other issues of fraud not this one.

It could be that I am too much of a purist, but I think that your karma value should be something easily computable if you look at the history of your interaction with the forum software.  Yes maybe that is not 100% possible but this logic flaw is quite easily fixable.

Limiting karma is fine however it does not take much karma to be able to do things in the forum.  If you limit karma to 50 a day then helpful people will not be so helpful.  As @Yenthe666 said it's not hard to get 100-200 karma points a day being helpful and having a history of helpful posts.

But even at 50 a day with this flaw I can get that with three up-votes of my own post.  In 10 days I have 500 karma posts.  Now I can do just about anything.

So I really think we are talking about two issues.  /humbly offered opinion.

**Comment by smack815** [comment] 2015-06-12 11:38
@Yenthe666 @JKE-be There is one saving feature to this flaw.  The user who wants to gain the system and earn quick karma needs to have 500 karma points to remove the check on their answer.

So this at the moment could only be used by high karma users to advance their rankings.

**Comment by Yenthe666** [comment] 2015-06-12 12:29
@smack815 alright thats a good plus. I'd propose the following fixes:
<li>This gets pulled up to 1.000 or 2.000 karma</li>
<li>The owner of the thread cannot uncheck his own answer if somebody accepted it (or he loses 15 karma). When the user accepts his own answer there is no karma gain, so thats fine.</li>
<li>An introduction for a max karma gain per day (lets say about 200-250 points?)</li>
<li>???</li>

I think this would be a great improvement.

**Comment by lukebranch** [comment] 2015-06-13 02:04
there seems to be a trend towards using fake accounts to reward other accounts:

This guy for example who's name is 's.a.':
https://www.odoo.com/fr_FR/forum/help-1/user/485558

seems to post vague questions that only contain a title, and then conveniently one of a group of members answers with a very particular answer and it is accepted shortly afterwards.

**Comment by Yenthe666** [comment] 2015-06-13 09:06
@lukebranch I've seen a couple of accounts like that too. Some guys in the top 30 have some strange behaviour too, such as accepted answers within minutes, multiple upvotes on almost all answers while their post is only a few hours old, ...

**Comment by lukebranch** [comment] 2015-06-13 11:37
@Yenthe666 ,

yes, hopefully it's only a few scattered accounts. I know this kind of behaviour is far more difficult to police, and even harder to automate policing in the forums.

**Comment by Yenthe666** [comment] 2018-01-05 10:59
@JKE-be any update on this one? 😉

**Comment by JKE-be** [comment] 2018-01-05 11:13
Meantime, the notion of "flag" has been introduced, and new user needs to wait for the validation.
So that block a lot of spammers already!

**Comment by Yenthe666** [comment] 2018-01-05 11:20
Yep, that is a fact. I guess if you want to you can always cheat but the forum has improved. I guess a close is fine here.

**Closed by Yenthe666** 2018-01-05 11:20 UTC
