### ISSUE TITLE
Odoo Config Yandex Mail service Error

### ISSUE THREAD

**Issue by W360S** [odoo/odoo#13479] opened 2016-09-14 14:08 UTC
Impacted versions:odoo V9
Hello anyone help plz
i have un issue with odoo V9 i have setup yandex mailservice to my odoo system it seem to be sussess full follow setup imap.yandex.com port 993 | smtp.yandex.com port 465
everything test ok but when i try to sent email from mass mailing & other mail then have errors like this.

Mail Delivery Failed
Mail delivery failed via SMTP server 'smtp.yandex.com'.
SMTPSenderRefused: 553
5.7.1 Sender address rejected: not owned by auth user.
bounce-11-mail.mass_mailing.contact-1@mydomain.com
anyone help plz. i try to post in odoo forum but my account could not be posted. plz hlep.

**Comment by W360S** [comment] 2016-09-17 04:33
Hello anyonel help plz?

**Comment by voti** [comment] 2016-12-13 17:33
I got same error,are you fixed？

**Comment by W360S** [comment] 2016-12-13 17:37
The error fixed :) you @voti just need to go to Settings > General Settings > Alias Domain < clear any text in the Alias Domain then apply. it will work > test now you can change to the new Alias Domain do main.

**Comment by W360S** [comment] 2016-12-20 02:30
i think after i have update to the lasted version

**Comment by mart-e** [comment] 2017-01-03 15:26
Hello,

Sorry but this is an issue on the configuration of the email server.
The error said "Sender address rejected: not owned by auth user."
If you search this error on the web, you should get more info on the problem.

However it is not a bug on Odoo so closing the issue.

**Closed by mart-e** 2017-01-03 15:26 UTC

**Comment by W360S** [comment] 2017-01-03 15:30
Do you recommended where to fixed this error? i try many ways but error not fixed. plz help

**Comment by voti** [comment] 2017-01-03 23:43
@W360S as @mart-e said,it is not a bug on Odoo. you need config your email server.
My solution : 
install & config postfix + dovecot in my host. 
easy way to build that,by docker-mailserver https://github.com/tomav/docker-mailserver

**Comment by powerline332** [comment] 2018-07-10 17:15
I am using a dockerized version, from here: https://unkkuri.com/blog/unkkuri-blog-1/post/install-odoo-version-11-in-docker-container-21 , as of July 10,2018, and am experiencing the exact same error as W360S. When I clear the field, the Email Invitation works, but it sends a link to the user with "locahost" in it. My WLAN IP is known so how do I send that address instead?

PS. odoo.com/forum needs 3 karma points to ask a question.... chicken and the egg problem...

**Comment by CristianHR** [comment] 2019-07-03 18:04
> Se corrigió el error :) usted @voti solo tiene que ir a Configuración> Configuración general> Alias ​​Domain <borre cualquier texto en el dominio Alias ​​y luego aplique. funcionará> prueba ahora puedes cambiar al nuevo dominio de alias

Esto me funciona, gracias

**Comment by yusniermatos** [comment] 2025-03-21 14:25
En v18 Enterprise, en Odoo.sh, no me está funcionando el envío de correos con Yandex.
Probé esto último: dejé en blanco el alias domain en la configuración general.
Tengo configurados los alias bounce y catchall.
Además, tengo configurado el dominio de mi empresa en los parámetros mail.default.from_filter y mail.catchall.domain.
Tengo configurado DKIM, SPF en Yandex.

La prueba del servidor de correo saliente sí funciona.

Pero no funciona el envío de correo desde Odoo, ya sea con el sender igual al configurado en el servidor de correo saliente, o con otro sender. El error es el mismo:

Falló la entrega del correo
No se logró entregar el correo con el servidor SMTP 'None'.
SMTPDataError: (550, b'5.7.0 Sender address rejected: not owned by authorized user 1742565595-sxLnB7BLaKo0-GMLAWmBC')

¿Cuáles son los pasos y las configuraciones exactas que hay que completar para hacer que funcione?

Gracias de antemano.
