### ISSUE TITLE
When using product variants the  sales and purchases buttons are not reliable

### ISSUE THREAD

**Issue by AlanBell** [odoo/odoo#7413] opened 2015-07-02 08:52 UTC
the buttons on product.template form that link to action_view_sales and action_view_purchase actions are not coded right for using templates and variants, they need to have a bit of extra code to get the domain right, or you end up searching for completely the wrong thing.
sale/sale.py action_view_sale (the second one)
and
purchase/purchase.py action_view_purchase
need fixing with this code:

```
    products = self._get_products(cr, uid, ids, context=context)
    if len(ids) == 1 and len(products) == 1:
        result['context'] = "{'default_product_id': " + str(products[0]) + ", 'search_default_product_id': " + str(products[0]) + "}"
    else:
        result['domain'] = "[('product_id','in',[" + ','.join(map(str, products)) + "])]"
        result['context'] = "{}"
```

**Comment by AlanBell** [comment] 2015-07-02 08:53
the file mrp/product.py action_view_mos gets it right looking at manufacturing orders, just sales and puchase buttons need to do the same thing.

**Comment by mart-e** [comment] 2015-07-09 08:53
Hello,

What do you mean exactly by `or you end up searching for completely the wrong thing`? A way to reproduce the bug?

**Comment by AlanBell** [comment] 2015-07-09 09:12
it is a bit hard to reproduce without sharing customer data, however lets have a better attempt at describing it. If you have product variants, then the product form is a product.template object rather than a product.product object, the buttons on the product form in the top right block for purchases and sales are supposed to open list views pre-filtered on the product id of the thing you have opened, so that you can jump to sales and purchases for that thing. The default setup searches for sales and purchases of the ID of the product.template, which might be the ID of an entirely different product.product.

**Comment by AlanBell** [comment] 2015-07-09 10:15
the patch above implements the same code that was put into the other buttons in this commit by @jco-odoo 
https://github.com/odoo/odoo/commit/4aa9ef82243b50e45d9fd8543776709aca73d1fe

**Comment by mart-e** [comment] 2015-07-09 11:39
I am wondering if you are not using an old version of the source code. 0b18a5afec291a7248593704b0456d667349fca4 and 68b8286d5fe384af2ce05b58807e532ffa27a796 you shouldn't have issues between product and templates.

**Comment by mart-e** [comment] 2015-07-09 11:50
To sum up, when you click on ["sale" button of product.product](https://github.com/odoo/odoo/blob/2835381c7edd472869cd86fe43e35a588b43e6e2/addons/sale/sale_view.xml#L508), you call [action_view_sale of product.product](https://github.com/odoo/odoo/blob/2835381c7edd472869cd86fe43e35a588b43e6e2/addons/sale/sale.py#L1291), the ids are ids of product.product. If you click on ["sale" button of product.template](https://github.com/odoo/odoo/blob/2835381c7edd472869cd86fe43e35a588b43e6e2/addons/sale/sale_view.xml#L523), you call [action_view_sale of product.template](https://github.com/odoo/odoo/blob/2835381c7edd472869cd86fe43e35a588b43e6e2/addons/sale/sale.py#L1310), the ids are ids of product.template.
These are different and there should have no mix, so maybe I missed something or you have an older version of views where there was a bug.

**Comment by AlanBell** [comment] 2015-07-09 14:25
I am certainly on the latest code, and reverting my fix reveals the incorrect behaviour, I am going to check carefully that the xml files have been applied correctly and the right methods are being called.

**Comment by lbaldi** [comment] 2016-01-11 19:37
Same problem here. Just sale and purchase button from product.template view.

**Comment by pedrobaeza** [comment] 2018-04-04 22:38
I'm closing this as no more feedback and seems to be something wrong on the user side.

**Closed by pedrobaeza** 2018-04-04 22:38 UTC
Labels: Blocked
