### ISSUE TITLE
[V8] only 80 of 160 taxes are shown: reality 2651

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#2235] opened 2014-09-07 17:38 UTC
On V8, when you want to (1.) select taxes in an (2a.) invoice or a (2b.) receipt only the (RES) first 80 taxes are shown.
On an invoice you can set and unset a filter, then all taxes are shown. The point is on a recipt you don't have this possibility.
(EXP) Be able to set any tax that is configured as available on receipts
(EXP) Be able to set tax without the need to set and unset a filter on an invoice

**Comment by cysnake4713** [comment] 2015-01-03 07:32
I have the same problem!

**Comment by cysnake4713** [comment] 2015-01-03 07:40
https://github.com/odoo/odoo/blob/8.0/addons/web/static/src/js/view_form.js#L3364
I think 160 limit cause this problem, but if you delete the limit, it will cause lots of time to open the search view.

**Comment by Sathors** [comment] 2015-07-28 21:14
Hey guys, I also have the same problem.
Actually you don't really need to set/unset a filter, if you click the X in the search field, then all the records will appear.

IMHO, clicking on the X to make appear all the records is all but intuitive.
Wouldn't it be better to query in the database only the current page instead of going to read everything in one go? Even though sorting would indeed require read the whole table.

Odoo guys, we are waiting for you there, because this issue is rather important for a system which want to be seen as professional.

Thanks.

**Comment by spadae22** [comment] 2015-07-28 21:56
This is because of the use of the selection widget used on the form view on Fiscal Position. I have an enterprise contract and a partner and was told by support it is by design. I modified the code since we also have 130.

here is the response, this needs to fixed asap. Account/partner_view.xml 
                            <field name="property_account_position" widget="selection”/>  <—— remove and you will be fine. 

I responded with this:
The issue is the widget has a limitation  on the view, In the US sales tax is a major issue and if odoo wants to compete with other ERPs, saying sales tax cannot be selected with a custom module is ridiculous, Any business owner who is informed about this limitation, say goodbye to odoo. You can’t set sale tax in you own county? How do you sell that. This should be fixed ASAP. This is why odoo cannot be sold, simple common issue as sales tax, which the government with shit all over you. Ask any business owner. Please report as a big and fix and push to the core.

Response from paid support:

Hi,

I understand your concern, but this is by design and I will explain you the reason.

We have used widget selection on some fields because we do not wish that record is opened by the user and not modified. And those field normally should not have much records, like Payment terms, Company, Journals etc.

Widget selection has a limit set to save performance penalty. Because for many2one records, it loads only 7 records when you click it, but for selection widget, it loads all the records, so imaging if the field has a lot of records and it does not have any limit set, then there will be performance problem due to loading all those records.

So it's not a solution to increase the limit for widget, but it is that field for which that widget should be removed, because based on your business requirement you should have many2one field.

So you should patch your server or create a custom module.

I hope this explanation helps.

- -
Regards,
Rifakat Husen Haradwala,

Odoo Professional Services.                     





E.R. Spada II  owner  |   er@e <mailto:er@digital-page.com>ugeconsulting.com  |  Direct.  518 365 7854 |  Fax.  518 459 7025
EUGE Consulting  | 107 Everett Road  |  Albany, New York 12205  |  http://www.e <http://www.digital-page.com/>ugeconsulting.com

CONFIDENTIALITY NOTICE: This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information.  Any unauthorized review, use, disclosure or distribution is prohibited.  If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message.

**Comment by Sathors** [comment] 2015-07-28 22:08
Thanks for your help @spadae22, but actually the problem happens also in all the tree views following a "Search More".
So here we are talking not only of Fiscal Positions, or some precise model, but all the models, because all are impacted.

**Comment by blaggacao** [comment] 2015-07-29 14:12
I can confirm, it is not an selection issue and underpin what @Sathors said: It's an issue on the "search more" search view.

**Comment by spadae22** [comment] 2015-07-29 15:13
The 80 limit on other view is global and can be changed in the css. Bu the selection widget you cannot, and any values over the 80 become unknown. So yes I understand your point, should not be a limit

**Comment by richard-willowit** [comment] 2015-08-20 05:09
@blaggacao - I concur.  Why on earth is this not fixed?  I noticed it is a problem since v7 at least...

**Comment by spadae22** [comment] 2015-08-20 05:57
No idea. v8 it is easy to hide create and edit on the drop down, but they will not change the widget =80. Support told me it normal behavior. They just do not deal in reality.

**Comment by Sathors** [comment] 2015-08-20 15:26
I will see if I have the time to propose a fix for it, being quite easy, because they process PRs much faster than issues.

If anyone wants to do it before I can free the time, better ^^.

**Comment by Yenthe666** [comment] 2017-06-27 11:37
Hi @blaggacao,

Thanks for your report.
As some people have already hinted this is build in by Odoo and there is no plan to change this in the stable versions of Odoo.
Martin gave an official statement:

> Indeed, we won't change it in stable (a bit inconvenient but nothing blocking).
However, we want to change that in master but it is not that easy (we have a problem to keep the current search).
In discussion with the framework team to find a solution but no promise on what and when.

You can find the quote here: https://github.com/odoo/odoo/issues/17490
I'll close this issue since it is confirmed that this will not be changed in the stable versions.

Regards,
Yenthe

**Closed by Yenthe666** 2017-06-27 11:37 UTC
