### ISSUE TITLE
[13] Odoo incompatible with Python 3.8

### ISSUE THREAD

**Issue by grzekru** [odoo/odoo#40303] opened 2019-11-14 21:27 UTC
**Impacted versions:**

Odoo 13
Python 3.8
Tested on Arch Linux and Debian, default python version on arch linux, and compiled from source on Debian

**Steps to reproduce:**

Run odoo using python 3.8

**Current behavior:**

```
Traceback (most recent call last):
  File "/home/gk/odoo/odoo/addons/base/models/qweb.py", line 314, in compile
    unsafe_eval(compile(astmod, '<template>', 'exec'), ns)
TypeError: required field "posonlyargs" missing from arguments

Error when compiling AST
TypeError: required field "posonlyargs" missing from arguments
Template: web.webclient_bootstrap
Path: /t/t/t[3]
Node: <t t-set="body_classname" t-value="'o_web_client'"/> - - -
```

**Expected behavior:**

Odoo works with newest stable python release

**Comment by pedrobaeza** [comment] 2019-11-14 21:31
Duplicate of #40232

No P3.8 compatibility yet, so closing.

**Closed by pedrobaeza** 2019-11-14 21:31 UTC

**Comment by tanvirahmedkhan74** [comment] 2020-09-21 17:03
It took me sometimes but i was able to run it with python 3.8

I changed the requirment.txt file a bit, And watch my github link -

https://github.com/tanvirahmedkhan74/Installing-Odoo13-on-Ubuntu20.04-with-Python-3.8.git

Replace the requirments.txt file with the given one on the github
