### ISSUE TITLE
Can not Save new/edit quotation ver 13

### ISSUE THREAD

**Issue by sxrgit** [odoo/odoo#52235] opened 2020-06-02 08:43 UTC
Impacted versions: 13

Steps to reproduce: 

Go to an EXISTING Quotation, 

1) click Create for New quotation -  cant see Save Discard option, can not save new quotation
2) Click Edit to edit quotation -  no option to Save edited quotation

Current behavior: No option to Save new quotation

Expected behavior: Should be able to Save quotations

Video/Screenshot link (optional):
![Error Quotation](https://user-images.githubusercontent.com/32684065/83500410-5b50be00-a4dc-11ea-917a-8a81ab7cea06.png)

**Comment by pedrobaeza** [comment] 2020-06-02 09:04
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by sxrgit** [comment] 2020-06-02 09:14
Hi, issue exists in runbot too. The screenshot attached is of runbot only.  I have explained the steps to reproduce in the issue itself. Kindly check.

**Comment by pedrobaeza** [comment] 2020-06-02 09:18
I'm doing the exact same steps without that problem:
![Selección_003](https://user-images.githubusercontent.com/7165771/83502975-af4ea900-a4c2-11ea-9703-536f9fac8997.png)
so the problem is probably in your side. Maybe an incompatible browser or addon locking some things? Try on a vanilla Chrome/Firefox without complements.

Closing this meanwhile no further evidence.

**Closed by pedrobaeza** 2020-06-02 09:18 UTC
Labels: Need information

**Comment by sxrgit** [comment] 2020-06-02 09:22
You are right working in other browser fine. I was using edge and it was showing problems.
