### ISSUE TITLE
The above exception was the direct cause of the following exception

### ISSUE THREAD

**Issue by zinzinday** [odoo/odoo#69425] opened 2021-04-16 19:00 UTC
Impacted versions: 14 - Community

Steps to reproduce:
- I have installed from source (git) on Ubuntu 20.04 64bit
- Logged in 
- enabled debug mode
- installed module first only Invoicing
- go menu (Invoicing > Configuration > Payment icons) http://localhost:8069/web#menu_id=167&action=259
Current behavior:
Getting an problem
Expected behavior:
```py
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/data/www/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/data/www/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/data/www/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/www/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/www/odoo/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/www/odoo/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/data/www/odoo/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/data/www/odoo/addons/web/controllers/main.py", line 1737, in load
    action = request.env[action_type].sudo().browse([action_id]).read()
  File "/data/www/odoo/odoo/addons/base/models/ir_actions.py", line 240, in read
    result = super(IrActionsActWindow, self).read(fields, load=load)
  File "/data/www/odoo/odoo/models.py", line 3020, in read
    return self._read_format(fnames=fields, load=load)
  File "/data/www/odoo/odoo/models.py", line 3040, in _read_format
    vals[name] = convert(record[name], record, use_name_get)
  File "/data/www/odoo/odoo/models.py", line 5666, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/data/www/odoo/odoo/fields.py", line 1019, in __get__
    self.compute_value(recs)
  File "/data/www/odoo/odoo/fields.py", line 1175, in compute_value
    records._compute_field_value(self)
  File "/data/www/odoo/odoo/models.py", line 4061, in _compute_field_value
    getattr(self, field.compute)()
  File "/data/www/odoo/odoo/addons/base/models/ir_actions.py", line 207, in _compute_search_view
    fvg = self.env[act.res_model].fields_view_get(act.search_view_id.id, 'search')
  File "/data/www/odoo/odoo/api.py", line 473, in __getitem__
    return self.registry[model_name]._browse(self, (), ())
  File "/data/www/odoo/odoo/modules/registry.py", line 177, in __getitem__
    return self.models[model_name]
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/www/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/www/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
KeyError: 'payment.icon'
```
Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment] 2021-04-16 19:30
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin - use base db)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Closed** 2023-06-14 16:11 UTC
Labels: Need information
