### ISSUE TITLE
[12.0] Automatic creation of RFQ from sale order uses wrong user

### ISSUE THREAD

**Issue by reinaldoramosarxi** [odoo/odoo#32387] opened 2019-04-03 13:20 UTC
Impacted versions: 12.0, that we tested

Steps to reproduce: 
- Create sale order using at least one make to order product (with no stock available, or not enough at least)
- Confirm the sale order

Current behavior: The request for quotation that results from the SO confirmation is created, but uses the Admin/OdooBot user_id as create_uid.

Expected behavior: The document should have the current user's id as create_uid, despite being an automated creation (generated from a manual input).

**Comment by pedrobaeza** [comment] 2019-04-03 14:02
Hi @reinaldoramosarxi that's not possible, as that user may not have permissions in the purchase area, so it has to be done this way through admin.

Closing as no issue, but expected behavior.

**Closed by pedrobaeza** 2019-04-03 14:02 UTC

**Comment by reinaldoramosarxi** [comment] 2019-06-25 16:44
Hello,

I know this issue was closed for expected behavior, but there is still a problem with this.

Whenever a RFQ is automatically created through OdooBot, the currency that is used on the RFQ is... Odoobot's company's. 

Regardless of OdooBot being used for access rule reasons, some user-related things (like company, or company currency) probably shouldn't use OdooBot's user.

Line where the currency_id is passed (self.env.user is already OdooBot at this point):
https://github.com/odoo/odoo/blob/12.0/addons/purchase_stock/models/stock_rule.py#L175

Thank you.

**Comment by llacroix** [comment] 2021-12-09 06:13
@reinaldoramosarxi the reason is that self.env.user is a property that calls

```
return self(user=SUPERUSER_ID).browse(self.uid)
```

So it returns the user itself but with the uid in the env set to SUPERUSER_ID. I just found a problem similar to yours in website_sale. The payment_term will be set to the payment_term based on the company of OdooBot instead of the current user.
