### ISSUE TITLE
Currency Switcher - Main Currency disappears after switching from CHF->EUR-USD

### ISSUE THREAD

**Issue by buzzy3** [odoo/odoo#22579] opened 2018-01-28 20:42 UTC
Impacted versions: Enterprise 11, Bootstrap Default Theme and any other

Steps to reproduce:
Enable Pricelists, Public CHF,  and Automatic Currency Rates
Fill a product  in Main Currency. Publish to eCommerce

Current behaviour:
On Desktop rendering, the Currency can be switched, and the rate is correctly exchanged in the choosed currency. Switching back to another Currency works as well, but the main currency disappears from Dropdown. Only Work around is restarting odoo

On Mobile Screen rendering, choosing another currency for a product items gives a prompt, that he didn't found any other pricelist for this currency. 

Expected behavior:
If you work with pricelists, and Automatic Currency Rates, it should compute any existing value to the desired-choosen Currency in Frontend, even or especially if there is no other pricelist in the choosen currency. 

VID: https://www.youtube.com/watch?v=bLGQ4PFnYeQ
Video/Screenshot link (optional):

![abbildung_2018-01-28_09-09-26_pm](https://user-images.githubusercontent.com/265888/35486625-0834c508-0471-11e8-8c8e-6fc2c8eb5991.png)

**Comment by sswapnesh** [comment] 2018-01-29 13:27
Hello @buzzy3 
I have Performed Same on [Runbot](http://297720-11-0-8ed757.runbot12.odoo.com/shop) and Can not Reproduce the Same Issue. 

![](https://image.prntscr.com/image/4ApZoRRERTquJc8L5opSPA.png)



![](https://image.prntscr.com/image/QS4ZcPI1T16SOveiBSaKJA.png)

**Comment by Yenthe666** [comment] 2018-01-29 15:27
@buzzy3 can you reproduce this on an official Odoo test instance at runbot.odoo.com?

**Comment by JKE-be** [comment] 2018-01-31 08:46
@buzzy3 
Are you sure that this price list is selectable and match your country group (or none).

In some case you can see a price list A that is not in the 'public' list, but because it has been selected manually on your sale order, or in your last order or even with a promo code...
Or some pricelist can disappear once you enter your country in the checkout because there are no more available for your country (should be detected early if you have geoip enable)

As @sswapnesh, I cannot reproduce your issue without more information

**Comment by JKE-be** [comment] 2018-02-07 08:18
I close this issue, because no feedback

**Closed by JKE-be** 2018-02-07 08:18 UTC
Labels: 11.0, Need information, Website

**Comment by buzzy3** [comment] 2018-04-08 14:44
Sorry for lack of my response. I can not reproduce it always and I think it was related to an JS Error sometimes poped up with the template. Close it
