### ISSUE TITLE
Export Issue with many workers

### ISSUE THREAD

**Issue by cormaza** [odoo/odoo#24145] opened 2018-04-09 22:42 UTC
Impacted versions:
11.0
Steps to reproduce:
Export whatever data, with relational data, without external identificator
Current behavior:
Show error message:

Error:
Odoo Server Error
```
Traceback (most recent call last):
  File "/opt/odoo/server/addons/web/controllers/main.py", line 77, in wrap
    return f(*args, **kwargs)
  File "/opt/odoo/server/addons/web/controllers/main.py", line 1444, in index
    return self.base(data, token)
  File "/opt/odoo/server/addons/web/controllers/main.py", line 1392, in base
    import_data = records.export_data(field_names, self.raw_data).get('datas',[])
  File "/opt/odoo/server/odoo/models.py", line 781, in export_data
    return {'datas': self._export_rows(fields_to_export)}
  File "/opt/odoo/server/odoo/models.py", line 705, in _export_rows
    xids = dict(self.__ensure_xml_id(skip=['id'] not in fields))
  File "/opt/odoo/server/odoo/models.py", line 672, in __ensure_xml_id
    columns=['module', 'model', 'name', 'res_id'],
psycopg2.ProgrammingError: copy_from cannot be used with an asynchronous callback.
```
Expected behavior:
Export correctly
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2018-04-09 22:50
Are you able to reproduce this in runbot (http://runbot.odoo.com/runbot)?

**Comment by cormaza** [comment] 2018-04-26 13:35
In some commit this was resolved, I cannot reproduce now

**Comment by CARLOSREYESNIC** [comment] 2018-06-08 18:29
cormaza, how did you do?

**Comment by cargohec** [comment] 2018-07-15 21:34
I have solved this issue in my deployment.

The error is has to do with the xml_id as @RalfWeiss mentions above. Looks like it only affects Bitnami deployments and my guess is that is has to do with the way the postgres database is installed in Bitnami. For some reason when a psycopg2 copy instructions is executed the system attempts to do it a asynchronously.

This error happens when a record that is being exported has no xml_id. Odoo creates one and attempts to add it to the ir_model_data table. The copy_from instruction si trying to insert a new id into the table. As it fails returning the error mentioned here the export fails.

Fix:
Change the following in the file /opt/bitnami/apps/odoo/lib/odoo-11.0.post20180618-py3.6.egg/odoo/models.py

Line 37:

    from contextlib import closing
to

    from contextlib import closing, contextmanager
Lines 671 - 683

    cr.copy_from(io.StringIO(
        u'\n'.join(
            u"%s\t%s\t%s\t%d" % (
                modname,
                record._name,
                xids[record.id][1],
                record.id,
            )
            for record in missing
        )),
        table='ir_model_data',
        columns=fields,
    )
to

    @contextmanager
    def _paused_thread():
        try:
            thread = psycopg2.extensions.get_wait_callback()
            psycopg2.extensions.set_wait_callback(None)
            yield
        finally:
            psycopg2.extensions.set_wait_callback(thread)
    with _paused_thread():
        cr.copy_expert("COPY ir_model_data (module, model, name, res_id) FROM STDIN",
            io.StringIO(u''.join(
                  u"%s\t%s\t%s\t%d" % (
                       modname,
                       record._name,
                       xids[record.id][1],
                       record.id,
                  )
                  for record in missing
               )
           ))
This will do a async bulk insert into the database of the missing xml_id's and the export will finish.

Hope this helps!

**Comment by cormaza** [comment] 2018-07-16 21:52
Try the solution that you propose, however, let the original copy run, and it worked perfect

`@contextmanager
        def _paused_thread():
            try:
                thread = psycopg2.extensions.get_wait_callback()
                psycopg2.extensions.set_wait_callback(None)
                yield
            finally:
                psycopg2.extensions.set_wait_callback(thread)
        with _paused_thread():
            cr.copy_from(io.StringIO(
                u'\n'.join(
                    u"%s\t%s\t%s\t%d" % (
                        modname,
                        record._name,
                        xids[record.id][1],
                        record.id,
                    )
                    for record in missing
                )),
                table='ir_model_data',
                columns=fields,
            )`

**Closed** 2020-01-17 13:25 UTC
Labels: 11.0, Framework
