### ISSUE TITLE
Email alias case sensitive

### ISSUE THREAD

**Issue by mrbreil** [odoo/odoo#334] opened 2014-06-04 06:15 UTC
We encountered a situation, where emails at support@domain.tld, which has an email alias created in OpenERP, were successfully transformed to a project issue. But emails at Support@domain.tld weren't recognized by OpenERP.

Can somebody confirm this? Is there a way to disable this behavior?

**Comment by bozicm** [comment] 2015-03-20 14:40
I can confirm this with Odoo v8, the exact same problem. I guess the root of the problem is in how mail.alias core module works (or even lower at the ORM level):

- Exchange server that somehow enforces uppercase names in e-mails (I guess this is by default and it's RFC valid (http://en.wikipedia.org/wiki/Email_address#Syntax).
- the fetchmail part of Odoo mail module does its' job fine
- the email alias settings (in *Settings > Technical > E-mail > Aliases*) just forces all the letters to lowercase, and that's why it can't import the emails with. I guess that this setting is case sensitive.

The problem lies in the https://github.com/odoo/odoo/blob/8.0/addons/mail/mail_alias.py, I suppose.

Too bad that this trivial bug is still open and unattended.

**Comment by burton1982** [comment] 2015-07-31 11:45
I am have the same problem? Anyone has an idea how to solve this bad bug?

**Comment by JKE-be** [comment] 2016-09-30 17:24
Thanks to @mvaled 
Fix has been merged https://github.com/odoo/odoo/commit/5b692df1b10ff7ced0185b392519b619b91021c1.

**Closed by JKE-be** 2016-09-30 17:24 UTC
