### ISSUE TITLE
Stock.move.line is deleted or not exists 

### ISSUE THREAD

**Issue by Mosalah1690** [odoo/odoo#73598] opened 2021-07-13 01:06 UTC
![Untitled](https://user-images.githubusercontent.com/87345373/125374478-60db3180-e387-11eb-8218-22fd1863c0d2.jpg)
Impacted versions: 13

Steps to reproduce:

Current behavior: see the attached error while trying to validate products receiving in the inventory module 

Expected behavior: 

Video/Screenshot link (optional): 
Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment] 2021-07-13 06:32
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Closed** 2023-04-07 12:58 UTC
Labels: Need information
