### ISSUE TITLE
Web x2many form modal, x2many error

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#19242] opened 2017-09-04 10:31 UTC
Impacted versions: master - from #19239 
NOTE: I am not sure if this is even an allowed operation but I'm experiencing the same in situations where it is.  Is hard because I'm trying to hunt down easily reproducible examples.
Steps to reproduce:
Logon as admin
Open a Sale Order
Edit it and Open a line
Add some invoice lines
Click Save
Click Save
Open the just edited line

Current behavior:
No invoice lines

Expected behavior:
Invoice lines
Video/Screenshot link (optional):

**Comment by gdgellatly** [comment] 2017-09-19 21:30
@ged-odoo This is a really important issue for me, and I think it is symptomatic of a lot of other web client issues.  What can I do, what more information do you need?

When I track through a debug session it basically goes like this.

Scenario: Nested editable one2many in a form modal (called via a tree_view_ref if it matters)
To make it less abstract lets call it sub.sale.order.line - and its fields are name, product_id.

What Happens:
In the modal everything pretty much behaves and data is entered, onchanges run - notwithstanding some other open reports
On Save and Close of the modal, then Save of the Sale Record.
Nothing is saved.  The field isn't even in the write dict.

To test further, I made the field invisible on the tree view of the sale.order.line, and triggered an onchange so I could see the field contents on return from the modal.  It is always [].

It is most definitely a regression, this set of modules I've had running since v5, and was also running on master only a few weeks ago.

**Comment by intero-chz** [comment] 2017-09-20 07:08
@gdgellatly "if it matters" -> yes i think it matters, IIRC. Can you try to "embed" the list view. I mean something like form of parent model -> one2many field -> form/list view of submodel. Like in sale.order form view.

**Comment by ged-odoo** [comment] 2017-09-20 07:36
@gdgellatly This is exactly the kind of issues that I really care about.  Every edge cases should work perfectly, now that we have a new design running.  However, I could not reproduce your issue this morning.  I tried on a master/saas-18/saas-16, and every time, the invoice line was properly saved.  So, maybe the issue was fixed by some other commit.  Could you retest with a recent build?

If the issue is still present, could you give me a detailed list of steps to reproduce the problem on the runbot?

Ping me as much as you need, this should be solved...

**Comment by gdgellatly** [comment] 2017-09-20 09:20
@ged-odoo @intero-chz Hi, I have been downloading and updating master daily, however, the last week or so I've been working on reports as this has been a blocker (although reports no picnic either).  For the first time in forever I left my laptop at work, so tomorrow I'll thorough tests through and if it still fails share code, record vids etc.

I just ran my test case above through runbot and can confirm it does not fail for an existing record.
However it does still fail (with a validation then a js error) for a new record but lets wait until I test better as invoice lines being added at sale order is not a real case..

**Comment by ged-odoo** [comment] 2017-09-20 10:32
@gdgellatly 
It is good to know that the issue seems solved on the runbot in the main case.  You mention that it still fail for new records, and that is really interesting.  The actual problem came from a change in the semantics of the 'readonly' modifiers (see the following fix: https://github.com/odoo-dev/odoo/commit/a5ca63c83beafd9a060ac58d3b4c6a9a987b28df).  In a nutshell, now, the 'readonly' modifier means that the web client never sends the value to the server.  In some cases, we actually want to do that, and we need to add explicitely the 'force_save' attribute.

With the commit linked above, the issue should be solved (at least, for the SO).  If you run into the same issue for your own addons, the fix is essentially the same: adding the force_save attribute.

I'll close this issue, but feel free to comment if there is still a problem, and I am always very interested in all tricky edge cases for relational fields. I want the web client to be rock solid :)

**Closed by ged-odoo** 2017-09-20 10:32 UTC
Labels: Framework
