### ISSUE TITLE
Datetime field swaps day and month

### ISSUE THREAD

**Issue by Emad-Eddin** [odoo/odoo#7890] opened 2015-08-05 10:04 UTC
The datetime field swaps the date and month.

How to produce:
- create a simple module with "Datetime" field
- in the view, select a date from the pop up calendar.
- change the time portion using the keyboard.
- Save the record.
- Odoo will swap the date and month.

In the below screens the expected datetime is: 01/08/2015 11:00
but Odoo will change it to: 08/01/2015 11:00 and store it in the database like this

![image](https://cloud.githubusercontent.com/assets/8530582/9083263/e99b669e-3b71-11e5-9419-b2bad8a3526b.png)

![image](https://cloud.githubusercontent.com/assets/8530582/9083289/1314ea54-3b72-11e5-9e8e-23ca68a08437.png)

Incorrect result:
![image](https://cloud.githubusercontent.com/assets/8530582/9083313/2a8b7e46-3b72-11e5-876c-f8a52a9db902.png)

**Comment by Emad-Eddin** [comment] 2015-08-06 08:53
After further investigation, this only happens if the "Date Format" in Settings --> Languages is set to: "%d/%m/%Y"

**Comment by msh-odoo** [comment] 2015-08-06 09:03
Well as far as I know, the issue is occurring because it seems that you having datetime format as "%d/%m/%Y" and "%H:%M:%S" and you are manually entering date without seconds part, web-client will try to parse your value according to exact match with format(which is obviously going to fail as you do not have seconds part in your value), and then it will try to parse according to locale format of datejs cultureinfo.
Entering a proper value must not generate this issue.

**Comment by gdgellatly** [comment] 2015-08-06 12:30
No it only happens when you change the settings from default for the default language.  I've encountered before,  the solution was to change to correct language.  In my case en UK instead of en us.

**Comment by Yenthe666** [comment] 2016-05-25 13:39
Hi @Emad-Eddin,

As explained by @msh-odoo this is handled by the configuration of your date and time format under settings.
Closing this since it is wrongly configured.

Regards,
Yenthe

**Closed by Yenthe666** 2016-05-25 13:39 UTC

**Comment by sandeepksrana** [comment] 2018-03-15 13:41
```
value.format is not a function
When copy a date string in date field or any date field value into another date field
```

Expected behavior: it was working fine in odoo 8 9 10

Video/Screenshot link (optional): Error:
# Uncaught TypeError: value.format is not a function
