### ISSUE TITLE
[12.0] Wrong Var Declaration in try_loading_for_current_company in account.chart.template 

### ISSUE THREAD

**Issue by nickx0815** [odoo/odoo#35091] opened 2019-07-23 09:04 UTC
Impacted versions: 12

Steps to reproduce: Installing the Module "l10n_de_skr03" with an external API (In my Case OdooRPC)

Current behavior: The Installation doesn't work, missing required field "company_id"

Expected behavior: Should install the module 
-> when i change the variable declaration to 
current_user = self.env['res.users'].browse(request.session.uid)
it works 

Video/Screenshot link (optional):
![odoo_bug](https://user-images.githubusercontent.com/38421056/61698529-88b7d180-ad39-11e9-8715-dd904d252f00.png)

**Comment by pedrobaeza** [comment] 2019-07-23 09:06
Sorry, but the problem is the way you are doing this, presumably without login correctly, and that's why the variable `uid` is not available.

Closing as no valid issue.

**Closed by pedrobaeza** 2019-07-23 09:06 UTC

**Comment by nickx0815** [comment] 2019-07-23 14:21
Thanks for the quick answer.
I am logged in, because the install of the sale_management, stock and contacts module works fine, only the install of this specifc module doesn't.
I am just wondering, why the expression used in the if clause is not the same in the line I have marked. If this would be the case, the code would run, because the variable company is assigend in the else clause.
Regards
Nick

**Comment by pedrobaeza** [comment] 2019-07-23 14:24
Check your external script, as something is not correct at all if that variable is not set (or maybe how your server is initialized - maybe several DBs without DB filter). In any case, you haven't found this problem before by luck.

**Comment by intero-chz** [comment] 2019-09-20 14:00
@pedrobaeza besides that it could be an issue with the used library OdooRPC, if i'm not fully incorrect, the whole rpc API is multi db capable, because you have to login and you always have to declare a db name on API calls. So why should that be a problem?

And even if this all is valid, because Odoo SA. wants it that way, the code is just wrong.

https://github.com/odoo/odoo/blob/1b760a988fdf7bbc08b92e0705929d5620356a2f/addons/account/models/chart_template.py#L169-L171

Why would you check for `request.session.uid` and use another attribute afterwards (`request.uid`)?

**Comment by pedrobaeza** [comment] 2019-09-20 14:06
Both parts should have the same value. That's why for the rest that's not a problem. And I doubt it's an OdooRPC problem as well, but the deployment of your Odoo, not being able to select automatically the DB (missing dbfilter perhaps).

**Comment by intero-chz** [comment] 2019-09-20 14:22
First off it's not my Odoo deployment here. Second i know there are some multi db problems for example with URLs for the logo or something. But using the API with a db parameter on every call, there shouldn't be multi db problems...

> Both parts **should** have the same value

And **should** is my problem here. This code is bullshit. And i really don't know why you want to defend it. Either both parts use `request.uid` or `request.session.uid` and not mixed usage...
