### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by walid-mashal** [odoo/odoo#39554] opened 2019-10-30 08:41 UTC
Impacted versions: 12.0

Recently, I was working with the copy() method of one of my modules when I encounterd the error 

`TypeError: 'NoneType' object is not subscriptable` 

originating from this line: 

https://github.com/odoo/odoo/blob/f65bdd17308d6fa5f984dd23f0b345cd92c977cb/odoo/models.py#L4197

which in turn has the result of this line:

https://github.com/odoo/odoo/blob/f65bdd17308d6fa5f984dd23f0b345cd92c977cb/odoo/models.py#L4154

Now My suggestion is that can't we change this line:

https://github.com/odoo/odoo/blob/f65bdd17308d6fa5f984dd23f0b345cd92c977cb/odoo/models.py#L4197

to something that first checks that we have something as the result of rec.copy_data() and not a None object before trying to access the index

**Comment by pedrobaeza** [comment] 2019-10-30 11:06
Unless you have reproducible steps of the problem, this can't be attended. It doesn't serve that you only point to some lines based on your analysis. They can be helpful, but after that steps.

**Comment by Yenthe666** [comment] 2019-12-03 08:04
Hi there,

Since we haven't gotten any feedback in a while I'm closing off this issue.
Don't hesitate to respond back with more information. We'll reopen the issue if there is enough information to explain this issue.

Regards,
Yenthe

**Closed by Yenthe666** 2019-12-03 08:04 UTC
Labels: Need information
