### ISSUE TITLE
[11.0]sale_expense module expose all SO with state 'sale' to internal users

### ISSUE THREAD

**Issue by dansanti** [odoo/odoo#25872] opened 2018-07-19 12:01 UTC
Impacted versions:
11.0

Steps to reproduce:

1.- Install Sale Module
2.- install HR module
3.- create user1 with Personal Orders perms
4.- create user2 with Personal Orders perms
5.- create a sale order with each user
6.- confirm sales ( don't block it)

Current behavior:

each user can see all new orders  (user1 can see user2 orders)

Expected behavior:

if user confirm sale, only own user ( or super user) must see order

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2018-07-20 05:31
But do you put as salesman each of the users? The requirement for this is to have the own salesman for restricting the sales orders.

**Comment by dansanti** [comment] 2018-07-20 17:32
I'm sorry, the module is  sale_expense.

yes, in sales, each order haves the correct salesman.

[('state', '=', 'sale')],  from Expense Employee can read confirmed SO Rule, each sale have this rule from sale_expense

**Comment by pedrobaeza** [comment] 2018-07-21 15:02
I still don't understand where do you see the Sales Order. Please put detailed steps for reproducing the problem, indicating each of the steps you perform.

**Comment by dansanti** [comment] 2018-07-23 04:49
Following the steps I make a video, that happens when sale_expense module is installed:
https://dl.dropboxusercontent.com/s/oqyuo7nf322j8zv/out-18.ogv

in second video, if a internal user with no sale perms, can see orders:
https://dl.dropbox.com/s/wd4ztzzkfcclc9o/out-20.ogv

**Comment by jem-odoo** [comment] 2019-07-05 11:38
Duplicate of #23643

**Closed** 2019-07-06 06:13 UTC
Labels: 11.0, Need information, Services
