### ISSUE TITLE
Unable to access settings option

### ISSUE THREAD

**Issue by vr0929** [odoo/odoo#56081] opened 2020-08-18 16:01 UTC
Impacted versions: v13

Steps to reproduce:

Current behavior:

![odoo error](https://user-images.githubusercontent.com/69862437/90536715-ceb8b200-e152-11ea-9d46-a2344aadc113.png)
Error: Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1322, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 383, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 356, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1441, in load_views
    for [v_id, v_type] in views
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1441, in <dictcomp>
    for [v_id, v_type] in views
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/res_config.py", line 386, in fields_view_get
    toolbar=toolbar, submenu=submenu)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/models/models.py", line 206, in fields_view_get
    r = super().fields_view_get(view_id, view_type, toolbar, submenu)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1528, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(self._name, etree.fromstring(result['arch']), view_id)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 987, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 614, in raise_view_error
    raise ValueError(message)
ValueError: Field `account_check_printing_layout` does not exist

Error context:
View `n/a`
[view_id: n/a, xml_id: n/a, model: n/a, parent_id: n/a]

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2020-08-18 16:04
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by vr0929** [comment] 2020-08-18 16:18
I'm unable to reproduce the problem. But prior to getting this error i had installed a few apps a couple of days earlier. Odoo debrand and om_account_accountant are the apps that i installed.

**Comment by Yenthe666** [comment] 2020-08-18 16:28
Hmm test if the issue is gone again if you remove these apps. If that is the case there is an issue in one of the custom apps and you should reach out to the author of the module. If you can't reproduce it on a default Odoo 13 there is not much we can do to be honest.

**Comment by vr0929** [comment] 2020-08-18 16:38
I removed all of the apps prior to posting this issue so i'm unsure of what else might be causing it.

**Comment by kos94ok-3D** [comment] 2020-08-18 17:15
@vr0929, try to update an account_check_printing module

**Comment by vr0929** [comment] 2020-08-18 19:34
I didnt have it installed. I installed it and the issue was resolved.

**Closed** 2021-08-17 15:32 UTC
Labels: Need information, 13.0

**Comment by zloslawa** [comment] 2021-09-10 09:21
Same problem here, fixed lines, but it pops up same error. Can there some cashe problems?

**Comment by oranteso** [comment] 2021-12-18 19:11
This issue is related to OM HR PayRoll, and this module includes a field called " account_check_printing_layout" 

This is solved installing the module Check Printing Base (account_check_printing).

Hope this helps.

BR
Ulises Orantes

**Comment by zloslawa** [comment] 2021-12-20 10:21
This is not an issue, i've found the solution and posted it on gtihub, but
thank you for a reply :)

sob., 18 gru 2021 o 20:11 oranteso ***@***.***> napisał(a):
