### ISSUE TITLE
Odoo/Tools/Config.py broken - No Module Named None

### ISSUE THREAD

**Issue by Smart-IT-Kirkham** [odoo/odoo#14045] opened 2016-10-28 09:18 UTC
Impacted versions: Branch: Odoo 10 .0

Steps to reproduce: Download Odoo 10.0 and attempt to run.

Current behavior:
2016-10-28 10:09:30,125 39728 ERROR ? odoo.service.server: Failed to load server-wide module `None`.
Traceback (most recent call last):
  File "D:\openerpworkspace\Odoo-10\odoo\service\server.py", line 838, in load_server_wide_modules
    odoo.modules.module.load_openerp_module(m)
  File "D:\openerpworkspace\Odoo-10\odoo\modules\module.py", line 367, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "D:\openerpworkspace\Odoo-10\odoo\modules\module.py", line 60, in load_module
    f, path, (_suffix, _mode, type_) = imp.find_module(addon_name, ad_paths)
ImportError: No module named None

Expected behavior:
Expected modules to be present in server_wide_modules instead its [None]
Error is fixed by reverting odoo/tools/config.py back to the previous version.

This:  [MERGE] forward port branch saas-12 up to 6f8e40c broken it.

Working config attached.
[config.zip](https://github.com/odoo/odoo/files/558018/config.zip)

**Comment by odony** [comment] 2016-10-28 13:03
We apologize for the trouble, this problem is caused by a [bugfix](https://github.com/odoo/odoo/commit/5ee4344efd0074fac4006984c1eb1ccc4f335518) that enables the use of the `server_wide_modules` configuration option, which was previously ignored.

You can fix your issue immediately by removing the line `server_wide_modules = None` that is in your Odoo configuration file. The configuration file is either located in `$HOME/.openerp_serverrc`,  `$HOME/.odoorc`, next to your odoo/openerp executable, or the location is explicitly passed as `-c <config_file>` to the Odoo server.

Alternatively, please update your source code as soon as the bug is closed, we will update the system to handle this case gracefully.

**Comment by odony** [comment] 2016-10-28 13:41
The bug has been fixed by #14051, so if you update your source code you should not get the error anymore.

**Closed by odony** 2016-10-28 13:41 UTC
