### ISSUE TITLE
Bug in domain result when field is translated

### ISSUE THREAD

**Issue by HGHULFG1** [odoo/odoo#62501] opened 2020-11-27 10:29 UTC
Impacted versions: 14

Steps to reproduce: 

1. a char field with widget domain
2. update the field with a translated record in it, for example the name of the product,
3. change the language of the user

Current behavior: the result of the domain will change according to the language of the user

Expected behavior: same domain result

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2020-11-27 11:48
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Closed** 2023-04-07 14:11 UTC
Labels: Need information
