### ISSUE TITLE
[11.0] File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 341, in _compiled_fn

### ISSUE THREAD

**Issue by mhdsyarif** [odoo/odoo#19989] opened 2017-10-10 03:37 UTC
Impacted versions:
Error view Agenda in event
![selection_292](https://user-images.githubusercontent.com/5978109/31368278-f1b761f8-ada6-11e7-86a1-e39abe988341.png)

**Comment by Yenthe666** [comment] 2017-10-10 05:52
Hi @mhdsyarif,

Thank you for your report.
I can't reproduce this on the latest Odoo source code (from 20171010). Can you reproduce this on an official instance (at runbot.odoo.com)? Have you updated your source code to the latest version?

Regards,
Yenthe

**Comment by mhdsyarif** [comment] 2017-10-10 06:27
Hi @Yenthe666 

I have used the latest version odoo-11.0-20171009 from [http://nightly.odoo.com/11.0/nightly/src/](http://nightly.odoo.com/11.0/nightly/src/)

Thanks,
Syarif

**Comment by Yenthe666** [comment] 2017-10-10 06:30
Hi @mhdsyarif,

Thank you for the extra info. Can you try to reproduce this on a runbot (at runbot.odoo.com) please?
Did you install all dependencies too? (from https://github.com/odoo/odoo/blob/11.0/requirements.txt)

Regards,
Yenthe

**Comment by mhdsyarif** [comment] 2017-10-10 06:40
Hi @Yenthe666 

I tried to access the event on [http://269880-11-0-9d5c18.runbot8.odoo.com/event/open-days-in-los-angeles-2017-10-11-2017-10-15-1/agenda](http://269880-11-0-9d5c18.runbot8.odoo.com/event/open-days-in-los-angeles-2017-10-11-2017-10-15-1/agenda)
the same error in local.
![selection_293](https://user-images.githubusercontent.com/5978109/31372533-5bd5dfc4-adc0-11e7-907c-262d1e6a7b66.png)

Yes, i used Python3 in local.

Reqards,
Syarif

**Comment by Yenthe666** [comment] 2017-10-10 06:43
Thanks a lot for the extra information - I was able to reproduce this now. I was looking in the back-end, not the front-end, sorry 😉 
Confirmed:
![image](https://user-images.githubusercontent.com/6352350/31372622-019a37fe-ad97-11e7-9c5b-e63b2bb1a6fb.png)
@JKE-be this is for you.

**Comment by mhdsyarif** [comment] 2017-10-10 07:06
Hi @Yenthe666 

Error in front-end, according to my question at the beginning :wink:

Reqards,
Syarif

**Comment by JKE-be** [comment] 2017-10-10 07:08
@mhdsyarif  thanks, i'm on it ;)

**Comment by Yenthe666** [comment] 2017-10-10 07:10
Yup, I missed that, apoligies. It'll be fixed in no time. 😄

**Closed** 2017-10-10 09:09 UTC
Labels: 11.0, confirmed, Website
