### ISSUE TITLE
Bug in promotion programs

### ISSUE THREAD

**Issue by thomaspot** [odoo/odoo#42157] opened 2019-12-19 09:55 UTC
Impacted versions:
V12

Steps to reproduce:
1. Install e-commerce, sale_coupon, & install options for coupon on website
2. Create a Promotion Program
3. Create a new product to be used as a free gift
3. Set options to get a free product when > amount (see screenshot)
![screen1](https://user-images.githubusercontent.com/8189005/71163317-1ea24a80-224d-11ea-88cf-c8955fe67a35.png)
4. Go to shop. Create an order for more than $50,- (as set in screenshot)
5. Add the selected free product
6. Goto Cart and for the free received product click on + to add +1 quantity, and repeat this several times
7. Click the + on any other product in Cart

Current behavior:

The free product gets randomly added several times, with no really good result.

Expected behavior:
The free product can be added more, but the discount stays only 1 (once)

Video/Screenshot link (optional):
https://www.youtube.com/watch?v=TG2qMVrVXfs&feature=youtu.be

**Comment by dsmarketing** [comment] 2021-03-17 14:44
Also found this problem on odoo v13, any updates?

**Comment by rdeodoo** [comment] 2022-10-25 10:26
> The free product can be added more, but the discount stays only 1 (once)

That's not how it was designed, it should be 1 per 50$ spend I believe, so in your video it should be limited to 2.

But indeed, in your video it seems to produce inconsistent results and going over 2.
I had a quick look and couldn't reproduce the issue anymore, it is indeed limited to 2. It was probably fixed in the many fix back then.

Let me know if you still can reproduce something inconsistent in 14.0 and I'll reopen this one + ping the related team.

**Closed by rdeodoo** 2022-10-25 10:26 UTC
Labels: Website, 12.0, 13.0

**Comment by thomaspot** [comment] 2022-10-25 18:37
Ok. Can confirm that it is working as expected 
Testen in runbot V14 https://20495947-14-0-all.runbot67.odoo.com
