### ISSUE TITLE
Cannot delete 2nd company - object with reference: wizard.multi.charts.accounts

### ISSUE THREAD

**Issue by Randy01p** [odoo/odoo#26862] opened 2018-09-09 00:17 UTC
Impacted versions: 8

Steps to reproduce:
- Created second company
- Mark checkbox "Manage multiple companies"
- Config > Accounting > mark checkbox on second company "This company has its own chart of accounts "
- Create Chart of accounts
- Delete all charts of accounts, etc. uncheck all of above and try to delete company in the end.
- Shows me an error, like in the screenshot attached.

I tried removing the company but it throws that error, please could you help tell me what i need to remove so that i can completely remove the second company in the same database?

Please forgive me if im not doing something thats obvious, but i would really appreciate it if you could help me completely remove this second company.

![selection_016](https://user-images.githubusercontent.com/43101563/45259822-3f3aee00-b3d6-11e8-8b70-af5e1fe92fdf.jpg)

**Comment by sswapnesh** [comment] 2018-09-17 16:59
8.0 is no Longer Supported. You can use [forum]( https://www.odoo.com/forum/help-1) Instead.

**Comment by pedrobaeza** [comment] 2018-09-17 17:03
Indeed. Only last 3 versions are officially supported. If you still reproduces this problem in upper versions, please put another issue indicating the steps in new version (note that v9 is hardly supported as we are only 1 month to the new version).

Closing by the reason above.

**Closed by pedrobaeza** 2018-09-17 17:03 UTC
