### ISSUE TITLE
[10.0] [Accounting] Reconnciliation view filter not working correctly

### ISSUE THREAD

**Issue by SBC-MvS** [odoo/odoo#15949] opened 2017-03-20 14:37 UTC
Impacted versions: Odoo 10.0+e-20170317 (Enterprise Edition)

Steps to reproduce: Go to "Manual Payments & Invoices Matching" and Change the view from Default to any avaiable (customer, supplier or all)

Current behavior: Suddenly the form tells me there is nothing to reconcile even though before i switched the view i saw multiple entries. Even going to the view all then has this behavior until i leave the page and load it completely new.

Expected behavior: The avaiable reconnciliations are filtered that only the requested view is shown (customer or supplier).

**Comment by augustosamame** [comment] 2017-08-18 19:07
I can confirm this same bug affects current stable version of Community edition 10.0 as well

**Comment by pedrobaeza** [comment] 2018-05-22 08:08
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-05-22 08:08 UTC
Labels: 10.0, Accounting
