### ISSUE TITLE
 'Allow Reconciliation' are disappear when  select Accont Type: Bank and Cash.

### ISSUE THREAD

**Issue by kotchasaan** [odoo/odoo#28345] opened 2018-11-02 02:58 UTC
Impacted versions:
odoo-11.0.post2018110

Steps to reproduce:
    Create Chart of Account
    Select Accont Type: Bank and Cash

Current behavior:
    The problem is 'Allow Reconciliation' are disappear.

Expected behavior:
    The 'Allow Reconciliation' still appear.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2018-11-02 08:38
This is the expected behavior because such accounts shouldn't allow reconciliation by default.

Closing as no issue.

**Closed by pedrobaeza** 2018-11-02 08:38 UTC
