### ISSUE TITLE
[11.0] JS Webclient Issue: Integer fields in modal in another language than English (i.e. Payment Terms)

### ISSUE THREAD

**Issue by wtaferner** [odoo/odoo#20116] opened 2017-10-13 03:24 UTC
**Impacted versions:**
11.0

**Steps to reproduce:**

- Go to the ```account.payment.term``` form view in another language than the base (English)
- Go to Edit Mode and open the Terms (```line_ids```)
- Change the Integer Field in the modal dialog and "save" it. You can immediately see that the field will not be taken correctly into account (zero instead of any number)
- Finally save it and it will save the wrong number due to the step before which failed without JS error.

**Current behavior:**
Impossible to save an Integer field within a dialog correctly in a translated view

**Expected behavior:**
Integer fields in modal dialog are correctly propagated to the form view to which it is "binded".

@ged-odoo @nim-odoo @mart-e 
May I ask you guys to check this quick on runbot...it is easy to reproduce and a major issue IMHO.

Thank you.

OPW-776462

**Comment by gdgellatly** [comment] 2017-10-13 03:59
related? #17850 - I never thought about, but the language I was using was en_au that day.

**Comment by ged-odoo** [comment] 2017-10-13 05:18
@wtaferner I could not reproduce the issue on the runbot.  What language did you use? german?  Did you do it on runbot with base or all addons?

**Comment by ged-odoo** [comment] 2017-10-13 05:25
@wtaferner any chance that your issue comes from this? https://github.com/odoo/odoo/commit/b8dac2ff32d2e875e2f43c91f702e17adc938f7e

**Comment by wtaferner** [comment] 2017-10-13 05:42
@ged-odoo 
I was reproducing it on runbot enterprise and the language does not matter...I found out in German on my instances but reproduction was in French (BE) on runbot.
Not sure about the commit you linked...but by now it is present...don't know what you do differently on runbot that you can not reproduce.

@gdgellatly 
Nope, I doubt it is related...I think it is about the brand-new and beautiful webclient refactoring ;-

**Comment by gdgellatly** [comment] 2017-10-13 06:26
@wtaferner I just tested your case and sorry I am not sure how you can so easily say they aren't related, as the reproduction is identical.  An integer field without a default > 0 always remain zero.

**Comment by wtaferner** [comment] 2017-10-13 07:57
@gdgellatly 
Hmm, sorry to say that...from my point of view it is not related...I tested the exact same use case in my own 10.0 instance and there there was no issue. So I guess it is somehow related but not exactly the same ;-)

**Comment by ged-odoo** [comment] 2017-10-13 09:15
@wtaferner this is a huge problem, coming from this: https://github.com/odoo/odoo/blob/11.0/addons/web/static/src/js/fields/field_utils.js#L495

Really surprised we did not stumble upon this before.

In some language, the thousand separator is a '.', so we build a regexp that actually matches everything, and the number is then totally erased.

The good news is that it was actually fixed in the commit mentioned above (https://github.com/odoo/odoo/commit/b8dac2ff32d2e875e2f43c91f702e17adc938f7e#diff-19818030508d3b402415500e031143b9R434) by properly escaping the character.

So in theory, this issue should be solved as soon as the forward port is done.

**Closed by ged-odoo** 2017-10-13 09:15 UTC
Labels: 11.0, Framework

**Comment by wtaferner** [comment] 2017-10-13 09:43
@ged-odoo 
Thank you for the pointers and well, it is almost impossible to spot everything for a limited number of people and teams who focus on master or even saas-18. The ultimate test is to publish it and let all users and partner help to find these nasty bugs ;-)

Looking forward to the fix and switched to English in the meantime :rescue_worker_helmet:

**Comment by KangOl** [comment] 2017-10-13 13:52
Forward port to v11 is done.
