### ISSUE TITLE
[10.0/9.0] Budget is always 0

### ISSUE THREAD

**Issue by philhug** [odoo/odoo#15569] opened 2017-02-20 17:10 UTC
Impacted versions: 9.0 / 10.0

Steps to reproduce:
* Enable "Budget Management"
* Create a new Budget
* Add a budgetary position with an income account, planned amount but without analytical account
* Create bookings on this account
* approve budget / set budget to done

Current behavior:
* Practical Amount is 0

Expected behavior:
* Practical Amount is set to sum of budgetary positions.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2018-05-10 09:25
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-05-10 09:25 UTC
Labels: 10.0, 9.0, Accounting
