### ISSUE TITLE
[12] Error while installing ecommerce demo

### ISSUE THREAD

**Issue by grzekru** [odoo/odoo#34635] opened 2019-07-07 14:58 UTC
Impacted versions:

12.0

Steps to reproduce:

1. Create new database using Odoo CE, select demo data
2. Try to install eCommerce app

Current behavior:

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/gk/Software/odoo12/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/gk/Software/odoo12/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/gk/Software/odoo12/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/gk/Software/odoo12/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/home/gk/Software/odoo12/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/gk/Software/odoo12/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/gk/Software/odoo12/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/gk/Software/odoo12/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/home/gk/Software/odoo12/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/home/gk/Software/odoo12/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/gk/Software/odoo12/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/gk/Software/odoo12/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/home/gk/Software/odoo12/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/home/gk/Software/odoo12/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/gk/Software/odoo12/odoo/addons/base/models/ir_module.py", line 445, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/gk/Software/odoo12/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/gk/Software/odoo12/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/gk/Software/odoo12/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/home/gk/Software/odoo12/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/gk/Software/odoo12/odoo/modules/loading.py", line 195, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/home/gk/Software/odoo12/odoo/modules/registry.py", line 297, in init_models
    model.init()
  File "/home/gk/Software/odoo12/addons/sale/report/sale_report.py", line 135, in init
    self.env.cr.execute("""CREATE or REPLACE VIEW %s as (%s)""" % (self._table, self._query()))
  File "/home/gk/Software/odoo12/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/home/gk/Software/odoo12/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: column s.warehouse_id does not exist
LINE 34:         , s.website_id as website_id, s.warehouse_id as ware...
                                               ^
```

**Comment by sswapnesh** [comment] 2019-07-07 17:23
> - Create new database using Odoo CE, select demo data
> - Try to install eCommerce app

I could not reproduce the same on latest Odoo v12 CE.
It works well on my end.
(Am I missing any additional step ?)

**Comment by pedrobaeza** [comment] 2019-07-07 18:40
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/12.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

**Closed by pedrobaeza** 2019-07-07 18:40 UTC
Labels: 12.0, Website

**Comment by karamtabba** [comment] 2019-10-18 07:41
I reproduced this with an Odoo version that I assume isnt up-to-date.
there is a dependency missing in the eCommerce module. install inventory module first then install eCommerce. That did the trick.

Also, dont use any odoo installer script that is outdated. follow the installation procedure provided by odoo to ensure your base is up to date. use github, and pull updates regularly is my recommendation.
