### ISSUE TITLE
[8.0.0] Can't print invoice (SyntaxError: JSON.parse: unexpected end of data at line 2 column 1 of the JSON data)

### ISSUE THREAD

**Issue by artwoerx** [odoo/odoo#3405] opened 2014-10-30 21:54 UTC
Can't print the invoice.
Tried the setting "PDF" and "RML PDF".

![screenshot_cant_print](https://cloud.githubusercontent.com/assets/5598152/4852749/fd7e0a28-607e-11e4-85c2-cac7aedcca20.jpg)

Firefox 32.0.3 message:
SyntaxError: JSON.parse: unexpected end of data at line 2 column 1 of the JSON data

--------------------
http://xxx.xxx.xxx.xxx:8069/web/js/web.assets_backend/3791034:2963

LOGFILE:
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/report/models/report.py", line 190, in get_pdf
    save_in_attachment = self._check_attachment_use(cr, uid, ids, report)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/report/models/report.py", line 336, in _check_attachment_use
    pdf = base64.decodestring(pdf)
  File "/usr/lib/python2.7/base64.py", line 321, in decodestring

TypeError: must be string or buffer, not None

**Comment by flotho** [comment] 2015-01-25 14:43
Hy,
I have the same issue on CentOS with wkhtmltopdf 12.1.1. So it doesn't looks like to coming from only the release of wkftohtml.
Any advice?

**Comment by davshafik** [comment] 2015-02-12 11:50
i have similar issue can anyone help me 
SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 5 of the JSON data

**Comment by lefas** [comment] 2015-02-24 17:00
Maybe you can find the solusion here 
https://www.odoo.com/forum/help-1/question/unicodeencodeerror-58753
or 
https://github.com/OCA/OCB/issues/78

**Comment by denysvitali** [comment] 2015-03-11 23:30
Solved by installing by upgrading by pip reportlab:

`pip install --upgrade reportlab`

(I also needed `python-dev` package wich I was missing, otherwise I couldn't install / upgrade reportlab from pip)

**Comment by baim** [comment] 2015-03-13 12:36
hai denysvitali,
I've tried to upgrade reportlab, but there is a warning error
openerp.service.report: Exception: ('Report Error', 'Failed to invoke method execute in class com.nantic.jasperreports.JasperServer: net/sf/jasperreports/compilers/GroovyEvaluator')
Traceback (most recent call last):
  File "/opt/odoo/openerp/service/report.py", line 93, in go
    result, format = openerp.report.render_report(cr, uid, ids, object, datas, context)
  File "/opt/odoo/openerp/report/__init__.py", line 40, in render_report
    return registry['ir.actions.report.xml'].render_report(cr, uid, ids, name, data, context)
  File "/opt/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_actions.py", line 155, in render_report
    return new_report.create(cr, uid, res_ids, data, context)
  File "/opt/odoo/addons/jasper_reports/jasper_report.py", line 265, in create
    return r.execute()
  File "/opt/odoo/addons/jasper_reports/jasper_report.py", line 150, in execute
    pages = self.executeReport(dataFile, outputFile, subreportDataFiles)
  File "/opt/odoo/addons/jasper_reports/jasper_report.py", line 230, in executeReport
    return server.execute(connectionParameters, self.reportPath, outputFile, parameters)
  File "/opt/odoo/addons/jasper_reports/JasperReports/JasperServer.py", line 111, in execute
    raise osv.except_osv(_('Report Error'), e.faultString)
except_orm: ('Report Error', 'Failed to invoke method execute in class com.nantic.jasperreports.JasperServer: net/sf/jasperreports/compilers/GroovyEvaluator')
2015-03-13 12:30:27,072 3306 ERROR DEVELOPMENT openerp.addons.web.controllers.main: An exception occured during an http request
Traceback (most recent call last):
  File "/opt/odoo/addons/web/controllers/main.py", line 69, in wrap
    return f(*args, **kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 1577, in index
    request.session.db, request.session.uid, request.session.password, report_id)
  File "/opt/odoo/openerp/http.py", line 837, in proxy_method
    result = dispatch_rpc(self.service_name, method, args)
  File "/opt/odoo/openerp/http.py", line 113, in dispatch_rpc
    result = dispatch(method, params)
  File "/opt/odoo/openerp/service/report.py", line 34, in dispatch
    res = fn(db, uid, *params)
  File "/opt/odoo/openerp/service/report.py", line 141, in exp_report_get
    return _check_report(report_id)
  File "/opt/odoo/openerp/service/report.py", line 119, in _check_report
    raise openerp.osv.orm.except_orm(exc.message, exc.traceback)
except_orm: (u'Report Error', u'Failed to invoke method execute in class com.nantic.jasperreports.JasperServer: net/sf/jasperreports/compilers/GroovyEvaluator')

**Comment by atuljain** [comment] 2015-04-07 18:30
Hi, any solution for this type of error , even i am not getting any error message on terminal

**Comment by trevorfh** [comment] 2015-06-03 20:24
We are helping http://www.afistfulofdice.co.uk set up their website and point of sale using Odoo and have run into this same error on the Virtual Machine we have configured for them.
The point of sale works OK, but some of the accounting reports were giving this same JSON error. We checked we had implemented the comments above, which improved the situation, except on large reports it was still giving the same JSON error.
When we increased the timeout period on the webserver, in our case Haproxy in front of the Odoo server,  the JSON error went away. We used 15secs for the server timeout.
Hope this helps

**Comment by funkbilly** [comment] 2015-06-16 21:44
Hi! don't know if I can help, but I had this issue. I reinstalled wkhtmltopdf from 0.12.1 to 0.12.2 (my Odoo runs on a CentOs 7 server) but it did not help. 
Then, I went in Settings > Reports > Reports. Searched for the invoice report.
I edited the invoice report and unchecked the "Reload from attachment". I was able then to download invoice pdf file properly.
Of course, I found the solution right after by searching "Reload from attachment" : https://www.odoo.com/fr_FR/forum/help-1/question/customer-invoice-pdf-not-changing-after-modifications-to-header-9571
Cheers

**Comment by pvanthony** [comment] 2015-10-18 16:34
This helped me. Thank you sharing the solution.

**Comment by stijnpolfliet** [comment] 2015-12-15 19:43
Unchecking the "Reload from attachment" in Settings > Reports > Reports for Invoices fixed it for me

**Comment by sle-odoo** [comment] 2016-06-08 12:46
Closing the issue as i cannot reproduce. If you're still facing it feel free to comment with complete steps so that i can help you.

Regards

**Closed by sle-odoo** 2016-06-08 12:46 UTC

**Comment by yelizariev** [comment] 2016-06-08 13:24
Probably the issue related to low **limit_memory_hard** value
