### ISSUE TITLE
search_view_ref in the field context causes error on Many2one field

### ISSUE THREAD

**Issue by artemShelest** [odoo/odoo#71484] opened 2021-05-31 11:08 UTC
**Impacted versions:** 13.0 (checked on releases 20200826, 20210525)

**Steps to reproduce:**

Preparation:

Install attached module (at the bottom), it makes 3 steps, needed for the reproduction:

1. Installs HR module (this issue is not related to this module, just for the sake of easy reproduction).
2. Defines a custom search view for the res.partner model.
3. Extends hr.employee.form view where a custom search view is referenced in the field context.

Reproduction:

1. Go to Main Menu -> Employees
2. Click on the card "Administrator"
3. Click on Location -> Work Address -> Adminitrator

**Current behavior:**

An error:
```
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.actions.actions', <function IrActions.get_bindings at 0x7f1753131a60>, frozenset({1, 2, 3, 6, 7, 10, 11, 12}), 'res.partner')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 745, in get
    value = self._data[field][record._ids[0]]
KeyError: 49

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1002, in __get__
    value = env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 751, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('ir.actions.act_window(49,).search_view', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1322, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 383, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 356, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1441, in load_views
    for [v_id, v_type] in views
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1441, in <dictcomp>
    for [v_id, v_type] in views
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 410, in fields_view_get
    res = super(MailThread, self).fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/models/models.py", line 206, in fields_view_get
    r = super().fields_view_get(view_id, view_type, toolbar, submenu)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1535, in fields_view_get
    bindings = self.env['ir.actions.actions'].get_bindings(self._name)
  File "<decorator-gen-35>", line 2, in get_bindings
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_actions.py", line 123, in get_bindings
    result[binding_type].append(action.read()[0])
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_actions.py", line 204, in read
    result = super(IrActionsActWindow, self).read(fields, load=load)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2918, in read
    vals[name] = convert(record[name], record, use_name_get)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5640, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1026, in __get__
    self.compute_value(recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1111, in compute_value
    records._compute_field_value(self)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3939, in _compute_field_value
    getattr(self, field.compute)()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_actions.py", line 171, in _compute_search_view
    fvg = self.env[act.res_model].fields_view_get(act.search_view_id.id, 'search')
  File "/usr/lib/python3/dist-packages/odoo/addons/web/models/models.py", line 206, in fields_view_get
    r = super().fields_view_get(view_id, view_type, toolbar, submenu)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1528, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(self._name, etree.fromstring(result['arch']), view_id)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 987, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 614, in raise_view_error
    raise ValueError(message)
ValueError: Field `name` does not exist

Error context:
View `n/a`
[view_id: n/a, xml_id: n/a, model: n/a, parent_id: n/a]

```

**Expected behavior:**

Administrator (res.partner) form is shown.

[search_view_ref_bug.tar.gz](https://github.com/odoo/odoo/files/6569829/search_view_ref_bug.tar.gz)

**Comment by pedrobaeza** [comment] 2021-05-31 11:13
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2021-05-31 11:13 UTC
