### ISSUE TITLE
When purchasing from Odoo Apps, the "thank you" message is in French

### ISSUE THREAD

**Issue by bistaray** [odoo/odoo#13938] opened 2016-10-21 22:43 UTC
I visited apps.odoo.com and purchased an App, and after authorizing my credit card, I was show a thankyou message in French "Terminé, votre paiement en ligne a été enregistré. Merci de votre commande."

![](http://i.imgur.com/MO4m7L1.png)

**Comment by JKE-be** [comment] 2016-10-22 15:58
@dmo-odoo

**Comment by lukebranch** [comment] 2016-10-23 02:31
i've noticed similar language issues with using the odoo.com website. I'll go to help.odoo.com sometimes and the language will be in spanish, french or english seemingly randomly (even in a chrome incognito tab).

**Comment by dmo-odoo** [comment] 2016-10-24 07:52
@JKE-be This is odoo.com e-commerce, this part of the process does not happen on apps.odoo.com and I would be very surprised if the behavior was different for POSBoxes, indicating that it is not a problem with apps specifically.

**Comment by JKE-be** [comment] 2016-10-24 08:08
@lukebranch it should be not randomly but based on your localisation (based on localisation from your ip).

But I'm really surprising to see it... and will happy to reproduce it to debug.

**Comment by JKE-be** [comment] 2016-10-24 08:14
@bistaray what was your url when you take the screenshot ? 

www.odoo.com ? apps.odoo.com ? 
A lang forced in url? 

Thanks

**Comment by lukebranch** [comment] 2016-10-24 08:25
@JKE-be ,

I'll try to reproduce this issue next time I encounter it and submit steps to reproduce.

**Comment by bistaray** [comment] 2016-10-24 14:25
@JKE-be I am not sure what the URL was, but today I purchased a free app and was taken to https://www.odoo.com/shop/confirmation as you can see:

![](http://i.imgur.com/kApoD1m.png)

**Comment by dmo-odoo** [comment] 2016-10-24 14:34
Saas Portal Sale Online is free but has a paid dependency which is Product price factor. The price displayed for an app is the sum of the price of the app itself (in this case it's free) plus the price of its dependencies (in this case, only Product price factor is paid and costs 30 euros.) When you click on Add to Cart, the price is split between the module itself and all its paid dependencies as they are all added to your cart (the module and all its paid dependencies) so you can see for what you are actually paying. However, the system saw that you already bought Product price factor so it put it out of your cart. (Or you manually removed it in which case I don't understand what the issue is.)

**Comment by bistaray** [comment] 2016-10-24 15:31
@dmo-odoo you are correct, I manually removed the dependency.  The point of making the screenshot was just to provide information about the URL that I may have used when getting the message in French after I purchased (because the screenshot I shared when reporting this issue had to URL, and I no longer have that page open).

**Comment by dmo-odoo** [comment] 2016-10-24 16:34
Sorry, I misinterpreted "I purchased a free app" for "how is it possible that I could buy a free app" when you actually meant "I found a way to reproduce it without paying anything".

**Comment by bistaray** [comment] 2016-10-24 16:47
@dmo-odoo I was not clear - so my fault.  No problem.

**Comment by bistaray** [comment] 2016-10-26 17:56
Bought another App today, the URL of the page where I see the French message is:

https://www.odoo.com/shop/confirmation

![](http://i.imgur.com/kFtAqgO.png)

**Comment by bistaray** [comment] 2016-10-26 17:56
Today my IP address is 47.149.121.126 if that helps.

**Comment by JKE-be** [comment] 2016-10-26 20:06
Thank you for the reporting !!!

The bug was in the translation in our instance... strange :-1:

**Closed by JKE-be** 2016-10-26 20:06 UTC

**Comment by bistaray** [comment] 2016-10-26 20:39
Thanks!! Glad to help.  I wonder if fhe stopped by the office earlier in the month and played with the translation menu??  (please don't tell him I blamed him)  :)

**Comment by Yenthe666** [comment] 2016-10-27 06:12
@bistaray I feel tempted to ping him here 😉 & nice that it got fixed.
