### ISSUE TITLE
One2many field with related only save 1 field at time in treeview view inside a form.

### ISSUE THREAD

**Issue by aliencrash** [odoo/odoo#25879] opened 2018-07-19 22:44 UTC
Impacted versions:
11
Steps to reproduce:
Create 1 normal one2many field and  1 or 2 related field related with the first one. 
Current behavior:
Only one field is updated when the field is changed. It doesn't happen to all fields but it looks like happens to fields in onchange list. 
Expected behavior:
Update the values and save all the values when the main form saves.
Video/Screenshot link (optional):
See the [video](https://drive.google.com/file/d/1LQn5oqYpQTSElEDJ0R1erQnZAsIaJXS2/view?usp=sharing)

**Comment by aliencrash** [comment] 2018-07-19 22:45
This is the field definition 

contract_line_ids = fields.One2many('billing.contract.line', inverse_name='subscription_id',
                                            string='Subscription Products', domain=[("state", "in", ["new", "active"])]
                                            )
delivery_lines = fields.One2many(related='contract_line_ids', copy=False)
canceled_lines = fields.One2many(related='contract_line_ids', inverse_name='subscription_id', copy=False,  domain=[("state", "in", ["cancel", "done"])], store=True)

**Comment by pedrobaeza** [comment] 2018-07-20 05:21
Sorry, but the error you are mentioning corresponds to custom code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2018-07-20 05:21 UTC

**Comment by aliencrash** [comment] 2018-07-20 06:45
The problem is in the framework not in my code.

**Comment by pedrobaeza** [comment] 2018-07-20 06:51
Then please indicate the steps to reproduce in standard core addons, not in your code.
