### ISSUE TITLE
[SAAS-17] saving template of fields to export

### ISSUE THREAD

**Issue by JulioSerna** [odoo/odoo#18742] opened 2017-08-08 22:51 UTC
Impacted versions:
master, saas-17

Steps to reproduce:
try to save template of fields to export in any model

Current behavior:
It is not allowed

Expected behavior:
Allow save template

Video/Screenshot link (optional):
https://youtu.be/Ew7m8SB1DmE

**Comment by Yenthe666** [comment] 2017-08-09 06:19
Hi @JulioSerna,

Thank you for your bug report.
I've just tested this and I can confirm this is a bug in SaaS-17:
![image](https://user-images.githubusercontent.com/6352350/29107659-73b73f72-7cdb-11e7-9c55-fc878060e91e.png)

@mart-e can you let somebody look at it?

Regards,
Yenthe

**Comment by mart-e** [comment] 2017-08-09 08:12
Why do you use saas-17? It has just been freezed and is still in stabilisation process, nobody runs on it at the moment (we have saas-15 at most on our SaaS). Please report issues on stable versions.

[Against which version should I submit a patch?](https://github.com/odoo/odoo/wiki/Contributing#against-which-version-should-i-submit-a-patch)

**Comment by wtaferner** [comment] 2017-08-09 08:14
@mart-e 
Will saas-17 be future 11.0?

**Comment by mart-e** [comment] 2017-08-09 08:14
@wtaferner there will probably have saas-18 before that 😉

**Comment by wtaferner** [comment] 2017-08-09 08:15
ok, great, so saas-18 is the branch to look at if I want to give it a little headstart :-) thx

**Comment by nhomar** [comment] 2017-08-09 08:17
@mart-e remembe in vauxoo we are following your stabilization process due to l10n_mx_xx stuff, we are testing all early because once it is stable enough then it is too late to propose proper patches...

Then we have a chicken-egg problem here... What can we do with that?

**Comment by Yenthe666** [comment] 2017-08-09 08:18
@wtaferner or the master version? 😄 
@nhomar that sounds like a lot of hassle..

**Comment by nhomar** [comment] 2017-08-09 08:20
well... that's odoo's live if not we can not follow you! you know your "stable policy" better than me ;-)

We are using saas-15 on our prods but we started prepare all new stuff on saas-17 (and yes it is anoying but it is a dirty job that somebody must do) ;-)

**Comment by mart-e** [comment] 2017-08-09 08:21
@wtaferner The saas branches are published to give a preview of the future release (and because there is no reason to hide them) but I do not advise to use them on production as they have a very short lifetime and we do not really communicate on which is supported or not.

@nhomar I am not sure what was the agreement you made for the l10n_mx modules, this should probably be checked with the accounting team. Here it is a web bug due to the new web framework introduced in saas-16. We have already reported it internally.
We do not accept issues report on master but if you have a patch on saas versions, no issue here.

**Comment by nhomar** [comment] 2017-08-09 08:25
@mart-e do not worry about this, if you reported already, nice, confirm it and that's it! .

we are working on saas versions and I can not wait until our customers receive an explosion on the face on a saas environment because obvious reasons.

I do not have a patch now, if you are aware of this, nice, but PLEASE do not close it just because it is saas.... 

I am ok with the fact you know the issue, thanks.

**Comment by mart-e** [comment] 2017-08-09 12:01
Ok reopening until it is fixed, sorry about it :-)

**Comment by pedrobaeza** [comment] 2018-06-05 17:53
AFAIK, this is not happening anymore, so I close. Please correct me if I'm wrong.

**Closed by pedrobaeza** 2018-06-05 17:53 UTC
Labels: Confirmed
