### ISSUE TITLE
[account] wrong journal item when invoice return picking

### ISSUE THREAD

**Issue by JulioSerna** [odoo/odoo#20840] opened 2017-11-10 02:26 UTC
Impacted versions:
* 11.0

Steps to reproduce:
* Create purchase by 1 qty and receive
* Create invoice by 1 qty
* Create return
* Create refund invoice

Current behavior:
The journal entry
![bill 2017 0004 odoo](https://user-images.githubusercontent.com/7595505/32639627-61e8cd36-c58a-11e7-907f-4f868bc786f0.png)

Expected behavior:
The journal entry
![334 odoo](https://user-images.githubusercontent.com/7595505/32639861-609feea4-c58b-11e7-9d37-1936c7cc2001.png)

Video/Screenshot link (optional):
https://youtu.be/ZzOOxvyPWm8

**Comment by sle-odoo** [comment] 2017-11-17 09:37
Hi @JulioSerna, thanks for the report but i'm not able to reproduce the issue with l10n_us and your steps applied to a product configured as fifo + automated or standard + automated. The "fixed asset account" line is not present at my end. Could you please try again on the last runbot? It would be really helpful.

Regards

**Comment by JulioSerna** [comment] 2017-11-18 00:46
Hello @sle-odoo 

It can reproduce
https://youtu.be/Kfb9CbccCiI

**Comment by sle-odoo** [comment] 2017-11-20 16:23
fixed with https://github.com/odoo/odoo/commit/5e481936541f1796ea57f8b420e963ec93df0d64
thank for the report and the videos
Regards

**Closed by sle-odoo** 2017-11-20 16:23 UTC
Labels: 11.0, Logistics, need information
