### ISSUE TITLE
Code for amount currency removed WHY?

### ISSUE THREAD

**Issue by shazzwazz20** [odoo/odoo#44197] opened 2020-01-29 12:49 UTC
Impacted versions: 12.0

Steps to reproduce: Raise invoice in multicurrency . Then  create payment record of same amount.
Reconcile invoice from payment form view.

Current behavior:
In payment move line, amount currency not captured
Expected behavior:
In payment move line, amount currency should captured which works fine on Odoo 10.0

We found logic for capturing amount currency removed from 
account/models/account_payment.py
Method name : def _create_payment_entry

Below code removed from 12.0

        _invoice_currency = False
        _if self.invoice_ids and all([x.currency_id == self.invoice_ids[0].currency_id for x in self.invoice_ids]):
            #if all the invoices selected share the same currency, record the paiement in that currency too
            invoice_currency = self.invoice_ids[0].currency_id__

account/models/account_move.py
Method name ; def _compute_amount_fields

Below code removed from 12.0
        if invoice_currency and invoice_currency != company_currency and not amount_currency:
            amount_currency = src_currency.with_context(self._context).compute(amount, invoice_currency)
            currency_id = invoice_currency.

Question: Why this logic removed from odoo 12?
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2020-01-29 18:05
AFAIK, everything is working in multi-currency in v12. Please add specific steps to reproduce the problem and what do you expect and what you don't get, but don't mention missing code, because code moves, gets refactor, etc.

**Comment by shazzwazz20** [comment] 2020-01-30 10:21
Ok. 
I want amount currency to appear on payment move lines when invoice is reconciled.

For you reference i attached a document which help understand issue.

[Multicurrency Issue 12.0 .pdf](https://github.com/odoo/odoo/files/4133480/Multicurrency.Issue.12.0.pdf)

**Comment by pedrobaeza** [comment] 2020-01-30 14:10
You are modifying things and thus it's expected to fail, so this is not a valid use case.

Closing, and please take into account that this must be reproducible with standard code without changes.

**Closed by pedrobaeza** 2020-01-30 14:10 UTC
Labels: Need information

**Comment by shazzwazz20** [comment] 2020-01-30 14:14
Ok thanks for your feedback
