### ISSUE TITLE
[8.0] Concurrent update

### ISSUE THREAD

**Issue by max3903** [odoo/odoo#6737] opened 2015-05-15 20:51 UTC
# Impacted versions

8.0, maybe other (I didn't check)
# Scope

The scenario below is using the invoicing process as example, but the problem (no lock) is on every application.
# Scenario
- User 1 creates a supplier invoice, enter lines (total 1000 €) and click on update to compute the taxes.
- User 2 sees a draft invoice (created and edited by user 1), validates it and pays it.
- User 1 changes the lines (total 10 €) and save the invoice.
# Obtained result
- Invoice total is 10 €, journal entry is 1000 € and payment is 1000 €.
# Expected result
- When User 2 tries to validate the invoice, he should get a popup informing him that User 1 is still editing the invoice.
# Further information

https://www.odoo.com/fr_FR/forum/help-1/question/no-concurrency-check-when-updating-records-31916

**Comment by beledouxdenis** [comment] 2015-05-21 11:53
We cannot do what you suggest as expected result, to lock the editing of a record during anyone else is editing the document.

What we can do is prevent the change of some fields when the record is within a specific state, for instance, when the invoice is already validated, prevent the possibility to change the lines, the taxes, and so on.

But it will probably be an endless task, invoices is a case, but there are probably a lot more remaining.

Regards,

**Comment by odony** [comment] 2015-05-21 12:36
For the record, Odoo uses an optimistic locking strategy as often as possible (detect conflicts/problems when they happen), rather than a pessimistic locking strategy (lock everything beforehand to prevent conflicts and problems). 
This is a design choice in order to scale properly and avoid annoying users and blocking their actions because someone else forgot to finish the operation they were doing and went on coffee break or vacation.
We used to have a mechanism that compared the actual last update date of the record being edited with the last update date as it was when the record was displayed to the user. This was disabled in the past because it mostly puzzled users when they saw a conflict, and they invariably pushed the 'Update anyway' button, which means the net result wasn't different (last update wins)

In practice most detected conflicts were also not real conflicts, because it is extremely rare that 2 users would be editing the same record at the same time and within the same field! When it happens it often means that users are working on different aspects of the same record, so there would be no real conflict, both updates can proceed. To be more effective the detection system should track the last modification date of every field of every record, which would become totally prohibitive in terms of cost.

Now, the use case you describe could indeed happen, and because we are talking about invoices it would be nice to prevent it (also for direct RPC access, BTW) . But that should be done with a specific fix that prevents modifying certain fields of invoices (and invoice lines) when an invoice is already confirmed, not by (re)introducing a global change that annoys every user without guaranteeing that the problem will be solved.

**Comment by mmalorni** [comment] 2015-09-01 17:01
We have experienced the same issue ourselves in the Project module when we update tasks. One of the description was overwritten when 2 people edited it at the same time.
In one of our software we resolved the issue by using the last modification date and submitting the previous values of the changed field and the current values. If there is a sequence conflict but the previous values passed are the same as the ones in the database, we go ahead and make the change anyway, if not we can return the warning with the 3 different values and who made the change. This way, we do not have to store a last modification date for each field. The cost is just a slight overhead by returning the previous values.

**Comment by max3903** [comment] 2015-09-21 19:05
For the record, @odony provided us with a specification document to solve this issue. Once we find a commercial agreement, the development should be done by Odoo SA after the release of Odoo 9 and publicly available as a module.

**Comment by dreispt** [comment] 2016-02-05 09:51
Just got a complaint about the exact issue reported by @mmalorni .
Unless I'm missing something, an implementation based on last change timestamp shouldn't be difficult.
it could be something optional / to add on specific model, either buy a configuration setting or a small addon module.

**Comment by gurneyalex** [comment] 2016-02-15 15:24
@dreispt @max3903 the timestamp based implementation by TinyERP was funded by Camptocamp, only to be dropped later... :cry:

**Comment by dreispt** [comment] 2016-02-16 09:08
@gurneyalex Can it be rescued?

**Comment by gurneyalex** [comment] 2016-02-16 10:03
@dreispt the code is still there, dormant and wondefully unused. 

https://github.com/odoo/odoo/blob/9.0/openerp/models.py#L3478

**Comment by Colmea** [comment] 2016-02-16 10:28
@gurneyalex Do you think that making "_check_concurrency()" works again is enough to have a working OCC system ?
I mean, what about web client side ? It will only throw a "simple" exception I guess ?

**Comment by gurneyalex** [comment] 2016-02-16 10:59
@Colmea no idea at all. Please test and report back. I'm too young in the Odoo world to have seen this working.

**Comment by odony** [comment] 2016-02-16 12:37
@Colmea the major part (and the user-facing one) of this mechanism has to be implemented in the web client. It would have to fetch, store and send the `__last_update ` value for each record, and then open some sort of conflict resolution dialog whenever an update is rejected due to a conflict. The server-side part is trivial and presumably still working.
This is how it *used to work*, mind you, and that very implementation was dropped as too naive and counterproductive, as I tried to explain in an [earlier comment](https://github.com/odoo/odoo/issues/6737#issuecomment-104256029). A better alternative would have to be opt-in or opt-out, and ideally use heuristics to automatically resolve conflicts that can be, for example when the fields being updated have not changed in the database, as @mmalorni [suggested](https://github.com/odoo/odoo/issues/6737#issuecomment-136795761).

If anyone wants to work on a patch that implements this, I'd be happy to review it. Maybe at some point it could be included in the core as an optional module as well.

**Comment by michaelkarrer81** [comment] 2017-05-17 08:56
This may be  related: #17037

**Comment by dreispt** [comment] 2017-05-17 12:32
@odony any progress/plan for a `__last_update` based approach?

**Comment by odony** [comment] 2017-05-17 12:54
@dreispt My last comment still holds ;-)

**Comment by spadae22** [comment] 2017-05-17 15:17
For my two cents, when I used ePace now owned by EFI, we had a history button on the bottom of the page, you could click it and it would show every field change by user. Was very helpful and user could be aware of changes with asking around.

**Comment by dreispt** [comment] 2017-05-17 15:36
@spadae22 you might like the [auditlog](https://github.com/OCA/server-tools/tree/10.0/auditlog) feature, then.

**Comment by spadae22** [comment] 2017-05-17 15:41
@dreispt Yes love that, thanks!

**Comment by pedrobaeza** [comment] 2018-04-03 23:03
This was fixed since v9, and for v8, you have the OCA module https://github.com/OCA/server-tools/tree/8.0/base_concurrency, so I close this.

**Closed by pedrobaeza** 2018-04-03 23:03 UTC
