### ISSUE TITLE
Missing dependencies:  ["web.ControlPanelMixin"]

### ISSUE THREAD

**Issue by nomad-7** [odoo/odoo#47782] opened 2020-03-17 10:16 UTC
Impacted versions: Odoo 13 Community

Steps to reproduce:  addin module: https://apps.odoo.com/apps/modules/12.0/odoo_crm_dashboard/

Current behavior: Missing dependencies:     ["web.ControlPanelMixin"]
web.assets_common.js:89 Non loaded modules:       ["crm_dashboard.dashboard"]

Expected behavior:  no problem with 'web.ControlPanelMixi' at least

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2020-03-17 12:36
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2020-03-17 12:36 UTC
