### ISSUE TITLE
Error while creating Invoice

### ISSUE THREAD

**Issue by Techloyce-Odoo** [odoo/odoo#57989] opened 2020-09-18 07:02 UTC
**Impacted versions:**
V13 Enterprise

**Steps to reproduce:**
Invoice-> Create: Error Popup
Invoice -> Create Form view-> Add Date: Error Popup
Invoice -> Create Form view-> Add propduct: Error Popup
**Current behavior:**
I'm unable to create invoices.
**Expected behavior:**
Odoo proper behavior.

**Video/Screenshot link (optional):**
https://drive.google.com/file/d/1EcWl4f5tbbMu6S1vd9e4jiZivdc7PBbo/view?usp=sharing

**Comment by pedrobaeza** [comment] 2020-09-18 07:05
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos (current video is black).

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Techloyce-Odoo** [comment] 2020-09-18 07:33
On runbot Odoo13 Enterprise everything is working smoothly.
Sorry for the video I didn't double check it.
I'm using enterprise addons since 6 months suddenly I'm getting that error. Then i removed all my addons and place new one same error was appearing.

**Error While addind invoice line product:**

```
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo13/odoo/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo13/odoo/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo13/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo13/odoo/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo13/odoo/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo13/odoo/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo13/odoo/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo13/odoo/enterprise/addons/web/controllers/main.py", line 1320, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo13/odoo/enterprise/addons/web/controllers/main.py", line 1312, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo13/odoo/odoo/api.py", line 410, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo13/odoo/odoo/api.py", line 397, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/models.py", line 5911, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/opt/odoo13/odoo/odoo/models.py", line 5712, in _onchange_eval
    method_res = method(self)
  File "/opt/odoo13/odoo/enterprise/addons/account/models/account_move.py", line 2961, in _onchange_price_subtotal
    line.update(line._get_fields_onchange_subtotal())
  File "/opt/odoo13/odoo/enterprise/addons/account/models/account_move.py", line 2714, in _get_fields_onchange_subtotal
    date=date or self.move_id.date,
  File "/opt/odoo13/odoo/enterprise/addons/account/models/account_move.py", line 2739, in _get_fields_onchange_subtotal_model
    balance = currency._convert(price_subtotal, company.currency_id, company, date)
  File "/opt/odoo13/odoo/odoo/addons/base/models/res_currency.py", line 191, in _convert
    assert company, "convert amount from unknown company"
AssertionError: convert amount from unknown company
```

**Error while adding date in invoice:**

```
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo13/odoo/odoo/api.py", line 722, in get
    value = self._data[field][record._ids[0]]
KeyError: <NewId 0x7fdff3782dd8>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo13/odoo/odoo/fields.py", line 1040, in __get__
    value = env.cache.get(record, self)
  File "/opt/odoo13/odoo/odoo/api.py", line 728, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('account.move(<NewId 0x7fdff3782dd8>,).invoice_sequence_number_next', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo13/odoo/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo13/odoo/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo13/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo13/odoo/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo13/odoo/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo13/odoo/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo13/odoo/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo13/odoo/enterprise/addons/web/controllers/main.py", line 1320, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo13/odoo/enterprise/addons/web/controllers/main.py", line 1312, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo13/odoo/odoo/api.py", line 410, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo13/odoo/odoo/api.py", line 397, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo13/odoo/enterprise/addons/account/models/account_move.py", line 904, in onchange
    return super(AccountMove, self.with_context(recursive_onchanges=False)).onchange(values, field_name, field_onchange)
  File "/opt/odoo13/odoo/odoo/models.py", line 5917, in onchange
    for name in nametree
  File "/opt/odoo13/odoo/odoo/models.py", line 5918, in <listcomp>
    if name not in done and snapshot0.has_changed(name)
  File "/opt/odoo13/odoo/odoo/models.py", line 5785, in has_changed
    return self[name] != record[name]
  File "/opt/odoo13/odoo/odoo/models.py", line 5448, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo13/odoo/odoo/fields.py", line 1064, in __get__
    self.compute_value(recs)
  File "/opt/odoo13/odoo/odoo/fields.py", line 1145, in compute_value
    records._compute_field_value(self)
  File "/opt/odoo13/odoo/odoo/models.py", line 3825, in _compute_field_value
    getattr(self, field.compute)()
  File "/opt/odoo13/odoo/enterprise/addons/account/models/account_move.py", line 1146, in _compute_invoice_sequence_number_next
    number_next = sequence._get_current_sequence(sequence_date=sequence_date).number_next_actual
TypeError: _get_current_sequence() got an unexpected keyword argument 'sequence_date'
```

I'm using untouched enterprise addons which were downloaded about 6 months ago.

**Comment by pedrobaeza** [comment] 2020-09-18 07:36
Update everything, as it's not a problem of Odoo, but on your end.

For more help, please ask on forums, as this issue tracker is not for that purpose. Closing due to this.

**Closed by pedrobaeza** 2020-09-18 07:36 UTC
Labels: Need information
