### ISSUE TITLE
[V9] - Website / Backend Menus stop working

### ISSUE THREAD

**Issue by Gh0st4unt3r** [odoo/odoo#9201] opened 2015-10-22 13:42 UTC
Have been trying to solve this but unsure where else to look now and advise in the right direction would be great.

When in debug mode the menu items work on back end and able to open web front end as soon as i am out of debug mode i get reference errors and menus either do not show or do not load or are not clickable.

Front End website view errors: 

ReferenceError: odoo is not defined web_editor.summernote.js:3:26
ReferenceError: jQuery is not defined web_editor.editor.js:11:1
ReferenceError: odoo is not defined website.assets_frontend.js:3:1
ReferenceError: odoo is not defined website.assets_editor.js:3:1
ReferenceError: odoo is not defined dpwsmedia.com:52:17

Backend web side

ReferenceError: odoo is not defined web:15:25
unreachable code after return statement web.assets_backend.js:6696:266
ReferenceError: jQuery is not defined web.assets_backend.js:3:96
ReferenceError: $ is not defined web:27:25

attached is an image of the back end when menus don't show.
![view](https://cloud.githubusercontent.com/assets/13893077/10666694/2166ad2c-78cb-11e5-92b0-05a0bbe68999.png)

**Comment by Gh0st4unt3r** [comment] 2015-10-29 17:47
Fixed, had to reinstall odoo and import database which has stop any conflictions

**Comment by mamiu** [comment] 2015-11-13 11:03
@Gh0st4unt3r I have the same problem and yes, reinstalling odoo (sometimes only restarting) solves the issue. But that's only a short-time solution, because after a short time the problem occurs again.

I use version 9 (via Docker on Fedora).

**Comment by Gh0st4unt3r** [comment] 2015-11-13 14:09
@mamiu - Odoo v9 at the moment is having a few javascript problems, a good way to solve some of them is make a back up of the database.

Then,
Remove odoo but not the database using the ubuntu apt-get or fedora yum/rpm
Ubuntu - apt-get remove odoo
Fedora - yum remove odoo

update to the latest version using either ubuntu apt-get or fedora yum/rpm.
Ubuntu - apt-get update and apt-get upgrade commands
Fedora - yum update and yum upgrade

next step install odoo with latest version of v9
Ubuntu - apt-get install odoo
Fedora - yum install odoo

Note: you may want to try this first before upload of backup database

First thing to try after re-intsall of odoo is upload the file store usually located in /var/lib/odoo/.local/share/Odoo

Upload/Replace - filestore folder from the backup zip folder

If the above does not work delete the database in database manager and upload the backup you downloaded before and should fix the problem.

Please note: that this may fix this problem but any future javascript bugs in odoo it may or may not fix as i have a few outstanding javascript issues but the main ones with the menu / front menus actually work now by doing this method as i know it fixes most issues.

let me know how you get on with this.

**Comment by mamiu** [comment] 2015-11-18 17:03
I solved the issue by installing odoo on debian (without docker). I don't know whether the problem is due to docker or docker on Fedora.

**Comment by rriemann** [comment] 2015-11-22 22:37
I ask you to re-open this issue. Installation from scratch might be a work-around, but is not a solution. I experienced the same issue.

**Comment by Gh0st4unt3r** [comment] 2015-11-23 07:34
Issue has been Re-opened.

**Comment by gitoni** [comment] 2015-11-26 13:49
I think I experience the same issue too.

I have found this IOError in the logs:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_attachment.py", line 151, in _file_read
    r = open(full_path,'rb').read().encode('base64')
IOError: [Errno 2] No such file or directory: u'/var/lib/odoo/filestore/mydb/6d/6da170e99ed49
```

my setup: nginx proxy and the official 9.0 docker image.

**Comment by samuellefever** [comment] 2015-11-27 09:20
Same issue.
Is it possible that nginx is involved?
It tries to find something in the filestore that does not exists anymore.
If you connect from a new browser, it will fix the problem for all browsers... seems related to odoo web cache for me...

**Comment by matrixise** [comment] 2015-11-27 09:49
hi, sorry, but you don't give the right information.

1. Could we have the information about your infra ?
2. Do you have this problem if you don't use docker, just in a virtualenv or a dedicated server ?

**try in local, just with localhost**, maybe it's a problem with your reverse proxy. on the port 8069.

In debug mode (loglevel) do you have some 404 in the logs ?
in the debugger of chrome, you have some errors, but do you have some missing javascript files ?

please, give us more details.

thank you

**Comment by Gh0st4unt3r** [comment] 2015-11-27 12:11
@matrixise  My issue has been resolved when i reinstalled odoo, but others have asked me to reopen the issue as most are still getting this error. they have posted what issues they have

**Comment by mamiu** [comment] 2015-11-27 22:40
After installing odoo 9 on a VPS with debian 8 and nginx as reverse proxy I thought the problem would be solved. But after a period of time (about 5 days) the issue reappear. Rebooting solves the issue for the next ~5 days.

**Comment by gitoni** [comment] 2015-11-27 23:37
This issue seems to be related and it should be fixed with the most recent odoo release: 
https://github.com/odoo/odoo/issues/9495#issuecomment-160111488

**Comment by aliabdi71** [comment] 2016-03-09 08:56
Upgrading "Web" module fixed this issue for me. If you can't access to App page from Odoo, you could go to pgadmin and open the damaged database, change the state of "web" module in "ir_module_module" table from "installed" to "to upgrade" and restart the odoo server.

**Comment by nick2474** [comment] 2016-03-18 05:49
I think my safari browser cache was given some issues as well, i solved this doing and update by pgAdmin3

update ir_module_module set state='to upgrade' where name='web' and state='installed';

then:

http://192.168.1.2:8061/web/?debug=#id=19&view_type=form&model=ir.module.module&menu_id=51&action=36

and update the module Web.

Still this version looks nicer but too many issues to solve.

**Comment by atularvind** [comment] 2016-04-13 11:00
@samuellefever It worked, when I changed the browser from chrome to the firefox and load the website.  and after that also worked on the chrome.

**Comment by mamiu** [comment] 2016-04-15 09:20
@samuellefever @atularvind Yes, you're right! That was always the solution for me.

So not odoo is the problem but nginx (or rather the combination of both)?

**Comment by sle-odoo** [comment] 2016-06-13 11:14
Closing as it seems to be a [deployment issue](https://github.com/odoo/odoo/issues/9201#issuecomment-210378303).

Regards

**Closed by sle-odoo** 2016-06-13 11:14 UTC

**Comment by lucode** [comment] 2016-06-18 13:20
Maybe this issues could be related to this forum post [https://www.odoo.com/de_DE/forum/hilfe-1/question/v9-menu-disappears-and-logout-after-activating-developer-mode-95289]. I'm wondering why it gets closed despite of no evidence which the source of the error is?

**Comment by aulsai** [comment] 2016-09-29 10:09
Guys,

My solution is to delete the references from DB to filestore.

The steps
1.Query your db as this query.
`select id, create_date, store_fname, datas_fname from ir_attachment where datas_fname like '%.js%';`
2.Delete records that you found.
3.Done.

Thanks.

**Comment by atularvind** [comment] 2016-09-30 15:25
@aulsai kudos, that will also work! I tried with one of the affected database.

**Comment by jas-odoo** [comment] 2017-02-08 14:35
You can also delete js either from odoo interface or as @aulsai said

Technical -> Attachment -> search .js -> delete all records found.

**Comment by freddyheredia4** [comment] 2017-02-16 20:58
Thankyou!!! the solution of jas-odoo  works!!!

**Comment by daramousk** [comment] 2017-03-01 13:27
Indeed @aulsai's comment resolved my issue, but have we identify what causes this? Is there possibly a fix so there is no need to run this query again ?

**Comment by Renatov** [comment] 2017-06-10 21:43
Hi to all, one shape is configure the file odoo.conf u openerp-server.conf in line data_dir =  
Giving the correct address where the files are hosted will be better

**Comment by meatballcoder** [comment] 2017-06-21 20:52
@aulsai I am using Docker, and this fixed mine, and it fixed an issue I was having with reports and a ValueError, Singleton Expected error.  After I did the select statement, I did delete from.  I then had to stop my docker container and start it back up.

**Comment by raysgavin** [comment] 2017-07-23 01:44
@jas-odoo  your work can solution is issue.thanks!!
