### ISSUE TITLE
Cannot send sales Quotation via email

### ISSUE THREAD

**Issue by davshafik** [odoo/odoo#2574] opened 2014-09-21 08:34 UTC
i got this error while trying to send sales qutation via mail 

Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 496, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 513, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 279, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 276, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 723, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 372, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 941, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 933, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 235, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/addons/email_template/wizard/mail_compose_message.py", line 54, in default_get
    res.get('model'), res.get('res_id'), context=context
  File "/opt/odoo/odoo-server/openerp/api.py", line 235, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/addons/email_template/wizard/mail_compose_message.py", line 103, in onchange_template_id
    values = self.generate_email_for_composer_batch(cr, uid, template_id, [res_id], context=context)[res_id]
  File "/opt/odoo/odoo-server/openerp/api.py", line 235, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/addons/email_template/wizard/mail_compose_message.py", line 167, in generate_email_for_composer_batch
    template_values = self.pool.get('email.template').generate_email_batch(cr, uid, template_id, res_ids, fields=fields, context=ctx)
  File "/opt/odoo/odoo-server/openerp/api.py", line 235, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/addons/email_template/email_template.py", line 489, in generate_email_batch
    values['body_html'] = tools.append_content_to_html(values['body_html'], signature, plaintext=False)
  File "/opt/odoo/odoo-server/openerp/tools/mail.py", line 582, in append_content_to_html
    content = re.sub(r'(?i)(</?html.*>|</?body.*>|<!\W*DOCTYPE.*>)', '', content)
  File "/usr/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer

**Comment by lmurta** [comment] 2015-04-01 16:11
FineWind solution did not work for me.
I always get the following error:
```
2015-04-01 15:46:17,034 22885 ERROR pht openerp.addons.email_template.email_template: Failed to render template <Template memory:a710f9cc> using values {'format_tz': <function <lambda> at 0xa6dd0ae4>, 'ctx': {'lang': 'pt_BR', 'default_template_id': 7, 'tz': 'America/Sao_Paulo', 'uid': 1, 'mark_so_as_sent': True, 'active_model': 'sale.order', 'default_use_template': True, 'default_composition_mode': 'comment', 'params': {'action': 409}, 'tpl_partners_only': True, 'search_disable_custom_filters': True, 'active_ids': [5], 'default_model': 'sale.order', 'default_res_id': 5, 'active_id': 5}, 'user': res.users(1,), 'object': account.account.template(5,)}
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/addons/email_template/email_template.py", line 201, in render_template_batch
    render_result = template.render(variables)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python2.7/dist-packages/jinja2/sandbox.py", line 330, in getattr
    value = getattr(obj, attribute)
UndefinedError: 'openerp.api.account.account.template object' has no attribute 'partner_id'
2015-04-01 15:46:17,047 22885 ERROR pht openerp.addons.email_template.email_template: Failed to render template <Template memory:a71a110c> using values {'format_tz': <function <lambda> at 0xa6e248b4>, 'ctx': {'lang': 'pt_BR', 'default_template_id': 7, 'tz': 'America/Sao_Paulo', 'uid': 1, 'mark_so_as_sent': True, 'active_model': 'sale.order', 'default_use_template': True, 'default_composition_mode': 'comment', 'params': {'action': 409}, 'default_res_id': 5, 'search_disable_custom_filters': True, 'active_ids': [5], 'default_model': 'sale.order', 'tpl_partners_only': True, 'active_id': 5}, 'user': res.users(1,), 'object': account.account.template(5,)}
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/addons/email_template/email_template.py", line 201, in render_template_batch
    render_result = template.render(variables)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python2.7/dist-packages/jinja2/sandbox.py", line 330, in getattr
    value = getattr(obj, attribute)
UndefinedError: 'openerp.api.account.account.template object' has no attribute 'user_id'
2015-04-01 15:46:17,052 22885 ERROR pht openerp.addons.email_template.email_template: Failed to render template <Template memory:b4fa3e0c> using values {'format_tz': <function <lambda> at 0xa6e8e95c>, 'ctx': {'lang': 'pt_BR', 'default_template_id': 7, 'tz': 'America/Sao_Paulo', 'uid': 1, 'mark_so_as_sent': True, 'active_model': 'sale.order', 'default_use_template': True, 'default_composition_mode': 'comment', 'params': {'action': 409}, 'default_res_id': 5, 'search_disable_custom_filters': True, 'active_ids': [5], 'default_model': 'sale.order', 'tpl_partners_only': True, 'active_id': 5}, 'user': res.users(1,), 'object': account.account.template(5,)}
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/addons/email_template/email_template.py", line 201, in render_template_batch
    render_result = template.render(variables)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python2.7/dist-packages/jinja2/sandbox.py", line 330, in getattr
    value = getattr(obj, attribute)
UndefinedError: 'openerp.api.account.account.template object' has no attribute 'partner_invoice_id'


```

**Comment by zancos** [comment] 2015-07-03 09:28
Same issue here, but FineWind trick don't solve my problem...

:(

Anybody has found solution for this bug?

Thanks

**Comment by Yenthe666** [comment] 2016-06-03 10:10
Hi @davshafik,

I can no longer reproduce this issue on the latest codebase from Odoo 8.
Please update your Odoo environment and it should be fixed now.
I'm closing this issue since I can no longer reproduce this. If anybody still faces this problem (after updating the code) just post on this (with more information) and I will re-open this issue.

Regards,
Yenthe

**Closed by Yenthe666** 2016-06-03 10:10 UTC

**Comment by Odoo-Italia-Associazione** [comment] 2019-02-04 05:30
I have the same trouble with Odoo 10.0 CE sending invoice
2019-02-04 05:29:29,289 961 INFO improntadigitale odoo.addons.mail.models.mail_template: Failed to render template <Template memory7f8fb4632650> using values {'format_amount': <function <lambda> at 0x7f8fb5735c08>, 'object': mail.message(4304,), 'ctx': {u'uid': , 'button_access': {'url': '/mail/view?message_id=4304', 'title': u'Vista Fattura'}, u'journal_type': u'sale', 'mail_notify_user_sinature': False, 'has_button_unfollow': False, u'default_use_template': True, u'search_disable_custom_filters': True, u'default_mode': u'account.invoice', u'pivot_measures': [u'amount_total_signed', u'__count__', u'amount_untaxed', u'amount_net_pay'], u'tz': u'Euope/Rome', 'record': account.invoice(71,), u'pivot_column_groupby': [], u'params': {u'action': 196}, 'button_unfollow': {'url': '/mil/unfollow?model=account.invoice&res_id=71&token=6b3ffedce74ad53ff249a8f7f003dc0c85e27f65', 'title': u'Non seguire pi\xf9'}, 'follwers': res.partner(), u'custom_layout': u'account.mail_template_data_notification_email_account_invoice', u'type': u'out_invoice', 'default_res_id': 71, 'has_button_access': False, u'default_template_id': 5, 'record_name': u'FAT/2019/0051 ', 'company_name': u'Imronta Digitale s.r.l.', 'company': res.company(3,), 'safe': False, u'default_composition_mode': u'comment', u'mark_invoice_as_sent' True, 'actions': [], 'button_follow': {'url': '/mail/follow?model=account.invoice&res_id=71&token=f2ac81f4b7d2dc5148f03825d55b9dab367f58e', 'title': u'Segui'}, u'active_id': 71, u'lang': u'it_IT', 'tracking': [], 'is_discussion': True, u'active_model': u'accoun.invoice', u'pivot_row_groupby': [u'partner_id'], 'not_followers': res.partner(1114,), 'subtype': mail.message.subtype(1,), 'websit_url': u'http://www.improntadigitale.eu', 'signature': False, 'mail_auto_delete': True, u'active_ids': [71], 'has_button_follow': Flse, 'model_name': u'Fattura'}, 'format_tz': <function <lambda> at 0x7f8fb5735b18>, 'user': res.users(1,), 'format_date': <function<lambda> at 0x7f8fb5735848>}
Traceback (most recent call last):
  File "/opt/odoo/10.0/addons/mail/models/mail_template.py", line 394, in render_template
    render_result = template.render(variables)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 2, in top-level template code
  File "/usr/lib/python2.7/site-packages/jinja2/sandbox.py", line 330, in getattr
    value = getattr(obj, attribute)
UndefinedError: 'odoo.api.mail.message object' has no attribute 'partner_id'
