### ISSUE TITLE
website_sale  error 500 on sort

### ISSUE THREAD

**Issue by matmicro** [odoo/odoo#40161] opened 2019-11-13 08:00 UTC
Impacted versions: 10

Steps to reproduce: 
I don't know from where it comes, but i can see a lot of error 500 in my log files.
Website user try to sort products on my shop. The sort parameter is encoded, which provoke the error 500:
Got error with this:  
     GET /shop?category=11&order=list_price%2Basc
Should be this to works: 
     GET /shop?category=11&order=list_price+asc

Current behavior: Error 500

Expected behavior: Should it be decoded correctly ?
In which file to apply a fix ?

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2019-11-13 08:27
Sorry, but v10 is not anymore a supported version. Only last three versions are.

If the error is reproducible in later versions an in runbot, please comment back.

Closing due to this.

**Closed by pedrobaeza** 2019-11-13 08:27 UTC

**Comment by matmicro** [comment] 2019-11-13 08:44
You can reproduce the same with Odoo 13
Go to url : /shop?order=name%2Basc
You will get an error 500

**Comment by pedrobaeza** [comment] 2019-11-13 08:48
That's because that URL is malformed

**Comment by matmicro** [comment] 2019-11-13 08:58
Ok, but can we manage this ?
As it looks some pages are generating this malformed URL.
Maybe the login page with redirect ? or another ones...

**Comment by pedrobaeza** [comment] 2019-11-13 09:00
Sorry, but no if no steps to reproduce the problem (which is how do you get to that malformed URL).
