### ISSUE TITLE
Checks have wrong payment amount

### ISSUE THREAD

**Issue by Ashley-Allan** [odoo/odoo#21970] opened 2018-01-02 14:13 UTC
Impacted versions: v11.0

Steps to reproduce: Select multiple vendor bills in list view and pay them. Then go into any of the payments created and print check.

Current behavior: The amount that is typed out on the check is the total amount of all payments, not the amount for the specific vendor.

Expected behavior: The amount typed out on the check is the amount paid to that individual vendor

Video/Screenshot link (optional):
[Print Check (Top).pdf](https://github.com/odoo/odoo/files/1597734/Print.Check.Top.pdf)

**Comment by Yenthe666** [comment] 2018-01-04 13:33
Hi @Ashley-Allan,

Thanks for the report!
I've just tested this but I don't really see the bug?
An example of the vendor bills I started with:
![image](https://user-images.githubusercontent.com/6352350/34565694-1d20c07a-f15c-11e7-9f67-6d299f2ca64b.png)

The payment for those three vendor bills:
![image](https://user-images.githubusercontent.com/6352350/34565615-ccb10366-f15b-11e7-980a-6fc3fef7a39b.png)
The check for ASUSTeK:
![image](https://user-images.githubusercontent.com/6352350/34565656-f01f5e4c-f15b-11e7-923a-0dfb1292a070.png)
The check for Camptocamp:
![image](https://user-images.githubusercontent.com/6352350/34565668-04dbc7da-f15c-11e7-87b7-7a8827452024.png)

Am I missing something?

**Comment by Ashley-Allan** [comment] 2018-01-04 13:56
Hello Yenthe,

Your cheques don’t look like they have the amount printed out at all, do they? Basically the cheque has to have the amount numerically at the right of the cheque and also the amount typed out on the cheque. I have attached the one of the cheques I generated to the e-mail, with the 2 amounts circled. They don’t match each other. The correct number is the $4,121.11 on the right, and the $11,742.59 is actually the total of all the bills I paid in the one batch payment.
I duplicated the bug on the demo database, and I’m sending you some screenshots, but it looks like you took the same steps as me.

Regards,
Ashley

**Comment by Yenthe666** [comment] 2018-01-04 14:09
Hi @Ashley-Allan,

Thanks a lot for the feedback.
Ideal would be a video where you can reproduce this on a runbot, this would be the easiest to reproduce and confirm.
Otherwise more details & screenshots would be great. Thanks!

Regards,
Yenthe

**Comment by Ashley-Allan** [comment] 2018-01-04 15:20
Hello Yenthe,

The video is in the zip folder below. I think it is self-explanatory when you see it, but I can answer any questions you have. I recreated the problem on the online demo.

[Video.zip](https://github.com/odoo/odoo/files/1603720/Video.zip)

Ashley

**Comment by Yenthe666** [comment] 2018-01-05 07:14
Hi @Ashley-Allan,

Thanks a lot for the video.
I simply forgot to do one setting (check on check instead of default) which resulted in me this not noticing this.
This is indeed wrong. @qdp-odoo could you fix this when you've got some time please?

Regards,
Yenthe

**Comment by smetl** [comment] 2018-02-28 10:14
Hi @Ashley-Allan 

I'm trying to reproduce the issue depicted on your video. Maybe I missed something in the configuration but it seems fixed. Can you confirm it plz?

Thank you a lot.

Best regards,
Laurent

**Comment by qdp-odoo** [comment] 2018-02-28 14:58
I'm closing the issue, because of the "being already fixed presumption".

don't hesitate to reopen it if it's not the case

**Closed by qdp-odoo** 2018-02-28 14:58 UTC
Labels: 11.0, Accounting
