### ISSUE TITLE
[12] Bills and Invoices gets wrong Chart of Accounts from Product Category

### ISSUE THREAD

**Issue by netronuk** [odoo/odoo#28328] opened 2018-11-01 08:02 UTC
Impacted versions:
Odoo 12

Steps to reproduce:
https://www.odoo.com/forum/help-1/question/odoo-12-bills-and-invoices-gets-wrong-chart-of-accounts-from-product-category-141491

Current behavior:
COH account in Vendor Bill Product lines are from Stock Accounts not Income and Expense Account

Expected behavior:
The account of Products should be Income and Expense Accounts

Video/Screenshot link (optional):
https://www.odoo.com/forum/help-1/question/odoo-12-bills-and-invoices-gets-wrong-chart-of-accounts-from-product-category-141491

**Comment by netronuk** [comment] 2018-11-01 10:52
I tested Odoo Runbot as you suggested. It has SAME issue. See the screenshots. 

![odoo12-runbot-product-category](https://user-images.githubusercontent.com/33455439/47847764-280bf180-ddc4-11e8-9875-0dc61102b34f.JPG)

![odoo12-runbot- vendor bill](https://user-images.githubusercontent.com/33455439/47847766-2a6e4b80-ddc4-11e8-8be3-6f331efeb69c.JPG)

**Comment by netronuk** [comment] 2018-11-01 11:30
I sent you test result of Odoo-runbot on Odoo 12. I think it is bug. Even
on latest Odoo 12, it has same issue.

https://github.com/odoo/odoo/issues/28328

Regards,

*Nihat Demir*
*NETRON.UK <http://NETRON.UK>*
*Restaurant Marketing & Technology Solutions*
51 Fashion Street
London, E1 6PX
United Kingdom
Tel: 020 7117 9487
Mob: 077 36888 993
Email: nihat@netron.uk
Web: http://netron.uk

<http://www.netron.uk>

**Comment by pedrobaeza** [comment] 2018-11-01 11:34
OK, thanks for the extra info. Reopening until further checking an labeling.

**Comment by oco-odoo** [comment] 2019-09-30 11:19
Hi @netronuk ,

I tested in 12.0 with your workflow, and it seems to work fine now. Since the issue is quite old, it has probably been fixed since then. I'm closing this thread; if I am wrong and something is still wrong, of course, don't hesitate to signal it here.

**Closed by oco-odoo** 2019-09-30 11:19 UTC
Labels: 12.0, Accounting
