### ISSUE TITLE
 can't send messages nor add followers

### ISSUE THREAD

**Issue by safecoms** [odoo/odoo#15500] opened 2017-02-15 05:09 UTC
Impacted versions:  odoo 10

Steps to reproduce:

Current behavior:
File "/opt/sc/odoo/odoo/odoo/http.py", line 638, in _handle_exception return super(JsonRequest, self)._handle_exception(exception) File "/opt/sc/odoo/odoo/odoo/http.py", line 675, in dispatch result = self._call_function(**self.params) File "/opt/sc/odoo/odoo/odoo/http.py", line 331, in _call_function return checked_call(self.db, *args, **kwargs) File "/opt/sc/odoo/odoo/odoo/service/model.py", line 119, in wrapper return f(dbname, *args, **kwargs) File "/opt/sc/odoo/odoo/odoo/http.py", line 324, in checked_call result = self.endpoint(*a, **kw) File "/opt/sc/odoo/odoo/odoo/http.py", line 933, in __call__ return self.method(*args, **kw) File "/opt/sc/odoo/odoo/odoo/http.py", line 504, in response_wrap response = f(*args, **kw) File "/opt/sc/odoo/odoo/addons/web/controllers/main.py", line 866, in call_button action = self._call_kw(model, method, args, {}) File "/opt/sc/odoo/odoo/addons/web/controllers/main.py", line 854, in _call_kw return call_kw(request.env[model], method, args, kwargs) File "/opt/sc/odoo/odoo/odoo/api.py", line 681, in call_kw return call_kw_multi(method, model, args, kwargs) File "/opt/sc/odoo/odoo/odoo/api.py", line 672, in call_kw_multi result = method(recs, *args, **kwargs) File "/opt/sc/odoo/odoo/addons/mail/wizard/invite.py", line 63, in add_followers new_partners.with_context(auto_delete=True)._notify(message, force_send=True, send_after_commit=False, user_signature=True) File "/opt/sc/odoo/odoo/addons/mail/models/res_partner.py", line 156, in _notify ('notify_email', '!=', 'none')])._notify_by_email(message, force_send=force_send, send_after_commit=send_after_commit, user_signature=user_signature) File "/opt/sc/odoo/odoo/addons/mail/models/res_partner.py", line 201, in _notify_by_email new_emails, new_recipients_nbr = self._notify_send(fol_values['body'], fol_values['subject'], recipient_template_values['followers'], **base_mail_values)KeyError: 'body'
Expected behavior:

Video/Screenshot link (optional):

**Comment by meghaParmar** [comment] 2017-03-16 12:57
I am facing the same issue in my application. Is there anything you found to solve this issue?
Any hint will help me a lot.

**Comment by pedrobaeza** [comment] 2018-05-10 09:08
Hi, I'm not able to reproduce this problem in latest code, so I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Disclaimer**: I'm not an Odoo employee, but a community member that voluntary contributes to triage / classify / solve issues. Take also into account that there's no obligation to answer nor solving things put in Odoo Community issue tracker. And thus, please consider this as a best effort initiative.

**Closed by pedrobaeza** 2018-05-10 09:08 UTC
Labels: 10.0, Services
