### ISSUE TITLE
Can't edit multiple PO lines at a time when changing unit price on Confirmed Orders

### ISSUE THREAD

**Issue by ajmalj** [odoo/odoo#63531] opened 2020-12-17 12:33 UTC
Impacted versions: 13.0 Community

Steps to reproduce:
When editable bottom is disabled in PO Line tree
1. edit a PO with multiple products.
2. change a cost save the line.
3. click the next product.

Current behavior:
Get this error.
Traceback:
TypeError: Cannot read property 'list' of undefined

Expected behavior:
We can edit and save multiple lines

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/17050191/102488422-051b2500-4092-11eb-9f3a-5cc840412de9.png)

Tested in Runbot and has same error

**Comment by pedrobaeza** [comment] 2020-12-17 12:43
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by ajmalj** [comment] 2020-12-17 12:54
![image](https://user-images.githubusercontent.com/17050191/102490551-000ba500-4095-11eb-9466-79a8e0ba8056.png)
Got  similar error in runbot as well, Steps to reproduce same as above

**Comment by svs-odoo** [comment] 2020-12-29 11:29
Hello @ajmalj 
What do you mean when you said "when editable bottom is disabled" ?
Because I didn't achieve to reproduce your issue, with or without the editable bottom on the PO lines.
Could you give more information on the step to reproduce the issue please ?

**Comment by ajmalj** [comment] 2020-12-29 11:41
Hi @svs-odoo still getting the same error, it happens when po is confirmed and editable bottom is removed in po line tree, that is we open popup to edit. I will share the video as well from runbot. Thanks for the response

https://user-images.githubusercontent.com/17050191/103281468-d76e9e00-49f8-11eb-87dc-2cca37258843.mp4

**Comment by ajmalj** [comment] 2021-02-16 04:09
Hi @svs-odoo Any help on this issue,were you able to reproduce.

**Comment by svs-odoo** [comment] 2021-02-16 09:15
Hello @ajmalj 
No, sorry but I didn't achieve to reproduce it, even by reproducing steps in your video.
Do you have still the issue ? It doesn't look like related to purchase, so maybe it was fixed by a change on the JS side.

**Comment by ajmalj** [comment] 2021-02-16 09:25
I thinks it is fixed now, Thanks for the support. Is this commit related https://github.com/odoo/odoo/commit/dff91809c17bbd44b09a9e9b8509f5af043e0b95#diff-afb62bf7e8238d49cddb59fc4e00079f16a21bd420c4052c2f897d15ddad73ca

**Closed** 2021-02-16 09:26 UTC
Labels: 13.0, Logistics
