### ISSUE TITLE
List view inline creation have issues when change view filters

### ISSUE THREAD

**Issue by Tardo** [odoo/odoo#33258] opened 2019-05-08 14:20 UTC
Impacted versions:
View on 11.0

Steps to reproduce:
Got to list view (with inline creation), press "Create" button and remove an filter.

Current behavior:
New record line disappear and view buttons doesn't change... Press the "discard" button has no effect.

Expected behavior:
Warning or ignore creation record and restart buttons to the original state.

Video/Screenshot link (optional):

cc @Tecnativa

**Comment by pedrobaeza** [comment] 2019-05-08 14:22
@Tardo I would say that is an editable tree view as extra data. I added also the cc for indexing this issue.

@ged-odoo we have found this problem. Are you aware of it?

**Comment by sswapnesh** [comment] 2019-05-08 18:56
Duplicate of https://github.com/odoo/odoo/issues/31827

**Comment by pedrobaeza** [comment] 2019-05-08 18:59
Indeed, closing this one in favor of the other.

**Closed by pedrobaeza** 2019-05-08 18:59 UTC
Labels: 11.0, Framework
