### ISSUE TITLE
Odoo acts as the relay service for unknown email address causing the email not only marked as SPAM but deleted outright.

### ISSUE THREAD

**Issue by jasononggo** [odoo/odoo#50895] opened 2020-05-08 08:44 UTC
**I think you should take a look. Consider this scenario:**

**The consequence:**
Because of how Odoo acts as the relay service for unknown email address, the company rep is not notified simply because he did not receive the email (and No, the company rep will not check the CRM platform because from what I see, CRM platform works as a Chat platform, reading the whole message would be ineffective).

**Limit of consequence:**
Domain outside the organization is also affected by this issue (the recipient will not receive the email). for example @gmail.com

I simply propose Odoo to stop acts as the relay service for unknown email address and use the **catchall** for example

From: Original Sender's via Odoo <catchall@companydomain.com>

================================================================

Impacted versions: 13.0

Steps to reproduce:

1. Enable the G Suite SMTP relay service.

Allowed senders: Any addresses (not recommended)
Only accept mail from the specified IP addresses: Yes
Allowed IP addresses: Odoo server ip address
Require SMTP Authentication: No
Require TLS encryption: Yes

2. Configure the Outgoing Mail Server

a. G Suite SMTP relay service
Priority 1

**Connection Information**
SMTP Server | smtp-relay.gmail.com
SMTP Port | 587

**Security and Authentication**
Connection Security | TLS (STARTTLS) 

b. G Suite SMTP
Priority 5

**Connection Information**
SMTP Server | smtp.gmail.com
SMTP Port | 465

**Security and Authentication**
Connection Security | SSL/TLS
Username: catchall@companydomain.com
Password: xxxxx

Current behavior:

1. someone@rocketmail.com send an email to hello@companydomain.com
2. Odoo create new record / Lead.
3. companyrep@companydomain.com send a reply.
4. someone@rocketmail.com receive the email and reply it.
5. Odoo fetch the email and **act as the relay service** for @rocketmail.com **note: This is should not happen**
6. companyrep@companydomain.com **did not get notified since he did not receive the email.**

Note: Odoo only use the record with lower priority number (continue to act as the relay service even to unknown email), the higher priority number is ignored although the email is not @companydomain.com

**Expected behavior:**

6. **Odoo did not acts as the relay service for unknown email, instead use the Outgoing Mail Server with higher priority number.**

Note: I set 2 records for Outgoing Mail Server (one with smtp-relay.gmail.com and one with smtp.gmail.com)

a. G Suite SMTP relay service
Priority 1

**Connection Information**
SMTP Server | smtp-relay.gmail.com
SMTP Port | 587

**Security and Authentication**
Connection Security | TLS (STARTTLS) 

b. G Suite SMTP
Priority 5

**Connection Information**
SMTP Server | smtp.gmail.com
SMTP Port | 465

**Security and Authentication**
Connection Security | SSL/TLS
Username: catchall@companydomain.com
Password: xxxxx

**Comment by pedrobaeza** [comment] 2020-05-08 10:08
Old question:

https://twitter.com/Chris00393885/status/1231560354515341313?s=20

We handle this through a relay with SRS.

@Yenthe666 do you remember other issues with the same topic to be linked here or to close this one as duplicated?

**Comment by jasononggo** [comment] 2020-05-08 10:25
@pedrobaeza please wait. I am searching for SRS. The twitter link you mentioned is about spoofing.

**Comment by pedrobaeza** [comment] 2020-05-08 10:27
https://en.wikipedia.org/wiki/Sender_Rewriting_Scheme

**Comment by jasononggo** [comment] 2020-05-08 10:44
@pedrobaeza I am not sure I did not anything wrong. I followed the [Odoo 13.0 deployment document](https://www.odoo.com/documentation/user/13.0/discuss/email_servers.html#if-you-are-a-user-of-odoo-online-or-odoo-sh).

I have set up the SPF and DKIM authentication on the DNS record.

The problem (from twitter) is about customer got angry because did not get a reply.

**The problem I have is:**
Email from @rocketmail.com or @live.com forwarded by Odoo Outgoing Mail Server (using G Suite SMTP relay service) did not get through (only email from @gmail.com get through)

The SRS works for customer using @gmail.com and not @rocketmail.com or @live.com

I will post the detail, I am afraid you will close it.

**Comment by pedrobaeza** [comment] 2020-05-08 10:49
Odoo only works for now with one mail server, and this one makes spoofing, so I'm not linking things bad. You are the one that are expecting things that are not going to happen like selecting over other outgoing mail server. In fact, that doesn't serve for anything except manual mail templates that specify this outgoing server, or in mass mailing.

The underlying question in all of this is about Odoo replacing using the same "From:" when re-sending a mail to their followers.

**Comment by jasononggo** [comment] 2020-05-08 10:58
@pedrobaeza 

Thank you, I appreciate it. I do want to clarify that Odoo does replace the "From:" with SRS method (forwaded email by Odoo is written as is "From: Jack O. via companydomain.com"

However, **this seems to fail when the customer is using other email provider such as** @rocketmail.com (Yahoo) or @live.com (Microsoft)

Here are the details:

1. customer@gmail.com email forwarded by Odoo to companyrep@companydomain.com

Note: I have not set DMARC as it is not advised by the Odoo 13.0 deployment

```
Message ID | <CADp_G_8qd=RYwVVZ9sKPNJYVUQRHcK0L+Ze6zk1Apqz6GsHtfQ@mail.gmail.com>
-- | --
8 May 2020 at 17:42 (Delivered after 2 seconds)
"Jason O." <jasonong713@gmail.com>
"Jason O." <jason.onggo@tempatkerja.com>
Re: test2 mode: Relay
PASS with IP 209.85.220.97 Learn more
'FAIL' Learn more
```

**Comment by pedrobaeza** [comment] 2020-05-08 13:53
AFAIK Odoo doesn't replace `From:` header. GMail does it if you uses it as MTA. Probably the problem is the DMARC on rocketmail or MS part.

Any way, no fail message is included her for diagnosing this.

**Comment by jasononggo** [comment] 2020-05-08 16:25
@pedrobaeza I see, I will update tomorrow and close the issue after confirmation (probably caused by the Spam filter)

Right now I have reached the STMP relay service limit per user (I think G Suite is not Odoo friendly if you use the SMTP relay service with the Sender Rewriting Scheme).

I agree with your point of view. This is the email provider fault and not Odoo.

So, in conclusion:
1. If you use `stmp.gmail.com` and use the default route e.g hello@companydomain.com > catchall@companydomain.com

**Advantage:**
2,000 message per user per day
You don't have to configure the spam filter.

**Disadvantage:**
1. More storage used. If someone send a message to a document with 100 followers (stmp.gmail.com will send to 100 users). Your catchall inbox will be filled with 100 new inbox, send it again? 200 new inbox (the recipient would be fine, only receive 1 new message).

**Advantage and disadvantage at the same time.**
2. No one in your company know who send the email, the FROM header will be catchall@companydomain.com . From a business perspective, this will cut the flow of information if you decide to cut someone. But this will add confusion if there is two people with exact initial (Jack Richard and Jack Rocho, everyone use Jack R. as initial).

And you would not want that to happen to your Sales team, so either use Mailgun or other email provider (if you trust Mailgun)

2. If you use `stmp-relay.gmail.com` and use the default route e.g hello@companydomain.com > catchall@companydomain.com

Advantage:
1. It easier to identify who send the email.

Disadavantage:
1. you would face a hard limit of 130 per day per user, if you work in a Consultant company, this definitely won't work (normally you would invite 4 - 5 people in a document, the ops guy, the marketing guy, etc you name it). Let the calculation write it down:

a. Company rep create a document with followers s1@gmail.com to s5@gmail.com (those are our business partner), you send the invitation letter.
b. Someone from the partner side replied. Immediately the relay server send 4 copies each. Let's say everyone did the same. Immediately, 16 copies each.

Let calculate the number: 1 email * 5 copies + 1 email * 4 copies * 4 sender from the partner side = 21 mail relayed. **In short, the maximum email would be 27 per day / 6 - 7 email per user**

That is considering if that company rep only create 1 document / 1 client.

If your business model as such (a Consultant, per document there would be 4 - 5 business partner outside your organization email, handle 3 - 4 clients per day, which is highly likely), you either Mailgun STMP relay service or buy new user license to add the capacity.

**Comment by pedrobaeza** [comment] 2020-05-08 16:32
Note that GSuite has a relay mode for the domain, allowing the MTA to use any "From" coming from any possible user of the domain. This means that if your GSuite domain in `example.com`, then you can send from `usera@example.com`, `userb@example.com`, etc and they won't be changed. The problem / casuistic remains with other mails that don't belong to that domain. Or you have an intermediate mail relay between Odoo and your final MTA (Gmail, Mailgun or whatever), that do the SRS, then the domain of these resent mail may not allow that to DMARC policies (not yours).

**Comment by jasononggo** [comment] 2020-05-08 16:42
@pedrobaeza 

I want to confirm, do you mean:

DMARC policies of customer@rocketmail.com prevent catchall@companydomain.com to relay a message from customer@rocketmail.com > salesperson@companydomain.com.

**Comment by pedrobaeza** [comment] 2020-05-08 16:45
Yes

**Comment by jasononggo** [comment] 2020-05-08 16:53
I understand now. I spent a day and thought this must be Odoo or G Suite problem, turns out it's the DMARC policies (I confirmed that ive.com, outlook.com DMARC policies is set to 100% reject).

I will edit the previous comment I made to avoid confusion.

In short:

**If your customer is @live.com or @rocketmail.com or @yahoo.com or anything else that use DMARC policies with 100% rejection, you are stuck with option no. 1.**

I will close this.

**Closed** 2020-05-08 16:59 UTC

**Comment by EmirT** [comment] 2020-05-25 09:01
@kidfrom I have exactly the same issue with Mailjet. I asked @pedrobaeza in (#51698) thanks to him I found this conversation. Could you tell me please, how did you solve it? Many thanks.

**Comment by kidfrom** [comment] 2020-05-25 10:40
@EmirT 

I checked your issue and I think it's not the same. @pedrobaeza comment gave you the reason behind the design.

#51698

> **Expected behavior:**
Odoo should send notification from the company domain. This can be catchall or any other email setup.

**Tricks**
You can achieve this by using an actual account for example `catchall@yourdomain.com` instead of SMTP relay service `client@clientdomain.com`. Add it to the `Outgoing Mail Server` settings on Odoo.

**Consequences of using an actual account catchall@yourdomain.com**
1. If you do this, the size of the replied email will be much more bigger and it will be stored on catchall@yourdomain.com mail boxes. It's not a problem if you use paid service such as G Suite as they offer you unlimited space if you have more than 4 users.
2. If you use POP mail server instead of IMAP3 for the `Incoming Mail Server` settings on Odoo, the fetch process will be much more longer, especially if you did not use the SMTP relay service.

**Things that may confuse you why it is better to use client@clientdomain.com instead of catchall@clientdomain.com for the FROM header**
1. In business sense, a Salesperson would not always use Odoo but also use the mail server interchangeably, so it is highly likely that the Salesperson would ask to the IT department
```
Hey, who sent me this email? catchall@yourdomain.com? Hey IT, I think there is an error. How am I going to reply this email?
```

If you use SMTP relay service for example `G Suite` and you relayed a message from `client@clientdomain.com` to a recipient, the recipient will receive the email with the FROM header as `FROM: client@clientdomain.com via yourdomain.com`

`via yourdomain.com` is the SRS method @pedrobaeza mentioned, it's configured by the SMTP relay service providers.

Your Gmail or other mail server uses the Reply-To header to send a Reply. FROM header is just often misunderstood by non-IT department as the actual sender. Using catchall@yourdomain.com as the FROM header will only create confusion for the non-IT department.

2. Harder discovery. Ever think of searching client's conversation with `client@clientdomain.com` as the filter? You will lose this option if you choose to use catchall as the FROM header.

**Consequences of SMTP relay service**

1. Always ask your clients to use G Suite, Office 365 service or own mail server to communicate.
Do not use Yahoo as their DMARC policy is set to `REJECT`, meaning If you relayed client@yahoo.com mail to other recipient, and the DMARC failed, the recipient will not know the mail is sent to him/her, and the worst part is, the sender also do not know the mail failed to get through.

**I recommended you to stick with the current behavior `use SMTP relay service and avoid relaying Yahoo email` to avoid tons of question from the non-IT department.**

I hope this knowledge helps you.

**Comment by EmirT** [comment] 2020-05-25 11:00
@kidfrom Thanks for your reply, I will read them carefully. Just to let you know I wore myself the "expected behavior" not @pedrobaeza  :)  The case occurs during the delivering Notification. Odoo is using client's domain (during the incoming email, which is normal) and sends the notifications to subs, under the SMTP set up but still using the client domain. E.g.  Odoo (SMTP mailjet) - > Client = Ok, Client (a@clientdomain.com) -> Odoo = ok, Odoo (SMTP mailjet) and (a@clientdomain.com) -> Subs. = problem from the mailjet side. Becasue Mailjet has limit for 100 sender.  I hope explain well, I'd appreciate all help. Thanks, Emir.

**Comment by kidfrom** [comment] 2020-05-25 11:21
> @kidfrom Thanks for your reply, I will read them carefully. Just to let you know I wore myself the "expected behavior" not @pedrobaeza :) The case occurs during the delivering Notification. Odoo is using client's domain (during the incoming email, which is normal) and sends the notifications to subs, under the SMTP set up but still using the client domain. E.g. Odoo (SMTP mailjet) - > Client = Ok, Client ([a@clientdomain.com](mailto:a@clientdomain.com)) -> Odoo = ok, Odoo (SMTP mailjet) and ([a@clientdomain.com](mailto:a@clientdomain.com)) -> Subs. = problem from the mailjet side. Becasue Mailjet has limit for 100 sender. I hope explain well, I'd appreciate all help. Thanks, Emir.

Let me clarify, in a conversation, there will be 100 different recipients? You should use the mail marketing service by your mail provider or do you mean 100 relayed messages per day?

I believe it is more beneficial for you to actually write a `use cases`, in this case, I read you are going to use this for invoicing. I believe 100 relayed message per day between clients and the finance dept. with 3 replies with 3 subs `client, finance manager, finance staff` / a total of 6 relayed message. You should **design** the communication flow and the workload of the finance staff as well. Mine roughly 7 - 14 invoices per day, this should not exceed the quota.

I suggest you to see the pricing or documentation about the SMTP relay service provided by Mailjet.

If you use G Suite, you have quota per day `130 relayed messages per day per licensed user`

**Comment by EmirT** [comment] 2020-05-25 15:51
@kidfrom many many thanks to your replies. I much appreciated it. 

Please see the image **https://imgur.com/a/5iBPBau** Mailjet limits the sender with 100. 

There will be 100 recipients for good not daily. I use the Odoo for my business and I set it up with mailjet and I found out that I use Relay SMTP.

 I think this limitation is the problem, mailjet is not responsive in Customer Service so I am searching a way around. So far I changed the notification email template, added my domain in the "from" instead of client's so Odoo sends the notification always from catchall@mydomain. 

This is not a good solution therefore I need to find a better solution. Do you think I am missing something in the configuration? Is there a better SMTP provider rather than Mailjet ?

**Comment by kidfrom** [comment] 2020-05-26 04:13
@EmirT I suggest you to switch to a different mail provider if possible and **if needed**, try to weight your own **use cases** so you can find the right solution for your needs.

> This is not a good solution therefore I need to find a better solution. Do you think I am missing something in the configuration? Is there a better SMTP provider rather than Mailjet ?

It's not you, it's your current mail provider's policy. Do not invest time in company with bad customer service.

I recommend you to use **G Suite**. I believe you will consider to build your own mail server in the future after calculating the possible monthly costs, **try not to until** you reached considerable amount of cost to be saved, and you have a dedicated staff for maintaining the mail server architecture.

**Comment by ray-odoo** [comment] 2021-09-01 21:48
Please also see https://github.com/odoo/odoo/pull/69218 and the use of the system parameters: mail.force.smtp.from and  mail.dynamic.smtp.from in cooperation with mail.catchall.domain
