### ISSUE TITLE
[Odoo 13] Help Me, After print using qweb show error like this !

### ISSUE THREAD

**Issue by cakrabirawa** [odoo/odoo#64181] opened 2021-01-07 04:51 UTC
Odoo13, Win 10
Error:
Something happened while trying to contact the server, check that the server is online and that you still have a working network connection.

Please how to fixed it
many thanks

![image](https://user-images.githubusercontent.com/7353693/103852706-0367de80-50df-11eb-8a33-3e6a08c8a573.png)

Pycharm Log
--------------
2021-01-07 11:54:28,786 4316 INFO odoo13db werkzeug: 127.0.0.1 - - [07/Jan/2021 11:54:28] "POST /web/action/load HTTP/1.1" 200 - 13 0.031 0.061
2021-01-07 11:54:29,177 4316 INFO ? werkzeug: 127.0.0.1 - - [07/Jan/2021 11:54:29] "GET /web/static/src/img/spin.png HTTP/1.1" 304 - - - -
2021-01-07 11:54:30,303 4316 INFO odoo13db odoo.addons.base.models.ir_actions_report: Generating PDF on Windows platform require DPI >= 96. Using 96 instead. 
2021-01-07 11:54:33,137 4316 INFO odoo13db werkzeug: 127.0.0.1 - - [07/Jan/2021 11:54:33] "GET /web/content/268-b247f36/web.report_assets_pdf.css HTTP/1.1" 200 - 4 0.035 0.076
2021-01-07 11:54:33,166 4316 INFO odoo13db werkzeug: 127.0.0.1 - - [07/Jan/2021 11:54:33] "GET /web/content/376-ed4ae8d/web.report_assets_common.css HTTP/1.1" 200 - 4 0.024 0.113
2021-01-07 11:54:33,169 4316 INFO odoo13db werkzeug: 127.0.0.1 - - [07/Jan/2021 11:54:33] "GET /web/content/377-ed4ae8d/web.report_assets_common.js HTTP/1.1" 200 - 4 0.029 0.106
2021-01-07 11:54:33,171 4316 INFO odoo13db werkzeug: 127.0.0.1 - - [07/Jan/2021 11:54:33] "GET /web/content/353-154c3e2/web.assets_common.js HTTP/1.1" 200 - 4 0.029 0.110
2021-01-07 11:54:33,395 4316 INFO ? werkzeug: 127.0.0.1 - - [07/Jan/2021 11:54:33] "GET /web/static/src/fonts/lato/Lato-Reg-webfont.woff HTTP/1.1" 200 - - - -
2021-01-07 11:54:33,410 4316 INFO ? werkzeug: 127.0.0.1 - - [07/Jan/2021 11:54:33] "GET /web/static/src/fonts/lato/Lato-Lig-webfont.woff HTTP/1.1" 200 - - - -
2021-01-07 11:54:35,448 4316 INFO ? werkzeug: 127.0.0.1 - - [07/Jan/2021 11:54:35] "GET /web/static/src/fonts/lato/Lato-Hai-webfont.woff HTTP/1.1" 200 - - - -
2021-01-07 11:54:35,448 4316 INFO ? werkzeug: 127.0.0.1 - - [07/Jan/2021 11:54:35] "GET /web/static/src/fonts/lato/Lato-Bol-webfont.woff HTTP/1.1" 200 - - - -
2021-01-07 11:54:35,449 4316 INFO ? werkzeug: 127.0.0.1 - - [07/Jan/2021 11:54:35] "GET /web/static/src/fonts/lato/Lato-Bla-webfont.woff HTTP/1.1" 200 - - - -
2021-01-07 11:54:37,074 4316 INFO odoo13db odoo.addons.base.models.ir_actions_report: The PDF report has been generated for model: ado.model.hospital.patient, records [1]. 
2021-01-07 11:54:37,081 4316 INFO odoo13db werkzeug: 127.0.0.1 - - [07/Jan/2021 11:54:37] "POST /report/download HTTP/1.1" 200 - 215 0.423 7.507
2021-01-07 11:54:37,749 4316 INFO odoo13db odoo.addons.base.models.ir_actions_report: Generating PDF on Windows platform require DPI >= 96. Using 96 instead. 
2021-01-07 11:54:40,194 4316 INFO odoo13db werkzeug: 127.0.0.1 - - [07/Jan/2021 11:54:40] "GET /web/content/376-ed4ae8d/web.report_assets_common.css HTTP/1.1" 200 - 4 0.006 0.029
2021-01-07 11:54:40,195 4316 INFO odoo13db werkzeug: 127.0.0.1 - - [07/Jan/2021 11:54:40] "GET /web/content/377-ed4ae8d/web.report_assets_common.js HTTP/1.1" 200 - 4 0.006 0.029
2021-01-07 11:54:40,196 4316 INFO odoo13db werkzeug: 127.0.0.1 - - [07/Jan/2021 11:54:40] "GET /web/content/268-b247f36/web.report_assets_pdf.css HTTP/1.1" 200 - 4 0.005 0.033
2021-01-07 11:54:40,222 4316 INFO odoo13db werkzeug: 127.0.0.1 - - [07/Jan/2021 11:54:40] "GET /web/content/353-154c3e2/web.assets_common.js HTTP/1.1" 200 - 4 0.008 0.054
2021-01-07 11:54:40,370 4316 INFO ? werkzeug: 127.0.0.1 - - [07/Jan/2021 11:54:40] "GET /web/static/src/fonts/lato/Lato-Reg-webfont.woff HTTP/1.1" 200 - - - -
2021-01-07 11:54:40,377 4316 INFO ? werkzeug: 127.0.0.1 - - [07/Jan/2021 11:54:40] "GET /web/static/src/fonts/lato/Lato-Lig-webfont.woff HTTP/1.1" 200 - - - -
2021-01-07 11:54:42,419 4316 INFO ? werkzeug: 127.0.0.1 - - [07/Jan/2021 11:54:42] "GET /web/static/src/fonts/lato/Lato-Bla-webfont.woff HTTP/1.1" 200 - - - -
2021-01-07 11:54:42,419 4316 INFO ? werkzeug: 127.0.0.1 - - [07/Jan/2021 11:54:42] "GET /web/static/src/fonts/lato/Lato-Bol-webfont.woff HTTP/1.1" 200 - - - -
2021-01-07 11:54:42,420 4316 INFO ? werkzeug: 127.0.0.1 - - [07/Jan/2021 11:54:42] "GET /web/static/src/fonts/lato/Lato-Hai-webfont.woff HTTP/1.1" 200 - - - -
2021-01-07 11:54:43,471 4316 INFO odoo13db odoo.addons.base.models.ir_actions_report: The PDF report has been generated for model: ado.model.hospital.patient, records [1]. 
2021-01-07 11:54:43,477 4316 INFO odoo13db werkzeug: 127.0.0.1 - - [07/Jan/2021 11:54:43] "POST /report/download HTTP/1.1" 200 - 215 0.278 6.044

**Comment by pedrobaeza** [comment] 2021-01-07 07:13
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2021-01-07 07:13 UTC
