### ISSUE TITLE
Variant Cost is impossible

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#21572] opened 2017-12-11 20:20 UTC
Impacted versions: 11.0

Steps to reproduce:
Enable Variants
Attempt to update cost

Current behavior:
The update cost behaviour is hidden on both the template and variant views so it seems no way to set cost.
Also no way to view cost on the variant form.

This is really a usability bug.  A user should be able to Go to a Product -> Set Cost on the usual form.

NOT go to Product Templates, Click Variants, Select From List, and use special cost editing and viewing form there.  

As it stands you cannot click through from any related model (e.g. Pickings, Purchase) and update cost.

Expected behavior:
To set and view cost on the product form.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment] 2017-12-12 07:25
@mart-e we might want to look into this. 😉

**Comment by lap-odoo** [comment] 2017-12-12 15:51
@bst-odoo could you please have a look at this one (related to variants)? Thanks ;)

**Comment by bst-odoo** [comment] 2017-12-13 12:17
Hello @gdgellatly ,

Indeed the cost price is now only on the variant form (when variants are enabled).

I couldn't reproduce your issue on our side (runbot V11) :  

https://drive.google.com/a/odoo.com/file/d/1OH7icyh7bXqH7qBjzQFVPEMClzXj1vH3/view?usp=drivesdk
https://drive.google.com/a/odoo.com/file/d/1oGUMzRj0huZEYEtTKDAsLFWlZFKBnMql/view?usp=drivesdk

Maybe the bug was fixed in the meantime.

Kr,

BST

**Comment by tivisse** [comment] 2019-11-12 11:22
Hi @gdgellatly 

Sorry for the delay. I just checked on the latest 11.0 version, and it seems to be fixed since that time.

![image](https://user-images.githubusercontent.com/8435879/68667772-10bf2280-0547-11ea-8892-be99f6dc2684.png)

Have a nice day,

Yannick.

**Closed by tivisse** 2019-11-12 11:22 UTC
Labels: 11.0, Functional Review

**Comment by Yenthe666** [comment] 2019-11-12 13:10
What would you expect in 2 years 😆
