### ISSUE TITLE
Python odoo translatıon error odoo15

### ISSUE THREAD

**Issue by dogancantorun8** [odoo/odoo#123633] opened 2023-06-04 11:19 UTC
I want to create translation file for custom module Odoo15 .But i get this error from system. How can i handle it

Errror : 
Traceback (most recent call last):
  File "C:\Users\Dogancan\Desktop\odoo-local\odoo\odoo\http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Users\Dogancan\Desktop\odoo-local\odoo\odoo\http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: ("Can't load unknown file type %s.", 'i18n/tr.po')

**Comment by dogancantorun8** [comment] 2023-06-04 14:00
I did the same operation as in the video. I imported the exported .po file to my module. However, the error did not resolve. When I debug the error detail, I saw that this error was return  from the file named "convert.py". (I am sharing the file below) I added the .po file extension here. However, I still could not translate my module.

with file_open(pathname, 'rb') as fp:
if ext == '.csv':
convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
elif ext == '.sql':
convert_sql_import(cr, fp)
elif ext == '.xml':
convert_xml_import(cr, module, fp, idref, mode, noupdate)
elif ext == '.js':
pass # .js files are valid but ignored here.
elif ext == '.po':
pass # .po files are valid but ignored here.

**Comment by duong77476** [comment] 2023-06-05 03:44
The po file and pot need to export in the module and then import via runnung server.
The step when i want to update translation for some modules, let's say `account`.
In case you want to overide the old translation you will First go to setting app, locate the translation tap -> export translation. you need to export both pot and po file for the language you want and run server again then update module.

In case you want modify translation only, you only need to locate to po file you want to edit in the code and then edit it then run server again and update module

**Comment by dogancantorun8** [comment] 2023-06-13 20:58
I did it the way you mentioned. However, in the current situation, I am not getting any error. But my translation files are still not working. There is no error log at the moment. What should I do? @duong77476

**Comment by duong77476** [comment] 2023-06-14 01:02
> I did it the way you mentioned. However, in the current situation, I am not getting any error. But my translation files are still not working. There is no error log at the moment. What should I do? @duong77476

Ok, please record the video then i can see whether you doing it correct or not

**Comment by vava-odoo** [comment] 2023-07-13 06:50
Closing as not a bug in standard Odoo

**Closed by vava-odoo** 2023-07-13 06:50 UTC
