### ISSUE TITLE
ODOO 8 bugged with latest chrome update 20160415

### ISSUE THREAD

**Issue by mcarropellicer** [odoo/odoo#11717] opened 2016-04-15 11:13 UTC
Impacted versions: 8.0

Steps to reproduce:

Log in and try to access any module.

Current behavior:

I noticed Odoo 8 is not working with the latest version of Chrome (20160415 - "Version 50.0.2661.75 m"), only appears the header and the content is blank.

Works perfectly in "Version 49.0.2623.112 m", confirmed in some machines of our company, just after the upgrade stops working.

**Comment by wtaferner** [comment] 2016-04-15 11:14
Duplicate of https://github.com/odoo/odoo/issues/11629#issuecomment-210409651

**Closed** 2016-04-15 11:14 UTC

**Comment by mcarropellicer** [comment] 2016-04-15 11:17
@wtaferner Sorry for create a duplicated issue, thanks for link the issue!

**Comment by wtaferner** [comment] 2016-04-15 11:40
@mcarropellicer 
Nevermind, everyone is here to help and get help ;-)
