### ISSUE TITLE
Consider changing the way Odoo handles the db management password and safer defaults

### ISSUE THREAD

**Issue by greaber** [odoo/odoo#23103] opened 2018-02-15 23:13 UTC
Using Odoo with docker, I was bitten by the problem that it is not enough to persist /var/lib/odoo and the db; I also had to persist /etc/odoo/odoo.conf because otherwise the database management password would get reset every time the container was restarted: https://github.com/odoo/docker/issues/167

I found it somewhat surprising that Odoo application state was being stored in a conf file.  I think it would be nice if all state could be kept in /var/lib/odoo, but if that is not going to happen because it would be too backwards incompatible, I would at least like a promise that all state will be either in /var/lib/odoo or in /etc/odoo/odoo.conf.

I also think that Odoo should be defaulting to something more secure than having no password for managing the db or at least giving very loud warnings if someone is running in a completely insecure state.  It took me a week to recognize that there was something wrong, and someone else might never have noticed.  This is especially an issue with docker, and it doesn't help that the official docs for the docker image say that you can bind mount odoo.conf if you want to customize it, but suggest that you don't need to if you don't want to customize it.

**Comment by jpaulin** [comment] 2018-03-12 08:00
The only thing that comes to my mind is that blank password or default password equal in strength. They're both bad. So the solution would be asking for a explicit password during installation, probably via non-interrupting way, so if people use the install script as part of deployment, it won't "hang"?

**Comment by greaber** [comment] 2018-03-12 09:31
Postgres doesn't store its password in the .conf file, and also usually it is protected by a firewall or (with docker) it runs on a private network.  And the password is necessary for everything; there is anot an extra "database administration password" that you may never use for anything but that you need to set to something secure to avoid your security being compromised.  So there is not so much of a security gotcha.

Odoo could require setting a password when you first configure it (which could help even non-docker users) and then complain and fail to work if later the odoo.conf file goes back to the default (because someone is naively dockerizing Odoo the way the odoo-docker documentation still recommends).  It would be even better for docker users if Odoo would stop storing state in odoo.conf, but I understand if that would be too backwards incompatible, and that's why I just asked for a promise about where state will be kept.

**Comment by greaber** [comment] 2018-03-12 09:33
The ODOO_RC method might work too,  but currently I am bind mounting odoo.conf into the container, which works OK although it complicates things slightly since the first time Odoo is set up you need to first copy odoo.conf out of the container so that it can be bind mounted.

**Comment by gdgellatly** [comment] 2018-03-12 09:35
@greaber you don't need to have your db password in the conf file is what I'm trying to say.  In fact, in truth you don't even really need a conf file.  There is nothing in that file that can't be passed in a run command via an env file.

**Comment by greaber** [comment] 2018-03-12 09:49
I thought you were saying that you can use ODOO_RC to set an alternative location for odoo.conf.  In any case, the main problem is not that there aren't good solutions for using Odoo securely or for using it securely with docker but that it is too easy for someone to shoot themselves in the foot, especially if they don't read all the docs carefully.

**Comment by thomas15v** [comment] 2018-03-12 13:39
Not only with docker. I have seen Odoo websites without docker that had no admin password set at all. it was also setup with https, so you could securely delete their databases (oh the irony).

It's oké that Odoo gives you a warning that no password has been set. But ONLY after you created a database. The problem is that most folks don't know about the '/web/database/manager' url and assume everything is Oké.

I think this issue should address a way that negates the chance of someone setting up Odoo insecurly. Maybe by generating a password after the first database has been created or disabling the management page if no password has been set.

The most useful solution I could think of is generating a new password when someone visits the page. Make that said password be printed in the console or witten to a file. After an hour, the password becomes invalid and can't be used anymore. This ensures that only people with access to the server can use the management page.

**Comment by chickahoona** [comment] 2020-06-20 07:20
Honestly... How is this not getting more attention... So every time someone upgrades his docker'ed Odoo instance, he will  have to set a password manually?

There is no explicit warning on the docker hub page https://hub.docker.com/_/odoo

So even if you don't want to change the default value and so on, **you have to warn people that the default configuration is insecure and that they have to create a custom config and specify a master password** That needs to be written in bold letters there!

**Comment by pedrobaeza** [comment] 2021-05-31 06:37
AFAIK, Odoo now changes default admin password to a more secure one the first time you access the system, so closing this.

**Closed by pedrobaeza** 2021-05-31 06:37 UTC
Labels: Framework, Wishlist
