### ISSUE TITLE
Error when I want create a backup of database

### ISSUE THREAD

**Issue by kurkop** [odoo/odoo#11583] opened 2016-04-02 20:33 UTC
Impacted versions:
9.0

Steps to reproduce:
Click in backup database, enter password of admin.

Current behavior:
- Return this message (in web):
```Database backup error: 'NoneType' object has no attribute '__getitem__'```

Other comment: I can create a database from windows browser, fails in Fedora with Firefox

Expected behavior:
```Normal backup```

Video/Screenshot link (optional):
http://stackoverflow.com/questions/36098859/odoo-database-backup-error

**Comment by bistaray** [comment] 2016-05-09 17:11
I am now getting this.  I get the message from Windows 10, Chrome.  My colleague gets the error when using an Ubuntu VM, but CAN use a Windows 10 machine with Chrome.  Very confusing!!

**Comment by isaacmv** [comment] 2016-05-21 14:16
I'm having the same issue, but it comes when my VPS is overloaded in dchacesize or numfile parameters (I check this in my Virtuozzo admin panel). So, I've to restart the container and then everything goes fine again, allowing me make backups in pg_dump or zip format.

**Comment by twohex** [comment] 2016-07-11 10:21
Also having this issue. It can be solved manually by loging to database. After that backup works because additional cookie gets sent to backup script. 
If you have some automation here you need to login, save the cookie and make a new request with the cookie provided.

**Comment by edsersolis** [comment] 2016-07-12 12:58
> Actually it is enough only to visit any database login page. After that the backup works.

The above didn't work for me, however login to the DB and than trying to backup did the trick. Thanks!

**Comment by dreispt** [comment] 2016-07-14 14:02
My guess is that the Odoo server is being started without the `-d` (or `--database`) option.
If so the instance startup is delayed until a login is made to a database.
If the database if specified as an option, the instance startup sequence is immediately performed on thea database.

**Comment by dreispt** [comment] 2016-07-14 14:02
Not a bug, workarounds were provided: closing.

**Closed by dreispt** 2016-07-14 14:02 UTC
