### ISSUE TITLE
Website's sign-in link goes missing

### ISSUE THREAD

**Issue by danielyen** [odoo/odoo#6776] opened 2015-05-20 03:27 UTC
Website's sign-in link disappears when I did the following:
1. As admin, edit Group -> Public.
2. In editing Public, add a regular user under Users tab.
3. In editing Public, under Access Rights, enable Write Access for Partners.
4. Save, and log out.
5. Website's sign-in link on the top menu disappears.
   
   Rolling back the changes, the Sign-in link stays missing.

Version 8.0-20150519

**Comment by joe1981alAPR** [comment] 2016-11-14 23:08
I would like to confirm this is still occurs in version 10.

Testing another issue I added a user to the "Other Extra Rights / Public" group and the "Sign In" link disappeared.

I removed the user from the group but the sign in option is still missing.

**Comment by qsm-odoo** [comment] 2017-12-06 15:35
Hello,
Thank you for your bug report, sorry we did not handle it earlier. The issue is in fact a general issue of our framework and will so be fixed as soon as possible.

cc @JKE-be @ged-odoo @aab-odoo

**Comment by frederic-meyrou** [comment] 2018-01-09 23:27
Dear all,

Do you know how to fix the problem while the framework patch is not published?
I have the same problem on Odoo V9 latest revision.

Tks a milion

./Frédéric

**Comment by JKE-be** [comment] 2018-01-09 23:30
You can reactivate public user
Add public user into public group
And désactivate the public user

That should fixes your problem

**Comment by JKE-be** [comment] 2018-01-09 23:30
Or just tick checkbox on public user should be enough !

**Comment by pedrobaeza** [comment] 2018-04-03 22:58
No further answer, so I close this issue.

**Closed by pedrobaeza** 2018-04-03 22:58 UTC
Labels: 9.0, Framework

**Comment by aitorbouzas** [comment] 2018-07-19 13:19
This issue just happened to me in v11. Any workaround? Sign in button seems to show only to public users group, but for some reason anonymous user can't see the button.

**Comment by qsm-odoo** [comment] 2018-07-19 14:11
Going to the "Public User" form view in debug mode and checking the "Public" checkbox should do the trick. Is it not the case ?

**Comment by aitorbouzas** [comment] 2018-07-19 14:14
@qsm-odoo Yes, that trick works. Any way, won't this problem be patched? It's been in Odoo for 3 years now.

**Comment by qsm-odoo** [comment] 2018-07-19 14:57
This will be patched, I will ping the bug fix team to check into it.

**Comment by aitorbouzas** [comment] 2018-07-19 14:59
Thank you, I really appreciate it.

**Comment by qsm-odoo** [comment] 2018-07-19 15:10
(opw-1867934)
