### ISSUE TITLE
No content helper keeps appearing after deleting a record  in List view with editable="top" option

### ISSUE THREAD

**Issue by synersyserp** [odoo/odoo#24842] opened 2018-05-22 07:20 UTC
Impacted versions: Odoo version 10

Steps to reproduce:
List view with option editable="top" (or bottom)

e.g.
><tree editable="top" string"somestring">

Delete a record > Save

Current behavior:
No content helper (class="oe_view_nocontent_create") keeps appearing after delete record in List view with option editable="true" even though it's not yet empy

Expected behavior:
No content helper (class="oe_view_nocontent_create") should only be called when there is item/content in list view

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/18321775/40347473-07a4f61a-5dd3-11e8-9e98-de5dd186dfae.png)

**Comment by pedrobaeza** [comment] 2018-05-22 07:28
Hi, I'm not able to reproduce this problem in latest runbot version, so I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-05-22 07:28 UTC
