### ISSUE TITLE
Sale price causes website crash

### ISSUE THREAD

**Issue by jwnickel** [odoo/odoo#24689] opened 2018-05-12 15:47 UTC
Impacted versions:11 Community

Steps to reproduce: Updating sale price or clicking in the sale price field after entering product name.

Current behavior: Causes the site to crash and reload.

Expected behavior: Should be allowed to update or select sale price without crashing.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2018-05-13 08:43
Hi, I'm not able to reproduce this problem in latest runbot version, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-05-13 08:43 UTC

**Comment by jwnickel** [comment] 2018-05-13 08:46
It's still there and it is a clean install.  It appears to be an issue with Edge.  Chrome seems to handle it without issues.
