### ISSUE TITLE
[14.0] The attached document link of web page doesn't show correct icon

### ISSUE THREAD

**Issue by dottdev** [odoo/odoo#69276] opened 2021-04-15 02:13 UTC
Impacted versions: 14.0

Steps to reproduce: Adding a document of a web page when editing the web page.

Current behavior: When Editing a web page, trying to add a document (eg. pdf) .
![image](https://user-images.githubusercontent.com/7236822/114803964-ff7ce400-9dd2-11eb-9831-f76a865971b9.png)
![image](https://user-images.githubusercontent.com/7236822/114804001-19b6c200-9dd3-11eb-9f9e-57d1c7a2ac4e.png)

The document icon will show "unknown" icon. 
![image](https://user-images.githubusercontent.com/7236822/114803601-533afd80-9dd2-11eb-94d8-0bca60122a25.png)

Expected behavior: should be like this...
![image](https://user-images.githubusercontent.com/7236822/114803647-69e15480-9dd2-11eb-9a72-e3fbb934e274.png)

**Comment by dottdev** [comment] 2021-04-18 03:02
By the way, I noticed that the html code of the attachment component lacks attribute of "data-mimetype" of <a>.
Once I add "data-mimetype" attribute as "application/pdf", the right icon would show up.

**Comment by rdeodoo** [comment] 2021-05-11 13:35
Hello, may I ask you to check if the issue is still occurring on an updated fresh install or on runbot?
Working fine on my end, maybe a bugfix was already merged in the meantime

![image](https://user-images.githubusercontent.com/30048408/117824116-7c826880-b26e-11eb-9196-24366462f5a7.png)

**Closed** 2021-05-31 22:51 UTC
Labels: 14.0, Confirmed, Website

**Comment by dottdev** [comment] 2021-06-26 00:42
Sorry for my late reply. After I updated, this issue was gone already. Thanks for your attention.
