### ISSUE TITLE
Error when trying the trail version 

### ISSUE THREAD

**Issue by chengsu2328** [odoo/odoo#63134] opened 2020-12-10 09:45 UTC
Error:
Uncaught TypeError: resp.indexOf is not a function

https://www.odoo.com/zh_CN/thanks/trial?re=https%3A%2F%2Fas17a.odoo.com%2Fsaas_worker%2Ftrial_do%3Fstudio_module%3D%26username%3DLucasFu%26country_code%3DHK%26module%3Dstock%253Asale_management%253Apurchase%26client_id%3Dafefec73-1e47-4485-8be5-b97f6b14e1fc%26dbname%3Dlong%26lang%3Dzh_CN%26confirm_token%3Dba999593-d7ef-4081-8402-f27513b2ad7f%26sync_after_creation%3DFalse%26company_name%3Dlong%26template%3D%26email%3Dchengsu2328%2540163.com%26dep_modules%3Dmail%253Aaccount&app=stock%3Asale_management%3Apurchase&dbname=long:186
Traceback:
TypeError: resp.indexOf is not a function
    at https://www.odoo.com/zh_CN/thanks/trial?re=https%3A%2F%2Fas17a.odoo.com%2Fsaas_worker%2Ftrial_do%3Fstudio_module%3D%26username%3DLucasFu%26country_code%3DHK%26module%3Dstock%253Asale_management%253Apurchase%26client_id%3Dafefec73-1e47-4485-8be5-b97f6b14e1fc%26dbname%3Dlong%26lang%3Dzh_CN%26confirm_token%3Dba999593-d7ef-4081-8402-f27513b2ad7f%26sync_after_creation%3DFalse%26company_name%3Dlong%26template%3D%26email%3Dchengsu2328%2540163.com%26dep_modules%3Dmail%253Aaccount&app=stock%3Asale_management%3Apurchase&dbname=long:186:74

**Comment by pedrobaeza** [comment] 2020-12-10 12:31
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Yenthe666** [comment] 2020-12-22 11:01
Closing as there has been no feedback.

**Closed by Yenthe666** 2020-12-22 11:01 UTC
Labels: Need information
