### ISSUE TITLE
"odoo.py setup" command errors

### ISSUE THREAD

**Issue by dreispt** [odoo/odoo#2834] opened 2014-10-01 13:45 UTC
I guess the Odoo setup command is complaining because the default branch is now 8.0 instead od master.

This is the output and error:
    $ odoo/odoo.py setup
    odoo:git repo found at /home/odoo/odoo-dev/odoo
    odoo:running git config alias.st status
    odoo:running git config merge.commit no
    odoo:running git config pull.ff only
    odoo:running git config alias.pl pull --ff-only
    odoo:running git config remote.odoo.url https://github.com/odoo/odoo.git
    odoo:running git config remote.odoo.pushurl git@github.com:odoo/odoo.git
    odoo:running git config --add remote.odoo.fetch dummy
    odoo:running git config --unset-all remote.odoo.fetch
    odoo:running git config --add remote.odoo.fetch +refs/heads/_:refs/remotes/odoo/heads/_
    odoo:running git config remote.odoo-dev.url https://github.com/odoo-dev/odoo.git
    odoo:running git config remote.odoo-dev.pushurl git@github.com:odoo-dev/odoo.git
    odoo:running git remote update
    Fetching origin
    Fetching odoo
    From https://github.com/odoo/odoo
     \* [new branch]      5.0        -> odoo/heads/5.0
     \* [new branch]      6.0        -> odoo/heads/6.0
     \* [new branch]      6.1        -> odoo/heads/6.1
     \* [new branch]      7.0        -> odoo/heads/7.0
     \* [new branch]      8.0        -> odoo/heads/8.0
     \* [new branch]      master     -> odoo/heads/master
     \* [new branch]      posbox     -> odoo/heads/posbox
     \* [new branch]      saas-1     -> odoo/heads/saas-1
     \* [new branch]      saas-2     -> odoo/heads/saas-2
     \* [new branch]      saas-3     -> odoo/heads/saas-3
     \* [new branch]      saas-4     -> odoo/heads/saas-4
     \* [new branch]      saas-5     -> odoo/heads/saas-5
    Fetching odoo-dev
    From https://github.com/odoo-dev/odoo
     \* branch            HEAD       -> FETCH_HEAD
    odoo:running git config branch.master.remote odoo
    odoo:running git config branch.master.merge refs/heads/master
    odoo:running git checkout master
    error: pathspec 'master' did not match any file(s) known to git.
    Traceback (most recent call last):
      File "odoo/odoo.py", line 162, in <module>
        main()
      File "odoo/odoo.py", line 156, in main
        cmds[sys.argv[1]]()
      File "odoo/odoo.py", line 144, in cmd_setup
        cmd_setup_git()
      File "odoo/odoo.py", line 95, in cmd_setup_git
        run('git','checkout','master')
      File "odoo/odoo.py", line 39, in run
        subprocess.check_call(l)
      File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '('git', 'checkout', 'master')' returned non-zero exit status 1

**Comment by Yenthe666** [comment] 2016-06-03 09:48
Hi @dreispt,

Could we close this one? I can't reproduce it anymore. :smile:

**Comment by Yenthe666** [comment] 2017-06-27 12:02
@dreispt shouldn't be relevant anymore? Closing this one.

**Closed by Yenthe666** 2017-06-27 12:02 UTC
