### ISSUE TITLE
CORS Error on Website Backend when Google Analytics is enabled

### ISSUE THREAD

**Issue by alex71m-zz** [odoo/odoo#61986] opened 2020-11-19 09:43 UTC
Impacted versions: v13

Steps to reproduce: go to backend 'Website' app

Current behavior:
with google analytics enabled, odoo reacts with "Unknown CORS Error"
looking at the browser console, the following error message is reported:

cb=gapi.loaded_0:1283 Uncaught TypeError: window.google.load is not a function
    at d (cb=gapi.loaded_0:1283)
    at dF (cb=gapi.loaded_0:1283)
    at nF._.h.VK (cb=gapi.loaded_0:1301)
    at _.Xy._.h.no (cb=gapi.loaded_0:757)
    at _.AC.Ac (cb=gapi.loaded_0:1064)
    at cb=gapi.loaded_0:1290
    at e.Ar (cb=gapi.loaded_0:370)
    at $k (cb=gapi.loaded_0:373)
    at Vk (cb=gapi.loaded_0:373)
    at _.Gk.pT (cb=gapi.loaded_0:373)

due to that the visitors charts doens't appear.

Expected behavior:
working analytics charts for visitors and alike

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/13301337/99648090-eefa5480-2a52-11eb-8043-c6bfd6f8bec6.png)

**Comment by pedrobaeza** [comment] 2020-11-19 09:46
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by alex71m-zz** [comment] 2020-11-19 10:55
Hallo Pedro

 

In order to activate the analytics on the webpage backend app, I need to prove that I own the domain on google console.

This is going to be difficult on runbot infrastructure.

Any other suggestion?

 

Best Regards / Mit freundlichen Grüssen / Distinti saluti / Atenciosamente

F.Alex Maone

**Comment by alex71m-zz** [comment] 2020-11-19 11:01
Just for your reference:



 

Best Regards / Mit freundlichen Grüssen / Distinti saluti / Atenciosamente

F.Alex Maone

**Comment by pedrobaeza** [comment] 2020-11-19 14:45
In my experience, this error is because Analytics is not well configured, but Odoo has nothing to do with it.

**Comment by alex71m-zz** [comment] 2020-11-19 15:17
Hi Pedro

 

I had the analytics working until a couple of weeks ago.

Then I updated my installation with a new build, and it didn’t anymore…

I’ll try with a fresh db and let you know….

 

 

Best Regards / Mit freundlichen Grüssen / Distinti saluti / Atenciosamente

F.Alex Maone

**Comment by pedrobaeza** [comment] 2020-11-19 15:19
Yes, please do such test.

**Comment by gregory-moka** [comment] 2020-11-20 11:19
Hi @alex71m-zz 
Are you using Safari browser ?

I had the same error when I'm trying to edit style on text (font-color) with the web editor. And, the error only appear on Safari browser.

```
Erreur:
Erreur CORS inconnue

Une erreur CORS inconnue est survenue. L'erreur est probablement due à un fichier JavaScript provenant d'une source externe. (Ouvrir votre la console de votre navigateur, vous donnera certainement une indication)
```

**Comment by alex71m-zz** [comment] 2020-11-20 11:29
Hi Gregory

Actually I didn’t tried with Safari, but with both Chrome and Edge the error stays...

Best regards / Mit freundlichen Grüßen 
Francesco A. M.

**Comment by alex71m-zz** [comment] 2020-11-20 11:31
Just tried Safari...same results...

Best regards / Mit freundlichen Grüßen 
Francesco A. M.

**Comment by alex71m-zz** [comment] 2020-11-23 14:53
Hi Pedro

 

I did the test as promised.

In a fresh installation, the issues I mention didn’t occur.

Then I have installed my former apps one after the other and found the culprit.

For me you can close the issue since not directly caused by odoo rather by an app.

Thanks again for your support.

 

 

Best Regards / Mit freundlichen Grüssen / Distinti saluti / Atenciosamente

F.Alex Maone

**Comment by pedrobaeza** [comment] 2020-11-24 08:03
OK, good to know. If it's a public module, you can share which one it is for others to know.

**Closed by pedrobaeza** 2020-11-24 08:03 UTC
Labels: Need information
