### ISSUE TITLE
Statistics Invoice exception division by Null

### ISSUE THREAD

**Issue by UteHaus** [odoo/odoo#51627] opened 2020-05-20 14:22 UTC
Impacted versions: 13.0-20200417 (Community Edition) 

System: Odoo run on Docker with Postgre SQL 

Steps to reproduce: Open Invoicing App --> Tab Reporting select Invoicing --> remove all filters --> on Measures select only _Due Amount_ --> on Filters Select _Cusomers_ 

Expected behavior: Show amount due on table view. 

The exception only occurs if the total amount due is 0.

`Fehler:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1322, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 383, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 356, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/account/report/account_invoice_report.py", line 191, in read_group
    result = super(AccountInvoiceReport, self).read_group(domain, fields, set(groupby) | {'currency_id'}, offset, limit, orderby, lazy)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2140, in read_group
    result = self._read_group_raw(domain, fields, groupby, offset=offset, limit=limit, orderby=orderby, lazy=lazy)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2265, in _read_group_raw
    self._cr.execute(query, where_clause_params)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 164, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 241, in execute
    res = self._obj.execute(query, params)
psycopg2.DataError: FEHLER:  Division durch Null`

**Comment by pedrobaeza** [comment] 2020-05-20 17:48
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by UteHaus** [comment] 2020-05-20 21:18
I cant reproduce the exception on runbot. I have a clear installation of odoo with one invoice. 
In the zip is the video file, with the steps to reproduce the exception.
[invoices-report-bug.zip](https://github.com/odoo/odoo/files/4659267/invoices-report-bug.zip)

This is the network request with params and the answer:
[invocing report exception .txt](https://github.com/odoo/odoo/files/4659327/invocing.report.exception.txt)

**Comment by pedrobaeza** [comment] 2020-05-21 06:58
Yeah, but that can be because you don't have latest source code on your local installation or data is somehow corrupted. We need the exact steps to be able to reproduce the problem to know the source of the bug (if any).

I'm closing this while you get that steps.

**Closed by pedrobaeza** 2020-05-21 06:58 UTC
Labels: Need information
