### ISSUE TITLE
13.0 sale_margin: method "_compute_margin" convert currency without checking if necesary

### ISSUE THREAD

**Issue by luismaring** [odoo/odoo#52562] opened 2020-06-07 22:37 UTC
Impacted versions: 13.0

Steps to reproduce:
Install module sale_margin

Current behavior:

The method _compute_margin convert currency in case its different than the company's default but an "if" is missing at line 19 in file sale_order.py

Expected behavior:
Convert currency only when pricelist currency is different from company's currency

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2020-06-08 06:48
Please indicate steps to reproduce a problem before analyzing code and give relative line codes that may change through time. If you have the patch clear, you can propose a PR with it and indicating the same steps to reproduce the problem.

**Comment by pedrobaeza** [comment] 2020-07-18 15:01
Closing as no more answers and the issue is not clear.

**Closed by pedrobaeza** 2020-07-18 15:01 UTC
Labels: 13.0, Need information
