### ISSUE TITLE
[master] Can not install Invoice module

### ISSUE THREAD

**Issue by Bonainifo** [odoo/odoo#35781] opened 2019-08-17 16:34 UTC
Impacted versions: Master 20190817

Steps to reproduce:
Install invoice module
Current behavior:
During install received an error massage:

   raise ValueError('External ID not found in the system: %s' % xmlid)
odoo.tools.convert.ParseError: "External ID not found in the system: base.module_payment_sepa_direct_debit" while parsing file:/d:/odoo13/odoo/addons/payment/data/payment_acquirer_data.xml:2, near
<odoo noupdate="1">

Expected behavior:

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment] 2019-08-17 16:44
Can you please upgrade `base` module and try again ?

**Comment by pedrobaeza** [comment] 2019-08-17 18:56
Master is in heavy development and this kind of problem can for sure happen meanwhile, but it's not a problem of unintended behavior that is more prone to be notified through an issue, so closing.

**Closed by pedrobaeza** 2019-08-17 18:56 UTC
