### ISSUE TITLE
duplication on pos order odoo 13

### ISSUE THREAD

**Issue by ibrahim08** [odoo/odoo#42862] opened 2020-01-07 14:24 UTC
Impacted versions: odoo 13 enterprise 

Steps to reproduce: multi threading, nginx proxy and workers are configured, have 90 point of sale, hundred of orders per day

Current behavior: odoo create some orders twice(around 30 orders), odoo duplicate the same order with same receipt number but different Order Ref(sequence) and different create_on. 

Expected behavior: no duplication of pos orders

Video/Screenshot link (optional): order exported in excel sheet

[Repeated Orders (2).xlsx](https://github.com/odoo/odoo/files/4031007/Repeated.Orders.2.xlsx)

**Comment by pedrobaeza** [comment] 2020-01-07 15:50
This should be fixed in #40600, so closing. Please update your code.

**Closed by pedrobaeza** 2020-01-07 15:50 UTC

**Comment by mah007** [comment] 2020-08-26 12:30
i think they didnt fix it yet

**Comment by HaydarZaraki** [comment] 2021-02-16 08:43
> i think they didnt fix it yet

yes the issue still occur

**Comment by mah007** [comment] 2021-02-21 18:55
and it repeated on sale order too 
https://github.com/odoo/odoo/issues/66580

**Comment by Belal-Abdullah** [comment] 2022-02-02 09:59
@ibrahim08 
@mah007 
@HaydarZaraki 
I face the problem on using Odoo14 EE , can you share your experience on solving this issue?

**Comment by mah007** [comment] 2022-02-02 11:16
it is on community and enterprise and they don't wanna investigate why it happen

**Comment by Belal-Abdullah** [comment] 2022-02-02 11:24
I think it's comes from client side, and they are providing a solution for server side by checking on pos_reference field before creating new order.

**Comment by javierjcf** [comment] 2022-12-22 10:44
Same problem here, some times pos orders are duplicated. but i cannot reproduce the error in my unit test.
In my case checking pos_reference in backend it is not a solution cause i have to duplicated orders (with a second of difference) with unique pos_reference, but same serial number!.

I think this issue is still not solved, many people saying that after clossing the issue
