### ISSUE TITLE
[hw_escpos] Concurrency problem accessing PosBoxless proxy printer

### ISSUE THREAD

**Issue by TheCloneMaster** [odoo/odoo#1957] opened 2014-08-25 07:12 UTC
Hi,

We are testing Posboxless with some TM-T220 Epson Esc/Pos matrix printers.
Everything works great with only some minor adjustments to receipt width (as they can print less columns than thermal ones and font types A/B are swapped)

Only issue is with concurrent access to printer.  As they are way slower than thermal ones, and maybe they have different buffering schemas, under normal operation even one single receipt send to the queue will trigger two simultaneous I/O operations (like "open cash box" and "receipt" and they will clash and enter a "resource busy" error cycle.

On closer inspection, if you add a couple flags, you will notice that two or more printer open and _raw operations are being received and processed from the queue before previous one has finished, producing this problem

We fixed it by serializing access to the printer with a lock at controllers/main.py in method "run"
We "lock" right after the "try" and then on "finally" we release the printer with a call to del printer and then release the lock.

**Comment by cv-clearcorp** [comment] 2015-02-12 01:12
Hi, I am not sure if this is the same problem, but we have concurrency errors on a posbox-less implementation.

We are running a posbox instance on a desktop, with an Epson thermal printer. Everything works as it is supposed. But from time to time, printing a ticket fails with a "already in use" error. After this error is encountered, the odoo process has to be restarted to be able to print again.

We created an udev rule changing the owner of the printer device to the posbox user and the mode to 600. But something keeps accesing it causing the error. At first we thought it was cups or something similar. But reading this, we think it may be odoo itself.

I do not have access to the computer at this moment, but I will tomorrow. @fvdsn , have you tested the changes proposed by @kron623 ?

Thanks

**Comment by mdo-odoo** [comment] 2015-02-12 08:04
This issue is solved now. You need to upgrade your local installation.

**Comment by jorenvo** [comment] 2015-11-20 11:09
These types of issues should have been solved now. The posbox has also come a long way since these issues happened so I'm closing this. Don't hesitate to open a new issue if you're still experiencing problems.

**Closed by jorenvo** 2015-11-20 11:09 UTC
Labels: RD

**Comment by feseme** [comment] 2016-11-11 04:50
Hi everyone. I have a problem when printing a ticket from the pos. I'm using posbox (raspberri pi 2 + posbox img v 4) + Epson tm u220 (matrix printer). It prints the ip perfectly but when i print a ticket from the pos it prints some question marks and some symbols, and it continue printing without stoping (errno 110... last trace back...). I think its because it tries to print the odoo logo (the tm u220 is text only), so i need how to remove the odoo logo from the pos ticket altering the pos.xml. thanx in advance for your help.

**Comment by jorenvo** [comment] 2016-11-14 23:53
@feseme are you sure that is what the issue is? One easy 'fix' is simply removing the company logo in the backend. Without a logo the POS will resort to printing the company name instead.

**Comment by feseme** [comment] 2016-11-15 14:51
@jorenvo can u please explain to me, how can i remove the logo?

**Comment by jorenvo** [comment] 2016-11-15 17:08
@feseme if you go to settings > general settings > configure your company data, you can temporarily delete the logo to see if that fixes the problem
