### ISSUE TITLE
Error at creating Fleet vehicle with driver connected to an existing user Without administration rights

### ISSUE THREAD

**Issue by a-ali24** [odoo/odoo#54199] opened 2020-07-07 18:44 UTC
Impacted versions: 13

Steps to reproduce:
1-Create a vehicle from user that have no Administration/Access Rights rights
2-in the creation of it add a driver who has an existing user on the database

Current behavior:
Got error because of the access rights that odoo was trying to modify someting on the user but couldn't complete this because the user has no right to write/create in res.users
note: this error happens in the first creation only -> if i created vehicle without driver then edited it to add driver the error will not show up
another note: the error is in fleet module i dont know how because i reviewed the code and didn't find any line that modify in res.users

Expected behavior: 
to create the vehicle normally with any driver

Video/Screenshot link (optional):

![error_1](https://user-images.githubusercontent.com/13247526/86827464-50b4b600-c092-11ea-9b49-88eb03280a1c.png)

![error_2](https://user-images.githubusercontent.com/13247526/86827487-57dbc400-c092-11ea-80d1-9e0ecfdbd137.png)

**Comment by pedrobaeza** [comment] 2020-07-08 07:02
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the green door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by a-ali24** [comment] 2020-07-08 11:21
yes the error showed up on the runbot database 
to reproduce the error :- 
1- login from the user demo/demo
2- try to create fleet with selecting the driver (Mitchell Admin)

why mitchell admin? because its another contact who has a user on the database

here is a video for the error on the runbot database (no missing configurations or custom modules)
https://youtu.be/zIwhfFeXAgY

**Comment by a-ali24** [comment] 2020-07-09 13:51
More information ?

**Comment by sswapnesh** [comment] 2020-07-09 19:01
@pedrobaeza  I can confirm this issue.

**Comment by Yenthe666** [comment] 2020-07-10 06:21
Not sure if it falls under marketing honestly but tagged.

**Comment by LucasLefevre** [comment] 2020-07-15 07:39
Hello,
Thanks for the feedback.
I managed to reproduce the issue in a test https://github.com/odoo/odoo/commit/9881fe6fb24d7ecd0adb461e3982c0fb5186728a
I don't have the time to find a proper fix right now, but I'll keep it in mind and come back to it as soon as possible

Have a nice day,
Lucas

**Comment by a-ali24** [comment] 2020-07-29 15:15
any updates?

**Comment by Yenthe666** [comment] 2020-07-29 15:20
No update as long as there is no new comment or PR ;)

**Comment by sswapnesh** [comment] 2021-01-09 17:55
This has been Fixed in Commit 2a8b56174609d15bf1c38e7b47515b397f40b707 https://github.com/odoo/odoo/pull/56192

**Closed** 2021-01-09 17:56 UTC
Labels: 13.0, Confirmed, Marketing
