### ISSUE TITLE
[9.0] Incorrect quantities invoicing received quantities

### ISSUE THREAD

**Issue by qtheuret** [odoo/odoo#8646] opened 2015-09-21 14:25 UTC
Tested in runbot http://102770-9-0-6a752d.runbot6.odoo.com

Looks like https://github.com/odoo/odoo/issues/8587 but for purchase side.

To reproduce:

Be sure that in sales/configuration/settings invoice sent quantities has been clicked.
1. Create a purchase order
2. Include a product that is set Invoiced on deliveries (C-Case)
3. Confirm the purchase order
4. Go to reception, receive less than the ordered quantity,

Current behavior:
- Invoice from purchase order is not created.

Expected behavior:
- Invoice created with a line containing the same quantity as received quantity.

**Comment by jco-odoo** [comment] 2015-09-29 09:20
You need to invoice from the sale order or purchase order after reception.

**Comment by jco-odoo** [comment] 2015-09-29 09:20
Or there is a menu Vendor Bills in case of purchase orders and you need to do it from there.

**Comment by jco-odoo** [comment] 2015-09-29 09:22
@mart-e still confirmed?

**Comment by qtheuret** [comment] 2015-09-30 07:09
@jco-odoo For the purchase order after reception, I have no option to make the invoice. But if I go the Vendor bills menu, I can see the bills for my reception.
Another issue I saw: The vendor bill has been well created, but on the purchase order form, Odoo indicates me 0 invoices for this PO.

**Comment by pedrobaeza** [comment] 2018-04-10 01:01
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-04-10 01:01 UTC
Labels: Confirmed
