### ISSUE TITLE
Accounting charts not shown when inputting journal entries

### ISSUE THREAD

**Issue by fweng322** [odoo/odoo#11765] opened 2016-04-21 05:30 UTC
Impacted versions: 9.0

Steps to reproduce:
1. Create an user with adviser rights to accounting management
2. Create the accounting charts with admin accounts first
3. When inputting the journal entries with admin accounts, it worked well. [1], but with user accounts nothing shown in the accounting chart menu [2]

Current behavior:
Please see [1] and [2]

Expected behavior:
users with adviser rights should be able to choose from existing accounting chart

Video/Screenshot link (optional):
[1] http://imgur.com/TjKxoaS
[2] http://imgur.com/i0xLKJE

**Comment by pedrobaeza** [comment] 2018-04-24 08:07
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-04-24 08:07 UTC
Labels: 9.0, Accounting
