### ISSUE TITLE
Traceback when accessing "Interview Form" field from "Job Position" form.

### ISSUE THREAD

**Issue by jpr-odoo** [odoo/odoo#6158] opened 2015-04-06 10:57 UTC
click on "Interview Form" field in "job position" form view. 
it's gives trackback:
raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'res_model' in leaf "<osv.ExtendedLeaf: ('res_model', '=', 'hr_recruitment') on survey_survey (ctx: )>" 

![image](https://cloud.githubusercontent.com/assets/7599806/7003544/79ce2524-dc79-11e4-8cc3-9c346f5d37cc.png)

**Comment by jpr-odoo** [comment] 2015-04-08 06:00
It has been fixed in this branch: https://github.com/odoo/odoo/compare/master...odoo-dev:master-hr_job-traceback-dbi

**Comment by truongvinhtrinh** [comment] 2015-05-25 03:03
Dear all,
I got the same problem, anyone can fix this?

**Comment by sle-odoo** [comment] 2016-06-13 11:09
Closing as i cannot reproduce with the latest 8.0.
Regards.

**Closed by sle-odoo** 2016-06-13 11:09 UTC
