### ISSUE TITLE
LongPolling virtual memory limit reached

### ISSUE THREAD

**Issue by juan131** [odoo/odoo#19140] opened 2017-08-29 15:43 UTC
# Impacted versions: 

Odoo 10.0 on MacOS Sierra 10.12.6

# Steps to reproduce:

Odoo configured as a WSCGI app using Apache (https://www.odoo.com/documentation/10.0/setup/deploy.html#odoo-as-a-wsgi-application).
LiveChat is configured deploying an evented Odoo via odoo-gevent and proxy requests starting with /longpolling/ to the longpolling port.

Create the Odoo Configuration File using:

```
odoo-bin --save -c /path-to-my-config-directory/odoo-server.conf --stop-after-init --data-dir=/path-to-my-data-directory/ --no-xmlrpc
```

Within the configuration files, these value are generated:
 
```
...
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_request = 8192
...
```

# Current behavior: 

When deploying the evented Odoo:

```
odoo-bin gevent -c  /path-to-my-config-directory/odoo-server.conf --max-cron-thread 0
```

I found the error:

```
2017-08-29 15:13:13,448 64309 WARNING ? odoo.service.server: LongPolling virtual memory limit reached: 2584416256
Terminated: 15
```

Increasing the value `limit_memory_soft` fixes the issue but I don't think that it should require such a big amount of memory.

# Expected behavior: 

Evented Odoo should start (The same steps works on a Debian distro with the same RAM/CPU characteristics)

Why do you think it is reaching that limit and why this is happening to me only on OS-X?

**Comment by Yenthe666** [comment] 2017-09-01 15:15
@sle-odoo could you have a look please?

**Comment by oscarolar** [comment] 2017-09-11 22:35
same case here, same OS, 
It only happens when I enable `workers=4`

**Comment by sle-odoo** [comment] 2017-09-12 06:52
For what it's worth, i'm on osx and i had to configure "limit_memory_soft=25273917440" in my .odoorc, but i can't explain why i chose this value :)

@KangOl any idea why limit_memory_soft needs to be increased for osx and not linux? I believe you stumbled over the same issue.

**Comment by xmo-odoo** [comment] 2017-09-12 07:57
The issue is that OSX pretty reliably allocates (or at least reports) a bit above 2GB of VMEM for *every process* by default — at least for the API psutil uses. htop apparently uses the same API so you can trivially check for it: launch a Python shell (without doing or loading anything in it), open htop, then look for your process.

On my machine the VIRT column gives a value between 2300M and 2400M depending on the actual Python I'm using. On my colleague's Linux machine, htop reports ~31M.

**Comment by juan131** [comment] 2017-09-28 10:54
I just want to mention that increasing those limits worked for me within the last month. But now.. After upgrading to MacOS High Sierra, I found the same problem again. 

@xmo-odoo is there anyway to disable those memory limits on OS-X?

**Comment by xmo-odoo** [comment] 2017-09-28 15:50
@juan131 not currently no.

**Comment by TimLai125** [comment] 2017-11-17 09:44
Hi, @xmo-odoo 
I have the same issue as well. The following line keep appearing in the odoo-server.log 
`odoo.service.server: LongPolling virtual memory limit reached`

This actually affected the longpolling request and caused 502 Gateway Error.
When the limit_memory_soft and limit_memory_hard are set too low, e.g. 201326592 and 402653184 in my case.

As @juan131 mentioned as well, the issue could be solved by increase the limit_memory_soft and limit_memory_hard but I wonder why the Longpolling is such "heavy"? Is there any possibility of memory leak in the process? 

** You can simply reproduce my issue by setting the limit_memory_soft and limit_memory_hard, worker = 1/2. If this does not, you could probably try to access Odoo with 6 users concurrently.

**Comment by xmo-odoo** [comment] 2017-11-17 10:11
> I wonder why the Longpolling is such "heavy"?

It's not, that's not the issue, that has nothing whatsoever to do with the issue.

**Comment by TimLai125** [comment] 2017-11-17 10:15
> It's not, that's not the issue, that has nothing whatsoever to do with the issue.

Do you mean the longpolling is not heavy?
May I know if there is any minimum memory settings for the Longpolling?

**Comment by guewen** [comment] 2017-12-08 12:05
> It's not, that's not the issue, that has nothing whatsoever to do with the issue.

Could you elaborate? We have the same issue in Debian-based Docker images. We need a very high soft limit which kinda make it useless.

**Comment by guewen** [comment] 2017-12-12 15:38
Here's what I mean:
```
root@6dddc642c765:/opt# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
odoo         1  7.9  0.7 323936 118816 ?       Ss   15:35   0:04 /usr/bin/python3 /usr/local/bin/odoo
odoo       136  2.2  0.7 338868 122060 ?       S    15:35   0:01 /usr/bin/python3 /usr/local/bin/odoo
odoo       137  7.6  0.8 361148 142052 ?       S    15:35   0:03 /usr/bin/python3 /usr/local/bin/odoo
odoo       138  2.5  0.7 339956 121032 ?       S    15:35   0:01 /usr/bin/python3 /usr/local/bin/odoo
odoo       139 12.8  0.8 491032 134256 ?       Sl   15:35   0:05 /usr/bin/python3 /usr/local/bin/odoo gevent
odoo       140  0.0  0.6 323936 103984 ?       SN   15:35   0:00 /usr/bin/python3 /usr/local/bin/odoo
root       172  1.0  0.0  19940  3572 ?        Ss   15:36   0:00 bash
root       179  0.0  0.0  38380  3084 ?        R+   15:36   0:00 ps aux
```

Are we forced to use a soft limit above 500MB because of the gevent process?

**Comment by bizzappdev** [comment] 2018-01-06 11:50
I have also the same issue. The following line keeps appearing in the odoo-server.log
virtual memory limit (2155655168) reached. In v9.
I have xmlrpc calls coming from external php side and this memory problem is causing the problem for slowing down the odoo and every call is taking a very long time.
after a restart of odoo service, it gets normal.

**Comment by Yenthe666** [comment] 2018-01-10 09:19
@KangOl and @xmo-odoo any update please?

**Comment by dbo-odoo** [comment] 2018-01-11 10:01
Hello,

As @xmo-odoo explained, there is no memory leak. The problem is simply that OS X allocates ~2Go of VMem by default, and if your soft-memory-limit is lower than that, the worker will be killed automatically and be respawned pretty much after every request. Unfortunately we can't really do anything about it, since this is done by the OS itself. The solution is either to disable resource management altogether or to put the soft-memory-limit higher than that default allocated virtual memory (e.g. 25273917440). Note that this **absolutely does not** mean that your gevented server uses that amount of memory; simply that it was allocated that much and that the resource management in Odoo can't tell the difference. There is **no memory leak** here, or at the very least what you're seeing is not a symptom of a memory leak; which is why, in xmo's words:

> It's not, that's not the issue, that has nothing whatsoever to do with the issue.


@guewen Your problem is not the same, since you're not on OS X. 500Meg is not an extraordinary number; it depends on the number of databases present on the server and the number of modules installed in each (the registry is loaded for each of them) and the number of concurrent requests on the longpolling (if you have 20 users using odoo at the same time, it's 20 greenlets that must all reside in memory). I don't see anything wrong with that number.

Given that it's an OS limitation that is out of our control, I'll close this issue.

Regards,

Damien

**Closed by dbo-odoo** 2018-01-11 10:01 UTC
Labels: 10.0, Framework

**Comment by SalahAdDin** [comment] 2018-06-12 10:00
I used [`768MB`](https://stackoverflow.com/a/35975994/3826549).
