### ISSUE TITLE
Accounting: TypeError: Cannot read property 'id' of undefined     at web.assets_backend.js:1041

### ISSUE THREAD

**Issue by hernelio-long** [odoo/odoo#64748] opened 2021-01-19 14:12 UTC
Impacted versions: 13.0

Steps to reproduce: 

- Create new Bills in the accounting module.
- The error is caused when we want invoice lines.

Uncaught (in promise) TypeError: Cannot read property 'id' of undefined at web.assets_backend.js:1041

Expected behavior:
Be able to edit y add.

Video/Screenshot link (optional):
Line.
![image](https://user-images.githubusercontent.com/61795658/105044528-d4cdfa00-5a34-11eb-8ee1-a07d0e0f7c34.png)

![image](https://user-images.githubusercontent.com/61795658/105044680-0050e480-5a35-11eb-9a7d-ea9ecd79ce3d.png)

![image](https://user-images.githubusercontent.com/61795658/105044740-1494e180-5a35-11eb-8fd7-c4d94d68d2c7.png)

Note:
The error arose after migrating odoo to version 13.

**Comment by pedrobaeza** [comment] 2021-01-19 14:58
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by miguelchuga** [comment] 2021-02-11 00:01
cannot be played in runbot because it is a database migrated from odoo 10 to odoo 13.

I have the same problem, has anyone managed to fix it?

**Comment by pedrobaeza** [comment] 2021-02-11 07:15
Sorry, but that's something out of scope of this issue tracker, and no answer from original author, so closing.

**Closed by pedrobaeza** 2021-02-11 07:15 UTC
Labels: Need information

**Comment by dli-odoo** [comment] 2021-02-11 07:30
@pedrobaeza 

Sorry to comment on the closed issue, but this could be due to the wrong configuration of Debit/Credit account.
The issue is raised because the user may have created purchase journals and have used receivable/payable accounts as a Debit/Credit Account. 

This is not correct.

Can he change the accounts used for that journal(i.e. expense) and try again?

**Comment by miguelchuga** [comment] 2021-02-11 10:46
you're right, that was !!!

**Comment by morphace** [comment] 2021-09-29 13:25
Yes that solved the same issue for us too.
