### ISSUE TITLE
Odoo v12 sale_management blank page

### ISSUE THREAD

**Issue by ralfeus** [odoo/odoo#30085] opened 2019-01-09 18:45 UTC
Impacted versions: 12

Steps to reproduce: Install "sale_management" application

Current behavior: Totally blank screen is shown

Video/Screenshot link (optional): https://prntscr.com/m51ixb

If I run in debug mode with assets (URL: http://odoo.ralfeus.eu/web?debug=assets), then it works fine. If I uninstall "sale_management" module it works fine. If I install it again, the problem returns.

**Comment by pedrobaeza** [comment] 2019-01-09 19:48
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by ralfeus** [comment] 2019-01-10 08:40
It seemed to be some hiccup. After several attempts to install and remove
Sales module and restart the server it suddenly started working again.

**Closed** 2019-01-10 08:43 UTC
Labels: 12.0, Need information, Services
