### ISSUE TITLE
[8.0] Can be Purchased can't be clicked, select image opens instead

### ISSUE THREAD

**Issue by gaqzi** [odoo/odoo#1056] opened 2014-07-10 05:45 UTC
Working with commit b333457ca3f278463f270e4e4655f70e2a658798 and setting up a product I can't uncheck `Can be Purchased`, unless clicking at the very top of the text/checkbox, because it's covered by the `<input type="file">` field for changing the product image. 

Tested using Chrome 35.0.1916.153.

Setting the height/width of the `.oe_form_binary_file` to `1px` still makes it work as expected in Chrome and should also leave it working in IE.

![screenshot 2014-07-10 13 38 35](https://cloud.githubusercontent.com/assets/18167/3534869/9c1bd4b4-07f4-11e4-8952-265de2d8f4f1.png)

**Comment by Yenthe666** [comment] 2016-07-29 14:44
Hi @gaqzi,

Thanks a lot for your report. At this point the issue can no longer be reproduced and everything works fine now.
Closing this because it is no longer reproducable.

Regards,
Yenthe

**Closed by Yenthe666** 2016-07-29 14:44 UTC
