### ISSUE TITLE
[BUG] %%Y-%%m-%%d rendering (in DevMode?)

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#15953] opened 2017-03-21 04:22 UTC
### Impacted versions:
c224df0
### Steps to reproduce:

- Click on any search with a date domain

You can use e.g. in `\addons\stock\views\stock_picking_views.xml` click on `<filter name="late" string="Late" domain="[('min_date','&lt;', time.strftime('%%Y-%%m-%%d %%H:%%M:%%S'))]" help="Pickings that are late on scheduled time"/>`, which means:
- Create any picking that becomes late
- Click on the Stock Panel on the "Late" link

### Current behavior:
`%%Y-%%m-01`, for instance, is rendered to `%2017-%03-01`, which then surprises with a traceback like this, after having been passed on a roundtrip through the client:
```logs
    result = method(recs, *args, **kwargs)
  File "/home/src/odoo-cc/odoo/models.py", line 1923, in read_group
    result = self._read_group_raw(domain, fields, groupby, offset=offset, limit=limit, orderby=orderby, lazy=lazy)
  File "/home/src/odoo-cc/odoo/models.py", line 2013, in _read_group_raw
    self._cr.execute(query, where_clause_params)
  File "/home/src/odoo-cc/odoo/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/home/src/odoo-cc/odoo/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
DataError: invalid input syntax for type timestamp: "%2017-%03-01"
LINE 4: ...RE ("mrp_workcenter_productivity"."date_start" >= '%2017-%03...
```

----------------------------------

I'd have to add, this only happens locally with a recently completely rebuild custom docker stack (on ubuntu). Maybe some library has changed its behaviour? Or has it to do that I run locally with the devmode flag? So that the view arch does not get interpreted from DB, but from file, which then at this point in time is differently handled than from DB-arch, as in the DB-arch remote I find:
```xml
<filter string="Today" name="today" domain="[('date_start','&gt;=',time.strftime('%%Y-%%m-%%d'))]"/>
<filter string="This Month" name="thismonth" domain="[('date_start','&gt;=',time.strftime('%%Y-%%m-01'))]"/>
<filter string="This Year" name="thisyear" domain="[('date_start','&gt;=',time.strftime('%%Y-01-01'))]"/>
```
the same as in the files, but I can remotely imagine that it is piped through different escaping on it's way...

**Comment by mpamped** [comment] 2017-04-06 20:30
I can confirm this with 10.0@428d9e81775dd470df6536ded4c6c56331efd760.

The problem only occurs when dev-mode is enabled (I ran `odoo.py` with `--dev=all`).

**Comment by Yenthe666** [comment] 2018-01-10 15:26
@mart-e perhaps something to check?

**Comment by mart-e** [comment] 2018-01-10 16:14
Indeed, looks like there is an issue when `--dev` option is enabled.
@JKE-be any idea?

**Comment by JKE-be** [comment] 2018-01-10 16:50
@mart-e  know issue

just a missing replace in read xml file... that don't escape the %% into %

%% once in sql will be %
But in dev mode, we read the xml file, so %%

a replace('%%', '%') should fix the problem

**Comment by JKE-be** [comment] 2018-01-10 20:05
Fixed with 8fb203f7c692c0262a579575127b429e858ff3a2

**Closed by JKE-be** 2018-01-10 20:05 UTC
Labels: Framework

**Comment by Yenthe666** [comment] 2018-01-11 06:45
Thanks for the quick responses and fixes guys. @blaggacao this should be fixed now!

**Comment by blaggacao** [comment] 2018-01-13 04:45
Nice there is (was) another one with foreign language formats, but I haven't it tracked down yet...
