### ISSUE TITLE
[13] Impossible to uninstall Discuss App and server error on route /web/become after instaling Discuss

### ISSUE THREAD

**Issue by daniespejel** [odoo/odoo#38144] opened 2019-10-07 20:11 UTC
Impacted versions: 13.0

Steps to reproduce: Install Discuss App on fresh odoo 13community installation, unistall Discuss app error is reproducible on current runbot

Current behavior: become super user is not possible, internal error page is show

Expected behavior: change to super user mode

Video/Screenshot link (optional):
![imagen](https://user-images.githubusercontent.com/14876947/66343828-13a87100-e912-11e9-973d-f92fb1014f08.png)
![imagen](https://user-images.githubusercontent.com/14876947/66343896-3470c680-e912-11e9-961e-c6f01b70309f.png)

traceback for super user server error
2019-10-07 19:53:10,672 10314 INFO odoonew werkzeug: 127.0.0.1 - - [07/Oct/2019 19:53:10] "GET /web/become HTTP/1.1" 500 - 2 0.001 0.017
2019-10-07 19:53:10,702 10314 ERROR odoonew werkzeug: Error on request:
Traceback (most recent call last):
  File "/mnt/e/odoo-dev/envs/odoo13/lib/python3.7/site-packages/werkzeug/serving.py", line 304, in run_wsgi
    execute(self.server.app)
  File "/mnt/e/odoo-dev/envs/odoo13/lib/python3.7/site-packages/werkzeug/serving.py", line 292, in execute
    application_iter = app(environ, start_response)
  File "/mnt/e/odoo-dev/odoo13/odoo/odoo/service/server.py", line 414, in app
    return self.app(e, s)
  File "/mnt/e/odoo-dev/odoo13/odoo/odoo/service/wsgi_server.py", line 142, in application
    return application_unproxied(environ, start_response)
  File "/mnt/e/odoo-dev/odoo13/odoo/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/mnt/e/odoo-dev/odoo13/odoo/odoo/http.py", line 1281, in __call__
    return self.dispatch(environ, start_response)
  File "/mnt/e/odoo-dev/odoo13/odoo/odoo/http.py", line 1251, in __call__
    return self.app(environ, start_wrapped)
  File "/mnt/e/odoo-dev/envs/odoo13/lib/python3.7/site-packages/werkzeug/middleware/shared_data.py", line 220, in __call__
    return self.app(environ, start_response)
  File "/mnt/e/odoo-dev/odoo13/odoo/odoo/http.py", line 1450, in dispatch
    result = ir_http._dispatch()
  File "/mnt/e/odoo-dev/odoo13/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "/mnt/e/odoo-dev/odoo13/odoo/addons/web_editor/models/ir_http.py", line 22, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/mnt/e/odoo-dev/odoo13/odoo/odoo/addons/base/models/ir_http.py", line 233, in _dispatch
    return cls._handle_exception(e)
  File "/mnt/e/odoo-dev/odoo13/odoo/odoo/addons/base/models/ir_http.py", line 201, in _handle_exception
    return request._handle_exception(exception)
  File "/mnt/e/odoo-dev/odoo13/odoo/odoo/http.py", line 744, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/mnt/e/odoo-dev/odoo13/odoo/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/mnt/e/odoo-dev/odoo13/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/mnt/e/odoo-dev/odoo13/odoo/odoo/addons/base/models/ir_http.py", line 229, in _dispatch
    result = request.dispatch()
  File "/mnt/e/odoo-dev/odoo13/odoo/odoo/http.py", line 803, in dispatch
    r = self._call_function(**self.params)
  File "/mnt/e/odoo-dev/odoo13/odoo/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/mnt/e/odoo-dev/odoo13/odoo/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/mnt/e/odoo-dev/odoo13/odoo/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/mnt/e/odoo-dev/odoo13/odoo/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/mnt/e/odoo-dev/odoo13/odoo/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/mnt/e/odoo-dev/odoo13/odoo/addons/web/controllers/main.py", line 843, in switch_to_admin
    return http.local_redirect(self._login_redirect(uid), keep_hash=True)
TypeError: _login_redirect() missing 1 required positional argument: 'redirect' - - -

Traceback for Discuss Uninstall
2019-10-07 19:58:24,029 10801 INFO odoonew odoo.addons.base.models.ir_module: ALLOW access to module.button_uninstall_wizard on ['mail'] to user admin #2 via 127.0.0.1
2019-10-07 19:58:24,034 10801 INFO odoonew werkzeug: 127.0.0.1 - - [07/Oct/2019 19:58:24] "POST /web/dataset/call_button HTTP/1.1" 200 - 4 0.004 0.010
2019-10-07 19:58:24,141 10801 INFO odoonew werkzeug: 127.0.0.1 - - [07/Oct/2019 19:58:24] "POST /web/dataset/call_kw/base.module.uninstall/load_views HTTP/1.1" 200 - 25 0.019 0.033
2019-10-07 19:58:24,179 10801 INFO odoonew werkzeug: 127.0.0.1 - - [07/Oct/2019 19:58:24] "POST /web/dataset/call_kw/base.module.uninstall/default_get HTTP/1.1" 200 - 2 0.002 0.004
2019-10-07 19:58:24,239 10801 WARNING odoonew odoo.http: ('ir.model(<NewId origin=141>,).count', None)
2019-10-07 19:58:24,246 10801 INFO odoonew werkzeug: 127.0.0.1 - - [07/Oct/2019 19:58:24] "POST /web/dataset/call_kw/base.module.uninstall/onchange HTTP/1.1" 200 - 11 0.019 0.022
2019-10-07 19:58:24,320 10801 INFO ? werkzeug: 127.0.0.1 - - [07/Oct/2019 19:58:24] "GET /web/static/src/xml/dialog.xml?debug=1570478304297 HTTP/1.1" 200 - - - -
2019-10-07 19:58:24,327 10801 INFO odoonew werkzeug: 127.0.0.1 - - [07/Oct/2019 19:58:24] "POST /web/dataset/call_kw/ir.module.module/name_get HTTP/1.1" 200 - 2 0.004 0.014
2019-10-07 19:58:24,343 10801 INFO ? werkzeug: 127.0.0.1 - - [07/Oct/2019 19:58:24] "GET /web/static/src/xml/crash_manager.xml?debug=1570478304325 HTTP/1.1" 200 - - - -
2019-10-07 19:58:24,510 10801 INFO odoonew werkzeug: 127.0.0.1 - - [07/Oct/2019 19:58:24] "POST /web/dataset/call_kw/ir.ui.view/check_access_rights HTTP/1.1" 200 - 1 0.000 0.005

**Comment by sswapnesh** [comment] 2019-10-07 20:18
Duplicate of https://github.com/odoo/odoo/issues/25138 (If its only about Uninstallation )

**Comment by sswapnesh** [comment] 2019-10-07 20:29
EDIT: I can confirm 1st Issue

Install `mail` module only --> Become Superuser
```
  File "/home/sswapnesh/WorkSpace/odoo/addons/web/controllers/main.py", line 843, in switch_to_admin
    return http.local_redirect(self._login_redirect(uid), keep_hash=True)
TypeError: _login_redirect() missing 1 required positional argument: 'redirect' - - -
```

**Comment by sswapnesh** [comment] 2019-10-07 20:39
Added Fix at https://github.com/odoo/odoo/pull/38145 to fix the Issue on becoming Superuser.

**Comment by daniespejel** [comment] 2019-10-07 20:42
1st issue disappear after installing website app, you could uninstall website after and server error is not coming back

**Comment by sswapnesh** [comment] 2019-10-07 20:43
Maybe because the portal module is still installed there.

**Closed** 2019-10-08 08:17 UTC
