### ISSUE TITLE
[9.0] Website Visual editor not save if there are a snippet with a svg tag

### ISSUE THREAD

**Issue by dansanti** [odoo/odoo#14485] opened 2016-11-26 03:52 UTC
Impacted versions:
9.0

Steps to reproduce:
1.-  make some snippet for website
2.- add a svg tag like 
`` 
`<section class="snippet_class"> <svg  x="0px" y="0px" width="100%"><defs><linearGradient id="svg-gradient" x1="0%" y1="0%" x2="100%" y2="0%"><stop offset="0%" class="gradient-bottom-color1"></stop><stop offset="50%" class="gradient-bottom-color2"></stop><stop offset="100%" class="gradient-bottom-color1"></stop></linearGradient></defs><path fill="url(#svg-gradient)" d="M1920,27.2c-10.4,1.2-99.6,11.7-259.9,19.2 .............72.2,1920,72.2 V27.2z"></path></svg></section> `
  (reduced svg)
3.- install it
4.- visual edit a page
5.- Add new snippet
6.- Save changes

Current behavior:

 Save not working for this page 

Expected behavior:

Save Page snippet with svg tag

**Comment by celm1990** [comment] 2016-12-06 20:46
Hi,

The problem is JQuery, [https://github.com/jquery/jquery/issues/2199](https://github.com/jquery/jquery/issues/2199)
Solution:

Change this line on file rte.js on module web_editor

[https://github.com/odoo/odoo/blob/9.0/addons/web_editor/static/src/js/rte.js#L367](https://github.com/odoo/odoo/blob/9.0/addons/web_editor/static/src/js/rte.js#L367)

Before

$el.find('[class]').filter(function () {
                    if (!this.**className**.match(/\S/)) {
                        this.removeAttribute("class");
                    }
                });

After

 $el.find('[class]').filter(function () {
                    if (!this.**getAttribute("class")**.match(/\S/)) {
                        this.removeAttribute("class");
                    }
                });


Impacted versions: All

**Comment by dansanti** [comment] 2016-12-07 11:10
yep works fine, changin className by getAttribute("class"), make action save works well.

**Comment by sardylan** [comment] 2017-12-01 11:19
I confirm that the proposed solution works on Odoo version 11.0

**Comment by Yenthe666** [comment] 2017-12-04 09:28
@adr-odoo could you give feedback on this? It has been open for quite a while.

**Comment by adr-odoo** [comment] 2017-12-04 09:46
Hello,

Merged: @e15e6fe
Thanks for the feedback and the fix!

Regards,

**Closed by adr-odoo** 2017-12-04 09:46 UTC
Labels: 9.0, Website
