### ISSUE TITLE
[11.0][11.0] point_of_sale: Barcode nomenclature can't handle coincidences in the sequence

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#19144] opened 2017-08-30 03:02 UTC
### Impacted versions:
All

### Steps to reproduce:
1. Configure a barcode nomenclature for Clients that respect this use case:
    - Barcodes of only 6 digits, sequential and fills with zeroes to the left: Ex.: _004328_ 
2. Use sequence **20** for _Clients_ and sequence **40** for _Products_
3. Use any possible combination with regex accepted by Odoo (as some can't be implemented, like: `^[0-9]{6}$`) to match clients barcode:
    - `.*`
    - `......`
    - `......{NNNNNN}`
    - `0`
    - etc...

### Current behavior:
If any of the previous barcode patterns are used in the Client Sequence, the Clients barcode will work but the products won't be found in the POS by using a barcode scanner from the main screen.

If I invert the sequences 20 for Products and 40 for Clients, the opposite will happen, products will go back to normal and none of the Clients barcode will be found by the scanner.

### Expected behavior:
Even if the pattern is duplicated, let's say:
1. Sequence 20, Clients, `.*`
2. Sequence 40, Products, `.*`

This module should first look for Clients that match the pattern and if none is found then continue with the Products, or vice versa if the sequences are inverted.

**Comment by gustavovalverde** [comment] 2017-08-31 18:14
@Yenthe666, do you know who could shed some light here? It's like a dark subject that I haven't been able to get some real advice on how to deal with it.

**Comment by Yenthe666** [comment] 2017-09-02 12:59
Absolutely @jorenvo or @mart-e for this one.

**Comment by gustavovalverde** [comment] 2017-09-08 13:41
**Ticket 767825**

This one is not being considered as a bug, even though I can't implement a simple use case scenario: 
Sequence 20, **Client** Nomenclature: `{NNNNNN}` <--- new one
Sequence 40, **Product** Nomenclature: `.*` <--- default 

{NNNNNN} should only match 6 digits codes, as I'm being told in the ticket. But this would crash the Products Nomenclature and none of the products would be read by barcode.

**Comment by gustavovalverde** [comment] 2017-09-08 13:44
Just to be clear on what I'm trying to state here:

A lower sequence should be completely isolated from the next ones (higher sequences). There's no reason why `{NNNNNN}` has to collide and crash `.*`

**Comment by gustavovalverde** [comment] 2017-09-14 20:02
A more specific use case which shouldn't collide based on the module actual logic and design:
Sequence 20, **Client** Nomenclature: `{NNNNNN}`
Sequence 40, **Product** Nomenclature: `{NNNNNNN}.*`

**Comment by js-landoo** [comment] 2017-09-15 08:27
Gustavo, you are not using odoo strategy.
If you want this working, you must use prefixed to differ different kind of codes.
For example, for customer, recommended prefix is "042" AND you can't create product codes starting with this one. In this case, nomenclature is not "{NNNNNN}", but "042......" (9 digits)
If you only can use 6 digits, you can try reserving 1 for customer code, for example "2" and yo remain 5 digits for customer code.
Client nomenclature will be "2....." (5 points) and you have 5 digits to code customer.
A customer with code 12345 will have a barcode 212345
Product nomenclature will be ".*" 
Just be careful no product barcode starts with "2", this will not be detected as product.

Regards

**Comment by gustavovalverde** [comment] 2017-09-16 01:04
@js-landoo, trying to modify real world use-cases just to adapt the logic to the actual barcode nomenclature. For example, I can't suggest my client to change their 8,000 employee's ID barcode, because it can't work that way. 

There's even a more general (and worldwide) use case: National IDS. Each country could use their National ID barcode as a Client Barcode, but trying to force a **prefix** would make this idea useless, as they can't add a prefix to the physical ID, as it won't exist in most cases.

What I'm trying to state here, is that adding a prefix is not a solution, as the nomenclature has to be adaptable to the real world, we can't do the inverse (adapt the real world to Odoo).

**Comment by js-landoo** [comment] 2017-09-16 15:33
I don't understand fully your use case, but as you say, international product codification uses prefix with national ID.
This is a standard in barcode world and I think is very logical to implement it in Odoo.
I don't know how other software can differ from product, customer and other types of barcodes without prefix, but i'm sure its not so efficient and powerful.

Although, have you tried this?:
Sequence 20, Client Nomenclature: ...... (6 points)
Sequence 40, Product Nomenclature: .......* (7 points and *)

**Comment by gustavovalverde** [comment] 2018-05-08 21:58
OPW 1767825 closed with:
![image](https://user-images.githubusercontent.com/16890942/39785220-5a8dd490-52e9-11e8-93d7-cb77f7a7c1c2.png)

**Comment by Yenthe666** [comment] 2018-05-09 05:59
Hi @gustavovalverde,

I guess I'll close this one then, since it is confirmed Odoo will not change/implement this in current versions.
As long as they have a backlog task they'll look into it. I hope you understand.

**Closed by Yenthe666** 2018-05-09 05:59 UTC
Labels: Logistics
