### ISSUE TITLE
[FR/RFC] Analytic accounts on POS

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#22886] opened 2018-02-07 13:52 UTC
### Impacted versions:
9.0, 10.0, 11.0, 12?

### Steps to reproduce:
Use analytic accounting for income segregation between branch offices
Use different approaches to meet this goal:
- Setting default analytic accounts to user
- Enforcing the use of analytic account on sales and purchases
- etc.

### Current behavior:
If the POS is the main income channel for a company, there's no way to set analytic accounts for this sales. So the analytic accounts becomes  mainly useless for POS oriented companies. 

### Expected behavior:
Have a way to use analytic accounts on the POS.

**Note**: Adding Pricelists to the POS was a great problem solver, this should be similar or even better.

**Comment by Yenthe666** [comment] 2018-02-07 14:04
@sle-odoo and @qdp-odoo I'm not sure if this should be labeled accounting or logistics. Could one of you have a look and give feedback?

**Comment by qdp-odoo** [comment] 2018-02-07 15:34
more an accounting one...  @lap-odoo it's definitively related to our this-afternoon-discussion, so it could be integrated in the task description as well.

@gustavovalverde thanks for the feedback, we gonna take care of it in a near future. In the meanwhile, as it is not a bug but a missing feature, I'll be closing this issue for the good sake of Clarity

**Closed by qdp-odoo** 2018-02-07 15:34 UTC
Labels: 10.0, 11.0, 9.0, Accounting

**Comment by lap-odoo** [comment] 2018-02-07 15:42
Yep, done !

**Comment by gustavovalverde** [comment] 2018-02-07 15:42
**Side note:** It would be _nice to have_ a place for doing **Feature Requests** with a voting system. I know this kind of stuff makes noise in github, but in the absence of a place, this is the most reliable place to do it.

**Comment by qdp-odoo** [comment] 2018-02-07 15:55
yep, but on the other side if we had some tool to vote for the next features, it would be hard for Laura to give more weight to feedback coming from her preferred partner... hehehe

**Comment by gustavovalverde** [comment] 2018-02-08 13:11
@qdp-odoo you'll make us blush 😄

**Comment by gustavovalverde** [comment] 2018-08-09 11:10
Is this being considered for v12?

**Comment by AliHussJaafar** [comment] 2019-01-03 10:08
Hello guys , any news about this feature ?

**Comment by qdp-odoo** [comment] 2019-01-10 14:10
not yet in the pipe...
