### ISSUE TITLE
Create opportunity from email odoo 9 not working

### ISSUE THREAD

**Issue by user998877** [odoo/odoo#15494] opened 2017-02-14 15:22 UTC
Impacted versions: odoo 9

Steps to reproduce: My domain alias is **myodoosystem.com** in sales team I'm add mail alias **sale**
and in Sale > Settings select option --> Each mail sent to the alias creates a new opportunity.

After send email from etc.  myemail@gmail.com  to sale@myodoosystem.com  opportunity is not created in odoo!

Current behavior:  Not create opportunity!

Expected behavior: Each mail sent to the alias creates a new opportunity

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2018-05-10 09:07
Hi, I'm not able to reproduce this problem in latest code, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-05-10 09:07 UTC
Labels: 9.0, Services
