### ISSUE TITLE
[11.0] [enterprise] TypeError when opening the import statement wizard in the accounting dashboard

### ISSUE THREAD

**Issue by tomeyro** [odoo/odoo#21951] opened 2018-01-01 22:16 UTC
Impacted versions:
- `11.0` (enterprise)

Steps to reproduce:
- Go to the accounting dashboard.
- Select "Import Statement" from a Bank Journal.

Current behavior:
- A TypeError is raised and the wizard is still loaded in the background.

Expected behavior:
- The wizard should pop up without any errors.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/8657959/34471413-9b0dfbba-ef0e-11e7-84f0-a23b9a160b48.png)

**Comment by danger89** [comment] 2018-01-03 13:36
Off-topic but: How can you go fast to the Accounting Dashboard in Odoo v11? When I click on 'Accounting' I go by default directly to 'Customer invoices' (first menu item)...

**Comment by danger89** [comment] 2018-01-03 14:02
Uhmm I just created my own menu item (manually too bad), since I couldn't find it otherwise.

When you enable 'Developing mode', you can go to Settings -> Technical -> Menu items. Create a new menu item.

And fill in your name for the menu, eg; Dashboard. As sub-menu I selected 'Accounting/Reports'. And as action you need to select 'ir.actions.act_window' and search for the action "Accounting Dashboard".

In Dutch:
![image](https://user-images.githubusercontent.com/628926/34523129-6c90dada-f096-11e7-9f1e-ed7ae79d0a1e.png)

**Comment by danger89** [comment] 2018-01-03 14:22
So you only see the Dashboard when you enable 'Technical settings / Show all accounting options'..

**Comment by Yenthe666** [comment] 2018-01-04 07:54
Hi @tomeyro,

Thanks a lot for your bug report.
I've just checked this and I can confirm that this is a bug in the official code.
Since I'm also facing this bug for a customer I've made an official bug report too. Ticket number is 803789

Regards,
Yenthe

**Comment by Yenthe666** [comment] 2018-01-05 07:22
Hi @tomeyro,

The bug has been fixed in the meanwhile (at https://github.com/odoo/enterprise/commit/525ff12c29a1c78d8f9a836888432fe6a7e4f9f2)!
When you update your Odoo instance it'll be working fine.

Regards,
Yenthe

**Closed by Yenthe666** 2018-01-05 07:22 UTC
Labels: 11.0, Accounting, confirmed

**Comment by tomeyro** [comment] 2018-01-05 16:54
Thanks @Yenthe666

**Comment by Yenthe666** [comment] 2018-01-05 18:51
You're welcome!
