### ISSUE TITLE
Search by date is not working in Timesheet records.

### ISSUE THREAD

**Issue by zaoral** [odoo/odoo#28107] opened 2018-10-24 12:48 UTC
### Impacted versions:

11.0

### Steps to reproduce:

1. Go to Timesheets / My Timesheets , select tree view
2. Type date in the search box

### Current behavior:

Not filtering by date. I tried to use different date formats but has not success.

### Expected behavior:

Be able to search timesheet records filtering by date.

### Video/Screenshot link (optional):

https://www.youtube.com/watch?v=pJ0RGrCDtZU&feature=youtu.be

**Comment by Yenthe666** [comment] 2018-10-24 12:54
@zaoral is your Odoo up to date? Can you reproduce it on a runbot?
I've just tried the latest 11.0 and it works fine there: 
https://drive.google.com/file/d/1BZ5-FdJWRuF6mCb3dkuSevBjBi3_O2z7/view

**Comment by zaoral** [comment] 2018-10-24 13:16
Hi @Yenthe666 

Yes, in fact i tested in the same buidl :( I do not understand why I do not work for me.
Build 389112-11-0-2bec22.

Here is a new video showing the runbot build that I am using and I repeat the test case
https://youtu.be/XQ68AKDsj8I

**Comment by Yenthe666** [comment] 2018-10-24 13:38
Okay that is really odd. @mart-e how can it be that we both get different results?

**Comment by pedrobaeza** [comment] 2018-10-24 13:42
Maybe bad configuration of the regional options in the browser of @zaoral?

**Comment by mart-e** [comment] 2018-10-24 13:50
Looks like a timezone issue, indeed. I just tried switching my timezone to Argentina and I got the bug. It matches to 10/24/2018 instead.

**Comment by zaoral** [comment] 2018-10-25 13:15
opw-1903224

**Comment by kebeclibre** [comment] 2018-11-22 13:06
closed in v11.0 with https://github.com/odoo/odoo/commit/ba8bac8f9884bc5d8962e0ba22ed2f4789dd98bf
in v12.0 with https://github.com/odoo/odoo/commit/462681723b63b5cacb943a2b1f40b26cb1355d83

(basically the same, except that in v12 it has become testable)

**Closed by kebeclibre** 2018-11-22 13:06 UTC
Labels: 11.0, Confirmed, Services

**Comment by zaoral** [comment] 2018-11-22 17:04
Excellent! Thank you
