### ISSUE TITLE
ParseError: "new row for relation "res_partner" violates check constraint "res_partner_check_name"

### ISSUE THREAD

**Issue by llonchj** [odoo/odoo#13097] opened 2016-08-09 22:09 UTC
Impacted versions: 9 20160809 daily

Steps to reproduce: create a new db, add crm app

Current behavior: Produces the exception below

Expected behavior: crm application should be installed

```Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 684, in dispatch
    result = self._call_function(*_self.params)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 320, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 313, in checked_call
    result = self.endpoint(_a, *_kw)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 963, in __call__
    return self.method(_args, *_kw)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 513, in response_wrap
    response = f(_args, *_kw)
  File "/usr/lib/python2.7/site-packages/openerp/addons/web/controllers/main.py", line 901, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/site-packages/openerp/addons/web/controllers/main.py", line 889, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/base/module/module.py", line 459, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/base/module/module.py", line 533, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/usr/lib/python2.7/site-packages/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/site-packages/openerp/modules/loading.py", line 338, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python2.7/site-packages/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/site-packages/openerp/modules/loading.py", line 159, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='demo')
  File "/usr/lib/python2.7/site-packages/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python2.7/site-packages/openerp/tools/convert.py", line 851, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python2.7/site-packages/openerp/tools/convert.py", line 938, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/lib/python2.7/site-packages/openerp/tools/convert.py", line 801, in parse
    self.parse(rec, mode)
  File "/usr/lib/python2.7/site-packages/openerp/tools/convert.py", line 804, in parse
    self._tags[rec.tag](self.cr, rec, de, mode=mode)
  File "/usr/lib/python2.7/site-packages/openerp/tools/convert.py", line 708, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/base/ir/ir_model.py", line 1143, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 354, in old_api
    result = method(recs, _args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/base/res/res_partner.py", line 533, in create
    partner = super(res_partner, self).create(vals)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/mail/models/mail_thread.py", line 233, in create
    thread = super(MailThread, self).create(values)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/models.py", line 4157, in create
    record = self.browse(self._create(old_vals))
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, _args, *_old_kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/models.py", line 4301, in _create
    tuple([u[2] for u in updates if len(u) > 2])
  File "/usr/lib/python2.7/site-packages/openerp/sql_db.py", line 141, in wrapper
    return f(self, _args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/sql_db.py", line 220, in execute
    res = self._obj.execute(query, params)
ParseError: "new row for relation "res_partner" violates check constraint "res_partner_check_name"
DETAIL:  Failing row contains (5, null, 1, null, null, 2016-08-09 21:48:43.869555, 0, person, null, null, null, null, null, null, null, null, f, null, null, f, null, null, t, null, null, null, f, null, 2016-08-09 21:48:43.869555, t, null, 1, en_US, 1, null, null, contact, f, null, null, null, null, none, null, f).
" while parsing /usr/lib/python2.7/site-packages/openerp/addons/mail/data/mail_demo.xml:6, near
<record id="base.partner_demo" model="res.partner">
            <field name="notify_email">none</field>
        </record>

```
```

**Comment by JKE-be** [comment] 2016-08-18 23:40
Hi,
Could you retry ? 
I cannot reproduce it with the last version.

**Comment by Yenthe666** [comment] 2018-02-14 08:14
Hi there,

I'm closing this bug report as there has been no feedback in over a year.

Regards,
Yenthe

**Closed by Yenthe666** 2018-02-14 08:14 UTC
