### ISSUE TITLE
can't add new work to task if there's already work for a confirm/done timesheet

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#366] opened 2014-06-06 06:06 UTC
OpenERP version is 6.1.1, with modules hr_timesheet_sheet and project_timesheet.

Steps to reproduce:
1) Create a timesheet for an employee
2) Create a task and log some work, timesheet lines will be created (to have this working I had to apply the patch described in https://bugs.launchpad.net/openobject-addons/+bug/949078 )
3) Submit the timesheet for approval
4) Try to log more work on the task

Observed result: I'm getting an error message that says that a timesheet line cannot be updated if the timesheet is confirm/done.

Expected result: User should be able to add more work and new timesheet lines should be created, not updating the old ones that already belong to a confirm/done timesheet.

Possible fix:
To fix this issue I added this code in file project_timesheet.py, inside write function for class project_work:

            if line_id.sheet_id.state in ['confirm','done']:
                # ignore changes if timesheet is in confirm or done status
                continue

I added the lines inside the "for task" just after the line_id null verification. With this is now working for me.

**Comment by Yenthe666** [comment] 2016-06-13 06:32
Hi @gurneyalex,

I can't reproduce this issue either. I'm closing this since it cannot be reproduced and @pna-odoo also pointed out to the possible fix.
If you can still reproduce this please respond and I'll reopen this issue.

Regards,
Yenthe

**Closed by Yenthe666** 2016-06-13 06:32 UTC
Labels: invalid
