### ISSUE TITLE
Problems error in the sales quotation with pricelist odoo 13

### ISSUE THREAD

**Issue by sngnt** [odoo/odoo#47649] opened 2020-03-16 01:35 UTC
Impacted versions: odoo 13 CE

Steps to reproduce:

Please explain, I get the following error:
1. Create product A for $ 100
![image](https://user-images.githubusercontent.com/5066447/76715675-f351cd80-675f-11ea-9045-7ea3779c3706.png)
2. Create price list with 10% discount
![image](https://user-images.githubusercontent.com/5066447/76715701-0c5a7e80-6760-11ea-8d6a-8a1fc031e413.png)
3. Create a new sales quotation for product A with the generated price list, with the following errors:
- Unit price is zero when no customers have been selected.
![image](https://user-images.githubusercontent.com/5066447/76715717-1a100400-6760-11ea-9729-e7dd12be1139.png)
- After selecting a customer, the unit price is discounted by exactly 10% when selecting product A, but when changing the quantity the unit price changes incorrectly.
![image](https://user-images.githubusercontent.com/5066447/76715726-25fbc600-6760-11ea-9b5c-e523295b1b1b.png)
![image](https://user-images.githubusercontent.com/5066447/76715737-2dbb6a80-6760-11ea-8294-95c7171ab66a.png)

Current behavior:

When changing another price list on the sales quotation, the unit price of products in the quotation is not updated but must re-select each product in the list 

Expected behavior:

It is necessary to add a button to update the entire price details when changing the price list in the sales quotation when selecting different price lists.

-------------------
Thank you everyone!

**Comment by pedrobaeza** [comment] 2020-03-16 07:49
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by sngnt** [comment] 2020-03-16 17:24
Thanks a lot!
------------
After I received the response from @pedrobaeza, I reinstalled a new database, solving the problem of changing unit prices when changing quantities. But I still got some issues:

video: [step-to-step](https://www.youtube.com/watch?v=ZNHQznLJVkU)
-> issue:
1. The price is 0 if the customer name is selected after adding the product to the list.
2. The unit price of the product does not change when choosing to change the price list. The unit price of the product only applies correctly when you select each product in the list.

**Comment by pedrobaeza** [comment] 2020-03-16 18:33
That's something expected, as the prices are not recalculated on both cases where the pricelist changes (from nothing to something, or from one pricelist to another).

Closing as won't fix/expected behavior/missing feature.

**Closed by pedrobaeza** 2020-03-16 18:33 UTC
Labels: Need information

**Comment by jerislav** [comment] 2020-04-22 08:22
By whom is this expected??
By customers or by developers, as it is very strange for end users to select product that has a price, and then the price is 0??
