### ISSUE TITLE
New fields on account.move.line not stored on account.move create

### ISSUE THREAD

**Issue by Sirfanas** [odoo/odoo#43923] opened 2020-01-24 13:19 UTC
## Steps to reproduce
Create a custom module, whose add a fields on account.move.line, add this field in invoice line tree on the invoice form

## Current behavior
The new field isn't save on invoice create, but is well save on a write

## Expected behavior
All fields of the invoice line should be save at create

## Solution track
After some investigation, I saw that the 'invoice_line_ids' is cleared from create's values in [_move_autocomplete_invoice_lines_create](https://github.com/odoo/odoo/blob/13.0/addons/account/models/account_move.py#L1496) if 'line_ids' is present in invoice create's dict.
And in my test (made on odoo's docker image 13.0, digest baf375103c8e) when I log the values passed on create function, I have line_ids in the dict, but my customs fields aren't in the datas, they are present in 'invoice_line_ids'
So as [_move_autocomplete_invoice_lines_create](https://github.com/odoo/odoo/blob/13.0/addons/account/models/account_move.py#L1496) pop 'invoice_line_ids', line_ids is stored without my own fields

**Comment by Sirfanas** [comment] 2020-01-24 13:26
To fix it for now, I actually update 'line_ids' with 'invoice_line_ids' data's, matching lines with the temporary id provided in datas

**Comment by sswapnesh** [comment] 2020-01-26 14:57
Duplicate of https://github.com/odoo/odoo/issues/40915
Have a look at https://github.com/odoo/odoo/issues/40915#issuecomment-574624912

**Comment by pedrobaeza** [comment] 2020-01-26 15:07
Yes, totally, so closing.

**Closed by pedrobaeza** 2020-01-26 15:07 UTC
Labels: 13.0, Accounting
