### ISSUE TITLE
KeyError: 'counterpart_aml_id':     aml_dict['move_line'] = AccountMoveLine.browse(aml_dict['counterpart_aml_id'])

### ISSUE THREAD

**Issue by HafedhRahmani** [odoo/odoo#25403] opened 2018-06-21 17:56 UTC
Impacted versions: 11.0

Steps to reproduce: 
When we try to reconcile payments, from the dashboard accounting
I think it's related to the cache, no specific steps

Video/Screenshot link (optional):
![step01](https://user-images.githubusercontent.com/36736035/41736387-98508f8c-758c-11e8-986a-465788b85d8c.png)
![step02](https://user-images.githubusercontent.com/36736035/41736389-98737a2e-758c-11e8-849c-6db67408b6b4.png)
![image](https://user-images.githubusercontent.com/36736035/41736565-37a1e04a-758d-11e8-96b9-15c6742a5f54.png)

Bug Traceback:

Traceback (most recent call last):
  File "/opt/local/odoo/odoo/community/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/local/odoo/odoo/community/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/local/odoo/odoo/community/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/local/odoo/odoo/community/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/opt/local/odoo/odoo/community/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/local/odoo/odoo/community/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/local/odoo/odoo/community/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/local/odoo/odoo/community/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/opt/local/odoo/odoo/community/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/local/odoo/odoo/community/addons/web/controllers/main.py", line 931, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/local/odoo/odoo/community/addons/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/local/odoo/odoo/community/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/local/odoo/odoo/community/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/local/odoo/odoo/community/addons/account/models/account_bank_statement.py", line 819, in process_reconciliations
    aml_dict['move_line'] = AccountMoveLine.browse(aml_dict['counterpart_aml_id'])
KeyError: 'counterpart_aml_id'

**Comment by pedrobaeza** [comment] 2018-06-21 17:58
This can be due to custom modules in your DB. Please try to reproduce the problem in runbot (http://runbot.odoo.com/runbot - admin/admin), and if you are able to, put here all the detailed steps for reproducing exactly the problem.

**Comment by pedrobaeza** [comment] 2018-07-02 01:19
Closing as there hasn't been an answer.

Feel free to open a new issue if this is still happening, but please include all the detailed steps to reproduce the problem, and better if it can be reproducible in a demo environment like runbot (http://runbot.odoo.com).

**Comment by odony** [comment] 2019-03-15 11:11
This can in fact be explained by the alteration of the mutable RPC parameters that is done [here](https://github.com/odoo/odoo/blob/5aa00c3362674ce41d19ea43c0c722c3c874390f/addons/account/models/account_bank_statement.py#L820). If by any chance the transaction gets rolled back because of a concurrent update, the next replay attempt will use the modified parameters, and you get the `KeyError` described here. Retrying the operation will succeed as soon as no other transaction conflicts again.
Altering mutable RPC parameters is a bit risky in a public RPC method, particularly when those altered parameters will modify the effect of the method. Making a deepcopy of the parameters before using them is an easy workaround. The framework does not do it by default because of the hard-to-foresee memory overhead it would have.

The JS condition mentioned by the OP is not a problem because the same condition is used to filter out invalid entries before passing them to `_formatToProcessReconciliation()` - so the condition is redundant in that case.

Note: the same symptom can still be reproduced in 12.0 with the same root cause, even if the code has moved around a little bit.

/cc @csnauwaert

**Comment by csnauwaert** [comment] 2019-03-15 14:32
A fix has been merged in v11 at https://github.com/odoo/odoo/commit/1834b80bfa2e259b0127d462a84225fab14fe39d

**Closed by csnauwaert** 2019-03-15 14:32 UTC
Labels: 11.0, Accounting
