### ISSUE TITLE
[9.0] Bug on Invoicing wizard on Sale order

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#8471] opened 2015-09-10 09:08 UTC
Hi Odoo,

When I want to created invoice on invoicing wizard on sale order, I found a bug.

Step to product:
1. Set the invoice method based on after delivery on settings for sales apps.
2. Create 2 quotation sale order, confirm it, and delivered the goods, make sure we don't have taxes on it.
3. go to sale order tree, and select/check the 2 sale order that we created, click more>invoice order
4. Click create and view the invoice.
5. the system will said the customer tax field is invalid

![odootest3](https://cloud.githubusercontent.com/assets/7590534/9784576/817b798a-57de-11e5-8335-e2b51910047b.JPG)

**Comment by pedrobaeza** [comment] 2018-04-10 00:35
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-04-10 00:35 UTC
