### ISSUE TITLE
Canceling sales order, remains produrement uncancelled on procurement group

### ISSUE THREAD

**Issue by anajuaristi** [odoo/odoo#3805] opened 2014-11-21 18:10 UTC
Tested in runbot
http://29238-8-0-1e009e.runbot.odoo.com/web 

Go to sales
Create a new one
Select a product, where procurement on record is manufacturing, make to order
Confirm sales order
This creates 2 different procurement on same procurement group (IS CORRECT)
	11/28/2014	Partner Locations/Customers	SO035	iPad Retina Display (32 GB, White, 3,6)	10.000	Unit(s)	Running
	11/28/2014	WH/Stock	SO035:WH: Stock -> Customers MTO	iPad Retina Display (32 GB, White, 3,6)	10.000	Unit(s)	Running

The second one, creates a new manufacturing order for iPad Retina Display (32 GB, White, 3,6) (IS CORRECT)

Now cancel the sales order
You can see that only the first procurement is canceled and the second one remains running. The created manufacturing order still remains waiting raw materials which is INCORRECT

----

Expected behavior shoudl be:
To cancel a sales order should make canceled all related procurements included on it's procurement group

Note: Cancelling a procurement, is cancelling the related MO, so this is also correct.

Thank you!!!
Ana

**Comment by yostashiro** [comment] 2015-03-11 05:33
This is also the case with Request for Quotation generated from 'Make To Order' setting.  When SO is cancelled, associated Request for Quotation should also be cancelled.

**Comment by clonedagain** [comment] 2015-03-12 08:15
That's a problem for me too, so I've just asked Odoo paid support to get in charge of fixing this.

**Comment by jco-odoo** [comment] 2015-03-13 14:44
So, you would allow to cancel a sale order with a delivery order in the way that it cancels automatically all steps then?  (unless you would not have the propagate_cancel)

**Comment by clonedagain** [comment] 2015-03-13 15:15
@jco-odoo I think it's OK that users have to cancel the delivery before they can cancel the SO. We can always make a module to do it automatically it we see fit.
However the problem is that once the delivery is canceled by hand, and the SO is canceled too, the procurements that were created to reserve/acquire the products for the delivery are still running.
We expect them to be canceled since the delivery and the SO are canceled.

**Comment by jco-odoo** [comment] 2015-03-13 15:44
You could cancel the picking from stock > ... immediately of course also, but if it created e.g. a manufacturing order this is problematic also. The rule is that cancelling pickings, cancels in the forward direction (towards customer), cancelling the procurements cancels in the backwards direction.  So, maybe the simplest solution is still to allow the cancelling when there is a delivery order and to simply cancel the procurements.

**Comment by clonedagain** [comment] 2015-03-13 15:52
Fine.

**Comment by aliomattux** [comment] 2015-03-13 15:58
just to be clear are you suggesting that users cancel the procurements manually?

**Comment by jco-odoo** [comment] 2015-03-13 16:03
Automatically.  It would be a little bit unhandy to do it otherwise.

**Comment by nim-odoo** [comment] 2015-03-18 07:45
The fix has been committed in branch 8.0

**Closed by nim-odoo** 2015-03-18 07:45 UTC

**Comment by anajuaristi** [comment] 2015-03-18 08:54
THANK YOU for commiting the fix 
:+1:

**Comment by pedrobaeza** [comment] 2015-03-18 09:01
Can you point us to the commit that solves it?

**Comment by jco-odoo** [comment] 2015-03-18 09:03
Not in the PR?  Commit 3d05ddab50c83fdcc9d638800f8d4c164c66c089

**Comment by nim-odoo** [comment] 2015-03-18 09:03
Here is the commit: https://github.com/odoo/odoo/commit/3d05ddab50c83fdcc9d638800f8d4c164c66c089

**Comment by pedrobaeza** [comment] 2015-03-18 18:52
Thanks, very useful!

**Comment by spadae22** [comment] 2015-03-20 06:01
Yes!

**Comment by pedrobaeza** [comment] 2015-03-20 08:06
Thanks!

**Comment by marvinxue** [comment] 2017-12-17 11:13
How about the PO? will also be cancelled automatically?
