### ISSUE TITLE
Using a function loop in email templates in a table structure

### ISSUE THREAD

**Issue by fmq-angel** [odoo/odoo#47860] opened 2020-03-18 04:01 UTC
When trying to use a for loop (${loop.cycle}) in email templates in a table structure the function loop failed to be rendered template
Impacted versions:
13.0
Sass 13.0
runbot

Steps to reproduce:
1. Confirm sale order from website.
2. Processing payment.
3. Failed to render template.
4. Add the following code snippet from email template (Sales Order: Confirmation Email)
`<tr style="**${loop.cycle('background-color:#f2f2f2', 'background-color: #ffffff')**}"><td colspan="4"><strong>${line.name}</strong></td><td colspan="4"><i>${line.name}</i></td><td style="width:150px;">
                                    <img src="/web/image/product.product/${line.product_id.id}/image_128" style="width:64px;height: 64px; object-fit: contain;" alt="Product image">
                                </td>
                                <td align="left">${line.product_id.name}</td>
                                <td>${line.product_uom_qty}</td><td align="right">${format_amount(line.price_reduce_taxexcl, object.currency_id)}</td><td align="right">${format_amount(line.price_reduce_taxinc, object.currency_id)}</td></tr>`

Current behavior:
the code part is rendered in this way which leads to an error in the log because "loop" is not defined in "${loop.cycle('background-color:#f2f2f2', 'background-color: #ffffff')}" and if you try to delete it shows another error with the line variable and says that it doesn't exist

Expected behavior:
Template rendered.

Video/Screenshot link (optional):
![imagen](https://user-images.githubusercontent.com/49037343/76924273-6f046500-689b-11ea-8081-26505013894d.png)

**Comment by pedrobaeza** [comment] 2020-03-18 06:50
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2020-03-18 06:50 UTC
