### ISSUE TITLE
"No rule matching this procurement"

### ISSUE THREAD

**Issue by Ayhamhafez** [odoo/odoo#10294] opened 2016-01-05 08:42 UTC
After creating procurement rule and define the minimum stock, after making compute stock minimum and run the scheduler I got the right procurement but when make run procurement, no PO automatically created and I got log that say "No rule matching this procurement"

I think it's a bug since it was work before couple of months.

**Comment by lap-odoo** [comment] 2018-02-21 15:38
@Ayhamhafez I cannot reproduce your issue. We would need more detailed steps to be able to help you. I'm closing your issue. If you can provide detailed steps to reproduce your issue I'll reopen. Thanks for your understanding.

**Closed by lap-odoo** 2018-02-21 15:38 UTC
Labels: 9.0, Logistics
