### ISSUE TITLE
[POS V12] Price should be fixed when changing the fiscal position

### ISSUE THREAD

**Issue by tglukhov** [odoo/odoo#34604] opened 2019-07-05 00:15 UTC
Hello everybody, I faced this issue, tried on runbot v10, V11, v12, its the same
Can somebody help me please? 

Impacted versions:
12, 11, 10

Steps to reproduce:
Configure 2 taxes:	
- VAT 13% (percentage of price = 13, included in price,  set tax scope on sales) 
- VAT 5% (percentage of price = 5, included in price, set tax scopes on sales) 

Configure fiscal positions : 
- "On site" -> do nothing, just create. 
- "Take Away" -> tax on product - VAT 13%, tax to apply -  VAT 5% 

Create an article Hamburger : 
price = 1000 $ (tax included), 
customer tax = VAT 13% 

On the POS configurations:	
- add  both fiscal positions on Fiscal position per order, 
- set the default fiscal position to "On site", 
- in Product price, set Tax-Included Price 

Connect you to the POS, select the Hamburger and change taxes from "On site" to "Take Away". 

Current behavior:
with the taxes "on site" the price is right (1000 $) tax amount is 115,04 $,
while changing the tax to "Take away", the price is changed to 884.96 $ with a tax amount 42,14 $ 

Expected behavior:
The price is fixed (1000 $) and the amount of tax should change
with tax set on "On site", price is 1000$,(tax = 115$, price without tax = 885 $) 
with tax set on "Take away" price must be fixed also to 1000$, (tax = 48 $, price without tax = 952 $)

**Comment by pedrobaeza** [comment] 2019-07-05 08:13
@switch87 what do you think about this?

**Comment by vincentius** [comment] 2019-08-12 15:21
We are experiencing the same issue here: #35605

**Comment by switch87** [comment] 2019-08-12 15:36
@tglukhov I will have to look into this, but I can already say that your expected behaviour is wrong. the price exclusive tax is not supposed to change if you change the tax on the product. If you put a price inclusive tax on a product it is inclusive the given tax, here 13%.

For instance, In Europe if you have a VAT number you can buy tax-free cross-borders to make the accounting easier. So if I go to a Dutch store where they have a product 1220% tax inclusive, the price tax exclusive will be 1000 Euro’s with a tax of 22%. If I show them my VAT number they will put me on a fiscal position European sales with 0% tax. So I expect to pay 1000 Euro. With your expected behaviour I would still pay 1220 Euro and I will not be able to get these 220 Euro back because there is 0% tax. I would never go to this store again ;)

**Comment by tglukhov** [comment] 2019-08-12 20:09
@switch87  maybe i was not clear in my explanations, 
We need to have the same price (with taxes icluded) even if we change fiscal position. 

Take a look here, it is the same issue in V10&V11 :
https://github.com/odoo/odoo/issues/18181

And btw here is the solution :
https://github.com/odoo/odoo/pull/21011
It should be the same solution for V12, because v12 code in "account/model/account.py" is the same as in v11.

**Comment by cvinh** [comment] 2019-08-13 01:03
@tglukhov thanks for pointing my 2 PR in v10&v11
The problems are still present in v12.
You can close this issue and have further discussion in the PR respectively

**Comment by switch87** [comment] 2019-08-13 11:26
@tglukhov @cvinh I double-checked on this issue and the current behaviour is how it is supposed to be. For instance for the example I gave as a very common use case it is impossible to make it act like you propose. 

- Fiscal positions are not allowed to influence the product price. Here, the product price is the price exclusive tax, no matter the configuration of how it should be shown. 
- To get the behaviour you want you should work with a pricelist "On site" and "Take out" the set the price with different tax.

**Closed by switch87** 2019-08-13 11:26 UTC
Labels: 12.0, Point of Sale

**Comment by cvinh** [comment] 2019-08-14 19:02
@switch87 yes @tglukhov mixed the two concepts of price and fiscal position. The description in this issue is not clear and leads to confusion.
The issue is well described and fixed in https://github.com/odoo/odoo/pull/17865

**Comment by cvinh** [comment] 2019-08-14 19:15
@switch87 in our case we don't want the 'price including tax' to change (in our country, B2C always want the price including tax). If we want it to change we use a pricelist and it works very well.
The 'price without tax' should change indeed because the tax changes.
BTW let's have further discussion in the PR if needed
