### ISSUE TITLE
[14.0] product.template /  website_only_description is not cleared / editable

### ISSUE THREAD

**Issue by rmeekers** [odoo/odoo#72726] opened 2021-06-24 14:15 UTC
**Impacted versions:**
14

**Steps to reproduce:**

1. Create a product
2. Create a Quotation template and add the product
3. Go to the website builder and add some description to the product and Save
4. Delete the Quotation template
5. Create a Quotation and add the product
6. Go the the _Customer preview_ and notice that the website builder description is still present

**Current behavior:**
Website description is retained after the Quotation template is deleted. In order to remove the website description, you have to create a new Quotation template with that product.

**Expected behavior:**

One of these on product level:

1. Add the field _website_only_description_ by default the a product form so that the description can be managed
2. Clear the field _website_only_description_ once there is no Quotation template anymore for that product

**Comment by pedrobaeza** [comment] 2021-06-24 16:07
This is because the field is translatable, and you should put something (like an space) for avoiding to use the fallback text (or remove the source term).

Closing as expected behavior.

**Closed by pedrobaeza** 2021-06-24 16:07 UTC

**Comment by rmeekers** [comment] 2021-06-24 20:27
This field is not editable anywhere. It's only accessible via the Quotation template by adding the product and then via the website builder. 
So this isn't expected behaviour; it's a bug
