### ISSUE TITLE
Odoo 12 - No Email Alias settings in Multiple company setup 

### ISSUE THREAD

**Issue by netronuk** [odoo/odoo#27951] opened 2018-10-18 15:26 UTC
Impacted versions: Odoo 12

Steps to reproduce: Two companies created in Odoo 12. Domain/email Alias settings applies both companies. Cant add new domain name to second company.

Current behavior:

Expected behavior: I should be able add domain/email alias on both companies to receive email for each company.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2018-10-18 19:04
This is done this way by design/restriction, so this can't be considered an issue, but the current behavior. You should develop an extension for supporting that or look for an existing one. This might change in future versions, but not in stable ones.

Closing due to these reasons.

**Closed by pedrobaeza** 2018-10-18 19:04 UTC
