### ISSUE TITLE
[hr_payroll]: Print menu not visible for PDF reports in list and form view #124745

### ISSUE THREAD

**Issue by hareshkansara** [odoo/odoo#126578] opened 2023-06-27 15:35 UTC
Impacted versions: Odoo enterprise version 16

Steps to reproduce: Install module hr_payroll (Payroll) and go to Payroll > Payslips > All Payslips, go to list view and select records, now you cant see print menu to print PDF reports from list view.

Current behavior: Not able to see print menu in list and form view to print base PDF report and custom PDF reports

Expected behavior: Print menu must always visible on list and form if any reports available for print

Video/Screenshot link (optional):

https://www.awesomescreenshot.com/video/18260858?key=6948563af28cabd1c499cca1ed9e1f13

Support ticket number submitted via odoo.com/help (optional):

NOTE: I have tested everywhere in runbot,localhost,odoo.sh etc with and without demo data and without any custom addons. I have double checked with latest code and i am sure that its due to som bug in odoo enterprise code.

**Comment by hareshkansara** [comment] 2023-06-27 15:36
Hello,

Thanks for your explanation. But what actually i posted is, when we add any new custom reports then it must show print menu near action menu. But its not showing.

And the print button added near refund/new is only able to print 1 default report.

So whats the solution if added new PDF reports for payslip and want to print?

**Comment by hareshkansara** [comment] 2023-06-27 15:36
@kba-odoo so can you reopen this issue plz and discuss more.

**Comment by hareshkansara** [comment] 2023-06-27 15:36
https://github.com/odoo/odoo/issues/124745

**Comment by william-andre** [comment] 2023-06-28 10:44
Duplicate of https://github.com/odoo/odoo/issues/124745

Please don't open the same issue multiple times, it will just scatter the information.
Continue the topic on the same issue instead.

**Closed by william-andre** 2023-06-28 10:44 UTC
