### ISSUE TITLE
E/ConnectorClient: ERROR:      **** Session expired ****

### ISSUE THREAD

**Issue by cviacmob** [odoo/odoo#41442] opened 2019-12-06 07:32 UTC
i run the backround run process to table but some time getting this error odoo mobile integeration. 
 @Override
    public boolean onStartJob(JobParameters job) {
        AmtPref.init(this);
        client = new OdooClient.Builder(this)
                .setHost(ServiceConstants.BASE_URL)
                .setSession(AmtPref.getInstance().getSessionId())
                .build();

        Thread thread = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    loadSectionMaster();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
        thread.start();

        AmtLog.d("JOB", "RUNNNING");
        return false;
    }

    @Override
    public boolean onStopJob(JobParameters job) {
        return false;
    }

    public ReminderService getThis() {
        return mReminderService;
    }

    public void loadSectionMaster() {
        try {
            if (null != AmtPref.getInstance().getLastSyncDateSection() && !AmtPref.getInstance().getLastSyncDateSection().isEmpty()) {
                ODomain mWeb = new ODomain();
                Log.e("lastdatesyn",":"+AmtPref.getInstance().getLastSyncDateSection());
                mWeb.add("write_date", ">=", AmtPref.getInstance().getLastSyncDateSection());
                OdooFields fields = new OdooFields();
                fields.addAll("name", "address", "division_id", "section_user_id", "cane_categ_id", "is_own_plant", "id");
                int offset = 0;
                final int limit = 200;
                client.searchRead("section.master", mWeb, fields, offset, limit, "", new IOdooResponse() {
                    @Override
                    public void onResult(OdooResult result) {
                        OdooRecord[] records = result.getRecords();
                        AmtPref.getInstance().writeString(Keys.LAST_SYNC_DATE_SECTION, AppUtils.getCurrentDateSync());
                        AmtPref.getInstance().writeString(Keys.LAST_SYNC_DATE_SHOWING, AppUtils.getCurrentTime());
                        for (OdooRecord record : records) {
                            if (null == DatabaseUtils.getSectionData(record.getString("id"))) {
                                SectionMasterActiveDB masterDb = new SectionMasterActiveDB(record.getString("name"), record.getString("address"), record.getString("division_id"), record.getString("section_user_id"), record.getString("cane_categ_id"), record.getString("is_own_plant"), record.getString("id"));
                                masterDb.save();
                            } else {
                                Update.table(SectionMasterActiveDB.class).set("Name=?,Address=?", record.getString("name"), record.getString("address")).where("ownPlant = ?", record.getString("id")).execute();
                            }
                        }
                    }
                });
            }
        } catch (NegativeArraySizeException e) {
            AmtLog.e("JOB", e.getMessage(), e);
        }
    }

**Comment by pedrobaeza** [comment] 2019-12-18 18:17
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2019-12-18 18:17 UTC
