### ISSUE TITLE
[12.0] company_id on Vendor Bill Invoice Line not set in Multi-Company

### ISSUE THREAD

**Issue by osi-scampbell** [odoo/odoo#43314] opened 2020-01-14 23:25 UTC
Impacted versions: 
12.0

Steps to reproduce:
Install account_accountant
Enable Multi-Company environment
Remove editable="bottom" on invoice_line_ids
Attempt to add an invoice line

Current behavior:
Notice the company_id is not set, this does not allow the user to change the account_id because of the domain set on the field. If you save the invoice line then re-open it, company_id will be set.

Expected behavior:
company_id is a related field and should be set when the form view is first opened, that way the user can change the account_id if necessary.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/39602586/72391407-44a2f980-36ea-11ea-8440-a29c840489cb.png)

**Comment by william-andre** [comment] 2020-01-15 11:55
You could add `'default_company_id': company_id` in the context key of `invoice_line_ids`
This is not a bug, so I'm closing this.

**Closed by william-andre** 2020-01-15 11:55 UTC
Labels: 12.0, Accounting
