### ISSUE TITLE
[BUG]Some modules are not loaded, some dependencies or manifest may be missing: ['sale_async_emails']

### ISSUE THREAD

**Issue by lingjiawen** [odoo/odoo#162146] opened 2024-04-17 01:10 UTC
Impacted versions: 17

Steps to reproduce: use odoo.sh upgrade to 17

Current behavior:
<img width="1016" alt="image" src="https://github.com/odoo/odoo/assets/26227995/5cc3e3e0-9c70-47fc-8c2f-935082f3dc48">

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by uncannycs** [comment] 2024-04-18 04:30
Hi I am getting the same issue while upgrading database from v16 to v17

**Comment by akloptim** [comment] 2024-04-18 08:08
I am also getting the same issue while upgrading database from v15 to v17

**Comment by vava-odoo** [comment] 2024-04-18 08:45
Hi @lingjiawen 
The module was added 3 days ago, so there is probably a mismatch between the version in upgrade platform and yours.
A pull of the repository should solve this.
Cheers

**Comment by gdenvy** [comment] 2024-04-18 09:34
Hi @vava-odoo ,

On the upgrade platform, we may only choose 17.0 and it gets from Latest revision. We have no option or chance to revert to an older revision

**Comment by vava-odoo** [comment] 2024-04-18 09:38
@gdenvy yes of course, but you can update your local source, can't you?

**Comment by gdenvy** [comment] 2024-04-18 09:39
Yes, we can update our local source. But we can't if we are running the upgrade on Odoo.sh.

**Comment by uncannycs** [comment] 2024-04-18 11:10
Hi @vava-odoo 
You mean to say we have to copy the odoo module and put it in our repository ?

**Comment by sst-smart** [comment] 2024-04-18 11:26
Hello Guys,
![scrnli_4_18_2024_1-25-37 PM](https://github.com/odoo/odoo/assets/79058136/22c97913-dd2d-4ee4-b31e-c222d1d34797)

I have the same problem so I download the module and upload it again in my repository then commit and it's working now,
regards,

**Comment by floflock** [comment] 2024-04-18 20:22
@vava-odoo I have the same problem as described when upgrading production on odoo.sh.

What do you mean by waiting for next Monday, is there a fix on odoo/odoo.sh end?

Thanks.

**Comment by lingjiawen** [comment] 2024-04-19 02:06
Hello, all. I have already upgraded. My temporary solution is to add a migration script to any custom module and cancel the installation of sale_async_emails in the database.If any help.
<img width="1454" alt="image" src="https://github.com/odoo/odoo/assets/26227995/6edde2f1-67dc-4423-ac89-57f7253591f6">

**Comment by vava-odoo** [comment] 2024-04-19 07:29
Hi @floflock 
Yes there are solutions, like the one suggested by @lingjiawen (remove the module from ir_module_module table) for example.
I just said there was a merge of a new module in stable, which can lead to such issues, and that the best would be to abort the migration and/or open an official ticket.
Cheers

**Comment by sst-smart** [comment] 2024-04-19 08:07
@floflock @gdenvy @lingjiawen @akloptim 
Hello,
The problem is solved now, you can check.
Regards,
Mohamed

**Comment by floflock** [comment] 2024-04-19 11:36
@sst-smart I tried, but with no luck.
![Screenshot-2024-04-19 at 13 35 44](https://github.com/odoo/odoo/assets/3831745/c09a7441-2ed4-406b-b184-be00a91d220a)

**Comment by Yenthe666** [comment] 2024-04-20 09:51
Also facing this one. As Odoo.sh updates on sunday typically we will wait until monday and re-evaluate.

**Comment by floflock** [comment] 2024-04-20 14:14
I migrated to 17.0 this morning with the hack showed by @lingjiawen.

I added the following migration script to one of my custom modules:

```
import logging

_logger = logging.getLogger(__name__)


def migrate(cr, version):
    _logger.info('Start script for deactivating sale_async_emails')
    _logger.info(f'Version: {version}')
    cr.execute("DELETE FROM ir_module_module WHERE name ILIKE 'sale_async_emails'")
    _logger.info('Stop script for deactivating sale_async_emails')

```

Docs to upgrade scripts:
https://www.odoo.com/documentation/17.0/developer/reference/upgrades/upgrade_scripts.html

**Comment by moneebalalfi** [comment] 2024-04-20 15:00
Hi @floflock 
Where you did put the migration file
and can you please give me the naming convention of the folder/files (screenshot or something).
Thanks!

**Comment by floflock** [comment] 2024-04-20 15:04
@moneebalalfi take one of your modules and create the following structure.

Important: The folder `17.0.1.0` is named the following: 17.0 is the odoo version, 1.0 is the module version. If your module does have another version than 1.0, please name it differently. It needs to be a higher version than before as well.

![Screenshot-2024-04-20 at 17 02 15@2x](https://github.com/odoo/odoo/assets/3831745/9c3d972f-fa65-46f2-9184-226d873955d4)

**Comment by Yenthe666** [comment] 2024-04-21 09:20
Since Odoo it's upgrade platform is fully shielded off & you have no clue what happens on their side I'd rather not write workaround scripts/hooks. You don't really know which other triggers you might be bypassing/not using due to deleting a module from the list they handle 😄

**Comment by floflock** [comment] 2024-04-22 07:41
> Since Odoo it's upgrade platform is fully shielded off & you have no clue what happens on their side I'd rather not write workaround scripts/hooks. You don't really know which other triggers you might be bypassing/not using due to deleting a module from the list they handle 😄

@Yenthe666 no worries, it is in the open source version of Odoo, not in the enterprise.

**Comment by floflock** [comment] 2024-04-22 07:44
> I migrated to 17.0 this morning with the hack showed by @lingjiawen.
> 
> I added the following migration script to one of my custom modules:
> 
> ```python
> import logging
> 
> _logger = logging.getLogger(__name__)
> 
> 
> def migrate(cr, version):
>     _logger.info('Start script for deactivating sale_async_emails')
>     _logger.info(f'Version: {version}')
>     cr.execute("DELETE FROM ir_module_module WHERE name ILIKE 'sale_async_emails'")
>     _logger.info('Stop script for deactivating sale_async_emails')
> ```
> 
> Docs to upgrade scripts: https://www.odoo.com/documentation/17.0/developer/reference/upgrades/upgrade_scripts.html

There is an addition DELETE necessary, otherwise the module `sale_async_emails` after migration:

`DELETE FROM public.ir_model_data WHERE name='module_sale_async_emails'`

You can place it in the migration script if not yet executed:

```
import logging

_logger = logging.getLogger(__name__)


def migrate(cr, version):
    _logger.info('Start script for deactivating sale_async_emails')
    _logger.info(f'Version: {version}')
    cr.execute("DELETE FROM ir_module_module WHERE name ILIKE 'sale_async_emails'")
    cr.execute("DELETE FROM public.ir_model_data WHERE name='module_sale_async_emails'")
    _logger.info('Stop script for deactivating sale_async_emails')
```

**Comment by guilindner** [comment] 2024-04-24 01:04
Weekly update fixed it, I successfully migrated to 17 without any tweaks

**Comment by Yenthe666** [comment] 2024-04-24 05:37
Yep, same here :) Let's close it.

**Closed by Yenthe666** 2024-04-24 05:37 UTC
