### ISSUE TITLE
[9.0, 10.0, 11.0] Account Bank Statement Reconcile is not multi-company aware

### ISSUE THREAD

**Issue by ivantodorovich** [odoo/odoo#26768] opened 2018-09-04 14:23 UTC
**Impacted versions:**
9.0, 10.0, 11.0

**Steps to reproduce:**

1. Create a company 'A', and company 'B'; Set company 'A' to be parent of company 'B'.
2. Set your user company to company 'A'.
3. Create a bank journal on company 'B'.
4. Import a bank statement and try to reconcile.

**Current behavior:**
The reconcile interface shows a message saying there are no lines to reconcile.
It will only work if you set your user's company to be the same as of the journal (company 'B').

**Expected behavior:**
It should let you reconcile, even if you are not logged in the same company.

-----

The issue is that several lines of `account.bank.statement` use `self.env.user.company_id.id` when it should be using `self.journal_id.company_id.id` or `self.company_id.id` instead.

https://github.com/odoo/odoo/blob/11.0/addons/account/models/account_bank_statement.py#L292
https://github.com/odoo/odoo/blob/11.0/addons/account/models/account_bank_statement.py#L320
https://github.com/odoo/odoo/blob/11.0/addons/account/models/account_bank_statement.py#L630
https://github.com/odoo/odoo/blob/11.0/addons/account/models/account_bank_statement.py#L681

**Comment by pedrobaeza** [comment] 2018-09-04 15:29
@ivantodorovich The problem is that your multi-company concept is not the one that Odoo takes. That's going to happen not only on that part, but across entire Odoo.

As it's conceived, Odoo can handle only one company each time. It doesn't serve parent and child companies nor using admin for it.

It would be great to have this correctly working, but there are a lot of changes to do, not only on this. There have been some initiatives for changing this, like https://github.com/odoo/odoo/pull/21219, but it requires a lot of work.

Closing this as won't fix. If you have a simple patch for avoiding in this exact case, maybe Odoo can admit it, but this won't be fixed by their part as being part of their design decision.

**Closed by pedrobaeza** 2018-09-04 15:29 UTC
Labels: 10.0, 11.0, 9.0, Accounting

**Comment by ivantodorovich** [comment] 2018-09-04 22:48
Thanks for the explaination @pedrobaeza.

Indeed a simple patch would be, as suggested, taking the `company.id` from the journal instead of `self.env.user`. It would require to change ~4 lines of code.

I'll take your advice and send a PR.
