### ISSUE TITLE
cohort view is invalid

### ISSUE THREAD

**Issue by HGHULFG1** [odoo/odoo#36998] opened 2019-09-17 11:14 UTC
Impacted versions: 12

Steps to reproduce:
`<odoo>
<record id="view_cohort_cohort" model="ir.ui.view">                                
  <field name="name">cohort.example.cohort</field>                                
  <field name="model">model_a</field>                                
  <field name="arch" type="xml">                                    
    <cohort string="Cohort records" date_start="date" date_stop="date_stop"></cohort>                                
  </field>                            
</record>

</odoo>`

Current behavior: invalid view type "cohort"

Expected behavior: open a cohort view
![Screenshot from 2019-09-17 14-13-37](https://user-images.githubusercontent.com/32647031/65036979-61eed380-d955-11e9-83c3-962df1a1d7bf.png)

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2019-09-17 11:18
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2019-09-17 11:18 UTC

**Comment by HGHULFG1** [comment] 2019-09-17 11:41
Dear Pedrobaeza, 
I just created a simple cohort view as you can see in above in the code,
"""
<odoo>
<record id="view_cohort_cohort" model="ir.ui.view">                                
  <field name="name">cohort.example.cohort</field>                                
  <field name="model">model_b</field>                                
  <field name="type">cohort</field>                                
  <field name="arch" type="xml">                                  
    <cohort string="Cohort records" date_start="date" date_stop="date_stop">
    </cohort>                            
  </field>                            
</record>

</odoo>
"""
 and the system returns (invalid view type) as you can see, when I create the cohort (with the same values) from inside the system it works fine, I am sure this is an odoo error,
