### ISSUE TITLE
[9.0c][video include] purchase.view_picking_in_search_picking_inherit > Invalid field u'reception_to_invoice'

### ISSUE THREAD

**Issue by eneldoserrata** [odoo/odoo#10266] opened 2016-01-02 06:52 UTC
This search view reference to Invalid field u'reception_to_invoice

![picking_filter_exeption](https://cloud.githubusercontent.com/assets/360270/12073586/c06ea5ce-b0fb-11e5-87ff-f83136d0b2aa.gif)

**Comment by Yenthe666** [comment] 2016-06-15 10:22
Hi @eneldoserrata,

Thanks a lot for the report and for the video, that is very handy.
I can't reproduce this issue anymore on the latest code so this is fixed in the meanwhile.

Regards,
Yenthe

**Closed by Yenthe666** 2016-06-15 10:22 UTC
