### ISSUE TITLE
[9.0] Some modules could not be started JS Issue?

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#9297] opened 2015-10-29 06:17 UTC
Hi Odoo,

Everytime I created a new database, there's an error message on browser console.
Here is the error message:

warning: Some modules could not be started 
Non loaded modules:      ["mail.chat_client_action", "mail.Chatter", "mail_tip.mail_tip"] 
Debug:                   Object {mail.chat_client_action: Object, mail.ChatComposer: Object, mail.Chatter: Object, mail.systray: Object, mail.window_manager: Object…}

The behavior is the same on runbot.
I am using google chrome to test it.

The expected behavior:
Should be no error at all.

Thank You.

**Comment by fshahy** [comment] 2016-01-21 20:40
Same problem here. Have you found the solution?

**Comment by jas-odoo** [comment] 2016-01-28 05:24
Same problem arise for me as I install  8.0 module in 9.0 version.As there is lot of changes in js structure in 8.0 & 9.0.

Removing module may solve the problem.

**Comment by yostashiro** [comment] 2016-03-06 10:42
I was getting a similar error with a new database when I created a dump of an existing database and restored it into the new database.  The problem was solved when I copied the filestore directory of the existing database to the directory for the new database.  I'm not sure about the technical implication, though.

**Comment by vdittgen** [comment] 2016-09-26 19:21
+1

**Comment by bimajatiwijaya** [comment] 2016-11-06 07:56
i was getting a similier error but when upgrade all modules.

in log message i got :
 Invalidating all model caches after database signaling.
and on browser got this :

![image](https://cloud.githubusercontent.com/assets/7659863/20036135/28b46c62-a431-11e6-966e-956ce966533d.png)

**Comment by mikeross6233m** [comment] 2017-01-17 09:00
How to solve this???

**Comment by Pradav** [comment] 2017-02-01 11:40
I get the same problem , i see there is a lot of people having this same issue but there is no answers 
error: Some modules could not be started 
Failed modules: 
here is the code i used: 

odoo.define('new_timesheet.sheet', function (require){
"use strict";
var timesheet = require('hr_timesheet_sheet.sheet');
timesheet.WeeklyTimesheet.include({

});
});

**Comment by be-cloud-js** [comment] 2017-04-25 06:53
Hi all,

I encouter the same issue, after restoring a filestore.

Thing is the access right was not correct on some of my directory in my filestore, some directories where belonging to the root account and Odoo was not able to write the js files and thereby returned empty ones.

A tip is to check this and set the correct permission.

Definitively not a bug in Odoo though.

Hope it helps.

Jerome

**Comment by juliocbravo86** [comment] 2017-07-26 08:22
Hello bimajatiwijaya, I have the same error that says, I already found the solution. Thank you

**Comment by mge-odoo** [comment] 2017-11-27 15:43
@Yenthe666 I don't think that this is a bug in the Odoo framework.

This error message is the usual error message displayed when an Odoo JS module (with `odoo.define('...', function (require) { ... });`) can't be loaded (see `boot.js`). There may be several reasons, like an error in the module definition, a `require` for a module that doesn't exist, a circular dependency, etc. but it's usually a good reason.

I have checked on runbot as mentioned in the previous comments but this error doesn't appear anymore ; this could happen if someone push something that breaks the JS but it's usually quickly spotted.

I close this issue for now but it could be re-opened if there is a concrete use case.

**Closed by mge-odoo** 2017-11-27 15:43 UTC
Labels: 9.0, Framework

**Comment by aaguptaayush** [comment] 2018-11-02 11:48
i have also this kind of error how to solve?

**Comment by marvar81** [comment] 2021-03-01 22:53
> i was getting a similier error but when upgrade all modules.
> 
> in log message i got :
> Invalidating all model caches after database signaling.
> and on browser got this :
> 
> ![image](https://cloud.githubusercontent.com/assets/7659863/20036135/28b46c62-a431-11e6-966e-956ce966533d.png)

how do you solve this problem??

**Comment by marvar81** [comment] 2021-03-01 22:55
> Hello bimajatiwijaya, I have the same error that says, I already found the solution. Thank you

How do you solve this problem??
