### ISSUE TITLE
[12.0] Wrong float comparation when assign stock.move state 

### ISSUE THREAD

**Issue by suniagajose** [odoo/odoo#32745] opened 2019-04-16 15:59 UTC
Impacted versions:
12.0

Steps to reproduce:
- Do a intenal move with [this lines](https://drive.google.com/file/d/1dz2bTj93GuhpbdGuJJstzJzgWgXXPgNW/view), all quantities is the same

Current behavior:
- The Stock Move has an state 'Partially available' when is completly reserved, caused by a wrong float comparation (e.g. 358.59 == 358.5900000000001).
 - code to fix:
https://github.com/odoo/odoo/blob/12.0/addons/stock/models/stock_move.py#L933

Expected behavior:
- [This line](https://drive.google.com/file/d/12xez6VNFaHHD2URRJKMGGUdZlJVdZtZ9/view) should be in state assigned

Video/Screenshot link (optional):
img 1: https://drive.google.com/file/d/12xez6VNFaHHD2URRJKMGGUdZlJVdZtZ9/view
img 2: https://drive.google.com/file/d/1dz2bTj93GuhpbdGuJJstzJzgWgXXPgNW/view

**Comment by ADVALAKI** [comment] 2019-04-17 06:58
can i create fix and contribute to odoo?
and how?

**Comment by gdgellatly** [comment] 2019-04-17 16:46
probably duplicate of #32707

**Comment by len-odoo** [comment] 2019-04-19 14:16
I haven't checked everything so it will have to wait next week, but I guess you could already test this related PR.

**Comment by len-odoo** [comment] 2019-04-23 14:04
There was a bug in the first version of 32844 that I committed, but which is solved. 
Does it solve your issue or is there still something else?

**Comment by suniagajose** [comment] 2019-04-23 22:05
yes @len-odoo 

thanks

**Comment by Yenthe666** [comment] 2019-04-24 06:40
Apoligies, didn't notice it was still open. Reopened.

**Closed** 2019-04-24 07:47 UTC
Labels: 12.0, Logistics
