### ISSUE TITLE
odoo 10 bugs | odoo failed on basic operation for restore.

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#15659] opened 2017-02-27 15:29 UTC
Impacted versions: 10

Steps to reproduce: odoo multi worker configured with 6
retore 6MB database

Current behavior:
ERROR None odoo.http: Postgres subprocess ('/usr/bin/pg_restore', u'--dbname=fake_twt_fp_it', '--no-owner', '/tmp/tmpGAKdIw') error 1

Expected behavior: Must restore small database and their should not ownership issues
In multi subdomain configuration must need to works.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment] 2018-01-10 15:54
Hi @tejastank,

Could you add more information about how to reproduce it or how you've gotten this please?

Regards,
Yenthe

**Comment by Yenthe666** [comment] 2018-02-12 11:06
Hi there,

I'm closing this bug report as there has been no feedback in quite a while and we cannot reproduce it without more information.

Regards,
Yenthe

**Closed by Yenthe666** 2018-02-12 11:06 UTC
Labels: 10.0, Need information

**Comment by tejastank** [comment] 2018-02-12 11:43
Mr. @Yenthe666 over internet never found issue on github.com especially for odoo.  ;)
