### ISSUE TITLE
[master] stock.inventory: can't start an imported inventory adjustment with lines

### ISSUE THREAD

**Issue by matt454357** [odoo/odoo#12970] opened 2016-07-31 16:07 UTC
Impacted versions:

Using runbot, as of today...

- fails in master
- fails in saas-12
- works in 9.0

Steps to reproduce:

- import a partial inventory (Select products manually)
- click Start Inventory

Current behavior:

- Start Inventory action has no effect

Expected behavior:

- set state to confirm (In Progress)
- show imported inventory lines

Video/Screenshot link (optional):

Here's the csv I imported:
![screenshot_stock inventory csv](https://cloud.githubusercontent.com/assets/7604932/17277629/b3f4dc00-5704-11e6-8eef-49485b053d5e.png)

After clicking Start Inventory in master:
![screenshot_stock inventory start](https://cloud.githubusercontent.com/assets/7604932/17277641/135a44fa-5705-11e6-9004-1acb88d39187.png)

After clicking Start Inventory in 9.0:
![screenshot_stock inventory start v9](https://cloud.githubusercontent.com/assets/7604932/17277678/117f008e-5706-11e6-8f43-946282e6c0e5.png)

**Comment by JKE-be** [comment] 2016-08-01 14:39
Probably not a bug due to the import.
I already reported the bug from front end.
Thanks for the reporting.

**Comment by JKE-be** [comment] 2016-08-01 15:07
Ok, I have just checked and the bug reported has been fixed in commit https://github.com/odoo/odoo/commit/ec841b7fa17378578a3a56a957fd81c0fc9adc30

Can you check that you have well tested with this rev...?
And if the bug is always existing, can you provide your xml...

Thanks

**Comment by JKE-be** [comment] 2016-08-01 15:32
Related commit: odoo-dev/odoo@e94c1bb57b7848edba52771c70729edbad4e32e4

**Closed** 2016-08-01 16:14 UTC
