### ISSUE TITLE
[website_sale] Quantity set to 0 when removing other item from cart

### ISSUE THREAD

**Issue by stijnh92** [odoo/odoo#7888] opened 2015-08-05 08:43 UTC
Scenario:
Add 1 item to the shopping cart with for example quantity 1.
Add another item with any quantity to the shopping cart.

Remove the first added item to the cart by setting its quantity to 0.
The second item's quantity will also be set to 0.
When refreshing the page, the correct quantity is visible again.

Screenshots:
![step1](https://cloud.githubusercontent.com/assets/8638753/9081647/a458abae-3b5e-11e5-8f62-26b4408f7e68.png)

![step2](https://cloud.githubusercontent.com/assets/8638753/9081650/a6e5e490-3b5e-11e5-8266-7eec8ec7481e.png)

Environment:
Odoo 8.0 (tested on runbot.odoo.com with latest commits)
Browser: Firefox 39.0
OS: Ubuntu 15.04

**Comment by lukebranch** [comment] 2015-08-05 10:21
@stijnh92 ,

I'm not involved with Odoo SA, and am just another user like yourself, however I think this may be the same issue that I reported here:

https://github.com/odoo/odoo/issues/3342

Any chance you are also using Firefox/Aurora when this issue occurs? I've come across a useful tool for creating animated GIFs which is useful to demonstrate issues like this:

http://www.cockos.com/licecap/

Are you able to post back a screencap/GIF demonstrating the issue so that I can confirm that this is the same issue I reported back in #3342?

**Comment by stijnh92** [comment] 2015-08-05 10:37
It is exactly the same yes.

**Comment by lukebranch** [comment] 2015-08-05 10:44
@stijnh92 ,

Thanks for confirming that. That issue was created awhile back when Odoo 8 was just recently released, however I think it may not have been a top priority for them in terms of the other more important bugs that needed fixing.

I'm not sure who handles these types of issues at Odoo. 

@Yenthe666 sorry to bother, but i'm not sure who I should notify at Odoo SA regarding this issue. Any idea who I should ping at Odoo?

**Comment by Yenthe666** [comment] 2015-08-05 11:02
@lukebranch I usually ping odony (Olivier Dony). He replies most of the times! You can try Antony Lesuisse too but he doesn't respond on like half of the pings.

**Comment by lukebranch** [comment] 2015-08-05 11:06
@Yenthe666 ,

Thanks for the reply, much appreciated.

@odony ,

I'm sorry to bother you with this I understand you are very busy. It's been an issue since October 2014 and still seems to be present in the latest revisions to 8.0.

I will create an animated GIF demonstrating the issue and post back here and #3342. Any chance you would be able to take a look at it? This can be reproduced on the runbots for the 8.0 branch as well.

**Comment by odony** [comment] 2015-08-06 08:35
Thanks for the detailed reproduction information and the useful gifs! The bug is indeed confirmed and @JKE-be will have a look and fix it. In the mean time we can close this issue as it is an exact duplicate of earlier issue #3342.

**Closed by odony** 2015-08-06 08:35 UTC
