### ISSUE TITLE
[10.0] Disable /re-enable Shipping Management

### ISSUE THREAD

**Issue by Ark74** [odoo/odoo#34843] opened 2019-07-14 19:26 UTC
**Impacted versions:**
* 10 - affected
* 11 - not affected
* 12 - not affected

**Steps to reproduce:**
1. Enable delivery cost for clients on sales or web siteadmin settings (default on runbot)
2. Disable **Shipping Management**: _No shipping management on website_
3. Re-enable **Shipping Management**: 
* _Delivery methods are only used internally: the customer doesn't pay for shipping costs_
* _Delivery methods are selectable on the website: the customer pays for shipping costs_
4. Error:

```
ParseError: "duplicate key value violates unique constraint "ir_model_data_module_name_uniq_index"
DETAIL:  Key (module, name)=(delivery, free_delivery_carrier_product_template) already exists.
" while parsing /data/build/odoo/addons/delivery/data/delivery_data.xml:5, near
<record id="free_delivery_carrier" model="delivery.carrier">
            <field name="name">Free delivery charges</field>
            <field name="fixed_price">0</field>
            <field name="free_if_more_than" eval="True"/>
            <field name="amount">1000</field>
            <field name="sequence">1</field>
            <field name="delivery_type">fixed</field>
            <field name="product_type">service</field>
            <field name="product_sale_ok" eval="False"/>
        </record>
```

**Current behavior:**
Error when trying to re-enable _Shipping Management_

```
ParseError: "duplicate key value violates unique constraint "ir_model_data_module_name_uniq_index"
DETAIL:  Key (module, name)=(delivery, free_delivery_carrier_product_template) already exists.
" while parsing /data/build/odoo/addons/delivery/data/delivery_data.xml:5, near
<record id="free_delivery_carrier" model="delivery.carrier">
            <field name="name">Free delivery charges</field>
            <field name="fixed_price">0</field>
            <field name="free_if_more_than" eval="True"/>
            <field name="amount">1000</field>
            <field name="sequence">1</field>
            <field name="delivery_type">fixed</field>
            <field name="product_type">service</field>
            <field name="product_sale_ok" eval="False"/>
        </record>
```

**Expected behavior:**
Either overwrite exiting data or use previous data without error. Maybe?

**Video/Screenshot link (optional):**
* Disable v10
![v10](https://user-images.githubusercontent.com/7444518/61188310-e87bf180-a642-11e9-80f4-1499c718326c.png)
* Disable v11/12
![v11-12](https://user-images.githubusercontent.com/7444518/61188311-eca80f00-a642-11e9-880c-5b84feca7e0f.png)
* Re-enable error (v10)
![error-v10](https://user-images.githubusercontent.com/7444518/61188305-e1ed7a00-a642-11e9-8dd0-26ba76fa1038.png)

Tested on latest runbot at 07/14/19

**Comment by Lutrome** [comment] 2019-07-17 01:46
Wouldn't you need to reinstall the eCommerce Delivery module to re-enable Shipping Management without errors?

**Comment by Ark74** [comment] 2019-07-19 04:04
@Lutrome are you sure?
I checked and they seemed uninstalled.

**Comment by Lutrome** [comment] 2019-07-19 23:48
@Ark74 Yes, I am sure. I tested it again and it still doesn't uninstall the eCommerce module.
![Odoo Before Turning Off](https://user-images.githubusercontent.com/921778/61570967-1008fa80-aa45-11e9-883e-4dd6f442f89c.JPG)
![Odoo Turning Off](https://user-images.githubusercontent.com/921778/61570969-139c8180-aa45-11e9-957e-7f9d6444f86d.JPG)
![Odoo After Turning Off](https://user-images.githubusercontent.com/921778/61570971-16977200-aa45-11e9-861a-2940f000004b.JPG)

**Comment by Ark74** [comment] 2019-07-22 00:17
@Lutrome 
Why remove eCommerce?
May it be that you are confusing 2 different modules?

eCommerce vs. eCommerce Delivery.
![webshop-vs-webshop_delivery](https://user-images.githubusercontent.com/7444518/61599124-729bfb00-abeb-11e9-8b9b-afb55f8860a1.png)

It only should remove _eCommerce Delivery_, not the whole webshop, as it state it will remove.
![uninstalled](https://user-images.githubusercontent.com/7444518/61599158-e807cb80-abeb-11e9-8cfe-22383b62e98d.jpeg)

**Comment by Lutrome** [comment] 2019-07-22 08:32
I quick connected to a 10.0 runbot to check, but it seems it doesn't have eCommerce Delivery installed and I'm not sure how to install it.

**Comment by Yenthe666** [comment] 2019-10-03 08:01
Dear @Ark74,

As Odoo 13 has been released today it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe

**Closed by Yenthe666** 2019-10-03 08:01 UTC
Labels: 10.0, Logistics

**Comment by forvas** [comment] 2021-11-08 13:54
@Ark74 I have just faced the same problem when restoring a database in a new server. After the restoration, when I update all modules, I get the error. However, before doing the update, if I do this query in the restored database, I get:

```
SELECT * FROM ir_model_data where module='delivery' AND name='free_delivery_carrier';
 id | create_uid | create_date | write_date | write_uid | noupdate | name | date_init | date_update | module | model | res_id 
----+------------+-------------+------------+-----------+----------+------+-----------+-------------+--------+-------+--------
(0 rows)
```

And in the whole code of the instance there is only one file which introduces the External XML ID `delivery.free_delivery_carrier`.

Had you found the problem? I have no idea of the reason.

Regards.
