### ISSUE TITLE
I cant Get Attendance Employee to my time sheet #1

### ISSUE THREAD

**Issue by mahrous007** [odoo/odoo#62796] opened 2020-12-03 10:34 UTC
Impacted versions: Odoo V 12 Community

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

Error:
Odoo Server Error

Traceback (most recent call last):
File "/home/pico-odoo/Desktop/PICO/odoo/odoo/http.py", line 656, in _handle_exception
return super(JsonRequest, self)._handle_exception(exception)
File "/home/pico-odoo/Desktop/PICO/odoo/odoo/http.py", line 314, in _handle_exception
raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
File "/home/pico-odoo/Desktop/PICO/odoo/odoo/tools/pycompat.py", line 87, in reraise
raise value
File "/home/pico-odoo/Desktop/PICO/odoo/odoo/http.py", line 698, in dispatch
result = self._call_function(**self.params)
File "/home/pico-odoo/Desktop/PICO/odoo/odoo/http.py", line 346, in _call_function
return checked_call(self.db, *args, **kwargs)
File "/home/pico-odoo/Desktop/PICO/odoo/odoo/service/model.py", line 98, in wrapper
return f(dbname, *args, **kwargs)
File "/home/pico-odoo/Desktop/PICO/odoo/odoo/http.py", line 339, in checked_call
result = self.endpoint(*a, **kw)
File "/home/pico-odoo/Desktop/PICO/odoo/odoo/http.py", line 941, in call
return self.method(*args, **kw)
File "/home/pico-odoo/Desktop/PICO/odoo/odoo/http.py", line 519, in response_wrap
response = f(*args, **kw)
File "/home/pico-odoo/Desktop/PICO/odoo/addons/web/controllers/main.py", line 966, in call_button
action = self._call_kw(model, method, args, {})
File "/home/pico-odoo/Desktop/PICO/odoo/addons/web/controllers/main.py", line 954, in _call_kw
return call_kw(request.env[model], method, args, kwargs)
File "/home/pico-odoo/Desktop/PICO/odoo/odoo/api.py", line 759, in call_kw
return _call_kw_multi(method, model, args, kwargs)
File "/home/pico-odoo/Desktop/PICO/odoo/odoo/api.py", line 746, in _call_kw_multi
result = method(recs, *args, **kwargs)
File "/home/pico-odoo/Desktop/PICO/odoo/addons/hr_attendance_sheet/models/hr_attendance_sheet.py", line 240, in get_attendances
tz = pytz.timezone(self.env.user.tz)
File "/usr/local/lib/python3.6/dist-packages/pytz/init.py", line 163, in timezone
if zone.upper() == 'UTC':
AttributeError: 'bool' object has no attribute 'upper'

**Comment by pedrobaeza** [comment] 2020-12-03 13:26
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by sswapnesh** [comment] 2020-12-03 16:24
> File "/home/pico-odoo/Desktop/PICO/odoo/addons/hr_attendance_sheet/models/hr_attendance_sheet.py", line 240, in get_attendances
> tz = pytz.timezone(self.env.user.tz)
> File "/usr/local/lib/python3.6/dist-packages/pytz/init.py", line 163, in timezone
> if zone.upper() == 'UTC':
> AttributeError: 'bool' object has no attribute 'upper'

This is from a custom module.

**hr_attendance_sheet** is a custom module https://apps.odoo.com/apps/modules/12.0/hr_attendance_sheet/

**Comment by pedrobaeza** [comment] 2020-12-03 16:28
Yes, thanks for the pointer, so closing as no Odoo bug.

**Closed by pedrobaeza** 2020-12-03 16:28 UTC
Labels: Need information
