### ISSUE TITLE
Odoo-The document contains no pages

### ISSUE THREAD

**Issue by ronozoro** [odoo/odoo#6214] opened 2015-04-09 00:32 UTC
Hi there i'm trying to print Qweb report but no luck i don't know why

it just generate empty report with no pages Here is all my code for this report

i  need to generate a report from wizard
My report class : 

```
from openerp.osv import osv,fields
import time

class fci_attendance_analysis (osv.osv_memory):
    _name='fci.attendance.analysis'

    _columns={
        'standard_id':fields.many2one('fci.standard',string='Standard',required=True),
        'group_id':fields.many2one('fci.standard.groups',string='Group'),
        'date':fields.date('Date Of generation',readonly=True),
        '_date':fields.date('Date'),
        'student_id':fields.many2one('fci.student',string='Student'),
        'number_of_absence': fields.integer( 'Number Of Absence'),
        'terms_id': fields.many2one('fci.terms', string='Term',required=True),
        'subject_id':fields.many2one('fci.subject',string='Subject',required=True),
        'state': fields.selection([('s','by Subject'),('t','By Student')],string='Select Report Type',required=True),
    }
    _defaults = {
                 'state': 't',
                 'date': time.strftime("%Y-%m-%d")
                 }
    def gen_student_attendance_report(self,cr, uid, ids, context={} ):
        noobs_data=[]
        val=[]
        data = self.read(cr, uid, ids, ['group_id', 'date','standard_id',\
                                'student_id','state','terms_id','subject_id'], context=context)

        stu= data[0]['student_id']
        sub=data[0]['subject_id']
        darsh=int(stu[0])
        sasa=int(sub[0])
        if data[0]['state'] == 't':
            cr.execute(
            "select DISTINCT ON (s.name) s.name as student_name,d.name as subject_name,attendance_date from fci_attendance_line ,fci_student s,fci_subject d where s.id=%d and d.id=%d and present=False "% (
                darsh,sasa))
            noobs = cr.dictfetchall()
            cr.execute(
            "select DISTINCT ON (s.name) s.name as student_name,d.name as subject_name,attendance_date from fci_attendance_line ,fci_student s,fci_subject d where s.id=%d and d.id=%d and present=False "% (
                darsh,sasa))
            noobs_details = cr.dictfetchall()
            for details_ids in noobs_details:
                for data in noobs:
                    details_ids[data['student_name']] = str(data['student_name'])+str(data['subject_name']) + str(data['attendance_date'])
                noobs_data.append(details_ids)
            print("Values",noobs_data)
        return  self.pool['report'].get_action(cr, uid, [], 'FCI_ERP.abcence_report_stu_document', data=noobs_data, context=context)
```

here is my wizard code : 

```
<?xml version="1.0" encoding="UTF-8"?>
<openerp>
    <data>
        <record id="fci_attendance_analysis_form" model="ir.ui.view">
            <field name="name">fci.attendance.analysis.form</field>
            <field name="model">fci.attendance.analysis</field>
            <field name="priority" eval="8"/>
            <field name="arch" type="xml">
                <form string="Time Table Report" version="7.0">
                    <header>
                        <span groups="base.group_user">
                            <button special="cancel" string="Close" type="object"
                                    icon="terp-dialog-close"/>
                            <button string="Generate Time Table Report" type="object"
                                    name="gen_student_attendance_report"/>
                        </span>
                    </header>
                    <sheet>
                        <separator string="Select Teacher/Student" colspan="4"/>
                        <div>
                            <group colspan="4" cols="4">
                                <field name="state"/>
                                <field name="standard_id"/>
                                <field name="date"/>
                                <field name="terms_id"/>
                                <field name="subject_id"/>
                            </group>
                            <group col="4" colspan="4">
                                <field name="group_id"
                                       attrs="{'required':[('state','=','t')],'invisible':[('state','!=','t')]}"/>
                                <field name="student_id"
                                       attrs="{'required':[('state','=','t')],'invisible':[('state','!=','t')]}"/>
                            </group>
                        </div>
                    </sheet>
                </form>
            </field>
        </record>

        <record model="ir.actions.act_window" id="fci_attendance_analysis_reports_view">
            <field name="name">Generate Time Table Report</field>
            <field name="type">ir.actions.act_window</field>
            <field name="res_model">fci.attendance.analysis</field>
            <field name="view_type">form</field>
            <field name="view_mode">form</field>
            <field name="target">new</field>
            <field name="domain">[]</field>
            <field name="context">{}</field>
        </record>
        <record model="ir.actions.act_window.view" id="fci_attendance_analysis_reports_view_form">
            <field name="act_window_id" ref="fci_attendance_analysis_reports_view"/>
            <field name="sequence" eval="20"/>
            <field name="view_mode">form</field>
            <field name="view_id" ref="fci_attendance_analysis_form"/>
        </record>
    </data>
</openerp>
```

here is my report tag : 

```
<report
           string="Student Report Absence"
           id="report_Absence_subject"
           model="fci.attendance.analysis"
           report_type="qweb-pdf"
           name="FCI_ERP.abcence_report_stu_document"
           file="FCI_ERP.abcence_report_stu_document"/>
```

and here is my report.xml :

```
<?xml version="1.0" encoding="utf-8"?>
<openerp>

    <data>
        <template id="abcence_report_stu_document">
            <style type="text/css">
                table.gridtable {
                font-family: verdana,arial,sans-serif;
                font-size:14px;
                color:#333333;
                border-width: 1px;
                border-color: #666666;
                border-collapse: collapse;
                }
                table.gridtable th {
                border-width: 1px;
                padding: 9px;
                border-style: solid;
                border-color: #666666;
                background-color: #dedede;
                }
                table.gridtable td {
                border-width: 1px;
                padding: 9px;
                border-style: solid;
                border-color: #666666;
                background-color: #ffffff;
                }
            </style>

            <t t-call="report.html_container">
                <t t-foreach="docs" t-as="o">
                    <t t-call="report.external_layout">
                        <div class="font">
                            <div class="page">
                                <div class="row text-center">
                                    <h2>
                                        <b>
                                            <span t-field='res_company.name'/>
                                        </b>
                                    </h2>
                                </div>
                                <para>
                                    <font color="white">......</font>
                                </para>
                                <para>
                                    <font color="white">......</font>
                                </para>
                                <para>
                                    <font color="white">......</font>
                                </para>
                                <div class="row text-center">
                                    <h2>
                                        <strong>

                                            <p>
                                              <span t-esc="o.student_id.name"/>
                                            </p>

                                            <p>
                                               <span t-esc="o.subject_id.name"/>
                                            </p>
                                        </strong>
                                    </h2>
                                </div>
                                <para>
                                    <font color="white">......</font>
                                </para>
                                <para>
                                    <font color="white">......</font>
                                </para>
                                <para>
                                    <font color="white">......</font>
                                </para>
                                <para>
                                    <font color="white">......</font>
                                </para>
                                <table class="gridtable">
                                    <tbody>
                                        <tr>
                                            <th>Student Name</th>
                                            <th>Standard</th>
                                            <th>Group</th>
                                        </tr>
                                        <tr>
                                            <td>
                                                <span t-esc="o.student_id.name"/>
                                            </td>
                                            <td>
                                                <span t-esc="o.standard_id.name"/>
                                            </td>
                                            <td>
                                                <span t-esc="o.standard_group.name"/>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                                <para>
                                    <font color="white">......</font>
                                </para>
                                <para>
                                    <font color="white">......</font>
                                </para>
                                <table class="gridtable">
                                    <tbody>
                                        <tr>
                                            <th>Subject Name</th>
                                            <th>Absence Day</th>
                                        </tr>
                                        <tr t-foreach="gen_student_attendance_report()" t-as="a">
                                            <td>
                                                <span t-esc="a['student_name']"/>
                                            </td>
                                            <td>
                                                <span t-esc="a['attendance_date'] "/>
                                            </td>

                                        </tr>

                                    </tbody>
                                </table>
                                <para>
                                    <font color="white">......</font>
                                </para>
                                <para>
                                    <font color="white">......</font>
                                </para>
                            </div>
                        </div>
                    </t>
                </t>
            </t>
        </template>
    </data>
</openerp>
```

thanks

**Comment by ibrahimomer** [comment] 2017-01-22 10:16
i have the same issue but i couldn't solve it

**Comment by Yenthe666** [comment] 2017-01-22 14:45
Hi,

The Github tracker is only for official bugs in the code, not custom development.
Please try the help forums (help.odoo.com).
Closing this one since it is not a bug in the official code.

Regards,
Yenthe

**Closed by Yenthe666** 2017-01-22 14:45 UTC
