### ISSUE TITLE
Auto resolve a question in Odoo Forum.

### ISSUE THREAD

**Issue by kbirkbr** [odoo/odoo#38845] opened 2019-10-16 05:39 UTC
Impacted versions:

Steps to reproduce:
1. Post a question in Odoo forum.
2. Somebody will respond to the question and the response will convert as answered automatically, even the provided answer not resolve the question/issue. 

Current behavior:
 Convert the response to answer automatically, even the answer not resolve the issue/question. And the question tagged as resolved automatically

Expected behavior:
Leave the response submitted by users as it is and allow the owner of the question to convert as the answer.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment] 2019-10-16 08:37
Hi,

I can assure you that answers are not automatically accepted. This happens by somebody on the official help forums. There are some people pretty active on it and if they see an answer that answers the question (or if they believe so) they usually accept it. 
Closing this one as it is not a bug but actual people accepting the answer. ;)

Regards,
Yenthe

**Closed by Yenthe666** 2019-10-16 08:37 UTC

**Comment by kbirkbr** [comment] 2019-10-16 08:41
@Yenthe666 , But that answer won't help to resolve the issue. Such case how can they accept the answer?
For your reference [link](https://www.odoo.com/forum/help-1/question/how-can-i-deactivate-a-company-insted-of-delete-in-odoo10-157404)

**Comment by Yenthe666** [comment] 2019-10-16 08:53
Sadly this does happen indeed. I can see the answer given wasn't really a good one and pretty vague. The issue with this is that it happens from time to time and sometimes some people even create fake accounts to accept/upvotes their own answers (note: I'm not saying it is the case here). There is not much to about this.

There is one thing that I still believe should be possible though and that is having the ability to remove an accepted answer again. It was possible in the past but has been removed at some point by Odoo.
@JKE-be do you think we could re-introduce the option?

Regards,
Yenthe

**Comment by kbirkbr** [comment] 2019-10-16 09:00
@Yenthe666 , What about considering, acceptance of the answer is only by the owner of the question instead of other users.

**Comment by Yenthe666** [comment] 2019-10-16 09:17
The final call is to the guys from Odoo, Jérémy should get back to you.

**Comment by kbirkbr** [comment] 2019-10-16 09:22
Thanks @Yenthe666 ,
And one more thing, if you can make the [question](https://www.odoo.com/forum/help-1/question/how-can-i-deactivate-a-company-insted-of-delete-in-odoo10-157404) ( I mentioned above ) as unresolved, please do it.
Thanks.

**Comment by Yenthe666** [comment] 2019-10-16 11:55
Sorry I don't have administrator rights on this database, I'm just a volunteer ;)
