### ISSUE TITLE
[13.0][control_panel_view.js] TypeError: Cannot read property 'context' of undefined

### ISSUE THREAD

**Issue by andrepurnomo** [odoo/odoo#46412] opened 2020-02-27 09:59 UTC
```
Error:
Traceback:
TypeError: Cannot read property 'context' of undefined
    at Class._evalArchChild (http://localhost/web/static/src/js/views/control_panel/control_panel_view.js:145:25)
    at http://localhost/web/static/src/js/views/control_panel/control_panel_view.js:287:26
    at Array.map (<anonymous>)
    at Class._parseSearchArch (http://localhost/web/static/src/js/views/control_panel/control_panel_view.js:285:45)
    at Class.init (http://localhost/web/static/src/js/views/control_panel/control_panel_view.js:117:22)
    at Class.prototype.<computed> [as init] (http://localhost/web/static/src/js/core/class.js:90:38)
    at new Class (http://localhost/web/static/src/js/core/class.js:107:33)
    at Class._createControlPanel (http://localhost/web/static/src/js/views/abstract_view.js:277:32)
    at Class.getController (http://localhost/web/static/src/js/views/abstract_view.js:208:51)
    at Class.prototype.<computed> [as getController] (http://localhost/web/static/src/js/core/class.js:90:38)
```

I get the above error after upgrading my module, the module is simple and has one compute value. My current solution is to rebuild the database and work as normal. But if I upgrade the module again, the error message will appear again.

Does anyone know the solution? thank you.

Impacted versions: 
- 13

Steps to reproduce:
- create database
- install module
- input data
- upgrade module
- ERROR

Current behavior:
- still got error

Expected behavior:
- no error

Video/Screenshot link (optional):

**Comment by andrepurnomo** [comment] 2020-02-27 18:33
I found the problem, it happened because of views. When I install, the form, tree, and kanban don't have an external ID.

![Screen Shot 2020-02-28 at 01 21 01](https://user-images.githubusercontent.com/24785523/75474185-1c850680-59c9-11ea-89ea-128c06cb5f92.png)

Then I upgraded the module and got a new view with the random type and random external id.

![Screen Shot 2020-02-28 at 01 21 52](https://user-images.githubusercontent.com/24785523/75474293-52c28600-59c9-11ea-8ff6-4104c91e43dd.png)

Because the type is random, I found a view with a form type but it has an arch_db from the kanban type.
![Screen Shot 2020-02-28 at 01 32 18](https://user-images.githubusercontent.com/24785523/75474821-3f63ea80-59ca-11ea-9479-34368b8d61cd.png)

I don't know why this can happen, for other views there are no problems.

Does anyone have a solution please?

**Comment by pedrobaeza** [comment] 2020-02-27 18:35
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2020-02-27 18:35 UTC
