### ISSUE TITLE
TypeError: Cannot read property 'list' of undefined at Class.setup (http://192.168.1.206:8069/web/static/src/js/views/view_dialogs.js:376:45)

### ISSUE THREAD

**Issue by ahmedlatif** [odoo/odoo#69101] opened 2021-04-11 23:39 UTC
Impacted versions: 12, 13, 14

Steps to reproduce:
I have this custom made widget which is when clicking on a One2many "search more" hyperlink is supposed to expand a wizard displaying the treeview products, so when it stopped working i tried debugging with assets and when i click on the hyperlink i get the error 
```
TypeError: Cannot read property 'list' of undefined
    at Class.setup (http://192.168.1.206:8069/web/static/src/js/views/view_dialogs.js:376:45)
```
when clicking on the view_dialogs.js to find where the exception is it says the problem is within this line
```
 var view = new ViewClass(fieldsViews[this.viewType], _.extend(viewOptions, {
```

Current behavior:
The widget isn't working and the One2many search more hyperlink is not displaying the whole tree view of the products

Expected behavior:
When clicking on search more, a wizard with the tree view of the products should pop up

Video/Screenshot link (optional):
![Screenshot_1](https://user-images.githubusercontent.com/11459081/114325341-e0125c80-9b2f-11eb-9c18-6d01f7b33495.png)

**Comment by pedrobaeza** [comment] 2021-04-12 00:28
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2021-04-12 00:28 UTC
