### ISSUE TITLE
Outgoing emails quotes & invoices not sending - please help!

### ISSUE THREAD

**Issue by 2SI3NX** [odoo/odoo#5210] opened 2015-02-10 23:13 UTC
Hi, everytime i send an email either quote or invoice the email sends with no error but the followers dont receive it. please help, this worked on the latest version in December and as soon as i updated Odoo now end of January ive had this problem.

I have also tested my outgoing servers and they all test successful, but the recipient doesnt seem to receive any mail at all.

**Comment by eskimoroll** [comment] 2015-02-11 19:59
"the followers dont receive it" - do you know for sure it isn't going into their spam box?

Does the sender domain have a valid SPF record?

"as i updated Odoo now end of January ive had this problem" - has Odoo changed ip addresses?...if the new ip has no reputation, emails generated from that IP could be going into spam boxes.

Do you have access to the email server queues? You can check at least that your MTA is functioning and the emails are getting to your outgoing server queue.

"I have also tested my outgoing servers"...are you even using the local server's MTA...or are you using an external account?

**Comment by VisionTen** [comment] 2015-02-11 22:46
Are you able to send quotations with the Admin user? I'm having a similar issue where no emails are generated/sent unless I am using the admin user.

**Comment by Beast141** [comment] 2015-02-12 05:59
@eskimoroll 
1. Yes  i am very certain it is not going to their spam boxes as i have sent to a number of different emails.
2. The emails i am sending from - i use them on my own email client as well so i have no problem sending/receiving emails.
3. When i updated Odoo - i changed my internal ip address of the server to a different one - so i am not sure if that makes a difference?  Does it perhaps need to revert back since Odoo might be binded to the previous IP address?
4. How do i get access to the email server queues?  Do you mean by my hosting company on my cpanel account?
5.What is the local server's MTA? i am using my own outgoing server which previously worked just fine. Even now the outgoing servers test successful but no mail.

@VisionTen I actually am the admin user - i have just renamed it to my name, which worked before. So dont think that is the issue.

I really would like to know if anyone else is having this problem because maybe i did something wrong during the upgrade.

**Comment by Beast141** [comment] 2015-02-16 05:08
Ive narrowed down the issue - i reloaded my backed up Virtual Machine and Odoo email sending worked like it used to. i then did precisely these steps to update. i did a git reset --hard and then a git pull and once finished updating and i restarted the server - i then tried to send quote/invoice to an external email and i did not receive it. Something has gone wrong after the update. or was i not supposed to do a git reset --hard ?

Please can someone help

**Comment by lukebranch** [comment] 2015-02-16 05:18
@Beast141 ,

Just out of interest are you running in Gevent mode (eg. port :8072 by default), or server mode (:8069 by default)?

If you're running in Gevent mode only and not gevent and server mode together then it's more than likely that your crons are not are not firing.

**Comment by Beast141** [comment] 2015-02-16 05:23
@lukebranch i have actually changed my port to a different number. Which i used before the upgrade as well. i didnt change any of these modes after the upgrade.  all i did was those 2 git commands.

Do you maybe have any idea what could be causing this? im starting to think it was the git reset hard command.

**Comment by lukebranch** [comment] 2015-02-16 09:35
@Beast141 ,

Unfortunately i'm on the road at the moment, and won't be able to check this out for a week or so. I'd recommend asking this question in the help forum, as I have a feeling this is directly related to the cron's not working properly for some reason.

You may want to switch your logs over to debug mode, and try to change your outgoing mail server to something plugged into mandrill for outgoing mail, as this will give you a very good idea of whether your mail is actually being sent out from Odoo, and if so, whether it is bouncing from your recipient's mailboxes or any other reasons.

Regardless i'd highly recommend asking the question in the forum and posting back here with the link for the sake of others who might land on this from google searches.

**Comment by Beast141** [comment] 2015-03-17 04:12
@lukebranch ,

Okay i have installed a separate fresh clean virtual Ubuntu Server and i installed Odoo fresh from the start with the install script of Andre schenkels - i then imported my database from my previous Odoo and tried to email again to a test user but nothing. Then i went ahead and redid the server without restoring any DBm started from scratch and setup an outgoing server - but i replaced localhost outgoing server with my own and when i tried emailing a test client via invoice or quotation - nothing. that email receives nothing once again. so i definitely know it is not my database that is causing an issue.

Please note once again that since November/December 2014 my last update using a git pull on my previous server is when i have been having this issue. before that everything worked and i had 3 outgoing mail servers and each worked for Invoice, Quotations, etc. bearing in mind i had replaced localhost outgoing server right from the beginning. 

Now even with a fresh server emails arent being received! i dont understand what is wrong, a fresh installation of Odoo - all i did was replace localhost with my own.. is that maybe the issue?

Please help guys.. im going crazy here. or is there something wrong with the latest Odoo.?

**Comment by Beast141** [comment] 2015-04-05 10:32
So i have figured out what the issue was. After spending days and even weeks of installing and re-installing. I emptied out the domain alias and that is what made the difference for me.

**Comment by TheWorks46** [comment] 2015-09-08 09:41
@Beast141 ,

Seems I've the same issue, which aliases did you empty out exactly? Those in Settings > Email > Aliases ?

![screenshot_email_alias](https://cloud.githubusercontent.com/assets/9446059/9731635/62f91aba-561e-11e5-9974-bc677d54d851.png)

**Comment by Beast141** [comment] 2015-09-09 01:58
Hi there - @TheWorks46 

No, the place i emptied it out is under General Settings.
![selection_009](https://cloud.githubusercontent.com/assets/10450920/9751603/135a3384-56a7-11e5-8bba-0584d0ae03ca.jpg)

**Comment by TheWorks46** [comment] 2015-09-22 11:19
Thanks @Beast141 ! This resolved the issue for me.

**Comment by innovo3d** [comment] 2016-11-11 16:58
@Beast141 , where is this setting?  I used to see it under Sales, Configuration, Settings, but after I set my email servers this setting seems to have disappeared!  Where can I find it?

**Comment by innovo3d** [comment] 2016-11-11 17:46
Never mind.  I found the problem.

Basically it had to do with my understanding of the "EMAIL" function.  I assumed that it meant that it would actually send a real email, which in my honest opinion, it should.  However, if the user has their preferences set as "Email Messages and Notifications? **Never**" then all of the EMAILS sent through the @ Send Email function will only be sent internally as a "Comment" through the Odoo system and the user will only see them when they log in.

**Comment by eburghar** [comment] 2017-01-31 21:06
This is silly and **clearing the domain** is definitively not the solution and **can't work**. How a smtp server is supposed to handle/accept a mail which has a recipient address without a domain ???

The root of the problem is on your smtp. Check the logs to see why it's rejecting an email which has an alias of the sending account as sender address.

**Comment by 2SI3NX** [comment] 2017-02-09 09:18
@eburghar this issue refers to people who SELF-HOST the server locally, while at the same time setting up **any** smtp server only for sending emails, which has nothing to do with setting the domain on Odoo.

**Comment by eburghar** [comment] 2017-02-09 11:11
Never stated this was for saas nor for a specific smtp server. There is no issue sending to whatever smtp server with alias and domain, as sender addresses are correctly created buy joining them together. So if you have issue with sending email with domain, it means you have a problem with your smtp or setting aliases and/or domain. We saw issues for example if the bounce email is not declared on the smtp server (default to odoo-postmaster).

On jeudi 9 février 2017, 10:19:19 WAT 2SI3NX wrote :
> @eburghar this issue refers to people who SELF-HOST the server locally, while at the same time setting up **any** smtp server only for sending emails, which has nothing to do with setting the domain on Odoo. 
> 
>

**Comment by Yenthe666** [comment] 2017-02-09 14:10
Hi everybody,

Since the original issue is already solved by the user itself I'm closing this issue.
The other topics are all other cases.
If somebody still fases a bug/issue please create a new issue report with as much information as you can.

Regards,
Yenthe

**Closed by Yenthe666** 2017-02-09 14:10 UTC
