### ISSUE TITLE
Order items missing in polish invoice print german invoice print is ok

### ISSUE THREAD

**Issue by hkiepe** [odoo/odoo#43888] opened 2020-01-24 08:35 UTC
Impacted versions: odoo12
Server ubuntu 18.04
Hello, the order items are missing in the PDF invoices, printed out for polish clients. For the german clients the order items are printed out in the PDF invoice. Any ideas? See screenshots.
![2020-01-24_09h30_10](https://user-images.githubusercontent.com/7147141/73055311-d5b56580-3e8c-11ea-8a79-930fce182246.png)
![2020-01-24_09h27_47](https://user-images.githubusercontent.com/7147141/73055312-d64dfc00-3e8c-11ea-98e4-a72b6148f62d.png)

**Comment by pedrobaeza** [comment] 2020-01-24 20:41
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by C3POdoo** [comment] 2023-03-30 11:43
Dear @hkiepe,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._

**Closed by C3POdoo** 2023-03-30 11:43 UTC
