### ISSUE TITLE
payment confirmation internal server error

### ISSUE THREAD

**Issue by BlissNomad** [odoo/odoo#52630] opened 2020-06-08 18:45 UTC
Impacted versions:13

Steps to reproduce:process payment and confirmation screen shows error

Current behavior: shows internal server error

Expected behavior: shows confirmation of payment page

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/53065476/84068078-72892300-a996-11ea-87c5-b17992eb9c2e.png)

when i try to complete a payment it goes through (i verified in bank and in sales reporting) but dosent give payment recieved or confirmation page, it gives this error instead:

Internal server error
("Failed to render template <Template memory:7f41dd31d978> using values {'format_date': <function MailTemplate._render_template.<locals>.<lambda> at 0x7f41dcc6cbf8>, 'format_datetime': <function MailTemplate._render_template.<locals>.<lambda> at 0x7f41dcc6cea0>, 'format_amount': <function MailTemplate._render_template.<locals>.<lambda> at 0x7f41dcc6ce18>, 'format_duration': <function MailTemplate._render_template.<locals>.<lambda> at 0x7f41dcc6cc80>, 'user': res.users(1,), 'ctx': {'lang': 'en_US', 'tz': 'Canada/Eastern', 'uid': 2, 'force_send': True, 'default_mass_mailing_name': False, 'default_mass_mailing_id': False, 'active_id': 52, 'active_ids': [52], 'active_model': 'sale.order', 'default_composition_mode': 'comment', 'default_model': 'sale.order', 'default_res_id': 52, 'default_template_id': 11, 'custom_layout': 'mail.mail_notification_paynow', 'tpl_partners_only': True, 'safe': False}, 'object': sale.order(52,)}", '')

**Comment by Yenthe666** [comment] 2020-06-09 06:17
@BlissNomad are you sure you didn't modify this e-mail and that you didn't break it though? Can you reproduce it on an official Odoo test instance at runbot.odoo.com?

**Comment by Yenthe666** [comment] 2020-07-27 14:59
Hi there,

Since there has been no feedback or answer on my questions I'm closing this one.
Feel free to respond with extra info and we'll reopen it.

Regards,
Yenthe

**Closed by Yenthe666** 2020-07-27 14:59 UTC
