### ISSUE TITLE
[13] Changing the currency in a sales order does not update the currency in the order lines

### ISSUE THREAD

**Issue by grzekru** [odoo/odoo#48156] opened 2020-03-22 16:25 UTC
**Impacted versions:**

13

**Steps to reproduce:**

1. Install sale module
2. Turn on pricelists and Multi-Currencies in settings
3. Create 2 pricelists with different currency (fe EUR and USD)
4. Create quotation, select USD pricelist
5. Add order line to quotation
6. Save
7. Edit
8. Change pricelist to EUR

**Current behavior:**

Incompatible currencies in the sales order and in the order line

**Expected behavior:**

The order lines currency changes to the currency assigned to the order

**Video/Screenshot link (optional):**

![image](https://user-images.githubusercontent.com/5862658/77254557-041fa900-6c62-11ea-9ac4-e8f65820ca24.png)

**Comment by sswapnesh** [comment] 2020-03-22 17:32
Hello @grzekru  
It won't be changed automatically (Duplicate of https://github.com/odoo/odoo/issues/23771 and has been Improved at https://github.com/odoo/odoo/pull/31535 for v14)


I don't think Patch #48157 will be accepted (Cc @dbo-odoo )
 
(Have a look at https://github.com/odoo/odoo/issues/23771#issuecomment-492767721)

**Comment by grzekru** [comment] 2020-03-22 18:53
SO line currency is clearly incorrect. In addition, the line currency is ignored when creating an invoice from the order. Its not about recomputing line value, just changing currency to match the sale order.

**Comment by dbo-odoo** [comment] 2020-03-23 07:05
> SO line currency is clearly incorrect

I agree. This is not good at all.

Was fixed in 12.0 at 3fdf3b1552. Was fixed in 13.0 at 2dfc0ea8c241d5d7 then reverted at 34e679598be... because it broke a test. Imm'a fix that test, I don't like this behaviour as it breaks expected relations.

Checking this out now, I'd like to have this fixed properly because it sucks big time.

**Closed** 2020-03-23 11:17 UTC
Labels: 13.0, Sales
