### ISSUE TITLE
account.move.line create() is looking for field code of account.account.type

### ISSUE THREAD

**Issue by PortCities** [odoo/odoo#10246] opened 2015-12-31 08:41 UTC
account.move.line create() is looking for field code of account.account.type

but this field doesnt exist. The bug is in line 931 of file /odoo/addons/account/models/account_move

to test the bug, add account type control on journal

**Comment by Yenthe666** [comment] 2016-06-15 10:07
Hi @PortCities,

Thanks for your report but you're mentioning a line on a file that has been edited after your report, so I have no way to check this.
I can't reproduce any issues in the latest Odoo code either.
I'm closing this since I have not enough information and cannot reproduce this.
If you still face this issue please create a new report with more details about the issue (and I'd love screenshots too).

Regards,
Yenthe

**Closed by Yenthe666** 2016-06-15 10:07 UTC
