### ISSUE TITLE
[Odoo12] website_builder: undefined snippets section

### ISSUE THREAD

**Issue by AntonioMalatesta8** [odoo/odoo#31893] opened 2019-03-16 14:17 UTC
**Impacted versions:**
Odoo 12
**Steps to reproduce:**
Edit the Home page using website builder snippets.
**Current behavior:**
When edit mode is enabled some snippets still not visibile (ex: Banner, Carousel, etc...).
All this snippets are grouped under "undefined" section.
**Expected behavior:**
Those snippet should be visibles and should be draggables in website area.
**Video/Screenshot link (optional):**
![Odoo12_error](https://user-images.githubusercontent.com/25451499/54476503-84fdc680-47fe-11e9-8f5f-69fca6244c8f.png)

**Comment by pedrobaeza** [comment] 2019-03-17 19:29
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by AntonioMalatesta8** [comment] 2019-03-17 19:56
Hi, I’m sorry but I’m not able to reproduce the error on runbot instance. 
Perhaps the error may have been caused by the installation method. 
I clone the latest odoo12 repository code in my local enviroment. Indeed I have installed odoo by source code. No addons modules, only a fresh installation. Thank you for your’s interest

**Comment by pedrobaeza** [comment] 2019-03-17 20:21
Sorry, then I'm afraid you have to check again your installation method, as this is not a direct problem of Odoo itself. Check the installation instructions on https://www.odoo.com/documentation/12.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

**Closed by pedrobaeza** 2019-03-17 20:21 UTC
Labels: Need information

**Comment by Yenthe666** [comment] 2019-03-17 20:31
and you can also try to update your source code to the latest version.

**Comment by AntonioMalatesta8** [comment] 2019-03-17 20:50
Yes, my code it was update at the latest version. In the last few days I will try to install again from source code. Thank you.

**Comment by AntonioMalatesta8** [comment] 2019-03-18 15:16
Hi @pedrobaeza and @Yenthe666 I have found something of interesting...
I have downloaded the latest version of nightly build selecting the src options at this link [odoo 12 nightly src](https://nightly.odoo.com/12.0/nightly/src/odoo_12.0.latest.tar.gz).
Then I compared the code of my version (
obtained by performing git clone) with the code of the downloaded nightly version.
As you can see in "git clone version" the module base is missing:
![image](https://user-images.githubusercontent.com/25451499/54540267-f624b180-4997-11e9-8ca7-05de69544d11.png)
In the left side there is my code version (cloned by github), in the right side there are the build version.
The module base, in github repository is located under odoo/odoo/addons/base.
In this location seems to be present the unit test and not the odoo code.
![image](https://user-images.githubusercontent.com/25451499/54540623-9aa6f380-4998-11e9-858a-2462a9f05c1e.png)
Is this my mistake or i have to load this location in the addons_path configuration parameters? 
In my enviroment if I move the base module from odoo/odoo/addons to odoo/addons the website error disappear.
Thank you.

**Comment by Yenthe666** [comment] 2019-03-18 15:30
@d-fence I summon you, the almighty Odoo packager! Do you know this from the top of your head? :)

**Comment by d-fence** [comment] 2019-03-18 15:36
You should not compare the git directory tree of Odoo with the source "package".
Source package is a dist package with ./addons moved in ./odoo/addons.

**Comment by AntonioMalatesta8** [comment] 2019-03-18 15:43
Ok I know about it,
but if I move the base modulo into the odoo/addons directory the problem describe above disappear.
Why?
So, is the location for the base module is correct ? 
Thank you @d-fence @Yenthe666

**Comment by d-fence** [comment] 2019-03-18 15:46
I don't know why you have to move it as it's already in odoo/addons:
https://github.com/odoo/odoo/tree/12.0/odoo/addons

**Comment by AntonioMalatesta8** [comment] 2019-03-18 16:51
Hi evrybody,
I'm sorry but the location of base module seems to be fake error (sorry, my mistake).

after several tests I discovered that the problem is the language setting when creating the database (**it is important to set the language at the exact moment the database is created**)
The steps to follow to reproduce the error are:
1. Create a new database with the Italian language
2. Install the website_builder module
3. Try editing the homepage.

The components not shown are:
banner, picture, carousel, features, three columns (in the structure section)
twitter scroller (in the features section)

I hope it can help you.
Thanks a lot for your's patience :-)

**Comment by pedrobaeza** [comment] 2019-03-18 17:35
Check the translations at https://www.transifex.com/odoo/odoo-12

**Comment by biodolo** [comment] 2019-03-29 10:57
Hi ,
we have the same problem with the website_builder.
Attached you can find a zip with a webm inside that shows a usecase to replicate the problem

[screencast-sandbox.odoo.netfarm.it-8076-2019.03.29-11-43-12.webm.zip](https://github.com/odoo/odoo/files/3022253/screencast-sandbox.odoo.netfarm.it-8076-2019.03.29-11-43-12.webm.zip)

**Comment by sherpya** [comment] 2019-05-20 10:55
@AntonioMalatesta8 it was a non closed <b> tag in the translation of website Italian po (text_block and tabs), fixed in 4ccdddc, I suggest you to manually load it.po of website addon because update module did not work for me

**Comment by AntonioMalatesta8** [comment] 2019-05-20 11:01
ok @sherpya, thanks a lot!!! :+1:
