### ISSUE TITLE
[10.0] LDAP problem with special characters

### ISSUE THREAD

**Issue by BT-aestebanez** [odoo/odoo#25039] opened 2018-06-04 08:35 UTC
Impacted versions: At least 10.0 (not tested in other versions)

Steps to reproduce: Try to login as a user which has a special character such as ä in the login

Current behavior: UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 26: ordinal not in range(128)

Expected behavior: Log in

Video/Screenshot link (optional):
https://github.com/odoo/odoo/blob/10.0/addons/auth_ldap/models/res_company_ldap.py#L148
Just modifying 'filter' to filter.encode('utf-8') in the line, it should work properly

**Comment by pedrobaeza** [comment] 2018-06-04 09:06
I'm pretty sure this doesn't happen in v11 due to Python 3.

**Comment by BT-aestebanez** [comment] 2018-06-04 09:09
You are right, my fault

**Comment by Yenthe666** [comment] 2019-10-07 09:10
Dear @BT-aestebanez,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe

**Closed by Yenthe666** 2019-10-07 09:10 UTC
Labels: 10.0, Services
