### ISSUE TITLE
Duplicating workcenters leads to duplicate names (the new one)

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#20956] opened 2017-11-15 08:13 UTC
Impacted versions: 11.0 the issue is probably in community but shows only in enterprise

Steps to reproduce:
In enterprise runbot
Go to workcenters and click into "Drill Station 1"
Click Duplicate
Change name to "Drill Station Why is there two of you now?" or similar
Return to list view

Current behavior:
Both names change

Expected behavior:
Only the new one changes

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/5093264/32825402-c2c56a9c-ca49-11e7-9f3f-ac22e14d9caa.png)

**Comment by sle-odoo** [comment] 2017-11-15 12:14
Hi,
It is related to rev 5a9cff3387cbb85034e58b587bd8e5ca9bbd089d that first landed in saas-15 (and the issue is present since saas-15). When you edit the name of a workcenter, you're actually editing the name of the resource (it's a related).

As "resource_id" is not set as copy False, it is passed when duplicating a workcenter and thus the new workcenter shares the same ressource as the original one, so editing the new name will also edit the original one.

@tde-banana-odoo should we set "resource_id" as copy False on the resource mixin or are they legit usecases when duplicating a record should keep the original resource? Thanks

**Comment by tde-banana-odoo** [comment] 2017-11-15 13:06
Hi,

Indeed it should duplicate the resource. Doing it on the mixin will also solve the same bug occuring probably with employees :pager: .

**Closed** 2017-11-28 14:12 UTC
Labels: 11.0, confirmed, Logistics
