### ISSUE TITLE
Demo user cannot create MOs

### ISSUE THREAD

**Issue by LoisRForgeFlow** [odoo/odoo#28467] opened 2018-11-07 10:39 UTC
Impacted versions:
12 and 11 at least.

Steps to reproduce:
Enter demo.odoo.com as demo user and try to create a Manufacturing Order.

Current behavior:
A error raises as if the user were trying to write a product.

I debugged a bit and I can tell that it has something to do with an inverse field calculation that results in a write in the product variant of the MO (vals dict only has the `product_tmpl_id` of the product). I think that this write operation shouldn't be needed for the only purpose of creating the MO.

Expected behavior:
No error raises and Manufacturing Users can create MOs without extra rights.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/23449160/48126238-ecb86980-e280-11e8-9cae-f0fedca4a11d.png)

**Comment by lreficent** [comment] 2019-09-20 11:36
This is only an example, this issue happens in many operations, I think is an ORM issue. This is quite annoying when you try to restrict permissions and you find that is not easy to restrict the write permission for products.

@Yenthe666 Could you please ping the appropriate guy? Thanks

**Comment by Yenthe666** [comment] 2019-09-20 11:52
@jco-odoo or @sle-odoo could one of you two check this issue please?

**Comment by sle-odoo** [comment] 2020-01-08 16:25
I can't reproduce this issue, seems it was fixed in the meantime. Probably a related without a readonly true somewhere...

Regards

**Closed by sle-odoo** 2020-01-08 16:25 UTC
Labels: 11.0, 12.0, Logistics

**Comment by LoisRForgeFlow** [comment] 2020-01-09 11:27
Yes, I noticed that in v13 it was fixed and I've just checked now and seems that's the case for v11 and 12 as well.

Thanks for having a look.
