### ISSUE TITLE
[15.0] account: wrong action on Clicking on new Transaction

### ISSUE THREAD

**Issue by poonam2606** [odoo/odoo#92923] opened 2022-06-04 06:21 UTC
Impacted versions: 15.0

Steps to reproduce:

- Go to Account Dashboard
- Click on New Transaction on Cash 

![Screenshot - 2022-06-04T114540 599](https://user-images.githubusercontent.com/60427448/171987196-f72aab05-228c-49ae-8db1-69a153022b75.png)

Current behavior: It is opening form view of the Old Statement
![Screenshot - 2022-06-04T114751 967](https://user-images.githubusercontent.com/60427448/171987228-cfe21a54-e81e-4302-8689-6f41055e11dc.png)

Expected behavior: It should Open form view to Create a new Record

![Screenshot - 2022-06-04T114837 949](https://user-images.githubusercontent.com/60427448/171987252-bc215248-78ca-40c5-9b9e-df145e74c7b3.png)

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment] 2023-05-22 19:39
hi @poonam2606 ,
seems this is not able to reproduce now, so it may get fixed in between.
can you confirm from your side and if this is not happening, can you close the issue.
thanks

**Closed** 2023-05-23 13:18 UTC
