### ISSUE TITLE
[12.0] Partner_Autocomplete Odoo Server Error: Recursion Error

### ISSUE THREAD

**Issue by hiltonmw** [odoo/odoo#36037] opened 2019-08-23 21:14 UTC
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by hiltonmw** [comment] 2019-08-23 21:17
**Impacted version:** 12
**Steps to reproduce:**
Go to CRM > Sales Menu > Customers > New ... change the record type to Company and start typing in the name of a company / any company...  And I'm receiving this traceback log / error:
`Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo12/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo12/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo12/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo12/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo12/odoo/odoo/api.py", line 745, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File "/opt/odoo12/odoo/odoo/api.py", line 718, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo12/odoo/addons/partner_autocomplete/models/res_partner.py", line 108, in autocomplete
    'query': query,
  File "/opt/odoo12/odoo/addons/partner_autocomplete/models/res_partner.py", line 97, in _rpc_remote_api
    return jsonrpc(url=url, params=params, timeout=timeout), False
  File "/opt/odoo12/odoo/addons/iap/models/iap.py", line 52, in jsonrpc
    req = requests.post(url, json=payload, timeout=timeout)
  File "/opt/odoo12/odoo-venv/lib/python3.6/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/odoo12/odoo-venv/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/odoo12/odoo-venv/lib/python3.6/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/odoo12/odoo-venv/lib/python3.6/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/opt/odoo12/odoo-venv/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/opt/odoo12/odoo-venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/opt/odoo12/odoo-venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/opt/odoo12/odoo-venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/opt/odoo12/odoo-venv/lib/python3.6/site-packages/urllib3/connection.py", line 332, in connect
    cert_reqs=resolve_cert_reqs(self.cert_reqs),
  File "/opt/odoo12/odoo-venv/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 279, in create_urllib3_context
    context.options |= options
  File "/usr/lib/python3.6/ssl.py", line 465, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/usr/lib/python3.6/ssl.py", line 465, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/usr/lib/python3.6/ssl.py", line 465, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  [Previous line repeated 277 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object`
**Expected Behavior:** Web Search and/or no error

I've disabled any potential add-on / modules that may be causing the problem(s), I've downloaded the latest git and re-uploaded the "add-ons" folder overwriting what's existing, and I've uninstalled and re-installed the module... the only way I can get it to *not* throw an error is to disable the parter_autocomplete module all together

**Comment by hiltonmw** [comment] 2019-08-23 21:18
Also FWIW, I'm running this on Ubuntu Server 18.04

**Comment by pedrobaeza** [comment] 2019-08-24 07:26
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Yenthe666** [comment] 2019-12-03 07:53
Hi there,

Since there has been no extra information in quite a while I'm closing this issue.
Don't hesitate to respond back with detailed information and then we'll reopen this issue.

Regards,
Yenthe

**Closed by Yenthe666** 2019-12-03 07:53 UTC
Labels: Need information
