### ISSUE TITLE
Delivered Quantity do not update after reserve on Invoice

### ISSUE THREAD

**Issue by ossvn** [odoo/odoo#12917] opened 2016-07-27 06:08 UTC
Impacted versions: Version 9.0c (Community Edition)

Steps to reproduce: 

- Create new SO
- Click on Delivery > Validate
- Click on "Reserve" > Validate
- Turn back to SO Detail, column "Delivered Quantity" do not change the quantity corresponding to reservered quantity.

Expected behavior: Delivered Quantity should be reflect the actual quantity customer received. Like I send you 100 unit, you just receive 50 unit (so we will reserve 50 unit to stock).

Video/Screenshot link (optional):

<img width="1440" alt="screen shot 2016-07-27 at 1 07 44 pm" src="https://cloud.githubusercontent.com/assets/9199446/17165524/334c4996-53fb-11e6-9617-3235d676e42b.png">

<img width="1440" alt="screen shot 2016-07-27 at 1 07 38 pm" src="https://cloud.githubusercontent.com/assets/9199446/17165523/33492e64-53fb-11e6-9248-1e7e622e0304.png">

<img width="1440" alt="screen shot 2016-07-27 at 1 06 55 pm" src="https://cloud.githubusercontent.com/assets/9199446/17165526/334dfa70-53fb-11e6-84c4-d00fc776d4c7.png">

<img width="1440" alt="screen shot 2016-07-27 at 1 06 43 pm" src="https://cloud.githubusercontent.com/assets/9199446/17165528/334f0046-53fb-11e6-9179-ea4c7b35f81b.png">

"Delivered Quantity" should reflect and changed to 0

**Comment by dbo-odoo** [comment] 2016-07-28 14:37
Hello,

This is an implementation choice.

Reverse of deliveries are not "the normal flow" of the sales pipe. While they can certainly happen from time to time, we have decided that the "Delivered Quantities" should not reflect this reverse operation. One of the reason is that having a customer return does not mean that the delivery wasn't done (i.e. the products *were in fact* delivered). Another reason is that it would make the flow extremely complex, since you may already have invoiced this delivery - and if the product is set to be invoiced based on the delivered quantities, this would create inconsistencies between the invoiced amount and the delivered amount.

I will close this issue, you can still reply if you have questions about this or if my explanation is unsatisfactory, but this is not a bug (it was designed that way).

Regards,

@dbo-odoo

**Closed by dbo-odoo** 2016-07-28 14:37 UTC
