### ISSUE TITLE
[8.0] setup.py error

### ISSUE THREAD

**Issue by malatestay** [odoo/odoo#5527] opened 2015-03-02 12:04 UTC
fresh install give us this error when we do

"sudo python setup.py install" 

 File "/usr/local/lib/python2.7/dist-packages/odoo-8.0-py2.7.egg/openerp/cli/templates/default/controllers.py", line 1
    {%- set mod = name|snake -%}
     ^
SyntaxError: invalid syntax

**Comment by xmo-odoo** [comment] 2015-03-02 12:16
The issue is being worked on (it's matching `.py` files for bytecode compilation even though these are not valid python files). In the meantime, you can install with `--no-compile`

**Comment by aab-odoo** [comment] 2015-03-02 15:54
Hello,

This is fixed by 9ebfa11b8c1130423af2d188d7657c47e599e81b.

Regards

**Closed by aab-odoo** 2015-03-02 15:54 UTC
