### ISSUE TITLE
[11,12]Web : Discard button not work on editable tree view

### ISSUE THREAD

**Issue by ammarofficewla** [odoo/odoo#31827] opened 2019-03-13 16:43 UTC
Impacted versions:
11.0
12.0
Steps to reproduce:
1). Used to any editable tree view
2). click on create button 
3). add and search, filter in a tree view 
4) click on discard button 
Current behavior:
Discard button not work.
Expected behavior:
Discard button wok

**Comment by pedrobaeza** [comment] 2019-03-13 16:51
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by ammarofficewla** [comment] 2019-03-14 16:42
Helllo @pedrobaeza,
I have used attribute values view for a again generate issue,
I have attached one video link,
please check it  

https://drive.google.com/file/d/1bdZX8x_ASnmjDhgFngXGLCcj33yBrlRQ/view

**Comment by pedrobaeza** [comment] 2019-03-14 20:41
OK, I see the problem. Thanks for the extra info.

@ged-odoo something for your team.

**Comment by pedrobaeza** [comment] 2019-05-08 18:59
Friendly reminder. @aab-odoo are you aware of this?

**Comment by msh-odoo** [comment] 2019-05-09 04:58
@Tardo @pedrobaeza @sswapnesh Should be fixed with https://github.com/odoo/odoo/pull/32817

**Comment by pedrobaeza** [comment] 2019-05-09 07:13
Great, thanks, @msh-odoo !

**Comment by aab-odoo** [comment] 2019-06-21 12:26
Fixed by https://github.com/odoo/odoo/pull/33572 in 11.0

**Closed by aab-odoo** 2019-06-21 12:26 UTC
Labels: 11.0, 12.0, Framework
