### ISSUE TITLE
Basemodel union method validation error

### ISSUE THREAD

**Issue by mhamra** [odoo/odoo#29594] opened 2018-12-18 00:18 UTC
Impacted versions: 11, 12

Steps to reproduce: 
create an inherited model with different _name attribute (all fields in a new table but share behaviour)

Current behavior: 
union method raise an exception "mixing apples with oranges"

Expected behavior: t
he validation should not apply the way it is implemented when a model is inherited with different _name attribute. Current validation is

            if not (isinstance(arg, BaseModel) and arg._name == self._name):
                raise TypeError("Mixing apples and oranges: %s.union(%s)" % (self, arg))

arg._name is not the same than self._name so the exception is raisen.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2018-12-20 16:33
What is the `union` method? Can you put the code you are using for raising that problem?

**Comment by Yenthe666** [comment] 2019-01-28 12:50
Hi,

I'm closing this issue report as there has never been any feedback on the question. It also looks like a development issue. Don't hesitate to respond back with a reproducable example though.

Regards,
Yenthe

**Closed by Yenthe666** 2019-01-28 12:50 UTC
Labels: 11.0, 12.0, Framework, Need information
