### ISSUE TITLE
Procurement Buy/Manufacture from sale order does not cancel source document

### ISSUE THREAD

**Issue by JulioSerna** [odoo/odoo#26003] opened 2018-07-26 23:39 UTC
Impacted versions:
* 11.0

Steps to reproduce:
* Create product A with route **Buy**
* Create product B with route **Manufacture**
* Create sale order with sale order line with **Make to Order** and product A 
* Create in the same sale order another sale order linea with **Make to Order** and product B
* Validate sale order
* Cancel sale order

Current behavior:
**After confirm sale order**
sale order make one purchase order to product A
sale order make one manufacture order to product B

**After cancel sale order**
The purchase order line is not unlinked 
The Manufacture order is not cancelled 

Expected behavior:
**After cancel sale order**
the purchase order line should be unlinked
The Manufacture order should be cancelled 

Video/Screenshot link (optional):
https://youtu.be/2VBhvOtZ6ak

**Comment by nhomar** [comment] 2018-07-27 00:18
@JulioSerna can you link the OPW please? and check when this started to happen? because AFAICR this was working fine few weeks ago.

**Comment by mga-odoo** [comment] 2018-07-31 18:27
I don't things its a bug, Odoo clearly indicates to take you a manual action in form of activity on the Purchase order (not on RFQ). If RFQ you need to cancel it manually as it does not have a value until it is not confirmed, look at the video https://drive.google.com/file/d/1r3biFZh6xWFlEw-smeUyG3GwqNl-uGzo/view

For the Manufacturing Order, it is like the same since the beginning as there are many other documents related to the mrp order (purchase, sub mrp order, warehouse internal transfers) so it always required the manual intervention and has to be treated manually in such exceptional case.

**Comment by Yenthe666** [comment] 2019-02-11 13:28
Hi there,

I assume this has been answered by @mga-odoo (thanks!) and as there has been no feedback I'm closing this ticket.

Regards,
Yenthe

**Closed by Yenthe666** 2019-02-11 13:28 UTC
Labels: 11.0, Services
