### ISSUE TITLE
[9.0]SupplierInfo are not correctly set when generated from purchase order

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#11107] opened 2016-02-25 16:24 UTC
**Impacted versions:**
9.0

**Steps to reproduce:**
Create a product service
configure Odoo for advanced supplier info
Create a PO with 2 products
validate/receive the goods

**Current behavior:**
Supplier info is created with only variant => when you recall the product, the uom is not fine because it's coming from the template so the template MUST be set in the supplierinfo

**Expected behavior:**
supplierinfo created with variant AND template

**Comment by pedrobaeza** [comment] 2018-04-17 23:42
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-04-17 23:42 UTC
Labels: 9.0, Logistics
