### ISSUE TITLE
[11.0] Company logo doesn't change without clearing the browser cache

### ISSUE THREAD

**Issue by selurvedu** [odoo/odoo#29558] opened 2018-12-16 18:37 UTC
Essentially, this is an old issue coming from 8.0. https://github.com/odoo/odoo/issues/3035

Confirmed by 11 other users on 11.0:

https://github.com/odoo/odoo/issues/3035#issuecomment-340733913 (1 comment + 9 likes)
https://github.com/odoo/odoo/issues/3035#issuecomment-432801002

Impacted versions: 11.0

Steps to reproduce:

1. Create a new Odoo DB.
2. Change your company logo.
3. Ensure that the old logo is still there even after reloading the page.

Current behaviour: The old logo persists until the browser cache is cleared. Control+F5 does not always help (the old logo is still visible on some pages).

Expected behaviour: The new logo is visible immediately, or after pressing Refresh / F5.

Tested on Chrome and Firefox.

By the way, same thing happens with favicon.

**Comment by pedrobaeza** [comment] 2018-12-17 08:48
This is totally expected, as the company logo has a special controller that is intended to be cached for speeding up the load of the webpage in normal conditions, so you need to force to be reloaded without cache (Ctrl+F5) or to clear cache when you change it.

So closing as no issue, but intended behavior.

**Closed by pedrobaeza** 2018-12-17 08:48 UTC
