### ISSUE TITLE
Create: Contract Update Document Template

### ISSUE THREAD

**Issue by DEVANGISHINDE66** [odoo/odoo#38880] opened 2019-10-16 12:42 UTC
Impacted versions: v12

Video/Screenshot link (optional):
![123](https://user-images.githubusercontent.com/51401154/66920188-6edc1100-f040-11e9-9a53-53ccb7bd43b7.png)

**Comment by pedrobaeza** [comment] 2019-10-17 09:14
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by DEVANGISHINDE66** [comment] 2019-10-22 10:25
Version : Odoo 12 Enterprise
steps :

1. go to Recruitment menu.
2. create application
3. click Generate Offer Link Button
4. create new Contract Template with New Contract Document Template
5. it will give this error.
 I also checked on runbot few days ago with along this error.

**Closed** 2023-03-30 11:46 UTC
Labels: 12.0, HR
