### ISSUE TITLE
[BUG][OE] account_report : only one account 999999 in general ledger with multicompany 

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#18826] opened 2017-08-12 19:54 UTC
Impacted versions:
10 Enterprise (and maybe other)

Steps to reproduce:
- Create two company with two chart of account
- Generate the generale ledger in 01-01-2018 to 31-12-2018

Current behavior:
During the report the account 99999 (unaffected_earnings_account) is select without context of the company.
If your selecte two company, You must see two account 99999 (one for each company).
![image](https://user-images.githubusercontent.com/16716992/29243708-fed2d1b2-7fa5-11e7-9512-9ae70e6f5b4b.png)

Account configuration :
![image](https://user-images.githubusercontent.com/16716992/29243711-100c0bba-7fa6-11e7-959f-63a0cfe8ba5c.png)

How to fix :

Issue 1:
This methode compute for all accounts regardless selected companies
https://github.com/odoo/enterprise/blob/10.0/account_reports/models/account_general_ledger.py#L99

Issue 2:
This compute with unaffected results is regardless selected companies
https://github.com/odoo/enterprise/blob/10.0/account_reports/models/account_general_ledger.py#L198

Issue 3:
This search is regarless selected companies https://github.com/odoo/enterprise/blob/10.0/account_reports/models/account_general_ledger.py#L213

Issue 4:
The compute date is regarding the user current company and not the company selected in the report. If the fiscal date is different between company, it will produce a bad result.
https://github.com/odoo/enterprise/blob/10.0/account_reports/models/account_general_ledger.py#L171

Issue 5:
No limitation of number of account 'Current Year Earnings'. Contraint only one per company :
https://github.com/odoo/odoo/pull/17777
https://github.com/odoo/odoo/pull/17775

**Comment by qdp-odoo** [comment] 2017-08-21 08:21
Hi Florent, 

thanks for this bug report and the preliminary analysis you made.

However, I think that issues 1) and 2) are not occuring since in query_get() function we should filter correctly https://github.com/odoo/odoo/blob/10.0/addons/account/models/account_move.py#L1310 as we pass the company_ids in the context (https://github.com/odoo/enterprise/blob/10.0/account_reports/models/account_general_ledger.py#L35)

Issue 3 have been reported few days ago also via our support channel and is currently being fixed.

Issue 4 is confirmed. <ouch> 

Issue 5 seems to be even more problematic since it questions our design choice.

I'll be digging this

**Comment by fmdl** [comment] 2017-08-23 18:04
Dear @qdp-odoo
I have just see this commit https://github.com/odoo/enterprise/commit/ead41a32bdbf3c907ecc9f4d412b403ff9485807 about the issue 3. For me it is just a beginning of solution, it only solve if you select only one company.

I don't see in the code some think like that (maybe I'm wrong) :

```
ledger_account_data = []
for company in self.env.context.get('company_ids'):
    #find the 999999 account ofr the company
    unaffected_earnings_account = self.env['account.account'].search([
                ('user_type_id', '=', self.env.ref('account.data_unaffected_earnings').id), ('company_id', 'in', company)], limit=1)
     # compute the earning money of company
    unaffected_earnings_data = do_query_unaffected_earnings(..., company_id=company)
     # inject the data in the ledger
    ledger_account_data = (get_account_data(unaffected_earnings_data, unaffected_earnings_account)
```

**Comment by fmdl** [comment] 2017-08-23 18:23
@nim-odoo  Test on runbot with commit https://github.com/odoo/enterprise/commit/ead41a32bdbf3c907ecc9f4d412b403ff9485807 : works for one company, but not when you select two or more company.

![image](https://user-images.githubusercontent.com/16716992/29631463-024a1088-8840-11e7-8699-8ef9f1046dba.png)

![image](https://user-images.githubusercontent.com/16716992/29631498-1cbdc31a-8840-11e7-8fd0-7b61bc8168b3.png)

![image](https://user-images.githubusercontent.com/16716992/29631682-b68d4844-8840-11e7-87bd-3e2d45e9662c.png)


Idea : remove the possibilty to see more than two company.

**Comment by fmdl** [comment] 2017-11-07 17:24
@qdp-odoo any news about this issues ?

regards

**Comment by pedrobaeza** [comment] 2018-06-05 18:13
If this is still happening, please put an OPW ticket at https://www.odoo.com/help, as this is something specific of an enterprise module, which doesn't belong to this repository.

Closing the issue by the reason above.

**Closed by pedrobaeza** 2018-06-05 18:13 UTC
Labels: Accounting
