### ISSUE TITLE
Invoice don't change to Paid

### ISSUE THREAD

**Issue by DiegoLelis** [odoo/odoo#1950] opened 2014-08-24 08:29 UTC
Hi, I'm using odoo 8 RC1, at 90152 commits
I can create Invoices, and Validate.
I can register a payment, but, even if i register a payment with the value of the invoice.
The invoice don't change to paid.

**Comment by Yenthe666** [comment] 2016-06-03 10:42
Hi @DiegoLelis,

I cannot reproduce this issue anymore, this has been fixed somewhere along the line.
If you still face this issue please update your Odoo codebase and it should be fixed.
Closing this since I can no longer reproduce the problem.

Regards,
Yenthe

**Closed by Yenthe666** 2016-06-03 10:42 UTC

**Comment by qupro** [comment] 2016-06-21 09:21
This work for me [http://stackoverflow.com/a/37869043/5103424](http://stackoverflow.com/a/37869043/5103424) on a Odoo 9.0c-20160428 (Community Edition)

**Comment by Kimhak-Loem** [comment] 2017-05-05 06:27
Hi @DiegoLelis 

The problem that the invoice doesn't change its status to **paid** because the **Difference Amount** is not equal to 0 and **Payment Difference** is _Keep Open_ when you register the payment. 

![screenshot 64](https://cloud.githubusercontent.com/assets/25259408/25735290/7710214e-3194-11e7-88ac-f991fa8ece0e.png)

These are because of Account Receivable and Account Payable haven't enable yet, so you need to check that option for both account.
![screenshot 65](https://cloud.githubusercontent.com/assets/25259408/25735468/cb1425d2-3195-11e7-8b6a-7ea1a03889ab.png)
![screenshot 66](https://cloud.githubusercontent.com/assets/25259408/25735472/d0578750-3195-11e7-8d77-edf50686fa17.png)



Regards,
Kimhak
