### ISSUE TITLE
CustomerPortal

### ISSUE THREAD

**Issue by SimonasTr** [odoo/odoo#35996] opened 2019-08-23 06:44 UTC
Impacted versions:
v11
Steps to reproduce:
None
Current behavior:
Unresolved reference 
Expected behavior:
Resolved reference

I am not sure if this is done intentionally and I fail to understand the reason behind it, but in controllers in whole base modules CustomerPortal class is imported like this:
from odoo.addons.portal.controllers.portal import CustomerPortal, pager as portal_pager, get_records_pager

Where CustomerPortal is actually defined in addons.portal.controllers.portal . This cause unresolved reference to CustomerPortal class and therefore deriving your class from it makes no sense.

**Comment by pedrobaeza** [comment] 2019-08-23 07:16
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by SimonasTr** [comment] 2019-08-23 07:55
I failed to get any error for this 'issue'. The question is more from development side. If we create a controller for customer portal and we derive it from CustomerPortal(which is imported from odoo.addons.portal.controllers.portal. It somehow manages to find its' way to this class, despite that it does not exist in the described path)). I wonder if it could cause some issues in development.

**Comment by pedrobaeza** [comment] 2019-08-23 07:57
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Closed by pedrobaeza** 2019-08-23 07:57 UTC
Labels: Need information
