### ISSUE TITLE
[9.0] Invoice whit blank line after picking confirmation

### ISSUE THREAD

**Issue by gigidn** [odoo/odoo#11206] opened 2016-03-03 16:00 UTC
Impacted versions: 9.0

Steps to reproduce:
a) Create a "Stockable Product" whit invoice police set on delivery. 
b) Update qty on the product e.g. 3. 
c) Create a sale order for this product whit qty > stock qty - e.g. 5.
d) Confirm the order
e) Confirm picking and create backorder

Current behavior:

An invoice whit blank line will be create.

Expected behavior:

An invoice whit the lines correct set whit product and qty skipped.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment] 2018-01-16 09:55
Hi @gigidn,

Thanks a lot for your bug report.
I've just tried to reproduce this on the latest Odoo V9 but it seems to work fine out of the box now.
I'm closing this bug report as I can't reproduce it anymore. If you can still reproduce it on an official Odoo instance (at runbot.odoo.com) then please comment back with a video and/or more steps and I'll look into this again.

Regards,
Yenthe

**Closed by Yenthe666** 2018-01-16 09:55 UTC
Labels: 9.0
