### ISSUE TITLE
v13 Sorting By Price on shop (E-commerce)

### ISSUE THREAD

**Issue by shivam-gupta581** [odoo/odoo#52831] opened 2020-06-11 10:09 UTC
Impacted versions: V13

Steps to reproduce:

1.Go to Website -> Settings -> Sale pricing settings and enable Multiple sale prices per product
2.Go to Pricelists and add a product to one (with a different price to Sales Price)
3.Go to shop (eCommerce)
4.Make sure the pricelist in which you set the product is selected
5.Sort by price

Current behavior: The prices are displayed correctly, but the products are ordered by the Sales Price instead of the website price.

Expected behavior: Products should be sorted according to the website price

**Comment by pedrobaeza** [comment] 2020-06-11 15:48
@JKE-be can you take a look to this?

**Comment by sswapnesh** [comment] 2020-06-11 16:44
Duplicate of https://github.com/odoo/odoo/issues/27743

**Comment by pedrobaeza** [comment] 2020-06-11 16:45
OK, then we have the answer and should be closed as expected.

**Closed by pedrobaeza** 2020-06-11 16:45 UTC
Labels: 13.0, Website
