### ISSUE TITLE
Wysiwyg Editor not showing insert options

### ISSUE THREAD

**Issue by amindehghani** [odoo/odoo#58081] opened 2020-09-20 05:39 UTC
Impacted versions: v13 Community

Steps to reproduce: create a forum and try commenting on it

Current behavior: it does not show link and media plugin of  wysiwyg editor even though i have required karma.

Expected behavior: showing the link and media plugin for user that has full edit access

More information : I checked the JavaScript and it runs correctly. all the conditions run correctly based on my user karma but it does not show me the link and media buttons in  wysiwyg editor.

**Comment by pedrobaeza** [comment] 2020-09-20 10:49
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by amindehghani** [comment] 2020-09-21 11:40
Hi

![1](https://user-images.githubusercontent.com/16416527/93762291-1df37600-fc1c-11ea-8024-30168b30c631.png)

as you can see in the screenshot above in line 119 it checks for full edit access depending on Karma and returns true.
in line 126 it looks at this variable and if it's true it pushes link and media plugin to the array.
this part works correctly and without any errors.

![2](https://user-images.githubusercontent.com/16416527/93762417-627f1180-fc1c-11ea-876d-1f6a3c4c5e67.png)
but as mentioned in the screenshot above the div which media and link plugins will be placed is empty meaning that it is not loaded.

**Comment by pedrobaeza** [comment] 2020-09-21 11:42
Yeah, but you are analyzing code, and this is not user steps to get to a problem, and this is working in Odoo itself.

**Comment by amindehghani** [comment] 2020-09-21 11:47
odoo/addons/website_forum/static/src/js/website_forum.js:127
i changed this line to `toolbar.push(['insert', ['link', 'picture']]` from `toolbar.push(['insert', ['linkPlugin', 'mediaPlugin']]);` and it fixed the issue.

**Comment by pedrobaeza** [comment] 2020-09-21 11:51
OK, closing as it seems there's no issue at all with Odoo core, but custom needs.

**Closed by pedrobaeza** 2020-09-21 11:51 UTC
Labels: Need information

**Comment by amindehghani** [comment] 2020-09-21 11:54
well actually it is not custom needs it's not working right now and picture and links are not loading as they are supposed to load.

**Comment by pedrobaeza** [comment] 2020-09-21 11:56
But then provide that user steps... The karma system is put on purpose for avoiding spam, and this is how it supposed to work.

**Comment by amindehghani** [comment] 2020-09-21 11:57
i have the required karma but it is not showing these buttons that is the problem.

**Comment by pedrobaeza** [comment] 2020-09-21 12:00
@Yenthe666 have you found that problem using Odoo forums?

**Comment by Yenthe666** [comment] 2020-09-21 12:50
This was removed on purpose to avoid abuse of the tools actually.

**Comment by amindehghani** [comment] 2020-09-21 13:10
@Yenthe666 well it is available for users with required amount of karma. it is set to 30 and i am using the admin account which has the amount of karma needed to show these tools. but they are not working. the change above i sent earlier fixed this issue.

**Comment by Yenthe666** [comment] 2020-09-21 13:20
No, it is not. Here's a sample from my account (and I'm top 4 of the world);
![image](https://user-images.githubusercontent.com/6352350/93771552-f43b4e80-fc1d-11ea-89f3-53a144218a05.png)
