### ISSUE TITLE
Mailing list quoting display is broken

### ISSUE THREAD

**Issue by StefanRijnhart** [odoo/odoo#10298] opened 2016-01-05 09:56 UTC
It is not uncommon to respond on the mailing lists to messages with which one completely disagrees. Unfortunately, display of quoted parts is broken so that it is unclear who said what.

https://www.odoo.com/groups/community-59/community-15978789?mode=date&date_begin=&date_end=

Sent message source:

```
In-Reply-To: <CAEJSRZvWvud8c6Qp=wfNG6O1+wK3i_jb33qVrF7XyrgPNjnyUA@mail.gmail.com>
Content-Type: multipart/alternative;
 boundary="------------010708030901050303020804"

This is a multi-part message in MIME format.
--------------010708030901050303020804
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 7bit

On 05-01-16 05:52, Andreas Becker wrote:
> Yep Dominique that is true, as Postgres was the base of all same as
> Odoo and MySQL etc came much later. 
>
> Unfortunately many customers who ask for and ERP are with hosters
> which still don't provide Postgres and MySQL is available everywhere.
> Additionally Postgres seems for many like a big black box while MySQL
> is very well documented and understandable and it has PHPmyAdmin which
> is far ahead of any tool managing postgres DBs.
>

I don't care how much you are highlighting the advantages of Erpnext on
this Odoo mailinglist, but when you start implying that Postgres is not
well documented it really hurts.

-- 
Opener B.V. - Business solutions driven by open source collaboration

Stefan Rijnhart - Consultant/developer

mail: stefan@opener.am
tel: +31 (0) 20 3090 139
web: https://opener.am


--------------010708030901050303020804
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: 8bit

<html>
  <head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
  </head>
  <body text="#000000" bgcolor="#FFFFFF">
    <div class="moz-cite-prefix">On 05-01-16 05:52, Andreas Becker
      wrote:<br>
    </div>
    <blockquote
cite="mid:CAEJSRZvWvud8c6Qp=wfNG6O1+wK3i_jb33qVrF7XyrgPNjnyUA@mail.gmail.com"
      type="cite"><base href="https://www.odoo.com">
      <div dir="ltr">Yep Dominique that is true, as Postgres was the
        base of all same as Odoo and MySQL etc came much later.Â 
        <div><br>
        </div>
        <div>Unfortunately many customers who ask for and ERP are with
          hosters which still don't provide Postgres and MySQL is
          available everywhere. Additionally Postgres seems for many
          like a big black box while MySQL is very well documented and
          understandable and it has PHPmyAdmin which is far ahead of any
          tool managing postgres DBs.</div>
        <br>
      </div>
    </blockquote>
    <br>
    I don't care how much you are highlighting the advantages of Erpnext
    on this Odoo mailinglist, but when you start implying that Postgres
    is not well documented it really hurts.<br>
    <br>
    <pre class="moz-signature" cols="72">-- 
Opener B.V. - Business solutions driven by open source collaboration

Stefan Rijnhart - Consultant/developer

mail: <a class="moz-txt-link-abbreviated" href="mailto:stefan@opener.am">stefan@opener.am</a>
tel: +31 (0) 20 3090 139
web: <a class="moz-txt-link-freetext" href="https://opener.am">https://opener.am</a></pre>
  </body>
</html>

--------------010708030901050303020804--
```

**Comment by odony** [comment] 2016-01-05 12:12
Thanks Stefan!
@tde-banana-odoo here is a raw message that should help to improve the testcases you're working on :-)

**Comment by tde-banana-odoo** [comment] 2016-01-05 12:49
Hello,

It seems to be caused by the @ in the cite attribute of blockquote. There is an email adresses encoding step before calling the cleaner. This step seems to create the issue. I will look into it.

**Comment by tde-banana-odoo** [comment] 2016-02-05 10:56
Should be fixed in 9 at https://github.com/odoo/odoo/commit/8aff53733b6ca1dd6f8074834ada1baaab3910d5 .

**Comment by Yenthe666** [comment] 2018-03-06 15:00
This one should have been closed ages ago because of https://github.com/odoo/odoo/commit/8aff53733b6ca1dd6f8074834ada1baaab3910d5 so closing.

**Closed by Yenthe666** 2018-03-06 15:00 UTC
