### ISSUE TITLE
[10.0]Pos order is not created nor saved in client if user has no mail

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#20763] opened 2017-11-07 13:52 UTC
Impacted versions:
* 10.0 fdb2f17 [I18N] add VAT es_MX translations

Steps to reproduce:
Create a user and check that its related partner has no email set.
Opene a session and make an order

Current behavior:
Having this in the logs :
```
Could not fully process the POS Order: Unable to send email, please configure the sender's email address.
```
The order is not saved in the client => no transaction at all is logged.

Expected behavior:
The lack of email shouldn't be an issue  :
- Add a control that the user who is opening the session has an email
- Don't lose the pos.order
- if no email is set on the user, add a generic email or add the mail of the user that opened the session 

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment] 2018-01-05 08:57
Hi @flotho,

Thanks for the report.
I've just tried this on the latest V10 but it seems to work fine.
The user:
![image](https://user-images.githubusercontent.com/6352350/34602034-9c15f1b4-f1fe-11e7-80c7-e57a738d47e2.png)
The related contact that has no e-mail:
![image](https://user-images.githubusercontent.com/6352350/34602046-ac3110ba-f1fe-11e7-9261-d8605d251fb8.png)
The POS order I've made with the user James in a new POS:
![image](https://user-images.githubusercontent.com/6352350/34602081-c1a4b8f2-f1fe-11e7-94a4-caf59e3fd510.png)

Am I missing something? Can you try again on a runbot please?

Regards,
Yenthe

**Comment by Yenthe666** [comment] 2018-04-18 09:15
Hi there,

I'm closing this bug report as I was not able to reproduce this and there has been no feedback in quite a while.

Regards,
Yenthe

**Closed by Yenthe666** 2018-04-18 09:15 UTC
Labels: 10.0, Point of Sale
