### ISSUE TITLE
Documentation request: customisation of the record string in the Gantt view

### ISSUE THREAD

**Issue by frlanxpertiz** [odoo/odoo#43941] opened 2020-01-24 15:58 UTC
Taking for example the Gantt view on planning.slot for the planning app, I didn't find any info in the docs about the possibility of changing on which fields the string of the slot is calculated (role, employee and dates in this case). If it's not supported then it would be a nice feature to have in the future.

**Comment by mart-e** [comment] 2020-05-18 05:42
Hi,

All the gantt documentation is at https://www.odoo.com/documentation/13.0/reference/views.html#gantt
The gantt view you mention has for definition
```xml
<gantt js_class="planning_gantt"
    form_view_id="1608"
    date_start="start_datetime"
    date_stop="end_datetime"
    default_group_by="employee_id"
    default_scale="week"
    color="color"
    plan="false"
    scales="day,week,month,year"
    precision="{'day': 'hour:full', 'week': 'day:full', 'month': 'day:full', 'year': 'day:full'}"
    decoration-info="not is_published"
    decoration-warning="publication_warning and is_published"
    decoration-danger="overlap_slot_count &gt; 0"
    display_unavailability="1"
    thumbnails="{'employee_id': 'image_128'}">
...
</gantt>
```

The employee is from the gantt definition but the fact that as slot is displayed as "4:00 PM - 12:00 AM Bartender" for instance is actually the `name_get`, it's not linked to the gantt view (you can see it when you open a slot).

I hope it helps.

Closing as a code question and not a bug report.

**Closed by mart-e** 2020-05-18 05:42 UTC
Labels: Documentation
