### ISSUE TITLE
Odoo v8 : error when trying to print a report (account.invoice)

### ISSUE THREAD

**Issue by yboujraf** [odoo/odoo#7058] opened 2015-06-13 14:28 UTC
Dear,

I tried to print a new report created for account.invoice.

We got this error message from Odoo : 

MissingError

One of the documents you are trying to access has been deleted, please try again after refreshing.

![screenshot 2015-06-13 16 27 15](https://cloud.githubusercontent.com/assets/6151258/8144656/19a6c610-11e9-11e5-8bb3-df4ca4ca9930.png)

Any help will be great

BR Youssef

**Comment by yboujraf** [comment] 2015-06-13 14:28
Please find the link create a new report :+1: 
http://odoo.guide/report-design-workshop/#comment-116

BR
Youssef

**Comment by Yenthe666** [comment] 2016-05-27 09:04
Hi @yboujraf,

This looks like some custom report? I cannot reproduce any issues with the default invoice report and since you link to a tutorial this looks like custom development.
Closing this issue since it is not about the default Odoo code and I think you've also solved your own problem.

Regards,
Yenthe

**Closed by Yenthe666** 2016-05-27 09:04 UTC
