### ISSUE TITLE
Mail Campaign not using altered email template (Tried in Odoo 8 and Odoo 9)

### ISSUE THREAD

**Issue by jaynegit** [odoo/odoo#9154] opened 2015-10-20 11:12 UTC
Process causing problem:

Create new mail template under Settings, Email, Templates. 
Save it.
Make a change to that template.
Save Change.
Use the template as part of a campaign. (Lead Automation, Campaigns, Create activity and set template to use.)

The campaign is sending out an email like the original - not including the change that was made.

**Comment by pedrobaeza** [comment] 2018-04-06 00:44
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue. I think the problem is on translations, but that part was already handled.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-04-06 00:44 UTC
Labels: 9.0, Services

**Comment by Yenthe666** [comment] 2018-04-06 05:31
Good answer @pedrobaeze!
