### ISSUE TITLE
[14.0] Sale - date_order always set to Datetime.now()

### ISSUE THREAD

**Issue by Kacer89** [odoo/odoo#74007] opened 2021-07-20 08:06 UTC
Impacted versions: 14.0
Module: Sale
Model: Sale.py

Steps to reproduce: 
User has option to change 'Quotation Date' (date_order) when creating SaleOrder (in draft), however when user hit confirm the Order the value will change to current date

Expected behavior:
I would expect that the date would remain, so something like this (line 918):

 `    def _prepare_confirmation_values(self):
        return {
            'state': 'sale',
            'date_order': self.date_order or fields.Datetime.now()
        }
`

**Comment by pedrobaeza** [comment] 2021-07-20 08:31
This is the intended behavior, as the quotation date has no more sense when the order is confirmed.

Closing as no issue, but intended behavior.

**Closed by pedrobaeza** 2021-07-20 08:31 UTC
