### ISSUE TITLE
[12] Scroll bar should not be Printed on Invoice Report

### ISSUE THREAD

**Issue by HarshitTEmipro** [odoo/odoo#32879] opened 2019-04-23 13:00 UTC
Here I attach the sample pdf of the scroll bar visible in invoice report
![Screenshot from 2019-04-23 18-27-23](https://user-images.githubusercontent.com/35089697/56582853-da937300-65f5-11e9-8acf-8c11257d4aee.png)

**Comment by pedrobaeza** [comment] 2019-04-23 13:42
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Closed** 2019-04-23 13:45 UTC
Labels: Need information

**Comment by sswapnesh** [comment] 2019-04-24 15:11
Similar to https://github.com/odoo/odoo/issues/27438 (But in Different report)
