### ISSUE TITLE
Date field value not getting updated because of formatDate error in TransientModel while working fine on models

### ISSUE THREAD

**Issue by sandeepksrana** [odoo/odoo#23740] opened 2018-03-19 12:33 UTC
Impacted versions:
In **Odoo 11** there is a big problem in date fields in **Wizard or TransientModel** forms date field value not getting updated because of formateDate error

**Value.format not a function** 

have a look here at` /web/static/src/js/fields/field_utils.js`
```

function formatDate(value, field, options) {
if (value === false) {
return "";
}
if (field && field.type === 'datetime') {
if (!options || !('timezone' in options) || options.timezone) {
value = value.clone().add(session.getTZOffset(value), 'minutes');
}
}
var date_format = time.getLangDateFormat();
return value.format(date_format);
}
```

I have gone through whole process I have created a` model and a wizard` both having two field `name ( char) or date ( date field)` setup and put in `default_get` method `name='test' and date='2018-03-02'` in both. while in model its getting updated and in wizard its showing error vaule.format is not function.

I have go through the above js file and check the` typeof of javascript object` when in the form its says object and when wizard it says String**`. very strange and a big issue.

have anyone checked it or found this issue.

**Comment by Yenthe666** [comment] 2018-03-19 12:45
@ged-odoo this is one for your team. 😉

**Comment by aab-odoo** [comment] 2018-03-19 14:28
Duplicate of #23672

**Closed by aab-odoo** 2018-03-19 14:28 UTC
Labels: 11.0, Framework

**Comment by Yenthe666** [comment] 2018-03-19 14:37
Oh wow, @sandeepksrana you really covered up `value.format` well.
This is the third time that I am telling you not to duplicate bug reports and keep making new issues.
If I see you doing this again I will lock every single bug report you make from now on.

**Comment by sandeepksrana** [comment] 2018-03-20 05:07
@Yenthe666 Hello  wahoo thats great no one is replaying, that means  its will not be resolved from your end.  @fpodoo no one really care about it.

**Comment by Yenthe666** [comment] 2018-03-20 07:05
@sandeepksrana to get a few things clear:
1. I do not work for Odoo and do this completely voluntarily.
2. The Github tracker is used for bugs in the Odoo community and are solved in a best effort case. If you have an enterprise license you can report it at odoo.com/help.
