### ISSUE TITLE
Duplicate Contacts on Message Composer

### ISSUE THREAD

**Issue by cormaza** [odoo/odoo#18468] opened 2017-07-26 18:35 UTC
Impacted versions: 10.0, master, saas

Steps to reproduce: You activate lead management on sales, when you make a message with composer, if lead doesn't have partner asigned, show form to create partner, and assign on mail composer this is correct, but if you make another message with composer show again partner form to create

Current behavior: You create always the same contact when you made twice or more times composer message

Expected behavior: First time made partner, assign to lead or record, for example always find a field that name is partner_id and second time you get same partner that you create before

Video/Screenshot link (optional):

**Comment by odony** [comment] 2017-07-28 08:47
I can't reproduce this, the first time you send a message the system will ask you to create a new partner, but if you send another message the system will see that a message was previously sent and will not ask you to create a partner again. No need to assign it to the partner_id field, which is not always correct anyway.
If you don't see this behavior, please demonstrate it with a short video, and comment again so we can reopen. Thanks.

**Closed by odony** 2017-07-28 08:47 UTC
