### ISSUE TITLE
odoo client Error

### ISSUE THREAD

**Issue by INDIVYAsree** [odoo/odoo#44643] opened 2020-02-05 10:57 UTC
Impacted versions:ODOO13

Steps to reproduce:
I Tried to change The View of Recruitment Kanban to some thing.I got the following error.

Current behavior:
Traceback:
TypeError: Cannot read property 'context' of undefined
    at Class._evalArchChild (http://ats.headrun.com/web/content/970-8f6affa/web.assets_backend.js:1480:334)
    at http://ats.headrun.com/web/content/970-8f6affa/web.assets_backend.js:1488:514
    at Array.map (<anonymous>)
    at Class._parseSearchArch (http://ats.headrun.com/web/content/970-8f6affa/web.assets_backend.js:1488:462)
    at Class.init (http://ats.headrun.com/web/content/970-8f6affa/web.assets_backend.js:1479:2978)
    at Class.prototype.<computed> [as init] (http://ats.headrun.com/web/content/969-ba67567/web.assets_common.js:3860:488)
    at new Class (http://ats.headrun.com/web/content/969-ba67567/web.assets_common.js:3861:65)
    at Class._createControlPanel (http://ats.headrun.com/web/content/970-8f6affa/web.assets_backend.js:1070:157)
    at Class.getController (http://ats.headrun.com/web/content/970-8f6affa/web.assets_backend.js:1066:678)
    at Class.prototype.<computed> [as getController] (http://ats.headrun.com/web/content/969-ba67567/web.assets_common.js:3860:488)

Expected behavior: Open Recruitment Application in ODOO13

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/55536324/73835858-2b4a2480-4834-11ea-92b6-475b9339d094.png)

**Comment by gdgellatly** [comment] 2020-02-05 10:59
Change it back

**Comment by INDIVYAsree** [comment] 2020-02-05 11:00
It is not opening to change. and I am New to ODOO

**Comment by INDIVYAsree** [comment] 2020-02-05 11:05
> Change it back
It is not opening to change. and I am New to ODOO.

suggest me what to do

**Comment by INDIVYAsree** [comment] 2020-02-05 11:11
![error](https://user-images.githubusercontent.com/55536324/73836912-5766a500-4836-11ea-8058-11ba295c99bd.png)

How to remove those two views

**Comment by Yenthe666** [comment] 2020-02-05 12:34
Clearly not a bug in default Odoo but misuse of the system (or the lack of knowledge). Closing as this doesn't belong here, please ask help on the official help forums.

**Closed by Yenthe666** 2020-02-05 12:34 UTC
