### ISSUE TITLE
Pricelist rule based on 'Supplier prices on the product form' is not correctly implemented

### ISSUE THREAD

**Issue by pedrobaeza** [odoo/odoo#4506] opened 2015-01-02 20:06 UTC
Steps to reproduce it
-----------------------------
* Initiate a runbot instance.
* Activate "Manage pricelists per supplier" on *Configuration > Configuration > Purchases" screen and apply.
* Go to products, select "iPad Mini", and on *Procurements* tab, *Suppliers* section, open "ASUSTeK" line.
* Put a price line with 10 € and no quantity.
* Go to *Purchase > Pricelists > Pricelists*, and create a new pricelist called "Special pricelist" with one version and two rules in it:
  * One with sequence 5 and based on "Supplier prices on the product form".
  * Another one with sequence 99 and based on "Other pricelist" and select pricelist "Default Purchase Pricelist (EUR)".
* Go to *Purchases > Requests for Quotation" and create a new one.
* Select any supplier different from ASUSTeK (for example, Axelor).
* Change pricelist to "Special pricelist (EUR)".
* Add a line with "iPad Mini" product.

Expected result
---------------------
* "iPad Mini" price is 800 €, that corresponds to cost price.

Obtained result
---------------------
* "iPad Mini" price is 10 €, that corresponds to ASUSTeK specific price defined in product form.

Explanation of the bug
-------------------------------
This is provoked by the code on https://github.com/odoo/odoo/blob/8.0/addons/product/pricelist.py#L309 (`if not seller and product.seller_ids:`) that assigns the first *product.supplierinfo* record if any other matches.

What it must do is to continue to the next rule to match against another pricelist rule.

Fix
----
In PR #4505 it's the solution for this bug.

**Comment by pedrobaeza** [comment] 2015-02-17 19:03
Any news on this?

**Comment by LeartS** [comment] 2015-02-24 08:43
I don't think it's a bug, I think it's the intended behaviour: the first rule matches, so it is executed and gets the price based on suppliers. If there is a supplier equal to the partner it uses that, if not it uses the first one. Keep in mind that that part of code is executed on sale pricelists also, it wouldn't make sense to skip the rule because there are no suppliers that match the partner (which would be a customer in this case!)

**Comment by pedrobaeza** [comment] 2015-02-24 08:59
Hi, Leonardo,

How can this not be a bug? This breaks the general rule system in what pricelists are based: if a rule doesn't match, pricelist engine must continue with the next. And also produces akward results, getting prices for a supplier that it's not the one you want.

This converts to something critical when with our module https://github.com/odoomrp/odoomrp-wip/tree/8.0/product_supplierinfo_for_customer, you use the same table and pricelist engine for defining specific prices for customers: you want to have some specific prices for some customers, but you want that the rest uses the price calculated from the following rules.

**Comment by LeartS** [comment] 2015-02-24 09:23
The rule does match, you didn't specify any restriction. The restrictions are all in the first section of a pricelist rule view: product category, product template, single product, minimum quantity.
It's just that you think "based on supplier price" implies (or should imply) the restriction "partner is a supplier for this product", while Odoo probably didn't think it like that (and I see reasons for both behaviours, but only for purchase pricelists).

I have not tested it, but I'm almost sure your patch breaks all sale pricelist rules based on the supplier price, except if you have that module installed. You may be basing your patch on that specific module use case.

Even for purchase pricelist, I'm not sure you want to consider the rule only if you're buying from a supplier of that product. For example, imagine some products which i buy only from a single trusted supplier. One week, for some rare reason, my usual supplier can't provide me the product, but he redirects me to another one and guarantees me he will make me the same price.
So I create a purchase order to the new supplier and set as pricelist the pricelist of my usual supplier.

This way I can buy from someone using the prices from my usual supplier without having to add the new supplier to all the products I'm going to buy, copying all the prices, do the order and then delete all the new supplierinfo I've added just for that sale order.

**Comment by pedrobaeza** [comment] 2015-02-24 09:31
My patch doesn't break anything, even not having the module I mention.

And I must insist: it's making an exception in the way pricelist engine works for the rest of the rules. I prefer consistency over the user case you are proposing (although valid, it's quickly fixed putting the same price on cost price).

Let's see what others think.

**Comment by LeartS** [comment] 2015-02-24 10:01
I still don't see what exception/inconsistency is making. As I said, the rule does match because you didn't specificy any restriction. There are no restrictions based on the partner, all restrictions are based on the product and the quantity.

I've tested the ocb branch and it does indeed break sale pricelists.
To test edit the default pricelist, add a rule based on supplier price and a markup of 2, set a supplier for a product with price 100.
Create a sale order using the default pricelist, I expect a price of 200 (supplier price * 2), I get 1 (standard price * 1, the default rule of the default pricelist)

**Comment by pedrobaeza** [comment] 2015-02-24 10:56
As stated before, this is not breaking pricelists in my opinion. I'm thinking in this as another rule, which when the matching criteria doesn't match, it continues to next rule. You already have this with product and product category. If the product for matching doesn't meet any of those, system continues with next rule.

What I expect from the test case you have made is 1, not 200 (anyways, what is markup? do you mean surcharge?).

**Comment by LeartS** [comment] 2015-02-24 11:42
Sorry, by markup I meant the multiplcative factor of the rule, `price_discount`.

I don't fully understand your point of view. If a rule defined with "supplier price on product form" as base rule would match only if the partner is a supplier for that product, you couldn't create sale pricelist rules based on supplier prices. That's because when evaluating a sale pricelist, the partner is the customer and, except in very rare cases, a customer is not also a supplier for that product.

The way I see it, "based on supplier price" is just an alternative to based on standard price or cost price, it's not an additional restriction for rule matching.

**Comment by pedrobaeza** [comment] 2015-02-24 11:57
No, forget about customers. Think in just suppliers (the standard). You have a pricelist with these rules:

Priority: 5 - Based on "Supplier prices on product form"
Priority: 999 - Based on "Cost Price"

Then, at product __Ice cream__, I add supplier __ASUSTeK__, with a price of 20, and the cost price I define is 30.

When I make a purchase order of __Ice cream__ to ASUSTeK, I get with or without my patch a price of 20.

But when I make a purchase order of __Ice cream__ to any other supplier, for example, __Axelor__, I expect a price of 30, because I don't have any specific entry for this supplier on the product form, so I expect the pricelist engine continues to next rule, that it's to get the cost price (30). That doesn't happen, and this is the inconsistency, because with the rest of "based on" options, the behaviour is to continue to next rule.

You have talked about the user case when someone wants the price of the default supplier. Thinking about it again, I don't think this is the most usual case. Each company might want a differente value (I have one that doesn't want to put nothing - e.g. 0 -, for example). Your case or this one can be accomplished with subsequent rules in the pricelist, if the engine works consistently.

**Comment by wtaferner** [comment] 2015-02-24 12:22
I agree with @pedrobaeza - it would be incorrect to take a dedicated partner price for someone else if not defined...the fix LGTM :+1:

**Comment by LeartS** [comment] 2015-02-24 12:34
Customer is the standard also. I'm talking about customers as in sale pricelists. This patch breaks that: i.e. I can't have pricelist rules (for sale pricelists) based on the supplier prices. Think about a very simple company that just resells what it buys for 1.5x the price the supplier has made them. How would you implement that with this patch?

For purchase pricelists, as I've said, your proposed behaviour (don't match the rule if the partner is not a supplier for that product) makes sense but is a diffrent behaviour from the one currently implemented and not a "bugfix".

> That doesn't happen, and this is the inconsistency, because with the rest of "based on" options, the behaviour is to continue to next rule.

Can you make an example? that's not my experience. When based on standard price or cost price it doesn't skip to the next rule, even if those prices are 0 (undefined). When based on another pricelist is a particular case as is the only option to apply multiple rules to a product.

**Comment by clonedagain** [comment] 2015-02-24 12:50
Maybe if you could expose your use cases with unit tests it would help validate the possible solutions,  or rule out one of the demands?

**Comment by pedrobaeza** [comment] 2015-02-24 12:52
Are you talking about me, Lionel?

**Comment by jbeficent** [comment] 2015-02-24 15:53
I believe @pedrobaeza proposal should be restricted only to the purchase pricelists.
In the sale pricelists scenario I agree with @LeartS 
And it is not to say that this is breaking uniformity. On the contrary!

In Odoo there's an inherent assumption that the supplier of a product in purchase orders created from procurement orders is always that defined in product.supplierinfo with lowest sequence. It is hardcoded, in fact!

As a consequence, when you create a sale pricelist based on "supplier prices on the product form" the application is inherently assuming that same procurement rule that supplierinfo with lowest sequence is the one to use. Also hardcoded to take the first!

Then, when you create a sales order using a sale pricelist that is based on supplier prices, the application should always fetch the first supplier to look for a valid price.

But on the purchase scenario, when you create a PO what you're looking is at is totally different! You are interested to fetch the price that the supplier entered in the PO offers for that product, irrespective of the position that this supplier happens to be in product.supplierinfo. That is because, contrary to creating PO's from procurement orders, when you create a PO manually the user decides who is going to supply. And the application should respond appropiately.

My 2 cents..

**Comment by anajuaristi** [comment] 2015-02-24 22:34
+1 @pedrobaeza @jbeficent 

Tested case on runbot. From my point of view it's a very clear bug. 

I'm buying something to a supplier that is not defined on supplierform list and I specifically set a rule to take product_cost on that case but system is taking always first supplier price. It's incorrect, just because that price is not corresponding to supplier on purchase order. Just because of that would be incorrect.

**Comment by ybofr** [comment] 2015-02-25 19:04
+1 @pedrobaeza @jbeficent @anajuaristi 

Hi all,
This bug is massive and I also sent it to Odoo. It is wrong that the rules are not respected. The system should not be allowed to choose any supplier or just take the first supplier if you are trying to purchase with a supplier not present in the product form.

This would give the impression that a price for that very supplier exists and this is not the case. So, from a functional point of view it is totally incorrect and my customers also do not want to accept such a bug.

Regards
Eva P.

**Comment by ybofr** [comment] 2015-02-25 19:12
@LeartS 
"The way I see it, "based on supplier price" is just an alternative to based on standard price or cost price, it's not an additional restriction for rule matching."

To base the sales price on any supplier price does not make any sense from a business point of view. You would not add a markup to the price of a specific supplier unless you are sure you want to purchase this from this very supplier. In that case, you would rather, from an accounting and functional point of view, use a standard price, rather than a supplier price. To use standard prices in purchasing is absolutely best practice in many industries, when the prices do not change a lot or when they change slowly.

**Comment by ybofr** [comment] 2015-02-25 19:18
@jbeficent The fact of hard coding the selection of the first supplier has caused many issues with my customers. I believe this is a bad idea and we just live with it, because, it is there. It's difficult to manage when you have a high number of products, as you have to make sure that on every single product the sequence number is correct.
The real life shows, you enter the suppliers as they come and you do not always check the sequence number.
Secondly, the system always make you believe you have a price for a supplier, where you do not have a price for that very supplier. It is not transparent and this is also something that should be corrected. What would be more logical is to use the "cost price" instead of one supplier price. This way, you could break all these strange dependencies, probably the legacy of shortcuts from the past.

**Comment by pedrobaeza** [comment] 2015-02-25 19:23
@ybofr, @jbeficent, but that's not strictly true. If you activate bids for the product, you will get from the procurement a bid, not a purchase order of the first supplier. 

Then, you can use https://github.com/OCA/purchase-workflow/tree/8.0/purchase_requisition_auto_rfq for getting automatic purchase orders for each supplier of the list.

**Comment by ybofr** [comment] 2015-02-25 19:26
@pedrobaeza , yes, this is what we did. We had to activate it on all products, to overcome the problem and we also installed the module you are citing. But the problem should not have happened in the first place ;-)

**Comment by anajuaristi** [comment] 2015-02-25 19:36
+1 @ybofr

**Comment by ybofr** [comment] 2015-02-25 21:49
Someone suggested that the sales price could be purchase price + margin. This is a standard case, but normally, not when you purchase from multiple sources. The business case is that you have a supplier for specific products and that the supplier gives you a price list. You would then, manage the supplier pricelist for that very supplier and make the sales price dependent of that very price list.
No business is able to maintain such price lists directly in the product, as it is long and inefficient to manage. For example, entering the price of 10 products in Odoo takes 10-20 minutes. The same job in SAP takes 1-5 minutes and you can also define the unit of measure of the pricing, for instance, you can say 5€ per 12 pieces. 

So, just to say, there is still a lot of work that needs to be done on the pricing. This will be an interesting challenge for the next years.

**Comment by jbeficent** [comment] 2015-02-26 01:33
I agree with @yobr that management of pricing is far better in SAP. Been SAP consultant in Sales and Distribution and CRM for years! Would love to see a similar approach to pricing and account determination in Odoo... Guess that one must make it happen somehow! @yobr, someday we should talk and see if we can prepare a poposal..

You can create more easily supplierinfo records using modue 'product_by_supplier' available for v7:
https://github.com/OCA/purchase-workflow/tree/7.0/product_by_supplier

This module could even be improved to create directly records within the tree view.

On the subject of being able to use sales pricelist being on supplier price + margin, I agree with @pedrobaeza that it is not fully consistent, because you might end up crearing a bid instead of a PO if you indicated so in a producthttps://github.com/OCA/purchase-workflow/tree/7.0/product_by_supplier. https://github.com/OCA/purchase-workflow/tree/7.0/product_by_supplier.

In a retail business, you can think that you have the option of using this strategy, but always must be conscious that then, the product cannot be set-up to create bids! That would end up being insonsistency between marketing and sourcing strategies. 

Introducing a restriction that would check this and throw an error message to the user may be helpful, as it would prevent such inconsistency.

This product's default supplier sourcing strategy os what Odoo can offer now. Nan-Tic implemented in the past a sourcing strategy based on selecting the supplier that offered the lowest price when creating PO's from procurement orders.

If multiple product sourcing strategies existed, and you could choase which to use they could be used by the pricing engine to offer the price for the supplier determined, based on that strategy. If this strategy was then used in the procurement order, you would run a vendor selection consistent with the sale price that you offered in the first place.

Just replacing the current hardcoded rule with a more flexible mechanism could provide huge benefits.

**Comment by ybofr** [comment] 2015-02-28 06:15
Hi Jordi,

Good to see we have a similar experience. But I'm an allrounder and certified in FI/CO as well as MM/PP. But +10years of implementing SD for large companies, like Novartis, etc.

So, I would be happy to work with you on the price list proposal as this is a very limiting factor, even for smaller companies in Odoo. Not only is it difficult to maintain, but it also does not really have the basic functionality I am looking for.

Related to Retail and pricing. A retail company does not work the way described (I used to be a retailer, so, it's also my own experience), by choosing a price in the product master. Normally, the very first condition for a retail company to base the sales price on the purchase price is that this purchase price is valid for a given period. Then the retailer can adapt his prices. Therefore, the period of validity is a key information. Secondly, if there is a discount based on the quantity purchased by the supplier, the retailer does not give directly that very discount. For instance, if he has a discount of 5% when he purchases 10 at a time, he does not want to give exactly 5% discount to the customer. He wants to have the freedom of choosing the discount he is giving, so he is not likely to use the supplier's price directly. Of course he could, but it would not be ideal for him.

The other problem with the supplier's price at the moment: if you want to base your sales prices on supplier's prices, you may also sell your stock at a totally different price than the one that you have purchased, as the change of prices on the product master are not linked with any date.

For these reasons, and also because, the existence of a supplier's price cannot be guaranteed, it is a bad practice to use the supplier's price in the sales. But of course, with the correction of Pedro, the supplier's price can be used for purchasing, especially if you do not have many products.

Note that even if the procurement is going to be created as a call for bid, the single request for quotation should choose the prices in the product master (in case, it works properly, as I have not really tested it thoroughly)

Regards

---
Eva P.

Get free Odoo training in our youtube channel http://www.youtube.com/user/ybofr

**Comment by mart-e** [comment] 2015-04-01 15:42
Hello everybody,

I agree with @pedrobaeza, it's a bug and the patch is correct.
However it's a change of behaviour (meaning: some pricelists that used to fetch a price could no longer find it, or get different one). We should avoid so that it will not be merged in version 8 but in master.

Regarding the question if this should or have an impact on a sale pricelist, I think the scenario is wrong. The sales pricelist that are based on supplier price should look for the cost price, not the supplier price. I don't see valid scenario where I would want to use the supplier price and not the cost price (and especially not the first supplier only). If you put the product is real time or average price, you will get the supplier price.

Let me know if you can find real life scenario we have missed where this patch would break something.

**Comment by mart-e** [comment] 2015-04-01 15:53
Merged at cd03150999c687c5108912d6ec8047d619e98417.
Thanks

**Closed by mart-e** 2015-04-01 15:53 UTC

**Comment by ybofr** [comment] 2015-04-01 20:55
HI Martin,
A pricing should be flexible enough to allow the users to do what they really want. In the case of Buy2Order, it is usual to have a pricelist given by the supplier that can be different from the cost price and that you want to apply as a basis for a calculation.
The problem in sales is that everyone has the freedom to define how he wants to calculate his price. There should be not too many constraints in terms of price calculation for sales.
