### ISSUE TITLE
Odoo 13 Installation Bug Windows Linux

### ISSUE THREAD

**Issue by mtsoftware2016** [odoo/odoo#38572] opened 2019-10-13 10:49 UTC
Hello ,
I don' t understant why close my post without giving me any solutions ..
I had install odoo 13 in Windows 10 by your installer official and also the same it contains bugs I can't reach general settings or adding extra addons . 
So please before close this post give me solutions I need to start work in Odoo 13
thanks.

**Comment by pedrobaeza** [comment] 2019-10-13 12:50
I closed it because this is not a beginner forum for assisting people in installing things on their own. For that you have... the forums. If you prove the problem is due to software or the packaging, then it can fit, but you are not even putting the traceback, log or whatever can lead to knowing that, so unless you do it, this will be closed in a few time.

**Comment by mtsoftware2016** [comment] 2019-10-13 13:36
hello sir I'am not beginner and I didn't ask you to show me how to install .
I had download odoo 13 for windows and after the installation I run Odoo and I find problem ..

**Comment by pedrobaeza** [comment] 2019-10-13 13:40
And the error? The traceback? The log?

**Comment by mtsoftware2016** [comment] 2019-10-13 13:40
no erros on log this is the problem

**Comment by mtsoftware2016** [comment] 2019-10-13 13:42
this is a screenshot look at my setting how it's like
https://imgbbb.com/image/LVSGNG

**Comment by mtsoftware2016** [comment] 2019-10-13 13:44
when i activate mode developer I don't find the options to update liste of apps this is another problem

**Comment by pedrobaeza** [comment] 2019-10-13 13:46
I'm doubting this is due to the windows installer, and it's working perfectly in https://runbot.odoo.com. If you don't provide the Odoo log for looking for possible problems, I'm afraid it won't be possible to provide any solution.

**Comment by Yenthe666** [comment] 2019-10-14 06:40
I've did the test with the latest Odoo 13 installers on a clean Windows 10 environment and everything works just fine. As @pedrobaeza suspected it seems to be an issue with your environment.

**Closed by Yenthe666** 2019-10-14 06:40 UTC
Labels: 13.0, Need information

**Comment by haotangio** [comment] 2019-12-13 08:57
@mtsoftware2016 I got same issue. If you install 1 Odoo app, the General Settings will appear.

**Comment by mtsoftware2016** [comment] 2019-12-14 17:14
Send me messagr in skype maki turki pseudo

Le ven. 13 déc. 2019 à 9:57 AM, Hao Tang <notifications@github.com> a
écrit :
