### ISSUE TITLE
Unable to add google maps widget in website

### ISSUE THREAD

**Issue by jabirmisnedtech** [odoo/odoo#68186] opened 2021-03-22 06:50 UTC
What are the steps to reproduce your issue?
Create website
Add google API Key in website settings
Go to website and click edit
Click on Google Map block and drag it inside website
Click inside google maps to change settings
It disappears

What is the current behavior that you observe?
Google maps block disappear on clicking inside it

What would be your expected behavior in this case?
Working Google maps block

Video/Screenshot link (optional):
https://user-images.githubusercontent.com/45730318/111950891-f65e6700-8af3-11eb-9b2c-2cd7fc6b4455.mp4

Support ticket number submitted via odoo.com/help (optional):
#2488738

**Comment by pedrobaeza** [comment] 2021-03-22 08:54
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by jabirmisnedtech** [comment] 2021-03-22 09:28
Hello @pedrobaeza ,
I am able to recreate the issue in  runbot. Please watch the video.

https://user-images.githubusercontent.com/45730318/111968214-f9fce880-8b09-11eb-8da4-5155ae0c55a2.mp4

**Comment by NICO-SOLUTIONS** [comment] 2021-03-24 09:13
Have a look to this issue... ([#62932](https://github.com/odoo/odoo/issues/62932))

**Comment by JKE-be** [comment] 2021-04-19 11:56
Opw has been closed.

**Closed by JKE-be** 2021-04-19 11:56 UTC
Labels: 14.0, Website

**Comment by JKE-be** [comment] 2021-04-19 12:36
Just tested now on runbot 14.0 and it works as expected.

Reminder to make it work:
   - need to enable billing on your account
   - need to enable "Maps JavaScript API" to have the small cart into the right column
   - need to enable "Maps JavaScript API" and "Place API" to use the "google maps" snippets

You can enable 3 together.
Don't forget to restrict your keys ;)
