### ISSUE TITLE
Can't install/update modules  and update apps list on odoo 12

### ISSUE THREAD

**Issue by rs430** [odoo/odoo#31685] opened 2019-03-07 23:56 UTC
Impacted versions: 12.0

Steps to reproduce: update apps list 

Current behavior: Error message : Record does not exist or has been deleted.

Expected behavior: Update apps list and install new modules

Video/Screenshot link (optional):

![capture](https://user-images.githubusercontent.com/6604852/53997582-0a1d1780-413d-11e9-8bec-641145568569.PNG)

![odooerror](https://user-images.githubusercontent.com/6604852/53997677-6849fa80-413d-11e9-922a-bf3fba3e5711.PNG)

**Comment by pedrobaeza** [comment] 2019-03-08 00:09
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Yenthe666** [comment] 2019-04-09 06:12
Hi there,

We haven't recieved any feedback in over a month.
We're closing this issue off because of this. Don't hesitate to comment back with more information if you can still reproduce the problem on the latest code.

Regards,
Yenthe

**Closed by Yenthe666** 2019-04-09 06:12 UTC
Labels: Need information
