### ISSUE TITLE
[12] website_forum: Missing user/karma validation on toggle_correct

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#34566] opened 2019-07-03 18:58 UTC
Impacted versions: 12

Steps to reproduce: Example on https://www.odoo.com/forum/help-1/question/how-to-get-product-website-url-for-multi-websites-ecommerce-152036

Current behavior: One can accept/reject answer even if it is not posted by him or Approved by author

Expected behavior: should be some Validation on it

Video/Screenshot link (optional):

![Screenshot from 2019-07-04 00-26-35](https://user-images.githubusercontent.com/16624719/60617930-6a258100-9df2-11e9-8a4c-22242b447773.png)

Cc: @JKE-be @rdeodoo

**Comment by sswapnesh** [comment] 2019-07-03 19:01
and also some Issue with Answer Counter on same page
![Screenshot from 2019-07-04 00-31-01](https://user-images.githubusercontent.com/16624719/60618164-17989480-9df3-11e9-964b-f0cbb69df9f3.png)

**Comment by pedrobaeza** [comment] 2020-04-08 18:02
Is this solved?

**Comment by sswapnesh** [comment] 2020-04-24 16:29
I think No (I didn't tried again but I didn't find any new commit there)

**Comment by JKE-be** [comment] 2020-04-27 12:22
If i'm not wrong it is fixed.
Since in the PR of @Esperax we exlicit add a check to allow a user that have downvoted, to upvote now.

Can you confirm @Esperax ?

**Comment by Esperax** [comment] 2020-04-27 12:47
The answer counter is solved, but I didn't know about the first bug mentioned above.
And what upvotes and downvotes have to do with that ? Am I missing something ?

**Comment by xO-Tx** [comment] 2020-11-10 17:36
Hello @sswapnesh
Actually, the expected behaviour is based on a karma validation :
- Answer can be accepted when user is an admin or his karma >= required karma value (default : 20 if you're the question owner otherwise 500).

I tested this in v12.0 and it seems to work as intended :)

**Comment by Yenthe666** [comment] 2020-11-10 17:38
Yeah I think it has been fixed. Closing unless we hear back it is not :)

**Closed by Yenthe666** 2020-11-10 17:38 UTC
Labels: 12.0, Website
