### ISSUE TITLE
WYSIWYG attachment can cause MemoryError if there are lots of existing photos in ir.atachment

### ISSUE THREAD

**Issue by AdrianTeng** [odoo/odoo#43113] opened 2020-01-10 10:42 UTC
Impacted versions: 13.0

Steps to reproduce:
Having a database with >10000 photos in `ir.attachment`, attempt to open WYSIWYG editor's attachment panel (e.g. from editing `blog.post`)

Current behavior:
The `search_read` query attempts to read all attachments in 1 go, which causes significant delay of the popup. Due to lack of any indication that a load is on-going, users would repeatingly click the attachment button again, resulting in multiple large query request. Usually this ends in Odoo server running out of memory and restart.

Expected behavior:
Ideally the attachment popup's `search_read` should only do a limited amount of read, and uses `offset` to fetch more images when required.

The fix probably should happen at around [here](https://github.com/odoo/odoo/blob/13.0/addons/web_editor/static/src/js/wysiwyg/widgets/media.js#L226-L227), using keyword `limit` with a reasonable amount. One also needs to store an `offset` and send the value over here + making the "Load more..." button to increment the `offset`

**Comment by Elkasitu** [comment] 2020-01-10 12:51
@Gorash @Zinston

**Comment by Elkasitu** [comment] 2020-01-10 12:53
@AdrianTeng looks like you have a pretty good solution in mind, a PR is welcome :)

**Comment by AdrianTeng** [comment] 2020-01-11 10:07
PR submitted -- would like to have your input on this @Elkasitu  :)

**Comment by Elkasitu** [comment] 2020-01-13 08:44
Thanks for the PR, I've tagged it and pinged the right people to take a look at it, hopefully it won't be too long, cheers :)

**Comment by Zinston** [comment] 2020-01-13 11:12
@Elkasitu Do you mean the above ping of @Gorash and I?
I'm not really familiar with the python side of Blog/Attachment. @Gorash is on vacation for the rest of the month. But anyway maybe @qsm-odoo or @seb-odoo is actually more the expert here? Correct me if I'm wrong but I believe they implemented changes to the "Load more..." system for v13.

**Comment by seb-odoo** [comment] 2020-01-13 12:07
I have done some refactoring in that file but none was related to the attachment query as far as I can remember.

I feel like this issue might already be there in v12 and maybe before, seeing as the code there was basically the same https://github.com/odoo/odoo/blob/12.0/addons/web_editor/static/src/js/widgets/widgets.js#L363

That said I'm out of the loop regarding recent plans and improvements for the editor, so I will leave it at that.

Since this is the base editor and not a website snippet, I feel like @dmo-odoo would be the right person to review the related PR?

**Comment by Elkasitu** [comment] 2020-01-13 12:31
@Zinston I pinged you and @Gorash because I know he has historically worked on the web editor and you mostly because you were in the git blame, I also know @qsm-odoo has worked on it but he touches on a lot of stuff so I didn't know if he'd be the right person and / or if he has the time.

If any of you feel willing / have the time to review the PR, then go ahead, if not we can wait until @Gorash's return, I don't think the issue is super urgent as it can be worked around by increasing `limit-memory-hard`

Alternatively, @AdrianTeng if you have an Enterprise subscription you may open a ticket at www.odoo.com/help where the request will be forwarded to our bugfix team and they'll be able to either review your PR or merge their own fix in a more reasonable timeframe

**Comment by qsm-odoo** [comment] 2020-01-13 15:15
Hello, the problem has always been there and was considered as a limitation. Unfortunately, the suggested fix is incorrect for multiple reasons. A big one is that there is post-query sorting in JS (because it is not a simple SQL ordering) which would thus be broken if we add limits and offsets.

We will discuss the problem with the team and come back to you as soon as possible.

**Comment by AdrianTeng** [comment] 2020-01-15 12:16
@qsm-odoo I can see `self.options.firstFilters` and `self.options.lastFilters`. Are they related to the user input of name search of the photos?

If that's the case then I propose the solutions:

The name input should send the search criteria to server, sorting should be done at SQL level. If the criteria has changed, `self.attachments` should be completed replaced instead of extend

**Comment by qsm-odoo** [comment] 2020-02-17 09:57
@sdegueldre Here is the customer issue. As discussed, we can remove the first and last filters feature then you can implement a smarted `read` of db attachments to solve all problems.

**Closed** 2020-03-03 17:52 UTC
Labels: 13.0, Web editor, Website

**Comment by sdegueldre** [comment] 2020-03-04 07:59
@AdrianTeng alright, this should be fixed in all supported versions from 11.0 to 13.0 (still working on the port to 13.2 and master), thank you for your report and your patience!
