### ISSUE TITLE
empty column in tree view saas-13.5,master

### ISSUE THREAD

**Issue by sangitassh** [odoo/odoo#57983] opened 2020-09-17 17:32 UTC
Impacted versions:
saas - 13.5 ,master 
Steps to reproduce:
 
 go to expense 

Current behavior:

empty column status and submit 

Expected behavior:
there should be no empty column 

Video/Screenshot link (optional):
https://drive.google.com/file/d/1gGuzpddhVAz7naOPubpRnu0IuoQmgBdK/view?usp=sharing

**Comment by sswapnesh** [comment] 2020-10-08 17:00
@sangitassh  That is empty because there are no Attachments, That column is used to View attachments from list view.
![Screenshot from 2020-10-08 22-29-55](https://user-images.githubusercontent.com/16624719/95490418-d4de4880-09b5-11eb-90d7-7fb7f8890ff8.png)

**Comment by Yenthe666** [comment] 2020-10-09 06:25
I guess it _could_ use a label in the tree view and something like "No attachments" if there are none but its nothing huge to me

**Comment by mart-e** [comment] 2020-11-19 06:46
Hi,

This is not new from 14.0, it was already there before (at least in 12.0 and 13.0) and indeed is filled only when having a value. It hasn't a label because, it's actually not a column but a button. You can see the same kind of columns in manufacturing orders, etc.

Closing as not a bug but don't hesitate to submit a PR if you have suggestions to improve this.

**Closed by mart-e** 2020-11-19 06:46 UTC
Labels: 14.0
