### ISSUE TITLE
[9.0]Register Payment => Payment Type always show no select

### ISSUE THREAD

**Issue by medMethnani** [odoo/odoo#11370] opened 2016-03-16 17:14 UTC
Impacted versions: Version 9.0c-20160302 (Community Edition)

Steps to reproduce: 

Current behavior: When a Payment type exist with Manuel or Check , it show empty selection see attched.

Expected behavior: When a Payment type exist with Manuel or check it need to show a selection button to select Mauel Or Check. 

Video/Screenshot link (optional):
![pay](https://cloud.githubusercontent.com/assets/3436150/13821628/a32df528-eba2-11e5-83f5-0f09a998a79f.png)

**Comment by csnauwaert** [comment] 2018-02-28 11:11
Hello,

I can't reproduce your issue on the latest v9.0 community, therefore I'm assuming it has been fixed and closing this issue. If that is not the case and you still have the problem. Feels free to comment.

Best regards

**Closed by csnauwaert** 2018-02-28 11:11 UTC
Labels: 9.0, Accounting
