### ISSUE TITLE
[11.0] Error blank page when change language to Vietnamese

### ISSUE THREAD

**Issue by minhhq09** [odoo/odoo#20211] opened 2017-10-16 16:36 UTC
Hi all,

I have the same issue with https://github.com/odoo/odoo/issues/20150. In my case, when i load language to Vietnamese and reload page. Odoo show blank page.

This is error log:

2017-10-16 15:32:55,295 7288 ERROR ERP4TTXJSC werkzeug: Error on request:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\werkzeug\serving.py", line 209, in run_wsgi
    execute(self.server.app)
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\werkzeug\serving.py", line 197, in execute
    application_iter = app(environ, start_response)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\service\server.py", line 254, in app
    return self.app(e, s)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\service\wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\service\wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 1298, in __call__
    return self.dispatch(environ, start_response)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 1272, in __call__
    return self.app(environ, start_wrapped)
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\werkzeug\wsgi.py", line 600, in __call__
    return self.app(environ, start_response)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 1473, in dispatch
    result = ir_http._dispatch()
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\website_sale\models\ir_http.py", line 15, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\auth_signup\models\ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web_editor\models\ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\http_routing\models\ir_http.py", line 397, in _dispatch
    result = super(IrHttp, cls)._dispatch()
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\utm\models\ir_http.py", line 20, in _dispatch
    response = super(IrHttp, cls)._dispatch()
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\ir\ir_http.py", line 212, in _dispatch
    return cls._handle_exception(e)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\website\models\ir_http.py", line 159, in _handle_exception
    return super(Http, cls)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\ir\ir_http.py", line 182, in _handle_exception
    return request._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 761, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\ir\ir_http.py", line 208, in _dispatch
    result = request.dispatch()
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 820, in dispatch
    r = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 522, in load_locale
    momentjs_locale = f.read()
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
  odoo.tools.convert.ParseError: "charmap" codec can't decode byte 0x9d in position 2075: character maps to <undefined>

I seen comment of @ongood and based on that. I fixed below:

- odoo/addons/web/controllers/main.py
- Change line 521:
with open(os.path.join(addons_path, 'web', 'static', 'lib', 'moment', 'locale', code + '.js'), 'r') as f:
to
with open(os.path.join(addons_path, 'web', 'static', 'lib', 'moment', 'locale', code + '.js'), 'rb') as f:

It's worked for me.

**Comment by Yenthe666** [comment] 2017-10-17 06:16
Hi @minhhq09,

Thanks for the report.
I've made a PR for your case at https://github.com/odoo/odoo/pull/20227 - it has to be reviewed and merged by somebody from Odoo.

**Comment by xmo-odoo** [comment] 2017-10-17 14:01
Dupe of #20075

**Closed by xmo-odoo** 2017-10-17 14:01 UTC
Labels: 11.0
