### ISSUE TITLE
V9 - POS : Vertical Scrollbar not responding on Android

### ISSUE THREAD

**Issue by mslokhat** [odoo/odoo#9788] opened 2015-11-27 13:44 UTC
Hi,

categories and products lists cannot be scrolled vertically  .

the scrollbar is displayed but no actions works.

rgds

**Comment by jorenvo** [comment] 2015-11-30 07:36
What version of Android are you using? What browser are you using?

**Comment by mslokhat** [comment] 2015-12-01 07:25
Hi, any latest androiid version 

android 4.4  with google chrome 46
it has same issue with native browser inside Android

**Comment by jorenvo** [comment] 2015-12-01 08:26
I've tested it on Android 5.1.1 with Chrome 46 and I can't seem to reproduce the issue. Scrolling through the product list works fine. Just to be clear, you're talking about scrolling this:

http://i.imgur.com/tZsdVEe.jpg

up and down right?

**Comment by mslokhat** [comment] 2015-12-02 15:04
Yes and also when showing Category pictures
on a PC it works. on a Tablet the scrollbar is locked

i need to us large scrollbars to be able to scroll but it is very slow.

**Comment by mslokhat** [comment] 2015-12-02 15:05
the scroll on category pictures is locked

**Comment by jorenvo** [comment] 2015-12-03 09:41
Hi,

So I tested it in Chrome 46 and the native Android browser. I cannot reproduce the issue at all. I'm not even sure I understand the issue anymore. You mention that the Vertical Scrollbar isn't responding. But you don't have to actually use the scrollbar if you have a touchscreen interface. You just swipe over the product list, you don't drag the actual scrollbar. Is your issue resolved by disabling the 'Display Category Pictures' option? Could you perhaps make a video showing the issue?


Kind regards,
Joren

**Comment by mslokhat** [comment] 2015-12-03 10:47
Hi,
swipe does not not work either and the scroll also does not respond.

ie , if you have lots of categories which out of the screen display, you cannot scroll down to select categories

you get this behavior when using child categories . 

i will try to make a video

**Comment by jorenvo** [comment] 2016-02-29 12:10
Hi,

This issue should be solved with c23be8917c4da41853feea3cb1e3fd27afad2c1f.


Kind regards,
Joren

**Closed by jorenvo** 2016-02-29 12:10 UTC
