### ISSUE TITLE
[10] wrong path for Etherpad configuration in Project / Task

### ISSUE THREAD

**Issue by zeroheure** [odoo/odoo#16828] opened 2017-05-05 09:13 UTC
Impacted versions:
10
Steps to reproduce:

1. Activate rich notes (pads) in Projects configuration.
2. Create a task
3. Edit the task and look at the instructions for Pad credentials in the description tab

Current behavior:
Instructions says 
« Please enter your Etherpad credentials through the menu 'Settings > General Settings > Configure your company data', in the 'Configuration' tab of your company. » 
Which is wrong, Pads credentials are setup in Settings > General Settings

Expected behavior:
Instructions would says « Please enter your Etherpad credentials through the menu 'Settings > General Settings »

**Comment by Yenthe666** [comment] 2017-05-08 06:31
Hi @zeroheure,

Thank you for your report.
I've tested this on the 10.0 and it is indeed under 'Settings > General settings' now.
@mart-e can I just make a PR to change this message in the source code?

Regards,
Yenthe

**Comment by zeroheure** [comment] 2017-05-08 10:16
There is some complains about the path in Odoo forum. See for example
https://www.odoo.com/forum/help-1/question/project-please-enter-your-etherpad-credentials-110793

Unfortunatly nobody takes time to report!

**Comment by Yenthe666** [comment] 2017-05-08 10:31
@zeroheure I'm happy you did. When I get feedback from mart-e I'll fix it. 😄

**Comment by mart-e** [comment] 2017-05-09 15:22
Hello,

It was already fixed in master at f5d53190d5f37186b6722a497ee9612ba3ffedfe
Created an English translation in 10.0 at ecf3555dee1

**Closed** 2017-05-09 15:21 UTC

**Comment by barry1955** [comment] 2017-12-06 00:38
I am new to Odoo.
We are using the bitnami odoo stack. 
I do not get the setting page described in most of the answers I have seen online.
I have checked on the server and while I can find the Etherpad python files, I am at a loss at hoe to use it. 
What I want is to use the same text editor as we use for internal notes. It works and is good look and feel. 
Can I reset Odoo to use only one text editor please? (I subscribe to the Highlander Rule ferociously)

**Comment by zeroheure** [comment] 2017-12-12 11:57
Please ask in forum, not in bug report. Don't forget to provide details about your setup : which Odoo version, which OS, what you did to install Odoo.

**Comment by Yenthe666** [comment] 2018-04-04 15:06
@mart-e this is actually unclear. Why is it under `Settings > Technical settings > Calendar > API credentials` in 10.0?
@miqmago this has been fixed in 11.0 though:
![image](https://user-images.githubusercontent.com/6352350/38316215-7dff0b6c-382a-11e8-931f-5290b68ee4a7.png)

**Comment by miqmago** [comment] 2018-04-04 17:09
Thanks, yes I'm using 10.0 from docker image (maybe it is not updated?)

(Sorry I've read my post again and realised that it could be misunderstood: I think it is not intuitive but of course I was joking... finally I was really happy to have found it after several trials navigating through settings ;)

**Comment by Yenthe666** [comment] 2018-04-04 17:57
It is the same in the last 10.0 ;) It should be like in V11 under the project settings which is logical honestly. Won't be changed in 10.0 because of stable policy I believe though :(

**Comment by zeroheure** [comment] 2018-04-04 20:56
Documentation and help should at least be updated. It will not break compatibility in a stable version but hel admins to find the config.

**Comment by mart-e** [comment] 2018-04-05 07:34
Hello,

Why searching so far in sub-menus? ;-)
It is available in Settings > General Settings menu. No need to be in debug mode.
The API Credentials menu is actually useless since affb77e (doing the same than General Settings) and can probably be removed in master.

**Comment by Yenthe666** [comment] 2018-04-05 07:56
@mart-e you know what I say, if we can fix it in master right away we should. 😉

**Comment by zeroheure** [comment] 2018-04-05 08:30
@mart-e  Because the documentation indicate a wrong place ("Settings > General Settings > Configure your company data"). It is  a small but very annoying bug that **should** be fixed, it will not break the stable.

**Comment by miqmago** [comment] 2018-04-05 09:06
I've went crazy looking for `Settings > General Settings`. Can't find where it is!

![captura de pantalla 2018-04-05 a les 11 04 52](https://user-images.githubusercontent.com/1849488/38356878-5477baae-38c1-11e8-8552-dfa165d751eb.png)

**Comment by miqmago** [comment] 2018-04-05 09:09
OMG!!! there it is!! right now I've found... The problem is that as you can see, when a menu has no submenus, it is clickable, but when it has submenus, it is not... But the color and look like is the same!!

My mistake it was in front of mine, but have to repeat myself that this is not intuitive... Maybe it is not the right place to post this, but having the same look and feel for a menu that is clickable and another one that is not, it does not feel right...

**Comment by zeroheure** [comment] 2018-04-05 09:12
Good point

**Comment by zeroheure** [comment] 2018-04-05 09:25
@mart-e I understand that, but this is a message for admin, yet admins speak english. And more : what is the most ennoying : a translation problem or a wrong instruction ?

**Comment by zeroheure** [comment] 2018-04-05 09:30
@mart-e  sorry, my mistake, I wrongly read your post.

**Comment by mart-e** [comment] 2018-04-05 09:31
No, instance administrators do not necessarily speak English. The majority of our new instances on odoo.com are created in another language than English.
It is not because developers are expected to speak English than we should expect end users to speak it too.

If you want to adapt the text in another language, please join our [translation effort](https://www.transifex.com/odoo/public/) (it was already corrected in French).
