### ISSUE TITLE
[10.0] Possibility of duplicate parent_left / parent_right values when concurrently altering stock.quant.package records

### ISSUE THREAD

**Issue by netice** [odoo/odoo#25459] opened 2018-06-25 14:24 UTC
Impacted versions:
all version

Steps to reproduce:
use multi process such as oca jobs model to create stock.quant.package concurrently.
you will get some package has the same parent_left and parent_right.
when search one record with 'child_of' operator the other will in result 
cause some method such stock method error.

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by netice** [comment] 2018-06-25 14:47
@odony

**Comment by Yenthe666** [comment] 2018-06-27 13:10
Hi @netice,

Could you please provide a sample script or reproducable way? The information is a bit too little.

**Comment by gurneyalex** [comment] 2019-01-31 16:40
@Yenthe666 @odony 

Steps to reproduce on Odoo 10.0:

Start 2 xterms

In terminal 1,  run `odoo shell --no-xmlrpc` and  run the following commands:
```
>>> pack1 = self.env['stock.quant.package'].create({})
>>> print pack1.id, pack1.parent_left_id
```

In terminal 2, run `odoo shell --no-xmlrpc` and  run the following commands:
```
>>> pack2 = self.env['stock.quant.package'].create({})
>>> print pack2.id, pack2.parent_left_id
```
You will notice that both stock.quant_package have the same value for parent_left. 

In both shells, you can run `self.env.cr.commit()` and save to database. 

After that, if you have `quant1` in the first package, and `quant2` in the second package, and you print `pack1.children_quant_ids`, you will see both `quant1` and `quant2`. Same if you print `pack2.children_quant_ids`, although `pack1.parent_id` and `pack2.parent_id` are `False`. 

I'm pretty certain this can be achieved by clicking on "put in pack" simultaneously in 2 browser sessions. 

Bonus : if you use PICK  + SHIP in your workflow, and click "put in pack" simultaneously on 2 PICK pickings, then when you SHIP, the first picking to ship will get extra moves created for the quants found in the ghost included package from the other SHIP :cry:

**Comment by gurneyalex** [comment] 2019-01-31 16:45
hello @rco-odoo I think https://github.com/odoo/odoo/pull/14562 is intended to fix this, am I correct ?

**Comment by odony** [comment] 2019-01-31 18:50
I guess this is a duplicate report of #14493, which was fixed in several parts:
- one of the root causes was a weakness of the parent_store mechanism in some concurrent situations, fixed as of 12.0 via #22558  - not possible to backport due to changes in the data structure.
- the other root cause was a misuse of the parent_store mechanism specifically for `stock.quant.package`, and this was fixed in 11.0 via #14694

Unfortunately the bug originates from commit 4952b96f in 8.0, so the issue is still present in 8.0, 9.0 and 10.0 too. As 10.0 is still supported, I've just created #30745 to backport the second fix in 10.0.

@gurneyalex @netice would you mind verifying that the PR fixes the issue as expected? Thanks!

**Comment by gurneyalex** [comment] 2019-01-31 20:41
@odony thanks for the ultra fast reaction. I'll check this tomorrow first thing in the morning. And then I'll try to fix the few hundred affected packages and related pickings...

**Comment by Yenthe666** [comment] 2019-10-07 09:09
I guess we can close this one off now guys. V10 is no longer supported and it looks like you guys made own commits to fix it.

**Closed by Yenthe666** 2019-10-07 09:09 UTC
Labels: 10.0, 9.0
