### ISSUE TITLE
record rules access error

### ISSUE THREAD

**Issue by ramitalat** [odoo/odoo#6574] opened 2015-05-05 23:35 UTC
Hi.
I tried to organize our company's warehouses and locations to the desired structure from our company's point of view to locations such that, (Input, Stock, Packing, and Output).
Then I defined a separate record rule for each location, to differentiate between each location moves and the others. Foe a while, everything was going well, but surprisingly, it get a strange error for the storekeeper ... 

"AccessError
The requested operation cannot be completed due to security restrictions. Please contact your system administrator.
(Document type: stock.move, Operation: read) "
From the first glance I expected that the record rule missed the read permission, but that was wrong. The record rules have the four permissions set!

Can anyone help?
Regards,

**Comment by ramitalat** [comment] 2015-05-08 01:47
Any help from this community?

**Comment by lukebranch** [comment] 2015-05-08 04:07
@ramitalat ,

Are you using multi-company features? If you are not i'd make sure you have a backup of database and filesystem first and then try switching off multi-company in Settings >> General Settings.

I think this is not a bug, but an access rights configuration issue. I'd recommend closing this issue and hitting the forums first to see if anyone else has run into anything similar.

**Comment by ramitalat** [comment] 2015-05-08 23:31
Dear @lukebranch ,
I'm not using the multi-company feature. It's one company having one warehouse with many locations as described above.
I considered this an issue because of the error content. It points out that the problem is the "read" while the record rule has the full permissions!

**Comment by ramitalat** [comment] 2015-05-10 13:10
Still no response!!! 
I'm wondering about the supposed support service this community should provide!

**Comment by lukebranch** [comment] 2015-05-13 13:06
@ramitalat ,

interesting. I've managed to resolve the access rights error previously by switching off multi-company settings, however I never got to the root cause of the issue. Hopefully Odoo SA responds soon on one of the channels you've posted this issue to.

**Comment by ramitalat** [comment] 2015-05-17 02:39
@lukebranch 
Here is the log file associated with this problem...

Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 940, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/addons/stock_account/stock_account.py", line 272, in action_done
    res = super(stock_move, self).action_done(cr, uid, ids, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/addons/stock/stock.py", line 2379, in action_done
    quant_obj.quants_move(cr, uid, quants, move, ops.location_dest_id, location_from=ops.location_id, lot_id=ops.lot_id.id, owner_id=ops.owner_id.id, src_package_id=ops.package_id.id, dest_package_id=quant_dest_package_id, context=ctx)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/addons/stock/stock.py", line 410, in quants_move
    quant = self._quant_create(cr, uid, qty, move, lot_id=lot_id, owner_id=owner_id, src_package_id=src_package_id, dest_package_id=dest_package_id, force_location_from=location_from, force_location_to=location_to, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/addons/stock_account/stock_account.py", line 155, in _quant_create
    quant = super(stock_quant, self)._quant_create(cr, uid, qty, move, lot_id=lot_id, owner_id=owner_id, src_package_id=src_package_id, dest_package_id=dest_package_id, force_location_from=force_location_from, force_location_to=force_location_to, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/addons/stock/stock.py", line 502, in _quant_create
    rounding = move.product_id.uom_id.rounding
  File "/opt/odoo/odoo-server/openerp/fields.py", line 823, in __get__
    return record._cache[self]
  File "/opt/odoo/odoo-server/openerp/models.py", line 5913, in __getitem__
    return value.get() if isinstance(value, SpecialValue) else value
  File "/opt/odoo/odoo-server/openerp/fields.py", line 55, in get
    raise self.exception
AccessError: ('AccessError', u'The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\n\n(Document type: stock.move, Operation: read)')


Have you any ideas about it?

**Comment by loiclavoie** [comment] 2015-05-26 01:17
I have the same issue, but your log seem's to miss a couple of line right before.
I got two line right before that stating two different id of record rules:
"openerp.models: Access Denied by record rules for operation: create on record ids: [54], uid: 7, model: account.invoice.li" (in my case, it happen when creating an invoice)

When I check the record rule, each one failing look like this (the id change at every attempt):
['|',('company_id','=',False),('company_id','child_of',[user.company_id.id])]

I'm guessing each run doesn't call the same rule (for some reason).

**Comment by ramitalat** [comment] 2015-05-28 20:01
This is not good news...

**Comment by blaggacao** [comment] 2015-07-31 17:48
Is this still an issue? 

@ramitalat If you feel, this is rather configuration, than a source code issue, you might consider closing this. Else, I would suggest, to elaborate your description, to make it convenient for others to reproduce this exact error. If you need any guidance on how to start, make sure to check first here: https://github.com/odoo/odoo/blob/8.0/CONTRIBUTING.md

**Closed** 2015-08-04 12:50 UTC

**Comment by ramitalat** [comment] 2015-08-04 12:52
Ok @blaggacao , I closed it disappointingly, just to follow your rules.

**Comment by blaggacao** [comment] 2015-09-03 22:55
:+1: Thanks, in the name of saving time and nerves of volunteering community developers.

**Comment by jahmia** [comment] 2019-11-08 13:10
Same problem
