### ISSUE TITLE
pictures not showing in Website Livechat

### ISSUE THREAD

**Issue by amindehghani** [odoo/odoo#60493] opened 2020-10-22 07:10 UTC
Impacted versions: 13.0 Community

Steps to reproduce: 
1. Create a new user and give it a profile picture
2. create a channel in livechat and assign that user to it
3. open the website as a public user

Current behavior: 
The image of Operator is not visible to the public user and shows a placeholder image instead

Expected behavior:
Showing the image of Operator

Video/Screenshot link (optional):

![Screenshot from 2020-10-22 10-37-21](https://user-images.githubusercontent.com/16416527/96837276-0265d000-1453-11eb-8608-553125b84004.png)

**Comment by pedrobaeza** [comment] 2020-10-22 07:17
Duplicate of #35037

**Closed** 2020-10-23 06:47 UTC
