### ISSUE TITLE
Broken odoo12 after updating latest version of enterprise 

### ISSUE THREAD

**Issue by Abraar-GT** [odoo/odoo#32113] opened 2019-03-26 07:44 UTC
Impacted versions:
12.0 enterprise

Once updated enterprise version its throwing error : 
odoo.addons.base.models.assetsbundle: Error: Undefined variable: "$o-modal-lg".
        on line 1140 of /stdin
>> $modal-lg: $o-modal-lg;
   -----------^
This error occured while compiling the bundle 'web.assets_backend' containing:
    - /web/static/lib/bootstrap/scss/_functions.scss
    - /web/static/lib/bootstrap/scss/_mixins.scss
    - /web/static/src/scss/utils.scss
    - /web/static/src/scss/bs_mixins_overrides.scss
    - /web/static/src/scss/primary_variables.scss
    - /web_enterprise/static/src/scss/primary_variables.scss
    - /web_editor/static/src/scss/web_editor.variables.scss
    - /web/static/src/scss/secondary_variables.scss
    - /web_enterprise/static/src/scss/secondary_variables.scss
    - /web_enterprise/static/src/scss/bootstrap_overridden.scss
    - /web_editor/static/src/scss/bootstrap_overridden.scss
    - /web/static/src/scss/import_bootstrap_part1.scss
    - /web/static/src/scss/bs_mixins_overrides.scss
    - /web/static/src/scss/import_bootstrap_part2.scss
    - /web/static/src/scss/bootstrap_review.scss
    - /web/static/lib/tempusdominus/tempusdominus.scss
    - /web_enterprise/static/src/scss/webclient.scss
    - /web_enterprise/static/src/scss/webclient_layout.scss
    - /web/static/src/scss/webclient.scss
    - /web/static/src/scss/domain_selector.scss
    - /web/static/src/scss/model_field_selector.scss
    - /web/static/src/scss/progress_bar.scss
    - /web/static/src/scss/dropdown.scss
    - /web_enterprise/static/src/scss/dropdown.scss
    - /web/static/src/scss/tooltip.scss
    - /web/static/src/scss/debug_manager.scss
    - /web/static/src/scss/control_panel.scss
    - /web/static/src/scss/fields.scss
    - /web_enterprise/static/src/scss/fields.scss
    - /web/static/src/scss/views.scss
    - /web/static/src/scss/pivot_view.scss
    - /web/static/src/scss/graph_view.scss
    - /web/static/src/scss/form_view.scss
    - /web_enterprise/static/src/scss/form_view.scss
    - /web/static/src/scss/list_view.scss
    - /web_enterprise/static/src/scss/list_view.scss
    - /web/static/src/scss/kanban_dashboard.scss
    - /web/static/src/scss/kanban_examples_dialog.scss
    - /web/static/src/scss/kanban_column_progressbar.scss
    - /web/static/src/scss/kanban_view.scss
    - /web/static/src/scss/kanban_view_mobile.scss
    - /web/static/src/scss/web_calendar.scss
    - /web/static/src/scss/search_view.scss
    - /web/static/src/scss/search_view_mobile.scss
    - /web/static/src/scss/dropdown_menu.scss
    - /web_enterprise/static/src/scss/search_view.scss
    - /web/static/src/scss/data_export.scss
    - /base/static/src/scss/onboarding.scss
    - /web/static/src/scss/base_settings.scss
    - /web/static/src/scss/report_backend.scss
    - /web_mobile/static/src/scss/mobile.scss
    - /base_import/static/src/scss/base_import.scss
    - /web_cohort/static/src/scss/web_cohort.scss
    - /web_dashboard/static/src/scss/dashboard_view.scss
    - /web_diagram/static/src/scss/diagram_view.scss
    - /web_editor/static/src/scss/web_editor.common.scss
    - /web_editor/static/src/scss/web_editor.backend.scss
    - /web_enterprise/static/src/scss/home_menu.scss
    - /web_enterprise/static/src/scss/home_menu_layout.scss
    - /web_enterprise/static/src/scss/menu_mobile.scss
    - /web_enterprise/static/src/scss/menu_search.scss
    - /web_enterprise/static/src/scss/control_panel_layout.scss
    - /web_enterprise/static/src/scss/datepicker.scss
    - /web_enterprise/static/src/scss/kanban_view.scss
    - /web_enterprise/static/src/scss/touch_device.scss
    - /web/static/src/scss/navbar_mobile.scss
    - /web_gantt/static/src/scss/gantt.scss
    - /web_grid/static/src/scss/grid_view.scss
    - /web_settings_dashboard/static/src/scss/dashboard.scss "

**Comment by pedrobaeza** [comment] 2019-03-26 09:16
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Abraar-GT** [comment] 2019-03-26 09:46
Hi,

Didnt found anything on runbot.

But i manage to resolve by updating community addons also earlier i just updated the enterprise addons and it was throwing the above error.

After that pip3 install -r requirements.txt and it worked as expected.

**Closed** 2019-03-26 09:59 UTC
Labels: Need information
