### ISSUE TITLE
Translation error Odoo V9

### ISSUE THREAD

**Issue by BartB83** [odoo/odoo#13412] opened 2016-09-06 14:59 UTC
Impacted versions: Odoo V9

Steps to reproduce: we want to change the product description by using the front-end translation editor. By clicking on 'translate' you see the yellow boxes which can be translated. Once we enter the text and click on 'save' we receive the error: 'translation is not valid'. 

Current behavior: We are translating our product pages into Dutch, but encounter several error messages when the translation is not 100% accurate.

Expected behavior: We want to use free translation and not be restricted by a 100% accurate translation of all our product descriptions.

Thanks for your help.

Regards, Bart

**Comment by RBrang** [comment] 2016-09-14 13:06
I guess this is a misunderstanding? The translation system does not verify or validate your translation in any way for correctness or so. This must be some differen problem, I guess.
I get the "translation not valid" error, too. My base language is german, and I'm trying to translate into english. I've already eliminated all "umlauts" from the original String, but that seems not to be the cause for this error. 
Still scratching my head...

**Comment by thomas15v** [comment] 2017-01-04 09:06
![image](https://cloud.githubusercontent.com/assets/2163941/21637019/56c443c2-d265-11e6-89f5-e26a02a5d4a1.png)
Its the bloody `None` that appears magically everywhere.

**Comment by Martronic-SA** [comment] 2017-03-24 10:14
This might be coming from translations in "translated" state but no Language is set.

**Comment by Yenthe666** [comment] 2017-03-24 10:51
Hi @thomas15v,

The issue in your translation is the `<br>`. If you'd change this to `<br/>` the system would accept the translation. Odoo wants all HTML content to be formatted correctly but it does not handle unclosed elements.
@BartB83 I believe you're facing a simular issue. 
Since there is no reproducable case or example I'm closing this issue. If you add proof to it or a case I'll reopen it.

Regards,
Yenthe

**Closed by Yenthe666** 2017-03-24 10:51 UTC
