### ISSUE TITLE
Documents Missing After 4 days from our application

### ISSUE THREAD

**Issue by saireddy57** [odoo/odoo#54907] opened 2020-07-24 12:15 UTC
Impacted versions:
odoo 8
Steps to reproduce:

Current behavior:    uploaded documents are being dissapearing in 4 days in application which is hosted and its will not dissapear in my local host running can anyone please help me with the solution and cause of the issue. I am using many2many field in the attachement.

Expected behavior:Documents should  not dissapear until we remove it manually.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2020-07-24 12:20
I don't think this is something of the module, but your deployment, but anyway, this is something of enterprise modules so please put a ticket at odoo.com/help, and they will see (probably in your system) the possible root cause.

Closing here.

**Closed by pedrobaeza** 2020-07-24 12:20 UTC

**Comment by Yenthe666** [comment] 2020-07-24 14:36
@pedrobaeza he's talking about V8 so its a no longer supported version (and not ENT).

**Comment by pedrobaeza** [comment] 2020-07-24 14:38
Ouch, I saw document and associated with `documents` module. So no clue which documents he is referring to (maybe attachments), but for sure is not something of Odoo.
