### ISSUE TITLE
[14.0] Weight UOM error when default is changed

### ISSUE THREAD

**Issue by pafnow** [odoo/odoo#61441] opened 2020-11-05 17:37 UTC
I'm used to change the default UOM for weight to be gram instead of kg.
Since 14.0, I receive an exception after making my usual changes.

Error is at this line:
https://github.com/odoo/odoo/blob/5b022f433a44e627541d30ae21d7a867f4a3a6ff/addons/product/models/product_template.py#L286
The domain used to find the reference UOM for weight contains ('measure_type', '=' , 'weight') which is not relevant anymore since this change removed measure_type field:
https://github.com/odoo/odoo/commit/52ed0be17e80aa6bcc24d59620dd3462b6d577c3#diff-7aa42e1663219ce82e34c884679a1f295e1fe26afd8daa7cb4d52d8663e79b83

**Comment by Yenthe666** [comment] 2020-11-06 07:53
Can you please add more detailed steps or make a video? I can't reproduce it on the latest 14.0

**Comment by pafnow** [comment] 2020-11-06 08:12
Sure here are the steps:
1. Head to Inventory / Configuration / UoM
2. Delete all UoM where Category = Weight
3. Recreate UoM manually (I do this to recreate the new UoM weight reference as gram)
4. Open any product.template form and you should get this exception:
```
Traceback (most recent call last):
  File "/mnt/c/Users/xxx/odoo/14.0/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/mnt/c/Users/xxx/odoo/14.0/odoo/http.py", line 314, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Invalid field uom.uom.measure_type in leaf ('measure_type', '=', 'weight')
```

**Comment by pedrobaeza** [comment] 2020-11-06 08:18
But that's the problem: you mustn't delete UoMs, as they are referenced by external identifier (XML-ID), and thus, this is wasting everything internally. Closing as no bug, but bad manipulation of the DB.

**Closed by pedrobaeza** 2020-11-06 08:18 UTC
Labels: 14.0, Need information

**Comment by pafnow** [comment] 2020-11-06 08:23
Hi,
The code was actually handling both case before: first match by XML-ID and if not found match the one defined as reference for weight.
Look this line of code:
`return self.env.ref('uom.product_uom_lb', False) or self.env['uom.uom'].search([('measure_type', '=' , 'weight'), ('uom_type', '=', 'reference')], limit=1) `
The second part (after the or) is the part which is now raising the exception since measure_type field was removed from uom.uom model (refer to my first post for the commit link).
I would suggest to just remove that part if we are not supposed to change XML-ID of weight reference unit...

**Comment by pedrobaeza** [comment] 2020-11-06 08:25
Please do a PR changing that, but in general, it's a very bad idea to remove standard data in the DB. This is the less bad thing that can happen. That's why some objects have the possibility to archive.
