### ISSUE TITLE
[12.0] Footer of PDF reports not displaying

### ISSUE THREAD

**Issue by zyyang** [odoo/odoo#31531] opened 2019-03-01 11:55 UTC
Impacted versions:
12.0 community&enterprise
wkhtmltopdf 0.12.5(my local version)

Steps to reproduce:
Log in to latest current [runbot](http://472408-12-0-a913e1.runbot13.odoo.com/web/login
Open up any pdf report with footer( e.g: preview company's external report in Settings)

Current behavior:
PDF report generated with no footer content.
[Preview External Report.pdf](https://github.com/odoo/odoo/files/2919317/Preview.External.Report.pdf)

Expected behavior:
Footer displayed.

Video/Screenshot link (optional):
None.

Possible cause:
the change to report.scss @nle-odoo made.

`    content: '\00a0';
`

**Comment by pedrobaeza** [comment] 2019-03-01 11:57
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by nle-odoo** [comment] 2019-03-01 12:14
Hello,


I have tried on runbot 12 => https://i.imgur.com/aGpRkAt.png and I do see the footer.

If you have Odoo in local, can you see if removing:

[code]/* Avoid flex removing vertical margin */
div.address.row {
    display: block;
}

/* margin-top does not work on first visible element of page */
body > *:first-child::before {
    content: '\00a0';
  @zyyang
zyyang 18 minutes ago  Contributor
#31531

 @nle-odoo	Reply…
    display: block;
    height: 1px;
}[/code]

in addons/web/static/src/scss/report.scss solves your issue?

**Comment by zyyang** [comment] 2019-03-01 12:19
I've been testing on my local laptop for a whole afternoon to find out the reason.
Pretty sure  "content: '\00a0'" causes all.

**Comment by zyyang** [comment] 2019-03-01 12:38
Hi, 
Could you tell me which build you are logging to?
From what I can see on runbot, I get footer-less sale order and invoice pdf report.
Like this:
[Order - SO063.pdf](https://github.com/odoo/odoo/files/2919391/Order.-.SO063.pdf)

> Hello,
> 
> I have tried on runbot 12 => https://i.imgur.com/aGpRkAt.png and I do see the footer.
> 
> If you have Odoo in local, can you see if removing:
> 
> ```css
> /* Avoid flex removing vertical margin */
> div.address.row {
>     display: block;
> }
> 
> /* margin-top does not work on first visible element of page */
> body > *:first-child::before {
>     content: '\00a0';
>     display: block;
>     height: 1px;
> }
> ```
> 
> in addons/web/static/src/scss/report.scss solves your issue?

**Comment by nle-odoo** [comment] 2019-03-01 13:01
Thanks, I have been able to reproduce on runbot when using different document template (in general settings) that the one that worked for me.

I have made a fix for the regression there: https://github.com/odoo/odoo/pull/31533 and I will merge it once I have tested it on runbot (in the following hours today).

**Closed** 2019-03-01 14:50 UTC
Labels: 12.0, Confirmed
