### ISSUE TITLE
button is not properly disabled

### ISSUE THREAD

**Issue by grey27** [odoo/odoo#75881] opened 2021-09-02 01:47 UTC
After I set the Confirm property to the button, the popup button was not disabled, so the user could click it multiple times

**Comment by grey27** [comment] 2021-09-02 04:05
The button on the Form view is disabled after being clicked until the action is complete, but with a confirmation box it is not disabled after being clicked

**Comment by pedrobaeza** [comment] 2021-09-02 06:25
The confirmation box avoids to click again on the button. Where is the problem? Please put a video showing the issue.

**Comment by grey27** [comment] 2021-09-03 02:59
video url: https://drive.google.com/file/d/1KSEsdaf89iKevABlAcgE3IW9MVFj09U1/view?usp=sharing

xml:
```
<header>
       <button name="do_long_time_1" type="object" string="not confirm button" class="oe_highlight"/>
       <button name="do_long_time_2" type="object" string="confirm button" class="oe_highlight" confirm="are you sure?"/>
 </header>
```
model:
```
def do_long_time_1(self):
       self.env.user.notify_success('111111')
       # simulate long time operation
       time.sleep(10)

def do_long_time_2(self):
       self.env.user.notify_success('222222')
       # simulate long time operation
       time.sleep(10)
```

When I hit the button multiple times quickly, button 1 doesn't repeat, but button 2 does

**Comment by msh-odoo** [comment] 2021-09-06 07:24
@pedrobaeza I think it is duplicate of #74647

**Comment by pedrobaeza** [comment] 2021-09-06 07:25
Indeed. Closing as duplicate. Following on the previous issue.

**Closed by pedrobaeza** 2021-09-06 07:25 UTC
Labels: Framework
