### ISSUE TITLE
no handler found 

### ISSUE THREAD

**Issue by csz** [odoo/odoo#11723] opened 2016-04-16 16:05 UTC
C:\Python27\python.exe E:/openerp/openerp-7.0-latest/openerp-7.0-20130717-231254/openerp-server
2016-04-16 15:56:53,099 8840 INFO ? openerp: OpenERP version 7.0-20130717-231254
2016-04-16 15:56:53,101 8840 INFO ? openerp: addons paths: E:\openerp\openerp-7.0-latest\openerp-7.0-20130717-231254\"E:\openerp\openerp-7.0-latest\openerp-7.0-20130717-231254\openerp\addons"
2016-04-16 15:56:53,101 8840 INFO ? openerp: database hostname: localhost
2016-04-16 15:56:53,101 8840 INFO ? openerp: database port: 5432
2016-04-16 15:56:53,101 8840 INFO ? openerp: database user: openerp
2016-04-16 15:56:53,846 8840 CRITICAL ? openerp.modules.module: Couldn't load module web
2016-04-16 15:56:53,846 8840 CRITICAL ? openerp.modules.module: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. Are you sure that git is installed?
2016-04-16 15:56:53,848 8840 ERROR ? openerp.service: Failed to load server-wide module `web`.
The `web` module is provided by the addons found in the `openerp-web` project.
Maybe you forgot to add those addons in your addons_path configuration.
Traceback (most recent call last):
  File "E:\openerp\openerp-7.0-latest\openerp-7.0-20130717-231254\openerp\service\__init__.py", line 60, in load_server_wide_modules
    openerp.modules.module.load_openerp_module(m)
  File "E:\openerp\openerp-7.0-latest\openerp-7.0-20130717-231254\openerp\modules\module.py", line 405, in load_openerp_module
    __import__('openerp.addons.' + module_name)
  File "E:\openerp\openerp-7.0-latest\openerp-7.0-20130717-231254\openerp\modules\module.py", line 133, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "E:\openerp\openerp-7.0-latest\openerp-7.0-20130717-231254\openerp\addons\web\__init__.py", line 3, in <module>
    import cli
  File "E:\openerp\openerp-7.0-latest\openerp-7.0-20130717-231254\openerp\addons\web\cli\__init__.py", line 1, in <module>
    import test_js
  File "E:\openerp\openerp-7.0-latest\openerp-7.0-20130717-231254\openerp\addons\web\cli\test_js.py", line 8, in <module>
    import openerp.addons.web.tests
  File "E:\openerp\openerp-7.0-latest\openerp-7.0-20130717-231254\openerp\addons\web\tests\__init__.py", line 2, in <module>
    from . import test_dataset, test_menu, test_serving_base, test_js
  File "E:\openerp\openerp-7.0-latest\openerp-7.0-20130717-231254\openerp\addons\web\tests\test_dataset.py", line 2, in <module>
    import mock
  File "C:\Python27\lib\site-packages\mock\__init__.py", line 2, in <module>
    import mock.mock as _mock
  File "C:\Python27\lib\site-packages\mock\mock.py", line 71, in <module>
    _v = VersionInfo('mock').semantic_version()
  File "C:\Python27\lib\site-packages\pbr\version.py", line 460, in semantic_version
    self._semantic = self._get_version_from_pkg_resources()
  File "C:\Python27\lib\site-packages\pbr\version.py", line 447, in _get_version_from_pkg_resources
    result_string = packaging.get_version(self.package)
  File "C:\Python27\lib\site-packages\pbr\packaging.py", line 710, in get_version
    raise Exception("Versioning for this project requires either an sdist"
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. Are you sure that git is installed?
2016-04-16 15:56:53,891 8840 INFO ? openerp: OpenERP server is running, waiting for connections...
2016-04-16 15:56:53,908 8840 INFO ? openerp.service.wsgi_server: HTTP service (werkzeug) running on 0.0.0.0:8069

**Comment by Yenthe666** [comment] 2016-06-13 13:40
Hi @csz,

Your true issue is coming from this:

> raise Exception("Versioning for this project requires either an sdist"
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. Are you sure that git is installed?

This issue is not related to Odoo itself, but is a faulty configuration.
Closing this issue since I can't reproduce it and it doesn't seem to have anything to do with Odoo itself.

Regards,
Yenthe

**Closed by Yenthe666** 2016-06-13 13:40 UTC
