### ISSUE TITLE
[9.0] res.config.settings default_get for group returns boolean when it should be integer

### ISSUE THREAD

**Issue by yvaucher** [odoo/odoo#10775] opened 2016-02-04 15:16 UTC
Version:

9.0

Error:

```
    File ".../server/openerp/sql_db.py", line 139, in wrapper
      return f(self, *args, **kwargs)
    File ".../server/openerp/sql_db.py", line 218, in execute
      res = self._obj.execute(query, params)
  DataError: invalid input syntax for integer: "True"
  LINE 1: ...t', NULL, 'fixed', NULL, false, NULL, NULL, NULL, 'True', fa...
                                                               ^
```

Considering we can now have selection fields instead of boolean to be able to use radio buttons. I saw both in current 9.0 branch (sale.config.settings has integer while base.config.settings has boolean in `addons/product/res_config.py`)

Like in sales/settings/configuration -> Incoterms (group_display_incoterm)
When trying to create a sale.config.settings without setting incoterm, it will fails as it provides a Boolean value while it expect an Integer.

https://github.com/odoo/odoo/blob/ff3184ed8284a135405314bb76644ce59ba89142/openerp/addons/base/res/res_config.py#L522-L523

For some reason it only fails if incoterm is to 1. It works fine when it's False

How to reproduce:

In python:

```
@api.mult
def test(self):
    # set up display incoterms
    vals = {'group_display_incoterm': 1}
    wiz = self.env['sale.config.settings'].create(vals)
    wiz.execute()
    # it works

    # setup something else
    vals = {'default_invoice_policy': 'cost'}
    wiz = self.env['sale.config.settings'].create(vals)
    # it fails on create due to default_get
```

Expected behavior

default_get is careful to provide integer when needed then create don't fail

**Comment by pedrobaeza** [comment] 2018-04-12 20:13
Hi, I'm not able to reproduce this problem in latest version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there.

**Closed by pedrobaeza** 2018-04-12 20:13 UTC
Labels: 9.0
