### ISSUE TITLE
Sale warning issues OdooV11

### ISSUE THREAD

**Issue by rohitramnani1994** [odoo/odoo#22114] opened 2018-01-09 14:13 UTC
Impacted versions: [11.0]

Steps to reproduce: 
1 > Go to Sales - > Configuration -> allow Warning in orders for products or customers
2> Go to Customer menu - > open any customer form view -> click on edit button - >go to internal notes tab

Current behavior:

when you select Warning in "Warning on the Sales Order"  field then show the one more required field is called "sale_warn_msg" and again  select  "Blocking Message" in same field then also shows one more required field is called "sale_warn_msg" 
Now i am select again No message and again select the "Warning or Blocking Message" then we can't  able to see rquired field "sale_warn_msg"  and when i click on save field getting a invalid field popup regarding message for sale order.

Expected behavior:
show the "sale_warn_msg" field as per selection in warning message field.

Video/Screenshot link (optional):
Video : https://youtu.be/W5HrygOioBE
Image : https://ibb.co/fR0p46

**Comment by rohitramnani1994** [comment] 2018-01-09 14:15
Hello @Yenthe666 

hope you are doing well !

can you please check it 

Many thanks in advance :)

**Comment by Yenthe666** [comment] 2018-01-09 14:31
Hi @rohitramnani1994,

Thank you for the bug report (and the video!)
I can confirm that this is a bug and a quite annoying one. @mart-e perhaps something you could take a look at?

Regards,
Yenthe

**Comment by mart-e** [comment] 2018-01-09 17:17
cc @ged-odoo looks like a funny bug (but not blaming the new view, was not present in saas-16)

**Comment by mge-odoo** [comment] 2018-03-26 14:59
Hi @rohitramnani1994 

Thanks for reporting this issue ; I have tested it on runbot 11.0 and I can't reproduce it so I guess that it has been fixed in the mean time.

I therefore close this issue but do not hesitate to reopen it if you face this issue again.

Regards,

Martin

**Closed by mge-odoo** 2018-03-26 14:59 UTC
Labels: 11.0, Confirmed, Framework
