### ISSUE TITLE
[12.0] Lock/Unlock switched in Manufacturing Orders form view

### ISSUE THREAD

**Issue by reinaldoramosarxi** [odoo/odoo#37350] opened 2019-09-24 10:07 UTC
Hello,

The Lock/Unlock buttons' domains (or the strings, depending on your philosophical inclination) are switched in the Manufacturing Orders form view.

That means that the button will say "Unlock" when it's unlocked and "Lock" when it's locked.

https://github.com/odoo/odoo/blob/12.0/addons/mrp/views/mrp_production_views.xml#L51
https://github.com/odoo/odoo/blob/12.0/addons/mrp/views/mrp_production_views.xml#L52

Thank you.

**Comment by reinaldoramosarxi** [comment] 2019-09-24 10:49
UPDATE: It's not the strings, there's actually an underlying issue with the domains.

**Comment by sswapnesh** [comment] 2019-09-25 15:59
Seems Duplicate of https://github.com/odoo/odoo/issues/21904
@reinaldoramosarxi  Can you please check that one ?

**Comment by reinaldoramosarxi** [comment] 2019-09-25 16:16
Looks like it. It's still a very strange behavior, nonetheless.

**Comment by sswapnesh** [comment] 2019-09-25 16:33
Hello @sle-odoo  (Based on https://github.com/odoo/odoo/issues/21904#issuecomment-354350249)

Can we Improve this for future versions ?

**Comment by Yenthe666** [comment] 2019-09-25 17:26
I assume a PR in master would be fine? (or saas-12.5 if you're fast)

**Comment by sswapnesh** [comment] 2019-09-25 17:28
Not sure if It will be Approved or not (Based on my Past experiences)

**Comment by pedrobaeza** [comment] 2019-09-25 17:33
TBH, I don't see the problem in current approach.

**Comment by sswapnesh** [comment] 2019-09-25 17:37
@pedrobaeza 
From https://github.com/odoo/odoo/issues/21904#issuecomment-354339827

> I agree with this use case also but the Same works differently for Sale order, So it is Confusing.

Not tested for newer versions

**Comment by pedrobaeza** [comment] 2019-09-25 17:42
You don't have to compare it with sales orders, but with pickings, which are lock by default (and SOs can be auto-locked as well). I would opt-in for a similar configuration for MOs, not to change current behavior.

**Comment by sswapnesh** [comment] 2019-09-25 17:45
That's also True, We can close this then.

**Comment by Yenthe666** [comment] 2019-09-25 17:47
A very fair point, I believe you're right Pedro. Thanks for the feedback!

**Closed by Yenthe666** 2019-09-25 17:47 UTC
Labels: 12.0, Logistics
