### ISSUE TITLE
[11.0] Delivered qty on sale orderline incorrect after deleting timesheet line

### ISSUE THREAD

**Issue by ThijsvOers** [odoo/odoo#21347] opened 2017-11-30 14:35 UTC
Impacted versions: 1, tested on odoo.runbot

Steps to reproduce: create a salesorder and add a service product (with options: 'Timesheet on task' and 'create new project and task')

- add a timsheetline entry (1 hour). After saving the task on the sale orderline the number of delivered hours is 1 (this is correct)
- Go back to the task and delete the timesheet line

I would expect that the total number if delivered Qtt would be 0, but it is 1.

So in my opinion the Qty of the salesorderline is not correctly updated after deleting the timesheet entry

![schermafdruk van 2017-11-30 15-33-41](https://user-images.githubusercontent.com/30256071/33435962-e361b076-d5e3-11e7-9607-58e1d3cb7cdd.png)
![schermafdruk van 2017-11-30 15-33-28](https://user-images.githubusercontent.com/30256071/33435963-e38432a4-d5e3-11e7-9f21-db49dfb8b8b3.png)

**Comment by astirpe** [comment] 2017-12-19 14:22
Are there news about this issue?

**Comment by Yenthe666** [comment] 2017-12-20 07:27
@astirpe nope, the Github tracker is best effort. If you have an enterprise license I suggest you to report it through there 😉

**Comment by astirpe** [comment] 2017-12-29 07:59
It seems to me that this issue was fixed with commit https://github.com/odoo/odoo/commit/1f09312bde9c61e8626f563fcda803272572c4b6 made by @jem-odoo.

@ThijsvOers could you please check whether the issue still occurs on runbot?

**Comment by jem-odoo** [comment] 2017-12-29 08:20
Yes, indeed. Sorry, I forget to tell you.
If you confirm the problem is solved, we can close this issue.
Thanks ;)

**Comment by ThijsvOers** [comment] 2018-01-07 14:39
I have tested the fix on runbot and it works fine, thank you. 

You also might want to know that we are currently working on a new module which should be the replacement of Odoo 8 module hr_timesheet_invoice. 

The reason for creating this module is that we want to have control over the invoicing of timesheets (they should be validated first AND we want to have the option to partial invoice hours). With the current functionality all hours that are written on a timesheet can be invoiced immediately.

The module will be published in the next weeks.

**Closed** 2018-01-08 07:25 UTC
Labels: 11.0
