### ISSUE TITLE
[8.0] Removing voucher lines quickly leads to an AssertionError.

### ISSUE THREAD

**Issue by mvaled** [odoo/odoo#8615] opened 2015-09-18 23:58 UTC
Steps to reproduce:
1. Create many (about 20) customer invoices for Agrolait and validate them all.
2. Go to Customer Payment and select agrolait and bank.
3. As quickly as you can click all the remove icons for all proposed voucher lines.  Put the pointer over the first one, and then click many times quickly.
4. Try to save the voucher.

You'll probably get an AssertionError:

```
Traceback (most recent call last):
  File "/home/manu/src/merchise/pgi/openerp/openerp/http.py", line 549, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/manu/src/merchise/pgi/openerp/openerp/http.py", line 586, in dispatch
    result = self._call_function(**self.params)
  File "/home/manu/src/merchise/pgi/openerp/openerp/http.py", line 322, in _call_function
    return checked_call(self.db, *args, **kwargs)

....

    return WorkflowService.new(cr, uid, res_type, res_id).delete()
  File "/home/manu/src/merchise/pgi/openerp/openerp/workflow/service.py", line 37, in new
    return cls(Session(cr, uid), Record(model_name, record_id))
  File "/home/manu/src/merchise/pgi/openerp/openerp/workflow/helpers.py", line 13, in __init__
    assert isinstance(record_id, (int, long))
AssertionError
```

You'll see also see that the POST contains virtual ids in the `line_dr_ids` like `[[2, 'one2many_v_id_1000', False], [2, 'one2many_v_id_1000', False], ...]`.  So the web client is trying to remove (that's 2) virtual ids.  Notice also that the same virtual id is being sent several times (I've seen as many as seven).

**Comment by mvaled** [comment] 2015-10-05 23:14
Hi @wtaferner,  Could try to reproduce this and confirm it?

**Comment by mvaled** [comment] 2015-10-05 23:27
As of commit 57b993ffadac980f1e05951a387f346bc42ac040 this still happens.

**Comment by wtaferner** [comment] 2015-10-06 05:11
@mvaled 
Nope, I tried it on latest runbot and was unable to reproduce...

**Comment by mvaled** [comment] 2015-10-07 01:01
Thanks @wtaferner.  I will try again, runbot and local, to see if I get "unlucky".

**Comment by spadae22** [comment] 2015-10-08 16:08
Still happens just reproduced today,reverse transfer for delivery order with many items, submitted bug on enterprise.

**Comment by mvaled** [comment] 2015-10-08 17:18
Hi @wtaferner,

I've just reproduced the issue it in runbot (http://106566-8-0-1423ce.runbot7.odoo.com/).  The recorded session is at https://youtu.be/VEnliMqS4g0

**Comment by wtaferner** [comment] 2015-10-08 18:00
@mvaled 
Maybe https://github.com/odoo/odoo/pull/8273 might resolve your issue...it is about sending three similar request while deleting a single one2many value and if you unlink really fast the backend might run into your issue which is workflow related...but this is something you should test...I will ask if it can be merged into stable 8.0 as it was already tested several weeks now without troubles...

**Comment by mvaled** [comment] 2015-10-08 18:06
Hi @wtaferner,

In my server I have merged that PR and the issue is reproducible.

**Comment by wtaferner** [comment] 2015-10-08 18:27
Then it is probably something else...try to reproduce on v9. And do not click so fast while unlinking in v8 ;-) If you can reproduce in v9 it is probably worth a deeper investigation...

**Comment by wtaferner** [comment] 2015-10-12 14:11
A fix seems to be on the way via https://github.com/odoo/odoo/pull/9025

**Comment by Yenthe666** [comment] 2017-11-26 16:04
Hi @mvaled,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Closed by Yenthe666** 2017-11-26 16:04 UTC

**Comment by kenhancoder** [comment] 2017-11-27 09:49
I reproduce this issue on Odoo 9  (；′⌒`)

**Comment by Yenthe666** [comment] 2017-11-27 11:49
@kenhancoder if you can reproduce it on a runbot you're free to make a new bug report.
