### ISSUE TITLE
Purchase Stock don’t have inventor on hand case

### ISSUE THREAD

**Issue by koz01** [odoo/odoo#32940] opened 2019-04-25 08:20 UTC
Version: Version 12 Enterprise

Case: After purchased the product, check in inventory report, don’t show inventory on hand.
Step 1: Purchase the product
<img width="683" alt="step1" src="https://user-images.githubusercontent.com/16234060/56720791-97f2a780-6769-11e9-98c2-91bfaa8fa5ff.png">

Step 2: Received the product with unique serial code
<img width="683" alt="step2" src="https://user-images.githubusercontent.com/16234060/56720814-a345d300-6769-11e9-8f00-9ec79f99f5b6.png">
<img width="681" alt="step2_1" src="https://user-images.githubusercontent.com/16234060/56720823-a6d95a00-6769-11e9-8692-440b8106e211.png">
Step 3: Check that unique serial product at the product move, stock move from vendor location to main warehouse location
<img width="683" alt="Step3" src="https://user-images.githubusercontent.com/16234060/56720841-af319500-6769-11e9-87c4-fe2670f0beba.png">
Check that product serial number at inventory on hand, no on hand will showing.
<img width="683" alt="step34" src="https://user-images.githubusercontent.com/16234060/56720855-b48edf80-6769-11e9-9df7-b4cbe7f0aa79.png">

**Comment by pedrobaeza** [comment] 2019-04-25 10:09
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by koz01** [comment] 2019-04-25 10:41
This is detail explain.

**Comment by koz01** [comment] 2019-04-25 10:42
No more customization.

**Comment by pedrobaeza** [comment] 2019-04-25 10:43
It's not reproducible in runbot. That's why I ask.

**Comment by koz01** [comment] 2019-04-25 10:48
I take database backup from the production server.
And then restore in my local server.
I test this case but not facing an issue.
Facing only in my Production server.

Production Server
Ubuntu 18.4
Source Installation

Local Server
Window 10
Exe Installation

I think due to the server source code.

**Comment by pedrobaeza** [comment] 2019-04-25 10:49
Then update it. Any way, it's not an Odoo issue, so I close this one.

**Comment by koz01** [comment] 2019-04-25 10:50
Why close this issue.
I not get any solution.This is Enterprise Version.

**Closed by pedrobaeza** 2019-04-25 10:49 UTC
Labels: Need information

**Comment by koz01** [comment] 2019-04-25 10:52
Odoo never takes responsibility for All Issue.
They always close the ticket.

**Comment by pedrobaeza** [comment] 2019-04-25 14:19
I'm not an Odoo employee. Just a volunteer from community that filters out incorrect issues in community version.

If you have an enterprise contract, then you should raise an enterprise ticket with your problem to odoo.com/help. But you have to take into account one thing, the same as the guarantee in physical devices: if the problem is generated by a bad manipulation, this might not be covered by the official support. Any way, enterprise team would decide this.
