### ISSUE TITLE
Customer in Company A is visible in Company B (Odoo 13)

### ISSUE THREAD

**Issue by ctringham** [odoo/odoo#41720] opened 2019-12-11 13:58 UTC
**Impacted versions:** 13

**Steps to reproduce:** 1. Create a customer in My Company (Chicago).  2. Switch to My Belgian Company

**Current behavior:**  Customer can be found and edited even though it's not in this company

**Expected behavior:** Customers (and other partners) in Company A should not be visible in Company B (default is that company is left blank, and those partners should be visible across companies)

**Video/Screenshot link (optional):** https://drive.google.com/file/d/1IT428Th0xeiztKxg0sGchd-gaKFG8f77/view

![Multicompany issue](https://user-images.githubusercontent.com/38899643/70627362-12bcf400-1c61-11ea-86b4-f2883e596e9b.jpg)

<del>**Note:** I tested this in Community Edition and it seemed to work correctly

**Comment by pedrobaeza** [comment] 2019-12-11 13:59
You have to deactivate the configuration option of sharing the address book.

Closing as no issue, but misconfiguration.

**Comment by ctringham** [comment] 2019-12-11 14:02
I thought that had been removed in Odoo 13

**Comment by pedrobaeza** [comment] 2019-12-11 14:05
I'm assuming not. Let me check...

**Comment by ctringham** [comment] 2019-12-11 14:07
In Odoo 12 and previous there were some Record Rules that were enabled if you de-selected the Common Contact Book and Common Product Catalog.  In Odoo 13 it's handled differently.

**Comment by pedrobaeza** [comment] 2019-12-11 14:13
Yeah, totally right! Now there's no record rule that prevents this, but it's supposed that it's handled through new multi-company ORM features. So are you saying this works properly in Odoo 13 CE?

**Comment by ctringham** [comment] 2019-12-11 14:28
I tested it earlier today and I thought it was OK, but now I find the same problem.

**Comment by ctringham** [comment] 2019-12-11 14:39
Seems that the customer can't be selected on a sales order (good), but is visible in the customers menu option (bad)
![SF user customers](https://user-images.githubusercontent.com/38899643/70630739-0340a980-1c67-11ea-9c31-ab93c6ad5251.jpg)
![SF user quotation](https://user-images.githubusercontent.com/38899643/70630749-089df400-1c67-11ea-9440-916452ef0c93.jpg)

**Comment by pedrobaeza** [comment] 2019-12-11 15:57
OK, so this apply properly for a bug. Reopening and pinging @Feyensv (again as my wildcard :) ) for this kind of things as I know he worked on multi-company stuff.

**Comment by dbo-odoo** [comment] 2019-12-11 16:19
Hi,

This is a side-effect of this fix: d86c2c588367dee319649ab2a5890975c1 - the commit explains why this was necessary.

The problem is that `res.partner` is used by users through the `inherits`, so we can't have rules that apply differently to partners that are also users and classic partners (which might also have user for the portal).

I'll close this, since it's the expected behaviour (even though I agree it's annoying).

KR,

**Comment by pedrobaeza** [comment] 2019-12-11 16:25
@dbo-odoo but that's not only annoying, but illegal according GDPR: one company can't see contacts and personal information of them from other companies. And this is breaking business processes from several of my customers when they migrate to 13.0. I know that a solution is to "restore that record rules in my DBs", but I think you should find another of solving the problem without doing that breaking thing.

**Comment by dbo-odoo** [comment] 2019-12-11 16:30
@pedrobaeza you make a good point
@amoyaux it's your fix, i suggest you have a look at this thread... and try to see what else could be done

**Comment by pedrobaeza** [comment] 2019-12-11 16:34
Let me suggest this domain for the record rule (applied in a v12, but not sure if valid for v13):
```
['|','|',('user_ids.company_ids', 'child_of', user.company_ids.ids),('company_id','child_of',[user.company_id.id]),('company_id','=',False)]
```

**Comment by amoyaux** [comment] 2019-12-11 17:05
It's not possible to have at the same time a not shared company book and a multi company environment where a user is in more than 1 company.

There is a PR where we had a bug for multi company https://github.com/odoo/odoo/pull/37712
(summary: _inherits apply record rules between models and so if a partner is in a specific company, its user is not accessible in another company)

I tried to correct the rule by adding ['|', ('user_ids', '=', False), ('user_ids.company_ids', 'in', company_ids)] on partner. However since there is an auto_join between res.users et res.partner (for perf https://github.com/odoo/odoo/commit/db8203c27a21acdbcad2cf1c394b6fea3cf13688), the generated SQL is wrong:

SELECT "res_partner".id FROM "res_partner","res_users" as "res_partner__user_ids" 
WHERE ("res_partner"."active" = True) 
  AND ("res_partner"."id"="res_partner__user_ids"."partner_id") 
  AND (
    (
           ("res_partner__user_ids"."id" in (SELECT "user_id" FROM "res_company_users_rel" WHERE "cid" IN (1,)))
       OR  (("res_partner"."id" not in (3, 5, 2, 4, 8, 6, 7)) OR "res_partner"."id" IS NULL)
    )  
    AND ((("res_partner"."type" != %s) OR "res_partner"."type" IS NULL)  OR  "res_partner"."type" IS NULL )
  )

The where close apply globally instead of its own domain but since it's low level code on SQL generation it's not trivial to fix or implement. So we just removed the shared company book in stable for the trade of a good multi company for users.

Also notice that shared company book and multi company with users that have more than one company never worked even in previous version.

If you want to still the other behavior then you just need to recreate the record rule ['|', ('id', '=', user.id), ('company_ids', 'in', company_ids)] on res.partner.

**Comment by pedrobaeza** [comment] 2019-12-11 17:12
Do you have a test for exercising the problem before removing the record rule? If so, I can take a look to find a satisfying solution for all cases.

But you have to agree with me about the legal problem with leaked personal information with that patch.

**Comment by amoyaux** [comment] 2019-12-12 14:19
No I don't have a test but if you check the usecase on #37712 you could probably do an easy test.
- Set a user in company A and B (default company A)
- Be active in only company B
- Do a search([]) on res.users -> you should have your user.
- Do a search([]) on res.partner -> you should not see the partner associated to your user.

Anyway GDPR or not, if you re-add the record rule, you will have the exact same behavior than in previous version (since the common company book is enable by default). In your migration process you should probably think to automatically add the rule if the common company book settings was disable.

**Comment by ctringham** [comment] 2019-12-14 02:08
Can this be re-opened?  It is not correct behaviour to show a customer from Company B in Company A, and even if the old logic with Record Rules was not perfect it did avoid this GDPR issue (and even in non-GDPR countries it is problematic to allow users access to customer data from an associated company).

**Comment by dbo-odoo** [comment] 2019-12-30 16:37
I think I have something better than the fix currently in place that should satisfy more people. Even if my fix is not approved, I believe we have to do something about this indeed.

**Comment by pedrobaeza** [comment] 2019-12-30 16:45
Thanks for that! Checking #42511 now.

**Closed** 2020-01-02 13:08 UTC
