### ISSUE TITLE
Can't load GoogleMaps inside Widget javascript

### ISSUE THREAD

**Issue by augustocadini** [odoo/odoo#31860] opened 2019-03-14 21:27 UTC
I just want add Google Maps to a new widget through Google Maps Javascript API. For the example of Google this works fine but when I try put into Odoo this not works. When load the page nothing happens, if I don't use callback function the follow error message is showed: `Uncaught ReferenceError: google is not defined`.

Impacted versions:
10

Steps to reproduce:
/static/src/js/google_maps_widget.js

```
var map;

function initialize() {
    map = new google.maps.Map(document.getElementById('map'), {
        center: { lat: -2.190874, lng: -79.884467 },
        zoom: 8,
    });
}
```
/static/src/xml/google_maps_widget.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<templates xml:space="preserve">
    <t t-name="FieldMap">
        <div class="vz_gmap"></div>
    </t>
</templates>
```

/views/template.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<odoo>
    <data>
        <template id="assets_backend" inherit_id="web.assets_backend">
            <xpath expr="." position="inside">
                <script type="text/javascript" src="/vz_visit/static/src/js/google_maps_widget.js"/>
                <script src="https://maps.googleapis.com/maps/api/js?key=MY_API_KEY&callback=initialize"></script>
                <div id="map" style="width:50%;height:550px;"></div>
            </xpath>
        </template>
    </data>
</odoo>
```

Current behavior:
Nothing happens.
Console error: Could not get content for //maps.googleapis.com/maps/api/js?key=API_KEY defined in bundle 'web.assets_backend'.

Expected behavior:
Google maps showed

Video/Screenshot link (optional):
![Screen Shot 2019-03-14 at 18 23 28](https://user-images.githubusercontent.com/18659348/54392423-6b397380-4686-11e9-9791-bb847f6002ed.png)

**Comment by pedrobaeza** [comment] 2019-03-14 21:34
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Comment by augustocadini** [comment] 2019-03-14 21:34
> Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.
> 
> Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.
> 
> If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

Ok.

**Closed by pedrobaeza** 2019-03-14 21:34 UTC
