### ISSUE TITLE
[13.0] Not possible to delete HR Employee because of Resource Foreign Key

### ISSUE THREAD

**Issue by lrstry** [odoo/odoo#61089] opened 2020-10-30 17:49 UTC
It's not possible to delete Employees with an existing Resource-record (hr_employee_resource_id_fkey still existing).
Other way round it's also not possible to delete the Resource first (hr_employee_resource_id_fkey still existing).

Why is there no ondelete=cascade in the [definition](https://github.com/odoo/odoo/blob/c6a8be30c2b43d6462e365da6f3ec5aad32d1c08/addons/hr/models/hr_employee_base.py#L29)?

Best regards,
Lars

**Comment by sswapnesh** [comment] 2020-10-30 18:28
> It's not possible to delete Employees with an existing Resource-record 

I just deleted an Employee from V13 Runbot https://4819065-13-0.runbot51.odoo.com/web#action=280&model=hr.employee&view_type=kanban&cids=&menu_id=204



`hr_employee_resource_id_fkey` will be on deleting Resource linked to an employee.

While deleting Employee we are also deleting Resource at
https://github.com/odoo/odoo/blob/c6a8be30c2b43d6462e365da6f3ec5aad32d1c08/addons/hr/models/hr_employee.py#L278

**Comment by pedrobaeza** [comment] 2020-10-30 22:29
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Closed** 2023-04-07 14:14 UTC
Labels: Need information
