### ISSUE TITLE
[Wishlist] Ability to invoice VAT in local currency (legal requirement in some countries)

### ISSUE THREAD

**Issue by jorunn** [odoo/odoo#22839] opened 2018-02-06 11:34 UTC
Some countries, including Norway and, I believe, the UK, requires that the VAT be expressed in the local currency even if the rest of the invoice is using a foreign currency.

Impacted versions: All

Steps to reproduce:
1. Create an invoice for a customer in a foreign currency.
2. Try to add VAT in your local currency as required by authorities.

Current behavior:
3. No can do, Odoo is currently limited to one currency per invoice. 

Expected behavior:
3. A setting or option exists to keep the VAT in the local currency.

Video/Screenshot link (optional):

**Comment by lukebranch** [comment] 2018-02-07 03:09
FWIW, I believe this is also a requirement in India as well in terms of printed reports for SO, INV, DO, and PO.

**Comment by qdp-odoo** [comment] 2018-02-28 08:31
Ok, not a bug but a missing feature, so I'll close the issue for the sake of Clarity.

We've recorded it as a feedback and we'll see what we can do for it in a next version. cc @lap-odoo 

Thanks for reporting

**Closed by qdp-odoo** 2018-02-28 08:31 UTC
Labels: Accounting, Wishlist
