### ISSUE TITLE
When Language code is edited it starts showing errors

### ISSUE THREAD

**Issue by chand3040** [odoo/odoo#8574] opened 2015-09-17 13:49 UTC
Here is how the error can be reproduced:-
1. Go to settings
2. Go to Languages
3. Edit the record and edit Locale Code that is "en_US" to anything else.
4. Go to Accounts ==> Sales Receipt (There comes odoo pop up).
Solution 1:-  Either remove hard coded search of language that has been made.
Solution 2 :- Don't allow the Locale code to be edited that can save pain of editing code.

**Comment by qtheuret** [comment] 2015-09-17 13:57
I think Solution 2 is better than solution 1. The language codes are standardized : https://en.wikipedia.org/wiki/Language_code (Odoo seems to use the IETF language tag)

**Comment by chand3040** [comment] 2015-09-17 15:01
Yes even I find that more feasible  as we don't know at how many places that code would have been replicated. Making that non editable would work.

**Comment by rco-odoo** [comment] 2015-10-26 16:24
The issue is fixed on versions `7.0` and `saas-6`.
It will be eventually fixed on versions `8.0` and `9.0` when the above commits will be forward-ported.

**Closed by rco-odoo** 2015-10-26 16:24 UTC
