### ISSUE TITLE
[11/12] Do not add Same products multiple times to Carts from Comparison list

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#28267] opened 2018-10-29 15:56 UTC
Impacted versions: 11/12
Runbot11: http://391126-11-0-bb939f.runbot13.odoo.com/shop/cart
Runbot12:http://391397-12-0-d94e8a.runbot14.odoo.com/shop/cart
Steps to reproduce: 
Add Items to Comparison List
![screenshot 61](https://user-images.githubusercontent.com/16624719/47661227-a1d28e00-dbbe-11e8-9be4-040604167e33.png)
Click multiple times 
Current behavior:
Same product is added multiple times to cart
![screenshot 62](https://user-images.githubusercontent.com/16624719/47661295-c3337a00-dbbe-11e8-9371-58127e3226f8.png)

Expected behavior:
No same item multiple times to cart.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2018-10-29 16:07
I consider this behavior as the expected one, as each time you click on "Add to cart", you add one unit to the cart, and this what people wants when clicking several times. Any way, not a bug, but a user perception.

Closing as no real issue.

**Closed by pedrobaeza** 2018-10-29 16:07 UTC

**Comment by sswapnesh** [comment] 2018-10-29 16:20
> I consider this behavior as the expected one, as each time you click on "Add to cart"

I dont think so, It does not disable Button  (Like it is working at other Place - Wishlist/Comparison/Cart)
On each click it is sending request to server.
![screenshot 63](https://user-images.githubusercontent.com/16624719/47664212-984c2480-dbc4-11e8-96f1-5db02ce7cba8.png)

**Comment by pedrobaeza** [comment] 2018-10-29 16:44
As said by @JKE-be this is user specific preferences, and this shouldn't be treated as issues. It will be generally considered for upper versions what to do on "double clicks".

**Comment by Yenthe666** [comment] 2018-10-29 17:06
Plus you could always make a PR against master with the same behavior of places where you believe it is better.
