### ISSUE TITLE
Odoo v11+Ubuntu 18.04 + 404 on javascript and CSS

### ISSUE THREAD

**Issue by ChristopheLux** [odoo/odoo#32046] opened 2019-03-22 12:47 UTC
Impacted versions:
V11
Steps to reproduce:
Standard Install on Ubuntu 18.04
Current behavior:
CSS+Javascript Not loading
Expected behavior:
CSS and Javascript Laoding

Video/Screenshot link (optional):

Hello Guys

Just installed a CE of Odoo v11 on an up to date Ubuntu 18.04

When behind nginx, some javascript and css are not loading and sending a 404

Install done with this script

 https://github.com/chris001/InstallScript
chris001/InstallScript
Odoo install script. Contribute to chris001/InstallScript development by creating an account on GitHub.
github.com
​

When adding
?debug=assets to the URL the css and javascript are correctly loaded

I have read multiple articles on the forum/Odoo Github about this issue
I have checked the add-on path in odoo-server.conf and everything seems to be ok
Put log on debug level but nothing specials appears

Nginx conf (sanitized)
##Odoo Backend##

upstream odooerp {
    server 127.0.0.1:8069;
}
#upstream odooerp-im {
#    server 127.0.0.1:8072 weight=1 fail_timeout=0;
#}

##https site##
server {
    listen      443 ssl http2;
   
    server_name office.example.com;
   
    root        /usr/share/nginx/html;
    index       index.html index.htm;

    # log files
    access_log  /var/log/nginx/odoo.access.log;
    error_log   /var/log/nginx/odoo.error.log;

    # SSL
    ssl_certificate /etc/letsencrypt/live/office.example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/office.example.com/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/office.example.com/chain.pem;

    # proxy buffers
    proxy_buffers 16 64k;
    proxy_buffer_size 128k;

    # timeouts
    proxy_read_timeout 720s;
    proxy_connect_timeout 720s;
    proxy_send_timeout 720s;

    ## odoo proxypass with https ##
    location / {
        proxy_pass  http://odooerp;
        # force timeouts if the backend dies
        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        proxy_redirect off;

        # set headers
        proxy_set_header    Host            $host;
        proxy_set_header    X-Real-IP       $remote_addr;
        proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Proto https;
    }

    # cache some static data in memory for 60mins
    location ~* /web/static/ {
        proxy_cache_valid 200 60m;
        proxy_buffering on;
        expires 864000;
        proxy_pass http://odooerp;
    }
   
   
   
    include /etc/nginx/nginxconfig.io/general.conf;

}

##http redirects to https ##
server {
    listen      80;
    server_name office.example.com;
   
    include /etc/nginx/nginxconfig.io/letsencrypt.conf;
   
    location / {
        return 301 https://$server_name$request_uri;
    }
}

Thanks in advance

**Comment by pedrobaeza** [comment] 2019-03-22 18:50
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/11.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

**Closed by pedrobaeza** 2019-03-22 18:50 UTC

**Comment by ChristopheLux** [comment] 2019-03-23 07:13
Hello

I have followed the proper installation documentation as per my text. 
I really wish you read it

Thanks

**Comment by gdgellatly** [comment] 2019-03-23 07:51
Hi

Issues are for bugs. You want support. You could try the forums but looks like either bad permissions or bad conf file to me.

Many many people run that stack successfully.
