### ISSUE TITLE
Bug on debit/credit amount while validating invoice with different currency

### ISSUE THREAD

**Issue by bista-kuldeep** [odoo/odoo#16044] opened 2017-03-24 13:13 UTC
Impacted versions:
10.0

Steps to reproduce:
-> Company currency is in USD
-> Activated MXN currency where rate is: 19.095309
-> Created a product with sale price: 100USD
-> Created a invoice with above product and selected the MXN in currency, so it gives unit price: 1909.53 on invoice line for above product
-> Validate the invoice

Current behavior:
After validating the invoice when i check the journal items it shows me 131.29USD in debit/credit instead of 100USD

Expected behavior:
It should add 100USD in debit/credit instead of 131.29USD

See attached video to reproduce the same
[bug.ogv.tar.gz](https://github.com/odoo/odoo/files/867923/bug.ogv.tar.gz)

.

**Comment by pedrobaeza** [comment] 2018-05-22 07:51
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-05-22 07:51 UTC
Labels: 10.0, Accounting
