### ISSUE TITLE
Register payment for multiple invoice with zero. 

### ISSUE THREAD

**Issue by ADVALAKI** [odoo/odoo#34140] opened 2019-06-14 11:07 UTC
Impacted versions: 12.0

Steps to reproduce: 
1. Goto Accounting -> Customers -> Invoices
2. Select multiple invoice from same customer
3. Click on Action button -> Register Payment
4. On Register Payment Wizard change payment value to 0(zero)
it will give traceback.
 

Current behavior: its giving traceback.

Expected behavior: it should handle exception properly. 

Video/Screenshot link (optional):
https://imgur.com/1JfLIdR

Runbot Link: http://539898-12-0-f6d51c.runbot20.odoo.com/web?#action=550&active_id=33&model=account.invoice&view_type=list&menu_id=502

**Comment by Yenthe666** [comment] 2019-06-14 11:27
@qdp-odoo for you

**Comment by sswapnesh** [comment] 2019-06-14 16:05
Duplicate of https://github.com/odoo/odoo/issues/31411 (and PR https://github.com/odoo/odoo/pull/32847 to fix it)

**Comment by C3POdoo** [comment] 2023-03-30 11:49
Dear @ADVALAKI,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._

**Closed by C3POdoo** 2023-03-30 11:49 UTC
Labels: Accounting, 12.0
