### ISSUE TITLE
Favorites Filters Default not working  in Inbox Menu

### ISSUE THREAD

**Issue by prakashjain** [odoo/odoo#22005] opened 2018-01-04 04:50 UTC
Impacted versions:
Version 9.0c (Community Edition) 

Steps to reproduce:
    Menu: Discuss --> Inbox Menu 
    make some search in Inbox . E.g. "Content: @username"
    save that Favorites search and tick "Use by default"
    

Current behavior:
"Inbox" form You can see your filter name default saved in search box, but default filter is not applied and all messages are shown. (When user click favorites filter name then only working).

Expected behavior:
Filter should be applied default 

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment] 2018-01-04 08:06
Hi @prakashjain,

Thanks a lot for your bug report!
I've just tested this and it does look like a bug. @aab-odoo could you have a look at this please?

Regards,
Yenthe

**Comment by prakashjain** [comment] 2018-01-04 09:53
Hi Yenthe,
Below steps followed:-
-- Inbox menu number of message available from different user content field contains @username 
-- Inbox default favorite filters saved Example: Filter Name: **Chat** Conditions: **content=@User1**
-- Inbox form loading favorite filers saved but record not showing based on filters, it showing all record, 
Once user select and click favorite filters name then only working.

Please check the same with data no of records in ( Discuss --> Inbox screen) menu.

**Comment by aab-odoo** [comment] 2018-01-05 15:01
Hello,

The issue is fixed by https://github.com/odoo/odoo/commit/35c829f12b28615351cb306397b1a3dfbfdeaccb.

Regards

**Closed by aab-odoo** 2018-01-05 15:01 UTC
Labels: 9.0

**Comment by Yenthe666** [comment] 2018-01-05 15:29
Tested and it does fit it. Thanks a lot @aab-odoo

**Comment by prakashjain** [comment] 2018-01-06 09:53
Thanks a lot @Yenthe666, @aab-odoo
