### ISSUE TITLE
Odoo version 8.0rc1 Bug : Error when typing seach box in vietnamese

### ISSUE THREAD

**Issue by vquochao** [odoo/odoo#2226] opened 2014-09-06 02:00 UTC
![capture](https://cloud.githubusercontent.com/assets/8382574/4173856/59df3e7c-3569-11e4-80de-7036bd9e8852.PNG)
Who can fix it?

**Comment by Yenthe666** [comment] 2016-06-03 10:37
Hi @vquochao and @davidtranhp,

I can no longer reproduce this issue on the latest codebase:
![image](https://cloud.githubusercontent.com/assets/6352350/15776448/d5243ee8-2987-11e6-8609-f0172aa3bb09.png)
Closing this issue since it has been fixed. If you still face this issue please update your Odoo to the latest codebase.

Regards,
Yenthe

**Closed by Yenthe666** 2016-06-03 10:37 UTC
