### ISSUE TITLE
After update of odoo v9 internet explorer dosn't show any thumbnails anymore

### ISSUE THREAD

**Issue by Stephan-ch** [odoo/odoo#13193] opened 2016-08-17 15:09 UTC
Impacted versions: Version 9.0c-20160817 (Community Edition)

Steps to reproduce: update via yum

Current behavior:

Expected behavior:

Video/Screenshot link (optional):
![ie-error](https://cloud.githubusercontent.com/assets/16590358/17741668/54f241c4-649d-11e6-9b60-8c5b307cb985.jpg)

**Comment by JKE-be** [comment] 2016-08-17 17:06
Hello, need more info...
What is the url of picture ? 
Do you use Filestore ? Folder always present ? 
No error in log ?

**Comment by Stephan-ch** [comment] 2016-08-17 17:30
The URL is a test machine, centos7, vm in vmware which is the same than the production one. The production is running with an older version of odoo v9 (beginn of july), but if I update this one, I get the same result. 
No filestore (virtual disk), no errors in log (resultcode 200). 
If you need an access, write me and I will create one.
First time I got this update issue was with update version of 31st of july

**Comment by JKE-be** [comment] 2016-08-17 18:00
Hello, 
Url: not the host, just the path of your picture... ? 
No filestore ? so all your picture is in your database ? 
By default: store is ~/.local/share/Odoo/filestore/<dbname>/...
That is typically the symptom of missing picture (not transferred between prod and test environment...)

**Comment by Stephan-ch** [comment] 2016-08-17 18:30
I'll collect the data/info and come back...

**Comment by Stephan-ch** [comment] 2016-08-22 08:37
Hi
I haven't testet it on a runbot.
But: Debugging IE Messages: Error: DOM7009: Das Bild unter der URL kann nicht decodiert werden: "http://profib.pferdeprofis-schweiz.ch:89/web/image/product.template/308/image/300x300?unique=6acba87". Datei: 300x300
When I open the same URL in Firefox, it works. 
What changed end of july in odoo??

**Comment by JKE-be** [comment] 2016-08-22 09:28
Hello @Stephan-ch 
Thank you for the reporting, I have just tested and reproduce it on IE.

I give you feedback asap

**Comment by JKE-be** [comment] 2016-08-22 15:21
Hello @Stephan-ch ,
As explain in the commit message, it was due a wrong mimetype returned by odoo.
And since the nosniff header added in July, it break IE picture in some case.

Thank for the reporting again.

**Comment by Stephan-ch** [comment] 2016-08-23 05:24
Good Morning
Please correct the issue in the cart too. 
Thx.

**Comment by JKE-be** [comment] 2016-08-23 20:53
I have just pushed a new fix on v9 now.
Thank you for the reporting again...

fix: odoo/odoo@5a9e1af64acc2e20d1f6e8d982cdd8554e0855ff
test regression: odoo/odoo@498b266f5c81b7f86b33ad3dd36a405495554de0

**Closed by JKE-be** 2016-08-23 20:53 UTC

**Comment by simahawk** [comment] 2016-11-29 11:18
@JKE-be I'm experiencing this issue and I double checked that I have your [fix commit](https://github.com/odoo/odoo/commit/97b702a7b085485b15dfcd3973941cf6dd3f2b55) in my local checkout.

Here's the original image

![ie_odoo_good_original](https://cloud.githubusercontent.com/assets/347149/20707322/41efd94e-b62b-11e6-818d-2d36f7c84d29.png)

and here is the resized version (that works fine on ubuntu and on Firefox on Windows)

![ie_odoo_broken_resized](https://cloud.githubusercontent.com/assets/347149/20707323/41f5714c-b62b-11e6-875c-5238c8a5c077.png)

The headers look the same... I really have no clue...

**Comment by JKE-be** [comment] 2016-11-29 15:49
Hello, Can you host this image (or send by mail to JKE@0D00.C0M)

Thanks

**Comment by simahawk** [comment] 2016-11-29 15:55
@JKE-be you got mail

**Comment by JKE-be** [comment] 2016-11-29 16:01
sorry, It was looking for your coca cola picture (the original image)

**Comment by simahawk** [comment] 2016-11-29 16:05
![cocacola_original](https://cloud.githubusercontent.com/assets/347149/20717512/ff19eac6-b655-11e6-9d48-ed7200ca518a.jpg)

There you go :)

**Comment by JKE-be** [comment] 2016-11-29 16:14
hello @simahawk 

I cannot reproduce your issue.

Can you confirm on this instance that you don't see the iMac img ? 
http://183062-9-0-21148f-all.runbot10.odoo.com/shop

Thanks

**Comment by simahawk** [comment] 2016-11-29 16:29
@JKE-be hmm I see it... could be related to a buggy image lib in the system? or corrupted image on upload?

**Comment by JKE-be** [comment] 2016-11-29 16:31
can you try to upload your picture yourself (because that github upload convert the picture :/) on runbot and check if you got the bug or not.
(When you upload the picture, use the no-optimization mode (sub menu) to be sure to don't convert it )

**Comment by JKE-be** [comment] 2016-11-29 16:34
Maybe you should take a look in odoo/tools/mimetypes.py...
```python
    # magic from pypi https://pypi.python.org/pypi/python-magic/
    if hasattr(magic,'from_buffer'):
        guess_mimetype = lambda bin_data, default=None: magic.from_buffer(bin_data, mime=True)
    # magic from file(1) https://packages.debian.org/squeeze/python-magic
    elif hasattr(magic,'open'):
        ms = magic.open(magic.MAGIC_MIME_TYPE)
        ms.load()
        guess_mimetype = lambda bin_data, default=None: ms.buffer(bin_data)
```

**Comment by simahawk** [comment] 2016-11-30 09:14
I'll have a look, thanks
