### ISSUE TITLE
[12.0] The .po translation broken after commit 9c77066f345360429a0920ca4d17af1f84a7ebea

### ISSUE THREAD

**Issue by jlzhou** [odoo/odoo#27044] opened 2018-09-18 08:59 UTC
Impacted versions:
Master branch, should by 12.0

Steps to reproduce:
Install a third party addon with localization po file in i18n folder, even loading translation manually, the translation won't work, The console reports error: Translation .... not found in reference pot, skipping.
Reverse the change of  "odoo/tools/translate.py" in this commit, the issue was gone.

Expected behavior:
The po translation works as before.

**Comment by mart-e** [comment] 2018-09-18 09:04
Hello,

Could you please detail your report? What module are referring to?
The goal of this commit is to make the .pot file as the reference for your module translations. You must have an up to date .pot file inside your i18n folder.

Can you reproduce the problem with a standard module?

**Comment by jlzhou** [comment] 2018-09-18 10:18
same question

**Comment by mart-e** [comment] 2018-09-18 12:00
Yes, you should always have a POT in the module.
However, I see there is an issue for the manual import wizard. I will work to fix that.

**Comment by pedrobaeza** [comment] 2018-09-18 12:07
Uhm, that's a real limitation in workflows like OCA one, as we recreate automatically the POT file after the PR is merged, but meanwhile, I understand that CIs are going to fail if we have translations included in the PR, but without the POT file.

**Comment by mart-e** [comment] 2018-09-18 12:15
The message is an info, not a warning so that won't be a problem for CIs.
If you check #26134 I gave an example where the desynchronisation between po and pot made an error. We also saw it in production.
So actually, my patch is required as difference would fail due to the unique constraint added recently on ir.translation
(watch out #26925 too for other breaking changes by the way)

**Comment by pedrobaeza** [comment] 2018-09-18 14:37
> The message is an info, not a warning so that won't be a problem for CIs.

Great, that's a relief.

> If you check #26134 I gave an example where the desynchronisation between po and pot made an error. We also saw it in production.
> So actually, my patch is required as difference would fail due to the unique constraint added recently on ir.translation

OK, agreed.

> (watch out #26925 too for other breaking changes by the way)

That's a very important thing for migrations to respect current custom translations. Do you handle legacy format in core or are your migration team will handle this on migration scripts (or not)?

**Comment by KangOl** [comment] 2018-09-18 15:12
> > (watch out #26925 too for other breaking changes by the way)
> 
> That's a very important thing for migrations to respect current custom translations. Do you handle legacy format in core or are your migration team will handle this on migration scripts (or not)?

Yes, migration team will handle it, else new constraints wont be created.

**Comment by pedrobaeza** [comment] 2018-09-18 15:18
@KangOl thanks for the info. It's a pity that we duplicate efforts on this task. You can join @dbo-odoo and me in Odoo XP for a talk on migration thing to see if we can make compatible both worlds.

**Closed** 2018-09-20 08:48 UTC
Labels: Internationalization
