### ISSUE TITLE
CRM - User X can see oppertunities with no <user_id> configured

### ISSUE THREAD

**Issue by Patrickar** [odoo/odoo#23776] opened 2018-03-20 15:14 UTC
**Impacted versions:**
11

**Steps to reproduce:**
Open CRM pipeline and kanban view is presented

**Current behavior:**
- User X has rights: "see own documents only" in CRM setting
- User X can see oppertunities in which no salesperson = <user_id> is configured

Expected behavior:
- User X should ONLY see oppertunities in which he/she is  the sales person <user_id>

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2018-03-21 09:56
Hi @Patrickar,

Sorry, but the intended behavior is the one you have described as current one: a user with "See own documents only" permission can see the opportunities that is assigned, but also the opportunities with nobody assigned. If you don't want this behavior for your use case, you can modify record rules in your DB with your own implementation, but it shouldn't be changed here.

Closing then.

**Closed by pedrobaeza** 2018-03-21 09:56 UTC
Labels: 11.0, Services
