### ISSUE TITLE
POS Invoice State is Open even after validate POS session

### ISSUE THREAD

**Issue by mfaheemkhan6** [odoo/odoo#5075] opened 2015-02-04 20:50 UTC
1: Generate an invoice from POS Front End for example for "Axelor" in demo data.
2: Without closing pos session, go to accounting > Customer and open the customer (Axelor) that previously invoiced in POS and click accounting tab.
3: You will see the payment of that invoice shown as receivable. 
4: Now pay the invoice by registering payment from related invoice or receive payment in accounting > customer payments. Then recheck the customer account. It had 0.0 receivable now. 
5: Now go to Point of sale and close and validate session. then again go and check the customer balance again. You will see the payment receivable as -2000 or whatever is in invoice.

Expected Solutions

1st solution: (Recommended and can be used for credit sales) To invoice an order it should not be compulsory to select payment method and this invoice should remain unpaid. Its payment should handled in accounting module. To achieve this task order should be converted to simple sale order (Sales Module) in back end instead of POS Order. 

2nd solution: If in case above solution is not acceptable (in case) then when we close POS session and validate it, invoice state should be changed from open to paid.

**Comment by TheCloneMaster** [comment] 2015-02-04 21:33
Hi, is this using regular POS or my version?

There have been a couple fixes since I send you the module...

Regards,
-Mario

**Comment by mfaheemkhan6** [comment] 2015-02-04 21:36
This is using regular POS.

**Comment by mfaheemkhan6** [comment] 2015-02-19 10:05
Is someone watch into this?

**Comment by Tiffa-Dakota** [comment] 2015-04-09 15:28
I have the same issue and no solution

**Comment by alejandroperezcosio** [comment] 2015-04-30 19:13
Have the same issue

**Comment by GeertSurkijn** [comment] 2015-06-04 16:21
This was also an issue in v7, so migrating to v8 seems not to help for this...

**Comment by alejandroperezcosio** [comment] 2015-06-04 18:22
Also waiting for a fix for this..
As a workaround, you can conciliate the payment from the accounting menu, that will change the state of the invoice to “Paid”.
This is not the best way to do this but it will maybe allow you to continue selling for now..
I would also know if someone is working to fix this issue.. 

Regards
—
Alejandro

**Comment by joanbarros** [comment] 2015-11-17 16:51
I don't see this as a bug...

The way I see it you select Validate on the POS when you receive a payment imediatelly. But if you don't receive the payment right away and would like to register an invoice for later payment. Then you could select the Invoice option in the POS and keep the Invoice open until the client comes around and pays for it.

Right now the problem I'm seeing is that there's no way to make the POS to create the Invoice and NOT generate a payment. When you validate the POS session, an entry is made to the Sales Journal and the payment is registered. Regardless of the Invoice that was created.

I think this is a big inconsistency in the flow of the information and I don't see how this could work for someone.

Does anyone handle this kind of cases successfully? if so, how do you do it?

**Comment by GeertSurkijn** [comment] 2015-11-18 08:22
If you have a POS up and running you are selling directly to customers, with payment done immediately, it is possible to ask an invoice. It is common sense that this invoice is needed to be set as paid (which is not done correctly in accounting currently). When you have a customer willing to pay afterwards, you have a sales order with delivery, not a POS sale. POS is made for selling immediately and keeping your cash books in order.

So I, and all projects up to know think this is the way to go at the POS. If this happens a lot at the POS we advise to open 2 tabs, one with the POS one with the sales order screen activated...

**Comment by joanbarros** [comment] 2015-12-29 15:01
Yes, you could have 2 tabs open and use 2 different interfaces with 2 different processes for this small difference.

IMHO in some types of business a customer often purchases stuff with credit and I don't see it that a big of a deal to implement in the POS to justify using a completely different process for this one case.

POS should allow to register orders as not paid and pending payment. It could be an option you have to enable and not the default behavior of the POS. When enabled in the configs you could have the option to take orders on credit on the POS.

**Comment by mohamedhagag** [comment] 2016-04-08 07:26
Just in case that there are people still looking for a fix, here is a simple module that will auto reconcile the invoice with its payment so the invoice will be paid.

https://github.com/mohamedhagag/dvit-odoo8/tree/master/pos_invoice_payment_auto_reconcile

**Comment by renepuigb** [comment] 2017-04-07 01:06
thanks mohamedhagag

**Comment by mohamedhagag** [comment] 2017-04-07 02:57
anytime @renepuigb - the module now is called pos_fixes in the same repo.
also it have been ported to v 10.0 in the same repo / 10.0 branch

**Comment by Yenthe666** [comment] 2017-12-13 13:05
Hi @mfaheemkhan6 ,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Closed by Yenthe666** 2017-12-13 13:05 UTC
Labels: Logistics

**Comment by tchigy** [comment] 2018-01-26 16:51
Every body who is still want to reconcile payment in pos invoice. this don't just reconcile payment but also enable partial payment so to invoice the order client don't have to pay the whole amount. payment are automatically reconciled and payment are saved on the invoice.

  [https://apps.odoo.com/apps/modules/8.0/pos_invoice_reconcile/](POS Invoice reconcile)
