### ISSUE TITLE
Widget "Add a line" and unlink icon it does not work from fields many2many

### ISSUE THREAD

**Issue by JulioSerna** [odoo/odoo#50709] opened 2020-05-06 04:57 UTC
Impacted versions:
* 12.0

Steps to reproduce:
* create a relation many2many e.g. from mrp.production add Many2many fields to res.partner
* Ensure that user(User: Test) have access right to relation Many2many in this case res.partner, but only access to **Read** 

Current behavior:
If the user(User: Test) wants to add one line from Many2many field he can not do that because the widget "Add a line" it is invisible
![Desktop_screenshot (2)](https://user-images.githubusercontent.com/7595505/81139653-190f7d80-8f2c-11ea-8e64-a59240673a74.png)

Expected behavior:
The user(User: Test) must see "Add a line" and add res.partner in Many2many field,
because he can read res.partner and we are no creating or writing or unlink

**Comment by Yenthe666** [comment] 2020-05-06 06:35
Maybe I misunderstand you but isn't this exactly what it should do? You only give read rights so the user does not get the "Add a line" button because he has no write rights?
@pedrobaeza do I miss something?

**Comment by JulioSerna** [comment] 2020-05-06 09:38
@Yenthe666 

but this field it is a many2many it is no make any write to res.partner isn't?

In fact, with access to write it is not working only with access to create, and I said in the description of the issue we are not creating any record into res.partner

**Comment by pedrobaeza** [comment] 2020-05-06 11:40
I'm afraid this is an old question that has been treated in #18987 or #29227, but I agree it's not correct at all, as you don't need create nor delete permissions for managing m2m items. The problem comes on how this is technically managed, inheriting from the same relation widget, and not having specific code for m2m.

@VincentSchippefilt @ged-odoo I think this deserves to be fixed in supported versions, and the fix shouldn't be very difficult. The only doubt I have is about how to handle in the popup specific "Create" button.

**Comment by Yenthe666** [comment] 2020-05-06 12:01
Sorry, I initially misunderstood you :) Indeed, this could be improved/fixed.

**Comment by sswapnesh** [comment] 2020-05-06 19:27
For now, You can use widget `many2many_tags` here which will work in this case.

**Comment by Yenthe666** [comment] 2020-05-13 11:54
OPW `2256837`

**Comment by sswapnesh** [comment] 2020-05-19 15:33
@Yenthe666 I think this will not be fixed on Stable
See https://github.com/odoo/odoo/pull/51510#pullrequestreview-414409412

**Comment by Yenthe666** [comment] 2020-05-19 19:40
Even if it's fixed or improved in the next version I'm happy honestly :) small steps forward

**Comment by Yenthe666** [comment] 2020-05-25 13:33
Quoting:

> After a further investigation, it seems that what you are reporting is a missing feature. Actually, when the user doesn't have create access on a model, it adds 'create="false"' on the view and this makes the field read only (no access to "add a line" anymore).

> I agree this is not very clear but since this behavior is used many times in our code base and in customers' customization, we can't fix this in stable versions.

> We use a lot create="false" to hide the "add a line" text because a many2many could be two way, so sometimes even if you write on one end you will still write on the other end.

> There are two workarounds for your issue:
  Use many2many_widgets which is not looking at access rights,
  Create a child of the res.partner tree view with "<attribute name="create">1</attribute>" and add context="{'tree_view_ref': 'your_new_tree_xmlid''}"  options="{'no_create': True}" on the m2m field.

> I will report this to our R&D team to improve this behavior.

Since it is confirmed, there is an internal task and since it is not being fixed in stable I'm closing this one.

**Closed by Yenthe666** 2020-05-25 13:33 UTC
Labels: 12.0, 13.0, Framework, OE
