### ISSUE TITLE
Invalid field 'parent_id' on model 'crm.lead'

### ISSUE THREAD

**Issue by crece365** [odoo/odoo#60223] opened 2020-10-18 19:31 UTC
Impacted versions: 14.0

Steps to reproduce: 

In a clean installation of Odoo enterprise with the Crm module, create an opportunity, when trying to access the form the following error appears:

![image](https://user-images.githubusercontent.com/50924836/96377677-bf52e680-114c-11eb-8b25-f69cde4bf3aa.png)

![image](https://user-images.githubusercontent.com/50924836/96377688-caa61200-114c-11eb-969d-d35663a5ab88.png)

Current behavior:

It prevents access to the opportunity and displays a message:

`Error:
Odoo Server Error

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/local/lib/python3.7/site-packages/odoo/http.py", line 682, in dispatch
    result = self._call_function(**self.params)
  File "/usr/local/lib/python3.7/site-packages/odoo/http.py", line 358, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/odoo/http.py", line 346, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/local/lib/python3.7/site-packages/odoo/http.py", line 911, in __call__
    return self.method(*args, **kw)
  File "/usr/local/lib/python3.7/site-packages/odoo/http.py", line 530, in response_wrap
    response = f(*args, **kw)
  File "/usr/local/lib/python3.7/site-packages/odoo/addons/web/controllers/main.py", line 1359, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/local/lib/python3.7/site-packages/odoo/addons/web/controllers/main.py", line 1351, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/local/lib/python3.7/site-packages/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/local/lib/python3.7/site-packages/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/odoo/models.py", line 2990, in read
    raise ValueError("Invalid field %r on model %r" % (name, self._name))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/local/lib/python3.7/site-packages/odoo/http.py", line 314, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Invalid field 'parent_id' on model 'crm.lead'`
Expected behavior:
```

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2020-10-18 22:13
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Yenthe666** [comment] 2020-10-19 07:05
Saw this one before too but can't reproduce it on the latest 14.0 anymore. Can you update your code & test again?
Pedro his steps should help you :)

**Comment by pedrobaeza** [comment] 2020-10-19 07:12
Yeah, but if the user can't reproduce it in runbot, then there's nothing more to do...

**Comment by crece365** [comment] 2020-10-19 09:32
It cannot be reproduced in runbot because it only manifests itself in a totally clean database, in runbot the database already has test data and apparently the problem is skipped.

I just reproduced the error in a new instance of odoo online, I have created a test user for you to validate:

https://odooparatodos.odoo.com/web/login
user: admin@odoo.com
password: admin

@Yenthe666 @pedrobaeza

**Comment by pedrobaeza** [comment] 2020-10-19 09:58
Maybe Odoo online doesn't contain same code as runbot. I know this happens with Odoo.sh, that they updated code regularly, but not on real time. Can it be, Yenthe?

**Comment by crece365** [comment] 2020-10-19 10:13
I have replicated it at my local with the latest nightly, https://nightly.odoo.com/14.0/nightly/. The reason it is not replicated in the runbot is because of the test data.

I have tested in my premises, without test data the error appears, with test data the error does not appear.

**Comment by alt-odoo** [comment] 2020-10-19 11:44
We are aware of this issue (currently under investigation by BugFix).

It is related to the field 'Input View' of some countries that is set, and contains some references to parent_id field (known cases : Mexico, Peru).

The workaround is to empty the field 'address_view_id' (visible in debug mode) on the concerned res.country.

**Comment by crece365** [comment] 2020-10-19 11:52
> We are aware of this issue (currently under investigation by BugFix).
> 
> It is related to the field 'Input View' of some countries that is set, and contains some references to parent_id field (known cases : Mexico, Peru).
> 
> The workaround is to empty the field 'address_view_id' (visible in debug mode) on the concerned res.country.

This works for me

**Comment by alt-odoo** [comment] 2020-10-23 13:20
This was fixed here : https://github.com/odoo/odoo/commit/3229239c2a738cc99820dba0fce1bd1c2a3536ea

**Comment by pedrobaeza** [comment] 2020-10-23 14:05
Thanks for the follow-up. Closing then.

**Closed by pedrobaeza** 2020-10-23 14:05 UTC
Labels: 14.0, Marketing
