### ISSUE TITLE
Favorites messages count 1 but no one favorite message

### ISSUE THREAD

**Issue by Alexandre-Bernardes** [odoo/odoo#33346] opened 2019-05-13 19:31 UTC
Impacted versions: v11

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

![Opera Instantâneo_2019-05-13_162520_jarvis](https://user-images.githubusercontent.com/12830044/57648681-851b0800-759c-11e9-9baf-273b91a50a3b.png)

**Comment by pedrobaeza** [comment] 2019-05-13 22:03
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Alexandre-Bernardes** [comment] 2019-05-14 12:38
Hi Pedro,
I can not reproduce on runbot.
Log file has no info on this error that just appeared out of nowhere!
I'll check out custom modules and try debugging.
Thank you.

**Closed** 2019-05-14 12:38 UTC
Labels: Need information
