### ISSUE TITLE
Down payment Invoice report issue

### ISSUE THREAD

**Issue by devangishindeitmcs** [odoo/odoo#27751] opened 2018-10-13 12:18 UTC
Impacted versions: v12

![error2](https://user-images.githubusercontent.com/40557860/46905351-15fb0980-cf10-11e8-94a8-460fa64db4e4.png)

![error1](https://user-images.githubusercontent.com/40557860/46905342-f1069680-cf0f-11e8-8986-e5c14a252d37.png)

**Comment by sswapnesh** [comment] 2018-10-13 14:54
Duplicate of #27459 and  and Resolved in 9a6f245.

**Comment by pedrobaeza** [comment] 2018-10-13 16:30
@sswapnesh the commit doesn't seem to be linked to this

**Comment by sswapnesh** [comment] 2018-10-13 16:45
Added correct, BTW Looks like @robodoo added wrong Commit reference in https://github.com/odoo/odoo/pull/27669
![screenshot 5](https://user-images.githubusercontent.com/16624719/46907780-6769bf80-cf35-11e8-952a-851e0d1e11b2.png)

**Comment by pedrobaeza** [comment] 2018-10-13 16:48
Thanks for the new link. Closing this then.

@mart-e maybe you should check robodoo to see why it puts incorrect SHA1 references.

**Closed by pedrobaeza** 2018-10-13 16:48 UTC

**Comment by mart-e** [comment] 2018-10-15 06:07
The reference is not the commit that did close the PR. If robodoo merges several PRs at the same time (which is one of the advantage of the bot, to batch the merges), the message will be the same on every PR closed in the batch. Understand the message as "closed in the merge batch with the reference ..."

The correct commit is still referenced with a "closes odoo/odoo#..." in the message.
For this PR it is ea091e4c40c7faf8e9534727b3c0623190043c39

However, I agree it is not clear and we will probably just get rid of the closing message.
