### ISSUE TITLE
AssertionError: Fields in 'groupby' must be regular database-persisted fields.. while clisking on dashboard menu

### ISSUE THREAD

**Issue by oumaima92** [odoo/odoo#24558] opened 2018-05-03 17:11 UTC
I'm working on Odoo 10. When I clock on the dashboard menu, i'm getting the following error:
![image](https://user-images.githubusercontent.com/38957724/39591594-1f2d218a-4efc-11e8-9341-d79987f5f762.png)
Here is the xml code:

![image](https://user-images.githubusercontent.com/38957724/39591965-4ea8ef7e-4efd-11e8-8446-ca378310d38c.png)

![image](https://user-images.githubusercontent.com/38957724/39591974-586d7d72-4efd-11e8-8a16-e9d1ba6f2bac.png)

![image](https://user-images.githubusercontent.com/38957724/39591989-61c13bde-4efd-11e8-841f-34063c68b5fb.png)

The biblio.inscription model is : 

![image](https://user-images.githubusercontent.com/38957724/39591712-731e561a-4efc-11e8-8d4d-f0fb6bbfd4bd.png)

The biblioth.livre model is:

![image](https://user-images.githubusercontent.com/38957724/39591806-c9550eb6-4efc-11e8-9d4b-69b05dba2da0.png)

I've added the depends in the _manifest_.py but it doesn't work, it gives me the error above ...any suggestions please? Thank you!

**Comment by pedrobaeza** [comment] 2018-05-03 17:17
Sorry, but the error you are mentioning corresponds to a custom module, so the problem is there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this. In concrete, you can't use a field that is not stored as groupby element.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

**Closed by pedrobaeza** 2018-05-03 17:17 UTC
