### ISSUE TITLE
Error when validate holidays

### ISSUE THREAD

**Issue by diezcode** [odoo/odoo#10079] opened 2015-12-15 10:14 UTC
I getting an error while I try to validate the holidays of the employees.
See the screenshots:
![1](https://cloud.githubusercontent.com/assets/7522882/11807856/ee09fab6-a31c-11e5-9a1c-dc7fc46d37d6.PNG)
![2](https://cloud.githubusercontent.com/assets/7522882/11807859/f10725ae-a31c-11e5-80e7-3bd475a83cc6.PNG)
![3](https://cloud.githubusercontent.com/assets/7522882/11807861/f2362ce0-a31c-11e5-8f93-cf648a999167.PNG)
![4](https://cloud.githubusercontent.com/assets/7522882/11807863/f32cc212-a31c-11e5-8b2c-0e90d77446ff.PNG)

I have no idea what the problem is there. Can someone help me ?

**Comment by Yenthe666** [comment] 2016-06-15 10:52
Hi @diezcode,

I've just tested this on the latest codebase and this issue has been fixed in the meanwhile.
If you still face this problem please update your Odoo to the latest codebase and it'll be fixed.
Closing this since it can no longer be reproduced.

Regards,
Yenthe

**Closed by Yenthe666** 2016-06-15 10:52 UTC
