### ISSUE TITLE
Error on account_tax_periodicity_journal installing l10n directly from account_accountant module

### ISSUE THREAD

**Issue by aliencrash** [odoo/odoo#56621] opened 2020-08-26 23:54 UTC
Impacted versions:
13.0
Steps to reproduce:
We have our current localization and it was installable in previous release of version 13.0. I took a nigthly and notice the issue presented below. 

To explain, the problem is that our accounting localization is developed to be 0 configuration after installing. Thus when we install our module it will automatically configure some information. But the problem I believe is, that when the database is empty and we are configuring data in res.company it will call automatically the write method from file account_reports/res_company.py. The issue is that since we are installing the localization this will prompt a call to set the field journal_id  with account_tax_periodicity_journal_id id which doesn't exists yet. 

This only happen if we install the accounting module directly. If the installation is done by first installing invoicing everything it's ok.

Current behavior:
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/alien/odoo/13/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/alien/odoo/13/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/alien/odoo/13/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/home/alien/odoo/13/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/home/alien/odoo/13/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/alien/odoo/13/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/alien/odoo/13/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/alien/odoo/13/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/home/alien/odoo/13/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/alien/odoo/13/odoo/odoo/addons/web/controllers/main.py", line 1326, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/alien/odoo/13/odoo/odoo/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/alien/odoo/13/odoo/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/alien/odoo/13/odoo/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-59>", line 2, in button_immediate_install
  File "/home/alien/odoo/13/odoo/odoo/addons/base/models/ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/alien/odoo/13/odoo/odoo/addons/base/models/ir_module.py", line 463, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/alien/odoo/13/odoo/odoo/addons/base/models/ir_module.py", line 573, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/alien/odoo/13/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/alien/odoo/13/odoo/odoo/modules/loading.py", line 423, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/home/alien/odoo/13/odoo/odoo/modules/loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/alien/odoo/13/odoo/odoo/modules/loading.py", line 225, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/home/alien/odoo/13/odoo/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/home/alien/odoo/13/odoo/odoo/tools/convert.py", line 736, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/alien/odoo/13/odoo/odoo/tools/convert.py", line 803, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/alien/odoo/13/odoo/odoo/tools/convert.py", line 721, in parse
    exc_info[2]
  File "/home/alien/odoo/13/odoo/odoo/tools/pycompat.py", line 13, in reraise
    raise value.with_traceback(tb)
  File "/home/alien/odoo/13/odoo/odoo/tools/convert.py", line 712, in parse
    self._tag_root(de)
  File "/home/alien/odoo/13/odoo/odoo/tools/convert.py", line 674, in _tag_root
    f(rec)
  File "/home/alien/odoo/13/odoo/odoo/tools/convert.py", line 674, in _tag_root
    f(rec)
  File "/home/alien/odoo/13/odoo/odoo/tools/convert.py", line 332, in _tag_function
    _eval_xml(self, rec, env)
  File "/home/alien/odoo/13/odoo/odoo/tools/convert.py", line 204, in _eval_xml
    return odoo.api.call_kw(model, method_name, args, kwargs)
  File "/home/alien/odoo/13/odoo/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/alien/odoo/13/odoo/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/alien/odoo/13/odoo/odoo/addons/account/models/chart_template.py", line 160, in try_loading
    template.with_context(default_company_id=company.id)._load(15.0, 15.0, company)
  File "/home/alien/odoo/13/enterprise/account_followup/models/chart_template.py", line 10, in _load
    res = super(AccountChartTemplate, self)._load(sale_tax_rate, purchase_tax_rate, company)
  File "/home/alien/odoo/13/enterprise/account_reports/models/chart_template.py", line 25, in _load
    self.env['res.config.settings'].with_context(company=company)._create_edit_tax_reminder(vals)
  File "/home/alien/odoo/13/enterprise/account_reports/models/res_config_settings.py", line 99, in _create_edit_tax_reminder
    'ref': _('Tax Return for %s') % (formatted_date,)
  File "<decorator-gen-138>", line 2, in create
  File "/home/alien/odoo/13/odoo/odoo/api.py", line 335, in _model_create_multi
    return create(self, [arg])
  File "/home/alien/odoo/13/odoo/odoo/addons/account/models/account_move.py", line 1665, in create
    return super(AccountMove, self).create(vals_list)
  File "<decorator-gen-109>", line 2, in create
  File "/home/alien/odoo/13/odoo/odoo/api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "/home/alien/odoo/13/odoo/odoo/addons/mail/models/mail_thread.py", line 268, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/home/alien/odoo/13/odoo/odoo/api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "/home/alien/odoo/13/odoo/odoo/models.py", line 3746, in create
    records = self._create(data_list)
  File "/home/alien/odoo/13/odoo/odoo/models.py", line 3852, in _create
    cr.execute(query, params)
  File "/home/alien/odoo/13/odoo/odoo/sql_db.py", line 168, in wrapper
    return f(self, *args, **kwargs)
  File "/home/alien/odoo/13/odoo/odoo/sql_db.py", line 245, in execute
    res = self._obj.execute(query, params)
odoo.tools.convert.ParseError: "null value in column "journal_id" violates not-null constraint
DETAIL:  Failing row contains (6, /, 2020-09-30, Tax Return for September, null, draft, entry, f, null, 1, 48, null, null, null, null, null, null, null, null, null, null, null, f, null, null, 1, null, null, null, null, f, null, null, null, null, null, null, null, null, null, null, null, 1, 2020-08-26 23:25:45.508529, 1, 2020-08-26 23:25:45.508529, null, no_extract_requested, null, -1, null, t, null, null, null, null, null, null, null, 0, null, null, null, null, null, null, N).
" while parsing /home/alien/odoo/13/addons/l10n_ao/data/account_chart_configure_template.xml:2, near

Expected behavior:
Should not call write method if we are installing or set the  journal_id not as required during installation
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2020-08-27 07:00
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2020-08-27 07:00 UTC
