### ISSUE TITLE
Calendar event with recursion start time change

### ISSUE THREAD

**Issue by ertus-odoo** [odoo/odoo#26993] opened 2018-09-14 10:00 UTC
Impacted versions:
Odoo 10.0 Enterprise Edition, French database, Paris,French Timezone

Steps to reproduce:
Create calendar event with recursion between September 2018 and December 2018 every week at 10a.m.  

Current behavior:
From October, events start time change to 9a.m...

Expected behavior:
Do not change the time of the event.

Video/Screenshot link (optional):
https://drive.google.com/file/d/1Tlr8tiORvI-U5GBIY2uzGkRVZ5SJNgSc/view

**Comment by ertus-odoo** [comment] 2018-10-19 09:03
Up!

**Comment by pedrobaeza** [comment] 2018-10-19 09:08
This is because you have in between the DST hour change. @mart-e can you check this one?

**Comment by Yenthe666** [comment] 2018-10-19 09:08
Basically duplicate of https://github.com/odoo/odoo/issues/9268 but for another version I assume.

**Comment by pedrobaeza** [comment] 2018-10-19 09:13
Exactly! So closing in favor of the other one.

**Closed by pedrobaeza** 2018-10-19 09:13 UTC
Labels: 10.0, Services
