### ISSUE TITLE
Creating product results in "TypeError: cur is undefined"

### ISSUE THREAD

**Issue by dvatp** [odoo/odoo#9394] opened 2015-11-03 18:02 UTC
After cloning 9.0, commit id:

e3287faee69a8afe958e91baa3f96739bcd30e26

I began experimenting and configuring the application.

I attempted to create several products but never actually created them -- I just clicked discard.  But the point to take home is that I was able to display the product dialog without error.

I installed several modules I thought I would need and then upon reflection decided to remove a few of them.  Unfortunately I did not keep track of the modules I removed.

After this any attempt to create a product consistently results in the error:

Error: QWeb2 - template['FieldMany2ManyTag']: Runtime Error: TypeError: cur is undefined

Once I acknowledge the error dialog the "create product" dialog / page appears.

I have the database (about ~3MB) that results in this error.  It does not contain any significant personal data so I can provide it to the developer looking at this issue.

I attempted to attach the stack trace as a text file but apparently that is not supported, so here it is:

---

http://10.10.20.40/web/content/249-b4577cb/web.assets_common.js:2444
Traceback:
QWeb2.tools.exception@http://10.10.20.40/web/content/249-b4577cb/web.assets_common.js:2444:7
anonymous@http://10.10.20.40/web/content/249-b4577cb/web.assets_common.js line 2478 > Function:31:8
._render@http://10.10.20.40/web/content/249-b4577cb/web.assets_common.js:2477:262
.render@http://10.10.20.40/web/content/249-b4577cb/web.assets_common.js:2477:146
FieldMany2ManyTags<.render_tag@http://10.10.20.40/web/content/382-3c768ad/web.assets_backend.js:3765
:3645
FieldMany2ManyTags<.render_value/handle_names@http://10.10.20.40/web/content/382-3c768ad/web.assets_
backend.js:3766:125
jQuery.Callbacks/fire@http://10.10.20.40/web/content/249-b4577cb/web.assets_common.js:644:281
jQuery.Callbacks/self.fireWith@http://10.10.20.40/web/content/249-b4577cb/web.assets_common.js:649:1
98
.Deferred/</deferred[tuple[0]]@http://10.10.20.40/web/content/249-b4577cb/web.assets_common.js:651:3
1
DropMisordered<.add/<@http://10.10.20.40/web/content/249-b4577cb/web.assets_common.js:2721:259
jQuery.Callbacks/fire@http://10.10.20.40/web/content/249-b4577cb/web.assets_common.js:644:281
jQuery.Callbacks/self.fireWith@http://10.10.20.40/web/content/249-b4577cb/web.assets_common.js:649:1
98
.Deferred/</deferred[tuple[0]]@http://10.10.20.40/web/content/249-b4577cb/web.assets_common.js:651:3
1
jQuery.Callbacks/fire@http://10.10.20.40/web/content/249-b4577cb/web.assets_common.js:644:281
jQuery.Callbacks/self.fireWith@http://10.10.20.40/web/content/249-b4577cb/web.assets_common.js:649:1
98
.Deferred/</deferred[tuple[0]]@http://10.10.20.40/web/content/249-b4577cb/web.assets_common.js:651:3
1
jQuery.Callbacks/fire@http://10.10.20.40/web/content/249-b4577cb/web.assets_common.js:644:281
jQuery.Callbacks/self.add@http://10.10.20.40/web/content/249-b4577cb/web.assets_common.js:645:467
.Deferred/promise.then/</</<@http://10.10.20.40/web/content/249-b4577cb/web.assets_common.js:650:753
jQuery.Callbacks/fire@http://10.10.20.40/web/content/249-b4577cb/web.assets_common.js:644:281
jQuery.Callbacks/self.fireWith@http://10.10.20.40/web/content/249-b4577cb/web.assets_common.js:649:1
98
.Deferred/</deferred[tuple[0]]@http://10.10.20.40/web/content/249-b4577cb/web.assets_common.js:651:3
1
BufferedDataSet<.read_ids/</<@http://10.10.20.40/web/content/382-3c768ad/web.assets_backend.js:3212:
280
.Deferred/promise.then/</</<@http://10.10.20.40/web/content/249-b4577cb/web.assets_common.js:650:678
jQuery.Callbacks/fire@http://10.10.20.40/web/content/249-b4577cb/web.assets_common.js:644:281
jQuery.Callbacks/self.fireWith@http://10.10.20.40/web/content/249-b4577cb/web.assets_common.js:649:1
98
.Deferred/promise.then/</</<@http://10.10.20.40/web/content/249-b4577cb/web.assets_common.js:650:849
jQuery.Callbacks/fire@http://10.10.20.40/web/content/249-b4577cb/web.assets_common.js:644:281
jQuery.Callbacks/self.fireWith@http://10.10.20.40/web/content/249-b4577cb/web.assets_common.js:649:1
98
.Deferred/</deferred[tuple[0]]@http://10.10.20.40/web/content/249-b4577cb/web.assets_common.js:651:3
1
jQuery.Callbacks/fire@http://10.10.20.40/web/content/249-b4577cb/web.assets_common.js:644:281
jQuery.Callbacks/self.fireWith@http://10.10.20.40/web/content/249-b4577cb/web.assets_common.js:649:1
98
.Deferred/promise.then/</</<@http://10.10.20.40/web/content/249-b4577cb/web.assets_common.js:650:849
jQuery.Callbacks/fire@http://10.10.20.40/web/content/249-b4577cb/web.assets_common.js:644:281
jQuery.Callbacks/self.fireWith@http://10.10.20.40/web/content/249-b4577cb/web.assets_common.js:649:1
98
.Deferred/promise.then/</</<@http://10.10.20.40/web/content/249-b4577cb/web.assets_common.js:650:849
jQuery.Callbacks/fire@http://10.10.20.40/web/content/249-b4577cb/web.assets_common.js:644:281
jQuery.Callbacks/self.fireWith@http://10.10.20.40/web/content/249-b4577cb/web.assets_common.js:649:1
98
done@http://10.10.20.40/web/content/249-b4577cb/web.assets_common.js:1040:86
.send/callback@http://10.10.20.40/web/content/249-b4577cb/web.assets_common.js:1060:15

**Comment by dvatp** [comment] 2015-11-03 19:40
In an attempt to recreate the scenario that caused the error as well as get back to a point I could actually begin using the application I deleted the database and initialized everything from scratch.

I then installed the modules I needed, starting with the MRP / manufacturing module.  After this I attempted to create a product.  No error occurred.

I then added the following modules and after each one again tried to verify if that particular module would recreate the error but I was unsuccessful -- I could not generate the error again.

Purchase Management
Accounting and Finance
Sales Management

It is possible this issue is caused by a database inconsistency that occurs as a consequence of removing a module, not adding it.

**Comment by pedrobaeza** [comment] 2018-04-10 00:47
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-04-10 00:47 UTC
