### ISSUE TITLE
QWeb2: Template 'ActionManager' not found

### ISSUE THREAD

**Issue by jshah4015** [odoo/odoo#21331] opened 2017-11-29 15:37 UTC
-Impacted versions:
Odoo 10.0Community

-Steps to reproduce:
Installed Odoo 10.0 on Windows from Scratch
Created new Db
Logged in and it does not show Menu
[Note : on other Node it works fine, but doesn't work on my server. I had installed Odoo 11.0 and Odoo 10.0, due to some issues, I uninstalled all versions and then installed Odoo 10 latest version on 25/11/2017]

-Current behavior:
After Logging in, Menu is not shown as in picture. 
No Error in Log File [Every Requests are having Status 200]
Error in Console of Browser is >

Uncaught Error: QWeb2: Template 'ActionManager' not found
    at Object.exception (web.assets_common.js:2908)
    at Engine._render (web.assets_common.js:2953)
    at Engine.render (web.assets_common.js:2949)
    at Class.renderElement (web.assets_common.js:3113)
    at web.assets_common.js:3113
    at web.assets_common.js:547
    at fire (web.assets_common.js:541)
    at Object.add [as done] (web.assets_common.js:542)
    at Array.<anonymous> (web.assets_common.js:547)
    at Function.each (web.assets_common.js:370)

Uncaught Error: QWeb2: Template 'CrashManager.error' not found
    at Object.exception (web.assets_common.js:2908)
    at Engine._render (web.assets_common.js:2953)
    at Engine.render (web.assets_common.js:2949)
    at Class.show_error (web.assets_backend.js:1828)
    at window.onerror (web.assets_backend.js:1716)

Furthermore after debugging, I found out this particular error >
ReferenceError: expressions_cache is not defined↵    at eval (eval at <anonymous> (http://localhost:8069/web/content/251-99734bc/web.assets_common.js:2907:11), <anonymous>:1:1)↵    at http://localhost:8069/web/content/251-99734bc/web.assets_common.js:2907:11

From log, I assume that every modules are loaded properly but it is not rendered somehow.

-Expected behavior:
It should show Menu properly and load everything

-Video/Screenshot link (optional):
![error_pic](https://user-images.githubusercontent.com/18393937/33383405-3db9ec1e-d549-11e7-83d8-763e765cf45b.PNG)

**Comment by Yenthe666** [comment] 2017-11-29 17:14
@ged-odoo does it ring any bell to you?

**Comment by jshah4015** [comment] 2017-11-29 17:19
No, I've no idea of this error. Can you explain me through this, why am I getting this error?

**Comment by sswapnesh** [comment] 2017-11-29 18:25
Related to #21117 (Both refers to installation on Windows)

**Comment by sswapnesh** [comment] 2017-11-29 18:28
@jshah4015 You can try this module [Fix Error Blank Page
](https://apps.odoo.com/apps/modules/10.0/web_fix_blank_page/).

**Comment by jshah4015** [comment] 2017-11-29 18:32
@sswapnesh I have already done the modification related to Mimetype issue, after that I get this error message on Action manager

**Comment by Yenthe666** [comment] 2017-12-29 10:22
@mart-e you gave feedback on https://github.com/odoo/odoo/issues/21117 and closed it but we have another bug report about this. Perhaps this gives you a better idea?

**Comment by fredericgermain** [comment] 2017-12-30 16:29
I had what seems is this exact error on odoo 11 when I have a crash at init because of a broken python dependency (https://apps.odoo.com/apps/modules/11.0/auto_backup/ needs paramiko)

did you check your odoo log at init ?

**Comment by Yenthe666** [comment] 2018-01-02 07:45
@fredericgermain the auto_backup module should give an error when you click on install if the dependency is not on your operating system. I've built this in at https://github.com/Yenthe666/auto_backup/blob/11.0/auto_backup/models/db_backup.py#L23-L27

**Comment by fredericgermain** [comment] 2018-01-02 09:09
I'm an odoo newbie... I didn't install auto_backup the right way... Thanks for the extra checks here!

I meant this error is maybe related to many different kinds of error at init, maybe by some other addon modules.

**Comment by mart-e** [comment] 2018-01-02 10:06
Please, give the errors in asset debug mode (going to `/web?debug=assets` page on your Odoo instance, e.g. http://localhost:8069/web?debug=assets)

**Comment by mart-e** [comment] 2018-01-02 10:07
Please, give the errors in asset debug mode (going to `/web?debug=assets` page on your Odoo instance, e.g. http://localhost:8069/web?debug=assets)

**Comment by chickahoona** [comment] 2018-02-13 09:47
I just had the same problem, which was caused by addon folders, that I configured, but were not present. 

(I assume that this can also happen if addon folders are not readable for the user.)

Odoo does not load some ressources, and returns the standard 404 page, which causes most of the website to fall apart.

**Closed** 2018-02-20 17:28 UTC
Labels: 10.0

**Comment by cheyko** [comment] 2019-01-25 14:51
Can anyone help me with this issue. My problem is that i accidentally deleted the odoo directory but I subsequently copied back the directory from another server and all was working until i added some missing modules from my addons folder and did a reboot ..... now i'm left with the blank page and the missing action manager and crashManager.error

**Comment by matteoopenf** [comment] 2022-06-23 09:42
any one find a solution, today in odoo 11 we have the same error after an updgrade?
