### ISSUE TITLE
Sorting issue in calendar

### ISSUE THREAD

**Issue by Gokulakannanaj** [odoo/odoo#26752] opened 2018-09-04 05:38 UTC
I want to sort records  based on start time in calendar.

Using   _order = 'start_datetime asc' in calendar model(calendar.event) records not sorted.

In view default_order='start_datetime'  throws the error

How can i sort records in calendar based on start time.

**Comment by pedrobaeza** [comment] 2018-09-04 07:09
> In view default_order='start_datetime' throws the error

Which error?

**Comment by pedrobaeza** [comment] 2018-09-04 07:09
And which version?

**Comment by Gokulakannanaj** [comment] 2018-09-04 09:52
Version [11]

And my code and error is

In Python:

_inherit = 'calendar.event'
_order = 'start_detatime asc'


In View:
<xpath expr="//calendar" position="attributes">
      <attribute name="default_order">start_datetime</attribute>
</xpath>


Traceback (most recent call last):
  File "/home/trail/web11/dev/trail-web/odoo/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/trail/web11/dev/trail-web/odoo/odoo/modules/loading.py", line 339, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/home/trail/web11/dev/trail-web/odoo/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/trail/web11/dev/trail-web/odoo/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/trail/web11/dev/trail-web/odoo/odoo/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/trail/web11/dev/trail-web/odoo/odoo/tools/convert.py", line 788, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/trail/web11/dev/trail-web/odoo/odoo/tools/convert.py", line 849, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/trail/web11/dev/trail-web/odoo/odoo/tools/convert.py", line 738, in parse
    self.parse(rec, mode)
  File "/home/trail/web11/dev/trail-web/odoo/odoo/tools/convert.py", line 748, in parse
    exc_info[2]
  File "/home/trail/web11/dev/trail-web/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/home/trail/web11/dev/trail-web/odoo/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/trail/web11/dev/trail-web/odoo/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/home/trail/web11/dev/trail-web/odoo/odoo/addons/base/ir/ir_model.py", line 1430, in _update
    record.write(values)
  File "/home/trail/web11/dev/trail-web/odoo/odoo/addons/base/ir/ir_ui_view.py", line 414, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/home/trail/web11/dev/trail-web/odoo/odoo/models.py", line 3042, in write
    field.determine_inverse(records)
  File "/home/trail/web11/dev/trail-web/odoo/odoo/fields.py", line 1070, in determine_inverse
    getattr(records, self.inverse)()
  File "/home/trail/web11/dev/trail-web/odoo/odoo/addons/base/ir/ir_ui_view.py", line 266, in _inverse_arch
    view.write(data)
  File "/home/trail/web11/dev/trail-web/odoo/odoo/addons/base/ir/ir_ui_view.py", line 414, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/home/trail/web11/dev/trail-web/odoo/odoo/models.py", line 3024, in write
    self._write(old_vals)
  File "/home/trail/web11/dev/trail-web/odoo/odoo/models.py", line 3190, in _write
    self._validate_fields(vals)
  File "/home/trail/web11/dev/trail-web/odoo/odoo/models.py", line 982, in _validate_fields
    check(self)
  File "/home/trail/web11/dev/trail-web/odoo/odoo/addons/base/ir/ir_ui_view.py", line 343, in _check_xml
    raise ValidationError(_('Invalid view definition'))
odoo.tools.convert.ParseError: "Invalid view definition


How can i sort records in calendar view based on time.

**Comment by mart-e** [comment] 2018-09-05 07:11
Hello,

I just tried and it worked fine. Please share your view if you have problem.
Please keep in mind that github only for bugs reporting on the standard Odoo. Not for questions or development help.

Regards

**Comment by Gokulakannanaj** [comment] 2018-09-05 08:55
Did you try this below code?

```xml
<xpath expr="//calendar" position="attributes">
         <attribute name="default_order">start_datetime</attribute>
</xpath>
```

**Comment by pedrobaeza** [comment] 2018-09-05 10:58
@Gokulakannanaj that attribute is not allowed on calendar view. You should rely on model order.

**Comment by pedrobaeza** [comment] 2018-09-05 11:32
But it's a bit of nonsense, as the calendar view already put elements in a time context. You can't order by another field, because they are put in the order of the specified date field for the view. Change the date field definition if you want that elements appear in other order.

Closing as no real issue.

**Closed by pedrobaeza** 2018-09-05 11:32 UTC
Labels: Need information

**Comment by mart-e** [comment] 2018-09-05 12:26
view per day
![calendar-day](https://user-images.githubusercontent.com/564822/45093049-8b0c3f80-b117-11e8-89a8-cabc39e3d34e.png)

view per month
![calendar-month](https://user-images.githubusercontent.com/564822/45093055-8fd0f380-b117-11e8-9cb8-14bbb292bab2.png)

Seems like working fine.

As said above, please keep github only for bugs reporting on the standard Odoo. Not for questions or development help.

For help, you may try the [mailing lists](https://www.odoo.com/page/odoo-community), the [forum](https://www.odoo.com/forum/help-1) or the [support page](https://www.odoo.com/help) (for paying users).

Regards

**Comment by Gokulakannanaj** [comment] 2018-09-05 12:41
@mart-e 
In week
![screenshot from 2018-09-05 18-04-58](https://user-images.githubusercontent.com/41570711/45093598-7ee3aa80-b136-11e8-8d5e-a9e6a5e56b9e.png)

In month
![screenshot from 2018-09-05 18-07-22](https://user-images.githubusercontent.com/41570711/45093657-b05c7600-b136-11e8-8f50-af187a3a833c.png)

I'm getting based on ID in month mode. It work perfectly in Week mode.
This is bug to me and not for my development purpose. And also posted my code also.
If it works fine to you, Enough.
Thanks.

**Comment by Reechee88** [comment] 2019-02-19 17:56
Yes, this bug really exists. Same here

**Comment by Reechee88** [comment] 2019-02-19 18:34
Found the bug:

calendar_model.js:669

It cuts the time part of the start_datetime field and in this way (of course!!) FullCalendar is not capable of handling the sorting. 

If this is not a bug, then what? :)

You can customize this function by inheriting in your custom js.

**Comment by inrebinfo** [comment] 2020-01-21 10:07
For me the following fix worked:
First you need to extend the CalendarRenderer (odoo/addons/web/static/src/js/views/calendar/calendar_renderer.js):375 and override the _initCalendar function (I just copied the original method). In this method odoo sets the initial configuration for the Fullcalendar instance and here we have to add one configuration line to tell the calendar to sort by the "r_start"-field.
`odoo.define('tourbooking.web_calendar_color', function (require) {

    var calendar = require('web.CalendarRenderer');
    var config = require('web.config');
    var core = require('web.core');

    var _t = core._t;

    var CustomCalendar = calendar.include({
        _initCalendar: function () {
            var self = this;

            this.$calendar = this.$(".o_calendar_widget");

            // This seems like a workaround but apparently passing the locale
            // in the options is not enough. We should initialize it beforehand
            var locale = moment.locale();
            $.fullCalendar.locale(locale);

            //Documentation here : http://arshaw.com/fullcalendar/docs/
            var fc_options = $.extend({}, this.state.fc_options, {
                /* here goes the original code, I removed it for the sake of readability */
                eventOrder: 'r_start', // THIS is the important line
            });

            this.$calendar.fullCalendar(fc_options);
        },
    });
});`
Probably there is a better way (like extending the method or something else), but for me this works :-)
