### ISSUE TITLE
Multiprocessing not working

### ISSUE THREAD

**Issue by fiddler0305** [odoo/odoo#20158] opened 2017-10-14 13:29 UTC
**Impacted versions:**
11.0 community
ubuntu 17.04  package install

**Steps to reproduce:**
add 
`workers = 8 `
on bottom of /etc/odoo/odoo.conf

**Current behavior:**
after doing above operation, it get lots of error (as images shown)

**Expected behavior:**
working normally

**Video/Screenshot link (optional):**
1. login
![01_login](https://user-images.githubusercontent.com/7629615/31576045-e002c758-b0b8-11e7-9af3-2cbe0d2ea66e.png)

2. after login
![02_logedin](https://user-images.githubusercontent.com/7629615/31576047-e9f0c8fa-b0b8-11e7-8ab7-945bda7bf8a4.png)

**Comment by fiddler0305** [comment] 2017-10-15 09:29
Debian 9.2 package install has the same problem

**Comment by ejprice** [comment] 2017-10-16 01:55
I'm having the same issue on Debian 9.2 with the following setup:

Base Debian 9.2 install
odoo_11.0.20171013_all.deb as well as 20171004 (and dependancies)

Additional deb packages installed:
python3-pyldap
python3-gevent
python3-setuptools
python3-pip

Plus these from pip3:
num2words wheel psycogreen

I have also tried git cloning the source and using pip3 to install dependencies from requirements.txt with the same results.

The workers don't want to work ;-)

**Comment by ejprice** [comment] 2017-10-16 02:06
Also digging further there are missing js and css files which I assume are causing the UI problem

http://localhost:8069/web/content/290-8bbd54f/web.assets_backend.js
http://localhost:8069/web/content/291-a724036/web_editor.summernote.js
http://localhost:8069/web/content/289-7ef8897/web.assets_common.js
http://localhost:8069/web/content/285-8bbd54f/web.assets_backend.0.css
http://localhost:8069/web/content/286-8bbd54f/web.assets_backend.1.css

And if I comment out workers Odoo 11 works

**Comment by gustavovalverde** [comment] 2017-10-16 05:17
@Yenthe666, I can confirm this, I closed a duplicated issue which I made with more details and using the information here #20176 

**Install Odoo with this specifications:**
- Ubuntu Xenial 
- Python 3.5.4
- PostgreSQL 9.6
- **NO** Demo data ---> there's another issue with demo data: #20175 

### Current behavior:
```javascript
20:59:27.057 (index):37 GET https://v11.iterativo.do/web/content/240-ba36516/web.assets_backend.0.css net::ERR_INCOMPLETE_CHUNKED_ENCODING
20:59:27.289 (index):38 GET https://v11.iterativo.do/web/content/241-ba36516/web.assets_backend.1.css net::ERR_INCOMPLETE_CHUNKED_ENCODING
20:59:27.311 (index):35 GET https://v11.iterativo.do/web/content/239-0a9c277/web.assets_common.0.css net::ERR_INCOMPLETE_CHUNKED_ENCODING
20:59:27.435 (index):47 GET https://v11.iterativo.do/web/content/245-ba36516/web.assets_backend.js net::ERR_INCOMPLETE_CHUNKED_ENCODING
20:59:27.491 (index):45 GET https://v11.iterativo.do/web/content/244-0a9c277/web.assets_common.js net::ERR_INCOMPLETE_CHUNKED_ENCODING
20:59:27.675 (index):49 GET https://v11.iterativo.do/web/content/246-ab351a2/web_editor.summernote.js net::ERR_INCOMPLETE_CHUNKED_ENCODING
20:59:27.676 (index):51 GET https://v11.iterativo.do/web/content/247-a129a5f/web_editor.assets_editor.js net::ERR_INCOMPLETE_CHUNKED_ENCODING
20:59:27.684 (index):61 Uncaught TypeError: odoo.define is not a function
    at (index):61
```

**Debug LOG**
```python
2017-10-16 00:59:30,500 364 INFO pruebas odoo.modules.loading: Modules loaded.
2017-10-16 00:59:30,502 364 INFO pruebas odoo.addons.base.ir.ir_http: Generating routing map
2017-10-16 00:59:30,512 363 INFO pruebas odoo.modules.registry: At least one model cache has been invalidated, signaling through the database.
2017-10-16 00:59:30,526 359 INFO pruebas odoo.modules.loading: Modules loaded.
2017-10-16 00:59:30,527 363 INFO pruebas werkzeug: 192.168.2.201 - - [16/Oct/2017 00:59:30] "GET /web/content/241-ba36516/web.assets_backend.1.css HTTP/1.0" 200 -
2017-10-16 00:59:30,531 364 INFO pruebas odoo.modules.registry: At least one model cache has been invalidated, signaling through the database.
2017-10-16 00:59:30,532 364 INFO pruebas werkzeug: 192.168.2.201 - - [16/Oct/2017 00:59:30] "GET /web/content/239-0a9c277/web.assets_common.0.css HTTP/1.0" 200 -
2017-10-16 00:59:30,533 359 INFO pruebas odoo.addons.base.ir.ir_http: Generating routing map
2017-10-16 00:59:30,538 366 INFO pruebas odoo.modules.loading: Modules loaded.
2017-10-16 00:59:30,540 366 INFO pruebas odoo.addons.base.ir.ir_http: Generating routing map
2017-10-16 00:59:30,596 365 INFO pruebas odoo.modules.loading: Modules loaded.
2017-10-16 00:59:30,599 365 DEBUG pruebas odoo.modules.registry: Multiprocess signaling check: [Registry - 2 -> 2] [Cache - 3 -> 5]
2017-10-16 00:59:30,599 365 INFO pruebas odoo.modules.registry: Invalidating all model caches after database signaling.
2017-10-16 00:59:30,602 365 INFO pruebas odoo.addons.base.ir.ir_http: Generating routing map
2017-10-16 00:59:30,629 363 DEBUG pruebas odoo.modules.registry: Multiprocess signaling check: [Registry - 2 -> 2] [Cache - 4 -> 5]
2017-10-16 00:59:30,629 363 INFO pruebas odoo.modules.registry: Invalidating all model caches after database signaling.
2017-10-16 00:59:30,640 363 INFO pruebas werkzeug: 192.168.2.201 - - [16/Oct/2017 00:59:30] "GET /web/content/245-ba36516/web.assets_backend.js HTTP/1.0" 200 -
2017-10-16 00:59:30,700 366 INFO pruebas odoo.modules.registry: At least one model cache has been invalidated, signaling through the database.
2017-10-16 00:59:30,703 366 INFO pruebas werkzeug: 192.168.2.201 - - [16/Oct/2017 00:59:30] "GET /web/content/242-ab351a2/web_editor.summernote.0.css HTTP/1.0" 200 -
2017-10-16 00:59:30,712 359 INFO pruebas odoo.modules.registry: At least one model cache has been invalidated, signaling through the database.
2017-10-16 00:59:30,713 359 INFO pruebas werkzeug: 192.168.2.201 - - [16/Oct/2017 00:59:30] "GET /web/content/244-0a9c277/web.assets_common.js HTTP/1.0" 200 -
2017-10-16 00:59:30,724 365 INFO pruebas werkzeug: 192.168.2.201 - - [16/Oct/2017 00:59:30] "GET /web/content/243-a129a5f/web_editor.assets_editor.0.css HTTP/1.0" 200 -
2017-10-16 00:59:30,846 366 DEBUG pruebas odoo.modules.registry: Multiprocess signaling check: [Registry - 2 -> 2] [Cache - 6 -> 7]
2017-10-16 00:59:30,846 366 INFO pruebas odoo.modules.registry: Invalidating all model caches after database signaling.
2017-10-16 00:59:30,850 366 INFO pruebas werkzeug: 192.168.2.201 - - [16/Oct/2017 00:59:30] "GET /web/content/246-ab351a2/web_editor.summernote.js HTTP/1.0" 200 -
2017-10-16 00:59:30,875 364 DEBUG pruebas odoo.modules.registry: Multiprocess signaling check: [Registry - 2 -> 2] [Cache - 5 -> 7]
2017-10-16 00:59:30,875 364 INFO pruebas odoo.modules.registry: Invalidating all model caches after database signaling.
2017-10-16 00:59:30,879 364 INFO pruebas werkzeug: 192.168.2.201 - - [16/Oct/2017 00:59:30] "GET /web/content/247-a129a5f/web_editor.assets_editor.js HTTP/1.0" 200 -
2017-10-16 00:59:31,489 365 INFO ? werkzeug: 192.168.2.201 - - [16/Oct/2017 00:59:31] "GET /web_enterprise/static/src/img/mobile-icons/android-192x192.png HTTP/1.0" 200 -

```

**In Console with debug assets**

```javascript
21:08:23.786 ?debug=assets:70 GET https://v11.iterativo.do/web/static/src/less/web.assets_backend/import_bootstrap.less.css net::ERR_INCOMPLETE_CHUNKED_ENCODING
```

**Comment by gustavovalverde** [comment] 2017-10-16 05:19
This one could also be related #20175

**Comment by gustavovalverde** [comment] 2017-10-20 10:34
Ticket 777033

**Comment by mlaitinen** [comment] 2017-10-20 12:18
I encountered the same issue. The weird thing is that if you connect to the longpolling port `8072` all the assets work just fine. With `8069` the UI is broken.

**Comment by kirca** [comment] 2017-10-24 21:53
I ran into this also while testing with the odoo:11.0 docker image. The problem seems to be that the assets are not fetched completely, i.e. they are truncated. When running it behind nginx this error is shown:
```
2017/10/24 21:48:52 [error] 4354#4354: *1901 upstream prematurely closed connection while reading upstream, client: 192.168.99.1, server: _, request: "GET /web/content/668-7aa3962/web.assets_frontend.0.css HTTP/1.1", upstream: "http://172.17.0.10:8069/web/content/668-7aa3962/web.assets_frontend.0.css", host: "192.168.99.100"
```
It seems the workers close the connection before sending all data.

**Comment by xmo-odoo** [comment] 2017-10-25 13:39
So… according to research by @odony and @julienlegros it seems to be an issue specifically on Python 3.5 on Linux, above a certain quantity of data sent over a non-blocking socket, so:

* Non linux apparently not an issue (not reproducible on OSX which explains why I couldn't repro it on my box)
* Python 3.6 apparently not an issue
* Small files (e.g. debug=assets) not an issue
* Blocking socket (default threaded socket) not an issue, only workers= triggers the problem.

**Comment by xmo-odoo** [comment] 2017-10-25 13:51
So the issue is likely https://bugs.python.org/issue24291, it is indeed an issue on non-blocking sockets, fixed in 3.5, it can apparently happen on any platform but it's going to depend when the platform's sockets do *partial* writes (so probably depend on the kernel's buffers & tuning & all).

**Comment by odony** [comment] 2017-10-25 17:09
You can try 253d49f7a404ab5c889c90446bf6e87efd4ce026 as a possible fix, but it is not fully validated yet.

**Comment by odony** [comment] 2017-10-25 17:11
@gustavovalverde #20175 looks unrelated

**Comment by gustavovalverde** [comment] 2017-10-26 10:38
I'm wondering, based on @xmo-odoo sentence: 
> (so probably depend on the kernel's buffers & tuning & all).

Could **containerization** be a root cause of this issue? As I'm using LXC containers for Odoo and https://github.com/odoo/odoo/issues/20158#issuecomment-339144630 is using Docker; maybe the kernel behavior (limitations) could also trigger this.

**Comment by gustavovalverde** [comment] 2017-10-26 10:38
@odony, tested https://github.com/odoo/odoo/commit/253d49f7a404ab5c889c90446bf6e87efd4ce026 and it's working great 👍

**Comment by kirca** [comment] 2017-10-26 10:51
@odony, patch https://github.com/odoo/odoo/commit/253d49f7a404ab5c889c90446bf6e87efd4ce026 works  :+1: .

@gustavovalverde it seems to be an issue with python's socket library as it was referenced in the commit
https://bugs.python.org/issue24291

**Closed** 2017-10-26 10:59 UTC
Labels: 11.0, Framework

**Comment by odony** [comment] 2017-10-26 11:04
Thanks for the feedback! 253d49f has been merged in 11.0 at d9b721c8055b791ca27fa2e3c188bb687f0639fb.

Hopefully it should have no adverse effect. I did what I could to limit the effects to the specific combination of Python 3.5 and multi-process mode, which are known required conditions to trigger the bug.
As we're unsure about actual OS settings that could make the bug appear in different conditions, the fix is not platform-specific.

(See the commit message of d9b721c8055b791ca27fa2e3c188bb687f0639fb for more details)

**Comment by Caltdi** [comment] 2018-05-22 03:18
In odoo 10.0c on LinuxMint 18.3 it has a very similar error, but the code is for odoo 11.0c. Is there a solution for Odoo 10.c?

**Comment by gamarino** [comment] 2019-03-04 18:41
Same problem still present in odoo 12 Enterprise

**Comment by SimoRubi** [comment] 2019-04-03 11:22
I'm having this same issue in 12 Enterprise with Python 3.6.7 (ubuntu 18.04).
I tried to manually edit the check in https://github.com/odoo/odoo/commit/d9b721c8055b791ca27fa2e3c188bb687f0639fb#diff-7c4c00ad10cee1a79d1ed0d8b96f0bfaR977 to let it go through for 3.6 and it definitely solves the issue.

**Comment by ccysfn** [comment] 2019-05-08 09:22
> @odony, tested [253d49f](https://github.com/odoo/odoo/commit/253d49f7a404ab5c889c90446bf6e87efd4ce026) and it's working great



> @odony, tested [253d49f](https://github.com/odoo/odoo/commit/253d49f7a404ab5c889c90446bf6e87efd4ce026) and it's working great

cant link it

**Comment by ccysfn** [comment] 2019-05-08 09:32
update workers=0 then solve the issue, but why?the same environment with python3.6.7 ,ubuntu18.04,12 community

**Comment by kingofsevens** [comment] 2019-06-10 22:45
Just to keep it noted. Same problem arose when the customer's products increased in PoS in 11.0 Enterprise with Python 3.6.7 on Ubuntu 18.04.2 LTS. Customer has over 13K products in PoS. It was working after a restart it stopped working and gave connection interrupted errors on PoS load. Applying the fix [`d9b721c`](https://github.com/odoo/odoo/commit/d9b721c8055b791ca27fa2e3c188bb687f0639fb#diff-7c4c00ad10cee1a79d1ed0d8b96f0bfaR977) to this version fixed the issue for now.

**Comment by JeremyShubert** [comment] 2019-10-18 19:32
I continue to have this issue with python 3.6.3, images and .js files are truncated or not available.  Sometimes all .js will load but large images get truncated, it varies with each page reload.  This only occurs through nginx reverse proxy, if I hit the port directly then the site loads without error

**Comment by Eusebius1920** [comment] 2020-01-06 18:17
I can confirm the error with 12.0.20200105 in community edition while using nginx as reverse_proxy.

**Comment by Yajo** [comment] 2020-02-14 13:51
I still face this problem using Python 3.7.6. Anybody in the same situation?

I have managed to reproduce this reliably:

1. Install module `website_slides`.
1. Add big PDF slide (> 10MiB)
1. Publish it.
1. Copy your session cookie. Let's say it's "abcde"
1. Run from inside your odoo container (in case it's a container): `trickle -sd 500 curl --cookie 'session_id=abcde' http://localhost:8069/slides/slide/annual-report-2009-12/download | wc --bytes`

You'll get an output like this:

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 75 10.2M   75 7963k    0     0   323k      0  0:00:32  0:00:24  0:00:08  330k
curl: (18) transfer closed with 2607423 bytes remaining to read
8154727
```

Each time you re-run the command, the bytes count will be different. The error `curl: (18) transfer closed with 2607423 bytes remaining to read` shows that this still happens.

Is anybody else still affected too? Any help?

**Comment by rafaelbn** [comment] 2020-02-14 16:27
OPW 2197711

@xmo-odoo @odony we have been fighting 1 week with this and  is critical for the customer. Any clue / help you could provide us please?

Thanks

**Comment by Tardo** [comment] 2020-02-14 22:55
I think that the problem comes from this low value: https://github.com/odoo/odoo/blob/12.0/odoo/service/server.py#L987

**Comment by odony** [comment] 2020-02-15 14:15
@rafaelbn @Yajo for the record I can't reproduce the problem with Yajo's scenario, all the downloads complete at 100% even if it takes more than 1 minute with throttled bandwidth. Do you have other network peculiarities in your case? Is this a problem that started to appear recently, and could be correlated with another change in your customer environment?

Regarding the socket timeout, I'm sure you remember the whole story from #17998, #12356 etc. You can try to bump it to very high values and see if it fixes the problem, but keep in mind all the warnings and discussion about this in these PRs, and regarding BW saturation causing extreme latencies.

PS: @Tardo the `settimeout()` has a very specific reason to be there, you can read the discussions on the PRs I mentioned. Having a timeout implies a blocking socket, calling `setblocking()` before just makes it more explicit.

**Comment by Tardo** [comment] 2020-02-15 14:17
@odony i will read the PR's but you can see:
"At the operating system level, sockets in timeout mode are internally set in non-blocking mode"

**Comment by Tardo** [comment] 2020-02-15 14:21
I can reproduce it putting a big file into web/static/ .... and request it with
```wget --limit-rate 500k --tries 1 http://......../bigfile.ext```

**Comment by pedrobaeza** [comment] 2020-02-15 15:44
Thanks for the reply, @odony. I have been able to reproduce the problem in local without reverse proxy with the same steps as @Tardo commented (well, I was using trickle + curl for throttling the speed rate, but shouldn't be significant).

Indeed augmenting the timeout mitigates the problem, but I have to increase more and more the value as the speed rate decreases or the file size raises, so this is symptomatic of any other thing. Maybe a bad reset of the timeout on the werkzeug streaming server code?

**Comment by ejprice** [comment] 2020-02-15 17:15
@Yajo Assuming the Nginx reverse proxy(ies) are located close to Odoo on the network, wouldn't you be better off using Nginx's static caching functionality to buffer the transfer of these large files? Transferring the file to Nginx from Odoo would be fast, eliminating the potential Odoo timeout. Nginx is more efficient at sending static files to the remote. It is also more tuneable and resilient being a purpose build web server instead of an application server like Odoo.  

Example:

`

    location ~* /web/static/ { 

    proxy_cache_valid 200 60m; 

    proxy_buffering on; 
    expires 864000; 
    proxy_pass http://odoo; 
 } `

One of the key tunable here is ` proxy_buffering on; ` which causes Nginx to transfer the whole file to itself before sending it to the remote. This example only caches files in the */static/ directories. You'd need to adjust it to work with PDFs. 

Other useful/relevant docs:
https://www.nginx.com/blog/nginx-caching-guide/
https://docs.nginx.com/nginx/admin-guide/content-cache/content-caching/

You may want to define a local caching directory:

`proxy_cache_path /path/to/cache levels=1:2 keys_zone=my_cache:10m max_size=10g 
                 inactive=60m use_temp_path=off;`

and add that to the nginx config:

`
# cache static data
location ~* /web/static/ { 
    proxy_cache my_cache;
    proxy_cache_valid 200 60m; 
    proxy_buffering on; 
    expires 864000; 
    proxy_pass http://odoo; 
  } `

You may need to play around with this a bit to get it to work. I don't have an exact nginx.conf file to cut and paste for you because we're using the Nginx ingress in Kubernetes and the config file is built dynamically from YAML files. It does work though and also reduces the load on our Odoo backends.

**Comment by Yajo** [comment] 2020-02-17 11:49
@ejprice According to my tests, you nailed it!

I use Traefik, just adding [the Buffering middleware](https://docs.traefik.io/middlewares/buffering/) seems to fix the problem.

**Comment by ejprice** [comment] 2020-02-17 14:20
@Yajo  that’s great news! And kind of funny because the next thing on my todo list is figure out Traefik 😂.

**Comment by Yajo** [comment] 2020-04-29 13:10
I opened OPW-2247730 because this still happens if your files are 219MB or bigger.

**Comment by mamiu** [comment] 2020-12-07 02:39
@odony This issue is still present in the latest version of Odoo v14. I debugged it for three full days until I figured out that it's due to the `workers` configuration. If the workers are set to a value greater or equal to `1` I can reproduce this issue reliably.

### The environment

Odoo version: **v14.0 release 20201123 (CE and EE)**
Hosting environment: **Kubernetes with Traefik Proxy** (so basically the **official [Odoo Docker](https://github.com/odoo/docker)** container)
Odoo config:

```ini
[options]
db_maxconn = 128
db_name = my-db-name
dbfilter = ^my-db-name$
limit_time_cpu = 600
limit_time_real = 1800
proxy_mode = True
workers = 3
```

### Reproduction steps

1. Run the latest Odoo version in a docker container on a **REMOTE** host (The *remote* part is important, since localhost has some special behavior on buffering. So don't install it on localhost or a VM running on localhost (even if it's using the bridge network adapter), but run it on another machine. Doesn't matter if it's a server, a laptop or a Raspberry Pi as long as it is a different machine)
2. Install the `website` addon
3. `curl` a file like the `web.assets_backend.js` with a limited rate and output only the last two lines (so that our terminal is not printing the whole file but still are able to see whether we got everything or just a part of the file). E.g.

```bash
curl 'http://<IP address or URL>/path/to/the/web.assets_backend.js' \
    -H 'Cookie: session_id=2a572f8fba3d721bdbb18a5de6cd0536d5f8e3f5' \
    --limit-rate 10K | tail -n 2
```

> The easiest way to get the full `curl` command is to go to the **Chrome DevTools** → **Network** tab → **right click** the `web.assets_backend.js` → **Copy** → **Copy as cURL** 

4. If the file fetching doesn't break in the middle just decrease the `--limit-rate` until it will break before the full content was delivered. (This can take 10 to 15 minutes but usually happens earlier and it is independent from the `limit_time_cpu` or `limit_time_real` configuration values. It only takes that long in an ideal debug setting, but in my real situation (sitting in Australia and having our Odoo servers in Europe) the connection tends to break after 2-3 seconds, which happens for the `web.assets_backend.js` file in 50% of the cases (once it's loaded it'll be cached by the browser but on the first load it often crashes))

The [solution](https://github.com/odoo/odoo/issues/20158#issuecomment-586621500) suggested by @ejprice is working but only a workaround and doesn't fix the Odoo issue. Anyway, thanks for it!
