### ISSUE TITLE
Employee image changes when changing related user.

### ISSUE THREAD

**Issue by obayit** [odoo/odoo#47932] opened 2020-03-18 14:44 UTC
Current Behaviour:
Employee's image always changes when changing the related user.

Expected Behaviour:
Employee's image should not change when changing its related user and that user doesn't has an image, or has a default image.

My case:
I have a database of existing employees, but their users are not linked yet.
Whenever I change the related user for an employee his/her image changes even when the user's image is not set, or it is the default. This is troublesome, and tedious to work with.

**Comment by pedrobaeza** [comment] 2020-03-18 15:11
But this is the intended behavior for synchronizing images, as the user photo should be the valid one. It's not your use case, but it's the usual one.

Closing then as won't fix as expected behavior.

**Closed by pedrobaeza** 2020-03-18 15:11 UTC

**Comment by obayit** [comment] 2020-03-19 07:13
I strongly disagree. The usual case is that when implementing Odoo, I enter all employees first. Then create users for those who need access to Odoo. Thus synchronization should go from employee to user. I only create internal users for existing employees, not the other way around!

I agree that, when creating a user I should have created it from the employee's form, but this doesn't work either!
This is simple but a serious usage issue.

**Comment by obayit** [comment] 2020-03-19 07:18
For example this [commit](https://github.com/odoo/odoo/commit/d74fe36654c2f879a4cb04cb990488c55149a991), sets the timezone only if the user has one!

**Comment by pedrobaeza** [comment] 2020-03-19 09:14
OK, that's your opinion and I ping @tivisse for seeing if that feedback is interesting for Odoo, but that's for new versions. For stable versions I only see the case that if no image in user, no change in employee's image.

**Comment by tivisse** [comment] 2020-03-23 07:30
Hi @obayit 

Thanks for your feedback. I will propose your improvement to the Product Owners team. But as @pedrobaeza said, this is the intended behavior since several versions (maybe it has always been like that).

But maybe they'll think it's valid. Wait and see, I'll come back to you when they decided what to do ;)

Have a nice day,

Yannick.
