### ISSUE TITLE
[v12.0] In sale order line can not allow to add note.

### ISSUE THREAD

**Issue by JagdishPanchalSCS** [odoo/odoo#27415] opened 2018-10-04 05:21 UTC
Impacted versions:
v12.0
Steps to reproduce:
1) Create sale order

2) select Customer

3) Add product 

4) add Section

5) Add note its give to trace back Error
Current behavior:

Expected behavior:
Its should allow to add note
Video/Screenshot link (optional):

![sale order](https://user-images.githubusercontent.com/33276865/46454325-4382dd00-c7c3-11e8-8306-e72627b6b8ec.png)

**Comment by Yenthe666** [comment] 2018-10-04 05:45
Hi @JagdishPanchalSCS,

Thanks a lot for the bug report!
This is actually a duplicate of https://github.com/odoo/odoo/issues/27409 and it seems to be happening in multiple places. I'll keep the other one open and close this one as this one is newer and more specific about one issue.

Regards,
Yenthe

**Closed by Yenthe666** 2018-10-04 05:45 UTC
Labels: 12.0, Services
