### ISSUE TITLE
Odoo11+12 - Not load default value in data DEMO if _log_access=False

### ISSUE THREAD

**Issue by iguixa** [odoo/odoo#29273] opened 2018-12-05 11:58 UTC
Impacted versions: Odoo 11 and Odoo 12

Steps to reproduce: Install attached module in company with demo data activated

The manifest file in module explain the problem. After installation, you can see in the database that the 'active' and 'number' fields have not been filled out correctly in the table td_laf (class with log_access = False)
```
SX=# select * from td_laf;
 id | name | active | number
----+------+--------+--------
  1 | LAF1 | f      |
  2 | LAF2 | f      |
  3 | LAF3 | f      |

SX=# select * from td_lat;
 id | name  | active | number | create_uid |        create_date         | write_uid |         write_date
----+-------+--------+--------+------------+----------------------------+-----------+---------------------------
  1 | LAT1  | t      |     10 |          1 | 2018-12-05 11:33:59.194495 |         1 | 2018-12-05 11:33:59.194495
  2 | LAT2  | t      |     10 |          1 | 2018-12-05 11:33:59.194495 |         1 | 2018-12-05 11:33:59.194495
  3 | LAT3  | t      |     10 |          1 | 2018-12-05 11:33:59.194495 |         1 | 2018-12-05 11:33:59.194495
```

[test_logAccess+demoData+defaultValues.zip](https://github.com/odoo/odoo/files/2648703/test_logAccess%2BdemoData%2BdefaultValues.zip)

**Comment by pedrobaeza** [comment] 2018-12-05 15:01
The problem is that you should activate `log_access`. If not, you wont' have all the features of ORM.

Closing as no real issue, but misuse of the ORM framework.

**Closed by pedrobaeza** 2018-12-05 15:01 UTC
