### ISSUE TITLE
@api.onchange function were not called after a change of value of field

### ISSUE THREAD

**Issue by tvibliani** [odoo/odoo#4902] opened 2015-01-26 12:15 UTC
**Onchange function were not called after a change of fields value**

Impacted versions:

 - 8.0

**Steps to reproduce:**

 1. Install "account_chart_date_picker" module (available as Community App)
 2. Click on "Accounting/Charts/Chart Of Accounts" menu.

**Current behavior:**
- onchange function of "From"(period) field should set "From"(date) field to starting date of selected period but does not.
- onchange function of "To"(period) field should set "To"(date) field to end date of selected period but does not.

![selection_008](https://cloud.githubusercontent.com/assets/9282767/5899201/77d38b2c-a571-11e4-8797-f09f15a81796.png)

default value of 'Fiscal Year' field is a current fiscal year and when 'Fiscal Year' field is set to current fiscal year(by default), then it's onchange function changes values of 'From' and 'To' (period) fields. but after this last change onchange function of these fields are NOT called, that's why 'From' and 'To'(date) fields are empty. That's actually is a bug of onchange, as it should be called after any change.
 
**Expected behavior:**

  ![selection_010](https://cloud.githubusercontent.com/assets/9282767/5899211/8fa8f430-a571-11e4-95cc-194b445d72d4.png)

**Comment by guewen** [comment] 2015-01-26 12:23
It could be the same issue than https://github.com/odoo/odoo/issues/4897

**Comment by alexis-via** [comment] 2015-01-30 22:18
I just hit this bug when writing a yml test for the "stay" module that use the new API and has @api.onchange : the onchange is not played when I create a new record inside the yaml file (I'm very new to yaml, but the examples I read show that on_change are supposed to be played when a new record is created via yaml file)

**Comment by rco-odoo** [comment] 2015-02-10 12:20
@tvibliani I committed a patch for the onchange (commit 2067a20).
Can you give it a try, and see whether the issue is still present?

**Closed** 2015-09-07 08:38 UTC

**Comment by tvibliani** [comment] 2015-09-29 08:57
:+1:
