### ISSUE TITLE
[10.0] Removing saved child record after adding duplicate still shows constraint warning

### ISSUE THREAD

**Issue by osluys** [odoo/odoo#17724] opened 2017-06-20 13:50 UTC
Impacted versions:
10.0

Steps to reproduce:
```python
#---------
# model.py
#---------
class Parent(models.Model):
    ...
    child_ids = fields.One2many('child.model', 'parent_id', "Children")

class Child(models.Model):
    ...
    _sql_constraints = [('parent_id_other_id_uniq', 'UNIQUE(parent_id, other_id)', 
                         "Duplicates not allowed")]
    sequence = fields.Integer(required=True)
    parent_id = fields.Many2one('parent.model', required=True)
    other_id = fields.Many2one('other.model', required=True)
    quantity = fields.Integer()
```
```xml
<!------
view.xml
------->
<record id="parent_view_form" model="ir.ui.view">
    ...
    <field name="arch" type="xml">
        <form>
            ...
            <field name="child_ids">
                <tree editable="bottom">
                    <field name="seq" widget="handle"/>
                    <field name="id"/>
                    <field name="other_id"/>
                    <field name="quantity"/>
                </tree>
            </field>
```

1. Using the form view, create a new parent record
2. Add the following records to the subtree

`id` | `other_id` | `quantity`
--|--|--
`1` | "Other 1" | 3
`2` | "Other 2" | 12

3. Save the form (child records are now saved to database)
4. Edit the form again
5. Add the following record to the subtree

`id` | `other_id` | `quantity`
--|--|--
`NewId` | "Other 1" | 9

6. Save the form again
7. Close warning about duplicate record (`other_id:` "Other 1")
8. Remove subtree record with `id == 1` (i.e. child record previously saved in steps 2 and 3)
9. Save the form yet again

Current behavior:

At this point, I am still given a warning about duplicate child records. If I were to remove the unsaved child record from step 5 instead, I would not get this warning.

Expected behavior:

I should be able to remove the saved duplicate child record (where `id == 1`) from the subtree and have the new child record saved in its place.

**Comment by pedrobaeza** [comment] 2018-06-01 00:18
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem and any possible tip about what's going on.

**Closed by pedrobaeza** 2018-06-01 00:18 UTC
Labels: 10.0, Framework

**Comment by Yenthe666** [comment] 2018-06-01 15:41
@pedrobaeza wait, are you sure here? He is actually adding code to demonstrate and reproduce a problem in the framework (atleast, the author believes so), no?

**Comment by pedrobaeza** [comment] 2018-06-01 16:28
I don't really identify any real problem in framework, but some instructions about what he does are confusing. The only way to demonstrates this is through a complete module attached as ZIP for trying, and specifying clearly the STR (steps to reproduce). Meanwhile, I keep the closing status as the valid one.

**Comment by Yenthe666** [comment] 2018-06-01 17:00
Okay, fair point, thanks Pedro. @osluys please do provide us with a module and a movie that shows the exact issue so we can act on it.
