### ISSUE TITLE
[9.0] Really slow pos loading in multi-company

### ISSUE THREAD

**Issue by Zoe9a** [odoo/odoo#9532] opened 2015-11-12 04:12 UTC
_Really slow pos loading in multi-company_*

Impacted versions:
- 9.0

Steps to reproduce:
"POS loading" use the "price" function of product model.
this function search the good sale price in pricelist.

During pos loading, each product execute one by one this function.
This is perferct with a small pricelist.
But with one price by product when you got 20 000 product. (multi company environement = 1 pricelist per company) : This loading coud take easily more than 30 minutes just for search each price in pricelist.

"Pos_cache" could help for this, but when you change a price for a product, you need to recompute the cache for each pos.config AND each user that use this price. So if you got four point of sales and 4 users, It coult take 4x4x30min = 480 min for everyone and during this time CPU usage of server becomes 100%: Result : Everyone wait in company.

Current behavior:
- Really slow POS Loading

Expected behavior:
- Normal wait time for POS loading

**Comment by jorenvo** [comment] 2015-11-12 14:18
I agree it's not ideal. Something that might help a little bit is that we provide a cronjob you could use to automatically recompute the caches during downtime in which Odoo is not used. Unless ofcourse you're using Odoo internationally in which case there may not be any downtime at all.

**Comment by yaho9** [comment] 2015-11-12 14:35
Yes sure, I could do that, but that means no new product or new price during the work day. I think this could be a major issue for customers.

**Comment by antonylesuisse** [comment] 2015-11-25 12:16
Are you using complex pricelists ?

**Comment by yaho9** [comment] 2015-11-28 11:31
I use "Advanced pricing based on formula" but I use this option just for csv importation. In fact, I don't use formula. I use a fixed price per product and per company(ex : 2 company = 2 pricelist).

**Comment by antonylesuisse** [comment] 2015-11-28 22:16
Every one of your 20 000 product has different price in company1 and company2 (meaning that you have 40k pricelist lines) or is it only for a subsest of roduct ?

**Comment by yaho9** [comment] 2015-11-29 05:06
Not exactly because pricelist is per company. so two pricelist with 20 000 lines each. The pos can load only one pricelist (20 000 in my case).
(company1 and company2 share all product but sale price is diferent.)

**Comment by yaho9** [comment] 2015-11-29 05:49
Odoo 9 offer the posibility to control price in "Product Sheet/sales tab/Pricing" and I use this for multi-company price. It's easier to understand for users than pricelist. So each time an user create a new "pricing", it's a new pricelist line. So the pos loading problem is certain.

**Comment by antonylesuisse** [comment] 2015-11-30 11:01
Ok thank for the information, @jorenvo we have to check the pricelist implementation to make sure we dont load the 40k lines 20k times.

**Comment by acespritech-solutions** [comment] 2016-02-09 13:13
We have implemented one feature to load products in pos in background and while products are loading in background, user can use pos online. https://www.odoo.com/apps/modules/8.0/pos_prod_load_background_v8/

**Comment by flotho** [comment] 2016-04-06 14:39
Hi @yaho9 ,

Do you have those kind of rules in your complex list items: https://github.com/odoo/odoo/issues/11617

**Comment by Yenthe666** [comment] 2017-11-26 15:42
@antonylesuisse and @jorenvo any update on this? Is it handled/OK or not?

**Comment by Gyuri77** [comment] 2018-01-08 12:00
We have ~100 000 products, and a lot of pricelists.
I modified the search_read for products (only for POS querys), and instead of odoo style object based search and browse, i write a big sql query,  so its fast as lightning. The downloaded data grows more than 80 MB, so we set in apache to send data compressed. Some of our pos uses mobileinternet sticks with pay per GB, so its a must have.
For many pricelist, i modified POS, added a new field: Additional pricelists,  so its only loads the additional pricelists and base pricelist for pos. pricelist loading is so slow yet, but we load 2-3 per pos instead of all 20+.

**Comment by pedrobaeza** [comment] 2018-04-10 23:09
@sle-odoo is there any news about this? I think some work has been done for improving load time, but I don't know if specific to this.

**Comment by sle-odoo** [comment] 2018-04-11 09:00
@pedrobaeza Now that pricelists are implemented client-side, this specific issue should be solved. @pimodoo

**Comment by Yenthe666** [comment] 2018-04-11 09:04
Hi @Zoe9a,

This problem should be fixed with the latest version of Odoo.
If you can still reproduce these problems on the latest Odoo then please don't hesitate to respond back with more details.

Regards,
Yenthe

**Closed** 2018-04-11 09:03 UTC
Labels: 9.0, Point of Sale
