### ISSUE TITLE
 Selection Field is Not Working in POS.

### ISSUE THREAD

**Issue by ayazmansuri** [odoo/odoo#11096] opened 2016-02-25 07:36 UTC
Hello...!!!
Currrently I'm Working on Custom POS Module in Odoo V8. where i have to find a bug that Country Selection Field is not working in POS.

In POS, After Selecting particular customer, Click on edit button, customer country is not showing in Country Field. it Shows None..!!!

![pos_edit](https://cloud.githubusercontent.com/assets/11834534/13312904/37337650-dbc0-11e5-8a46-1b7e899b6c24.jpg)

**Comment by Yenthe666** [comment] 2016-06-13 07:45
Hi @ayazmansuri,

When the country field shows None it means the contact has not yet had a country set.
The selection field however is filled up if the customer already has a country filled in or after you fill it in. An example:
![image](https://cloud.githubusercontent.com/assets/6352350/16000251/85214a5a-314b-11e6-895a-70cf5cfd466a.png)
Closing this since this is not a bug.

Regards,
Yenthe

**Closed by Yenthe666** 2016-06-13 07:45 UTC
