### ISSUE TITLE
module:base_import, class:Import(models.TransientModel),method:_read_xls(self, options), options['skip'] parameter not applied

### ISSUE THREAD

**Issue by aixi88** [odoo/odoo#72823] opened 2021-06-26 04:00 UTC
Impacted versions:14

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment] 2021-06-26 09:03
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by aixi88** [comment] 2021-06-27 05:18
![base_import_skip](https://user-images.githubusercontent.com/9400678/123533700-1e401500-d74a-11eb-9a67-56d608322535.png)

**Comment by pedrobaeza** [comment] 2021-06-27 09:38
I don't find such problem: putting a different value there makes to start on that row.

**Comment by aixi88** [comment] 2021-06-27 12:31
```
    def _read_xls(self, options):
        """ Read file content, using xlrd lib """
        book = xlrd.open_workbook(file_contents=self.file or b'')
        sheets = options['sheets'] = book.sheet_names()
        sheet = options['sheet'] = options.get('sheet') or sheets[0]
        return self._read_xls_book(book, sheet)
```
In the above code, options['skip']  is not used.

**Comment by aixi88** [comment] 2021-06-27 12:39
```
    def parse_preview(self, options, count=10):
        """ Generates a preview of the uploaded files, and performs
            fields-matching between the import's file data and the model's
            columns.
            If the headers are not requested (not options.headers),
            ``matches`` and ``headers`` are both ``False``.
            :param int count: number of preview lines to generate
            :param options: format-specific options.
                            CSV: {quoting, separator, headers}
            :type options: {str, str, str, bool}
            :returns: {fields, matches, headers, preview} | {error, preview}
            :rtype: {dict(str: dict(...)), dict(int, list(str)), list(str), list(list(str))} | {str, str}
        """
        self.ensure_one()
        fields = self.get_fields(self.res_model)
        try:
            rows = self._read_file(options)
            headers, matches = self._match_headers(rows, fields, options)
```
**In the above preview code, option['skip'] is not used.**
```
    def _read_xls(self, options):
        """ Read file content, using xlrd lib """
        book = xlrd.open_workbook(file_contents=self.file or b'')
        sheets = options['sheets'] = book.sheet_names()
        sheet = options['sheet'] = options.get('sheet') or sheets[0]
        return self._read_xls_book(book, sheet)
```

**Comment by aixi88** [comment] 2021-06-29 03:46
[test.xls](https://github.com/odoo/odoo/files/6730489/test.xls

This is the file I tested. When I changed the starting line to 3, the preview interface did not change. I manually selected the fields to be imported and imported them directly. As a result, only 3 lines of data were imported and 1 line was less imported

**Comment by aixi88** [comment] 2021-06-29 03:47
[test.xls](https://github.com/odoo/odoo/files/6730489/test.xls

This is the file I tested. When I changed the starting line to 3, the preview interface did not change. I manually selected the fields to be imported and imported them directly. As a result, only 3 lines of data were imported and 1 line was less imported

**Comment by pedrobaeza** [comment] 2021-06-29 06:33
Preview is not changed, but the aim of changing that is when importing, not in the preview.

**Comment by aixi88** [comment] 2021-06-30 01:22
> Preview is not changed, but the aim of changing that is when importing, not in the preview.

Auto matching field is a very good function in preview. I hope you can consider it
[test.xls](https://github.com/odoo/odoo/files/6737327/test.xls)
This is my import test file. Starting from the third line, four lines of data should be imported, but only three lines are imported, 
"_convert_ import_data” Maybe there is something wrong with the logic. The empty line has been filtered before 
data [options.get ('skip'):]
```
    @api.model
    def _convert_import_data(self, fields, options):
        """ Extracts the input BaseModel and fields list (with
            ``False``-y placeholders for fields to *not* import) into a
            format Model.import_data can use: a fields list without holes
            and the precisely matching data matrix

            :param list(str|bool): fields
            :returns: (data, fields)
            :rtype: (list(list(str)), list(str))
            :raises ValueError: in case the import data could not be converted
        """
        # Get indices for non-empty fields
        indices = [index for index, field in enumerate(fields) if field]
        if not indices:
            raise ValueError(_("You must configure at least one field to import"))
        # If only one index, itemgetter will return an atom rather
        # than a 1-tuple
        if len(indices) == 1:
            mapper = lambda row: [row[indices[0]]]
        else:
            mapper = operator.itemgetter(*indices)
        # Get only list of actually imported fields
        import_fields = [f for f in fields if f]

        rows_to_import = self._read_file(options)
        if options.get('headers'):
            rows_to_import = itertools.islice(rows_to_import, 1, None)
        data = [
            list(row) for row in map(mapper, rows_to_import)
            # don't try inserting completely empty rows (e.g. from
            # filtering out o2m fields)
            if any(row)
        ]

        # slicing needs to happen after filtering out empty rows as the
        # data offsets from load are post-filtering
        return data[options.get('skip'):], import_fields
```

**Comment by pedrobaeza** [comment] 2021-06-30 06:10
You can propose the changes on master branch through a pull request.

**Comment by aixi88** [comment] 2021-06-30 08:33
> You can propose the changes on master branch through a pull request.

I haven't done that, but I'll give it a try, thank you very much!

**Closed** 2021-06-30 09:10 UTC
Labels: Need information
