### ISSUE TITLE
Auto-populate company contact error

### ISSUE THREAD

**Issue by Nevyn75** [odoo/odoo#34845] opened 2019-07-15 06:07 UTC
Impacted versions: 12

Steps to reproduce:

- Inside Contacts module create new Company contact

- Select one of the suggested company

Current behavior: this error appears: 

> Uncaught TypeError: Cannot read property 'type' of undefined
> https://mydomain.com:8443/web/content/382-6ac400c/web.assets_backend.js:1357
> Traceback:
> TypeError: Cannot read property 'type' of undefined
>     at Class._applyChange (https://mydomain.com:8443/web/content/382-6ac400c/web.assets_backend.js:1357:205)
>     at Object.<anonymous> (https://mydomain.com:8443/web/content/378-30ab706/web.assets_common.js:3751:384)
>     at Object.<anonymous> (https://mydomain.com:8443/web/content/378-30ab706/web.assets_common.js:802:681)
>     at fire (https://mydomain.com:8443/web/content/378-30ab706/web.assets_common.js:796:299)
>     at Object.add [as done] (https://mydomain.com:8443/web/content/378-30ab706/web.assets_common.js:797:467)
>     at Array.<anonymous> (https://mydomain.com:8443/web/content/378-30ab706/web.assets_common.js:802:649)
>     at Function.each (https://mydomain.com:8443/web/content/378-30ab706/web.assets_common.js:625:767)
>     at Object.<anonymous> (https://mydomain.com:8443/web/content/378-30ab706/web.assets_common.js:802:560)
>     at Function.Deferred (https://mydomain.com:8443/web/content/378-30ab706/web.assets_common.js:803:194)
>     at Object.then (https://mydomain.com:8443/web/content/378-30ab706/web.assets_common.js:802:525)

If I disable auto-populate feature or I don't click on any suggested Company, the contact is created without any problem.

Thanks.

**Comment by pedrobaeza** [comment] 2019-07-15 07:18
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Nevyn75** [comment] 2019-07-16 08:41
Hi, thanks to you for feedback.
On runbot the problem is not present.

I tried to delete and recreate a clean DB, installing only the contacts module and the problem is still present.

I forgot to mention that I'm running the odoo container...
Now I'll try outside the container, starting from a fresh pull of source code and let you know.

Thanks.

**Comment by Nevyn75** [comment] 2019-07-16 14:32
Launching odoo from sources no problem.
Only inside the container, but the sources are the same, mounted inside it...

Maybe a dependency problem?

Anyway I suppose I can close the issue because not related to source code.

Thank you.

**Closed** 2019-07-16 14:32 UTC
Labels: 12.0
