### ISSUE TITLE
Odoo V12 (Marketing Automation) : Traceback appear when hit scheduled activity

### ISSUE THREAD

**Issue by AmitBista** [odoo/odoo#29267] opened 2018-12-05 10:55 UTC
Impacted versions: 12

Steps to reproduce:
1 go to marketing automation > Campaigns
2 Open running campaign
3 Open Participants via a smart button
4 Open any record and run scheduled activity via a smart button
after click traceback appaer as below.

Current behavior:

Traceback appears As:
--------------------------------
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/amit/workspace/odoo-12.0/odoo_12_enterprise/marketing_automation/models/marketing_campaign.py", line 505, in _execute_action
    action.run()
  File "/home/amit/workspace/odoo-12.0/odoo/odoo/addons/base/models/ir_actions.py", line 581, in run
    res = func(action, eval_context=eval_context)
  File "/home/amit/workspace/odoo-12.0/odoo/odoo/addons/base/models/ir_actions.py", line 493, in run_action_object_create
    res = self.env[action.crud_model_id.model].create(res)
  File "<decorator-gen-262>", line 2, in create
  File "/home/amit/workspace/odoo-12.0/odoo/odoo/api.py", line 430, in _model_create_single
    return create(self, arg)
  File "/home/amit/workspace/odoo-12.0/odoo/addons/crm/models/crm_lead.py", line 310, in create
    return super(Lead, self.with_context(context, mail_create_nolog=True)).create(vals)
  File "<decorator-gen-125>", line 2, in create
  File "/home/amit/workspace/odoo-12.0/odoo/odoo/api.py", line 451, in _model_create_multi
    return create(self, [arg])
  File "/home/amit/workspace/odoo-12.0/odoo/addons/mail/models/mail_thread.py", line 273, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/home/amit/workspace/odoo-12.0/odoo/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/home/amit/workspace/odoo-12.0/odoo/odoo/models.py", line 3505, in create
    records = self._create(data_list)
  File "/home/amit/workspace/odoo-12.0/odoo/odoo/models.py", line 3605, in _create
    cr.execute(query, params)
  File "/home/amit/workspace/odoo-12.0/odoo/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/home/amit/workspace/odoo-12.0/odoo/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (49, 2, null, null, null, null, null, t, null, null, null, 1, null, null, null, null, lead, 0, null, 1, 2, null, 2018-12-05 10:50:35, null, null, 2018-12-05 10:50:35, null, 0, 10, null, null, null, 0, null, null, null, null, null, null, null, null, null, null, 1, null, 2, 2018-12-05 10:50:35.20841, 2, 2018-12-05 10:50:35.20841, null, null, null).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amit/workspace/odoo-12.0/odoo/odoo/tools/cache.py", line 88, in lookup
    r = d[key]
  File "/home/amit/workspace/odoo-12.0/odoo/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/home/amit/workspace/odoo-12.0/odoo/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.access', <function IrModelAccess.check at 0x7f16f48ac048>, 2, 'marketing.trace', 'write', True, ('en_US',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amit/workspace/odoo-12.0/odoo/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/amit/workspace/odoo-12.0/odoo/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/amit/workspace/odoo-12.0/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/amit/workspace/odoo-12.0/odoo/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/home/amit/workspace/odoo-12.0/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/amit/workspace/odoo-12.0/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/amit/workspace/odoo-12.0/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/amit/workspace/odoo-12.0/odoo/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/home/amit/workspace/odoo-12.0/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/home/amit/workspace/odoo-12.0/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/amit/workspace/odoo-12.0/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/amit/workspace/odoo-12.0/odoo/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/home/amit/workspace/odoo-12.0/odoo/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/amit/workspace/odoo-12.0/odoo_12_enterprise/marketing_automation/models/marketing_participant.py", line 159, in action_execute
    self.activity_id.execute_on_traces(self)
  File "/home/amit/workspace/odoo-12.0/odoo_12_enterprise/marketing_automation/models/marketing_campaign.py", line 479, in execute_on_traces
    activity_method(traces_allowed)
  File "/home/amit/workspace/odoo-12.0/odoo_12_enterprise/marketing_automation/models/marketing_campaign.py", line 511, in _execute_action
    'state_msg': _('Exception in server action: %s') % str(e),
  File "/home/amit/workspace/odoo-12.0/odoo/odoo/models.py", line 3220, in write
    self.check_access_rights('write')
  File "/home/amit/workspace/odoo-12.0/odoo/odoo/models.py", line 2994, in check_access_rights
    return self.env['ir.model.access'].check(self._name, operation, raise_exception)
  File "<decorator-gen-23>", line 2, in check
  File "/home/amit/workspace/odoo-12.0/odoo/odoo/tools/cache.py", line 93, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/amit/workspace/odoo-12.0/odoo/odoo/addons/base/models/ir_model.py", line 1209, in check
    (model, self._uid,))
  File "/home/amit/workspace/odoo-12.0/odoo/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/home/amit/workspace/odoo-12.0/odoo/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.InternalError: current transaction is aborted, commands ignored until end of transaction block
===================================================

Expected behavior:
Traceback should not be raisd

Video/Screenshot link (optional):
https://drive.google.com/file/d/1EVC8U_MRuvtcsjqNfTUHICvDnLLnfZVg/view?usp=sharing

**Comment by Yenthe666** [comment] 2018-12-05 11:01
Hi @AmitBista,

Thanks for your report.
I've just tested this in the latest Odoo 12 but it seems to work fine out of the box.
Can you still reproduce it on the latest official test instance at runbot.odoo.com? Is your Odoo source code up to date?

Regards,
Yenthe

**Comment by sswapnesh** [comment] 2018-12-05 17:19
@AmitBista Looks like Thats beacuse of` 'state_msg': _('Exception in server action: %s') % str(e),`
Could you please share details of server action ?

**Comment by Yenthe666** [comment] 2019-01-28 12:52
Hi,

As we haven't gotten any feedback and it has been open for months I'm closing this issue.

Regards,
Yenthe

**Closed by Yenthe666** 2019-01-28 12:52 UTC
Labels: 12.0, Need information, Services
