### ISSUE TITLE
[BUG][14.0] Not possible to regenerate assets

### ISSUE THREAD

**Issue by tom-kramer** [odoo/odoo#75324] opened 2021-08-19 13:37 UTC
Impacted versions:
- 14.0

Steps to reproduce:
- Switch into debug mode
- Regenerate assets

Current behavior:
- Page is refreshed
- Assets return 404
- Blank page

Expected behavior:
- Assets are regenerated and page is refreshed
- No blank page

Video/Screenshot link (optional):
https://user-images.githubusercontent.com/22794962/130077839-c6b76ef6-9880-4997-b1e4-6c6505452501.mov

Support ticket number submitted via odoo.com/help (optional):
#2628854

**Comment by pedrobaeza** [comment] 2021-08-19 13:53
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by tom-kramer** [comment] 2021-08-19 14:09
@pedrobaeza Did you see the attached video? It is already in runbot as you can see in the url in the bottom left.

**Comment by pedrobaeza** [comment] 2021-08-19 14:14
You have hidden the URL, so it can't be appreciated if it's runbot or not. Anyways, I'm just replicating the same without problems.

**Comment by tom-kramer** [comment] 2021-08-19 14:33
@pedrobaeza I mean the url in the bottom left, sorry for not being clear enough. I can replicate it with chrome, safari and firefox aswell. Are you in normal developer mode or asset mode?

**Comment by pedrobaeza** [comment] 2021-08-19 14:35
I were in developer mode.

**Comment by tom-kramer** [comment] 2021-08-19 14:40
@pedrobaeza Did you clear all caches? I can reproduce it on https://9505575-14-0-all.runbot50.odoo.com/web?debug=1#cids=1&home= every time. I am using chrome 92.0.

**Comment by tbaden** [comment] 2021-08-19 14:42
I can also reproduce this. Having all caches disabled and running on 
https://9505575-14-0-all.runbot50.odoo.com/
as admin user in 'normal' debug mode and clicking 'regenerate asset bundels' causes this:
![Bildschirmfoto 2021-08-19 um 16 42 03](https://user-images.githubusercontent.com/6755125/130088980-ece46b64-53c9-4f2f-9ab0-7774fbfd7f70.png)

**Comment by pedrobaeza** [comment] 2021-08-19 14:43
I'm using Firefox, and I'm not. Anyways, I don't see why are you twisting the steps to reproduce for getting that problem. Do you have a real case?

**Comment by tom-kramer** [comment] 2021-08-19 18:40
@pedrobaeza Well, I am not twisting the steps to reproduce. I guess it's kind of obvious that if you have a cached version of assets, the error will not appear. 

As you can see in the comment from @tbaden the error is reproducible. Can you maybe check with another browser?

**Comment by pedrobaeza** [comment] 2021-08-19 18:41
But how do you get to a situation where you need to regenerate assets that way is what I don't get. Anyways, I let this issue opened to see if Odoo team considers this as something to be checked.

**Comment by tom-kramer** [comment] 2021-08-30 08:10
@pedrobaeza Is there still information missing?

**Comment by pedrobaeza** [comment] 2021-08-30 08:38
You can check my latest comment.

**Closed** 2023-06-03 17:21 UTC
Labels: 14.0
