### ISSUE TITLE
Currency Symbol for CAD is before not after.

### ISSUE THREAD

**Issue by GasparYYC** [odoo/odoo#18544] opened 2017-07-30 01:02 UTC
Impacted versions:
10
Steps to reproduce:

1. In Setting -> Company Define the currency for the company as CAD
2. Save changes
3. Add any product to website with a price

Current behavior:
1. Dollar sign "$" is shown after the numbers

Expected behavior:
1.Dollar sign "$" should be before the numbers  (exactly like USD)

In Canada French or English the Currency symbol is the same as in the US.

You could fix the table: res_currency 
by changing the position to "before".

[Source:](https://en.wikipedia.org/wiki/Dollar_sign#Currencies_that_use_the_dollar_or_peso_sign)
**In real life:** Not true that French Canada shows the dollar symbol ($) after that number, that was in the 60's and 70s.. 

Thank you for your consideration

**Comment by Yenthe666** [comment] 2017-07-31 15:10
@mart-e this looks like an improvement for you.

**Comment by GasparYYC** [comment] 2017-07-31 17:50
@mart-e Yes and no, because in English Canada the symbol after the number is just plain wrong (not up for discussion). 

thanks

**Comment by mart-e** [comment] 2017-08-03 14:05
Thanks for the report.
The issue is that the symbol is one the currency instead of the language. I believe it was set on after as correct for the French speakers. However, you say it is not true.

> In real life: Not true that French Canada shows the dollar symbol ($) after that number, that was in the 60's and 70s..

@dufresnedavid @jbchouinard @Ehtaga (or others from Québec), could you confirm?

**Comment by dufresnedavid** [comment] 2017-08-03 14:14
In French (CA), I confirm that the symbol is always shown after the amount.

**Comment by Ehtaga** [comment] 2017-08-03 14:15
@GasparYYC @mart-e Sorry but in French, the currency symbol must be after the number (for CAD and USD).
See http://bdl.oqlf.gouv.qc.ca/bdl/gabarit_bdl.asp?id=1584 (Quebec government)

**Comment by mart-e** [comment] 2017-08-03 15:10
Thanks for the answer, this is what I thought.

We already had this discussion with @qdp-odoo, we had not a clear rule for the currency position and we chose not to move it and let the user configure it depending on their usecase.

**Comment by dufresnedavid** [comment] 2017-08-03 15:15
@mart-e the symbol position should not depend on the currency. It should depend only on the language.

In en_US, the symbol is always before the amount whatever the currency.

Just take a look at Word and Libreoffice.
Also, take a look at http://babel.pocoo.org/en/latest/api/numbers.html.

**Comment by GasparYYC** [comment] 2017-08-03 15:23
Thank you all for your comments. 
@mart-e Sounds like you're pushing for a binary solution. In my opinion this is a language setting, in my case we are planning to have operations in English (Canada) and French (Canada). 

How can we have both? Its the same currency and the same country.

**Comment by mart-e** [comment] 2017-08-04 09:40
I am not looking for a binary solution but now (in v8-10), it is defined on the currency and that is not possible to change in stable.

However, on, "should we change or not in master", it was an old debate we had already at least 2 years ago (I can no longer find the thread). We can discuss that again but, at that time, we chose not to change it.

**Comment by pedrobaeza** [comment] 2018-06-05 17:40
Seeing the debate, I close the issue as no issue at all, but the debate about linking currency position to language instead of currencies (that doesn't happen in Spanish for example), can be extended for newer versions.

**Closed by pedrobaeza** 2018-06-05 17:40 UTC
Labels: 10.0, Localization

**Comment by mart-e** [comment] 2018-06-06 09:47
FYI, after some lobbying, we have created a task to define the currency position and presence of space to be set on the language. It is currently been developed at https://github.com/odoo-dev/odoo/tree/master-base-currency-position-rop but not ready yet.
Hopefully, this one will be accepted, merged and not reverted before v12...
