### ISSUE TITLE
HR Attendance inconsistency in records in kiosk mode [SaaS]

### ISSUE THREAD

**Issue by rizzopablo** [odoo/odoo#25849] opened 2018-07-18 13:50 UTC
Impacted versions: v10 and v11 only for Odoo SaaS service.

Steps to reproduce:

Use the kiosk mode for checking in and out, using a card reader (barcodes or rfid, tested both of them)

Current behavior:

Odoo SaaS randomly saves inconsistent check in and out records with the same in and out time (seconds included) and thereafter the inconsistency of the database prevents further check in/out for that employee.

Expected behavior:

Odoo should keep database consistency by two ways:

1.- Javascript should not send multiple requests from the same card read, with the exact same time, may be it's not clearing a buffer or something, so it sends a request to the server with multiple records for the same employee and the same time.
2.- The server side should not save multiple inconsistent attendance records with the exact same time for check in and out and for the same employee, even when the javascript sends the request with that incorrect data. Server should only record one consistent check out or check in for that time.

Video/Screenshot link (optional):

Video: https://dlive.io/video/blo/c971c400-8a90-11e8-b2de-f7be8f055a16
![error_attendance](https://user-images.githubusercontent.com/13275003/42885799-58b3857c-8a78-11e8-82fa-aaf4abdd9082.png)

**Comment by pedrobaeza** [comment] 2018-10-11 16:10
I think the problem is in the card reader itself, that sends double the information (maybe you should update your config)

**Comment by jcchoquet** [comment] 2018-10-17 17:44
HI,
i have the same problem with kiosk mode on Odoo V11.
i have added a safety time (3sec) on barcode reader. I have added a trace in log Odoo et I see for example 5 actions attendance in the same time.

**Comment by pedrobaeza** [comment] 2018-10-17 17:47
Thanks for the confirmation. @tivisse seems to be on it as he has self-assigned this. Let's wait for the answer.

**Comment by RomainLibert** [comment] 2018-12-31 13:42
Fixed by https://github.com/odoo/odoo/pull/28150

**Closed by RomainLibert** 2018-12-31 13:42 UTC
Labels: 10.0, 11.0, HR, Services
