### ISSUE TITLE
showing meeting details for a partner takes very long and is performed twice

### ISSUE THREAD

**Issue by grexe** [odoo/odoo#11417] opened 2016-03-19 19:35 UTC
Using Odoo 9.0c.20160319 on Debian Linux 8.3 testing (stretch) with PostgreSQL 9.5 (6.5GB databse with imported contacts using CSV->web and meetings imported by hand by reverse-engineering how meetings are created by Odoo), I am facing excessive loading times for viewing meeting details when navigating from the list of meetings with a given partner, regardless of how many meetings there are (tried with max. 12).

While the calendar listview with all meetings is shown in a second, it takes approx. 20secs (!) until the detail view for any selected meeting is completely rendered (after ~12secs it is shown the first time, but then loaded a second time).

From the server log, it seems that meeting details are queried one by one for the meeting, I think this query could be optimized but didn't look at the code yet:

```
2016-03-19 19:24:24,902 17986 INFO pauls werkzeug: 127.0.0.1 - - [19/Mar/2016 19:24:24] "POST /web/dataset/call_kw/res.partner/name_get HTTP/1.1" 200 -
2016-03-19 19:24:24,902 17986 INFO pauls werkzeug: 127.0.0.1 - - [19/Mar/2016 19:24:24] "POST /web/dataset/call_kw/res.partner/name_get HTTP/1.1" 200 -
2016-03-19 19:24:24,927 17986 INFO pauls werkzeug: 127.0.0.1 - - [19/Mar/2016 19:24:24] "POST /web/dataset/call_kw/res.partner/name_get HTTP/1.1" 200 -
2016-03-19 19:24:24,927 17986 INFO pauls werkzeug: 127.0.0.1 - - [19/Mar/2016 19:24:24] "POST /web/dataset/call_kw/res.partner/name_get HTTP/1.1" 200 -
2016-03-19 19:24:24,937 17986 INFO pauls werkzeug: 127.0.0.1 - - [19/Mar/2016 19:24:24] "POST /web/dataset/call_kw/res.partner/name_get HTTP/1.1" 200 -
2016-03-19 19:24:24,944 17986 INFO pauls werkzeug: 127.0.0.1 - - [19/Mar/2016 19:24:24] "POST /web/dataset/call_kw/res.partner/name_get HTTP/1.1" 200 -
2016-03-19 19:24:28,337 17986 INFO pauls werkzeug: 127.0.0.1 - - [19/Mar/2016 19:24:28] "POST /web/dataset/call_kw/calendar.event/fields_view_get HTTP/1.1" 200 -
2016-03-19 19:24:28,397 17986 INFO pauls werkzeug: 127.0.0.1 - - [19/Mar/2016 19:24:28] "POST /web/dataset/call_kw/res.partner/fields_get HTTP/1.1" 200 -
2016-03-19 19:24:28,402 17986 INFO pauls werkzeug: 127.0.0.1 - - [19/Mar/2016 19:24:28] "POST /web/dataset/call_kw/calendar.event.type/fields_get HTTP/1.1" 200 -
2016-03-19 19:24:28,405 17986 INFO pauls werkzeug: 127.0.0.1 - - [19/Mar/2016 19:24:28] "POST /web/dataset/call_kw/calendar.alarm/fields_get HTTP/1.1" 200 -
2016-03-19 19:24:42,327 17986 INFO pauls werkzeug: 127.0.0.1 - - [19/Mar/2016 19:24:42] "POST /web/dataset/call_kw/calendar.event/read HTTP/1.1" 200 -
2016-03-19 19:24:42,542 17986 INFO pauls werkzeug: 127.0.0.1 - - [19/Mar/2016 19:24:42] "POST /mail/read_followers HTTP/1.1" 200 -
2016-03-19 19:24:42,555 17986 INFO pauls werkzeug: 127.0.0.1 - - [19/Mar/2016 19:24:42] "POST /web/dataset/search_read HTTP/1.1" 200 -
2016-03-19 19:24:43,060 17986 INFO pauls werkzeug: 127.0.0.1 - - [19/Mar/2016 19:24:43] "POST /web/dataset/call_kw/calendar.attendee/read HTTP/1.1" 200 -
2016-03-19 19:24:49,999 17986 INFO pauls werkzeug: 127.0.0.1 - - [19/Mar/2016 19:24:49] "POST /web/dataset/call_kw/res.partner/get_attendee_detail HTTP/1.1" 200 -
```

Because I didn't find a simple way to configure the calendar view yet (see issue #11416 ), this is quite annoying, and actually inacceptable for everyday use at a customer site (where customer meetings are an integral part of the business).

**Comment by JKE-be** [comment] 2016-07-26 08:40
Hello
Can you check that you have always the same issue after a pull of the code ?

Where do you see in log that it is done 2x ? 
Can you take a screenshot of the chrome console with the request done and the time ... 
Because open an event in form view is very 'simple' operation and should not take so many seconds.

Ps: The performance for Calendar View in v10 has been improved. Now search view is linked to sidebar, so only 1 search/request.

**Comment by grexe** [comment] 2016-08-07 20:24
thank you @JKE-be for your updates on my issues, just checked now beucase of holidays - can only test at the customers site in ~2 weeks, sadly, as the owner is also on holidays...

For now I can only say that I noticed performance improvements in various areas, but sadly this issue still remains, and also occurs when creating a new meeting.

**Comment by JKE-be** [comment] 2016-08-08 08:35
Ok, no problem...
Open the calendar view can be slow sometimes... But open a calendar.event object in form view should be fast...
The network manager from chrome should help you to see which request is 'to optimize'...
To debug it, it will be easier if you can provide one db where the latency is reproducible...

**Comment by pedrobaeza** [comment] 2018-04-17 23:54
Closing as there hasn't been an answer.

Feel free to open a new issue if this is still happening, but please include all the detailed steps to reproduce the problem, and better if it can be reproducible in a demo environment like runbot (http://runbot.odoo.com).

**Closed by pedrobaeza** 2018-04-17 23:54 UTC

**Comment by grexe** [comment] 2018-05-03 14:03
sorry I'm no longer active on this, but it could be a local networking misconfiguration. Thanks for your support and I hope to have some time to check out Odoo again in the future!
