### ISSUE TITLE
[9.0] Manually added conditions in mail template body doesn't work

### ISSUE THREAD

**Issue by rruebner** [odoo/odoo#8699] opened 2015-09-24 10:17 UTC
Hi all,

it is no longer possible to add working conditions like "% if ... % endif" in mail template body parts in odoo version 9.

***Impacted versions:***

 - 9.0

***Steps to reproduce:***

* in runbot version 9 activate the developer mode
* go to Settings -> Technical -> Email -> Templates
* open any mail template and click on edit
* copy & paste the following code part in the mail template body
```
% if True:
<h1>Yah!</h1>
% endif
```
* save it and click on preview

***Current behavior:***

* you will see the whole condition part rendered as normal text

***Expected behavior:***

* conditions should work like in version 8, means that you only see "Yah!" for the example above

Side note: if you provide conditions in mail templates via XML data it works. If you add conditions manually later it doesn't work.

Regards, Robert

**Comment by jholze** [comment] 2015-10-23 19:44
@rruebner did you checked the update from Cesar ? Would be nice if we can supply a fix for this general odoo issue

**Comment by rruebner** [comment] 2015-10-27 09:51
@jholze Yes, I checked it and left a comment in it. There is no solution right now.

**Comment by jholze** [comment] 2015-11-18 08:39
@odony morning, can you please check this too, because i think it's a must have for odoo that it is possible to add conditions in the new mail editor like in the old one.

**Comment by odony** [comment] 2015-11-18 08:56
@Gorash Could you have a look at this issue and confirm? Thanks!

**Comment by jholze** [comment] 2015-11-18 10:53
:+1:

**Comment by jholze** [comment] 2015-11-24 14:26
Is @Gorash still alive :)

**Comment by Gorash** [comment] 2015-12-02 09:45
I be back, I'll check this issue

**Comment by jholze** [comment] 2015-12-10 14:03
@Gorash can you please have a look here as well

**Comment by Gorash** [comment] 2015-12-10 14:26
Yep,
It's ready, I had a button to edit code html inside the editor.
Thanks for your report

**Comment by jholze** [comment] 2016-03-17 16:16
I checked it. You are right, the edit code button is shown in debug mode, but the conditions are not working well. Try to check some of the mail templates eg. in 9. The conditions are shown as text, even in preview mode.

**Comment by rruebner** [comment] 2016-03-30 08:51
Hi @Gorash, the edit code button works and it shows the HTML source code. But like @jholze mentioned if you add a condition like the example mentioned in the issue description in the HTML source code and save the condition is stored as simple text. Can you please look at it again.

**Comment by Gorash** [comment] 2016-03-30 09:09
Is stored as simple text? It is not evaluated for sending the message?

**Comment by rruebner** [comment] 2016-03-30 09:37
Yes, thats right. It won't be evaluated. You will see the following condition as text in the email (like I mentioned it in the issue description).
```
% if True:
<h1>Yah!</h1>
% endif
```

**Comment by Gorash** [comment] 2016-03-30 09:51
The corrected error is just that the tags were automatically wrapper with a p tag. It's fixed. I have not had python evaluation error locally, I'll check.

**Comment by jholze** [comment] 2016-04-06 20:34
hey @Gorash, some updates here ?

**Comment by jholze** [comment] 2016-04-08 21:44
@Gorash please reopen

**Comment by Gorash** [comment] 2016-06-14 12:32
look https://github.com/odoo/odoo/pull/12416

**Comment by jholze** [comment] 2016-06-14 12:39
@rruebner can you please check. Thanks @Gorash

**Comment by Gorash** [comment] 2016-06-20 07:37
@rruebner Is this appropriate behavior ?

**Comment by Gorash** [comment] 2016-06-20 14:36
I don't have this issue :-/ but I try to fix... you can try
(when you have jinja code you have the editor in text mode and without jinja you can use preview mode, they are no other solution)

**Comment by Gorash** [comment] 2016-06-22 12:29
Fxed, tested by some people, merged :+1:

**Closed by Gorash** 2016-06-22 12:29 UTC

**Comment by jholze** [comment] 2016-06-22 14:28
@Gorash fixed where ? here #12416 ?

**Comment by Gorash** [comment] 2016-06-23 07:46
Yes. Sorry for not having put the reference of the commit : https://github.com/odoo/odoo/commit/f38f8930f0436a40f675fa1d054a9d46f550d440
Having done after test. Since this is a big change, if there is an issue contact me with the full traceback version of the browser ... I can take into account with my computer because I have not been able to reproduce the rruebner bug (is via colleagues tests that I solve it)

**Comment by Gorash** [comment] 2016-06-23 09:49
I revert the commit for internal choice.
Odoo want to use qweb in template and remove jinja support on next version. If users want to use jinja they can change the view to use text widget instead of html widget. We are going to create task to convert template who use jinja into qweb template.

**Comment by rruebner** [comment] 2016-06-23 12:12
Hi @Gorash,

I tested it again in latest runbot v9 after you revert your fix. It works now but I don't know what commit fixed it at the end. To add conditions in email templates you have to follow these steps:

1. go to Settings -> Technical -> Email -> Templates 
2. open any mail template and click on edit
3. click on the **Code View** icon in the body html icon bar, it doesn't work in the default editor view
4. add your conditions like my example in the issue description
5. click again on the **Code View** icon to switch back to the default editor view, if you save the email template with activated code view the condition parts won't be saved
6. save the email template
7. click on the preview button -> the condition part is not rendered as text and you see only the content between the condition tags

Finally the issue is fixed for me. Lets see how it will work with qweb templates in the future.
