### ISSUE TITLE
[11.0 e] Can not print Cost Analysis report for Manufacturing order 

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#20119] opened 2017-10-13 05:02 UTC
Impacted versions: 11.0 e

Steps to reproduce: Go to [http://270891-11-0-349612.runbot14.odoo.com](http://270891-11-0-349612.runbot14.odoo.com) Manufacturing Orders --> Select Order and Print Cost Analysis report
 or Open Order MO/00025 and Print Cost Analysis report
Current behavior: 
```
500: Internal Server Error
Error
Error message:

unsupported operand type(s) for +=: 'float' and 'NoneType'
```

![](https://image.prntscr.com/image/RyNV6sHISjuEW8m3HaejdA.png)

Expected behavior: Should Print report. 

Video/Screenshot link (optional): [https://prnt.sc/gwsjnq](url) https://prnt.sc/gwsjnq

**Comment by Yenthe666** [comment] 2017-10-13 07:51
Hi @sswapnesh,

Thank you for your report - this is indeed a bug:
![image](https://user-images.githubusercontent.com/6352350/31535638-146e9c96-affc-11e7-9a2b-1b9d425c18fe.png)
The problem is because of the Python 3 changes. Problem is at this line:
https://github.com/odoo/enterprise/blob/34961203551b37f18df657101ef4b36142967b4a/mrp_account/reports/mrp_cost_structure.py#L51

@xmo-odoo can you fix?

Regards,
Yenthe

**Comment by xmo-odoo** [comment] 2017-10-13 10:10
Just because it has a type error in the traceback does not mean it has to do with Python 3, Python 2 won't add a float and a None either.

Here it seems more likely that a stock move has no price_unit or product_qty, this is not visible in the UI because they're replaced by 0 during read, but in the database the value is a NULL and because the report is implemented using straight SQL, you end up with a `None` value as cost.

**Comment by Yenthe666** [comment] 2017-12-12 09:27
Hi @sswapnesh,

This has been fixed in the meanwhile!
![image](https://user-images.githubusercontent.com/6352350/33876864-fea6ec92-df26-11e7-87eb-7e7c33158689.png)

Regards,
Yenthe

**Comment by sswapnesh** [comment] 2017-12-12 17:52
Hello @Yenthe666 
I got the new bug in this report.

```
float division by zero
Traceback (most recent call last):
  File "/home/odoo/runbot/extra/runbot/static/build/285832-11-0-de25b5/odoo/addons/base/ir/ir_qweb/qweb.py", line 341, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_2412_1753
  File "<template>", line 2, in body_call_content_1752
  File "<template>", line 3, in body_call_content_1751
  File "<template>", line 8, in foreach_1750
  File "<template>", line 30, in foreach_1728
ZeroDivisionError: float division by zero

Error to render compiling AST
ZeroDivisionError: float division by zero
Template: 2412
Path: /templates/t/t/t/div/t[2]/table/tbody/tr[1]/td[4]/span
Node: <span t-esc="m['cost'] / m['qty']" t-options="{&quot;widget&quot;: &quot;monetary&quot;, &quot;display_currency&quot;: currency}"/>


```

You can check it on [Runbot](http://285832-11-0-de25b5.runbot12.odoo.com/web?#id=39&view_type=form&model=mrp.production&action=757&menu_id=510)


![](https://image.prntscr.com/image/8VsRMNgjT3auO1ToM7NwiA.png)

**Comment by Yenthe666** [comment] 2017-12-12 18:43
Hmm indeed. The MO form itself:
![image](https://user-images.githubusercontent.com/6352350/33902223-a370aafe-df74-11e7-827b-f38a19324ff4.png)
Odd that I can't reproduce it out of the box.

**Comment by sswapnesh** [comment] 2017-12-12 18:47
You should get the error.

![](https://image.prntscr.com/image/YLEd0jKQRiSjmFhVJxcTLA.png)

**Comment by sswapnesh** [comment] 2017-12-12 18:52
The reason is we can set Zero quantity in [Bom](http://285832-11-0-de25b5.runbot12.odoo.com/web?#id=2&view_type=form&model=mrp.bom&menu_id=510) Line. (Which should not be allowed, In version 10 e We can not set product qty to Zero in Bom line)


![](https://image.prntscr.com/image/Ddqf6wYWQvqp2nXkjTlQXw.png)

**Comment by sle-odoo** [comment] 2017-12-27 14:14
@sswapnesh Hi, sorry for the delay. Null bom line are now allowed to mark some components of a bom as optional.

I just created a bom with a 0 component and some other normal ones and the cost analysis did not trigger any tracebacks. I see in your screenshot that you are working with workorders, maybe the issue stems from there. Can you try to create a new bom from scratch with a new routing from scratch and reproduce the issue? These steps would be really helpful.

Regards

**Comment by sle-odoo** [comment] 2017-12-27 15:16
@sswapnesh can you confirm that if you "mark as done" the manufacturing order, the traceback does not appear?

**Comment by sswapnesh** [comment] 2017-12-27 15:26
Hello @sle-odoo 
Give me few minutes. I am checking it on runbot.

**Comment by sswapnesh** [comment] 2017-12-27 15:29
Just generated on Runbot.

[Here](http://288639-11-0-754c73.runbot8.odoo.com/web?#id=1&view_type=form&model=mrp.bom&action=767&menu_id=511) is the Bom.

You should get traceback for this [Order.](http://288639-11-0-754c73.runbot8.odoo.com/web?#id=40&view_type=form&model=mrp.production&action=759&menu_id=)

**Comment by sle-odoo** [comment] 2017-12-27 15:30
@sswapnesh ok, found the issue. it's due to the fact that the cost analysis should not be printed on a not yet done MO, indeed
- the cost method is applied when validating a move so it doesn't make sense to display it at this time (you probably want to see the bom cost report)
- the view expects to work on move where the quantity cannot be 0, and if you use an optional bom line, the quantity is 0 until the move is validated (goes to the cancelled state)

Actually the report should display "Some of the Manufacturing Order(s) selected are not done yet" when printing on a non done MO, but it's not working. I'll make a fix. Thanks for the report

**Comment by sswapnesh** [comment] 2017-12-27 15:44
One more thing I noticed when I copied [MO/00021](http://288639-11-0-754c73.runbot8.odoo.com/web?debug#id=40&view_type=form&model=mrp.production&action=759&menu_id=511) (It is done State), It created MO/00022 (In Confirmed state) but I didn't get Buttons to Produce MO.


![](https://image.prntscr.com/image/J0up8tavRLiGJoi11nf_Xw.png)

Correct me If I am missing something.

**Closed** 2017-12-28 14:36 UTC
Labels: 11.0, confirmed
