### ISSUE TITLE
parent position not recomputed

### ISSUE THREAD

**Issue by JonathanStein** [odoo/odoo#9055] opened 2015-10-13 15:58 UTC
The parent_left and parent_right fields are only recomputed when the parent is changed. We also need to recompute the position if any fields in the "_parent_order" was changed.

Example: Financial accounts have _parent_order = "code". If account "1010 Sales X" and account "1020 Sales Y" have the same parent account, try to change "1010" to "1030".
You will then have "1030 Sales X" before "1020 Sales Y".

The decision to recompute is here:
https://github.com/odoo/odoo/blob/9.0/openerp/models.py#L3860

**Comment by clb-openfire** [comment] 2015-11-06 10:16
This is a duplicate of bug reported for v7.0 and including a fix (still waiting for being merged)
see https://github.com/odoo/odoo/pull/829

**Comment by pedrobaeza** [comment] 2018-04-03 23:13
This seems pretty old and the way hierarchy is handled has even changed to another method in master, so I close this.

**Closed by pedrobaeza** 2018-04-03 23:13 UTC
