### ISSUE TITLE
multi company issue

### ISSUE THREAD

**Issue by vanderperre** [odoo/odoo#57982] opened 2020-09-17 17:15 UTC
Impacted versions:
13.0
Steps to reproduce:
- multi company
- pricelist set on
- set company property to use common pricelist
- product belong to company
-create a product template with default_get and onchange

Current behavior:
    due to the fact something is broken when creating a product template
    with default get and onchange (custom module), instead of 
    a POST create template when adding price list (std behavior), the patch is 
    to ignore check_company consistency because it result with a res.company() 
    object to compare to company_ids or company.id ... perhaps an odoo bug
    In fact when you use new ID instead of true ID implied in multicompany rule
    ===> use check_company=False on the adequate field

Expected behavior:
consider object with new id as object with true id

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2020-09-17 17:18
Sorry, but I don't get the problem unless you specify better the steps to reproduce the problem and the actual problem.

**Comment by vanderperre** [comment] 2020-09-17 17:30
Hi Pedro,
models.py, line 3174,  result of comparaison is not attended when new id record

**Comment by pedrobaeza** [comment] 2020-09-17 17:44
That's not what I ask for, but reproducible steps in the UI for getting to what you consider an error, and what is the error.

**Comment by vanderperre** [comment] 2020-09-17 17:56
Hi Pedro, 

Custom module for product template
class ProductTemplate(models.Model):
    _inherit = "product.template"

add a field like this : 
    product_pricelist_item_ids = fields.One2many(
        comodel_name='product.pricelist.item',
        inverse_name='product_tmpl_id',
        string='Prices'
    )

instead of button action to go to the price list (this involve a POST request for creating the product template) : 
 
insert the field product_pricelist_item_ids in the product template form

...

**Comment by pedrobaeza** [comment] 2020-09-17 17:59
Uhm, this is then not a problem in Odoo, but what you are trying to do and your unknowledge of how this works.

This issue tracker is for notifying issues with Odoo standard code without any modification.

Please ask on forums how to solve your specific development problem.

Closing due to this.

**Closed by pedrobaeza** 2020-09-17 17:59 UTC
Labels: Need information

**Comment by vanderperre** [comment] 2020-09-17 18:01
Already solved ;)
