### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by pedroporras** [odoo/odoo#24560] opened 2018-05-03 21:43 UTC
Impacted versions:
Odoo v10.0
Steps to reproduce:
Create new sale order with other user diferent to admin
Current behavior:
I cant create nothing in sale order, crm and clients
Expected behavior:
It should leave me create it.
Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/11019468/39604225-df9f5e6c-4ef0-11e8-9f5e-b003b1b41a23.png)

**Comment by pedrobaeza** [comment] 2018-05-03 22:03
Hi, I'm not able to reproduce this problem in latest runbot version, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-05-03 22:03 UTC
