### ISSUE TITLE
Blog Post with Publish Date instead of Create Date

### ISSUE THREAD

**Issue by parthivgls** [odoo/odoo#7962] opened 2015-08-09 10:36 UTC
Current v8 website_blog follows "create_date" field for listing blogs and use "create_date" for counting as well. 

It fails where some one wants to write the blog in advance but don't want to publish ASAP. In other CMS, it's quite possible to change this using "publish_date", which by default will be current date but can be changed as well. In current Scenario "create_date" is not modifiable.

**Comment by lmignon** [comment] 2015-08-09 10:42
@parthivgls  take a look at https://github.com/OCA/website/tree/8.0/website_blog_mgmt

**Comment by Yenthe666** [comment] 2016-08-05 09:30
Duplicate of https://github.com/odoo/odoo/issues/7963
Closing this issue because it is a duplicate.

**Closed by Yenthe666** 2016-08-05 09:30 UTC
