### ISSUE TITLE
TypeError: self.records.find(...) is undefined

### ISSUE THREAD

**Issue by max3903** [odoo/odoo#7650] opened 2015-07-16 22:08 UTC
# Versions
8

# Steps to reproduce
* Create a payment for Agrolait and select a payment method in USD
* Enter the amount: 100
* Click on the line and check the box "Full Reconcile"
* Click on save

# Result
I get the error message below:
```
TypeError: self.records.find(...) is undefined
```

# Expected result
The payment is saved.

**Comment by Yenthe666** [comment] 2016-08-05 09:42
Hi @max3903,

Thanks a lot for your report! I've just tested this in the latest Odoo 8 and I can no longer reproduce this issue.
It looks like it has been fixed in the meanwhile :gem: 

Regards,
Yenthe

**Closed by Yenthe666** 2016-08-05 09:42 UTC
