### ISSUE TITLE
[ALL] handle widget is not available in the official Odoo app

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#37953] opened 2019-10-04 06:22 UTC
Impacted versions: All, tested in detail with an Odoo V12 instance

Steps to reproduce:
1. Connect to an Odoo enterprise instance, go to sales and open (or create) a sale order.
2. Add multiple products lines on this sale order.
3. Now try to reorder the lines just like you can do on a desktop with the handle widget

Current behavior:
You cannot change the order of lines as the handle widget is not shown and it is not possible to (re)order sale order lines.

Expected behavior:
Ability to use the handle just like on the desktop, allowing sales persons on the road to structure their sale orders.

**Comment by Yenthe666** [comment] 2019-10-04 06:23
@adr-odoo could you have a look at this and give input please? I've had several customers in the past reporting this was not possible. I've tested it and this is indeed quite a limitation..

**Comment by Yenthe666** [comment] 2019-10-15 07:19
OPW 2087251

**Comment by adr-odoo** [comment] 2019-10-17 07:08
Thanks for your feedback.
Unfortunately, this feature has been hidden because it's not currently implemented.
We consider this as a feature request and an internal task will be created.
I can not guarantee the feasibility of the task, nor the delay.

As this is not a bug, I allow myself to close this issue.

Regards,

**Closed by adr-odoo** 2019-10-17 07:08 UTC
Labels: 12.0, 13.0, Mobile app, OE

**Comment by Yenthe666** [comment] 2019-10-17 07:50
Oh man, that is pretty disappointing to hear :( I've got a few dozen users starting with Odoo soon who all have to make quotes etc on the road, in the mobile app. :/ Any workarounds or options to speed this up available (except for using the web browser)?
