### ISSUE TITLE
Could not send quotation get_base_url

### ISSUE THREAD

**Issue by kolmano** [odoo/odoo#31877] opened 2019-03-15 12:20 UTC
Impacted versions:
odoo 12.0ce

Steps to reproduce:
 - Install sales & CRM module
 - create quotation and fill it with anything
 - click 'Send by Email' button
 - keep everything default (mail template: Sales Oder: Send by email)
 - click on button send
get this error message: 
`Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/init/odoo_inst/odoo/addons/base/models/qweb.py", line 344, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_300_649
AttributeError: 'sale.order' object has no attribute 'get_base_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/init/odoo_inst/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/init/odoo_inst/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/init/odoo_inst/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/init/odoo_inst/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/init/odoo_inst/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/init/odoo_inst/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/init/odoo_inst/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/init/odoo_inst/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/init/odoo_inst/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/init/odoo_inst/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/init/odoo_inst/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/init/odoo_inst/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/init/odoo_inst/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/init/odoo_inst/addons/mail/wizard/mail_compose_message.py", line 193, in action_send_mail
    self.send_mail()
  File "/home/odoo/init/odoo_inst/addons/mail/wizard/mail_compose_message.py", line 267, in send_mail
    ActiveModel.browse(res_id).message_post(**post_params)
  File "/home/odoo/init/odoo_inst/addons/sale/models/sale.py", line 643, in message_post
    return super(SaleOrder, self.with_context(mail_post_autofollow=True)).message_post(**kwargs)
  File "/home/odoo/init/odoo_inst/addons/rating/models/mail_thread.py", line 14, in message_post
    message = super(MailThread, self).message_post(**kwargs)
  File "/home/odoo/init/odoo_inst/addons/mail/models/mail_thread.py", line 2059, in message_post
    self._message_post_after_hook(new_message, values, model_description=model_description, mail_auto_delete=mail_auto_delete)
  File "/home/odoo/init/odoo_inst/addons/mail_bot/models/mail_thread.py", line 12, in _message_post_after_hook
    return super(MailThread, self)._message_post_after_hook(message, values, model_description=model_description, mail_auto_delete=mail_auto_delete)
  File "/home/odoo/init/odoo_inst/addons/mail/models/mail_thread.py", line 2081, in _message_post_after_hook
    mail_auto_delete=mail_auto_delete,
  File "/home/odoo/init/odoo_inst/addons/mail/models/mail_message.py", line 1060, in _notify
    model_description=model_description, mail_auto_delete=mail_auto_delete)
  File "/home/odoo/init/odoo_inst/addons/mail/models/mail_message.py", line 1137, in _notify_recipients
    self.env['res.partner']._notify(self, partner_email_rdata, record, force_send=force_send, send_after_commit=send_after_commit, model_description=model_description, mail_auto_delete=mail_auto_delete)
  File "/home/odoo/init/odoo_inst/addons/mail/models/res_partner.py", line 135, in _notify
    mail_body = base_template.render(template_ctx, engine='ir.qweb', minimal_qcontext=True)
  File "/home/odoo/init/odoo_inst/addons/web_editor/models/ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/home/odoo/init/odoo_inst/odoo/addons/base/models/ir_ui_view.py", line 1291, in render
    return self.env[engine].render(self.id, qcontext)
  File "/home/odoo/init/odoo_inst/odoo/addons/base/models/ir_qweb.py", line 59, in render
    result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/home/odoo/init/odoo_inst/odoo/addons/base/models/qweb.py", line 272, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/home/odoo/init/odoo_inst/odoo/addons/base/models/qweb.py", line 351, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.models.qweb.QWebException: 'sale.order' object has no attribute 'get_base_url'
Traceback (most recent call last):
  File "/home/odoo/init/odoo_inst/odoo/addons/base/models/qweb.py", line 344, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_300_649
AttributeError: 'sale.order' object has no attribute 'get_base_url'

Error to render compiling AST
AttributeError: 'sale.order' object has no attribute 'get_base_url'
Template: 300
Path: /templates/t/table/tr[1]/td/table/tbody/tr[1]/td/t[3]
Node: <t t-set="base_url" t-value="record.get_base_url()"/>`

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment] 2019-03-16 05:44
Hello @kolmano 
I am not able to reproduce this on latest v12 (Tried with and without demo).

Could please check again ? (Ref commit https://github.com/odoo/odoo/commit/c1be1993f9bcd11f3fdff78e81ea71e518c15779)

**Comment by pedrobaeza** [comment] 2019-03-17 21:20
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile or it's a misconfiguration problem, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2019-03-17 21:20 UTC
Labels: 12.0, Services
