### ISSUE TITLE
rtl error

### ISSUE THREAD

**Issue by amrdesign** [odoo/odoo#33546] opened 2019-05-21 20:52 UTC
Impacted versions: 12

when i change langues to "RTL" i got error
```
خطأ:
Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined

http://localhost:8069/web/content/248-eddffb7/web.assets_common.js:3744
تتبع الأثر:
TypeError: Cannot read property 'getBoundingClientRect' of undefined
    at computeFloatOuterWidthWithMargins (http://localhost:8069/web/content/248-eddffb7/web.assets_common.js:3744:73)
    at _adapt (http://localhost:8069/web/content/248-eddffb7/web.assets_common.js:3743:461)
    at Object.initAutoMoreMenu (http://localhost:8069/web/content/248-eddffb7/web.assets_common.js:3737:533)
    at Class.start (http://localhost:8069/web/content/254-d74b033/web.assets_backend.js:847:189)
    at Class.prototype.<computed> [as start] (http://localhost:8069/web/content/248-eddffb7/web.assets_common.js:3538:488)
    at http://localhost:8069/web/content/248-eddffb7/web.assets_common.js:3683:52
    at http://localhost:8069/web/content/248-eddffb7/web.assets_common.js:802:681
    at fire (http://localhost:8069/web/content/248-eddffb7/web.assets_common.js:796:299)
    at Object.add [as done] (http://localhost:8069/web/content/248-eddffb7/web.assets_common.js:797:467)
    at Array.<anonymous> (http://localhost:8069/web/content/248-eddffb7/web.assets_common.js:802:649)
```

**Comment by Yenthe666** [comment] 2019-05-23 13:34
@mart-e did you see this one before?
@amrdesign can you please add steps on how to reproduce this error? Can you reproduce it on one of the latest Odoo instances at runbot.odoo.com?

**Comment by mart-e** [comment] 2019-05-23 13:37
Please give the error in debug=assets more, otherwise it is not very infromative.
Access it your odoo instance at `http://<yourdomain>/web?debug=assets`

**Comment by jonmercarpio** [comment] 2019-06-02 13:28
Duplicate of #31653

**Comment by pedrobaeza** [comment] 2019-06-02 20:18
Closing as seems to be the same missing library and no other answer.

**Closed by pedrobaeza** 2019-06-02 20:18 UTC
Labels: 12.0, Need information
