### ISSUE TITLE
[11.0] uom modification in product is not allowed anymore

### ISSUE THREAD

**Issue by cvinh** [odoo/odoo#31652] opened 2019-03-07 04:16 UTC
Impacted versions: 11.0

Steps to reproduce:
edit an archived product that has stock moves and change the unit of measure
Current behavior:
The modification is not allowed with message "You can not change the unit of measure of a product that has already been used in a done stock move. If you need to change the unit of measure, you may deactivate this product."
Expected behavior:
The modification should be allowed as the product is archived
Video/Screenshot link (optional):

**Comment by cvinh** [comment] 2019-03-07 04:23
@pimodoo could you explain why you made that change in the commit 0ae3e5a8b4180162c18a1f1f106855851e92e2ae ?

We need to change the unit of measure of a product without having to recreate it (in order to keep the history)
I don't see the case where we could have bad configurations except if there are pending sale_orders, purchase orders, stock moves...etc.... Maybe you meant that changing uom of a product is very dangerous and you prefered to block that...
In the case you really want to forbid a change of uom, the message should be changed to something like "You can not change the unit of measure of a product that has already been used in a done stock move. You may desactivated this product and duplicate it to a new product"
Thanks in advance for your reply

**Comment by pedrobaeza** [comment] 2019-03-07 08:24
This is done on purpose, as some conversions are done on analysis and other places of Odoo, and changing UoM of a product produces incompatible conversions, so this is a must and allowing this in the past was an accident, not something intended.

Closing then as intended behavior.

**Closed by pedrobaeza** 2019-03-07 08:24 UTC

**Comment by cvinh** [comment] 2019-03-07 18:40
@pedrobaeza thanks for replying
@pimodoo so the raise error message has to be changed indeed

**Comment by pedrobaeza** [comment] 2019-03-08 10:46
The error is not very clear but it means that you deactivate that product and create another one.
