### ISSUE TITLE
Connection Lost Error.

### ISSUE THREAD

**Issue by asiamatrix** [odoo/odoo#30380] opened 2019-01-20 16:08 UTC
1. Edit POS Session and Add Payment Method.
2. And then Click Save button.
3. I'm facing "connection lost" "You are trying to back online"

<img width="952" alt="screenhunter 608" src="https://user-images.githubusercontent.com/44358604/51441836-4bc83f00-1d04-11e9-9e31-01f24ac354da.png">

And Showing the following 
<img width="649" alt="screenhunter 607" src="https://user-images.githubusercontent.com/44358604/51441813-0d328480-1d04-11e9-8f51-2a654de0b964.png">

How can i fix? Please help me.

**Comment by pedrobaeza** [comment] 2019-01-20 16:09
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by asiamatrix** [comment] 2019-01-20 16:12
Facing Connection lost everywhere.
I facing when sending a quotation.
<img width="962" alt="screenhunter 600" src="https://user-images.githubusercontent.com/44358604/51441860-99dd4280-1d04-11e9-92b5-d59a3faacf11.png">

**Comment by pedrobaeza** [comment] 2019-01-20 16:13
This is for sure something bad in your end, probably with the reverse proxy you are using.

Closing as out of the scope of this issue tracker.

**Closed by pedrobaeza** 2019-01-20 16:13 UTC
Labels: Need information
