### ISSUE TITLE
Uncaught Error: NameError: name 'active_id' is not defined

### ISSUE THREAD

**Issue by Guobower** [odoo/odoo#15830] opened 2017-03-11 04:04 UTC
Impacted versions:
10.0  20170307 20170307
Steps to reproduce:
1、Creat database
2、Change administrator name to adm，setup home action to Apps
3、Rename my company name to Master
3、Install Account & Finance
Then got the error message
and any action can lead to this issue.
I test many times, this issue attend always.
Current behavior:
![qq 20170328173702](https://cloud.githubusercontent.com/assets/22065407/24399525/a4223898-13df-11e7-96f0-2ffe517ba423.png)
![qq 20170328173842](https://cloud.githubusercontent.com/assets/22065407/24399538/adc0347c-13df-11e7-86d9-91623a80e076.png)

**Comment by mart-e** [comment] 2017-03-13 15:08
Hello,

> Steps to reproduce:
> install account ,inventory. sales, parchase, mrp

Sorry but we will need more than that. Which actions do you make,...
I see you have your Odoo configured in Chinese. Can you reproduce this issue in English or in a different language ?
Installing these modules works fine. So, if there is a issue, it must be in some very specific conditions.

**Comment by Guobower** [comment] 2017-03-28 09:47
Impacted versions:
10.0  20170307 20170307
Steps to reproduce:
1、Creat database
2、Change administrator name to adm，setup home action to Apps
3、Install Account & Finance
Then got the error message
![Uploading QQ截图20170328173702.png…]()
![Uploading QQ截图20170328173842.png…]()

**Comment by aheficent** [comment] 2017-09-21 08:15
Steps to reproduce from my side:
1 create demo database
2 activate developer mode
3 set home action to Apps(the action associated to the top menu)
4 install a module or execute any action that makes the browser to redirect

If we select the action associated to the menu Apps/apps this issue is not happening.

**Comment by Karsten-77** [comment] 2017-11-20 14:24
Hello!
I have a semilar Error at Odoo 11 Head 92cb7800514f5ccb49a7f486284040f891b6c984 .
1 create demo database
2 install website_sale
3 activate developer mode with assets

Fehler:
Error: NameError: name 'active_id' is not defined
```
http://dev.tomws.ddnss.de/web/static/lib/py.js/lib/py.js:370
Zurückverfolgung
PY_ensurepy@http://dev.tomws.ddnss.de/web/static/lib/py.js/lib/py.js:370:19
py.evaluate@http://dev.tomws.ddnss.de/web/static/lib/py.js/lib/py.js:1340:20
py.evaluate@http://dev.tomws.ddnss.de/web/static/lib/py.js/lib/py.js:1409:34
py.evaluate@http://dev.tomws.ddnss.de/web/static/lib/py.js/lib/py.js:1418:21
py.eval@http://dev.tomws.ddnss.de/web/static/lib/py.js/lib/py.js:1453:16
eval_contexts/<@http://dev.tomws.ddnss.de/web/static/src/js/core/pyeval.js:850:25
iterator@http://dev.tomws.ddnss.de/web/static/lib/underscore/underscore.js:176:16
createReduce/<@http://dev.tomws.ddnss.de/web/static/lib/underscore/underscore.js:191:14
_.mixin/</_.prototype[name]@http://dev.tomws.ddnss.de/web/static/lib/underscore/underscore.js:1484:29
eval_contexts@http://dev.tomws.ddnss.de/web/static/src/js/core/pyeval.js:838:12
eval_contexts/<@http://dev.tomws.ddnss.de/web/static/src/js/core/pyeval.js:854:25
iterator@http://dev.tomws.ddnss.de/web/static/lib/underscore/underscore.js:176:16
createReduce/<@http://dev.tomws.ddnss.de/web/static/lib/underscore/underscore.js:191:14
_.mixin/</_.prototype[name]@http://dev.tomws.ddnss.de/web/static/lib/underscore/underscore.js:1484:29
eval_contexts@http://dev.tomws.ddnss.de/web/static/src/js/core/pyeval.js:838:12
pyeval@http://dev.tomws.ddnss.de/web/static/src/js/core/pyeval.js:981:16
do_action@http://dev.tomws.ddnss.de/web/static/src/js/chrome/action_manager.js:667:26
on_menu_action/</<@http://dev.tomws.ddnss.de/web/static/src/js/chrome/web_client.js:166:28
exec/<@http://dev.tomws.ddnss.de/web/static/src/js/core/concurrency.js:216:31
then/</</<@http://dev.tomws.ddnss.de/web/static/lib/jquery/jquery.js:3276:86
fire@http://dev.tomws.ddnss.de/web/static/lib/jquery/jquery.js:3119:38
add@http://dev.tomws.ddnss.de/web/static/lib/jquery/jquery.js:3165:49
then/</<@http://dev.tomws.ddnss.de/web/static/lib/jquery/jquery.js:3275:57
each@http://dev.tomws.ddnss.de/web/static/lib/jquery/jquery.js:383:49
then/<@http://dev.tomws.ddnss.de/web/static/lib/jquery/jquery.js:3272:49
Deferred@http://dev.tomws.ddnss.de/web/static/lib/jquery/jquery.js:3332:25
then@http://dev.tomws.ddnss.de/web/static/lib/jquery/jquery.js:3271:48
exec@http://dev.tomws.ddnss.de/web/static/src/js/core/concurrency.js:215:20
on_menu_action/<@http://dev.tomws.ddnss.de/web/static/src/js/chrome/web_client.js:164:24
then/</</<@http://dev.tomws.ddnss.de/web/static/lib/jquery/jquery.js:3276:86
fire@http://dev.tomws.ddnss.de/web/static/lib/jquery/jquery.js:3119:38
fireWith@http://dev.tomws.ddnss.de/web/static/lib/jquery/jquery.js:3231:49
Deferred/</deferred[tuple[0]]@http://dev.tomws.ddnss.de/web/static/lib/jquery/jquery.js:3321:33
add/<@http://dev.tomws.ddnss.de/web/static/src/js/core/concurrency.js:108:21
fire@http://dev.tomws.ddnss.de/web/static/lib/jquery/jquery.js:3119:38
fireWith@http://dev.tomws.ddnss.de/web/static/lib/jquery/jquery.js:3231:49
then/</</<@http://dev.tomws.ddnss.de/web/static/lib/jquery/jquery.js:3283:73
fire@http://dev.tomws.ddnss.de/web/static/lib/jquery/jquery.js:3119:38
fireWith@http://dev.tomws.ddnss.de/web/static/lib/jquery/jquery.js:3231:49
then/</</<@http://dev.tomws.ddnss.de/web/static/lib/jquery/jquery.js:3283:73
fire@http://dev.tomws.ddnss.de/web/static/lib/jquery/jquery.js:3119:38
fireWith@http://dev.tomws.ddnss.de/web/static/lib/jquery/jquery.js:3231:49
then/</</<@http://dev.tomws.ddnss.de/web/static/lib/jquery/jquery.js:3283:73
fire@http://dev.tomws.ddnss.de/web/static/lib/jquery/jquery.js:3119:38
fireWith@http://dev.tomws.ddnss.de/web/static/lib/jquery/jquery.js:3231:49
done@http://dev.tomws.ddnss.de/web/static/lib/jquery/jquery.js:9275:33
callback@http://dev.tomws.ddnss.de/web/static/lib/jquery/jquery.js:9685:57
```

**Comment by ntttue** [comment] 2017-12-06 09:01
I have the same error! in odoo 10. 
1- Create dabase. 
2- activate developer mode 
3- install Material module 
4- Go to localhost:8999/web 
![screenshot_9](https://user-images.githubusercontent.com/6711997/33653136-8edc3912-da9e-11e7-8f3b-2edcc5006a95.png)

**Comment by pedrobaeza** [comment] 2018-05-10 09:39
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-05-10 09:39 UTC
Labels: 10.0

**Comment by GertClaesen** [comment] 2020-09-03 08:32
Have you already tried to remove 'Home action' by preference of user? I had the same problem, by leaving this empty, problem was gone.

**Comment by sonmars** [comment] 2020-09-13 05:29
> Have you already tried to remove 'Home action' by preference of user? I had the same problem, by leaving this empty, problem was gone.

The same for me. But it is  bug if we cannot set this field with anything.
