### ISSUE TITLE
[11.0] Could not re-install Stock module

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#23094] opened 2018-02-15 16:39 UTC
Impacted versions: 11.0

Steps to reproduce: Uninstall Stock module --> Re-install it

Current behavior: Tracabck 

![](https://image.prntscr.com/image/BFYy3KU4TWWY2-SLEJXlZQ.png)

Expected behavior: Module should be installed 

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment] 2018-02-15 16:39
@sle-odoo  Could you please check this?

**Comment by sle-odoo** [comment] 2018-02-15 16:41
fixed by #22265 probably

**Comment by sswapnesh** [comment] 2018-02-15 16:42
When trying to install Manufacturing module

![](https://image.prntscr.com/image/maW_JDK7T_qyiUKDa0PQeg.png)

**Comment by sswapnesh** [comment] 2018-02-15 16:42
Just tested on Latest Runbot [http://303281-11-0-665496.runbot14.odoo.com](http://303281-11-0-665496.runbot14.odoo.com)

**Comment by sle-odoo** [comment] 2018-02-15 16:43
this issue is a duplicate of #22243
we don't have the ressources at the moment to look into it sadly

i'll close the original issue once it's fixed

thanks for the report

**Closed by sle-odoo** 2018-02-15 16:43 UTC

**Comment by sswapnesh** [comment] 2018-02-15 16:46
My bad, Agree with You.

**Comment by sle-odoo** [comment] 2018-02-15 16:52
no worries
