### ISSUE TITLE
[10.0] Get blog posts with URL encoded date_begin generates error

### ISSUE THREAD

**Issue by BIZ4Africa** [odoo/odoo#24236] opened 2018-04-14 23:31 UTC
Impacted versions: 10.0

Steps to reproduce:

- Open a web browser
- Type the URL of your blog with URL escaped value for date_begin like: 
"https://www.example.com/en_US/blog/our-blog-1/tag/foo-2,bar-3,odoo-12?date_end=2017-08-01+00%3A00%3A00&date_begin=2017-07-01+00%3A00%3A00"

Current behavior:
Odoo log file show an error like below

> INFO xyz odoo.sql_db: bad query: SELECT "blog_post".id FROM "blog_post" WHERE (((((("blog_post"."active" = true)  AND  ("blog_post"."id" in (SELECT "blog_post_id" FROM "blog_post_blog_tag_rel" WHERE "blog_tag_id" IN (1, 12, 13, 16, 17, 19))))  AND  ("blog_post"."blog_id" = 1))  AND  ("blog_post"."post_date" >= '2017-07-01%2000:00:00'))  AND  ("blog_post"."post_date" <= '2017-08-01%2000:00:00'))  AND  ("blog_post"."post_date" <= '2018-04-14 23:28:04')) AND ("blog_post"."website_published" = true) ORDER BY "blog_post"."post_date" DESC 
> 2018-04-14 23:28:04,592 19026 ERROR xyz odoo.addons.website.models.ir_http: 500 Internal Server Error:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/odoo/addons/website/models/ir_http.py", line 273, in _handle_exception
>     response = super(Http, cls)._handle_exception(exception)
>   File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
>     return request._handle_exception(exception)
>   File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 774, in _handle_exception
>     return super(HttpRequest, self)._handle_exception(exception)
>   File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
>     result = request.dispatch()
>   File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 833, in dispatch
>     r = self._call_function(**self.params)
>   File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 333, in _call_function
>     return checked_call(self.db, *args, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 101, in wrapper
>     return f(dbname, *args, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 326, in checked_call
>     result = self.endpoint(*a, **kw)
>   File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 941, in __call__
>     return self.method(*args, **kw)
>   File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 506, in response_wrap
>     response = f(*args, **kw)
>   File "/usr/lib/python2.7/dist-packages/odoo/addons/website_blog/controllers/main.py", line 133, in blog
>     blog_posts = BlogPost.search(domain, order="post_date desc")
>   File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 1516, in search
>     res = self._search(args, offset=offset, limit=limit, order=order, count=count)
>   File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 4252, in _search
>     self._cr.execute(query_str, where_clause_params)
>   File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 154, in wrapper
>     return f(self, *args, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 231, in execute
>     res = self._obj.execute(query, params)
> DataError: date/time field value out of range: "2017-07-01%2000:00:00"
> LINE 1: ..."blog_id" = 1))  AND  ("blog_post"."post_date" >= '2017-07-0...
>                                                              ^
> 

Expected behavior:

Odoo should convert the date range in prope datetime format, probably using a function like urllib.unquote_plus

**Comment by JKE-be** [comment] 2018-04-23 08:44
I cannot reproduce your issue.
https://youtu.be/EHVQXhAs1yc

Please give more info.

**Comment by Yenthe666** [comment] 2018-05-22 14:27
Hi there,

As there has been no feedback in a month I'm closing this issue.
If you can still reproduce it then please do add more information and details and we'll look into it again.

Regards,
Yenthe

**Closed by Yenthe666** 2018-05-22 14:27 UTC
Labels: 10.0, Need information, Website
