### ISSUE TITLE
Error when creating new point of sales

### ISSUE THREAD

**Issue by GustavoSchuler** [odoo/odoo#19661] opened 2017-09-22 19:21 UTC
Impacted versions: last published

Steps to reproduce: 

Current behavior:

Erro:
Odoo Server Error
```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-15/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/saas-15/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/saas-15/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-15/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-15/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/saas-15/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/saas-15/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/saas-15/addons/web/controllers/main.py", line 894, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/saas-15/addons/web/controllers/main.py", line 886, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/saas-15/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/home/odoo/src/odoo/saas-15/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-15/addons/point_of_sale/models/pos_config.py", line 219, in create
    'name': _('POS Order %s') % values['name'],
TypeError: not all arguments converted during string formatting
```
Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment] 2017-10-02 08:00
Hi @GustavoSchuler,

Thank you for your report.
Did you reproduce this on an official runbot (runbot.odoo.com)? How did you trigger it? Are you talking about the mast version of Odoo? I was able to create a new point of sale without any issues:
![image](https://user-images.githubusercontent.com/6352350/31068503-91979a94-a758-11e7-9340-e7a2575a26c5.png)

Regards,
Yenthe

**Comment by thomasesr** [comment] 2017-11-01 17:36
Having issues With Version 11 of Odoo. with latest version as of 11/01/2017. When creating or trying to edit PoS, I get the following error:

`Erro:
Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 920, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 912, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\point_of_sale\models\pos_config.py", line 335, in create
    'name': _('POS Order %s') % values['name'],
TypeError: not all arguments converted during string formatting`

I really need this working asap.

**Comment by Yenthe666** [comment] 2017-11-02 07:32
@GustavoSchuler,

Again. Did you reproduce this on an official runbot (runbot.odoo.com)? How did you trigger it? 
It works fine on the latest Odoo 11 (from today).

**Comment by thomasesr** [comment] 2017-11-02 13:31
To reproduce this error on linux and windows new installs from scratch, new database created installed the PoS module and tried to create a new module gives me this error from several builds ago. Freshly installed postgresql service rolling back to fresh install of centos minimal and trying again, tried on latest fedora, on windows server 2008 r2 and the same issue occurs. If there is something wrong that I'm doing while installing then there is no documentation about it.

**Comment by thomasesr** [comment] 2017-11-02 14:28
I've found out how the bugs presents itself. If you go in Manage Databases and create a new database in a language and country other then English USA (I was trying with Portuguese/Brazil), then the error always presents itself. But If I create a new database in English USA, then there is no error at all, works just fine, if I then install Portuguese as a language and try to create a new PoS then the error apears again. But I can alter just fine. So I have to alter the language to English to create and then back again to Portuguese.

**Comment by Yenthe666** [comment] 2017-11-02 15:57
@thomasesr it works fine when having multiple languages installed and being in any language too... For example in Spanish:
![image](https://user-images.githubusercontent.com/6352350/32336153-cd42ce0c-bfee-11e7-96bc-24b35774a929.png)
I'll try a new install with a base language and country in spain soon.

**Comment by thomasesr** [comment] 2017-11-02 16:20
Try the latest build of odoo 11 and the base language Portuguese (BR) Brazil. It seems to have the issue there when creating PoS. Otherwise I'll have one user in english just to do that while the rest I'll maintain in Portuguese.

**Comment by Yenthe666** [comment] 2017-11-03 08:06
@thomasesr I've just tried this on a fresh Odoo 11 with the language Portuguese and the country on Brazil. It works without any problems in Portuguese and English, both with the country in Brazil and anywhere else. Can you please find a way to reproduce this on an official Odoo instance (runbot.odoo.com) or a movie of how you do this? Are you absolutely sure that you're on the latest Odoo 11 codebase? One of us is missing something 😉

**Comment by kaframa** [comment] 2017-11-21 07:02
Hi, I also have exactly the same problem. and when I put English language there if I can create the new point of sale.

**Comment by profjefferson** [comment] 2017-12-26 19:37
There is a Bug when using de Portuguese language, the error really occur, but when i change to English i can create point of sale.

**Comment by zodiacfireworks** [comment] 2018-01-22 20:23
I have the same issue in Community Version 12.0alpha1 downloaded yesterday

![image](https://user-images.githubusercontent.com/4976355/35242571-f1053dec-ff87-11e7-8c47-8d93944ccc68.png)

**Comment by Yenthe666** [comment] 2018-01-23 07:14
@zodiacfireworks 12.0alpha1 is the master version and is under construction at all times. Don't ever use the master version / 12.0 alpha in production.

**Comment by abondis** [comment] 2018-03-13 18:47
Hi, I got a similar issue.

It seems the fr_CA.po translates `POS Order %` to `Commande` (without the `%`) making the creation fail since `_('POS Order %s') % values['name']` will not work.

fr.po has the right translation `msgstr "Commande du PdV %s"`

**Comment by mart-e** [comment] 2018-03-22 10:14
The remaining errors should be fixed at a8230853e89

**Closed** 2018-03-22 10:14 UTC
Labels: Internationalization, Need information

**Comment by sagardevlakhe** [comment] 2018-07-21 03:01
i also got this type of error. during Sales > Sales Order > Delivery > Validate Delivery 


![image](https://user-images.githubusercontent.com/41436143/43031470-54156bba-8cc2-11e8-98e6-517fca7d45d6.png)

**Comment by mart-e** [comment] 2018-07-23 07:09
@sagardevlakhe please open a new issue and and copy the _full_ error
