### ISSUE TITLE
I got blank page with odoo logo only / odoo 10

### ISSUE THREAD

**Issue by ahmedsliman** [odoo/odoo#23230] opened 2018-02-21 11:58 UTC
Impacted versions:
10.0

Current behavior:
I got blank page with Odoo logo only on the admin dashboard

Expected behavior:
To display the admin menu and screens details

Video/Screenshot link (optional):
http://prntscr.com/ihrsqv

**Comment by Yenthe666** [comment] 2018-02-22 14:45
Hi there,

Duplicate of https://github.com/odoo/odoo/issues/19627 and probably others.
Closing this one in favour of the other.

**Closed by Yenthe666** 2018-02-22 14:45 UTC
