### ISSUE TITLE
[10.0] CSS does not load in autostart odoo daemon script. odoo.define is not a function error in browser console.

### ISSUE THREAD

**Issue by mikeross6233m** [odoo/odoo#15960] opened 2017-03-21 08:09 UTC
Impacted versions:
10.0

Steps to reproduce:
Added a script to make odoo autostart on ubuntu startup.

`#!/bin/sh
### BEGIN INIT INFO
# Provides: odoo-server
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Should-Start: $network
# Should-Stop: $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Enterprise Business Applications
# Description: ODOO Business Applications
### END INIT INFO
PATH=/bin:/sbin:/usr/sbin:/usr/bin:/usr/local/bin
DAEMON=/opt/odoo10/odoo-bin
NAME=odoo-server
DESC=odoo-server

# Specify the user name (Default: odoo).
USER=odoo

# Specify an alternate config file (Default: /etc/openerp-server.conf).
CONFIGFILE="/opt/odoo10/odoo-server.conf"

# pidfile
PIDFILE=/var/run/${NAME}.pid

# Additional options that are passed to the Daemon.
DAEMON_OPTS="-c $CONFIGFILE"
[ -x $DAEMON ] || exit 0
[ -f $CONFIGFILE ] || exit 0
checkpid() {
[ -f $PIDFILE ] || return 1
pid=`cat $PIDFILE`
[ -d /proc/$pid ] && return 0
return 1
}

case "${1}" in
start)
echo -n "Starting ${DESC}: "
start-stop-daemon --start --quiet --pidfile $PIDFILE --chuid $USER --background --make-pidfile --exec $DAEMON -- $DAEMON_OPTS
echo "${NAME}."
;;
stop)
echo -n "Stopping ${DESC}: "
start-stop-daemon --stop --quiet --pidfile $PIDFILE --oknodo
echo "${NAME}."
;;

restart|force-reload)
echo -n "Restarting ${DESC}: "
start-stop-daemon --stop --quiet --pidfile $PIDFILE --oknodo
sleep 1
start-stop-daemon --start --quiet --pidfile $PIDFILE --chuid $USER --background --make-pidfile --exec $DAEMON -- $DAEMON_OPTS
echo "${NAME}."
;;
*)
N=/etc/init.d/$NAME
echo "Usage: $NAME {start|stop|restart|force-reload}" >&2
exit 1
;;

esac
exit 0`

Current behavior:

On startup, if the browser cache is cleared. The CSS does not load on the login page as well as on the main odoo dashboard page. 
After checking the console in browser(by pressing Inspect or F12). The following error appears.
"web:49 Uncaught TypeError: odoo.define is not a function at web:49"

Normal manual odoo start by terminal works good.

Tried installing 
sudo npm install -g less-plugin-clean-css

did not work for me.

Seems like same problem as this page.
https://github.com/odoo/odoo/issues/13808

Expected behavior:

The CSS and JS should load normally without any issue on startup.

Video/Screenshot link (optional):

**Comment by mikeross6233m** [comment] 2017-03-24 06:47
Very strange thing happened with Odoo.

I just ran another source code of Odoo only once and then just restarted the ubuntu.

After suddenly the above issue was resolved without changing anything. 

I still can't find how did that happened.

**Comment by Yenthe666** [comment] 2017-03-27 07:20
Hi @mikeross6233m,

Thanks for your report.
I'm closing it since you say you cannot reproduce it yourself anymore.
If you however find how you did it or on how to reproduce it just respond here and I'll reopen it.

Regards,
Yenthe

**Closed** 2017-03-27 07:20 UTC

**Comment by mikeross6233m** [comment] 2017-03-27 09:56
Sorry but the issue was not completely resolved. I had few issues with the PDF report generation. The CSS and the report formatting was not correct.
I also tried setting web.base.url=http://0.0.0.0:8069, web.base.url.freeze=True and report.url=http://0.0.0.0:8069
Didn't work for me.

So I created a new database and everything was working fine.
