### ISSUE TITLE
website module odoo 13

### ISSUE THREAD

**Issue by AbdelrahmanHamdy1996** [odoo/odoo#47548] opened 2020-03-12 19:46 UTC
wrong behaviour leads to bad gateway 502 in website module 
![Screenshot from 2020-03-12 21-40-38](https://user-images.githubusercontent.com/46800696/76560889-d0e35a00-64aa-11ea-9e99-0d6aba56bfd3.png)
![Screenshot from 2020-03-12 21-41-01](https://user-images.githubusercontent.com/46800696/76560900-d9d42b80-64aa-11ea-83e5-26c017efe058.png)

**Comment by pedrobaeza** [comment] 2020-03-12 19:54
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by AbdelrahmanHamdy1996** [comment] 2020-03-12 20:09
this issues not appear on runbot

**Comment by AbdelrahmanHamdy1996** [comment] 2020-03-12 20:10
i will clean my DB and try again

**Comment by pedrobaeza** [comment] 2020-03-12 20:13
OK, let us know if you have reproduceable steps.

**Closed by pedrobaeza** 2020-03-12 20:13 UTC
Labels: Need information
