### ISSUE TITLE
Weird error -- Invalid view definition , Field does not exit

### ISSUE THREAD

**Issue by ravik** [odoo/odoo#15753] opened 2017-03-08 08:03 UTC
I created a custom module for odoo 9.0
There is no problem adding new fields
I check through Settings --> Database Structure -->Fields
and I can find the custom fields added when I first installed the custom modules

 I always restart the odoo server.
When I reference the new fields in my custom view and try to 'upgrade' through the admin interface, I get an error that
Field 'xxxxx' does not exist

**Comment by mart-e** [comment] 2017-03-09 13:33
Hello,

Adding fields on a model in a module is a very basic feature used in dozens of standard modules. If it did not work, we would probably have noticed.
The issue is most likely in your custom module (e.g. adding on the wrong model, wrong declaration,...) and we would need the code for that.

However github is to report issues on the standard Odoo code and framwork, not for the custom modules.
Closing the issue has no bug on Odoo has been shown.

If you can show us with a simple example that there is a bug in Odoo field addition (there may but in some very specific conditions you do not explain), then I can reopen this issue

**Closed by mart-e** 2017-03-09 13:33 UTC

**Comment by ravik** [comment] 2017-03-12 04:47
Hi,

Thanks for your comment. May be my coding might be wrong.
However below is my code.

**__init__.py**

from . import status_project_timesheet



**status_project_timesheet.py**

from openerp import api,fields,models
class task_status(models.Model):
    _inherit = "project.task"
    status_name1=fields.Char(string='Status Name')

**view file**
<?xml version="1.0" encoding="utf-8"?>
<odoo>
    <record id="view_task_form2_inherited_stat" model="ir.ui.view">
        <field name="name">project.task.form2.inherited.stat</field>
        <field name="model">project.task</field>
        <field name="inherit_id" ref="project_timesheet.view_task_form2_inherited"/>
        <field name="arch" type="xml">
            <field name="account_id" position="before">
                <field name="status_name1"/>
            </field>
        </field>
    </record>
</odoo>
