### ISSUE TITLE
UI Issue in Search List Pop-up

### ISSUE THREAD

**Issue by BuddhimaN** [odoo/odoo#8125] opened 2015-08-18 12:31 UTC
Impacted versions:

 - 8.0

Steps to reproduce:

 1. Log in as Admin
 2. Go to Settings
 3. Click on Groups menu item under Users
 4. Select any Group from List view
 5. Click Edit
 6. Click "Add an item" under Users Tab
 7. Click down arrow in the search box

Current behavior:

 - Advanced options overlap with the Search box. 
![screenshot from 2015-08-18 17 43 27](https://cloud.githubusercontent.com/assets/13850932/9329816/75db93b2-45d2-11e5-9fef-0b2b43a027a6.png)

Expected behavior:

- Advanced options should not overlap with Search box

Note :
This issue available in every Search List pop-up and sometimes it blocks default filters in the search box from removing.

**Comment by flotho** [comment] 2015-08-20 17:37
Hi,

Duplicate of #3224

**Comment by Yenthe666** [comment] 2016-10-03 10:26
Hi @BuddhimaN,

Thanks a lot for your report! In the mean time the bug has been fixed and is no longer present in the latest version of Odoo 8:
![image](https://cloud.githubusercontent.com/assets/6352350/19034585/9302db72-8964-11e6-99d7-ce62867d4a9d.png)
I'm closing this issue since it has already been fixed.

Regards,
Yenthe

**Closed by Yenthe666** 2016-10-03 10:26 UTC
