### ISSUE TITLE
Multi Currency in Manual Journal Entry 

### ISSUE THREAD

**Issue by iamharikrishnank** [odoo/odoo#63606] opened 2020-12-19 05:00 UTC
Impacted versions: V13 Community
Problem:
Suppose I have AED as a company currency and I want to create a journal entry in EURO &USD.The Issue is that  Its not calculating amount in the field amount in currency.Please solve this issue ASAP

**Comment by pedrobaeza** [comment] 2020-12-19 08:52
Multi-currency accounting is working in Odoo, so you should be doing some steps in an incorrect way for not getting it. Please refer to manuals for seeing how to do it and ask on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).

Closing this by the reason above. If you provide whole detailed steps for reproducing a problem, then this can be considered an issue.

**Closed by pedrobaeza** 2020-12-19 08:52 UTC
