### ISSUE TITLE
 this._summernoteManager.saveCroppedImages is not a function

### ISSUE THREAD

**Issue by instechMX** [odoo/odoo#47623] opened 2020-03-13 16:44 UTC
Impacted versions:
Odoo 12.0-20200312
Steps to reproduce:
Try to modify payment methods in web.
Current behavior:
Send this error 
Uncaught TypeError: this._summernoteManager.saveCroppedImages is not a function
https://localhost/web/content/1169-0a2899a/web.assets_backend.js:2426
Rastreo de error:
TypeError: this._summernoteManager.saveCroppedImages is not a function
    at Class.commitChanges (https://localhost/web/content/1169-0a2899a/web.assets_backend.js:2426:74)
    at Class.prototype.<computed> [as commitChanges] (https://localhost/web/content/971-f512b0e/web.assets_common.js:3538:488)
    at https://localhost/web/content/1169-0a2899a/web.assets_backend.js:1574:235
    at Function._.map._.collect (https://localhost/web/content/971-f512b0e/web.assets_common.js:13:270)
    at Class.commitChanges (https://localhost/web/content/1169-0a2899a/web.assets_backend.js:1574:169)
    at https://localhost/web/content/1169-0a2899a/web.assets_backend.js:1561:1093
    at https://localhost/web/content/971-f512b0e/web.assets_common.js:802:681
    at fire (https://localhost/web/content/971-f512b0e/web.assets_common.js:796:299)
    at Object.add [as done] (https://localhost/web/content/971-f512b0e/web.assets_common.js:797:467)
    at Array.<anonymous> (https://localhost/web/content/971-f512b0e/web.assets_common.js:802:649)
Expected behavior:
That i cloud modify the payment methods
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2020-03-13 17:04
AFAIK, this was already solved. Have you tried with an updated version of Odoo code?

**Comment by instechMX** [comment] 2020-03-13 17:22
Hi, I'm using the night build (https://nightly.odoo.com/) and i already upgraded to the latest version did you know if I had to installed directly from the GitHub repo or something?

**Comment by pedrobaeza** [comment] 2020-03-13 17:25
Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

**Comment by gacalixto** [comment] 2020-03-13 18:58
I'm having the same issue!
Whenever i try to create a new record on my custom module, it shows the same error:
```
Uncaught TypeError: this._summernoteManager.saveCroppedImages is not a function
http://odoo.meucpd.com.br:8069/web/content/1355-29fc60c/web.assets_backend.js:2427
Traceback:
TypeError: this._summernoteManager.saveCroppedImages is not a function
    at Class.commitChanges (http://odoo.meucpd.com.br:8069/web/content/1355-29fc60c/web.assets_backend.js:2427:74)
    at Class.prototype.<computed> [as commitChanges] (http://odoo.meucpd.com.br:8069/web/content/356-15f025e/web.assets_common.js:3538:488)
    at http://odoo.meucpd.com.br:8069/web/content/1355-29fc60c/web.assets_backend.js:1574:235
    at Function._.map._.collect (http://odoo.meucpd.com.br:8069/web/content/356-15f025e/web.assets_common.js:13:270)
    at Class.commitChanges (http://odoo.meucpd.com.br:8069/web/content/1355-29fc60c/web.assets_backend.js:1574:169)
    at http://odoo.meucpd.com.br:8069/web/content/1355-29fc60c/web.assets_backend.js:1561:1093
    at http://odoo.meucpd.com.br:8069/web/content/356-15f025e/web.assets_common.js:802:681
    at fire (http://odoo.meucpd.com.br:8069/web/content/356-15f025e/web.assets_common.js:796:299)
    at Object.add [as done] (http://odoo.meucpd.com.br:8069/web/content/356-15f025e/web.assets_common.js:797:467)
    at Array.<anonymous> (http://odoo.meucpd.com.br:8069/web/content/356-15f025e/web.assets_common.js:802:649)
```


after removing a html field, the error stops.
Odoo v12

**Comment by instechMX** [comment] 2020-03-13 19:16
The only way to reproduce the error it's uploading my database to runbot. Is this is secure?. I feel not confident about doing it. I think the error it's in my database that it's probably created before the update version that solves this issue.

**Comment by instechMX** [comment] 2020-03-13 19:17
> I'm having the same issue!
> Whenever i try to create a new record on my custom module, it shows the same error:
> 
> ```
> Uncaught TypeError: this._summernoteManager.saveCroppedImages is not a function
> http://odoo.meucpd.com.br:8069/web/content/1355-29fc60c/web.assets_backend.js:2427
> Traceback:
> TypeError: this._summernoteManager.saveCroppedImages is not a function
>     at Class.commitChanges (http://odoo.meucpd.com.br:8069/web/content/1355-29fc60c/web.assets_backend.js:2427:74)
>     at Class.prototype.<computed> [as commitChanges] (http://odoo.meucpd.com.br:8069/web/content/356-15f025e/web.assets_common.js:3538:488)
>     at http://odoo.meucpd.com.br:8069/web/content/1355-29fc60c/web.assets_backend.js:1574:235
>     at Function._.map._.collect (http://odoo.meucpd.com.br:8069/web/content/356-15f025e/web.assets_common.js:13:270)
>     at Class.commitChanges (http://odoo.meucpd.com.br:8069/web/content/1355-29fc60c/web.assets_backend.js:1574:169)
>     at http://odoo.meucpd.com.br:8069/web/content/1355-29fc60c/web.assets_backend.js:1561:1093
>     at http://odoo.meucpd.com.br:8069/web/content/356-15f025e/web.assets_common.js:802:681
>     at fire (http://odoo.meucpd.com.br:8069/web/content/356-15f025e/web.assets_common.js:796:299)
>     at Object.add [as done] (http://odoo.meucpd.com.br:8069/web/content/356-15f025e/web.assets_common.js:797:467)
>     at Array.<anonymous> (http://odoo.meucpd.com.br:8069/web/content/356-15f025e/web.assets_common.js:802:649)
> ```
> 
> after removing a html field, the error stops.
> Odoo v12

How and where did you remove that field?

**Comment by pedrobaeza** [comment] 2020-03-13 19:24
Then you should try to update your modules. Any way, if it's not reproduceable in runbot, I'm afraid we can't do much for solving it and it's not the goal of this issue tracker, so closing the issue. If you find a way to reproduce or give more hints about the problem, it can be reopened.

**Closed by pedrobaeza** 2020-03-13 19:24 UTC
Labels: Need information

**Comment by blackwaremayank** [comment] 2020-03-20 03:57
Hi @pedrobaeza 

I'm also facing this same issue. And i confirm that i'm using the latest code as shown in below snapshot.
![image](https://user-images.githubusercontent.com/48239869/77134034-59559200-6a8b-11ea-8af8-99622d87e289.png)

Please refer below snapshot, you'll find assets from **web_editor** module didn't get updated. I have updated the **base** module and also tried **debug=assets** after taking latest Odoo update.

![image](https://user-images.githubusercontent.com/48239869/77134261-324b9000-6a8c-11ea-929e-58ec5c020f81.png)

Also i'm facing this assets update issue in both Odoo V12 and Odoo V13.

Thanks

**Comment by romaindutartre** [comment] 2020-03-24 03:13
I had the same problem but with the wysiwyg module (`this.wysiwyg.save Cropped Images is not a function`). I had restored from a database including filestore and I suppose some of the assets were outdated because a **Regenerate Bundle Assets** solved the problem, let me know if that works for you.

**Comment by instechMX** [comment] 2020-03-24 06:07
> I had the same problem but with the wysiwyg module (`this.wysiwyg.save Cropped Images is not a function`). I had restored from a database including filestore and I suppose some of the assets were outdated because a **Regenerate Bundle Assets** solved the problem, let me know if that works for you.

Omg thank, iu. I renovate the assets and restart the service odoo and now everything its working.
How to regenerate assets from the GUI
If are on Odoo 12.0+ then regenerating asset bundles is simple from the GUI (assuming that you can access the GUI.)
Enable developer mode
Open the debug menu from the toolbar
Select Regenerate Asset Bundles
This runs a JS function called regenerateAssets .
restart odoo

**Comment by Team-IT-Conection** [comment] 2020-03-25 22:16
I hade the same problem
I tried Regenerate Bundle Assets did not solve the problem

**Comment by Team-IT-Conection** [comment] 2020-03-25 22:22
i repeat the same action and it's ok
the problem was solved
thank you !

**Comment by instechMX** [comment] 2020-03-26 02:05
> i repeat the same action and it's ok
> the problem was solved
> thank you !

Nice!,

**Comment by Kilhog** [comment] 2020-03-26 12:43
I confirm there is something wrong with updating `web_editor.assets_wysiwyg.js` after a `-u all`, and "Regenerate Bundle Assets" is not always working

**Comment by treviser** [comment] 2020-04-13 05:48
I have the same problem with Odoo 13.0 latest nightly build. It only happens, when I try to create or edit a user. Everything else works. No error in the log, but in the user interface:

`Error:


Traceback:
TypeError: this.wysiwyg.saveCroppedImages is not a function
    at Class.commitChanges (http://xxx.xxx.xxx.xxx:8069/web/content/1507-1c31299/web.assets_backend.js:2587:55)
    at Class.prototype.<computed> (http://xxx.xxx.xxx.xxx:8069/web/content/523-082e4d9/web.assets_common.js:3860:488)
    at Class.commitChanges (http://xxx.xxx.xxx.xxx:8069/web/content/1507-1c31299/web.assets_backend.js:2641:13)
    at Class.commitChanges (http://xxx.xxx.xxx.xxx:8069/web/content/523-082e4d9/web.assets_common.js:3863:371)
    at http://xxx.xxx.xxx.xxx:8069/web/content/1507-1c31299/web.assets_backend.js:1388:235
    at Function._.map._.collect (http://xxx.xxx.xxx.xxx:8069/web/content/523-082e4d9/web.assets_common.js:109:270)
    at Class.commitChanges (http://xxx.xxx.xxx.xxx:8069/web/content/1507-1c31299/web.assets_backend.js:1388:169)
    at http://xxx.xxx.xxx.xxx:8069/web/content/1507-1c31299/web.assets_backend.js:1371:355`

**Comment by treviser** [comment] 2020-04-13 06:16
Regenerating the assets (with some fiddling) did solve the problem.

**Comment by treviser** [comment] 2020-04-13 08:27
I don't know where to document it, but it maybe helpful for others.
When you have installed the Openworx Backend Theme, this gets obfuscated, the error message ist empty and the tracebook looks like this:

`Traceback:
commitChanges@http://52.59.193.234:8069/web/content/1334-17865a4/web.assets_backend.js:2587:55
OdooClass.extend/</prototype[name]</<@http://52.59.193.234:8069/web/content/523-082e4d9/web.assets_common.js:3860:488
commitChanges@http://52.59.193.234:8069/web/content/1334-17865a4/web.assets_backend.js:2641:13
OdooClass.extend/Class.include/</prototype[name]</<@http://52.59.193.234:8069/web/content/523-082e4d9/web.assets_common.js:3863:371
commitChanges/defs<@http://52.59.193.234:8069/web/content/1334-17865a4/web.assets_backend.js:1388:235
_.collect@http://52.59.193.234:8069/web/content/523-082e4d9/web.assets_common.js:109:270
commitChanges@http://52.59.193.234:8069/web/content/1334-17865a4/web.assets_backend.js:1388:169
saveRecord/unlockedMutex<@http://52.59.193.234:8069/web/content/1334-17865a4/web.assets_backend.js:1371:355`

This is really annoying.

**Comment by Yenthe666** [comment] 2020-04-13 08:49
@mgielissen this might be interesting for you. @treviser why don't you report it at https://github.com/Openworx/backend_theme? It looks like an issue with the theme

**Comment by mgielissen** [comment] 2020-04-13 12:41
A client had the same error with Odoo 12EE last week

**Comment by maytemontano** [comment] 2020-04-15 19:48
I had the same problem with Odoo 12.0+e-20200325  and Regenerate Bundle Assets did solved the problem, thanks!

**Comment by WaelSan** [comment] 2020-05-03 11:36
@maytemontano try to regenerat Assets, I resolved this problem by this method

**Comment by Rublood** [comment] 2020-05-06 13:17
Same issue here but regenerate assets not work all times

**Comment by usermadhan** [comment] 2020-06-16 11:01
Once modules are upgraded (Odoo 13.0) then unable to edit or create the users. Getting the error in browser console. 

"TypeError: this.wysiwyg.saveCroppedImages is not a function".

Regenerate the assets bundle through GUI and restart the container fixed the issue.
