### ISSUE TITLE
[12.0] account: Group accountant can not create cash / bank statement

### ISSUE THREAD

**Issue by abdallamhafeez** [odoo/odoo#33314] opened 2019-05-12 16:00 UTC
Impacted versions:
12.0

Steps to reproduce:
1- Login with user have group "Accountant" only
1- Open Accounting dashboard
2- Click on "New Transaction" for journal "Cash" or "Bank"
3- Save transaction

Current behavior:
Appear access error for "account.journal"

Expected behavior:
 The accountant can save cash/bank statement
Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/13385546/57584796-b97cbe80-74df-11e9-93f1-aced3a5559b7.png)

**Comment by pedrobaeza** [comment] 2019-05-12 20:16
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by abdallamhafeez** [comment] 2019-05-12 21:19
I tested it in runbot (http://518105-12-0-754ba4.runbot17.odoo.com) with user "account" and password "123456789" and appear the same issue. I try to add access to write for "account.journal" to group "Accountant" and it works.

**Comment by gdgellatly** [comment] 2019-05-13 04:39
I had a bit of this lately. I think it's to do with first time a statement is created it writes details to journal like import method, bank account, default debit credit.

**Comment by Yenthe666** [comment] 2019-07-31 14:40
@abdallamhafeez have you been able to resolve this in the meanwhile or is this issue still present?

**Comment by abdallamhafeez** [comment] 2019-08-01 03:25
@Yenthe666 It still appears in latest runbot

**Comment by C3POdoo** [comment] 2023-03-30 11:50
Dear @abdallamhafeez,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._

**Closed by C3POdoo** 2023-03-30 11:50 UTC
Labels: Accounting, 12.0
