### ISSUE TITLE
Uninstall module odoo11

### ISSUE THREAD

**Issue by vsnetvn** [odoo/odoo#28454] opened 2018-11-07 04:35 UTC
Impacted versions: Odoo11

I customize add field type Char on model **ir.module.module** install success  but when uninstall this module error field does not exits
![w](https://user-images.githubusercontent.com/5435030/48110855-35702280-e281-11e8-8b5e-408e39ae1db5.png)
![q](https://user-images.githubusercontent.com/5435030/48110856-35702280-e281-11e8-91dc-ade895f7be79.png)

Please see the problem

**Comment by pedrobaeza** [comment] 2018-11-07 09:05
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code or you have made something forbidden. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2018-11-07 09:05 UTC
