### ISSUE TITLE
odoo session expired --> dynamic products in website

### ISSUE THREAD

**Issue by sezginzerdelci** [odoo/odoo#66545] opened 2021-02-19 14:56 UTC
hello all, 

i'm using odoo version 14. When I use Dynamic Product content on the website, I get session expired error if I am not logged in.

Can I find out what is the reason for this?

**Comment by pedrobaeza** [comment] 2021-02-19 14:57
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by sezginzerdelci** [comment] 2021-02-19 21:52
hi,
No problem appears in the runbot infrastructure. I haven't installed any custom modules. my error image is below.Is there an update? If there is an update, how can I change it?
![104093506-9ba6c480-5293-11eb-9209-c2c2a20e8c1d](https://user-images.githubusercontent.com/7361835/108565475-cb76cc80-7315-11eb-9083-e7195acf2c49.png)

**Comment by pedrobaeza** [comment] 2021-02-19 22:31
I'm afraid then that is a deployment problem. Please check install guide.

Closing as no reproducible in runbot.

**Closed by pedrobaeza** 2021-02-19 22:31 UTC
Labels: 14.0, Need information

**Comment by pbanswer** [comment] 2022-05-05 13:51
Hi. It seems that i have the similar problem. When i create dynamic snippet, it works correctly only if you log in like an administrator, or user account. Snippet uses data from the odoo model(rpс request). So if you didn't log in and try to go on the website like a public user from another browser, odoo displays a message, something like

"Odoo session is expired. The current page is about to be refreshed."

Like on the previous message screenshot. If tap 'ok' on the warning - page starting refresh,  if close - snippet uses default content from template(not data from database).

I didn't find any solution , which works for me in the documentation or on the forums.
