### ISSUE TITLE
[PROJECT] Upgrade 9.0c.20160105 on 9.0c20151220 - Module Project display Error

### ISSUE THREAD

**Issue by klepallec** [odoo/odoo#10305] opened 2016-01-05 13:34 UTC
Hello,

Recently, I upgrade the odoo from 9.0c20151220 to 9.0c.20160105. Now I have these error when i click on module project : 

Configuration  0 Tableau de bord Recherche Tâches Reports Tâches Flux cumulé Configuration Settings Stages Projets Fourni par Odoo Projets x Ouvert Créer Filtres Regrouper par Favoris 1-2 / 2 Communication Plus 3 Tasks Système d'Information Plus 10 Tasks × Odoo Odoo Server Error Traceback (most recent call last): File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 643, in _handle_exception return super(JsonRequest, self)._handle_exception(exception) File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 680, in dispatch result = self._call_function(**self.params) File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 316, in _call_function return checked_call(self.db, *args, **kwargs) File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 118, in wrapper return f(dbname, *args, **kwargs) File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 309, in checked_call result = self.endpoint(*a, **kw) File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 959, in __call__ return self.method(*args, **kw) File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 509, in response_wrap response = f(*args, **kw) File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 892, in call_kw return self._call_kw(model, method, args, kwargs) File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 884, in _call_kw return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs) File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 238, in wrapper return old_api(self, *args, **kwargs) File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 342, in old_api result = method(recs, *args, **kwargs) File "/usr/lib/python2.7/dist-packages/openerp/addons/web_planner/models/web_planner.py", line 45, in render return self.env['ir.ui.view'].browse(template_id).render(values=values) File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 236, in wrapper return new_api(self, *args, **kwargs) File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 562, in new_api result = method(self._model, cr, uid, self.ids, *args, **old_kwargs) File "/usr/lib/python2.7/dist-packages/openerp/addons/web_editor/models/ir_ui_view.py", line 29, in render return super(view, self).render(cr, uid, id_or_xml_id, values=values, engine=engine, context=context) File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 238, in wrapper return old_api(self, *args, **kwargs) File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_ui_view.py", line 1065, in render return self.pool[engine].render(cr, uid, id_or_xml_id, qcontext, loader=loader, context=context) File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 238, in wrapper return old_api(self, *args, **kwargs) File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_qweb.py", line 252, in render element = self.get_template(id_or_xml_id, qwebcontext) File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_qweb.py", line 172, in get_template document = qwebcontext.loader(name) File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_ui_view.py", line 1063, in loader return self.read_template(cr, uid, name, context=context) File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 238, in wrapper return old_api(self, *args, **kwargs) File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_ui_view.py", line 938, in read_template return self._read_template(cr, uid, view_id, context=context) File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 238, in wrapper return old_api(self, *args, **kwargs) File "<string>", line 2, in _read_template File "/usr/lib/python2.7/dist-packages/openerp/tools/cache.py", line 85, in lookup value = d[key] = self.method(*args, **kwargs) File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_ui_view.py", line 923, in _read_template arch = self.read_combined(cr, uid, view_id, fields=['arch'], context=context)['arch'] File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 238, in wrapper return old_api(self, *args, **kwargs) File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_ui_view.py", line 635, in read_combined view_arch = etree.fromstring(view['arch'].encode('utf-8')) File "lxml.etree.pyx", line 3092, in lxml.etree.fromstring (src/lxml/lxml.etree.c:70691) File "parser.pxi", line 1828, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:106689) File "parser.pxi", line 1716, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:105478) File "parser.pxi", line 1086, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:100105) File "parser.pxi", line 580, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:94543) File "parser.pxi", line 690, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:96003) File "parser.pxi", line 620, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:95050) XMLSyntaxError: EntityRef: expecting ';', line 229, column 117

Can you help me please ?

thx

**Comment by Yenthe666** [comment] 2016-05-23 12:44
Hi @klepallec,

Could you try a new update and see if this issue is still present?
It should be fixed by now.

**Comment by klepallec** [comment] 2016-05-27 09:07
Hello,

I resintall Odoo, so i can't test sorry :/

**Comment by Yenthe666** [comment] 2016-05-27 09:08
Hi @klepallec,

No problem. Do you mind me closing this issue?
Since we have no way to reproduce this or find out what was wrong.

Regards,
Yenthe

**Comment by klepallec** [comment] 2016-05-27 09:10
Yes no pb you can please.
thks

**Closed** 2016-05-27 09:13 UTC
