### ISSUE TITLE
[11.0] Error in loading moment.js with locale es_MX

### ISSUE THREAD

**Issue by alan196** [odoo/odoo#22463] opened 2018-01-24 01:57 UTC
Impacted versions:
11.0
Steps to reproduce:
- Create a new database with language es_MX
- Use web/?debug=assets to get the error.

Current behavior:
- White screen.
```
  File "/opt/odoo-11.0/odoo/odoo/tools/misc.py", line 211, in _fileopen
    raise ValueError("Unknown path: %s" % name)
ValueError: Unknown path: /web/static/lib/moment/locale/es-mx.js
```
I look an issue in this file: https://github.com/odoo/odoo/blob/11.0/odoo/tools/misc.py#L201-L211
I explain inside the code in comments.
```python
def _fileopen(path, mode, basedir, pathinfo, basename=None):
    name = os.path.normpath(os.path.normcase(os.path.join(basedir, path)))

    import odoo.modules as addons
    paths = addons.module.ad_paths + [config['root_path']]
    for addons_path in paths:
        addons_path = os.path.normpath(os.path.normcase(addons_path)) + os.sep
        if name.startswith(addons_path):
            break
    else:
# This raise an error because /web/static/lib/moment/locale/es-mx.js does not exist in.
# https://github.com/odoo/odoo/tree/11.0/addons/web/static/lib/moment/locale
        raise ValueError("Unknown path: %s" % name)
```
This method is called in: https://github.com/odoo/odoo/blob/11.0/addons/web/controllers/main.py#L517-L537
I explain inside the code in comments:
```python
@http.route('/web/webclient/locale/<string:lang>', type='http', auth="none")
    def load_locale(self, lang):
        magic_file_finding = [lang.replace("_", '-').lower(), lang.split('_')[0]]
# This make a list:
# magic_file_finding = ['es-mx', 'es']
        for code in magic_file_finding:
        # When you read the first element 'es-mx'
        # it will raise the error explained in the last method.
        # this loop never go to the second element of the list 'es'
        # this element exist https://github.com/odoo/odoo/blob/11.0/addons/web/static/lib/moment/locale/es.js
            try:
                return http.Response(
                    werkzeug.wsgi.wrap_file(
                        request.httprequest.environ,
                        file_open('web/static/lib/moment/locale/%s.js' % code, 'rb')
                    ),
                    content_type='application/javascript; charset=utf-8',
                    headers=[('Cache-Control', 'max-age=36000')],
                    direct_passthrough=True,
                )
            except IOError:
                _logger.debug("No moment locale for code %s", code)

        return request.make_response("", headers=[
            ('Content-Type', 'application/javascript'),
            ('Cache-Control', 'max-age=36000'),
        ])
```

Notes:
- I only get this issue when I start Odoo using init file https://github.com/odoo/odoo/blob/11.0/debian/init
The config file is the following 
```
[options]
addons_path =
    /opt/odoo-11.0/enterprise,
    /opt/odoo-11.0/odoo/addons,
    /opt/odoo-11.0/odoo/odoo/addons,
workers = 9
```
- If I start odoo with `./odoo-bin -c /etc/odoo-server.conf` I don't get this issue.

Expected behavior:
- Load odoo menu.

**Comment by alan196** [comment] 2018-01-24 02:11
Entreprise Ticket 807562

**Comment by rim-odoo** [comment] 2018-02-13 09:24
You should only see 
```
2018-02-13 09:23:41,528 22302 DEBUG 11.0 odoo.addons.web.controllers.main: No moment locale for code es-mx
```
in your logs

**Comment by bariserdogan** [comment] 2018-06-07 06:44
+1
Hello,
I take the same mistake. Home page is not loading.
As I mentioned, I do not have any problem when I run it with the config file:
`python3 ./odoo-bin -c /etc/odoo-server.conf`

**Comment by SalahAdDin** [comment] 2018-06-21 19:49
Same problem here, but with `es_CO`.

**Comment by SalahAdDin** [comment] 2018-06-22 07:12
```bash
2018-06-22 07:10:59,751 15 ERROR rotafilo werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1318, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1292, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1490, in dispatch
    result = ir_http._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/web_editor/models/ir_http.py", line 22, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/http_routing/models/ir_http.py", line 393, in _dispatch
    result = super(IrHttp, cls)._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/utm/models/ir_http.py", line 26, in _dispatch
    response = super(IrHttp, cls)._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_http.py", line 212, in _dispatch
    return cls._handle_exception(e)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_http.py", line 169, in _handle_exception
    return super(Http, cls)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/addons/utm/models/ir_http.py", line 31, in _handle_exception
    response = super(IrHttp, cls)._handle_exception(exc)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_http.py", line 182, in _handle_exception
    return request._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 770, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_http.py", line 208, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 829, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 526, in load_locale
    file_open('web/static/lib/moment/locale/%s.js' % code, 'rb')
  File "/usr/lib/python3/dist-packages/odoo/tools/misc.py", line 193, in file_open
    pathinfo=pathinfo, basename=basename)
  File "/usr/lib/python3/dist-packages/odoo/tools/misc.py", line 211, in _fileopen
    raise ValueError("Unknown path: %s" % name)
ValueError: Unknown path: /web/static/lib/moment/locale/es-co.js
```

**Comment by SalahAdDin** [comment] 2018-06-22 07:20
I haven't this problem in production environment, why?

**Comment by janbec** [comment] 2018-06-22 14:44
I ran into the same error with enUS. Apparently clearing the addons path in odoo-server.conf, restarting the service and restoring the addonspath with another restart helped.

**Comment by SalahAdDin** [comment] 2018-06-22 15:46
@janbec how can i do that within a Docker container.

**Comment by janbec** [comment] 2018-06-22 16:12
@SalahAdDin Well, I'm not sure how the docker would change the way, but for me it is just opening `etc/odoo-server.conf` with nano, clear the addons-path, save, restart service, fill in the path again, save, restart service.
Seems a little strange but worked for me.

**Comment by SalahAdDin** [comment] 2018-06-22 16:52
I will test it again, but, i think it is a non-satisfactory solution for a production environment,

**Comment by janbec** [comment] 2018-06-25 13:35
@SalahAdDin 
I agree. Had the same problem again today and turns out the localization file was actually missing. Check `addons/web/static/lib/moment/locale ` for the file with the unknown path. In my case (local VM) I just renamed `en-ca.js` to `en-us.js` and it worked. In your case, maybe use the correct file.

**Comment by SalahAdDin** [comment] 2018-06-26 06:54
@janbec I did it with `docker`, it does not works, i saw the problem is with a non `OCA` free module. I think it's a module problem.

**Comment by grzekru** [comment] 2018-12-19 23:15
Hello,

Just had the same problem with my Odoo12 installation.
ValueError: Unknown path: /web/static/lib/moment/locale/pl-pl.js 1 0.001 0.016
It was caused by typo in configuration file in addons_path

addons_path = /location/to/addons1,,/location/to/addons2
instead of:
addons_path = /location/to/addons1,/location/to/addons2

**Comment by alan196** [comment] 2018-12-20 10:00
Thanks @grzekru 👍 

I just tested and it works...

I had a coma in the end of the addons_path:

```
addons_path=
    /location/to/addons1,
    /location/to/addons2,
```

After I remove the last coma it just worked.

```
addons_path=
    /location/to/addons1,
    /location/to/addons2
```

**Comment by Yenthe666** [comment] 2018-12-20 10:35
Closing as solved, thanks guys!

**Closed by Yenthe666** 2018-12-20 10:35 UTC
Labels: 11.0, Framework

**Comment by luistriana28** [comment] 2018-12-20 17:21
👍

**Comment by leelapriskila** [comment] 2019-01-11 08:57
Hi Everyone,
I am facing the same issue in Odoo 12 CE
But For Me Missing Locale File Is en-us.js
ValueError: Unknown path: /web/static/lib/moment/locale/en-us.js - - -
How to fix this?
 @alaidin Have you got any solution for this?

Thanks & Regards,
Leelapriskila R

**Comment by alan196** [comment] 2019-01-11 16:10
Hello @leelapriskila 

This issue was related to the definition of addons_path in the conf file of Odoo, if you have a comma `,` at the end of the addons_path or in the middle two commas, it will raise that error.

Just update the configuration file of Odoo and verify that you don't have that issue.

Check my [comment](https://github.com/odoo/odoo/issues/22463#issuecomment-448940947).

I hope this helps

**Comment by leelapriskila** [comment] 2019-01-22 07:45
Hi @alan196

Thanks For Suggestion.In config life there is no comma at the end of addons path but still I am facing that issue.
Any Other Solutions?

Regards,
Leelapriskila

**Comment by lin-ww** [comment] 2020-07-10 09:32
> Hello,
> 
> Just had the same problem with my Odoo12 installation.
> ValueError: Unknown path: /web/static/lib/moment/locale/pl-pl.js 1 0.001 0.016
> It was caused by typo in configuration file in addons_path
> 
> addons_path = /location/to/addons1,,/location/to/addons2
> instead of:
> addons_path = /location/to/addons1,/location/to/addons2

Thanks, i also have an extra comma in the end of the --addons-path... Hahahahaha

**Comment by lin-ww** [comment] 2020-07-10 09:35
https://github.com/odoo/odoo/issues/22463#issuecomment-448782706
I just resolved it by remove the comma in the end of --addons-path, Hahahaha

**Comment by joyanto09** [comment] 2021-03-14 10:40
Yes It's solved to removed the comma in the end of --addons-path,,,, Thanks All
