### ISSUE TITLE
[11,12,13] Public Price list not perfectly display

### ISSUE THREAD

**Issue by ammarofficewla** [odoo/odoo#38122] opened 2019-10-07 16:25 UTC
Impacted versions:
13.0

Steps to reproduce:
Go to website > shop > click on product
1. Change price list (public price list to EUR) 
2. Again Tried to change price list

Current behaviour:
Screen are overlap or website design are not set perfect

Expected behaviour:
Display full name of price list and not changed in website desing.

Video/Screenshot link (optional):

https://drive.google.com/open?id=1DRqpYetkWVMaECk9DZPS3IbVweYWbpeV

**Comment by seb-odoo** [comment] 2019-10-07 18:11
@qsm-odoo do you know if there is an easy fix for this?

Wouldn't it already be present on v12 too?

**Comment by rdeodoo** [comment] 2019-10-10 12:36
That is also in v11.0.
We could fix it there with `dropdown-menu-right` on the `dropdown-menu`.

**Comment by qsm-odoo** [comment] 2019-10-10 13:32
Not sure it is worth an xml change in stable versions though... I'll let you decide @rdeodoo :)

**Comment by rdeodoo** [comment] 2019-10-10 13:35
I would do it as it won't break existing xpath since it is adding a class right?
Worst case they don't update their view and they don't get the fix

**Comment by rdeodoo** [comment] 2021-06-03 17:09
The google drive link that was showing the issue is dead.
I don't remember what it was about, but I don't see anything bad on 12 and 13.
Closing it, we can reopen or reply if someone remember the issue and it is still there.

**Closed by rdeodoo** 2021-06-03 17:09 UTC
Labels: 11.0, 12.0, 13.0, Website
