### ISSUE TITLE
odoo12: un checked "phone formatting" yet still my +XX is being removed

### ISSUE THREAD

**Issue by f1-outsourcing** [odoo/odoo#62227] opened 2020-11-24 09:45 UTC
please stop closing issues, when you do not understand it, ask then first some developer.
https://github.com/odoo/odoo/issues/62209

phone formatting still active after turning it off with crm ->contacts -> un checked "phone formatting"

`Then this is the expected behavior: `
Is rediculous. 

This is what is written: 
```
Phone Formatting
Format phone numbers based on national conventions 
```
Where does it say "check this, to un install the module"? This simply does not work!

I want to disable phone formatting, that is normal request that should be available in any CRM environment. I do not even get why you added this module. As if users cannot enter a phone number.

**Comment by Yenthe666** [comment] 2020-11-24 10:21
Closing as duplicate of https://github.com/odoo/odoo/issues/62209
@pedrobaeza is one of the most experienced Odoo developers ever so please think twice when you say "when you do not understand it, ask then first some developer.". He creates some of the best apps in the Odoo ecosystem.

**Closed by Yenthe666** 2020-11-24 10:21 UTC

**Comment by pedrobaeza** [comment] 2020-11-24 10:37
Thanks for your support and kind words, Yenthe :smiley:

@f1-outsourcing, this issue tracker is a voluntary effort and try to reflect some bugs that are detected by community, and it's driven by some of us in the community, and thus, it's some times opinionated, but this is not the case, as if there's a technical requirement for having the module installed, it's not something debatable, and even more if the module requiring it is not of Odoo core.

In this case, not knowing the whole reasoning, I would say that if not having well formatted phone numbers, you will have problems using VoIP services, so that's why it's a requirement. You can discuss with the creators of `base_phone` module why they have put such requirement, but this is outside the scope of this issue tracker.

**Comment by f1-outsourcing** [comment] 2020-11-24 12:49
But phone_validation is one from odoo not? And if it is default I can understand that others are using it.

The reason for storing the full number is preventing not well formated auto generated phone numbers. I cannot think of any reason not to store the number with +XX

mobiles phones all accept dialing with +XX also when it stays national.
voip providers also support +XX for national (mine does not even allow local numbers)

If you generate it automatically and not store it, you only increase chances of that it goes wrong. Because you have to take into account all possible options in the world to generate this number correctly.

When storing the full number you do not need to worry about this.

Currently your approach fails when:

Example:
I store phone +XX 1111111, odoo saves 1111111 because the company (the one in users&companies) is in same XX
If you now have a voip provider in different country, submit 1111111 they will think the number is local, connection fails because it should be international.

Example:
If you sync contacts with the phone, and are on holiday the connections fails, should have international number stored.

Example:
If you remove the country of the the company (the one in users&companies). The +XX is not being added back to contact record so the stored number is now incorrect.

Example:
If you change the country of the company (the one in users&companies). You will end up with contacts not having +xx of two countries.

The whole principle of changing data in the entity company (the one in users&companies) has an effect on a not related entity contact is a bad approach.

You will have also incosistent data in your database having some entries +xx  and some without.

Furthermore when I was testing I got the impression that some settings were cached, so it is difficult to tell exactly under what conditions the +XX is being removed. 

I think the argument for storing consitent data and not having a unnecessary relation between company (the one in users&companies) and contact is sufficient to address this issue.

Removing data like +XX is always easier and better, than trying to guess what data is missing and should have been there.

**Comment by pedrobaeza** [comment] 2020-11-24 12:55
But as said, the one requiring to install the module is `base_phone`. For Odoo, if you don't want to auto-format phones, don't install the module. There's no option of formatting it on the fly, and that can't be changed in a stable version. You can, however, develop a module to do it.
