### ISSUE TITLE
Statements - Due

### ISSUE THREAD

**Issue by HeatherEH21** [odoo/odoo#64466] opened 2021-01-13 11:40 UTC
Impacted versions:

Steps to reproduce: In contacts, Due> total due

Current behavior: currently displays £00.00 on every account

Expected behavior: to show the amount due from the invoice so a statement can be sent

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):2439127

**Comment by pedrobaeza** [comment] 2021-01-13 12:17
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by HeatherEH21** [comment] 2021-01-13 16:51
Hi,

Not sure where i'm going with the link?

Heather

**Closed** 2023-04-06 21:34 UTC
Labels: OE, Need information
