### ISSUE TITLE
openerp-gevent missing from Debian package

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#10502] opened 2016-01-17 13:28 UTC
Steps to reproduce: 

1. install https://nightly.odoo.com/9.0/nightly/deb/odoo_9.0c.20160118_all.deb
2. run the following command:

`odoo.py --workers=4 --xmlrpc-port 8066`

Expected: the server starts

Actual: I get 100+ of error messages:

```
/usr/bin/python: can't open file '/usr/bin/openerp-gevent': [Errno 2] No such file or directory
```

**Comment by gurneyalex** [comment] 2016-01-17 13:28
likely similar to #9673

@sle-odoo could you look into this please.

**Comment by gurneyalex** [comment] 2016-01-18 11:25
See also https://github.com/odoo/odoo/pull/10207

**Comment by mart-e** [comment] 2016-01-18 12:05
Closing as duplicate of an existing issue

**Closed by mart-e** 2016-01-18 12:05 UTC
