### ISSUE TITLE
[9.0] Cannot delete a sale team member

### ISSUE THREAD

**Issue by rgeromegnace** [odoo/odoo#9746] opened 2015-11-25 20:10 UTC
I create a sale team. I add several members to that sale team. When I try to delete one of them I got the follwing error:

---

Odoo Avertissement - Erreur de validation
L'opération n'a pas pu être terminée, probablement à la suite d'une :
- suppression : vous essayez de supprimer un enregistrement auquel d'autres enregistrements font référence
- création/modification : un champ requis n'est pas correctement rempli

[objet référencé : Change Password Wizard User - change.password.user]

**Comment by jmalinens** [comment] 2015-11-30 12:37
Delete is not working everywhere where in many2many_kanban widget is used. Also there is mistake in CSS in every Kanban Record delete link: <a t-if="! read_only_mode" type="delete" style="position: absolute; right: 0; padding: 4px; **diplay**: inline-block">X</a>

**Comment by Yenthe666** [comment] 2018-02-14 10:49
Hi @rgeromegnace,

Thanks a lot for the bug report.
It seems to be fixed in the meanwhile as I was no longer able to reproduce this issue.
Please update your Odoo source code to the latest version and try again.

Regards,
Yenthe

**Closed by Yenthe666** 2018-02-14 10:49 UTC
