### ISSUE TITLE
[11.0] l10n_in_stock uninstallable 

### ISSUE THREAD

**Issue by libukoshy** [odoo/odoo#19898] opened 2017-10-05 16:20 UTC
Impacted versions:
Odoo 11
Steps to reproduce:

Current behavior:

Error:
Odoo Server Error

Traceback (most recent call last):
  File "D:\Program Files\odoo-11.0\odoo\http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "D:\Program Files\odoo-11.0\odoo\http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "D:\Program Files\odoo-11.0\odoo\http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "D:\Program Files\odoo-11.0\odoo\http.py", line 341, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "D:\Program Files\odoo-11.0\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "D:\Program Files\odoo-11.0\odoo\http.py", line 334, in checked_call
    result = self.endpoint(*a, **kw)
  File "D:\Program Files\odoo-11.0\odoo\http.py", line 929, in __call__
    return self.method(*args, **kw)
  File "D:\Program Files\odoo-11.0\odoo\http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "D:\Program Files\odoo-11.0\odoo\addons\web\controllers\main.py", line 920, in call_button
    action = self._call_kw(model, method, args, {})
  File "D:\Program Files\odoo-11.0\odoo\addons\web\controllers\main.py", line 908, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "D:\Program Files\odoo-11.0\odoo\api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "D:\Program Files\odoo-11.0\odoo\api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-39>", line 2, in button_immediate_install
  File "D:\Program Files\odoo-11.0\odoo\addons\base\module\module.py", line 70, in check_and_log
    return method(self, *args, **kwargs)
  File "D:\Program Files\odoo-11.0\odoo\addons\base\module\module.py", line 437, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "D:\Program Files\odoo-11.0\odoo\addons\base\module\module.py", line 530, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "D:\Program Files\odoo-11.0\odoo\modules\registry.py", line 84, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "D:\Program Files\odoo-11.0\odoo\modules\loading.py", line 341, in load_modules
    loaded_modules, update_module)
  File "D:\Program Files\odoo-11.0\odoo\modules\loading.py", line 240, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "D:\Program Files\odoo-11.0\odoo\modules\loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "D:\Program Files\odoo-11.0\odoo\modules\loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "D:\Program Files\odoo-11.0\odoo\tools\convert.py", line 788, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "D:\Program Files\odoo-11.0\odoo\tools\convert.py", line 849, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "D:\Program Files\odoo-11.0\odoo\tools\convert.py", line 748, in parse
    exc_info[2]
  File "D:\Program Files\odoo-11.0\odoo\tools\convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "D:\Program Files\odoo-11.0\odoo\tools\convert.py", line 719, in _tag_template
    return self._tag_record(record, data_node)
  File "D:\Program Files\odoo-11.0\odoo\tools\convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "D:\Program Files\odoo-11.0\odoo\addons\base\ir\ir_model.py", line 1467, in _update
    record = record.create(values)
  File "D:\Program Files\odoo-11.0\odoo\addons\base\ir\ir_ui_view.py", line 384, in create
    return super(View, self).create(self._compute_defaults(values))
  File "D:\Program Files\odoo-11.0\odoo\models.py", line 3289, in create
    self._fields[key].determine_inverse(record)
  File "D:\Program Files\odoo-11.0\odoo\fields.py", line 1045, in determine_inverse
    getattr(records, self.inverse)()
  File "D:\Program Files\odoo-11.0\odoo\addons\base\ir\ir_ui_view.py", line 253, in _inverse_arch
    view.write(data)
  File "D:\Program Files\odoo-11.0\odoo\addons\base\ir\ir_ui_view.py", line 400, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "D:\Program Files\odoo-11.0\odoo\models.py", line 3011, in write
    self._write(old_vals)
  File "D:\Program Files\odoo-11.0\odoo\models.py", line 3164, in _write
    self._validate_fields(vals)
  File "D:\Program Files\odoo-11.0\odoo\models.py", line 975, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
ParseError: "Error while validating constraint

Element '<xpath expr="//span[@t-field='pack_operation.product_id.description_picking']">' cannot be located in parent view

Error context:
View `gst_report_picking_inherit`
[view_id: 1039, xml_id: n/a, model: n/a, parent_id: 847]
None" while parsing None:4, near
<data inherit_id="stock.report_picking">
        <xpath expr="//span[@t-field='pack_operation.product_id.description_picking']" position="after">
            <t t-if="pack_operation.product_id and pack_operation.product_id.l10n_in_hsn_code and o.company_id.country_id.code == 'IN'"><h6><strong class="ml16">HSN/SAC Code:</strong> <span t-field="pack_operation.product_id.l10n_in_hsn_code"/></h6></t>
        </xpath>
    </data>

Expected behavior:

Video/Screenshot link (optional):
![isue](https://user-images.githubusercontent.com/4153342/31238255-11c94346-aa17-11e7-881f-3f8d010329a2.png)

**Comment by totalard** [comment] 2017-10-05 16:25
Yeah... Me too Same

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 971, in _validate_fields
    check(self)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 316, in _check_xml
    view_def = view.read_combined(['arch'])
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 700, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 649, in apply_view_inheritance
    source = self.apply_inheritance_specs(source, specs_tree, view_id)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 627, in apply_inheritance_specs
    self.raise_view_error(_("Element '%s' cannot be located in parent view") % tag, inherit_id)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 489, in raise_view_error
    raise ValueError(message)
ValueError: Element '<xpath expr="//span[@t-field='pack_operation.product_id.description_picking']">' cannot be located in parent view

Error context:
View `gst_report_picking_inherit`
[view_id: 742, xml_id: n/a, model: n/a, parent_id: 527]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 719, in _tag_template
    return self._tag_record(record, data_node)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_model.py", line 1467, in _update
    record = record.create(values)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 384, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3289, in create
    self._fields[key].determine_inverse(record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1045, in determine_inverse
    getattr(records, self.inverse)()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 253, in _inverse_arch
    view.write(data)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 400, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3011, in write
    self._write(old_vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3164, in _write
    self._validate_fields(vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 975, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error while validating constraint\n\nElement \'<xpath expr="//span[@t-field=\'pack_operation.product_id.description_picking\']">\' cannot be located in parent view\n\nError context:\nView `gst_report_picking_inherit`\n[view_id: 742, xml_id: n/a, model: n/a, parent_id: 527]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 86, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 341, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 334, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 929, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 920, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 908, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-45>", line 2, in button_immediate_upgrade
  File "/usr/lib/python3/dist-packages/odoo/addons/base/module/module.py", line 70, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/module/module.py", line 591, in button_immediate_upgrade
    return self._button_immediate_function(type(self).button_upgrade)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/module/module.py", line 530, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 84, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 341, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 240, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 788, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 849, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 748, in parse
    exc_info[2]
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 85, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 719, in _tag_template
    return self._tag_record(record, data_node)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_model.py", line 1467, in _update
    record = record.create(values)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 384, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3289, in create
    self._fields[key].determine_inverse(record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1045, in determine_inverse
    getattr(records, self.inverse)()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 253, in _inverse_arch
    view.write(data)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 400, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3011, in write
    self._write(old_vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3164, in _write
    self._validate_fields(vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 975, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error while validating constraint

Element '<xpath expr="//span[@t-field='pack_operation.product_id.description_picking']">' cannot be located in parent view

Error context:
View `gst_report_picking_inherit`
[view_id: 742, xml_id: n/a, model: n/a, parent_id: 527]
None" while parsing None:4, near
<data inherit_id="stock.report_picking">
        <xpath expr="//span[@t-field='pack_operation.product_id.description_picking']" position="after">
            <t t-if="pack_operation.product_id and pack_operation.product_id.l10n_in_hsn_code and o.company_id.country_id.code == 'IN'"><h6><strong class="ml16">HSN/SAC Code:</strong> <span t-field="pack_operation.product_id.l10n_in_hsn_code"/></h6></t>
        </xpath>
    </data>

**Comment by Yenthe666** [comment] 2017-10-06 06:34
Hey @libukoshy,

Please add a bit more information, such as a flow to do for triggering this error. Otherwise it'll be hard to help you 😉

**Comment by JKE-be** [comment] 2017-10-07 22:29
@sle-odoo @qdp-odoo 

Uninstallable module since xpath is no more valid
`<xpath expr="//span[@t-field='pack_operation.product_id.description_picking']" position="after">`

**Comment by totalard** [comment] 2017-10-08 16:22
I just commented Out.... So ok..

How can i fix it permenantly?

**Comment by Yenthe666** [comment] 2017-10-09 05:41
@totalard one of the Odoo developers should fix this soon enough in the official Odoo.

**Comment by pimodoo** [comment] 2017-10-09 08:48
Hello,

This bug has just been fixed in rev: https://github.com/odoo/odoo/commit/e7e37c70e7b71adf6bf51a54202a262b4a2ce68d in 11.0

Best regards

**Closed by pimodoo** 2017-10-09 08:48 UTC
Labels: 11.0

**Comment by DhirajPalekar** [comment] 2017-10-09 12:30
Yeah.. it just fixed the issue.Thanks pimodoo!
Just to be clear: 
Step1: Go To -> addons/l10n_in_stock/views/report_stockpicking_operations.xml
Step2: Find and Replace all 'pack_operation' with 'move'  (Total 4 Times)
Step3. Save the file.
Step4: Restart The Odoo Server

Hope this helps. Cheers!

**Comment by rha-odoo** [comment] 2017-10-09 12:34
Well, Step4 is not required!

**Comment by steeve400** [comment] 2018-01-30 06:54
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/stephen/odoo/odoo11.0/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/stephen/odoo/odoo11.0/odoo/tools/convert.py", line 583, in _tag_record
    self._test_xml_id(rec_id)
  File "/home/stephen/odoo/odoo11.0/odoo/tools/convert.py", line 254, in _test_xml_id
    assert modcnt == 1, """The ID "%s" refers to an uninstalled module""" % (xml_id,)
AssertionError: The ID "course.list" refers to an uninstalled module

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/odoo/odoo11.0/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/stephen/odoo/odoo11.0/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/stephen/odoo/odoo11.0/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/stephen/odoo/odoo11.0/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/stephen/odoo/odoo11.0/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/stephen/odoo/odoo11.0/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/stephen/odoo/odoo11.0/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/stephen/odoo/odoo11.0/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/home/stephen/odoo/odoo11.0/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/stephen/odoo/odoo11.0/addons/web/controllers/main.py", line 934, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/stephen/odoo/odoo11.0/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/stephen/odoo/odoo11.0/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/stephen/odoo/odoo11.0/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-45>", line 2, in button_immediate_upgrade
  File "/home/stephen/odoo/odoo11.0/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/stephen/odoo/odoo11.0/odoo/addons/base/module/module.py", line 602, in button_immediate_upgrade
    return self._button_immediate_function(type(self).button_upgrade)
  File "/home/stephen/odoo/odoo11.0/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/stephen/odoo/odoo11.0/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/stephen/odoo/odoo11.0/odoo/modules/loading.py", line 339, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/home/stephen/odoo/odoo11.0/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/stephen/odoo/odoo11.0/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/stephen/odoo/odoo11.0/odoo/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/stephen/odoo/odoo11.0/odoo/tools/convert.py", line 788, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/stephen/odoo/odoo11.0/odoo/tools/convert.py", line 849, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/stephen/odoo/odoo11.0/odoo/tools/convert.py", line 738, in parse
    self.parse(rec, mode)
  File "/home/stephen/odoo/odoo11.0/odoo/tools/convert.py", line 748, in parse
    exc_info[2]
  File "/home/stephen/odoo/odoo11.0/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/home/stephen/odoo/odoo11.0/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/stephen/odoo/odoo11.0/odoo/tools/convert.py", line 583, in _tag_record
    self._test_xml_id(rec_id)
  File "/home/stephen/odoo/odoo11.0/odoo/tools/convert.py", line 254, in _test_xml_id
    assert modcnt == 1, """The ID "%s" refers to an uninstalled module""" % (xml_id,)
odoo.tools.convert.ParseError: "The ID "course.list" refers to an uninstalled module" while parsing /home/stephen/odoo/odoo11.0/stephen-addons/student/views/views.xml:20, near
<record model="ir.ui.view" id="course.list">
      <field name="name">course</field>
      <field name="model">student.course</field>
      <field name="arch" type="xml">
        <tree>
          <field name="name"/>
          <field name="year"/>
        </tree>
      </field>
    </record>
Anybody can help me but in that case i was trying to connect two models student model and course model the issue is in xml

**Comment by steeve400** [comment] 2018-01-30 06:56
Error:
Odoo Server Error
  File "/home/stephen/odoo/odoo11.0/odoo/tools/convert.py", line 254, in _test_xml_id
    assert modcnt == 1, """The ID "%s" refers to an uninstalled module""" % (xml_id,)
odoo.tools.convert.ParseError: "The ID "course.list" refers to an uninstalled module" while parsing /home/stephen/odoo/odoo11.0/stephen-addons/student/views/views.xml:20, near
<record model="ir.ui.view" id="course.list">
      <field name="name">course</field>
      <field name="model">student.course</field>
      <field name="arch" type="xml">
        <tree>
          <field name="name"/>
          <field name="year"/>
        </tree>
      </field>
    </record>

**Comment by YayFor** [comment] 2019-09-13 16:07
Did you fix this having same error trying to install my app.
