### ISSUE TITLE
Facing problem when sending my vendor or customer emails it says fails

### ISSUE THREAD

**Issue by AsmaAl-Haddar** [odoo/odoo#71071] opened 2021-05-19 19:45 UTC
I am using version 13 but when I create sale order and I make send by email it it shows that the little small envelop on the right or on the left of the page.

**Comment by pedrobaeza** [comment] 2021-05-20 06:45
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Closed** 2023-04-07 14:07 UTC
Labels: Need information
