### ISSUE TITLE
Accounting Generic Feedback - Batch Payments & SEPA

### ISSUE THREAD

**Issue by lap-odoo** [odoo/odoo#20597] opened 2017-10-31 10:13 UTC
Hi, 

This issue is meant to collect feedback about the management of batch payment in Odoo but also about about the SEPA (Credit Transfer & Direct Debit).

**Comment by lap-odoo** [comment] 2017-10-31 10:14
@ploegvde I think you were interested in this subject

**Comment by ploegvde** [comment] 2017-10-31 18:46
For batch payment i would like to see a intermediate account added. On creating the batch payment the total amount is moved to the intermediate account. From bank you get 1 total amount line on the bank statement witch you can directly reconcile with the amount on the intermediate account. That speeds up reconciliation big time.

1. You select 100 invoice for a total amount of €10000
2. You create sepa file and transfer from account payable to intermediate account the €10000
3. You receive a bank statement line of € 10000 and can right away reconcile against intermediate account

This way you only have to select once all invoices. In your solution on reconcile you have to select 100 (!) invoices. This current implementation in Odoo v11 is undo-able in practice and unnecessary because the selection is already mad on creating the batch payment.

**Comment by gelo-landoo** [comment] 2017-11-02 12:04
Hi @lap-odoo
I´m not an expert on this subject, but I think that it should be  kept on mind. In OCA was made a PR on the module that is used to generate SEPA operations. And in the file "Readme" it was said:
"Account Banking PAIN Base Module
This module contains fields and functions that are used by the module for SEPA Credit Transfer (account_banking_sepa_credit_transfer) and SEPA Direct Debit (account_banking_sepa_direct_debit). This module doesn't provide any functionality by itself.
This module was started [...]
Configuration
Go to Accounting > Configuration > Settings.
On the fields "Initiating Party Issuer" and "Initiating Party Identifier", in the section SEPA/PAIN, you can fill the corresponding identifiers.
If your country requires several identifiers (like Spain), you must:
Go to Accounting > Configuration > Settings.
On the section SEPA/PAIN, check the mark "Multiple identifiers".
Now go to Accounting > Configuration > Management > Payment Modes.
Create a payment mode for your specific bank.
Fill the specific identifiers on the fields "Initiating Party Identifier" and "Initiating Party Issuer"."
I´ll give you the link: https://github.com/OCA/bank-payment/blob/10.0/account_banking_pain_base/README.rst
May be I am wrong and only one creditor identifier is valid, but think it isn´t. If this PR was created it would be because it was necessary.
Best regards,

**Comment by gelo-landoo** [comment] 2017-11-02 12:31
Hi @lap-odoo ,
I have detected some subjects to discuss:
1- It´s not possible to set on a partner a payment mode to export at the invoices. I think it´s necessary because a partner can have invoices and each one can have its own payment mode.
2- When I charged an invoice by SDD, I can only charged on a journal with a iban account, because the customer has to have a Debit Direct Mandate and for this you have to set on the Mandate a journal that accepts an iban account (if not, you have this message "SEPA Direct Debit scheme only accepts IBAN account numbers. Please select an IBAN-compliant debtor account for this mandate". In Spain, there is an account you use while you´re sending the receipt and the money arrives at the bank. This is not a iban account, it´s a customer account (number 431200). I only can use this account if I create a journal with this account, and put it as a bank jounal type and I set a iban account. It has no sense.
3- When I charged a customer invoice by SDD, and the customer has two different mandates, I can´t set on which one I want charge it. Then, when I´m going to create the XML file I can´t change it.
4- - If I´m on the list view of supplier invoices I can´t pay by SEPA transfer some of them if they are invoices of different suppliers. I can´t set the bank beneficiary account. I think this data should be on the invoice. 
5- When I´m going to create the sepa transfer xml file, there is an error:
"Unable to generate any data for the selected payments.
Payments in exception
The following payments could not be translated to SEPA Direct Debit XML. Either they do not belong to the company you are currently connected on, they are not related to any mandate, or they have already been collected in a previously generated file"
No one of the three reasons are right.
Regards,

**Comment by lap-odoo** [comment] 2017-12-26 09:14
@gelo-landoo : Concerning the creditor identifier, I checked on different website and it seems well that it is linked to the creditor (the company) and not to the bank/bank account/country. There is one creditor identifier per legal entity. 

http://www.sepaforcorporates.com/sepa-direct-debits/sepa-creditor-identifier/
https://www.ecb.europa.eu/paym/retpaym/undpaym/qa/html/index.en.html
https://www.europeanpaymentscouncil.eu/sites/default/files/kb/file/2017-11/EPC262-08%20v5.0%20Creditor%20Identifier%20Overview.pdf 

I'll have a look at your other feedbacks

**Comment by jvOrsouw** [comment] 2018-05-11 10:13
I'm surprised nothing has been done with the other feedback of @gelo-landoo. Especially nr 3: 

1. I would like the possibility before validating an invoice to choose if the invoice is to be collected by SDD or not, instead of having to remove the payment from the invoice
2. If a customer has more than 1 mandate, I want the possility to choose which mandate (and which bank account) needs to be debited.

**Comment by jvOrsouw** [comment] 2018-05-11 11:56
@lap-odoo when SDD is activated, it should automatically show field 'SDD paying mandate' on the invoice, and here, only mandates of the customer should be shown. This is (at the moment) the only way you can choose which mandate to use in case of multiple mandates. 
Additional: 
- if a one-time mandate is used, it should not be in the list to be selected on the invoice
- request: mandate can not be changed when invoice in state 'paid'. 
- please add the mandate to the treeview of accounting - sales - payments
- show number of active debit mandates on customer

**Comment by ploegvde** [comment] 2018-08-16 08:14
Hi, we are closing in on the V12 freeze and i want to mention my comment again:
https://github.com/odoo/odoo/issues/20597#issuecomment-340868454

@lap-odoo You opent a issue, so you get feedback. Is there a possibility that we get feedback back. Seems like we are doing it for ???

This missing feature (what is quite standard in other applications in the Netherlands) is preventing users from using it. It i a rather easy feature. The big con is that after selecting multiple invoices and putt them in a batch, you don't have to reconcile every invoice again on the bank statement. If yo send a batch payment to the bank the whole amount is set on a (reconcilable) intermediate account. On bank statement you can reconcile the whole bank debit against the amount on the intermediate account. It really speeds up the work

**Comment by Yenthe666** [comment] 2018-08-16 08:50
CC @avw-odoo who is also active on these subjects. Can one of you please give us feedback? It has been from december 2017 that we got a response.

**Comment by avw-odoo** [comment] 2018-08-17 08:58
Hello @ploegvde @Yenthe666 @jvOrsouw @gelo-landoo 

We have made some improvements, you can have a look here.
- https://github.com/odoo/odoo/pull/26349#issuecomment-413111235
- https://github.com/odoo/odoo/commit/74b6f84cc83a9adee7d78e77a5e28465a30ce03a

We are working on SDD (not finished yet)
- Make SDD mandate as a payment token (i.e. you can use mandate by subscription).
- Usable for website payments with easy validation (like a payment acquirer)
- Collect SDD payments in batch payment that make the reconciliation easier

**Comment by fclementic2c** [comment] 2018-08-17 11:53
@lap-odoo 
Functionally, SEPA payment most important features are:
- Being able to pay different suppliers at once. Companies do payment run once or twice a month. 
So, accountant expect to be able to ask the system to provide a list of suggested payment based on due date ; then you should be able to excludes or addup manually other invoices and finally you generate all payments 1 one click.
As long as this feature is not in place Odoo SEPA modiule is useless.

- Being able to say when & how you trigger payments: 
*Fixed date, at each invoice due date, 
* one payment per supplier, per invoice
* Fees are shared, you pay or supplier pay (less important)
* Odoo should store in attachment XML (nice to have)

Also: SEPA payment can uses several versions. In my experience version 3 and 5 are the most common. You only propose 1 version in Odoo (and I am not talking about the SEPA swiss version which is ignored)

Last comment: You must compatible with multi-payment terms. Today you can sort invoice to pay by due date on the invoice but incase of multi payment terms, this due date and the amount to pay is wrong since odoo propose a full payment.

Long awaited features....

**Comment by lap-odoo** [comment] 2018-08-20 07:59
@avw-odoo Can you have a look at the feedback from @fclementic2c ? Thanks 

The responsibility of the accounting app has been transferred to AVW a few months ago, he is now the person to contact for feedback related to accounting.

**Comment by jvOrsouw** [comment] 2018-08-21 10:27
@avw-odoo small request for the SEPA DD XML file: the layout of the address line of debtors is not correct: it should be: 
            <AdrLine>street housenumber doornumber</AdrLine>
            <AdrLine>zip city</AdrLine>

and not everything in 1 line, even including the debtor name.

**Comment by jvOrsouw** [comment] 2018-09-21 20:43
@avw-odoo What is the exact status of the improvements? Is there anything to test?

**Comment by jvOrsouw** [comment] 2018-10-05 08:44
@avw-odoo I had been hoping that creating a 'batch payment' would have improved the flow in the banking software. However: every batch is in the banking software still cut up into multiple files/documents. this is a big issue for SEPA Direct Debit because debiting f.e. 100 customers means the banking software creates 100 documents and banks don't allow for so many documents each month. 
It's caused by 'grouping payment by mandate'. this feature needs to go, or at least be optional to use or not use when creating a SEPA DD.xml file.

**Comment by avw-odoo** [comment] 2018-11-16 20:37
@fclementic2c 

These features are available for 12.0 :

> Being able to pay different suppliers at once.

> One payment per supplier, per invoice

We will launch new tasks about SDD / SCT and I'll still take this thread into account.

**Comment by Yenthe666** [comment] 2018-11-17 08:34
@wtaferner in our case we need exactly the opposite of your case actually. This change makes it better for us in the Netherlands interesting enough. I guess it should become configurable 😉

**Comment by wtaferner** [comment] 2018-11-17 08:54
@Yenthe666
I know, but it should have been a individual patch for you guys in terms of very specific backporting instead of just applying it with a HUGE change of behavior more than one year after release :wink: 

I would love if the features available in 12.0 would have been backported as they would enable all use cases already in 11.0. Anyway, escalated here, via ticket and reverted it on my side, but I do not see why I must now maintain the diff :cry:

**Comment by oco-odoo** [comment] 2018-11-21 10:07
@wtaferner 

Thank you for reporting the issue; but please let us time to react before pinging 8 people on the issue and creating an additional ticket. For this matter, you could as well just have pinged me and I would have reacted all the same (except for this sentence), with no more delay. Making everyone happy is also part of my job, and it'll be my pleasure to fix your issue :)

Regarding the issue, actually the SEPA regulation allows both "old" and "new" way of grouping payments in the XML file. I understand that you call it a "change of behavior," but this is a too strong a term, seen the circumstances. From our point of view, we just generated the same type of file with the same data in a different way that was compliant with the same rules, so that this weird limitation put by Ducth banks did not make our software unusable in the Netherlands. Nothing in the regulation indicates how banks will behave in regards to the way PmtInf nodes are created. 

There is, however, an option that we did not use until now, called batch booking (BtchBookg), telling whether or not the bank should report the transactions with a single statement. It is what is causing your problem. Indeed, as you can see in this document, page 13 https://www.europeanpaymentscouncil.eu/sites/default/files/KB/files/EPC130-08%20SDD%20Core%20C2B%20IG%202017%20V1.0.pdf  , not specifying the option in the XML (which is what we used to do) makes it so that " pre-agreed customer-to-bank
conditions apply". In other words, it all depends on your bank. Note that it was already the case before, you simply got lucky in the way your bank treated PmtInf nodes.

Of course, we cannot solve this in stable with a new field, as it would break our stability policy. So, for 11 and 12, we will use a config parameter allowing changing the default value for this option (false in 11, true in 12 because of account.batch.payment objects). I've done it on these two PR (you can see one has already been merged): 
https://github.com/odoo/enterprise/pull/3111
https://github.com/odoo/enterprise/pull/3112

On master, we can add this new field on account.batch.payment's form view, which is done here (and if the Gods of Merging are with me, it should be ok for next saas):
https://github.com/odoo/enterprise/pull/3117

**Comment by wtaferner** [comment] 2018-11-27 09:20
@oco-odoo 
I have bad news for you guys or myself as it was not accepted by the bank in Austria (the new format with BatchBooking is not working at all compared to the one without the node). As they do not provide useful XML Checkers, information or errors it is probably again a feature which is useless (without fork commits). So, basically the change of behavior and its fix destroyed the feature in this specific case.

No idea why this is happening as I guess you guys were respecting the specifications, but I already lost too much time on this, so I reverted the stuff again on my side and wait for better and/or urgent times.

In case you want to check against an Austrian Institution which is kind of a reference for all banks here, please check the https://stuzza.at XML Checker, but still it is probably just a Banking Issue of the individual implementations (which seems to be a pain). The specific case will anyway switch to another bank, so I will face the issue or other issues again soon enough.

**Comment by oco-odoo** [comment] 2018-11-27 09:45
@wtaferner The XML structure shouldn't be the problem, as it is validated on our side (and tested on runbot) with the schema provided by the EPC. 

As you say, the individual implementations seem to be the real problem here ... Could you maybe ask for more details about the issue on you bank's side ? If something went wrong on their side, it is their reponsability (if not duty) to explain what exactly. Especially if we pass the EU verifications. 

We might end up adding another config parameter to use the former SEPA generation code (grouping per mandate) instead of the Batch Booking one, but before doing so, I would like that the issue on their side is not something simple and silly that we could fix easily while avoiding duplicating code like that uselessly. 

Also, if they claim the problem is the form of the xml, could you maybe provide it to me by mail so that I can have a look ? (while anonymizing it, of course)

**Comment by wtaferner** [comment] 2018-11-27 10:08
@oco-odoo 
I will contact you on a private channel for further communication...it is still a pity that it was done in stable, but I understand your PoV.

**Comment by jwaes** [comment] 2022-05-04 07:18
How am i supposed to know about the config variables to set the `BtchBookg` to false. As an 'ordinary' paying enterprise customer i have no access to the enterprise github repo, nor the issues that are linked in this thread ?

**Comment by wtaferner** [comment] 2022-05-05 05:40
@jwaes 
You can claim access in your odoo.com profile associated with your company having the enterprise contract (I think), otherwise contact support that your Github user gets access to the repo. About the issue above...it is quite old and already resolved in newer versions.

**Comment by Yenthe666** [comment] 2022-05-05 06:04
This thread shoul be closed anyways as lap doesn't even work at Odoo anymore.

**Closed by Yenthe666** 2022-05-05 06:04 UTC
Labels: Accounting, RFC
