### ISSUE TITLE
[11.0] Multi-company: Lot/Serial Numbers visible for other companies' users

### ISSUE THREAD

**Issue by salmemik** [odoo/odoo#23889] opened 2018-03-26 14:29 UTC
Impacted versions: 11.0 (I'm using Community edition)

Steps to reproduce:
- Activate Multi-company configuration from General Settings but do NOT select sub-selection "Common Product Catalog"
- Select "Lots & Serial Numbers" and "Expiration Dates" from Inventory Settings
- Create parent company and its child company
- Create users and products for both companies
- Create e.g. Inventory adjustement for both companies products to their own warehouses, provide lot numbers, Best before dates etc.

Current behavior:
- On the view "Lots/Serial Numbers" user can see all companies' products, lot amounts best before dates..

Expected behavior:
- User can see only the lots of products he/she is allowed to see

Video/Screenshot link (optional):
<img width="1163" alt="inventory_adjustments_-_odoo" src="https://user-images.githubusercontent.com/11749898/37912230-b0d87936-311a-11e8-8473-676e29ec91a7.png">
<img width="1164" alt="products_-_odoo" src="https://user-images.githubusercontent.com/11749898/37912231-b0f64740-311a-11e8-92ea-4b3b1cc75b86.png">
<img width="1167" alt="lots_serial_numbers_-_odoo" src="https://user-images.githubusercontent.com/11749898/37912232-b12d70bc-311a-11e8-81d5-2d13b16c1b4f.png">

**Comment by pedrobaeza** [comment] 2018-03-26 17:15
Lots are not multi-company aware currently, so this is not a bug, but a missing feature. @jco-odoo / @lap-odoo is there any plans for making lots multi-company aware?

**Comment by jco-odoo** [comment] 2018-03-27 07:06
company-awareness could be simple related with the product_id.company_id?

**Comment by gdgellatly** [comment] 2018-03-27 07:26
I'm kind of on the fence on this one and I use lots a lot - a few hundred thousand currently across 9 companies.

Is it annoying to see all the lots for unrelated companies - yes
Does it lead to errors - yes

But on the flipside - when one company sells/transfers to another the lot goes with it.  I guess what I'm saying is that actually the lot is not associated with a company, but rather a product which may be in any company at a time.  Whats more is that they also get full traceability back to raw materials as well, which in our case is really useful.

If I was going to fix, then it would be a company_id field on lots with record rules seperate from the product.  People can implement their own business rules from there.

Or if you were going to use a "related" field then actually I think you need a function field to determine company_id as if the product has no company, but all the moves for that lot are in one company then it is that companies lot.

**Comment by pedrobaeza** [comment] 2018-03-27 07:53
@gdgellatly I think you don't need to complicate the thing: the related field `product_id.company_id` + record rule the same as products (that is now non active by default) serves for the same purpose. If you are transferring a lot between companies, it's because the product has `company_id = False`, and thus the product + lot will be visible for all companies.

**Comment by gdgellatly** [comment] 2018-03-27 08:24
@pedrobaeza I'm not convinced.  Sometimes products are used by all companies, but lots specific to a company.  Sometimes they aren't.  By using a related field or a functional field you need to consider what is given up as well.  

In fact I think it is simpler to not use a related field, and just use a default of the products company.

**Comment by pedrobaeza** [comment] 2018-03-27 08:44
OK, but then it should be put on the product onchange, not as default. Any way, it's still more complicated when you change the company in the product, so my bet is still for the related field.

**Comment by gdgellatly** [comment] 2018-03-27 09:29
@pedrobaeza When you change the product of a company?  That causes more issues than a simple lot number.  Sales orders, invoices, etc etc. i.e all the places where a lot is actually used would then need updating.  I guess I just don't see why a product lot is so special that it should be related compared to say a sale order line.

**Comment by pedrobaeza** [comment] 2018-03-27 10:09
Well, then any of both approaches is OK.

**Comment by sle-odoo** [comment] 2020-01-07 19:29
Implemented in v13 at b6f053b25ef80599086797a41521c9e5679a015e

**Closed by sle-odoo** 2020-01-07 19:29 UTC
Labels: 11.0, Logistics
