### ISSUE TITLE
[12.0][bus] updating channels in CrossTabBus cause recursive loop

### ISSUE THREAD

**Issue by hoangtrann** [odoo/odoo#55650] opened 2020-08-08 16:55 UTC
Impacted versions: 12.0

Steps to reproduce:

- Note that this issue happend on mobile device running iOS. In my case, I use iPhone with `iOS 13.5`.
- I encounter this issue while using `web_notify` provided by OCA.
- The implementation is quite simple, we add new channel(s) in in `WebClient` `show_application`, then the issue will happend after loading the application

Current behavior:

- Recursive loop of adding-deleting channel and doing polling at the same time.
- Resource exhaustion happened on both client-side and server-side
- I guess that Local Storage is used for working with cross tab longpolling, as we use value store at local as reference of which channels to be added or deleted.
- This issue happend even if the tab is master

Expected behavior:

Video/Screenshot link (optional):

I add `console.log` to show the channels while the bus service processes events in `crosstab_bus`, these logs will keep showing infinitely

```
addChannel: function () {
        this._super.apply(this, arguments);
        this._callLocalStorage('setItem', 'channels', this._channels);
        console.log("after add channel", this._callLocalStorage('getItem', 'channels'));
    },
```

```
_onStorage: function (e) {
        var value = JSON.parse(e.newValue);
        var key = e.key;
        
        ...
        
        // update channels
        else if (key === this._generateKey('channels')) {
            var channels = value;
            console.log("new channels", channels);
            console.log("current channels", this._channels);
            console.log(_.difference(this._channels, channels));
            console.log(_.difference(channels, this._channels));
            _.each(_.difference(this._channels, channels), this.deleteChannel.bind(this));
            _.each(_.difference(channels, this._channels), this.addChannel.bind(this));
        }
        ...
    },
```

![image](https://user-images.githubusercontent.com/43057022/89715908-51af6f00-d9d3-11ea-9657-7d77a1bc217f.png)

**Comment by pedrobaeza** [comment] 2020-08-09 10:47
Sorry, but if the problem comes using a third-party module, this is not something of Odoo itself. If you think you can fix it changing something in Odoo, just make the PR with that patch, and it can be considered for its inclusion, but if not, you have to patch that third-party module, not Odoo.

Closing then as no Odoo issue, but third-party one.

**Closed by pedrobaeza** 2020-08-09 10:47 UTC

**Comment by nilshamerlinck** [comment] 2020-08-10 05:18
Hi @hoangtrann

I pushed a fix for `web_notify` here: https://github.com/OCA/web/pull/1531

Let me know if it helps in your case ;-)

**Comment by BT-sschmid** [comment] 2021-05-06 16:48
Coming back to this topic after having the same issues...
The problem is the addChannel method of the JS Bus implementation which writes to the browser's local storage. In case of multiple Tabs, each can write to this storage. But as the local storage is not threadsafe the loop as initially described can occur.

Odoo itself does not use the addChannel method, they add channels in the backend directly in the bus.bus model. Thus, as long as there is no locking-mechanism for the localstorage you should add the channel via backend in the bus.bus model directly.

**Comment by Yenthe666** [comment] 2021-05-06 17:09
Also see https://github.com/odoo/odoo/pull/69383 for native Odoo fixes related to longpolling storms
