### ISSUE TITLE
odoo12: contact search results, click discuss, clicking back in browser does not work.

### ISSUE THREAD

**Issue by f1-outsourcing** [odoo/odoo#62228] opened 2020-11-24 09:55 UTC
That is of course very annoying, and you have to manually go back to the contacts and search for the contact again.

I already reported it like this, because I thought it is not really related to the module.
https://github.com/odoo/odoo/issues/62186

**Comment by Yenthe666** [comment] 2020-11-24 10:22
Can you add a video of what you mean please? Do you mean you search in the contacts app on some criteria and then click the back button?

**Comment by f1-outsourcing** [comment] 2020-11-24 10:46
http://www.f1-outsourcing.eu/files/20201124-114037.mp4

**Comment by pedrobaeza** [comment] 2020-11-24 11:00
The problem is that the URL doesn't contain whole "activity", so filters and so on are not kept when you are using browser back button or go to another app. This is by design, and the reasoning behind that includes some convenience, some technical reasons.

Closing as well as this won't be fixed and discussed other times.

**Closed by pedrobaeza** 2020-11-24 11:00 UTC
Labels: Need information

**Comment by Yenthe666** [comment] 2020-11-24 11:11
Yeah. It is annoying but this basically a limitation of how the framework works right now. The Odoo team is aware of it though! :)
