### ISSUE TITLE
The logo is not centered vertically on the contact page

### ISSUE THREAD

**Issue by LeDistordu** [odoo/odoo#11565] opened 2016-03-31 20:34 UTC
Odoo 9.0e-20160330

The logo is not centered vertically on the contact page

https://www.odoo.com/forum/help-1/question/page-nous-contacter-et-le-centrage-vertical-du-logo-99999

**Comment by Yenthe666** [comment] 2016-05-20 16:33
Hi @LeDistordu the Odoo help topic you're linking to is showing custom development that you want to do, since you want this logo centered.
This is not something that falls under an issue, since you can't reproduce this on the Runbot / is intended in this way.
@mart-e just to be sure, can you confirm this? Closing this since I'm quite sure about it.

**Closed by Yenthe666** 2016-05-20 16:33 UTC

**Comment by mart-e** [comment] 2016-05-23 07:06
@Yenthe666 indeed, github is not the right plcae to ask advises for customisation (and redirect to mailing list or forum)

**Comment by LeDistordu** [comment] 2016-05-29 16:57
it's not customisation, i think logo must be center by default no ? Everybody is looking how to get around it made did not..
