### ISSUE TITLE
Report missing footer Odoo 8 

### ISSUE THREAD

**Issue by Sameer1990** [odoo/odoo#4938] opened 2015-01-27 13:34 UTC
Hello ,
I have an issue with printing reports on Odoo 8 , without any customization  on any module , just the src code , the footer for all report not shown .

I have tried many src code from nightly.odoo.com .

OS : Linux Ubuntu 14.04  32 bit
Webkit version : downloaded from http://wkhtmltopdf.org/downloads.html .

**Comment by Yenthe666** [comment] 2015-01-27 13:46
Hmm this might be the same issue as https://github.com/odoo/odoo/issues/4806

**Comment by sle-odoo** [comment] 2015-01-28 10:20
Hi,
I'm closing this as it's a duplicate of #4806.
Wkhtmltopdf version 0.12.2 and 0.12.2.1 seems to have some regressions: `--dpi` ignored and javascript links not processed.

You should use [wkhtmltopdf 0.12.1](http://sourceforge.net/projects/wkhtmltopdf/files/archive/0.12.1/). We are working on workaround and discussing with the maintainer of the project in the meanwhile.

Regards

**Closed by sle-odoo** 2015-01-28 10:20 UTC
