### ISSUE TITLE
[11.0-12.0] Calendar view should respect readonly start and end date

### ISSUE THREAD

**Issue by cvinh** [odoo/odoo#27482] opened 2018-10-07 03:47 UTC
Impacted versions:
11.0, 12.0
Steps to reproduce:
Go to Event module, create and finish an event
Current behavior:
In form view, the start and end date are readonly
In calendar view, the event can be moved
Expected behavior:
In calendar view, the event should be readonly as start date and end date are both readonly

Video/Screenshot link (optional):

**Comment by cvinh** [comment] 2019-03-07 07:44
I think that's a big core problem for calendar views... is Odoo SA gonna move calendar views to Enterprise ? @Yenthe666

**Comment by Yenthe666** [comment] 2019-03-07 07:47
Why would you say it is a big core problem though? All calendar view records are always movable, it is by design. As far as I know nothing is planned to move them to enterprise.

**Comment by cvinh** [comment] 2019-03-08 06:30
@Yenthe666 because they don't respect security on the object. It's the aim of this issue. You should not be able to move an event in the calendar view if date_start or date_end are readonly at the object level... What is your point of view ?

**Comment by Yenthe666** [comment] 2019-03-08 07:03
Well you have a fair point atleast but it is not my call to make. @mart-e what do you think?

**Comment by mart-e** [comment] 2019-03-08 08:47
This is a rather aggressive approach to report an issue...

What you see [on the field definition](https://github.com/odoo/odoo/blob/2dbce5e6ff851ecc9936bccb40ec42663f0e8bb4/addons/event/models/event.py#L143) will apply only on the form view.
The calendar will allow you to drag&drop records if the [start field is writable](https://github.com/odoo/odoo/blob/2dbce5e6ff851ecc9936bccb40ec42663f0e8bb4/addons/web/static/src/js/views/calendar/calendar_view.js#L149) (globally, not per record).

The readonly attributes set on the views or domains set on the fields are not security measures, it is an helper on the UI. It indicates the user he should probably not modify these values but, if he really wants to modify it (because he knows what he is doing), he will still be able. There is many way to work around, the calendar is one of them.

If we really want to prevent modifying a record in a specific condition, we would use security rules, like [we do on leaves](https://github.com/odoo/odoo/blob/afd2019fd48d8e7a652bc08f8826ac4902b0d280/addons/hr_holidays/security/hr_holidays_security.xml#L30..L36) or an overwrite of the `write` like [we do on PoS orders](https://github.com/odoo/odoo/blob/12.0/addons/point_of_sale/models/pos_order.py#L612..L621).

If you disagree with this implementation, please check our [contributing guidelines](https://github.com/odoo/odoo/wiki/Contributing) and don't hesitate to submit a patch to improve that.
In the meantime, I am closing this issue as the calendar do work as expected.

**Closed by mart-e** 2019-03-08 08:47 UTC
Labels: 11.0, 12.0, Services

**Comment by cvinh** [comment] 2019-03-08 09:15
@mart-e thanks for pointing the code.
I did not intend to be aggressive, I'm sorry that you took it so.
Your answer is very clear, thanks again for your time to clear that.

**Comment by mart-e** [comment] 2019-03-08 09:23
@cvinh no worries, glad we sorted that
