### ISSUE TITLE
Can't save documents which has Date field in Japanese Language

### ISSUE THREAD

**Issue by kosuke1103** [odoo/odoo#7440] opened 2015-07-03 08:56 UTC
Hi all,

In Japanese language, some documents which have date field can't save.

 Because AM and PM is shown as "午前" and "午後" in Japanese.

When I change it to AM or PM, I can save it...
<img width="1280" alt="save" src="https://cloud.githubusercontent.com/assets/6937795/8496004/d90c160e-21ac-11e5-9cb3-87377bfd004d.png">
<img width="1280" alt="error" src="https://cloud.githubusercontent.com/assets/6937795/8496003/d90a33f2-21ac-11e5-854f-6b342e86ab55.png">

**Comment by SaFi2266** [comment] 2015-07-14 09:25
Same exactly here with Arabic language too

**Comment by hkgenpex** [comment] 2015-11-27 05:20
Yes I also can not save record with adding date in record using Arabic Language.
This error with Version 8 & Version 9 both.

**Comment by Yenthe666** [comment] 2016-05-27 08:09
Hi @kosuke1103,

I've just tried this with the latest V8 build from Odoo and I can no longer reproduce this error:
![image](https://cloud.githubusercontent.com/assets/6352350/15602022/1adaa8e0-23f3-11e6-9487-af2c5cf4e589.png)
Closing this since it is fixed.

Regards,
Yenthe

**Closed by Yenthe666** 2016-05-27 08:09 UTC
