### ISSUE TITLE
[14.0] not possible reconcile 

### ISSUE THREAD

**Issue by siddjellali** [odoo/odoo#71189] opened 2021-05-24 20:19 UTC
Impacted versions: Odoo 14.0-20210518 (Community Edition)

Steps to reproduce:

am not able to reconcile any journal item. The steps to reproduce the error are the next ones:

Create an invoice (to reconcile with)
Create an item in a bank or cash journal
Publish the entry
Try to reconcile the invoice in the step 1 with the journal entry.
Current behavior: 
You get the error "The entry ... is already posted"
Expected behavior: reconcile OK

**Comment by pedrobaeza** [comment] 2021-05-24 20:21
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by siddjellali** [comment] 2021-05-25 18:09
Hi, 

indeed, i'm not able to reproduce this issue because it's linked to a community module "base_accounting_kit"
https://apps.odoo.com/apps/modules/14.0/base_accounting_kit/

![image](https://user-images.githubusercontent.com/3965823/119546906-b7b78800-bd94-11eb-9789-6ad0cde89bd3.png)

I will reach the support #Cybrosys.

**Comment by pedrobaeza** [comment] 2021-05-25 18:13
Yes, please. This is only for Odoo core modules.

**Closed by pedrobaeza** 2021-05-25 18:13 UTC
Labels: Need information
