### ISSUE TITLE
[12.0]jquery error when enable debug=assets

### ISSUE THREAD

**Issue by Guobower** [odoo/odoo#31711] opened 2019-03-08 14:34 UTC
Impacted versions:
Odoo 12.0
Steps to reproduce
1、Creat a new database.
2、Install app sale
3、Enable debug=assets

Current behavior:

Expected behavior:

Video/Screenshot link (optional):
![qq 20190308223225](https://user-images.githubusercontent.com/22065407/54034586-35157300-41f2-11e9-87e2-4387e016ff8e.png)

**Comment by pedrobaeza** [comment] 2019-03-10 15:54
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Closed** 2019-03-14 21:57 UTC
Labels: 12.0, Need information
