### ISSUE TITLE
[11.0] Payments bringing miscellaneous journals by default

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#22296] opened 2018-01-17 11:42 UTC
#### Impacted versions:
11.0

#### Steps to reproduce:
Create a Payment

#### Current behavior:
Miscellaneous journals comes by default:
![image](https://user-images.githubusercontent.com/16890942/35041082-eaf738e2-fb59-11e7-963d-de2666a96146.png)

It just changes after the amount is input

#### Expected behavior:
Bring bank and cash journals by default.

**Comment by gustavovalverde** [comment] 2018-01-17 11:44
@Yenthe666  I know you'll see this one and tag it, but this is annoying and confusing, I'd say it's kind of urgent to fix it.

**Comment by Yenthe666** [comment] 2018-01-17 12:23
@qdp-odoo this looks annoying to me too. Did you do this with a specific reason?

**Comment by qdp-odoo** [comment] 2018-01-18 09:10
Alas, this was made on purpose to allow the following use case: upon registration of a payment of 0$, select a misc journal in order to be able to close an invoice with a writeoff.

That being said, we may enable that only for the registration of payments from invoices/bills!

**Comment by Yenthe666** [comment] 2018-01-18 09:17
@qdp-odoo so to conclude:
- This was done by purpose
- We might want to improve this so it only happens for specific cases (registration of payments from invoices/bills) but that would be against the master?

**Comment by qdp-odoo** [comment] 2018-01-18 09:56
yes indeed, I just checked and it ain't be that easy to change in stable... So let's close this issue and report that as a feedback to @lap-odoo 

thanks for the contribution, anyway

**Closed by qdp-odoo** 2018-01-18 09:56 UTC
Labels: 11.0, Accounting

**Comment by gustavovalverde** [comment] 2018-01-18 11:43
Just as a side note from this one. Even though it's in the commit history, is there a change-log  of behavioral changes like this one? It's been harder than usual in v11 to identify all new features and changes. This one for example, if not explained, it might be seen like a bug (it's kind of a bug, but not completely).

I know there was a technical document done internally showing all possible the changes coming to v11, some of then were added others moved to v12, but I haven't found a place where I can have a comparison of changes between v10 and v11, or all the new features in v11.

Maybe @lap-odoo can shed some light here.

**Comment by lap-odoo** [comment] 2018-01-18 12:53
@gustavovalverde Thanks for the feedback, I've created a task to improve that in Master. 

We do have public release notes (https://www.odoo.com/fr_FR/page/odoo-11-release-notes#part_7) but, indeed, they don't contain all the details. I agree it would be interesting to share more detailed release notes (mainly for the Odoo Partners). I'll discuss it internally and I hope we will be able to have that for the next releases .. 

But for that particular question, I'm not sure the release not would have helped you. This behavior is a downside of a development made to be able to register a write-off (without payment) from an invoice. Even if you had access to a detailed release note it would not be obvious to make the link between that development and the behaviour when creating a payment from scratch.

**Comment by gustavovalverde** [comment] 2018-01-18 12:59
Thanks @lap-odoo, I know that a more detailed release notes will be appreciated by partners, mainly for knowledge on new version implementations and will also help on marketing from a partner's perspective. I'm confident on your feedback evaluation, and I know good things will happen after your discussion.

**Comment by qdp-odoo** [comment] 2018-01-18 13:32
@gustavovalverde you're going to make her blush...

**Comment by lap-odoo** [comment] 2018-02-01 15:09
@gustavovalverde : Here is the release note for Version 11.1 : https://www.odoo.com/page/odoo-11-1-release-notes. This contains a summary of all the changes that have been done between 11.0 and 11.1. If you need the technical details, then using github will be more appropriate.

**Comment by gustavovalverde** [comment] 2018-02-01 22:21
In @lap-odoo we trust! 😄

Just two comments based on this great addition:
1- Can this be a milestone in github? Maybe a tag or something to identify it. As right now we have branch 11.0 and saas-11.1. Right now it could be confusing, even I'm not sure if 11.0 includes this changes (I'm assuming it does, but I'm not 100% sure until I check the commit history).

2- Are those release notes just in English? Or do we have a transifex counterpart to make the translation?

**Comment by mart-e** [comment] 2018-02-02 10:00
Hello Gustavo,

I have added the release notes translations on transifex if you wish to translate it:
https://www.transifex.com/odoo/odoo-com/release_notes/

**Comment by d-fence** [comment] 2018-02-02 10:33
Hello Gustavo,

we decided to not use tags to identify releases in git. The main reasons are that it will interfere with our branch naming and it can confuse the end user. But we have release commits if you want to find when a release was done. The commit comment starts with '[REL] ...'.

**Comment by gustavovalverde** [comment] 2018-02-12 12:56
@d-fence, I'm still confuse. 

Are the 11.1 changes part of the `11.0` branch, or just part of the `saas-11.1` branch?

Just in case it's just part of `saas-11.1`, is it safe to use this branch for on-premise production databases? Is there information on how to move from one saas branch to another?

Side note: @Yenthe666, do you have some on those good tutorials with information on `saas`'s branches use?

**Comment by Yenthe666** [comment] 2018-02-12 13:11
Hey @gustavovalverde,

No I don't have any tutorial about the `saas` branches for one simple reason: nobody should ever use `saas`-branches unless you're Odoo itself. Its not a good idea to get into that and I don't want to get anybody into it 😆

**Comment by mart-e** [comment] 2018-02-12 13:19
The problem is that saas branches are stable but have a short lifetime. So you can if you want but we don't support them and will probably drop them quickly. We publish them as a good way to show the state of our current developments and if you wish to test how is going to be the next stable version but I don't advise it to run on production.

**Comment by Yenthe666** [comment] 2018-02-12 13:20
Think about the upgrading. Upgrade every few months.. 😱

**Comment by gustavovalverde** [comment] 2018-03-28 13:42
Just as a heads-up. Thanks to @ougc27 for his fix on stable 😉 https://github.com/odoo/odoo/commit/8327b67cf5498a1d9d133ec02f0e7619c4ce26d1
