### ISSUE TITLE
Install odoo12 enterprise on ubuntu 18.04 LTS error

### ISSUE THREAD

**Issue by vsnetvn** [odoo/odoo#31318] opened 2019-02-21 09:40 UTC
I installed odoo 12 enterprise on ubuntu 18.04 LTS google cloud but when I manipulated once, odoo died and appeared log "Segmentation fault (core dumped)". Can you explain how to help me?

VPS info: 4Cpu, Ram 16G

Log file:
2019-02-21 09:39:41,379 28831 INFO TEST werkzeug: 120.72.83.181 - - [21/Feb/2019 09:39:41] "POST /web/dataset/call_kw/hr.employee/load_views HTTP/1.1" 200 - 92 0.071 0.102
2019-02-21 09:39:41,510 28831 INFO TEST werkzeug: 1.55.227.39 - - [21/Feb/2019 09:39:41] "POST /calendar/notify HTTP/1.1" 200 - 3 0.007 0.008
2019-02-21 09:39:41,517 28831 INFO TEST werkzeug: 1.55.227.39 - - [21/Feb/2019 09:39:41] "POST /web/dataset/call_kw/res.users/systray_get_activities HTTP/1.1" 200 - 15 0.022 0.011
2019-02-21 09:39:41,524 28831 INFO TEST werkzeug: 1.55.227.39 - - [21/Feb/2019 09:39:41] "GET /web/image?model=res.users&field=image_small&id=2 HTTP/1.1" 200 - 13 0.016 0.011
2019-02-21 09:39:41,817 28831 INFO TEST werkzeug: 120.72.83.181 - - [21/Feb/2019 09:39:41] "POST /web/dataset/search_read HTTP/1.1" 200 - 18 0.010 0.008
2019-02-21 09:39:41,975 28831 INFO TEST werkzeug: 120.72.83.181 - - [21/Feb/2019 09:39:41] "GET /web/image?model=hr.employee&field=image_medium&id=1&unique= HTTP/1.1" 200 - 14 0.014 0.015
2019-02-21 09:39:41,977 28831 INFO TEST werkzeug: 120.72.83.181 - - [21/Feb/2019 09:39:41] "GET /web/image?model=hr.employee&field=image_small&id=1&unique= HTTP/1.1" 200 - 14 0.010 0.018
2019-02-21 09:39:44,095 28831 INFO TEST werkzeug: 1.55.227.39 - - [21/Feb/2019 09:39:44] "POST /web/action/load HTTP/1.1" 200 - 30 0.021 0.029
Segmentation fault (core dumped)

**Comment by pedrobaeza** [comment] 2019-02-21 09:45
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/12.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

**Closed by pedrobaeza** 2019-02-21 09:45 UTC

**Comment by Elkasitu** [comment] 2019-02-21 09:47
Can you explain how you installed it? From source? A .deb? An installation script? Docker?

**Comment by vsnetvn** [comment] 2019-02-21 09:48
My install with exable https://www.odoo.yenthevg.com/installing-odoo-12-enterprise-ubuntu/

**Comment by Elkasitu** [comment] 2019-02-21 10:03
That install medium is not an official one, try with an official installation medium and see if the problem persists

**Comment by Yenthe666** [comment] 2019-02-21 10:54
> That install medium is not an official one, try with an official installation medium and see if the problem persists

hey hey, no hate on my script! ⛔️  😉 
Looks like your Odoo instance tried to access memory that it didn't have access too. What are the server specifications?

**Comment by vsnetvn** [comment] 2019-02-22 01:58
Hi Yenthe66

My info

Filesystem      Size  Used Avail Use% Mounted on
udev            7.9G     0  7.9G   0% /dev
tmpfs           1.6G  5.9M  1.6G   1% /run
/dev/sda        315G  4.8G  295G   2% /
tmpfs           7.9G  8.0K  7.9G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           7.9G     0  7.9G   0% /sys/fs/cgroup
tmpfs           1.6G     0  1.6G   0% /run/user/0

root@localhost:~# free -m
              total        used        free      shared  buff/cache   available
Mem:          16040         136       15172          31         730       15591
Swap:           255           0         255

**Comment by vsnetvn** [comment] 2019-02-22 02:15
![screenshot from 2019-02-22 09-11-31](https://user-images.githubusercontent.com/5435030/53215163-f6c07580-3681-11e9-89ff-1bba73a14cb3.png)
Click menu Contact is odoo die log export Segmentation fault (core dumped)

**Comment by vsnetvn** [comment] 2019-02-22 02:47
![screenshot from 2019-02-22 09-11-31](https://user-images.githubusercontent.com/5435030/53216162-4a34c280-3686-11e9-9970-38d1c924e802.png)
Click menu Contact then odoo is die export log Segmentation fault (core dumped)

**Comment by Yenthe666** [comment] 2019-02-22 07:10
Do other menus and apps work fine or do they have the same problem? Can you update your Odoo to the latest source and then restart the Odoo service too?

**Comment by vsnetvn** [comment] 2019-02-22 07:28
The menu and other applications are fine but the Contact menu is constantly having problems, I tried to uninstall many times in different ways such as installing community, installing enterprise and on ubuntu 16.04. Really too deadlock because my odoo setup experience is pretty much (from odoo 8, 9, 10, 11 and 12). Can you help me with a personal account?

**Comment by vsnetvn** [comment] 2019-02-22 09:37
Exactly accessing the res.partner object will fail when I mention it

**Comment by Yenthe666** [comment] 2019-02-22 09:40
@vsnetvn hmm if it only on the res.partner object then there is no issue with my script as it is only in one place. Do you have custom development on res.partner?

**Comment by vsnetvn** [comment] 2019-02-22 09:42
@Yenthe666 Your right command I used a lot it is not a problem. The problem is now Odoo
