### ISSUE TITLE
report footer missing after restart, adding --javascript-delay to wkhtmltopdf fixes it [PATCH]

### ISSUE THREAD

**Issue by gooofy** [odoo/odoo#4482] opened 2014-12-31 12:10 UTC
Hi,

we noticed a pretty hard to trace problem with one of our custom qweb based reports: the report would sometimes be missing its footer, typically after a odoo restart but also at random times. after extensive debugging we discovered that specifying a larger javascript-delay in wkhtmltopdf seems to fix the problem permanently, see patch below.

would it make sense to add a system parameter in odoo to let users specify this delay in a permantent way so it would match their setup?

details about our setup:

- debian 7
- wkhtmltopdf 0.12.1 (static build from wkhtmltopdf.org with patched qt)
- odoo 8 stable build from dec 30th 2014
- running behind apache https proxy setup

problem seems to be related to load times for javascript and css, in our case web base url points to https proxy so loading especially after apache restart can take a bit of time. in fact, we managed to reproduce the problem by restarting apache proxy alone.

```javascript
--- report/models/report.py     2014-12-31 13:00:11.750661235 +0100
+++ /opt/odoo/openerp_old/openerp/addons/report/models/report.py        2014-11-23 16:22:52.000000000 +0100
@@ -439,16 +439,12 @@
                 content_file.write(reporthtml[1])
 
             try:
-                wkhtmltopdf = [_get_wkhtmltopdf_bin()] + ['--javascript-delay', '5000'] + command_args + local_command_args
+                wkhtmltopdf = [_get_wkhtmltopdf_bin()] + command_args + local_command_args
                 wkhtmltopdf += [content_file_path] + [pdfreport_path]
 
                 process = subprocess.Popen(wkhtmltopdf, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
                 out, err = process.communicate()
 ```

**Comment by sle-odoo** [comment] 2015-01-06 16:52
Hello,
Thanks for the detailed report.
I don't think that this patch is a good idea. It looks like wkhtmltopdf doesn't wait correctly for the end of the request or the script execution, so is it really an Odoo bug? Did you investigate the no stop slow scripts argument? Also, did you customize the report footer?

I suggest you to visit the [wkhtmltopdf issues tracker](https://github.com/wkhtmltopdf/wkhtmltopdf/issues), maybe a similar issue has been commented by the authors.

Regards

**Comment by gooofy** [comment] 2015-01-06 17:16
Hi Martin,

On Wed, Dec 31, 2014 at 4:17 PM, Martin Trigaux
<notifications@github.com> wrote:

> You are adding and not removing command_args I guess.

yeah, right - sorry, got the patch reversed #-}

> Could you create directly a pull request? Also your change should probably go to command_args.

sorry, no, I cannot prepare a pull request right now. putting the
extra option into command_args sounds like a good idea to me.

> Also do you have this only on custom reports or also possible on standard?

we did not notice the issue on the standard reports but then we didn't
try those very often (only by accident, in fact ;) )

> Do you have more info on what could cause the timeout on javascript ?

it seemed to us that a slow webserver/proxy (like the one we were
using when freshly re-started) is a contributing factor but we did not
investigate the matter further.

> I don't think it's useful to specify a parameter for this if we have a big enough value. cc @sle-odoo

sure, why not. for our client it seems for now 0.75s is already
enough, the default 0.5 seems just a tiny bit too tight.

thanks for looking into this,

   guenter

**Comment by gooofy** [comment] 2015-01-06 17:20
Hi Simon,

On Tue, Jan 6, 2015 at 5:52 PM, Simon Lejeune <notifications@github.com> wrote:

> Thanks for the detailed report.
> I don't think that this patch is a good idea. It looks like wkhtmltopdf doesn't wait correctly for the end of the request or the script execution, so is it really an Odoo bug?

hard for me to tell. arguably the patch is rather a workaround than a
fix - I can say for certain it did fix the issue for us :)

> Did you investigate the no stop slow scripts argument?

I don't think so

> Also, did you customize the report footer?

yes, the footer is customize for the client - nothing fancy, though,
just a three-column footer of static test + std page number
information

> I suggest you to visit the wkhtmltopdf issues tracker, maybe a similar issue has been commented by the authors.

I don't think we will have the necessary resources to investigate this
further from our side (we will be busy with the odoo rollout for the
coming weeks and months and need to stay focused), just wanted to make
sure the issue is documented. feel free to investigate the matter
further yourself and/or use the patch we provided.

thanks again for the great work on odoo!

   guenter

**Comment by sle-odoo** [comment] 2015-01-06 17:24
Thanks, i'll keep this issue in mind, but i'm closing it as i can't reproduce it at this time.
Maybe you can try `--no-stop-slow-scripts` to avoid defining a bigger and bigger time to wait.
Regards

**Closed by sle-odoo** 2015-01-06 17:24 UTC

**Comment by zeeshananjumjunaidi** [comment] 2017-04-27 07:50
Thanks
