### ISSUE TITLE
[13.0] Cannot install/uninstall modules after uninstalling ecommerce/website

### ISSUE THREAD

**Issue by robot-nick** [odoo/odoo#50873] opened 2020-05-07 14:54 UTC
Impacted versions: 13.0

Steps to reproduce:
Uninstall ecommerce, then try uninstalling website module.
After that, trying to install any other module.

Current behavior:
Cannot install new modules and Apps.

```
psycopg2.ProgrammingError: column s.website_id does not exist
LINE 37:         , s.website_id as website_id, s.warehouse_id as ware...
                   ^
```

Expected behavior:
Install/Uninstall website/ecommerce/other apps

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2020-05-07 14:56
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by robot-nick** [comment] 2020-05-07 15:28
Hey, so I started a new DB on odoo 13.0 official docker CE version. Was using it for around a week and created website with webshop. Decided that I wont need the webshop, so I uninstalled the eCommerce Module and got the error the first time, also the website_id one. Then I tried uninstalling the website which did not work, throwing the same error.

Today I understood, that when trying to install the "restaurant" module, same thing happens. And unistalling website isnt possible either anymore. I never tempered with the DB, but for a quick fix, if there is one, I installed phppgadmin to fix it. I just don't have enough knowledge to do that.

Will try to reproduce the error in runbot later today!

This is the full error:

```
Fehler:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1326, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-60>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 463, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 573, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 423, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 202, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name}, new_install)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 349, in init_models
    model.init()
  File "/usr/lib/python3/dist-packages/odoo/addons/sale/report/sale_report.py", line 147, in init
    self.env.cr.execute("""CREATE or REPLACE VIEW %s as (%s)""" % (self._table, self._query()))
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 164, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 241, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: column s.website_id does not exist
LINE 37:         , s.website_id as website_id, s.warehouse_id as ware...
                   ^
```

**Comment by pedrobaeza** [comment] 2020-05-08 20:00
Have you tried to restart the service? Please try the same on runbot.

**Comment by Yenthe666** [comment] 2020-06-06 15:32
Closing as there has been no more feedback.

**Closed by Yenthe666** 2020-06-06 15:32 UTC
Labels: Need information

**Comment by ahmedshahriar** [comment] 2020-07-22 15:49
Restarting the service solved my issue.
