### ISSUE TITLE
[10.0]Setup Error due to "No module named passlib.utils"

### ISSUE THREAD

**Issue by zaneven** [odoo/odoo#16451] opened 2017-04-16 05:38 UTC
Impacted versions: 10.0

Steps to reproduce:

1. git clone from site

2. pip install -r requirements.txt

3. python odoo-bin

then
```
[root@VM_0_110_centos odoo]# python odoo-bin
Traceback (most recent call last):
  File "odoo-bin", line 5, in <module>
    __import__('pkg_resources').declare_namespace('odoo.addons')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2078, in declare_namespace
    declare_namespace(parent)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2094, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2064, in _handle_ns
    loader.load_module(packageName); module.__path__ = path
  File "/usr/lib64/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/root/odoo/odoo/__init__.py", line 60, in <module>
    import modules
  File "/root/odoo/odoo/modules/__init__.py", line 8, in <module>
    from . import db, graph, loading, migration, module, registry
  File "/root/odoo/odoo/modules/graph.py", line 13, in <module>
    import odoo.osv as osv
  File "/root/odoo/odoo/osv/__init__.py", line 4, in <module>
    import osv
  File "/root/odoo/odoo/osv/osv.py", line 4, in <module>
    from ..exceptions import except_orm
  File "/root/odoo/odoo/exceptions.py", line 15, in <module>
    from tools.func import frame_codeinfo
  File "/root/odoo/odoo/tools/__init__.py", line 8, in <module>
    from misc import *
  File "/root/odoo/odoo/tools/misc.py", line 16, in <module>
    import passlib.utils
ImportError: No module named passlib.utils
```
Current behavior: setup error

Expected behavior: successful install

Video/Screenshot link (optional):

**Comment by AyaYousef** [comment] 2017-04-17 06:52
I've the same issue

**Comment by repodevs** [comment] 2017-04-17 10:51
You can install passlib module using pip

```bash
sudo pip install passlib
```

**Comment by AyaYousef** [comment] 2017-04-17 11:35
@repodevs I did, but still I've the same problem

**Comment by zaneven** [comment] 2017-04-17 11:58
@repodevs I have installed that module, but it doesn't work

**Comment by pimodoo** [comment] 2017-04-20 10:10
@zaneven Hello, your problem maybe caused because your pip command is related to pip3 which is for python 3 and Odoo uses python 2. Could you please try to run 'pip2 install passlib' instead of 'pip install passlib' and if it works, you can run 'pip2 install -r requirements.txt'

**Comment by stellaf** [comment] 2017-04-22 11:17
you edit the file odoo-bin, and change it to #!/usr/bin/env /opt/odoo/virtualenv/odoo10/bin/python    In this way, the odoo knows which python to use.

**Comment by zaneven** [comment] 2017-04-28 02:44
@pimodoo I tried what you said. but this time it became "No module named yaml" 

`pip install yaml`

` Could not find a version that satisfies the requirement yaml (from versions: )
No matching distribution found for yaml
`

**Comment by pimodoo** [comment] 2017-04-28 08:11
Hello, as you pip command is related to python 3, you should always use the command pip2.

The library yaml, is so available by running 'pip2 install PyYAML' and if you want to install all dependency at once, you have to go in your odoo directory and run 'pip2 install -r requirements.txt' and all needed library will be installed.

**Closed** 2017-04-28 08:57 UTC

**Comment by EranGrin** [comment] 2017-04-29 16:26
Hello, I also had the same issue and finally, I found the issue and the solution.
The problem at my end was that I had python 3.6 installed on my mac already before I started the installation of odoo.
Solution 
1. uninstall python3.6 and install python2.7
2. python was installed via macports, since brew installation path is /usr/local/bin/pyhon..... long story short,
try doing this:
   brew install python
   brew linkapps python
   brew link --overwrite python 

This should do the work

**Comment by erpnedir** [comment] 2017-08-28 05:00
I go through this thead but I come up with this error on MacOsX Sierra.

clang -fno-strict-aliasing -fno-common -dynamic -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DHAVE_SASL -DHAVE_TLS -DHAVE_LIBLDAP_R -DHAVE_LIBLDAP_R -DLDAPMODULE_VERSION=2.4.27 -IModules -I/usr/include -I/usr/include/sasl -I/usr/local/include -I/usr/local/include/sasl -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c Modules/LDAPObject.c -o build/temp.macosx-10.12-x86_64-2.7/Modules/LDAPObject.o
    Modules/LDAPObject.c:18:10: fatal error: 'sasl.h' file not found
    #include <sasl.h>
             ^
    1 error generated.
    error: command 'clang' failed with exit status 1

**Comment by OHR7** [comment] 2017-09-12 18:07
Hi Ithink the issue is that you didnt start the virtual env in which you installed the modules

**Comment by loveismyside** [comment] 2017-09-27 11:57
I have some problem please how to solve thanks
Traceback (most recent call last):
  File "./odoo-bin", line 5, in <module>
    __import__('pkg_resources').declare_namespace('odoo.addons')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2081, in declare_namespace
    declare_namespace(parent)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2097, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2046, in _handle_ns
    loader.load_module(packageName)
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/var/www/html/Odoo10Tutorial/odoo/odoo/__init__.py", line 60, in <module>
    import modules
  File "/var/www/html/Odoo10Tutorial/odoo/odoo/modules/__init__.py", line 8, in <module>
    from . import db, graph, loading, migration, module, registry
  File "/var/www/html/Odoo10Tutorial/odoo/odoo/modules/graph.py", line 13, in <module>
    import odoo.osv as osv
  File "/var/www/html/Odoo10Tutorial/odoo/odoo/osv/__init__.py", line 4, in <module>
    import osv
  File "/var/www/html/Odoo10Tutorial/odoo/odoo/osv/osv.py", line 4, in <module>
    from ..exceptions import except_orm
  File "/var/www/html/Odoo10Tutorial/odoo/odoo/exceptions.py", line 15, in <module>
    from tools.func import frame_codeinfo
  File "/var/www/html/Odoo10Tutorial/odoo/odoo/tools/__init__.py", line 8, in <module>
    from misc import *
  File "/var/www/html/Odoo10Tutorial/odoo/odoo/tools/misc.py", line 22, in <module>
    import werkzeug.utils
ImportError: No module named werkzeug.utils

**Comment by canaan-yz** [comment] 2017-10-02 04:55
I install another py2.7 via brew.  The same error occurred when run odoo with "python odoo.bin " .Because this Python owns to MacOS,not brew's. "passlib" happened to be the first to detect,so package is not installed, either other packeges.It worked when adjust command with" python2 odoo.bin".check path of "python -V ,pip -V ,python2 -V, pip2 -V",make sure use the correct python&pip interpreter.

**Comment by william-andre** [comment] 2018-11-16 15:39
You can also easily change between multiple versions of python without having to uninstall anything. More info [here](https://linuxconfig.org/how-to-change-from-default-to-alternative-python-version-on-debian-linux)

**Comment by Ali-mughal** [comment] 2021-01-05 11:56
please activate the virtual environment the put the command. In my scenario its work.
