### ISSUE TITLE
Pager for Many2one pop-up

### ISSUE THREAD

**Issue by anandkansagra** [odoo/odoo#28975] opened 2018-11-23 05:13 UTC
Impacted versions:
10, 11, 12
For Community as well as Enterprise

Steps to reproduce:
Open any Many2one pop-up which has more than 160 records.
Firstly it will show 160 records only but there seem more than 160 records.
If we will apply any filter and remove that then it will show all records.

Current behaviour:
If there are more than 160 records than it will show 160 records only at first time

Expected behaviour:
Many2one pop-up will show all records for the first time in pager if it is available.

Video/Screenshot link (optional):
![1](https://user-images.githubusercontent.com/45279628/48929209-74060e00-ef0c-11e8-9524-6305d63288d9.gif)

**Comment by Yenthe666** [comment] 2018-11-23 07:03
If I'm not mistaken this was done by design within the framework for performance reasons.
@pedrobaeza do you remember?

**Comment by pedrobaeza** [comment] 2018-12-07 17:05
Yes, Yenthe, this was a design decision for avoiding to fetch all records in case you remove current filter for adding a new one, given the context. I agree sometimes can be confusing, but the "Search more..." option shouldn't be abused in normal flows for searching from the whole recordset. It's intended for only refine your search in case that there are more of the 7 displayed records.

There are modules in community for removing this restriction, but I don't recommend to bypass it for not hammering too much the server and look for other flows. If you need to use "Search more..." all the times, then you should switch for sure something in your processes.

Closing this as won't fix due to design decision.

**Closed by pedrobaeza** 2018-12-07 17:05 UTC
Labels: 10.0, 11.0, 12.0, Framework
