### ISSUE TITLE
[14.0 ] Uncaught TypeError: dom.addButtonLoadingEffect is not a function

### ISSUE THREAD

**Issue by fizcris** [odoo/odoo#67319] opened 2021-03-05 09:59 UTC
Since a couple of updates  (I think #63417) of odoo 14.0 (I am pulling the latest image from Docker Hub.) I cannot open the web editor anymore due to the following error when the editor button is clicked:

```
Uncaught TypeError: dom.addButtonLoadingEffect is not a function
http://xxxxxxx.com/web/content/7537-cf6a95b/1/web.assets_frontend_lazy.js:187
Rastreo de error:
TypeError: dom.addButtonLoadingEffect is not a function
    at Class._onActionMenuClick (http://xxxxxx.com/web/content/7537-cf6a95b/1/web.assets_frontend_lazy.js:187:269)
    at HTMLAnchorElement.<anonymous> (http://xxxxxxx.com/web/content/4070-608e817/1/web.assets_common_lazy.js:4666:11)
    at HTMLElement.dispatch (http://xxxxxx.com/web/content/4070-608e817/1/web.assets_common_lazy.js:1627:447)
    at HTMLElement.elemData.handle (http:/xxxx.com/web/content/4070-608e817/1/web.assets_common_lazy.js:1613:166)
````
Deleting the function call `const restore=dom.addButtonLoadingEffect(ev.currentTarget);` from the .js file and everything works again.... But this is just a workaround obviously.

I trace back the `addButtonLoadingEffect` function to the file `addons/web/static/src/js/core/dom.js` so I know for a fact that the .js file is in the server and the right function is there but somehow it is not being loaded/found... 
I have reloaded all the related modules [core, web, website] successfully but still no luck... I have tested runbot, and there are no problems whatsoever... obviously.

Can someone give some light on what is going on?

Regards.

I have asked my question [here](https://www.odoo.com/es_ES/forum/ayuda-1/uncaught-typeerror-dom-addbuttonloadingeffect-is-not-a-function-184013), but I think it´s closer to the development than the usability of oddo.

**Comment by pedrobaeza** [comment] 2021-03-05 10:01
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by fizcris** [comment] 2021-03-05 10:15
Hi Pedro, 

Thanks for the quick response. As I said, I have tested it in runbot, and no issues whatsoever. 

I have uninstalled all the custom/community modules and updated all the related ones [core, web, website]. And I think all the .js files are overwritten each module reload (correct?), but the issue is still present... Maybe something outdated in the DB can be affecting a .js file?

I am asking for a bit of guidance in what to do next.

**Comment by pedrobaeza** [comment] 2021-03-05 10:19
I'm afraid this issue tracker is not for that. You can ask these questions on forums.

A little tip: try upgrading your modules from command line.

**Closed by pedrobaeza** 2021-03-05 10:19 UTC
Labels: Need information

**Comment by fizcris** [comment] 2021-03-05 15:51
Solved by activating developer mode with assets.

**Comment by pedrobaeza** [comment] 2021-03-05 17:36
Then you have an incorrect JS asset that breaks everything when no on debug assets mode. Check JS console to see which one.

**Comment by fizcris** [comment] 2021-03-05 20:55
Thank you for the advice! Unfortunately same error on console on noDebug and debug mode (without assets):

```
Uncaught TypeError: dom.addButtonLoadingEffect is not a function
    at Class._onActionMenuClick (web.assets_frontend_lazy.js:187)
    at HTMLAnchorElement.<anonymous> (web.assets_common_lazy.js:4666)
    at HTMLElement.dispatch (web.assets_common_lazy.js:1627)
    at HTMLElement.elemData.handle (web.assets_common_lazy.js:1613)
_onActionMenuClick @ web.assets_frontend_lazy.js:187
(anonymous) @ web.assets_common_lazy.js:4666
dispatch @ web.assets_common_lazy.js:1627
elemData.handle @ web.assets_common_lazy.js:1613
```

To my knowledge, the file `addons/web/static/src/js/core/dom.js` is not being served when it is not in debug with assets mode... It is not a major issue... but I would like to understand to increase my knowledge about odoo. 

It might be as well related to the docker hub odoo image... but it is a lot of effort debugging odoo inside a container for this having this quick fix, I will stick with it for now..

**Comment by fizcris** [comment] 2021-03-08 18:36
As easy as click in Regenerate Assets Bundles
