### ISSUE TITLE
Display filter on Optional products in quotations and orders reports

### ISSUE THREAD

**Issue by maisim** [odoo/odoo#66789] opened 2021-02-25 07:53 UTC
https://github.com/odoo/odoo/blob/5d4650c22899a59d0cb5e4f19fe1da94a48e29f9/addons/sale_management/report/sale_report_templates.xml#L5

Context : 
+ odoo12 to 14 (maybe others)
+ in Pdf report of invoice or order

Does someone know why optional products are displayed only if state of document is draft or sent ?
I can't understand the logic

**Comment by Yenthe666** [comment] 2021-02-27 10:38
@maisim because your customer is only adding optional products to the quotation before it is confirmed/signed?
CC @pedrobaeza

**Comment by pedrobaeza** [comment] 2021-02-27 15:25
Once the quotation has been confirmed, optional products don't make sense in most use cases, If in your use case, it makes sense, then you can develop a module that overrides that condition and show in the report that part. But there are plenty places (like in the portal) where a similar logic is applied, so you will get to check them.

Closing as no bug, but functional use case.

**Closed by pedrobaeza** 2021-02-27 15:25 UTC

**Comment by maisim** [comment] 2021-03-01 13:18
It make sense, thank you for taking the time to clarify this point.
