### ISSUE TITLE
PoS Changes counld not be saved error

### ISSUE THREAD

**Issue by leiw324** [odoo/odoo#57592] opened 2020-09-13 14:17 UTC
Impacted versions: Odoo 13.0

Steps to reproduce: After installed PoS, I try to Validate one product payment, but displayed error.

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/33790160/93020280-abc4d500-f60e-11ea-97c5-92cd1ccd0ea2.png)

**Comment by pedrobaeza** [comment] 2020-09-14 06:47
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by leiw324** [comment] 2020-09-14 11:26
Hello,

Sorry, where is click on the blue door icon of the version row?

Thanks

**Comment by leiw324** [comment] 2020-09-14 11:28
Hello,

No problem:

![image](https://user-images.githubusercontent.com/33790160/93080560-74166580-f6c0-11ea-85f8-0637603d7eac.png)

**Comment by leiw324** [comment] 2020-09-14 11:29
After Validate will display this error

**Comment by pedrobaeza** [comment] 2020-09-14 11:34
But is reproducible on runbot?

**Comment by leiw324** [comment] 2020-09-15 02:45
> Hello,
> 
> No problem:
> 
> ![image](https://user-images.githubusercontent.com/33790160/93080560-74166580-f6c0-11ea-85f8-0637603d7eac.png)

In runbot was no problem.

**Comment by pedrobaeza** [comment] 2020-09-15 07:19
Then it's something on your side, so nothing that we can't do here.

Try to update your source code and update modules in your DB, or start from a fresh one if possible. Closing then as no Odoo issue.

**Closed by pedrobaeza** 2020-09-15 07:19 UTC
Labels: Need information

**Comment by leiw324** [comment] 2020-09-15 14:41
Hello,

I just installed Odoo, but still have same issue, please help.

Thanks

**Comment by pedrobaeza** [comment] 2020-09-15 16:15
Please ask for that help in forums.

**Comment by leiw324** [comment] 2020-09-15 17:31
I know what happened, thanks.
