### ISSUE TITLE
[l10n_generic_auto_transfer_demo]: Wrong external id used for account.transfer.model demo data

### ISSUE THREAD

**Issue by hareshjupical** [odoo/odoo#49173] opened 2020-04-08 07:14 UTC
Impacted versions: V13 Enterprise

Steps to reproduce: Create any V13 ent fresh database with demo data and then install the module "Account Automatic Transfers Demo Data" (l10n_generic_auto_transfer_demo). On installation time, it will giving you errors on log.

Current behavior: Account Automatic Transfers Demo Data Module not install correctly and not load demo data.

Expected behavior: Do not use wrong external ID for demo records or remove demo data from module

Please find the bellow trace back:

odoo.modules.loading: Module l10n_generic_auto_transfer_demo demo data failed to install, installed without demo data 
Traceback (most recent call last):
  File "/home/jupical/workspace/odoo/community/13.0/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/home/jupical/workspace/odoo/community/13.0/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jupical/workspace/odoo/community/13.0/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7f17d0073b70>, 'l10n_generic_coa.1_expense_rent')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jupical/workspace/odoo/community/13.0/odoo/tools/safe_eval.py", line 349, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/jupical/workspace/odoo/community/13.0/odoo/tools/convert.py", line 657, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/home/jupical/workspace/odoo/community/13.0/odoo/tools/convert.py", line 663, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/home/jupical/workspace/odoo/community/13.0/odoo/addons/base/models/ir_model.py", line 1671, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "</usr/local/lib/python3.6/dist-packages/decorator.py:decorator-gen-25>", line 2, in xmlid_lookup
  File "/home/jupical/workspace/odoo/community/13.0/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/jupical/workspace/odoo/community/13.0/odoo/addons/base/models/ir_model.py", line 1660, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: l10n_generic_coa.1_expense_rent

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jupical/workspace/odoo/community/13.0/odoo/tools/convert.py", line 712, in parse
    self._tag_root(de)
  File "/home/jupical/workspace/odoo/community/13.0/odoo/tools/convert.py", line 674, in _tag_root
    f(rec)
  File "/home/jupical/workspace/odoo/community/13.0/odoo/tools/convert.py", line 563, in _tag_record
    f_val = _eval_xml(self, field, env)
  File "/home/jupical/workspace/odoo/community/13.0/odoo/tools/convert.py", line 117, in _eval_xml
    return safe_eval(a_eval, idref2)
  File "/home/jupical/workspace/odoo/community/13.0/odoo/tools/convert.py", line 32, in <lambda>
    safe_eval = lambda expr, ctx={}: s_eval(expr, ctx, nocopy=True)
  File "/home/jupical/workspace/odoo/community/13.0/odoo/tools/safe_eval.py", line 372, in safe_eval
    pycompat.reraise(ValueError, ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr)), exc_info[2])
  File "/home/jupical/workspace/odoo/community/13.0/odoo/tools/pycompat.py", line 13, in reraise
    raise value.with_traceback(tb)
  File "/home/jupical/workspace/odoo/community/13.0/odoo/tools/safe_eval.py", line 349, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/jupical/workspace/odoo/community/13.0/odoo/tools/convert.py", line 657, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/home/jupical/workspace/odoo/community/13.0/odoo/tools/convert.py", line 663, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/home/jupical/workspace/odoo/community/13.0/odoo/addons/base/models/ir_model.py", line 1671, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "</usr/local/lib/python3.6/dist-packages/decorator.py:decorator-gen-25>", line 2, in xmlid_lookup
  File "/home/jupical/workspace/odoo/community/13.0/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/jupical/workspace/odoo/community/13.0/odoo/addons/base/models/ir_model.py", line 1660, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: <class 'ValueError'>: "External ID not found in the system: l10n_generic_coa.1_expense_rent" while evaluating
"[ref('l10n_generic_coa.1_expense_rent')]"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jupical/workspace/odoo/community/13.0/odoo/modules/loading.py", line 84, in load_demo
    load_data(cr, idref, mode, kind='demo', package=package, report=report)
  File "/home/jupical/workspace/odoo/community/13.0/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/home/jupical/workspace/odoo/community/13.0/odoo/tools/convert.py", line 736, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/jupical/workspace/odoo/community/13.0/odoo/tools/convert.py", line 803, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/jupical/workspace/odoo/community/13.0/odoo/tools/convert.py", line 721, in parse
    exc_info[2]
  File "/home/jupical/workspace/odoo/community/13.0/odoo/tools/pycompat.py", line 13, in reraise
    raise value.with_traceback(tb)
  File "/home/jupical/workspace/odoo/community/13.0/odoo/tools/convert.py", line 712, in parse
    self._tag_root(de)
  File "/home/jupical/workspace/odoo/community/13.0/odoo/tools/convert.py", line 674, in _tag_root
    f(rec)
  File "/home/jupical/workspace/odoo/community/13.0/odoo/tools/convert.py", line 563, in _tag_record
    f_val = _eval_xml(self, field, env)
  File "/home/jupical/workspace/odoo/community/13.0/odoo/tools/convert.py", line 117, in _eval_xml
    return safe_eval(a_eval, idref2)
  File "/home/jupical/workspace/odoo/community/13.0/odoo/tools/convert.py", line 32, in <lambda>
    safe_eval = lambda expr, ctx={}: s_eval(expr, ctx, nocopy=True)
  File "/home/jupical/workspace/odoo/community/13.0/odoo/tools/safe_eval.py", line 372, in safe_eval
    pycompat.reraise(ValueError, ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr)), exc_info[2])
  File "/home/jupical/workspace/odoo/community/13.0/odoo/tools/pycompat.py", line 13, in reraise
    raise value.with_traceback(tb)
  File "/home/jupical/workspace/odoo/community/13.0/odoo/tools/safe_eval.py", line 349, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/jupical/workspace/odoo/community/13.0/odoo/tools/convert.py", line 657, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/home/jupical/workspace/odoo/community/13.0/odoo/tools/convert.py", line 663, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/home/jupical/workspace/odoo/community/13.0/odoo/addons/base/models/ir_model.py", line 1671, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "</usr/local/lib/python3.6/dist-packages/decorator.py:decorator-gen-25>", line 2, in xmlid_lookup
  File "/home/jupical/workspace/odoo/community/13.0/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/jupical/workspace/odoo/community/13.0/odoo/addons/base/models/ir_model.py", line 1660, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
odoo.tools.convert.ParseError: "<class 'ValueError'>: "External ID not found in the system: l10n_generic_coa.1_expense_rent" while evaluating
"[ref('l10n_generic_coa.1_expense_rent')]"" while parsing /home/jupical/workspace/odoo/enterprise/13.0/l10n_generic_auto_transfer_demo/data/data.xml:2, near
<odoo noupdate="1">
    <record id="auto_transfer_journal" model="account.journal">
        <field name="company_id" ref="base.main_company"/>
        <field name="name">IFRS Automatic Transfers</field>
        <field name="code">IFRS</field>
        <field name="type">general</field>
        <field name="show_on_dashboard" eval="False"/>
    </record>

    <record id="monthly_model" model="account.transfer.model">
        <field name="name">Monthly IFRS rent expense transfer</field>
        <field name="date_start" eval="time.strftime('%Y-01-01')"/>
        <field name="frequency">month</field>
        <field name="journal_id" ref="auto_transfer_journal"/>
        <field name="account_ids" model="account.account" eval="[ref('l10n_generic_coa.1_expense_rent')]"/>
    </record>
    <record id="monthly_model_line_1" model="account.transfer.model.line">
        <field name="transfer_model_id" ref="monthly_model"/>
        <field name="account_id" ref="l10n_generic_coa.1_expense_rd"/>
        <field name="percent" eval="35.0"/>
    </record>
    <record id="monthly_model_line_2" model="account.transfer.model.line">
        <field name="transfer_model_id" ref="monthly_model"/>
        <field name="account_id" ref="l10n_generic_coa.1_expense_sales"/>
        <field name="percent" eval="65.0"/>
    </record>

    <record id="yearly_model" model="account.transfer.model">
        <field name="name">Yearly liabilites auto transfers</field>
        <field name="date_start" eval="time.strftime('%Y-01-01')"/>
        <field name="frequency">year</field>
        <field name="journal_id" ref="auto_transfer_journal"/>
        <field name="account_ids" model="account.account" eval="[ref('l10n_generic_coa.1_current_liabilities'),ref('l10n_generic_coa.1_payable')]"/>
    </record>
    <record id="yearly_model_line_1" model="account.transfer.model.line">
        <field name="transfer_model_id" ref="yearly_model"/>
        <field name="account_id" ref="l10n_generic_coa.1_payable"/>
        <field name="percent" eval="77.5"/>
    </record>
    <record id="yearly_model_line_2" model="account.transfer.model.line">
        <field name="transfer_model_id" ref="yearly_model"/>
        <field name="account_id" ref="l10n_generic_coa.1_non_current_liabilities"/>
        <field name="percent" eval="22.5"/>
    </record>
</odoo>

Video/Screenshot link (optional): 

Please find the attached screenshots:
![error_3](https://user-images.githubusercontent.com/48671325/78755452-d1322080-7996-11ea-88d4-3afbd46df126.png)
![error_2](https://user-images.githubusercontent.com/48671325/78755460-d42d1100-7996-11ea-8190-c8cb72edff44.png)
![error_1](https://user-images.githubusercontent.com/48671325/78755462-d55e3e00-7996-11ea-9e4a-1adcbe489631.png)

**Comment by pedrobaeza** [comment] 2020-04-08 07:42
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem on an standard Odoo (without extra addons) and any possible tip about what's going on.

**Closed by pedrobaeza** 2020-04-08 07:42 UTC

**Comment by hareshjupical** [comment] 2020-04-08 08:45
We have tried with freshDB without any custom module and then also error coming. Also i have checked that the external ID used in odoo demo data, that is not located in mentioned module. They are using external ID which is not available in whole odoo community 13 and odoo enterprise 13.
