### ISSUE TITLE
[12] Inconsistency b/w today marker in Datetime Picker

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#28702] opened 2018-11-14 19:26 UTC
Impacted versions: 12

Steps to reproduce: 
See gif for details
Current Date 15 Nov (Correct timezone in User Preference)

Current behavior: Inconsistent Date (It display 14th when date is selected)

Expected behavior: It should same (15 Nov in current Case)

Video/Screenshot link (optional):
![peek 2018-11-15 00-55](https://user-images.githubusercontent.com/16624719/48507175-31d82f00-e871-11e8-8655-a2ded96b6bb6.gif)

**Comment by sswapnesh** [comment] 2018-11-15 14:58
Will add more detailed description with screenshots.

**Comment by sswapnesh** [comment] 2018-11-28 18:44
> Sorry, but I don't get the problem.

Current Datetime at My location in Timezone:  29 Dec 12:11 am (+05:30)
UTC Datetime: 28 Dec 6:41 pm


Create Event and Click on Start Date field
![screenshot](https://user-images.githubusercontent.com/16624719/49173631-4127a400-f36a-11e8-9481-a1bed56744a1.png)
Today Marker is on 29th --> Correct till now

Select any Date
![screenshot](https://user-images.githubusercontent.com/16624719/49174082-6ec11d00-f36b-11e8-9a4c-e7f0bd930c55.png)

Click again to choose new date --> Today Marker is on 28th which is wrong
![screenshot](https://user-images.githubusercontent.com/16624719/49174111-80a2c000-f36b-11e8-82a1-e66584b15de0.png)

**Comment by pedrobaeza** [comment] 2018-11-28 23:59
Uhm, difficult thing to reproduce, but I guess there can be a problem showing this in locale tz. I'm tagging this, but one more question. What is the timezone in your browser?

**Comment by gdgellatly** [comment] 2019-01-14 23:52
Impacted versions: 12.0 - probably prior

Related are #13440 and the date part is essentially a duplicate of #28702 but adds extra information and workaround as well as related problem. OK I'm adding to this issue.

Steps to reproduce: - note correlation is not necessarily causation here
Good luck, I suppose if you are in Europe you can try either side of midnight, I'm GMT +13.
You get one shot at reproducing it or else you need to create/login as another user because once a user has a timezone set, it will error trying to unset it if you are the logged in user.
Using sale orders with sale order dates installed is a good candidate.

When the users timezone is not set: (I don't know what happens in a mismatch, didn't dig that deep)

- Dates display using **browser** timezone.
- Default dates that don't use js (e.g. clicking CREATE in Sales Order) - use **browsers** timezone for fields.Date.context_today.
- Datepicker default dates use the **users** timezone in preferences (and by default this is not set so tend to UTC).
- Chatter displays in **Browser** timezone.
- Functions in chatter that set a default for a field using fields.Date.context_today use the **Users** timezone (and by default this is not set so tend to UTC) - for example Schedule Activity deadline date.

Expected behavior:
Consistent display and defaults. If I had to guess it feels like context["tz"] is not being passed.

Workaround - Give user a timezone that matches browser will resolve for many people, too bad if you travel.

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment] 2019-01-15 13:33
Note: I was (Didn't tried with new updates) able to Reproduce this with correct timezone in user. (With Brussels and Indian timezone)

**Comment by gdgellatly** [comment] 2019-01-15 13:52
@sswapnesh yes, I could as well, why I moved my issue. Mine doesn't replicate when timezones set.

**Comment by C3POdoo** [comment] 2023-03-30 13:05
Dear @sswapnesh,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._

**Closed by C3POdoo** 2023-03-30 13:05 UTC
Labels: Services, 12.0
