### ISSUE TITLE
[9.0][Online][event_sale] creating sales-orders for event-products doesn´t work 

### ISSUE THREAD

**Issue by schmidtwastl** [odoo/odoo#9168] opened 2015-10-21 00:00 UTC
Reproduce:
sales->sales orders->create sales order -> On the order lines add a product which is linked to an event -> save -> confirm -> now should open the registration wizard, but: error   

```
Error: send_commands to 'event_registration_ids' receive a non command value.
[{"registration_id":5,"name":"Administrator","event_id":3,"phone":"23445667763","sale_order_line_id":5,"email":"***@***.com","event_ticket_id":5}]

https://backend100.odoo.com/web/content/390-b8625b5/web.assets_backend.js:3740
Traceback:
AbstractManyField<.send_commands/</<@https://backend100.odoo.com/web/content/390-b8625b5/web.assets_backend.js:3740:194
Mutex.prototype.exec/<@https://backend100.odoo.com/web/content/387-0784a6d/web.assets_common.js:2709:136
.Deferred/promise.then/</</<@https://backend100.odoo.com/web/content/387-0784a6d/web.assets_common.js:650:678
jQuery.Callbacks/fire@https://backend100.odoo.com/web/content/387-0784a6d/web.assets_common.js:644:281
jQuery.Callbacks/self.add@https://backend100.odoo.com/web/content/387-0784a6d/web.assets_common.js:645:467
.Deferred/promise.then/</<@https://backend100.odoo.com/web/content/387-0784a6d/web.assets_common.js:650:631
.each@https://backend100.odoo.com/web/content/387-0784a6d/web.assets_common.js:473:758
.Deferred/promise.then/<@https://backend100.odoo.com/web/content/387-0784a6d/web.assets_common.js:650:553
.Deferred@https://backend100.odoo.com/web/content/387-0784a6d/web.assets_common.js:651:189
.Deferred/promise.then@https://backend100.odoo.com/web/content/387-0784a6d/web.assets_common.js:650:518
Mutex.prototype.exec@https://backend100.odoo.com/web/content/387-0784a6d/web.assets_common.js:2709:98
AbstractManyField<.send_commands/<@https://backend100.odoo.com/web/content/390-b8625b5/web.assets_backend.js:3739:1115
_.forEach@https://backend100.odoo.com/web/content/387-0784a6d/web.assets_common.js:12:558
AbstractManyField<.send_commands@https://backend100.odoo.com/web/content/390-b8625b5/web.assets_backend.js:3739:1077
AbstractManyField<.set_value@https://backend100.odoo.com/web/content/390-b8625b5/web.assets_backend.js:3737:1
OdooClass.extend/</prototype[name]</<@https://backend100.odoo.com/web/content/387-0784a6d/web.assets_common.js:2532:556
FieldX2Many<.set_value@https://backend100.odoo.com/web/content/390-b8625b5/web.assets_backend.js:3750:854
OdooClass.extend/</prototype[name]</<@https://backend100.odoo.com/web/content/387-0784a6d/web.assets_common.js:2532:556
FormView<.load_record/<@https://backend100.odoo.com/web/content/390-b8625b5/web.assets_backend.js:3545:235
_.forEach@https://backend100.odoo.com/web/content/387-0784a6d/web.assets_common.js:12:650
_.mixin/</_.prototype[name]@https://backend100.odoo.com/web/content/387-0784a6d/web.assets_common.js:69:521
FormView<.load_record@https://backend100.odoo.com/web/content/390-b8625b5/web.assets_backend.js:3545:127
Events<.trigger@https://backend100.odoo.com/web/content/387-0784a6d/web.assets_common.js:2616:166
EventDispatcherMixin<.trigger@https://backend100.odoo.com/web/content/387-0784a6d/web.assets_common.js:2618:636
FormView<.load_defaults/<@https://backend100.odoo.com/web/content/390-b8625b5/web.assets_backend.js:3548:212
.Deferred/promise.then/</</<@https://backend100.odoo.com/web/content/387-0784a6d/web.assets_common.js:650:678
jQuery.Callbacks/fire@https://backend100.odoo.com/web/content/387-0784a6d/web.assets_common.js:644:281
jQuery.Callbacks/self.fireWith@https://backend100.odoo.com/web/content/387-0784a6d/web.assets_common.js:649:198
.Deferred/</deferred[tuple[0]]@https://backend100.odoo.com/web/content/387-0784a6d/web.assets_common.js:651:31
jQuery.Callbacks/fire@https://backend100.odoo.com/web/content/387-0784a6d/web.assets_common.js:644:281
jQuery.Callbacks/self.fireWith@https://backend100.odoo.com/web/content/387-0784a6d/web.assets_common.js:649:198
.Deferred/promise.then/</</<@https://backend100.odoo.com/web/content/387-0784a6d/web.assets_common.js:650:849
jQuery.Callbacks/fire@https://backend100.odoo.com/web/content/387-0784a6d/web.assets_common.js:644:281
jQuery.Callbacks/self.fireWith@https://backend100.odoo.com/web/content/387-0784a6d/web.assets_common.js:649:198
.Deferred/promise.then/</</<@https://backend100.odoo.com/web/content/387-0784a6d/web.assets_common.js:650:849
jQuery.Callbacks/fire@https://backend100.odoo.com/web/content/387-0784a6d/web.assets_common.js:644:281
jQuery.Callbacks/self.fireWith@https://backend100.odoo.com/web/content/387-0784a6d/web.assets_common.js:649:198
done@https://backend100.odoo.com/web/content/387-0784a6d/web.assets_common.js:1040:86
.send/callback@https://backend100.odoo.com/web/content/387-0784a6d/web.assets_common.js:1060:15
```

**Comment by manutvarghese** [comment] 2015-11-30 13:23
How you solved this error?

**Comment by armandog** [comment] 2016-03-12 05:02
I'm having the same error, is there a workaround?

**Comment by pedrobaeza** [comment] 2018-04-06 00:42
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-04-06 00:42 UTC
Labels: 9.0, Services
