### ISSUE TITLE
install apps

### ISSUE THREAD

**Issue by almustafago** [odoo/odoo#23082] opened 2018-02-15 09:57 UTC
Impacted versions: odoo v11 >> i remove ecommerce model , and after  i try to re-install it gives me this message

Steps to reproduce:
![install](https://user-images.githubusercontent.com/15360515/36250702-a40b251c-124f-11e8-9f03-c617b01fa676.PNG)

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment] 2018-02-15 11:48
Hi @almustafago,

What exactly do you mean with "i remove ecommerce model"? Do you mean you've clicked on deleting the app and then clicked on install again?

**Comment by sswapnesh** [comment] 2018-02-15 16:30
Hello @almustafago 
Could you please update your odoo Source code and try again?
Duplicate of #21905 and It has has been resolved in Commit 9f583717e574795f8bd241fea44bad1a59253a66

**Comment by almustafago** [comment] 2018-02-15 16:49
no i make just uninstall and  model data file still avilable in odoo directory

**Comment by Yenthe666** [comment] 2018-02-15 17:02
@almustafago you really need to add more clear information or nobody can help you. Can you reproduce it on runbot? Have you updated your local Odoo? What do you call make uninstall? What do you mean with model data file?

**Comment by almustafago** [comment] 2018-02-17 07:12
ok , i have not update odoo -
unistall it meains unistall model in apps list -
model data it meains the model file that found in addons dircetory

**Comment by almustafago** [comment] 2018-02-17 10:23
@sswapnesh  still face the same problem after i add your amadement in websit dircetory

**Comment by Yenthe666** [comment] 2018-02-19 11:35
@almustafago please test this on the latest V11 (at runbot.odoo.com), we really can't reproduce the issue on the latest V11.

**Comment by almustafago** [comment] 2018-02-19 17:39
Hello dear thank you so much for your kindness.. Me be this bug cause I'm
use bitnami Odoo

بتاريخ ١٩‏/٠٢‏/٢٠١٨ ١٤:٣٥، كتب "Yenthe V.G" <notifications@github.com>:

**Comment by Yenthe666** [comment] 2018-02-20 07:05
@d-fence do you happen to have a bitname instance somewhere to test if it is platform/OS dependant?

**Comment by d-fence** [comment] 2018-02-20 07:53
@Yenthe666 sorry, I don't have such an instance.

**Comment by sswapnesh** [comment] 2018-06-07 18:13
@Yenthe666  @almustafago  I cannot reproduce the same in Bitnami.  or may be duplicate of #25078

**Comment by JayVora-SerpentCS** [comment] 2018-06-07 18:22
Suspect that, its due to either missing models(by the absence of website module) or access to files. @almustafago you must share server log which will speak of the query being fired.

**Comment by Yenthe666** [comment] 2018-06-07 19:06
@sswapnesh so you tried this on the latest Bitname release and everything works fine at your end?

**Comment by sswapnesh** [comment] 2018-06-08 01:56
Yes @Yenthe666 , I tried it on Latest Bitnami release, You can Reinstall `website_sale`, But If you have removed `website` module also, You will get error during installing  `website_sale` as mentioned in  #25078

**Comment by Yenthe666** [comment] 2018-06-08 07:45
Then I believe we can close this one off and continue on 25078, as that is a confirmed bug.

**Closed by Yenthe666** 2018-06-08 07:45 UTC
Labels: 11.0
