### ISSUE TITLE
E-Commerce categories sorting problem

### ISSUE THREAD

**Issue by bariserdogan** [odoo/odoo#25535] opened 2018-06-29 08:04 UTC
Impacted versions: Odoo V11

Steps to reproduce: Website -> Configuration -> e-commerce categories 

Current behavior: 
When I drag and drop more than once, when I left this page without refreshing the page, I went in and looked again and the category line was restored to its original state. 
What might be the cause of this?

Expected behavior:
I want the category line to stay as it is.

Video/Screenshot link (optional):

### **Before correction**
![kategori ekran alintisi 1](https://user-images.githubusercontent.com/17798258/42080390-3f0893e8-7b8b-11e8-8ffd-9dc09215c007.JPG)

### **After my correction**
![kategori ekran alintisi 2](https://user-images.githubusercontent.com/17798258/42080473-73b90618-7b8b-11e8-9443-a39a2a6e2381.JPG)

### **After turning off and on**
![kategori ekran alintisi 3](https://user-images.githubusercontent.com/17798258/42080479-794a6f54-7b8b-11e8-9dee-19c7d3f7b80c.JPG)

**Comment by pedrobaeza** [comment] 2018-06-29 11:05
This problem is not specific to that model, but a general issue with the widget "handle". It's being handled (sorry for the word game, hehe) in #10003, and in master it's already solved (although there are possible refinements). Unfortunately, this can't be solved on current version.

**Comment by pedrobaeza** [comment] 2018-06-29 11:05
Duplicate of #10003

**Comment by seb-odoo** [comment] 2018-06-29 11:15
@pedrobaeza be careful when closing related issues.

For the fix to work, the sequence field must be declared as invisible in the form view (the form that is opened when editable= is not set).
See https://github.com/odoo/odoo/commit/b2c1d5ede2254e13bea32451faefa28a6eddcd4c#diff-72ec671833aeb837f26b98fcffc8e4aaR79

This is a "bug" of the framework that should be fixed separately.

Until that is fixed, it is not guaranteed every handle sequence will be fixed:

- every handle inside a list with editable= should be fixed
- those which don't have editable won't be fixed until we add the sequence field in the form (if it's not there yet)

I only made sure invoice and sale order were fixed, not the others.

In this particular case it might be fine if there is editable, I did not check. I'm just raising warning to not auto-close before making sure.

**Comment by pedrobaeza** [comment] 2018-06-29 11:34
@seb-odoo thanks for the warning. Does it serves if it's not invisible?

https://github.com/odoo/odoo/blob/8643175d00fb8ac418af15273cdbce32f9946c50/addons/website_sale/views/product_views.xml#L155

**Comment by seb-odoo** [comment] 2018-06-29 11:44
@pedrobaeza yes it's ok if the field is visible too, the default will be calculated the same way. But if it's visible the user can also change the value manually to put it wherever he wants on the list.

But he will only be able to place it correctly manually if he knows about the sequence of the other elements, which he will probably not know if there is a handle widget since then the value is not displayed, so this is a strange use case...

It's better to test the use case than relying on the code, maybe this is not even the form that is used in the particular case.

**Comment by pedrobaeza** [comment] 2018-06-29 11:52
Tried on master runbot (http://343600-master-49edee.runbot17.odoo.com/web#action=892&model=product.public.category&view_type=list&menu_id=419), when you add a new public category, that form is presented and you have the occasion to put the sequence. If left to 0, then it's sorted at the beginning, but when you drag in the list form to any of the positions, the sorting is respected, so I think this solves indeed the issue.

**Comment by seb-odoo** [comment] 2018-06-29 12:56
I tested too and it seems to just be always 0? It should be -1 then because the first element is already 0.

I checked and indeed in this case the model is not aware of its parent list, so it's not able to compute the correct default value.

It's not a big deal since the field is visible, but it would be nice if the default value was working here too.

**Comment by seb-odoo** [comment] 2018-10-10 14:29
PR in progress fixing the default value issue: #27634

**Comment by seb-odoo** [comment] 2020-02-28 19:10
Not sure why it didn't become closed, but this resolves it https://github.com/odoo/odoo/commit/25025a886c3095d2fae32bc936e0cbf2080a6236

**Closed by seb-odoo** 2020-02-28 19:10 UTC
Labels: 11.0, Framework, Wishlist
