### ISSUE TITLE
[Proposal] New labels

### ISSUE THREAD

**Issue by mreficent** [odoo/odoo#25020] opened 2018-06-01 12:17 UTC
I propose you the creation of the following tag labels:

 - For issues, a label tag "`PR`" would mean that the issue has already a opened PR that solves it.
This way, people attending new issues in Issues page, will know immediately what issues are not attended yet.

 - For PRs, a label tag "`Issue`" would mean that the PR solves an issue.
This way, PRs that solve issues could receive more reviews or will not stay forgotten or buried between the other PRs.

It's very simple. This means that maybe @Yenthe666 or @pedrobaeza will have more work, but I am sure they like to work.

What do you think?

**Comment by Yenthe666** [comment] 2018-06-01 12:48
Hi @mreficent,

Thanks for the suggestion and for thinking along, very welcomed!
I think it is not much extra effort to have more insight for the other side of the issue or a PR, so I think I like it.
@mart-e and @odony what do you two think? It could give us more ways of filtering and reporting plus it gives more insights to the people using the tracker.

Regards,
Yenthe

**Comment by pedrobaeza** [comment] 2018-06-01 14:29
When there's a PR, I usually close the associated issue, as having only 1 thing opened is enough, so I don't see that needed, but no great problem of having it.

**Comment by Yenthe666** [comment] 2018-06-01 14:32
@pedrobaeza the downside with that is that a PR might stay open very long while you already closed the issue off. Odoo is not as fast as OCA with merges/fixes. This may result in new issues for example, but in general both approaches have no real problem.

**Comment by mart-e** [comment] 2018-06-01 14:35
Hello,

I am not sure about this. The more complex the system gets, the harder it will be to keep consistent labels.
Maybe, a useful label could be something like "PR welcome" but the link between issues and PR is done by github, when you use the correct # reference, so I don't really see the point to add, yet another label.

I don't mind keeping the issue open when the PR is still unprocessed, especially if we are not sure the PR is the right way to fix the bug.
Opening both an issue and a PR at the same is, on the other hand, indeed counter productive (cf our [contribution](https://github.com/odoo/odoo/wiki/Contributing) page)

**Comment by pedrobaeza** [comment] 2018-06-01 14:38
About avoiding new duplicated issues, you know that people generally don't look before putting the issue, so the problem is going to be the same closing it or not, but I'm also OK in letting it opened, specially as Martin says when it's not clear that the PR is going to fix it.

**Comment by Yenthe666** [comment] 2018-06-01 14:41
Sounds good. @mart-e I like your "PR welcome" suggestion though, although we can label a lot of issues with that one I'm afraid.
I get what @mreficent wants though, being able to filter more thorough and have a cleaner link between issues/PR's.

**Comment by mart-e** [comment] 2018-06-01 15:00
@Yenthe666 if you can set on on half of the issues, then it is probably not a good label.
What I had in mind, was more for the issues where a problem is identified, we know what should be done in a PR but not a priority and an employee used the classic "I don't have the time to do it but can review a PR" :wink:, not just all the confirmed one. You see the difference?

Sorry but it looks like this issue/PR label request is more for management of its own issues, I am not convinced to help the general triage of issues/PR.

**Comment by antonylesuisse** [comment] 2018-06-08 09:04
You can refer one an other in the commit message or discussion. If you already have a PR please dont open an issue. So i'm against adding those tags.

**Closed by antonylesuisse** 2018-06-08 09:04 UTC
Labels: RFC
