### ISSUE TITLE
[11.0] Taxes missing in expense by mail

### ISSUE THREAD

**Issue by Vartkat** [odoo/odoo#29014] opened 2018-11-25 21:20 UTC
Impacted versions: 11 CE (hr_expense module)

Steps to reproduce:
- Expense configuration-> with email
- Create a (template) product with account and taxes and an internal short code for email
- Send email to mail address with object = [code] blabla 123.45

Current behavior:
Expense is well created when mail is received, amount is the right amount, account is the account of the template product, **but taxes are not there **
Expected behavior:

Taxes should be the ones setup in the template product.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2019-11-17 23:12
I'm not able to reproduce this problem in my side. Can you please try on runbot and specify all the steps to reproduce it?

**Comment by Yenthe666** [comment] 2019-12-03 07:50
Hi there,

Since there has been no extra information in a while I'm closing this issue.
Don't hesitate to respond back with detailed information and then we'll reopen this issue.

Regards,
Yenthe

**Closed by Yenthe666** 2019-12-03 07:50 UTC
Labels: 11.0, Need information, Services
