### ISSUE TITLE
[10.0] Project.Task's Description cannot be saved

### ISSUE THREAD

**Issue by htoan04** [odoo/odoo#14394] opened 2016-11-18 19:48 UTC
Impacted versions:
10.0

Steps to reproduce:
- Edit any task of project
- Type any in task's description
- Then save

Current behavior:
Content field gets cleared, not saved

Expected behavior:
Content field should get saved

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment] 2016-11-21 05:48
Hi @htoan04,

Thank you for your report. This issue has already been reported (and confirmed) here https://github.com/odoo/odoo/issues/14351
Closing this since it is a duplicate.

Regards,
Yenthe

**Closed by Yenthe666** 2016-11-21 05:48 UTC
