### ISSUE TITLE
[12.0.x] Set payment method get error

### ISSUE THREAD

**Issue by nguyenquangtoan** [odoo/odoo#27813] opened 2018-10-15 15:32 UTC
Impacted versions:12.0.x

Steps to reproduce:Set payment method

Current behavior:Custom payment

Expected behavior:

Video/Screenshot link (optional):
![screen shot 2018-10-15 at 10 29 55 pm](https://user-images.githubusercontent.com/294521/46961071-222ac680-d0ca-11e8-984e-1551d193d880.png)
![screen shot 2018-10-15 at 10 30 15 pm](https://user-images.githubusercontent.com/294521/46961072-222ac680-d0ca-11e8-91f5-73bb4bc9668b.png)

**Comment by pedrobaeza** [comment] 2018-10-15 15:35
Please specify all the detailed steps for getting the problem.

**Comment by sswapnesh** [comment] 2018-10-15 15:57
I have seen this error and but was not able to Reproduce on fresh Install.

**Comment by sswapnesh** [comment] 2018-10-15 16:02
It is when `_get_manual_payment_acquirer` return[ blank record set ](https://github.com/odoo/odoo/blob/12.0/addons/payment/wizards/payment_acquirer_onboarding_wizard.py#L43) and [here](https://github.com/odoo/odoo/blob/12.0/addons/payment/wizards/payment_acquirer_onboarding_wizard.py#L125) trying to set value.

**Comment by pedrobaeza** [comment] 2018-10-15 16:51
But then it's a misconfiguration...

**Comment by sswapnesh** [comment] 2018-10-15 16:58
Or User belongs to New Company which does not have any Payment Acquirer yet.
I think Its better to check `manual_acquirer` before assigning value [here](https://github.com/odoo/odoo/blob/12.0/addons/payment/wizards/payment_acquirer_onboarding_wizard.py#L125).

**Comment by sswapnesh** [comment] 2018-12-05 16:59
I am able to Reproduce this on latest Runbot

**Comment by Yenthe666** [comment] 2019-04-09 06:18
@sswapnesh any chance you could give this one another test and make a video of it in the process?

**Comment by sswapnesh** [comment] 2019-04-09 17:09
@Yenthe666  This has been fixed in https://github.com/odoo/odoo/commit/16c1c89e46946a04499ac483d8546ac4b7d06c35 with PR https://github.com/odoo/odoo/pull/29608

**Comment by Yenthe666** [comment] 2019-04-09 18:46
Aha, thanks a lot!

**Closed by Yenthe666** 2019-04-09 18:46 UTC
Labels: 12.0, Need information
