### ISSUE TITLE
Odoo 10 Community Installation issue : logging session out 

### ISSUE THREAD

**Issue by AEK-BKF** [odoo/odoo#15102] opened 2017-01-17 14:33 UTC
Impacted versions: 10 (latest) on Windows 10

Steps to reproduce: Creation the first database (test) to connect to Odoo app

Current behavior: error :
WARNING ? odoo.http: Logged into database 'test', but dbfilter rejects it; logging session out.
NB: the database 'test' is created with 105 tables created too.

Expected behavior: create the database and redirect to Odoo application

Video/Screenshot link (optional):

**Comment by zeroheure** [comment] 2017-01-18 15:14
dbfilter is a parameter in odoo.conf  Did you change it ? It shouldn't be change unless in production mode. Normal value is `dbfilter = .*`

**Comment by felly** [comment] 2017-01-31 13:33
Maybe a duplicate of #11740

**Comment by pedrobaeza** [comment] 2018-05-09 00:17
Hi, this seems something related to your deployment (in concrete, with dbfilter), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/11.0/setup/install.html.

I'm closing this issue now.

**Closed by pedrobaeza** 2018-05-09 00:17 UTC
Labels: 10.0, Framework
