### ISSUE TITLE
Tabs for Sales & Invoicing do not render properly

### ISSUE THREAD

**Issue by wulaaf** [odoo/odoo#32251] opened 2019-03-29 13:47 UTC
Impacted versions:
12.0

Steps to reproduce:
Standard install of Odoo12.0 Community with Enterprise addons

Current behavior:
Tabs for Sales and Invoice do not render properly

Expected behavior:
Render properly

Video/Screenshot link (optional):
![Screenshot 2019-03-29 18 45 29](https://user-images.githubusercontent.com/22291306/55236969-e720e780-5252-11e9-80f4-b9eea716795a.png)
![Screenshot 2019-03-29 18 45 32](https://user-images.githubusercontent.com/22291306/55236970-e720e780-5252-11e9-9200-f13c3abbb944.png)
![Screenshot 2019-03-29 18 45 35](https://user-images.githubusercontent.com/22291306/55236971-e720e780-5252-11e9-8d78-682f8a4d3de9.png)

**Comment by pedrobaeza** [comment] 2019-03-29 15:16
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by wulaaf** [comment] 2019-03-29 21:07
Thanks for the quick response.

I will try to reproduce this in the runbot infrastructure and get back to you.

I'm using the docker image for odoo 12.0. I have not deployed any custom or community modules. Everything is as it came with the Community and Enterprise modules.

Muhammad Abdullah Abid
+92 321 201 3131

Sent from my OnePlus

________________________________

**Comment by wulaaf** [comment] 2019-03-30 09:38
Could it possibly be that the docker image hasn't been updated with #30771 or #3568?

**Comment by pedrobaeza** [comment] 2019-03-30 12:11
I'm not sure, but if not reproducible in runbot, then it's not directly a problem of Odoo itself. You can put an issue on odoo/docker about your last comment.

**Closed by pedrobaeza** 2019-03-30 12:11 UTC
Labels: Need information

**Comment by wulaaf** [comment] 2019-03-30 13:42
It's a docker issue.

ENV ODOO_VERSION 12.0
ARG ODOO_RELEASE=20190128
ARG ODOO_SHA=9e34aaed2eb1e7697aaf36767247dbf335e9fe7a

The release in the build file is from 20190128
