### ISSUE TITLE
Cannot see added products on POS Orderlines Screen

### ISSUE THREAD

**Issue by Musula** [odoo/odoo#70225] opened 2021-05-03 09:05 UTC
Impacted versions: 14

Odoo 14.0+e-20210502 (Enterprise Edition) 

Steps to reproduce:

Update odoo14 to Odoo 14.0+e-20210502 
Open a POS with restaurant configuration
Add item to order
Item not visible on the POS order lines screen
However the total order amount is visible
Current behavior:
Item not visible on the POS order lines screen

Browser Console error:

Directive t-foreach should always be used with a t-key! (in template: 'Orderline')

Expected behavior:
Item(s) added to an order should be visible on the POS order lines screen

Video/Screenshot link (optional):
![Blank product line on POS](https://user-images.githubusercontent.com/15103081/116858500-24f95280-ac07-11eb-86b0-06152f84f880.jpeg)

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment] 2021-05-03 09:06
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Musula** [comment] 2021-05-03 09:42
Hi,
Thanks for the response.
Unfortunately I am unable to reproduce the issue on runbot.
The issue occurred after updating my installation from Odoo 14.0+e-20210420 to 14.0+e-20210502

Upon tracing I noted the error is due to an update on the file OrderLine.xml file

 /usr/lib/python3/dist-packages/odoo/addons/point_of_sale/static/src/xml/Screens/ProductScreen/Orderline.xml

Removing / commenting the block of code below on the Orderline.xml resolves the error
---------------------
 <t t-if="props.line.get_lot_lines()">
                <ul class="info-list">
                    <t t-foreach="props.line.get_lot_lines()" t-as="lot">
                        <li>
                            SN <t t-esc="lot.attributes['lot_name']"/>
                        </li>
                    </t>
                </ul>
  </t>

---------------------
Thanks !

**Comment by pedrobaeza** [comment] 2021-05-03 09:44
Then it's seem something related to your deployment, with outdated code or third party modules, so it can't be solved here, so closing.

**Closed by pedrobaeza** 2021-05-03 09:44 UTC
Labels: Need information

**Comment by Musula** [comment] 2021-05-03 09:54
Okay. Thanks.
