### ISSUE TITLE
Missing Widget "html" Error while opening user settings.

### ISSUE THREAD

**Issue by shixiwang** [odoo/odoo#14226] opened 2016-11-09 08:01 UTC
I installed odoo 10 (1109 version) on a ubuntu 14.04 LTS machine. but when i open my user settings dialog, it shows that missing widget "html"
i tried reinstall many times , and create new database but none of that works.
could you please help me ? thank you.
![image](https://cloud.githubusercontent.com/assets/16421189/20130985/6a32d30c-a695-11e6-97c0-39a3d9cdd8bb.png)

**Comment by hisuley** [comment] 2016-11-09 08:46
same issue. HOW TO FIX IT?

**Comment by JKE-be** [comment] 2016-11-09 13:08
Hello @shixiwang , @hisuley 

I'm trying to reproduce your problem, but  I cannot :/

Can you give me more details.

Thanks

![image](https://cloud.githubusercontent.com/assets/4848797/20139357/bb2c2988-a696-11e6-8b9b-dcabd4669d4c.png)

**Comment by hisuley** [comment] 2016-11-10 03:29
@JKE-be
I followed the installation guide. Nothing special. Install directly from Ubuntu apt ( add deb http://nightly.odoo.com/10.0/nightly/deb/ ./  to sources.list )

**uname -a result:**
3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Python packages installed**
Warning: cannot find svn location for odoo==10.0-20161109
Babel==2.3.4
Chameleon==2.6.1
Jinja2==2.8
Mako==1.0.4
MarkupSafe==0.23
Pillow==2.3.0
PyChart==1.39
PyWebDAV==0.9.8
PyYAML==3.10
Pygments==1.6
SecretStorage==2.0.0
Werkzeug==0.9.4
XlsxWriter==0.5.2
ZSI==2.1-a1
apt-xapian-index==0.45
argparse==1.2.1
bzr==2.7.0dev1
chardet==2.0.1
colorama==0.2.5
configobj==4.7.2
decorator==4.0.10
docutils==0.12
ebaysdk==2.1.4
feedparser==5.2.1
gdata==2.0.18
gevent==1.1.2
greenlet==0.4.10
gyp==0.1
html5lib==0.999
httplib2==0.8
jcconv==0.2.3
keyring==3.5
launchpadlib==1.10.2
lazr.restfulclient==0.13.3
lazr.uri==1.0.3
lptools==0.2.0
lxml==3.6.4
meld3==0.6.10
mock==2.0.0
oauth==1.0.1
## FIXME: could not find svn URL in dependency_links for this package:
odoo==10.0-20161109
ofxparse==0.15
paramiko==1.10.1
passlib==1.6.5
pdftools==0.37
psutil==1.2.1
psycopg2==2.4.5
pyOpenSSL==0.13
pyPdf==1.13
pycrypto==2.6.1
pydot==1.0.28
pygobject==3.12.0
pygpgme==0.3
pyinotify==0.9.4
pyparsing==2.0.1
pyserial==2.6
python-apt==0.9.3.5ubuntu2
python-dateutil==1.5
python-debian==0.1.21-nmu2ubuntu2
python-ldap==2.4.10
python-openid==2.2.5
pytz==2012c
pyusb==0.4.3
pyxdg==0.25
reportlab==3.0
requests==2.2.1
roman==2.0.0
shadowsocks==2.8.2
simplejson==3.3.1
six==1.5.2
ssh-import-id==3.21
suds==0.4.1
supervisor==3.0b2
uTidylib==0.2
unittest2==0.5.1
urllib3==1.7.1
vatnumber==1.1
vobject==0.8.1c
wadllib==1.3.2
wheel==0.24.0
wsgiref==0.1.2
xlwt==0.7.5
zope.interface==4.0.5

**Comment by hisuley** [comment] 2016-11-10 03:42
@JKE-be Besides, i found another issue on the fresh installation of Odoo,.

When i click the Calendar App, it shows that:


 Uncaught TypeError: this.$buttons.off(...).destroy is not a function

https://erp.linkyee.com/web/content/441-ba9bcb6/web.assets_backend.js:2973
Traceback:
TypeError: this.$buttons.off(...).destroy is not a function
    at Class.destroy (https://erp.linkyee.com/web/content/441-ba9bcb6/web.assets_backend.js:2973:870)
    at Class.prototype.(anonymous function) [as destroy] (https://erp.linkyee.com/web/content/436-b729eac/web.assets_common.js:3009:559)
    at Class.destroy (https://erp.linkyee.com/web/content/441-ba9bcb6/web.assets_backend.js:1620:332)
    at https://erp.linkyee.com/web/content/441-ba9bcb6/web.assets_backend.js:1633:219
    at Function._.map._.collect (https://erp.linkyee.com/web/content/436-b729eac/web.assets_common.js:13:270)
    at Class.clear_action_stack (https://erp.linkyee.com/web/content/441-ba9bcb6/web.assets_backend.js:1633:159)
    at Array.<anonymous> (https://erp.linkyee.com/web/content/441-ba9bcb6/web.assets_backend.js:1627:140)
    at fire (https://erp.linkyee.com/web/content/436-b729eac/web.assets_common.js:541:299)
    at Object.fireWith [as resolveWith] (https://erp.linkyee.com/web/content/436-b729eac/web.assets_common.js:546:198)
    at Array.deferred.(anonymous function) (https://erp.linkyee.com/web/content/436-b729eac/web.assets_common.js:548:56)


@JKE-be Besides, i found another issue on the fresh installation of Odoo,.

When i click the Calendar App, it shows that:


 Uncaught TypeError: this.$buttons.off(...).destroy is not a function

https://erp.linkyee.com/web/content/441-ba9bcb6/web.assets_backend.js:2973
Traceback:
TypeError: this.$buttons.off(...).destroy is not a function
    at Class.destroy (https://erp.linkyee.com/web/content/441-ba9bcb6/web.assets_backend.js:2973:870)
    at Class.prototype.(anonymous function) [as destroy] (https://erp.linkyee.com/web/content/436-b729eac/web.assets_common.js:3009:559)
    at Class.destroy (https://erp.linkyee.com/web/content/441-ba9bcb6/web.assets_backend.js:1620:332)
    at https://erp.linkyee.com/web/content/441-ba9bcb6/web.assets_backend.js:1633:219
    at Function._.map._.collect (https://erp.linkyee.com/web/content/436-b729eac/web.assets_common.js:13:270)
    at Class.clear_action_stack (https://erp.linkyee.com/web/content/441-ba9bcb6/web.assets_backend.js:1633:159)
    at Array.<anonymous> (https://erp.linkyee.com/web/content/441-ba9bcb6/web.assets_backend.js:1627:140)
    at fire (https://erp.linkyee.com/web/content/436-b729eac/web.assets_common.js:541:299)
    at Object.fireWith [as resolveWith] (https://erp.linkyee.com/web/content/436-b729eac/web.assets_common.js:546:198)
    at Array.deferred.(anonymous function) (https://erp.linkyee.com/web/content/436-b729eac/web.assets_common.js:548:56)

**Comment by jeantinguelyawais** [comment] 2017-09-06 14:08
Hello,
 I have the same problem. 
 New installation from github with all the applications opened...
 What can I do?
Best regards.
Jean.

**Comment by jeantinguelyawais** [comment] 2017-09-06 14:14
Well, indeed activating the debug mode with assets disable the message....

**Comment by jeantinguelyawais** [comment] 2017-09-07 06:34
Well, when I want to install a new application the message is fired. I cant' install new applications. Very bad... What can I do?

**Comment by Yenthe666** [comment] 2018-01-26 10:09
Hi @shixiwang,

I'm closing this bug report as both me and @JKE-be cannot reproduce it anymore.
As for the other responses: this is about another issue, if you can still reproduce that then you're free to make a new bug report.

Regards,
Yenthe

**Closed by Yenthe666** 2018-01-26 10:09 UTC

**Comment by Reechee88** [comment] 2018-02-04 20:15
Same problem here

**Comment by Reechee88** [comment] 2018-02-04 20:21
After I cleared browser cache, it is solved

**Comment by sburns90** [comment] 2018-04-10 04:50
@Reechee88 
Thanks, clearing the browser cached fixed the problem for me as well.

**Comment by m4as** [comment] 2018-05-02 16:09
Same problem here (fresh docker containers)

Seems to happen when (at least) french translation is enabled and active for the profile, and you navigate from `Discuss` (`Message` in fr) tab to any another module tab.

Changing language to english seems to fix it.

**Comment by sushicodeur** [comment] 2019-12-11 11:08
Same problem docker container Odoo 12 with french translation active. When going from Message tab to another, get this error the first time. Click again and it's gone. 

```
Erreur:
Uncaught TypeError: this.$buttons.off(...).destroy is not a function

https://odoo.mydomain.com/web/content/1595-478ef35/web.assets_backend.js:2708
Retraçage :
TypeError: this.$buttons.off(...).destroy is not a function
    at Class.destroy (https://odoo.mydomain.com/web/content/1595-478ef35/web.assets_backend.js:2708:343)
    at Class.prototype.<computed> [as destroy] (https://odoo.mydomain.com/web/content/1594-1cebeb7/web.assets_common.js:3538:488)
    at Class._removeAction [as _super] (https://odoo.mydomain.com/web/content/1595-478ef35/web.assets_backend.js:484:334)
    at Class._removeAction (https://odoo.mydomain.com/web/content/1595-478ef35/web.assets_backend.js:508:310)
    at Class._removeAction (https://odoo.mydomain.com/web/content/1594-1cebeb7/web.assets_common.js:3541:371)
    at Function._.each._.forEach (https://odoo.mydomain.com/web/content/1594-1cebeb7/web.assets_common.js:12:558)
    at Class._removeControllers (https://odoo.mydomain.com/web/content/1595-478ef35/web.assets_backend.js:484:518)
    at Class._pushController (https://odoo.mydomain.com/web/content/1595-478ef35/web.assets_backend.js:482:6)
    at https://odoo.mydomain.com/web/content/1595-478ef35/web.assets_backend.js:465:6
    at https://odoo.mydomain.com/web/content/1594-1cebeb7/web.assets_common.js:802:681
```

**Comment by AlanBell** [comment] 2019-12-19 21:38
you have probably uninstalled the web_editor module. Check that is installed.

**Comment by Fazryan** [comment] 2021-01-28 05:20
> you have probably uninstalled the web_editor module. Check that is installed.
> There might be more information on the javascript console, inspect the web page and see what it says.

I tried that step,
And this is the result;
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/fazryan/odoo12/odoo12/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/fazryan/odoo12/odoo12/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/fazryan/odoo12/odoo12/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/fazryan/odoo12/odoo12/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/home/fazryan/odoo12/odoo12/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/fazryan/odoo12/odoo12/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/fazryan/odoo12/odoo12/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/fazryan/odoo12/odoo12/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/home/fazryan/odoo12/odoo12/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 967, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 955, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/fazryan/odoo12/odoo12/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/home/fazryan/odoo12/odoo12/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/home/fazryan/odoo12/odoo12/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/fazryan/odoo12/odoo12/odoo/addons/base/models/ir_module.py", line 445, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/fazryan/odoo12/odoo12/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/fazryan/odoo12/odoo12/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/fazryan/odoo12/odoo12/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/home/fazryan/odoo12/odoo12/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/fazryan/odoo12/odoo12/odoo/modules/loading.py", line 179, in load_module_graph
    load_openerp_module(package.name)
  File "/home/fazryan/odoo12/odoo12/odoo/modules/module.py", line 368, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/home/fazryan/odoo12/odoo12/odoo/modules/module.py", line 82, in load_module
    exec(open(modfile, 'rb').read(), new_mod.__dict__)
  File "<string>", line 5, in <module>
  File "/odoo/odoo-server/addons/web_editor/models/__init__.py", line 5, in <module>
    from . import ir_qweb
  File "/odoo/odoo-server/addons/web_editor/models/ir_qweb.py", line 35, in <module>
    from odoo.tools.misc import babel_locale_parse
ImportError: cannot import name 'babel_locale_parse'

Please someone guide me,
Thank you in advance.

**Comment by JKE-be** [comment] 2021-01-28 08:59
Nothing linked to this issues.

Check that babel_local_parse is present in file odoo/odoo/tools/misc.py and try to restart your odoo server 

I invite you to open a new Issues if it persists ;)
