### ISSUE TITLE
Error when setting LDAP Authentication

### ISSUE THREAD

**Issue by annvt-dl** [odoo/odoo#40069] opened 2019-11-09 16:07 UTC
Impacted versions: 13

Steps to reproduce:
1/. In General Settings screen, check LDAP Authentication checkbox 
(the first time to configure LDAP Authenticate)
2/. Click Save button

Current behavior:
- Popup Odoo Error dialog.

Expected behavior:
- Can save successful and allow to configure LDAP server.

Video/Screenshot link (optional):
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo/odoo/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 1319, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 1311, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 393, in call_kw
    result = _call_kw_model_create(method, model, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 373, in _call_kw_model_create
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-168>", line 2, in create
  File "/opt/odoo/odoo/odoo/api.py", line 322, in _model_create_single
    return create(self, arg)
  File "/opt/odoo/odoo/addons/account/models/res_config_settings.py", line 156, in create
    return super(ResConfigSettings, self).create(values)
  File "<decorator-gen-3>", line 2, in create
  File "/opt/odoo/odoo/odoo/api.py", line 343, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo/odoo/odoo/models.py", line 3740, in create
    fields[0].determine_inverse(batch_recs)
  File "/opt/odoo/odoo/odoo/fields.py", line 1071, in determine_inverse
    self.inverse(records)
  File "/opt/odoo/odoo/odoo/fields.py", line 566, in _inverse_related
    target[field.name] = record_value[record]
  File "/opt/odoo/odoo/odoo/models.py", line 5573, in __setitem__
    return self._fields[key].__set__(self, value)
  File "/opt/odoo/odoo/odoo/fields.py", line 1040, in __set__
    records.write({self.name: write_value})
  File "/opt/odoo/odoo/addons/website/models/website.py", line 164, in write
    result = super(Website, self - public_user_to_change_websites).write(values)
  File "/opt/odoo/odoo/odoo/models.py", line 3507, in write
    field.write(self, vals[fname])
  File "/opt/odoo/odoo/odoo/fields.py", line 1923, in write
    atts.write({'datas': value})
  File "/opt/odoo/odoo/addons/calendar/models/ir_attachment.py", line 27, in write
    return super(Attachment, self).write(vals)
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_attachment.py", line 479, in write
    vals = self._check_contents(vals)
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_attachment.py", line 246, in _check_contents
    mimetype = values['mimetype'] = self._compute_mimetype(values)
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_attachment.py", line 242, in _compute_mimetype
    mimetype = guess_mimetype(base64.b64decode(values['datas']))
  File "/usr/lib64/python3.6/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

**Comment by Yenthe666** [comment] 2019-11-09 16:20
Hi @annvt-dl,

Thanks a lot for your bug report. I've just tested this on the latest 13.0 but it works fine:
![image](https://user-images.githubusercontent.com/6352350/68531676-349b2200-0315-11ea-8857-03cbeb32f0a2.png)

Are you able to reproduce this on the latest official instance of Odoo at runbot.odoo.com?

Regards,
Yenthe

**Comment by annvt-dl** [comment] 2019-11-10 11:44
I uninstalled all third party addons, pulled latest version from git origin/13.0.
I have the same error (couldn't save General setting) but with new error stack trace:
- AssertionError: ldap 3.2.0 and _ldap 2.4.28 version mismatch!

I installed on CentOS7: 
yum install python3 python3-devel python3-pip python36-pillow python36-lxml python3-setuptools openldap-devel

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo/odoo/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 1323, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 1311, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 395, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 382, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/addons/base/models/res_config.py", line 630, in execute
    self._install_modules(to_install)
  File "/opt/odoo/odoo/odoo/addons/base/models/res_config.py", line 34, in _install_modules
    result = to_install_modules.button_immediate_install()
  File "<decorator-gen-58>", line 2, in button_immediate_install
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_module.py", line 463, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_module.py", line 573, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 420, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 312, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 179, in load_module_graph
    load_openerp_module(package.name)
  File "/opt/odoo/odoo/odoo/modules/module.py", line 365, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/opt/odoo/odoo/addons/auth_ldap/__init__.py", line 3, in <module>
    from . import models
  File "/opt/odoo/odoo/addons/auth_ldap/models/__init__.py", line 4, in <module>
    from . import res_company_ldap
  File "/opt/odoo/odoo/addons/auth_ldap/models/res_company_ldap.py", line 4, in <module>
    import ldap
  File "/usr/local/lib64/python3.6/site-packages/ldap/__init__.py", line 36, in <module>
    ImportError('ldap %s and _ldap %s version mismatch!' % (__version__,_ldap.__version__))
AssertionError: ldap 3.2.0 and _ldap 2.4.28 version mismatch!

**Comment by Yenthe666** [comment] 2019-11-10 12:15
Well this really looks like a packaging issue on your own OS then. @d-fence probably something for you to double check though.

**Comment by annvt-dl** [comment] 2019-11-11 06:31
I complied all Python's requirements of Odoo13 successful:
cd /opt/odoo/odoo && sudo pip3 install -r requirements.txt.

**Comment by d-fence** [comment] 2019-11-14 08:48
@annvt-dl It seems that pyldap is not packaged under CentOS, nor in EPEL release.
Unfortunately, CentOS is not supported by Odoo because of the missing requirements.
AFAIU from your last message, your were able to build the requirements so I can close this issue ?

**Comment by annvt-dl** [comment] 2019-11-14 09:45
@d-fence : I could compile Python's requirements of Odoo13 successful but I still met this issue.
Can you give me any hint?

**Comment by d-fence** [comment] 2019-11-14 10:08
I'm sorry to say that it's probably something related to your CentOS/pip setup.
I was able to compile pyldap-2.4.28 on CentOS 7 and import it right after.
You could try to remove any rpm/pip package related to ldap and then perform:
`yum install openldap-devel`
`pip install pyldap==2.4.28`
`python3 -c "import ldap; print(ldap.__version__)"`
I cannot help more than that

**Closed by d-fence** 2019-11-14 10:08 UTC
Labels: 13.0, Need information

**Comment by annvt-dl** [comment] 2019-11-14 11:13
@d-fence : thanks for your hint. I already solved this issue.

`python3 -c "import ldap; print(ldap.__version__)"`
_Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib64/python3.6/site-packages/ldap/__init__.py", line 36, in <module>
    ImportError('ldap %s and _ldap %s version mismatch!' % (__version__,_ldap.__version__))
AssertionError: ldap 3.2.0 and _ldap 2.4.28 version mismatch!_

I tried to determine how many python ldap version already installed in my server and found that have two versions:
`pip freeze | grep ldap`
_pyldap==2.4.28
python-ldap==3.2.0_

I uninstalled both two versions and reinstall pyldap 2.4.28
`pip uninstall pyldap`
`pip uninstall python-ldap`
`pip install pyldap==2.4.28`

And now this issue is fixed
`python3 -c "import ldap; print(ldap.__version__)"`
_2.4.28_

**Comment by d-fence** [comment] 2019-11-14 12:13
We have a [PR to  move from pyldap to python-ldap ](https://github.com/odoo/odoo/pull/40249)
