### ISSUE TITLE
[13] Generate Missing Terms Traceback

### ISSUE THREAD

**Issue by implementosk** [odoo/odoo#39001] opened 2019-10-18 07:34 UTC
Impacted versions:
13

Steps to reproduce:
Activate developer mode
Go to settings, Translations, Generate missing terms
Select language
Click Update

Current behavior:
Odoo Server Error

Expected behavior:
Working feature

Video/Screenshot link (optional):
<img width="984" alt="Screenshot 2019-10-18 at 09 28 22" src="https://user-images.githubusercontent.com/35446152/67074750-0305bf80-f18a-11e9-98fb-8d7faf6738e4.png">

**Comment by pedrobaeza** [comment] 2019-10-18 07:35
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Yenthe666** [comment] 2019-10-18 07:38
Reproduced & confirmed on the latest 13.0 with the French language:
![image](https://user-images.githubusercontent.com/6352350/67075211-02b9f400-f18b-11e9-98ae-f34117451e44.png)
@mart-e for you

**Comment by mart-e** [comment] 2019-10-18 10:28
Hi,

Thanks for the report. This is an issue when catching translations linked to inexistent records, the error was not properly catched.
It should be properly catched at #39021

The error itself is however interesting to investigate, could you have a look in your logs before the error? You should get an error or warning line with something like "Unable to find object ..."

Regarding the error on the runbot, it is probably due to an old reference in the .pot of website_theme_install, fixed at #39020

**Comment by mart-e** [comment] 2019-10-21 08:06
Strangely, I can not reproduce this error anymore on a 13.0 (but I was able before).
Something indeterministic? Already fixed somewhere else?
Could you detail how you reproduce (step by step or video)?

**Comment by mart-e** [comment] 2019-10-21 10:59
Ok, I will assume this was fixed by another patch. Anyway, still logging a warning so can be caught if happens again.
Will merge #39021 as a fix for the traceback

**Closed** 2019-10-21 12:57 UTC
Labels: 13.0, Confirmed, Internationalization
