### ISSUE TITLE
[14.0] related_sudo is no use for related field

### ISSUE THREAD

**Issue by lin-ww** [odoo/odoo#69583] opened 2021-04-21 08:17 UTC
Impacted versions: 14.0

Steps to reproduce:
I defined model A as below:
```python
# modelA
fieldA = fields.Char()
```
model B as below:
```python
# modelB
# default related_sudo is True for related field, here i assigned it to False
fieldB1 = fields.Many2one('modelA')
fieldB2 = fields.Char(related='fieldB1.fieldA', related_sudo=False)
```
I have the read access to model B, but i do not have the read access to model A.  
Now i read fieldB1,fieldB2 in web or in Odoo shell(without sudo)

Current behavior:
fieldB2 can be read.

Expected behavior:
It should raise access error because of the related_sudo is False, and no access to the 'fieldB1.fieldA.

Unexpectedly, the fieldB2 can not be accessed to read when i assigned ```prefetch``` to False in fieldA.  
After viewing the code, I think when i read fieldB1, Odoo will prefetch the  modelA field value, include fieldA, then fieldB2 can be read in env.cache directly.

Is that the Odoo frame issue?

**Comment by pedrobaeza** [comment] 2021-04-21 09:24
Use compute_sudo=False.

**Comment by lin-ww** [comment] 2021-04-22 01:57
> Use compute_sudo=False.

Use related_sudo=False or compute_sudo=False may get the same result as the code in fields.py below:
```python
        if attrs.get('related'):
            # by default, related fields are not stored, computed in superuser
            # mode, not copied and readonly
            attrs['store'] = store = attrs.get('store', False)
            attrs['compute_sudo'] = attrs.get('compute_sudo', attrs.get('related_sudo', True))
            attrs['copy'] = attrs.get('copy', False)
            attrs['readonly'] = attrs.get('readonly', True)
```

**Comment by pedrobaeza** [comment] 2021-04-22 06:15
I remember now: if a field is cached, it's retrieved from it and no security is applied. This is done by design, for avoiding an overhead on a rare case, so you should adapt to this "limitation".

Closing as won't fix.

**Closed by pedrobaeza** 2021-04-22 06:15 UTC
