### ISSUE TITLE
[website_forum] New spam fighting features

### ISSUE THREAD

**Issue by smack815** [odoo/odoo#3460] opened 2014-11-04 13:24 UTC
The forum needs the ability to easily clean up after spammers.  The following new features would help users police the forums and keep spammers at a minimum.

1. A new [spam] link should be listed next to [comment] [close] [edit] [delete] that would close the thread marking it as "spam or advertising" and also downvoting the thread.  There should be of course a confirmation dialogue box confirming this action and the user must have enough karma (or maybe more than normally needed to close a thread) to perform this action.
2. Users with sufficient karma (maybe 1000 or 2000) should be able to see any forum user's profile even if it is unpublished or they have negative karma.  This includes all deleted threads not just open and closed threads.  This is needed to clean up a spammer account completely.
3. A new [spam] link should be included on each open question in the profile view of a user.  This way you could see all of the posts of a spammer and from their profile mark each as spam, closing and downvoting them from one screen. The action should refresh the view showing the new status of the thread [Closed]. (maybe this should be a high karma feature)

These features are sorely needed in order to keep the helpful members of the forum motivated to self police odoo's forum for free.  It can take several minutes to clean up a spammers account completely and without quicker/easier and streamlined methods of doing it, users will eventually give up and simply allow the spammers to degrade the quality of the forums.

**Comment by smack815** [comment] 2015-01-29 14:13
@odony @tde-banana-odoo @LeartS The spammers are getting smarter.  They are now posting with titles that seems reasonable for the Odoo forums

https://www.odoo.com/forum/help-1/question/program-reviews-74608
https://www.odoo.com/forum/help-1/question/method-reviews-74605

I will ask again that a few lines of code be added to block anonymous viewing of all threads closed for reasons of spam and all deleted threads.  If you have a valid Odoo account you can, of course, still see the threads just block access to the bots and google surfers.

**Comment by Yenthe666** [comment] 2015-01-29 14:20
@smack815 good catch. But there are quite a lot more problems with the forums at the moment.
Have a look at this question: https://www.odoo.com/forum/help-1/question/how-to-send-an-internal-message-in-openerp-7-0-17629#answer_74577
People with negative karma can still post answers, so they happily spam away on existing (top) answers. There is nothing that we users can do about this. I can downvote all his comments and delete them manually but this will not keep working.

Can you guys atleast implement a safety measure that does not allow posting new comments when you are under -xx karma? (for example -20, so you can never harm innocent users)
All these posts are still indexed by Google to so the spammers are happy.

**Comment by odony** [comment] 2015-01-29 17:44
@smack815 I'm testing out something on the forum right now:
- questions posted by people with karma under the karma for posting questions are hidden except for high karma users (karma > 1000)
- answers posted by people with karma under the karma for answering questions are hidden except for high karma users (karma > 1000)
- comments posted by people with karma under the karma for commenting are hidden except for high karma users (karma > 1000)

If that works well we could apply this change more permanently to the forum module.

@Yenthe666 the system **does** prevent users with negative karma from posting - but if they do the full signup including email validation (and they do it!), they are allowed to post questions and answers until someone votes them down.
With the test I'm conducting it will at least automatically hide their contents everywhere as soon as they are downvoted enough, or as soon as a question is closed as spam (= 5 downvotes)

**Comment by smack815** [comment] 2015-01-29 17:56
@odony That explains why the Forum is giving a 403 Forbidden message right now.

May I make one suggestion... Can there be a visual clue that the post/comment is hidden to low karma users.  It could be a color clue or a text clue (I like the color clue).  This clue helps high karma users to know if they need to do something to help stop the spammer or if the firestorm is already over.

**Comment by smack815** [comment] 2015-01-29 18:01
@odony I fell like I do nothing but complain.... sorry but while I have your attention and you are in the forum module.... The delete comment **X** is not working for deleting your own comments nor for deleting comments written by others.

**Comment by smack815** [comment] 2015-01-29 18:11
@odony I have just now [confirmed](http://43214-8-0-835065.runbot6.odoo.com/forum/help-1/question/how-to-configure-alerts-for-employee-contract-expiration-1) this is broken in the official V8 fork.

Neither the admin nor my user can delete comments.  Should I make a new issue for the forum software?

**Comment by odony** [comment] 2015-01-29 18:30
@smack815 Yes sure, please open an issue for this. As for the 403 error, it's caused by my experiment not working as it should, I'll retry something else later, sorry :disappointed:

**Comment by smack815** [comment] 2015-01-29 18:33
@odony The forum members thank you.

**Comment by Yenthe666** [comment] 2015-01-29 21:00
@odony your new ideas sound pretty good. No worries that it didn't work this time, I'm sure you'll find a way! And as @smack815 said the forum members thank you. You're doing a great job!

**Comment by lukebranch** [comment] 2015-02-09 01:08
@odony ,

I think an Akismet clone for Odoo would be a great way to fight this. Automattic (Wordpress) offers a free tier for personal users, as well as business tiers depending on your requirements:

akismet.com/plans/

This could start as a simple RBL and/or DNSBL and evolve from there as Akismet has over the years.

I think it would be best if this could be offered as a service that operates through an Odoo addon (similar to Akismet) as this would allow you to constantly upgrade the code in the service depending on your spam fighting requirements, and allow you both a free (personal use) tier for mass adoption (thus making it more effective), and different business tiers.

This addon/service would not be immediately effective, however with mass adoption I think this could be an incredibly effective spam fighting tool for Odoo website/e-commerce users, as once one user connected to the service flags an email address as spam it could be flagged throughout the entire network connected to the service as a red flag. Something like this could be implemented on multiple levels as well (eg. Contact Form, comments, reviews, etc.).

On another subject, is it possible to add an option for high-karma users (ie. over 1000 karma for help.odoo.com) on user's profiles to allow a 'close as spam and delete' option next to the list of user's questions (ie. /forum/help-1/user/[...]). Most of these spam posts at the moment have obvious spam titles (eg. '2015 big discountbest') and it would be great if higher karma users could just kill the spam from there (maybe with ajax-like functionality so there's no need to reload the page) rather than going through each post one by one. It would save a lot of time sifting through those that open one account and just post loads of spam through one account (eg. this prick: https://www.odoo.com/forum/help-1/user/434299).

**Comment by smack815** [comment] 2015-02-13 03:49
@odony & @tde-banana-odoo a forum badge for my 500th and 1000th closed spam would be a really nice retirement gift.  Or the Odoo gold watch, whatever is easier.

**Comment by smack815** [comment] 2015-02-14 05:10
I hope there are not many new Odoo prospects reading the forums. @odony @fpodoo 
https://www.odoo.com/forum/help-1/question/brrip-1080p-download-and-top-five-2014-watch-free-online-full-movie-with-blu-ray-1080p-quality-76405
https://www.odoo.com/forum/help-1/question/movie-download-and-watch-tammy-2014-watch-free-online-full-movie-with-blu-ray-1080p-quality-and-enjoy-76411
https://www.odoo.com/forum/help-1/question/brrip-1080p-download-and-night-moves-2013-watch-free-online-full-movie-with-blu-ray-1080p-quality-76410
https://www.odoo.com/forum/help-1/question/brrip-1080p-download-and-relatos-salvajes-2014-watch-free-online-full-movie-with-blu-ray-1080p-quality-76409
https://www.odoo.com/forum/help-1/question/movie-download-and-watch-gloria-2014-watch-free-online-full-movie-with-blu-ray-1080p-quality-and-enjoy-76408
https://www.odoo.com/forum/help-1/question/brrip-1080p-download-and-dracula-untold-2014-watch-free-online-full-movie-with-blu-ray-1080p-quality-76407
https://www.odoo.com/forum/help-1/question/brrip-1080p-download-and-constantine-2005-watch-free-online-full-movie-with-blu-ray-1080p-quality-76406
https://www.odoo.com/forum/help-1/question/brrip-1080p-download-and-spare-parts-2015-watch-free-online-full-movie-with-blu-ray-1080p-quality-76420
https://www.odoo.com/forum/help-1/question/brrip-1080p-download-and-big-eyes-2014-watch-free-online-full-movie-with-blu-ray-1080p-quality-76418
https://www.odoo.com/forum/help-1/question/best-quality-watch-still-alice-2014-all-free-enjoy-with-bluray-quality-now-76415
https://www.odoo.com/forum/help-1/question/best-quality-watch-son-of-a-gun-2014-all-free-enjoy-with-bluray-quality-now-76414
https://www.odoo.com/forum/help-1/question/brrip-1080p-download-and-the-spongebob-movie-sponge-out-of-water-2015-watch-free-online-full-movie-with-blu-ray-1080p-quality-76413
https://www.odoo.com/forum/help-1/question/brrip-1080p-download-and-birdman-2014-watch-free-online-full-movie-with-blu-ray-1080p-quality-76412

**Comment by Yenthe666** [comment] 2015-02-24 07:32
@odony and @fpodoo any update on this please?
There is a lot of spam coming in and it is annoying to close/delete/edit every single spam topic. 
Another person on the forums is complaining about it too: https://www.odoo.com/forum/help-1/question/moderator-can-ban-user-77436

**Comment by lukebranch** [comment] 2015-02-24 09:19
@Yenthe666 ,

I'm not sure about you, but the most troublesome spam i'm having to deal with is users posting multiple times from the same account within a short space of time (eg. 20 posts in 5 minutes).

Reddit for example has a time limit on multiple posts from the same user which tends to curb spammers to a certain extent, and I think it would be great if Odoo could implement something similar (obviously carefully considering new users at the same time). 

Perhaps a popup message explaining why they cannot post multiple times within the space of a few minutes, and/or CAPTCHA code (or something requiring human input/confirmation) for posting multiple times within a short period would be an option.

I really think some form of Akismet Clone could help with this type of thing in the long run. It could act as a phone-home for Odoo to know how many instances of a particular version are online at any given time and where (if this is something they wanted), and it would also offer Odoo's own forum better protection against spammers due to a Collaborative, human-driven effort from the entire community. This would in turn benefit everyone using the service.

I think the overheads of running this type of service would be minimal and mirrors could be distributed around the world and hosted by Odoo partners or willing members of the community to ease any load concerns.

**Comment by Yenthe666** [comment] 2015-02-24 09:39
@lukebranch I like your suggestions. What I assume as good options to cut back on the spam would be:
<ul>
<li> Maximum number of posts per xx minutes or CAPTCHA's as you said.</li>
<li> Ability to flag accounts</li>
<li> Accounts with negative karma (for example -20 karma) are automaticly locked </li>
<li> Ability from high level forum users to 'lock' an account for xx hours </li>
<li> Spam detecting algorithm, something along the lines of Akismet, as you said </li>
</ul>

I think this would be a big step in the good way and discourage a lot of the spammers since it will not be worth the hassle.

**Comment by lukebranch** [comment] 2015-02-24 10:09
@Yenthe666 ,

Yes, I think that is it in a nutshell. I'd be happy to do some more research on other forum platforms/services with spam-fighting features to see if there's anything that Odoo SA can glean from if they are interested.

I think it would be useful for the average joe forum user to be able to report as spam (eg. flag account/flag post), perhaps so that a higher-karma user (or Odoo staff member) can see a list of posts reported as spam for easier review and removal (eg. facebook's report post feature). The average forum user would not need to see these flags, as they could be displayed only to those with higher karma, or something along those lines.

**Comment by lukebranch** [comment] 2015-02-24 10:28
Further to my previous message, there's a few things existing community-driven projects that i've just come across as follows:

Project HoneyPot (the original guys behind CloudFlare CDN):
http://www.projecthoneypot.org/httpbl_api.php
http://www.projecthoneypot.org/cloudflare_beta.html

StopForumSpam:
http://www.stopforumspam.com/

fSpamlist: 
http://www.fspamlist.com

Sorbs:
http://www.sorbs.net/
Bot Scout:
http://botscout.com/

DroneBL:
http://dronebl.org/

AHBL:
http://ahbl.org/

**Comment by smack815** [comment] 2015-02-24 16:12
@lukebranch @Yenthe666 @odony I love ProjectHoneyPot.  Not only do they help prevent spammers you can also help them catch spammers to be blocked for the whole community.

I have sadly stopped deleting spam posts in the forum.

**Comment by Yenthe666** [comment] 2015-02-24 17:49
@lukebranch great links and a lot have good options.
@smack815 I've closed another 10 or so today. I do wonder why I even bother since Odoo itself doesn't even seem to care. They don't even seem to be bothered to reply on all our suggestions and improvements..

**Comment by odony** [comment] 2015-02-24 19:24
I'm still following this thread but I also explained what we plan to do about 
it in the next version 
https://github.com/odoo/odoo/issues/3460#issuecomment-61968508. Our forum 
system is heavily inspired by StackExchange, why not get the inspiration there, 
where it's working and scaling?
Akismet-like stuff, captchas or integration with third-party tools definitely 
sound out-of-scope. Why wouldn't a first-post/first-comment moderation queue 
(just like on SE) work just fine, with zero setup (just tick the box to enable it)?

@smack815 I'm still trying to find the time to implement the auto-hiding of 
negative karma posts in 8.0, but my last attempt failed and I can't dedicate 
much coding time to the forum these days, sorry :-(

**Comment by smack815** [comment] 2015-02-24 19:40
@odony, it's ok we know you are working hard.  I'll just wait for saas-6 or will it be implemented in 9.0?

**Comment by lukebranch** [comment] 2015-02-25 02:34
@odony ,

I think SE-style features being implemented into help.odoo.com would definitely be a big  step in the right direction. As you've said it's human-driven spam that is giving you the problems here, so it is much harder to fight.

If it is someone specifically targeting help.odoo.com for whatever reason (eg. sorryopenerp springs to mind) I have a feeling that they would simply start a legitimate account (or a few) and use those accounts for posting legitimate Odoo questions, while simultaneously helping the spammers with the moderation queue.

I guess this sort of behaviour would be trackable though and you'd be able to see those posing as legitimate accounts to help spammers by who they are helping.

I'd be happy to take some time to investigate the various StackExchange features for fighting spam to see how they do it and post back here with what I find.

**Comment by Yenthe666** [comment] 2015-02-25 07:13
By the way, while we're at it! Where can we post suggestions for new features on the forums?
I'd love a feature where we can set bounty on a question, just like on StackOverflow. You can offer xx bounty on a question which gives you more chance on an answer and other people can earn karma.

**Comment by lukebranch** [comment] 2015-02-27 04:16
@odony ,

Please consider implementing the first comment/post queue soon. Please take a look at the closed as spam posts from today in the forum, it's getting out of hand.

The main problems are one accounting posting 20-30 posts within the space of a few minutes, and they could definitely be curbed quite quickly with a simple first-post/first-comment queue as you have suggested.

**Comment by lukebranch** [comment] 2015-02-27 06:12
I just came across this article regarding how twitter is updating it's abuse reporting tools:

http://www.theverge.com/2014/12/2/7317955/twitter-releases-improved-tools-for-reporting-abuse-and-harassment

perhaps there are some features that Odoo can consider in the future.

I understand the forum is not a top priority in regards to development for the platform, however it is great advertising for the brand, and it's a very important tool for the end user and for developers offering services related to Odoo.

**Comment by Yenthe666** [comment] 2015-02-27 07:24
@lukebranch you have a point that a minor fix should really happen on the long term. Even if it is just a verification queue. I've closed loads of spam threads these last days...
Its affecting the Odoo brand atleast partially and it is very annoying for us, the users.
One question though.. Where do you view the closed as spam posts? Never seemed to find/notice this option?

**Comment by lukebranch** [comment] 2015-02-27 07:27
@Yenthe666 ,

I haven't found this feature either. I'm just clicking on the username of the spammer and then closing all of their spam posts from there. 

I can only see closed posts that i'm working on as I just open a bunch of tabs in the browser to downvote, close and delete them all.

I've closed at least a hundred today. Hopefully Odoo is able to implement some sort of verification queue soon, as the spammer(s) are getting more determined.

**Comment by Yenthe666** [comment] 2015-02-27 07:56
@lukebranch thanks for the reply. Okay I thought I missed something :) I've deleted & closed another 10 or so today. Be sure to edit the posts and get the text out, otherwise they'll rank up in Google which is what they want.

**Comment by lukebranch** [comment] 2015-02-27 07:58
@Yenthe666 ,

Thanks for letting me know. I thought deleting them would remove them from public view though, right?

**Comment by Yenthe666** [comment] 2015-02-27 08:02
@lukebranch it will remove them from the public view in the lists on the Odoo forums itself. However when you would google for a similar thing as in the title Odoo will show up with all the threads. Even after they are deleted and closed they're still indexed by Google.
And live from the forums right now:
<img src="http://i.imgur.com/BCq4nyH.png" /> @odony please start taking action on this.

**Comment by smack815** [comment] 2015-02-27 12:31
@lukebranch No deleting and down voting have no affect and are a waste of time.  One thread closed as spam will stop the user from posting more.  I would avoid giving yourself double work that has no benefits. 

All forum threads are publicly accessible even if they are closed and or deleted.  They only need to exist in the database to be anonymously recalled.  Just open up a browser that is not logged into the forum and go to [https://www.odoo.com/forum/help-1/question/76406]

Then add one to the number to see the next spam post in the series... I am sure Google knows how to move up and down forum sequential posts... More efferent than trying to spider an ever changing forum list.

The only think that needs to be done to keep Google from indexing and offering Odoo spam to the world is to make all forum posts closed for reasons of spam viewable to only logged in users with karma higher than 0.

That is a change easy to make.  [/dismount soap box]

**Comment by lukebranch** [comment] 2015-02-28 05:03
@smack815 ,

Thanks for letting me know. I've just done a google search for 'streaming movies odoo' in google and here are the results:

https://www.google.com.hk/?gfe_rd=cr&ei=MkrxVKuZPKiL8Qf2voDwBw&gws_rd=ssl#q=movie+streaming+odoo+site:www.odoo.com&start=30

There have been a few DMCA takedowns issued from what I can tell for the content in google's search results. There seems to be hundreds if not thousands of them listing in google, and it can't be good for odoo.com's SEO to have all of that spammy content originating from the TLD.

I think the spammers are out to damage the search engine reputation of Odoo (in terms of SEO), and it looks like it's working to a certain extent, and could be hurting your website traffic as a result.

I can try to tackle what I can find in the search engine results that i've closed, however it would be far better if Odoo issued a fix that simply switched off the public access to those posts when they were closed as spam and/or deleted as @smack815 has suggested.

**Comment by smack815** [comment] 2015-02-28 12:40
@lukebranch it's very nice of you to worry about odoo's SEO but I worry about the thousands of odoo users who will be affected by this problem.  Once you have written the code to spam Odoo.com it's trivial to spam all the websites that use odoo's software.  

No one can convince me that thirty posts in a few minutes were done by a human even if a human registered.  They are writing code and will use it anywhere they can.

**Comment by smack815** [comment] 2015-02-28 12:45
And spamming a Mom and Pop shop is actually better because they probably will not be reviewing their website daily. So they get more mileage for the same source code.

**Comment by lukebranch** [comment] 2015-02-28 13:39
@smack815 ,

I honestly think it is someone using the developer tools in their browser to do this, as it seem sporadic and not at all consistent with a script. I think if it was a script it would be doing far more damage, as I don't think Odoo has any timers on new post submissions, or a first post/comment queue yet.

I've closed spam posts roughly as quickly as they've been created, making me think that there is a human on the other end of the posts.

When before it seemed to be a single person, now it seems like there may be one or two people working together to post at the same time.

I'm sure Odoo is aware of the problem and working towards a solution, as the spam problem has become pretty severe recently. Hopefully a fix is issued in SaaS 6 which I believe will shortly be implemented in Odoo.com along with a new theme i've seen in the runbots.

**Comment by lukebranch** [comment] 2015-03-02 02:34
The spam is now roughly 50 pages deep at the time of writing, and showing no signs of slowing down.

**Comment by Yenthe666** [comment] 2015-03-02 06:52
@lukebranch they're actually over 100 pages now and are going very fast. They're posting more than 1 post a minute at the moment.
@odony @xmo-odoo @tde-banana-odoo its time for you guys to come in action. Delete all these & start building in a prevention system, please. This is damaging your brand and it is annoying us all.

**Comment by lukebranch** [comment] 2015-03-02 09:17
@Yenthe666 ,

Yeah, i've noticed. It seems like there's a team of them working together. It's 150 pages deep now. I could delete spam all day and not even make a dent in it.

**Comment by Yenthe666** [comment] 2015-03-02 09:33
@lukebranch you shouldn't even try, I tried it for 40 minutes but I can't even slow them down.
Honestly, this is now the problem of Odoo, not ours. We have been warning them since november for this and they did not look into any fixes, not even temp ones.

**Comment by smack815** [comment] 2015-03-02 10:49
@Yenthe666  I would not say that they have done nothing.  They have put a few patches on the system to make it a little bit harder.  But now someone will spend development time to weed out and clean up the database.

@lukebranch do you still believe that they are not using scripts?

**Comment by lukebranch** [comment] 2015-03-02 11:09
@smack815 ,

I think you may be right about the scripts!

**Comment by smack815** [comment] 2015-03-02 11:10
@odony May I kindly request that any tools that get developed to do massive cleanup of the database based on user etc. be included in the saas-6 and Master branches to be used by the community.  This problem will be duplicated over the user community if not by these types of attracts, then by other types.

Tools will be very helpful to combat this and save Odoo owners many hours of hand deletion.  Thanks for your consideration!

**Comment by smack815** [comment] 2015-03-02 11:26
@odony It seems that [forum spammer babara](https://www.odoo.com/forum/help-1/user/444508) did not register with the email before posting 10 spam messages...

![forum-spam](https://cloud.githubusercontent.com/assets/8161873/6439837/4abf2d7e-c0ad-11e4-92ca-aa4659afca1f.png)

**Comment by zbik2607** [comment] 2015-03-02 12:13
Why do spammers attack. The answer to this is simple: <a href="https://www.odoo.com/forum/help-1/question/spammers-are-happy-spam-indexed-by-google-and-other-spiders-why-71187">Spammers are happy</a>

**Comment by odony** [comment] 2015-03-02 19:19
# Temporary measures taken this morning (CET):
- Blocked all IP blocks from the main ISPs where most of the spam posts where 
originating:
   + Indonesian AS17974 http://bgp.he.net/AS17974
   + South Korean AS38661 http://bgp.he.net/AS38661
- Added manual activation step (very temporary!)
- Deleted all posts from users with negative karma
- Deleted all posts from users with multiple posts and no karma gain (except 
some real users like 393912, 434606 or 412543)
- @smack815: User 444508 (babara) did perform an email activation (full session 
is here: http://pastebin.com/T2dVtFz2, look at line 337) I think your 
screenshot might have been taken when some of his posts had already been 
deleted, explaining why his karma was back at 0 without visible downvotes.

Sorry, no generic cleanup tool for the above, a couple quick SQL queries based 
on user karma.

# Permanent measures:
- Any post by a user with negative karma is now a 404 page except for users 
with high karma.

# Coming Soon:
- New user posts limited to 1 question/answer per 24h until they have more than 
the initial karma
- ...

**Comment by zbik2607** [comment] 2015-03-02 20:04
Hmmm, strange, at this moment, still exists, about 300 today's spammers posts, one after the other, from about ~ 3/2/15, 1:17 AM

**Comment by smack815** [comment] 2015-03-02 20:10
@odony @zbik2607 

6 Spam messages - https://www.odoo.com/forum/help-1/user/444790
9 Spam messages - https://www.odoo.com/forum/help-1/user/444785
8 Spam messages - https://www.odoo.com/forum/help-1/user/444775
11 Spam messages - https://www.odoo.com/forum/help-1/user/444688
3 Spam messages - https://www.odoo.com/forum/help-1/user/444690
3 Spam messages - https://www.odoo.com/forum/help-1/user/444684

**Comment by zbik2607** [comment] 2015-03-02 20:15
@smack815, I'm not sure but this may be the result of my action (negative karma creations)

**Comment by lukebranch** [comment] 2015-03-03 02:46
@odony ,

Thank you for taking action. These spammers seem very determined, and not motivated by link building alone. I look forward to the seeing the new spam fighting features being integrated into the upcoming SaaS 6 switch on Odoo.com.

**Comment by Yenthe666** [comment] 2015-03-03 07:18
@odony thanks for the enhancement and (temp) fixes!
There does seem to be a lot of spam on the pages though? Starting from page 7 (https://www.odoo.com/forum/help-1/page/7) up to page 30 (https://www.odoo.com/forum/help-1/page/30) Is there any easy way for you to delete this too?

**Comment by odony** [comment] 2015-03-03 18:55
Deleted all the remaining spam posts I could find (those mentioned by @smack815 were in there too). If you find any more of them, please be sure to close them as spam so they disappear  for normal users and are easier to track for cleanup. Thanks!

**Closed** 2016-03-25 14:46 UTC
Labels: need review, RD, wishlist

**Comment by aek** [comment] 2016-06-27 10:25
Sorry that miss this thread, I use to fight with those spammers too. My steps are downvote and close the answer and also open the spammer profile to quickly downvote and open to close as spam all their questions. But these days seems that Odoo block the access for the profile link that used to be on the username of who posted. Should I open an issue for that? to allow anyone to be able to open the user profile by clicking on the username?
