### ISSUE TITLE
[v9]Opening the invoice workflow in diagramm view crashed

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#11146] opened 2016-02-29 16:27 UTC
Impacted versions:

9.0 from rpm

Steps to reproduce:
Open the invoice workflow in diagram

Current behavior:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 680, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 959, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 509, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/openerp/addons/web_diagram/controllers/main.py", line 79, in get_diagram_info
    search_acts = node_act.search([(field_data[0]['relation_field'], '=', id)], 0, 0, 0, req.session.context)
KeyError: 0
```
Expected behavior:

Dsiplay the diagram

**Comment by Yenthe666** [comment] 2016-06-13 07:51
Hi @flotho,

I can no longer reproduce this issue on the latest runbot.
Please update your Odoo codebase and it should be fixed. If you still face this problem please add some more details about how to trigger the bug but note it should be reproducable on the latest code.
Closing this since the bug has been fixed in the meanwhile.

Regards,
Yenthe

**Closed by Yenthe666** 2016-06-13 07:51 UTC
