### ISSUE TITLE
[11.0] odoo 11, does not save attribute values ​​in variants

### ISSUE THREAD

**Issue by nuelgoz** [odoo/odoo#25056] opened 2018-06-04 20:37 UTC
it does not save variants, in Odoo 11, when you create a product with variants it saves the attributes and the variants, but when generating a high number of variants the system does not keep the changes made.

example: I have 8 attributes and in each attribute several values, are characteristics of an ordered, I can have ram screen and several values for each attribute, I can continue adding attributes and the system saves them but there comes a time that no longer allows me to save more attribute values, but it allows me to save more attributes.

I have already changed the speed of the server, the number of connections in the database, the time of use of the cpu and software, the workers and the system and I do not notice any change in the log of the odoo and postgre I do not detect anything weird , also I have some porducts that have 4000 variables and no longer accept more and other porducts that up to 9000 does not give this problem and others that saves thousands of variables 3000 or more.

**Comment by gdgellatly** [comment] 2018-06-05 01:08
It will eventually if you let it, but your volumes are at the extreme end.

You'll need to run with zero workers and wait.  Otherwise you hit CPU
limits. I'm pretty sure there is some non linear computation going on
because it gets very slow as volumes increase.

I've not had to do any big ones for a while but for roughly 20k it took
about 7 hours.

**Comment by pedrobaeza** [comment] 2018-06-05 07:45
Yes, this is not a problem of Odoo, but timeouts in your configuration.

Any way, I would rethink your product structure for sure, as 4k / 9k variants per template doesn't seem something sane. You should split IMO some attributes as separate templates for having a better granularity.

Closing as no real issue.

**Closed by pedrobaeza** 2018-06-05 07:45 UTC

**Comment by nuelgoz** [comment] 2018-06-05 16:06
el problema no es que no pueda genarar las variables, la cuestion es que no las guarda por lo tanto se queda en la plantilla de producto sin guardar.

yo creo que esto no es un ploblema de configuracion de tiempos de la configuracion de odoo ni de postgre sino que el sistema falla realizando estas tareas ya que no hay un patron, es algo aleatorio.

**Comment by pedrobaeza** [comment] 2018-06-05 16:11
You must write here only in English, but what you say it's because previously an error that has lead to an inconsistent JS client state. Refresh browser and it is.

**Comment by nuelgoz** [comment] 2018-06-05 17:03
I appreciate your interest, but I do not think it is due to a bad configuration, I think it is a failure in Odoo, I have posted it here to have a contrasted opinion and to know if it happens to other users and someone can provide a solution, as you can know What is not a failure of odoo? I respect your opinion but I think you should not close the publication, you say it is not a failure of odoo without having verified it.

**Comment by pedrobaeza** [comment] 2018-06-05 17:15
I have already stated a possible cause, but you have to understand that without constant steps to reproduce the problem, this doesn't lead to anything, and the steps can't be: create a template with 9k variants and wait to see if it fails.

**Comment by nuelgoz** [comment] 2018-06-05 17:22
if you create a template of more than 15k variants and it does not fail you let me know.

**Comment by pedrobaeza** [comment] 2018-06-05 17:32
As a hint for not being rude, there's an OCA module that can help you if you still persist with such a big number of variants: https://github.com/OCA/product-variant/tree/10.0/product_variant_configurator
