### ISSUE TITLE
[16] The product attribute multi value problem with no variant!

### ISSUE THREAD

**Issue by esakarya** [odoo/odoo#108878] opened 2023-01-01 08:31 UTC
If a product has multiple values of a non-variant attribute, it appears to be variant on the website.

- Attribute is not Variant cration mode
![odoo_01](https://user-images.githubusercontent.com/61056242/210165061-af801147-b005-4060-90a0-af3cf9202e8f.jpeg)

- and product support multi value from attribute.
![odoo_02](https://user-images.githubusercontent.com/61056242/210165073-ddde0c0d-6dd0-4ccb-ac25-d16852c63797.jpeg)

- final problem is website says its variant .
![odoo_03](https://user-images.githubusercontent.com/61056242/210165091-e2d21d88-7499-4362-8f37-1e6e32bbe8ef.jpeg)

**How can i use multi value from attribute without variant looking ? i think its a big problem. we are a lot of product has supported multi value from attribute.**

**Comment by esakarya** [comment] 2023-01-07 08:44
any news ?

**Comment by esakarya** [comment] 2023-01-18 16:03
all odoo's contributors is death ? its big deal.

**Comment by esakarya** [comment] 2023-03-06 19:58
Up

**Comment by toaa-odoo** [comment] 2023-03-07 08:24
Hi! As answered on your Twitter comment, this is currently working as intended. However, in the future you will be able to use variants and filters in another way, once this PR (https://github.com/odoo/odoo/pull/109771) is merged. Thank you for your feedback, and be assured it is heard.

**Closed by toaa-odoo** 2023-03-07 08:24 UTC

**Comment by eikido18** [comment] 2023-12-03 20:54
@esakarya 

Maybe this is a solution for you?
https://github.com/OCA/e-commerce/tree/16.0/website_sale_product_attribute_value_filter_existing
