### ISSUE TITLE
Cannot get backup from odoo v9 server

### ISSUE THREAD

**Issue by daramousk** [odoo/odoo#13192] opened 2016-08-17 14:23 UTC
Impacted versions:
V9 community (possibly enterprise as well)
commit 842bf793f5d3819ae42dd9debcfeda16e48dda4f
Date:   Sun Aug 14 00:38:20 2016 +0200

Steps to reproduce:
Open an incognito window and try taking a backup of a database **without** logging in. (just head on to database manager and click backup)

Current behavior:
This exception is thrown:

2016-08-17 14:19:08,279 23430 ERROR ? openerp.addons.web.controllers.main: Database.backup
Traceback (most recent call last):
  File "/home/george/odoo/odoov9/odoo-server-v9/addons/web/controllers/main.py", line 699, in backup
    ('Content-Disposition', content_disposition(filename)),
  File "/home/george/odoo/odoov9/odoo-server-v9/addons/web/controllers/main.py", line 425, in content_disposition
    return request.registry['ir.http'].content_disposition(filename)
TypeError: 'NoneType' object has no attribute '__getitem__'

Expected behavior:

A backup should be downloaded

**Note**:From what I can see if I comment out the content-disposition in web/controllers/main.py line 698 on the backup method the backup is being downloaded correctly. The content_disposition method tries to get a registry object from a request.

**Comment by alaa9jo** [comment] 2016-08-18 12:57
This is not a new issue, I had the same exact issue a few days ago, I searched in issues and I found issue #11583 , you have to login once then try to backup again.

**Comment by daramousk** [comment] 2016-08-18 18:55
Is there a fix for this behaviour? Is this behaviour intended for a reason? Is there any workaround for wanting to get a backup via and rpc call?

**Comment by alaa9jo** [comment] 2016-08-19 14:06
>Is there a fix for this behaviour? 

That thread I mentioned wasn't updated since the issue was reported, it's closed as not a bug since there are workarounds, you have to login or at least visit login page then go back to database manager and try to backup,

> Is this behaviour intended for a reason? Is there any workaround for wanting to get a backup via and rpc call?

I don't think this is intended at all, check on comments by twohex and dreispt , you may find your answers there, but in my opinion this is a bug and provided workarounds (visiting login page) doesn't make any sense.

@Yenthe666 , what do you think of this issue? could you let somebody have a look at this one?

**Comment by Yenthe666** [comment] 2016-08-19 14:18
Hi @daramousk,

Thanks a lot for your report! I've just tested this and this is indeed a bug. Example:
![image](https://cloud.githubusercontent.com/assets/6352350/17812699/8a9b410e-6628-11e6-9fb4-8e23aded4e89.png)

@JKE-be can you look at this please?
@alaa9jo thanks a lot for pinging me :wink:

**Closed** 2016-08-19 16:42 UTC
Labels: confirmed
