### ISSUE TITLE
Sale Flow issue [9.0]

### ISSUE THREAD

**Issue by lithint** [odoo/odoo#13066] opened 2016-08-08 14:27 UTC
Impacted versions:9.0
Case 1
     Step 1:
-              Sales -> Settings -> enable 'Never allow to modify a confirmed sale order'
   Step 2:
-              Create a sale order and confirm.
  -             Sale Order directly going to done state(draft to done).
    expected: It should be in 'sale order' state.
    In 'Done' state able to edit the following fields:
-            Salesperson
-            Sales Team
     expected: should not allow to edit once done.- as this will affect the SO analysis and reporting

Case 2:
-  In normal sale orders, after the delivery of the products, the Cancel button the Sale order
  allows to cancel the SO, but no effect in the Delivery order which is done.
  
  expected: Any sale order if a delivery is done, it should not allow the SO to cancel,
  if allowing the SO to cancel after Delivery is done. it should reverse all the process/transactions related to it.

Note: tested in the runbot too

**Comment by pedrobaeza** [comment] 2018-04-25 23:44
The 2 things you mention are not the intended behavior, and you should adapt to it. No real issue, so closing.

**Closed by pedrobaeza** 2018-04-25 23:44 UTC
Labels: 9.0
