### ISSUE TITLE
Can't set access rights for users in odoo v9

### ISSUE THREAD

**Issue by ajaychauhan727** [odoo/odoo#9155] opened 2015-10-20 11:30 UTC
Steps to reproduce:
- Create one user
- Give Administration's Access Rights rights to that
- Login with that user & try to set access rights for other users.

Results:
It gives access error on clicking on Settings menu, even if you try to click on Users menu it gives you other access error.
![access_error](https://cloud.githubusercontent.com/assets/5329501/10605774/b24a1bc0-774b-11e5-839a-4d4fd90225bb.png)

**Comment by gaelrabier** [comment] 2015-11-16 09:53
Any news on this one? It is very annoying since I have to choose between giving full admin rights to a user, or creating all users myself.

**Comment by pedrobaeza** [comment] 2018-04-06 00:43
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-04-06 00:43 UTC
