### ISSUE TITLE
ValueError: too many values to unpack (expected 2) when open slide channels or create slides

### ISSUE THREAD

**Issue by frankmiao2015** [odoo/odoo#33925] opened 2019-06-06 04:13 UTC
Impacted versions: odoo 12

Steps to reproduce:
Install website_slides, create one slide under public channel, go back to menu Presentation, click Public Channel where the created slide resides, you will get 500 Internal Error. And if you are going to create another slide by right top New-New Slide-choose Public Channel-Select. The same errors happens.

And I use the multi website function. Not sure if that is an issue

Current behavior:
500: Internal Server Error
too many values to unpack (expected 2)
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/addons/base/models/qweb.py", line 346, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_website_layout_1628
  File "<template>", line 2, in body_call_content_1625
  File "/odoo/odoo-server/addons/http_routing/models/ir_http.py", line 93, in slug
    identifier, name = value
ValueError: too many values to unpack (expected 2)

Here is the full Trace back:

`Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/addons/base/models/qweb.py", line 346, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_website_layout_1628
  File "<template>", line 2, in body_call_content_1625
  File "/odoo/odoo-server/addons/http_routing/models/ir_http.py", line 93, in slug
    identifier, name = value
ValueError: too many values to unpack (expected 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/addons/base/models/ir_http.py", line 203, in _dispatch
    result = request.dispatch()
  File "/odoo/odoo-server/odoo/http.py", line 833, in dispatch
    r = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 340, in checked_call
    result.flatten()
  File "/odoo/odoo-server/odoo/http.py", line 1268, in flatten
    self.response.append(self.render())
  File "/odoo/odoo-server/odoo/http.py", line 1261, in render
    return env["ir.ui.view"].render_template(self.template, self.qcontext)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 1284, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/odoo/odoo-server/addons/website/models/ir_ui_view.py", line 319, in render
    return super(View, self).render(values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/odoo/odoo-server/addons/web_editor/models/ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 1293, in render
    return self.env[engine].render(self.id, qcontext)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_qweb.py", line 59, in render
    result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/odoo/odoo-server/odoo/addons/base/models/qweb.py", line 274, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/odoo/odoo-server/odoo/addons/base/models/qweb.py", line 348, in _compiled_fn
    raise e
  File "/odoo/odoo-server/odoo/addons/base/models/qweb.py", line 346, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_3560_2096
  File "/odoo/odoo-server/odoo/addons/base/models/qweb.py", line 353, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.models.qweb.QWebException: too many values to unpack (expected 2)
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/addons/base/models/qweb.py", line 346, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_website_layout_1628
  File "<template>", line 2, in body_call_content_1625
  File "/odoo/odoo-server/addons/http_routing/models/ir_http.py", line 93, in slug
    identifier, name = value
ValueError: too many values to unpack (expected 2)

Error to render compiling AST
ValueError: too many values to unpack (expected 2)
Template: website.layout
Path: /templates/t/t[1]/div/header/nav/div[2]/div/div[2]/t[1]/form
Node: <form t-att-action="keep('/shop'+ ('/category/'+slug(category)) if category else None, search=0)" method="get">
                                
                                <t t-set="search_text" t-value="search"/>
                                <input class="form-control" name="search" placeholder="Search" t-att-value="search" type="text" data-oe-model="ir.ui.view" data-oe-id="3390" data-oe-field="arch" data-oe-xpath="/data/xpath[4]/div[2]/div[1]/div[1]/t[1]/form[1]/input[1]"/>
                                <button class="btn btn-default">
                                    <i class="fa fa-search" data-oe-model="ir.ui.view" data-oe-id="3390" data-oe-field="arch" data-oe-xpath="/data/xpath[4]/div[2]/div[1]/div[1]/t[1]/form[1]/button[1]/i[1]"/>
                                    <span class="oe_search_found" t-if="search and search_count">
                                                            <small>(
                                                            <t t-esc="search_count"/>
                                                            found)</small>
                                                            </span>
                                                            </button>
                            </form>`

**Comment by pedrobaeza** [comment] 2019-06-06 07:23
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by frankmiao2015** [comment] 2019-06-08 04:07
It is my theme issue. Sorry for that

**Closed** 2019-06-08 04:07 UTC
Labels: Need information

**Comment by fathia-ghribi** [comment] 2020-12-16 16:25
hello ,
i try to implement lda2vec from (https://github.com/sebkim/lda2vec-pytorch) with my own data. when i run the model preprocess.py.
`from collections import Counter
from tqdm import tqdm

def preprocess(docs):
"""Tokenize, encode documents.

Arguments:
    docs: A list of tuples (index, string), each string is a document.

Returns:
    encoded_docs: A list of tuples (index, list), each list is a document
        with words encoded by integer values.
    decoder: A dict, integer -> word.
    word_counts: A list of integers, counts of words that are in decoder.
        word_counts[i] is the number of occurrences of word decoder[i]
        in all documents in docs.
"""

def tokenize(doc):
    return doc.split()
tokenized_docs = [(i, tokenize(doc)) for i, doc in tqdm (docs[:])] 
counts = _count_unique_tokens(tokenized_docs)
encoder, decoder, word_counts = _create_token_encoder(counts)
encoded_docs = _encode(tokenized_docs, encoder)
return encoded_docs, decoder, word_counts
def _count_unique_tokens(tokenized_docs):
tokens = []
for i, doc in tokenized_docs:
tokens += doc
return Counter(tokens)

def _encode(tokenized_docs, encoder):
return [(i, [encoder[t] for t in doc]) for i, doc in tokenized_docs]

def _create_token_encoder(counts):

total_tokens_count = sum(
    count for token, count in counts.most_common()
)
print('total number of tokens:', total_tokens_count)

encoder = {}
decoder = {}
word_counts = []
i = 0

for token, count in counts.most_common():
    # counts.most_common() is in decreasing count order
    encoder[token] = i
    decoder[i] = token
    word_counts.append(count)
    i += 1

return encoder, decoder, word_counts
def get_windows(doc, hws=5):
"""
For each word in a document get a window around it.

Arguments:
    doc: a list of words.
    hws: an integer, half window size.

Returns:
    a list of tuples, each tuple looks like this
        (word w, window around w),
        window around w equals to
        [hws words that come before w] + [hws words that come after w],
        size of the window around w is 2*hws.
        Number of the tuples = len(doc).
"""
length = len(doc)
assert length > 2*hws, 'doc is too short!'

inside = [(w, doc[(i - hws):i] + doc[(i + 1):(i + hws + 1)])
          for i, w in enumerate(doc[hws:-hws], hws)]

# for words that are near the beginning or
# the end of a doc tuples are slightly different
beginning = [(w, doc[:i] + doc[(i + 1):(2*hws + 1)])
             for i, w in enumerate(doc[:hws], 0)]

end = [(w, doc[-(2*hws + 1):i] + doc[(i + 1):])
       for i, w in enumerate(doc[-hws:], length - hws)]

return beginning + inside + end
`
i'm getting this error : ValueError: too many values to unpack (expected 2)
how to fix this ??

**Comment by fathia-ghribi** [comment] 2020-12-16 16:26
![image](https://user-images.githubusercontent.com/73582705/102376296-c7e86180-3fc3-11eb-9933-e4864d2561f3.png)
