### ISSUE TITLE
Product Kit returns do not update sales order invoiced and delivered quantity

### ISSUE THREAD

**Issue by Elbagoury** [odoo/odoo#53783] opened 2020-06-29 07:58 UTC
Impacted versions:
Odoo 12,11 EE & CE
Solved in Odoo 13 EE & CE

Steps to reproduce:
1-Create a Product Kit
2-Create a new Sales Order for your Kit
3-Deliver and Invoice the Sales Order
4-Return the Sales Order

Current behavior:
Invoiced and Delivered quantity in sales order line not updated

![Kit Return](https://user-images.githubusercontent.com/9639673/85988136-4857dd80-b9f7-11ea-80b1-9863c790090f.JPG)

Expected behavior:
Invoiced and Delivered quantity in sales order line should be updated if I click on (update SO/PO)

![kit return 3](https://user-images.githubusercontent.com/9639673/85990650-0335aa80-b9fb-11ea-922f-9145b1a3fd4a.JPG)

**Comment by pedrobaeza** [comment] 2020-06-29 08:04
Have you marked the check "To Refund (update SO/PO)"?

**Comment by Elbagoury** [comment] 2020-06-29 08:22
@pedrobaeza yes.

**Comment by Elbagoury** [comment] 2020-06-29 08:28
@pedrobaeza it is on odoo runbot now, item name Bagoury Kit

**Comment by Elbagoury** [comment] 2020-06-29 08:44
@pedrobaeza  , Yes, It is on [Odoo Runbot](https://3354394-12-0-7f4fcd.runbot49.odoo.com) now Odoo 12 EE, Item name **Bagoury Kit** inside **SO0038** & **SO0039**

**Comment by flotho** [comment] 2020-09-15 08:35
Hi,

I can confirm such a process either on classical refunding process.
Here is the process : 
- Create a SO with qty_ordered to 25, 
- Invoice 10 qty from this SO
- Invoice 10 more qty from this SO
- Make a refund from the second Invoice and change the qty to 5
At this time we could expect to have 10+10-5 = 15 quantity invoiced yet the Sale Order line indicates 20 qty invoiced.
The problem is that the link between SOL and AIL is reset when you create the refund invoice.
The problem is coming from this https://github.com/odoo/odoo/blob/12.0/addons/sale/models/account_invoice.py#L116 the copy False is obviously the cause of the issue.

Is it a voluntary behaviour? Adding the a.i.l to the s.o.l after this process solve the issue.

Thanks for your advice,

**Comment by Yenthe666** [comment] 2020-09-15 11:01
@amoyaux probably for your team to check!

**Comment by travish2** [comment] 2020-11-10 20:56
#55981 PR solved this for me

**Comment by Yenthe666** [comment] 2020-11-11 08:15
Awesome, closing as most likely fixed in https://github.com/odoo/odoo/commit/1dbc1c7e50556c3c111cdb8477f9dbf2b731bb10

**Closed by Yenthe666** 2020-11-11 08:15 UTC
Labels: 12.0, Logistics
