### ISSUE TITLE
[11.0] Performance problem when trying to reconcile payments with an invoice with many lines

### ISSUE THREAD

**Issue by ysantiago** [odoo/odoo#31084] opened 2019-02-13 20:16 UTC
Impacted versions:
11.0

Steps to reproduce:
* Create an invoice with a large number of lines (more than 200) all lines with tax and validate it.
* Try to reconcile many payments with the invoice created.

Current behavior:
* The reconciliation never finish.

Expected behavior:
* Payments must be reconciled with the invoice in a reasonable amount of time.

**Comment by pedrobaeza** [comment] 2019-02-13 20:20
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by moylop260** [comment] 2019-02-19 00:18
@ysantiago
You are using cash basis then it seems duplicated with
https://github.com/odoo/odoo/issues/30934

Please, could you close this one?

**Closed** 2019-02-19 02:01 UTC
Labels: 11.0, Need information
