### ISSUE TITLE
Odoo 12 CE create database with demo data, time zone automatically insert with Europe/Brussel

### ISSUE THREAD

**Issue by smartboxbiz** [odoo/odoo#27749] opened 2018-10-13 01:07 UTC
Impacted versions: 12.0

Steps to reproduce: Create new database with demo data, click username and go to Preferences, time zone will show error since it automatically filled with Europe/Brussels

Current behavior: Time zone will show error since it automatically filled with Europe/Brussels

Expected behavior: Time zone should be empty

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/3717125/46899553-00a9bf00-cebf-11e8-9d94-5bb0da2c9af5.png)

**Comment by pedrobaeza** [comment] 2018-10-13 01:49
Duplicate of #27410

**Closed by pedrobaeza** 2018-10-13 01:49 UTC

**Comment by sswapnesh** [comment] 2018-10-13 04:13
I don't think this is Duplicate. This is not about Widget, It is about Timezone in it.

**Comment by pedrobaeza** [comment] 2018-10-13 10:53
I think it's all related. When the other mess is solved, then we can judge.
