### ISSUE TITLE
Res.partner filter as per user access right.

### ISSUE THREAD

**Issue by kunalgoel1** [odoo/odoo#52203] opened 2020-05-30 12:48 UTC
**Impacted versions:** v13

**Steps to reproduce:** 
Create a customer and also create a supplier.
Create one user for with access rights of only Sales Administrator and another user with access rights of only Purchase Administrator. Now login from the sales user or purchase user.

**Current behavior:**
Sales user is able to view all Suppliers also. And vice-versa, Purchase user is able to view all customers in contacts.

**Expected behavior:**
Sales Team users should only be able to access customer contacts and purchase team users should only be able to access supplier contacts.

**Comment by sswapnesh** [comment] 2020-05-30 16:36
Because every contact is customer and supplier from Odoo 13.

**Comment by pedrobaeza** [comment] 2020-06-01 06:56
Indeed: the strict subdivision of the partners into customers and suppliers was removed because in the past, a lot of duplicates were created due to this. Now all are viewed by default, but the order is modified for showing first those with sales/purchase according the document.

Closing as no issue, but expected behavior.

**Closed by pedrobaeza** 2020-06-01 06:56 UTC
