### ISSUE TITLE
[12] Printing of documents template / tested in runbot

### ISSUE THREAD

**Issue by aitalinassim** [odoo/odoo#30577] opened 2019-01-26 16:58 UTC
**Impacted versions:**
12

**Steps to reproduce:**
Enable multi companies
In 1st company, create a RFQ and print it (pdf file)
Switch to the 2nd company
create a RFQ and print it (pdf file)

**Current behavior:**
RFQ pdf of 1st company have the logo, company address and supplier address
RFQ pdf of the 2nd company do not have logo, address and supplier coordinates

**Expected behavior:**
RFQ shall be same, just company name and address change, supplier shall be visible for both ...
Same for the other printable documents.

**Pdf of RFQ from both companies:**
[Request for Quotation - PO00073.pdf](https://github.com/odoo/odoo/files/2799244/Request.for.Quotation.-.PO00073.pdf)
[Request for Quotation - PO00037.pdf](https://github.com/odoo/odoo/files/2799245/Request.for.Quotation.-.PO00037.pdf)

**Comment by gdgellatly** [comment] 2019-01-28 06:59
As it happens I had a multicompany instance running for the express purpose of writing reports, so thought I'd check. I can't reproduce this by switching admin user between companies and printing different RFQ's. Both companies set to clean template atm, but I've been testing against all of them finetuning the scss files.

Not sure what could cause it, maybe assets regeneration fixes or maybe reloading from old file.

**Comment by pedrobaeza** [comment] 2019-02-02 01:33
I have just tried on runbot and it's working perfectly. See the result in the attachment, both with everything:

[Invoice - INV_2019_0003.pdf](https://github.com/odoo/odoo/files/2823909/Invoice.-.INV_2019_0003.pdf)
[Draft Invoice.pdf](https://github.com/odoo/odoo/files/2823910/Draft.Invoice.pdf)

So closing this for now unless further proofs are given.

**Closed by pedrobaeza** 2019-02-02 01:33 UTC
Labels: Need information
