### ISSUE TITLE
[10.0] mail: Mail Composer form removes all content upon pressing Send button 

### ISSUE THREAD

**Issue by davidtranhp** [odoo/odoo#14398] opened 2016-11-20 03:59 UTC
Impacted versions: 10.0

Steps to reproduce: in OpenChatter, open Full Composer from, type something and press Send

Current behavior: Message content is removed completely and and empty content message is sent to recipients

Expected behavior: Message content must remain

**Comment by bista-amitd** [comment] 2016-11-21 04:48
duplicate of #14381

**Comment by Yenthe666** [comment] 2016-11-21 07:15
Hi @davidtranhp,

Thanks a lot for your report! This is indeed & duplicate of 14381, so I'm closing this one.

Regards,
Yenthe

**Closed by Yenthe666** 2016-11-21 07:15 UTC
