### ISSUE TITLE
Failed to add a credit note to an invoice which having the same amount

### ISSUE THREAD

**Issue by suppliesterminal** [odoo/odoo#118367] opened 2023-04-12 15:44 UTC
Impacted versions:
Odoo 15

**Steps to reproduce:**
1. create a credit note and save
2. create an invoice with the same product and then save and confirm
3. add the credit note to the invoice

**Current behavior:**
Popped up an error window.

RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/models.py", line 5210, in ensure_one
    _id, = self._ids
ValueError: too many values to unpack (expected 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/odoo/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 910, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1326, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1318, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 464, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 451, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/addons/account/models/account_move.py", line 3186, in js_assign_outstanding_line
    return lines.reconcile()
  File "/home/odoo/src/odoo/addons/account_edi/models/account_move.py", line 688, in reconcile
    res = super().reconcile()
  File "/home/odoo/src/odoo/addons/account/models/account_move.py", line 5557, in reconcile
    not_paid_invoices\
  File "/home/odoo/src/user/odoo-graphql-st/payment_adyen_og/models/account_move.py", line 13, in action_invoice_paid
    if self.move_type == 'out_refund' and self.state == 'posted' and self.payment_state in ['paid', 'in_payment']:
  File "/home/odoo/src/odoo/odoo/fields.py", line 1075, in __get__
    record.ensure_one()
  File "/home/odoo/src/odoo/odoo/models.py", line 5213, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Expected singleton: account.move(336, 335)

Expected behavior:

Video/Screenshot link (optional):
![WX20230412-114316@2x](https://user-images.githubusercontent.com/76964092/231510871-dfe428c2-5cd0-45ce-a799-a98570c83bb6.png)
![WX20230412-114224@2x](https://user-images.githubusercontent.com/76964092/231510905-dbb272f0-3ece-403c-be5d-e446933795bd.png)
![WX20230412-114340@2x](https://user-images.githubusercontent.com/76964092/231510934-709990d9-82fa-4f8f-8ef9-08659d9e982b.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment] 2023-04-13 09:50
hi @suppliesterminal ,
from the shared trace back, it seems the issue is happening from a third party app(payment_adyen_og) and also couldn't reproduce the same in odoo runbot with the shared steps .

thanks

**Comment by jp-22** [comment] 2023-04-13 11:42
@suppliesterminal check the module (payment_adyen_og) its causing the error , it should use "for invoice in self:" and then proceed the method with "invoice" not "self" in the method "action_invoice_paid" as it gets multiple records there.

**Comment by vava-odoo** [comment] 2023-04-13 13:05
Well spotted @niyasraphy and @jp-22!
Closing the issue as it is not related to standard odoo.

**Closed by vava-odoo** 2023-04-13 13:05 UTC
Labels: Accounting, 15.0

**Comment by suppliesterminal** [comment] 2023-04-13 17:36
> hi @suppliesterminal , from the shared trace back, it seems the issue is happening from a third party app(payment_adyen_og) and also couldn't reproduce the same in odoo runbot with the shared steps .
> 
> thanks

Thank you. I will have a check.
