### ISSUE TITLE
if "Receive Inbox Notifications by Email" is set to never then sending things by email doesn't work

### ISSUE THREAD

**Issue by AlanBell** [odoo/odoo#7374] opened 2015-06-30 14:00 UTC
Default settings
- Set a partner to Receive Inbox Notifications by Email=Always
- Create a sales order and confirm it, the partner should get a "Quotation confirmed" email and be added as a follower of the order
- Send the order by email and the partner should get the full email with the PDF.

Attempting to prevent the first email:
- Now set the partner to Receive Inbox Notifications by Email=Never
- Create a sales order and confirm it, the partner will not get a notification email but will be added as a follower of the order
- Send the order by email and the partner _will not_ get the full email with the PDF.

The partner should not get emails just for being a follower of the document however if you explicitly send them an email they should get it.

**Comment by richard-willowit** [comment] 2015-07-21 05:30
+1 - We would still like to be able to explicitly send messages to a recipient, but do not want to send them general messages that come from the messaging system.

**Comment by samuellefever** [comment] 2015-07-23 08:41
+1

**Comment by spadae22** [comment] 2015-07-28 02:44
Yes I agree, customers are reporting emails they do not want. You should be able to define what they receive.

**Comment by dbertha** [comment] 2015-07-29 12:58
+1, very annoying.
I need the portal module but want to disable the "quotation send" mail notification. I'll have to write a new module to undo the effects of portal module.

**Comment by joolsr** [comment] 2015-08-04 20:52
Looking at recent runbot for how these things are handled in master (ie v9 to come), they are showing much more fine grained control of what followers can control, including about another 5 different facets that can be controlled.
![v9image](https://cloud.githubusercontent.com/assets/934876/9072390/c8c36fa4-3af2-11e5-8c9c-111936b4202f.png)

This may or may not help with your slightly different requirement, but the fact that you can choose to just allow followers to see email updates only for example, indicates that it may be best to allow inbox notifications but control more specifically what is shown on updates to followers ..

**Comment by aftabnaveed** [comment] 2015-10-15 03:07
Never means never, I think it should not let you send emails. Funny thing is there is no Control on Sale Confirmation Email that is which should be fixed and that email should not be sent automatically. That looks like a bug to me.

**Comment by AlanBell** [comment] 2015-10-15 09:59
well if it was a "do not mail" field then yes, blocking all mails would be justified - but I would want a big fat error message when I try to send them a mail rather than a silent failure, but the control I want is "don't send this person notifications", which is what the field claims to do. Customers get set as a follower of their quotes by default, so every step of the way they get update notifications - which might well not be wanted.

**Comment by proscion** [comment] 2015-10-24 09:31
@AlanBell you are so right...this feature is so annoying ! users keep complaining

**Comment by drummingbird** [comment] 2016-02-05 01:33
+1 This is a super annoying bug for website sales!

**Comment by blaggacao** [comment] 2016-04-16 05:12
@odony Who might be in charge of this one?

**Comment by blaggacao** [comment] 2016-04-16 05:18
However, allegedly, there is an option to take fine grained control of different subtypes. see image...
<img width="782" alt="capture" src="https://cloud.githubusercontent.com/assets/7548295/14579283/adee0a88-0368-11e6-8f8b-8767fbbd0fb3.PNG">


Nonwithstanding, Alan is quite right in his pledge for:
a) syntactical corrrection
b) diffenciation "notification" from "intentional (manually triggered) emails" and that this should be configurable on partners as a further drop down option on the cited field.

**Comment by blaggacao** [comment] 2016-04-16 06:58
This seems related, at least for my use case: https://github.com/odoo/odoo/commit/1b5c2ced45b508a6e86681cad47efe12c486362b (see config option in image of my last post)

**Comment by blaggacao** [comment] 2016-04-16 08:46
Here is where internal flag takes effect:
https://github.com/odoo/odoo/blob/8aee655825262c5a1b14576a239abd9496fe785e/addons/mail/models/mail_message.py#L908-L919

Another beast is the following, which marks an email as notification automatically in many cases.
https://github.com/odoo/odoo/blob/8aee655825262c5a1b14576a239abd9496fe785e/addons/mail/models/mail_mail.py#L54-L58

I'm not yet sure though if the latter (which is triggered in the described case) is responsible for the odd behaviour described by the OP.

**Comment by innovo3d** [comment] 2016-11-11 17:53
+10!

I just wasted a good part of my week before arriving at this page.  This is really annoying.  Send Email should mean exactly that.  If a user has selected "Never" for Email Notifications, that is fine for "Notifications", but I wanted to send them an EMAIL, not a notification.

Emails and Notifications are NOT the same.  If we want to give users the ability to filter them BOTH, then that's fine, create another check box in the user preferences and allow a default value.  But Emails and Notifications should definitely not be categorized as the same.  

Either that, OR the Send Email button should be renamed to "Send Message"  and any references to email should be hidden.

**Comment by pedrobaeza** [comment] 2018-04-04 22:40
Well, although it seems strange, that's the intended behavior and it's logical in its way: not receiving by email things is to not send anything. As there is the possibility of having a portal, that recipient can see also things in Odoo messaging, so it's coherent.

I close this.

**Closed by pedrobaeza** 2018-04-04 22:40 UTC
