### ISSUE TITLE
Search by date in the reconciliation wizard

### ISSUE THREAD

**Issue by zaoral** [odoo/odoo#28156] opened 2018-10-25 13:07 UTC
### Impacted versions:

11.0

### Steps to reproduce:

- Go to reconciliation wizard
- Search by date

### Current behavior:

I try to use the instance format date to search and does not work.
Only work when typing date in format YYYY-MM-DD when the regional configuration is MM/DD/YYYY

### Expected behavior:

Should be great to be able to search in the same format date MM/DD/YYYY as it is configured in the instance: this is a more logical conclusion for the not technical users.

Video/Screenshot link (optional):

https://youtu.be/2LPV_7302ic

![formato fecha asistente conciliacion 1](https://user-images.githubusercontent.com/7593953/47502364-f46a1e00-d83d-11e8-97d2-c566d8d2eb3d.png)

**Comment by zaoral** [comment] 2018-10-25 13:10
FYI OPW 1903580

**Comment by pedrobaeza** [comment] 2018-10-25 13:10
Duplicate of #28107

It's the same problem

**Comment by pedrobaeza** [comment] 2018-10-25 13:11
Please inform in the OPW about the conversation in the other issue.

**Comment by zaoral** [comment] 2018-10-25 13:15
@pedrobaeza 

How are you sure that is the same problem? Here we are talking about the date format, is not really a timezone problem as it is in https://github.com/odoo/odoo/issues/28107

**Comment by pedrobaeza** [comment] 2018-10-25 13:16
I was talking about regional configuration of your browser...

**Comment by jjscarafia** [comment] 2018-10-25 13:41
@pedrobaeza it doesn't seams to be a configuration of the browse, we have try with different browsers and OS and get the same behaviour on each of the. It is working ok on v9 but not on v11.

You can also check that the value is shown on the right date format but can only be searched by using "DEFAULT_SERVER_DATE_FORMAT"


### How user need to search:
![seleccion_688](https://user-images.githubusercontent.com/3016656/47504317-647aa300-d842-11e8-8bcc-34685ab7b90a.png)


### How user should search
![seleccion_689](https://user-images.githubusercontent.com/3016656/47504319-647aa300-d842-11e8-9527-a5a9cbecbaa7.png)


I believe this issue is not relatd with #28107

**Comment by pedrobaeza** [comment] 2018-10-25 22:16
OK, reopening.

**Comment by nim-odoo** [comment] 2018-11-23 16:07
@jjscarafia This is not working in v10 either (nor v9 I guess). Actually, in that version the date is displayed in the server format: https://screenshots.firefox.com/nOeccdRkep7OsMWF/403214-10-0-1935fb.runbot11.odoo.com

Searching works in the server format only. It might be less confusing since the display match the DB value.

So far, it's a nice-to-have, not an issue. The string entered by the user is used to search in the DB: https://github.com/odoo/odoo/blob/499cdd57083da462eec0a66bf76be18a3c703101/addons/account/models/account_move.py#L721

Such a feature can work well when a complete date is written, but when it's only partial, it becomes a nightmare to search at the DB level. Converting, for example, "06/20" into the right DB format is not straightforward. It would match "06/20/2018" or "01/06/2018". It is then probably necessary to filter the string at the JS level... Anyway, this is out of scope of a fix.

**Comment by william-andre** [comment] 2019-01-02 13:55
@nim-odoo At least, when the date is completely written in the user's lang format, it works now. Better than nothing.

**Comment by william-andre** [comment] 2019-01-10 13:53
I reworked the commit, and it is now parsing regarding to the user's locale if it can

**Comment by Yenthe666** [comment] 2019-02-11 13:21
@william-andre could you tell us what happend with this commit/PR? Any plans for it?

**Comment by william-andre** [comment] 2019-02-11 13:46
@Yenthe666 I just reminded @qdp-odoo to take a look at it

**Comment by Yenthe666** [comment] 2019-02-11 13:58
Thank you!

**Comment by C3POdoo** [comment] 2019-04-11 14:12
Dear @zaoral,

_This is an automated message._
This issue is linked to the Odoo support ticket opw-1903580 that has been closed.
We hope you got an answer to your issue.

If you believe the problem is not solved yet and would like to keep this issue open, please let us know to reopen it.

**Closed by C3POdoo** 2019-04-11 14:12 UTC
Labels: 11.0, Accounting, OE, Wishlist
