### ISSUE TITLE
[13.0] hr_holidays: print timeoff description access 

### ISSUE THREAD

**Issue by abdallamhafeez** [odoo/odoo#48537] opened 2020-03-27 16:50 UTC
Hello
I have issue when create PDF report for Timeoff request, I found that if the a does not has access to field "Description" and appears in form view as "****" but when print report contain this field, PDF appears field value. I investigate and found that function "_read" does not call:   https://github.com/odoo/odoo/blob/c87db90d5dbab4d02a9378a1fc905c9b2935cbe2/addons/hr_holidays/models/hr_leave.py#L671

**Comment by pedrobaeza** [comment] 2020-03-27 16:57
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by abdallamhafeez** [comment] 2020-03-27 21:48
Hello
I create a custom PDF report from Time off to allow employees to sign it so that I can not reproduce the issue in runbot. 

It is not a functional issue but technical as PDF report does not check function `_read` in class Model, as for example restriction in  model `hr.leave` that make field `name` appear as `****` based on user login in this function https://github.com/odoo/odoo/blob/c87db90d5dbab4d02a9378a1fc905c9b2935cbe2/addons/hr_holidays/models/hr_leave.py#L671

**Comment by pedrobaeza** [comment] 2020-05-08 19:57
Sorry, but the steps are still not clear, so closing. You can reissue with clearer steps.

**Closed by pedrobaeza** 2020-05-08 19:57 UTC
Labels: Need information
