### ISSUE TITLE
Runtime Error: Error: QWeb2 - template['message_item']: Error evaluating template: SyntaxError: missing ] in index expression

### ISSUE THREAD

**Issue by aliencrash** [odoo/odoo#32292] opened 2019-04-01 10:58 UTC
Impacted versions:
12.0
Steps to reproduce:
If we have a expression like in my ir.client.action for the backend it gives error.
`<t t-set="mystring" t-value="'we love odoo'"/>
<t t-esc="mystring[0:6]"/>
`
The expression works well for reports and for Website in frontend.
Current behavior:
Error: QWeb2 - template['messages_container']: Runtime Error: Error: QWeb2 - template['message_item']: Error evaluating template: SyntaxError: missing ] in index expression

http://0.0.0.0:8069/web/content/13441-24af0c2/web.assets_common.js:3374
Traceback:
exception@http://0.0.0.0:8069/web/content/13441-24af0c2/web.assets_common.js:3374:7
anonymous@http://0.0.0.0:8069/web/content/13441-24af0c2/web.assets_common.js line 3416 > Function:42:8
_render@http://0.0.0.0:8069/web/content/13441-24af0c2/web.assets_common.js:3415:262
render@http://0.0.0.0:8069/web/content/13441-24af0c2/web.assets_common.js:3415:146
_render@http://0.0.0.0:8069/web/content/13441-24af0c2/web.assets_common.js:3419:52
render@http://0.0.0.0:8069/web/content/13441-24af0c2/web.assets_common.js:3415:146
renderElement@http://0.0.0.0:8069/web/content/13441-24af0c2/web.assets_common.js:3673:1004
_widgetRenderAndInsert/<@http://0.0.0.0:8069/web/content/13441-24af0c2/web.assets_common.js:3683:1
then/</</<@http://0.0.0.0:8069/web/content/13441-24af0c2/web.assets_common.js:802:678
fire@http://0.0.0.0:8069/web/content/13441-24af0c2/web.assets_common.js:796:281
add@http://0.0.0.0:8069/web/content/13441-24af0c2/web.assets_common.js:797:467
then/</<@http://0.0.0.0:8069/web/content/13441-24af0c2/web.assets_common.js:802:649
each@http://0.0.0.0:8069/web/content/13441-24af0c2/web.assets_common.js:625:758
then/<@http://0.0.0.0:8069/web/content/13441-24af0c2/web.assets_common.js:802:553
Deferred@http://0.0.0.0:8069/web/content/13441-24af0c2/web.assets_common.js:803:189
then@http://0.0.0.0:8069/web/content/13441-24af0c2/web.assets_common.js:802:518
_widgetRenderAndInsert@http://0.0.0.0:8069/web/content/13441-24af0c2/web.assets_common.js:3682:165
appendTo@http://0.0.0.0:8069/web/content/13441-24af0c2/web.assets_common.js:3673:92
_onClickGetEmailsInFolders/data_emails<@http://0.0.0.0:8069/web/content/13502-70d4ec3/web.assets_backend.js:2501:294
then/</</<@http://0.0.0.0:8069/web/content/13441-24af0c2/web.assets_common.js:802:678
fire@http://0.0.0.0:8069/web/content/13441-24af0c2/web.assets_common.js:796:281
fireWith@http://0.0.0.0:8069/web/content/13441-24af0c2/web.assets_common.js:801:198
Deferred/</deferred[tuple[0]]@http://0.0.0.0:8069/web/content/13441-24af0c2/web.assets_common.js:803:56
genericJsonRpc/<@http://0.0.0.0:8069/web/content/13441-24af0c2/web.assets_common.js:3557:1
then/</</<@http://0.0.0.0:8069/web/content/13441-24af0c2/web.assets_common.js:802:678
fire@http://0.0.0.0:8069/web/content/13441-24af0c2/web.assets_common.js:796:281
fireWith@http://0.0.0.0:8069/web/content/13441-24af0c2/web.assets_common.js:801:198
then/</</<@http://0.0.0.0:8069/web/content/13441-24af0c2/web.assets_common.js:802:874
fire@http://0.0.0.0:8069/web/content/13441-24af0c2/web.assets_common.js:796:281
fireWith@http://0.0.0.0:8069/web/content/13441-24af0c2/web.assets_common.js:801:198
done@http://0.0.0.0:8069/web/content/13441-24af0c2/web.assets_common.js:1192:86
callback@http://0.0.0.0:8069/web/content/13441-24af0c2/web.assets_common.js:1212:15

Expected behavior:
I should return <span>we lov</span>
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2019-04-01 11:00
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by aliencrash** [comment] 2019-04-01 11:02
I will simulate there

**Comment by Yenthe666** [comment] 2019-05-23 13:41
@aliencrash can you please add the additional info in? Otherwise we cannot help you further and this issue will soon be closed.

**Comment by Yenthe666** [comment] 2019-07-31 14:39
Hi there,

I'm closing this bug report as there has been no more feedback on the last question. We assume that the problem has been solved in the meanwhile. If this is not the case then don't hesitate to respond back (with feedback) and we'll reopen it.

Regards,
Yenthe

**Closed by Yenthe666** 2019-07-31 14:39 UTC
Labels: Need information
