### ISSUE TITLE
No negative symbol on pdf invoice

### ISSUE THREAD

**Issue by nmeen** [odoo/odoo#17093] opened 2017-05-19 07:26 UTC
Impacted versions: ODOO 10

Problem.
If i print a invoice with a negative amount, the pdf shows a vertical bar instead of a minus symbol.
![image](https://cloud.githubusercontent.com/assets/28800797/26237253/b07fadb0-3c74-11e7-86c2-c8688d82b5a5.png)

I have tried to install a new pdf reader, but with no result.

**Comment by Yenthe666** [comment] 2017-05-19 09:50
@Gorash and @sle-odoo probably for you?

**Comment by badiatarigan** [comment] 2017-10-04 06:11
I have some problem..
how to change negetive simbol?
please advise..
thanks

**Comment by Yenthe666** [comment] 2017-12-06 12:27
@sle-odoo could you give an update please?

**Comment by flotho** [comment] 2017-12-06 12:28
Hi @Yenthe666 thanks for pointing this one.
@sle-odoo , any special font could be needed ?

**Comment by sle-odoo** [comment] 2017-12-06 13:09
I don't have any update for this sadly, as i'm not able to reproduce the issue. Could you please share with us your deployment's detail? It seems like a fontconfig issue, but with a classical install of any recent debian or ubuntu it should work properly.

**Comment by flotho** [comment] 2017-12-06 14:17
Maybe this one could help : https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3017

**Comment by flotho** [comment] 2017-12-06 15:03
Hi,
Installing the fonts dejavu solve my issue :
```
yum install dejavu-sans-fonts*
```

**Comment by Yenthe666** [comment] 2017-12-06 15:06
@nmeen could you try this too please?

**Comment by flotho** [comment] 2017-12-06 15:59
@nmeen , maybe you could also check in your general settings which fonts are available

**Comment by LFCPirex** [comment] 2017-12-13 19:17
Hi, 

I believe I have a particular setup since I'm running Odoo on a Windows 7 machine, however even after installing the DejaVu fonts (https://dejavu-fonts.github.io/), I have a vertical bar instead of the minus sign.

I'm new to Odoo, so I don't understand so well the QWeb reports, but could somebody point me to the invoice report, maybe I can have a look and see if something else is missing in my setup.

**Comment by gdgellatly** [comment] 2017-12-14 07:10
My experience with this is that it is the font embedded in the whtlmtopdf process.  Standard webfonts often have issues, bad kerning, missing symbols, poor spacing accuracy etc and its a bit platform/installation specific.  

Ordinarily what I do is create a separate less file for reports and declare all new fonts (e.g. Work Sans2, Lato2, or Helvetica2) pointing to the a ttf or otf either Latin or Extended implementation to get a nice clean print embedded in it compared to WOFF.  If you try and just add them to the font-family or font-face it always picks the webfont so doing it this way you lose the debug with Wysiwyg HTML looking the same.

Just look in the properties of your pdf, it will tell you what fonts are being embedded.

**Comment by tahirlanre** [comment] 2017-12-22 04:16
Hello @sle-odoo, I have same problem. I am running Odoo 10 on Windows Server 2012. I also have this problem on Windows 7

**Comment by sle-odoo** [comment] 2017-12-28 13:15
@tahirlanre could you try the suggestion of gdgellatly and see what's the embedded font in the pdf and replace it in your system?

**Comment by tahirlanre** [comment] 2017-12-29 16:31
Ok, thanks @sle-odoo. Can you quickly guide me on how to create a separate less file for all reports on odoo?

**Comment by gdgellatly** [comment] 2017-12-29 23:08
@tahirlanre You need to do it for each report format.  It's pretty easy.

an assets file with something like

```xml
    <template id="report_assets_common" inherit_id="web.report_assets_common" active="True" name="Replacement Fonts">
        <xpath expr="link[last()]" position="after">
            <!--<script type="text/javascript" src="/fonts_replace/static/src/js/fonts.js"></script>-->
            <link href="/fonts_replace/static/src/less/layout_clean.less" rel="stylesheet" type="text/less"/>
        </xpath>
    </template>
```

Then a less file with something like for the problematic classes
```less
.o_report_layout_clean {
  .invoice_tbody {
    font-family: <some other font family>;
  }
```

But your problem at the moment is more the font files.  Check the embedded fonts, and replace them in Windows.   See the last post here https://answers.acrobatusers.com/When-I-print-Adobe-PDF-strange-symbols-document-q1929.aspx

**Comment by tahirlanre** [comment] 2017-12-30 05:25
Many thanks @gdgellatly

**Comment by pdesmarets** [comment] 2018-03-05 16:58
If I may add some observations...  On the same Windows 10 PC with the same Chrome 64 browser, and the same Acrobat Reader:
- if I generate an invoice or quotation from a test on-premises windows community install of Odoo 11, I get the negative sign issue
![image](https://user-images.githubusercontent.com/10139210/36987980-e6dc144e-209d-11e8-9d37-cc46c9a10d0d.png)
- if I generate an invoice or quotation from the cloud-based test of Odoo, everything works fine:
![image](https://user-images.githubusercontent.com/10139210/36988054-173509e8-209e-11e8-9e97-9ea5a70abc27.png)

It therefore seems to me that the issue is server side-related.  BTW, the same behavior as described above remains, even after installing the dejavu-sans fonts and following all the steps in https://answers.acrobatusers.com/When-I-print-Adobe-PDF-strange-symbols-document-q1929.aspx

However, I am no savvy enough to know how to implement the last suggestion of @gdgellatly

Any help would be greatly appreciated!  Thanks!

**Comment by mkmk89** [comment] 2018-05-07 11:00
I have exactly the same issue on Windows Server 2016 Odoo v11. I installed Dejavu fonts, but that is not resolving the issue. HTML templates are working, fine, when printed to PDF it replaces - with |

**Comment by raishak6** [comment] 2018-05-19 09:38
As far as Windows 10 is concerned, I think this is just an OS Version/Build issue. I experienced the same problem on my Windows OS generally and Initially I thought it was a Windows OS non-compatibility issue with Odoo, but my assumption changed when I got a new PC with a very recent Windows 10 Pro Edition and when I launched Odoo on it the negative sign was coming out correctly in all PDF reports.
However, another PC with Windows 10 Home Edition was still having the issue but when I updated that one too to the latest Home Edition the error vanished completely.
So in a nut shell if your system is Windows 10 simply update your OS and that should resolve the problem.

I am yet to test the effect of the OS update on Windows 7 and any Windows Server.

**Comment by pedrobaeza** [comment] 2018-05-19 11:18
Closing this as an OS specific thing.

**Closed by pedrobaeza** 2018-05-19 11:18 UTC
Labels: 10.0, Framework

**Comment by nle-odoo** [comment] 2018-07-27 15:49
Hi @nmeen  

This should be solved in 9.0 with https://github.com/odoo/odoo/commit/cb2a3afa7e0

To have the solution available in 10.0, you have to wait for forward-port from 9.0 to 10.0 (the last one was 2 days ago) that should be done at the latest in one week, and once it is in 10.0 the installation bundles should be updated the day after.

Regards.

**Comment by hamidalouani** [comment] 2018-08-21 16:06
hi,
i resolved the problem odoo 10 windows Xp
after install font dejavusans (in windows/fonts)
go to :  \Odoo 10.0\server\odoo\addons\report\static\src\css
edit css file "reset.min.css"

add in the begin of file after this line :
background: transparent;
the new line to add :
font-family: DejaVuSans;

the results is like this :

/*

HTML5 CSS Reset
Based on Eric Meyer's CSS Reset
and html5doctor.com HTML5 Reset

Copyright (c) 2011 736 Computing Services Limited
Released under the MIT license. http://opensource.736cs.com/licenses/mit

*/

html, body, div, span, applet, object, iframe,
h1, h2, h3, h4, h5, h6, p, blockquote, pre,
a, abbr, acronym, address, big, cite, code,
del, dfn, em, font, img, ins, kbd, q, s, samp,
small, strike, strong, sub, sup, tt, var,
b, i, center, dl, dt, dd, ol, ul, li,
fieldset, form, label, legend,
table, caption, tbody, tfoot, thead, tr, th, td,
article, aside, audio, canvas, details, figcaption,
figure, footer, header, hgroup, mark, menu, meter, nav,
output, progress, section, summary, time, video {
	margin: 0;
	padding: 0;
	border: 0;
	outline: 0;
	font-size: 100%;
	vertical-align: baseline;
	background: transparent;
	font-family: DejaVuSans;
}

........

save the file and print your pdf view.

**Comment by hamidalouani** [comment] 2018-08-21 17:52
if dont work : reboot service odoo-server-10 in windows services

**Comment by nle-odoo** [comment] 2018-08-22 06:16
Hi @hamidalouani 

The issue was that the special `-` character used (that is special so it is not split from the following number) is not represented in the font and some version of windows the font system would not fallback on the right character.

Thus your solution is good, thanks. When testing the same with `Segoe UI` (which was installed by default in the faulty windows), it was solved for me as well.

But hopefully it was already solved with https://github.com/odoo/odoo/commit/cb2a3afa7e0 which was forward-ported on July 30 (with https://github.com/odoo/odoo/commit/3a14b75518ab5c9a62dfb0238e9c5f04d957a25f) so another solution is updating the code from that date (updating the code and restarting the server should be enough).

**Comment by raishak6** [comment] 2018-09-02 07:00
Hi @hamidalouani,

Thanks for the update, I've tried on my Windows 2016 Server and it worked.

Regards
