### ISSUE TITLE
Error when dealing with Arabic numbers (hindi)

### ISSUE THREAD

**Issue by akram1** [odoo/odoo#42725] opened 2020-01-05 14:21 UTC
###Impacted versions: 13

###Steps to reproduce:
Make sure you have Arabic installed and used
Install Time off
get into time off
click on the second menu item (All)

####Current behavior:
raised and error
خطأ:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo13/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo13/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo13/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo13/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo13/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo13/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo13/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo13/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo13/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo13/addons/web/controllers/main.py", line 1277, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/opt/odoo13/addons/web/controllers/main.py", line 1296, in do_search_read
    return Model.web_search_read(domain, fields, offset=offset, limit=limit, order=sort)
  File "/opt/odoo13/addons/web/models/models.py", line 36, in web_search_read
    records = self.search_read(domain, fields, offset=offset, limit=limit, order=order)
  File "/opt/odoo13/odoo/models.py", line 4808, in search_read
    records = self.search(domain or [], offset=offset, limit=limit, order=order)
  File "/opt/odoo13/odoo/models.py", line 1601, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/opt/odoo13/odoo/models.py", line 4371, in _search
    self._cr.execute(query_str, where_clause_params)
  File "/opt/odoo13/odoo/sql_db.py", line 163, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo13/odoo/sql_db.py", line 240, in execute
    res = self._obj.execute(query, params)
psycopg2.DataError: invalid input syntax for type timestamp: "٢٠٢٠-٠١-٣١ ٢٠:٥٩:٥٩"
LINE 1: ...state" IS NULL))  AND  ("hr_leave"."date_from" <= '٢٠٢٠-٠١-٣...

###Expected behavior:
Show all time off

###Video/Screenshot link (optional):

**Comment by akram1** [comment] 2020-01-05 19:44
you may need to change locale to Arabic country. mine is YE

**Comment by pedrobaeza** [comment] 2020-01-06 00:29
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by akram1** [comment] 2020-01-06 10:53
I run runbot, it looks eveything is ok here are the screen shots. Mine gives the error described above. My server is standard debian 9u2. I just upgraded and upgrade psycopg2 ro 2. python is 3.7 and system locale is UFT8 US. the problem remains the same.

![Screenshot_2020-01-06_12-13-32](https://user-images.githubusercontent.com/6378526/71813603-235b6100-308b-11ea-81bb-1fcf8deff286.png)
![Screenshot_2020-01-06_12-09-38](https://user-images.githubusercontent.com/6378526/71813614-2bb39c00-308b-11ea-96d8-9f89c9868571.png)
![Screenshot_2020-01-06_12-09-53](https://user-images.githubusercontent.com/6378526/71813616-2bb39c00-308b-11ea-86bb-7af3235a901f.png)
![Screenshot_2020-01-06_12-10-52](https://user-images.githubusercontent.com/6378526/71813618-2c4c3280-308b-11ea-8e38-bd86812f4184.png)
![Screenshot_2020-01-06_12-12-19](https://user-images.githubusercontent.com/6378526/71813619-2c4c3280-308b-11ea-8400-e2d5845fa9fb.png)
![Screenshot_2020-01-06_12-13-03](https://user-images.githubusercontent.com/6378526/71813620-2ce4c900-308b-11ea-9f40-106274e3fa68.png)

**Comment by akram1** [comment] 2020-01-06 10:58
some correction:  I just upgraded apt get upgrade and upgrade psycopg2 to 2.8.

pip3 list

 Package           Version                                                      
----------------- -----------                                                  
appdirs           1.4.3                                                        
attrs             19.3.0                                                       
Babel             2.3.4                                                        
beautifulsoup4    4.8.1                                                        
cached-property   1.5.1                                                        
certifi           2019.9.11                                                    
chardet           3.0.4                                                        
decorator         4.0.10                                                       
defusedxml        0.6.0                                                        
docutils          0.12                                                         
ebaysdk           2.1.5                                                        
feedparser        5.2.1                                                        
gevent            1.3.4                                                        
greenlet          0.4.13                                                       
html2text         2016.9.19                                                    
idna              2.7                                                          
isodate           0.6.0                                                        
Jinja2            2.10.1                                                       
libsass           0.12.3                                                       
lxml              4.2.3                                                        
Mako              1.0.4                                                        
MarkupSafe        0.23                                                         
mock              2.0.0                                                        
num2words         0.5.6                                                        
ofxparse          0.16                                                         
passlib           1.6.5                                                        
pbr               5.4.3                                                        
Pillow            5.4.1                                                        
pip               19.3.1                                                       
polib             1.1.0                                                        
psutil            4.3.1                                                        
psycopg2          2.8.4                                                        
pydot             1.2.3                                                        
pyldap            2.4.28                                                       
pyparsing         2.1.10                                                       
PyPDF2            1.26.0                                                       
pyserial          3.1.1                                                        
Python-Chart      1.39                                                         
python-dateutil   2.5.3                                                        
python-openid     2.2.5                                                        
python-stdnum     1.11                                                         
pytz              2016.7                                                       
pyusb             1.0.0                                                        
PyYAML            5.1.2                                                        
qrcode            5.3                                                          
reportlab         3.3.0                                                        
requests          2.20.0                                                       
requests-toolbelt 0.9.1                                                        
setuptools        39.0.1                                                       
Shapely           1.6.4.post2                                                  
simplejson        3.16.0                                                       
six               1.12.0                                                       
soupsieve         1.9.4                                                        
suds-jurko        0.6                                                          
urllib3           1.24.3                                                       
vatnumber         1.2                                                          
vobject           0.9.3                                                        
Werkzeug          0.14.1                                                       
xlrd              1.0.0                                                        
XlsxWriter        0.9.3                                                        
xlwt              1.3.0                                                        
zeep              3.1.0

**Comment by pedrobaeza** [comment] 2020-01-07 01:19
Then the problem is in your deployment, so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/13.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).

**Closed by pedrobaeza** 2020-01-07 01:19 UTC
Labels: Need information
