### ISSUE TITLE
[9.0] Adding item to invoice - VAT not added automatically

### ISSUE THREAD

**Issue by katsele** [odoo/odoo#10887] opened 2016-02-11 15:25 UTC
Hello, 

I couldn't figure out why VAT is not adding automatically when I'm adding an item to my invoice. In the settings I added the default VAT to 21%, and still I have to select VAT in the list... Is there a way to auto add VAT? 

Best regards, 
Katsele.

**Comment by flotho** [comment] 2016-02-11 22:44
Hi @katsele 

Have you got a VAT set on the product itself?
FYI, many problems on VAT in v9 :
* https://github.com/odoo/odoo/issues/10863
* https://github.com/odoo/odoo/issues/10648
* https://github.com/odoo/odoo/issues/10892

**Comment by Yenthe666** [comment] 2016-06-13 08:12
Hi @katsele,

I can no longer reproduce this bug on the latest code. An example product:
![image](https://cloud.githubusercontent.com/assets/6352350/16000868/312fb09a-314f-11e6-817b-b848ef58b51a.png)
An invoice where I've added the product:
![image](https://cloud.githubusercontent.com/assets/6352350/16000885/468cd99a-314f-11e6-9fc7-ba7f1b3dcaf0.png)
After clicking on save the tax is also applied on the total:
![image](https://cloud.githubusercontent.com/assets/6352350/16000890/563061f0-314f-11e6-90d9-2c507bf3fb48.png)

Closing this issue since it can no longer be reproduced.
Please update your Odoo to the latest codebase.

Regards,
Yenthe

**Closed by Yenthe666** 2016-06-13 08:12 UTC
