### ISSUE TITLE
It is not possible to unreserve more products of than you have in  stock.

### ISSUE THREAD

**Issue by koz01** [odoo/odoo#32941] opened 2019-04-25 08:25 UTC
Version: Version 12 Enterprise

Not use Multi UOM.

Case: When click on Validate Button on delivery order showing this message. Not all the product is happened.
![error](https://user-images.githubusercontent.com/16234060/56721126-40a10700-676a-11e9-9edc-0d2495a2a48b.jpg)

**Comment by pedrobaeza** [comment] 2019-04-25 09:22
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by koz01** [comment] 2019-04-25 10:41
1. We sell the product on POS without onhand.
2. We sell the product on Sale.And then we not click DO validate.
3. After three day, We click Validate for Waiting and Ready DO shipment.
4. Facing this Error.

**Comment by pedrobaeza** [comment] 2019-04-25 10:44
Sorry, but this is not happening on standard, so you should have something misconfigured, and that's why I ask to be reproduce in runbot and with which data.

**Comment by koz01** [comment] 2019-04-25 10:54
Odoo never takes responsibility for All Issue.

**Closed** 2019-04-25 11:00 UTC
Labels: Need information

**Comment by pedrobaeza** [comment] 2019-04-25 14:19
The same answer than https://github.com/odoo/odoo/issues/32940#issuecomment-486692418

**Comment by h4818** [comment] 2019-08-15 06:19
Seems like something to do with POS and purchases

https://www.odoo.com/forum/help-1/question/it-is-not-possible-to-unreserve-more-products-of-than-you-have-in-stock-138783

**Comment by gnfranco** [comment] 2022-03-03 02:21
To reproduce this do you have exceeded precision for one UOM. For exempla if you uses liter to buy a SKU and use milliliters to consume it into an Manufacturer Order you probably will have some problems sooner or later.
