### ISSUE TITLE
[12.0][13.0] Deselect lot or select lot without sufficient qty on picking, inventory is unreserved and cannot be re-reserved

### ISSUE THREAD

**Issue by aliomattux** [odoo/odoo#43163] opened 2020-01-12 23:17 UTC
Impacted versions:
12.0, 13.0
Steps to reproduce:
Create new database, install purchase, stock, sale
enable lot tracking with expiration dates
Create product test with lot tracking enabled
purchase and receive quantity 100 to stock with lot 12345
Create sale order for 1 qty of test product and confirm
on delivery order under detailed operations delete lot from auto assigned 12345 and click save.
Quantity reserved = 0
There is no possible way in the UI to re-reserve inventory. If I select again lot 12345 or any other lot with available inventory, inventory reservation is not triggered
Current behavior:
System allows creation of an impossible to recover from inventory reservation issue
Expected behavior:
After the reserved qty is set to 0, I should be able to select a lot with available inventory and re-reserve. Also, the unreserve button should not be visible when there is no reserved qty
![2020-01-12_17-17-30](https://user-images.githubusercontent.com/1051273/72227214-76d42000-355f-11ea-956b-3b29fe063f84.png)

Video/Screenshot link (optional):

**Comment by aliomattux** [comment] 2020-01-12 23:20
Scenario 2.
Create 2 lots. 12345, 6789
Receive qty 100 from a new PO to lot 12345.
Create sales order for 1x qty of test product and confirm
On delivery order change lot from 12345 to 6789 and save. Reserved qty now = 0.
Edit delivery order and re-select lot 12345. Nothing happens and no button/option to re-reserve inventory.

The unreserve button unreserves inventory for the entire outgoing shipment. Only the specific line item needs resolution, and only the change of a lot.

Picking process is that the picker goes to a shelf with potentially hundreds of serial numbers. Picker will pick a random serial number and confirm it in the system. If there is any kind of inventory issue, the picking will be trapped and a significant process required to correct the issue due to current functionality limitation.

**Comment by pedrobaeza** [comment] 2020-01-12 23:57
Can you please put screenshots of all the steps (or a video) to be sure on your steps to reproduce the problem?

**Comment by aliomattux** [comment] 2020-01-13 00:03
Here are some additional screenshots, but the steps are quite simple and should be easy to reproduce. I tested twice using only the core module installed and only 1 product and 2 serials.
Before edit
![2020-01-12_18-01-15](https://user-images.githubusercontent.com/1051273/72227752-b7369c80-3565-11ea-9ea5-9aacfac2eed1.png)

Delete contents of serial field
![Uploading 2020-01-12_18-01-40.png…]()

Press Save
![2020-01-12_17-17-30](https://user-images.githubusercontent.com/1051273/72227759-c87fa900-3565-11ea-8fa1-da013ae59205.png)

**Comment by aliomattux** [comment] 2020-01-13 04:11
I spent some time studying the code and you can see the issue better,
stock/models/stock_move_line.py
in def write

what happens is when any field change and write happens, all qty are unreserved using the quant function _update_reserved_quantity(). It then tries to reserve again using the same function except a positive of product_qty which is computed field.
When the inventory reservation is initially unreserved, the computed field now stuck at 0 so when the function on quant _update_reserved_quantity() is called again, it passes 0.

My temporary fix in testing is to store the original quantity reserved in a new field and then use that reference when reserving the inventory again. This will allow me to bypass the issue but i'm looking at improving the reservation of lots using the stock move line. I may create some custom mobile interface to split and more user friendly re-reserve inventory to specific lots

**Comment by pedrobaeza** [comment] 2020-01-13 08:44
@amoyaux @sle-odoo can you take a look to this?

**Comment by sle-odoo** [comment] 2020-01-13 08:55
@aliomattux indeed, when you edit a move line and the new characteristics are unavailable in stock, the product_uom_qty goes to zero and if you edit it again, it doesn't re-reserve. That's because we don't have a kind of "qty_to_do" fields on the move line. So your fix is correct ..
> store the original quantity reserved in a new field

.. but it was considered "overkill" in standard.

about this one
> Also, the unreserve button should not be visible when there is no reserved qty

we'll have a look, thanks for the report

**Comment by sle-odoo** [comment] 2020-01-28 15:32
fixed by https://github.com/odoo/odoo/pull/43979 in v13, we'll see if backporting is needed

thanks for the detailed issue

**Closed by sle-odoo** 2020-01-28 15:32 UTC
Labels: 12.0, 13.0, Logistics
