### ISSUE TITLE
"Insufficient Credit" to Auto-populate Comany Data und runbot - unable to test this feature

### ISSUE THREAD

**Issue by technicomp** [odoo/odoo#27670] opened 2018-10-11 10:16 UTC
Impacted versions: 12 / Runbot

Steps to reproduce: Settings / General Settings

Current behavior: 

Auto-populate company data not working - 
Autocomplete company data (name, logo, address, etc.)
**Insufficient credit**

**Comment by pedrobaeza** [comment] 2018-10-11 10:18
This is because it's an IAP, that requires to pay per use.

Closing as no issue.

**Closed by pedrobaeza** 2018-10-11 10:18 UTC

**Comment by pedrobaeza** [comment] 2018-10-11 10:28
Well, then you should stick to the other issue instead of this one, as this one is clear: you can't activate it while you don't have credits.

**Comment by technicomp** [comment] 2018-10-11 10:32
I think you don´t get the problem - since there are no credits available on the runbot installations anymore, the errors in the open tickets #27419 and #27422  can not be reproduced in this enviroment.

**Comment by pedrobaeza** [comment] 2018-10-11 10:39
Yeah, I get it, but the chicken-egg problem is there: you can't solve problems for paid services if there's no credit for trying them. This is something broader, and a sandbox/free testing support should be added by IAP providers, but for now it's not possible.

@mart-e what is the official position about this?

**Comment by technicomp** [comment] 2018-10-11 10:52
Will @mart-e also respond to a closed ticket?

**Comment by pedrobaeza** [comment] 2018-10-11 10:56
Yes, @technicomp, that's not a problem to comment as you are doing right now.

**Comment by mart-e** [comment] 2018-10-11 11:45
Check the [IAP documentation](https://www.odoo.com/documentation/12.0/webservices/iap.html), you can use the sandbox address https://iap-sandbox.odoo.com/
You won't be credited for the purchase of packs.

**Comment by pedrobaeza** [comment] 2018-10-11 11:55
Great that there's that option! Which code version is running? Always latest one?

**Comment by mart-e** [comment] 2018-10-11 11:57
I am not sure to understand the question. iap.odoo.com and iap-sandbox should be always synced, the Odoo version they are running is not really relevant.
But @rrahir can probably answer to that.

**Comment by pedrobaeza** [comment] 2018-10-11 11:58
Well, I'm talking that if there's a problem in the code and it's solved in latest revisions, then this saas sandbox version might not contain that fix.

**Comment by rrahir** [comment] 2018-10-11 12:07
Hi, the code running on iap and iap-sanbox are the same, we only enable the 'sandbox mode' on the latest. Also, both servers are updated whenever a fix or an improvement is published :)

**Comment by pedrobaeza** [comment] 2018-10-11 12:09
Great, thanks for the confirmation. @technicomp then you can try against that server to check if the problem is solved.

**Comment by technicomp** [comment] 2018-10-11 16:28
Sorry, I don´t get it - how can I test a problem related to something that works only with credits available on the runbot if the runbot itself has insufficient credits?

**Comment by mart-e** [comment] 2018-10-12 08:31
@technicomp your question was regarding testing an existing application, not testing the application you are developing, sorry for the confusion.
I am afraid that is not possible, we do not have some "free trial" mode at the moment.

**Comment by technicomp** [comment] 2018-10-12 10:48
Yes, it is about testing the existing application, actually it is about on of the core functionalities of odoo - contacts. As you can see also in the attached video of one of the tickets, it is about the simple task of creating a new contact. #27419 and #27422 are about basic functionality - can you reproduce these odoo bugs without credits? I guess not.
