### ISSUE TITLE
[9.0] Radio widget defaults to value of previously viewed record instead of empty when creating new record

### ISSUE THREAD

**Issue by osluys** [odoo/odoo#11065] opened 2016-02-23 11:05 UTC
Impacted versions:
Odoo 9.0, Windows 10, Firefox 44

Steps to reproduce: 
- Create a form view with a selection field that has **no default value** and display it as a radio widget.
- Create several records, selecting different radio button values.
- Go to the tree view and randomly select a record to view.
- Within the form view, create a new record.

Current behavior:
The radio widget automatically selects the previous value of the record you were just viewing. Creating a record directly from the tree view without first viewing a record works as expected, i.e. nothing is selected for the radio widget. Specifying a default value of `False` on the field does not change the behavior.

Expected behavior:
There should be nothing selected for the radio widget.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2018-04-17 23:39
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed by pedrobaeza** 2018-04-17 23:39 UTC
Labels: 9.0
