### ISSUE TITLE
[14.0] server error when trying to update module from the updates menu.

### ISSUE THREAD

**Issue by FedericoLaTorre** [odoo/odoo#72902] opened 2021-06-29 05:25 UTC
Impacted versions: 14.0

Steps to reproduce: enter apps, updates and try to update any module

Current behavior: system error

Expected behavior: module update

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 1389, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: button_immediate_upgrade() takes 1 positional argument but 2 were given

**Comment by pedrobaeza** [comment] 2021-06-29 06:34
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by straga** [comment] 2021-07-07 11:31
If push upgrade button inside module what work ok.
args = {list:0} [] - empty list that right.
But if push blue button - args = {list:1} [{}]
It happen for that module.
https://github.com/straga/odoo_vik_main/tree/14.0/web_widget_colorpicker

**Comment by yelizariev** [comment] 2021-07-07 11:59
@straga could you send screenshots which buttons work and which don't

**Comment by straga** [comment] 2021-07-07 13:05
https://youtu.be/siQPvhlHRoU

**Comment by yelizariev** [comment] 2021-07-07 13:55
`Updates` menu seems not maintained. Maybe it should be deleted (in master)

**Comment by straga** [comment] 2021-07-07 14:13
Ok. Some peoples use that. Sometimes asked me why doesn't work.

**Closed** 2023-04-07 13:01 UTC
Labels: Need information
