### ISSUE TITLE
Not able to cancel SO

### ISSUE THREAD

**Issue by goyanipankaj** [odoo/odoo#28980] opened 2018-11-23 10:23 UTC
Impacted versions:
Odoo 12.0

Steps to reproduce:
1> Create Tender from SO 
2> After created tender then try to cancel SO.
Got the error!
if requisition_line.state not in ('done', 'cancel')]
  File "/home/bista/workspace/odoo-12/addons/purchase_requisition/models/purchase_requisition.py", line 492, in <listcomp>
    return [(requisition_line.requisition_id, requisition_line.requisition_id.user_id, visited) for requisition_line in self.requisition_line_ids if requisition_line.state not in ('done', 'cancel')]

Current behavior:
Get error when try to cancel SO.

Expected behavior:
Requisition line have not state.

Video/Screenshot link (optional):
![issue](https://user-images.githubusercontent.com/8874012/48938650-d9232900-ef37-11e8-9ba8-6c278efa2075.png)

**Comment by pedrobaeza** [comment] 2018-11-23 10:47
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Yenthe666** [comment] 2018-11-23 10:55
@pedrobaeza clearly a bug in Odoo as you can see the field `state` does indeed not exist anymore:
https://github.com/odoo/odoo/blob/b3052b690fad15feb3211525666d4962bc1a24ac/addons/purchase_requisition/models/purchase_requisition.py#L191-L207

**Comment by goyanipankaj** [comment] 2018-11-23 11:12
Yes, I have checked on Runbot and get the same issue.
Please check: http://403228-12-0-99801f.runbot15.odoo.com with admin user.

**Comment by pedrobaeza** [comment] 2018-11-23 11:13
Thanks for confirming. Correctly labelled by my colleague Yenthe and will be handled by Odoo team.

**Comment by sswapnesh** [comment] 2018-12-21 19:33
Added Fix: https://github.com/odoo/odoo/pull/29715

**Comment by sswapnesh** [comment] 2018-12-26 17:43
Solved in https://github.com/odoo/odoo/commit/595209a3e81506f455a308390c6529a6fc32079e PR #29715

**Closed** 2018-12-26 17:57 UTC
Labels: 12.0, Services

**Comment by sswapnesh** [comment] 2018-12-26 17:59
@Yenthe666  AFAIK this should be closed automatically when https://github.com/odoo/odoo/pull/29715 was merged (or @robodoo has closed that so this was still open )

**Comment by Yenthe666** [comment] 2018-12-27 12:38
Yep, it should have. Sometimes it doesn't seem to happen though, quite random.

**Comment by goyanipankaj** [comment] 2018-12-27 14:57
This issue still is Open, It's not resolve.

**Comment by sswapnesh** [comment] 2018-12-27 15:31
@goyanipankaj  Could you please add more detailed steps to reproduce (Better with screenshot)  and full trackback (With full Runbot link of that SO)?
