### ISSUE TITLE
[15.0e]Usability issue with spreadsheet with Japanese text 

### ISSUE THREAD

**Issue by kanda999** [odoo/odoo#92011] opened 2022-05-23 03:57 UTC
Impacted versions:
15.0e

Steps to reproduce:
This error occurred in Google Chrome and Microsoft Edge.
Try to type あ(which is keystroke sequence using Japanese IME: "a" )

Current behavior:
The Japanese string recognition in the spreadsheet always doesn't work
If refresh page, the same error occurs.
If input "あ"(whirch is "a") ,no text will be displayed

Expected behavior:
When input "あ"(whirch is "a") -> , output "あ".

Video/Screenshot link (optional):
![qu2fx-q3bzc](https://user-images.githubusercontent.com/101688144/169728076-509d7d44-d414-4d8d-a91e-c84d0477fc89.gif)

Support ticket number submitted via odoo.com/help (optional):
OPW #2860650

Related issue
https://github.com/odoo/odoo/issues/76133

**Comment by yostashiro** [comment] 2022-10-23 07:03
For the record, here is the reply on the OPW ticket from May 2022:

> Thanks for your feedback, we will try to take it into account for the next version of Odoo.

As of now, the issue is still there in 16.0.

**Comment by rrahir** [comment] 2022-10-29 08:38
Hi, Unfortunately, I was not able to reproduce the issue as you described it. Could you elaborate on the kind of input method you use?
On my end, I used Ubuntu's EMI equivalent (Japanese Mozc) to output Hiragana characters directly. This way I can reproduce the issue as described in https://github.com/odoo/odoo/issues/76133   We will try to find a solution for this particular behaviour but I would like to make sure that it also addresses the behaviour described in your video.

**Comment by rrahir** [comment] 2022-11-03 15:37
@yostashiro Hello :) We've come up with a fix for IME inputs. It's not merged yet but should  be rather soon. Could you confirm that it solves your issue ? https://runbot.odoo.com/runbot/bundle/15-0-spreadsheet-allow-ime-input-rar-134918

**Comment by rinaldifirdaus** [comment] 2023-04-19 13:30
I test in runbot to make sure whether this issue still exist or not. and I found that this issue already fixed, but another issue is occurring. 
https://30399761-15-0-all.runbot179.odoo.com/web#spreadsheet_id=17&cids=1&menu_id=439&action=action_open_spreadsheet

The new issue is happens when we type on spreadsheet in hiragana with following step:
1. go to document > create spreadsheet > blank
2. change your keyboard input to japanese character (hiragana or katakana).
3. Type any alphanumeric key 1 time. then in spreadsheet it will be typed 2 times

please see following video:
https://drive.google.com/file/d/1S_FeXZlKaGys7PsX16nRejW7LEyQqXaT/view?usp=sharing

**Comment by rrahir** [comment] 2023-04-21 06:27
Thanks for looking into it - we indeed still have an issue when starting to write some text from a non-edited cell.  Unfortunately, I am not sure we can properly fix in 15.0 due to the amount of changes required. We will first target the master branch and see how/if it can be easily backported

**Comment by LucasLefevre** [comment] 2023-06-16 11:55
Fixed by https://github.com/odoo/o-spreadsheet/commit/a40186aad1d2994281f7ef19b4815d8b1af448a6

**Closed by LucasLefevre** 2023-06-16 11:55 UTC
Labels: spreadsheet
