### ISSUE TITLE
Odoo Error

### ISSUE THREAD

**Issue by AntonioManuel87** [odoo/odoo#26826] opened 2018-09-06 11:30 UTC
Impacted versions: Odoo version 10

Steps to reproduce: I suppose the error comes from installing more instances of odoo on the same windows. I used the method from: https://www.odoo.com/es_ES/forum/ayuda-1/question/multiple-instances-installation-of-odoo-on-windows-89993
and create different users on pgadmin for different instances.

Current behavior: error like attachment when click on the users on settings. And when I try to create a new user nothing happens,

Expected behavior: See the dialogs when click on link.
[Odoo Odoo Client Error_1.txt](https://github.com/odoo/odoo/files/2356790/Odoo.Odoo.Client.Error_1.txt)

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2018-09-06 11:43
Sorry, but that error means nothing. You have to put JS errors with debug=assets form, and also using Windows is always a source of problems. Are you able to reproduce the problem on https://runbot.odoo.com?

**Comment by AntonioManuel87** [comment] 2018-09-06 12:02
Hello,

When I clear the cache in Firefox it gave me another error.
[Odoo Odoo Client Error_2.txt](https://github.com/odoo/odoo/files/2356900/Odoo.Odoo.Client.Error_2.txt)

And when I activate debug mode everything for now is ok. But I still want to use the user mode.

**Comment by mart-e** [comment] 2018-09-06 14:04
Hello,

If you have no error in debug=assets but errors in "normal" mode, that is most likely because of the several instances installed on the same machine. Try on another browser too (or a different firefox profile). If you have no problem, it is because of some data still in cache.

Having different databases/versions of Odoo on the same machine will only work if you make sure to access it through different URL.
Accessing it through localhost is only for the development/testing part but for production, you will want to configure a server like NGINX in between.

**Comment by Yenthe666** [comment] 2019-01-28 12:44
Closing as most likely solved thanks to the answer from Martin.

**Closed by Yenthe666** 2019-01-28 12:44 UTC
Labels: Need information
