### ISSUE TITLE
[12.0] sending timesheet reminders manually doesn't work 

### ISSUE THREAD

**Issue by mmotahar-ia** [odoo/odoo#41597] opened 2019-12-10 03:32 UTC
Impacted versions:
Odoo.sh version 12.0 latest

Steps to reproduce:
https://github.com/odoo/enterprise/blob/6a8f053cbe6fcb0454b1ffe62b5c516c39d8b569/timesheet_grid/models/res_company.py#L134

Create an employee with a user linked to it and a working day of 40hpw
Create only one entry for that employee for his last week. 
Go to scheduled action and open timesheet reminder for the employee
click on the button run manually. 
Nothing happense in the Odoo.sh staging DB and no outgoing email has been created under the settings menu. 

Current behavior:
no email sent out to employees reminding them to fill their timesheets
When we click on run manually system shows the following line in the log file.
age-727142 odoo.modules.registry: At least one model cache has been invalidated, signaling through the database.

Expected behavior:
System should send email notification to employees to fill their timesheet. 

Video/Screenshot link (optional):

**Comment by mmotahar-ia** [comment] 2019-12-10 03:34
#https://github.com/odoo/odoo/issues/25029

**Comment by pedrobaeza** [comment] 2019-12-10 08:16
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Yenthe666** [comment] 2020-03-08 19:26
I'm closing this bug report as there has been no response/feedback to the questions asked by @pedrobaeza

**Closed by Yenthe666** 2020-03-08 19:26 UTC
Labels: Need information

**Comment by shurshilov** [comment] 2023-02-21 17:22
I still get error on odoo 14 2023 CE when manual start odoo cron

**Comment by shurshilov** [comment] 2023-02-21 18:39
I found BUG!) If you run two cron at the same time that change the data in ONE model, then they will both freeze and there will be this error.

**Comment by tb25torbat** [comment] 2025-03-13 15:46
"I was looking for the same! Found this: https://apps.odoo.com/apps/modules/14.0/custom_email_reminder/"
The developer of this module may can develop into version 12.0
