### ISSUE TITLE
[10.0][11.0] Price set on document changes if quantity is changed

### ISSUE THREAD

**Issue by edsersolis** [odoo/odoo#25166] opened 2018-06-08 17:03 UTC
Impacted versions:
10.0, 11.0

Steps to reproduce:
- Create a quotation or invoice.
- Set a product in a line and set a price in-line.
- Change the quantity of the product in the line. 

Current behavior:
- After changing the quantity it will set the price back to original.

Expected behavior:
- Remain set price.

Note: the price should only change if the product is removed and added again. It makes no sense that because of a quantity change the price also changes.

**Comment by pedrobaeza** [comment] 2018-06-08 17:29
Indeed this is the intended behavior, as you can have scaled prices, and thus you need to recompute it. The usual flow is to put the product, the quantity, and then maybe change unit price...

If you don't want this flow, then customize your installation disabling that, but it's not a bug, but a feature.

Closing by these reasons.

**Closed by pedrobaeza** 2018-06-08 17:29 UTC

**Comment by edsersolis** [comment] 2018-06-09 16:02
Great, it now makes sense. Thanks!
