### ISSUE TITLE
[12] an error when i click on save and new with adding  packaged products 

### ISSUE THREAD

**Issue by AliHussJaafar** [odoo/odoo#27834] opened 2018-10-16 08:21 UTC
Impacted versions:
Odoo 12.0e+e-20181010 
windows 10 x64 bit 
Steps to reproduce:
An error when i click on save and new in the products views  
![odoo1](https://user-images.githubusercontent.com/34475900/47002363-76b75b80-d135-11e8-99b0-39af4a6af741.png)

![odoo2](https://user-images.githubusercontent.com/34475900/47002365-77e88880-d135-11e8-952c-b1909746dd21.png)

Uncaught TypeError: Cannot read property 'views' of undefined
http://localhost:8069/web/content/396-1dd2b08/web.assets_backend.js:1447
Traceback:
TypeError: Cannot read property 'views' of undefined
    at Class._processX2ManyCommands (http://localhost:8069/web/content/396-1dd2b08/web.assets_backend.js:1447:1046)
    at Class.applyDefaultValues (http://localhost:8069/web/content/396-1dd2b08/web.assets_backend.js:1287:652)
    at Object.<anonymous> (http://localhost:8069/web/content/396-1dd2b08/web.assets_backend.js:1441:13)
    at Object.<anonymous> (http://localhost:8069/web/content/385-eb76a46/web.assets_common.js:802:681)
    at fire (http://localhost:8069/web/content/385-eb76a46/web.assets_common.js:796:299)
    at Object.fireWith [as resolveWith] (http://localhost:8069/web/content/385-eb76a46/web.assets_common.js:801:198)
    at Object.deferred.(anonymous function) [as resolve] (http://localhost:8069/web/content/385-eb76a46/web.assets_common.js:803:56)
    at Object.<anonymous> (http://localhost:8069/web/content/385-eb76a46/web.assets_common.js:3587:448)
    at Object.<anonymous> (http://localhost:8069/web/content/385-eb76a46/web.assets_common.js:802:681)
    at fire (http://localhost:8069/web/content/385-eb76a46/web.assets_common.js:796:299)

**Comment by pedrobaeza** [comment] 2018-10-16 08:30
Please try to reproduce the problem on runbot (https://runbot.odoo.com - admin/admin) and give all the detailed steps to reproduce the problem.

**Comment by AliHussJaafar** [comment] 2018-10-16 08:41
Still same error on runbot 


Uncaught TypeError: Cannot read property 'views' of undefined
http://385086-master-a19eb4.runbot14.odoo.com/web/content/2014-df6780d/web.assets_backend.js:1444
Traceback:
TypeError: Cannot read property 'views' of undefined
    at Class._processX2ManyCommands (http://385086-master-a19eb4.runbot14.odoo.com/web/content/2014-df6780d/web.assets_backend.js:1444:1023)
    at Class.applyDefaultValues (http://385086-master-a19eb4.runbot14.odoo.com/web/content/2014-df6780d/web.assets_backend.js:1285:652)
    at Object.<anonymous> (http://385086-master-a19eb4.runbot14.odoo.com/web/content/2014-df6780d/web.assets_backend.js:1438:13)
    at Object.<anonymous> (http://385086-master-a19eb4.runbot14.odoo.com/web/content/2013-4d6a345/web.assets_common.js:802:681)
    at fire (http://385086-master-a19eb4.runbot14.odoo.com/web/content/2013-4d6a345/web.assets_common.js:796:299)
    at Object.fireWith [as resolveWith] (http://385086-master-a19eb4.runbot14.odoo.com/web/content/2013-4d6a345/web.assets_common.js:801:198)
    at Object.deferred.(anonymous function) [as resolve] (http://385086-master-a19eb4.runbot14.odoo.com/web/content/2013-4d6a345/web.assets_common.js:803:56)
    at Object.<anonymous> (http://385086-master-a19eb4.runbot14.odoo.com/web/content/2013-4d6a345/web.assets_common.js:3587:448)
    at Object.<anonymous> (http://385086-master-a19eb4.runbot14.odoo.com/web/content/2013-4d6a345/web.assets_common.js:802:681)
    at fire (http://385086-master-a19eb4.runbot14.odoo.com/web/content/2013-4d6a345/web.assets_common.js:796:299)


First go to Sales > Configuration > Setting > enable Product Packaging  and unit of measures 
then go to Sales > Orders > Quotation > Create 

try to add a new product a pop up view will appear pick any product and click on save and new 
error

**Comment by pedrobaeza** [comment] 2018-10-16 08:42
Please don't use master branch, but a stable one.

**Comment by AliHussJaafar** [comment] 2018-10-16 08:47
still same error on ver 12  runbot17 

Uncaught TypeError: Cannot read property 'views' of undefined
http://385071-12-0-661483.runbot17.odoo.com/web/content/2015-1726620/web.assets_backend.js:1445
Traceback:
TypeError: Cannot read property 'views' of undefined
    at Class._processX2ManyCommands (http://385071-12-0-661483.runbot17.odoo.com/web/content/2015-1726620/web.assets_backend.js:1445:1023)
    at Class.applyDefaultValues (http://385071-12-0-661483.runbot17.odoo.com/web/content/2015-1726620/web.assets_backend.js:1285:652)
    at Object.<anonymous> (http://385071-12-0-661483.runbot17.odoo.com/web/content/2015-1726620/web.assets_backend.js:1439:13)
    at Object.<anonymous> (http://385071-12-0-661483.runbot17.odoo.com/web/content/2014-39f4fce/web.assets_common.js:802:681)
    at fire (http://385071-12-0-661483.runbot17.odoo.com/web/content/2014-39f4fce/web.assets_common.js:796:299)
    at Object.fireWith [as resolveWith] (http://385071-12-0-661483.runbot17.odoo.com/web/content/2014-39f4fce/web.assets_common.js:801:198)
    at Object.deferred.(anonymous function) [as resolve] (http://385071-12-0-661483.runbot17.odoo.com/web/content/2014-39f4fce/web.assets_common.js:803:56)
    at Object.<anonymous> (http://385071-12-0-661483.runbot17.odoo.com/web/content/2014-39f4fce/web.assets_common.js:3587:448)
    at Object.<anonymous> (http://385071-12-0-661483.runbot17.odoo.com/web/content/2014-39f4fce/web.assets_common.js:802:681)
    at fire (http://385071-12-0-661483.runbot17.odoo.com/web/content/2014-39f4fce/web.assets_common.js:796:299)

**Comment by pedrobaeza** [comment] 2018-10-16 09:08
But you are not indicating the detailed steps to reproduce the error.

**Comment by AliHussJaafar** [comment] 2018-10-16 09:10
@pedrobaeza  

First go to Sales > Configuration > Setting > enable Product Packaging and unit of measures
then go to Sales > Orders > Quotation > Create

try to add a new product a pop up view will appear pick any product and click on save and new
error

any more information needed ?

**Comment by pedrobaeza** [comment] 2018-10-16 09:14
Which product? Is with any of the possible products?

**Comment by AliHussJaafar** [comment] 2018-10-16 09:18
i ve tried this with almost all  kind of products with different options (ex. purchasable  , manufactured , new product created directly ... )

**Comment by pedrobaeza** [comment] 2018-10-16 10:51
OK, I see, thanks for the details. It seems a problem with popup view. @ged-odoo maybe this is the problem with fields not added in subviews?

**Comment by sswapnesh** [comment] 2018-10-16 14:00
Duplicate of https://github.com/odoo/odoo/issues/27409

**Comment by pedrobaeza** [comment] 2018-10-16 14:06
Thanks for the link. I close this one then.

**Closed by pedrobaeza** 2018-10-16 14:06 UTC
Labels: 12.0, Framework
